{100}{}{Das ist ein Biker.}
{101}{}{Du siehst einen knallharten Biker. Ihm ist alles egal.}

#Attempt to talk
{110}{}{Alter, hier gibt's keine Fremden!}
{111}{}{Au, mach dich vom Acker!}
{112}{}{Verschwinde, du Grünschnabel, ich hab keine Zeit für sowas.}
{113}{}{Was glotzt du so?}
{114}{}{Willst du mich beißen?}
{115}{}{::rülpst::}
{116}{}{Verdammt, heute bin ich schlecht gelaunt.}
{117}{}{Mach den Mund auf, und ich knall dich ab!}
{118}{}{Verdammt, Leute. Schon wieder einer!}
{119}{}{Kommt uns in den Bars nicht in die Quere, wir machen da gern Ärger.}
{120}{}{Ich habe Jay Kukish schon lange nicht mehr gesehen.}

#Pop-up dialogue
{200}{}{Einmal mit dem Chopper fahren, und du willst nie wieder mit deinen Stiefeln durchs Ödland stapfen ...}
{201}{}{Das Auto trägt den Körper, aber das Bike trägt die Seele ...}
{202}{}{Der Herr hat sich nicht geirrt, als er den stählernen Vogel gegen das eiserne Ross eintauschte ...}
{203}{}{Lebe, um zu fahren, fahre, um zu leben ...}
{204}{}{Wir sind die Teufel auf Rädern!}
{205}{}{Die beste Musik ist das Dröhnen unserer Motoren.}
{206}{}{Benzin hat in unseren Adern schon lange das Blut ersetzt ...}
#{206}Das Blut in unseren Adern wurde schon lange durch benzin ersetzt.
#{206}In unseren Adern fließt schon lange Benzin.
{207}{}{Unsere Essenz ist Brutalität, unser Gott ist Technik.}

#Female character:
{1110}{}{Mädel, hier sind doch alle unter Freunden!}
{1111}{}{Au, mach dich vom Acker!}
{1112}{}{Hau ab, du Pferd, ich hab keine Zeit für so was.}
{1113}{}{Was glotzt du so?}
{1114}{}{Willst du an mir lutschen?}
{1115}{}{::rülpst::}
{1116}{}{Verdammt, heute bin ich schlecht gelaunt.}
{1117}{}{Mach einfach den Mund auf, und ich knall dich ab!}
{1118}{}{Verdammt, Leute. Schon wieder einer!}
{1119}{}{Legt euch in den Bars nicht mit uns an, dort machen wir gern Ärger.}
{1120}{}{Ich habe Jay Kukish schon lange nicht mehr gesehen.}