{100}{}{Du siehst einen Karawanenhändler.}
{101}{}{Du siehst einen Karawanenführer.}
{102}{}{Danke, Fremder. Wir sehen uns in Black Rock!}
{103}{}{Haltet die Stellung! Sie sind nah!}

{110}{}{Hätte nicht erwartet, hier noch jemanden zu sehen. Lass mich raten – du warst unterwegs und hast dich um deinen eigenen Kram gekümmert, als plötzlich aus dem Nichts ein hässlicher, hirnloser Raider-Bastard mit einem Gesicht wie ein Gecko, einer Stimme wie eine nasse Ratte und dem Geruch von beidem zusammen mit einem halben Dutzend seiner Raider-Kumpane auftauchte, dir eine Knarre an den Kopf hielt und dich aufforderte, hier reinzukommen und uns herauszulocken. Bin ich nah dran?}
{111}{}{Mehr oder weniger, ja.}
{112}{}{Raider? Da draußen gibt's keine Raider!}

{113}{}{Diese schleimigen, rückgratlosen Hurensöhne! Willkommen in der Falle, Fremder.}
{114}{}{Falle?}

{115}{}{Ach ja? Du warst also gerade auf der Durchreise und hast beschlossen, ohne jeden Grund in irgendeine modrige Höhle zu gehen, was?}
{116}{}{Ich bin den ganzen Tag auf den Beinen. Ich hab nur nach einem Plätzchen gesucht, um ein Nickerchen zu machen.}
{117}{}{Das war ironisch gemeint. Die Raider sind direkt draußen.}

{118}{}{Entschuldige, wenn ich das für verdammt unwahrscheinlich halte! Aber gut – so machen wir's. Wir gehen nach draußen, du direkt neben mir, und sehen, was passiert. Und wenn du irgendwelche Faxen machst, wird das, was ich dann mit dir anstelle, *zum Schreien komisch*. Hol mich, wenn du bereit bist aufzubrechen.}
{119}{}{Na schön, ich bin gleich wieder da.}
{120}{}{Sag mir zuerst, was hier passiert ist.}

{121}{}{Was wir hier haben, ist ein verdammtes Chaos. Der andere Ausgang ist versperrt, unsere Vorräte gehen zur Neige und am schlimmsten ist, dass ich hinter dem Zeitplan liege. Ich HASSE es verdammt noch mal, zu spät zu kommen! Jetzt heißt es alles oder nichts, und sterben hab ich nicht vor. Wie kommen wir hier verdammt noch mal raus?}
{122}{}{Wie ist das passiert?}
{123}{}{Lass mich nachdenken.}

{124}{}{Schon irgendwelche Ideen, Fremder?}
{125}{}{Wir kamen aus Reno, um ein paar Gecko-Felle abzuholen. Wir waren auf dem Weg durch die Berge, aber irgendwas fühlte sich nicht richtig an. Wir holten das Fernglas raus, um uns umzusehen, und siehe da: Die Raider hatten nicht mal ihre Lagerfeuer gelöscht. Reine Anfänger, dachte ich mir. Zum Glück kannte ich eine Höhle, die quer durch den Berghang führte. Wir mussten die Karawane nur hindurch und auf der anderen Seite wieder rausbringen, und die Raider hätten nicht mal gewusst, dass wir da waren. Clever von mir, was?}
{126}{}{Was ist dann passiert?}
{127}{}{Wie sich herausstellte, wussten sie auch von der Höhle. Scheiße, wir sind ihnen direkt in die Falle gelaufen! Kurz nachdem wir durch waren, sprengten sie die Höhle hinter uns und verschütteten den Tunnel. Durch den Schutt kommen wir verdammt noch mal nicht durch. Ich weiß nicht, ob sie das von Anfang an geplant hatten oder einfach Glück hatten, aber jetzt ist es auch egal. Es gibt nur einen Ausgang – sie müssen bloß warten. Entweder kommen wir raus und sie erschießen uns, oder wir bleiben hier sitzen und verhungern.}
{128}{}{Eine unangenehme Geschichte.}
{129}{}{Die Raider sind alle tot. Du kannst jetzt rauskommen.}

{130}{}{Na schön, sehen wir uns das mal an. Aber wenn du mich verarschst ...}
{131}{}{[Warten]}
{132}{}{Verdammt noch mal, Junge! Du hast das alles erledigt? Verdammte Meisterleistung! Jetzt können wir diesen Ort endlich verlassen. Such mich in Black Rock - das Bier geht auf mich!}
{133}{}{Wir sehen uns dort.}

{134}{}{Die Raider müssen abgehauen sein. Wir sollten verschwinden, bevor sie zurückkommen.}
{135}{}{Klar, lass uns gehen.}
{136}{}{Ich muss nur kurz, äh, pinkeln. Geh schon mal vor.}

#Female character
{1102}{}{Danke, Fremder. Wir sehen uns in Black Rock!}
{1115}{}{Ach ja? Du warst also gerade auf der Durchreise und hast beschlossen, ohne jeden Grund in irgendeine modrige Höhle zu gehen, was?}
{1132}{}{Verdammt noch mal, Mädchen! Du hast das alles erledigt? Verdammte Meisterleistung! Jetzt können wir diesen Ort endlich verlassen. Such mich in Black Rock - das Bier geht auf mich!}
