{100}{}{Du siehst einen Wachmann.}
{101}{}{Du siehst einen Karawanenwächter.}

#Ïîñëå ñïàñåíèÿ
{110}{}{Ist es wirklich vorbei? Ich kann es nicht glauben!}
{111}{}{Ich dachte, ich würde in dieser Höhle ganz sicher sterben!}
{112}{}{Du hast uns den Arsch gerettet! Danke!}

#Äî ñïàñåíèÿ
{120}{}{Wir sitzen hier fest, aber sie kommen nicht an uns ran. Eine Pattsituation.}
{121}{}{So eine Lage hatten wir noch nie.}
{122}{}{Wir hätten nicht so weit kommen sollen, nur wegen dieser verdammten Felle!}
{123}{}{Diese Banditen haben Mist gebaut - sie hatten uns in der Falle, aber können nichts damit anfangen.}
{124}{}{Wir sind hergekommen, um Felle zu kaufen. Jetzt werden wir mit unseren eigenen bezahlen.}
{125}{}{Meine Güte, wie viele Leute wollen die Raider hier noch einsperren?}
{126}{}{Es sieht nicht gut aus. Wir haben gerade unser letztes Ersatz-brahmin verbraucht.}
{127}{}{Wenn wir hier jemals rauskommen, müssen wir mehr brahmin in Black Rock kaufen.}

{130}{}{RAIDER! Sie sind hier!}
{131}{}{Was? Ich bin kein Raider!}
{132}{}{Raider? Wo?!}
{133}{}{Du musst nicht schreien. Ich bin direkt hier.}

{134}{}{Warte, du gehörst nicht zu ihnen. Was machst du hier?}
{135}{}{Ich will nur reden.}
{136}{}{Ist das irgendein Trick? Ach, scheiß drauf - wir haben sowieso nichts zu verlieren. Wer auch immer du bist, du solltest mit dem Boss reden. Er ist direkt hinter mir.}
{137}{}{Kein schlechter Anfang ...}
