{100}{}{Du siehst ein Mädchen mit einem kurzen Irokesenschnitt.}
{101}{}{Auf den ersten Blick sieht dieses Mädchen wie ein sehr wildes (und sehr sexy) Tier aus.}

{110}{}{Howdy, Cowboy.}
{111}{}{}
{112}{}{Wer seid ihr Leute?}
{113}{}{Warum bist du allein in Gesellschaft von Männern hier?}
{114}{}{Howdy. Und tschüss.}

#who are bikers answer
{115}{}{[Sie macht ein sehr überraschtes Gesicht] Das sind Biker. Siehst du das nicht?!}
{116}{}{Ich weiß nur nicht, wer Biker sind. Erzähl mir von eurer Bande.}
{117}{}{Verstehe. Schon gut.}
{118}{}{Ha-ha! Aus welchem Loch bist du denn gekrochen, wenn du nichts über Biker weißt? Na gut, ich kann's dir wohl erzählen ... Unsere Jungs fahren durchs Ödland und suchen nach funktionierender Technik. Die verkaufen sie dann in den Städten. Weil sie sich so für Technik begeistern, kennen sie sich mit Reparaturen aus. Deshalb kommen immer wieder wichtige Gangster vorbei, um uns ein gutes Angebot zu machen.}
{119}{}{Vorkriegstechnologie? Interessant. Wo bekommen sie die her?}
{120}{}{In verlassenen Stadtvierteln oder Militärstützpunkten. Wenn du mich fragst, ist das ein ziemlich gefährliches Leben.}
{121}{}{Was soll daran gefährlich sein, im Muell nach alten Kabeln und schmutzigen Toastern zu wühlen?}
{122}{}{Weißt du, das Ödland ist randvoll mit seltsamen Kreaturen, besonders in den Wüstengebieten. Viele Leute, die ihr Leben in Städten verbringen, wissen nicht einmal von ihnen. Und wir laufen ihnen ständig über den Weg! Außerdem können dir all die alten Gebäude in verlassenen Stadtvierteln auf den Kopf fallen, wenn du nicht gut genug aufpasst. Also ja, es ist ziemlich gefährlich.}
{123}{}{Verstehe. Wie lange machst du das schon?}
{124}{}{Ich? Mein ganzes Leben lang! Und die anderen schon doppelt so lange!}
{125}{}{Doppelt so lange? Wie alt bist du denn?}
{126}{}{Fünfzehn. Na und?}
{127}{}{Wow! Also ... ich ... Hmm ... Na gut, schon vergessen.}
{128}{}{Jaa. Wo kommen Leute wie du überhaupt her ... Schon gut.}
{129}{}{Okay. Bis dann.}

#answer - what is she doing here
{130}{}{Na ja, ich bin hier, weil es mit den Jungs mehr Spaß macht als irgendwo sonst. Und viel sicherer ist.}
{131}{}{Sie sehen für mich nicht gerade wie Verteidiger der Unschuldigen aus. Eher wie jemand, der gern randaliert und ordentlich austeilt.}
{132}{}{Okay, ich verstehe. Lass mich dich etwas anderes fragen.}
{133}{}{Na klar! Aber das ist doch cool! Und außerdem, was ist das Problem? Sie werden vielleicht ein bisschen betrunken, ja, und dann hältst du dich besser von ihnen fern, aber die Leute lieben sie! Weil sie cool sind!}
{134}{}{Ja, klar. In der Bar Leute zu verprügeln ist nicht besonders cool, vor allem, wenn man der Wirt ist.}
{135}{}{Quatsch! Wirte *freuen sich immer* über die Gesellschaft von Bikern, und wir *verstehen uns immer* gut mit ihnen.}
{136}{}{Ach ja? Interessant. Und was ist mit dem Chaos, das sie anrichten? Und den Schäden?}
{137}{}{Die anderen Gäste zahlen für die Schäden. Ist dir klar, wie viele Leute nur deshalb in diese Lokale kommen, um zuzusehen, wie jemand verprügelt wird? Die Wirte profitieren davon, und nach solchen Schlägereien wird ihr Laden nur noch besser.}
{138}{}{Ein interessanter Punkt ... Meinst du das ernst?}
{139}{}{Äh, ja. Ist das so überraschend?}
{140}{}{Nun, ja.}
{141}{}{Nicht wirklich.}

{142}{}{Iih. Aus welchem Loch bist du denn gekrochen, Cowboy?}
{144}{}{Aus dem Vault im Westen.}
{145}{}{Ich bin aus keinem Loch gekrochen. Ich will einfach mein Leben als anständiger Mensch leben und nicht als Abschaum wie du.}
{146}{}{Ich bin aus keinem Loch gekrochen ... Weißt du was, eigentlich stimmt das zum Teil.}
{147}{}{Ich komme aus einer normalen postapokalyptischen Gesellschaft.}
{148}{}{Hast du je daran gedacht, dass eine „postapokalyptische Gesellschaft“ nicht automatisch etwas Normales ist?}
{149}{}{Äh ... Du hast wohl recht.}
{150}{}{Genau.}
{151}{}{Okay, vergiss es.}

{152}{}{Was?! Leute, dieses Stinktier wagt es, schlecht über uns zu reden!}
{153}{}{}
{154}{}{Hey! Moment mal! Sie hat nicht verstanden, was ich gesagt habe! Ich ehrlich gesagt auch nicht ...}
{155}{}{Ach, wirklich? Verteidigt euch, ihr verdammten Anarchisten!}
{156}{}{Unsere Leute lassen dich mit diesem Scheiß nicht davonkommen. Halt die verdammte Klappe und wag es bloß nicht, wegen unseres brotherhood rumzuquieken. Wir sind *frei* und unabhängig. Das wirst du nie kapieren.}
{157}{}{Na gut, du bist der Boss ...}

{158}{}{Wirklich?!}
{159}{}{Ja. Ich habe sogar meinen Pass dabei. Hier, sieh ihn dir an.}
{160}{}{Ja. Ich kann dir sogar die Koordinaten zeigen.}
{161}{}{Ja. Ich meine es ernst.}
{162}{}{Das ist ja abgefahren! Wenn das stimmt ... Weißt du, du solltest unserem Anführer davon erzählen. Er liebt Technik und würde sich *sehr* freuen, deinen Vault zu besuchen.}
{163}{}{Ich überleg's mir.}

#where are you from?
{170}{}{Woher kommst du?}
{171}{}{Aus Vegas. Warum fragst du?}
{172}{}{Du bist ganz schön weit von zu Hause weg ...}
{173}{}{Mach dir keine Gedanken darum.}

{174}{}{Ich würde überall in Amerika hingehen, solange ich mit Phil und seinen Kumpels zusammen bin!}
{175}{}{Haben deine Eltern dir erlaubt, mit diesen Typen in der Wüste herumzuhängen?}
{176}{}{Kann man sich auf sie verlassen?}
{177}{}{In Ordnung.}

{178}{}{Ich habe nicht um ihre Erlaubnis gebeten.}
{179}{}{Diese Biker – kann man sich auf sie verlassen?}
{180}{}{Wir reden später weiter.}
{181}{}{Die sind großartig! Bei ihnen merkt man richtig, dass man frei ist. Sie verurteilen dich nicht oder so, du kannst einfach du selbst sein, weißt du?}
{182}{}{Na gut. Ich wollte dich noch etwas anderes fragen.}
{183}{}{Wie behandeln sie dich?}
{184}{}{Besser geht's nicht. Nur sie können mir all das Glück der Welt geben. Ich zögere nicht mal, mit ihnen ein paar Bier zu kippen. Wenn ich zu Hause wäre, würden meine Eltern mir den Arsch aufreißen, nur weil ich auch nur ans Biertrinken denke. }
{185}{}{Ha! Sind sie also einfach nur Säufer?}
{186}{}{Nein, aber sie genießen immer ein gutes Bier ... Trotzdem basteln sie lieber an dreckiger Technik herum. Aber wenn man beides kombiniert ... Oh, das ist ein richtiges Fest!}

#Vegas Family quest
{200}{}{Hey, bist du von zu Hause in Vegas weggelaufen? Deine Eltern suchen dich überall ...}
{201}{}{[Seufzt] Lass sie. Ich gehe nicht zu ihnen zurück.}
{202}{}{Du machst einen Fehler. Sie haben dich all die 15 Jahre deines Lebens unterstützt ...}
{203}{}{Ich will deinen Scheiß nicht hören! Pack deine Sachen und mach dich bereit für die Heimreise!}
{204}{}{Warum bist du vor ihnen weggelaufen?}
{205}{}{Wie auch immer. Wie du willst.}

{206}{}{Na, sieh sich einer Mr. Tugendbold an! Ugh, ich kann dein Gesicht nicht ausstehen. Hör zu, Kumpel, ich liebe meine Freiheit zu sehr, um sie wegen irgendwelcher Prinzipien aufzugeben.}
{207}{}{Na, sieh sich diesen kleinen Rebellen an! Geh nach Hause, SOFORT!}
{208}{}{Was für ein Ärger. Hau ab und kümmere dich um deinen eigenen Kram.}
{209}{}{Du kleiner ... Ich finde schon einen Weg, dich zu deinen Eltern zurückzubringen!}
{210}{}{Na gut, vielleicht änderst du irgendwann deine Meinung.}

{211}{}{Von wegen. Sie haben mich ständig gezwungen, langweiligen Scheiß zu machen. „Benimm dich, lern schreiben, bla bla bla.“ Wenn ich Phil und seine Jungs nicht getroffen hätte, wäre ich in diesem glänzenden Drecksloch von einer Stadt vor Langeweile gestorben.}
{212}{}{„Glänzendes Drecksloch“? Vegas? Echt jetzt?}
{213}{}{Was? Vegas sieht nett aus, aber es ist auf Lügen gebaut, mit Betrug zementiert ... Na gut! Hör auf, mich mit diesen verdammten Fragen zu nerven! Ich gehe sowieso nicht zurück.}
{214}{}{Warum nicht? Dort fühle ich mich wie hinter Gittern. Morgens zur Arbeit gehen, abends von der Arbeit zurückkommen. Wer könnte so ein Leben jemals schätzen?}
{215}{}{Du wurdest also einfach ausgebeutet, oder?}
{216}{}{Na, na, du willst also einfach nicht deinen Lebensunterhalt verdienen, stimmt's?}
{217}{}{Du solltest auf deine Eltern hören, du kleiner Rotzlöffel. Pack deine Sachen und geh zurück zu deiner Familie!}
{218}{}{Ganz genau! Ich bin erst fünfzehn! Jeden Samstagabend hab ich im „Hard Rock Cafe“ gefeiert. Dort hab ich die Biker kennengelernt. Als meine Eltern davon erfuhren, verbot mir mein Dad, wieder zu diesen Partys zu gehen. Er ist so ein Langweiler, ihn interessiert nur seine Arbeit und sonst nichts.}
{219}{}{Warum denn? Hatte er Angst, die Biker könnten dich in Schwierigkeiten bringen?}
{220}{}{Und ich bin seiner Entscheidung einer Meinung. Kinder sollten sich niemals auf solche zwielichtigen Partys einlassen.}
{221}{}{Nun, wir kommen aus Clear City! Mein Vater klammert sich so sehr an seinen Posten im Rathaus, dass er nicht einmal die Stadtgrenze verlassen will, um mich zu suchen! Ich will nicht so sauber sein und mich benehmen, als wäre ich etwas Besseres als alle anderen. Biker sind meine besten Freunde, und ich werde sie niemals verlassen!}
{222}{}{Weißt du, mit deinen Freunden hast du recht. Du hättest deinen Vater einfach davon überzeugen sollen, dass sich ein freies Leben mit einem Job an einem angesehenen Ort vereinbaren lässt. Mehr ist es nicht.}
{223}{}{Das glaube ich nicht. Deine Familie ist wichtiger, verstehst du? Es sind deine Eltern, und sie machen sich Sorgen um dich. Sie haben sogar mich angeheuert, damit ich dich finde. Ist das nicht der beste Beweis dafür, dass sie dich lieben?}
{224}{}{Na schön, Schluss mit diesem kindischen Unsinn! Du hättest schon vor langer Zeit eine ordentliche Tracht Prügel verdient! Pack deinen Scheiß und mach dich bereit, nach Hause zu gehen, SOFORT!}
{225}{}{Verdammt, ich weiß nicht. Ich muss darüber nachdenken.}
{226}{}{Meine *Familie* ist nichts weiter als ein Paar Wärter in diesem Gefängnis namens „Zuhause“. Ich kann nicht mal aufs Klo gehen, ohne dass man mich überwacht. Kaum bin ich draußen, höre ich schon eine Stimme an meinem Ohr: „Wo gehst du hin?“ Also ja, Familie ist Familie, das stimmt, aber meine Freiheit ist mir wichtiger. Ich werde sie nicht vermissen ...}
{227}{}{Wirklich? Du klingst nicht überzeugt genug. Ich merke, dass du dich unwohl fühlst.}
{228}{}{Hmm, na ja, vielleicht hast du recht. Aber du solltest wissen, dass deine Familie sich große Sorgen um dich macht. Denk daran.}
{229}{}{Ach, halt die Klappe, verdammt noch mal! Ich kenne meine Eltern besser als du!}
{230}{}{Vielleicht. Aber ich weiß besser, was mit ihnen passiert ist, nachdem du gegangen bist.}
{231}{}{[Ihre Augen weiten sich] Wa... Was ist passiert?!}
{232}{}{Siehst du! Du machst dir Sorgen. Sie sind dir doch nicht egal, oder?}
{233}{}{Verdammt! Ist dir klar, was ich dir für so einen Scherz antun könnte? ...}
{234}{}{Keine Sorge, deinen Eltern geht es gut, abgesehen davon, dass sie völlig fertig sind.}
{235}{}{Ja, ja, komm schon, denk dir noch mehr Geschichten aus.}
{236}{}{Ich meine es ernst! Dein Vater sah furchtbar aus. Müde, dunkle Ringe unter den Augen. Er kann nicht schlafen, weil er nicht weiß, wo du bist. Ich glaube, mit deiner Rücksichtslosigkeit bringst du ihn noch ins Grab.}
{237}{}{Ist das wahr?... [Das Mädchen stolpert kurz, dann versucht sie, sich zu sammeln] aber... ich...}
{238}{}{Zögere nicht. Sie werden sich immer freuen, dich zu sehen, auch wenn du bei deinen Freunden bleiben willst. Besuch sie einfach ab und zu, damit sie sich nicht zu viele Sorgen machen.}
{239}{}{Na ja... Versprechen kann ich nichts. Wir werden sehen.}
{240}{}{Ich weiß nicht, was ich tun soll... Ich... Äh, verdammt. Na gut! Wenn Phil nächste Woche nach Vegas fährt, komme ich mit ihm. Hoffentlich gehe ich ihm nicht zu sehr auf die Nerven... Ich sehe nach, wie es ihnen geht, und komme zurück.}
{241}{}{Das ist doch schon was. Also gut. Bis dann.}

{242}{}{Sieht so aus, als hättest du das Mädchen überreden können, zumindest vorübergehend zu ihren Eltern zurückzukehren.}

{243}{}{[Das Mädchen erschaudert] Ich glaube, du würdest dich im Bürgermeisterbüro von Vegas ganz gut machen, zusammen mit diesen Anzug tragenden Bastarden. Hau ab!}
{244}{}{Na gut, na gut, na gut. Wie du willst...}
{245}{}{Aber was soll ich deinen Eltern sagen?}
{246}{}{Was auch immer. Ist mir jetzt egal.}
{247}{}{Also kann ich ihnen sagen, dass du tot bist?}
{248}{}{Hmm. Wenn du nicht zurückwillst, soll ich deinen Eltern vielleicht etwas von dir ausrichten?}
{249}{}{Na gut, ich lasse dich in Ruhe.}
{250}{}{Hey, das ist eigentlich eine gute Idee! Vielleicht hören sie dann auf, Söldner nach mir zu schicken... Und Babysitter wie dich.}
{251}{}{Wir brauchen einen Beweis, dass es dir gut geht. Wie wäre es mit einem persönlichen Gegenstand?}
{252}{}{Weißt du, ich finde, das geht ein bisschen zu weit. Da mache ich nicht mit.}

{253}{}{Ich habe dieses Medaillon mit meinem Foto drin. Das ist das Einzige, was mir aus meinem früheren Leben geblieben ist.}
{254}{}{Gib mir das Medaillon. Ich bringe es deinen Eltern.}
{255}{}{Weißt du, ich finde, das geht ein bisschen zu weit. Da mache ich nicht mit.}
{256}{}{[Nimmt das Medaillon ab und betrachtet es mit nostalgischem Blick] Warte... Lass mich es noch ein letztes Mal ansehen...}
{257}{}{Hör auf, herumzutrödeln, und gib mir das Medaillon. Ich habe noch anderes zu erledigen.}

#Female lines:
{1110}{}{Na, Mädchen.}
{1118}{}{Ha-ha! Aus welchem Loch bist du denn gekrochen, wenn du nichts über Biker weißt? Na gut, ich kann's dir wohl erzählen ... Unsere Jungs fahren durchs Ödland und suchen nach funktionierender Technik. Die verkaufen sie dann in den Städten. Weil sie sich so für Technik begeistern, kennen sie sich mit Reparaturen aus. Deshalb kommen immer wieder wichtige Gangster vorbei, um uns ein gutes Angebot zu machen.}
{1142}{}{Igitt. Aus welchem Loch bist du denn gekrochen, Cowgirl?}
{1152}{}{Was?! Leute, diese Schlampe hier bettelt darum, ordentlich den Arsch versohlt zu bekommen!}
{1206}{}{Seht euch diese Frau Tugendbold an! Ugh, ich kann dein Gesicht nicht mal ertragen. Hör zu, Fräulein, ich liebe meine Freiheit viel zu sehr, um sie wegen der Prinzipien anderer aufzugeben.}
{1239}{}{Na ja... Versprechen kann ich nichts. Wir werden sehen.}
