{100}{}{Du siehst Bob, den Totengräber.}
{101}{}{Du siehst einen schmutzigen, zotteligen Mann in alten, zerfetzten Kleidern.}

#Starting conversation
{110}{}{[Du siehst einen schmutzigen Dorfbewohner, der nach Schweiß und Alkohol stinkt. Sein Kopf, kaum von langen, dünnen Haarsträhnen bedeckt, sieht seltsam aus; es ist, als hätte man ihn bei der Geburt mit einer Zange am Kopf herausgezogen, und als er die Welt sah, in der er leben müsste, klammerte er sich an alles, was er finden konnte, um sich von ihr fernzuhalten.]}
{111}{}{Ähm, entschuldige, wer bist du?}
{112}{}{Steh nicht einfach so rum, Zottel! Sagst du jetzt Hallo, oder was?}

{113}{}{[Er springt auf und dreht sein schmutziges Gesicht mit weit aufgerissenem Mund zu dir. Dabei zeigt er einen gelben Zahn, vielleicht den einzigen, den er hat.] Oh, du meine Güte! W-warum musstest du mich so ersch-schrecken?}
{114}{}{Tut mir leid, das war nicht meine Absicht. Kommt nicht wieder vor.}
{115}{}{Hör auf zu zittern, Feigling. Ich habe dir eine Frage gestellt.}

{116}{}{Äh, ähm ... Ich bin Bob, der örtliche Totengräber und T-Tischler. Ich bin n-niemand Beson-deres.}
{117}{}{Mein Name ist }
{118}{}{. Freut mich, dich kennenzulernen, Bob, Totengräber.}
{119}{}{Da bin ich anderer Meinung, du bist etwas ganz Besonderes. Von all den Freaks in diesem Dorf bist du mit Abstand der größte Freak.}

{120}{}{[Ein paar Sekunden lang starrt er dich teilnahmslos an, dann streckt er dir seine schlammige Hand entgegen und grinst breit mit seinem zahnlosen, schmutzigen Mund.] O-o-oh, es ist so schön, einen n-netten Menschen kennenzulernen! [Er schaut sich mit Scham in den Augen um.] T-tut mir leid wegen der Unordnung. Ich b-bekomme sonst keine Besucher.}
{121}{}{Mach dir keine Sorgen. Kannst du ein paar Fragen beantworten?}

{122}{}{[Er murmelt etwas Unverständliches in seinen Bart.] ...Wie alle. Warum sollten sie ... Diese widerlichen kleinen ...}
{123}{}{Murmel mich nicht voll. Ich brauche Antworten, und mit dir zu reden ist schon unangenehm genug.}

{124}{}{I-ich weiß n-nichts. Ich mache nur S-Särge. Und ... und grabe G-Gräber ...}
{125}{}{Dann verschwende ich hier meine Zeit. Ich verschwinde.}
{126}{}{Dann hast du doch sicher Zeit zum Reden, oder?}

#Reaction when digging the graves
{130}{}{H-Hey! B-Bist du derjenige, der die Gräber ausraubt?}
{131}{}{Wer, ich? Nein, das würde ich nie tun.}
{132}{}{Wenn du jemandem davon erzählst, plündere ich als Nächstes deine Leiche. Verstanden?}

#Second conversation
{150}{}{Hä, was?}
{151}{}{Nichts, beruhig dich.}

{152}{}{Was ist das für ein widerlicher Gestank?}
{153}{}{Fühlst du dich nicht einsam, hier draußen ganz allein?}
{154}{}{Erzähl mir von Black Rock.}
{155}{}{[Er sieht sich um und schnuppert dann an seiner schmutzigen Kleidung.] Oh ... Ich bin's wohl ...}
{156}{}{Ich ... Ich mag keine Menschenmengen, und, äh ... Die Leute sind nicht gern in der Nähe eines Totengräbers. So ist das einfach ...}
{157}{}{Äh ... Ich weiß nicht ... Es ist friedlich. Justin will niemanden hereinlassen, aber ... Aber so sind wir alle hierhergekommen.}

#About Jed
{160}{}{Für wen ist der Sarg draußen?}
{161}{}{[Er seufzt zittrig.] Er ist für ... für Jed. Er hat gesagt, er wird bald sterben. Aber das sagt er schon lange. Normalerweise wickeln wir die Toten einfach in Lumpen, aber Smith ist ... Smith ist etwas Besonderes.}
{162}{}{Reden wir über etwas anderes.}

{163}{}{Smith, du bist von weit hergekommen, um hierher zu gelangen, und nun wirst du für immer hierbleiben.}
{164}{}{Dieser Ort hat versucht, dir zu schaden, aber ...}
{165}{}{... aber du hast ihn bezwungen. Und ... hier ein neues Leben begonnen.}
{166}{}{Wir werden dich nie vergessen.}
{167}{}{Ruhe in Frieden. Du hast es verdient.}

{168}{}{Und jetzt ab in die Bar!}
{169}{}{Sieht aus, als wäre Jed tot.}
{170}{}{Was ist mit Smith passiert?}
{171}{}{Es wa ... Es war ein ganz normaler Tag. Normales Wetter. Er war draußen und schaute zum Himmel hinauf, und ... und dann ... ist er einfach eingeschlafen. [Er wischt sich mit einem schmutzigen Ärmel die Augen.] Oh Mann, er ... Er war der einzige Mensch, den ich je gesehen habe, der eines natürlichen Todes gestorben ist.}

#Ïðî Æàñìèí
{180}{}{Was hältst du von Jasmine?}
{181}{}{[Er lächelt schief] Sie... Also, sie ist... S-sie ist ein gutes Mädchen. Ich würde mit ihr reden, aber... Aber ich habe Angst. Sie ist ansteckend. Was würden die L-Leute sagen? Nein, ich... Ich bin gern allein.}
{182}{}{Würdest du gern mit ihr zusammenleben?}

{183}{}{Ich?! Oh, ja! Ja, das würde ich liebend gern!}
{184}{}{Ich behalte das im Hinterkopf.}

{185}{}{Ich möchte mit dir über Jasmine sprechen.}
{186}{}{Ich hab dir doch gesagt, es... Es wäre möglich, wenn sie nicht k-krank wäre.}
{187}{}{Wirklich? Ohh, das ist unangenehm. Sie hat mir erzählt, sie glaubt, deine Mutter hätte sich bei deiner Geburt vollgeschissen und dabei den falschen Haufen behalten, dass du die Leichen vergewaltigst, die du bekommst, und ihre Überreste isst, und dass man sie in Reno gezwungen hat, Hunde zu ficken, du ihr aber geholfen hast, darüber hinwegzukommen, weil ihr der Gedanke, dich anzufassen, alles andere in Perspektive rückt.}
{188}{}{Ich habe ihre Infektion geheilt. Sie möchte eine Familie gründen, Bob. Hast du Interesse?}
{189}{}{Na gut, vergiss es.}

{190}{}{Was?! [Seine Stimme steigt zu einem schrillen Kreischen an] Warum?! Warum ich?! Was hab ich denn je getan? Na ja, vielleicht stinke ich ein bisschen und meine Zähne sind schlecht – aber wer hier hat das nicht? Was für eine Schlampe aus ihr geworden ist... Dabei sieht sie selbst aus, als wäre sie aus irgendeinem Muellcontainer gekrochen. Ich rede nie wieder mit ihr!}
{191}{}{Soll ich ihr das sagen?}
{192}{}{Ja! Oh, du liebe Güte! N-nein, ich darf das nicht vermasseln. Ich mach's! Das ist m-meine letzte Chance. Ahh, ich – ich muss mich vorbereiten, richtig gut!}
{193}{}{Denk darüber nach. Ich geh mit ihr reden.}

{194}{}{Bob, ich kann dir mit ihr helfen...}
{195}{}{Äh... Nein, ich k-kenne dich nicht wirklich. Du bist nur irgendein Typ, warum sollte ich dir v-vertrauen? Was hast du hier gemacht?}
{196}{}{Du vertraust mir nicht? Na schön.}

#Ãðîáîêîïàòåëü
{200}{}{Hey Bob, stimmt es, dass du mit den Leichen, die du begräbst, „herumspielst“?}

{201}{}{Nein! Sie lügen! Sie lügen alle, das stimmt nicht! Das stimmt NICHT!}
{202}{}{Hey, du kannst es mir sagen, Bob. Ein Totengräber zum anderen.}
{203}{}{Na gut, vergiss es.}

{204}{}{H-hier vertraut dir doch sowieso k-keiner, weißt du das? Warum sollte ich?}
{205}{}{Na gut, vergiss es.}
{206}{}{}
{207}{}{[Er seufzt] Ich... Das ist nur ein paar M-Male passiert... Sieh mich an! Ich hatte noch nie eine Freundin! Ich- ich habe Bedürfnisse, verstehst du?! Alsho muss ich mich um mich selbst kümmern!}
{208}{}{Ich weiß nicht, wovon du redest! Lasch- lasch mich einfach in Ruhe!!}
{209}{}{Gut, ich gehe.}
{210}{}{Beruhig dich, sonst verlierst du deinen letzten Zahn.}
{211}{}{Bedürfnisse?}
{212}{}{Ich schätze, ich habe jetzt nichts mehr zu verbergen... Hier. [Er zieht ein altes Magazin aus der Tasche.] N-Nimm es. Es hat mir durch viele Jahre geholfen, aber dank dir brauche ich es nicht mehr. Ich habe jetzt ein anderes Leben.}
{213}{}{Was für ein ungewöhnliches Magazin...}
{214}{}{Du hast Erfahrungspunkte für den Einsatz deiner Redekunst erhalten.}
{215}{}{Was bringt es, es jetzt noch zu verbergen? Nach dem, was J-Jasmine gesagt hat, kann ich nicht mal mehr eine Frau a-ansehen... Hier. [Er zieht ein altes Magazin aus der Tasche.] N-Nimm es. Es hat mir durch viele Jahre geholfen, aber ich brauche es nicht mehr.}
{216}{}{Wenn ich dir das sage, bleibt mir gar nichts mehr. Ich bin ganz allein im Leben...}
{217}{}{Na gut, vergiss es.}

#The main quest of this location
{250}{}{Hmm. Schicke Stiefel. Wo hast du die her?}
{251}{}{Äh... V-von e-einem Toten, den ich begraben habe. Nur ein paar alte Stiefel...}
{252}{}{Nur ein paar alte Stiefel von einer alten Leiche? Zeig mir die Sohlen!}
{253}{}{[Er sieht nervös aus] W-w-was soll das? Das sind nur S-S-Stiefel!}
{254}{}{W-w-w-weil ich, wenn da ein Stern drauf ist, weiß, dass es Milos S-S-Stiefel sind, du A-A-Arschloch!}
{255}{}{Zeig sie einfach. Wenn ein Stern auf den Sohlen ist, reden wir darüber, was als Nächstes passiert.}

{256}{}{[Er sieht sich hektisch um] Warte, i-ich, äh, ich muss Jushtin sehen-}
{257}{}{Also steckt Justin mit drin? Sag mir, was du über Milo weißt, oder der Nächste, den man hier draußen begräbt, bist du!}
{258}{}{Bob, du musst ehrlich zu mir sein. Nach allem, was ich für Black Rock getan habe, findest du nicht, dass ich das verdient habe?}
{259}{}{Alles, was ich will, ist die Wahrheit, Bob. Sag mir einfach, was passiert ist. Ich verspreche, du wirst nicht dafür bestraft.}
{260}{}{Nein, *ich* gehe zu ihm. Bleib hier, bis ich zurückkomme.}

{261}{}{Du – du versprichsh? Hör zu, ich wollte das nicht! Sie haben mich gezwungen!}
{262}{}{Na, na. Erzähl mir alles.}
{263}{}{Wie kann ich dir vertrauen?! Ich kenne dich doch nicht mal! Lass mich in Ruhe! Verschwinde!}
{264}{}{Ich bin gleich zurück. Bleib hier, beweg dich nicht.}
{265}{}{Du erzählst es niemandem? B-bitte, Justin und William dürfen nichts davon erfahren! Sie bringen mich um!}
{266}{}{Ich verspreche es. Sag mir einfach, was passiert ist.}
{267}{}{Nein, nein, nein! [Er bedeckt sein Gesicht mit den Händen] Fass mich nicht an, bitte! Ich e-erzähl dir alles!}
{268}{}{Ich höre.}
{269}{}{[Er fuchtelt panisch mit der Hand] Nicht – fass mich nicht an! Ich wehre mich!}
{270}{}{Ich gebe dir Zeit, über deine Möglichkeiten nachzudenken. Vielleicht bist du schlauer, wenn ich zurückkomme.}

{271}{}{E-es war Justins S-sohn! Er ist an allem schuld! Er und seine Bande, sie – sie haben Milo umgebracht, seine Sachen genommen und mich gezwungen, s-seine Leiche zu begraben! Es war nicht meine Schuld! Ich hatte nichts damit z-u tun! Ich habe nur das Grab ausgehoben und die Leiche begraben, mehr nicht!}
{272}{}{Ich habe Fragen an dich.}
{273}{}{Genug davon. Ich werde herausfinden, was hier los ist.}
{274}{}{Ich habe noch mehr Fragen zu Milo.}

{275}{}{S-sag's bloß niemandem!}
{276}{}{Wer hat Milo angegriffen?}
{277}{}{Warum haben sie dich Milos Grab ausheben lassen?}
{278}{}{Warum hast du Milos Stiefel genommen?}
{279}{}{Was ist mit Milos Lieferung passiert?}
{280}{}{Warum hast du niemandem etwas gesagt?}
{281}{}{Ich habe noch eine Frage.}

{282}{}{[Er schluckt trocken und senkt die Stimme zu einem Flüstern] Die... Die Bande der „Moleratten“. Justins Sohn, er ist – er ist einer von ihnen...}
{283}{}{Sie mussten s-seine Leiche verstecken, und... [Er zuckt hilflos mit den Schultern] ...Wo hätten sie das sonst tun sollen, wenn nicht hier?}
{284}{}{Ich wollte nur mal w-was Schönes tragen! Wenn ich gewusst hätte, dass das passiert, hätte ich sie nicht g-genommen!}
{285}{}{Sie h-haben es genommen. Er hatte eine ganze Hütte voller G-Gecko-F-Felle, und sie haben alles mitgenommen!}
{286}{}{[Er sieht sich nervös um] Jushtin würde mir nichts tun, aber sein - sein Sohn... Er sagte mir, ich soll mein Maul h-halten, also... Also hab ich es gehalten! Du wirst es ihm doch nicht erzählen, dass ich mit dir geredet hab, o-oder?}
{287}{}{Nein! Ich glaub dir nicht! Du wirst mich v-verpetzen! Du bist genau wie die anderen! Wie alle!}
{288}{}{Okay, ich hab genug davon. Du sagst mir jetzt die Wahrheit, oder ich erzähle William alles!}
{289}{}{Du - nein, nein! Das ist E-Erpressung! Alle werden dich dafür hassen!}
{290}{}{Nicht annähernd so sehr, wie sie dich hassen werden, wenn ich William erzähle, dass du Milo getötet hast ... }
{291}{}{Na schön, ich kümmere mich selbst darum. Warte hier.}

#Æåíñêèå ðåïëèêè
{1195}{}{Äh ... Nein, ich, äh, kenn dich nicht wirklich. Du bist nur irgendeine F-Frau. Warum sollte ich dir vertrauen? Was hast du hier gemacht?}
{1207}{}{[Er seufzt] Ich ... Es ist nur ein paar Mal passiert ... Sieh mich an! Ich hatte noch nie eine Freundin! Ich - ich hab Bedürfnisse, weißt du?! Also muss ich mich um mich selbst kümmern!}
{1260}{}{Nein, *ich* gehe zu ihm. Bleib hier, bis ich zurückkomme.}
{1287}{}{Nein! Ich glaub dir nicht! Du wirst mich v-verpetzen! Du bist genau wie die anderen! Wie alle!}
{1291}{}{Na schön, ich kümmere mich selbst darum. Warte hier.}
