{100}{}{Du siehst Justin.}
{101}{}{Du siehst einen missmutigen Mann mit furchtbar schmutzigen, haarigen Händen. Offenbar wühlt er gern in Technik herum.}

{107}{}{Hey, ich hab deinen Kampf mit Mike gesehen. Und weißt du was? Ich fand's großartig! Mann, das hat mich an meine Jugend erinnert ... Und weißt du, Mike hat schon eine ganze Weile darum gebettelt. Also danke für die Show.}
{108}{}{Äh, gern geschehen ... }

#Starting conversation
{110}{}{Ja?}
{111}{}{Hast du Arbeit für mich?}
{112}{}{Tschüss.}

{113}{}{Wer hat hier das Sagen?}
{114}{}{Anscheinend William und ich. Aber in letzter Zeit schadet er mehr, als er nützt, weil er Fremden immer mehr vertraut und gegenüber immer freundlicher wird. Früher oder später fällt uns seine „Willkommensmatten“-Politik direkt auf die Füße. Also muss ich dafür sorgen, dass wir uns nicht mit nutzlosen Essern belasten.}
{115}{}{Richtig. Noch eine Frage.}
{116}{}{Richtig. Das wär's dann.}

#Quest - rid the community of filth
{120}{}{Hast du gehört, was Jasmine zugestoßen ist?}

{121}{}{Was hast du getan?! Jetzt wird dieses Gesindel niemals verschwinden! Wozu hast du sie überhaupt geheilt? Glaub mir, allen wäre besser gedient, wenn sie weg wäre!}
{122}{}{Du hast mir versprochen, mich zu bezahlen!}
{123}{}{Aber warum?!}
{124}{}{Ich sehe, du bist nicht glücklich. Dann gehe ich wohl, damit ich dich nicht noch nervöser mache.}
{125}{}{Hey, vielleicht war das für dich ja ein richtig herzerwärmendes Gefühl, aber *ich* muss hier *leben*! Und ich will keine dreckige Hure als Nachbarin, die wer weiß welche Krankheiten hat! Und diese aufreizende Art von ihr – da wird mir schlecht!}
{126}{}{Von wegen! Ich habe dir hundert Dollar versprochen, wenn du sie *loswirst*! Du hast alles nur schlimmer gemacht! Wenn du für deine willkürlichen Wohltaten Händchen halten und dich umarmen lassen willst, geh zu William, denn so einen Scheiß dulde ich nicht!}
{127}{}{Tut mir leid, ich habe dich missverstanden. Jetzt ist sie tot. Du kannst dich selbst davon überzeugen.}
{128}{}{Wirklich?}
{129}{}{Heilige Scheiße, du bist ja ein ganz besonderer Fall, was? Erst rettest du ihr das Leben und dann würgst du es ihr ab. Hast du beschlossen, den Teufel gleich an beiden Eiern zu packen? Na gut, na gut, der Auftrag ist erledigt, ich muss zahlen. Hundert Dollar, wie vereinbart. Und jetzt verschwinde.}
{130}{}{Mit Vergnügen.}

{131}{}{Du bist also derjenige, der diese Schlampe endlich zur Hölle geschickt hat? Gute Arbeit, und keinen Moment zu früh. Lass mich dir als Zeichen meiner Wertschätzung etwas geben – schließlich brauchen wir in Zukunft vielleicht noch mehr „Hilfe“ dieser Art. [he gives you 100 dollars]}
{132}{}{Danke, wir sehen uns.}
{133}{}{Bist du damit zufrieden?}
{134}{}{Und ob. Das hier ist mein Zuhause, verdammt. Ich brauche keine krankheitsverseuchten Huren, die durch meine Straßen laufen. Diese Schlampe hätte die ganze Stadt vergiftet, wenn nicht körperlich, dann im Kopf. Und ihre aufreizende Art, pah – mir wird schon schlecht, wenn ich nur daran denke.}
{135}{}{Harte Regeln ... Erinnert mich an zu Hause. Mach's gut.}

{136}{}{Also werden wir sie nicht wiedersehen? Endlich! Das ist eine Erleichterung. Danke, Fremder. Lass mich dir als Zeichen meiner Wertschätzung etwas geben – schließlich brauchen wir in Zukunft vielleicht noch mehr „Hilfe“ dieser Art. [he gives you 100 dollars]}
{137}{}{Was ist mit ihr passiert? „Nichts Gutes“ wäre eine ausgezeichnete Antwort.}
{138}{}{Äh, noch nichts.}
{139}{}{Es trifft sich nur so, dass sie tot ist.}
{140}{}{[Er lächelt] Ist das so? Darauf warte ich schon eine ganze Weile. Ich glaube, ich mache eine Flasche Whiskey auf, um zu feiern! Lass mich dir als Zeichen meiner Dankbarkeit etwas geben - vielleicht brauchen wir in Zukunft ja noch mehr „Hilfe". [er gibt dir 100 Dollar]}

{150}{}{Du willst nützlich sein? Erwürg diese Hure im Schlaf. Das ist das Beste, was du für diesen Ort tun kannst. Wasch dir danach nur die Hände.}
{151}{}{Welche Hure?}
{152}{}{Gibt es eine weniger gewalttätige Möglichkeit?}
{153}{}{Warum willst du sie loswerden?}
{154}{}{Ich erledige das.}
{155}{}{Das klingt nicht gut. Das mache ich nicht.}
{156}{}{Ich denke darüber nach. Später.}
{157}{}{}
{158}{}{Hier gibt es keine Arbeit für dich. Zumindest nicht von mir.}
{159}{}{Na gut.}

{160}{}{Jasmine, diese abgenutzte Schlampe aus Reno. Ihr Vater kam auf die Idee, sie aus ihrer natürlichen Umgebung zu holen, also brachte er sie hierher. Igitt!}
{161}{}{Nein, gibt es nicht. Ich hätte es schon vor langer Zeit selbst erledigt, wenn William nicht wäre. Der Friedhof ist ohnehin ganz in der Nähe. Aber er will, dass wir alle Händchen halten und fröhliche Lieder singen, bis sich alles von selbst regelt. Was für ein Schwächling. Er hat keinen Sinn für die Wirklichkeit. Er glaubt immer noch, sie könne geheilt werden!}
{162}{}{Sie ist ansteckend. Zum Glück hat sie es noch nicht weitergegeben, aber warum sollten wir diese erbärmliche Hure überhaupt hier haben wollen? Das hier ist eine anständige Gemeinschaft. Allein durch ihre Anwesenheit vergiftet sie alles, was wir aufgebaut haben.}
{163}{}{Gut. Ich gebe dir hundert Dollar, wenn du sie loswirst. Töte sie, jag sie fort - mir egal, Hauptsache, du schaffst diese Spermaschleuder aus Black Rock! Und lass dich nicht von Williams gefühlsduseligem Schwachsinn einwickeln!}
{164}{}{Das ist deine Entscheidung. Aber ich würde dir hundert Dollar zahlen, wenn du sie von hier fortschaffst.}
{165}{}{Hundert Dollar? Na gut, ich bin dabei.}
{166}{}{Gib mir etwas Zeit zum Nachdenken.}

{167}{}{Was springt für mich dabei heraus, wenn ich sie verschwinden lasse?}
{168}{}{Respekt und hundert Dollar von mir persönlich.}

{169}{}{Hast du eine Sicherung für eine Wasserpumpe?}
{170}{}{Ach, ich verstehe. Unser Nachbar Gerlach hat dich geschickt, oder? Nun, ich verschenke nichts. Und außerdem habe ich kein Ersatzteil. Vielleicht gibt es in den größeren Städten etwas. Zum Beispiel in Reno – vor dem Krieg gab es dort viele Reparaturwerkstätten.}

#Quest - fugitive slaves
{180}{}{Was hältst du von den entlaufenen Sklaven?}

{181}{}{Ich finde, sie sollten weiter in die andere Richtung fliehen. Versteh mich nicht falsch, aber solche Leute brauchen wir hier nicht. Sie bringen uns nur Ärger.}
{182}{}{Ärger? Inwiefern?}
{183}{}{Erstens haben wir schon mehr als genug Mäuler zu stopfen. Ja, im Moment mangelt es uns nicht an Nahrung – nicht mit den Geckos, die wir jagen, den Feldfrüchten, die wir anbauen, und dem Brahmin, das William gekauft hat –, aber das wird nicht ewig so bleiben. Früher oder später kommen Zeiten der Hungersnot, und dann werden wir bereuen, jeden Landstreicher aufgenommen zu haben, der in die Stadt kommt. Wir leben hier nur deshalb gut und sicher, weil meine Wasserpumpe Grundwasser aus den Tiefen unter uns hochpumpt.}
{184}{}{Und zweitens?}
{185}{}{Und zweitens sind sie entflohene Sklaven! Sieh dir die Halsbänder an! Jeder, der nach Black Rock kommt, wird wissen, was sie sind, und irgendwann dringt die Nachricht zu ihrem Besitzer durch. Er wird Sklavenjäger schicken, um sie zurückzuholen – und uns alle gleich mit! Ja, vielleicht bedeutet dir das nichts, aber du wohnst nicht hier, anders als ich. Ich will nicht, dass mein Sohn oder ich den Rest unseres Lebens darauf warten müssen, dass uns das einholt.}
{186}{}{Ich kann sie loswerden, wenn du willst.}
{187}{}{Ich werde darüber nachdenken.}
{188}{}{Schaff sie hier weg, ist mir egal, wie. Aber selbst kann ich nichts tun – ich will nicht, dass William mir wieder eine Moralpredigt hält.}
{189}{}{}
{190}{}{Wegen der Sklaven ...}
{191}{}{Was kannst du mir über sie sagen?}
{192}{}{Du brauchst dir keine Sorgen mehr zu machen. Sie sind tot.}
{193}{}{Du brauchst dir keine Sorgen mehr zu machen. Sie sind weg.}
{194}{}{Großartig! Da fällt mir ein Stein vom Herzen. Hier – hundert Mäuse. Du hast sie dir verdient.}
{195}{}{Abgemacht.}
{196}{}{Wir haben das schon besprochen. Sie gehören nicht hierher, Ende der Diskussion.}
{197}{}{William und ich haben beschlossen, sie den brahmin-Pferch reinigen zu lassen. Gewöhn dich also daran, sie hier zu sehen.}
{198}{}{[Er wirft frustriert die Hände hoch] Nach allem, was ich getan habe! All die Jahre, die ich in den Aufbau dieses Ortes gesteckt habe! Und Außenstehende wie du schwärmen hier einfach rein wie Fliegen auf brahmin-Scheiße! Ihr seid alle gleich! Glaubst du, sie werden auch nur *die Hälfte* von dem tun, was ich für diesen Ort getan habe? Was glaubst du, warum sie überhaupt hierhergekommen sind?}
{199}{}{Warte ...}
{200}{}{[Er ignoriert dich] Was glaubst du, warum sie überhaupt Halsbänder trugen? Glaubst du, die Besten und Klügsten werden zu Sklaven? Nein! Sie sind Sklaven, weil sie zu nichts anderem taugen – außer Scheiße wegzuputzen! Wahrscheinlich wurden sie in die Sklaverei verkauft, weil sie Verbrecher sind oder bis zum Hals in Schulden stecken oder ihr Leben auf andere Weise vermasselt haben – und jetzt werden sie unseres vermasseln! Und William will sie das machen lassen! VERDAMMT!... Warum erkläre ich dir das überhaupt? Du hörst ja nicht mal zu. Verschwinde einfach aus meinem Haus. Und komm nicht wieder!}
{201}{}{Wie du willst. Ich habe getan, was ich tun musste.}
{202}{}{Großartig! Da fällt mir ein Stein vom Herzen! [Er zögert] Aber ... Was, wenn sie zurückkommen? Hier, fünfzig Mäuse. Ich hoffe nur, ich sehe sie nicht wieder. Für solchen Stress bin ich zu alt.}

#Quest - missing brahmin
{210}{}{Was weißt du über Williams vermissten brahmin?}
{211}{}{Nur, dass Williams rotzfrecher Bengel seinen gehörnten zweiköpfigen Freund verloren hat, während er bei der Arbeit geschlafen hat. Er wird es natürlich abstreiten, aber wie sonst erklärt man, dass eine halbe Tonne Fleisch direkt vor seiner Nase verschwindet?}
{212}{}{Du klingst fast, als würdest du dich freuen, was passiert ist.}
{213}{}{Woher soll ich wissen, dass du es nicht warst? Hat man dich nicht bei den Ställen gesehen?}
{214}{}{Wer könnte es deiner Meinung nach gewesen sein?}
{215}{}{Weißt du, wer Schrotpatronen mit Nägeln fuellt?}
{216}{}{Klar weiß ich das. Ich habe die einzige Werkstatt in der Stadt – wenn du etwas herstellen willst, das komplizierter ist als eine Keule, kommst du zu mir. Aber Munition ist schwierig. Nur Bolt hat sich einmal Schrotpatronen für den Eigenbedarf gemacht.}
{217}{}{Ich *werde* mich freuen, wenn William etwas daraus lernt. Wahrscheinlich wurde es von einem der Außenstehenden gestohlen, die er reingelassen hat. Vielleicht ist er jetzt etwas weniger leichtgläubig.}
{218}{}{Sieh nur, wie nah die Toilette an den Ställen ist! Jeder könnte jederzeit dort sein. Sogar ich.}
{219}{}{Hey, ich will niemanden ohne Beweise beschuldigen, aber du und ich wissen beide, wie es war – einer von Williams Außenseitern war's. Und du? Wo warst *du*, als brahmin verschwunden ist?}
{220}{}{Keine weiteren Fragen.}
{221}{}{Hast du die Geschichte über das verschwundene brahmin gehört?}
{222}{}{… Scheiße. Ich wusste es. Scheiße! Ich wusste, dass Bolt in irgendwelche schmutzigen Geschäfte verwickelt war, aber das? Ich hätte nie gedacht, dass er so was tun würde.}
{223}{}{Mitglieder einer Gang, der er früher angehörte, haben ihn dazu gezwungen.}
{224}{}{Verdammt noch mal! Siehst du? Siehst du, was William angerichtet hat? Wenn er nicht jeden aufgenommen hätte, den er finden konnte, hätten wir dieses Problem nicht! Erst die Hure, dann die Sklaven, jetzt ein Ex-Räuber! Was kommt als Nächstes? Ein bankrotter Zuhälter? Vielleicht ein verdammter Kultist?}
{225}{}{Hat Bolt keine zweite Chance verdient? William will den Menschen helfen. Du willst sie einfach verstoßen.}
{226}{}{Wag es ja nicht. Wag es verdammt noch mal nicht, so mit mir zu reden. Bolt und ich haben viel zusammen durchgemacht! Er hat beim Saubermachen der Windmühle geholfen, beim Graben des Brunnens und bei all den verschiedenen Maschinen hier … Aber das macht ihn nicht unschuldig. Und es gibt William nicht das Recht, wegen seiner Fehlentscheidungen alle anderen leiden zu lassen.}
{227}{}{In dieser Welt findest du keine Heiligen. Du solltest schätzen, was du hast. Aber ich gehe jetzt.}
{228}{}{Denk, was du willst. Darüber diskutiere ich nicht mit dir.}
{229}{}{Du hast recht. Damit diese Gemeinschaft gedeihen kann, muss man alle aussortieren, die nichts beitragen können.}
{230}{}{Nein, nicht aussortieren. Wir müssen sie von Anfang an fernhalten. Wir sollten den ganzen Abschaum abweisen, sobald er hier auftaucht. Und alle, die gut genug sind zu bleiben, sollten wir wie Kinder erziehen. Aber keiner von uns weiß, wie das geht.}
{231}{}{Genau. Ich bin froh, dass du es zugibst. Jetzt muss ich gehen.}

#About Black Rock
{250}{}{Kann ich dir ein paar Fragen über diesen Ort stellen?}
{251}{}{Kann dich nicht aufhalten. Aber glaub ja nicht, dass ich mich mit dir unterhalte, bis mir die Zunge anschwillt.}
{252}{}{Wie hat das alles angefangen?}
{253}{}{Wie schafft ihr es, in einer so trockenen und ungeschützten Umgebung zu leben?}
{254}{}{}
{255}{}{Frag Jed. Er war schon vor uns allen hier und ist vor der "Zivilisation" geflohen. Er war allein, bis William und ich uns hier in der Gegend niederließen. Aber dann fing William an, jeden arbeitsscheuen Vagabunden einzusammeln, den er finden konnte. Hör zu, ich versteh's ja - ohne Hilfe hätte ich das alles nicht geschafft. Aber die Leute, die er jetzt anschleppt? Krankheitsverseuchte Huren und entlaufene Sklaven? Für so einen Scheiß hab ich mich nicht gemeldet.}
{256}{}{Wegen mir. Wenn ich nicht den Strom und die Wasserpumpe eingerichtet hätte, würde hier außer Jed niemand wohnen. Wir hatten Glück - hier standen irgendwelche Metallskulpturen. Jetzt sind das die Gebäude, in denen wir schlafen. Und was unsere exponierte Lage angeht: So können wir jeden Angreifer schon aus einer Meile Entfernung sehen. Wir haben Deckung, sie nicht. Angriffe von außen machen mir keine Angst - Sorgen bereiten mir die Gefahren im Inneren.}

#Quest - searching of a delivery man
{260}{}{Weißt du etwas über den verschwundenen Kurier?}
#So now William's got you on this? Fuck, I knew he wouldn't let it rest.
#Do you have a problem with my search?
#That courier's got gecko skins. William wants to use them to set up a caravan route. Fuck... I've got nothing against Milo, but we'd all be better off if he was sleeping drunk under a bush or something.
#What's the problem? Tell me the details. Maybe you'll change my mind.
{261}{}{Was gibt's da zu wissen? Er ist nur ein paar Tage überfällig. Kein Grund zur Sorge.}
{262}{}{Bist du sicher? Du suchst doch immer nach einem Grund, Leute loszuwerden, oder?}
{263}{}{Na schön, ich glaub dir.}
{264}{}{Ach, du glaubst, ich hätte was damit zu tun, hm? Der böse alte Justin, immer auf der Suche nach einem Grund, jemanden umzubringen! Ist es das, was du denkst? Du hast verdammt noch mal keine Ahnung von mir. Außerdem war ich die ganze Zeit hier, frag jeden. Dein Kurier liegt wahrscheinlich irgendwo besoffen in einem Graben.}
{265}{}{Ich glaub dir nicht. Ich behalte dich im Auge.}
{266}{}{Und dein Sohn - wo war er am Tag von Milos Mor... Äh, Verschwinden?}
{267}{}{}
{268}{}{}
{269}{}{[Stürzt sofort vor] WAG ES JA NICHT!! Wag es nicht, meinem Sohn die Schuld zu geben! Das würde er niemals tun! NIEMALS! Ich hab ihn seit seiner Geburt vor so was beschützt! Ich hab ihn aus dieser verdammten Gang rausgeholt! Und jetzt kommst du daher und machst alles zunichte, wofür ich gearbeitet habe? Verschwinde! Verschwinde, bevor ich dir deine verlogene, verdammte Zunge rausreiße!!}
{270}{}{Milos Leiche liegt auf dem Friedhof. Überzeug dich selbst.}
{271}{}{Oh, ich geh ja. Ich werde nachsehen. Und dann wirst du schon sehen! Du wirst sehen, dass er nichts damit zu tun hatte! Er... Er kann es nicht gewesen sein...}
{272}{}{Na dann, gehen wir.}
{273}{}{Na gut, ich geh ja schon, meine Güte...}
{274}{}{[Du gehst zum Friedhof und kommst zurück, nachdem Justin die Wahrheit gesehen hat. Er lässt sich auf einen Stuhl sinken, packt sich an den Kopf und stößt ein langes, elendes Stöhnen aus.]}
{275}{}{Oh, tut mir leid, bester Papa der Welt, ich hab nicht mitbekommen, was du gesagt hast. Kannst du es wiederholen?}
{276}{}{[Lass ihn sich erholen]}
{277}{}{[Seine nuschelnde Stimme ist kaum zu hören] Fick dich. Du hast kein Recht, über mich zu urteilen.}
{278}{}{Ach ja?}
{279}{}{Verstehst du jetzt, warum ich mich immer gegen Neuankömmlinge gewehrt habe? Wie sollen wir für sie verantwortlich sein, wenn wir nicht mal unsere eigenen Probleme in den Griff kriegen? Gott, Eugene ... Wie konnte es nur so weit kommen?}
{280}{}{Du wusstest davon?!}

{281}{}{Nein! Ich meine ... Scheiße ... Ich wollte nie, dass es so weit kommt. Als ich hörte, dass William eine Karawanenroute nach Reno einrichten will, bin ich ausgerastet. Mein Sohn bot an, die Karawane mit ein paar Warnschüssen aus den Bergen zu verscheuchen. Ich sagte Nein, aber ... ich schätze, er hat seinen neuen Freunden davon erzählt. Ich wollte nie, dass so etwas passiert! Ich wollte doch nur ein friedliches, ruhiges Leben.}
{282}{}{Es sieht so aus, als wäre dir das einfach nicht vergönnt gewesen. Was jetzt?}
{283}{}{Es tut mir leid, dass ich dich da mit hineingezogen habe, aber jetzt müssen wir etwas unternehmen.}
{284}{}{Jetzt? [Er schüttelt traurig den Kopf.] Diese Bande, die „Molerats“ – sie haben bestimmt schon einen Plan, um die Karawane anzugreifen. Jetzt lässt sich das nicht mehr verhindern. Wenn du es versuchen willst, halte ich dich nicht auf, aber ich kann dir nicht helfen.}
{285}{}{Es gibt immer einen Weg. Wenn wir uns das nächste Mal sehen, wird hier eine Karawane sein.}
{286}{}{Dann haben wir uns nichts mehr zu sagen. Tschüss.}
{287}{}{Ich werde nicht versuchen, dich aufzuhalten. Aber merk dir meine Worte: Wenn diese Karawane tatsächlich durchkommt, werden Plünderer mit ihr kommen. Und wo es Karawanenleute gibt, gibt es Huren, Diebe und Betrüger. Unsere Gemeinschaft wird zu einem weiteren Drecksloch wie Reno. Und das geht alles auf deine Kappe.}
{288}{}{Auf Wiedersehen, Justin.}

{290}{}{Also haben wir dir die Karawane zu verdanken, was? Hast du überhaupt darüber nachgedacht, was jetzt aus Black Rock wird? Sie werden mehr Leute hierherbringen. Huren, Drogenabhängige, Verbrecher. Das ist dir doch scheißegal, oder? Du wohnst nicht mal hier. Du bist bloß irgendein Fremder, der aus dem Ödland hergeweht kam und über unsere aller Zukunft entschieden hat. Wie beschissen ist das denn?}
{291}{}{Ja, ich verstehe. Und jetzt ist es an der Zeit, dass dieser Fremde anderswo Geschichte schreibt. Tschüss.}
{292}{}{Ich sehe die Karawane hier nicht. Ich will nicht lügen – ich bin froh darüber. Klar, sie hätte mehr Geld eingebracht – na und? Das Geld soll ruhig in Reno bei den Huren, Drogenabhängigen und Gangbossen bleiben. William war *so* nah dran, alles zu zerstören, was wir aufgebaut haben ... Und das Einzige, was uns gerettet hat, war irgendein Fremder aus dem Ödland. Ist das nicht verrückt?}

#Female character
{1121}{}{Was hast du getan?! Jetzt wird dieses Gesindel niemals verschwinden! Wozu hast du sie überhaupt geheilt? Glaub mir, allen wäre besser gedient, wenn sie weg wäre!}
{1127}{}{Tut mir leid, ich habe dich missverstanden. Jetzt ist sie tot. Du kannst dich selbst davon überzeugen.}
{1129}{}{Heilige Scheiße, du bist ja ein ganz besonderer Fall, was? Erst rettest du ihr das Leben und dann würgst du es ihr ab. Hast du beschlossen, den Teufel gleich an beiden Eiern zu packen? Na gut, na gut, der Auftrag ist erledigt, ich muss zahlen. Hundert Dollar, wie vereinbart. Und jetzt verschwinde.}
{1131}{}{Du bist also derjenige, der diese Schlampe endlich zur Hölle geschickt hat? Gute Arbeit, und keinen Moment zu früh. Lass mich dir als Zeichen meiner Wertschätzung etwas geben – schließlich brauchen wir in Zukunft vielleicht noch mehr „Hilfe“ dieser Art. [he gives you 100 dollars]}
{1201}{}{Wie du willst. Ich habe getan, was ich tun musste.}
{1219}{}{Hey, ich will niemanden ohne Beweise beschuldigen, aber du und ich wissen beide: Es war einer von Williams Fremden. Und du? Wo warst du, als das brahmin verschwunden ist?}
{1283}{}{Es tut mir leid, dass ich dich da mit hineingezogen habe, aber jetzt müssen wir etwas unternehmen.}
{1290}{}{Also haben wir dir die Karawane zu verdanken, was? Hast du überhaupt darüber nachgedacht, was jetzt aus Black Rock wird? Sie werden mehr Leute hierherbringen. Huren, Drogenabhängige, Verbrecher. Das ist dir doch scheißegal, oder? Du wohnst nicht mal hier. Du bist bloß irgendein Fremder, der aus dem Ödland hergeweht kam und über unsere aller Zukunft entschieden hat. Wie beschissen ist das denn?}
{1291}{}{Ja, ich verstehe. Und jetzt ist es an der Zeit, dass dieser Fremde anderswo Geschichte schreibt. Tschüss.}
{1292}{}{Ich sehe die Karawane hier nicht. Ich will nicht lügen – ich bin froh darüber. Klar, sie hätte mehr Geld eingebracht – na und? Das Geld soll ruhig in Reno bei den Huren, Drogenabhängigen und Gangbossen bleiben. William war *so* nah dran, alles zu zerstören, was wir aufgebaut haben ... Und das Einzige, was uns gerettet hat, war irgendein Fremder aus dem Ödland. Ist das nicht verrückt?}
