{100}{}{Du siehst Eugene.}
{101}{}{Du siehst einen ungepflegten jungen Mann in einer Lederjacke. Er sieht aus, als hätte er sich seit Langem nicht mehr geduscht.}
{102}{}{Wir brauchen hier nicht jeden Abschaum.}

#Ğàçãîâîğ ó çàãîíà ïî ïîâîäó áåãëûõ ğàáîâ
{110}{}{Na, sieh einer an. Jetzt bestimmt ein Fremder aus dem Ödland, wie unsere Gemeinschaft geführt werden soll. Weißt du, was ich denke?}
{111}{}{Ist mir scheißegal, wa- }
{112}{}{Was willst d- }
{113}{}{[Er ignoriert dich] Dass mein Alter recht hat! Das Einzige, was wir euch Neuankömmlingen geben sollten, sind zwei Ladungen Schrot! Glaubst du, ich hätte nicht den Mumm dazu? Hm? Versuch's doch. VERSUCH'S!}
{114}{}{Womit, du Vollidiot, mit deiner unsichtbaren Schrotflinte?}
{115}{}{Warum wollt ihr auf uns schießen? Niemand hat etwas falsch gemacht.}
{116}{}{Ach ja? Na ja, äh ... Scheiße! [Er tritt wütend so heftig gegen den Zaun, dass die Balken zu wackeln beginnen.] Ich warne dich – leg dich nicht mit uns an! [Er dreht sich um und stürmt davon, wobei er etwas vor sich hin murmelt.]}
{117}{}{Uns? Wer ist denn „uns“? ...}
{118}{}{[Er ignoriert dich] Dass mein Alter recht hat! Das Einzige, was wir Neuankömmlingen geben sollten, sind zwei Ladungen Schrot! Und ich sehe dir an, dass du genauso denkst. }
{119}{}{Aber glaub bloß nicht, dass wir deshalb Freunde sind. Pass auf und geh uns nicht auf die Nerven. [Er dreht sich um und geht davon.]}

#Ğàçãîâîğ î ñèòóàöèè ñ Ìàéëî
{120}{}{Ja, was?}
{121}{}{Nichts.}
{122}{}{Ich will über deine Raider-Bande reden.}

{123}{}{[Er lacht] Oh, meine Raider-Bande? Wo soll ich die denn herhaben?}
{124}{}{Hör auf zu lügen. Ich weiß, dass du Milo getötet hast, also solltest du besser anfangen zu reden.}
{125}{}{Du weißt, dass ich die Wahrheit sage, auch wenn es sonst niemand tut. Es ist nur eine Frage der Zeit, bis ich Beweise dafür finde. Dann komme ich wieder.}

{126}{}{Wer, ich? [Er sieht sich mit einem wenig überzeugenden Ausdruck völliger Bestürzung um.] Und warum sollte ich dir das glauben?}
{127}{}{Totengräber Bob trägt Milos Stiefel. Er hat mir alles erzählt.}
{128}{}{Ich habe Beweise aus Gerlach. Zum Beispiel hat man dich dort mit Milo reden sehen. Sag mir die Wahrheit, dann muss ich nicht zu William oder deinem Vater gehen.}

{129}{}{Bob hat es dir erzählt? [Er sieht sich nervös um und beugt sich dann zu dir.] Na schön, Neuling, du hast mich erwischt. Und jetzt?}
{130}{}{[Er sieht sich nervös um und beugt sich dann zu dir.] Na schön, Neuling, du hast mich erwischt. Und jetzt?}
{131}{}{Ich will Einzelheiten. Erzähl mir genau, was mit Milo passiert ist.}

{132}{}{Das war's? Lässt du mich danach in Ruhe?}
{133}{}{Warum Milo?}
{134}{}{Woher wusstest du von der Lieferung?}
{135}{}{Was hast du mit dem Paket gemacht?}
{136}{}{Erzähl mir von deiner Gang.}
{137}{}{Hast du nicht gedacht, dass man dich irgendwann erwischen würde?}
{138}{}{Reden wir über deine Bestrafung.}

{139}{}{Milo hatte mit der Gang eine Abmachung, damals, als wir noch groß waren. Er gab uns Informationen, und wir sorgten dafür, dass er nicht angegriffen wurde. So konnte er all seine Lieferungen machen. Eine Zeit lang hatten wir das ganze Tal unter Kontrolle.}
{140}{}{William wollte Gecko-Felle aus Gerlach, um irgendeinen verrückten Karawanenhandel aufzuziehen. Mein Vater sagte, er würde alles ruinieren. Ich ging zu Milo und sagte ihm, er solle die Felle verschwinden lassen, aber er sagte, ich solle mich verpissen. Da beschloss die Gang, ihn loszuwerden. Ich wollte nicht, dass das passiert, ich schwöre! Aber ich konnte sie nicht aufhalten.}
{141}{}{Ich habe nichts davon genommen, aber der Rest der Gang hat die Felle mitgenommen. Was sie damit gemacht haben, weiß ich nicht.}
{142}{}{Wir sind die Maulwurfsratten! Noch nie von uns gehört? Die meisten von uns kamen aus Reno, ein paar aus Salt Lake City. Diebe, Killer, Zuhälter - damals, als wir noch groß waren, waren wir alles, was eine Gang sein konnte. Hey, sieh mich nicht so an! Wir haben doch nur versucht zu überleben.}
{143}{}{Ohh, wie gruselig. Hast du überhaupt eine Ahnung, wovon du redest? Wir sind eine GANG! Wir haben mehr Leute umgebracht, als du je kennengelernt hast! Und auch du wirst uns nicht im Weg stehen, verstanden?}

{144}{}{Du glaubst, ich habe Angst vor dir? Die Maulwurfsratten sind nicht mehr, was sie mal waren, aber wir sind immer noch verdammt viel härter als du.}
{145}{}{Vielleicht, aber jetzt solltest du lieber meine Fragen beantworten.}
{146}{}{Denk, was du willst, aber ich finde einen Weg, dich zur Rechenschaft zu ziehen. Und jetzt verpiss dich.}
{147}{}{Vielleicht, vielleicht auch nicht. Man sieht sich, Eugene.}

{148}{}{Wie hat die Gang so lange durchgehalten?}
{149}{}{Hm? Warum?}
{150}{}{Weil ich euch helfen kann. Ehrlich.}
{151}{}{Weil du dieser Gang den Rücken kehren und ein ehrliches Leben führen solltest.}
{152}{}{Weil es der letzte Tag deines Lebens sein wird.}
{153}{}{Denk, was du willst. Ich habe noch mehr Fragen.}

{154}{}{Du? Du glaubst, du hast das Zeug zur Maulwurfsratte? Das hier ist keine verdammte Pfadfindergruppe. Wie viele Leute hast du umgebracht, hm?}
{155}{}{Du redest mit dem übelsten Raider diesseits des Kontinents. Zeig verdammt noch mal Respekt.}
{156}{}{Mehr als alle in diesem Ameisenhaufen von einem Dorf.}
{157}{}{„Verflucht“ steht mir ins Gesicht geschrieben. Und überall, wo ich hingehe, ist es genauso.}
{158}{}{Ich bringe jeden um, wirklich jeden, auch Kinder. Du glaubst, deine Gang wäre verdammt hart? Wenn du noch nie das Todesröcheln eines aufgeschlitzten Kleinkinds gehört hast, verdienst du es nicht einmal, mit mir zu reden.}
{159}{}{Vergiss es, reden wir über etwas anderes.}

{160}{}{[Er hält einen Moment inne] Weißt du, ich glaube, du bist vielleicht wirklich der Richtige. Vielleicht kannst du uns ja doch helfen.}
{161}{}{Gut. Ich höre.}

{162}{}{Ja, das habe ich schon gehört. Zum Beispiel von Milo. Sieh dir an, was aus ihm geworden ist.}
{163}{}{Nicht sehr überzeugend, was? Na gut, reden wir darüber ...}
{164}{}{Verdammt, du hast recht. Nach dem, was Milo passiert ist ... Scheiße, ich weiß nicht, was ich tun soll. Vielleicht sollte ich einfach abhauen. Die Gang ist ohnehin am Ende ...}
{165}{}{Sag mir, was sie vorhaben. Ich kümmere mich um alles.}

{166}{}{Du musst dich beeilen. Sie werden die Karawane überfallen, wenn sie in die Berge kommt. Sie werden alle töten und alles mitnehmen – es wird aussehen, als wäre die ganze Karawane einfach verschwunden. Hier, nimm dieses Funkgerät und diese Frequenzen. Nur so kannst du sie finden.}
{167}{}{Ich werde es im Hinterkopf behalten.}

{168}{}{Was, kannst du es kaum erwarten, deine Nase in die Gang zu stecken?}
{169}{}{Ich habe gehört, was passiert ist. Nun ja ... Jetzt gibt es kein Zurück mehr.}
{170}{}{Na, na.}

#Female character
{1110}{}{Na, sieh einer an. Jetzt bestimmt ein Fremder aus dem Ödland, wie unsere Gemeinschaft geführt werden soll. Weißt du, was ich denke?}
{1129}{}{Bob hat es dir erzählt? [Er sieht sich nervös um und beugt sich dann zu dir.] Na schön, Neuling, du hast mich erwischt. Und jetzt?}
{1130}{}{[Er sieht sich nervös um und beugt sich dann zu dir.] Na schön, Neuling, du hast mich erwischt. Und jetzt?}
{1154}{}{Du? Du glaubst, du hast das Zeug zum Maulwurfsratten? Das hier ist verdammt nochmal keine Pfadfindergruppe. Wie viele Leute hast du schon umgebracht, hm?}
