{100}{}{Du siehst den großen Biker Phil.}
{101}{}{Das ist Phil Pritchett, vermutlich der größte Biker der örtlichen Gang.}

#Òàéìåðíûå ñöåíû
{102}{}{Hey! Diese Biker haben sich als echt coole Typen entpuppt!}
{103}{}{Wach auf, Kumpel! Du hast lange geschlafen.}
{104}{}{Bring mich nicht auf die Palme!}
{105}{}{Hast du das gesehen?! Ha-ha-ha!}
{106}{}{Ähm ... Wie hast du das gemacht?}
{107}{}{Was war das? Magie?!}

#ÍStarting conversation
{110}{}{[Beachtet dich nicht]}
{111}{}{[Betrachtet den Totenkopf auf deinem Overall und grinst]}
{112}{}{Was geht, Wanderer? Setz dich, lass uns reden!}
{113}{}{[Sieht sich deine Hände an und lacht] Was ist los?}

#About ghost train
{120}{}{Hast du vielleicht mal einen Zug vorbeifahren hören?}
{121}{}{Hab ich. Ich hab ihn schon oft gesehen. Aber wir konnten ihn nicht einholen.}
{122}{}{Wer könnte ihn wohl fahren, was meinst du?}
{123}{}{Natürlich niemand. Das ist ein Geisterzug. Was, noch nie davon gehört?}
{124}{}{Nö. Hab ich nicht.}
{125}{}{Also, ich erzähle es dir nur einmal, also hör gut zu. Vor dem Krieg wurden ein paar automatische Züge zu Testzwecken in Betrieb genommen. Man wollte sehen, wie sie sich schlagen. Also fuhren sie kreuz und quer durch Nevada. Und dann, zack! – ging etwas in den automatischen Steuerungssystemen kaputt.}
{126}{}{Und er ist entgleist?}
{127}{}{Nein! Diese Idioten von den Bahnhöfen versuchten, es aufzuhalten, aber vergeblich. Während sie es versuchten, begann der Krieg. Bis heute fährt es also auf den Schienen Nevadas auf und ab.}
{128}{}{Hm. Eine lustige Geschichte.}

#About archivarius's runaway daughter
{140}{}{Na, bist du nicht der Verfolger entlaufener Mädchen? Im Ödland trifft man selten Leute wie dich. Verleih dir eine Medaille, damit dich jeder sofort erkennt.}
{141}{}{Bist du sauer, dass das Mädchen dich verlassen hat?}
{142}{}{Sauer? Ich? Ha! Soll ich mich vielleicht auch noch auf dem Klo einschließen und heulen? Nein, es ist mir ziemlich egal. Mit ihr war es lustig, aber andererseits ... Na ja, du hast eine gute Tat vollbracht und den ganzen Mist - die Tochter ihrem Vater zurückgebracht. Ich finde, das ist bewundernswert.}
{143}{}{Puh, das heißt, kein böses Blut? Super. Dann lass uns über etwas anderes reden.}

#Starting dialogue options
{150}{}{Kann ich bei dir Metallkram kaufen?}
{151}{}{Leute, wer seid ihr eigentlich?}
{152}{}{Wegen der Reparaturen.}
{153}{}{Hey, Leute! Wie wär's mit einem Bier? Ich hab genug für alle!}
{154}{}{Ich muss die Tore zum Bahnhof öffnen. Könnt ihr mir helfen?}
{155}{}{[Lass ihn in Ruhe]}

#Who are you:
{160}{}{[Sie sehen einander an und lachen über dich] Hast du schon mal von Bikern gehört?}
{161}{}{Vielleicht. Ihr seid so etwas wie eine Gang, oder?}
{162}{}{Eine Gang? Na ja, wenn du dich traust, kannst du uns Gang nennen.}
{163}{}{Was macht ihr?}
{164}{}{Machen wir's einfach: Alles, was mit Metallkram zu tun hat, ist unser Spezialgebiet.}
{165}{}{Metallkram?}
{166}{}{Wir fahren durchs Ödland und sammeln Vorkriegstechnologie. Wenn du Reparaturen oder Teile brauchst, sag einfach Bescheid, keine falsche Scheu! Wir haben zwar noch andere Einnahmequellen, aber diese Leidenschaft ist uns über die Jahre nie vergangen.}
{167}{}{Ah, verstehe.}

#Upgrades, main menu:
{170}{}{Ich höre.}
{171}{}{Ich möchte meine Waffe verbessern.}
{172}{}{Ich muss diesen Steuerungsmechanismus für die Nuka-Cola-Anlage reparieren.}
{173}{}{Du kennst dich ja prima mit Maschinen aus. Willst du dir meinen Pickup mal ansehen?}
{174}{}{Ich habe einen ernsthaften Vorschlag – ich muss den Zugsteuerungscomputer reparieren.}
{175}{}{}
{176}{}{Vergiss es, ich habe es mir anders überlegt.}

{177}{}{Hey, Leute, schaut mal – Freibier! Kommt, setzt euch und entspannt euch! Wir tun euch nichts. [Er legt dir den Arm um die Schulter und setzt sich neben dich. Die anderen scharen sich ebenfalls um euch.]}
{178}{}{[Ihr trinkt einen halben Tag lang, bis alle flach auf dem Gesicht liegen ...]}

#Opening the station gates
{202}{}{[Er scheint dich gar nicht zu beachten.]}
{203}{}{[Er beachtet dich immer noch nicht und trinkt weiter sein Bier.]}
{204}{}{Hey, Kumpel, hörst du mich?}
{205}{}{[Spuckt auf den Boden und nimmt noch einen Schluck aus der Flasche.]}
{206}{}{Ignorierst du mich?! Willst du auch meine Faust im Gesicht ignorieren?!}
{207}{}{Verstanden. Was willst du dafür haben?}
{208}{}{Schluss jetzt! Ich hab genug von dir! Mach die Tore auf, oder ich ...}
{209}{}{[Grinst und lacht] Na, du bist aber schnell, was? Ich kann das machen. Aber was springt für mich dabei raus?}
{210}{}{Mach die Tore auf!}
{211}{}{Ich komme später wieder.}
{212}{}{Na sieh mal einer an, noch so ein Schlaumeier, der durch will! Tore, sagst du? Kein Problem! Ich muss mich nicht mal von der Stelle rühren.}
{213}{}{Dich nicht von der Stelle rühren? So ein Quatsch!}
{214}{}{Du glaubst nicht, dass ich das mache? Biker-Ehrenwort – mir sollen die Eier abgeschnitten werden, wenn ich die Tore nicht von hier aus öffne.}
{215}{}{Moment, du hast doch was vor ...}
{216}{}{Ganz einfach. Ich bin mir selbst nicht ganz sicher, also – willst du wetten?}
{217}{}{Auf keinen Fall! Mach einfach das Tor auf.}
{218}{}{Kein Problem, ich mach's. Pass auf und staune!}
{219}{}{Ja, klar. Wer soll dir denn glauben, dass du sie aus der Ferne öffnen kannst ... Na schön, mal sehen.}
{220}{}{Warte, ich muss mich konzentrieren ...}
{221}{}{Aha ...}

#Cutscene of gates opening
{222}{}{*Er strengt sich so sehr an, dass er rot anläuft.*}
{223}{}{URRRRGGHH!!!}
{224}{}{Was! Er hat's geschafft!}
{225}{}{Ja! Habt ihr das gesehen, Leute!?}
{226}{}{Das kann ich nicht glauben ...}
{227}{}{Ha-ha-ha!}

#Upgrading guns and stuff
{230}{}{Lass mich dein Spielzeug sehen.}
{231}{}{Kannst du meine Lederrüstung verstärken?}
{232}{}{Hier ist eine abgenutzte Metallrüstung. Kannst du sie wieder herrichten?}
{233}{}{}
{234}{}{Ich hab's mir anders überlegt. Nicht nötig.}
{235}{}{So viel Geld habe ich nicht ...}
{236}{}{Kinderleicht. Ich mach's für }
{237}{}{ Dollar.}
{238}{}{Na gut. Hier ist das Geld. Ich warte.}
{239}{}{[Ein paar Stunden später bringt der Biker dir deine verbesserte brahmin-Lederrüstung mit Metallverstärkungen. Der versteht wirklich was von seinem Handwerk!]}
{240}{}{[Ein paar Stunden später bringt der Biker dir eine glänzende, verstärkte Metallrüstung. Sie sieht aus, als käme sie direkt vom Fließband!]}
{241}{}{Na, das nenne ich mal was!}

{242}{}{Hey! Ich werde deinen Scheiß nicht aufheben!}
{243}{}{Das ist aus Versehen runtergefallen. Ich heb's auf ...}

{244}{}{Was? Zeig her.}
{245}{}{Gewehr.}
{246}{}{Pistole.}
{247}{}{Eine andere Waffe.}
{248}{}{Zurück.}
{249}{}{Wie lange dauert's noch?}

{250}{}{Hast du ein Zielfernrohr für ein Jagdgewehr?}
{251}{}{Kannst du die Leistung des Plasmagewehrs erhöhen?}
{252}{}{Mach eine abgesägte Schrotflinte daraus.}
{253}{}{Ich möchte den Energieverbrauch des Lasergewehrs senken.}
{254}{}{Hey, jetzt wird's was! Genau mein Ding. Na gut. Ich mach dir einen Rabatt – einfach, weil mir das Spaß macht. Für }
{255}{}{Wow! Wo hast du dieses Schmuckstück her? Verdammt, ich schwöre, ich mach daraus ein Meisterwerk! Für }
{256}{}{Sturmgewehr. Was kannst du damit machen?}
{257}{}{Ich kann das Magazin erweitern. Für }
{258}{}{}
{259}{}{[Eine Stunde später bringt der Biker dir die Waffe. Da gibt's nichts zu meckern. Perfekte Arbeit!]}

{260}{}{Laserpistole – was meinst du, was lässt sich damit machen?}
{261}{}{Kannst du dieses brutale "Desert eagle" noch brutaler machen?}
{262}{}{Hier ist eine Plasmapistole. Was sagst du dazu?}
{263}{}{Kannst du die Nachladegeschwindigkeit des Magnum erhöhen?}
{264}{}{Hmm. Nettes Spielzeug. Ja. Ich habe ein paar Ideen, wie man es auffälliger machen kann. Für }

{270}{}{Ich habe Dynamit. Kannst du Dynamitstangen daraus machen?}
{271}{}{Kannst du einen Molotowcocktail machen?}
{272}{}{Ich überlege, was ich aus diesem brahmin Schlagstock machen könnte ...}
{273}{}{Diese Powerfaust ist irgendwie schwach. Mit bloßen Fäusten kann ich einen Mann schneller zu Tode prügeln ...}
{274}{}{Leichter, als jemandem das Höschen auszuziehen. Ich mach's für }
{275}{}{}
{276}{}{Wie wär's mit einem normalen Flammenwerfer?}

#Hitching a ride
{280}{}{Sag mal, was ist die nächste zivilisierte Stadt?}
{281}{}{Zivilisiert? Scheiße, hier findest du nichts, was *zivilisiert* ist.}
{282}{}{Du weißt, was ich meine.}
{283}{}{Na gut, gib mir deine Karte, ich zeig's dir. Hier ist New Reno. Ein großartiger Ort, genau, wie wir ihn mögen – Anarchie, Freiheit und Unabhängigkeit. Manchmal gehen wir dort im Casino abhängen. Hier liegt Salt Lake – eine langweilige Stadt. Aber immerhin friedlich. Mehr oder weniger. Und hier ist das Beste – Las Vegas. Vielleicht der wichtigste Ort in Nevada. Allerdings ist er weit weg.}
{284}{}{Stimmt. Danke für die Auskunft.}
{285}{}{Du hast ein Fahrzeug. Kannst du mich in die Stadt bringen?}
{286}{}{Jetzt gleich?}
{287}{}{Ich muss nach New Reno. [700$]}
{288}{}{Nein, später. Ich sag dir Bescheid, wenn es so weit ist.}
{289}{}{Ich muss nach Salt Lake. [700$]}
{290}{}{Ich muss nach Lovelock. [400$]}
{291}{}{Ich muss nach Wendover. [400$]}
{292}{}{Jemand hat nicht genug Kohle. Außerdem bin ich zu müde, um dorthin zu fahren. Verstanden?}
{293}{}{In Ordnung.}

#About surroundings
{294}{}{Und was ist das hier für ein Ort?}
{295}{}{Eine militärische Radarstation. Im Süden findest du die Ruinen einer Vorkriegssiedlung, und ringsum gibt es Berge und Wüste. Wenn du draußen herumstreifen willst, vergiss nicht, einen dicken Knüppel mitzunehmen – oder noch besser etwas, das einen Elektroschock verpasst.}
{296}{}{Warum?}
{297}{}{In den Ruinen gibt es jede Menge wilder Hunde. Normalerweise halten sie sich fern – sie haben Angst vor uns. Aber Außenseiter wie dich zerfleischen sie bis auf die Knochen.}
{298}{}{Wegen irgendwas mit „elektrischer Ladung“ – wozu ist das gut?}
{299}{}{In den Bergen nordöstlich von hier könnt ihr auf fliegende Roboter stoßen. Wir konnten nicht herausfinden, woher sie kommen oder was ihr Zweck ist. Aber wir wissen mit Sicherheit, dass sie alle humanoiden Wesen töten, denen sie begegnen. Du bist gewarnt.}

#Train repairing
{300}{}{[Schwer atmend betrachtet er den Computer und dreht ihn hin und her] Ein Kinderspiel. Ich wette, ihm fehlen ein Kondensator und ein Chip. Das lässt sich leicht reparieren.}
{301}{}{Wie viel willst du für deine Arbeit?}
{302}{}{1500. Ich würde mehr verlangen, aber du bist in Ordnung, also gebe ich dir Rabatt.}
{303}{}{Prima, der Preis ist in Ordnung. Hier ist das Geld. Ich warte auf das Ergebnis.}
{304}{}{Was soll das, Geld? Pfft ... Aber was kannst du sonst anbieten? Na gut. Gib mir 3000, dann versuche ich, das Ding zu reparieren.}
{305}{}{Ganz schön happige Preise, aber ich brauche es. Ich warte auf das Ergebnis.}
{306}{}{Ich überlege mir dein Angebot.}

{307}{}{Du hast einen Weg gefunden, den Zug zu reparieren.}

#PLC
{310}{}{So ein winziges, nerviges Ding. Aber ich krieg das hin. Was gibst du mir dafür? Ah, du hast nichts außer Geld. Na gut. Mein Preis: 1000 Kröten.}
{311}{}{Hier sind das Gerät und das Geld.}
{312}{}{Nicht nötig.}
{313}{}{Der Biker erledigte seine Lieblingsarbeit mit Bravour. Jetzt muss nur noch das Gerät zurück zur Fabrik gebracht werden.}

#Pickup 
{320}{}{Wow, für so ein kleines Ding zahl ich dir sogar selbst was!}
{321}{}{Ähm ... Ich brauche das Auto.}
{322}{}{Hey, kein Problem. Wir fahren sowieso lieber Motorrad, als in einem stickigen Auto durchgerüttelt zu werden.}
{323}{}{Na gut. Was ist mit einer Aufrüstung? Kannst du dir ansehen, was sich machen lässt?}
{324}{}{Na, mal sehen ...}
{325}{}{In Ordnung.}
{326}{}{Ja, ich habe ein paar Ideen. Weißt du, warum Beschleunigung und Geschwindigkeit so mies sind? Weil die Kontakte schwach sind, jede Menge Dreck zwischen den Teilen steckt und das Öl fast vollständig eingetrocknet ist ... Außerdem könnte ich noch ein paar Spezialteile einbauen. Das Ding wird fliegen!}
{327}{}{Gut. Und wie viel willst du für diese Überholung?}

{328}{}{Zwei Riesen. Einfach so. Wirklich. Aber es wird ein paar Tage dauern, sag ich dir.}
{329}{}{Na gut, ich warte. Hier sind 2000$.}
{330}{}{Nein, das ist zu teuer und dauert zu lange. Vielleicht später.}

{331}{}{Hey, Kumpel, wach auf!}
{332}{}{Hä!? Was!? Wo!?..}
{333}{}{Keine Panik! Dein Auto ist im Arsch.}
{334}{}{WAS?!!}
{335}{}{Das war's, sag ich dir, es ist hinüber. Raider, dieses Gesindel, sind reingerauscht, während ich pinkeln war.}
{336}{}{NEIN! AUF KEINEN VERFICKTEN FALL!!!}
{337}{}{Also, dein Auto wurde geklaut. Hättest besser aufpassen sollen.}
{338}{}{WAS ZUR HÖLLE!!!}
{339}{}{Ha-ha-ha!!!}
{340}{}{Warum zum Teufel lachst du!? Verstehst du nicht – das ist das Wertvollste, was ich hatte!}
{341}{}{Hahah! [wischt sich die Tränen weg] Du bist echt komisch, weißt du das!}
{342}{}{Was?.. Äh... War das etwa ein Witz?}
{343}{}{Da steht dein Auto, genau da, wo es hingehört. Alles normal. Ich meine, ich bin mit der Arbeit fertig, weißt du? Alles in Ordnung, der Motor ist ein Biest, die Beschleunigung – einfach unglaublich!}
{344}{}{Grhmm... Dieser Biker-Humor...}
{345}{}{Sei kein Weichei! Wenn du sonst noch was brauchst, komm vorbei, wir helfen dir.}
{346}{}{Ja... Vielleicht. Mach's gut.}

{347}{}{Der Biker hat die Motorsysteme des Pick-ups verbessert. Jetzt fährt das Auto viel schneller als zuvor.}

#Alien blaster
{400}{}{Dieser Blaster schießt nicht...}
{401}{}{Tatsächlich... Es scheint, als wäre im Inneren ein Sicherheitssystem ausgelöst worden, das der Vorbesitzer eingebaut hat. Den Schraubenzieherspuren nach zu urteilen, hat jemand versucht, es zu entfernen. Hmm... Gib mir etwas Zeit, vielleicht finde ich heraus, wie man das repariert. Aber ich brauche etwas Geld für ein Bier... Nur 3000 Mäuse.}
{402}{}{Das ist zu viel!}
{403}{}{Lass es vorerst. Sieh dir die andere Waffe an, die ich habe.}
{404}{}{Glaub mir, an solche Technologie kommt man nur schwer heran. Siehst du das Zeichen von Area 51? Nur Gott weiß, was dort vor sich ging, aber ich kann dir sicher sagen: Es lohnt sich.}
{405}{}{Okay, abgemacht.}
{406}{}{Großartig. Also, wie gesagt: Ich nehme den Auftrag nur für 3000 Kronkorken an.}
{407}{}{Nimm alles, was du brauchst!}
{408}{}{Jetzt nicht.}
{409}{}{Nein, abgemacht ist abgemacht.}
{410}{}{Wie auch immer, ich finde es schon allein heraus!}
{411}{}{Äh, ich muss erst nachsehen.}
{412}{}{Oh ja! Dieses süße Ding verdient einen guten Besitzer. Hüte es gut, so eins findest du kein zweites Mal. Trotzdem weiß ich nicht, wo du die „Batterien“ dafür herbekommst. Wenn ich du wäre, würde ich dort suchen, wo es herkommt – in Area 51.}
{413}{}{Danke.}

#Station gates - additional dialogue
{420}{}{Ich kann bezahlen.}

{421}{}{[Enttäuscht] Geld ... Geld mag ich nicht. Leere deine Taschen aus – hast du irgendwelche Drogen? Über Psycho würde ich mich freuen. Ein stimpak tut's auch.}
{422}{}{Stimpak.}
{423}{}{Mentats.}
{424}{}{Buffout.}
{425}{}{Psycho.}
{426}{}{Anti-Raucher.}
{427}{}{Schmerzmittel.}
{428}{}{}
{429}{}{Nichts ...}

{430}{}{[Zuckt nur mit den Schultern und wendet sich ab]}
{431}{}{[Nimmt die Dosis, untersucht sie, riecht daran und steckt sie ein] Nicht schlecht.}
{432}{}{Hey, wir hatten einen Deal – mach die Tür auf!}

#Power armor info
{450}{}{Erzähl mir von deiner Rüstung. Sie interessiert mich sehr.}

{451}{}{Sie interessiert dich? Wirklich? Über alte Technologie kann ich stundenlang reden. Aber dafür brauche ich etwas, das mir die Kehle befeuchtet, weißt du?}
{452}{}{Hier, ein Bier. Nur zu!}
{453}{}{Ah, stimmt. Wenn ich etwas zu trinken finde, komme ich wieder.}
{454}{}{Dann ein andermal, falls du noch interessiert bist.}

{455}{}{Das habe ich dir doch schon gesagt. Schlechtes Gedächtnis?}
{456}{}{Ich muss nur noch etwas klarstellen.}
{457}{}{Das ist eine andere Geschichte. Aber was willst du wissen?}
{458}{}{Na gut. Was willst du wissen?}

{459}{}{Woher hast du diese Rüstung?}
{460}{}{Was für eine Rüstung ist das?}
{461}{}{Würdest du sie verkaufen oder gegen etwas eintauschen?}
{462}{}{Könntest du eine solche herstellen?}

{463}{}{Wenn ich es dir erzähle, muss ich dich umbringen. Ha-ha, nur ein Scherz. Eigentlich ist diese Geschichte wirklich nichts für deine Ohren.}
{464}{}{Das wollte ich alles wissen.}
{465}{}{Powerrüstung T-51b, Vorkriegsmodell. Aber ich hab nicht so viel Glück, wie es scheint. Einige Teile funktionieren nicht, obwohl sie alle grundlegenden Funktionen erfuellt – sie schützt mich vor Kugeln und Strahlung und verstärkt außerdem meine Kraft. Im Inneren steckt eine Fusionszelle, die das Modul antreibt, das jede meiner Bewegungen verstärkt. Nur zu deiner Information: Die Amerikaner hätten in Anchorage ganz schön alt ausgesehen, wenn es die T-51 nicht gegeben hätte.}
{466}{}{Auf keinen Fall. Diese Rüstung ist meine zweite Haut geworden. Du bekommst sie nur von meiner Leiche runter, und so bald wird das nicht passieren. Sollte es jemals so einen Idioten geben, der mich umbringen kann, dann merk dir eins: Die Rüstung lässt sich unmöglich unbeschädigt abnehmen. Um sie ihrem toten Besitzer auszuziehen, musst du zuerst die äußere Panzerung schwer beschädigen.}
{467}{}{Du glaubst, ich schnapp mir einen Lötkolben und baue mal eben nach, woran die Amerikaner jahrelang gearbeitet haben? Vor dem Krieg haben Hunderte Spezialisten mit ihrer Präzisionstechnik daran gearbeitet, und alles, was ich hier habe, sind meine Jungs – die rechte Hand, um Gesichter zu verprügeln, und die linke, um das Lenkrad zu halten, während die rechte ihre Arbeit macht. Dabei würde ich die Produktion liebend gern in Massen aufziehen – ich habe sogar einige der Originalbaupläne gefunden –, aber unter den derzeitigen Bedingungen ist das einfach unmöglich.}
{468}{}{Warte, Baupläne?! Du hast sie?! Warum hast du das nicht gleich gesagt!}
{469}{}{Du brauchst sie wirklich? Hmm. Du hast dich bei diesen Frühreifen in Reno gut bewährt und verdienst unseren Respekt. Also gut – ich teile sie mit dir. Du bist ein guter Junge.}
{470}{}{Verdammt richtig!}
{471}{}{Du hast Baupläne für eine Powerrüstung erhalten.}
{472}{}{Du brauchst sie wirklich? Hmm. Ich glaube nicht, dass ich irgendetwas mit dir teilen will.}
{473}{}{Ich kann sie kaufen.}
{474}{}{Ich kann es mir verdienen.}
{475}{}{So ist es schon besser. Löse das Problem in Reno, und die Sachen gehören dir.}
{476}{}{Vielleicht kannst du sie mir einfach verkaufen?}
{477}{}{Oh, das ...}
{478}{}{Du scheinst ein fähiger Kerl zu sein, wenn du es bis hierher geschafft hast und mich zur Rede stellst. Es gibt einen Auftrag, für den ich zu zahlen bereit bin.}
{479}{}{Erzähl mir mehr.}
{480}{}{[Kratzt sich nachdenklich am Kinn] Vergiss es. Wir mögen kein Geld.}
{481}{}{Vielleicht kann ich es mir dann verdienen?}
{482}{}{Ich bin bereit zu zahlen. Hier sind 5000.}
{483}{}{Das ist zu teuer. Also vorerst nicht.}
{484}{}{Wenn irgendein Schurke versucht, mich übers Ohr zu hauen, werde ich normalerweise richtig wütend. Und glaub mir – das endet immer übel ... für ihn.}
{485}{}{...}

#############################################################################
#
#        Quest - set up for bikers
#
#############################################################################

#Quest obtaining - NOT USED, except couple of lines
{500}{}{Das hört man in Nevada nicht oft ...}
{501}{}{Vielleicht interessiert mich das nicht. Entschuldige und ... mach's gut.}
{502}{}{Das stimmt. Was innerhalb einer Bande passiert, bleibt innerhalb der Bande. Wir sind selbstständig genug, um uns nicht in die örtlichen Fehden in Städten und Siedlungen einzumischen. Und manche machen sich das zunutze.}
{503}{}{Worauf willst du hinaus?}
{504}{}{Normalerweise bleiben nach uns nur märchenhafte Geschichten über Saufereien und Schlägereien zurück, aber in letzter Zeit flüstern böse Zungen schlechte Neuigkeiten.}
{505}{}{Was meinst du damit?}
{506}{}{Jemand ruiniert unseren Ruf im Staat, indem er in Siedlungen und Städten im Westen Probleme verursacht. Natürlich sind auch wir nicht abgeneigt, Beute zu machen, aber das, was diese Bastarde in unserem Namen treiben, grenzt an Raub. Und Nevadas Biker sind keine Banditen.}
{507}{}{Vielleicht kann ich helfen?}
{508}{}{Hm, das ist keine schlechte Idee. Dann spitz die Ohren und hör gut zu, denn ich bezahle für die Arbeit.}
{509}{}{Okay, was muss ich tun?}
{510}{}{Ich will mich nicht mit so gefährlichen Leuten einlassen. Also ohne mich.}

{511}{}{Wir müssen diese Bastarde finden und bestrafen. Wie genau, ist mir egal. Als Beweis, dass die Sache erledigt ist, bring mir die Jacken, mit denen sie die Bevölkerung einschüchtern. Niemand außer uns darf sie tragen. Außerdem wurden sie den Leichen getöteter Biker abgenommen, was für uns mindestens genauso wichtig ist.}
{512}{}{Ich bin dabei.}
{513}{}{Ausgezeichnet. Ich warte auf Nachricht. Wenn du willst, bringe ich dich nach Reno und setze dich am Stadtrand ab, damit du nicht selbst auffliegst. Wir können die Mistkerle nicht finden, weil irgendjemand sie per Funk vor uns warnt. Sie schaffen es immer, sich zu verstecken.}
{514}{}{Los geht's!}
{515}{}{Danke, aber nicht jetzt. Ich gehe allein.}

{516}{}{Und ich dachte, ihr seid selbst Banditen.}
{517}{}{Wenn es sein muss, schlachten wir jeden verdammten Hurensohn ab. Aber wir tun es weder fürs Essen noch zum Vergnügen.}
{518}{}{Ja. Und?}
{519}{}{}

#Quest done - NOT USED, OLD
{520}{}{Wegen des Auftrags.}
{521}{}{Was, kapierst du's immer noch nicht?}
{522}{}{Nein, du Schlaumeier, die Sache ist erledigt – ich habe die Jacken dabei.}
{523}{}{Warum könnt ihr nicht selbst mit den Bastarden fertigwerden?}
{524}{}{}
{525}{}{Du hast versprochen, mich nach Reno zu bringen ...}
{526}{}{Warum ... Na gut, vergessen wir's.}
{527}{}{Für so eine Sache bringe ich dich hin, kein Problem. Fahren wir jetzt los?}
{528}{}{Ja.}
{529}{}{Nein, warte.}
{530}{}{Wir können nicht tagelang vor Reno warten, denn niemand weiß, wann und wo diese Mistkerle wieder auftauchen. Außerdem haben wir Gerüchte gehört, dass Barkeeper irgendjemanden per Funk vor unserem Kommen warnen. Sie schaffen es immer, sich zu verstecken. Du siehst nicht aus wie einer von uns, also kannst du sie leichter überraschen.}
{531}{}{Verstanden.}
{532}{}{Gute Arbeit. Du hast uns einen großen Gefallen getan. Unser Ruf ist in Nevada ohnehin nicht der beste, aber dass diese Dreckskerle in unserem Namen randalieren ... so etwas verzeihen wir nicht. Ich hoffe, sie haben ihre volle Dosis abbekommen?}
{533}{}{Äh, ja, ich habe es so gemacht, wie es nötig war.}
{534}{}{Ausgezeichnet. Hier ist dein Lohn. Ich glaube, wir sollten uns ab jetzt öfter sehen – du gefällst uns.}
{535}{}{Hast du endlich Respekt gelernt? Na also.}
{536}{}{Warte. Man spricht viel Gutes über dich. Ich weiß, wie schwer es ist, immer ehrlich und anständig sein zu wollen. Bei mir klappt's jedenfalls nicht, aber du ... (zieht einen Revolver) Nimm ihn. Du musst dich immer vor Abschaum schützen können.}
{537}{}{Dafür danke ich dir!}

{538}{}{Was glaubst du, wer sind die Leute, die euch in die Pfanne hauen?}
{539}{}{Wahrscheinlich die örtlichen Straßenrowdys in New Reno. Möchtegerns, die ihren Überlebensinstinkt verloren haben. Andererseits haben wir genug Feinde. Es könnte also jeder gewesen sein.}

#quest: stagecoach robbery - NOT USED 
{540}{}{Hast du irgendetwas über den Kutschenüberfall bei Black Rock gehört?}
{541}{}{Die Einheimischen haben irgendwas erzählt, aber das interessiert mich nicht. Das waren bestimmt Raider.}
{542}{}{Manche glauben, dass die Biker dahinterstecken.}
{543}{}{Was soll das heißen? Glaub den bösen Zungen nicht. Du kannst dir gar nicht vorstellen, wie viele Neider und Missgünstige es inzwischen auf unsere Bande abgesehen haben. Aber wir sind keine Banditen und überfallen keine Kutschen. Wir haben damit nichts zu tun.}
{544}{}{Na gut.}

#The first quest of Phil - the Reno investigation
{550}{}{Man hört nicht viel über euch in Nevada ...}
{551}{}{}
{552}{}{Ganz genau. Was in der Bande geschieht, bleibt in der Bande. Wir sind selbstständig genug, um uns nicht in die örtlichen Konflikte der Städte und Siedlungen einzumischen. Und in letzter Zeit nutzt offenbar jemand das aus.}
{553}{}{Wovon redest du?}
{554}{}{Das ist seltsam. Plötzlich meiden alle Karawanenhändler in der Gegend um New Reno uns. Früher kamen wir gut miteinander aus, doch jetzt sind sie äußerst misstrauisch und greifen jedes Mal nach ihren Waffen, wenn sie uns sehen, als hätten sie Angst vor etwas. Ich würde der Sache selbst nachgehen, aber niemand will auch nur mit uns reden. Mit dir würden sie aber reden.}
{555}{}{Was soll ich tun?}
{556}{}{Finde zunächst heraus, warum unser Ruf so schlecht geworden ist, was über uns erzählt wird und wer die üblen Gerüchte verbreitet. Jede Information ist wichtig.}
{557}{}{Klingt einfach. Ich übernehme den Auftrag.}
{558}{}{Ich glaube, das interessiert mich nicht. Tut mir leid, auf Wiedersehen.}
{559}{}{Gut. Komm wieder, wenn du etwas herausgefunden hast. Wenn du willst, kann ich dich nach Reno fahren und am Stadtrand absetzen, damit ich nicht auffalle.}

{560}{}{Wegen des Auftrags.}
{561}{}{Was ist hier los, verdammt?}
{562}{}{Es heißt, ihr hättet die Postkutsche überfallen und ausgeraubt. Das ist in der Nähe von Black Rock passiert.}
{563}{}{Ähm, ich sehe mir das noch an.}
{564}{}{Dann trödel nicht.}
{565}{}{Na gut.}
{566}{}{Wir? Die Postkutsche ausgeraubt?! So ein Bullshit! Wer hat dir das erzählt?}
{567}{}{Die Angestellten von "Nevada Express" haben es mir selbst erzählt.}

{568}{}{Hm. Ich weiß nicht, warum sie das glauben. Wir müssen der Sache auf den Grund gehen und ermitteln. Übernimmst du das für uns?}
{569}{}{Schon erledigt. Ich war am Tatort und habe ein paar Hinweise gefunden – dieses DVR-Protokoll vom Roboter.}
{570}{}{Ich war am Tatort und habe ein paar Hinweise gefunden – dieses DVR-Protokoll vom Roboter.}
{571}{}{Ich arbeite noch daran.}
{572}{}{Warum sollten wir dir glauben?}
{573}{}{Gute Frage. Warum sollten wir dir vertrauen? Na schön, wenn du nicht willst, kümmern wir uns selbst darum – ohne dich.}
{574}{}{Ich überleg's mir.}
{575}{}{Na schön, ich sehe mir euer Problem an. Wartet auf Neuigkeiten.}
{576}{}{Du hast versprochen, mich nach Reno zu bringen ...}

{580}{}{Ist das hier gemeint?}
{581}{}{Auch wenn ich die Daten darauf nicht entschlüsseln kann ...}
{582}{}{Ja, ich habe die Daten darauf bereits entschlüsselt.}

{583}{}{Du kannst es nicht? Ha, natürlich nicht. Schätzchen, für diesen Job braucht man einen klugen Kopf. Überlass das einem echten Profi und verschwende keine Zeit.}
{584}{}{[Warten]}
{585}{}{Warte, ich versuche es lieber selbst. Ein bisschen Erfahrung kann nicht schaden.}
{586}{}{Na, da klingt der Vogel jetzt aber ganz anders ...}
{587}{}{Wovon redest du?}
{588}{}{Die Kerle, die den Roboter eingerichtet haben, waren keine Idioten. Sie haben ihn so eingestellt, dass er nicht nur das Gelände, sondern auch die ganze Mannschaft überwacht. Diese Mistkerle, die ihre eigene Postkutsche ausgeraubt haben, scheinen nicht mal zu wissen, dass sie dabei aufgenommen werden. Hey, das reicht nicht nur, um unseren Namen reinzuwaschen, sondern auch, um "Nevada Express" unglaubwürdig zu machen. Was meinst du?}
{589}{}{Das haben sie verdient! Beim nächsten Mal überlegen sie es sich besser.}
{590}{}{Schuld sind nur zwei Arschlöcher. Es ist nicht fair, deswegen den Ruf aller anderen zu ruinieren.}
{591}{}{Tuco wird diese Nachricht nicht gern hören, aber sie werden uns nicht länger hassen. Und wenn wir die Sache einfach stillschweigend regeln, werden die Leute uns trotzdem nicht vertrauen. Unser Interesse ist offensichtlich.}
{592}{}{Richtig. Ich sehe, was sich machen lässt.}
{593}{}{Wir zählen auf dich.}
{594}{}{Tschüss.}
{595}{}{}

{596}{}{Dein Problem in Reno ist gelöst. Jetzt glauben alle, dass der Angriff von unbekannten Räubern verübt wurde und man dich zu Unrecht beschuldigt hat.}
{597}{}{Ich fürchte, dein Problem lässt sich nicht lösen. Diese Bastarde von „Nevada Express“ haben die Beweise an sich genommen.}
{598}{}{Dein Problem in Reno ist erledigt. Tuco hat die Beweise geprüft und eine öffentliche Strafe verhängt. Jetzt wissen alle, dass der Angriff von einigen aus den eigenen Reihen verübt wurde.}
{599}{}{Gute Arbeit! Genau das brauchen wir. Ich wäre nie darauf gekommen, ihnen falsche Hinweise unterzuschieben, aber du ... Du bist clever.}
{600}{}{Danke.}
{601}{}{Na gut, steh nicht einfach so herum. Ich habe die Belohnung nicht vergessen. Hier, nimm sie [gibt dir eine Laserpistole]. Sie gehört dir.}
{602}{}{Nicht schlecht.}
{603}{}{Gute Arbeit! Natürlich ist es schade, dass der Ruf der Firma wegen zweier Idioten Schaden genommen hat, aber was kümmert uns das schon, oder?}
{604}{}{Ja.}
{605}{}{Verdammt, diese Arschlöcher beruhigen sich immer noch nicht?! Ich hab genug davon! Wenn sie meinen, ihr Ruf sei wichtiger, sollen sie daran ersticken, wenn ich ihnen beim nächsten Treffen meine Plasmakanone entgegenhalte!}
{606}{}{Whoa, so schlimm ist es doch nicht ...}
{607}{}{Klar – für *uns* ist es nicht so schlimm ... Na schön, kümmern wir uns erst mal um dich. Ich habe die Belohnung nicht vergessen. Aber du warst nicht so nützlich, wie ich gehofft hatte. Was ist deine Arbeit wert? Ich denke, 200 reichen. Mehr gibt's nicht.}
{608}{}{Immerhin etwas.}

#Female character
{1103}{}{Wach auf, Schwesterherz! Du hast lange geschlafen.}
{1112}{}{Was geht, Wanderer? Setz dich, lass uns reden!}
{1123}{}{Natürlich niemand. Das ist ein Geisterzug. Was, noch nie davon gehört?}
{1140}{}{Na, bist du nicht der Verfolger entlaufener Mädchen? Im Ödland trifft man selten Leute wie dich. Verleih dir eine Medaille, damit dich jeder sofort erkennt.}
{1142}{}{Sauer? Ich? Ha! Soll ich mich vielleicht auch noch auf dem Klo einschließen und heulen? Nein, es ist mir ziemlich egal. Mit ihr war es lustig, aber andererseits ... Na ja, du hast eine gute Tat vollbracht und den ganzen Mist - die Tochter ihrem Vater zurückgebracht. Ich finde, das ist bewundernswert.}
{1160}{}{[Sie sehen einander an und lachen über dich] Hast du schon mal von Bikern gehört?}
{1161}{}{Vielleicht. Ihr seid so etwas wie eine Gang, oder?}
{1176}{}{Vergiss es, ich habe es mir anders überlegt.}
{1207}{}{Verstanden. Was willst du dafür haben?}
{1234}{}{Ich hab's mir anders überlegt. Nicht nötig.}
{1321}{}{Ähm ... Ich brauche das Auto.}
{1331}{}{Hey, Schwesterherz, wach auf!}
{1341}{}{Hahah! [wischt sich die Tränen weg] Du bist echt komisch, weißt du das!}
{1405}{}{Okay, abgemacht.}
{1469}{}{Brauchst du sie wirklich? Hm. Du hast dich bei diesen Frühreifen in Reno gut geschlagen und verdienst unseren Respekt. Also gut – ich teile sie mit dir. Du bist ein gutes Mädel.}
{1478}{}{Du scheinst fähig zu sein, wenn du es bis hierher geschafft hast und mich befragst. Es gibt einen Auftrag, für den ich zu zahlen bereit bin.}
{1530}{}{Wir können nicht tagelang bei Reno herumlungern. Niemand weiß, wann und wo diese Mistkerle wieder auftauchen. Wir haben auch Gerüchte von Barkeepern gehört, dass irgendwer die Bastarde per Funk vor unserem Kommen warnt. Sie schaffen es immer, sich aus dem Staub zu machen. Du siehst nicht aus wie eine von uns, deshalb kannst du sie leichter überraschen.}
{1532}{}{Gute Arbeit. Du hast uns einen großen Gefallen getan. Von uns hält man in Nevada ohnehin nicht viel, und wenn diese Dreckskerle in unserem Namen anfangen, Ärger zu machen ... so etwas verzeiht man nicht. Ich hoffe, sie haben ordentlich was abbekommen?}
{1533}{}{Äh, ja, ich habe getan, was nötig war.}
{1563}{}{Ähm, ich sehe mir das noch an.}
{1582}{}{Ja, ich habe die Daten schon von dem Ding.}
