{100}{}{Du siehst Jasmine.}
{101}{}{Du siehst ein Mädchen mit einem roten Schal um den Hals.}
{102}{}{Danke fürs Geld. Bei der ersten Gelegenheit bin ich weg von hier.}
{103}{}{Mir geht's nicht besonders gut ...}

#Starting converstaion
{109}{}{Und deiner?}
{110}{}{[Du siehst ein Mädchen mit wunderschönem Haar und einem roten Schal um den Hals. Sobald sie deinen Blick erwidert, lächelt sie kokett.] Na, hallo, Hübscher. Neu in der Stadt? Ich würde *alles* für ein bisschen Unterhaltung hier geben. Bist du nur auf der Durchreise oder willst du bleiben?}
{111}{}{Freut mich. Ich heiße }
{112}{}{Wer bist du?}
{113}{}{Kannst du dich nicht mit den Leuten hier unterhalten?}
{114}{}{Ist dir in dem Schal nicht heiß?}

{115}{}{Baby? Warum hast du mich „Baby“ genannt?}
{116}{}{Warum bin ich „Baby“?}
{117}{}{Keine Sorge, Baby. Nur, weil ich dich mag.}

{120}{}{Was für ein schöner Name! Ich bin Jasmine. Freut mich.}
{121}{}{Hmm, wie sag ich's ... Früher habe ich auf den Feldern gearbeitet, jetzt erhole ich mich. Reicht dir das, Baby?}
{122}{}{[Sie verschränkt die Arme und verzieht mürrisch das Gesicht.] Hmpf! Mit den Leuten hier zu reden bringt nichts. Frag nicht, Baby, ich habe meine Gründe.}

{123}{}{Ach du meine Güte! [Sie lächelt verschmitzt und beginnt, ihr Hemd aufzuknöpfen.] Wenn du willst, kann ich alles ausziehen, Baby.}
{124}{}{Äh ... Warum?}
{125}{}{Wirklich? Das würdest du tun?}
{126}{}{[Sie lacht] Ist das dein Ernst? Du weißt es wirklich nicht? [Sie legt einen Finger unter dein Kinn und zwinkert] Keine Sorge, Baby. Ich bin eine großartige Lehrerin.}
{127}{}{[Sie legt dir die Hand auf die Schulter] Baby, ich kann noch viel mehr als das. Leg deine Hand einfach hierhin ...}
{128}{}{Whoa! Was ist das unter deinem Schal?!}
{129}{}{[Der verführerische Ausdruck verschwindet aus ihrem Gesicht. Sie stößt dich weg und dreht dir den Rücken zu] Jedes verdammte Mal! Erst läuft's gut, aber dann ein einziger Blick und ... [Sie seufzt] Geh einfach.}
{130}{}{Jasmine?}

#Second dialogue
{150}{}{[Sie starrt dich stumm und ausdruckslos an und wartet darauf, dass du gehst.]}
{151}{}{[Still gehen]}

{152}{}{Kann ich dich ein paar Dinge über Black Rock fragen?}
{153}{}{[Sie runzelt die Stirn] Glaubst du, ich weiß irgendwas? Frag in der Bar, die halten nie den Mund. Die lassen mich nicht mal rein.}
{154}{}{Tschüss.}

{155}{}{Wie bist du hier gelandet?}
{156}{}{Daddy - mein richtiger Daddy - hat mich aus Reno rausgeschmissen. Er dachte, er könnte mich vor meinem Leben dort retten. Dann wurde er von einem Rudel Geckos gefressen und jetzt verhungere ich hier ganz allein. Ist das nicht ironisch?}
{157}{}{Was hast du dort gemacht?}
{158}{}{Oh mein Gott, du kapierst es wirklich nicht? Ich bin eine Hure, eine verdammte billige Hure! Jeder Dreckskerl konnte mich für fünfzig Bucks haben, und das war noch bevor mein Zuhälter seinen Anteil kassiert hat.}
{159}{}{Tut mir leid. Ich wollte dich nicht aufregen.}
{160}{}{Reden wir über etwas anderes.}
{161}{}{Wegen was?}
{162}{}{Arbeit ist Arbeit. Das stört mich nicht.}
{163}{}{Also ... Was ist eine „Hure“?}
{164}{}{[Sie starrt dich mit weit aufgerissenen Augen an] Verarschst du mich? Oh mein Gott, das ist dein Ernst. Heilige Scheiße ... Eine Jungfrau, in deinem Alter ...}
{165}{}{Was?}
{166}{}{Wenn ich nicht krank wäre, Baby, würde ich's dir zeigen ... Für fünfzig Bucks. Aber im Moment sollte mich niemand anfassen.}

{170}{}{Jasmine, was passiert mit deiner Haut?}
{171}{}{[Sie seufzt] Du willst es wirklich wissen? Ich hab diesen furchtbaren Scheiß auf der Haut - bis jetzt nur ein paar Pickel, aber keiner weiß, was als Nächstes passiert. Die Leute haben mich angestarrt und hinter meinem Rücken geredet ... Ich muss diesen Schal tragen, damit sie es nicht sehen.}
{172}{}{Darf ich mal sehen?}
{173}{}{Wow, ich glaube, mir wird gleich schlecht. Ich sollte besser gehen.}
{174}{}{[Sie zögert, dann wickelt sie schweigend den Schal ab. An der Seite ihres Halses siehst du eine große Ansammlung geschwollener, schmerzhaft aussehender Blasen.]}
{175}{}{Das ist definitiv eine Infektion, wahrscheinlich sexuell übertragbar. Ich glaube, man kann sie heilen, aber du brauchst antibakterielle Medikamente.}
{176}{}{Wirklich? Ich dachte, das würde mein ganzes Leben lang immer schlimmer werden! Aber ich kann nicht einfach irgendein Medikament kaufen. Selbst wenn ich das Geld hätte, wo zum Teufel sollte ich es herbekommen?}
{177}{}{Du hast 100 Erfahrungspunkte für die richtige Diagnose erhalten.}
{178}{}{Das sieht ziemlich übel aus. Weißt du, was es ist?}
{179}{}{[Sie zuckt traurig mit den Schultern.] Nein, nur dass es schlimm ist.}
{180}{}{Von mir. [Gib ihr eine Flasche Blutreiniger.]}
{181}{}{Wo hast du das her?}
{182}{}{Wahrscheinlich von irgendeinem Junkie in Reno oder einem der anderen Mädchen. Du kannst dir gar nicht vorstellen, mit was für Typen ich schlafen musste ...}
{183}{}{Hast du andere Leute damit gekannt?}
{184}{}{Ja. Ungefähr jede zehnte Hure in Reno hat es. Keine lebt lange – meistens nehmen sie Gift und sterben. So geht es schneller.}
{185}{}{Falls ich jemals in Reno bin, werde ich daran denken. Pass auf dich auf.}

{186}{}{Ich besorge dir das Medikament, keine Sorge.}
{187}{}{}
{188}{}{}
{189}{}{Ich werde versuchen, das Heilmittel für dich zu finden.}
{190}{}{Ich weiß, das ist unangenehm, aber wir müssen über deine Haut reden.}

{191}{}{Hast du nicht versucht, zu einem Arzt zu gehen?}
{192}{}{Zeig mir deine Hautkrankheit.}
{193}{}{Siehst du hier irgendwo verdammte Ärzte? Selbst in Reno muss man ständig Betäubungsmittel von Dealern kaufen, damit es nicht zu schlimm wird. Ich glaube, Jed, der alte Mann, der neben Justin wohnt, hat mir erzählt, dass sie es in Reno vor langer Zeit mit irgendeiner Pflanze heilen konnten, aber mehr weiß ich nicht. Ich weiß nicht einmal, ob das stimmt.}
{194}{}{Im Ernst? Du willst mir wirklich helfen? [sie lächelt] Danke! Ich dachte nicht, dass es überhaupt jemanden interessiert! Versuch, mit Jed zu reden – er sagte, er kenne ein Heilmittel aus irgendeiner Pflanze oder so, aber er weiß nicht mehr, wie man es herstellt. Vielleicht kannst du etwas aus ihm herausbekommen.}
{195}{}{Na gut.}

#Let's talk about your cure
{200}{}{Reden wir über dein Heilmittel.}
{201}{}{Ja?}
{202}{}{Ich habe dieses Heilmittel für dich. [gib ihr den Kolben mit Blutreiniger]}
{203}{}{Ich habe dieses Heilmittel für dich. [gib ihr den Kolben mit Gift]}
{204}{}{Tut mir leid, noch nichts.}

{205}{}{Oh mein Gott! Danke, danke, danke! [sie schnappt sich das Heilmittel] Ich dachte nicht, dass es auf der Welt wirklich Leute wie dich gibt! Du bist mein verdammter Schutzengel, du hast mir mein Leben zurückgegeben! Ich schwöre, ich werde nie wieder für Geld mit jemandem schlafen!}
{206}{}{Ich hoffe, es hilft.}
{207}{}{Trink unbedingt alles aus.}
{208}{}{So oder so hast du die Infektion aus der Gemeinschaft entfernt.}
{209}{}{Dank dir ist Jasmine auf dem Weg der Besserung.}
{210}{}{Was könnte dich deiner Meinung nach heilen?}
{211}{}{[Sie zuckt hilflos mit den Schultern] Woher zum Teufel soll ich das wissen? Der alte Jed weiß vielleicht etwas – er sagte, es gäbe da diese Pflanze, die das heilen könnte, aber an den Rest erinnert er sich nicht.}

#Banish her
{220}{}{Jemand hat mir gesagt, dass man deine Infektion hier nicht haben will. Nichts Persönliches, Jasmine.}
{221}{}{[Sie seufzt] Sie haben sich also endlich entschieden? Verdammt, ich wusste, dass es so kommen würde. Aber ich hatte gehofft, sie würden wenigstens selbst herkommen, damit ich ihnen ins Gesicht spucken kann.}
{222}{}{Du musst woanders hinziehen. Zu deinem eigenen Wohl.}
{223}{}{Ich bin nicht zum Reden hier. Verschwinde jetzt, oder stirb!}
{224}{}{Darüber reden wir später.}
{225}{}{Du meinst, ich gehöre nicht hierher? Wahrscheinlich hast du recht ... Aber die Karawane meinte, ich müsste hundert Dollar zahlen, um mitzufahren! Ich habe kein Geld!}
{226}{}{Hier sind hundert Dollar.}
{227}{}{[Sie sieht fassungslos aus] Du ... Meinst du das ernst? Ich dachte nicht, dass jemand dafür bezahlen würde, mich loszuwerden. Na gut, ich verstehe. Ich verspreche, mit der nächsten Karawane mitzufahren.}
{228}{}{Das solltest du besser tun. Ich werde dich im Auge behalten.}
{229}{}{}

{230}{}{A-aber ich kann das nicht!}
{231}{}{Ich habe dich gewarnt. [Angriff]}
{232}{}{Und warum nicht?}
{233}{}{Du kannst vorerst bleiben, aber später reden wir darüber.}
{234}{}{Ich habe kein Geld für einen Planwagen! Niemand hilft mir, und nicht einmal verkaufen kann ich mich! Ich kann nicht einmal nach Reno zurück, Daddy hat unser Haus verkauft! Ich lande auf der Straße!}
{235}{}{Nein, du landest unter der Erde. [Angriff]}
{236}{}{Ja, das ist wirklich traurig. Aber die Einheimischen wollen dich hier nicht mehr haben. Du musst gehen.}

#After curing her
{250}{}{Mein Schutzengel!}
{251}{}{Wie geht es dir?}
{252}{}{Reden wir noch mal über deine Krankheit. Wie hast du dich angesteckt?}
{253}{}{Wo sonst? Reno. Jede Hure dort hat irgendeine Krankheit. Die Großstadt versucht auf eine von einer Million Arten, dich umzubringen.}
{254}{}{Großartig! Meine Haut ist noch gezeichnet, aber ich fühle mich stark und gesund. Und das alles dank dir!}
{255}{}{Ruh dich jetzt aus.}

{260}{}{Da du geheilt bist, kommst du in dieser Stadt zurecht?}
{261}{}{Na ja ... [sie seufzt] Ich bin ... einsam. Niemand wird mehr versuchen, mich zum Gehen zu bewegen oder umzubringen, aber jeder weiß noch, was ich früher in Reno gemacht habe. Ich ... ich wollte schon immer eine Familie, aber ... [sie schüttelt den Kopf] Ich schätze, das wird nie passieren.}
{262}{}{Würde hier niemand eine Familie mit dir gründen?}
{263}{}{Wer würde mich schon wollen? Kein normaler Typ will eine abgehalfterte Hure.}
{264}{}{Muss er normal sein? Wie wär's mit Totengräber Bob?}
{265}{}{Na ja, man weiß ja nie. Es gibt immer Hoffnung.}
{266}{}{Ach, hör auf mit dem Unsinn.}

{267}{}{[Sie lacht] Bob?! Dieser komische Trottel? Der ist alt! Ich meine, nicht zu alt für Kinder, aber ... Sieh dir seinen Kopf und den Zahn an! Er ist so hässlich, dass er ... nicht mal vor einer abgehalfterten Frau wie mir zurückschrecken würde! Und er stottert, was irgendwie ... na ja, auf eine gewisse Art süß ist, aber ... Er lebt allein, genau wie ich ... Und ... Und er ist fleißig und wirklich irgendwie lieb, und er stinkt nicht *so* sehr, verglichen mit manchen Typen in Reno, und ... Hmmm. Ich meine ... Aber, weißt du ... diese eine Sache.}
{268}{}{Welche Sache?}
{269}{}{}

{270}{}{Er, äh ... Wie soll ich es sagen? Die Leute sagen, er, äh ... „schändet“ die Leichen. Wenn das stimmt, ist er ein Irrer! Ich will nicht mit einem Psychopathen zusammenleben! Glaubst du, ich kann ihm trauen?}
{271}{}{Du vertraust mir doch, oder? Ich sage dir: Hör nicht auf diese Gerüchte.}
{272}{}{Du hast recht, du solltest ihm besser aus dem Weg gehen.}
{273}{}{Warte hier. Ich finde mehr heraus und komme zurück.}

{274}{}{Du bist der Einzige, dem ich vertraue. Na gut, ich mach's! Du fragst ihn wegen des Dates, ja? Ich kann nicht selbst hingehen. Bei meinem Ruf will ich nicht, dass er mich, na ja ... falsch versteht.}
{275}{}{Ich bringe euch zusammen.}
{276}{}{Ich sehe mal, was sich machen lässt.}

{277}{}{Das ist großartig!}
{278}{}{Bis dann.}
{279}{}{Siehst du?}

{280}{}{Ich habe Bob überzeugt, mit dir auszugehen. Er ist ein bisschen grob, aber so ist er eben.}
{281}{}{Oh, du bist unglaublich! [Sie umarmt dich] Niemand war je so nett zu mir. Vielen, vielen Dank! Jetzt muss ich mich für mein Date fertig machen. Oh, ich bin so aufgeregt!}
{282}{}{Viel Glück.}
{283}{}{Eine Ex-Prostituierte und ein Nekrophiler haben sich auf dem Friedhof gefunden. So etwas Herzerwärmendes und Süßes hast du noch nie gesehen.}

{284}{}{Bob hat Nein gesagt. Eigentlich stimmt das nicht ganz. Er sagte, dein Körper wäre der erste, den er verbrennt, statt ihn zu begraben, weil du so krank und schmutzig bist, dass er das Grundwasser nicht verseuchen will. Außerdem würde er lieber Leichen ficken, weil die weniger stinken und reizendere Persönlichkeiten haben.}
{285}{}{Das hat er gesagt? Er ... Das ... [Sie fängt an zu weinen] Dieser Mistkerl! Er war meine letzte Chance ... Danke, dass du es versucht hast. Du kannst nichts dafür. Nach allem, was ich getan habe, verdiene ich es vielleicht, allein zu sein. }
{286}{}{Tut mir leid, Jasmine.}
{287}{}{Ja, wahrscheinlich.}
{288}{}{Du hast zwei kaputte Menschen ihrer letzten Hoffnung beraubt. Das geht jetzt auf dein Gewissen.}

#About missing brahmin
{290}{}{Was weißt du über den verschwundenen brahmin?}
{291}{}{Williams Junge sagt, er habe die ganze Nacht auf den brahmin aufgepasst, aber ich habe ihn schlafen sehen. Er hat sogar geschnarcht. Ahh ... So ein süßer Junge.}
{292}{}{Ist in dieser Nacht etwas Ungewöhnliches passiert?}
{293}{}{Hm, nicht wirklich. Bolt war nachts auf der Toilette, und Justin morgens. William weckte mich, als er seinen Jungen wegen des verschwundenen brahmin anschrie.}
{294}{}{Stimmt.}

#Female character
{1110}{}{[Du siehst ein Mädchen mit wunderschönem Haar und einem roten Schal um den Hals. Sobald sie deinen Blick erwidert, lächelt sie verführerisch.] Na, hallo, Schöne. Neu in der Stadt? Ich würde *alles* für ein bisschen Unterhaltung hier geben. Bist du nur auf der Durchreise oder willst du bleiben?}
{1126}{}{[Sie lacht] Ist das dein Ernst? Du weißt es wirklich nicht? [Sie legt einen Finger unter dein Kinn und zwinkert] Keine Sorge, Baby. Ich bin eine großartige Lehrerin.}
{1159}{}{Tut mir leid. Ich wollte dich nicht aufregen.}
{1164}{}{[Sie starrt dich mit weit aufgerissenen Augen an] Verarschst du mich? Oh mein Gott, das ist dein Ernst. Heilige Scheiße ... Eine Jungfrau, in deinem Alter ...}
{1178}{}{Das sieht ziemlich übel aus. Weißt du, was es ist?}
{1227}{}{[Sie sieht fassungslos aus] Du ... Meinst du das ernst? Ich dachte nicht, dass jemand dafür bezahlen würde, mich loszuwerden. Na gut, ich verstehe. Ich verspreche, mit der nächsten Karawane mitzufahren.}
{1250}{}{Mein Schutzengel!}
{1274}{}{Du bist der Einzige, dem ich vertraue. Na gut, ich mach's! Du fragst ihn wegen des Dates, ja? Ich kann nicht selbst hingehen. Bei meinem Ruf will ich nicht, dass er mich, na ja ... falsch versteht.}
