{100}{}{Du siehst einen Bandenführer.}
{101}{}{Du siehst den Anführer der „Ferocious Molerats“.}
{102}{}{Wir haben viel zu tun. Geh uns aus dem Weg.}
{103}{}{Still! Ich höre sie, sie sind ganz nah!}

{110}{}{Hey, du! Ja, du! Du hast echt Mist gebaut, Bürschchen! Beweg dich bloß nicht – ich durchlöchere dich sechsmal, bevor du dich überhaupt umdrehen kannst!}
{111}{}{Whoa, ganz ruhig! Ich bin hier, um dir zu helfen.}
{112}{}{Beruhig dich. Sag mir, was du willst, ich höre dir zu.}

{113}{}{Du bist derjenige, der Hilfe braucht, du Arschloch! Aber heute ist dein Glückstag! Ich brauche lebenden Köder, um mir ein Ärgernis vom Hals zu schaffen. Also mache ich dir ein Angebot!}
{114}{}{Oh-oh, Leute, der große, furchteinflößende Held der Ödnis gibt uns eine Chance, uns zu erklären! Ich zittere hier schon in meinen verdammten Stiefeln! [er grinst höhnisch] Du bist schon tot, du schwanzlutschender Schlappschwanz, du weißt es nur noch nicht. Wenn du dein Leben zurückverdienen willst, solltest du genau tun, was ich verdammt noch mal sage.}
{115}{}{Und was wäre das?}
{116}{}{Weißt du was, ich hab's mir anders überlegt. Ich glaube, die Welt ist besser dran ohne dich. [Angriff]}

{117}{}{Siehst du diese Höhle? [er nickt in Richtung eines unübersehbaren Höhleneingangs] Da drin hocken ein Haufen Waschlappen und scheißen sich in die Hose, weil sie zu viel Schiss haben, rauszukommen und sich uns zu stellen.}
{118}{}{Und du willst, dass ich sie ausräuchere.}

{119}{}{Oooh, bist du da ganz allein draufgekommen, du Hohlkopf? Ab mit dir da rein. Komm nicht raus, wenn du sie nicht mitbringst. Kapiert?}
{120}{}{Na gut, ich sehe, was ich tun kann.}
{121}{}{[Er pfeift den anderen zu] Macht den Weg frei! Der hier geht rein! [er beugt sich dicht heran und knurrt dir ins Ohr] Und denk dran: Wage es nicht, ohne den Treck wieder rauszukommen. Glaub mir, du verhungerst dort lieber, als uns zu verärgern.}
{122}{}{[Hineingehen]}
{123}{}{[Widerstand leisten]}
{124}{}{Keine dieser Möglichkeiten gefällt mir. Ich bin dann mal weg.}

{125}{}{[Er zieht seine Waffe] Halt, du Motherfucker!}
{126}{}{Schon gut, Mann, beruhig dich. Ich mache, was du willst.}
{127}{}{[Ignorieren]}

{128}{}{Was zum ... Hast du Todessehnsucht, Arschloch?! Zurück da rein, verdammt noch mal! Und komm diesmal nicht ohne den Treck wieder raus!}
{129}{}{Sie sind schon tot. Du kannst reingehen und sie holen.}
{130}{}{Ich wollte nur etwas frische Luft schnappen. Ich gehe jetzt wieder rein.}
{131}{}{Das geht zu weit. [Angriff]}

{132}{}{VERARSCHST DU MICH?! [Er zieht seine Waffe] Findest du das lustig?! Du wirst verdammt KOMISCH aussehen, wenn ich dir den verdammten Schädel wegpuste, verstanden?! Das Letzte, was du je sehen wirst, ist, wie ich deinen gottverdammten Schädel mit Blicken durchbohre, du scheißefressender Wichser!}
{133}{}{Du solltest dich beruhigen. Dann lebst du länger.}
{134}{}{[Die Raider ziehen ihre Waffen.]}
{135}{}{[Mach dich kampfbereit]}
{136}{}{Du solltest verdammt gute Neuigkeiten für mich haben, sonst begrabe ich dich lebendig!}
{137}{}{[Er beginnt vor Wut zu schreien, sein Gesicht läuft rot an und seine Augen quellen ihm fast aus den Höhlen] Mit WEM ZUR HÖLLE glaubst du verdammte SCHEISSE, dich anzulegen, du arschleckender Hundeficker?! WIR SIND DIE VERDAMMTEN, GRAUSAMEN MAULWURFSRATTEN!!! Wir sind die verdammt noch mal brutalsten Killer im Ödland, hörst du?! Wir beherrschen jeden, der diese Berge zu Gesicht bekommt. Sie leben und sterben, weil WIR es sagen! NIEMAND legt sich mit uns an! NIEMAND!!!}

{138}{}{Ach wirklich? Dann sehen wir uns das mal an – direkt nach dir. Macht euch bereit, Leute!}
{139}{}{Na dann ...}

#Female character
{1114}{}{Oh-oh, Leute, die große, harte Schlampe des Ödlands gibt uns eine Chance, uns zu erklären! Ich zittere hier schon in meinen verdammten Stiefeln! [Er grinst höhnisch] Du bist schon tot, du eitertriefende Fotze, du weißt es nur noch nicht. Wenn du dein Leben zurückverdienen willst, tust du besser genau, was ich verdammt noch mal sage.}
{1119}{}{Ooooh, hast du das ganz allein herausgefunden, du Zuckerbrüstchen? Rein da, verdammt. Komm erst wieder raus, wenn du sie mitbringst. Kapiert?}
{1128}{}{Was zum ... Hast du Todessehnsucht, Schlampe?! Zurück da rein, verdammt! Und komm nächstes Mal nicht ohne den Karawanenzug wieder raus!}
{1132}{}{WILLST DU MICH VERARSCHEN?! [Er zieht seine Waffe] Findest du das lustig?! Denn du wirst verdammt KOMISCH aussehen, wenn ich dir den Schädel wegpuste, verstanden?! Das Letzte, was du je sehen wirst, ist, wie ich deinen verdammten Schädel mit den Augen ficke, du verdammte dumme Hure!}
{1137}{}{[Er beginnt vor Wut zu schreien, sein Gesicht läuft rot an und seine Augen quellen ihm fast aus den Höhlen] Mit WEM ZUR HÖLLE glaubst du verdammte SCHEISSE, dich anzulegen, du hundelutschender Spermasäufer?! WIR SIND DIE VERDAMMTEN, GRAUSAMEN MAULWURFSRATTEN!!! Wir sind die verdammt noch mal brutalsten Killer im Ödland, hörst du?! Wir beherrschen jeden, der diese Berge zu Gesicht bekommt. Sie leben und sterben, weil WIR es sagen! NIEMAND legt sich mit uns an! NIEMAND!!!}
