{100}{}{Du siehst einen Raider.}
{101}{}{Du siehst ein Mitglied der „Ferocious Molerats“.}

#Pop-ups
{110}{}{Wir sind die Ferocious Molerats, du Arschloch!}
{111}{}{Jetzt sind wir verdammt noch mal unaufhaltsam!}
{112}{}{Ganz schön gut eingerichtet haben wir's hier, was?}
{113}{}{Wer ist böse? Wir sind böse! Diese verdammte Wüste gehört uns!}
{114}{}{Das bedeutet es, eine Maulwurfsratte zu sein!}
{115}{}{Hast du Angst, Schlampe? Heh. Hab ich's doch gewusst.}
{116}{}{Diese dummen Arschlöcher verstecken sich in einer Ecke wie kleine Kinder.}

{120}{}{Ich rieche einen Karawanenhändler!}
{121}{}{Bewegung! Da kommen sie!}
{122}{}{Oh ja! Wir haben diese Dreckskerle verdammt noch mal fertiggemacht!}
{123}{}{Uff, ich bin müde. Und hungrig!}
{124}{}{Erzähl allen in Black Rock, was du hier gesehen hast. Lass nichts aus! Sag ihnen, dass NICHTS die Herrschaft der Ferocious Molerats beenden wird!}