{100}{}{Du siehst einen Prospektor.}
{101}{}{Du siehst einen jungen Mann, dessen Augen Verzweiflung widerspiegeln.}
{102}{}{}

#Starting conversation
{110}{}{Hallo. Und auf Wiedersehen.}
{111}{}{Hi, wer bist du?}
{112}{}{}
{113}{}{Hör zu, tut mir leid, aber ich möchte gerade mit niemandem reden. Lass mich einfach in Ruhe hier sitzen.}
{114}{}{Na gut.}
{115}{}{Kannst du mir etwas Interessantes erzählen?}
{116}{}{Tschüss.}
{117}{}{Ähm, nein. Ich glaube nicht. Ich weiß nichts „Interessantes“.}
{118}{}{Mit dir zu reden macht nicht gerade Spaß.}
{119}{}{Mhm. Ja. Dir auch.}

#ÊQuest about missing prospectors
{150}{}{Jemand hat mir erzählt, dass sich ein Prospektor aus Reno in Black Rock versteckt. Weißt du etwas darüber?}
{151}{}{Äh ... Na ja, hier sind Leute aus ganz Nevada. Warum?}
{152}{}{Kein besonderer Grund ... Ich habe zufällig etwas von Mr. Wright.}
{153}{}{[Zieht den Kopf verstohlen zwischen die Schultern] Mr. Wer? K-kenn ich nicht. Äh ... Wen sucht er denn?}
{154}{}{Na, na. Ich habe nie gesagt, dass er jemanden sucht.}

{155}{}{[Er sieht sich nervös um] Mr. Wright hat ein Kopfgeld auf mich ausgesetzt, oder?}
{156}{}{Ganz genau. Tausend Dollar. Und glaub mir, die wird sich jemand holen.}
{157}{}{Ich bin nicht im Auftrag von Wright hier. Jemand anderes hat mich geschickt.}

{158}{}{Was, hier, vor allen Leuten? Nein, die- Moment, hast du *tausend* gesagt? Das kann nicht sein! Hör zu, Wright wird das nicht zahlen. Er lügt, kapierst du das nicht?}
{159}{}{Da gibt's nichts zu kapieren. Ich will nur das Geld.}
{160}{}{Das klingt interessant. Was ist zwischen dir und Wright vorgefallen?}
{161}{}{Äh, warte- warte! Wright wird meine Leiche ja sowieso nicht zu Gesicht bekommen, oder? Wie wär's damit: Ich gebe dir meinen Vertrag mit ihm und du lässt mich in Ruhe. Du zeigst ihm den Vertrag und sagst, du hättest ihn von meiner Leiche genommen. Er wird mich nie wiedersehen. Und meinen Metalldetektor gebe ich dir auch noch, dafür kriegst du bestimmt etwas Kleingeld! Können ... Können wir uns einigen?}
{162}{}{Warum nicht? Gib mir den Vertrag und den Metalldetektor. Um alles andere kümmere ich mich.}
{163}{}{Erzähl mir erst, was zwischen dir und Wright vorgefallen ist.}
{164}{}{Lügen ist eine üble Angewohnheit, aber in diesem Fall eine einträgliche.}

{165}{}{[Er seufzt erleichtert] Oh, Gott sei Dank ... Hör zu, wenn es um andere Prospektoren geht, die mit mir konkurrieren - viel Glück ihnen. Ich hätte den Vertrag ohnehin nie erfuellen können.}
{166}{}{Erzähl mir mehr.}

{167}{}{Wo soll ich überhaupt anfangen? Mein Partner und ich sollten Sprengstoff aus Hawthorne liefern, aber so einfach war es nicht. Robert wurde von rivalisierenden Prospektoren getötet, und allein konnte ich den Auftrag nicht erledigen. Ich bin heimlich nach Reno zurückgekehrt, um meine Familie zu sehen, und wir haben beschlossen, dass ich die Stadt besser verlasse, bevor Wrights Söhne mich umbringen. Das ist die Kurzfassung.}
{168}{}{Warum braucht Wright Sprengstoff?}
{169}{}{Wie ist Robert gestorben?}
{170}{}{Warum hast du Roberts Familie nichts gesagt?}
{171}{}{Warum glaubst du, dass Wright dich umbringen würde?}
{172}{}{Warum diese Geheimniskrämerei?}

{173}{}{Wright kontrolliert das Stromgeschäft in Reno. Früher hat er damit gutes Geld verdient, aber jetzt kommt er kaum noch über die Runden. Südlich von Reno gibt es ein Dorf, das um eine alte Uranmine herum entstanden ist, und er braucht das Uran, um Strom zu erzeugen. Ich weiß nicht genau, wozu der Sprengstoff gebraucht wird, aber ich vermute, er will die Mine erweitern.}
{174}{}{Ich kam gerade von einem Erkundungsgang zurück, als ich rivalisierende Konkurrenten in unserem Lager sah. Ich versteckte mich, aber Robert ... [er seufzt] Ich wollte helfen, aber es stand vier gegen einen. Es ist reines Glück, dass ich überhaupt überlebt habe.}
{175}{}{Wie bitte?! Soll ich ihnen in die Augen sehen und sagen, dass ich ihren Sohn einfach habe sterben lassen? Gott, ich kann mir nicht einmal selbst im Spiegel ins Gesicht sehen. Wie soll ich ihnen jemals unter die Augen treten?}
{176}{}{Weil er verdammt noch mal genau das tut! Er ist ein Gangster, wie jeder andere Boss in Reno! Er würde an mir ein Exempel statuieren. Ehrlich gesagt kann ich es ihm nicht einmal verübeln – ich habe Mist gebaut, und meine Familie schuldet ihm ohnehin schon eine Menge Geld.}
{177}{}{Wright wollte keine Konkurrenz. Jeder Boss in Reno kämpft um mehr Gebiet und Einfluss.}
{178}{}{Erzähl mir mehr über den Sprengstoff.}
{179}{}{Wright wollte fünf Kisten C-4. Hawthorne ist der einzige wahrscheinliche Ort, an dem es das gibt, aber wir kamen nicht an den Verteidigungssystemen vorbei. Robert wollte einen Roboter reparieren, um die Minen auszuschalten, aber jedenfalls kann man sich mit diesen Kisten in der Hand nicht an den Geschütztürmen vorbeischleichen. Wir dachten, im Lagerhaus gäbe es ein Auto oder so etwas, aber wir hatten nicht einmal einen Plan, wie wir das C-4 zu den Minen bringen sollten. Gott, was für ein dämlicher Plan.}
{180}{}{Weißt du, was ich von alldem halte?}
{181}{}{Was?}
{182}{}{Ich bringe dich einfach um und sage Wright, der Auftrag sei erledigt. Was meinst du?}
{183}{}{Du hast deine Familie im Stich gelassen und Roberts Familie leiden lassen. Du musst ihnen helfen.}
{184}{}{}

{185}{}{Warte, ich weiß, was du brauchst! Wright wird meine Leiche sowieso nicht zu Gesicht bekommen, oder? Wie wär's damit: Ich gebe dir meinen Vertrag mit ihm, und du lässt mich in Ruhe. Du zeigst ihm den Vertrag und sagst, du hättest ihn von meiner Leiche genommen. Er wird mich nie wiedersehen. Und meinen Metalldetektor gebe ich dir auch noch. Dafür bekommst du bestimmt etwas Geld! Können... Können wir uns einigen?}
{186}{}{Gib mir den Vertrag und den Metalldetektor. Um alles andere kümmere ich mich.}
{187}{}{Nein. Du musst deine Schulden bei deiner Familie und Roberts Familie begleichen.}
{188}{}{ABER WIE!? Wright braucht jede Menge Sprengstoff, und ich kann ihn nicht allein von Hawthorne besorgen.}
{189}{}{Dann bringe ich dich einfach um und sage Wright, der Auftrag sei erledigt. Na, was sagst du dazu?}
{190}{}{Ich besorge den Sprengstoff und erfuelle den Vertrag für dich. Vertrau mir.}

{193}{}{Wirklich? Aber... Ach, welche Wahl habe ich schon? Hier ist der Vertrag. Und nimm diesen Metalldetektor – damit kommst du an den Minen in Hawthorne vorbei. Ich gehe nach Reno und warte dort auf dich. Ich zähle auf dich, ja? Von diesem Vertrag hängt das Schicksal unserer beider Familien ab.}
{194}{}{Pass auf dich auf.}
