{100}{}{Du siehst einen Flüchtling.}
{101}{}{Du siehst einen sehr dünnen Mann.}
{102}{}{Wir hätten nicht weglaufen sollen. Wenigstens waren wir in Sicherheit.}

{110}{}{[Er blickt zu Boden] Ja, Sir?}
{111}{}{Ihr seid also die entflohenen Sklaven, stimmt's?}
{112}{}{Ich bin nur auf der Durchreise.}

{113}{}{[Sie sehen einander an, dann wieder zu Boden] Äh... Ja, Sir. Es hat keinen Sinn mehr, es zu verheimlichen. Wir sind entflohene Sklaven.}
{114}{}{Ich muss wissen, was euch zugestoßen ist, bevor ich entscheiden kann, ob ihr bleiben dürft.}
{115}{}{Das reicht mir. Ihr müsst von hier verschwinden.}
{116}{}{Wartet erst einmal hier.}
{117}{}{Warum werdet ihr diese Halsbänder nicht los?}

{120}{}{Ja, Sir. Wie Sie wünschen, Sir.}
{121}{}{Woher kommst du?}
{122}{}{Aus Reno, Sir. Wir wurden gefangen genommen, als wir noch jung waren, und sind seitdem Sklaven.}
{123}{}{Wie seid ihr entkommen?}
{124}{}{Wir haben wochenlang einen Tunnel gegraben, dann eines Nachts eine Wache niedergeschlagen und sind geflohen. Unser Freund hat ein Jahr lang alles geplant, aber er hat nur herausgefunden, wie wir entkommen können. Wir wussten nicht, wie wir draußen überleben oder diese Halsbänder loswerden sollten. Mit diesen Dingern um den Hals herumzulaufen, ist ... [sie tauschen ängstliche Blicke aus] ... sehr gefährlich.}
{125}{}{Warum seid ihr weggelaufen?}
{126}{}{Mister Luciano hat in Reno Schwierigkeiten, also gab er uns weniger zu essen und ließ uns jeden Tag mehr arbeiten. Wir verstehen, warum er das tun musste, aber es war zu viel. Das Risiko war besser, als dortzubleiben.}
{127}{}{Wie viele von euch sind entkommen?}
{128}{}{Wir waren zu fünft. Einer verhungerte. Der zweite trank aus einer Pfütze und starb an einer Krankheit. Den dritten fraß ein Gecko. Es war ... [sie sehen einander traurig an] ... eine harte Reise.}
{129}{}{Glaubt ihr, dass sie nach euch suchen?}
{130}{}{Mister Luciano wird wütend sein, aber wir sind nichts Besonderes. Er wird niemanden dafür bezahlen, außerhalb der Stadt nach uns zu suchen.}
{131}{}{Ich habe genug gehört, um eine Entscheidung zu treffen.}

{132}{}{[Die beiden Männer sehen dich nervös an.]}
{133}{}{Ihr scheint harmlos zu sein. Ihr könnt bleiben. Sehen wir zu, dass ihr einen Job in den Ställen bekommt ...}
{134}{}{Ihr könnt hier nicht bleiben. Ihr müsst gehen.}
{135}{}{Ich muss darüber nachdenken. Ich komme mit meiner Antwort wieder.}
{136}{}{[Ihre Schultern sinken herab] J-ja, Sir. Wir verstehen. Aber wir haben nirgendwohin zu gehen. Eine weitere Reise durch die Wüste überleben wir nicht, Sir! Wir können nicht gehen.}
{137}{}{Dein Meister braucht Sklaven, oder? Er wird euch wieder aufnehmen, wenn ihr nach Reno zurückkehrt. Dann habt ihr wieder Essen und ein Dach über dem Kopf.}
{138}{}{Warum kehrt ihr nicht zu eurem Meister zurück?}
{139}{}{Mister Luciano?! [Zum ersten Mal sieht er dir in die Augen, voller Entsetzen] Er wird uns lebendig häuten!}
{140}{}{Ich werde darüber nachdenken. Bleibt hier.}
{141}{}{Daran habe ich nicht gedacht. [he thinks for a moment] Wir können nicht allein überleben. Mister Luciano vergibt uns vielleicht noch ... [he turns to his friend] Was meinst du? [his friend nods, and he looks back at the ground in front of you] Wenn wir nicht hierbleiben können, nehmen uns auch andere Städte nicht auf. Unsere einzige Chance ist, nach Reno zurückzugehen. Wir brechen auf, sobald wir können.}
{142}{}{Pass auf dich auf!}
{143}{}{Je früher, desto besser. Ich will dich hier nicht wiedersehen.}

{144}{}{Ich frage nicht, ich sage es dir. Verschwinde. Noch ein Wort, und ich verfüttere dich an die Geckos, mit den Füßen voran. Lebend.}
{145}{}{N-nein, Sir, bitte nicht, Sir! Wir gehen, Sir, bitte tun Sie uns nichts!}
{146}{}{Das war verdammt viel mehr als ein Wort. Lauf los.}
{147}{}{Geh einfach. Lass diese Leute, dieses Essen, dieses Wasser, diese ganze Siedlung hinter dir, und ich verschone dein Leben. Geh einfach.}

{148}{}{Okay, wir gehen. Wir wollen keinen Ärger. Wir gehen.}
{149}{}{Hey, ich bin noch nicht fertig! [end]}

#Collar
{150}{}{Das wäre sehr hilfreich. Dann würde man uns nicht mehr als Sklaven erkennen. Aber sie lassen sich nicht so leicht abnehmen.}
{151}{}{Ich versuch's. Lass mich mal sehen.}
{152}{}{Erzähl mir von euch.}
{153}{}{[Diese Halsbänder wurden speziell so konstruiert, dass sie sich nicht ohne entsprechende Berechtigung abnehmen lassen. Wenn du nicht weißt, was du tust, werden sie beim Herumhantieren damit den Träger durch einen Stromschlag sofort töten.]}
{154}{}{Ich glaube, ich weiß, wie man die deaktiviert. Ich nehme sie euch jetzt ab.}
{155}{}{Ups! [deliberately activate both collars]}
{156}{}{Ich kann euch nicht helfen.}

{157}{}{Wir sind frei! [he laughs in joy] Ich fasse es nicht! Du hast uns gerettet! [he moves his head around, stretching his neck like it's the first time he's ever doing it] Oh, das ist ... unglaublich!}
{158}{}{Viel Spaß, Leute.}

#Female character
{1110}{}{[He looks at the ground] Ja, Ma'am?}
{1113}{}{[They look at each other, then back at the ground] Äh ... Ja, Ma'am. Es hat keinen Sinn mehr, es zu verheimlichen. Wir sind entflohene Sklaven.}
{1120}{}{Ja, Ma'am. Was immer Sie sagen, Ma'am.}
{1122}{}{Aus Reno, Ma'am. Wir wurden gefangen genommen, als wir noch jung waren, und sind seitdem Sklaven.}
{1131}{}{Ich habe genug gehört, um eine Entscheidung zu treffen.}
{1136}{}{[Ihre Schultern sacken herab] J-ja, Ma'am. Wir verstehen. Aber wir haben nirgendwohin zu gehen. Eine weitere Reise durch die Wüste würden wir nicht überleben, Ma'am! Wir können nicht gehen.}
{1145}{}{N-nein, Ma'am, bitte nicht, Ma'am! Wir gehen ja, Ma'am, bitte tun Sie uns nur nichts!}
