{100}{}{Du siehst einen Einheimischen.}
{101}{}{Du siehst einen Bürger von Black Rock.}

###############################################################
#
#              Pop-ups
#
###############################################################

#Jed died
{102}{}{Ich wusste, dass Jed bald sterben würde.}
{103}{}{Jed hat so viel für uns getan. Ich hoffe, er ist jetzt an einem besseren Ort.}
{104}{}{Heutzutage sterben nicht viele Menschen an Altersschwäche.}
{105}{}{Jed hat immer gesagt: „Wenn ich sterbe, schickt mich in den Himmel.“ Was auch immer das heißen soll.}
{106}{}{Ich habe geträumt, dass Smith im Himmel war, aber dort wimmelte es von Stammesleuten. Pech gehabt.}

#Jed's alive
{107}{}{Jed bleibt nicht mehr viel Zeit. Ich spüre es.}
{108}{}{Wenn Jed stirbt, muss ich vielleicht weinen. Weißt du ... nur ein bisschen.}
{109}{}{Der Himmel wartet auf Jed ... Ach, was soll's.}

#Robbed graves reactions
{110}{}{Man sagt, jemand schaufelt die Gräber aus, aber ich glaube immer noch, dass Bob dahintersteckt.}
{111}{}{Wenn ich aufwache und noch ein geschändetes Grab finde ... dann ist Bob fällig.}
{112}{}{Bob ist ein guter Kerl, aber er muss lernen, sich zu beherrschen.}
{113}{}{}
{114}{}{}

{115}{}{Wenn ich sterbe, hoffe ich, dass die Geckos meinen Körper erreichen, bevor Bob es tut.}
{116}{}{Wir müssen Bob zur Rechenschaft ziehen! Wie oft will er unsere Toten noch schänden?}
{117}{}{Bob ist ein guter Kerl, aber er muss lernen, sich zu beherrschen.}
{118}{}{}
{119}{}{}

#Mike's outcomes
{120}{}{Mike war einer unserer besten Jäger! Warum hast du das getan?!}
{121}{}{Du musstest Mike wirklich umbringen?!}
{122}{}{Wie konntest du Mike umbringen?!}
{123}{}{Ich mochte Mike, aber ich wusste, dass es früher oder später passieren würde.}
{124}{}{}

{125}{}{Mike liebt es wirklich zu kämpfen.}
{126}{}{Wenn es einen Kerl in der Stadt gibt, mit dem man sich nicht anlegen sollte, dann ist es Mike.}
{127}{}{Mike wird sich wieder betrinken und Streit suchen.}
{128}{}{Dieser Mike braucht wirklich eine Abreibung.}
{129}{}{}

{130}{}{Oh, Mike hat dich besiegt? Ha! Das muss Spaß gemacht haben.}
{131}{}{Scheiße, Mike hat dir ganz schön den Arsch versohlt, was?}
{132}{}{Mann, ich hatte wirklich gehofft, dass jemand Mike ordentlich vermöbelt. Schade.}
{133}{}{Gib nicht auf. Mike wurde schon seit ... Hmm, vielleicht vor ein paar Tagen zuletzt geschlagen.}
{134}{}{}

{135}{}{Du hast Mike verprügelt? Das ist eine Ehre!}
{136}{}{Du hast Mike also verprügelt, was? Beeindruckend.}
{137}{}{Hey, gut gemacht mit Mike!}
{138}{}{Das hält Mike eine Weile davon ab, Streit zu suchen.}
{139}{}{Hahaha!!! Du hast Mike vermöbelt! Abklatschen!}

#When character is a raider
{140}{}{In letzter Zeit gibt es mehr Raider. Hmm, woher soll ich wissen, dass du nicht zu ihnen gehörst?}
{141}{}{Raider sind hier nicht willkommen.}
{142}{}{Ein Leben als Raider endet nicht gut.}
{143}{}{Gott soll mich strafen, wenn ich diesen Monat nicht mindestens einen Raider töte.}
{144}{}{}
{145}{}{Wenn die Raider die nächste Karawane angreifen, bekommen wir keine weitere.}
{146}{}{Heute Morgen waren wieder mehr Raider da. Wie lange soll das noch so weitergehen?}
{147}{}{Ich wünschte, diese Raider würden einfach sterben.}
{148}{}{}
{149}{}{}

#Pop-ups
{150}{}{Äh, hi.}
{151}{}{Was für ein beschissener Tag. Wie jeder andere auch.}
{152}{}{Gib mir nicht die Hand. Ich war gerade auf dem Klo.}
{153}{}{Hier wird's langsam eng.}
{154}{}{Du willst dich doch hoffentlich nicht hier niederlassen?}
{155}{}{Hast du William schon kennengelernt? Er ist ein guter Kerl. Nicht besonders helle, allerdings.}
{156}{}{Hast du schon mit Justin gesprochen? Er ist hart im Nehmen, aber unersetzlich.}

#Brahmin
{157}{}{Wie konnte eine ganze brahmin einfach verschwinden?}
{158}{}{Wenn ich William wäre, würde ich seinen Jungen ordentlich vermöbeln.}
{159}{}{Nur in Black Rock könnte eine ganze brahmin einfach verschwinden.}

#Fugitive slaves
{160}{}{Diese Sklaven machen nichts als Ärger.}
{161}{}{Sklaven gehören zu ihrem Herrn, nicht nach Black Rock!}
{162}{}{Die Sklaven sind endlich weg? Das ist gut zu hören.}
{163}{}{Wenn wir noch mehr entflohene Sklaven erwischen, machen wir es genauso.}
{164}{}{Hat William den Verstand verloren? Wir wollen hier keine entlaufenen Sklaven versteckt halten!}
{165}{}{William hat diese Sklaven mitgenommen? Er ist viel zu weich.}
{166}{}{Na ja, ich glaube, es besteht keine Gefahr, wenn die Halsbänder dieser Sklaven weg sind.}
{167}{}{Diese Sklaven sollten kein Problem mehr sein, aber wer weiß?}
{168}{}{}
{169}{}{}

#Main quest of Black Rock
{170}{}{Verdammt! William hatte auf diese Karawane gesetzt ...}
{171}{}{Schade, dass der Karawanenhandel geplatzt ist.}
{172}{}{Auch ich hatte gehofft, etwas Neues von dieser Karawane kaufen zu können ...}
{173}{}{Ich schätze, wir werden so bald keine Post aus Reno bekommen.}

{174}{}{Wer auch immer diese Karawane gerettet hat, muss ein verdammt harter Hund sein ...}
{175}{}{Endlich geht es bergauf!}
{176}{}{Ich habe diese ganzen Karawanen satt.}

{177}{}{Ich habe gehört, William wartet auf Milo. Normalerweise kommt er nicht so spät.}
{178}{}{Würde mich nicht wundern, wenn Milo einfach vor seiner Frau davongelaufen ist. Ha!}
{179}{}{Ich habe Milo schon lange nicht mehr gesehen.}


###############################################################
#
#              Talk with Dave about pistol
#
###############################################################

{199}{}{Du siehst Dave.}

{200}{}{[Er lächelt und nickt] Willkommen! Ich freue mich immer, Leute wie dich in diesem Scheißloch zu sehen.}
{201}{}{[Er mustert dich misstrauisch] Neu in der Stadt? Interessant ... Was willst du von mir?}
{202}{}{Bist du Dave?}
{203}{}{Nichts.}
{204}{}{Erwischt! Ich werde nicht länger verheimlichen, dass ich Dave bin. Genau genommen wussten es vorher schon alle, und jetzt weißt du es auch. Verdammt, in so einer kleinen Stadt kann man sich nur schwer verstecken.}
{205}{}{Keine Witze. Weißt du etwas über diese Pistole?}
{206}{}{Ah, ja ... Mein treuer Partner Smiley ging früher mit ihr auf die Jagd. Er hatte Glück, aber nicht genug, um eine Begegnung mit Plünderern zu überleben. Smileys Sachen wurden verkauft, und natürlich hat dieser verdammte Händler William die besten Stücke genommen, einschließlich dieser Waffe. Aber er hat einen Fehler gemacht.}
{207}{}{Was für einen Fehler?}
{208}{}{Er hat vergessen, dass sie Batterien braucht! Niemand kauft eine Plasmapistole, die man nicht mit Energie versorgen kann. Außerdem ist sie nicht so gut, wie sie aussieht. Smiley musste ständig an ihr herumbasteln, damit sie überhaupt funktionierte.}
{209}{}{Weißt du, wie man sie wieder in Schuss bringt?}
{210}{}{Hmm ... [er reibt sich das Kinn] Also, ich hab ihm dabei zugesehen ... Also bin ich wohl der Einzige, der weiß, wie man das Baby reinigt und kalibriert. Seit Smiley gestorben ist, hat es keiner mehr versucht. Ehrlich gesagt wird das Ding nie ein richtiger Killer, aber mit ein bisschen Arbeit kannst du vielleicht mehr Wumms aus ihm rausholen.}
{211}{}{Das klingt großartig. Kannst du das machen?}
{212}{}{Klar ... aber das kostet dich was.}
{213}{}{Was willst du?}
{214}{}{William sitzt mir wegen Geckohäuten im Nacken, aber die Jagd läuft in letzter Zeit echt mies. Besorg mir Geckohäute im Wert von, sagen wir, 250 Dollar, und ich bring das Baby wieder richtig auf Vordermann.}
{215}{}{Lass uns noch mal über die Pistole reden.}
{216}{}{Welche Arten von Geckohäuten will William?}
{217}{}{Dann gehe ich mal.}

{218}{}{Goldene Geckohäute sind mehr wert als silberne, aber jede Sorte tut's. Ich muss William nur vom Hals schaffen.}
{219}{}{Hier ist eine silberne Geckohäut.}
{220}{}{Nimm eine goldene Geckohäut.}
{221}{}{Sieh mal! Ich habe eine Säuregeckohäut.}

{222}{}{Großartig! Das reicht. Gib mir die Pistole, dann bringe ich sie sofort wieder in Schuss.}
{223}{}{Hier, bitte. Das sollte es besser wert sein.}
{224}{}{Gut, aber das reicht noch nicht. Bring mir mehr.}

{225}{}{[Dave zerlegt die Waffe sorgfältig, reinigt und kalibriert sie. Manchmal sieht es so aus, als wüsste er nicht, was er tut, aber schließlich setzt er die Pistole wieder zusammen und reicht sie dir.] Na, was hab ich gesagt? Nur ich kann sie reparieren!}
{226}{}{Gute Arbeit, Dave. Nevada wird bald um einiges leerer sein.}
{227}{}{Danke, Dave. Du hast mir wirklich geholfen.}
{228}{}{Nein, das reicht nicht.}
{229}{}{Keine Ursache. War doch nichts.}

#{230}{}{Dave, what do you know about energy weapons?}
#{231}{}{Not much. You might find some pre-war magazines about them in big cities though.}
#{232}{}{Tell me about Smiley and raiders. What happened?}
#{233}{}{We were on our way back from a hunt in Lovelock. The raiders ambushed us and demanded food. They looked tired and hungry, and there weren't many of them, so we just shot them. Smiley was badly wounded in the fight. Sucks, huh?}
#{234}{}{Lovelock? Where is that?}

{235}{}{Und jetzt?}
{236}{}{Wir sehen uns später, wenn ich die Pistole habe.}
{237}{}{Ich mache es, sobald du die Pistole bringst.}
{238}{}{Ich hab dir doch schon gesagt, William sitzt mir wegen Geckohäuten im Nacken. Bring mir ungefähr }
{239}{}{Dollar für Felle, und ich bringe die Pistole für dich in Ordnung.}

###############################################################
#
#              Talk with Bolt
#
###############################################################

{250}{}{Du siehst Bolt.}
{251}{}{[Er starrt dich finster an] Was?}
{252}{}{Äh, nichts. Überhaupt nichts.}
{253}{}{Bist du Bolt?}

{254}{}{So nennen sie mich. Was willst du?}
{255}{}{Warum nennen sie dich Bolt?}
{256}{}{Was hast du in der Nacht gemacht, als brahmin verschwand?}
{257}{}{[Er grinst] Vielleicht, weil in meinen Augen ein metallischer Funke glimmt.}
{258}{}{Geschlafen, wie ich sollte. Versuch nicht, mir mit diesem Psychokram zu kommen – ich habe nichts mit diesem verdammten brahmin zu tun. Gar nichts.}
{259}{}{Bolt, kann ich deine Schrotpatronen sehen?}
{260}{}{Äh, meine Schrotpatronen? Warum?}
{261}{}{Ich will sie mit denen vergleichen, die in der Leiche des gestohlenen brahmin steckten.}
{262}{}{[Er sieht sich um und flüstert] Wie zum Teufel ... Verdammt! Ich wusste, dass ich wegen der Scheiße Ärger kriege!}
{263}{}{Interessant. Was hast du zu deiner Verteidigung zu sagen?}

{264}{}{Scheiß drauf, ich versuch's gar nicht erst! Ich bin nicht so einer. Weißt du, was für einer ich bin? Ich bin einer von der „Molerats“-Gang, das ist es! Na ja, ich *war* ein Molerat. Ich bin im Ruhestand ... Zumindest dachte ich das.}
{265}{}{Erzähl mir von der Gang.}
{266}{}{Du hast die Gang verlassen?}
{267}{}{Was hat das mit dem verschwundenen brahmin zu tun?}
{268}{}{Was hast du jetzt vor?}
{269}{}{Ich muss entscheiden, was ich als Nächstes tue.}
{270}{}{Ein Haufen Taugenichtse, die es in Gerlach oder Black Rock zu nichts gebracht haben, aber genug Munition haben, um sich in den Bergen durchzuschlagen. Nicht gerade glamourös, aber man muss ja essen.}
{271}{}{Ja. Früher hatten wir dieses ganze Tal unter Kontrolle, aber als ich ging, zogen wir zufälligen Reisenden das letzte bisschen aus der Tasche. Ich ließ mich hier nieder, und bis du mich durchschaut hast, wusste niemand von meiner Vergangenheit.}
{272}{}{Die Jungs hatten eine Weile nichts gegessen, also kamen sie eines Abends zu mir. Ich konnte nicht Nein sagen – sie sind zwar nicht mehr so bedrohlich wie früher, aber immer noch stark genug, um mich umzubringen! Ich rührte Xanderwurzelpulver ins Wasser und gab es dem Kind, damit es einschlief. Dann riss ich die Bretter vom Zaun, um brahmin ohne großen Aufwand herauszuholen.}
{273}{}{Nicht viel. Wenn sie mich rauswerfen, dann ist das eben so. Ich gehe zu Big Louie und schließe mich ihm an. Es wird nicht so gut sein wie hier, aber wenigstens verhungere ich nicht wie die Maulwurfsratten. Die haben nicht mehr viel Zeit.}
{274}{}{Nicht mehr viel Zeit? Warum wirst du sie nicht gleich los?}
{275}{}{Ich weiß, was du denkst – eine Truppe zusammentrommeln und diese Typen erledigen, stimmt's? Keine Chance, Kumpel – so was gab's nur in alten Filmen. Die Bande ist gut in den Bergen versteckt, du kommst nicht so leicht an sie ran. Aber eins sage ich dir: Wenn William die Karawanenroute in Gang bringt, wird das die Bande wiederbeleben.}
{276}{}{Ich werde allen die Wahrheit erzählen, außer du überzeugst mich vom Gegenteil.}
{277}{}{Ach, wie vornehm! Scheiß drauf. William wird mich nicht umbringen, er wird mich nur rauswerfen. Also kann ich aufatmen. Siehst du? [atmet tief ein] Ich rieche Abenteuer!}

{280}{}{Ich habe mit William gesprochen. Er verzeiht dir und sagt, du kannst bleiben.}
{281}{}{William ist stinksauer. Du musst Black Rock verlassen.}
{282}{}{Er verzeiht mir? Nach allem, was ich getan habe? Ich ... Hm. Damit hatte ich nicht gerechnet. Aber wenn er es sagt ... Hör zu, danke. Du hast mir etwas Gutes getan, mehr, als ich verdient habe.}
{283}{}{Ja, ich will nicht behaupten, ich hätte es nicht verdient. Ich packe meine Sachen und gehe. Ich habe versucht, mich zu bessern, aber ich konnte es nicht – und das ist schon in Ordnung. Sag William, dass die Bande zurückkommt, egal ob ich hier bin oder nicht. Er sollte besser darauf vorbereitet sein.}
{284}{}{Genieß dein Leben hier.}
{285}{}{Halt einfach die Klappe und verschwinde.}

{286}{}{Ich muss tun, was ich kann, um das wieder in Ordnung zu bringen.}
{287}{}{Du wirst mich hier nicht wiedersehen.}

#Female character
{1101}{}{Du siehst einen Bürger von Black Rock.}
{1275}{}{Ich weiß, was du denkst – eine Truppe zusammentrommeln und diese Typen erledigen, stimmt's? Keine Chance, Süße – so was gab's nur in alten Filmen. Die Bande ist gut in den Bergen versteckt, du kommst nicht so leicht an sie ran. Aber eins sage ich dir: Wenn William die Karawanenroute in Gang bringt, wird das die Bande wiederbeleben.}
{1280}{}{Ich habe mit William gesprochen. Er verzeiht dir und sagt, du kannst bleiben.}