{100}{}{Du siehst William.}
{101}{}{Du siehst den Besitzer der Gaststätte.}

#Conversation
{107}{}{[Mach ein finsteres Gesicht] Hey, hat deine Mutter dir nie gesagt, dass Starren unhöflich ist? Hör damit auf!}
{108}{}{He, ganz ruhig! Lass dich von dem Gesindel nicht stören, hier bist du sicher. Wie wär's, wenn du dir ein Sandwich aufs Haus nimmst und wir dieses Missverständnis vergessen, hm?}
{109}{}{Was zum ... Ist das dein Ernst? [du hörst jemanden hinter dir lachen] Hey, hör da hinten auf damit! Hör zu, Freund: Wenn ich etwas habe, das du brauchst, und du etwas hast, das ich brauche, können wir vielleicht ein Geschäft aushandeln, von dem wir beide etwas haben. Das nennt man Tauschhandel. Kapiert?}
{110}{}{Na, Freund! Es ist schon eine Weile her, seit hier ein neues Gesicht aufgetaucht ist. Lust auf Tauschhandel? Keine Scheu! Ich helfe Reisenden immer gern, solange sie keinen Ärger machen.}
{111}{}{Tauschhandel? Was ist das?}
{112}{}{Wirklich? Also ... handeln. Wenn ich etwas habe, das du brauchst, und du etwas hast, das ich brauche, können wir vielleicht ein Geschäft aushandeln, von dem wir beide etwas haben. Das nennt man Tauschhandel. Kapiert?}
{113}{}{Klingt einleuchtend. Tauschen wir.}
{114}{}{Noch nicht. Ich möchte dich nach diesem Ort fragen.}

{115}{}{Ja, die Auswahl ist nicht gerade groß, ich weiß. Nächstes Mal habe ich mehr ... hoffe ich.}
{116}{}{Na, hallo, Freund! Schön, dich zu sehen!}
{117}{}{Lass uns reden.}
{118}{}{Was hast du zum Tauschen?}
{119}{}{Für heute reicht's. Tschüss.}

{120}{}{Was ist das für eine seltsame Pistole?}
{121}{}{Können wir über die seltsame Pistole reden, die ich bei dir gekauft habe?}
{122}{}{Das ist eine echte Plasma-Pistole eines sehr alten Modells. Eine der ersten, die vor dem Krieg auf den zivilen Markt kamen. Sie ist etwas ramponiert, aber sie erfuellt ihren Zweck. Warum?}
{123}{}{Erzähl mir mehr über die Pistole.}
{124}{}{Das war's.}

{125}{}{Sie gehörte einem Einheimischen. Gott hab ihn selig. Viel mehr weiß ich nicht darüber, aber Dave vielleicht. Ich bin nur der Verkäufer.}
{126}{}{Wie bist du an sie gekommen?}
{127}{}{Nachdem die Raider den Besitzer getötet hatten, teilten Dave und ich unter uns auf, was in seinem Zelt übrig war. Viel war es nicht, das kann ich dir sagen.}
{128}{}{Interessant. Dann lass uns handeln.}
{129}{}{Das war alles, was ich wollte. Ich gehe dann mal.}
{130}{}{Reden wir über etwas anderes.}

{131}{}{Ich möchte dich ein paar Dinge über diesen Ort fragen.}
{132}{}{Zum Beispiel?}

{133}{}{Hast du eine Sicherung für die Wasserpumpe?}
{134}{}{Nein, so etwas gibt es hier nicht. Ich kümmere mich hauptsächlich um Essen und Trinken. Justin kümmert sich um die ganze komplizierte Technik.}
{135}{}{Stimmt.}
{136}{}{Noch etwas?}
{137}{}{Das reicht.}
{138}{}{Gibt es hier Raider?}
{139}{}{Ja, so eine einheimische Bande von Mistkerlen. Sie leben irgendwo oben in den Bergen. Niemand weiß etwas über sie.}

#About Black Rock
{140}{}{Aber klar! Ich rede immer gern über unsere reizende Kommune Black Rock!}
{141}{}{Was kannst du mir über die Geschichte dieses Ortes erzählen?}
{142}{}{Wer hat hier das Sagen? Ich bin neu hier und möchte bei den richtigen Leuten Eindruck machen.}
{143}{}{Hast du hier *ernsthafte* Arbeit für mich?}
{144}{}{Hey, hier ist alles ernst! Aber wenn du etwas Großes suchst: Ein Karawanenhändler hat mir erzählt, dass „Nevada Express“ einen Ermittler braucht, auch wenn das schon eine Weile her ist. Du findest sie in Reno. Die Arbeit hier ist etwas entspannter ... Aber immerhin hast du nette Kollegen!}

{145}{}{Wer ist der stille Typ mit der Lederjacke?}
{146}{}{Keine Ahnung. Er kam vor einiger Zeit mit der Karawane und sagt kaum etwas, außer wenn er Essen und Trinken kauft. Ich glaube, er zieht bald weiter.}
{147}{}{Das wären Justin und ich! Ich kümmere mich um das Essen, und Justin hält Wasser und Strom am Laufen. Justin ist, äh ... nicht annähernd so freundlich wie ich, aber wenn es um das Wohl der Gemeinschaft geht, finden wir immer einen gemeinsamen Nenner.}

{148}{}{Worüber redet ihr denn?}
{149}{}{Wie du meinst.}

#About bikers
{150}{}{Weißt du etwas über Biker?}
{151}{}{Sie kommen von Zeit zu Zeit hier durch. Was willst du wissen?}
{152}{}{Wer sind sie?}
{153}{}{Haben sie so etwas wie einen Stützpunkt?}
{154}{}{Was hältst du von ihnen?}
{155}{}{Was weißt du über den Angriff auf „Nevada Express“?}
{156}{}{Das reicht. Danke.}

{157}{}{Sag mal, ist kürzlich ein Biker namens Jay Kukish hier durchgekommen?}
{158}{}{Ja, ist er! Er hat sich mit Essen eingedeckt und ist in Eile wieder abgehauen.}
{159}{}{Hast du eine Ahnung, wohin er gefahren ist?}

{160}{}{Gute Frage. Hmmm ... Ich habe von Bikern gehört, die mit ihren Maschinen durch Nevada und Kalifornien fahren, frei nach ihrer eigenen Philosophie leben und ihr Schicksal selbst bestimmen. Bei diesen Typen ist das anders. Die hier fahren einfach als Haufen halbwegs anständiger Kerle herum, denen alles scheißegal ist, außer sie selbst. Beantwortet das deine Frage?}
{161}{}{Keine Ahnung! Falls sie eins haben, erzählen sie es niemandem. Ich weiß, dass sie meistens aus dem Osten und Süden kommen, aber im Great Nevada Ring gibt es verdammt viel Platz, um eine Basis zu verstecken.}
{162}{}{Great Nevada was?}
{163}{}{So nennen wir die Fernstraße zwischen Salt Lake City, Vegas und Reno. Auf diesen Straßen sind viele Reisende unterwegs, und das heißt auch, dass es jede Menge Banditen gibt. Wenn du die Straßen meidest, gehst du den meisten aus dem Weg, musst dich dann aber mit der Wildnis des Ödlands herumschlagen.}
{164}{}{Sie sind keine schlechten Leute. Sie haben viel Temperament und machen keinen Ärger, deshalb mag ich sie. Ich lasse sie allerdings im Voraus zahlen, wenn du verstehst, was ich meine.}
{165}{}{Ich habe gehört, jemand hätte östlich von hier einen „Nevada Express“-Transport angegriffen. Es könnten Raider gewesen sein, aber „Express“ gibt den Bikern die Schuld. Ich kenne die Einzelheiten nicht, aber die Geschichte ist merkwürdig.}
{166}{}{Kannst du mir zeigen, wo der Angriff stattgefunden hat?}
{167}{}{Klar! [Er zeigt dir den Ort auf deiner Karte.]}
{168}{}{Könnte ich, aber ich bin mir nicht sicher, ob ich sollte. Warum sollte ich dir vertrauen?}
{169}{}{Was, wenn ich dich bezahle?}
{170}{}{Gib mir fünfzig Mäuse, dann zeige ich dir den Ort.}
{171}{}{Klingt gut! [Er nimmt dein Geld und zeigt dir den Ort auf deiner Karte.]}
{172}{}{Als er losfuhr, war er auf dem Weg nach Süden. Wohin er auch will, in Reno wird er bestimmt Halt machen.}
{173}{}{Danke für deine Hilfe.}

#Gecko's eggs
{180}{}{Ich hab Geckoeier ... also, Geckohoden. Ich meine Eier.}
{181}{}{Hey, das ist ja großartig! Ich gebe dir fünfzig Mäuse pro Stück dafür!}
{182}{}{Warum kaufst du sie?}
{183}{}{Dann nimm alles, was ich habe.}
{184}{}{Ich überleg's mir.}
{185}{}{Na ja, ich hoffe, du denkst schnell ...}
{186}{}{Denn Karawanenhändler aus Reno zahlen mir mehr dafür. Sie zahlen Höchstpreise, weil die Dinger schwer zu bekommen sind. Deshalb kaufe ich sie und verkaufe sie weiter. Zum Glück lassen sie sich lange aufbewahren.}
{187}{}{Ein faires Geschäft! Danke.}
{188}{}{Hey, hat deine Mutter dir nie gesagt, dass es gemein ist, Leute reinzulegen?}
{189}{}{Daran erinnere ich mich nicht ...}

#History
{190}{}{}
{191}{}{Es gibt nicht viel zu erzählen. Vor dem Krieg war Black Rock eine Art riesiger Schrottplatz. Zumindest hielten wir es für einen Schrottplatz. Überall standen diese seltsamen Metallformen und Konstruktionen. Sie sahen aus, als hätte ein Junkie sie gebaut.}
{192}{}{[Mehr]}
{193}{}{Wir hörten das Gerücht, dass sich jemand hier niedergelassen hatte, und erkannten, dass wir uns eine Gemeinschaft fernab der „Zivilisation“ aufbauen konnten. Damals war das Leben in den Großstädten ziemlich beschissen. Wir wollten einen Neuanfang.}
{194}{}{[Mehr]}
{195}{}{Also kamen wir her, rissen diese seltsamen Konstruktionen nieder und bauten unsere Häuser daraus. Es kamen mehr Leute, mit Brahmins und Zelten. Schließlich wurden wir zu einem Ort, an dem Reisende und Karawanenhändler Halt machten.}
{196}{}{Danke.}
{197}{}{Keine Ursache!}
{198}{}{Klingt eher nach einer Ansammlung von Skulpturen als nach einem Schrottplatz, findest du nicht?}
{199}{}{Du meinst, wie eine Kunstausstellung? Hm ... Weißt du, vielleicht hast du recht!}

#Help Jas
{200}{}{Es scheint, als liefe hier nicht viel gut. Kann ich dir irgendwie helfen?}
{201}{}{[Er hebt eine Augenbraue] Nun, ich weiß nicht, was du vorhast, aber wenn du helfen willst, wäre ich dir dankbar, wenn du etwas wegen Jasmine unternehmen könntest.}
{202}{}{Wer?}
{203}{}{Schon gut.}
{204}{}{Hm.}

{205}{}{[Er seufzt] Das arme, arme Mädchen. Ihr Vater brachte sie aus Reno hierher. Es hätte ein großartiger Neuanfang werden können, aber er starb bei einer Gecko-Jagd, und Jasmine bekam diese üblen Blasen auf der Haut. Irgendeine Krankheit.}
{206}{}{Und?}
{207}{}{Justin sagt, wir sollten sie lebendig verbrennen, damit sich niemand sonst ansteckt, so wie früher. Aber dazu fehlt ihm der Mut. Ich? Ich finde, wir sind besser als das. Ich will nicht, dass böse Gerüchte über unser kleines Städtchen die Runde machen.}
{208}{}{Was kann ich tun?}
{209}{}{Nun, ich will ganz offen sein: Wir können nicht viel für sie tun. Uns fehlt nicht nur ein Arzt, wir haben nicht einmal die richtigen Medikamente. Aber wenn du einen Weg findest, sie zu heilen, bezahle ich dich für deine Mühe.}
{210}{}{Ich sehe, was ich tun kann.}
{211}{}{Es tut mir leid, aber ich kann dir nicht helfen.}
{212}{}{Verstehe. Vergiss es einfach.}
{213}{}{Das freut mich! Sag bloß nichts zu Justin. Er hasst Jasmine.}

{220}{}{Wegen Jasmine ... }
{221}{}{Ja?}
{222}{}{Sie ist tot.}
{223}{}{Ach, nichts.}
{224}{}{Ich konnte sie heilen. Sie ist nicht mehr ansteckend.}
{225}{}{Tot?! Das hat sie nicht verdient! [seufzt] Na ja, wenigstens besteht jetzt keine Ansteckungsgefahr mehr. Ich wette, Justin wird das gern hören.}
{226}{}{Hast du mir nicht eine Belohnung versprochen?}
{227}{}{Tschüss.}
{228}{}{Ja, dafür, dass du sie heilst! Glaubst du, ich freue mich, von ihrem Tod zu erfahren? Sie wollte nicht krank sein. Wenn du für das, was du einem schutzbedürftigen Mädchen angetan hast, eine Belohnung willst, frag Justin. Von mir bekommst du nichts.}
{229}{}{Na gut.}
{230}{}{Verdammt! Du hast keine Ahnung, wie erleichtert ich bin, das zu hören. Hier, nimm das für deine Auslagen [er gibt dir fünfzig Dollar] – und hier sind etwas zu essen und zu trinken. Geht aufs Haus. Du hast es dir verdient!}
{231}{}{Gern geschehen.}
{232}{}{Na gut.}

{233}{}{William, tut mir leid, aber mich hat das etwas mehr gekostet ... }
{234}{}{Mir tut es auch leid, aber ich bin nicht reich. Ich habe dir so viel gegeben, wie ich konnte.}
{235}{}{Na gut.}
{236}{}{Oh ... Das ist unangenehm. Hm ... Ich glaube, ich kann noch fünfzig Dollar entbehren. Keine Sorge, das hole ich wieder rein. Aber mehr kann ich dir nicht geben, tut mir leid.}
{237}{}{Danke.}
{238}{}{Du hast 50 Erfahrungspunkte für den erfolgreichen Einsatz der Handeln-Fertigkeit erhalten.}
{239}{}{Sie ist gegangen.}
{240}{}{Ohne dich überhaupt zu verabschieden? Hm ... Das überrascht wohl nicht, wenn man bedenkt, wie sie hier behandelt wurde. Totengräber Bob war vielleicht der Einzige, dem sie etwas bedeutet hat ... Na ja, da lässt sich wohl nichts machen.}

#Quest - fugitive slaves
{250}{}{Kann ich sonst noch irgendwie helfen?}
{251}{}{Ja, tatsächlich. Wir könnten bei einer Sache eine neue Perspektive gebrauchen.}
{252}{}{Erzähl mir mehr.}
{253}{}{Vor Kurzem sind ein paar entlaufene Sklaven in der Stadt aufgetaucht. Die armen Kerle müssen einen langen, beschwerlichen Weg hinter sich haben, um ihrem früheren Besitzer zu entkommen. Aber wir wissen nicht, ob sie hier nützlich sein oder ob man ihnen trauen können. Justin hält es sogar für gefährlich, sie überhaupt hier zu haben. Wir brauchen eine neutrale Person, die beurteilt, ob wir sie bleiben lassen oder fortschicken sollten.}
{254}{}{Ich erledige das.}
{255}{}{Nein danke. Mit entlaufenen Sklaven will ich nichts zu tun haben.}

{256}{}{Wegen der entlaufenen Sklaven ... }
{257}{}{Was denkst du?}
{258}{}{Sie arbeiten für fast nichts, außer Essen und einem Dach über dem Kopf. Sie werden Black Rock sehr nützlich sein.}
{259}{}{Sie sind tot. So ist es für alle besser, glaub mir.}
{260}{}{}
{261}{}{Ich habe sie fortgeschickt. Sie hätten Sklavenhändler hierhergelockt.}
{262}{}{Ich bin noch dabei.}

{263}{}{Genau das wollte ich hören! Und es geht nicht um billige Arbeitskräfte – wir sind hier alle gleich. Es geht um Sicherheit. Wenn du mir sagst, dass man ihnen trauen kann und sie keine Sklavenhändler anlocken, bin ich mehr als zufrieden.}
{264}{}{Gut.}
{265}{}{Tot?! Verdammt ... Du warst das doch nicht, oder? Nein, sag's mir nicht. Ich will es nicht wissen. [Er seufzt] Na ja, wenigstens wird Justin sich freuen ... }
{266}{}{Habe ich für meine Mühen nicht etwas verdient?}
{267}{}{}
{268}{}{}
{269}{}{Wenn man darüber nachdenkt ... Ja, es besteht die Möglichkeit, dass Sklavenhändler ihre Spur aufnehmen und sich auf den Weg nach Black Rock machen. Das wäre nicht gut, selbst wenn wir uns verteidigen können. Offenbar sind wir ohne Sklaven besser dran. Und ich bin besonders froh, dass die Sache friedlich gelöst wurde.}
{270}{}{Großartig.}

{271}{}{Vielen Dank für dein großes Verständnis für die Lage, das weiß ich sehr zu schätzen. Nimm dir ein Sandwich – nach dem ganzen Herumgerenne musst du hungrig sein.}
{272}{}{Danke.}
{273}{}{Immerhin etwas.}

{274}{}{Großartig! Du findest sie dicht gedrängt am Lagerfeuer vor Jeds Haus. Sag Justin nur nichts – er will sie einfach loswerden.}
{275}{}{Mal sehen.}
{276}{}{Nein, danke. Tut mir leid, aber ich wollte nicht, dass jemand stirbt! Was werden die Leute davon halten, wie wir Besucher behandeln? Ich schätze, Justin wird sich trotzdem freuen, es von dir zu hören.}
{277}{}{Mensch ...}

{278}{}{Danke, dass du so gute Arbeit geleistet hast. Nimm dir ein Sandwich und ein Bier – nach der ganzen Rennerei musst du doch hungrig sein.}

#Quest - missing brahmin
{300}{}{Kann ich sonst noch etwas tun?}
{301}{}{Wegen der verschwundenen brahmin ...}
{302}{}{}
{303}{}{Ich will nicht lügen – die Sache mit den Sklaven hat deinem Ruf nicht gerade gutgetan. Aber ich glaube, ich habe etwas für dich.}
{304}{}{Ich hatte gehofft, dass du danach fragst! Nachdem du dich um die entflohenen Sklaven gekümmert hast, habe ich etwas ganz nach deinem Geschmack.}
{305}{}{Worum geht's?}

{306}{}{Also, die Sache ist die: Mein Junge passt normalerweise nachts auf die brahmin auf, aber vor ein paar Tagen ist mir aufgefallen, dass eine fehlt. Justin sagt, mein Sohn sei schuld, aber das glaube ich nicht. Ich brauche jemanden, der der Sache auf den Grund geht.}
{307}{}{Ich glaube, ich kriege das hin.}
{308}{}{Tut mir leid, Kumpel, aber ich habe gerade andere Probleme.}
{309}{}{Großartig! Ich werde dich dafür ordentlich entlohnen, versprochen! Das Gehege für die brahmin ist gleich hinter der Gaststätte. Mein Sohn ist gerade dort draußen.}
{310}{}{Warte einfach, ich gehe mit ihm reden.}

{311}{}{Gibt es Neuigkeiten?}
{312}{}{Noch nichts.}

{313}{}{Stellt irgendjemand in Black Rock Schrotpatronen mit rostigen Nägeln her?}
{314}{}{Hmm, gute Frage ... Hier ist Munition schwer zu bekommen, deshalb heben wir sie normalerweise für besondere Gelegenheiten auf. Wenn jemand Munition herstellt, dann weiß Justin Bescheid. Er hat alle Werkzeuge und Maschinen der Stadt.}
{315}{}{Das sind alle Informationen, die ich brauchte.}
{316}{}{Ich habe den Dieb gefunden.}
{317}{}{Wer?! Wer war's?}
{318}{}{[Erzähl ihm die ganze Geschichte.]}
{319}{}{...Und er hat meinen Sohn vergiftet?! Dieser Bastard! Ich habe ihn bei mir aufgenommen, ihm wie einem Familienmitglied vertraut! Wie konnte dieser hinterhältige Mistkerl mir das antun?!}
{320}{}{}
{321}{}{Du solltest bedenken, dass sie ihn getötet hätten, wenn er nicht getan hätte, was sie verlangten. Es ist schwer, sein eigenes Ding durchzuziehen, wenn einem eine Schrotflinte vorgehalten wird. Er war Gefangener der Umstände, siehst du das nicht?}
{322}{}{Er ist gefährlich. Schon seine Anwesenheit zieht Raider an. Wir müssen ihn loswerden.}
{323}{}{Du meinst, ich soll ihm verzeihen? Nach allem, was er getan hat? [Er legt eine Hand ans Kinn und runzelt die Stirn] Na ja ... Er wurde dazu gezwungen. Und diese Bande, die Molerats – mit denen ist nicht zu spaßen. Nein, er ist genauso ein Opfer wie ich ... Ich verzeihe ihm, er darf bleiben. Und was brahmin angeht – ich glaube, er wird es wiedergutmachen.}
{324}{}{Gut. Ich gehe ihm die gute Nachricht überbringen.}
{325}{}{Ja ... Ja, du hast recht. Vielleicht hat er die Bande verlassen, aber die Bande hat ihn nicht verlassen. Mir gefällt das nicht, aber ... Wir müssen ihn zum Gehen bewegen.}
{326}{}{Denk daran: Es war deine Entscheidung. Ich gehe es ihm jetzt sagen.}
{327}{}{Warte! Ich habe dir eine Belohnung versprochen. Nimm etwas Geld, ein Sandwich und ein Bier. Geht aufs Haus. Danke für deine harte Arbeit, Freund.}
{328}{}{Gern geschehen.}

#Delivery
{350}{}{Noch mehr Arbeit?}
{351}{}{Wegen des Kuriers ...}
{352}{}{Du bist echt eine Maschine, was? Na gut, es gibt noch eine Sache. Sie ist etwas komplizierter als die letzten, aber nach Bolt und den Sklaven bin ich mir ziemlich sicher, dass du das hinbekommst.}
{353}{}{Keine Sorge. Ich schaffe das.}
{354}{}{Großartig! Ein Kurier sollte eine Lieferung überbringen, aber er ist schon ein paar Tage überfällig. Jemand muss ihn und die Pakete finden, die er bei sich hatte. Er kann nicht weit sein. Was sagst du?}
{355}{}{Ich werde mein Bestes geben.}
{356}{}{Für eine Lieferung durch die Wüste laufen und einen Boten suchen? Heute nicht.}

{357}{}{Ausgezeichnet! Der Kurier heißt Milo. Er kommt aus Gerlach, also würde ich dort mit der Suche anfangen. Frag herum und finde heraus, ob jemand etwas weiß.}
{358}{}{Ich habe noch mehr Fragen zu diesem Auftrag.}
{359}{}{Ich sehe, was ich tun kann.}

#Delivery - questions
{360}{}{Nur zu.}
{361}{}{[Seufzt] Ich habe gehört, Evan hatte einen Unfall. Das sind schlechte Nachrichten, aber das Paket müsste trotzdem noch unterwegs sein.}
{362}{}{Erzähl mir mehr über diesen Kurier.}
{363}{}{Er heißt Milo. Er lebt in Gerlach, liefert aber auch hierher. Viel gibt es über ihn nicht zu sagen – ruhig, professionell ... Das war's eigentlich schon. So sollte ein Kurier nun mal sein.}
{364}{}{Was hat er geliefert?}
{365}{}{Geckofelle von Evan. Bevor du fragst: Ja, wir haben eigene Jäger, aber Evan ist ein echter Meister. Seine Felle sind besser als die von jedem anderen hier in der Gegend.}
{366}{}{Erzähl mir von Gerlach.}
{367}{}{Es liegt westlich von hier. Eine kleine Siedlung, ähnlich wie unsere – nur verdammt viel strenger. Sie ist nach ihrem Gründer, Mr. Gerlach, benannt. Soweit ich weiß, hat er immer noch das Sagen.}
{368}{}{Wie hoch ist meine Belohnung?}
{369}{}{Hör zu, ich verstehe, dass du dafür eine Belohnung willst, aber hier steht ein Menschenleben auf dem Spiel! Finde ihn erst, dann reden wir über die Bezahlung, klar?}
{370}{}{Okay, ich suche nach ihm.}

{371}{}{Du kannst immer noch keinen Elefanten in der Wüste finden? Tut mir leid, schlechter Witz.}
{372}{}{Ich habe den Kurier gefunden ... Oder besser gesagt, was von ihm übrig ist.}
{373}{}{Er ist tot? Verdammt, der arme Milo. Was ist passiert?}
{374}{}{Mit einer Schaufel auf den Kopf geschlagen, das ist passiert. Er wurde von Eugene und der Molerats-Gang ermordet.}
{375}{}{Er wurde, äh, von Geckos gefressen. Bob und ich haben ihn schon begraben.}

{376}{}{Das hast du mir schon erzählt. Willst du noch was Neues sagen?}
{377}{}{Eigentlich habe ich vorher gelogen.}
{378}{}{Nein, nichts.}

{379}{}{Milo war ein guter Mann – zu gut, um so zu enden. Ich hoffe, seine Frau kommt damit zurecht. [Er seufzt] Na ja, danke, dass du mir Bescheid gesagt hast. Hier sind hundert Dollar. Ich würde dir gern mehr geben, aber ohne Milos Lieferung wird es bei mir eine Weile ziemlich knapp mit dem Geld. Tut mir leid.}
{380}{}{Immerhin etwas.}
{381}{}{Was meinst du?}
{382}{}{Milo wurde von Eugene und der Molerats-Gang ermordet. Mit einer Schaufel erschlagen.}
{383}{}{Ich werde noch mehr Beweise sammeln und wiederkommen. Bis dann.}

{384}{}{Oh mein Gott! Ich hatte ja keine Ahnung! Hör zu, wir dürfen keine Zeit verlieren. Lass uns sofort mit Justin und Eugene reden.}
{385}{}{Wenn du dir da so sicher bist ... }
{386}{}{[Nach einem riesigen Skandal kehrst du mit William in die Bar zurück] Diese verdammte Familie, ich schwör's! Eines Tages werde ich ... Ach, vergiss die erst mal. Eine Karawane aus Reno ist unterwegs, und Eugenes Bande plant einen Hinterhalt. Sie müssen aufgehalten werden, aber allein schaffen wir das nicht. Vielleicht gibt es da aber etwas, das wir tun können ... }
{387}{}{Was können wir tun, um die Karawane zu retten?}

{388}{}{Ich habe Eugenes Funkgerät mitgenommen. Hier. Wenn du die richtige Frequenz findest, kannst du diese Bastarde bei ihren Plänen belauschen und die Karawane warnen. Die Reichweite ist ziemlich kurz, also musst du schnell und vorsichtig sein.}
{389}{}{Hey, ich habe nie gesagt, dass ich da mitmache!}
{390}{}{Ich werde mein Bestes geben.}

{391}{}{Ich verlange nicht, dass du gegen sie kämpfst! Warne die Karawane einfach, bevor die Bande sie erreicht. Nur du kannst das schaffen. Über deine Belohnung reden wir später.}
{392}{}{Ich überleg's mir.}
{393}{}{Ich gehe. Ich bin so schnell wie möglich zurück.}
{394}{}{Ich habe Eugene die Decknamen und Frequenzen der Maulwurfsratten entlockt. Nimm sie. Damit kannst du ihre Gespräche belauschen und die Karawane warnen. Die Reichweite ist nicht besonders groß, also sei schnell und vorsichtig. Viel Glück.}

#Final converstaion about saved caravan
{395}{}{Hey, du bist es! Die Karawanenhändler haben mir alles erzählt! Du bist ein verdammter Wunderheiler, weißt du das?! Gute Arbeit!}
{396}{}{Zu solchen Worten würde eine Belohnung perfekt passen.}
{397}{}{Ich bin froh, dass ich helfen konnte.}
{398}{}{Du verlangst nicht mal eine Belohnung? Das ist nobel! Hör zu, ab jetzt bekommst du 20% d Rabatt auf meine Waren. Du bist hier jederzeit willkommen, merk dir das!}
{399}{}{Weißt du, du könntest mir für meine Mühen auch etwas mehr geben ... }
{400}{}{Danke für den Rabatt. Alles Gute!}
{401}{}{Ohne Evans Felle habe ich nicht viel. Ich kann dir zweihundert Dollar und 20% d Rabatt in meiner Gaststätte anbieten. Denk daran, wenn du in der Nähe bist!}
{402}{}{Wie wär's, wenn du mir stattdessen die alte Energiepistole gibst?}
{403}{}{Ich brauche Geld. Gib mir alles, was du kannst.}
{404}{}{Behalt das Geld, ich brauche es nicht.}

{405}{}{Du hast sie doch schon gekauft, erinnerst du dich? Glaubst du, ich habe zwei davon? Tut mir leid, aber das ist nicht so.}
{406}{}{Pass auf dich auf.}
{407}{}{Das ist verdammt noch mal eine gute Idee. Wer sonst würde dieses Stück Schrott hier haben wollen? Nimm es und viel Spaß damit.}
{408}{}{Mehr kann ich nicht tun. Tut mir leid, dass es nicht mehr ist.}
{409}{}{Na ja, wenigstens ist es etwas. Pass auf dich auf!}
{410}{}{Ich wusste, dass du das sagen würdest! Helden brauchen kein Geld, oder? Na gut, na gut, war nur ein Scherz. Aber den Rabatt meine ich ernst!}
{411}{}{Das werde ich mir merken. Jetzt muss ich los.}

{412}{}{Na ja, das war's. Die Karawane kommt nicht. All meine Mühe war umsonst. [Er seufzt] Vielleicht hatte Justin recht.}
{413}{}{Vielleicht lernst du etwas daraus. Vertrau niemandem. Ich muss weiter.}
{414}{}{Ist mir egal, das ist dein Problem.}
{415}{}{Ja ... Ja. Aber wir haben es versucht, oder?}
{416}{}{Richtig. Ich bin geschäftlich hier.}
{417}{}{Wie auch immer. Ich muss los.}

{420}{}{Oh, ja ... Hier sind hundert Mäuse dafür, dass du Milo gefunden hast. Tut mir leid, dass es nicht mehr ist, aber ohne Felle von Evan habe ich nicht viel übrig.}
{421}{}{Na gut.}

###########################################################################
#
#    Pop-ups - wasteland news
#
###########################################################################

#Starting onws
{500}{}{Neuigkeiten? Lass mich überlegen.}
{501}{}{Na, was gibt's Neues?}
{502}{}{Mal sehen, was gibt's sonst noch Neues ...}
{503}{}{Ein Reisender hat mir gestern etwas erzählt ...}
{504}{}{Ich habe Neuigkeiten aus dem Ödland! Wer will sie hören?}
{505}{}{Das Unheimlichste in der Wüste sind Sandstürme.}
{506}{}{Wir brauchen hier mal einen besseren Fusel ...}
{507}{}{Dieser herumziehende Leguanjäger wird schon eine Weile vermisst. Wir sollten nach ihm suchen.}

#Raiders destiny
{510}{}{Endlich hat jemand die Maulwurfsratten zur Rechenschaft gezogen!}
{511}{}{Wir müssen uns keine Sorgen mehr um die Maulwurfsratten machen.}
{512}{}{Wurde auch Zeit, dass sich jemand um diese Maulwurfsratten kümmert.}

{513}{}{Diese verdammten Maulwurfsratten. Es wird nur noch schlimmer werden.}
{514}{}{Nach dem, was sie mit der Karawane angestellt haben, sind die Maulwurfsratten zu allem fähig.}

{516}{}{Die Maulwurfsratten beherrschen immer noch den Süden unseres Tals.}
{517}{}{Manche sagen, von den Maulwurfsratten sei nicht mehr viel übrig, aber sie sind immer noch gefährlich.}

#Cheyenne's
{520}{}{Man sagt, die Cheyenne werden nicht mehr lange durchhalten. Bald sind sie nur noch eine Erinnerung.}
{521}{}{Wenn Big Louies Hunde die Cheyenne besiegen, was werden sie dann mit uns machen?}
{522}{}{Hier gäbe es mehr Karawanen, wenn Big Louies Hunde nicht wären.}
{523}{}{Heutzutage sollte man den Cheyenne besser aus dem Weg gehen.}
{524}{}{Wenn du keine Raider magst, mach lieber einen großen Bogen um Lovelock.}
{525}{}{Wer wollte hier nach Cheyenne? Das solltest du dir vielleicht noch mal überlegen. Die Raider sind völlig durchgedreht.}

{526}{}{Wer wollte nach Cheyenne? Gute Neuigkeiten: Die Raider sind kein Problem mehr!}
{527}{}{Endlich sind Big Louies Hunde tot. Das dürfte die Straßen viel sicherer machen.}
{528}{}{In Lovelock ist es viel friedlicher, seit Big Louie nicht mehr im Weg ist.}

#About Gerlach
{529}{}{Man sagt, Gerlach hält sich immer noch wacker. Der Kerl ist zäh!}
{530}{}{Fährt jemand zu unseren Nachbarn im Westen?}

{531}{}{Gerlach ... Es ist traurig zu hören, dass unsere Nachbarn fort sind.}
{532}{}{In Gerlach ist es verdächtig ruhig geworden. Da geht etwas Faules vor sich, wenn du mich fragst.}
{533}{}{Gerlach ist praktisch verlassen. Alle sind woanders hingegangen, aber keiner weiß wohin.}

#Stagecoach quest in Reno
{540}{}{Hast du von dem Vorfall bei „Nevada Express“ gehört? Bleib bloß weg – dort ist es sehr gefährlich!}
{541}{}{Ich hätte nicht gedacht, dass jemand „Nevada Express“ angreifen und gewinnen könnte.}
{542}{}{Es würde mich nicht überraschen, wenn „Nevada Express“ eine Falle gestellt worden wäre.}

#About Reno in general
{550}{}{Man sagt, in Reno geht es jetzt ziemlich drunter und drüber. Aber wann war das je anders?}
{551}{}{Bleib Reno lieber fern. Da geht echt beschissener Scheiß ab, wie ich gehört habe.}
{552}{}{Man sagt, in Reno war es seit dem Krieg nicht mehr so schlimm.}

{553}{}{Man sagt, in Reno ist es in letzter Zeit viel ruhiger geworden. Vielleicht sollten wir zurückkehren?}
{554}{}{Es klingt, als würde es in Reno endlich wieder besser werden.}
{555}{}{Ich habe gehört, dass der Bandenkrieg in Reno endlich vorbei ist!}

#About the Oasis City
{560}{}{Ein Reisender hat mir erzählt, irgendwo in den Bergen gäbe es eine Art Oase. Interessant.}
{561}{}{Hier hört man echt verrückte Geschichten. Wie soll es denn im Norden in den Bergen eine Stadt geben?}
{562}{}{Man sagt, in den Bergen gäbe es eine Stadt wie vor dem Krieg. Das kann doch nicht stimmen.}
{563}{}{Hast du von dieser Oasenstadt gehört, wo alle blaue Overalls tragen? Ja, das glaube ich auch nicht.}

#Local stuff
{570}{}{Hat jemand Mikes Kampf gesehen? Das muss eine verdammt gute Show gewesen sein!}
{571}{}{Bob sagt, jemand gräbt die Gräber aus. Ich mache mir Sorgen um ihn ...}

{572}{}{Entlaufene Sklaven? Na und? Sie sind auch Menschen! Gib ihnen einfach eine Chance!}
{573}{}{Entlaufene Sklaven? Nun, dazu gibt es jetzt nicht viel zu sagen.}

{574}{}{Ja, die Sache mit brahmin war peinlich.}

###########################################################################

#Female character
{1116}{}{Hey, Freund! Schön, dich zu sehen!}
{1261}{}{Ich habe sie fortgeschickt. Sie hätten Sklavenhändler hierhergelockt.}
{1271}{}{Vielen Dank für dein großes Verständnis für die Lage, das weiß ich sehr zu schätzen. Nimm dir ein Sandwich – nach dem ganzen Herumgerenne musst du hungrig sein.}
{1278}{}{Danke, dass du so gute Arbeit geleistet hast. Nimm dir ein Sandwich und ein Bier – nach der ganzen Rennerei musst du doch hungrig sein.}
{1376}{}{Das hast du mir schon erzählt. Willst du noch was Neues sagen?}
{1377}{}{Eigentlich habe ich vorher gelogen.}
{1389}{}{Hey, ich habe nie gesagt, dass ich da mitmache!}
{1397}{}{Ich bin froh, dass ich helfen konnte.}
{1405}{}{Du hast sie doch schon gekauft, erinnerst du dich? Glaubst du, ich habe zwei davon? Tut mir leid, aber das ist nicht so.}
{1407}{}{Das ist verdammt noch mal eine gute Idee. Wer sonst würde dieses Stück Schrott hier haben wollen? Nimm es und viel Spaß damit.}