{100}{}{Du siehst einen jungen Jungen.}
{101}{}{Du siehst einen niedlichen jungen Jungen. Er stinkt nach Mist.}

{110}{}{Ja, Sir?}
{111}{}{Ich bin nur auf der Durchreise.}

#Missing brahmin
{120}{}{Dein Vater hat mich gebeten, nach einem vermissten brahmin zu suchen. Was hast du zu deiner Verteidigung zu sagen?}
{121}{}{Reden wir über das vermisste brahmin.}
{122}{}{Ich habe nichts falsch gemacht! Wirklich! Es ist, als hätte es sie nie gegeben – nachts war sie noch hier, und morgens war sie weg! Sie ist einfach verschwunden! Ich sage die Wahrheit!}

{123}{}{Wie sah das brahmin aus?}
{124}{}{Wie jedes normale brahmin. Vier Hufe, zwei Köpfe, ein Schwanz ... Stinkt ...}
{125}{}{Wo hast du es zuletzt gesehen?}
{126}{}{Sie war genau dort, um die Ecke! Und morgens war sie weg! Einfach verschwunden!}
{127}{}{War in der Nacht noch jemand in der Nähe?}
{128}{}{Nein! Da bin ich mir sicher! Denn ... Denn ich habe nicht geschlafen, und ich habe das Tor mit einem besonderen Knoten zugebunden! Wenn jemand das Seil lösen würde, wüsste ich es, denn er würde es nicht auf dieselbe Weise wieder zuknoten! Niemand hätte das geschafft! Nicht einmal die Toilette, nicht einmal das Zelt dieser Dame aus Reno ist nah genug, dass jemand ein Brahmin stehlen könnte, ohne dass ich es bemerke!}
{129}{}{Hör mal, Junge, ich merke, dass du mich anlügst. Sag die Wahrheit, oder es setzt was.}
{130}{}{Du ... Du sagst es meinem Vater doch nicht, oder? Ich bin eingeschlafen ... Es tut mir leid! Nachts schlafe ich normalerweise nicht! Aber sobald ich etwas Wasser getrunken hatte, war ich einfach ... Ich weiß nicht! Ich kann mich nicht einmal daran erinnern, müde gewesen zu sein, aber ich bin erst morgens aufgewacht. Und dann war das brahmin weg! Es muss irgendeine Art von ... von Strahlung gewesen sein, oder ein brahmin-stehlender Mutant mit besonderen Kräften!}
{131}{}{Ein Rätsel, in der Tat.}

{132}{}{Du findest es doch, oder? Mein Vater wird wütend, wenn du es nicht findest!}
{133}{}{Vielleicht, vielleicht auch nicht. Vielleicht habe ich Glück.}
{134}{}{Ich werde alles tun, was ich kann.}
{135}{}{Ich habe dir alles erzählt! Ehrlich!}
{136}{}{Na gut, warte hier.}

{140}{}{Kam in jener Nacht jemand mit einer Schrotflinte vorbei?}
{141}{}{Ich habe niemanden gesehen, aber ... Die Leute kommen ständig am Klo vorbei. Ich kann mich nicht erinnern, da waren zu viele.}
{142}{}{Verstehe. Dann suche ich weiter nach einem Mann mit einer Schrotflinte ...}

#Questioning
{152}{}{Ich möchte dich nur etwas fragen.}
{153}{}{Was?}
{154}{}{Nichts.}
{155}{}{Was machst du hier?}
{156}{}{Was sind das für Tiere?}
{157}{}{Was kannst du mir über Black Rock erzählen?}
{158}{}{Das reicht.}

{159}{}{Mein Vater hat diesen Pferch vor ein paar Jahren gebaut. Meine Aufgabe ist es, auf die brahmin aufzupassen, damit sie niemand stiehlt!}
{160}{}{[Er sieht ungläubig aus] Du weißt nicht, was ein brahmin ist?! Ich wusste gar nicht, dass das möglich ist! Also ... Es sind Tiere. Wir züchten sie, schlachten sie dann, und mein Vater macht daraus Fleischsuppe. Die ist wirklich gut!}
{161}{}{Ich wohne hier! Ich war noch nie woanders, außer einmal in Gerlach, aber das zählt eigentlich nicht, weil ich mit niemandem gesprochen habe.}
{162}{}{Gerlach?}
{163}{}{Ja. Da lang. [Er zeigt nach Westen]}
{164}{}{Wird dir hier nicht langweilig?}
{165}{}{Ja, es ist WIRKLICH langweilig. Manchmal will ich einfach weg und nach Hause, aber mein Vater lässt mich nicht. Wenn die brahmin nachts schlafen, kannst du aber mit ihnen spielen. Du schleichst dich leise an und schlägst ihnen auf den Bauch, dann rennst du weg! Und dann schauen sie sich um und sagen: „Hä??? Was ist los???“ Hahahaha!}

#Female character
{1110}{}{Ja, Ma'am?}
