# Brok Encounter Table
{100}{}{Du triffst auf Schurken und Wölfe.}
{101}{}{Du triffst auf Schurken.}
{102}{}{Du triffst auf Wölfe.}
{103}{}{Du triffst auf Skorpione.}
{104}{}{Du triffst auf Sporenpflanzen.}
{105}{}{Du triffst auf eine Unity-Patrouille, die gegen Schurken kämpft.}
{106}{}{Du triffst auf eine Unity-Patrouille, die gegen Wölfe kämpft.}
{107}{}{Du triffst auf eine Unity-Patrouille.}

# VPat Encounter Table
{150}{}{Du triffst auf Sklavenhändler und Hunde.}
{151}{}{Du triffst auf Sklavenhändler.}
{152}{}{Du triffst auf goldene Geckos.}
{153}{}{Du triffst auf wilde Hunde.}
{154}{}{Du triffst auf eine Patrouille und Hunde, die gegen Sklavenhändler kämpfen.}
{155}{}{Du triffst auf Sklavenhändler, die gegen goldene Geckos kämpfen.}
{156}{}{Du triffst auf eine Patrouille, die gegen Sklavenhändler kämpft.}
{157}{}{Du triffst auf eine Patrouille, die gegen goldene Geckos kämpft.}
{158}{}{Du triffst auf eine Patrouille, die gegen wilde Hunde kämpft.}
{159}{}{Du triffst auf eine Patrouille.}

# RDRC Encounter Table
{200}{}{Du wirst von Plünderern überfallen.}
{201}{}{Du triffst auf Wölfe.}
{202}{}{Du triffst auf eine Karawane, die sich gegen Plünderer zur Wehr setzt.}
{203}{}{Du triffst auf eine Karawane, die sich gegen Plünderer zur Wehr setzt.}
{204}{}{Du triffst auf eine Karawane, die sich gegen Plünderer zur Wehr setzt.}
{205}{}{Du triffst auf eine Karawane, die sich gegen Plünderer zur Wehr setzt.}
{206}{}{Du triffst auf eine Karawane.}
{207}{}{Du triffst auf eine Karawane.}
{208}{}{Du triffst auf eine Karawane.}
{209}{}{Du triffst auf eine Karawane.}

# VNNB Encounter Table
{250}{}{Du triffst auf Marodeure.}
{251}{}{Du triffst auf Wölfe.}
{252}{}{Du triffst auf Skorpione.}
{253}{}{Du triffst auf eine Karawane, die sich gegen Marodeure zur Wehr setzt.}
{254}{}{Du triffst auf eine Karawane, die sich gegen Marodeure zur Wehr setzt.}
{255}{}{Du triffst auf eine Karawane, die sich gegen Wölfe zur Wehr setzt.}
{256}{}{Du triffst auf einen Karawanenzug, der Skorpione abwehrt.}
{257}{}{Du triffst auf eine Karawane.}
{258}{}{Du triffst auf eine Karawane.}
{259}{}{Du triffst auf eine Karawane.}
{260}{}{Du triffst auf eine Karawane.}
{261}{}{Du triffst auf einen Reisenden.}

# NCR Encounter Table
{300}{}{Du triffst auf Überreste der Armee des Meisters.}
{301}{}{Du triffst auf Marodeure.}
{302}{}{Du triffst auf NCR-Ranger, die gegen Überreste der Armee des Meisters kämpfen.}
{303}{}{Du triffst auf NCR-Ranger, die gegen Plünderer kämpfen.}
{304}{}{Du triffst auf Farmer, die Überreste der Armee des Meisters abwehren.}
{305}{}{Du triffst auf Farmer, die Plünderer abwehren.}
{306}{}{Du triffst auf NCR-Ranger.}
{307}{}{Du triffst auf Farmer.}

# DNRV Encounter Table
{350}{}{Du triffst auf einen Sklavenhändler-Karawanenzug.}
{351}{}{Du triffst auf Wegelagerer und Räuber.}
{352}{}{Du triffst auf Wegelagerer.}
{353}{}{Du triffst auf Räuber.}
{354}{}{Du triffst auf einen Karawanenzug, der Wegelagerer abwehrt.}
{355}{}{Du triffst auf einen Karawanenzug, der gegen Räuber kämpft.}
{356}{}{Du triffst auf einen Karawanenzug, der gegen Wegelagerer kämpft.}
{357}{}{Du triffst auf einen Karawanenzug, der von Räubern belagert wird.}
{358}{}{Du triffst auf einen Sklavenkarawanenzug, der gegen einen Karawanenzug kämpft.}
{359}{}{Du triffst auf Wegelagerer, die gegen Räuber kämpfen.}
{360}{}{Du triffst auf eine Karawane.}
{361}{}{Du triffst auf eine Karawane.}

# DMRV Encounter Table
{400}{}{Du triffst auf Wegelagerer.}
{401}{}{Du triffst auf Räuber.}
{402}{}{Du triffst auf Räuber und Wegelagerer.}
{403}{}{Du triffst auf Goldgeckos und Skorpione.}
{404}{}{Du triffst auf goldene Geckos.}
{405}{}{Du triffst auf Maulwurfsratten und Schweineratten.}
{406}{}{Du triffst auf Skorpione.}
{407}{}{Du triffst auf Sporenpflanzen.}
{408}{}{Du triffst auf Räuber, die gegen Wegelagerer kämpfen.}
{409}{}{Du triffst auf einen Karawanenzug, der Wegelagerer abwehrt.}
{410}{}{Du triffst auf einen Karawanenzug, der Räuber abwehrt.}
{411}{}{Du triffst auf einen Karawanenzug, der Skorpione abwehrt.}
{412}{}{Du triffst auf Geckos, die gegen Skorpione kämpfen.}
{413}{}{Du triffst auf eine Karawane.}

# Band Encounter Table
{450}{}{Du triffst auf Wegelagerer und Räuber.}
{451}{}{Du triffst auf Wegelagerer und Geckos.}
{452}{}{Du triffst auf goldene Geckos.}
{453}{}{Du triffst auf Skorpione und Sporenpflanzen.}
{454}{}{Du triffst auf Räuber, die gegen Skorpione kämpfen.}
{455}{}{Du triffst auf Skorpione, die gegen Räuber kämpfen.}
{456}{}{Du triffst auf einen Karawanenzug, der Wegelagerer abwehrt.}
{457}{}{Du triffst auf einen Karawanenzug, der Räuber abwehrt.}
{458}{}{Du triffst auf einige Wegelagerer, die Sporenpflanzen ausjäten.}
{459}{}{Du triffst auf eine Karawane.}

# DVMV Encounter Table
{500}{}{Du triffst auf Wegelagerer und Wildhunde.}
{501}{}{Du triffst auf Räuber und wilde Hunde.}
{502}{}{Du triffst auf Räuber.}
{503}{}{Du triffst auf Wegelagerer.}
{504}{}{Du triffst auf einen Schwarm Gottesanbeterinnen und einige Sporenpflanzen.}
{505}{}{Du triffst auf Hunde und Sporenpflanzen.}
{506}{}{Du triffst auf einen Schwarm Gottesanbeterinnen.}
{507}{}{Du triffst auf wilde Hunde.}
{508}{}{Du triffst auf Räuber, die gegen Hunde kämpfen.}
{509}{}{Du triffst auf eine Karawane, die Hunde abwehrt.}
{510}{}{Du triffst auf einen Karawanenzug, der Räuber abwehrt.}
{511}{}{Du triffst auf einen Karawanenzug, der Wegelagerer abwehrt.}
{512}{}{Du triffst auf eine Karawane.}

# Red Encounter Table
{550}{}{Du triffst auf Geckos und Wölfe.}
{551}{}{Du triffst auf Räuber.}
{552}{}{Du triffst auf Wölfe.}
{553}{}{Du triffst auf goldene Geckos.}
{554}{}{Du triffst auf Prospektoren, die Räuber abwehren.}
{555}{}{Du triffst auf Fallensteller, die Geckos jagen.}
{556}{}{Du triffst auf Schwarzbrenner, die gegen Wölfe kämpfen.}
{557}{}{Du triffst auf Siedler, die gegen Räuber kämpfen.}
{558}{}{Du triffst auf Siedler, die gegen Wölfe kämpfen.}
{559}{}{Du triffst auf Schwarzbrenner.}
{560}{}{Du triffst auf Fallensteller.}
{561}{}{Du triffst auf Prospektoren.}

# SRNRRN Encounter Table
{600}{}{Du triffst auf Todeskrallen.}
{601}{}{Du triffst auf Feuergeckos.}
{602}{}{Du triffst auf eine Karawane, die vor Todeskrallen flieht.}
{603}{}{Du triffst auf eine Karawane, die gegen Todeskrallen kämpft.}
{604}{}{Du triffst auf eine Karawane, die gegen Feuergeckos kämpft.}
{605}{}{Du triffst auf eine Karawane, die gegen Feuergeckos kämpft.}
{606}{}{Du triffst auf eine Karawane.}
{607}{}{Du triffst auf eine Karawane.}
{608}{}{Du triffst auf eine Karawane.}
{609}{}{Du triffst auf eine Karawane.}

# EPA Encounter Table
{650}{}{Du triffst auf Aliens und Todeskrallen.}
{651}{}{Du triffst auf Zentauren und Schweber.}
{652}{}{Du triffst auf Feuergeckos.}
{653}{}{Du triffst auf Aliens.}
{654}{}{Du triffst auf Todeskrallen.}
{655}{}{Du triffst auf Feuergeckos.}
{656}{}{Du triffst auf Aliens.}
{657}{}{Du triffst auf Zentauren.}
{658}{}{Du triffst auf Schweber.}

# New Encounter Table
{700}{}{Du triffst auf einige Yakuza.}
{701}{}{Du triffst auf eine Gang.}
{702}{}{Du triffst auf einige Wölfe.}
{703}{}{Du triffst auf einige Mobster, die gegen einige Yakuza kämpfen.}
{704}{}{Du triffst auf einige Mobster, die gegen eine Gang kämpfen.}
{705}{}{Du triffst auf einige Mobster.}
{706}{}{Du triffst auf einen Reisenden.}

# NRNR Encounter Table
{750}{}{Du triffst auf eine Karawane, die Überreste der Armee des Meisters abwehrt.}
{751}{}{Du triffst auf eine Karawane, die gegen Überreste der Armee des Meisters kämpft.}
{752}{}{Du triffst auf eine Karawane, die gegen Todeskrallen kämpft.}
{753}{}{Du triffst auf eine Karawane.}
{754}{}{Du triffst auf eine Karawane.}
{755}{}{Du triffst auf eine Karawane.}