{100}{}{Du siehst einen Generator.}

{101}{}{Der Generator befindet sich im Energiesparmodus. Du kannst ihn für kurze Zeit in den Normalmodus zurückversetzen.}
{102}{}{Der Generator ist betriebsbereit. Die Stromversorgung ist vollständig wiederhergestellt.}

{103}{}{Watts Electronics-Generatoren verwenden eine andere Energiequelle.}
{104}{}{Der Generator ist betriebsbereit.}
{105}{}{Du versetzt den Generator wieder in den Betriebsmodus. Die Stromversorgung der Radarstation ist wiederhergestellt.}
{106}{}{[Fertig]}
{107}{}{Das wird nicht mehr benötigt.}
