{100}{}{Hey, Kleiner, was zum Teufel willst du da?!}
{101}{}{Es ist verschlossen – aber du kannst kein Schloss erkennen.}
{102}{}{Das Tor hat kein sichtbares Schloss. Vielleicht lässt es sich anders öffnen.}
{103}{}{Die Tür ist mit einer Falle versehen.}
{104}{}{Es passiert nichts.}
{105}{}{Das Tor ist kaputt.}
{106}{}{Es gibt kein Schlüsselloch. Seltsam. Vielleicht funktioniert es anders?}
{107}{}{Das Tor lässt sich irgendwie anders öffnen. Fähigkeiten helfen hier nicht weiter.}
