{100}{}{Du siehst ein Terminal.}
{101}{}{Du siehst ein funktionierendes Terminal.}

{102}{}{Der Computer lässt sich nicht einschalten. Offenbar hat er nicht genug Strom.}
{103}{}{[Herunterfahren]}
{104}{}{Das Terminal leuchtet kurz mit allen Anzeigen auf, dann erlöschen sie und der Hauptmonitor schaltet sich ein. Erstaunlich, dass die Technik noch funktioniert.}
{105}{}{[Folge dem Peilsendersignal von Aufsehers Pip-Boy]}
{106}{}{[Funkgerät überprüfen]}
{107}{}{Du hörst nur „Rauschen“.}

{110}{}{Es gibt ein Signal! Der grüne Punkt bewegt sich schnell nordöstlich von Salt Lake. Selbst mit einem Auto wirst du die Entführer nicht einholen können. Das Signal wird bald außerhalb der Radarreichweite sein.}
{111}{}{Sieht so aus, als müsstest du eine Art Schienenfahrzeug finden, um sie zu verfolgen. Vielleicht gibt es etwas Passendes in Salt Lake?}