{100}{}{Nicht überraschend: brahmin ist genauso tot wie bei deinem letzten Besuch.}
{101}{}{Du hast brahmin gefunden, der vermisst wurde – oder besser gesagt, was von ihm übrig ist. Nichts ist geblieben außer Kopf und Hufen. Sie stinken bereits nach Verwesung.}
{102}{}{[Sorgfältig untersuchen]}
{103}{}{Trotz des Übelkeit erregenden Gestanks entdeckst du, dass beide Schädel gezackte Löcher aufweisen, die von Einschusslöchern umringt sind. In den Schädeln stecken Nägel, vermutlich aus selbstgemachten Schrotpatronen.}
{104}{}{Interessant ...}
