{100}{}{Türsteuerungsterminal.}
{101}{}{Dieser Computer steuert das große Vault-Tor.}

{104}{}{Niemand antwortet auf deinen Ruf.}
{105}{}{Du erhältst Erfahrung dafür, andere Vault-Bewohner ausfindig zu machen.}

{107}{}{Du siehst eine Konsole. Die Vault-Tür kannst du damit nicht öffnen, aber du kannst versuchen, ein Signal zu senden.}
{108}{}{Vault kontaktieren.}
{109}{}{[Gehen]}
{110}{}{(Aus dem Lautsprecher dringen Rauschen und Störungen, etwas Knistern, dann eine Stimme) Äh... Hallo...}
{111}{}{Haben Sie Pizza bestellt?}
{112}{}{W-was... [Pause] Ähm... Nein.}
{113}{}{Wie wär's mit dem „Deepthroat“-Film?}
{114}{}{Nein.}
{115}{}{Fehlt Ihnen nicht ein Taschentuch?}
{116}{}{Nein.}
{117}{}{Oh, was weißt du schon! Es ist so hübsch... Übrigens, kannst du mir sagen, wie spät es ist?}
{118}{}{Nein.}
{119}{}{Seltsam... Könntest du...}
{120}{}{Nein.}
{121}{}{Oh... Bist du sicher, dass es nicht dein Taschentuch ist?}
{122}{}{Nein, ist es nicht.}
{123}{}{Warum bin ich dann noch hier?}
{124}{}{Keine Ahnung. Wo genau bist du?}
{125}{}{Draußen, vor der Vault-Tür. Ist das nicht offensichtlich?}
{126}{}{Aber... Das kann nicht sein! Wo bist du?! Ich meine... Rufst du aus einer anderen Vault an?}
{127}{}{Na ja, nicht ganz. Ich komme zwar aus einer anderen Vault, aber gerade bin ich zufällig vor deiner.}
{128}{}{Hmm... Und wie bist du hierhergekommen?!}
{129}{}{Zu Fuß. Es war nicht schwer. Na ja, wäre es nicht gewesen, wenn nicht Mutanten, Raider und ihresgleichen das Ödland bevölkern würden. Könntest du vielleicht die Tür öffnen, damit wir bei einem Glas kaltem Nuka-Cola reden können?}
{130}{}{[Pause] Tut mir leid, aber ich kann das Risiko nicht eingehen. Ich weiß nicht, wie die Lage hinter dieser Tür ist. Was, wenn diese... Mutanten und Raider hier reinkommen? Außerdem bin ich immer noch nicht sicher, ob das alles nicht irgendein Scherz ist.}
{131}{}{Was ist mit den Monitoren eurer Vault? Überwachst du sie überhaupt? Ihr könnt längst an die Oberfläche! Wir haben es geschafft und bauen jetzt eine Stadt.}
{132}{}{Bauen? Wie denn?}
{133}{}{Na, mit einem G.E.C.K. natürlich!}
{134}{}{Vielleicht hast du recht, wir müssen deine Informationen überprüfen. Aber vorerst bleiben wir wohl hinter diesen Türen. Danke, dass du dich bei uns gemeldet hast. Tut mir leid, dass ich nicht länger mit dir sprechen kann, ich habe ein wichtiges Treffen.}
{135}{}{Wa... Moment mal...}

{136}{}{(Signal verloren)}
{137}{}{Verdammter Feigling!}
{138}{}{[Verlassen]}
{139}{}{Nein, du! (Signal erneut verloren)}
{140}{}{[Verlassen]}