#############################################################
#  Message File: containr.msg                               #
#  Fallout: Nevada (Crazy Edition)                          #
#  Fix Error Use Skill on the Door (Random Maps)            #
#############################################################

#############################################################
#  The following lines are for description of the door. The #
#  first lines, line 100-1, are for the look_at_proc. The   #
#  remainder until the next block are for description_proc  #
#  based one skill and perception success.                  #
#############################################################

# look_at_proc
{100}{}{Du siehst eine Holzkiste.}
{101}{}{Du siehst einen Metallschrank.}
{212}{}{Du siehst einen Kühlschrank.}

# description_proc

# Perception Check Critical Success
{102}{}{Du siehst einen robusten Behälter, der verschlossen ist (sich aber vermutlich mit einem Dietrich öffnen lässt) und mit einer Sprengfalle versehen ist. Vielleicht könntest du ihn aufbrechen.}
{103}{}{Du siehst einen robusten Behälter, der verschlossen und mit einer Sprengfalle versehen ist. Vielleicht könntest du ihn aufbrechen.}
{104}{}{Du siehst einen robusten Behälter, der scheinbar kein Schloss hat, aber mit einer Sprengfalle versehen ist. Vielleicht könntest du ihn aufbrechen.}
{105}{}{Du siehst einen robusten Behälter mit einem alten, rostigen Schloss und einer Sprengfalle. Vielleicht könntest du ihn aufbrechen.}

{106}{}{Du siehst einen robusten Behälter, der verschlossen ist (sich aber vermutlich mit einem Dietrich öffnen lässt) und mit einer Falle versehen ist. Vielleicht könntest du ihn aufbrechen.}
{107}{}{Du siehst einen robusten Behälter, der verschlossen und mit einer Falle versehen ist. Vielleicht könntest du ihn aufbrechen.}
{108}{}{Du siehst einen robusten Behälter, der scheinbar kein Schloss hat, aber mit einer Falle versehen ist. Vielleicht könntest du ihn aufbrechen.}
{109}{}{Du siehst einen robusten Behälter mit einem alten, rostigen Schloss und einer Falle. Vielleicht könntest du ihn aufbrechen.}

{110}{}{Du siehst einen robusten Behälter, der verschlossen ist (sich aber vermutlich mit einem Dietrich öffnen lässt) und an dem ein Draht befestigt ist. Vielleicht könntest du ihn aufbrechen.}
{111}{}{Du siehst einen robusten Behälter, der verschlossen ist und an dem zerrissene Drähte befestigt sind. Vielleicht könntest du ihn aufbrechen.}
{112}{}{Du siehst einen robusten Behälter, offenbar ohne Schloss. An seiner Tür hängen abgerissene Drähte. Vielleicht kannst du ihn aufbrechen.}
{113}{}{Du siehst einen robusten Behälter mit einem alten, verrosteten Schloss und einem Draht daran. Vielleicht kannst du ihn aufbrechen.}

{114}{}{Du siehst einen robusten Behälter, der verschlossen ist (sich aber wahrscheinlich mit einem Dietrich öffnen lässt). Vielleicht kannst du ihn aufbrechen.}
{115}{}{Du siehst einen robusten Behälter, der verschlossen ist. Vielleicht kannst du ihn aufbrechen.}
{116}{}{Du siehst einen robusten Behälter, offenbar ohne Schloss. Vielleicht kannst du ihn aufbrechen.}
{117}{}{Du siehst einen robusten Behälter mit einem alten, verrosteten Schloss. Vielleicht kannst du ihn aufbrechen.}

# Perception Check Success

{118}{}{Du siehst einen robusten Behälter, der verschlossen ist – sich aber wahrscheinlich mit einem Dietrich öffnen lässt – und mit einer Sprengfalle versehen ist.}
{119}{}{Du siehst einen robusten Behälter, der verschlossen und mit einer Sprengfalle versehen ist.}
{120}{}{Du siehst einen robusten Behälter, offenbar ohne Schloss, aber mit einer Sprengfalle daran.}
{121}{}{Du siehst einen robusten Behälter mit einem alten, verrosteten Schloss und einer Sprengfalle.}

{122}{}{Du siehst einen robusten Behälter, der verschlossen und mit einer Sprengfalle versehen ist (sich aber wahrscheinlich mit einem Dietrich öffnen lässt).}
{123}{}{Du siehst einen robusten Behälter, der verschlossen und mit einer Falle versehen ist.}
{124}{}{Du siehst einen robusten Behälter, offenbar ohne Schloss, aber mit einer Falle daran.}
{125}{}{Du siehst einen robusten Behälter mit einem alten, verrosteten Schloss und einer Falle daran.}

{126}{}{Du siehst einen robusten Behälter, der verschlossen ist (sich aber wahrscheinlich mit einem Dietrich öffnen lässt) und einen Draht daran hat.}
{127}{}{Du siehst einen robusten Behälter, der verschlossen ist und an dem abgerissene Drähte hängen.}
{128}{}{Du siehst einen robusten Behälter, offenbar ohne Schloss. An seiner Tür hängen abgerissene Drähte.}
{129}{}{Du siehst einen robusten Behälter mit einem alten, verrosteten Schloss und einem Draht daran.}

{130}{}{Du siehst einen robusten Behälter, der verschlossen ist, sich aber wahrscheinlich mit einem Dietrich öffnen lässt.}
{131}{}{Du siehst einen robusten Behälter, der verschlossen ist.}
{132}{}{Du siehst einen stabilen Behälter, scheinbar ohne Schloss.}
{133}{}{Du siehst einen stabilen Behälter mit einem alten, rostigen Schloss.}

# Perception Check Critical Failure

{134}{}{Du siehst einen beschädigten, verschlossenen Behälter mit einer Sprengfalle. Wahrscheinlich lässt er sich mit einem Dietrich öffnen.}
{135}{}{Du siehst einen beschädigten, verschlossenen Behälter mit einer Sprengfalle.}
{136}{}{Du siehst einen beschädigten Behälter, scheinbar ohne Schloss, aber mit einer Sprengfalle.}
{137}{}{Du siehst einen beschädigten Behälter mit einem alten, rostigen Schloss und einer Sprengfalle.}

{138}{}{Du siehst einen beschädigten, verschlossenen Behälter mit einer Falle. Wahrscheinlich lässt er sich mit einem Dietrich öffnen.}
{139}{}{Du siehst einen beschädigten, verschlossenen Behälter mit einer Falle.}
{140}{}{Du siehst einen beschädigten Behälter, scheinbar ohne Schloss, aber mit einer Falle.}
{141}{}{Du siehst einen beschädigten Behälter mit einem alten, rostigen Schloss und einer Falle.}

{142}{}{Du siehst einen beschädigten, verschlossenen Behälter mit einem Draht. Wahrscheinlich lässt er sich mit einem Dietrich öffnen.}
{143}{}{Du siehst einen beschädigten, verschlossenen Behälter mit zerrissenen Drähten.}
{144}{}{Du siehst einen beschädigten Behälter, scheinbar ohne Schloss. An der Tür sind zerrissene Drähte.}
{145}{}{Du siehst einen beschädigten Behälter mit einem alten, rostigen Schloss und einem Draht.}

{146}{}{Du siehst einen beschädigten, verschlossenen Behälter. Wahrscheinlich lässt er sich mit einem Dietrich öffnen.}
{147}{}{Du siehst einen beschädigten, verschlossenen Behälter.}
{148}{}{Du siehst einen beschädigten Behälter, scheinbar ohne Schloss.}
{149}{}{Du siehst einen beschädigten Behälter mit einem alten, rostigen Schloss.}

# Perception Check Failure

{150}{}{Du siehst einen alten, verschlossenen Behälter mit einer Sprengfalle. Wahrscheinlich lässt er sich mit einem Dietrich öffnen.}
{151}{}{Du siehst einen alten, verschlossenen Behälter mit einer Sprengfalle.}
{152}{}{Du siehst einen alten Behälter, scheinbar ohne Schloss, aber mit einer Sprengfalle.}
{153}{}{Du siehst einen alten Behälter mit einem alten, rostigen Schloss und einer Sprengfalle.}

{154}{}{Du siehst einen alten, verschlossenen Behälter mit einer Sprengfalle (aber wahrscheinlich lässt er sich mit einem Dietrich öffnen).}
{155}{}{Du siehst einen alten, verschlossenen Behälter mit einer Falle daran.}
{156}{}{Du siehst einen alten Behälter, der scheinbar kein Schloss hat, aber mit einer Falle versehen ist.}
{157}{}{Du siehst einen alten Behälter mit einem alten, rostigen Schloss und einer Falle daran.}

{158}{}{Du siehst einen alten, verschlossenen Behälter (aber wahrscheinlich lässt er sich mit einem Dietrich öffnen), an dem ein Draht befestigt ist.}
{159}{}{Du siehst einen alten, verschlossenen Behälter mit abgerissenen Drähten daran.}
{160}{}{Du siehst einen alten Behälter, der scheinbar kein Schloss hat. An seiner Tür sind abgerissene Drähte befestigt.}
{161}{}{Du siehst einen alten Behälter mit einem alten, rostigen Schloss und einem Draht daran.}

{162}{}{Du siehst einen alten, verschlossenen Behälter, der sich aber wahrscheinlich mit einem Dietrich öffnen lässt.}
{163}{}{Du siehst einen alten, verschlossenen Behälter.}
{164}{}{Du siehst einen alten Behälter, der scheinbar kein Schloss hat.}
{165}{}{Du siehst einen alten Behälter mit einem alten, rostigen Schloss.}

#############################################################
#  The following lines are for damage done to the player or #
#  critter who tried to open the door, or failed a traps    #
#  roll.                                                    #
#############################################################

# The following sets of lines are to be translated as:
# You set off the trap and were hit for [x] points of damage.
# NPC sets of the trap and was hit for [x] points of damage.

# Player sets off the trap
{166}{}{Du löst die Falle aus und erhältst }
{167}{}{ Schadenspunkte.}

# NPC sets off the trap
{168}{}{ löst die Falle aus und erhält }
{169}{}{ Schadenspunkte.}

#############################################################
#  The following lines are for when the player uses skills  #
#  on the door.                                             #
#############################################################

# Player uses a skill on the door
# Unlock Door
{170}{}{Du öffnest das Schloss des Behälters geschickt.}
{171}{}{Wegen deiner Unerfahrenheit hast du das Schloss des Behälters verklemmt.}
{172}{}{Du konntest das Schloss des Behälters nicht öffnen.}

# Lock Door
{189}{}{Du verschließt den Behälter geschickt.}
{190}{}{Du konntest den Behälter nicht verschließen.}

# Find Trap on the Door
{194}{}{Du bemerkst eine Falle am Behälter.}
{195}{}{Du bemerkst keine Fallen am Behälter.}

# Disarm the Trap on the Door
{196}{}{Du entschärfst die Falle geschickt.}
{198}{}{Du konntest die Falle nicht entschärfen.}

# NPC uses a skill on the door
# The following lines are prepended by the NPC's name

# Unlock Door
{173}{}{ öffnet das Schloss des Behälters geschickt.}
{174}{}{ -- hat das Schloss des Behälters verklemmt.}
{175}{}{ -- konnte den Behälter nicht öffnen.}

# Lock Door
{191}{}{ verschließt den Behälter geschickt.}
{192}{}{ -- konnte den Behälter nicht verschließen.}

# Find Trap on the Door
{199}{}{ bemerkt eine Falle am Behälter.}
{200}{}{ -- bemerkt keine Fallen am Behälter.}

# Disarm the Trap on the Door
{201}{}{ entschärft die Falle geschickt.}
{202}{}{ -- kann die Falle nicht entschärfen.}

# Using a key on the door.
{400}{}{Du öffnest den Behälter.}

#############################################################
#  The following lines are for when the player tries to     #
#  use items on the door which are not lockpicks.           #
#############################################################

# Player uses an item on the door
{176}{}{Du brichst das Schloss am Behälter auf.}
{177}{}{Beim Versuch, das Schloss am Behälter aufzubrechen, verrenkst du dir den Rücken und erleidest 1 Schadenspunkt.}

# The following set of lines is to be translated as:
# You strain your back while trying to bust the lock and
# take [x] points of damage.

{178}{}{Beim Versuch, das Schloss aufzubrechen, verrenkst du dir den Rücken und erleidest }
{179}{}{ Schadenspunkte.}
{180}{}{Du bist nicht stark genug, um das Schloss aufzubrechen.}

# NPC uses an item on the door
# The following lines are prepended by the NPC's name
{181}{}{ bricht das Schloss am Behälter auf.}
{182}{}{ verrenkt sich beim Versuch, das Schloss aufzubrechen, den Rücken und erleidet 1 Schadenspunkt.}

# The following line set of lines is to be translated as:
# NPC strains his back while trying to bust the lock and
# takes [x] points of damage

{183}{}{ verrenkt sich beim Versuch, das Schloss aufzubrechen, den Rücken und erleidet }
{184}{}{ Schadenspunkte.}

{185}{}{ -- ist nicht stark genug, um das Schloss aufzubrechen.}
{186}{}{ verrenkt sich beim Versuch, das Schloss aufzubrechen, den Rücken und erleidet 1 Schadenspunkt.}

# The following line set of lines is to be translated as:
# NPC strains her back while trying to bust the lock and
# takes [x] points of damage

{187}{}{ verrenkt sich beim Versuch, das Schloss aufzubrechen, den Rücken und erleidet }
{188}{}{ Schadenspunkte.}

#############################################################
#  Damage done to the door due to explosives.               #
#############################################################

{193}{}{Die Explosion hat nicht einmal einen Kratzer am Behälter hinterlassen.}

#############################################################
#  Reporting Door Status should it be used.                 #
#############################################################

{203}{}{Sieht aus, als wäre er abgeschlossen.}
{204}{}{Du bemerkst eine Falle.}

# NPC finds trap
# The following line is to be translated as:
# NPC notices a trap in the door jam.

{205}{}{ bemerkt eine Falle im Türrahmen.}

#############################################################
#  Setting traps on a door and whether the door is open or  #
#  closed to set the trap.                                  #
#############################################################

# Player tries to set a trap on an open door
{206}{}{Du kannst keine Falle aufstellen, weil sie offen ist.}

# NPC tries to set a trap on an open door
{207}{}{ kann keine Falle aufstellen, weil sie offen ist.}

# Player tries to set a trap on a closed door
{208}{}{Du stellst geschickt eine Falle auf.}
{209}{}{Du kannst keine Falle aufstellen.}

# NPC tries to set a trap on a closed door
{210}{}{ stellt geschickt eine Falle am Behälter auf.}
{211}{}{ -- kann keine Falle am Behälter aufstellen.}
