{100}{}{Du siehst einen Kunden.}
{101}{}{Du siehst Madison.}

#Î'ëàäêà
{105}{}{Ave, Göttin!}
{106}{}{Komm mit mir, Arschloch.}
{107}{}{Bleib hier, Schwachkopf.}

#######################################################
#
#           Äèàëîã - íàëè÷èå â êîìàíäå
#
#######################################################

#======================================================
# Êîãäà ñ'îè' è æäå' ãåğîèíş
#======================================================

{110}{}{Oh! Mein Baby ist zu mir zurückgekommen! Ich wusste es, du brauchst mich! Wohin gehen wir diesmal? Vielleicht zu mir nach Hause?}
{111}{}{Komm schon, ich brauche dich.}
{112}{}{Schon gut.}

#======================================================
# Êîãäà õîäè' çà ãåğîèíåé - ïåğâàÿ äèàëîãîâàÿ âå'êà
#======================================================

{120}{}{Was willst du, Baby?}
{121}{}{Alles, was du willst, Schöne!}
{122}{}{Na, was kann so ein alter Furz für ein kleines Mädchen wie dich tun?}
{123}{}{Hey, du weißt, wen du rufen musst, wenn du mich brauchst! Ja, ich bin dein Mann.}
{124}{}{Ich kann es kaum erwarten, bis du es sagst.}
{125}{}{Komm schon! Entscheide dich! Sag mir, dass du *das* willst!}
{126}{}{Oh, tut mir leid wegen der Flecken auf der Hose ... Ich werde versuchen, sie besser zu verbergen.}
{127}{}{Was? Soll ich fester?}
{128}{}{[Sieht dich an und zieht die Hände aus den Taschen] Oh, äh ... Alles in Ordnung. Ehrlich.}
{129}{}{[Summt etwas über den letzten Kuss] ... Oh, tut mir leid, ich war schon wieder abgelenkt.}

{130}{}{Lass uns reden.}
{131}{}{Lass uns den Abstand zwischen uns ändern.}
{132}{}{Steck deine Waffe weg.}
{133}{}{Zieh deine Rüstung aus.}
{134}{}{Bleib hier und warte auf mich.}
{135}{}{Erzähl mir von deinen Waffenfertigkeiten.}
{136}{}{}
{137}{}{}

{138}{}{Was immer du willst, Baby!}
{139}{}{Großartig.}

#Óäåğæàíèå äèñ'àíöèè:
{140}{}{Oh, mein Baby will mir näher sein! Darauf habe ich schon gewartet ...}
{141}{}{Bleib mir so weit wie möglich vom Leib, du Irrer.}
{142}{}{Bleib auf mittlerer Distanz.}
{143}{}{Bleib in meiner Nähe, Süße.}
{144}{}{Ich denke, dieser Abstand reicht.}

{145}{}{Ah! Okay, okay ... Ich halte mich fern. Aber mal sehen, wer länger durchhält!}
{146}{}{Kein guter Anfang für unsere Beziehung, Baby. Glaub mir, ich kenne mich damit aus.}
{147}{}{Au! Baby, du machst mich wahnsinnig! Ich werde ein menschlicher Schutzschild für deinen knackigen Hintern sein!}

{148}{}{Oh! Baby, ich kann sogar einen Striptease tanzen! Sag einfach ein Wort!}
{149}{}{Äh ... Heute nicht, Playboy. Die Rüstung reicht.}

#Îñâîáîæäåíèå ïåğñîíàæà:
{150}{}{Oh nein! [fasst sich an den Kopf] Ist dieser Tag etwa gekommen!?}
{151}{}{Ja, du Hund, ich mache Schluss mit dir. Für immer.}
{152}{}{Beruhige dich, warte einfach auf mich, ich bin gleich zurück.}
{153}{}{Na gut, du kannst bleiben. Ich ertrage deine arrogante Visage noch ein bisschen länger.}

{154}{}{Puh! [packt sich trotzig ans Herz] Oh! Wie erleichtert mein Herz ist!}
{155}{}{Ach, na ja.}
{156}{}{Na gut! Also!!! Der alte Hund muss wohl warten ... Wie immer. Äh ... Aber du kommst doch wieder, oder? Du lässt deinen treuen Diener doch nicht hier zurück, oder?}
{157}{}{Warte einfach ab.}
{158}{}{NEIN! NEIIIN!!! Wie könnte ich nur! Wie könnte ich mein Kätzchen ohne Aufmerksamkeit und Fürsorge zurücklassen! Dafür werde ich bestraft! Ich komme in die Hölle! Gib mir nur noch eine Chance! Bitte! Ich gehöre ganz dir!}
{159}{}{Warte einfach, du Trottel. Ich komme wieder.}
{160}{}{Ja! JA, Liebling, ich brauche dich nicht. Geh weg und komm nicht wieder!}
{161}{}{Oh, diese Worte zerreißen mich in Stücke! Was für ein Schmerz! Mmm ... WAS für ein SCHMERZ!!! [quiekt] Ich halte es NICHT aus! Ich bringe mich um!}
{162}{}{Was kümmert's mich ...}
{163}{}{[Atmet schwer, greift sich an die Brust] Was bin ich doch für ein Idiot! Na ja, ich warte ... Ich hoffe, du kommst wieder ... Ich glaube, das wird geschehen! Glaub mir, ich werde brav sein! Ehrlich!}
{164}{}{Warte, so lange du willst.}

{165}{}{Du würdest alles meistern. Aber außer einer Schrotflinte und einem Revolver musste ich noch nie etwas anderes benutzen.}
{166}{}{Okay.}


#######################################################
#
#                  Ğàññïğîñû
#
#######################################################

#Î'âå'û íàïàğíèêà íà ïğîñüáó ïîáîë'à'ü:

{200}{}{Schon wieder? Willst du nicht gleich zum Vergnügen kommen?}
{201}{}{Ich habe in einem Laden diese Gummidinger gesehen ... Falls du das meinst.}
{202}{}{Oh, ja, mal sehen, wo wir uns niederlassen ...}
{203}{}{Ich schlage Position 26 vor.}
{204}{}{Oh, es juckt, ja? [lächelt]}
{205}{}{Na, natürlich! Werd mal ein bisschen erwachsen, ja?}
{206}{}{Ich spüre, dass das ersehnte Erlebnis gleich kommt!}
{207}{}{Ich habe so lange gewartet! Sag mir, wie sollen wir es machen?}
{208}{}{Wie du willst - mit einem Bier oder auf nüchternen Magen?}
{209}{}{Davon rede ich nicht, du Dummkopf. Reg dich nicht zu früh auf.}

#Ñïèñîê âîïğîñîâ:

{210}{}{Verdammt, wie immer ...}
{211}{}{Was weißt du über diesen Ort?}
{212}{}{Sieh dir meinen Rucksack an. Kommt dir etwas bekannt vor?}
{213}{}{Wer kann in Reno Gift herstellen?}
{214}{}{Weißt du, wer Oliver ist?}
{215}{}{}
{216}{}{}
{217}{}{}
{218}{}{}
{219}{}{Okay, genug geredet.}
{220}{}{Noch eine Frage.}
{221}{}{Für heute reicht's.}

{230}{}{Oh, du bist wirklich gefährlich, Baby! Ich beneide denjenigen nicht, den du dir zum Töten ausgesucht hast. Na gut, ich weiß, wo das geht. Striker, er wohnt im Bowlingstadion. Ein örtlicher Gangster und Drogenhersteller. Sehr zu empfehlen.}
{231}{}{Was noch?}

#Ïğî ãîğîäà è êàğ'û:
{300}{}{Ödland. Einfach nur Ödland.}
{301}{}{Ödland. Einfach nur Ödland.}
{302}{}{Ödland. Einfach nur Ödland.}
{303}{}{Hä? Wo bin ich denn? Oh, tut mir leid, ich hab zu viele Pillen genommen und halluziniere jetzt von irgendeiner wunderschönen Stadt ... Oh, was für eine schöne Halluzination!}
{304}{}{Hä? Wo bin ich denn? Oh, tut mir leid, ich hab zu viele Pillen genommen und halluziniere jetzt von irgendeiner wunderschönen Stadt ... Oh, was für eine schöne Halluzination!}
{305}{}{Wüste und Eisenbahn. Was willst du sonst noch wissen, mein Neugieriger? Oh, da ist so eine Hütte, bestimmt gibt es dort ein Bett ...}
{306}{}{Ich war noch nie hier, aber ich habe davon gehört. Angeblich haben die Soldaten hier schon lange keinen Frauenkörper mehr gesehen ... Ups, das hätte ich nicht sagen sollen.}
{307}{}{Ein dreckiger Bunker. Ja, ich mag exotische Orte, um mir oral Lust bereiten zu lassen, aber nicht so einen dreckigen Ort.}
{308}{}{Ruinen, Ruinen, überall Ruinen. Hey, sieht aus, als wären wir nicht allein!}
{309}{}{MAP_KLAMATH_1}
{310}{}{MAP_KLAMATH_MALL}
{311}{}{MAP_KLAMATH_RATCAVES}
{312}{}{Baby, das ist der perfekte Ort für Liebhaber von brahmin-Ärschen. Aber ich bevorzuge die andere Sorte Ärsche.}
{313}{}{MAP_KLAMATH_TRAPCAVES}
{314}{}{MAP_KLAMATH_GRAZE}
{315}{}{MAP_VAULTCITY_COURTYARD}
{316}{}{MAP_VAULTCITY_DOWNTOWN}
{317}{}{MAP_VAULTCITY_COUNCIL}
{318}{}{Wilde? Baby, steht dir der Sinn nach Exotik? Ah, das kann ich verstehen – pure Natur und keine Drogen. Ich schätze, die treiben es lange und ausgiebig.}
{319}{}{[Sie sieht sich um] Ich erinnere mich, genau wie in den guten alten Tagen, bevor ich in New Reno eingebrochen bin. Los, verschwinden wir – die hiesigen Grobiane sind selbst für so ein gefährliches Mädchen kaum zu überleben, glaub mir.}
{320}{}{MAP_SHAIEM_RAIDERS_BASA}
{321}{}{Dunkel, feucht, ruhig, kühl ... Ein toller Ort, um auf der Matratze zu tanzen.}
{322}{}{MAP_MODOC_DOWNTHESHITTER}
{323}{}{MAP_HOWTHORNE_POLIGON}
{324}{}{MAP_BATTL_OWL}
{325}{}{MAP_BATTL_BAIKERS}
{326}{}{MAP_GHOST_LAKE}
{327}{}{MAP_ZONA51_Toplivo}
{328}{}{MAP_ZONA51_KASARMS}
{329}{}{MAP_ZONA51_ANGAR}
{330}{}{MAP_VAULT_8_DESTROYVAULT}
{331}{}{MAP_GECKO_SETTLEMENT}
{332}{}{MAP_GECKO_POWER_PLANT}
{333}{}{MAP_GECKO_JUNKYARD}
{334}{}{MAP_GECKO_ACCESS_TUNNELS}
{335}{}{MAP_VAULT_8_CITY_DESTROY}
{336}{}{MAP_VAULT_15}
{337}{}{MAP_THE_SQUAT_A}
{338}{}{MAP_THE_SQUAT_B}
{339}{}{MAP_VAULT_15_EAST_ENTRANCE}
{340}{}{MAP_VAULT_13}
{341}{}{MAP_VAULT_13_ENTRANCE}
{342}{}{MAP_VEGAS_STRIP}
{343}{}{MAP_VEGAS_HARD_ROCK}
{344}{}{MAP_VEGAS_SLAVERTOWN}
{345}{}{MAP_VEGAS_GHOULTOWN}
{346}{}{MAP_VEGAS_SIGN}
{347}{}{MAP_VEGAS_DAMBA}
{348}{}{MAP_KLAMATH_CANYON}
{349}{}{MAP_HOWTHORNE_DEPOTS}
{350}{}{MAP_HOWTHORNE_TRAIN_DEPO}
{351}{}{Ich weiß nicht, was wir hier machen, aber ich würde es lieber im Hotel "Silver" in Zimmer Nummer sechs tun.}
{352}{}{MAP_DEN_SLAVE_RUN}
{353}{}{MAP_CAR_DESERT}
{354}{}{MAP_RENO_SILVER}
{355}{}{MAP_RENO_ELDORADO}
{356}{}{MAP_RENO_BILLRD}
{357}{}{MAP_RENO_TRAINDEPO}
{358}{}{MAP_RENO_OLIVER}
{359}{}{MAP_PEPGAZ}
{360}{}{MAP_VEGAS_STABLES}
{361}{}{Oh, Baby! Baby! Jetzt gehe ich hier nicht mehr weg, nicht mal für irgendjemandes Arsch. Hey, Zwerg, fünf Mäuse für die da aus Wendover! Fünf Mäuse!!!}
{362}{}{MAP_REDDING_WANAMINGO_ENT}
{363}{}{MAP_REDDING_WANAMINGO_12}
{364}{}{MAP_REDDING_WANAMINGO_12}
{365}{}{MAP_REDDING_MINE_ENT}
{366}{}{MAP_REDDING_DTOWN_TUNNEL}
{367}{}{MAP_REDDING_MINE_TUNNEL}
{368}{}{Ruinen. Einfach nur Ruinen.}
{369}{}{Ödland. Einfach nur Ödland.}
{370}{}{Ödland. Einfach nur Ödland.}
{371}{}{Ödland. Einfach nur Ödland.}
{372}{}{Ödland. Einfach nur Ödland.}
{373}{}{Ödland. Einfach nur Ödland.}
{374}{}{Ödland. Einfach nur Ödland.}
{375}{}{Ödland. Einfach nur Ödland.}
{376}{}{Ödland. Einfach nur Ödland.}
{377}{}{Ödland. Einfach nur Ödland.}
{378}{}{MAP_BROKEN_HILLS1}
{379}{}{MAP_BROKEN_HILLS2}
{380}{}{Ödland. Einfach nur Ödland.}
{381}{}{Ödland. Einfach nur Ödland.}
{382}{}{Ödland. Einfach nur Ödland.}
{383}{}{Ödland. Einfach nur Ödland.}
{384}{}{Ödland. Einfach nur Ödland.}
{385}{}{Ödland. Einfach nur Ödland.}
{386}{}{Ödland. Einfach nur Ödland.}
{387}{}{Ödland. Einfach nur Ödland.}
{388}{}{Ödland. Einfach nur Ödland.}
{389}{}{Ödland. Einfach nur Ödland.}
{390}{}{Ödland. Einfach nur Ödland.}
{391}{}{Ödland. Einfach nur Ödland.}
{392}{}{MAP_RAIDERS_CAMP1}
{393}{}{MAP_RAIDERS_CAMP2}
{394}{}{Ödland. Einfach nur Ödland.}
{395}{}{Ödland. Einfach nur Ödland.}
{396}{}{MAP_SPECIAL_RND_WHALE}
{397}{}{Diese Öffnung kommt mir bekannt vor. Ich habe sie schon mal irgendwo gesehen.}
{398}{}{Pass auf, wo du hintrittst, Baby. So eine Schönheit wie dich möchte ich nicht Stück für Stück aufsammeln müssen.}
{399}{}{Ödland. Einfach nur Ödland. Irgendwie hervorgehoben.}
{400}{}{Ödland. Einfach nur Ödland. Und ein schönes Gebäude. Wahrscheinlich gibt es da drin ein elegantes Bett und ein Telefon, um eine Firmen-Stripshow zu bestellen.}
{401}{}{MAP_SPECIAL_RND_BRIDGE}
{402}{}{Oh, ist das eine Art Café? Lust, reinzugehen und ein bisschen Spaß zu haben?}
{403}{}{MAP_SPECIAL_RND_HOLY1}
{404}{}{MAP_SPECIAL_RND_HOLY2}
{405}{}{MAP_SPECIAL_RND_GUARDIAN}
{406}{}{Ödland. Einfach nur Ödland.}
{407}{}{MAP_SPECIAL_RND_PARIAH}
{408}{}{MAP_SPECIAL_RND_MAD_COW}
{409}{}{MAP_NAVARRO_ENTRANCE}
{410}{}{Ödland. Einfach nur Ödland.}
{411}{}{Ödland. Einfach nur Ödland.}
{412}{}{Ödland. Einfach nur Ödland.}
{413}{}{Ödland. Einfach nur Ödland.}
{414}{}{Ödland. Einfach nur Ödland.}
{415}{}{Ödland. Einfach nur Ödland.}
{416}{}{Ödland. Einfach nur Ödland.}
{417}{}{Ödland. Einfach nur Ödland.}
{418}{}{Ödland. Einfach nur Ödland.}
{419}{}{Ödland. Einfach nur Ödland.}
{420}{}{Ödland. Einfach nur Ödland.}
{421}{}{Ödland. Einfach nur Ödland.}
{422}{}{Ödland. Einfach nur Ödland.}
{423}{}{Ödland. Einfach nur Ödland.}
{424}{}{Ödland. Einfach nur Ödland.}
{425}{}{Ruinen. Einfach nur Ruinen.}
{426}{}{Ödland. Einfach nur Ödland.}
{427}{}{Ruinen. Einfach nur Ruinen.}
{428}{}{Ein herrlicher Ort. Frische Betten, sauberes Wasser und jede Menge Gratis-Donuts aus dem Automaten. Wie wär's, wenn wir anhalten und uns in den Doppelbetten entspannen?}
{429}{}{Berge und kalter Wind. Hier gibt es für uns nichts zu tun.}
{430}{}{Warum ist es so dunkel? Wie sollen wir einander finden ... Ich meine, ich wollte sagen: übereinander herfallen.}
{431}{}{Ödland. Einfach nur Ödland. Irgendwo nicht weit von Salt Lake. Ich kann es kaum erwarten, in die weichen Betten im „Sechste Kugel“ zu kommen ...}
{432}{}{Baby, du weißt besser, was zu tun ist. Ehrlich. Ich folge dir einfach.}
{433}{}{Schon gut. Ein paar schmutzige Halunken aus Reno sind hierhergezogen und bewundern abends brahmin Arsch.}
{434}{}{MAP_ENCLAVE_TRAP_ROOM}
{435}{}{MAP_SALT_TRAIN}
{436}{}{So ein beschissenes Wohnviertel, wunderschön. Können wir keinen etwas solideren Schlafplatz finden?}
{437}{}{Salt Lake City, die beschissenste Stadt im Ödland, aber ein Bett für uns wird sich dort bestimmt finden.}
{438}{}{Puh! Während du hier bist und all deine großen Aufgaben erledigst, stehe ich hier und bewundere deinen Körper.}
{439}{}{So eine Kirche ... Hey, wie wär's mit einer Hochzeit?}
{440}{}{Die Slums. Hier ist es so wild und aufregend ...}
{441}{}{Ruinen. Einfach nur Ruinen.}
{442}{}{Ruinen. Einfach nur Ruinen.}
{443}{}{Ruinen. Einfach nur Ruinen.}
{444}{}{Ruinen. Einfach nur Ruinen.}
{445}{}{Ruinen. Einfach nur Ruinen.}
{446}{}{Ruinen. Einfach nur Ruinen.}
{447}{}{Ruinen. Einfach nur Ruinen.}
{448}{}{Großartig. Ich hätte nie gedacht, dass ich diesen Hersteller der Universalpisse je zu Gesicht bekommen würde, der den ganzen Handel im Ödland in den Schatten gestellt hat.}
{449}{}{Ödland. Einfach nur Ödland.}

#######################################################
#
#                  Ïëàâàşùèå ôğàçû
#
#######################################################

#======================================================
# Ïëàâàşùèå ôğàçû ïğè ïîïû'êå 'îëêíó'ü
#======================================================

{1000}{}{Hier?}
{1001}{}{Besser so, Kätzchen?}
{1002}{}{Und hier?}
{1003}{}{Ja, Kätzchen.}
{1004}{}{Was?}
{1005}{}{Wohin gehen wir?}
{1006}{}{Gehen wir, Schatz?}
{1007}{}{Ich gehe, wohin du willst.}
{1008}{}{Tut mir leid, Schatz.}
{1009}{}{Besser?}
{1010}{}{Äh ...}
{1011}{}{Na, wie sehe ich in diesem Licht aus?}
{1012}{}{Bringst du mich auf die Bühne?}
{1013}{}{Ich gehe einfach hierhin.}

#À'àêà íà ãåğîÿ
{1020}{}{Ich glaube, ich habe genug!}

#======================================================
# Òàéìåğíûå ğıíäîìíûå ôğàçû
#======================================================

#Êîãäà íå çäîğîâ:
{1100}{}{Oh Göttin, hab Erbarmen! Mir ist nicht gut!}
{1101}{}{Ich brauche einen Arzt, Baby.}
{1102}{}{Oh Mann. Au, das tat weh.}
{1103}{}{Au!}
{1104}{}{Oh ...}
{1105}{}{Verdammt ...}
{1106}{}{Doktor?}
{1107}{}{Ich halte durch ... gerade so ...}
{1108}{}{Bald bin ich tot ...}

#Êîãäà ÃÃ îñ'àâèëà íàïàğíèêà î'äûõà'ü:
{1200}{}{Oh là là ...}
{1201}{}{Sehr gut}
{1202}{}{Ich warte auf meine Schöne ...}
{1203}{}{Ich warte auf meine Göttin.}
{1204}{}{Ich warte nur auf sie.}
{1205}{}{Sie geht mir ganz bestimmt nicht fremd ...}
{1206}{}{Ach, diese Frauensachen ...}
{1207}{}{Frauen sind eben so – man muss immer auf sie warten.}
{1208}{}{Sie ist schon wieder einkaufen ...}
{1209}{}{Das Zeug soll ich auch noch tragen?}
{1210}{}{Hey, ich bin hier! Und mir ist langweilig!}
{1211}{}{Die sind immer so, man muss immer auf sie warten.}
{1212}{}{Äh ... Na ja, wenigstens habe ich Cola. Ich bin völlig erschöpft.}
{1213}{}{Ich sollte die Finger von Frauen lassen ... Sie bringen nur Ärger.}
{1214}{}{Da hätte ich mir lieber einen Kampf im Ring in »Eldorado« angesehen.}
{1215}{}{Und was ist jetzt? Gibt's keinen Sex?}

#======================================================
# Èñïîëüçîâàíèå ïğåäìå'îâ íà íàïàğíèêå
#======================================================

#Ñ'èìóëÿ'îğ èëè âîäà
{1300}{}{Puh! Mein Raketenantrieb ist wieder aufgetankt und einsatzbereit!}
{1301}{}{Jetzt bin ich voller Energie für eine Nummer auf der Matratze.}
{1302}{}{Ganz genau!}
{1303}{}{Toll, jetzt stehe ich in der Schlange.}
{1304}{}{Wurde auch Zeit.}
{1305}{}{Und ich dachte wirklich, jetzt wäre es aus mit mir.}
{1306}{}{Ah, tut das gut!}

#Äğóãèå ìåäèêàìåí'û
{1310}{}{Du hast recht – ich will mich nicht übergeben.}
{1311}{}{Warum stinkt dein Atem so nach Rauch? Verdammt ...}
{1312}{}{Oh, die berühmte »Furious«! Seit hundert Jahren nicht mehr gesehen.}
{1313}{}{Nicht so schnell, Liebste. Wenn wir sterben, dann gemeinsam!}
{1314}{}{Oh, stimmt, Baby liebt mich ja viel zu sehr.}
{1315}{}{Na ja, ich bin kein großer Fan von Süßigkeiten, aber man sagt, damit ...}
{1316}{}{Zu einem Glas bloody Mary sage ich niemals Nein!}
{1317}{}{Das Zeug esse ich einfach nicht! Na gut, für dich.}
{1318}{}{Was ist das für ein Scheiß? Na ja, wenn wir nichts anderes haben ...}
{1319}{}{Genau wie damals, als man mich in der ... festhielt. Äh, egal.}
{1320}{}{Wie früher. Ich erinnere mich an Doc Gray und seine Experimente an ... Na ja, vergessen wir's.}

#Èíûå ïğåäìå'û
{1330}{}{Äh, danke, Süße.}
{1331}{}{Danke.}
{1332}{}{Baby, weißt du, was du da tust?}
{1333}{}{Können wir nicht einfach schla... uns ausruhen?}
{1334}{}{Vielleicht schlafen wir einfach miteinander?}
{1335}{}{Was, ich hab am meisten davon abbekommen?}
{1336}{}{Nicht gerade hilfreich.}
{1337}{}{Na gut, wenn du darauf bestehst, meine Göttin.}
{1338}{}{Wunderschön, mein Kopf explodiert doch nicht, oder?}
{1339}{}{Sieht aus, als würde ich mich langsam daran gewöhnen.}
{1340}{}{Mir ist ein bisschen komisch.}
{1341}{}{Äh, sicher, dass du nicht willst? Warum probierst du es nicht?}
{1342}{}{Klar, Baby. Ich nehme etwas davon.}
{1343}{}{Danke, Kätzchen.}
{1344}{}{Nicht schlecht.}

#Î'âå'û ïğî èíâåí'àğü:
{1998}{}{[Betrachtet den Gegenstand}
{1999}{}{] }
{2000}{}{Nichts Interessantes. Solche Gummidinger hab ich schon in dem Laden in der Nähe von „Silver legacy“ gesehen ...}

{2053}{}{Eine echte Rarität. Man sagt, sie heilt nicht nur, sondern stärkt auch das Immunsystem.}
{2097}{}{Hm, ja, du stellst meine Beobachtungsgabe auf die Probe, Baby! Natürlich sehe ich, dass man das irgendwo platzieren muss.}
{2120}{}{Mühelose Kraft und Brutalität. Echtes Gold unter all dem Scheiß, den man im Ödland finden kann. Der einzige Nachteil ist der schwere Lauf. Es gibt allerdings Techniker, die ihn reparieren könnten.}
{2164}{}{Kommt mir bekannt vor! Ich erkenne Strikers Arbeit. Allerdings scheitern viele mit dem Zeug im Ring. Du willst es doch nicht ausprobieren, oder?}
{2222}{}{Es leuchtet? Baby, solche Dinger sind allein wegen dem wertvoll, was sie sind.}
{2237}{}{Zeitungen? Na, du willst mich doch nicht zwingen, das zu lesen, oder? Na gut ... Werbung für „Pretty & Glamour“. Davon hab ich schon gehört. Ja, genau, der Verkaufsautomat in „Silver Legacy“.}
{2239}{}{Ein bisschen schwach. Ehrlich.}
{2255}{}{Ich kann nur sagen: Nur ein nerdiger Botaniker kann das reparieren.}
{2278}{}{Mickey ... Genau so ein geiler Bock wie ich.}
{2281}{}{Na gut. Komm schon, Baby, ich verrate niemandem, wie viele Schlösser deinen geschickten Fingern nicht widerstehen konnten.}
{2301}{}{Das ist von der Firma „Pretty & Glamour“. Im Hotel „Silver Legacy“ gibt es einen Automaten ... Hey, Moment mal, willst du mir etwa sagen, dass ich stinke?}
{2310}{}{Das Einzige auf der Welt, das mit der Zeit nur besser wird.}
{2311}{}{Diese armen Leute in Salt Lake sind nur dank Vocas am Leben. Eine Handvoll in den Mund, und schon ist dein Strahlenproblem gelöst.}
{2324}{}{Ein teures Ding. Wenn wir den Brunnen erreichen, probier es aus.}
{2333}{}{Glaubst du, dass es im Ödland Leute gibt, die so etwas brauchen?}
{2337}{}{Eine berühmte Vorkriegsdroge, die deine geistigen Fähigkeiten verbessert. Willst du sie etwa nicht probieren? Kluge Mädchen sind wie eine Falle im dunklen Wald.}
{2388}{}{Hmm, ich erinnere mich, dass man in der Nähe von Salt Lake Geckos gesehen hat, die Säure spuckten.}
{2413}{}{Und an sie erinnere ich mich auch! Sie arbeitete in einem Stripclub. Eine echte Sexbombe, aber nach Ted Bundy war sie verschwunden. Ich wette hundert Münzen, dass sie in eine andere Stadt abgehauen ist.}
{2417}{}{Sieht aus wie ein Helm einer Powerrüstung. Ist es natürlich nicht ... Na ja, ich hab sie mal in einer Zeitschrift gesehen.}
{2430}{}{Ehh, wenn wir damit ein paar Aliens in Area 51 erschießen könnten, was?!}
{2433}{}{Wirksam! Ohne Kappe bist du schon begehrt, aber mit der Kappe bist du megabegehrt!}
{2441}{}{Hey, hier steht der Name des Besitzers drauf. Aber was soll's, oder?}
{2471}{}{Irgendein durchgeknallter Professor hat das geschrieben. Du willst doch nicht genauso werden, oder? Und in einem Arztkittel und Minirock wärst du ziemlich sexy.}
{2499}{}{Da war so ein Nerd, der dieses Gift von einem Lagerhaus aus in Reno vertickt hat. Ich hab mal ein bisschen davon genommen und wäre fast draufgegangen. Nach ein paar gebrochenen Knochen hab ich diesen Arsch nie wieder gesehen.}
{2516}{}{Die Kollektion „Pretty & Glamour“!? Oh, jetzt kannst du dich von Körpergeruch verabschieden.}
{2525}{}{Oh, das berühmte „Furious“! Ich erinnere mich. Da war ein Wissenschaftler in Reno, der ein Methamphetamin-Labor entwickelte, aber dann übernahmen die Junkies, die er selbst an das Zeug gewöhnt hatte. Ich rate dir, es nicht einmal zu probieren.}
{2551}{}{Ach, komm schon!}
{2552}{}{Hauptsache, du übertreibst es nicht.}
{2554}{}{Fühlt sich fast an wie eine gewöhnliche Münze und ist nicht davon zu unterscheiden.}
{2556}{}{Ist das eine Nachbildung eines Schwanzes? Ich meine, meiner ist zu klein? Verdammt, ich muss ihn wohl vergrößern lassen.}
{2557}{}{Das ist eine Nachbildung eines Schwanzes? Ich meine, meiner ist zu klein? Verdammt, ich muss ihn wohl vergrößern lassen.}
{2558}{}{D-Das ist nicht m-meiner! Ehrlich! Ja, ich würde den Mann umbringen lassen, wenn ich ihn sähe ... Vielleicht ...}
{2560}{}{Seltenes Stück. Aber du willst das doch nicht mit dir herumtragen? Im Vault-Anzug siehst du heißer aus!}
{2561}{}{Seltenes Stück. Aber du willst das doch nicht mit dir herumtragen? Im Vault-Anzug siehst du heißer aus!}
{2562}{}{Schon wieder Schrott aus „Pretty & Glamour“ ...}
{2563}{}{Schon wieder Schrott aus „Pretty & Glamour“ ...}
{2564}{}{Schon wieder Schrott aus „Pretty & Glamour“ ...}
{2565}{}{Das habe ich in Kalifornien gesehen. Das ist lange her.}
{2566}{}{Schon wieder Schrott aus „Pretty & Glamour“ ...}
{2573}{}{Du stehst auf extremen Lustgewinn!}
{2577}{}{Schon wieder Schrott aus „Pretty & Glamour“ ...}
{2593}{}{Äh, sieh mal, dieser Hal Wallace muss ein vernünftiger Mann sein. Für ihn würde ich arbeiten. Aber ich kann es kaum schaffen.}
{2595}{}{Äh, sieh mal, dieser Hal Wallace muss ein vernünftiger Mann sein. Für ihn würde ich arbeiten. Aber ich kann es kaum schaffen.}
{2596}{}{Stehst du jetzt auf korrupte mexikanische Bullen? Ganz schön extrem!}
{2597}{}{Dieser Deputy hat wohl keine Zeit zwischen den Beinen bekommen.}
{2626}{}{Glück gehabt! Gute Waffen und seltene Munition. Unter anderen Umständen hättest du das nicht finden können.}
{2627}{}{Glück gehabt! Eine großartige Waffe und seltene Munition. Unter anderen Umständen hättest du das nicht finden können.}
{2628}{}{Glück gehabt! Eine fantastische Waffe und seltene Munition. Unter anderen Umständen hättest du das nicht finden können.}