{100}{}{Du siehst einen Banditen.}
{101}{}{Du siehst einen Marodeur.}
{102}{}{Du siehst einen Räuber.}
{103}{}{Du siehst einen Sträfling.}
{104}{}{Du siehst einen Schurken.}
{105}{}{Du siehst einen entflohenen Gefangenen in Ausrüstung, die er der Wache gestohlen hat.}

{200}{}{Ergib dich!}
{201}{}{Geld oder Leben.}
{202}{}{Das ist ein Überfall.}
{203}{}{Gib mir all deine Wertsachen.}
{204}{}{Ich krieg dich!}
{205}{}{Hände hoch.}
{206}{}{Hände hoch!}
{207}{}{Keine Panik – es ist in einer Minute vorbei.}
{208}{}{Zeig mir deine Hände.}
{209}{}{Gebt mir Deckung, Jungs.}

{210}{}{Mach's dir nicht unnötig schwer.}
{211}{}{Rück die Beute raus.}
{212}{}{Schnappt sie euch, Jungs.}
{213}{}{Tötet die da.}
{214}{}{Ich verspreche dir einen schnellen Tod.}
{215}{}{Hände hoch!}
{216}{}{Nicht bewegen.}
