{100}{}{Du siehst Bobby.}
{101}{}{Du siehst deinen alten Kumpel Bobby.}

{110}{}{Hallo, Fremder! Nur zu. Alle haben es immer eilig, rennen irgendwohin ... Bist du auch so einer? Warum bleibst du nicht auf einen Plausch mit einem alten Mann? Die Zeit vergeht langsam und erzählt interessante Geschichten, aber bist du bereit dafür?}
{111}{}{Nur der Rauch steigt unwiderruflich zum Himmel auf, doch ein Mensch kann seinen Weg frei in jede Richtung wählen ... Möchtest du eine Geschichte darüber hören?}
{112}{}{Äh, okay, ich höre zu.}
{113}{}{Und du scheinst ein Experte für Ödland-Kraut zu sein? Das wird lustig.}
{114}{}{Wow, ganz ruhig! Ich bin nur hier, um mich umzusehen. Überanstreng dich nicht gleich.}

{115}{}{Wie auch immer, da waren zwei Brüder. Sie hießen ... Na ja, nennen wir sie Dick und Tom. Einer von ihnen, Tom, half immer seinen Nächsten ... oder auch Fernstehenden. Im Herzen war er ein bescheidener, einzigartiger Mann. Und sein Bruder konnte einfach nicht widerstehen, andere auszunutzen. Er verklagte seine eigene Mutter auf Geld, das ihr gehörte.}
{116}{}{[Weiter]}
{117}{}{Und dann kam der Tag, an dem Gott, wie viele glaubten, jedem gab, was er verdiente. Tommy, der eine Horde Clowns zu ihrem Zirkus gefahren hatte, wurde von denselben Clowns gefressen, ganz ohne Salz und Pfeffer ... Aber auch Dick starb. Im Schlaf. Nachdem er sich zum Pharma-Lagerhaus hochgearbeitet und durch geschickte Spekulationen ein Vermögen angehäuft hatte. Das ist die Geschichte.}
{118}{}{Sag mir, dass das nur erfunden ist. Ich muss das wirklich von dir hören. Hey, ich rede mit dir!}
{119}{}{Ausgezeichnet! Ich war auf eine schnippische Predigt gefasst, und wie gut du das noch gedreht hast!}
{120}{}{Du bist so bekifft, dass ich buchstäblich nichts zu sagen habe. Ich komme wieder, wenn du normal bist ... Falls das überhaupt möglich ist.}

{121}{}{Mir ist noch eine Geschichte eingefallen: über einen alten Schriftsteller aus Denver. Was für ein überaus positiver Mensch er war – er versuchte immer, in jeder Situation etwas Positives zu finden. Nachdem er bei einer Begegnung mit einem bekifften Colafahrer sein Bein verloren hatte, sagte er: „Jetzt kann ich mein Buch zu Ende schreiben, ohne mich von sinnlosem Herumgerenne ablenken zu lassen.“}
{122}{}{Im Vault während der Bombardierung von 2077, wo seine Verwandten sich endlos über ihr Schicksal beklagten, freute er sich, dass endlich alle zusammengekommen waren. Am Ende wurde er rausgeworfen und zum Ghul ... Und er sagte, wie toll das sei, die Strahlung sei kein Problem mehr, so viele Orte zu besuchen!}
{123}{}{Irgendwelche verrückten Sektierer haben ihn irgendwo bei Great Plains gekreuzigt – gut! Das bedeutet ... U-ugh ... Na ja, ehrlich gesagt sehe ich daran nichts Positives. Aber ihm würde schon etwas einfallen, da kannst du sicher sein. Mach dir keine Sorgen, sei glücklich.}
{124}{}{Ich hoffe, du erzählst deinen Kindern nicht solche Geschichten. Moment, du bist noch nicht fertig?}
{125}{}{Eine Geschichte ist besser als die andere! Gib mir ein Tütchen Gras!}
{126}{}{Ich bin nicht in der Stimmung, mir dein Trip-Gelaber anzuhören. Viel Glück.}

{127}{}{Also ... Loyalität ist ein gutes Wort, oder? Das dachte sich auch ein Hund, der sich durch die Verwüstung des nuklearen Holocausts zu seinem Herrchen durchschlug. Doch als der Hund ihn fand ...}
{128}{}{Halt! Lass mich raten – jemand hat jemanden gefressen.}
{129}{}{Ja, ja, erzähl weiter. Ich kann es kaum erwarten, noch mehr zu hören.}
{130}{}{Das war's, ich bin fertig. Tschüss, Geschichtenerzähler!}

{131}{}{Hm ... Ich glaube, ich sollte die Geschichte vom einsamen Wanderer aus irgendeinem Vault erzählen. Wie meinst du, sollte ich diese Geschichte beenden?}
{132}{}{Ich denke, es liegt am Wanderer, wie die Geschichte ausgeht.}
{133}{}{Was ist der Haken? Warum erzählst du mir ständig diese Geschichten? Ist das irgendeine Art Prüfung?}
{134}{}{Das ist mir verdammt egal! Ich hab dich schon satt. Ich hau ab.}
{135}{}{Der Wanderer hat irgendeinen bekifften alten Mann wegen seiner Beute umgelegt. Na, wie gefällt dir das? [Angreifen]}

{136}{}{Kein Haken, nein. Schließlich sind wir ja nicht auf der Brücke des Todes, ha-ha! Ich will dich nur ein bisschen zum Nachdenken bringen. Deine Gedanken in die richtige Richtung lenken.}
{137}{}{Gedanken sind nichts, Taten zählen. Und egal, was irgendwer sagt, ich tue, was ich für richtig halte.}
{138}{}{Bis jetzt denke ich nur daran, dir für meine verschwendete Zeit eine reinzuhauen. Verschwinde aus meinem Blickfeld, Junkie.}
{139}{}{Gut gesagt! Lass alles seinen Lauf nehmen ... Man weiß nie, was hinter der nächsten Ecke lauert, aber das ist kein Grund, Trübsal zu blasen. Keine Sorge, sei glücklich!}
{140}{}{Amen. Mach's gut, Philosoph.}
{141}{}{Was auch immer hinter der nächsten Ecke lauert, sollte lieber vor Angst davonlaufen. Bleib gesund und rauch nicht zu viel.}
{142}{}{Danke, weisester aller Weisen, dass du mir die Gelegenheit gegeben hast, mich der Quelle des Wissens anzuschließen. Na gut, ich muss los.}

#Ñëó÷àéíûå ôğàçû
{150}{}{Warum ist noch keiner auf die Idee gekommen, leere Zigaretten zu verkaufen?}
{151}{}{In dieser Einöde gibt es niemanden, mit dem man einen Joint rauchen könnte ...}
{152}{}{Das Leben ist viel einfacher, als alle denken.}
{153}{}{Man hat dir erlaubt, ganz von vorn anzufangen – wie hast du es geschafft, alles zu ruinieren?}
{154}{}{Von wegen – jede Menge Killer-Vinylplatten und kein einziger Plattenspieler.}
{155}{}{Sei glücklich, um Himmels willen!}
{156}{}{Keine Sorge!}

#Æåíñêèå ğåïëèêè
{1110}{}{Hallo, Fremder! Nur zu. Alle haben es immer eilig, rennen irgendwohin ... Bist du auch so einer? Warum bleibst du nicht auf einen Plausch mit einem alten Mann? Die Zeit vergeht langsam und erzählt interessante Geschichten, aber bist du bereit dafür?}
{1114}{}{Wow, ganz ruhig! Ich bin nur hier, um mich umzusehen. Überanstreng dich nicht gleich.}
{1119}{}{Ausgezeichnet! Ich war auf eine schnippische Predigt gefasst, und wie gut du das noch gedreht hast!}
{1129}{}{Ja, ja, erzähl weiter. Ich kann es kaum erwarten, noch mehr zu hören.}