{100}{}{Du siehst einen Ghul.}
{101}{}{Du siehst einen Einheimischen.}

#starting converstation
{110}{}{Wow, willkommen im glitzernden Vegas, Wanderer!}
{111}{}{Vegas? Das ist doch nur ein Schrottplatz, du Spinner!}
{112}{}{Vegas? Oh ja, klingt toll.}

{113}{}{Vegas ist überall, sieh dich doch nur um! Ist es nicht wunderschön?}
{114}{}{Du bist ein durchgeknallter Irrer, wunderbar. Aber das ist mir egal. Hast du Reifen für meine Räder?}
{115}{}{Oh ja. In der Tat wunderschön. Sag mal, hast du vielleicht Reifen für meine Räder?}

{116}{}{Nein.}
{117}{}{Äh ... Nein? Wirklich? Was zum Teufel sind dann diese Dinger, die hier haufenweise herumliegen?!}
{118}{}{Ha, mein lieber Freund, warum sollte jemand *gute* Reifen auf einem *Schrottplatz* entsorgen? Wenn sie noch zu gebrauchen wären, lägen sie nicht hier herum!}
{119}{}{Hmm ...}

{120}{}{Aber was ich *für* deine Räder habe, sind diese Hände hier und ein paar nette Gerätschaften dazu ... Vorausgesetzt, du hast wirklich Räder ...}
{121}{}{Wovon redest du?}
{122}{}{Nein, ich habe nur nach Reifen gesucht. Mach's gut.}
{123}{}{Du bist einfach verrückt. Was kann man schon aus Schrott machen, außer noch mehr Schrott!?}
{124}{}{Ich bin nicht verrückt, ich bin voller Ideen! Das wird oft verwechselt, also nimm's mir nicht übel. Weißt du, vielleicht bin ich der letzte gute Ingenieur auf diesem gottverlassenen Planeten!}
{125}{}{Verstehe ... Was genau bietest du an?}
{126}{}{Du hast ein Gefährt? Oh, ich sehe, du hast eins. Nun ... Es ist ziemlich primitiv, aber ich brenne trotzdem darauf, ein paar Dinge damit anzustellen. Such einfach aus der Liste aus!}
{127}{}{Du hast ein Gefährt? Oh ... Schade, dass du keins hast. Weißt du, ich habe einen ziemlichen Basteldrang!}
{128}{}{Großartig, führen wir eine Inspektion durch.}
{129}{}{Das alles interessiert mich gerade nicht. Mich interessiert dieser Chryslus Motors Katalog. Kannst du mir etwas darüber erzählen?}

{130}{}{Hm, das Auto ist nicht gerade fabrikneu, oder? Als es aus der Chryslus-Fabrik rollte, habe ich wahrscheinlich noch in die Hose gemacht. Ja, das waren noch Zeiten ... Also, was soll ich für dich tun – starke Scheinwerfer, einen Brennstoffzellenregler, vielleicht einen größeren Kofferraum?}
{131}{}{Erzähl mir was über die Scheinwerfer.}
{132}{}{Erzähl mir was über dieses Brennstoffding.}
{133}{}{Erzähl mir was über den Kofferraum.}
{134}{}{Ich brauche nichts davon.}

{135}{}{Ein paar gewaltige Halogenlampen auf der Motorhaube kommen nie aus der Mode. Nachts zu fahren ist nicht gerade angenehm, wenn es keine Straßen mehr gibt, findest du nicht auch? Ich könnte sie ohne großen Aufwand einbauen. Die Frage ist nur: Was bekomme ich dafür?}
{136}{}{Oh ja, das hätte ich gern!}
{137}{}{Nicht jetzt. Was hattest du sonst noch gesagt, was du machen kannst?}
{138}{}{Dein Auto verbraucht Unmengen an Treibstoff, und die Hälfte der Energie geht dafür drauf, das Ödland aufzuheizen, stimmt's? Oh ja, ich weiß, wie sich das anfühlt! Ich weiß auch, wie man verhindert, dass dein Auto die Batterien leersaugt wie ein Kurzschluss. Die Frage ist nur: Was bekomme ich dafür?}
{139}{}{Das ist etwas Arbeit, aber ich könnte es machen. Dein Kofferraum ist ziemlich geräumig, und du könntest etwa ein Dutzend Kämpfer samt Ausrüstung darin unterbringen. Aber manchmal reicht das immer noch nicht, stimmt's? Ein Lederverdeck bietet Platz für etwa 20% Beutestücke mehr. Aber du musst mich schon anspornen, wenn du verstehst, was ich meine.}
{140}{}{Hm! Ich musste schon lange nicht mehr lesen. An die Buchstaben würde ich mich nicht mehr erinnern, aber wenn du es mir vorliest, werde ich versuchen, etwas damit anzufangen.}
{141}{}{Prima, machen wir's so.}
{142}{}{Einfach so? Nein, nein, zuerst brauche ich eine warme Mahlzeit und muss meine Kehle befeuchten. Mit leerem Magen funktioniert mein Kopf nicht richtig.}
{143}{}{Wie auch immer.}
{144}{}{Warte dann noch ein bisschen – wir reden später darüber.}
{145}{}{Hast du es dir schon anders überlegt? Schade!}
{146}{}{Erzähl mir noch mal von den Möglichkeiten für dein Auto.}
{147}{}{Vielleicht. Aber ich gehe sowieso.}
{148}{}{Oh ja, das sollte reichen! Wärm dich an dem Fass auf, während ich den Kleinen hier fertig mache ...}

{149}{}{Sei einfach vorsichtig, ja?}
{150}{}{Heiliger Chryslus! Es funktioniert! Das kann ich nicht glauben!}
{151}{}{Was, wirklich?}
{152}{}{Fertig! Der Pick-up nutzt jetzt die Energie effizienter.}
{153}{}{Jetzt leuchtet dein Auto mit neuen Scheinwerfern den Weg aus.}
{154}{}{Dieses Verdeck wird dir gute Dienste leisten und das Fassungsvermögen deines Kofferraums um }
{155}{}{Hmm ...}
{156}{}{[-more-]}
{157}{}{20% erhöhen.}
{158}{}{Also, was willst du?}
{159}{}{Welche Snacks und Getränke hast du?}
{160}{}{[In deinem Rucksack nach Alkohol suchen]}
{161}{}{[In deinem Rucksack nach Essen suchen]}
{162}{}{So was habe ich nicht. Ich besorge etwas.}
{163}{}{Schon gut. Was hast du über mein Auto gesagt?}
{164}{}{Du hast bereits so viel gegessen, wie ein deathclaw in einer Woche verdrücken könnte. Wage es ja nicht, mich noch mal nach Essen zu fragen!}
{165}{}{Hey, ganz ruhig, Kumpel! Vielleicht habe ich ein bisschen übertrieben. Kannst du es mir wirklich verübeln? Ach, sieh mich nicht so an.}
{166}{}{Halt dein Maul und mach dich an die Arbeit.}
{167}{}{Artikel über Fahrzeuge vom Typ "Chryslus Motors" erwiesen sich als ziemlich nützlich. Du hast ein paar Tipps bekommen, wie du die Geschwindigkeit und die maximale Traglast deines Autos erhöhen kannst.}
{168}{}{Sonst noch was?}
{169}{}{Vergiss das Essen. Lass uns über mein Auto reden.}
{170}{}{Komm damit klar. Tschüss.}

{171}{}{[Bier geben]}
{172}{}{[Alkohol geben]}
{173}{}{[Rot Gut geben]}
{174}{}{["Bloody Mary" geben]}
{175}{}{[Er wartet gespannt.]}

{176}{}{[Sandwich geben]}
{177}{}{[Pizza geben]}
{178}{}{[Trockenfleisch geben]}
{179}{}{[Leguanhappen geben]}
{180}{}{[Obst geben]}

{181}{}{Oh ja! Vor der Arbeit eine Kleinigkeit zu essen, ist immer gut. Auch wenn's nicht viel ist, oder?}
{182}{}{Moment, du meinst, es war dir nicht genug?}
{183}{}{Oh ja! Etwas Treibstoff im System – genau das, was ein Mechaniker braucht, oder? Na ja, zumindest für den Anfang.}
{184}{}{Verbrennst du bei so viel „Treibstoff“ nicht?}
{185}{}{Du bist immer noch nicht voll?!}

{186}{}{Oh ja, das war eine höllische Fahrt.}
{187}{}{Darauf kannst du wetten ...}

{190}{}{Oh ja ...}
{191}{}{Ich sehe, deine Scheinwerfer leuchten wie die Sonne aus deinem Arsch, hah!}
{192}{}{Du brauchst keinen neuen Regler – der, den du hast, sollte noch viele Meilen reichen.}
{193}{}{Na ja, offenbar brauchst du keinen besseren Kofferraum. Wie schade.}
{194}{}{Also, was willst du?}

#Female dialogue (by Rekrut)
{1110}{}{Whoa, willkommen im funkelnden Vegas, Schätzchen!}
{1145}{}{Hast du es dir inzwischen anders überlegt, Liebling? Tja, Pech gehabt!}
{1164}{}{Du hast bereits so viel gegessen, wie ein deathclaw in einer Woche verdrücken könnte. Wage es ja nicht, mich noch mal nach Essen zu fragen!}
{1165}{}{Hey, ganz ruhig, Liebling! Vielleicht bin ich ein bisschen zu weit gegangen. Kannst du es mir wirklich verübeln? Ach, sieh mich nicht so an.}
