{100}{}{Du siehst einen kleinen Jungen.}
{101}{}{Du siehst ein kleines Mädchen.}

{200}{}{Sind wir angekommen?}
{201}{}{Ich will schlafen.}
{202}{}{Trägst du mich?}
{203}{}{Meine Mutter verbietet mir, mit Fremden zu reden.}
{204}{}{Mama und Papa sind weg.}
{205}{}{Siehst du meinen glänzenden Stein?}
{206}{}{Spiel mit mir!}
{207}{}{La-la-la, la-la-la. Ich kann dich nicht hören.}
{208}{}{Warum können wir jetzt nicht spielen?}
{209}{}{Willst du spielen?}
