{100}{}{Der Anführer des Coyote-Stammes.}
{101}{}{Du siehst eine verdammt attraktive Frau, die genauso unhöflich wie schön ist.}

{110}{}{Du wirst auf dem Opferfeuer brennen!}
{111}{}{Ich werde dein Herz essen, um stärker zu werden!}
{112}{}{Angriff, meine Kinder!}
{113}{}{Töten! Töten!}
{114}{}{Meine hungrigen Kinder, nehmt euch die leckersten Stücke!}
{115}{}{Das Fleisch von Fremden ist so köstlich ...}
{116}{}{Ich mag dich. Besonders dein Roastbeef.}
{117}{}{Na los, lauf! Damit machst du meine Kinder nur wütend!}
{118}{}{Niemand wird verschont, wenn diese Beute entkommt!}
{119}{}{Ein herrliches Abendessen heute Abend, meine Kinder! Freut euch!}