{100}{}{Du siehst John.}
{101}{}{Du siehst einen athletischen Mann. Das einzige Kleidungsstück, das er trägt, ist ein Cowboyhut.}

{102}{}{Du hast den Fahrgast ans Ziel gebracht.}

{103}{}{Ruhe! Keine Zeit für Geplauder – lass uns einfach so schnell wie möglich von hier verschwinden.}
{104}{}{Danke für die Mitfahrgelegenheit! Wenn es nur mehr Leute wie dich gäbe.}
{105}{}{   }

{106}{}{Ich mache keinen Schritt, bevor wir nicht aus dieser Gegend raus sind.}

####################################################
#
#    Òèïîâûå äåéñòâèÿ ñ íïñ
#
####################################################

#Ñòàíäàğòíûå äèàëîãîâûå îïöèè
{120}{}{Warte hier, bis wir losfahren.}
{121}{}{Ja, ich möchte, dass du mir Gesellschaft leistest. Mit Mitreisenden zu reisen macht immer mehr Spaß.}

{122}{}{Na dann, los?}
{123}{}{Ich habe das Gefühl, wir sollten uns beeilen und verschwinden.}

{124}{}{Geh zurück zum Wagen, du wirst nicht gebraucht.}
{125}{}{Okay, Mann.}
{126}{}{Ich brauche deine Hilfe. Folge mir.}
{127}{}{Hey, keine Witze – die Zeit wird knapp. Keine Ahnung, was du von mir willst, aber ich werde mich nicht weit vom Wagen entfernen.}
{128}{}{Folge mir einfach.}
{129}{}{Dann bleib hier.}

#Ïîïûòêà òîëêíóòü [àâòîğû òåêñòà BalckDeigner è Kerb]
{130}{}{Hey! Finger weg!}
{131}{}{Ich kann selbst auf mich aufpassen, nur damit du's weißt.}
{132}{}{Willst du mich etwa anfassen?}
{133}{}{Hey, ich schwitze doch gar nicht so sehr!}
{134}{}{Stinke ich etwa?}
{135}{}{Wohin? Dahin? Okay. Aber dann geht's nach Vegas!}
{136}{}{Stört mich nicht ... vorerst.}
{137}{}{Werd nicht gleich so aufgeregt.}
{138}{}{}
{139}{}{}
#--- Äëÿ æåíñêîãî ïåğñà:
{140}{}{Wenn du dich schon entschieden hast, es anzufassen – weiter unten, Baby.}
{141}{}{Du hast so weiche Hände!}
{142}{}{Soll ich für dich Gitarre spielen, Baby?}
{143}{}{Oh, magst du's hart?}
{144}{}{Du könntest einfach fragen. Ich kann nicht widerstehen.}
#--- Äëÿ ìóæñêîãî:
{145}{}{Oh Mann, lass deine Hände bei dir!}
{146}{}{Hey, nicht schubsen! Ich wäre fast in einen Haufen Scheiße getreten.}
{147}{}{Okay, ich bin schon weg.}
{148}{}{Okay, du bist der Boss.}
{149}{}{Ich halte auch lieber Abstand.}

#Ïåğâûé äèàëîã
{150}{}{[Du siehst einen nackten Mann mit athletischem Körperbau und einem ausgeprägten Sixpack] Hey, Mann, kannst du mich nach Vegas mitnehmen? Ich bezahle, versprochen.}
{151}{}{Wie willst du bezahlen? Du hast ja nicht mal eine Hose an!}
{152}{}{Du siehst nicht wie ein Anhalter aus. Was ist der Haken?}
{153}{}{Kein Problem! Setz dich hin, Mann, ich bring dich hin.}
{154}{}{Ich brauche keine ungeeigneten Reisebegleiter.}

{155}{}{Wenn ich sage, dass ich bezahle, dann bezahle ich auch! Vertrau mir, okay?}
{156}{}{[Er wirft die Hände seitlich in die Luft und zeigt, dass er überhaupt nichts bei sich hat] Mann, ich bin sauber wie russischer Wodka! Keine Hintergedanken! Absolut keine!}
{157}{}{Wirklich?! Wow, Mann, du rettest mir den Tag! Weißt du, wo das Café "Hard Rock" in Vegas ist? Da sollte ich sein. Und je schneller, desto besser.}
{158}{}{Na dann, mach dich vom Acker! [zeigt verzweifelt den Mittelfinger]}
{159}{}{[Gehen]}

{160}{}{Wir ziehen bald los, aber bis dahin – warte.}

{161}{}{Bevor wir aufbrechen, beantworte noch ein paar Fragen.}
{162}{}{Los geht's.}

{163}{}{Wir verschwenden Zeit, Mann.}
{164}{}{Wohin gehst du?}
{165}{}{Nach Vegas. Man sagt, es ist lange her, dass im Café "Hard Rock" jemand großartige Country-Musik gehört hat. Da sollte ich sein ... Um diesen Hinterwäldlern zu zeigen, dass es in Nevada noch echte Musik gibt.}
{166}{}{Ich glaube, du bist zu spät dran, Cowboy. Die Bühne im "Hard Rock" ist schon mit erstklassigem Jazz besetzt.}
{167}{}{Was?! Nein!! Bist du sicher? Verdammt! Die Typen sind schon da und legen los! Ich muss mich beeilen, Mann. Los geht's!}
{168}{}{Warum bist du nackt?}
{169}{}{Mir ist einfach heiß.}
{170}{}{-??}
{171}{}{Ja! Was ist denn? Ist dir das peinlich? Kumpel, beruhig dich, bring mich nach Vegas, ich entschädige dich für deine Ausgaben.}
{172}{}{Ich besorge dir ein paar Klamotten.}
{173}{}{Klamotten? Scheiß auf Klamotten, Mann!! Hier steht eine viel wichtigere Frage auf dem Spiel! Wir sind auf einer Mission, um Vegas zu retten, das letzte Refugium der verdammten amerikanischen Kultur, und du redest mit mir über Klamotten?! Los geht's! Nach Vegas! Keine Minute verlieren!}
{174}{}{Du wirst mir doch nicht etwa ... an die Wäsche wollen, oder?}
{175}{}{Wa- ... IHH!! Ich hasse Schwuchteln! Nein, ich bin nicht so, ganz sicher nicht.}
{176}{}{Schätzchen, heute Abend nicht – der hübsche John ist beschäftigt, tut mir leid.}

{177}{}{Das Gespräch ist beendet. Warte, bis wir aufbrechen.}
{178}{}{}
{179}{}{}

#Èíñöåíèğîâêà
{180}{}{Hey, du! Was zum Teufel, Nigger, was zum Teufel glaubst du, was du da machst!?}
{181}{}{DU!? Aber ... WIE!?}
{182}{}{Das war einfach. Jetzt kommt uns keiner mehr in die Quere!}
{183}{}{Äh, Kumpel, ich war's nicht, der dich bei diesen Schlägern verpfiffen hat, ehrlich!..}
{184}{}{Scheiß auf die Schläger und meine Jacke! Scheiß auf den Dreck!}
{185}{}{Äh ... John, lass mich das erklären ...}
{186}{}{Spar's dir, du Hurensohn! Du hast schon genug von meiner Zeit verschwendet!}
{187}{}{Du brichst mir das Herz, John. Wir sind Gefährten!}
{188}{}{Ganz genau! Wenn du allein auf diese Bühne gehst, schmiere ich deine Eingeweide überall darauf!}
{189}{}{Das war nur ein Missverständnis. Natürlich gehen wir zusammen. Daran habe ich nicht einmal gedacht ...}
{190}{}{Gut. Wir haben noch Zeit, uns vorzubereiten. Und jetzt: Hau ab!}
{191}{}{Wie du meinst ... Partner.}
{192}{}{}
{193}{}{}
{194}{}{}

{195}{}{Verflucht seist du, du undankbarer Dreckskerl! Ich habe so viele Batterien für dich verschwendet ...}
{196}{}{Nimm's nicht persönlich, Mann, aber wir müssen getrennte Wege gehen. Danke fürs Mitnehmen und so. Und ich erinnere mich, dass ich versprochen habe, dich zu bezahlen ... Scheiße, hör zu, ich habe gelogen. Ich habe nichts, womit ich dich bezahlen könnte, aber irgendwann hole ich das nach. Ehrlich, kein Scheiß. Mein Partner und ich versuchen, in einem örtlichen Imbiss aufzutreten, und wenn wir Glück haben, springt dabei ordentlich Geld für uns heraus.}
{197}{}{Hast du's nicht kapiert, Mann? Er hat dich sitzen lassen! Und du willst immer noch mit ihm zu tun haben?}
{198}{}{Natürlich! Reiß mir den Arsch auf, wenn ich meine Freunde verrate, Mann.}
{199}{}{Äh ... Deine Sache. Na gut, pass auf dich auf.}

####################################################
#
#    Âñòóïèòåëüíûå ğåïëèêè ïğè çàõîäå íà êàğòó
#
####################################################

#Ğıíäîìíûå òèïîâûå ôğàçû ïğè çàãğóçêå ëşáûõ êàğò [àâòîğû òåêñòà BalckDeigner è Kerb]
{200}{}{Wo zum Teufel sind wir?!}
{201}{}{Das ist nicht Vegas!}
{202}{}{Gib mir recht: Wir sind nicht da, wo wir sein wollen.}
{203}{}{Hey, warum halten wir hier an?}
{204}{}{Sag bloß nicht, dass wir uns verfahren haben, ja?}
{205}{}{Wir sind Cowboys, wir sind Cowboys, wir sind mutig und zu zweit!}
{206}{}{Äh ... Wenn der Sitz nur nicht so sehr an meinem Hintern kleben würde ...}
{207}{}{Sieh mich nicht so an! Wenigstens ist meine Bräune gleichmäßig.}
{208}{}{Ich würde lieber in den Toiletten von Vegas leben als hier.}
{209}{}{Nur in Vegas finde ich meinen Frieden.}
{210}{}{Ich sehe mich mal um. Vielleicht finde ich etwas zu essen.}
{211}{}{Keine Sorge, ich passe auf das Auto auf.}
{212}{}{Ugh! Ich will so spektakulär wie möglich in Vegas einfahren.}
{213}{}{Frische Luft ... Willst du da eine Klimaanlage einbauen?}
{214}{}{[singt]}

#Êîíòåêñòíûå ôğàçû äëÿ îòäåëüíûõ êàğò
#--- äàìáà Ãóâåğà
{250}{}{Warum bringst du mich nicht gleich zum „Hard Rock“? Das wäre schneller.}
{251}{}{Am Damm gibt es nichts zu tun. Zum „Hard Rock“, solange wir noch können!}
#--- îğèãèíàëüíàÿ êàğòà âñòğå÷è
{255}{}{Waren wir nicht schon mal hier?}
{256}{}{Dieser Ort erinnert mich an etwas ...}
{257}{}{Ich wette, wir drehen uns im Kreis!}
#--- Ìåğòâûé îòåëü
{260}{}{Was ist das hier für eine Gegend? Bringst du mich vielleicht zum „Hard Rock“, bevor wir uns verirren?}
{261}{}{Das ist nicht Vegas, sondern irgendein Loch. Wo ist das „Hard Rock“?}
#--- Ğàáîòîğãîâöû Âåãàñà
{265}{}{Warum halten wir hier an?! Äh, hör zu, lass uns von hier verschwinden!}
{266}{}{Nein, nein, nein! Halt hier bloß nicht an!}
{267}{}{Ich bleibe nicht in dieser Gegend! Mach, was du willst – ich warte beim Wagen, egal was passiert.}
#--- ×èñòûé Ãîğîä
{268}{}{Jetzt denke ich an Klamotten. Vielleicht sollten wir zum „Hard Rock“ fahren?}
{269}{}{Wow! Das ist Vegas.}
{270}{}{Ja, so hatte ich es mir vorgestellt. Jetzt suchen wir das „Hard Rock“.}
#--- ñòîÿíêà êàğàâàíîâ â Âåãàñå
{275}{}{Das ist nur ein Vorort. Wo ist das „Hard Rock“?}
{276}{}{Ich bin sooo aufgeregt. Weißt du, wo es langgeht?}
{277}{}{Wir sind fast da! Jetzt müssen wir nur noch das Café finden.}

#Æåíñêèå âàğèàíò
{1104}{}{Danke für die Mitfahrgelegenheit! Wenn es nur mehr Leute wie dich gäbe.}
{1125}{}{Okay, Süße.}
{1150}{}{[Du siehst einen nackten, athletisch gebauten Mann mit einem ausgeprägten Sixpack] Hey, Süße, kannst du mich nach Vegas mitnehmen? Ich bezahle, versprochen.}
{1156}{}{[Er wirft die Arme seitlich in die Luft und zeigt, dass er keinerlei Gegenstände bei sich hat] Süße, ich bin so sauber wie russischer Wodka! Keine Hintergedanken! Ganz bestimmt!}
{1157}{}{Wirklich?! Wow, Süße, du rettest mir den Tag! Weißt du, wo das Café „Hard Rock“ in Vegas ist? Da muss ich hin. Je schneller, desto besser.}
{1163}{}{Wir verschwenden Zeit, Süße.}
{1165}{}{Vegas, Baby. Man sagt, im Café „Hard Rock“ habe schon lange niemand mehr großartige Country-Musik gehört. Da sollte ich hin ... um diesen Hinterwäldlern zu zeigen, dass es in Nevada noch echte Musik gibt.}
{1167}{}{Was?! Nein!! Bist du sicher? Verdammt! Die Typen sind schon da und legen los! Ich muss mich beeilen, Mann. Los geht's!}
{1171}{}{Ja! Was ist denn los? Ist es dir peinlich? Schätzchen, beruhig dich. Bring mich nach Vegas, ich komme für alle deine Ausgaben auf.}
{1173}{}{Klamotten? Scheiß auf Klamotten, Baby!! Hier steht eine viel wichtigere Frage auf dem Spiel! Wir sind auf einer Mission, um Vegas zu retten, das letzte Heiligtum der verdammten amerikanischen Kultur, und du redest mit mir über Klamotten?! Los geht's! Nach Vegas! Keine Zeit zu verlieren!}
{1196}{}{Keine Sorge, Baby, aber wir müssen getrennte Wege gehen. Danke für die Mitfahrgelegenheit und so. Und ich erinnere mich, dass ich versprochen habe zu zahlen ... Scheiße, hör zu, ich habe gelogen. Ich habe nichts, womit ich bezahlen könnte, aber irgendwann hole ich das nach. Ehrlich, kein Scheiß. Mein Partner und ich versuchen, in einem Lokal aufzutreten, und wenn wir Glück haben, kommt dabei ordentlich Geld rum.}
{1198}{}{Natürlich! Reiß mir den Arsch auf, wenn ich meine Freunde verrate, Baby.}
