{100}{}{Du siehst einen wilden Ghoul.}
{101}{}{Du siehst einen Agenten einer inzwischen aufgelösten Patrouilleneinheit. Sieht nicht so aus, als würde er so bald in den Ruhestand gehen.}

{110}{}{Gestatten, Michael Dixon, Patrouilleneinheit.}
{111}{}{Zeig mir die Papiere, bevor ich Gewalt anwende.}
{112}{}{Steig aus dem Wagen und berühre mit einem Finger deine Nase.}
{113}{}{Sieht aus, als wärst du betrunken. Als Strafe werden dir beide Hände amputiert.}
{114}{}{Ich wäre nicht überrascht, wenn du in den Schmuggel illegaler Mexikaner verwickelt bist.}
{115}{}{Gib deine Waffe ab, bevor ich Verstärkung rufe.}
{116}{}{Ich bin gezwungen, zu drastischen Maßnahmen zu greifen.}
{117}{}{Ich frage dich nur ein einziges Mal ...}
{118}{}{Ich beschlagnahme dein Fahrzeug.}
{119}{}{Widerstand ist zwecklos.}