{100}{}{Du siehst einen Karawanenmeister.}
{101}{}{Gott sei Dank haben wir es hierher geschafft. Es scheint immer schwieriger zu werden, von einem Ort zum anderen zu kommen, ohne von irgendwem oder irgendetwas angegriffen zu werden.}
{102}{}{Was kann ich jetzt für dich tun?}
{103}{}{Wohin bist du unterwegs?}
{104}{}{Was hast du geladen?}
{105}{}{Tschüss.}
{106}{}{Ugh.}
{107}{}{Ich habe gerade eine Lieferung abgeholt aus }
{108}{}{ und jetzt bin ich unterwegs nach }
{109}{}{.}

# Ëîêàöèè
{198}{}{New Reno}
{199}{}{Kriegswind}
{200}{}{Vault City}
{201}{}{Wendover}
{202}{}{ }
{203}{}{Vegas}
{204}{}{Ailie}
{205}{}{NPP}
{206}{}{Salt Lake City}
{207}{}{Lovelock}
{208}{}{Wendover}
{209}{}{ }

{110}{}{Was hast du geladen?}
{111}{}{Tschüss.}
{112}{}{Wir transportieren }

# Cargo for the Caravan
{150}{}{Medizin.}
{151}{}{Golderz.}
{152}{}{Urangestein.}
{153}{}{Farmwaren.}
{154}{}{Drogen.}
{155}{}{Sklaven.}
{156}{}{Zeug.}

{113}{}{Meinst du, ich könnte vielleicht mit dir handeln?}
{114}{}{Wohin bist du unterwegs?}
{115}{}{Tschüss.}
{116}{}{Nun, ich sehe keinen Grund, warum nicht, schließlich hast du uns aus einer misslichen Lage geholfen und so. Hier ist, was ich habe.}
{117}{}{[Tauschhandel]}
{118}{}{Ich habe es mir anders überlegt.}
{119}{}{Ich weiß, ich habe dich schon irgendwo gesehen. Heilige Scheiße! Du bist der Typ auf all diesen Steckbriefen! Hör zu, wir wollen keinen Ärger. Du gehst deines Weges, und wir gehen unseren. Ich werde niemandem erzählen, dass wir dich gesehen haben. Also verschwinde!}
{120}{}{Hey! Du bist der Typ auf all diesen Steckbriefen. Keine Sorge, ich verpfeife dich nicht; soweit ich mich erinnere, werde ich selbst an ein paar Orten gesucht. Also, willst du handeln oder nicht?}
{121}{}{[Tauschhandel]}
{122}{}{Gut genug. Wir müssen weiter. Keine Sorge, ich verpfeife dich nicht.}
{123}{}{Moment mal! Ich habe von dir gehört. Bist du das Scheusal, das jeden Karawanenführer in Nevada schikaniert? Wir können Leute wie dich nicht leiden, also zieh Leine!}
{124}{}{Ich habe Gutes über jemanden gehört, der auf deine Beschreibung passt. Ich schätze, es wäre in Ordnung, dir etwas von unserer Ladung zu verkaufen. Hier ist, was ich habe.}
{125}{}{[Tauschhandel]}
{126}{}{Tschüss.}
{127}{}{Ich habe von dir gehört. Du bist der knallharte Kerl, der überall für Randale sorgt. Ich habe mich schon darauf gefreut, dich zu treffen und dir die Hand zu schütteln. Wenn ich an all die unverschämten und respektlosen Gerüchte über dich denke, kommen mir die Tränen. Es wäre mir eine Ehre, mit dir zu handeln.}
{128}{}{[Tauschhandel]}
{129}{}{Tschüss}
{130}{}{Man sagt, dass du oder jemand, der so aussieht wie du, in letzter Zeit Ärger gemacht hat. Ich mache keine Geschäfte mit Leuten wie dir. Tut mir leid.}
{131}{}{Ich weiß nicht, was du willst, und es ist mir auch egal. Mit Leuten wie dir machen wir keine Geschäfte.}
{132}{}{Warum gehst du nicht ... woanders „Gutes tun“. }
{133}{}{Ich bin sicher, jemand mit deinem Ruf findet anderswo Vorräte.}
{134}{}{Nennen Sie Ihr Anliegen.}
{135}{}{Wohin bist du unterwegs?}
{136}{}{Was hast du geladen?}
{137}{}{Tschüss.}
{138}{}{Ugh.}
{139}{}{Das ist ... schön. Haben Sie noch einen schönen Tag. }

{300}{}{Danke für Ihren Einkauf.}