{100}{}{Du siehst einen Wachmann.}
{101}{}{Du siehst einen der Wachleute. Sie bewachen mit dir den Karawanenzug.}

{200}{}{Du siehst einen Karawanenhändler.}
{201}{}{Du siehst einen deiner Mitreisenden.}

{300}{}{Ich hoffe, wir begegnen unterwegs niemandem mehr.}
{301}{}{Es wird schön sein, am Ende meinen Lohn zu bekommen.}
{302}{}{Ich hoffe, die Bar hat noch geöffnet, wenn wir dort ankommen.}
{303}{}{Es wird schön sein, endlich mal wieder richtiges Essen zu bekommen.}
{304}{}{Ich wollte schon immer reisen. Ich glaube, das kommt dem Reisen am nächsten.}
{305}{}{Meine Füße bringen mich um. Warum laufen diese blöden brahmin so langsam?}
{306}{}{Es fühlt sich an, als wären wir nicht mehr weit von unserem Ziel entfernt.}