{100}{}{Du siehst einen schlanken, sonnengebräunten Mann.}
{200}{}{Du siehst eine schlanke, sonnengebräunte Frau.}
# male
{101}{}{Du siehst einen Farmer.}
# female
{201}{}{Du siehst einen Farmer.}
{102}{}{Du bemerkst, dass er eine Farmerbräune hat.}
{202}{}{Du bemerkst, dass sie eine Farmerbräune hat.}
{103}{}{Du bist gerade noch rechtzeitig gekommen. Wenn du nicht gekommen wärst ... Nun, wir sind dir dankbar, dass du gekommen bist. Wir haben nicht viel, aber ich möchte, dass du das als Belohnung für deine Hilfe annimmst. [Er gibt dir etwas]}
{104}{}{Danke.}
{105}{}{Ugh.}
{106}{}{Nochmals vielen Dank, dass du uns geholfen hast.}
{107}{}{}
{108}{}{}
{109}{}{Du da, Hände hoch, damit ich sie sehen kann. In letzter Zeit machen uns Banditen zu schaffen. Du könntest einer von ihnen sein. Was willst du?}
{110}{}{Ich will nur Vorräte tauschen.}
{111}{}{Ich bin nur auf der Durchreise. Ich geh dann mal weiter.}
{112}{}{Ugh.}
{113}{}{Na ja, ich schätze, das kann nicht schaden. Hier ist, was ich zum Tauschen habe.}
{114}{}{[Tauschhandel]}
{115}{}{Na gut, und jetzt verschwinde!}
{116}{}{[Tauschhandel]}
{117}{}{Ich sagte, verschwinde!}
{118}{}{}
{119}{}{[Er entspannt sich ein wenig.] Du bist zu dämlich, um ein Bandit zu sein. Brauchst du Vorräte?}
{120}{}{Mhm.}
{121}{}{Nö.}
{122}{}{Dann haben wir nichts miteinander zu bereden. Geh einfach weiter.}
{123}{}{[ENDE]}
{124}{}{Verschwinde von meiner Farm!}
{125}{}{Niemand nimmt mir mein Zuhause weg.}
{126}{}{Dreckige Banditen.}
{127}{}{Runter von meinem Land.}
{128}{}{Heutzutage kann man niemandem mehr trauen.}
{129}{}{Verdammte Banditen.}
{130}{}{Ich habe zu hart gearbeitet, um jetzt aufzugeben.}
{131}{}{Vielleicht farme ich woanders.}
{132}{}{Ich bin nur ein armer Farmer.}
{133}{}{Bitte, brennt meine Farm nicht nieder.}
{134}{}{Landwirtschaft hat mir sowieso nie gefallen.}
{135}{}{Ich komme wieder.}
{136}{}{Bitte, nimm meine Frau ...}