{100}{}{Du siehst deinen Verfolger.} 
{101}{}{Du siehst einen Söldner. Er ist hinter dir her, weil du den Filter zu Salt Lake bringen willst.}

{110}{}{Gib mir sofort den Filter!}
{111}{}{Du entkommst mir nicht! Gib mir den Filter!}
{112}{}{Das Ding in deinem Rucksack gehört mir!}
{113}{}{Bist du auf dem Weg nach Salt Lake? Soll ich deine Sachen tragen?}
{114}{}{Salt Lake wird bestimmt viel Geld für diesen Filter bezahlen.}
{115}{}{Halt die Klappe und gib mir den Filter!}
{116}{}{Tut mir leid, aber ich brauche diesen Filter dringender als du.}
{117}{}{„Stehen bleiben!“ – Soll man das bei einem Überfall etwa sagen?}
{118}{}{Das Ding ist zu schwer, und die Stadt ist sehr weit weg. Gib es mir.}
{119}{}{Mit diesem Filter herumzulaufen, ist ziemlich gefährlich, findest du nicht?}
{120}{}{Auch wenn ich Karawanenhändler bin, liebe ich schnelles Geld.}
{121}{}{Filter oder Leben?}