{100}{}{Du siehst einen vernarbten Reisenden.}
{101}{}{Du siehst den Wachmann des Händlers.}

{200}{}{Keine gezogenen Waffen in der Nähe des Bosses.}
{201}{}{Niemand kommt bewaffnet zum Boss.}
{202}{}{Leg deine Waffe weg, bevor wir dich erschießen.}
{203}{}{Waffen weg, oder mach dich vom Acker.}

{250}{}{Du wurdest gewarnt – jetzt wirst du dafür bezahlen.}

{300}{}{Sprich mit dem Boss, er regelt das.}
{301}{}{Ich nehme meinen Job ernst. Legst du dich mit dem Boss an, bist du tot.}
{302}{}{Der Boss ist eigentlich ein guter Kerl.}
{303}{}{Denk nicht mal daran, den Boss zu bestehlen.}