{100}{}{Du siehst Harrelson.}
{101}{}{Du siehst den paranoiden Ghul namens Damon Harrelson. Schwer zu sagen, was in seinem Kopf vorgeht.}

{102}{}{[Als du um die Ecke schaust, läufst du plötzlich dem Ghul über den Weg, der eine schäbige Robe mit dem Firmenlogo von Nuka-Cola trägt. Als er dich sieht, greift er sofort nach seiner Waffe, doch du schaffst es gerade noch rechtzeitig, in den Schatten zurückzuweichen.]}
{103}{}{[Weiter]}

{104}{}{Hey, du Plünderer! Komm raus! Vielleicht wird dein Tod dann schnell und still sein. Obwohl ich dir das nicht versprechen kann!}
{105}{}{Keine Eile, Hübscher ... Harrelson, richtig?}
{106}{}{Du bist hier der Plünderer!}
{107}{}{[Geh raus und stürz dich in den Kampf]}
{108}{}{[Versuche zu entkommen]}

{109}{}{Was hast du gesagt!? Ihr Hurensöhne, das ist MEINE Hütte! Und DU bist hierhergekommen, um meine hart verdiente Beute zu stehlen! Dafür wirst du extra leiden!}
{110}{}{[Kämpfen]}
{111}{}{Hä? Was murmelst du da, du kleiner Dieb!? Ich kenne all deine Tricks! Versuch gar nicht erst, mich hinters Licht zu führen, sonst wird dein Tod SEHR schmerzhaft!}
{112}{}{Hätte nie gedacht, von einem alten Ghul eine vernünftige Ansprache zu hören. Wie bist du so geworden?}

{113}{}{Ich sag's dir ... sobald ich dich erwische und in einen Käfig stecke! Ich habe schon ein paar Dutzend wie dich gefangen. Jeder von ihnen wollte ein Stück von mir, wollte meine Sachen. Aber meine Fallen sind nicht nur zur Zierde da! Und du? Bist du nicht deswegen hierhergekommen?}
{114}{}{Ich bin hier, um deinem Wahnsinn ein Ende zu setzen.}
{115}{}{Stimmt – ich bin nur hier, um dir deinen ganzen Besitz zu klauen und ihn den Quok-Brüdern zu verkaufen.}

{116}{}{Dann hör auf zu reden!}
{117}{}{Wer ist hier verrückt?! Du springst einer Waffe entgegen, obwohl du genau weißt, wie es ausgeht, und ich ... ich verteidige mein Zuhause!}
{118}{}{Vielleicht hast du deinen Besitz beschützt, aber dafür mussten gewöhnliche Prospektoren sterben. Was ist mit deinem Gewissen? Quält es dich nicht?}
{119}{}{Sag mal, woher hast du all diese Sachen? Von Leichen genommen?}
{120}{}{Sind das nicht zu viele Worte für ein Wesen, das seine menschliche Gestalt verloren hat?}
{121}{}{Also interessieren dich nur deine Sachen und die anderen sind dir völlig egal?}
{122}{}{Ich hab genug davon. Ich will dir ein für alle Mal den Garaus machen.}

{123}{}{Gewissen? Dieses Wort habe ich seit siebzig Jahren nicht mehr gehört ... Es konnte keinen von denen retten, die bei den Atomexplosionen starben. Seitdem habe ich vergessen, was „Gewissen“ bedeutet.}
{124}{}{Atomexplosionen? Heißt das, du hast den Großen Krieg miterlebt?}
{125}{}{Die Leute haben bekommen, was sie verdient haben. Als ich Flaschen auslieferte, sah mich niemand als menschliches Wesen. Erst als ich die Großstadt verließ, fand ich in meinem Auto endlich Frieden. Als ich die Lichtblitze sah ... erfüllte mich Freude. Ich dachte, ich wäre der letzte Mensch auf der Welt ... bis Bastarde wie ihr aufgetaucht seid! Sie kamen hinter mir her, wollten mir meine Vorräte wegnehmen, wollten mich töten! Nein, ich fühle mich nicht schuldig, weil ich Tiere töte. Und Menschen sind Tiere!}
{126}{}{Ich glaube, du hattest einfach nur Pech mit den Leuten, und deshalb bist du wütend auf die ganze Welt.}
{127}{}{[Pause] Halt den Mund und komm dahin, wo ich dich sehen kann. Meine Vergangenheit wird dir bald keine Sorgen mehr bereiten. Wie ich sagte – Menschen sind Tiere. Sie verdienen es nicht mehr, menschliche Wesen genannt zu werden.}

{128}{}{Eine kleine Entschädigung für die Unannehmlichkeiten, die mir entstanden sind. Das ist nur fair.}
{129}{}{Warum dann all diese Opfer? Deine Abgeschiedenheit und die Gerüchte über blutige Gewalt ziehen nur noch mehr Aufmerksamkeit auf dich. Jeder denkt, dass du hier unermessliche Reichtümer hast.}
{130}{}{Das denken sie also über mich? Das war zu erwarten. Ihr Tiere riecht Geld, wie Fliegen fauliges Fleisch riechen. Habe ich nicht recht? Würde es die Welt schlechter machen, eine Fliege zu erschlagen?}
{131}{}{Ein interessanter Vergleich. Aber die Prospektoren suchten doch nur nach einem Weg zu überleben ... Solche Zeiten eben.}
{132}{}{Du hast immer noch den Mumm, darüber zu reden, Affe? Genau das tun diese Tiere. Sie nehmen ihresgleichen das Leben, um sich zu ernähren. Aber ja ... Solche Zeiten ... Solch eine Welt. [Er erinnert sich an etwas aus seiner Vergangenheit und hebt dramatisch die Stimme.] Aber vor dem Krieg war es genauso! Die Leute haben einander nicht wie heute umgebracht, aber sie schikanierten einander in der Schule, schikanierten die Schwachen in der Armee ... Die Menschen haben sich kein bisschen verändert.}
{133}{}{Gier und Egoismus – darum geht es dir, verstehe. Behandelst du die Leute denn anders?}
{134}{}{Halt den Mund! Halt den Mund! Ich habe genug von deinem Unsinn. Komm raus und stell dich deinem Schicksal, du diebischer Bengel!}

{135}{}{Oh, du bist nicht der einzige Dieb, mit dem ich mich unterhalten durfte ... Aber unser Gespräch macht mir mehr Spaß, wenn [er hebt die Stimme] du in einem Käfig sitzt und dir die Eingeweide herausgerissen wurden!!!}
{136}{}{Das ist hart.}
{137}{}{Weißt du, du gibst dich als netter Hurensohn aus, aber was würdest du sagen, wenn man dich mit einer scharfen Klinge an der Kehle an die Wand drückt? Ja, diesen ganzen Scheiß habe ich schon vor dem Krieg gesehen. Wenn man dich an der Kehle packt, kommt dein wahres Wesen zum Vorschein. Und glaub mir, es stinkt nicht weniger als ein Stück menschliche Scheiße.}
{138}{}{Ich glaube, in meinem Wesen steckt mehr als das.}
{139}{}{Komm raus, dann werden wir sehen. Du bist weder der Erste noch der Letzte. Aber du gefällst mir. Mit dir werde ich ein längeres „Gespräch“ führen als sonst.}

{200}{}{Du erhältst eine hohe Dosis radioaktiver Strahlung vom Ghoul.}
{201}{}{Oh, ich spüre, wie deine Zellen absterben!}
{202}{}{Oh, ich spüre, wie die Strahlung dich durchdringt!}
{203}{}{Dein Körper wird die Strahlung lieben!}
{204}{}{Ghoulifizierung sollte nicht deine Sorge sein. Du wirst vorher tot sein!}

#Female character
{1109}{}{Was hast du gesagt!? Du Schlampe, das ist MEINE Hütte! Und DU bist hierhergekommen, um meine hart erarbeiteten Waren zu klauen! Ja, dafür wirst du extra leiden!}
{1112}{}{Hätte nie gedacht, vom alten Ghoul eine vernünftige Ansprache zu hören. Wie bist du so geworden?}
{1113}{}{Ich sag's dir ... sobald ich dich erwische und in einen Käfig stecke! Ich habe schon ein paar Dutzend wie dich gefangen. Jeder von ihnen wollte ein Stück von mir, wollte meine Sachen. Aber meine Fallen sind nicht nur zur Zierde da! Und du? Bist du nicht deswegen hierhergekommen?}
{1137}{}{Weißt du, du gibst dich als nette Schlampe und so aus, aber was würdest du sagen, wenn man dich mit einer scharfen Klinge an der Kehle an die Wand drückt? Ja, diesen ganzen Scheiß habe ich schon vor dem Krieg gesehen. Wenn man dich an der Kehle packt, kommt dein wahres Wesen zum Vorschein. Und glaub mir, es stinkt nicht weniger als ein Stück menschliche Scheiße.}
{1139}{}{Komm raus, dann werden wir sehen. Du bist weder der Erste noch der Letzte. Aber du gefällst mir. Mit dir werde ich ein längeres „Gespräch“ führen als sonst.}
