{100}{}{Das ist Hardy, ein Ghoul-Händler.}
{101}{}{Du siehst einen Händler mit verbrannter Haut.} 
{102}{}{Tu Ghulen nichts, du verdammter Rassist!} 
{103}{}{Willkommen ... Moment mal, seid ihr die Leute, von denen man mir in Reno erzählt hat? Keine hektischen Bewegungen, sonst lasse ich auf euch schießen!} 

#Òîğãîâëÿ
{110}{}{Ein Wanderer? Hier in der Gegend? [hustet] Interessant. Für die Reise brauchst du wahrscheinlich eine neue Unterhose. Überleg's dir – vielleicht finde ich unter diesen Sachen etwas für dich.}
{111}{}{Ja, zeig mir, was du hast.}
{112}{}{Ich glaube, ich kaufe im Moment nichts.}

{113}{}{Noch mehr?}
{114}{}{Ja, sehen wir uns deine Ware noch mal an.}
{115}{}{Nein, das reicht.}

{116}{}{Genug geredet, handeln wir.}
{117}{}{Noch eine Frage, wenn ich darf.}
{118}{}{Das reicht. Mach's gut.}

{119}{}{Hey, Glatthaut, du kommst gerade rechtzeitig! Warum? Weil ich nach ein paar weiteren Geschäften Schluss mache. Ja, der alte Hardy hat endlich beschlossen, in Rente zu gehen und sich irgendwo zu verstecken. Also sei nicht geizig – kauf mir meinen ganzen Kram ab. So eine Gelegenheit gibt's vielleicht nicht wieder!}

#Ğàññïğîñû
{120}{}{Kann ich dir ein paar Fragen stellen?}
{121}{}{Mach schnell – ich muss mich ausruhen.}
{122}{}{Woher kommst du?}
{123}{}{Aus dem Hub. Das liegt weit im Süden. Oder besser gesagt, nicht so weit, aber die Strecke zu Fuß ist wirklich hart. Zwischen dem Hub und Reno gibt es fast keine Siedlungen und keine Straßen. Außerdem müssen wir den größten Teil der Strecke durch eine karge Wüste zurücklegen. Diese Route ist zu Fuß ziemlich beschwerlich, selbst ohne Gepäck. Wahrscheinlich ist meine Karawane die einzige.}
{124}{}{Wie läuft das Geschäft?}
{125}{}{Nicht besonders gut, ehrlich gesagt. Jede Reise bringt uns gutes Geld ein, aber alles geht für die Kosten drauf – Sicherheit, Wasser, brahmin... Ich glaube, ich mache bald dicht. Also denk dran – vielleicht sehen wir uns nie wieder. Handel, solange du noch kannst.}
{126}{}{Erzähl mir von dir.}
{127}{}{Interessiert dich das wirklich? Was, wenn ich dir erzähle, wie ich in den Tagen des Großen Knalls aus meinem Versteck kam und so verstrahlt wurde, dass meine Mutter mich nicht wiedererkannte? Oder wie meine glatthäutigen Freunde eines natürlichen Todes starben, direkt vor meinen Augen? Oder willst du vielleicht wissen, wie es sich anfühlt, sich jeden Tag Dreck und Eiter aus dem Körper zu schneiden? Nein, ich rede lieber nicht über mich.}

{128}{}{Wenn du das Geschäft aufgeben willst, würdest du mir vielleicht einen Rabatt geben?}
{129}{}{Klingt vernünftig – je schneller du das Zeug loswirst, desto schneller komme ich nach Reno, zu meinen weißbrüstigen Mädels.}
{130}{}{Ach nein – mit solchen Tricks kommst du bei mir nicht durch. Ich habe das alles nicht umsonst durch die Wüste geschleppt!}
{131}{}{Na gut, vergiss es. Dann handeln wir eben zu deinen starrsinnigen Preisen.}
{132}{}{Dann kaufe ich gar nichts. Behalt dein Zeug.}
{133}{}{Weißt du noch, wie es vor dem Großen Krieg war?}
{134}{}{Genau wie jetzt. Nur ein bisschen sauberer und angenehmer.}

#Ïîñûëêà îò Áåğ÷à
{140}{}{Ich komme von Lewis Birch. Er hat mich gebeten, das zum Hub zu bringen.}
{141}{}{Birch hat dich geschickt? Dann gibt's kein Problem ... Ja, ich erkenne seine Holodisks. Gib sie her. Wenn ich zum Hub zurückkehre, statte ich dem Büro dieses Trottels einen Besuch ab. Die werden sich freuen, mich zu sehen!}
{142}{}{Na ja, meine Arbeit ist getan.}
{143}{}{Du hast Lewis Birchs Aufgabe abgeschlossen.}

#Female character
{1110}{}{Ein Wanderer? Hier in der Gegend? [hustet] Interessant. Für die Reise brauchst du wahrscheinlich eine neue Unterhose. Überleg's dir – vielleicht finde ich unter diesen Sachen etwas für dich.}
{1119}{}{Hey, Glatthaut, du kommst gerade rechtzeitig! Warum? Weil ich nach ein paar weiteren Geschäften Schluss mache. Ja, der alte Hardy hat endlich beschlossen, in Rente zu gehen und sich irgendwo zu verstecken. Also sei nicht geizig – kauf mir meinen ganzen Kram ab. So eine Gelegenheit gibt's vielleicht nicht wieder!}
