{100}{}{Du siehst einen Fremden.}
{101}{}{Du siehst einen seltsamen, unheimlichen Mann.}
{102}{}{Ein wahrer Riese. Er isst wahrscheinlich Leute wie dich zum Frühstück.}
{103}{}{?}
{104}{}{Wer zum Teufel seid ihr?!}
{105}{}{Ich werde deine Fragen nicht beantworten, Wanderer. Ich bin gekommen, um dich zu warnen.}
{106}{}{Mich warnen? Wovor?}
{107}{}{Verdammt! Wie hast du das ... Aus solcher Entfernung ...}
{108}{}{Das wird keine weitere Warnung geben. Gib deine Suche auf, oder du wirst das Schicksal anderer reiner Seelen teilen.}
{109}{}{Sieht aus, als wäre es ein Hinterhalt gewesen!}
{110}{}{„Reine Seelen“? Was zum Teufel faselst du da?!}
{1105}{}{Ich werde deine Fragen nicht beantworten, Wanderer. Ich bin gekommen, um dich zu warnen.}