{100}{}{Du siehst einen verwirrten Mann.}
{101}{}{Du siehst einen verwirrten Mann mit einem Schild auf der Brust, auf dem ÑIch weiﬂì steht. Er scheint schwer beunruhigt zu sein.}
{102}{}{Du hast dem Kerl das ÑBeruhigungsmittelì in den Hintern gespritzt.}
{103}{}{Verdammt, ich war gerade erst in Fahrt, und du ...}

{110}{}{Das ist eine T‰uschung! Nichts davon ist echt!}
{111}{}{Kneift mich mal jemand! Ich muss tr‰umen!}
{112}{}{Das-ist-ein-Albtraum-und-ich-kann-nicht-aufwachen!!!}
{113}{}{Nichts davon existiert wirklich ñ weder Nevada noch das CafÈ, nicht einmal ich!}
{114}{}{Wir wurden alle manipuliert!}
{115}{}{Jemand hat diese Halluzination erschaffen! Sie ist nicht echt!}
{116}{}{Jemand spielt uns nur etwas vor!}
{117}{}{Wir wurden reingelegt! Das ist alles gelogen!}
{118}{}{Es mag echt aussehen und echt klingen, aber es ist nicht echt!}
{119}{}{Du bist nur ein Spielzeug! Ein Bauer! Eine Marionette in geschickten H‰nden!}
{120}{}{Vertrau ihnen nicht! Sie wollen dich reinlegen!}

{200}{}{Das ist d‰mlich ... Viel zu d‰mlich ...}
{201}{}{Warum!? ...}
{202}{}{Ach verdammt, du hast den ganzen Spaﬂ verdorben ...}
{203}{}{Es w‰re gerade erst besser geworden ...}
