{100}{}{Du siehst Rekrut.}
{101}{}{Du siehst einen apathischen Mann, der wie ein Arzt oder Ingenieur aussieht. Ständig richtet er seine Brille.}

{110}{}{Wie oft hat der Wanderer den armen Sam schon erröten lassen?}
{111}{}{Findest du nicht, dass es einfacher ist, mit einer weiblichen Figur zu spielen?}

{112}{}{Bitte sprich ordentliches Englisch.}
{113}{}{Es heißt „you're“, nicht „your“.}
{114}{}{Es heißt „their“, nicht „there“.}
{115}{}{Du hast es erraten, manchmal kann ich ein Nerd sein.}
{116}{}{Hast du erwartet, hier einen Hund zu finden? Tut mir leid, Hunde sind nicht erlaubt.}
{117}{}{Ich kritisiere gern die Vorschläge anderer Leute.}
{118}{}{Warum nicht einem guten Menschen helfen?}
{119}{}{Ich habe immer gesagt, dass es eine gute Idee war!}
{120}{}{Nichts ist unmöglich für einen Mann, der es nicht selbst machen muss.}