{100}{}{Du siehst Kerb.}
{101}{}{Du siehst niemand Geringeren als Kerb!}

#Если ГГ бухой или обколотый:
{110}{}{Dieser Junkie soll die Welt retten? Na ja ... Warum zum Teufel nicht. Wie der Priester, so die Gemeinde.}

#Обычные ответные реплики:
{111}{}{2,5 Megabyte ... 2,5 Megabyte!!!}
{112}{}{Wenn ich dich ansehe, sehe ich endlose Dialogzeilen ...}
{113}{}{Ein nichtkommerzielles Projekt, hm? Wenigstens mьssen wir uns keine Sorgen um [censored] Zensur machen!}
{114}{}{Warte, was zum beschissenen Fick? Oh, schon gut, es funktioniert ...}
{115}{}{Und zum Teufel mit der politischen Korrektheit!}
{116}{}{Krieg. Krieg bleibt immer gleich ... Komm schon, das muss doch jemand sagen!}
{117}{}{Lass den Mut nicht sinken, Genosse! 2077 rьckt mit jeder Minute nдher!}
{118}{}{Ich frage mich, was wohl in dem Gebiet der ehemaligen UdSSR vor sich geht.}
{119}{}{Jetzt hдtte ich gern Lynettes Leber mit einem Glas Chianti ... Oder wenigstens Morpheus' Herz mit etwas Bier.}

#При применении воровства:
{130}{}{Hey! Lass deine dreckigen Krallen von mir!!}
#При применении науки:
{131}{}{Soziopath mit manisch-depressiver Stцrung, sagst du? Sieh dich doch mal an!}
#При применении бухла:
{132}{}{Schenk mir lieber ein Glas sьЯes Blut ein.}
#При применении drug-предметов:
{133}{}{Hey! Vielleicht wьrde ich dich auch gern mit etwas pieksen! Mit einem Messer zum Beispiel! Aber du siehst ja nicht, dass ich das tue, oder?}
