{100}{}{Du siehst Vault_13.}
{101}{}{Du siehst einen Administrator, einen Blogger, einen Musiker und noch mehr.}

{110}{}{Ach, es gibt nichts Besseres als ein Glas radioaktives Bier ...}
{111}{}{Hey, Barkeeper, nimmst du Bitcoins?}
{112}{}{Was gäbe ich für eine Schüssel russische Pelmeni.}
{113}{}{So hatte ich mir die postnukleare postapokalyptische Zukunft nicht vorgestellt.}
{114}{}{Hat hier jemand eine Milz übrig?}
{115}{}{Ja, ich finde die Vorstellung von unsichtbaren Menschen wirklich lustig.}
{116}{}{Ich bin 179 Jahre alt.}
{117}{}{Wo ist hier die Toilette? Ich muss ein paar Bomben abwerfen.}
{118}{}{Ich habe früher auch gelb-blaue Kleidung getragen. Das ging nicht gut aus.}
{119}{}{Haben sie dich auch aus dem Vault geworfen?}
{120}{}{Ach, sie haben dich also „auf eine wichtige Mission geschickt“, hm?}
{121}{}{Mach dir nichts vor, du hast einfach gestunken oder so.}
{122}{}{HIRNE!}
{123}{}{Ha-ha, nur ein Scherz.}
{124}{}{Wenn ich so darüber nachdenke, hatte ich früher mein eigenes Geschäft.}
{125}{}{Und alles, was davon übrig ist, ist diese verdammte Diskette!}
{126}{}{Stell dir vor, ich kam nur für eine Woche oder so in die USA, um ein paar Verwandte zu besuchen ...}
{127}{}{Und bumm, jetzt sitze ich hier fest.}
{128}{}{Warum habe ich mir überhaupt die Mühe gemacht, Steuern zu zahlen?}
{129}{}{Ich dachte, ich würde die Apokalypse bequem aus einem Vault auf meinem Landsitz beobachten.}
{130}{}{Aber nein.}
{131}{}{Ich sitze hier fest und fasle Fremden etwas vor.}
{132}{}{Hey, hast du vielleicht etwas Gras?}
{133}{}{Das wusste ich.}
{134}{}{Verdammter Kiffer.}
{135}{}{Hier ist kein einziger normaler Mensch.}
{136}{}{Hör auf, mich mit dem Ding zu pieksen!}