{100}{}{Du siehst BlackDesigner.}
{101}{}{Du siehst einen gewöhnlichen Designer, wie jeden anderen auch.}

{110}{}{Hast du beschlossen, mal vorbeizuschauen? Gut!}
{111}{}{Im Ödland ist allerhand los.}
{112}{}{Ich würde selbst reisen, aber nicht mit leeren Taschen.}
{113}{}{Ich arbeite buchstäblich für Essen.}
{114}{}{Wer leiht mir zwei Millionen Mäuse für mein Projekt?}
{115}{}{Nur läppische zwei Millionen!}
{116}{}{Na gut, vergiss, dass ich gefragt habe ...}
{117}{}{Es wird keine Fortsetzung geben. Ich denke, das hast du inzwischen verstanden.}
{118}{}{Woran ich jetzt arbeite? Komisch, ich arbeite an ... dir!}
{119}{}{Neeein, nein, nein! Ich habe hier keinerlei Alkohol.}
{120}{}{Hmm, also *so* willst du Rollenspiel spielen? ... Na ja, das ist deine Sache.}
{121}{}{Gehörst du auch zu denen, die nicht gern viel Text lesen?}
{122}{}{Wenn ich das ganze Team hierherholen würde, wäre kein Platz mehr, um eine Katze zu schwingen. Tut mir leid.}
{123}{}{Das „Ich weiß“-Kind? Beachte ihn nicht. Er war nicht der Erste und wird ganz sicher nicht der Letzte sein.}

{200}{}{Glaubst du, wenn du mich immer wieder mit diesem Ding piekst, bringt dich das weiter?}
{201}{}{Hmm, an deiner Hartnäckigkeit merke ich, dass du glaubst, dabei käme etwas Nützliches heraus. Ha!}
{202}{}{Ja, ich weiß, du erwartest, dass ich dir irgendein superduper Gerät gebe. Tut mir leid, deine Erwartungen zu enttäuschen, aber daraus wird nichts.}
{203}{}{Was soll ich sonst noch für dich tun? Das Spiel für dich durchspielen?}
{204}{}{Ja, nur zu, ich bringe es einfach noch nicht übers Herz, es dir zu sagen ...}
{205}{}{Was, du piekst so gern mit einem Pfeil auf einen Mann ein? Aber für ein Geschenk würdest du doch alles tun, oder?}
{206}{}{Ja, genau! Fast geschafft!}
{207}{}{Klar. Du hast es dir verdient. Ich hole es jetzt ... Nein, warte. Noch nicht.}

{210}{}{Verdammt, du hast so viel Zeit und Mühe investiert! Ein Applaus ist angebracht, ich muss dich belohnen. Hier. Eine unerschöpfliche Erfahrungsquelle ... Na ja, solange du den Mut dazu hast.}
{211}{}{[Gehen]}
{212}{}{Ich glaube, ich habe alles gesagt.}