{100}{}{Du siehst Master.}
{101}{}{Du siehst Master, den Einzigen und Wahrhaftigen.}

{110}{}{Wow, ein Auto! Darf ich einen Blick unter die Motorhaube werfen?}
{111}{}{Was haben wir denn hier? Ein Fahr-ze-ug!}
{112}{}{Ich kann dir nicht helfen, frag im Forum nach.}
{113}{}{Als ich jung war, habe ich jeden Winkel dieses Ödlands bereist, von Kalifornien bis Washington. Früher war ich wie du ein Abenteurer, aber dann bekam ich eine Kugel ins Knie.}