{100}{}{Du siehst einen King.}
{101}{}{Du siehst eines der Mitglieder der King-Gang.}

{110}{}{Du hättest nicht in dieses Gebiet kommen sollen.}
{111}{}{Wir sind hier die Kings!}
{112}{}{Du musst zahlen, um durch unser Gebiet zu kommen.}
{113}{}{Äh, das Schutzgelderpressen wird in letzter Zeit schwieriger.}
{114}{}{Eigentlich bin ich kein Gangster – aber die Gang hat anders entschieden.}
{115}{}{Gib uns das Geld und verpiss dich!}
{116}{}{Was, die Lichter von Vegas locken dich auch?}
{117}{}{Der Boss freut sich, wenn ich dir ein paar Münzen abnehme.}
{118}{}{*Wir* sind hier die Kings, also benimm dich!}
