{100}{}{Du siehst einen Mann, der in seinem Leben schon viel erlebt hat.}
{101}{}{Du siehst einen Händler.}
{102}{}{Wow, hier in der Gegend sind nicht gerade viele Leute.}
{103}{}{Hey! Warte! Ich habe Waren, die du gebrauchen könntest!}
{104}{}{Hey! Hast du etwas zum Tauschen?}
{105}{}{Heute ist wohl mein Glückstag. Sieh dir an, was ich im Angebot habe.}

{200}{}{Hallo, Reisender! Auf dieser Route sind Menschen selten, aber neue Kunden sind mir immer willkommen. Wollen wir handeln?}
{201}{}{Na, du! Gut, dass du vorbeischaust. Die meisten Leute ziehen auf dieser Route einfach weiter. Willst du handeln?}
{202}{}{Willst du meine Waren sehen?}

{250}{}{Das wäre nett.}
{251}{}{Tut mir leid. Ich muss weiter.}
{252}{}{Ja. Ich haben Waren!}
{253}{}{Ich gehen.}

{260}{}{Hat mich gefreut, mit dir Geschäfte zu machen. Viel Glück auf deiner Reise.}
{261}{}{Tschüss.}

{270}{}{Gut, Sie sind zurück. Darf ich Ihnen noch etwas anbieten?}
