{100}{}{Du siehst einen verwilderten Roboter-Diener.}
{101}{}{Du siehst einen Roboter-Diener der Serie „Mr. Handy“. Wahrscheinlich hat dieser hier seine Besitzer vor vielen Jahren verloren.}
{102}{}{ }

{110}{}{Möchten Sie einen Witz hören, Mr. McClennan?}
{111}{}{Guten Morgen, Mrs. McClennan.}
{112}{}{Abschaum wie ihr habt Mrs. McClennan getötet!}
{113}{}{Verschwindet vom Anwesen der Familie McClennan!}
{114}{}{Retten Sie sich, Mr. McClennan! Gehen Sie in den Keller und nehmen Sie die Kinder mit!}
{115}{}{Ich lasse nicht zu, dass ihr meinen Herren etwas antut!}
{116}{}{Niemand darf den morgendlichen Hundespaziergang unterbrechen. Sie müssen ein Bußgeld zahlen.}
{117}{}{Ich sehe einen Dieb! Meister, bleiben Sie im Zimmer und schließen Sie die Tür ab!}
{118}{}{Sie hätten den Hund meines Herrn nicht entführen dürfen!}
{119}{}{Was für ein blendender Lichtblitz! Mr. McClennan? Was ist los? Mr. McClennan!}
{120}{}{Ich darf den Mitgliedern der Familie McClennan nichts antun, aber Sie gehören nicht dazu!}
{121}{}{Ich wurde darauf programmiert, Befehle zu befolgen, aber nur von Mitgliedern der Familie McClennan!}
{122}{}{Ich muss beschützen, denn ich bin Eigentum der Familie McClennan.}
{123}{}{Es wird ein sanfter Regen sein!!!}
{124}{}{Ihr Blut ist ein hervorragendes Schmiermittel, -Fehler!}
{125}{}{„Tiefenreinigung“-Modus wird aktiviert.}
{126}{}{Soll ich den Schädel dieses Primaten neben Ihre anderen Trophäen stellen, Mr. McClennan?}
{127}{}{Soll ich dem Eindringling Knoblauch oder Senfsauce servieren, Mrs. McClennan?}
