{100}{}{Das ist Neon Gangster.}
{101}{}{Du siehst einen Banditen, bekannt als Neon Gangster.}

{110}{}{Mein Motto lautet: „Lebe strahlend und sterbe strahlend!“}
{111}{}{Mach dich bereit, in dieser Lichtshow zum Schatten zu werden!}
{112}{}{Das Licht von Vegas, in mir wiedergeboren, wird dich zu Asche verbrennen!}
{113}{}{Diese Stadt wird vor Angst erzittern, wenn sie meinen Namen hört. Das nenne ich eine „strahlende Persönlichkeit“!}
{114}{}{Du willst mich schlagen? Das ist, als würdest du versuchen, die Sonne zu treffen!}
{115}{}{Der Mond wird deinen Körper nachts am Straßenrand beleuchten.}
{116}{}{Meine Waffe wurde geschaffen, um Recht und Ordnung durchzusetzen. Ich setze damit Chaos durch.}
{117}{}{Ich hasse es, Feiglinge zu töten. Also musst du dich tapfer zeigen, komm schon!}
{118}{}{Weißt du, was ein „homozentrischer Lichtstrahl“ ist? Das wirst du gleich erfahren ...}
{119}{}{Ganz einfach: Du wirst durch die stimulierte Emission eines optischen Quantengenerators getötet.}
