{100}{}{Ein Kannibalenjäger.}
{101}{}{Ein Jäger vom Stamm der Coyote. Er jagt dich und andere Tiere aus der Außenwelt.}

{110}{}{Frissssches Fleisssch!}
{111}{}{Knochen und Fleisssch!}
{112}{}{Außenssseiter wird ssssterben!}
{113}{}{Ich werde meine Familie mit dir ernähren!}
{114}{}{Der hier wehrt sich!}
{115}{}{Gute Beute!}
{116}{}{Die Wilden aus der Außenwelt werden immer appetitlicher!}
{117}{}{Schnappt euch den Wilden!}
{118}{}{Ihr Wilden seid nur zum Essen gut!}
{119}{}{Ein neues Opfer für den Gott der Windmühlen!}
