{100}{}{Du siehst einen Punk.} 
{101}{}{Du siehst einen Punk mit sehr aggressivem Verhalten. Er scheint unter Drogeneinfluss zu stehen.}

{110}{}{Ich werde auf deinem Grab tanzen!}
{111}{}{Wir, die Kokainschnupfer von Salt Lake, gegen die Säufer von Las Vegas!}
{112}{}{Ich lebe in einer Plastikwelt und esse Plastikflocken.}
{113}{}{Wenn die Leute mich nicht mögen, mag ich die Leute auch nicht.}
{114}{}{Ich kämpfe gegen das System ... Eigentlich nicht, ich kämpfe einfach nur.}
{115}{}{Ich finde, alle Leute aus der Nachbarschaft sähen mit einem Loch im Kopf besser aus.}
{116}{}{Ich bin 18, also kann ich „Leck mich!“ sagen.}
{117}{}{Hey, sieh mal! Als hätte der Teufel hier hingeschissen!}
{118}{}{Ich fick das System! Und du bist der Anfang!}
{119}{}{Wir häuten dich lebendig für eine Flasche Bier.}
