{100}{}{Du siehst eine zwielichtig aussehende Person.}
{101}{}{Du siehst einen Raider.}

{200}{}{Du bist auf unserem Gebiet. Jetzt wirst du sterben!}
{201}{}{Wie kannst du es wagen, unangekündigt hier aufzutauchen!}
{202}{}{Stirb, Stadtmensch!}
{203}{}{Dein Tod bringt mir ein bisschen Geld ein.}
{204}{}{Knie vor mir nieder, du Wicht!}
{205}{}{Ihr wisst, was zu tun ist, Gentlemen.}
{206}{}{Keine Zeugen.}
{207}{}{Deck mich!}
{208}{}{Keine Gnade!}
{209}{}{Der Mann sagt: keine Überlebenden.}
{210}{}{Der Boss sagt, Betreten verboten.}
{211}{}{Holen wir uns unser Geld!}