{100}{}{Du siehst einen Hinterwäldler.}
{101}{}{Du siehst einen Hinterwäldler, der aus Verzweiflung den Weg des Raubes und Einbruchs eingeschlagen hat.}

{110}{}{Halt! Das ist ein Überfall!}
{111}{}{Wag ja keinen Widerstand, sonst ... Sonst!..}
{112}{}{Ich will niemanden töten ... aber ich muss!}
{113}{}{Ich muss jemanden töten, um meine Familie zu ernähren!}
{114}{}{Sei nicht gierig, teil mit den Armen, du reicher Mistkerl!}
{115}{}{Du gibst dich arm, aber deine weichen Hände verraten dich!}
{116}{}{Ich rieche reichen Abschaum wie dich schon von Weitem!}
{117}{}{Geld! Sofort!}
{118}{}{Dieses Jahr lief schlecht. Du gleichst die Verluste aus.}
{119}{}{Ich rackere mich nicht von morgens bis abends ab, während Leute mit dicken Geldbeuteln an mir vorbeigehen.}