{100}{}{Du siehst einen Gefangenen.}
{101}{}{Du siehst einen übel zugerichteten Gefangenen.}

{102}{}{H-hilf mir! B-bitte! Lass mich nicht hier!}
{103}{}{Ich bin ü-übel verletzt ... Ich halte nicht mehr lange durch ... Hast du ein stimpak oder so etwas?}

{104}{}{Danke, Freund! Ich kehre in die Stadt zurück und erzähle allen von demjenigen, der mich gerettet hat.}
{105}{}{Wie bist du hier gelandet?}
{106}{}{Was hat Harrelson dir angetan?}
{107}{}{Was weißt du über Harrelson?}
{108}{}{Tschüss.}

{109}{}{Ich komme aus Salt Lake. Als ich meinen Job verlor, rieten mir die Quok-Brüder, hierherzukommen. Sie sagten: „Hier gibt es einen gebrechlichen alten Mann mit wertvollem Besitz.“ Und ich biss an. Am Eingang tappte ich in die Falle, dann machte Harrelson mich in der Höhle fertig.}
{110}{}{Mit ihm war es verdammt unheimlich. Eigentlich schien er nichts zu tun, aber er ging mir so auf die Nerven, dass ich fast den Verstand verlor! Manchmal setzte er sich mit ruhigem Gesicht neben mich und schimpfte über mein Wesen. Dieser Hurensohn! Er schaute mir direkt in die Seele ... Ich bin froh, dass er tot ist!}
{111}{}{Dieser Bastard ist hundert Jahre alt. Er hat den Atomkrieg überlebt. Er erzählte nicht viel über sich, aber ich fragte auch nicht. Ich wollte nur hier weg.}

#Æåíñêèå ğåïëèêè
{1104}{}{Danke, Freund! Ich kehre in die Stadt zurück und erzähle allen von demjenigen, der mich gerettet hat.}