{100}{}{Die hier erzielen auf dem Markt einen guten Preis.}
{101}{}{Versuch, die Ware nicht zu beschädigen.}
{102}{}{Du wirst ein widerspenstiger Sklave sein.}
{103}{}{Das ist nicht gut.}
{104}{}{Rückzug!}
{105}{}{Vielleicht verkaufe ich stattdessen Möbel.}
{106}{}{Sklavenhändler sollten einander nicht angreifen.}
{107}{}{Die Gilde wird davon erfahren!}
{108}{}{Was macht ihr?}
{109}{}{Irgendein Glück gehabt?}
{110}{}{Gute Sklaven gefunden?}
{111}{}{Wir suchen neue Ware.}
{112}{}{Das ist unser Gebiet.}