{100}{}{Ein sehr tiefes Loch. Es stinkt noch immer stark nach Exkrementen, aber es pocht nicht mehr.}
{101}{}{Du siehst gleich etwas, das jedem gesunden Menschenverstand widerspricht! Man kann nicht erkennen, ob es lebt oder nicht, aber es pulsiert und stößt giftige Dämpfe aus.}
{102}{}{Das bewirkt nichts.}
{103}{}{Das Loch pulsiert und stößt giftige Dämpfe aus. Da willst du nicht hineingehen.}
{104}{}{Wenn du in dieses stinkende Loch hinabsteigen willst, brauchst du ein Seil, um nach unten zu kommen.}
{105}{}{Du hast bereits ein Seil in dieses Loch hinabgelassen. Du brauchst kein weiteres.}
{106}{}{Das Seil ist befestigt und hinabgelassen.}
{107}{}{Es ist immer noch zu gefährlich, dort hinunterzugehen ... Und warum solltest du das überhaupt wollen? Komm zur Vernunft!}