{100}{}{Du siehst ein Monster.}
{101}{}{Du siehst einen hässlichen Mutanten. Er scheint aus der Verschmelzung mehrerer Menschen und Hunde entstanden zu sein.}
{102}{}{Wir ... sehen ... Licht ...}

{110}{}{Lange kein Abendessen mit den Gästen mehr gehabt!}
{111}{}{Wir rächen die Welpen!}
{112}{}{In einer Sache hatte der Meister recht!}
{113}{}{Wir hassen Menschlinge!}
{114}{}{Der Meister wird die Menschheit verschlingen, so wie er uns verschlungen hat!}
{115}{}{Niemand entgeht der Vergeltung des Meisters!}
{116}{}{Verflucht sei der Meister für das, was er uns angetan hat!}
{117}{}{Tötet uns!}
{118}{}{Wir hören eure Gedanken!}
