{100}{}{Du siehst einen schmutzigen, unrasierten Mann.}
{200}{}{Du siehst eine schmutzige, abgerackerte Frau.}
{101}{}{Fallensteller.}
{102}{}{Komm ihm besser nicht zu nahe. Vielleicht suchen ein paar Insekten in seiner Kleidung ein saubereres Zuhause.}
{103}{}{Hallo. Hier im Fallenstellergebiet trifft man nicht viele Leute. Was willst du?}
{104}{}{Hast du Geckofelle zu verkaufen?}
{105}{}{Ich bin nur auf der Durchreise.}
{106}{}{}
{107}{}{Nun, ich schätze, ich könnte dir meine Felle verkaufen. Dann muss ich nicht extra in die Stadt fahren.}
{108}{}{Was hast du?}
{109}{}{Schon gut.}
{110}{}{}
{111}{}{Hier ist, was ich habe:}
{112}{}{normale Geckofelle.}
{113}{}{goldene Geckofelle.}
{114}{}{Ich nehme alle, die du hast.}
{115}{}{Vielleicht ein andermal. Tschüss.}
{116}{}{War nett, mit dir Geschäfte zu machen. Man sieht sich.}
{117}{}{Tschüss.}
{118}{}{}
{119}{}{}
{120}{}{Sieht aus, als wärst du knapp bei Kasse. Pass auf, ich bin schon SEHR lange in diesen Wäldern unterwegs, wenn du verstehst, was ich meine. Ich mache es dir lohnenswert.}
{121}{}{Klar.}
{122}{}{Keine Chance. Mach's gut.}
{123}{}{}
{124}{}{}
{125}{}{[Du fühlst dich gleich in mehr als einer Hinsicht schmutzig – aber du hast ein paar Gecko-Felle bekommen.]}
{126}{}{Tschüss.}
{127}{}{[Er hebt die rechte Hand und sagt] Ich. Mächtiger Fallensteller. Jage große Geckos. Ich nicht böse gemeint, dein Land betreten. Gehe friedlich. [Er überreicht dir ein Gecko-Fell als Geschenk.]}
{128}{}{[ENDE]}
{129}{}{Ich habe nichts mehr mit dir zu bereden.}
{130}{}{Du Feigling!}
{131}{}{Das ist mein Jagdgebiet. Verschwinde!}
{132}{}{Ich ziehe dir bei lebendigem Leib die Haut ab!}
{133}{}{Ich mache deinen Kopf zu einer Trophäe.}

{134}{}{Ein gewöhnliches Gecko-Fell: $}
{135}{}{Ein goldenes Gecko-Fell: $}

{136}{}{Na gut, Mann. Du hast gewonnen.}
{137}{}{Zum Glück muss ich meine Fallen überprüfen.}
{138}{}{Ich glaube, ich höre Mama rufen.}

#Æåíñêèé âàðèàíò.
{10102}{}{Komm ihm besser nicht zu nahe. Vielleicht suchen ein paar Insekten in seiner Kleidung ein saubereres Zuhause.}
{10136}{}{Na gut, Lady. Du hast gewonnen.}
{10137}{}{Zum Glück muss ich meine Fallen überprüfen.}
{10138}{}{Ich glaube, ich höre Mama rufen.}
