{100}{}{Du siehst einen Nomaden.}
{101}{}{Du siehst einen erfahrenen Nomaden aus Great Basin.}

{110}{}{[Runzelt die Stirn, als er dich sieht] Du solltest nicht so nahe kommen. Es ist schon heiß genug hier drin.}
{111}{}{[Sieht dich neugierig an] Hallo! Bist du auch auf Reisen?}
{112}{}{[Blickt dich ausdruckslos an] Bist du nur auf Reisen? Oder fliehst du vor jemandem?}

{113}{}{Ich möchte Vorräte für die Reise kaufen. Kannst du mir etwas davon tauschen?}
{114}{}{Ich frage mich, was Leute wie du in diesen unbewohnten Gegenden machen.}
{115}{}{Ich bin schon eine Weile unterwegs. Sag mal, wo ist die nächste Stadt?}
{116}{}{Ich sollte meine Reise wohl fortsetzen. Leb wohl.}
{117}{}{Das ist alles, was ich tauschen kann. Wenn das nicht reicht, musst du in die Stadt gehen.}
{118}{}{Apropos Stadt. Sag mal, wo finde ich eine?}
{119}{}{Wir ziehen von Tal zu Tal und suchen nach einem geeigneten Ort zum Leben. Wir stammen aus dem Nordosten. Dort gab es eine Reihe von Kriegen, weshalb viele von dort geflohen sind. Du wirst sicher andere Nomaden wie uns treffen.}
{120}{}{Salt Lake liegt im Norden. Folge der Highway, und du gelangst direkt in die Stadt nahe einem großen See.}