{100}{}{Ich muss sergeant Graves warnen!}
{101}{}{Ich muss die Stadtwachen warnen!}

{102}{}{Abschaum von außerhalb ...}
{103}{}{Degeneriertes Gesindel ...}
{104}{}{Stirb, Fremder!}

{110}{}{Können wir Ihnen helfen, Bürger?}
{111}{}{Seien Sie gegrüßt, Bürger. Schön, Sie zu sehen.}
{112}{}{Wir hatten Sorge, dass Sie verletzt sein könnten, Bürger.}
{113}{}{In diesen Teilen des Ödlands müssen Sie wachsam bleiben. Passen Sie auf den Straßen auf, Bürger.}
{114}{}{Das war's? Nicht gerade der beste Rat, den Sie mir geben können.}

{120}{}{Ich brauche medizinische Hilfe!}
{121}{}{Könnten Sie mich zum Vault begleiten?}
{122}{}{Könnten Sie mich nach Gerlach begleiten?}
{123}{}{Könnten Sie mich nach Black Rock begleiten?}
{124}{}{Gibt es Neuigkeiten von den letzten Patrouillen?}
{125}{}{}
{126}{}{Ich mache mich dann auf den Weg.}
{127}{}{Können Sie mir einen Rat geben, wie ich in den Ödlanden überlebe?}
{128}{}{Nur einen: Halte dich von Highways fern. Querfeldein dauert es vielleicht länger, ist aber sicherer – man trifft seltener auf Leute.}

#Ëå÷åíèå
{129}{}{Sie haben keine ernsthaften Verletzungen. Wenn Sie sich nicht wohlfühlen, wird der Arzt im Vault Ihnen helfen.}
{130}{}{Halten Sie durch, Bürger, wir helfen Ihnen!}
{131}{}{[Warten]}
{132}{}{Jetzt sollte es Ihnen besser gehen.}
{133}{}{Danke.}

#Ïåğåìåùåíèå â ïîñåëåíèÿ
{134}{}{Ja, natürlich.}
{135}{}{Dann brechen wir auf!}
{136}{}{Ich glaube, ich gehe lieber ohne Sie.}
{137}{}{Ja, natürlich. Wir begleiten Sie und setzen Sie in der Nähe der Stadt ab.}
{138}{}{Ja, natürlich. Wir begleiten Sie und setzen Sie in der Nähe der Stadt ab.}

#Î ïàòğóëèğîâàíèè
{140}{}{Es ist gefährlich, ohne Schutz allein durch diese Gegend zu reisen.}
{141}{}{Das ist ein sicherer Ort, hier trifft man nicht allzu oft Fremde. Meistens sind es Einzelgänger – Flüchtige oder Schatzsucher.}

{142}{}{Die Plünderer im Südosten sind in letzter Zeit sehr aktiv. Das ist eindeutig kein gutes Zeichen.}
{143}{}{Wir treffen heutzutage nur noch selten auf Plünderer. Es scheint, als hielte irgendetwas sie vom Südosten fern.}

{144}{}{Wir haben seit Langem niemanden mehr aus Gerlach gesehen. Kein Rauch, keine Feuer. Es scheint, als hätten die Leute dieses Land verlassen. Das sind gute Nachrichten.}
{145}{}{Vor nicht allzu langer Zeit haben wir einen Zug Richtung Osten fahren sehen.}
{146}{}{Außerdem hat irgendein Bastard }
{147}{}{unsere Leute auf Patrouille umgebracht. Ich weiß nicht, wer es war, aber er ist verdammt zäh.}
{148}{}{}

{149}{}{ Ich habe dir nichts weiter zu sagen.}
{150}{}{}
