{100}{}{Du siehst einen jungen Soldaten.}
{101}{}{Du siehst einen Rekruten vom Wind des Krieges. Es ist offensichtlich, dass ihm seine Aufgaben nicht besonders gefallen.}

#Î'âå'íûå ğåïëèêè, êîãäà åùå íè îäèí èç ğåéäåğîâ íå óáè':
{110}{}{Jetzt nicht! Sie sind noch in der Nähe!}
{111}{}{Es ist gefährlich! In Deckung!}
{112}{}{Hey, du bist keiner von diesen Plünderern! Wenn du nicht helfen kannst, geh mir nicht auf die Nerven!}
{113}{}{Keine Zeit für Erklärungen, die Feinde sind überall!}
{114}{}{Hey, hast du eine Waffe? Dann verteidige dein Leben!}

#Ğàçãîâîğ, êîãäà ğåéäåğû óáè'û, íî íå ñèëàìè ÃÃ:
{120}{}{Puh ... [Atmet schwer, fasst sich an die Brust und setzt sich auf den Boden, wobei er sich mit einer Hand abstützt] Hey, du kannst von Glück reden, dass ich dich nicht für einen Plünderer gehalten habe, sonst würdest du wie die anderen tot am Boden liegen.}
{121}{}{Ja, klar. Wie auch immer, was ist passiert?}
{122}{}{Wir waren zu dritt auf Patrouille, als die Plünderer uns überfielen. Ich habe mich schnell gewehrt und bin weggelaufen, aber sie haben mich weiter verfolgt. Verdammt, noch ein bisschen länger und ich wäre gegrillt gewesen.}
{123}{}{Hmm. Zeig mir dein Magazin ... Oh, verstehe.}

{124}{}{Verdammt, weil ich ein Rekrut bin, haben sie mir nur wenig Munition gegeben. Was haben die sich dabei gedacht, verdammt! Und du? Du könntest wenigstens helfen!}
{125}{}{Ich muss mit der Munition haushalten, ha-ha.}
{126}{}{Tut mir leid, es fiel mir schwer zu verstehen, was hier vor sich geht.}
{127}{}{Ach wirklich? Na dann, sei nicht sauer, wenn dich jemand *aus Versehen* aus dem Wind des Krieges in den Hintern tritt. Und jetzt muss ich zu meinen Waffenbrüdern und ihnen die ganze Geschichte erzählen. Geh du deinen eigenen Weg, Wanderer.}
{128}{}{Ja.}
{129}{}{Wirklich? Hmm. Klingt plausibel. Jedenfalls sollte ich jetzt zu meinen Waffenbrüdern im Wind des Krieges gehen und ihnen die ganze Geschichte erzählen. Geh du deinen eigenen Weg, Wanderer.}
{130}{}{Warte, kannst du mir zeigen, wo der Wind des Krieges ist?}
{131}{}{Pass auf dich auf.}
{132}{}{Öffne deine Karte. Folge der Straße, dann bieg hier und hier ab. Du wirst die Station sehen, an der die Karawanen halten. Dort sind Besucher wie du willkommen. Ich muss jetzt los.}
{133}{}{Danke.}
{134}{}{Du hast die Koordinaten des Windes des Krieges erhalten.}

#Ğàçãîâîğ, êîãäà ğåéäåğû óáè'û âñå èëè íåêî'îğûå ñèëàìè ÃÃ:
{140}{}{Puh ... [Schwer atmend greift er sich an die Brust und setzt sich auf den Boden, wobei er sich mit einer Hand abstützt] Danke, Wanderer. Ohne dich wäre ich jetzt in der Hölle verbrannt.}
{141}{}{Was ist passiert?}
{142}{}{Ich sehe, deine Munition ist fast aufgebraucht.}
{143}{}{Verdammt, stimmt. Als Neuling habe ich nur sehr wenig Munition bekommen. Was haben die sich dabei gedacht, verdammt noch mal! Gut, dass du da warst.}
{144}{}{Ja ...}
{145}{}{Hör zu, ich gehe zurück zu meinen Waffenbrüdern im Wind des Krieges und erzähle ihnen von deiner Hilfe. Sie werden das bestimmt zu schätzen wissen. Aber jetzt muss ich los. Nochmals danke.}
{146}{}{Pass auf dich auf.}
{147}{}{Deine Hilfe für den Rekruten hat deinen Ruf im Wind des Krieges verbessert.}

#Female character:
{1124}{}{Verdammt, weil ich ein Rekrut bin, haben sie mir nur wenig Munition gegeben. Was haben die sich dabei gedacht, verdammt! Und du? Du könntest wenigstens helfen!}
{1127}{}{Ach wirklich? Na dann, sei nicht sauer, wenn dich jemand *aus Versehen* aus dem Wind des Krieges in den Hintern tritt. Und jetzt muss ich zu meinen Waffenbrüdern und ihnen die ganze Geschichte erzählen. Geh du deinen eigenen Weg, Wanderer.}
{1129}{}{Wirklich? Hmm. Klingt plausibel. Jedenfalls sollte ich jetzt zu meinen Waffenbrüdern im Wind des Krieges gehen und ihnen die ganze Geschichte erzählen. Geh du deinen eigenen Weg, Wanderer.}
{1140}{}{Puh ... [Schwer atmend greift er sich an die Brust und setzt sich auf den Boden, wobei er sich mit einer Hand abstützt] Danke, Wanderer. Ohne dich wäre ich jetzt in der Hölle verbrannt.}
