#Îïèñàíèÿ
{100}{}{Du siehst eine Kapuze.}
{101}{}{Du siehst die Motorhaube eines Lieferwagens.}
{102}{}{Nach den „Reparaturen“ ist es nur noch ein Haufen Metall. Der Besitzer muss wirklich stinksauer sein.}
{103}{}{Trotz des Verschleißes und der ordentlichen Laufleistung wird der Motor seinem Besitzer noch eine Weile dienen.}

#Ğàçíîå
{105}{}{Du kannst während eines Kampfes nicht im Motor herumwühlen.}

#Ğåæèì äèàëîãà
{110}{}{Der Motor schnurrt. Es klingt, als würde er dir Dankesworte zuflüstern.}
{111}{}{Nach den „Reparaturen“ ist es nur noch ein Haufen Metall. Der Besitzer muss wirklich stinksauer sein. Aber ganz verloren ist er noch nicht.}
{112}{}{[Versuchen, den Motor wiederherzustellen]}
{113}{}{Du hebst die Motorhaube an. Der Anblick unzähliger Teile und Kabel löst eine Panikattacke bei dir aus.}
{114}{}{[Versuchen, das Problem herauszufinden]}
{115}{}{[Liegen lassen]}

{116}{}{Es scheint nicht besonders kompliziert zu sein, aber du kannst nicht erkennen, wo das Problem liegt.}
{117}{}{}
{118}{}{Der Motor funktioniert einwandfrei, er braucht nur eine normale Wartung.}
{119}{}{[Wartung durchführen]}
{120}{}{[Nützliche Teile aus dem Motor ausbauen]}
{121}{}{Saubere Arbeit!}
{122}{}{Schon besser.}
{123}{}{Du hast den ganzen brauchbaren Kram auseinandergebaut und den Energieversorgungsregler sowie eine funktionierende Mikro-Fusionszelle mitgenommen. Dem Besitzer wird das wohl nicht gefallen, aber du wusstest doch, worauf du dich einlässt, oder?}
{124}{}{Ganz genau.}
{125}{}{Das Auto fährt nicht ohne Energie und die Teile, die du so dreist geklaut hast.}
{126}{}{[Wartung durchführen]}
