{100}{}{Was für ein schöner Ort! Du verspürst den Drang, deinen Helm abzunehmen und die frische Luft einzuatmen ...}
{101}{}{Du trittst versehentlich auf eine Art Sporenpilz. Er platzt und setzt eine Sporenwolke frei.}
{102}{}{Oh ... Ich bin so müde ...}
{103}{}{Ich ... kann ... nicht ... mehr ...}
{104}{}{Dein Bewusstsein schwindet und du gleitest in den süßen, sehnlichst herbeigewünschten Schlaf. Doch als du aufwachst, bist du entsetzt ...}
{105}{}{Dieser Ort scheint wohl doch nicht so schön zu sein, wie es zunächst den Anschein hatte.}
