{100}{}{Dein Kopf dröhnt höllisch. Es sieht aus, als hätte sich während deiner Bewusstlosigkeit etwas in dieser Höhle verändert.}
{101}{}{Der Universelle Geist muss deine Bitten erhört und einen Durchgang geöffnet haben, den du allein niemals hättest öffnen können.}
{102}{}{Oh!}
{103}{}{Langsam wird dir endlich alles klarer.}
{104}{}{Verdammt! Ich war so nah dran!}
{105}{}{Dein Bewusstsein versinkt erneut in der Dunkelheit.}
{106}{}{Etwas scheint klarer zu werden ...}
{107}{}{Verdammt! Ich war so nah dran!}

{110}{}{Was? Aufseher?}
{111}{}{Hä? Wer ist da?}
{112}{}{Aufseher! Ich bin's!}
{113}{}{... So dunkel ...}
{114}{}{Was?}
{115}{}{... Verschwende keine Zeit!}
{116}{}{Mein Körper verrottet ... Ich sterbe ...}
{117}{}{Es ist unerträglich! Töte mich!}
{118}{}{Nur der Tod ...}
{119}{}{... Tod ...}
