{100}{}{Du siehst einen Roboter.}
{101}{}{Du siehst einen Roboter. Du hast das Gefühl, dass er feindselig sein könnte.}
{102}{}{Willkommen.}

#Âûêğèêè ïğè íàïàäåíèè
{110}{}{Alarm! Eindringling in Sicht!}
{111}{}{Sicherheitssysteme aktivieren!}
{112}{}{Protokoll zur Beseitigung von Eindringlingen wird aktiviert! Wird ausgeführt.}

#Ïîïûòêà çàãîâîğèòü
{120}{}{Willkommen im Kraftwerk "Poseidon Oil"! Bitte stören Sie nicht die öffentliche Ordnung und halten Sie das Gelände sauber.}
{121}{}{Wir entschuldigen uns für die entstandenen Unannehmlichkeiten. Wir hoffen, dass sich ein solcher Vorfall nicht wiederholt.}
{122}{}{Willkommen, Besucher.}
{123}{}{Willkommen, Besucher. Wir freuen uns immer, dich zu sehen.}

#Ïîïûòêà îòêëş÷åíèÿ
{130}{}{Der Roboter ist deaktiviert.}
{131}{}{Mit dem ist es aus.}

{132}{}{Du verstehst die Systeme des Roboters nicht und erregst nur unerwünschte Aufmerksamkeit.}
{133}{}{Unbefugtes Personal sollte das nicht tun.}
{134}{}{Zwing mich nicht, Gewalt anzuwenden.}
{135}{}{Eindringling entdeckt! Sofort eliminieren!}

{136}{}{Deine Reparaturfähigkeit reicht nicht aus, um den Roboter erfolgreich zu deaktivieren.}
