#############################################################
#  Message File: Generic.msg                                #
#                                                           #
#  Note: Characters within curly braces (like line 100)     #
#        will be read in as a message string. Caution       #
#        should be used when making comments. All comments  #
#        should be prepended with a pound symbol for        #
#        visual ease. This does not comment out the line    #
#        though.                                            #
#                                                           #
#  Purpose: This message file contains the information      #
#           concerning doors in a locked state, trapped     #
#           state, locked and trapped state.                #
#                                                           #
#  Log: Please note any changes that have been made to this #
#       file and comment which lines have changed.          #
#                                                           #
#  Created: October 1, 1997                                 #
#                                                           #
#  Updated:                                                 #
#############################################################

#############################################################
#  The following lines are for giving out experience points #
#  to the player.                                           #
#############################################################

# Player gains [x] of experience points
{100}{}{Du erhältst }
{101}{}{ Erfahrungspunkte.}


#############################################################
#  The following lines are for what the player received     #
#  experience for (ie, picking a lock, disarming traps).    #
#############################################################
{102}{}{Du entschärfst die Falle erfolgreich.}
{103}{}{Du schaffst es nicht, die Falle zu entschärfen.}
{104}{}{Du löst versehentlich die Falle aus.}

# Prepend Lines with NPC name
{105}{}{ entschärft die Falle erfolgreich.}
{106}{}{ schaffen es nicht, die Falle zu entschärfen.}
{107}{}{ löst versehentlich die Falle aus.}

{200}{}{Danke.}
{201}{}{Guten Tag.}
{202}{}{Danke.}
{203}{}{Danke!}
{204}{}{Nein, danke.}
{205}{}{Nein, danke.}
{206}{}{Klar.}
{207}{}{Ja.}
{208}{}{Nein.}
{209}{}{In Ordnung.}

#############################################################
#  The following lines are generic noises that the player   #
#  makes when he/she has a low i.q. level.                  #
#############################################################
{300}{}{Ug.}
{301}{}{Og.}
{302}{}{Ooga.}
{303}{}{Urg.}

#############################################################
#  The following lines are generic non-spoken dialogs       #
#############################################################
{350}{}{[ENDE]}
{351}{}{[TSCHÜSS]}
{352}{}{[WEITER]}
{353}{}{[FORTFAHREN]}
{354}{}{[KAMPF]}
{355}{}{[GELD GEBEN]}

#############################################################
#  The following lines are generic departure dialogs        #
#############################################################
{375}{}{Tschüss.}
{376}{}{Auf Wiedersehen.}

#############################################################
#  The following lines are for special events in the        #
#  dude_obj                                                 #
#############################################################

{450}{}{Die Luft ist rein. Los, wir gehen!}

#############################################################
#  The following lines are for Miscellaneous things needed  #
#  throughout the game.                                     #
#############################################################

{900}{}{Die alte, abgenutzte Tür sieht aus, als könnte man sie mit einem gut platzierten Sprengsatz zerstören.}
{901}{}{Du siehst den Sklavenkarren, der die Sklaven zurück nach Den bringen soll.}

{905}{}{Wuff! Wuff!}

{910}{}{Du bekommst einen Schock vom elektrifizierten Boden.}
{911}{}{ bekommt einen Schock vom elektrifizierten Boden.}
{912}{}{Der Strom fällt auf null und steigt dann wieder auf 50%, als die Notstromgeneratoren anspringen.}
{913}{}{Ein leises Summen ist zu hören, als der Strom wieder durch die Basis fließt.}

{920}{}{Du stößt auf die Überreste von Nagor, der beim Versuch starb, seinen Hund zu retten.}
{921}{}{Nagor starb, als er versuchte, den Körper seines Hundes zurück ins Dorf zu schleppen.}

{930}{}{Hoooooowl!}

{950}{}{Du nimmst dir etwas Zeit, um ein paar Manöver zu üben. Deine waffenlosen Kampffertigkeiten steigen um 5%.}

{951}{}{Die kämpfende Maulwurfsratte setzt zum tödlichen Schlag an.}
{952}{}{Der Kampf ist vorbei.}

#############################################################
#  These are for converting numeric values to number words. #
#  You want it to go further, add 'em yourself.             #
#############################################################
{2000}{}{null}
{2001}{}{eins}
{2002}{}{zwei}
{2003}{}{drei}
{2004}{}{vier}
{2005}{}{fünf}
{2006}{}{sechs}
{2007}{}{sieben}
{2008}{}{acht}
{2009}{}{neun}
{2010}{}{zehn}
{2011}{}{elf}
{2012}{}{zwölf}
{2013}{}{dreizehn}
{2014}{}{vierzehn}
{2015}{}{fünfzehn}
{2016}{}{sechzehn}
{2017}{}{siebzehn}
{2018}{}{achtzehn}
{2019}{}{neunzehn}
{21020}{}{zwanzig}
{2021}{}{einundzwanzig}
{2022}{}{zweiundzwanzig}
{2023}{}{dreiundzwanzig}
{2024}{}{vierundzwanzig}
{2025}{}{fünfundzwanzig}
{2026}{}{sechsundzwanzig}
{2027}{}{siebenundzwanzig}
{2028}{}{achtundzwanzig}
{2029}{}{neunundzwanzig}
{2030}{}{dreißig}
{2031}{}{einunddreißig}
{2032}{}{zweiunddreißig}
{2033}{}{dreiunddreißig}
{2034}{}{vierunddreißig}
{2035}{}{fünfunddreißig}
{2036}{}{sechsunddreißig}
{2037}{}{siebenunddreißig}
{2038}{}{achtunddreißig}
{2039}{}{neununddreißig}
{2040}{}{vierzig}
{2041}{}{einundvierzig}
{2042}{}{zweiundvierzig}
{2043}{}{dreiundvierzig}
{2044}{}{vierundvierzig}
{2045}{}{fünfundvierzig}
{2046}{}{sechsundvierzig}
{2047}{}{siebenundvierzig}
{2048}{}{achtundvierzig}
{2049}{}{neunundvierzig}
{2050}{}{fünfzig}
{2051}{}{einundfünfzig}
{2052}{}{zweiundfünfzig}
{2053}{}{dreiundfünfzig}
{2054}{}{vierundfünfzig}
{2055}{}{fünfundfünfzig}
{2056}{}{sechsundfünfzig}
{2057}{}{siebenundfünfzig}
{2058}{}{achtundfünfzig}
{2059}{}{neunundfünfzig}
{2060}{}{sechzig}
{2061}{}{einundsechzig}
{2062}{}{zweiundsechzig}
{2063}{}{dreiundsechzig}
{2064}{}{vierundsechzig}
{2065}{}{fünfundsechzig}
{2066}{}{sechsundsechzig}
{2067}{}{siebenundsechzig}
{2068}{}{achtundsechzig}
{2069}{}{neunundsechzig}
{2070}{}{siebzig}
{2071}{}{einundsiebzig}
{2072}{}{zweiundsiebzig}
{2073}{}{dreiundsiebzig}
{2074}{}{vierundsiebzig}
{2075}{}{fünfundsiebzig}
{2076}{}{sechsundsiebzig}
{2077}{}{siebenundsiebzig}
{2078}{}{achtundsiebzig}
{2079}{}{neunundsiebzig}
{2080}{}{achtzig}
{2081}{}{einundachtzig}
{2082}{}{zweiundachtzig}
{2083}{}{dreiundachtzig}
{2084}{}{vierundachtzig}
{2085}{}{fünfundachtzig}
{2086}{}{sechsundachtzig}
{2087}{}{siebenundachtzig}
{2088}{}{achtundachtzig}
{2089}{}{neunundachtzig}
{2090}{}{neunzig}
{2091}{}{einundneunzig}
{2092}{}{zweiundneunzig}
{2093}{}{dreiundneunzig}
{2094}{}{vierundneunzig}
{2095}{}{fünfundneunzig}
{2096}{}{sechsundneunzig}
{2097}{}{siebenundneunzig}
{2098}{}{achtundneunzig}
{2099}{}{neunundneunzig}
{2100}{}{einhundert}

#############################################################
#  These are generic Reactions to the player's actions in   #
#  the game to other NPC's. NPC's float these lines.        #
#############################################################

######
#  Caught Pickpocketing (Warning)  (3000-3299)
######

# Tough Guard (3000-3024)
{3000}{}{}

# Guard (3025-3049)
{3025}{}{}

# Tough Citizen (3050-3074)
{3050}{}{Versuch das noch mal, und ich muss dich töten.}
{3051}{}{Ich hab nichts, was man klauen könnte, du Idiot.}
{3052}{}{Ich glaube nicht, dass wir uns *so* gut kennen.}
{3053}{}{Fass das noch mal an, und du wirst dafür bezahlen.}
{3054}{}{Nimm deine Hände von mir.}
{3055}{}{Mach das noch mal, und ich reiß dir den Kopf ab.}
{3056}{}{Finger weg!}
{3057}{}{Suchst du Ärger?}
{3058}{}{Fass mich noch mal an, und du bist tot.}
{3059}{}{Nur Ärger gibt's umsonst.}
{3060}{}{Hey! Halt dich zurück.}
{3061}{}{Pass auf!}
{3062}{}{Willst du sterben?}
{3063}{}{Versuch das noch mal, und ich schlag dir den Schädel ein.}
{3064}{}{Das gehört mir; Finger weg!}

# Citizen (3075-3099)
{3075}{}{}

# Custom (3100-3299)
{3100}{}{}

######
#  Caught Stealing from Something (Warning)   (3300-3599)
######

# Tough Guard (3300-3324)
{3300}{}{}

# Guard (3325-3349)
{3325}{}{Warum legst du nicht einfach alles wieder genau dorthin zurück, wo du es gefunden hast?}
{3326}{}{Weißt du, es ist nicht nett, etwas zu nehmen, das dir nicht gehört.}
{3327}{}{Weg da, Rotzlöffel!}
{3328}{}{Erzähl mir jetzt nicht, du würdest „nur deine Schlüssel suchen“. Verschwinde!}
{3329}{}{Wonach du auch suchst, hier ist es nicht. Verstanden?}

# Tough Citizen (3350-3374)
{3350}{}{}

# Citizen (3375-3399)
{3375}{}{}

# Custom (3400-3599)
{3400}{}{}

######
#  Caught Lockpicking Door (Warning)   (3600-3899)
######

# Tough Guard (3600-3624)
{3600}{}{}

# Guard (3625-3649)
{3625}{}{Hey, du! Was hast du da zu suchen?}
{3626}{}{Wenn du keinen Schlüssel in der Hand hast, solltest du dich besser entfernen.}
{3627}{}{Das ist nicht ohne Grund abgeschlossen, Rotzlöffel.}
{3628}{}{Lass das, bevor es Ärger gibt!}

# Tough Citizen (3650-3674)
{3650}{}{}

# Citizen (3675-3699)
{3675}{}{}

# Custom (3700-3899)
{3700}{}{}

######
#  Caught Sneaking (Warning)    (3900-4199)
######

# Tough Guard (3900-3925)
{3900}{}{}

# Guard (3925-3949)
{3925}{}{Hey, du! Was machst du da?}
{3926}{}{Du solltest nicht hier sein!}
{3927}{}{Wenn du glaubst, du kannst einfach an mir vorbeigehen, vergiss es!}
{3928}{}{Du solltest besser nicht vorhaben, was ich glaube, dass du vorhast, Fremder.}
{3929}{}{Was? Glaubst du etwa, ich merke dich nicht? Verschwinde!}

# Tough Citizen (3950-3974)
{3950}{}{}

# Citizen (3975-3999)
{3975}{}{}

# Custom (4000-4199)
{4000}{}{}

######
#  Being Attacked by the player (Warning)    (4200-4499)
######

# Tough Guard (4200-4225)
{4200}{}{}

# Guard (4225-4249)
{4225}{}{}

# Tough Citizen (4250-4274)
{4250}{}{}

# Citizen (4275-4299)
{4275}{}{}

# Custom (4300-4499)
{4300}{}{}

######
#  Call for Help Guards  (4500-4799)
######

# Tough Guard (4500-4525)
{4500}{}{}

# Guard (4525-4549)
{4525}{}{}

# Tough Citizen (4550-4574)
{4550}{}{}

# Citizen (4575-4599)
{4575}{}{}

# Custom (4600-4799)
{4600}{}{}

######
# Call for Help Others    (4800-5099)
######

# Tough Guard (4800-4825)
{4800}{}{}

# Guard (4825-4849)
{4825}{}{}

# Tough Citizen (4850-4874)
{4850}{}{}

# Citizen (4875-4899)
{4875}{}{}

# Custom (4900-5099)
{4900}{}{}

######
#  Attack Player  [War Cries]   (5100-5399)
######

# Tough Guard (5100-5125)
{5100}{}{}

# Guard (5125-5149)
{5125}{}{}

# Tough Citizen (5150-5174)
{5150}{}{}

# Citizen (5175-5199)
{5175}{}{}

# Custom (5200-5399)
{5200}{}{}

# Watched Comments(5400-5599)
{5400}{}{Bleib da weg.}

# For Repair Bots
{9000}{}{Reparaturen abgeschlossen.}
{9001}{}{Bewaffnung abgeschlossen.}
{9002}{}{Strukturschäden werden repariert.}

# default options for party members
{10000}{}{Sag mir mal was.}
{10001}{}{Du solltest dich jetzt heilen.}
{10002}{}{Ich brauche dich hier, bis ich zurückkomme.}
{10003}{}{Steck deine Waffe weg.}
{10004}{}{Bleib in meiner Nähe.}
{10005}{}{Entferne dich nicht zu weit.}
{10006}{}{Wir sollten uns ein wenig verteilen.}
{10007}{}{Das war's fürs Erste.}
{10008}{}{Wir müssen unseren Abstand zueinander ändern.}
{10009}{}{Ich muss mit dir über deine Ausrüstung sprechen.}
{10010}{}{Andererseits denke ich, dieser Abstand ist fürs Erste in Ordnung.}
{10011}{}{Eigentlich gibt es wohl nichts, was ich über deine Ausrüstung wissen müsste.}
{10012}{}{Ich brauche dich, damit du die Rüstung ablegst, die du gerade trägst.}
{10013}{}{Ich muss wissen, welche Waffen du benutzen kannst.}

# default join me again message
{10100}{}{Los geht's.}