{100}{}{Du siehst das Sicherheits-Terminal.}
{101}{}{Du siehst das Terminal zur Steuerung des Sicherheitssystems der Station.}
{102}{}{Zum Aktivieren des Terminals sind wissenschaftliche Kenntnisse erforderlich.}

{103}{}{Du hast das Sicherheitssystem bereits deaktiviert.}
{104}{}{Das funktioniert nicht.}
{105}{}{Du hast das Sicherheitssystem gehackt und deaktiviert.}
{106}{}{Deine wissenschaftlichen Kenntnisse reichen nicht aus, um dieses Terminal zu hacken.}
{107}{}{Das kann ich nicht.}
{108}{}{Schon besser!}
{109}{}{Diesmal ist es dir nicht gelungen, das Sicherheitssystem zu hacken.}
{110}{}{Fehlgeschlagen.}
{111}{}{}
{112}{}{Das Sicherheitssystem reagiert nicht.}
{113}{}{Kein Signal.}