#Êîìï â ÀİÑ - ÷àñòü ïåğâàÿ
{100}{}{Du siehst ein funktionierendes Terminal.}
{101}{}{Du siehst ein Reaktorsteuerterminal.}

#Ïğèìåíåíèå íàğêîòû íà êğèòòåğå, êîòîğûé çà ıòî íàïàäàåò íà ÃÃ:
{126}{}{Das hättest du nicht tun sollen!}
{127}{}{}
{128}{}{Das brauche ich nicht!}
{129}{}{Auf keinen Fall! Das ist verboten.}
{130}{}{Denk nicht einmal daran, es wieder zu tun!}
{131}{}{Wir dürfen das nicht versuchen.}


#Äëÿ êîëà-ïğîäàæ
{150}{}{Du hast einen Handel mit Nuka-Cola abgeschlossen. Glückwunsch!}
{151}{}{Du hast einen neuen Erfolg freigeschaltet.}
{152}{}{Der Nuka-Cola-Verkauf in diesem Geschäft ist nicht mehr gültig.}
{153}{}{Sieht so aus, als würden die Einnahmen dieses Ortes bald stark einbrechen.}

#Êîìï â ÀİÑ - ÷àñòü âòîğàÿ
{160}{}{Du hast es geschafft, in das System einzudringen. Den darin enthaltenen Dokumenten nach zu urteilen, wurde dieses Kraftwerk von der Regierung nicht ausschließlich für friedliche Zwecke genutzt.}
{161}{}{Berichte über die Versorgung mit Uranerz ansehen.}
{162}{}{Projekt für den Radiosender „Lovelock“ ansehen.}
{163}{}{Koordinaten des Radiosenders „Lovelock“ ansehen.}
{164}{}{Fehlerbericht von PoseidonNet ansehen.}
{165}{}{Da Uranerz vom Militär genutzt wurde, unterlagen Abbau und Verteilung strenger staatlicher Kontrolle. Daher musste das Poseidon Oil-Kraftwerk regelmäßig inspiziert werden und eine lückenlose Buchführung führen. Diesen Aufzeichnungen zufolge war zum Zeitpunkt der Stilllegung des Kraftwerks genug Uran auf Lager, um es noch 250 Jahre lang effizient zu betreiben.}
{166}{}{Auf besonderen Erlass wurde ein eigener Stromzweig eingerichtet, um einen Funkturm nahe der Siedlung Lovelock zu versorgen. Die Anlage wurde als von entscheidender Bedeutung eingestuft und vom Militär überwacht. Das Atomkraftwerk sollte den Sender mit ausreichend Strom versorgen.}
{167}{}{Du lädst die Koordinaten des Senders auf dein Pip-Boy herunter.}
{168}{}{Offenbar befindet sich dieser Sender in derselben Gegend wie der Cheyenne-Stamm.}
{169}{}{Du hast die Koordinaten bereits heruntergeladen. Der Sender befindet sich im Süden.}
{170}{}{Es ist ein Computernetzwerk für die Kommunikation über große Entfernungen. Sein Zweck ist es, verschiedene militärische und staatliche Einrichtungen der Vereinigten Staaten miteinander zu verbinden. Das Netzwerk ist jetzt offline, was nicht besonders überraschend ist.}
{171}{}{[Fertig]}
{172}{}{Du lädst die Stationskoordinaten auf deinen Pip-Boy. Offenbar befindet sich diese Station in derselben Gegend wie der Stamm der Cheyenne.}
{173}{}{Offenbar ist es die Station bei der Siedlung des Cheyenne-Stammes, die du bereits besucht hast.}

#########################################################################
#
# Ñòàíäàğòíûå ôğàçû äëÿ êîìïüşòåğîâ è òåğìèíàëîâ
#
#   Âíèìàíèå ! İòîò ğàçäåë òåêñòà èñïîëüçóåòñÿ ïî óìîë÷àíèş â áîëüøèíñòâå êîìïüşòåğîâ è òåğìèíàëîâ Íåâàäû.
#     Òî åñòü ıòîò òåêñò èñïîëüçóåòñÿ â öåëîì ğÿäå ñêğèïòîâ.
#
#########################################################################

{200}{}{Während eines Kampfes kannst du den Computer nicht benutzen.}
{201}{}{Dein Wissenschafts-Fertigkeit ist für diesen Vorgang zu niedrig.}
{202}{}{Du brauchst Wissenschaft, um diesen Computer zu benutzen.}

#########################################################################



#########################################################################
#
#            Ğåàêöèÿ íïñ íà êğèêè è ëîâóøêè
#
#########################################################################

#-------------- Íà÷àëî ğåïëèê

#Òåñò äëÿ îõîòíè÷üåãî ñâèñòêà İâàíà
{388}{}{Wer schreit da?!}
{389}{}{Verdammte Touristen!}
{390}{}{Darauf falle ich nicht noch mal rein!}

{391}{}{?!}
{392}{}{!!}
{393}{}{ }

#Äëÿ òğóäÿã, ôåğìåğîâ, ãîğîæàí
{400}{}{Wer schreit da?}
{401}{}{Warum schreist du so?}
{402}{}{Redest du mit mir?}
{403}{}{Ich kann dich auch so gut hören!}
{404}{}{Kannst du ein bisschen leiser sein?}
{405}{}{Irren laufen frei herum ...}
{406}{}{Irgendetwas stimmt nicht!}
{407}{}{Was ist los?!}
{408}{}{Nie ist ein Cop da, wenn man ihn braucht.}

{450}{}{Darauf falle ich nicht noch mal rein!}
{451}{}{Na toll, schon wieder ein paar Psychos!}
{452}{}{Keine Chance, ich bleib lieber, wo ich bin ...}
{453}{}{Was? Schon wieder?!}
{454}{}{Wie oft denn noch!}
{455}{}{Beruhig dich endlich!}

{460}{}{Ist das ein Streich oder was?}
{461}{}{Also, was ist passiert?}
{462}{}{Wer hat geschrien?}
{463}{}{Ich versteh nicht, wer da geschrien hat.}
{464}{}{Hat hier nicht jemand geschrien?}
{465}{}{Verdammte Touristen! Die gehen mir echt auf die Nerven!}
{466}{}{Schluss, ich unternehme nichts mehr deswegen!}
{467}{}{Äh ... Was war das?}

{470}{}{WAS? WAS IST PASSIERT?!}
{471}{}{Wurde jemand niedergestochen?!}
{472}{}{Verdammt nochmal!?}
{473}{}{Was ist hier für ein Aufruhr!!?}
{474}{}{Äh ... Was war das?}
{475}{}{}
{476}{}{}
{477}{}{}

#Äëÿ ïğèìèòèâíûõ ñóùåñòâ:
{500}{}{Wer schreit denn da?}
{501}{}{Warum schreist du?}
{502}{}{Schreist du mich an?}
{503}{}{Ich hören, ja, ja ...}
{504}{}{He, du! Du zu laut!}
{505}{}{Böse Geister haben deinen Verstand genommen}
{506}{}{Was sein los?!}
{507}{}{Bist du auf einen Dorn getreten?!}

{550}{}{Nein, ich gehen erst, wenn böse Geister nicht mehr schreien}
{551}{}{Geister spielen wieder Streiche!}
{552}{}{Nein, ich gehe besser nicht ...}
{553}{}{Was? Schon wieder?!}
{554}{}{Nicht schon wieder!?}
{555}{}{Du zu wild, ich sollte dir Schlafkräuter geben}

{560}{}{Dein Witz schlecht!}
{561}{}{Äh?!}
{562}{}{Wo wird geschrien?!}
{563}{}{Ich nicht verstehen, wo böse Geister sein?}
{564}{}{Puh ... Sollte weniger Kräuter rauchen ...}
{565}{}{Habe ich Visionen?}
{566}{}{Nein, ich gehen erst, wenn böse Geister nicht mehr schreien}
{567}{}{Äh ...}

{570}{}{WAS?! WAS IST PASSIERT?!}
{571}{}{Kampf!? Wer kämpfen!?}
{572}{}{Oh!? Böse Geister!!!}
{573}{}{Ich nicht verstehen, wer schreien?}
{574}{}{Äh?}
{575}{}{}
{576}{}{}
{577}{}{}

#Äëÿ àãğåññèâíî íàñòğîåííûõ ñóùåñòâ è êğóòûõ ïàğíåé (ğåéäåğû, áàíäèòû, îõğàííèêè):
{600}{}{Warum zum Teufel schreist du wie ein Verrückter?!}
{601}{}{He, du Idiot! Hör auf zu schreien!}
{602}{}{Schreist du mich an, du Arschloch?}
{603}{}{He, ich kann dich bestens hören, hör damit auf!}
{604}{}{Was zum Teufel hast du hier vor?}
{605}{}{Sieht aus, als hätten wir hier noch einen Irren ...}
{606}{}{Hat dir jemand etwas abgerissen? Warum schreist du so?}
{607}{}{Verdammt noch mal, halt endlich die Klappe!}
{608}{}{Fahr zur Hölle!!}
{609}{}{Verdammt noch mal, halt endlich deine verdammte Klappe!}

{650}{}{Beachtet den Kerl nicht, der ist offensichtlich nicht ganz dicht.}
{651}{}{Scheiß drauf!}
{652}{}{Ich sehe mir lieber aus der Entfernung an, was hier los ist ...}
{653}{}{Was? Schon wieder?!}
{654}{}{Wie oft denn noch?!}
{655}{}{Sieh mal, noch so ein Schwachkopf!}

{660}{}{Verdammt, ich hab den interessantesten Teil verpasst!}
{661}{}{Verdammt, schon wieder zu spät zur Vorstellung!}
{662}{}{Wurde hier nicht gerade jemand abgestochen?}
{663}{}{Kann mir jemand sagen, wo zum Teufel das Geschrei herkam?}
{664}{}{Verdammt, da gab's einen Kampf und jetzt ist er vorbei! Ein Wunder!}
{665}{}{Scheiße, bilde ich mir das nur ein?!}
{666}{}{Äh ... War das nur meine Einbildung?}
{667}{}{Ach, was soll's, ich leg mich hin.}

{670}{}{WAS? WAS IST PASSIERT?!}
{671}{}{Yeah! Jemand kriegt ordentlich den Arsch versohlt!!}
{672}{}{Endlich eine Prügelei!!}
{673}{}{Eine Schlägerei? Das muss ich mir ansehen!}
{674}{}{Verdammt, was war das?}

#Äëÿ áğàìèíîâ
{700}{}{Muuu!}
{701}{}{Muuuuh!}
{702}{}{Muuuh!}
{703}{}{Muuu?}
{704}{}{Muu-muu?}

#-------------- Êîíåö ğåïëèê