{100}{}{Codetür.}
{101}{}{Du siehst eine verstärkte Codetür, die zum Kraftwerk führt. Wie zu erwarten, ist sie verschlossen.}
{102}{}{Die Tür ist verschlossen.}

#Óíè÷òîæåíèå äâåğè:
{105}{}{Die Explosion sprengt die Tür aus den Angeln und schleudert Trümmer durch die Luft.}
{106}{}{Du brauchst etwas mit mehr Wumms.}

#Ïğèìåíåíèå íàâûêîâ è ïğåäìåòîâ
{110}{}{Wer stark ist, hat recht! Das Schloss fällt ab.}
{111}{}{Du hast das Schloss auseinandergebaut und die Tür geöffnet.}
{112}{}{Du hast das Schloss aufgebrochen.}
{113}{}{Du hast das Codeschloss mit einer Sicherheitslücke ausgetrickst.}
{114}{}{Das bewirkt nichts.}
{115}{}{Was hast du erwartet? Das hier ist viel ernster!}
{116}{}{Gute Idee, aber deine Fähigkeiten lassen zu wünschen übrig.}
{117}{}{Diese Tür ist zu stark für dich.}
