{100}{}{Du siehst einen Kran.}
{101}{}{Du siehst einen verrosteten Kran. Erwarte nicht zu viel.}
{102}{}{Die Kette ist nicht mehr zu gebrauchen. Du musst sie ersetzen.}
{103}{}{Dieser Kran könnte dir nützlich sein, aber ihm fehlt eine Kette.}
{104}{}{Du hast die Kette durch ein Seil ersetzt. Für leichte Lasten sollte es reichen.}
{105}{}{Du hast die Kette bereits ersetzt.}
{106}{}{Du brauchst ihn nicht mehr. Lass ihn in Frieden verrosten.}
{107}{}{Mit einem Kran hast du nahe der Garagenwand eine Pyramide aus Trümmern errichtet.}
