{100}{}{Verklemmte Tür.}
{101}{}{Die Tür sitzt so fest, dass du sie nicht einmal ein Stück bewegen kannst.}
{102}{}{Diese Metalltür lässt sich nicht einfach mit einem Tritt öffnen.}
{103}{}{Deine Fähigkeiten helfen dir nicht weiter, die Tür ist verklemmt.}
{104}{}{Keine Chance, die Tür sitzt fest.}
{105}{}{Die Tür sitzt so fest, dass du sie nicht einmal ein Stück bewegen kannst.}
{106}{}{Geht nicht auf.}
