{100}{}{Du siehst ein Garagentor.}
{101}{}{Du siehst ein massives Garagentor ohne sichtbare Schlösser.}
{102}{}{So ein massives Tor kannst du nicht aufbrechen.}
{103}{}{Du kannst das Schloss nicht knacken, weil die Tür von innen verriegelt ist.}
{104}{}{Du kannst das Schloss nicht knacken, weil es gar keines gibt.}
{105}{}{Du entfernst die Riegel. Der Weg ist frei.}
{106}{}{Die Tür ist von innen verriegelt. Von hier aus kannst du sie nicht öffnen.}
{107}{}{Von innen verriegelt.}
{108}{}{Du siehst ein massives Garagentor.}
