#Îïèñàíèÿ
{100}{}{Du siehst einen durch einen Code verschlossenen Tresor.}
{101}{}{Du siehst einen stabil wirkenden Tresor.}

#Ïğè íàíåñåíèè óğîíà
{102}{}{Die Explosion hinterlässt keine Spuren am Tresor. Er muss aus einer extrem widerstandsfähigen Legierung bestehen.}

#Ïğè ïîëó÷åíèå áîíóñà - áóìàæêè óïğàâëÿşùåãî
{103}{}{Deine Beobachtungsgabe ist erstaunlich! Du entdeckst ein Geheimfach im Tresor, in dem sich eine Art Notiz befindet.}

#Ïğèìåíåíèå íàâûêîâ è ïğåäìåòîâ
{104}{}{Das ist ein sehr widerstandsfähiger Tresor für Manager. Solche Tresore enthalten bekanntermaßen viele Wertsachen.}
{105}{}{Das bringt nichts.}
{106}{}{Ein sehr stabil wirkender Tresor. Darin müssen wertvolle Dinge sein.}
{107}{}{Das bringt nichts.}
{108}{}{Mit mechanischen Dietrichen kommst du nicht weiter – dieser Tresor hat ein elektronisches Schloss.}
{109}{}{Das brauche ich nicht.}

#Ïîïûòêà îáåçâğåäèòü ëîâóøêó
{110}{}{Du entdeckst eine elektrische Falle am Tresor, aber deine Fähigkeiten reichen nicht aus, um sie zu entschärfen.}
{111}{}{Du hast die Falle am Tresor entschärft.}
{112}{}{Na also!}
{113}{}{Die Falle trifft dich mit einem elektrischen Schlag, aber deine Ausrüstung fängt den Schaden ab.}
{114}{}{Die Falle trifft dich mit einem elektrischen Schlag, aber deine Gummistiefel verringern den Schaden.}
{115}{}{Die Falle trifft dich mit einem elektrischen Schlag und du erleidest Schaden.}
{116}{}{Fehlgeschlagen.}
{117}{}{Verdammt!}
{118}{}{Keine Fallen.}

#Ïîïûòêà âçëîìà
{120}{}{Dieser Tresor wurde bereits geknackt.}
{121}{}{Deine Fähigkeit ist zu niedrig, um dieses Schloss zu knacken. Es hat keinen Zweck, es zu versuchen.}
{122}{}{Dieser Tresor ist durch eine elektrische Falle geschützt. Du solltest sie entschärfen, bevor du versuchst, ihn zu knacken.}
{123}{}{Da ist eine Falle.}
{124}{}{Der Tresor ist durch Starkstrom geschützt.}

{125}{}{Du knackst das Schloss geschickt.}
{126}{}{Was haben wir denn hier?}
{127}{}{Du schaffst es nicht, das Schloss dieses Tresors zu knacken.}

#Ïëàâàşùèå ğåïëèêè ïğè íåóäà÷å âçëîìà:
{130}{}{Fehlgeschlagen ...}
{131}{}{Komm schon!}
{132}{}{Ugh!}
{133}{}{Geh endlich auf, verdammt!}
{134}{}{Bei der Macht, die mir verliehen wurde von ...}
{135}{}{Nun mach schon!}
{136}{}{Wie viel denn noch?!}
{137}{}{Ich will, dass du sofort aufmachst!}
{138}{}{Komm schon, was verheimlichst du vor mir?}
{139}{}{Noch ein kleines bisschen ...}
{140}{}{Nur noch ein winzig-kleines bisschen ...}
{141}{}{Uhhhh ...}
{142}{}{Ach, Mist ...}
{143}{}{Verdammt!}
{144}{}{Ich rieche Wertgegenstände ...}
