{100}{}{Du siehst einen Raider.}
{101}{}{Einer der Geier von Big Louie, der dich nach Hawthorne begleitet.}
{102}{}{Oh mein Gott! Sie haben Kenny getötet!}

#Êîãäà ïî íàïàğíèêó ïîïàäàå' 'óğåëü (äëÿ ãåğîÿ-ìóæ÷èíû):
{104}{}{Verdammt noch mal!}
{105}{}{Wohin zum Teufel führt ihr uns?!}
{106}{}{Du kleines... Ich hab dich gewarnt!}
{107}{}{Scheiß drauf! Ich bin nicht dein verdammter Leibwächter!}
{108}{}{Wenn ich mit ihm fertig bin, bist du als Nächstes dran, Arschloch!}
{109}{}{Du Arschloch! Das werde ich dir nicht vergessen!}

#Äèàëîã:
{110}{}{Und? Willst du einfach weiterreden?}
{111}{}{Warte hier, während ich mich umsehe.}
{112}{}{Ich habe einen sicheren Weg gefunden. Komm mit.}
{113}{}{Warte hier, ich muss erst die Gegend auskundschaften.}
{114}{}{Vergiss es.}

{115}{}{Nerv mich nicht, ich ruhe mich aus.}
{116}{}{Hilf mir über den Zaun.}

#Ñäà÷à êâåñ'à
{130}{}{Die Sicherheitssysteme sind außer Betrieb! Die Lagerräume können gefahrlos durchsucht werden ... Was?}
{131}{}{Ich werd verrückt ... Ich dachte, du wärst zu nichts zu gebrauchen, aber der Boss hatte recht mit dir. Gute Arbeit. Na ja, ich hab noch einiges zu tun. Geh zurück zur Basis.}
{132}{}{Klar. Bis dann.}

{133}{}{Die Geschütztürme sehen übel aus. Fällt dir ein, wie wir an ihnen vorbeikommen?}
{134}{}{Also, die Geschütztürme laufen doch mit Strom oder so, oder? Zieh dem Generator den Stecker, dann ist das erledigt. Keine Ahnung, denk dir was aus.}
{135}{}{Stimmt.}

{136}{}{Willst du nicht mitkommen? Vorhin konntest du den Blick nicht von mir abwenden.}
{137}{}{Nee. Ich warte hier, bis du den Auftrag erledigt hast. Allein ist es sicherer. Und wenn du versuchst abzuhauen, bist du des Todes.}
{138}{}{Stimmt.}

#Ïåğâûé ğàçãîâîğ
{140}{}{Hier sind wir. So sieht der Plan aus: Der Boss will, dass wir einen Weg in den Militärstützpunkt finden, damit wir uns ein paar von den eingelagerten Waffen und Munitionsvorräten holen können. Eigentlich will er, dass DU den Weg in den Stützpunkt findest, denn ich riskiere dafür nicht meinen Arsch. Und keine faulen Tricks, sonst kannst du dich als tot betrachten. Verstanden?}
{141}{}{Verstanden. Wo werden die Waffen und die Munition gelagert?}
{142}{}{Ja, ja, spar dir die Sprüche. Und bleib in meiner Nähe, damit ich dir nicht jedes Mal den Arsch retten muss, wenn es Ärger gibt.}
{143}{}{Wir sind am Rand einer toten Stadt. Wir müssen hindurch, um zum Stützpunkt zu gelangen. Sie wird von Geschütztürmen bewacht, also pass auf deinen Arsch auf.}
{144}{}{Hab's verstanden. Los geht's.}
{145}{}{Du hast recht. Lass uns kurz reden.}

#Âîïğîñû
{150}{}{Was? Noch was?}
{151}{}{Was ist das hier für ein Ort?}
{152}{}{Was ist unser Auftrag?}
{153}{}{Wo sind die Lagerhäuser?}
{154}{}{Noch eine Frage.}
{155}{}{Genug gequatscht. Los geht's.}
{156}{}{Hawthorne, eine tote Stadt. Alle, die hier lebten, starben im Großen Krieg. Jetzt wimmelt es hier nur noch von Ratten, Geschütztürmen, Abschaum und jeder anderen Sorte Scheiß, die du dir vorstellen kannst.}
{157}{}{Bist du taub? Wir müssen die Waffen und Munition in der Basis holen, und dafür müssen wir die Geschütztürme ausschalten. Solange die noch da sind, kommen wir nicht rein.}
{158}{}{Irgendwo im Norden. In der Basis.}
{159}{}{Hier. Direkt hinter dem Zaun.}
{160}{}{Wohnt hier jemand?}
{161}{}{Hier gibt es nur Prospektoren, und zwar nur die verzweifelten. Sie kämpfen um jedes Stück Kupferdraht. Die Strahlung hat alle ausgelöscht, die tatsächlich hier gelebt haben – von ihnen sind nur noch Knochen auf den Straßen übrig.}


#Female character (Èâàí):
{1104}{}{Verdammt noch mal!}
{1105}{}{Wohin zum Teufel führt ihr uns?!}
{1106}{}{Du kleines... Ich hab dich gewarnt!}
{1107}{}{Scheiße! Ich bin nicht dein verdammter Leibwächter!}
{1108}{}{Wenn ich mit ihm fertig bin, bist du als Nächste dran, du Miststück!}
{1109}{}{Du Miststück! Das werde ich dir nicht vergessen!}

{1112}{}{Ich habe einen sicheren Weg gefunden. Komm mit.}
{1114}{}{Vergiss es.}
{1115}{}{Nerv mich nicht, ich ruhe mich aus.}
