{100}{}{Du siehst einen Gast.}
{101}{}{Du siehst einen fahrenden Händler. Er ruht sich gerade von der Reise aus und sammelt Kraft für den langen Weg.}
{102}{}{Danke für deine Hilfe.}

{110}{}{Ja? Was willst du?}
{111}{}{Nur ein bisschen plaudern, wenn es dich nicht stört.}
{112}{}{Nichts. Falsche Tür.}
{113}{}{Das ist natürlich großartig, aber nach all dem Trubel würde ich mich gern erst einmal von der Reise erholen. Weißt du, manchmal muss man ganz schön herumrennen, um etwas herauszufinden. Außerdem wurde mein Geldbeutel gestohlen! In dieser Stadt gibt es einfach zu viele Diebe.}
{114}{}{Dein Geldbeutel wurde gestohlen? Erzähl mir mehr darüber.}
{115}{}{Dann störe ich dich nicht länger bei deiner Trübsal. Auf Wiedersehen.}
{116}{}{Es war ein alter Lederbeutel mit allerlei Papieren und Notizen. Geld war keins drin. Zuletzt hatte ich ihn im Büro der Karawanenhändler benutzt. Dann kam ich hierher zurück, und der Beutel war weg! Ich weiß nicht einmal, wer mich wann bestohlen haben könnte. Der Weg vom Büro bis hierher ist ja ziemlich kurz.}
{117}{}{Also, auf dem Weg von den Karawanenhändlern zum Hotel ... Ich werde es mir merken.}
{118}{}{Wenn du ihn findest, bezahle ich dich.}
{119}{}{Gut.}
{120}{}{Ja?}
{121}{}{Erzähl mir noch einmal von deinem gestohlenen Geldbeutel.}
{122}{}{Nichts, vergiss es.}
{123}{}{Deine Geldbörse wurde gefunden. Frag nicht, wo. Ich habe meine eigenen Berufsgeheimnisse.}
{124}{}{Was für eine Erleichterung! Wenn sie nicht aufgetaucht wäre, kannst du dir nicht vorstellen, wie viel Zeit und Mühe ich aufgewendet hätte, um die Papiere wiederzubeschaffen. Vielen Dank. Ich habe dir eine Belohnung versprochen. Hier sind 100 $.}
{125}{}{Du musst nicht bezahlen. Belohnungen für das Eigentum anderer anzunehmen, ist nicht wirklich fair.}
{126}{}{Gern geschehen. Sei vorsichtig in dieser Stadt. Ich muss jetzt los.}
{127}{}{Du bist ein wunderbarer Mensch! Nochmals vielen Dank.}
{128}{}{Gern geschehen. Sei vorsichtig in dieser Stadt. Ich muss jetzt los.}

#Æåíñêèå ğåïëèêè
{1112}{}{Nichts. Falsche Tür.}