{100}{}{Du siehst einen Minenräumroboter.}
{101}{}{Ein Standardroboter, für Minenräumarbeiten umgerüstet.}
{102}{}{Systemprüfung ... Keine Fehler ... Warte auf Anweisungen ...}

{103}{}{(Der Roboter wartet auf direkte Anweisungen)}
{104}{}{[Schick den Roboter auf eine Minenräumrunde entlang des Garnisonsgeländes und der Lageranlagen]}
{105}{}{[Gehen]}
{106}{}{Protokoll „suchen und entschärfen“ ausführen ... Wird geladen ...}
{107}{}{Los, beweg dich!}
{108}{}{Beginnen.}