{100}{}{Sicherheitsturm.}
{101}{}{Du siehst einen Sicherheitsturm, der mit zwei Miniguns bewaffnet ist.}

#Попытка обезвредить ремонтом
{102}{}{Das kannst du wдhrend eines Kampfes nicht tun!}
{103}{}{Du wirst aus diesem komplizierten System nicht schlau.}
{104}{}{Du verursachst einen Kurzschluss in den Kabeln, und der Turm steht in Flammen.}
{105}{}{Das bringt jetzt nichts mehr.}

#Фразки партнеров-рейдеров
{110}{}{Hey! Hцr auf zu jammern, los geht's!}
{111}{}{Das war groЯartig. Und jetzt?}
{112}{}{Дh, dazu sage ich lieber nichts.}
{113}{}{Mach endlich Schluss damit!}
{114}{}{Lass den Turm stehen, wir mьssen los!}
{115}{}{Hцr auf, Zeit zu verschwenden, ich bekomme Hunger!}