{100}{}{Eine Lagerhallentür.}
{101}{}{Es ist eine riesige Metalltür der Lagerhalle.}
{102}{}{Sieht aus, als wäre die Tür von der anderen Seite blockiert. Sie lässt sich von hier aus nicht öffnen.}
{103}{}{Selbst dieser kräftige Tritt hat die Tür nicht bewegt.}

{104}{}{Die Tür ist von innen verkeilt und lässt sich von hier aus nicht öffnen.}
{105}{}{Von innen verkeilt.}
{106}{}{Mit großer Mühe gelingt es dir schließlich, die Tür zu öffnen.}
{107}{}{Die Tür ist jetzt endgültig verkeilt und wird sich nicht mehr öffnen lassen.}
{108}{}{Die Tür bewegt sich nicht.}

