{100}{}{Du siehst einen Spielautomaten.}
{101}{}{Der Spielautomat funktioniert nicht. Du fragst dich, ob noch Kleingeld darin ist.}

#Èñïîëüçîâàíèå íàâûêîâ è ïğ. íà àâòîìàòå:
{102}{}{Mit bloßen Händen kannst du nichts ausrichten.}
{103}{}{Der Spielautomat funktioniert nicht. Hast du etwa erwartet, spielen zu können?}
{104}{}{}
{105}{}{Du konntest das Schloss des Spielautomaten nicht knacken.}
{106}{}{Du holst aus und schlägst die verrostete Verkleidung ab. Jetzt gehört das ganze Kleingeld dir.}
{107}{}{Mit dem richtigen Werkzeug öffnest du den Automaten mühelos und nimmst das Kleingeld.}
{108}{}{Du hast es nicht geschafft, den Deckel von dem Ding abzutreten. Zu schwach.}
{109}{}{Das verrostete Schloss dieses Automaten stellt kein Problem dar. Jetzt gehört das ganze Kleingeld dir.}

#Êîãäà âçëîìàë àâòîìàò:
{110}{}{Ja, genau so!}
{111}{}{Schüttel es, Baby!}
{112}{}{Schüttel es, Baby!}
{113}{}{Ha-ha!}
{114}{}{Ein bisschen Taschengeld.}
{115}{}{Hey, hier ist noch etwas Kleingeld drin!}
{116}{}{Mann, ist das befriedigend!}
{117}{}{Schon besser!}
{118}{}{Leck mich, Glücksspielautomat! Ich hab's geschafft!}
{119}{}{Jetzt bin ich reich!}

{120}{}{Du hast diesen Glücksspielautomaten bereits aufgebrochen und das ganze Kleingeld herausgeholt. Es ist nichts mehr drin.}
{121}{}{Das bringt nichts.}
{122}{}{Dieser Glücksspielautomat ist schon lange kaputt. Mit bloßen Händen wirst du nichts aus ihm herausholen.}
{123}{}{Damit kannst du nichts anfangen.}
{124}{}{Du findest }
{125}{}{ Dollar.}

#Female character:
{1110}{}{Ja, genau so!}
{1111}{}{Schüttel es, Baby!}
{1112}{}{Schüttel es, Baby!}
{1113}{}{Ha-ha!}
{1114}{}{Ein bisschen Taschengeld.}
{1115}{}{Hey, hier ist noch etwas Kleingeld drin!}
{1116}{}{Gut gemacht, Mädchen!}
{1117}{}{Schon besser!}
{1118}{}{Leck mich, Glücksspielautomat! Ich hab's geschafft!}
{1119}{}{Jetzt bin ich reich!}
