{100}{}{Du siehst einen Minenräumroboter.}
{101}{}{Dieser Aufklärungsroboter wurde darauf programmiert, Minen zu entschärfen. Mehr kannst du wohl kaum von ihm erwarten. Sieht aus, als enthielte das Steuerungsprogramm Fehler.}
{102}{}{Das kannst du im Kampf nicht tun.}
{103}{}{Hier musst du deinen Kopf einsetzen, nicht deine Hände.}

#Íàâûêè
{110}{}{Du schaffst es nicht, den Programmcode zu reparieren – was angesichts deiner Fähigkeiten kaum überrascht ...}
{111}{}{Den Roboter zusammenzubauen ist ziemlich einfach. Aber damit er funktioniert, musst du Fehler in seinem Steuerungsprogramm beheben.}
