{100}{}{SoS deaktiviert.}
{101}{}{Du siehst ein deaktiviertes Gerät namens SoS.}
{102}{}{Du hast eine Kiste mit der Aufschrift „S.o.S.“ konfisziert. Jetzt kannst du zu Vault City zurückkehren. Ich meine, in früheren Spielversionen konntest du das. Aber dieser Inhalt wurde jetzt gestrichen. Nicht böse gemeint. Warum arbeitet niemand an der ultimativen Edition von Fallout Nevada? Sie ist so gut!}
{103}{}{Mission erfuellt.}
