{100}{}{Ein Schalter.}
{101}{}{Du siehst den Schalter, mit dem sich die Hangarbeleuchtung ein- und ausschalten lässt ... Oder eben ausschalten und einschalten, ganz wie du willst.}
{102}{}{Du schaltest die Hangarbeleuchtung ein.}
{103}{}{Du schaltest die Hangarbeleuchtung aus.}
{104}{}{Das elektrische Feld verletzt dich!}
{105}{}{Nichts passiert. Offenbar hat die Hangarhalle keinen Strom.}

{110}{}{Ugh ... Ich hoffe, ich finde den Lichtschalter, bevor ich mir hier die Beine breche.}
{111}{}{Offenbar wurde dieser unterirdische Hangar zur Wartung von Ausrüstung aus der Vorkriegszeit genutzt.}