{100}{}{Ein Schaltpult.}
{101}{}{Das Schaltpult brummt, also fließt irgendwo noch Strom.}
{102}{}{Das Schaltpult ist endgültig kaputt.}

{103}{}{Das hilft hier nicht weiter.}
{104}{}{Du konntest die Geschütztürme mit diesem Schaltpult nicht vom Stromnetz trennen.}
{105}{}{Der Kurzschluss legt den Schutzschild lahm, und plötzlich erstarren die Geschütztürme draußen.}
{106}{}{Diese Fertigkeit ist hier nutzlos.}
{107}{}{Das Schaltpult versorgt die Geschütztürme nicht mehr mit Strom. Jetzt spielt das allerdings keine Rolle mehr.}
{108}{}{Du bist nicht stark genug, um diese Kabel herauszureißen.}

{109}{}{Nur ein bisschen mehr, und du wärst eines Stromschlags gestorben.}
{110}{}{Du hast einen Stromschlag bekommen, aber deine Rüstung hat den Schlag abgefangen.}
{111}{}{Du hast einen Stromschlag bekommen! Die Stiefel haben einen Teil des Schlags abgefangen.}
{112}{}{Du hast einen Stromschlag bekommen!}