{100}{}{Du siehst den Wartungscomputer.}
{101}{}{Du siehst einen gewöhnlichen Wartungscomputer.}

{110}{}{System geladen.}
{111}{}{[Dokumente nach Datum sortieren]}
{112}{}{[Beenden]}

{113}{}{Erledigt.}
{114}{}{Abschrift der letzten Sitzung der Kommission.}
{115}{}{Beschluss der Kommission zum Fall der Desertionen.}
{116}{}{Tests des neuen Funkstörsystems.}
{117}{}{Abnahmeprotokoll der „schmutzigen Bomben“.}
{118}{}{Überwachungsdaten zu Vault 8.}
{119}{}{Informationen über den Militärfunksender in Lovelock.}

{120}{}{[Zurück]}
{121}{}{}
{122}{}{Wegen des Falls der Massendesertionen wurde eine Kommission eingesetzt. Sie legte dem Garnisonskommandanten einen Bericht vor.}
{123}{}{„Heute ging der Auftrag ein, eine Reihe von Signalstörsendern der nächsten Generation zu testen. Die Tests sind für den 17. Oktober 2077 angesetzt. Sie beginnen um 18:28 Uhr und enden um 21:02 Uhr. Ort: Hawthorne-Testgelände. Alle Einheiten müssen voll einsatzbereit sein. An die Technikabteilung: Gerät für die Tests vorbereiten und außerplanmäßige Computersicherheitsprüfungen durchführen, um Fehlfunktionen zu verhindern. Das Gerät nach Bestätigung durch den zuständigen Quartiermeister aus dem Lager in Hangar V9 bringen.“}
{124}{}{Eine Lieferung von fünf Behältern mit einem radioaktiven Isotop wurde zur vorübergehenden Lagerung im Hangar V9 abgeliefert.}
{125}{}{Wie sich herausstellte, überwachte das Militär in Hawthorne Vault 8 ununterbrochen. Es sammelte vor allem Daten von Computern und automatisierten Systemen und hörte die Kommunikation ab. Hawthorne war dafür verantwortlich, den Vault im Falle einer feindlichen Invasion oder von Naturkatastrophen zu schützen. Das Überwachungsobjekt erhielt die höchste Prioritätsstufe.}
{126}{}{Der Militärfunksender in Lovelock diente als Kommunikations- und Überwachungsposten für Vault 8.}
{127}{}{Notiere die Koordinaten von Lovelock.}
{128}{}{Hm. Dort leben die Cheyenne. Vielleicht wissen einige Einheimische, wo sich dieser Sender befindet.}
{129}{}{Ich war schon dort.}
