{100}{}{Du siehst einen Biker.}
{101}{}{Du siehst Jay Kukish. Ja, genau den.}
{102}{}{Ich vertraue dir nicht, aber im Kampf kannst du nützlich sein.}

{110}{}{Bleib ruhig. Das lähmende Mittel könnte dir leichte Kopfschmerzen bereiten, aber du bist bald wieder ganz der Alte.}
{111}{}{Also war es eine Falle. Lass mich hier raus, du Mistkerl! Sofort!}
{112}{}{Warum versteckst du dich hinter Panzerglas? Komm her, dann reden wir wie echte Männer.}
{113}{}{Ich sehe, du hast alles genau geplant. Mich gelähmt und hier eingesperrt. Clever. Tja, jetzt habe ich wohl keine große Wahl.}
{114}{}{Verschwenden wir keine Zeit. Komm zur Sache. Warum hast du das alles getan?}

{115}{}{[Du wachst in einem hellen, abgeschlossenen Raum auf. Durch dickes Glas siehst du einen Biker, der dich beobachtet.]}
{116}{}{Du ...}

{120}{}{Drohungen helfen dir nicht. Du kommst hier nicht raus, solange ich dich nicht lasse. Also bleib sitzen und rühr dich nicht.}
{121}{}{Oder was? Willst du mich wieder bewusstlos schlagen? Warte nur, bis ich dich in die Finger bekomme!}
{122}{}{Na gut, vorerst werde ich mich nicht wehren. Reden wir.}
{123}{}{Ganz schön gerissen für einen Biker. Mich an so einem Ort in eine Falle zu locken ... Hast du Angst vor jemandem?}

{124}{}{Vielleicht bekommst du diese Gelegenheit noch. Aber vorerst bleibst du eingesperrt. Ich wollte sicherstellen, dass unser Gespräch sicher abläuft.}
{125}{}{Sicher?! Du bist einfach ein Feigling! Versteckst dich hinter Glas, weil du Angst vor mir hast.}
{126}{}{Gut. Kommen wir zur Sache.}
{127}{}{Das ist vernünftig. So schießen wir wenigstens nicht aufeinander.}
{128}{}{Deine Versuche, mich auf die Palme zu bringen, sind lächerlich und erbärmlich. Genau diese Reaktion hatte ich von den Bewohnern des Vaults erwartet. Ihr seid wie Kinder, geplagt von pubertären Problemen und Wahnvorstellungen, die euer Alter weit übersteigen. Ich warte, bis du dich beruhigt hast. Schließlich hält mich nichts davon ab, zu gehen. Anders als dich.}
{129}{}{Du gehst hier nicht weg, bevor du mit der Wahrheit rausrückst! Sag mir, Miststück, sag mir alles, was du weißt!}
{130}{}{Na gut, ich versuche mich zu beruhigen. Sag mir inzwischen, wie du mich aufgespürt hast.}
{131}{}{Schon besser.}
{132}{}{Sag mir, wie du es geschafft hast, mich aufzuspüren.}
{133}{}{Denk nicht mal dran. Ich werde dir diesen Triumph nicht gönnen.}
{134}{}{Das werden wir ja sehen!}
{135}{}{Na gut. Aber jetzt sag mir, wie du es geschafft hast, mich aufzuspüren.}

{136}{}{[Spöttisch] Wie niedlich. Hast du das im Ödland aufgeschnappt? Ich sehe, deine Reisen haben ihre Spuren hinterlassen ... Aber verschwenden wir keine Zeit mit nutzlosem Geplauder. Du kommst hier nicht raus, wenn ich dich nicht lasse.}
{137}{}{Ach ja? Und wenn ich es versuche, schlägst du mich wieder bewusstlos? Warte nur, bis ich dich in die Finger kriege!}
{138}{}{Ganz genau. Du kommst hier nicht raus, wenn ich dich nicht lasse. Also verschwende deine Zeit nicht mit belanglosem Geplauder.}
{139}{}{Na schön! Genug geredet, bringen wir das ein für alle Mal zu Ende! Mit den Fäusten!}
{140}{}{Endlich höre ich in deinem kindischen Gebrabbel die Stimme der Vernunft. Beachte, dass ich dir noch nicht drohe. Die Betäubungsfalle wurde ausgelöst, nachdem der Funkstörer eingeschaltet worden war. Ich habe dich hergebracht, um sicherzustellen, dass unser Gespräch sicher abläuft.}
{141}{}{[Nickt grimmig] In dieser Welt kann man niemandem trauen. Wenn du mit mir reden willst, musst du dich an meine Regeln halten. Beachte, dass ich dir nicht drohe. Die Betäubungsfalle wurde ausgelöst, nachdem der Funkstörer eingeschaltet worden war. Ich habe dich hergebracht, um sicherzustellen, dass unser Gespräch sicher abläuft.}

{142}{}{In deinem Pip-Boy wurde ein Peilsender eingebaut. Höchstwahrscheinlich steckt einer in jedem Pip-Boy, der den Bewohnern von Vault 8 ausgehändigt wurde. Ich habe ihn benutzt, um dich aufzuspüren, aber das könnte auch jemand anderes tun. Der Signalstörer hat dieses Problem vorübergehend gelöst. Keine Sorge, ich habe den Peilsender vorsichtshalber bereits ausgebaut.}
{143}{}{Wer wusste sonst noch davon? Deine Freunde, die Biker aus Bridgeport?}
{144}{}{Scheiß drauf! Du hast diese Biker aus Bridgeport doch schon gewarnt, oder?}
{145}{}{Nein. Mein Verhältnis zu meinen Brüdern ist angespannt. Wir gehen unterschiedliche Wege. Zugegeben, ich war es, der das Gerücht in die Welt gesetzt hat, dass in Hawthorne etwas Großes passieren wird.}
{146}{}{}
{147}{}{Wird hier wirklich etwas passieren?}
{148}{}{Du versteckst dich doch aus gutem Grund auf dieser Basis, oder? Türen, Monitore, Fallen – das Arsenal eines echten Feiglings.}

{149}{}{Hawthorne war vor dem Großen Krieg ein Militärstützpunkt. Das Militär legte ihn selbst still und zog ab, und die kleine örtliche Bevölkerung starb nach und nach aus. Viele Prospektoren versuchten, die Ressourcen dieses Stützpunkts zu erreichen ... Aber sie wären besser weggeblieben. Jedenfalls bin ich aus einem anderen Grund hier. Die ganze Sache mit Vault 8 hat eindeutig mit dem Militär und der Regierung zu tun. Ich bin hergekommen, um Informationen zu suchen.}
{150}{}{Okay, warte. Du weißt also gar nichts? Warum hast du dann das Gerät aus dem Vault gestohlen?}
{151}{}{Ich verstehe das nicht. Du musst ganz von vorne anfangen und mir alles erzählen, was passiert ist.}
{152}{}{Ach ja ... Du erinnerst dich nicht, stimmt's? Mein Auftraggeber hat mich gewarnt ...}
{153}{}{Dr. Willmouth wirkt wahre Wunder! Er hat mein Gedächtnis wiederhergestellt und kann Strahlenkrankheit behandeln. Ja, er ist ein echter Zauberer. Und er hat einen Autodoc.}
{154}{}{Der Arzt im Vault hat mir mit einem Autodoc mein Gedächtnis zurückgegeben. Und wenn ich hier rauskomme, wirst du es bereuen, dass er das getan hat.}
{155}{}{Du scheinst gut informiert zu sein, hast aber die Möglichkeit nicht bedacht, dein Gedächtnis mithilfe des Autodocs im Vault wiederherzustellen.}

{156}{}{Glaubst du das wirklich? Ein Autodoc kann keine so komplizierte Operation durchführen. Ich habe schon fortschrittlichere Geräte gesehen, aber selbst die konnten das Bewusstsein eines Patienten nicht ersetzen. Und jemandem das Gedächtnis zu löschen ... [er kichert plötzlich] Dafür braucht man keinen Autodoc. Wahrscheinlich geht in deinem Vault noch etwas anderes vor sich, von dem du nichts weißt. Etwas, das dir entfallen ist, während der Doc seine „Experimente“ an dir durchgeführt hat.}
{157}{}{Ich schätze ... Moment mal! Verarsch mich nicht, du Hurensohn! Deinetwegen habe ich mein Gedächtnis verloren!}
{158}{}{Ich glaube an Dr. Willmouths Ehrlichkeit! Dein dämliches Grinsen zeigt doch nur, dass du lügst und mir etwas verschweigst. Hattest du etwas mit meiner Amnesie zu tun?}
{159}{}{Das spielt jetzt keine Rolle mehr. Was vorbei ist, ist vorbei. Mich interessiert jetzt, was du mit dem gestohlenen Gerät gemacht hast.}

{160}{}{Mein Auftraggeber hat dich deines Gedächtnisses beraubt. Ich habe nur deinen Körper als Vorwand benutzt, um in den Vault zu kommen. Und meine alten Klamotten und den Kram, damit es etwas natürlicher wirkte.}
{161}{}{Also, was ist im Vault passiert?}
{162}{}{Hätte wissen müssen, dass du nur ein erbärmlicher Söldner bist. Und was war dein Auftrag da drin?}

{163}{}{Mein Auftrag war, in den Vault einzudringen, die Wachen auszuschalten und das Gerät zu stehlen. Das muss ich dir wohl nicht sagen.}
{164}{}{Worüber hast du mit dem Aufseher gesprochen, bevor du ihn ausgeschaltet hast?}
{165}{}{Wozu dient das Gerät, das du gestohlen hast?}
{166}{}{Wer ist dieser Auftraggeber, den du erwähnt hast?}
{167}{}{Okay, dieser Teil der Geschichte ist jetzt klar.}

{168}{}{Das war ein langes Gespräch. Im Grunde interessierte sich der alte Mann für mein Leben außerhalb der Stadt, und ich fragte nach den Vaults und ihren Technologien. Ich werde das nicht alles wiederholen.}
{169}{}{Zuerst konnte ich es selbst nicht verstehen. Erst in Area 51 gelang es mir, dahinterzukommen. Dort gab es die fortschrittlichsten Technologien, die ich je gesehen hatte.}
{170}{}{Das würde ich auch gern wissen. Wer er ist, woher er deinen Körper hat, warum er ein Gerät aus dem Vault brauchte – all das weiß ich nicht. Aber es steht meinen Interessen nicht im Weg.}
{171}{}{}
{172}{}{Was meinst du?}
{173}{}{Das kristallbasierte Informationsspeichermodul ist eine äußerst seltene und für die Zeit des Krieges bahnbrechende Technologie. Warum zum Teufel ist es an so einem erbärmlichen Ort wie einem Bombenvault gelandet? Ich konnte keine Möglichkeit finden, die Daten auszulesen, aber ich vermute, dass die Diskette Programme zur Koordination der automatischen Kontrollsysteme des Vaults enthält ... Und wahrscheinlich noch etwas anderes, weniger Offensichtliches.}
{174}{}{Warum hast du das Gerät deinem Auftraggeber nicht gebracht?}
{175}{}{Wenn es um ausgeklügelte Vorkriegstechnologie geht, sind mir Auftraggeber egal. Ich beschloss, erst herauszufinden, worum es sich handelt. Eine solche Gelegenheit mit dieser Art von Technologie bietet sich selten.}

{176}{}{Wenn dir das alles klar ist, warum hast du dir dann verdammt noch mal so viel Mühe gegeben, mich zu finden?}
{177}{}{Tut mir leid, aber ohne das Gerät wird der Vault den Gefahren des Ödlands zum Opfer fallen. Das kann ich nicht zulassen.}
{178}{}{Wegen deiner technologischen Ambitionen haben sie mich aus dem Vault geworfen und gezwungen, das Gerät zurückzugeben.}
{179}{}{Mittlerweile sind mir der Vault und das Gerät egal. Ich will mich an den Leuten rächen, die das alles angefangen haben. Und du bist einer von ihnen.}
{180}{}{Ich habe gerade einen Auftrag bekommen. Der Rest geht mich nichts an.}
{181}{}{Verstehe. Du kannst das Gerät haben. Mir ist egal, was jetzt damit passiert. Ich lasse es hier. Ich muss mich jetzt um etwas anderes kümmern. Wenn du mehr über solche Technik erfahren willst, solltest du allerdings Area 51 besuchen – dort gibt es eine Menge faszinierender Dinge, sogar noch bessere als das, was du schon gesehen hast. [Schaut auf die Monitore neben sich] Oh, Scheiße ...}
{182}{}{Was?}
{183}{}{Wir haben Besuch. Und um den müssen wir uns kümmern.}
{184}{}{Warte, ich will auch kämpfen! Zusammen wird es leichter.}
{185}{}{Ja, geh nur direkt auf sie zu. Ich hoffe, sie foltern dich langsam und qualvoll.}
{186}{}{Hey, lass mich nicht hier zurück! Ich verhungere noch!}
{187}{}{Wenn du überhaupt Grips hast, findest du einen Weg nach draußen. Leb wohl.}
{188}{}{Du hast dich also schon mit dem Vault und seinen Bewohnern vertraut gemacht. Was hältst du von meinem Zuhause?}
{189}{}{Ihr seid wie Kinder. Es ist lustig, Leuten wie euch erklären zu müssen, dass der Weihnachtsmann nicht echt ist.}
{190}{}{[Dialog beenden]}
{191}{}{[Er lacht nur leise und geht zum Aufzug.]}
{192}{}{Keine Chance. Nach diesem Gespräch kann ich dir nicht trauen. Was du sagst, ist viel zu zweideutig – erst spielst du den Harten, dann bettelst du. Entweder herrscht in deinem Kopf ein heilloses Durcheinander, oder du hältst mich für einen Idioten. Das wird nichts.}
{193}{}{Na, fick dich! Ich hoffe, du krepierst da draußen!}
{194}{}{Schon gut. Vielleicht sind wir quitt. Versuch, mir nicht in die Quere zu kommen.}
{195}{}{Ich biete es dir ja nur an. Bereu es später nicht, wenn du ablehnst.}
{196}{}{Warte! Ich weiß einfach nicht, wie ich mit dir reden soll. Glaub mir, ich will nur all das besser verstehen.}
{197}{}{[Er sieht dich an, dann den Monitor und dann wieder dich.] Na gut. Aber sobald wir aus der Gefahrenzone raus sind, gehen wir getrennte Wege. Wenn du ohne Risiko von hier wegkommen willst, versuch, dich zur Hintertür zu schleichen. Sie befindet sich direkt neben dem Bahntor des Hangars. Ein kleiner Raum rechts. Pass auf, dass du ihn nicht übersiehst.}
{198}{}{Alles klar, danke!}

{1157}{}{Ich schätze ... Moment mal! Verarsch mich nicht, du Hurensohn! Deinetwegen habe ich mein Gedächtnis verloren!}
