{100}{}{Du siehst Doktor Willmouth.}
{101}{}{Du siehst Ian Willmouth. Die meisten nennen ihn Doc.}

#Õîõìà ïğè ïîäğîáíîì îñìî'ğå
{102}{}{Warum starrst du mich so an?}
{103}{}{Ich habe das Gefühl, beobachtet zu werden ...}

#Ñîîáùåíèÿ â êîíñîëü:
{104}{}{Du erhältst 100 Erfahrungspunkte, weil du mehr über Harold und seine Vergangenheit erfahren hast.}

####################################################
#
#         Ñàìûé ïåğâûé äèàëîã
#
####################################################

{110}{}{Schön, dass du wieder wach bist, }
{111}{}{. Du bist wahrscheinlich verwirrt, oder? Ja, du hast bestimmt viele Fragen, besonders wegen deiner Amnesie. Ich hätte es vorgezogen, wenn der Aufseher noch länger gewartet hätte, bevor er dich nach draußen schickt, aber trotzdem freue ich mich, dass sich dein Gehirn erholt. Ach, und falls du dich nicht erinnerst: Ich heiße Dr. Willmouth.}
{112}{}{Ich kann mich an nichts erinnern, Doc. Was ist mit mir passiert?}
{113}{}{Das war zu erwarten. Dein Gehirn war den zerstörerischen Einflüssen der Außenwelt ausgesetzt. Ich gehe nicht ins Detail, aber das Wichtigste ist, dass wir es wiederherstellen konnten. Leider ist ein Teil deiner Erinnerungen für immer verloren.}
{114}{}{Wie ist das passiert?}
{115}{}{Ein Fremder hat dich zu uns gebracht. Er nannte sich Biker und hatte dich gefesselt auf dem Rücksitz seines Zweirads. Du kannst Sergeant Graves nach ihm fragen. Als man dich zu mir brachte, warst du nur eingeschränkt beweglich und hast deine Umgebung nicht wahrgenommen. Ich diagnostizierte eine Hirnschädigung und schweren Gedächtnisverlust.}
{116}{}{Ich spreche mit Graves. Kann ich auch in Zukunft auf deine medizinische Hilfe zählen?}
{117}{}{Natürlich. Wenn du medizinische Hilfe brauchst, werde ich alles in meiner Macht Stehende tun, um dir zu helfen. Der Aufseher selbst hat es angeordnet.}
{118}{}{Hast du noch einen Rat für mich, bevor ich die Stadt verlasse?}
{119}{}{Hüte dich vor Strahlung und vermeide Körperkontakt mit toten oder lebenden Organismen.}

{120}{}{Ich weiß deine Hilfe zu schätzen, Doc, aber es wäre einfacher, mich draußen selbst behandeln zu können, statt jedes Mal zu dir kommen zu müssen, wenn ich verletzt werde.}
{121}{}{Du hast recht. Dein Körper ist noch sehr schwach und dein Immunsystem hat sich noch nicht erholt.}
{122}{}{Ich brauche etwas für Notfälle. Kannst du mir dabei helfen?}
{123}{}{Ich kann dir ein stimpak oder einen Erste-Hilfe-Kasten geben. Ersteres ist eine Chemikalie, die die Regeneration beschädigter Zellen beschleunigt. Letzteres enthält verschiedene Medikamente und Werkzeuge für aufwendigere Eingriffe. Ein stimpak erfordert keine medizinischen Kenntnisse, ein Erste-Hilfe-Kasten dagegen schon.}
{124}{}{Ich nehme ein stimpak.}
{125}{}{Ich nehme den Erste-Hilfe-Kasten.}
{126}{}{Mehr kann ich nicht tun. Alles andere würde auffallen, und vielleicht werde ich vor den Ausschuss gerufen. Das ist im Moment das Letzte, was ich will.}
{127}{}{Danke, Doc.}
{128}{}{Vielleicht, aber Selbstbehandlung ist für einen Laien sehr gefährlich. Du könntest dich mit Chemikalien überdosieren oder den Verband falsch anlegen. Am besten lässt du es gar nicht erst so weit kommen.}
{129}{}{Ich verstehe, Doc.}

{130}{}{Du hast mich angelogen! Du hast meine Erinnerung nicht wiederhergestellt, sondern durch eine neue ersetzt!}
{131}{}{Wie hast du – bist du in meinen Computer eingedrungen? Wie außergewöhnlich! Ich sollte wütend sein, aber eigentlich bin ich stolz. Noch nie ist mir eine so erfolgreiche Persönlichkeitsübertragung gelungen. Zugegeben, bei dir war es einfacher.}
{132}{}{Hast du das schon bei jemand anderem gemacht?!}
{133}{}{Nur ein paar Mal, meist wegen versehentlicher Hirnverletzungen. Aber dein Fall war einzigartig. Dein Gehirn war auf sehr präzise, ganz bestimmte Weise beschädigt worden. Wer auch immer dir das angetan hat, wollte offensichtlich, dass du es überlebst.}
{134}{}{Ist es überhaupt möglich, so etwas zu tun?}
{135}{}{Dafür hätte man ein fortschrittliches Labor und einen sehr erfahrenen Chirurgen gebraucht. Selbst ich könnte so eine Operation nicht durchführen. Das muss definitiv außerhalb von Vault City passiert sein. Bevor du aufgetaucht bist, wurdest du offiziell seit einigen Monaten vermisst ... Das erklärt so einiges.}
{136}{}{Dann muss ich anderswo nach Antworten suchen. Ich bin sicher, dieser Biker weiß etwas ... Und Doc, erzähl niemandem davon, bis ich der Sache auf den Grund gegangen bin.}

{140}{}{Ich habe vor Kurzem davon geträumt, Teil des ersten Teams zu sein, das den Vault verlassen hat. Was bedeutet das, Doc?}
{141}{}{Träume sind unter unseren Bürgern selten. Ich kann dir nicht viel darüber sagen. Wenn man bedenkt, wie viel Zeit seit der ersten Expedition außerhalb des Vaults vergangen ist, kann ich dir sagen, dass es wahrscheinlich nichts Besonderes ist. Könnte es etwas aus deinem Unterbewusstsein sein? Ich bin sicher, du wirst später eine Erklärung finden.}
{142}{}{Okay, Doc.}

{143}{}{Dann muss ich mit ihm sprechen. Pass auf dich auf, Doktor Willmouth.}
{144}{}{Das ist ein nützlicher Rat. Ich muss zu Sergeant Graves.}

{306}{}{Kannst du mir mehr über Strahlung erzählen?}

{307}{}{Klar. Was möchtest du wissen?}
{308}{}{Gibt es bestimmte Gebiete, die ich meiden sollte?}
{309}{}{Wie kann ich meine Strahlenvergiftung behandeln?}
{310}{}{Gibt es Chems, mit denen ich einer Strahlenvergiftung vorbeugen kann?}
{311}{}{Welche Auswirkungen hat eine längere Strahlenbelastung auf den Körper?}
{312}{}{Ich glaube, das war's. Bis später.}

{313}{}{Das wusste ich schon. Auf Wiedersehen.}
{314}{}{Natürlich sollte man Orte mit hoher Strahlung meiden. Aber manchmal strahlen auch einzelne Gegenstände. Besonders große Metallobjekte, etwa alte Autos.}
{315}{}{Rad-X-Pillen stärken die natürliche Strahlenresistenz deines Körpers. Du solltest sie einnehmen, bevor du verseuchte Gebiete betrittst. Wenn du bereits verstrahlt bist, entfernt RadAway die Strahlung aus deinem Körper. Vielleicht gibt es noch andere Chemikalien, die helfen könnten, aber mir ist keine bekannt.}
{316}{}{Halte deine Strahlenwerte unter 100 Rad. Alles darüber ist sehr gefährlich.}
{317}{}{Langfristige Strahlenbelastung wirkt sich negativ auf deinen Körper aus und kann Schwäche, Ungeschicklichkeit und Ausdauerverlust verursachen. Mit Behandlung wirst du dich erholen, aber das braucht Zeit.}
{318}{}{Pass auf dich auf, Bürger }
{319}{}{. Und es lebe Vault City!}
{320}{}{Es lebe Vault City!}
{321}{}{Ja, wir sehen uns, Doc.}

####################################################
#
#         Îñíîâíîé äèàëîã
#
####################################################

#Ïåğâàÿ ğåïëèêà äîêà:
{400}{}{Hallo, unser Retter. Ich gebe trotz des ganzen Chaos mein Bestes. Wie kann ich dir helfen, }
{401}{}{?}
{402}{}{Du siehst gar nicht gut aus! Glaub mir, wenn du diesen Mist nimmst, verschwinden deine Probleme nicht.}
{403}{}{Ja, }
{404}{}{? Wie kann ich dir helfen?}
{405}{}{Manchmal ist es schwierig, allen in der Stadt zu helfen. Aber sie sind gute Leute.}

{406}{}{Na gut, ich geh dann mal.}
{407}{}{Du siehst schrecklich aus! Du hättest früher vorbeikommen sollen.}

#Ìåä. ïîìîùü:
{410}{}{Ich brauche medizinische Hilfe.}
{411}{}{Setz dich. Das tut überhaupt nicht weh.}
{412}{}{Okay, Doc, ich vertraue dir ... }
{413}{}{Beantworte mir lieber ein paar Fragen.}
{414}{}{Nein, ich komme allein zurecht.}
{415}{}{Erledigt. Weiter!}
{416}{}{Danke, Doc, aber ich habe noch ein paar Fragen.}
{417}{}{Danke, Doc.}

{418}{}{Ich habe Fieber, Kopfschmerzen und innere Blutungen. Was ist mit mir los?}
{419}{}{Finden wir es heraus. Setz dich bitte in den Auto-Doc ... }
{420}{}{Heil mich, Doc!}
{421}{}{Ich muss erst noch ein paar Dinge erledigen. Ich bin gleich zurück.}
{422}{}{Was, schon wieder? Hat die letzte Behandlung nicht gewirkt? Na gut, versuchen wir es noch einmal.}
{423}{}{[Doctor Willmouth examines you and finds a viral infection] Ich habe dir ein paar antivirale Mittel gegen die Infektion gegeben. Jetzt sollte alles in Ordnung sein, aber ich kann nicht garantieren, dass das Virus nicht wiederkommt. Sei nächstes Mal vorsichtiger.}
{424}{}{Wie konnte ich mich überhaupt anstecken?}
{425}{}{Was wäre passiert, wenn du mich nicht behandelt hättest?}
{426}{}{Danke, Doc, mir geht es jetzt viel besser.}
{427}{}{Nun ... Ehrlich gesagt ist das Immunsystem unserer Bürger schwächer als das der Menschen, die im Ödland leben. Jedes Wesen, mit dem du in Kontakt gekommen bist, könnte dich angesteckt haben. Überleg mal ... Vielleicht hat dich etwas gebissen, etwa ein Hund oder ein Insekt, oder du hast etwas berührt. Man kann sich bei jemandem oder durch etwas anstecken, das vollkommen gesund aussieht.}
{428}{}{Das lässt sich schwer mit Sicherheit sagen, aber so eine Infektion verschwindet nicht so leicht. Wenn du dich daran gewöhnen kannst, wirst du keine Symptome haben, aber sie könnte deinem Körper auf andere Weise schaden.}

####################################################
#
#         Âîïğîñ î êëîíàõ
#
####################################################

{480}{}{Doc, du wusstest doch, dass wir Klone sind, oder?}

{481}{}{Offen gesagt – ja, das wusste ich.}
{482}{}{Warum hast du dann nichts gesagt?}
{483}{}{Ist jeder in der Stadt ein Klon?}
{484}{}{Bist du auch ein Klon?}
{485}{}{Was hältst du von Vault 8s Mission?}
{486}{}{Würdest du dich für deinen „Prototyp“ opfern?}
{487}{}{Ich will nicht einmal darüber reden.}
{488}{}{}
{489}{}{}
{490}{}{}
{491}{}{}

{492}{}{Die Wahrheit zu sagen war inakzeptabel. Sonst hätten wir alle einsperren müssen.}
{493}{}{Nicht alle. Die Vault-Verwaltung bestand aus gebürtigen Vault-Bewohnern. Aber viele von ihnen wurden alt und starben, weil sie keine eigenen Klone herstellen konnten. Andernfalls hätte das zu Chaos und schließlich zu Aufständen in der Stadt geführt.}
{494}{}{Ja. Ich wurde kurz nach der Schließung des Vaults „im Reagenzglas“ erschaffen. Doch nachdem der ursprüngliche Arzt, Richard Moreau, verschwunden war, brauchte unsere Regierung jemand Zuverlässigen für das medizinische Personal. Also wurde mir ein Teil der Wahrheit erzählt und ich bekam diese Position. Aber es gab eine Menge, die ich nicht wusste!}
{495}{}{Hmm. Vielleicht war es grausam von der Regierung, eine ganze Stadt als Labor für ihre eigenen egoistischen Zwecke zu erschaffen. Aber unsere Körper haben dazu beigetragen, vielen Menschen das Leben zu retten ... Ich weiß nicht, was ich davon halten soll. Ich muss erst darüber nachdenken, bevor ich über jemanden urteile.}
{496}{}{Weißt du, vielleicht ist es gar nicht so schlimm, der Klon von jemandem zu sein. Ich meine, sieh dich an – im Vault waren wir glücklich, gebildet und geschützt. Wie viele Orte wie diesen gibt es im Ödland? Ein halbes Leben glücklich zu leben, um dann jemand anderem das Leben zu retten ... So schlimm ist das meiner Meinung nach nicht. Den Menschen außerhalb der Stadt geht es viel schlechter.}
{497}{}{}
{498}{}{}
{499}{}{}

####################################################
#
#     Âîïğîñ î Ãàğîëüäå è êâåñ' î ìó'àöèÿõ
#
####################################################

{500}{}{Hast du den Mutanten in den Zellen gesehen?}
{501}{}{Reden wir über Mutationen.}

#Ïğî Ãàğîëüäà è ìó'àöèè
{510}{}{Der Mutant? Er war irgendeinem unbekannten Virus ausgesetzt, aber Strahlung könnte auch eine Rolle gespielt haben. Andererseits verlängert das Virus sein Leben. Zusammen mit seinem Leiden.}
{511}{}{Könnte er uns anstecken?}
{512}{}{Was hältst du von Harolds geistigen Fähigkeiten?}
{513}{}{Erzähl mir von Richard Grey.}
{514}{}{Erzähl mir von den Mutationen.}
{515}{}{Ich glaube, das reicht dazu.}

{521}{}{Wohl kaum. Er ist selbst keine Strahlenquelle und auch kein Virusträger.}
{522}{}{Trotz seiner Mutation und seines Alters ist dieser Mutant ... wie ein Teenager. Er macht gern Unsinn, versteht aber alles vollkommen. Er hat seinen Lebenswillen behalten ... zumindest vorerst. Wer weiß, vielleicht verändert es ihn eines Tages, unnatürlich lange leben zu können.}
{523}{}{Richard Grey? Wir hatten nie einen Bürger dieses Namens. Vielleicht meinst du Richard Moreau. Er verschwand während der ersten Expedition in die Außenwelt auf mysteriöse Weise. Das ist lange her.}
{524}{}{Harold sagte, er kenne Richard Grey aus Vault 8.}
{525}{}{Ich würde ihn nicht ernst nehmen. Wer weiß, was in seinem Kopf vorgeht? Theoretisch könnte Richard Moreau natürlich seinen Namen geändert haben. Aber ich bezweifle, dass das der Fall ist.}

{530}{}{Soweit ich weiß, gibt es drei Arten von Mutationen, wenn man sie nach ihrem Auslöser einteilt: durch Gifte, Strahlung und Viren. Die ersten beiden sind normalerweise sehr instabil und führen zu verschiedenen Formen des Todes. Aber die Virusmutation ist ... etwas Besonderes. Leider weiß ich auf diesem Gebiet nur wenig. Mir fehlt schlicht das Material für die Forschung.} 
{531}{}{Du brauchst einen Mutanten für deine Forschung?}
{532}{}{Nein, keinen lebenden. Ich würde gern Harolds Blutproben mit denen verschiedener mutierter Kreaturen im Ödland vergleichen. Ich habe mehrmals versucht, ein Forschungsteam zum Sammeln von Proben zusammenzustellen, aber das Komitee lehnt mich immer ab. Sie sagen, die Patrouillen riskieren schon genug ihr Leben, ohne sich auch noch um meine Forschung kümmern zu müssen.}
{533}{}{Ich kann dir die Proben besorgen.}
{534}{}{Kannst du das? Daran habe ich gar nicht gedacht! Nimm diesen Satz steriler Spritzen und sammle im Ödland Tierblutproben. Mich interessieren Schweineratten, Kojoten und Geckos. Oder zumindest ihre Artgenossen. Schreib es dir auf, damit du es nicht vergisst. Und sei vorsichtig! Falls etwas passiert, kann ich dich medizinisch versorgen.}
{535}{}{Wo kann ich diese Tiere finden?}
{536}{}{Gut. Aber ich habe noch eine Frage.}
{537}{}{Ich sehe, was ich tun kann.}
{538}{}{Schweineratten findest du in den westlichen Ruinen. Für Kojoten musst du woanders suchen, aber den Patrouillenberichten zufolge gibt es welche in der Wüste südöstlich von hier. Geckos sind überall, halten sich aber meist in der Nähe der Berge auf.}

#Êâåñ' íà ìó'àöèè
{540}{}{Hast du die Proben bekommen?}
{541}{}{Ich habe eine Schweineratten-Blutprobe.}
{542}{}{Ich habe eine Kojoten-Blutprobe.}
{543}{}{Ich konnte kein Kojotenblut besorgen. Wie wäre es mit Hund oder Wolf?}
{544}{}{Ich habe eine Gecko-Blutprobe.}
{545}{}{Noch nicht. Ich wollte über etwas anderes sprechen.}
{546}{}{Noch nicht. Ich gehe und kümmere mich sofort darum.}

{550}{}{Ausgezeichnet! Wir sollten die Probe sofort einfrieren ... [Er nimmt dir die Probe ab]}
{551}{}{[Weiter]}
{552}{}{Ach ja, wenn du noch mehr Proben sammelst, bring sie zu mir.}
{553}{}{Okay, Doc.}
{554}{}{Ach ja. Ich glaube, das war alles, was ich brauchte. Diese Proben reichen für ein paar Wochen Forschung. Ich bin dir sehr dankbar, danke.}
{555}{}{Gern geschehen, aber ... Doc, nachdem ich mit diesen toten Mutanten zu tun hatte, fühle ich mich irgendwie seltsam ... Mir ist übel, ich habe Fieber und Kopfschmerzen ... Was passiert mit mir?}
{556}{}{Schnell, setz dich hin, damit ich dich untersuchen kann ...}
{557}{}{[Weiter]}
{558}{}{Es geht dir wieder gut. Es war nur eine Infektion.}
{559}{}{Infek-tschon?}
{560}{}{Ich glaube, ich verstehe, wovon du sprichst – Mikroorganismen und Viren dringen in den Körper ein und lösen eine Immunreaktion aus.}
{561}{}{Ich sehe, du hast es geschafft, dir die Grundlagen anzueignen. Gut gemacht! Sehr beeindruckend für jemanden, der gerade erst aus dem Koma erwacht ist.}
{562}{}{Aber wie kann so ein winziges Ding eine so heftige Reaktion auslösen?}
{563}{}{Heterogene Mikroorganismen und Viren dringen in den Körper ein und lösen eine Immunreaktion aus. Die Symptome, die du beschrieben hast, zeigen, wie dein Körper die Eindringlinge bekämpft.}
{564}{}{Leider ist das ein häufiges Problem bei Vault-Bewohnern. Unsere Körper sind an eine sterile und saubere Umgebung gewöhnt. Das Ödland hingegen ist alles andere als das. Ein Organismus kann sich nur dann an eine Infektion anpassen, wenn er ihr oft in kleinen Dosen ausgesetzt ist. Da wir in einer sauberen Umgebung leben, sind unsere Immunsysteme nur wenigen Infektionen ausgesetzt. Deshalb bist du so leicht krank geworden.}
{565}{}{Was passiert, wenn ich es nicht rechtzeitig behandle?}
{566}{}{Das hängt davon ab, wie schwer die Infektion ist. Manche verschwinden, ohne dass du sie überhaupt bemerkst. Stärkere Infektionen verursachen Übelkeit, Fieber und andere unangenehme Symptome. Die schwersten können zum Tod führen. Pass auf dich auf, damit du nicht so endest wie Harold. Aber wie ich schon sagte: Wenn dein Körper eine Zeit lang Infektionen ausgesetzt ist, passt er sich daran an.}
{567}{}{Wie kann ich sie selbst behandeln?}
{568}{}{Du solltest wenn möglich einen Arzt aufsuchen. Wenn du dich aber mitten in der Wüste infizierst, versuch, Antibiotika mit Xanderwurzel zu mischen. Die Mischung muss erhitzt werden, du brauchst also ein Feuer. Nicht ideal, aber im Notfall reicht es. Sauberes Wasser hilft auch, falls du so etwas im Ödland findest.}
{569}{}{Willmouth hat dir beigebracht, wie man eine Infektion mit Wildpflanzen und einem Lagerfeuer behandelt.}
{570}{}{Wie lange kann die Krankheit andauern?}
{571}{}{Dein Körper wird so hart kämpfen, wie er kann, je nachdem, wie ausdauernd du bist. Wenn du dich von der Außenwelt abschottest, wird dein Körper die Infektion irgendwann vollständig beseitigen. Wenn du jedoch ständig einer feindseligen Umgebung ausgesetzt bist, wird sich die Infektion viel schneller ausbreiten.}
{572}{}{Danke für die Erklärung, Doc. Das wird mir außerhalb der Stadt nützlich sein.}

####################################################
#
#     Ïğî ñëóã èç Äæåğëàêà
#
####################################################

{600}{}{Hast du unsere neuen Diener schon kennengelernt?}

{601}{}{Ja. Sehr interessantes Studienmaterial.}
{602}{}{Hast du sie untersucht?}
{603}{}{Sind sie für uns gefährlich?}
{604}{}{Was hältst du von ihren geistigen Fähigkeiten?}
{605}{}{Findest du es nicht unethisch, sie mit Pillen vollzustopfen?}
{606}{}{}
{607}{}{}
{608}{}{Mich interessiert etwas anderes.}
{609}{}{Das ist alles, ich wollte es nur wissen.}

{610}{}{Ja, sonst hätte man sie nicht aus dem Isolierblock entlassen.}
{611}{}{Nun, das kommt darauf an, was du damit meinst. Was Viren oder Infektionen angeht – nein.}
{612}{}{Sie sind ein erbärmlicher Haufen. Aber sie können sich unterhalten und sogar train... Äh, gebildet werden.}
{613}{}{Nein, finde ich nicht. Wir geben ihnen zweimal täglich Medikamente, um ihren Willen und ihre Triebe zu unterdrücken, damit sie arbeiten, statt Ärger zu machen. Glaub mir, das ist in unserem Interesse.}

####################################################
#
#             Æåí ğåïëèêè
#
####################################################

{1115}{}{Ein Fremder hat dich zu uns gebracht. Er nannte sich Biker und hatte dich gefesselt auf dem Rücksitz seines Zweirads. Du kannst Sergeant Graves nach ihm fragen. Als man dich zu mir brachte, warst du nur eingeschränkt beweglich und hast deine Umgebung nicht wahrgenommen. Ich diagnostizierte eine Hirnschädigung und schweren Gedächtnisverlust.}
{1318}{}{Pass auf dich auf, Bürger }
{1400}{}{Hallo, unser Retter. Ich gebe trotz des ganzen Chaos mein Bestes. Wie kann ich dir helfen, }
{1407}{}{Du siehst schrecklich aus! Du hättest früher vorbeikommen sollen.}
{1424}{}{Wie konnte ich mich überhaupt anstecken?}
