{100}{}{Du siehst Sergeant Graves.}
{101}{}{Du siehst Peter Graves, den Leiter der Sicherheit von Vault City.}
{102}{}{Was ist hier passiert?!}
{103}{}{Kurz vor deiner Rückkehr wurde die Stadt angegriffen.}

#Îáùàÿ âå'âü äèàëîãà âíå êâåñ'îâ:
{110}{}{Sonst gibt es nichts zu berichten. Von jetzt an musst du auf eigene Faust handeln.}
{111}{}{Pass auf dich auf.}
{112}{}{Wer ist der seltsame Typ in der Zelle?}

{113}{}{Ich habe geträumt, dass ich zum ersten Team gehöre, das den Vault verlässt. Ist dir so etwas schon einmal passiert?}
{114}{}{Nein. Wie alle normalen Bürger habe ich noch nie geträumt. Ich weiß, dass Doktor Willmouth dieser Anomalie schon ein paar Mal begegnet ist, aber er hat ihr nie Beachtung geschenkt. Das solltest du auch nicht tun. Es ist wahrscheinlich nichts.}
{115}{}{In Ordnung.}

#Äèïëîìà' èç Ëàâëîê:
{140}{}{Ich bin in der Radiostation von Lovelock auf einige interessante Dokumente gestoßen. Ich dachte, sie könnten dich interessieren.}
{141}{}{[Studiert die Dokumente aufmerksam] Hm. Diesen Papieren zufolge wird unser Vault schon seit geraumer Zeit überwacht. Die Station ermöglichte die Kommunikation zwischen den Computersystemen unseres Vaults und denen eines bestimmten Regierungs-Vaults. Diese Information ist als geheim einzustufen! Wir müssen alle Systeme gründlich überprüfen und jede externe Kontrolle ausschließen. Danke für diesen wertvollen Fund. Mach mit deiner Mission weiter.}
{142}{}{Natürlich.}

#Ñ'àğ'îâûé äèàëîã:
{150}{}{Wie ich sehe, geht es dir besser. Doktor Willmouth hat hervorragende Arbeit geleistet und dich wieder auf die Beine gebracht. Er hat empfohlen, dir keine Aufträge zu geben, aber wir haben keine Wahl. Etwas Schreckliches ist passiert – etwas, womit wir hätten rechnen müssen, wenn ein Außenstehender auftaucht.}
{151}{}{Wovon redest du?}
{152}{}{Anscheinend hat der Mann, der dich zurück zum Vault City gebracht hat, das nur getan, um in den Vault einzubrechen. Er hat ein Gerät gestohlen, das für die Sicherheit und den Wohlstand des Vaults unverzichtbar ist. Zu Fuß können wir sein Fahrzeug nicht einholen. Da du der einzige Bürger bist, der weit über die Stadtgrenzen hinausgereist ist, bist du der Einzige, dem wir diesen Auftrag anvertrauen können. Finde das Gerät und bring es zurück.}
{153}{}{Ich verstehe, was du sagst, aber ich kann mich an nichts erinnern. Ich muss mehr darüber erfahren, was passiert ist.}
{154}{}{Natürlich. Doktor Willmouth hat uns vor deiner Amnesie gewarnt. Frag nur.}
{155}{}{Erzähl mir alles.}
{156}{}{Ein Mann, der sich „Biker“ nannte, brachte deinen bewusstlosen Körper in die Stadt. Du warst schon seit geraumer Zeit verschwunden. Der Mann stellte sich als Jay Kukish vor und verlangte, den Aufseher zu sprechen. Sie unterhielten sich lange, während Dr. Willmouth sich um dich kümmerte. Nach einiger Zeit setzte der Biker eine Art Betäubungswaffe ein, um die Wachen und den Aufseher bewusstlos zu machen. Dann stahl er das Gerät aus dem Vault und kämpfte sich aus der Stadt hinaus. Hast du noch weitere Fragen?}

{157}{}{Ja, ich habe noch andere Fragen.}
{158}{}{Keine weiteren Fragen.}

{159}{}{Gut. Was möchtest du wissen?}
{160}{}{Erzähl mir alles, was du über Jay Kukish weißt.}
{161}{}{Erzähl mir mehr über das gestohlene Gerät.}
{162}{}{Wie finde ich diesen Biker?}
{163}{}{Bekomme ich Ausrüstung für meine Reise?}
{164}{}{Was erwartet mich draußen in der Welt?}
{165}{}{Was passiert, wenn ich mich weigere zu helfen?}
{166}{}{}
{167}{}{}
{168}{}{In Ordnung. Noch eine Frage.}
{169}{}{Ich glaube, das war alles, was ich wissen wollte.}

{170}{}{Er trägt eine schmutzige Lederjacke mit einem Flammenschädel auf dem Rücken. Vielleicht hat er seine Kleidung gewechselt, aber ich glaube nicht, dass er das oft tut. Er ist unhöflich, aggressiv und interessiert sich offenbar nur für Technologien. Er kam auf seinem zweirädrigen Flitzer an und fuhr damit wieder davon. Mehr kann ich dir über ihn nicht sagen.}
{171}{}{Ich weiß weder den Namen dieses Geräts noch seinen genauen Zweck. Den Berichten zufolge war es für einige unserer automatisierten Systeme, darunter auch die Sicherheitssysteme, unverzichtbar. Ohne es sind wir Angriffen von außen schutzlos ausgeliefert.}
{172}{}{Ich empfehle dir, seinen Reifenspuren zu folgen. Unsere Patrouillen berichten, dass sie zu einem Ort namens „Black Rock“ führen könnten. Er liegt südöstlich von hier. Die Einheimischen müssen doch etwas wissen.}
{173}{}{Der Aufseher hat dir keine Ausrüstung zugeteilt, aber alles, was du bei deiner Ankunft dabeihattest, liegt im Lagerhaus. Vielleicht können dir andere Bürger etwas leihen.}
{174}{}{Ich kann dir nicht viel sagen. Unsere Späher haben von Siedlungen in der Nähe berichtet ... wenn man sie denn Siedlungen nennen kann. Manchmal treffen wir im Ödland auf Reisende, aber normalerweise versuchen wir, sie zu verscheuchen. Sie gehören nicht hierher.}
{175}{}{Du hast keine Wahl. Deine Staatsbürgerschaft ist ausgesetzt, bis du das Gerät zurückbringst. Es stehen dir nur einige wenige Standardmaßnahmen zur Verfügung; dazu gehört auch eine eingeschränkte medizinische Versorgung.}
{176}{}{Er sagt, er sei Karawanenhändler und reise zwischen Nevada und Kalifornien hin und her. Unsere Patrouille hat ihn festgenommen, als er unseren Außenposten auskundschaftete. Er sagt, er habe nach einem Atomkraftwerk gesucht. Sieht so aus, als würde er die Wahrheit sagen. Trotzdem müssen wir bei Fremden vorsichtig sein, also halten wir ihn noch eine Weile unter Verschluss. Doktor Willmouth sagt, er sei irgendeinem Virus ausgesetzt gewesen, der Arme. Aber du brauchst dir keine Sorgen um ihn zu machen. Geh wieder an die Arbeit.}

{186}{}{Na dann, viel Glück. Hol deine Sachen aus dem Lagerhaus. Und denk daran: Sei vorsichtig im Umgang mit den Leuten im Ödland. Erwähne niemandem gegenüber, dass es diese Stadt gibt. Das wäre alles.}
{187}{}{Wird erledigt, Sir!}
{188}{}{Du hast eine neue Quest erhalten. Öffne dein Pip-Boy, um ihren Status zu überprüfen.}

#Fuse
{200}{}{Ich brauche eine Ersatzsicherung für eine Wasserpumpe, aber mein Antrag wurde abgelehnt. Kannst du mir helfen?}
{201}{}{Dafür brauchst du einen guten Grund.}
{202}{}{Gerlach braucht ein Ersatzteil für ihre Wasserpumpe. Ich möchte ihnen helfen.}
{203}{}{[Lüge] Ich habe einen Kontakt außerhalb der Stadt. Er will die Sicherung im Austausch gegen Informationen.}
{204}{}{Ich habe keine guten Gründe, aber ich werde welche finden!}
{205}{}{}
{206}{}{}

{207}{}{Ich hoffe, du weißt, was du tust. Wir können nicht einfach jedem unsere Technologie überlassen. Ich werde für dich eine Bestellung beim Lagerhaus aufgeben. Und jetzt geh.}
{208}{}{Danke.}

{209}{}{Gerlach? Die Siedlung im Süden? Warum sollten wir ihnen etwas geben? Jedenfalls ist Sergeant Stark für den Südsektor zuständig. Du findest ihn in dem Gebäude auf der anderen Straßenseite.}
{210}{}{Danke. Ich werde den Sergeant suchen.}

#Ïğî íàïàäåíèå Ñîáèğà'åëÿ Äóø
{300}{}{Was für ein seltsamer Zufall – gerade als unsere Stadt wieder in Schwierigkeiten steckt, tauchst du auf.}
{301}{}{Was ist hier passiert?}
{302}{}{Wir wurden angegriffen. Alles ging sehr schnell. Die Angreifer haben den Aufseher überwältigt und ihn aus der Stadt hinausgeschleppt.}
{303}{}{Ich habe ein schlechtes Gefühl dabei. Das ist zu passend, um Zufall zu sein.}
{304}{}{Erzähl mir alles.}
{305}{}{Ich konnte den Biker aufspüren und das gestohlene Gerät zurückholen. Wir wurden von mysteriösen Leuten angegriffen. Mein Pip-Boy wurde verwanzt. Jemand agiert hinter unserem Rücken, Sergeant. Und das schon seit langer Zeit.}

{306}{}{Hmm ... Der Aufseher sagte früher Ähnliches, aber damals verstand ich ihn nicht. Er sagte, eine Veränderung stehe bevor und wir müssten bereit sein. Das war nicht für die Öffentlichkeit bestimmt.}
{307}{}{Erzähl mir mehr über den Angriff.}
{308}{}{Wir wurden von einer Gruppe Männer in Kampfrüstung angegriffen, angeführt von einer Gestalt mit Kapuze. Sie drangen mit einer Art lähmendem Mittel in die Stadt ein, gegen das wir uns nicht wehren konnten. Während die Wachen und andere Bürger außer Gefecht waren, nahmen die Feinde den Aufseher gefangen und verließen das Stadtgebiet. Einige der Wachen erholten sich und versuchten, die Eindringlinge aufzuhalten, wurden aber sofort getötet.}
{309}{}{Wozu brauchen sie den Aufseher?}
{310}{}{Ich nehme an, es hat mit dem gestohlenen Gerät und dem Wissen des Aufsehers zu tun. Er weiß etwas über den Vault, das keine der Wachen und keiner der gewöhnlichen Bürger weiß. Jedenfalls wurde der Aufseher außerhalb unseres Überwachungsbereichs gebracht – also zu weit weg, als dass wir ihn erreichen könnten. Das bedeutet, dass die Entführer ihn wahrscheinlich nicht zurückbringen wollen.}
{311}{}{Ich habe das Gerät. Hier.}
{312}{}{Verstehe. Das ist gut. Trotzdem weiß nur der Aufseher, wie man es benutzt.}
{313}{}{Was schlägst du vor?}
{314}{}{Der Aufseher weiß Dinge über den Vault, die sonst niemand weiß. Wissen, das äußerst gefährlich wäre, wenn es falsch eingesetzt würde. Deshalb darf es nicht in die Hände der Entführer fallen. Um jeden Preis. *Verstehst* du mich, Bürger?}
{315}{}{Sieht aus, als hätte ich einen neuen Auftrag.}

{316}{}{Gut. Es gibt niemanden sonst, dem ich das anvertrauen kann. Niemand sonst hat so viel Wissen und Erfahrung wie du.}
{317}{}{Noch irgendwelche Hinweise?}
{318}{}{Wir konnten feststellen, dass die Entführer mit dem Zug unterwegs sind. Unser Radar verfolgte den Pip-Boy des Aufsehers, bis er außer Reichweite geriet. Vielleicht ist diese Information nützlich, wenn du einen anderen Funksender findest.}
{319}{}{Verstanden. Ich sehe, was ich tun kann.}
{320}{}{Du bist unsere letzte Hoffnung, Bürger.}
{321}{}{Ja, klar. Erst entziehst du mir die Bürgerrechte und wirfst mich aus der Stadt, und jetzt bin ich plötzlich eure letzte Hoffnung! Na toll. Wie auch immer, ich kümmere mich um alles. Schon wieder.}
{322}{}{Ich verstehe. Ich hoffe, wenn das vorbei ist, wird alles wieder so wie früher. Bis bald, Sergeant.}
{323}{}{}
{324}{}{Du willst damit sagen, ich soll den Aufseher umbringen?! Bist du verrückt?!}
{325}{}{Wir haben keine Wahl. Sein Wissen ist eine Waffe, die uns alle töten kann.}

#Female character:
{1314}{}{Der Aufseher weiß Dinge über den Vault, die sonst niemand weiß. Wissen, das äußerst gefährlich wäre, wenn es falsch eingesetzt würde. Deshalb darf es nicht in die Hände der Entführer fallen. Um jeden Preis. *Verstehst* du mich, Bürger?}
{1320}{}{Du bist unsere letzte Hoffnung, Bürger.}
