{100}{}{Die Ruinen dieser alten Siedlung vermitteln ein Gefühl des Vergessens. Seit dem Ende des Großen Krieges scheint die Zeit hier stillzustehen.}
{101}{}{Du betrittst den Stadtrand von Hawthorne. Hier ist es ziemlich ruhig.}
{102}{}{Du betrittst das Gebiet einer Garnison. Die Stille hier macht dich nervös.}
{103}{}{}
{104}{}{Die Plünderer waren schon hier.}
{105}{}{Dieses Militärlager wurde vor langer Zeit von Schatzsuchern geplündert.}
{106}{}{}
{107}{}{Hey, sieht aus, als würde dieser Generator noch funktionieren ...}
{108}{}{Anscheinend haben die dummen und gierigen Schatzsucher versehentlich die örtlichen Sicherheitssysteme aktiviert. Jetzt wimmelt es in der Stadt von feindlichen Robotern.}
{109}{}{Eine Nachricht von Jay Kukish erscheint auf deinem Bildschirm von Pip-Boy.}
{110}{}{Wa... Wie ist das möglich?!}
{111}{}{Dieses Gebäude befindet sich im Notbetrieb. Offenbar war hier seit Jahren niemand mehr.}