{100}{}{Du siehst den alten Vernon.}
{101}{}{Du siehst Vernon, einen alten Stadtbewohner und rechthaberischen Bücherwurm.}
{102}{}{Ich mag alt sein, aber ich hab noch einiges auf dem Kasten!}

#Äèàëîã ïğî Äèîãåíà:
{119}{}{Suchst du immer noch nach Antworten? Nun, vielleicht habe ich welche für dich.}

{120}{}{Willkommen in meiner bescheidenen Behausung!}
{121}{}{Sei gegrüßt! Wie kann ein einsamer alter Mann dir helfen?}
{122}{}{Diogenes würde den Teil mit der „bescheidenen Behausung“ sicher komisch finden.}
{123}{}{Ha! Wenn du mehr über ihn wüsstest, junger Mann, würdest du verstehen, dass diese „bescheidene Behausung“ für Diogenes und die Umstände, unter denen er lebte, völlig *ausreichend* war. Das Klima, die Landschaft, die Gesellschaft ...}
{124}{}{Doch es gibt noch andere Gründe, in einer Tonne zu leben. Für ihn ging es dabei um Rebellion und Selbstdarstellung.}
{125}{}{Schon, aber ... Worauf willst du hinaus?}
{126}{}{Du solltest dich nicht selbst herabsetzen, wenn du einen recht anständigen Wohnort hast und zu einem aktiven Teil der Stadtbevölkerung gehörst.}
{127}{}{Aber ich bin der ärmste Mann in dieser Stadt!}
{128}{}{Da haben wir's wieder.}
{129}{}{Na ja ... Okay, dann ändern wir es zu: „Ich bin der Ärmste unter dem ‚aktiven Teil der Stadtbevölkerung‘.“}
{130}{}{Willst du damit sagen, dass die Landstreicher auf den Straßen nicht zur Stadt gehören?}
{131}{}{Allerdings. Sie gehören nicht dazu. Die Stadt ist größer als sie, und Bettler bringen ihr nur Schande.}
{132}{}{Aber die Bettler sind eine direkte Folge der Handlungen der Stadt. Sie wurden von der Stadt hervorgebracht und werden von ihr verschlungen, wenn sich die Lage zum Besseren wendet.}
{133}{}{Sie stehen auf derselben Stufe wie Schadstoffemissionen. Wie Rauch, der aus dem Schornstein einer Fabrik steigt – er gehört nicht mehr zur Stadt.}
{134}{}{Du sagst also, Bettler gehörten nicht zur Stadt? Das ist absurd.}
{135}{}{Wieso?}
{136}{}{Findest du nicht, dass ein Teil des Ganzen, wenn er groß und unabhängig wird, aufhört, ein Teil zu sein, und somit selbst zu einem Ganzen wird? Aber das Ganze, von dem er kein Teil mehr ist, hängt nicht von ihm ab.}
{137}{}{Hm ... Ja. Du hast recht.}
{138}{}{Also haben wir gerade gelernt, dass ...}
{139}{}{[Seit einigen Stunden führst du mit dem Bücherwurm eine tiefgründige Diskussion darüber, ein Ganzes in Teile zu zerlegen und aus Teilen wieder ein Ganzes zusammenzusetzen.]}
{140}{}{...und somit bleibt das Ganze, obwohl es weiterhin Teil des kleineren Ganzen ist, selbst ein Ganzes, während es zugleich Teil des anderen Ganzen ist, denn auch das andere Ganze bleibt Teil jenes Ganzen.}
{141}{}{Ein hervorragender Schluss! Ich sehe, deine Schlussfolgerungsfähigkeiten sind unübertroffen.}
{142}{}{Ganz genau! Es war mir ein Vergnügen, mit dir zu diskutieren. Leb wohl!}

#Äèàëîã ïğî èñòîğèş ãîğîäà:
{150}{}{Du scheinst viel intelligenter zu sein als die anderen Leute in dieser Stadt. Vielleicht kennst du die Geschichte des Ortes?}
{151}{}{Das tue ich. Ich erzähle dir gern etwas über die Stadt und ihre Gründungsgeschichte. Wenn du Zeit hast, natürlich, denn es ist eine ziemlich lange Geschichte.}
{152}{}{Bitte, erzähl mir davon.}
{153}{}{Leider habe ich keine Zeit für lange Geschichten.}
{154}{}{Also gut, es war einmal ... [Er sieht aus, als würde er den Kindern eine Gutenachtgeschichte erzählen] Dies ist die Geschichte großer Menschen und ihrer harten täglichen Arbeit.}
{155}{}{[Mehr]}
{156}{}{Die Stadt Salt Lake wurde vor dem Krieg erbaut. Gemessen an amerikanischen Maßstäben war sie groß. Es gab viele Menschen, Züge fuhren auf der Eisenbahn hin und her, Fabriken stießen Rauch aus. Die Stadt war voller Leben und ständig in Bewegung.}
{157}{}{Nach einer Weile entstand ein kleines Glücksspielviertel mit nicht allzu teuren Casinos und Restaurants, die große Schilder und glänzende Konsolen hatten ...}
{158}{}{Die Stadt war keineswegs sauber, schließlich war sie ein Industriezentrum. Sie erzeugte Strom, betrieb Fabriken und förderte Salz und Kupfer ... Im Norden der Stadt gab es sogar einen Militärstützpunkt mit eigenem Flugplatz.}
{159}{}{Und dann ...}
{160}{}{Gott steh uns bei! Die Radiosender schrien plötzlich, eine nukleare Bedrohung stehe unmittelbar bevor! In Panik stellten sich die Einwohner an, um in den großen unterirdischen Schutzräumen Zuflucht zu suchen, sicheren Bunkern, die von der Vault-Tec Corporation gebaut worden waren. Kleine Poolbauunternehmen wie „Preiser Inc.“ begannen, private Mini-Bunker für Familien zu bauen. Hunderte davon gibt es in Salt Lake, verstreut in den Kellern verschiedener Gebäude.}
{161}{}{Dann beruhigte sich alles wieder. Die bewaffneten Konflikte ließen nach, und die Menschen begannen, die Bomben zu vergessen. Niemand weiß, wer den ersten Schuss abgefeuert hat. Es könnten die Russen gewesen sein, die Chinesen oder sogar wir. Jetzt spielt es keine Rolle mehr. Die Vergangenheit ist tot und begraben.}
{162}{}{Die Weitsichtigsten versteckten sich in einem großen Vault auf dem Wausatch Ridge östlich von hier, während der Rest in seinen Familien-Vaults und Kellern Zuflucht suchte. Diejenigen, die in diesem Teil der Salt Lake City lebten, hatten mehr Glück, denn die Bomben fielen hauptsächlich im Norden, wo sich der Militärstützpunkt befand. Das örtliche Klima milderte die Auswirkungen der Explosionen: Der Regen im Herbst spülte die nukleare fallout fort, und später bedeckte Schnee sie.}
{163}{}{Die Menschen kamen erst zehn oder dreißig Jahre nach dem Krieg aus ihren Vaults. Schließlich wollte niemand sein Leben hinter Metallwänden verbringen.}
{164}{}{Die Mutigeren gingen zuerst hinaus, während sich die anderen Zeit ließen. Die letzten verbliebenen Vault-Bewohner hatten die Sonne erst vor wenigen Jahren zum ersten Mal wieder gesehen.}
{165}{}{Diejenigen, die zuerst herauskamen, erkannten sofort, dass die Außenwelt nicht mehr sicher war. Strahlung und mutierte Tiere versetzten die Bewohner in Angst und Schrecken. Auch einige Menschen hatten nichts Gutes im Sinn. Also wurde ein Rat einberufen und ein Sheriff gewählt, der eine neue Gesellschaft auf den Ruinen der alten Stadt aufbauen sollte.}
{166}{}{Der Sheriff nahm den Kampf gegen das Verbrechen auf. Er versammelte eine Gruppe entschlossener Leute um sich und half dabei, viele Geschäfte und Organisationen zu stärken ... Natürlich war das keine leichte Aufgabe.}
{167}{}{Die Stadt ist ... sozusagen zerbrechlich. Jede bedeutende Persönlichkeit hier ist eine Säule, auf der sie ruht. Sollte eine dieser Säulen einstürzen, wird die ganze Stadt folgen.}
{168}{}{Ich hoffe, meine Geschichte hat dich interessiert. Wärst du so freundlich, mir für meine Mühe eine Tasse Tee anzubieten?}
{169}{}{Gerne! Hier sind 10 Bucks als Trinkgeld. Danke!}
{170}{}{Oh, nein, ich habe kein Geld dabei.}
{171}{}{Na ja. Schade, denn ich bin hungrig.}
{172}{}{Auf Wiedersehen.}

#Ïğîâî
{180}{}{Weißt du etwas über die Einwohnerzahl von Provo?}
{181}{}{Oh ja. Das ist eine alte Geschichte. Die Einwohner von Provo waren wie der Ku-Klux-Klan aus der Zeit vor dem Krieg. Anfangs nutzte der Sheriff ihre Engstirnigkeit und ihren Extremismus für seine eigenen Zwecke. Er setzte sie ein, um sich bestimmter unerwünschter Leute zu entledigen, und als sich die Lage besserte, wurde er sie los. Seitdem hassen diese Hinterwäldler die Stadt und ihre Bürger. Sie halten uns für Gauner. Nach einer Weile wandten sie sich der Wegelagerei zu, und Verbrecher aller Art schlossen sich ihnen an.}
{182}{}{Der Sheriff hat mich gebeten, mich um diese Verbrecher zu kümmern ...}
{183}{}{Oh? Nun, das ist keine Überraschung. Die Hinterwäldler haben bereits mehrere Karawanen ausgeraubt und sogar versucht, die Stadt zu sabotieren. Aber der Sheriff will keinen offenen Krieg gegen sie führen. Verstehst du, niemand weiß viel über Provo. Wahrscheinlich sind überall in der Gegend Fallen versteckt, die nur darauf warten, dass ein Unvorsichtiger sie auslöst. Die taktische Lage spricht eindeutig gegen den Sheriff. Wenn du dich also in das Gebiet wagen willst, sei auf der Hut und achte genau auf deine Umgebung.}
{184}{}{Verstanden.}

#Áèáëèîòåêà
{190}{}{Ich habe nirgendwo sonst eine so große Büchersammlung gesehen. Woher stammen die Bücher in deiner Bibliothek?}
{191}{}{Nun, ich habe diese Bücher eigenhändig in den Ruinen zusammengesucht, ob du's glaubst oder nicht.}
{192}{}{Was für ein großartiges Beispiel selbstloser Hingabe an Kultur und Bildung! Du bist eine bemerkenswerte Person.}
{193}{}{Ein seltsames Steckenpferd für einen Bewohner einer zerstörten Stadt. Messer zu sammeln wäre eine nützlichere Beschäftigung.}
{194}{}{Was hast du davon?}
{195}{}{[Vernon kichert.] Das ist doch etwas übertrieben. Außerdem habe ich erst später in meinem Leben angefangen, mich nach Literatur zu sehnen. Es dauerte mehrere Jahre, bis ich Gedanken und Ideen in Geschriebenem erkennen konnte, statt Bücher nur als Unterhaltung zu betrachten.}
{196}{}{War das Büchersammeln also ursprünglich nicht deine eigene Idee?}
{197}{}{[Vernon kichert.] Messer zu horten hat vielleicht gewisse Vorteile, aber es erweckt einfach den Eindruck von Eitelkeit und Angeberei. Bei mir war das überhaupt nicht der Fall. Ich habe nicht aus Begeisterung angefangen, Bücher zu sammeln, das versichere ich dir. Es dauerte mehrere Jahre, bis ich Gedanken und Ideen in Geschriebenem erkennen konnte, statt Bücher nur als Unterhaltung zu betrachten.}
{198}{}{Es war eine Aufgabe, die uns von unserer mormonischen Gemeinschaft übertragen wurde. Die Salt Lake Stadtbibliothek wurde während des Atomangriffs zerstört. Die anschließenden Brände vernichteten auch viele der privaten Bibliotheken. Die Mormonen beschlossen, dass es wichtig sei, die erhalten gebliebenen Überreste des Wissens aus der Vorkriegszeit zu bewahren. Heutzutage befindet sich der Großteil der Archive in der Mormonenkirche, und die Bücher, die du hier siehst, sind eine private Sammlung, sozusagen nur für den internen Gebrauch.}
{199}{}{Verstehe.}

#Ïğîäàæà êíèæåê
{200}{}{Hast du Bücher oder Zeitschriften zu verkaufen?}
{201}{}{Ja, vielleicht habe ich etwas, falls du Interesse hast.}
{202}{}{Erzähl mir mehr.}
{203}{}{Nein, danke.}

{204}{}{Ich habe zufällig ein seltenes Buch über Medizin – genauer gesagt über Neurochirurgie. Selbst wenn du nicht selbst als Arzt praktizierst, dürfte es für jeden professionellen Arzt von Interesse sein. Einen informativeren praktischen Ratgeber habe ich noch nie gesehen.}
{205}{}{Wie viel willst du für das Buch?}
{206}{}{Kein Interesse.}
{207}{}{Weißt du, in diesem Abschnitt meines Lebens ist mir meine Gesundheit mehr wert als Geld. Ich habe ein Herzleiden und brauche dafür ein bestimmtes Medikament, das in der Stadt nirgends aufzutreiben ist. Und ich konnte es auch sonst nirgendwo finden.}
{208}{}{Du sagst, du brauchst ein Herzmedikament? Na gut, wenn ich eins finde, bringe ich es dir.}
{209}{}{Du hast Glück. Ich habe zufällig genau das Richtige in einer Ampulle dabei. Lass uns tauschen.}
{210}{}{Ich habe das Herzmedikament, das du wolltest. Ich gebe es dir im Tausch gegen das Buch über Neurochirurgie.}
{211}{}{Danke, dass du mir die Chance gibst, länger zu leben!}
{212}{}{Gern geschehen.}

{213}{}{Es wird dir bestimmt gefallen! Ein lustiger kleiner Comic aus der Zeit vor dem Krieg. Nimm ihn, du wirst es nicht bereuen!}
{214}{}{Was willst du dafür haben?}
{215}{}{Kein Geld. Geld kann dir keine Gesundheit kaufen. Hast du von der Lage mit dem sauberen Wasser in der Stadt gehört? Der Chemiker hat nur sehr selten Wasseraufbereitungstabletten im Angebot. Bring mir die Tabletten, dann bekommst du den Comic. Es lohnt sich allemal.}
{216}{}{Ich habe zufällig die Tabletten dabei. Lass uns tauschen.}
{217}{}{Gib mir etwas Zeit, darüber nachzudenken.}
{218}{}{Ich habe Wasseraufbereitungstabletten. Ich gebe sie dir im Tausch gegen das Buch über Neurochirurgie.}

{219}{}{Seit Kurzem bin ich im Besitz eines Automobils. Kannst du mir etwas zum Thema anbieten?}
{220}{}{Oh, wirklich? Das ist sehr, sehr interessant. Fahrbereite Automobile sind heutzutage eine große Seltenheit. Nun, ich habe einen Chryslus Motors-Katalog. Ein sehr dickes Magazin mit vielen verschiedenen Artikeln und nützlichen Tipps. Aber eine solche Rarität verkaufe ich nur zu einem besonderen Preis.}
{221}{}{Was soll es kosten?}
{222}{}{Dann vergiss es.}
{223}{}{Wie immer. Herzmedikamente. Du weißt schon.}
{224}{}{Noch mehr Tabletten fürs Herz? Puh! Eine zweite Packung wird noch schwerer aufzutreiben sein als die erste.}
{225}{}{Hier sind die Herztabletten. Und jetzt zu dem Chryslus Motors Katalog, den du versprochen hast ...}

{230}{}{Nimmst du seltene Bücher und Zeitschriften?}
{231}{}{Ich glaube, ich habe gefunden, wonach du gesucht hast – ein Bündel Vorkriegszeitungen.}
{232}{}{Bücher habe ich reichlich, aber keine Zeitschriften. Weißt du, ich möchte die Ereignisse der letzten Monate vor dem Großen Krieg besser dokumentieren. Wenn du etwas zu diesem Thema findest, tausche ich es gern gegen eines meiner Bücher ein.}
{233}{}{Hmm ... Es wird wohl ein wenig Arbeit machen, so etwas zu finden.}

{234}{}{Hmm ... [Vernon sieht sich die Artikel gründlich an.] Ah! Der Denver Post, nicht wahr! Unglaublich, mehr als 50 Jahre sind vergangen und sie sind immer noch lesbar! Na gut, dafür kannst du dir etwas Wertvolles aus meiner Bibliothek aussuchen.}
{235}{}{Ich brauche einen Führer zum Überleben in der Wildnis.}
{236}{}{Ich gebe dir die Zeitungen im Tausch gegen das Buch über Elektronik.}
{237}{}{Gib mir das Erste-Hilfe-Handbuch, dann gehören dir die Zeitungen.}
{238}{}{Wie wäre es mit wissenschaftlichen Büchern?}
{239}{}{Hast du etwas über Fallen?}
{240}{}{Ich interessiere mich für Bücher über Schusswaffen.}
{241}{}{Ich suche schon lange etwas über Energiewaffen ...}
{242}{}{Ich möchte diese Zeitungen erst lesen. Wenn ich fertig bin, bringe ich sie dir.}

{243}{}{Dir etwas beibringen? Nun, ich habe vielen Einwohnern der Stadt Schreiben und Mathematik beigebracht, aber meistens blieb es dabei. Heutzutage sind die Leute praktischer veranlagt und verschwenden ihre Zeit lieber nicht mit etwas, dessen Nutzen fraglich ist.}
{244}{}{Freies Sprechen.}
{245}{}{Die Geheimnisse des Glücksspiels.}
{246}{}{Nein, danke.}

{247}{}{Vielleicht ist das „Scout-Handbuch“ nützlich für dich? Du solltest es unbedingt lesen: Es enthält viele hilfreiche Informationen zum Überleben in der Wildnis.}
{248}{}{„Deans Elektronik“. Zufällig habe ich das letzte verbliebene Exemplar im Regal. Heutzutage gehen Studienbücher wie dieses weg wie warme Semmeln.}
{249}{}{Ja, ich habe noch ein letztes Buch über Theorie und Praxis der Ersten Hilfe, das nur darauf wartet, gegen ein ordentliches Bündel Zeitungen eingetauscht zu werden.}
{250}{}{Na schön, ich werde die interessantesten wissenschaftlichen Veröffentlichungen für dich zusammensuchen.}
{251}{}{„Maddocks Tricks und Fallen“ ist genau das, was du brauchst. Ein *äußerst* seltenes Exemplar, aber du hast Glück, denn ich habe eines.}
{252}{}{Dann suchst du wohl „Waffen und Munition“. Und ich habe es.}
{253}{}{Nein, ich interessiere mich für etwas anderes.}
{254}{}{Ja, das passt. Lass uns tauschen.}

{255}{}{Danke, Wanderer, es war mir ein Vergnügen, mit dir Geschäfte zu machen.}
{256}{}{Ganz meinerseits. Leb wohl.}
{257}{}{}
{258}{}{}
{259}{}{[Nickt sarkastisch.] Schämt Euch!}
{260}{}{Ich sehe, du bist nicht leicht hereinzulegen.}

{261}{}{Ich frage mich – war es wirklich so schwer, in dieser Stadt Zeitungen zu finden?}
{262}{}{Allerdings. Erstens war Salt Lake vor dem Krieg eine riesige Stadt mit sozial engagierten Bürgern, daher waren Zeitungen sehr gefragt. Zweitens verfallen Zeitungen schnell, besonders in einem feuchten Klima wie unserem. Ich habe bereits alle Zeitungsautomaten in der Gegend abgeklappert, abgesehen von denen in verstrahlten Gebieten und unbewohnten Bezirken. Wahrscheinlich war ich nicht der Erste, denn ich konnte nichts Brauchbares finden. Ach und weh!}
{263}{}{Verstehe. Nun, leb wohl.}

{264}{}{Oh, verstehe. Heutzutage gibt es nicht mehr viele davon, oder? Und auch nicht viele ausführliche Informationen darüber. Dabei gab es früher eine ganze Zeitschriftenreihe zu genau diesem Thema, die „Super Science“ hieß. Tatsächlich gebe ich hier die einzige Ausgabe her, die ich besitze.}

{265}{}{Na ja, du hast hier offensichtlich nichts „Wertvolleres“ als Bücher. Also gut, sehen wir uns an, was du hast.}
{266}{}{Hmm, wie wäre es mit einer Lektion? Du kannst mir doch sicher etwas beibringen.}
{267}{}{Meine Bibliothek ist die größte der Stadt. Sag mir, was du brauchst, und ich versuche, es zu finden.}
{268}{}{Wovon redest du?}
{269}{}{Wie dem auch sei, ich habe andere Interessen.}
{270}{}{Ein gutes Thema für einen Vortrag. Oder gleich für eine ganze Vortragsreihe. Aber wie bei Büchern gilt: Je mehr du schon weißt, desto weniger kann ich dir beibringen. Also, was meinst du? Sollen wir anfangen?}
{271}{}{Bitte fang an, Professor.}
{272}{}{...Und das war's für heute. Hast du noch Fragen?}
{273}{}{Das war sehr aufschlussreich. Ich habe nur eine Frage: War es wirklich so schwer, in dieser Stadt Zeitungen zu finden?}
{274}{}{Danke für die Lektion. Keine Fragen. Ich muss los – und herausfinden, wie ich das neu erworbene Wissen anwenden kann.}
{275}{}{Ich bin mir nicht ganz sicher, ob ich dir etwas beibringen kann, das du nicht schon weißt.}

#Ñëó÷àéíûå ôğàçêè:
{300}{}{Die Jugend von heute ...}
{301}{}{Nein, das ist es nicht ...}
{302}{}{Nein, wirklich, dieser Komiker hätte sofort gehängt werden sollen.}
{303}{}{Nichts Interessantes daran.}
{304}{}{Noch ein Groschenroman.}
{305}{}{Das ist Unsinn! Oh ... Es ist ein Buch über Psychiatrie ...}
{306}{}{Mein Gott, wenn ich doch nur im 19. Jahrhundert geboren worden wäre!}
{307}{}{Die Zivilisation ist ... frei geworden, ja.}
{308}{}{Wirklich stark ist man erst, wenn man auch die komische Seite der Dinge sieht.}
{309}{}{Man muss über die Dinge lachen, die einem wehtun, sonst treibt einen die Welt noch in den Wahnsinn.}
{310}{}{Wer aus der Reihe tanzt, hört eine andere Trommel.}
{311}{}{Wer zur Tür hereinkommt, ist meistens eine Enttäuschung.}
{312}{}{Jede Minute, die man allein mit Grübeln verbringt, vergrößert nur die eigene Isolation.}
{313}{}{Es ist die Wahrheit, auch wenn es nicht passiert ist.}
{314}{}{Es ist wirklich schade, dass so viel Mist manchmal so viel Spaß macht.}
{315}{}{Wer sein wahres Ich wirklich auslebt, hat keine Zeit für irgendein verdammtes Hobby.}
{316}{}{Manche Dinge lässt man besser, wie sie sind.}
{317}{}{Ich wünschte, ich wüsste, warum die Leute Gefühle für so wichtig halten.}
{318}{}{Fressen Katzen Fledermäuse? Fressen Fledermäuse Katzen?}
{319}{}{Warum ist ein Rabe wie ein Schreibtisch?}
{320}{}{Wenn du nicht weißt, wohin du gehst, bringt dich jeder Weg dorthin.}
{321}{}{In allem steckt ein Sinn, man muss ihn nur finden.}
{322}{}{Ich bin älter als du und muss es besser wissen.}
{323}{}{Fang am Anfang an und mach weiter, bis du ans Ende kommst, dann hör auf.}

#Female character:
{1123}{}{Ha! Wenn du mehr über ihn wüsstest, junge Dame, würdest du verstehen, dass Diogenes' „bescheidene Behausung“ für ihn und die Umstände, unter denen er lebte, durchaus *ausreichend* war. Das Klima, die Landschaft, die Gesellschaft ...}
{1255}{}{Danke, Wanderer. Es war mir ein Vergnügen, mit dir Geschäfte zu machen.}
