{100}{}{Du siehst ein Kind.}
{101}{}{Du siehst ein einheimisches Kind – vielleicht den Keim einer strahlenden Zukunft dieser Stadt. Oder ihres Untergangs.}
{102}{}{Du hast etwas Schlechtes getan, indem du einem Kind Drogen angeboten hast. Deine Seele ist ein wenig schwärzer geworden.}
{103}{}{Hallo.}

{110}{}{Hi.}
{111}{}{Diese Geldbörse, die aus deiner Tasche ragt – gehört sie dir?}
{112}{}{Tschüss.}
{113}{}{Ja. Was ist?}
{114}{}{Wirklich? Vielleicht hat sie ein Händler verloren und du hast sie zufällig „gefunden“?}
{115}{}{Na und? Was geht dich das an? Wenn du willst, kannst du sie kaufen. 10 Bucks.}
{116}{}{Einverstanden. Hier sind 10 Bucks, jetzt gib mir die Geldbörse.}
{117}{}{Wow! Das ist großartig!}
{118}{}{Wo hast du sie gefunden?}
{119}{}{Ja. Mach's gut.}
{120}{}{Schon gut, vergiss es.}
{121}{}{Einer von unseren Leuten hat sie gefunden. Ich weiß nicht, wer. Dann wechselte sie den Besitzer. }
{122}{}{Verstehe. Jetzt sind alle Spuren verloren.}
{123}{}{Rede nur weiter, du kleiner Dieb.}
{124}{}{Du solltest besser aufhören, Erwachsene anzulügen. Das kann böse enden. Gib mir die Geldbörse, bevor der wahre Besitzer auftaucht.}
{125}{}{Auf keinen Fall!}
{126}{}{Äh ... Na gut, nimm sie, aber erzähl bloß niemandem von mir!}
{127}{}{In Ordnung.}
{128}{}{Wenn du mir widersprichst, packe ich dich am Kragen und schleife dich direkt zum Sheriff, verstanden? Und jetzt gib mir das Ding!}
{129}{}{Aber ich war's nicht, ich schwöre! Hier, nimm es, aber verrat niemandem etwas von mir! Bitte!}
{130}{}{Und ich rufe sofort die Bullen und sage ihnen, dass du mich belästigst!}