{100}{}{Du siehst einen dürren Jungen.}
{101}{}{Es ist nur ein ganz gewöhnlicher Junge.}
{102}{}{Meine Mami sagt, ich darf nicht mit Fremden reden.}
{103}{}{ }

#Ôèíàëüíûå ğåïëèêè
{110}{}{Danke, wenigstens muss ich mir jetzt nicht mehr so viele Sorgen machen. Aber mein Hund tut mir trotzdem leid ...}
{111}{}{Danke, jetzt weiß ich, was mit meinem Hund passiert ist ... Mein Dad wird den Kerl umbringen! Ehrlich!}
{112}{}{[Stirnrunzelnd, den Blick von dir abgewandt]}
{113}{}{Na gut, Junge, jetzt ist alles vorbei.}

#Ïîëó÷åíèå êâåñòà:
{120}{}{[Du siehst einen Jungen zwischen den Blättern umherlaufen.]}
{121}{}{Hey, was machst du an so einem zwielichtigen, verlassenen Ort?}
{122}{}{[Lass ihn in Ruhe]}
{123}{}{Ich suche meinen Hund ... Hast du sie gesehen? Sie hat ein Halsband und eine weiße Marke ...}
{124}{}{Nein, hab ich nicht. Erzähl mir mehr, vielleicht sehe ich sie ja!}
{125}{}{Nein, hab ich nicht.}
{126}{}{Sie ist mittelgroß, grau und hat einen weißen Fleck auf der Brust. Wir hatten sie immer an der Kette, aber sie hat sich losgerissen und ist irgendwohin weggelaufen. Sie trägt ein Halsband mit einer Marke, auf der ihr Name steht. Ich vermisse sie so sehr ... Bitte find sie! Bitte!!}
{127}{}{Na gut, na gut, ich gebe mein Bestes. Hast du eine Ahnung, wohin sie gelaufen sein könnte??}
{128}{}{Na gut, na gut, ich versuch's. Versprechen kann ich aber nichts.}
{129}{}{Ich weiß nicht ... Ich habe Angst, dass sie sie gefressen haben! Diese dreckigen Leute aus den Slums! Die essen ständig Hunde! Könnten sie es gewesen sein? Bitte, find sie! Sie ist schon seit zwei Tagen weg! Bitte! Ich habe solche Angst!}
{130}{}{Schon gut, ich suche sie.}

#Ñëó÷àéíûå ôğàçû ïğè õîæäåíèè ïî ëèñòâå
{131}{}{Wo bist du hin? ...}
{132}{}{Hey, Hündchen, komm her!}
{133}{}{::Pfeift::}
{134}{}{Bitte, komm zurück!}
{135}{}{Geh nach Hause, bitte!}
{136}{}{Ich vermisse dich so sehr, bitte komm zurück!}
{137}{}{::wischt sich die Tränen ab::}

#Ñäà÷à êâåñòà:
{150}{}{Hast du sie gefunden?!}
{151}{}{Tut mir leid, Kleiner, aber dein Hund ist durchgedreht und hat mich angegriffen. Ich musste sie töten.}
{152}{}{Tut mir leid, aber dein Hund ist tot. Jemand aus den Slums hat sie schon verdaut.}
{153}{}{Tut mir leid, bisher hatte ich kein Glück.}

{154}{}{[Das Gesicht des Jungen verändert sich] Aber ... Das kann nicht sein! [Er sieht aus, als würde er gleich weinen]}
{155}{}{Weißt du, manche der Ärmsten müssen irgendwie überleben. Vielleicht wollte er deinen Hund nicht essen, aber er musste. Tut mir leid, Kleiner, aber mehr kann ich nicht für dich tun.}
{156}{}{WAS?! Das kann nicht sein!!! Mein Hündchen war ganz normal! Das ist unmöglich! Sie war es nicht! Nein!}
{157}{}{Leider war sie es. Sie muss sich in das Rudel verirrt haben, und ihre wilden Instinkte haben die Oberhand gewonnen. Hier ist die Marke von ihrem Halsband. Das ist ihre Marke, oder?}
{158}{}{Offenbar hast du recht. Vielleicht war es ein anderer Hund. Ich suche weiter.}
{159}{}{Ja ... Das ist sie ... [Er schluchzt und beginnt lautlos zu weinen]}
{160}{}{Komm schon, reiß dich zusammen! Es tut mir leid wegen des Hundes, aber wenn sie weggelaufen ist, ging es ihr dort sicher besser. Vielleicht hatte sie es satt, an der Kette zu liegen. Kannst du dir vorstellen, wie sehr sie gelitten hätte, wenn sie weiterhin an der Kette gelebt hätte?}
{161}{}{[Lass ihn in Ruhe]}
{162}{}{Äh ... Wirklich? ... [wischt sich mit der Hand die Tränen ab] Na ja, ich hoffe, sie hat jetzt ein besseres Leben im Himmel!}
{163}{}{Ja, im großen Zwinger im Himmel! Dort geht es ihr gut. Und du solltest deinen Problemen die Stirn bieten, statt weich zu werden! Verstanden? Jetzt geh, wasch dir das Gesicht und hör auf zu weinen.}
{164}{}{Danke ...}
{165}{}{Keine Ursache! Tschüss!}
{166}{}{[Deine Worte scheinen nicht viel geholfen zu haben, und der Junge weint nur noch mehr.]}
{167}{}{[Lass ihn mit seinem Schmerz und seiner Einsamkeit allein]}

#Female character:
{1124}{}{Nein, hab ich nicht. Erzähl mir mehr, vielleicht sehe ich sie ja!}
{1125}{}{Nein, hab ich nicht.}
{1153}{}{Tut mir leid, bisher hatte ich kein Glück.}
