{100}{}{Du siehst Tom.}
{101}{}{Die großen weißen Augen im Gesicht dieses Schwarzen scheinen in heller Traurigkeit zu leuchten.}
{102}{}{Gott sei mit dir! Weiche nicht vom rechten Weg ab.}
{103}{}{Oh Gott ... Du bist immer noch hier ...}

#Ïåğâûé äèàëîã
{110}{}{Gerade als ich den ersten Löffel meiner Suppe schlucken wollte, kamen die Fliegen angeflogen. Weißt du, das ist ziemlich unangenehm, aber man muss damit klarkommen.}
{111}{}{Hallo. Heute ist so ein schöner Tag, nicht wahr?}
{112}{}{Na schön, iss. Ich störe dich nicht.}
{113}{}{Richtig. Ich sollte besser rausgehen und etwas frische Luft schnappen.}

{114}{}{Wer bist du?}
{115}{}{Ich bin Tom, ein einfacher Arbeiter.}
{116}{}{Freut mich. Vielleicht können wir uns ein anderes Mal unterhalten.}

{117}{}{Warum behandeln sie dich so, Tom?}
{118}{}{Alle behandeln mich so. Schwarze und Weiße. Vielleicht liegt's an meinem Wesen. Aber beachte das gar nicht – die machen nur Spaß, sie meinen es nicht böse. Natürlich gibt es auch welche, die dir einfach das Gesicht einschlagen würden, wenn du sie lässt. Zum Glück sind nicht mehr viele von der Sorte hier – die Gemeinschaft mag sie nicht.}
{119}{}{Zum Beispiel?}
{120}{}{Tut mir leid, Tom, aber ich muss dich verlassen.}
{121}{}{Ich würde mich jetzt selbst über dich lustig machen, wenn ich könnte, aber ich habe keine Zeit. Atme erst mal durch.}

{122}{}{[Sieht sich um] Äh, hör zu, ich will über niemanden reden. Ich bin ein friedlicher Mann!}
{123}{}{Na schön, wie du willst.}
{124}{}{Wen meinst du? Es war doch der Weiße bei den Schließfächern, oder?}
{125}{}{Simon ... Äh, frag mich nicht nach ihm ... Ich will nicht darüber reden ... Weder schlecht noch gut.}
{126}{}{Ich kann dir helfen, ihn loszuwerden, wenn du willst.}
{127}{}{Ich kann dir helfen, ihn loszuwerden, wenn du mir sagst, wer dem Verwalter die Schlüssel gestohlen hat.}
{128}{}{Oh Herr! Ich bin ein friedlicher Mann. Lass mich in Ruhe! Simon ist ganz sicher ein Mistkerl. Ich wäre froh, wenn er woanders wäre, aber ich will kein Blut an meinen Händen haben. Außerdem habe ich sowieso nichts, womit ich dich bezahlen könnte.}
{129}{}{Blut an deinen Händen? Du hast „Blut an deinen Händen“ gesagt?! Tom, ich wollte ihn nicht umbringen! Es würde reichen, ihm ein bisschen Angst einzujagen.}
{130}{}{Ehrlich gesagt, vertraue ich dir nicht. In Salt Lake hört man nicht viel Gutes über dich. Tut mir leid.}
{131}{}{Du erbärmlicher Bettler, ich will nicht mal mit dir reden.}
{132}{}{Na schön, Tom, ich bestehe nicht darauf.}
{133}{}{Verdammter Feigling, ich will nicht mal mit dir reden.}
{134}{}{[Denkt einen Moment nach und sieht sich um] Hör zu, gehen wir irgendwohin, wo wir ungestörter sind, ja?}
{135}{}{Na schön, ich höre ...}
{136}{}{[Flüstert] Bitte versteh mich. Dieser Simon – er ist ein arroganter Bastard. Er schlägt jeden zusammen, gegen den es seine Herkunft und Stellung erlauben. Er ist ein sehr grausamer Mann. Gott bewahre, dass solche Leute an die Macht kommen!}
{137}{}{Na schön. Und deshalb will ich dir helfen.}
{138}{}{Ich verstehe, aber das ist mir egal.}
{139}{}{Und ich habe einen großartigen, aber friedlichen Plan. [seufzt] Ich habe dem Verwalter die Schlüssel gestohlen und sie auf der Toilette versteckt. Ja, ich war's wirklich.}
{140}{}{Hm, erzähl weiter.}
{141}{}{Ich dachte, das würde in der Fabrik für etwas Panik sorgen, und wenn die Ermittlungen beginnen, würde ich sie Simon unterschieben. Aber das ging mir dann doch zu weit. Ich kann niemandem etwas anhängen, nicht einmal so einem Tier wie Simon. Außerdem ist das in meiner Lage sehr riskant.}
{142}{}{Na, na ...}
{143}{}{Jetzt weiß ich nicht, was ich tun soll. Ich dachte, ich gestehe und gebe die Schlüssel zurück, aber dann werfen sie mich raus. Und lügen kann ich nicht, wie du siehst ...}
{144}{}{Also, Tom, hör zu: Setz dich ruhig hin und halt den Mund. Ich lasse mir etwas einfallen.}
{145}{}{Ha, du hast es selbst gestanden! Also gut, warte auf meine Entscheidung und Gnade. Sonst erzähle ich von dir.}
{146}{}{Gott segne dich!}
{147}{}{Äh, gut. Jetzt müssen wir uns wohl verabschieden.}
{148}{}{Ja, das habe ich wohl verdient ... Bitte, denk darüber nach, denk gut darüber nach.}
{149}{}{Wie ich entscheide, so wird es sein. Jetzt verschwinde.}

{150}{}{Wegen Simon ...}
{151}{}{Was ist mit ihm?}
{152}{}{Er ist tot. Und frag nicht, wie es dazu kam – das ist unwichtig.}
{153}{}{Freu dich – er wurde gefeuert! Wegen ... dem Schlüsseldiebstahl. Wer hätte das gedacht, hm?}
{154}{}{Ich wollte etwas fragen, aber vergiss es.}
{155}{}{Oh Gott, was hast du getan! Offenbar lässt sich in dieser Welt nichts friedlich lösen. Jetzt bin ich schuld an seinem Tod! Oh Gott ...}
{156}{}{He, Alter, halt den Mund. Ich habe dir geholfen – das Problem gelöst. Zeig etwas Respekt. Und gib mir was. So was ist mehr wert als ein Sandwich!}
{157}{}{Wie soll ich das denn machen? Ich bin ein einfacher Arbeiter. Ich verdiene nicht viel. Ich kann dir nur meinen Strahlenanzug geben. Den kannst du verkaufen.}
{158}{}{Gib mir den Anzug. Besser als nichts.}
{159}{}{Hier. Und jetzt keinen Scheiß mehr, klar? Ich bin schon sauer genug. Jetzt ist Schluss!}
{160}{}{Das ist dein Problem. Tschüss.}
{161}{}{[Lächelt] Verdammt, das war gut! Du hast es tatsächlich geschafft! Danke für alles, was du getan hast. Und vor allem für deine Freundlichkeit und dein Verständnis. Das fehlt auf dieser Welt wirklich.}
{162}{}{Ja. Schade, dass man die Rettung der Welt nicht in die Tasche stecken kann ...}
{163}{}{Gern geschehen.}
{164}{}{Äh, ich habe nichts, was ich dir geben könnte. Ich bin ein einfacher Arbeiter. Ich verdiene nicht viel. Ich kann dir nur meinen Strahlenanzug geben. Den kannst du verkaufen.}
{165}{}{Hier. Ich hoffe, er hilft dir irgendwie. Pass auf dich auf.}
{166}{}{Tschüss. Und lass dich nie wieder von jemandem schikanieren.}

{167}{}{Tom, jemand hat dem Administrator die Schlüssel gestohlen, und ich werde den Dieb finden. Wer auch immer das war – er kommt damit nicht davon. Du willst doch nicht, dass der Verdacht auf dich fällt, oder?}
{168}{}{Wegen Simon. Ich helfe dir, ihn loszuwerden, wenn du mir sagst, wer die Schlüssel gestohlen hat.}
{169}{}{Kaltschweiß, geweitete Pupillen, erhöhter Puls ... Meine Erfahrung als Detektiv sagt mir, dass du etwas verschweigst.}
{170}{}{Du bist kein guter Lügner, Tom. Ich sehe, du weißt mehr, als du zugibst.}
{171}{}{[Fassungslos] Privatdetektiv? Gibt es so was heutzutage überhaupt? Wow ...}
{172}{}{Für mich ist das nur ein Hobby, nicht meine Pflicht ...}
{173}{}{Ich habe die Schlüssel. Erinner mich daran, was du mit ihnen vorhattest?}
{174}{}{*schnüffelt* Ich rieche einen Dieb aus einem Kilometer Entfernung! [holt tief Luft] JA, DU BIST ES!}
{175}{}{Ähm ... Du meinst das doch nicht ernst, oder? Heh ... Ich meine, wie kannst du den Dieb riechen ...}
{176}{}{[Sieh ihn ernst an]}

#Ïëàâàşùèå èçäåâêè îò òîâàğèùåé â ñòîëîâîé
{180}{}{Hey, Alter, willst du etwas ... *Milch*? Ha-ha!}
{181}{}{Tom starrt schon wieder. Sieh nicht weg, du Dummkopf!}
{182}{}{Nenn dich nicht einen Nigger? Tut mir leid, das kann ich nicht!}
{183}{}{Tom, wie wär's mit einem Witz über Afrika?}
{184}{}{Hey, Tom, du kannst doch kein blaues Auge kriegen, oder?}
{185}{}{Wie kommt es, dass hier so viele Schwarze sind? Tom, hast du alle zusammengetrommelt?}

#Female character
{1116}{}{Freut mich. Vielleicht können wir uns ein anderes Mal unterhalten.}
{1121}{}{Ich würde mich jetzt selbst über dich lustig machen, wenn ich könnte, aber ich habe keine Zeit. Atme erst mal durch.}
{1156}{}{He, Alter, halt den Mund. Ich habe dir geholfen – das Problem gelöst. Zeig etwas Respekt. Und gib mir was. So was ist mehr wert als ein Sandwich!}
{1161}{}{[Lächelt] Verdammt, das war gut! Du hast es tatsächlich geschafft! Danke für alles, was du getan hast. Und vor allem für deine Freundlichkeit und dein Verständnis. Das fehlt auf dieser Welt wirklich.}
{1163}{}{Gern geschehen.}
