{100}{}{Du siehst einen Administrator.}
{101}{}{Du siehst eine ältere Frau mit zerzaustem Haar, das in alle Richtungen absteht. Man kann nur sagen, dass ihre Reize längst der Vergangenheit angehören.}
{102}{}{Hilfe! Hier sind Verrückte!!!}
{103}{}{Danke für die Hilfe.}

#Äèàëîã äî ïîëó÷åíèÿ êâåñòà
{110}{}{Ja, was ist?}
{111}{}{Kann ich hineingehen?}
{112}{}{Nichts.}

{113}{}{Nein. Der Eingang zur Fabrik ist nur für Mitarbeiter.}
{114}{}{Ich bin doch einer von ihnen!}
{115}{}{Äh ... Gnädige Frau, Sie sehen müde aus. Ist etwas passiert?}
{116}{}{Schon gut.}

{117}{}{Ach ja? Ich glaube, davon wüsste ich.}
{118}{}{Na ja, wenigstens ist es jemandem aufgefallen! In dieser Fabrik gibt es so viele Männer, und keiner kann einer alten Frau helfen ... Und vor Kurzem wurde ich sogar ausgeraubt, wissen Sie? Sie haben mir meinen Schlüsselbund direkt vor der Nase weggenommen!}
{119}{}{Wie ist das passiert?}
{120}{}{Das ist doch Unsinn. Die Schlüssel sind kein Geld. Warum sollten sie sie stehlen?}
{121}{}{Verdächtigen Sie jemanden?}
{122}{}{Tut mir leid. Ich muss jetzt gehen. Auf Wiedersehen.}

{123}{}{Ich möchte nach den Schlüsseln fragen, die gestohlen wurden.}
{124}{}{Ich weiß nicht, was diese Diebe wollten, aber viel bringen wird es ihnen wohl kaum.}
{125}{}{Verstehe. Nun, ich muss los.}
{126}{}{Wenn du willst, kann ich nach dem Dieb suchen.}
{127}{}{Ich hatte hier eine ganze Schar von Arbeitern. Eine gewöhnliche Zusammenkunft, Abrechnungen und ähnliche Verwaltungsarbeit. An dem Tag verschwand mein Schlüsselbund. Das könnte jeder gewesen sein.}
{128}{}{Ich weiß es nicht. In der Fabrik ist es generell schwierig, etwas zu stehlen. Überall sind Menschen, da wird man leicht erwischt. Und die Schlüssel sind nichts Wichtiges. Was auch immer der Dieb sich davon versprochen hat, er wird es nicht bekommen.}
{129}{}{Es war eine ganze Schar da. Wahrscheinlich ist es jemand Neues. Die anderen hätten gemerkt, dass meine Schlüssel ihnen nichts Wertvolles einbringen.}
{130}{}{Woher willst du wissen, dass du sie nicht einfach verloren hast?}
{131}{}{Ich bin eine alte Frau, aber mein Gedächtnis ist noch gut!}
{132}{}{Ich wäre dir sehr dankbar. Frag die Arbeiter, am besten während der Mittagspause, wenn sie in den Speisesaal gehen. Aber niemand wird es zugeben!}
{133}{}{Ich werde trotzdem versuchen, der Sache auf den Grund zu gehen. Ich dulde keinen Abschaum, der Frauen bestiehlt!}

#Çàâåğøåíèå êâåñòà
{150}{}{Deine Schlüssel wurden gefunden.}
{151}{}{Wirklich?! Das ist großartig! Wo sind sie?}
{152}{}{Ich habe die Schlüssel. Ich habe sie zufällig auf der Toilette gefunden – jemand hat beschlossen, sie dort zu verstecken.}
{153}{}{Ich konnte die Schlüssel zurückbringen. Wie sich herausstellte, hat Tom, der Schwarze, sie gestohlen.}
{154}{}{Der Schwarze Tom hat sie. Zeit, ihn zur Strecke zu bringen!}
{155}{}{Der neugierige Simon hat sie. Zeit, ihn zur Strecke zu bringen!}
{156}{}{Simon hat die Schlüssel in seinem Spind im Diner gelassen. Beeil dich, solange sie noch dort sind.}

{157}{}{Oh, du bist sehr aufmerksam! Tut mir leid, jetzt werden wir nie erfahren, wer es war. Aber ich habe die Schlüssel, also ist es nicht wichtig.}
{158}{}{Ja ...}
{159}{}{Oh, dieser Schurke! Ich wusste, dass ich bei ihm vorsichtig sein sollte! Vom Aussehen her könnte man meinen, er sei so einfältig, aber weißt du, ich habe den Schwarzen nie getraut. Sie sehen für mich sogar unheimlich aus! Mit ihren weißen Pupillen! Oh, wie schrecklich …}
{160}{}{Stimmt. Und außerdem hat er sich als Dieb herausgestellt …}
{161}{}{Zieh keine voreiligen Schlüsse. Er hat die Schlüssel gestohlen, um seinen alten Feind zu bestrafen – diesen weißen Mistkerl Simon.}
{162}{}{Hmm ... Es wurde auch Zeit, diesen Mistkerl aus der Fabrik zu werfen! Und weißt du was? Vielleicht ist der Schwarze doch nicht so dumm, wie es scheint ... Ich glaube, ich sage lieber nichts. Sollen sie sich gegenseitig die Kehlen aufschlitzen. Jedenfalls weiß ich in dieser Sache nur, was du mir erzählt hast, also muss ich es dabei belassen. Die Schlüssel habe ich ja jetzt ohnehin.}
{163}{}{Großartig.}
{164}{}{Dieser neugierige Mistkerl, ich konnte ihn noch nie leiden. Ich bin froh, ihn aus der Fabrik werfen zu können! Und er soll nur versuchen, zurückzukommen ...}
{165}{}{Das hat er verdient!}
{166}{}{Das ist deine Sache.}

{167}{}{Oh, vielen Dank! Du hast die alte Dame vor Ärger bewahrt. Wie könnte ich dir da nicht dankbar sein? Hier, nimm 100 Dollar und eine Kirsch-Nuka-Cola-Cola. Das ist unsere neue Sorte, noch nicht einmal im Verkauf.}
{168}{}{Ist das alles? Na gut, immerhin etwas ...}
{169}{}{Trotzdem danke!}
{170}{}{Ich glaube, du kannst das Geld besser gebrauchen als ich. Aber die Cola nehme ich. Eine Erfrischung kann nicht schaden.}
{171}{}{Ich hätte nie gedacht, dass es in unserer Zeit noch gute Samariter gibt! Vielen Dank.}
{172}{}{Gern geschehen. Und lass dich nicht noch einmal so behandeln.}
{173}{}{Gern geschehen.}

#Female character
{1152}{}{Ich habe die Schlüssel. Ich habe sie zufällig auf der Toilette gefunden – jemand hat beschlossen, sie dort zu verstecken.}
