{100}{}{Du siehst einen Arbeiter.}
{101}{}{Das ist nur ein gewöhnlicher Fabrikarbeiter.}
{102}{}{Ich bin beschäftigt. Reden wir nach der Arbeit.}
{103}{}{Ich bin es nicht gewohnt, mit vollem Mund zu reden.}

{112}{}{He, Kumpel! Unbefugte dürfen sich den Tanks nicht nähern. Sperrgebiet. Umdrehen!}
{113}{}{Unbefugte dürfen sich den Tanks nicht nähern. Sperrgebiet. Umdrehen!}
{114}{}{Ugh ...}

###################################################
#
#     ‹€‚€™ˆ… ”€‡›
#     €âòîğ: €ëåêñàíäğ €ãàôîíöåâ
#
###################################################

#All's good
{250}{}{Bei dem Tempo verdiene ich genug, um meine eigene Fabrik zu eröffnen!}
{251}{}{Jetzt werde ich jede Menge Schnaps haben!}
{252}{}{Heute kriege ich das beste Mädchen der Stadt ab!}
{253}{}{Und dabei hieß es immer, mit ehrlicher Arbeit kommt man zu nichts! Ha!}
{254}{}{Bei solchen Bedingungen arbeite ich tagelang!}
{255}{}{Lasst uns unseren Herrn preisen, Brüder!}
{256}{}{Alle Mann! Heute geht's zum "Tin angel"! Ich gebe einen aus!}
{257}{}{Endlich hört meine Alte auf, mir in den Ohren zu liegen ...}
{258}{}{Ja! Ja! Wer hat gesagt, wir wären Versager? Ha-ha!}
{259}{}{::summt fröhlich etwas über einen Priester und zehn Huren::}
{260}{}{Es hat sich gelohnt, all die Zahnräder und Schrauben aus diesen verdammten Maschinen zu klauben!}
{261}{}{Wer auch immer uns geholfen hat, dem spendiere ich eine Woche lang den besten Fusel in Salt Lake!}
{262}{}{Ich kann's nicht glauben, dass uns tatsächlich jemand geholfen hat! Wir errichten ihm zu Ehren ein Denkmal aus leeren Flaschen!}
{263}{}{Meine Glücksmütze von Nuka-Cola hat mir endlich geholfen!}
{264}{}{Ich bin jetzt ein erfolgreicher Mann! Nennt mich „Sir“!}
{265}{}{Nuka-Cola! Der Geschmack des Sieges!}
{266}{}{Nuka-Cola! Still deinen Durst!}
{267}{}{Nuka-Cola! Jetzt 5 Rad/h weniger!}
{268}{}{Das Leben ist schön!}
{269}{}{Kein verdammter brahmin-Fraß mehr zum Abendessen!}

#all's ok
{300}{}{Ein weiterer Tag bricht an, aber der Dreck bleibt derselbe ...}
{301}{}{Noch ein erbärmlicher Tag ...}
{302}{}{Maschine Nummer 3 ist schon wieder kaputt ...}
{303}{}{Uff, dieser Kater ...}
{304}{}{Wer hat schon wieder ins Konzentrat gepisst?!}
{305}{}{Wie läuft's? Alles beim Alten ...}
{306}{}{Arbeiten? Wozu?}
{307}{}{Schon wieder Überstunden ...}
{308}{}{Ich sollte lieber brahmin hüten ...}
{309}{}{Hauptsache, bis zum Abend durchhalten ...}
{310}{}{Wer hat mein Bier genommen?!!}
{311}{}{Ich kann dieses Nuka-Cola nicht mehr sehen!}
{312}{}{Wer hat heute an der dritten Maschine gearbeitet? Sie ist schon wieder im Eimer!}
{313}{}{Wo kann ich mich eine Stunde hinlegen?}
{314}{}{::blickt düster zurück und tritt ein Maschinenteil weg::}
{315}{}{Wenn ich doch nur das Sagen hätte! Ich hätte hier Ordnung geschaffen!}
{316}{}{Anstatt diesen Scheiß zu machen, sollten sie lieber Bier brauen!}
{317}{}{Sie sollten Schnaps brennen – wir würden im Gold baden ...}
{318}{}{Wenn uns doch nur jemand helfen könnte ...}
{319}{}{Hat nicht geklappt und wird auch nie klappen!}

#all's bad
{350}{}{Oh, Mist ... Nein, nicht der übliche Scheiß – viel schlimmer ...}
{351}{}{Zeit, mir einen anderen Job zu suchen ...}
{352}{}{Mein Bruder ist Raider ... Vielleicht sollte ich mich ihm anschließen?}
{353}{}{Welchen beschissenen Streich könnte ich dem Manager vor meinem Abgang spielen?}
{354}{}{Ich wäre lieber Sklave, als hier zu arbeiten!}
{355}{}{Doppelschichten schieben, ohne ein einziges freies Wochenende ... Und das ist das Ergebnis.}
{356}{}{Ich hab nicht mal Gift, um mich umzubringen ... Moment, da ist Nuka-Cola! Schlägt Arsen um Längen!}
{357}{}{Nuka-Cola! Der Geschmack des Sieges? Ist er das? Hmm ...}
{358}{}{Ich ersäufe den Vorarbeiter im Konzentratbehälter – und dann ab nach Vegas!}
{359}{}{Fürs Wegmachen von brahmin-Scheiße gibt's sogar mehr Geld!}
{360}{}{Ich werde wohl eine Niere verkaufen müssen ...}
{361}{}{Ich warte auf den Geisterzug und werfe mich einfach unter seine Räder ...}
{362}{}{Ich hab's ihnen gesagt – sie sollten mehr Geld in Werbung stecken!}
{363}{}{Ich kündige ... Ich habe gehört, Vegas braucht Kanalarbeiter ...}
{364}{}{Was soll ich tun? Mich zuerst umbringen oder meine Frau und Kinder?}
{365}{}{Was soll ich essen? Brahmin-Kaugummieintopf, mit Rattenscheiße als Beilage?}
{366}{}{Lasst uns die Maschinen zerlegen! Vielleicht ist der Schrott was wert ...}
{367}{}{Heute alle ins "Tin angel"! Wir feiern mein Begräbnis!}
{368}{}{Ein ehrlicher, hart arbeitender Mensch bringt es heutzutage zu nichts ...}
{369}{}{Vielleicht wäre ich beim Hoover dam besser aufgehoben?}
