{100}{}{Du siehst Arroganten Larry.}
{101}{}{Du siehst den Chefkoch dieser lausigen Kantine.}
{102}{}{*Skriptausführungsfehler*}

#Ïåğâûé ğàçãîâîğ
{110}{}{[Ohne dir auch nur die geringste Beachtung zu schenken, knetet der Koch weiter Teig und pfeift ein albernes Liedchen.]}
{111}{}{Geben Sie mir eine Speisekarte, guter Mann.}
{112}{}{[Gehen]}

{113}{}{[Der Koch hält inne und blickt zu dir auf.] Sieh nach oben.}
{114}{}{Äh ... Da ist nichts.}
{115}{}{Pffft-ha-ha-ha!!! Natürlich ist da nichts, denn diese Kantine ist nur für Fabrikarbeiter. Für gewöhnliche Ganoven wird hier nicht aufgetischt. Wenn du essen willst, geh zu Jolly Joe.}
{116}{}{Aber ich bin Fabrikarbeiter.}
{117}{}{Ach, verstanden. Dann halte ich mich hier nicht länger auf.}

{118}{}{Ist das so? Na dann, willkommen im miesesten Diner der Stadt. Also, was darf's sein – Würmer, Schimmel oder Stiefel mit Mayonnaise?}
{119}{}{Ich nehme die Würmer. M-m, lecker!}
{120}{}{Vielleicht nehme ich den Schimmel.}
{121}{}{Hm, probieren wir die Stiefel.}
{122}{}{Willst du mich verarschen?! Wo gibt's hier normales Futter?}
{123}{}{Ich habe keinen Hunger. Iss deine Würmer oder was auch immer du da hast. Ich gehe.}

{124}{}{Ja, wurde auch Zeit.}
{125}{}{[Gehen]}
{126}{}{Baa-hah! Abklatschen! Es ist so eine Freude, in der Fabrik Frischfleisch zu sehen! Aber jetzt mal im Ernst. Wenn du was zu essen willst, habe ich es hier. Du musst nur deine Wertmarken mitbringen.}
{127}{}{Meine was?}
{128}{}{Wertmarken. Die werden vom Abteilungsleiter für zwei Wochen im Voraus ausgegeben. Eine Wertmarke bedeutet eine Mahlzeit. Dein Vorgesetzter *hätte* dir das sagen müssen! Verdammte Bastarde, die machen sich nicht mal mehr die Mühe ...}
{129}{}{Ah, dafür braucht man die also ... Ich habe sie hier.}
{130}{}{Stimmt. Ich gehe dann mal und, äh, rede mit meinem Vorgesetzten.}
{131}{}{Hey, nicht so hastig! Dein Vorgesetzter hätte es dir eben erklären sollen. Die Wertmarken werden vom Abteilungsleiter für zwei Wochen im Voraus ausgegeben. Eine Wertmarke bedeutet eine Mahlzeit. Wenn du Futter willst, habe ich es hier. Bring einfach deine Wertmarken mit.}
{132}{}{Na, hast du deinem Vorgesetzten den Hintern versohlt? Oder sabberst du weiter über die letzte Schüssel Suppe hier?}
{133}{}{Ja, hier sind die Wertmarken. Alles klar.}
{134}{}{Nein, noch nicht.}
{135}{}{Ach, einen Kunden in diesem Loch zum zweiten Mal zu sehen, ist äußerst selten. Haha, nur ein Scherz!}
{136}{}{Genug der Witze. Wo ist die Speisekarte?}
{137}{}{Dann hast du ja Glück gehabt, denn ich gehe gerade.}
{138}{}{Na, was darf es diesmal sein?}
{139}{}{Ein gewöhnliches Abendessen. Hier sind die Wertmarken.}

#Âûäà÷à îáåäà
{140}{}{Gut. Dann weißt du alles, was du wissen musst. So muss ich mir nicht mit blöden Fragen den Kopf zerbrechen. Also, wie viele Popel willst du heute?}
{141}{}{Ich brauche nichts, ich habe es mir anders überlegt.}
{142}{}{Mach ich. Wie viele Rationen?}

{143}{}{Eine Ration. Hier ist die Wertmarke.}
{144}{}{Zwei Rationen.}
{145}{}{Drei Rationen.}
{146}{}{Vier Rationen.}
{147}{}{Fünf Rationen.}
{148}{}{Ich möchte alle meine Wertmarken eintauschen.}
{149}{}{}

{150}{}{Wow, was für ein Appetit!}
{151}{}{Halt die Klappe. Pack noch ein paar drauf, und schau, was ich damit anfangen kann.}
{152}{}{Vielleicht überlege ich mir die Auswahl noch ein wenig.}
{153}{}{Hier. Eine Ration enthält Obst, ein Sandwich und eine Flasche Nuka-Cola. Guten Appetit und ... Mach den anderen Platz, blockier nicht das Fenster!}
{154}{}{Danke.}
{155}{}{Ich würde ja „Danke“ sagen, aber nicht für so einen Service.}
{156}{}{Du hast den einfältigen Koch getäuscht und praktisch die Fabrik ausgeraubt. Wie schäbig!}

#Çàñòàë çà ïåğåäâèæåíèåì ïî êóõíå
{160}{}{Hey, das hier ist kein Kontrollpunkt! Raus aus meiner Küche, aber dalli!}
{161}{}{Was für ein Aufstand ...}

#Female character
{1122}{}{Willst du mich verarschen?! Wo gibt's hier normales Futter?}
{1132}{}{Na, hast du deinem Vorgesetzten den Hintern versohlt? Oder sabberst du weiter über die letzte Schüssel Suppe hier?}
{1141}{}{Ich brauche nichts, ich habe es mir anders überlegt.}
{1151}{}{Halt die Klappe. Pack noch ein paar drauf, und schau, was ich damit anfangen kann.}
{1155}{}{Ich würde ja „Danke“ sagen, aber nicht für so einen Service.}
