{100}{}{Du siehst den Jolly Joe.}
{101}{}{Du siehst einen sehr komischen Glatzkopf mit einem Dauergrinsen und hervorstehenden Zähnen. Wenn da nicht seine Kleidung wäre, würdest du ihn für verrückt halten.}
{102}{}{ }

#Dialogue
{109}{}{Ein neues Gesicht in unserem Laden? Mach es dir bequem! In keiner Bar der Welt kannst du lange sitzen, ohne Alkohol zu kaufen und dich zu betrinken. Und genau dafür machen wir unseren Job! Such dir was aus, was darf's sein?}
{110}{}{Na? Was darf's zu trinken sein?}
{111}{}{Zeig mir, was du da hast.}
{112}{}{Nichts, ich gehe.}
{113}{}{Ich möchte mich über eure Kellnerin beschweren. Sie war unhöflich zu mir!}
{114}{}{Ach, komm schon! Sie ist eine tolle alte Dame. Alle hier sind verrückt nach ihr, und du wirst sie auch bald lieben. Entspann dich!}
{115}{}{N-na gut, wie auch immer ...}
{116}{}{Das war's? Kumpel, so verhungerst du noch! Ha-ha-ha!}

#Women's replics:
{118}{}{Ich möchte mich über eure Kellnerin beschweren. Sie war unhöflich zu mir!}
{119}{}{Das war's? Kumpel, so verhungerst du noch! Ha-ha-ha!}

#Post-games bonus:
{120}{}{Ho-ho! Wer besucht denn unsere Stadt! Schön zu sehen, Mister, dass du uns nicht vergisst! Bleibst du lange?}
{121}{}{Ho-ho! Wer besucht denn unsere Stadt! Schön zu sehen, Miss, dass du uns nicht vergisst! Bleibst du lange?}
{122}{}{Nein, Joe. Ich bin nur für ein paar Minuten auf einen Krug Bier vorbeigekommen.}
{123}{}{Nein, Joe. Ich bin nur für ein paar Minuten auf einen Krug Bier vorbeigekommen.}
{124}{}{Ich schaue ab und zu mal vorbei. Bis dann!}
{125}{}{[Er schüttelt heftig den Kopf] Ja, ich verstehe! Wieder auf die Straße, um das Ödland vor den verdammten Mistkerlen zu retten! Ich bin so froh, dass so tapfere Leute wie du unsere Gegend noch gelegentlich besuchen.}
{126}{}{Natürlich gibt es auch in dieser Welt gute Menschen ...}
{127}{}{Klar. Und ich möchte dir auch eine Freude machen. [Er holt eine Brille und eine schimmlige Flasche hervor] Du glaubst gar nicht, wie alt dieser Drink ist. So etwas im Ödland zu finden, ist ein Glücksfall. Aber ich hatte Glück und konnte eine Kiste zu einem vernünftigen Preis ergattern. Sie ist allerdings fast aufgebraucht. Hier, ich möchte auf dein Wohl trinken.}
{128}{}{[Mehr]}
{129}{}{[Du verbringst einige Zeit damit, Joes faszinierenden Geschichten zu lauschen und eine Flasche köstlichen Whiskey zu leeren.] ... Und so wurden wir diesen Deathclaw los. Gruselig, was?}
{130}{}{Oh, Joe, mit diesen Deathclaws ist es viel einfacher. Aber ich glaube, das weißt du schon, wenn du diesem Ding von Angesicht zu Angesicht gegenübergestanden hast. Hm?}
{131}{}{Äh ... ja! Äh ... natürlich. Natürlich weiß ich alles über sie. [Er sieht die Flasche an] ... Ähm, weißt du ... verdammt, ich bewundere dich so sehr, dass ich dir diese ganze Flasche schenke. Hier, bitte!}
{132}{}{Wow, danke für diese Rarität, Joe! Man sieht sich. Tschüss.}

#Inquire about the city
{140}{}{Ich möchte dich etwas über die Stadt fragen.}
{141}{}{Ich möchte für alle hier einen ausgeben, um mich vorzustellen.}
{142}{}{Jetzt gerade nicht, Kumpel. Sag mal, hast du hier funktionierende Züge gesehen?}

{143}{}{Tut mir leid, aber wenn man deinen Ruf bedenkt, wird dir das nicht helfen.}
{144}{}{Verdammt!}
{145}{}{Das ist eine großartige Art, dich der Stadt vorzustellen! Zahl 200 Bucks, und jeder hier wird wissen, wer du wirklich bist.}
{146}{}{Hier ist das Geld. Hey, Leute, das Bier geht auf mich! Für alle!}
{147}{}{Äh, eigentlich möchte ich dich etwas über die Stadt fragen.}
{148}{}{Heute nicht. Tschüss.}
{149}{}{Ein guter Anfang, aber glaub mir – in dieser Stadt machst du dir nicht bloß dadurch einen Namen, dass du allen ein Bier spendierst. Fang klein an.}
{150}{}{Danke für den Tipp, Joe.}

{151}{}{Oh, genau deshalb laufe ich hier jeden Tag meine Hosen durch!}

{152}{}{Wer hat hier das Sagen?}
{153}{}{Wird dieser Ort vom Gesetz kontrolliert?}
{154}{}{Ist dieser Galgen oft leer?}
{155}{}{Wo kann ich mich oder meine Ausrüstung flicken lassen?}
{156}{}{Kannst du mir mehr über die Gegend erzählen?}
{157}{}{Warum sind hier so viele Karawanenhändler?}
{158}{}{Okay, genug gequatscht.}
{159}{}{Verstehe. Kann ich noch etwas fragen?}

{160}{}{Ich schätze, es ist der Sheriff. Er hat alle an der Leine – deshalb traut sich kein Feigling, hier sein Gesicht zu zeigen. Oh ja.}
{161}{}{Der Sheriff ist das Gesetz. Es geschieht alles so, wie er es sagt.}
{162}{}{Komm am Nachmittag wieder, wenn es noch nicht zu dunkel ist. Normalerweise verfüttern sie dann die neuen Opfer der Show ans Publikum. Lustige Typen sind das.}
{163}{}{Na ja, du kannst dir an den Verkaufsautomaten etwas holen oder dir was zu essen kaufen. Die Quok-Brüder auf der anderen Straßenseite verkaufen Ausrüstung, und der Techniker aus der Nuka-Cola-Fabrik hilft dir, kaputtes Inventar wieder in Ordnung zu bringen. Im Norden, vor dem Büro des Sheriffs, gibt es einen Apotheker, allerdings ist bei ihm in letzter Zeit kaum noch etwas zu kaufen. Außerdem kannst du im Hotel übernachten, wenn dich die Schwäche fast umhaut.}
{164}{}{[Er seufzt, offenbar hat er diese Frage satt.] Oh Gott ... Das hier ist das Geschäftszentrum. Wenn du Ausrüstung brauchst oder dich entspannen willst – komm her. Die Nuka-Cola-Fabrik liegt im Osten, und weiter in dieser Richtung ist der Abwasserkanal. Im Norden liegt das Wohnviertel, in dem sich das Büro des Sheriffs befindet. Alles in allem solltest du lieber nicht herumstreunen: wegen der Strahlung, den wilden Hunden, den Säuregeckos ... Und vielen anderen feindseligen Abscheulichkeiten.}
{165}{}{In den letzten Jahren hat Salt Lake mehr Unternehmer als üblich angezogen. Das war, weißt du, genau der richtige Zeitpunkt, um sich die Taschen mit Geld vollzustopfen. Diejenigen, die das rechtzeitig erkannt haben, haben das ganze Potenzial der Stadt für ihre eigenen Interessen genutzt. Deshalb hat die Stadt für andere Siedlungen immer noch etwas zu bieten.}

{166}{}{[Plötzlich verstummen alle um dich herum und wenden sich dir zu.] Wovon redest du?}
{167}{}{Äh, ich wollte fragen: Gibt es hier einen Zug, der noch fährt? Einen, der sich wirklich bewegt, verstehst du?}
{168}{}{[Joe blickt ins Publikum. Sein Lächeln schwindet und wird zu einer Grimasse.] Nein, hier gibt es nur Haufen rostigen Metalls.}
{169}{}{Aber ihr habt doch eine Eisenbahn, oder?}
{170}{}{Und?}
{171}{}{Also sag mir, wo ist der Bahnhof mit den Zügen?}
{172}{}{[Er senkt die Stimme, und das Lächeln verschwindet langsam von seinem nervösen Gesicht.] Hör zu, selbst ich wage es nur selten, darüber Witze zu machen ... Geh nicht dorthin. Und hör auf, davon zu reden.}
{173}{}{Hey, immer mit der Ruhe!}
{174}{}{Sieht aus, als hättest du die falsche Frage gestellt. Hier stimmt etwas nicht ...}

{175}{}{Wer ist der Typ, der sich beim Eingang herumtreibt?}
{176}{}{Unverbesserlicher Ned? Ein wandelnder Sack voller Eingeweide. Ich würde die Dienste so eines Lümmels nicht in Anspruch nehmen, wenn er nicht so wenig dafür verlangen würde. Und ein paar Münzen spare ich gern. Ha!}

#Recipe of the peanut paste
{177}{}{}
{178}{}{Du erhältst 75 Erfahrungspunkte für den erfolgreichen Einsatz der Handelsfertigkeit.}
{179}{}{Vergiss es, ich muss los.}
{180}{}{Welche Erdnusspaste hast du auf Lager?}
{181}{}{Paste? Ach ja, die Vocas-Nusspaste. Das Ergebnis meiner kulinarischen Forschung. Wie du siehst: erfolglos.}
{182}{}{Warum erfolglos?}
{183}{}{Weil der Brei zu hart und zu säurehaltig für den Magen war. Ein Fabriktechniker hat sie früher als Rostlöser gekauft, aber nachdem er das Rezept erfahren hatte, fing er an, sie selbst herzustellen. Scheiße ...}
{184}{}{Interessant. Würdest du mir das Rezept verraten?}
{185}{}{Hey, du bist doch dieser Schutzengel, der durch die Stadt zieht und für Gerechtigkeit sorgt? Na, dann kein Problem – hier ist das Rezept, und ich verlange keinen Cent dafür!}
{186}{}{Großartig.}
{187}{}{Warum sollte ich es einem Fremden verraten?}

{188}{}{Na ja, ich kann bezahlen.}
{189}{}{Geizhals. Dann auf Wiedersehen.}
{190}{}{Weißt du, so dringend brauche ich es gar nicht. Ich kann auch ohne deine Rezepte leben. Tschüss.}

{191}{}{Hey, gute Idee! 100 Dollar, und das Rezept gehört dir. Was sagst du?}
{192}{}{Na ja, ich kann bezahlen.}
{193}{}{75, keinen Dollar mehr.}
{194}{}{Na gut, ich kaufe es.}
{195}{}{Na gut. Du hast recht – wem sonst könnte ich dieses Rezept verkaufen? 75 müssen reichen.}
{196}{}{Vergiss das Rezept. Lass uns über etwas anderes reden.}
{197}{}{Tritt mir bloß nicht auf meine schmerzenden Hühneraugen! Ich gebe es schon fast umsonst her!}
{198}{}{Wow, du willst dafür wirklich bezahlen? Das ist großartig! Also ... [schreibt das Rezept auf ein Stück Papier] Hier, verlier es nicht. Wenn du keine Küche findest, kannst du ein einfaches Lagerfeuer benutzen.}
{199}{}{Alles klar.}

####################################################################
#
# THE Jolly Joe SHOW
#
# Author: Aleksandr Agafontsev aka Kerb
#
####################################################################

# Markers:
# GGG -- Joe phrases
# TTT -- replics over the "strange person"

####################################################################
# Story number 1. About The Ghost Train.
####################################################################

{300}{GGG}{Übrigens, hab ich dir schon vom Geisterzug erzählt? Also ...}

{301}{}{Noch nicht? Du meinst wohl zum hundertsten Mal?}
{302}{}{Noch ein Wort, und es gibt eine Geschichte über den Geister-Barkeeper!}
{303}{}{Sprich seinen Namen nicht leichtfertig aus!}
{304}{}{Hör nicht auf sie, Joe! Lass es krachen, Kumpel!}

{310}{GGG}{...Also!!! Die meisten glauben, dass er Seelen sammelt und sie geradewegs in die Hölle treibt ...}

{311}{}{Dann muss ich wohl eine Fahrkarte für meine Alte buchen!}
{312}{}{ }
{313}{}{Seelen? Dann brauchst du dir keine Sorgen zu machen. Ha-ha-ha!}
{314}{}{ }

{320}{GGG}{...Ihr von Bier vergiftetes Gehirn ist nicht schlau genug, um sich andere Versionen auszudenken ...}

{321}{}{Seit wann nennt man die Pisse, die du hier ausschenkst, Bier?}
{322}{}{Übrigens, das ist DEIN Bier, Joe!}
{323}{}{Verallgemeinere nicht! Mein Gehirn wurde von meiner Schlampe ausgefressen ...}
{324}{}{ }

{330}{GGG}{Ruhe da! Ähm ... Also, die wahre Geschichte des Zuges kennen nur wenige ...}

{331}{}{Wenige? Und du bist einer von ihnen? So was wie der Auserwählte?}
{332}{}{Wenige, die den hiesigen Fusel überlebt haben! Die Geschichte kennt dagegen jeder.}
{333}{}{ }
{334}{}{Gibt es noch andere Geheimnisse in diesem sprechenden Kürbis von dir?}

{340}{GGG}{Hör mal, du ... Ich erzähle dir Dinge, die sonst niemand erzählt!}

{341}{}{Im Ernst, Joe! Solche Geschichten habe ich nicht mal in der Klapse gehört!}
{342}{}{Dein Talent leuchtet heller als deine Glatze, mein Freund! Ich bin ganz Ohr!}
{343}{}{ }
{344}{}{ }

{345}{TTT}{::zieht unauffällig eine Waffe hervor::}

{350}{GGG}{Schon gut, du wirst dich später daran erinnern! Also – eigentlich hat der Zug einen Besitzer und einen Zweck ...}

{351}{}{Deine Eingeweide über die Schienen zu schmieren!}
{352}{}{Ordentlichen Fusel und Huren hierherzubringen!!! Ja, Joe! Weiter so!}
{353}{}{ }
{354}{}{ }

{355}{TTT}{::nimmt die Abzugssperre ab::}

{360}{GGG}{Das ist ... Nun, es ist wie bei den Ghulen! Man glaubt, sie seien Strahlung ausgesetzt gewesen, stimmt's?}
{370}{GGG}{Aber weißt du, wer sie wirklich sind? Aliens, die sich als Menschen tarnen! Und das war schon vor dem Krieg so!}

{371}{}{Nein, Joe. Die Menschen tarnen sich als sie. Ha-ha!}
{372}{}{Er steht in Flammen! Joe, du bist der Beste!}
{373}{}{Strahlung? Die haben sich dein Bier reingepumpt und sich nicht mal die Mühe gemacht, pinkeln zu gehen!}
{374}{}{ }

{380}{GGG}{...Und *sie* haben den Krieg angefangen, damit sie ohne Verkleidung herumlaufen können! Klingt doch plausibel!}

{381}{}{::kratzt sich mit offenem Mund am Kopf::}
{382}{}{Hast du dir also endlich Psycho in deinen Abendbecher gekippt?}
{383}{}{Du bist völlig neben der Spur, Joe!}
{384}{}{Du hast das Ganze quasi mit einem Zug angefangen...}
{385}{}{Äh ...}

{390}{GGG}{Zug? Was für ein Zug? Der, in dem ich Elvis getroffen habe?}

{391}{}{Ja. Der auch ein Außerirdischer war, nicht gestorben ist und nach Hause geflogen ist. Vergiss es!}
{392}{}{Du solltest uns lieber noch etwas von deinem Bier holen...}
{393}{}{ }
{394}{}{ }

{395}{TTT}{::steckt die Waffe weg und widmet sich wieder seinem Drink. Seltsam.::}

####################################################################
# Story number 2. "Joe the Invisible".
####################################################################

{400}{GGG}{Also gut, Jungs! Ich hab mich entschieden...}

{401}{}{Noch eine lange Geschichte erzählen? Du solltest dich lieber entscheiden, dich aufzuhängen!}
{402}{}{Endlich den Fusel in diesen Krügen durch etwas Gutes ersetzen?}
{403}{}{Dir ein Gehirn kaufen?}
{404}{}{ }

{410}{GGG}{Nein, nein... Ich... Ich erzähl euch nichts mehr...}

{411}{}{Heilige Scheiße, ich muss high sein und träumen!}
{412}{}{Und ich hör auf, den Röcken nachzujagen!}
{413}{}{Fängst du dann an, Männern nachzujagen? Oder hast du beschlossen, mit einem brahmin anzubandeln?}
{414}{}{Was hast du gesagt!?}

{420}{GGG}{S-Sch... Sei still! Du unterbrichst mich ständig... Sieht so aus, als gefiele dir das nicht...}

{421}{}{Komm schon, Joe! Du kannst dich gut ausdrücken! Wenn du nur deine Wörter zu sinnvollen Sätzen zusammenfügen könntest...}
{422}{}{ }
{423}{}{ }
{424}{}{Das gefällt mir, Joe! Ich war mal in einer Klapsmühle, und wenn ich dir zuhöre, werde ich ganz nostalgisch!}

{430}{GGG}{Also, ich habe beschlossen, diesen Moment mit einem Schwall neuen Biers zu feiern! Spitzenqualität!}
{440}{GGG}{Das Bier namens „Unsichtbarer Joe“! Also... ja...}
{450}{GGG}{Nur... Ihr müsst euch beteiligen, gerade mal 2 Bucks pro Pint.}

{451}{}{Gutes Bier, schweigsamer Joe ... Verdammt, wo bin ich?! Bring mich zurück in den "Tin angel"!}
{452}{}{Wenn der Anteil an brahmin-Pisse darin 5 Prozent niedriger ist als hier drin, ist es schon gut ...}
{453}{}{Was für Pisse?! Alle Getränke, die Joe serviert, werden aus frischem Rattenkot gemacht!}
{454}{}{Hey! Jeder gibt was dazu!}

{460}{GGG}{::Stille::}

{461}{}{Äh ... Joe?}
{462}{}{Wo ist das Bier?}
{463}{}{Ich verdurste!}
{464}{}{Ich sehe immer noch kein Bier!}

{470}{GGG}{Na ja, also ... Das ist der unsichtbare Joe! Nur im Menü ist er sichtbar ...}

{471}{}{Ich verstehe nicht ...}
{472}{}{Versucht Joe, witzig zu sein?}
{473}{}{Wow ... Das macht er doch sonst auch, oder?}
{474}{}{Wo soll das alles noch hinführen ...}

####################################################################
# Story number 3. About the book.
####################################################################

{480}{GGG}{Hey, Leute. Ich hab hier was geschrieben ...}

{481}{}{Geschrieben? Du hast statt einer Unterschrift ein X gemacht!}
{482}{}{ }
{483}{}{Was hast du geschrieben? Ein Testament? Wann ist die Beerdigung?}
{484}{}{ }

{490}{GGG}{Nein, ich meine es ernst!}
{500}{GGG}{Ich hab ein Buch geschrieben ... Na ja, vorerst nur den Titel ...}
{510}{GGG}{... Und das Stück hab ich auch verloren ...}

{511}{}{Im selben magischen Land, wo man deinen Kürbis durch eine Kokosnuss ersetzt hat?}
{512}{}{Verloren? Wohl eher hast du dir damit auf einer Toilette den Arsch abgewischt ...}
{513}{}{Hey, hört auf! Na los, Joe! Weiter so!}
{514}{}{ }

{520}{GGG}{Na ja ... Es geht um einen Mann, der in irgendeinem Bunker gelandet ist ... Und da war ein ...}

{521}{}{Sack voll brahmin-Mist?}
{522}{}{Ein Bunker voller Nutten und Schnaps! Ja, Joe! Mehr!!!}
{523}{}{ }
{524}{}{ }

{530}{GGG}{Nein, nein ... Ein Tank voller grünem Zeug ... Wie hieß das noch ...}
{540}{GGG}{Ah! Forced Amplification Gainer! FAG! Den Namen hab ich mir selbst ausgedacht!}

{541}{}{Ja, wer hätte daran gezweifelt ...}
{542}{}{Denk dir lieber aus, wie wir an guten Fusel kommen ...}
{543}{}{ }
{544}{}{ }

{550}{GGG}{Also fällt er da rein! Und verwandelt sich in eine Art Abscheulichkeit, einen Mischling, so eine Kreuzung aus Kakerlake und Skorpion ...}
{560}{GGG}{... Und landet in einer Pfütze aus radioaktivem Abfall.}

{561}{}{Hey, genau wie meine Schwiegermutter!}
{562}{}{Oh, ich hätte nichts dagegen, mit jemandem gekreuzt zu werden ...}
{563}{}{Halt die Klappe, du notgeiler Schweinehund! Meinst du etwa wieder meine Frau?}
{564}{}{ }

{570}{GGG}{Ruhe da!}
{580}{GGG}{... Und dann fängt er an, Leute zu schnappen und sie in riesige grüne Monster zu verwandeln!}
{590}{GGG}{Manche werden telepathisch, nachdem sie mit FAG in Kontakt gekommen sind! Und er will die ganze Welt in solche Dinger verwandeln!}
{600}{GGG}{Und er nennt sich ... Wie war der Name noch? Der Besitzer? Der Schöpfer? Nein, das klingt dämlich. Ach, vergiss es! Also ...}

{601}{}{Welcher Mistkerl hat ihm Drogen gegeben?}
{602}{}{Hey, Joe! Gib mir eine Handvoll von dem Zeug, das du rauchst!}
{603}{}{Und dann taucht so ein harter Held auf und metzelt deinen „Besitzer“ nieder? Ha-ha-ha!}
{604}{}{Ja, selbst die dämlichen Komiker des zwanzigsten Jahrhunderts wären nie auf so eine Geschichte gekommen.}

{610}{GGG}{Ah! Also, wie war's?}

{611}{}{ }
{612}{}{ }
{613}{}{ }
{614}{}{Ich hatte einen Freund, Dr. Moreau. Der hätte sich totgelacht und dir dann wegen dieses unwissenschaftlichen Unsinns den Kürbis abgedreht ... FAG, verdammt ...}

{620}{GGG}{Ich habe selbst so einen Kerl gesehen! Er hat nur einen Blick auf mich geworfen – und ist in meinen Kopf gekrochen!}

{621}{}{... Und war von der Menge an leerem Raum völlig verblüfft.}
{622}{}{Hör endlich auf, Joe. Schenk mir lieber noch einen Bloody Mary ein ...}
{623}{}{ }
{624}{}{ }

####################################################################
# Story number 4. About The Great War.
####################################################################

{630}{GGG}{J-... Leute! Seht nur, wie sich das Leben seit vor dem Krieg verändert hat!}

{631}{}{Ja. An normalen Fusel und Huren kommt man jetzt schwerer ran.}
{632}{}{Oh! Guten Morgen, Herr Genie!}
{633}{}{Hat dein Kürbis beschlossen, eine Doktorarbeit in Philosophie zu schreiben?}
{634}{}{Ja, damals war es noch verboten, Barkeeper wegen verwässerter Drinks zu lynchen! Nur so nebenbei.}

{640}{GGG}{Nein ... darum geht's mir nicht. Ich rede von all den neuen Dingen, die aufgetaucht sind ...}
{650}{GGG}{Rad-Skorpione ... Rad-Kakerlaken ... Übrigens, warum-}

{651}{}{Wenn du jetzt fragst, was an denen so RAD ist, erschieß ich dich!}
{652}{}{Für diesen dämlichen Witz sollte längst jemand hingerichtet werden!}
{653}{}{Ich glaube, den hab ich schon mal irgendwo gehört ...}
{654}{}{Du solltest deinem Fusel besser das Präfix „Rad“ verpassen. Nach deinem „Bier“ brauchst du nicht mal mehr eine Taschenlampe!}

{660}{GGG}{Hm ... Ich wollte dir von dem Ghoul-Vampir aus Pennsylvania erzählen!}

{661}{}{Aus Transsilvanien, du Sonderling! Graf ... äh ... Glad, der Inhalator!}
{662}{}{Der Vampir aus der Bar, der uns das Geld aus den Taschen saugt.}
{663}{}{ }
{664}{}{Joe, leg los! Du bist mein einziger Ersatz für einen Fernseher.}

{670}{GGG}{Unterbrich mich nicht! Also ... Es war einmal ein guter Mann.}
{680}{GGG}{Und er liebte im Leben zwei Dinge: seine Arbeit und seine Freizeit.}
{690}{GGG}{Er arbeitete bei der Blutbank und sammelte sozusagen das Blut der Leute. Und er war glücklich, dass er damit anderen Menschen half.}
{700}{GGG}{Und er entspannte sich gern in der Bar auf der anderen Straßenseite ...}

{701}{}{... Und die Bar hieß „Tin angel“}
{702}{}{... Eines Tages trank er statt einer weiteren Flasche Scheißbier das Blut des Barkeepers. Ende.}
{703}{}{ }
{704}{}{Psst! Er macht gleich wie immer einen Witz.}

{710}{GGG}{Als der Krieg ausbrach, wurde die Bank geschlossen und dann die Stadt zerstört ... Durch, äh ... einen Angriff!}
{720}{GGG}{Und er saß immer noch in der Bar. Und wurde zum Ghoul! Und sein von der Strahlung gegrilltes Hirn war sozusagen hinüber!}

{721}{}{Verstanden! Dann verkleidete er sich als Barkeeper und eröffnete eine Bar namens „Tin angel“!}
{722}{}{Hast du das erraten, weil Joe was über das Hirn gesagt hat?}
{723}{}{Äh, ich hab plötzlich Lust, nach Hause zu gehen ...}
{724}{}{ }

{730}{GGG}{Äh ... Nein. Er hatte vergessen, was er tat. Er erinnerte sich nur daran, dass er Blut brauchte, um Menschen zu helfen.}
{740}{GGG}{Und daran, dass er aus irgendeinem Grund früher in eine bestimmte Bar gegangen war. Also schloss er, dass das Blut der Grund dafür war.}
{750}{GGG}{Aber wie hieß die Bar noch gleich? Daran konnte er sich nicht erinnern!}
{760}{GGG}{Und jetzt wandert er über die Erde, auf der Suche nach Bars. Er betritt sie nachts, tötet die Gäste und fuellt ihr Blut in Flaschen ab!}
{770}{GGG}{Was nicht hineinpasst, trinkt er selbst aus ...}
{780}{GGG}{Und er wird erst aufhören, wenn er diese Bar findet ... Die seit 2077 in Trümmern liegt.}

{781}{}{Also wird er seine Bar nicht finden? Wie beschissen ...}
{782}{}{Das ist weder witzig noch gruselig. Äh ... Es wird doch nicht so bald dunkel, oder?}
{783}{}{Leute, Pennsylvania ist weit weg von Nevada, oder? Oder etwa nicht?}
{784}{}{Ich hab sowieso Joes Pampe statt Blut in den Adern. Noch einen!}

{785}{TTT}{Auf den armen Kerl aus Pennsylvania!}

####################################################################
# Story number 5. About Halloween.
####################################################################

{790}{GGG}{Leute! Feiern wir Halloween?}

{791}{}{Aber sicher! Das ist der einzige Grund, warum dein Kürbis hier ist.}
{792}{}{Schön, dass du ihn leer hältst. Da ist genug Platz für ein paar Kerzen.}
{793}{}{Nur wenn du uns zu Ehren des Feiertags die Drinks spendierst!}
{794}{}{Für so eine Plörre sollte eigentlich er uns bezahlen!}

{800}{GGG}{Ja! Ich spendier eine Runde! Ich rolle das Fass mit meinem besten Bier raus ...}

{801}{}{Warum bist du plötzlich so großzügig?}
{802}{}{Und zu Ehren der Kürbisse ... Äh ... der Kürbisse machen wir eine Party! Mit Schnaps und Nutten!}
{803}{}{Hey! Warum bist du so aufgeregt, du Hormonbündel?!}
{804}{}{ }

{810}{GGG}{Nein, nein. Ich habe nur schöne Erinnerungen an Halloween ...}

{811}{}{An den Psychopathen aus Sparks, der in der Halloween-Nacht vier Leute mit dem „Ripper“ häutete und abstach, zwei weitere ausweidete, drei andere den ganzen Tag folterte und die Leichen dann am Stadtrand vergrub?}
{812}{}{Äh ... Von den dreien hieß es, sie seien vermisst ... Du bist doch nicht aus Sparks, oder?}
{813}{}{Du hast auch nach Batterien gesucht ... Nicht etwa für den „Ripper“? Nein?}
{814}{}{Hey! Halt verdammt noch mal die Klappe!}

{820}{GGG}{Nein! Es geht um meine Frau ...}
{830}{GGG}{Oh! Sie hatte eine ganz besondere Art, mich umzuhauen. Oder sollte ich sagen, mir das Hirn wegzupusten.}
{840}{GGG}{Im Vergleich zu ihr seid ihr bloß Kinder ...}

{841}{}{Hirn? Du hattest mal eins?}
{842}{}{Das war fair, alter Junge! Du hast sie gefickt, sie hat dir das Hirn gefickt!}
{843}{}{Geteiltes Leid ist halbes Leid! Erzähl schon, Kumpel!}
{844}{}{ }

{850}{GGG}{Aber ... Aber ich habe sie immer noch geliebt.}
{860}{GGG}{An Halloween vor 20 Jahren haben wir uns zum letzten Mal gesehen.}
{870}{GGG}{Es tut weh, mich an meine letzten Worte an sie zu erinnern: „Hau ab zu deiner Mutter nach Iowa, du wandelnder Friedhof der Leguane am Spieß!“}
{880}{GGG}{Ich dachte, wir würden uns am nächsten Tag wie immer wieder versöhnen ...}
{890}{GGG}{... Und sie ging Kräuter sammeln und verirrte sich ...}
{900}{GGG}{Sie hat meine Lieblings-Geckoschenkel mit Broc-Blüten so köstlich zubereitet ...}

{901}{}{Ha-ha! Frau Kürbis ist vor Herrn Kürbis davongelaufen!}
{902}{}{Halt die Klappe, Arschloch!}
{903}{}{Komm schon, Joe, lass die Nase nicht hängen.}
{904}{}{Lasst jetzt das Fass rollen! Ich zahle! Und stoßt unbedingt mit uns an!}

####################################################################
# Story number 6. About the bald head (sample).
# Author: Aleksandr Poshelyuzhin
####################################################################

{910}{GGG}{Viele von euch fragen sich, was ich mit meinen Haaren gemacht habe.}
{920}{GGG}{Also. Einmal kam ich zur Nuka-Cola-Fabrik ...}

{921}{}{Was ist los, Joe, hast du deinen alten Job satt?}
{922}{}{Warum bist du da hingegangen? Hier bei uns ist es doch viel besser.}
{923}{}{Wenn du stattdessen eine Ladung richtiges Bier holen würdest, wäre das interessanter.}
{924}{}{Hör nicht auf diese Idioten! Was ist dann passiert?}

{930}{GGG}{Ich kam zur Fabrik und sagte ...}

{931}{}{Joe kann sprechen! Unglaublich!}
{932}{}{Ach, komm schon! Jetzt reicht's aber!}
{933}{}{Du erzählst das jetzt zum hundertsten Mal ...}
{934}{}{Ich wusste, dass du wegen Cola kahl geworden bist. Du musst wissen, wann Schluss ist, Joe!}

{940}{GGG}{Nein, wartet! Lasst mich erzählen ...}
{950}{GGG}{Ich ging zur Fabrik und sagte: „Woher bekommt ihr das Wasser für Cola?“}
{960}{GGG}{Und sie sagen alle ganz hochmütig zu mir: „Ach, wir holen es aus der Kanalisation.“ „Was?!“, sage ich zu ihnen. „Das ist giftig!“}
{970}{GGG}{Und sie sagten: „Du glaubst, dein Gesöff ist sauberer?“}
{980}{GGG}{Ich glaubte ihnen nicht. „Zeigt es mir!“, sagte ich.}
{990}{GGG}{Sie führten mich in die Kanalisation, und …}

{991}{}{Was? Was war da? Ratten? Mutanten?}
{992}{}{Joe hat sich in die Hose gemacht und ist geflohen.}
{993}{}{Und in den Rohren fließt Cola statt Urin. Kicher.}
{994}{}{Und da ist der Bettler, der dasitzt und die Flaschen mit Urin fuellt.}

{995}{TTT}{Bist du wirklich freiwillig in die Kanalisation gegangen? Du hast sie wohl nicht mehr alle …}

{1000}{GGG}{Nein, nein, warte, lass mich ausreden!}
{1010}{GGG}{Und da ist … Da ist … Oh mein Gott, das kann ich nicht glauben!!!}
{1020}{GGG}{::lacht so sehr, dass es aussieht, als würde er gleich auf den Boden fallen::}
{1030}{GGG}{Da ist … Oh, mein …}
{1040}{GGG}{::wischt sich eine Träne weg:: Äh …}
{1050}{GGG}{Nein, ich bediene lieber den Tisch fünf mit Fusel.}
