{100}{}{Du siehst einen Händler.}
{101}{}{Du siehst einen Karawanenführer. Seiner sonnengebräunten Haut nach ist er viel unterwegs.}
{102}{}{Geh mir aus dem Weg!}
{103}{}{All meine Waren sind zerstört! Ich bin ruiniert! Pleite!!!}
{104}{}{Morgen sind wir nicht mehr hier.}
{105}{}{Genieß den herrlichen Geschmack von Nuka-Cola!}
{106}{}{Oh ...}
{107}{}{Dank dir sieht unsere Zukunft endlich ein bisschen heller aus. Danke.}
{108}{}{Die Waren im Wagen waren vollständig zerstört worden.}

{110}{}{Brennen dir die Füße von der langen Reise? Hier, nimm eine Flasche zur Erfrischung. Kostet dich nur 3 Dollar.}
{111}{}{Verlockend, aber was ist das für ein Getränk und wo kommt es her?}
{112}{}{Danke, aber nein.}
{113}{}{Nun, ich hatte Glück, ein paar Kisten Vorkriegs-Nuka-Cola zu finden. Ich habe sie selbst probiert – ein absolut sauberes Qualitätsprodukt! Und übrigens viel besser als das aus der örtlichen Fabrik.}
{114}{}{Du hast also nichts mit der örtlichen Nuka-Cola-Fabrik zu tun?}
{115}{}{Oh nein. Ich stamme selbst nicht von hier und war überrascht, als ich erfuhr, dass es hier eine ganze Fabrik gibt. Also muss ich die Cola billiger verkaufen, damit ich sie loswerde, bevor die Schläger aus der Fabrik davon erfahren ... Wobei ich wahrscheinlich übertreibe, hehe. Was sollte eine so große Fabrik schon an einem kleinen Händler aus dem Ödland interessieren?}
{116}{}{Vielleicht. Ich wette, der Fabrik würde das ganz und gar nicht gefallen.}

{117}{}{Zum Glück gibt es in dieser Stadt einen Sheriff, der Gesetz und Gerechtigkeit achtet. Also kann ich dir ein paar Flaschen verkaufen. Dafür bist du doch hier, oder?}
{118}{}{Ja.}

{119}{}{Komm schon. Nur 3 Dollar pro Flasche!}
{120}{}{Gib mir eine Flasche Vorkriegs-Nuka-Cola.}
{121}{}{Gib mir drei Flaschen Vorkriegs-Nuka-Cola.}
{122}{}{Wusstest du, dass deine Cola schon aus einer Meile Entfernung nach Strahlung stinkt?}
{123}{}{Die Fabrik hat mich gebeten, dich lästigen Kerl auszuschalten. Aber ich bin offen für friedliche Lösungen.}
{124}{}{Hey, sei nicht blöd! Der Sheriff selbst hat mir erlaubt, hier zu verkaufen ... Obwohl er damit gedroht hat, mich aus der Stadt zu werfen, falls ich Ärger mache. Außerdem würde die örtliche Karawane das nicht gutheißen. Und schließlich ist es nicht fair! Ich habe mir meine Ware ehrlich verdient und sie ganz allein hierhergeschleppt. Und jetzt bin ich plötzlich ein Verbrecher! Nur weil die Fabrik das Wichtigste nicht anerkennen will – dass ihr Produkt viel schlechter ist als das aus der Vorkriegszeit. Probier es einfach, dann merkst du sofort den Unterschied! Möchtest du etwas?}
{125}{}{Im Gegensatz zu deiner Ware stinken die Produkte der Fabrik nicht schon aus einer Meile Entfernung nach Strahlung.}
{126}{}{Wirklich? Wow, was für eine Überraschung ... Na ja, dann muss ich wohl ... äh ... das Zeug irgendwo am Stadtrand zerschlagen.}
{127}{}{Du bist ein schlechter Schauspieler. Du wusstest, dass die Flaschen verstrahlt sind, und hast sie trotzdem hierhergebracht, um sie den Einheimischen zu verkaufen. Plagt dich dein Gewissen nicht?}
{128}{}{[Er sieht langsam müde aus] Vielleicht … Aber hör zu. In dem Dorf, aus dem mein Sohn und ich kommen, ist niemand mehr übrig, weil es dort unmöglich geworden war zu leben. Eines Tages erfuhr ich von einem verlassenen Nuka-Cola-Truck. Die Ladung in meinem Wagen ist alles, was dort war. Ehrlich. Ich wollte nur schnell ein paar Kronkorken verdienen und aus der Stadt verschwinden. Mein Sohn und ich haben weder Unterkunft noch Essen. Wir brauchen Geld, um Vorräte und Munition zu kaufen. Unter anderen Umständen müsste ich nicht in einen verstrahlten Truck klettern. Außerdem sind die Flaschen nicht so verstrahlt, dass es jemand merken würde.}
{129}{}{Dann kaufe ich dir deine ganze Cola ab.}
{130}{}{Dann werde ich dich bei der Polizei anzeigen.}
{131}{}{Lass den Scheiß, bevor die Polizei dich verhaftet und aus der Stadt jagt.}
{132}{}{Ich muss darüber nachdenken.}
{133}{}{Wag es ja nicht! Wir haben so hart gearbeitet, um die Flaschen zu holen und hierherzubringen! Bitte, hab Erbarmen mit mir und meinem Sohn! Wir haben nirgendwohin, wo wir hingehen könnten, unser Dorf ist leer. Ich verspreche, wir verschwinden, sobald wir Vorräte und Munition für den Weg haben.}
{134}{}{Äh … Trotzdem haben wir keine Wahl. Wir haben nirgendwohin, wo wir hingehen könnten, unser Dorf ist leer. Ich verspreche, wir verschwinden, sobald wir Vorräte und Munition für den Weg haben.}
{135}{}{Na schön, dann eben nicht. Du MUSST JETZT verschwinden!}
{136}{}{Ich möchte dieses Getränk kaufen.}
{137}{}{SUPER! Wie viele Flaschen?}
{138}{}{}
{139}{}{ für }
{140}{}{ Kronkorken.}
{141}{}{Alle }
{142}{}{Danke! Wenn du mehr willst – komm wieder.}
{143}{}{In Ordnung.}
{144}{}{Danke … Hey, sieh mal! Die letzte Kiste ist leer, aber meine Taschen sind es nicht. Hehe, endlich ist es vorbei und wir können gehen. Danke, deine Hilfe war sehr willkommen!}
{145}{}{Das ist gut.}
{146}{}{Warum arbeitest du nicht als offizieller Kurier für die Fabrik? Du hast alle nötigen Qualitäten.}
{147}{}{Das wäre großartig, aber sie halten uns für ungeeignet. Aus irgendeinem Grund konnte ich mich mit den Typen nicht einigen. Sie denken, ein Kurier muss gut aussehen und gut riechen. Dabei kenne ich mich in der Gegend aus und kann gut mit meinem Jagdgewehr umgehen, und das ist wichtiger als gutes Aussehen. Außerdem kenne ich die Mentalität der Einheimischen viel besser als diese Stadtschnösel. Aber die Manager in der Fabrik sehen das anders.}
{148}{}{Hm. Ich verstehe.}

{149}{}{Ich konnte einen Deal mit dem Geschäftsführer aushandeln. Sie sind bereit, deine Karawane als offiziellen Kurier anzunehmen.}
{150}{}{Wow, du musst hier einen ausgezeichneten Ruf haben! Danke für die Hilfe, allein hätte ich den Job nie bekommen. Hier, nimm ein paar Nuka-Cola als Geschenk.}
{151}{}{Ja, pass auf dich auf.}
