{100}{}{Sie sehen Direktor Skinner.}
{101}{}{Sie sehen den Leiter der Nuka-Cola-Fabrik. Er hat sein Geschäftsgesicht aufgesetzt.}

#Íà÷àëî ğàçãîâîğà
{110}{}{Guten Tag. Was führt Sie her?}
{111}{}{Entschuldigen Sie die Störung.}
{112}{}{Sonst noch was?}

#Àâòîìàòû êîëû:
{120}{}{Ich habe gehört, dass Ihre Nuka-Cola-Verkaufsautomaten ausgeraubt werden. Haben Sie den Dieb schon erwischt?}
{121}{}{Nein! Der Kerl ist völlig unauffindbar. Sheriff Barton sucht wie wild nach ihm. Das Einzige, was wir wissen, ist, wie er seine Raubzüge durchführt. Leider ist uns noch keine gute Abwehrmaßnahme eingefallen. Ich fürchte, irgendwann müssen wir auf herkömmliche Verkaufsmethoden zurückgreifen und auf Verkaufsautomaten verzichten. Unsere Produkte werden dadurch leider teurer. Falls Ihnen etwas Verdächtiges auffällt, melden Sie es bitte dem Sheriff. Wir müssen den Räuber um jeden Preis fassen!}
{122}{}{Ich gestehe, ich bin es, der Sie ausgeraubt hat. Jetzt fühle ich mich deswegen schlecht.}
{123}{}{Wie schade, äh … Ich hoffe, Sie finden den Täter.}
{124}{}{Ach, komm schon! Bring mich nicht zum Lachen! Das war wahrscheinlich irgendein Halbstarker aus dem Randgebiet von Salt Lake oder diese Mistkerle aus Provo.}
{125}{}{Provo?}
{126}{}{Oh ... Na, na ...}
{127}{}{Ja, ich glaube eher, dass sie es waren. Hast du noch nie davon gehört? Das ist eine Siedlung südlich von hier, bewohnt von Gesetzlosen, die Burton aus der Stadt vertrieben hat. Seitdem hassen sie ganz Salt Lake. Früher waren sie die Könige der Unterwelt der Stadt und konnten entscheiden, wen sie vernichten und wen sie verschonen. Zum Glück ist das Vergangenheit. Du solltest dich besser von der Gegend fernhalten, genau wie wir.}
{128}{}{Verstanden.}

#Ïğîäàæà ôèëüòğà
{140}{}{Ich habe das Teil gefunden, das man braucht, um den artesischen Turm in Betrieb zu nehmen.}
{141}{}{Mein Gott! Das gibt's doch nicht! Ist das wahr?! Und ... funktioniert es?}
{142}{}{Ich bin mir nicht ganz sicher, aber es sieht gut aus.}
{143}{}{Weißt du, ich werde nicht einmal Fragen stellen! Ich suche schon seit Jahren nach diesem Teil! Bitte, verkauf es mir!}
{144}{}{Warum sollte ich es dir verkaufen? Soweit ich weiß, brauchen die Bürger auch Wasser ...}
{145}{}{Es liegt im Interesse aller, dass der Turm richtig funktioniert. Wasser ist die Grundlage des Lebens ... und unserer Produktion. Je sauberer es ist, desto höher sind unsere Einnahmen und desto zufriedener sind unsere Kunden. Die Fabrik wird Dutzende Karawanen nach Salt Lake locken! Sie wird den hiesigen Handel gewaltig ankurbeln!}
{146}{}{Ist das alles?}
{147}{}{Außerdem möchte ich darauf hinweisen, dass unsere Fabrik der wohlhabendste Betrieb der Stadt ist. Niemand wird dir mehr für dieses Teil bieten können als wir. Verstehst du?}
{148}{}{Ja. Wie viel bietest du?}

{149}{}{20.000 Dollar. Denk daran, dass sich unser Kontostand ständig ändert und die Gewinne jeden Tag schwanken. Der Preis, den ich genannt habe, kann also morgen schon anders sein.}
{150}{}{Einverstanden. Hier ist das Teil.}
{151}{}{Nein, ich suche lieber nach anderen Käufern.}
{152}{}{Oh ... Nun gut. Ich bin mir allerdings hundertprozentig sicher, dass du zurückkommen wirst, denn *niemand* in der Stadt kann dir mehr Geld bieten. Glaub mir.}
{153}{}{Wir werden sehen ...}
{154}{}{Du hast den Wasserfilter für den artesischen Turm geliefert und damit die Lebensqualität in der Gegend verbessert.}
{155}{}{[Der Fabrikleiter ist ganz auf das Teil fixiert und bemerkt dich gar nicht.]}
{156}{}{Auf Wiedersehen.}
{157}{}{[Du lässt das Teil auf den Boden fallen, worauf sich dem Fabrikleiter die Haare sträuben.] WAS MACHST DU DA!!!}
{158}{}{Ach, keine Sorge, alles in Ordnung. Lass mich das aufheben ...}

#Ïğî àğòåçèàíñêóş áàøíş
{160}{}{Neulich bin ich in den artesischen Turm geraten ... Warum bringst du ihn nicht zum Laufen?}
{161}{}{Ja. Die ganze Stadt redet schon seit Ewigkeiten darüber. Aber bisher blieb es bei Gesprächen – nichts als Gerede.}
{162}{}{Was ist das Problem?}
{163}{}{Wir haben keinen Filter, um das Wasser zu reinigen und Verunreinigungen wie Sand und Kieselsteine zu entfernen. Wenn wir die Turbinen ohne das Ding starten, sind sie innerhalb weniger Stunden unbrauchbar.}
{164}{}{Ist es so schwer, diesen Filter zu finden?}
{165}{}{Und ob! Es gibt nicht viele Städte in der Gegend, die artesische Türme dieser Größe besitzen. Wir haben Karawanen zu so vielen Orten geschickt! Niemand konnte das Teil finden, weder in New Reno noch in Denver, nicht einmal in Vegas – die Stadt ist riesig und hat viel saubereres Wasser, aber selbst dort gab es keinen passenden Filter. Wir haben die Hoffnung so gut wie aufgegeben.}
{166}{}{Kann man ihn durch etwas anderes ersetzen?}
{167}{}{Ich fürchte nicht. In der Gegend gibt es keine entsprechenden Ersatzteile.}
{168}{}{Wie schade. Es wäre wirklich schön, das Teil zu finden ...}
{169}{}{}

#Òğåòèé êâåñò - ïî÷èíêà ÏËÊ:
{170}{}{Was ist die nächste Aufgabe?}
{171}{}{Ich fürchte, du musst auf Geschäftsreise gehen. Natürlich nur, wenn du etwas Geld verdienen willst.}
{172}{}{Erzähl mir bitte mehr.}
{173}{}{Kein Interesse.}
{174}{}{Wenn unser Betrieb effizient arbeiten soll, müssen wir wieder etwas automatisieren. Das Hauptproblem ist im Moment die speicherprogrammierbare Steuerung. Um den Rest können sich unsere Techniker kümmern, aber ich glaube nicht, dass ich hier in Salt Lake je auch nur einen einzigen Programmierer gesehen habe. Du musst in einer anderen Stadt einen Fachmann finden und das Ding wieder zum Laufen bringen. Das ist eine sehr wichtige Aufgabe. Glaubst du, du schaffst das?}
{175}{}{Ich erledige das.}
{176}{}{Dann geh bitte zu unserem Chefmechaniker, er ist im nahe gelegenen Gebäude. Er wird dir alles genau erklären. Ich übernehme deine Ausgaben, sobald der Auftrag erledigt ist. Ach, und hier ist eine Fahrkarte für die Postkutsche. Vielleicht kannst du sie gebrauchen.}
{177}{}{In Ordnung.}
{178}{}{Der Auftrag ist erledigt. Hier ist ein funktionierender Regler.}
{179}{}{Es freut mich sehr, wenn alles so funktioniert, wie es soll! Ich bin dir dankbar. Hier ist deine Bezahlung: }
{180}{}{Die Zusammenarbeit mit dir war angenehm.}
{181}{}{Auf Wiedersehen.}

#Îáùèå âîïğîñû
{200}{}{Bist du hier der Direktor?}
{201}{}{Kannst du mir etwas über die Fabrik erzählen?}
{202}{}{Wie läuft das Geschäft in der Fabrik?}

{203}{}{Ganz recht. Ich heiße Skinner. Direktor Skinner.}
{204}{}{Wie bist du an deine Stellung gekommen?}
{205}{}{Ich bin der Erbe des Unternehmens.}
{206}{}{Wirklich?! Keine Bandenkriege, keine Leichen von Konkurrenten im See, keine Erpressung oder Einschüchterung, gar nichts?}
{207}{}{Hm... Kommst du vielleicht aus Reno? Dort scheinen sie Probleme am liebsten mit großen Knüppeln zu lösen. Hier weiß jeder, dass kein Möchtegern ein Unternehmen leiten könnte: Ihm fehlen das Wissen, die Fähigkeiten und die Unterstützung der Gemeinschaft.}
{208}{}{Verstehe. Darf ich noch etwas fragen?}
{209}{}{Na gut, das reicht.}
{210}{}{Für mich ist das unmöglich - ich glaube, du bist über viele Leichen gegangen, um deine Ziele zu erreichen.}
{211}{}{Mein Vorfahr besaß die Fabrik schon vor dem Krieg, aber damals stellte man hier ganz andere Getränke her. Vor zehn Jahren begann ich aktiv damit, die Fabrik wieder aufzubauen: Ich fand Nuka-Cola Rezepte und stellte die nötigen Leute zusammen. Die Arbeitskräfte kamen aus den Zwangsarbeitslagern der Einheimischen. Die alten Anlagen zu reparieren, erwies sich als viel schwieriger. Es dauerte viele Jahre, bis wir alles wieder zum Laufen brachten.}
{212}{}{Was für ein Unsinn?! Nun ja... Es stimmt, dass Zwangsarbeiter für uns gearbeitet haben. Das waren wirklich harte Zeiten.}

{213}{}{Der Fabrik geht es in letzter Zeit nicht gut. Die Produktion geht zurück, unsere Einnahmen sind gering und die Leute verlieren die Motivation zu arbeiten.}
{214}{}{Die Fabrik läuft in letzter Zeit ziemlich gut. Wir haben inzwischen so viele Aufträge, dass uns manchmal die Arbeitskräfte ausgehen, um sie zu erledigen! Unsere Einnahmen sind hoch und die Leute sind motivierter denn je. Wir müssen die Gelegenheit beim Schopf packen und das Beste aus der Situation machen.}
{215}{}{Alles wie immer: Die Leute sind faul, die Einnahmen lassen zu wünschen übrig, aber wir haben genug, um vorerst über die Runden zu kommen ... Ich weiß allerdings nicht, wie lange wir noch durchhalten.}
{216}{}{Außerdem hat irgendein Arschloch unsere Produktion sabotiert. Wir konnten nicht herausfinden, wer es war. Das muss ein verdammt gerissener Mistkerl gewesen sein!}
{217}{}{Ach ja, irgendein Dreckskerl hat auch noch unsere Nuka-Cola-Automaten ausgeraubt. Der schlaue Punk hinterlässt keine Spuren und geht äußerst vorsichtig vor. Ich habe deswegen schon mit dem Sheriff gesprochen. Ich bin sicher, Herr Burton wird sich umgehend um das Problem kümmern.}
{218}{}{Verstehe.}
{219}{}{Woher bekommt ihr die Zutaten für die Produktion?}
{220}{}{In der Gegend um Salt Lake City gibt es mehrere Farmen der Mormonen. Dort bauen sie alle nötigen Pflanzen an. Salz und Alkali gewinnen wir aus den Vorkommen im Great Salt Lake. Damit hatten wir also keine Probleme.}

#Âòîğîé êâåñò - äåòàëü ó êàğàâàíùèêà
{230}{}{Was ist die nächste Aufgabe?}
{231}{}{Ein Karawanenhändler will aus unserer Notlage Kapital schlagen. Wir hatten vereinbart, dass er uns einen neuen Encoder besorgt, um den kaputten zu ersetzen. Als Preis hatten wir 300 $ ausgemacht. Jetzt, wo er den Encoder hat, verlangt er 1.000 $!}
{232}{}{[Weiter.]}
{233}{}{Dieser Karawanenhändler hat vielleicht Nerven! Jeden Tag erhöht er den Preis noch weiter, und wir haben keine Möglichkeit, ihn bei einem anderen Händler zu kaufen. Der Sheriff hat beschlossen, sich aus unserem Interessenkonflikt herauszuhalten. Deshalb mache ich dir folgendes Angebot: Besorg ihm den Encoder mit *jedem* Mittel, das du für nötig hältst, und ich kaufe ihn dir für einen angemessenen Preis von 300 $ ab. So lösen wir gleich mehrere Probleme: Ich bekomme das Teil zu einem fairen Preis, du verdienst etwas Geld, und der Karawanenhändler bekommt, was er für seine Gier verdient.}
{234}{}{Klingt gut. Wo finde ich den Karawanenhändler?}
{235}{}{Mit solchen zwielichtigen Geschäften will ich nichts zu tun haben. Tut mir leid.}
{236}{}{Ausgezeichnet. Der Karawanenhändler wohnt im The 6'th Bullet.}
{237}{}{Verstanden.}
{238}{}{Ich habe den Encoder.}
{239}{}{Ausgezeichnet. Wie vereinbart – hier sind deine 300 $.}
{240}{}{Kinderleicht. Hast du noch andere Aufgaben?}
{241}{}{Danke, aber unsere Zusammenarbeit muss vorerst auf Eis gelegt werden. Ich komme wieder, wenn ich bereit bin weiterzumumachen.}

#Ïåğâûé êâåñò - ïğîäàâåö äîâîåííîé êîëû
{250}{}{Ich suche Arbeit. Vielleicht kannst du eine Stelle für mich finden?}
{251}{}{Im Moment habe ich genug Arbeiter ... Andererseits: Bist du von hier?}
{252}{}{Oh nein, ich bin nur auf der Durchreise.}
{253}{}{Auf der Durchreise, sagst du? Dann hätte ich vielleicht etwas für dich. Du könntest mir ein paar Gefallen tun und dann weiterziehen.}
{254}{}{Klingt gut. Um was für Gefallen geht es?}

{255}{}{Vor Kurzem ist im Geschäftsviertel eine zwielichtige Person aufgetaucht. Sie wagt es, in dieser Stadt Nuka-Cola zu verkaufen, obwohl sie nichts mit meiner Fabrik zu tun hat. Wir haben schon genug Probleme, und dieser Kerl macht alles nur noch schlimmer. Wenn du ihn aus der Stadt schaffst, zahle ich dir 300 Dollar.}
{256}{}{Lass mich dich erst etwas fragen.}
{257}{}{Den zwielichtigen Nuka-Cola-Verkäufer aus der Stadt schaffen? Mach ich.}
{258}{}{Weißt du, ich finde nicht, dass es fair ist, so Geschäfte zu machen. Ich lehne ab.}

{259}{}{Hmm ... Vergiss nicht, die Tür hinter dir zuzumachen.}
{260}{}{Äh, okay.}
{261}{}{Danke für deine Zeit. Aber denk daran: Ich verlange nicht von dir, etwas Illegales zu tun. Mir ist jedoch egal, wie du mit dem Kerl umgehst. Auf jeden Fall werde ich jede Beteiligung an irgendwelchem Fehlverhalten abstreiten, und der Sheriff vertraut mir viel mehr als dir.}
{262}{}{Ich werde mir deine ... Loyalität merken. Der Auftrag ist so gut wie erledigt.}

{263}{}{Natürlich. Was möchtest du wissen?}
{264}{}{Wo finde ich diesen Verkäufer?}
{265}{}{Wie wirkt sich so ein kleiner Laden auf dein Unternehmen aus?}
{266}{}{Handelt der Verkäufer mit deinem Nuka-Cola?}
{267}{}{Warum bittest du nicht die Polizei um Hilfe?}
{268}{}{Verstehe. Ich habe noch andere Fragen.}
{269}{}{Wie gesagt: im Karawanenlager.}
{270}{}{Du denkst, es ist nur eine „kleine Verkaufsstelle“. Aber überleg mal: Wie kann irgendein Flashman so viele Waren zum Verkauf haben? Ich weiß nicht, woher er sein Nuka-Cola bekommt, aber jedenfalls nicht von uns. Niemand weiß, wie er so viele Flaschen für sein Lager bekommen hat. Vielleicht hat er irgendwo sogar ein ganzes Lagerhaus. Noch schlimmer ist, dass seine Waren auch weniger kosten. Diese Konkurrenz könnte dem Ruf der Fabrik schaden.}
{271}{}{Nein, seine Waren stammen nicht aus unseren Lagern. Wir haben das bereits überprüft. Offenbar ist er zufällig auf ein Vorkriegslager mit Nuka-Cola gestoßen. Irgendein verlassener Lastwagen oder ein großes Lagerhaus, ich weiß es nicht.}
{272}{}{Ich habe bereits mit dem Sheriff darüber gesprochen. Er sieht nichts Kriminelles an den Aktivitäten des Verkäufers. Rechtlich ist sein Geschäft also sauber.}
{273}{}{Danke für deine Antworten.}
{274}{}{Ich habe noch ein paar Fragen zum Auftrag.}
{275}{}{Wegen dieses „zwielichtigen“ Verkäufers.}
{276}{}{Ja?}
{277}{}{Der Verkäufer wird dieser Stadt nie wieder Ärger machen. Ihm ist ein gewisser ... „Unfall“ zugestoßen.}
{278}{}{Der Verkäufer hat keine Waren mehr und somit nichts mehr zu verkaufen.}
{279}{}{Der Verkäufer hat seine Ware abgegeben und wurde auf meine Empfehlung hin von deinem Manager eingestellt.}
{280}{}{Sehr gut. Schön zu sehen, dass etwas auf ordentliche Weise erledigt wird.}
{281}{}{Danke.}

{282}{}{Darf ich dich etwas fragen? Warum schmeckt dein Nuka-Cola anders als das, was dieser Verkäufer verkauft?}
{283}{}{[Er runzelt missbilligend die Stirn.] Erstens wurde das Vorkriegsgetränk über 70 Jahre lang in versiegelten Flaschen gelagert. In dieser Zeit hat es, ähnlich wie Wein, seine Eigenschaften verändert und neue entwickelt. Das Nuka-Cola, das man in Vorkriegsbeständen findet, unterscheidet sich bereits deutlich von dem, was es früher einmal war. Und zweitens ... ich spreche nicht gern darüber, aber wir wissen nicht, wie das Getränk früher hergestellt wurde. Dank der Informationen auf den Etiketten und unserer eigenen Laborforschung konnten wir einen mehr oder weniger ähnlichen Geschmack erzielen. Natürlich ist es keine exakte Nachbildung. Deshalb unterscheidet sich unser Nuka-Cola ein wenig vom Vorkriegsprodukt, aber den Leuten schmeckt es trotzdem.}
{284}{}{Danke für deine Antwort. Jetzt ist mir vieles klarer.}

#Female character
{1120}{}{Ich habe gehört, dass Ihre Nuka-Cola-Verkaufsautomaten ausgeraubt werden. Haben Sie den Dieb schon erwischt?}
{1122}{}{Ich gestehe, ich bin es, der Sie ausgeraubt hat. Jetzt fühle ich mich deswegen schlecht.}
{1150}{}{Einverstanden. Hier ist das Teil.}
{1160}{}{Neulich bin ich in den artesischen Turm geraten ... Warum bringst du ihn nicht zum Laufen?}
{1251}{}{Im Moment habe ich genug Arbeiter ... Andererseits: Bist du von hier?}
