{100}{}{Siehst du Simon?}
{101}{}{Ein scharfer Blick, ein entschlossenes Kinn und eine stolze Haltung verleihen diesem Mann das Auftreten eines inoffiziellen Anführers.}
{102}{}{Verdammter Spind! Geh zu, verdammt!}
{103}{}{Was glotzt du so? Willst du eins in die Fresse kriegen?}
{104}{}{ }
{105}{}{Ich bin gerade nicht in der Stimmung ...}
{106}{}{Wie geht's? Gehen dir diese Nigger auf die Nerven? Gut.}

{110}{}{Fremder? Was ist los? Ich versuche, mich von all den Idioten in der Fabrik zu erholen. Ich will wirklich nicht reden.}
{111}{}{Weißt du etwas über die verschwundenen Schlüssel der Betriebsleiterin?}
{112}{}{Weißt du, dass dieser Schwarze im Speisesaal dich umbringen will?}
{113}{}{Dann will ich dich nicht weiter stören.}

{114}{}{Verdammter Geck! Ja, ich hab schon alle Schubladen und Taschen durchsucht! Ich habe VERDAMMT NOCH MAL keine Schlüssel und hatte auch nie welche!}
{115}{}{Was? Schon wieder? Kann ich mal eine Pause von all diesen dämlichen Fragen haben?}
{116}{}{[Simon hört sich die Geschichte mit offenem Mund an] Dieser Mistkerl! Der Nigger ist ganz schön gerissen! Weißt du, was ich jetzt mache? Oh nein, ich schlag ihm nicht ins Gesicht! Er wollte mich austricksen, also trickse ich jetzt ihn aus.}
{117}{}{Was hast du vor?}
{118}{}{Na ja, sagen wir, ich brauche jemanden, der dem Nigger die Schlüssel in die Tasche steckt und es dann der alten Frau erzählt. Ich bezahle dich! Natürlich könnte ich es selbst machen, aber bei mir wäre das nicht sicher – das könnte Verdacht erregen. Und du bist neu, niemand wird etwas vermuten. Was sagst du?}
{119}{}{Wenn du zahlst, bin ich dabei.}
{120}{}{Nein, das gefällt mir nicht.}
{121}{}{Großartig. Ich warte auf Neuigkeiten, Partner!}
{122}{}{Alles klar.}
{123}{}{Na klar, du kannst einfach gehen. Alles gut. Aber denk darüber nach – ich würde ordentlich zahlen und könnte dir vielleicht sogar etwas aus der Fabrik zuschieben. Was können diese alte Frau und der fette Nigger schon bieten? Ich hab's nicht eilig. Denk darüber nach. Mach es, wenn du bereit bist.}
{124}{}{Ich muss darüber nachdenken ...}

{125}{}{Dein schwarzer Rivale ist tot.}
{126}{}{Ich habe den Neger verpfiffen, wie vereinbart. Jetzt ist er gefeuert.}
{127}{}{Es ist verdammt gut, wenn die Leute ihre Arbeit hervorragend machen! Oh ja ... Ich halte immer mein Wort. Hier, 250 Kröten. Natürlich ist das nicht gerade das große Geld, also kann ich dir zusätzlich nur einen Gasschutzanzug anbieten. Den kannst du auf dem Markt für gutes Geld verkaufen. Glaub mir, der Nigger hätte dir nicht mehr gegeben.}
{128}{}{Genau! Na dann, trennen wir uns, als wären wir uns nie begegnet. Pass auf dich auf.}
{129}{}{Komm mir nicht zu nahe, bevor du das Problem gelöst hast.}

#Æåíñêèå ğåïëèêè
{1110}{}{Fremder? Was ist los? Ich versuche, mich von all den Idioten in der Fabrik zu erholen. Ich will wirklich nicht reden.}
{1121}{}{Großartig. Ich warte auf Neuigkeiten, Partner!}
{1126}{}{Ich habe den Neger verpfiffen, wie vereinbart. Jetzt ist er gefeuert.}
