{100}{}{Du siehst Harry, den Verkäufer.}
{101}{}{Du siehst einen pingeligen Verkäufer, der ständig lächelt.}

#Âîïğîñû
{110}{}{Ja, ja? Wie kann ich helfen?}
{111}{}{Bis dann.}
{112}{}{Kann ich hier Arbeit finden?}
{113}{}{Das weiß ich nicht. Sprich mit unserem Direktor, er prüft normalerweise jeden Arbeiter selbst. Mr. Skinner ist in seinem Büro, direkt hinter mir.}
{114}{}{Danke, ich gehe zu ihm.}
{115}{}{Ich habe ein Teil, mit dem sich der artesische Turm in Betrieb nehmen lässt. Mit wem sollte ich wegen des Preises sprechen?}
{116}{}{Oh, ja! Natürlich, die Fabrik muss diesen Turm unbedingt reparieren lassen! Sprich sofort mit unserem Direktor. Er ist in seinem Büro, direkt hinter mir.}
{117}{}{Oh, du bist es! Wir haben von deinen Erfolgen als Kurier gehört. Wir freuen uns sehr, dass du mit uns arbeitest.}

#Ïëàâàşùèå íîòàöèè:
{150}{}{Meine Damen und Herren! So sollten wir arbeiten!}
{151}{}{Nicht faulenzen.}
{152}{}{Der Angestellte ist das Fundament jedes Unternehmens.}
{153}{}{Ein Angestellter ist wie ein Gott ... Ja, genau.}
{154}{}{Ich kann die Fabrik retten oder ruinieren. Ist dir klar, wie wichtig ich bin?}
{155}{}{Am wichtigsten ist es, das Vertrauen des Kunden zu gewinnen.}
{156}{}{Was ist für einen Kunden am wichtigsten? Richtig, ihm in den Arsch zu kriechen.}
{157}{}{Wir werden viele Kunden haben, wenn du dich anstrengst.}
{158}{}{Denk nicht mal ans Faulenzen!}
{159}{}{Und? Wo sind unsere Kunden?!}
{160}{}{Hier gibt es keine Kunden, weil du faul bist!}
{161}{}{Wenn du nicht faul wärst und so arbeiten würdest wie ich ...}
{162}{}{Es gibt keine Karriereentwicklung! Man wird entweder befördert oder nicht.}
{163}{}{Verwechsle Marketing nicht mit Management! Das ist nicht dasselbe.}
{164}{}{Wir brauchen einen anständigen Designer ...}
{165}{}{Ich kannte mal einen Designer ...}
{166}{}{Unser Unternehmen ist entweder gut oder ... Hoppla, kein Oder.}
{167}{}{Na? Bist du jetzt fertig mit Faulenzen?}
{168}{}{Wach auf! Kunden!}
{169}{}{Oh! Sieh mal – ein Kunde!}
{170}{}{Pass auf, wie ich ihm etwas verkaufe!}
{171}{}{Fünf Prozent! FÜNF PROZENT!!!}
{172}{}{Ein männlicher Angestellter sollte mäßig unverheiratet sein.}
{173}{}{Hände aus dem Arsch – das passt zu dir!}
{174}{}{Wann gibt's Mittagessen?}
{175}{}{Ich verhungere hier ... Oooh ...}
{176}{}{Geht jemand zum Markt? Ich hätte gern Trockenfleisch ...}
{177}{}{Das Wichtigste in der Verwaltung ist, mit Menschen zu arbeiten.}
{178}{}{Sachbearbeiter ist der coolste Job! Glaubst du nicht? Tja, Pech gehabt!}
{179}{}{Hast du alles aufgeschrieben? Ich werde es überprüfen!}

#Òîğãîâåö äîâîåííîé êîëîé íà ñòîÿíêå
{180}{}{Warum willst du diesen Karawanenhändler mit der Vorkriegs-Cola nicht einstellen?}
{181}{}{Ach, ich erinnere mich an ihn, ja, ja. Unser Rivale mit dem ziemlich zwielichtigen Geschäft, stimmt's? Wir brauchen keine Leute von solcher ... äh ... Herkunft. Weißt du, Bauern mit gebräunter Haut und schwieligen Händen gewinnen nicht gerade die Zuneigung der Leute.}
{182}{}{Ich glaube, du liegst falsch. So einen guten Arbeiter sollte man nicht abweisen.}
{183}{}{Könnte ich dich umstimmen? Wohl kaum ... Na gut, bis dann.}
{184}{}{Ach wirklich? Und was sollte mich umstimmen?}
{185}{}{Meine Empfehlung als erfahrener Kurier.}
{186}{}{Meine Empfehlung als erfahrener Händler.}
{187}{}{Das ändert die Sache. Was ist denn so gut an ihm?}
{188}{}{Du achtest auf sein Aussehen statt auf seine tatsächlichen Fähigkeiten und Erfahrungen. Das ist in einer städtischen Umgebung wichtig, bei den Dorfbewohnern ist es aber anders. Sie werden den Händler als einen der Ihren akzeptieren, was ihm Verhandlungen erleichtern wird.}
{189}{}{Hmm. So habe ich das noch nie betrachtet. Jetzt verstehe ich, warum unsere Kuriere bei Aufträgen in Siedlungen scheitern. Vielleicht müssen wir unsere Vorgehensweise überdenken. Bitte sag diesem Händler, dass wir gern einen Vertrag mit ihm abschließen würden – vorausgesetzt, er gibt uns den Rest der Nuka-Cola.}
{190}{}{Du hast die richtige Entscheidung getroffen, Harry.}

#Ïğî ëèöåíçèş
{200}{}{Wie wär's mit einem gemeinsamen Geschäft?}
{201}{}{Du willst Cola in anderen Städten verkaufen, stimmt's?}
{202}{}{Vielleicht!}
{203}{}{Wenn dem so ist, stehe ich Ihnen zu Diensten! Willkommen im Büro der *in Betrieb befindlichen* Nuka-Cola-Fabrik! Der einzigen in dieser Region und vielleicht sogar weltweit. Sie können jederzeit mit uns vereinbaren, dass wir das Getränk an jeden Ort und jede Institution liefern. Aber ich sollte Sie gleich warnen: Wir verkaufen nur das Produkt, um die Lieferungen müssen Sie sich selbst kümmern.}
{204}{}{Mit anderen Worten, ihr gebt einfach die Lizenz für den Handel mit dem Erfrischungsgetränk aus?}
{205}{}{Wir stellen das Getränk her und verkaufen es in großen Mengen im Großhandel. Natürlich können Sie auch jedes Mal einfach eine große Menge Cola kaufen und Ihre Gefährten damit versorgen. Aber wer eine Lizenz kauft, bekommt einen Rabatt und die Möglichkeit, Ware zurücklegen zu lassen.}
{206}{}{Zurücklegen?}
{207}{}{Ja. Sobald wir das Volumen Ihrer Bestellung kennen, lagern wir sie einfach ein und warten auf Ihren Karawanenzug. Andernfalls verteilen wir die Bestellung auf alle Kunden, die gerade kommen. Dann muss Ihr Karawanenzug mindestens mehrere Tage warten, bis wir die benötigte Menge wieder hergestellt haben.}
{208}{}{Wenn ich also eine Lizenz kaufe, ist garantiert, dass meine Ware für mich bereitsteht, richtig?}
{209}{}{Richtig! Aber es gibt noch etwas zu beachten. In den Ödlanden kursieren Gerüchte über minderwertige Ware. Das schadet dem Ruf der Fabrik. Wenn Sie nachweisen können, dass Sie direkt mit uns zusammenarbeiten, sind Ihre Kunden eher bereit, mit Ihnen Geschäfte zu machen, und Ihr Ansehen wird deutlich steigen.}
{210}{}{Heißt das, ich kann auch ohne Lizenz Geschäfte machen?}
{211}{}{Vielleicht! Wenn Sie vertrauenswürdig genug wirken. Aber glauben Sie mir, die meisten Händler haben ihre Lektion bereits gelernt und versuchen, nur mit Leuten zu handeln, die eine Lizenz haben.}
{212}{}{Wie viel kostet diese Lizenz?}
{213}{}{Wir verkaufen sie Ihnen für }
{214}{}{ Bucks. Ein sehr guter Preis, wenn man Ihren Verkaufsgewinn bedenkt.}
{215}{}{Klingt verlockend. Und was mache ich danach?}
{216}{}{Das müssen Sie selbst entscheiden. Sie können eine große Lieferung Cola kaufen. Einen Kunden zu finden und die Ware auszuliefern, ist Ihre Aufgabe. Wir empfehlen Ihnen, mit Karawanenhändlern zu sprechen. Natürlich nehmen sie für ihre Dienste einen Anteil, aber sie können sehr schnell eine große Menge Flaschen transportieren.}
{217}{}{Wie viele Kuriere gibt es derzeit? Werde ich mit so einem Geschäft Geld verdienen können?}
{218}{}{Ich denke schon! Siehst du, eine Zeit lang arbeitete die Fabrik hauptsächlich für den Markt der Innenstadt. In den Ödlanden kennt man unsere Produkte kaum. Dort verbraucht man noch immer die Vorräte aus der Vorkriegszeit.}

{219}{}{Ich möchte eine Lizenz kaufen! Wie viel kostet sie?}
{220}{}{Danke für die Erklärung, ich werde darüber nachdenken. Mach's gut.}
{221}{}{Dollar. Das ist der Preis des Direktors, er hat angeordnet, nicht darüber zu feilschen.}
{222}{}{Ich kaufe sie!}
{223}{}{Oh, das kann ich mir nicht leisten. Bis dann.}
{224}{}{Lass dein Geld nicht fallen! Das ist das Grauenhafteste, was ich je gesehen habe!}
{225}{}{Hoppla, Entschuldigung.}
{226}{}{[Du unterschreibst einen Stapel Papiere und schüttelst die Hand] Viel Glück im Geschäft, Kurier! Wir wünschen dir und deinem bescheidenen Vorhaben Wohlstand und viel Erfolg!}
{227}{}{Dir auch!}
{228}{}{Du bist offizieller Vertreter der Nuka-Cola-Fabrik geworden. Glückwunsch zu deiner angesehenen Position!}
