{100}{}{Du siehst einen Lagerverwalter.}
{101}{}{Du siehst den Leiter des Fabriklagers.}

{110}{}{H-hey! Du darfst da nicht rein! Das ist ein Betriebsraum. Raus hier! Los, los!!!}
{111}{}{Na gut, ich gehe.}
{112}{}{Diesmal gehe ich, aber sei gewarnt: Beim nächsten Mal schlage ich dir vielleicht die Zähne aus.}

{113}{}{Beruhig dich, ich bin wegen des Kaufs einer Produktcharge hier.}
{114}{}{Wir sind kein Laden!... Moment, darum geht's also. Entschuldigung, aber ich habe dich noch nie gesehen. Kannst du mir deine Lizenz zeigen? In letzter Zeit geben sich viele Leute als Kuriere aus.}
{115}{}{Hier, sieh nach.}
{116}{}{Äh, ich habe sie gerade nicht dabei.}

{117}{}{Also erlöse meine Ohren von deinem Geschwafel! Besorg dir eine Lizenz oder verschwinde! Verdammte Bettler, ich hab euch so satt ...}
{118}{}{[Gehen]}
{119}{}{Schon besser! Entschuldige meine Unhöflichkeit, ständig belästigen mich irgendwelche Bettler. Seit Langem sage ich diesen Idioten in der Fabrik, sie sollen einfach ein Buchhaltungssystem einführen. Aber sie haben immer zu tun ... Also, wie viele Flaschen brauchst du heute?}
{120}{}{Wie viele Flaschen kann ich bestellen?}
{121}{}{Ach ja, du bist neu hier. Also gut, hör zu, ich erkläre es dir einmal. Zuerst rolle ich diese Kisten zum Eingang und schließe sie für dich ab. Danach läuft alles nach dem üblichen Bestellverfahren, wir müssen uns nicht einmal sehen oder hören. Du zahlst den Großhandelspreis, ich fuelle den Bestand auf. Wie und wo du sie vertreibst, ist deine Sache. Klar?}
{122}{}{Völlig klar.}
{123}{}{Und da du sowieso fragen wirst: Wir können speziell für dich höchstens }
{124}{}{ Einheiten pro Monat herstellen. Die Fabrik schafft noch nicht mehr.}
{125}{}{Gut. Keine weiteren Fragen.}
{126}{}{Na schön. Und jetzt hole ich diese verdammten Kisten raus. Aus dem Weg!}
{127}{}{[Gehen]}

{130}{}{A-ah, ist das nicht unser Kurier ... Wie reizend. Aber ich bin gerade beschäftigt, stör mich nicht.}
{131}{}{In Ordnung.}
