{100}{}{Du siehst eine Kellnerin.}
{101}{}{Du siehst eine sehr beschäftigte Frau mit einem ziemlich unfreundlichen Gesichtsausdruck. Was für eine Hexe.}

#Ïåğâàÿ ôğàçêà:
{102}{}{Was?}
{103}{}{Was willst du?}
{104}{}{Sag's einfach.}
{105}{}{Noch ein neues Gesicht! Was willst du?}
{106}{}{Was darf's sein?}
{107}{}{Was? Wie wär's mit einem Bier? Davon bekommst du weniger Durchfall.}
{108}{}{Oh! Ein neuer Kunde! Was willst du?}
{109}{}{Wenn du das Geschirr zerbrichst, stelle ich es dir in Rechnung. Also, was willst du?}

#Ğåïëèêè äëÿ áëóæäàíèé ìåæäó ñ'îëèêàìè:
{110}{}{Wenn du kotzen musst, dann draußen.}
{111}{}{Hey! Nicht prügeln!}
{112}{}{Iss, Schätzchen.}
{113}{}{Das macht 50 Kröten.}
{114}{}{Komm schon, Schlafmütze.}
{115}{}{Wie lange muss ich noch warten?}
{116}{}{Du willst noch eins? Ist das dein Ernst?}
{117}{}{Iguana? Vielleicht hättest du auch gern einen gegrillten Schwanz auf dem Silbertablett?}
{118}{}{Was das ist, fragst du? Das ist ein Kuchen ... mit Fleisch.}
{119}{}{Na, wen haben wir denn da, der so hungrig ist?}
{120}{}{Du hast Hunger, was! Na? Na??}
{121}{}{Ein Handtuch? Ach komm! Seht euch den hier an, Leute.}
{122}{}{Den Tisch abwischen? Hättest du das nicht selbst machen können?}
{123}{}{Was für ein Schwein.}
{124}{}{Wenn du etwas kaputt machst, werde ich sauer.}
{125}{}{Na klar, Mami räumt hinter allen her ...}
{126}{}{::brummelt::}
{127}{}{Hier, kipp's runter.}
{128}{}{Fünf Mäuse. Los, los!}
{129}{}{Beweg dich, du bist nicht allein hier.}

#Äèàëîã
{150}{}{Lass mich die Speisekarte sehen.}
{151}{}{Ich gehe.}
{152}{}{Warum so unhöflich?}
{153}{}{Was noch?}
{154}{}{[Menü]}
{155}{}{Schon gut.}
{156}{}{[Macht ein erstauntes Gesicht] Du hast vielleicht Nerven! Die alte Frau gibt sich solche Mühe und wischt hier allen den Dreck weg, und trotzdem ist er nicht zufrieden! Wo kommst du denn her, feiner Pinkel? Ich wette, du kommst aus Vegas, stimmt's? Du bist hergekommen, um zu essen, also iss! Ich bin nicht deine Mutter und muss dich nicht zurechtmachen. Was willst du bestellen?}

#Èçâèíåíèÿ
{157}{}{Verdammt, ich hau ab aus deinem scheiß Laden! Erst beleidigt mich eine alte Schachtel und dann ein glatzköpfiger Idiot!}
{158}{}{Es tut mir leid, dass ich unhöflich war. Das wird nicht wieder vorkommen. Entschuldigung.}
{159}{}{Na, mein Freund, hast du dich beruhigt?}
{160}{}{Warum verschwindest du nicht von hier, Kumpel?}
{161}{}{[Strahlt übers ganze Gesicht und winkt ab] Ach, komm schon! Hier sind schon schlimmere Dinge passiert! Du würdest nicht glauben, was die alte Frau in ihrem Leben alles gesehen hat! Keine Sorge! Schon gut!}
{162}{}{Puh, das ist eine Erleichterung ...}
{163}{}{Oh, du jämmerlicher Idiot! [Fast weinend droht sie mit den Fäusten] Wenn ich jünger wäre, würde ich's dir zeigen! Hey, Jungs, werft ihn raus!}
{164}{}{Oh, du alte Schachtel!!!}

#Åñëè Äæî ìåğ'â
{200}{}{Der Laden ist geschlossen, siehst du das nicht? Wir haben ... eine Tragödie hier.}

#Female character:
{1156}{}{[Macht ein erstauntes Gesicht] Du hast vielleicht Nerven! Die alte Frau gibt sich solche Mühe und wischt hier allen den Dreck weg, und trotzdem ist er nicht zufrieden! Wo kommst du denn her, feiner Pinkel? Ich wette, du kommst aus Vegas, stimmt's? Du bist hergekommen, um zu essen, also iss! Ich bin nicht deine Mutter und muss dich nicht zurechtmachen. Was willst du bestellen?}
{1158}{}{Es tut mir leid, dass ich unhöflich war. Das wird nicht wieder vorkommen. Entschuldigung.}
{1159}{}{Na, mein Freund, hast du dich beruhigt?}
{1160}{}{Warum verschwindest du nicht von hier, du Rotzbengel?}
{1163}{}{Oh, du jämmerlicher Idiot! [Fast weinend droht sie mit den Fäusten] Wenn ich jünger wäre, würde ich's dir zeigen! Hey, Jungs, werft sie raus!}
