{100}{}{Du siehst einen Polizisten.}
{101}{}{Du siehst einen Polizisten in Kampfrüstung. Er beobachtet die Straßen.}
{102}{}{Weitergehen.}
{103}{}{He, du! Waffe weg!}
{104}{}{Ich beobachte dich. Denk nicht einmal daran, irgendeinen Mist zu bauen.}

{110}{}{Was ist passiert?}
{111}{}{Ich habe gerade gesehen, wie ein Dieb sich ins Einkaufszentrum geschlichen hat!}
{112}{}{Ist nichts, mir ist nur langweilig.}
{113}{}{Du hast deinen Komplizen verraten!}

{114}{}{Halt, keinen Schritt weiter! Ich hab dich im Visier!}
{115}{}{NEIN!!! CHEF!!!}
{116}{}{Zu spät, mein Freund. Tritt ins Licht.}
{117}{}{Polizist: „Wir haben den Arsch geschnappt. Gut, dass du ihn gemeldet hast. Wenn du Zeit hast, sprich mit Sheriff Burton. Er gibt dir eine Belohnung für deine Mühe.“}

#Æåíñêèå ğåïëèêè
{1117}{}{Polizist: „Wir haben den Arsch geschnappt. Gut, dass du ihn gemeldet hast. Wenn du Zeit hast, sprich mit Sheriff Burton. Er gibt dir eine Belohnung für deine Mühe.“}
