{100}{}{Du siehst einen kranken Stadtbewohner.}
{101}{}{Du siehst einen kranken Bürger. Schweiß rinnt ihm von der Stirn. Er hat wohl Fieber.}
{102}{}{Du siehst einen Bürger. Sein Gesicht wirkt frischer. Es scheint ihm ziemlich gut zu gehen.}

{103}{}{Hallo. Was machst du in meinem Haus?}
{104}{}{Geh weg! Mir geht's so schlecht! O-oh ...}
{105}{}{Da ist mein Retter! Hut ab!}
{106}{}{Hey, schon gut. Ich bin mit diesen Spritzen fertig.}
{107}{}{Mir geht's gut, wirklich ... Danke, dass du dir Sorgen machst.}
{108}{}{Oh, danke! Mir geht es schon besser!}
{109}{}{Du hast dem Patienten ein Gegengift gegeben. Bald wird er sich erholen.}
{110}{}{Was zum Teufel machst du da!?}
{111}{}{Das wird ihm nicht helfen.}
{112}{}{Bist du verrückt? Bleib mir mit dem Zeug vom Leib!}
{113}{}{Das wird ihm nicht helfen. Du brauchst das Gegengift.}
{114}{}{Dieser Mann braucht keine Behandlung.}
{115}{}{Medikamente werden benötigt.}
{116}{}{Der Patient hat Ruhr. Er braucht Medikamente; mit Fähigkeiten allein kommst du nicht weiter.}
{117}{}{Bist du sicher, dass du weißt, was zu tun ist?}
{118}{}{Die Behandlung schlägt fehl.}
{119}{}{Du hast den Patienten erfolgreich behandelt. Jetzt geht es ihm bestimmt besser.}
{120}{}{Du siehst einen Bürger.}

#Æåíñêèå ğåïëèêè:
{1105}{}{Da ist mein Retter! Hut ab!}
