{100}{}{Du siehst einen Passanten.}
{101}{}{Du siehst einen gewöhnlichen Bürger der Stadt Salt Lake.}
{102}{}{Entschuldigung, ich habe es eilig.}
{103}{}{Oh, Mister Hickok! Schön, dich zu sehen!}

#Íàåì ìàøèíèñòà:
{300}{}{Hallo. Wie geht's?}
{301}{}{Ich suche einen Zugführer. Eine lange Reise liegt vor mir ...}
{302}{}{Na gut.}
{303}{}{Du bist verrückt! Niemand in dieser Stadt geht auch nur in die Nähe des Bahnhofs. Der Sheriff lässt dich nicht! Und wenn dich jemand begleiten würde, dann bestimmt kein Einheimischer. Schluss damit. Ich will keinen Ärger.}
{304}{}{Schade.}
