{100}{}{Du siehst einen Bürger.}
{101}{}{Du siehst einen Bürger.}
{102}{}{Du siehst einen gewöhnlichen Bürger von Salt Lake City.}
{103}{}{Stör mich nicht.}
{104}{}{Stör Robert bitte nicht. Er hat noch kein Obst fürs Abendessen geschnitten, weil er sich mit seinem dämlichen Rätsel beschäftigt.}

#Ñîñòîÿíèå ñàíèòàğèè: îòëè÷íîå
{120}{}{Es ist eine Weile her, dass sich jemand vor dem Haus übergeben hat.}
{121}{}{Ich bin heute so aufgedreht!}
{122}{}{Ich hatte seit Ewigkeiten nicht mehr so viel Energie.}
{123}{}{Es ist, als wäre ich zehn Jahre jünger!}
{124}{}{Ich bin bereit, meine Kraft zu zeigen!}
{125}{}{Ich habe heute einen riesigen Appetit.}
{126}{}{Eigentlich habe ich verdammt großen Hunger.}
{127}{}{Ich könnte einen gebratenen Gecko verputzen ... Oder zumindest die Hälfte davon.}
{128}{}{Ich sollte morgens mit dem Joggen anfangen. Vor streunenden Hunden davonlaufen oder so.}
{129}{}{Ich will überhaupt nicht schlafen.}

#Ñîñòîÿíèå ñàíèòàğèè: ïëîõîå ëèáî íåéòğàëüíîå
{130}{}{Schon wieder hat sich jemand vor dem Haus übergeben ...}
{131}{}{Ich sollte mich besser bis zur nächsten Anbausaison mit Vocas eindecken.}
{132}{}{Die Apotheke ist leer.}
{133}{}{Gegen diese verdammte Ruhr muss etwas unternommen werden.}
{134}{}{Mir steht ein ganzer Abend auf dem Donnerbalken bevor.}
{135}{}{Ich muss eine Toilette finden ... Oh, Scheiße ... Jetzt muss ich nicht mehr.}
{136}{}{Mir geht's nicht so gut ... Ich brauche ... etwas Ruhe ...}
{137}{}{Man sagt, Biertrinken hilft gegen Durchfall.}
{138}{}{Gestern kam so ein riesiger Haufen aus mir raus! Das glaubst du nicht!}
{139}{}{Es ist besser, Nuka-Cola zu trinken als Wasser.}

#Ñîñòîÿíèå çàâîäà: äèâåğñèÿ èëè ïëîõîå ñîñòîÿíèå
{140}{}{Ich habe gehört, dass die Fabrik sabotiert wurde.}
{141}{}{Die Sabotage wurde eindeutig von diesen Bastarden aus Provo verübt.}
{142}{}{Verdammt. Wenn die Fabrik dichtmacht, ist das für niemanden gut.}
{143}{}{Ich hoffe, die Fabrik hält durch ...}
{144}{}{Macht euch auf was gefasst, Salt Lake, die Fabrik wird bald Geschichte sein.}
{145}{}{In der Fabrik läuft echt eine Menge Scheiße, Mann.}
{146}{}{Mein Geschwisterchen wird seinen Job in der Fabrik kündigen.}
{147}{}{Die Fabrik ist verflucht.}
{148}{}{Weißt du noch, wie großartig die Fabrik einmal war?}
{149}{}{Wann wird der Fabrikleiter sich darum kümmern?}

#Ñîñòîÿíèå çàâîäà: îòëè÷íîå ñîñòîÿíèå
{150}{}{Noch nie sind so viele Karawanen wegen Nuka-Cola gekommen.}
{151}{}{Nuka-Cola ist sehr gefragt.}
{152}{}{Wow, was für ein Aufhebens um die Fabrik!}
{153}{}{So viele Leute bei der Fabrik, als gäbe es dort irgendeine Vorstellung.}
{154}{}{Ich hätte nie gedacht, dass ich so etwas mal erleben würde.}
{155}{}{Hoch lebe der Fabrikdirektor von Nuka-Cola! Der König aller Direktoren!}
{156}{}{Sieht aus, als hätten sie in der Fabrik ein paar gute Angestellte eingestellt.}
{157}{}{Die Fabrik ist plötzlich wieder auf Vordermann.}
{158}{}{Was? Noch eine Nuka-Cola-Karawane? Wie viele kann es denn geben ...}
{159}{}{Sie gehen nur wegen Salt Lake zu Nuka-Cola...}

#Åñëè Ïğîâî óíè÷òîæåí / Ãèëìîğ ïîâåøàí
{160}{}{Meiner Meinung nach hatten diese Hinterwäldler aus Provo es verdient.}
{161}{}{Es war nicht einfach - Gilmore war ein ganz schönes Kaliber.}
{162}{}{Provo wird sich nicht in die Nähe dieses Ortes wagen.}
{163}{}{So geht man mit Provo um. Hätten wir gleich von Anfang an so machen sollen!}
{164}{}{Der Sheriff hat endlich jemanden gefunden, der sich um Provo kümmert.}
{165}{}{Ich frage mich, wen sie angeheuert haben, um sich um Provo zu kümmern. Burton hat sich sicher nicht selbst die Hände schmutzig gemacht.}
{166}{}{Nee, der Sheriff würde sich nicht die Hände schmutzig machen, nicht einmal für diese Arschlöcher.}
{167}{}{Gilmore, du Hurensohn, fahr zur Hölle!}
{168}{}{So ist es schon besser! Eine angemessene Antwort!}
{169}{}{Diese Provo-Idioten haben es schon lange verdient!}

#Ñîñòîÿíèå çàâîäà: ñğåäíåå ñîñòîÿíèå
{170}{}{In der Fabrik geht etwas Seltsames vor.}
{171}{}{Die Fabrik könnte einen fähigen Manager gebrauchen.}
{172}{}{Wann würde die Fabrik endlich mit voller Kapazität arbeiten?}

#Âîğşãà ïîéìàí
{180}{}{Dieser Dieb wurde endlich geschnappt! Geschieht ihm recht.}
{181}{}{Es lebe der Sheriff von Salt Lake, Burton die Peitsche! Ein Schrecken für alle Diebe!}
{182}{}{Das Schicksal dieses Diebes wird allen anderen Dieben als Warnung dienen.}
{183}{}{Der Dieb hat es verdient!}
{184}{}{Genau! Er verdient eine Weile im Knast!}
{185}{}{Jetzt wird die Kriminalität hier ganz versiegen.}
{186}{}{Ich hoffe, dass es in der Stadt jetzt weniger Überfälle gibt.}
{187}{}{Seit der Dieb geschnappt wurde, fühle ich mich irgendwie besser.}
{188}{}{Diebstahl wird nicht geduldet!}
{189}{}{Fürchtet euch, Diebe von Salt Lake!}

#Àâòîìàòû êîëû âçëîìàíû
{200}{}{Wann schnappen sie diesen Dieb endlich?}
{201}{}{Haben sie denjenigen erwischt, der die Verkaufsautomaten ausgeraubt hat?}
{202}{}{Die Verkaufsautomaten von Nuka-Cola könnten wegen der Diebstähle abgeschafft werden.}
{203}{}{Jemand raubt ständig die Verkaufsautomaten aus.}
{204}{}{Irgendein gerissener Gauner hat die Hälfte der Verkaufsautomaten in Nuka-Cola ausgeraubt.}
{205}{}{Ist dir aufgefallen, dass die Verkaufsautomaten in Nuka-Cola leergeräumt wurden?}

#Ñîñòîÿíèå ãîğîäà: îòëè÷íîå ñîñòîÿíèå
{210}{}{Ich ziehe aus dieser Stadt nirgendwohin!}
{211}{}{Die Stadt ist jetzt noch viel toller als vorher.}
{212}{}{Ich glaub meinen eigenen Augen nicht! Ist das wirklich die Stadt Salt Lake?}
{213}{}{Ich hätte nie gedacht, dass Salt Lake sich so verändern würde.}
{214}{}{Weißt du noch, wie wir angefangen haben? Diese schlechten Zeiten liegen jetzt hinter uns ...}
{215}{}{Ist das Salt Lake? Noch gestern war das ein völlig anderer Ort.}
{216}{}{Die Stadt wächst, das ist Fakt.}
{217}{}{Vielleicht sollte ich in die Innenstadt ziehen.}
{218}{}{Die Stadt ist interessanter geworden. Viel besser als vorher.}
{219}{}{Es lebe der great Salt-See!}

#Ñîñòîÿíèå ãîğîäà: ïëîõîå ñîñòîÿíèå
{220}{}{Ich bin traurig.}
{221}{}{Ich wünschte, ich wäre in New Reno geboren.}
{222}{}{Ich glaub meinen eigenen Augen nicht! Verdammt noch mal, die Stadt Salt Lake ...}
{223}{}{Es scheint, als gäbe es heutzutage immer weniger Karawanen.}
{224}{}{Weißt du noch, wie wir angefangen haben? Und jetzt ist alles so weit gekommen ...}
{225}{}{Ist das Salt Lake? Es kommt mir vor, als hätte die Stadt erst gestern geblüht ...}
{226}{}{Die Stadt verfällt, noch mehr als zuvor.}
{227}{}{Verdammt noch mal!}
{228}{}{Ich sollte lieber nach Vegas ziehen.}
{229}{}{Nein, nein, ich muss einen Weg aus diesem Ort finden.}

#Ïğî ïîåçä-ïğèçğàê
{230}{}{Man sagt, der Geisterzug sei kürzlich durch die Stadt gefahren.}
{231}{}{Die Nachbarn sagen, sie hätten den Geisterzug wieder gehört.}
{232}{}{Ich frage mich, wie lange dieser Geisterzug noch hier herumrumpeln wird.}
{233}{}{Hat gestern Nacht jemand rumpelnde Räder gehört?}
{234}{}{Ich schwöre bei Gott, ich habe ihn aus 30 Fuß Entfernung vorbeifahren sehen!}
{235}{}{Er existiert, ich schwöre es!}
{236}{}{Jeder hat schon davon gehört!}
{237}{}{Der Geisterzug hat wieder Seelen im Ödland eingesammelt.}
{238}{}{So ist das eben - man lebt sein Leben und dann holt einen der Geisterzug ab.}
{239}{}{Der Geisterzug sammelt wieder Seelen ein.}
{240}{}{Ich würde dem Geisterzug lieber nicht über den Weg laufen.}
{241}{}{Ach, irgendwann steigen wir alle in den Geisterzug.}

#Íàåì ìàøèíèñòà:
{300}{}{Hey, wie läuft's?}
{301}{}{Ich suche einen Lokführer. Eine lange Reise liegt vor uns.}
{302}{}{Alles in Ordnung.}
{303}{}{Du musst verrückt sein! Niemand in der Stadt traut sich auch nur in die Nähe des Bahnhofs. Der Sheriff wird es niemals erlauben! Hier findest du niemanden, der mit dir mitkommt, also lass uns nicht weiter darüber reden. Ich habe genug andere Probleme.}
{304}{}{Schade.}
