{100}{}{Du siehst einen Bürger.}
{101}{}{Du siehst einen der vielen Einheimischen.}
{102}{}{Hallo.}
{103}{}{Danke, dass du mit dem Hund geholfen hast.}
{104}{}{ }

{110}{}{Johnny ist wegen irgendetwas aufgebracht. Schon wieder.}
{111}{}{Das liegt an dem Hund.}
{112}{}{Ach, er kann es immer noch nicht verwinden?}
{113}{}{Ja, er läuft durchs Haus und sucht danach. Aber sie kommt nicht zurück.}
{114}{}{Eine traurige Geschichte.}
{115}{}{Was glaubst du, was mit ihr passiert ist?}
{116}{}{Ich bin sicher, sie ist im Magen dieses einäugigen Freaks aus den Slums verdaut worden.}
{117}{}{Ugh, wie kannst du nur ... Er scheint harmlos zu sein.}
{118}{}{Ha! Du hättest ihn in Aktion sehen sollen!}
{119}{}{In welcher Aktion?}
{120}{}{Bei Überfällen hat dieser hinterhältige Kerl uns eine Suppe aus Hundefleisch gekocht.}
{121}{}{Ich glaube, du kannst ihn einfach nicht leiden.}
{122}{}{Stimmt, er ist mir zuwider.}
{123}{}{Vielleicht ist der Hund ja irgendwo am Stadtrand mit einem Rudel mitgezogen?}
{124}{}{Woher soll ich das wissen?!}
{125}{}{Schon gut, sei nicht so gereizt.}
{126}{}{Wechseln wir das Thema ...}
