{100}{}{Du siehst einen Apotheker.}
{101}{}{Es ist ein Apotheker, obwohl er vielleicht sogar Arzt ist ... Aber jetzt arbeitet er als Apotheker.}

{102}{}{Das muss eine interessante Aufgabe sein, wenn man Arzt oder Chemiker ist ... Aber danke, dass du es mir erzählt hast.}
{103}{}{Nun, die Sache scheint erledigt zu sein. Das heißt auch, dass ich in meiner Freizeit am Lagerfeuer etwas zu tun haben werde. Leb wohl, Kollege!}
{104}{}{Dieb! Hilfe!}
{105}{}{Ich frage mich, welcher?}

{110}{}{Ich höre.}
{111}{}{Zeig mir die Ware.}
{112}{}{Brauchst du einen Arbeiter für einen bescheidenen Lohn? Da ist ein armer Kerl, der keine Arbeit findet.}
{113}{}{Nein. Ich kann kaum selbst meinen Lebensunterhalt verdienen. Die Arbeiter zu bezahlen, ist mir zu viel ... Vielleicht braucht der Sheriff jemanden. Um ihn herum sind immer Leute mit irgendetwas beschäftigt.}
{114}{}{In Ordnung.}
{115}{}{Na ja, ich habe so gut geholfen, wie ich konnte. Mehr habe ich nicht anzubieten.}
{116}{}{Noch einmal.}
{117}{}{Siiicher. Leb wohl.}
{118}{}{Auf Wiedersehen.}
{119}{}{Gehen wir zurück.}

#About the filter for the tower:
{120}{}{Zur Gesundheitsversorgung in der Stadt ...}
{121}{}{Worüber möchtest du sprechen?}
{122}{}{Über den Filter für den artesischen Wasserturm. Ich habe ihn gefunden! Aber wie bringt man den Turm wieder zum Laufen? Gibt es jemanden, mit dem ich darüber sprechen kann?}
{123}{}{Na, natürlich mit mir! Schließlich kommen hier alle mit verdammter Ruhr zu mir. Ich hätte dafür gesorgt, dass der Turm wieder läuft.}
{124}{}{Und was machst du danach? Verkaufst du Wasser?}
{125}{}{Wenn es nach mir ginge, würde ich das Wasser kostenlos abgeben. Aber unter unseren Umständen muss ich anders vorgehen. Zuerst muss ich den Jungs, die alles reparieren und das Gelände für die Arbeiten vorbereiten, eine beträchtliche Summe zahlen. Dann muss ich Leute für den Schutz anheuern. Vielleicht kann ich den Sheriff fragen, mal sehen. Zumindest würde ich die Preise nicht in die Höhe treiben, anders als die Fabrik Nuka-Cola. Für die zählt nur das Geschäft.}
{126}{}{Die Fabrik ist also auch daran interessiert, den Filter zu kaufen?}
{127}{}{Na, natürlich! Aber merk dir meine Worte: Wenn die Fabrik alleiniger Besitzer des sauberen Wassers wird, ist das noch schlimmer, als gar kein sauberes Wasser zu haben!}
{128}{}{Warum?}
{129}{}{Über der Stadt schwebt eine Gesundheitskatastrophe. Das sehe ich doch. Niemand kann sicher sein, am nächsten Tag wieder aufzuwachen. Wenn die Stadt sauberes Wasser hat, werden die Leute sich gegenseitig an die Gurgel gehen. Es wird zu ernsten Konflikten kommen.}
{130}{}{Klingt kompliziert. Und wie viel kannst du mir für den Filter zahlen?}
{131}{}{5.000, außerdem bekommst du in meiner Apotheke 30% d Rabatt. Mehr kann ich nicht anbieten.}
{132}{}{Abgemacht!}
{133}{}{Nach dieser herzzerreißenden Geschichte überlasse ich dir den Filter kostenlos.}
{134}{}{Ich werde über dein Angebot nachdenken.}
{135}{}{Danke! Das ist die Rettung unserer Stadt!}
{136}{}{Verstehe. Auf Wiedersehen.}
{137}{}{Du hast den Filter für den artesischen Wasserturm abgeliefert und die Lebensbedingungen der Einheimischen deutlich verbessert.}

#About artesian water tower:
{138}{}{Ich war beim artesischen Wasserturm in den Slums. Hat schon jemand versucht, ihn zu reparieren? Das würde der Stadt Unmengen sauberes Wasser bringen!}
{139}{}{Das würde sie natürlich. Dieser Turm erregt schon lange die Aufmerksamkeit aller. Die Nuka-Cola-Fabrik hat ein paar Leute angeheuert, der Sheriff hat versucht, jemanden zu finden, der ihn repariert, und es wurden sogar Kuriere in andere Städte geschickt. Aber alles vergeblich.}
{140}{}{Was ist das Problem?}
{141}{}{Im Großen und Ganzen ist der Turm funktionsfähig. Nur ein Gerät funktioniert nicht: die Reinigungsmaschine. Um sie zu reparieren, brauchen wir einen neuen Filter. Aber niemand weiß, wo man einen herbekommt. So etwas kann man nicht im Gemischtwarenladen kaufen. Allerdings ging das Gerücht um, dass jemand in Vegas ein passendes Teil gefunden hat. Aber das ist nur eine Geschichte, sonst hätte man es schon längst hierhergebracht.}
{142}{}{Hmm, das klingt nach einem ernsten Problem. Hoffentlich stoße ich auf so einen Filter.}
{143}{}{Eher unwahrscheinlich, aber wenn du viel im Ödland unterwegs bist, frag in den Städten herum. Am besten fängst du in Vegas an.}
{144}{}{Dann also Vegas ... Das merke ich mir.}
{145}{}{Du hast die Koordinaten der Las Vegas erhalten.}

#About radiation in the city
{154}{}{Wie kannst du in einem so feuchten und stinkenden Klima leben? Haben Besucher vielleicht Atemprobleme?}
{155}{}{Stimmt. Man muss sich an die Bedingungen hier gewöhnen. Aber der Körper passt sich mit der Zeit an. Vor allem sollte man seine Nase nicht in Dinge stecken, die einen nichts angehen.}
{156}{}{Und worin sollte man seine Nase nicht stecken?}
{157}{}{Im Norden gibt es ein großes radioaktives Gebiet, einen regelrechten Friedhof. Das war der Teil des Ballungsraums Salt Lake, auf den während des Krieges Atombomben abgeworfen wurden. Von Zeit zu Zeit spülen Regenfälle den radioaktiven Dreck in den Great Salt-See. Zum Glück haben wir mit dem Klima Glück.}
{158}{}{Wieso?}
{159}{}{Unsere Landschaft hält die meisten Gefahren fern. Hier gibt es weder heftige Winde wie in den Wüsten noch Hitzedämpfe. Außerdem ist unter den hiesigen Bedingungen eine Pflanze mutiert: die Seerose. Sie wächst am Ufer des Great Salt-Sees. In anderen Städten ist sie einfach nur eine Pflanze, aber diese hier trägt eine besondere Art nahrhafter Nüsse.}
{160}{}{Ach, deshalb habe ich auf dem Weg hierher gesehen, wie die Leute ständig auf etwas herumkauten ...}
{161}{}{Das sind Vocas-Nüsse. Sie sind sehr hart, man muss ordentlich darauf herumkauen, sonst ist die Wirkung gering.}
{162}{}{Und was genau bewirken sie?}
{163}{}{Diese Nüsse entfernen radioaktive Elemente aus dem Körper. Natürlich geschieht das nicht sofort. Die Strahlung wird tagsüber mit Schweiß und Urin ausgeschieden. Die Wirkung ist nicht besonders stark, aber wenn du regelmäßig Vocas verwendest, normalisiert sich die Strahlenbelastung wieder ... mehr oder weniger.}
{164}{}{Klingt nach einer sehr nützlichen Pflanze. Wo findet man sie?}
{165}{}{Du kannst Nüsse bei mir oder im „Tin angel“ kaufen. Und wenn du sie selbst sammeln willst, solltest du durch unbewohnte Gegenden mit viel schmutzigem Wasser streifen. Vocas wächst unter ziemlich unangenehmen Bedingungen. Denk nur daran, dass sie zweimal im Jahr reift – im Frühling und im Herbst. Zu diesen Jahreszeiten liegen sie körbeweise in den Regalen.}
{166}{}{Verstanden. Danke, dass du mir das erzählt hast.}
{167}{}{Verstanden. Vielleicht kannst du mir noch etwas dazu erklären?}

#Recipe of the nut extract
{168}{}{Ich glaube, ich weiß, wie wir das Problem lösen können. Zum Glück hat mir meine Überlebenserfahrung auf Reisen zwischen den Städten schon oft das Leben gerettet.}
{169}{}{... Du meinst also, wir müssen einen Extrakt aus den Nüssen herstellen und ihn intravenös statt oral verabreichen? Brillant! Einfach brillant!}
{170}{}{Es scheint, dass Nüsse mit strahlenschützender Wirkung hier weit verbreitet sind, aber die Leute leiden trotzdem. Woran liegt das?}
{171}{}{Vocas wirkt nur schwach, besonders im Vergleich zu Medikamenten aus der Vorkriegszeit. Es hilft erst, wenn man regelmäßig ganze Handvoll davon nimmt. Aber selbst dann gibt es Einschränkungen.}
{172}{}{Was verhindert die regelmäßige Prophylaxe?}
{173}{}{Nun, die Nüsse reifen nur zweimal im Jahr, daher ist eine regelmäßige Einnahme schwer zu erreichen. Außerdem verträgt der Körper diese schwere Kost nicht besonders gut. Mir ist in letzter Zeit aufgefallen, dass diese Pflanze umso weniger nützt, je öfter die Leute Vocas essen. Der Körper wird übersättigt und ein natürlicher Schutzmechanismus setzt ein. Das ist leider kein Allheilmittel für uns.}
{174}{}{Ich glaube, ich weiß, wie wir dieses Problem lösen können. Zum Glück habe ich reichlich wissenschaftliche Kenntnisse in Chemie.}
{175}{}{Meinst du das ernst? Oh, ich würde mich liebend gern mit dir am Labortisch unterhalten. Also ... Was schlägst du vor, Kollege?}
{176}{}{Meine Berufsgeheimnisse sind teuer. Ich verrate sie dir für 350 $.}
{177}{}{Ich teile mein Wissen sehr gern mit denen, die es zum Wohl der Menschen einsetzen können.}
{178}{}{Tut mir leid, aber gerade kann ich nicht – ich muss arbeiten.}
{179}{}{Gemeinsam mit dem Apotheker hast du ein Mittel zur Vorbeugung von Strahlenkrankheit entwickelt. Das wird der ganzen Stadt sehr nützen.}

#About the current sanitary conditions
{180}{}{Zu den hygienischen Bedingungen in der Stadt: Wie sind sie jetzt? Kannst du es mir sagen?}
{181}{}{Jetzt ist es ruhig. Die Seuche scheint vorbei zu sein, aber für endgültige Schlussfolgerungen ist es noch zu früh. Die Menschen werden seltener krank und leiden weniger an Darminfektionen. Ich hoffe, das bleibt so.}
{182}{}{Schrecklich. Die Seuche ist in der ganzen Stadt ausgebrochen. Die Menschen sterben an Darmerkrankungen, und wir können nichts für sie tun. Meine Vorräte sind knapp, und nicht jeder kann es sich leisten, sie zu kaufen. Ich weiß nicht, wie lange das noch so weitergeht.}
{183}{}{Alles ist wie früher. Es gibt in der Stadt immer noch vereinzelte Fälle von Darmerkrankungen, aber bisher gab es nur sehr wenige Todesfälle.}
{184}{}{Was soll ich sagen ... Jede Stadt im Ödland hat Probleme mit der Gesundheitsversorgung. Aber die Menschen kommen irgendwie damit zurecht, also überleben die meisten. Was in Salt Lake passiert, ist kompliziert: Einerseits hat uns die Natur reichlich Wasser und eine wunderbare Vocas-Pflanze geschenkt, andererseits wagen wir uns wegen der Gefahr einer Vergiftung und Verstrahlung nicht einmal in die Nähe des Great Salt-Sees. Außerdem trägt die Nuka-Cola-Fabrik offensichtlich zum Problem bei. Ein komplizierter Fall.}

#Selling Niskigwan's backpack 
{185}{}{Ich habe allerlei medizinisches Zubehör. Interesse?}
{186}{}{Eigentlich halte ich mich lieber an die zivilisierte Medizin. Aber heutzutage ist man froh über jedes zusätzliche Hilfsmittel. Mal sehen, vielleicht ist etwas Nützliches dabei.}
{187}{}{Sieh mal.}
{188}{}{Ja, ein paar Sachen könnten nützlich sein, besonders diese hier. Der Arzt, der sie benutzt hat, scheint ziemlich erfahren gewesen zu sein. Ich gebe dir 1000 $ für diese Tasche.}
{189}{}{Abgemacht.}
{190}{}{Ich suche mir großzügigere Kunden. Auf Wiedersehen.}
{191}{}{Ja, manche Schmuckstücke können nützlich sein, besonders diese hier. Der Sanitäter, der sie benutzt hat, scheint ziemlich erfahren gewesen zu sein. Aber da die Stadt jetzt nicht mehr so viele Probleme mit Krankheiten hat wie früher, brauche ich diese Werkzeuge nicht. Ich kann dir also nur 500 Dollar dafür geben.}
{192}{}{[Nickt und gibt dir das Geld, während sie die Werkzeuge an sich nimmt]}

{193}{}{Ich glaube, ich weiß, wie man dieses Problem lösen kann. Zum Glück habe ich viel medizinische Erfahrung.}
{194}{}{Ich glaube, ich weiß, wie wir dieses Problem lösen können. Zum Glück habe ich reichlich wissenschaftliche Kenntnisse in Chemie.}

#About the increased amount of goods when there is a good environmental situation
{195}{}{Gern! Das kommt gerade recht, denn seit die Stadt ihre Krankheitsprobleme losgeworden ist, haben sich die Waren gestapelt. Merk dir also: Wenn du jetzt zu mir kommst, ist das Regal nicht mehr leer.}
{196}{}{Das ist gut ... ich meine, natürlich gut für mich. Na los, mal sehen, was du hast.}
{197}{}{Dank der verbesserten Umweltbedingungen in der Stadt wird der Warenbestand der Apotheke doppelt so oft aufgefuellt.}

#Manufacture of medicine
{200}{}{Stellst du Medikamente her?}
{201}{}{Ich kann Heilpulver, Gegengifte, Stimpaks und den „Blutreiniger“ herstellen. Aber du musst mir die Zutaten bringen, denn meine Vorräte sind knapp. Also, was brauchst du?}
{202}{}{Gegengift.}
{203}{}{Stimpak.}
{204}{}{„Blutreiniger“.}
{205}{}{Heilpulver.}

{209}{}{Reden wir über etwas anderes.}
{210}{}{Nichts. Gehen wir zurück.}

{211}{}{Ich stelle es her, wenn du mir den Schwanz eines Radskorpions bringst. Es kostet }
{212}{}{Ich stelle es her, wenn du mir einen leeren Great Salt-See, eine Xanderwurzel und eine Broc-Blüte bringst. Es kostet }
{213}{}{Ich stelle es her, wenn du mir eine Xanderwurzel, eine Broc-Blüte und zwei Handvoll Tollkirschen bringst. Es kostet }
{214}{}{Ich stelle es her, wenn du mir eine Xanderwurzel und eine Broc-Blüte bringst. Es kostet }

{218}{}{Was kannst du noch mal herstellen?}
{219}{}{ Dollar pro Dosis.}

{220}{}{Eine Dosis herstellen.}
{221}{}{Zwei Dosen herstellen.}
{222}{}{Drei Dosen herstellen.}
{223}{}{Vier Dosen herstellen.}
{224}{}{Fünf Dosen herstellen.}
{225}{}{Zehn Dosen herstellen.}
{226}{}{Stelle so viele Dosen wie möglich her.}

{230}{}{[Der Apotheker schüttelt spöttisch den Kopf, während er zusieht, wie du nervös deine leeren Taschen durchsuchst und nach Dingen suchst, die gar nicht da sind]}
{231}{}{Hoppla ...}
{232}{}{Fertig. Sonst noch etwas?}
{233}{}{Noch ein Medikament, bitte.}
{234}{}{Reden wir jetzt, wenn es dir nichts ausmacht.}
{235}{}{Das wäre alles. Bis dann.}

#The achievement of the medicaster
{240}{}{Kannst du mir beibringen, wie man Medizin herstellt?}
{241}{}{Leider nein. Dafür braucht man zumindest ein wenig Wissen über die Eigenschaften der Heilkräuter des modernen Ödlands.}
{242}{}{Schade. Ich wollte diese Fertigkeit unbedingt erlernen ...}

{243}{}{Nun, ein wenig zusätzliches Einkommen wäre nicht schlecht. Aber woher soll ich wissen, wofür du dein Wissen einsetzen wirst? Was, wenn du beschließt, mein Konkurrent zu werden oder sogar mit der Drogenproduktion anzufangen? Und ich will keinen Ärger mit dem Sheriff.}
{244}{}{Nun, ein wenig zusätzliches Einkommen wäre nicht schlecht. Ich bin bereit, mein Wissen einer so guten Person wie dir anzuvertrauen. Aber ich hoffe, dass ich im Gegenzug etwas bekomme, okay?}
{245}{}{Ich zahle 1.000 $ für den Unterricht.}
{246}{}{Darüber entscheiden wir ein andermal.}

{247}{}{Da du der Stadt sauberes Wasser zurückgebracht hast, helfe ich dir gern.}
{248}{}{Großartig. Sollen wir anfangen?}
{249}{}{Jetzt nicht, ich habe andere Dinge zu erledigen.}

{250}{}{Hey, das gehört mir!}
{251}{}{Aber ich habe diese Sachen auf ehrliche Weise erworben. Wenn du sie also haben willst, musst du dafür bezahlen.}
{252}{}{Grr ...}

#Artesian water filter, addition
{260}{}{Danke! Unsere Stadt ist jetzt gerettet. Aber ich kann dich nicht ohne eine kleine Belohnung gehen lassen. Hier, bitte. [Er gibt dir ein Super-Stimmpack und ein Ultra-Gegengift.] Das sind sehr teure Medikamente. Ich könnte sie an die Reichen verkaufen, aber du brauchst sie vielleicht dringender.}
{261}{}{Dazu sage ich nicht nein.}

{262}{}{Hast du Medikamente gegen Herzkrankheiten auf Lager?}
{263}{}{Leider nicht. Und ich würde dir nicht raten, darauf zurückzugreifen. Wer weiß, welche Nebenwirkungen sie in den Jahren nach dem Großen Krieg entwickelt haben? Wie auch immer, du musst in größeren, saubereren Städten wie Las Vegas danach suchen.}
{264}{}{Verstanden.}

#Treatment of infection
{265}{}{Ich fühle mich fiebrig und der Husten bringt mich um ... Gibt es ein Heilmittel gegen so eine Krankheit?}
{266}{}{Lass mich dich untersuchen ... Das ist eine Infektion. Mit Tollkirschenbeeren, die mit Alkohol vermischt werden, lässt sie sich recht gut behandeln. Aber diese Behandlung ist immer noch viel weniger wirksam als das ordnungsgemäß hergestellte Arzneimittel auf Grundlage derselben Beeren. Das kannst du bei mir kaufen, es heißt „Blutreiniger“ ... Falls es noch vorrätig ist.}
{267}{}{Mal sehen, ob du etwas Wirksames im Angebot hast.}
{268}{}{Oh, danke für den Tipp! Wenn ich mir im Ödland ein Lager aufschlage und krank werde, kann ich mich vielleicht gleich vor Ort am Lagerfeuer behandeln lassen.}
{269}{}{Der Apotheker hat dir beigebracht, die Infektion am Lagerfeuer mit Wildpflanzen und Alkohol zu behandeln.}

#Treatment
{270}{}{Ich muss mich heilen lassen.}
{271}{}{Klar. Aber du musst dafür bezahlen.}
{272}{}{[Die vollständige Behandlung: }
{273}{}{[Wunden behandeln: }
{274}{}{[Vergiftung behandeln: }
{275}{}{[Eine Verstümmelung behandeln: }
{276}{}{[Verstrahlung behandeln: }
{277}{}{Für heute reicht's. Lass uns reden.}
{278}{}{Auf Wiedersehen, Doc.}
{279}{}{$]}
{280}{}{Das Geld reicht nicht aus, um die Behandlungskosten zu decken.}
{281}{}{Jetzt ist alles in Ordnung.}
{282}{}{Danke, Doc. Ich gehe dann lieber.}
{283}{}{[Die Infektion behandeln: }

#PLC
{290}{}{Ich erledige einige Arbeiten für die Nuka-Cola-Fabrik. Und man hat mir gesagt, ich soll nicht mit dir darüber reden. Warum?}
{291}{}{[Lächelt traurig] Ich und verschiedene Aktivisten hatten Konflikte mit der Werksleitung. Zum Beispiel, weil die flüssigen Abfälle aus dem Werk die ohnehin schon zerstörte Natur in der Stadt noch weiter zerstören. Dieses Problem betrifft alle in Salt Lake..}
{292}{}{Also ist das der Grund ...}
{293}{}{Also, was für eine Arbeit machst du für die Fabrik?}
{294}{}{Ich habe den Auftrag bekommen, die Steuerungseinheit zu reparieren, mit der man die automatischen Anlagen nutzen kann.}
{295}{}{Das kann ich nicht sagen. Auf Wiedersehen.}
{296}{}{Oh mein Gott! Ich hoffe, du willst den Auftrag nicht ausführen?}
{297}{}{Warum?}
{298}{}{Wenn die Fabrik die Automatisierung wiederherstellt, wird das für alle schlecht sein, außer für eine Handvoll leitender Manager dieser Firma! Im Moment wird vieles von Hand erledigt. Aber wenn die Förderbänder ohne menschliches Zutun laufen, werden viele Arbeiter auf die Straße gesetzt. Außerdem würde dadurch die Produktion der Fabrik stark steigen, was dazu führen wird, dass sie die Stadt mit ihren Abfällen noch mehr verschmutzt.}
{299}{}{Hm. Was für eine seltsame Ironie – ohne die Fabrik ist es schlecht für die Stadt, und mit ihr auch nicht besser. Also, was schlägst du vor?}
{300}{}{Gib mir die Steuerungseinheit, ich werde sie zerstören. Im Gegenzug zahle ich dir 350 Kröten, mehr kann ich nicht bieten. Aber du tust damit etwas Gutes! Und was die Fabrik angeht: Für sie wird die Lage dadurch nicht SCHLECHTER.}
{301}{}{Na gut, nimm das Gerät. Auch wenn es weniger Geld ist, spare ich mir die damit verbundenen Kosten und fühle mich besser, wenn ich etwas Gutes tue.}
{302}{}{Gib mir etwas Zeit, darüber nachzudenken.}
{303}{}{Nur wenige würden auf mögliche Einnahmen verzichten, um sich für das Wohl einer Stadt einzusetzen, die nicht ihre eigene ist. Danke.}
{304}{}{Gern geschehen.}

#Women's replics:
{1122}{}{Über den Filter für den artesischen Wasserturm. Ich habe ihn gefunden! Aber wie bringt man den Turm wieder zum Laufen? Gibt es jemanden, mit dem ich darüber sprechen kann?}
{1138}{}{Ich war beim artesischen Wasserturm in den Slums. Hat schon jemand versucht, ihn zu reparieren? Das würde der Stadt Unmengen sauberes Wasser bringen!}
{1160}{}{Ach, deshalb habe ich auf dem Weg hierher gesehen, wie die Leute ständig auf etwas herumkauten ...}
{1177}{}{Ich teile mein Wissen sehr gern mit denen, die es zum Wohl der Menschen einsetzen können.}
