{100}{}{Du siehst einen Bürger.}
{101}{}{Vor dir steht eine Frau mittleren Alters. Sie scheint den ganzen Tag geweint zu haben.}
{102}{}{ }

#Ïîñëå óáèéñòâà ìóæà
{110}{}{::seufzt schwer::}
{111}{}{Danke, dass du mich davor gerettet hast ...}
{112}{}{Verschwinde!}

#Äèàëîã ñ ìóæåì
{150}{}{Schrei mich nicht an!}
{151}{}{Du Miststück! Du versuchst nicht mal zuzuhören!!!}
{152}{}{Warum sollte ich dir zuhören?! Das hab ich schon mal gehört ...}
{153}{}{Mir ist egal, was du gehört hast! Hörst du mir jetzt zu oder nicht?!}
{154}{}{Nein, tu ich nicht!}
{155}{}{Warum?! Warum muss ich mich vor meiner Frau demütigen?!}
{156}{}{Du demütigst dich?! Nein, du demütigst deine Frau!}
{157}{}{Du Schlampe! Warum hasst du mich?! Was habe ich dir je getan?!}
{158}{}{Du schreist mich jeden Tag ohne Pause an!}
{159}{}{Schlampe ... Du Schlampe ...}
{160}{}{Bei *jedem* deiner Saufgelage! Wie lange noch?!}
{161}{}{Ja, ich bin betrunken! Na und?! Heißt das, dass man mich so behandeln darf?!}
{162}{}{Niemand behandelt dich „so“! Hör auf!}
{163}{}{Doch, tust du! Statt Liebe und Fürsorge bekomme ich das hier ...}
{164}{}{Wie soll ich mich um dich kümmern, wenn du mich schlägst und beleidigst?!}
{165}{}{DU HURE!!! Eines Tages bringe ich dich um!}
{166}{}{Und dafür wirst du in der Hölle brennen. Dort gehörst du hin.}
{167}{}{Ich?! In der Hölle?! Schlampe! Ich tue so viel für dich! ...}
{168}{}{Was tust du denn?! Bild dir bloß nichts ein ...}
{169}{}{Wer hat gestern den Muell rausgebracht? Warum muss immer ICH den Muell rausbringen?}
{170}{}{Ja, streng dich nicht zu sehr an, du armes Ding ...}
{171}{}{Was?! Du Hure, ich hab's doch schon gesagt! ICH werde mir einen Job suchen!}
{172}{}{Na, wenn du einen hast, kannst du damit angeben. Aber bis dahin lastet der ganze Haushalt auf meinen Schultern.}
{173}{}{Wovon redest du überhaupt, du Dummkopf?! Du hockst nur im Haus herum, während ich alles repariere und in Ordnung bringe!}
{174}{}{Ich sehe, du weißt meine Arbeit wirklich zu schätzen, was?}
{175}{}{Warum weißt du meine nicht zu schätzen, hä?!}
{176}{}{Was denn *deine*? Was hast du im letzten Jahr schon getan?}
{177}{}{Wenn ich nicht wäre! ...}
{178}{}{„Ich, ich, ich“, die ganze Zeit. Sonst nichts ...}
{179}{}{DU SCHLAMPE!!! DU HURE!!! ICH BRING DICH UM!!!}

#Äèàëîã ñ íåé
{200}{}{[Die Frau ist in Tränen aufgelöst] Warum bist du hier?}
{201}{}{Warum weinst du?}
{202}{}{Sei nicht so aufgebracht, alles wird gut!}
{203}{}{Ich will mich doch nur über ein heulendes Weib lustig machen.}
{204}{}{Äh, geht mich nichts an. Ich verschwinde.}

{205}{}{Hau ab, bevor ich meinen Mann rufe!}
{206}{}{Wird er dich wirklich beschützen?}
{207}{}{Na los, Schlampe, ruf deinen Wichser!}
{208}{}{Schon gut, schon gut, ich gehe ja.}

{209}{}{Reiz mich nicht! Merck ist sehr gefährlich, besonders wenn er betrunken ist. Und jetzt ist er betrunken.}
{210}{}{Betrunken und gefährlich? Frau, das ergibt doch keinen Sinn.}
{211}{}{Wie auch immer! Ich geh und mach mich über ihn lustig.}

{212}{}{Du kannst es einfach nicht lassen, was? Merck wird sich freuen, dir eine reinzuhauen, glaub mir!}
{213}{}{Nein, ich will nur wissen, würde er dich wirklich beschützen?}
{214}{}{Ich will nur wissen, warum du weinst.}
{215}{}{Schon gut, ich lass dich in Ruhe.}
{216}{}{Oh ja! Ärger, ich komme!}

{217}{}{Ja. Was für ein Paradoxon. Männer ...}
{218}{}{Wer hat dich zum Weinen gebracht?}
{219}{}{Dann ist doch alles in Ordnung, oder?}

{220}{}{Bist du nicht ein Optimist? Leider hilft das heutzutage niemandem ...}
{221}{}{Diesmal schon!}
{222}{}{Warum weinst du dann?}
{223}{}{Heißt das, du weinst ohne Grund? Du bist so dumm!}
{224}{}{Vielleicht haben wir nichts zu bereden.}

{225}{}{Das glaube ich nicht.}
{226}{}{Dann sag mir wenigstens, wer dich aufgeregt hat.}
{227}{}{Ha, du weinst ohne Grund? Du bist so dumm!}
{228}{}{Na gut, dann lass ich dich jetzt in Ruhe.}
{229}{}{Stell das männliche Vorrecht nicht infrage, Schlampe!}

{230}{}{Es ist Merck. Er schreit mich ständig an. Dieser Bastard ... Ich hab so viel für ihn getan ... Und er ... Er denkt nur an sich! Immer nur "ich" und "ich" ...}
{231}{}{Und du gibst ihm natürlich einen Grund, dich anzuschreien?}
{232}{}{Warum macht er das?}
{233}{}{Ist er immer so aggressiv?}
{234}{}{Du bist so dumm! Von Tränen wird dir auch nicht geholfen!}
{235}{}{Hast du schon versucht, um Hilfe zu bitten?}
{236}{}{Na gut, ich will dir nicht länger zuhören.}
{237}{}{}
{238}{}{[Nach deiner nächsten Beleidigung bricht die Frau in Tränen aus. Sie wird nicht mehr mit dir sprechen.]}
{239}{}{Du dummer Idiot, das wird dir nicht helfen!}

{240}{}{Warum du ...}
{241}{}{Ja, sicher ... Schönen Tag noch.}
{242}{}{Pass auf dich auf.}
{243}{}{Ja, ich weiß. Ich hoffe, du bist mit deinen Fragen fertig.}
{244}{}{Ja, es ist schön, eine weinende Frau zu sehen und zu wissen, dass ich nichts damit zu tun habe.}
{245}{}{Ja, sicher, tut mir leid.}

{250}{}{Offensichtlich verbringst du nicht viel Zeit mit Betrunkenen. Leute wie Merck brauchen keinen Grund – sie finden einfach einen. Es spielt keine Rolle, was ich tue.}
{251}{}{Ein typischer Kerl mit dicken Eiern. Und er will, dass es jeder weiß. Er hält sich für einen Meister und großen Mann. Dabei kann er nicht einmal die Schranktür reparieren.}
{252}{}{Nein, nur wenn er betrunken ist. Und das ist fast jeden Tag der Fall. Wenn er nüchtern ist, kann man sogar ganz angenehm mit ihm reden. Er kann Witze machen und nette Dinge sagen ...}
{253}{}{Wer in dieser Stadt hilft jemandem in Not? Der Sheriff will sich nicht in die Angelegenheiten einer Familie einmischen, und die Nachbarn wollen sich keine Feinde machen. Außerdem, was können sie schon tun? Mit einer Waffe kommen und ihm in den Kopf schießen? Das wäre extrem. Und gefährlich.}
{254}{}{Dann helfe ich dir!}

{255}{}{Warum? Warum willst du dich einmischen?}
{256}{}{Ich will damit Profit machen.}
{257}{}{Ich will einfach nur helfen – ich kann die Tränen von Frauen nicht ertragen.}
{258}{}{Du brauchst Hilfe, oder? Was gehen dich meine Beweggründe an?}
{259}{}{Was rede ich da bloß! Ich kann dir nicht helfen. Tut mir leid.}
{260}{}{Wenn ich einen Söldner kennen würde, hätte ich ihn schon angeheuert.}
{261}{}{Wie edel von dir. Leider habe ich schon vor langer Zeit das Vertrauen in Fremde verloren.}
{262}{}{Hm, weißt du ... Na gut.}
{263}{}{Hast du eine Idee, was zu tun ist?}
{264}{}{Vielleicht, aber ich will dir nicht mehr helfen. Tschüss.}
{265}{}{Wie edelmütig von dir. Ich hoffe, du hast genug Herz dafür.}
{266}{}{Keine Sorge! Hast du eine Idee, was zu tun ist?}
{267}{}{Eine Idee? Ich hatte gehofft, du würdest selbst auf eine kommen. Na gut ... Ich habe eine Flasche vergifteten Mondschein. Aber ich kann es nicht tun. Außerdem könnte er es durchschauen, weil ich ihm noch nie so einen Drink gegeben habe.}
{268}{}{Gib mir die Flasche.}
{269}{}{Noch etwas?}
{270}{}{Vergiss es, ich finde selbst eine Lösung.}
{271}{}{Okay, viel Glück.}
{272}{}{[Verlassen]}
{273}{}{Nun, die örtliche Polizei wird sich wohl kaum in die Angelegenheiten unserer Familie einmischen. Falls es zu einem Kampf kommt, brauchst du dir um sie keine Sorgen zu machen. Nur, damit du Bescheid weißt.}
{274}{}{[Sie holt eine Flasche aus einem Versteck] Hier. Übrigens wird sich die örtliche Polizei wohl kaum in die Angelegenheiten unserer Familie einmischen. Falls es zu einem Kampf kommt, brauchst du dir um sie keine Sorgen zu machen. Nur, damit du Bescheid weißt.}
{275}{}{[Sie holt eine Flasche aus einem Versteck] Hier. Ich hoffe, du hast den Mut, es zu tun.}
{276}{}{Weißt du was? Räum den Scheiß selbst auf! Ich bin weg!}
{277}{}{Ich brauche nichts, ich werde damit auf meine Weise fertig.}
{278}{}{Das reicht. Ich finde selbst eine Lösung.}
{279}{}{Ich finde selbst eine Lösung.}

#Female character
{1220}{}{Bist du nicht ein Optimist? Leider hilft das heutzutage niemandem ...}
{1244}{}{Ja, es ist schön, eine weinende Frau zu sehen und zu wissen, dass ich nichts damit zu tun habe.}
{1278}{}{Das reicht. Ich finde selbst eine Lösung.}
