{100}{}{Du siehst einen Säufer.}
{101}{}{Du siehst einen dreckigen und äußerst unhöflichen Mann. Er trinkt eindeutig zu viel Alkohol.}
{102}{}{Das Familienproblem wurde gelöst.}
{103}{}{Scheiße! Dieser Idiot hat seine Frau umgebracht!}
{104}{}{Was hast du getan?!}
{105}{}{Dieser Idiot ist unverbesserlich. Dein Gespräch mit ihm hat seine Überzeugungen nur noch bestärkt.}
{106}{}{Du hast das Familienproblem ohne Blutvergießen und Gewalt gelöst.}
{107}{}{Der Säufer hat so große Angst, dass er sich diese Lektion lange merken wird.}
{108}{}{Merck hat solche Angst vor dir, dass er es nicht wagen wird, seiner Frau gegenüber unhöflich zu sein.}

{109}{}{ }

{110}{}{Wer zum Teufel bist du?!}
{111}{}{Neeeein! Was habe ich getan!?}
{112}{}{::weint hysterisch::}
{113}{}{NEIN!!! Miststück, wie konntest du mir das antun?!}
{114}{}{Nicht das! Wie konnte ich nur?!}
{115}{}{DAS ALLES WEGEN DIR!!!}

{116}{}{Lass mich in Ruhe!}
{117}{}{Na, hallo, schätze ich ...}

#Ñòàðûé äèàëîã, èñïîëüçóåòñÿ ÷àñòè÷íî:
{118}{}{Du hast recht, Kumpel, wir müssen einander helfen ... Willst du ein Glas Selbstgebrannten?}
{119}{}{Du hast recht, Kumpel. Willst du mit mir einen „Bloody Mary“ teilen?}

{120}{}{Ich versteh das nicht! Wer zum Teufel bist du?! Und was zum Teufel willst du von meiner Frau?!}

{121}{}{Sie hat mir gerade erzählt, dass es ihr schwerfällt, mit dir zu reden. Eine Frau muss sich doch mal Luft machen, oder?}
{122}{}{Mit ihr? Nichts. Aber sie will dich tot sehen. Verabschiede dich lieber jetzt!}
{123}{}{Na ja, vielleicht ... Weiber beschweren sich immer, wenn ihnen was nicht passt ...}
{124}{}{Na und, was ist so schlimm daran?}
{125}{}{Du liegst falsch. Du musst netter und sanfter zu deiner Frau sein.}
{126}{}{Dafür mach ich dich fertig! ... [schlag ihm ins Gesicht]}
{127}{}{Waaas?! Seh ich für dich aus wie ein Kind? Willst du mir was über das Leben beibringen? Warum hassen mich alle?! Was hab ich getan?! Ich wollte mich nur entspannen, ein paar Bier trinken, aber alle gehen auf mich los! Du, meine Frau, alle!}
{128}{}{Seltsam, das von einem Mann zu hören, der nichts tut. Leb wohl.}
{129}{}{Dein Ego ist zu groß. Ich mach's kleiner ... zusammen mit deinem Leben!}
{130}{}{Alles! Ich versuche, es ihr zu erklären – ein Mann hat eben auch mal schlechte Zeiten, ja, hat keinen Job und so weiter. Und was macht sie?! Sie will nicht mit mir kuscheln, mich wärmen oder mir was zu essen geben! Wenn ein Mann in Schwierigkeiten steckt, braucht er schließlich Hilfe!}
{131}{}{Du hast recht, Kumpel, wir sollten einander helfen ...}
{132}{}{Du hast recht, Kumpel, wir sollten einander helfen ... Willst du ein Bier?}
{133}{}{Warum hilfst du dir dann nicht selbst, wenn du so schlau bist? Warum sollte dir jemand helfen?}
{134}{}{Genau das sage ich ihr ... Ach! Du würdest es sowieso nicht verstehen.}
{135}{}{Nicht verstehen? Hm ...}
{136}{}{[Du hast mit diesem Schwachkopf dank deiner psychologischen Kenntnisse ein tiefgründiges Gespräch geführt. In seinem Kopf hat sich etwas verändert. Hoffentlich wird von nun an alles gut.]}
{137}{}{Na ja, ich muss los. Pass auf dich auf!}
{138}{}{[Du hattest ein tiefgründiges Gespräch mit diesem Schwachkopf. Er hat dir jede Menge spirituellen Scheiß erzählt, aber in ein paar Wochen hat er bestimmt noch mehr davon auf Lager ...]}

#Íîâûé äèàëîã:
{150}{}{Wir kennen uns nur von früher, kümmere dich nicht drum.}
{151}{}{Ich bin ihr Gewissen. Wenn sie es braucht, kann sie sich bei mir ausweinen.}
{152}{}{Ich ... Äh ... Ich bin dein neuer Nachbar und wollte nur Hallo sagen.}
{153}{}{Von ihr? Nichts. Sie will dich tot sehen. Sag Lebewohl!}

{154}{}{Für wen hältst du dich?! *Ich* bin der Mann im Haus! Wenn du mit meiner Frau reden willst, frag erst mich um Erlaubnis!}
{155}{}{Ist sie dein Eigentum? Willst du das damit sagen?}
{156}{}{Ich stehe doch direkt vor dir. Beruhig dich, Mann.}
{157}{}{Du Abschaum! Wage es ja nicht, sie so zu behandeln!}
{158}{}{Warum denn? [Er schneidet eine alberne Grimasse] Oooh! Willst du mich dafür verprügeln?}
{159}{}{Reg dich nicht so auf, wir können das friedlich lösen!}
{160}{}{Ja, dann hast du einen weiteren Feind. Ist es das, was du willst?}
{161}{}{Ganz genau, und zwar sofort!}

{162}{}{Du bist einfach ein Stück Scheiße! Hau ab!}
{163}{}{Hey, immer mit der Ruhe!}
{164}{}{Wie kannst du es wagen! Nimm das, du Wichser!}
{165}{}{[Sieht dich bekifft an und öffnet den Mund] Mich in meinem eigenen Haus zu beleidigen! Was bist du doch für ein Arschloch!}
{166}{}{[Pack seinen Arm und drück ihn ihm auf den Rücken]}
{167}{}{Hey! Hey! Immer mit der Ruhe! Ich habe nichts getan!}
{168}{}{Vor einer Minute hast du noch den großen Macker gespielt. Was ist los?}
{169}{}{Was zum Teufel willst du von mir!?}
{170}{}{Tu nicht so blöd, du Dreckskerl! Deine Frau kann dich nicht ausstehen!}
{171}{}{Nichts. Werd erst mal nüchtern, du verdammter Säufer.}
{172}{}{Das ist *meine* Frau! Wer zum Teufel bist du, dass du ...}
{173}{}{Halt die Klappe und hör mir zu!}
{174}{}{Du hast recht. Sie ist deine Frau, ich werde mich nicht zwischen euch stellen.}
{175}{}{Ugh ...}
{176}{}{Wenn ich dich noch einmal dabei erwische, wie du deine Frau schlägst, ist das dein letzter Tag!}
{177}{}{Schon gut, schon gut, ich hab's kapiert ... Ich ... ich hab's kapiert! Kein Problem!}
{178}{}{Das werden wir sehen. Ich werde deine jämmerliche Familie im Auge behalten.}
{179}{}{Ich hab's kapiert, okay!}
{180}{}{Gut. Und jetzt werd nüchtern, du verdammter Säufer!}
{181}{}{Weißt du, wie viele Leute ich umgebracht habe, während ich durchs Ödland streifte?}
{182}{}{[Es scheint, als würde dieser Säufer nüchtern] Äh ...}
{183}{}{?}
{184}{}{. Und du kannst zum }
{185}{}{-ten werden.}
{186}{}{Was ... Nein! Neeein! Warum!? Warum!?}
{187}{}{Tu nicht so blöd, du weißt warum.}
{188}{}{Du solltest besser aufhören. Meine Hände jucken schon.}
{189}{}{Einfach, weil ich Lust dazu habe. Und jetzt verpiss dich.}

{190}{}{Einfach so? Du würdest einen Mann umbringen, weil er sich mal Luft gemacht hat!?}
{191}{}{Halt die Klappe, Abschaum! Ich kenne keine einzige Stadt, in der man so etwas durchgehen lässt.}
{192}{}{[Schluckt] Bin ich wirklich so schlimm? Hat sie dich deshalb angeheuert? Um mich umzulegen?}
{193}{}{Ich tue das aus freien Stücken.}
{194}{}{Genau, sie hat ordentlich gezahlt.}
{195}{}{Ehrlich gesagt hat sie mir das Gift gegeben, aber ich fand, du hast das nicht verdient.}
{196}{}{Das reicht! Du darfst noch letzte Worte sprechen! Danach stirbst du!}

{197}{}{Zur Hölle, NEIN! Ich will nicht sterben! [Fällt auf die Knie] Verzeih mir! Es tut mir leid! Ich habe meine Fehler eingesehen! Ich werde mich benehmen! Ich schwöre! Gib mir nur noch eine Chance! A-ah!!!}
{198}{}{Du verdienst keine zweite Chance. Darüber hättest du früher nachdenken sollen. Jetzt stirb!}
{199}{}{Na gut. Du bekommst deine zweite Chance. Aber es wird auch deine letzte sein.}
{200}{}{Ich werde mich ändern! Ich schwöre!!!}
{201}{}{Das werde ich überprüfen. Und jetzt werd nüchtern, du verdammter Säufer.}
{202}{}{Ich bin ein MANN! Ein Mann, kein Waschlappen!}
{203}{}{Okay, okay, Macho, beruhig dich!}
{204}{}{Ein richtiger Mann sollte keine Frauen schlagen.}
{205}{}{Jetzt wollen wir mal sehen, was für ein Mann du bist! Komm raus und kämpf, Abschaum!}
{206}{}{Ich bin ein MANN! Ein Mann, kein Waschlappen! Das hier ist mein Haus! Und du?! Wer BIST DU?}

{207}{}{Klar, hier ist eine Flasche Fusel.}
{208}{}{Klar, hier ist eine Flasche "Bloody Mary".}
{209}{}{Klar, hier ist eine Flasche Bier.}

{210}{}{Ach, diese Weiber heulen immer gleich los. Das geht mir jedes Mal auf die Nerven! Hey, du, komm her, Schlampe! Mach mir was zu essen! Und es ist mir egal, dass wir nichts haben!...}
{211}{}{Ah! Gute Nachbarn sind was Feines. Hey, Idiot! Mach mir was zu essen, wir haben Gäste! Was? Du Hure, ich sagte, MACH MIR WAS ZU ESSEN! Und etwas zu saufen.}
{212}{}{Vergiss es, Kumpel, ich hab selbst was dabei. Auf ex, ja?}
{213}{}{Ohh!!! Genau mein Typ! Damit hättest du anfangen sollen! Lass die Schlampe links liegen, soll sie doch heulen... Wo waren wir? Richtig! Ein Schluck, ja?}
{214}{}{[Vergifteten Selbstgebrannten einschenken]}
{215}{}{Natürlich, hier ist eine Flasche Selbstgebrannter.}
{216}{}{Lass gut sein, mit so einem Grobian trinke ich nicht. Ich gehe.}
{217}{}{Oh, tut mir leid, ich muss los! Tschüss!}

{218}{}{Ha! Solche Nachbarn braucht man. Du bist jederzeit willkommen, sozusagen.}
{219}{}{[Weiter]}
{220}{}{[Trinkt das Glas Selbstgebrannten] Würg! Verdammt!... Hey, Nachbar, warum trinkst du nicht? Das geht doch nicht! Na komm, hier! Prost!}
{221}{}{Genau! Prost, Nachbar!}
{222}{}{Uääh! Oh, der war gut! Du hast einen ordentlichen Selbstgebrannten, Nachbar... warum trinkst du nicht? Ich versteh's nicht.}
{223}{}{Schwache Nieren.}
{224}{}{Ahh... Ich hab sogar ein bisschen geschwitzt! Weißt du, als ich noch bei der Polizei war, bekamen mein Partner und ich mal einen Tipp über ein Bordell. Wir mussten uns ja das Vertrauen der Drogendealer erschleichen, also haben wir ein paar Dosen genommen... Äh...}
{225}{}{Worum geht's?}
{226}{}{Mein Partner hatte das schlechte Zeug... Er starb zwei Tage später. Niemand konnte ihn retten. Und ich... [weint]}
{227}{}{Mein Freund, ihr beide standet euch wohl nahe?}
{228}{}{Wir waren fast wie *Brüder*! Ich kann immer noch nicht ... Verdammt, gib mir noch einen! Trink diesmal mit mir, ja? Wenigstens ein paar Schlucke.}
{229}{}{Ja, äh, klar.}
{230}{}{[Trinkt] Ughrr! Oh, hier drin ist es so heiß ... Wo hast du das Zeug her? Ist das von Harry dem Rattenfresser?}
{231}{}{Äh, nein, aus einer Bar.}
{232}{}{[Hält sich am Tischrand fest und fällt auf ein Knie] Ohhhh ... Der hat gesessen ... [lacht] Nicht mal russischer Wodka ist so stark! Oh ... Was hast du mir gegeben?}
{233}{}{... Äh, was war noch mal mit Harry dem Rattenfresser?}
{234}{}{... Er wohnt hier in der Nähe, brennt Mondschein und verkauft ihn in der Bar ... [kriecht über den Boden und versucht, sich hinzulegen] Hör zu ... Setz dich hierhin, während ich ... Äh ... Erzähl mir ... von dir ...}
{235}{}{Von mir? Weißt du, das ist nicht wichtig.}
{236}{}{Warum?..}
{237}{}{Schlaf, schlaf einfach. Wenn du aufwachst, erzähl ich dir alles.}
{238}{}{... Von dir?}
{239}{}{Von mir, davon, wie ich durch die Einöde streife – ich erzähl dir alles. Keine Sorge, schlaf.}
{240}{}{... Du ... Versprichst ... Du machst dich ... Nicht ... Über mich lustig ...}
{241}{}{[Schweigen]}
{242}{}{Also ... Ich ... Will ... Es hören ...}
{243}{}{[Das war sein letzter Atemzug]}

{244}{}{Du hast dich mies verhalten und diesen Säufer vergiftet. Aber so ist es besser.}
{245}{}{Warum behandelst du sie, als wäre sie dein Eigentum?}

#Female character
{1104}{}{Was hast du getan?!}
{1152}{}{Ich ... Äh ... Ich bin dein neuer Nachbar. Wollte nur Hallo sagen.}
{1172}{}{Das ist *meine* Frau! Wer zum Teufel bist du, dass du ...}
{1181}{}{Weißt du, wie viele Leute ich umgebracht habe, während ich durchs Ödland streifte?}
{1195}{}{Ehrlich gesagt hat sie mir das Gift gegeben, aber ich fand, du hast das nicht verdient.}
{1206}{}{Ich bin ein MANN! Ein Mann, kein Waschlappen! Das hier ist mein Haus! Und du?! Wer BIST DU?}
{1220}{}{[Trinkt das Glas Selbstgebrannten] Würg! Verdammt!... Hey, Nachbar, warum trinkst du nicht? Das geht doch nicht! Na komm, hier! Prost!}
{1222}{}{Uääh! Oh, der war gut! Du hast einen ordentlichen Selbstgebrannten, Nachbar... warum trinkst du nicht? Ich versteh's nicht.}
{1232}{}{[Hält sich am Tischrand fest und fällt auf ein Knie] Ohhhh ... Der hat gesessen ... [lacht] Nicht mal russischer Wodka ist so stark! Oh ... Was hast du mir gegeben?}
