{100}{}{Du siehst einen Maschinisten.}
{101}{}{Das ist dein Partner, den du angeheuert hast, um dich als Lokführer zum Zug zu begleiten.}
{102}{}{Du stehst ohne Lokführer da. Du musst einen Ersatz finden.}

#Äèàëîã
{110}{}{Hallo. Ich kann jederzeit los, sag mir einfach wann, okay? Und weißt du, die Einheimischen wurden etwas misstrauisch, als ich anfing, von Zügen zu reden. Irgendetwas macht ihnen Angst. Geht mich natürlich nichts an, ich wollte dich nur warnen.}
{111}{}{Ich passe auf, danke. Wir sollten los. Pack deine Sachen und geh zum Bahnhof.}
{112}{}{Keine Sorge, ich kümmere mich um alles. Warte einfach hier.}

{113}{}{Endlich! Ich habe es satt, in diesem miesen Diner herumzuhängen. Aber wir hatten eine Abmachung – ich arbeite für dich, solange du mich bezahlst.}
{114}{}{Ich kenne die Abmachung. Wir haben 1000 $ vereinbart. Hier ist das Geld. Geh jetzt zum Bahnhof.}

{115}{}{Wie läuft's mit dem Zug? Alles bereit? Ich kann jederzeit los, sag einfach Bescheid.}
{116}{}{Das wollte ich gerade sagen. Mach dich bereit und geh zum Bahnhof.}
{117}{}{Noch sind nicht alle Vorbereitungen abgeschlossen. Warte hier, bis ich fertig bin.}

{118}{}{Ich glaube, wir haben 1000 $ vereinbart. Warte kurz, ich hole das Geld.}

#Åñëè ïåğñîíàæ áûë êóïëåí ó ğàáîòîğãîâöåâ â Âåãàñå:
{210}{}{Hallo, Herr. Ich kann jederzeit los, sag mir einfach wann. Und die Einheimischen sind etwas misstrauisch geworden, als ich anfing, von Zügen zu reden. Irgendetwas macht ihnen Angst. Geht mich natürlich nichts an, ich wollte dich nur warnen.}
{213}{}{Wie du befiehlst, Herr!}
{214}{}{Du bist ein ziemlich guter Sklave. Geh zum Bahnhof.}
{215}{}{Soll ich zum Bahnhof gehen? Jederzeit, Herr. Sag einfach Bescheid.}
{216}{}{Das wollte ich gerade tun. Mach dich bereit und geh zum Bahnhof.}
{217}{}{Noch sind nicht alle Vorbereitungen abgeschlossen. Warte hier, bis ich fertig bin.}

{218}{}{Warte, ich muss noch etwas erledigen. Warte hier.}
