{100}{}{Du siehst einen Manager.}
{101}{}{Du siehst den Hotelmanager. Er ist damit beschäftigt, den Staub von seinem Anzug zu pusten.}
{102}{}{Leg die Waffe weg, dann reden wir.}

#Starting replicas
{109}{}{Was?}
{110}{}{Möchtest du ein Zimmer buchen?}
{111}{}{Ja? Was willst du?}

{112}{}{Wollen wir ein wenig plaudern? Mich interessiert die Lage in der Stadt. Was gibt's Neues?}
{113}{}{Erzähl mir von der Stadt. Was gibt es zu sehen und wo kann man sich die Zeit vertreiben?}
{114}{}{Hier ist es ziemlich langweilig. Keine Musik, keine Zeitschriften.}
{115}{}{Ich brauche ein Zimmer zum Ausruhen. Was würde mich das kosten?}
{116}{}{Erzähl weiter.}
{117}{}{Ich will nichts, ich gehe dann.}
{118}{}{Noch eine Frage, wenn ich darf ...}
{119}{}{Na gut, danke.}

#About the hotel and the city:
{120}{}{Tja, was soll ich sagen ... [Er lehnt sich in seinem Sessel zurück und verschränkt die Finger auf dem Bauch.] Es ist nicht gerade der beste Ort in der Gegend. Ich meine, es gibt ja auch noch Vegas und Reno ... Obwohl ich eigentlich noch nie dort war, aber ... Na ja, ehrlich gesagt habe ich nicht viel zu erzählen.}
{121}{}{Na ja, offensichtlich das Hotel, in dem du gerade bist. Auf der anderen Straßenseite leuchtet das Schild eines „Tin Angel“-Cafés. Es hat ein besonderes Merkmal – den gotischen Stil! An Feiertagen treffen sich dort gern die Leute und kotzen sich nach einem Dutzend Bier vor dem Eingang aus.}
{122}{}{Die Straße runter findest du eine Handelshalle. Dort kannst du Waffen und anderen Kram kaufen. Wenn du allerdings Medikamente brauchst, solltest du lieber bei einem Apotheker aus der Gegend vorbeischauen. Er wohnt nördlich von hier, in der Nähe des Renaissanceplatzes. Ist nicht weit. Aber seine Auswahl ... [Er macht eine Geste und verzieht das Gesicht.] Na ja.}
{123}{}{Außerdem gibt es hier das Büro unseres Sheriff Burton. Er hat hier bei so ziemlich allem das Sagen. Also benimm dich und mach keinen Ärger – das mag er nicht. Es war nicht leicht, in der Stadt für Ordnung zu sorgen, aber er hat es geschafft. Verdammt, ich will gar nicht daran denken, was ohne ihn hätte passieren können ...}
{124}{}{Du kannst auch beim Nuka-Cola-Werk vorbeischauen und mit dem Direktor plaudern. Ohne ihn hätten wir verdammt noch mal weder sauberes Wasser noch Strom und all den anderen Komfort. Manche von uns haben sogar Haushaltsroboter. Ist das nicht cool? [Er zwinkert.]}
{125}{}{Und die Fabrik ist wirklich eine Wucht. Sie ist nicht weit von hier, Richtung Osten. Nur dieser Fabrik ist es zu verdanken, dass die Leute überhaupt noch wissen, dass es die Salt Lake gibt. Die Karawanen kommen hauptsächlich wegen der flüssigen Freude her, die dort hergestellt wird.}
{126}{}{Übrigens findest du die Karawanenleute selbst die Straße runter, auf der anderen Seite des Platzes.}
{127}{}{Ich weiß nicht, was ich sonst noch sagen soll. Ach ja, im Café gibt es ein paar Spielautomaten. Viel Spaß. [Er zwinkert.]}
{128}{}{Äch. Auf dem Platz beim Eingang steht ein Galgen. Wenn du willst, kannst du bis 16 Uhr warten und dir die Vorstellung ansehen. Ist nicht echt. So eine Art Unterhaltung hier vor Ort – jemand spielt den Henker, und jemand anderem wird irgendein kompletter Unsinn vorgeworfen, dann wird er „aufgehängt“. Alle amüsieren sich, und den Rest des Tages geht es allen prächtig.}
{129}{}{Das war alles. Sonst gibt es nichts Interessantes.}

#Comic magazines
{130}{}{[Er hebt eine Augenbraue] Das ist kein Unterhaltungsbetrieb. Wir brauchen hier Ruhe. Und doch ... Ich weiß, dass gute Hotels früher Zeitschriften auf den Kaffeetischen liegen hatten, für Gäste, die während ihres Aufenthalts nichts zu tun hatten. Aber um die Veröffentlichung von Druckerzeugnissen steht es in Salt Lake in letzter Zeit nicht zum Besten. Zeitschriften sind entweder bei den Atombombenangriffen verbrannt oder durch das feuchte Klima und die schlechte Lagerung verrottet. Was übrig blieb, haben die Mormonen für ihre Bibliothek mitgenommen.}
{131}{}{[Mehr]}
{132}{}{Du bist doch oft unterwegs, oder? Kannst du für mich nach ein paar Zeitschriften suchen? Ich kann nicht viel bezahlen, aber ein paar Zeitschriften aufzutreiben, wäre doch keine große Belastung für dich, oder?}
{133}{}{Ich werde versuchen, es nicht zu vergessen. Wechseln wir jetzt das Thema.}
{134}{}{Wenn mir so etwas über den Weg läuft, denke ich an dich. Leb wohl.}
{135}{}{Ich habe eine Comiczeitschrift.}
{136}{}{Wegen des Kaffeetischs ...}
{137}{}{Hast du etwas Passendes gefunden?}
{138}{}{Hier, eine tolle Comiczeitschrift.}
{139}{}{Ich habe eine Ausgabe der Erotikzeitschrift „Cat's Paw".}
{140}{}{Noch nicht, ich wollte nur wissen: An welchen Zeitschriften bist du interessiert?}
{141}{}{Noch nicht. Ich hätte gar nicht fragen sollen. Wechseln wir das Thema.}
{142}{}{Nein. Ich muss los.}
{143}{}{Unterhaltsames oder Erotisches. Irgendetwas, das man vor dem Schlafengehen lesen kann ... Hast du so etwas?}
{144}{}{Genau, was ich brauche! Ich zahle dir $40 dafür. Einverstanden?}
{145}{}{Klar. Gib mir das Geld, dann gehört sie dir.}
{146}{}{Lass mich kurz darüber nachdenken. Erzähl mir inzwischen etwas anderes.}
{147}{}{Klingt gut, aber ich muss darüber nachdenken. Bis dann.}
{148}{}{Du erhältst Erfahrungspunkte für die Lieferung.}
{149}{}{}

#To rent a room for a day
{150}{}{Das Zimmer ist für einen Tag gemietet. Für dich kostet es }
{151}{}{Ich nehme das Zimmer. Hier ist das Geld.}
{152}{}{Ich habe nicht genug Geld. Ich komme später wieder.}
{153}{}{Sehr gut. Ich bringe dich auf dein Zimmer.}
{154}{}{[Folge ihm]}
{155}{}{Du hast den ganzen Boden vollgekotzt! Wer soll das jetzt sauber machen?!}
{156}{}{Du fühlst dich ausgeruht und erholt.}
{157}{}{ Dollar. Um deinen Aufenthalt zu verlängern, zahl am nächsten Tag erneut.}

#About the city
{200}{}{Na, was gibt's Neues ... Was gibt's Neues ...}
{201}{}{Vor Kurzem wurde ein Dieb geschnappt. Es hat eine Weile gedauert, aber er stellte sich als ziemliches Wiesel heraus. Der Sheriff hatte zwei Jahre lang versucht, ihn aufzuspüren, aber ohne Erfolg. Zuerst dachten alle, es wäre die Provo-Bande, aber die sind zu hart im Nehmen – die hauen dir lieber gleich ins Gesicht, als zu stehlen. Und in letzter Zeit trauen sie sich kaum noch in die Stadt. Na, wenigstens ergibt jetzt alles einen Sinn. Und unser Sheriff ist großartig! Was für ein toller Job!}
{202}{}{Vor Kurzem kam heraus, dass irgendein Widerling die Nuka-Cola-Automaten ausraubt. Kannst du dir das vorstellen? Niemand versteht, wie das geht. Man kommt zum Automaten, und er ist einfach leer! Und es gibt keine Spuren eines Einbruchs. Wie macht er das nur, frage ich mich ...}
{203}{}{Es gibt beunruhigende Gerüchte. Manche sagen, Whip habe einen Söldner angeheuert, der alle in der Siedlung Provo abgeschlachtet hat. [Er macht mit der Hand eine schneidende Bewegung] Alle. Das muss verdammt schwierig gewesen sein. Der Sheriff will nicht zugeben, dass er den Auftrag dazu gegeben hat, aber das spielt keine Rolle – auch wenn es ziemlich beängstigend ist, waren alle erleichtert, die Nachricht zu hören.}
{204}{}{Gilmore wurde hingerichtet. Was für ein Dreckskerl ... Das war längst überfällig, aber niemand wollte ihn aus Provo holen, wo er sich versteckt hielt. Jetzt sollten sich seine Hinterwäldler-Kumpane beruhigen.}
{205}{}{Die Nuka-Cola-Fabrik floriert! Immer mehr Karawanen kommen hier vorbei, und in der Fabrik gibt es jede Menge freie Stellen. Ich kann gar nicht genug davon bekommen – ich habe es noch erlebt!}
{206}{}{Entweder war es ein Ablenkungsmanöver oder die Angestellten in der Nuka-Cola-Fabrik taugen einfach nichts, aber die Fabrik hat vor Kurzem den Betrieb eingestellt. Ohne sie wird es für die Stadt schwierig. Ich hoffe, dass sich die Lage dort eines Tages bessert ...}
{207}{}{Jetzt haben wir viel mehr sauberes Wasser. Jemand hat einen artesischen Wasserturm in Betrieb genommen. Das ist sensationell!}
{208}{}{Die Lage mit dem Wasser wird immer schlimmer. Niemand weiß, was zu tun ist. Jeden Tag verstopfen die Besucher die Toilette, sogar die Wände sind vollgespritzt! Ich habe es so satt!}

{209}{}{Insgesamt blüht die Stadt auf und wird schöner und sauberer. Ich hätte nie gedacht, dass ich das noch erleben würde. Die Karawanen kommen häufiger, die Leute ziehen hierher. Salt Lake wird zu einem echt coolen Ort.}
{210}{}{Insgesamt geht die Stadt zugrunde. Die Leute ziehen weg, die Karawanen kommen seltener. Einfach beschissen. Und ich kann mich noch glücklich schätzen, denn wenigstens habe ich Arbeit.}
{211}{}{Insgesamt ist die Lage in der Stadt wie zuvor – nicht gut. Ein langweiliger, verschlafener Ort. Es gibt bessere.}
