{100}{}{Du siehst einen Karawanenhändler.}
{101}{}{Du siehst einen gerissenen Karawanenhändler. Sein Gesicht bringt sein Motto klar zum Ausdruck: „Ich kenne den Preis von allem.“}
{102}{}{Hi.}
{103}{}{Wenn du einen Gegenstand zu deinem eigenen Vorteil stiehlst, wirkt sich das negativ auf dein Karma aus.}
{104}{}{Frecher Betrüger!}

{110}{}{Was willst du?}
{111}{}{Man munkelt, du hast einen Encoder, den eine Nuka-Cola-Fabrik braucht.}
{112}{}{Nichts.}

{113}{}{Hab einen. Ich verkauf ihn dir für 1000 $.}
{114}{}{Aber die Fabrik hat 300 $ ausgehandelt.}
{115}{}{Gegen so einen Preis habe ich nichts einzuwenden. Ich bezahle einfach und bringe den Encoder zur Fabrik.}
{116}{}{Ich rate dir, dich mir gegenüber nicht so stur zu stellen. Sonst könnte das böse enden.}
{117}{}{Und ich kaufe ihn nicht. Tschüss.}
{118}{}{Es ist mir egal, was die Fabrik will. Das Ding gehört mir, ich bestimme den Preis. Und die Fabrik sollte froh sein, wenn ich nächste Woche nicht noch fünfhundert draufschlage.}
{119}{}{Willst du mich etwa bedrohen? Ha-ha, das wird nicht funktionieren. }
{120}{}{Ich verstehe, aber du solltest zum ursprünglichen Preis zurückkehren, wenn du deine Chance auf Gewinn nicht verlieren willst.}
{121}{}{Ach ja? Nenn mir einen einzigen Grund, warum ich den Preis für die riesige Fabrik mit ihren riesigen Einnahmen senken sollte.}
{122}{}{Ich bin schon lange im Karawanengeschäft in Nevada. Ich habe viel erlebt. Willst du dieses Risiko wirklich eingehen? Dann bitte, verkauf ihn nicht. Ich bin nur hier, um dich als Karawanenhändlerkollege freundschaftlich zu warnen.}
{123}{}{Hmm ... Da ist was dran. Ich wollte mehr Geld aus ihnen herausholen, aber je länger ich das Ding behalte, desto schneller finden sie Ersatz ... Na gut, du hast mich wieder zur Vernunft gebracht. Ich bin einverstanden, zum ursprünglichen Preis von 300 $ zurückzukehren.}
{124}{}{Ich durchschaue Leute wie dich. Ich habe mehr Erfahrung.}
{125}{}{Hier sind deine 300 $ und gib mir den Encoder.}
{126}{}{Gut, aber ich habe kein Geld, um zu bezahlen. Ich komme später mit Bargeld wieder.}
{127}{}{Gute Entscheidung. Hast du 1000 $?}
{128}{}{Nimm das Geld und gib mir den Encoder.}
{129}{}{Ich bin mir immer noch nicht sicher, ob ich das Richtige tue. Versteh mich nicht falsch – es geht nicht nur um mich, sondern auch um meine Jungs. Wir müssen hart arbeiten, um uns zu ernähren. Aber reden wir nicht darüber.}
{130}{}{Tschüss.}
{131}{}{Genau darauf hatte ich gehofft! Und ich zweifle nicht einmal daran, dass es richtig war, den Preis nach Vertragsabschluss in die Höhe zu treiben. Versteh mich nicht falsch – es geht nicht nur um mich, sondern auch um meine Jungs. Wir müssen hart arbeiten, um uns zu ernähren. Aber reden wir nicht darüber.}
{132}{}{Na dann, tschüss.}