{100}{}{Du siehst Chip.}
{101}{}{Du siehst einen ungepflegten Bettler, der dich mustert.}
{102}{}{*Er macht eine eindringliche Geste, damit du zu ihm kommst*}
{103}{}{Hier können wir uns nicht unterhalten.}

#Ïåğâûé äèàëîã
{110}{}{Hey, psst! Junge, komm her, wir müssen reden.}
{111}{}{Hey, psst! Schrubber, komm her, wir müssen reden.}
{112}{}{Hey, psst! Cowboy, komm her, wir müssen reden.}
{113}{}{Hey, psst! Hübscher, komm her, wir müssen reden.}

{1110}{}{Hey, psst! Schlampe, komm her, wir müssen reden.}
{1111}{}{Hey, psst! Mama, komm her, wir müssen reden.}
{1112}{}{Hey, psst! Muchacha, komm her, wir müssen reden.}
{1113}{}{Hey, psst! Süße, komm her, wir müssen reden.}

{120}{}{Nicht mit so einem heruntergekommenen Säufer wie dir.}
{121}{}{Wenn es um ein Geschäft geht, warum nicht.}
{122}{}{Das ist deine Sache, ich wage nicht, darauf zu bestehen. Aber an deiner Stelle würde ich mir das anhören.}
{123}{}{Ja, ist mir egal. Ich will mich nicht mit dir unterhalten. Verzieh dich auf den Schrottplatz, du Abschaum!}
{124}{}{Vielleicht später. Jetzt muss ich mich um wichtige Angelegenheiten kümmern.}
{125}{}{Ja, ein Geschäft. Und ich würde sagen, dass unser Geschäft von gemeinsamem Interesse ist, he-he.}
{126}{}{Was meinst du?}
{127}{}{Du hast es beim ersten Mal nicht verstanden? Verzieh dich, Dreckskerl!}
{128}{}{Wenn ich es mir anders überlege, komme ich zurück und dann setzen wir das Gespräch fort. Aber jetzt muss ich los.}
{129}{}{Du hast es dir anders überlegt? Schlau.}
{1129}{}{Du hast es dir anders überlegt? Schlau.}
{130}{}{Kommt ganz darauf an, worüber du mit mir reden willst.}
{131}{}{Nein, du sahst nur aus wie irgendein Bettler, nicht wie der, den ich brauche.}
{132}{}{Na, das ist doch der Biker, nach dem du gesucht hast, oder?}
{133}{}{Ein Biker? Moment mal, woher ... Okay, du weißt also etwas.}
{134}{}{Jep. Aber das ist ein vertrauliches Gespräch. Weißt du, wo der einäugige Ausgestoßene Stapleton wohnt? In den Slums im Osten, direkt gegenüber vom artesischen Turm. Wir treffen uns dort. Und vergiss nicht, mir etwas zu essen und Kleingeld mitzubringen. Mit vollem Magen redet es sich besser.}
{135}{}{[Still beobachten, wie der Bettler davongeht.]}