{100}{}{Du siehst einen Mechaniker.}
{101}{}{Du siehst Francis, den Mechaniker.}
{102}{}{Vor dir steht der Mechaniker der Nuka-Cola-Fabrik.}

{104}{}{Lass mich in Ruhe!}
{105}{}{Ja, Baby! Kein Wunder, dass ich der beste Mechaniker in der Fabrik bin!}
{106}{}{Der Techniker konnte den Bordcomputer wiederherstellen.}

################################################################
#
# The starting dialogue thread
#
################################################################

{110}{}{Ein neues Gesicht? Dich habe ich hier noch nie gesehen. Na ja, hier kommen so viele Leute vorbei, dass man sich nicht alle merken kann. Was willst du?}
{111}{}{Zuerst würde ich gern wissen, wer du bist.}
{112}{}{Sag schon, was ist?}
{113}{}{Ich heiße Francis. Ich bin Mechaniker, und hier fällt alles in meinen Aufgabenbereich ... ich meine, in der Nuka-Cola-Fabrik. Und du musst mich nicht siezen, ich bin ein einfacher Mann.}
{114}{}{Du musst ein ziemlich fähiger Fachmann sein. Vielleicht habe ich ein paar Fragen.}
{115}{}{Das wollte ich nur wissen. Tschüss.}

{118}{}{Na, na. Warst du nicht derjenige, den man hier gesehen hat, als mein Schweißgerät verschwunden ist? Ich will niemanden ohne Beweise beschuldigen, aber ... [Er deutet auf eines seiner Augen und kneift das andere zusammen.] Von jetzt an wird dieses Auge jeden Schritt jedes Besuchers im Raum verfolgen. Merk dir das.}
{119}{}{Äh ...}

#Rejects to repair weapons
{120}{}{Kannst du meine Waffen verbessern?}
{121}{}{[Mit den Armen wedelnd] Nein, nein und nochmals nein! Mit Waffen habe ich nichts zu tun und will damit auch nichts zu tun haben! Das ist ein riskantes Geschäft.}
{122}{}{Na gut, dann reden wir über etwas anderes.}
{123}{}{Dann hast du einen Kunden verloren. Tschüss.}

#Vault-Tec devices for the Vault City warehouse
{125}{}{Kennst du dich mit etwas aus dieser Liste der Vault-Tec-Technologien aus?}
{126}{}{Vault-Tec, sagst du? Lass mich mal sehen ... Ich schätze, das alles hat mit der Technologie der Vaults zu tun, die die Firma Vault-Tec vor dem Krieg gebaut hat. Aber in Salt Lake gibt es nur einen solchen Vault, tief in den Bergen, und er ist noch immer verschlossen. Aber dort musst du nicht suchen. Ich bin auch schon auf Gassensoren in Familienschutzräumen gestoßen, die von der Preiser Incorporated gebaut wurden.}
{127}{}{Preiser ... Was?}
{128}{}{Na ja, weißt du, vor dem Krieg gab es noch eine andere Firma, die Vaults für diese Stadt baute. Die waren aber nicht so groß, eher für Familien gedacht, für ein paar Leute. Im Gebiet von Salt Lake gab es zweihundert oder vielleicht noch mehr, aber fast alle wurden geplündert oder überflutet. In den 60 Jahren seit dem Krieg ist dort jedoch kaum etwas außer Ratten und Feuchtigkeit übrig geblieben. Trotzdem kann man dort noch einige Technologien finden. Ich erinnere mich, dass manche das Logo von Vault-Tec trugen. Vielleicht vergab die Firma Aufträge für Technologien, die sie nicht selbst entwickeln konnte.}
{129}{}{Alles klar.}

################################################################
#
# Artesian water filter
#
################################################################

{130}{}{Ich frage mich, warum der artesische Wasserturm nicht funktioniert. Braucht die Stadt kein sauberes Wasser?}
{131}{}{Du bist nicht der Einzige, der sich das fragt. Aber leider gibt es ein Problem mit einem Teil, den niemand finden kann: dem Wasserfilter. Ohne ihn verstopft die Turbine mit Sand und bleibt schließlich stehen. Die Fabrik hat schon versucht, ihn über Karawanen zu bestellen. Inzwischen kennt wahrscheinlich jeder in Nevada das Problem, aber noch niemand hat das richtige Teil gefunden.}
{132}{}{Also muss man einfach nur dieses Teil finden?}
{133}{}{Einfach? Nun, nicht ganz. Selbst wenn es jemand findet, könnte in der Stadt ein Streit ausbrechen, der an einen Bürgerkrieg grenzt, um das Recht, den Turm zu besitzen. Wir alle brauchen sauberes Wasser: die Fabrik Nuka-Cola, die Stadtverwaltung, die Bevölkerung, die Reichen vor Ort. Und jeder wird seine eigenen Ziele verfolgen. Das Problem ist also größer, als nur irgendein Teil zu finden. Sprich mit meinem Chef, Direktor Skinner, darüber.}
{134}{}{Na gut, danke für die Erklärung.}
{135}{}{Du warst nicht gerade hilfreich, aber trotzdem danke.}

################################################################
#
# Reloading Press for ammunition
#
################################################################

#The question about the possibility of creating
{150}{}{Kannst du eine Presse zur Munitionsherstellung bauen?}
{151}{}{Hm, dieses Ding herzustellen, würde ziemlich viel Zeit in Anspruch nehmen. Vielleicht würde ich es machen, aber nur gegen eine sehr gute Bezahlung. Sagen wir 10.000 Bucks.}
{152}{}{Ich zahle 5.000 als Anzahlung und den Rest, wenn die Presse fertig ist. Einverstanden?}
{153}{}{Das ist zu teuer!}
{154}{}{Ich komme vorerst auch ohne Presse zurecht.}
{155}{}{Na ja, so kommen wir nicht weiter.}

{156}{}{Das ist fair. Aber es wird eine Woche dauern, du musst also warten.}
{157}{}{Einverstanden. Hier ist die Anzahlung.}

{158}{}{Was?! Bei so einem zeitaufwendigen Auftrag gebe ich keinen Rabatt!}
{159}{}{Verstehe ...}

{160}{}{Also gut! Komm in einer Woche mit dem Rest des Geldes wieder.}
{161}{}{In Ordnung.}

#After the creation
{170}{}{Bist du fertig? Mit meiner Presse zur Munitionsherstellung??}

{171}{}{Natürlich, wie versprochen. Aber erst mal her mit den Bucks!}
{172}{}{Der Restbetrag, 5.000 $, wie vereinbart.}
{173}{}{Warte, ich hole das Geld.}
{174}{}{Findest du nicht, dass 10.000 zu viel sind? Was, wenn ich ablehne?}

{175}{}{Na ja, wenn man bedenkt, was du für die Stadt getan hast, warum nicht? Aus Respekt gebe ich dir 500 Bucks Rabatt.}
{176}{}{Oh, mit deinen anderen Aufträgen habe ich viele Möglichkeiten, Gewinn zu machen. Du bekommst deinen Rabatt: 500 Bucks weniger.}
{177}{}{Die Verbindung zu einem so schlauen Händler wie dir wird mir in Zukunft gute Gewinne einbringen. Ich gebe dir 500 $ Rabatt, einverstanden?}
{178}{}{Der Preis ist in Ordnung. Und du bist keiner dieser Salt Lake Stadtbewohner, denen ich einen Rabatt geben würde.}
{179}{}{Danke, das macht 4.500 $.}
{180}{}{Schade. Dann sind hier 5.000 $, wie vereinbart.}

################################################################
#
# Armor
#
################################################################

#Armor upgrades:
{200}{}{Kannst du meine Rüstung verbessern?}

{201}{}{Oh, in dem Bereich bin ich ein echter Tausendsassa! Sehr gern. Was für eine ist es diesmal?}
{202}{}{}
{203}{}{Metallrüstung.}
{204}{}{Lederrüstung.}
{205}{}{Lederjacke.}

{209}{}{Heute nichts Besonderes.}

#Leather jacket:
{210}{}{Als Rüstung taugt sie nicht viel, aber ich kann Panzerplatten anbringen, um den Schutz vor mechanischem Schaden zu verbessern. Der einzige Nachteil ist, dass du dann nicht mehr so schnell laufen kannst.}
{211}{}{Klar. Wenn du mir die Jacke bringst.}
{212}{}{Schon gut.}

{213}{}{}
{214}{}{[Panzerplatten anbringen]}
{215}{}{Nichts.}

{216}{}{Das kostet dich }
{217}{}{ Dollar.}
{218}{}{Hier ist das Geld und eine verstärkte Lederjacke.}
{219}{}{Hier ist das Geld und eine normale Lederjacke.}

#Leather armor
{230}{}{Eine gute Wahl für unerfahrene Reisende. So eine Rüstung wird oft von Karawanenleuten verlangt. Ich kann ihr ein paar zusätzliche Schutzstufen verpassen. Die Rüstung schützt dann besser vor Schaden.}
{231}{}{[Schutz verstärken]}
{232}{}{Klar. Wenn du mir die Rüstung bringst.}
{233}{}{Hier ist das Geld und die Lederrüstung.}

#Metal armor
{240}{}{Ja, ich habe auch schon mit so einer Rüstung gearbeitet. Ich kann ein paar abgenutzte Platten ersetzen und sie polieren. Sieht dann fast aus wie neu!}
{241}{}{[Metallrüstung verstärken]}
{242}{}{[M2 zusätzlich verstärken]}
{243}{}{[M2 verspiegeln]}

{244}{}{Hier ist das Geld und die Metallrüstung.}
{245}{}{Hier ist das Geld und die Metallrüstung M2.}
{246}{}{Hier ist das Geld und die Metallrüstung M2 mit verspiegelter Oberfläche.}
{247}{}{Hier ist das Geld und die verstärkte Metallrüstung M2.}

#The end
{290}{}{[Nach der langen Arbeit bringt der Meister den fertigen Gegenstand und nickt sich zustimmend zu.] Gute Arbeit.}
{291}{}{Nun, sie muss nur noch einem Praxistest unterzogen werden.}
{292}{}{Bist du sicher? Zähl genau nach ...}
{293}{}{Fehlt etwas? ...}

{294}{}{Zieh deine Rüstung aus.}
{295}{}{Oh, natürlich ...}

################################################################
#
# Tokens for Cola vending machines
#
################################################################

#Questions - tokens to cheat with Cola machines:
{300}{}{Man sagt, du kannst runde Metallplatten prägen?}
{301}{}{Klar. Welchen Durchmesser?}
{302}{}{Wie eine normale Münze.}
{303}{}{Ganz einfach, wie ein Kinderspiel... Moment mal! Du findest das lustig, du Schlaumeier!? Wenn ich dich dabei erwische, zahlst du dafür! Skinner hat sogar ein Kopfgeld auf Diebe wie dich ausgesetzt ...}
{304}{}{Hey, ganz ruhig! Ich habe noch nichts falsch gemacht!}
{305}{}{Noch nicht! Da hast du Glück. Sonst hätten Skinner, der Sheriff und ich dich sofort erledigt! Und spar dir diesen unschuldigen Blick! Ich weiß, wohin die Chips gehen. Dann nehmen die Techniker in der Fabrik den ganzen Kram aus den Maschinen, und der Chef fragt mich aus, wann und für wen ich sie hergestellt habe. Ich habe genug! Bei solchen „Aufträgen“ mache ich nicht mehr mit.}
{306}{}{Äh, na gut, wie du meinst, Alter ...}

################################################################
#
# Factory quest on PLC
#
################################################################

{310}{}{Der Direktor hat mir den Auftrag gegeben, etwas namens PLC zu reparieren.}
{311}{}{Ach ja, man hat mich informiert. Hier, nimm das. Das Ding ist ziemlich kompliziert. Keiner von uns kann gut programmieren, und genau diese Erfahrung braucht man dafür.}
{312}{}{Wie soll ich das reparieren?}
{313}{}{Na ja, du solltest das besser wissen. Schließlich wirst du dafür bezahlt, heh. Aber eigentlich gibt es mehrere Möglichkeiten. Die erste ist ein Techniker in Las Vegas, von dem uns die Karawanenleute erzählt haben. Dann wären da noch die Biker. Die Jungs sind verrückt nach alter Technik. Und wenn du selbst die nötigen Fähigkeiten hast, gehört dir die ganze Bezahlung. Die Werkbank steht in dem Gebäude vor dem Büro.}
{314}{}{Erzähl mir mehr über dieses Gerät. Was macht es?}
{315}{}{Wer ist der Techniker in Vegas?}
{316}{}{Biker. Wie kann ich sie kontaktieren?}
{317}{}{Okay, ich mach mich an die Arbeit.}
{318}{}{Großartig. Warte, noch etwas: Erzähl den Einheimischen nichts von der Steuerung. Es gibt Leute in Salt Lake City, die besser nicht wissen sollten, dass wir automatische Systeme wiederherstellen.}
{319}{}{Warum?}
{320}{}{Na ja, wenn du ein lebendes Ziel werden willst, nur zu. Aber neben denen, die einfach nur einen lukrativen Auftrag wollen, gibt es auch Leute wie unseren Apotheker, die glauben, dass eine Reparatur der Fabrik die ohnehin beschissene Umweltsituation in der Stadt noch verschlimmern würde. Ach ja, und die Leute in der Fabrik wären nicht mehr so gefragt wie früher – zumindest bräuchte man nicht mehr so viele –, weil die Roboter ihre Arbeit übernehmen würden. Verstehst du, wie heikel das ist? Dann halt den Mund, wenn du dir die Gelegenheit, etwas Geld zu verdienen, nicht verderben willst.}
{321}{}{Alles klar.}
{322}{}{Die speicherprogrammierbare Steuerung. Sie ist für die automatische Steuerung verschiedener Geräte nötig. Stell dir vor, wir könnten alle Förderbänder, Antriebe, Manipulatoren, Sensoren und Ladekräne daran anschließen – alles, was wir für den autonomen Betrieb der Fabrik brauchen. Die Leute müssten nur zwischen den Maschinen umhergehen, sie steuern und überwachen, damit es nicht zu Unfällen kommt.}
{323}{}{Die Karawanenhändler haben mir erzählt, dass es in Vegas beim Hoover Dam einen Typen mit außergewöhnlichem Talent für Elektronik gibt. Wenn das stimmt, kann nur er die Steuerung reparieren.}
{324}{}{Keine Ahnung. Sie sagen dir normalerweise nicht, wann sie in die Stadt fahren. Ihre Basis ist anderswo. Natürlich muss der Sheriff Bescheid wissen; er würde alles über solche Leute herausfinden, was er kann.}
{325}{}{Erzähl mir noch mal etwas über die SPS.}
{326}{}{Ich habe die Steuerung reparieren können.}
{327}{}{Wirklich? [Er führt einige Tests durch] Sie funktioniert tatsächlich! Wunderbar. Bring sie jetzt zu Direktor Skinner.}
{328}{}{Alles klar.}
{329}{}{Aber heißt das nicht, dass ein Teil der Belegschaft dann nicht mehr gebraucht wird?}
{330}{}{Du klingst wie dieser altkluge Apotheker. Natürlich kann der Direktor ein paar Faulpelze entlassen. Aber das ist nicht mal die Hälfte! Auch automatisierte Maschinen müssen überwacht und gewartet werden. Und dafür braucht man Menschen. Heutzutage kann man der Technik nicht wirklich trauen.}

################################################################
#
# Train
#
################################################################

{350}{}{Ich muss diesen Computer reparieren. Machst du das?}

{351}{}{[Als Francis das Gerät sieht, bleibt er stehen und mustert dich eine Weile schweigend.] Was ist das? Der Computer aus dem Zug, stimmt's? Na gut, ich sag's dir, wie's ist. Die Einheimischen, mich eingeschlossen, haben schreckliche Angst vor dem Bahnbetriebswerk. Der Sheriff, die Mormonen, der Geisterzug, die Wartungsroboter ... Ich habe genug Gründe, nicht daran denken zu wollen. Meine Haut ist mir wichtiger als jedes Geld.}
{352}{}{Was sagt der Sheriff?}
{353}{}{Die Mormonen? Was haben die damit zu tun?}
{354}{}{Ein Geisterzug? Was ist das für ein Märchen?}
{355}{}{Roboter? Am Bahnhof?}
{356}{}{Schon gut, vergiss mein Angebot. Ich komme auch ohne dich klar.}

{357}{}{Der Sheriff hat uns verboten, dorthin zu gehen. Er sagt, es sei sehr gefährlich. Und das nicht ohne Grund. Von Zeit zu Zeit gibt es neue Gerüchte über mutige Männer, die dorthin gingen und nicht zurückkamen. Ich weiß nicht, was dort vor sich geht, und ich will es auch nicht wissen.}
{358}{}{Der Sheriff hat sie mit der Überwachung des gefährlichen Gebiets beauftragt. Frag am besten sie selbst. Sie wohnen im Norden, nahe dem zerstörten Teil der Stadt.}
{359}{}{Ein Märchen!? Du nennst das ein Märchen?! Da waren ein paar Mutige, die versucht haben, auf dem Zug zu reiten, wie beim Rodeo, weißt du. Und was hat's gebracht? Wer seinen schwarzen Körper berührt, wird sofort zu Asche gegrillt! Das ist kein Märchen. Obwohl es nur sehr wenige gibt, die ihn tatsächlich gesehen haben ... Und ich gehöre ganz sicher nicht dazu.}
{360}{}{Wartungsroboter. Sie reparieren seit der Zeit vor dem Krieg die Straße und den Bahnhof. Es ist schwer zu sagen, wer oder was sie steuert, aber sie arbeiten zusammen. Wer versucht hat, sich ihnen in den Weg zu stellen oder in die Gefahrenzone zu gehen, bekam eine Portion Plasma in den Arsch. Sie sind also eine echte Tatsache, realer als jeder Geisterzug.}

{361}{}{Du scheinst mir nicht zu vertrauen, Francis. Warum?}
{362}{}{Was hast du getan, um dir mein Vertrauen zu verdienen? Ich kann mich nicht erinnern, dass du in der Stadt einen besonders glaubwürdigen Ruf hättest. Also, wenn du das Gerät reparieren willst, geh woanders hin.}
{363}{}{Nein, nein, es geht nicht um dich. Die Leute sagen Gutes über dich, manche behaupten sogar, du seist ein Held. Aber ich habe Angst vor den Mormonen und dem Sheriff.}
{364}{}{Das solltest du nicht denken. Ich habe die richtigen Beziehungen, um uns beide zu schützen. Also, hilfst du mir?}
{365}{}{Nein, warte, setz mich nicht unter Druck, lass mich nachdenken ... Du kannst das natürlich organisieren, aber warum sollte ich mich solchen Risiken aussetzen? Hier mein Vorschlag: Bring mir 1.000 Dollar, dann versuchen wir, das Problem diskret zu lösen.}
{366}{}{Hier sind das Geld und der Computer. Fang an, ich brauche die Ergebnisse so schnell wie möglich.}
{367}{}{Na, du weißt, wie man Vertrauen gewinnt. Hier, nimm das und lass dich von niemandem sehen. Ich will keine Probleme am Hals haben.}
{368}{}{In Ordnung.}

################################################################
#
# The car
#
################################################################

{400}{}{Würdest du's glauben? Ich habe mein eigenes Auto! Bist du neidisch?}
{401}{}{Also, welche Verbesserungen kannst du an meinem Pickup vornehmen?}

{402}{}{[Schnaubt überheblich] Na klar. Und ich habe meine eigene Cola-Fabrik ... Moment, das ist kein Scherz!? Unglaublich! Lass mich mal sehen, nur einen Blick! So etwas Seltenes findet man heutzutage ...}
{403}{}{Selten? Hey, Moment mal! Bin ich also nicht der Einzige mit Rädern?!}
{404}{}{Natürlich nicht! Früher war die Stadt ein Industriezentrum, hier gibt es viele funktionstüchtige Maschinen, aber wegen des Klimas und der Bombardierung des nördlichen Teils ist alles verfallen. Ab und zu findet jemand Autos in alten Garagen, bringt sie wieder zum Laufen und ...}
{405}{}{Und?!}
{406}{}{Und nichts. Heutzutage ist es eine echte Herausforderung, brauchbare Reifen zu finden. Nach einem halben Jahrhundert sind sie verrottet. Aber das Hauptproblem sind all diese Arten von Chips und Reglern. Schon vor dem Krieg waren sie schwer zu finden, und jetzt ist es fast unmöglich.}
{407}{}{Und wie viele von diesen Glückspilzen gibt es in Salt Lake City?!}
{408}{}{Mal sehen ... Hm ... In den letzten zwanzig Jahren habe ich etwa ein Dutzend funktionstüchtige Autos gesehen, außerdem die Motorräder, auf denen die Biker herumfahren. Aber wir haben auch andere selbstfahrende Maschinen. Zum Beispiel die Autos in der Fabrik.}
{409}{}{Ich sehe, du hast Erfahrung im Umgang mit Fahrzeugen. Kannst du also etwas mit meinem Baby anfangen?}
{410}{}{Würde ich liebend gern, lass mich nur ihre Flanken berühren!}
{411}{}{Gehen wir, ich zeig sie dir.}
{412}{}{Du solltest warten, bis ich sie zum Eingang gefahren habe.}

{413}{}{Oh mein Gott! [Er packt sich an den Kopf] Das ultimative Meisterwerk von "Chryslus motors"! Der geländegängigste Wagen, von dem ich je gehört habe! Verdammt, jetzt bin ich wirklich neidisch.}
{414}{}{Ja! Wie ich schon sagte!}
{415}{}{Natürlich sollte man heutzutage froh sein, wenn man überhaupt ein funktionstüchtiges Auto besitzt, aber selbst an so einem Fahrzeug gibt es ein paar Mängel, die man beheben könnte.}

{416}{}{Mängel? Aha! Offenbar hast du beschlossen, an mir etwas zu verdienen!}
{417}{}{Ich bin neugierig. Was schlägst du vor?}
{418}{}{Jemanden an meinem Auto herumpfuschen lassen? Finger weg! Das ist mein Auto!}

{419}{}{Natürlich, natürlich! Wie du meinst. War nur ein Angebot.}
{420}{}{Was willst du mir anbieten?}
{421}{}{Ich bin immer noch nicht an dem interessiert, was du mir anbieten wolltest. Ich gehe.}

{422}{}{Nun, obwohl ich ein Fan von technischen Spielereien bin, habe ich noch nicht gelernt, sie zu Mittag zu essen ...}
{423}{}{Also, was ist dein Angebot?}
{424}{}{}

{425}{}{Eine äußerst praktische Lösung: Zuerst entfernen wir überflüssiges Metall, um das Gewicht des Wagens zu verringern, dann bauen wir über dem Kofferraum einen neuen, stabilen Rahmen. Ich habe alles, was ich dafür brauche.}
{426}{}{Die Kapazität des Kofferraums erhöhen? Das wäre großartig. Wie viel würde mich das kosten?}
{427}{}{Nun, das interessiert mich nicht. Ich komme wieder, wenn ich es mir anders überlege.}

{428}{}{Und dieses stinkende Zelt - oh Mann, wie eklig! Werfen wir es auf den Muell!}

{430}{}{Zusammen mit der Gebühr für meine Arbeit macht das etwa }
{431}{}{ Dollar.}

{432}{}{Der Preis ist in Ordnung. Hier ist das Geld. Also, legen wir los!}
{433}{}{Gib mir Zeit zum Nachdenken. Falls ich eine günstigere Lösung finde ...}

{434}{}{Francis hat den Kofferraum deines Pick-ups verbessert. Jetzt kannst du dort 20% mehr Sachen unterbringen.}
{435}{}{Francis hat den Kofferraum deines Pick-ups verbessert. Jetzt kannst du dort 40% mehr Sachen unterbringen.}

{436}{}{Nun, dann fahr zum Eingang der Fabrik, und ich fange an zu arbeiten.}
{437}{}{Ich hole den Wagen.}

################################################################
#
# Power armor
#
################################################################

{500}{}{Was ist das für ein Kram auf deinem Schreibtisch?}
{501}{}{Oh, ein verdammter Haufen Polymere, Metalle und Keramik, mit dem ich seit Monaten nichts anfangen kann ... Warum fragst du?}
{502}{}{Das sieht aus wie Teile eines Roboters ...}
{503}{}{Irgendwie ist es ein Roboter. Tatsächlich siehst du hier den Ruhm der ehemaligen amerikanischen Armee - den T-51b-Kraftanzug. Oder besser gesagt, das, was davon übrig ist. Er wurde im Norden gefunden, in den Ruinen des bombardierten Stadtteils. Irgendetwas ließ das interne Energiemodul zerfallen, wodurch fast die gesamte Rüstung in die Luft flog. Nur wenig davon war noch funktionsfähig.}
{504}{}{Kann man ihn reparieren?}

{505}{}{Wenn jemand passende Ersatzteile und die Originalbaupläne findet - natürlich. Aber die zu finden, ist nahezu unmöglich.}
{506}{}{Hypothetisch gesehen - wo bekomme ich die nötigen Teile her?}
{507}{}{Was genau muss ersetzt werden?}
{508}{}{Ich möchte die Rüstung in funktionsfähigem Zustand kaufen.}

{509}{}{Wegen der Powerrüstung. Kann man sie noch reparieren?}
{510}{}{Wegen der Powerrüstung.}
{511}{}{Wir reden später weiter darüber.}

{512}{}{Hm, ich schätze, auf Militärbasen. Wo sonst? Aber ich kenne sie nur vom Hörensagen. Außer einer im Norden, die allerdings durch einen direkten Treffer einer Atombombe zerstört wurde.}
{513}{}{Mal sehen ... Zuerst brauchen wir Baupläne. Dann müssen wir einige Teile ersetzen ... genau gesagt die CPU, das Energiemodul und einen neuen Helm. Außerdem müssen wir irgendwo etwas finden, womit wir den Strahlen- und Gasschutz wiederherstellen können.}
{514}{}{Jetzt will ich sie noch mehr! Also, abgemacht: Du besorgst die Teile, ich repariere die Rüstung und überlasse sie dir. Natürlich hätte ich dafür gern etwas im Gegenzug.}
{515}{}{Abgemacht!}
{516}{}{Ich überleg's mir.}

{517}{}{Gut. Ich brauche die Baupläne. Ich weiß nicht, wo man sie herbekommt, aber ich weiß, dass einer der Biker aus dem Westen eine *funktionierende* Powerrüstung besitzt. Vielleicht kann er dir die Informationen geben. Ich habe allerdings keine Ahnung, wo diese Biker leben. Aber der Sheriff weiß es ganz sicher.}
{518}{}{Biker? Wie interessant.}

{519}{}{Oh, genau das habe ich gebraucht! Die beschädigten Bereiche der gepanzerten Huelle wiederaufzubauen, wird eine Menge Arbeit machen. Aber dank der Baupläne wird es jetzt viel einfacher. Das ist ein großartiger Fund! Schade, dass sie nur für den äußeren Wiederaufbau nützlich sind.}

{520}{}{Was genau?}
{521}{}{Besprechen wir die erste Phase der Reparatur. Was muss gemacht werden?}
{522}{}{Nichts.}
{523}{}{Besprechen wir die zweite Phase der Reparatur.}
{524}{}{Besprechen wir die dritte Phase der Reparatur.}

{525}{}{Gern geschehen! Zuerst muss die Rüstungshülle wiederhergestellt werden. Das ist nicht einfach. Für die Konstruktion wurden hochwertige Polymere, Cermets und spezielle Befestigungselemente verwendet. Ich brauche Baupläne, um zu sehen, wie alles vorher zusammengesetzt war. Mit den Materialien sieht es schlecht aus, aber es ist trotzdem möglich, welche zu finden.}
{526}{}{Ich habe eine kaputte Powerrüstung. Reicht es, die Huelle wiederherzustellen?}
{527}{}{Ich habe Baupläne für das Rahmengestell!}
{528}{}{Wo kann ich sie finden?}
{529}{}{Die Baupläne also ... Verstanden. Ich suche schon danach.}

{530}{}{Wenn ich das gewusst hätte, hätte ich diesen Schrotthaufen schon vor langer Zeit repariert. Aber hier ein Vorschlag: Manchmal kommen Biker aus dem Westen her. Einer von ihnen trägt eine Powerrüstung. Vielleicht könnte er ein paar Informationen mit uns teilen.}
{531}{}{Verstehe. Dann such weiter.}

{532}{}{Oh, genau das habe ich gebraucht! Ich kann die Rüstung nicht nur als Grundlage verwenden, sondern auch die fehlenden Teile der Panzerung daraus entnehmen. Ein großartiger Fund! Schade, dass sie nur für die äußere Rekonstruktion taugt.}
{533}{}{Mach vorerst wenigstens das.}

{534}{}{Fertig! Sieht spektakulär aus, oder? Natürlich ist es immer noch nur ein Haufen Metall. Ohne das Energiemodul braucht man gar nicht erst zu versuchen, sie anzuziehen – sie ist zu schwer. Lass sie vorerst auf dem Tisch liegen, sie läuft nicht weg.}
{535}{}{Sehr gut. Was kommt als Nächstes?}
{536}{}{Großartig. Wir machen ein andermal weiter.}

{537}{}{Jetzt müssen wir die Dichtigkeit der Huelle wiederherstellen. Die Strahlenschutz- und Gasschutzschichten sind durchgebrannt, und der Helm ist völlig zerlegt. Wir müssen das alles durch irgendwelche Behelfslösungen ersetzen. Schreib es dir lieber auf, falls dein Gedächtnis dich im Stich lässt. Ich brauche: einen luftdichten Helm, einen Schutzanzug gegen Gas und einen Strahlenschutzanzug.}
{538}{}{Ich habe einen Strahlenschutzanzug.}
{539}{}{Ich habe einen Schutzanzug gegen Gas.}
{540}{}{Ich habe einen Laborhelm.}
{541}{}{ Wir haben bereits }
{542}{}{Strahlenschutz}
{543}{}{Gasschutz}
{544}{}{luftdichten Helm}
{545}{}{ und }
{546}{}{.}

{547}{}{Fertig! Wir sind wieder einen Schritt weiter!}
{548}{}{Das ist gut.}
{549}{}{Großartige Neuigkeiten! Die Huelle ist wiederhergestellt. Es wäre toll, mit einer Flasche "Bloody Mary" darauf anzustoßen, aber der schwierigste Teil der Arbeit liegt noch vor uns. Also sollten wir uns noch nicht zu früh freuen.}
{550}{}{Gut zu hören. Was muss noch gemacht werden?}
{551}{}{Großartig, aber machen wir später weiter.}
{552}{}{Am schwierigsten ist es, das autonome System wiederherzustellen. Diese Art von Rüstung zeichnet sich durch ein Kraftmodul aus, das dem Exoskelett Beweglichkeit verleiht und die Kraft des Trägers erhöht. Die Systeme wurden von einem internen Minireaktor betrieben und von einem Zentralprozessor gesteuert. All das ist zerstört. Wir müssen Ersatz finden, denn solche Dinge können wir nicht von Grund auf herstellen. Außerdem brauche ich Baupläne der inneren Struktur, sonst dauert die Analyse bei der Demontage Jahre. Schreib jetzt auf, was ich brauche: ein autonomes System, eine CPU und Baupläne.}
{553}{}{Ich habe die CPU.}
{554}{}{Ich habe ein autonomes System.}
{555}{}{Ich habe Baupläne der inneren Struktur der Rüstung.}
{556}{}{Ich habe eine kaputte Powerrüstung. Kann man die verwenden?}
{557}{}{Verstehe. Ich werde danach suchen.}

{558}{}{Oh ja, genau das brauche ich! Aber ich brauche auch noch Baupläne und ein autonomes System.}
{559}{}{Oh ja, genau das brauche ich! Aber ich brauche auch noch die Baupläne und die CPU.}
{560}{}{Oh ja, genau das brauche ich! Aber ich brauche auch noch ein autonomes System und die CPU.}
{561}{}{Oh ja, genau das brauche ich! Und in diesem Fall brauche ich nicht einmal die Baupläne.}

{562}{}{Ich habe alles, was du brauchst. Also sei bitte nicht faul – die letzte Phase steht noch bevor!}
{563}{}{Also, wir haben alles, was wir brauchen, um die Arbeit abzuschließen!}

{564}{}{Großartig! Ich bin bereit, mit der letzten Phase des Wiederaufbaus zu beginnen, aber es gibt da einen strittigen Punkt. Bisher habe ich kostenlos gearbeitet, während du nach den benötigten Teilen gesucht hast. Wem von uns gehört die Rüstung also jetzt? Gib zu: Wer sie bekommt, sollte den anderen für seine Mühen entschädigen.}
{565}{}{Wie hoch ist die Entschädigung für deine Dienste?}
{566}{}{Ich bringe dich einfach um und stelle die Rüstung selbst fertig.}
{567}{}{Gute Frage. Darüber muss ich nachdenken.}

{568}{}{Ich veranschlage meinen Arbeitsanteil auf 10.000 $. Wir könnten es aber auch andersherum machen – ich zahle dir 10.000 $ und behalte die Rüstung. Ich könnte sie für einen besseren Preis verkaufen.}
{569}{}{Das ist fair genug. Hier sind 10.000 $. Jetzt streng dich an und bring die Arbeit zu Ende!}
{570}{}{Diese Summe kann ich mir nicht leisten. Wir können ein andermal darüber reden.}

{571}{}{Nun, ich beneide dich fast, obwohl ich mit diesem Auftrag selbst eine Menge Spaß und Geld hatte. Solche Gelegenheiten findet man nicht an jeder Ecke, und so etwas wirst du wahrscheinlich nie wieder erleben ... Weißt du, wenn ich du wäre, würde ich der Rüstung einen Namen geben. Zum Beispiel „Grizzly“. Was meinst du? Ich finde, der passt gut.}
{572}{}{„Grizzly“-Powerrüstung? Das ist ein toller Name!}
{573}{}{Was für ein beschissener Name. Ihre Hauptaufgabe ist es, vor Kugeln zu schützen, alles andere ist unwichtig.}

{574}{}{Wie auch immer, das geht mich nichts an. Ich würde die Rüstung gern in Aktion sehen. Komm schon – zieh sie an!}
{575}{}{...}
{576}{}{Verdammt, sie funktioniert! Das ist ein Wunder!}

{577}{}{Dein Angebot gefällt mir – ich nehme das Geld und du die Rüstung.}
{578}{}{Mann, ich bin schon jetzt neidisch auf mich selbst! Ich freue mich darauf, richtig abzusahnen! Außerdem hatte ich noch nie so viel Spaß bei der Arbeit. Hm, weißt du, was ich denke? Wie wär's, wenn ich dieser Rüstung einen eigenen Namen gebe? Zum Beispiel „Grizzly“. Was meinst du? Ich finde, der passt gut.}
{579}{}{„Grizzly“-Powerrüstung? Das ist ein toller Name!}
{580}{}{Was für ein beschissener Name, Schlaumeier.}
{581}{}{Hm ... Wie auch immer – danke, Partner. Hoffentlich war das nicht unser letztes gemeinsames „Geschäft“. [Er lächelt und schüttelt dir die Hand] Viel Glück!}
{582}{}{Dir auch.}

#Womens replica
{1303}{}{Ganz einfach, wie ein Kinderspiel... Moment mal! Du findest das lustig, du Schlaumeier!? Wenn ich dich dabei erwische, zahlst du dafür! Skinner hat sogar ein Kopfgeld auf Diebe wie dich ausgesetzt ...}
{1304}{}{Hey, ganz ruhig! Ich habe noch nichts falsch gemacht!}
{1403}{}{Selten? Hey, Moment mal! Bin ich also nicht der Einzige mit Rädern?!}
{1414}{}{Ja! Wie ich schon sagte!}
{1564}{}{Großartig! Ich bin bereit, mit der letzten Phase des Wiederaufbaus zu beginnen, aber es gibt da einen strittigen Punkt. Bisher habe ich kostenlos gearbeitet, während du nach den benötigten Teilen gesucht hast. Wem von uns gehört die Rüstung also jetzt? Gib zu: Wer sie bekommt, sollte den anderen für seine Mühen entschädigen.}
{1566}{}{Ich bringe dich einfach um und stelle die Rüstung selbst fertig.}
