{100}{}{Du siehst einen Jungen.}
{101}{}{Du siehst einen einheimischen Jungen namens Robin.}
{102}{}{Einem Kind Drogen anzubieten, ist eine äußerst niederträchtige Tat. Deine Seele ist ein wenig dunkler geworden.}
{103}{}{Du bist ein gemeiner Mann! Du bist *sehr* böse!}
{104}{}{Du bist eine gemeine Frau! Du bist *sehr* böse!}
{105}{}{Lass mich in Ruhe! Ich versuche, das schwierigste Rätsel zu lösen!}

{106}{}{Du hast dem Kind das proportionale Rechnen beigebracht. Bravo!}
{107}{}{Die persönlichen Sachen eines Kindes zu stehlen, wirkt sich negativ auf dein Karma aus.}

{110}{}{[Der Junge denkt angestrengt über etwas nach und beachtet dich nicht]}
{111}{}{Hey! Was machst du da?}
{112}{}{[Lass ihn in Ruhe]}

{113}{}{[Der Junge zieht nervös die Schulter hoch und schenkt dir keine Beachtung]}
{114}{}{Hör mal, du kleiner Scheißer! Respektierst du etwa die Erwachsenen nicht?! Ich verprügle dich!}
{115}{}{[Schüttle ihn an der Schulter] Hallo, junger Mann, hörst du mich?...}

{116}{}{Äh! Tut mir leid! Ich war in Gedanken versunken! Ich hab ein Rätsel, bei dem mir der Kopf raucht.}
{117}{}{Ach ja? Vielleicht sollte ich dir den Schädel öffnen und mal nachsehen?}
{118}{}{Erzähl mir von dem Rätsel.}
{119}{}{Ein Rätsel? Interessiert mich nicht. Find's selbst raus.}

{120}{}{[Murmelt etwas] Wie schlau...}
{121}{}{Respektlos gegenüber Erwachsenen, du Rotzlöffel? Halt den Mund!}
{122}{}{Äh, na gut, ich geh dann mal.}

{123}{}{Schrei mich nicht an, du hast angefangen! Klar?! Und du bist in *meinem* Haus, also: Tschüss! [zeigt auf die Tür]}
{124}{}{Ach, du kleiner neunmalkluger Scheißer! Wo kommen in dieser postapokalyptischen Welt bloß solche kleinen Klugscheißer wie du her...}

{125}{}{Willst du es auch lösen?}
{126}{}{Ja, erzähl mir von dem Rätsel!}
{127}{}{Nein, Dummkopf, ich will beweisen, dass ich cooler bin als so ein kleiner Scheißer.}
{128}{}{Nein, will ich nicht. Tschüss.}

{129}{}{Na gut, hör zu. Ein Karawanenhändler kam durch drei Städte. In der ersten musste er ein Viertel des Werts seiner Waren dafür bezahlen, einen Stellplatz zu mieten. In der zweiten Stadt verlangte man ebenfalls ein Viertel von dem, was ihm noch geblieben war. In der dritten Stadt ein Viertel des Rests. Als er zu Hause ankam, hatte er nur noch 1.728 Bucks, aber er konnte nichts verkaufen. Wie viel hatte er also am Anfang?}
{130}{}{Aber das ist doch ganz einfach! Ich kann dir sofort die Antwort sagen.}
{131}{}{Was für ein dämliches Rätsel! Hat man dir nicht das Rechnen beigebracht? Sieht ganz so aus. Weißt du überhaupt, wie man läuft?}
{132}{}{Hm... Weißt du, im Moment interessiert mich das nicht, also schaue ich später noch mal vorbei. Tschüss!}

{133}{}{Ich wusste es - du kriegst es nicht hin...}

{134}{}{Wirklich!? Wie viel ist es denn?!}
{135}{}{4096}
{136}{}{3840}
{137}{}{3456}
{138}{}{3110}
{139}{}{3024}
{140}{}{Äh ... eigentlich weiß ich's nicht. Lösen wir es später ...}

{141}{}{[Es sieht so aus, als würde er dir nicht glauben] Was?! Nein! Das stimmt nicht! Es muss 3375 sein!!!}
{142}{}{Ist das so? Nein, Kleiner, du zählst falsch. Tut die Wahrheit weh? Verlierer!!!}
{143}{}{Bist du sicher? Na ja, du wirst es besser wissen. Ich lasse dich dann mal allein ...}
{144}{}{Hm, woher weißt du das?}
{145}{}{Du musst geschummelt haben! Bäh!}

{146}{}{Genau! Du kannst nicht mal selbst zählen, also halt den Mund! Ich schaff das auch ohne dich! Määäh! [Er zeigt dir die Zunge]}
{147}{}{Du kleiner Mistkerl, so respektlos zu Erwachsenen?! Ich bring dir Manieren bei, du Rotzlöffel!}
{148}{}{Na gut, tut mir leid. Ich wollte dich nicht aufregen. Löse dein Rätsel. Tschüss.}

{149}{}{[Der Junge rennt weg] Papa! Ein Fremder im Haus! Papa!}
{150}{}{Ha, Angsthase ...}

{151}{}{[Murmelt] Ha! Genau! Ich hab's endlich raus! Und schau mal - sogar besser als die Erwachsenen! Und ich hab's ihnen gesagt! Ich hab ihnen gesagt, dass ich das kann!}
{152}{}{Das kannst du, das kannst du. Tschüss.}

{153}{}{Das stimmt nicht! Das ist falsch! Karawanenhändler haben mir dieses Rätsel gegeben! Also ja, ich schaff das auch ohne dich! Pfffft! [Er zeigt dir die Zunge und spuckt]}
{154}{}{Dann mach's eben. Ich muss meine Leute retten. Bis dann.}

{155}{}{Also, ich dachte mir: Ein Viertel entspricht 0,25, richtig? Also muss man die Summe mit einem Viertel multiplizieren und den Rest addieren. Dann erhält man die zweite Zahl. Die multipliziert man ebenfalls mit einem Viertel und addiert sie wieder. Das ergibt 3375. Stimmt's??}
{156}{}{Nein, du hast einen Fehler gemacht. Du berechnest ein Viertel von einer kleineren Zahl, aber zuerst wird es von einer größeren Zahl berechnet. Da gibt es einen Unterschied, also rechne es mit dem Verhältnis aus.}
{157}{}{Nicht die geringste Ahnung! Vielleicht ist das zu schwierig für mich ...}
{158}{}{Du und dein winziges Gehirn kapieren das nicht. Wir reden weiter, wenn dir endlich Eier wachsen und du aufhörst, dich wie ein Mädchen aufzuführen.}

{159}{}{Was meinst du mit Verhältnis?!}
{160}{}{Lass es mich dir erklären ...}
{161}{}{Na ja, weißt du, das ist zu schwierig für dich, und ich habe keine Zeit.}

{162}{}{Du lügst mich an!!!}
{163}{}{Nein ... Äh, na gut, ich bringe es dir bei.}
{164}{}{Denk, was du willst, ist mir egal. Du liegst einfach falsch.}

{165}{}{[Du erklärst, wie man mit Variablen zählt und Proportionen berechnet – das ist eine gute Lektion für einen Jungen.] Danke, Mister! Ich bin so glücklich! Jetzt werde ich cooler sein als Jolly Joe! Der kann nicht mal sein eigenes Einkommen zählen. Moment mal ... Hier sind die Stimmnüsse – das ist wie eine Bezahlung für die Lektion!}
{166}{}{Danke. Jetzt lern aus deinen Fehlern.}
{167}{}{[Du erklärst, wie man mit Variablen zählt und Proportionen berechnet – das ist eine gute Lektion für einen Jungen.] Danke, Mister! Ich bin so glücklich! Jetzt werde ich cooler sein als Jolly Joe! Der kann nicht mal sein eigenes Einkommen zählen. Moment mal ... Hier sind ein paar Wasserreinigungstabletten – das ist wie eine Bezahlung für die Lektion! Wir brauchen sie nicht mehr, seit die Stadt sauberes Wasser bekommt.}

#Æåíñêèå ðåïëèêè:
{1123}{}{Schrei mich nicht an, du hast angefangen, nicht ich! Klar?! Und du bist in *meinem* Haus, also: Tschüss! [zeigt dir die Tür]}
{1148}{}{Na gut, tut mir leid. Ich wollte dich nicht aufregen. Löse dein Rätsel. Tschüss.}
{1149}{}{[Der Junge rennt weg] Papa! Ein Fremder im Haus! Papa!}
{1153}{}{Das stimmt nicht! Das ist falsch! Karawanenhändler haben mir dieses Rätsel gegeben! Also ja, ich schaff das auch ohne dich! Pfffft! [Er zeigt dir die Zunge und spuckt]}
{1165}{}{[Du erklärst, wie man mit Variablen zählt und Proportionen berechnet – das ist eine gute Lektion für ein Mädchen.] Danke, Miss! Ich bin so glücklich! Jetzt werde ich cooler sein als Jolly Joe! Der kann nicht mal sein eigenes Einkommen zählen. Moment mal ... Hier sind die Stimmnüsse – das ist wie eine Bezahlung für die Lektion!}
{1167}{}{[Du erklärst, wie man mit Variablen zählt und Proportionen berechnet – das ist eine gute Lektion für ein Mädchen.] Danke, Miss! Ich bin so glücklich! Jetzt werde ich cooler sein als Jolly Joe! Der kann nicht mal sein eigenes Einkommen zählen. Moment mal ... Hier sind ein paar Wasserreinigungstabletten – das ist wie eine Bezahlung für die Lektion! Wir brauchen sie nicht mehr, seit die Stadt sauberes Wasser bekommt.}
