{100}{}{Du siehst den Sheriff.}
{101}{}{Du siehst Burton „Whip“ Hickok, den Sheriff von Salt Lake City.}

{102}{}{Entschuldigung, was ist das hier für ein Ort?}
{103}{}{Ich sollte wirklich etwas für die Bildung hier tun, wenn die Leute nicht mal das Schild „Sheriff“ am Eingang lesen können ...}
{104}{}{Ach, das ist also das Büro des Sheriffs? Und Sie sind ...}
{105}{}{Ich bin der Sheriff höchstpersönlich. Mein Name ist Burton Hickok, aber manche nennen mich „Whip“. Und um die nächste Frage gleich zu beantworten: Ja, mein Vorfahr ist *der* Hickok. Und ja, ich sorge mit einer Peitsche für Ordnung ... und, falls nötig, mit einer Pistole.}
{106}{}{Okay, Sheriff Burton, jetzt ist alles klar.}

#Dialogue start:
{110}{}{Du warst es also, der den Dieb in der Innenstadt bei den Quok-Brüdern erwischt hat? Das hast du richtig gemacht. Es hat mich lange gekostet, den Dreck der Stadt zu beseitigen, aber es gibt immer noch Bastarde, die Salt Lake in eine Muellhalde verwandeln wollen. Deshalb schätzen wir jeden Sieg der gerechten Justiz über die Gesetzlosigkeit. Im Namen aller in Salt Lake danke ich dir für deine Hilfe. Ich weiß nicht, was deine Beweggründe waren, aber ich weiß es trotzdem zu schätzen. Der Tradition nach steht dir eine Belohnung zu. 3000 $ ist der Betrag, den die Händler ohne dich verloren hätten. Nochmals vielen Dank.}
{111}{}{Wow! Das ist eine ganz schön hohe Belohnung!}
{112}{}{Na gut. Bring den da in die Zelle, und den hier lassen wir laufen. [Er wendet sich an dich.] Das ist meine erste und letzte Warnung, weil du neu in der Stadt bist. Ich weiß nicht, was dich zu so einer schmutzigen Tat getrieben hat, aber ab jetzt wird niemand mehr nett zu dir sein. [Er legt die Hand auf seine Waffe.] Und jetzt verschwinde.}
{113}{}{Verdammt, das ist wirklich aus dem Ruder gelaufen ...}
{114}{}{Du bist also der geheimnisvolle Geist? Ja, wir haben schon von deinen „Heldentaten“ gehört. Ich weiß nicht, warum sie dich im ganzen Ödland suchen, aber wenn du in meiner Stadt Ärger machst, werde ich dich höchstpersönlich von der Welt schaffen. Das war vorerst nur eine Warnung. Die erste und letzte.}
{115}{}{Verstanden, Sheriff. Du musst es nicht wiederholen.}
{116}{}{Reden.}
{117}{}{Wie läuft's, Sheriff?}
{118}{}{Ich muss dir etwas Wichtiges sagen.}
{119}{}{Ich muss weiter.}
{120}{}{Wirklich? Was denn?}
{121}{}{Vergiss es, es ist doch nicht so wichtig.}

#Question answer
{122}{}{Ich konnte einen Filter für den artesischen Turm besorgen. Kannst du mir sagen, an wen ich ihn am besten verkaufen kann?}
{123}{}{Könntest du eine offene Stelle für einen bestimmten Penner finden? Nein, nicht für mich.}
{124}{}{Sheriff, ich brauche eine *ernsthafte* Arbeit. Du weißt schon, was ich meine.}
{125}{}{}
{126}{}{Sheriff, da gibt es eine üble Sache mit einem Hund ...}
{127}{}{Wusstest du, dass Merck seine Frau schlägt? Ich kann es bezeugen!}
{128}{}{Merck hat seine Frau umgebracht! Ich habe es mit eigenen Augen gesehen!}

#About the tower filter:
{130}{}{An mich.}
{131}{}{Äh ... Darf ich fragen, warum? Ich dachte, die Nuka-Cola-Fabrik braucht ihn dringender, zum Beispiel.}
{132}{}{Das stimmt. Unsere Stadt hat bereits Probleme mit der Gesundheitsversorgung und sauberem Wasser. Die Möglichkeit, große Mengen sauberen Wassers zu erzeugen, könnte zu einer echten Plage für die Stadt werden und viele Konflikte auslösen, wenn sie in die falschen Hände gerät.}
{133}{}{Welche Konflikte? Zwischen wem?}
{134}{}{Zum Beispiel zwischen der Bevölkerung und der Fabrik. Wenn wir den Filter der Stadt überlassen, wird die Fabrik erhebliche Gewinneinbußen erleiden, was sich auch auf die Arbeitsplätze auswirken wird. Da die Fabrik die industrielle Basis der Stadt und der wichtigste örtliche Betrieb ist, kann dabei nichts Gutes herauskommen. Je schlechter es der Fabrik geht, desto schlechter geht es der Bevölkerung.}
{135}{}{Warum geben wir den Filter dann nicht der Fabrik?}
{136}{}{Weil die Fabrik die Wasserversorgung an sich reißen und für ihre Geschäfte nutzen wird, statt zum Wohl der Bevölkerung. Viele wären darüber empört. Ich schlage vor, eine neutrale Partei zu finden, die für Ausgleich sorgt. Ich bin der Sheriff – ich bin diese neutrale Partei. Verkauft mir den Filter, dann lassen sich solche Probleme vermeiden.}
{137}{}{Und welchen Preis würdest du zahlen?}
{138}{}{Zehntausend. Mehr kann ich der Stadtkasse nicht entnehmen, unsere Stadt ist nicht so reich. Die Fabrik wird dir wahrscheinlich mehr bieten, aber ich habe dir bereits gesagt, wie das enden könnte. Denk darüber nach.}
{139}{}{Abgemacht.}
{140}{}{Ich denke darüber nach und entscheide später.}
{141}{}{Das liegt bei dir. Aber du solltest meine Worte besser bedenken.}
{142}{}{In Ordnung.}
{143}{}{Nun, du hast eine weise Entscheidung getroffen. Hier ist dein Geld. Und ... danke. Unsere Stadt wird deine Hilfe zu schätzen wissen.}
{144}{}{Kein Problem, Sheriff!}
{145}{}{Du hast den Filter für den artesischen Turm abgeliefert und damit die Lebensbedingungen vor Ort deutlich verbessert.}

#Cola Merchant
{146}{}{Ich möchte ein Verbrechen melden! Der Händler auf dem Parkplatz hat mir verstrahlte Nuka-Cola verkauft.}
{147}{}{Verdammt, ich hätte riechen müssen, dass mit diesem Händler etwas faul ist! Mir ist gar nicht in den Sinn gekommen, seine Waren auf Strahlenbelastung zu prüfen. Der hat wahrscheinlich ernsthafte psychische Probleme, wenn er mit verstrahlten Sachen herumhantiert. Nun, wir müssen die Waren beschlagnahmen und vernichten ... Danke für Ihre Aussage. Das war eine rechtzeitige Entscheidung, jemand hätte zu Schaden kommen können.}
{148}{}{Gern geschehen, Sheriff.}

#About the cleaned up hobo:
{150}{}{Für einen Landstreicher, was? Geht es um den, der in der Handelszone herumstreunt? Wurde auch Zeit, dass er aus der Gosse kommt ... Na schön, ich kann ihm Arbeit geben. Nichts für zarte Hände, aber harte, ehrliche Arbeit. Sagen Sie ihm, er soll zu mir kommen, dann reden wir darüber.}
{151}{}{Mach ich.}

#Gary Gilmore Quest:
{152}{}{Es gibt da tatsächlich etwas, das ich selbst nicht erledigen kann, aber ich bin mir nicht sicher, ob Sie dazu in der Lage wären.}
{153}{}{}

{154}{}{Es gibt da tatsächlich etwas, das ich selbst nicht erledigen kann.}
{155}{}{Interessant. Erzählen Sie.}
{156}{}{Zuerst ein wenig Geschichte, damit Sie wissen, in welches Loch Sie Ihre Nase stecken. Einst gab es in Salt Lake einen Bürgerkrieg, und die Unterwelt blühte dabei auf. Es war eine schwere Zeit für die Stadt. Ich beschloss, mir das nicht länger gefallen zu lassen und den Mistkerlen das Handwerk zu legen.}
{157}{}{Und?}
{158}{}{Ich kannte ungefähr die Zahl der Täter. Also nahm ich eine Truppe treuer Jungs mit und wir stürmten all ihre Treffpunkte. Die Gefangenen knickten ein und verrieten ihre Komplizen. Wie sich herausstellte, ist es manchmal nützlich, die Grenze zu überschreiten.}
{159}{}{Und?}
{160}{}{Wir erwischten jedes Mitglied der Bande und stellten sie auf dem Platz öffentlich zur Schau. Die Stadt lernte ihre Lektion. Die meisten Mistkerle hingen drei Tage am Galgen. Diejenigen, die beteiligt waren, aber den Tod nicht verdient hatten, wurden aus der Stadt verbannt. Lange haben wir nichts mehr von ihnen gehört ... Bis vor Kurzem.}
{161}{}{Und was haben sie jetzt angestellt?}
{162}{}{Wir hatten beinahe vergessen, dass es sie gibt, abgesehen von ein paar gelegentlichen Todesfällen auf der Straße Richtung Süden. Doch in den letzten paar Jahren hören wir immer öfter vom Gebiet um Provo – besonders von den Überfällen auf Karawanen und Reisende. Manchmal ergeben diese Angriffe überhaupt keinen Sinn. Ich glaube, sie wollen sich an uns rächen.}
{163}{}{Aber sie kommen nicht in die Stadt?}
{164}{}{Sie haben wohl immer noch zu viel Angst. Aber offenbar ist ihnen die Landwirtschaft langweilig geworden. Die Bande verübt gelegentlich kleinere Überfälle und Raubzüge am Stadtrand. Aber es gibt einen Mann, der die Bande zusammenhält.}
{165}{}{Wer?}
{166}{}{Gary Gilmore. Die „Akten“ dieses Verbrechers sind so vielfältig, dass man sich nur wundern kann. Für mich ist klar, dass mit ihm etwas nicht stimmt. Er verdient den Tod wie kein anderer, aber – und das ist mir wichtig – unsere Stadtbewohner müssen seinen Tod miterleben.}
{167}{}{Und was hält dich davon ab?}
{168}{}{Ein Dutzend Schläger in den fremden Ruinen von Provo, wo überall Fallen lauern. Bei einem Angriff dort würden wir viele Männer verlieren. Allein hineinzuschleichen ist viel einfacher. Aber ich brauche meine Männer hier. Deshalb suche ich einen Söldner, der mutig und erfahren genug ist, Gilmore zurückzubringen – wenn nicht lebend, dann wenigstens mit seinem Kopf.}
{169}{}{Ein ernster Auftrag. Gibt es dafür auch eine ordentliche Bezahlung?}
{170}{}{Für unsere Stadt ist ein Kopfgeld von 3000 $ pro Kopf ziemlich ordentlich. Für den lebenden Verbrecher zahle ich doppelt so viel. Ich rate dir, dir Zeit zu nehmen und gut darüber nachzudenken. Beurteile erst die Lage und entscheide dann.}
{171}{}{In Ordnung, ich übernehme den Auftrag.}
{172}{}{Ich muss über das Angebot nachdenken.}
{173}{}{Genug davon. Ich bin eigentlich kein Söldner ... [leave]}

{177}{}{Gilmore weigert sich, nach Salt Lake zurückzukehren. Vielleicht sollte ich ihn einfach erledigen?}
{178}{}{Ich bin froh über jede Gelegenheit, der Stadt ein gewisses Maß an Gerechtigkeit zu verschaffen, aber eine öffentliche Hinrichtung wäre mir lieber.}
{179}{}{Nun, du weißt es sicher besser.}
{180}{}{Gilmore ist tot. Es gab keine andere Möglichkeit.}
{181}{}{Du glaubst, ich freue mich, nur weil du es mir sagst? Ich brauche einen Beweis, einen eindeutigen und überzeugenden. Kannst du mir einen vorlegen?}
{182}{}{Hier ist sein Kopf. Du willst doch nicht bestreiten, dass das *sein* Körperteil ist, oder?}
{183}{}{Leider nicht.}
{184}{}{Eben. Und du kannst sicher sein, dass die Stadt dir nicht einfach glauben wird. Die Leute werden tuscheln und sich Geschichten ausdenken ... Raus aus dem Büro und komm erst mit einem Beweis zurück!}
{185}{}{[Gehen]}
{186}{}{Ausgezeichnete Arbeit! Sieh ihn dir an – so gebrechlich, und doch hat er so viel Ärger gemacht ... Wir stellen seinen Kopf auf dem Hauptplatz aus, damit die ganze Stadt die Unausweichlichkeit gerechter Vergeltung sehen und bewundern kann. Wie versprochen, hier sind 3000 $ für den Auftrag. Danke, ich werde das nicht vergessen.}
{187}{}{Gern geschehen.}

{188}{}{Und, was ist mit Gilmore? Wann findet der Prozess statt?}
{189}{}{Dieser Bastard wird bekommen, was er verdient, aber nicht sofort. Wir müssen ihn noch zu allerlei Dingen verhören. Danach schleifen wir ihn durch die Straßen der Stadt, damit jeder sehen kann, was aus Leuten wie ihm wird.}
{190}{}{Verstanden.}
{191}{}{Gary Gilmore und sein kriminelles Leben sind Geschichte.}
{192}{}{Ausgezeichnete Arbeit! Viele würden dich um dein Können beneiden. Du hast nicht nur hart gearbeitet, sondern auch viele potenzielle Opfer dieses Verrückten gerettet. Das ist das Doppelte des vereinbarten Lohns wert. Hier. [gibt dir 6000 $]}
{193}{}{Gern geschehen, Sheriff.}

{197}{}{Sheriff, nachdem wir uns um diesen Verrückten gekümmert haben: Haben Sie noch weitere Aufträge für mich?}
{198}{}{Hältst du dich also für hart im Nehmen? Oder tötest du einfach gern andere für schnelles Geld? Wie dem auch sei, das geht mich nichts an. Für jeden Kopf aus dem Rest der Provo-Bande bin ich bereit, ein Kopfgeld zu zahlen. Denk nicht einmal daran, mich zu täuschen – wir führen über jeden von ihnen eine Akte mit Fotos und ausführlichen Beschreibungen.}
{199}{}{Na gut. Ich werde über dein Angebot nachdenken. Bis später.}

#About the dog
{200}{}{Als hätte ich hier nicht schon genug andere Probleme ... Ich höre.}
{201}{}{Ein Junge, der hier auf der anderen Straßenseite wohnt, hat seinen Hund verloren und mich gebeten, sie zu suchen. Aber ... der Hund ist tot.}
{202}{}{Lass mich raten – durch deine Hand, richtig?}
{203}{}{Ja. Aber ich musste es tun! Sie hatte sich eindeutig mit Tollwut angesteckt und mich angegriffen.}
{204}{}{Nein, der Ausgestoßene, der beim artesischen Turm wohnt, hat es getan.}
{205}{}{Verstehe. In der Stadt gab es schon immer tollwütige Hunde. Keine Sorge, ich rede mit dem Jungen und erkläre ihm die Situation. Du bleibst einfach hier und wartest.}
{206}{}{Um ehrlich zu sein, bin ich mir nicht so sicher. Ich sollte nachsehen gehen.}
{207}{}{Ausgezeichnet!}
{208}{}{Nein, ich mache das. Da es meine Schuld ist, sollte ich es ihm lieber selbst sagen.}
{209}{}{Bist du sicher? Na gut, wie du meinst.}
{210}{}{Ich habe mit dem Jungen und seiner Familie gesprochen. Alles ist in Ordnung. Du kannst den Vorfall vergessen.}
{211}{}{Danke, Sheriff!}
{212}{}{Und warum hat er das getan?}
{213}{}{Weil er sie frisst!!!}
{214}{}{Das dachte ich mir. Ehrlich gesagt bin ich sogar dankbar. Obwohl wir ihn alle nicht leiden können, befreit er die Stadt von streunenden Hunden. Ohne handfeste Beweise kann ich allerdings nichts gegen ihn unternehmen.}
{215}{}{Ich habe die Hundemarke. Ich habe sie vor seinem Haus gefunden.}
{216}{}{Ich habe keine Beweise.}
{217}{}{Ich habe keine Beweise, aber ich habe es mit eigenen Augen gesehen! Reicht das nicht?!}
{218}{}{Was soll ich deiner Meinung nach dagegen tun? Jemanden aufgrund der Aussage eines anderen bestrafen? Und was, wenn sich herausstellt, dass es nicht stimmt und der Hund zu seinen Besitzern zurückkehrt? Wie würde ich dann dastehen? "Der Sheriff bestraft Unschuldige!" So gehe ich nicht vor.}
{219}{}{Dann werde ich nach Beweisen suchen.}
{220}{}{Das reicht mir. Ich werde mit ihnen reden. Keine Sorge.}

# Additional dialogue about Gilmore
{232}{}{Hör mal, Sheriff. Du bist ein kluger Mann. Wenn du jemanden für etwas "Drecksarbeit" brauchst, ist das deine Chance. Ich habe mehr als  }
{233}{}{ Kerben an meiner Waffe. Glaubst du, ich kann mich nicht um ein kleines örtliches Problem kümmern?}
{234}{}{Na ja, du wirst es besser wissen.}
{235}{}{Zweifelst du an meinen Fähigkeiten? Dann brauche ich deinen miesen Job nicht.}
{236}{}{Sheriff, ich habe auf meinen Wanderungen schon viel erlebt und mich aus so mancher brenzligen Lage befreit. Ich würde dir wirklich gern helfen.}
{237}{}{Hmm. Du machst einen ziemlich fähigen Eindruck, beim Rest bin ich mir nicht so sicher. Na ja, es ist deine Entscheidung. Wenn du stirbst, komm nicht bei mir angeheult.}
{238}{}{Hmm, wenn du wirklich ein ausgezeichneter Schütze bist, könntest du dich vielleicht behaupten ...}
{239}{}{Das ist großartig. Um welches Problem geht es?}
{240}{}{Sheriff, ich rate dir davon ab, mein Angebot abzulehnen, wenn du jemanden für "Drecksarbeit" brauchst. Ich habe zum Beispiel }
{241}{}{ tote Aliens aus Area 51 auf dem Kerbholz.}

#About bikers
{250}{}{Sheriff, man sagt, du kennst den Standort des Biker-Stützpunkts. Stimmt das?}
{251}{}{Ja, es stimmt. Und ich werde diese Information nicht umsonst weitergeben. Beweise zuerst, dass du dieser Stadt etwas wert bist.}
{252}{}{Ich könnte dir etwas Geld für die Information geben.}
{253}{}{Findest du nicht, dass ich schon genug getan habe?}
{254}{}{Ich werde über deine Worte nachdenken.}
{255}{}{Geld? Sehe ich für dich etwa wie ein Händler aus? Allerdings ... Du kannst der Stadt eine Spende geben. Etwa 3000 $, zum Beispiel, das würde uns hier sehr helfen.}
{256}{}{Gut, hier ist meine Spende.}
{257}{}{Nun, jetzt sehe ich, dass du Recht und Ordnung nicht mit Füßen trittst. Nun zu deinem Problem: Hier sind die Koordinaten von Battle Mountain, wo sich eines der Bikerlager befindet. Ich war selbst noch nicht dort, also kann ich dir nur diese Information geben.}
{258}{}{Danke.}
{259}{}{Hm. Lass mich nachdenken. Angesichts deines Ansehens in meiner Stadt ...}
{260}{}{... teile ich die Information gern mit dir.}
{261}{}{... werde ich dir nicht helfen.}

# About Merck and family problems
{262}{}{Ich hatte schon lange einen Verdacht, aber ich konnte nie direkte Beweise finden. Seine Frau sagt nichts. Vielleicht hat sie Angst. Trotzdem kann ich mich nicht einmischen – das ist ihre Privatsache.}
{263}{}{Wirklich? Was, wenn es dann zu spät ist?}
{264}{}{Was könnte ich schon tun? Wenn seine Frau gestanden und selbst um Hilfe gebeten hätte ... Trotzdem gefällt es mir nicht, jemanden für die Worte eines anderen zu bestrafen. Es ist eine kleine Stadt, hier gibt es viel Klatsch und alte Familienfehden. Halte dich lieber da raus, glaub mir. Ich hoffe, das Leben lehrt sie, einander zu schätzen.}
{265}{}{Hm. Na gut, wenn du dir so sicher bist ...}
{266}{}{Was?! Verdammt! Ich hatte befürchtet, dass es schlimm enden würde. Aber wenn ich mich eingemischt hätte, wäre das Problem nicht gelöst worden. Leute wie Merck kann man nicht einfach ändern. Jetzt knöpfen wir uns den Mistkerl vor. Hey, Leute! Macht euch bereit! Du wartest hier, bis wir zurück sind.}
{267}{}{[Warten]}

{268}{}{Ich hab den Mistkerl erwischt! Er war so hysterisch, dass er sich nicht einmal gewehrt und selbst nach dem Galgen verlangt hat. Ich schätze, wenn er wieder nüchtern ist und seinen Rausch ausgeschlafen hat, wird er anders reden. Was meinst du, was sollen wir mit ihm machen?}
{269}{}{Öffentlich hängen! Sozusagen als abschreckendes Beispiel.}
{270}{}{Hängt ihn, aber nicht öffentlich. Diese Schande soll geheim bleiben. Gegen Merck ließ sich leider nichts machen.}
{271}{}{Er hat keine Wurzeln mehr in der Stadt. Vielleicht sollten wir ihn verbannen?}
{272}{}{Verurteile ihn zu gemeinnütziger Arbeit unter strenger Bewachung. Er braucht Disziplin.}
{273}{}{Ich weiß nicht, das musst du entscheiden.}
{274}{}{Du hast recht. Ich werde über die Strafe nachdenken.}
{275}{}{Oh! Danke für das Geld!}
{276}{}{Ja, du hast recht. Ihm fehlt es an Disziplin. Es ist schade, dass es so weit kommen musste, denn er war ein vielversprechender Mann. Seinen verletzten Stolz hat er sich selbst zuzuschreiben.}
{277}{}{Nun, danke, dass du mir davon berichtet hast. Hier sind 200 Mäuse. Ich hoffe, du wirst dich auch weiterhin in Salt Lake für die Ordnung einsetzen. Mach's gut.}
{278}{}{Ihn verbannen? Das habe ich mit den Bastarden, die jetzt im Gebiet um Provo leben, schon einmal durchgemacht. Jetzt werden sie hier nie wieder einen Fuß hineinsetzen. Ich hoffe, Merck wird diese Lektion auch verstehen.}
{279}{}{Da stimme ich zu. Das ist sein persönliches Problem. Soll er es mit ins Grab nehmen.}
{280}{}{Wir hatten schon lange keine öffentliche Hinrichtung mehr ... Nun, vielleicht ist es an der Zeit, die Leute etwas aufzurütteln und alle daran zu erinnern, wie alles begann ...}

{281}{}{Äh ... Sheriff, ich habe mich bereits darum gekümmert. Merck ist tot.}
{282}{}{Ach, so ist das! Willst du vielleicht auch noch das Sheriffabzeichen?! Dreh dich um und verschwinde aus meinem Büro. Leute wie dich brauchen wir in unserer Stadt nicht.}
{283}{}{Äh ...}

# Answers about the city
{310}{}{Etwas Bestimmtes?}
{311}{}{Vergiss es, ich habe noch eine andere Frage.}
{312}{}{Danke für deine Antwort. Tschüss.}
{313}{}{Mehr oder weniger in Ordnung, denke ich.}

{350}{}{Irgendein Dieb plündert hier alle Nuka-Cola-Automaten. In der ganzen Fabrik herrscht Panik, und wir haben nicht die geringste Ahnung, wer dahinterstecken könnte.}
{351}{}{Wegen Provo. Die Leute glauben immer noch nicht, dass dort alle tot sind. Die Nachricht hat sich unter den Karawanenhändlern herumgesprochen, aber niemand will hinfahren und nachsehen. Ich hoffe, diese verdammten Bastarde sind wirklich tot.}
{352}{}{Gary Gilmore hat bekommen, was er verdient hat. Möge er in der Hölle brennen!}
{353}{}{Nun, die Nuka-Cola-Fabrik hat ein beispielloses Wachstum erlebt. Die Dinge entwickeln sich zum Besseren. Allerdings wird die Ökologie der Stadt umso schlechter, je besser die Fabrik läuft, wegen all der produzierten Abfälle. Eine verdammt ungerechte Situation.}
{354}{}{Es sieht so aus, als würde die Nuka-Cola-Fabrik bald auseinanderfallen. Wir müssen irgendwann etwas dagegen unternehmen. Die Arbeiter fliehen in alle Richtungen, die Produktion geht zurück. Dafür geht es den Menschen besser, denn die geringeren Emissionen der Fabrik bedeuten, dass weniger Schadstoffe in den See gelangen. Die Stadt wird sauberer.}
{355}{}{Uns allen ist aufgefallen, dass sich die Gesundheitslage in der Stadt verbessert. Wir haben viel weniger Krankheiten, und vor den Toiletten gibt es keine solchen Menschenmengen mehr. Das freut mich.}
{356}{}{Die medizinische Versorgung in der Stadt ist sehr schlecht geworden. Eine echte Seuche. Ich rate dir, direkten Kontakt mit Menschen zu vermeiden und lieber Cola statt Wasser zu trinken.}
{357}{}{Alles in allem floriert die Stadt. Einen solchen Zustrom an Neuankömmlingen habe ich noch nie erlebt. Offenbar spricht es sich bereits im Ödland herum, dass die Stadt wieder auf den Beinen ist – hier kann man Geld verdienen und eine gute Zeit haben. Ich hoffe, das bleibt so.}
{358}{}{Die ganze Stadt ist verrückt geworden. Ich schaffe es kaum, die Lage unter Kontrolle zu halten. Die Leute können jederzeit verwildern und mich, dich oder jeden anderen auf ihrem Weg zerreißen. Wir müssen etwas unternehmen ... Ich weiß nicht, was. Ich hoffe wirklich, uns fällt etwas ein ...}
{359}{}{Die Stadt geht ihrem gewöhnlichen Alltag nach. Die Bevölkerung beschwert sich nicht, jeder kennt seinen Platz und irgendwie kommen alle miteinander aus.}
{360}{}{Nachdem die Lage in Provo geklärt ist, herrscht in der Stadt wieder Ruhe. Dank dir haben die Bürger keine Angst mehr, nachts nach draußen zu gehen.}


#Additions about Gilmore and Provo
{370}{}{Hier ist die vereinbarte Lieferung Köpfe aus Provo.}
{371}{}{Na gut, sehen wir sie uns an ...}
{372}{}{[Weiter]}
{373}{}{Was – willst du dich über mich lustig machen?}
{374}{}{Ach, komm schon! Was ist denn so schlimm daran? Der Kopf ist eben auf den Boden gerollt ...}
{375}{}{Ein weiteres Problem der Stadt gelöst. Im Namen aller Bürger danke ich dir. Hier ist deine Belohnung: }
{376}{}{ Dollar.}
{377}{}{Wer hätte gedacht, dass man für einen gewöhnlichen Kopf so viel Geld bekommen kann ...}

#Reaction to the sheriff of Uranium City
{380}{}{[Als er dein Sheriff-Abzeichen sieht, hebt er skeptisch eine Augenbraue] Wo hast du das her?}
{381}{}{Ich bin der gewählte Sheriff von Uranium City.}
{382}{}{Nun, du musst wissen, sie haben mir das Amt einfach übertragen. Ich wollte es gar nicht annehmen, aber sie haben darauf bestanden ...}
{383}{}{Ich habe von den Karawanenleuten etwas über diese Stadt gehört ... Dort wird Uranerz für Kraftwerke abgebaut, stimmt's? Nun, schön zu sehen, dass auch andere Siedlungen für Ordnung sorgen und das Gesetz achten. Setz dich, Sheriff. Für dich nehme ich mir gern mehr Zeit als sonst.}
{384}{}{Schön, einen freundlichen Vertreter des Gesetzes zu sehen. Also, reden wir, Sheriff.}
{385}{}{Hm ... Na schön, steck diesen Schmuck in eine Tasche, bis ich ihn dir abnehme. *Ich* bin hier der Sheriff, und niemand außer *mir* trägt diesen Titel in meiner Stadt.}
{386}{}{Ähm, sicher, Sheriff.}

# Ghost Train
{400}{}{Fahren in letzter Zeit irgendwelche Züge durch die Stadt?}
{401}{}{Ha! Warum willst du das wissen? Willst du unbedingt sterben? Dann geh abends besser zum Galgen. Meistens ist jemand da, der sich von diesem Leben verabschieden darf.}
{402}{}{Trotzdem fahren hier Züge durch, oder?}
{403}{}{Ja, einen gibt es. Er kommt mitten in der Nacht. Rast mit halber Geschwindigkeit durch, ohne anzuhalten, und verschwindet Richtung Westen. Man sagt, manchmal kann man die Seele des Lokführers Mundharmonika spielen hören. Wer die Silhouette des „Geisterzugs“ gesehen hat, traut sich nicht, die Gleise zu überqueren. Was, wenn er plötzlich aus dem Nichts auftaucht und dich überfährt?}
{404}{}{Meinst du das ernst?}
{405}{}{Und ob. Manche haben sogar versucht, aufs Dach des Waggons zu springen, wurden aber von den höllischen Flammen zu Asche verbrannt.}
{406}{}{Wow! Wie oft fährt er vorbei?}
{407}{}{Mehrmals pro Saison, hin und her. Er hat eindeutig eine sehr lange Strecke. Muss unterwegs eine Menge Seelen einsammeln.}
{408}{}{Äh, okay, lassen wir den Gruselteil aus ... Kennst du sein endgültiges Ziel?}
{409}{}{Nein. Manche glauben, dass dieser Zug weder hält noch abbiegt. Einige schwören sogar, er könne gleichzeitig an verschiedenen Orten sein.}
{410}{}{Klingt nach betrunkenem Unsinn.}
{411}{}{Trotzdem gibt es ihn, was auch immer er wirklich ist. Die halbe Stadt hat ihn gesehen.}
{412}{}{Danke für die Geschichte, aber ich muss los.}
{413}{}{Sheriff, Schluss mit den Märchen. Wir wissen beide, dass der „Geisterzug“ ganz real ist und sich kaum von einem gewöhnlichen Zug unterscheidet ...}
{414}{}{Manchmal fährt jemand mit dem Zug nach Norden und Westen. Manche haben auch Roboter gesehen, die die Eisenbahn noch in Schuss halten. Aber wer das braucht und warum, weiß niemand.}
{415}{}{Das heißt eindeutig, dass er echt ist.}

#About Reaper of Souls
{450}{}{Halt! Keinen Schritt weiter!}
{451}{}{Sheriff? Äh ... ich habe nichts getan!}
{452}{}{Na sieh mal einer an, die Ehrlichkeit in Person steht vor mir. Antworte mir: Warum gehst du zum Bahnhof?}
{453}{}{Ich habe dort etwas zu erledigen, Sheriff. Aber das geht dich nichts an.}
{454}{}{Und was ist das?}
{455}{}{Ich fahre mit dem Zug weit über die Stadt hinaus. }
{456}{}{Antworte mir, verdammt! Antworte, bevor es zu spät ist!}
{457}{}{Geh mir aus dem Weg! Ich sage nichts!}
{458}{}{Bevor es zu spät ist? Wovon redest du?!}
{459}{}{Verdammt, du verstehst nicht, worauf du dich einlässt! Du kannst ihn nicht aufhalten, selbst wenn du die ganze lausige Stadt gegen ihn aufhetzt.}

{460}{}{Wie du willst. Du wirst es niemandem erzählen. [Sheriff zieht seine Waffe]}
{461}{}{(Hoppla, Zeit, sich aus dem Staub zu machen ...)}

{462}{}{Wovon redest du?}
{463}{}{Tu nicht so blöd, Besserwisser. Du weißt es. Der Seelenschnitter.}
{464}{}{Der Seelenschnitter?}
{465}{}{Du hast mich schon richtig verstanden. Tu nicht so, als hättest du nichts gehört. Der Mann in den Roben.}
{466}{}{Wer zum Teufel ist er? Was habe ich mit ihm zu tun?}
{467}{}{Hör mir gut zu, sturer Junge. Du glaubst, du wirst ihn aufhalten, du glaubst, du wirst deine Leute retten. Das wirst du nicht. Er wird nur von dir bekommen, was er will. Das ist meine letzte Warnung – geh zurück in deine Stadt, vergiss die Sache und bete, dass er nicht hinter dir herkommt.}
{468}{}{Heh, ich wusste es, Sheriff. Du bist nur seine Schlampe!}
{469}{}{Warum bist du dir so sicher, dass er nicht hinter mir herkommt?}
{470}{}{Der Sensenmann interessiert sich nur für reine Seelen. Ich weiß nicht, warum. Er sammelt sie schon seit Langem.}
{471}{}{Äh ... „Reine Seelen“? Klingt wie ein Schlaflied für Kinder.}
{472}{}{Ha-ha-ha! Da ist unser Sheriff mit seinen Gruselgeschichten! Zum Totlachen!}
{473}{}{„Reine Seelen“? Du meinst Menschen, die keinen Mutationen ausgesetzt waren, richtig?}
{474}{}{Er braucht die Nachkommen derer, die ihre Reinheit bewahren konnten, indem sie den Großen Krieg in den sicheren Vaults überlebten. Unsere Stadt kann ihm nicht mehr geben, was er will.}
{475}{}{Was hat das mit deiner Stadt zu tun?}
{476}{}{Warum braucht er genetisch reine Körper?}
{477}{}{Warum entführt er Menschen?}
{478}{}{Während des Krieges überlebte Salt Lake dank der Familien-Vaults. Die Bevölkerung kam im Laufe der Jahrzehnte nach und nach aus ihnen heraus. Doch mit der Zeit verloren hier alle ihre Reinheit.}
{479}{}{Hm. Offenbar haben die örtliche Ökologie in Verbindung mit Strahlung und Mutationen die Genetik der Bevölkerung beeinflusst.}
{480}{}{Na klar. Hier ist doch alles eine einzige Kloake. Was hast du erwartet?}
{481}{}{Ja, diese Stadt kann man nicht gerade sauber nennen ...}

{482}{}{Ich weiß nicht, was er mit den Entführten macht, aber sie kommen nicht zurück.}
{483}{}{Warum machen wir dieser Viper nicht ein für alle Mal den Garaus?}
{484}{}{Wir müssen seine Macht berücksichtigen. Er ist nicht einfach ein Mensch, sondern ein Wunder der Genmutation. Vielleicht kann er sogar deine Gedanken lesen.}
{485}{}{Willst du ernsthaft sagen, dass es keine Möglichkeit gibt, ihn aufzuhalten?}
{486}{}{Nicht in deinem Fall. Also warne ich dich zum letzten Mal: Dreh um und verschwinde. Das Überleben dieser Stadt ist mir wichtiger als deine dumme Mission.}
{487}{}{Kommt überhaupt nicht infrage! Ich gehe zum Bahnhof, ob es dir passt oder nicht.}
{488}{}{Na gut, ich gehe zurück in die Stadt ... fürs Erste.}
{489}{}{Du irrst dich. Der Seelenschnitter wird zurückkommen, um mich und meine Leute zu holen. Und du kennst nicht einmal seine wahren Absichten. Was, wenn ihm die „reinen Seelen“ ausgehen? Was passiert dann mit deinem Salt Lake?}
{490}{}{Es tut mir leid, aber ich *muss* dich aufhalten. [Der Sheriff zieht seine Waffe]}
{491}{}{(Hoppla, Zeit, sich aus dem Staub zu machen ...)}
{492}{}{Ich weiß es nicht und will es auch nicht wissen. Dreh dich jetzt um und komm nicht wieder.}
{493}{}{Warte, Sheriff! Vielleicht versucht er, eine Soldatenarmee aufzustellen, um das ganze Ödland an sich zu reißen? Deine Stadt hat schon genug gelitten. Es wird Zeit, dem ein Ende zu setzen!}
{494}{}{Sei kein Narr! Was kannst *du* schon gegen ihn ausrichten?}
{495}{}{Ich lasse mich nicht so leicht einschüchtern. Ich bin ihm schon begegnet. Glaub mir, er hat eine Schwachstelle, und ich werde sie finden.}
{496}{}{Du bist so naiv, dass es mich blendet. Sogar ich musste einen Handel mit ihm eingehen. Es gab eine Zeit, da musste ich mich entscheiden, um Salt Lake zu retten. Früher oder später muss jeder seinen Preis zahlen. Vielleicht wirst du das irgendwann auch verstehen.}
{497}{}{Das ist ein schweres Geständnis. Aber die Stadt kommt wieder auf die Beine, oder? Und der Seelenschnitter wird ihr weiter das Blut aussaugen, bis sie ausgeblutet ist.}
{498}{}{Wie willst du ihn überhaupt einholen? Er fährt in einem schwarzen Hochgeschwindigkeitszug. Du kannst weder ihn noch sein Ziel ausfindig machen.}
{499}{}{Ich habe die Koordinaten des Vaults, in dem er sich aufhält. Er hat den Aufseher meiner Stadt als Geisel genommen; in dessen Pip-Boy steckt ein Peilsender. Ich kann den Standort des Zuges bestimmen. Außerdem habe ich bereits ein funktionstüchtiges Transportmittel und bin bewaffnet. Das Überraschungsmoment ist auf meiner Seite, ebenso mein Verstand und mein Mut. Ich bin bestens vorbereitet, Sheriff!}
{500}{}{Ich sehe, du meinst es ernst ... Ich fürchte, diese Entscheidung wird mich mein Leben lang verfolgen. Geh.}
{501}{}{Ich werde dich nicht enttäuschen, Sheriff!}
{502}{}{... Und ich werde meine Stadt nicht in Gefahr bringen, indem ich einem Schwächling wie dir vertraue. Bring mich nicht zum Lachen und verschwinde, uns allen zuliebe!}
{503}{}{Der Weg ist frei!}
{504}{}{Ich warne dich nicht noch einmal.}

#Reaper dead
{505}{}{Der Seelenschnitter ist tot!}
{506}{}{Tot? Das kann ich nicht glauben ... Na ja, das werden wir wohl bald sehen.}
{507}{}{Also, welchen Handel hast du mit ihm abgeschlossen?}
{508}{}{Einst herrschten in der Stadt sehr instabile Verhältnisse. Kriminelle Parasiten überschwemmten die Stadt, und selbst tagsüber fühlte sich niemand sicher. Es war praktisch ein Bürgerkrieg. Dann tauchte er auf und bot seine Hilfe an, um für Ordnung zu sorgen. Das war keine leichte Entscheidung für mich.}
{509}{}{Was verlangte er als Gegenleistung?}
{510}{}{Reine Seelen. So viele er wollte. Anfangs verlangte er sie zweimal im Jahr, dann immer öfter.}
{511}{}{Und du hast nicht versucht, dich zu wehren?}
{512}{}{Meine Männer hatten schon immer Angst vor dem Seelenschnitter. Wir konnten einfach nicht.}
{513}{}{Diese Entscheidung war so unmoralisch, dass ich selbst über dich richten werde. SOFORT!}
{514}{}{Gib dir nicht die Schuld. Diese Entscheidung war besser als ein langer und blutiger Kampf mit der kriminellen Unterwelt.}
{515}{}{Du hast recht, früher oder später muss jeder seinen Preis zahlen.}

# Women's replica:
{1112}{}{Na gut. Bring den da in die Zelle, und den hier lassen wir laufen. [Er wendet sich an dich.] Das ist meine erste und letzte Warnung, weil du neu in der Stadt bist. Ich weiß nicht, was dich zu so einer schmutzigen Tat getrieben hat, aber ab jetzt wird niemand mehr nett zu dir sein. [Er legt die Hand auf seine Waffe.] Und jetzt verschwinde.}
{1128}{}{Merck hat seine Frau umgebracht! Ich habe es mit eigenen Augen gesehen!}
{1173}{}{Genug davon. Ich bin eigentlich kein Söldner ... [leave]}
{1184}{}{Eben. Und du kannst sicher sein, dass die Stadt dir nicht einfach glauben wird. Die Leute werden tuscheln und sich Geschichten ausdenken ... Raus aus dem Büro und komm erst mit einem Beweis zurück!}
{1193}{}{Gern geschehen, Sheriff.}
{1198}{}{Hältst du dich also für hart im Nehmen? Oder tötest du einfach gern andere für schnelles Geld? Wie dem auch sei, das geht mich nichts an. Für jeden Kopf aus dem Rest der Provo-Bande bin ich bereit, ein Kopfgeld zu zahlen. Denk nicht einmal daran, mich zu täuschen – wir führen über jeden von ihnen eine Akte mit Fotos und ausführlichen Beschreibungen.}
{1208}{}{Nein, ich mache das. Da es meine Schuld ist, sollte ich es ihm lieber selbst sagen.}
{1215}{}{Ich habe die Hundemarke. Ich habe sie direkt vor seinem Haus gefunden.}
{1236}{}{Sheriff, ich habe auf meinen Wanderungen schon viel erlebt und mich aus so mancher brenzligen Lage befreit. Ich würde dir wirklich gern helfen.}
{1253}{}{Glaubst du nicht, dass ich das schon versucht habe?}
{1410}{}{Klingt nach betrunkenem Unsinn.}
{1451}{}{Sheriff? Äh ... ich habe nichts getan!}
{1463}{}{Tu nicht so dumm, Schlaumeierin. Du weißt es. Der Seelenschnitter.}
{1467}{}{Hör gut zu, stures Mädchen. Er hat mich gebeten, dich aufzuhalten, aber ich will mich nicht mit den Problemen anderer Leute herumschlagen. Das ist meine letzte Warnung – geh zurück in deine Stadt und vergiss das alles. Der Schnitter wird nicht hinter dir her sein.}
{1468}{}{Heh, ich wusste es, Sheriff. Du bist doch nur seine Schlampe!}
{1494}{}{Sei kein Narr! Was kannst *du* schon gegen ihn ausrichten?}
{1513}{}{Diese Entscheidung war so unmoralisch, dass ich selbst über dich richten werde. SOFORT!}