{100}{}{Du siehst Beagle.}
{101}{}{Du siehst den leitenden Assistenten des Sheriffs.}

{102}{}{Wenn du den Sheriff suchst, ist er geschäftlich unterwegs.}

{110}{}{Was führt dich her? Wenn du den Sheriff sehen willst, er ist in seinem Büro.}
{111}{}{Gott, wer ist das?! Warum erschießen wir ihn nicht einfach?}
{112}{}{Du hast das mit dem Dieb richtig gemacht! Gut gemacht!}
{113}{}{Provo hätte schon vor langer Zeit zerstört werden sollen!}
{114}{}{Wegen Gilmore – gut gemacht!}
{115}{}{Steck deine Waffe weg! Sofort!}
