{100}{}{Du siehst einen Ausgestoßenen.}
{101}{}{Du siehst Stapleton.}
{102}{}{Du siehst einen einsamen, einäugigen Bewohner der Slums.}
{103}{}{Du siehst einen einsamen und geheimnisvollen Stapleton ... obwohl er größtenteils wie ein gewöhnlicher Bettler aussieht.}

#Îáùèå ôğàçû - Common description
{110}{}{[Der Mann, den du siehst, ist kräftig gebaut und hat ein hässliches Gesicht, dem ein Auge fehlt] Das ist mein Zuhause, ich wohne hier. Bist du sicher, dass du hier richtig bist?}
{111}{}{Na ja, normalerweise kommt hier niemand vorbei ...}
{112}{}{Okay, ich gehe dann.}
{113}{}{Verstehe ...}

#Êòî òàêîâ - Who are you
{120}{}{Darf ich fragen, mit wem ich spreche?}
{121}{}{Warum musst du das wissen? Normalerweise wenden sich alle einfach von mir ab. Und wenn sie mich doch kennenlernen wollen, gibt es Ärger. Geh lieber deiner Wege.}
{122}{}{Aber trotzdem. Dein Name ist doch kein Geheimnis, oder?}
{123}{}{Wow, du bist wirklich ein ziemlich ungeselliger Kerl ...}
{124}{}{[Eine Weile starrt der Ausgestoßene dich mit seinem einen Auge einfach nur an] Früher nannten sie mich Mr. Stapleton. Jetzt nennt mich niemand mehr beim Namen. Sie sagen mir nur noch, ich soll verschwinden. Deshalb sitze ich hier allein und gehe nicht mehr in die Stadt. Besuchen kommt mich auch niemand.}
{125}{}{Also war es deine eigene Entscheidung, oder? Ich meine, dich zu verstecken.}
{126}{}{[Er scheint lange und gründlich über die Antwort nachzudenken] Ich schätze schon ... Es ist schwer, mit Leuten zu reden, wenn sie sich schon eine Meinung über dich gebildet haben, ohne auch nur ein einziges Wort mit dir gewechselt zu haben.}
{127}{}{Warum behandeln sie dich so?}
{128}{}{Wegen des Rufs eines ehemaligen Verbrechers. Das ist lange her, damals, als die Nuka-Cola-Fabrik gerade eröffnet hatte. Ich war für die Instandhaltung zuständig, und bei einem unglücklichen Unfall wurde mein Gesicht schwer entstellt. Deshalb fingen die Leute an, mich zu meiden. Ich verfiel dem übermäßigen Trinken, schloss mich einer kleinen Gang an und stahl einen Haufen Sachen aus derselben Fabrik. Es waren unruhige Zeiten für die Stadt, in denen dich an jeder Ecke ein Schläger überfallen konnte. Weißt du, was geschehen ist, ist geschehen, aber die Leute erinnern sich immer noch an mein früheres, schlimmes Ich. Nur der Sheriff hat gelernt, andere nicht nach ihrer Vergangenheit zu beurteilen.}
{129}{}{Also konnte der Sheriff sogar einen ehemaligen Verbrecher akzeptieren?}
{130}{}{Genau. Er ist ein fairer Kerl.}

{131}{}{Ein fairer Kerl, weil er einen ehemaligen Knacki herumlaufen lässt? Da überlege ich mir seine Sache lieber zweimal.}
{132}{}{Es ist traurig, dass dein Leben so schlecht verlaufen ist. Es tut mir leid, dass ich dich das noch einmal durchleben lasse.}
{133}{}{Na ja, ich bin nur ein Fremder auf der Durchreise. Dazu habe ich keine Meinung. Man sieht sich, Stapleton.}

{134}{}{Ich bin es gewohnt, dass Leute mich so provozieren. Deine Versuche bringen hier also nichts. Das ist sinnlos, und ich finde, du solltest einfach gehen und dich um deinen eigenen Kram kümmern.}
{135}{}{Keine Ahnung, warum du das sagst, aber danke für die freundlichen Worte.}
{136}{}{Klar. Bis später ... Wanderer.}
{137}{}{Tschüss.}

#Ïğî áàøíş - about the tower
{150}{}{Was ist das für ein Turm da drüben?}
{151}{}{Ein Wasserturm, gebaut von der Vorkriegsfirma "Rain Soft". Drinnen befindet sich ein riesiger Tank, in dem artesisches Wasser von einer Tauchpumpe gesammelt und dann mithilfe eines Drucksystems über Wasserleitungen an die Kunden verteilt wurde.}
{152}{}{Kann man ihn jetzt noch benutzen?}
{153}{}{Nein. Das ganze Wasser war schon vor dem Großen Krieg aufgebraucht. Es gibt viele Leute, die ihn in Betrieb nehmen wollen, aber bisher hat es niemand geschafft.}
{154}{}{Was hält sie davon ab?}
{155}{}{Die Pumpenturbine, die das Wasser aus der Tiefe heraufpumpt, braucht einen neuen Reinigungsfilter. Niemand weiß, wo man einen herbekommt. Also steht dieser riesige Turm nutzlos herum. Aber selbst wenn man einen Filter finden würde, müsste man viel Zeit aufwenden, um alles einzurichten. Und mehr noch ...}
{156}{}{Mehr noch?}
{157}{}{Ich möchte mir gar nicht vorstellen, was für ein Sturm in der Stadt losbricht, wenn es darum geht, wer den Turm betreiben darf. Jeder braucht sauberes Wasser – die Leute, die Anlage Nuka-cola, allerlei gerissene Geschäftemacher ... Jeder Einwohner.}
{158}{}{Eine schwierige Entscheidung, ganz sicher. Wo könnte ich das Teil also finden?}
{159}{}{[Zuckt mit den Schultern] Ich weiß, dass Las Vegas einen Damm am Colorado gebaut hat. Ich weiß nicht, wie er funktioniert, aber dort gibt es reichlich sauberes Wasser. Selbst dann hätten Karawanenfahrer den Filter längst geliefert, wenn sie ihn hätten.}

#Ïğî ñîáàê - about the dogs
{160}{}{Wie schmeckt Hundefleisch?}
{161}{}{Na ja ... Besser als zähes Geckofleisch oder stinkendes Molerattenfleisch.}
{162}{}{Und ihre Besitzer haben nichts dagegen?}
{163}{}{Sie haben keine Besitzer. Das ist herrenloses Fleisch.}
{164}{}{Bist du sicher?}
{165}{}{Ein Hund würde nicht vor einem guten Herrchen weglaufen. Außerdem tragen sie keine Hundemarken und Halsbänder. In Salt Lake bekommt jeder Haushund eins, um Unfälle zu verhindern. Früher gab es in der Stadt ein großes Problem mit herrenlosen Hunden.}
{166}{}{Wie wurde das Problem gelöst?}
{167}{}{Der Sheriff organisierte eine Treibjagd auf sie. Eine große Menge kam zusammen, und an Munition und Fallen mangelte es nicht. Danach wurden die Hunde als Nahrung verwendet. Alle machten Gewinn und die Stadt wurde auch noch sauberer.}
{168}{}{...Du behältst die Gewohnheit also bei?}
{169}{}{Na schön, reden wir nicht weiter darüber.}
{170}{}{Der Sheriff weiß Bescheid. Er ist froh, dass ich es tue. Er lässt mir sogar etwas Munition zum Schießen da.}
{171}{}{Nun, wenn der Sheriff höchstpersönlich zum Hundeessen ermuntert, muss die Lage in der Stadt wirklich beschissen sein. Leb wohl.}
{172}{}{Na gut, ich glaube dir.}

#Êâåñò íà ñîáàê - Dog quest
{180}{}{Alle Hunde in der Gegend sind tot.}
{181}{}{Was, wirklich? Gute Arbeit! Hm ... Du musstest wohl etwas Munition dafür aufwenden, was? Hier, ich habe noch etwas Schießpulver übrig. Mehr kann ich dir nicht bezahlen. Jetzt kann ich nachts wieder schlafen. Ich bin wirklich froh, dass du geholfen hast.}
{182}{}{Dann pass auf dich auf.}

{183}{}{Wie lebst du ganz allein in so einer wilden Gegend?}
{184}{}{Ganz gut. Niemand legt sich mit mir an, und ich mich mit niemandem ... Außer mit einem Hunderudel. Die können einem ganz schön auf die Nerven gehen. Besonders nachts, wenn sie mich nicht schlafen lassen. Aber mit ihnen komme ich besser klar als mit Menschen ...}
{185}{}{Hunde machen dir zu schaffen? Ich kann sie loswerden.}
{186}{}{Du musst dich der Welt einfach öffnen. Leb wohl.}
{187}{}{Das ... Das wäre großartig. Aber ich habe irgendwie nichts, womit ich bezahlen könnte.}
{188}{}{Du kannst nicht bezahlen? Kein Problem. Ich helfe dir trotzdem.}
{189}{}{Du kannst nicht bezahlen? Dann lasse ich dich in Ruhe.}

{190}{}{Der ganze Ort ist ein Hundefriedhof!}
{191}{}{Du hast herausgefunden, dass der örtliche Außenseiter Hundefleisch isst.}
{192}{}{Igitt! Was ist das für ein Gestank?}
{193}{}{Das Haus stinkt nach Hundefleisch.}
{194}{}{Und wie soll ich das bekommen?}

#Ïî÷èíêà ïîåçäà - repairing the train
{200}{}{Du hast in der Fabrik gearbeitet. Kommst du auch mit den Computersystemen des Zuges klar?}
{201}{}{[Blickt zur Tür zurück, steht dann auf und versperrt mit seinem Rücken das Fenster] Wo hast du das her? Aus dem Zugdepot?}
{202}{}{Nun ... ja.}
{203}{}{Ist dir das wirklich wichtig?}

{204}{}{Wenn der Sheriff davon erfährt, bekommst du verdammt große Probleme. Das Depot ist Sperrgebiet. Man darf nicht einmal etwas von dort mitbringen.}
{205}{}{Warum diese Verbote?}
{206}{}{Verbote interessieren mich nicht. Ich muss nur dieses Gerät reparieren.}

{207}{}{Ich weiß nicht viel darüber. Aber dort sind viele Leute gestorben. Manche von ihnen haben sich in Plasmaschleim verwandelt. Aber das habe ich dir nicht erzählt.}
{208}{}{Also, weißt du, wie man den Computer repariert?}
{209}{}{Du solltest das nicht auf die leichte Schulter nehmen. Du musst vorsichtig sein, wenn du über die Eisenbahn redest. Dort gehen unheimliche Dinge vor sich.}
{210}{}{Vielleicht könnte ich den Computer reparieren. Aber ich helfe dir nicht. Ich brauche in dieser engen Stadt nicht noch mehr Ärger.}
{211}{}{Hm.}
{212}{}{Kannst du mir also helfen, den Bordcomputer zu reparieren?}
{213}{}{Vielleicht könnte ich den Computer reparieren. Aber ich möchte es mir nicht mit dem Sheriff verscherzen.}
{214}{}{Vertrau mir, ich weiß, was ich tue.}
{215}{}{Na gut, ich überleg's mir.}

{216}{}{Wirklich? Hm ... Ich kann dir wohl vertrauen. Also, hör zu. Dem Computer fehlt wahrscheinlich ein eher unwichtiges, aber dennoch notwendiges Teil. Der Sheriff ist kein Narr, der alte Technik zerstört. Wenn du mir das Werkzeug besorgst, versuche ich, ihn zu reparieren.}
{217}{}{Und ... Wenn es dir nichts ausmacht, besorg mir eine Flasche "Bloody Mary", ja?}
{218}{}{Hier ist eine Flasche Jolly Joe.}
{219}{}{Oh, welch ein Genuss! Danke.}
{220}{}{Ein gewöhnliches Werkzeug reicht, oder? Hier, bitte.}
{221}{}{Hier ist ein Super-Werkzeugkasten. Nimm ihn, wenn du ihn brauchst.}
{222}{}{Gern geschehen.}
{223}{}{Schon gut, danke. Alles ist besser, als in den Ruinen herumzuwühlen.}
{224}{}{Kannst du den Computer jetzt bitte reparieren?}
{225}{}{Wenn ich etwas verspreche, breche ich mein Wort nicht. Gib mir das Ding, ich versuche es.}
{226}{}{Hier. Enttäusch mich nicht!}
{227}{}{Ich komme mit dem Computer zurück.}

{228}{}{Finde heraus, wie man den Zug repariert.}

{229}{}{Es war keine leichte Aufgabe, aber das Gerät funktioniert jetzt. Hier, probier es aus. [Starrt dich eine Weile schweigend an] Das ist doch nicht bloß Neugier, oder? Wohin willst du, wenn das kein Geheimnis ist?}
{230}{}{Ich reise weit. Ein paar Tage Fahrt nach Norden.}
{231}{}{Der Norden? Das ist ein gefährlicher Weg. Dort ist die Natur anders, viel erbarmungsloser. Starke Winde, Kälte, Strahlung. Die Menschen überleben dort nicht lange. Mit dem Zug zu fahren ist wahrscheinlich nicht ganz so gefährlich.}
{232}{}{Woher weißt du das alles?}
{233}{}{Ich bin aus dem Norden hierhergefahren. Aber das ist lange her.}
{234}{}{Gefahren? Auf einem ... Fahrzeug?}
{235}{}{Ja, mit einem Zug. Ich war noch ein Kind. [Etwas aus seiner Erinnerung lässt ihn mitten im Satz innehalten] Das ist aber nicht besonders interessant. Und ich erinnere mich an nicht viel. Das ist zu lange her. Vielleicht hat sich seitdem alles verändert.}
{236}{}{Na gut, mach's gut.}

{240}{}{Du hast gesagt, dein Name ist Stapleton und du kommst aus dem Norden. Wo hast du gelebt – in einem Haus oder einem Bunker?}
{241}{}{Ich glaube, es war ein Bunker. Mit Metallwänden. Viel Licht und Musik ... Und rote Blumen ... Und eine schreckliche Sirene.}
{242}{}{Blumen? Wahrscheinlich sind dort Blumen gewachsen ...}
{243}{}{Wahrscheinlich?! [Er hellt sich auf] Du hast den Bunker also gefunden!?}
{244}{}{Es war nicht nur ein Bunker, sondern ein riesiger Vault. Die Reise war verdammt schrecklich, aber ich habe es überlebt.}
{245}{}{Nein, äh, nein. Mir ist es nur wieder eingefallen.}
{246}{}{Kein Wunder, dass diese Orte gut bewacht werden. Aber was ist jetzt aus diesem Ort geworden?}
{247}{}{Die Bewohner verließen den Vault, als du noch ein Kind warst. Ich habe das Tagebuch eines gewissen Stapleton. Vielleicht war er ein Vorfahr von dir.}

{248}{}{Mein Gott! So viele Jahre sind vergangen! Ich erinnere mich langsam ... Ja! Ich erinnere mich! Überlass mir diese Aufzeichnungen! Das ist etwas sehr Persönliches!}
{249}{}{Wie bezahlst du mich für den Fund?}
{250}{}{Nimm.}
{251}{}{Nein! Ich brauche sie auch.}

{252}{}{Aber ich habe nichts ... Moment, ich kann Schrotflintenmunition herstellen oder dir die Komponenten geben. Es ist nicht viel ... Bitte, sie sind mir so wichtig!}

{253}{}{Na gut, nimm sie. Ich überlasse sie dir kostenlos.}
{254}{}{Gut. Gib mir die Komponenten, dann sind wir quitt.}
{255}{}{Stell etwas Munition her, dann gebe ich dir das Tagebuch.}

{256}{}{Das sind meine Erinnerungen! Deshalb hoffe ich, dass du es dir anders überlegst.}
{257}{}{Das kann ich nicht. Mach's gut.}

{258}{}{Nein! Ich kann sie nicht hergeben!}
{259}{}{Na gut, na gut, reg dich nicht so auf.}

{260}{}{Du kommst dem Geheimnis der Herkunft dieses armen Kerls auf die Spur.}
{261}{}{Danke! Es sind meine Erinnerungen, und ich werde mir jetzt eine Weile diese Tagebücher genau ansehen.}
{262}{}{Gern geschehen.}

#Female character:
{1110}{}{[Der Mann, den du siehst, ist kräftig gebaut und hat ein hässliches Gesicht, dem ein Auge fehlt] Das ist mein Zuhause, ich wohne hier. Bist du sicher, dass du hier richtig bist?}
{1132}{}{Es ist traurig, dass dein Leben so schlecht verlaufen ist. Es tut mir leid, dass ich dich das noch einmal durchleben lasse.}
{1136}{}{Klar. Bis später ... Wanderer.}
{1243}{}{Wahrscheinlich?! [Er hellt sich auf] Du hast den Bunker also gefunden!?}
