{100}{}{Du siehst einen Arbeiter.}
{101}{}{Du siehst einen zwielichtigen Jungen. Als du ihn weiter musterst, kneift er die Augen zusammen und sieht dich an.}
{102}{}{Lass mich in Ruhe!}
{103}{}{Psst!! Warte, bis ich zurück bin ...}
{104}{}{ }
{105}{}{Na, Zeit, hier abzuhauen!}

#First dialogue:
{120}{}{Was brauchst du?}
{121}{}{Sag mir, wer du bist und was du hier machst.}
{122}{}{Ich suche nur jemanden zum Reden. Wie lebt es sich in dieser Stadt?}
{123}{}{Hey, weißt du, was es mit Gilmore auf sich hat? Und was dieser Provo ist?}
{124}{}{}
{125}{}{Ich glaube, ich habe dich mit jemand anderem verwechselt. Ich mach mich dann mal auf den Weg.}

#####################################################################
#
# First dialogue [before theft]
#
#####################################################################

{136}{}{Ah ... Dann wird es dir hier gefallen. Früher hatten wir Probleme, aber jetzt kommt die Stadt wieder auf die Beine. Die Leute werden reicher ... [zwinkert] Ich würde dir also raten, noch ein bisschen hierzubleiben.}
{137}{}{Ah ... Na ja, wenn ich du wäre, würde ich von hier abhauen. Vielleicht nach Vegas. Ehrlich gesagt ist es hier beschissen. Der einzige Grund, warum ich noch hier bin, ist, dass ich das Ödland noch weniger ausstehen kann.}
{138}{}{Ah ... Eine Stadt, nehme ich an. Nichts Besonderes. Die Leute leben einfach hier, das ist alles. Immer noch besser als in Reno, so viel steht fest. Ich bin von dort abgehauen und glaube, dass ich die richtige Entscheidung getroffen habe.}
{139}{}{Na gut, vergiss es.}
{140}{}{Na ja, alle nennen mich den Unverbesserlichen Ned. Frag nicht, warum. Ich bin nur ein Arbeiter, wie viele andere auch. Ich helfe Leuten mit ihrem Kram und verdiene hier und da mal einen Groschen. Obwohl ich manchmal auch ziemlich ... „einträgliche“ Aufträge erledige ... [zwinkert] Wie dem auch sei, ich beschwere mich nicht.}
{141}{}{Provo ist ein verdammtes Drecksloch, das kein vernünftiger Mensch besuchen sollte. Dort leben all die Verbannten, die der Sheriff aus der Stadt gejagt hat. Die meisten hier werden dir sagen, dass sie alle Verbrecher sind, aber da steckt mehr dahinter. Ich habe gehört, dass sie Burton geholfen haben, während des Bürgerkriegs die Dinge zu regeln. Und als er sie nicht mehr brauchte, setzte er sie vor die Tür. Jetzt halten sie sich von Salt Lake City fern, aber ich bin sicher, sie haben einen Groll gegen die Stadt und die ganze Welt. Was Gilmore angeht – der ist ein richtiges Arschloch. Mörder, Vergewaltiger und Dieb. Whip will Leute auf ihn ansetzen, aber ich glaube, er hat Angst, dass sie unterwegs abgeknallt werden.}
{142}{}{Na ja, alle nennen mich den Unverbesserlichen Ned. Frag nicht, warum. Falls du es wissen willst: Ich suche ... „geschäftstüchtige“ Leute für ein paar einfache Aufträge. Hm, du siehst nicht gerade wie der passende Typ aus.}
{143}{}{Na ja, alle nennen mich den Unverbesserlichen Ned. Frag nicht, warum. Falls du es wissen willst: Ich suche ... „geschäftstüchtige“ Leute für ein paar einfache Aufträge. Aber ich glaube nicht, dass du das nötig hast – du hast dir in dieser Stadt schon einen guten Platz gesichert.}

#####################################################################
#
# Getting convinced to steal
#
#####################################################################

{149}{}{Warte! Weißt du, du siehst aus wie ein ganz schön gerissener Bastard. Du weißt, was ich meine? [zwinkert]}
{150}{}{[Öffne überrascht die Augen] Ich habe keine Ahnung, wovon du redest!}
{151}{}{Oh, du hast also meine verborgenen Talente bemerkt. Dann könnten wir doch ein ... gemeinsames Interesse finden, meinst du nicht?}
{152}{}{Äh, weißt du was? Mir gefällt nicht, worauf du hinauswillst. Ich glaube, ich gehe jetzt einfach ...}

{153}{}{Okay, kein Problem. Vergiss, dass ich etwas gesagt habe.}
{154}{}{Warte, was wolltest du sagen?}
{155}{}{Schon besser.}
{156}{}{}

{157}{}{Ach ja? Und was ist damit? [zieht eine Münze aus deiner Tasche, die du zum ersten Mal in deinem Leben siehst] Ich hab's gesehen! Du hast gerade versucht, mich zu bestehlen!}
{158}{}{Was zum ... Das ist eine verdammte Falle!}
{159}{}{Scheiße, du hast mich erwischt, Mann. Ja, ich bin ein Dieb. Die Frage ist: Was machen wir jetzt?}
{160}{}{Ja, ja. Ich verstehe. Aber weißt du ... ich mache dir keinen Vorwurf.}
{161}{}{Oh, wie ehrlich! Aber weißt du ... ich mache dir keinen Vorwurf.}
{162}{}{Was, im Ernst?}
{163}{}{Verdammter Betrüger! Geh mir aus dem Weg!}

{164}{}{Siehst du, ich bin auch ... opportunistisch, genau wie du. [zwinkert erneut]}
{165}{}{Nun ja ... vielleicht.}
{166}{}{Natürlich, ich denke, wir könnten leicht ein gemeinsames Interesse finden.}
{167}{}{Großartig.}
{168}{}{Ich wusste es! Wir beherrschen dieselbe Kunst. Und wo wir gerade von Kunst sprechen ... Hast du etwas auf dem Herzen?}
{169}{}{Nein, nein, vergiss es! Ich bin raus und all das. Tschüss.}
{170}{}{Hm, ich bin interessiert. Erzähl mir mehr.}

{171}{}{[Ohne ein Wort nickt er zum Gebäude auf der anderen Straßenseite]}
{172}{}{Du bist verrückt!}
{173}{}{Gute Wahl!}
{174}{}{Da ist ein Innenhof. Ich frage mich, warum die Händler ihn mit Gerümpel vollgestellt haben. Ich glaube, damit wollen sie Diebe davon abhalten, hineinzukommen. Was meinst du ... Könnte ein *Dieb* hineinkommen?}
{175}{}{Hm. Wo ist der Haken?}
{176}{}{Vielleicht ... Ich weiß nicht.}
{177}{}{Kommen wir gleich zur Sache? Das gefällt mir. Ich erklär dir alles.}
{178}{}{Natürlich.}
{179}{}{Hm ... Ihr Neulinge braucht immer erst eine Erklärung der Grundlagen. Ich versuche, mich kurz zu fassen.}
{180}{}{Wen nennst du hier einen Neuling? Obwohl ... ich höre mir besser an, was du zu sagen hast.}

{181}{}{Zunächst einmal ist es sehr schwierig, allein hineinzukommen. Du musst über den Zaun klettern und dann die Sachen zurückschleppen. Dafür braucht man also jemanden, der einem hilft und die Straße im Auge behält. Eine Sache für zwei Leute.}
{182}{}{Verstanden. Und zweitens?}
{183}{}{Die Straße gegenüber wird ständig von einem verdammten Polizisten patrouilliert. Wir müssen herausfinden, wann wir außer Sichtweite sind. Deshalb braucht man zwei Leute.}
{184}{}{Verstanden ...}
{185}{}{Es gibt noch ein Problem. Wir müssen nachts vorgehen, aber die Straßenlaternen beleuchten die Straße. Ein gewaltiges Risiko, wenn man den Polizisten mit einrechnet. Wir müssen uns etwas einfallen lassen.}
{186}{}{Was soll ich tun?}
{187}{}{Versuch, etwas gegen die Straßenlaterne zu unternehmen. In der Zwischenzeit behalte ich die Lage im Auge und arbeite die Einzelheiten des Plans aus.}
{188}{}{Mir gefällt, wie du denkst! Ich bin dabei!}
{189}{}{Gut. Bis heute Abend.}
{190}{}{Tschüss.}

#Heist beginning
{191}{}{Pst! Auf den Straßen sind noch zu viele Leute. Zu gefährlich.}
{192}{}{Na gut, ich komme später vorbei.}
{193}{}{Sieht nach einem guten Zeitpunkt aus, um loszuschlagen. Was meinst du?}
{194}{}{Ich bin bereit! Zeigen wir diesen Bonzen, wo's langgeht!}
{195}{}{Noch nicht, wir sollten noch etwas warten.}
{196}{}{Du hast dich entschieden, den Diebesjob anzunehmen. Dein erstes Ziel ist es, in den Innenhof des Handelszentrums zu gelangen.}

{197}{}{Warte, ich will eine rauchen.}
{198}{}{Du bist am Schauplatz deines möglichen „Geschäfts“ angekommen.}

#####################################################################
#
# Doing the deed
#
#####################################################################

#Floating dialogue when trying to talk during the job:
{200}{}{Mach langsam. Tu so, als kämst du gerade von der Arbeit nach Hause.}
{201}{}{Entspann dich. Die Bullen merken, wenn du angespannt bist.}
{202}{}{Behalte einfach die Straße im Auge, Partner.}

#Traders are dead
{205}{}{Was für ein Zufall, die Händler wurden gerade abgeknallt, als wir beschlossen haben zu ... Na, du weißt schon.}
{206}{}{Äh ... keine Ahnung! Muss Zufall sein.}
{207}{}{Ich dachte, es wäre einfacher, wenn sie nicht da wären.}
{208}{}{Was zum Teufel ist los mit dir!? Oh Gott. Jetzt sind wir erledigt. Ich will nichts mehr mit dir zu tun haben. Schluss damit. [verschränkt die Arme vor der Brust] – Ich kenne dich nicht.}
{209}{}{Als ob du mich je gekannt hättest. Geh mir aus dem Weg, Versager.}

#Floats when waiting for PC in the courtyard [male char]?
{210}{}{Ach, Scheiße! Wo steckt dieser Arsch!!!}
{211}{}{Wenn er nicht rauskommt ...}
{212}{}{Na los! Komm endlich raus!}
{213}{}{Was soll das, ist das eine Falle?}
{214}{}{Argh! Wo steckt dieser Wichser!?}
{215}{}{Ist das eine Falle?}
{216}{}{Na toll, Scheiße!}
{217}{}{Wo ist er hin?!}
{218}{}{Ich wusste, dass ich ihm nicht trauen kann!}
{219}{}{Hey, du! Ich will nicht im Knast landen!}

#Getting boosted over the fence:
{220}{}{Hör auf, Zeit zu verschwenden! Du musst mir helfen, über den Zaun zu kommen. Kapiert?}
{221}{}{Los geht's.}
{222}{}{Noch nicht, man könnte uns sehen.}
{223}{}{Okay. Warte auf mich. Ich bin gleich zurück.}

{230}{}{Sag mir Bescheid, wenn wir loskönnen, okay?}

#####################################################################
#
# Finishing the job
#
#####################################################################

#Finishing the job, when standing near the fence
{300}{}{Es ist erledigt. Hilf mir hier raus!}
{301}{}{Bist du sicher? Was, wenn ich dich einfach hier lasse?}
{302}{}{Natürlich, nichts wie weg.}
{303}{}{Nein, warte. Es ist zu gefährlich.}
{304}{}{Du bluffst! Vergiss nicht, dass die ganze Beute bei mir ist. Lass mich hier und du gehst leer aus!}
{305}{}{Du hast recht, lass uns abhauen.}
{306}{}{Und trotzdem gehe ich jetzt ...}
{307}{}{Ugh ... Na schön, warte. Was willst du?}
{308}{}{Ich will 75%.}
{309}{}{Was!? Pfft! Leck mich! Ich komme auch ohne deine Hilfe hier raus! Du hast nicht mal Zeit, jemanden zu rufen, bevor ich weg bin!}
{310}{}{Na schön. Das werden wir ja sehen.}
{311}{}{Weißt du, du tust mir leid. Lass uns abhauen.}
{312}{}{Ugh, du ... Willst du mich ausnehmen und dabei saubere Hände behalten? Scheiße, du kannst dir deinen Extranteil sonst wohin stecken. Hilf mir einfach hier raus!}
{313}{}{Schon viel besser. Los geht's.}
{314}{}{Du musst warten. Es ist gefährlich.}
{315}{}{Ich gehe trotzdem. Tschüss.}
{316}{}{Ja, leck mich! Ich komme auch ohne so einen Rotzbengel wie dich klar!}
{317}{}{Wir werden sehen ...}

#End of quest
{320}{}{Puh! Ich dachte schon, ich werde erwischt. Und du? Prima. Scheiße, ich glaube, es wird Zeit, das Geschäft abzuschließen ... Na schön, teilen wir die Beute und gehen getrennte Wege. Also, das Geld, dein Anteil: }
{321}{}{ Prozent. Und was ist mit den Waren?}
{322}{}{Mal sehen, was Lady Fortuna uns beschert hat.}
{323}{}{Du hast mitten in der Stadt einen großen Raubzug durchgezogen.}
{324}{}{Gut, einverstanden. Ich bezweifle, dass die Händler so bald merken, dass sie ausgeraubt wurden. Trotzdem solltest du dich besser eine Weile bedeckt halten. Ach ja – wir kennen uns nicht und waren heute Abend an verschiedenen Orten. Klar?}
{325}{}{Verstanden. Mach's gut, Partner.}

#Thief's floats inside the store
{330}{}{Oh mein Gott!}
{331}{}{Oh-ho!!!}
{332}{}{Es gehört alles mir!}
{333}{}{He-he-he!}
{334}{}{Verdammte Geizhälse!}
{335}{}{Lernt teilen!}
{336}{}{Was euch gehörte, gehört jetzt uns.}
{337}{}{So viel Zeug!}
{338}{}{Mhm!}
{339}{}{Na, na! Was haben wir denn hier!?}
{340}{}{Richtig ... Das brauche ich nicht ... Das ist es auch nicht ...}

#Caught by cop
{350}{}{Du hast den großen Coup vermasselt!}
{351}{}{Na, na, zurück zu den alten Gewohnheiten?}
{352}{}{Äh, hoppla, Boss! Tut uns leid, dass wir dich nicht eingeladen haben ...}
{353}{}{Beim Sheriff kannst du dich entschuldigen.}
{354}{}{Warum hab ich mich nur darauf eingelassen!?}

#Splitting profits
{360}{}{Zeig mir, was du hast.}
{361}{}{[Weiter]}
{362}{}{WAS!? Findest du das nicht ein bisschen viel? Was ist mit den Prozenten?! Na schön, her damit! Sofort! Ich hab meinen Arsch nicht umsonst riskiert ...}
{363}{}{[Weiter]}
{364}{}{Ja, das scheint mir fair. Damit kann ich leben.}
{365}{}{Dann wäre das also beschlossen. Es war mir ein Vergnügen, mit dir zu arbeiten.}
{366}{}{Nein, warte, ich muss mir das erst durch den Kopf gehen lassen.}
{367}{}{Nimm alles. Ich brauche den ganzen Krempel nicht.}

#####################################################################
#
# After theft
#
#####################################################################

#First dialogue after success:
{400}{}{[Du siehst deinen alten Bekannten. Er kann sich kaum noch aufrecht halten, weil er sich ordentlich einen hinter die Binde gekippt hat] He-e-e-e-y! Partner! Setz dich!}
{401}{}{[Gesell dich zu ihm]}

{402}{}{Na, Partner? WIR HABEN'S GESCHAFFT! Hörst du!? WIR HABEN'S GESCHAFFT, ha-ha!}
{403}{}{Ja, ich hör dich. Sollen dich die anderen auch hören?}
{404}{}{Aha. Und ich seh, du hast schon die Hälfte deines Anteils verjubelt.}
{405}{}{Und jetzt?}
{406}{}{Na und? Mach's gut, Partner.}

{407}{}{[Er ist immer noch ein bisschen betrunken] Ah, Partner. Hey, alle zusammen, das ist mein Partner! Wir haben zusammen SO VIEL ERLEBT!}
{408}{}{Sollen das alle hören?}

{409}{}{Ganz ruhig, alles bestens! [fährt mit den Fingern über seine Lippen] Still wie ein Grab. Hihi.}
{410}{}{Ich sehe, du hast es geschafft, hier alles in die Luft zu jagen ...}
{411}{}{Was hast du jetzt vor?}
{412}{}{Na dann, pass auf dich auf.}

{413}{}{Wer, ich? Keine Chance! Anders als manch einer habe ich mich für die kluge Lösung entschieden. Ich hab mein Geld für schlechte Zeiten beiseitegelegt. Das hier? Nur ein bisschen Kleingeld, um die Nerven zu beruhigen. He-he ...}
{414}{}{Beiseitegelegt? Bist du sicher, dass es keiner findet?}
{415}{}{[Setzt eine stoisch gelassene Miene auf und bewegt die Hand] NIEMAND!}

{416}{}{Ah, klingt nach dem Richtigen. Was hast du jetzt vor?}

{417}{}{[Wischt sich Biertropfen vom Kinn] Äh ... Weißt du, in der Stadt ist es nicht sicher. Sie könnten ... Na, du weißt schon? [zwinkert] Hickok ist ein ziemlicher Dreckskerl. Wenn's sein muss, nimmt er sich jeden vor. Also, ich weiß auch nicht. Ich halte mich eine Weile bedeckt – das Geld sollte eine Weile reichen. Später seh ich weiter. Außerdem hatte ich mit meinem Glaswaren-„Geschäft“ immer ein gutes Einkommen. Verstehst du? [zwinkert]}
{418}{}{Glaswaren?! Ist das dein Ernst?!}
{419}{}{Na ja, interessiert mich nicht. Erzähl's jemand anderem, ich bin raus.}

{420}{}{Verdammt, ja!}
{421}{}{Quatsch! Du? Glaswaren?! Wie denn?}
{422}{}{Wie? Ach, na ja, gibt viele Möglichkeiten. Geh zum Beispiel zu einem Nuka-Cola-Automaten ...}
{423}{}{Äh ... Wozu der Automat? Ich glaube, ich verstehe nicht ganz ...}
{424}{}{Nein, nein, hör zu! Das bringt dir sonst keiner bei!}
{425}{}{Äh, entschuldige. Erzähl weiter, ich bin ganz Ohr.}
{426}{}{Also, du gehst ganz unauffällig hin. Fast so, als hättest du einen Kater, damit keiner Verdacht schöpft. Dann steckst du einfach die Hand in deine Tasche und ... holst dieses ... äh ... runde Ding raus und steckst es in den Schlitz.}
{427}{}{Muss man da nicht eine Münze reinwerfen?}
{428}{}{Ja! Genau! Statt einer Münze ... [sieht sich um und vergewissert sich, dass niemand zuhört] nimmst du das Metallding, steckst es in den Automaten und – voilà! Eine Gratisflasche nur für dich!}
{429}{}{Ganz schön raffiniert! Wo krieg ich diese „Dinger“ her?}
{430}{}{Tja, das ist dein Problem. Ich hab die meisten von meinen schon benutzt. Eigentlich kann dir jeder Techniker, dem die Hände nicht aus dem Arsch wachsen, tausend davon prägen. Außer, er findet heraus, wofür sie sind. Obwohl ... Es gibt noch eine andere Methode.}
{431}{}{Noch eine?! Dann raus damit!}
{432}{}{Heh! Einfach so?}
{433}{}{Komm schon, halt nichts vor deinem Kumpel zurück. Du wolltest es mir sowieso erzählen. Also spuck's aus!}
{434}{}{[Schluckt Bier hinunter] Hrmm ... Na schön, ich erzähl's dir. Eigentlich doch nicht. [holt etwas aus seiner Tasche] Hier.}
{435}{}{Was?! Eine Münze mit einem Loch und etwas Seil? Meinst du das ernst?}
{436}{}{Mhm. Steck die Münze in den Schlitz. Der Automat läuft, du schnappst dir die Flasche und ziehst die Münze wieder hoch! [Grinst, als wäre er gerade zum Gouverneur des Staates ernannt worden]}
{437}{}{Was, wenn sie stecken bleibt?}
{438}{}{Ach, kommt vor. Aber das ist ja kein großer Verlust.}
{439}{}{Du bist eine wandelnde Goldgrube, Freund!}
{440}{}{Oh ja, bin ich ... Apropos, du kannst sie behalten! Ich mach mir neue. Jetzt muss ich wohl mit dem Gesicht voran in diesen Salat fallen und ein paar Stunden schlafen.}
{441}{}{Danke, dass du deine Erfahrung mit mir geteilt hast.}
{442}{}{Heh, mach's gut, Idiot. Man sollte seine Erfahrung nicht einfach so hergeben. Heh.}

#Female version:
{1122}{}{Ich suche nur jemanden zum Reden, ich bin neu in der Stadt. Wie lebt es sich in dieser Stadt?}
{1125}{}{Ich glaube, ich habe dich mit jemand anderem verwechselt. Ich mach mich dann mal auf den Weg.}
{1149}{}{Warte! Weißt du, du siehst aus wie eine ziemlich durchtriebene Schlampe. Du weißt, was ich meine? [zwinkert]}
{1157}{}{Ach ja? Und was ist damit? [zieht eine Münze aus deiner Tasche, die du zum ersten Mal in deinem Leben siehst] Ich hab's gesehen! Du hast gerade versucht, mich zu bestehlen!}
{1159}{}{Scheiße, du hast mich erwischt, Mann. Ja, ich bin ein Dieb. Die Frage ist: Was machen wir jetzt?}
{1169}{}{Nein, nein, vergiss es! Ich bin raus und all das. Tschüss.}
{1220}{}{Hör auf, Zeit zu verschwenden. Du musst mir helfen, über den Zaun zu kommen. Verstanden?}
{1360}{}{Na, na, mal sehen, was du draufhast.}

#Floating dialogue when thief waits in courtyard [fem char]
{1210}{}{Ach, Scheiße! Wo ist diese Schlampe!!!}
{1211}{}{Wenn sie nicht rauskommt ...}
{1212}{}{Na los! Komm endlich raus!}
{1213}{}{Was soll das, ist das eine Falle?}
{1214}{}{Argh! Wo ist diese Schlampe!?}
{1215}{}{Was soll das, eine Falle?}
{1216}{}{Na toll, Scheiße!}
{1217}{}{Wo ist sie hin?!}
{1218}{}{Ich wusste, dass ich ihr nicht trauen konnte!}
{1219}{}{Hey, du! Ich will nicht im Knast landen!}

{1354}{}{Warum hab ich mich nur darauf eingelassen!?}
