{100}{}{Du siehst den Organisator.}
{101}{}{Du siehst den Veranstalter öffentlicher Hinrichtungen.}

{102}{}{Ich bin gerade beschäftigt. Lass uns nach der Veranstaltung reden.}
{103}{}{Du wurdest ... gehängt.}
{104}{}{Du hast einen neuen Erfolg freigeschaltet.}

#Ñòàäèÿ 1: Îáúÿâëåíèå ïğåñòóïëåíèÿ
{110}{}{Meine Damen und Herren!}
{111}{}{Heute wird hier etwas Aufregendes geschehen!}
{112}{}{Direkt vor euren Augen ... wird der Gerechtigkeit Genüge getan!}
{113}{}{Diese Person hat Omas Apfelkuchen gestohlen!}
{114}{}{Ein solches Verbrechen ist unverzeihlich!}
{115}{}{Eine trauernde Großmutter hat den Verbrecher gefasst, und jetzt ist er HIER!}
{116}{}{Wir werden sehen, was mit dem Entführer von Omas Kuchen geschieht!}
{117}{}{Er wird vor Qualen zucken, während er 30 Zoll über dem Boden hängt!}
{118}{}{Diese Lektion wird er sich merken und so etwas nie wieder tun!}
{119}{}{Wollt ihr das?!}
{120}{}{WOLLT ihr das WIRKLICH, verdammt noch mal?!}
{121}{}{Für die Oma!}
{122}{}{Für den Kuchen!}
{123}{}{Für die Gerechtigkeit in Salt Lake City!!!}
{124}{}{Es lebe der Sheriff. Und es lebe Salt Lake!}
{125}{}{Doch zuerst hören wir uns die letzten Worte des Verbrechers an ...}

#Ñòàäèÿ 2: Ñëîâî âèñåëüíèêà
{150}{}{Nun, was soll ich sagen!}
{151}{}{Ja, ich bin böse, ich habe Omas Kuchen gestohlen ...}
{152}{}{Ich gestehe!}
{153}{}{Ich bin froh, dass unsere Stadt niemals schläft und kein Verbrecher ihrer Gerechtigkeit entgeht!}
{154}{}{Aber ganz ehrlich! Ich gebe meine Fehler zu! Ich werde es nicht wieder tun!}
{155}{}{Ja, früher habe ich Omas Kuchen gestohlen ...}
{156}{}{... und nicht nur Kuchen!}
{157}{}{Ich habe sogar ... Oh! Es ist mir peinlich, es zuzugeben ...}
{158}{}{Nein! Ich sage es!}
{159}{}{Ich habe ihr Fersenmassagegerät gestohlen und weit weg von der Stadt versteckt!}
{160}{}{Jetzt bereue ich es!}
{161}{}{Ich bin bereit, mich der Gerechtigkeit zu stellen, denn es stimmt!}
{162}{}{Ich glaube an unseren Sheriff!}
{163}{}{Nach dem Hängen betrete ich diesen Pfad *nie wieder*!}
{164}{}{Ich schwöre!}
{165}{}{Und ich hoffe, das tut sonst auch niemand.}
{166}{}{::nickt dem Henker zu, damit er anfängt::}

{200}{}{Hast du gehört? Wie soll er nach diesen Worten weiterleben?}
{201}{}{Jetzt *müssen* wir seinem Leiden ein Ende setzen!}
{202}{}{Hängt ihn auf!}
{203}{}{Mama}
{204}{}{Danke euch allen, ihr könnt gehen.}
{205}{}{Ehrlich gesagt war's großartig! Das sollten wir wiederholen.}
{206}{}{Trotzdem wurde ich gehängt! Ich wusste, dass das passieren würde.}

{210}{}{Hast du gehört? Wie soll sie nach diesen Worten weiterleben?}
{211}{}{Jetzt *müssen* wir ihrem Leiden ein Ende setzen!}
{212}{}{Hängt sie auf!}

#Äèàëîã
{300}{}{Was willst du?}
{301}{}{Was zum Teufel ist hier los?!}
{302}{}{Oh, du bist wohl ein Fremder. Keine Sorge. So amüsieren sich unsere Leute.}
{303}{}{Amüsieren?!}
{304}{}{Ja. Früher haben wir hier tatsächlich Verbrecher gehängt. Noch vor Kurzem. Aber seit Sheriff Burton mit der Unterwelt aufgeräumt und all die Bastarde aus der Stadt gejagt hat, steht der Galgen leer und die Leute in der Stadt langweilen sich.}
{305}{}{Und? Ist euch nichts Besseres eingefallen?}
{306}{}{Genau darum geht's! Die Stadt ist ziemlich langweilig. Und der Galgen ist ein richtiges Ventil.}
{307}{}{Und wer spielt den Gehängten?}
{308}{}{Die Leute melden sich selbst freiwillig und steigen aufs „Podest“. Sie finden das lustig. Sheriff Burton sagt, ein Geständnis für Verbrechen, die man nicht begangen hat, helfe dabei, den Kopf von schmutzigen Gedanken zu befreien.}
{309}{}{Und? Hilft es?}
{310}{}{Vermutlich. Je länger ich in dieser Stadt lebe, desto weniger mache ich mir Sorgen um Verbrechen. Aber das verdanken wir natürlich nicht unseren Aufführungen, sondern dem Sheriff selbst.}
{311}{}{Aber schreckt das die Neuankömmlinge nicht ab?}
{312}{}{Doch. Und das ist gut so. Ohne „unerwünschte Elemente“ bleibt die Stadt ruhiger.}
{313}{}{Hmm. Kann ich die Rolle eines Gehängten übernehmen?}
{314}{}{Das ist alles irgendwie seltsam. Ich muss los.}
{315}{}{Was?}
{316}{}{Ja! Ich will in eurer Show auftreten!}
{317}{}{Schon gut ... Nichts.}
{318}{}{Hmm. Interessant. Wie bist du darauf gekommen? Na gut. Je mehr Shows, desto besser. Aber jeder darf nur einmal auftreten. Du kannst also nicht noch einmal mitmachen.}
{319}{}{Großartig! Fangen wir an!!!}
{320}{}{Eigentlich habe ich es mir anders überlegt ... Äh ... Aufs Hängen kann ich verzichten.}
{321}{}{[zum Henker] Na gut, bring den hier zum Podium. Er ist neu in der Stadt, also lass ihn nicht davonkommen.}
{322}{}{WAS ... Au! Lass mich los!!!}

#Female character:
{1206}{}{Trotzdem wurde ich gehängt! Ich wusste, dass das passieren würde.}
{1320}{}{Eigentlich habe ich es mir anders überlegt ... Äh ... Aufs Hängen kann ich verzichten.}
{1321}{}{[zum Henker] Na gut, bring die hier zum Podium. Sie ist neu in der Stadt, also lass sie nicht davonkommen.}
