{100}{}{Du siehst einen Zuschauer.}
{101}{}{Du siehst einen ganz gewöhnlichen Zuschauer.}
{102}{}{Warte, der Spaß fängt gerade erst an!}

{110}{}{Ja, hängt ihn endlich auf!}
{111}{}{Genug!}
{112}{}{Gebt uns Fleisch!}
{113}{}{Brutale Gerechtigkeit ...}
{114}{}{Mach Schluss!}
{115}{}{Hahaha!}
{116}{}{Macht weiter!}
{117}{}{Na? Wie lange dauert das noch!?}
{118}{}{Fangen wir an!}
{119}{}{Das haben wir schon gehört.}
{120}{}{Ich würde mir etwas Neues einfallen lassen.}