{100}{}{Du siehst ein Kabel.}
{101}{}{Du siehst lose heraushängende Drähte. Es muss einen Grund geben, warum sie herausgezogen und in der Mitte durchtrennt wurden.}
{102}{}{Das sind nur ein paar Drähte. Du weißt nicht einmal, wohin sie führen.}
{103}{}{Mit diesen Drähten ist alles in Ordnung.}
{104}{}{Du verbindest die Drähte und stellst damit die Stromversorgung des Hangars wieder her.}
{105}{}{Es werde Licht, oh heiliger Plutonium!}