{100}{}{Du siehst einen Schachtdeckel.}
{101}{}{Du siehst einen automatischen Schachtdeckel.}
{102}{}{Du siehst einen automatischen Schachtdeckel mit einem Gitter, das verhindert, dass jemand hineingelangt.}

{103}{}{Leider klemmt der Schachtdeckel. Auf die übliche Weise bekommst du ihn nicht auf.}
{104}{}{Muss repariert werden.}
{105}{}{Hier gibt es kein Schloss, das man knacken könnte.}
{106}{}{Dieser Schachtdeckel muss nicht repariert werden.}
{107}{}{Mit bloßen Händen kannst du diese Anlage nicht reparieren.}
{108}{}{Du brauchst ein bestimmtes Werkzeug.}

{109}{}{Deine Fähigkeiten reichen für die Reparatur nicht aus.}
{110}{}{Ja!}
{111}{}{Etwas ist schiefgelaufen. Vielleicht beim nächsten Mal.}
