{100}{}{Der Verkaufsautomat ist außer Betrieb.}
{101}{}{}
{102}{}{Mit bloßen Händen bekommst du nichts aus diesem Automaten heraus.}
{103}{}{Er ist leer.}
{104}{}{Du hast diesen Verkaufsautomaten bereits geplündert und das gesamte Kleingeld herausgenommen.}
{105}{}{Hier lässt sich nichts machen.}
{106}{}{Guter Gedanke, aber die Kasse eines derart robusten Automaten bekommst du mit bloßen Händen nicht auf.}
{107}{}{Du hast das Schloss geknackt und die Rückwand des Automaten geöffnet. Jetzt gehört dir das ganze Kleingeld!}
{108}{}{Ja!}
{109}{}{Du konntest das Schloss nicht knacken.}
{110}{}{Mit Werkzeug hast du die Rückwand des Automaten geöffnet. Jetzt gehört dir das ganze Kleingeld!}
{111}{}{Du hast erhalten }
{112}{}{ Dollar.}