{100}{}{Nicht im Kampf!}
{101}{}{Du blickst zweifelnd nach oben, dorthin, wo das Wasser tropft und der Himmel schwach durch die kleinen Fenster schimmert. Die Wendeltreppe führt in die Dunkelheit, und du kannst nicht einmal ihr Ende erkennen. Was für ein verdammt hoher artesischer Turm! Bis ganz nach oben zu klettern, kostet eine Menge Kraft.}
{102}{}{Ich werde vor Erschöpfung zusammenbrechen, wenn ich mich nicht ausruhe.}
{103}{}{Hinaufklettern und deine Gesundheit aufs Spiel setzen.}
{104}{}{Verlassen.}

{105}{}{Uff! Was für eine Aussicht! Ist Salt Lake wirklich so dreckig?!}
{106}{}{Du stehst oben auf einem außer Betrieb befindlichen artesischen Turm. Die Aussicht von hier ist spektakulär.}
{107}{}{Der Panoramablick vom Turm schärft vorübergehend deine Wahrnehmung.}