{100}{}{Du siehst einen leeren Zeitungsautomaten.}
{101}{}{Du siehst einen Zeitungsautomaten. Darin befindet sich etwas.}
{102}{}{Hier ist nichts.}
{103}{}{Da ist etwas drin, aber die Abdeckung sitzt zu fest, um sie mit bloßen Händen zu öffnen.}

{104}{}{Dein Schlag war nicht kräftig genug, um die Abdeckung zu entfernen.}
{105}{}{Dein Schlag war kräftig genug, um die Abdeckung abzuschlagen.}
{106}{}{Erledigt.}
{107}{}{Mit den Werkzeugen hast du die Abdeckung abgeschraubt.}
{108}{}{Erledigt;}
{109}{}{Mit dem Generalschlüssel öffnest du das Schloss an der Abdeckung.}
{110}{}{Fertig}
{111}{}{Leider konntest du das Schloss nicht öffnen.}
{112}{}{Leider kannst du den Deckel nicht öffnen.}
{113}{}{Das hilft hier nicht.}
{114}{}{Nutzlos.}
{115}{}{Bringt nichts – der Deckel ist bereits offen.}
{116}{}{Du findest 50 Bucks und nimmst sie an dich.}
{117}{}{Unglaublich, dass da noch Geld drin ist ...}