{100}{}{Du siehst Tanks.}
{101}{}{Du siehst große Tanks mit einer übel riechenden Mixtur, aus der bald Nuka-Cola wird.}
{102}{}{Du hast in der Nuka-Cola-Fabrik eine gefährliche Sabotageaktion verübt.}
{103}{}{Die Nuka-Cola-Fabrik wurde sabotiert! Und du hast dabei geholfen.}

{104}{}{Diese Flüssigkeit wurde bereits vergiftet. Eine erneute Injektion bringt nichts.}
{105}{}{Du hast den Tank mit Flüssigkeit vergiftet, aber das reicht nicht. Vergifte noch einen.}
{106}{}{Du siehst große Tanks mit einer übel riechenden Mixtur, aus der Nuka Cola hätte werden können, wenn du sie nicht vergiftet hättest.}
{107}{}{Du hast bereits genug Flüssigkeit vergiftet. Verschwende das Gift nicht.}
{108}{}{Erledigt!}
{109}{}{Dieser Tank ist fertig.}