{103}{}{Nicht während eines Kampfes!}

{110}{}{Hier kannst du mit Nuka-Cola handeln und den Einkauf sowie den Vertrieb abwickeln.}
{111}{}{[Eine neue Ladung Cola kaufen]}
{112}{}{Nuka-Cola aus deinem Rucksack ins Lager bringen}
{113}{}{Nuka-Cola aus dem Lager nehmen}
{114}{}{[Prüfen, wie viele Flaschen noch auf Lager sind]}
{115}{}{[Gehen]}

{120}{}{Derzeit sind keine Waren mehr auf Lager.}
{121}{}{Derzeit befinden sich }
{122}{}{ Flaschen Nuka-Cola in deinem Lager.}
{123}{}{[Zurück]}
{124}{}{[Gehen]}
{125}{}{Deine Waren sind ausverkauft.}

#Ïîêóïêà êîëû
{130}{}{Du hast dein Limit für diesen Monat überschritten. Warte, bis die Fabrik die nächste Warenlieferung für dich produziert hat.}
{131}{}{In diesem Monat kannst du höchstens }
{132}{}{ Flaschen Nuka-Cola kaufen.}
{133}{}{4.000 Flaschen kaufen (kostet 8.000 $).}
{134}{}{3.000 Flaschen kaufen (kostet 6.000 $).}
{135}{}{2.000 Flaschen kaufen (kostet 4.000 $).}
{136}{}{1.000 Flaschen kaufen (kostet 2.000 $).}
{137}{}{500 Flaschen kaufen (kostet 1.000 $).}
{138}{}{100 Flaschen kaufen (kostet 200 $).}
{139}{}{Du hast im Lager bestellt und die erforderliche Anzahl Flaschen zum Großhandelspreis erhalten. Dein Nuka-Cola wurde im Lager eingelagert.}

#Çàãğóçèòü êîëó
{140}{}{Lade das Nuka-Cola in den Behälter.}
{141}{}{5 Flaschen.}
{142}{}{10 Flaschen.}
{143}{}{20 Flaschen.}
{144}{}{30 Flaschen.}
{145}{}{50 Flaschen.}
{146}{}{100 Flaschen.}
{147}{}{Alle Flaschen laden.}
{148}{}{[Gehen]}
{149}{}{[Fertig]}

#Âûãğóçèòü êîëó
{150}{}{Derzeit befinden sich }
{151}{}{ Flaschen Nuka-Cola in deinem Lager.}
{152}{}{}
{153}{}{5 Flaschen nehmen.}
{154}{}{10 Flaschen nehmen.}
{155}{}{20 Flaschen nehmen.}
{156}{}{30 Flaschen nehmen.}
{157}{}{50 Flaschen nehmen.}
{158}{}{100 Flaschen nehmen.}
{159}{}{Alle Flaschen nehmen.}
{160}{}{[Gehen]}
{161}{}{[Fertig]}
{162}{}{Im Lager ist nichts mehr übrig.}
{163}{}{Tut mir leid, du kannst nicht so viel tragen.}
{164}{}{[Alles nehmen, was ich tragen kann]}
