{100}{}{Du siehst ein Terminal.}
{101}{}{Dieses Terminal steuert den Betrieb der Teilsysteme des Pumpensumpfs.}
{102}{}{}
{103}{}{Dieses Terminal ist jetzt nutzlos.}

{106}{}{Fluttore: geschlossen. Druck: normal. Notablass-Terminal: blockiert.}
{107}{}{Notablass-Terminal? Das ist wahrscheinlich das Ding, das vorne hängt. Nein danke, von hier aus ist es einfacher. Also, öffne die Fluttore!}
{108}{}{[Gehen]}