{102}{}{Das kannst du im Kampf nicht benutzen.}
{103}{}{Du brauchst dieses Terminal nicht mehr.}

{190}{}{Die Fässer stehen an ihrem Platz. Ein Funke – und das Hangartor wird in Stücke gesprengt!}
{191}{}{Dieses Terminal dient zur Steuerung des Hangarkrans. Schade, dass es nicht funktioniert, denn es wird nicht mit Strom versorgt.}
{192}{}{Dieses Terminal dient zur Steuerung des Hangarkrans. Deine Versuche, den Kran damit irgendwie zu beeinflussen, bleiben jedoch erfolglos. Irgendwo im Stromkreis des Hangars muss eine Unterbrechung sein.}
{193}{}{[Gehen]}
{194}{}{Am Terminal leuchten verschiedene Lampen auf. Du wischst Staub und Sand von den Kippschaltern und kannst die Beschriftungen erkennen. Ja, du kannst es benutzen.}
{195}{}{[Mit einem Kran die Treibstofffässer zum Tor bewegen]}