#! Not used in 1.0
{100}{}{Das ist eine Luke.}
{101}{}{Eine mächtige Tür mit einem mächtigen Schloss. Sie lässt sich nur mit einem bestimmten Schlüssel öffnen.}
{102}{}{Sie ist verschlossen. Du kannst sie nur mit einem bestimmten Schlüssel öffnen.}
{103}{}{Verschlossen. Ich brauche einen Schlüssel.}
{104}{}{Diese Tür würde sogar einer kleinen Atomexplosion standhalten. Oder vielleicht auch nicht.}

{110}{}{Du schließt diese riesige Luke auf.}
{111}{}{Erledigt!}
{112}{}{Hier ist das nutzlos.}
{113}{}{Die Tür ist bereits offen.}
{114}{}{Nutzlos}
{115}{}{Das hilft hier nicht. Such nach dem Schlüssel.}