{100}{}{Du siehst eine Tür.}
{101}{}{Du siehst eine sehr robuste Tür mit einem schweren Schloss. Selbst Dynamit würde nicht viel ausrichten!}

{102}{}{Die Tür ist verschlossen.}
{103}{}{Das hilft dir hier nicht. Du brauchst einen Schlüssel.}
{104}{}{Die Tür ist bereits offen.}
{105}{}{Du hast diese mächtige Tür geöffnet.}

{106}{}{Hey, du! Weg da!}
{107}{}{Was zum Teufel ist— hey! Ein Dieb! Ich zeig's dir!}
{108}{}{Hey! Geh da nicht rein. Denk nicht mal dran.}
{109}{}{Hah! Schlechte Entscheidung, du diebischer Abschaum!}
