{100}{}{}
{101}{}{}
{102}{}{Das alles gehört dem Mechaniker, der irgendwo in der Nähe ist.}
{103}{}{Während des Kampfes wirst du es nicht brauchen.}
{104}{}{Das ist jetzt nutzlos.}
{105}{}{Was für ein interessantes Ding.}

{110}{}{Auf dem Tisch liegen Teile der verfallenen Powerrüstung.}
{111}{}{[Die Schäden genau untersuchen]}
{112}{}{[Eine erste Analyse der Reparaturmöglichkeiten durchführen]}
{113}{}{[Die Teile in Ruhe lassen]}

#Ïåğâûé ıòàï ïî÷èíêè
{114}{}{Offenbar hatte dieses seltene Stück militärischer Ausrüstung während des Großen Krieges besonderes Pech: Der Helm ist fast völlig zerstört, und der Rückenteil ist zerbeult, einschließlich des Antriebsmoduls. Und natürlich fehlt auch das „spannendste“ Teil – der Prozessor. Um DAS wieder aufzubauen, bräuchte man eine ganze Fabrik ... oder zumindest jede Menge Ersatzteile.}
{115}{}{Um die Powerrüstung wiederherzustellen, musst du nicht nur einige Teile ersetzen, sondern auch sehr gute Kenntnisse in Systemtechnik haben (einfach gesagt: Reparatur und Wissenschaft).}
{116}{}{}
{117}{}{Beginne die erste Reparaturphase – die Wiederherstellung der tragenden Struktur.}

{118}{}{Blind zu arbeiten wird schwierig.}
{119}{}{[Die beschädigte Powerrüstung verwenden]}
{120}{}{[Die Baupläne für die tragende Struktur verwenden]}
{121}{}{[Nichts tun und die Teile auf dem Tisch liegen lassen]}

{122}{}{Nachdem du den ganzen Tag an der Powerrüstung gearbeitet hast, gibt es ein positives Ergebnis: Die tragende Struktur ist wiederhergestellt! Das ist ein großer Schritt nach vorn. Für eine vollständige Reparatur reicht es aber nicht.}
{123}{}{Ugh, das ist wirklich schwierig ...}

#Âòîğîé ıòàï ïî÷èíêè
{130}{}{Beginne die zweite Reparaturphase – die Wiederherstellung der Rumpfdichtigkeit.}
{131}{}{Von der alten Powerrüstung ist nichts mehr übrig, das sich zur Wiederherstellung der Dichtigkeit verwenden ließe. Du musst Ersatz für die Schichten zum Schutz vor Gas und Strahlung sowie für den hermetischen Helm finden.}
{132}{}{[Den Strahlenschutzanzug verwenden]}
{133}{}{[Den Gasschutzanzug verwenden]}
{134}{}{[Den Laborkittelhelm verwenden]}
{135}{}{[Nichts tun und die Teile auf dem Tisch liegen lassen]}

{136}{}{Du hast diesen Teil der Reparatur erfolgreich abgeschlossen.}
{137}{}{Großartig!}

{138}{}{Die zweite Reparaturphase der Powerrüstung ist abgeschlossen! Die Dichtigkeit der Rüstung ist wiederhergestellt.}
{139}{}{Endlich!}

#Òğåòèé ıòàï ïî÷èíêè
{150}{}{Beginne die dritte Reparaturphase – die Wiederherstellung des Energiesystems.}
{151}{}{Die Lage ist komplizierter als erwartet. Die komplexe Innenstruktur der Powerrüstung ist fast vollständig zerstört, insbesondere das autonome System und die CPU. Du musst sie mithilfe der passenden Baupläne ersetzen.}
{152}{}{[Die Baupläne und Ersatzteile für die Reparatur verwenden]}
{153}{}{[Die Baupläne und eine beschädigte Powerrüstung für die Reparatur verwenden]}
{154}{}{Oh, das ist zu schwierig für mich.}
{155}{}{Du drehst die letzte Schraube in die Rüstung und bestaunst den vollständigen Anzug auf dem Tisch. Du gehst ein paar Schritte zurück und bleibst reglos stehen, wie ein Kunstkenner vor einem antiken Gemälde.}
{156}{}{Wunderschön!}
