{100}{}{}
{101}{}{Hey! Dreh woanders durch, du verdammter Psycho!}
{102}{}{Hey! Was machst du da!? Weg da, bevor ich dich in eine Zelle stecke!}
{103}{}{Du wurdest bei einem Akt des Vandalismus erwischt. Das dürfte sich nicht positiv auf deinen Ruf in der Stadt auswirken.}

{104}{}{Diese Straßenlaterne funktioniert nicht.}
{105}{}{Du hast die Kabel kurzgeschlossen, wodurch die Lampen ausgingen.}
{106}{}{Wenn du Techniker wärst, wüsstest du, was zu tun ist.}
{107}{}{Du hast wie ein Rowdy mit einem Stein die Glühbirne einer Straßenlaterne zerschmettert.}

#Æåí ğåïëèêè
{1101}{}{Hey! Dreh woanders durch, du psychotische Schlampe!}
