{100}{}{Du siehst einen Zug.}
{101}{}{Dieser Zug wird sich nicht mehr bewegen – seine letzte Fahrt ist zu Ende.}

{110}{}{Der Zug ist unter dem Dach des Hangars gut erhalten.}
{111}{}{[Zug starten]}
{112}{}{[Situation einschätzen]}
{113}{}{[Zugsysteme überprüfen]}
{114}{}{[Gehen]}

{120}{}{Der Zug scheint funktionstüchtig und abfahrbereit zu sein.}
{121}{}{Der Zug scheint in Ordnung zu sein, aber der Bordcomputer funktioniert nicht. Es ist schwer zu sagen, woran das liegt. Eine fachkundige Wartung ist nötig.}
{122}{}{[Defekten Bordcomputer ausbauen]}
{123}{}{[Funktionsfähigen Bordcomputer einbauen]}
{124}{}{Erledigt.}
{125}{}{Du baust den Bordcomputer ein und drückst erwartungsvoll den Knopf. Der Bildschirm leuchtet hellgrün auf. Du starrst ein paar Minuten auf die Meldung "Systemprüfung ...", bis der Bildschirm schließlich anzeigt, dass der Zug betriebsbereit ist.}
{126}{}{Dieser Zug wurde mit moderner Vorkriegstechnologie gebaut. Die Benutzeroberfläche ist recht einfach, aber selbst wenn du den Zug in Gang bekommst, wird es schwierig sein, gleichzeitig das komplexe Reaktorsystem und andere wichtige Parameter und Anzeigen im Auge zu behalten. Du wirst einen Assistenten finden müssen.}

{130}{}{Der Zug ist abfahrbereit, aber allein schaffst du das nicht. Du musst einen Helfer finden.}
{131}{}{Der Zug ist abfahrbereit, aber du kannst ihn nicht schnell genug beschleunigen, um das Hangartor zu durchbrechen. Du musst einen Weg finden, das Tor zu öffnen.}
{132}{}{Der Zug kann losfahren, aber wohin?}
{133}{}{Der Zug ist abfahrbereit.}
{134}{}{Los!}
{135}{}{Der Zug ist nicht funktionsfähig.}
