{100}{}{Du siehst einen Säufer.}
{101}{}{Du siehst einen gewöhnlichen Passanten, der an der Bar ein wenig zu viel getrunken hat.}
{102}{}{Den Betrunkenen zu bestehlen, wirkt sich negativ auf dein Karma aus.}

#Attempt at shoving
{103}{}{He, du! Ich krieg dich! ...}
{104}{}{Geh ... aus dem Weg ...}
{105}{}{Whoa, der Boden bewegt sich!}

{110}{}{::hurrgh::}
{111}{}{Dieser Trunkenbold kann sich kaum auf den Beinen halten. Du bedeutest ihm nicht viel. Gar nichts bedeutet ihm etwas.}