{100}{}{Du siehst einen Bettler.}
{101}{}{Du siehst einen in Ungnade gefallenen alten Mann, der im Muell wühlt. Er scheint es nicht leicht zu haben.}

{102}{}{Du bist bloß ein Paar Fotzen, die im Wind flattern. Hau verdammt noch mal ab.}
{103}{}{Ich brauche niemandes Hilfe!}

#Floating Dialogue
{109}{}{ }
{110}{}{Ich hab gesehen, wie du mich angesehen hast! Wage es ja nicht, auf mich herabzusehen, du Stück Scheiße!}
{111}{}{Verpiss dich, alter Mann.}
{112}{}{Halt die Klappe! Du bist ein Niemand! Ich war schon hier, bevor dein Daddy überhaupt geboren war!}
{113}{}{Und sieh nur, was aus dir geworden ist. Praktisch ein Vorbild!}
{114}{}{Verdammte Kinder! Ich sag's dir, damals ...}
{115}{}{... als noch Dinosaurier auf der Erde wandelten ...}
{116}{}{... sorgte der Bürgermeister dafür, dass jeder seinen Platz kannte. Typen wie dich schickten wir direkt nach Golgatha!}
{117}{}{Diese Zeiten sind lange vorbei, alter Mann.}
{118}{}{Ich war einmal ein angesehener Mann! Aber jetzt lebe ich auf der Straße, wühle im Muell, und du ... Sieh dich doch an!}
{119}{}{Ha-ha-ha!}
{120}{}{Du lachst dem Tod ins Gesicht!}
{121}{}{Du nimmst mir die Worte aus dem Mund, du alter Fossil. Genau so siehst du aus.}