{100}{}{Du siehst einen „zwielichtigen Mann“.}
{101}{}{Du siehst einen völlig gewöhnlichen Mann von der Straße, der überhaupt nicht verdächtig wirkt.}
{102}{}{Keine Sorge.}

{110}{}{Wow, sieh dir diese Klamotten an! Du bist nicht von hier, oder?}
{111}{}{Hey, hab ich dich nicht in dem anderen Teil von Reno mit diesem ernst dreinblickenden Kerl gesehen? Es ist ... überraschend, dich unter anständigen Leuten zu sehen.}
{112}{}{Na, na, täuschen mich meine Augen? Wenn das nicht noch ein Bewohner dieser wunderschönen Slums ist! Meine Hochachtung!}
{113}{}{Und wer bist du?}

{114}{}{Nur ein weiterer Penner, Sir, wie jeder andere. Ich versuche nur, mich aufzuwärmen. Ich hoffe, das macht Ihnen nichts aus.}
{115}{}{Hör auf, mich zu verarschen! Wer bist du und was willst du in Wrights Gebiet?}
{116}{}{Mein Boss sagt, du musst verschwinden. Das kannst du freiwillig tun oder in einer Kiste.}
{117}{}{Ich weiß nicht, wer du bist, aber du solltest nicht hier sein. Ich zahl dir 300 Bucks, wenn du verschwindest, okay?}
{118}{}{Das macht mir nichts aus. Bleib ... vorerst.}

{119}{}{Wovon reden Sie, Sir?! Ich bin nur ein gewöhnlicher Penner. Sie verwechseln mich bestimmt mit jemand anderem!}
{120}{}{Deine Haut ist viel zu glatt für jemanden von der Straße. Willst du immer noch den Unschuldigen spielen?}
{121}{}{Ich?! Wofür denn?! Ich hab nichts getan! Ich wärme mich nur an einem Fass auf! Bitte, Sir, ich möchte mir nur einmal diese prächtigen Slums ansehen, dann gehe ich wieder.}
{122}{}{[Drück ihn gegen eine Wand] Pass mal auf, Arschloch. Ich weiß nicht, wer dich geschickt hat, aber solange ich für Wright arbeite, lasse ich keinen Abschaum wie dich durchschlüpfen. Verstanden? Und jetzt verpiss dich!}
{123}{}{Oh wow, Sie sind wirklich großzügig, Sir! Für so viel Geld würde ich ... Wenn ich's mir recht überlege, ist das vielleicht das beste Ergebnis.}
{124}{}{Hier ist dein Geld. Ich will dich nie wiedersehen.}
{125}{}{Ist mir egal.}
{126}{}{Bleib hier, ich komme wieder.}
{127}{}{[Du bemerkst die verängstigten Gesichter von Bürgern, die aus Fenstern und von Straßenecken hervorlugen] J-ja, S-Sir, ich werde Sie nicht wieder stören ...}
{128}{}{Allerdings! Und jetzt hau ab.}
{129}{}{[Er sieht dich finster an] Du glaubst, du siehst alles? Wette, du hast auch Augen im Hinterkopf.}
{130}{}{Du glaubst doch nicht wirklich, dass ich darauf reinfalle?}
{131}{}{Haha! Du bist genauso blind wie die anderen. Diese ... Bosse sehen zwar, aber bemerken die einfachen Dinge nicht. Du weißt, was ich meine. Sie sind selbstsicher, arrogant und glauben, alles zu wissen. Aber du bist nur ein Werkzeug. Sie benutzen dich, und du ... benutzt sie wahrscheinlich auch, aber auf andere Weise.}
{132}{}{Wovon redest du?}
{133}{}{Jetzt reicht's! Ich befördere dich zurück in den Muell, wo du hingehörst! [Angreifen]}
{134}{}{Du kannst mich hier auf der Straße windelweich prügeln. Aber damit beweist du nur, dass du genauso ein Stück Scheiße bist wie dein Boss. Wenn du das tust, weiß es in weniger als einer Stunde jeder hier. Wie klingt das? Ja, ich gehe ... ganz still und leise.}
{135}{}{Gut, jetzt mach, dass du wegkommst.}

#Female version
{1114}{}{Nur ein weiterer Penner, Ma'am, wie jeder andere auch. Ich versuche nur, mich aufzuwärmen. Hoffe, das stört Sie nicht.}
{1119}{}{Wovon reden Sie, Ma'am?! Ich bin nur ein gewöhnlicher Penner, Sie müssen mich mit jemand anderem verwechseln!}
{1121}{}{Ich?! Wofür denn?! Ich hab nichts getan! Ich wärme mich nur an einem Fass auf! Bitte, Ma'am, ich möchte mir nur einmal diese prächtigen Slums ansehen, dann gehe ich wieder.}
{1123}{}{Oh wow, Sie sind wirklich großzügig, Ma'am! Für so viel Geld würde ich ... Wenn ich's mir recht überlege, ist das vielleicht das beste Ergebnis.}
{1127}{}{[Du bemerkst die verängstigten Gesichter von Bürgern, die aus Fenstern und von Straßenecken hervorlugen] S-sicher, M-Ma'am, ich werde Sie nicht wieder stören ...}
{1131}{}{Haha! Du bist genauso blind wie die anderen. Diese ... Bosse sehen zwar, aber bemerken die einfachen Dinge nicht. Du weißt, was ich meine. Sie sind selbstsicher, arrogant und glauben, alles zu wissen. Aber du bist nur ein Werkzeug. Sie benutzen dich, und du ... benutzt sie wahrscheinlich auch, aber auf andere Weise.}
