{100}{}{Du siehst Wrights Wache.}
{101}{}{Du siehst eine von Mr. Wrights Wachen.}

{102}{}{Willst du Mr. Wright sprechen? Er ist in seinem Büro.}
{103}{}{Mr. Wright schläft jetzt. Komm morgen früh wieder.}
{104}{}{Der Eingang ist gleich die Straße hinauf.}
{105}{}{Ich behalte dich im Auge.}
{106}{}{Mr. Wright schläft. Weitergehen.}

{107}{}{Du siehst eine von Mr. Wrights Wachen. Die Ähnlichkeit mit Wright selbst ist verblüffend.}

{108}{}{Der Boss ist ... Er ist nicht hier. Verschwinde einfach!}

#Floating dialogue between Chuck and Wright's wife:
{109}{}{ }
{110}{}{Na, hast du mich vermisst?}
{111}{}{Oh, Chuck, du bist es schon wieder ...}
{112}{}{Ich wollte nur mal vorbeischauen und Hallo sagen. Was ist los?}
{113}{}{Hör auf, Chuck. Wir haben darüber gesprochen.}
{114}{}{Ach komm! Wozu braucht er so viele Frauen?}
{115}{}{Ansehen, Chuck. Ansehen und der Wunsch, seine Blutlinie fortzuführen.}
{116}{}{Eine Blutlinie?! Was stimmt denn mit uns nicht?! Ich habe Brüder überall in Reno, und -}
{117}{}{Wag es ja nicht!}
{118}{}{- und er hat mehr Frauen, als irgendein Mann brauchen könnte!}
{119}{}{Du wirst es nicht verstehen. Ihm liegt diese Familie am Herzen. Du denkst nur an dich selbst.}
{120}{}{Ach ja, so edel. Das ist ganz bestimmt Dad! Ein Herz aus Gold!}
{121}{}{Du hast kein Recht, über ihn zu urteilen. Er hat dir das Leben und einen Job gegeben.}
{122}{}{Ich ... Alles, was er mir gibt, ist Geld. Ich will mehr. Ich will dich!}
{123}{}{Nein, Chuck. Das habe ich dir schon gesagt.}
{124}{}{Du brichst mir das Herz!}
{125}{}{Ich habe nie um dein Herz gebeten. Gib mir nicht die Schuld dafür, dass es dir schlecht geht.}
{126}{}{Warum bist du ihm so treu? Ihr seid alle nicht mal halb so alt wie er!}
{127}{}{Wenn du das fragen musst, hast du keine Ahnung, was Treue bedeutet. Aber das hast du ja bereits gezeigt.}
{128}{}{Warum bist du so grausam zu mir?}
{129}{}{Was machst du überhaupt hier? Hast du nicht Dienst?}
{130}{}{Was soll schon passieren? Dad schläft und die Türen werden bewacht.}
{131}{}{In dieser Stadt kann alles passieren.}
{132}{}{Ich bin nur ein paar Schritte von der Tür entfernt! Hier kommt keiner rein.}
{133}{}{Vielleicht. Aber wenn Wright herausfindet, dass du hier bist ...}
{134}{}{Sei vernünftig. Ich kann doch nicht die ganze Nacht neben seiner Schlafzimmertür stehen!}
{135}{}{Versuch, es deinem Vater zu erklären ... Vielleicht gibt er dir ja einen Stuhl. Hihi!}
{136}{}{Grr! Ja, lach nur. Ich versuche, deine Grausamkeit bei einer Flasche Whiskey zu vergessen.}
{137}{}{Heh-hee ...}
{138}{}{::schnüffel:: Was ist das, Apfelkuchen für meinen Vater?}
{139}{}{Ja, mit Liebe gebacken.}
{140}{}{Es wäre wirklich schön, etwas davon zu bekommen ...}
{141}{}{Da ist die Tür. Geh und such dir jemanden, der ihn für dich backt.}
{142}{}{::seufz::}

#Forcing PC from home
{150}{}{Hey, was zum Teufel machst du hier?! Nachts darfst du hier nicht herkommen! Verzieh dich, verdammt noch mal!}
{151}{}{[Geh.]}

#Caught entering bedroom
{152}{}{Stirb, Dieb!!}
{153}{}{Wag es ja nicht, hierherzukommen! Ich male die Decke mit deinem Hirn an!}

{154}{}{Hey, wer hat dich hier reingelassen? Die Leute versuchen zu schlafen! Verzieh dich, verdammt noch mal!}
{155}{}{Heute kommt niemand rein. Komm in einer Woche wieder.}

{156}{}{Willst du Mr. Wright treffen? Leg erst deine Waffen ab.}