{100}{}{Da ist er! Schnappt ihn euch! Zeigen wir diesem Arschloch, was passiert, wenn man sich mit uns anlegt!}
{101}{}{Da ist sie! Schnappt sie euch! Zeigen wir dieser Schlampe, was passiert, wenn man sich mit uns anlegt!}

{106}{}{Da ist er! Schnappt ihn euch! Zeigen wir diesem Arschloch, was passiert, wenn man sich mit uns anlegt!}
{107}{}{Da ist sie! Schnappt sie euch! Zeigen wir dieser Schlampe, was passiert, wenn man sich mit uns anlegt!}
{108}{}{Mit deinen Taten hast du dir viele Feinde in den Slums von Reno gemacht.}