{100}{}{Du siehst Theodore Wright.}
{101}{}{Du siehst den reichen Besitzer der örtlichen Slums und eine einflussreiche Autorität in Reno.}

{102}{}{Lass mich erst zu meinem Tisch kommen, du Höhlenmensch!}
{103}{}{*Schnarch ...*}
{104}{}{Weck ihn jetzt lieber nicht auf.}
{105}{}{Komm zu einer zivilisierten Uhrzeit wieder.}
{106}{}{Dieb! Wachen! Diiieb!!!}

{107}{}{Hm?! Was ... *murmelt*}

#Ïğîáóæäåíèå îò õîæäåíèé ÃÃ ïî êîìíàòå
{110}{}{::streckt sich::}
{111}{}{...hey! Was zum ...}
{112}{}{::dreht sich um::}
{113}{}{Hrrmf ...}

{115}{}{Noch ein schöner Tag in der Hölle.}
{116}{}{Vielleicht schlafe ich heute Nacht tatsächlich mal ...}

#Ïåğâûé ğàçãîâîğ
{130}{}{Halt Abstand. Ich weiß nicht, was mit deinem Gesicht los ist, aber selbst wenn es nicht ansteckend ist, will ich es nicht in meiner Nähe haben.}
{131}{}{Verstehe, Mr. Wright. Wir können von hier aus reden.}
{132}{}{[Niest in seine Richtung] Oh, Mr. Wright, ich wollte Ihnen schon immer die Hand schütteln.}

{133}{}{Ich bin überrascht, dass eine so ... wichtige Person Zeit für mich hat. Wie kann ich dem einzigen Gesetzeshüter weit und breit helfen, Sheriff?}
{134}{}{Jeder braucht irgendetwas von mir ... Was führt dich her?}
{135}{}{Hast du meinen ... Auftrag erledigt?}
{136}{}{Schön, dich zu sehen. Aber vergiss nicht, wo dein Platz ist.}
{137}{}{Nichts.}
{138}{}{Ich wollte nur Hallo sagen.}
{139}{}{Ich sollte mich auf den Weg machen.}

#Ïîïûòêà íàïğîñèòüñÿ íà ğàáîòó
{140}{}{Mr. Wright, ich suche Arbeit. Ich habe viel von Ihnen gehört. Vielleicht können wir einander helfen?}
{141}{}{[Er mustert dich von oben bis unten und denkt nach] Weißt du, was in dieser Stadt wichtiger ist als ein dickes Portemonnaie oder eine schnelle Knarre?}
{142}{}{Was denn, Mr. Wright?}
{143}{}{Mir ist nicht nach Rätseln zumute. Hast du Arbeit für mich, ja oder nein?}
{144}{}{Ja, Mr. Wright. Es ist der Ruf, nicht wahr?}

{145}{}{Vorsätzliche Ignoranz. [er schnaubt verächtlich] Verschwinde.}
{146}{}{[Verschwinde]}

{147}{}{Dein Ruf. Ganz gleich, wie viel Geld du hast oder welche Waffe du trägst: Was dir fehlt, ist ein guter Ruf. In meinen Slums kennt dich niemand und niemand kann dich empfehlen. Und ich vertraue meinen Leuten. Wenn du Arbeit willst, zeig mir die Ergebnisse deiner Arbeit ... die man beurteilen kann.}
{148}{}{Sie haben wirklich noch nie von mir gehört, Mr. Wright? Ich habe in Reno schon einiges geleistet.}
{149}{}{In Ordnung, Mr. Wright.}

{150}{}{Pah. Es ist mir völlig egal, was andere in New Reno von dir halten. Mein Reich ist hier, in den Slums.}
{151}{}{Hmm ... [er mustert dich erneut, als würde er etwas Neues an dir erkennen, dann nickt er] Vielleicht hast du etwas drauf. Meine Leute sprechen in höchsten Tönen von dir.}
{152}{}{Heißt das, Sie haben Arbeit für mich?}
{153}{}{[Er hebt eine Augenbraue] Du denkst schneller als die meisten in dieser Stadt. Und ja, ich spreche von deinem Ruf. Sag mir, wer kann dich als zuverlässigen Mitarbeiter empfehlen?}
{154}{}{Die Leute in den Slums haben viel Gutes über mich zu sagen.}
{155}{}{Ich war in anderen Teilen der Stadt aktiv. Sie haben doch bestimmt schon von mir gehört.}
{156}{}{Äh, also, ich bin noch nicht lange in der Stadt, und ...}
{157}{}{Dann haben wir nichts zu besprechen. Die Tür ist dort drüben.}
{158}{}{[Gehen]}
{159}{}{[Er nickt] Vielleicht hast du etwas drauf.}

{160}{}{Eins sage ich dir ganz klar: Die Wrights sind eine Familie mit Würde. Glaub ja nicht, dass du durch diese Gelegenheit zu einem von uns wirst. Merk dir: Du arbeitest für uns, du *hilfst* uns nicht. Wage es nicht einmal, dieses Wort zu benutzen. Wir sind keine Bettler, wir brauchen keine Almosen. Verstehst du mich?}
{161}{}{Ich verstehe, Mr. Wright.}
{162}{}{Sehr gut. [er lehnt sich in seinem Stuhl zurück und verschränkt die Finger auf dem Bauch] Ich habe ein paar Aufträge für einen Mann wie dich ... Für jemanden, der nicht von hier ist. Ich bezahle gut – solange die Arbeit ordentlich erledigt wird.}
{163}{}{Ich höre.}

{164}{}{Ich habe von eurem Vertrag mit den Prospektoren gehört. Du bist mit ihren Ergebnissen nicht zufrieden, stimmt's?}
{165}{}{Bin ich nicht. Sie verschwinden monatelang, halten ihre Termine nicht ein – und glauben, damit durchzukommen? Nein, das war's für sie. Ich suche einen Profi. Jemanden, auf den man sich verlassen kann. Jemanden ... Loyalen.}
{166}{}{Ich kann dieser Profi sein.}
{167}{}{Äh, viel Glück dabei. Tschüss.}

{168}{}{Vergiss nicht, welchen Platz du hier hast! Hrm ... [er reibt sich den Nacken]}

{169}{}{Ich bin froh, dass wir uns kennengelernt haben, Sheriff. Aber vergiss nicht, für wen du arbeitest.}

{170}{}{Geh nach Uranium City. Ich will einen umfassenden Bericht über die Lage in der Mine ... MEINER Mine.}
{171}{}{Ich werde Nachforschungen anstellen und zurückkommen, Mr. Wright.}
{172}{}{Du wirst bezahlt, wenn der Auftrag erledigt ist. Du kannst jetzt gehen.}
{173}{}{[Weggehen.]}

{174}{}{Wegen des Auftrags ...}
{175}{}{Warum hast du deine Leute nicht schon früher dorthin geschickt?}
{176}{}{Ich brauche meine Leute hier ... Aber das geht dich nichts an.}
{177}{}{Verstehe.}

{180}{}{Ich höre.}
{181}{}{Äh ... Eigentlich nichts.}
{182}{}{Dann geh wieder an die Arbeit! Reiz meine Geduld nicht. Ich könnte eine Schlange von Leuten vor der Tür haben, die deinen Job wollen, bis hin zu Lucianos Ranch!}
{183}{}{[Gehen]}

{184}{}{Ich bin von Uranium City zurück.}
{185}{}{Erzähl mir alles.}
{186}{}{Ein Einheimischer namens Nelson hat jetzt das Sagen. Er versucht, dir die Mine abzunehmen.}
{187}{}{Ein zwielichtiger Kerl aus dem Hub versucht, sich deine Mine unter den Nagel zu reißen. Er scheint es ernst zu meinen ... Und gefährlich zu sein.}
{188}{}{Die Arbeit ist vollständig zum Erliegen gekommen, und die meisten Bergleute haben die Stadt verlassen. Die Leute fragen sich, wem die Mine wirklich gehört und wer sie wieder in Betrieb nehmen wird.}
{189}{}{Irgendein gefährlicher Mutant in der Mine hat die Arbeiter vertrieben. Die meisten von ihnen haben die Stadt verlassen.}
{190}{}{Was weißt du noch?}
{191}{}{Das ist fürs Erste alles. Ich komme wieder, wenn ich mehr herausgefunden habe.}

{192}{}{Genug. Ich weiß genug, um meine nächsten Schritte zu planen. Ich kann es mir nicht leisten, die Mine zu verlieren ... Aber zuerst, hier ist dein Geld: 200 $.}
{193}{}{Das ist alles? Mr. Wright, seien Sie ehrlich zu mir: Sie sind pleite, oder?}
{194}{}{Vielen Dank, Mr. Wright! Das weiß ich zu schätzen!}

{195}{}{Es wird noch mehr kommen, wenn du lange genug durchhältst. Du hast bewiesen, dass man dir mehr Arbeit anvertrauen kann.}
{196}{}{Verstehe, Mr. Wright. Was war das mit der zusätzlichen Arbeit?}

{197}{}{Mäßige deinen Ton! Dieser Bandenkrieg hat die Wirtschaft von New Reno an den Rand des Zusammenbruchs gebracht! Er hat meiner Familie fast alles genommen, was wir uns erarbeitet haben! Ich habe jahrelang für meinen Besitz gearbeitet. Ich werde nicht zulassen, dass man ihn mir wegnimmt!}
{198}{}{Ich brauche ein Druckmittel, damit meine Mine MEINE bleibt. Die Mine braucht viele Ressourcen, aber vor allem Sprengstoff. Die Vorräte dort müssen inzwischen aufgebraucht sein.}
{199}{}{Woher bekommen Sie den Sprengstoff?}
{200}{}{Ich habe ein paar Prospektoren angeheuert, die Sprengstoff aus einer alten Militärbasis holen sollten. Sie ... sind verschwunden. Was sehr ärgerlich ist. Jetzt muss ich mich mit ihren Familien auseinandersetzen. Verstehst du, wie ... heikel die Lage ist?}
{201}{}{Was soll ich tun, Mr. Wright?}
{202}{}{Mir ist egal, wie, aber ich will, dass der Auftrag erfuellt wird. Finde heraus, was mit meinen Prospektoren geschehen ist.}
{203}{}{Ich kümmere mich darum, Mr. Wright.}
{204}{}{Na gut, ich werde sehen, was ich tun kann.}
{205}{}{Sprich zuerst mit der Familie Gate. Sie muss etwas wissen. Sie lebt in den Slums vor dem Hotel.}
{206}{}{Ich mache mich auf den Weg.}

{207}{}{[Er durchbohrt dich mit einem Blick voller Verachtung und Abscheu] Ich beschäftige keine Vergewaltiger und Kindermörder. Ich kann mich nicht entscheiden, ob meine Wachen dich erschießen sollen oder ob ich das Vergnügen haben soll, es selbst zu tun. Du solltest verschwinden, bevor ich mich entschieden habe.}
{208}{}{[Schweigend weggehen]}

#Êâåñò íà âîçâğàò øàõòû
{210}{}{Wegen der Prospektoren ...}
{211}{}{Wo ist mein Sprengstoff?}
{212}{}{In Uranium City. Nelson hat ihn.}
{213}{}{Ich habe ihn hier, Mr. Wright.}
{214}{}{Ich weiß es nicht. Aber ich habe die Prospektoren gefunden.}
{215}{}{Verschwende nicht meine Zeit! Mich interessiert nur der Sprengstoff. Mir ist egal, wer ihn bekommt, solange er zu *mir* gebracht wird!}
{216}{}{Dann kümmere ich mich darum.}
{217}{}{Was?! Du Schwachkopf! Diese Sprengstoffe sind mein Druckmittel gegen diese Stadt! Hol sie um jeden Preis zurück! Wenn du diesen Nelson töten musst, dann tu es. Los, geh jetzt. Wenn ich dich das nächste Mal sehe, hast du gefälligst meine Sprengstoffe dabei.}
{218}{}{[Weggehen.]}
{219}{}{Endlich. Solange ich die hier habe, kann ich den Bergleuten dort meine Bedingungen diktieren. [er übergibt die Sprengstoffe einem Wachmann] Nun zur Bezahlung. Wer hat diese Sprengstoffe aus dem Militärstützpunkt geholt?}
{220}{}{Die Prospektoren, Mr. Wright. Sie haben die Sprengstoffe geholt. Sie baten mich nur, sie abzuliefern, weil sie Angst vor Ihnen haben.}
{221}{}{Ich musste alles selbst erledigen, Mr. Wright. Ich habe sogar den Vertrag hier. Es wäre nur fair, wenn Sie mich bezahlen.}
{222}{}{Hm. Du hättest lügen und behaupten können, du hättest sie von diesem Stützpunkt geholt, aber das hast du nicht. Ehrlichkeit weiß ich zu schätzen. Jedenfalls, hier ist dein Lohn für den Auftrag.}
{223}{}{Danke, Mr. Wright.}
{224}{}{Das überrascht mich nicht. Ich bin von Unfähigen umgeben. Ich muss Maßnahmen gegen die Familien der Prospektoren ergreifen. Deine Arbeit wird angemessen bezahlt.}
{225}{}{Ich musste alles erledigen, Mr. Wright. Es wäre nur fair, wenn Sie mich bezahlen.}
{226}{}{Du könntest lügen. Vielleicht haben sie die Sprengstoffe geholt und du hast sie mir nur gebracht. Aber der Auftrag ist erledigt, du bist hier und sie sind es nicht, also bekommst du die Belohnung.}
{227}{}{Ich brauche mehr Sprengstoffe, um meine Mine den Usurpatoren in Uranium City wieder abzunehmen. Sag mir, wer leitet die Mine jetzt?}
{228}{}{Irgendein Kerl aus dem Hub namens Lewis Birch. Er scheint ein harter Brocken zu sein.}
{229}{}{Nelson, einer von hier.}
{230}{}{Die Arbeit ist vollständig zum Erliegen gekommen, und die meisten Bergleute haben die Stadt verlassen. Die Leute fragen sich, wem die Mine wirklich gehört und wer sie wieder in Betrieb nehmen wird.}
{231}{}{Dann schaff ihn aus dem Weg. Diese Mine gehört mir und nur mir. Alles, was sie heute ist, verdankt sie meiner Unterstützung.}
{232}{}{Ich kümmere mich darum.}
{233}{}{Nach Abschluss wirst du bezahlt. Wir sind fertig.}
{234}{}{[Gehen]}
{235}{}{In dem Fall musst du Uranium City daran erinnern, warum es überhaupt existiert. Jeder dort ist nur wegen meiner Investitionen dort. Du hast Nelson erwähnt ... Ich erinnere mich an ihn. Er war ein guter Arbeiter in der Mine. Jetzt versucht er, sie mir wegzunehmen. Ich will, dass er beseitigt wird.}
{236}{}{Niemand kann Ihren Anspruch auf die Mine noch anfechten, Mr. Wright.}
{237}{}{Gut. Hier ist deine Bezahlung. Wenn du mich angelogen hast, solltest du besser nie wieder in diese Stadt zurückkehren.}
{238}{}{Keine Lügen, Mr. Wright.}

#Ğàáî÷èå èç Óğàí-Ñèòè
{250}{}{Ich suche die vermissten Bergleute aus Uranium City.}
{251}{}{Ich würde dir raten, auf den Muellhalden nachzusehen, wo sie hingehören.}
{252}{}{Ich suche Joseph. Er leitete die Minenmannschaften.}
{253}{}{Ich suche Carl. Er betreute die Werkbank.}
{254}{}{Ich suche Michael, einen Lieferanten.}
{255}{}{Danke, das ist alles, was ich wissen muss.}

{256}{}{Dieser nutzlose Schwachkopf hätte niemals irgendjemanden leiten dürfen. Ich habe ihn an Olivers Ranch in die Sklaverei verkauft. Vielleicht lernt er endlich etwas über Führung, wenn er selbst davon betroffen ist.}
{257}{}{Dieser halbgescheite Nigger weiß gar nicht, wie viel Glück er hat. Ich kann ihn nicht bestrafen, bis ich einen geeigneten Ersatz finde ... Und das ist nicht leicht. Bis dahin lebt er mit seiner Familie in meinen Slums vor dem Silver Legacy-Hotel.}
{258}{}{Dieser Mann gibt dem Wort „nutzlos“ eine neue Bedeutung. Er hatte nichts, was ich ihm hätte abnehmen können. Nicht einmal die Sklavenhändler wollten ihn. Ich habe ihn auf die Straße gesetzt – wahrscheinlich ist er inzwischen von Hunden oder seinen Bettlerkollegen gefressen worden.}
{259}{}{[Gehen]}

#Ïğîáëåìà ñ ìèññèñ Êëîâåğ
{260}{}{Eine Bewohnerin deiner Slums, Mrs. Clover, ist zum Opfer der Schulden eines anderen geworden. Wie stehst du dazu?}
{261}{}{Wieder ein Problem. Mrs. Clover ist dank der Einnahmen ihres Restaurants eine verlässliche Geldquelle, daher liegt es in meinem Interesse, sie zahlungsfähig zu halten. Andererseits liegt es nicht in meinem Interesse, Schulden zu erlassen ... Ich nehme meinen Anteil, egal, wer dafür bezahlt. Ich werde diese Angelegenheit aus der Ferne sehr genau beobachten.}
{262}{}{Verstanden. Reden wir über etwas anderes.}
{263}{}{Das ist alles, was ich wissen musste. Auf Wiedersehen, Mr. Wright.}

#Êâåñò íà ñòğàííîãî òèïà â òğóùîáàõ
{270}{}{Deine Arbeit in Uranium City ist getan. Meine Söhne übernehmen von hier an ... wenn wir bereit sind. Du hast einen weiteren Auftrag.}
{271}{}{Ich höre.}
{272}{}{Man hat mir von einem seltsamen Mann berichtet, der in meinen Slums herumschnüffelt. Ich kenne ihn nicht, aber in meinem Gebiet darf es keine Geheimnisse vor mir geben. Geh zur Ostseite der Slums und kümmere dich um ihn. Vermeide möglichst jeden Aufruhr, aber tu, was immer nötig ist, um den Auftrag zu erledigen.}
{273}{}{Ich bin unterwegs, Mr. Wright.}
{274}{}{Ich habe mich um den Fremden gekümmert. Offenbar hat er die Elendsviertel beobachtet, aber ich konnte nicht mehr herausfinden.}

{275}{}{Ich dachte mir, dass er früher oder später auftauchen würde. Das erklärt die Berichte, die ich erhalten habe.}
{276}{}{Hast du erwartet, dass jemand die Elendsviertel ausspioniert?}
{277}{}{Ich werde beobachtet. Das weiß ich. Ich wollte nur sehen, wie du mit der Situation umgehst. [seine Lippen verziehen sich zu einem kleinen, aber sehr selbstzufriedenen Grinsen] Du wurdest ebenfalls beobachtet.}
{278}{}{Jeder beobachtet jeden ... Was nun?}
{279}{}{Nun, deine Bezahlung. [er zählt das Geld ab] Das war dein letzter Auftrag. Von jetzt an brauche ich jemanden, der klüger ist als du. Belästige mich nicht wieder.}
{280}{}{Nun, deine Bezahlung. [er zählt das Geld ab] Das war dein letzter Auftrag. Dein Ruf in den Elendsvierteln macht klar, dass ich mich nicht auf dich verlassen kann. Die Tür ist dort drüben.}
{281}{}{Nun, deine Bezahlung. [er zählt das Geld ab] Du hast gute Arbeit geleistet. Du hast bewiesen, dass du vertrauenswürdig bist. Du bist bereit für anspruchsvollere ... heikle Aufträge.}
{282}{}{Ich höre, Herr Wright.}
{283}{}{Du solltest inzwischen wissen, dass in Reno ein Krieg tobt. Im Moment herrscht Ruhe, was mir zugutekommt, aber meine Söhne und ich werden beobachtet. Allein zu handeln wäre zu gefährlich. Mir bleibt keine andere Wahl, als mich mit meinem alten Feind zu verbünden – Oliver Luciano.}
{284}{}{[Weiter]}
{285}{}{Geh zu seiner Ranch und überbring ihm mein Angebot eines Bündnisses. *Höflich.*}
{286}{}{Darf ich ein paar Fragen stellen, Herr Wright?}
{287}{}{Ich bin schon unterwegs, Herr Wright.}

{288}{}{Ich mache keine Geschäfte mit Gangstern. Ich kann Mitarbeiter mit geteilter Loyalität nicht gebrauchen.}
{289}{}{Wow, die Nachricht verbreitet sich schnell ...}

{290}{}{Wenn es sein muss.}
{291}{}{Noch eine Frage, wenn ich darf.}
{292}{}{Danke, Herr Wright. Das war alles, was ich wissen musste.}
{293}{}{Warum habt ihr die Uranium City-Mine gesichert, wenn ihr sie nicht wieder in Betrieb nehmen wollt?}
{294}{}{Das werde ich ... irgendwann. Im Moment reicht es mir zu wissen, dass ich sie unter Kontrolle habe. Ich habe derzeit größere Sorgen, aber ich kann nicht zulassen, dass sie in die Hände anderer fällt.}
{295}{}{Du bist pleite, oder?}
{296}{}{Das ist eine unverblümte Frage, aber Geschäftsleute schätzen klare Worte. Meine Familie ist nicht mehr so wohlhabend wie früher, aber wir haben ... genug.}
{297}{}{Wie wurde Oliver Luciano zu deinem Feind?}
{298}{}{Das war in einem anderen Reno als diesem hier. Während seiner Blütezeit, vor über zehn Jahren, herrschte hier Frieden. Doch die Stadt wuchs über ihre Möglichkeiten hinaus, und wir waren gezwungen, uns gegeneinander zu wenden. Dadurch bekam Big Louie die Chance, uns alle zu verwüsten und seine Hunde die Reste auflesen zu lassen. Jetzt muss ich mich mit meinem Feind verbünden, um den Krieg eines anderen zu überleben. Eine bittere Ironie, nicht wahr?}
{299}{}{Darf ich dir ein paar Fragen zur aktuellen Lage stellen, Mr. Wright?}

{300}{}{Ich habe schlechte Nachrichten. Oliver Luciano ist tot.}
{301}{}{Ich habe Luciano dein Angebot überbracht. Er ist bereit, dich anzuhören – persönlich.}
{302}{}{Auf welcher Seite stehst du in diesem Krieg?}
{303}{}{Auf meiner eigenen. Politik interessiert mich nicht, und ich habe nichts zu gewinnen, aber diese Gangster werden nicht aufhören, bis ihnen ganz Reno gehört ... oder sie sterben.}
{304}{}{Ich habe Luciano dein Angebot überbracht, aber er hat abgelehnt. Das tut mir sehr leid, Mr. Wright.}
{305}{}{Ich habe Luciano dein Angebot überbracht, aber er hat abgelehnt.}

#Êîëëåêöèÿ
{308}{}{Das Museum bleibt bis auf Weiteres geschlossen. Ich wurde kürzlich ausgeraubt und werde nicht zulassen, dass die Relikte einer großen Ära für das Drogengeld irgendwelchen Abschaums verhökert werden.}
{309}{}{Das ist schade.}
{310}{}{Mr. Wright, ich habe viel über Ihre Sammlung von Dingen aus der Vorkriegszeit gehört. Können Sie mir mehr darüber erzählen?}
{311}{}{Ich sammle Relikte aus dem alten Amerika. Sie sind mein Denkmal für die reiche Kultur des Landes, das einmal war ... den Ort, an dem meine Familie hätte geboren werden sollen, statt auf der Asche zu sitzen, in der wir heute leben. Zur Sammlung gehören eine Jazztrompete, ein Kartenspiel, Fotos aus verschiedenen Epochen und vier volle Schränke mit allerlei amerikanischen Erinnerungsstücken ...}
{312}{}{aber darum musst du dich nicht kümmern. Das wäre ohnehin nichts für dich.}
{313}{}{Die Türen meines Museums bleiben den einheimischen Grobianen verschlossen, die Kultur nicht erkennen würden, selbst wenn sie ihre Hütten damit zupflastern und an ihrer Stelle eine Kunstgalerie errichten würden. Aber du hast mir gute Dienste geleistet. Vielleicht kann ich dich mit einer Führung erleuchten.}
{314}{}{Nein? Nun, vielleicht änderst du später deine Meinung.}
{315}{}{Sie wären überrascht, wie sehr mich Dinge aus der Vorkriegszeit interessieren, Mr. Wright. Ich würde Ihre Sammlung liebend gern sehen.}
{316}{}{Ich würde Ihnen gern alles zeigen, aber jetzt gerade nicht. Entschuldigen Sie die Störung.}
{317}{}{Schauen Sie, aber fassen Sie nichts an. Folgen Sie mir. [er stöhnt, erhebt sich aus seinem Sessel und geht zur Schlafzimmertür]}
{318}{}{[Eine Führung machen.]}
{319}{}{...Sehen Sie jetzt, wie viel wir verloren haben? Dies war ein großartiges Land, unsere Stadt auf dem Hügel ... Und das könnte es immer noch sein, wären seine Bewohner nicht so habgierig und selbstsüchtig.}
{320}{}{Vielen Dank für die Führung, Mr. Wright. Das war sehr lehrreich!}

#Òğóáà äæàçîâàÿ
{321}{}{Auf der Straße heißt es, Sie besitzen eine Jazztrompete, Mr. Wright.}
{322}{}{Erinnern Sie sich an die Jazztrompete in Ihrem Museum?}
{323}{}{Sie ist das Prunkstück meiner Sammlung von Americana aus der Vorkriegszeit. Sie bedeutet mir sehr viel.}
{324}{}{Warum ist sie so wichtig?}
{325}{}{Steht sie zum Verkauf?}
{326}{}{Mr. Wright, es ist sehr wichtig, dass ich sie ihrem früheren Besitzer zurückbringe.}
{327}{}{Ich sehe, wie wichtig sie Ihnen ist. Ich werde Sie nicht noch einmal damit behelligen.}
{328}{}{Sie gehörte einem Musiker, der vor zehn Jahren im Club gespielt hat. Seine Band ist Teil der Geschichte von Reno. Dort hat Big Louie seine Karriere „begonnen“ – ja, derselbe, der dieser Stadt so viel Leid gebracht hat. Seine Band war für Reno eine seltene Quelle von Kunst und Kultur ... Doch der Bürgerkrieg hat sie zerschlagen.}
{329}{}{Ich würde sie nur ungern hergeben ... Aber alles hat seinen Preis. 1000 $.}
{330}{}{So edel das auch klingt, ich kann ein Stück Renos Geschichte nicht einfach wegen der Gefühle eines Einzelnen hergeben.}
{331}{}{Dann kaufe ich sie sofort.}
{332}{}{Mr. Wright, Sie kennen mich doch besser. Diese Antiquität kann wieder Leben und Kultur hervorbringen! Ich habe vor, eine neue Jazzband zu gründen und den Menschen Kunst zu bringen!}
{333}{}{Abgemacht. [er steckt das Geld ein, geht in sein Schlafzimmer und kommt kurz darauf mit der Trompete zurück] Gut, dass Sie gerade jetzt gekommen sind. Zu jedem anderen Zeitpunkt hätte ich mich geweigert, sie zu verkaufen – für jeden Preis.}
{334}{}{Danke.}
{335}{}{Es ist lange her, dass ich mich so inspiriert gefühlt habe. Na gut ... ich vertraue dir. Du kannst die Trompete haben. Der Zukunft zuliebe.}

#Âñòğå÷à ñ Ëó÷èàíî
{350}{}{Ich bin überrascht. Ich dachte, er wäre einer der bestbewachten Männer in ... Na ja, spielt keine Rolle. Danke, dass du ein zuverlässiger Angestellter warst, aber ich habe keine Arbeit mehr für dich. Meine Söhne können sich auf absehbare Zeit um alles kümmern.}
{351}{}{Leb wohl.}
{352}{}{Gut ... Vielleicht gibt es für Reno doch noch Hoffnung. Hier ist dein Lohn. Von jetzt an hängt alles von mir ab. Ich brauche deine Dienste nicht mehr. Vielleicht hat Luciano Arbeit für dich – ich erwarte, dass er in Zukunft viel zu tun haben wird.}
{353}{}{Verstehe. Das ist bedauerlich, aber ich mache dir keinen Vorwurf. Luciano ist ein vorsichtiger Mann und vertraut anderen nicht leicht. Jedenfalls habe ich keine Arbeit mehr für dich. Meine Söhne können sich auf absehbare Zeit um alles kümmern.}
{354}{}{Warte! Vielleicht könnte ich ihn umstimmen?}
{355}{}{Du hattest deine Chance bereits. Ich glaube nicht, dass ein weiterer Versuch etwas ändern würde. Trotzdem habe ich nichts zu verlieren, also kannst du es ruhig versuchen.}
{356}{}{Du hast recht, daraus wird einfach nichts. Lassen wir die Sache auf sich beruhen.}
{357}{}{Diesmal werde ich Sie nicht enttäuschen, Mr. Wright.}
{358}{}{Gut.}
{359}{}{Nicht überraschend, angesichts deiner Unwissenheit und Arroganz.}
{360}{}{[Nach kurzem Nachdenken gibt er dir 100 $] Du kannst gehen.}

#Êâåñò Ïàòğèêà
{370}{}{Mr. Wright, im Namen von Patrick bitte ich um die Erlaubnis, einen Nachtfilm zu zeigen.}
{371}{}{[Er spricht wehmütig und betont jede Silbe] Nacht-film ... Ich hätte nicht gedacht, dass Patrick schlau genug ist, jemanden an seiner Stelle zu schicken. Ich habe ihm bereits gesagt, dass seine bescheuerte Religion in meinem Gebiet nicht willkommen ist. Sag Patrick, dass ich seine Versuche, mich zu untergraben, nicht dulden werde.}
{372}{}{Mr. Wright, hören Sie ...}
{373}{}{Nein, DU hörst zu! Er kann froh sein, dass er nach seinen Aktionen gegen mich überhaupt noch auf eigenen Beinen rauslaufen darf! Er macht MEINEN Mietern Hoffnung auf Dinge, die sie nicht haben können! Er redet MEINEN Mietern ein, sie seien stark und hätten etwas Besseres verdient als das, was ich ihnen biete! Warum sollte ich darüber hinwegsehen?}
{374}{}{Können wir das nicht wie Geschäftsleute besprechen? Was wäre, wenn du für deine Geduld entschädigt würdest?}
{375}{}{Patrick will keinen Aufstand anzetteln. Er will den Leuten nur einen Film zeigen. Vertrau mir.}
{376}{}{Darauf habe ich keine Antwort, Mr. Wright.}
{377}{}{Endlich reden wir vernünftig. Wenn ich aus seiner Schmarotzerei Profit schlagen kann, sieht die Sache schon anders aus ... Und er muss den Mund halten. Vielleicht kann er sogar die Ausbreitung dieser Geschlechtskrankheit eindämmen, die unter Renos Prostituierten grassiert. Also gut, ich erlaube es ihm gegen eine symbolische Gebühr von 1000 $.}
{378}{}{Hier ist das Geld.}
{379}{}{Ich hole das Geld.}
{380}{}{Dann sind wir uns einig. Aber sag Patrick, dass ich lediglich verspreche, mich nicht in seine Vorstellung einzumischen. Für Sicherheit werde ich nicht sorgen.}
{381}{}{Du bist ... vertrauenswürdig genug, dass ich ihn diese Veranstaltung vielleicht abhalten lasse. Aber für die Sicherheit müsst ihr selbst sorgen – ich verspreche nur, mich nicht einzumischen. Und jetzt geh.}
{382}{}{Das weiß ich zu schätzen, Boss.}
{383}{}{Ich vertraue diesem Patrick nicht, aber du hast in meinen Slums einen guten Ruf. Na schön, ich werde mich nicht in seine Vorstellung einmischen. Aber für seine Sicherheit übernehme ich keine Verantwortung – darum müsst ihr euch kümmern.}
{384}{}{Danke.}
{385}{}{Und warum sollte ich dir vertrauen? Du bist in diesem Viertel ein Niemand.}
{386}{}{Dagegen kann ich wohl nichts sagen.}
{387}{}{Mr. Wright, das könnte eine großartige Gelegenheit für Sie sein. Lassen Sie mich erklären ...}
{388}{}{[Er hört deiner Erklärung aufmerksam zu und nickt schließlich.] Ich verstehe, ich verstehe. Dieser Prediger sollte dich all seine Geschäfte erledigen lassen – du kannst viel besser reden als er. Na gut, sag ihm, dass ich einverstanden bin. Aber für Sicherheit werde ich nicht sorgen – darum müsst ihr euch kümmern.}

#Êğûøà äëÿ êîíöåğòà â Êîòòîí-êëóáå
{390}{}{Ich vertrete die Cotton club. Wir möchten über den Schutz eines Konzerts verhandeln.}
{391}{}{Ausgezeichnet. Dein Boss sollte wissen, dass ich schon immer an einer Zusammenarbeit interessiert war. Schließlich sind wir Nachbarn. Sag ihm, dass ich zum Konzert beitragen werde, aber dafür will ich 30% of der Tageseinnahmen.}
{392}{}{Wir stimmen diesen Bedingungen zu.}
{393}{}{Wir werden Ihr Angebot prüfen und uns bei Ihnen melden.}
{394}{}{Eine weise Entscheidung. Ich schicke meine Männer, um die Einzelheiten zu klären.}
{395}{}{Danke. Das wäre alles.}

#Female character
{1135}{}{Hast du meinen ... Auftrag erledigt?}
{1138}{}{Ich wollte nur Hallo sagen.}
{1147}{}{Dein Ruf. Ganz gleich, wie viel Geld du hast oder welche Waffe du trägst: Was dir fehlt, ist ein guter Ruf. In meinen Slums kennt dich niemand und niemand kann dich empfehlen. Und ich vertraue meinen Leuten. Wenn du Arbeit willst, zeig mir die Ergebnisse deiner Arbeit ... die man beurteilen kann.}
{1148}{}{Sie haben wirklich noch nie von mir gehört, Mr. Wright? Ich habe in Reno schon einiges geleistet.}
{1162}{}{Sehr gut. [Er lehnt sich in seinem Stuhl zurück und verschränkt die Finger auf dem Bauch.] Ich habe ein paar Aufträge für eine Frau wie dich ... Für jemanden, der nicht von hier stammt. Ich bezahle gut – solange die Arbeit ordentlich erledigt wird.}
{1184}{}{Ich bin von Uranium City zurück.}
{1210}{}{Wegen der Prospektoren ...}
{1215}{}{Verschwende nicht meine Zeit! Mich interessiert nur der Sprengstoff. Mir ist egal, wer ihn bekommt, solange er zu *mir* gebracht wird!}
{1217}{}{Was?! Du Idiot! Diese Sprengstoffe sind mein Druckmittel *gegen* diese Stadt! Hol sie um jeden Preis zurück! Wenn du diesen Nelson töten musst, dann tu es. Und jetzt geh. Wenn ich dich das nächste Mal sehe, hast du gefälligst meine Sprengstoffe dabei.}
{1220}{}{Die Prospektoren, Mr. Wright. Sie haben die Sprengstoffe zurückgeholt. Sie haben mich nur gebeten, sie abzuliefern, weil sie Angst vor Ihnen haben.}
{1222}{}{Hm. Du hättest lügen und behaupten können, du hättest sie von diesem Stützpunkt geholt, aber das hast du nicht. Ehrlichkeit weiß ich zu schätzen. Jedenfalls, hier ist dein Lohn für den Auftrag.}
{1226}{}{Du könntest lügen. Vielleicht haben sie die Sprengstoffe geholt und du hast sie mir nur gebracht. Aber der Auftrag ist erledigt, du bist hier und sie sind es nicht, also bekommst du die Belohnung.}
{1237}{}{Gut. Hier ist deine Bezahlung. Wenn du mich angelogen hast, solltest du besser nie wieder in diese Stadt zurückkehren.}
{1270}{}{Deine Arbeit in Uranium City ist getan. Meine Söhne übernehmen von hier an ... wenn wir bereit sind. Du hast einen weiteren Auftrag.}
{1274}{}{Ich habe mich um den Fremden gekümmert. Offenbar hat er die Elendsviertel beobachtet, aber ich konnte nicht mehr herausfinden.}
{1279}{}{Nun, deine Bezahlung. [er zählt das Geld ab] Das war dein letzter Auftrag. Von jetzt an brauche ich jemanden, der klüger ist als du. Belästige mich nicht wieder.}
{1281}{}{Nun, deine Bezahlung. [Er zählt das Geld ab.] Du hast diesen Auftrag gut erledigt. Du hast bewiesen, dass man dir vertrauen kann. Du bist bereit für mehr ... heikle Aufträge.}
{1282}{}{Ich höre, Herr Wright.}
{1301}{}{Ich habe Luciano dein Angebot überbracht. Er ist bereit, dich anzuhören – persönlich.}
{1304}{}{Ich habe Luciano dein Angebot überbracht, aber er hat abgelehnt. Das tut mir sehr leid, Mr. Wright.}
{1305}{}{Ich habe Luciano dein Angebot überbracht, aber er hat abgelehnt.}
{1310}{}{Mr. Wright, ich habe viel über Ihre Sammlung von Dingen aus der Vorkriegszeit gehört. Können Sie mir mehr darüber erzählen?}
{1312}{}{Aber darum musst du dir keine Sorgen machen. Das wäre ohnehin nichts für dich.}
{1313}{}{Mein Museum ist für die einheimischen Grobiane geschlossen, die Kultur nicht erkennen würden, selbst wenn sie ihre Hütten plattwalzte und an ihrer Stelle eine Kunstgalerie errichtete. Aber du hast mir gute Dienste geleistet. Vielleicht lässt du dich bei einer Führung erleuchten.}
{1316}{}{Ich würde Ihnen gern alles zeigen, aber jetzt gerade nicht. Entschuldigen Sie die Störung.}
{1350}{}{Ich bin überrascht. Ich dachte, er wäre einer der bestbewachten Männer in ... Na ja, spielt keine Rolle. Danke, dass du ein zuverlässiger Angestellter warst, aber ich habe keine Arbeit mehr für dich. Meine Söhne können sich auf absehbare Zeit um alles kümmern.}
{1352}{}{Gut ... Vielleicht gibt es für Reno doch noch Hoffnung. Hier ist dein Lohn. Von jetzt an hängt alles von mir ab. Ich brauche deine Dienste nicht mehr. Vielleicht hat Luciano Arbeit für dich – ich erwarte, dass er in Zukunft viel zu tun haben wird.}
{1353}{}{Verstehe. Das ist bedauerlich, aber ich mache dir keinen Vorwurf. Luciano ist ein vorsichtiger Mann und vertraut anderen nicht leicht. Jedenfalls habe ich keine Arbeit mehr für dich. Meine Söhne können sich auf absehbare Zeit um alles kümmern.}
{1355}{}{Du hattest deine Chance bereits. Ich glaube nicht, dass ein weiterer Versuch etwas ändern würde. Trotzdem habe ich nichts zu verlieren, also kannst du es ruhig versuchen.}
{1360}{}{[Nach kurzem Nachdenken gibt er dir 100 $] Du kannst gehen.}
{1381}{}{Du bist ... vertrauenswürdig genug, dass ich ihn diese Veranstaltung vielleicht abhalten lasse. Aber für die Sicherheit müsst ihr selbst sorgen – ich verspreche nur, mich nicht einzumischen. Und jetzt geh.}
{1387}{}{Mr. Wright, das könnte eine großartige Gelegenheit für Sie sein. Lassen Sie mich erklären ...}