{100}{}{Du siehst einen fanatischen Fan.}

#Случайное подробное описание
{101}{}{Du siehst einen wild aussehenden Mann. Er schreit sich die Seele aus dem Leib.}
{102}{}{Du siehst einen fanatischen Kampfsportfan. Er schreit nach Blut.}
{103}{}{Du siehst eine wild aussehende Frau. Sie schreit sich die Seele aus dem Leib.}
{104}{}{Du siehst einen fanatischen Kдfigkampf-Fan. Sie schreit nach Blut.}

#Попы'ка разговора
{110}{}{Jaaaaaa!}
{111}{}{Schlag mich! Schlag mich! Davon erzдhl ich meinen Kindern!}
{112}{}{Zeig's ihnen!}
{113}{}{Einer von uns!}
{114}{}{::ruft:: ::pfeift:: ::schreit::}
{115}{}{::hysterisch::}
{116}{}{Jaaaaaa!}
{117}{}{Aaaaaah!}
{118}{}{::quiekt:: ::ruft::}
{119}{}{::pfeift:: ::schreit:: ::pfeift::}
{120}{}{Tцte ihn!}
{121}{}{Tцte den Bastard!}
{122}{}{Du bist der Beste!}
{123}{}{Du bist der Beste, Gangster!}
{124}{}{Zeig's diesem Hurensohn!}
{125}{}{Ja! Zeig's ihm!}
{126}{}{DER BESTE! DER BESTE!!!}
{127}{}{JAAAA!!!}
{128}{}{Du bist der beste Kдmpfer, den ich je gesehen habe.}
{129}{}{Hast du das gesehen, ha!? Hast du das gesehen!?}
{130}{}{Oh ja, der hier weiЯ, wie man jemandem richtig wehtut.}
{131}{}{Dieser Sklave kommt gerade erst aus dem Цdland, aber er kдmpft wie ein Kцnig! Unglaublich!}
{132}{}{Oh mein Gott!}
{133}{}{Ist das ьberhaupt erlaubt?!}

#Когда фан сделал с'авку во время боя на ГГ (для муж. героя)
{150}{}{! Ich setze 3 Dollar auf dich!}
{151}{}{ gewinnt, ich setze auf ihn!}
{152}{}{! 10 Dollar auf deinen Sieg!}
{153}{}{! Du bist der Beste!}
{154}{}{ , ich glaube an dich!}
{155}{}{ , du musst gewinnen!}
{156}{}{ , du wirst gewinnen!}
{157}{}{ , du bist groЯartig!}
{158}{}{ , mit dir mache ich ein Vermцgen!}

#Когда фан сделал с'авку во время боя НЕ на ГГ, а на его про'ивника
{160}{}{ , auf dich setze ich keinen Penny!}
{161}{}{ wird verlieren!}
{162}{}{ ist scheiЯe!}
{163}{}{ ist nur ein Stьck ScheiЯe, kein Kдmpfer!}
{164}{}{ , blamier dich bloЯ nicht im Ring!!!}
{165}{}{ , der macht dich zum Frьhstьck!!!}
{166}{}{ , hцr auf, herumzualbern!}
{167}{}{ , du bist scheiЯe!}
{168}{}{ , keinen Penny auf dich!}

#Female character:

#Когда фан сделал с'авку во время боя на ГГ (для жен. героя)
{1150}{}{! Ich setze 3 Dollar auf dich!}
{1151}{}{ gewinnt, ich setze auf sie!}
{1152}{}{! 10 Dollar auf deinen Sieg!}
{1153}{}{! Du bist der Beste!}
{1154}{}{ , ich glaube an dich!}
{1155}{}{ , du musst gewinnen!}
{1156}{}{ , du wirst gewinnen!}
{1157}{}{ , du bist groЯartig!}
{1158}{}{ , mit dir mache ich ein Vermцgen!}

#Когда фан сделал с'авку во время боя НЕ на ГГ, а на его про'ивника
{1160}{}{ , auf dich setze ich keinen Penny!}
{1161}{}{ wird verlieren!}
{1162}{}{ - du bist scheiЯe!}
{1163}{}{ ist nur ein Stьck ScheiЯe, kein Kдmpfer!}
{1164}{}{ , blamier dich bloЯ nicht im Ring!!!}
{1165}{}{ , sie macht dich zum Frьhstьck!!!}
{1166}{}{ , hцr auf, herumzualbern!}
{1167}{}{ , du bist scheiЯe!}
{1168}{}{ , keinen Penny auf dich!}
