{100}{}{Du siehst einen starken Mann.}
{101}{}{Du siehst einen großen, kräftigen Mann mit durchtrainierten Muskeln.}

{110}{}{*grinst dich zahnlos an*}
{111}{}{*kratzt sich am Kopf*}
{112}{}{*macht Sit-ups*}
{113}{}{*bruellt*}
{114}{}{Hfff}
{115}{}{Grrr}
{116}{}{*wärmt seine Hände auf*}
{117}{}{Ugh-mf.}
{118}{}{Hau ab!}
{119}{}{Ich bin so hungrig, ich könnte jetzt ein ganzes deathclaw verdrücken ...}
{120}{}{*kratzt sich*}
{121}{}{*murmelt*}
{122}{}{Errr}
{123}{}{Ughf}
{124}{}{Hrrr}
{125}{}{Ehhh}
{126}{}{Grrr}
{127}{}{Hoppala}

{128}{}{Lass mich besser in Ruhe.}
{129}{}{*starrt deinen Kopf an wie einen Boxsack*}
{130}{}{Ich hör' zu?}
{131}{}{Brauchst du einen Trainer?}
{132}{}{*nickt blöde zu allem, was du sagst*}

# boxing boxers messages

# punch
# hit noise
{300}{}{Ernhhh}
{301}{}{Unfff}
{302}{}{Hrghhh}
{303}{}{Nfff}
{304}{}{Hrggg}
{305}{}{Ooof}

# dodge
{310}{}{Zu langsam!}
{311}{}{Nicht ins Gesicht!}
{312}{}{Du kämpfst wie meine Großmutter!}
{313}{}{Nicht unter die Gürtellinie schlagen!}
{314}{}{Du bist gar nicht schlecht.}
{315}{}{War das schon alles?}

# knock down
{320}{}{Und bleib liegen!}
{321}{}{K. o.!}
{322}{}{Runter, sofort!}
{323}{}{Wenn er stirbt, stirbt er.}

{330}{}{Du hättest ein Champion werden können!}
{331}{}{Wie kann so ein ... Geggghhh ...}
{332}{}{*Huuuuurrrrllllll*}
{333}{}{Ooo, Glücksbärchis ...}
{334}{}{Ich glaube, ich bleib einfach noch ein Weilchen hier liegen.}
{335}{}{Kein Schmerz, kein Schmerz, kein Schmerz ...}

# punching
{340}{}{Friss das!}
{341}{}{Willst du was davon abhaben?!}
{342}{}{Schlampe!}
{343}{}{Jetzt gehörst du mir.}
{344}{}{Leute wie dich esse ich zum Frühstück.}
{345}{}{Haadookin.}
{346}{}{Jetzt stirbst du.}
{347}{}{SUPER... NUKLEARER... TORNADO... FAUST...}

# taunt
{350}{}{Adrian! Adrian!}
{351}{}{Hier gehst du zu Boden.}
{352}{}{Ich mach dich zu meiner Schlampe ...}
{353}{}{Ich werde dich brechen.}
{354}{}{Du kämpfst wie ein fetter brahmin!}
{355}{}{Du hast keinen Mumm!}
{356}{}{Du bist ein Penner! Ein Penner!}
{357}{}{Ich verprügle dich wie einen Hund ...}

# corner
{360}{}{Einen Rückkampf wird's nicht geben!}
{361}{}{Schlag zu wie ein Schmetterling ...}
{362}{}{Hände oben lassen ...}
{363}{}{Bleib wachsam!}
{364}{}{Kämpf dich durch den Scheiß!}
{365}{}{Kritischer Treffer!}
{366}{}{Verpass mir 'ne Platzwunde, Mick.}
{367}{}{Denk dran: immer schön den Jab setzen!}
{368}{}{Ich seh alle drei!}