{100}{}{Du siehst einen Türsteher des Casinos.}

{101}{}{Du siehst einen Türsteher des Casinos. Er ist RIESIG.}
{102}{}{Du siehst einen Türsteher des Casinos. Er sieht groß und wütend aus.}
{103}{}{Du siehst einen Türsteher des Casinos. Er mustert dich misstrauisch.}
{104}{}{Du siehst einen Türsteher des Casinos. Du hättest nicht gedacht, dass ein Mensch so groß sein kann.}

{105}{}{Ich warne dich – keine Waffen im Casino.}
{106}{}{Nimm die Kopfbedeckung ab, wenn du rein willst.}

#Îğóæèå â ğóêàõ
{110}{}{Hey, du! Schaff die Waffe weg!}
{111}{}{Ich warne dich – nimm die Waffe weg!}
{112}{}{Keine Waffen im Casino!}
{113}{}{Versteck die Waffe!}
{114}{}{Mit dieser Waffe kommst du hier nicht rein!}
{115}{}{Hey, versteck die Waffe!}

{116}{}{Noch einmal: Versteck die Waffe!}
{117}{}{Ich wiederhole: Keine Waffen!}
{118}{}{Ich wiederhole: Keine Waffen im Casino!}
{119}{}{Nimm diese Waffe SOFORT weg!}
{120}{}{Waffen sind im Casino verboten!}

{121}{}{Hey, die Waffe. Ich wiederhole mich nicht noch einmal!}
{122}{}{Hmm, sieht aus, als suche da jemand Ärger.}
{123}{}{Ich warne dich zum letzten Mal.}
{124}{}{Du hast mich nicht gehört? Ich kann es dir auch mit Gesten erklären!}
{125}{}{Sieht aus, als wäre es Zeit, jemanden unschädlich zu machen.}
{126}{}{Versteck die Waffe, dann wird niemand verletzt.}

{127}{}{Das war's, Arschloch, jetzt bist du dran!}
{128}{}{Ich habe dich gewarnt!}
{129}{}{Harter Kerl? Das werden wir ja sehen!}
{130}{}{Wir müssen dir wohl Manieren beibringen!}
{131}{}{Das war's – du steckst ganz schön in der Scheiße!}
{132}{}{Du hast es so gewollt, Arschloch!}
{133}{}{ALARM! FEINDE IM CASINO!}

#Ïîïû'êà çàãîâîğè'ü
{150}{}{Guten Abend.}
{151}{}{Ich darf nicht mit Kunden sprechen.}
{152}{}{Probleme?}
{153}{}{Was willst du?}
{154}{}{Tut mir leid, nicht mein Problem.}
{155}{}{Frag den Administrator.}
{156}{}{Ich kann mich nicht mit Gesprächen ablenken lassen.}

#Íàğêîìàí:
{160}{}{Hey, du! Süchtige können wir hier nicht gebrauchen. Verschwinde. Deinen Entzug kannst du woanders durchstehen. Hast du mich verstanden?}
{161}{}{Denk nicht mal daran, mich anzufassen, sonst erlebst du die Nerd-Wut! Hi-i-y-a-a-h!!!}
{162}{}{Schon gut, ich verstehe ...}

{163}{}{Bist du high? Ich würde dir nicht empfehlen, hier zu sein.}
{164}{}{Was ist mit deiner Haut los? Ist das ansteckend?}

#Áàëàêëàâà:
{170}{}{Hey! Wenn du im Casino herumlaufen willst, zeig dein Gesicht. Wir müssen sehen, wer du bist.}
{171}{}{[Still gehen]}

#Female character:
{1127}{}{Das war's, Miststück, du hast es so gewollt!}
{1128}{}{Ich hab dich gewarnt, du billige Hure!}
{1129}{}{Ganz schön hart im Nehmen, was? Das werden wir ja sehen!}
{1130}{}{Wir müssen dir wohl Manieren beibringen!}
{1131}{}{Das war's – du bist erledigt!}
{1132}{}{Du hast es so gewollt, du Schlampe!}
{1133}{}{ALARM! FEINDE IM CASINO!}
