{100}{}{Du siehst einen Casinogast.}
{101}{}{Normalerweise trinke ich nicht mit Fremden und werde auch nicht mit ihnen high.}

#Ñîîáùåíèÿ â êîíñîëü ïğè âûïîëíåíèè êâåñòà Ëó÷èàíî
{102}{}{Dieser Gast wird nach einem Schluck eines „seltsamen“ Getränks bewusstlos.}
{103}{}{Deine Ablenkung an der Bar war erfolgreich.}
{104}{}{Ugh ... Was war das denn??}

# examines
{150}{}{Du siehst einen der Casinogäste. Er sieht müde aus.}
{151}{}{Du siehst einen der Casinogäste. Seine Augen glänzen golden.}
{152}{}{Du siehst einen der Casinogäste. Er hält sich das Gesicht in den Händen.}
{153}{}{Du siehst einen der Casinogäste. Er wirkt ein wenig angetrunken.}
{154}{}{Du siehst einen der Casinogäste. Er zwinkert dir breit zu und torkelt dann davon.}
{155}{}{Du siehst einen der Casinogäste. Er versucht, die Kellnerin auf sich aufmerksam zu machen.}
{156}{}{Du siehst eine der Casinogästinnen. Sie sieht müde aus.}
{157}{}{Du siehst eine der Casinogästinnen. Ihre Augen glänzen golden.}
{158}{}{Du siehst eine der Casinogästinnen. Sie hält sich das Gesicht in den Händen.}
{159}{}{Du siehst eine der Casinogästinnen. Sie wirkt ein wenig angetrunken.}
{160}{}{Du siehst eine der Casinogästinnen. Sie zwinkert dir breit zu und torkelt dann davon.}
{161}{}{Du siehst eine der Casinogästinnen. Sie versucht, den Kellner auf sich aufmerksam zu machen.}

#Äëÿ ñóïåğáğîíè:
{207}{}{Sieh ihn dir nur an ... Sie ... Es. Was auch immer das ist, es jagt mir Schauer über den Rücken.}
{208}{}{Glaubst du, das Ding will jemanden abknallen?}
{209}{}{Es ist die Wut der Hölle in Fleisch und Blut. Äh, unter der Rüstung, versteht sich.}
{210}{}{Bleib dem Ding aus dem Weg.}
{211}{}{Sieht ganz schön gefährlich aus ...}
{212}{}{*Schluck*}
{213}{}{Ich glaube, dieser Mr. Roboto hat mich gescannt.}
{214}{}{Ich glaube, dieser wandelnde Panzer hat mich finster angestarrt. Ich bin weg.}
{215}{}{Ich habe gehört, das Ding hat gestern drei Auftragskiller zerlegt.}

#Äëÿ áåğñåğêà:
{216}{}{Schon wenn ich ihn nur ansehe, bekomme ich eine Gänsehaut.}
{217}{}{Glaubst du, er will jemanden abknallen?}
{218}{}{Bleib dem Mann aus dem Weg.}
{219}{}{Ich glaube, er hat mich angesehen.}
{220}{}{Ich glaube, er hat mich gerade finster angestarrt. Ich bin weg.}
{221}{}{Ich habe gehört, er hat erst gestern drei Auftragskiller erschossen.}
{222}{}{Oh-oh. Aus dem Weg!}
{223}{}{Die Wut der Hölle in Fleisch und Blut.}
{224}{}{Sieht ganz schön gefährlich aus ...}
{225}{}{*Schluck*}

#(!!! çàìåíèòü) Äëÿ ïğåñôèíãåğà:
{226}{}{La Femme Nikita, und noch mehr.}
{227}{}{Schon wenn ich sie nur ansehe, bekomme ich eine Gänsehaut.}
{228}{}{Glaubst du, sie will jemanden abknallen?}
{229}{}{Ich glaube, sie hat mich angesehen.}
{230}{}{Ich glaube, sie hat mich gerade finster angestarrt. Ich bin weg.}
{231}{}{Ich habe gehört, sie hat erst gestern drei Auftragskiller erschossen.}
{232}{}{Was für ein Arsch! Äh, ein knallharter Arsch, meine ich.}
{233}{}{So hart siehst du gar nicht aus, Herr Preisboxer.}
{234}{}{Ich habe 20 Chips auf dich gesetzt!}
{235}{}{Hey, Champ! Der letzte Kampf war großartig!}
{236}{}{Ich habe dich im Ring kämpfen sehen. Verdammt guter rechter Haken.}
{237}{}{Lässt du dich fallen? Ich habe 30 Chips auf dich gesetzt.}
{238}{}{Wie viel stemmst du beim Bankdrücken?}
{239}{}{Wo trainierst du?}
{240}{}{Pass auf den Masticator auf. Er hat eine Vorliebe für Ohren.}
{241}{}{Ich würde dir einen Drink spendieren, wenn ich nicht mein ganzes Geld auf deinen Gegner verwettet hätte.}
{242}{}{So hart siehst du gar nicht aus, Frau Linke-Haken.}
{243}{}{Darf ich sehen, wie du deine Bauchmuskeln anspannst?}

#(!!! çàìåíèòü)Äëÿ ïîğíîñòàğ:
{244}{}{Wow. Sieh dir das an.}
{245}{}{Sieh dir *das* mal an.}
{246}{}{::Formt lautlos das Wort „Verdammt“.::}
{247}{}{Ich WUSSTE, ich hätte mich heute rasieren sollen.}
{248}{}{Komm mal kurz her und plauder mit mir, Süße.}
{249}{}{Die Tribals haben ordentlich Holz vor der Hütte! Verdammt!}
{250}{}{Sieh dir mal die Oberweite dieser Tribal an.}
{251}{}{Das da ist die Hauptstute in meiner Herde.}
{252}{}{Für diese Frau würde ich sogar baden.}
{253}{}{Deine Goldader hab ich genau hier.}
{254}{}{Schüttel es!}
{255}{}{Zeig, was du draufhast!}
{256}{}{::Pfeift::}
{257}{}{Gehen die Beine noch weiter nach oben?}
{258}{}{Verdammt nochmal.}
{259}{}{Hast du Pommes zu deinem Milchshake, Schöne?}
{260}{}{Vielleicht tanzt sie heute Abend.}
{261}{}{Hast du ihren neuesten Film gesehen? Heiß, Mann, verdammt HEISS.}
{262}{}{Entschuldige. Ich muss mal zur Toilette und äh, mir kurz die Haare kämmen.}
{263}{}{Ich wäre gern ihre Unterhose.}
{264}{}{Ich wäre gern ihre Unterwäsche.}
{265}{}{Ich würde gern an ihren Shorts riechen.}
{266}{}{Das ist vielleicht eine heiße Schlampe.}
{267}{}{Verdammt. So viele Kurven und ich hab keine Bremsen.}
{268}{}{Na, halloooo, Hengst.}
{269}{}{Ein Hengst wie du braucht einen Sattel? Ich hab morgen Abend Zeit.}
{270}{}{Was machst du später, Matrose?}
{271}{}{Darf ich deine Muskeln fühlen?}
{272}{}{Wieso fällst du nicht in Ohnmacht, wenn du einen Steifen hast?}
{273}{}{Willst du auf einen Drink bei mir vorbeikommen?}
{274}{}{Ich möchte mein Abendessen von deiner Brust essen.}
{275}{}{Brauchst du einen Partner für deinen nächsten Film?}
{276}{}{::Starrt auf deinen Bizeps.::}

#Èãîğíûå ğåïëèêè:
{280}{}{Lady Luck, lass mich jetzt nicht im Stich.}
{281}{}{Würfel los.}
{282}{}{Baby braucht ein neues Paar Schuhe ...}
{283}{}{Verdammte Touristen ... }
{284}{}{Verdammt! Ich lag 53 Chips vorn, und dann ... }
{285}{}{Bei all dem Pech ... }
{286}{}{So nah dran!}
{287}{}{Ich sprenge die Bank.}
{288}{}{Ich? Ich sprenge die Bank. Sieh mir zu.}
{289}{}{Das Haus ist gegen mich.}
{290}{}{Das Glück ist gegen mich.}
{291}{}{Kommt überhaupt jemand zu meiner Beerdigung?}
{292}{}{Das Haus ist heute gnädig zu mir.}
{293}{}{Zwischen Trinkgeld und diesen Saufgelagen ... }
{294}{}{Wenn du so weitersetzt, wirst du Golgotha bald dein Zuhause nennen ... }
{295}{}{Kellnerin, noch einen Drink!}
{296}{}{Kellner, noch einen Drink!}
{297}{}{Diese Drinks schmecken ... seltsam.}
{298}{}{Ich hab das Fieber!}
{299}{}{Sind meine Chips etwa schon alle weg?}
{300}{}{Das Glück ist ein launisches Biest, und meine Schwiegermutter auch.}
{301}{}{Na, na ...}
{302}{}{Ähh, lass mich nicht hängen!}
{303}{}{Komm schon, Süße!}
{304}{}{Verdammte Crossroaders, überall ...}
{305}{}{Na toll, noch ein Spieler mit kleinem Einsatz.}
{306}{}{Ich bin sowas von der Knaller.}
{307}{}{Ich schlafe, wenn ich tot bin.}
{308}{}{Mann, ich muss pissen.}
{309}{}{Mann, ich muss mal die Schlange entleeren.}
{310}{}{Verdammt, hier lassen sie auch jeden rein.}
{311}{}{Komm schon, Sieben!}
{312}{}{Du hast Schneid, Baby.}
{313}{}{Wer ist heute Abend der große Gewinner? Mikey!}
{314}{}{Nicht überwürfeln ... Komm schon ... }
{315}{}{Ich muss mal „abdüsen“ ... Wenn du verstehst, was ich meine.}
{316}{}{Das ist doch beschissen.}
{317}{}{Ich hab nur 60 Chips verloren. Also, in den ersten fünf Minuten.}
{318}{}{Rot 23! Rot 23! Komm schon ... Rot 23 ... }
{319}{}{50 Chips auf Schwarz 15 ... }
{320}{}{Es dreht sich und dreht sich ... Wo es hält, weiß keiner ... }

#Âûèãğàë
{321}{}{Ich bin DER BESTE Spieler!}
{322}{}{Ach was? Wo ist die Kasse?}
{323}{}{Scheiße, ich hab wirklich gewonnen? Ja!!}
{324}{}{Jetzt gehört das MIR! Ha-ha-ha!}
{325}{}{Ihr Vollidioten, ich hab gewonnen!}
{326}{}{Und dabei hieß es, das sei alles nur Schwindel!}
{327}{}{::tanzt vor Freude::}
{328}{}{::schlägt die Hände zusammen::}
{329}{}{Ich bin dran!!!}

#Ïğîèãğàë
{330}{}{Drecksack!}
{331}{}{Verdammtes Glück.}
{332}{}{Ich hab *schon wieder* verloren!}
{333}{}{Schon gut, ich hab noch ein bisschen Kleingeld übrig.}
{334}{}{Ach, verdammt, wann hört das endlich auf!}
{335}{}{Ich mach sie jetzt fertig!}
{336}{}{Heute ist nicht mein Tag ... Scheiße ...}
{337}{}{Warum bin ich so ein Versager?}
{338}{}{Zeit, mit dem Scheiß aufzuhören ...}
{339}{}{Verdammt noch mal, was für ein Pech.}
{340}{}{Bald hab ich gar nichts mehr.}
