{100}{}{Du siehst ein Kind.}
{101}{}{Du siehst ein gewöhnliches freches Gör.}
{102}{}{}
{103}{}{Hey! Gib das zurück!}
{104}{}{Gib mir mein Spiel zurück, oder ... Oder ich werde sauer!}
{105}{}{Ganz genau, das geht dich nichts an!}
{106}{}{Du hast den Ausgang des Streits beeinflusst. Hoffen wir, dass du die richtige Entscheidung getroffen hast.}

#Dialogue:
{110}{}{[Zwei Kinder streiten sich heftig um das Spiel] NEIN! ES GEHÖRT MIR! Huch – wer bist du?}
{111}{}{Ich frage mich nur, worüber ihr euch streitet.}
{112}{}{[Das erste Kind:] Na ja, ich hab dieses Spiel in einem alten Gebäude gefunden, aber ER hat es genommen und will es nicht zurückgeben! [Das zweite Kind:] ICH hab doch gesagt, wir sollen zu dem Gebäude gehen! Wenn ich nicht gewesen wäre, hätten wir es gar nicht gefunden!}
{113}{}{Hey, beruhigt euch mal ...}
{114}{}{[Erster:] Aber ich hab's gefunden! Also gehört es mir! [Zweiter:] Aber ich bin ein Jahr älter als du! Also darf ich entscheiden, wer es bekommt!}
{115}{}{Hey! Jetzt beruhigt euch mal, ihr beiden!}

{116}{}{[Erster:] Ja, was meinst du? Ich sollte es bekommen, oder? [Zweiter:] Nein, ich sollte es bekommen! Sag's ihm!}
{117}{}{Das alles wegen eines Spiels? Ist mir doch egal.}
{118}{}{[Sprich mit dem ersten Kind] Du musst deinen Älteren Respekt entgegenbringen. Sie sind klüger und reifer. Hör auf deinen großen Bruder.}
{119}{}{[Sprich mit dem zweiten Kind] Er hat es gefunden. Du kannst es ihm nicht einfach wegnehmen, nur weil du älter bist. Gib es zurück.}
{120}{}{Warum könnt ihr es nicht teilen? Ihr seid schließlich Brüder.}
{121}{}{Na, warum spielt ihr nicht darum? Der Gewinner bekommt das Spiel.}

{130}{}{[Erster:] Ha! Ich wusste, dass es den Erwachsenen egal ist. Ich nehme es! [Zweiter:] Wag's ja nicht, sonst hau ich dir die Rübe runter! Du kleiner...}
{131}{}{Bis später, Kinder. Na ja, zumindest einer von euch, wenn das so weitergeht.}
{132}{}{[Erster:] Was?! Ach... [Zweiter:] Genau! Ich bin reifer, also bekomme ich das Spiel! [Er dreht sich um, streckt dem ersten Kind seinen Hintern entgegen und macht mit den Lippen ein Furzgeräusch.] Ätsch!}
{133}{}{Na gut, viel Spaß...}
{134}{}{[Erster:] Ha! Sogar die Erwachsenen halten dich für einen Idioten! Gib mir jetzt das Spiel! [Zweiter:] Na gut, dann behalt es! Ich will dieses blöde Spiel sowieso nicht! Das ist doch eh nur was für Babys!!}
{135}{}{Na gut, viel Spaß...}
{136}{}{[Erster:] Weil er ein Idiot ist! [Zweiter:] Weil er ein blödes Baby ist!}
{137}{}{Von hier aus betrachtet klingt ihr beide wie dumme, blöde Babys. Keiner von euch will dem anderen überhaupt zuhören! Warum versucht ihr nicht, beim gemeinsamen Spielen etwas voneinander zu lernen?!}
{138}{}{[Erster:] Hmpf... Na gut. Wir teilen. [Zweiter:] Ja, meinetwegen... Zum Spielen braucht man sowieso zwei Leute.}
{139}{}{Großartig! Nehmt euch das als wertvolle Lektion zu Herzen. Eines Tages wird sie euch noch nützlich sein.}
{140}{}{Deine Überzeugungskraft hat dir 100 Erfahrungspunkte eingebracht.}
{141}{}{[Erster:] Ja, das ist eine tolle Idee! Das ist fair, lass uns spielen! [Zweiter:] Klar! Und wenn ich gewinne, weißt du, dass ich es die ganze Zeit verdient habe!}
{142}{}{Ich spiele mit.}
{143}{}{Ich sehe zu.}
{144}{}{ ... [Erster:] Hey, das ist nicht fair! Du hast gewonnen, weil du erwachsen bist! [Zweiter:] Ja, wir hätten dich gar nicht mitspielen lassen sollen!}
{145}{}{Aber das habt ihr! Und jetzt habt ihr nichts mehr, worum ihr euch streiten könnt! Problem gelöst. Hahahahahaha! [Nimm das Spiel]}
{146}{}{ ... [Erster:] Ha! Ich hab gewonnen! Na, was sagst du? Es gehört mir! Mir!!! [Zweiter:] Ja, schön, dann kannst du es behalten! Ist sowieso nur was für Babys! Ist mir egal!}
{147}{}{ ... [Erster:] Ach nein! Ich hab verloren! Mann... [Zweiter:] HA! Jetzt kannst du dich nicht mehr beschweren. Es gehört jetzt mir, ganz allein mir, und ich lasse dich NIE wieder damit spielen!}
{148}{}{Na ja, fair ist fair.}
{149}{}{Die kleinen Kinder waren deinen Tricks nicht gewachsen. Du erhältst 100 Erfahrungspunkte.}