{100}{}{Du siehst den Verfolger.}
{101}{}{Du siehst einen brutal wirkenden Schläger. Sieht aus, als hätte er einen Auftrag.}
{102}{}{Die Verfolgung ist vorbei.}

{110}{}{Hey, Deveraux! Warum läufst du vor uns weg?}
{111}{}{Waren wir nicht gut zu dir? Waren wir nicht wirklich nett?}
{112}{}{Stryker hat dich respektiert. Dich beschützt. Erinnerst du dich nicht?}
{113}{}{Und dann hast du ihm ein Messer in den Rücken gerammt. Nicht gut, Deveraux. Eine miese Nummer.}
{114}{}{Willst du rauskommen und wie Erwachsene darüber reden?}
{115}{}{Darüber oder über deinen Freund, den du vor einiger Zeit an eine andere Gang verpfiffen hast?}
{116}{}{Das war ein Fehler, Terry. Das verstehen wir.}
{117}{}{Du kannst immer noch klug handeln. Du kannst immer noch zurückkommen.}
{118}{}{Es wird sein, als wäre nie etwas passiert! ...}
{119}{}{Solange es nicht wieder vorkommt.}
{120}{}{Wir lassen sogar deine Freunde gehen! Ich schwöre beim Leben meiner Mutter!}
{121}{}{Was sagst du, Deveraux? Willst du es dir leichter machen?}
{122}{}{::waits::}
{123}{}{::sneers::}
{124}{}{Wie du willst, Deveraux! Dann machen wir es eben auf die harte Tour!}
{125}{}{Komm verdammt noch mal raus, du kleine Schlampe!}
{126}{}{Wenn du nicht rauskommst, durchlöchern wir den Laden mehr als das Kondom meines Vaters!}
{127}{}{...Scheiß drauf. Knöpft ihn euch vor, Jungs!}
