{100}{}{Du siehst ein Kind.}
{101}{}{Du siehst ein Kind. Ungewaschen, stinkend und wütend auf die ganze Welt.}
{102}{}{[Er starrt seinen Vater finster an]}

#Talking to kids (male PC)
{110}{}{Ich rede nicht mit Fremden, Arschloch!}
{111}{}{Hau ab!}
{112}{}{Papa! Dieser Mann fasst mich an!}
{113}{}{Komm nicht näher!}
{114}{}{Ich gehe nirgendwo mit dir hin!}
{115}{}{Ich kenne dich nicht.}

#Talking to kids (female PC)
{120}{}{Ich rede nicht mit Fremden, Schlampe!}
{121}{}{Hau ab!}
{122}{}{Papa! Diese Frau fasst mich an!}
{123}{}{Komm nicht näher!}
{124}{}{Ich gehe nirgendwo mit dir hin!}
{125}{}{Ich kenne dich nicht.}

#Patrick's package
{130}{}{Verschwinde!}
{131}{}{Gern. Sobald du mir gesagt hast, wo Patricks Paket ist.}
{132}{}{Noch ein Wort und ich rufe meinen Dad!}
{133}{}{Hör zu, ich tue dir nichts. Ehrlich. Ich brauche nur den Brief. Kannst du mir sagen, wo er ist?}
{134}{}{Ich ... weiß nicht ... [er blickt nervös zu seinem Vater zurück]}
{135}{}{Hat dein Dad ihn genommen? Du musst nichts sagen, nick einfach.}
{136}{}{[Das Kind schaut zu seinem Vater, um sicherzugehen, dass er nicht hinsieht, und nickt dann langsam leicht.]}
{137}{}{Okay. Du kannst dich jetzt entspannen.}

{138}{}{Rede, du kleiner Scheißer! Wovor auch immer du Angst hast, vor mir solltest du noch mehr Angst haben!}
{139}{}{Hat dein Dad ihn genommen? Sag es mir! [schlägt ihm auf den Kopf] Du störrische kleine Schlampe!}

{140}{}{Deine grausame Behandlung eines Kindes hat sich negativ auf dein Karma ausgewirkt.}

#Concert posters
#! Achtung! This text is used for many kids across Reno
{150}{}{Ja?}
{151}{}{Brauchst du Arbeit? Ich gebe dir 10 Dollar, wenn du diese Plakate aufhängst.}
{152}{}{Nichts.}
{153}{}{Cool! Davon kaufe ich mir ein warmes Sandwich!}
{154}{}{Hier sind das Geld und die Plakate. Häng sie dort auf, wo jeder sie sehen kann!}
{155}{}{Warte.}
{156}{}{Du hast keine Plakate mehr.}
{157}{}{Wird gemacht!}
{158}{}{Gut.}

#Female version
{1150}{}{Ja?}
{1157}{}{Wird gemacht!}