{100}{}{Du siehst einen Jungen.}
{101}{}{Du siehst ein trauriges, verwirrtes Kind.}

{102}{}{Vielen Dank! Jetzt kann ich nach Hause gehen!}

#Before sorting things out with barman
{110}{}{Bitte, Sir, ich brauche wirklich Ihre Hilfe! Bitte, nur ein bisschen Kleingeld. So viel Sie entbehren können! Ich verlange nicht viel ...}
{111}{}{Vielleicht sollte ich dir lieber etwas zu essen bringen?}
{112}{}{Wo sind deine Eltern, Kleiner?}
{113}{}{Na klar, Kleiner, hier ist ein Zehner. Gönn dir eine warme Mahlzeit.}
{114}{}{Hau ab, Kleiner, von mir kriegst du nichts!}
{115}{}{Tut mir leid, heute nicht.}

{116}{}{Nein, Sir, ich habe keinen Hunger. Es ist nicht einmal für mich.}
{117}{}{Warum bettelst du dann?}
{118}{}{Zu Hause warten sie auf mich ... Ich muss alles, was ich im Café verdiene, nach Hause bringen, aber der Barkeeper hat mir nur die Hälfte bezahlt! Das sind ganze 100 Mäuse! Wenn ich ohne das Geld nach Hause komme, verprügeln sie mich, bis ich nicht mehr sitzen kann!}
{119}{}{Moment, er hat dir nur die Hälfte gegeben? Wie konnte er nur?!}

{120}{}{Ja, Sir! Genau! Vielleicht bin ich nicht der beste Arbeiter, aber ich habe die ganze Woche hart gearbeitet! Was für ein gieriges Arschloch!}
{121}{}{Whoa, beruhig dich, Kleiner. Ich rede mit ihm.}
{122}{}{Hör zu, Kleiner, ich habe größere Probleme. Du bist auf dich allein gestellt.}
{123}{}{Wie viel hast du gesagt? 100 Mäuse? Wie wär's, wenn ich sie dir gebe und du deiner Wege gehst?}

{124}{}{Danke, Sir! Vielen, vielen Dank! Jetzt brauche ich nur noch 90 Dollar, damit meine Eltern mich nicht verprügeln. Super!}
{125}{}{Heh, ganz schön clever für einen Bettler, was? Erst 10 Dollar, jetzt 90 ...}
{126}{}{Das wäre großartig!}
{127}{}{Das glaube ich nicht.}
{128}{}{Aber Sir ...}
{129}{}{Willkommen in der Wirklichkeit, Kleiner. Gewöhn dich dran.}
{130}{}{[Ihm klappt die Kinnlade herunter.] Was, wirklich?!}
{131}{}{Natürlich, hier ist der Rest deines Lohns.}
{132}{}{Oh ... Tut mir leid, so viel Geld habe ich gerade nicht bei mir. Warte kurz.}
{133}{}{Oh wow! Du bist der beste Mensch, dem ich je begegnet bin! Wirklich, wirklich! Ich will genauso werden wie du!}
{134}{}{Kein Problem, Kleiner. Bis dann.}

#Second dialogue
{140}{}{[Der Junge steht immer noch da und bettelt.]}
{141}{}{}
{142}{}{Hier ist das Geld.}
{143}{}{Milton will dich hier weghaben, also hat er mir das Geld gegeben ... Und ich behalte es, du Trottel! Jetzt verpiss dich, bevor ich dir den Arsch versohle!}
{144}{}{[Geh einfach weiter.]}

{145}{}{[Erschrocken rennt der Junge vor dir davon, dreht sich aber nach einer Weile, als er in sicherer Entfernung ist, um und zeigt dir den Mittelfinger.]}
{146}{}{Hoffentlich sehe ich dich nie wieder, du kleiner Bastard!}

#After end of game
{150}{}{Warte mal, Sir! Du erinnerst dich an mich, oder? Du hast mir im Café geholfen ...}
{151}{}{Du warst der Junge aus dem Cotton Club, richtig? Der Barkeeper wollte dich nicht für deine Arbeit bezahlen, also habe ich dir geholfen.}
{152}{}{Genau. Du hast mir echt den Hintern gerettet!}
{153}{}{Moment, du brauchst doch nicht schon wieder Geld, oder?}
{154}{}{Nein, nein! Ich wollte mich nur noch mal bedanken. [Er holt eine Plasmagranate hervor.] Die habe ich beim Durchwühlen des Muells gefunden. Du kannst sie wahrscheinlich besser gebrauchen. Tschüssi!}
{155}{}{Wow, was die Leute alles wegwerfen ... Danke, Kleiner!}

#Female version
{1110}{}{Bitte, gnädige Frau, ich brauche wirklich Ihre Hilfe! Bitte, nur ein bisschen Kleingeld. So viel Sie entbehren können! Ich verlange ja nicht viel ...}
{1116}{}{Nein, gnädige Frau, ich habe keinen Hunger. Es ist nicht mal für mich.}
{1120}{}{Ja, gnädige Frau! Genau! Vielleicht bin ich nicht der beste Arbeiter, aber ich habe die ganze Woche hart gearbeitet! So ein gieriges Arschloch, das ist er!}
{1124}{}{Danke, Ma'am! Vielen, vielen Dank! Jetzt brauche ich nur noch 90 Dollar, damit meine Eltern mich nicht verprügeln. Spitze!}
{1128}{}{Aber, Ma'am ...}
{1133}{}{Oh wow! Du bist der beste Mensch, dem ich je begegnet bin! Wirklich, wirklich! Ich will genauso werden wie du!}
{1142}{}{Hier ist das Geld.}
{1143}{}{Milton will dich hier weghaben, also hat er mir das Geld gegeben ... Und ich behalte es, du Trottel! Jetzt verpiss dich, bevor ich dir den Arsch versohle!}

{1150}{}{Warten Sie, Miss! Sie erinnern sich doch an mich, oder? Sie haben mir im Café geholfen ...}