{100}{}{Du siehst Nick Hauer.}
{101}{}{Du siehst einen Mann mit dunkler Sonnenbrille und staubiger Robe. Sieht aus, als hätte er eine Menge Wüstenreisen hinter sich.}
{102}{}{Sie sind ganz nah ...}
{103}{}{Danke, Freund. Ohne dich hätten wir es nicht geschafft.}
{104}{}{Danke für deine Hilfe. Jetzt müssen wir nur noch die Toten begraben und uns auf den Weg nach San Francisco machen. Das wird man so schnell nicht vergessen.}
{105}{}{Was? Was sagt er, Terry?}

{110}{}{Halt! Hörst du das?}
{111}{}{Sie kommen näher, Nick. Das sieht gar nicht gut aus.}
{112}{}{Verdammt! Deveraux' Familie hat uns aufgehalten. Wir haben keine Wahl, Freund. Bei diesem Mondlicht kommen wir nicht ungesehen davon. Hast du eine Idee? Vielleicht sollten wir uns in diesem Haus verstecken und hoffen, dass seine Mauern uns schützen.}
{113}{}{Das Ding geht hoch wie eine Kerze. Lauf, ich halte sie auf.}
{114}{}{Wenn wir uns hier verschanzen, schaffen wir es vielleicht.}
{115}{}{Immer noch den Helden spielen, Freund? Na, viel Glück. Es wäre eine schreckliche Verschwendung, wenn ein Mann wie du für Fremde sterben würde.}
{116}{}{Geh einfach. Uns läuft die Zeit davon.}
{117}{}{Ich komme allein zurecht. Du solltest dich darauf konzentrieren, sie in Sicherheit zu bringen.}
{118}{}{Du hast recht. Das wird eine beschissene Nacht.}
{119}{}{Los geht's!}

#Female version
{1103}{}{Danke, Freund. Ohne dich hätten wir das nicht geschafft.}
{1115}{}{Immer noch den Helden spielen, Freund? Na, viel Glück. Es wäre eine schreckliche Verschwendung, wenn eine Frau wie du für Fremde sterben würde.}
