{100}{}{Du siehst einen Stadtbewohner.}
{101}{}{Du siehst einen ziemlich zwielichtig aussehenden Mann.}

{110}{}{[Er scheucht dich hastig weg] Weitergehen, wir führen gerade ein wichtiges Gespräch mit meinem Partner.}
{111}{}{Hör auf mit dem Scheiß. Ich liefere dir den Chemiker und seinen Freund aus. Dafür brauche ich deine Empfehlung für Stryker.}
{112}{}{Du störst hier ein wichtiges Geschäft. Ich zahle dir 1.000 $, wenn du dich von der Straße verziehst und die beiden uns überlässt.}
{113}{}{Ich weiß, warum du hier bist. Mein Angebot: Entweder du verziehst dich von der Straße, oder Mr. Thompson und ich kümmern uns um dich.}
{114}{}{Du musst hier weg. Sofort.}
{115}{}{Na schön, ich gehe ja schon.}

{116}{}{Gute Entscheidung. Geh vor, wir sind direkt hinter dir.}
{117}{}{Ach, ich wollte mich sowieso nicht in diesen Scheiß einmischen. Gebt uns das Geld, dann sind wir weg.}
{118}{}{Thompson ist schon im Hotel? Scheiße, dafür habe ich mich nicht verpflichtet. Wir verschwinden.}
{119}{}{Ach ja?}
{120}{}{Ich meine es ernst. Äh, Devereaux hat eine Bombe gebaut und ist bereit, das ganze Gebäude in die Luft zu jagen. Er hat den Mumm dazu. Der Mann sitzt in der Falle, verstehst du? Er ist jetzt verzweifelt und bereit, das Äußerste zu tun. Bring ihn nicht dazu.}
{121}{}{Verdammt, ich wusste, dass er so verrückt ist. Hör zu, wenn du abhauen willst, ist das dein Problem. Du wirst sowieso geschnappt. Aber lass die anderen sterben, nicht mich. Ich warte irgendwo anders ab.}
{122}{}{Gut.}
{123}{}{Hier ist das Geld.}
{124}{}{Was zum Teufel machst du hier? Ich bin Strykers persönlicher Consigliere, und du störst mein geheimes Geschäft. Und jetzt verschwinde!}
{125}{}{Oh, tut mir leid, wir haben das nicht gleich richtig verstanden. Wir haben den Befehl des Chefs wohl falsch aufgefasst ... Kein Problem, wir mischen uns nicht ein.}
{126}{}{Geh.}