{100}{}{Du siehst einen Karawanenhändler.}
{101}{}{Du siehst einen ganz gewöhnlichen Karawanenwächter. Er isst gerade.}

#Ïîïûòêà çàãîâîğèòü ïğè îòğèöàòåëüíîé ğåïóòàöèè ó êàğàâàíùèêîâ
{110}{}{Ich habe schon eine Menge über jemanden gehört, der so aussieht wie du. Und nichts davon war gut.}
{111}{}{Äh ... ich bin beschäftigt. Sprich mit jemand anderem.}
{112}{}{Äh ... nein danke, ich brauche niemanden zum Reden.}
{113}{}{Hör mal, kannst du mich einfach in Ruhe lassen?}

#Äèàëîã
{120}{}{Hallo.}
{121}{}{Ist dieser Tisch frei?}
{122}{}{Tschüss.}

{123}{}{Ich spendiere dir nichts, falls du darauf aus bist. Aber gegen ein kleines Gespräch habe ich nichts einzuwenden.}
{124}{}{Dann plaudern wir. Du bist bei der Karawane, richtig?}
{125}{}{Na dann, tschüss.}

{126}{}{Ja, ich bin einer der Wachen. Wenn du meinen Boss suchst, er ist auf dem Parkplatz. Der Kerl in der Metallrüstung.}
{127}{}{Erzähl mir etwas über das Karawanengeschäft.}

{128}{}{In Reno gibt es etwa ein Dutzend unabhängige Karawanen, aber sie bedienen nur den lokalen Markt – Kleinkram. Es gibt nur zwei Karawanen für den Fernverkehr mit Niederlassungen in Reno – eine hat ihren Sitz in Las Vegas, die andere in Salt Lake City. Manchmal kommt eine Karawane aus dem Osten, aber das ist selten. Außerdem gibt es noch die "Nevada Express", aber die befördern nur Leute, keine Waren.}
{129}{}{Du hast Karawanen erwähnt, die nach Osten und Westen fahren. Was ist mit Norden und Süden?}
{130}{}{Warum transportiert die "Nevada Express" keine Waren?}
{131}{}{Erzähl mir etwas über die unabhängigen Karawanen vor Ort.}
{132}{}{Warum hat Reno keine eigene Fernverkehrskarawane?}
{133}{}{Das war sehr aufschlussreich, aber ich muss los.}

{140}{}{Im Norden gibt es nichts außer ein paar kleinen Siedlungen. Sie haben nie genug, um die Reise lohnenswert zu machen.}
{141}{}{Ich habe gehört, jemand habe vor Kurzem eine Route nach Black Rock eingerichtet. Vielleicht ändert sich das also gerade.}
{142}{}{[Weiter]}
{143}{}{Und der Süden? Vergiss es. Die karge Wüste ist schon schlimm genug, aber dahinter liegt das von Atombomben verbrannte Land. Je weiter du gehst, desto schlimmer wird es. Angeblich gibt es dort eine Stadt, wenn man weit genug kommt, aber das kann den Aufwand nicht wert sein. Ich habe nur von einer Karawane gehört, die von dort heraufgekommen ist. Ich habe den Mann nie gesehen, aber gehört, dass er ziemlich übel zugerichtet ist.}
{144}{}{Verstehe. Was kannst du mir sonst noch über das Karawanengeschäft erzählen?}

{145}{}{Sie haben es tatsächlich geschafft, ein paar alte Busse aus der Zeit vor dem Krieg wieder flottzumachen. Damit kann man viele Leute schnell befördern, aber sie sind bei Weitem nicht so robust wie unsere von brahmin angetriebenen Karren, und nach 70 Jahren sind die Highways auch nicht mehr das, was sie einmal waren. Sie können es sich nicht leisten, ihre Fahrzeuge zu riskieren, indem sie mehr Gewicht transportieren.}
{146}{}{Nicht viel, ehrlich gesagt. Sie machen Geschäfte mit Farmen und anderen Leuten am Stadtrand. Ein paar der Wagemutigeren tauschen sogar Lebensmittel mit den Cheyenne, aber ich habe gehört, dass sie in letzter Zeit nicht viel anzubieten haben.}
{147}{}{In Reno gibt es viel zu viele Schwierigkeiten, um ein neues Geschäft aufzuziehen. Und so eine lange, gefährliche Reise ist weder einfach noch billig. Vegas und Salt Lake City sind etwas besser dran und können es sich leisten, eigene Karawanen auszurüsten, aber Reno ist für so etwas nicht in der Verfassung.}
