{100}{}{Du siehst Barton, den Händler.}
{101}{}{Du siehst einen müden Händler, der lustlos seine Waren auf einem Tisch durchstöbert.}

#Barter:
{110}{}{Suchst du etwas, Freund?}
{111}{}{Ja, zeig mir, was du hast.}
{112}{}{Ich glaube nicht. Auf Wiedersehen.}

{113}{}{Es war mir ein Vergnügen, mit dir Geschäfte zu machen. Sonst noch etwas?}
{114}{}{Zeig mir noch einmal, was du hast. Ich glaube, ich habe etwas vergessen.}
{115}{}{Ja, ich glaube, das war's. Auf Wiedersehen.}

{116}{}{Na, wen haben wir denn da! Ich freue mich immer, dich zu sehen. Gutes soll mit Gutem vergolten werden, oder? Ich glaube, auf Empfehlung von dem-oder-derjenigen kann ich dir einen kleinen Rabatt geben. Solche Preise mache ich nicht für jeden!}
{117}{}{Dann legen wir mal los.}
{118}{}{Danke, aber ich bin nicht zum Einkaufen hier.}

{119}{}{Ich habe vor Kurzem mit ein paar Karawanenleuten gesprochen. Sie sagen viel Gutes über dich. Ich finde, du hast einen kleinen Rabatt verdient.}
{120}{}{Ich habe vor Kurzem mit ein paar Karawanenleuten gesprochen. Sie hatten nicht viel Gutes über dich zu sagen. Und ich vertraue ihrem Urteil. Von jetzt an wird es hier für dich also teurer. Und versuch gar nicht erst zu diskutieren. Du weißt, was du getan hast.}
{121}{}{In den örtlichen Slums reden alle über dich. Ich schätze, was du für diese armen Leute tust. Wenn du bei mir einkaufen willst, gebe ich dir einen netten Rabatt.}
{122}{}{In den örtlichen Slums reden alle über dich. Und nicht gerade Gutes. Weißt du, was mit Leuten passiert, die sich in dieser Stadt so aufführen? Ihre Preise werden erhöht, damit sie sich zum Teufel scheren. Aber ich will keinen Streit, anders als manche andere. Nur damit du Bescheid weißt: Meine Preise sind für dich jetzt höher.}
{123}{}{Du hast 10% dabatt in Bartons Laden erhalten.}
{124}{}{Du hast 5% dabatt in Bartons Laden erhalten.}
{125}{}{Sheriff? Du bist der neue Sheriff von Uranium City? Unglaublich! Es ist mir eine Ehre, dich in meinem Laden zu sehen. Übrigens habe ich etwas Kleines für einen besonderen Kunden zurückgelegt. Einen .44-Revolver und etwas Munition! Ich glaube, der passt hervorragend in dein Holster. Ich verkaufe ihn dir mit Rabatt.} 
{126}{}{[Als er dein zwielichtiges Aussehen bemerkt, runzelt er die Stirn und schüttelt den Kopf] Denk nicht mal dran. Ich erkenne deinesgleichen schon von Weitem. Lass die Hände da, wo ich sie sehen kann!}
{127}{}{Barton hat deine diebischen Neigungen erkannt und seine Preise um 10% erhöht.}
{128}{}{Na, sieh dir das an. Eine Bande Plünderer hat vor Kurzem die Basis Hawthorne aufgebrochen. Sie haben alles mitgenommen, was nicht niet- und nagelfest war. Dabei sind ein paar richtig feine neue Spielzeuge abgefallen. Schau dich um, vielleicht findest du ja etwas, das dir gefällt.}

{130}{}{Was sind das für Tickets auf dem Tresen? Tickets für die Postkutsche?}
{131}{}{Ja. Die Postkutsche nimmt nur Bargeld, also kaufe ich ein paar "Nevada Express"-Tickets für Leute, die andere Dinge eintauschen wollen. Nimm dir ruhig eins, so musst du nicht warten, bis dein Geldbeutel voll ist.}
{132}{}{Wo ist der Haken?}
{133}{}{Gut, tauschen wir.}
{134}{}{Den gibt es nicht. Die Postkutsche nimmt nämlich nur Bargeld, also ... Moment, das habe ich ja schon gesagt. Ansonsten liegt es ganz bei dir. Du kannst gern beim Verwalter von "Nevada Express" kaufen, wenn du Bargeld hast.}
{135}{}{Und ich traue dem Braten immer noch nicht. Du hättest das nicht gemacht, wenn du dir davon keinen Gewinn versprechen würdest.}
{136}{}{[Er verzieht die Lippen zu einem grimmigen Grinsen] Na gut, erwischt. Ja, ich mache dabei Gewinn. Tickets bei mir zu kaufen ist viel teurer. Aber ich finde, das ist fair, wenn man bedenkt, dass ich die eingetauschten Waren später noch bearbeiten muss.}
{137}{}{Danke, aber ich war wegen etwas anderem hier.}

#About Jay
{140}{}{Ich suche Jay Kukish, einen Biker. Hast du ihn gesehen?}
{141}{}{Na ja, als ob ich die Biker alle beim Namen kennen würde. In letzter Zeit waren allerdings ziemlich viele hier. Sie schienen etwas zu planen. Ich habe gesehen, wie einer zur Silver Legacy gegangen ist, um dort zu übernachten. Frag den Typen an der Rezeption nach mehr Infos.}
{142}{}{Danke.}

##############################################################################
#
#                            Questions
#
##############################################################################

#Questions
{250}{}{Ich habe eine Frage.}
{251}{}{Nur zu.}
{252}{}{Im Moment nichts.}
{253}{}{Danke, aber ich habe noch eine Frage.}
{254}{}{Das reicht fürs Erste.}

#Suggestions
{255}{}{Ich bin neu hier. Kannst du mir ein paar Tipps geben?}
{256}{}{Nun, ich würde dir nicht empfehlen, dich weiter als bis nach El Dorado vorzuwagen. Die Stadt ist für Neulinge gefährlich. Straßenräuber, Händler, Abschaum und schließlich Revolutionäre von beiden Seiten – Ärger zu finden war noch nie so einfach. Unser kleines Viertel rund ums Hotel ist der sicherste und kultivierteste Ort. Weißt du was? Geh einfach mit dem Empfangschef im Hotel reden. Er kann dir viel mehr über die Stadt erzählen als ich.}
{257}{}{Warum gibt es hier so viele Karawanenfahrer?}
{258}{}{Das hier ist der einzige Karawanenhalt in der Stadt. Ein guter Ort, um sich vor der nächsten Reise auszuruhen. Für mich ist das umso besser – sie haben oft großartige Waren dabei. Deshalb dreht sich hier der größte Teil des Handels in der Stadt.}

#Slaves
{260}{}{Ich suche einen Sklaven ... Na ja, einen bestimmten Sklaven.}
{261}{}{Hey, hör zu, ich handle nicht mit Sklaven. Nicht, dass sie hier besonders beliebt wären. Den Bewohnern geht es auch nicht besser, nur tragen sie keine Halsbänder.}
{262}{}{Na gut, nehmen wir an, ich brauche einen Sklaven. Wo würde ich einen bekommen?}
{263}{}{Hm, normalerweise gründen diejenigen, die Sklaven brauchen, entweder eine Bande oder bestellen sie aus Vegas. Aber das kommt selten vor. Der größte Sklavenhalter hier ist Mister Oliver Luciano. Du könntest versuchen, ihm einen Sklaven abzukaufen. Wright hat früher auch Sklaven gekauft, bevor er seine Minen schloss.}
{264}{}{Also dann Luciano. Danke für den Rat.}

#Bikers
{265}{}{Was weißt du über die Biker?}
{266}{}{Nicht viel. Sie reden nicht gern über ihr Leben und bleiben normalerweise nicht lange hier. Die meisten halten sie für eine gewöhnliche Bande – Wanderer mit guten Waffen und einer unerträglichen Einstellung. Aber die „Nevada Express“ erzählen davon, dass Biker eine ihrer Postkutschen überfallen haben. Klingt ziemlich überzeugend. Frag Tuco, wenn du mehr über den Überfall erfahren willst.}

#B.Lou's Traitor
{270}{}{Hast du einen dicken Mann mit einer Narbe am Hals gesehen?}
{271}{}{Weißt du, wer der Glatzkopf am Eingang ist?}
{272}{}{Wo ist der Glatzkopf vom Eingang jetzt?}

{273}{}{Ja, ich hab so jemanden gesehen. Er hing bei den Karawanenfahrern herum und wollte irgendwohin. Frag sie, vielleicht können sie dir mehr sagen.}
{274}{}{Ein zwielichtiger Kerl. Redet wie ein Bandit, aber seine Kleidung ist in Ordnung, und er bemüht sich um einen hohen Tonfall. Ganz sicher nur zu Besuch, besonders wenn er versucht, mit den Karawanenleuten ein Geschäft abzuschließen. Die sind auch nicht blöd und merken, wenn etwas faul ist. Sonst weiß ich nichts über ihn.}
{275}{}{Ich glaube, er ist mit einer Karawane nach Vegas aufgebrochen, wenn mich meine Erinnerung nicht täuscht.}

#About Nuka-Cola
{276}{}{Wir könnten ein Geschäft über den Verkauf von Nuka-Cola abschließen.}
{277}{}{Aber ich verkaufe keine Lebensmittel. Die Karawanenleute kaufen im Silver Restaurant ein. Oder, wenn es gar nicht anders geht, in dem kleinen Café bei El Dorado. Vielleicht wären die eher interessiert.}
{278}{}{Restaurant oder Café? Ich sehe nach, ob sie Interesse haben.}

#About weapon sales
{282}{}{Was ist mit dem mageren Waffenangebot los?}
{283}{}{Willst du mich auf den Arm nehmen?! In dieser Stadt kannst du dich glücklich schätzen, wenn du überhaupt ein gutes Gewehr im Angebot findest. Und wenn es dann auch noch erschwinglich ist, hast du doppelt Glück!}
{284}{}{Warum?}
{285}{}{Hm, gute Frage. Ich versuche mal zu erklären, warum das meiner Meinung nach so ist.}
{286}{}{Nur zu, ich bin gespannt.}
{287}{}{Jetzt nicht.}
{288}{}{Zunächst einmal gab es in dieser Stadt vor dem Großen Krieg kaum Militär, also gibt es hier nur zivile Waffen. Und sobald eine gute Waffe auf dem Markt auftaucht, kauft sie irgendein reicher Gangster. Sogar uralte Stücke werden noch benutzt, zum Beispiel von den Wachen der El Dorado.}
{289}{}{[Weiter]}
{290}{}{Du fragst dich wahrscheinlich, wo die Militärwaffen sind, die stärksten und zuverlässigsten. Ich würde vermuten, dass sie auf den Militärbasen geblieben sind, denn bisher konnte noch niemand eindringen. Ich habe Gerüchte über drei Basen in Nevada gehört. Die Mutigen, die zurückzukehren versuchten, erzählten von tödlichen Geschütztürmen und schrecklichen Mutanten. Alles nur Gerüchte, aber sie scheinen nicht aus der Luft gegriffen zu sein. Wie sonst lässt sich dieser Mangel an Waffen militärischer Qualität in einem Land mit einer derart militaristischen Vergangenheit erklären? Allerdings gibt es hier jemanden mit einem großartigen Waffenarsenal: Wind of War. Sie lagern alles auf ihrer Basis, was sie erbeuten oder ertauschen konnten.}
{291}{}{Was ist das für eine Waffe, die du bei den Wachen der El Dorado erwähnt hast?}
{292}{}{Tommy Guns? Die sind verdammt alt, die gehören ins verdammte Museum. Ich bin mir ziemlich sicher, dass der Besitzer sie nur wegen des Stils gekauft hat. Angeberei, sonst nichts. Ich glaube, er hat es geschafft, jede Tommy Gun im Staat zu kaufen. Zumindest habe ich außerhalb von El Dorado keine gesehen.}
{293}{}{Danke für die Erklärung.}

#Bundy's photo
{294}{}{Dieses Mädchen auf dem Foto – hat sie hier jemals ihr Gesicht gezeigt?}
{295}{}{Süß, aber solche Typen kommen normalerweise nicht hierher.}
{296}{}{Was ist mit dem Namen Ted Bundy? Sagt dir der etwas?}
{297}{}{Nein. Ich verkaufe hier Waren. Wenn du Informationen willst, frag einen Barkeeper. Heh, auf so was stehen sie – das ist schließlich ihr Job.}
{298}{}{Verstanden.}

#Affiliate
{300}{}{Ist das der einzige seriöse Laden in Reno?}
{301}{}{Nun, wie soll ich es sagen ... Ich habe den größten Laden in Reno, das stimmt. Das verdanke ich dem Karawanenhalt und ihrem Vertrauen. Aber ich habe einen Geschäftspartner weiter südlich. Und der hat oft ausgefallenere Waren auf Lager.}
{302}{}{Erzähl mir mehr über diesen Geschäftspartner.}
{303}{}{Nun, ich habe sozusagen einen Helfer. So einen risikofreudigen Kerl, der im Süden Handel treibt. Die einzige normale Stadt dort unten ist der Hub. Allerdings ist der Weg dorthin lang und beschwerlich. Du musst dich durch die meisten Straßen im Süden durchschlagen. Er heißt übrigens Hardy. Du wirst ihn mit niemandem verwechseln – Ghule sind in dieser Gegend selten.}
{304}{}{Hm. Die Kosten für eine so gefährliche Reise müssten sich doppelt bezahlt machen. Das heißt, im Süden gibt es etwas Besonderes. Warum gibt es dann nur eine Karawane?}
{305}{}{Hey, du scheinst einiges über Handel zu wissen! Unsere Gegend hatte wirklich Glück – der Große Krieg hat den Großteil der Stadt nicht so stark getroffen, und die Strahlung war geringer. Aber weiter südlich ist jede halbwegs große Stadt zu radioaktiven Trümmern geworden. Trotzdem sind Waffen und Munition dort viel leichter zu finden. Deshalb besteht unser größter Handelszweig darin, sie mit Medikamenten und Vorräten zu versorgen und dafür ihre Waffen zu bekommen. Und es gibt nur eine Karawane, weil sich nicht wirklich genug Leute finden, die ihr Leben riskieren wollen.}
{306}{}{Gibt es irgendwo eine Karawane, die zum Hub fährt?}
{307}{}{Wegen Hardy. Ich muss ihm eine Nachricht für den Hub mitgeben.}
{308}{}{Du hast 100 EP erhalten, weil du mit deinem Feilschen erfolgreich etwas über eine Karawanenroute erfahren hast.}

{310}{}{Ich muss ihm eine Nachricht für den Hub mitgeben.}
{311}{}{Kein Problem, ich gebe ihm den Brief mit. Aber ich erwarte ein Trinkgeld, verstanden?}
{312}{}{Bei deinem Ruf mache ich das. Kein Problem.}
{313}{}{Großartig. Hier ist es, und hundert Dollar für deine Mühen.}
{314}{}{Großartig. Hier ist es.}
{315}{}{Nein danke, ich glaube, ich versuche, Hardy zu finden, um ihm den Brief persönlich zu geben ...}
{316}{}{Dann wünsche ich dir viel Glück. Oh, das wirst du brauchen. Die Route nach Süden ist für eine Karawane schwierig, und es gibt dort fast keine Siedlungen. Die Suche könnte also eine ganze Weile dauern.}
{317}{}{Verstanden.}
{318}{}{Du hast den Auftrag von Lewis Birch erledigt.}
{319}{}{Das Paket fiel aus deiner Tasche, während du mit dem Händler gesprochen hast.}

#Female version:
{1110}{}{Suchst du etwas, Schönheit?}
{1114}{}{Zeig mir noch einmal, was du hast. Ich glaube, ich habe etwas vergessen.}
{1136}{}{[Zieht die Lippen zu einem finsteren Grinsen] Na gut, du hast mich erwischt. Ja, ich mache Gewinn. Wenn du die Tickets bei mir kaufst, sind sie viel teurer. Aber ich finde, das ist fair, wenn man bedenkt, dass ich die ertauschten Waren später noch bearbeiten muss.}
