{100}{}{Du siehst einen Fremden.}
{101}{}{Du siehst Maxson.}
{102}{}{Du siehst Balder.}

{103}{}{Du siehst einen völlig kahlen Mann. Er zupft ständig an seinem Kragen.}
{104}{}{Du siehst Maxson. Er scheint seinen Hals unter dem Kragen verstecken zu wollen.}
{105}{}{Du siehst Balder, den Mann, der Big Louie verraten und sich aus der Stadt geschlichen hat.}

{106}{}{Big Louies schmutziges Geschäft ist erledigt. Du erhältst 1000 Erfahrungspunkte.}
{107}{}{Maxson versucht zu fliehen!}

#Ïîâ'îğíûé ïğèõîä ïîñëå ïåğâîãî äèàëîãà áåç îïîçíàíèÿ
{110}{}{Wieder einmal führt Maxon seine Träume von Las Vegas vor. Er imitiert einen Cowboy, der ein Lasso schwingt und versucht, auf einem Stier zu reiten.}
{111}{}{Willst du immer noch nach Vegas?}
{112}{}{Oh. Ja. Einen angenehmen Aufenthalt.}

#Ïåğâûé äèàëîã, äî îïîçíàíèÿ
{120}{}{Hallo, Partner! Wartest du auch?}
{121}{}{Nein, tue ich nicht. Willst du irgendwohin?}
{122}{}{Nein, ich bin nur auf der Durchreise.}

{123}{}{Ach, na gut. Mach's gut.}
{124}{}{[Gehen]}

{125}{}{Ja, ich lasse mich nach Vegas mitnehmen. Man sagt, im Ödland gibt es keinen besseren Ort, um sein Glück zu versuchen!}
{126}{}{Las Vegas?}
{127}{}{Und was ist mit Reno?}
{128}{}{Warum gehst du nicht gleich?}
{129}{}{Und wer bist du eigentlich?}
{130}{}{Na gut. Tschüss.}

{131}{}{Die Stadt, die niemals schläft! Man sagt, die Bomben hätten sie kaum getroffen. DAS ist wahre Zivilisation, Bruder! Casinos, Hotels und Karawanen aus allen Ecken Nevadas! Vegas, Baby, Vegas! ICH KOMME ZU DIR, BABY!!! [Er tanzt auf der Stelle und johlt fröhlich]}
{132}{}{In Reno hat man entweder Glück oder ist tot. Ich hätte gern mehr Möglichkeiten.}
{133}{}{Ach, diese Typen, weißt du – die sind pünktlich wie ein Uhrwerk. Zu pünktlich! Nur wegen eines einzigen Fahrgasts ändern sie ihren Zeitplan nicht.}
{134}{}{Mein Name? Er ist ... Maxson. Einfach Maxson.}
{135}{}{Na gut ... Einfach Maxson. Vielleicht sehen wir uns wieder.}
{136}{}{Das hast du sehr seltsam gesagt.}
{137}{}{Nur Halsschmerzen. Vergiss es.}

#Ğàñïîçíàíèå
{150}{}{Maxson, richtig? Hat man dich jemals Balder genannt?}
{151}{}{Du erhältst 100 Erfahrungspunkte dafür, dass du Maxson erkannt hast.}

{152}{}{[Das Lächeln bleibt ihm auf den Lippen, verschwindet jedoch aus seinen Augen] Hey, das ist echt mies! Ich finde, der Glatzkopf-Look steht mir!}
{153}{}{Ich rede nicht von deinem Kopf, Idiot. Warum gehen wir nicht ein Stück zur Seite und reden unter vier Augen?}
{154}{}{Ach ja? Wie wär's, wenn ich es Big Louie zeige und eine zweite Meinung einhole?}

{155}{}{[Er starrt dich einen Moment lang finster an] Also ... Hör zu. [Er sieht sich um und beugt sich zu dir] Ich will einfach nur raus. Raus aus der Bande, raus aus diesem Leben. Wenn du meinen Rat willst, machst du dasselbe. Ich will einfach verschwinden. Okay?}
{156}{}{Das glaube ich nicht. Ich bin nicht den ganzen Weg hierhergekommen, nur um unverrichteter Dinge wieder abzuziehen.}
{157}{}{Vielleicht. Warum?}

{158}{}{Hmm. In Vegas wartet ein SEHR lukrativer Auftrag auf mich, und den lasse ich mir nicht entgehen. Also, was hast du vor? Einen wertvollen Kunden der "Nevada Express" hier mitten in der Öffentlichkeit umbringen? Na los, zeig's mir. Oder hast du dir schon in die Hose geschissen?}
{159}{}{Nein, du Arschloch, du kommst mit mir in die Slums. Ich habe dich im Visier.}
{160}{}{Nein, du Arschloch, du kommst mit mir in die Slums. Denk gar nicht erst daran wegzurennen.}
{161}{}{Aber verdammt noch mal! Ist mir scheißegal! Sieh mir nur zu!}
{162}{}{Ehrlich gesagt ist es mir ziemlich egal. Ich gehe.}

#Ïğèíÿ'èå ğåøåíèé - îáìåí íà îğóæèå
{163}{}{Wenn du hier raus willst, kann ich dir helfen.}
{164}{}{Glaubst du wirklich, dass ich dir das abkaufe?}
{165}{}{Warum nicht? Glaubst du, ich will den Rest meines Lebens mit Big Louie verbringen? Nein, da wäre mir ein guter Freund in Vegas lieber.}
{166}{}{Wie du meinst. Du kommst mit mir in die Slums. Ich habe dich im Visier.}
{167}{}{Wie du meinst. Du kommst mit mir in die Slums. Denk gar nicht erst daran wegzulaufen.}
{168}{}{Dann muss ich wohl meinen Befehlen folgen. Glaubst du, ich ziehe das nicht durch? Sieh es dir an.}
{169}{}{Ehrlich gesagt ist es mir ziemlich egal. Ich gehe.}

{170}{}{Das glaube ich dir nicht. Was willst du Big Louie erzählen? Dass du mich hast laufen lassen?}
{171}{}{Ich gebe ihm deine Schrotflinte als Beweis.}
{172}{}{Ich weiß es noch nicht. Ich komme wieder, wenn mir etwas eingefallen ist.}

{173}{}{Netter Versuch. Meine einzige Waffe gebe ich nicht so einfach her.}
{174}{}{Willst du sie eintauschen?}
{175}{}{Was ist, schwere Entscheidung?}
{176}{}{Versuchen wir's noch mal.}
{177}{}{Hast du deine Meinung geändert?}
{178}{}{Entscheide dich.}
{179}{}{Nee. Ich interessiere mich nur für Schrotflinten und Gewehre.}
{180}{}{Ich komme wieder, wenn ich eine Lösung dafür gefunden habe.}
{181}{}{Du hast eine friedliche Lösung für das Dilemma der Maxsons gefunden.}
{182}{}{Großartig. Ich bin sicher, jetzt sind alle glücklich.}
{183}{}{Ja, vielleicht.}

#Ïğèíÿ'èå ğåøåíèé - áîé â 'ğóùîáàõ:
{184}{}{[Er knirscht mit den Zähnen] Na schön ... Als hätte ich eine Wahl. Bringen wir's hinter uns ... }
{185}{}{[Folge ihm]}
{186}{}{[Er knirscht mit den Zähnen] Na schön ... So endet es doch immer ... }
{187}{}{[Folge ihm, bevor er entkommt.]}
{188}{}{Hey, Leute, ich muss noch was erledigen. Bin gleich zurück.}

{191}{}{Ha! Willst du mir Angst machen, Zuckerschnute? Deine Aufgabe ist es, die Beine breit zu machen, nicht mit deinen kleinen Fäustchen herumzufuchteln. Verpiss dich!}
{192}{}{Na warte! Gleich wirst du sehen, was meine kleinen Fäustchen mit deinem Kiefer anstellen!}
{193}{}{Na schön, Arschloch, wart hier. Ich komme wieder!}
{194}{}{Du hast nicht mal genug Eier, um mit mir um die Ecke zu gehen und das zu klären, was? Zu feige, dich mir wie ein Mann zu stellen?}
{195}{}{[Seine Augen blitzen auf] Feige?! Jetzt hast du's versaut, Schlampe!}
{196}{}{Versuch gar nicht erst wegzulaufen. Ich beobachte dich.}
{197}{}{Netter Versuch. Aber so leicht kannst du mich nicht austricksen, Lady.}
{198}{}{Wie du willst. Dann erledigen wir's eben hier.}
{199}{}{Na schön, Arschloch, warte hier. Ich bin gleich zurück.}
{200}{}{Und mich ohne Waffe zurücklassen? Nein, so leicht kommst du mir nicht davon.}

#Ïëàâàşùèå ôğàçû:
{201}{}{Bringen wir es hinter uns.}
{202}{}{Na, na ... }
{203}{}{Warte, das dauert nicht lange ... }
{204}{}{Du machst einen Fehler. Einen großen Fehler.}
{205}{}{Das dauert nicht lange.}
{206}{}{Was habe ich getan, um das zu verdienen?!}
{207}{}{Oh Scheiße, was zum Teufel ... }
{208}{}{Und der Tag hatte so gut angefangen ... }
{209}{}{Wir könnten das friedlich regeln ... }
{210}{}{Zu spät, weißt du ... }

{220}{}{Und ... LAUF!}
{221}{}{Zeit, verdammt noch mal abzuhauen!}
{222}{}{Beine, lasst mich jetzt nicht im Stich!}
{223}{}{Zeit abzuhauen!}
{224}{}{Vollgas!}
{225}{}{Solange mich niemand sieht, kann ich entkommen ... }

{228}{}{Ja, ich komme! Ich komme!}
{229}{}{Wir könnten einen Deal machen ... }
{230}{}{Du bist dran! Lass mich einfach in Ruhe!}

{231}{}{Na, na, was haben wir denn hier?}
{232}{}{[Weiter]}

#Female character
{1120}{}{Hey, schöne Lady! Wartest du auch?}
{1131}{}{Die Stadt, die niemals schläft! Man sagt, die Bomben hätten sie kaum getroffen. DAS nenne ich wahre Zivilisation, Schwester! Casinos, Hotels und Karawanen aus allen Ecken Nevadas! Vegas, Baby, Vegas! ICH KOMME ZU DIR, BABY!!! [Er tanzt auf der Stelle und johlt vergnügt]}
{1156}{}{Das glaube ich nicht. Ich bin nicht den ganzen Weg hierhergekommen, nur um unverrichteter Dinge wieder abzuziehen.}
{1158}{}{Hm. Ich habe in Vegas einen SEHR lukrativen Deal an Land gezogen, und den lasse ich mir nicht entgehen. Also, was willst du tun? Einen wertvollen Kunden der "Nevada Express" hier mitten in der Öffentlichkeit umbringen? Na los, zeig's mir. Oder hast du dir schon in die Hose gemacht?}
{1170}{}{Ich glaube dir nicht. Was willst du Big Louie erzählen? Dass du mich laufen lassen hast?}
{1204}{}{Du machst einen Fehler. Einen großen Fehler.}
{1230}{}{Du bist dran! Lass mich einfach in Ruhe!}
