{100}{}{Du siehst einen Besucher.}
{101}{}{Du siehst einen Gast, der ein Glas Nuka-Cola aufmerksam studiert.}
{102}{}{He! Du bist also derjenige, der diesen Fusel liefert? Gute Arbeit! Weiter so!}

{110}{}{Würdest du mir noch ein Glas einschenken?}
{111}{}{Ich hoffe, ich kriege davon keine Blähungen ...}
{112}{}{Hmm ... Was für ein seltsamer Geruch ...}
{113}{}{Ich frage mich, woraus das gemacht ist.}
{114}{}{Weißt du, das Zeug aus der Vorkriegszeit war besser ...}
{115}{}{... aber das ist inzwischen schal geworden, während das hier frisch ist!}
{116}{}{Sag die Wahrheit: Hast du das einer Leiche abgenommen oder einfach geklaut?}
{117}{}{Salt Lake City? Nie davon gehört.}
{118}{}{Wenn sie dort Nuka-Cola herstellen, werde ich den Ort auf jeden Fall besuchen!}
{119}{}{Wer ist dein Lieferpartner? Muss ein echter Experte sein.}
{120}{}{Das ist genau das, was ich gebraucht habe!}
{121}{}{Ich glaube, ich nehme eine Flasche für unterwegs.}
{122}{}{Solange ich nicht süchtig werde ...}