{100}{}{Du siehst einen Kunden.}
{101}{}{Vor dir steht ein zerlumpter Landstreicher mit einem armseligen Anschein einer Fliege um den Hals.}
{102}{}{[Wischt sich die Tränen ab] Danke, Freund, ich bin dir auf ewig dankbar!}
{103}{}{Ich muss hier weg, bevor die „Vergeltung“ eintrifft.}

#Story about grandma
{110}{}{Oh, ich sehe, der ehrenwerte Herr hat diese Stadt mit seiner Anwesenheit beehrt! Ja, ja, ich spreche mit Ihnen, mein Herr. Darf ich sagen, wie schwer es heutzutage ist, einem Mann mit guten Manieren zu begegnen? ... Möchten Sie mit mir ein Glas Orvietto Classico Campogrande trinken? - Aber warten Sie! Oh weh! Wie es scheint, habe ich mein Portemonnaie zu Hause vergessen. Das ist wirklich bedauerlich ...}
{111}{}{Keine Sorge, äh, mein Herr. Barkeeper! Ein Bier für diesen edlen Ausgestoßenen.}
{112}{}{Auf was für Ideen die Leute kommen, um ein Freibier abzustauben ... Verpiss dich, Säufer.}

{113}{}{Haben Sie es sich anders überlegt und beschlossen, mir Gesellschaft zu leisten, mein Herr?}
{114}{}{Na gut, hol dir ein Bier von der Bar. Ich zahl's.}
{115}{}{Selbst wenn ich wollte, würde der Gestank, der von dir ausgeht, meine Meinung mehr als gründlich ändern. Tschüss.}

{120}{}{[Er leert die Flasche fast augenblicklich und rülpst laut, während er sich mit dem Handrücken den Mund abwischt] Ugh ... Dieses Gesöff solltest du wirklich nicht trinken. Dafür bist du viel zu aristokratisch, he-he ... Danke, genau das hab ich gebraucht.}
{121}{}{Sieht aus, als hätte das deiner Höflichkeit wirklich einen Dämpfer verpasst, was?}
{122}{}{Na ja, normalerweise bin ich sehr höflich, aber manchmal wird's mir zu viel ... Interessiert es dich wirklich, warum ich so bin? Na gut, ich erzähl's dir. Ist kein großes Geheimnis. Alles dank meiner Oma, Gott hab sie selig. Sie hat sich zur feinen Dame gemacht, ganz vornehm, angezogen, als hätte sie ein Museum ausgeraubt. Spitze, Krimskrams um den Hals ... Eine ziemlich eckza ... erhabene Dame. Und ich musste damit leben. Sogar so ein Ding um den Hals tragen. Weißt du, warum?}
{123}{}{Ich hoffe, nicht, weil du ... ihr zu nah warst. Warum?}
{124}{}{Ich muss gleich gähnen. Hoffentlich kommt jetzt was Interessantes.}
{125}{}{Apfelkuchen! So, wie sie ihn gebacken hat ... Ich würde eine Woche lang nichts trinken, wenn ich ihn nur noch einmal schmecken könnte. Aber diese Welt ist nichts für Großmütter wie sie. Als es hart auf hart kam, fing sie selbst an, Kuchen zu verkaufen, fünfzehn Mäuse das Stück. Mir blieb nur ihr Anhänger ... Aber selbst den hab ich irgendwo in den Slums verloren. Er war ein ziemlich ... erlesenes Stück.}
{126}{}{Was für eine Geschichte ...}
{127}{}{Du hast die Kuchen doch nicht selbst gebacken, oder? Nur Spaß.}
{128}{}{Das ist nicht lustig! Ich hab sie wirklich geliebt. Auf die gute Art. Aber dieses verdammte Gesöff aus der Bar, das mir jeden Tag im Magen rumort – es vergiftet mein Leben. Oma hat mich unterstützt, mir geholfen, damit klarzukommen, und mir auf die Finger geklopft, wenn ich zu viel getrunken hab. Aber dann hab ich den Anhänger verloren ...}
{129}{}{Jeder glaubt, dass irgendjemand schuld ist. Hauptsache, nicht man selbst.}
{130}{}{Na ja, so ist das Leben.}
{131}{}{Wie dem auch sei, danke, dass du mir zugehört hast. Und noch mal danke fürs Bier. Schau irgendwann mal vorbei, ich freu mich, dich zu sehen.}
{132}{}{Na gut, tschüss.}
{133}{}{Du hast dir die Geschichte eines traurigen Säufers angehört und dafür 100 EP erhalten.}

#Talking after drink
{140}{}{[Er verbeugt sich unbeholfen] Es ist ein Vergnügen, dich wiederzusehen, sozusagen.}
{141}{}{Ich bin an ein antikes Stück gekommen. Erkennst du es?}
{142}{}{Ganz meinerseits.}

{143}{}{Das ist ... Unmöglich! Ihr seid wirklich ein edler Herr! Und ich dachte, so etwas käme nur in den Märchen meiner Oma vor. Danke, danke und nochmals danke!}
{144}{}{Gern geschehen. Hier, du Kuchenliebhaber.}
{145}{}{He, Finger weg! Ich arbeite nicht nur für ein „Danke“.}
{146}{}{Aber ... Es ist doch nur ein Nippes! Kaum eine Flaschenkappe wert! Oma würde sich im Grab umdrehen, wenn sie dich reden hörte! [Er schluchzt und schnäuzt sich in seine Fliege]}
{147}{}{Ja, ja, immer dasselbe Lied ... Zahlst du jetzt oder nicht?}
{148}{}{Na gut, du kannst es haben. Hör einfach auf zu jammern, Mamasöhnchen.}
{149}{}{[Er lässt sich Zeit und kramt in seinen stinkenden Lumpen. Schließlich dreht er sich zu dir um, wirft allen anderen im Raum einen misstrauischen Blick zu und drückt dir eine Handvoll schmutziger Münzen in die Hand. Du willst ganz bestimmt nicht wissen, woher sie stammen.] Mehr hab ich nicht ... Du Blutsauger.}
{150}{}{Viel besser. Jetzt kannst du deinen kleinen Nippes haben.}
{151}{}{Du hast dem Trunkenbold das Familienerbstück zurückgegeben und ihm die Hoffnung wiedergegeben. Vielleicht wird er von nun an selbstbewusster sein.}
{152}{}{Du hast dem Trunkenbold das Familienerbstück zurückgegeben und einmal mehr bewiesen, dass diese Welt nichts für Schwächlinge ist.}

#Female version
{1102}{}{[Wischt sich die Tränen ab] Danke, Freund, ich bin dir auf ewig dankbar!}
{1110}{}{Oh, ich sehe, die ehrenwerte Dame hat diese Stadt mit ihrer Anwesenheit beehrt! Ja, ja, ich spreche mit Ihnen, Fräulein. Darf ich sagen, wie schwer es heutzutage ist, einer Frau mit guten Manieren zu begegnen? ... Möchten Sie mit mir ein Glas Orvietto Classico Campogrande trinken? - Aber warten Sie! O je! Es sieht ganz so aus, als hätte ich meine Brieftasche zu Hause vergessen. Wie unglücklich ...}
{1113}{}{Haben Sie es sich anders überlegt und beschlossen, mir Gesellschaft zu leisten, gnädige Frau?}
{1120}{}{[Er leert die Flasche fast augenblicklich und rülpst laut, während er sich mit dem Handrücken den Mund abwischt] Ugh ... Dieses Gesöff solltest du wirklich nicht trinken. Dafür bist du viel zu aristokratisch, he-he ... Danke, genau das hab ich gebraucht.}
{1131}{}{Wie dem auch sei, danke, dass du mir zugehört hast. Und noch mal danke fürs Bier. Schau irgendwann mal vorbei, ich freu mich, dich zu sehen.}
{1143}{}{Das ist ... Unmöglich! Ihr seid wirklich eine edle Dame! Und ich dachte, so etwas käme nur in den Märchen meiner Oma vor. Danke, danke und nochmals danke!}
{1144}{}{Gern geschehen. Hier, du Kuchenliebhaber.}
