{100}{}{Du siehst den Ausbilder der Rekruten.}
{101}{}{Du siehst Edward Benson, den Ausbilder der Rekruten für "Nevada Express".}
{102}{}{Ich bin gerade beschäftigt. Bitte verschwende nicht meine Zeit.}
{103}{}{Das war die richtige Entscheidung, danke. Und jetzt zurück an die Arbeit ...}

{110}{}{Ich erledige Papierkram. Wenn es nicht um Geschäfte geht, lenk mich bitte nicht ab.}
{111}{}{Was ist? Siehst du nicht, dass ich versuche zu arbeiten?}
{112}{}{Na gut, ich gehe ja schon.}
{113}{}{Schon gut, ich lass dich in Ruhe.}
{114}{}{Wir reden später weiter.}

#About the attack
{116}{}{Na ja, wenn der Boss es gesagt hat ... Ja, ist passiert. [er setzt eine sehr förmliche Miene auf] Wir wurden losgeschickt, um das Notsignal zu untersuchen. Auf halbem Weg trafen wir auf Überlebende. Ohne uns wären sie gestorben. Wären sie weitergezogen, wären sie direkt den Cheyenne in die Arme gelaufen.}
{117}{}{Was, schon wieder? Sch... Um's kurz zu machen: Wir wurden losgeschickt, um ein Notsignal zu untersuchen, und auf halbem Weg haben wir zwei der Überlebenden aufgelesen. Danach kehrten wir nach New Reno zurück.}

{118}{}{Wer sind die Überlebenden?}
{119}{}{Habt ihr den Ort des Angriffs untersucht?}
{120}{}{Was weißt du über den Angriff?}
{121}{}{Kannst du mir die Koordinaten des Angriffsorts geben?}

{130}{}{Zwei unserer Wachen. Gute Kerle. Haben sich bei früheren Einsätzen bewährt. Tolle Schützen mit Nerven aus Stahl – genau, was wir immer brauchen. Ich glaube, sie sind vor einer Weile auf dem Weg zum Restaurant vorbeigekommen.}
{131}{}{Äh ... Haben wir nicht. Es war ein langer Weg, und die Überlebenden haben uns alles erzählt, was wir wissen mussten.}
{132}{}{Unsere Jungs sagten, der Angriff sei von Bikern ausgeführt worden. Ich vertraue ihnen. Sonst hätte niemand die Feuerkraft oder die Eier, unseren Konvoi zu knacken.}

{133}{}{Hä? Was?! Soll ich mich vielleicht auch noch für dich bücken?}
{134}{}{Aber Tuco hat gesagt, ich darf!}
{135}{}{Lass gut sein, Tuco hat grünes Licht gegeben.}
{136}{}{[Spöttisch] „Aber Tuco hat gesagt, ich darf!“ ... Natürlich, er ist der Boss. Hier sind die Koordinaten. Höchstwahrscheinlich haben die Black Rock Einheimischen die Postkutsche schon geplündert. Ich wünsche dir nicht mal Glück dabei. Ha!}
{137}{}{[Er murmelt etwas Unverständliches vor sich hin] ... natürlich, er ist der Boss. Hier sind die Koordinaten. Höchstwahrscheinlich haben die Black Rock Einheimischen die Postkutsche schon geplündert. Ich wünsche dir nicht mal Glück dabei. Ha!}

{138}{}{Tuco sagte, du hättest die Rettungsaktion bei der Postkutsche angeführt?}
{139}{}{Erzähl mir noch mal von der Rettungsaktion.}

#General questions
{140}{}{Wer bist du?}
{141}{}{Hast du etwas über die Biker hier in der Gegend gehört?}
{142}{}{[Murrend] In dieser Stadt gibt es heutzutage zu viele unverschämte Arschlöcher ... Ich bin Edward. Ich bin der Mentor der „Nevada Express“-Rekruten.}
{143}{}{Biker? Ich *hasse* sie! Sie sind eine Plage für Nevada! Verdammte Troglodyten, voll behängt mit Klimperkram und anderem Mist. Sie denken, sie können Bars aufmischen und unsere Postkutschen überfallen. Diese Hurensöhne sollten mir bloß so weit wie möglich vom Leib bleiben!}

#Evidence against "Nevada Express"
{150}{}{Setz dich jetzt hin und sieh dir das an. Ich will dein Gesicht sehen, wenn du die Daten hier siehst.}
{151}{}{[Untersucht die Daten-Diskette] Was zum ... Moment ... Nein! Alles ist weg!}
{152}{}{Wovon redest du?}
{153}{}{Ich sage, dass diese Beweise zusammen mit dem Rest der Postkutsche verrosten sollten.}
{154}{}{Sieht so aus, als wüsstest du mehr, als du zugibst, oder?}
{155}{}{Es gibt Kräfte, die mächtiger sind als wir. Ich erkläre es dir.}
{156}{}{Ich will keine Erklärungen. Nur Profit.}
{157}{}{Natürlich wüsste ich gern, was dich dazu gebracht hat.}
{158}{}{Eigeninteresse? Das könnte mit einer Kugel aus einer dunklen Gasse enden, wenn du nicht auf meine Worte hörst.}
{159}{}{Na schön, ich höre.}
{160}{}{Ein gewisser Geschäftsmann war nach Salt Lake City gereist, um den Verkauf von Nuka-Cola in Reno abzuwickeln, und war auf dem Rückweg. Ein anderer Typ in Reno wollte diesen Handel verhindern, und zufällig schuldeten ihm zwei unserer Wachen Geld.}
{161}{}{Und du wusstest davon?}
{162}{}{Nein, das habe ich erst später erfahren. Die Jungs haben mir schließlich alles erzählt. Als ich die Wahrheit erfuhr, musste ich mitspielen. Schließlich können wir die Vergangenheit nicht ändern, und Ärger mit der örtlichen Mafia brauchen wir auch nicht.}
{163}{}{Wie du siehst, hat der Plan nicht funktioniert.}
{164}{}{Was auch immer passiert ist, bitte versteh: "Nevada Express" hatte nichts damit zu tun. Nur diese Jungs sind schuld, aber was passiert, wenn Tuco oder jemand außerhalb der Firma herausfindet, dass Verbrecher in unseren Reihen sind? Unser Ruf würde schwer leiden. Das wäre für alle schlecht. Sollen wir dafür alles riskieren, nur um die Wahrheit ans Licht zu bringen?}
{165}{}{Hast du eine Idee, was wir tun sollen?}
{166}{}{Vielleicht ... könnte ich den Chip einfach zerstören. Die Wachen hätten dasselbe getan.}
{167}{}{Aber dein Vorgehen hat dem Ruf der Biker geschadet. Wenn du ihnen weiter Ärger einbrockst, könnten sie tatsächlich anfangen, "Nevada Express" zu überfallen.}

{168}{}{Scheiße, daran hab ich nicht gedacht ... Was machen wir dann?}
{169}{}{Ich werde versuchen, mir etwas einfallen zu lassen. Aber nicht jetzt.}
{170}{}{Na gut, dann vernichte ich eben die Beweise.}
{171}{}{Na gut, dann vernichte ich eben die Beweise. Aber ich verlange eine Belohnung – 2000 $.}
{172}{}{Deine Ideen sind beschissen. Ich finde eine andere Verwendung für den Chip.}

{173}{}{Das hoffe ich wirklich.}
{174}{}{Auf Wiedersehen.}
{175}{}{Ich hätte nicht gedacht, dass dein Gewissen dir dazwischenfunkt. Danke. Ich hoffe, wir müssen nicht noch einmal darauf zurückkommen. Und hier ist etwas für deine Mühe.}
{176}{}{Tschüss.}
{177}{}{Ist das der Preis für dein Schweigen? Hm ... Na ja, ich denke, das ist sicherer, als den Ruf der Firma aufs Spiel zu setzen. Hier ist das Geld, aber ich glaube nicht, dass ich mich freuen werde, dich wiederzusehen.}
{178}{}{Tschüss.}
{179}{}{Es ist noch nicht zu spät, es dir anders zu überlegen!}
{180}{}{Bis dann.}

{181}{}{Ich habe eine Idee. Ich programmiere die Diskette um und gebe sie Tuco. Alle werden denken, dass irgendeine Raiderbande den Angriff verübt hat.}
{182}{}{Genial! Und du meinst, du kannst das?}
{183}{}{Natürlich, ich kenne mich bestens mit der Programmierung von Robotern aus.}
{184}{}{Pff, wie schwer kann das schon sein? Es sind doch nur Einsen und Nullen, oder?}
{185}{}{Äh ... Vielleicht sollten wir es nicht riskieren. Wenn jemand Beweise dafür findet, dass die Diskette manipuliert wurde, scheitert der Plan.}
{186}{}{Dann denke ich noch ein bisschen darüber nach.}
{187}{}{Dann bleibt nur noch, es durchzuziehen, was?}
{188}{}{Los geht's!}
{189}{}{Ich habe noch anderes zu tun. Ich komme wieder, wenn ich bereit bin.}
{190}{}{[Du hast den Code fertig geschrieben und kompiliert, bevor du ihn ein paar Mal getestet hast. Er funktioniert wie am Schnürchen!] Zzzzzz ... Hä? Was-? Ist es fertig? Oh, mal sehen ... Perfekt! Wir sagen Tuco, dass wir die Angreifer fälschlicherweise für Biker gehalten haben. Er wird eine Weile sauer sein, aber nachdem wir uns entschuldigt haben, sollten sich die Biker selbst beruhigen. Danke, ich werde es nicht vergessen.}
{191}{}{Jederzeit.}

#Female version
{1189}{}{Ich habe noch anderes zu tun. Ich komme wieder, wenn ich bereit bin.}
