{100}{}{Du siehst einen Drogendealer.}
{101}{}{Du siehst einen Mann in zerknitterter Kleidung. Er reibt sich die Nase.}
{102}{}{Du siehst einen Drogendealer. Seine Augen suchen die Gegend nach Kunden ab.}

#Ñêèäêè
{110}{}{Oh, ich kenne dich. Äh ... Deinem Boss zuliebe gebe ich dir einen Rabatt. Wie wär's mit ... dreißig Prozent? Klingt fair?}
{111}{}{Ja, klingt fair. Was hast du heute da?}
{112}{}{Heute brauche ich nichts, aber ich merke mir den Rabatt fürs nächste Mal.}
{113}{}{Was kann ich für meinen Lieblingskunden tun?}
{114}{}{Warst du derjenige, der Wrights Slums verwüstet hat? Der Mistkerl hat es einem Dealer immer schwer gemacht, sein Geld ehrlich zu verdienen. Je mehr Probleme seine Kinder haben, desto besser läuft's für mich. Du hast dir gerade einen Rabatt verdient ... Mach weiter so.}
{115}{}{[Als er dich ansieht, leuchten seine Augen vor Wiedererkennen auf] Oh, hey! Was kann ich für dich tun?}

#Ïîäçûâàşùèå ôğàçû
{200}{}{Na, sieh mal an, wer da ist! Komm, schau dir an, was ich habe!}
{201}{}{Sieh dir meine Süßigkeiten an!}
{202}{}{Na los, ich mache dir einen guten Preis!}
{203}{}{::pfeift::}
{204}{}{Nach einem harten Tag gibt's nichts Besseres als einen Zug, oder?}
{205}{}{Ich habe Stoff, bei dem du den Himmel küsst!}
{206}{}{Ich habe, was du brauchst!}
{207}{}{Mir gefällt dein Gesicht! Du kriegst den Familienpreis!}
{208}{}{Ich hab genau das, wonach du suchst! Du weißt es nur noch nicht!}
{209}{}{Warum laufen, wenn du fliegen kannst?}
{210}{}{Ich hab den reinsten Scheiß! Probier's aus, und du willst nie wieder was anderes!}
{211}{}{Du willst fliegen? Du hast Kohle? Dann redest du mit MIR!}
{212}{}{Fühlst du dich mies? Ich bring dich wieder hoch!}
{213}{}{Ich hab Zeug und noch mehr Zeug. Lass uns reden.}

#Êîãäà òîâàğà íåò
{220}{}{Tut mir leid, ich bin ausverkauft. Komm später wieder.}
{221}{}{Ich hab gerade nichts da. Schau morgen vorbei.}
{222}{}{Alles weg. Morgen hab ich wieder Nachschub.}

#Îòğàâëåííîå ïèâî äëÿ êàçèíî
{230}{}{Ich brauche eine Ladung leicht vergiftetes Bier. Nicht tödlich. Frag nicht, warum.}
{231}{}{Hey, es ist nicht meine Aufgabe, Fragen zu stellen. 300 Mäuse, und es gehört dir.}
{232}{}{Hier ist das Geld. Mach schnell.}
{233}{}{Jetzt nicht.}
{234}{}{Hey, das reicht nicht! Komm wieder, wenn du alles beisammen hast!}
{235}{}{Na gut.}
{236}{}{[Nach einiger Zeit kommt der Dealer zurück] Ich musste ein paar Sachen auftreiben, aber ich bin fertig. Hier.}
{237}{}{Genau, was ich brauche.}

#Ñîëîìîí:
{250}{}{Ich suche einen Dealer namens Solomon. Weißt du, wo er ist?}
{251}{}{Hey, hör zu, mein Zeug ist viel besser als Solomons. Aber wenn du unbedingt ihn brauchst, dann kann ich dir vielleicht weiterhelfen. Kostet dich 1000 $.}
{252}{}{[1000 $ zahlen]}
{253}{}{Ich hab eine bessere Idee. Ich schlag dir einen Zahn nach dem anderen aus, bis du mir sagst, wo er ist. Fangen wir links oder rechts an?}
{254}{}{Hier sind 100 $. Betrachte es als Geschenk von meinem Boss, zusammen mit deinem Leben. Dafür sagst du mir, wo Solomon ist, und wir vergessen dieses Gespräch.}
{255}{}{Ich überleg's mir.}
{256}{}{Ich sagte 1000 $.}
{257}{}{Was für ein geiziger Hurensohn ...}
{258}{}{Jetzt reden wir. Solomon vertickt seinen Scheiß nachts hinter dem El Dorado. Sag ihm, ich schicke dich.}
{259}{}{[Gehen]}
{260}{}{Und ich dachte schon, du meinst es ernst.}
{261}{}{Halt die Klappe! Ich hab mich nur verrechnet, das ist alles. Kann jedem passieren.}
{262}{}{[Er sieht dich an und lächelt dann selbstsicher] Klingt nach Bullshit. Leck mich am Arsch.}
{263}{}{[Angreifen]}
{264}{}{[Leise gehen]}
{265}{}{Hey, hey, immer mit der Ruhe! Hör zu, geh nachts einfach hinter das El Dorado. Solomon wird dort sein. Sag ihm, ich hätte dich geschickt.}
{266}{}{[Leise gehen]}

#Êîìïîíåíòû äëÿ Ñòğàéêåğà
{270}{}{Ich bin wegen Strykers Komponenten hier.}
{271}{}{Geld im Voraus.}
{272}{}{[Vollständig bezahlen]}
{273}{}{Wie viel wolltest du? 1000 $? Ich glaube, es würde viel weniger kosten, dich umzubringen. Was meinst du?}
{274}{}{Ich komme mit dem Geld zurück. Warte hier.}
{275}{}{Weißt du was? Ich bring dich einfach um! [Angreifen]}
{276}{}{Du drohst mir? Vor allen Leuten? Nee, glaube ich nicht. Dein Boss wollte das geheim halten. Was, wenn ich mit Thompson rede, hm? Daran hast du wohl nicht gedacht, was? Pass verdammt noch mal auf, was du sagst. Das hier sind die Straßen, und hier gelten unsere eigenen Gesetze.}
{277}{}{Du drohst mir? Ich könnte einfach abhauen, weißt du? Ich bin ein großes Risiko eingegangen, um diese Komponenten zu besorgen! ...Hör zu, wie wär's, wenn du 100 $ vom Preis abziehst und wir den Handel einfach abschließen, ja?}
{278}{}{[900 $ bezahlen]}
{279}{}{Nimm's. Und jetzt verschwinde.}
{280}{}{In Ordnung.}
{281}{}{Was ist das?}
{282}{}{Nicht genug? Tja, Pech gehabt ...}

#Êâåñò Òîìïñîíà
{290}{}{Ich habe das Gerücht gehört, dass Thompsons Team hier erschossen wurde. Weißt du etwas darüber?}
{291}{}{Ich hab's mit eigenen Augen gesehen! Sie waren hier und haben irgendeinen Mist gebrüllt, Leute um sich geschart ... Ich schätze, das hat unerwünschte Aufmerksamkeit erregt. Einen von den Kerlen hat's so hart erwischt, dass er von den Füßen gerissen wurde! Ich hab noch nie eine Waffe gesehen, die das aus so großer Entfernung schafft! Das war verdammt geil!}
{292}{}{Von wo aus haben sie geschossen?}
{293}{}{Woher zum Teufel soll ich das wissen? Ich würde sagen, aus dem Casino oder den Slums von Wright, aber dann dachte ich mir, dass doch jemand den Schützen gesehen hätte. Und soweit ich weiß, hat das niemand. Seltsam, was?}
{294}{}{Danke.}

#Îñòàëüíîé äèàëîã
{300}{}{Sag mir, was du brauchst, und ich mache dir den besten Preis in Reno!}
{301}{}{Du willst nach einem miesen Tag mal richtig Spaß haben? Dann bist du hier genau richtig!}
{302}{}{Ich habe die beste Ware! Vielleicht können wir sogar ein Geschäft machen! Was meinst du?}
{303}{}{Ich habe den besten Scheiß der Stadt!}
{304}{}{Oh, ein Kunde! Was darf es diesmal sein?}
{305}{}{Hey, ich habe jede Menge Zeug! Was immer du brauchst, komm zu mir!}
{306}{}{Sieh mal! Ich habe gerade neue Ware bekommen! Wie wär's mit einem Geschäft, hm?}

{307}{}{Was hast du?}
{308}{}{Diesmal nicht.}
{309}{}{Ich hoffe, wir sehen uns wieder.}
{310}{}{Vielleicht später. Tschüss.}

{311}{}{Hast du ein starkes Gift im Angebot?}
{312}{}{Du meinst tödliches Zeug? Alles, was ich verkaufe, ist sicher, verstanden? Ob du's glaubst oder nicht, ich mag meine Kunden LEBENDIG!}
{313}{}{Also ... Hmm. Weißt du, ich kenne ein paar Typen, die dir Gift besorgen können ... Äh, Ware. Gangster. Einer verkauft hinter dem El Dorado, der andere ist in der Bowlingbahn. Das hast du nicht von mir, klar? Aber warum etwas kaufen, das dich umbringen kann, wenn mein Zeug dir die beste Zeit deines Lebens beschert? Sehe ich doch richtig, oder?}

#Female character
{1261}{}{Halt die Klappe! Ich hab mich nur verrechnet, das ist alles. Kann jedem passieren.}
