{100}{}{Du siehst Mr. Bertolini.}
{101}{}{Du siehst einen zierlichen Casinomanager. Sieht aus, als hätte er ein wenig von seinen Weinvorräten genossen.}
{102}{}{Noch ein Geschäftsmann beißt ins Gras.}
{103}{}{Tu mir einen Gefallen – STIRB!}
{104}{}{Was passiert hier?! Wo ist das Licht?!}

##########################################################################
#
#                      Ğàçíîå
#
##########################################################################

#Êîãäà ìåğòâ Òîìïñîí
{105}{}{Warte, halt! Warst nicht du es, den man neben Mr. Thompson gesehen hat, als er getötet wurde? Du solltest besser nicht länger hierbleiben – ich brauche dich nicht, um noch mehr Ärger zu machen. Wachen, zeigt diesem Störenfried die Tür!}
{106}{}{[Geh friedlich weg.]}
{107}{}{[Leiste Widerstand.]}
{108}{}{Dieser Termin ist beendet.}
{109}{}{Dieser Termin ist beendet – ebenso wie unsere Partnerschaft.}

#Íà÷àëî ğàçãîâîğà
{110}{}{Was brauchst du in meinem Büro?}
{111}{}{Ich habe schon lange keine Ghule mehr in diesem Casino gesehen ... Moment mal. Ha! Ich hielt dich für einen Ghul ... Hmm, aber denk nicht, dass ich mich dafür entschuldige.}
{112}{}{Thompsons Männer haben mir von dir erzählt. Seine Freunde sind meine Freunde. Wie kann ich dir helfen?}
{113}{}{Komm, Partner, setz dich. Ich bin ganz Ohr.}
{114}{}{Ich freue mich immer, dich in meinem Casino zu sehen. Mach es dir bequem.}
{115}{}{Ich, äh, bin gleich wieder da.}
{116}{}{Mein Name ist Ricardo Bertolini – ich bin der Besitzer dieses Hauses. Das hier ist meine Wohnung. Normalerweise kümmere ich mich nicht um die Gäste ... es sei denn, sie haben einen Geschäftsvorschlag für mich.}

{117}{}{Auf der Straße erzählt man sich, man hätte dich mit diesem alten Rancher gesehen – Oliver. Wenn du diesen Weg einschlägst, werde ich dich nicht aufhalten. Aber falls dem so ist, gibt es von nun an keine Geschäftsbeziehungen mehr zwischen uns. Wenn du weiter für mich arbeiten willst, beweise, dass du noch vertrauenswürdig bist.}
{118}{}{Das ist nur ein Täuschungsmanöver. Ich werde meinen Wert beweisen.}
{119}{}{Ist es etwa falsch, einfach mit einem Konkurrenten zu reden? Na gut.}

#Ïğî êîëó
{120}{}{Ich habe einen Vorschlag. Wir könnten ein für beide Seiten vorteilhaftes Geschäft über den Verkauf von Nuka-Cola vereinbaren ...}
{121}{}{Das Angebot ist verlockend, aber in meiner Bar werden nur alkoholische Getränke ausgeschenkt. Hier wird niemand Cola kaufen. Wären wir eine Art Café, würde ich wahrscheinlich zustimmen.}
{122}{}{Ah, verstanden.}

#Êëîâåğ
{123}{}{Boss, ich kenne eine Frau, die nach dem Tod ihres Mannes gezwungen ist, ihre Schulden beim Casino abzuzahlen. Könnten Sie helfen, die Sache zu regeln?}
{124}{}{Ich habe von der Geschichte gehört ... Mrs. Clover, richtig? Dir zuliebe bin ich bereit, ihr diese Schulden zu erlassen – außerdem ist die Gesamtsumme für dieses Casino nicht viel. Informiere den Verwalter über meinen Wunsch.}
{125}{}{Danke, Mr. Bertolini!}

#Ïğî âğàæäåáíîñòü Òîìïñîíà
{130}{}{Ich habe Gerüchte gehört, du hättest Mr. Thompson beleidigt. Was hast du dazu zu sagen?}
{131}{}{Er hat es darauf angelegt!}
{132}{}{Ich werde mich nicht herausreden. Die Sache geht nur ihn und mich etwas an.}
{133}{}{Und was macht das für einen Unterschied?}

{134}{}{Das klingt nach einer offensichtlichen Lüge. Aber da wir Partner sind und gemeinsame Interessen haben, lasse ich es durchgehen. Trotzdem solltest du bedenken: Der Respekt von Mr. Thompson und seinem Team ist mir wichtiger als deine Dienste.}
{135}{}{Das ist eine gewagte Aussage. Ich habe keine Einwände, aber bedenke: Der Respekt von Mr. Thompson und seinem Team ist wichtiger als deine Dienste.}
{136}{}{Wenn du Streit suchst, dann such ihn woanders. Ich respektiere Mr. Thompson und beabsichtige, unsere ... gemeinsamen Geschäfte mit ihm fortzuführen. Wenn du uns weiterhin in die Quere kommst, werden wir nicht länger ein Auge zudrücken.}
{137}{}{Verstanden.}

{138}{}{Was soll diese Maskerade?}
{139}{}{Komm, setz dich. Brauchst du etwas?}

#Ïîïûòêà íàïğîñèòüñÿ íà ğàáîòó
{140}{}{Mr. Bertolini, ich möchte für Sie arbeiten.}
{141}{}{Arbeiten ... Was meinst du damit?}
{142}{}{Ich brauche einen *richtigen* Job. Nicht so was wie Croupier oder Hausmeister. Ich kann mehr, verstehen Sie?}
{143}{}{Was, im Casino ist keine Stelle frei?}
{144}{}{Unsere Leute erledigen alltägliche Aufgaben gut. Arbeitskräfte sind in Reno leicht zu finden. Viel schwieriger ist es, gute Partner für gemeinsame Geschäfte zu finden.}
{145}{}{Tische zu bedienen und Böden zu fegen ist Kleinkram. Ich kann *mehr* Verantwortung übernehmen, verstehen Sie?}
{146}{}{Keine Jobs? Schade. Dann muss ich mich wohl woanders umsehen.}
{147}{}{Für ernsthafte Arbeit brauchst du einen triftigen Grund oder eine Empfehlung. Was davon kannst du mir bieten?}
{148}{}{Brauchen Sie niemanden, der die Böden fegt oder so etwas?}
{149}{}{Nun, im Moment habe ich wirklich nichts, womit ich Sie beeindrucken könnte. Ich komme wieder, wenn ich etwas habe.}
{150}{}{Für ernsthafte Arbeit brauchst du einen triftigen Grund oder eine Empfehlung. Warte ... [Bertolini nimmt einen seiner Wachleute für ein vertrauliches Gespräch beiseite und kehrt dann zu dir zurück] Es gibt Grund zu der Annahme, dass deine Kontakte innerhalb der Stadt ... fragwürdig sind. Und jetzt geh.}
{151}{}{Kontakte? Mit wem? ...}

{152}{}{Jordan Bishop hat mich empfohlen. Ich soll für Sie arbeiten.}
{153}{}{Aber Ihr Verwalter hat mir geraten, mit Ihnen zu sprechen.}
{154}{}{Hören Sie, ich bin nicht von gestern. Ich habe in meinem Leben schon so manchen Auftrag erledigt ...}
{155}{}{Was ist mit diesem Paket, das ich aus Vegas für Sie habe?}
{156}{}{Und was ist mit meiner Hilfe im Fall Chase? Zählt das gar nichts?}

{157}{}{Na schön. Ich vertraue dir eine einfache Aufgabe an und sehe, wie du dich schlägst.}
{158}{}{Ausgezeichnet. Wie kann ich Ihnen helfen, Mr. Bertolini?}
{159}{}{Solange ich bezahlt werde, bin ich dabei.}

{160}{}{Geh zur Luciano-Ranch am südlichen Stadtrand. Dort findest du einen örtlichen Bettler, der sich „Canary“ nennt. Sag ihm: „Die Vergoldung ist aus unserem Jahrhundert verschwunden“, und komm mit seiner Antwort zu mir zurück.}
{161}{}{Klingt einfach. Ich denke darüber nach.}
{162}{}{In Ordnung.}
{163}{}{Bezahlt wird nach Abschluss des Auftrags. Aber geh unauffällig vor, damit niemand aus Olivers Kommune Verdacht schöpft.}
{164}{}{Verstanden.}

#Ïîñûëêà èç Âåãàñà
{165}{}{Ich habe ein Paket für dich aus Vegas.}
{166}{}{Ich habe darauf gewartet. Was ist los?}
{167}{}{Ich habe Schwierigkeiten ...}
{168}{}{Schwierigkeiten?! Ich habe gutes Geld für dieses Produkt bezahlt, und jetzt kommst du zu mir und sagst, du hättest „Schwierigkeiten“?! Ich hätte einen zuverlässigeren Kurierdienst nehmen sollen ... Zu deinem eigenen Besten hoffe ich, dass das dein letzter Fehler war, Kurier.}
{169}{}{Natürlich, äh, Mr. Bertolini. Keine weiteren Pannen.}

{170}{}{Ich habe darauf gewartet, aber ... Wie ist es in *deinen* Besitz gelangt!?}
{171}{}{Lange Geschichte, Boss. Kurz gesagt: Ich habe gute Verbindungen, und deine Leute können Geheimnisse nicht besonders gut für sich behalten. Also, willst du das Paket oder soll ich es wegwerfen?}
{172}{}{Halt den Mund und bete zu den Göttern, dass ich dich nicht auf der Stelle erschieße. Dieses Produkt ist zu wertvoll. Viele in Reno würden dafür ihre Seele verkaufen. Ich bin schlau genug, stattdessen bar zu bezahlen. Hier ist dein Lohn für die Lieferung. Lass jetzt den Koffer da und verschwinde.}
{173}{}{Na gut.}

{175}{}{Ich habe verlässliche Informationen über Spionage in diesem Ort. Interessiert?}
{176}{}{Ich höre sehr aufmerksam zu und entscheide dann, ob die Information auch nur einen Hauch meiner Geduld verdient.}
{177}{}{[Erzähl ihm von Chase]}
{178}{}{Ach, komm schon, ich wollte dich nur beeindrucken ...}
{179}{}{[Er deutet auf den Wachmann] Du weißt, was zu tun ist. Geh und kümmere dich um Chase. [Wendet sich wieder dir zu] Und du ... Hm. Vielleicht kannst du noch nützlich sein. Hier, nimm das als kleine Bezahlung. Und jetzt verschwinde.}

##########################################################################
#
#                      Êâåñòû
#
##########################################################################

#Ïåğâûé êâåñò
{180}{}{Ich bin hier, um über meinen Auftrag zu sprechen.}
{181}{}{Hast du den Kontakt getroffen?}
{182}{}{Ja, ich habe ihn auf Olivers Ranch getroffen.}
{183}{}{Offenbar war er ein lausiger Kontaktmann. Sonst wäre er noch am Leben.}
{184}{}{Nein, ich habe ihn noch nicht gefunden.}
{185}{}{Ich bezahle niemanden dafür, in meinem Kasino herumzulungern. Ganz im Gegenteil – die Leute bezahlen mich. Komm nicht zurück, bevor du den Auftrag erledigt hast.}
{186}{}{Na gut.}
{187}{}{[Er sieht dich aufmerksam an, zieht dann einen einzelnen Fünfzig-Dollar-Schein hervor, zerknuellt ihn und wirft ihn dir vor die Füße] Verschwinde.}
{188}{}{Hey, ich habe den Auftrag erledigt!}
{189}{}{Was hat er gesagt?}
{190}{}{Er sagte: „Es ist in unsere Taschen gewandert.“}
{191}{}{Er sagte: „Es ist in unsere Taschen gewandert.“ Was könnte das bedeuten?}
{192}{}{Für zu viele Fragen kannst du dir eine Kugel in die Stirn einfangen. Merk dir das.}
{193}{}{Äh, na gut. Und was ist mit dem Auftrag?}
{194}{}{Das erklärt einiges. Also wird es Zeit, entschlossen zu handeln ... Aber zuerst erzähl mir, was du über Oliver Luciano weißt.}
{195}{}{Ist das nicht der alte Mann von der Ranch, der vor Kurzem gestorben ist?}
{196}{}{[Er hebt die Augenbrauen und sieht den Wachmann an, der nickt. Dann zieht er einen Fünfzig-Dollar-Schein hervor, zerknuellt ihn und wirft ihn dir vor die Füße] Ich brauche deine Dienste nicht mehr. Verschwinde.}
{197}{}{Ich schätze, das war's mit unserer Zusammenarbeit ... }
{198}{}{Ein alter Mann, dem eine Ranch in der Gegend gehört und der einen großen Teil der Lebensmittel für Renos Markt liefert.}
{199}{}{So ein alter Knacker, der in einer Hütte auf der Ranch lebt und sich in den Schlaf furzt.}
{200}{}{Pass auf, was du sagst, du ungebildetes Schwein! Auch wenn Oliver und ich uns nicht grün sind, respektiere ich ihn und sein Geschäft.}
{201}{}{Ach, so ist das ... Ich werd's versuchen.}
{202}{}{Oliver und ich kamen früher recht gut miteinander aus, doch vor etwa zehn Jahren kam es zum Streit. Als in der Stadt der Bürgerkrieg ausbrach, standen wir auf entgegengesetzten Seiten der Barrikaden. Jetzt, wo ganz andere Leute das Sagen haben, will ich dem ein Ende setzen. Du wirst mir dabei helfen. Hier ist etwas, damit du zuversichtlicher bist – dein Lohn.}
{203}{}{Kannst du mir etwas mehr darüber erzählen?}
{204}{}{Ich bin dabei.}
{205}{}{Ich komme zurück, wenn der Auftrag erledigt ist.}

{206}{}{Vielleicht ... Es wird dir helfen, die Lage besser einzuschätzen. Dann kann ich einige Fragen beantworten.}
{207}{}{Ich muss etwas über diesen Bürgerkrieg erfahren.}
{208}{}{Warum seid ihr auf unterschiedlichen Seiten gelandet?}
{209}{}{Was hindert euch daran, Frieden zu schließen und Partner zu werden?}
{210}{}{Wünschst du dir ... Lucianos Tod?}
{211}{}{Darf ich noch eine Frage stellen?}

{212}{}{Das ist vor etwa sechs Jahren passiert. Die örtlichen Geschäftsleute kamen nicht miteinander aus, weil sie damit beschäftigt waren, um Einflussbereiche zu konkurrieren. Zusammen mit der rasant wachsenden Bevölkerung und dem Mangel an Ressourcen trieb das viele in den Ruin: Armut in den Häusern, Banditen auf den Straßen, Sabotage in den Unternehmen, Clans, die sich gegenseitig umbrachten. All dem setzte der „Big Daddy“ des Ödlands ein jähes Ende, als er mit seinem Team auftauchte. Er sollte angeblich „einen Auftrag ausführen“, überlistete am Ende aber alle. Seitdem herrscht in der Stadt relativer Frieden.}
{213}{}{Das ist eine lange Geschichte. Sagen wir einfach, wir haben unterschiedliche Vorstellungen davon, wie sich die Stadt entwickeln sollte. Mir gefallen Mr. Thompsons Ideen. Oliver ist völlig gegenteiliger Meinung.}
{214}{}{Gute Frage. Wahrscheinlich liegt es an der allgemeinen Lage in der Stadt und ... wie soll ich es ausdrücken ... an der Sturheit dieses alten Mannes. Ich kann Oliver nicht von seinen Ideen abbringen, aber sie widersprechen meiner Vorstellung von der Zukunft dieser Stadt völlig.}
{215}{}{Auf keinen Fall! Der Tod dieses Mannes würde nur seine Ranch zugrunde richten. Dann gäbe es keine Arbeiter und keine Sklaven mehr, und ihre Ressourcen würden geplündert. Ich habe eine andere Idee, aber es ist noch zu früh, sie dir zu verraten.}
{216}{}{Luciano liefert gelegentlich Lebensmittel an das Restaurant von Silver Legacy. Ich brauche dich, um seinen Ruf zu ruinieren, wenn er das nächste Mal liefert. Geh zum Restaurant, warte auf den Konvoi und sabotier das Geschäft. Wie du das anstellst, weiß ich nicht und will es auch nicht wissen. Aber es muss so aussehen, als hätten Lucianos Männer einen Fehler gemacht.}
{217}{}{Ich mache mich auf den Weg.}
{218}{}{Kann ich mehr über die Lage erfahren, die zu Spannungen mit Luciano geführt hat?}
{219}{}{Hast du erledigt, worum ich dich gebeten habe?}
{220}{}{Ich bin noch dabei.}
{221}{}{Auftrag erledigt, Lucianos Ruf ist ruiniert.}
{222}{}{Das sind gute Neuigkeiten. Hast du es ... unauffällig erledigt, wie ich dich gebeten habe?}
{223}{}{Danke, Mr. Bertolini. Gibt es neue Aufträge?}
{224}{}{Ich wurde gerade informiert, dass Oliver Luciano verstorben ist. Damit ist der Zweck meines Plans hinfällig. Was deine Dienste angeht ... Nun, ich habe keine weiteren Aufträge für dich. Du kannst gehen.}
{225}{}{Oh, Oliver, warum hast du mich enttäuscht ... }
{226}{}{Ja, du hast dich bewährt, also kann ich dir eine ernstere Mission anvertrauen. Deine Bezahlung richtet sich außerdem nach der Bedeutung der jeweiligen Aufgabe.}
{227}{}{Was soll ich tun?}
{228}{}{Ich möchte, dass du Lucianos Unternehmen zerstörst. Er muss aus seiner Komfortzone gerissen werden, damit ich ihm später meine Bedingungen diktieren kann. Und Oliver darf auf keinen Fall sterben.}
{229}{}{Sein ganzes Unternehmen zerstören? Wie soll ich das anstellen?!}
{230}{}{Der Auftrag ist angenommen. Warten Sie auf Ergebnisse, Mr. Bertolini.}
{231}{}{Wer bezahlt hier eigentlich wen, beim Gecko?! Das ist *dein* Problem, also entscheide selbst, was du tust. Aber wenn ich du wäre, würde ich mir zuerst die zentralen Anlagen der Ranch genauer ansehen – den Hangar, den brahmin-Pferch oder den Sklavenhof. Je mehr Verluste du verursachst, desto besser.}
{232}{}{Vielleicht ist das eine gewagte Frage, aber trotzdem – warum ist das überhaupt nötig? Schließlich versorgt dieses Unternehmen Reno mit Lebensmitteln ... }
{233}{}{Ich werde meine Pläne nicht mit dir besprechen. Aber ich sage dir, Luciano ist nicht so einfältig, wie du denkst. Er ist kein gewöhnlicher Rancher, der den Kopf im Arsch eines brahmin stecken hat. Und er ist auch kein Händler, der Schrauben an degenerierte Wilde verkauft. Er ist die treibende Kraft. Einer der mächtigsten Männer der Stadt. Die Leute scharen sich um ihn; er diktiert seine Bedingungen und hat außerdem irgendeinen Plan. Hmm ... Ich weiß nicht, vielleicht kommst du aus einem dieser Orte, wo Essen einfach nur ein weiteres Produkt ist. Aber hier ist es das, worum sich das Leben dreht. Verstehst du jetzt?}

{234}{}{Was hast du erreicht?}
{235}{}{Im Moment noch nichts, aber ich kümmere mich später darum.}
{236}{}{Es tut mir leid, aber die Aufgabe ohne Gewalt zu erledigen, kam nicht infrage. Glaub mir, es war die einzig mögliche Lösung.}
{237}{}{Oh ja, genau wie du es wolltest. Niemand schöpft Verdacht.}

{238}{}{In diesem Fall ist es nur fair, wenn ich deine Bezahlung halbiere. Du hast nur die Hälfte der Arbeit erledigt und unsere Vereinbarung gebrochen. Ich weiß deine Mühen zu schätzen, aber über dieses ... Missverständnis kann ich noch nicht hinwegsehen.}
{239}{}{Dein Fleiß gefällt mir – du passt dich wirklich gut an.}
{240}{}{Meine Informanten erzählen eine andere Geschichte. Du versuchst, mich hinters Licht zu führen, und das ist unverzeihlich. Du hast Glück, dass ich dieses Casino nicht in einen Schießstand verwandeln will, denn das würde meinem Ruf schaden. Und jetzt raus hier.}
{241}{}{[Gehen]}
{242}{}{In mancher Hinsicht sind wir uns ähnlich – ich verzeihe niemandem, der sich weigert, mich für meine Arbeit zu bezahlen. Jetzt stirbst du!}
{243}{}{[Begib dich zur Ranch]}

{244}{}{Ich brauche deinen Rat, wie ich den Auftrag besser erledigen kann. Kann ein Mord das Problem lösen?}
{245}{}{Wenn du noch einmal solchen Unsinn redest, wird es unser letztes Gespräch sein. Ich bezahle dich für deine eigenen cleveren Ideen ... Aber wenn du mit dem Auftrag wirklich überfordert bist, versuch, die Vorräte zu vergiften. Oder versteck zumindest etwas Sprengstoff darin.}
{246}{}{Danke, Mr. Bertolini. Sie haben mir sehr geholfen.}
{247}{}{Na gut, ich versuch's.}

{250}{}{Für heute ist die Sprechstunde vorbei. Komm morgen nach acht Uhr wieder.}
{251}{}{Ein Dieb! Wachen! Ein Dieb!}

#Êâåñò íà äèâåğñèş íà ğàí÷î
{252}{}{Aus heiterem Himmel brach in Lucianos Lebensmittellager ein Feuer aus. Ein großer Teil der Waren wurde zerstört. }
{253}{}{Auf der Ranch brach eine *zufällige* Viehseuche aus, kurz nach meinem *zufälligen* Besuch dort. }
{254}{}{Damit hatte ich nicht gerechnet, und du wusstest davon. Jetzt lässt Oliver sich nicht mehr zu einer Vereinbarung drängen, und wir werden unsere Streitigkeiten nicht mit möglichst wenig Blutvergießen beilegen können. Nach dieser Nachricht ist unsere Zusammenarbeit beendet. Raus aus meinem Casino.}
{255}{}{[Gehen]}

{256}{}{Gute Arbeit! Bei solchen Verlusten wird Oliver viel nachgiebiger sein. Hier ist die Bezahlung für deine Dienste.}
{257}{}{Danke, Boss.}
{258}{}{Von jetzt an kannst du ihn und seine Ranch vergessen. Ich werde persönlich mit ihm sprechen und ihm anbieten, ihm beim Wiederaufbau seines Geschäfts zu helfen. Jetzt liegen die Verhandlungen in meiner Hand.}
{259}{}{Also brauchst du meine Dienste nicht mehr?}

{260}{}{Nun, du hast alles erledigt, worum ich dich gebeten habe. Aber da ist noch eine letzte Angelegenheit. Wenn du ablehnst, werde ich nicht darauf bestehen, und ich werde dich auch nicht zweimal fragen. Das ist eine persönliche Bitte ... Sozusagen ein Familiendrama.}
{261}{}{Es ist mir eine Ehre, Ihnen und Ihrer Familie zu helfen.}
{262}{}{Oh, ich mische mich nicht in Familienangelegenheiten ein. Tut mir leid, Boss.}
{263}{}{Ich mache dir keinen Vorwurf. Diese ganze Arbeit muss dich erschöpft haben. Geh zur Bar und entspann dich auf meine Kosten. Ich halte dich nicht länger auf.}
{264}{}{[Gehen]}
{265}{}{Mein Sohn Huey muss eine Familienangelegenheit erledigen. Das Problem ist, dass er schon immer für ... überflüssiges Mitleid bekannt war. Er muss einen Schurken töten. Deine Aufgabe ist es, dafür zu sorgen, dass alles glattgeht. Danach erzählst du mir, wie es gelaufen ist. Geh jetzt ins Erdgeschoss; dort findest du Huey.}
{266}{}{Ich werde Sie nicht enttäuschen, Mr. Bertolini.}
{267}{}{Und das ist noch nicht alles. }
{268}{}{Außerdem haben alle Sklaven *aus Versehen* ihre Schockhalsbänder ausgelöst. Auf der Ranch gab es keine Sklavenarbeit mehr. }

#Êâåñò íà Õüşè
{270}{}{Wie ich sehe, seid ihr mit Huey zurück. Wie ist es gelaufen?}
{271}{}{Ich habe Huey dazu gebracht, einen Spitzel zu erschießen. Er selbst hätte es nicht geschafft.}
{272}{}{Ich musste mich persönlich um den Informanten kümmern. Huey stand nur daneben und bruellte wie ein Kind.}
{273}{}{Huey hatte den Mut, die Sache selbst zu erledigen.}
{274}{}{Huey ließ das Opfer entkommen. Ich konnte es nicht verhindern.}

{275}{}{Das klingt glaubhaft. Ich kenne Huey sehr gut – ihm fehlt der Mumm dazu. Genau genommen wusste ich, dass du es erledigen würdest. Nimm also meinen Dank und die Bezahlung entgegen.}
{276}{}{Danke, Mr. Betrolini.}
{277}{}{Du lügst. Ich kenne Huey sehr gut. Ihm fehlt der Mumm dazu. Ich hatte gehofft, dass du die Arbeit für ihn erledigst, aber am Ende lügst du, um ihn zu verteidigen. Ich weiß nicht, was du erwartet hast. Der Auftrag ist erledigt und ich bin verpflichtet, dich zu bezahlen, aber von jetzt an brauche ich deine Dienste nicht mehr. Du kannst gehen.}
{278}{}{Wie Sie wollen, Boss.}
{279}{}{Und warum überrascht mich das nicht? [er erhebt die Stimme] Allerdings gibt es nur eine Sache, die mich überrascht hat – dass du hierhergekommen bist, mir in die Augen siehst und davon erzählst, wie du den Auftrag vermasselt hast. [er erhebt die Stimme noch weiter] Ich habe dich nicht für nächtliche Spaziergänge bezahlt, du Trottel! Unsere Zusammenarbeit ist hiermit beendet! Verschwinde!}
{280}{}{[Gehen]}
{281}{}{[Angreifen]}
{282}{}{Dein Ruf ist berechtigt – du hast mir einen großen Dienst erwiesen. Dafür ernenne ich dich zu meinem Consigliere. Mein Name bedeutet viel in dieser Stadt, und meine Leute bekommen gewöhnlich gute Preise und günstigere Konditionen.}
{283}{}{Danke. Ich weiß das zu schätzen.}
{284}{}{Deine Hilfe war sehr nützlich. Um alles Weitere kümmere ich mich selbst. Ich habe keine weiteren Aufträge für dich. Du kannst gehen.}
{285}{}{Wie Sie wollen, Boss.}

{286}{}{Ich habe Gerüchte gehört, dass derjenige, den mein Sohn töten sollte, immer noch frei herumläuft. Ich vermutete, dass Huey nicht den Mumm dazu hatte, weshalb ich dich auf die Sache angesetzt habe. Stattdessen hast du einfach vor meinem Haus hingeschissen. Das werde ich nicht dulden! Sicherheit – erledigt ihn!}
{287}{}{Hoppla ...}
{288}{}{Warte kurz! Ich habe dich enttäuscht, aber ich hatte meine Gründe. Denk mal nach – was bringt dir mein Tod, außer noch mehr Ärger mit Strykers Gang und einem Kampf in deinem Casino?}
{289}{}{[Er streicht über seine Wangenknochen und überdenkt deine Worte] Verschwinde aus dem Casino. Steckst du hier noch einmal den Kopf rein, werde ich nicht lange fackeln.}
{290}{}{[Gehen]}
{291}{}{Warte kurz. Ich habe Mr. Thompson von dir erzählt. Er war interessiert. Sprich mit ihm, vielleicht bietet er dir einen Auftrag an.}
{292}{}{Du erhältst }
{293}{}{ Erfahrung für den Aufstieg zum Consigliere.}

#Êğûøà äëÿ êîíöåğòà â Êîòòîí-êëóáå
{300}{}{Ich vertrete den „Cotton“ Club. Wir würden gern ein Abkommen über den Schutz während eines Konzerts aushandeln.}
{301}{}{Gute Idee; ich plane so ein Abkommen schon seit Langem. Schließlich sind wir Nachbarn. Sag dem Besitzer des Clubs, dass ich bereit bin, zur Sicherheit beim Konzert beizutragen, allerdings unter der Bedingung, dass wir für jeden Konzerttag einen Anteil an den Einnahmen erhalten. 35% of der Einnahmen sollen bar auf meinen Schreibtisch geliefert werden.}
{302}{}{Wir stimmen diesen Bedingungen zu.}
{303}{}{Wir müssen über diesen Vorschlag nachdenken.}
{304}{}{Richtige Entscheidung. Ich werde meine Leute schicken, damit sie den Vertrag genauer besprechen.}
{305}{}{Danke, das wäre alles.}

#Female character
{1123}{}{Boss, ich kenne eine Frau, die nach dem Tod ihres Mannes gezwungen ist, ihre Schulden beim Casino abzuzahlen. Könnten Sie helfen, die Sache zu regeln?}
{1151}{}{Kommunikation? Mit wem? ...}
{1154}{}{Hör mal, ich bin nicht von gestern. Ich habe in meinem Leben schon eine Menge Aufträge erledigt ... }
{1178}{}{Ach, komm schon, ich wollte dich nur beeindrucken ...}
{1181}{}{Hast du den Kontakt getroffen?}
{1182}{}{Ja, ich habe ihn auf Olivers Ranch getroffen.}
{1184}{}{Nein, ich habe ihn noch nicht gefunden.}
{1188}{}{Hey, ich habe den Auftrag erledigt!}
{1202}{}{Oliver und ich kamen früher recht gut miteinander aus, doch vor etwa zehn Jahren kam es zum Streit. Als in der Stadt der Bürgerkrieg ausbrach, standen wir auf entgegengesetzten Seiten der Barrikaden. Jetzt, wo ganz andere Leute das Sagen haben, will ich dem ein Ende setzen. Du wirst mir dabei helfen. Hier ist etwas, damit du zuversichtlicher bist – dein Lohn.}
{1222}{}{Das sind gute Neuigkeiten. Hast du es ... unauffällig erledigt, wie ich dich gebeten habe?}
{1224}{}{Mir wurde gerade mitgeteilt, dass Oliver Luciano verstorben ist. Damit ist der Zweck meines Plans hinfällig, und was deine Dienste angeht ... Nun, ich habe keine weiteren Aufträge für dich. Du kannst gehen.}
{1226}{}{Ja, du hast dich bewährt, also kann ich dir eine ernstere Mission anvertrauen. Deine Bezahlung richtet sich außerdem nach der Bedeutung der jeweiligen Aufgabe.}
{1228}{}{Ich möchte, dass du Lucianos Unternehmen zerstörst. Er muss aus seiner Komfortzone gerissen werden, damit ich ihm später meine Bedingungen diktieren kann. Und Oliver darf auf keinen Fall sterben.}
{1238}{}{In diesem Fall ist es nur fair, deine Bezahlung zu halbieren. Du hast nur die Hälfte der Arbeit erledigt und unsere Vereinbarung gebrochen. Ich weiß deine Mühe zu schätzen, aber über dieses ... Missverständnis sehe ich noch nicht hinweg.}
{1254}{}{Damit hatte ich nicht gerechnet, und du wusstest davon. Jetzt lässt Oliver sich nicht mehr zu einer Vereinbarung drängen, und wir werden unsere Streitigkeiten nicht mit möglichst wenig Blutvergießen beilegen können. Nach dieser Nachricht ist unsere Zusammenarbeit beendet. Raus aus meinem Casino.}
{1260}{}{Nun, du hast alles getan, worum ich dich gebeten habe. Aber eine letzte Sache gibt es noch. Ich werde nicht darauf bestehen, wenn du ablehnst, und ich werde auch nicht zweimal fragen. Es ist eine persönliche Bitte ... eine kleine Familienangelegenheit, sozusagen.}
{1271}{}{Ich habe Huey dazu gebracht, einen Spitzel zu erschießen. Er selbst hätte es nicht geschafft.}
{1277}{}{Du lügst. Ich kenne Huey sehr gut. Ihm fehlt der Mumm dazu. Ich hatte gehofft, dass du die Arbeit für ihn erledigst, aber am Ende lügst du, um ihn zu verteidigen. Ich weiß nicht, was du erwartet hast. Der Auftrag ist erledigt und ich bin verpflichtet, dich zu bezahlen, aber von jetzt an brauche ich deine Dienste nicht mehr. Du kannst gehen.}
{1279}{}{Und warum überrascht mich das nicht? [er erhebt die Stimme] Allerdings gibt es nur eine Sache, die mich überrascht hat – dass du hierhergekommen bist, mir in die Augen siehst und davon erzählst, wie du den Auftrag vermasselt hast. [er erhebt die Stimme noch weiter] Ich habe dich nicht für nächtliche Spaziergänge bezahlt, du Trottel! Unsere Zusammenarbeit ist hiermit beendet! Verschwinde!}
{1282}{}{Dein Ruf ist berechtigt – du hast mir einen großen Dienst erwiesen. Dafür ernenne ich dich zu meinem Consigliere. Mein Name bedeutet viel in dieser Stadt, und meine Leute bekommen gewöhnlich gute Preise und günstigere Konditionen.}
{1284}{}{Deine Hilfe war sehr nützlich. Um alles Weitere kümmere ich mich selbst. Ich habe keine weiteren Aufträge für dich. Du kannst gehen.}
{1286}{}{Ich habe Gerüchte gehört, dass derjenige, den mein Sohn töten sollte, noch frei herumläuft. Ich vermutete, Huey hätte nicht den Mumm dazu, weshalb ich dich auf die Sache angesetzt habe. Stattdessen hast du mir einfach vor die Haustür geschissen. Das lasse ich mir nicht gefallen! Sicherheit - erledigt dieses Miststück!}
{1288}{}{Warte mal! Ich habe dich enttäuscht, aber ich hatte meine Gründe. Denk darüber nach - was bringt dir mein Tod, außer einem Streit in deinem Kasino und noch mehr Ärger mit Strykers Gang?}

###################################################################
#
#   Ğàçâîäêà íà ñåêñ
#
###################################################################

{310}{}{Du bist in Reno eine echte Berühmtheit. Ich wollte dich schon immer näher kennenlernen ... }
{311}{}{[Er grinst anzüglich] Manchmal langweile ich mich in dieser Stadt. All diese albernen Mädchen von der Straße kennen nicht einmal die Regeln der Etikette, und mit ihnen gibt es nie viel zu bereden. Bist du eine von ihnen oder gibst du nur der Versuchung nach?}
{312}{}{Was redest du da?! Igitt! Wie kannst du nur! So tief würde ich niemals sinken.}
{313}{}{Ist es dir wirklich so wichtig, mit wem du schläfst? Du kannst dir schließlich jeden leisten. Sogar mehrere auf einmal.}
{314}{}{Meine Rose erblüht nicht für jeden - und schon gar nicht für Straßenlumpen.}
{315}{}{Ich glaube, ich habe mit dem falschen Thema angefangen. Entschuldige, ich muss auf die Toilette.}

#-òèïàæ: êóğòèçàíêà
{316}{}{Viele haben dasselbe behauptet. Manche logen, während andere wirklich davon überzeugt waren, dass sie selbst über ihr Leben bestimmen ... Worauf setzt du - darauf, in dieser Stadt unschuldig und unversehrt zu bleiben?}
{317}{}{Warum nicht? Ich hoffe, jemanden zu finden, der mir gefällt. Ich kann auswählen, statt ausgewählt zu werden.}
{318}{}{Hm. [er kneift skeptisch die Augen zusammen und bläst langsam Zigarettenrauch aus] Eine Kurtisane? Mit deiner Zunge weißt du umzugehen. Wohnst du schon lange in dieser Stadt?}
{319}{}{Nein. Ist das wirklich wichtig?}
{320}{}{Schon gut. Ich will nur verstehen, wie sehr dich diese schmutzige Welt schon verdorben hat. Hier in Reno verändern sich die Menschen mit der Zeit. Das Stadtleben macht sie kultiviert, niederträchtig und gerissen.}
{321}{}{Ja. [macht einen gelangweilten Gesichtsausdruck] Ist mir aufgefallen.}
{322}{}{[Er hebt die Augenbrauen] Langweile ich dich?}
{323}{}{Mr. Bertolini – wissen Sie ... Sie sind langweilig. SEHR langweilig.}
{324}{}{Ja. Du hast recht ... Hör zu, ich bin gerade beschäftigt. Bring dich in Ordnung, wenn du dieses Gespräch fortsetzen willst. Du siehst aus ... wie ein Landei, das den ganzen Tag Kartoffeln ausgegraben hat.}
{325}{}{Was für eine Frechheit! Na schön, Mr. Bertolini, ich werde mich in Ordnung bringen. Ich bin mir nur nicht sicher, ob für Sie.}
{326}{}{Ja. Du hast recht ... [er klatscht in die Hände] Ich weiß, was wir machen. Wir nehmen eine Flasche Wein und gehen in mein Büro. Du trinkst doch Wein, oder?}
{327}{}{Ich ziehe einen Martini vor, Mr. Bertolini.}
{328}{}{Jetzt wünsche ich mir nur noch eins – aus diesem Raum zu kommen.}
{329}{}{Niemand hält dich hier fest.}

{330}{}{[Er kichert] Wie du willst, Liebling. Wie du willst.}
{331}{}{[Gehen]}

#-òèïàæ: âåòğåíàÿ øëşõà
{340}{}{Ich erwarte nichts. Ich langweile mich nur zu Tode in dieser Stadt.}
{341}{}{Es ist eine Ewigkeit her, und in all der Zeit habe ich nie eine würdige Partnerin gefunden.}
{342}{}{[Er zuckt mit den Schultern] Hier findest du nichts Anständiges und Unschuldiges.}
{343}{}{Ja, insgesamt bin ich des Lebens überdrüssig. Können wir etwas trinken? So macht es mehr Spaß.}
{344}{}{[Er hebt den Zeigefinger] Ganz genau! Ich kann mir jede leisten. Ich kann jede Straßendirne für jede Unterhaltung kaufen, die ich will. Und sie wäre bis zu ihrem Tod an mich gebunden ... Aber nur, solange das Geld fließt. Und worauf hoffst du? In dieser Stadt unschuldig und unversehrt zu bleiben?}
{345}{}{Hm ... [er kneift skeptisch die Augen zusammen und bläst langsam Zigarettenrauch aus] Ich spüre es. Wohnst du schon lange in dieser Stadt?}
{346}{}{Wirklich? Weißt du, du stellst hohe Ansprüche. Aber du hast recht. In einer schmutzigen Welt ist es schwer, seine Unterwäsche sauber zu halten. Ich weiß nicht, ob es dir auch auffällt, aber viele von denen, die von außerhalb nach Reno gekommen sind, haben sich mit der Zeit verändert. Unter ihnen waren Menschen mit reiner Seele und reinem Körper. Sie alle wurden vom Stadtleben verdorben.}
{347}{}{Stimmt. Aber es gibt auch solche, die ihren Familientraditionen treu bleiben. Wie zum Beispiel Mr. Wright. Auch wenn wir Abstand voneinander halten, liegen mir Familienwerte am Herzen ... Meinst du, ich habe dich mit meinem Gerede gelangweilt?}
{348}{}{Ja. Auf Wiedersehen, Mr. Bertolini. Vielleicht sieht man sich.}
{349}{}{[Er grinst mit den Mundwinkeln, während er seine Haltung verändert, und mustert aufmerksam deine Hüften, als du vom Stuhl aufstehst und zum Ausgang gehst]}

#-òèïàæ: äîğîãàÿ ıãîöåíòğè÷íàÿ äàìî÷êà
{350}{}{Mr. Bertolini, versuchen Sie, mich zu beleidigen?}
{351}{}{Oh, nein! Beleidigungen gegenüber Frauen dulde ich in meinem Casino nicht. Aber du interessierst mich wirklich. Worauf wartest du noch? Schließlich ist es unmöglich, in dieser Stadt unschuldig und unversehrt zu bleiben.}
{352}{}{Worauf ich warte, bleibt meine Sache. Ich mag es nicht, wenn jemand meine Unterwäsche nach Schmutzflecken durchsucht.}
{353}{}{[Er hebt die Augenbrauen, lächelt dann und schüttelt energisch den Kopf] Natürlich, natürlich. Du gefällst mir. Genauer gesagt, dein Charakter. Wohnst du schon lange in dieser Stadt?}
{354}{}{Nein, noch nicht lange. Ich kam aus dem Norden; es war eine lange und beschwerliche Reise.}
{355}{}{Aus dem Norden ... Hmm. Dort gibt es nicht viele Siedlungen. Interessant. Weißt du, die Menschen in Reno verändern sich mit der Zeit. Vielleicht verstehst du das noch nicht, aber du kannst es spüren. Das Stadtleben macht sie kultiviert, niederträchtig und gerissen.}
{356}{}{Na und? Das geht mich nichts an. Ich denke nicht einmal darüber nach.}
{357}{}{[Er betrachtet dich voller Begeisterung] Eine starke Frau ... Aber weißt du, in Reno gibt es Menschen, die der Familientradition treu bleiben. [Er seufzt und erinnert sich an etwas] Du erinnerst mich an ... Ach, vergiss es. Ich glaube, ich fange an, dich zu langweilen. Oder nicht?}
{358}{}{Wenn du anfängst, mich zu langweilen, stehe ich einfach auf und gehe.}
{359}{}{[Sieh ihn erstaunt an, wende dich dann von ihm ab und geh leise davon]}

#-èòîã
{360}{}{[Er seufzt, als du gehst, und mustert deine Hüften] Keine Sorge, Mami. Ich laufe nicht weg.}
{361}{}{Gibt es noch etwas Aufregenderes?}
{362}{}{Ich suche es selbst aus, keine Sorge.}

{363}{}{Oh, Ihr seid eine starke und kostspielige Frau. Ich freue mich darauf, Eure Süße bei einem guten Wein und einem Hauch von Entblößung zu genießen. Bitte, kommt in mein Schlafzimmer. [er bedeutet den Wachen, nicht zu stören]}
{364}{}{Jetzt kann ich Euch nicht langweilig werden lassen. Betrachtet mich den ganzen Abend als Euren Daddy. Gehen wir. [er bedeutet den Wachen, nicht zu stören]}
{365}{}{Wie Ihr wollt, Mami. Jetzt bin ich Euer unartiger Sohn. Ihr dürft mich den ganzen Abend lang versohlen. [er bedeutet den Wachen, nicht zu stören]}
{366}{}{Sehr gut. Und jetzt wollen wir keine Zeit verlieren. Folgt mir. [er bedeutet den Wachen, nicht zu stören]}
{367}{}{[Folge ihm]}

{368}{}{Entschuldigen Sie, Mr. Bertolini, ich muss kurz auf die Toilette. Bis später.}
{369}{}{Wegen des Abends zu zweit. Haben Sie es sich inzwischen anders überlegt?}
{370}{}{Ich bin gerade beschäftigt. [er mustert dich] Bring dich in Ordnung, wenn du dieses Gespräch fortsetzen willst. Du siehst aus ... wie ein Bauernmädchen, das den ganzen Tag Kartoffeln ausgegraben hat.}
{371}{}{[Er klatscht in die Hände] Gut! Holen wir eine Flasche Wein und ziehen uns in mein Büro zurück. Du trinkst doch Wein, oder?}

{372}{}{Z-z-z ... ganz sanft ... Mami ...}
{373}{}{[Er grinst lüstern] Manchmal langweile ich mich in dieser Stadt. All diese albernen Mädchen von der Straße kennen nicht einmal die Regeln der Etikette, und mit ihnen gibt es nicht viel zu bereden ... [plötzlich bemerkt er etwas an deinem Verhalten, dann wird sein Gesichtsausdruck starr] Ein Junkie? Hätte ich mir denken können. Raus. In diesem Zustand wagst du es bloß nicht, mich anzufassen.}
{374}{}{[Gehen]}
{375}{}{Du verbringst den ganzen Abend in Bertolinis Armen. Im Bett erweist er sich als äußerst langweiliger und schwatzhafter Partner.}