{100}{}{Du siehst einen Hausmeister.}
{101}{}{Du siehst ein Kind, das die Flure putzt.}

{110}{}{Kann ich Ihnen helfen, Sir?}
{111}{}{Erzähl mir, was du hier machst.}
{112}{}{Noch nichts.}

{113}{}{Ich bin nur Hausmeister, Sir. Ich sorge dafür, dass die Flure und Zimmer sauber sind.}
{114}{}{Aber ... Du bist doch noch ein Kind.}
{115}{}{}
{116}{}{[Er runzelt die Stirn] Das sagen alle! Dann gehen sie auf die Straße und werden erschossen oder sterben an einer Überdosis, während sie im Muell liegen. Ich verdiene mein Geld, ohne zu lügen oder jemandem wehzutun. Das ist besser als die meisten Erwachsenen, die ich kenne.}
{117}{}{Sag mir ehrlich: Wirst du *gezwungen* zu arbeiten?}
{118}{}{Hmm, behandelt dein Boss dich gut?}
{119}{}{Hey, weißt du, wer Bertolinis Büro putzt?}
{120}{}{Verstehe. Ich lasse dich weiterarbeiten.}
{121}{}{Oh nein, Sir! Na ja ... Ich muss arbeiten, um Geld zu verdienen. Selbst wenn ich am Ende der Schicht todmüde bin. Niemand außer mir selbst sorgt für mich.}
{122}{}{Er ... Na ja ... Ja. Er schlägt mich nicht, aber ... Er macht mir Angst ... Und manchmal ist er unhöflich. Aber ich bin trotzdem froh, dass ich den Job bekommen habe. Es ist eine Ehre.}

{123}{}{[Er sieht besorgt aus] Das wäre ich, Sir ... Ist Mr. Bertolini unzufrieden? Er ist ... Er ist doch nicht wütend, oder?}
{124}{}{Irgendwie sagt mir das, dass das ein harter Job ist. Wie wär's mit einem Geschäft?}
{125}{}{Nein, äh, ich wollte nur sagen, dass du großartige Arbeit leistest.}
{126}{}{Ein Geschäft? Heißt das, du bezahlst mich für etwas Besonderes und Mr. Bertolini nimmt dann die Hälfte?}
{127}{}{Diesmal nicht. Genau genommen solltest du ihm nichts davon erzählen. Ich bezahle dich dafür, diese Wanzen in seinem Zimmer zu platzieren.}
{128}{}{Wan-zen? Was ist das?}
{129}{}{Keine Sorge. Denk einfach daran: Niemand darf sie jemals finden, verstanden?!}
{130}{}{I... Ich glaube schon. Aber wenn Mr. Bertolini es herausfindet, bringt er mich um!}
{131}{}{In dem Fall vergiss alles, was ich gesagt habe.}
{132}{}{Dann sorg dafür, dass er es nicht herausfindet. Erledige das und du wirst bezahlt. Abgemacht?}
{133}{}{Uff, hör zu, Junge. Wenn du den Mund hältst und nichts vermasselst, zahle ich dir so viel, dass du einen Monat lang nicht arbeiten musst!}
{134}{}{[Er denkt darüber nach und sieht dich zweifelnd an] Nein... Nein, Sir, das ist zu gefährlich!}
{135}{}{Ich wusste es! Schick nie ein Kind, um die Arbeit eines Mannes zu erledigen. Ich kümmere mich allein darum.}
{136}{}{Hmm, sieht so aus, als müsste ich etwas anderes versuchen.}
{137}{}{Wirklich?! [Er denkt einen Moment angestrengt nach] Äh, gib mir... 500 $, und ich verstecke deine Wanzen in Mr. Bertolinis Büro.}
{138}{}{Hier sind das Geld und die Wanzen. Ich warte. Und denk dran – kein Wort zu irgendwem!}
{139}{}{Warte, ich bin gleich wieder da.}
{140}{}{Bertolinis Arbeitszimmer ist jetzt verwanzt.}

#Æåíñêèå ğåïëèêè
{1110}{}{Kann ich Ihnen helfen, Ma'am?}
{1113}{}{Ich bin nur ein Hausmeister, Ma'am. Ich sorge dafür, dass die Flure und Zimmer sauber sind.}
{1121}{}{Oh nein, Ma'am! Nun... Ich muss arbeiten, um Geld zu verdienen. Auch wenn ich nach der Schicht völlig erschöpft bin. Niemand außer mir selbst sorgt für mein Essen.}
{1123}{}{[Er sieht besorgt aus] Das wäre ich, Ma'am... Ist Mr. Bertolini unzufrieden? Er ist... Er ist doch nicht wütend, oder?}
{1131}{}{In dem Fall vergiss alles, was ich gesagt habe.}
{1134}{}{[Er denkt darüber nach und sieht dich zweifelnd an] Nein... Nein, Ma'am, das ist zu gefährlich!}
{1135}{}{Ich wusste es! Schick nie ein Kind, um die Arbeit einer Frau zu erledigen. Ich kümmere mich allein darum.}