{100}{}{Du siehst einen Wachmann.}
{101}{}{Du siehst einen massigen Leibwächter.}

#Òåìà îñâåùåíèÿ
{102}{}{Ich sehe mal nach.}
{103}{}{Hey, du! Wenn du siehst, dass sich hier jemand reinschleicht, reiß ihm verdammt noch mal die Hände ab! Klar?}
{104}{}{Irgendwas stimmt nicht. Wir sollten die anderen warnen.}
{105}{}{Äh ... Okay.}
{106}{}{Ich finde raus, wer das war, und verpasse ihm einen *richtigen* Blackout.}
{107}{}{Na, wenn das nicht unser Saboteur ist!}
{108}{}{Schon wieder?! Letztes Mal ist mir die Geduld ausgegangen ...}

{110}{}{Steck deine Waffe weg.}
{111}{}{ICH SAGTE: Steck deine Waffe weg!}
{112}{}{Attentäter! Beschützt Bertolini!}
{113}{}{Ein Dieb!}

{120}{}{Verschwinde von hier, du verdammter Junkie!}
{121}{}{Wag es ja nicht, den Boss anzufassen. Ich hab dich im Auge.}
{122}{}{Der Boss hält große Stücke auf dich. Er versteht was von Menschen.}
{123}{}{Die Sprechstunde ist vorbei. Komm morgen früh wieder.}

#Ğàçãîâîğ íî÷üş ñ íàïàğíèêîì
#! âàæíî: ïóñòûå ñğîêè íå óäàëÿòü - ıòî ïàóçû ïåğåä íîâûì öèêëîì ğåïëèê
{150}{}{Hey, hat jemand Lust auf Armdrücken?}
{151}{}{Nein danke, Duke. Wir haben unsere Arme lieber noch am Körper.}
{152}{}{Ha-ha-ha! Du hast verdammt recht, mich zu fürchten! Im Ring haben das alle getan!}
{153}{}{Ja, ja, wir wissen's. Du warst ein Champion.}
{154}{}{Champion am Arsch, du Hurensohn! Ich war DER KÖNIG!}
{155}{}{Ein König, hm? Man sollte meinen, ein König könnte sich neue Zähne leisten.}
{156}{}{Ha! Als ob mich die schwächlichen Beleidigungen neidischer Pöbel interessieren würden.}
{157}{}{Wie hat er uns gerade genannt?}
{158}{}{Lies mal ein Buch, Junge. Es gibt keinen Grund, körperlich UND geistig unterlegen zu sein.}
{159}{}{Hey, Duke. Warum hast du den Ring eigentlich verlassen?}
{160}{}{...Schon gut. Politik, das ist alles. Der Untergang aller Könige.}
{161}{}{Sie haben dich benutzt, Duke. Wie all die anderen.}
{162}{}{Was hast du gerade gesagt?! Soll ich dir den Schädel zerquetschen?}
{163}{}{Whoa, was hab ich denn gesagt?}
{164}{}{Pass auf, was du sagst, Junge, sonst bringt dich eines Tages noch jemand dazu, deine Zunge zu verschlucken.}
{165}{}{Whoa, tut mir leid, Mann. Respekt. Hör zu ... Beruhigen wir uns einfach und fangen noch mal von vorn an, okay?}
{166}{}{ }
{167}{}{ }
{168}{}{ }
{169}{}{ }
