{100}{}{Du siehst einen Leibwächter.}
{101}{}{Du siehst einen grimmigen Leibwächter. Sieht aus, als wäre er seiner Arbeit sehr ergeben.}

{102}{}{S-s-S-s-S ...}
{103}{}{Am besten störst du ihn nicht.}

{110}{}{Weg mit den Waffen!}
{111}{}{Ich wiederhole: Weg mit den Waffen!!}
{112}{}{Ein Attentäter! Beschützt Mr. Bertolini!}
{113}{}{Dieb!}

{120}{}{Wir wollen hier keine Junkies! Raus!}
{121}{}{Denk nicht mal daran, dem Boss etwas anzutun – ich hab dich im Auge.}
{122}{}{Der Boss hält viel von dir. Er kann Menschen gut einschätzen.}
{123}{}{Der Boss empfängt Besucher nur tagsüber.}

{130}{}{[Der Leibwächter schreckt beim Geräusch deiner Schritte hoch] Halt! Nachts gibt es keinen Besuch. Raus! Die Arbeitszeit beginnt um acht Uhr morgens.}
{131}{}{[Angreifen!]}
{132}{}{[Geh.]}