{100}{}{Du siehst Huey.}
{101}{}{Du siehst Huey. Er ist wie zuvor.}
{102}{}{Tu, was du willst.}

{110}{}{[Zum Opfer gesprochen] Weiter gehe ich nicht. Hier müssen sich unsere Wege trennen. Mein Vater wollte dich umbringen, aber ich werde es nicht tun. Fleh meinen Partner an, es mir gleichzutun.}
{111}{}{[Weiter]}
{112}{}{[Das Opfer blickt zu euch beiden auf und spricht] Jetzt verstehe ich, warum dein Vater dich verabscheut. Das hat er schon immer... Sagst du, ich darf gehen? Ich schätze, ich sollte dankbar sein. Ich werde Strykers Männern erzählen, was hier geschehen ist.}
{113}{}{Whoa, warte einen Moment. Huey, was machst du da?}
{114}{}{Beruhige dich, Partner. Geh zurück und sag deinem Vater, dass ich den Job erledigt habe. Wenn er die Wahrheit erfährt, bringt er uns beide um. Verstehst du, was ich meine?}
{115}{}{Hmm ...}
{116}{}{Bist du verrückt oder einfach nur dumm? Früher oder später wird jemand sehen, wie er herumläuft, obwohl er *nicht tot* ist. Was hast du dann vor?}
{117}{}{Ich werde mich nicht an dem Schlamassel beteiligen, den mein Vater und die anderen Verbrecherbosse in dieser Stadt anrichten. Es ist mir egal, was er sagt. Es ist mir egal, was er denkt. Ich werde es nicht tun.}
{118}{}{Was für ein rebellischer Unsinn. Werd erwachsen! Nimm deine Waffe und tu, was du tun musst!}
{119}{}{Dräng mich nicht! Ich schulde dir nichts! Ich schulde niemandem etwas!}
{120}{}{Du bist schwach! Erbärmlich! Reiß dich zusammen, das ist deine letzte Chance, deine Beziehung zu deinem Vater zu retten! Hast du vergessen, was mit den anderen passiert ist? Willst du das auch? €? Sieh mich an! Stell dich endlich der Realität!}
{121}{}{Wie du willst. Es ist dein Leben.}
{122}{}{Halt den Mund! [Er zieht den Kopf zwischen die Schultern und wendet sich von dir ab.] Dann bring ihn eben selbst um! Ich mach es nicht! Ich... ich mach es nicht!}
{123}{}{[Nimm Hueys Hand und richte seine Waffe auf das Opfer.] Drück einfach ab, Huey. Nur ein einziges Mal. Mehr braucht es nicht. Dann bist du frei.}
{124}{}{[Huey zittert, wird blass und wendet das Gesicht vom Opfer ab.] Verzeih mir...}
{125}{}{[Weiter]}
{126}{}{[Hueys Waffe feuert einmal, dann immer wieder, während sich auf der Kleidung des zuckenden Opfers purpurrote Blüten ausbreiten. Beim Sturz platzt eine Arterie, ein dichter roter Nebel breitet sich aus und legt sich auf dich und Huey. Schließlich klickt Hueys Waffe leer. Der Körper des Opfers liegt regungslos da.]}
{127}{}{Es ist vorbei, Huey. War doch gar nicht so schwer, oder?}
{128}{}{Es ist erledigt, Huey. Du kannst jetzt den Kopf drehen.}
{129}{}{[Schwer atmend versucht Huey, den Kopf zum Opfer zu drehen. Er fährt sich mit der Hand übers Gesicht und würgt entsetzt, als er die Blutspuren darauf sieht. Er stößt deine Hände weg.] Lass mich! Lass mich in Ruhe!...}
{130}{}{Keine Sorge, Junge. Es wird leichter. Bald wirst du überhaupt nichts mehr fühlen.}

#Æåíñêèå ðåïëèêè
{1110}{}{[Zum Opfer gesprochen] Weiter gehe ich nicht. Hier müssen sich unsere Wege trennen. Mein Vater wollte dich umbringen, aber ich werde es nicht tun. Fleh meinen Partner an, es mir gleichzutun.}
{1122}{}{Halt den Mund! [Er zieht den Kopf zwischen die Schultern und wendet sich von dir ab.] Dann bring ihn eben selbst um! Ich mach es nicht! Ich... ich mach es nicht!}
