{100}{}{Du siehst Huey.}
{101}{}{Du siehst einen jungen Mann mit zerzaustem Haar und finsterem Blick.}
{102}{}{Wer bist du? Nimm das ab, damit ich dich sehen kann.}
{103}{}{Ich habe dir nichts zu sagen. Lass mich in Ruhe.}

{110}{}{Ah, noch einer von den Schlägern meines Vaters. Was willst du?}
{111}{}{Du bist also Ricardo Bertolinis Sohn? Wo deine Mutter wohl ist?}
{112}{}{Nichts.}

#Chatter
{113}{}{Ist dir das wirklich wichtig? Sie ist bei meiner Geburt gestorben.}
{114}{}{Tut mir leid, dass ich gefragt habe.}
{115}{}{Deine Entschuldigungen sind mir scheißegal. Gott sollte sich entschuldigen, falls es ihn gibt.}
{116}{}{Hast du gerade deine Tage, oder bist du immer so angepisst?}
{117}{}{Hör zu, ich will einfach nur in Ruhe gelassen werden. Scheiße, was ich *wirklich* will, ist, dass Reno schön ruhig und friedlich ist, so wie damals, als ich ein Kind war. Aber es ist die verdammte Hölle, und mein Vater liebt es so. Und er versucht, mir den „richtigen“ Weg zu zeigen, die Dinge zu tun. So zu werden wie er. Davon wird mir schlecht. Die Welt muss nicht so beschissen sein, weißt du. Aber niemand will etwas dagegen unternehmen.}
{118}{}{Du hältst nichts von der Art, wie dein Vater die Dinge angeht?}
{119}{}{Ich halte von vielem auf dieser Welt nichts. Lass mich jetzt in Ruhe, bevor ich mich noch so aufrege, dass ich mich aufhänge.}
{120}{}{Wir reden später weiter.}
{121}{}{Na gut, keine Sorge.}

#Quest
{130}{}{Dein Vater hat mich geschickt, um ein paar Dinge zu regeln. Erklär's mir.}
{131}{}{[Seufzt theatralisch] Stryker hat einen Spitzel bei uns eingeschleust. Jetzt will Vater, dass ich ihn erledige. Der Spitzel weiß nicht, dass er aufgeflogen ist. Und du bist hier, um ... Hör zu, ich bin nicht blöd. Ich weiß, warum du hier bist.}
{132}{}{Ist das ein Problem?}
{133}{}{Es geht nicht darum, ob er den Tod verdient. Das Problem ist, dass ich damit jemandem etwas beweisen soll. Das will ich nicht.}
{134}{}{Ach, heul doch. Wir kriegen nicht immer, was wir wollen. Lad deine Waffe, wisch dir den Rotz von der Nase und bring mich zu dem Ort. Verstanden?}
{135}{}{Vertrau mir einfach. Wenn wir dort sind, kümmern wir uns darum.}
{136}{}{[Er kneift nachdenklich die Augen zusammen] Na gut, bringen wir's hinter uns. Wir erledigen das am Bahnhof, wo uns niemand sieht. Ich sage allen Bescheid, dass wir aufbrechen. Warte hier ...}
{137}{}{[Warten]}

#After quest
{140}{}{Danke für deine Hilfe. }
{141}{}{Kannst du mir bei noch einem Auftrag helfen?}
{142}{}{Nur zu.}

{143}{}{Reden.}
{144}{}{Also, ich hätte gern so eine von diesen komisch aussehenden Knarren, die die Sicherheitsleute hier benutzen.}
{145}{}{Man nennt sie Tommy Guns. Vater hat Museen nach ihnen durchsucht. Sie gehören zum Vorkriegsimage des Casinos und sehen ziemlich albern aus, wenn du mich fragst – aber das spielt keine Rolle. Wichtig ist, dass sie alle im zweiten Stock eingeschlossen sind. Der einzige Schlüssel steckt bei dem großen Kerl im blauen Anzug, und wenn sie dich beim Knacken des Schlosses erwischen, machen sie dich fertig.}
{146}{}{Na ja, ich brauche etwas Kleingeld.}
{147}{}{Von mir bekommst du keins. Vater gibt mir ohne guten Grund kein Geld. Aber er hat 20 Riesen in seinem Tresor! Alles auf dem Rücken besserer Leute verdient. Es wäre nur recht, wenn jemand es ihm abnehmen würde, aber du kommst da niemals lebend rein.}
{148}{}{Kennst du die Kombination des Tresors?}
{149}{}{Klar. 9-7-5-3-1. Trotzdem kommst du nicht ohne Ärger ran.}
{150}{}{Ich bin sicher, es gibt noch einen anderen Weg.}
{151}{}{Na ja, wenn du es sowieso versuchen willst, solltest du es nachts tun. Dann werden die Wachen nachlässig – sie spielen Billard, dösen in den Sesseln, so was eben. Du könntest wohl auch das Licht ausschalten. Das würde sie aufscheuchen.}

#Female replica
{1114}{}{Tut mir leid, dass ich gefragt habe.}