{100}{}{Du siehst einen Casinoverwalter.}
{101}{}{Du siehst einen Mann in einem eleganten Anzug mit tadelloser Haltung. Man merkt, dass er hart daran arbeitet, beides zu bewahren.}

{110}{}{Ein guter Rat: Du gehörst nicht hierher. Also verschwinde besser, bevor sich jemand darum kümmert!}
{111}{}{Willkommen in unserem Casino! Ich bin der Verwalter. Kann ich etwas für dich tun?}
{112}{}{Wolltest du etwas?}

{113}{}{Wie läuft dieser Laden weiter, jetzt, wo Bertolini weg ist?}
{114}{}{Der Übergang war ziemlich schwierig, aber wir haben alles fest im Griff. Bitte mach dir keine Sorgen – wir werden nicht zulassen, dass diese Tragödie den Casinobetrieb stört. Wenn du mich jetzt entschuldigst, ich habe viel zu tun.}
{115}{}{Du scheinst ausweichend zu sein. Na ja ...}

{116}{}{Reden wir über Mrs. Clover.}
{117}{}{Oh ja. Ihr Fall ist uns zweifellos lästig, aber die Regeln sind klar. Mrs. Clover muss ihre Schulden in Höhe von 1000 Dollar begleichen.}
{118}{}{Wie ich dir bereits gesagt habe, gelten die Regeln für alle. Keine Ausnahmen.}
{119}{}{Auf Wiedersehen.}
{120}{}{Was kannst du mir über diese Schulden sagen?}

{121}{}{Wenn es hilft, diese Angelegenheit zu klären, erzähle ich Ihnen alles. Der verstorbene Ehemann von Mrs. Clover hatte bei unserem Kasino eine ziemlich hohe Schuld. Nach seinem Tod ging die Schuld auf seine nächsten Angehörigen über – in diesem Fall auf Mrs. Clover. Sie muss sie in bar zurückzahlen – genau 1000 Dollar – oder eine andere Form der Entschädigung vereinbaren.}
{122}{}{Könnte jemand anders ihre Schuld begleichen?}
{123}{}{Aber natürlich! Das ist ein Geschäft, keine persönliche Vendetta. Wenn jemand die Schuld in ihrem Namen begleicht, ist die Angelegenheit erledigt.}
{124}{}{Dann begleiche ich die Schuld.}
{125}{}{Sehr gut. Werden Sie die vollen 1000 Dollar jetzt bezahlen?}
{126}{}{Ja. Bitte sehr.}
{127}{}{Es war mir ein Vergnügen, mit Ihnen Geschäfte zu machen! Bitte bringen Sie diese Quittung zu Mrs. Clover und teilen Sie ihr mit, dass ihre Schuld beglichen ist. Wir freuen uns jederzeit, sie in unserem Kasino begrüßen zu dürfen!}
{128}{}{Das ist großartig. Wir sehen uns.}
{129}{}{Nein, ich muss später wiederkommen.}
{130}{}{Natürlich. [Sein Kopf neigt sich kaum merklich nach unten.] Bitte beachten Sie, dass die El Dorado weiterhin versuchen wird, Mrs. Clovers Schuld einzutreiben, unabhängig von etwaigen mündlichen Zusicherungen in ihrem Namen, bis sie beglichen ist.}

{131}{}{}
{132}{}{Ich habe noch weitere Fragen zu Mrs. Clovers Schuld.}

{133}{}{Mrs. Clover hat diese Schuld nicht gemacht. Warum sollte sie dafür aufkommen?}
{134}{}{Mit dem Tod ihres Mannes erbte Mrs. Clover sein gesamtes Vermögen. Also erbte sie auch seine Verbindlichkeiten. Das nennt man eine „Familiengarantie“. Sie mögen anderer Meinung sein, aber da es in Reno keine offiziellen Autoritäten gibt, liegt es an uns, über die Verpflichtungen und Folgen unserer finanziellen Geschäfte zu entscheiden.}
{135}{}{Sie sollten sich keine Sorgen darüber machen, dass ich anderer Meinung bin. Sorgen sollten Sie sich um meinen Boss machen. Vielleicht kennen Sie ihn als Renos inoffizielle Autoritätsperson.}
{136}{}{Ihr ... [Er wird blass.] ...Ihr Boss?}
{137}{}{Ja, er ist enttäuscht darüber, wie Ihr Kasino diese Frau behandelt. Sehr, sehr enttäuscht.}
{138}{}{Nun, ich, äh ... [Er schluckt.] ...wir möchten eine so ... angesehene Persönlichkeit nicht enttäuschen. Natürlich können wir Mrs. Clover ihre Schulden erlassen ... wenn er das für das Beste hält.}
{139}{}{Das tut er.}
{140}{}{Ich weiß nicht, ich muss ihn erst fragen.}

{141}{}{Das ist eine Menge Geld. Gibt es noch eine andere Möglichkeit, die Schulden zu begleichen?}
{142}{}{Hmm. [er mustert dich aufmerksam] Vielleicht könnte ein Buchungsfehler dazu führen, dass Mrs. Clovers Schulden unter den Tisch fallen. Aber solche Fehler sind meist das Ergebnis anderer, weitaus *esoterischerer* Fehler. Ich könnte mit dir über solche Details sprechen, aber das müsste unter uns bleiben ...}
{143}{}{Erzähl weiter.}

{144}{}{Ich könnte Mrs. Clovers Schulden komplett erlassen, aber dafür müsstest du mir etwas besorgen. Genauer gesagt: ein Zigarettenetui aus Kupfer, so eines wie in Mr. Wrights Sammlung.}
{145}{}{Von all den Dingen in Reno willst du ein Zigarettenetui?}
{146}{}{In diesem Fall ist ein Zigarettenetui nicht einfach nur ein Zigarettenetui. Symbole der Vorkriegsgesellschaft stehen für einen gewissen Status. In meiner besonderen Lage sind solche Dinge mächtiger als Waffen oder sogar Geld.}
{147}{}{Wer ist Mr. Wright, und was hat es mit dieser Sammlung auf sich?}
{148}{}{Du kennst Mr. Wright nicht? Das solltest du. Ihm gehören die Slums gegenüber diesem Kasino und das Silver Legacy. Er war einst ein sehr mächtiger Mann, aber davon ist heute nur noch ein Schatten übrig. Trotzdem besitzt er noch immer seine Sammlung von Erinnerungsstücken aus der Vorkriegszeit. Er ist ein ... traditionsbewusster Mann und schätzt das Amerika, das einst war. Er sammelt Artefakte aus jener Zeit und zeigt seine Sammlung manchmal Leuten, die sie zu schätzen wissen. So wie mir.}
{149}{}{Was, wenn dein Boss davon erfährt?}
{150}{}{Nun, das wird er doch nicht, oder? [er verengt die Augen] Und außerdem glaube ich nicht, dass er dir sowieso glauben würde.}
{151}{}{Ich werde über deinen Vorschlag nachdenken.}
{152}{}{Heute ist dein Glückstag, denn zufällig habe ich dieses Zigarettenetui hier. Nimm es.}
{153}{}{Ich habe dein Zigarettenetui. Bringen wir es hinter uns.}

{154}{}{Einen Moment! Ich kann mir vorstellen, dass Mr. Bertolini jemanden mit deinen Fähigkeiten gut gebrauchen könnte. Wenn du Interesse hast, besuch ihn und sag ihm, dass ich dich für einen Job empfohlen habe. Wenn nicht, dann viel Glück.}
{155}{}{Ich werde daran denken. Danke und auf Wiedersehen.}

#Êèé Áåðòîëèíè
{165}{}{Es war Mr. Bertolinis persönlicher Queue. Ohne ihn haben wir keinen Grund, für die Reparatur zu bezahlen. Du kannst ihn behalten – ich bin sicher, du findest jemanden, dem du ihn verkaufen kannst.}
{166}{}{Hey, wir hatten eine Abmachung!}
{167}{}{Verstehe. Na gut, dann gehe ich wohl.}
{168}{}{Die Bedingungen des Deals gelten nicht mehr. Ich bin sicher, du verstehst das. Falls nicht, solltest du wissen, dass unsere Wachen nicht zögern werden, ungebärdige Gäste des Hauses zu verweisen – und zwar ohne den besagten Queue.}
{169}{}{Vielleicht tun sie das, aber sie werden nicht rechtzeitig hier sein, um dich zu retten. [Angreifen.]}

{170}{}{Hast du Arbeit für mich?}
{171}{}{Das Casino sucht derzeit keine Haushaltshilfen, aber danke für dein Interesse. Schau jederzeit wieder vorbei, falls sich etwas ändert.}
{172}{}{Das Casino sucht derzeit keine Haushaltshilfen, aber versuch es doch bei unserem Besitzer, Mr. Bertolini. Er sucht talentierte Leute für, äh, besondere Aufträge.}
{173}{}{In Ordnung.}
{174}{}{Eigentlich ... [er hebt einen Finger] ... gibt es eine Aufgabe, bei der du vielleicht helfen könntest. Nichts Aufwendiges, aber sie bringt 200 Dollar ein.}
{175}{}{Worum geht's?}
{176}{}{Schade, ich suche nur nach aufwendiger Arbeit.}
{177}{}{[Er greift unter seinen Schreibtisch und holt einen Kasten hervor. Er öffnet ihn und enthüllt einen zerbrochenen, zusammenklappbaren Pool-Queue.] Das ist Mr. Bertolinis Lieblingsqueue. Gestern wurde er wegen schlechter Nachrichten sehr wütend und zerbrach ihn über einem Knie. Genauer gesagt: über dem Knie des Boten. Wir zahlen 200 Dollar für die Reparatur.}
{178}{}{Bertolini hat seinen *Lieblingsqueue* zerbrochen?}
{179}{}{Eine von Mr. Chases Wanzen wurde geschickt zwischen Bertolinis Sachen versteckt.}
{180}{}{Kein Problem. Ich kümmere mich darum.}
{181}{}{Das ist nicht wirklich mein Ding.}

{182}{}{Allerdings. Mr. Bertolini ist ein Mann mit Überzeugungen. Er handelt entschlossen, selbst wenn es um Dinge geht, an denen ihm sehr viel liegt.}
{183}{}{[Er wirft dir einen verschmitzten Blick zu] Aber das weißt du ja bereits, oder?}
{184}{}{Aber du musst davon nichts wissen.}
{185}{}{Mir auch nicht. Aber früher oder später muss die Arbeit erledigt werden, von dir oder jemand anderem. Uns zählen die Ergebnisse. Also, hier – solange du den Queue in angemessenem Zustand zurückbringst, bekommst du dein Geld, ganz gleich, ob du die Reparatur selbst durchgeführt hast oder nicht.}
{186}{}{Das freut mich. [Er reicht dir den Kasten.] Ich wäre dir dankbar, wenn du ihn so schnell wie möglich zurückbringen könntest. Ach, und der Kasten selbst ist abgenutzt, besonders am Boden – darum kümmere dich bitte auch.}
{187}{}{Denk daran: Am besten zeigt man seine Dankbarkeit mit Geld. Ich bin dann weg.}
{188}{}{Auf Wiedersehen.}
{189}{}{Ist der Auftrag mit dem Queue noch zu haben?}
{190}{}{Vorläufig schon. Ich wollte gerade den Putzjungen bezahlen, damit er ihn zum Mechaniker draußen am Rangierbahnhof bringt. Willst du der Konkurrenz einen Schritt voraus sein?}
{191}{}{Ja. Gib mir den Queue, ich repariere ihn.}
{192}{}{Nein, gib ihn ihm.}
{193}{}{Wegen des Queues ...}
{194}{}{Ist er fertig?}
{195}{}{Ich verstehe nicht, warum hat Bertolini seinen Lieblingsqueue zerbrochen?}
{196}{}{Ja, hier ist er.}
{197}{}{Noch nicht. Ich bringe ihn später.}
{198}{}{Tut mir leid, ich habe ihn verloren.}
{199}{}{[Er nimmt den Queue aus dem Etui und begutachtet sorgfältig die Qualität der Arbeit] Hmm. Die Balance stimmt, Länge und Krümmung sind unverändert. Hervorragende Arbeit! Hier ist dein Lohn, danke.}

#Female character
{1168}{}{Die Bedingungen des Deals gelten nicht mehr. Ich bin sicher, du verstehst das. Falls nicht, solltest du wissen, dass unsere Wachen nicht zögern werden, ungebärdige Gäste des Hauses zu verweisen – und zwar ohne den besagten Queue.}
