{100}{}{Du siehst den Maulwurf.}
{101}{}{Er sieht für dich wie ein zwielichtiger Kerl aus, aber Bertolini hat ein besonderes Interesse an ihm.}

{110}{}{Ich verstehe, dass der Junge nicht das Zeug dazu hat. Aber was hält dich zurück?}
{111}{}{Ich habe eine Nase für Gelegenheiten, und dein Boss stinkt geradezu danach. Wie wär's, wenn wir uns gegenseitig einen Gefallen tun?}
{112}{}{Nichts. Ich wollte nur wissen, ob du noch letzte Worte hast.}
{113}{}{Ich bin kein Mörder. Ich bin hier, um dir zu sagen, dass du dich eine Weile besser versteckst. Ändere deine Frisur, lass dir vielleicht einen Bart wachsen.}
{114}{}{Habe ich eine Wahl? Na gut, ich lege ein gutes Wort für dich ein. Versprechen kann ich nichts, aber, hehe, ich glaube, er könnte jemanden wie dich gebrauchen.}
{115}{}{Eigentlich wollte ich nur sehen, wie verzweifelt er nach neuen Leuten sucht. Gleich braucht er einen weniger. [Töte ihn]}
{116}{}{Gut. Verschwinde von hier.}
{117}{}{Du kommst nicht von hier, oder? Mit so einer Einstellung endest du schnell tot in der Gosse ... Hör zu, du willst nicht für Bertolini arbeiten. Er ist nur ein gieriger Geschäftsmann, der sich für einen Gangster hält. Wenn du wirklich etwas bewirken willst, kann ich bei meinem Boss ein gutes Wort für dich einlegen. Keine Versprechen, aber ich glaube, er könnte einen Mann wie dich gebrauchen.}
{118}{}{Ich werde daran denken. Und jetzt geh, bevor dich jemand bemerkt.}
{119}{}{Ich war bereit, dein Verhalten zu dulden. Beleidigungen gegen Mr. Bertolini dulde ich nicht. [Töte ihn]}

#Æåíñêèå ğåïëèêè
{1113}{}{Ich bin kein Mörder. Ich bin hier, um dir zu sagen, dass du dich eine Weile besser versteckst. Ändere deine Frisur, lass dir vielleicht einen Bart wachsen.}
{1117}{}{Du kommst nicht von hier, oder? Mit so einer Einstellung endest du schnell tot in der Gosse ... Hör zu, du willst nicht für Bertolini arbeiten. Er ist nur ein gieriger Geschäftsmann, der sich für einen Gangster hält. Wenn du wirklich etwas bewirken willst, kann ich bei meinem Boss ein gutes Wort für dich einlegen. Keine Versprechen, aber ich glaube, er könnte eine Frau wie dich gebrauchen.}
