{100}{}{Du siehst einen Halunken.}
{101}{}{Du siehst einen Halunken namens Basketball Buddy.}

{110}{}{Oh nein, nein. Wenn jemand so gutaussehend wie ich die Leute einfach stehen und starren ließe, würde niemand mehr arbeiten. Wenn du also nichts zu erledigen hast, geh weiter.}
{111}{}{Oh, du bist es ... Äh, sei gegrüßt.}
{112}{}{Oh, du bist es ... Äh, sei gegrüßt! Bitte richte deinem Boss aus, dass ich ihm einen äußerst angenehmen Tag wünsche.}
{113}{}{}
{114}{}{[Geh einfach weiter.]}

#Íàáîğ îòìû÷åê
{120}{}{Ich suche etwas Besonderes.}
{121}{}{Hast du noch das Dietrichset?}
{122}{}{Besonderes? Nun, zufällig habe ich hier gerade ein Dietrichset. Du könntest stolzer Besitzer eines Sets Dietriche von Basketball Buddy werden, dem beliebtesten Gauner auf den Straßen von Reno!}
{123}{}{Dietriche?}

{124}{}{Versuch doch mitzuhalten, ja? Ich habe ein komplettes Set Dietriche und Spannwerkzeuge für dich. Unersetzliche und unbezahlbare Werkzeuge für die Besten der Besten.}
{125}{}{Wie viel?}

{126}{}{"Wie viel?" [Er verdreht theatralisch die Augen.] Hör zu, Kumpel, der hirntote Pöbel mag glauben, Reno werde vom Geld regiert, aber ich weiß es besser. Reno wird von einer zuverlässigen Knarre in deiner Hand regiert.}
{127}{}{Du brauchst eine Waffe?}

{128}{}{Nicht irgendeine. Ich brauche eine Pistole mit einem gängigen Kaliber. Ich tausche diese Dietriche dafür ein, und glaub mir, sie sind es wert. Sonst würde ich sie doch kaum mit mir herumtragen, oder?}
{129}{}{Ich überleg's mir.}
{130}{}{Du hättest mir wirklich nicht sagen sollen, dass du keine Waffe hast. [Angreifen.]}

{131}{}{}
{132}{}{Ein erfolgreiches Geschäft! Zeit für Basketball Buddy, seinen Platz in Reno zu finden ... Wenn du noch etwas brauchst, komm zu mir.}
{133}{}{Tschüss.}

{140}{}{Ich habe eine 10-mm-Pistole. Ein gängigeres Kaliber gibt es kaum.}
{141}{}{Ich habe eine 10-mm-Pistole. Sie hat sogar ein verlängertes Magazin.}
{142}{}{Ich habe eine 10-mm-Pistole. Sie ist ein älteres Modell, aber, äh, das macht sie nur stilvoller.}
{143}{}{Ich habe eine 10-mm-Pistole mit montierter Taschenlampe.}
{144}{}{Ich habe einen Magnum-Revolver.}
{145}{}{Ich habe einen Magnum-Revolver. Diesen Speedloader lege ich sogar noch drauf.}
{146}{}{Ich habe einen Desert Eagle.}
{147}{}{Ich habe einen wunderschönen vergoldeten Desert Eagle.}
{148}{}{Ich habe einen Desert Eagle mit Visier.}
{149}{}{Ich habe einen Desert Eagle. Er hat sogar ein erweitertes Magazin.}
{150}{}{Ich habe eine „Detective Special“.}
{151}{}{Ich habe diese erstklassige 10-mm-Pistole. Ist sie nicht wunderschön?}

#Êîêòåéëü Ìîëîòîâà
{200}{}{Warum nicht? Aber ich werde nicht im Muell nach Zutaten wühlen. Bring mir eine Flasche Bier, einen Schluck Fusel und eine Signalrakete, dann mixe ich dir einen Cocktail für }
{201}{}{ Dollar.}

{202}{}{Mach eine.}
{203}{}{Mach zwei.}
{204}{}{Mach drei.}
{205}{}{Mach fünf.}
{206}{}{Mach zehn.}
{207}{}{Jetzt nicht.}

{208}{}{Wie ich sehe, hast du eine Brandbombe. Machst du eine für mich?}
{209}{}{Ich brauche eine Brandbombe.}

{210}{}{Nimm sie. Und ... pass da draußen auf. So einen Kunden wie dich möchte ich nicht verlieren.}
{211}{}{In Ordnung.}
{212}{}{Natürlich! Alles für dich! Ich brauche nur eine Flasche Bier, einen Schluck Fusel und eine Signalrakete, um sie zu zünden. Und, äh ...}
{213}{}{ Dollar. Das ist der Sonderpreis für dich und deinen Boss.}

#Female character
{1126}{}{„Wie viel?“ [Er verdreht theatralisch die Augen.] Hör mal, Schöne, die hirntote gewöhnliche Meute glaubt vielleicht, Reno werde vom Geld regiert, aber ich weiß es besser. Reno wird von einer verlässlichen Knarre in deiner Hand regiert.}
