{100}{}{Du siehst einen Schläger.}
{101}{}{Du siehst einen Schläger mit dem Spitznamen Stinkender Grizzly, der sich vorsichtig umsieht.}

#Not the robbery
{102}{}{Das hier ist *unser* Revier.}
{103}{}{Wen haben wir denn da? Oh, sieh an, Mr. Niemand von gestern!}
{104}{}{Äh, ich geh dann mal ...}

#Thompson's quest
{110}{}{Also gut, halt die verdammte Klappe und hör zu. Du hast eine von Mr. Thompsons Mädchen verprügelt. Ich hör mir deine Ausrede an und knall dich dann wie üblich ab.}
{111}{}{W-was!? Woher sollte ich das wissen?! Die haben mir nichts davon gesagt!}
{112}{}{Die? Erzähl mir von diesem ... Dritten, und vielleicht lasse ich dich *gehen*.}
{113}{}{Es ist mir scheißegal, wer dich angeheuert hat. Ich bin hier, um mich um dich zu kümmern.}
{114}{}{Ich weiß nicht, wer die sind! Sie sahen aus, als kämen sie nicht von hier. Sie laufen, als hätten sie sich einen Stock in den Arsch geschoben, und geben nur Befehle. Sie haben mich dafür bezahlt, das Mädchen zusammenzuschlagen, und sind dann abgehauen. Das ist alles, ehrlich!}
{115}{}{Aha, du hast das Geld noch nicht ausgegeben, oder? Gib es her.}
{116}{}{Klar, klar! Hier ist es. Also, äh, vergessen wir die Sache, ja? Ich entschuldige mich bei Mr. Thompson und verschwinde von den Straßen. Versprochen!}
{117}{}{Von mir aus. Verpiss dich jetzt.}
{118}{}{Ich glaube nicht. Ich hab's mir anders überlegt!}

{119}{}{Genug! Bitte, hör auf!}
{120}{}{Das reicht, um Stinkin' Grizzly aus diesem Viertel verschwinden zu lassen.}

{121}{}{Ach ja? Nee! Ich hab keine Angst! Leck mich, du Konzernknecht!}
{122}{}{[Kämpfen]}

#Robbery
{150}{}{Hey, du! Warte mal kurz!}
{151}{}{[Nähern]}
{152}{}{[Ignorieren]}

{153}{}{Hey, Freund, kannst du mir mit ein paar Dollar aushelfen?}
{154}{}{Klar, hier sind 2 Dollar.}
{155}{}{Hier sind 10. Und jetzt lass mich in Ruhe.}
{156}{}{Warum sollte ich dir irgendwas geben?}

{157}{}{Was, das ist alles?}
{158}{}{Du hast doch um ein paar Dollar gebeten!}
{159}{}{Ugh, hier sind noch mal 10. Lass mich einfach gehen.}

{160}{}{Ah, ja, sorry, Freund. Du kannst gehen. [er schnappt sich das Geld und geht grinsend davon]}
{161}{}{[Gehen]}
{162}{}{Und ich sage: Das ist nicht genug! Kohle her! Sofort! Sonst verteile ich dich auf dem Asphalt!}
{163}{}{Pah, niemals! Du kriegst keinen einzigen Dollar von mir!}

{164}{}{Gut genug. Weitergehen. [er schnappt sich das Geld und geht kichernd davon]}
{165}{}{[Gehen]}

{170}{}{[Er rennt heran und packt dich an der Schulter] Hey! Ich rede mit dir! So eine Respektlosigkeit lasse ich mir von dir nicht gefallen. Gib mir dein Geld, bevor ich sauer werde, klar?}

{171}{}{Kannst du ein paar Dollar entbehren? Vielleicht können ich und meine Jungs dich ja umstimmen. Komm doch rüber, dann reden wir darüber.}
{172}{}{Was, das ist alles? Meine Jungs sind härter. Ich geh sie einfach holen...}

{173}{}{Ha! Ich kenne hier jeden, du kannst mich nicht täuschen. Na los, Taschen leeren! Schnell! [er packt deinen Ärmel]}
{174}{}{[Widerstand leisten]}
{175}{}{[Nachgeben]}
{176}{}{[Deine Taschen werden um dein ganzes Bargeld erleichtert] Na, wer ist denn hier reich?! Und jetzt verpiss dich von meiner Straße! Ich will dich nie wiedersehen!}
{177}{}{[Gehen]}
{178}{}{Ich werde diese Straße mit deinem Blut tränken!}

#making fun of the metal detector
{300}{}{Ha! Na, sieh mal einer an! Ein Freak mit einem Stock.}
{301}{}{Sieh mal, sieh mal! Was zum Teufel trägt der da mit sich herum?}
{302}{}{Sieh dir das an! Ein Kerl mit einem Stock.}
{303}{}{Bilde ich mir das ein, oder trägt der Typ einfach einen Stock mit sich herum?}
{304}{}{He, du, hier gibt's keinen Schatz. Such gar nicht erst.}
{305}{}{Suchst du etwas? Brauchst du Hilfe?}
{306}{}{He, sag Bescheid, wenn du etwas findest, ja?}
{307}{}{Im Rinnstein nach Münzen suchen, was für ein Leben ...}
{308}{}{Ja, such schön nach Geld!}
{309}{}{Leute wie dich brauchen wir ... wenn du etwas Nützliches findest.}

#Æåíñêèå ðåïëèêè
{1103}{}{Wen haben wir denn hier?}
{1153}{}{Hey, Süße, kannst du mir mit ein paar Kröten aushelfen?}
{1160}{}{Ah, ja, tut mir leid, Süße. Du kannst gehen. [er schnappt sich das Geld und geht grinsend davon]}
{1170}{}{[Er rennt herbei und packt dich an der Schulter] Schlampe! Ich rede mit dir! So eine Respektlosigkeit lasse ich mir von dir nicht bieten. Gib mir dein Geld, bevor ich sauer werde, verstanden?}
{1171}{}{Kannst du ein paar Dollar entbehren? Vielleicht können ich und meine Jungs dich ja umstimmen. Komm doch rüber, dann reden wir darüber.}
{1176}{}{[Deine Taschen werden um dein ganzes Bargeld erleichtert] Na, wer ist denn hier reich?! Und jetzt verpiss dich von meiner Straße! Ich will dich nie wiedersehen!}

{1300}{}{Ha! Na, sieh mal einer an! Ein Freak mit einem Stock.}
{1301}{}{Sieh mal, sieh mal! Was zum Teufel trägt sie da mit sich herum?}
{1302}{}{Sieh dir das an! Ein Mädchen mit einem Stock.}
{1303}{}{Bilde ich mir das ein, oder trägt das Mädchen einfach einen Stock mit sich herum?}
{1304}{}{He, du, hier gibt's keinen Schatz. Such gar nicht erst.}
{1305}{}{Suchst du etwas? Brauchst du Hilfe?}
{1306}{}{He, sag Bescheid, wenn du etwas findest, ja?}
{1307}{}{Im Rinnstein nach Münzen suchen, was für ein Leben ...}
{1308}{}{Ja, such schön nach Geld!}
{1309}{}{Leute wie dich brauchen wir ... wenn du etwas Nützliches findest.}
