{100}{}{Du siehst einen Straßenjungen.}
{101}{}{Du siehst einen schwer fassbaren Graffiti-Künstler.}
{102}{}{Deine alte Rostlaube wurde in einen glänzenden Schlitten verwandelt!}
{103}{}{Das sieht fantastisch aus!}
{104}{}{Hilfe!}

{110}{}{Du schon wieder?! Ich mache nichts Schlimmes, ich schwöre!}
{111}{}{Ach ja? Sieht aus, als wärst du wieder bei deinen alten Tricks. Wenn ich dich noch einmal erwische ...}
{112}{}{Ich hoffe, du hast deine Lektion gelernt. Bis bald.}
{113}{}{Hey, Mann, hast du Lust auf eine für beide Seiten vorteilhafte Partnerschaft? Ich glaube, mein Auto braucht einen neuen Anstrich.}
{114}{}{W-wirklich? Ich darf ein *funktionierendes* Auto lackieren?! Ich mach's!!! Was soll drauf? Ich kann alles machen!}
{115}{}{Lackier einfach das ganze Ding neu, damit es wieder wie neu aussieht. Und ... Mach einen Sheriffstern auf die Tür. Das wird sehr ... konzeptionell.}

{116}{}{Das wird perfekt, ich schwöre! Aber, äh ... Wie viel willst du dafür bezahlen?}
{117}{}{Ich gebe dir hundert Dollar.}
{118}{}{Nichts.}

{119}{}{Pfft, hundert für die ganze Arbeit? Gib mir, äh ... zweihundert.}
{120}{}{Du kleiner Blutsauger! Na schön, zweihundert. Keinen Penny mehr!}
{121}{}{Tut mir leid, Junge. Du bekommst hundert.}
{122}{}{Zweihundert oder gar nichts!}
{123}{}{Na schön! Hier sind zweihundert Dollar. Fang an!}
{124}{}{Dann eben nichts. Tschüss, kleiner Blutsauger.}
{125}{}{Hmpf! Na gut, na gut, du hast mich überzeugt. Oh Mann ... Ein echtes Auto! Gib mir das Geld, ich bin schnell fertig.}
{126}{}{Hier sind deine hundert. Zeig, was du draufhast.}
{127}{}{Wenn ich's mir recht überlege, gefällt mir der ramponierte Look doch. Vergiss es, Junge.}