{100}{}{Du siehst einen Teenager.}
{101}{}{Du siehst einen langhaarigen Teenager. In Reno treiben sich viele wie er auf den Straßen herum.}
{102}{}{Siehe da! Vor dir steht ein begabter Graffiti-Künstler, ganz in sein Handwerk vertieft.}

{105}{}{Ich rede nicht mit Fremden.}
{106}{}{Frag erst gar nicht.}
{107}{}{Fass mich an, und mein Dad reißt dir den Kopf ab!}
{108}{}{Denk nicht mal dran, mich anzufassen! Meine Gang streicht die Wände mit deinem Blut!}
{109}{}{Lass mich in Ruhe!}

#Night and evening
{150}{}{[Als der Junge dich bemerkt, blickt er sich nervös um] Lass mich in Ruhe!}
{151}{}{Was treibst du so spät noch hier draußen?!}
{152}{}{Mit Vergnügen!}

{153}{}{I... ich... ich komme von einer Party nach Hause!}
{154}{}{Ach ja? Na, dann geh weiter! Und lass dich hier bloß nicht noch mal blicken.}

{155}{}{ICH GEHE NUR NACH HAUSE!!!}
{156}{}{Schon gut, schon gut, reg dich nicht auf...}

#When caught
{200}{}{[Leise schleichst du dich an den Vandalen heran und packst ihn am Handgelenk] AAAAAH!!! SCHEISSE!!!}
{201}{}{Ich wusste es! Du bist derjenige, der die Hotelwände beschmiert! Hab dich, du kleiner Rotzbengel!}
{202}{}{NA UND?! DAS SIND NUR WÄNDE! LASS MICH LOS, MANN!!!}
{203}{}{Das ist deine einzige Warnung. Wenn ich dich noch einmal sehe, verkaufe ich dich an die Sklavenhändler. Verstanden?}
{204}{}{Zu spät, Kleiner! Hättest du früher dran denken sollen. Jetzt beweg deinen Hintern ins Hotel, dann sehen wir, was sie von deiner Arbeit an ihren „bloßen Wänden“ halten. Los jetzt!}
{205}{}{Danke! Danke! Ich besprüh diese Wände nie wieder! Ich verspreche es!}
{206}{}{Das will ich auch hoffen! Ich behalte dich im Auge. Und jetzt, verschwinde!}

{207}{}{Du hast das Problem friedlich gelöst, aber es gibt keine Garantie, dass der Junge damit aufhört.}
{208}{}{Glückwunsch! Du hast den schwer zu fassenden Übeltäter erwischt.}
{209}{}{}

{210}{}{Ich glaub, ich hab mir in die Hose gemacht. Kann ich nach Hause gehen?}
{211}{}{Also das ist der kleine Bastard, der unser Hotel verunstaltet! Du bist mir ganz schön auf die Nerven gegangen, Kleiner, ist dir das klar?}
{212}{}{Ich mach's nie wieder!}
{213}{}{Ach ja? Warum hast du dann überhaupt unsere Wände vollgesprüht?}
{214}{}{Na ja ... Das machen doch alle ...}
{215}{}{Also musst du das auch machen, was? Alle coolen Kids tun's!}
{216}{}{Ich ... wollte ... ich wollte einfach nur malen.}
{217}{}{Was?}
{218}{}{Hm.}

{250}{}{Na gut, wir haben den kleinen Rotzlöffel. Was meinst du, was wir mit ihm machen sollen?}
{251}{}{Er lernt nur auf eine Art daraus – verprügelt ihn!}
{252}{}{Ich glaube, er hat genug. Ich bezweifle, dass er es noch mal tut.}
{253}{}{Lass ihn die Wände saubermachen. Das sollte ihm eine Lehre sein.}
{254}{}{Warum lassen wir ihn nicht für uns arbeiten? Wir bezahlen ihn dafür, etwas Schönes an die Wand zu malen. Das lockt doch Touristen an, oder?}

{255}{}{Ich schätze, du hast recht. Wir kümmern uns selbst um ihn. Danke für deine Hilfe. Ach ja, hier sind 100 Mäuse für die gute Arbeit. Mach's gut!}
{256}{}{[Geh.]}
{257}{}{Hm ... Ich hoffe, du hast recht. Danke für deine Hilfe. Ach ja, hier sind 100 Mäuse für die gute Arbeit. Mach's gut!}
{258}{}{Mir gefällt, wie du denkst! Wir erteilen ihm eine Lektion und lassen gleichzeitig etwas Arbeit erledigen! Danke für deine Hilfe. Ach ja, hier sind 100 Mäuse für die gute Arbeit. Mach's gut!}
{259}{}{Hey, da ist was dran! Mit der Sprühdose ist der Junge gar nicht mal so schlecht, weißt du ... Ich muss mit meinem Boss reden, aber ich glaube, der Junge hat einen Job. Danke für deine Hilfe! Ach ja, hier sind 100 Mäuse für die gute Arbeit. Mach's gut!}
{260}{}{Du hast einen klugen Weg gefunden, mit einem Graffiti-Künstler umzugehen.}

#Æåíñêèå ðåïëèêè:
{1201}{}{Ich wusste es! Du bist derjenige, der die Hotelwände beschmiert! Hab dich, du kleiner Rotzbengel!}
{1202}{}{NA UND?! DAS SIND NUR WÄNDE! LASS MICH LOS, LADY!!!}
{1205}{}{Danke, Lady! Ich beschmiere diese Wände nicht mehr! Versprochen!}
{1206}{}{Das will ich auch hoffen! Ich behalte dich im Auge. Und jetzt, verschwinde!}