{100}{}{Du siehst einen Bürger von Reno.}
{101}{}{Du siehst Harding.}
{102}{}{Du siehst einen Bewohner der Slums. Man würde sagen, er hat schon bessere Tage erlebt, aber eigentlich sieht er aus, als hätte er noch nie einen guten Tag in seinem Leben gehabt.}

{103}{}{Danke, mir geht's schon viel besser. Obwohl mich diese Pillen irgendwie wacklig auf den Beinen machen.}
{104}{}{Danke für die Unterstützung, Freund. An dir kann man sich ein Beispiel nehmen.}

#First dialogue
{110}{}{[Du bemerkst ein paar Tränen, die auf seinen Wangen glitzern.] Hä? Wer bist du?}
{111}{}{Mein Name ist }
{112}{}{. Was ist dir passiert?}
{113}{}{Ich bin ein Bandit. Gib besser sofort dein ganzes Bargeld her!}
{114}{}{Der Weihnachtsmann. Ich bin dann mal weg.}
{115}{}{Das scheint gerade kein guter Zeitpunkt zu sein. Ich komme wieder, wenn es dir besser geht.}

{116}{}{Ja? Komisch, denn ich hab nichts. Sieh doch! Hier ist nichts. Wrights Männer haben mir schon alles abgenommen, was ich hatte!}
{117}{}{Keine Sorge, war nur ein Scherz. Übrigens, ich bin }
{118}{}{Dann bleib schön still sitzen. Und keinen Mucks. Klar?}
{119}{}{Ach, schon gut, ich geh ja. Du kannst dich entspannen.}

{120}{}{Tut mir leid, es ist nur eine Depression, nichts Ernstes. Ich bin Harding, der Handwerker von hier. Wie kann ich dir helfen?}
{121}{}{Heul doch! Sieh dir diese Tränen an! Bist du ein Mann oder ein Waschlappen, Harding?!}
{122}{}{Das sieht wirklich ernst aus, Harding. Kann ich irgendetwas tun, um zu helfen?}
{123}{}{Mach's gut, Harding.}

{124}{}{Hallo. Ich habe mich inzwischen so gut wie erholt. Wie kann ich dir helfen?}
{125}{}{Du hast recht - ich bin nichts als ein Waschlappen. Meine Nachbarn lachen mich aus, und ich muss die Drecksarbeit für alle erledigen, weil ich mich nicht durchsetzen kann. Nein, ich werde keine Ausreden suchen. So läuft die Welt nun mal. Sie sind Wölfe und ich bin ein Schaf. So ist das eben.}
{126}{}{Helfen? Wie denn? Gegen die Depression? Das bezweifle ich stark. Ich fühle mich oft völlig bedeutungslos. Ich bin nichts als ein Waschlappen. Meine Nachbarn lachen mich aus, und ich muss die Drecksarbeit für alle erledigen, weil ich mich nicht durchsetzen kann. Nein, ich werde keine Ausreden suchen. So läuft die Welt nun mal. Sie sind Wölfe und ich bin ein Schaf. So ist das eben.}
{127}{}{Vielleicht sollte man deinen Nachbarn mal eine Lektion erteilen.}
{128}{}{Na ja, ich glaube, hier kann ich nicht helfen. Ich mach mich dann mal auf den Weg.}
{129}{}{Oh Gott, nein! Ganz und gar nicht! Ihnen ist nicht zu helfen, und es ist auch nicht nötig. Alles ist so, wie es sein sollte. Die Gesellschaft weist mich wohl in meine Schranken.}
{130}{}{Warum gibst du so leicht auf?}
{131}{}{Nun, ich musste es versuchen. Mach's gut, Harding, wir sehen uns später. Vielleicht.}
{132}{}{Ein guter Mann bringt mir bei, wie man unter Menschen lebt. Er sagt, ich kann überleben, wenn ich mich füge. Das ist nicht immer leicht.}
{133}{}{Hm. Na gut, ich gehe jetzt.}

#About mormons and the club
{140}{}{Was haben deine Nachbarn über den anonymen Club gesagt?}
{141}{}{Sie haben dir von dem Ort erzählt, hm? Siehst du? Ich habe ihnen nichts getan und schon kippen sie eine Menge Dreck in meinen angeschlagenen Topf.}
{142}{}{Äh, angeschlagener Topf?}

{143}{}{Ja. Wir alle, die in den Club gehen – wir sind die angeschlagenen Töpfe der Menschheit. Auf den Muell geworfen, aber wir versuchen trotzdem, am Leben zu bleiben. Und die Leute sehen sich das gern an – wer genießt schließlich keine gute Show?}
{144}{}{Erzähl mir von diesem Club.}
{145}{}{Wer führt den Club eigentlich?}
{146}{}{Wer sind die anderen „Töpfe“ in deinem Club?}
{147}{}{}
{148}{}{}
{149}{}{Das reicht erst mal. Wir sehen uns später.}

{150}{}{Niemand kümmert sich darum, außer uns. Es ist eine kleine Gruppe von Leuten, die versuchen wollen, die Kraft zum Weiterleben zu finden. Wir kommen zusammen und reden über unsere Probleme und so. Das würde dich wohl nicht interessieren ...}
{151}{}{Patrick hat alles auf die Beine gestellt. Er ist ein guter Mann, predigt das Wort Gottes und hört denen, die Hilfe brauchen, immer zu. Aber er weiß einfach, was zu tun ist. Ansonsten haben wir keinen Anführer.}
{152}{}{Dazu sage ich nichts. Wir können nicht hinter dem Rücken der anderen reden.}

#Choice of healing
{160}{}{Hör zu, ich habe mit Patrick über euren Club gesprochen ...}
{161}{}{Was?! Wie kann er es wagen?! Er hat versprochen, nichts hinter unserem Rücken zu besprechen! Und du ... Worüber habt ihr geredet? Er hat dir von uns erzählt, nicht wahr? Hast du über uns gelacht? Bitte, geh weg! Ich will keinen von euch mehr sehen!}
{162}{}{Bitte, geh weg! Ich will keinen von euch mehr sehen!}
{163}{}{Nein, nein, beruhige dich! Ich bin hier, um dir zu helfen. Wir können einander vertrauen, oder?}
{164}{}{Na, leck mich doch auch, du erbärmlicher Schwachkopf!}
{165}{}{Na schön, ich gehe ja schon.}
{166}{}{Ist das so? Kann mir wirklich geholfen werden? Gibt es jemanden, der den Riss in meinem Topf kitten kann?}
{167}{}{Vielleicht kann das niemand, aber du solltest nicht ständig leiden. Ich habe Anti-Raucher-Pillen, die die Gefühle dämpfen. Du wirst dich besser fühlen, vertrau mir.}
{168}{}{Natürlich! Deine Probleme rühren von deinen Minderwertigkeitsgefühlen her. Wenn wir das lösen, kannst du auch deine anderen Probleme beheben.}
{169}{}{Hmm, ich muss darüber nachdenken. Ich komme bald wieder.}
{170}{}{Ich weiß nicht, wie ich deinen Minderwertigkeitskomplex beheben soll. Vor allem, weil du ihn so reichlich verdient hast.}
{171}{}{Hier ist eine Eintrittskarte für Moms Nachtclub. Geh hin und entspann dich.}
{172}{}{Du solltest nicht ständig leiden. Ich habe Anti-Raucher-Pillen, die die Gefühle dämpfen. Du wirst dich besser fühlen, vertrau mir.}
{173}{}{Vielleicht hast du recht. Ich versuche es. Wenn sie mich entspannen können, helfen sie mir auch bei meinem nächsten Anflug von Depressionen.}
{174}{}{Hier, geh aus und genieß dein Leben, Harding.}
{175}{}{Ich hatte mein ganzes Leben lang Angst, dorthin zu gehen, geschweige denn, einen nackten Körper zu sehen! Und jetzt halte ich meine Eintrittskarte zum Glück in der Hand ... Ein seltsames Gefühl. Weißt du, eine Zeit lang dachte ich, die Selbstgeißelung, der sich die Gesellschaft unterwirft, sei das Einzige, was in den Wahnsinn führt. Aber du bringst mich dazu, diese Theorie zu überdenken. Ich werde versuchen, mich zu ändern. Nein, ich *werde* mich ändern. Ja! Ich schaffe das! Danke.}

{176}{}{Du hast eine Lösung für Hardings Depression gefunden.}

#Female
{1104}{}{Danke für die Unterstützung, Freund. An dir kann man sich ein Beispiel nehmen.}
{1128}{}{Na ja, ich glaube nicht, dass ich hier helfen kann. Ich mache mich auf den Weg.}
{1160}{}{Hör zu, ich habe mit Patrick über euren Club gesprochen ...}
{1161}{}{Was?! Wie kann er es wagen?! Er hat versprochen, nichts hinter unserem Rücken zu besprechen! Und du ... Worüber habt ihr geredet? Er hat dir von uns erzählt, nicht wahr? Hast du über uns gelacht? Bitte, geh weg! Ich will keinen von euch mehr sehen!}
