#Áàðàáàíùèê
{100}{}{Du siehst Jay.}
{101}{}{Du siehst Jay Nielson, einen schwarzen Obdachlosen. Die Leute nennen ihn „Kartoffelfuß“.}
{102}{}{Hey, zeigen wir diesen Bleichgesichtern mal, was Rhythmus ist!}
{103}{}{Ich werde deinen Gesang vermissen.}

{110}{}{[Zuerst sieht es aus, als wäre ein Muellhaufen zum Leben erwacht. Dann taucht ein dreckiger Fuß aus dem Abfall auf, gefolgt von einem ebenso dreckigen Gesicht mit wirrem schwarzem Haar. Die Gestalt zieht ein paar riesige Metalldosen hervor, stellt sie um sich herum auf und setzt sich hin.]}
{111}{}{Äh, was machst du da?}
{112}{}{Hm? Ich will spielen. Lehn dich zurück und hör zu.}
{113}{}{Meinst du das ernst?}
{114}{}{Verdammt richtig! Siehst du? [Er holt zwei abgewetzte, ungleiche Stöcke hervor.] Trommelstöcke. Ich hab sie im Muell gefunden. Soll ich was spielen?}
{115}{}{Na gut, ich bin neugierig.}

{116}{}{Hey, nein. [Er hebt die Hand.] Nicht mit leerem Magen.}
{117}{}{Hier sind zehn Dollar.}
{118}{}{Was?! Du willst, dass ich dich füttere, damit du auf ein paar Dosen herumtrommeln kannst?}
{119}{}{Tut mir leid, ich hab nichts.}

{120}{}{Respekt! Na gut, dann legen wir los. Eins, zwei, drei, vier ... Los geht's! [Er beginnt geschickt eine Melodie auf den Dosen zu trommeln.]}
{121}{}{Whoa, meine Ohren! Das ist keine Musik, das ist Lärm! Hör damit auf!}
{122}{}{Ich spür den Rhythmus! Weiter so!}
{123}{}{Keine Ahnung, ob sich das gelohnt hat. Ich geh jetzt einfach.}

{124}{}{[Jay übt weiter auf seinen „Trommeln“.]}
{125}{}{Wie lange machst du das schon?}
{126}{}{Ich will dich nicht stören.}
{127}{}{Seit meiner Kindheit. Ich gebe den Leuten eine Vorstellung, verdiene ein paar Kröten und überlebe einen weiteren Tag.}
{128}{}{Weißt du, du bist viel zu gut dafür, auf Muelltonnen zu spielen. Ich stelle gerade eine Band für den Club hier zusammen. Hast du Interesse?}
{129}{}{Eine Band?! Wow! Klar! Ich gehe sofort hin!}
{130}{}{Na dann los.}

{131}{}{Ich spiele dir ein paar Stücke vor, wenn du mir etwas zu essen besorgst. Ich verhungere hier.}