#Guitarist
{100}{}{Du siehst Charles.}
{101}{}{Du siehst Charles, einen schwarzen Mann aus dem Ghetto.}
{102}{}{Ich kümmere mich drum.}

{103}{}{Weiß. W. E. I. S. S. Weiß.}
{104}{}{Person of Color. Das ist ein wichtiger Ausdruck.}
{105}{}{Früher hatten wir unsere eigenen Viertel. Weiße gingen da nie hin.}
{106}{}{Meiner Großmutter würde es nichts ausmachen, was ich mache.}

{108}{}{Weißt du, du bist einer der besten Weißen, die ich je getroffen habe.}
{109}{}{Gute Idee, aber ich bezweifle, dass es so einfach ist.}

#Dialogue
{110}{}{[Du siehst einen schwarzen Mann in seltsamer Kleidung, verziert mit Nieten und feinen Flicken an Kragen und Ärmeln. Konzentriert stimmt er die Saiten seiner Gitarre.] Du lenkst mich ab. Und wenn ich abgelenkt bin, werde ich sauer. Was willst du, Weißbrot?}
{111}{}{Warum hast du mich „Weißbrot“ genannt?}
{112}{}{Weil du der weißeste weiße Bastard bist, den ich je gesehen habe! Sieh dir deine Haut an, so weiß, als hättest du noch nie die Sonne gesehen! Wo kommst du her, aus dem Kerker? Bist du in einem Keller aufgewachsen? Egal, interessiert mich nicht. Was willst du?}
{113}{}{Ich stelle eine Jazzband für den Cotton Club zusammen. Willst du mitmachen?}
{114}{}{Schon gut.}

{115}{}{Jazz ist gut. Die Stimme meines Volkes. [seine Stimme wird hart] MEINES Volkes.}
{116}{}{Dein Volk, mein Volk – wir haben doch alle dieselbe Hautfarbe von innen, oder? Warum reißen wir nicht die Barrieren nieder und spielen Jazz für alle?}
{117}{}{Verstehst du, wir sind hier eine Familie. Jeder hilft jedem. Und dann kommst du hierher und versuchst, dich in diese Familie zu drängen und dich als Anführer aufzuspielen. Entweder willst du mir eine Lüge auftischen, oder du kapierst es wirklich nicht. Und ich weiß nicht, was mich mehr aufregt.}
{118}{}{Ist das wichtig? Wir könnten Großes erreichen, wenn wir zusammenarbeiten. Vertrau mir.}
{119}{}{Jaaa ... da bin ich mir sicher, aber bei dir nicht. Ich lebe Musik, ich verkaufe sie nicht, verstehst du? Und um diese Leidenschaft zu teilen, muss ich meinem Partner vertrauen können. Manche Dinge zählen in dieser Welt noch immer, vielleicht jetzt mehr denn je. Und obendrein bist du weiß. Hör zu, beweise unserer Familie, dass man dir vertrauen kann - dann komme ich mit dir.}
{120}{}{Mit Familie meinst du die Slums, oder? Ich muss darüber nachdenken.}

{121}{}{Ich habe schon alles gesagt. Ich arbeite nicht mit dir, bis die Hood etwas Gutes über dich zu sagen hat.}
{122}{}{Na gut.}
{123}{}{Spielst du auf der Bühne?}
{124}{}{Ich spiele nur für unsere Leute. Na ja, außer du zählst Wrights Partys dazu, aber die hat er schon eine Weile nicht mehr veranstaltet. Was einen Soloauftritt auf der Bühne angeht - ich bin mir nicht sicher. Schlechte Zeiten.}

{125}{}{Habe ich genug für die Nachbarschaft getan, damit du mir vertraust?}
{126}{}{Weißt du, du bist gar nicht übel. Für eine Weiße. Na gut, ich bin dabei. Aber ich will nicht allein arbeiten - in dieser Stadt ist es gefährlich. Schließlich herrscht Krieg.}
{127}{}{Abgemacht!}

#Æåíñêèå ğåïëèêè
{1108}{}{Weißt du, du gehörst zu den Guten.}
{1110}{}{[Du siehst einen Schwarzen in seltsamer Kleidung, verziert mit Nieten und feinen Flicken an Kragen und Ärmeln. Er konzentriert sich darauf, die Saiten seiner Gitarre zu stimmen.] Du lenkst mich ab. Und wenn ich abgelenkt bin, werde ich sauer. Was brauchst du, Weiße?}
{1111}{}{Warum hast du mich „Weiße“ genannt?}
{1112}{}{Weil du die weißeste weiße Schlampe bist, die ich je gesehen habe! Sieh dir deine Haut an, sie ist so weiß, als hättest du noch nie die Sonne gesehen! Wo kommst du her, aus dem Verlies? Bist du in einem Keller aufgewachsen? Egal, ist mir schnuppe. Was willst du?}
{1115}{}{Jazz ist gut. Die Stimme meines Volkes. [seine Stimme wird hart] *Meines* Volkes.}
{1119}{}{Jaaa ... da bin ich mir sicher, aber bei dir nicht. Ich lebe Musik, ich verkaufe sie nicht, verstehst du? Und um diese Leidenschaft zu teilen, muss ich meinem Partner vertrauen können. Manche Dinge zählen in dieser Welt noch immer, vielleicht jetzt mehr denn je. Und obendrein bist du weiß. Hör zu, beweise unserer Familie, dass man dir vertrauen kann - dann komme ich mit dir.}
{1125}{}{Habe ich genug für die Nachbarschaft getan, damit du mir vertraust?}
{1126}{}{Weißt du, du bist gar nicht übel. Für eine Weiße. Na gut, ich bin dabei. Aber ich will nicht allein arbeiten - in dieser Stadt ist es gefährlich. Schließlich herrscht Krieg.}