#Trumpetist
{100}{}{Du siehst Ornette.}
{101}{}{Du siehst Ornette, einen dunkelhäutigen Bewohner des Ghettos.}
{103}{}{Ehrlich gesagt, gibt es nichts zu besprechen.}
{104}{}{Man sieht sich, Freund.}

{110}{}{[Du siehst einen älteren Schwarzen mit Flecken und Flecken auf den Händen. Als du näher kommst, blickt er auf und mustert dich aufmerksam.] Suchst du etwas?}
{111}{}{Ich suche Ornette, den Trompeter. Bist du das?}
{112}{}{Ach, Ornette ist kein Trompeter mehr. Diese Stadt brauchte weder meine Trompete noch meine Musik. Alle sind zu sehr damit beschäftigt, zu überleben und reich zu werden. Warum fragst du überhaupt?}
{113}{}{Nun, ich und der Besitzer des "Cotton Club" wollen ein paar Auftritte organisieren. Eine Trompete wäre dafür genau das Richtige ...}
{114}{}{[Er wird hellhörig] Das ist Schnee von gestern. Ich wollte meine Band auch wiederbeleben, nachdem sie auseinandergefallen war. Aber was hätte ich tun können? Ich habe meine Trompete für drei Dollar an Wright verkauft. Ich kriege sie nicht zurück, denn Wright wird mich dafür wahrscheinlich ordentlich zur Kasse bitten. Und ohne Trompete bin ich kein Trompeter.}
{115}{}{Und wenn ich sie zurückbekomme?}
{116}{}{Dann leb wohl, trompetenloser Trompeter.}
{117}{}{[Er denkt lange schweigend nach, bevor er antwortet] Für große Auftritte bin ich zu alt, aber ein paar Gigs kriege ich wohl noch hin.}
{118}{}{Dann kümmere ich mich darum.}
{119}{}{Mal sehen, was ich tun kann.}

{120}{}{Wie läuft es?}
{121}{}{Ich hab's vergessen. Was ist mit deinem Instrument passiert?}
{122}{}{Ornette, ich muss es wissen. Gibt es noch andere Leute, die uns helfen würden?}
{123}{}{Ich würde gern mehr über deine alte Jazzband erfahren.}
{124}{}{Ich habe deine Trompete. Bist du bereit, jetzt mitzukommen?}
{125}{}{Äh, nicht wirklich. Ich hab noch jede Menge andere Dinge zu erledigen. Apropos ...}
{126}{}{Sobald ich Neuigkeiten habe, komme ich wieder.}
{127}{}{Ich habe sie an Wright verkauft. Ich vermute, er hat sie noch.}
{128}{}{Von der alten Truppe sind nur noch zwei übrig. Charles, ein Gitarrist, lebt in den Slums im Westen. Soweit ich gehört habe, ist er ziemlich reizbar geworden – mit ihm auf einen Nenner zu kommen, wird schwierig. Und Martin ... Was für eine Stimme! Nach Lou war er der Zweitwichtigste in unserer Band, aber er ist ein fürchterlicher Rassist, und wir haben schon vor langer Zeit den Kontakt abgebrochen. Außerdem habe ich von einem obdachlosen Schwarzen gehört, der auf den Straßen die Leute unterhält. Ich bin ihm nie begegnet, aber er könnte nützlich sein.}
{129}{}{Das ist lange her. Eine große, eng verbundene Gruppe, Instrumente, eine Bühne. Big Louie selbst führte uns an. Aber kurz vor dem Bürgerkrieg brach er mit uns und verkaufte seine Ehre an die Ideale der Raider. Ohne ihn sind wir auseinandergefallen. War wohl besser so ... Er hielt zu viel von sich.}
{130}{}{[Untersucht das Instrument sorgfältig, die runzligen Finger fahren über das glatte Metall.] Ich habe sie seit Jahren nicht mehr in der Hand gehalten ... Ich brauche etwas Zeit zum Üben und um mich an alles zu erinnern. Danke.}
{131}{}{Na gut, wir sehen uns.}

#After returning the Trumpet
{140}{}{Danke, dass du das tust. Sehr ehrenhaft ... für einen Weißen.}
{141}{}{Kennst du jemanden, der uns nützlich sein könnte?}
{142}{}{Ich würde gern etwas über die alte Jazzband hören.}
{143}{}{Kein Problem.}

{144}{}{Sieht aus, als hätten wir alle beisammen. Wen hast du nicht gefunden?}
{145}{}{Ich habe da jemanden im Sinn. Charles, ein Gitarrist, lebt in den Slums im Westen. Soweit ich gehört habe, ist er ziemlich reizbar geworden – mit ihm auf einen Nenner zu kommen, wird schwierig.}
{146}{}{Mir fällt da ein Typ ein. Ich habe von einem obdachlosen Schwarzen gehört, der die Leute auf der Straße unterhält. Ich bin ihm nie begegnet, aber er könnte nützlich sein.}

#After the first concerts
{147}{}{Milton sagte, du hättest den Angriff beobachtet. Erzähl mir, was du weißt.}
{148}{}{Oh ... Hör zu, können wir unter vier Augen reden? Ich will nicht, dass jemand anderes mithört. Also, ich glaube, ich weiß, wer den Anschlag bezahlt hat. Höchstwahrscheinlich war es Martin. Die Handschrift auf dem Zettel war seine.}
{149}{}{Wer ist das?}
{150}{}{Wir haben in der Band von Big Louie gespielt. Er ist ausgestiegen, nachdem das Kollektiv auseinandergefallen war. Deshalb ist er noch auf uns sauer. Und er sieht es nicht gern, wenn Weiße in einer Jazzband spielen.}
{151}{}{Und das reicht ihm, um zu versuchen, diese Konzerte zu verhindern?}
{152}{}{Oh, unterschätze niemals die Sturheit eines alten schwarzen Mannes. Seine Ambitionen halten ihn nicht davon ab, hier alles auf den Kopf zu stellen.}
{153}{}{Also, was machen wir?}
{154}{}{Also, zuerst einmal: Sag Milton nichts. Wenn er davon erfährt, wird er versuchen, den alten Kerl loszuwerden. Dann versuch, selbst mit Martin zu reden und die Sache zu klären. Ich weiß, dass das nicht leicht wird. Aber wenn dem alten Mann deinetwegen irgendetwas zustößt, brauchst du nicht erwarten, dass ich noch mit dir rede.}
{155}{}{Verstanden. Wo wohnt er?}
{156}{}{An den Bahngleisen, in einem der Häuser gegenüber von Frank Cochran. Viel Glück.}
{157}{}{Na dann, ich geh mal.}

#End of concerts
{160}{}{[Als du dich der Bühne näherst, bemerkst du, dass sich alle Bandmitglieder um dich versammeln, um dir die Hand zu schütteln.]}
{161}{}{Ich nehme an, das heißt, dass wir nicht mehr zusammen auftreten werden?}
{162}{}{Ja. Wir haben erfahren, dass Martin tot ist. Wir wissen nicht, wer es getan hat, aber wir wissen, dass er auf diese Band und ganz besonders auf dich neidisch war. Und du wusstest es auch. Tut mir leid, aber die Geschichte ist zu verdächtig ... So neidisch Martin auch war, er war trotzdem einer von uns. Bevor du aufgetaucht bist, haben wir gut zusammengearbeitet. Deshalb glauben wir, es wäre das Beste, wenn wir uns auflösen. Danke für alles.}
{163}{}{Ja, ich habe ihn aus dem Weg geschafft. Genau wie er es mit mir versucht hat. Wo ist da der Unterschied?}
{164}{}{Na gut, macht's gut, Leute! Viel Glück mit eurer neuen Band.}
{165}{}{[Ornette schüttelt den Kopf, während alle zu Boden blicken.] Sieht aus, als würden Weiße sich nie ändern. Das würdest du nicht verstehen, mach dir keine Sorgen.}
{166}{}{Na schön, leb wohl. Als ob ich deine beschissene Band gebraucht hätte. Ich kümmere mich allein um alles!}
{167}{}{Ja. Darauf hast du dich mit Martin geeinigt. Außerdem, entschuldige die Offenheit, aber er ist als Sänger viel besser als du. Er wurde dafür geboren. In einer Sache könnte er recht haben – Jazz ist was für Schwarze. Das ist nicht diskriminierend gemeint, so kommt es einfach. Wir gehen wohl besser getrennte Wege. Danke für alles. Besonders dafür, dass du uns wieder zusammengebracht hast. Wir werden es nicht vergessen.}