{100}{}{Du siehst Martin.}
{101}{}{Du siehst einen abgehärteten alten Schwarzen.}
{102}{}{Nein, ich werde nicht mit dir über das Wetter und den ganzen Scheiß plaudern.}

#Ïğèìå÷àíèå: Ïåğñîíàæ äîñòóïåí òîëüêî ïğè èãğå çà ìóæñêîãî ÃÃ

{110}{}{[Als er dich bemerkt, verziehen sich seine Lippen zu einem Grinsen. Offenbar hat er auf dich gewartet.] Na, wen haben wir denn da? Was ist los? Habe ich deine kostbaren Gefühle verletzt? Wird dir ganz übel bei dem Gedanken, dass ein armseliger *Schwarzer* dich übertrumpft hat? Hmpf ... Für dich ist Jazz nur ein Geschäft, eine Möglichkeit, den Einheimischen schnell ein paar Kröten abzunehmen. Du verstehst es nicht. *Ich* sollte an deiner Stelle sein. Ich! Jazz war mein Leben!}
{111}{}{Das ist lustig. Jetzt bist du dran zu sterben.}
{112}{}{Das hättest du wirklich nicht tun sollen, Martin.}

{113}{}{Ha! Wenn du mir auch nur ein Haar krümmst, bist du bei uns erledigt, ganz besonders bei Ornette. Wir sind *das Volk*. Du gehörst nicht zu uns - du wirst NIEMALS zu uns gehören. Denk darüber nach.}
{114}{}{Hab ich schon. Scheiß auf die Band. Ich will nur, dass du tot bist.}
{115}{}{Na gut, aber fühl dich nicht zu sicher. Man weiß nie, wann ich meine Meinung ändere.}

{116}{}{Oh, du bist zurück? Konntest wohl einfach nicht fernbleiben, was?}
{117}{}{Soweit ich weiß, geht es bei Jazzmusik um Freude und Nächstenliebe. Mir scheint, du bist derjenige, der hier nicht hingehört.}
{118}{}{Dein Stolz hat Renos Bewohnern die letzte Chance auf echte Kultur genommen. Wenn dir die Musik wirklich etwas bedeutet, musst du Platz machen.}
{119}{}{Was zum Teufel weißt du schon über ... Über ... Scheiße. Vielleicht bin ich zu weit gegangen. Aber zu meinen Prinzipien stehe ich. Du solltest keinen Jazz spielen ... Du *kannst* keinen Jazz spielen! Das ist unsere Kultur, nicht deine!}
{120}{}{Was für ein Witz! Musik - ha! Jazz ist nicht einfach nur Musik, es ist eine Kultur - unsere Kultur! Du wirst es nie verstehen.}

{121}{}{Na gut. Nimm meinen Platz ein. Man sagt, deine Stimme sei ohnehin viel besser.}
{122}{}{Beruhige dich, damit wir wie Erwachsene reden können.}
{123}{}{Bist du wieder hier, um mir die Zeit zu stehlen? Ich bin nicht dein Minnesänger, weißt du. Ich habe Besseres zu tun, als dich zu unterhalten.}
{124}{}{Erzähl mir von deiner alten Band.}
{125}{}{Warum interessiert dich das? Du wirst es sowieso nicht verstehen. Du hast deine Band gegründet - wozu? Ruhm? Geld? Aber wir hatten Herz. Es war das „goldene Zeitalter“ von New Reno. Die Stadt war im Gleichgewicht, und selbst Leute wie wir konnten auf die Bühne gehen und zum Wohl aller spielen, für Schwarze und Weiße gleichermaßen.}
{126}{}{Unser wichtigster Mann war Big Louie. Wir nannten ihn so, weil der echte Louie klein war, während dieser Kerl nicht in den Club kam, ohne sich den Kopf am Türrahmen zu stoßen. Heh ... [Er lächelt nostalgisch und blickt in die Ferne] Anfangs kamen nur unsere Leute, um uns zuzuhören. Dann tauchten die einflussreichen Weißen auf ... Aber eigentlich nicht wegen des Jazz. Sie wollten zeigen, wie „tolerant“ sie sind. Für sie waren wir ... Zootiere.}
{127}{}{Und wir waren frei. Frei von Geld, Macht und Politik – frei von all dem. Aber das hielt nicht lange an. Bald ging das „goldene Zeitalter“ zu Ende, und die Probleme begannen. Big Louie zog ins Ödland. Ornette und ich sind die Einzigen, die noch übrig sind ... [Er schüttelt sich aus seiner Träumerei] Aber glaub ja nicht, ich hätte dir das erzählt, um deine Neugier zu befriedigen! Ich wollte dir nur eine Vorstellung davon geben, wie diese Zeiten waren. Aber ich erwarte nicht, dass du das verstehst.}
{128}{}{[Weiter]}

{129}{}{Was?! Du meinst es ernst? Ich ... ich habe lange davon geträumt ... [Sein Gesichtsausdruck wird hart] Aber ich soll dir einfach geben, was du willst? Niemals. Zuerst will ich eine Entschuldigung. Dann nehme ich vielleicht deinen Platz ein.}
{130}{}{Schluss damit, ich hab genug davon. Zieh endlich deinen verdammten Kopf aus dem Arsch, sonst gibt es keine Band! Nie wieder!}
{131}{}{Was für eine Entschuldigung?}
{132}{}{Ich bin raus. Viel Spaß dabei, allein zu sterben. Es wird dich freuen zu hören, dass Renos Jazzkultur mit dir sterben wird.}
{133}{}{Erpressung? Heh ... Ich wusste es. Du kannst es einfach nicht ertragen, einem Schwarzen Anerkennung zu zollen.}
{134}{}{Ach, ein Ultimatum, ja? [Seine Augen leuchten feurig auf] Ich zeig's dir. Ich zeig euch allen, was echter Jazz ist! Und jetzt verschwind! Ich muss ungestört üben.}
{135}{}{Na gut.}

{136}{}{[Er zieht die Hose herunter und dreht sich um] Küss mir den Arsch, dann vergesse ich alles.}
{137}{}{Äh ...}
{138}{}{Na los! [Er wackelt mit dem Hintern und grinst über die Schulter] Mach schon! Und nicht nur ein Küsschen auf die Wange – ich will, dass jeder Quadratzentimeter meines Arsches von deinen Lippen feucht ist! Nur das allein genügt!}
{139}{}{Also gut ... Im Namen der Kunst ... [Tu es]}
{140}{}{Jetzt nicht und niemals. Zieh deine Hose hoch, bevor ich dir ein Stuhlbein in den Darm ramme.}
{141}{}{Das war der Tropfen, der das Fass zum Überlaufen brachte. Der Deal ist geplatzt. Verrecke allein und vergessen, das ist mir egal.}
{142}{}{Oh ja! Das reicht. Betrachten wir den Streit als begraben. Und jetzt ... Lass mir Zeit, ungestört zu üben.}