{100}{}{Du siehst einen Bettler.}
{101}{}{Du siehst einen Obdachlosen.}
{102}{}{Du siehst einen Landstreicher.}
{103}{}{Du siehst einen Armen.}

{104}{}{Du siehst einen abgewrackt wirkenden Junkie.}

{105}{}{Ein armer Mann, der unter freiem Himmel schläft.}
{106}{}{Eine arme Frau, die unter freiem Himmel schläft.}
{107}{}{Du siehst einen schmutzigen und stinkenden Junkie.}

#Ïîñëå ïîäàÿíèÿ
{110}{}{Du bist ... Du bist ein Heiliger ... [er schluchzt vor Freude]}
{111}{}{Danke, danke, danke ... [er schluchzt vor Freude]}

{112}{}{Dank dir werde ich mindestens noch ein paar Tage leben ...}
{113}{}{Das Zittern wird wiederkommen, aber du hast mir eine Chance gegeben!}

#Ïğèìåíåíèå ïğåäìåòîâ
{120}{}{Dieser arme Mensch muss zumindest vorerst nicht mehr hungern.}
{121}{}{Dieser Junkie braucht keinen weiteren Schuss.}
{122}{}{Dieser Junkie braucht etwas anderes.}
{123}{}{Dieser Junkie braucht etwas anderes.}
{124}{}{Dieser Mann braucht etwas anderes.}
{125}{}{Diese Frau braucht etwas anderes.}

#Ïîïûòêà çàãîâîğèòü ñ íèùèì
{150}{}{Bitte helft den Obdachlosen!}
{151}{}{Helft uns bitte!}
{152}{}{Gebt uns etwas zu essen! Ich habe seit zwei Tagen nichts gegessen!}
{153}{}{Hast du etwas Kleingeld übrig?}
{154}{}{Kannst du mir etwas Geld leihen, bis ich bezahlt werde?}
{155}{}{Ich verhungere ... Hast du irgendwas?}
{156}{}{Entschuldigung, hast du etwas Kleingeld übrig?}
{157}{}{Bitte gib mir etwas, damit ich mir ein Stück Brot kaufen kann!}
{158}{}{Du würdest einem Blinden doch helfen, oder?}
{159}{}{}

#Ïîïûòêà çàãîâîğèòü ñ íàğêîìàíîì
{170}{}{Bitte ... Ich brauche einen Schuss ...}
{171}{}{Mir geht es so schlecht ...}
{172}{}{Wie spät ist es? Ist auch egal ...}
{173}{}{Sterbe ich?}
{174}{}{Oh, mein Kopf ...}
{175}{}{Oh, meine Leber ...}
{176}{}{Alles tut weh ...}
{177}{}{[Starrt ins Leere]}
{178}{}{Du! Hör auf, den Himmel kreisen zu lassen!}
{179}{}{Hey, warum so laut?}
{180}{}{Sieh mal, wie groß mein Fuß ist. Damit könnte ich einen Zwerg zerquetschen.}
{181}{}{Wie bin ich im Wald gelandet?}
{182}{}{Alles ist so süß ... Warum ist es süß?}
{183}{}{Willst du sehen, wie ich fliege?}

#Ïğîèçâîëüíûå ïëàâàşùèå ôğàçû (àâòîğû Kerb è BlackDesigner)
{200}{}{Es wäre besser gewesen, wenn ich im Mutterleib gestorben wäre ...}
{201}{}{Wie bin ich nur so geworden?}
{202}{}{Mir geht es schrecklich ...}
{203}{}{Ich bin so hungrig, ich würde einen Stiefel essen.}
{204}{}{Oh ...}
{205}{}{:: seufzt ::}
{206}{}{Reno ... Reno ...}
{207}{}{Heute werde ich sterben.}
{208}{}{Ich war einmal ein angesehener Mann ...}
{209}{}{Warte ... Ah, nein, nichts.}
{210}{}{[Richtet zerrissene Kleidung]}

{211}{}{Wenigstens ist Armut ehrlich, oder? [schluchzt]}
{212}{}{Warum sollte ich den Tod fürchten? Ich bin bereits in der Hölle ...}
{213}{}{Das Leben ist nicht nur schwarz und weiß ... Es ist einfach nur schwarz.}
{214}{}{Wie oft kann man seinen eigenen Piss trinken?}
{215}{}{Wenn ich doch nur eine Katze finden könnte ... Mmm, lecker ...}
{216}{}{Vor dem Krieg habe ich Tauben gefangen ... Wo sind sie hin?}
{217}{}{Wenigstens ist jeder Tag ein freier Tag ...}
{218}{}{Warte, warte, warte ...}