{100}{}{Du siehst einen Straßenjungen.}
{101}{}{Du siehst einen Straßenjungen in Lumpen. Es scheint, als wolle er mit dir reden.}
{102}{}{Guten Tag.}

{110}{}{Mein Herr, warten Sie! Hören Sie mich an!}
{111}{}{Klar, was willst du?}
{112}{}{Geh weg, ich bin keine Wohltätigkeitsorganisation.}

{113}{}{Nein, ich will nichts! Ein Mann hat mich geschickt, um mit dir zu reden! Ich habe sein Gesicht nicht gesehen, aber er sagte, er wolle dich im Silver Legacy Hotel treffen!}
{114}{}{Ein geheimes Treffen im Hotel ... Wie faszinierend. Wo finde ich ihn?}
{115}{}{Ich habe ein mieses Gefühl dabei. Wenn du mir eine Falle stellst, finde ich dich und ziehe dir die Eingeweide aus dem Arsch, verstanden?}
{116}{}{Er sagte, er wäre im Hotel Silver Legacy, mittleres Zimmer im zweiten Stock. Du sollst allein kommen.}
{117}{}{Danke, Kleiner. Hier sind zwei Dollar. Hol dir was zu essen.}
{118}{}{Danke, Kleiner. Du kannst gehen.}
{119}{}{Vielleicht tauche ich auf, vielleicht auch nicht. Und jetzt: Abflug! Ich bin beschäftigt.}

#Female version
{1110}{}{Miss, warten Sie! Hören Sie mich an!}
{1113}{}{Nein, ich will nichts! Ein Mann hat mich geschickt, um mit dir zu reden! Ich habe sein Gesicht nicht gesehen, aber er sagte, er wolle dich im Silver Legacy Hotel treffen!}
{1116}{}{Er sagte, er wäre im Hotel Silver Legacy, mittleres Zimmer im zweiten Stock. Du sollst allein kommen.}
{1118}{}{Danke, Kleiner. Du kannst gehen.}