{100}{}{Du siehst einen zwielichtig wirkenden Kerl.}
{101}{}{Du siehst ... einen Killer!}
{102}{}{Du siehst einen verdächtigen Kerl mit einem vertraut wirkenden Tattoo am Hals.}
{103}{}{Du siehst einen Killer, der dich unbedingt erschießen will.}
{104}{}{Wir sehen uns in der Hölle, Schlampe!!!}
{105}{}{Big Louie lässt grüßen! Fress Blei, Schlampe!!!}

{110}{}{Du hast dich mit den falschen Motherfuckern angelegt, Schlampe! Jetzt ist Schluss mit lustig!}
{111}{}{Hey, was soll das?!}
{112}{}{Tu nicht so unschuldig, Schlampe! Ich hab gesehen, wie du meine Jungs in Lovelock umgebracht hast! Ohne die Gang bin ich niemand! Mit diesem Tattoo am Hals nimmt mich keiner! Mein Leben ist vorbei – aber dich nehme ich mit! [er richtet seine Waffe auf dich, die schiefen Zähne in einem animalischen Knurren entblößt]}
{113}{}{Warte, wir können darüber reden!}
{114}{}{Ich schätze, einen hab ich übersehen. Dann machen wir jetzt Schluss damit.}

{115}{}{Hast du mir noch was zu sagen, Schlampe?!}
{116}{}{Eigentlich, vergiss es. Es ist einfacher, dich einfach umzubringen.}

{117}{}{Du glaubst doch nicht wirklich, dass du mich besiegen kannst, oder?}
{118}{}{Verdammt richtig, Schlampe! Dein Glück ist aufgebraucht!}
{119}{}{Hör mir doch einfach zu!}

{120}{}{Äh ... Na ja ... Oh, Scheiße, was hab ich mir nur gedacht? Du bist eine verdammte Killermaschine! Scheiß drauf – vergessen wir das Ganze einfach. Ich will leben!}
{121}{}{Oh, das wird nicht passieren. Ich wollte nur, dass du weißt, was für ein Idiot du bist, bevor du stirbst.}
{122}{}{Gut. Gehen wir einfach getrennte Wege.}

{123}{}{All deine Kumpels sind tot, aber das Schicksal hat dich verschont. Ist das nicht ein Zeichen von oben?}
{124}{}{Schlampe, die Einzige, die das Schicksal heute holt, bist DU!}
{125}{}{[Er zögert] Äh ... Was meinst du?}
{126}{}{Das ist deine Chance auf einen Neuanfang. Willst du dein neues Leben wirklich mit einem weiteren Mord beginnen?}
{127}{}{Das ... Das ist doch Bullshit! Ich hab dir sogar für eine Sekunde geglaubt, aber nein, du bist nur eine Schlampe, die um Gnade bettelt. Aber ... Vielleicht, wenn sie tot sind und ich lebe ... Vielleicht ist das wirklich ein Zeichen. Als hätten sie mich nur zurückgehalten. Ja ... Und du, Schlampe, merk dir das immer als *dein* Zeichen des Schicksals. Denk an den Tag, an dem *ich* dich am Leben ließ. Bet besser, dass wir uns nie wieder begegnen.}

{128}{}{Selbst wenn du mich umbringst, werden meine Auftraggeber in Reno nicht ruhen, bis sie dich gefunden haben.}
{129}{}{HA-HA-HA! Glaubst du, ich bin so blöd, Schlampe? Wie glaubst du, hab ich dich überhaupt gefunden? Ich hab mich umgehört – und keiner der Anführer in Reno will etwas mit dir zu tun haben! Verdammt, jetzt hast du mich NOCH mehr auf die Palme gebracht!}
{130}{}{...Oh, Scheiße. Äh, vergessen wir einfach, dass das passiert ist, ja? Ist doch nichts passiert?}

{131}{}{Nur in Reno weiß man etwas von diesem Tattoo. In einer anderen Stadt wird man es nicht erkennen.}
{132}{}{HA! Das ist alles, was du draufhast, Schlampe? Pech gehabt! Zeit, dir den hohlen Schädel wegzupusten!}
{133}{}{Äh ... [Er senkt die Waffe und sieht dich vorsichtig an] Weißt du ... Du hast den Rest unserer Bande erledigt ... Vielleicht sollte ich meine Verluste begrenzen. Scheiß drauf! Ich bin weg!}
{134}{}{Ich zahle dir 1000 $ für die Unannehmlichkeiten.}
{135}{}{Versuch nicht, mich für dumm zu verkaufen, Schlampe! Du hast nichts! Ich kann Geld wittern wie eine Ratte Fleisch!}
{136}{}{Hm ... Vielleicht ist das ein besseres Geschäft, als mein Leben zu riskieren. Na gut, wirf mir das Geld rüber, dann sind wir quitt.}
{137}{}{Hier ist das Geld. Nimm es, und wir gehen getrennte Wege.}

{138}{}{Du erhältst Erfahrung dafür, dass du das Problem ohne Gewalt gelöst hast.}

#Æåíñêèå ğåïëèêè
{1110}{}{Du hast dich mit den falschen Motherfuckern angelegt, Schlampe! Jetzt ist das Spiel vorbei!}
{1112}{}{Spiel mir gegenüber nicht den Unschuldigen, Schlampe! Ich hab gesehen, wie du meine Jungs in Lovelock umgelegt hast! Ohne die Gang bin ich niemand! Mit diesem Tattoo am Hals nimmt mich keiner! Mein Leben ist vorbei – aber dich nehm ich mit! [er richtet seine Waffe auf dich, die schiefen Zähne zu einem tierischen Knurren entblößt]}
{1121}{}{Oh, das wird nicht passieren. Ich wollte nur, dass du weißt, was für ein Idiot du bist, bevor du stirbst.}
{1133}{}{Äh ... [er senkt die Waffe und sieht dich vorsichtig an] Weißt du ... du hast den Rest unserer Gang *tatsächlich* erledigt ... Vielleicht sollte ich meine Verluste begrenzen. Scheiß drauf! Ich hau ab!}


