{100}{}{Du siehst Machete.}
{101}{}{Du siehst einen einschüchternden Leibwächter. Schon sein Anblick lässt dich den Kopf in den Sand stecken wollen.}

#Îñíîâíàÿ ÷àñòü äèàëîãà è ïğîïóñê ê áîññó
{105}{}{Der Boss ist tot! Alles ist vorbei!}

{110}{}{Halt! Du stehst im Haus von Mr. Luciano. Was willst du vom Boss?}
{111}{}{Ich muss mit ihm reden.}
{112}{}{[Er nickt zur Begrüßung] Der Boss erwartet dich.}
{113}{}{Eigentlich nichts, ich bin wegen etwas anderem hier.}

{114}{}{Wegen was?}
{115}{}{Ich suche Arbeit.}
{116}{}{Äh, nichts. Ich wollte nur plaudern.}
{117}{}{[Er winkt ab] Um solche Kleinigkeiten kümmert sich der Boss nicht. Dafür haben wir einen Verwalter.}
{118}{}{Mr. Chase meinte, ich könnte hier *ernsthafte* Arbeit finden.}
{119}{}{Warte hier. [Er klopft, geht in einen anderen Raum und kommt kurz darauf zurück] Der Boss ist bereit für dich. Sei ruhig und höflich. Mr. Luciano verdient Respekt, verstanden?}
{120}{}{Johnny Chase? Das ändert die Sache. }
{121}{}{Um solche "Kleinigkeiten" kümmere ich mich auch nicht. Ich bin wegen ... *ernsthafter* Arbeit hier.}
{122}{}{Ach, ist das so? [Er verschränkt die Arme und mustert dich] Du *wirkst* ernsthaft ... Vielleicht bist du wirklich vom Fach.}
{123}{}{Ich hab mit ihr gesprochen. Sie sagte, ich könnte *ernsthafte* Arbeit bekommen.}
{124}{}{Das wollte ich nur wissen. Tschüss.}
{125}{}{In Ordnung.}

#Ñòóêà÷
{126}{}{Weißt du, dass hier ein Spion herumschleicht?}
{127}{}{Ach ja? Wer?}
{128}{}{Ein Mann draußen namens Canary. Er reagiert auf den Code-Satz "Der Glanz ist aus unserem Zeitalter gewichen."}
{129}{}{Äh, niemand. Ich wollte nur sehen, ob du aufpasst. Gute Arbeit!}
{130}{}{Wir haben uns das angesehen, und du hattest recht. Der Boss sagte, ich soll dir das geben. }
{131}{}{Danke für die Kohle.}
{132}{}{Das ist noch nicht alles. Der Boss will mit dir reden. Geh rein.}
{133}{}{Großartig.}

{134}{}{Ich habe eine Nachricht von Mr. Wright.}
{135}{}{Ich hätte fast geglaubt, dass du zu uns gehörst ... }
{136}{}{Der Boss wartet. Geh rein.}
{137}{}{Großartig.}

#Ğàá èç Óğàí-Ñèòè
{138}{}{Das kostet dich 1.000 Dollar. Natürlich nur, wenn du keine Sondervereinbarung mit Mr. Luciano hast.}
{139}{}{Hey, wir reden hier von einem guten Sklaven! Er arbeitet hart, kennt seinen Platz, und die Rinder hören auf ihn. Sklaven wie ihn findet man selten.}
{140}{}{Ich möchte einen bestimmten Sklaven kaufen: Joseph aus Uranium City.}
{141}{}{Wir haben 250 Dollar für diesen Sklaven bezahlt. Wenn du keine Vereinbarung mit Mr. Luciano hast, warum sollten wir ihn verkaufen?}
{142}{}{Ich verdopple den Preis.}
{143}{}{Hmm. Na gut. 500 Dollar, und er gehört ganz dir.}
{144}{}{Hier, nimm das Geld.}
{145}{}{Ich überleg's mir.}
{146}{}{Abgemacht. Ich funke die Wachen an und sage ihnen, dass du deine Ware aus dem Pferch abholst.}
{147}{}{In Ordnung.}

{148}{}{Ihr habt einen Sklaven aus Uranium City. Ich möchte ihn kaufen.}
{149}{}{Ihr habt einen Sklaven vom Cheyenne-Stamm. Ich möchte ihn kaufen.}

#Ïğî èìÿ Ìà÷åòå è åãî îğóæèå
{150}{}{Ich frage nur ungern, aber wer bist du?}
{151}{}{Mein Name ist Machete Rodriguez. Merk ihn dir. Ich bin der persönliche Leibwächter des Bosses und Sicherheitschef auf der Ranch.}
{152}{}{Du hast einen seltsamen Namen ... Machete.}
{153}{}{Du bist nicht besonders helle, was? Das ist ein Spitzname. Rate mal, wie ich dazu kam.}
{154}{}{Das ist ein Spitzname. Willst du wissen, wie ich dazu kam?}
{155}{}{Nun, nett, dich kennenzulernen ... }
{156}{}{Nun, du hast ja keine Machete dabei, also ... }
{157}{}{Hmm ... Dein Name auch?}
{158}{}{Nein. Meine Eltern haben mich so genannt. Sie kamen nach den Bomben nach Reno.}
{159}{}{Schon gut.}
{160}{}{Wo haben sie vorher gelebt?}
{161}{}{Mexiko. Es liegt weit im Süden. Man sagt, dort hätten alle gehungert, also sind alle nach Norden gezogen. Jeder, der konnte.}
{162}{}{Zurück zu deinem Namen. Ich verstehe immer noch nicht ... }
{163}{}{[Er runzelt die Stirn] Nicht mehr. Ich habe sie im Kampf gegen die Hunde am Bahnhof südlich von Reno verloren. Ich habe überall gesucht, aber ich konnte sie nicht finden! Sie war die beste Waffe, die ich je besessen habe!}
{164}{}{Vielleicht kann ich bei der Suche helfen?}
{165}{}{Ich nehme an, du hast eine Waffe, die zu deinem Namen passt?}
{166}{}{Hey, wenn du sie findest, bist du mein neuer bester Freund! Ich bezahle dich dafür, dass sie wieder in meinen Händen ist. Aber nach dem Sturm, der vor einer Weile durchgezogen ist, liegt sie jetzt bestimmt unter dem Sand.}
{167}{}{Ich bringe dir deine Machete zurück. Warte hier.}
{168}{}{Ich habe deine Machete gefunden! Sie ist ziemlich rostig, scheint aber noch einsatzfähig zu sein.}
{169}{}{Ich habe deine Machete gefunden! Ich habe sie sogar für dich aufgearbeitet.}
{170}{}{Du hast sie gefunden! Ich kann es nicht glauben! Ich habe versprochen zu zahlen, und ich halte immer mein Wort. Danke.}
{171}{}{Das war nicht schwer.}
{172}{}{Ja? Sie spricht nicht gerade viele Empfehlungen aus. }

#Î ìåñòíîñòè
{180}{}{Was ist das hier für ein Ort?}
{181}{}{[Er verengt misstrauisch die Augen] Das ist die Ranch von Oliver Luciano, dem größten Geschäftsmann in Reno. Du solltest Respekt zeigen. Das hier ist das Büro. Die Ranch liegt hinter dem Gebäude.}
{182}{}{Ist eine Ranch wirklich so wichtig?}

{183}{}{Fünfzig Sklaven, zwei Dutzend Wachen, tonnenweise lebendes brahmin-Fleisch – ja, sie ist riesig.}
{184}{}{Sklaven?}
{185}{}{Du hast brahmin-Fleisch erwähnt. Kann ich welches bekommen?}
{186}{}{Klingt beeindruckend. Kann ich mich umsehen?}
{187}{}{}
{188}{}{Findest du es nicht falsch, Leute einzusperren und sie zur Arbeit zu zwingen?}
{189}{}{}
{190}{}{Habe ich gestottert? Ja, Sklaven.}
{191}{}{Damit habe ich nichts zu tun. Sprich mit der Verwalterin. Ihr Büro ist das Gebäude westlich von hier, hinten.}
{192}{}{Nein. [Er verschränkt die Arme] Nur Arbeiter und Freunde von Mr. Luciano dürfen auf der Ranch herumlaufen.}
{193}{}{}
{194}{}{[Er hebt überrascht eine Augenbraue, wirft dann den Kopf zurück und lacht] Du bist lustig! Diese Sklaven sind keine Menschen wie du und ich. Sie haben *Glück*, dass Boss ihnen für ihre Arbeit Essen und Sicherheit gibt! Er hat sie aus Slums und Dörfern geholt, wo sie sowieso kein eigenes Leben führen konnten. Für sie ist Boss ein *Gott*! Und warum auch nicht? Ohne ihn wären sie längst tot.}
{195}{}{Werden sie hier also nicht misshandelt?}
{196}{}{[Er sieht dich seltsam an] Bist du etwa in einem Vault aufgewachsen? Ich hab dir doch gesagt, dass sie nicht in der Lage sind, ihr eigenes Leben zu führen. Also müssen wir ihnen zeigen, wer das Sagen hat, sonst kommen sie noch auf *dumme* Ideen. Manchmal müssen wir sie daran erinnern.}
{197}{}{Kann ich dich noch einmal wegen der Ranch fragen?}

{200}{}{Brauchst du noch mehr Sklavenhalsbänder?}
{201}{}{Du hast Halsbänder? Sehr gut! Wir brauchen immer mehr davon. Ich zahle dir 100 Dollar für jedes, das du mir bringst.}
{202}{}{Dann habe ich Halsbänder zu verkaufen.}
{203}{}{Ich behalte meine Halsbänder erst mal.}
{204}{}{Wie viele hast du?}
{205}{}{[Ein Halsband]}
{206}{}{[Zwei Halsbänder]}
{207}{}{[Drei Halsbänder]}
{208}{}{[Fünf Halsbänder]}
{209}{}{[Alle: }
{210}{}{]}
{211}{}{[Er nimmt die Halsbänder und gibt dir 100 Dollar pro Stück] Gutes Geschäft. Wenn du noch mehr findest, zahle ich dafür.}
{212}{}{Gut.}

#Êâåñò Îëèâåğà ïî äèâåğñèè â êàçèíî
{220}{}{Mr. Luciano sagte, ich soll den Casino-Job mit dir besprechen.}
{221}{}{[Er sieht sich um und beugt sich dann vor, während er leise spricht] Boss hat dich ausgewählt? Ich hatte auf jemanden gehofft, der etwas ... härter ist. Ich plane das schon lange und will jemanden, der sich mit dem Geschäft auskennt.}
{222}{}{Ob du mir vertraust oder nicht: Mr. Luciano hat mich ausgewählt. Also legen wir los.}

{223}{}{Gut, wir haben zwei Ablenkungsmanöver zur Auswahl. Wenn du kannst, führ beide durch. Erstens: Gib den El Dorado Besuchern etwas vergiftetes Bier, damit sie mit dem Casino unzufrieden sind. Das wird Ricardos Aufmerksamkeit erregen. Woher du das Gift bekommst, ist deine Sache.}
{224}{}{Was ist die zweite Möglichkeit?}
{225}{}{Du hast doch gesehen, dass die Sicherheitsleute von El Dorado Tommyguns benutzen, oder? Bertolini hat vor zehn Jahren jede gekauft, die er finden konnte. Wann immer jemand eine Tommygun sieht, denkt er an El Dorado.}
{226}{}{Verstehe. Erzähl weiter.}
{227}{}{Du musst dir eine Tommygun besorgen und ein paar Zivilisten angreifen. Du musst niemanden umbringen, aber sorg dafür, dass jeder weiß, dass es ein Angriff war. Nimm dir jemanden wie eine Hure oder einen Slumbewohner vor. Die Leute werden denken, die Arbeiter von El Dorado verprügeln die Leute. Ricardo *muss* ermitteln.}
{228}{}{Mann, das ist alles? Hast du keine weiteren sinnlosen Komplikationen auf Lager? Na schön, dann mach ich mich wohl an die Arbeit. Viel Spaß dabei, auf deinem Arsch zu sitzen und nichts zu tun.}
{229}{}{Alles klar. Zeit, zur Sache zu kommen.}

{230}{}{Ich muss mit dir über den Casino-Job reden.}
{231}{}{Was, noch mehr Fragen?}
{232}{}{Erklär den Plan noch mal.}
{233}{}{Vergiss es, ich finde selbst eine Lösung.}

{234}{}{Du willst, dass die Leute sehen, wie ich mit einer Tommygun auf Zivilisten schieße. Aber wenn sie mein Gesicht sehen, wissen sie doch, dass ich nicht für das Casino arbeite. Sie könnten die Sache sogar auf dich zurückführen.}
{235}{}{Hm, guter Punkt. Okay, ich hab's. [Er reicht dir eine Sturmhaube.] Damit kannst du dein Gesicht verbergen. Trag nur nichts, woran die Leute dich erkennen könnten.}
{236}{}{Na gut.}

#Âçëîì ñåéôà ó Áåğòîëèíè
{237}{}{Kennst du jemanden, der beim Knacken von Safes helfen kann?}
{238}{}{Ich kenne einen Typen unten in der Innenstadt, der Basketball Buddy heißt. Früher hat er Schlösser geknackt, bis sie ihm ordentlich die Fresse poliert haben, he he. Aber bei Bertolinis Safe wird er wahrscheinlich nicht helfen. Du brauchst jemanden mit echten Fähigkeiten, und solche Leute gibt's in der Stadt nicht viele.}
{239}{}{Danke.}

#Êâåñò Îëèâåğà ïî äèâåğñèè ó ãàíãñòåğîâ
{240}{}{Mr. Luciano möchte, dass ich den Job mit dir bespreche.}
{241}{}{Lass uns noch mal über Mr. Lucianos Job reden.}
{242}{}{Du brauchst meine Hilfe, oder? Gib's einfach zu. Und ja, ich hab einen Plan.}
{243}{}{Erzähl ihn mir. Ich brauche deine ... Hilfe wirklich.}
{244}{}{Ich finde es selbst heraus. Ich will nicht, dass du dir noch was einbildest.}
{245}{}{[Er wird ernst.] Darüber haben wir schon gesprochen. Bei deinem schlechten Gedächtnis kann ich dir nicht helfen.}
{246}{}{[Er wird ernst.] Hm. Den letzten Job hast du erledigt. Na gut, vielleicht kriegst du das hin.}
{247}{}{[Weiter]}
{248}{}{Wir müssen Thompson und Stryker so weit bringen, dass sie wütend genug sind, um einen Krieg gegeneinander anzufangen.}
#Old version:
#Òåïåğü êàê ıòî ñäåëàòü. ß ïğåäëàãàş äèâåğñèş ñî âçğûâ÷àòêîé. Çàìèíèğóé ïàğàäíûå äâåğè â îáåèõ øòàáàõ.
#Åñëè íå ñìîæåøü ıòî ñäåëàòü, òîãäà åñòü åùå âàğèàíò ñ çàæèãàòåëüíûìè ãğàíàòàìè -
#çàêèäàé èìè îõğàííèêîâ è òóò æå óáåãàé, ïîêà òåáÿ íå çàñåêëè.
#È òî, è äğóãîå ñîçäàñò ìíîãî øóìà, à äàëüøå íà÷íóòñÿ ğàçáîğêè, êòî íà êîãî çàğûïàåòñÿ.
#İòî ïîçâîëèò âûèãğàòü âğåìÿ.
{249}{}{Am besten bringst du Sprengstoff an den Eingangstüren beider Hauptquartiere an. Das macht ordentlich Krach. Wenn du das nicht schaffst, töte an jedem Hauptquartier jemanden, ohne dass sie merken, dass du es warst. Sie werden einander die Schuld geben und uns mehr Zeit verschaffen.}
{250}{}{Was, wenn sie mich erkennen?}
{251}{}{Wo bekomme ich Brandgranaten her?}
{252}{}{Wo bekomme ich Sprengstoff her?}
{253}{}{Das reicht. Ich kümmere mich ab hier darum.}
{254}{}{Na endlich kann ich dich zu was gebrauchen. Jetzt darf ich die ganze Arbeit machen. Schon wieder.}
{255}{}{Hey, ich hab dir die Sturmhaube nicht für Partytricks gegeben, klar? Benutz deinen Kopf, Grünschnabel!}
{256}{}{Wenn du es nicht selbst schaffst, such dir jemanden, der es erledigt. Das ist dein Problem, nicht meins.}
{257}{}{Das ist dein Problem, nicht meins. Fang mit dem Mechaniker am Bahnhof an.}
{258}{}{Nimm das. [er reicht dir eine Sturmhaube] Setz sie auf, bevor du den Auftrag erledigst, dann erkennen sie dich nicht.}

#Êâåñò Îëèâåğà íà ñäåëêó ñ êàğàâàíùèêàìè
{260}{}{Mr. Luciano will, dass ich mich um ein paar Geschäfte kümmere. Er meinte, ich soll mit dir reden.}
{261}{}{Du? Hm, der Boss muss wohl etwas in dir sehen. Na gut, aber denk dran: Das hier ist *heikel*.}
{262}{}{Wie heikel?}
{263}{}{Ugh, sag mir nicht, dass ich eine Krawatte tragen muss!}
{264}{}{Dank der Wanzen, die du in Bertolinis Zimmer angebracht hast, haben wir von einem geheimen Geschäft außerhalb von Reno erfahren. Ricardo will Waffen besorgen. Im Moment will er sich während der Kämpfe nur selbst schützen, aber früher oder später wird er sich uns vorknöpfen.}
{265}{}{Also dafür hatte er den Koffer voller Geld ...}
{266}{}{Ja, und genau dafür werden wir es verwenden. Du gibst dich als jemand vom Casino aus und wickelst das Geschäft ab. Der Boss will sich die Karawane für die Zukunft gewogen halten ... wenn möglich. Aber am wichtigsten ist, dass wir die Waffen bekommen. Je besser du dich schlägst, desto besser geht es *allen*. Verstanden?}
{267}{}{Verstanden.}
{268}{}{Vertrau mir, was immer du „bekommst“, bekomme auch ich.}
{269}{}{Das Geschäft findet nachts außerhalb von Reno statt. Wenn du bereit bist, sprich mit mir.}
{270}{}{Ich bin jetzt bereit.}
{271}{}{Na gut, ich komme wieder, wenn ich bereit bin.}

{272}{}{Na, wie sieht's mit den Waffen aus?}
{273}{}{Es sind weniger, als wir gedacht hatten. Bertolini muss ein lausiger Tauschhändler sein, he-he! Wie dem auch sei, wir haben genug Waffen, um einen Angriff abzuwehren. Der Boss ist zufrieden. Er zeigt es zwar nicht ... niemals ... aber ich merke es.}
{274}{}{Das sind ganz schön viele Waffen für eine Ranch, oder?}
{275}{}{Der Boss will sich auf niemanden verlassen müssen. Diese Waffen sind nur ein Teil davon. Außerdem sind sie nicht nur für die Ranch, sondern auch für die Karawanen. Wir haben vieles zu beschützen, nicht nur hier.}
{276}{}{Verstehe. Na gut, ich gehe dann mal.}

#Æåíñêàÿ ğåïëèêà
{1113}{}{Eigentlich nichts, ich bin wegen etwas anderem hier.}
{1118}{}{Mr. Chase meinte, ich könnte hier *ernsthafte* Arbeit finden.}
{1130}{}{Wir haben uns das angesehen, und du hattest recht. Der Boss sagte, ich soll dir das geben. }
{1153}{}{Du bist nicht besonders helle, was? Das ist ein Spitzname. Rate mal, wie ich dazu gekommen bin.}
{1181}{}{[Er verengt misstrauisch die Augen] Das ist die Ranch von Oliver Luciano, dem größten Geschäftsmann in Reno. Du solltest Respekt zeigen. Das hier ist das Büro. Die Ranch liegt hinter dem Gebäude.}
{1225}{}{Du hast doch gesehen, dass die Sicherheitsleute von El Dorado Tommyguns benutzen, oder? Bertolini hat vor zehn Jahren jede gekauft, die er finden konnte. Wann immer jemand eine Tommygun sieht, denkt er an El Dorado.}
{1258}{}{Nimm das. [er reicht dir eine Sturmhaube] Setz sie auf, bevor du den Auftrag erledigst, dann erkennen sie dich nicht.}
{1264}{}{Dank der Wanzen, die du in Bertolinis Zimmer angebracht hast, haben wir von einem geheimen Geschäft außerhalb von Reno erfahren. Ricardo will Waffen besorgen. Im Moment will er sich während der Kämpfe nur selbst schützen, aber früher oder später wird er sich uns vorknöpfen.}
{1269}{}{Das Geschäft findet nachts außerhalb von Reno statt. Wenn du bereit bist, sprich mit mir.}
{1270}{}{Ich bin jetzt bereit.}
