{100}{}{Du siehst Essie Gate.}
{101}{}{Du siehst eine Frau mit einem traurigen, abwesenden Blick.}
{102}{}{Danke! Danke für alles!}
{103}{}{Danke für deine Mühe, aber wir müssen trotzdem gehen.}

#Ïåğâûé ğàçãîâîğ è 'èïîâûå ôğàçû
{110}{}{[Die Frau schaut schnell auf, als du den Raum betrittst, doch als sie dich sieht, blickt sie dich nur enttäuscht und ausdruckslos an] Oh ... Wenn du etwas verkaufen willst: Wir kaufen nichts. Und beitreten wollen wir auch nicht.}
{111}{}{Nein, ich wollte nur einer Einheimischen ein paar Fragen stellen.}
{112}{}{Dann haben wir nichts zu bereden. [Gehen]}

{113}{}{Oh, du bist nicht von hier? Entschuldige meinen unfreundlichen Empfang, aber in Reno trifft man nicht oft auf freundliche Fremde. Was willst du?}
{114}{}{Ja?}
{115}{}{Wer bist du?}
{116}{}{Kannst du mir etwas über die Stadt erzählen?}
{117}{}{Entschuldige, wir reden ein andermal.}
{118}{}{Reden wir über etwas anderes.}
{119}{}{}

{120}{}{Essie Gate. Ich bin nur eine Hausfrau ... Also komm bloß nicht auf dumme Gedanken.}
{121}{}{Was gibt's da schon zu erzählen? Geh durch Reno und sieh dir alles an, was du wissen musst. Es gibt nicht viel, was sich lohnt, und um das wenige streiten sich schon alle. Aber es ist immer noch besser als der Rest von Nevada. Was bleibt uns also für eine Wahl?}
{122}{}{}
{123}{}{}
{124}{}{Was war noch mal mit deinem Mann?}
{125}{}{Wegen der Sache mit deinem Mann ... }
{126}{}{Ich bin neu hier. Kannst du mir sagen, wie ich mich in dieser Stadt einleben kann?}
{127}{}{Ich habe eine Notiz von einem gewissen Robert, der hier gelebt hat. Sagen dir diese etwas?}
{128}{}{}
{129}{}{}

#Äî ïîëó÷åíèÿ êâåñ'à
{130}{}{Ich bin neu hier. Kannst du mir sagen, wie ich mich in dieser Stadt einleben kann?}
{131}{}{Ich kann dir nicht helfen. Aber ... Wenn es dir nichts ausmacht ... Ach, vergiss es. Ich habe ohnehin nichts, womit ich dich bezahlen könnte.}
{132}{}{Du kannst nicht bezahlen? Na, dann haben wir nichts zu bereden.}
{133}{}{Wenn du nichts zu bezahlen hast, dann bezahl eben nichts. Sag mir, was du brauchst.}
{134}{}{Spuck's einfach aus, und *ich* entscheide, ob ich's machen will, okay?}
{135}{}{[Die Frau seufzt schwer und schließt die Augen] Ich habe mitgehört, wie Robert mit Mark darüber gesprochen hat, zu irgendeinem Militärstützpunkt zu gehen. Ich kann nur raten, was mit ihm passiert ist. Ich wollte ihn nicht gehen lassen, aber wie hätte ich ihn aufhalten sollen? Mr. Wright hat den Befehl persönlich gegeben!}
{136}{}{Okay, warte, warte, warte. Jetzt ganz langsam, und erzähl mir genau, was passiert ist!}

{137}{}{Oh, entschuldige ... }
{138}{}{Wer ist Robert?}
{139}{}{Wer ist Mark?}
{140}{}{Wer ist dieser Mr. Wright?}
{141}{}{Was für einen Auftrag?}
{142}{}{Was für ein Militärstützpunkt?}
{143}{}{Glaubst du, Robert ist etwas zugestoßen?}
{144}{}{Das ist alles, was ich wissen muss.}

{145}{}{Robert ist mein Mann. Er ist ein ... Prospektor nennt man sie wohl. Er sucht in alten Ruinen nach nützlichen Dingen aus der Vorkriegszeit und verkauft sie dann an Händler.}
{146}{}{Er war der Partner meines Mannes. Ein Prospektor wie Robert, nur weniger erfahren.}
{147}{}{Sei froh, dass du nicht weißt, wer Mr. Wright ist. Er ist einer der Geschäftsmänner von Reno. Ihm gehören diese Slums, das heißt, wir gehören ihm.}
{148}{}{Ich weiß es nicht. Mr. Wright brauchte etwas vom Militärstützpunkt, aber noch ist niemand hineingekommen. Er heuerte Robert und seinen Partner an, damit sie die Ersten sind.}
{149}{}{Hawthorne, glaube ich, heißt er. Ich weiß nicht viel darüber, aber man sagt, seit dem Krieg sei niemand mehr drinnen gewesen. Robert wusste mehr.}
{150}{}{Robert hat uns immer Nachrichten geschickt, wenn er draußen im Ödland war. Aber wir ... Wir haben schon lange nichts mehr von ihm gehört ... }

{151}{}{Also wirst du uns helfen, Robert zu finden?}
{152}{}{Zuerst brauche ich mehr Informationen.}
{153}{}{Oh, natürlich ... }
{154}{}{Ich helfe dir gern.}
{155}{}{Nein, ich habe keine Zeit dafür. [Gehen]}
{156}{}{Oh, danke! Robert hat diese Koordinaten hinterlassen. Ich weiß nicht, was sie bedeuten, aber ich bin sicher, du wirst es verstehen. Bitte sei vorsichtig.}
{157}{}{Na gut. Sehen wir mal, was Sache ist.}

{158}{}{[In ihren Augen flackert kurz Hoffnung auf, doch sie verschwindet sofort wieder] Ja?}
{159}{}{Ich brauche mehr Informationen.}

#Ëèñ'îâêà î' ìóæà èç Õî'îğíà
{160}{}{Was?! Was ist das?! Zeig es mir, sofort!}
{161}{}{Nicht so schnell, Frau. Diese Lieferung ist eine Menge Geld wert ... }
{162}{}{Natürlich. Nimm es.}
{163}{}{Äh, Mist, ich hab's irgendwo liegen lassen. Ich bin gleich zurück.}

{164}{}{[Sie schnappt sich ihren letzten Geldvorrat und schüttelt }
{165}{}{[ dollars] Hier! Das ist alles, was wir haben. Und jetzt gib mir den Zettel!}
{166}{}{Das ist alles?! Verdammt, ich habe mein eigenes Leben riskiert! Gib mir das Bild, den Bücherstapel und ein frisches Sandwich vom Tisch, *dann* gebe ich dir den Zettel.}
{167}{}{Klar.}
{168}{}{[Sie senkt den Kopf und sieht dich an] Ich bezahle es. Mit jedem letzten Stück Brot, das wir haben! Gib mir einfach den Zettel!}
{169}{}{[Sie liest den Text schweigend und schließt dann müde die Augen] Ich wusste es ... Ich wusste, dass es so enden würde ...}
{170}{}{Was?}
{171}{}{Das ist mir eigentlich egal ...}
{172}{}{[Sie scheint dich nicht zu hören] Früher oder später musste es passieren. Robert war gut, aber eine Militärbasis? Nein, das war zu gefährlich ... Viel zu gefährlich ...}
{173}{}{Das kannst du laut sagen.}
{174}{}{Aber warte, wo ist Mark?!}
{175}{}{Wer?}
{176}{}{Roberts Partner! Er müsste wissen, was dort passiert ist ... Falls er noch lebt.}
{177}{}{Es gab keine zweite Leiche. Aber warum brauchst du ihn?}
{178}{}{Hör zu ... Das ist kompliziert. Unsere Familie lebte von ihrer Arbeit. Sie bezahlten Miete und Strom, indem sie für Mr. Wright auf Erkundung gingen. Ohne sie ... Unsere Schulden ... Wir können froh sein, wenn er uns nicht in die Sklaverei verkauft. Wenn Mark noch lebt, könnte er die Arbeit zu Ende bringen.}
{179}{}{Was für grausame Gesetze ihr hier habt ...}

{180}{}{Oh ja. Mr. Wright ist ein herzloser Mann. Aber man kann es ihm nicht verübeln. Wir stehen wirklich in seiner Schuld.}
{181}{}{Was, wenn ich mit Wright rede?}
{182}{}{Vielleicht weiß Marks Familie etwas?}
{183}{}{Ich werde versuchen, Mark zu finden und die Sache in Ordnung zu bringen.}
{184}{}{Ich habe meinen Teil der Abmachung erfuellt. Das geht mich nichts an.}

{185}{}{Mit Mr. Wright? Mit ihm kann man nicht einfach ... »reden«. Wenn du sein Haus betreten willst, kann ich dir nur raten: Wähle deine Worte mit Bedacht.}
{186}{}{Vielleicht, aber sie wollen nicht mit uns reden. Sie sind so wütend geworden ... Ich weiß nicht, warum.}
{187}{}{Oh, danke. Bitte bring uns bald Neuigkeiten.}
{188}{}{Tschüss.}
{189}{}{Ja, wir verstehen ...}
{190}{}{Tschüss.}

#Çàâåğøåíèå êâåñ'à
{200}{}{Wegen Mark.}
{201}{}{Hast du etwas herausgefunden?}
{202}{}{Mark hat die Stadt verlassen und ist irgendwo nach Norden geflohen. Ich glaube nicht, dass du ihn je wiedersehen wirst.}
{203}{}{Nein, noch nicht.}
{204}{}{Also ist er einfach abgehauen? Er hätte uns wenigstens sagen können, was mit Robert passiert ist! Dieser Bastard! Das ... Nein, daran kann ich jetzt nicht denken. Wir müssen weg. Wenn niemand diesen Auftrag erfuellt, wird Mr. Wright uns holen kommen. Und du ... Danke, dass du versucht hast, uns zu helfen.}
{205}{}{Mal sehen. Vielleicht gibt es noch Hoffnung ...}
{206}{}{Ist das alles? Verdammt, nach der Reise gibt's nicht mal was zu essen ...}
{207}{}{Mark ist aus der Stadt geflohen, aber ich habe ihn überredet zurückzukommen. Das wird dein Problem allerdings nicht lösen ...}
{208}{}{}
{209}{}{}

{210}{}{Um deine Schulden musst du dir keine Sorgen mehr machen. Wright ist tot.}
{211}{}{Ich habe gute Neuigkeiten. Jemand hat den Auftrag deines Mannes erfuellt, also hat Wright deine Schulden erlassen.}
{212}{}{Oh mein Gott! Glaubst du wirklich, *das* wäre eine Lösung?! Was wird jetzt aus den Slums?! Seine Söhne werden sich ihretwegen bekämpfen – und uns alle im Kreuzfeuer umbringen! Wir müssen weg. Trotzdem danke, dass du uns gewarnt hast. So haben wir Zeit, uns etwas zu überlegen.}
{213}{}{Gern geschehen.}
{214}{}{Was?! Aber wie? ... Du warst es, nicht wahr? Danke, danke! Das hätte sonst niemand für uns getan! Warte ... In Reno hat alles seinen Preis. Falls du das noch nicht weißt – merk es dir. [sie hält ein rundes Gerät mit herausragenden Drähten hin] Robert wollte damit seinen Metalldetektor verbessern. Wir brauchen es nicht mehr, aber vielleicht kannst du es gebrauchen. Nochmals vielen Dank für alles! Du hast uns das Leben gerettet!}
{215}{}{Pass auf dich auf.}

#Female character
{1166}{}{Das ist alles?! Verdammt, ich habe mein eigenes Leben riskiert! Gib mir das Bild, den Bücherstapel und ein frisches Sandwich vom Tisch, *dann* gebe ich dir den Zettel.}
