{100}{}{Du siehst Colin.}
{101}{}{Du siehst einen Bürger. Du hast das Gefühl, seine Mutter hat ihm nie Manieren beigebracht.}
{102}{}{Die meisten Leute halten es nicht für ein Talent, allen auf die Nerven zu gehen, aber bei dir hat es definitiv funktioniert.}

{110}{}{[Zieht sich wütend an den Haaren] Töten! Ich bringe sie beide um! Und dich auch! Ich werde die ganze Welt in Brand setzen! Ich... [plötzlich verlässt ihn die Kraft, und er sinkt auf die Knie] Ich habe sie geliebt! Ich habe ihr alles gegeben! Die besten Jahre meines Lebens! Und sie geht zu IHM zurück! Warum, warum...? Er könnte sie niemals so lieben wie ich...}
{111}{}{[So leise wie möglich gehen]}

{112}{}{Ich weiß, was ich getan habe, klingt schrecklich... Aber für die Frau, die man liebt, kann man alles tun.}
{113}{}{Brichst du in jedes Haus ein, oder sind wir ein Sonderfall? Ach, und wo wir gerade dabei sind: Lass meine Frau in Ruhe.}
{114}{}{Ich würde jeden töten, um meine Familie zu beschützen!}

{120}{}{Wer zum Teufel bist du? Du solltest einen verdammt guten Grund haben, in mein Haus zu platzen!}
{121}{}{Pass auf, was du sagst! [Schlag ihm auf den Kiefer]}
{122}{}{Ich bin unwichtig. Dein Freund in den Abwasserkanälen allerdings ...}
{123}{}{Hey, reg dich nicht auf! Ich gehe ja schon.}
{124}{}{Wie unhöflich! Wenn du dich so aufführen willst, habe ich kein Interesse daran, mit dir zu reden. Leb wohl.}
{125}{}{Und wer genau bist du?}
{126}{}{Wer ich bin?! Ich bin Colin – der verdammte Hausherr! Und das ist meine Frau Shelley. Wir zahlen unsere Miete und kümmern uns um unseren eigenen Kram! Das solltest du auch tun!}
{127}{}{Mich würde es persönlich nicht kümmern, aber du hast definitiv etwas mit einem Mann in den Abwasserkanälen zu tun ...}

{130}{}{[Colin fällt mit dem Rücken hart zu Boden, während seine Frau schreit] Arrrgh! Was zum Teufel stimmt nicht mit dir?!}
{131}{}{Das war für den Ghoul, der seit zehn Jahren in den Abwasserkanälen lebt, du Hurensohn!}
{132}{}{Chris?! Oh Gott, er lebt?!}
{133}{}{Besser denn je. Und er ist zurück, um sich zu rächen!}
{134}{}{Nicht deinetwegen. Wegen dem, was du getan hast, saß er ein Jahrzehnt lang in den Abwasserkanälen fest und musste Rattenfleisch essen.}

{140}{}{Mich würde es persönlich nicht kümmern. Der Mann, den du eingesperrt hast, allerdings ...}
{141}{}{[Er wird plötzlich ganz still und regungslos] Wa... Was für ein Mann? Ich habe keinen Mann eingesperrt.}
{142}{}{Shelleys erster Ehemann. Du hast ihn in die Kanalisation gestoßen und für immer eingemauert. Seit Jahren ernährt er sich von Ratten, um zu überleben!}
{143}{}{Habe ich nicht? Hm, vielleicht habe ich mich geirrt. Tut mir leid.}
{144}{}{[Er flüstert vor sich hin] Chris lebt? Nein ... Nein, das kann nicht sein ...}
{145}{}{Doch, und er lebt. Was hast du jetzt vor?}

{146}{}{Was ich tun soll? Ha-ha ... [er grinst nervös] ... Was bleibt mir anderes übrig? Es gibt jetzt nur eine Möglichkeit. Ha-ha!}
{147}{}{Okay, das ist eine Idee. Aber was wäre, wenn – hör mir einfach zu – du ihn *nicht* umbringst?}
{148}{}{Du meinst, ihn umzubringen? Nun, ich denke, du kannst dir denken, wo er ist. Viel Glück.}

{149}{}{Es ist mir scheißegal, was du denkst. Das ist nicht dein Problem, nicht deine Familie, nicht dein Leben. Du hast kein Recht, mir zu sagen, was ich tun soll!}
{150}{}{Denk, was du willst. Das wird dir nicht viel nützen, solange du nicht weißt, wo er ist.}
{151}{}{Hm ... Du hast recht. Okay, er ist in der Kanalisation. Viel Glück.}

{152}{}{Ach, ich verstehe. Nichts ist umsonst, was? Na schön, wie du willst. Ich geb dir 300 Mäuse, wenn du mir zeigst, wo dieser Bastard haust.}
{153}{}{Hier geht es um das Leben eines Mannes! Es ist weit mehr wert als dein jämmerliches Geld.}
{154}{}{Endlich redest du vernünftig. Oder von Cents, he-he. Gib mir das Geld, dann zeige ich dir, wo er wohnt ...}

{155}{}{Wenn du bezahlst, zeige ich dir, wo Chris jetzt ist.}

{156}{}{Zeigst du mir jetzt endlich, wo er wohnt? Ich muss ihn umbringen, bevor er meine Familie zerstört!}
{157}{}{Bezahl mich, dann zeige ich es dir.}
{158}{}{Na gut, komm mit. Ich will das sehen.}
{159}{}{Nö, ich verrate es nicht. Ich wollte nur sehen, wie du wieder wütend und hilflos wirst.}

#Æåíñêèå ðåïëèêè
{1143}{}{Habe ich nicht? Hm, vielleicht habe ich mich geirrt. Tut mir leid.}
{1156}{}{Zeigst du mir jetzt endlich, wo er wohnt? Ich muss ihn umbringen, bevor er meine Familie zerstört!}
{1159}{}{Nö, ich verrate es nicht. Ich wollte nur sehen, wie du wieder wütend und hilflos wirst.}