{100}{}{Du siehst Mrs. Clover.}
{101}{}{Du siehst Mrs. Clover. Sie ist noch nicht wirklich alt, aber sie fängt schon an, „zu vertrocknen“.}

#First talk
{110}{}{Du schon wieder!? Lass mich in Ruhe! Ich habe dir alles gegeben, was ich hatte! Wenn du noch mal herkommst, zeige ich dir, wozu diese alte Frau fähig ist!}
{111}{}{Ich glaube, du verwechselst mich mit jemand anderem.}
{112}{}{Halt's Maul, Alte! Dein Gejammer ist mir scheißegal.}

{113}{}{Oh ... Verzeihung! Ich dachte, Sie wären von der Spielbank. Diese Türsteher sind so herzlos, dass sie keine Angst haben, jemanden wie mich mit Gewalt zu behandeln!}
{114}{}{Diese Türsteher? Was ist los?}
{115}{}{Was ist passiert?}
{116}{}{Das interessiert mich alles nicht. Ich glaube, ich gehe jetzt.}

{117}{}{Du ... Ich dachte, die Türsteher wären wieder da.}
{118}{}{Ich bin so froh, ein freundliches Gesicht zu sehen ...}

#Receiving quest
{119}{}{Mich hat das Unglück getroffen. Mein Mann ist gestorben, und dann stellte sich heraus, dass er bei der Spielbank Schulden hatte. Jetzt werde ich entweder vor die Tür gesetzt oder in die Sklaverei verkauft.}
{120}{}{Entschuldigung, aber wer sind Sie?}
{121}{}{Wenn es die Schulden deines Mannes sind, warum wirst du dafür bestraft?}
{122}{}{Wie ist dein Mann gestorben?}
{123}{}{Wie viel schuldet dein Mann?}
{124}{}{Und niemand hat sich für dich eingesetzt?}
{125}{}{Ich würde dir gern bei diesen Schulden helfen.}
{126}{}{Das geht mich nichts an. Ich denke, ich gehe jetzt.}

{127}{}{Erzähl mir noch einmal, was passiert ist.}
{128}{}{Schön. Ich muss jetzt gehen.}
{129}{}{Auf Wiedersehen.}

{130}{}{Frau Clover, wenn Sie es unbedingt wissen wollen: Ich arbeite in der Küche eines Restaurants hier in der Gegend.}
{131}{}{Die Türsteher scheren sich nicht darum. Sie wollen nur ihr Geld. Da mein Mann tot ist, wollen sie es unbedingt von mir bekommen. So läuft die Welt.}
{132}{}{Straßenkinder haben ihn überfallen, als er betrunken war. Für sie muss er leichte Beute gewesen sein.}
{133}{}{Ich muss noch tausend bezahlen. Selbst wenn ich keine Miete zahlen müsste, würde es ein paar Wochen dauern, so viel zusammenzubekommen. Und so, wie es gerade läuft, glaube ich nicht, dass ich so viel Zeit habe.}
{134}{}{Solange ich hier bin, lässt Mr. Wright nicht zu, dass mir etwas passiert. Ich bin eine seiner zuverlässigsten Mieterinnen. Aber ich bezweifle, dass es so weitergeht. Wegen meiner Miete wird er sich nicht mit dem Casino anlegen. Er wird mich einfach rauswerfen und das Zimmer jemand anderem geben. Und wenn es so weit ist ... bin ich leichte Beute für die Türsteher. Ich glaube, sie werden mich in die Sklaverei verkaufen.}
{135}{}{Du willst helfen? Das ist wunderbar! Aber ich habe nichts, womit ich dich bezahlen könnte.}
{136}{}{Einmalige Zahlungen sind in Reno nicht besonders aussichtsreich. Ich hoffe, dass meine Hilfe eine langfristige Investition sein wird.}
{137}{}{Warum verschwende ich dann meine Zeit hier? Ich gehe.}
{138}{}{Ich muss mehr über das Problem wissen, bevor wir weitermachen.}
{139}{}{Verstanden. Na schön, genug von diesem traurigen Gerede – ich muss jetzt gehen.}
{140}{}{Danke für deine Ehrlichkeit, mehr kann ich nicht erwarten. Aber hör zu – mein Haus gehört Mr. Wright, und ich arbeite im Hotel "Silver Legacy". Vielleicht verbessert es deinen Ruf in der Gegend, wenn du mir hilfst? Wie dem auch sei, deine Hilfe ist alles, was ich jetzt noch habe. Sprich mit dem Empfangschef im "El Dorado" – er hat alle Geschäftsbücher.}
{141}{}{Ich spreche mit dem Verwalter.}

#Handing in the quest
{150}{}{Schön, dich zu sehen.}
{151}{}{Hier ist das Geschäftsbuch des Verwalters. Du schuldest ihnen jetzt nichts mehr.}
{152}{}{Auf Wiedersehen.}
{153}{}{Du hast es geschafft!? Unglaublich! Ich weiß gar nicht, wie ich dir danken soll. Sei dir nur sicher, dass die anderen Bewohner dieser Slums das nicht übersehen werden. Danke. Hier, nimm wenigstens das. Etwas zu essen für unterwegs. Ein besonderes Rezept, das sonst niemand kennt!}
{154}{}{Danke. Und auf Wiedersehen.}
{155}{}{Apropos, dein Mann war ein ziemlich guter Spieler. Wie konnte jemand wie er so viel Geld verlieren?}
{156}{}{Das kann ich dir schon sagen, oder? Diese hinterhältigen Mistkerle im Casino betrügen mit gezinkten Würfeln. Das Haus gewinnt immer, stimmt's? Er wusste es, aber versuchte sein Glück trotzdem immer wieder. Er dachte, er könnte ihr System schlagen und Glück haben ... [sie seufzt] Hat er aber nicht.}
{157}{}{Ja, so funktioniert Glücksspiel nun mal. Also, bis dann, Mrs. Clover.}

#Questions about other quests
{160}{}{Ich suche Arbeiter von Uranium City. Weißt du etwas darüber?}
{161}{}{Ja, natürlich. Gerüchte verbreiten sich hier schnell. Carl ist mein Nachbar. Michaels Leute haben ihn auf die Straße gesetzt, und Joseph wurde in die Sklaverei verkauft. Zu sehen, wie ein Mann von so hohem Ansehen plötzlich alles verliert ... Das ist beängstigend.}
{162}{}{Weißt du etwas über Ted Bundy?}
{163}{}{Nein. Wer ist das? Wenn er schon hier gelebt hat, bevor ich eingezogen bin, wissen vielleicht meine Nachbarn etwas. Sie sind schon viel länger hier als ich.}
{164}{}{Was kannst du mir über Harding erzählen?}
{165}{}{Ein ruhiger Kerl. Ein bisschen langsam, schätze ich. Deshalb wird er ständig gedemütigt. Einerseits tut er mir leid. Andererseits ist er selbst schuld, dass er seinen Platz in der Gesellschaft nicht findet. Wenn du mich fragst, hat er in seinem Leben einfach nicht genug Aufmerksamkeit bekommen. Besonders von Mädchen. [sie zwinkert] Du weißt, was ich meine.}
{166}{}{Was weißt du über die vermissten Schürfer, Mark und Robert?}
{167}{}{Davon habe ich gehört. Beide sind einfach verschwunden. Kein Wunder, schließlich ist es nicht gerade der sicherste Job, mit diesen Metalldetektoren durch die Ruinen zu laufen ... Ich erinnere mich, dass Mark vorbeikam. Ich sah ihn spät in der Nacht durch das Fenster. Aber ich habe keine Ahnung, was er hier wollte.}
{168}{}{Noch eine Frage.}
{169}{}{Das wollte ich wissen.}

#??????? ???????
{1136}{}{Habe ich irgendwas von Bezahlung gesagt? Ich will mich um diese Sache kümmern, weil das nicht fair ist!}
