{100}{}{Du siehst einen Stadtbewohner.}
{101}{}{Du siehst einen gewöhnlichen Bewohner dieses Slums.}

{109}{}{Äh, hallo. Wir freuen uns natürlich über Besuch, aber ...}
{110}{}{Äh, hallo. Wir freuen uns ganz sicher über Besuch ... anders als unsere Nachbarn ...}
{111}{}{Ja, deine Nachbarn sind nicht sehr gesprächig.}
{112}{}{Auf Wiedersehen.}
{113}{}{Das sind sie nicht. Aber sie waren nicht immer so. Seit Mark verschwunden ist, warten sie auf die Konsequenzen.}
{114}{}{Äh, Konsequenzen?}
{115}{}{Mr. Wright mag keine Leute, die ihn enttäuschen. Und Mark hat ihn enttäuscht. Jetzt muss jemand dafür bezahlen, verstehst du? Die alten Knacker tun mir leid, aber ihre Tage sind gezählt.}
{116}{}{Weißt du, was mit Mark passiert ist?}
{117}{}{Nun ... sagen wir einfach, ich habe neulich Abend etwas mitbekommen, aber ich kann mich kaum noch daran erinnern. Ich bin sicher, irgendetwas könnte mir auf die Sprünge helfen ... Wenn du verstehst, was ich meine.}
{118}{}{Natürlich. Würden hundert Bucks für die Information reichen?}
{119}{}{Weißt du, wer ich bin? Wer mein Boss ist? Das willst du gar nicht wissen, das kann ich dir sagen. Normalerweise bekommt er Informationen viel schneller aus den Leuten heraus als ich.}
{120}{}{Ich kenne einen Trick mit deinen Fingern, der deinem Gedächtnis auf die Sprünge helfen könnte. Soll ich ihn dir zeigen?}
{121}{}{Hundert ... oh ja, klar ...}
{122}{}{Hier ist das Geld.}
{123}{}{Oh, vielen Dank, Sir. [he sticks the money into his pocket] Gut, dass du uns besuchen gekommen bist.}
{124}{}{Also, erzähl mir alles.}
{125}{}{Es war spät in der Nacht. Mark kam nach Hause, völlig erschöpft und voller Straßenstaub. Er hatte einen heftigen Streit mit seiner Familie wegen irgendetwas, wir konnten sie sogar durch die Wand hören ... Sie wollten, dass Mark irgendwo nach Norden aus der Stadt verschwindet. Und genau das hat der verdammte Kerl getan! Hat seine Familie im Stich gelassen, dieser gottverdammte Feigling! Nur weil bei einem Auftrag von Mr. Wright etwas schiefgelaufen war und er einfach nicht zu Ende bringen konnte, was er angefangen hatte. Tja, Pech gehabt.}
{126}{}{Diese Information könnte nützlich sein. Du hältst den Mund über unser Gespräch, und ich gehe ein bisschen recherchieren.}
{127}{}{Sieht aus, als hätte Mark die Stadt verlassen. Er war auf dem Weg nach Norden.}
{128}{}{Ach, verstehe. Äh, ich helfe dir und deinem Boss gern ... wobei auch immer ich kann. Äh, kein Problem.}
{129}{}{W-Warte, lass dir Zeit ... Ich helfe, äh, immer gern jedem, dem ich begegne.}
{130}{}{Sei nicht lächerlich. In diesem Slum gibt es jemanden, der nicht zulässt, dass Fremde uns etwas antun. Ich spreche von Mr. Wright. Er will uns in der Tasche haben, also behältst du deine Tricks besser für dich.}
{131}{}{Diesmal hast du Glück.}

#Æåíñêèå ğåïëèêè
{1123}{}{Oh, vielen Dank, gnädige Frau. [er steckt das Geld in seine Tasche] Gut, dass Sie gekommen sind, um uns zu besuchen.}