{100}{}{Du siehst Patrick.}
{101}{}{Du siehst einen jungen Mann mit einem niedlichen, altmodischen Bart.}

#Ïåğâûé ğàçãîâîğ
{110}{}{[Der junge Mann lächelt dich an, doch in seinen Augen liegt Trauer] Willkommen, Wanderer. Mein Name ist Patrick. Darf ich dir ein paar Fragen stellen?}
{111}{}{Das kommt auf die Fragen an.}
{112}{}{Klar, ich habe nichts zu verbergen.}
{113}{}{Auf keinen Fall, hier stelle ich die Fragen!}

{114}{}{Nein, nein. Ich bestehe nicht darauf. Wenn du nicht reden willst, können wir friedlich getrennte Wege gehen. Aber deine Meinung ist mir wichtig, ebenso wie die der Leute, die hier leben.}
{115}{}{Aber ich komme nicht von hier ...}
{116}{}{Na gut. Geh und stell deine Fragen.}
{117}{}{Ich möchte nicht, dass du mich um etwas bittest.}

{118}{}{Das spielt keine Rolle. Wir wandeln alle auf demselben Land.}
{119}{}{Trotzdem. Die Entscheidung liegt bei dir.}
{120}{}{Na schön, dann.}

###########################################################################
#
#                  TEST
#
###########################################################################

{122}{}{Deine Worte machen Mut. Sag mir, glaubst du an Gott?}
{123}{}{Ich glaube nur an den glatten Lauf meiner Waffe.}
{124}{}{Ja, ich glaube an Ihn!}
{125}{}{Nein, das tue ich nicht. Einfach nicht.}
{126}{}{Ist das dein Ernst? Du könntest genauso gut fragen, ob ich an den Weihnachtsmann glaube.}
{127}{}{Ich weiß nicht einmal, wer das ist.}

{128}{}{Was leitet dich bei deinen Entscheidungen? Gottes Wort, deine persönlichen Erfahrungen oder etwas anderes?}
{129}{}{Mein Pip-Boy 2009 leitet mich auf den Pfad der Logik und Vernunft.}
{130}{}{Ich glaube, dass wir ohne den Herrn blind in der Dunkelheit umherirren und nur Er uns den Weg weisen kann.}
{131}{}{Ich brauche niemandes Rat und Anweisungen, um wichtige Entscheidungen im Leben zu treffen.}
{132}{}{Ich lasse mich von einer Flasche Schnaps leiten, gemischt mit Stachelechsenspieß nach Hausfrauenart.}
{133}{}{Ich weiß nicht. Die Frage übersteigt meinen Horizont.}

{134}{}{Wärst du bereit, dein Leben zu opfern, um andere Menschen zu retten?}
{135}{}{Ich muss zuerst wissen, was das für Leute sind. Wenn sie es wert sind und es keinen anderen Ausweg gibt, dann ja.}
{136}{}{Ich möchte mein Leben dafür einsetzen, Menschen zu helfen. Ich bin bereit, mich zu opfern, um sie zu retten.}
{137}{}{Die meisten Menschen auf der Welt sind mein Opfer nicht wert.}
{138}{}{Ich kann meinen linken Stiefel opfern. Das wäre schwierig, aber ich kann es versuchen.}
{139}{}{Ich weiß nicht. Das könnte ich erst in dem Moment beantworten.}

{140}{}{Was wünschst du dir im Leben am meisten? Reichtum, Ruhm, Familie ... Oder vielleicht die Welt zu retten?}
{141}{}{Meine oberste Priorität ist immer, zu überleben. Alles andere kommt danach.}
{142}{}{Ich will jeden retten, den ich retten kann.}
{143}{}{Ich muss mir keine höheren Ziele fürs Leben ausdenken.}
{144}{}{Kann ich alles davon haben? Nein? Dann nehme ich wohl ... etwas mit Pep. Und Popcorn dazu.}
{145}{}{Die Entscheidung ist schwer.}

{146}{}{Was ist deiner Meinung nach die schlimmste aller menschlichen Untugenden?}
{147}{}{Gier.}
{148}{}{Stolz.}
{149}{}{Verrat.}
{150}{}{Die Nähe eines Bauchnabels.}
{151}{}{Na ja, sie sind alle auf ihre Art ziemlich schlimm.}

{154}{}{Wie kann ich dir helfen?}
{155}{}{Heute nichts.}
{156}{}{Du wolltest mir ein paar Fragen stellen, oder?}
{157}{}{Oh, ja. Wenn es dir nichts ausmacht.}
{158}{}{Gut. Fangen wir an.}
{159}{}{Ich habe es mir anders überlegt.}

{160}{}{[Er nickt zustimmend] Du kennst den Preis der Dinge. Du kennst den Weg, den du gehst. Aber nicht alles auf dieser Welt lässt sich beziffern. Mach dich auf ein Rätsel gefasst, das sich nicht lösen lässt.}
{161}{}{[Er nickt zustimmend] Du hast dein Leben deinen Mitmenschen gewidmet. Viele von ihnen werden dir diesen Gefallen nicht erwidern. Eines Tages könnte dich das umbringen ... oder dich retten.}
{162}{}{[Er nickt zustimmend] Du weißt, was du wert bist. Und wenn der richtige Zeitpunkt gekommen ist, wirst du der Welt zeigen, was du wert bist.}
{163}{}{[Er nickt zustimmend] Du glaubst an das Morgen. Und es wird kommen, mit oder ohne uns.}
{164}{}{[Er nickt zustimmend] Es ist schwer, sich im Voraus zu entscheiden, nicht wahr? Du ziehst es wohl vor, von Fall zu Fall zu entscheiden. Viele Menschen glauben, die Welt sei schwarz oder weiß, aber die Wahrheit ist, dass es keine Wahrheit gibt. Du kannst die richtige Antwort erst kennen, wenn du die Frage selbst gesehen hast.}
{165}{}{Entschuldige, falls das ermüdend war. Ich wollte nur wissen, was für ein Mensch du bist.}
{166}{}{Ugh, schon gut.}

###########################################################################
#
#                  Îáûäåííûå ğàçãîâîğû: î ñåáå, î êëóáå è ïğ
#
###########################################################################

#Î ñåáå
{170}{}{Ich würde gern mehr über dich erfahren. Magst du erzählen?}

{171}{}{Sicher. Ich heiße Patrick und komme aus Salt Lake City – einer großen Stadt weit im Osten. Unsere mormonische Gemeinschaft hat mich hierher geschickt, um das Wort Gottes zu verkünden. Es war nicht leicht, aber ich werde nicht aufgeben.}
{172}{}{So einen Overall habe ich schon einmal gesehen. Kommst du aus einem Vault?}
{173}{}{}
{174}{}{Warum hat deine Gemeinschaft dich ausgerechnet in diese gefährliche Stadt geschickt?}
{175}{}{Predigst du auch den Prostituierten unten?}
{176}{}{Was genau machst du hier?}
{177}{}{Klar.}
{178}{}{}
{179}{}{Noch eine Frage, bitte.}
{180}{}{Genug von dir und deiner Missionsarbeit. Wechseln wir das Thema.}
{181}{}{Richtig. Aber ich muss los.}

{182}{}{Nein, nein, ich wurde geboren, nachdem unser Volk den Schutzraum verlassen hatte. Am Stadtrand gibt es einen Vault, aber seit Jahren war niemand mehr dort. Dieser Overall ist ein ... Andenken an meinen Großvater. Er diente im Vault, aber als die Bomben fielen, weigerte er sich, sich vor Gottes Welt zu verstecken. Er sagte, er würde die grauen Wände und den geschlossenen Raum ohne einen einzigen Strahl von Gottes Licht nicht ertragen – oder könne es nicht. Das ist alles, was ich über ihn weiß – er war schon lange tot, bevor ich geboren wurde.}
{183}{}{}
{184}{}{Das ist unsere Tradition. Jeder von uns muss zwei Jahre lang das Wort Gottes verkünden. Ich hätte einen anderen Weg wählen oder es ganz ablehnen können, aber das habe ich nicht getan. Die Menschen hier brauchen Erlösung genauso sehr wie alle anderen.}
{185}{}{Gib den Menschen hier nicht die Schuld. Sie überleben auf die einzige Weise, die sie kennen. Deshalb bin ich hier – um ihnen die Augen zu öffnen. Du glaubst es vielleicht nicht, aber einige von ihnen haben sich bereits bekehrt.}
{186}{}{Oh, vieles. Neben Beten, Predigen und dem Sammeln alter Bücher bringe ich Kindern das Schreiben bei, leite eine anonyme Selbsthilfegruppe und helfe einfach jedem, dem ich helfen kann.}

#Ïîæåğ'âîâàíèå
{190}{}{Ich möchte deiner Sache 100 $ spenden.}
{191}{}{Das ist sehr großzügig von dir! Jeder Dollar hilft Menschen in Not und kann sogar jemandem das Leben retten. Ich danke dir von ganzem Herzen!}
{192}{}{Gern geschehen.}
{193}{}{Das reicht jetzt aber!}

###########################################################################
#
#                  Õàğäèíã
#
###########################################################################

{200}{}{Ich interessiere mich für deine Selbsthilfegruppe.}
{201}{}{Ich verstehe deine Neugier, aber du brauchst sie nicht, glaub mir. Diese Gruppe hilft Menschen, die sich nicht selbst helfen können. [he smiles] Ich weiß nicht viel über dich, aber ich kann dir sagen, dass du das genaue Gegenteil davon bist.}
{202}{}{Ist Harding in deiner Gruppe?}
{203}{}{Ich ... verstehe. Ich nehme an, wenn du es weißt, hat es keinen Sinn, es abzustreiten. Aber ich werde kein weiteres Wort darüber verlieren. Regel Nummer eins lautet: Was in der Gruppe geschieht, bleibt in der Gruppe. Das ist eine heikle Angelegenheit. Wenn wir das Vertrauen des anderen missbrauchen, bleibt vielen unserer Mitglieder nichts mehr.}
{204}{}{Können wir vielleicht über etwas anderes reden?}
{205}{}{Erzähl mir von diesen Gruppentreffen. Was versucht ihr zu erreichen?}
{206}{}{Tut mir leid, aber ich glaube nicht, dass du das verstehen würdest. Weißt du, was Psychiatrie ist?}
{207}{}{Lass mich raten – Gruppentherapie, stimmt's? Ihr sitzt im Kreis und wascht euch gegenseitig das Gehirn.}
{208}{}{Das ist ... nicht weit von der Wahrheit entfernt. Ich bin überrascht! Woher ...? Ich sollte mich wohl freuen, einen Kollegen vor mir zu haben. Medizinisches Wissen ist in dieser Stadt schwer zu finden. Wo hast du das gelernt?}
{209}{}{Lebenserfahrung, Patrick. Lebenserfahrung.}
{210}{}{Erstaunlich! Möge Gott dich segnen. Deine Gabe kann in der Ödnis Großes bewirken!}
{211}{}{Vielleicht. Aber was eure Selbsthilfegruppe angeht ...}

{212}{}{Natürlich. Ich bin jederzeit bereit, meine Erfahrungen mit einem Kollegen zu teilen.}
{213}{}{Wie viele Leute kommen zu dieser Selbsthilfegruppe?}
{214}{}{Nur ein paar. Selbst drei reichen für unsere Gruppentherapie. Manche kommen nur einmal und lassen sich nie wieder blicken. Im Moment haben wir etwa zehn feste Mitglieder.}
{215}{}{Noch eine Frage.}
{216}{}{Was ist mit diesen Leuten los?}
{217}{}{Diese Menschen kommen mit den Belastungen der Gesellschaft nicht zurecht. Die meisten leiden unter Angstzuständen oder ähnlichen Beschwerden, und die Gesellschaft nutzt sie aus. Das häufigste Bild in unserer Gruppe sind Kaninchen, die in einer Welt voller Wölfe leben.}

{218}{}{Wie versuchst du, Harding zu „heilen“?}
{219}{}{Ich versuche, ihm beizubringen, mit seinen Unsicherheiten umzugehen. Die Gesellschaft wird ihn nicht akzeptieren, also muss er lernen, sich selbst zu akzeptieren.}
{220}{}{War Harding schon immer so?}
{221}{}{Ich glaube, seit seiner Kindheit. Er will nicht darüber reden, aber ich vermute, dass seine Eltern ihn sexuell missbraucht haben. Ich weiß, dass er immer ein Außenseiter war und in Büchern Zuflucht gefunden hat. Das war seiner sozialen Entwicklung nicht gerade zuträglich.}
{222}{}{Wie hat Harding mit diesem Zustand überlebt?}
{223}{}{Er hält sich für den Abschaum der Gesellschaft und nimmt deshalb die niedrigsten Arbeiten an – brahmin bewachen, Toiletten putzen und solche Dinge. Jede Gemeinschaft, selbst Reno, braucht Leute, die so etwas erledigen.}

{224}{}{Ich bin mit deiner Wahl von Hardings Behandlung nicht einverstanden.}
{225}{}{Was meinst du?}
{226}{}{Du versuchst, seine Phobie zu unterdrücken, indem du es ihm als Außenseiter bequem machst. Aber ich denke, er braucht mehr Aufmerksamkeit und Gespräche.}
{227}{}{Das könnte gefährlich sein. Die Gesellschaft schikaniert ihn schon seit Langem – niemand weiß, was tief in seinem vernarbten Gewissen verborgen liegt. Ich wollte ihm Frieden geben, statt ihn noch mehr Stress auszusetzen.}
{228}{}{Wie wäre es mit Medikamenten?}
{229}{}{Ich denke noch darüber nach. Vorerst habe ich eine andere Frage.}

{230}{}{Ich habe in letzter Zeit darüber nachgedacht. Er braucht etwas, das seine Nerven beruhigt und seine Angst unterdrückt.}
{231}{}{Vor dem Krieg wurde ein Mittel gegen das Rauchen zur Unterdrückung von Angst eingesetzt. Vielleicht hilft ihm das.}
{232}{}{Ich denke immer noch, dass er mehr Selbstvertrauen im Umgang mit anderen entwickeln muss.}

{233}{}{Ich bin kein Experte, also vertraue ich auf dein Wissen und den Willen Gottes. Aber ich habe keine Chems. Die örtlichen Händler könnten helfen, verlangen aber zweifellos einen hohen Preis.}
{234}{}{Ich sehe, was ich tun kann.}
{235}{}{Ich bin kein Experte, also vertraue ich auf dein Wissen und den Willen Gottes. Wenn Harding seine Ängste überwinden soll, muss er sein sexuelles Trauma bewältigen ... Die Idee gefällt mir nicht, aber vielleicht können die Sexarbeiter in Reno dir helfen.}
{236}{}{Ich bin dagegen. Ich weiß nicht warum.}
{237}{}{Manchmal ist es sinnvoll, auf seinen Instinkt zu hören, aber in diesem Fall dürfen wir kein Risiko eingehen. Vergiss nicht: Es geht um das Seelenheil eines anderen Mannes.}
{238}{}{Ich denke darüber nach und melde mich wieder.}

###########################################################################
#
#                  Êâåñ'û
#
###########################################################################

#Î ñè'óàöèè â ãîğîäå
{240}{}{Was kannst du mir über die Lage in der Stadt erzählen?}
{241}{}{Während wir hier sprechen, lockt Satan die Menschen dieser Stadt immer tiefer in sein Spinnennetz des Bürgerkriegs.}
{242}{}{Was meinst du, warum können die Menschen hier nicht in Frieden leben?}
{243}{}{Das ist eine gute Frage. Der nördliche Teil meiner Heimat, Salt Lake City, wurde durch dreizehn Atomschläge zerstört. Es hat also viel Zeit und Mühe gekostet, ihn wieder bewohnbar zu machen. Doch Reno und seine Bewohner haben sich alle Errungenschaften der alten Welt bewahrt.}
{244}{}{Ironischerweise haben die Verwüstung von Salt Lake City starke Familien und Gemeinschaften hervorgebracht, weil die Menschen zusammenarbeiten mussten. Hier wurden die Menschen Opfer ihrer eigenen Selbstsucht.}
{245}{}{Jeder versuchte, den anderen etwas wegzunehmen, und kümmerte sich nur um sich selbst. Deshalb findest du hier keine klugen Ärzte, Lehrer oder andere solche Leute. Und darum hat diese Gesellschaft keine Zukunft. Die Menschen können nur noch um die Überbleibsel vergangener Jahre kämpfen.}
{246}{}{[Weiter]}

{247}{}{Wenn die örtlichen Gangs Krieg führen, welche wirst du unterstützen?}
{248}{}{Gangs? Es geht nicht nur um Gangs, mein Freund. Hinter ihnen stehen Leute mit eigenen politischen Ansichten und Ideen dazu, wie man die Stadt führen sollte. Sie wissen, dass sie sich selbst an diesem Ort nicht einfach nehmen können, was sie wollen. Die Ressourcen sind begrenzt, und wenn sie heute zu gierig sind, bleibt ihnen morgen nichts mehr. Darum entscheiden sich die Menschen für eine Seite – sie glauben, dass diese einen Plan für die Zukunft hat. Aber ich glaube nicht, dass eine von beiden auf dem richtigen Weg ist.}
{249}{}{Danke für die Erklärung.}

#Êâåñ' íà áîëüíîãî
{250}{}{Kann ich deiner Mission irgendwie helfen?}
{251}{}{Meinst du das ernst? Es erfuellt meine Seele mit Freude, dass jemand helfen möchte.}
{252}{}{Im Moment habe ich zwei Probleme. Itchie hat eine schwere Verletzung am Arm, und ich kann mein lang ersehntes Paket aus der Heimat nicht abholen.}
{253}{}{Im Moment ist Itchies Wunde das größte Problem. Ich kann nichts für ihn tun.}
{254}{}{Im Moment ist meine größte Sorge, dass ich mein lang ersehntes Paket aus der Heimat nicht abholen kann.}
{255}{}{Ich kümmere mich um ihn.}
{256}{}{Ich sehe nach deinem Paket.}
{257}{}{Aber nein, schon gut. Im Moment brauche ich nichts.}

{258}{}{Er durchwühlte gerade eine Muelltonne, als um ihn herum ein Feuergefecht ausbrach. Er wurde in den Arm geschossen, und die Wunde hat sich entzündet. Ich konnte ihm nur alle Schmerzmittel geben, die ich hatte. Wenn du Arzt bist, kannst du helfen?}
{259}{}{Ich helfe dir.}
{260}{}{Ich kann helfen, aber Medikamente kosten Geld.}
{261}{}{Ah, tut mir leid. Ich dachte, du würdest aus Nächstenliebe helfen und keine bezahlten Dienste anbieten. Mal sehen ... Ich habe nur 100 Dollar. Reicht das?}
{262}{}{Ich kümmere mich um den Patienten und komme dann zu dir zurück.}
{263}{}{Das ist sehr gut! Ich hoffe auf das Beste.}
{264}{}{Gute Nachrichten! Ich habe Itchies Verletzung behandelt.}
{265}{}{}
{266}{}{Das sind großartige Neuigkeiten! Das ist mein letztes Geld, aber ihm zu helfen, ist es wert.}
{267}{}{Nein, du brauchst das Geld dringender als ich.}
{268}{}{Gib es her.}
{269}{}{Das sind großartige Neuigkeiten! Danke für deine Güte. Möge der Herr dich segnen.}
{270}{}{Gern geschehen.}
{271}{}{Das sind großartige Neuigkeiten! Danke für deine Güte. Möge der Herr dich segnen.}
{272}{}{Hey, wer bezahlt mich denn? Das hat mich 100 Dollar gekostet!}
{273}{}{Oh, tut mir leid. Ich dachte, du würdest aus Nächstenliebe helfen und keine bezahlten Dienste anbieten. Na gut, ich habe noch 100 Dollar. Hoffentlich reicht das, denn mehr habe ich nicht.}
{274}{}{Gib es mir.}
{275}{}{Gern geschehen.}

#Êâåñ' íà ïîñûëêó
{280}{}{Jeden Monat schicken mir meine Brüder in Salt Lake City ein Paket über die Nevada Express, das eine Nachricht und Vorräte enthält. Diesmal ist der Kurier – ein Junge aus den Slums – nie angekommen. Der Mitarbeiter der Nevada Express sagte mir, dass sie es ihm gegeben hätten. Es gibt keinen Grund für sie, ihren Ruf wegen der Vorräte in dem Paket aufs Spiel zu setzen.}
{281}{}{[Weiter]}
{282}{}{Ich nehme an, die Vorräte sind weg. Ich mache den Leuten in den Slums keinen Vorwurf; angesichts ihrer Umstände kann ich nur hoffen, dass sie jemandem in Not zugutekamen. Aber die Nachricht ... Sie bedeutet mir viel. Bitte versuch, sie zu finden.}
{283}{}{Ich sehe, was ich tun kann.}

{284}{}{Wegen deiner Nachricht ...}
{285}{}{Hast du sie gefunden? Ich brauche sie wirklich.}
{286}{}{Hier, bitte.}
{287}{}{Wie hast du sie schon wieder verloren?}
{288}{}{Jeden Monat schicken mir meine Brüder in Salt Lake City ein Paket über die Nevada Express, das eine Nachricht und Vorräte enthält. Diesmal ist der Kurier – ein Junge aus den Slums – nie angekommen. Ich brauche nur die Nachricht. Sprich mit dem Mitarbeiter der Nevada Express oder dem Kurier.}
{289}{}{Du hast es wirklich geschafft! Das ist unglaublich! Ich fürchte, ich kann dich nicht bezahlen, aber ich danke dir von ganzem Herzen. Du kannst dir nicht vorstellen, wie wichtig diese Anweisungen für meine Arbeit hier sind.}
{290}{}{Was steht denn überhaupt in dieser Nachricht?}
{291}{}{Ich wünsche dir alles Gute. Viel Glück.}
{292}{}{Ja, tschüss.}
{293}{}{[Er liest die Nachricht] Hm. Die Gemeinschaft bietet mir an, nach Salt Lake City zurückzukehren. Aber das kann ich nicht! Die Menschen in Reno brauchen mich jetzt mehr denn je. Ich muss bleiben.}
{294}{}{Das ist sehr ehrenhaft von dir. Nun, viel Glück.}
{295}{}{Wenn du meinst. Für mich ist es Zeit weiterzuziehen. Leb wohl.}

#Êâåñ' íà êèíîïîêàç
{296}{}{Ja, ich hätte eine heikle Bitte. Die Nachricht, die du mir gebracht hast, enthielt einen alten Film auf Holodisk. Ich möchte nachts eine Filmvorführung für die Einheimischen organisieren, aber ich fürchte, Mr. Wright wird es mir nicht erlauben. Könntest du ihn davon überzeugen, eine Vorführung zu gestatten?}
{297}{}{Ich kümmere mich darum. Ich spreche mit Wright.}
{298}{}{Danke. Ich warte auf seine Antwort.}
{299}{}{Bis später.}
{300}{}{Ich würde gern zuerst mehr über den Film erfahren.}

{301}{}{Natürlich! Was möchtest du wissen?}
{302}{}{Ich muss mit dir über den Film sprechen.}
{303}{}{Was für ein Film ist das?}
{304}{}{Was ist daran so wichtig?}
{305}{}{Warum machst du dir so viele Sorgen um Wrights Meinung?}
{306}{}{Das war's.}
{307}{}{Es ist ein Vorkriegsfilm über die Gier und Laster der Menschheit. Die Hauptaussage ist, dass die Sünden der Welt ihre Zerstörung herbeigeführt haben ... Ich weiß, dass das vielen nichts bedeuten wird, aber wenn ich damit auch nur eine Seele retten kann, war es das wert. Die Mormonen nutzen den Film für diesen Zweck schon seit der Zeit vor dem Krieg, und Missionare wie ich zeigen ihn immer am Ende ihrer Mission. Soweit ich weiß, hat ihn noch niemand in Reno gesehen.}
{308}{}{Die Menschen in Reno wissen nichts über ihre Vergangenheit und haben keine Hoffnung für ihre Zukunft. Dieser Film könnte ihnen beides geben. Außerdem haben die meisten Einheimischen noch nie zuvor irgendeinen Film gesehen. Vielleicht hilft er ihnen, unseren Glauben besser zu verstehen und den Weg Gottes einzuschlagen.}
{309}{}{Ihm gehören die Slums und im Grunde auch die Menschen, die darin leben. Wenn Wright den Film nicht genehmigt, könnte er die Vorführung unterbinden oder noch drastischere Maßnahmen ergreifen. Ohne seine Erlaubnis geht es einfach nicht.}
{310}{}{Wright hat dir erlaubt, den Film zu zeigen, aber er sagte, dass er nicht für deine Sicherheit verantwortlich sein wird.}
{311}{}{Verstehe ... Ich verstehe. Ich hatte gehofft, wir würden seinen Schutz genießen, aber ich mache ihm keinen Vorwurf.}
{312}{}{Wäre das gefährlich? Warum sollte jemand eine Filmvorführung angreifen?}
{313}{}{Ich fürchte, manche Leute in der Stadt sind mit meinen Predigten nicht einverstanden. Sie könnten stören ... oder vielleicht sogar gewalttätig werden. Hör zu, vielleicht verlange ich zu viel, aber ... würdest du mir helfen?}
{314}{}{Ich mache mich bereit und sage dir Bescheid, wenn ich so weit bin.}
{315}{}{Um Wright musst du dir keine Sorgen mehr machen – er ist tot.}
{316}{}{Das sind traurige Nachrichten. Ich fürchte, was nun mit den Slums geschehen könnte, aber das bedeutet, dass wir jetzt nötiger sind als je zuvor. Es wird auch die Filmvorführung gefährlicher machen.}
{317}{}{Wir können den Film jetzt zeigen.}
{318}{}{Bist du sicher, dass du bereit bist? Wir müssen ihn außerhalb der Stadt zeigen und haben keine Zeit zurückzugehen, falls wir etwas vergessen. Nimm alles mit, was du brauchen könntest.}
{319}{}{Los geht's.}
{320}{}{Eigentlich hast du recht. Ich bin bald zurück.}

{321}{}{Schön, dich nach unserer großen Nacht wohlauf zu sehen.}
{322}{}{Du bist noch ganz! Wie war der Film?}
{323}{}{Alle waren völlig gebannt! Die Frauen weinten, die Männer freuten sich. Allerdings glaube ich, dass weniger der Film selbst dafür verantwortlich war als vielmehr die Gelegenheit, etwas zu genießen, das sie noch nie zuvor gesehen hatten. Hier gibt es so wenig Vergnügen, und noch weniger, bei denen keine gefährlichen Folgen drohen. Ich denke, sie werden noch lange darüber reden. Danke! Ohne dich wäre das alles nicht möglich gewesen!}
{324}{}{Ende gut, alles gut.}
{325}{}{Von nun an müssen diese Menschen den Weg Gottes selbst beschreiten. Noch einmal: Danke für alles. Ich hoffe, du wirst den Menschen hier auch weiterhin helfen ... Sie brauchen es.}
{326}{}{Viel Glück, Patrick.}
{327}{}{Du hast dem mormonischen Missionar geholfen. Das hat dein Karma und deinen Ruf in den Slums verbessert.}

#Êâåñ' Òîìïñîíà
{330}{}{Sag mal, du hast nicht zufällig ein Scharfschützengewehr?}
{331}{}{Ich?! Nein, ich bin ein friedliebender Mensch. Die einzige Waffe, die ich trage, dient meiner Selbstverteidigung.}
{332}{}{Wie erklärst du dann die Patronenhülse auf deinem Balkon? Sie scheint mit der Schießerei auf der Straße vor Kurzem zusammenzuhängen.}
{333}{}{Oh ... verstehe. Hör zu, an dem Tag bat eine Familie darum, hier zu bleiben. Sie sahen aus, als kämen sie von auswärts, und der Ehemann hatte einen seltsam aussehenden Aktenkoffer dabei. Ich hatte keine Ahnung, dass sie Attentäter waren! Glaubst du, Stryker hat sie angeheuert?}
{334}{}{Schwer zu sagen, aber deine Geschichte klingt überzeugend. Und du hast wirklich kein Gewehr. Danke für die Information.}

#Female character
{1110}{}{[Der junge Mann lächelt dich an, doch in seinen Augen liegt Trauer] Willkommen, Wanderer. Mein Name ist Patrick. Darf ich dir ein paar Fragen stellen?}
{1115}{}{Ich komme nicht von hier. Vielleicht kann ich deine Fragen nicht beantworten.}
{1134}{}{Wärst du bereit, dein Leben zu opfern, um andere Menschen zu retten?}
{1136}{}{Ich möchte mein Leben dafür einsetzen, Menschen zu helfen. Ich bin bereit, mich zu opfern, um sie zu retten.}
{1158}{}{Gut. Fangen wir an.}
{1159}{}{Ich habe es mir anders überlegt.}
{1160}{}{[Er nickt anerkennend.] Du kennst den Preis der Dinge. Du kennst deinen Weg. Aber nicht alles auf dieser Welt hat eine Zahl. Mach dich auf ein Rätsel gefasst, das sich nicht lösen lässt.}
{1208}{}{Das ist ... nicht weit von der Wahrheit entfernt. Ich bin überrascht! Ich schätze, ich sollte froh sein, eine Kollegin vor mir zu haben. Medizinisches Wissen ist in dieser Stadt schwer zu finden. Wo hast du das gelernt?}
{1210}{}{Erstaunlich! Möge Gott dich segnen. Deine Gabe kann in der Ödnis Großes bewirken!}
{1236}{}{Ich bin dagegen. Ich weiß nicht warum.}
{1266}{}{Das sind großartige Neuigkeiten! Das ist mein letztes Geld, aber ihm zu helfen, ist es wert.}
{1275}{}{Gern geschehen.}
{1314}{}{Ich mache mich bereit und sage dir Bescheid, wenn ich so weit bin.}
{1318}{}{Bist du sicher, dass du bereit bist? Wir müssen ihn außerhalb der Stadt zeigen und haben keine Zeit zurückzugehen, falls wir etwas vergessen. Nimm alles mit, was du brauchen könntest.}
{1320}{}{Eigentlich hast du recht. Ich bin bald zurück.}
