{100}{}{Du siehst Patrick.}
{101}{}{Du siehst Patrick. Er sieht wie immer ordentlich und sauber aus.}
{102}{}{Das Publikum flieht entsetzt auseinander!}
{103}{}{Pass auf sie auf, nicht auf mich.}
{104}{}{All die Mühe umsonst ...}
{105}{}{Danke für deine Hilfe.}

#On loading map
{110}{}{Die meisten Leute sind hier. Der Rest sollte auftauchen, sobald ich mit meiner Rede anfange.}
{111}{}{Verstanden. Was brauchst du von mir?}
{112}{}{Du wirst mein Leibwächter sein. Auch wenn das vielleicht etwas hochtrabend klingt ... Jedenfalls bist du für die Sicherheit zuständig. Zweifellos ist hier jemand ein Attentäter oder ein Demonstrant. Wir müssen dafür sorgen, dass alle die Vorstellung genießen können, ohne verletzt zu werden.}
{113}{}{Findest du nicht, dass du zu misstrauisch bist? Hier sieht niemand wie eine Bedrohung aus.}
{114}{}{Na gut. Geh deine Rede halten, ich behalte die Menge genau ...er im Auge.}
{115}{}{Na gut, ich halte die Augen offen. Vielleicht sogar zwei.}
{116}{}{Beten wir, dass alles nach Plan läuft.}

#Ðå÷ü
{200}{}{Ähm ... [rückt den Kragen zurecht]}
{201}{}{Also gut, fangen wir an ...}
{202}{}{Wir sind hier versammelt, geführt von Gottes Hand.}
{203}{}{Geleitet durch eine hilflose, dem Untergang geweihte Welt.}
{204}{}{Wir alle sind Opfer der Gier und Skrupellosigkeit unserer Vorfahren.}
{205}{}{Als der Mensch aus Mangel an Ressourcen zum Krieg griff ...}
{206}{}{... dem Großen Krieg.}
{207}{}{Seitdem hat sich nichts geändert. Die Menschen zerstören weiterhin die letzten Reste Menschlichkeit in sich.}
{208}{}{Sie vergessen, dass wir alle Brüder und Schwestern sind. Wir alle sind ... Gottes Kinder.}
{209}{}{Dieser Film wird uns zeigen, wie alles dazu kam, damit wir die Fehler der Vergangenheit vermeiden.}
{210}{}{Na dann, legen wir los!}