{100}{}{Du siehst einen Zuschauer.}
{101}{}{Du siehst einen Zuschauer. Er wartet auf die Vorstellung.}
{102}{}{Die Zuschauer fliehen in Panik!}
{103}{}{Was zum Teufel?! Scheiße, besser, ich verschwinde von hier ...}
{104}{}{Die Lage ist jetzt sicher.}
{105}{}{Wag es ja nicht, mich anzufassen!}
{106}{}{Ach, verdammt ... *hicks* Ich hab schon wieder zu viel getrunken ... Vielleicht sollte ich mich *hicks* ein paar Minuten hinlegen ...}
{107}{}{Uuh ... Ich hätte den Drink nicht nehmen sollen ... Ich muss mich hinlegen.}

{108}{}{Ja, also ... die Gerechtigkeit möge siegen und so weiter.}
{109}{}{Du hast den Zuschauer betrunken gemacht.}

{110}{}{Äh, hi.}

{111}{}{[Der Mann zieht seine Baseballkappe tiefer ins Gesicht und versucht, Blickkontakt zu vermeiden.]}
{112}{}{Wohin gehst du?}
{113}{}{Viel Spaß bei der Vorstellung.}
{114}{}{Geht dich nichts an.}
{115}{}{Doch, das geht mich was an. Ich bin Patricks Leibwächter. Wenn du ihm etwas zu sagen hast, sag es mir.}
{116}{}{Oh, ich hab ihm was zu sagen, Arschloch, nur nicht, wenn du dabei bist. Jetzt geh mir verdammt noch mal aus dem Weg.}
{117}{}{Was hast du gerade zu mir gesagt?! Du solltest besser verschwinden, bevor ich wütend werde. Du willst nicht erleben, wie ich bin, wenn ich wütend bin.}
{118}{}{Diesmal lasse ich das mit dem „Arschloch“ durchgehen, Patrick zuliebe. Jetzt geh auf deinen Platz. Oder verschwinde.}
{119}{}{Weißt du was? Ist mir egal. Mach, was du willst.}
{120}{}{Ach ja, *Arschloch*? Was willst du tun, dich hinknien und mich anbeten? [Er zieht seine Jacke zur Seite und gibt eine Pistole preis] Ja, genau. Du und dein Kumpel habt in Reno nichts verloren. Und jetzt geh mir aus dem Weg, bevor ich dir in den Hals greife, deine Eingeweide herausreiße und dich damit aufhänge.}
{121}{}{Jetzt nehme ich dir die Knarre ab und marschiere mit dir in die Wüste. Jedes Mal, wenn du langsamer wirst, jage ich dir eine Kugel in irgendeinen Körperteil, wo sie dich nicht umbringt. Gerade so, dass es genug wehtut, damit du wieder weitergehst. Du wirst weiter laufen als je zuvor in deinem Leben, denn wenn du endlich stehen bleibst und dich *nicht mehr* bewegen kannst, dann schieße ich dir eine Kugel in den Kopf und gehe zurück. Hier wird nicht mal jemand merken, dass wir weg sind. Ich wette sogar, in der ganzen Stadt wird dich keiner vermissen. Was sagst du?}
{122}{}{Du machst große Ansagen. Ich lasse Taten sprechen. Letzte Warnung - das ist deine Chance, zu verschwinden.}
{123}{}{[Er erstarrt, die Augen weit aufgerissen, dann schließt er seine Jacke] Hoffen wir für dich, dass ich dich nie in einer dunklen Gasse erwische, Arschloch! [Er zeigt dir den Mittelfinger und wendet sich ab]}
{124}{}{[Angreifen.]}
{125}{}{[Lass ihn gehen.]}
{126}{}{Er ist zu weit weg.}

#Æåíñêèå ğåïëèêè
{1116}{}{Oh, ich habe ihm schon etwas zu sagen, Schlampe, nur nicht, solange du dabei bist. Und jetzt geh mir verdammt noch mal aus dem Weg.}
{1118}{}{Das mit der „Schlampe“ lasse ich dir dieses eine Mal durchgehen, Patrick zuliebe. Jetzt geh auf deinen Platz. Oder verschwinde.}
{1120}{}{Ach ja, *Schlampe*? Was willst du tun, dich hinknien und mich anbeten? [Er zieht seine Jacke zur Seite und gibt eine Pistole preis] Ja, genau. Du und dein Kumpel habt in Reno nichts verloren. Und jetzt geh mir aus dem Weg, bevor ich dir in den Hals greife, deine Eingeweide herausreiße und dich damit aufhänge.}
{1123}{}{[Er zögert kurz, beobachtet dich und tritt dann zurück] Hoffen wir für dich, dass ich dich nie in einer dunklen Gasse erwische, Schlampe! [Er zeigt dir den Mittelfinger und wendet sich ab]}