{100}{}{Du siehst einen Zuschauer.}
{101}{}{Du siehst ein aufgeregtes Mitglied des Publikums.}

{102}{}{Die Zuschauer fliehen in Panik!}
{103}{}{Das ist der schlimmste Tag meines Lebens ... seit einem Jahr.}

#Ğåïëèêà äëÿ äåòåé
{105}{}{Kannst du es glauben? Ein echter Film, wie in den alten Zeiten!}

#Ğåïëèêà äëÿ âçğîñëûõ
{110}{}{Bist du auch wegen des Films hier?}
{111}{}{Wir haben die ganze Familie mitgebracht. Hoffentlich lohnt es sich!}
{112}{}{Ich habe noch nie einen Film gesehen. Vielleicht werde ich nie wieder einen sehen!}
{113}{}{Von hier aus haben wir einen wunderschönen Blick auf den Sonnenuntergang ...}
{114}{}{Dieser Patrick ist unglaublich!}
{115}{}{Heutzutage bekommen nicht viele Leute diese Gelegenheit ...}
{116}{}{Ich frage mich, ob es ein Horrorfilm ist.}

#Ïîäğîáíûå îïèñàíèÿ
{120}{}{Du siehst einen fliehenden Zuschauer. Du glaubst nicht, dass diese Vorstellung gute Kritiken bekommen wird.}
{121}{}{Du siehst einen Zuschauer, der vor Vorfreude zittert.}
{122}{}{Du siehst ein glückliches Paar. Hier müssen sie ihre Beziehung nicht verbergen.}
{123}{}{Du siehst einen glücklichen Vater. Er unterhält seine Kinder, damit ihnen nicht langweilig wird.}
{124}{}{Du siehst einen älteren Mann. Er spricht mit seinem Sohn über die alten Zeiten.}
{125}{}{Du siehst ein Kind. Es hört seinem Vater aufmerksam zu.}
{126}{}{Du siehst einen Mann in zerlumpter Kleidung. Er plaudert mit seiner Frau, als wäre er im siebten Himmel.}
{127}{}{Du siehst eine Frau in abgetragenen Kleidern. Sie entspannt sich und lacht mit ihrem Mann.}