{100}{}{Du siehst einen obdachlosen Jungen.}
{101}{}{Du siehst ein armes, schmutziges Kind, das dich beobachtet.}
{102}{}{Hey, Mister, ich weiß, wie ich Ihnen helfen kann!}
{103}{}{Hey, Miss, ich weiß, wie ich Ihnen helfen kann!}

####################################################################
#              Ïåğâûé ğàçãîâîğ
####################################################################

{110}{}{Hallo, Mister! Willkommen im großartigen Reno!}

{111}{}{Danke, Kleiner! Ich hatte keine Ahnung, dass Reno so eine freundliche Stadt ist!}
{112}{}{Verschwinde, du Bettler!}
{113}{}{Warum bist du so freundlich? Du willst doch etwas, oder?}
{114}{}{Ja, hallo. Und tschüss.}

{115}{}{[Der Junge blinzelt nicht einmal] Na gut, Mister. Ich werde Sie nicht mehr belästigen.}
{116}{}{Gut. Also, was willst du?}
{117}{}{Sorg dafür, dass du das nicht tust. Ich will nicht mehr mit dir reden.}

{118}{}{Oh nein, Mister! Ich helfe nur den Neuankömmlingen im großartigen Reno, damit sie sich nicht verlaufen.}
{119}{}{Hmm. Eine seltsame Art, seinen Lebensunterhalt zu verdienen ... }
{120}{}{Ich dachte, du wärst ein Bettler.}
{121}{}{Dann brauche ich dich nicht.}

{122}{}{Ich bettle nicht einfach nur um Geld! Ich sorge dafür, dass jeder deiner Dollar gut angelegt ist!}
{123}{}{Hmm, hier sind 5 Dollar. Was kannst du mir über deine Stadt erzählen?}
{124}{}{Kennst du irgendwelche Geheimnisse?}
{125}{}{Sag mal, hast du einen Mann namens Balder gesehen?}
{126}{}{Hmm ... Du bist klein genug, um durch das Fenster zu kommen ... }
{127}{}{}
{128}{}{Na gut, mal sehen, ob du mir helfen kannst.}
{129}{}{Ich schätze, ich brauche nichts.}

{130}{}{Oh nein, für Neuankömmlinge kann es sehr gefährlich sein! Für ein bisschen Geld kann ich dir sagen, wie du heil davonkommst!}
{131}{}{Das war sarkastisch gemeint, du verdammtes Stück Scheiße. Such dir woanders jemanden, der dir was zusteckt.}
{132}{}{Ach, du bist also ein Bettler, was?}
{133}{}{Wie du meinst. Was machst du hier?}
{134}{}{Trotzdem kannst du mir nicht helfen. Ich gehe.}

{135}{}{Wie du meinst, Mister. Ich lasse dich in Ruhe.}
{136}{}{Ich helfe Neuankömmlingen im großartigen Reno, damit sie sich nicht verlaufen und keinen Ärger bekommen.}

{137}{}{[Der Junge schenkt dir ein übertriebenes Lächeln] Hallo, Mister! Wie kann ich Ihnen helfen?!}
{138}{}{Du kennst dich in der Stadt gut genug aus, oder?}
{139}{}{Hmm ... Du bist klein genug, um durch das Fenster zu kommen ... }
{140}{}{Im Moment nichts.}

{141}{}{Deshalb bin ich ja hier! Ich helfe immer gern! ... für nur ein *bisschen* Geld!}
{142}{}{[Er legt den Kopf schief] Hmm? Wie meinst du das?}
{143}{}{Ich suche einen Mann, den sie Balder Maxson nennen. Er hat Dehnungsstreifen am Hals. Hast du ihn gesehen?}
{144}{}{Weißt du, wer die Wände des Hotels streicht?}

{145}{}{Stehst du oft hier?}
{146}{}{Ja, ich habe mein halbes Leben hier verbracht!}
{147}{}{Na gut, reden wir über etwas anderes.}

####################################################################
#              Ïîêóïêà èíôîğìàöèè î òàéíèêå:
####################################################################

{148}{}{Ich versuche, in ein, äh, „verlassenes“ Zimmer zu kommen. Willst du mir helfen?}
{149}{}{Hmm ... Na ja, ich habe tatsächlich eins. Was zahlst du dafür?}
{150}{}{Ich gebe dir 20 Mäuse.}
{151}{}{Ich gebe dir 10 Mäuse.}
{152}{}{Ich gebe dir 5 Mäuse.}
{153}{}{Schon gut, reden wir über etwas anderes.}

{154}{}{Nee, damit verdienst du viel mehr Geld ... Wenn du dafür bezahlst, meine ich.}
{155}{}{Was, wenn ich einfach anfange, dir die Finger zu brechen?}
{156}{}{Äh ... Aber das würdest du doch nicht tun. Oder?}
{157}{}{Und ob! Ich bin der leibhaftige Teufel! Ich liebe es, kleinen Jungen die Finger zu brechen!}
{158}{}{Das glaube ich dir nicht! Niemals würdest du so was tun! Nicht wegen eines kleinen Geheimnisses!}
{159}{}{[Einen Finger packen und kräftig nach hinten biegen] Letzte Chance, Kleiner!}
{160}{}{Na gut, du hast recht. Aber ich will das Geheimnis trotzdem wissen.}
{161}{}{Warte, nein! Ich sag's dir! Tu mir bitte nicht weh!}
{162}{}{Raus mit der Sprache, Göre! Was ist das Geheimnis?}
{163}{}{Vergiss es, ich tu dir nichts. Also, verrätst du mir das Geheimnis?}
{164}{}{Aaaah! Lass mich los! Lass mich los, dann sag ich's dir!}
{165}{}{Erst sagst du es mir!}
{166}{}{[Loslassen] Das war eine Warnung. Beim nächsten Mal höre ich nicht auf.}
{167}{}{[Die Karawanenhändler beginnen vom Parkplatz aus, dich anzuschreien] Hey! Lass den Jungen in Ruhe, Arschloch!}
{168}{}{Du hast Glück gehabt, Kleiner ... Diesmal. Wir sehen uns später wieder.}
{169}{}{[Dem Jungen direkt in die Augen sehen und stärker auf den Finger drücken]}
{170}{}{[Er starrt dich finster und schweigend an]}
{171}{}{[Du spürst, wie der Finger in deinem Griff verrutscht, als die Knochen aus dem Gelenk springen] AAAAAAH!!! DAS TUT WEH!!! AAAAAAH!!!}
{172}{}{Hoppla ...}
{173}{}{Nein, bitte nicht! Ich sag's!}
{174}{}{Ich höre!}

{175}{}{Puh ... [er versucht, wieder zu Atem zu kommen] Ich wollte sagen, dass ich ein paar Karawanenhändler über einen Dieb reden hörte, der ihnen ein paar Sachen gestohlen und verstecken konnte, bevor sie ihn erwischten. Ich weiß nicht, wo er sie versteckt hat, aber es muss in der Nähe des Parkplatzes sein!}
{176}{}{War's das? Denn wenn du mich angelogen hast ... }
{177}{}{Es stimmt! Sie sagten, es war dunkel, und sie sind bei vielen Gebäuden in der Nähe herumgelaufen. Deshalb wissen sie nicht, wo er sie versteckt hat. Der Dieb hat zu viel Angst, um zurückzukommen, also müssen sie noch dort versteckt sein ... }
{178}{}{Mal sehen.}
{179}{}{Du hast von einem versteckten Vorrat in der Nähe des Parkplatzes erfahren, ohne dafür zu bezahlen, indem du einem Kind mit Gewalt gedroht hast. Darauf kannst du wirklich stolz sein.}
{180}{}{Ich habe einen der Karawanenhändler sagen hören, dass ein Dieb ihnen ein paar Sachen gestohlen und versteckt hat, bevor sie ihn erwischten. Ich weiß nicht, wo er sie versteckt hat, aber es muss in der Nähe des Parkplatzes sein!}

{181}{}{Okay, in Ordnung.}
{182}{}{Reden wir über etwas anderes.}
{183}{}{Hier ist das Geld.}

{184}{}{Ich gebe dir 15 Dollar.}
{185}{}{Du hast von einem versteckten Vorrat in der Nähe des Parkplatzes erfahren.}
{186}{}{[Er steckt das Geld schnell irgendwo in seinen Lumpen ein.] Ich habe einen der Karawanenhändler sagen hören, dass ein Dieb ihnen ein paar Sachen gestohlen und versteckt hat, bevor sie ihn erwischten. Ich weiß nicht, wo er sie versteckt hat, aber es muss in der Nähe des Parkplatzes sein!}

####################################################################
#                    Î ãîğîäå
####################################################################

{187}{}{Ich erzähle dir, was ich weiß, aber ich brauche das Geld im Voraus.}
{188}{}{Okay, hier sind 5 Dollar.}
{189}{}{Jetzt nicht.}

{190}{}{Was willst du wissen?}
{191}{}{Wo kann ich Vorräte kaufen und verkaufen?}
{192}{}{Wie kann ich hier etwas Geld verdienen?}
{193}{}{Welche Unterhaltung gibt es in dieser Stadt?}
{194}{}{Gibt es hier Orte, die ich meiden sollte?}
{195}{}{Wer hat hier das Sagen?}
{196}{}{Ich suche einen Biker namens Jay Kukish.}
{197}{}{}
{198}{}{}
{199}{}{[Weiter.]}
{200}{}{Du kannst im Karawanenladen auf der anderen Seite des Parkplatzes Sachen kaufen. Zwei Restaurants sind ganz in der Nähe. Das Restaurant von Silver Legacy ist gleich dort drüben und hat gutes Essen, aber es ist teuer. Das Cotton Club ist neben dem El Dorado – das Essen dort ist schrecklich, aber 15 Prozent billiger.}
{201}{}{Wenn du für einen mächtigen Boss arbeiten willst, brauchst du einen guten Ruf oder jemanden, der dich empfiehlt. Hier ist es nicht leicht, Arbeit zu finden. [Er kneift die Augen zusammen und mustert dich.] Aber ... vielleicht bist du anders.}
{202}{}{Sowohl das Silver Legacy als auch das El Dorado haben Casinos, und im El Dorado gibt es im Keller einen Boxring. Es gibt einen Nachtclub mit vielen schönen Frauen, aber man muss bezahlen oder eine Einladung haben, um hineinzukommen. Deshalb nehmen Karawanenhändler nachts meistens die Dienste einer Frau von der Straße in Anspruch. Äh ... Und wenn du einfach nur mit jemandem reden willst, gibt es Ricky in dem hohen Gebäude neben dem El Dorado. Früher war er Karawanenhändler, und wenn du ihm einen Drink spendierst, redet er stundenlang!}
{203}{}{Zuerst wäre da Thompson – er hat das alte Rathausgebäude übernommen. Der zweite ist Stryker. Er und seine Männer haben sich in einem ehemaligen Bowlingclub eingenistet. In Reno gibt es eine Menge Kleinkriminelle, aber normalerweise ist alles in Ordnung, solange du auf der Hauptstraße bleibst. Jedenfalls solltest du aufpassen, wo du hintrittst.}
{204}{}{Niemand hat hier das Sagen, aber alle Bosse wollen es. Thompson und Stryker sind am gefährlichsten – sie sind groß und verstehen keinen Spaß.}
{205}{}{Ein Biker? Manchmal gehen Biker ins Hotel des Silver Legacy. Frag am besten dort nach.}

####################################################################
#                    Î ãğàôôèòè
####################################################################

{210}{}{Oh ... Das ist ein ziemlich großes Geheimnis. Dafür musst du eine Menge bezahlen.}
{211}{}{Was hältst du von 50 Dollar?}
{212}{}{[Pack einen seiner Finger und biege ihn zurück, bis es wehtut.] Du wirst bezahlen, wenn du mir nichts erzählst, Junge!}
{213}{}{Ich habe es mir anders überlegt. Lass mich etwas anderes fragen.}

{214}{}{Noch einen Straßenjungen für 50 Dollar umlegen? Auf keinen Fall! Ich will 200 Dollar, keinen Cent weniger!}
{215}{}{Du bist ein harter Verhandlungspartner, Junge! Na gut, hier sind 200 Dollar.}
{216}{}{Wie ich dir schon gesagt habe: Er macht das nur früh am Morgen, wenn alle schlafen. Dann solltest du nach ihm Ausschau halten.}
{217}{}{Verstehe. Lass mich noch etwas anderes fragen.}
{218}{}{Na ja, ich habe noch nie mit ihm gesprochen, aber ich habe ihn die Casinowände streichen sehen. Tagsüber und den größten Teil der Nacht sind gewöhnlich viele Leute unterwegs, deshalb arbeitet er nur früh am Morgen, kurz vor Sonnenaufgang. Das ist die einzige Zeit, in der der Großteil der Stadt schläft.}

{219}{}{Aaaah! Lass mich los! Lass mich los, dann sag ich's dir!}
{220}{}{Erst sagst du es mir!}
{221}{}{[Loslassen] Das war eine Warnung. Beim nächsten Mal höre ich nicht auf.}

{222}{}{[Die Karawanenhändler bruellen vom Parkplatz herüber] Hey! Lass den Jungen in Ruhe, Arschloch!}
{223}{}{Du hast Glück gehabt, Kleiner ... Diesmal. Wir sehen uns später wieder.}
{224}{}{[Dem Jungen direkt in die Augen sehen und stärker auf den Finger drücken]}

{225}{}{[Du spürst, wie der Finger in deinem Griff verrutscht, als die Knochen aus dem Gelenk springen] AAAAAAH!!! DAS TUT WEH!!! AAAAAAH!!!}
{226}{}{Hoppla ...}

{227}{}{Nein, bitte nicht! Ich sag's!}
{228}{}{Puh! [er versucht, wieder zu Atem zu kommen] Ich habe nie mit ihm gesprochen, aber ich habe gesehen, wie er die Wände des Casinos bemalt. Tagsüber und fast die ganze Nacht sind normalerweise viele Leute unterwegs, also arbeitet er nur früh am Morgen, kurz vor Sonnenaufgang. Das ist die einzige Zeit, in der die meisten in der Stadt schlafen.}
{229}{}{Mal sehen.}

####################################################################
#                    Î Ëûñîì Ìàêñîíå
####################################################################

{230}{}{Ich glaube, ich habe so jemanden schon mal gesehen. Aber wenn du wissen willst, wo ... }
{231}{}{Ich bezahle dich.}
{232}{}{Oh, glaub mir, das will ich. [packe einen seiner Finger und biege ihn zurück, bis es wehtut] Wie wichtig ist es dir, deine Finger heil zu behalten?}

{233}{}{Ich sage es dir für 50 Dollar.}
{234}{}{Klingt fair. Hier ist das Geld.}
{235}{}{[Er nickt in Richtung des Karawanenladens]}
{236}{}{War's das? Das ging ja leicht ... }
{237}{}{Puh! [er versucht, wieder zu Atem zu kommen] Ich habe ihn in den Karawanenladen gehen sehen. Er müsste noch in der Nähe sein!}

####################################################################
#              Îêíî â êîìîğêó øâåéöàğà
####################################################################

{238}{}{Äh ... [er schaut sich um] ... Helfen wobei?}
{239}{}{Der einzige Weg hinein ist ein Fenster. Für mich ist es zu klein, aber ich glaube, du passt durch.}
{240}{}{Ach, vergiss es.}
{241}{}{Warum musst du da rein?}
{242}{}{Weil ich wissen will, was da drin ist.}

{243}{}{[Er schaut sich wieder um] Wo ist der Haken, Mister?}
{244}{}{Na gut, schön! Ich will, dass du alles aus dem Raum mitnimmst und es mir zurückbringst.}
{245}{}{Ist es gefährlich?}
{246}{}{Nein! Überhaupt nicht.}
{247}{}{Ich muss nachdenken. Was springt für mich dabei raus?}
{248}{}{Wir teilen uns das Geld.}
{249}{}{Bist du sicher, dass da Geld drin ist?}
{250}{}{Eigentlich nicht, aber ich bin mir sicher, dass da drin *irgendetwas* Wertvolles ist.}
{251}{}{Aber was, wenn nicht?}
{252}{}{Was hast du schon zu verlieren?}
{253}{}{Nichts, aber ... Irgendwas kommt mir daran faul vor.}
{254}{}{Beruhig dich! Alles ist in Ordnung. Das kostet dich nur zehn Minuten, und danach bekommst du die Hälfte von allem, was wir finden.}
{255}{}{Hmm ... Das könnte mir heute Abend was zu essen verschaffen ... }
{256}{}{Also, bist du dabei oder nicht?}

{257}{}{Nein, ich bin raus. Das fühlt sich nicht richtig an.}
{258}{}{Nein, ich bin raus. Ich habe von dir gehört. Die Leute sagen, dass man dir nicht trauen kann.}
{259}{}{Ich bin dabei. Wann fangen wir an?}
{260}{}{Sofort.}
{261}{}{Ich komme wieder, wenn es so weit ist.}
{262}{}{Na ja, vielleicht überlegst du es dir noch anders. Ich versuche es später noch mal.}
{263}{}{Nein, ich bin raus. Bei dir fühle ich mich nicht sicher. Ich glaube nicht, dass irgendein Kind das sollte.}
{264}{}{Nein. Ich habe gehört, wie die Karawanenhändler richtig üble Dinge über dich gesagt haben.}
{265}{}{Ein Kind in ein Leben voller Verbrechen einzuführen, wäre nicht gut für dein Karma.}

####################################################################
#              Ó îêíà, òàéìåğíîå ñîáûòèå
####################################################################

{270}{}{Da wären wir.}
{271}{}{Dieser Ort ist nicht verlassen! Das ist das Hotel!}
{272}{}{Beruhig dich, das Zimmer ist leer.}
{273}{}{Das gefällt mir nicht ... }
{274}{}{Kletter schnell durchs Fenster!}
{275}{}{Okay, okay ... }
{276}{}{Hier sind ein paar Sachen. Soll ich sie nehmen?}
{277}{}{Ja! Nimm alles mit!}
{278}{}{Oh! Nicht schlecht!}
{279}{}{Ich bin fertig.}
{280}{}{Hier ist alles, was ich finden konnte.}
{281}{}{Na gut, nimm den Kram und das Kleingeld und verschwinde von hier.}
{282}{}{Für einen erfolgreichen Einbruch erhältst du 100 Erfahrungspunkte.}
{283}{}{   }

####################################################################
#              Î áàéêåğàõ
####################################################################

{290}{}{Hey, hast du hier irgendwelche Biker gesehen?}
{291}{}{Oh ja, Mister! Ihre Maschinen sind so cool! Manchmal betrinken sie sich und fangen auf der Straße Prügeleien an und so. Es macht immer Spaß, ihnen zuzusehen!}
{292}{}{Klingt nach einem Riesenspaß. Wo kann ich sie jetzt finden?}
{293}{}{Oh, sie sind jetzt nicht hier. Ich glaube nicht, dass sie so bald wiederkommen. Wenn die Nevada Express-Leute sie sehen, erschießen sie sie wahrscheinlich auf der Stelle.}
{294}{}{Verstehe. Noch eine Frage.}
{295}{}{Verstehe. Das war alles.}
{296}{}{Warum sollte der Nevada Express auf sie schießen?}
{297}{}{Die Biker haben einen Bus überfallen, der nach Black Rock fuhr. Das war echt verrückt, selbst für Biker. Der Typ in der Kampfrüstung, Tuco, sagte mir, ich solle mich vor ihnen in Acht nehmen. Er hat bei den Nevada Express in Reno das Sagen.}

####################################################################
#              Ôè÷à äëÿ ìàøèíû
####################################################################

{300}{}{Wow, Mister! Ich habe noch nie in meinem Leben ein funktionierendes Auto gesehen! Weißt du, man sagt, Reno war früher berühmt für seine Autowerkstätten. Ich glaube nicht, dass davon noch etwas übrig ist ... Außer ...}
{301}{}{Ja, ja, ich verstehe. Hier sind 20 Mäuse. Was ist es?}
{302}{}{Oh, du kennst zufällig etwas für mein Auto? Das riecht nach einer Falle.}
{303}{}{Warte damit. Wir reden später.}

{304}{}{Auf keinen Fall, Mister! Ich würde einen Kunden niemals anlügen! Ich muss vertrauenswürdig sein, sonst kann ich nichts essen!}
{305}{}{Wenn du meinst ...}
{306}{}{Bis dann.}
{307}{}{Danke! Vor ein paar Tagen kam jemand vorbei und wollte eine alte Kiste verkaufen, aber keiner wollte sie kaufen. Ich weiß nicht, was es ist, aber es ist ganz sicher etwas für ein Auto. Wo er jetzt ist, weiß ich allerdings nicht.}
{308}{}{Danke. Ich halte die Augen nach ihm offen.}
{309}{}{Dafür kriege ich 20 Mäuse? Was für eine Abzocke ...}
{310}{}{Was hast du vorhin über mein Auto gesagt?}
{311}{}{Wenn du zahlst, sag ich's dir!}

{312}{}{Hey, was zum Teufel hast du mir da angedreht?! Das ist nur Reifenfarbe, und die ist sowieso völlig eingetrocknet!}
{313}{}{Angedreht?! Ich hab dir nur erzählt, was ich gehört habe! Ich wusste nicht, dass das Zeug nutzlos ist!}
{314}{}{Und was soll ich jetzt damit anfangen?!}
{315}{}{Hast du eine Ahnung, was ich mit dem Zeug anfangen kann?}

{316}{}{Na ja, wenn du es nicht benutzen und auch nicht zurückverkaufen kannst ... Gar nichts, schätze ich. Also ... wirf es weg.}
{317}{}{Du kleiner Bengel! Wenn ich dich das nächste Mal sehe, dann ...}
{318}{}{Ich schätze, ich bin selbst schuld. Tut mir leid, dass ich dich angeschrien habe, Kleiner.}
{319}{}{Tja, man kann nicht immer gewinnen. Käufer aufgepasst, nehme ich an.}
{320}{}{Schon gut, die Leute schreien mich ständig an. Tut mir leid, dass das Zeug nichts taugt ... Ich hatte gehofft, dein Auto würde etwas Cooles bekommen.}
{321}{}{Das geht uns beiden so. Man sieht sich, Kleine.}

#Female character:
{1110}{}{Hallo, Fräulein! Willkommen im großen Reno!}
{1115}{}{[Der Junge blinzelt nicht einmal] In Ordnung, Fräulein. Ich werde Sie nicht mehr belästigen.}
{1118}{}{Oh nein, Fräulein! Ich helfe nur den Neuankömmlingen im großen Reno, damit sie sich nicht verirren.}
{1135}{}{Wie Sie meinen, Fräulein. Ich werde Sie nicht mehr belästigen.}
{1137}{}{[Der Junge schenkt dir ein übertriebenes Lächeln] Hallo, Fräulein! Wie kann ich Ihnen helfen?}
{1157}{}{Und ob! Ich bin die böse Hexe des Ödlands! Ich liebe es, kleinen Jungs die Finger zu brechen!}
{1158}{}{Das glaube ich dir nicht! Niemals würdest du so was tun! Nicht wegen eines kleinen Geheimnisses!}
{1174}{}{Ich bin ganz Ohr!}
{1243}{}{[Er blickt sich wieder um] Wo ist der Haken, Fräulein?}
{1291}{}{Oh ja, Fräulein! Ihre Maschinen sind so cool! Manchmal betrinken sie sich und prügeln sich auf der Straße und so. Das macht immer Spaß zuzusehen!}
{1300}{}{Wow, Fräulein! Ich habe in meinem Leben noch nie ein funktionierendes Auto gesehen! Wissen Sie, man sagt, Reno war einst für seine Autowerkstätten berühmt. Ich glaube nicht, dass noch etwas davon übrig ist ... Außer ... }
{1304}{}{Ach was, Fräulein! Ich würde einen Kunden niemals anlügen! Ich muss vertrauenswürdig sein, sonst bekomme ich nichts zu essen!}
{1305}{}{Wenn du meinst ...}
{1307}{}{Danke! Vor ein paar Tagen kam jemand vorbei und wollte eine alte Kiste verkaufen, aber keiner wollte sie kaufen. Ich weiß nicht, was es ist, aber es ist ganz sicher etwas für ein Auto. Wo er jetzt ist, weiß ich allerdings nicht.}
{1318}{}{Ich schätze, ich bin selbst schuld. Tut mir leid, dass ich dich angeschrien habe, Kleiner.}
