{100}{}{Du siehst den Kutschenwächter.}
{101}{}{Du siehst einen Kutschenwächter.}

#Îòâåòíûå ğåïëèêè äî ïåğâîãî ğàçãîâîğà
{105}{}{Hey, bring mir einen Drink!}
{106}{}{Hey, warum dauert das so ... Oh, ich dachte, du wärst der Kellner.}
{107}{}{Wenn du Freunde suchst, bist du hier falsch.}
{108}{}{Wenn es um Arbeit geht, sprich mit Tuco.}
{109}{}{Ich bin nur ein Wächter. Sprich mit Tuco.}

#Ïåğâûé ğàçãîâîğ ïîñëå ïğèîáğåòåíèÿ êâåñòà
{110}{}{Wenn du keine Huren und keinen Schnaps verkaufst, geh weiter.}
{111}{}{Wer bist du?}
{112}{}{Was machst du hier?}
{113}{}{Vielleicht habe ich ja Huren und Schnaps. Wer kauft?}
{114}{}{Du bist doch dieser glücklose Wächter von "Nevada Express", oder?}
{115}{}{Dann haben wir nichts zu bereden.}
{116}{}{Tschüss.}

{120}{}{Kunden natürlich! Wieso?}
{121}{}{Tuco hat uns nach dem letzten beschissenen Auftrag auf Eis gelegt. Er sagt, wir sollen entweder in Bestform sein oder gar nicht. Wir kriegen unsere Jobs zurück, sobald sich die Lage beruhigt hat.}
{122}{}{Äh, wir haben gutes Geld verdient, als wir für die Nevada Express gearbeitet haben. Warum?}
{123}{}{Ach, verdammt ... Die Leute reden, was? Mann, da sollte man doch meinen, dass es nicht so schwer ist, sich in so einer großen Stadt zu verstecken ...}
{124}{}{Also du bist es. Ich will wissen, was es mit dem überfallenen Postkutschenkonvoi auf sich hat.}
{125}{}{Ach, verpiss dich einfach, ja? Ich versuche, den Scheiß zu vergessen, und mich nicht wieder damit zu befassen.}
{126}{}{Tut mir leid, aber du hast keine Wahl. Ich untersuche die Sache auf Tucos Befehl.}
{127}{}{Was? [Sie sehen einander an] Äh ... Na schön, wie auch immer. Aber weißt du, ich würde das an deiner Stelle nicht ausgraben. Diese Biker sind gefährlich. Lieber macht man sich die nicht zum Feind.}
{128}{}{Wie auch immer, erzähl mir die Einzelheiten.}

{129}{}{Wir waren nördlich von Lovelock, als es passierte. Wir fuhren wie üblich die Straße entlang, als diese Biker uns überfielen. Wir waren so schnell unterwegs, dass sie schon aus allen Richtungen auf uns schossen, als wir den Bus endlich anhalten konnten. Sie haben den Roboter sofort ausgeschaltet, und mit dem Rest von uns war es auch bald vorbei.}
{130}{}{Wie haben sie den Roboter zerstört?}
{131}{}{Kannst du mir zeigen, wo der Überfall stattfand?}
{132}{}{Warum habt ihr euch nicht gewehrt?}
{133}{}{Wie hast du überlebt?}
{134}{}{Das reicht fürs Erste.}

{135}{}{Sie hatten Energiewaffen. Die haben sie wahrscheinlich von Militärstützpunkten.}
{136}{}{Hey, das kann ich dir nicht sagen! Das ist geheim! Wenn Tuco dir vertraut, gibt er dir vielleicht die Koordinaten.}
{137}{}{Niemand hätte das von den Bikern erwartet. Wir haben noch nie gegeneinander gekämpft. Irgendetwas muss sie wohl so verzweifelt gemacht haben, dass sie zu so etwas greifen.}
{138}{}{Sie nahmen alles, was wir hatten, und ließen uns gehen. Sie wollten, dass wir allen in Reno erzählen, was passiert ist. Kannst du das glauben? Dreckskerle! Ungefähr einen Tag später wurden wir von einer Rettungspatrouille aufgegriffen.}
{139}{}{Du lügst!}
{140}{}{Was zum Fick?! [Er steht auf] Willst du Scheiße labern, du Arschloch?! Ich schmeiß dich gleich auf die Straße!}
{141}{}{Du solltest sehr vorsichtig sein, was du als Nächstes sagst. Ich habe Beweise – die Aufzeichnungen des Roboters.}
{142}{}{Nimm es nicht persönlich, ich wollte nur sichergehen ...}
{143}{}{Ich weiß, dass ihr selbst den Bus angegriffen habt.}
{144}{}{Lass mich los!}
{145}{}{Schon gut, schon gut ...}
{146}{}{Was? Verdammt! Ich dachte, wir wären vorsichtig gewesen ... [Er beugt sich näher zu dir] Und, was hast du jetzt vor, hm? Was lässt dich glauben, dass wir dich nicht umbringen? Dann wäre es nur noch eine Leiche, die wir beseitigen müssten!}
{147}{}{Hier, vor allen Leuten? Wohl kaum.}

{148}{}{Verdammt ... Na gut, wie wäre es, wenn wir dir die Aufzeichnungen abkaufen? 2000 Dollar – mehr haben wir nicht. Das ist mehr, als du von Tuco bekommst, glaub mir.}
{149}{}{Sag mir zuerst, warum ihr es getan habt.}
{150}{}{Abgemacht. Es war mir ein Vergnügen, mit dir Geschäfte zu machen.}
{151}{}{Hm. Ich werde darüber nachdenken.}
{152}{}{Überleg es dir gut. Wenn du die richtige Entscheidung getroffen hast, bin ich hier.}
{153}{}{Mhm.}

{154}{}{[Er gibt dir das Geld, legt dann die Holodisk unter das Stuhlbein und springt darauf, sodass sie zerbricht] Das hätte auch dir passieren können, weißt du. Sei froh, dass du dich für die kluge Option entschieden hast.}
{155}{}{Such keinen Ärger. Das hätte auch dir passieren können.}
{156}{}{Ja, ja, wie du meinst. Ich bin nur wegen des Geldes hier.}

{157}{}{Warum interessiert dich das? Ach, verdammt ... Wir haben nur alte Schulden beglichen. Früher waren wir Söldner, und einer unserer alten Bosse gab uns den Auftrag, einen der Passagiere zu töten. So ein Angebot kann man nicht einfach ablehnen, weißt du.}
{158}{}{Wen solltet ihr töten?}
{159}{}{Irgendeinen Geschäftsmann aus der Gegend. Er kam aus Salt Lake zurück, um regelmäßige Lieferungen von Nuka-Cola zu vereinbaren. Manche Leute hier waren nicht gerade begeistert davon ... Pass auf dich auf, wenn du in Reno Geschäfte machst.}
{160}{}{Wer wollte ihn tot sehen?}
{161}{}{Bist du verrückt? Das kann ich dir nicht sagen! Sonst bringen sie auch mich um ... Und dich auch. Natürlich kann ich jetzt nicht zurück nach Nevada Express. Und ich wollte nur endgültig aus dem Söldnergeschäft aussteigen ...}

#Îòâåòíûå ğåïëèêè ïîñëå ïğèíÿòèÿ ğåøåíèé
{170}{}{Danke, dass du uns nicht verraten hast. Es war die richtige Entscheidung.}
{171}{}{An deiner Stelle würde ich nicht hierbleiben. Leute wie du haben hier gern mal Unfälle.}
{172}{}{Na? Hast du dich schon entschieden?}

#Female character
{1142}{}{Nimm es nicht persönlich, ich wollte nur sichergehen ...}
{1154}{}{[Er gibt dir das Geld, legt dann die Holodisk unter das Stuhlbein und springt darauf, sodass sie zerbricht] Das hätte auch dir passieren können, weißt du. Sei froh, dass du dich für die kluge Option entschieden hast.}
{1170}{}{Danke, dass du uns nicht verraten hast. Es war die richtige Entscheidung.}
