{100}{}{Du siehst Mr. Chase.}
{101}{}{Du siehst einen vornehm aussehenden Mann. Er mustert dich, als würde er in einem Laden einen Hut aussuchen.}
{102}{}{Punktzahl: }

###################################################################
#
# Getting acquainted
#
###################################################################

{110}{}{[Du siehst einen gepflegten, elegant gekleideten Mann. Sein gutes Aussehen und sein Auftreten stehen im Gegensatz zu der Narbe an seinem Hals und seinem eiskalten Blick.] Hallo. Lust auf eine Partie Billard? Ich will nicht um Geld spielen, ich suche nur einen würdigen Gegner.}
{111}{}{Kann ich dir ein paar Fragen über diese Stadt stellen?}
{112}{}{Klar, eine Partie würde mir gefallen.}
{113}{}{Tut mir leid, ich bin nur hier, um die Tische zu bewundern. Viel Glück.}

{114}{}{Es wirkt verdächtig, an den Tischen herumzustehen, ohne Interesse an einer Partie zu haben, findest du nicht?}
{115}{}{Wer sagt, dass ich kein Interesse habe? Stell die Kugeln auf, wir spielen!}
{116}{}{Nun, wenn du so darauf bestehst, dann gehe ich eben.}

{117}{}{Ich habe keine Lust, die Neugier jedes dahergelaufenen Zuschauers zu befriedigen. Aber ich rede gern beim Klang aufeinanderprallender Kugeln.}
{118}{}{Wie du willst, ich spiele. Wo ist die Kreide?}
{119}{}{Und ich habe keine Lust darauf. Dann viel Glück.}

###################################################################
#
# The game
#
###################################################################

{120}{}{[Er kreidet langsam seinen Queue ein.] Manche glauben, ein Gespräch lenke von einer guten Partie ab, aber ich denke, am Tisch zeigt sich der wahre Charakter eines Menschen, ob es ihm gefällt oder nicht. Deshalb sollte man immer auf sich achten, selbst wenn man nur zum Spaß spielt. [Er nickt dir zu.] Fang an. Schließlich bist du der Gast.}
{121}{}{Man sollte immer auf sich achten.}
{122}{}{Was willst du damit sagen?}

{123}{}{Was für ein Anstoß! Selbst Joe Davis hätte es kaum besser machen können. Vielleicht wird diese Partie interessanter, als ich erwartet hatte.}
{124}{}{[Weiter]}
{125}{}{Ich denke nur laut, mehr nicht. Konzentrieren wir uns lieber aufs Spiel – das war ein schlechter Anstoß.}
{126}{}{[Weiter]}

{127}{}{[Er zielt auf die nächste Kugel.] Nun, da wären wir also – in Reno, der Stadt, die von Lady Luck verschont blieb. Hier wird jeder Durst gestillt. Hast du in einem der Casinos schon die Bank gesprengt? Oder bist du der Typ, der bei einem Glücksspiel nichts aufs Spiel setzen will?}
{128}{}{Vielleicht spiele ich, aber ich setze nur, was ich mir leisten kann.}
{129}{}{Glücksspiel ist mir zu gefährlich. So kann man leicht alles verlieren, was man hat.}
{130}{}{Ich habe nichts gegen Glücksspiel, aber ich halte mich lieber davon fern.}
{131}{}{Leicht verdientes Geld! Ist das nicht großartig? Du erlebst den Nervenkitzel des Sieges *und* wirst dafür bezahlt!}
{132}{}{Das ist ein guter Ansatz. Ein Gentleman sollte sich kein Geld für seine Laster leihen, weder vor noch nach dem Spiel. Übrigens ein guter Schuss – ich hätte nach einem Handicap fragen sollen. Macht es dir etwas aus, wenn ich rauche? Gut ... }
{133}{}{Eine vernünftige Antwort. Lieber übervorsichtig als das Gegenteil. Übrigens ein interessanter Zug – du hast mich in eine knifflige Lage gebracht. Vielleicht gönne ich mir eine Zigarre, während ich über meinen Zug nachdenke ... }
{134}{}{Seltsame Worte. Du wirkst nicht wie jemand, der Risiken so sehr scheut. [Er wirft dir aus dem Augenwinkel einen undurchschaubaren Blick zu.] Mein Zug ... Aber zuerst muss ich meine Zigarre anzünden.}
{135}{}{Die Öfen in Reno laufen mit den Leichen jener, die auf der Suche nach schnellen Gewinnen hergekommen sind. Die Einheimischen haben gelernt, sich nicht mit ihnen einzulassen, aus Angst, selbst mit hineingezogen zu werden ... Sag mal, das erinnert mich an etwas. Wie wär's mit einer Rauchpause?}

{136}{}{[Er zündet sich eine Zigarre an und blickt aus dem Fenster zu den Prostituierten draußen.] Da sind sie, immer im Dienst. Nun, ich nehme an, manche interessieren sich auch für diese Art Spiel, und es gibt kein Vergnügen, das Reno nicht zu Geld macht.}
{137}{}{So was gibt's bei uns nicht, aber ich wünschte wirklich, es gäbe es!}
{138}{}{Moment ... Ich könnte Sex haben *und* dafür bezahlt werden? Warum hat mir das keiner gesagt?!}
{139}{}{Ein gefährliches Spiel. Ich würde diese Mädchen nicht anrühren, selbst wenn ich eine Powerrüstung trüge.}
{140}{}{Ich weiß nicht, wer verkommener ist – die Huren oder die Leute, die sie in Anspruch nehmen.}
{141}{}{Manche haben keine andere Wahl. Aber ich persönlich halte mich lieber davon fern.}
{142}{}{[Er seufzt.] Bei Frauen muss man vorsichtig sein. Barker, Dillinger ... Viele große Männer sind an so etwas zugrunde gegangen. [Er schießt.] Ha! Diesen Trickschuss habe ich von ... Ach, egal. Er ist jetzt nur noch einer von Renos Bettlern.}
{143}{}{[Er seufzt.] Ich bin kein Moralapostel, aber sich so billig anzubieten, gehört sich nicht. [Er schießt.] Ha! Diesen Trickschuss habe ich von ... Ach, egal. Er ist jetzt nur noch einer von Renos Bettlern.}
{144}{}{Hey, nur keine Eile, ja? War nur Spaß, gut gespielt. Ein guter Zug.}
{145}{}{Wirklich? Hm. Hey, immer mit der Ruhe, ja? Nur Spaß, guter Zug. Du hattest aber bessere Möglichkeiten ... Vielleicht solltest du einen trinken, um dich zu beruhigen.}
{146}{}{Ich schätze, du hast recht. Nicht jeder kann sich in seinem Beruf so geschickt behaupten wie ich ... oder du. [Er schießt.] Bah, wie konnte ich daneben schießen?}
{147}{}{Solche Gedanken solltest du für dich behalten. So berechtigt sie auch sein mögen, von dir klingen sie nach sauren Trauben ... Wackel nicht mit dem Queue, das ist kein Schwanz. Sieh an, schon wieder ein Foul.}
{148}{}{Mit so einer Einstellung könntest du mehr einstecken, als dir lieb ist ... Wackel nicht mit dem Queue, das ist kein Schwanz. Sieh an, schon wieder ein Foul.}
{149}{}{}
{150}{}{Urteile nicht über mich. Wenigstens verdiene ich mein Geld ehrlich.}
{151}{}{[Er hebt überrascht die Augenbrauen.] Hm! Du hast recht, ich entschuldige mich.}

{152}{}{Übrigens, wie wär's nach dem Spiel mit einem Drink? Wenn du dir lieber eine Vene spritzen willst: Hier ist man auf solche Vorlieben nicht eingestellt. Bei dem Tempo wird sich das allerdings eher früher als später ändern.}
{153}{}{Chems sind etwas für Verlierer, die sich einreden, sie wären Gewinner. Ich brauche sie nicht.}
{154}{}{Sehe ich für dich wie ein Junkie aus? Selbst wenn, solltest du trotzdem keine voreiligen Schlüsse ziehen.}
{155}{}{Chems können ein tristes Leben aufhellen, und trister als in Reno geht's kaum.}
{156}{}{Whoa, was? Auf einen Drink komme ich mit, aber mehr nicht!}
{157}{}{[Er nickt verständnisvoll.] Gut gesagt. In dieser Zeit und an diesem Ort findet man selten Leute wie uns.}
{158}{}{Es mag schlaue Junkies geben, aber ich bin noch keinem begegnet. Du bist doch hoffentlich gerade nicht zugedröhnt? Sonst hätte ich das Gefühl, unfair im Vorteil zu sein.}
{159}{}{Nein, nichts dergleichen. Ich biete dir nur einen guten Drink in einer anständigen Bar an. [Er schießt und schnaubt dann.] Wie peinlich! Wie konnte ich diesen Schuss verfehlen?}
{160}{}{Hm. Ist dir kalt? Ich sehe, wie du zitterst. Das wirkt sich sogar auf das Spiel aus – wie konntest du den letzten Stoß verfehlen?}

{161}{}{Ich mag das Geräusch, wenn Kugeln zusammenstoßen. Viel besser als das Knallen von Schüssen, besonders wenn sie auf dich gezielt sind. Schade, dass in Reno flinke Hände gefragter sind als Leute, die Probleme lieber mit ... alternativen Methoden lösen.}
{162}{}{Ein schneller Verstand und flinke Hände sind wirkungsvoller als ein schneller Verstand allein. Gewalt war die erste Regel der Diplomatie und ist oft die letzte.}
{163}{}{Ich versuche, mich nicht auf Kämpfe einzulassen. Wenn es doch passiert, versuche ich, so schnell wie möglich wieder herauszukommen.}
{164}{}{Diplomatie wird unterschätzt. Warum für eine Sache sterben, wenn man jemand anderen für sich sterben lassen und sich dafür auch noch bedanken kann?}
{165}{}{Für meine Methoden gibt es immer Nachfrage. Das einzige Problem ist, dass sie so unauffällig sind, dass sich ihr Einsatz nur schwer beweisen lässt.}
{166}{}{Ja, ich glaube, die Waffe an deinem Gürtel ist nicht bloß Zierde. Wenn du es mit einem der hiesigen Pöbel zu tun bekommst, setze ich auf dich.}
{167}{}{Ein Experte wie du wird in Reno nie ohne Gelegenheit dastehen. Du würdest sicher über dem hiesigen Kanonenfutter rangieren ...}
{168}{}{Hmm. Du siehst für mich nicht aus wie Annie Oakley. Wenn du dich wichtigmachen willst, würde ich dir raten, die Kimme deiner Waffe abzufeilen, falls die Einheimischen beschließen, sie dir dorthin zu schieben, woher deine Worte kommen. Mit leeren Prahlereien können sie nichts anfangen.}
{169}{}{Du kannst nicht vor all deinen Problemen davonlaufen, besonders nicht in Reno. Hinter jeder Ecke wartet eine Kugel, und ich bezweifle, dass du ihnen allen davonlaufen kannst.}
{170}{}{[Er kichert leise] Diplomatie ... Damit hätte ich nicht gerechnet, das von dir zu hören. Du wirkst nicht wie jemand, der darauf setzt.}
{171}{}{[Er grinst leicht und wirft dir einen Seitenblick zu] Klingt ernst ... Aber glaub mir, ich habe schon einiges erlebt.}
{172}{}{[Er hört aufmerksam zu und bewegt dabei den Queue in seiner Hand] Übrigens scheinen die örtlichen Gangs heute ruhig zu sein. Viele Einheimische glauben, dass sie den Kopf über Wasser halten können, wenn sie sich einem der beiden Bosse anschließen. Nun, ich nehme an, Leichen schwimmen, wenn man genug davon unter sich hat.}
{173}{}{Es gilt das Recht des Stärkeren. Wenn es sein muss, schließe ich mich auch einem von ihnen an.}
{174}{}{Alle schauen auf den einen oder den anderen. Eine dritte Partei könnte zuschlagen, bevor jemand merkt, was los ist.}
{175}{}{Ich warte auf jemanden, der zu wissen scheint, wovon er redet. Jemanden wie dich zum Beispiel.}
{176}{}{Wer Reno erobern könnte, muss etwas Besonderes sein. Dem zu folgen, lohnt sich.}
{177}{}{Hm. Du bist entschlossen, das muss ich dir lassen. Solche Methoden missbillige ich, aber deinen ... Fokus respektiere ich durchaus.}
{178}{}{[Er kichert] Ich möchte sehen, wie du damit umgehst. Tritt bitte zur Seite ... Mit etwas mehr Finesse würdest du bei diesem Spiel bessere Ergebnisse erzielen.}
{179}{}{Du bist ganz schön scharfsinnig für jemanden, der gerade erst angekommen ist, findest du nicht? Ich beschwere mich nicht ... Aber ich frage mich, wie du das machst.}
{180}{}{Eine sehr oberflächliche Einschätzung der Lage. Damit beeindruckst du vielleicht die Zuschauer, aber mich nicht ... [er zielt und versenkt den Ball geschickt in einer Ecktasche] Ha! Heute ist mein Tag, oder?}

{181}{}{Sieht so aus, als kämen wir dem Endspiel näher. Danke für das faire Spiel, das bin ich hier nicht gewohnt. In Reno gehören Betrug und Verrat zum Alltag. Jede Loyalität entspringt der Angst, und die meisten warten nur auf ihre Chance, zu jemand Stärkerem überzulaufen. [Er seufzt wehmütig] Aber vielleicht sind meine Prinzipien in dieser modernen Welt überholt.}
{182}{}{Die Welt hat sich weiterentwickelt. Du solltest dasselbe tun, bevor du abgehängt wirst.}
{183}{}{Mein Wort gilt. Mein Ruf hängt von meiner Ehrlichkeit ab.}
{184}{}{Partnerschaften können mehr sein als die Summe ihrer Teile. Leichter gesagt als getan, aber wenn sich die Gelegenheit bietet ... Warum nicht?}
{185}{}{Es stimmt, meine Prinzipien haben mich etwas gekostet. Diese Narbe ist nur der offensichtlichste Beweis. Aber ich sterbe lieber für meine Prinzipien, als ohne sie zu leben.}
{186}{}{Glaubst du wirklich, dass mich deine Meinung so sehr interessiert? Das Gewicht eines Menschen bemisst sich an seinen Taten, nicht an seinen Worten.}
{187}{}{Es ist mir ein Vergnügen, mit Leuten wie dir zu tun zu haben. Schade, dass heutzutage so wenige den Wert von Werten kennen.}
{188}{}{Vielleicht sind deine Worte für die Hoffnungslosen in den Slums inspirierend. Aber bei mir wirst du auf einen anspruchsvolleren Zuhörer treffen.}

{189}{}{[Er kommt um den Tisch herum, um dir die Hand zu schütteln] Das war ein ausgezeichnetes Spiel! Ich mag verloren haben, aber ich habe einen der wenigen Menschen in dieser Stadt getroffen, die es wert sind. Es wäre schade, wenn dies unser einziges gemeinsames Unterfangen bliebe ...}
{190}{}{Ist das ein Angebot?}
{191}{}{Vorerst musst du dich mit dem Spiel begnügen. Man sieht sich.}
{192}{}{Spiel, Satz und Sieg! Ich hab's noch drauf! ...Oh, du bist noch da? Danke fürs Spiel, es hat Spaß gemacht, aber ich glaube, du hast nichts mehr zu bieten. Ich schlage vor, wir verschwenden nicht länger die Zeit des anderen. Vielleicht sehen wir uns trotzdem eines Tages wieder. Die Leute können einen hin und wieder überraschen ... Wie auch immer, viel Glück.}
{193}{}{[Geh.]}

{194}{}{In der Tat ... Aber dies ist nicht der beste Ort zum Reden. Folge mir an einen ungestörteren Ort.}
{195}{}{[Folge ihm.]}
{196}{}{Danke fürs Spiel. Man sieht sich.}

###################################################################
#
# The quest
#
###################################################################

{200}{}{Kommen wir zur Sache. Jemand möchte im Zimmer des Besitzers von El Dorado mithören. Natürlich soll das diskret geschehen, damit der Besitzer nichts davon erfährt.}
{201}{}{Und wer ist dieser Jemand?}
{202}{}{Kein Problem. Dein Geld, meine Zeit. Wird erledigt.}
{203}{}{Äh, ich hab's mir anders überlegt. Mach's gut!}

{204}{}{Wir sehen uns wieder.}
{205}{}{Hallo. Wie wär's mit einer Partie an den Tischen unten?}
{206}{}{Erzähl mir von deinem Angebot.}
{207}{}{Und schon gehen wir wieder getrennte Wege.}
{208}{}{Erinner mich, was wolltest du noch mal?}

{209}{}{Für dich bin ich dieser Jemand.}
{210}{}{Gut genug. Ich bin dabei.}
{211}{}{Ich arbeite nicht im Dunkeln, tut mir leid.}
{212}{}{Hier sind zwei Wanzen. Eine sollte direkt in seinem Büro sein, die andere in seinem Schlafzimmer. Platziere sie an Orten, wo sie nicht entdeckt werden. Wenn du fertig bist, komm hierher zurück. Viel Glück.}
{213}{}{[Geh.]}

{214}{}{Ich bin nicht hier, um Spielchen zu spielen. Man hat mir gesagt, ich soll mich um dein Problem kümmern.}
{215}{}{Ja, man hat mir von dir erzählt. Ich vertraue Mr. Lucianos Urteil, was dich angeht, aber ... ich sollte deinen Charakter kennenlernen. Und ich habe festgestellt, dass sich das wahre Wesen eines Menschen am Billardtisch zeigt.}
{216}{}{Ich habe keine Zeit dafür. Sag mir einfach, was zu tun ist.}
{217}{}{Wenn du meinst. Ich schätze, für eine Partie habe ich Zeit.}
{218}{}{Wir müssen das später besprechen. Ich muss los.}
{219}{}{Luciano hat mich geschickt, um mich um dein Problem zu kümmern.}
{220}{}{Interessant, dass das Schicksal uns immer wieder zusammenführt. Darüber wollte ich letztes Mal mit dir sprechen. Ich hoffe, du kommst mir diesmal mehr entgegen.}
{221}{}{Die Dinge haben sich geändert. Kommen wir zur Sache.}

{230}{}{[Seine Hand streift scheinbar zufällig das Holster] Ich nehme an, du bist hier, um mir gute Nachrichten zu bringen?}
{231}{}{Ja, erledigt. Die Wanzen sind platziert.}
{232}{}{Ich habe nachgedacht ... Du bist verdammt vorsichtig damit. Wie viel ist dir mein Schweigen wert?}
{233}{}{Nein, ich wollte nur nach dem Rechten sehen und sichergehen, dass es dir gut geht.}
{234}{}{[Eine Weile bastelt er an einem Radioempfänger herum und lauscht dabei über Kopfhörer. Schließlich sieht er dich an und nickt.] Mein Freund, ich bin froh, dass ich mich nicht in dir getäuscht habe. Und nun wirst auch du dich freuen. [Er zählt langsam dein Geld ab.] Wenn du an weiterer Arbeit für den richtigen Mann interessiert bist, such Oliver Luciano auf. Er hat eine beeindruckende Ranch am Stadtrand. Sag ihnen, Johnny Chase schickt dich.}
{235}{}{Die Zusammenarbeit war mir ein Vergnügen, Mr. Chase.}
{236}{}{Ich hielt dich für einen ehrlichen Geschäftsmann, nicht für irgendeinen ... Erpresser! Aber vermutlich bin ich selbst schuld, weil ich den Preis nicht vorher ausgehandelt habe.}
{237}{}{Danke, Mr. Chase. Ich werde es mir überlegen.}
{238}{}{Einverstanden. Ein kleines Missverständnis, aber leicht zu beheben. Und vergiss nicht, Mr. Luciano zu besuchen.}
{239}{}{Hmm. Ich schätze, ich habe dich falsch eingeschätzt. Aber nicht so sehr, wie du mich falsch eingeschätzt hast. [Er greift nach seiner Waffe]}
{240}{}{[Kämpfen!]}
{241}{}{Ich habe Fragen zu dem Auftrag.}
{242}{}{Ich erledige deinen Auftrag nicht für dich. Verschwinde, und strapaziere meine begrenzte Geduld nicht weiter.}
{243}{}{[Geh.]}
{244}{}{Bertolini ist bereits tot. Hat das Ganze überhaupt noch einen Sinn?}
{245}{}{Ist er das? Hmm, das überrascht mich, erklärt aber wohl das Verhalten der Arbeiter. Trotzdem bleibt der Auftrag bestehen. Jemand anderes wird seinen Platz einnehmen, und gerade deshalb ist es umso wichtiger, dass wir von den neuen Geschäften dieser Person erfahren.}
{246}{}{Aus diesem Auftrag kommst du nicht raus.}

#Women's replics
{1111}{}{Kann ich dir ein paar Fragen über diese Stadt stellen?}
{1113}{}{Tut mir leid, ich bin nur hier, um die Tische zu bewundern. Viel Glück.}
{1119}{}{Und ich habe keine Lust darauf. Dann viel Glück.}
{1123}{}{Was für ein Anstoß! Selbst Joe Davis hätte es kaum besser machen können. Vielleicht wird diese Partie interessanter, als ich erwartet hatte.}
{1125}{}{Ich denke nur laut, mehr nicht. Konzentrieren wir uns lieber aufs Spiel – das war ein schlechter Anstoß.}
{1127}{}{[Er zielt auf die nächste Kugel] Tja, da wären wir also in Reno, der Stadt, die von Lady Luck verschont wurde. Hier ist für jeden Durst etwas dabei. Hast du in einem der Casinos schon die Bank gesprengt? Oder gehörst du zu denen, die bei Glücksspielen kein Risiko eingehen?}
{1130}{}{Ich habe nichts gegen Glücksspiel, aber ich halte mich lieber davon fern.}
{1132}{}{Das ist eine gute Einstellung. Eine Dame sollte sich für ihre Laster kein Geld leihen, egal ob vor oder nach dem Spiel. Übrigens: guter Schuss. Ich hätte um einen Vorsprung bitten sollen. Macht es dir etwas aus, wenn ich rauche? Gut ...}
{1141}{}{Manche haben keine andere Wahl. Aber ich persönlich halte mich lieber davon fern.}
{1144}{}{Hey, nur keine Eile, ja? War nur Spaß, gut gespielt. Ein guter Zug.}
{1145}{}{Wirklich? Hm. Hey, immer mit der Ruhe, ja? Nur Spaß, guter Zug. Du hattest aber bessere Möglichkeiten ... Vielleicht solltest du einen trinken, um dich zu beruhigen.}
{1154}{}{Sehe ich für dich wie ein Junkie aus? Hm, vielleicht. Trotzdem solltest du keine voreiligen Schlüsse ziehen.}
{1157}{}{[Er nickt verständnisvoll.] Gut gesagt. In dieser Zeit und an diesem Ort findet man selten Leute wie uns.}
{1166}{}{Ja, ich glaube, die Waffe an deinem Gürtel ist nicht bloß Zierde. Wenn du es mit einem der hiesigen Pöbel zu tun bekommst, setze ich auf dich.}
{1168}{}{Hm. Für mich siehst du nicht aus wie Annie Oakley. Wenn du dich wichtigmachen willst, würde ich dir raten, das Korn von deiner Waffe abzufeilen, falls die Einheimischen beschließen, sie dir dorthin zu schieben, woher deine Worte kommen. Leere Prahlereien können sie nicht leiden.}
{1177}{}{Hm. Du bist entschlossen, das muss ich dir lassen. Solche Methoden missbillige ich, aber deinen ... Fokus respektiere ich durchaus.}
{1179}{}{Du bist ganz schön scharfsinnig für jemanden, der gerade erst angekommen ist, findest du nicht? Ich beschwere mich nicht ... Aber ich frage mich, wie du das machst.}
{1189}{}{[Er kommt um den Tisch herum, um dir die Hand zu schütteln] Das war ein ausgezeichnetes Spiel! Ich mag verloren haben, aber ich habe einen der wenigen Menschen in dieser Stadt getroffen, die es wert sind. Es wäre schade, wenn dies unser einziges gemeinsames Unterfangen bliebe ...}
{1190}{}{Ist das ein Angebot?}
{1192}{}{Spiel, Satz und Sieg! Ich hab's noch drauf! ...Oh, du bist noch da? Danke fürs Spiel, es hat Spaß gemacht, aber ich glaube, du hast nichts mehr zu bieten. Ich schlage vor, wir verschwenden nicht länger die Zeit des anderen. Vielleicht sehen wir uns trotzdem eines Tages wieder. Die Leute können einen hin und wieder überraschen ... Wie auch immer, viel Glück.}
{1220}{}{Interessant, dass das Schicksal uns immer wieder zusammenführt. Darüber wollte ich letztes Mal mit dir sprechen. Ich hoffe, du kommst mir diesmal mehr entgegen.}
{1232}{}{Ich habe nachgedacht ... Du bist verdammt vorsichtig damit. Wie viel ist dir mein Schweigen wert?}
{1233}{}{Nein, ich wollte nur nach dem Rechten sehen und sichergehen, dass es dir gut geht.}
{1234}{}{[Eine Weile bastelt er an einem Radioempfänger herum und lauscht dabei über Kopfhörer. Schließlich sieht er dich an und nickt.] Mein Freund, ich bin froh, dass ich mich nicht in dir getäuscht habe. Und nun wirst auch du dich freuen. [Er zählt langsam dein Geld ab.] Wenn du an weiterer Arbeit für den richtigen Mann interessiert bist, such Oliver Luciano auf. Er hat eine beeindruckende Ranch am Stadtrand. Sag ihnen, Johnny Chase schickt dich.}
{1236}{}{Ich dachte, du wärst eine ehrliche Geschäftsfrau und nicht irgendeine ... Erpresserin! Aber ich schätze, selbst schuld, wenn ich den Preis nicht vorher ausgehandelt habe.}
