{100}{}{Du siehst einen Wachmann.}
{101}{}{Du siehst den Wachmann der Ranch.}
{102}{}{Gib mir nur einen Grund. Ich fordere dich heraus.}
{103}{}{Schön, dich zu sehen.}
{104}{}{Pass auf dem Anwesen von Mr. Luciano auf.}

#Äëÿ îõğàííèêîâ íà òåğğèòîğèè ğàí÷î
{110}{}{Halt! Ich kenne dich nicht. Was machst du auf Mr. Lucianos Ranch?}
{111}{}{Ich bin, äh, der Neue. Sieh mal, sie haben mir diese Jacke und alles gegeben!}
{112}{}{Ich arbeite für Mr. Luciano.}
{113}{}{Mit wem glaubst du, redest du? Ich bin Olivers neue rechte Hand! Ich gehe hin, wo ich will!}
{114}{}{Ranch?! Wow, ich habe mich total verlaufen! Tut mir leid, ich gehe einfach zurück zum Tor.}
{115}{}{Ich behalte dich im Auge.}
{116}{}{Äh, klar.}
{117}{}{Tut mir leid, keine Zeugen. [Angreifen]}
{118}{}{Frischfleisch, was? Na gut, mach dich an die Arbeit. Belästige nur niemanden – im Moment ist viel los, und wir haben keine Zeit für Fragen.}
{119}{}{Äh, klar.}
{120}{}{Ach, ich habe von dir gehört. Na gut, mach weiter. Belästige nur niemanden – im Moment ist viel los, und wir haben keine Zeit für Fragen.}
{121}{}{Oh ... Richtig. Mein Fehler. Tut mir leid, dass ich dich belästigt habe.}
{122}{}{Ja, genau!}
{123}{}{Viele Leute arbeiten für den Boss, aber das gibt ihnen nicht das Recht, hier zu sein. Jetzt mach kehrt. Komm nicht zurück, bevor Mr. Luciano dir die Erlaubnis gibt, hier zu sein.}
{124}{}{Ich kenne dich nicht. Das heißt, du solltest dich lieber anderswo um deine eigenen Angelegenheiten kümmern. Und jetzt verschwinde zum Teufel!}

{125}{}{Okay, das reicht! Schnappt ihn!}
{126}{}{Dafür müsst ihr mich erst erwischen!}

#Äëÿ âíóòğåííåé îõğàíû ó êàáèíåòà Îëèâåğà
{150}{}{Was zum- Dieb! Alle herkommen!}
{151}{}{[Angreifen]}
{152}{}{[Seine Hand greift nach der Waffe] Sir, Sie dürfen nicht hier sein. Verschwinden Sie, sofort.}
{153}{}{Ich wollte nur Ihren Boss sprechen ...}
{154}{}{Okay, wie du meinst.}
{155}{}{Du hättest zuerst schießen sollen. [Angreifen]}
{156}{}{Sie haben keinen Termin. Das wüsste ich. Wenn Sie Mr. Luciano sprechen wollen, wenden Sie sich an Machete. Und jetzt gehen Sie bitte.}

#Female character
{1111}{}{Ich bin, äh, die Neue. Seht ihr, sie haben mir diese Jacke und alles gegeben!}
{1114}{}{Ranch?! Wow, ich habe mich total verlaufen! Tut mir leid, ich gehe einfach zurück zum Tor.}
{1124}{}{Ich kenne dich nicht. Das heißt, du solltest dich lieber anderswo um deine eigenen Angelegenheiten kümmern. Und jetzt verschwinde zum Teufel!}
{1125}{}{Okay, das reicht! Schnappt sie!}
{1152}{}{[Seine Hand greift nach der Waffe] Ma'am, Sie dürfen nicht hier sein. Verschwinden Sie, sofort.}
{1153}{}{Ich wollte nur Ihren Boss sprechen ...}