{100}{}{Du siehst einen Sklaven.}
{101}{}{Dieser zähe, sonnengebräunte Sklave unterscheidet sich auffällig von den anderen.}
{102}{}{Danke, Wanderer.}

{110}{}{Ich kennen dich nicht, Bleichgesicht.}
{111}{}{Ich kenne dich auch nicht. Äh, das wolltest du doch sagen, oder?}
{112}{}{Bleichgesicht? So haben mich die Cheyenne genannt. Bist du von dort?}
{113}{}{Ich kann mich nicht dazu aufraffen, das zu entziffern. Tschüss.}

{114}{}{Ich sein Gishiyash vom Stillen Fluss, von den Cheyenne im Norden. Ich sein Sklave böser Männer, die mich nahmen, als ich von der Jagd zurückkehrte. Jetzt sie mich brahmin bewachen lassen. Ich es hassen! Ich sein Jäger, nicht Hirte!}
{115}{}{Ich habe gute Nachrichten. Dein Bruder Acabidab hat mich gebeten, dich zu befreien.}
{116}{}{Ist es wirklich so schlimm hier?}
{117}{}{Möchtest du nach Hause zurückkehren?}
{118}{}{Wir reden später weiter.}
{119}{}{Was, wenn ich dir bei der Flucht helfe?}

{120}{}{Hmm, für jeden Sklaven wär's gar nicht schlecht. Viele hier sein glücklich, wenn Meister ihnen sagen, was sie tun sollen. Aber ich bin frei geboren! Ich bin stolz! Ich bin Cheyenne, kein Sklave!}
{121}{}{Cheyenne warten auf mich. Das weiß ich. Ich trage Cheyenne in meiner Seele. Wenn ... wenn ich Cheyenne finden könnte, würden wir alle feiern. Aber stattdessen sitze ich in diesem Käfig fest.}

{122}{}{Die Bergluft ist kalt ... Aber sie bringt auch Regen. Wenn du mir und Cheyenne helfen willst, danke. Aber es wird nicht einfach. Die Wachen halten mich hier fest, und ich kann nicht frei sein, solange ich das hier trage. [Er zeigt auf ein Schockhalsband um seinen Hals.] Kannst du mir helfen?}
{123}{}{Zuerst rede ich mit deinem Meister und bitte ihn, dich gehen zu lassen.}
{124}{}{Ich kümmere mich um das Halsband, dann kämpfen wir uns hier raus. Was hältst du davon?}
{125}{}{Erzähl mir noch mal von dir.}
{126}{}{Der Älteste im großen Haus ist schlau. Vielleicht lässt er mich frei, wenn er mehr dafür bekommt. Aber ich glaube, er will den Himmel selbst besitzen.}
{127}{}{Andere Sklaven sagen, das kleine Haus neben der Scheune steuert die Halsbänder. Sie sagen, im kleinen Haus gibt es einen "Generator". Ich weiß nicht, was da drin vor sich geht. Aber vielleicht weißt du, wie man es abstellt.}
{128}{}{Ich habe gute Neuigkeiten. Du bist frei!}
{129}{}{[Du erledigst die Formalitäten, um den Mann freizulassen, und gehst mit ihm zum Ausgang. Er wirft den Wachen einen misstrauischen Blick zu und reibt sich über den nun freien Hals.]}
{130}{}{Also, gehst du jetzt zurück zu den Cheyenne?}
{131}{}{Ich gehe allein. Ich weiß, wie ich unterwegs Nahrung und Wasser finde. Wenn du zu den Cheyenne reist, such mich bitte.}
{132}{}{Viel Glück auf dem Weg, Gishiyash.}
{133}{}{Das ist eine ziemlich dumme Idee, aber du entscheidest. Wenn du es heil zu deinem Stamm schaffst, treffen wir uns vielleicht wieder. Leb wohl.}
{134}{}{Bevor er geht, zeigt Gishiyash dir den Standort seines Stammes auf deiner Pip-boy-Karte.}

{140}{}{Die Wachen sind tot. Verschwinde hier, und zwar schnell.}
{141}{}{Ich gehe nicht. Dieses Halsband bringt mich um, wenn ich mich zu weit entferne.}
{142}{}{Ich habe die Halsbänder ausgeschaltet. Nimm es ab und kletter über den Zaun.}
{143}{}{Ich helfe dir, es abzunehmen.}
{144}{}{Das wird einiges ändern.}
{145}{}{[Du entschärfst das Halsband mühelos.] }
{146}{}{[Der Sklave reißt sich trotzig das Halsband ab.] }
{147}{}{Ich danke dir, aber ich muss dich um einen weiteren Gefallen bitten.}
{148}{}{[Du untersuchst das Gerät sorgfältig. Du kommst zu dem Schluss, dass es weit außerhalb deiner Fähigkeiten liegt, es zu entschärfen.]}
{149}{}{Tut mir leid, ich muss erst etwas überprüfen. Ich komme wieder.}

#Clothes for the escape
{150}{}{Du hast mich gerettet, Wanderer! Wenn ich nach Cheyenne zurückkehre, werde ich ihnen erzählen, wie du mir geholfen hast. Danke!}
{151}{}{Was brauchst du?}
{152}{}{Ich muss durch Reno, um zu entkommen. Wenn ich mich vor Geckos verstecke, dürfen Geckos mich nicht sehen. Aber wenn ich mich vor Leuten verstecke, dürfen die Leute mich nicht bemerken. Ich brauche Kleidung, wie die Leute in Reno sie tragen, damit niemand erkennt, dass ich aus dem Käfig der Sklaven entkommen bin.}
{153}{}{Mal sehen, was ich habe.}
{154}{}{Ich sehe mich um, was ich finden kann. Warte einen Moment.}
{155}{}{Ich brauche Kleidung, mit der ich wie die Leute aus Reno aussehe. Hast du so etwas?}
{156}{}{[Geben: }
{157}{}{]}
{158}{}{[Weiter]}
{159}{}{[Zurück]}
{160}{}{Warte einen Moment. Ich versuche, etwas zu finden, das dir helfen kann.}

#Female version
{1102}{}{Danke, Wanderer.}
{1110}{}{Ich kennen dich nicht, Bleichgesicht.}
{1142}{}{Ich habe die Halsbänder ausgeschaltet. Nimm es ab und kletter über den Zaun.}
{1150}{}{Du hast mich gerettet, Wanderer! Wenn ich nach Cheyenne zurückkehre, werde ich ihnen erzählen, wie du mir geholfen hast. Danke!}