{100}{}{Du siehst einen Metzger.}
{101}{}{Du siehst einen sehr kräftigen Mann. Er sieht aus, als wäre er zum Metzger geboren.}
{102}{}{Mr. Luciano ist tot. Tot, hörst du?! Wie sollen wir diesen Laden ohne ihn führen?}
{103}{}{Du erhältst 100 Erfahrungspunkte, weil du etwas über Mr. Luciano und seine Ranch erfahren hast.}

{110}{}{[Du siehst einen kahlköpfigen Mann mit dicken, kräftigen Händen. Er versucht, sich an dem Lagerfeuer eine Zigarette anzuzünden, und flucht, als er sich die Finger verbrennt.]}
{111}{}{Heh, das hättest du dir denken können.}
{112}{}{Hey, nimm dieses Feuerzeug. Es ist ein Geschenk.}
{113}{}{[Weitergehen]}

{114}{}{Noch ein Wort, und du zündest mir den Rest deines Lebens die Zigaretten an.}
{115}{}{Mensch, tut mir leid ...}
{116}{}{[Er überlegt kurz, beschließt aber, dein Geschenk anzunehmen.] Danke. Du bist neu hier, oder?}
{117}{}{Äh, ja. Ich wollte mir die Ranch von innen ansehen.}

{118}{}{Ja, verstehe ich. Sie ist ziemlich beeindruckend, was?}
{119}{}{Kann ich dir ein paar Fragen über die Ranch stellen?}
{120}{}{Das wäre es erstmal. Ich sehe mich weiter um.}

{121}{}{Nur zu. Vielleicht kann ich dir etwas erzählen.}

{122}{}{Erzähl mir von dieser Ranch.}
{123}{}{Was soll ich sagen? Es ist nicht nur unsere Arbeit, es ist unser Zuhause. Wir sind hier alle eine Familie. Und niemand verlässt die Familie ... Mr. Luciano sieht das als Verrat, und, hehe, du willst ihn nicht wütend machen. Nicht, dass du gehen wollen würdest, aber wie auch immer. Reno wird immer Nahrung brauchen – und wir haben reichlich davon. Seit wir Sklaven für die Ernte einsetzen, läuft es sogar noch besser. Alles, was wir nicht verwerten können, verfüttern wir an die Brahmin, bis sie schlachtreif sind. Neulinge brauchen immer eine Weile, um sich daran zu gewöhnen, aber für uns ist es Routine.}
{124}{}{Also versorgt ihr die ganze Stadt mit Lebensmitteln?}
{125}{}{Nein, natürlich nicht. Rund um Reno gibt es noch andere Bauern, und man sagt, im Nordosten gebe es einen Indianerstamm, der gutes Getreide anbaut. Aber Mr. Luciano ist bei Weitem der größte Produzent hier in der Gegend. Er ist zuverlässig und ehrlich, und seine Ranch ist die größte im County.}
{126}{}{Wie kann man überhaupt eine so große Ranch betreiben?}
{127}{}{Das ist nicht leicht. Das Land erinnert sich noch daran, was die Menschheit ihm vor 60 Jahren angetan hat. Selbst heute haben wir mit kranken Tieren und Ernteausfällen zu kämpfen. Man sagt, in den ersten 20 Jahren nach dem Krieg habe es überhaupt keine Ernte gegeben. Mr. Luciano ist der Einzige, der noch aus jener Zeit hier ist. Angeblich haben er und seine Frau Maureen dieses Land schon bewirtschaftet, bevor die Bomben fielen. Ich weiß nicht, wie viel an diesen Gerüchten dran ist, aber eines weiß ich sicher: Niemand versteht mehr von Landwirtschaft als Mr. Luciano. Er gehörte zu den Ersten, die ausschließlich Wasser aus Brunnen statt aus offenen Gewässern nutzten. Er gehörte zu den Ersten, die Sklaven statt angestellter Arbeiter einsetzten. Der Wille dieses Mannes ist unerschütterlich. Er hat die Ranch nie aufgegeben, nicht einmal, nachdem seine Frau gestorben war.}

{128}{}{Was kannst du mir über Mr. Luciano erzählen?}
{129}{}{Er ist der Kopf der Ranch. Und ich meine nicht nur, dass er uns bezahlt. Er ist derjenige, der diesem Ort Leben einhaucht. Klar, er ist jetzt alt, aber er ist immer noch ein Mann, dem man Respekt zollen sollte. Er steht noch immer, trotz allem.}
{130}{}{„Selbst nach allem“? Was meinst du?}
{131}{}{Er hat für seine Familie gelebt, aber jetzt ist seine ganze Familie fort. Er ist der letzte Luciano.}
{132}{}{Erzähl mir seine Geschichte.}
{133}{}{Erzähl mir die Geschichte von Mr. Luciano.}

{134}{}{Ich weiß nicht, ob ich dir viel erzählen darf, aber ich sage dir, was ich für wichtig halte. Er war eines von fünf Kindern in einer armen Familie. Viele seiner Verwandten starben kurz nach den Bombenangriffen – manche bei Schießereien auf der Straße, manche an der Strahlung, manche einfach an Hunger. Damals war Mr. Luciano erst etwa zehn Jahre alt, aber ich bin sicher, dass er sich noch gut an diese Zeit erinnert. Er wollte ein besseres Leben. Er wusste, dass er für Größeres bestimmt war.}
{135}{}{[Weiter]}
{136}{}{Er hat sein ganzes Leben hart gearbeitet. Es ist erstaunlich, dass er heute noch lebt. Er hatte Herzinfarkte, Hämorrhoiden, verdammt, auf einem Auge ist er sogar erblindet – aber sein Geist brennt noch immer wie Feuer, obwohl er seine ganze Familie verloren hat. Seine Frau starb vor etwa zwei Jahren an Krebs. Möge sie in Frieden ruhen. Sein erster Sohn starb bei der Geburt. Die Ärzte sagten, es lag an der Strahlung, der er und seine Frau bei der Feldarbeit aus dem Boden ausgesetzt waren. Sein zweiter Sohn war Anfang zwanzig, als er vor zehn Jahren während der Revierkämpfe auf mysteriöse Weise ums Leben kam. Der Mörder wurde nie gefunden.}
{137}{}{[Weiter]}
{138}{}{Nicht viele könnten nach all dem weitermachen. Aber sieh dir diese Ranch an – ein verdammtes Wunder ist das! Und Mr. Luciano hat es möglich gemacht. Sein Essen hat Reno so viel Leben geschenkt. Viele wären heute nicht mehr am Leben, wenn es ihn nicht gäbe.}
{139}{}{Was für eine düstere Geschichte. Ich bin sicher, Luciano wird alles tun, damit sein Geschäft floriert. Was weißt du über seine Beteiligung am aktuellen Krieg in Reno?}
{140}{}{Ist das wirklich ein Krieg? Das sind doch nur ein paar Banditen aus dem Ödland, die stehlen wollen, was wir aufgebaut haben. Es ist widerlich, dass sich jemand in Reno auf ihre Seite schlägt. Mr. Luciano setzt sich wirklich für etwas ein. Er kämpft für seine Ranch, und das ist wichtiger als jeder Machtkampf, der in der Stadt tobt. Ich weiß nicht, was er vorhat, aber meiner Meinung nach wären wir alle besser dran, wenn diese Gangster die Stadt verlassen und nie wiederkommen würden.}
{141}{}{Na gut, danke für die Geschichte. Sie hat mir einiges zum Nachdenken gegeben.}
{142}{}{Klar. Pass auf dich auf.}
{143}{}{Pass auf dich auf.}