{100}{}{Du siehst die Verwalterin.}
{101}{}{Du siehst eine streng dreinblickende Geschäftsführerin. Sie hat auf alles eine klare Antwort.}
{102}{}{Ich bin hier, um Geschäfte zu machen, nicht um zu plaudern. Wenn du nichts Wichtiges zu sagen hast, dann geh.}
{103}{}{Bist du taub oder einfach nur dumm? Solange du für Mr. Luciano arbeitest, wirst du antworten, wenn ich mit dir spreche.}
{104}{}{Ohne Oliver werden harte Zeiten auf die Ranch zukommen. Aber wir haben uns darauf vorbereitet.}

#Ïğèîáğåòåíèå êâåñòà
{110}{}{Ich nehme an, das hier ist kein Kundendienst. Was machst du hier?}
{111}{}{Na schön, dann gehe ich eben.}
{112}{}{Ich kümmere mich um die tägliche Verwaltung, den Papierkram und andere Geschäfte, für die Mr. Luciano keine Zeit hat. Das heißt, ich führe alle Verhandlungen mit unseren Händlern und Lieferanten. Verträge, Zahlungen, alles. Wie du dir vorstellen kannst, ist das eine Menge Arbeit. Und ich würde *wirklich* gern wieder damit weitermachen.}
{113}{}{Was wäre, wenn ich dir helfen würde? Vielleicht wäre ich selbst ein großartiger Verhandler.}
{114}{}{Hm. [sie hebt eine Augenbraue] Vielleicht könntest du das ... Du verstehst doch, dass es auf dem Markt um mehr geht als nur um Angebot und Nachfrage, oder?}
{115}{}{Ja, und gerade geht es dem Markt in Reno schlecht.}
{116}{}{Reno war einmal ein großartiger Ort, um Geschäfte zu machen. Doch dann fingen die Geschäftsleute an, sich gegenseitig zu bekämpfen und Kriminelle mit hineinzuziehen. Was wir heute haben, ist kein Vergleich zu damals.}
{117}{}{Du meinst vor den Bomben?}
{118}{}{Nein, nein. [sie winkt ab] Ich spreche vom „Goldenen Zeitalter“ von Reno. Das ist noch gar nicht so lange her ... Aber darum geht es nicht. Ich brauche Informationen. Hast du Interesse?}
{119}{}{Worum geht's?}
{120}{}{[Sie seufzt genervt] Was für ein Händler du auch sein magst, wir suchen keine neuen Verträge. Wir verkaufen bereits unsere gesamten Waren, bis auf das, was wir für uns behalten.}
{121}{}{Finde heraus, woher Thompson und Stryker ihre Lebensmittel beziehen. Sie bekommen sie mit ziemlicher Sicherheit von Händlern, die mit uns zusammenarbeiten, aber für nähere Informationen zahlen wir 300 Dollar.}
{122}{}{Und ich werde dich Mr. Luciano empfehlen, falls du für ihn arbeiten möchtest.}
{123}{}{Klingt vernünftig. Ich kümmere mich darum.}
{124}{}{Ich glaube nicht, dass ich das schaffe.}
{125}{}{Gut. Beeil dich, damit ich wieder an die Arbeit kann.}
{126}{}{Na gut.}
{127}{}{Du wirst bezahlt, wenn du uns die Informationen bringst. Bis dahin lass mich in Ruhe arbeiten.}

{128}{}{Warum kannst du diese Informationen nicht selbst herausfinden?}
{129}{}{Das geht dich nichts an, aber die meisten Geschäfte in Reno halten ihre Abmachungen geheim. Wir können nicht einfach fragen, wer an wen verkauft.}

#Äèâåğñèÿ ó ğåñòîğàíà
{140}{}{Ich, äh, habe in einem Restaurant ein Gespräch mitgehört. Angeblich stimmt etwas mit eurem Fleisch nicht!}
{141}{}{Tss! Glaubst du ernsthaft, ich wüsste davon noch nichts, oder willst du mich einfach nur wütend machen? Ich bin sicher, das ist nur ein Gerücht, entweder vom Restaurantbesitzer oder von unseren Feinden. Schade, dass Oliver jetzt glaubt, auf der Ranch gäbe es ein Problem. Oder vielleicht glaubt er das gar nicht und braucht nur einen Vorwand, um uns zu bestrafen. So oder so haben wir bereits ordentlich Prügel bezogen.}
{142}{}{Hm, eine zwielichtige Sache. Na dann, man sieht sich.}

#Ñäà÷à êâåñòà
{150}{}{Ich habe eine Liste mit den Geschäften von Thompson und Stryker. Darin sollten die Informationen stehen, die du brauchst.}
{151}{}{Verschwende nicht meine Zeit, gib sie mir!}
{152}{}{[Gib sie ihm]}
{153}{}{Hm ... Daten, Lieferanten, Orte, Geschäfte ... Ich bin beeindruckt. Ich hätte nicht gedacht, dass Gangster genug Grips haben, um so sorgfältig Buch zu führen. Gute Arbeit. Hier sind wie vereinbart 300 Dollar. Wenn du noch mehr Arbeit suchst, werde ich bei Mr. Luciano ein gutes Wort für dich einlegen.}
{154}{}{[Weiter]}
{155}{}{Ich habe noch einen Auftrag für dich. Den Daten zufolge beziehen beide Banden einen Teil ihrer Lebensmittel von einheimischen Geschäftsleuten und Karawanen. Ich weiß nichts über diese Lieferanten – finde heraus, wer sie sind und warum sie diesen ... Revolutionären so ergeben sind.}

#Female character
{1140}{}{Ich, äh, habe in einem Restaurant ein Gespräch mitgehört. Angeblich stimmt etwas mit eurem Fleisch nicht!}
