{100}{}{Du siehst einen Sklaven.}
{101}{}{Du siehst einen Sklaven. Seiner rauen, schmutzigen Haut nach zu urteilen, ist er schon lange in diesem Zustand.}

{102}{}{Nach dem Tod des Meisters wird die Ranch verlassen sein.}
{103}{}{Was sollen wir ohne den Meister tun?}
{104}{}{Wie soll ich leben, wenn der Meister nicht mehr da ist?}

{105}{}{Ich weiß nicht ... Ich kann nicht anders leben.}
{106}{}{Der Meister ist gerecht, aber sehr grausam.}
{107}{}{Manchmal wird der Meister sehr wütend. Dann hält man am besten den Mund.}
{108}{}{Heute würde ich dem Meister aus dem Weg gehen.}