{100}{}{Du siehst Oliver Luciano.}
{101}{}{Du siehst einen Mann mittleren Alters in einem Schlafanzug und weichen Pantoffeln.}
{102}{}{Wachen! Was macht ein Fremder in meinem Büro?!}
{103}{}{Noch ein Geschäftsmann weniger.}
{104}{}{Verschwinde!}

{105}{}{Mein ... Herz ... Wie ... schmerzhaft ...}
{106}{}{Ugh ... Maureen ...}
{107}{}{A-a-arrgh!!!}
{108}{}{*hust* ... *hust* ...}
{109}{}{Der Geschäftsmann starb still und qualvoll an seinem Bett.}

{110}{}{Machete sagte, du wolltest mich sehen. Ich bin bereit, mir anzuhören, was du zu sagen hast.}
{111}{}{Entschuldigen Sie, dass ich Sie störe, Mr. Luciano. Ich komme wieder, wenn ich etwas habe, das Ihre Zeit wert ist, wenn Sie mich lassen ...}
{112}{}{Ich bin nicht gerade bester Laune, also hoffe ich, dass es sich lohnt.}
{113}{}{Komm rein, mach es dir bequem. Eine freie Minute kann ich für dich finden.}

{114}{}{[Als du den Raum betrittst, fällt dir zuerst seine Sauberkeit, Ordnung und Stille auf. Plötzlich hörst du das dumpfe Klirren angestoßener Weingläser und nimmst einen schwachen Hauch von Desinfektionsmittel wahr. Ein Mann im alten Bademantel steht mit dem Rücken zu dir. Über die Schulter wirft er dir einen kurzen, gleichgültigen Blick zu, gießt sich langsam ein Glas klares Wasser aus einer Karaffe ein und setzt sich dann, das Glas behutsam haltend, an seinen Schreibtisch.]}
{115}{}{Mr. Oliver Luciano?}

{116}{}{Du kämpfst bald, stimmt's? Du solltest wissen, dass ich viel Geld auf dich gesetzt habe und gewinnen will.}
{117}{}{Danke, Boss.}
{118}{}{Ich werde dich nicht enttäuschen, Boss.}
{119}{}{Du verstehst nicht, Dummkopf. Ich will einfach nur gewinnen.}

#Âñòğå÷à ñ Ğàéòîì
{120}{}{Mr. Luciano, Theodore Wright hat Ihnen ein Treffen vorgeschlagen, um -}
{121}{}{Ich will nichts mit ihm zu tun haben.}
{122}{}{Aber Sir! Mr. Wright bietet Ihnen ein sehr gutes Geschäft an.}
{123}{}{Nun, ich sehe, du hast dich entschieden.}

{124}{}{Vielleicht. Unter anderen Umständen würde ich es in Erwägung ziehen, aber nicht auf Geheiß des Laufburschen des Teufels.}
{125}{}{Was soll das heißen? Mr. Wright ist Geschäftsmann, nicht der Teufel!}
{126}{}{Stell dich nicht dumm. Ich rede nicht von ihm. Du weißt genau, wen ich meine.}
{127}{}{Hast du ein Problem mit meinem zweiten Boss?}
{128}{}{Deine Heuchelei ist abstoßend. Verschwinde. Sofort. Bevor ich etwas tue, das du bereuen wirst.}
{129}{}{Nun, Sie haben sich klar ausgedrückt, Sir. Ich werde Sie nicht weiter belästigen.}

{130}{}{Ich dachte, du arbeitest für *mich*. Du solltest besser keine weiteren Überraschungen dieser Art auf Lager haben. Ich bin enttäuscht, aber unsere Beziehungen zu Wright sind schon viel zu lange angespannt. Sag ihm, ich bin bereit, ein Treffen zu arrangieren ... Nur, weil ich dir vertraue.}
{131}{}{Danke, Boss.}
{132}{}{Das ist großartig.}

{133}{}{Nun, unsere Beziehungen zu Wright sind schon viel zu lange angespannt. Aber ich verstehe nicht: Warum hat er mir so einen ... zweifelhaften kleinen Speichellecker geschickt und nicht jemanden aus seiner Familie?}
{134}{}{Weil ich im Gegensatz zu seinen Leuten nicht überwacht werde. Mr. Luciano, Sie wissen, wie gefährlich es ist, offen zu operieren. Mr. Wright hat mich wegen meiner Diskretion ausgewählt.}
{135}{}{Ja, ich gehöre vielleicht nicht zur Familie, aber Mr. Wright vertraute mir diese heikle Aufgabe an, weil ich in der Stadt einen tadellosen Ruf genieße.}
{136}{}{Stimmst du dem Treffen also zu?}

{137}{}{Wer hat diese überzeugende Rede geschrieben? Ich bezweifle, dass du es warst. Sag Wright, dass solche geschliffenen Worte lächerlich klingen, wenn sie aus deinem Mund kommen.}
{138}{}{Nun, ich werde Mr. Wright deine Absage überbringen.}
{139}{}{Ich muss zugeben, du denkst gründlicher nach als die meisten Untergebenen. Vielleicht hat Wright dich deshalb für diesen Auftrag ausgewählt und keinen aus der Familie. Schließlich haben seine Söhne zusammen weniger Verstand als ein einköpfiger Brahmin. Na gut, du hast gewonnen. Sag Theodore, dass ich bereit bin, ihn zu treffen.}

{140}{}{Dein Ruf ist mir keinen Eimer brahmin-Pisse wert. Verschwinde und sag Wright, er soll nächstes Mal einen besseren Vermittler schicken.}
{141}{}{Weil ich im Gegensatz zu seinen Leuten nicht überwacht werde. Mr. Luciano, Sie wissen, wie gefährlich es ist, offen zu operieren. Mr. Wright hat mich wegen meiner Diskretion ausgewählt.}
{142}{}{Nein. Ich bin nicht daran interessiert, mit einem Geschäftsmann zu verhandeln, der so tief gesunken ist, dass er irgendeinen erbärmlichen Handlanger statt seines eigenen Sohnes schickt.}
{143}{}{Du lehnst ab, weil ich es bin? Na ja, wenigstens hab ich's versucht ...}
{144}{}{Hey, immer mit der Ruhe! Ich möchte dich darauf hinweisen, dass hier in Reno eine glänzende Zukunft auf mich wartet.}
{145}{}{Ich habe dir meine Entscheidung bereits mitgeteilt. Du hast nichts getan, um meine Meinung zu ändern.}
{146}{}{Bei allem Respekt, Sir, das ist ein Fehler. Glauben Sie mir, Mr. Wright bietet Ihnen einen hervorragenden Handel an.}
{147}{}{Ich werde Mr. Wright Ihre Antwort übermitteln. Danke für Ihre Zeit.}
{148}{}{Na gut. Ich muss dann mal los.}

#Ïîïûòêà íàïğîñèòüñÿ íà ğàáîòó
{150}{}{Mr. Luciano, ich möchte für Sie arbeiten.}
{151}{}{Das sagen viele. Aber wenn es darum geht, tatsächlich zu arbeiten, sind die meisten ungefähr so nützlich wie brahmin Scheiße. Und genau wie brahmin Scheiße landen die, die nur große Töne spucken, auf dem Komposthaufen ... Wenn du verstehst, was ich meine.}
{152}{}{Ich verstehe. Und was ist mit dem Job?}
{153}{}{Hör zu, ich nehme nicht einfach irgendwen. Ich brauche jemanden mit tadellosen Referenzen. Die Frage ist: Hast du die?}
{154}{}{Na ja, jetzt, wo du und Mr. Wright zusammenarbeiten, kann ich wohl auch für dich arbeiten, ohne meine Loyalität teilen zu müssen.}
{155}{}{Ich bin überzeugt. Ich stelle dich ein, aber eins muss dir klar sein: Ich bin kein nachsichtiger Mann. Und wenn du mich enttäuschst, nageln meine Leute dich an die Wand, selbst wenn sie dich dafür bis in die tiefste Hölle verfolgen müssen.}
{156}{}{Natürlich. Kein Problem.}
{157}{}{Ich habe dir doch schon mit Canary geholfen. Reicht das nicht?}
{158}{}{Mr. Chase hat mich gebeten, wegen eines Jobs mit Ihnen zu sprechen. Ich bin sicher, er hätte das nicht ohne guten Grund getan.}
{159}{}{Ich kenne niemanden in Reno, der für mich bürgen kann.}
{160}{}{[Er wird lauter] Dann SUCH DIR JEMANDEN, du Trottel! Beweg deinen faulen Hintern und tu endlich was. Ich schätze Leute, die sich ihren Lebensunterhalt durch eigene Arbeit verdienen. Und jetzt raus aus meinem Haus.}
{161}{}{[Gehen]}
{162}{}{Ich brauche niemanden wie dich. Ich kann politische Huren nicht ausstehen, die von einem Herrn zum nächsten wechseln. Ich brauche LOYALITÄT! Nicht nur mir gegenüber, sondern auch meinen Idealen. Und jetzt verschwinde zur Hölle.}
{163}{}{[Gehen]}
{164}{}{Ich habe Arbeit für dich, aber ich kann politische Huren nicht ausstehen, die von einem Herrn zum nächsten wechseln. Ich brauche LOYALITÄT! Nicht nur mir gegenüber, sondern auch meinen Idealen. Merk dir das und schwing dich zum Teufel!}
{165}{}{Nicht nötig. Sieh mich an – ich habe genug Erfahrung und brauche keine Empfehlungen.}
{166}{}{Also, mein alter Freund Johnny Chase braucht Hilfe bei einer sehr heiklen Angelegenheit. Finde ihn im Casino El Dorado und hilf ihm, die Sache schnell zu erledigen.}
{167}{}{Ich gehe jetzt zu Mr. Chase.}
{168}{}{In Ordnung, ich sehe, was ich tun kann.}
{169}{}{Halt. Ich bin noch nicht fertig. Das ist wichtig: Sei höflich zu Chase und wage es ja nicht, ihn anzulügen. Wir dulden keine politischen Huren, die mit jedem flirten, dem sie begegnen, um sich ihr Auskommen zu sichern. Das ist alles. [Er macht eine Geste, dass du gehen sollst]}
{170}{}{[Gehen]}
{171}{}{Ich muss dir etwas über den Auftrag sagen.}
{172}{}{Hast du deine Aufgabe erledigt?}
{173}{}{Äh, ich wollte nur etwas klarstellen ...}
{174}{}{[Er wird lauter] Ich sagte: GENUG! Benutz jetzt deine wenigen verbliebenen Gehirnzellen und erledige verdammt noch mal den Auftrag!}
{175}{}{[Geh.]}
{176}{}{Das war's, Auftrag erledigt.}
{177}{}{[Er seufzt] Vielleicht. Aber ich habe gehört, Chase sei ein „Unfall“ zugestoßen. Ich glaube nicht an „Unfälle“, und du hast dir nicht einmal die Mühe gemacht, mir eine Erklärung zu geben. Wachen!}
{178}{}{[Kämpfen]}
{179}{}{[Leise gehen]}
{180}{}{[Er nickt] Ich hoffe, du wurdest vollständig bezahlt. Ich will eine ehrliche Partnerschaft.}
{181}{}{Ja, Mr. Luciano. So ziemlich.}
{182}{}{Nun, da du meinem alten Freund Chase geholfen hast, können wir über ernstere Angelegenheiten sprechen.}
{183}{}{Ich höre.}
{184}{}{Ich habe schlechte Nachrichten: Chase ist ein „Unfall“ zugestoßen, und ich ...}
{185}{}{Ich glaube nicht an „Unfälle“, und du hast dir nicht einmal die Mühe gemacht, mir eine Erklärung zu geben. Wachen!}
{186}{}{Ich glaube dir. Ich sehe, dass es dir nur ums Geschäft geht. Du musst dich nicht bei den Mächtigen einschleimen, um ihre „Freundschaft“ zu gewinnen. Das gefällt mir. Ich stelle dich ein, aber merk dir: Ich bin kein nachsichtiger Mann. Und wenn du mich enttäuschst, werden meine Leute deinen Arsch an die Wand nageln, selbst wenn sie dich dafür bis in die Tiefen der Hölle verfolgen müssen.}
{187}{}{Der Verwalter der Ranch wird dir die Einzelheiten nennen.)}

#Ğàá èç Óğàí-Ñèòè
{190}{}{Mr. Luciano, ich möchte einen Ihrer Sklaven kaufen – er heißt Joseph.}
{191}{}{Das war's? Sprich mit Machete, er kümmert sich um Kleinigkeiten.}
{192}{}{Ugh ...}
{193}{}{Ich stehe zu meinem Wort. Ich habe versprochen, dir im Gegenzug für deine Hilfe zu helfen. Und diesmal bleibt es nicht bei Worten. Du kannst diesen Sklaven haben, ich gebe die Anweisung. Geh zum Pferch und sag den Wachen, dass Joseph dir gehört.}
{194}{}{Danke, Mr. Luciano.}

{195}{}{Mr. Luciano, ich weiß, dass sich ein Cheyenne-Sklave in Ihrem Besitz befindet. Ich würde ihn gern kaufen.}

#Ïåğâûé êâåñò
{200}{}{Die Informationen, die du uns beschafft hast, waren nützlich. Aber ich weiß immer noch nicht, wie vertrauenswürdig du bist. Du musst dir mein Vertrauen also noch ein wenig verdienen.}
{201}{}{Was soll ich tun?}
{202}{}{Dein Hauptziel: Stiehl das Geld, das in Bertolinis Safe gehortet wird. Das ist eine schwierige Aufgabe, aber ich denke, du schaffst das. Schließlich ist es dir bereits gelungen, Wanzen in seinem Büro zu installieren. Ich bin sicher, du findest auch einen Weg zum Safe.}
{203}{}{Äh, ein Casino ausrauben? Bist du knapp bei Kasse oder so?}
{204}{}{Verstanden. Sonst noch etwas?}
{205}{}{[Er runzelt die Stirn] Ich bin kein Dieb! Ich arbeite für meinen Lebensunterhalt. Aber vielleicht hast du meine Bitte falsch verstanden ... Nun, damit keine Zweifel bleiben, erkläre ich es dir. Mir geht es nicht so sehr um das Geld selbst, sondern darum, Bertolini in den Ruin zu treiben. Er hat diese Summe aus einem bestimmten Grund angesammelt.}
{206}{}{Verstanden. Du hast gesagt, das sei das Hauptziel. Gibt es noch Nebenziele?}
{207}{}{Wenn Bertolini sein Erspartes verliert, wird es noch eine Weile dauern, bis sein Geschäft zusammenbricht. Wenn es so weit ist, werden seine Leute ausschwärmen wie Ameisen aus einem zerstörten Ameisenhaufen. Wir müssen diesen Krisenmoment so lange wie möglich hinauszögern.}
{208}{}{Kannst du mir etwas Konkretes empfehlen?}
{209}{}{Sprich mit Machete darüber. Diese Einzelheiten sind unter meiner Würde.}
{210}{}{In Ordnung. Das Geld stehlen und ein Casino sabotieren. Verstanden.}
{211}{}{Du wirst nach Abschluss bezahlt. Und jetzt mach dich an die Arbeit.}
{212}{}{[Geh.]}
{213}{}{Der Auftrag ist erledigt – ich habe Bertolinis Geld aus seinem Safe gestohlen. Hier ist der Koffer.}
{214}{}{Ausgezeichnete Arbeit! Da du den Auftrag unauffällig erledigt hast, zahle ich dir mehr als geplant. [Er gibt dir 2000 $]}
{215}{}{Gute Arbeit! Aber ich habe gehört, dass Bertolini einen bedauerlichen „Unfall“ hatte. Das war nicht, was ich wollte. Du hast den Auftrag trotzdem erledigt, also hier ist dein Geld: 1000 $. Aber ich habe keine Arbeit mehr für dich.}
{216}{}{[Geh.]}
{217}{}{Danke, Boss.}

{218}{}{Aber damit ist dein sekundäres Ziel noch nicht erledigt – ruiniere den Ruf des Casinos. Hast du das geschafft?}
{219}{}{Ja, ich habe das Casino sabotiert.}
{220}{}{Ja, ich konnte ein Casino vor den Augen der einfachen Bürger bloßstellen.}
{221}{}{Noch nicht, ich arbeite daran.}

{222}{}{Das sind gute Neuigkeiten. Das verschafft mir Zeit, alles vorzubereiten ... Also, Zeit für deinen Lohn.}
{223}{}{Danke.}
{224}{}{}
{225}{}{[Er zählt 350 $ ab] Ich würde deine Dienste gern weiter in Anspruch nehmen, aber ich höre, dass du dich entschieden hast, auf der anderen Seite der Barrikade zu kämpfen. Deshalb will ich nichts mehr mit dir zu tun haben. Verschwinde verdammt noch mal.}
{226}{}{[Er zählt 350 $ ab] Ich bin nicht zufrieden. Klar, du hast es geschafft, das Geld zu stehlen und deine Spuren zu verwischen, aber du hast einen gewaltigen Fehler gemacht: Bertolini durfte nicht sterben. So einen Leichtsinnigen kann ich nicht auf meiner Gehaltsliste haben. Verschwinde verdammt noch mal.}
{227}{}{[Er zählt 500 $ ab, reicht dir das Geld und nickt zu Bertolinis Koffer] Gute Bezahlung für gute Arbeit. Ich habe jetzt einen weiteren Plan, und du sollst ihn in die Tat umsetzen.}
{228}{}{[Geh.]}
{229}{}{Was kommt als Nächstes?}
{230}{}{Ich will, dass du einen Krieg zwischen Stryker und Thompson anzettelst. Sabotiere ihr Gebiet, damit sie sich gegenseitig die Schuld geben. Machete wird dir die Einzelheiten nennen.}
{231}{}{Das war's?}
{232}{}{Ja ... Bist du noch da?}
{233}{}{Ich bin schon unterwegs, Mr. Luciano.}

{234}{}{Gute Arbeit! Außerdem habe ich von einem gewissen „Tumult“ im Casino gehört. Ich weiß nicht, ob du etwas damit zu tun hattest, aber ich warne dich ein einziges Mal: Sei vorsichtig, solange du für mich arbeitest. Da du den Auftrag erledigt hast, zahle ich dir aber wie geplant. [Er gibt dir 1000 $]}

#Âòîğîé êâåñò
{240}{}{Seltsamerweise scheint Thompson tot zu sein, also musst du den Auftrag nicht mehr erledigen.}
{241}{}{Seltsamerweise scheint Stryker tot zu sein, also musst du den Auftrag nicht mehr erledigen.}
{242}{}{Auftrag erledigt. Stryker und Thompson werden die Wahrheit so bald nicht herausfinden.}
{243}{}{Nun, das bedeutet, dass deine Dienste weniger bedeutend waren, als ich erwartet hatte. Deshalb bekommst du nur die Hälfte des Lohns. Und wage es ja nicht, mit mir zu diskutieren. Stryker und Thompson waren eine wichtige Kraft in dieser Stadt. Ohne sie wird Reno im Chaos versinken, und darauf sind wir noch nicht vorbereitet.}
{244}{}{Was meinst du?}
{245}{}{[Er zählt deine Bezahlung ab] Stryker und Thompson waren wichtige Kräfte in dieser Stadt. Ohne sie wird Reno im Chaos versinken, und darauf sind wir noch nicht vorbereitet.}
{246}{}{Wovon redest du?}
{247}{}{Bis vor Kurzem war meine Ranch selbstversorgend. Doch die letzten Jahre haben unsere Vorräte aufgezehrt. Wir haben nicht viel Geld für den Handel, und man beobachtet uns. Die Mächtigen unterdrücken uns von allen Seiten. Sie lassen uns nicht weiter vorankommen.}
{248}{}{Weiter?}
{249}{}{Ich habe deine Dienste in Anspruch genommen, um meinen früheren Einfluss in der Stadt zurückzugewinnen. Dafür gibt es zwei Wege: deine Rivalen schwächen oder selbst stärker werden. Den ersten Teil hast du erledigt. Jetzt ist es Zeit, sich um den zweiten zu kümmern.}
{250}{}{Was soll ich tun?}
{251}{}{Deine Aufgabe ist es, mit einer Karawane am Stadtrand einen Handel auszuhandeln. Machete hat alle Einzelheiten.}
{252}{}{Ich rede mit ihm.}

#Çàâåğøåíèå âñåé ëèíåéêè êâåñòîâ
{260}{}{Komm herein, von nun an bist du ein gern gesehener Gast in meinem Haus. Ich habe schon gehört, wie das Treffen gelaufen ist. Ich bin froh, dass du nicht nur die Waren bekommen, sondern auch meinen Ruf gerettet hast. Vielleicht werden mir diese Händler in Zukunft noch nützlich sein. Hier ist deine Bezahlung für die gut erledigte Arbeit.}
{261}{}{Gut.}
{262}{}{Komm herein, wir müssen etwas besprechen. Technisch gesehen hast du den Auftrag erledigt – ich habe die Waren bekommen und Bertolinis Casino steht ohne Ausrüstung da. Aber ich hatte gehofft, du könntest die Sache ohne Blutvergießen erledigen. Schließlich hätten mir diese Lieferanten in Zukunft nützlich sein können. Trotzdem werde ich dir die Gewalt nicht vorwerfen, denn du warst vor Ort und musstest entscheiden. Du hättest es besser machen können, aber deinen Lohn hast du dir trotzdem verdient.}
{263}{}{Gut.}
{264}{}{Komm rein, wir müssen über etwas reden: deine Feigheit und Dummheit! Glaubst du, du kannst hier mit gesenktem Kopf hereinkommen und Almosen bekommen? Du zeigst dich hier, nachdem du so ein wichtiges Geschäft vermasselt hast? Deine Idiotie ist verblüffend. Sei Gott dankbar, dass ich dich nicht längst erschossen habe! [Er wird von heftigem Husten und Würgen geschüttelt, hält sich die Brust und kommt erst nach einer Weile wieder zu sich.] Zu deinem Glück haben meine Leute den Konvoi in die Flucht geschlagen, und sie sind ins Ödland geflohen. Die Waren sind bei mir geblieben. Aus Respekt vor dem, was du früher für mich getan hast, lasse ich dich in Frieden gehen. Und jetzt verschwinde!}
{265}{}{[Gehen]}
{266}{}{Vielleicht helfe ich dir eines Tages, falls du Probleme hast. Und schließlich würde ich dich gern zu meinem Consigliere machen, wenn es dir recht ist. Das ist eine angesehene Stellung, sehr respektabel. Ich rate dir, nicht abzulehnen.}
{267}{}{Danke, Mr. Luciano. Es wäre mir eine Ehre.}
{268}{}{Danke, Boss, aber das ist mir zu viel Verantwortung. Ich muss ablehnen.}
{269}{}{[Er nickt.] Ich verstehe. Nicht jeder findet sich mit solcher Arbeit leicht zurecht. Wenn du ehrlich glaubst, dass du dafür nicht geeignet bist, kann ich das respektieren. Ich werde nicht darauf bestehen. Du kannst gehen.}
{270}{}{Auf Wiedersehen, Mr. Luciano.}
{271}{}{Ich werde all meinen Männern auf der Ranch und in der Stadt Bescheid geben. Mein Name verschafft dir in Reno gewisse Privilegien. Sprich zuerst mit Machete, er wird dir helfen.}
{272}{}{Danke, Mr. Luciano. Auf Wiedersehen.}
{273}{}{Und ich weiß deine Hilfe zu schätzen. Aber vor Kurzem habe ich herausgefunden, dass du ein doppeltes Spiel spielst. Offensichtlich treibt dich nicht der Glaube an den Menschen oder seine Ideen an, sondern der Geruch von Geld. Mein Konkurrent muss dich gut bezahlt haben. Jetzt kannst du deinen Lebensabend in Wohlstand verbringen ... Aber ich habe genug geredet. Du weißt, wo die Tür ist. Von jetzt an hält dich nichts mehr an diesem Ort.}

#Êğûøà äëÿ êîíöåğòà â Êîòòîí-êëóáå
{300}{}{Ich bin ein Vertreter der Cotton Club. Wir würden gern mit Ihnen einen Vertrag abschließen, um die Konzerte im Club zu schützen.}
{301}{}{Ein Konzert? Das sind ja erfreuliche Neuigkeiten. Wenn der Club Sicherheit braucht, kann ich welche stellen. Dafür möchte ich aber mehr Gegenleistungen erhalten. Sagen Sie dem Besitzer, dass ich ihm helfe, wenn er mir 15% of der Einnahmen jedes Konzerttages zahlt und mir außerdem den Alleinvertrag für die Versorgung des Clubs mit Lebensmitteln gibt. Außerdem muss er aufhören, Schutzgeld an Thompson zu zahlen.}
{302}{}{Wir stimmen diesen Bedingungen zu.}
{303}{}{Wir müssen über dieses Angebot nachdenken.}
{304}{}{Du hast die richtige Entscheidung getroffen. Ich schicke meine Männer, um die Einzelheiten zu klären.}
{305}{}{Danke, das wäre alles.}

#Female character
{1110}{}{Machete sagte, du wolltest mich sehen. Ich bin bereit, mir anzuhören, was du zu sagen hast.}
{1119}{}{Du verstehst es nicht, du Dummkopf. Ich will einfach nur gewinnen.}
{1130}{}{Ich dachte, du arbeitest für *mich*. Wie viele weitere böse Überraschungen hast du noch auf Lager? Auch wenn ich enttäuscht bin: Tatsache ist, dass unsere Beziehungen zu Wright schon viel zu lange angespannt sind. Sag ihm, ich bin bereit, ein Treffen zu arrangieren ... aber nur, weil ich dir vertraue.}
{1143}{}{Du lehnst ab, weil ich es bin? Na ja, wenigstens hab ich's versucht ...}
{1157}{}{Ich habe dir mit Canary schon geholfen. Warum tust du mir nicht im Gegenzug einen Gefallen?}
{1158}{}{Mr. Chase hat mir empfohlen, wegen eines Auftrags mit dir zu sprechen. Dafür wird er sicher einen Grund gehabt haben.}
{1160}{}{[Er erhebt die Stimme] Dann FINDE JEMANDEN, du Dummkopf! Beweg deinen faulen Hintern und mach etwas Arbeit. Ich schätze Menschen, die ihren Lebensunterhalt mit ihrer eigenen Hände Arbeit verdienen. Und jetzt raus aus meinem Haus.}
{1169}{}{Warte. Ich bin noch nicht fertig. Das ist wichtig: Sei höflich zu ihm und wage es ja nicht, ihn anzulügen. Wir dulden keine politischen Huren, die mit jedem flirten, den sie treffen, um sich ihren Lebensunterhalt zu sichern. Das ist alles. [Er bedeutet dir zu gehen]}
{1172}{}{Hast du den Auftrag erledigt?}
{1182}{}{Nun, da du meinem alten Freund Chase geholfen hast, können wir uns einem „ernsteren“ Gespräch widmen.}
{1195}{}{Mr. Luciano, Sie haben einen Cheyenne-Sklaven in Ihrem Besitz. Ich würde ihn gern kaufen.}
{1215}{}{Gute Arbeit! Aber ich habe gehört, dass Bertolini einen „Unfall“ hatte. Ich habe dich nicht gebeten, ihn umzubringen. Hör zu, du hast den Auftrag erledigt, also bekommst du hier deine Bezahlung: 1000 $. Aber für jemanden, der so leichtsinnig ist, habe ich keine weitere Arbeit.}
{1218}{}{Aber was ist mit deinem sekundären Ziel – dem Ruf des Casinos zu schaden? Hast du dich auch darum gekümmert?}
{1225}{}{[Er zählt 350 $ ab] Ich würde deine Dienste gern weiter in Anspruch nehmen, aber ich höre, dass du dich für die andere Seite der Barrikade entschieden hast. Also gibt es nichts mehr zu besprechen. Verschwinde.}
{1226}{}{[Er zählt 350 $ ab] Obwohl es dir gelungen ist, das Geld zu stehlen und deine Spuren zu verwischen, hast du einen großen Fehler gemacht. Du solltest Bertolini nicht töten! Ich kann nicht zulassen, dass der Mörder mit meiner Organisation in Verbindung gebracht wird. Also will ich nichts mehr mit dir zu tun haben. Verschwinde.} 
{1249}{}{Ich habe deine Dienste in Anspruch genommen, um meinen früheren Einfluss in der Stadt zurückzugewinnen. Dafür gibt es zwei Wege: Deine Rivalen schwächen oder selbst stärker werden. Den ersten Teil hast du erledigt, jetzt ist es an der Zeit, sich um den zweiten zu kümmern ...}
{1264}{}{Komm rein, wir müssen über etwas reden: deine Feigheit und Dummheit! Glaubst du, du kannst hier mit gesenktem Kopf hereinkommen und Almosen bekommen? Du zeigst dich hier, nachdem du so ein wichtiges Geschäft vermasselt hast? Deine Idiotie ist verblüffend. Sei Gott dankbar, dass ich dich nicht längst erschossen habe! [Er wird von heftigem Husten und Würgen geschüttelt, hält sich die Brust und kommt erst nach einer Weile wieder zu sich.] Zu deinem Glück haben meine Leute den Konvoi in die Flucht geschlagen, und sie sind ins Ödland geflohen. Die Waren sind bei mir geblieben. Aus Respekt vor dem, was du früher für mich getan hast, lasse ich dich in Frieden gehen. Und jetzt verschwinde!}
{1268}{}{Danke, Boss, aber das ist zu viel Verantwortung für mich. Ich muss ablehnen.}