{100}{}{Du siehst einen Einwohner von Reno.}

#Âğåìåííûå ïëàâàşùèå ğåïëèêè
{110}{}{Dieser Tag in Reno ist von der Hand des Teufels gezeichnet.}
{111}{}{Wir sitzen doch alle im selben Boot. Verstehst du das nicht?}
{112}{}{Heute Nacht wird jemand sterben. Ich spüre es.}
{113}{}{Ich kann diese Geräusche nachts nicht mehr ertragen ...}
{114}{}{Wenn ich jemals die Chance dazu bekomme, ziehe ich in die Hölle. Dort muss es besser sein als hier.}
{115}{}{Ich werde den Gedanken nicht los, dass Renos letzte Tage angebrochen sind.}
{116}{}{Wir haben keine Halsbänder, aber leben trotzdem wie Sklaven.}
{117}{}{Verdammter Krieg!}
{118}{}{}
{119}{}{}

#Ïîïû'êà 'îëêíó'ü, êîãäà íïñ ñ'îè' íà ñ'àğ'îâîì ãåêñå
{120}{}{Das ist mein Zuhause! Hör auf, mich herumzuschubsen, sonst wirst du es bereuen!}
{121}{}{Wenn ich wegen dir auch nur einen Tropfen meiner Suppe verschütte ...}
{122}{}{Such dir einen anderen Ort für so was!}
{123}{}{Lass das!}

#Ïîïû'êà çàãîâîğè'ü
{129}{}{Ich vermisse meinen Mann ... ::schluchzt:: Nachdem dieser Drogenhändler gestorben war, hatte er nirgendwo mehr seine Medizin kaufen können ...}
{130}{}{Kümmere dich nicht um sie, sie streiten ständig. Gib ihnen einfach einen Grund dazu.}
{131}{}{Wie fändest du es, wenn ich einfach in DEIN Zuhause platze und Fragen stelle?}
{132}{}{Ich habe dir nichts zu sagen.}

{133}{}{Ich würde gerne plaudern, aber ich bin schon spät dran für den Nachtclub ...}
{134}{}{Das ist ... du! Wow! Ich bin ein großer Fan – ich verpasse deine Show, wann immer ich kann, nie!}
{135}{}{Hm? Belästige mich nicht. Ich habe meine Eintrittskarte für den Nachtclub verloren und suche sie.}
{136}{}{Hey, gute Vorstellung! Ich habe sie in Moms Club gesehen. Netter Laden ...}

{137}{}{Störst du mich gerade? Ich frühstücke.}
{138}{}{Lass mich in Ruhe. Ich esse zu Mittag.}
{139}{}{Unterbrich mein Abendessen nicht.}

{140}{}{Du bist hier nicht willkommen.}
{141}{}{Ich will hier nicht mal die Türklinken anfassen! Außerdem ist mir meine Haarnadel im Waschbecken im Bad runtergefallen. Igitt!}
{142}{}{Oh, wie nett von dir! Danke!}
{143}{}{Diese Dame mag dich eindeutig.}

#Çâåçäà ñöåíû
{145}{}{Ich muss träumen! Ein Star? Hier, bei mir zu Hause?!}
{146}{}{Mein Gott, du bist es! Kann ich ein Autogramm haben?}
{147}{}{Es ist mir eine Ehre, dich kennenzulernen!}
{148}{}{Ich habe deinen letzten Auftritt gesehen. Großartig!}
{149}{}{}

# 1. LOOK, MALE (WTG)
{150}{}{Du siehst einen zerlumpt aussehenden Mann. Er wirkt gelangweilt.}
{151}{}{Du siehst einen zerlumpt aussehenden Mann. Seine Augen wirken stumpf.}
{152}{}{Du siehst einen zerlumpt aussehenden Mann. Er sieht verkatert aus.}
{153}{}{Du siehst einen zerlumpt aussehenden Mann. Er wirkt ein wenig beschwipst.}
{154}{}{Du siehst einen zerlumpt aussehenden Mann. Er wirft dir einen gereizten Blick zu und ignoriert dich dann.}
{155}{}{Du siehst einen zerlumpt aussehenden Mann. Er wirkt wütend.}

# 2. LOOK, FEMALE (WTG)
{160}{}{Du siehst eine zerlumpt aussehende Frau. Sie wirkt gelangweilt.}
{161}{}{Du siehst eine zerlumpt aussehende Frau. Ihre Augen wirken stumpf.}
{162}{}{Du siehst eine zerlumpt aussehende Frau. Sie starrt ins Leere.}
{163}{}{Du siehst eine zerlumpt aussehende Frau. Sie wirkt ein wenig betrunken.}
{164}{}{Du siehst eine zerlumpt aussehende Frau. Sie wirft dir einen gereizten Blick zu und ignoriert dich dann.}
{165}{}{Du siehst eine zerlumpt aussehende Frau. Als sie deinen Blick bemerkt, verzieht sie verächtlich den Mund.}

#Ñëàäêàÿ ïàğî÷êà â íîìåğå Ñèëüâåğ, î'âå'íûå ğåïëèêè
{200}{}{Wir sind beschäftigt.}
{201}{}{Bist du blind? Raus!}
{202}{}{Lass uns in Ruhe, sonst rufen wir den Sicherheitsdienst!}
{203}{}{Pass auf. Ich bin hier ein sehr angesehener Kunde.}
{204}{}{Glotz mich nicht an, du Freak!}
{205}{}{Ich mache keine Gruppensexnummern, klar?}
{206}{}{Raus aus meinem Zimmer!}
{207}{}{Was zum Teufel machst du hier?}
{208}{}{Unverschämtheit!}
{209}{}{Hör auf damit!}
{210}{}{Was glotzt du so?}
{211}{}{Darf ich bitten?}
{212}{}{Raus aus unserem Zimmer!}
{213}{}{Suchst du einen Dreier?}
{214}{}{Verzieh dich, du Perverser!}
{215}{}{Was ist dein Problem?}

{216}{}{Ich bin beschäftigt.}
{217}{}{Ich bin zu müde ...}
{218}{}{Verschwinde, bevor ich richtig sauer werde!}
{219}{}{Such dir eine andere.}
{220}{}{Sie gehört mir.}

#Female character
{1214}{}{Verzieh dich, Schlampe!}
