{100}{}{Du siehst eine Madam.}
{101}{}{Du siehst eine Madam namens Betty Paige.}
{102}{}{Du hast das Verhütungsmittel erfolgreich gewechselt.}
{103}{}{Du genießt eine ganze Stunde leidenschaftlichen, unermüdlichen Sex. Die Hure bringt dir alles bei, was sie weiß.}
{104}{}{Erst als das Licht angeht, bemerkst du eine schwere Hautkrankheit an den Genitalien der Prostituierten. Du kannst nur hoffen, dass du dich nicht angesteckt hast.}
{105}{}{Erst als das Licht angeht, bemerkst du eine schwere Hautkrankheit an den Genitalien der Prostituierten. Hoffentlich hat dein Schutz gewirkt.}
{106}{}{Erst als das Licht angeht, bemerkst du eine schwere Hautkrankheit an den Genitalien der Prostituierten. Doch heute hattest du Glück.}
{107}{}{Bald werden die Straßen von der Madam sprechen, die auf tragische Weise an einer plötzlichen, mysteriösen „Krankheit“ ihr Ende fand.}

#Ïî÷èíêà ôîíàğÿ
{110}{}{Danke für das Licht. Ich habe die Dunkelheit satt – manchmal kann man nachts Kunden und Schläger nicht auseinanderhalten ...}
{111}{}{ Wenn du eine meiner Mädchen willst, gebe ich dir als Dank für deine Mühe einen kleinen Rabatt.}
{112}{}{ Hm. Du bist also trotz deiner Krankheit noch hier? Ich habe dadurch viele meiner Mädchen verloren. Hier, nimm etwas Geld. Gönn dir etwas Schönes.}
{113}{}{Danke.}

{114}{}{Du weißt wirklich, wie man Kunden anlockt. Mal sehen, was du so auf Lager hast.}
{115}{}{Danke, aber heute nicht.}

{116}{}{Hey, Schätzchen, hau ab hier! Niemand würde deinen hässlichen Arsch ficken. Selbst Huren haben ihre Grenzen!}
{117}{}{Hast du dich entschieden?}
{118}{}{Ich überlege noch. Hast du Vorschläge?}
{119}{}{Nicht heute.}

#Çàêàç
{120}{}{Wenn du das nötige Geld hast, bieten wir alles, was du brauchst. Meine Mädchen geben dir jede Art von Sex, die du willst.}
{121}{}{Wie viel?}
{122}{}{Welche Arten von Sex gibt es?}
{123}{}{Danke, aber ich bin nicht interessiert.}

{124}{}{Äh ... [sie sieht dich verwundert an] ... Du weißt es nicht? Hör zu, nimm eines meiner Mädchen und finde es heraus. Taten sagen mehr als Worte, nicht wahr?}
{125}{}{Ist das ... sicher?}
{126}{}{Oh ja, ja! Natürlich! Völlig sicher ... Die gleichgeschlechtliche Variante ist am sichersten ... Jedenfalls meine ich nicht die Huren in der Nähe des Nachtclubs. Bei den Mädchen fängst du dir noch was Übles ein.}
{127}{}{Was Übles? Warum?}
{128}{}{Oh, die waschen sich nicht mal, Liebling. Die machen dich krank, sie sind *voll davon*. Aber meine Mädchen nicht – die sind alle sauber.}

{129}{}{ Dollar. Der beste Preis in der Stadt.}
{130}{}{Nur für dich, Süße, kann ich den Preis etwas senken. Sagen wir ...}
{131}{}{ Dollar. Ein Sonderpreis, nur für dich und deinen Boss.}
{132}{}{Hier ist das Geld. Es sollte sich besser lohnen.}
{133}{}{Das wird jeden Penny wert sein. Wen willst du? Sie gehören dir für eine Stunde.}
{134}{}{[Such dir eine Prostituierte aus und geh nach oben in ein Zimmer]}

{135}{}{Du scheinst gut im Geschäft zu sein. Was ist dein Geheimnis?}
{136}{}{Die Einheimischen wissen, dass wir die Besten in der Stadt sind. Es ist eigentlich eine Frage des Status, herzukommen. Und Auswärtige brauchen nach einer langen Reise jemanden, der sie gut behandelt. Aber weißt du, die Menschen sind einfach so. *Jeder* will, was wir anbieten. Das ist ein ganz grundlegender menschlicher Instinkt.}
{137}{}{Verstehe.}
{138}{}{Dann gehe ich mal.}
{139}{}{Man sagt, du hättest ein gutes Verhältnis zu Thompson. Stimmt das?}
{140}{}{Oh, Thompson ... Weißt du, er wird mich zu seiner Frau machen, wenn er diesen Krieg gewinnt ... Moment, warum erzähle ich dir das? Egal, das ist privat.}

{141}{}{Hey, schaust du dich nur um, oder ... Oh, wow, du bist es! Da bist du genau richtig. Jemand wie du verdient nur das Beste.}

#Êâåñò Òîìïñîíà
{150}{}{Mr. Thompson hat mich geschickt, um die Angriffe auf deine Angestellten zu untersuchen.}
{151}{}{[Ihr Lächeln verschwindet] Wirklich? Früher war es hier gut, bis diese verdammten Arschlöcher eingezogen sind. Sie verprügeln meine Mädchen, bedrohen mich – MICH! Ich war zuerst hier! Du solltest ihnen zeigen, wem diese Straße wirklich gehört.}
{152}{}{Was weißt du über sie?}
{153}{}{Warum glaubst du, dass sie das tun?}
{154}{}{Soll ich sie umbringen?}
{155}{}{Und warum sollte Mr. Thompson deine Probleme kostenlos lösen?}
{156}{}{Okay. Ich kümmere mich darum.}

{157}{}{Ich kenne einen von den Jungs ... Er heißt Stinky Grizzly. Ich weiß nicht, ob sie von hier sind, aber in letzter Zeit hängen sie oft hier in der Gegend herum. Sie halten sich für die ganz Großen ... Sie haben keine Ahnung, in was für einen Dreck sie sich da hineingeritten haben.}
{158}{}{Ist dir das wirklich wichtig? Hat Mr. Thompson dich geschickt, um das Problem zu lösen, oder sollst du nur einen Haufen dummer Fragen stellen?}
{159}{}{Mir ist egal, was du mit ihnen machst. Ich will nur nicht mehr sehen, wie sie sich in mein Geschäft einmischen.}
{160}{}{[Sie grinst] Oh, lass mich raten. Er hat dich nicht bezahlt, was? Und das wird er auch nicht tun, oder? Verdammt! Ich zahle ihm jede Woche pünktlich Schutzgeld, und wenn ich ihn endlich brauche, schickt er so einen Idioten wie dich. Warum überrascht mich das nicht? Hör zu, wenn du Geld verdienen willst, versuch nicht, mich auszunehmen. Zeig Rückgrat und mach verdammt noch mal deinen *Job*!}
{161}{}{Mir gefällt dein Ton nicht. Gib mir das Geld, oder ich zeige dir, wie echter Ärger aussieht.}
{162}{}{Oder was? Was willst du denn tun, hä? Ich bin die oberste Schlampe deines Bosses. Rührst du auch nur ein Haar auf meinem Kopf an, wünschst du dir, nie geboren worden zu sein.}
{163}{}{Ich bin derjenige, der dieses Problem löst. Ich entscheide, welche Informationen wichtig sind und welche nicht.}
{164}{}{Ach ja? Na schön, ich sage dir, was ich denke. Sie dachten wahrscheinlich, sie könnten sich ein Stück vom Revier unter den Nagel reißen, während sich die großen Jungs gegenseitig bekämpfen. Verdammte dumme Arschlöcher. Aber ich schätze, sie wissen nicht, wie es hier läuft, denn vor kurzem habe ich sie noch nie in der Gegend gesehen.}

{165}{}{Ich habe dein Problem gelöst.}
{166}{}{Schon? Ich schätze, zu irgendwas bist du ja doch gut. Sag Thompson, dass ich mit deiner Arbeit zufrieden bin.}

#Female character
{1117}{}{Hast du dich entschieden?}
{1161}{}{Mir gefällt dein Ton nicht. Gib mir das Geld, oder ich zeige dir, wie echter Ärger aussieht.}
{1163}{}{Ich bin derjenige, der dieses Problem löst. Ich entscheide, welche Informationen wichtig sind und welche nicht.}
