{100}{}{Du siehst eine Prostituierte.}

#Ïîäğîáíîå îïèñàíèå
{110}{}{Du siehst eine Dame der Nacht. Ihre zerlumpte Kleidung liegt verführerisch um ihren Körper.}
{111}{}{Du siehst eine Prostituierte. Sie zwinkert dir zu.}
{112}{}{Du siehst eine Prostituierte. Ihre Augen sind wie durchgebrannte Sicherungen.}
{113}{}{Du siehst eine Prostituierte. Sie riecht nach Blumen.}
{114}{}{Du siehst eine Prostituierte. Sie riecht nach Mutter.}
{115}{}{Du siehst eine Prostituierte. Ihre Brüste sehen aus, als würden sie gleich aus ihren zerlumpten Fetzen platzen.}
{116}{}{Du siehst eine Prostituierte. Sie sieht aus, als würde sie ihre Partner umbringen und auffressen.}
{117}{}{Du siehst eine Prostituierte. Sie mustert dich wie eine Juwelierin.}
{118}{}{Du siehst eine Prostituierte. Ihre zerlumpte Kleidung liegt verführerisch um ihren Körper.}

#Îòâåòíûå ğåïëèêè
{197}{}{Verschwinde! Ich darf dich nicht einmal ansehen!}
{198}{}{Vergiss es! Ich bediene keine Junkies.}
{199}{}{Interessiert? Lesbische Sachen sind billiger.}

{200}{}{Ich heiße Easy. Und du?}
{201}{}{Möchtest du Gesellschaft?}
{202}{}{Lass mich dir etwas beibringen, das nur eine Frau lehren kann.}
{203}{}{Soll ich dein Bett wärmen?}
{204}{}{Brauchst du ein Loch?}
{205}{}{Suchst du eine Freundin?}
{206}{}{Wenn du noch nie ein Mädchen aus Reno hattest, hast du wahre Liebe nie kennengelernt.}
{207}{}{Suchst du Ärger?}
{208}{}{Wie wäre es zur Abwechslung mit einer ECHTEN Frau in deinem Bett?}
{209}{}{Ich fühle mich so leer, Baby. Kannst du mir helfen?}
{210}{}{Du siehst bedrückt aus. Soll ich dich aufmuntern?}
{211}{}{Vergiss das Casino. Ich kann dir einen ECHTEN Nervenkitzel bieten!}
{212}{}{Willst du tanzen?}
{213}{}{Suchst du eine Freundin für die Nacht? Oder für zehn Minuten?}
{214}{}{Ich weiß, was du brauchst.}
{215}{}{Wird dir heiß unter dem Kragen oder woanders?}
{216}{}{Willst du zur Sache kommen?}
{217}{}{Willst du etwas Zeit mit mir verbringen?}
{218}{}{Danach können wir reden ... Aber das kostet extra.}
{219}{}{Missionarsstellung, Cowgirl, Hündchenstellung, oral, anal, Fesselspiele, S&M, Gruppensex – was immer du willst. Probier's einfach aus.}
{220}{}{Na los, Zeit ist Geld.}
{221}{}{Du willst mich? Erst bezahlen ...}
