{100}{}{Du siehst einen Kurier.}
{101}{}{Du siehst einen geheimen Kurier von Las Vegas.}

{102}{}{Der Kurier wurde ausgeschaltet. Jetzt musst du nur noch das Paket zu Big Louie bringen.}
{103}{}{Die Raider lauern im Hinterhalt.}
{104}{}{Mach dich bereit! Der Kurier kommt!}
{105}{}{Der Kurier nдhert sich. Wenn du ihn nicht verschrecken willst, solltest du dich verstecken.}
{106}{}{Du siehst den Wachmann des Kuriers.}
{107}{}{Du siehst einen brutalen Wachmann.}
{108}{}{Du siehst einen Raider-Kameraden.}
{109}{}{Du siehst deinen Partner.}
{110}{}{Hmm ... Lieber vorsichtig sein.}
{111}{}{Hier gefдllt es mir nicht – ein perfekter Ort fьr einen Hinterhalt ...}
{112}{}{Was? Ein Hinterhalt? Wo?}
{113}{}{Der Kurier ist mit dem Paket entkommen! Du hast deine Mission nicht erfuellt!}

#Сообщения над рейдерами перед нападением на курьера
{120}{}{Blutet sie aus!}
{121}{}{Schnappt ihn euch!}
{122}{}{Der gehцrt mir!}
{123}{}{Na also!}
{124}{}{Halt! Das ist ein Ьberfall!}

#Серые сообщения над спрятавшимися рейдерами
{130}{}{Ruhe! Noch nicht!}
{131}{}{Macht euch alle bereit!}
{132}{}{Sie sind ganz nah ...}
{133}{}{Vertreibt sie bloЯ nicht!}
{134}{}{Haltet eure Дrsche unten!}
{135}{}{Alle verstecken!}
{136}{}{Pass auf, er kommt!}
{137}{}{Wartet ab ...}
{138}{}{Nicht mal atmen!}
{139}{}{Bleib wachsam!}
