{100}{}{Du siehst Frank Cochran.}
{101}{}{Du siehst einen mürrischen Arbeiter in Kleidung, die mit Motoröl und Ruß befleckt ist.}

###############################################################################
#
#           Íà÷àëî äèàëîãà
#
###############################################################################

{108}{}{Ich habe noch eine Frage.}
{109}{}{Danke.}
{110}{}{Ja, was?}
{111}{}{Ich habe noch mehr Fragen.}
{112}{}{Kannst du meine Rüstung verbessern?}
{113}{}{Kannst du Waffen modifizieren?}
{114}{}{Nichts.}
{115}{}{Na gut, vergiss es.}

#Ïåğâûé ğàçãîâîğ
{120}{}{[Als du den schwach beleuchteten Raum betrittst, siehst du dessen Bewohner mit schmutzigem Gesicht und Schutzbrille. Er wirkt zugleich beschäftigt und müde. Als er dich bemerkt, hört er auf zu arbeiten.] Hm? Bist du ein Kunde oder hast du dich nur verlaufen? Man weiß nie, wer hier so auftaucht ... Aber hey, vielleicht hab ich diesmal Glück. Was kann ich für dich tun?}
{121}{}{Hallo. Darf ich fragen, auf wen ich hier in diesen Slums gestoßen bin?}
{122}{}{Frank Cochran, zu deinen Diensten. Ich bin Mechaniker und Elektriker und auch ein bisschen Büchsenmacher. Ich muss mich oft um so ziemlich alles kümmern, was mit Reparaturen zu tun hat. Und was die Slums angeht – ich nehme dir das nicht übel. Mir gefällt es hier. Wenn ich den Leuten mehr vertrauen würde, wäre ich längst irgendwo näher an den Hauptstraßen hingezogen.}
{123}{}{Verstehe. Wenn ich also etwas reparieren lassen muss, kann ich zu dir kommen?}
{124}{}{Jep, ich bin immer bereit, meiner Lieblingsbeschäftigung nachzugehen, solange du zahlst. Was brauchst du?}
{125}{}{Wie wär's mit einem Handel?}
{126}{}{Das ist kein Laden, falls du das meinst. Aber ich schätze, es schadet nicht, etwas von dem Kram loszuwerden.}
{127}{}{Sehen wir uns deinen Schrott mal an.}

###############################################################################
#
#           Âîïğîñû è îòâåòû
#
###############################################################################

{129}{}{Weißt du, wo ich hier Technologie aus Vorkriegsbunkern finden kann?}
{130}{}{Ich will nicht behaupten, dass ich mich freue, dich zu sehen, aber immerhin habe ich jemanden zum Reden.}

#Ïğî Òåäà Áàíäè
{131}{}{Ist es nicht gefährlich, hier draußen allein zu leben?}
{132}{}{Natürlich nicht. Die Straßen im Zentrum sind gefährlicher. In Reno gilt: Je weniger Zeit du mit anderen verbringst, desto sicherer bist du. Außerdem ziehen manchmal auch andere Leute hierher, die Menschenmengen nicht ausstehen können. Vor einer Weile war da ein Typ namens Ted. Blieb für sich, redete nicht viel – genau mein Schlag. Ist allerdings schon länger nicht mehr hier gewesen. Keine Ahnung, warum.}
{133}{}{Ted, hm? Das muss ich mir merken.}

#Ïğî îõğàíó â ïîäâàëå
{134}{}{Du weißt schon, dass du seltsame Nachbarn im Keller hast?}
{135}{}{Ja, die sind vor Kurzem aufgetaucht. Ich weiß nichts über sie und will es auch gar nicht wissen. Sie sitzen da ruhig herum, stören mich nicht, und damit bin ich eigentlich ganz zufrieden. Ich habe das Gefühl, dass sie dort drin etwas bewachen.}
{136}{}{Verstehe.}

#Òåğìèò
{140}{}{Ich muss einen, äh, verlassenen Tresor öffnen. Kannst du mir helfen?}
{141}{}{Von Tresorknacken hab ich keine Ahnung. In Reno gibt's jede Menge Diebe, falls du danach fragen willst. Aber ich habe Thermit in Militärqualität. Allerdings nicht viel. Und billig ist es auch nicht. Also leg das Geld bereit, wenn du es haben willst.}
{142}{}{Erzähl mir von dem Thermit.}
{143}{}{Dann lass uns handeln.}
{144}{}{Ich glaube, das brauche ich nicht.}
{145}{}{Ich hab's von ein paar Prospektoren bekommen, die von einem Armeestützpunkt zurückkamen. Sie hielten es für Sprengstoff. Also hab ich ein paar Tests gemacht. Es stellte sich heraus, dass das Zeug aus einer Mischung verschiedener Oxide, Peroxide und irgendwelcher Chemikalien besteht, die ich nicht verstanden habe. Sieht aus wie gewöhnliches Thermit, aber es gibt einen Haken: Es erzeugt keine Flammen, sondern eine verdammte Hitze. Es frisst sich durch so ziemlich alles, auch Metall, und das völlig geräuschlos. Perfekt, um in einen „verlassenen“ Tresor einzudringen.}
{146}{}{Hast du nur dieses eine Päckchen?}
{147}{}{[Er kneift einen Moment die Augen zusammen und zuckt dann mit den Schultern] Eigentlich hab ich noch eins. Ich wollte es für schlechte Zeiten aufheben, aber ach, was soll's. Ich weiß, dass du es ernst meinst, also verkauf ich's dir.}
{148}{}{Jep, das war's. Ich hab es nicht selbst hergestellt, weißt du. Wenn es weg ist, ist es weg.}

#Âîëò-Òåê
{149}{}{Wie die Schutzbunker aus der Vorkriegszeit? Wir haben zwei in Reno. Einer unter dem Rathaus, den Thompson als Hauptquartier nutzt, und einer unter dem Stadtpark, neben der alten Bowlingbahn. Stryker hat ihn allerdings abgeschlossen.}

###############################################################################
#
#           Ïğåññ äëÿ ñíàğÿæåíèÿ ïàòğîíîâ
#
###############################################################################

#Ïğåññ ïàòğîíîâ
{150}{}{Kannst du Munition herstellen?}
{151}{}{Nee, das mache ich nicht. So schwer ist es zwar nicht, aber dafür braucht man eine Munitionspresse.}
{152}{}{Kannst du mir dann eine Munitionspresse bauen? Ich bezahle dafür.}
{153}{}{Schon gut.}
{154}{}{Hmm ... Ja, das kriege ich hin. Ich brauche 10.000 Mäuse und ein paar Tage Arbeit dafür.}
{155}{}{Das ist ein fairer Preis. Ich gebe dir 5.000 Dollar im Voraus und den Rest, wenn das Werkzeug fertig ist.}
{156}{}{Bis später.}

{157}{}{Wow, das ist ganz schön teuer! Können wir darüber verhandeln?}
{158}{}{Ich müsste nicht so viel verlangen, wenn ich anständiges Werkzeug hätte. Meins ist total abgenutzt, mit dem Zeug hier zu arbeiten ist echt beschissen. Besorg mir so einen „Snap-Off“-Superwerkzeugkasten, dann bin ich schneller fertig und verlange nur 2.000 Mäuse. Abgemacht?}
{159}{}{Ich hab zufällig gerade einen hier! Also, abgemacht?}

{160}{}{Willst du mich verarschen? Ich bin nicht blind, weißt du.}
{161}{}{Reicht nicht? Dann komme ich später wieder.}

{162}{}{Wie du meinst. Komm in ein paar Tagen wegen der Presse wieder.}
{163}{}{Bis dann.}

{170}{}{Wie läuft's mit meiner Munitionspresse?}
{171}{}{Sie ist fertig. Ich hab sie sicherheitshalber versteckt. Gib mir erst das Geld, dann hole ich sie für dich.}
{172}{}{Hier sind die 5.000 Mäuse.}
{173}{}{Es wäre einfacher, dich umzulegen und sie selbst zu suchen! [Attack]}
{174}{}{Warte hier, ich komme mit dem Geld zurück.}
{175}{}{Ich habe gerade kein Bargeld dabei, aber vielleicht interessiert dich dieser Superwerkzeugkasten?}

#Îáíîâëåíèå ïğåññà ïàòğîíîâ
{180}{}{Mit dieser Munitionspresse kann ich manche Kaliber nicht herstellen.}
{181}{}{Ja, mit so einem Ding kannst du nicht alles machen. Aber wenn ich so darüber nachdenke, könnte ich sie für dich verbessern.}
{182}{}{Verbessern? Wie denn?}
{183}{}{Ach, vergiss es. So ist sie schon in Ordnung.}
{184}{}{Ich kann weitere Aufsätze und Einsätze hinzufügen. Dann kannst du mehr Kaliber herstellen und sogar panzerbrechende Munition pressen. Sie wird schwerer, aber es lohnt sich. Sagen wir ...}
{185}{}{ Dollar.}
{186}{}{Hier ist das Geld. Fang an.}
{187}{}{Fertig! Es ist immer schön, ein Meisterwerk entstehen zu sehen.}
{188}{}{Danke!}

#Ïî÷èíêà áîğòîâîãî êîìïüşòåğà
{190}{}{Kannst du diesen Bordcomputer reparieren?}
{191}{}{[Er nimmt den Computer hoch und betrachtet ihn, als hätte er noch nie etwas Vergleichbares gesehen. Eine Weile dreht er ihn in den Händen, fährt nachdenklich mit dem Finger über die staubige Platine, atmet den Geruch der Kondensatoren ein und kratzt sich dann am Hinterkopf] Ja, das kriege ich hin. Warum nicht? Sieht aus, als würden ein paar Teile fehlen. Ist aber kein großes Problem. Für einen kleinen Obolus kümmere ich mich darum. 2000 sollten reichen.}
{192}{}{Hier ist das Geld, aber sei vorsichtig. Man kann ihn nicht ersetzen und ich brauche ihn wirklich dringend. Eine zweite Chance gibt es nicht.}
{193}{}{Ich überleg's mir.}
{194}{}{Du hast einen Weg gefunden, den Zug in Salt Lake City zu reparieren.}

#Ïî÷èíêà êèÿ Áåğòîëèíè
{195}{}{Ich, äh, habe meinen Lieblingsqueue kaputtgemacht. Kann man den reparieren?}
{196}{}{Ja, kein Problem. Der ist leicht genug zusammenzubauen. Du musst das Metallgelenk anfertigen und den Queue zurechtschneiden. Am schwierigsten ist die Balance. Du musst das richtige Gewicht, die Länge und die Krümmung berücksichtigen. Zum Glück war ich früher ein ziemlich guter Billardspieler und habe sogar ein- oder zweimal mit Mr. Chase gespielt. Der ist ein echter Meister des Spiels. Hoffentlich sind meine Fähigkeiten noch nicht zu eingerostet. Für 200 Bucks repariere ich ihn dir.}
{197}{}{Abgemacht. Hier sind das Geld und der Queue.}
{198}{}{Na ja, wenn es wichtiger ist, ein guter Spieler als ein Mechaniker zu sein, versuche ich, ihn selbst zu reparieren. Auf Wiedersehen.}
{199}{}{Fertig! Du wirst keinen Unterschied bemerken.}

###############################################################################
#
#           Çàêàçû íà ğåìîíò
#
###############################################################################

#Èìèòàòîğû ìîíåò äëÿ àâòîìàòîâ ÿäåğ-êîëû
{200}{}{Ich brauche Metallplatten in Münzgröße und -form.}
{201}{}{Klar. Wie viele?}
{202}{}{500}
{203}{}{400}
{204}{}{300}
{205}{}{200}
{206}{}{100}
{207}{}{Eigentlich, vergiss es.}

{208}{}{Klar. Ich mache es für }
{209}{}{Hier ist das Geld.}
{210}{}{Nein, danke.}
{211}{}{[Eine Stunde später schleppt ein erschöpfter Mechaniker einen Sack voller Platten herein] Äh ... Wir haben ein kleines Problem. Ich habe beim Anfertigen den Bohrer geschrottet, daher kann ich keine weiteren herstellen. Das hier ist alles, was ich geschafft habe.}
{212}{}{Na ja, immerhin ist es etwas.}
{213}{}{ Dollar.}

#Øàéåíñêèé âîäîñáîğíèê
{220}{}{Kannst du den Wassertank der Cheyenne in Lovelock reparieren?}

{221}{}{Fick mich quer! Ist das dein Ernst? Da musst du dich schon sehr, sehr ins Zeug legen, um mich zu überzeugen. Schließlich bin ich ein großartiger Mechaniker, ich habe die halbe Stadt repariert. Ich muss mir nicht den Arsch aufreißen, um den Berg hochzukraxeln und für ein paar Wilde einen dreckigen Regenwassersammler zu flicken.}
{222}{}{ Dollar.}
{223}{}{Meine Güte, ich hab doch nur gefragt. Schon gut.}
{226}{}{Wären }
{227}{}{Dollar deine Mühe wert?}

{228}{}{[Er kratzt sich an einer unrasierten Wange] Ja ... Na gut, meinetwegen. Aber ich will das Geld im Voraus.}
{229}{}{Hier, nimm es. Keine krummen Dinger!}
{230}{}{Eigentlich habe ich es mir anders überlegt. Du kannst wieder weiter nichts tun.}
{231}{}{[Er zählt das Geld sorgfältig und nickt dann] Ja, ja. Ich kümmere mich darum. Keine Sorge.}
{232}{}{Gut.}

{233}{}{Ich arbeite nicht umsonst.}
{234}{}{Du willst mich wohl verarschen!}
{235}{}{Träum weiter.}

#Ïğåäîõğàíèòåëü äëÿ íàñîñà â Äæåğëàêå
{240}{}{Ich brauche eine Sicherung für eine Wasserpumpe.}
{241}{}{Kein Problem. Hab noch eine in meinem Vorrat. [Er kneift die Augen zusammen] Für 300 Mäuse gehört sie dir.}
{242}{}{Bist du verrückt?! So viel Geld für so ein kleines Ding?}
{243}{}{Hier ist das Geld. Gib mir die Sicherung.}
{244}{}{Ich suche weiter.}

{245}{}{[Er zuckt mit den Schultern] Heutzutage ist nichts umsonst. Aber ich hätte eine Alternative, falls du interessiert bist.}
{246}{}{Ich höre.}
{247}{}{Nein, ich bezahle. Hier ist das Geld.}
{248}{}{In letzter Zeit sind hier jede Menge Hunde unterwegs. Ich glaube, es ist Paarungszeit, sie sind geil und aggressiv. Die Köter aus ganz Reno scheinen sich hier zu einer Party zu versammeln. Ich habe also sogar nachts Angst, zum Pinkeln rauszugehen. Bring die Hündinnen um, dann gehört die Sicherung dir.}
{249}{}{Abgemacht.}
{250}{}{Gut.}
{251}{}{Danke für die Sicherung.}

{252}{}{Wegen der Sicherung ...}
{253}{}{Dreihundert Mäuse. Und spar dir den Versuch, mich auszurauben. Sie ist versteckt, wo du sie niemals finden wirst.}
{254}{}{Das ist ganz schön teuer. Kann ich irgendetwas tun, um den Preis zu drücken?}
{255}{}{Ich habe die Hündinnen getötet. Wo ist meine Belohnung?}
{256}{}{Ich zahle. Hier ist das Geld.}
{257}{}{Hat sich gelohnt. Danke für die Hilfe.}
{258}{}{Gern geschehen.}
{259}{}{Großartig.}
{260}{}{Na ja, dann geh ich mal.}
{261}{}{Wie wär's, wenn ich stattdessen eine Kugel ausgebe?}
{262}{}{Ha! Das glaub ich verdammt noch mal nicht. Ohne mich findest du meinen Vorrat nie.}
{263}{}{Hmm ...}

#Àïãğåéä ïèêàïà:
{270}{}{Hast du schon mal an einem fahrtüchtigen Auto gearbeitet?}
{271}{}{Wie jeder Mechaniker habe ich an Autos gearbeitet. Damit meine ich, dass ich eine Menge davon auseinandergebaut habe, ohne zu verstehen, wie sie funktionieren. Außerdem sind funktionstüchtige Ersatzteile fast unmöglich zu finden.}
{272}{}{Hast du irgendwelche von diesen Ersatzteilen?}
{273}{}{Das wollte ich wissen.}

{274}{}{Ja, ich hab eine gute Sache – einen Kraftstoffregler. Wenn du ein funktionierendes Auto hättest, könnte ich versuchen, ihn einzubauen. Soweit ich mich erinnere, soll er den Batterieverbrauch senken.}
{275}{}{Gute Idee. Denn zufällig habe ich ein funktionierendes Auto.}

{276}{}{[Seine Augen werden groß] Wirklich?! Du hast ein funktionierendes Auto? Kann ich es sehen?}
{277}{}{Es steht draußen. Also, wegen dem Ersatzteil ...}
{278}{}{Es ist nicht hier. Vielleicht fahr ich später damit vorbei.}

{279}{}{Klar! Wofür soll ich das Ding sonst verwenden? Ich baue ihn dir für, sagen wir ... 1000 Dollar ein.}
{280}{}{Hier ist das Geld. An die Arbeit.}
{281}{}{Jetzt gerade nicht.}
{282}{}{Ich glaube, ich bring dich um und baue das Teil selbst ein!}
{283}{}{Kraftstoffregler. Bau ihn in einen Automotor ein, und die Batterie hält doppelt so lange. Ich verkaufe und installiere ihn für 1000 Dollar.}

{284}{}{Was war das noch mal für ein Autoteil, von dem du gesprochen hast?}
{285}{}{[Er grinst] Nee, du machst Witze. Das glaub ich nicht. Und du findest es nicht nur ohne mich nicht, sondern könntest auch nie herausfinden, wie man es richtig einbaut. *Ich* bin hier der Mechaniker, falls du das noch nicht kapiert hast.}
{286}{}{Ich meine es verdammt ernst. Und rate mal, was jetzt kommt! [Angriff]}
{287}{}{Hmm. Verstehe. Gut, hier ist das Geld. Ich warte, bis du fertig bist.}
{288}{}{Hmm. Verstehe. Dann geh ich das Geld holen.}

{289}{}{Der Kraftstoffverbrauch deines Autos ist jetzt viel effizienter als vorher!}

#×àñòü îò ìàøèíû
{290}{}{Was kannst du mir über diesen Teil erzählen?}
{291}{}{Hmm ... Das ist ein Kraftstoffregler. Wird in Automotoren verwendet. Er ist unersetzlich; ohne ihn springt das Auto nicht an. Weißt du, vor einer Weile hat ein Karawanenhändler vom Wind des Krieges nach diesem Teil gefragt. Vielleicht kannst du dort etwas damit anfangen.}
{292}{}{Wind des Krieges? Daran sollte ich mich erinnern.}

###############################################################################
#
#           Óëó÷øåíèÿ
#
###############################################################################

#Àïãğåéä îğóæèÿ
{300}{}{[Er kratzt sich an der unrasierten Wange] Äh. Ich kenne mich nicht mit jeder Waffe aus, aber bei Standardsachen - Pistolen, Gewehren und Schrotflinten - ist für mich alles ziemlich einfach. Erwarte aber nicht zu viel.}

{301}{}{[Magnum-Revolver zeigen]}
{302}{}{desert eagle zeigen}
{303}{}{[Jagdgewehr zeigen]}
{304}{}{[Schrotflinte zeigen]}
{305}{}{[Elektroschocker zeigen]}
{306}{}{[Vorschlaghammer zeigen]}
{307}{}{[Speer zeigen]}
{308}{}{}
{309}{}{Schon gut.}
{310}{}{ Dollar.}
{311}{}{Ich hätte da ein paar Ideen. Gib mir }
{312}{}{ Dollar, dann verbessere ich sie für dich.}
{313}{}{Hier ist das Geld. Fang an.}
{314}{}{Ich biete es ja nur an.}
{315}{}{Ich habe noch eine Waffe, an der du arbeiten sollst.}
{316}{}{Reden wir über etwas anderes.}
{317}{}{Bis dann.}
{318}{}{Was soll das, ein Witz?}
{319}{}{Äh, schon gut ...}

{320}{}{Ich kann dir einen Speedloader basteln. Das macht dann }
{321}{}{Verdammt, das ist eine verdammt schicke Waffe! Ich glaube, ich kann ihr Magazin verlängern. Das macht dann }
{322}{}{Ja, mit denen habe ich schon gearbeitet. Ich kann ein Zielfernrohr darauf montieren, wenn du willst. Für gerade mal }
{323}{}{Du willst sie doch bestimmt abgesägt haben, oder? Das habe ich meistens gemacht. Dadurch wird sie leichter und lässt sich einhändig abfeuern. Du bekommst mehr Feuerkraft, aber triffst damit nichts, was weiter als eine Armlänge entfernt ist. Wenn du willst, macht das dann }
{324}{}{Ja, ich erinnere mich, dass ich solche Dinger für Farmer repariert habe, als es noch welche in der Nähe von Reno gab. Ich kann sie neu verkabeln, damit sie einen stärkeren Stromschlag abgibt. Für }
{325}{}{Das Ding hat schon bessere Tage gesehen ... Es braucht etwas Arbeit, aber ich kann es wieder herrichten. Das kostet dich }
{326}{}{Brauchst du eine geschärfte Klinge? Kein Problem. Das mache ich für }
{327}{}{Na toll. Hier kann ich nichts machen ... Wenn ich so darüber nachdenke, kann ich dir einen Patronengurt anfertigen. Das ist ziemlich einfach und kostet dich nur }
{328}{}{Ein verdammter Vorschlaghammer, was willst du denn? Hm ... Ich könnte wohl Stacheln daran anbringen. Interesse? Das kostet dich }
{329}{}{}

{330}{}{[Nach ein paar Stunden ist der Mechaniker mit seiner Arbeit fertig und gibt dir deine verbesserte Waffe zurück]}
{331}{}{Danke. Ich habe noch eine Waffe für dich, falls du Interesse hast.}
{332}{}{Danke.}

{335}{}{[„Savage“ zeigen]}
{336}{}{[Nelsons kapter Schrotflinte zeigen]}

#Äèíàìèò
{350}{}{Arbeitest du mit Sprengstoff?}
{351}{}{Ein paar grundlegende Arbeiten kann ich erledigen. Was hast du im Sinn?}
{352}{}{Kannst du ein Bündel Dynamit in einzelne Stangen zerlegen?}
{353}{}{Kannst du einzelne Dynamitstangen zu einem Bündel zusammenbinden und einen Zünder anbringen?}
{354}{}{Nein, ich frage nur.}
{355}{}{Erledigt.}
{356}{}{Danke.}
{357}{}{Klar. Ich brauche das Dynamit und }
{358}{}{Klar. Ich brauche 5 Stangen und }
{359}{}{ Dollar.}

#Àïãğåéä áğîíè
{400}{}{Klar. Ich fertige viel Rüstung für Karawanenhändler an. Bisher habe ich nur mit Leder gearbeitet, aber ich probiere gern etwas anderes aus. Bring es einfach her, dann sehen wir, was ich machen kann.}
{401}{}{Ich überleg's mir.}
{402}{}{Ich möchte dir noch eine andere Rüstung zeigen.}
{403}{}{Ich bin hier.}
{404}{}{Du musst sie ausziehen, bevor ich etwas damit machen kann.}
{405}{}{Oh, stimmt, natürlich ...}
{406}{}{[Nach einiger Zeit bringt der Mechaniker deine verbesserte Rüstung zurück und nickt zufrieden vor sich hin] Verdammt, bin ich gut.}
{407}{}{Das ist saubere Arbeit!}
{408}{}{Ich möchte dir noch eine andere Rüstung zeigen.} #Fix

{410}{}{Kannst du mit dieser Lederjacke etwas anfangen?}
{411}{}{Kannst du eine Lederrüstung verbessern?}
{412}{}{Und eine Metallrüstung?}
{413}{}{Ich habe die Rüstung und ein paar Platten dafür. Kannst du damit etwas anfangen?}

{420}{}{Ich kann eine Stahlplatte anbringen. Bequem wird sie nicht sein – und leicht auch nicht –, aber sie schützt dich. Außer du spielst mit Elektrizität, heh. Das kostet dich }
{421}{}{Ja. Ich kann ein paar Stahlplatten einarbeiten und hier etwas Verstärkung anbringen ... Das gibt eine gute Rüstung. Ich berechne dir }
{422}{}{Verdammt ja, ich kenne mich mit Metall aus. Ich poliere es, bis es glänzt, flicke die Löcher – nicht mal der Hersteller wird es wiedererkennen! Das macht dann }
{423}{}{Scheint nicht allzu kompliziert. Ich mach's für }

#Female character
{1141}{}{Von Tresorknacken hab ich keine Ahnung. In Reno gibt's jede Menge Diebe, falls du danach fragen willst. Aber ich habe Thermit in Militärqualität. Allerdings nicht viel. Und billig ist es auch nicht. Also leg das Geld bereit, wenn du es haben willst.}
{1230}{}{Eigentlich habe ich es mir anders überlegt. Du kannst wieder weiter nichts tun.}
{1262}{}{Ha! Das glaub ich verdammt noch mal nicht. Ohne mich findest du meinen Vorrat nie.}