{100}{}{Du siehst einen starken Mann.}
{101}{}{Du siehst einen kräftigen Mann. Er dürstet nach deinem Blut!}
{102}{}{Du siehst eine kräftige Frau.}
{103}{}{Du siehst eine kräftige Frau. Sie dürstet nach deinem Blut!}

{110}{}{Du hast gewonnen!}
{111}{}{Du hast gewonnen! Das fühlt sich großartig an!}
{112}{}{Du hast einen starken Gegner besiegt. Was für ein Gefühl!}
{113}{}{Du hast einen äußerst gefährlichen Gegner besiegt. Du fühlst dich wie auf dem Gipfel der Welt!}
{114}{}{Du erhältst den Erfolg „Legende des New Reno-Rings“.}
{115}{}{Du erhältst den Erfolg „Legende des Las Vegas-Rings“.}
{116}{}{So viele zermürbende Kämpfe überstanden zu haben, hat deine Ausdauer verbessert.}