{100}{}{Du siehst Michael, den Barkeeper.}
{101}{}{Das ist Michael. Sein Name steht auf einem abgewetzten Namensschild an seinem Hemd.}

{102}{}{Möchtest du vor dem Kampf etwas trinken?}
{103}{}{Apropos Kämpfe: Kann ich eine Wette platzieren?}
{104}{}{Apropos Kämpfe: Kann ich mitmachen?}
{105}{}{Klar, zeig mir, was du hast.}
{106}{}{Nein, ich muss los.}
{107}{}{Das war's?}
{108}{}{Noch eine Frage.}
{109}{}{Tschüss.}

{110}{}{Dafür haben wir jemanden. Sprich vor Kampfbeginn mit ihm.}
{111}{}{Das bezweifle ich ... Aber das ist nicht meine Entscheidung. Nimm den Gang zu deiner Rechten und geh dann hoch zum Büro des Bosses. Rede mit ihm.}
{112}{}{Wer ist gerade im Ring?}
{113}{}{Keine Ahnung. Irgendwelche Stammesleute aus dem Ödland. Sklavenhändler bringen von Zeit zu Zeit welche her. Sie werden so schnell ersetzt, dass ich mir nicht mal ihre Namen zu merken versuche. Und wozu auch? Sie sind bloß Frischfleisch. [Er zuckt gleichgültig mit den Schultern]}
{114}{}{Ich suche das Mädchen auf diesem Bild. Hast du sie hier schon mal gesehen?}
{115}{}{Nö, glaube nicht, aber ihr Körper kommt mir irgendwie bekannt vor ... Komisch, wie kann einem ein Körper bekannt vorkommen? [Er verzieht das Gesicht und kratzt sich am Kopf] Vielleicht kommt sie aus dem Nachtclub? Oh ja! Bin mir nicht ganz sicher, aber ich glaube, ich hab sie dort tanzen sehen. So ein Körper ... Jaaa ... [Sieht aus, als würde er gleich anfangen zu sabbern]}

{116}{}{Ich habe gehört, dass hier ein paar Dealer Stoff verkaufen. Ich brauche dringend welchen, verstehst du?}
{117}{}{Bist du bescheuert? Von welchen Dealern redest du?}
{118}{}{Von denen da. [Zeig ihm die Notiz]}
{119}{}{Hmm ... Du hast recht, ich weiß es selbst nicht mal. Jackson muss sich geirrt haben.}
{120}{}{Ah, ja, DIE da. Zwielichtige Typen, die früher hier herumlungerten. Aber Mr. Bishop hat sie alle rausgeworfen.}
{121}{}{Verstanden.}

{122}{}{Schön, dich zu sehen, Champion.}

#Female version:
{1102}{}{Möchtest du vor dem Kampf etwas trinken?}
{1122}{}{Schön, dich zu sehen, Champion.}
