{100}{}{Du siehst Bishop.}
{101}{}{Du siehst einen Geschäftsmann mit sehr ernstem Gesichtsausdruck.}

#×èòåğñòâî:
{102}{}{Hör auf zu schummeln, du Mistkerl! Ich schwöre, das muss das letzte Mal sein ... }
{103}{}{[Kampf beginnen.]}
{104}{}{[Verlassen.]}

#Ïåğâûé ğàçãîâîğ:
{110}{}{[Er mustert dich abschätzend.] Hm. Was brauchst du, Kumpel?}
{111}{}{Du bist also derjenige, der diese Kämpfe organisiert?}
{112}{}{Nichts. Bis später.}

{113}{}{Allerdings. Wenn du ein paar Männer sehen willst, die sich gegenseitig die Fresse zu Brei schlagen, bist du hier genau richtig. Mein Name ist Jordan Bishop. Ich leite diesen Ring, und hier passiert nichts ohne meine Erlaubnis. Also, was willst du von mir?}
{114}{}{Erzähl mir von den Regeln des Rings. Ich überlege, vielleicht mitzumachen.}
{115}{}{Ich möchte auf einen Kämpfer wetten.}
{116}{}{Wo hast du die Kämpfer her, die gerade im Ring stehen?}
{117}{}{Geschäft? Ich wollte nur reden. Na ja, wenn du so beschäftigt bist, gehe ich wohl besser ... }

{118}{}{Ich leite diesen Ring und habe keine Zeit für dumme Fragen. Ich hoffe, du bist diesmal wegen eines Geschäfts hier?}

{120}{}{Ach, das. Ich nehme keine Wetten an. Dafür ist ein anderer Kerl in der Halle zuständig. Such ihn.}
{121}{}{Nur ein paar gewöhnliche Sklaven. Für die Schwergewichte taugen sie nicht wirklich. Also tanzen sie ein bisschen, es ist kein ernsthafter Kampf. Warum fragst du?}
{122}{}{Du?! Hör zu, unsere Bedingungen sind nichts für dich, sie sind zu ... hart. Hier gibt es nur eine Kampfregel: keine Waffen. Die Gegner kämpfen bis zum Tod, bis zu ihrem letzten verdammten Atemzug. Natürlich kann man einen Kämpfer am Leben lassen, aber im Ring zeigt niemand je so viel Gnade. Wenn du mitmachen willst, solltest du auf so etwas gefasst sein.}
{123}{}{Na und? Bin ich nicht gut genug? Schade ... }
{124}{}{[Er mustert dich aufmerksam] Hm. Unter der Kleidung kann man dich kaum richtig einschätzen ... Aber ich gebe dir gern eine Chance. Doch ich warne dich: Bei unseren Kämpfen gibt es keinerlei Einschränkungen! Niemand hält sich zurück, und in diesem Ring sterben immer wieder Leute. Die einzige Bedingung lautet: keine Waffen. Ich rate dir, dich im Trainingsraum aufzuwärmen. Dort gibt es einen verdammt guten Trainer, der dir helfen kann.}
{125}{}{Wie viel verdiene ich, wenn ich gewinne?}
{126}{}{Das hängt davon ab, wie viel Geld die Zuschauer bei den Wetten verlieren. Die Einsätze werden während des Kampfes gemacht. Sobald das Personal seinen Anteil genommen hat, geben wir dir den Rest.}
{127}{}{Wer werden meine Gegner sein?}
{128}{}{Fangen wir erst mal damit an, zu sehen, wie du dich gegen die Sklaven schlägst. Wenn dem Publikum gefällt, was du draufhast ... Nun, wir haben auch ein paar Profis, aber du musst noch besser werden, bevor du gegen sie antreten kannst. Keine Sorge, die machen dir die Hölle heiß, falls du je mit ihnen in den Ring steigst!}
{129}{}{Verlockendes Angebot!}
{130}{}{Dann mach dich kampfbereit. Unsere ernsthaften Kämpfe finden normalerweise abends um 21:00 Uhr statt.}
{131}{}{Kann's kaum erwarten!}

#Ïîäãîòîâêà ê áîş è âîçíàãğàæäåíèå
{132}{}{He, bist du bereit für einen Kampf, Sportler?}
{133}{}{Verdammt, ja!}
{134}{}{Jetzt nicht.}

{135}{}{Ausgezeichnet! Der Trainer wärmt dich auf. Mach sie fertig!}
{136}{}{[Warte bis 21:00 Uhr und steig in den Ring.]}

{137}{}{Hey, wo zum Teufel steckt unser Champion? Oh, da bist du ja! Hier ist dein Geld. [er gibt dir deinen Gewinn] Wenn du für den nächsten Kampf bereit bist, sag mir Bescheid.}
{138}{}{In Ordnung.}

{139}{}{Hey, Champion! Bist du hier, um dir den nächsten Adrenalinkick zu holen?}
{140}{}{Aber sicher! Ich bin bereit zu kämpfen.}
{141}{}{Nein, ich bin nur gekommen, um den Sklavenkämpfen zuzusehen.}

{142}{}{Tut mir leid, Champion, wir sind noch nicht bereit für den nächsten Kampf. Komm morgen wieder, ja?}
{143}{}{So viel Entschlossenheit gefällt mir! Na los, dann!}
{144}{}{Du hast wahrscheinlich bemerkt, dass wir den Druck im Ring erhöhen und dir stärkere Gegner vorsetzen. Aber diesmal wird es eine *echte* Herausforderung für dich. Für diesen Kampf zahle ich mehr. Du solltest besser ordentlich austeilen!}
{145}{}{Ich habe für deinen Gegner heute Abend eine Spitzenprämie gezahlt. Ich schätze, sie haben sogar unten in Vegas von dir gehört, denn dieser hier ist extra von dort gekommen, um gegen dich zu kämpfen. Sei gewarnt – mit dem ist nicht zu spaßen. Mein Rat: Denk an *all* deine Schwächen im Kampf. Diesmal werden sie im Ring zu einem gewaltigen Problem.}
{146}{}{Hättest du dich nur sehen können! Das war der beste linke Haken, der je in meinem Ring geschwungen wurde! Mit solchen Tricks verdienen wir eine Menge Geld. Das Publikum war außer sich, die ganze Stadt wollte rein, um zuzusehen! Wie auch immer, hier ist dein Geld. [er gibt dir deinen Gewinn] Wenn du bereit bist, komm vorbei, dann arrangieren wir einen weiteren Kampf ... ZU DEINEN EHREN!}
{147}{}{Ich bin schon vom Zusehen dieses unglaublichen Kampfes erschöpft! Das war ... Das war der Wahnsinn! Unser Ring ist der angesagteste Ort der Stadt, Champion, und das haben wir alles dir zu verdanken. [er gibt dir deinen Gewinn] ...Aber jetzt müssen wir über die schlechte Nachricht reden.}
{148}{}{Was ist los? Sag's geradeheraus!}
{149}{}{Das Publikum liebt dich so sehr, dass es Haus und Hof auf dich verwettet ... und gewinnt! Verstehst du, worauf ich hinauswill?}
{150}{}{Oje ...}
{151}{}{Du bist so gut, dass wir mit dir kein Geld verdienen können. Jeder Kampf ist eine sichere Wette. Du ruinierst uns, Champion! Unter solchen Umständen können wir kein Geld verdienen.}
{152}{}{Moment mal, der Ring lebt also von verlorenen Wetten?}
{153}{}{Na klar! Was denn sonst? Na ja, da wäre noch die Bar, aber das ist kaum der Rede wert im Vergleich zu dem, was wir mit den Wetten verdienen. Und einige Fans gehen danach im Kasino spielen, aber auch das bringt nur begrenzt was.}
{154}{}{Jemand hat wohl nicht genug Leute für die Werbung!}

{155}{}{Ja, also ... Ich habe im Ring schon echte Schmerzen gesehen, aber nichts, was schmerzhafter wäre als das hier. Du hast uns groß gemacht, aber du wirst uns ruinieren. Es tut mir leid. Du bist der Beste ... Und du musst gehen.}
{156}{}{Und alles lief so gut ... }

{157}{}{Tut mir leid, Sportfreund. Manche Kämpfe kann man einfach nicht gewinnen.}

#Óòî÷íåíèå, ÷åãî íå õâàòàåò äëÿ ó÷àñòèÿ íà ğèíãå:
{158}{}{Warum darf ich nicht mitmachen?}
{159}{}{Erstens sind deine Arme wie Nudeln. Das Publikum mag keine kurzen Kämpfe, und genau das wäre deiner. Zweitens sehe ich schon an deinen Bewegungen, dass du keine Ahnung vom Boxen hast. Verstehst du, worauf ich hinauswill, Nudelarme?}
{160}{}{Vielleicht beherrschst du die Technik des waffenlosen Kampfes, aber wir wählen starke Gegner aus, und du siehst nicht stark genug aus. Egal, ob du gewinnst oder verlierst, der Kampf wäre schnell vorbei. Das mögen unsere Fans nicht.}
{161}{}{Stark genug siehst du aus, aber das heißt nicht, dass du kämpfen kannst. Hier gibt's keine besoffene Schlägerei. Sprich mit unserem Trainer, der zeigt dir, wie's läuft.}
{162}{}{Alles klar, danke.}

{163}{}{Warte mal. Ich habe gehört, Mr. Bertolini sucht jemanden für eine „Spezialaufgabe“. Ich weiß nicht, was zum Teufel er vorhat, aber wenn du in dieser Stadt Geld und Ansehen verdienen willst, geh zu ihm. Sag ihm, dass ich dich geschickt habe, dann versteht er.}
{164}{}{Danke, Mr. Bishop. Ich werde darüber nachdenken.}

#Áîé íà ğèíãå:
{200}{}{LASST DEN KAMPF BEGINNEN!}
{201}{}{Du hast gewonnen! Das war großartig!}

{202}{}{ICH BEISS DIR DIE OHREN AB!!!}
{203}{}{BANZAI!!!}
{204}{}{GRRR!!!}
{205}{}{ES IST ZEIT, DICH ZU ERLEDIGEN!!!}
{206}{}{HRRR!!!}
{207}{}{FLEH UM GNADE, WELPE!!!}
{208}{}{NUR EINER VON UNS GEHT HIER WIEDER RAUS!!!}
{209}{}{DU BIST SCHON TOT!!!}
{210}{}{ICH BIN DIE MACHT!!!}
{211}{}{NA, NA!!!}
{212}{}{ZITTERE, ABSCHAUM!!!}
{213}{}{ICH HÄNGE MIR DEINE ZÄHNE UM DEN HALS!!!}
{214}{}{ICH MACHE AUS DEINEN KNOCHEN EINEN TALISMAN!!!}
{215}{}{DU BIST NIEMAND!!!}
{216}{}{MIT DEM GESICHT NACH UNTEN!!!}
{217}{}{ARSCH HOCH!!!}
{218}{}{NOCH SO EIN SCHWÄCHLING!!!}
{219}{}{NOCH SO EIN ARSCHLOCH!!!}
{220}{}{VERRECK, DU DRECKSKERL!!!}
{221}{}{ICH BRINGE EUCH ALLE UM!!!}
{222}{}{ES WIRD ZEIT, DASS DU IN RENTE GEHST!!!}
{223}{}{DAS WAR'S!!! DIE PARTY GEHT LOS!!!}
{224}{}{TROCKNE DEINE HOSE, DU DRECKSKERL!!!}
{225}{}{KEINE PANIK!!!}
{226}{}{FRISS SCHEISSE!!!}
{227}{}{KAMIKAZE!!!}
{228}{}{ARGHHH!!!}

{250}{}{Du hast gewonnen!}
{251}{}{Du hast gewonnen! Das war großartig!}
{252}{}{Du hast einen äußerst formidablem Gegner besiegt! Das war ein unglaubliches Erlebnis!}
{253}{}{Du hast einen äußerst gefährlichen Gegner besiegt! Der Raum pulsiert vor euphorischer Energie. Die Menge blickt zu dir auf wie zu einem Gott!}

{254}{}{Kann man hier Chems kaufen?}
{255}{}{Nein. Auf keinen Fall. Ich habe nichts gegen Chems, aber sie schaden dem Ruf meines Lokals. Und in Reno ist ein guter Ruf eine Menge wert.}
{256}{}{Und was ist dann das hier? [Fatso's Quittung zeigen]}
{257}{}{Stimmt.}
{258}{}{Hm. Na ja, wir können nicht alles überwachen. Jedenfalls haben wir damit nichts zu tun.}
{259}{}{Hm.}

#Female character:
{1117}{}{Geschäft? Ich wollte nur reden. Na ja, wenn du so beschäftigt bist, gehe ich wohl besser ... }
{1132}{}{He, bist du bereit für einen Kampf, Sportler?}
{1137}{}{Hey, wo zum Teufel steckt unser Champion? Oh, da bist du ja! Hier ist dein Geld. [er gibt dir deinen Gewinn] Wenn du für den nächsten Kampf bereit bist, sag mir Bescheid.}
{1139}{}{Hey, Champion! Bist du hier, um dir den nächsten Adrenalinkick zu holen?}
{1140}{}{Aber sicher! Ich bin bereit zu kämpfen.}
{1141}{}{Nein, ich bin nur gekommen, um den Sklavenkämpfen zuzusehen.}
{1142}{}{Tut mir leid, Champion, wir sind noch nicht bereit für den nächsten Kampf. Komm morgen wieder, ja?}
{1144}{}{Du hast wahrscheinlich bemerkt, dass wir den Druck im Ring erhöhen und dir stärkere Gegner geben. Aber diesmal wird es eine *echte* Herausforderung für dich. Für diesen Kampf habe ich eine höhere Gage bezahlt. Du solltest besser gleich richtig loslegen!}
{1146}{}{Wenn du dich nur hättest sehen können! Das war der beste linke Haken, der je in meinem Ring geschwungen wurde! Mit solchen Tricks verdienen wir eine Menge Geld. Das Publikum war außer sich, die ganze Stadt wollte rein, um zuzusehen! Wie auch immer, hier ist dein Geld. [er gibt dir deinen Gewinn] Wenn du bereit bist, komm vorbei, dann vereinbaren wir einen weiteren Kampf ... ZU DEINEN EHREN!}