{100}{}{Du siehst einen Trainer.}
{101}{}{Du siehst einen Veteranen zahlreicher Kämpfe. Sieht aus, als würde er gern Befehle erteilen.}

{105}{}{Ich habe dir alles beigebracht, was ich weiß. Mehr kann ich dir nicht beibringen.}
{106}{}{Ich bin stolz, Teil deiner Reise gewesen zu sein!}
{107}{}{Weiter so! Du bist nicht aufzuhalten!}
{108}{}{Du bist der beste Schlachter im Ring!}

#Beginning dialogue
{110}{}{Runter auf den Boden, zwanzig Liegestütze!}
{111}{}{Wer bist du?}
{112}{}{Bist du Trainer? Kannst du mich trainieren?}
{113}{}{Nicht jetzt. Leb wohl.}

{114}{}{Wer zum Teufel hat dir erlaubt, den Mund aufzumachen, du Made?! Du redest mich nur mit SIR an, ist das klar?! Ich bin der Trainer! Ich mache aus Würmern wie dir echte Männer! Wenn ich sage, spring, springst du! Wenn ich sage, lauf, läufst du! Wenn ich sage, töte, dann tötest du verdammt noch mal!}
{115}{}{Ich bin der Trainer! Ich mache aus Würmern wie dir echte Männer! Wenn ich sage, spring, springst du! Wenn ich sage, lauf, läufst du! Wenn ich sage, töte, dann tötest du verdammt noch mal!}

{116}{}{Zum Teufel! Ich verschwende meine Zeit nicht mit rückgratlosen Waschlappen wie dir!}
{117}{}{Was springt für mich dabei raus?}
{118}{}{Kumpel, deine Fähigkeiten leuchten heller als die El Dorado Lichter! Ich kann dir nicht viel beibringen. Aber wir könnten ein bisschen trainieren, wenn du mich dafür ordentlich entlohnst.}
{119}{}{Ich brauche es sowieso nicht ...}

{120}{}{Ähm ... Geld, Sir!}
{121}{}{Ganz genau! Ich nehme 1000 Mäuse pro Sitzung. Keine Fragen!}
{122}{}{Klar. Hier ist das Geld. Wann fangen wir an?}
{123}{}{Verstanden. Ich komme mit dem Geld wieder.}

{124}{}{Sofort! Ab unter die Dusche! BEWEGUNG!!!}
{125}{}{Jawohl, Sir!}
{126}{}{Dein rechter Haken sitzt! Den Rest musst du selbst erledigen. Komm wieder, wenn du einen ernst zu nehmenden Kampf hinter dir hast – dann wärmen wir uns auf!}
{127}{}{Prima. Aufgewärmt, dann legen wir los!}
{128}{}{Nach einer intensiven Trainingseinheit mit dem Coach ist dein waffenloser Kampf um 5% gestiegen.}
{129}{}{Vieles von dem Training ist für dich ein alter Hut, aber deine Fähigkeiten sind trotzdem um 3% gestiegen.}

{130}{}{Wenn ich alles aus mir machen will, muss ich alles nutzen, was mir zur Verfügung steht, oder? Wie wär's mit ein bisschen chemischer Hilfe?}
{131}{}{Ist das ein Witz?! Das ist hier tabu! Wir haben jeden Dealer verjagt! Denk nicht mal daran, noch einmal danach zu fragen!}
{132}{}{Aber ich habe eine Notiz!}
{133}{}{Na gut.}
{134}{}{Na gut, das reicht! Entweder du hältst die Klappe und verschwindest, oder ich schlage dir die Fresse zu Brei!}
{135}{}{Versuch's doch, alter Mann!}
{136}{}{Na schön, ich gehe ja schon.}

#Female version:
{1105}{}{Ich habe dir alles beigebracht, was ich weiß. Mehr kann ich dir nicht beibringen.}
{1106}{}{Ich bin stolz, Teil deiner Reise gewesen zu sein!}
{1107}{}{Weiter so! Du bist nicht aufzuhalten!}
{1108}{}{Du bist der beste Schlachter im Ring!}

{1110}{}{Runter auf den Boden, zwanzig Liegestütze!}
{1114}{}{Wer zum Teufel hat dir erlaubt zu reden, Madenfresser?! Du sprichst mich nur mit SIR an, ist das klar?! Ich bin der Coach! Ich mache aus Möchtegerns wie dir echte Kämpfer! Wenn ich sage, spring, dann springst du! Wenn ich sage, lauf, dann läufst du! Wenn ich sage, töte, dann tötest du ganz sicher!}
{1115}{}{Ich bin der Coach! Ich mache aus Möchtegerns wie dir echte Kämpfer! Wenn ich sage, spring, dann springst du! Wenn ich sage, lauf, dann läufst du! Wenn ich sage, töte, dann tötest du ganz sicher!}
{1118}{}{Kleiner Kumpel, deine Fähigkeiten leuchten heller als die El Dorado Lichter! Ich kann dir nicht viel beibringen. Aber wir könnten ein bisschen trainieren, wenn du mich dafür ordentlich entlohnst.}
{1124}{}{Sofort! Ab unter die Dusche! BEWEGUNG!!!}
{1126}{}{Dein rechter Haken sitzt! Den Rest musst du selbst erledigen. Komm wieder, wenn du einen ernst zu nehmenden Kampf hinter dir hast – dann wärmen wir uns auf!}
{1131}{}{Ist das ein Witz?! Das ist hier tabu! Wir haben jeden Dealer verjagt! Denk nicht mal daran, noch einmal danach zu fragen!}