{100}{}{Du siehst einen vom Pech verfolgten Landstreicher.}
{101}{}{Du siehst einen schmutzigen Obdachlosen. Er wirkt etwas ordentlicher und sauberer als die anderen, die das gleiche Schicksal teilen.}

{110}{}{[Dieser Bettler sieht seltsam gepflegt aus.]}
{111}{}{Wie bist du so tief gesunken?}
{112}{}{[Gehen]}
{113}{}{Du würdest es nicht glauben. Vor nicht allzu langer Zeit war ich der Boss einer erfolgreichen Mine! Ich konnte alles haben, was ich wollte! Geld, Essen, Waffen – ich konnte mir alles leisten. Und dann, ganz plötzlich, wurde ich gefeuert. [Er lächelt traurig] So ist das eben – man hat alles, und im nächsten Augenblick hat man nichts mehr.}
{114}{}{[Gehen]}
{115}{}{Du bist also der Quartiermeister aus Uranium City, den Wright auf die Straße gesetzt hat.}
{116}{}{Ja, ich bin's. Er hat mich einfach auf der Stelle gefeuert und dann allen in der Stadt gesagt, sie sollten mir keine Arbeit geben. Also hat es auch keiner getan. Und ich konnte nichts dagegen machen.}
{117}{}{Ich kann dir helfen, deinen alten Job zurückzubekommen.}
{118}{}{[Er schaut überrascht auf] Wirklich? Na ja ... toll! Aber wozu? Die Minen sind zur Hölle geworden. Dort gibt es sowieso nichts für mich zu tun.}
{119}{}{Die Mine ist geräumt. Du kannst zurückkehren.}
{120}{}{Zurückkehren? Ha ... Hahaa! [Er wirft den Kopf zurück und lacht hysterisch] Wie soll ich zurückkehren?! Mein Geldbeutel und mein Magen sind leer. Ich komme dort niemals lebend an! Die Banditen machen mich nieder, bevor ich zehn Meilen aus der Stadt bin.}
{121}{}{Na gut. Mal sehen, ob ich etwas für dich habe ...}
{122}{}{Hier sind 50 $, damit du Vorräte kaufen kannst.}
{123}{}{Na gut, ich überlege mir, wie ich das regeln kann.}
{124}{}{Vielen Dank! Damit werde ich satt, aber zu Fuß von hier bis zu den Minen zu laufen, ist immer noch Selbstmord.}
{125}{}{Verstanden. Hier sind 300 $ für eine Postkutsche.}
{126}{}{Lass mich noch etwas überlegen, wie ich dich kostengünstiger nach Uranium City bringen kann.}
{127}{}{Kein Problem. Ich fahre dich mit meinem Wagen hin. Such ihn und warte dort auf mich.}
{128}{}{[Mit weit geöffnetem Mund starrt er auf das Geld] Einfach so?! Du bist ein wahrer Heiliger! Ich breche auf, sobald ich kann. Vielen Dank!}
{129}{}{Das ist nicht für dich, sondern für die Zukunft von Uranium City. Geh schon, wir treffen uns dort.}
{130}{}{Ein WAGEN?! So etwas habe ich lange nicht mehr gesehen! Ich gehe sofort los. Vielen Dank!}

{131}{}{[Er trippelt von einem Fuß auf den anderen, während du deine Tasche durchsuchst.]}
{132}{}{Weißt du was? Hier sind 50 $, kauf dir deine eigenen Vorräte.}
{133}{}{Sieht aus, als hätte ich nichts. Warte noch ein bisschen.}

{137}{}{Der Arbeiter wartet im Wagen. Mach dir keine Sorgen um ihn.}

#Æåíñêèå ðåïëèêè
{1128}{}{[Mit weit geöffnetem Mund starrt er auf das Geld] Einfach so?! Du bist ein wahrer Heiliger! Ich breche auf, sobald ich kann. Vielen Dank!}