{100}{}{Du siehst Carl.}
{101}{}{Du siehst einen Mann mit großen, schwieligen Händen.}
{102}{}{Kann's kaum erwarten!}

{110}{}{Hallo. Äh, brauchst du etwas?}
{111}{}{Mir wurde gesagt, dass ein gewisser Carl hier wohnt. Er hat früher in Uranium City gearbeitet.}
{112}{}{Nichts Besonderes, ich sehe mich nur um.}
{113}{}{Ach, tja, das bin ich. Warum? Hat Wright dich geschickt?}
{114}{}{Nein, Marilyn hat mich geschickt. Sie bringt die Arbeiter wieder zusammen.}
{115}{}{Was? Haben sie sich endlich geeinigt? Nein, was rede ich da? Wenn sie sich geeinigt hätten, hätte Wright mich zurückgeschickt.}
{116}{}{Die Mutanten sind tot. Alle drei. Die Mine kann wieder in Betrieb gehen, aber wir brauchen Arbeiter.}
{117}{}{Hm. Dann sehe ich mal, was ich wegen dieser Probleme tun kann.}

{118}{}{Hallo, ich bin's wieder.}
{119}{}{Marilyn hat mich geschickt. Wie wär's, wenn du nach Uranium City zurückkehrst?}
{120}{}{Bis dann.}

{121}{}{Hey, das sind gute Nachrichten! Ich würde gern zurück, aber ... Hör zu, ich kann meine Familie nicht einfach so zurücklassen.}
{122}{}{Was brauchst du denn?}
{123}{}{Ich muss meiner Frau das ganze Geld überlassen, und bis zur Mine ist es eine lange Fahrt. Könntest du mir 300 Dollar für die Postkutsche geben? Ich zahle es zurück, sobald ich meinen Lohn bekomme. Ehrlich!}
{124}{}{Gibt es keinen anderen Weg?}
{125}{}{Na gut, hier sind 300 Dollar. Pack deine Sachen.}
{126}{}{Warte genau hier, ich bin gleich zurück.}

{127}{}{Na ja, es sei denn, du kannst mich fahren. Aber ich bezweifle, dass du irgendein Fahrzeug hast, ha-ha.}
{128}{}{Ich fahre dich kostenlos mit meinem Auto nach Uranium City.}
{129}{}{Du hast ein Auto?! Wirklich?! Oh, wow, das ist großartig! Ich packe sofort meine Sachen. Ich wollte schon immer mal in einem Auto mitfahren ...}
{130}{}{Geh zum Auto und warte dort auf mich. Du fährst im Kofferraum mit.}
{131}{}{Danke, Freund! Wir sehen uns in Uranium City.}
{132}{}{Auf Wiedersehen.}

{133}{}{Weißt du, was mit Joseph passiert ist?}
{134}{}{Ehrlich gesagt, ich habe ihn schon eine Weile nicht gesehen. Nachdem er Mr. Wright getroffen hatte, sah er ziemlich aufgewühlt aus. Vielleicht solltest du Mr. Wright fragen, was passiert ist.}
{135}{}{Kannst du mir sagen, wo ich Michael finde?}
{136}{}{Aber sicher – Michael lebt auf der Straße. Wright hat ihn vor die Tür gesetzt, und dort ist er geblieben. Als er Quartiermeister war, wollte jeder sein Freund sein. Und jetzt braucht ihn niemand mehr. Verrückt, wie sich die Dinge entwickeln, oder?}
{137}{}{Der Arbeiter wartet in deinem Auto. Mach dir keine Sorgen um ihn.}

#Æåíñêèå ğåïëèêè
{1131}{}{Danke, Freund! Wir sehen uns in Uranium City.}