{100}{}{Du siehst Mark.}
{101}{}{Du siehst deinen alten Kumpel, den Prospektor Mark. Er ist zurück in Reno.}
{102}{}{Du hast den Metalldetektor auf dem langen, beschwerlichen, aber ehrlichen Weg erhalten.}

{103}{}{Vielen Dank für alles, was du für uns getan hast!}
{104}{}{Jemand hat Wright umgebracht! Muss ein verdammt verzweifelter Bastard gewesen sein. Er hat uns allen einen großen Gefallen getan.}
{105}{}{Hey, wie läuft's? Ich halte mich noch, aber das wird nicht ewig so weitergehen ...}
