#0. QUICK LOOK (NORMAL)
{100}{}{Du siehst einen Spielautomaten.}
#1. QUICK LOOK (HIGH-ROLLER)
{101}{}{Du siehst einen glänzenden Spielautomaten.}

#1. LOOK (NORMAL)
{150}{}{Du siehst einen Spielautomaten. Du könntest schwören, dass er dich ansieht.}
{151}{}{Du siehst einen Spielautomaten. Sein Gehäuse und der vergoldete Hebel glänzen verführerisch und spiegeln die Lichter der leuchtenden Schilder von New Reno.}
{152}{}{Du siehst einen glänzenden Spielautomaten. Mindesteinsatz: }
{153}{}{ Münzen.}
{154}{}{Du siehst einen glänzenden Spielautomaten.}

#2. FLOAT DIALOGUE (PLAYER = DRUNK OR HIGH) (WTG)
{160}{}{*Spiel mit mir, Cowboy.*}
{161}{}{*Hey, hallo, Seemann.*}
{162}{}{*Wirf eine Münze ein und zieh den Hebel. Ich werde dich nicht enttäuschen.*}
{163}{}{*Klick ... Klick ... Kliiick ... *}
{164}{}{*Hey, Hübscher. Komm näher, spiel mit mir.*}
{165}{}{*Hallo, Hübscher.*}
{166}{}{*Du bist süß. Warum spielst du nicht mit mir?*}

#3. FLOAT DIALOGUE (NORMAL) (WTG)
{175}{}{*Ding*}
{176}{}{*Zing*}
{177}{}{*Trrr-pow*}
{178}{}{*Ch-ch-ch-ch*}
{179}{}{*Ding-dong*}
{180}{}{*Blamm*}

#4. RETARD (WTG)
{185}{}{Du siehst eine seltsame, vergoldete Metallbox mit drei Augen und einer Hand. Es ist das Schönste, was du je gesehen hast.}
{186}{}{Ich }
{187}{}{ wer du}
{188}{}{Ich vermisse Mama. }
{189}{}{ vermisse Volt. Ich will nach Hause.}
{190}{}{Schüttle ihm die Hand.}
{191}{}{Du seltsamer Mutant.}
{192}{}{Volt segne dich! Volt!}
{193}{}{Du Wasserchip?}
{194}{}{Geh nach anderen glänzenden Dingen suchen.}
{195}{}{Geh weg.}

#5.  RETARD TALKS TO SLOT MACHINE (4, 5)
{205}{}{Die wunderschöne, dreiäugige, einarmige, vergoldete Metallbox reagiert nicht.}
{206}{}{ICH }
{207}{}{ ANTWORTE MIR }
{208}{}{Schüttle ihm die Hand.}
{209}{}{Ich von Volt, du sprichst jetzt mit mir.}
{210}{}{Du seltsamer Mutant.}
{211}{}{Du Wasserchip?}
{212}{}{Geh nach anderen glänzenden Dingen suchen.}
{213}{}{Geh weg.}

#6.  RETARD PULLS HANDLE (4, 5)
{220}{}{Du packst seine Hand und schüttelst sie herzlich. Du hörst ein *bzzzzzz* und der Kasten fängt an zu sprechen! "Bitte ... Komm schon ... Gib mir Geld."}
{221}{}{Ayyyyyyy! Roboter! Böse! Lauf!}
{222}{}{Geh weg.}

#7.  NO MONEY (WTG, 9)
{225}{}{Ugh, ich hab nicht mal Geld für Spielautomaten. Na ja, vielleicht ein andermal ... }
{226}{}{Geh weg.}

#8.  PLAY. . . ? (WTG, 14, 15)
{230}{}{Du siehst einen Spielautomaten. Sein Gehäuse und der vergoldete Hebel glänzen verführerisch im Licht der leuchtenden Schilder von New Reno. Der Münzschlitz lockt dich, und voller Vorfreude spürst du, wie dein Gesicht zu strahlen beginnt.}
{231}{}{[Deine Hand zittert, als du in deiner Tasche nach Geld suchst. Die Maschine flüstert dir weiter zu.] *Komm schon, mein Süßer ... Bitte ... Quäl mich nicht ... *}
{232}{}{[Deine Hand zittert, als du in deiner Tasche nach Geld suchst. Die Maschine flüstert dir weiter zu.] *Na, na, Süßer ... Genau so ... Fass den Hebel an ... Drück fester ... Komm schon ... *}
{233}{}{Du hast }
{234}{}{ Münzen. Alles riskieren?}
{235}{}{Du hast }
{236}{}{ Münzen. }
{237}{}{ Münze setzen?}
{238}{}{ }
{239}{}{ Münzen setzen?}
{240}{}{Das reicht für heute Nacht.}
{241}{}{Das reicht für heute.}

#9.  LOOOOOOSER (8)
{245}{}{Das Rad dreht sich, und ... nichts.}
{246}{}{NICHTS. NICHTS! Du hörst, wie diese schäbige Maschine dich verhöhnt, und die Wut überkommt dich ... Türsteher müssen deinen schreienden Körper von der Maschine wegzerren.}
{247}{}{[Die Maschine kichert.] *Tut mir leid, Schätzchen, aber nichts hält ewig. Lass dir auf dem Weg nach draußen nicht in den Arsch treten. Ha-ha-ha-ha-ha-ha!*}
{248}{}{Du hast }
{249}{}{ weitere Münzen. Den Verlust ausgleichen und weiterspielen?}
{250}{}{Du hast }
{251}{}{ Münzen. Alles riskieren?}
{252}{}{Du hast verloren. Die Party ist für heute Nacht vorbei, ob du willst oder nicht.}
{253}{}{Du hast verloren. Die Party ist für heute vorbei, ob du willst oder nicht.}
{254}{}{Das reicht für heute Nacht.}
{255}{}{Das reicht für heute.}

#10.  WIN x1 (8)
{260}{}{Drei Symbole. Du hast dein Geld zurückgewonnen.}
{261}{}{[Die Maschine flüstert weiter.] *Nun, Liebling ... Das passiert mindestens einmal ... Noch einmal ... Bitte, versuch es ... *}
{262}{}{[Die Maschine flüstert weiter.] *Na, na, Süßer ... Versuch es noch einmal ... Fass den Hebel an ... Drück fester ... Komm schon ... *}
{263}{}{Du hast }
{264}{}{ Münzen. Weiterspielen?}
{265}{}{Du hast noch }
{266}{}{ Münzen. Weiterspielen?}
{267}{}{Das reicht für heute Nacht.}
{268}{}{Das reicht für heute.}

#11.  WIN x2 (8)
{275}{}{Drei Kugeln! Du hast dein Geld verdoppelt!}
{276}{}{[Die Maschine atmet vor Lust schwer.] *Also, Liebling ... Zieh weiter am Hebel ... Schneller, kräftiger, schneller, komm schon ... *}
{277}{}{[Die Maschine atmet vor Lust schwer.] *Also, Liebling ... Zieh weiter am Hebel ... Schneller, kräftiger, schneller, komm schon ... *}
{278}{}{Du hast }
{279}{}{ Münzen. Weiterspielen?}
{280}{}{Das reicht für heute Nacht.}
{281}{}{Das reicht für heute.}

#12.  WIN x3 (8)
{290}{}{Drei Granaten! Wow! Du hast dein Geld verdreifacht!}
{291}{}{[Die Maschine quietscht vor Lust, während das Geld in deine Ablage fällt.] *Oh ja! Gott, ja! Ja! Schneller! Kräftiger! Worauf wartest du noch?! Mehr!*}
{292}{}{[Die Maschine quietscht vor Lust, während das Geld in deine Ablage fällt.] *Ohh! Wer ist dein Daddy?! Wer ist dein Daddy?! Mach es noch einmal! Diesmal zieh fester! Fester!*}
{293}{}{Spring vor Freude, atme dann tief durch und mach weiter.}
{294}{}{Komm schon, Granaten! Ich brauche neue Schuhe! [Weiterspielen.]}
{295}{}{Du hast }
{296}{}{ Münzen. Weiterspielen?}
{297}{}{Das reicht für heute Nacht.}
{298}{}{Das reicht für heute.}

#13. DRUNK, HIGH OR OTHERWISE FUCKED UP (WTG)
{305}{}{[Du siehst einen Spielautomaten. Sein Gehäuse und der vergoldete Hebel glänzen verführerisch im Licht der leuchtenden Schilder von New Reno. Der Münzeinwurf lockt dich, und voller Vorfreude hellt sich dein Gesicht auf. Als du ihn ansiehst, zwinkert dir eines der Fenster zu, und du hörst eine Frauenstimme.] *Na, hallo, Süßer. Willst du ein wenig Zeit mit mir verbringen?*}
{306}{}{[Du siehst einen Spielautomaten. Sein Gehäuse und der vergoldete Hebel glänzen verführerisch im Licht der leuchtenden Schilder von New Reno. Der Münzeinwurf lockt dich, und voller Vorfreude hellt sich dein Gesicht auf. Als du ihn ansiehst, zwinkert dir eines der Fenster zu, und du hörst eine Männerstimme.] *An ein Mädchen wie dich hier würde ich mich erinnern. Wo warst du nur mein ganzes Leben lang, Schöne?*}
{307}{}{[Kneif dich.]}
{308}{}{Äh ... Hallo?}
{309}{}{[Atme tief durch, dreh dich um und geh.]}

#14. DRUNK CONVERSATION 1 (13)
{315}{}{*Ich bin noch da, Baby ... Sei nicht schüchtern. Du willst doch spielen, oder?*}
{316}{}{*Hier bin ich, Süßer. Ich warte nur darauf, dass ein stattlicher Mann wie du mich fuellt ... *}
{317}{}{W-Wer bist du?}
{318}{}{Ja, ich will ... }
{319}{}{Vielleicht sollte ich gehen, bevor ich etwas tue, das ich bereue.}
{320}{}{[Atme tief durch, dreh dich um und geh.]}

#15. DRUNK 2 (14)
{325}{}{*Suchst du etwas, Baby? Ich kann dich auf eine Weise befriedigen, die du noch nie erlebt hast. Du wirst nie einen größeren Rausch erleben ... *}
{326}{}{*Ich bin deine wahr gewordenen Träume, Süßer. Ich brauche nur ein bisschen Aufmerksamkeit. Nur ein oder zwei Münzen für die Fahrt deines Lebens!*}
{327}{}{Kann ich biiitte spiiielen?}
{328}{}{Ja, ich will ... }
{329}{}{Vielleicht sollte ich gehen, bevor ich etwas tue, das ich bereue.}
{330}{}{[Atme tief durch, dreh dich um und geh.]}

#16. DRUNK 3 (15)
{335}{}{*Natürlich, Baby, ich bin da. [you feel compassion radiating off the machine] Lass Daddy den Schmerz verschwinden.*}
{336}{}{*Natürlich, Süßer, ich bin da. [you feel compassion radiating off the machine] Lass Mami den Schmerz verschwinden.*}
{337}{}{Ich bin auf dieser Quest, aber ich weiß nicht, wo ich sie finden soll, und sie lassen mich nicht zurück in den Vault und ... Und ... [schluchzt]}
{338}{}{Ich bin auf dieser Quest, aber ich weiß nicht, wo ich sie finden soll, und sie lassen mich nicht zurück in den Vault und ... Und ... [schluchzt]}
{339}{}{Ich bin auf dieser Quest, aber ich weiß nicht, wo ich sie finden soll, und sie lassen mich nicht zurück in den Vault und ... Und ... [schluchzt]}
{340}{}{Ich habe das Spiel durchgespielt und den Perk Unermüdlichkeit genommen, aber es gibt nur so viel Inhalt und ... Und ... [schluchzt]}
{341}{}{Jetzt ist Fallout in 3D, und sie haben die Fertigkeiten rausgenommen, und der Protagonist hat eine Sprachausgabe und ... Und ... [schluchzt]}
{342}{}{Ich wollte einen guten Charakter machen, also habe ich Begabt genommen, aber jetzt braucht man für alles Fertigkeiten und ich habe keine Punkte und ... Und ... [schluchzt]}
{343}{}{Jetzt rede ich mit einem Spielautomaten! Ich bin ein *Versager*!}
{344}{}{[Atme tief durch, dreh dich um und geh.]}

#17. DRUNK 4 (16)
{350}{}{*Schon gut, Baby ... Alles wird wieder gut. Komm her und lass mich alles regeln. Lass es raus, Baby ... *}
{351}{}{*Keine Sorge, Süßer. Halt dich einfach an mir fest. Es wird alles gut. Stütz dich auf mich, Süßer ... *}
{352}{}{Danke, Spielautomat. [schluchzt] Du bist mein einziger Freund.}
{353}{}{Ich weiß nicht, wohin ich gehen soll, und ich weiß nicht, was ich tun soll, und alle nehmen mir ständig mein Geld weg und ... Oh Gott ... }
{354}{}{[Atme tief durch, dreh dich um und geh.]}

#18. DRUNK 5 (17)
{360}{}{[Du legst deinen müden Kopf auf den Automaten.]}
{361}{}{*Geht es dir gut, Baby? Ich möchte dich nicht in diesem Zustand gehen lassen.*}
{362}{}{*Geht es dir gut, Süßer? Ich möchte dich nicht in diesem Zustand gehen lassen.*}
{363}{}{Du bist der Einzige, der mich versteht, Spielautomat. Ich liebe dich.}

#19. DRUNK 6 (18)
{370}{}{[In einem der Fenster siehst du etwas, das eine einzelne Träne sein könnte.]}
{371}{}{*Diese Welt ist voller Schurken und Diebe, aber du bleibst dir selbst treu, hörst du, }
{372}{}{? Auch wenn es wehtut, lass nicht zu, dass sie dich verändern. Und jetzt ... Verschwinde von hier, hörst du. Eine Frau sollte nicht sehen ... sollte nicht sehen, wie ein großer, starker Spielautomat weint.*}
{373}{}{*Du bist der einzige wahre Held in dieser Welt voller Schurken und Diebe, hörst du, }
{374}{}{. Bleib ein Held. Lass dich von dieser Welt nicht unterkriegen. Und jetzt verschwinde, bevor ich in Tränen ausbreche.*}
{375}{}{Leb wohl ... }

#20.  PLAY, HIGH-ROLLING MACHINE. . . ? (WTG, 14, 15, 21, 22, 23, 24)
{380}{}{Du siehst einen Spielautomaten mit hohen Einsätzen. Der Mindesteinsatz beträgt }
{381}{}{ Münzen. Der glänzende Korpus und der vergoldete Hebel funkeln verführerisch im Licht von Renos blinkenden Lichtern. Der Münzschlitz lockt dich, und dein Herz rast vor Vorfreude.}
{382}{}{[Deine Hand zittert, während du das Geld zählst. Der Automat ruft dich mit leisem Flüstern, das sonst niemand zu hören scheint.] *Na komm, Süßer ... Quäl mich nicht, ich brauch es ... *}
{383}{}{[Deine Hand zittert, während du das Geld zählst. Der Automat ruft dich mit leisem Flüstern, das sonst niemand zu hören scheint.] *Na komm, Baby ... Fass meinen Hebel an. Pack fest zu und zieh!*}
{384}{}{Du hast }
{385}{}{ Münzen. Alles riskieren?}
{386}{}{Du hast }
{387}{}{ Münzen. }
{388}{}{ Münzen setzen?}
{389}{}{ }
{390}{}{ Münzen setzen?}
{391}{}{Das reicht für heute Nacht.}
{392}{}{Das reicht für heute.}

#21.  LOOOOOOSER, HIGH-ROLLING (20)
{400}{}{Das Rad dreht sich, und ... nichts.}
{401}{}{NICHTS. NICHTS! Du hörst, wie diese schäbige Maschine dich verhöhnt, und die Wut überkommt dich ... Türsteher müssen deinen schreienden Körper von der Maschine wegzerren.}
{402}{}{[Die Maschine kichert.] *Tut mir leid, Schätzchen, aber nichts hält ewig. Lass dir auf dem Weg nach draußen nicht in den Arsch treten. Ha-ha-ha-ha-ha-ha!*}
{403}{}{Du hast }
{404}{}{ Münzen. Versuchst du, den Verlust wieder hereinzuholen?}
{405}{}{Du hast }
{406}{}{ Münze. Alles riskieren?}
{407}{}{Kein Geld mehr. Heute ist einfach nicht deine Nacht.}
{408}{}{Kein Geld mehr. Heute ist einfach nicht dein Tag.}
{409}{}{Das reicht für heute Nacht.}
{410}{}{Das reicht für heute.}

#22.  WIN x1, HIGH-ROLLING (20)
{415}{}{Drei Bomben. Du hast dein Geld zurückgewonnen.}
{416}{}{[Die Maschine flüstert weiter.] *Nun, Liebling ... Das passiert mindestens einmal ... Noch einmal ... Bitte, versuch es ... *}
{417}{}{[Die Maschine flüstert weiter.] *Na, na, Süßer ... Versuch es noch einmal ... Fass den Hebel an ... Drück fester ... Komm schon ... *}
{418}{}{Du hast }
{419}{}{ Münzen. Weiterspielen?}
{420}{}{Das reicht für heute Nacht.}
{421}{}{Das reicht für heute.}

#23.  WIN x2, HIGH-ROLLING (20)
{425}{}{Drei Atombomben! Du hast dein Geld verdoppelt!}
{426}{}{[Die Maschine atmet vor Lust schwer.] *Also, Liebling ... Zieh weiter am Hebel ... Schneller, kräftiger, schneller, komm schon ... *}
{427}{}{[Die Maschine atmet vor Lust schwer.] *Also, Liebling ... Zieh weiter am Hebel ... Schneller, kräftiger, schneller, komm schon ... *}
{428}{}{Du hast }
{429}{}{ Münzen. Weiterspielen?}
{430}{}{Das reicht für heute Nacht.}
{431}{}{Das reicht für heute.}

#24.  WIN x3, HIGH-ROLLING (8)
{435}{}{Drei Atompilze! Du hast dein Geld verdreifacht!}
{436}{}{[Die Maschine quietscht vor Lust, während das Geld in deine Ablage fällt.] *Oh ja! Gott, ja! Ja! Schneller! Kräftiger! Worauf wartest du noch?! Mehr!*}
{437}{}{[Die Maschine quietscht vor Lust, während das Geld in deine Ablage fällt.] *Ohh! Wer ist dein Daddy?! Wer ist dein Daddy?! Mach es noch einmal! Diesmal zieh fester! Fester!*}
{438}{}{Spring vor Freude, atme dann tief durch und mach weiter.}
{439}{}{Na los, Atompilze! Ich brauche neue Schuhe! [Weiterspielen.]}
{440}{}{Du hast }
{441}{}{ Münzen. Weiterspielen?}
{442}{}{Das reicht für heute Nacht.}
{443}{}{Das reicht für heute.}

# use gambling skill on table, the +1 is for high roller tables
# critical failures
{1000}{}{Diese Quoten gehen nicht auf. Hier stimmt doch etwas nicht ... }
{1001}{}{Alles scheint mit rechten Dingen zuzugehen. Hier bestehlen sie dich ganz ehrlich.}
# failures
{1005}{}{Diese Quoten gehen nicht auf. Hier stimmt doch etwas nicht ... }
{1006}{}{Alles scheint mit rechten Dingen zuzugehen. Hier bestehlen sie dich ganz ehrlich.}
# success
{1010}{}{Alles scheint mit rechten Dingen zuzugehen. Hier bestehlen sie dich ganz ehrlich.}
{1011}{}{Diese Quoten gehen nicht auf. Hier stimmt doch etwas nicht ... }
# critical success
{1015}{}{Alles scheint mit rechten Dingen zuzugehen. Hier bestehlen sie dich ganz ehrlich.}
{1016}{}{Diese Quoten gehen nicht auf. Hier stimmt doch etwas nicht ... }