{100}{}{Du siehst einen hungernden Landstreicher.}
{101}{}{Du siehst einen Obdachlosen. Er sieht hungrig aus.}
{102}{}{Nicht ins Gesicht! Überallhin, nur nicht ins Gesicht!}

#Before feeding him
{110}{}{Entschuldigen Sie die Störung, Sir, aber könnten Sie einem armen Mann etwas Brot geben? Ich habe Hunger, Sie würden mir das Leben retten ...}
{111}{}{Von hier aus hast du einen guten Blick auf das Hotel. Ich gebe dir etwas zu essen, wenn du mir sagen kannst, wer ständig die Wände bemalt.}
{112}{}{Klar, mal sehen, was ich in meinem Rucksack habe.}
{113}{}{Tut mir leid, ich kann dir nicht helfen.}
{114}{}{Hau ab, du dreckiger Bettler!}

{115}{}{Oh, danke, Sir, Sie sind so freundlich! Mir kommen vor Rührung die Tränen!}
{116}{}{Hier, bitte!}

{117}{}{[Er beobachtet dich aufmerksam, während du in deinem Inventar kramst.]}
{118}{}{Hier, nimm etwas reifes Obst.}
{119}{}{Wie wär's mit Trockenfleisch?}
{120}{}{Hier, etwas gebratener Leguan. Schling nicht alles auf einmal runter!}
{121}{}{Ich habe Leguan am Spieß. Köstlich!}
{122}{}{Ein leckeres Sandwich macht dich bestimmt satt!}
{123}{}{Ich kann etwas brahmin-Milch entbehren, wenn du willst.}
{124}{}{}

#After feeding him
{150}{}{Also, was kannst du mir über den Graffiti-Künstler erzählen?}
{151}{}{Oh, Sir, Sie können sich gar nicht vorstellen, wie dankbar ich Ihnen für Ihre Hilfe bin! [er wischt sich die Tränen von seinen unrasierten Wangen]}
{152}{}{Erzähl mir von dem Vandalen, der die Wände des Silver Legacy bemalt, dann kann ich dir noch etwas zu essen geben.}
{153}{}{Kopf hoch, jemand anders wird dir schon helfen.}
{154}{}{Schon gut. Ich helfe gern.}

{155}{}{Oh, Sir, ich würde alles für einen Bissen zu essen tun! Alles!}
{156}{}{Warte, ich habe gerade nichts zu essen dabei.}
{157}{}{[Der Bettler genießt jeden Bissen deiner Gabe und stöhnt vor Wonne] Oh, danke, mein Herr ... Er ist ein Junge, den sie Straßenköter nennen. Er arbeitet nur nachts, wenn niemand hinsieht. Er ist gerissen, aber kein Kämpfer – bei Tageslicht würde er sich nichts trauen!}
{158}{}{Du lügst mich an! Wie soll er im Dunkeln malen können?!}
{159}{}{Diese Gemälde sind viel zu gut, um im Dunkeln entstanden zu sein. Was verschweigst du mir?}
{160}{}{Oh nein, mein Herr, nach dem, was Sie für mich getan haben, würde ich Sie niemals anlügen! Er kommt früh am Morgen, wissen Sie, wenn es nicht mehr ganz so dunkel ist. Nur dann ist niemand unterwegs.}
{161}{}{Verstehe ... das wollte ich nur wissen. Wir sehen uns.}

{162}{}{Von wegen! Sag es mir sofort, oder ich füttere dich mit deinem eigenen Arsch!}
{163}{}{Nein, nicht! [er wirft die Arme über den Kopf und zittert] Sie nennen ihn Straßenköter! Er kommt früh am Morgen, wenn es hell genug ist, um etwas zu sehen, aber alle noch schlafen! Dann bemalt er die Wände! Mehr weiß ich nicht, ich schwöre!}
{164}{}{Diesmal lasse ich dich am Leben. Wenn du mich angelogen hast, komme ich wieder.}
{165}{}{Na, war das so schwer? Und dabei wolltest du dafür tatsächlich noch bezahlt werden ...}

#Female Player Copy
{1110}{}{Entschuldigen Sie die Störung, gnädige Frau, aber könnten Sie einem armen Mann etwas Brot geben? Ich habe Hunger. Sie würden mir das Leben retten ...}
{1115}{}{Oh, danke, gnädige Frau, Sie sind so gütig! Da kommen mir glatt die Tränen!}
{1151}{}{Oh, gnädige Frau, Sie können sich gar nicht vorstellen, wie dankbar ich Ihnen für Ihre Hilfe bin! [er wischt sich die Tränen von den unrasierten Wangen]}
{1156}{}{Warte, ich habe gerade nichts zu essen dabei.}
{1157}{}{[Der Bettler genießt jeden Bissen deiner Gabe und stöhnt vor Wonne] Oh, danke, gnädige Frau ... Er ist ein Junge, den sie Straßenköter nennen. Er arbeitet nur nachts, wenn niemand hinsieht. Er ist gerissen, aber kein Kämpfer – bei Tageslicht würde er sich nichts trauen!}
{1160}{}{Oh nein, gnädige Frau, nach dem, was Sie für mich getan haben, würde ich Sie niemals anlügen! Er kommt früh am Morgen, wissen Sie, wenn es nicht mehr ganz so dunkel ist. Nur dann ist niemand unterwegs.}
{1163}{}{Nein, nicht! [Er wirft die Arme über den Kopf und duckt sich.] Sie nennen ihn Straßenköter! Er kommt früh am Morgen, wenn es hell genug ist, um etwas zu sehen, aber alle noch schlafen! Dann bemalt er die Wände! Mehr weiß ich nicht, ich schwöre!}