{100}{}{Du siehst einen traurigen Besucher.}
{101}{}{Du siehst einen Restaurantgast mit einem niedergeschlagenen Gesichtsausdruck.}
{102}{}{Hallo, da bin ich wieder.}
{103}{}{Lass mich in Ruhe.}

#Beginning of dialogue
{110}{}{[Dieser unauffällig aussehende Mann nimmt still einen Schluck aus einer Flasche. Er wirkt, als wäre er in melancholischen Gedanken versunken.]}
{111}{}{Hey, Mann, warum so ein langes Gesicht?}
{112}{}{Hey, willst du einen Schluck mit mir trinken?}
{113}{}{Weißt du, wenn du versuchst, deinen Kummer zu ertränken, schiebst du das Unvermeidliche nur auf.}
{114}{}{Hallo, wer bist du?}
{115}{}{[Lass ihn in Ruhe.]}

{120}{}{Was? [Der Mann blickt langsam auf.] Ach, nein, keine Sorge.}
{121}{}{Aber ich will es wissen!}
{122}{}{Bist du immer so verschlossen?}
{123}{}{}
{124}{}{Na gut, wenn du meinst.}

{125}{}{Danke, aber ich suche niemanden, bei dem ich mich ausweinen kann.}
{126}{}{Wenn ich sage, dass ich dir zuhören will, dann solltest du besser anfangen zu reden.}
{127}{}{Sag es mir doch einfach endlich.}
{128}{}{Weißt du, du musst wirklich darüber reden. Das hilft viel besser als Alkohol.}
{129}{}{Na gut, wenn du meinst.}

{130}{}{Was?! [Er zischt durch die Zähne.] Was weißt du schon? Wer zum Teufel bist du überhaupt? Nur irgendein Mann, der aus dem Ödland hierhergestolpert ist! [Er winkt ab.] Lass mich in Ruhe!}
{131}{}{Na gut, beruhig dich ... }

{132}{}{Hm? [Er wirft dir einen genervten Blick zu.] Geht dich nichts an. Lass mich in Ruhe.}
{133}{}{Wie kannst du es wagen?! Geh auf die Knie und entschuldige dich!}
{134}{}{Tut mir leid, das geht mich wahrscheinlich nichts an ... Aber ist etwas passiert?}
{135}{}{In Ordnung, wenn du meinst.}

{136}{}{[Er zuckt wütend zusammen, hält aber im letzten Moment inne. Er scheint nicht zu Gewalt zu neigen.] Hör zu, lass mich einfach in Ruhe!}
{137}{}{Ha!}

{150}{}{Hm? [Der Mann mustert dich und wendet sich dann wieder seiner Flasche zu] Nein, tue ich nicht.}
{151}{}{Na gut, wie wär's mit einem Drink? Ich lade dich ein.}
{152}{}{Mal ehrlich – liegt es daran, dass du keinen Respekt vor mir hast?}
{153}{}{Und wenn ich ihn mir selbst nehme?}
{154}{}{Bist du immer so unhöflich?}
{155}{}{Na schön, ich lasse dich in Ruhe, wenn du nicht reden willst.}

{156}{}{Ach, ich kann schon für mich selbst sorgen, keine Sorge.}
{157}{}{Du? Ha, nimm erst mal die Nase aus der Flasche. Tschüss, Verlierer.}
{158}{}{Oh, tut mir leid, ich wollte damit nichts sagen ... }
{159}{}{Ganz ruhig, ich geh ja schon.}
{160}{}{Ja ... Natürlich. Jeder muss hin und wieder Dampf ablassen.}
{161}{}{Prima. Sieht aus, als wäre dir etwas passiert. Was ist los?}

{162}{}{Ja, weil du mich ansprichst, obwohl ich meine Ruhe haben will, und dann versuchst, ... Ach, vergiss es. Ja, ich respektiere dich nicht. In dieser Stadt solltest du besser aufpassen, was du sagst.}
{163}{}{[Er hebt eine Augenbraue] Viel Glück dabei, hier einen Kumpel zu finden. Ich schließe keine Freundschaften bei einem Drink.}
{164}{}{Also respektierst du mich nicht?}
{165}{}{Ha! Noch so ein Produkt des Egozentrismus.}
{166}{}{Wer? Ich?!}
{167}{}{Warum? Ich werde dir trotzdem nichts Wichtiges erzählen. Ich bin ein ganz gewöhnlicher Arbeiter ... Ich versuche nur, mich zu entspannen. Und du bringst mich wieder auf die Palme. Also ... [Er winkt ab] ... Lass mich in Ruhe, Wanderer.}
{168}{}{Nur wenn Wanderer wie du mich belästigen. Verdammt noch mal, kann ich hier nicht in Ruhe einen Drink genießen?!}

{169}{}{Ja, wahrscheinlich. Aber es ist lange her, dass ich hier Leuten begegnet bin, denen ich mich anvertrauen kann. [Er mustert dich aufmerksam] Aber ... Du weißt ja, was es heißt, sich in die Fänge einer Schlange zu begeben.}
{170}{}{Ja, wahrscheinlich. Aber es ist lange her, dass ich hier Leuten begegnet bin, denen ich mich anvertrauen kann. [Er mustert dich aufmerksam] Woher kommst du, wenn ich fragen darf?}
{171}{}{Ich komme aus Reno.}
{172}{}{Ich komme aus einer kleinen Siedlung weit im Norden.}
{173}{}{Geht dich nichts an.}
{174}{}{Wa-?... }

{175}{}{In dem Fall gehen dich meine Probleme nichts an. Alles Gute, Wanderer.}
{176}{}{Ach ja... }
{177}{}{Ah... Nun, es war nett, mit dir zu plaudern.}
{178}{}{So wird es also laufen... }

{179}{}{Wirklich? Ich dachte, außer ein paar Indianern und Plünderern gäbe es keine Siedlungen. Schön zu hören, dass es in den Ödlanden jemanden mit menschlichem Antlitz gibt.}
{180}{}{Also, was bedrückt dich?}
{181}{}{Ich lasse nach einem langen Tag nur Dampf ab.}
{182}{}{Oh, ich kenne das Gefühl – eine Entscheidung treffen zu müssen... Zwischen was und was diesmal?}
{183}{}{Zwischen Hunger mit ehrlichem Gesicht und selbstsatter Genügsamkeit. Weißt du, ich habe einen Hund, aber es wurde schwer, sie zu füttern, und jetzt hat sie auch noch einen Wurf Welpen bekommen. Meine Frau hat mich angefahren, ich würde nichts tun und wir müssten sie füttern, und die Einnahmen waren nicht gerade gut... Ich musste ihnen mit dem Vorschlaghammer die Köpfe einschlagen. Bei den Erinnerungen daran zittern mir immer noch die Hände... }
{184}{}{Ich dachte, Reno wäre voller harter Leute, die sich wegen Welpen keine Sorgen machen.}
{185}{}{Ha! Ödlandbewohner... Das hier mag eine harte Stadt sein, aber jeder hat seine eigene komplizierte Geschichte. Wenn du das noch nicht verstanden hast, wirst du es irgendwann.}
{186}{}{Hm. Darüber muss ich nachdenken.}
{187}{}{Ja, natürlich, denk nach. Und... Weißt du... Danke, dass du mir zugehört hast.}
{188}{}{Natürlich! Jederzeit.}
{189}{}{Pfft! Ha-ha! Ein Mann weint wegen ein paar toten Hunden! Was für eine Geschichte!}
{190}{}{Was zum Teufel weißt du schon?! Hältst du dich für einen ganz großen Mann? [er zischt durch die Zähne] Du bist nur irgendein Abschaum aus dem Ödland und hältst dich für großartig, weil du das größte Tier weit und breit bist. [er wedelt mit der Hand] Lass mich in Ruhe. Ich brauche deine „Weisheit“ nicht. Ach, und nimm die hier – [er wirft dir ein paar Kondome vor die Füße] – damit die nächste Generation sich nicht mit noch mehr Typen wie dir herumschlagen muss.}
{191}{}{Ha-ha-ha! Tschüss, Loser.}
{192}{}{Das muss schrecklich gewesen sein. Es tut mir leid, dass du das durchmachen musstest.}
{193}{}{Mach dir keine Sorgen darum – ich komm schon drüber hinweg. Und ... weißt du ... danke, dass du mir zugehört hast. Moment mal – hey, Barkeeper! Ein Bier für meinen Freund! Ich zahl!}
{194}{}{Oh, danke dafür.}
{195}{}{Lass es dir schmecken! Diese Stadt braucht Leute wie dich. Du wirst sehen, Reno wird dank Leuten wie dir und mir besser werden.}
{196}{}{Klar, pass auf dich auf.}

#Female version
{1126}{}{Wenn ich gesagt habe, dass ich dir zuhöre, solltest du am besten anfangen zu reden.}
{1153}{}{Und wenn ich ihn mir selbst nehme?}
{1158}{}{Oh, tut mir leid, ich wollte damit nichts sagen ... }
{1162}{}{Ja, weil du mich ansprichst, obwohl ich meine Ruhe haben will, und dann versuchst, ... Ach, vergiss es. Ja, ich respektiere dich nicht. In dieser Stadt solltest du besser aufpassen, was du sagst.}
{1167}{}{Warum? Ich werde dir trotzdem nichts Wichtiges erzählen. Ich bin ein ganz gewöhnlicher Arbeiter ... Ich versuche nur, mich zu entspannen. Und du bringst mich wieder auf die Palme. Also ... [Er winkt ab] ... Lass mich in Ruhe, Wanderer.}
{1175}{}{In dem Fall gehen dich meine Probleme nichts an. Alles Gute, Wanderer.}
{1185}{}{Ha! Ödlandbewohner... Das hier mag eine harte Stadt sein, aber jeder hat seine eigene komplizierte Geschichte. Wenn du das noch nicht verstanden hast, wirst du es irgendwann.}
{1187}{}{Ja, natürlich, denk nach. Und... Weißt du... Danke, dass du mir zugehört hast.}
{1190}{}{Was zum Teufel weißt du schon?! Hältst du dich für eine knallharte Schlampe? [Er zischt durch die Zähne.] Du bist doch nur irgendein Abschaum aus dem Ödland, der sich großartig vorkommt, weil er das gemeinste Tier weit und breit ist. [Er wedelt mit der Hand.] Lass mich in Ruhe. Deine „Weisheit“ brauch ich nicht. Ach, und nimm die hier – [Er wirft dir ein paar Kondome vor die Füße] –, damit sich die nächste Generation nicht mit noch mehr Leuten wie dir herumschlagen muss.}
{1193}{}{Mach dir keine Sorgen darum – ich komm schon drüber hinweg. Und ... weißt du ... danke, dass du mir zugehört hast. Moment mal – hey, Wirt! Ein Bier für meinen Freund! Ich zahl!}
