{100}{}{Du siehst eine Empfangsdame.}
{101}{}{Du siehst einen elegant gekleideten Empfangsmitarbeiter. Er lächelt dich willkommen heißend an.}
{102}{}{Tut mir leid, aber du musst deine Waffe wegstecken.}

#Íà÷àëî äèàëîãà:
{109}{}{Erzähl mir von diesem Hotel.}
{110}{}{Willkommen im Silver Legacy, dem besten Hotel in Reno! Es ist außerdem das einzige Hotel in Reno, also kannst du genauso gut gleich ein Zimmer buchen. Und wenn du schon hier bist, warum schaust du dir nicht auch das Casino an? Du hast einen langen Weg hinter dir, gönn dir ruhig etwas!}
{111}{}{Was kann ich für dich tun?}

{112}{}{Ich muss mit dem Besitzer sprechen. Wo ist er?}
{113}{}{Hast du die zwei Schläger gesehen? Einer hat Dreadlocks und der andere trägt ein Brecheisen. Wo sind sie hin?}
{114}{}{Warum lasst ihr die Leute draußen überall eure Wände bemalen?}
{115}{}{Okay, aber erzähl mir zuerst von dem Hotel.}
{116}{}{Ich brauche ein Zimmer.}
{117}{}{Ich brauche im Moment nichts. Ich gehe dann mal.}
{118}{}{Ich habe noch eine Frage ...}
{119}{}{Verstehe. Danke.}

#Ïğî ğıêåòèğîâ:
{125}{}{[Das Lächeln des Empfangsmitarbeiters verschwindet, und er blickt nervös zur Tür hinaus] Äh ... Sie sind, äh ... beim El Dorado, gleich hinter Virginia Street ...}

#Ïğî ãğàôôèòè-õóëèãàíà:
{126}{}{„Die Leute“? Ha! Wir haben versucht, die dafür Verantwortlichen aufzuhalten, glaub mir. Aber wir erwischen sie nie auf frischer Tat. Wer auch immer sie sind, sie sind vorsichtig.}
{127}{}{Vielleicht kann ich diesen Künstler für euch erwischen.}
{128}{}{Vielleicht. Wahrscheinlich nicht, aber einen Versuch ist es wert. Ich zahle dir 100 Dollar, wenn du sie bei ihrer Tat erwischst.}
{129}{}{Ich werde daran denken.}

#Îá îòåëå è î ãîğîäå:
{130}{}{Du bist im einen und einzigen Silver Legacy! Dieses Gebäude ist Renos wichtigste Herberge für Reisende aus dem Ödland. Vor dem Krieg waren wir für unsere Gastfreundschaft und die Schönheit unserer Umgebung berühmt. Wir waren das Juwel der Stadt! Reno ist heutzutage viel rauer, aber wir kämpfen darum, der Diamant darin zu bleiben.}
{131}{}{Die Welt ist heute ganz anders als damals. Wie kann das Hotel noch Gäste anlocken?}
{132}{}{Die Leute müssen doch schlafen, oder? Reno zieht immer noch Leute von außerhalb an. Die meisten unserer Kunden sind Karawanenarbeiter, aber es gibt auch Flüchtlinge aus anderen Siedlungen, die in der Großstadt ihr Glück versuchen wollen.}
{133}{}{Warum kommen die Leute nach Reno?}
{134}{}{Abgesehen vom Geschäft? Hm. Ich würde sagen, der Hauptgrund ist die Freiheit. Hier gibt es weder Bürgermeister noch Sheriff. Die Kontrolle liegt in den Händen der Leute! Und ja, das kann gefährlich werden, aber für viele ist es auch sehr reizvoll, mich eingeschlossen. Jedenfalls ist Reno ein großartiger Ort für einen Besuch, selbst wenn du nicht hierbleiben willst. Reno war schon immer ein tolles Reiseziel.}
{135}{}{Touristen? Wir leben in einem Ödland. Wie viel Tourismus kann es da schon geben?}
{136}{}{Du wärst überrascht! Reno wurde von den Bombenangriffen kaum getroffen, deshalb sind viele der alten Vergnügungsstätten noch intakt. Wenn du Spaß haben willst, schau dir einfach die Casinos an! Oder geh runter zu Virginia Street und schau bei El Dorado vorbei. Dort gibt es Alkohol, einen Nachtclub und sogar Kämpfe im Keller! Und vergiss nicht: Wenn du dich ausruhen musst, sind wir die Besten in der Stadt.}
{137}{}{Und was ist mit Essen und Vorräten?}
{138}{}{Das Silver Legacy hat gleich auf der anderen Straßenseite ein wunderbares Restaurant. Besseres Essen findest du in Reno bestimmt nicht! Und neben dem Karawanenparkplatz gibt es einen Laden. Was immer du für die Reise brauchst, dort bekommst du es.}

#Ïğî Òåäà Áàíäè:
{139}{}{Weißt du, wo 75 Virginia Street ist?}
{140}{}{Hm. Die meisten Häuser haben keine Nummern, aber das müsste irgendwo hier in der Nähe sein. Ich würde es in den Slums auf der anderen Straßenseite versuchen.}
{141}{}{Danke.}
{142}{}{Kennst du ruhige Gegenden in der Stadt, wo man sicher wohnen könnte?}
{143}{}{In Reno gibt es nicht viele sichere Orte und noch weniger ruhige! Du müsstest einen Ort ohne Menschen finden. Hm ... Wenn ich einen ruhigen und sicheren Ort wählen müsste, würde ich zum Flughafen oder Bahnhof gehen. Die sind natürlich nicht mehr in Betrieb, also hat niemand einen Grund, dort hinauszufahren.}

#Ñíÿòü êîìíàòó íà ñóòêè:
{149}{}{Ein Zimmer kostet dich }
{150}{}{ Dollar für 24 Stunden. Wir vermieten nur tageweise, nicht länger.}
{151}{}{Ich nehme ein Zimmer, danke. Hier ist das Geld.}
{152}{}{So viel Geld habe ich gerade nicht. Ich komme später wieder.}
{153}{}{Großartig! Ich zeige dir dein Zimmer. Wann hast du das letzte Mal in einem richtigen Bett geschlafen, hm?}
{154}{}{[Folge ihm.]}
{155}{}{Du hast den ganzen Boden vollgekotzt! Und wer soll das jetzt sauber machen?}
{156}{}{Du fühlst dich ausgeruht.}

#Äæåé Êóêèø
{160}{}{Waren hier irgendwelche Biker abgestiegen? Ich suche einen namens Jay Kukish.}
{161}{}{Vor Kurzem ist eine ganze Gruppe Biker durch die Stadt gekommen. Im Hotel steigen sie normalerweise nicht ab, obwohl Mr. Mordino gern viel Zeit mit ihnen verbringt. Früher ist er selbst Motorrad gefahren, weißt du. Wenn du Fragen zu Bikern hast, solltest du wahrscheinlich mit ihm sprechen.}

#Ïî÷èíêà âûòÿæêè
{170}{}{Hast du Arbeit für mich?}
{171}{}{Ich habe den Lüfter im Lüftungsschacht repariert.}
{172}{}{Nein ... Moment mal. Kennst du dich mit Technik aus? Im zweiten Stock gibt es ein leeres Zimmer mit einem kaputten Lüfter im Lüftungsschacht. Ich glaube, einer der früheren Gäste hat daran herumgefummelt. Wenn du ihn reparieren kannst, bezahle ich dich.}
{173}{}{Ich sehe es mir an.}
{174}{}{Danke, damit wäre ein Problem weniger. Hier sind 100 Mäuse für deine Mühe. Mach's gut!}
{175}{}{Gern geschehen!}

#Ñåìüÿ áîññà
{180}{}{Ich bin beeindruckt, dass dein Boss den Laden ganz allein am Laufen halten kann. Er muss wohl keine Familie haben, wenn er so viel Zeit seiner Arbeit widmen kann.}
{181}{}{Oh nein, nein, er hat ganz bestimmt eine Familie. Eine Frau und ein wunderschönes kleines Mädchen. Ich erinnere mich noch an den Abend, an dem er ihr im Hotelrestaurant einen Antrag gemacht hat. Ach ... so romantisch. Manchmal gehen sie dort immer noch zusammen aus.}
{182}{}{Im Restaurant, sagst du. Gut zu wissen.}