{100}{}{Du siehst Billy.}
{101}{}{Du siehst ein seltsames Wesen, das aus irgendeinem stinkenden Loch gekrochen ist. Es scheint gut gelaunt zu sein.}
{102}{}{}
{103}{}{Licht ... Mutter ... Ich ... komme ...}
{104}{}{Ich bin nur der Hausmeister. Frag den Mann dort, er ist der Besitzer.}

{105}{}{Z-z-Z-z ...}
{106}{}{Endlich ist der Tag vorbei.}

{110}{}{Hör auf, mich so anzusehen!}
{111}{}{Ich *weiß*, dass mich keiner dabeihaben will! Du musst es mir nicht ständig sagen!}
{112}{}{ICH BIN AUCH EIN MENSCH!}
{113}{}{Alle lachen mich nur aus! Hört einfach auf!}
{114}{}{::schnief::}

#Mordino family
{120}{}{Ich stehe zu Euren Diensten, Sir!}
{121}{}{Weißt du, wohin die Familie Mordino gegangen ist? Ich habe gehört, sie kamen früher oft hierher, bevor sie verschwanden. Warum?}
{122}{}{Mach dir keine Gedanken darum.}

{123}{}{[Der Junge sieht sich vorsichtig um] Warum ... Warum willst du das wissen?}
{124}{}{Na ja, ich mache mir Sorgen um sie. Wir kannten uns früher ...}
{125}{}{Sieh mal, Billy - ich habe eine leckere Süßigkeit. Sie ist nicht nur süß. Du weißt, was ich meine, oder?}
{126}{}{Sag mir einfach, was du weißt, und ich gebe dir etwas Schönes.}
{127}{}{Vergiss es, ich finde alles selbst heraus.}

{128}{}{[Er kneift die Augen zusammen] Lügt Ihr mich an? Ich würde mich daran erinnern, wenn sie Euch gekannt hätten, und ich glaube nicht, dass ich Euch je mit ihnen gesehen habe.}
{129}{}{Mach dir keine Gedanken darum.}
{130}{}{Du ... Du wirkst freundlich. Nicht wie die Gangster hier in der Stadt. Die jagen mir Angst ein ...}
{131}{}{Also, kannst du mir sagen, was mit der Familie passiert ist?}
{132}{}{[Billy schaut schnell im Raum umher und blickt dann mit einem sehr unkindlichen Ausdruck zu dir auf] Ja ... Ja, Sir. Danke, Sir. Genau das brauche ich.}
{133}{}{Äh, nein danke, Sir. Ich habe schon Leute wie Euch gesehen. Euer "etwas Schönes" brauche ich nicht, es sei denn, es ist ... etwas, das mir wichtig ist.}
{134}{}{Es geht ihnen gut, Sir. Manchmal erkälten sie sich, weil es dort unten feucht ist, aber sie werden immer wieder gesund.}
{135}{}{"Dort unten feucht"? Wohnen sie in einer Höhle oder so?}
{136}{}{Oh nein, Sir! Es ist nur der Keller am Bahnhof. Sehr schön dort, Sir!}
{137}{}{Na gut, das reicht. Du kannst gehen.}
{138}{}{Du hast herausgefunden, dass die Familie Mordino im Keller am Bahnhof ist.}

#Walking the tables
{150}{}{Ugh, es ist überall verschmiert ... Das lässt sich so schwer saubermachen ...}
{151}{}{Oh Mann, jemand hat ein Bonbon fallen lassen! Ich hol's mir ...}
{152}{}{Ist der Geschäftsmann hungrig? Ich bin gleich wieder da!}
{153}{}{Der Geschäftsmann ist schon wieder nicht hier. Schade ...}
{154}{}{Willst du was essen? Ich bin gleich wieder da!!!}

{155}{}{*Ahh, süßes Klo! Mein süßestes Klo ...*}
{156}{}{Vielleicht hat hier jemand etwas Schönes dagelassen ...}
{157}{}{Oh! Jemand hat ein halbes Stück Kaugummi fallen lassen! Ich hol's mir!}
{158}{}{Wow! Jemand hat ein Sandwich dagelassen!}
{159}{}{Jemand hat sein Bier nicht ausgetrunken! Jetzt gehört es mir.}
{160}{}{::wühlt im Urinal herum::}
{161}{}{::zieht leise ein Stück Brot aus dem Urinal und steckt es sich schnell in den Mund::}
{162}{}{Ein Stück Papier! Damit kann ich mich abwischen!}
{163}{}{Chef, dieses Ei ist doch verdorben, oder? Darf ich es essen?}
{164}{}{Nichts Interessantes ...}
{165}{}{::blickt sich nervös um::}

{180}{}{Kann ich Ihnen etwas bringen? Was heißt, nein danke? Sie haben schon alles, was Sie brauchen? Na, das ist ja seltsam!}
{181}{}{Chef, darf ich kacken gehen?}
{182}{}{Chef, das Ei im Urinal ist doch verdorben, oder? Darf ich es essen?}
{183}{}{Chef, ich will schlafen ...}
{184}{}{Chef, warum ist dein Hosenschlitz offen?}
{185}{}{Chef, krieg ich mein Bonbon?}
{186}{}{Ob der Chef mir heute ein Bonbon gibt ...}
{187}{}{Der Chef ist nett!}

#Female version
{1120}{}{Ich stehe zu Ihren Diensten, Ma'am!}
{1128}{}{[Er kneift die Augen zusammen] Lügt Ihr mich an? Ich würde mich daran erinnern, wenn sie Euch gekannt hätten, und ich glaube nicht, dass ich Euch je mit ihnen gesehen habe.}
{1132}{}{[Billy blickt rasch im Raum umher, dann sieht er mit einem ganz und gar nicht kindlichen Ausdruck zu Ihnen auf] Ja ... Ja, Ma'am. Danke, Ma'am. Genau das brauche ich.}
{1133}{}{Äh, nein danke, Ma'am. Ich habe schon Leute wie Sie gesehen. Ich brauche Ihr „etwas Schönes“ nicht, es sei denn, es ist ... etwas, das mir wichtig ist.}
{1134}{}{Es geht ihnen gut, Ma'am. Manchmal erkälten sie sich, weil es da unten feucht ist, aber sie werden immer wieder gesund.}
{1136}{}{Oh nein, gnädige Frau! Das ist nur der Keller am Bahnhof. Er ist sehr schön, gnädige Frau!}