{100}{}{Du siehst Lewis Mordino.}
{101}{}{Du siehst den müden Besitzer des „Silver“-Hotels.}
{102}{}{Sieh mal, ich habe genug gelitten. Lass mich einfach in Ruhe.}

#Äèàëîã:
{106}{}{Ich höre.}
{107}{}{Du bist hier der Besitzer? Erzähl mir bitte, wie das alles angefangen hat.}
{108}{}{Du musst eine Menge über diese Stadt wissen, oder? Bitte erzähl mir davon.}
{109}{}{Tschüss.}

#Ïğî ğıêåò
{110}{}{Was wollten diese Typen?}
{111}{}{Vergiss es, das geht dich nichts an.}
{112}{}{Oh nein, du hast mich deinen Leibwächter genannt. Damit geht mich das etwas an, soweit ich das sehe.}
{113}{}{Hm, ist das so? Na gut. Fangen wir von vorne an.}
{114}{}{Hm. Entschuldige bitte. Aber du musst verstehen, in der Stadt herrscht Krieg. Solange du dich um deine eigenen Angelegenheiten kümmerst und dich heraushältst, wirst du davon nicht betroffen sein. Verstehst du?}
{115}{}{Krieg? Erzähl mir davon!}

{116}{}{Dieser Krieg zwischen den Geschäftsleuten dauert schon seit etwa zehn Jahren. Vor etwa sechs Jahren wurde der Konflikt viel blutiger. Irgendein Idiot holte Raiderbanden her, um dem Ganzen ein Ende zu setzen. Doch die Raider machten ihren eigenen Deal – und verschoben die Machtverhältnisse.}
{117}{}{[Weiter]}
{118}{}{Das Problem ist, dass sich diese Raider nicht einmal untereinander einigen konnten. Infolgedessen fiel die Stadt für mehrere Jahre ins Koma. Es kam zu einer wirtschaftlichen und sozialen Krise – Straßenüberfälle, Nahrungsmangel und ein ganzer Haufen anderer Probleme. Gott allein weiß, was sich derjenige dabei gedacht hat, der das alles angezettelt hat, aber die gegenwärtige Regierung ist eindeutig nicht in der Lage, irgendetwas davon in den Griff zu bekommen.}
{119}{}{Auf welcher Seite stehst du?}
{120}{}{Auf meiner eigenen. Wie eigentlich jeder in dieser Stadt. Manche glauben, es sei einfacher, sich einer Gang anzuschließen, aber ich versuche, mich aus all dem Konflikt herauszuhalten und ein einfaches Geschäftsleben zu führen. Deshalb ist es mir egal, wer das Sagen hat. Solange er mir meine Lebensweise nicht aufzwingt, kann er segeln, wohin er will.}
{121}{}{Verstehe. Danke für die Erklärung.}

#Î ãîğîäå
{130}{}{Na dann, willkommen in Reno! Eine wahrhaft lebendige und geschäftige Stadt, das Babylon dieser Höllenlandschaft, in der wir leben. Wenn du länger bleiben möchtest, kannst du ein Zimmer bekommen. Sprich mit dem Empfangschef, wenn es um die Geschichte der Stadt geht, redet er viel lieber.}
{131}{}{Nun, ich habe diesen Ort geerbt, aber lange Zeit stand das Gebäude leer. Als New Reno zu einem Zentrum des regen Handels mit allen anderen Siedlungen wurde, strömten die Karawanenhändler herbei. Dadurch gab es plötzlich jede Menge Händler auf der Durchreise, die keinen Schlafplatz für die Nacht hatten. Da ich gern mehr über die guten Leute aus anderen Teilen des Ödlands erfahre, habe ich die Türen dieses Hotels gern geöffnet. Und der Rest ist, wie man so sagt, Geschichte.}
{132}{}{Reden wir über etwas anderes.}

#Äæåé Êóêèø
{140}{}{Ich habe ein Gerücht gehört, dass du und die Biker alte Freunde seid. Zum Beispiel einer von ihnen, der Jay heißt.}
{141}{}{Ich habe nie einen Hehl daraus gemacht, dass ich diese Typen mag. Wenn sie in der Stadt sind, trinken wir oft zusammen Bier und erzählen uns Geschichten. Aber Jay ist nicht wie die anderen Biker. Er ist von Technologie besessen und nicht besonders gesprächig. Selbst unter seinesgleichen gilt er als Sonderling.}
{142}{}{Man sagt, Jay sei vor Kurzem durch Reno gekommen. Stimmt das?}
{143}{}{Ja, er blieb über Nacht und fuhr am Morgen wieder los. Er schien es sehr eilig zu haben. Er hatte so ein merkwürdiges Funkeln in den Augen ... Wahrscheinlich hatte er etwas Besonderes gefunden, aber er hat mir kein verdammtes Wort darüber gesagt, was es war.}
{144}{}{Ich weiß, was es mit diesem Funkeln auf sich hat. Ich muss ihn sofort kontaktieren, bevor es zu spät ist!}
{145}{}{Bist du sicher? Das sind nicht gerade Leute, die mit dir reden, wenn du ihnen nicht gefällst. Nicht, dass das viel ausmacht ... Soweit ich weiß, ziehen die Biker irgendwo nach Südosten. Sie haben nicht gesagt, warum oder wohin. Es gibt also nur einen Weg herauszufinden, wo sie jetzt sind: Du musst sie mit einem wirklich guten Funkgerät kontaktieren. Und es gibt gute und schlechte Nachrichten. Die gute ist, dass es in Reno eine geeignete Station gibt, die du nutzen könntest. Die schlechte ist, dass sie sich in einem alten Bunker unter dem Stryker-Gebäude befindet und der Eingang verschlossen ist.}
{146}{}{Das wird mich nicht aufhalten. Kennst du die Rufzeichen und Kanäle, über die ich die Biker erreichen könnte?}
{147}{}{Das wusste ich nie. Die Biker benutzen ihre eigenen Rufzeichen und Kommunikationskanäle, damit niemand sie aufspüren kann.}
{148}{}{Vielleicht steht es irgendwo geschrieben. Danke und auf Wiedersehen.}
{149}{}{Ich muss Jay kontaktieren, bevor es zu spät ist!}

#Øàíòàæ:
{160}{}{Mein Boss, Mr. Thompson, verliert langsam die Geduld mit deiner Dummheit.}
{161}{}{Ich habe beim letzten Gespräch alles gesagt, was ich sagen wollte. Ich bin mein eigener Boss. Du wirst einen sehr guten Grund finden müssen, um meine Meinung zu ändern.}
{162}{}{Gib mir Zeit zum Nachdenken.}
{163}{}{Vielleicht können wir einen Deal machen? Wovor hast du Angst?}
{164}{}{Nach all den Einschüchterungen und Drohungen - jetzt auf einmal Diplomatie? Hätte Thompson früher beschlossen, es auf die feinfühligere Art zu versuchen, hätten wir vielleicht eine Einigung erzielt. Aber meine Grundüberzeugungen werde ich niemals ändern. Ich bin ein *freier* Geschäftsmann. Beweise mir jetzt, dass ein Bündnis mit Thompson für mich vorteilhafter ist als eines mit Stryker oder sonst jemandem.}
{165}{}{Ich habe es geschafft, eine Aufnahme von einem Treffen Strykers zu bekommen. Er hat dich einen starrköpfigen Narren genannt und plant, dich zu ersetzen, sobald er die Macht an sich gerissen hat.}
{166}{}{Also, was ist deine endgültige Antwort an meinen Boss?}
{168}{}{}
{169}{}{}

{170}{}{Na, Daddy-o! Man sagt, deine kleine Frau hat gar nicht so üble Titten, hm? He-he ...}
{171}{}{[Mordino schweigt eine Weile, den Blick gesenkt] W-was ... Was willst du ...}
{172}{}{Nicht viel. Mr. Thompson verlangt Schutzgeld, dass du alle Verbindungen zu Stryker abbrichst und die Zimmer im zweiten Stock zur Überwachung nutzt. Such es dir aus.}
{173}{}{[Lange Pause] Ich ... bin einverstanden ...}
{174}{}{Endlich. Ich richte es ihm aus. Er wird dich treffen wollen, also mach dich bereit.}
{175}{}{[Zeig ihm Mrs. Mordinos Finger] Weißt du, was das ist?}
{176}{}{Mein Boss hat die Nase voll von dir. Entweder du kooperierst, oder du endest wie Stryker. Keine weiteren Warnungen.}
{177}{}{Stryker ist tot? Hm ... Ich dachte, dieser Kampf würde niemals enden. Na gut, dann habe ich wohl keine Wahl.}
{178}{}{Also, wähl.}

#Íàáîğ äëÿ óõîäà
{180}{}{Wären Sie als Mann von Welt an hochwertigen Körperpflegeprodukten interessiert?}
{181}{}{[Er betrachtet neugierig deine Sachen] Oh mein Gott, das ist ein komplettes Körperpflegeset von "Pretty & Glamour"! Beeindruckend. Im Lauf der Jahre habe ich viele solcher Sets verschenkt, aber als die Vorräte knapp wurden, musste ich sie fürs Hotel zurückhalten. Dieses Set könnte mir wirklich helfen!}
{182}{}{[Weiter]}
{183}{}{Ich kaufe dir das gern ab. Wie viel willst du dafür?}
{184}{}{2000 $}
{185}{}{1500 $}
{186}{}{1000 $}
{187}{}{Hm, darüber habe ich noch nicht wirklich nachgedacht. Gib mir einen Moment, um es mir zu überlegen, dann reden wir über den Preis.}
{188}{}{Das ist viel zu viel für nur ein einziges Set! Du musst den Preis senken.}
{189}{}{Äh, nein. Ich suche mir einfach Kunden, die es sich leisten können. Tschüss.}
{190}{}{Na ja, der Preis scheint angemessen. Es ist sein Geld wert. Ich nehme es.}
{191}{}{Ausgezeichnet! Dann handeln wir.}
{192}{}{Weißt du, ich habe es mir anders überlegt. Tschüss.}
{193}{}{Ich kann jetzt keine Scherze gebrauchen. Nein.}
{194}{}{Tut mir leid, kommt nicht wieder vor.}

#Ëîõîòğîí â êàçèíî
{200}{}{Wusstest du, dass jemand die Automaten im Casino manipuliert?}
{201}{}{Was zum Teufel hast du gerade gesagt! Unser Casino ist das ehrlichste in der ganzen Stadt.}
{202}{}{Vielleicht. Aber es gibt Hinweise darauf, dass einer der Automaten einen zusätzlichen Zähler hat. Seltsam, oder?}
{203}{}{Hm. Na gut, dann lasse ich einen meiner Assistenten die Automaten überprüfen. Nur damit unser Gewissen rein bleibt.}
{204}{}{Und was ist mit dem Geld, das die Spieler verloren haben?}
{205}{}{Unsinn! Wir geben niemandem sein Geld zurück, selbst wenn du *beweist*, dass einer der Casinoangestellten ein Betrüger ist. Wir wissen nicht, wer seinetwegen Geld verloren hat, und selbst wenn, wäre es unmöglich zu beweisen, dass sie es deswegen und nicht einfach aus Pech verloren haben. Jetzt lass mich meine Angestellten instruieren.}
{206}{}{Na schön ...}

#Female character
{1187}{}{Hm, darüber habe ich noch nicht wirklich nachgedacht. Gib mir einen Moment, um es mir zu überlegen, dann reden wir über den Preis.}
{1192}{}{Weißt du, ich habe es mir anders überlegt. Tschüss.}
