{110}{}{Unser Boss lässt grüßen.}
{111}{}{Du schon wieder?! Ich hab die Nase voll von dir!}
{112}{}{Na, na, beruhige dich. Hier versuchen Leute zu schlafen.}
{113}{}{He-he ... Ja! Du wirst zu aufgeregt, und dann müssen wir vielleicht ...}
{114}{}{Warte mal. Wer zum Teufel ist das?}
{115}{}{Hä?}
{116}{}{Das ist mein Leibwächter. Ich würde dir raten, deinem Boss auszurichten, dass die Antwort immer noch Nein lautet.}
{117}{}{Na schön ... Na schön. Aber wir kommen wieder.}
{118}{}{Ja! Wir kommen wieder!}
{119}{}{Und du, Junge ... Such dir einen neuen Job. Helden leben in dieser Stadt nicht lange.}
{120}{}{Was ist gerade passiert?}
{121}{}{Vergiss es. Das geht dich nichts an, misch dich nicht ein.}

{122}{}{Du denkst, du hast gerade eine Erpressung unterbrochen.}

{1115}{}{Wer, ich?}
{1119}{}{Und du, Mädchen ... Such dir einen neuen Job. Heldinnen leben in dieser Stadt nicht lange.}