{100}{}{Du siehst eine Mutter.}
{101}{}{Du siehst ein Kind.}
{102}{}{Du siehst einen der Mordinos.}
{103}{}{Wachen! Wachen!!!}

#Äèàëîã
{110}{}{Bitte bringt uns nicht um!!!}
{111}{}{Na, na, na. Ist das nicht die liebe Familie Mordino. Ihr hättet euch vor Mr. Thompson verstecken sollen.}
{112}{}{Bleib hier und rühr dich nicht vom Fleck, bis ich zurückkomme.}

{114}{}{[Sie drückt ihre Tochter fester an sich] Warte – wir gehen friedlich! Tut uns nur nichts!}
{115}{}{Das werden wir sehen. Jetzt bewegt euch!}
{116}{}{Du hast die Familie Mordino gefangen genommen.}

{117}{}{Wer waren die Typen? Strykers Sicherheitsleute?}
{118}{}{Ich weiß es nicht! Mein Mann hat sie angeheuert! Sie sind nur Söldner, sie dienen nur dem Geld!}