{100}{}{Du siehst einen fanatischen Fan.}
{101}{}{Du siehst einen Verehrer, der vor Lust ganz von Sinnen ist. Sieht aus, als würde er dich zerfetzen!}

{102}{}{Mach die Tür auf!}
{103}{}{Hey!}
{104}{}{Wo bist du, Süße?!}
{105}{}{Ich rede mit dir!}
{106}{}{Komm raus, Süße!}
{107}{}{Versteck dich nicht länger!}
{108}{}{Wenn's sein muss, zerren wir dich da raus!}
{109}{}{Wo bist du?! WO?!}
{110}{}{Hör auf, dich zu verstecken!}
{111}{}{Du kannst uns nicht aufhalten! Wir finden dich!}
{112}{}{Ich begehre dich schon so lange!}
{113}{}{Ich habe Süßigkeiten für dich, Mädchen!}
{114}{}{Ich brauche dich!}
{115}{}{Wir wissen, dass du da drin bist!}

{120}{}{ }

{150}{}{[Die Menge ist über dir, bevor du nach deiner Waffe greifen kannst. Dutzende kräftige Hände reißen dir die Kleider vom Leib und betasten jeden Zentimeter deines Körpers. Lärm und Chaos sind überwältigend. Du wirst mitten auf der Straße zu Boden gedrückt und dort von einem unbeweglichen Gewicht festgehalten. Du kannst dich nicht bewegen und nicht einmal atmen.]}
{151}{}{[Ertragen]}
{152}{}{Die Menge hat dich brutal vergewaltigt!}
