{100}{}{Du siehst einen Vertreter.}
{101}{}{Du siehst einen ernst dreinblickenden Mann, der im Auftrag eines anderen hier ist.}
{102}{}{Wir sind fertig.}

{103}{}{Wer bist du?}
{104}{}{Ich vertrete Mr. Thompson. Wir wissen von deinem Geschäft mit Strykers Bande und möchten dir ein Gegenangebot machen.}
{105}{}{Ich weiß von deiner Vereinbarung mit Stryker. Ich schlage vor, du überdenkst sie noch einmal.}
{106}{}{Ich bin hier, um dein Geschäft mit Stryker zu verhindern. Für immer. [Angriff]}

{107}{}{Ich bin mit meinen Vereinbarungen mit Stryker zufrieden. Warum sollte ich davon abrücken?}
{108}{}{Stryker ist tot. Seine Bande kommt ohne ihn nicht klar. Schon die Tatsache, dass ich so nah an dich herankommen konnte, beweist, dass sie nicht wissen, was sie tun.}
{109}{}{Weil Thompson diesen Krieg gewinnen wird. Und wenn er das tut, wird er alle Drogenhändler unter seine Kontrolle bringen. Glaubst du wirklich, ein Chemiker auf Strykers Seite würde daran etwas ändern?}
{110}{}{Du hast recht. Na gut, ich bin dabei. Thompson soll jemanden schicken, um die Einzelheiten auszuhandeln.}
{111}{}{Gut. Ich hoffe, du hast nicht vor, auf beiden Seiten zu spielen ...}
{112}{}{Wirklich?}
{113}{}{Nur eine Warnung, mehr nicht. Ich gehe.}
{114}{}{Wenn du das tust, wird Mr. Thompson es nicht vergessen. Glaub mir, er ist ein weitaus gefährlicherer Feind als Stryker. Ein Chemiker auf Strykers Seite wird ihm nicht die nötige Stärke für eine gute Verteidigung geben.}
{115}{}{Äh ... Na ja, Thompson ist einfach viel cooler als Stryker, findest du nicht?}
{116}{}{Das ist kindisch. Verschwinde.}
{117}{}{Na ja, ich habe dich gewarnt.}

#Æåíñêèå ğåïëèêè
{1106}{}{Ich bin hier, um dein Geschäft mit Stryker zu verhindern. Für immer. [Angriff]}
{1113}{}{Nur eine Warnung, mehr nicht. Ich gehe.}
{1117}{}{Na ja, ich habe dich gewarnt.}
