{100}{}{Du siehst deinen Kontakt.}
{101}{}{Du siehst den Mann, von dem Thompson gesprochen hat.}

{109}{}{Sieh dich woanders um. Seit Strykers Tod sind die Leute hier nervös. Wenn du eine Kugel abbekommst, bist du selbst schuld.}

{110}{}{Halt! Was machst du hier?}
{111}{}{Ich suche dich.}
{112}{}{Ich sehe mich nur um.}
{113}{}{Sieh dich woanders um. Stryker mag es nicht, wenn Leute in seinem Gebiet herumschnüffeln.}
{114}{}{Na gut.}
{115}{}{[Er sieht sich um] Wirklich?}
{116}{}{„Du bist so klein wie ein Käfer ...“}
{117}{}{„... oder riesig wie ein Wal ...“ Na schön, wir müssen reden. Sofort.}
{118}{}{Was ist passiert?}

#Old text:
{119}{}{Stryker will einen Waffendeal abschließen. Ich erzähle dir alles, was ich weiß, aber ich habe eine Bedingung: Ich will zu Thompson überlaufen, und zwar so schnell wie möglich.}
{120}{}{In Thompsons Reihen verachtet man Überläufer. Nach der Sache mit Stryker lassen sie dich nicht einfach davonkommen, darauf kannst du wetten. Du solltest von hier verschwinden, und zwar weit weg.}
{121}{}{Riecht es nach Ärger? Stimmt - der ganzen Bande von Stryker steht ein Blutbad bevor. Und du wirst mitten im Kreuzfeuer stehen, wenn du nicht rechtzeitig abhaust. Ich richte Thompson deinen Wunsch aus.}
{122}{}{Ach, so ist das also - du hast beschlossen, dich möglichst teuer zu verkaufen? Das nennt man „politische Prostitution“. Pfui! Aber bitte - vielleicht ... *vielleicht* nimmt Thompson dich auf.}
{123}{}{Wirklich? Ich bin erledigt! Du meinst, ich sollte besser abhauen ... Na ja, ich habe wohl keine andere Wahl. Ich muss mich in einem dieser kleinen Dörfer verkriechen und Bauer oder Jäger werden. Vielleicht sollte ich das gleich tun.}
{124}{}{Wow, sie nehmen mich auf, oder? Klasse! Ich wollte schon lange zu ihm überlaufen, ehrlich! Aber das ist gar nicht so einfach, du verstehst doch?}
{125}{}{Was denn! Früher habe ich, äh, einfach anders gedacht. Dann habe ich von Thompsons Ideen erfahren und, äh, die Augen geöffnet bekommen! Ehrlich! Aber ich werde mich anstrengen, ich kann nützlich sein, gebt mir nur eine Chance!}
{126}{}{Ja, ja, und jetzt reden wir über Strykers Deal.}
{127}{}{}
{128}{}{}
{129}{}{Äh, das konnte ich nicht herausfinden ... Aber ich weiß, dass die Daten in einem Terminal im Generatorraum gespeichert sind. Man kommt durch einen Hintereingang hinein, aber die Türen sind verschlossen.}

#New text:
{130}{}{Strykers Männer stehen kurz davor, ein großes Geschäft abzuschließen. Ich weiß, wann und wo, aber bevor ich es dir sage, will ich tausend Dollar in bar.}
{131}{}{Ist dir das Geld mehr wert als dein Leben?}

{132}{}{Verpiss dich. Ich gehe hier ein verdammt großes Risiko ein. Ich brauche das Geld, um ... Ach, egal. Kein Geld, keine Infos.}
{133}{}{Hmm, das ist der Preis für eine Nevada Express-Fahrt nach Salt Lake City, oder? Ich sollte lieber abhauen, solange ich noch kann. Stimmt's?}
{134}{}{Na gut, hier ist das Geld. Jetzt erzähl mir alles, was du weißt.}
{135}{}{Ich kriege diese Informationen auch ohne deine Hilfe. Also ... Sag Lebwohl, du Spitzel!}
{136}{}{Ich brauche dich nicht – ich finde alles selbst heraus. Und jetzt geh mir aus dem Weg.}
{137}{}{Ich bringe dir, was du brauchst.}
{138}{}{Also, wo ist das Geld?}
{139}{}{Verdammt, natürlich erwische ich ausgerechnet die eine Person auf Thompsons Gehaltsliste, die ein halbes Hirn hat! Na gut, du hast recht – ich habe diesen verdammten Ort satt. Tag für Tag gibt es nur mehr Kämpfe, Attentate, Patrouillen und Überfälle. Sie sagen, das alles sei für eine bessere Zukunft, aber das ist Bullshit! Es ist egal, wer das Sagen hat, sie sehen alle gleich aus, wenn ihre Stiefel auf deinem Gesicht herumtrampeln. Ich lasse nicht zu, dass das mein verdammtes Leben wird.}
{140}{}{Muss es Bargeld sein? Ich kann den Mittelsmann ausschalten und dir stattdessen ein Ticket besorgen.}
{141}{}{Verstehe.}
{142}{}{Ist mir egal, solange ich in diesem Bus sitze.}
{143}{}{Ich habe dir ein Nevada Express-Ticket besorgt.}
{144}{}{Komm zu Papa! Genau das brauche ich. Und denk nicht mal daran, mir zu folgen – ich werde dich im Auge behalten.}
{145}{}{Ich habe meinen Teil der Abmachung erfuellt. Erzähl mir von Strykers Deal.}
{146}{}{Gut. Das sollte reichen. Und denk nicht mal daran, mir zu folgen – ich werde dich im Auge behalten.}
{147}{}{Also, hör zu. Stryker schließt einen Deal mit einem Wind of War ab, um Munition und medizinische Vorräte zu bekommen. Sie unterzeichnen den Vertrag bald. Die Lieferungen kommen erst später.}
{148}{}{Wann und wo unterzeichnen sie den Vertrag?}
{149}{}{Sie treffen sich im zweiten Stock des Silver Legacy-Hotels. Das Zimmer ist bereits reserviert. Strykers Männer sichern das Gebäude.}
{150}{}{Verstanden. Das sollte reichen. Und jetzt verschwinde von hier.}
{151}{}{Danke für die Informationen. Jetzt brauche ich dich nicht mehr. [Angreifen.]}
