{100}{}{Du siehst einen Söldner.}
{101}{}{Du siehst einen verdächtigen Mann. Er wirkt nicht besonders freundlich.}
{102}{}{Sprich mit dem Boss, nicht mit mir.}

################################################################
#          Äèàëîã
################################################################

{110}{}{Hey! Das hier ist unser Revier. Verschwindet.}
{111}{}{Ihr seht aus wie ein Haufen Hunde ohne Leine. Was habt ihr vor?}
{112}{}{Gut, ich gehe.}

{113}{}{[Seine Hand wandert langsam zum Halfter, sein Blick huscht unstet zwischen dir und den anderen hin und her] Wir machen keine Spielchen. Verschwindet, oder ihr bekommt es mit uns allen zu tun. Und das ist erst der Anfang.}
{114}{}{Für wen arbeitet ihr?}
{115}{}{Kommen wir zur Sache. Ich bin wegen der Mordinos hier. Und ich nehme sie mit, so oder so.}
{116}{}{Wir arbeiten für uns selbst. Da, wo das Geld stimmt. Und jetzt verpiss dich!}
{117}{}{Ich kenne dich nicht. Wer auch immer dich geschickt hat, sag ihnen, sie sollen jemanden schicken, den ich kenne, oder Mordino selbst. Sonst kommt niemand in ihre Nähe.}
{118}{}{Nein, du begreifst es nicht. Ich werde dich töten und sie mir dann mit Gewalt nehmen. [Angreifen]}
{119}{}{Äh ... Klar. Mach ich.}

################################################################
#          Ğàçíîå
################################################################

{130}{}{Diese Tür ist abgeschlossen. Du brauchst einen Schlüssel.}
{131}{}{Das ist eine seltsame Art von Schloss, die du noch nie gesehen hast. Du brauchst einen Schlüssel, um es zu öffnen ... Oder du schlägst die Tür einfach ein.}
{132}{}{Verschlossen.}
{133}{}{Aufgeschlossen.}
{134}{}{Das hat ganz schön Lärm gemacht.}

################################################################
#
#        Ïåğåãîâîğû (àâòîğû òåêñòà: Kerb è BlackDesigner)
#
################################################################

{200}{}{ }
{201}{}{Hey, wie geht's dir heute?}
{202}{}{Mir geht's gut.}
{203}{}{Toll! Weißt du, was das heißt?}
{204}{}{Was?}
{205}{}{Du bist gut genug, um dich selbst zu ficken! Ha-ha-ha!}
{206}{}{Das ist der schlechteste Witz, den ich je gehört habe.}
{207}{}{Dann solltest du dich hier ja pudelwohl fühlen! Ha-ha-ha!}
{208}{}{ }
{209}{}{Hey, Kopf hoch, Mann! Was ist los?}
{210}{}{Hast du's schon gehört? Wieder hat man eine von Mamas Mädchen gefunden, der die Augen ausgestochen wurden.}
{211}{}{Schon wieder?! Mann, wer zum Teufel ist dieser Typ?}
{212}{}{Ich weiß, oder? Was für ein Psychopath.}
{213}{}{Ich meine, ich würde Zunge und Ohren rausschneiden. Aber die Augen? Was für ein Irrer!}
{214}{}{ }
{215}{}{Also, in letzter Zeit kaufe ich bei diesem hässlichen Hurensohn mit dem Ring ein.}
{216}{}{Riskant. Wie läuft's bisher?}
{217}{}{Bisher gut. Ich glaube, der ist echt.}
{218}{}{Ja, na ja, ich hab so einiges gehört. Ich wäre vorsichtig.}
{219}{}{Wie auch immer, ich habe angefangen, eine Liste mit Leuten zu schreiben, die ich umbringen sollte.}
{220}{}{Ach ja? Wie viele?}
{221}{}{Äh, ich glaube, so um die 20?}
{222}{}{Ha! Kleine Fische! Meine hat mindestens 50!}
{223}{}{Ach ja?}
{224}{}{Ja!}
{225}{}{Weißt du, ich glaube, ich habe gerade Nummer 21 gefunden!}
{226}{}{Hey, beruhig dich mal, Kumpel. Übertreib's nicht!}
{227}{}{Warum nicht? Als ob es sonst irgendwas zu tun gäbe!}
{228}{}{ }
{229}{}{Hör zu, du weißt, dass ich mich nie über irgendwas beschwere.}
{230}{}{Und?}
{231}{}{Also will ich mir jetzt mal ein paar Dinge von der Seele reden.}
{232}{}{Zum Beispiel?}
{233}{}{Einfach jede Menge Dinge, die mich ankotzen ...}
{234}{}{Na dann los.}
{235}{}{Ich meine jetzt nicht Sachen, die mich bloß nerven ...}
{236}{}{Komm endlich zur Sache, verdammt noch mal!}
{237}{}{... sondern Sachen, bei denen ich einfach nur töten will!}
{238}{}{ }
{239}{}{Erstens die Security im Casino. Ich hab die Schnauze voll von dem Scheiß!}
{240}{}{Du bist nicht der Einzige.}
{241}{}{Diese Typen durchsuchen ständig mein ganzes Zeug! Ohne jeden verdammten Grund!}
{242}{}{Ja?}
{243}{}{Sie sagen, das soll das Casino schützen, aber weißt du was?}
{244}{}{Was?}
{245}{}{Du bestellst Essen an der Bar, und sie geben dir das Messer gleich selbst dazu!}
{246}{}{Ist das der Grund, warum du so angepisst bist?}
{247}{}{Wo ist da die Logik? Sie geben dir das verdammte Messer!}
{248}{}{Was soll ich sagen? Du hast recht.}
{249}{}{Schon eine Flasche Whiskey reicht, um jemanden umzubringen!}
{250}{}{Du liegst nicht falsch!}
{251}{}{Was, wenn ich Boxer oder so was wäre, hm? Was, wenn ich mit meinen Fäusten töten könnte?}
{252}{}{Die können sie mir ja schlecht wegnehmen.}
{253}{}{Also ist das ganze Sicherheitsding einfach bescheuert!}
{254}{}{Ja, ergibt nicht besonders viel Sinn.}
{255}{}{Aber weißt du, was mich WIRKLICH ankotzt?}
{256}{}{Bist du noch nicht fertig?}
{257}{}{Diese Scheißkerle im Kasino mit ihren Zigarren!}
{258}{}{Was ist denn mit Zigarren?}
{259}{}{Wann hört das verdammt noch mal auf?!}
{260}{}{ }
{261}{}{Diese reichen Motherfucker müssen immer rauchen ...}
{262}{}{ }
{263}{}{... an einem großen braunen Schwanz lutschen!}
{264}{}{Ha!}
{265}{}{Ja, genau! Einen großen braunen Schwanz im Mund!}
{266}{}{Ha! Sag's ihnen!}
{267}{}{Oh, und noch etwas, das mich ankotzt ...}
{268}{}{Ja?}
{269}{}{Diese Scheißkerle mit einem Stacheldraht-Tattoo am Arm.}
{270}{}{Als würden sie glauben, das macht sie zu harten Kerlen, was?}
{271}{}{Ja. Denen sollte man verdammt noch mal den Arsch versohlen!}
{272}{}{ }
{273}{}{Mann, ich würde ihnen so gern die verdammten Zähne ausschlagen ...}
{274}{}{War's das?}
{275}{}{Weißt du, was passieren würde, wenn du ihnen ein paar Mal mit einem Schlagstock über den Kopf ziehen würdest?}
{276}{}{Was?}
{277}{}{Die gingen runter wie ein verdammter Stein!}
{278}{}{ }

#Female character
{1115}{}{Kommen wir zur Sache. Ich bin wegen der Mordinos hier. Und ich nehme sie mit, so oder so.}