{100}{}{Du siehst einen Revolutionär.}
{101}{}{Du siehst einen von Strykers Unterstützern.}
{102}{}{Du hast Lucianos Aufgabe erledigt.}

{103}{}{Schön, dich zu sehen.}
{104}{}{Wie geht's dem Boss?}
{105}{}{Ach, wenn ich dem Boss doch nur so nah wäre ...}
{106}{}{Du und Stryker seid gute Freunde.}

#Floats while attempting to talk
{110}{}{Ich hab dir nichts zu sagen.}
{111}{}{Striker ist hier der Boss, sprich mit ihm.}
{112}{}{Weitergehen. Stryker duldet kein Herumlungern.}
{113}{}{Aha. Was noch?}
{114}{}{Niemanden zum Reden? Äh, ich versteh dich ...}
{115}{}{Ich bin nicht zum Plaudern hier.}