{100}{}{Du siehst einen Leibw‰chter.}
{101}{}{Du siehst einen grimmigen Leibw‰chter. Man merkt, dass er seinen Job wirklich gut macht.}
{102}{}{Du kannst eintreten.}

{103}{}{Keinen Schritt weiter! Was willst du?}
{104}{}{Ich muss wegen eines Gesch‰fts mit dem Kurier sprechen.}
{105}{}{Nichts.}
{106}{}{Geh rein. Wenn ich eine Waffe sehe, schieﬂe ich. Ohne Warnung.}
{107}{}{Okay ...}
{108}{}{Geh rein ... Aber steck die Waffe weg. Wenn ich sie wieder sehe, schieﬂe ich.}