{100}{}{Du siehst einen Besucher.}
{101}{}{Du siehst einen Besucher des Clubs. Er versucht, eine der Tänzerinnen zu bezirzen.}
{102}{}{Dieser Besucher will nicht mit dir reden.}
{103}{}{ }

{110}{}{Sie weiß, wie man das trägt!}
{111}{}{Diese Süße ist ein Augenschmaus!}
{112}{}{::johlt::}
{113}{}{::schreit::}
{114}{}{::applaudiert::}
{115}{}{::hysterisch::}
{116}{}{Jaaa!}
{117}{}{Aaaaaah!}
{118}{}{::quiekt::}
{119}{}{Bring mich um, Mädchen!}
{120}{}{Du bist der Beste!}
{121}{}{Du bist die Beste, Liebling!}
{122}{}{Ich brauche mehr Bier.}
{123}{}{DU BIST DIE BESTE. DIE BESTE!}
{124}{}{Jaaa!!!}
{125}{}{TIIITS!!!}
{126}{}{So etwas habe ich in meinem Leben noch nie gesehen!}
{127}{}{Hast du das gesehen, hä?! Hast du?!}
{128}{}{Verletz mich, Schöne!}
{129}{}{Oh mein Gott!}
{130}{}{Ich bin dein größter Fan, Schönheit!}
{131}{}{Baby, komm zu mir! Vergiss die Stange!}
{132}{}{Zeig uns deinen Arsch!}
{133}{}{Oh, diese Versuchung!}
