{100}{}{Du siehst Mom.}
{101}{}{Du siehst den Besitzer des Nachtclubs.}

#Ïîñëå èçíàñèëîâàíèÿ 'îëïîé ôàíà'îâ
{102}{}{Oh mein Gott! Was haben sie dir angetan?!}

#Â ìîìåí' óáèéñ'âà Ìàìàøè
{103}{}{Danach ist der Club für dich für immer geschlossen.}

################################################################3
#
# Ñ'àğ'îâûå äèàëîãè
#
################################################################3

#Äëÿ ÃÃ-ìóæ÷èíû:
{110}{}{[Mustert dich von Kopf bis Fuß] Junger Mann, das hier ist ein Raum nur für Angestellte. Besucher lasse ich nur geschäftlich herein. Wenn du also nichts mit mir zu besprechen hast, muss ich dich bitten zu gehen.}
{111}{}{Ich muss mit dir reden.}
{112}{}{Nein, ich habe nichts mit dir zu besprechen ... }

{113}{}{Wegen was?}
{114}{}{Äh, vergiss es.}
{115}{}{Natürlich. Worüber möchtest du reden?}

{116}{}{Jedes Mädchen hat Potenzial, du bist da keine Ausnahme. Aber du musst dich schon etwas anstrengen. Mädchen mit deinem Aussehen haben es schwer, das Publikum zu begeistern.}

#Äëÿ ÃÃ-æåíùèíû
{120}{}{[Mustert dich von den Beinen aufwärts] Was ist, Mädchen?}
{121}{}{Ich würde gern im Club auftreten.}
{122}{}{Ich weiß auch nicht, ich bin einfach im falschen Raum gelandet.}

{123}{}{[Mustert dich von den Beinen aufwärts] Na, so was! Was für Beine! Wie kann ich dir helfen, Süße?}
{124}{}{Du findest wirklich, ich bin eine „Süße“? Wie wär's dann mit einem Job als Tänzerin?}
{125}{}{Es freut mich, dass dir meine Beine gefallen, aber ich bin einfach im falschen Raum gelandet.}
{126}{}{Verstehe, aber ich muss mit dir über etwas anderes reden.}

{127}{}{Mmm ... Weißt du, beim Tanzen kommt es auf Anmut und Beweglichkeit an, und daran mangelt es dir. Ein hübsches Gesicht allein reicht nicht, um das Publikum zu begeistern. Also, meine Süße, wir müssen leider auf dich verzichten.}
{128}{}{Bitte! Lass es mich wenigstens versuchen!}
{129}{}{Schade ... Na gut, dann gehe ich wohl.}

{130}{}{Dein Durchhaltevermögen gefällt mir. Aber ich weiß, wovon ich rede. Du musst erst vor dem Spiegel üben.}

{131}{}{Was für ein Durchhaltevermögen! Du siehst wirklich niedlich aus. Ich denke, wenn du dich richtig anstrengst, kommst du beim Publikum gut an. Ach ja - wie heißt du, Süße?}
{132}{}{.}
{133}{}{Du kannst mich Mom nennen - wie alle anderen auch. Also, du willst es versuchen? Dann zeig mal, wie du dich bewegst, ja?}
{134}{}{Okay!}
{135}{}{Vielleicht später. Ich muss noch ein paar Dinge erledigen.}

#Ïåğâûå ñìî'ğèíû â êàìîğêå
{136}{}{Was für ein Selbstvertrauen! Na gut, zeig mir, was du draufhast. }
{137}{}{[Zieh dich um und zeig, was in dir steckt]}

{138}{}{Nicht schlecht für den ersten Versuch. Du hast wirklich Talent. Ich denke, du schaffst das!}
{139}{}{Das ist großartig! Kannst du mir mehr über den Job erzählen?}

{140}{}{Sehr gern! Süße wie du verdienen am Anfang 100 $ pro Abend. Wir setzen dich erst in der Morgenshow ein - um diese Zeit ist der Club normalerweise fast leer -, damit wir dich in Aktion sehen und eine endgültige Entscheidung treffen können.}
{141}{}{Und wenn du dich entscheidest, mich zu behalten?}
{142}{}{Wenn du wirklich gut bist, trittst du nachmittags auf, wenn der Club brechend voll ist. Das ist die lukrativste Zeit, deshalb zahle ich 500 Dollar pro Stunde. Übrigens, Kätzchen, ich rate dir, die ersten paar Tage nicht zu dieser Zeit aufzutreten.}
{143}{}{Warum?}
{144}{}{Weißt du, nicht jeder Kunde benimmt sich in Lokalen wie unserem gut. Manchmal sind sie ein bisschen ... schwierig. Du musst lernen, mit ihnen umzugehen.}
{145}{}{Das klingt ein wenig beängstigend!}
{146}{}{Keine Sorge. Bewahr die Fassung, egal, was die Kunden tun. Vielleicht prügeln sie sich mitten in der Show, aber du musst es ignorieren und weitertanzen. Manche werfen Essen nach dir. Aber glaub mir, Baby, das ist keine Beleidigung, ganz im Gegenteil – das heißt, dass sie dich mögen!}
{147}{}{Das ist doch nichts! Ich komm schon klar! Ehrlich!}
{148}{}{Ugh! Mit solchen Widerlingen will ich nichts zu tun haben. Mach's gut, und entschuldige, dass ich dich belästigt habe ...}
{149}{}{Schade, Baby, wirklich schade. Ich hoffe, du findest noch den Mut dazu. Mit solchen Beinen könntest du uns gute Dienste leisten.}
{150}{}{Na ja, vielleicht ...}

{151}{}{Mmm! Ich glaube an dich. Also, komm einfach morgens wieder, sobald du bereit bist, dann bringen wir dich auf die Bühne.}
{152}{}{Danke! Das werde ich! Darauf kannst du dich verlassen!}

#Äëÿ äå'îóáèéö
{160}{}{Genau wie ich liegen auch meinen Mädchen Kinder sehr am Herzen. Wir haben dein Gesicht überall in der Stadt auf Steckbriefen gesehen. Raus aus meinem Club.}
{161}{}{[Leise gehen.]}
{162}{}{[Lügen] Ich erkläre es! Das ist eine Falle meiner Rivalen ...}
{163}{}{Ach, ich verstehe. Wenn das stimmt, erklärt das eine Menge. Ich weiß nicht, ob ich dir trauen kann, aber wenigstens darfst du im Club bleiben.}
{164}{}{Besser als nichts.}

#Äëÿ äå'îóáèéö
{170}{}{Hier gab es vor Kurzem eine Prügelei unter Betrunkenen. Weißt du etwas darüber?}
{171}{}{Ja, einer von Strykers Männern fing an, die Mädchen zu belästigen. Als die Wachen ihn zu beruhigen versuchten, provozierte er eine Prügelei und verletzte einen der Wachleute mit einer Scherbe. Unsere Jungs warfen ihn auf die Straße.}
{172}{}{Du weißt doch, dass Stryker zu den mächtigsten Leuten der Stadt gehört, oder? Man sollte meinen, du wärst vorsichtiger im Umgang mit seinen Männern.}
{173}{}{}
{174}{}{Hatte er eine Sonnenbrille auf?}
{175}{}{Danke, das wollte ich wissen.}
{176}{}{Normalerweise dulden wir besoffene Eskapaden. Aber bei diesem Kerl war es anders. Wegen seiner Beziehung zu Stryker hält er zu viel von sich. Er dachte, das würde ihn unverwundbar machen. Wir mussten ihm zeigen, dass auch Leute wie er sich an die Regeln halten und benehmen müssen. Sonst bekommen sie einen Schlagstock über den Schädel und landen auf der Straße.}
{177}{}{Ich weiß nichts davon. Es gab eine Schlägerei, Shades oder so waren mir egal.}

################################################################3
#
# Âûñ'óïëåíèÿ ÃÃ íà 'àíöïîëå
#
################################################################3

#Îáùàÿ ñ'àğ'îâàÿ ğåïëèêà
{200}{}{Da ist unser süßes Mädchen! Wie fühlst du dich?}
{201}{}{Da ist unser süßes Mädchen! Wie geht's dir?}
{202}{}{Da ist unser süßes Mädchen! Bist du gekommen, um die Tanzfläche zu erobern?}
{203}{}{Da ist unser süßes Mädchen! Vermisst du die Tanzfläche schon?}

{204}{}{Da ist unsere Königin!}

{210}{}{Ich möchte auftreten!}
{211}{}{Ich wollte nur mal Hallo sagen.}

#Ïîïû'êà íàïğîñè'üñÿ íà ñëåäóşùåå âûñ'óïëåíèå
{219}{}{Vermisst du die Tanzfläche? Aber jetzt ist noch nicht der richtige Zeitpunkt. Komm zwischen 21 und 22 Uhr vorbei.}
{220}{}{Sehr gut, aber jetzt ist kein guter Zeitpunkt. Komm morgens vor dem Mittagessen vorbei, zwischen 8 und 12 Uhr.}
{221}{}{In Ordnung.}
{222}{}{Gerade noch rechtzeitig! Los geht's ... }
{223}{}{[Wechsle deine Kleidung und geh auf die Bühne.]}

{224}{}{Komm zwischen 18 und 20 Uhr vorbei.}
{225}{}{Na gut.}
{226}{}{Vermisst du die Tanzfläche? Du kommst genau richtig!}
{227}{}{Ich bin bereit!}
{228}{}{Warte, ich bin noch nicht bereit.}
{229}{}{Du hast die Tanzfläche wohl ganz schön vermisst, was? Aber jetzt ist noch nicht der richtige Zeitpunkt. Komm heute Nacht um 1 Uhr vorbei.}
{230}{}{Oh, deine Begeisterung gefällt mir! Nun, genau jetzt ist der richtige Zeitpunkt, das Publikum zu unterhalten.}
{231}{}{Warte ... [ihr Gesichtsausdruck verändert sich] Weißt du ... ich wollte sagen ... Ich bin froh, dass du das immer noch machst. Für alle in der Stadt ist es gerade eine sehr schwere Zeit, und einen ganzen Club am Laufen zu halten, ist noch schwieriger. Aber, du weißt schon ... Keine Angst! Ich habe die lästigen Kunden nicht grundlos erwähnt. Da ist ein wirklich übler Kerl. Halte dich von ihm fern. Wenn ich diesen Hurensohn nur finden könnte. Was ich mit ihm anstellen würde ... Er taucht aus dem Nichts auf und tut unseren Mädchen schreckliche Dinge an! Hüte dich vor ... Ted Bundy. Merk dir diesen Namen und geh ihm aus dem Weg. Okay? Und jetzt ab auf die Tanzfläche. Du schaffst das, Süße!}
{232}{}{Ich habe vor keinem Ted Bundy Angst. Los geht's!}
{233}{}{Großartig! Verschwenden wir keine Zeit – zieh dich um und geh zu deinem Publikum. Sie warten auf dich.}

{234}{}{[Schaut nachdenklich zur Tür] Mmm. Weißt du, da draußen sind gerade viele Kunden, und sie sind ganz aufgeregt. Hör zu! Das ist eine große Verantwortung – ein voller Club, eine ganze Menschenmenge. Bist du wirklich bereit, Süße? Überleg es dir. Ich will dich nicht entmutigen, ich will nur wissen, ob dir danach ist. Du kannst ablehnen und an einem anderen Tag wiederkommen.}
{235}{}{Du machst mich richtig heiß! Ich liebe das Risiko! Ich bin bereit!}
{236}{}{Du machst mir Angst! Ich will das nicht tun. Was, wenn ich gleich auf der Bühne vergewaltigt werde!?}
{237}{}{Klar, ich verstehe. Komm ein andermal wieder.}
{238}{}{Bis dann.}

{239}{}{Schätzchen, bitte, setz dich hin, hab keine Angst! Ich flehe dich an, gerate nicht in Panik, okay? Du warst heute fantastisch! Vielleicht sogar ein bisschen zu fantastisch!}
{240}{}{Ist etwas passiert?}
{241}{}{Noch nicht, aber ... Oh ... Hast du gesehen, was draußen los ist? Deine Beliebtheit schlägt zurück! Gleich vor der Eingangstür steht eine ganze Horde geiler Typen. Sie wollen dich! Die Sicherheitsleute können sie kaum zurückhalten. Schnell, du musst durch die Hintertür fliehen! Wir benutzen sie nur im Notfall, dort sollte niemand sein. Setz nicht deine Gesundheit aufs Spiel, nur wegen deines Ruhms!}
{242}{}{Ich verschwinde von hier!}

{243}{}{Bitte, beeil dich! Sie suchen nach dir!}

{244}{}{Es war interessant, mit dir zu arbeiten, aber alles hat ein Ende. Ich hoffe, du bist nicht allzu enttäuscht.}
{245}{}{Na gut.}
{246}{}{Es ist schade, aber ich kann weder dich noch meinen Club aufs Spiel setzen. In Reno gibt es zu viele Verrückte. Es ist in deinem eigenen Interesse, die Bühne zu meiden.}
{247}{}{Ich verstehe ...}
{248}{}{Ich erinnere mich an unser Gespräch, aber jetzt ist keine gute Zeit zum Tanzen. Komm wie üblich vorbei – zwischen 21 und 22 Uhr.}
{249}{}{Alles ist bereit. Das Publikum wartet! Na los, Süße, mach mich stolz! Das ist deine Chance, zu glänzen!!!}

#Çàâåğøåíèå âûñ'óïëåíèé è ïîëó÷åíèå ãîíîğàğà
{250}{}{Liebling, du schaffst das, wenn du hart arbeitest. Hier ist deine erste Bezahlung. Ich hoffe, du kommst wieder. Komm am frühen Nachmittag vorbei, dann sehen wir, wie du dich machst, wenn mehr Kunden da sind.}
{251}{}{Meine erste Bezahlung! Danke!}
{252}{}{Für den ersten Auftritt gar nicht schlecht! Mädchen wie du haben eine Zukunft. Komm später zur selben Zeit vorbei, dann machen wir eine weitere Show. Ach ja, hier ist dein Geld. [She winks and whispers in your ear] Du warst gut!}
{253}{}{Danke.}
{254}{}{Du wirst immer besser! Weiter so. Ich habe darüber nachgedacht und beschlossen, dir mehr zu zahlen – du hast es dir verdient! Jetzt musst du noch eine Schippe drauflegen. Komm zwischen 21 und 22 Uhr. Dann sind mehr Kunden da, und das bedeutet mehr Geld!}
{255}{}{Danke!}
{256}{}{Weißt du, dem Publikum hat dein Auftritt sehr gefallen. Du warst gut! Wenn du dich weiter verbesserst, gehen unsere Kunden noch pleite! Ha-ha, nur ein Scherz. Aber du warst wirklich toll, also hier ist dein wohlverdientes Geld. Ruh dich aus und komm zur selben Zeit wieder. Wir warten auf dich!}

{257}{}{Ich bezahle dich gleich! Deine Show heute Abend war fantastisch! Die Kunden waren außer Rand und Band, und wir haben ein Vermögen gemacht! Du bist ein Idol für jeden Junggesellen in Reno! Pass von jetzt an auf den Straßen auf, ja? Hier ist dein Geld. Gut gemacht! Und jetzt ... Leb wohl, Süße.}
{258}{}{Auf Wiedersehen, Mama! [hug her and leave]}

{259}{}{Du erhältst einen Erfolg dafür, dass du die Kunst des Burlesque gemeistert hast.}

#Ïğîêàæåííûé
{260}{}{Es tut mir sehr leid, aber so kann ich dich nicht reinlassen. Sieh dich nur an – keine Stelle ist von der Krankheit verschont geblieben. Niemand wird sich deinen Auftritt ansehen, nicht einmal unter mehreren Schichten Make-up. Tut mir leid.}
{261}{}{Oh nein ...}

#Ïëàâàşùèå ôğàçû Ìàìàøè âî âğåìÿ âûñ'óïëåíèé ÃÃ
{270}{}{Was für ein Körper!}
{271}{}{Braves Mädchen!}
{272}{}{Ja, langsamer, Liebling, langsamer!}
{273}{}{Ja, komm schon ... Heb das Bein noch ein bisschen höher!}

{280}{}{Meine Herren! Darf ich Ihnen präsentieren!}
{281}{}{Unsere neue Miss Burlesque!}
{282}{}{Sie werden sie *lieben*!}
{283}{}{!}
{284}{}{Enttäusch mich nicht, Baby.}

{292}{}{Meine Herren!}
{293}{}{Lernen Sie unsere bezauberndste }
{294}{}{... Ihr Lieblingsmädchen kennen!}
{295}{}{Dies ist ihr letzter Auftritt!}
{296}{}{Jetzt für Sie, zum letzten Mal ... }
{297}{}{!}
{298}{}{Oh!}
{299}{}{Rock sie, Süße! MUSIK!!!}

################################################################3
#
# Ğàññïğîñû ïî ëèíåéêå êâåñ'îâ êëóáà
#
################################################################3

#Ïğî óáèéñ'âî Áàíäè
{300}{}{Ich muss dir etwas über Ted Bundy erzählen.}

{302}{}{[Ihre Augen weiten sich vor Schreck] Mein Gott, Baby, hast du ihn gesehen?!}
{303}{}{Und ob! Er kam mit einem furchtbaren Elektromesser auf mich los und schrie, er würde mir die Augen ausstechen! Ich hatte keine andere Wahl, ich musste ihn töten!}
{304}{}{[Sie sieht noch überraschter aus] Mein Gott, Baby, sieh dich nur an! Einerseits war das wahrscheinlich furchterregend, aber andererseits hast du dieser Stadt einen großen Gefallen getan!}
{305}{}{Bist du sicher?}
{306}{}{Ja! Ich ... ich habe dir nicht die ganze Wahrheit über ihn erzählt. Ich wollte dir keine Angst machen, bevor du auf die Bühne gehst. Weißt du, er ist nicht einfach nur ein Mann, er ist ein gnadenloser Mörder! Er war früher unser Wachmann, aber mir fiel auf, wie er unsere Mädchen ansah. Es war ... böse!}
{307}{}{Böse?}
{308}{}{Nach einer Weile wurde er unerträglich, belästigte die Mädchen ständig mit seltsamen Fragen und machte ihnen Angst, bevor sie auf die Bühne gingen. Die Lage spitzte sich immer weiter zu ... Schließlich feuerte ich ihn.}
{309}{}{War er also wütend auf dich?}
{310}{}{Ich weiß es nicht. Vielleicht. Aber sechs Monate später fanden wir im Hof neben der Hintertür die Leiche einer unserer Tänzerinnen. Sie war so wunderschön, und so viele Menschen liebten ihre Auftritte. Danach gab es weitere Angriffe, immer mit tödlichem Ausgang. In drei Jahren nahm er zwölf unserer Mädchen das Leben!}
{311}{}{Aber warum hat er das getan?}
{312}{}{Ich glaube nicht, dass wir je herausfinden werden, was in seinem Kopf vorging. Ich glaube auch nicht, dass ich es wissen will.}
{313}{}{Wahrscheinlich nicht.}

{314}{}{Jetzt wird das Leben leichter! Du hast eine wirklich gute Tat vollbracht. Danke. Wenn du möchtest, kannst du noch eine Nacht bleiben. Wir veranstalten eine Show zu deinen Ehren! Wir werden das Haus voll bekommen! Wir hängen überall in der Stadt Ankündigungen auf! Das wird eine Show gewaltigen Ausmaßes! Alle werden eine Menge Geld verdienen!}
{315}{}{Großartige Idee!}
{316}{}{Weißt du, ich glaube, ich habe genug. Bis dann.}

{317}{}{Na dann. Mach dich bereit und komm in ein paar Tagen nachmittags wieder!}
{318}{}{Bis später dann!}

{319}{}{Natürlich, wie du willst. Aber falls du es dir anders überlegst – denk daran, das Angebot steht noch.}
{320}{}{Ich werde darüber nachdenken.}

#Ïğî ôî'îãğàôèş ñ 'åëà Áàíäè
{350}{}{Ich habe bei diesem Freak ein Foto gefunden. Weißt du, wer sie ist?}
{351}{}{Oh ja. Das ist Susie, sie hatte einen tollen Körper. Aber sie ist vor langer Zeit verschwunden. Hübsche Mädchen wie sie leben in Reno nicht lange ... [sie seufzt traurig] Weißt du, das ist eine sehr traurige Geschichte. Ich möchte nicht darüber reden.}
{352}{}{Ich verstehe ...}
{353}{}{Ich habe dir schon gesagt, dass ich nichts weiter zu sagen habe. Susie verschwand sechs Monate, bevor Ted mit seinen Angriffen begann. Ich weiß nicht, was mit ihr passiert ist. Aber ich glaube nicht, dass es etwas Gutes war.}
{354}{}{Verstehe ...}

#Äåâóøêà íàéäåíà â Âåãàñå
{360}{}{Das Mädchen auf dem Foto – Susie. Ich habe sie in Vegas gefunden!}
{361}{}{Oh Gott! Das ist so lange her. Das heißt, sie hat überlebt. Ist sie Ted entkommen?}
{362}{}{Sie scheint der Grund dafür gewesen zu sein, dass Ted den Verstand verlor. Susie konnte seine sexuellen Wünsche nicht erfuellen und sie trennten sich. Dann begann Ted, sich an schönen Frauen zu rächen. Er stach ihnen die Augen aus, weil er Susies Wimpern schon immer gern geküsst hatte.}
{363}{}{Iih! Das ist widerlich! Vor so einem Mann wäre ich auch weggelaufen ...}
{364}{}{Sie ist jetzt in Vegas und arbeitet als Kellnerin. Sie hat Angst vor Männern, aber ansonsten scheint es ihr sehr gut zu gehen.}
{365}{}{Das arme Mädchen! Ihr ganzes Leben wurde zerstört. Aber ich freue mich, dass sie ihren Platz gefunden hat. Hübsche Mädchen haben in Reno nicht viele Möglichkeiten.}
{366}{}{Ja, sie ist dort glücklich.}
{367}{}{Danke, dass du mir das erzählt hast. Jetzt ergibt alles einen Sinn. Vergiss uns nicht und schau manchmal vorbei!}
{368}{}{Na klar! Bis dann!}

################################################################3
#
# Ïğî÷åå
#
################################################################3

#Áèëå' äëÿ Õàğäèíãà
{380}{}{Ich würde gern mit dir über eine ... lästige Person sprechen. Sein Name ist Harding.}
{381}{}{Harding? Ich kann mich an niemanden mit diesem Namen erinnern.}
{382}{}{Er besucht den anonymen Club für psychisch Kranke.}
{383}{}{Oh, jetzt verstehe ich. Kein Wunder, dass sie nicht zu uns kommen. Die armen Leute ... }
{384}{}{Hast du Mitleid mit ihnen? Vielleicht könntest du dann Harding helfen. Er leidet unter Kindheitserinnerungen an sexuelle Belästigung.}
{385}{}{Du hast Mitleid mit ihnen? Dann haben du und ich uns nichts mehr zu sagen.}
{386}{}{Vielleicht können wir später darüber reden, aber ich muss jetzt gehen.}
{387}{}{Weißt du, die Leute verändern sich, wenn sie in unserem Club sind. Jeder ist anders – manchmal verändern sie sich zum Schlechten, manchmal zum Guten. Aber Harding bekommt in seinem Leben offensichtlich einfach keine Aufmerksamkeit und Fürsorge. Unsere Mädchen könnten ihm helfen, aber nicht über die Grenzen des Anstands hinaus.}
{388}{}{Großartig! Heißt das, ich kann ihn in den Club bringen?}
{389}{}{Weißt du, ich glaube, ich kümmere mich selbst darum.}

{390}{}{Seien wir ehrlich – ich kann nicht sicher sein, dass das kein Schwindel ist und die Karte nicht jemand anderem zugutekommt. Also stelle ich eine Freikarte zum halben Preis aus. Das wären dann ... 50 Dollar.}
{391}{}{Kein Problem, hier ist das Geld.}
{392}{}{Dann eben nicht. Ich finde einen anderen Weg.}

{393}{}{Hier ist die Karte. Und sag Harding, dass wir auf ihn warten.}
{394}{}{Danke!}
{395}{}{Oh, ich weiß, dass ich dir vertrauen kann. Ich stelle dem armen Kerl sofort die Karte aus. Sag ihm, dass wir auf ihn warten.}
{396}{}{Danke, Mama!}

#Female character
{1389}{}{Weißt du, ich glaube, ich kümmere mich selbst darum.}
