{100}{}{Du siehst einen abgebrühten Milizionär.}
{101}{}{Du siehst Racer.}
{102}{}{Du siehst einen von Strykers Schergen.}

#Îáû÷íûå ğåïëèêè
{110}{}{Ja?}
{111}{}{Was?}
{112}{}{Nichts, wollte nur Hallo sagen.}
{113}{}{Nichts. Tschüss.}
{114}{}{Das war ein nettes Gespräch, aber ich muss los.}

#Çíàêîìñ'âî:
{120}{}{Was zum Teufel willst du? [Er stöhnt.] Oh Gott ... Nach der Party gestern Abend brummt mir der Schädel.}

{121}{}{Kopfschmerzen? Dann ist dein Held zur Stelle! [Moonshine geben]}
{122}{}{Kopfschmerzen? Dann ist dein Held zur Stelle! [Bier geben]}
{123}{}{Kopfschmerzen? Dann ist dein Held zur Stelle! ["Bloody Mary" geben]}
{124}{}{Kopfschmerzen? Dann ist dein Held zur Stelle! ["Rot Gut" geben]}

{125}{}{Wer bist du?}
{126}{}{Ich hätte nur ein paar Fragen ... }
{127}{}{Schon gut, schon gut, ich gehe ja.}

{130}{}{Würdest du dich verpissen? [Er reibt sich die Schläfen.] Ich habe keine Lust, irgendwelche Fragen zu beantworten. Ich kann gerade nicht mal klar denken.}
{131}{}{In all der Zeit, in der ich für Stryker arbeite, habe ich hier noch nie jemanden wie dich gesehen.}
{132}{}{Ganz genau. Sie nennen mich nicht umsonst den Racer. Wenn ich erst mal loslege, bremse ich nicht gern.}
{133}{}{Racer, hm? Nun, freut mich, dich kennenzulernen.}

{134}{}{Wirklich? Du rettest mir das Leben. Hey, setz dich und plaudere ein bisschen mit mir – ich trinke nicht gern allein.}
{135}{}{[Weiter]}
{136}{}{... Also, wie ich allen Neulingen sage: Hol dir einen Spare, dann kommt der Strike von ganz allein!}
{137}{}{Du kennst dich wohl gut mit dem Spiel aus.}

#Ğàññïğîñû
{140}{}{Erzähl mir von deinem Boss.}
{141}{}{Was macht ihr alle hier?}
{142}{}{Ihr scheint echt was draufzuhaben. Kann ich bei euch mitmachen?}
{143}{}{Jemand versucht, den Besitzer des Hotels "Silver Legacy" unter Druck zu setzen. Weißt du etwas darüber?}
{144}{}{Wohnen Strykers Leute im Keller des Bahnhofs?}

{145}{}{Stryker ist tot. Warum treibt ihr euch immer noch hier herum?}

{150}{}{Stryker? Big Louie hat ihn vor fünf Jahren mit der Stadt betraut. Stryker hat einen Plan – hier wird sich bald einiges ändern, und er wird mittendrin sein.}
{151}{}{Das ist Strykers Hauptquartier. Früher war es ein Bowlingclub, kaum zu glauben. Stryker versucht, es wieder aufzubauen, aber davon sind wir noch weit entfernt. Wenn es aber so weit ist – Mann! Dieser Ort, voller Spiele, Drinks und Leute, die Spaß haben? Stell dir das mal vor!}
{152}{}{Du musst Stryker fragen, aber er lässt nicht jeden rein. Du brauchst jemanden, der für dich bürgt. Und, äh, falls du reinkommst ... Nur ein guter Rat: Unterbrich ihn niemals, *wirklich niemals*.}
{153}{}{Wahrscheinlich wieder dieser Mistkerl Thompson. Er will unbedingt diesen Laden, aber der Besitzer will partout unabhängig bleiben. Ewig kann er aber nicht durchhalten ... Es ist nur eine Frage, wer ihn letztendlich rumkriegt.}
{154}{}{Keine Ahnung. Stryker erzählt uns nur, was wir wissen müssen. Aber es könnte sein – wir haben eine Menge Eisen im Feuer, wenn du verstehst, was ich meine.}

{155}{}{Ich ... ich weiß nicht. Zuerst dachte ich, wir würden es auch ohne ihn schaffen, aber ... Einige von uns sind abgehauen, andere wurden von Thompsons Bande umgebracht. Wenn das so weitergeht, muss ich die Stadt verlassen.}

#Ñîëîìîí
{160}{}{Kennst du Solomon?}
{161}{}{Mmmm ... Vielleicht. Warum?}
{162}{}{Jemand im El Dorado-Keller hat ihn mir empfohlen. Er sagte, du könntest mir helfen, ihn zu finden.}
{163}{}{Du meinst den kleinen Kerl? Okay, das ändert einiges. Ja, ich kann dich mit ihm zusammenbringen. Wir brauchen seine Dienste nicht mehr, aber wir halten noch Kontakt.}
{164}{}{Wir?}
{165}{}{Äh ... Vergiss das. Ich kann dich mit Solomon zusammenbringen, aber vorher musst du mir einen Gefallen tun.}
{166}{}{Was brauchst du?}
{167}{}{Also gut, pass auf. Unsere letzte Feier war in Moms Nachtclub. Ich war betrunken und, äh ... vielleicht habe ich mich ein wenig danebenbenommen. Na ja, ich *kann mich nicht genau* daran erinnern, was passiert ist. Jedenfalls habe ich jetzt Hausverbot. Leider habe ich dort meine verspiegelte Sonnenbrille liegen lassen und will sie zurück. Ich brauche dich, damit du mit meiner Eintrittskarte zum Club gehst und meine Brille holst.}
{168}{}{Ich überleg's mir.}
{169}{}{Wegen des Gefallens ... }
{170}{}{Ja?}
{171}{}{Warum fragst du mich und nicht deinen Boss?}
{172}{}{Oh, okay, ich komm schon irgendwie klar.}
{173}{}{[Er verzieht das Gesicht] Oooh ... Das ist eine etwas heikle Sache. Stryker will den Club und versucht, mit Mom zu verhandeln. Deshalb ist er nicht gerade glücklich über das, was ich, äh, getan habe. Ich würde ihn lieber nicht daran erinnern. Du verstehst, worauf ich hinauswill?}
{174}{}{Ja, verstehe. Na dann, zurück an die Arbeit.}
{175}{}{Ich habe deine Brille.}
{176}{}{Verdammt ja! [er setzt die Brille auf und sieht sich um] Abgemacht ist abgemacht. Ich melde mich bei Solomon und sage ihm, dass du vertrauenswürdig bist. Er arbeitet in einem Gebäude hinter dem El Dorado, neben dem Cotton Club. Sag ihm, dass ich dich geschickt habe.}
{177}{}{Großartig.}

#Áóíêåğ
{180}{}{Was ist das für ein Bunkereingang auf der anderen Straßenseite, im Park?}
{181}{}{Ein Luftschutzbunker aus der Vorkriegszeit. Ein paar Hundert Leute könnten dort wahrscheinlich ein paar Tage leben, aber heutzutage gibt es dafür kaum noch Bedarf.}
{182}{}{Warum ist er verschlossen?}
{183}{}{Keine Ahnung. Strykers Idee. Er glaubt wahrscheinlich, dass er jemanden findet, der den Türcode knacken kann.}
{184}{}{Türcode?}
{185}{}{Ja, da ist eine Tür, die an ein Terminal angeschlossen ist, und wir kommen einfach nicht rein. Das Ding ist wie ein verdammter Vault. Wahrscheinlich ist es die Kommandozentrale des Bunkers – weißt du, was das bedeutet?}
{186}{}{Was?}
{187}{}{Das bedeutet, dass es dort einen Radiosender, eine Stromquelle, Überwachungssysteme, medizinische Vorräte und all den Kram gibt. Die Leute vor dem Krieg haben bei ihren Bunkern keine halben Sachen gemacht. Aber wir werden es nie genau wissen, solange Stryker niemanden findet, der entweder das Terminal knacken oder die Tür sprengen kann.}
{188}{}{Sieht so aus, als hättet ihr dort schon ein paar Sachen geplündert.}
{189}{}{Ja, Stryker hat alle Überwachungssysteme ausgebaut, an die wir rankamen, und sie rund um das Hauptquartier verkabelt. Sie funktionieren prima, auch wenn die Jungs es satt haben, den ganzen Tag auf Monitore zu starren. Ehrlich gesagt brauchen wir sie nicht wirklich, aber manchmal zeichnet Stryker seine Treffen auf, falls er etwas gegen jemanden in der Hand haben muss. Aber, äh, erzähl niemandem, dass ich das gesagt habe.}
{190}{}{Wie komme ich an den Schlüssel für den Bunker?}
{191}{}{Sprich mit Stryker. Für ein paar Kröten gibt er ihn dir wahrscheinlich. Schließlich wirst du ohne Zugang zur Kommandozentrale auch nicht reinkommen.}
{192}{}{In Ordnung.}

#Female character
{1130}{}{Würdest du dich verpissen? [Er reibt sich die Schläfen.] Ich habe keine Lust, irgendwelche Fragen zu beantworten. Ich kann gerade nicht mal klar denken.}
{1133}{}{Racer, hm? Nun, freut mich, dich kennenzulernen.}
{1175}{}{Ich habe deine Brille.} #does not exist
