{100}{}{Du siehst einen Leibwächter.}
{101}{}{Du siehst einen Leibwächter, und er sieht dich.}
{102}{}{Du hast Lucianos Aufgabe erledigt.}

{103}{}{Du hast recht, ich habe wirklich zu hart gearbeitet.}
{104}{}{Wenigstens versteht mich jemand ... Freund.}
{105}{}{::schnarch::}
{106}{}{Der Wachmann döst ein. Wahrscheinlich bleibt er nicht lange weg, also solltest du dich beeilen.}
{107}{}{Was zum Teufel ist das? Du erwartest doch nicht, dass ich dieses Gesöff trinke? Besorg mir einfach ein Bier.}

#Floating dialogue on talking (male char)
{110}{}{Lenk mich nicht ab.}
{111}{}{Halt! Was willst du?}
{112}{}{Stryker hat gesagt, ich darf durch.}
{113}{}{Ich darf da nicht rein?}
{114}{}{[Er spricht in spöttischem Ton] Nein, da *darfst* du nicht rein! Niemand darf das, außer Stryker sagt es, und ich kann mich nicht erinnern, dass er irgendwas über dich gesagt hätte.}
{115}{}{Kein Problem.}
{116}{}{Na schön, aber lenk den Eierkopf nicht zu lange ab.}
{117}{}{Kein Problem.}
{118}{}{Ich bin gleich fertig. Ich habe eine Nachricht von seiner Frau. Sie macht sich Sorgen, weißt du?}
{119}{}{Warum sagst du das nicht gleich? Nur zu.}
{120}{}{Darauf falle ich nicht rein. Stryker gibt den Befehl, ich lasse dich durch.}
{121}{}{[100 $ übergeben] Verstehe, Stryker ist sehr ... streng. Lässt einen Mann nicht mal seine Frau sehen. Wie fändest du das, wenn du an seiner Stelle wärst?}
{122}{}{Hmm ... Na gut, zehn Minuten.}
{123}{}{Danke.}

#Female version
{1104}{}{Wenigstens versteht mich jemand ... Freund.}
{1118}{}{Seine eigene Frau darf ihn nicht sehen?! Was seid ihr denn für Leute?! Lasst mich durch!}	