{100}{}{Du siehst einen Milizionär.}
{101}{}{Du siehst ein Mitglied von Thompsons Sturmtrupp. Er wartet auf deine Anweisungen.}
{102}{}{Pass auf. Diese Mistkerle könnten überall sein.}

{110}{}{Hast du etwas für uns?}
{111}{}{Die Überwachung ist ausgeschaltet. Du kannst loslegen.}
{112}{}{Erinner mich, was brauchst du?}
{113}{}{Noch nichts zu melden. Ich arbeite noch an der Ablenkung.}
{114}{}{Das Hauptquartier überwacht das Gebiet. Schalte ihr Überwachungssystem aus oder zerstöre es.}
{115}{}{In Ordnung.}
{116}{}{Gut, dann kommen wir zur Sache. Wenn du nicht den Mumm hast, kannst du Thompson Bericht erstatten. Andernfalls können wir eine zusätzliche Knarre gebrauchen. Das wird ein verdammt harter Kampf.}
{117}{}{Ich bin dabei! Das würde ich um nichts in der Welt verpassen!}
{118}{}{Meine Arbeit hier ist getan. Das müsst ihr ohne mich erledigen.}

{119}{}{Mir gefällt deine Einstellung. Zeigen wir diesen Rotzlöffeln, wo sie hingehören!}
{120}{}{[Den Angriff beginnen]}
{121}{}{Dann geh uns aus dem Weg. Jetzt sind die echten Männer an der Reihe.}
{122}{}{[Zu Thompsons Hauptquartier gehen]}
{123}{}{Warte, ich habe es mir anders überlegt. Ich will euch beim Kämpfen helfen.}

#Æåíñêèå ğåïëèêè
{1123}{}{Warte, ich habe es mir anders überlegt. Ich will euch beim Kämpfen helfen.}