{100}{}{Du siehst den Kommandanten.}
{101}{}{Du siehst den Kommandanten des Angriffstrupps.}
{102}{}{Erzähl Stryker, was passiert ist.}
{103}{}{Das Gebäude ist in unserer Hand. Geh zu Stryker und überbring ihm die gute Nachricht.}

{104}{}{Du siehst ein Mitglied des Teams.}
{105}{}{Du siehst ein Mitglied des Angriffstrupps.}

{110}{}{Na, hast du die Verteidigungsanlagen sabotiert?}
{111}{}{Der Bunker hat keinen Strom. Er ist so verwundbar, wie er nur sein kann.}
{112}{}{Dann ist es Zeit zuzuschlagen. Bist du dabei oder nicht?}
{113}{}{Natürlich. So einen Kampf lasse ich mir nicht entgehen!}
{114}{}{Bin ich nicht. Ihr müsst das ohne mich erledigen.}

{115}{}{Gut. Los geht's!}
{116}{}{[Den Angriff beginnen]}
{117}{}{Dann steh uns nicht im Weg. Besser noch, melde dich bei Stryker und sag ihm, dass wir den Bunker übernehmen.}
{118}{}{[Zu Strykers Hauptquartier gehen]}
{119}{}{Eigentlich habe ich es mir anders überlegt. Ich will bei der Einnahme des Bunkers helfen.}

#Æåíñêèå ğåïëèêè
{1119}{}{Eigentlich habe ich es mir anders überlegt. Ich will bei der Einnahme des Bunkers helfen.}