{100}{}{Du siehst einen Bürger.}
{101}{}{Du siehst einen gewöhnlichen Bewohner der Slums.}

{102}{}{Was immer du willst, ich bin nicht in der Stimmung.}
{103}{}{Na gut, vielleicht komme ich später wieder.}
{104}{}{Ich mach's kurz.}

{105}{}{In diesem Haus hat mein Mann das Sagen.}

#Ïğî Õàğäèíãà
{110}{}{Jemand macht Harding schlecht. Ich will wissen, wer und warum.}
{111}{}{[Er hebt überrascht die Augenbrauen] Du bist wirklich in *seinem* Auftrag hier? Na gut, dann sag ich dir mal, was ich davon halte: }
{112}{}{SCHEISS auf diesen Drecksack! Und SCHEISS auch auf dich!}
{113}{}{Harding verdient es nicht, dass sich jemand wie du für ihn einsetzt. }
{114}{}{Harding ist ein schwächlicher kleiner Wichser und verdient alles, was ihm zustößt. Vielleicht würde man ihn mehr respektieren, wenn er nicht so erbärmlich wäre. Aber statt als Mann um Respekt zu kämpfen, zieht er es vor, Trübsal zu blasen, rumzuheulen und was auch immer in diesem Geheimclub zu tun, zu dem er jeden Freitag geht. Typen wie er werden einfach nie besser. }
{115}{}{Und jetzt raus aus meinem Haus, du winselnde, weichherzige Memme!}
{116}{}{Also, bei allem Respekt: Bitte verlassen Sie mein Haus.}
{117}{}{Was für ein Geheimclub?}
{118}{}{Irgendein seltsamer Fremder von außerhalb versammelt alle Ausgestoßenen der Gegend und hält wöchentliche Treffen ab. Er sagt, er wolle ihnen einfach nur aus reiner Herzensgüte helfen, und das ist immer ein sicheres Zeichen dafür, dass jemand nichts Gutes im Schilde führt.}
{119}{}{Ich sollte mit Harding darüber sprechen.}

#Ïîòåğÿííàÿ ïîñûëêà Ïàòğèêà
{120}{}{Hey, wusstest du, dass dein Sohn Patricks Post verloren hat?}
{121}{}{Ach, dieser selbstgerechte Scheißkerl hat also die Kekse von seiner Mama nicht bekommen? Heul mir doch einen verdammten Fluss. So hoch und mächtig ist er jetzt wohl nicht mehr, was?}
{122}{}{Sei nicht unhöflich. Ich gehe.}
{123}{}{Pass auf, was du sagst! Weißt du, für wen ich arbeite?}
{124}{}{Ich brauche nur einen Brief. Ich bezahle dafür.}
{125}{}{Du spielst mit dem Feuer, weißt du. Patrick kann nur eine gewisse Zeit geduldig bleiben.}

{126}{}{[Er wird blass] Äh - tut mir leid! Tut mir leid! Ich hab mich nur ein bisschen hinreißen lassen. Hör zu, hier gibt es kein Paket. Wir haben nie ein Paket gesehen. Wir haben nur diesen Brief, siehst du? Hier, nimm ihn! Ich kooperiere doch, siehst du?}
{127}{}{Lass das nicht noch mal vorkommen. Denk dran: In dieser Stadt gibt es zwei Arten von Leuten - die mit Waffen und die, die für sie arbeiten. Und jetzt geh mir aus dem Weg.}
{128}{}{Geld? Geld mag ich. Von wie viel Geld reden wir?}
{129}{}{Ich gebe dir 100 Dollar für den Brief.}
{130}{}{Heh! Die leichtesten hundert Dollar, die ich je verdient habe! Hier ist der Brief. Such gar nicht erst nach dem Rest des Pakets, der ist längst weg.}
{131}{}{Das überrascht mich nicht. Gib mir den Brief.}
{132}{}{Ha-ha-ha! Halt die verdammte Klappe. Ich hab ihn reden hören – „Oh, bitte, danke, Gott segne dich!“ Rückgratloser kleiner Bastard. Hier wird er niemals überleben.}
{133}{}{Er hat so lange durchgehalten. Obwohl er keine Waffen hat, obwohl er nicht von hier ist, obwohl er sich in die örtliche Politik einmischt, lebt er immer noch. Tatsächlich sieht er nicht einmal so aus, als hätte er sich sonderlich angestrengt. Und jemand schickt ihm Pakete von außerhalb. Was sagt dir das?}
{134}{}{Das – äh – [he suddenly looks very agitated] Dieses Paket ... Jemand gibt *sehr* viel Geld für ihn aus ... Äh, hör mal. Das Paket ist weg. Aber ich habe diesen Brief. Warum gibst du ihn ihm nicht? Sag ihm, äh, dass mir die Verzögerung leidtut. Wirklich, wirklich leid.}
{135}{}{Ich gebe ihm den Brief und deine Entschuldigung. Pass von jetzt an auf.}
{136}{}{Vergiss es, ich gehe.}

#Ïîäğîáíîå îïèñàíèå
{150}{}{Du siehst einen zerlumpten Mann. Er vermisst eindeutig jemanden.}
{151}{}{Du siehst einen zerlumpten Mann. Seine Augen sind vom Alkohol trüb.}
{152}{}{Du siehst einen zerlumpten Mann. Er scheint unter einem höllischen Kater zu leiden.}
{153}{}{Du siehst einen zerlumpten Mann. Er ist ganz offensichtlich betrunken.}
{154}{}{Du siehst einen zerlumpten Mann. Er wirft dir einen genervten Blick zu und verliert dann das Interesse.}
{155}{}{Du siehst einen zerlumpten Mann. Er scheint über irgendetwas, vielleicht auch über alles, stinksauer zu sein.}

{160}{}{Du siehst eine zerlumpte Frau. Sie vermisst eindeutig jemanden.}
{161}{}{Du siehst eine zerlumpte Frau. Du würdest sagen, sie ist in Gedanken versunken, aber wenn du genauer darüber nachdenkst, glaubst du, sie hat sich einfach verirrt.}
{162}{}{Du siehst eine zerlumpte Frau. Ihr Blick geht ins Leere, als wäre sie tausend Meilen weit weg.}
{163}{}{Du siehst eine zerlumpte Frau. Sie wirkt ein wenig betrunken.}
{164}{}{Du siehst eine zerlumpte Frau. Sie wirft dir einen genervten Blick zu und verliert dann das Interesse.}
{165}{}{Du siehst eine zerlumpte Frau. Als sich eure Blicke treffen, schnaubt sie verächtlich.}

# Ğàçãîâîğ
{200}{}{Weißt du, was man hier mit Leuten macht, die in fremde Häuser eindringen, um Fragen zu stellen?}
{201}{}{Ich suche nach 75 Virginia Street. Ist das hier die richtige Adresse?}

{202}{}{Ja, das ist sie. Und jetzt?}
{203}{}{Hast du das Mädchen auf diesem Bild schon einmal gesehen? Diese Adresse steht auf der Rückseite.}

{204}{}{Ich weiß nichts und will auch nichts wissen! Raus aus meinem Haus und verschwende nicht meine Zeit!}
{205}{}{Ich glaube, der Hunger macht dich gereizt. Was hältst du von 100 Dollar für eine warme Mahlzeit?}
{206}{}{Na, das war wohl ein Reinfall. Ich gehe.}

{207}{}{Was?!}
{208}{}{Wie wär's mit 200 Dollar?}
{209}{}{Na, das war wohl ein Reinfall. Ich gehe.}

{210}{}{Hey, hey, hey! Moment mal! Ich, äh, erinnere mich langsam wieder ...}
{211}{}{[Gib ihm das Geld]}
{212}{}{[Gehen]}

{213}{}{Nein, warte! Gib mir 100 Dollar, dann erzähle ich dir alles. Alles, was ich weiß!}
{214}{}{Okay, hier sind 100 Dollar. Was weißt du über dieses Mädchen?}
{215}{}{Nein, das glaube ich dir nicht. Versuch's beim nächsten Mal besser.}

{216}{}{Also gut, ich weiß nichts über dieses Mädchen. Aber bevor wir eingezogen sind, wohnte ein unheimlicher Typ in diesem Haus. Ich habe mir seine Sachen angesehen, als er auszog. Da war ein Album voller Mädchenfotos, und auf jedem einzelnen waren die Augen herausgebrannt!}
{217}{}{Wie hieß er?}
{218}{}{Ich weiß nur, dass er Ted hieß. Seinen Nachnamen kenne ich nicht.}
{219}{}{Wohin ist er gegangen?}
{220}{}{Ich weiß es nicht genau, aber er sagte, er würde irgendwohin ziehen, wo es ruhiger ist als hier. Also ist er wahrscheinlich nicht im Stadtzentrum. Ich erinnere mich auch, dass er seine Sachen südlich von hier hingebracht hat.}
{221}{}{Hat er etwas zurückgelassen?}
{222}{}{Nee, nur ein paar alte Zeitungen. Die haben wir vor langer Zeit verbrannt.}
{223}{}{Okay. Ted ist also an einen ruhigeren Ort weiter südlich gezogen. Was könnte das bedeuten? ...}
{224}{}{Übrigens, warum fragst du? Wer ist dieser Typ?}
{225}{}{Er ist ein mörderischer Wahnsinniger, der Tänzerinnen aus dem örtlichen Club zerstückelt und ihnen die Augen herausschneidet, bevor er sie umbringt. Du und deine Familie könnt von Glück sagen, dass ihr noch lebt.}

{226}{}{[Seine Augen weiten sich] Er... Das ist... Oh, Scheiße. Wirklich?}
{227}{}{Ich überlasse dich deinen Gedanken. Mach's gut.}

{228}{}{Du hast etwas von dem Geheimnis hinter Ted Bundys Foto aufgedeckt.}

#Female character
{1112}{}{SCHEISS auf diesen Drecksack! Und SCHEISS auch auf dich!}