{100}{}{Du siehst einen verwundeten Milizionär.}
{101}{}{Du siehst einen von Thompsons Männern mit einer bandagierten Schulter.}
{102}{}{Du hast einen Teil von Lucianos Auftrag erledigt.}
{103}{}{Du hättest nicht hierherkommen sollen!}
{104}{}{Dieser Raum ist belegt!}

{109}{}{Was soll das heißen?}
{110}{}{[Du siehst einen jungen Revolutionär; so jung, dass ihm die Rüstung fast von den schmalen Schultern rutscht.] Ich kann mich nicht erinnern, dass sonst noch jemand hier ein Bett gebucht hätte. Wer bist du?}
{111}{}{Thompson hat mich geschickt. Du musst mir genau erzählen, was mit eurer Gruppe passiert ist.}
{112}{}{[Ignorieren]}

{113}{}{Der Boss kümmert sich um uns. Echt toll, oder? Aber ich habe schon alles erzählt ... Na gut, vielleicht haben die anderen nicht genug Verstand dafür. Ich erzähle dir alles.}
{114}{}{Nur zu.}
{115}{}{Der Boss hat uns befohlen, in der Nähe eines Nachtclubs eine Demonstration abzuhalten, um die Öffentlichkeit auf uns aufmerksam zu machen. Es ist die belebteste Straße der Stadt. Wie befohlen versammelten wir eine Gruppe an der Kreuzung. Doch gerade als sich eine Menschenmenge zu bilden begann, wurde ich von einer Kugel getroffen. Der Schuss war lautlos, und ich konnte nicht erkennen, woher er kam. Die Menge floh sofort, während unsere Leute in Deckung gingen. Seltsam, ich weiß, aber es ist die Wahrheit. Frag die Leute auf der Straße, sie werden es bestätigen.}
{116}{}{Kannst du sagen, mit welcher Waffe du angeschossen wurdest?}
{117}{}{Leider nicht. Die Kugel ist durchgegangen. Aber falls es hilft: Ich stand an der Straßenlaterne an der Kreuzung, neben dem Haus von Mr. Wright.}
{118}{}{Das reicht fürs Erste.}

{119}{}{Tut mir leid, aber, äh, wie alt bist du?}
{120}{}{Fünfzehn, warum?}
{121}{}{Bist du nicht ein bisschen jung für Politik und Revolution?}
{122}{}{Ich bin genau im richtigen Alter, verdammt noch mal! Sieh dir an, wie weise die „Erwachsenen“ in dieser Stadt sind, bevor du mir sagst, ich sei „zu jung“. Zur Hölle mit ihnen, ich vertraue Thompson wie meinem eigenen Vater – er weiß, wohin wir müssen und was zu tun ist.}

#Ìåäèöèíñêàÿ ïîìîùü
{123}{}{Ich sehe, du hattest es nicht leicht. Tut es immer noch weh?}
{124}{}{[Richtet vorsichtig seinen Verband] Ja, manchmal tut es höllisch weh! Jetzt ist es besser, aber ich weiß nicht, wie lange noch. Wenn der Schmerz nicht bald nachlässt, muss ich mir bei den Drogenhändlern eine weitere Dosis besorgen. Und das gefällt mir nicht besonders.}
{125}{}{Nimm eine stimpak, das wird helfen.}
{126}{}{Nimm ein paar Schmerzmittel. Genau das brauchst du.}
{127}{}{Ich konnte den Autodoc reparieren. Du kannst ihn benutzen.}
{128}{}{Ich besorge dir ein paar Medikamente, keine Sorge.}
{129}{}{Dann will ich dich nicht länger stören.}
{130}{}{Das wäre großartig. Ich bin hier gerade am Ende meiner Kräfte. Thompson hat versprochen, mir Medikamente zu besorgen, aber ich habe immer noch nichts bekommen.}
{131}{}{Warum benutzt du nicht den Autodoc?}
{132}{}{Ich habe danach gefragt, aber Thompson meinte, er funktioniere nicht. Angeblich hat ihn jeder in der Stadt benutzt, nachdem das alte Rathaus aufgelöst worden war. Kein Wunder, dass er pleiteging. Und es gibt niemanden, der ihn reparieren könnte.}
{133}{}{Also gut, reden wir über etwas anderes.}
{134}{}{Dann gehe ich mal. Geschäfte, du weißt schon.}
{135}{}{Was soll das heißen?}
{136}{}{Oh!... o-oh... So schön! Der Schmerz ist weg... Danke! Ich hatte jede Hoffnung verloren, dass mir jemand helfen würde. Aber du bist besser als diese Idioten. Jetzt kann ich dem Händler sagen, wo er sich das Zeug hinschieben kann, ha-ha!}
{137}{}{Gern geschehen. Aber ich möchte trotzdem noch über etwas anderes mit dir reden.}
{138}{}{Viel Spaß damit! Ich habe noch andere Dinge zu erledigen.}
