{100}{}{Du siehst einen Milizionär.}
{101}{}{Du siehst einen von Thompsons Anhängern.}
{102}{}{Du hast einen Teil von Lucianos Aufgabe erledigt.}

{103}{}{Willst du dich anschließen? Mr. Thompson könnte an dir interessiert sein.}
{104}{}{Wir sorgen hier für Sicherheit.}
{105}{}{Mach keinen Ärger, wenn du diesen Ort lebend verlassen willst.}

{110}{}{Machst du Fotos? [er greift nach seiner Waffe] Ich zeige dir, was wir mit Spionen machen!}
{111}{}{Nein, ich bin kein Spion! Hier, nimm die Kamera. Das wird es beweisen.}
{112}{}{Schlechter Zug. Jetzt werde ich Spion und Mörder zugleich.}

#Æåíñêèå ğåïëèêè
{1105}{}{Mach keinen Ärger, wenn du diesen Ort lebend verlassen willst.}
{1110}{}{Machst du Fotos? [er greift nach seiner Waffe] Ich zeige dir, was wir mit Spionen machen!}