{100}{}{Du siehst Canary.}
{101}{}{Du siehst einen gewöhnlichen Penner ... Oder jemanden, der versucht, wie einer auszusehen.}
{102}{}{Äh, hallo.}

{109}{}{Was kann ein armer alter Landstreicher wie ich für Sie tun, Sir?}
{110}{}{Oh, werter Herr, könnten Sie einem armen, vom Pech verfolgten Landstreicher ein wenig helfen?}
{111}{}{Wer bist du?}
{112}{}{Natürlich, hier sind 10 Dollar für Essen.}
{113}{}{Ich habe eine Frage.}
{114}{}{Nicht heute.}
{115}{}{Ich habe nur eines zu sagen: "Unserem Jahrhundert ist der Glanz abhandengekommen."}
{116}{}{Mein Name ist Canary, Sir. Nur ein kleiner, umherziehender Landstreicher in einer großen Welt.}
{117}{}{Hallo, Canary. Und leb wohl.}
{118}{}{Es ist in unseren Taschen gelandet, amigo.}
{119}{}{Ist das alles, was du zu sagen hast?}
{120}{}{Ich bin nur ein einfacher Landstreicher. Was willst du noch von mir? Ich habe schon mehr gesagt, als mein Verstand verkraften kann.}
{121}{}{Wenn du meinst ...}
{122}{}{Äh ... [Als du dich zum Gehen wendest, klopft er auf seine Tasche und sieht dich an.]}
{123}{}{Na schön, hier sind 10 Dollar, Philosoph.}
{124}{}{Tut mir leid, ich bin pleite.}
{125}{}{Verpiss dich, von mir kriegst du nichts!}
{126}{}{[Er runzelt die Stirn und richtet wütend seine Lumpen] Weg von meinem Feuer! Das ist mein Platz!}
{127}{}{Na schön, hier sind 10 Dollar.}
{128}{}{Ha! Dagegen lässt sich wohl nichts sagen, was?}
{129}{}{Vielen Dank, Sir!}
{130}{}{Gern geschehen.}
{131}{}{Kannst du jetzt ein paar Fragen beantworten?}
{132}{}{Würde ich ja, würde ich, aber ach ... Der Hunger, er macht das Denken so schwer ...}
{133}{}{Hier sind zehn Mäuse, damit du deinen Hunger stillen kannst.}
{134}{}{Warte, ich bin gleich wieder da.}

{135}{}{Natürlich, Sir. Gern geschehen.}
{136}{}{Was weißt du über diesen Ort?}
{137}{}{Was ist hinter diesem Zaun?}
{138}{}{Hast du den Besitzer dieser Ranch je gesehen?}
{139}{}{Wie bist du so tief gesunken?}
{140}{}{Ich habe genug gehört.}

{141}{}{[Er zeichnet mit den Händen einen großen Kreis] Eine Ranch! Sie ist riesig! Hier wird Essen hergestellt – das Wichtigste auf der Welt.}
{142}{}{Das ist das Zuhause eines großen Mannes. Ihm gehört diese Ranch, und er lebt hier mit seiner Familie, seinen Wachen, Sklaven und brahmin. Oh, er beschützt sie gut ... Betritt man das Gelände, wird man auf der Stelle erschossen, es sei denn, man gehört zu ihnen!}
{143}{}{Oh, in Reno gibt es nicht viele wie ihn. Ein harter Brocken, ganz sicher – aber weißt du, wie Nüsse verderben? Nicht von außen, nein, sondern von innen!}
{144}{}{Ich? Oh, Wanderer, was könnte dich an einem alten Penner wie mir interessieren? Ich wurde aus Staub geboren, lebe vom Staub und eines Tages kehre ich zum Staub zurück. Dann werden sie mich vergessen, aber noch nicht – manchmal kommen die Wachen vorbei und bitten mich, etwas in die Stadt oder aus der Stadt zu bringen. Einfacher, als einen Sklaven oder eine Wache zu schicken, oder?}
{145}{}{Verstehe. Ich möchte dich noch etwas fragen.}
{146}{}{Vorerst keine weiteren Fragen.}

#Æåíñêèå ğåïëèêè
{1109}{}{Was kann ein armer alter Penner wie ich für dich tun, Madam?}
{1110}{}{Oh, schöne Madam, könntest du einem armen, vom Pech verfolgten Penner ein wenig Geld geben?}
{1118}{}{Es landete in unseren Taschen, amiga.}
{1121}{}{Wenn du meinst ...}
{1129}{}{Vielen Dank, Madam!}
{1135}{}{Natürlich, Madam. Gern geschehen.}