{100}{}{Du siehst Thompson.}
{101}{}{Du siehst einen eindrucksvollen Mann. Er trieft vor Autorität.}
{102}{}{Er sieht ungepflegt und niedergeschlagen aus.}
{103}{}{Ich gebe dir eine Minute.}

#Îòêàç â ñîòğóäíè÷åñòâå:
{110}{}{Du hast Nerven, dich hier blicken zu lassen? Ich hatte große Hoffnungen in dich gesetzt. Wir hätten gemeinsam so viel erreichen können. Wir hätten diese Stadt wieder auf Vordermann bringen können! Aber nein, du bist eine politische Hure wie alle anderen! Ich brauche dich nicht. Verschwinde!}
{111}{}{Ich gehe dann mal, bevor ich dir noch die gute Laune verderbe.}
{112}{}{Ich gehe erst, wenn ich dich umgebracht habe!}

#Ïåğâûé ğàçãîâîğ:
{115}{}{[Er mustert dich aufmerksam von Kopf bis Fuß] Du bist offensichtlich nicht zufällig hier hereingestolpert. Was willst du in meinem Hauptquartier?}
{116}{}{*Dein* Hauptquartier? Und wer hat dich zum Bürgermeister erklärt?}
{117}{}{Du hast hier eine Menge bewaffneter Männer. Ich will mehr über dich erfahren.}
{118}{}{Ich habe deine Plakate gesehen. Ich bin interessiert. Kannst du mir etwas über deine Bewegung erzählen?}

{119}{}{Sieh dich um. Ich bin die Wahl des Volkes. Sie würden für mich stimmen, wenn sie die Gelegenheit dazu hätten.}
{120}{}{Es wäre mir ein Vergnügen, aber ich habe nicht viel Zeit. Die Idee ist einfach: Wir richten das Rathaus wieder ein und führen das Amt des Bürgermeisters wieder ein, so wie es kurz nach dem Großen Krieg war. Warum, fragst du? Weil die Probleme dieser Stadt begannen, als wir die Rechtsstaatlichkeit verloren. Ohne eine zentrale Autorität verlagerte sich die Macht in die Hände der Wirtschaftsgrößen der Stadt, die versuchten, die vollständige Kontrolle an sich zu reißen. Das brachte Nachbarn gegeneinander auf und löste den Bürgerkrieg aus. Ich will alles wieder so haben wie vor 40 Jahren – und die Mehrheit der Bürger von Reno stimmt mir zu.}
{121}{}{Wir haben hier alle Hände voll zu tun. Wenn du nichts Geschäftliches zu besprechen hast, lenk die Leute nicht von ihrer Arbeit ab.}
{122}{}{Ich würde gern mehr über deine Bewegung erfahren.}
{123}{}{Verstanden.}
{124}{}{Ich will dich nicht länger aufhalten.}

#Íàïğîñèòüñÿ íà ñëóæáó:
{130}{}{[Ein Mann beugt sich zu ihm und flüstert ihm etwas ins Ohr. Nach einer Minute wendet er sich dir zu, die Augen zusammengekniffen] Wir haben nichts zu besprechen.}
{131}{}{Na gut, dann gehe ich eben.}
{132}{}{Machen wir eins klar: Jeder einzelne Mann hier steht voll und ganz hinter der Sache. Für Söldner oder „politische Huren“ ist hier kein Platz. Wenn du einer von uns sein willst, musst du mich davon überzeugen, dass du vertrauenswürdig bist und dich für die Sache einsetzt.}
{133}{}{Ich muss niemandem etwas beweisen. Ich arbeite für jeden, den ich für den Richtigen halte. Entweder du vertraust mir, oder ich gehe.}
{134}{}{Frag irgendwen in Mr. Bertolinis Casino. Mein Ruf spricht für sich.}
{135}{}{Ich habe Verbindungen zu Big Louie. Denk darüber nach. Du willst ihn als Freund. Als Feind willst du ihn *nicht*.}
{136}{}{Gib mir eine Chance! Ich hab es satt, kleine Brötchen zu backen – ich will in die großen Ligen aufsteigen!}
{137}{}{}
{138}{}{Ich höre.}
{139}{}{Ich schätze, das kann ich nicht beweisen.}

{140}{}{Heh. Wenn wir Stammesleute in der Wüste wären, hätte ich dir für so ein Gerede die Eingeweide herausgerissen. Aber hier in Reno brauche ich Leute mit deinem ... Schneid. Jedenfalls will ich dich erst einmal auf die Probe stellen.}
{141}{}{Ja, ich habe von dir gehört. Ich denke, wir können miteinander ins Geschäft kommen. Aber zuerst will ich dich auf die Probe stellen.}
{142}{}{Big One und ich haben nicht mehr das ... Verhältnis ... wie früher. Aber als Letztes will ich, dass er mir dazwischenfunkt, besonders mit der neuen Ausrüstung, die er mit sich herumträgt. Gut, aber zuerst will ich dich auf die Probe stellen.}
{143}{}{Wegen des Auftrags ...}
{144}{}{Ist es erledigt?}
{145}{}{Ich bin dran, Boss.}

{146}{}{[Erhebt die Stimme] Und was zum Teufel machst du dann hier?! Verschwende nicht meine Zeit! Wenn ich dich das nächste Mal sehe, ist der Auftrag besser erledigt!}
{147}{}{[Gehen]}
{148}{}{Hmm. Du redest selbstbewusst, und ich weiß, dass du ... Fähigkeiten ... hast, die mir nützlich sein könnten. Aber zuerst will ich sehen, ob du geeignet bist.}

#Ïåğâûé êâåñò:
{150}{}{Ein paar Halunken haben es gewagt, meine Mädchen in der Nähe des Casinos zu belästigen. Ich wollte Billy schicken, aber ich will dich in Aktion sehen. Kümmer dich um sie und komm mit dem Ergebnis zurück.}
{151}{}{Wie ist die Bezahlung?}
{152}{}{In Ordnung, ich mach's.}
{153}{}{Ich seh mir das an.}
{154}{}{Ich will Reno vor sich selbst retten, und alles, worum es dir geht, ist Geld?! Vielleicht – vielleicht! – kann Paige dir mit Geld helfen, wenn du höflich bist. So, genug geredet. Wenn ich dich das nächste Mal sehe, will ich Ergebnisse.}
{155}{}{Ich habe den Schlägern gegeben, was sie verdient haben. Jetzt wissen sie, wer hier das Sagen hat.}
{156}{}{Schlechte Nachrichten, Boss – Betty Paige ist tot.}
{157}{}{[Schlägt mit den Fäusten auf den Tisch] VERDAMMT! Das wäre nicht passiert, wenn meine Jungs ein Auge auf die Sache gehabt hätten! Ich muss meinen Vollstreckern klarmachen, wo's langgeht.}
{158}{}{Gut. Ich hoffe, du hast dich Paige gegenüber von deiner besten Seite gezeigt. Selbst ihr gegenüber dürfen wir keine Schwäche zeigen.}
{159}{}{[Weiter]}

#Äèàëîã áóäó÷è ïğèáëèæåííûì Á.Ëóè:
{160}{}{Selbst in dem Anzug siehst du noch aus wie ein Raider.}
{161}{}{Vielleicht für jemanden von außerhalb wie dich, aber hier passe ich bestens rein. Die Leute vertrauen mir.}
{162}{}{Aber du belügst sie.}
{163}{}{Natürlich belüge ich sie! Macht kommt nicht von Waffen oder Abzeichen. Sie kommt von Lügen. Je mehr du lügst, desto mächtiger wirst du – und ich kann sehr gut lügen. Niemand will die Wahrheit hören! Sie geben sich lieber als etwas aus, das sie nicht sind. Ich sage ihnen, was sie hören wollen, und biege die Wahrheit gerade so weit zurecht, dass ich bekomme, was ich will. Das ist wahre Macht.}
{164}{}{Hm, was für eine interessante Ansicht.}
{165}{}{Weißt du etwas über den Angriff auf den Kurier von Las Vegas?}
{166}{}{Big One versucht immer noch, mich auszutricksen. Er weiß, dass ich darin verwickelt sein muss – wegen meiner Beziehung zu Ricardo Bertolini. Das ist nur ein weiterer Zug in dem Spiel, das wir spielen.}
{167}{}{Reden wir von Raider zu Raider.}
{168}{}{Was?! Ach ja, stimmt. Manchmal vergesse ich, mit wem ich rede. Du siehst nicht gerade wie ein Raider aus, weißt du. Aber Big One hat ein gutes Auge für Menschen.}
{169}{}{Dann lassen wir die Vergangenheit lieber ruhen.}
{170}{}{Wie ist es dazu gekommen, dass du und Stryker jetzt so dasteht?}
{171}{}{Ich fasse mich kurz. Vor fünf Jahren übernahm Big One Reno. Nachdem er ein Jahr lang geherrscht hatte, zog er zurück ins Ödland und ließ Stryker und mich das Sagen haben. Aber dann fing Stryker mit seiner eigenen idiotischen Politik an, also trennten wir uns. Renos Geschäftsleute nutzten den Konflikt aus und versuchten, uns loszuwerden. Jetzt stehen wir mit dem Rücken zur Wand – entweder gewinnt einer von uns, oder Reno wirft uns ganz raus.}
{172}{}{Das erklärt einiges.}

{180}{}{Was ist das hier für ein Ort?}
{181}{}{Dieses Gebäude war früher Renos Rathaus, und hier unten befand sich der Luftschutzbunker für die Angestellten. Es ist lange her, dass es hier irgendeine Autorität gab. Nachdem sie den Bürgermeister rausgeworfen hatten, versuchten die Geschäftsleute, sich hier einzurichten, aber das hielt nicht lange.}
{182}{}{Was ist passiert?}
{183}{}{Bürgerkrieg. Erst kämpften die Geschäftsleute um die Stadt, dann gab es nur noch Aufstände. Das ging so, bis Big One auftauchte und seine eigenen Leute, darunter mich, an die Macht brachte.}
{184}{}{Warum hat Big Louie die Stadt verlassen?}
{185}{}{Er ist nicht so „groß“, wie alle denken, klar? Ich glaube, du hast schon eine Ahnung, was passiert ist.}
{186}{}{[Weiter]}
{187}{}{Ich werde nicht mit dir darüber reden. Das ist eine persönliche Angelegenheit, nur zwischen uns. Du willst da nicht mit reingezogen werden.}
{188}{}{Na gut.}
{189}{}{Er hatte Geld, Macht, die ganze Stadt in der Hand. Warum also ist er gegangen? Ich weiß, warum. Er wollte nichts davon. Er jagte einem Traum nach ... oder einer Erinnerung. Er wuchs in Reno während dessen „Goldener Ära“ auf, als die Leute hatten, was sie brauchten, und sich nicht gegenseitig bekämpften. Ich schätze, er dachte, er könnte das zurückbringen. Aber das war alles Schwachsinn. Reno konnte nicht mehr so sein – verdammt, vielleicht hatte das, woran er sich erinnerte, nie wirklich existiert. Und als ihm das klar wurde, rannte er zurück ins Ödland. Lieber lebt er in Einsamkeit, als mit dem Ergebnis all seiner Arbeit.}
{190}{}{Und was ist mit dir? Worauf arbeitest du hin?}
{191}{}{Sehr interessant. Ich muss erst einmal darüber nachdenken.}
{192}{}{Heh. Ich will das Sagen haben. Sieh mich nicht so an – das ist nicht einfach nur ein weiterer Schwindel. Ich weiß ein bisschen über Renos Geschichte.}
{193}{}{Welchen Teil von Renos Geschichte?}
{194}{}{Kurz nach dem Großen Krieg. Sieh dich um! Weißt du, was diese Stadt ist? Sie ist ein Denkmal für eine alte Idee. Damals wurde Reno von einem Diktator namens Bürgermeister regiert. Sein Gefolge kroch ihm zu Füßen und flehte um Gnade, seine Gegner wurden vom Erschießungskommando erledigt, und alle nutzlosen Träumer wurden in die Sklavenzellen gesteckt. Diese Geschichte lebt in der Stadt weiter. Wir können die alten Zeiten immer noch zurückbringen!}
{195}{}{Ist das der einzige Weg, die alten Zeiten zurückzubringen? Vor dem Krieg lebten die Leute auch auf andere Weise.}
{196}{}{Das kommt nicht infrage. Seit dem Großen Krieg sind drei Generationen vergangen. Es ist schwer, jemanden zu finden, der sich noch an die Welt davor erinnert. Die Menschen leben ... jetzt anders. Sie sind zu tief gesunken. Die meisten würden sich lieber den Starken unterwerfen, und die wenigen Starken in dieser Stadt haben einen Bürgerkrieg angefangen. Das ist jetzt die menschliche Natur. Wir sind *noch nicht bereit*, zu diesen Lebensweisen zurückzukehren. Bis dahin brauchen wir eine starke Führung. Wir brauchen einen Bürgermeister. Wir brauchen *mich*.}
{197}{}{Das gibt mir einiges zu denken. Ich muss darüber nachdenken.}

#Âòîğîå çàäàíèå:
{200}{}{Wir müssen der Sache auf den Grund gehen. Diese Taugenichtse müssten ziemlich dumm sein, meine Mädchen anzugreifen. Vielleicht zieht noch jemand anderes die Fäden. Mit einigen meiner Männer ist etwas passiert – ich glaube, das könnte damit zusammenhängen.}
{201}{}{Was ist passiert?}
{202}{}{Einige unserer Soldaten gerieten auf der Straße unter Beschuss. Ich möchte, dass du der Sache nachgehst. Der Überlebende ist den Flur hinunter, fang bei ihm an. Du wirst bezahlt, sobald die Ermittlungen abgeschlossen sind.}
{203}{}{Ich kümmere mich darum, Mr. Thompson.}
{204}{}{Ich habe herausgefunden, wie der Angriff auf Ihre Leute ablief.}
{205}{}{Erzähl mir alles.}
{206}{}{Den Beweisen zufolge, die ich gefunden habe, benutzte der Schütze ein schallgedämpftes Scharfschützengewehr. Er feuerte vom Balkon eines nicht als Wohngebäude genutzten Hauses gegenüber dem Casinoeingang. Der Scharfschütze arbeitete allein und muss als gewöhnlicher Bürger verkleidet gewesen sein, sonst hätte man ihn beim Verlassen des Gebäudes bemerkt.}
{207}{}{[Er nickt] Vor dem Großen Krieg nannte man solche Operationen „Operationen unter falscher Flagge“. Jetzt ist es klar: Eine dritte Partei in der Stadt versucht, Stryker und mich in einen offenen Krieg zu treiben. Wer auch immer sie sind, sie sind clever und stammen mit ziemlicher Sicherheit nicht von hier. Ich wüsste, wenn es in dieser Gegend Scharfschützengewehre gäbe.}
{208}{}{Klingt plausibel. Vielleicht sind es Söldner aus einer anderen Stadt.}
{209}{}{Viele der örtlichen Wirtschaftsbosse haben Angst vor uns. Wenn sie Söldner für Sabotage angeheuert haben, muss ich meine Überwachung in der ganzen Stadt verstärken. Das einzige Problem ist der Caravan-Parkplatz ... Aber bevor wir dazu kommen, müssen wir uns um deine Bezahlung kümmern. [Er legt ein Bündel Geld auf den Tisch und schiebt es zu dir.] Für deine Mithilfe – und in der Erwartung, dass noch mehr daraus wird.}
{210}{}{Was war das mit dem Parkplatz?}
{211}{}{Der größte Teil der Stadt gehört entweder Stryker oder mir. Das einzige neutrale Gebiet, das noch übrig ist, ist der Caravan-Parkplatz ... der Haupteingang zur Stadt. Der zweite Stock des örtlichen Hotels wäre perfekt, um alles zu überwachen. Deine Aufgabe ist es, den Hotelbesitzer, Mr. Mordino, zur Zusammenarbeit zu bewegen.}
{212}{}{Wie ... behutsam soll ich bei diesem Auftrag vorgehen?}
{213}{}{Das überlasse ich dir. Meine Kontrolle über dieses Gebiet hat Vorrang. Nutze alle nötigen Mittel. Aber wäge erst deine Möglichkeiten ab, bevor du dich entscheidest – Erpressung, ein Geschäftsangebot ... Es gibt vieles, womit man einen willensstarken Mann überzeugen kann.}
{214}{}{Verstanden, Mr. Thompson. Ich erledige das so sauber wie möglich.}
{215}{}{Hm, das wird nicht einfach. Ich sehe, was ich tun kann.}

{220}{}{Mordino ist tot. Jetzt kannst du deinen Mann im Hotel einsetzen.}
{221}{}{Hm. Das ist nicht die Lösung, die ich mir gewünscht habe. Es wird schwierig, jemanden zu finden, der das Hotel führen kann. Aber darum kümmern wir uns ein andermal – jetzt kann ich dieses Gebiet übernehmen und für Ordnung sorgen.}
{222}{}{[Weiter]}
{223}{}{Gute Arbeit. Mordino geht kein Risiko ein, also bin ich sicher, dass wir leicht mit ihm fertigwerden, solange wir seine Familie in der Tasche haben. Jetzt geh und bring die Sache zu Ende.}
{224}{}{Ich erledige das.}
{225}{}{Die Sache ist erledigt. Hier ist deine Bezahlung: tausend Dollar, dein Anteil an den Einnahmen des Hotels.}
{226}{}{Danke, Mr. Thompson.}
{227}{}{Ich konnte mit Mordino eine Einigung erzielen. Er ist zu Verhandlungen bereit.}

{228}{}{Gute Arbeit. Ich treffe mich persönlich mit Mordino, aber zuerst lasse ich meine Männer alle Zimmer und das Hotelpersonal überprüfen. Dabei werde ich deine Hilfe brauchen.}
{229}{}{Ich habe das Gefühl, das hätte sich auch anders lösen lassen ...}
{230}{}{Gerechtigkeit erfordert immer Opfer. Besonders in unserer Zeit. Hm ... Vor einem Jahr hätte ich das nicht gesagt. Reno verändert die Menschen. Dich auch, nicht wahr?}
{231}{}{Vielleicht ... }
{232}{}{Natürlich, aber unsere aktuelle Aufgabe ist noch nicht erledigt.}
{233}{}{Ich kümmere mich selbst darum. Dieses neue Gebiet wird mir einen Vorteil verschaffen, aber wir müssen alle Spuren von Strykers Einfluss beseitigen – das heißt, alle Spitzel und Dealer, die für ihn arbeiten.}
{234}{}{Was soll ich tun?}
{235}{}{Die anderen kümmern sich um die Einzelheiten. Für dich habe ich eine wichtige Aufgabe. Ich habe gehört, dass Stryker einen großen Deal eingefädelt hat, kenne aber keine Einzelheiten. Sprich mit unserem neuen Kundschafter – früher patrouillierte er an der Südmauer von Strykers Hauptquartier. Aber sei vorsichtig – vielleicht ist er ein Doppelagent. Nenne ihm den Code-Satz „Du bist so klein wie ein Käfer“ und tu dann, was immer nötig ist. Was auch immer Stryker vorhat, du musst es verhindern.}
{236}{}{Ich erledige das.}

{237}{}{Strykers Deal ist erledigt.}
{238}{}{Das ist ein weiterer Schritt nach vorn für uns und ein weiterer zurück für ihn. Seine Männer verlassen ihn bereits, was gut für uns und für Reno ist. [er reicht dir einen Stapel Geldscheine] Das hast du dir verdient.}
{239}{}{Was kommt als Nächstes?}
{240}{}{Nur noch eine Sache bleibt: der letzte Angriff auf sein Hauptquartier. Du musst dich nicht am Kampf beteiligen, mein Einsatzteam kümmert sich darum. Deine Aufgabe ist es, in ihr Hauptquartier einzudringen und ihr Überwachungssystem auszuschalten. Dadurch werden sie verwundbar und können keine Verstärkung rufen. Sobald ihre Verteidigung ausgeschaltet ist, triff den Anführer der Einsatzgruppe im Stadtpark vor Strykers Hauptquartier. Alles klar? Ich werde es nicht wiederholen. An die Arbeit!}
{241}{}{Mach ich.}
{242}{}{Stryker ist tot. Zeit, deinen Sieg zu feiern!}
{243}{}{[Atmet laut] Dieser Tag wird in die Geschichte von New Reno eingehen! Zu diesem Anlass öffnen wir eine Flasche guten alten Whiskey. Trink mit mir! Auf dich kann ich mich verlassen.}
{244}{}{Danke.}
{245}{}{Von jetzt an kannst du dich ganz offen meine rechte Hand nennen. Das wird in Reno etwas bedeuten. Jeder unter meinem Kommando wird gern mit dir zusammenarbeiten oder dir Rabatte auf seine Dienste geben. Merk dir das.}
{246}{}{Großartig!}
{247}{}{Von hier an ist es nur noch niedere Arbeit, nichts, womit ich dich beauftragen würde. Du kannst dich entspannen.}
{248}{}{Und was wirst du jetzt tun?}
{249}{}{In Ordnung. Auf Wiedersehen, Mr. Thompson!}
{250}{}{Diplomatie, Wirtschaft, die ganze Arbeit, Reno zu altem Glanz zu verhelfen. Wir müssen das Rathaus wiederaufbauen und mehr Männer anwerben. Die Reste von Strykers Bande werden wohl weiter Ärger machen – Sabotage, Attentate oder sich einfach den Schlägern auf der Straße anschließen. Für mich gibt es eine Menge zu tun.}

#Îğóæåéíûé áîíóñ
{251}{}{Ich kann im bevorstehenden Kampf helfen, aber ich brauche eine bessere Waffe.}
{252}{}{In Ordnung. Was möchtest du?}
{253}{}{[Maschinenpistole 9 mm und 40 Schuss]}
{254}{}{[Photonenpistole]}
{255}{}{[8 Splittergranaten und ein Kampfmesser]}
{256}{}{}
{257}{}{Ich habe nicht viel Ausrüstung. Ich kann es nicht riskieren, sie jemandem zu geben, der nicht damit umgehen kann. Ich vertraue meiner Einsatztruppe, deshalb bekommt sie die beste Ausrüstung.}
{258}{}{Na gut.}
{259}{}{Ich zähle auf deine Hilfe. Nimm vorsichtshalber eine stimpak.}
{260}{}{Kein Problem.}

#Êğûøà äëÿ êîíöåğòà â Êîòòîí-êëóáå
{300}{}{Ich vertrete die Cotton Club. Der Besitzer möchte dich dafür bezahlen, bei einem bevorstehenden Konzert für Schutz zu sorgen.}
{301}{}{Ist das wahr? Dieser Taugenichts kann nicht einmal seine Abgaben pünktlich bezahlen, und jetzt veranstaltet er eine Show? Hm ... Damit könnten wir alles bekommen, was er uns schuldet. Na gut, ich setze Leute darauf an, aber ich will die Hälfte seiner Einnahmen aus der Show.}
{302}{}{Ich richte es ihm aus.}
{303}{}{Mr. Thompson, wir kennen uns schon lange. Hören Sie auf mich: Unter diesen Bedingungen geht er bankrott. Vielleicht bekommen Sie jetzt Ihr Geld, aber wenn er dadurch sein Geschäft aufgeben muss, werden Sie nie wieder etwas von ihm bekommen.}
{304}{}{Sie können Ihren eigenen Preis festlegen, aber überlegen Sie es sich: Wollen Sie ein Geschäft unter Druck setzen, das ohnehin schon am Abgrund steht? Klar, Sie können Ihren eigenen Preis festlegen, aber überlegen Sie: Ergibt es Sinn, jemanden auszunehmen, der schon fast bankrott ist?}
{305}{}{Sie haben recht. Na gut, ich nehme nur ein Viertel der Einnahmen, aber ich behalte ihn im Auge.}
{306}{}{Danke, Mr. Thompson.}

#Female character
{1110}{}{Du wagst es, dich hier blicken zu lassen? Ich hatte große Hoffnungen in dich gesetzt. Wir hätten gemeinsam so viel erreichen können. Wir hätten diese Stadt wieder auf Vordermann bringen können! Aber nein, du bist eine politische Hure wie alle anderen! Ich brauche dich nicht. Verschwinde!}
{1111}{}{Ich gehe dann mal, bevor ich dir noch die gute Laune verderbe.}
{1117}{}{Du hast hier eine Menge bewaffneter Männer. Ich will mehr über dich erfahren.}
{1118}{}{Ich habe deine Plakate gesehen. Ich bin interessiert. Kannst du mir etwas über deine Bewegung erzählen?}
{1144}{}{Ist es erledigt?}
{1158}{}{Gut. Ich hoffe, du hast dich Paige gegenüber von deiner besten Seite gezeigt. Selbst ihr gegenüber dürfen wir keine Schwäche zeigen.}
{1230}{}{Gerechtigkeit erfordert immer Opfer. Besonders in unserer Zeit. Hm ... Vor einem Jahr hätte ich das nicht gesagt. Reno verändert die Menschen. Dich auch, nicht wahr?}
{1243}{}{[Atmet laut] Dieser Tag wird in die Geschichte von New Reno eingehen! Zu Ehren dieses Tages machen wir eine Flasche guten alten Whiskey auf. Trink mit mir! Dir kann ich vertrauen.}