{100}{}{Du siehst einen Reisenden.}
{101}{}{Du siehst einen erschöpften Reisenden.}

#Ïëàâàşùèå ôğàçû ïğè îòêàçå ğàçãîâàğèâàòü:
{105}{}{Bitte, ich bin müde. Lass mich ausruhen.}
{106}{}{Ich kann noch auf den Beinen stehen!}
{107}{}{Jetzt nicht. Ich will nur schlafen.}

#Ğàçãîâîğ î äîğîãå ìåæäó Óıíäîâåğîì è Ğèíî:
{110}{}{Tut mir leid, aber ich bin zu müde zum Reden. Die Reise war lang.}
{111}{}{Eine harte Reise? Das kann ich gut nachvollziehen.}
{112}{}{Dann reden wir später.}

{113}{}{Hm? ... Oh, nein, nicht so. Die Reise war in Ordnung, aber ich musste mich beeilen, um vor Einbruch der Dunkelheit hier zu sein.}
{114}{}{Ich weiß, was du meinst. Ich würde niemals eine Nacht außerhalb der Stadt verbringen!}
{115}{}{Ja, das Ödland kann nachts sehr gefährlich sein.}
{116}{}{Ha! Was, hast du etwa Angst vor der Dunkelheit?}

{117}{}{Mmm. Hör zu, ich bin gerade zu erschöpft, um mich darum zu kümmern. Komm morgen früh wieder, vielleicht fühle ich mich dann beleidigt, okay?}
{118}{}{Ach, armes Baby. Geh und mach dein Nickerchen in deinem Bettchen.}
{119}{}{Na gut. Tut mir leid, dass ich dich wach gehalten habe.}

{120}{}{Ich sollte jetzt gehen.}
{121}{}{Von wo bist du unterwegs?}
{122}{}{Tschüss.}

{123}{}{Ehrlich gesagt mache ich mir weniger Sorgen um das Ödland als um die Leute darin. Mit einem Gecko lässt sich normalerweise leichter „verhandeln“, wenn du verstehst, was ich meine.}
{124}{}{Meinst du das ernst?}
{125}{}{Oh ja. An dem Ort, von dem ich komme, bleiben die Leute nicht lange, also respektieren sie niemanden – weder Nachbarn noch Besucher.}
{126}{}{Woher kommst du?}
{127}{}{Interessant. Na dann, man sieht sich.}

{128}{}{Wendover ... Oh, richtig, davon hast du wahrscheinlich noch nie gehört. Äh, es ist ein saisonales Jagddorf in der Nähe von Salt Lake.}
{129}{}{Was hat dich hierher verschlagen?}
{130}{}{Kannst du mir zeigen, wo es liegt?}
{131}{}{Das wollte ich nur wissen. Tschüss.}

{132}{}{Sag noch mal, woher kommst du?}
{133}{}{Ja, klar.}

{134}{}{Äh, mit Karten kenne ich mich nicht aus. Wenn du mal in Salt Lake bist, frag einen Einheimischen. Der kann dir wahrscheinlich zeigen, wo es liegt.}
{135}{}{Gibt es etwas, das ich wissen sollte, falls ich mal nach Wendover komme?}
{136}{}{Das wäre alles, danke.}
{137}{}{[Er seufzt] Das ist eine lange Geschichte. Du brauchst dir deswegen keine Sorgen zu machen, das ist mein Problem.}
{138}{}{Wenn du meinst. Man sieht sich.}
{139}{}{Dort leben hauptsächlich Jäger und ihre Familien. Die Männer jagen Geckos, während sich Frauen und Kinder um ihre Hütten kümmern. Es gibt alles, was man braucht – eine Taverne, einen Laden, eine Jägergilde –, aber abgesehen davon ist dort nicht viel los. Außerdem ... wohnen viele Leute nur während der Jagdsaison dort, also glauben sie, sie könnten tun und lassen, was sie wollen, ohne dafür bestraft zu werden.}
{140}{}{Keine Strafe? Klingt nach genau meinem Geschmack! Wo liegt es?}
{141}{}{Was hast du in Reno vor?}
{142}{}{Ich weiß nicht. Hier fängt man sich leicht eine Kugel ein, wenn man nicht aufpasst. Oder die Leute um einen herum, wenn ich so darüber nachdenke. Ich muss mich wirklich anstrengen, um hier zu überleben.}

#Female character
{1114}{}{Ich weiß, was du meinst. Ich würde niemals eine Nacht außerhalb der Stadt verbringen!}
{1116}{}{Ha! Was, hast du etwa Angst vor der Dunkelheit?}
{1130}{}{Kannst du mir zeigen, wo es liegt?}