{100}{}{Du siehst einen alten Autodoc.}
{101}{}{Du siehst einen abgenutzten Autodoc.}
{102}{}{Das kannst du im Kampf nicht tun.}

#Ïåğâè÷íûé îñìîòğ
{110}{}{[Dieser Autodoc ist in einem schrecklichen Zustand, als hätte jemand versucht, damit eine Armee aus Todeskrallen zu behandeln. Er war offensichtlich lange in Gebrauch.]}
{111}{}{[Untersuche die Maschine genau.]}
{112}{}{[Die Maschine wird noch mit Strom und Medikamenten versorgt. Wenn die beschädigten Komponenten repariert würden, könnte sie noch zur Heilung eingesetzt werden.]}
{113}{}{[Weiter]}
{114}{}{[Der Medikamentenvorrat befindet sich tief im Inneren der nahe gelegenen Wand und scheint unzugänglich zu sein, vermutlich um Plünderungen zu verhindern. Dem Computer zufolge sind die Vorräte jedoch fast aufgebraucht.]}
{115}{}{[Gehen]}
{116}{}{[Dieser Autodoc wartet auf Befehle.]}
{117}{}{[Sieh dir die Maschine noch einmal an]}
{118}{}{[Beende deine Untersuchung]}
{119}{}{}

#Ïî÷èíêà è äèàãíîñòèêà
{120}{}{Diagnose des Operationsmoduls durchführen.}
{121}{}{Diagnose des Diagnostikmoduls durchführen.}
{122}{}{Diagnose des Sensormoduls durchführen.}
{123}{}{Diagnose des Radiometriemoduls durchführen.}
{124}{}{Systemweite Überprüfung durchführen.}

{130}{}{[Versuche, dieses Modul zu reparieren]}
{131}{}{[Gehen]}
{132}{}{Also, selbst ein winziger Fehler kann bei der Heilung Verletzungen verursachen. Das sollte ich zu reparieren versuchen ...}

{140}{}{Diagnose wird gestartet. Manipulatoren ... Kalibrierung erforderlich. Werkzeuge ... Kein Signal von Instrument(en): B2, B7, B18. Sterilisationssystem ... Zufuhrfehler. 3D-Scanner ... Fehlercode 402. Software ... Keine Fehler gefunden. Diagnose abgeschlossen: Modul ist nicht funktionsfähig.}
{141}{}{Diagnose wird gestartet. Werkzeuge ... Kein Signal von Instrument(en): A1, A3. 3D-Scanner ... Fehlercode 408. Software ... Diagnoseprogramme offline; Neuinstallation erforderlich. Diagnose abgeschlossen: Modul ist nicht funktionsfähig.}
{142}{}{Diagnose wird gestartet. Stereo-Einheiten ... Kalibrierung erforderlich. 3D-Scanner ... Fehlercode 411. Software ... Nicht behebbarer Absturz beim Start; Neuinstallation erforderlich. Diagnose abgeschlossen: Modul ist nicht funktionsfähig.}
{143}{}{Diagnose wird gestartet. Keine Antwort vom Modul. Diagnose abgeschlossen: Modul ist nicht funktionsfähig.}
{144}{}{Diagnose wird gestartet. Im gesamten System wurden mehrere behebbare Fehler festgestellt. Eine gründliche Reparatur durch einen zugelassenen Techniker wird empfohlen. Diagnose: System ist funktionsfähig.}

{145}{}{Neustart ... Chirurgiemodul ist funktionsfähig.}
{146}{}{Neustart ... Diagnostikmodul ist funktionsfähig.}
{147}{}{Neustart ... Sensormodul ist funktionsfähig.}
{148}{}{Neustart ... Radiometrisches Modul ist funktionsfähig.}
{149}{}{Neustart ... System ist vollständig funktionsfähig.}
{150}{}{Neustart ... Systemfehler.}
{151}{}{Irgendwo muss mir wohl ein Fehler unterlaufen sein ...}
{152}{}{[Gehen]}
{153}{}{[Weiter]}

#Ëå÷åíèå
{160}{}{Befehl: chirurgische Diagnose.}
{161}{}{Befehl: Behandlung körperlicher Verletzungen.}
{162}{}{Befehl: Behandlung fremder Toxine.}
{163}{}{Befehl: Behandlung der Strahlenkrankheit.}
{164}{}{Befehl: Behandlung fremder Infektionen.}
{165}{}{Befehl: Amputation des sechsten Fingers.}
{166}{}{Allgemeine Systemdiagnose durchführen.}

{167}{}{Operation abgeschlossen. Achtung! Der Medikamentenvorrat ist knapp. Es sind nur noch }
{168}{}{ Dosen Stimulanzien übrig.}
{169}{}{Achtung! Dem Autodoc sind die für die Operation benötigten medizinischen Vorräte ausgegangen.}
{170}{}{ Dosen Antitoxin übrig.}
{171}{}{ Dosen RadAway übrig.}
{172}{}{Operation abgeschlossen.}
{173}{}{Operation abgeschlossen. Der Finger wurde amputiert. Die Wunde wurde behandelt.}
{174}{}{ Dosen antimikrobieller Lösung verbleibend.}

{175}{}{Diagnose abgeschlossen. Aktueller Gesundheitszustand: }
{176}{}{/}
{177}{}{. Aktueller Vergiftungsgrad: }
{178}{}{. Aktueller Infektionsgrad: }
{179}{}{. Aktueller Grad der Strahlenkrankheit: }
{180}{}{.}
{181}{}{Der Autodoc versagte während der Behandlung und verursachte eine schwere Verletzung.}
