{100}{}{Das ist Chris Avellone.}
{101}{}{Du siehst Chris Avellone höchstpersönlich!}
{102}{}{Das ist Feargus Urquhart.}
{103}{}{Du siehst Feargus Urquhart höchstpersönlich!}

{110}{}{Chris, was zum Teufel!? Wer war das!?}
{111}{}{Mmm ... Was ist denn DIESES Mal los?}
{112}{}{Was los ist!? Das Ding ist voller Fehler - das ist los! Die Betatester raufen sich die Haare!}
{113}{}{Schon gut, Boss, wir beheben das.}
{114}{}{Grr ... Nehmen wir mal an, ich glaube dir. Und was ist mit dem Auto?! Warum verschwindet es ständig?!}
{115}{}{Äh, der Motor läuft nicht ganz rund ...}
{116}{}{Oh, der Motor! Dann repariert ihn doch, ihr verdammten Nerds!}
{117}{}{Wenigstens haben wir ein Auto im Spiel. Das ist cool ...}
{118}{}{Cool, ja. Vor allem, wenn man bedenkt, dass es gar nicht fährt!}
{119}{}{Nun, der Motor hat seine Grenzen. Die Programmierer haben darauf bestanden.}
{120}{}{Allerdings! So viel Arbeit, und die Hälfte unserer Skripte ist kaputt!}
{121}{}{Sonst noch was?}
{122}{}{ELSE? Ja, ich habe einen ganzen Roman über eure ungelösten Handlungslücken!}
{123}{}{Zum Beispiel?}
{124}{}{Zum Beispiel, was soll dieser Unsinn mit Myron? Wann wurde er zu einer Schlüsselfigur im Drogengeschäft von Reno?}
{125}{}{Nun, er, äh, er ist ein Genie ...}
{126}{}{Aha, ja, ja. Das erklärt alles. Na gut, das zählt tatsächlich als Ausrede.}
{127}{}{Nein, er ist wirklich ein Genie, das meine ich ernst.}
{128}{}{Außerdem gibt's da noch etwa fünf weitere unfertige Orte!}
{129}{}{Mhm ... Welcher ist der fünfte, Boss?}
{130}{}{Äh ... Was sind die ersten vier?}
{131}{}{Das frage ich ja: welche ...}
{132}{}{Schon gut, vergiss es. Und schreib bloß nichts über die EPA oder Suliks Dorf, wenn es die gar nicht gibt!}
{133}{}{Ach komm, Boss, die Spieler werden es lieben! Das wird sie dazu ermutigen, das Spiel zu modden!}
{134}{}{Dann wirf ihnen den Mapper zusammen mit ein paar Tools hin. Und was ist mit dem Intro!? Unsinn!}
{135}{}{Ein Junge, der aus einem Vault kommt? Ja, das sollten wir neu machen.}
{136}{}{Ganz genau!}
{137}{}{Andererseits haben wir Armstrong und außerdem Sex implementiert.}
{138}{}{[Verdreht die Augen] ...Sex implementiert ...}
{139}{}{Äh? ...}
{140}{}{Was? Ach ja. Hör auf, faul zu sein!}
{141}{}{Okay. Jedenfalls, was hältst du ganz allgemein vom Spiel?}
{142}{}{Nun, weißt du, trotz der Bugs glaube ich, dass Fallout 2 ... für immer leben wird.}
{143}{}{Nur bis das Zeitalter der 3D-Spiele anbricht, und dann ...}
{144}{}{Was für ein interessanter Gedanke! Führ ihn weiter aus.}
{145}{}{Weiter ausführen?}
{146}{}{Na ja, bau irgendwo mehr Dialog ein. Zum Beispiel für den Zwerg im New Reno-Boxring.}
{147}{}{Oh. Ja, praktischerweise hat er einen Dialogzweig mit Mobbing ...}
{148}{}{Großartig, mach dich an die Arbeit.}
{149}{}{Noch mehr blöde Anweisungen, Boss?}
{150}{}{Lass mich mal nachsehen. Aha, hier! Hier!}
{151}{}{Was? Was ist denn?}