{100}{}{Du siehst eine Konsole.}
{101}{}{Du siehst eine Konsole, die Zugang zum Lagerhaus gewährt.}
{102}{}{Du siehst eine Passwortabfrage auf der Konsole.}
{103}{}{Das kannst du im Kampf nicht tun.}
{104}{}{Zugang gewährt.}
{105}{}{Du hast die Konsole gehackt und dir so Zugang zur Tür verschafft.}
{106}{}{Du konntest die Konsole nicht hacken.}
{107}{}{Fehler: Die Tür reagiert nicht. Sie könnte beschädigt sein.}
{108}{}{Dein Fähigkeitswert ist zu niedrig, um das zu versuchen.}
