{100}{}{Du siehst einen Tresor.}
{101}{}{Du siehst einen verstärkten Tresor mit Zahlenschloss.}
{102}{}{Der Tresor hat all deinen Schlägen standgehalten. Er wird noch vielen weiteren standhalten.}
{103}{}{Abgeschlossen!}

{105}{}{Du hast diesen Tresor bereits geknackt.}
{106}{}{Das könnte schwieriger sein, als du dachtest.}
{107}{}{Geschafft!}
{108}{}{Falsche Dietriche.}

{109}{}{Du knackst erfolgreich das Schloss des Tresors.}
{110}{}{Du konntest den Tresor nicht öffnen.}
{111}{}{Du gibst Hueys Code problemlos ein, und das Schloss springt auf.}
{112}{}{Offen!}