{100}{}{Du setzt dir die Sturmhaube auf.}
{101}{}{Du nimmst die Sturmhaube ab.}
{102}{}{Du trägst keine Sturmhaube.}
{103}{}{Deine Sturmhaube ist in deiner Tasche, weil sie mit deinen anderen derzeit angelegten Gegenständen nicht kompatibel ist.}
{104}{}{Du kannst die Sturmhaube nicht aufsetzen. Sie ist mit deinen anderen angelegten Gegenständen nicht kompatibel.}
{105}{}{Deine Sturmhaube erfuellt ihre Aufgabe nicht besonders gut, solange du eine Jacke eines Luciano-Ranchwächters trägst.}
{106}{}{Diese Maske täuscht mich nicht! Ich weiß, wer du bist!}
{107}{}{Du hast mit einem der Tommy Guns des Casinos für Unruhe gesorgt. Luciano wird zufrieden sein.}
