{100}{}{Du siehst die Überwachungscomputer.}
{101}{}{Du siehst die Überwachungscomputer mit Zugriff auf die lokale Datenbank.}

{111}{}{[Nach Informationen über Mr. Mordino suchen]}
{112}{}{[Fertig]}
{113}{}{Du findest die Abschriften der Entscheidungen eines Ausschusses zu Mr. Mordino und seinem Hotel. Sie fielen nicht zu seinen Gunsten aus.}
{114}{}{Du findest nicht heraus, wie das geht.}
{115}{}{[Nach Informationen über Strykers Geschäft suchen]}
{116}{}{Du findest Notizen zu einem geheimen Treffen zwischen Stryker und Vertretern von Wind of War. Stryker will Chemikalien aus seinem Labor gegen Waffen, Rüstungen und Munition eintauschen. Das Geschäft soll im Silver Legacy Hotel stattfinden, in einem der Zimmer im zweiten Stock. Strykers Männer haben bereits ein Zimmer gebucht und die Sicherheitsvorkehrungen verschärft.}
{117}{}{Das war aufschlussreich ...}
{118}{}{[Das Ortungssystem deaktivieren und das Passwort ändern]}
{119}{}{[Fertig]}
{120}{}{Jetzt musst du nur noch dem Angriffstrupp mitteilen, dass er mit der Operation beginnen kann.}

{121}{}{[Die Buchhaltungsunterlagen kopieren]}
{122}{}{Du kopierst die Buchhaltungsdaten. Sie werden Lucianos Verwalter sehr nützlich sein.}
{123}{}{[Zurück]}
