{100}{}{Du öffnest den Kühlschrank und siehst mehrere aufgehängte Kondome. In jedem steckt ein menschliches Auge.}
{101}{}{[Den schrecklichen Kühlschrank schließen]}
{102}{}{Der Kühlschrank ist so grauenhaft wie eh und je.}

{200}{}{[Dich wappnen und den Kühlschrank untersuchen]}

{201}{}{Die Augen wurden in Salz eingelegt. Einige haben noch Reste von Augenlidern und Wimpern, was darauf hindeutet, dass sie Frauen gehörten. Manche haben mit der Zeit ihre gesamte Farbe verloren, was darauf schließen lässt, dass sie möglicherweise schon seit über einem Jahr hier liegen.}
{202}{}{[Unbeschädigte Kondome einsammeln]}

{300}{}{[Den Gefrierschrank öffnen]}
{301}{}{Der Gefrierschrank ist voller abgetrennter Finger. Sie stammen wahrscheinlich aus derselben Quelle wie die aufgehängten Augen.}
{302}{}{[Die Finger untersuchen]}
{303}{}{Nur wenige der Finger tragen Ringe vom Reno Club. Vielleicht waren nicht alle Opfer Tänzerinnen von Mom.}

{400}{}{[Die Kühlschranktür ansehen]}
{401}{}{In der Kühlschranktür stehen ein paar ungeöffnete Bierflaschen und eine kleine Ersatz-Energiezelle.}
{402}{}{In der Kühlschranktür ist nichts Interessantes.}
{403}{}{[Nimm das Bier und die kleine Energiezelle]}

{500}{}{[Durchsuche das untere Fach]}
{501}{}{Du findest eine verdorbene Dose Fleisch und ein vertrocknetes Omelett unbekannten Alters. Das musst du wirklich nicht probieren.}

{600}{}{[Zieh das Gemüsefach heraus]}
{601}{}{Du spürst, dass etwas darin liegt. Was könnte es sein?}
{602}{}{[Öffne das Gemüsefach]}
{603}{}{Nichts allzu Schlimmes, nur ein paar weitere Finger und Fotos. Die Finger sind sorgfältig in einen durchsichtigen Beutel gewickelt. Bei den meisten fehlen die Nägel.}
{604}{}{[Sieh dir die Fotos an]}
{605}{}{Du siehst Bilder von Mamas Tänzerinnen. Bei allen sind die Augen herausgebrannt ... bis auf eine. Auf einem Gruppenfoto siehst du das Mädchen vom Bild, das du bei der Leiche des Irren gefunden hast, mit unversehrten Augen. Vielleicht lebt sie noch!}
{606}{}{Es ist unwahrscheinlich, dass sie Ted in dieser Stadt entkommen konnte ... Hier gibt es nichts mehr zu durchsuchen.}
{607}{}{Du hast einen neuen Beweis für den Fall Ted Bundy gefunden.}