{100}{}{Willkommen in New Reno, der größten Kleinstadt der Welt. Fassfeuer und Neonreklamen tauchen die Straßen in einen höllischen Schein.}
{101}{}{Diese Gegend von Reno sieht übel aus. Hier solltest du besser auf dich aufpassen.}
{102}{}{Dieser örtliche Vault liegt irgendwo hier in der Gegend.}
{103}{}{Du bist im Geschäftsviertel von Reno. Hier liegen Luxus und Armut direkt nebeneinander.}
{104}{}{Am Stadtrand von Reno stößt du auf einen verlassenen Bahnhof.}
{105}{}{In der muffigen Luft dieses Kellers liegt ein Gefühl von Chaos.}