{100}{}{Eine Konsole.}
{101}{}{Eine Computer-Konsole zum Öffnen der versiegelten Bunkertüren.}

{102}{}{Du musst diese Konsole gerade nicht benutzen.}
{103}{}{Das hilft nicht weiter.}
{104}{}{Für diese Konsole ist ein SEHR komplexes Passwort erforderlich.}
{105}{}{Verifiziert. Druckausgleich in der Vorkammer wird eingeleitet ...}
{106}{}{Fertig}
{107}{}{Passwort erforderlich}
{108}{}{Für diese Konsole ist ein schwindelerregend komplexes alphanumerisches Passwort erforderlich. Vielleicht steht es irgendwo geschrieben?}
{109}{}{Dafür ist dieses Papier also da!}
