{100}{}{Du siehst einen Computer.}
{101}{}{Dieser Computer funktioniert noch! Er muss jahrzehntelang im Standby-Modus gewesen sein.}

{110}{}{Das Terminal enthält administrative Informationen und bietet Zugang zum Radiosender.}
{111}{}{[Kontaktiere die Biker anhand der Angaben auf dem Zettel, den Jay Kukish dir hinterlassen hat.]}
{112}{}{[Geh.]}

{120}{}{Was zur Hölle!? Wer ist da? Empfang?}
{121}{}{Hier ist Jay Kukish.}
{122}{}{Nur ein Wanderer. Ich suche Jay Kukish, ich muss mit ihm reden.}
{123}{}{Jay! Lange nicht gesehen. Ich habe gehört, du bist irgendwo in den Norden gezogen. Wie war's? Hör zu, wir haben deine Nachricht bekommen. Wir haben uns in der Nähe von Hawthorne versammelt, in einem kleinen Ort namens Bridgeport. Du weißt schon, dem voller Hinterwäldler. Komm vorbei und erzähl uns, was du herausgefunden hast. Wo bist du gerade?}
{124}{}{In New Reno.}
{125}{}{Was? Hm ... [lange Pause] ... Deine Stimme klingt ziemlich seltsam, Jay ... Okay, wer ist das?! Hey! [du unterbrichst die Verbindung]}
{126}{}{(Hm, sie wissen also nicht einmal, was Jay Kukish treibt. Warum ist er nach Vault 8 nicht zu ihnen zurückgekehrt? Ich sollte nach Bridgeport fahren und persönlich mit diesen Bikern reden. Hoffentlich sind sie freundlich.)}
{127}{}{[Die Stimme pausiert] Echt jetzt? Wir haben Jay schon eine Weile nicht mehr gesehen. Woher kennst du ihn?}
{128}{}{Er hat mein Volk betrogen und ausgeraubt. Ich werde ihn töten und mir zurückholen, was mir gehört.}
{129}{}{Ich bin mir nicht sicher. Entweder hat er mich gerettet oder ich ihn. Jedenfalls muss ich mit ihm reden.}
{130}{}{Ich glaube, wir sind Freunde. Sonst hätte er mir wohl keine Jacke, keine Waffe und keine Kontaktdaten hinterlassen.}
{131}{}{Ach ja? Na gut, ich werde dir nicht im Weg stehen. Jay ist vor ein paar Monaten verschwunden. Seitdem haben wir eine Menge Gerüchte gehört ... Hör zu, wir sollten besser persönlich reden. Wir sind in einer kleinen Stadt namens Bridgeport. Wenn du Jay wirklich sehen willst, komm her. Ende.}
{132}{}{Bridgeport ... In Ordnung. Ende.}
{133}{}{Großes Fragezeichen, hm? Das klingt ganz nach Jay. Hör zu, ich kann dir vorerst nicht helfen. Du solltest wohl herkommen und uns erzählen, was du weißt. Wir sind in einer kleinen Stadt namens Bridgeport. Wenn du Jay wirklich sehen willst, komm her. Ende.}
{134}{}{Ich weiß nicht, ob ich dir trauen kann. Vielleicht liegt Jay schon irgendwo tot in einem Graben, und du versuchst nur, unser Vertrauen zu gewinnen ... Wir sollten besser persönlich reden. Wir sind in einer kleinen Stadt namens Bridgeport. Wenn du Jay unbedingt sehen musst, komm her. Ende.}

#Information about the bunker
{160}{}{[Nach Informationen über diesen Bunker suchen]}
{161}{}{Dieses Bauwerk befindet sich unter dem Stadtplatz. Der Auftrag für seinen Bau wurde vom Büro des Bürgermeisters vergeben und aus Steuergeldern bezahlt. Es sollte als Schutzraum für die Bevölkerung dienen, falls das Gebiet um Reno bombardiert würde.}
{162}{}{[Weiter]}
{163}{}{Im Oktober 2077 suchte der Großteil der Stadtbevölkerung im Bunker Schutz. In Zeiten der Panik und des Bandenkriegs nutzten einige Familien ihn als Versteck, um die gefährliche Zeit abzuwarten. Schließlich wurde der Bunker verlassen.}
{164}{}{[Zurück]}

#Female version
{1122}{}{Nur ein Wanderer. Ich suche Jay Kukish, ich muss mit ihm reden.}
{1129}{}{Ich bin mir nicht sicher. Entweder hat er mich gerettet oder ich ihn. Jedenfalls muss ich mit ihm reden.}