{100}{}{Du siehst eine Luke.}
{101}{}{Eine dicke, schwere, gepanzerte Luke, die sich nur mit einer Schlüsselkarte öffnen lässt.}
{102}{}{Du brauchst eine Schlüsselkarte.}
{103}{}{Diese Tür lässt sich nur mit einer Schlüsselkarte entriegeln. Sie befindet sich vermutlich irgendwo in diesem Bunker.}
{104}{}{Deine Fähigkeiten sind hier nutzlos. Du brauchst eine Schlüsselkarte. Sie ist zweifellos irgendwo hier in der Nähe.}
{105}{}{Das wird nicht funktionieren.}
{106}{}{Das hat nicht einmal einen Kratzer hinterlassen.}
{107}{}{Das wird nicht helfen.}
{108}{}{Es ist zwecklos.}
{109}{}{Sie ist offen.}
{110}{}{Du entriegelst den Mechanismus.}
{111}{}{Du verriegelst den Mechanismus.}
{112}{}{Sie ist verriegelt.}