{100}{}{Diese Schalttafel scheint die Stromversorgung des gesamten zweiten Stockwerks des Casinos zu steuern.}

#Ğåìîíò
{101}{}{Der Deckel des Schaltkastens ist mit einem Vorhängeschloss gesichert.}
{102}{}{Durch diese Kabel fließt eine Menge Strom. Du solltest sie besser nicht mit bloßen Händen berühren.}
{103}{}{Die Beleuchtung im zweiten Stock wurde ausgeschaltet.}
{104}{}{Die Beleuchtung im zweiten Stock wurde eingeschaltet.}
{105}{}{Du kannst den ganzen Tag hier stehen, aber dieser Schaltkasten öffnet sich nicht von allein.}

#Âçëîì
{110}{}{Das Schloss ist bereits aufgebrochen.}
{111}{}{Das Schloss hält stand.}
{112}{}{Du brichst das Schloss mühelos auf.}
{113}{}{Dieses Schloss mit Schlüsselloch ist verriegelt.}
{114}{}{Mit einem Schlüssel verschlossen.}
{115}{}{Das Schloss ist offen.}
{116}{}{Du hast das Schloss entriegelt.}
