{0}{}{}
{100}{}{Du siehst einen Verkaufsautomaten.}
{101}{}{Du siehst einen Verkaufsautomaten aus der Vorkriegszeit.}
{102}{}{Du hast gerade Wichtigeres zu tun, als Werbung zu lesen!}
{103}{}{Das bringt nichts.}

{110}{}{Dieser Verkaufsautomat wurde vor langer Zeit geplündert. Nur die Produktliste und ein paar leere Verpackungen sind noch übrig.}
{111}{}{[Lies die Werbung an der Seite des Automaten.]}
{112}{}{[Lies die Produktliste.]}
{113}{}{[Geh.]}
{114}{}{Pretty & Glamour ist Amerikas erste Wahl in Sachen Hygiene und Körperpflege. Wir bieten alles, was du brauchst, um selbstbewusst, stilvoll und attraktiv zu sein! Mit Pretty & Glamour kannst du dein Bestes geben!}

{115}{}{Du hast derzeit }
{116}{}{ von sieben Pretty-&-Glamour-Produkten dabei. Du hast }
{117}{}{[Pack alles in eine Schachtel.]}
{118}{}{, }
{119}{}{.}

{120}{}{Thorium-Zahnpasta}
{121}{}{mit Radium angereichertes Heilwasser}
{122}{}{Radon-Badesalz}
{123}{}{Rasierer „Atomic Blades“}
{124}{}{intelligentes Handtuch}
{125}{}{Duftseife}
{126}{}{Feuchttücher}
{127}{}{}
{128}{}{}
{129}{}{}

{130}{}{Du sammelst sorgfältig alle Gegenstände in einer Schachtel. Du hast ein echtes, vollständiges Pretty-&-Glamour-Körperpflegeset zusammengetragen! Damit werden dich alle kultivierten Gesellschaftsdamen im Nevada der Gegenwart beneiden!}
{131}{}{Ich bin bereit, auszugehen!}
{132}{}{Dir fehlt noch etwas.}
{133}{}{Verdammt ...}
{134}{}{Nichts auf der Produktliste sieht aus wie etwas in deinem Inventar.}
