{100}{}{Du siehst einen Spielautomaten.}
{101}{}{Du siehst einen Spielautomaten mit blinkenden Lichtern.}
{102}{}{Dieser Spielautomat ist gerade besetzt.}
{103}{}{Du bekommst nichts aus diesem Automaten.}
{104}{}{Dieser Automat ist in Ordnung und funktioniert.}
{105}{}{Nichts.}
{106}{}{Ein gewöhnlicher Spielautomat. Sieht aus wie jeder andere hier im Raum.}

{107}{}{Du untersuchst die Maschine und findest den Grund für die hohe Verlustquote: Jemand hat die Walzen falsch eingesetzt und so die Gewinnchancen verringert.}
{108}{}{Das erklärt alles!}