{100}{}{Du siehst Dokumente auf einem Tisch.}
{101}{}{Du siehst verschiedene Karten und andere Dokumente, die über einen Tisch verstreut sind.}
{102}{}{Im Kampf kannst du nicht lesen!}

{150}{}{Diese Dokumente gehören dem Rekrutierungsoffizier. Er wird es wahrscheinlich nicht schätzen, wenn du sie durchsiehst.}
{151}{}{Diese Dokumente enthalten Berichte für den Nevada Express-Verwalter sowie aktuelle Karten von Nevada.}
{152}{}{[Suche nach Orten, die du noch nicht entdeckt hast]}
{153}{}{Geh weg.}

{154}{}{Du siehst die Dokumente durch, findest aber nichts Neues.}
{155}{}{Du hast etwas Interessantes gefunden.}
{156}{}{Übertrage die Koordinaten der überfallenen Postkutsche in deinen Pip-Boy.}
{157}{}{Übertrage die Koordinaten von Las Vegas in deinen Pip-Boy.}
{158}{}{Übertrage die Koordinaten von Salt Lake City in deinen Pip-Boy.}
{159}{}{Übertrage die Koordinaten von Lovelock in deinen Pip-Boy.}
{160}{}{Übertrage die Koordinaten von Wind of War in deinen Pip-Boy.}
{161}{}{Übertrage die Koordinaten von Hawthorne in deinen Pip-Boy.}
{162}{}{Übertrage die Koordinaten von Black Rock in deinen Pip-Boy.}
{163}{}{Übertrage die Koordinaten von Wendover in deinen Pip-Boy.}
{164}{}{[Weiter suchen]}
{165}{}{[Fertig]}
{166}{}{Du suchst auf der Karte nach neuen Orten.}
{167}{}{Du findest nichts Interessantes.}
{168}{}{[Von den Karten zurücktreten]}
{169}{}{Übertrage die Koordinaten von Uranium City in deinen Pip-Boy.}