{100}{}{Du siehst den Anführer.}
{101}{}{Du siehst den Anführer des Konvois.}

{102}{}{Man sieht sich ... Partner.}

{110}{}{Wer zum Teufel bist du?}
{111}{}{Ich bin nur auf der Durchreise. Was transportiert ihr?}
{112}{}{Ich bin, äh, hier, um die Ware abzuholen.}
{113}{}{Ich weiß, warum du hier bist. Ich mache dir ein besseres Angebot: Verkauf mir die Waffen und geh lebend von hier weg.}
{114}{}{Ach, ich geh nur spazieren. Tschüss.}

{120}{}{Auf der Durchreise? Bis hierher? Mitten in der Nacht? ... Dann zieh einfach weiter. Hier gibt's nichts zu sehen.}
{121}{}{Ach ja? [Er mustert dich misstrauisch.] Mir wurde gesagt, ich soll auf einen Funkspruch warten, aber ich habe nichts gehört. Was ist los?}
{122}{}{}
{123}{}{Äh ...}
{124}{}{Wir hatten technische Probleme mit dem Funkgerät. Hast du die Ware oder nicht?}
{125}{}{}
{126}{}{Sag mir das Passwort.}
{127}{}{Äh ... „Hurensöhne“?}
{128}{}{Passwort? Niemand hat mir etwas von einem Passwort gesagt.}

{129}{}{[Die Karawanenhändler machen ihre Gewehre bereit und sehen sich misstrauisch um] Also, was zum Teufel ist hier los?! Wenn du nicht von Bertolini bist, wer bist du dann?}
{130}{}{Bertolini ist tot. Ihr seid den ganzen Weg umsonst gekommen. Aber ich weiß von eurem Geschäft und bin bereit, ein Gegenangebot zu machen.}
{131}{}{Ich vertrete Bertolinis Konkurrenz. Wir sind viel mächtiger als er. Es liegt in eurem Interesse, mit uns zusammenzuarbeiten.}

{132}{}{Hmm. Na gut, wir sind den ganzen Weg aus dem Boneyard hierhergekommen und haben die Dinger dabei. Wir nehmen sie ganz sicher nicht wieder mit zurück. Also gut, ich verkaufe sie euch, aber glaubt nicht, dass ihr einen Rabatt bekommt.}
{133}{}{Ich verkaufe es dir für $}
{134}{}{Mein Boss würde gerne auch in Zukunft mit euch Geschäfte machen, aber diese Preise sind unangemessen. Wenn ihr diese Gelegenheit nutzen wollt, müsst ihr sie senken.}
{135}{}{Euer Pech. Mein Boss würde gerne auch in Zukunft mit euch Geschäfte machen ...}
{136}{}{Ich habe eine andere Idee: Lasst die Ware hier und verschwindet, dann lasse ich euch am Leben.}
{137}{}{Der Preis gefällt mir nicht. Ich glaube, ich nehme lieber die Ware und euer Leben. [Angreifen.]}
{138}{}{Wartet, ich hole das Geld.}

{139}{}{[Die Wachen zählen das Geld und lassen dich die Waffen in den Kisten überprüfen] Also gut, wir sind fertig. Sag deinem Boss, dass das nicht noch einmal vorkommt. Wir wollten eine langfristige Geschäftsbeziehung aufbauen, aber das hier ist viel zu zwielichtig. Wir verschwinden jetzt.}
{140}{}{[Weiter]}
{141}{}{Klingt gut ... fürs Erste. Aber wenn es beim nächsten Mal Ärger gibt, war es das letzte Mal. Klar?}
{142}{}{Du konntest den Preis pro Bestellung um 500 $ drücken. Die Ersparnis landete in deiner Tasche.}
{143}{}{Willst du mich verarschen? Setz dich, Kleiner. Ich handle schon, bevor du überhaupt geboren warst, und das ist so ziemlich das schlechteste Angebot, das ich je gehört habe. Das ist der Preis, nimm ihn oder lass es.}
{144}{}{Ach ja? [Er stemmt die Hände in die Hüften und verengt die Augen] Ist das deine erste Abzocke, Kleiner? Denn meine ist es verdammt noch mal nicht. Mir ist egal, welche Verstärkung du hast, wir lassen uns nicht so leicht einschüchtern. Also sag deinen Freunden, sie sollen nach Hause gehen, damit wir wie Erwachsene reden können.}

#İòîò ğàçãîâîğ íå èñïîëüçóåòñÿ:
{150}{}{Woher habt ihr die Waffen?}
{151}{}{Aus einer Werkstatt im Boneyard. Sie bauen dort Waffen nach Vorkriegsbauplänen. Zähe Burschen, die Truppe. Sie sind seit etwa zehn Jahren im Geschäft, aber abgesehen von ein paar Auftragsarbeiten stellen sie Waffen hauptsächlich für sich selbst her.}
{152}{}{Gehörst du zu ihnen?}
{153}{}{Nee, die Typen verlassen die Werkstatt so gut wie nie. Wir sind die Far Go-Händler aus dem Hub. Normalerweise kommen wir nicht bis hierher.}
{154}{}{Und was sind sie? Waffenfanatiker?}
{155}{}{Nicht ganz. Es ist einfach das Einzige, was sie können ... abgesehen von ihrer kriminellen Vergangenheit. Sie kamen vor einiger Zeit in den Boneyard, in der Hoffnung, sesshaft zu werden. Sie verschanzten sich in einer alten Waffenfabrik und gruben einen Graben voller radioaktivem Glibber. Ich schätze, die alten Baupläne müssen dort herumgelegen haben. Anfangs redeten sie mit niemandem, aber irgendwann fingen sie an, Waffen und Munition gegen Lebensmittel zu verkaufen. Im Grunde sind die Waffen das Einzige, was sie über Wasser hält.}

#Æåíñêèå ğåïëèêè
{1110}{}{Wer zum Teufel bist du?}
{1112}{}{Ich bin, äh, hier, um die Ware abzuholen.}
{1130}{}{Bertolini ist tot. Ihr seid den ganzen Weg umsonst gekommen. Aber ich weiß von eurem Geschäft und bin bereit, ein Gegenangebot zu machen.}
{1153}{}{Nee, die Typen verlassen die Werkstatt so gut wie nie. Wir sind die Far Go-Händler aus dem Hub. Normalerweise kommen wir nicht bis hierher.}