{100}{}{Du solltest besser nichts anfassen. Vor allem nicht den großen roten Knopf ... oder den anderen.}
{101}{}{Das kannst du im Kampf nicht benutzen.}
{102}{}{Dieser Konsole kommt keine weitere Verwendung zu.}

{104}{}{Du siehst ein Terminal zur Steuerung des Funkverkehrs. Offenbar benutzen die Wachen das Funkgerät zur Kommunikation, aber über die Konsole kannst du mehr über andere Befehle herausfinden.}
{105}{}{[Setze deine Computerkenntnisse ein, um alle Sklavenhalsbänder zu deaktivieren]}
{106}{}{[Aktiviere die Selbstzerstörung aller Halsbänder]}
{107}{}{[Gehen]}
{108}{}{Du findest nicht heraus, wie das geht.}
{109}{}{Befehl eingeleitet.}
{110}{}{[Verlassen]}
{111}{}{[Versuche, das System mit deinen technischen Kenntnissen zu deaktivieren]}
{112}{}{Das Kontrollsystem ist deaktiviert.}
{113}{}{[Ende]}
{114}{}{Du kriegst es einfach nicht heraus.}
{115}{}{[Zurück]}