{100}{}{Das ist eine ganz normale, stabile Tür.}
{101}{}{Diese Tür ist verriegelt und kann nur von innen geöffnet werden.}
{102}{}{Diese Tür ist verriegelt und lässt sich von dieser Seite aus nicht öffnen.}
{103}{}{Von innen verriegelt.}
{104}{}{Du entfernst die Bolzen und öffnest die Tür.}
{105}{}{Von der anderen Seite abgeschlossen.}
{106}{}{Geöffnet.}
{107}{}{Nicht einen Kratzer.}
{108}{}{Die Explosion reißt die Tür aus den Angeln. Sie fällt mit einem lauten Krachen zu Boden.}