{100}{}{Du siehst ein schäbiges Plakat.}
{101}{}{Du siehst ein altes, ramponiertes Plakat. In der Mitte kannst du eine seltsame Ausbuchtung sehen, die aus der Wand ragt.}
{102}{}{Dieses Plakat ist ein Relikt. Du glaubst nicht, dass es seinem Besitzer gefallen würde, wenn du es beschädigst.}
{103}{}{Unter dem Plakat findest du einen Safe voller Wertgegenstände.}
{104}{}{Wow, hier ist eine Menge drin!}
{105}{}{Ich bin nur neugierig auf den Film.}
{106}{}{Ein klassisches Drama über einen Gangster mit Prinzipien. Im postnuklearen Ödland wirkt es sehr naiv.}