{100}{}{Du siehst einen Lüftungsschacht.}
{101}{}{Du siehst die Lüftungsanlage. Sie funktioniert nicht, was nicht besonders überraschend ist.}
{102}{}{Du siehst die Lüftungsanlage. Überraschenderweise funktioniert sie noch.}
{103}{}{Du hörst, wie die Anlage anspringt, aber einer der Ventilatoren dreht sich immer noch nicht.}
{104}{}{Kaputt.}
{105}{}{Dieser Ventilator funktioniert einwandfrei.}

#Repair attempts (skill or tools)
{106}{}{Du bist nicht geschickt genug, um das Problem zu beheben.}
{107}{}{Ich krieg das nicht hin.}
{108}{}{Du hast die Anlage bereits repariert. Du musst es nicht zweimal tun.}
{109}{}{Wenn es nicht kaputt ist, repariere es nicht!}
{110}{}{Du hast die Lüftung repariert.}
{111}{}{Erledigt!}