{100}{}{Die Eingangstür.}
{101}{}{Eine Tür, die zum Nachtclub führt. Sie scheint gut bewacht zu sein.}
{102}{}{Das bringt nichts.}
{103}{}{Die verstärkte Tür hält deinen schwächlichen Schlägen stand.}
{104}{}{ Dollar.}

#For male PC
{105}{}{Guten Tag, mein Herr. Hier, um sich zu entspannen? Der Eintritt beträgt }
{106}{}{Kein Problem. Hier ist das Geld.}
{107}{}{Ich habe es mir anders überlegt. Entschuldigen Sie die Störung.}
{108}{}{Ich habe gerade nicht genug Geld dabei. Vielleicht ein andermal.}

{109}{}{Äh ... Sind Sie sicher, dass Sie hier richtig sind, Ma'am? Das ist ein Club für *Herren*.}
{110}{}{Was ist das Problem? Vielleicht möchte ich mir auch eine Tanzvorführung ansehen!}
{111}{}{Eigentlich möchte ich mit Ihrer Chefin sprechen. Vielleicht könnte ich ja für sie arbeiten?}
{112}{}{Oh, das wusste ich nicht! Ich gehe dann einfach.}

{113}{}{Wie Sie wünschen, Ma'am. Der Eintritt beträgt }
{114}{}{Na gut ... Kommen Sie rein. Mamas Büro ist links.}
{115}{}{Danke.}
{116}{}{Ich habe es mir anders überlegt. Entschuldigen Sie die Störung.}

{117}{}{Keine Sorge, ich habe eine Einladung.}
{118}{}{Gehen Sie ruhig durch, mein Herr.}
{119}{}{Gehen Sie ruhig durch, Ma'am.}
{120}{}{ Guten Tag.}
{121}{}{Gute Nacht.}

#If the PC is an enemy of the club
{130}{}{Diese Tür ist von innen verriegelt. Es klingt nicht, als hätte es jemand eilig, sie zu öffnen.}
{131}{}{Hey, was soll das!? Was ist aus „Der Kunde ist König“ geworden?}