#Backdoor
{100}{}{Du siehst eine Tür.}
{101}{}{Du siehst einen Notausgang. Er wirkt stabil.}
{102}{}{Deine Schläge können der Tür nichts anhaben.}
{103}{}{Die Tür ist von innen verbarrikadiert.}
{104}{}{Da kann ich nichts machen.}

#Changing room
{105}{}{Du siehst die Tür zum Personalraum. Sie wirkt stabil.}
{106}{}{Die Tür ist verschlossen.}
{107}{}{Diese Tür ist verschlossen.}
{108}{}{Diese Tür ist jetzt entriegelt.}