{100}{}{Ein kleiner Generator. Wenn du mehr Zeit hast, kannst du ihn dir noch etwas genauer ansehen.}
{101}{}{Du untersuchst den Generator, findest aber nichts Interessantes heraus.}
{102}{}{Dieser Generator muss nicht repariert werden.}
{103}{}{Nach der Untersuchung des Generators stellst du fest, dass er von einem anderen Ort hierher gebracht wurde. Die übrige Computerausrüstung wahrscheinlich auch.}
{104}{}{Interessante Infos – aber für mich nutzlos ...}
