{100}{}{}
{101}{}{}

#Òèïîâûå ğåïëèêè
{139}{}{Das ganze Radon lässt deinen Rucksack warm werden.}
{140}{}{Du hast dein Ziel nicht getäuscht.} #If this exclusively refers to traps, I'd prefer "The target evades your trap."
{141}{}{Das Gerät wirkt erfolgreich auf das Ziel ein.} #If this exclusively refers to traps, I'd prefer "You catch the target in your trap."

{142}{}{Wird ausgeführt}
{143}{}{Fertig}

{150}{}{}
{151}{}{}
{152}{}{Du solltest das behalten, bis der Auftrag erledigt ist.}
{153}{}{Dieser Dieb ist zu erfahren, um auf deinen Trick hereinzufallen.}
{154}{}{Du wurdest wegen Schummelns vom Dartspiel ausgeschlossen.}
{155}{}{Dieser Ghul beobachtet dich ganz genau. Versuch gar nicht erst, ihn zu täuschen.}
{156}{}{Nein}

####################################################################
#              Óñòàíîâêà ëîâóøåê
####################################################################

{158}{}{Dort ist bereits eine Falle.}
{159}{}{Hier ist kein Platz für diese Falle.}

{160}{}{Wird ausgeführt ...}
{161}{}{Nur eine Minute ...}
{162}{}{Ganz ruhig!}
{163}{}{Ich mach's ja schon ...}
{164}{}{Sie werden nichts ahnen.}
{165}{}{Leck mich, Baby!}
{166}{}{Das dürfte den Genpool bereinigen.}
{167}{}{Eine heiße Überraschung, kommt sofort!}
{168}{}{Was für ein verdammt gutes Easter Egg ...}
{169}{}{Heh-heh-heh ...}
{170}{}{Einen Moment}
{171}{}{Bevor mich jemand sieht ...}

{180}{}{Du wurdest entdeckt!}
{181}{}{Hey! Was machst du da?!}
{182}{}{Während eines Kampfes kannst du keine Fallen stellen.}

####################################################################
#              Äîñòèæåíèÿ
####################################################################

{183}{}{Dein Chem-Missbrauch hat dir dauerhaften Schaden zugefügt.}
{184}{}{Ooooh, Mann, ich bin total fertig ... Völlig fertig ...}

{185}{}{Es spricht sich herum. Bei den Karawanenhändlern hast du dir einen guten Ruf erarbeitet.}
{186}{}{Es spricht sich herum. Deinen guten Ruf bei den Karawanenhändlern hast du verloren.}
{187}{}{Du hast einen neuen Erfolg errungen und deinen Intelligenzwert erhöht, weil du so viele Kriminalfälle gelöst hast.}
{188}{}{Du hast gelernt, Heilpulver und Gegengift herzustellen.}
{189}{}{Schon viel besser!}
{190}{}{Dein diszipliniertes körperliches Training hat dich attraktiver gemacht!}
{191}{}{Für das Knacken zahlreicher Schlösser hast du den Erfolg „Meisterknacker“ errungen.}

#Ñ÷åò÷èê âèğóñà
{192}{}{Du fröstelst leicht, und das will einfach nicht aufhören.}
{193}{}{*hust, hust*}
{194}{}{*Ugh*}
{195}{}{Glückwunsch! Deine Krankheit hat sich zu ausgewachsener Lepra entwickelt.}
{196}{}{Du fühlst dich fiebrig und übel.}
{197}{}{Du hustest ständig Blut. Du brauchst medizinische Hilfe!}
{198}{}{Du leidest an einer ansteckenden Krankheit.}
{199}{}{Du fühlst dich weniger krank als zuvor.}

#Äîïîëíèòåëüíî:
{200}{}{Dein Pip-Boy zeigt den Grad deiner Strahlenvergiftung an: }
{202}{}{Du bist jetzt als „Held der Slums“ bekannt.}
{203}{}{Wie schnell sie doch vergessen. Du bist nicht länger als „Held der Slums“ bekannt.}
{204}{}{Du hast gelernt, Heilpulver und Gegengifte herzustellen.}
{205}{}{Du hast gelernt, wie man „Blutreiniger“-Medizin und „Pferdetöter“-Gift herstellt.}
{206}{}{Du hast gelernt, wie man „Blutreiniger“-Medizin, „Pferdetöter“-Gift, Heilpulver und Gegengifte herstellt.}
{207}{}{Du hast dir den Ruf „Speichellecker“ erworben. Natürlich funktioniert das nicht, wenn du ihnen davon erzählst.}
