{100}{}{Du siehst Rico.}
{101}{}{Du siehst einen muskulösen Türsteher namens Rico.}

{102}{}{Misch dich nicht ein. Das geht dich nichts an.}
{103}{}{::nickt respektvoll::}
{104}{}{Wir brauchen hier mehr Leute wie dich.}

{110}{}{Suchst du Ärger in meinem Laden?}
{111}{}{Ja, und ich habe gerade welchen gefunden. Ich werde mich jetzt darum kümmern.}
{112}{}{Ich muss den Kerl sehen.}
{113}{}{Ich wollte nur kurz Hallo sagen. Bis später.}

{120}{}{[Er lässt die Knöchel knacken] Das war's. Du hast es so gewollt.}
{121}{}{Warte, warte, es tut mir leid! Das kommt nicht wieder vor!}
{122}{}{Warte, ich will ihn doch nur sehen!}
{123}{}{Nur zu, du Fleischsack!}

{124}{}{[Er atmet langsam durch die Nase aus] Heute hast du Glück. Beim nächsten Mal pisst du Blut.}
{125}{}{Äh ...}

{126}{}{Du schon wieder? Verpiss dich. Das ist deine letzte Warnung.}
{127}{}{Okay, okay, ich hab's verstanden.}
{128}{}{Das war's. Jetzt bist du dran!}
{129}{}{Komm doch her.}

{130}{}{Da darfst du nicht hin. Wenn du den Gefangenen sehen willst, sprich mit Gerlach.}
{131}{}{Ich gehe, wohin ich will. Halt dich zurück, bevor ich wütend werde.}
{132}{}{Gerlach hat gesagt, ich darf mit ihm sprechen.}
{133}{}{Okay, ich gehe zu deinem Boss.}

{134}{}{[Er murmelt etwas vor sich hin] ...Na gut. Versuch da drin keinen Ärger zu machen.}
{135}{}{Natürlich!}

{136}{}{Reparier zuerst die Pumpe. Wenn du fertig bist, kannst du den Gefangenen sehen.}
{137}{}{Du solltest darüber nachdenken, netter zu mir zu sein. Papa Gerlach passt nicht mehr auf dich auf.}
{138}{}{Na gut, aber ich komme wieder.}

#Æåíñêèå ğåïëèêè
{1127}{}{Okay, okay, ich hab's verstanden.}
{1129}{}{Komm doch her.}
