{100}{}{Du siehst Steve.}
{101}{}{Du siehst einen dürre wirkenden Kerl. Seine Kleidung ist schmutzig und mit Rostflocken bedeckt.}

#Ïëàâàşùèå î'âå'û
{102}{}{Hilfe! Sie werden mich umbringen!}
{103}{}{Du Mistkerl!!! Sie war alles, was ich hatte!}
{104}{}{Oh Gott! Sie war alles, was mir noch geblieben war!}

#########################################################
#
#  Ğàçãîâîğ â 'şğÿãå
#
#########################################################

{110}{}{Du hast mir das Leben gerettet! Wie lange noch, weiß ich nicht, aber bevor du aufgetaucht bist, hatte ich keine Chance!}

{111}{}{Gerlach ist tot. Du bist jetzt frei.}
{112}{}{Was ist passiert?}
{113}{}{Wegen der Wasserpumpe ...}
{114}{}{Hast du eine Idee, wie wir aus diesem Keller rauskommen?}
{115}{}{Ich komme wieder. Bleib, wo du bist.}

#########################################################
#
#  Ğàçãîâîğ ÍÅ â 'şğÿãå
#
#########################################################

{120}{}{Du hast mir das Leben gerettet, Mann! Aber die Leute hier werden mir das nie verzeihen. Verdammt.}
{121}{}{Du bist es! Schön, dich zu sehen, Mann. Im Ödland gibt es nicht mehr viele Kerle wie dich.}

{122}{}{Kannst du den Wassertank in Lovelock reparieren?}
{123}{}{Wegen der Wasserpumpe.}
{124}{}{Wie kannst du mich für meine Hilfe bezahlen?}
{125}{}{Was ist eigentlich wirklich passiert?}
{126}{}{Warum verlässt du diesen Ort nicht?}
{127}{}{Erzähl mir von dir und deiner Schwester.}
{128}{}{Erzähl mir von diesem Ort.}
{129}{}{Pass auf dich auf.}

#########################################################
#
#  Î'âå'û ïğè ğàçãîâîğå â 'şğÿãå
#
#########################################################

{130}{}{[Er fasst sich an den Kopf] Ich wollte nicht, dass das passiert! Jetzt ist die Gemeinschaft endgültig dem Untergang geweiht! [blickt plötzlich auf] Wo ist Susie? Geht es ihr gut?!}
{131}{}{Äh, ja, klar. Dann sehe ich dich draußen.}

{137}{}{Auf keinen Fall, ich kann meine Schwester nicht zurücklassen. Und wohin sollte ich gehen? Black Rock würde mich niemals aufnehmen, und Reno ... Nein, ich gehe nie wieder nach Reno zurück.}

{139}{}{Ich habe die Wasserpumpe repariert. Sie läuft jetzt einwandfrei.}
{140}{}{Ich habe diese Sicherung. Hilft die weiter?}
{141}{}{Heilige Scheiße, das ist perfekt! Wo hast du die her? Zeig sie Gerlach, vielleicht lässt er mich dann gehen!}
{142}{}{Die hier? Sieht aus wie das Teil, das ich in die Luft gejagt habe. Bitte bau es in die Pumpe ein ... Äh, vorsichtig. Ich würde es selbst machen, aber Gerlach lässt mich nicht raus.}

{143}{}{Ich kann dich befreien, wenn du dafür zahlst.}
{144}{}{Ich habe nichts ... Aber ich weiß, wo ein Vorrat mit guten Sachen versteckt ist. Doch ich verrate es dir erst, wenn ich hier raus bin!}
{145}{}{Mal sehen.}
{146}{}{Ach, das hätte ich fast vergessen. Wenn du Hilfe brauchst, sprich mich einfach an. Ich kann eine Lederjacke für dich verbessern – nicht nur widerstandsfähiger machen, sondern auch so optimieren, dass du mehr Zeug tragen kannst.}
{147}{}{Ich überleg's mir. Tschüss.}
{148}{}{Du hast den Gefangenen befreit.}

#########################################################
#
#  Î'âå'û ïğè ğàçãîâîğå ÍÅ â 'şğÿãå
#
#########################################################

{149}{}{Die Leute kommen aus dem ganzen Ödland hierher. Gerlach glaubt, dass wir überleben können, wenn wir zusammenhalten und Verantwortung für uns selbst übernehmen. So einen Ort habe ich noch nie gesehen, aber ich habe wirklich daran geglaubt, auch wenn es mich beinahe das Leben gekostet hätte. Jetzt weiß ich nicht mehr, was ich denken soll.}
{150}{}{Die Leute kommen aus dem ganzen Ödland hierher. Gerlach glaubt, dass wir überleben können, wenn wir zusammenhalten und Verantwortung für uns selbst übernehmen. So einen Ort habe ich noch nie gesehen, aber ich glaube wirklich daran, auch wenn es mich beinahe das Leben gekostet hätte.}
{151}{}{Ich bin nur ein Typ aus New Reno. Ich mache dies und das, aber meine Schwester ist die Begabte. Jeder liebt ihr Essen.}
{152}{}{Ich habe keinen Ort, an den ich gehen kann. Meine Schwester und ich gehen nicht zurück nach Reno, und im Ödland gibt es nichts außer Geckos und Radskorpionen. Das hier ist alles, was wir haben.}

{153}{}{Man hat mich auf die Wasserpumpe aufpassen lassen. Sie ist die einzige Wasserquelle hier draußen.}
{154}{}{Erzähl weiter.}
{155}{}{Aber sie ist alt, und man muss sie im Auge behalten. Ich bin bei der Arbeit eingeschlafen und die Sicherung ist durchgebrannt ... Ich glaube, so nennt man das. Wie auch immer, ohne sie funktioniert die Pumpe nicht.}
{156}{}{Kurz gesagt: Wir haben kein Wasser mehr. Also wollten alle mich dafür drankriegen. Da kamst du gerade recht.}
{157}{}{Das ist alles meine Schuld. Ich wäre beinahe draufgegangen, hätte meine Schwester beinahe ganz allein zurückgelassen und die ganze Gemeinschaft beinahe zerstört ... Das ist eine schwere Sache. Da denkt man über alles noch einmal nach. Ich fühle mich wie ein anderer Mensch ... Ich muss anfangen, Verantwortung zu übernehmen.}

{158}{}{Es funktioniert großartig, und das alles nur dank dir. Du hast nicht nur mich gerettet, sondern die ganze Gemeinschaft.}
{159}{}{Die Sicherung ist durchgebrannt, und ich habe nicht die leiseste Ahnung, wie man sie repariert. Du musst eine neue finden oder selbst eine herstellen, wenn du weißt, wie das geht.}

{160}{}{Wird diese Sicherung ihren Zweck erfuellen?}
{161}{}{Das war's.}
{162}{}{Das finden wir nur auf eine Art heraus! Beeil dich, wir brauchen das Wasser!}
{163}{}{Na gut.}

{164}{}{Reno? Wie weit ist es?}
{165}{}{Nicht allzu weit. Ich zeige es dir auf deiner Karte. Aber je näher du kommst, desto gefährlicher wird es. Versuch also, die Straßen zu meiden.}
{166}{}{Danke.}

#########################################################
#
#  Âîäîñáîğíèê â Ëàâëîêå
#
#########################################################

{170}{}{Verdammt ja, das mach ich! Ich schulde dir mein Leben! Ich geh gleich los und erledige das!}
{171}{}{Bitte tu das.}
{172}{}{Nein, warte. Ich krieg das selbst hin. Und wenn nicht, komme ich wieder und bitte dich um Hilfe.}
{173}{}{Na gut. Aber ich bin jederzeit bereit, mit anzupacken!}
{174}{}{Vielleicht hast du recht. Mach dich auf den Weg nach Lovelock.}
{175}{}{Bleib hier. Ich hole dich, wenn ich dich brauche.}

{176}{}{Überlass das mir! Ich werde das nicht vermasseln!}
{177}{}{Großartig.}

{178}{}{Würde ich ja, aber wenn ich gehe, bevor die Pumpe repariert ist, versuchen sie wahrscheinlich wieder, mich umzubringen.}
{179}{}{Stimmt.}

{180}{}{Du hast einen einfachen Weg gefunden, Lovelocks Wasserknappheit zu beheben.}

#########################################################
#
#  ×åì ïîìî÷ü
#
#########################################################

{181}{}{Lass mich nachdenken ... Ich habe nicht viel zu bieten. Aber ich kann deine Lederjacke verbessern oder allerlei Reparaturarbeiten übernehmen.}
{183}{}{Äh, klar.}
{184}{}{Ich komme wieder, wenn ich deine Hilfe brauche.}
{185}{}{Oh, warte! [er gibt dir einige Waffenteile] Es ist nicht viel, aber ich bin sicher, du kannst damit irgendetwas anfangen. Oder du verkaufst sie.}

{190}{}{Ich habe eine Lederjacke, die du wieder herrichten sollst.}
{191}{}{Diese Lederjacke hat schon bessere Tage gesehen. Kannst du sie wieder instand setzen?}
{192}{}{Klar! Gib sie her.}
{194}{}{Welche Jacke? Ich sehe keine.}
{195}{}{Hoppla ...}
{196}{}{Fertig! Probier sie aus!}
{197}{}{In Ordnung.}

#########################################################
#
#  Ïğî ïåğåñåëåíèå
#
#########################################################

{200}{}{Was hältst du davon, von hier wegzuziehen?}
{201}{}{Ohne Gerlach ist dieser Ort nicht sicher. Wenn wir die Chance bekommen, wegzuziehen, sollten wir sie besser nutzen.}
{202}{}{Nach der Sache mit der Pumpe ist es nur eine Frage der Zeit, bis Gerlach irgendeinen Grund findet, mich loszuwerden. Wenn sich die Gelegenheit ergibt, hier wegzukommen, ergreife ich sie.}

{203}{}{Du hast vorhin etwas von einem Versteck gesagt.}
{204}{}{Oh, ja, also ... Ich weiß eigentlich nicht, wo es ist, aber meine Schwester hat mir einmal davon erzählt. Frag sie, sie wird es dir sagen.}
{205}{}{Es ist dasselbe, von dem meine Schwester dir erzählt hat.}
{206}{}{Oh, ist das so?}
{207}{}{[Sein Lächeln verschwindet] Hat meine Schwester dir nicht schon von Gerlachs Versteck erzählt? Was willst du noch?}
{208}{}{Okay!}

#########################################################
#
#  Æåíñêèé âàğèàí' ğåïëèê
#
#########################################################

{1110}{}{Du hast mir das Leben gerettet! Wie lange noch, weiß ich nicht, aber bevor du aufgetaucht bist, hatte ich keine Chance!}
{1120}{}{Du hast mir das Leben gerettet! Danke. Aber die Leute hier werden mir das nie verzeihen. Verdammt.}
{1121}{}{Du bist es! Schön, dich wiederzusehen. In den Einöden gibt es nicht mehr viele Mädchen wie dich.}
