{100}{}{Du siehst einen Dorfbewohner.}
{101}{}{Du siehst eine sehr traurige Frau.}

#Ïîïûòêà çàãîâîğèòü âî âğåìÿ êàçíè
{102}{}{Ich kann mir das nicht ansehen ...}
{103}{}{Ich komme erst raus, wenn es vorbei ist.}
{104}{}{Lauf! So weit weg wie möglich! Die sind alle verrückt!}
{105}{}{Wie können sie das tun?}

#Ïîïûòêà çàãîâîğèòü ïîñëå êàçíè:
{110}{}{Du ... Du bist nicht aus Black Rock, oder?}
{111}{}{Nein. Können wir trotzdem reden?}
{112}{}{[Sie seufzt traurig] Es tut mir leid. Ich bin gerade nicht in der Stimmung zu reden. Vielleicht kann dir jemand anderes helfen ...}
{113}{}{Das ist wahrscheinlich eine gute Idee.}
{114}{}{Du? Aber ... Ich glaube nicht, dass ich dir bei irgendetwas helfen kann.}
{115}{}{Nein, aber ich wette, du brauchst Hilfe.}
{116}{}{Auf Wiedersehen.}
{117}{}{Tut mir leid, ich vertraue Fremden nicht. Wenn du nicht aus Black Rock bist, haben wir nichts zu bereden. Bitte, lass mich einfach in Ruhe.}
{118}{}{In Ordnung.}
{119}{}{Keine Sorge, ich komme gerade von dort. Bist du Milos Frau?}
{120}{}{Milo?! Du kennst Milo?! Wo ist er?!}
{121}{}{Wow, beruhige dich. Genau das wollte ich dich gerade fragen ...}
{122}{}{Das wird schwer zu hören sein, aber ... Dein Mann ist tot. Er ist auf dem Friedhof von Black Rock begraben.}
{123}{}{Er hat seinen Frieden gefunden, an einem besseren Ort. Genauer gesagt in einem schönen, stillen Grab, wo er sich dein Gejammer und Wehklagen nicht mehr anhören muss. Ich wette, der Totengräber in Black Rock hat ihn auch besser gefickt, als du es je getan hast.}
{124}{}{Nein, ich weiß nichts! Beruhige dich!}
{125}{}{Oh, Milo ... Niemand hat ihn mehr gesehen, seit er diese verdammten Felle nach Black Rock gebracht hat! Weder hier noch dort! Er kann doch nicht einfach mitten in der Wüste verschwunden sein, oder?! Ich vermisse ihn so sehr ...}
{126}{}{Was hat er gemacht, bevor er wegging?}
{127}{}{Wie sah er aus, als er wegging?}
{128}{}{Nichts Ungewöhnliches ... Aber warte mal. Am Tag vor seiner Abreise kam ein junger Mann zu ihm, den ich noch nie gesehen hatte. Er trug eine Lederjacke und sah ungepflegt aus, wie so ein Schläger aus New Reno. Ich weiß nicht, worüber sie gesprochen haben, aber Milo warf ihn ziemlich schnell raus.}
{129}{}{Braune Haare, sehr gebräunt, für einen Mann durchschnittlich groß ... Oh, aber er hatte seine guten Lederstiefel an! Milo sagte immer, wenn man seinen Lebensunterhalt mit Laufen verdient, braucht man gute Stiefel. Er hat sie selbst aus Leder von brahmin gemacht. Auf der Sohle ist ein Stern und am rechten Stiefel eine Messerscheide. Ich erinnere mich noch, wie ich ihm dabei zugesehen habe ... Er hat so schöne Hände ...}
{130}{}{Milo hatte also einen Streit mit einem jungen Halbstarken, bevor er nach Black Rock aufbrach, und trug dabei seine Lederstiefel mit dem Stern auf der Sohle. Daran sollte ich mich erinnern.}

{131}{}{D-danke ... [sie beginnt zu schluchzen] ... Jetzt weiß ich es ...}
{132}{}{Ich lasse dich allein.}
{133}{}{[Sie zuckt zurück, als wäre sie geschlagen worden, und beginnt dann zu weinen] Du ... du *Monster*! VERSCHWINDE!}
{134}{}{Wie auch immer.}
{135}{}{Bitte, lass mich in Ruhe. Wir haben sowieso nichts mehr zu besprechen.}

{136}{}{Oh, du bist es schon wieder.}
{137}{}{Kann ich dir ein paar Fragen über Milo stellen?}
{138}{}{Stimmt etwas nicht?}
{139}{}{Ich denke, wir sollten hier Schluss machen.}
{140}{}{Das erklärt einiges.}

{141}{}{Ach, heul doch. Wenigstens muss sich der glückliche Milo nicht mehr damit herumschlagen.}
