{100}{}{Du siehst einen Dorfbewohner.}
{101}{}{Du siehst einen niedergeschlagenen Bürger Gerlachs in schmutziger Kleidung.}

#Ïîïû'êà çàãîâîğè'ü âî âğåìÿ êàçíè
{102}{}{Du gehörst nicht hierher.}
{103}{}{Das geht dich nichts an.}
{104}{}{Geh weiter.}
{105}{}{Das ist nicht deine Angelegenheit.}
{106}{}{Geh mir aus dem Weg.}
{107}{}{Töte ihn!}
{108}{}{Was machst du hier?}
{109}{}{}

#Ïîïû'êà çàãîâîğè'ü ïîñëå êàçíè:
{110}{}{Ich habe dir nichts zu sagen, Fremder. Sprich mit Gerlach, er hat hier das Sagen.}
{111}{}{Was kannst du mir über diesen Ort erzählen?}
{112}{}{Wo ist Gerlach, und wer ist er?}
{113}{}{Was hältst du von den Hinrichtungen?}
{114}{}{Gut, ich rede mit ihm.}

{115}{}{Hier passen wir aufeinander auf. Wenn du nicht zu uns gehörst, solltest du besser weiterziehen.}
{116}{}{Er hat diesen Ort gegründet. Er wohnt in dem Haus im Südwesten.}
{117}{}{Ich habe keine Lust, darüber zu reden. Wenn du es unbedingt wissen musst: Nein, ich sehe sie nicht gern, aber wir haben keine Wahl. Das Ödland ist ein grausamer Ort.}
{118}{}{Er ist tot. Ich weiß nicht, ob wir ohne ihn durchhalten.}

{119}{}{Oh, du bist es! Schön, dich hier wiederzusehen. Kann ich dir irgendwie helfen?}
{120}{}{Ich bin nur auf der Durchreise.}

#Äæåğëàê ìåğ'â
{121}{}{Gerlach ist weg. Wahrscheinlich folgen wir ihm bald.}
{122}{}{Das war so dumm!! Wie sollen wir ohne unseren Anführer überleben? Hau verdammt noch mal ab!}
{123}{}{Na schön, ich gehe ja schon.}

#Ïğåäëîæåíèå î' Ãîğîäà Óáåæèùà
{124}{}{Möchtet ihr an einen sichereren Ort ziehen?}
{125}{}{Sicherer als hier? Und ob. Warum?}
{126}{}{Dann herzlichen Glückwunsch, ihr seid die Ersten, die in unseren Vault ziehen!}
{127}{}{Ach, kein besonderer Grund. Ich hab nur laut nachgedacht.}
{128}{}{Ein Vault? So wie Vault-Tec? Wo?}
{129}{}{Nur ein paar Tagesreisen nach Norden.}
{130}{}{[Du bemerkst, wie sich andere Dorfbewohner um dich versammeln] Und wir können einfach dort leben? Wo ist der Haken?}
{131}{}{Der Haken ist: Wenn ihr einwilligt, könnt ihr nie wieder zurückkommen.}

{132}{}{[Die Dorfbewohner sehen einander an] Warum sollten wir dir glauben?}
{133}{}{Ich habe eure Wasserpumpe repariert. Der Vault verfügt über viel fortschrittlichere Technik.}
{134}{}{Ohne Gerlach ist das eure einzige Chance.}
{135}{}{Wenn ich Steve geholfen habe, warum sollte ich euch nicht helfen?}
{136}{}{Äh ... Na ja, ich kann es nicht wirklich beweisen, aber es ist wirklich besser als dieser Ort! Ehrenwort!}

{137}{}{Beweis es. Wir haben keinen Grund, dir zu vertrauen.}
{138}{}{Sieh dir mein Pip-Boy an. So etwas wurde nur Vault-Bewohnern gegeben.}
{139}{}{Dann habe ich keinen Grund, euch zu helfen. Euer Pech.}

{140}{}{Er hat sich doch ein wenig Respekt verdient, oder? [Die Menge ruft zustimmend] Na gut, wir machen es. Wir haben sowieso nichts zu verlieren. Dieser Ort kann nicht ewig durchhalten.}
{141}{}{Großartig!}
{142}{}{Woher sollen wir wissen, dass du es nicht einer Leiche abgenommen hast? Oder noch besser: Warum sollten wir es nicht dir abnehmen?}
{143}{}{Ach komm, warum sollte ich euch anlügen? Na gut, vielleicht ändert ihr später eure Meinung.}
{144}{}{Davon habe ich gehört, aber noch nie eins gesehen. Wenn jeder im Vault so eins bekommt, bin ich dabei! [Der Rest der Menge murmelt zustimmend]}
{145}{}{Natürlich!}

{146}{}{Wir haben jede Menge Essen und Wasser. Ihr werdet nie wieder hungern oder Durst haben.}
{147}{}{Ich habe genug gehört! Du hast einen neuen Nachbarn, Kumpel!}
{148}{}{Großartig!}
{149}{}{Ach, Essen und Wasser, den Spruch habe ich ja noch nie gehört. Ja, klar! Das kauf ich dir nicht ab.}
{150}{}{Du glaubst mir nicht? Na, dann eben nicht. Mach's gut.}

{151}{}{Er hat recht! [Alle nicken] Ja, wir könnten es versuchen. Du hast gezeigt, dass man dir vertrauen kann.}
{152}{}{Großartig!}
{153}{}{Du hast vielleicht die Pumpe repariert, aber das beweist nicht, dass man dir vertrauen kann. Was, wenn das alles ein großer Trick ist?}
{154}{}{Na ja, denk darüber nach. Vielleicht änderst du später deine Meinung.}

{155}{}{Wer weiß? Steve ist noch nicht lange hier, wir kennen ihn nicht besonders gut. Vielleicht hast du ihn aus irgendeinem Grund gerettet, den wir nicht kennen. Warum sollten wir dir vertrauen?}
{156}{}{Du vertraust mir nicht? Autsch. Vielleicht kann ich etwas tun, um das zu ändern.}

{157}{}{Ja, und du hast ihn umgebracht! Woher sollen wir wissen, dass du uns nicht dasselbe antust?}
{158}{}{Stimmt. Ohne Gerlach wird dieser Ort nicht überleben. [Die Dorfbewohner flüstern einander zustimmend etwas zu] Ich glaube dir, Fremder. Was bleibt uns sonst übrig?}
{159}{}{Wir sind alle erwachsen und kommen auch ohne Gerlach zurecht. Aber du, Fremder – du hast uns bisher nicht gerade viele Gründe gegeben, dir zu vertrauen.}

{160}{}{Wann brechen wir auf?}
{161}{}{Ich gehe zurück zum Vault und sage ihnen, dass ihr bereit seid. Wartet, bis jemand euch abholt.}
{162}{}{Du hast die Gemeinschaft davon überzeugt, in den Vault zu ziehen. Jetzt musst du nur noch Sergeant Stark Bericht erstatten.}
{163}{}{Wir warten. Aber denk nicht einmal daran, unser Vertrauen zu missbrauchen. Wir können immer noch Waffen in die Hand nehmen.}
{164}{}{Natürlich, warte einfach!}
{165}{}{Wir warten schon auf deine Leute. Wo zum Teufel sind sie? Wir sitzen nicht ewig hier herum.}

#Female character
{1120}{}{Ich bin nur auf der Durchreise.}
{1128}{}{Ein Vault? So wie Vault-Tec? Wo?}
{1133}{}{Ich habe eure Wasserpumpe repariert. Der Vault verfügt über viel fortschrittlichere Technik.}
{1135}{}{Wenn ich Steve geholfen habe, warum sollte ich euch nicht helfen?}
{1140}{}{Sie hat sich doch ein bisschen Respekt verdient, oder? [Die Menge jubelt zustimmend] Na gut, wir machen's. Zu verlieren haben wir sowieso nichts. Dieser Ort kann sich nicht ewig halten.}
{1147}{}{Ich habe genug gehört! Du hast jetzt einen neuen Nachbarn, junge Dame!}
{1150}{}{Du glaubst mir nicht? Na, dann eben nicht. Mach's gut.}
{1151}{}{Sie hat recht! [Alle nicken] Ja, wir könnten es versuchen. Du hast gezeigt, dass man dir vertrauen kann.}
{1153}{}{Du hast vielleicht die Pumpe repariert, aber das beweist nicht, dass man dir vertrauen kann. Was, wenn das alles ein großer Trick ist?}
{1158}{}{Stimmt. Ohne Gerlach wird dieser Ort nicht überleben. [Die Dorfbewohner flüstern einander zustimmend etwas zu] Ich glaube dir, Fremder. Was bleibt uns sonst übrig?}
{1159}{}{Wir sind alle erwachsen und kommen auch ohne Gerlach zurecht. Aber du, Fremder – du hast uns bisher nicht gerade viele Gründe gegeben, dir zu vertrauen.}
