{100}{}{Du siehst Susie.}
{101}{}{Du siehst ein sehr attraktives Mädchen. Etwas scheint sie zu bedrücken.}
{102}{}{Du siehst ein sehr attraktives Mädchen.}

#Åñëè ïîãóáëåí åå áğàòà:
{103}{}{Du herzloser Bastard! Wie konntest du nur?!}
{104}{}{Bitte, hilf! Sie werden ihn umbringen!!!}
{105}{}{Mein Bruder ... Warum ...?}

#################################################
#
#  Ñòàğò äèàëîãà è âîïğîñû
#
#################################################

{109}{}{Danke, dass du meinem Bruder geholfen hast! Aber was wird jetzt aus unserer Gemeinschaft?}
{110}{}{Danke, aber mein Bruder ist immer noch in Gefahr. Wenn wir die Pumpe nicht reparieren können, werden sie ihn ganz sicher umbringen!}
{111}{}{Danke, dass du meinem Bruder geholfen hast!}

{112}{}{Was hast du jetzt vor?}
{113}{}{Erzähl mir von dir und deinem Bruder.}
{114}{}{Warum sind alle so wütend auf deinen Bruder?}
{115}{}{Wie können wir deinen Bruder befreien?}
{116}{}{Für meine Hilfe brauche ich mehr als nur ein „Danke“.}
{117}{}{Du glaubst doch nicht, dass ich das umsonst getan habe, oder?}
{118}{}{Kannst du mir etwas über diese Siedlung erzählen?}

{119}{}{Vielleicht später. Ich komme wieder.}
{120}{}{Schon gut.}

{121}{}{Ist Reno weit von hier entfernt?}
{122}{}{Wie würdest du dazu stehen, von hier wegzuziehen?}

#################################################
#
#  Îòâåòû íà âîïğîñû
#
#################################################

{150}{}{Was *können* wir schon tun? Wir können nicht weg. Hier draußen gibt es nichts als Wüste, Staub und Tod. Wir müssen hierbleiben, bis wir einen besseren Ort finden.}
{151}{}{Wir haben in Reno gelebt. Es war nicht immer so schlimm, aber als wir weggingen, starben die Leute jeden Tag. Wir hörten von einem Karawanenhändler von Gerlach und dachten: Warum nicht?}
{152}{}{Zu Fuß etwa eine Woche. [sie zeigt nach Süden] Aber heutzutage ist es ein übler Ort. Leute wie du sollten sich davon fernhalten.}
{153}{}{Steve passte auf die Wasserpumpe auf, als sie kaputtging, und alle sind durchgedreht! Sie ist unsere einzige Wasserquelle, aber trotzdem hätten sie nicht versuchen dürfen, ihn umzubringen!}
{154}{}{Dieser Muskelprotz aus Reno hält ihn in seinem Keller gefangen. Gerlach wird Steve nichts tun, solange du einen Deal mit ihm hast oder noch Wasser im Tank ist. Unsere einzige Hoffnung ist, dass du die Pumpe reparierst ... Du lässt uns doch nicht so im Stich, oder?}
{155}{}{Mein Bruder und ich sind erst vor Kurzem hier angekommen, also weiß ich nicht viel. Ein Karawanenhändler erzählte uns, dass hier alle zusammenarbeiten, um die Gemeinschaft zu unterstützen, und wir wollten dazugehören. Ich wünschte, er hätte uns gesagt, dass sie dich umbringen, wenn du einen Fehler machst!}
{156}{}{Gerlach ist tot, also ist Steve frei. Aber was bringt das? Wenn kein Wasser mehr im Tank ist, bringen sie uns sowieso um.}

{157}{}{Ich habe darüber nachgedacht, aber ohne meinen Bruder gehe ich nicht. Er ist alles, was ich habe.}
{158}{}{Wir müssen uns einen anderen Ort suchen. Wir haben keine Wahl – ohne Gerlach wird dieser Ort auseinanderfallen.}
{159}{}{Ich gehe, wenn alle anderen gehen.}

{160}{}{Mein Bruder und ich sind erst vor Kurzem hier angekommen, also weiß ich nicht viel. Ein Karawanenhändler erzählte uns, dass hier alle zusammenarbeiten, um die Gemeinschaft zu unterstützen, und wir wollten dazugehören. Ich wünschte, er hätte uns gesagt, dass sie dich umbringen, wenn du einen Fehler machst!}

#################################################
#
#  Öåíà çà âîçíàãğàæäåíèå
#
#################################################

{200}{}{Und einmal dachte ich, jemand wollte einfach nur helfen. Na ja, ich habe nichts Wertvolles, aber ich weiß, wo Gerlach seine guten Sachen versteckt hat. Wenn du meinem Bruder hilfst, zeige ich es dir.}
{201}{}{Und einmal dachte ich, jemand wollte einfach nur helfen. Na ja, ich habe nichts Wertvolles, aber ich weiß, wo Gerlach seine guten Sachen versteckt hat.}
{202}{}{Wenn das Zeug so gut ist, warum hast du es dann noch nicht genommen?}
{203}{}{Essen, Wasser, ein Dach über dem Kopf und Familie sind mir wichtig. Geld nicht. Außerdem würde Gerlach ziemlich schnell herausfinden, wenn jemand aus der Gemeinschaft sein Zeug hätte. Bei dir ist das kein Problem.}

{204}{}{Zeig mir den verdammten Schatz! Ich will alles, was drin ist!}
{205}{}{Susie sagte, das Versteck sei irgendwo hier in der Nähe.}

#Ïëàâàşùèå ôğàçû äëÿ òàéìåğà, êîãäà áğàò ìåğòâ (ëşáûì ñïîñîáîì)
{300}{}{::weint::}
{301}{}{::seufzt::}
{302}{}{Ohhh ...}
{303}{}{::wischt sich die Tränen ab::}
{304}{}{Was soll ich jetzt tun?..}
{305}{}{::murmelt etwas::}
{306}{}{Ich kann nicht hierbleiben ...}
{307}{}{Wer wird mich jetzt beschützen?}
{308}{}{Wo kann ich hin?}
{309}{}{Ich habe jetzt niemanden mehr ...}

#Female character
{1116}{}{Für meine Hilfe brauche ich mehr als nur ein „Danke“.}
{1117}{}{Du glaubst doch nicht, dass ich das umsonst getan habe, oder?}