{100}{}{Du siehst Evan.}
{101}{}{Du siehst Evan, einen abgebrühten Fallensteller.}
{102}{}{}
{103}{}{Geh zurück ins Dorf, ich hole dich ein.}

{110}{}{In dieser Höhle gibt es ein Geckonest, eines von mehreren in der Gegend. Sie wimmelt nur so von den Viechern, also sei vorsichtig. Wenn du schnell und leise bist, solltest du keine allzu großen Probleme haben.}
{111}{}{Ich soll die Eier einsammeln, richtig?}
{112}{}{... Ohne die Geckopopulation auszurotten, ja. Lass mindestens die Hälfte am Leben, sonst haben wir nächste Saison nichts zu essen.}
{113}{}{Du kannst auf mich zählen.}
{114}{}{Ich warte am Ausgang auf der anderen Seite der Höhle auf dich. Sei vorsichtig und lauf nicht vor Angst davon. Sonst bist du in der ganzen Siedlung unten durch. Dann rühre ich keinen Finger für dich.}
{115}{}{Bis dann.}

{120}{}{Das ging schnell. Wie lief die Jagd? Hattest du Glück?}
{121}{}{Ich schnappe nur etwas frische Luft. Ich bin gleich mit den Eiern zurück.}
{122}{}{Ich habe Schreie gehört! Was zum Teufel ist da drin los?}
{123}{}{Es wurde chaotisch, aber ich habe die Eier bekommen.}
{124}{}{Ich erkläre es später. Jetzt muss ich wieder rein.}
{125}{}{Ich habe die Eier. Reicht das?}

{126}{}{Was?! Ach, ich wusste, ich hätte das keinem Anfänger anvertrauen sollen! Wenn du nur ein paar getötet hast, kommen wir wohl noch glimpflich davon. Aber wenn du mehr als die Hälfte des Rudels ausgerottet hast ...}
{127}{}{Ähm, und die Eier?}
{128}{}{Zeig her.}
{129}{}{[Rucksack öffnen]}
{130}{}{Ich kann noch mehr holen. Warte hier.}
{131}{}{Das ist alles? Hör zu, sie schicken keine Karawane, wenn wir nicht mindestens zehn Eier haben. Bei weniger verschwenden wir nur unsere Zeit.}
{132}{}{Na gut ...}

{135}{}{Das reicht, gib sie mir. Wir müssen uns beeilen und ins Dorf zurück, bevor man uns bemerkt.}
{136}{}{[Gib ihm alle Eier]}
{137}{}{Warte, Moment mal. Ich habe für diese Eier meinen Hals riskiert. Warum sollte ich sie nicht einfach nehmen und selbst verkaufen?}
{138}{}{Ich versuche, noch mehr zu holen.}

{139}{}{Hey, pass mit denen auf! Sie sind zerbrechlich!}
{140}{}{Na gut, schon gut ...}

{141}{}{[Evan wickelt die Eier vorsichtig ein und polstert sie zum Schutz mit Fellen und Schilf] So, fertig. Wir können jetzt zurückgehen.}
{142}{}{[Zur Siedlung zurückkehren]}

{143}{}{[Er runzelt die Stirn] Ich bin nicht den ganzen Weg hierhergekommen, um mich im letzten Moment mit dir zu streiten. Ich habe dich unterrichtet, du hast gelernt. Betrachte das als Bezahlung für meine Arbeit.}
{144}{}{Fick dich, alter Mann. Diese Eier gehören mir!}
{145}{}{Einverstanden. Nimm sie.}

{146}{}{Du-!! [Er knirscht mit den Zähnen] Behalt die verdammten Eier. Ich will dein Gesicht nie wiedersehen!}
{147}{}{Das beruht auf Gegenseitigkeit. Mach, dass du wegkommst.}
{148}{}{Hey, reg dich nicht auf, ich gehe ganz friedlich ...}
{149}{}{Die Jagd ist vorbei.}

{150}{}{Du hast Evan mitten in der Jagd zurückgelassen. Das wird deinem Ruf in Gerlach schaden.}
{151}{}{[Er sieht dich nachdenklich an] ...Weißt du, du hast heute verdammt gute Arbeit geleistet. Ich finde, du hast dir eine Belohnung verdient. [Er zählt zehn Eier ab und gibt dir dann den Rest] Denk dran, in Reno zahlen sie viel mehr dafür, als du hier bekommen kannst.}
{152}{}{Wie viele Eier soll ich mitbringen?}
{153}{}{Mindestens zehn. Nicht weniger!}

#Æåíñêèå ðåïëèêè
{1125}{}{Ich habe die Eier. Reicht das?}
{1128}{}{Zeig her.}
{1137}{}{Warte, Moment mal. Ich habe für diese Eier meinen Hals riskiert. Warum sollte ich sie nicht einfach nehmen und selbst verkaufen?}
