{100}{}{Du siehst Evan.}
{101}{}{Du siehst Evan, einen abgebrühten Geckojäger.}
{102}{}{Jetzt nicht!}
{103}{}{Geh zurück ins Dorf. Ich komme nach.}

########################################################
#
#                Ïåğâûå ğåïëèêè äèàëîãà
#
########################################################

{110}{}{Hallo, Fremder! Es ist immer schön, hier ein neues Gesicht zu sehen. Solange es nicht feindselig ist, versteht sich.}
{111}{}{Lust zu plaudern?}

{112}{}{Entschuldige, aber wer bist du?}
{113}{}{Ich möchte dich etwas über diese Siedlung fragen.}
{114}{}{Ich möchte dich etwas über die Jagd fragen.}
{115}{}{Ich habe eine Munitionspresse.}
{116}{}{Kannst du mir etwas Munition herstellen?}
{117}{}{Kannst du mir etwas Munition herstellen?}
{118}{}{Weißt du etwas über Waffenmodifikationen?}
{119}{}{Tschüss.}

{120}{}{Normalerweise stellt sich derjenige, der ein Gespräch beginnt, zuerst vor.}
{121}{}{Ach ja? Jetzt hält mir irgendein Hinterwäldler einen Vortrag über gute Manieren?}
{122}{}{Nö, du sagst mir zuerst deinen Namen.}
{123}{}{Oh, tut mir leid. Ich heiße }
{124}{}{.}
{125}{}{Wenn du dich so aufführen willst, bitte. Ich gehe.}

{126}{}{Ach, bin ich das? Du bist wohl derjenige, der gleich voreilige Schlüsse zieht, was? Du kennst mich nicht und nennst mich trotzdem einen „Hinterwäldler“. Ziemlich kindisch ... Also, sagst du mir jetzt deinen Namen, oder wollen wir uns weiter stur stellen?}
{127}{}{Ach, wirklich? Da wäre ich mir nicht so sicher. [Er verschränkt die Arme und sieht dich schweigend an]}
{128}{}{Tut mir leid, ich wollte dich nicht beleidigen. Ich heiße }
{129}{}{. Können wir das vergessen?}

{130}{}{Schön, dich kennenzulernen! Ich heiße Evan, ich jage hier in der Gegend Geckos. [Er streckt dir die Hand entgegen] Schluss mit den Förmlichkeiten, reden wir einfach wie Freunde.}
{131}{}{Schon besser. Na gut, alles vergeben. Ich heiße Evan, ich jage hier in der Gegend Geckos. [Er streckt dir die Hand entgegen] Schluss mit den Förmlichkeiten, reden wir einfach wie Freunde.}
{132}{}{[Seine Hand schütteln]}
{133}{}{Ich schüttle keine Hände!}

{134}{}{Vertrauensprobleme, was? Na schön, wie du willst. Aber hier läuft das anders. Früher oder später musst du das akzeptieren oder verschwinden.}
{135}{}{Mal sehen.}

########################################################
#
#                Âîïğîñû î ïîñåëåíèè
#
########################################################

{140}{}{Das hier ist nicht bloß eine Siedlung, sondern eine Familie. Gerlach kommt aus Reno, aber hier leben Leute aus ganz Nevada.}

{141}{}{Wer ist Gerlach?}
{142}{}{Was hältst du davon, umzuziehen?}
{143}{}{Was hältst du von den Hinrichtungen?}
{144}{}{Warum wollten sie den Kerl hinrichten?}
{145}{}{Was ist mit der Pumpe los?}
{146}{}{Also gut, reden wir über etwas anderes.}
{147}{}{Das reicht, wir sehen uns.}
{150}{}{Erzähl mir noch mal von dieser Gemeinschaft.}

{151}{}{Gerlach hat hier das Sagen, so eine Art spiritueller Anführer. Er hat diesen Ort auch gegründet. Er wohnt in dem Haus auf der anderen Straßenseite.}
{152}{}{Ich bin zufrieden mit meinem Leben. Ich schlafe, wo ich will, und tue, was ich will. Aber langsam spüre ich mein Alter. Ich überlege, mir einen sichereren Ort zum Niederlassen zu suchen.}
{153}{}{Gerlach versteht etwas davon, Leute zu organisieren – jahrelang war er Karawanenwächter. Er muss viele verschiedene Gemeinschaften gesehen haben, deshalb vertraue ich ihm. Trotzdem ... Manchmal habe ich einfach das Gefühl, dass er etwas verheimlicht.}
{154}{}{Weil er verantwortungslos war und seine Arbeit nicht gemacht hat. Er sollte auf die Wasserpumpe aufpassen, ist aber eingeschlafen und jetzt funktioniert sie nicht mehr. Er tut mir leid, aber er hat die ganze Gemeinschaft in Gefahr gebracht. Ohne Wasser können wir nicht überleben.}
{155}{}{Ich glaube, irgendwas ist durchgebrannt? Ich kenne mich mit Maschinen nicht aus. Wenn du ein Ersatzteil hast, wären wir dir wirklich dankbar!}
{156}{}{Gerlach war der Anführer und Gründer dieses Ortes.}

{157}{}{Warum bist du nicht mit den anderen gegangen?}
{158}{}{Es stellt sich heraus, dass diese alten Knochen sich noch nicht zur Ruhe setzen wollen. Danke für das Angebot, aber das ist nichts für mich.}
{159}{}{Nun, das liegt ganz bei dir.}

########################################################
#
#       Àïãğåéäû è ïî÷èíêà îğóæèÿ
#
########################################################

{160}{}{Ich habe im Laufe der Zeit schon einige Jagdwaffen hergerichtet. Meistens Schrotflinten.}
{161}{}{Kannst du diese doppelläufige Schrotflinte kürzen?}
{162}{}{}
{163}{}{}
{164}{}{Kommen wir zurück zu den anderen Fragen.}
{165}{}{Ein andermal.}
{166}{}{Diese „Savage“ muss nach jedem Schuss nachgeladen werden. Kannst du etwas damit anfangen?}

{170}{}{Für dich? Umsonst. [he winks at you] Dein Geld ist hier nichts wert.}
{171}{}{Das könnte ich machen. Gib mir, hm ... 120 Mäuse für meine Arbeit, dann erledige ich das.}
{172}{}{Klar, aber nicht umsonst. Wasser ist gerade wertvoll. Ich mach's für drei Flaschen.}
{173}{}{Klar, aber nicht umsonst. Wasser ist gerade wertvoll. Ich mach's für zwei Flaschen.}

{174}{}{Reden wir über eine andere Waffe.}

{176}{}{Hier ist die Waffe. Los geht's!}
{177}{}{Hier sind 120 Mäuse und die Waffe. Los geht's!}
{178}{}{Hier sind drei Wasserflaschen und die Waffe. Los geht's!}
{179}{}{Hier sind zwei Wasserflaschen und die Waffe. Los geht's!}

{181}{}{[After an hour, he returns you the weapon] Hier, mein Freund. Viel Spaß!}
{182}{}{Danke.}

{183}{}{Ja, das kann ich machen.}
{184}{}{Hmm. Ich kann an diesem Gewehr einen Patronengurt anbringen. Ich habe andere Jäger damit gesehen. Ich habe sogar etwas Gecko-Leder dafür.}

{187}{}{Lass mich dich noch etwas anderes fragen.}
{188}{}{Nein, jetzt nicht.}
{189}{}{Oh, nein, das wird nicht funktionieren.}
{190}{}{Fehlt etwas?}

########################################################
#
#                Ïğî îõî'ó
#
########################################################

{199}{}{Nun, ich könnte stundenlang über die Jagd reden ... Aber nicht mit dir.}
{200}{}{Nun, ich könnte stundenlang über die Jagd reden.}
{201}{}{Kann ich mit dir jagen?}
{202}{}{Erzähl mir etwas über Geckos.}
{203}{}{Du hast etwas von Geckofellen gesagt?}
{204}{}{Woher bekommst du deine Jagdausrüstung?}
{205}{}{Wie weit bist du durch das Ödland gereist?}
{206}{}{Jetzt nicht.}
{207}{}{Noch eine Frage.}
{208}{}{Das reicht.}
{209}{}{Reno? Zwei Wochen zu Fuß, immer gerade nach Süden. Den Highways zu folgen geht schneller, ist aber gefährlich. Wenn du es wirklich wissen willst, frag jemanden, der von dort kommt.}
{210}{}{Mutierte Echsen. Soweit ich gesehen habe, gibt es sie in Silber und Gold. Die silbernen sind klein und etwas nervös, aber leicht genug zu erledigen. Die goldenen sind eine größere Herausforderung – sie sind größer, zäher und haben Kiefer, die deine Hand durchbeißen wie ... [er denkt nach] ... wie ein Messer durch brahmin Scheiße! Aber dafür bekommst du mehr Fleisch, und Händler zahlen Höchstpreise für ihre Felle.}
{211}{}{Geckofelle geben gutes Leder, aber um es ihnen abzuziehen, braucht man ein besonderes Händchen. Wenn du nicht weißt, wie es geht, ruinierst du nur das Fell und verschwendest deine Zeit.}
{212}{}{Kannst du es mir beibringen?}
{213}{}{Klar! Ich bring dir alles bei, was ich weiß. Einem Reisenden wie dir wird das bestimmt nützlich sein.}
{214}{}{Lehre mich, oh großer Fallensteller!}
{215}{}{Nicht jetzt. Lass uns erst über etwas anderes reden.}
{216}{}{Vielleicht später, ich bin beschäftigt. Wir sehen uns.}
{217}{}{Evan hat dir beigebracht, wie man Geckos richtig häutet.}
{218}{}{Ich bin hier nicht sonderlich beliebt, aber du noch weniger. Ich kann mich nicht dabei erwischen lassen, wie ich dir helfe.}
{219}{}{Oh Scheiße, hassen die mich wirklich so sehr? Kannst du wenigstens noch ein paar Fragen beantworten?}
{220}{}{Könnte ich, aber ich will meine Zeit nicht mit irgendeinem Grünschnabel verschwenden. Du musst geduldig sein und ein Auge fürs Detail haben. Wir haben noch nie zusammen gejagt, also weiß ich nicht, ob du das Zeug dazu hast.}
{221}{}{Schade.}
{222}{}{Ich tausche mein Fleisch und meine Felle in Black Rock gegen Vorräte, aber sie haben nie genug Munition, und ich werde langsam zu alt, um meinen Speer zu benutzen. Vor Jahren habe ich meine Munition noch selbst mit einer Handpresse hergestellt, aber die Ausrüstung dafür habe ich nicht mehr.}
{223}{}{Könnte ich, aber ich weiß nicht, ob du das Zeug dazu hast. Tut mir leid, aber die Jagd im Canyon hat nicht gereicht, um festzustellen, ob du das Zeug dazu hast oder nicht.}
{224}{}{}
{225}{}{Ich bin kein Entdecker, aber ich habe so ziemlich jeden Berg nördlich von Reno erklommen. Außer uns gibt es New Reno, Black Rock und die Wilden in Lovelock. Wenn du unterwegs bist, pass auf den Highways auf. Da wartet immer jemand darauf, dich zu überfallen. Wenn ich kann, meide ich die Straßen. Wenn nicht, reise ich mit einer Karawane.}
{226}{}{Wo ist New Reno?}
{227}{}{Wo liegt Lovelock?}
{228}{}{Wo ist Black Rock?}
{229}{}{Du bist nicht von hier, was? Macht nichts, ich zeig's dir. [Er zeigt dir den Ort auf deiner Karte]}
{230}{}{Danke, aber ich möchte dich etwas über die Jagd fragen.}
{231}{}{Danke, ich glaube, das war alles, was ich wissen musste.}

########################################################
#
#                Êâåñ' - ïîèñê ïîñûëüíîãî
#
########################################################

{290}{}{Ich suche Milo. Weißt du, wo er ist?}
{291}{}{Milo? Ich habe ihn nicht mehr gesehen, seit er meine Felle zu William nach Black Rock gebracht hat. Bist du sicher, dass er nicht noch dort ist?}
{292}{}{Warum sollte William deine Felle brauchen?}
{293}{}{Ich habe die besten Felle weit und breit. William glaubt, er kann sie an Karawanenhändler verkaufen, die zwischen Reno und Salt Lake City unterwegs sind. Wenn du mich fragst, ist das Wunschdenken, aber trotzdem – viel Glück dabei.}
{294}{}{Hat Milo etwas gesagt, bevor er aufgebrochen ist?}
{295}{}{Hmm ... Ich kann mich an nichts Besonderes erinnern. Hast du schon mit seiner Frau gesprochen?}
{296}{}{Würde irgendjemand wollen, dass Milo verschwindet?}
{297}{}{Eigentlich nicht, er ist nur ein Kurier. Vielleicht hat er sich einfach betrunken. Oder, schlimmstenfalls, wurde er von Geckos gefressen.}

########################################################
#
#                Ó÷àñ'èå â îõî'å
#
########################################################

#Îõî'à  - ïåğâûé ğàçãîâîğ
{300}{}{Du willst mit mir kommen? Hmm ... Ich *könnte* Hilfe gebrauchen, aber ich glaube, du würdest mir nur im Weg stehen. Nicht böse gemeint, aber ich brauche jemanden, der sich mit Jagen und Überleben auskennt.}
{301}{}{Du willst mit mir kommen? Nicht böse gemeint, aber du bist ein Fremder. Woher soll ich wissen, dass das keine Falle ist? Da draußen wären wir ganz allein, und ich bin nicht so alt geworden, indem ich unvorsichtig war.}
{302}{}{Du willst mit mir kommen? Hmm ... Ich *könnte* Hilfe gebrauchen. Ich bin zu alt, um mit einem Speer herumzurennen und alles selbst zu erledigen. Ein zusätzliches Paar Hände ist genau das, was ich jetzt brauche.}
{303}{}{Ich bin bereit. Was muss ich wissen?}
{304}{}{Ich behalte das im Hinterkopf. Zuerst habe ich noch ein paar andere Fragen.}

{305}{}{New Reno braucht ein paar Geckoeier. Ich bekomme einen guten Preis dafür, weil ich die Einzigen bin, die sie aus einem Nest holen kann, ohne dass es zum Kampf kommt.}
{306}{}{Ohne Kampf? So schwer kann es doch nicht sein, ein paar Geckos zu töten.}
{307}{}{Ha! Anfängerfehler. Wir brauchen das Gecko-Fleisch, um hier zu überleben. Wenn wir sie jetzt alle töten, verhungern wir später. Wir müssen genug Geckos am Leben lassen, damit sich das Nest erholen und uns nächste Saison mehr Fleisch und Eier liefern kann.}
{308}{}{Verstehe. Wie holen wir die Eier aus dem Nest, ohne etwas zu töten?}

{309}{}{Zuerst bringe ich dir bei, Fallen zu stellen und dabei unentdeckt zu bleiben. Pass besser gut auf, denn ich brauche keinen Assistenten, der Anweisungen nicht befolgen kann. Klar?}
{310}{}{Klar. Ich verspreche, gut aufzupassen.}
{311}{}{Nein danke. Das ist nicht mein Stil.}
{312}{}{Gut. Wenn wir dort sind, erkläre ich dir alles genau. Aber du musst deine Sachen hier in dieser Kiste lassen. Auch deine Waffen. Wenn wir fertig sind, bekommst du alles zurück.}
{313}{}{Wir gehen unbewaffnet auf die Jagd?!}
{314}{}{Verdammt richtig. Du lernst nichts, wenn du sie einfach alle erschießt. Eines Tages klemmt die Waffe oder dir geht die Munition aus, und dann musst du mit dem Nötigsten zurechtkommen. Ein Jäger muss wissen, wie er sich auf das Schlimmste vorbereitet, nur das Nötigste mitnimmt und immer genug übrig lässt, damit das Nest überlebt. Verstehst du, worauf ich hinauswill?}
{315}{}{Ich verstehe, Meister! Ich bin bereit für die Jagd.}
{316}{}{Ich komme wieder, wenn ich bereit bin.}

{317}{}{Ich bin bereit, auf die Jagd zu gehen.}

{318}{}{Wo kommen eigentlich all diese Geckos her?}
{319}{}{Sie sind überall in Kalifornien und Nevada, aber ich habe gehört, dass sie oft in der Nähe von Strahlung auftauchen. Die Geckos hier haben wir wahrscheinlich dem Atomkraftwerk im Norden zu verdanken. Zumindest hat man mir gesagt, dass es ein Atomkraftwerk ist – ich war noch nie verrückt genug, hinzufahren und nachzusehen. Selbst ich will mich nicht mit *so vielen* Geckos herumschlagen. Und selbst wenn ich wollte, würde ich lieber nicht meine Eingeweide auskotzen und an Strahlenvergiftung sterben.}

#Îõî'à - â'îğîé ğàçãîâîğ
{320}{}{Das war noch nicht die richtige Jagd, oder?}
{321}{}{Nein. Bei der letzten Jagd hast du gezeigt, dass du ein paar Echsen ausweichen kannst. Jetzt musst du einer ganzen Menge von ihnen ausweichen.}
{322}{}{Klingt ernst. Was ist der Plan?}
{323}{}{Das klingt mir nicht geheuer. Vielleicht später.}

{324}{}{Ah, jetzt kommt der Teil, für den ich langsam zu alt werde. Mehr erzähle ich dir, wenn wir dort sind. Und denk dran: Wir können es uns auf keinen Fall leisten, das Nest auszurotten.}
{325}{}{Lass mich raten – ich lasse meine Waffen wieder zurück?}
{326}{}{Diesmal gebe ich dir meinen Speer. Eine Schusswaffe wäre zu laut, und außerdem will ich nicht, dass du in Versuchung gerätst, sie alle auszurotten.}
{327}{}{Ich bin bereit. Los geht's!}
{328}{}{Ich muss mich erst um ein paar Dinge kümmern. Bis später.}

{329}{}{Wir sind da. Eine wunderschöne Schlucht, findest du nicht? [he looks around and breathes deeply] Na gut, konzentrieren wir uns. Ich habe in den Felsen etwas Köder ausgelegt. Nimm diese Fallen und stell sie in den Durchgängen auf, durch die die Geckos auf dem Weg zum Köder müssen. Wenn du bereit bist, blas in diese Pfeife, dann kommen sie angerannt. Alles verstanden?}
{330}{}{Verstanden.}
{331}{}{Gut. Noch etwas – ich bringe dir das aus gutem Grund so bei. Befolge meine Anweisungen, sonst gehen wir zum letzten Mal zusammen auf die Jagd.}
{332}{}{Na gut.}

{333}{}{Wie läuft's? Mein Köder liegt doch noch da, oder?}
{334}{}{Ich glaube, ich habe sie alle gefangen.}
{335}{}{Sag mir noch mal, was ich tun muss.}
{336}{}{Ich überlege noch. Ich gehe die Fallen aufstellen ...}

{337}{}{Hast du das etwa schon vergessen? Stell die Fallen in einem Durchgang auf, durch den die Geckos müssen, und lock sie dann mit der Pfeife her. So einfach ist das!}
{338}{}{Mal sehen ...}
{339}{}{[Follow the master]}
{340}{}{Hey, du hast Talent! Du hast sie alle erwischt! Gut, geh zurück ins Dorf, während ich mich um die Felle kümmere. Beim nächsten Mal wird's ernst. Ach ja, behalt die Pfeife. Ich habe noch eine.}
{341}{}{Na gut, wir sehen uns im Dorf.}
{342}{}{Was zum Teufel soll das? Du solltest die Fallen benutzen! Hast du überhaupt irgendwas von dem gehört, was ich gesagt habe? [he sighs] Hör zu, das wird nichts. Du kannst die Pfeife behalten, aber das machen wir nicht noch mal. Verschwinde.}
{343}{}{Ich hab dir schon gesagt, dass ich nicht noch mal mit dir auf die Jagd gehe.}
{344}{}{Wenn du nicht willst, dann eben nicht. Ich bin weg.}
{345}{}{Ehrlich gesagt kenne ich mich mit Fallen nicht aus. Kannst du mir beibringen, wie man sie benutzt?}
{346}{}{Jetzt gleich? Na gut, aber ich hoffe, die Gruppe zieht nicht weiter, während ich dir die Grundlagen erkläre. Pass auf ...}
{347}{}{[Weiter]}
{348}{}{Jetzt? Nein, das ist nicht der richtige Zeitpunkt. Finde es einfach selbst heraus.}
{349}{}{Meister Evan hat deinen Fallenwert um 5% erhöht.}
{351}{}{Du haust mitten während der Jagd ab und tauchst jetzt wieder auf, als wäre nichts gewesen? Ich weiß nicht, wie man das bei euch zu Hause handhabt, aber hier läuft das nicht so. Erwarte nicht, dass ich dich noch einmal mit auf die Jagd nehme.}
{352}{}{Hey, du hast einen übersehen. Macht nichts, ist ja dein erstes Mal. Bei der nächsten Jagd wird es ernster. Geh zurück ins Dorf, während ich diese Felle abziehe. Und behalte die Pfeife, ich habe noch eine.}
{353}{}{Du hast das Jagdgebiet mitten während der Jagd verlassen. Irgendwie glaubst du wohl, das hätte Evan so gewollt.}

{354}{}{Na, sieh mal einer an, unser verlorener Jäger ist wieder da. Hast du kalte Füße bekommen oder was? Wir mögen hier keine Leute, die ihr Wort nicht halten. Erwarte keinen warmen Empfang.}
{355}{}{Dagegen kann ich nichts sagen ...}
{356}{}{Du hast ganz schön Nerven, nach dem, was du getan hast, hier wieder aufzutauchen. Ich werde der bessere Mensch sein und mich um dich kümmern, aber mit weiteren Gratisgeschenken ist Schluss. Verstanden?}
{357}{}{Na schön, wie auch immer ...}

{358}{}{Also ... Wie stelle ich eine Falle auf?}
{359}{}{Benutz sie an dir selbst. Ha! Ein alter Jägerwitz. Sie wird vor dir platziert, also denk daran, dich dabei in die richtige Richtung zu drehen. Und wenn du die Gelegenheit hast, versuch, Fallen einzusammeln und wiederzuverwenden.}

{360}{}{Ich kann es kaum erwarten, wieder auf die Jagd zu gehen. Was meinst du?}
{361}{}{Ich habe fürs Erste alle Felle und alles Fleisch, was ich brauche. Aber wenn du so ungeduldig bist, habe ich von etwas gehört ...}
{362}{}{Worum geht's?}
{363}{}{Fallensteller aus dem Nordosten haben mir erzählt, dass sie dort oben den Urvater aller Rad-Skorpione gesehen haben. Er ist zehnmal so groß wie ein gewöhnlicher Rad-Skorpion, und sein Panzer ist so dick, dass Speere ihn nicht durchbohren können. Ich weiß nicht, ob das stimmt, aber du kannst dein Glück versuchen. Wenn du ihn tötest, gibt das vielleicht eine gute Geschichte ab.}
{364}{}{Genau das wollte ich hören! Ich werde dieses Monster finden und töten. Es wird mir nicht entkommen!}
{365}{}{Ein legendärer Skorpion, hm? Ich behalte das im Hinterkopf, aber im Moment habe ich Wichtigeres zu tun.}
{366}{}{Hey, genau die richtige Einstellung! Du erinnerst mich an mich selbst, als ich jünger war. Pass nur gut auf dich auf.}
{367}{}{Danke. Hast du irgendwelche Tipps?}
{368}{}{Du brauchst etwas mit ordentlich Wumms ... Wie ein Maschinengewehr, heh. Mit Fallen wirst du da nicht weit kommen, das steht fest. Wenn du kannst, ziel lieber auf eine empfindliche Stelle, statt auf seinen Panzer einzuhämmern. Egal, wie groß es ist, ein gebrochenes Bein verdirbt ihm trotzdem den Tag. Mit stumpfen Angriffen kommst du vielleicht nur schwer durch seinen Panzer, aber Energie geht direkt hindurch. Ich glaube, einer der Bewohner von Black Rock hat eine Plasmapistole. Frag William danach.}
{369}{}{Sonst noch was?}
{370}{}{Nimm ein Gegengift mit. Normalerweise wird das Gift eines Radskorpions mit zunehmendem Alter schwächer, aber ein Stich von etwas in dieser Größe wird dich trotzdem umbringen. Hier, nimm etwas aus meinem persönlichen Vorrat.}
{371}{}{Das wird nützlich sein. Wo ist dieser Skorpion?}
{372}{}{Man hat gesagt, er sei irgendwo im Nordosten. Ich markiere das Gebiet auf deiner Karte. Viel Glück!}
{373}{}{Danke! Wenn ich etwas Zeit habe, suche ich ihn. Wir sehen uns, Evan!}

########################################################
#
#                Ñêîğïèîí Ëåãåíäà
#
########################################################
{400}{}{Ich habe den legendären Skorpion aufgespürt!}
{401}{}{Nun, reden kann jeder. Hast du irgendwelche Beweise für deine Worte?}
{402}{}{Hier, sieh dir diesen Panzer an. Er gehörte dem Biest. Ich habe ihn eigenhändig von seinem Kadaver gerissen.}
{403}{}{Hier, sieh dir diese Rüstung an. Ich habe sie selbst aus dem Panzer des Skorpions gefertigt.}
{404}{}{Du musst mir nicht glauben, wenn du nicht willst, aber ich weiß ganz genau, dass ich ihn getötet habe.}
{405}{}{Das ist großartig! Glückwunsch, jetzt bist du ein echter Jäger. Du hast meinen tiefsten Respekt.}
{406}{}{Danke, Evan. Das bedeutet mir viel.}
{407}{}{Vielleicht kannst auch du einer werden, wenn du genug übst.}
{408}{}{Du erhältst 100 Erfahrungspunkte.}

#Female character
{1134}{}{Vertrauensprobleme, was? Na schön, wie du willst. Aber hier läuft das anders. Früher oder später musst du das akzeptieren oder verschwinden.}
{1181}{}{[Nach einer Stunde kommt er mit der Waffe zurück] Ihre Waffe, gnädige Frau. Viel Vergnügen!}
{1229}{}{Du bist nicht von hier, was? Macht nichts, ich zeig's dir. [Er zeigt dir den Ort auf deiner Karte]}
{1302}{}{Du? Mit mir? Hm ... ein bisschen Hilfe könnte ich *wirklich* gebrauchen. Ich bin zu alt, um mit einem Speer herumzurennen und alles selbst zu erledigen. Ein zusätzliches Paar Hände kommt mir gerade recht.}
{1310}{}{Klar. Ich verspreche, gut aufzupassen.}
{1315}{}{Ich verstehe, Meister! Ich bin bereit für die Jagd.}
{1342}{}{Was zum Teufel soll das? Du solltest die Fallen benutzen! Hast du überhaupt irgendwas von dem gehört, was ich gesagt habe? [he sighs] Hör zu, das wird nichts. Du kannst die Pfeife behalten, aber das machen wir nicht noch mal. Verschwinde.}
{1345}{}{Ehrlich gesagt kenne ich mich mit Fallen nicht aus. Kannst du mir beibringen, wie man sie benutzt?}
{1354}{}{Na, sieh mal einer an, unser verlorener Jäger ist wieder da. Hast du kalte Füße bekommen oder was? Wir mögen hier keine Leute, die ihr Wort nicht halten. Erwarte keinen warmen Empfang.}
{1356}{}{Du hast ganz schön Nerven, nach dem, was du getan hast, hier wieder aufzutauchen. Ich werde der bessere Mensch sein und mich um dich kümmern, aber mit weiteren Gratisgeschenken ist Schluss. Verstanden?}
{1373}{}{Danke! Wenn ich etwas Zeit habe, suche ich ihn. Wir sehen uns, Evan!}

{4400}{}{Ich habe den legendären Skorpion aufgespürt!}
{4402}{}{Hier, sieh dir diesen Panzer an. Er gehörte dem Biest. Ich habe ihn eigenhändig von seinem Kadaver gerissen.}
{4403}{}{Hier, sieh dir diese Rüstung an. Ich habe sie selbst aus dem Panzer des Skorpions gefertigt.}
{4404}{}{Du musst mir nicht glauben, wenn du nicht willst, aber ich weiß ganz genau, dass ich ihn getötet habe.}
{4405}{}{Das ist großartig! Glückwunsch, jetzt bist du eine echte Jägerin. Du hast meinen tiefsten Respekt.}
