{100}{}{Du siehst eine Wasserpumpe.}
{101}{}{Die Pumpe fuellt gerade den Tank mit Grundwasser.}
{102}{}{Die Pumpe funktioniert nicht. Sie scheint kaputt zu sein.}

{103}{}{Die Pumpe funktioniert.}
{104}{}{Die Pumpe ist jetzt wieder in Ordnung.}
{105}{}{Die Sicherung ist durchgebrannt.}
{106}{}{Die Sicherung muss ersetzt werden.}

{107}{}{Die Pumpe lässt sich nicht weiter reparieren.}
{108}{}{Nutzlos.}
{109}{}{Das hilft nicht. Die Sicherung ist durchgebrannt und muss ersetzt werden.}
{110}{}{Sie braucht eine neue Sicherung.}
{111}{}{Du ersetzt die Sicherung und startest die Pumpe. Über das Dröhnen der Maschine hinweg hörst du Wasser im Tank schwappen.}
{112}{}{Erledigt.}

{113}{}{Beim Durchsuchen des Gerümpels findest du einen dünnen Draht und lötest ihn vorsichtig an die Stelle der Sicherung.}
{114}{}{Dir fehlt das mechanische Wissen, um herauszufinden, was mit der Pumpe nicht stimmt.}
{115}{}{Das kann ich nicht.}

{116}{}{Nicht das.}

{117}{}{Die Pumpe funktioniert normal ... bis sie das nächste Mal kaputtgeht.}
{118}{}{Die Pumpe funktioniert.}
{119}{}{Die Sicherung ist durchgebrannt. Ohne sie funktioniert die Pumpe nicht.}
{120}{}{Die Sicherung muss ersetzt werden.}
{121}{}{Das hilft dir nicht dabei, das Problem zu lösen.}
{122}{}{Ich verstehe nicht.}

{123}{}{Du hast die Pumpe repariert. Schade, dass sie niemand mehr braucht.}
{124}{}{Diese Pumpe ist funktionstüchtig, wurde aber schon eine Weile nicht mehr benutzt.}

{125}{}{Hier gibt es keine Stelle, an der du das Gift hineingießen kannst.}
{126}{}{Nutzlos.}
{127}{}{Das ist eine Wasserpumpe. Sie scheint in ordentlichem Zustand zu sein, funktioniert aber nicht.}
