{100}{}{Du siehst einen Haufen gewöhnlich aussehender Steine. Der Haufen selbst wirkt jedoch ungewöhnlich, als hätte ihn jemand von Hand aufgeschichtet.}
{101}{}{Du brauchst eine Schaufel, um diesen Steinhaufen abzuräumen.}
{102}{}{Ich brauche eine Schaufel.}
{103}{}{Nur ein gewöhnlicher Steinhaufen. Darin ist kaum etwas Brauchbares.}
{104}{}{Hier ist nichts.}
{105}{}{Diese Steine lassen sich nicht stören. Du hast keinen Grund, sie herumzuschieben.}
{106}{}{Was soll das bringen?}
{107}{}{Das ist sinnlos.}
{108}{}{Das ist ja ein Fund!}
{109}{}{Du findest ein äußerst geschickt verstecktes Versteck voller Wertgegenstände.}
{110}{}{Das ist nicht nötig.}
{111}{}{Die Steine zu Schotter zu sprengen, bringt dir nichts.}
{112}{}{Das ergibt keinen Sinn.}