{100}{}{}
{101}{}{Das ist ein persönlicher Brief! Du brauchst eine Erlaubnis, um ihn zu lesen.}
{102}{}{Im Kampf kannst du das nicht lesen.}

{103}{}{Auf dem Tisch liegen ein Bleistift und ein Brief, geschrieben mit zitternder Hand. Er ist an Milo adressiert.}
{104}{}{[Brief lesen.]}
{105}{}{[Geh.]}

{106}{}{"Verzeih mir, Milo. Ich konnte nicht länger warten. Ich musste diesen Ort verlassen. Frag Gerlach, was passiert ist. Es tut mir leid."}
{107}{}{Hier liegt eine Notiz an Reisende.}
{108}{}{Geh weg.}
{109}{}{"Wenn du das hier liest, gib diesen Brief bitte Milo. Er ist 32 Jahre alt, hat braune Haare und ist sehr gebräunt. Er trägt Lederstiefel mit einem Messerholster und einem Stern auf der Sohle. Er ist nach Black Rock gegangen und nie zurückgekommen. Wenn du ihn triffst, bring ihn bitte nach Hause!"}
{110}{}{Na ja, immerhin ist es ein Hinweis ...}
{111}{}{Mit dieser Beschreibung wird es leichter, Milo zu finden.}
{112}{}{Auf dem Tisch liegen ein Bleistift und altes Papier. Nichts Interessantes.}
{113}{}{"Verzeih mir, Milo. Ich konnte nicht länger warten. Ich mache mich allein auf die Suche nach dir. Alle fünf Tage komme ich zurück, um Lebensmittel zu holen. Wenn ich nicht zurückkomme, bin ich tot. Lieber sterbe ich in der Ödnis, als ohne dich zu leben."}
