{100}{}{Du siehst einen Wassertank.}
{101}{}{Du siehst einen Wassertank. Von drinnen hallt ein Rumpeln. Offenbar ist er nicht voll.}
{102}{}{Du siehst einen Wassertank. Er enthält reichlich Wasser, aber dem Geruch nach zu urteilen ist es nicht trinkbar.}
{103}{}{Es sieht so aus, als wäre dieser Keller dafür gebaut worden, nur eine Person aufzunehmen.}
{104}{}{Dieses Dorf ist verlassen. Jetzt streift hier nur noch der Wüstenwind umher.}
{105}{}{Du siehst einen Tank. Im Inneren hörst du Wasser plätschern.}
{106}{}{Das ist zwecklos. Das Wasser ist bereits verseucht.}
{107}{}{Das Wasser ist bereits verseucht.}
{108}{}{Das sollte für die ganze Siedlung reichen. Komm später wieder, um die Ergebnisse zu sehen.}
{109}{}{Das Wasser ist verseucht.}
{110}{}{Wozu brauchst du das?}