{100}{}{Du siehst Derry.}
{101}{}{Du siehst Bruce Derry, den Anführer der Biker.}
{102}{}{Dein Bericht über die Lage in Hawthorne hat ganz schön für Aufsehen gesorgt. Offenbar werden die Biker Bridgeport bald verlassen, sehr zur Freude der Hinterwäldler.}
{103}{}{Verpiss dich.}
{104}{}{Hallo.}

{110}{}{Worum geht's?}
{111}{}{Nichts.}

{112}{}{Ich suche Jay Kukish.}
{113}{}{Hier wirst du ihn nicht finden. Ich glaube, er ist schon in Hawthorne.}
{114}{}{Warum erzählst du mir das so bereitwillig?}
{115}{}{Weil unsere Gang ein besonderes Verhältnis zu Jay hat. Er war schon immer ein Einzelgänger, der sein eigenes Ding macht. Wenn du mit ihm zu tun hast, nur zu, geh ruhig zu ihm und hol ihn ein. Ich mache mir eher Sorgen darüber, was wir jetzt alle tun sollen. Er hat in Hawthorne für Aufruhr gesorgt, wir sind seinem Ruf gefolgt und haben uns hier versammelt, und jetzt sitzen wir untätig herum.}
{116}{}{Also wartet ihr auf eine Nachricht aus Hawthorne?}
{117}{}{Warum musste Jay nach Hawthorne?}
{118}{}{Die Garnison in Hawthorne wurde geknackt – ihre automatischen Verteidigungssysteme funktionieren nicht mehr. Vielleicht solltest du dort mal vorbeischauen.}
{119}{}{Erzähl mir von dir. Wie bist du einer Bikergang beigetreten?}
{120}{}{Erzähl mir von deiner Gang.}
{121}{}{Tschüss.}

{122}{}{Na ja, ja. Wir konnten riechen, dass sich etwas zusammenbraut. Jay verbreitete Gerüchte, wir sollten besser in der Nähe von Hawthorne bleiben, weil dort etwas passieren würde. Also haben wir uns in Bridgeport versammelt – schließlich war es gefährlich, direkt in Hawthorne zu bleiben.}
{123}{}{Jay interessierte sich für einen Regierungsvault. Seiner Aussage nach liegt er irgendwo in Nevada. Er wollte auf einem Militärstützpunkt nach den Koordinaten suchen.}
{124}{}{Ach ja? Jay hat sich noch nicht bei uns gemeldet. Auf diese Nachricht warten wir schon ziemlich lange. Und ehrlich gesagt gehen uns die Hinterwäldler hier langsam auf die Nerven. Sobald alle bereit sind, ziehen wir zum Stützpunkt.}
{125}{}{Ich bin ein Veteran des New Reno-Bürgerkriegs. Damals spannten die örtlichen Geschäftsleute Biker für ihre schmutzigen Geschäfte ein. Wir waren Söldner, eine Eingreiftruppe, bis die Lage so weit eskalierte, dass man uns nicht mehr brauchte. Wie sich herausstellte, wurden wir nur benutzt. Also beschlossen wir, der ganzen Stadt ins Gesicht zu spucken. Ich wollte frei sein.}
{126}{}{Wir sind Leute, die in der modernen Gesellschaft keinen Platz gefunden haben. Sieh dir Bigfoot an – er ist ein Veteran aus Wind of War. Als er merkte, dass das örtliche Militär schlimmer war als die Raider, zog er los, um nach seinen eigenen Prinzipien zu leben. Und dann ist da noch Whiner – seine Siedlung wurde von Raidern zerstört. Er hatte keine Wahl, als Rache zu suchen. Unsere Bande half ihm und gab ihm einen neuen Lebenssinn.}
