{100}{}{Du siehst einen Farmer.}
{101}{}{Du siehst einen angesehenen Einwohner von Bridgeport, das Oberhaupt einer Familie.}
{102}{}{Mein Sohn ist tot ... Das bedeutet Krieg! Von jetzt an ist jeder Biker, den ich sehe, ein toter Mann.}
{103}{}{Gib mir nur einen Grund!}
{104}{}{Hallo.}

{110}{}{Halt! Wer bist du? Wenn du einer von den Bikern bist, dann verpiss dich! Das ist mein Haus, und ich werde es nicht mit dir teilen, du verdammter Schmarotzer!}
{111}{}{Beruhige dich. Ich bin kein Biker, nur ein Reisender.}
{112}{}{[Sieht dich skeptisch an] Ach ja? Na gut, wir können erst mal reden. Pass nur auf, sonst rennst du von hier weg wie ein gebissener brahmin.}
{113}{}{Schon gut, schon gut.}
{114}{}{Also? Was willst du?}
{115}{}{Nichts, ich hatte nur niemanden zum Reden. Tschüss.}

{116}{}{Erzähl mir von den Bikern.}
{117}{}{Warum hasst du die Biker so sehr?}
{118}{}{Mich interessiert, wie du in dieser Wildnis überlebst.}
{119}{}{Früher kamen sie nicht in so großer Zahl hierher. Wir hatten nie Probleme mit ihnen. Und jetzt kommen sie einfach in Rudeln. Ich kann nicht verstehen, was sie hierher verschlägt. Aber das ist auch egal – ich will nur, dass sie verschwinden. Meine Frau und ich können nachts nicht mal schlafen, wenn sie draußen sind.}
{120}{}{Warum sollte ich sie mögen? Ich schufte wie ein Blöder, um meine Familie zu ernähren. Und diese Marodeure haben sich einfach ein paar glänzende Motorräder und Waffen besorgt und spielen jetzt die ganz Harten. Ich würde gern sehen, wie sie ein paar Jahre hierbleiben und sich um die Felder kümmern! Natürlich ist das nicht mein Hauptproblem mit ihnen. Sie können leben, wie sie wollen, ich will nur, dass sie mich in Ruhe lassen. Und Bridgeport auch.}
{121}{}{Wie du siehst, arbeiten wir den ganzen Tag. Nur die ständige Arbeit hilft uns, unsere Probleme zu vergessen. Es ist wirklich interessant, wie wir hier leben, aber frag jemand anderen, mir ist nicht danach. Mein Nachbar redet zum Beispiel für sein Leben gern.}
{122}{}{Ich denke, das reicht für heute. Ich muss los, bis dann.}

{123}{}{Die Biker sind jetzt meine Familie. Also pass auf, was du sagst, Daddy, sonst kriegst du eine Faust ins Gesicht.}
{124}{}{So ist das also! Du verdammter Bengel, wisch dir erst mal die Muttermilch von den Lippen! Gib mir nur einen Grund, und ich puste dir das Hirn raus.}
{125}{}{Jetzt mal ganz ruhig. Wenn ich kämpfen wollte, würde ich ohne Vorwarnung zu schießen anfangen, darauf kannst du wetten.}

{126}{}{Und der Kerl am Eingang mit den geschickten Händen – ist er auch ein Biker?}
{127}{}{Sieht aus, als würde dein Sohn alles tun, um ein Biker zu werden.}
{128}{}{Manche wären vielleicht froh gewesen. Dein Sohn war froh, diesen Ort mit den Bikern zu verlassen.}
{129}{}{[Mit zusammengebissenen Zähnen] Mein Sohn ist ein Idiot! Er ist zu naiv, er versteht nicht, worauf er sich einlässt. Wie ich ihn erzogen habe, damit er am Ende so wird ...}
{130}{}{Es wird schwer sein, ihn umzustimmen.}
{131}{}{Er versteht es einfach noch nicht. Ein eigenes Zuhause – was könnte besser sein? Er hat sich entschieden, seine Familie gegen die Straße einzutauschen. Dummer Idiot ... Wenn er merkt, dass er sein Leben vergeudet, wird es zu spät sein. Man muss ihm vorher Vernunft einprügeln, bevor dieser Abschaum ihn aus dem Haus lockt. Kannst du helfen?}
{132}{}{Ich weiß nicht ... Wie soll ich das anstellen?}
{133}{}{Ich habe keine Ahnung. Vielleicht musst du die Biker in seinen Augen demütigen. Finde etwas gegen sie und zeig ihm, dass es gefährlich ist, mit ihnen zu tun zu haben. Noch besser wäre es, wenn sie alle tot wären. Aber das ist zu riskant. Meine einzige Hoffnung ist, dass die Biker abhauen, ohne ihn in ihre Reihen aufzunehmen. Kannst du dafür sorgen?}
{134}{}{Okay, ich versuche, die Biker loszuwerden und deinen Sohn zu retten.}
{135}{}{Danke. Jetzt können wir jede Hilfe gebrauchen.}
{136}{}{[Gehen]}
{137}{}{Tut mir leid, aber ich mische mich nicht in Familienangelegenheiten ein. Wenn der Kerl ein Biker werden will, ist das seine Entscheidung. Tschüss.}
{138}{}{Dante ist mit den Bikern abgehauen. Es war unmöglich, ihn aufzuhalten.}
{139}{}{Ich weiß. Ich werde nicht darauf warten, dass er zurückkommt. Das war sein größter Fehler. Wenn ich ihn doch nur hätte aufhalten können ... Wenn ich doch nur ...}
{140}{}{[Gehen]}
{141}{}{Jetzt, da die Biker weg sind, wird dein Sohn nirgendwohin gehen.}
{142}{}{Vor allem haben die Biker gezeigt, wie schwach sie sind; sie konnten nicht einmal mit uns fertigwerden. Das wird meinem Sohn eine gute Lehre sein. Besonders, nachdem ich ihn verprügelt habe.}
{143}{}{Gut. Dann lasse ich euch beide mal allein.}
{144}{}{Ich konnte Dante davon überzeugen, zu Hause zu bleiben.}
{145}{}{Unglaublich! Früher konnte man ihn nur mit einem Stockhieb auf den Hinterkopf überzeugen, und du hast es mit Worten geschafft? Wie unerwartet. Ich hoffe, er hat seine Lektion gelernt. Danke für deine Hilfe. Betrachte dich von nun an als Gast in meinem Haus.}
{146}{}{Danke, dass du diese zweirädrigen Gorillas losgeworden bist. Klar, vielleicht kommen sie zurück. Aber das Wichtigste ist, dass sie Dante im Stich gelassen und zurückgelassen haben. Das wird ihm eine gute Lehre sein. Besonders, nachdem ich ihn verprügelt habe.}
{147}{}{Dann lasse ich euch beide mal allein.}

{150}{}{Ich kann dir helfen, die Biker loszuwerden.}
{151}{}{Du? Allein? Gegen mehrere schwer bewaffnete Banditen? Das wird nicht so einfach. [Er kneift ungläubig die Augen zusammen] Außerdem, warum solltest du uns helfen? Wir sind weder verwandt noch Nachbarn und haben nichts, womit wir dich bezahlen könnten. Andererseits könntest du ihre Leichen nach allerlei Wertvollem durchsuchen.}
{152}{}{Es gibt auch andere Möglichkeiten als Mord. Darüber muss ich nachdenken.}
{153}{}{Wie versprochen werden die Biker in Bridgeport keinen Ärger mehr machen.}
{154}{}{Vielen Dank. Nach all dem tut es gut, diese Worte zu hören. Ich hoffe, du bleibst noch ein wenig hier.}
{155}{}{}
{156}{}{Tschüss.}
