{100}{}{Du siehst einen Farmer.}
{101}{}{Du siehst einen angesehenen Einwohner von Bridgeport, das Oberhaupt einer Familie.}
{102}{}{}
{103}{}{Noch ein Schritt, und du bekommst meine Mistgabel zu spüren!}
{104}{}{Ich bin ein friedlicher Bauer. So werde ich nicht mit dir reden. Steck deine Waffe weg!}

{110}{}{Was willst du?}
{111}{}{Nichts, ganz ruhig.}

{112}{}{Mich interessiert dieses Dorf. Erzähl mir die Geschichte dieses Ortes.}
{113}{}{Nun, das wird eine sehr kurze und langweilige Geschichte. Bridgeport war seit dem Krieg unbewohnt, bis sich unsere Familien vor etwa sechs Jahren hier niederließen. Wir kommen alle aus Reno. Wir verließen den Ort, als das Leben dort sehr schlecht wurde und es keine andere Lösung gab, als fortzugehen. Dann stießen wir auf diesen wunderbaren Ort und beschlossen zu bleiben.}
{114}{}{Erzähl weiter.}
{115}{}{Wir haben die Häuser repariert, Feldfrüchte angebaut und sogar eigenes Vieh gezüchtet – du weißt schon, uns einfach niedergelassen. Ehrlich gesagt ist es viel besser als in Reno, obwohl ich manchmal den Luxus der Großstadt vermisse. Zum Beispiel konnten wir die Stromversorgung in Bridgeport bisher nicht vollständig wiederherstellen, und manchmal brauchen wir Medikamente. Außerdem verfallen unsere Häuser.}
{116}{}{Wenn du möchtest, kann ich dir etwas aus Reno mitbringen.}
{117}{}{Wie ernährt ihr euch?}
{118}{}{Hier ist es ziemlich kalt.}
{119}{}{Bist du in dieser Gegend allein?}
{120}{}{Das ist interessant, aber lass uns das Thema wechseln.}
{121}{}{Danke, das reicht.}

{130}{}{}
{131}{}{Zuerst lebten wir von den Lebensmittelvorräten aus der Vorkriegszeit, die dank des kalten Klimas gut erhalten waren. Jetzt sind sie aufgebraucht, die Läden hier sind geplündert. Aber inzwischen haben wir gelernt, Feldfrüchte anzubauen und brahmin zu züchten. Manchmal bringt Jacob etwas von der Jagd mit. Jeder trägt auf seine Weise etwas bei.}
{132}{}{Ja, aber zum Glück haben wir Felle von brahmin. Sie schützen besser vor der Kälte als Vorkriegskleidung und erst recht besser als die Häute dieser riesigen Echsen. Alten Fotos nach zu urteilen, gab es hier Skigebiete, mit ganzen Bergen, die vollständig mit Schnee bedeckt waren. Das Klima hat sich wahrscheinlich stark verändert, denn wir haben in unserem Leben noch nie so viel Schnee gesehen. Doch statt Schnee haben wir jetzt sauberes Wasser, das die Seen fuellt. Darin gibt es sogar Fische! Auf jeden Fall sind die kalten Berge besser als die heißen Wüsten Nevadas.}
{133}{}{Nur selten verirren sich Reisende hierher. Ich habe von einem Stamm Wilder in den Bergen im Süden gehört. Wenn es dich interessiert, sprich unseren Schürfer Jacob darauf an.}
{134}{}{}
{135}{}{Du hast etwas über Probleme mit der Stromversorgung gesagt?}
{136}{}{Du hast erwähnt, dass ihr Medikamente braucht. Ist jemand in eurer Gemeinschaft krank?}
{137}{}{Wenn die Gemeinschaft Vorräte braucht, warum richtest du keine Handelsroute zu anderen Siedlungen ein?}
{138}{}{Gibt es nicht. Jacob hat versucht, den Generator in Gang zu bringen, um die Straßen und Häuser zu beleuchten, aber bisher ohne Erfolg.}
{139}{}{Vielleicht kann ich helfen?}
{140}{}{Das wäre großartig. Sprich mit Jacob darüber.}
{141}{}{In Ordnung.}
{142}{}{Reden wir über etwas anderes.}
{143}{}{Das interessiert mich nicht. Tschüss.}
{144}{}{Ich spreche später mit ihm. Erzähl mir bitte etwas anderes.}

{145}{}{Meine Tochter braucht Hilfe. Bist du Arzt? Es wäre ein großes Glück, wenn du Arzt wärst oder zumindest einen normalen Erste-Hilfe-Kasten hättest, um ihr Fieber zu behandeln.}
{146}{}{Ich habe etwas medizinische Erfahrung. Erlaubst du mir, die Patientin zu untersuchen?}
{147}{}{Du hast Glück – ich habe einen Erste-Hilfe-Kasten.}
{148}{}{Du hast Glück – ich habe eine Arzttasche.}
{149}{}{Klar, ich helfe gern!}
{150}{}{Ich sehe später nach ihr. Erzähl mir erst einmal etwas anderes.}
{151}{}{Dann gehe ich wieder an meine Arbeit.}
{152}{}{Danke! Das hilft nicht nur meiner Tochter, sondern allen. Hier gibt es immer wieder gesundheitliche Probleme.}
{153}{}{Gern geschehen.}
{154}{}{Deiner Tochter geht es wieder gut.}
{155}{}{Danke! Du hast unserem Haus Freude gebracht. So etwas vergisst man hier nicht.}
{156}{}{Pass auf dich auf.}
{157}{}{Wag es ja nicht, meine Tochter anzufassen! Ich spüre, dass etwas Abstoßendes an dir ist.}
{158}{}{Nun, ich habe tatsächlich eine besondere Beziehung zu Kindern. Da hast du recht ...}
{159}{}{}

{160}{}{Ich habe darüber nachgedacht, aber wir sind so weit von größeren Siedlungen entfernt, dass wir niemanden erreichen können, um Handel anzubieten. Manchmal brauchen wir wirklich etwas – zum Beispiel sind Medikamente und Ausrüstung immer willkommen.}
{161}{}{Wenn ich irgendwann in die Großstadt komme, überbringe ich den Karawanenhändlern euer Angebot.}
{162}{}{Das ist nicht mein Problem. Reden wir über etwas anderes.}
{163}{}{Kein Interesse. Tschüss.}
{164}{}{Das ist eine wirklich gute Idee. Ich erstelle eine Liste mit den Dingen, die wir brauchen. Wir können eine kleine Menge Lebensmittel, sauberes Wasser und Felle tauschen. Sag das bitte den Karawanenhändlern.}
{165}{}{Okay, aber das ist nicht alles, worüber ich etwas wissen wollte.}
{166}{}{Kein Problem. Ich gehe sofort.}
{167}{}{Was die Patientin angeht – hier ist ein Erste-Hilfe-Kasten. Behandle sie selbst.}
{168}{}{Was die Patientin angeht – hier ist eine Arzttasche. Behandle sie selbst.}
{169}{}{}

{170}{}{Du hast von den fehlenden Annehmlichkeiten der Stadt gesprochen. Braucht dein Kind hier etwas?}
{171}{}{Hier, nimm ein Nuka-Cola für deine Tochter. Es ist ein Geschenk.}
{172}{}{Wir versorgen sie mit allem, was sie braucht, aber ... Bevor wir Reno verließen, mochte sie Nuka-Cola sehr gern. Doch die Vorräte hier sind schon vor langer Zeit ausgegangen, und Nachschub ist nirgends zu bekommen.}
{173}{}{Indem du eine zehnte Flasche Nuka-Cola bringst, hast du dir bei den Einheimischen einen besseren Ruf erworben.}
{174}{}{Ein Geschenk? Na ja, danke. So viel Fürsorge für Kinder ist heutzutage selten.}
{175}{}{Du bist jederzeit willkommen.}
{176}{}{Wir brauchen nichts von dir. Sieh lieber zu, dass du hier verschwindest, solange du noch atmest.}
{177}{}{Vielleicht hast du meine besondere Beziehung zu Kindern erraten ...}
{178}{}{Offenbar halten die Einheimischen nicht viel von mir ...}

{180}{}{Was ist? Hast du es geschafft, das Stromnetz zu reparieren? Großartig! Vielen Dank. Jetzt wird das Leben hier viel einfacher, besonders im kalten Winter. Hier, nimm etwas Obst vom Teller, bedien dich. Sobald wir den Elektroherd zum Laufen gebracht haben, werde ich meine Frau als Erstes bitten, einen Apfelkuchen zu backen.}
{181}{}{Du bist jederzeit willkommen.}

{182}{}{Was ist das für ein Geruch?}
{183}{}{Wie ich schon sagte, meine Frau hat einen Apfelkuchen gebacken. Für deine guten Taten hast du dir ein Stück verdient.}
{184}{}{Danke.}

{190}{}{Erzähl mir von den Bikern.}
{191}{}{Wir haben sie nicht hierhergerufen. Früher kamen manchmal Biker zu uns, aber nie so viele. Sie wirken irgendwie nervös, als würden sie auf etwas warten. Ich weiß nicht, worauf. Aber unsere Familie hat diese Kerle schon satt. Für uns alle wäre es besser, wenn sie bald verschwinden würden.}
{192}{}{In Ordnung.}
