{100}{}{Du siehst einen Farmer.}
{101}{}{Du siehst einen sonnengebräunten Bewohner von Bridgeport. Offenbar verbringt er den ganzen Tag damit, brahmin anzusehen.}
{102}{}{}
{103}{}{Du solltest diese Stadt so schnell wie möglich verlassen.}
{104}{}{Danke für deine Hilfe.}
{105}{}{Oh nein, nicht das! Wie sollen wir ohne brahmin überleben?!}
{106}{}{Nun ...}

{110}{}{Hey. Was willst du?}
{111}{}{Erzähl mir von den Bikern.}
{112}{}{Ich helfe dabei, die Herde in den Pferch zu treiben.}
{113}{}{Also, du siehst hier brahmin?}
{114}{}{Erzähl mir von dieser Siedlung.}
{115}{}{Tschüss.}

{116}{}{Hey, du gehörst doch nicht zu diesen Bikern, oder? Falls nicht, dann verschwinde so schnell wie möglich von hier! Diese verdammten Biker haben hier so viel Lärm gemacht, dass meine armen brahmin in der Stadt umhergelaufen sind. Jetzt kann ich sie nicht zurück in den Pferch treiben ...}
{117}{}{Bist du immer noch hier? Verschwinde lieber, bevor diese Biker eine Prügelei anfangen.}
{118}{}{Ah, ohne die Biker ist es so friedlich ... So sollte unser kleines Dorf auf dem Land sein. Moment, brauchst du etwas?}
{119}{}{Danke, dass du mir mit den brahmin geholfen hast. Ohne dich hätte ich ihnen selbst nachjagen müssen. Wenn sie Angst haben, sind sie unberechenbar.}

{120}{}{Sie kamen aus dem Norden hierher. Erst einer, dann noch einer – und jetzt sind so viele gekommen, als hätten sie das geplant. Ich weiß nicht, was sie in unserer kleinen Siedlung suchen, aber wir wollen lieber nicht fragen. Hoffentlich verschwinden sie bald, sie machen nur Ärger.}
{121}{}{Du kannst helfen? Das ist großartig. Denk dran: Wenn sie Angst haben, sind sie sehr stur, und deshalb wird es schwierig, sie einzufangen.}
{122}{}{Ja, ich kümmere mich im Grunde um die brahmin. Aber wir haben nur sehr wenige Leute, deshalb muss jeder manchmal von allem ein bisschen erledigen.}
{123}{}{Unser schönes Bridgeport. Als unsere Familien vor dem Krieg in Reno hierher flohen, war hier niemand. Nur die alten, verfallenen Häuser, bedeckt mit Sand und Dreck. Wir haben lange und hart gearbeitet, um diesen Ort halbwegs bewohnbar zu machen.}
{124}{}{Gern geschehen.}
