{100}{}{Du siehst Jacob.}
{101}{}{Du siehst einen Bewohner von Bridgeport. Seinem Aussehen nach zu urteilen, ist er keiner der örtlichen Farmer.}
{102}{}{}
{103}{}{Verschwinde, bevor wir dir die Beine brechen.}

{110}{}{Was willst du?}
{111}{}{Du siehst nicht wie ein Farmer aus. Erzähl mir von dir.}
{112}{}{Was hältst du von den Bikern?}
{113}{}{Genug über Geografie. Erzähl mir lieber etwas über die Biker.}
{114}{}{Tschüss.}
{115}{}{Genug über die Biker. Erzähl mir etwas über dich. Du siehst nicht wie ein Farmer aus.}
{116}{}{}
{117}{}{}
{118}{}{}
{119}{}{Du siehst nicht wie ein Biker aus. Wenn du nur zum Ausruhen hergekommen bist, solltest du deine Sachen packen und verschwinden. Du willst dich doch nicht mit diesen Bikern anlegen.}

{120}{}{Nein, ich bin kein Farmer. Klar, manchmal helfe ich bei der Ernte oder im Schlachthaus. Aber meine Hauptaufgabe ist es, die Ruinen nach allem Brauchbaren zu durchkämmen. Außerdem bin ich gut im Umgang mit Schusswaffen und kenne mich ein wenig mit Mechanik aus. Meine Fähigkeiten werden also in Bridgeport gebraucht.}
{121}{}{Du warst doch schon an den verschiedenen Orten in der Umgebung, oder? Gibt es dort etwas Interessantes?}
{122}{}{Nun, es gibt einige sehenswerte Orte – Uranium City, New Reno, Hawthorne. Davon hast du bestimmt schon gehört.}
{123}{}{Erzähl mir von Uranium City.}
{124}{}{Erzähl mir von Hawthorne.}
{125}{}{Gibt es außer den Ruinen und diesen Städten noch etwas Bemerkenswertes in dieser Gegend?}
{126}{}{Eine alte Minenstadt im Nordwesten. Sie wurde von einem der Bosse in Reno unterhalten, und das Erz diente als Brennstoff für das Kraftwerk. Aber dort ist etwas Schlimmes passiert, und nun stirbt Uranium City aus.}
{127}{}{Ein Militärstützpunkt im Nordosten. Ich habe dort einmal viel Zeit damit verbracht, die alten Häuser zu durchstöbern. Ein gefährlicher Ort. Das war er wegen der Nagetiere und Roboter schon immer, aber jetzt ist er noch gefährlicher – wegen der Schürfer, die das Gelände plündern. Zwischen den verschiedenen Banden, die dort ihr Unwesen treiben, kommt es ständig zu Kämpfen.}
{128}{}{Im Südosten gibt es eine Fernstraße, aber das nächste Dorf in dieser Richtung ist sehr weit entfernt. Einige besonders verzweifelte Karawanen versuchen, diese Handelsroute zu bewältigen und zwischen Las Vegas und New Reno hin und her zu fahren, aber nur wenige überleben die Reise.}
{129}{}{Was noch?}
{130}{}{Südlich und südwestlich der Berge ist nur Wüste. Es ist ein rauer Ort. Dort kann man nicht leben, geschweige denn reisen. Niemand versucht es auch nur. Ich kann mich an keinen einzigen Fall erinnern, in dem jemand es aus dem Süden hierher geschafft hätte. Kann es jenseits der Wüste noch etwas geben? Ich bezweifle es.}
{131}{}{Zwischen uns und der Wüste im Süden liegt eine Hochebene. Manchmal jage ich dort, aber nie tief in den Bergen – ich will dem örtlichen Stamm, der dort lebt, nicht begegnen.}
{132}{}{Erzähl mir von diesem Stamm im Süden.}
{133}{}{Diese Wilden hatten fast schon vergessen, wie man spricht. Der ganze Stamm ist wahrscheinlich seit dem Großen Krieg von der Außenwelt abgeschnitten, deshalb müssen sie mit ihren Verwandten Kinder zeugen. Ich weiß auch, dass sie Kannibalen sind. Das Schüttelkörpersyndrom und die angenagten menschlichen Knochen auf den Parkplätzen beweisen es. Woher ich das weiß? Ich habe es gesehen. Ich musste mich ihnen sogar ein paarmal entgegenstellen. Sie kämpfen wie Tiere, aber was können sie mit ihren Keulen und Speeren schon gegen mein Gewehr ausrichten?}

{140}{}{Ich habe nichts gegen ihre Lebensweise, aber sie sollten normalen Leuten nicht ihre Gesetze aufzwingen! Wir haben sie nicht hierhergerufen. Als es in Bridgeport nur ein paar Biker gab, war das kein Problem, aber jetzt fangen sie an, uns unter Druck zu setzen. Nicht mehr lange, und unsere schöne Stadt wird zum Kriegsgebiet.}
{141}{}{Was wollen sie hier?}
{142}{}{Keine Ahnung. Ich habe sie reden hören, aber sie scheinen selbst nur eine vage Vorstellung davon zu haben. Vielleicht haben sie Ärger gewittert, wissen aber nicht, worum es geht.}
{143}{}{Man sagt, du versuchst, die Stromversorgung der Stadt wiederherzustellen. Wie läuft es bisher?}
{144}{}{Mir fehlen die Fähigkeiten und die Zeit, mich darum zu kümmern. Warum? Willst du helfen? Nur damit du's weißt: Wir können dich für deine Dienste nicht bezahlen.}
{145}{}{Ich will einfach nur helfen.}
{146}{}{Verdammt, wenn du nichts hast, womit du bezahlen kannst, kommt kein Geschäft zustande.}
{147}{}{Hör zu. In der Garage auf der anderen Straßenseite steht ein Notstromgenerator. Er läuft, aber ich konnte die Häuser nicht mit Strom versorgen. Offenbar bin ich ein lausiger Elektriker. Wie man das hinkriegt? Keine Ahnung. Du musst überall in der Stadt nachsehen, die Schaltkästen überprüfen, dich am Transformator zu schaffen machen und die Korrosion beseitigen. Wenn du ein guter Techniker und schlau genug bist, hast du das im Nu repariert.}
{148}{}{Gibt es hier kein Kraftwerk?}
{149}{}{Nein. Die Stromquelle ist nicht hier. Bridgeport bekommt seinen Strom von woanders über die Stromleitungen.}
{150}{}{Ich sehe, was ich tun kann.}
{151}{}{Wie lange reicht der Generator noch, wenn wir ihn reparieren?}
{152}{}{Wir brauchen nicht viel – Licht, Heizung, Küchengeräte. Wir haben genug Energie gespeichert, um unsere Familien mindestens zehn Jahre lang zu versorgen.}
{153}{}{Ich sehe, du konntest den Strom wieder zum Laufen bringen! Danke. Du warst eine große Hilfe. Ich weiß nicht, wie ich mich revanchieren soll. Hier, nimm diesen Whiskey. Ich habe ihn im alten Haus gefunden und für die Feiertage aufgehoben. Aber mit einem guten Mann teilt man ihn lieber.}
{154}{}{Gern geschehen.}
