{100}{}{}
{101}{}{}
{102}{}{Das ist funktionstüchtig.}
{103}{}{Das kannst du im Kampf nicht tun.}
{104}{}{Warum solltest du das tun?}
{105}{}{Gute Idee, aber der Zeitpunkt ist falsch. Irgendwo im Stromkreis gibt es eine Unterbrechung.}
{106}{}{Das muss nicht repariert werden.}
{107}{}{Du hast es auf beschämende Weise nicht geschafft, den Generator einzuschalten.}
{108}{}{Du schaltest den Generator ein. Wie erwartet funktioniert er einwandfrei. Jetzt muss nur noch das externe Stromnetz in Ordnung gebracht werden.}
{109}{}{Du hast den Strom zu einem Straßentransformator geleitet.}
{110}{}{Du kannst den Generator nicht so umverdrahten, dass der Strom dorthin geleitet wird, wo er gebraucht wird.}
{111}{}{Der Straßentransformator funktioniert jetzt und versorgt die Gebäude mit Strom. Jetzt musst du nur noch sicherstellen, dass der Strom ordnungsgemäß geliefert wird.}
{112}{}{Du hast das gewünschte Ergebnis nicht erreicht.}

{113}{}{Dieses Haus hat jetzt Strom.}
{114}{}{Du hast es nicht geschafft, das Haus mit Strom zu versorgen.}
{115}{}{Das wird hier kaum helfen.}
