{101}{}{Die Bücher, Broschüren und Schriften in diesen Regalen erzählen dir mehr über die Geschichte von Bridgeport.}
{102}{}{Während eines Kampfes kannst du nicht lesen.}
{103}{}{Mit deiner Bildung wäre es viel zu mühsam und langweilig, dich durch so viele Papiere zu wühlen.}
{104}{}{Um diesen Computer zu benutzen, sind wissenschaftliche Kenntnisse erforderlich.}
{105}{}{Um die Veröffentlichungen in diesen Regalen zu studieren, brauchst du nicht nur deine Hände, sondern auch deinen Kopf.}

{110}{}{Diese Regale sind mit allerlei Vorkriegsbroschüren und Büchern sowie den persönlichen Aufzeichnungen des letzten Besitzers gefuellt. Im Allgemeinen behandeln diese Materialien die Geschichte von Bridgeport.}
{111}{}{Lies den Abschnitt über die Vorkriegsgeschichte der Siedlung.}
{112}{}{Lies den Abschnitt über das Jahr 2077.}
{113}{}{Lies den Abschnitt über die Nachkriegsgeschichte der Siedlung.}
{114}{}{Geh weg.}

{115}{}{Es war eine Kleinstadt, die hauptsächlich von zwei Arten von Menschen bewohnt wurde – reichen Familien und Arbeitern der Badeorte. Bridgeport war berühmt für seine Bergresorts mit Seen voller Forellen und makellosen, schneebedeckten Hängen. Ein ruhiger Ort, beinahe ein Paradies, geeignet für ein sorgloses Leben. Auch deshalb richteten sich viele wohlhabende Einwohner Nevadas und Kaliforniens hier Ferienhäuser für Feiertage und Wochenenden ein.}
{116}{}{Nach vereinzelten Informationen wurde das Dorf während des Großen Krieges völlig ausgelöscht. Die Einheimischen hatten nirgendwo Schutz vor der Strahlung, die der Wind aus dem durch Nuklearexplosionen zerstörten Los Angeles im Süden und von Area 51 im Nordosten herantrug. Als ihnen ihr Schicksal klar wurde, feierten viele Einwohner auf den Straßen der Stadt ein Abschiedsfest, entschlossen, dem Tod mit einem Lächeln zu begegnen.}
{117}{}{Das Dorf ist vermutlich seit dem Tag unbewohnt, an dem die Bevölkerung 2077 ausgelöscht wurde. Vor weniger als einem Jahrzehnt brachten die ersten Siedler – Flüchtlinge aus Reno – wieder Leben ins Dorf.}