{100}{}{Du siehst Betty.}
{101}{}{Du siehst das übliche gehörnte Vieh. Offenbar das einzige in dieser Siedlung.}

{110}{}{Muuuh.}
{111}{}{brahmin führen}
{112}{}{brahmin hierlassen}
{113}{}{Nichts tun}

{114}{}{Muuu!}
{115}{}{Schon besser.}
{116}{}{Muuu?}

{117}{}{brahmin mit Dynamit sprengen}
{118}{}{brahmin mit Plastiksprengstoff sprengen}
{119}{}{Du bist frei, Betty. Die Mutanten sind tot, ich brauche dich nicht mehr.}
{120}{}{Betty ist jetzt frei.}

{121}{}{(Das ist kein geeigneter Ort, um einen Köder auszulegen.)}
{122}{}{Du hast die Mutanten in eine Falle gelockt und die Mine gesprengt.}
{123}{}{Brahmin lässt sich Zeit und weigert sich, weiterzugehen.}
{124}{}{Beweg deinen Arsch, du verdammtes Vieh!}

#Ïîïûòêà òîëêàòü (ôğàçû ïğè íèçêîé êàğìå)
{130}{}{Los, du dummes, fettes Vieh!}
{131}{}{Beweg dich, du Vieh!}
{132}{}{Los, oder ich schlag dich mit der Peitsche!}
{133}{}{Wenn du weiter trödelst, setzt es was!}
{134}{}{Du machst mich wütend, du Vieh. O-oh, bin ich wütend!}
{135}{}{Hrm, dummes brahmin ...}
{136}{}{Für deine Sturheit wirst du büßen!}
{137}{}{Na schön, noch ein einziges Mal, dann ist meine Geduld am Ende.}
{138}{}{Beweg dich!}
{139}{}{Komm schon, Betty, Liebes, beweg dich ... Oder ich puste dir den Schädel weg!}