{100}{}{Du siehst Zhu Shi.}
{101}{}{Du siehst eine Frau mit ungewöhnlicher Hautfarbe und schräg stehenden Augen.}
{102}{}{Du siehst Zian Shi.}
{103}{}{Du siehst einen Mann mit ungewöhnlicher Hautfarbe und schräg stehenden Augen.}

{110}{}{Guten Tag, mein Herr.}
{111}{}{Guten Tag, Sheriff.}
{112}{}{Beste Grüße.}

{113}{}{Ich würde gern wissen, wie du hierhergekommen bist.}
{114}{}{Was machst du in diesem kleinen Städtchen?}
{115}{}{Warum gehst du nicht irgendwohin, wo das Leben besser ist?}

{116}{}{Mein Mann Zian und ich kommen aus San-Francisco. Der Kaiser hat entschieden, dass wir der Gemeinschaft nichts nützen, und uns verbannt. Manchmal ist er ein wenig zu hart, aber das machte uns nichts aus.}
{117}{}{Meine Frau Zhu und ich kommen aus San-Francisco. Der Kaiser hat entschieden, dass wir der Gemeinschaft nichts nützen, und uns verbannt. Manchmal ist er ein wenig zu hart, aber das machte uns nichts aus.}
{118}{}{Wer ist der Kaiser?}
{119}{}{Erzähl mir von San-Francisco.}
{120}{}{Warum machte euch das nichts aus?}
{121}{}{Seit der Gründung des Palastes hat niemand den Kaiser gesehen. Und das ist schon lange her. Wir wissen nur, dass er im Palast lebt, und dass ihn außer seinem Ersten Berater niemand sehen darf.}
{122}{}{Ruinen und noch mehr Ruinen – das erwartet jeden Reisenden. Doch Shi bemühen sich sehr, die Stadt mit ihrer Arbeit wieder aufzubauen. Der Palast ist bereits wieder errichtet, der Klan hat sich in den Vororten niedergelassen, und die anderen Viertel warten, bis sie an der Reihe sind.}
{123}{}{Wir wagen es nicht, uns dem Willen des Kaisers zu widersetzen. Er hat es so beschlossen, und wir werden gehorchen. Aber ich muss sagen, dass wir gerne wie Bauern leben. Das Land riecht nach Leben und wirkt beruhigend, während uns die Ruinen der Stadt nur Angst machen und erzürnen.}

{124}{}{Wir bauen Mais an und züchten Brahmin. Wir sind Bauern, dazu sind wir geboren.}
{125}{}{Aber hier leben wir gut. Wir bauen Feldfrüchte an, züchten Vieh und werden nicht vom Lärm und Trubel der Großstadt gestört. Das hier ist jetzt unser Zuhause. Und wir wollen nicht weg, selbst wenn die Erddrachen all unser brahmin verschlingen.}
{126}{}{Erddrachen?}
{127}{}{Oh, Nelson hat es dir noch nicht erzählt? Die Gier der Männer, die in der Mine arbeiteten, hat die Erddrachen geweckt. Sie wollen die Menschen bestrafen, wie die Götter sie einst mit einem Höllenfeuer bestraften, das ganze Städte auslöschte.}
{128}{}{Nehmen wir an, ich möchte sie treffen. Was muss ich dafür tun?}
{129}{}{Nun, nichts ist besser, als Lärm zu machen. Wir mussten sogar einen Krachmacher aus Dosen wegräumen, der nachts unsere Herde bewachte. Er steht in den Regalen.}

#Áğàìèí
{150}{}{Es tut mir leid, aber ich brauche eure brahmin, um diese Siedlung zu retten.}
{151}{}{Betty? Sie ist die Einzige, die uns geblieben ist. Wir können sie nicht einfach so hergeben.}
{152}{}{Betty? Gebt ihr all euren Brahmin Namen?}
{153}{}{Denk darüber nach – eines Tages werden diese unterirdischen Kreaturen nicht nur die Bergleute fressen, sondern auch dich und Betty erwischen.}
{154}{}{Ich kann das brahmin kaufen. Sind 1000 Dollar genug für dich?}
{155}{}{Denk über das Angebot nach, während ich mich ein wenig umsehe.}
{156}{}{Eigentlich waren nicht wir es, die sie so genannt haben, sondern der alte Nelson. Er hat all unsere brahmin so genannt und manchmal scherzhaft vor sich hin gemurmelt: „Betty, meine Schöne, willst du eine Spritztour in meinem Wagen machen?“ Ein langes Leben ohne Frauen scheint ihm zuzusetzen, hihi.}
{157}{}{[Sie tuscheln eine Weile miteinander] Wir sind einverstanden.}
{158}{}{Hier ist das Geld.}
{159}{}{Ich komme mit dem Geld zurück.}
{160}{}{Es ist so traurig, sich von Betty zu trennen ...}
{161}{}{Das spielt jetzt keine Rolle mehr. Jetzt gehört sie mir!}
{162}{}{Ich verstehe. Aber nichts währt ewig.}
{163}{}{[Sie tuscheln eine Weile miteinander] Wir verstehen. Es ist traurig, sich von Betty zu trennen, aber deine Worte klingen so weise, dass wir nicht ablehnen können.}
{164}{}{[Sie schütteln den Kopf] Die gierigen Bergleute sind selbst schuld. Drachen lassen jene in Frieden, die in Frieden leben, so wie wir. Unser ganzer Besitz besteht aus dieser Hütte und Betty. Was könnte ihren Verlust schon wettmachen?}
{165}{}{Danke, du hast das Richtige getan.}

#Æåíñêèå ğåïëèêè
{1110}{}{Sei gegrüßt, Ma'am.}