{100}{}{Du siehst Marilyn.}
{101}{}{Du siehst die Besitzerin des örtlichen Saloons, eine stolze und starke Frau.}
{102}{}{Wenn du nicht aufhörst, wirst du es bereuen!}
{103}{}{Du bist nun deines Amtes als Sheriff von Uranium City enthoben.}

{109}{}{Mach schon, oder verschwinde.}
{110}{}{[Als du den Saloon betrittst, begegnest du dem strengen Blick einer hübschen Frau] Oh, ein neuer Mann in Uranium City? Großartig. Ich hoffe, du fängst keine Schlägereien an oder schleppst Uranerz hier herein ... Und ja, putz deine Stiefel ab, bevor du reinkommst, damit weniger Dreck hereinkommt. Und keine Waffen. Und das sind nur einige unserer Regeln. Wenn dir das nicht passt, bleib draußen.}
{111}{}{Ähm, ich werde mir ... eure Regeln merken.}
{112}{}{Weißt du, du hast eine unerträgliche Persönlichkeit.}
{113}{}{Na gut. Also, was kann ich für dich tun?}
{114}{}{Ja. Ich weiß. Und du bist nur ein Wanderer auf der Durchreise. Also, womit kann ich dir helfen?}
{115}{}{Ich denke, mit ein paar Antworten.}
{116}{}{Wolltest du etwas?}
{117}{}{Bis dann.}
{118}{}{Hmm ...}
{119}{}{Wie kann ich dem Sheriff helfen?}

#Î ìåñòíûõ æèòåëÿõ
{120}{}{Du hast hier eine ganz schöne Gesellschaft um dich herum.}
# 121 Oh Yes. Lousy Indian, Ghoul-paranoid, poor Chinese gangsters and a strutting Turkey from the south. But I already used. Perhaps this is the fate of many mining towns. Here are flocking to work from across the region. And, of course, nothing but their mercantile interests they replace the village did not want to give. Well, instead remaining at least can agree among themselves. It is already an achievement, isn't it?
{121}{}{Oh ja. Ein elender Indianer, ein paranoider Ghul, arme Chinesen, Banditen und irgendein arroganter Arsch aus dem Süden – aber inzwischen bin ich daran gewöhnt. Ich schätze, das ist das Schicksal aller kleinen Bergbaustädte. Von überall aus der Region strömen Leute hierher, um zu arbeiten. Und – natürlich – wollen sie der Gesellschaft nichts bieten außer ihren eigenen geschäftlichen Interessen. Aber die, die bleiben, können sich wenigstens miteinander arrangieren. Das ist doch schon was, oder?}
{122}{}{Erzähl mir von dem „arroganten Arsch“.}
{123}{}{Ein paranoider Ghul?}
{124}{}{Wer sind die armen Chinesen?}
{125}{}{Ich interessiere mich für den Indianer.}
{126}{}{Ich würde gern mehr über die „Banditen“ erfahren.}
{127}{}{Reden wir über etwas anderes.}
{128}{}{Weißt du, das ist langweilig. Also, mach's gut.}
{129}{}{Hm. Zum Beispiel?}
{130}{}{Na gut. Dann bis später.}

{131}{}{Lewis Birch? Er ist ... Wie soll ich es ausdrücken, er ist eine echte Type. Ich weiß nicht, wie sie im Süden leben, aber er hört einfach nicht auf zu reden! So selbstgerechte und arrogante Idioten findet man sonst nirgends. Aber unter anderen Umständen könnte er nützlich sein.}
{132}{}{Nelson. Er ist von hier. Niemand kennt seine Vergangenheit, und ich bezweifle, dass sie viel hergibt. Sonst würde er nicht dauernd so einen verrückten Mist erzählen.}
{133}{}{Eine Bauernfamilie. Sie kamen vor ein paar Jahren aus San Francisco hierher und kommen bestens zurecht. Das sind sehr fleißige Leute. Was ich nicht verstehe, ist, warum zum Teufel sie die Großstadt verlassen haben. Frag sie doch selbst.}
{134}{}{Ich mochte diesen zotteligen Rothaut sofort. Er stammt aus Cheyenne. Viele Jahre lang war er Sklave, bis er schließlich hier landete. Jetzt ist dies seine Heimat.}
{135}{}{Nun, du kannst sie an einer Hand abzählen. Tony ist ein typischer Kerl mit Problemen in der Pubertät. Er ist krank und scheint einfach nicht gesund zu werden. Kelly kann gut schießen, aber es fühlt sich an, als wäre ihre Seele einfach ... leer. Juan ist so brutal, dass man ihm manchmal am liebsten in die Eier treten möchte. Das war's auch schon. Nicht, dass sie richtige Schläger wären, aber wenn das so weitergeht, werden sie sich ihr Brot auf unehrliche Weise verdienen müssen.}
#--Còàğûé âàğèàíò: Íó, èõ íàäî ïåğå÷èñëÿòü ïî ïàëüöàì. Òîíè - îáû÷íûé òàêîé ïàğåíü ñ íåîêîí÷åííûì ïîäğîñòêîâûì êğèçèñîì.
#Áîëåí è âğîäå áû íåèçëå÷èìî. Êåëëè - õîğîøèé ñòğåëîê, íî òàêîå îùóùåíèå, ÷òî çà äóøîé ó íåãî ñîâñåì ïóñòî.
#Õóàí - âåñü òàêîé êğóòîé áğóòàë, ÷òî ïîğîé òàê è õî÷åòñÿ ïíóòü åìó ïî ÿéöàì.
#È, íàêîíåö, Ğîìàíòèê - ñàìûé áåñïîëåçíûé êóñîê ìÿñà âî âñåì Óğàí-Ñèòè. Âîò òàêîé íàáîğ øïèíàòà.
{136}{}{Über den Kranken.}
{137}{}{Der Bengel glaubt, dass er mich irgendwann ins Bett kriegt. Und natürlich wird das nicht passieren ... Aber *vielleicht* war ich zu hart zu ihm. Angesichts seiner Krankheit ... Ja. Das war nicht sehr nett.}
{138}{}{Nein, schon gut - er ist nicht mehr bei uns. Er ist tot.}
{139}{}{Schon? Oh ... [Sie seufzt] An solche Nachrichten bin ich gewöhnt. Ich werde später eine Abschiedsfeier veranstalten.}

{140}{}{Erzähl mir von den anderen Siedlern.}
{141}{}{Über wen willst du diesmal reden?}
{142}{}{Reden wir über etwas anderes.}

{143}{}{Eine Abschiedsfeier? Aber er wollte dich doch ins Bett kriegen!}
{144}{}{Aber das heißt nicht, dass ich ihn jetzt wie Dreck behandeln muss. Heutzutage muss man so einiges ertragen. Ich habe schon Schlimmeres erlebt.}

{145}{}{Stimmt es, dass Birch dir sauberes Wasser gegeben hat?}
{146}{}{Ja! Überraschend, oder? Aber ich glaube, er will nur Eindruck schinden. Der Mann braucht das Gefühl, wichtig zu sein, weißt du?}

#Àğñåíàë Ìığèëèí
{150}{}{Ein schönes Waffenarsenal, das du da im Schrank hast ...}
{151}{}{Ja. Uranium City hat viele „Cowboys“ gesehen, die dem Reichtum nachjagen, und wenn es dann ans Bezahlen geht, haben viele nichts als eine Knarre bei sich. Daher stammt diese Sammlung. Nicht die beste Wahl, aber wenigstens haben wir immer etwas, um uns vor unliebsamen Besuchern zu schützen.}
{152}{}{Ich möchte diese Sammlung kaufen.}

{153}{}{Keine schlechte Idee. Früher hatten wir keine Probleme damit, das Arsenal loszuwerden. Die besten Stücke brachten wir mit einem Karawanenzug nach Reno, den Rest holten sich die Bergleute gegen Bezahlung. Aber jetzt gibt es das alles nicht mehr. Also, weißt du was? [Sie kratzt sich nachdenklich am Ohr] Ich verkaufe alles für 1500 Kröten.}
{154}{}{Ich kaufe es! Hier ist das Geld.}
{155}{}{[Sie wird lebhaft] Was, wirklich? Großartig! Es ist offen, du kannst alles nehmen, was du darin siehst.}
{156}{}{Ausgezeichnet.}
{157}{}{Zu teuer! Für diesen Schrott zahle ich höchstens 300.}
{158}{}{Ach ja? Damit sind nicht einmal die Schäden gedeckt, die die Vorbesitzer verursacht haben. 1500 ist fast geschenkt! Nein, kein Geschäft.}
{159}{}{Überleg doch mal. Neue Arbeiter kommen so bald nicht, und mit Reno wird es keinen Handel mehr geben. So bekommst du wenigstens noch etwas für diesen Schrott.}
{160}{}{[Seufzt schwer] Du hast recht. Selbst wenn ich eine Karawane anheuere oder die Waffen selbst dorthin bringe, verliere ich durch den Transport noch mehr Geld ... Na gut, dann eben 300.}
{161}{}{Klug gewählt. Hier sind 300 Kröten.}
{162}{}{Ach, keine Sorge! Du hast so viel für uns getan, da gebe ich dir das alles gerne. Nimm es! Der Schrank ist offen.}
{163}{}{Danke!}
{164}{}{Nicht so schnell! Du hättest in der Bar nicht mit den Fäusten um dich schlagen sollen. Jetzt bekommst du nicht einfach so irgendwas. Wir sind fertig.}
{165}{}{Ach, schon gut, Sheriff! Du brauchst es ohnehin dringender. Nimm es! Es ist offen.}

#Ìÿñî äğàêîíîâ
{169}{}{Gern geschehen. Sonst noch etwas?}
{170}{}{Ich sehe, eure Speisekarte ist gewachsen?}
{171}{}{Nun, wir haben die Überreste der Erddrachen gefunden und dachten, es wäre schade, sie verkommen zu lassen.}
{172}{}{Und ... wie schmeckt es?}
{173}{}{Bisher hat sich noch niemand vergiftet. Und das Fleisch ist viel nahrhafter als das von brahmin. Außerdem haben wir es satt, ständig dasselbe zu essen.}
{174}{}{Das scheint nicht einfach nur Fleisch zu sein. Verrätst du mir das Rezept?}
{175}{}{Ganz einfach – [Sie wird ganz aufgeregt] Das Fleisch wird mit Pfeffer und Salz gewürzt und dann mit Brahminmilch übergossen. Anschließend werden die Frikadellen in Maisöl gebraten und zusammen mit Grünzeug in Maisfladen gewickelt. Klingt lecker, oder?}
{176}{}{Nun, Würmer sind natürlich auch essbar. Besonders, wenn es sonst nichts zu essen gibt. Kann ich, äh, welche haben?}
{177}{}{Iiiih, wie eklig! Diese Würmer könnten überall herumkriechen, und du isst sie! Igitt! Igitt! Igitt!}
{178}{}{Klar! Hier, nimm dir einen Teller, geht aufs Haus.}
{179}{}{Oh nein! Das ist wirklich köstlich. Hier, probier mal. Geht aufs Haus.}

#Óñëóãè
{180}{}{Kann ich ein Zimmer mieten?}
{181}{}{Ja. Für 50 Dollar kannst du ein Zimmer für die Nacht haben.}
{182}{}{Hast du etwas zu essen?}
{183}{}{Ich kann nur Fleisch und Rot Gut anbieten. Sauberes Wasser behalte ich für mich, tut mir leid.}
{184}{}{Okay, lass uns handeln.}
{185}{}{Nichts, was ich brauche.}
{186}{}{Das ist alles? So verhungert man ja.}
{187}{}{Allerdings, ich will mehr.}
{188}{}{Das reicht. Lass uns über etwas anderes reden.}
{189}{}{Das reicht. Entschuldige mich jetzt – ich habe zu tun.}

#Î ãîğîäå
{199}{}{Keine großen Kundenscharen oder Touristen, verdammt gut. Wo soll ich anfangen, Sheriff?}
{200}{}{Würdest du mir etwas über diese Siedlung erzählen?}
{201}{}{Keine großen Kundenscharen oder Touristen, verdammt gut. Wo soll ich anfangen?}
{202}{}{Genug über die Stadt, ich brauche etwas.}
{203}{}{Machen wir ein andermal weiter.}

{204}{}{Gibt es hier irgendwas, womit man sich die Zeit vertreiben kann?}
{205}{}{Nein.}
{206}{}{Gar nichts? Keine Spielautomaten, kein Schießstand, kein ...}
{207}{}{Ähm, okay.}
{208}{}{Sonst noch was?}
{209}{}{Hmm. Ich verstehe nicht – machst du Witze oder willst du Eindruck schinden? Na ja, egal. Hör zu, das hier ist eine *Arbeits*siedlung. Die Leute kamen her, um Erz abzubauen, und viele von ihnen sind gestorben, weil sie gierig oder dumm waren. Und jetzt kommst du her und fragst, ob es hier irgendwas zum Spaß gibt. Ich schätze, du hattest im Leben viel mehr Glück.}
{210}{}{Prima, was hältst du davon, wenn ich mir selbst etwas zur Unterhaltung suche?}
{211}{}{Na schön. Vergiss es.}
{212}{}{Jetzt bleib mal schön stehen! In meinem Lokal wird nicht gekämpft oder geschossen! Das hier ist ein anständiger Laden. Wer das anders sieht, den werfe ich eigenhändig raus. Geht woanders kämpfen.}
{213}{}{Du? Mich rauswerfen? Ha-ha-ha! Pass auf, dass du dir nicht wehtust, Kleines.}
{214}{}{Keine Sorge, das wird mich trotzdem nicht aufhalten. Ich verprügle Jungs schon, seit ich ein Teenager war.}
{215}{}{Äh, du hast Jungs verprügelt?}
{216}{}{Verdammt richtig! Sie alle dachten, Stärke könne jedes Problem lösen. Und? Ein paar Griffe, und selbst wenn ich nicht gerade ein Muskelprotz bin, läuft es immer gleich ab: Tränen, Gejammer und Heulen vor meiner Mutter. Ha, das waren noch Zeiten!}
{217}{}{Das ändert alles. Lassen wir es so, wie es ist.}
{218}{}{Ist mir scheißegal – ich mache, was ich will. Du bist für mich nur ein lästiges Ärgernis!}
{219}{}{Du! Ich hätte dich gleich nach dem ersten Wort nach draußen werfen sollen. Verdammte Idioten, ihr lasst nur eure Muskeln spielen! Weißt du was? Für dich kostet jetzt alles bei mir doppelt so viel. Ist das klar? Verdammt richtig!}

{220}{}{Was ist das für ein Gebäude auf der anderen Straßenseite?}
{221}{}{Noch eine Frage.}
{222}{}{Das Büro der Bergmannsgilde. Es ist verschlossen, dunkel und drinnen sind Ratten. Da gibt es nichts zu holen. Früher war es der belebteste Ort in Uranium City, abgesehen von der Mine. Jetzt sind die Leute weg und niemand geht mehr hin.}
{223}{}{Erzähl mir etwas über die Gegend.}
{224}{}{Man kann sagen, wir leben am Rand der Zivilisation. Und ehrlich gesagt gefällt mir das. Im besten Fall kommt eine Karawane aus Hub vorbei, aber meistens sind wir abgeschnitten. Jeder versucht, nach new Reno zu kommen ... oder von dort weg.}
{225}{}{Erzähl mir etwas über die Mine.}
{226}{}{Hier gibt es eine Mine. Sie stammt aus der Zeit vor dem Krieg. Über ein Jahr lang haben wir Uranerz für Mr. Wright in New Reno abgebaut, bis diese Mutanten kamen und alles zerstörten. Infolgedessen ist die Siedlung größtenteils verlassen, das Erz wurde nicht verarbeitet und wir versuchen, etwas Lukrativeres zu machen. Zum Beispiel Landwirtschaft.}
{227}{}{Wie hat hier alles angefangen?}
{228}{}{Mit Mr. Wright und seinen Söhnen. Er beschloss, das Kraftwerk der Stadt in New Reno wieder in Betrieb zu nehmen und schickte seine Söhne in die Minen. Ihnen gefiel Uranium City, weil es dort wenigstens ein bisschen technische Ausrüstung gab, wenn auch nur primitive. Dann wurde eine Bergmannsgilde gegründet. Anfangs waren Sklaven die Hauptarbeitskräfte, aber es stellte sich heraus, dass es teurer war, als Arbeiter einzustellen. So lebten wir über ein Jahr lang. Und zwar gut.}
{229}{}{Eines verstehe ich nicht – wie konnten die Leute hier bei der ständigen Strahlung arbeiten?}
{230}{}{Gute Frage. Nelson hat nach der Arbeit in der Mine manchmal sogar nachts geleuchtet. Mit ihm konnte man Strom sparen, haha!}
{231}{}{Ist die Mine wirklich so verstrahlt?}
{232}{}{Na ja, nicht so sehr, wie du vielleicht denkst. Es gibt kein aufbereitetes Uran, nur Erz. Die stärkste Strahlung gab es dort, wo das Erz verarbeitet wurde. Trotzdem ist das ein wunder Punkt für Uranium City. Als hier noch alles unter Wright lief, arbeiteten hier Sklaven und freie Arbeiter. Dabei kam es häufig zu ... Verlusten. Schließlich konnte man trotz Verstrahlung noch über ein Jahr arbeiten, bevor die Krankheit einen dahinraffte. Und in der Zeit konnte man genug verdienen, um seine Familie zu ernähren – oder sein kurzes Leben hell und aufregend zu gestalten. Heutzutage ist das gar nicht so übel.}
{233}{}{Hell und aufregend?}
{234}{}{Oh, hier war so viel los! Aber das liegt alles in der Vergangenheit, als die Siedlung noch voller Menschen war.}
{235}{}{Und wie haben sie es geschafft, die Strahlenkrankheit so lange fernzuhalten?}
{236}{}{Na ja, die Gilde war nicht dumm, weißt du. Sie hatte einen Zeitplan und Regeln. Man musste Gummihandschuhe und -stiefel tragen, eine Maske aufsetzen und alles Metall ablegen, bevor man hineinging. Und natürlich gab es Vorschriften zu den Arbeitszeiten. Wer bereit war, seine Gesundheit für Geld zu opfern, musste mit den Folgen leben. Üblicherweise arbeitete man 14 Stunden, danach gingen alle für einen Drink in meine Bar. Rot Gut floss in Strömen!}
{237}{}{Stimmt.}
{238}{}{Hm. Seltsam, genau das hat mich der Fremde aus dem Süden gefragt. Ich glaube, er ist in seinem Zimmer. Sprich mit ihm, wenn es dich interessiert.}
{239}{}{Prima, jetzt weiß ich wenigstens ein bisschen mehr.}

#Òåêóùàÿ ñèòóàöèÿ
{250}{}{Wir müssen über die aktuelle Lage in Uranium City sprechen.}
{251}{}{Ich höre.}
{252}{}{Was ist hier wirklich passiert?}
{253}{}{Die Leute begannen, in den Minen zu verschwinden, und bald fanden wir tiefe Gräben im Boden und Kleidungsreste. Dann kamen Gerüchte über fleischfressende Würmer auf, aber nur ein paar Leute, wie Nelson, versicherten uns, sie tatsächlich gesehen zu haben ...}
{254}{}{Das war's?}
{255}{}{Dann liefen die Arbeiter davon. Sie glaubten nicht unbedingt an Mutanten, sondern dachten, die Gilde wolle die Arbeiter loswerden, um Kosten zu sparen. Als es immer weniger Bergleute gab, rastete Wright aus. Alle verschwanden, niemand kam zurück – den Rest erledigten die Gerüchte.}
{256}{}{Verstehe. Erzähl mir jetzt etwas anderes.}
{257}{}{Erzähl mir noch einmal, was hier passiert ist.}
{258}{}{}
{259}{}{Warum ziehst du nicht nach Reno oder sonst wohin? An einen besseren Ort?}
{260}{}{Alle sagen das – wenn es hier schlecht ist, sollten wir von hier weg an einen besseren Ort. Aber das ist mein Zuhause! Und weißt du was? Wenn es hier stinkt, sollte ich den Dreck einfach selbst beseitigen.}
{261}{}{Okay. Aber das ist noch nicht alles.}
{262}{}{Was muss getan werden, um den Ort wieder in Ordnung zu bringen?}
{263}{}{Oh, das wird nicht einfach. Erstens müssen wir die Monster loswerden, wer auch immer sie sind. Zweitens müssen wir herausfinden, wem die Mine gehört. Drittens müssen wir wenigstens einen Teil der Belegschaft zurückholen. Das ist alles ziemlich kompliziert.}
{264}{}{Komplikationen machen mir keine Angst. Ich kümmere mich darum!}
{265}{}{Wirklich? Das ist großartig. Ich weiß nicht, was du vorhast, aber in der Mine gibt es eine Menge zu tun, glaub mir.}
{266}{}{Ich krieg das schon irgendwie hin. Jetzt sollten wir noch ein paar Dinge klären.}
{267}{}{Mit wem sollte ich wegen der Monster sprechen?}
{268}{}{Was ist das Problem mit dem Besitz der Mine?}
{269}{}{Was für Arbeiter müssen wir zurückholen, um wieder loszulegen?}
{270}{}{Das ist nicht alles, was mich interessiert.}
{271}{}{Nelson ist ihnen schon lange auf der Spur. Wenn jemand etwas über sie weiß, dann er. Ich habe gehört, es gibt drei Monster und sie orientieren sich am Geräusch.}
{272}{}{Ich habe gehört, Wright ist wegen der Probleme mit der Mine pleitegegangen. Er kann nicht einmal einen Karawanenführer in unsere Stadt anheuern. Da stellt sich die Frage, wie er die Produktion aufrechterhalten will. Nelson kennt sich in der Mine aus wie in seiner Westentasche, auch wenn er ein seltsamer Kauz ist. Wright beschloss, ihn und seine Bande loszuwerden, um weniger Probleme zu haben. Nur hat ihm das nichts gebracht.}
{273}{}{Lass mich dir von allen erzählen.}
{274}{}{Die Mutanten sind erledigt! Alle drei Leichen liegen tot nahe dem Mineneingang.}
{275}{}{Das gibt Hoffnung! Ich weiß gar nicht, wie ich dir danken soll. Ich kann dir nur etwas Rot Gut aufs Haus geben. Hier. [Gibt dir die Flasche und etwas Beef Jerky]}
{276}{}{Irgendwie wirkst du nicht besonders begeistert.}
{277}{}{Ah, entschuldige. Es gibt auch ohne die Monster so viel zu tun, dass einem der Kopf schwirrt.}
{278}{}{Danke, bis später.}
{279}{}{Joseph ist einer der fähigsten Verwalter der Gilde. Er ist der Einzige, der die Produktion organisieren und dafür sorgen kann, dass sie nicht ins Stocken gerät. Das Problem ist, dass ihn seit dem Ärger mit der Mine niemand mehr finden kann. Er scheint sich vor Mr. Wright zu verstecken – oder vielleicht hat der ihn schon gefunden.}
{280}{}{Die anderen?}
{281}{}{Carl – der Bediener der Erzaufbereitungsmaschine. Manche sagen, er sei nach Reno gegangen. Seine Familie lebt irgendwo in den Slums. Ich glaube, seine Frau will nicht, dass er hierher zurückkommt.}
{282}{}{Michael – ein Lieferant der Gilde. Auch er beschloss, nach Reno zurückzugehen, um sich bei Wright zu entschuldigen. Ich weiß nicht, was aus ihm geworden ist.}
{283}{}{Weißt du was, das reicht fürs Erste.}
{284}{}{Dann reden wir über etwas anderes.}
{285}{}{Scheint, als wären jetzt alle da?}
{286}{}{Oh, stimmt ja! Es geht wieder bergauf. Wie in den guten alten Zeiten.}
{287}{}{Großartig. Reden wir über etwas anderes.}
{288}{}{Aber jetzt ist Nelson tot, und niemand ist mehr da, der mir Rat geben kann.}
{289}{}{Ja, ich hab’s gehört. Eine traurige Geschichte. Hm ... Oh, ich glaube, Nelson schlug vor, Lewis Birch Dynamit umzubinden und ihn in die Mine zu schicken. Ich bezweifle, dass das funktioniert.}
{290}{}{Die Monster werden euch nicht mehr belästigen ... [Einzelheiten erzählen]}
{291}{}{Das sind ja gute Neuigkeiten! Und das hast du ganz allein geschafft? Du bist ein großartiger Mensch. Schade, dass ich nichts habe, womit ich dich belohnen könnte. Und es liegt noch viel Arbeit vor uns. Aber ich kann dir etwas von meinen Ersparnissen abgeben. Hier, 300 Dollar. Ich hoffe, das entschädigt dich wenigstens ein bisschen für deine Mühe.}
{292}{}{Ein „Danke“ reicht mir. Geld brauche ich nicht – du kannst es besser gebrauchen als ich.}
{293}{}{Geld – das ist alles, was ich brauche!}
{294}{}{Was, wirklich? Einfach so? Du lehnst ab? Großartig! Aber lass mich dir wenigstens einen Drink aufs Haus spendieren.}
{295}{}{Danke.}
{296}{}{Ich wusste, dass du das sagen würdest.}
{297}{}{Ja. Tschüss.}

{298}{}{Warte! Du hast so viel für uns getan – willst du uns einfach so verlassen? Vielleicht klingt das nicht besonders toll, aber ich würde dich gern als unseren Sheriff sehen. Ich habe sogar schon einen Sheriffstern dafür.}
{299}{}{Es wäre mir eine Ehre, Sheriff dieser Stadt zu sein. Danke für dein Vertrauen, Marilyn.}
{300}{}{Danke, Marilyn, aber ich diene bereits einer anderen Stadt und kann sie nicht verraten. Behalte diese Marke - du hast sie dir verdient.}
{301}{}{[Marilyn nimmt die Marke und steckt sie dir an die Brust] Sie soll dich an gute Taten und Ordnung erinnern! Dieser Titel bringt zwar keine Verpflichtungen mit sich, aber wenn du mal in unserer Gegend bist, vergiss nicht vorbeizuschauen und dich zu erkundigen, wie es läuft. Na, Sheriff?}
{302}{}{In Ordnung, Marilyn. Ich werde dich nicht enttäuschen.}
{303}{}{Wow, die glänzt ja!}
{304}{}{Ich?! Ich war die ganze Zeit hier der Sheriff, verdammt. Aber ... ich verstehe. Nichts für ungut.}
{305}{}{Schon klar. Leb wohl.}

#Ìóçûêàëüíûé àâòîìàò
{310}{}{Ist dieses Möbelstück mit den Lichtern hier nur zur Dekoration?}
{311}{}{Eine Jukebox? Den Arbeitern wurde irgendwann langweilig, also haben sie diesen Schrott aus dem Lager geschleppt. Ich habe sie gewarnt, dass das Ding nicht funktioniert. Niemand hat es reparieren können, also steht es einfach nur da.}
{312}{}{Darf ich sie mir ansehen?}
{313}{}{Na ja, wenn du weißt, was du tust, klar.}
{314}{}{In Ordnung.}
{315}{}{Die Jukebox funktioniert jetzt.}
{316}{}{Oh, wunderbar! Hier war es ziemlich langweilig. Danke. Hier, nimm dir was. Geht aufs Haus.}
{317}{}{Pass auf dich auf.}

#Êâåñò íà âëàäåëüöà øàõòû
{318}{}{Jetzt gehört Nelson die Mine. Bist du zufrieden?}
{319}{}{Die Mine ist wieder in Wrights Besitz, er wird sie bald wieder in Betrieb nehmen.}
{320}{}{Birch hat beschlossen, die Mine zu übernehmen. Was hältst du davon?}
{321}{}{Natürlich! Bei ihm weiß ich wenigstens, woran ich bin. Wir kennen uns schon so lange. Und mit seiner Erfahrung im Bergbau hat Uranium City alle Chancen, sich zu erholen. Andererseits ist Nelson nicht besonders zuverlässig. Er weiß zum Beispiel nicht, wie man mit Leuten verhandelt. Also sollte jemand einen Teil seiner Arbeit übernehmen. Letzten Endes ist das besser als nichts.}
{322}{}{Kein Wunder. Er hat Geld, Beziehungen und potenzielle Kunden. Das ist eine lohnende Entscheidung. Andererseits wird er hier neue Leute einstellen und die Belegschaft verändern. Hoffentlich hat das nichts mit mir zu tun. Trotzdem gefällt mir, dass sich endlich etwas tut.}
{323}{}{Birch? Der hier kann eine Menge bewirken, wenn er will. Ich meine, nicht er selbst, sondern die Organisation, die er vertritt. Sie werden hier für etwas Ordnung sorgen. Nur eine Sache macht mir Sorgen – es liegt nicht in ihrem Interesse, die Stadt wieder aufzubauen. Sie kommen mit ihren Waffen und Ressourcen hierher, holen das ganze Erz und packen dann ihre Sachen und verschwinden, sodass für uns nichts übrig bleibt. Aber früher oder später wird die Stadt sowieso untergehen. Ich möchte nur, dass sie noch ein bisschen länger durchhält.}
{324}{}{Deine Meinung ist mir klar. Bis dann.}

#Weapons in hand
{400}{}{Ich sagte doch: keine Waffen.}
{401}{}{Oh, tut mir leid, das habe ich vergessen. [remove the weapon]}
{402}{}{Meine Waffen habe ich immer dabei!}

#Female character
{1114}{}{Ja. Ich weiß. Und du bist nur ein Wanderer auf der Durchreise. Also, womit kann ich dir helfen?}
{1401}{}{Oh, tut mir leid, das habe ich vergessen. [remove the weapon]}
