{100}{}{Du siehst einen Jungen.}
{101}{}{Du siehst ein Kind, das seiner Mutter ähnlich sieht.}
{102}{}{}
{103}{}{Du bist nun nicht mehr Sheriff von Uranium City.}

{110}{}{[Als er dich sieht, wird der Junge lebhafter] Oh! Sheriff! Cool! Eines Tages werde ich so wie du ... Also, ich werde es versuchen.}
{111}{}{Netter Junge.}
{112}{}{Hallo.}
{113}{}{Du bist noch eine Weile hier, oder?}
{114}{}{Du solltest besser von hier verschwinden.}
