{100}{}{Du siehst Juan.}
{101}{}{Du siehst einen kräftigen Bergarbeiter mit großen, freiliegenden Muskeln.}
{102}{}{Lass mich in Ruhe! Ich sauf mich auch ohne Nelson zu Tode.}
{103}{}{Ist nur ein Test, Alter!}

#Äèàëîã
{107}{}{Mach's dir gemütlich.}
{108}{}{Irgendwie wirkst du nicht besonders freundlich. Als würden dir die Hände nach einer Prügelei jucken.}
{109}{}{Würde der Sheriff seine Zeit mit leerem Gerede verschwenden?}

{110}{}{[Kratzt sich mit seiner behaarten Hand am langen, unrasierten Kinn] Du wirst mich Juan nennen. Und es ist mir scheißegal, was du davon hältst. Wenn du streiten willst, stehe ich jederzeit zur Verfügung.}
{111}{}{Ich sehe, du bist ein geschickter Debattierer.}

{112}{}{[Begutachtet seine schwieligen Handflächen] Mit diesen Händen habe ich schon so viele Diskussionen geführt, dass deine ein Kinderspiel werden. [Er verschränkt die Arme und mustert dich abschätzig und scharf] Glaubst du mir nicht? Das musst du auch nicht. Für einen kleinen Beweis ist es nie zu spät.}
{113}{}{Gut. Ich nehme die Herausforderung an! Wo kann ich dir am bequemsten die Fresse polieren?}
{114}{}{Ich muss jetzt niemandem etwas beweisen. Lass uns einfach reden?}
{115}{}{Dieses Gespräch gefällt mir nicht, also gehe ich.}

{116}{}{Wenn du etwas sagen willst, dann murmel nicht, sondern sprich laut und deutlich. Schwätzer mögen wir hier nicht.}
{117}{}{Ich erinnere mich, du wolltest darüber streiten, wer stärker ist. Hast du deine Meinung inzwischen geändert?}
{118}{}{Wer bist du?}
{119}{}{Wie bist du hier gelandet?}
{120}{}{Was hältst du von Nelson?}
{121}{}{Genug gequatscht für heute.}

{122}{}{Hörst du schlecht? Juan, ich hab's dir doch schon gesagt. Ich habe in der Mine gearbeitet, bis sie geschlossen wurde. Ich könnte immer noch arbeiten, aber niemand ist da, der mich bezahlt.}
{123}{}{Ich kam aus Vegas, kurz nachdem sie aufgehört hatten, mir Jobs zu geben. Sie meinten, ich hätte ein hitziges Temperament. Ha! Echt jetzt?! Sie sollten bereuen, dass sie mich losgeworden sind.}
{124}{}{E-ein großartiger Kerl. Ich hab ihn sofort wie einen Bruder ins Herz geschlossen. Versuch nur, ihn anzufassen, und du bist tot, verstanden? Und außerdem – wer außer ihm könnte hier alles organisieren?}
{125}{}{[Kratzt sich mit dicken Fingern an der Brust und mustert dich] Ich bin kein Masochist. Ich prügle mich nicht grundlos. Aber wenn du versuchen willst, mich im Armdrücken zu schlagen, bin ich dabei. Gleich hier, an Marylins Tisch. Wer verliert, zahlt 100 Bucks. Was hältst du von dem Vorschlag?}
{126}{}{Ausgezeichnet! Ich setze meinen Einsatz und nehme die Herausforderung an!}
{127}{}{Ich stelle erst ein paar Fragen.}
{128}{}{Geht gerade nicht. Später.}

{129}{}{[Pfeift] Hey, alle in der Bar! Seht euch an, wie ich jemanden fertigmache.}
{130}{}{[Geh zur Bar, setz dich an einen Tisch und fang einen Wettkampf an]}
{131}{}{Würde Marylin das nicht stören?}
{132}{}{Wahrscheinlich schon. Aber ich hab sie nicht gefragt.}

{133}{}{Na? Mit Versagern kommt man hier nicht weit, und du scheinst beweisen zu wollen, dass du keiner von ihnen bist.}
{134}{}{Ich bin nicht ganz fit, hust, hust. Vielleicht nächstes Mal.}
{135}{}{Ich hab's mir anders überlegt. Und mir ist egal, was du davon hältst.}

#Ïğî Òîíè
{140}{}{Tony ist ohnmächtig geworden.}
{141}{}{Das musste ja irgendwann passieren. Ich hoffe, er bekommt einen Platz in der Hölle. Irgendwo in der Nähe des Ausgangs.}
{142}{}{Wechseln wir das Thema.}
{143}{}{Das war's.}

#Ñîñòÿçàíèå
{150}{}{*Ar-r-rg!*}
{151}{}{*Hmmm-m!*}
{152}{}{*Hy-y-y-a*}
{153}{}{A-ARGH, DU WICHSER!!}

{154}{}{Du hast den Armdrückwettkampf gewonnen.}
{155}{}{Du hast den Armdrückwettkampf verloren.}
{156}{}{Puh ... Mich hat darin lange niemand schlagen können, und dann tauchst du einfach auf! Wo kommst du her? Ach, egal. Hier ist dein Gewinn.}
{157}{}{Hier, damit du es dir zweimal überlegst, dich mit mir anzulegen.}
{158}{}{Ha! Ich dachte, du wärst ein ernst zu nehmender Gegner. [Nimmt dein Geld] Ja, selbst Geckos machen mir mehr Schwierigkeiten.}
{159}{}{Das ist definitiv nicht mein Glückstag.}
{160}{}{Und du kannst einfach nicht genug bekommen, was? Na gut, Revanche. Hier und jetzt, an Marilyns Tisch. Derselbe Einsatz – 100 $. Zufrieden?}

{161}{}{Was zum Teufel! Schon wieder! Schluss damit, ich fordere dich nicht mehr heraus, genug davon. Nimm deinen Gewinn und sprich bloß nicht darüber, klar?}

#Female character
{1135}{}{Ich hab's mir anders überlegt. Und mir ist egal, was du davon hältst.}
{1156}{}{Puh ... Mich hat darin lange niemand schlagen können, und dann tauchst du einfach auf! Wo kommst du her? Ach, egal. Hier ist dein Gewinn.}
