{100}{}{Du siehst Romantic.}
{101}{}{Du siehst einen Bergarbeiter. Aus irgendeinem Grund nennen ihn alle Romantic.}

{110}{}{Schönes Wetter heute. Gut für eine gute Sache, oder, Sheriff?}
{111}{}{Wie geht's dir, Wanderer?}
{112}{}{Tschüss.}
{113}{}{Ich habe Neuigkeiten – Tony ist gestorben.}
{114}{}{Traurige Nachricht. Aber wir wussten alle, dass er eines Tages sterben würde. Ich hätte nur nicht gedacht, dass es so bald passiert.}
{115}{}{Das war's.}

{1111}{}{Wie geht's dir, Wanderer?}