{100}{}{Du siehst Tony.}
{101}{}{Du siehst einen von Nelsons Männern. Und ihm geht es offensichtlich ziemlich schlecht.}
{102}{}{Du siehst einen von Nelsons Männern.}
{103}{}{  }

{110}{}{*Hustet heftig und spritzt alles voll.*}
{111}{}{Der Patient ist sich bei deinen Maßnahmen nicht ganz sicher.}
{112}{}{Weißt du überhaupt, was du da tust?}

{113}{}{Hey, Doc, ich hab mich noch nie besser gefühlt! Danke, das meine ich ernst. Wenn ich wieder auf den Beinen bin, trinke ich als Erstes, bis ich wieder umfalle!}
{114}{}{Ausgezeichnet, jetzt erzähl mir bitte ein paar Informationen.}
{115}{}{Schon gut. Ruh dich aus.}

{116}{}{Hm? Was ist das?}
{117}{}{Hm? Was ist das? Ohne komme ich gut zurecht.}
{118}{}{Nichts.}

{119}{}{Erzähl mir von Nelson. Wer ist er wirklich?}
{120}{}{[Sieht sich um] Ich will nicht darüber reden. Er ist paranoid, aber wer außer ihm hätte hier Fuß fassen und die Mine ordentlich führen können? Manchmal benimmt er sich seltsam, redet irgendeinen Unsinn, und dann fragt man sich: „Was geht in ihm vor?“ Manche sagen, er käme irgendwo aus dem Süden, aber niemand weiß es genau, denn er ist schon lange hier. Länger als jeder von uns.}
{121}{}{Was weißt du über die Mutanten hier in der Gegend?}
{122}{}{Worüber? Marylin? Ha-ha, nur ein Scherz. Diese Kreaturen da unten sind bloß Würmer. Ich meine, wirklich riesige Würmer. Ein alter Bergmann sagte, die Larven steckten im Fels. Als sie ausgegraben wurden, fingen sie an zu wachsen und zuzunehmen. Wahrscheinlich hat die Strahlung etwas damit zu tun. Aber wen zum Teufel kümmert das noch?}

{123}{}{Dieser Bergmann leidet gleichzeitig an zwei Krankheiten – Strahlenkrankheit und Tuberkulose.}
{124}{}{Ein schwerer Fall, ohne spezielle Medikamente kann man nicht viel tun.}
{125}{}{Symptome verschiedener Krankheiten ... Ich versteh's nicht!}
{126}{}{Du kannst nicht erfassen, worin die Krankheit des Patienten besteht.}
{127}{}{Kaum eine passende Lösung.}
{128}{}{Diese Fähigkeit hilft dir hier nicht weiter.}
{129}{}{Du konntest den Patienten heilen. Nach ein paar weiteren Wochen Reha sollte er sich vollständig erholt haben.}
{130}{}{Bin ich noch am Leben, Doc? Dann hab ich ja noch eine Chance, Marylin flachzulegen ...}
{131}{}{Du spritzt dem Patienten das Medikament intravenös in den Arm. Bald wird es ihm bestimmt besser gehen.}
{132}{}{Du spritzt dem leichtgläubigen Patienten das Gift intravenös in den Arm.}
{133}{}{Du hast dieses Medikament bereits gespritzt. Eine zweite Dosis bringt hier nichts.}
{134}{}{Jetzt ist es nutzlos.}
{135}{}{Doc, du weißt doch, was du tust, oder? Ich vertraue dir ...}
{136}{}{Doc, mir geht's so schlecht ... Ist das normal?}
{137}{}{Hustet ... War das wirklich ... Medizin ... Doc?}
{138}{}{Es sieht so aus, als sei er eines natürlichen Todes gestorben.}
{139}{}{Ruh dich jetzt aus.}