{100}{}{Du siehst Michael.}
{101}{}{Du siehst den Lieferanten der Bergmannsgilde.}

{110}{}{(Du siehst einen Lieferanten; seit er in Reno ein Bettler war, hat er sich erstaunlich verändert.) Oh, du bist es?! Endlich kann ich meinem Retter meine Dankbarkeit zeigen. Nicht jeden Tag trifft man Menschen wie dich.}
{111}{}{Dankbarkeit ist schön und gut, aber kommen wir zur Sache.}
{112}{}{Wie kann ich dir helfen?}
{113}{}{Kann ich Ihnen helfen, Sheriff?}

{114}{}{Was machst du hier?}
{115}{}{Heute nichts.}
{116}{}{Ich versuche, mich mit verschiedenen Leuten und einer Karawane zu einigen, damit sie uns Vorräte liefern.}
{117}{}{Du kaufst etwas?}
{118}{}{Ja, unsere Arbeiter brauchen Ausrüstung und Werkzeug für die Arbeit in der Mine – Schaufeln, Stiefel, Sprengstoff, Medizin. Im Grunde alles, was helfen kann. Die Preise stehen auf der Tafel.}
{119}{}{Das ist alles, was ich wissen muss.}

{120}{}{Der Maschinenführer sagte, ich könnte meine Belohnung abholen.}
{121}{}{Es war die Zündschnur, richtig? Ich bin froh, dass wir das so schnell klären konnten. Hier ist die Belohnung – 300 Bucks.}
{122}{}{Danke.}


{123}{}{[Sell Rad-X, }
{124}{}{[Sell Rad-away }
{125}{}{[Sell the shovel, }
{126}{}{[Sell a sledgehammer, }
{127}{}{[Sell the mount, }
{128}{}{[Sell the flare, }

{129}{}{[Stiefel verkaufen }
{130}{}{[Dynamit verkaufen, }
{131}{}{[Eine Dynamitstange verkaufen, }
{132}{}{[Plastiksprengstoff verkaufen, }
{133}{}{[Einen Molotowcocktail verkaufen, }
{134}{}{[Seil verkaufen, }
{135}{}{}
{136}{}{}
{137}{}{}
{138}{}{}
{139}{}{$]}

{140}{}{Nächste Liste.}
{141}{}{Vorherige Liste.}
{142}{}{Wie viel willst du verkaufen?}
{143}{}{Eins.}
{144}{}{Zwei.}
{145}{}{Drei.}
{146}{}{Vier.}
{147}{}{Fünf.}
{148}{}{Zehn.}
{149}{}{Ich muss mir die Liste noch einmal ansehen.}
{150}{}{Nichts.}
{151}{}{Alles, ich habe (}
{152}{}{ Stück.).}

{153}{}{Gutes Geschäft.}
{154}{}{Versuch jetzt dasselbe mit dem anderen Gegenstand.}
{155}{}{Das war's für heute.}
