{100}{}{Du siehst Carl.}
{101}{}{Du siehst den Bediener der Erzaufbereitungsanlage.}

{110}{}{Hey, hey! Was führt dich her?}
{111}{}{Ich wollte dich dasselbe fragen – wie war die Reise?}
{112}{}{Ich wollte fragen, wie es läuft.}
{113}{}{Tschüss.}

{114}{}{Nun, meine Frau wollte mich nicht einmal aus dem Haus lassen, aber ich habe sie überredet und ihr mein ganzes Geld dagelassen. Ziemlich riskanter Schritt, aber du hast mir new hope fürs Leben in dieser Stadt gegeben. Also erwarte ich fest, es zurückzubekommen, selbst wenn ich nach einem Jahr an der Strahlung sterbe.}
{115}{}{Äh, ein Jahr?}
{116}{}{Nun, die Leute leben hier nicht lange. Und ich muss mit der Erzaufbereitungsmaschine arbeiten, weißt du.}
{117}{}{Erzähl mir von deiner Arbeit.}

{118}{}{Ja, wirklich nicht besonders gut. Der Automatikcomputer der Maschine ist kaputtgegangen. Jetzt muss ich dieses Ungetüm von Hand bedienen. Das kostet viel Zeit, und ich bin dabei stärker der Strahlung ausgesetzt. Ich muss meinen Arbeitsplan anpassen und nur viermal am Tag arbeiten, mit langen Pausen. Wenn wir einen Zulieferer hätten, könnte er wahrscheinlich das Ersatzteil finden, um die Maschine zu reparieren.}
{119}{}{Ja, wirklich nicht besonders gut. Der Automatikcomputer der Maschine ist kaputtgegangen. Jetzt muss ich dieses Ungetüm von Hand bedienen. Das kostet viel Zeit, und ich bin dabei stärker der Strahlung ausgesetzt. Ich muss meinen Arbeitsplan anpassen und nur viermal am Tag arbeiten, mit langen Pausen. Ich habe das benötigte Ersatzteil bei unserem Zulieferer bestellt, aber die Suche wird einige Zeit dauern.}
{120}{}{Jetzt ist alles in bester Ordnung! Der Computer an der Maschine erledigt jetzt die ganze Arbeit für mich, und ich muss nicht mehr so lange in einem verstrahlten Raum sitzen. Danke für deine Hilfe, }
{121}{}{Sheriff.}
{122}{}{Wanderer.}
{123}{}{Was für ein Ersatzteil wird zur Reparatur der Maschine benötigt?}
{124}{}{Eine Sicherung ist durchgebrannt. Das ist zwar nichts Ungewöhnliches, aber wir haben trotzdem keine.}
{125}{}{Ich habe eine Sicherung dabei. Geht die?}
{126}{}{Genau, die brauche ich! Hör zu, ich kann dir das Ding jetzt nicht bezahlen, aber wenn der Zulieferer auftaucht, wird er es tun, ganz bestimmt! Ohne dieses Teil bin ich so gut wie ohne Hände.}
{127}{}{Genau, die brauche ich! Hör zu, ich kann dir das Ding noch nicht bezahlen, aber unser Zulieferer kann es. Ohne dieses Teil bin ich so gut wie ohne Hände.}
{128}{}{Dann nimm sie.}
{129}{}{Ich überleg's mir.}
{130}{}{Danke! Jetzt kann ich wieder voll arbeiten. Wenn der Zulieferer auftaucht, gibt er dir das Geld zurück. Und ich schulde dir einen Schluck Fusel.}
{131}{}{Danke! Jetzt werde ich mich voll ins Zeug legen. Frag den Lieferanten in seinem Büro, er gibt dir das Geld zurück. Ich schulde dir noch etwas Fusel.}
{132}{}{Auf Wiedersehen.}
{133}{}{Der Maschinenführer sieht besorgt aus, während du in deinen Taschen nach dem Gegenstand suchst.}

{134}{}{Neben der Mine steht eine große Maschine zur Erzverarbeitung. Du gibst auf der einen Seite Roherz hinein und erhältst auf der anderen gereinigtes Uran und Berge von Schlacke. Ich bediene die Maschine. Die Sache ist komplizierter, als sie aussieht. Außerdem findet die Arbeit in der Nähe von verstrahltem Erz statt.}
{135}{}{Warum arbeitest du dann dort, wenn du ständig der Strahlung ausgesetzt bist?}
{136}{}{Weil es die einzige ehrliche Möglichkeit ist, meine Familie zu ernähren. Natürlich werde ich in ein, höchstens zwei Jahren sterben, wenn ich die zulässige Strahlendosis nicht überschreite. Aber bis dahin wird meine Familie für mehrere Jahre finanziell abgesichert sein.}

#Female character
{1122}{}{Wanderer.}
