{100}{}{Du siehst Joseph.}
{101}{}{Du siehst den Verwalter der Bergmannsgilde.}

{110}{}{Danke, du hast mir Hoffnung gegeben, Sheriff!}
{111}{}{Danke, du hast mir Hoffnung gegeben!}
{112}{}{[Du siehst den Verwalter der Gilde. Er sieht viel besser und sauberer aus als zuvor.] Oh, sieh mal, wen wir da haben! Jemanden, den ich immer gern sehe. Ich nutze die Gelegenheit, um dir aufrichtig dafür zu danken, dass du mir die Chance gegeben hast, wieder ein normales Leben zu führen. Du hast uns Hoffnung auf die Zukunft gegeben. So etwas passiert in unserem Leben nicht oft. Danke. Das meine ich ernst.}
{113}{}{Gern geschehen.}
{114}{}{Na ja, ich werde dann mal das Büro aufräumen. Hier herrscht ein fürchterliches Chaos ...}
{115}{}{Na dann, bis später.}
{116}{}{Ach, übrigens: Im Safe liegt eine Waffe des früheren Verwalters. Du kannst sie nehmen – eine kleine Belohnung für deine Mühen.}
