{100}{}{Du siehst einen Waffenschrank.}
{101}{}{Du schaust auf einen gewöhnlichen Schrank, der zur Aufbewahrung von Schusswaffen eingerichtet wurde.}

{102}{}{Dem Besitzer würde es nicht gefallen, wenn du ohne Erlaubnis darin herumwühlst.}
{103}{}{Na, na! Du fragst wohl nicht einmal um Erlaubnis, was? }
{104}{}{Wenn du das nächste Mal etwas ohne zu fragen mitnehmen willst, trete ich dir in den Arsch.}
{105}{}{Jetzt reicht's mir!}

{106}{}{Du hast den Gildenverwalter mit deinem Auto zu seinem Zielort gefahren.}
{107}{}{Du hast den Operator mit deinem Auto zu seinem Zielort gefahren.}
{108}{}{Du hast den Gildenlieferanten mit deinem Auto zu seinem Zielort gefahren.}