{100}{}{Du wählst ein Lied und drückst erwartungsvoll auf den Knopf. Doch als Antwort hörst du aus dem Lautsprecher nur ein leises statisches Rauschen.}
{101}{}{Du wählst ein Lied und drückst erwartungsvoll auf den Knopf. Im Inneren der Jukebox rattert der Plattenteller los.}
{102}{}{Die Maschine muss nicht repariert werden.}
{103}{}{Reparatur fehlgeschlagen.}
{104}{}{Du hast neue Lieder in die Maschine geladen.}
{105}{}{Deine Unfähigkeit lässt die Kabel im Spender schmelzen und die Chips durchbrennen. Offensichtlich kann der Musikspieler jetzt nicht mehr repariert werden.}
{106}{}{Diese Maschine ist durchgebrannt und kann nicht repariert werden.}
{107}{}{Diese Maschine funktioniert nicht.}
{108}{}{Du kannst keine neuen Lieder laden, weil der Musikspieler nicht funktioniert.}
{109}{}{Fertig}