{100}{}{Du siehst Avanigizhig, den Nebeltag, den Schamanen der Cheyenne.}
{101}{}{Du siehst einen grauhaarigen Mann in schmutziger Kleidung, dessen Blick in die Ferne schweift.}
{102}{}{Was ist das? Tränke für den Körper? Danke, aber ich habe meine eigenen.}

#Ïëàâàşùèå ôğàçû
#Êîãäà ÃÃ ïîä êàéôîì:
{110}{}{Die Geister sprechen nicht mit jemandem, der den Atem des Feuers in der Nase hat. Ich auch nicht.}
{111}{}{Diese Substanzen lassen den Verschlinger in deinen Körper und deinen Geist eindringen! Solange du unter ihrem Einfluss stehst, werde ich nicht mit dir sprechen.}
#Êîãäà ó ÃÃ â ğóêàõ îğóæèå
{112}{}{Dies ist ein Ort des Friedens, nicht des Krieges. Wir sprechen nicht mit Waffen in der Hand.}
{113}{}{Der Herrscher des Lebens rät uns, unsere Probleme mit Worten statt mit Waffen zu lösen.}
#Êîãäà ÃÃ îòêğûë ñåêğåòíóş âåòêó äèàëîãà
{114}{}{Möge das Glück dich begleiten. Meine Tage sind gezählt, doch vor dir liegt noch ein langer Weg. Danke für alles.}
{115}{}{Mögest du mit dem Geist wandeln, der mich und Ogima all diese Jahre beschützt hat!}
{116}{}{Viel Glück. Und besuch Kanada nicht. Niemals.}

#Ïëàâàşùèå ñîîáùåíèÿ ïğè ğàíåíèè (â 1.0. íå èñïîëüçóåòñÿ):
{120}{}{Böse Taten!}
{121}{}{Indem du mir Böses angetan hast, hast du Böses über dich selbst gebracht!}
{122}{}{Was ist dein Stamm?}
{123}{}{Ich sehe den Blick des Verschlingers in deinen Augen!}
{124}{}{Mein Fluch wird dich für immer verfolgen! Nicht einmal der Tod wird dich erlösen!}
{125}{}{Du bist nur ein Wurm in den Überresten des Verschlingers!}
{126}{}{Dein Stamm verdient Respekt.}

##################################################
#
#      Ïåğâûé äèàëîã
#
##################################################

#ÃÃ ñ íèçêîé ğåïóòàöèåé, ñòàë íàëåò÷èêîì èëè èìååò äîñòèæåíèå ğàáîòîğãîâöà:
{130}{}{Halt, Wanderer! Ich bin nur ein alter Mann und besitze nichts. Lass dich nicht von bösen Geistern leiten ...}
{131}{}{Tue ich nicht. Warum sagst du das?}
{132}{}{Das sind die einzigen Geister, die ich respektiere! Hast du ein Problem damit?}
{133}{}{Na gut, ich mache mich dann auf den Weg.}

{134}{}{Ich sehe in dir eine Dunkelheit, tiefer als die Nacht. Schon der Anblick schmerzt mich. [er seufzt] Nun, vielleicht muss ein Wanderer heutzutage in der Dunkelheit wandeln, nachdem der Verschlinger aus seinem Inneren hervorbrach und mit seinem verzehrenden Feuer die Welt überzog ...}
{135}{}{Genau. Beantwortest du jetzt meine Fragen?}
{136}{}{Aha. Ich glaube, dein Gehirn ist längst abgelaufen.}
{137}{}{Belassen wir es dabei.}

{138}{}{Alles hat seine Zeit. Meine kommt bald.}
{139}{}{Du lässt dich nicht so leicht auf die Palme bringen, was? Vergiss es, ich gehe.}

{140}{}{Gut. Das freut mich zu hören.}
{141}{}{Ich möchte dich etwas fragen.}
{142}{}{Dann sehen wir uns später.}

{143}{}{Hm ... Ich sehe ein Kind des Verschlingers und zugleich einen Freund der Cheyenne. Ich hoffe, du gehst weiter den hellen Pfad, Wanderer ... }

{144}{}{Unser bescheidenes Lager steht dir offen, Wanderer, solange du in Frieden kommst.}
{145}{}{Es ist ein freudiger Tag, wenn du in unser Lager kommst, Wanderer. Wie kann ein alter Schamane dir helfen?}

##################################################
#
#      Âòîğîé äèàëîã - äî óíè÷òîæåíèÿ ğåéäåğîâ
#
##################################################

{150}{}{[Der alte Mann wirkt wie ein Geist zwischen den Gräbern. Seine hohlen Augen starren hoffnungslos ins Leere.] W- ... Wer ist da?}
{151}{}{Was machst du hier, alter Mann? Willst du jemanden ausgraben? Oder hängst du einfach gern bei Leichen herum?}
{152}{}{Ich gehe nur spazieren. Was machst du zwischen den Gräbern?}
{153}{}{Pass auf, ich bin der Verschlinger! Buh-uuuh! [gehen]}
{154}{}{Ich wollte gerade gehen. [verlassen]}

{155}{}{[Er sieht dich eine Weile an. Du bemerkst Tränen in seinen Augen.] Lass mich in Ruhe!}
{156}{}{Halt den Mund, solange du noch ein paar Zähne hast!}
{157}{}{Ganz ruhig, ganz ruhig. Ich gehe ja schon.}

{158}{}{[Er sieht dich eine Weile an. Du bemerkst Tränen in seinen Augen.] Was ich mache? ... Ich weiß es nicht ... }
{159}{}{Hast du Gedächtnisprobleme, alter Mann?}
{160}{}{Vielleicht hätte ich nicht fragen sollen. Verzeih mir.}
{161}{}{Eigentlich will ich es gar nicht wissen. Wir sehen uns.}

{162}{}{Lass mich in Ruhe! Geh!}
{163}{}{Ich hätte nicht fragen sollen, verzeih mir. Ist etwas passiert?}
{164}{}{Nichts. Ich bin es, der um Vergebung bitten muss ... Ich habe mich der Vergessenheit hingegeben und dadurch mein Augenlicht verloren ... }
{165}{}{Was ist passiert?}
{166}{}{Gern.}

#Ïîëó÷åíèå êâåñòà íà ëèêâèäàöèş ğåéäåğîâ
{170}{}{Nichts ... Ich komme nachts immer hierher und kann mich nie daran erinnern, warum. Etwas in mir zerreißt mir die Seele. Ich weiß, dass der Herrscher des Lebens sich um unsere Toten kümmert, aber ... Wie viel Leid müssen wir wegen der Gier des weißen Mannes ertragen?}

{171}{}{Redest du von Plünderern?}
{172}{}{„Die Gier des weißen Mannes“? Wovon redest du?}
{173}{}{Welche Probleme hattest du mit dem weißen Mann?}
{174}{}{Zeigt uns gefälligst den nötigen Respekt, ihr Abschaum! Wir sind die Hunde, die eure Herde beschützen. Ohne uns hätten die Wölfe euch längst gefressen.}
{175}{}{Warum werdet ihr sie nicht los?}
{176}{}{Das interessiert mich gerade nicht.}

{177}{}{Ja, Ogima denkt das auch. Das ist die Wahrheit ... Die Wahrheit in Gefangenschaft.}
{178}{}{Plünderer, möge der Verschlinger sie verdammen. Eines Tages kamen sie zu einem weiteren Überfall und gingen nie wieder fort.}
{179}{}{}

{180}{}{Unsere Vorfahren erzählten uns, dass unser Volk schon immer verfolgt wurde, selbst als Gold noch über diese Lande herrschte. Deshalb versteckte sich unser Volk in den Bergen, als der Letzte Tag kam. Doch obwohl sich die Zeiten geändert haben, sind die Menschen gleich geblieben.}
{181}{}{Die Wahrheit ist, dass der Verschlinger immer weitere Kinder hervorbringen wird. Sie werden kommen und die ersetzen, die er verloren hat. Diese Wahrheit können wir nicht allein besiegen. Wir können nur auf die Gnade des Herrschers des Lebens hoffen.}
{182}{}{Du musst nicht mehr lange warten. Ich bin diese Gnade.}

{183}{}{[Seine Augen lodern] Also hat Ogima diese Entscheidung getroffen, ja? Die, die ich nicht treffen konnte? Na gut! Tu es für uns, mach sie vom Angesicht der Erde weg! Blut für Blut!}
{184}{}{Na gut. Aber etwas Hilfe könnte ich gebrauchen.}
{185}{}{Ich gehe dann über meine Strategie nachdenken.}

{186}{}{Täuschen mich meine Ohren? Oder ... will die rechte Hand des großen Plünderers mich auf die Probe stellen? Dann sag ihm, dass man uns gelehrt hat, vorsichtig zu sein.}
{187}{}{Von mir? Ich bin alt. Aber unser Krieger Gekek, der den Eingang bewacht, kann dir den Weg zu ihrem Lager zeigen. Ich kann dir nur Weisheit mitgeben: Greif sie nicht direkt an. Sie sind starke Kämpfer. Doch selbst dem größten Krieger kann die Kehle durchgeschnitten werden, wenn er unachtsam ist.}
{188}{}{Ich verstehe ... glaube ich. Ich rede mit Gekek.}
{189}{}{Sei vorsichtig, Wanderer.}
{190}{}{Natürlich.}
{191}{}{Ist das so? Ich habe noch nie erlebt, dass ein Fremder unserem Volk ohne Gegenleistung hilft. Vielleicht ist die Zeit gekommen ... }

{192}{}{[Der alte Mann ist offensichtlich niedergeschlagen. Zwischen den Gräbern sieht er aus wie ein Geist.]}
{193}{}{[Gehen]}

{194}{}{Wie könnt ihr mit den Raidern leben?}
{195}{}{Ogima ist ein redegewandter Fuchs. Damit die Kriegsaxt begraben bleibt, zahlen wir den Raidern Tribut und sie lassen uns in Ruhe. Meistens. Es ist nicht schön, aber wenn wir uns nicht an die Abmachung halten, wird es viel schlimmer.}

{196}{}{(murmelt etwas) Und unsere Wege kreuzen sich erneut ... }
{197}{}{Ich möchte dich etwas fragen.}
{198}{}{... und trennen sich wieder.}

{199}{}{Psst! Jetzt ist nicht die Zeit zum Reden, Wanderer. Ich muss mein tägliches Ritual vollenden.}
{200}{}{Dann ein andermal.}

##################################################
#
#      Âòîğîé äèàëîã - ïîñëå óíè÷òîæåíèÿ ğåéäåğîâ
#
##################################################

{201}{}{So etwas habe ich noch nie gesehen – ein Kind des Verschlingers, das Leuten wie uns hilft. Du gibst mir viel zu denken, Wanderer.}
{202}{}{Alle herhören! Unser Held ist zurück!}
{203}{}{Unsere Wege kreuzen sich wieder. Was wird der heutige Tag wohl bringen?}
{204}{}{Ich sollte gehen. Mach's gut.}
{205}{}{Weißt du schon? Die Raider sind Geschichte!}
{206}{}{Was wirst du jetzt tun, da die Raider fort sind?}
{207}{}{Hier in der Nähe müsste ein Radiosender sein. Wo ist er?}
{208}{}{}
{209}{}{}

#Ñïğîñ ïğî ğàäèîñòàíöèş
{210}{}{Hmm ... Dieser Ort ist Fremden normalerweise verboten. Nur dort können wir ungestört unsere heiligsten Riten vollziehen. Aber du verdienst unser Vertrauen, Wanderer. Ich kann dich nicht hinbringen, aber ich verrate dir, wo er ist.}
{211}{}{Na gut, ich finde ihn selbst.}
{212}{}{}
{213}{}{}
{214}{}{}

#Îá óíè÷òîæåíèè ğåéäåğîâ
{215}{}{Die Nachricht verbreitet sich im ganzen Ödland! Danke! Ich bin endlich bereit für meine letzte Reise, auf der ich zu den Geistern meiner Lieben gehen und den Stamm den Jungen überlassen werde.}
{216}{}{}
{217}{}{Apropos Junge: Glaubst du, sie werden es schaffen?}
{218}{}{Schön zu sehen, dass es dir gut geht. Bleib gesund.}
{219}{}{Sie haben noch viel zu lernen. Wie auf einem Minenfeld schaffen es manche durch Glück hindurch, andere umgehen es ganz. Doch wir, die Alten, haben sie all die Jahre sicher hindurchgeführt. Wenn ich meinen Ahnen begegne, werde ich ihnen sagen, dass unsere Jungen ihren Weg finden werden, so wie sie uns den unseren gezeigt haben.}
{220}{}{Du bist ein Schamane. Du weißt mehr als die meisten deiner Stammesgenossen. Kannst du mir die Geschichte dieses Ortes erzählen?}
{221}{}{Kannst du mir die Geschichte dieses Ortes noch einmal erzählen?}

#Èñòîğèÿ ïîñåëåíèÿ
{230}{}{Wir lebten weit im Nordosten, in den Bergen. Unser Stamm überlebte dort den Letzten Tag.}
{231}{}{Wie habt ihr eine so lange Reise geschafft?}

{232}{}{Den größten Teil des Weges legten wir mit dem Zug zurück, aber die Schienen waren nicht stabil genug. Er endete an der Grenze Nevadas, nahe Salt Lake City.}
{233}{}{Erzähl mir mehr über diese Zeit.}
{234}{}{Warum habt ihr euer Land verlassen?}
{235}{}{Salt Lake City? Wo liegt das?}
{236}{}{Das war alles, danke.}

{237}{}{Ich zeige es dir auf deiner Karte. Zu Zeiten, als Gold über dieses Land herrschte, war es eine große Stadt. Seitdem hat sie ihren Glanz verloren, aber dort leben immer noch Menschen.}
{238}{}{Du hast die Koordinaten von Salt Lake City erhalten.}
{239}{}{Das ist über dreißig Jahre her. Als der Verschlinger seinen Tribut auf der ganzen Welt forderte, versteckten die Alten unser Volk in den Bergen. Dort überlebten wir den Letzten Tag. Viele starben danach, als riesige Wolken aus brennendem Staub uns vor dem Herrscher des Lebens verbargen. Ich erinnere mich nicht mehr gut an diese Zeit, ich war noch sehr jung, aber ... Es war schrecklich.}
{240}{}{Das Land selbst stellte sich gegen uns. Die Berge ließen uns an Hoffnung, Feuer und Nahrung denken, doch am meisten fürchteten wir die grausamen Mutanten. Sie griffen Siedlungen an und töteten alle. Von den Menschen blieben nur zerschmetterte Körper und zerrissene Kleidung zurück.}

#Female character:
{1130}{}{Halt, Wanderer! Ich bin nur ein alter Mann und besitze nichts. Lass dich nicht von bösen Geistern leiten ...}
{1143}{}{Hmm ... Ich sehe in dir ein Kind des Verschlingers und zugleich einen Menschen, der unser Volk liebt. Ich hoffe, du gehst weiter den hellen Pfad, Wanderer ... }
{1144}{}{Unser bescheidenes Lager steht dir offen, Wanderer, solange du in Frieden kommst.}
{1145}{}{Es ist ein freudiger Tag, wenn du in unser Lager kommst, Wanderer. Wie kann ein alter Schamane dir helfen?}
{1152}{}{Ich gehe nur spazieren. Was machst du zwischen den Gräbern?}
{1154}{}{Ich wollte gerade gehen. [verlassen]}
{1189}{}{Sei vorsichtig, Wanderer.}
{1199}{}{Psst! Jetzt ist nicht die Zeit zum Reden, Wanderer. Ich muss mein tägliches Ritual vollenden.}
{1202}{}{Alle herhören! Unser Held ist zurück!}
{1210}{}{Hmm ... Dieser Ort ist Fremden normalerweise verboten. Nur dort können wir ungestört unsere heiligsten Riten vollziehen. Aber du verdienst unser Vertrauen, Wanderer. Ich kann dich nicht hinbringen, aber ich verrate dir, wo er ist.}
{1211}{}{Na gut, ich finde ihn selbst.}
