{100}{}{Du siehst ein Kind.}
{101}{}{Du siehst ein hübsches und fröhliches Kind vom Stamm der Cheyenne.}

{102}{}{Warum schaut der Fremde mich so seltsam an?}
{103}{}{Deine Augen sehen aus wie die des Verschlingers.}
{104}{}{Ist etwas nicht in Ordnung, Fremder?}
{105}{}{Mama! Mama! Der Fremde hat Dreck an sich!}
{106}{}{Ich weiß, dass du Dreck gegessen hast!}
{107}{}{Du bist unheimlich!}
{108}{}{Niskigvan würde dir beibringen, keinen Dreck zu essen! Das hat er uns beigebracht!}

{109}{}{Fremder!}
{110}{}{Mama!}
{111}{}{Wer bist du?}
{112}{}{Wir dürfen nicht mit Fremden reden!}
{113}{}{Fremder!}
{114}{}{Ich schreie!}
{115}{}{Ich beiße!}
{116}{}{Fass mich nicht an!}
{117}{}{Geh weg!}

{118}{}{Wir dürfen nicht mit Fremden reden.}
{119}{}{Fremde sind böse.}
{120}{}{Ha-ha-ha!}
{121}{}{:: streckt dir die Zunge raus ::}
{122}{}{Bist du weit gelaufen?}
{123}{}{Ich bin müde ...}
{124}{}{Mama will, dass wir arbeiten!}
{125}{}{Iss diese bösen Leute und verwandle dich in einen Wendigo!!!}
{126}{}{Bist du böse?}
{127}{}{Bist du gut?}
{128}{}{Erzählst du Geschichten?}
{129}{}{Niskigvan hat uns Puppen gemacht, und dann ... Au!}
{130}{}{Kennst du Niskigvan? Er ist gut.}
{131}{}{Heute gibt's gebratene Mäuse. Mjam-mjam!}
{132}{}{Hast du als Fremder schon mal gesalzenen Gecko probiert? Der ist lecker!}
{133}{}{Die Jäger kommen zum Mittagessen und gehen dann wieder.}
{134}{}{Jagen Fremde?}
{135}{}{Einer flog nach Osten, einer nach Westen, einer über das Kuckucksnest!}

{141}{}{Mm ... Mama? ..}
{142}{}{:: snkkrk ::}
{143}{}{Zzzz}
{144}{}{Wer ist da? Oh ... Das ist ...}
{145}{}{Der Schamane hat eine Pis ... Pisto ...}
{146}{}{D... Don... Hrrr...}
{147}{}{...Mami...}
{148}{}{Ich schlafe...}
{149}{}{Morgen...}

{150}{}{Kindern Drogen zu geben, hat deine Seele verdunkelt und den Fluch des Stammes über dich gebracht. Schäm dich.}

{151}{}{Pssst! Ich höre zu!}

#Æåíñêèé âàğèàíò ğåïëèê
{1118}{}{Wir dürfen nicht mit Fremden reden.}
{1119}{}{Fremde sind böse.}
{1120}{}{Ha-ha-ha!}
{1121}{}{:: streckt dir die Zunge raus ::}
{1122}{}{Bist du weit gelaufen?}
{1123}{}{Ich bin müde ...}
{1124}{}{Mama will, dass wir arbeiten!}
{1125}{}{Iss diese bösen Leute und verwandle dich in einen Wendigo!!!}
{1126}{}{Bist du böse?}
{1127}{}{Bist du gut?}
{1128}{}{Erzählst du Geschichten?}
{1129}{}{Niskigvan hat uns Puppen gemacht, und dann ... Au!}
{1130}{}{Kennst du Niskigvan? Er ist gut.}
{1131}{}{Heute gibt's gebratene Mäuse. Mjam-mjam!}
{1132}{}{Hast du als Fremder schon mal gesalzenen Gecko probiert? Der ist lecker!}
{1133}{}{Die Jäger kommen zum Mittagessen und gehen dann wieder.}
{1134}{}{Jagen Fremde?}
{1135}{}{Einer flog nach Osten, einer nach Westen, einer über das Kuckucksnest!}
