{100}{}{Eine Frau vom Stamm.}
{101}{}{Eine Cheyenne-Frau, die auf dem Feld arbeitet.}

#Толкание
{102}{}{Alles klar.}
{103}{}{Ich gehen.}
{104}{}{Du unhцflich!}
{105}{}{Himmelsmutter beschьtze mich!}
{106}{}{Nicht schubsen!}
{107}{}{Du froh sein, mein Mann nicht sehen!}
{108}{}{Geh Geckos schubsen!}
{109}{}{Schubst du mich noch mal, wirst du es bereuen!}
{110}{}{Ich kratze dir die Augen aus!}
{111}{}{Hilfe!!!}

#Попытка заговорить
{112}{}{Ich nicht sprechen.}
{113}{}{Ich passe auf Feld und Kinder auf.}
{114}{}{Дh... Ich nicht reden.}
{115}{}{Geh mit Ogima Black Cloud reden.}

#Попытка заговорить под действием химии или алкоголя
{116}{}{Was du essen?}
{117}{}{Du in Ordnung, Freund?}
{118}{}{Was guckst du?}
{119}{}{Ich mцgen das nicht. Geh!}