{100}{}{}
{110}{}{Ich frage mich, wie sie wohl in einem Salat schmecken würden...}
{111}{}{Besser, wir rotten sie aus, bevor sie anfangen zu reden!}

{112}{}{Merken: Nur die mit Zähnen jäten...}
{113}{}{Ein Maul weniger.}
{114}{}{Wer würde einen Löwenzahn mit einem deathclaw kreuzen?}
{115}{}{Unkraut jäten? Na ja, immerhin besser, als Ratten mit einer Schaufel zu erschlagen.}
{116}{}{Töte eine Pflanze, rette eine Fliege!}
{117}{}{War das etwa ein mutierter Hanf?}
{118}{}{Na, wie gefällt dir das?}

{119}{}{Das sollte reichen!}
{120}{}{Mann, das war langweilig, aber ich hab's geschafft!}
{121}{}{Mann, das war langweilig, aber ich hab's geschafft!}
{122}{}{Du hast alle mörderischen Pflanzen auf diesem Feld getötet.}
{150}{}{Du hast }
{151}{}{ von 5 Pflanzen getötet.}
