{100}{}{Du siehst Gekek den Falken.}
{101}{}{Du siehst einen muskulösen Krieger vom Stamm der Cheyenne mit einem finsteren Gesichtsausdruck.}

{102}{}{Nein! Böse! Strafe, Strafe!}
{103}{}{Du hast 100 Erfahrungspunkte für den Einsatz deines Charismas erhalten.}

{107}{}{Ich nicht sprechen.}
{108}{}{Ich Eingang bewachen.}
{109}{}{[Er schüttelt langsam den Kopf] Nicht reden.}
{110}{}{Ich Stamm sicher machen.}

{111}{}{Was du essen?}
{112}{}{Alles okay?}
{113}{}{Wo du hinsehen?}
{114}{}{[Er runzelt die Stirn] Nicht gut. Geh!}

{115}{}{[Er schnuppert] Schlechter Geruch.}
{116}{}{Das nicht richtig.}
{117}{}{Ich nicht wollen, aber du mich zwingen.}
{118}{}{Böser Fremder! Hinsetzen!}
{119}{}{Was dein Stamm?}
{120}{}{Cheyenne nicht vergessen!}
{121}{}{Du Kind des Verschlingers!}

{122}{}{Du stark, ich schwach.}
{123}{}{Fremder gut! Oder ... nicht?}
{124}{}{Du von gutem Stamm.}
{125}{}{Ich nicht danach fragen!}

{147}{}{Herrscher des Lebens, mach mich stark!}
{148}{}{Ich sprechen!}
{149}{}{Mmm! Ich magischen Rauch einatmen!}
{150}{}{Ich auf Dach gehen.}
{151}{}{Ich nicht sterben! Ich NIEMALS sterben!}
{152}{}{[Murmelt etwas in einer anderen Sprache]}
{153}{}{Wir vertreiben die Wolken ... Siehst du? Sie sind weg!}
{154}{}{Ha-ha-ha-ha!}

#Î'ïğàâêà ê ğåéäåğàì
{155}{}{Lauf in den Busch!}

{156}{}{Ich nicht sprechen mit Fremden.}
{157}{}{Du kannst mit mir reden, Gekek. Dein Häuptling sagte, das sei in Ordnung. Du warst doch schon bei der Basis der Raider, oder? Kannst du mich dorthin bringen?}
{158}{}{[Gekeks Augen werden groß] Ich ... Du ... Hmm! Warum du Raider brauchst?}
{159}{}{Weil ich dein Problem mit ihnen lösen kann, Gekek. Bringst du mich zu ihrer Basis?}
{160}{}{Hmm ... Ja. Ich zeigen dir Weg, wenn du bereit. Aber nicht spät kommen – Gekek hat viele Pflichten!}
{161}{}{Ich bin bereit. Bring mich hin, oh gefiederter Krieger!}
{162}{}{Lass die Flügel hängen, Hawk. Ich bin noch nicht bereit.}

{163}{}{Puh! Gut, dass wir entkommen sind. Sehr schlimm, wenn Raider sehen. Oooh!}
{164}{}{Erzähl mir von ihren Standorten ... Äh ... Wo sind alle?}
{165}{}{Erzähl mir von den Ruinen. Gibt es hier etwas Interessantes?}
{166}{}{Erzähl mir von den Raidern.}
{167}{}{Erzähl mir von ihrem Boss.}

{168}{}{Böse Männer sitzen im Haus. Anführer sitzt oben. Zweibeinige Hunde draußen, passen auf. Vorsicht! Muss verstecken!}
{169}{}{Stimmt.}
{170}{}{Na gut. Ich sehe mich in der Gegend um.}
{171}{}{Altes Dorf. Sand, Dreck, Muell. Niskigvan und Avanigizhig suchen hier Datura-Gras. Aber Vorsicht in Büschen! Große Gefahr! Hmm ... Hinter dem Haus ist ein Wassertank, wie bei den Cheyenne. Und man kann von hinten ins Haus gehen. Das ist alles.}
{172}{}{Ein Wassertank? Vielleicht trinken die Raider daraus ...}
{173}{}{[Er runzelt die Stirn] Raider schlecht. Raider böse! Raider dumm. Lieben Kämpfen, aber schlecht aufpassen! [Er schüttelt den Kopf] Sehr dumm. Die meisten Raider sitzen im Haus. Drei passen draußen auf. Raider machen Feuerwasser, trinken Feuerwasser. Nicht gut! Feuerwasser trinken, Kopf tut weh. Will schlafen. [Seine Lippe kräuselt sich angewidert] Dumm.}
{174}{}{Boss groß. SEHR groß. Trägt Hut und ist schwarz und böse, wie der Verschlinger. Bleibt allein. Boss sitzt oben auf dem Haus.}
{175}{}{Datura-Gras?}
{176}{}{Ja! Datura-Gras ... [er bemüht sich, das richtige Wort zu finden] ... Xander-Wurzel und Broc-Blume. Für Schamanen ist Datura-Gras Rauchpfeife, für Heiler Datura-Gras Medizin! Büsche ansehen. Datura-Gras finden, Niskigvan bringen. Glücklich machen! Aber du Gras nicht mischen, ist gefährlich.}
{177}{}{Ich sehe Schmerz böser Raider. Ich so glücklich! So glücklich!}
{178}{}{Deine Unterdrücker sind tot. Das ist vorbei. Verschwinden wir von hier.}
{179}{}{Ich habe ihr Trinkwasser vergiftet. Hoffen wir, dass es wirkt. In ein oder zwei Tagen sollten wir die Ergebnisse sehen.}

{180}{}{Mir hier gefallen! Mir dort nicht gefallen!}
{181}{}{Ja, der Raider-Stützpunkt ist kein besonders angenehmer Ort. Leb wohl.}
{182}{}{Uff! [er sieht erleichtert aus] Als Raider dich hinter Haus bringen, ich denken, du treffen Herrscher des Lebens!}
{183}{}{Gekek, bring mich noch mal zum Raider-Stützpunkt. Ich muss sehen, ob das Gift gewirkt hat.}

#Íà êàğ'å ğåéäåğîâ, êîãäà ÃÃ ñ íèìè ñíşõàëñÿ
{184}{}{Ich sehen! Du Verräter!!!}
{185}{}{Warte, Gekek! Ich bin kein Verräter! Ich habe nur gelogen, um ihr Vertrauen zu gewinnen!}
{186}{}{Ja. Und?}
{187}{}{Ja. Und jetzt gehe ich zur Bande und erzähle ihnen alles über dich.}
{188}{}{Keiner hat nach deiner Meinung gefragt. Du kannst gehen! [gehen]}

{189}{}{Ich nicht glauben! Du Verräter!}
{190}{}{Warum ich dir vertrauen?!}

{191}{}{Weil ich die einzige Hoffnung deines Stammes bin ... Und weil du noch am Leben bist. Ist das nicht genug?}
{192}{}{Weiß ich nicht. Finde es selbst heraus.}

{193}{}{[Er verengt die Augen, nickt dann langsam und verschlagen] Ja ... Du schlau. Gerissen! Ich glauben.}
{194}{}{Gut. Vertrau mir. Leb wohl.}

#Òåñ'îâûå ñîîáùåíèÿ
{200}{}{Alle Raider wohlauf und am Leben.}
{201}{}{Einer tot!}
{202}{}{Zweiter tot!}
{203}{}{Drei Raider zum Verschlinger geschickt!}
{204}{}{Vier - tot!}
{205}{}{Raider fünf folgt Raider vier!}
{206}{}{Hahaha! Alle Raider tot!}
{207}{}{Erst, wenn alle Raider tot sind.}
{208}{}{Alle Raider wurden ordentlich und lautlos beseitigt.} #This seems to be message box text to me. If Gekek is saying this, then it should be changed.

#Female character
{1161}{}{Ich bin bereit. Bring mich hin, oh gefiederter Krieger!}
{1162}{}{Lass die Flügel hängen, Hawk. Ich bin noch nicht bereit.}
{1170}{}{Na gut. Ich sehe mich in der Gegend um.}
{1179}{}{Ich habe ihr Trinkwasser vergiftet. Hoffen wir, dass es wirkt. In ein oder zwei Tagen sollten wir die Ergebnisse sehen.}
{1185}{}{Warte, Gekek! Ich bin kein Verräter! Ich habe nur gelogen, um ihr Vertrauen zu gewinnen!}
