{100}{}{Du siehst Fatso Jackson.}
{101}{}{Du siehst einen ziemlich fetten Mann.}

#Ïîøåë â 'óàëå'
{102}{}{Muss mal pinkeln.}
{103}{}{Muss mal groß.}
{104}{}{Na, wo steckt Jackson junior?}
{105}{}{Schon wieder! Der explosive Durchfall!!}
{106}{}{Ich geh mal die Kinder ins Schwimmbad bringen.}
{107}{}{Ich geh aufs Klo, rühr nichts an.}
{108}{}{Verdammt, ich mach mir gleich in die Hose!}
{109}{}{::furzt so heftig, dass die Tische wackeln::}
{110}{}{Mein Arsch explodiert gleich ...}

#Óõîäè' èç 'óàëå'à
{111}{}{Scheiß drauf, ich wasche mir nicht die Hände.}
{112}{}{Verdammt, das war rekordverdächtig.}
{113}{}{::furzt so heftig, dass die Wände erzittern::}
{114}{}{Ohhhhh, das tut gut.}
{115}{}{Zeit, den Schwanz einzupacken und weiterzukochen.}
{116}{}{Ich geh mal in die Suppe spucken ...}
{117}{}{He, wer hat das alles hier an die Wand geschmiert? Ziemlich gut. Für eine Zeichnung aus Scheiße.}
{118}{}{Puh, das wird eine Weile dauern, bis sich das verzogen hat.}
{119}{}{Kein Papier? Kein Problem.}
{120}{}{Hoppla, vergessen abzuwischen. Macht nichts.}
{121}{}{Muss schon wieder die Unterhose wechseln. Moment, welche Unterhose?}

#Ïîïû'êà çàãîâîğè'ü, êîãäà îí â 'óàëå'å
{122}{}{Ich bin eine Weile nicht verfügbar.}
{123}{}{Warte verdammt noch mal!}
{124}{}{Ich bin beschäftigt!}
{125}{}{Mach dir nicht in die Hose, ich bin gleich fertig ...}
{126}{}{::furzt so laut, dass sich die anderen abwenden::}
{127}{}{Fühlt! Sich! Gut an!}
{128}{}{Warte, jetzt kommt's ... Hhnnnrrgg!!!}
{129}{}{Hier steh ich nun, gebrochenen Herzens ...}

#Äèàëîã:
{130}{}{He, sieh mal, wer da ist! Der Zirkus hat einen Clown zurückgelassen. Was geht?}
{131}{}{Wie läuft's, Jackson?}
{132}{}{Ich brauche Chems.}
{133}{}{}
{134}{}{Ich habe gehört, hier in der Gegend soll es einen Radiosender geben.}
{135}{}{Ich möchte ein paar Vorräte kaufen.}
{136}{}{Vergiss es, ich gehe.}

{137}{}{Radiosender? Was ist das?}
{138}{}{Das wäre wahrscheinlich ein großes Gebäude mit Antennen.}
{139}{}{Schon gut. Fangen wir noch mal von vorn an.}
{140}{}{Hm, ich habe irgendwo ein großes Metallding gesehen, etwa drei Stockwerke hoch. Ich weiß aber nicht mehr, wo, und von hier aus kann man es nicht sehen. Frag die Wilden im Süden. Einer von ihnen muss davon wissen.}

#Çàêàç íàğêî'û
{141}{}{Ich kann sie herstellen. Bring mir einfach die richtigen Zutaten und mein Geld.}
{142}{}{Stell mir ein Heilpulver her.}
{143}{}{Stell mir ein Gegengift her.}
{144}{}{Stell mir ein stimpak her.}
{145}{}{Ich brauche ein sehr starkes Gift.}

{146}{}{Ich brauche Xanderwurzel und Broc-Blume. Du musst pro Dosis zahlen - }
{147}{}{ Dollar.}

{148}{}{Eine Dosis herstellen.}
{149}{}{Mach zwei.}
{150}{}{Mach drei.}
{151}{}{Mach fünf.}
{152}{}{Mach zehn.}

{153}{}{Ich habe nicht genug Geld ... }
{154}{}{Ich habe die Zutaten nicht ... }
{155}{}{Hier, bitte. Zeig mir deine Magie.}
{156}{}{Ich brauche etwas anderes.}

{157}{}{Ich habe fast alles hier, was ich brauche. Bring mir einfach einen Radskorpionstachel und das Geld für jede Dosis. }
{158}{}{Ich brauche zwei leere Spritzen, Xanderwurzel und Broc-Blume. Alles andere, was ich brauche, habe ich hier. Jede kostet dich }

{161}{}{Geht dich nichts an.}
{162}{}{Warum zum Teufel interessiert dich das? Ich lebe, ich atme. Also ist alles gut.}
{163}{}{Es ist ... [er winkt ab] ... kompliziert. Ich brauche das richtige Zeug, und ich habe nicht alles hier.}
{164}{}{}
{165}{}{Dafür habe ich nicht genug hier. Frag dich in Reno um, du wirst mehr als genug finden.}

#ßä, ïğîèçâîäñ'âî:
{168}{}{Gift? [er schaut dich komisch an und zuckt dann mit den Schultern] Wie auch immer, Geschäft ist Geschäft. Besorg mir drei Radskorpionstacheln, zwei Handvoll Nachtschattenbeeren und eine leere Spritze. Danach brauche ich nur noch einen Tag, um es herzustellen, und }
{169}{}{Na gut, ich mache mich an die Arbeit. Komm morgen wieder, dann ist es fertig.}
{170}{}{Das Zeug ist gut! Nur, äh, verwechsel es nicht mit deinen Stimpaks. [er gibt dir eine Spritze mit sehr starkem Gift]}
{171}{}{Deine Bestellung ist noch nicht fertig.}
{172}{}{Sie ist fertig. Willst du sie noch?}
{173}{}{Gib es mir.}

{210}{}{Hey, Mold! Wenn du schon sterben musst, könntest du vorher nach draußen kriechen?}

#Äåëî î íàğêîäèëåğå
{211}{}{Erzähl mir von dem Händler, der dir schlechte Zutaten angedreht hat.}
{212}{}{[Er winkt ab] Vergiss es. Unsere Jungs haben schon nachgesehen. Du wirst ihn nicht finden.}
{213}{}{Ich habe in Reno nicht denselben Ruf wie deine „Jungs“.}
{214}{}{Hmm ... daran habe ich nicht gedacht. Na gut, hör zu. Er hielt sich im Stadtzentrum auf und handelte mit uns im Keller des El Dorado. Hier ist die Liste des Scheißes, den wir von ihm bekommen haben. Beim letzten Handel hat er uns stattdessen Gift angedreht.}
{215}{}{Was für ein Keller?}
{216}{}{Der Keller unter dem El Dorado-Casino. Dort haben sie den Kampfring. Normalerweise machen wir solche Geschäfte in einer Menschenmenge, damit alle ehrlich bleiben, aber anscheinend hat das nicht funktioniert. Verdammter Kerl.}
{217}{}{Woran erkenne ich ihn?}
{218}{}{Wir nennen ihn Solomon. Am Mittelfinger trägt er einen ringförmigen Schlagring in Schädelform.}
{219}{}{Kannst du mir sonst noch etwas sagen, das mir hilft, ihn zu finden?}
{220}{}{Ich glaube nicht, dass er aus Reno stammt. Wir haben die Händler vor Ort gefragt, aber keiner kennt ihn. Er muss aus irgendeinem Grund in die Stadt gekommen sein, ich weiß nur nicht, weswegen.}
{221}{}{Das reicht.}
{222}{}{Du hast einen weiteren Hinweis auf den Händler.}

#Ïîëó÷åíèå äîñ'èæåíèÿ "Çíàõàğü"
{223}{}{Könntest du mir beibringen, wie man Chems herstellt?}
{224}{}{Für dich doch immer, mein Freund ... Für 500 Kröten.}
{225}{}{500 Kröten?! Dann solltest du verdammt gut unterrichten können. [bezahle ihn]}
{226}{}{500 Kröten?! So viel Geld habe ich nicht!}
{227}{}{Vielleicht ein andermal.}
{228}{}{Was immer du willst, Partner. Kostenlos.}
{229}{}{So hört sich das gut an! Also los, verrat mir deine Geheimnisse ... }
{230}{}{Nicht jetzt. Ich komme später wieder.}

#Ğàçãîâîğ ïî äóøàì
{235}{}{Na gut, vergiss es.}
{236}{}{Was macht ihr?}
{237}{}{Wie läuft es mit der Gang?}
{238}{}{Was ist das für ein Stamm im Süden?}
{239}{}{Was soll das sein, eine Fangfrage? Ich koche und braue Schnaps für die Gang. Wonach sieht's denn aus?}
{240}{}{Was, der Boss gibt dir die kalte Schulter? Draußen sieht's übel aus. Die Leute reisen jetzt in Gruppen, jeder hat eine Knarre. Überfälle werden immer schwieriger. Ich muss mich echt ins Zeug legen, damit ich und die Gang über die Runden kommen. Wenn diese verdammten Indianer nicht wären, hätten wir echt ein Problem.}
{241}{}{Es sieht übel aus. Die Leute reisen jetzt in Gruppen, jeder hat eine Knarre. Überfälle werden immer schwieriger. Ich muss mich echt ins Zeug legen, damit ich und die Gang über die Runden kommen. Wenn diese verdammten Indianer nicht wären, hätten wir echt ein Problem.}
{242}{}{Unser brahmin. Immer wenn wir Essen oder Mädchen brauchen, ziehen wir nach Süden und bedienen uns. Aber Big Louie hat mit ihnen irgendein anderes Abkommen. Er sagt, wir dürfen nicht zu viel nehmen, sonst verhungern sie oder so, und dann bekommen wir irgendwas von ihnen. Also versuchen wir, nicht zu gierig zu werden.}
{243}{}{Dräng mich nicht, du Arschloch!}
{244}{}{Dräng mich, und ich piss dich an! Ich mein's verdammt ernst.}
{245}{}{Ist die Gang schon lange hier?}
{246}{}{Keine Ahnung, ich bin erst seit zwei Jahren hier. Aber man sagt, es sei die älteste Gang in der Gegend. Jeder kennt uns und fürchtet uns.}
{247}{}{Kannst du mir etwas über diese Gegend erzählen?}
{248}{}{Willst du mich verärgern? Vergiss es, hör einfach zu. Das hier ist unsere Basis, aber wir sind überall. Wir haben sogar eigene Leute in Reno – Stryker und Thompson. Wenn du mal dort bist, halt dich von ihnen fern, außer du gehörst zu uns. Unterwegs liegt dieses Dorf voller Indianer. Wir kriegen gutes Zeug von ihnen – sie haben zu viel Angst, gegen uns zu kämpfen, wollen aber nicht weg, also tun sie im Grunde, was wir sagen.}
{249}{}{Was kannst du mir über Big Louie erzählen?}
{250}{}{Kennst du irgendwelche Geheimnisse aus der Gegend?}
{251}{}{Der Boss? Leute wie ihn muss man fürchten und respektieren. Das heißt, man redet nicht über sie.}

{252}{}{Ja, ich kenne eins. Für 100 Bucks erzähl ich's dir.}
{253}{}{Her damit, Bruder. Ich bin ganz Ohr!}
{254}{}{So dringend muss ich's nicht wissen.}
{255}{}{Ja, ich kenne eins. Für 50 Bucks erzähl ich's dir.}
{256}{}{Aha ... [er beschnuppert das Papier und knickt den Rand des Dollarscheins, um zu sehen, ob er falsch ist] Wir haben irgendeinen Schwachkopf in der Einöde gefunden und ihn hergebracht, um im Ring ein wenig Spaß mit ihm zu haben. Wir haben ihn im Keller eingesperrt, aber irgendwie hat er das Schloss aufgebrochen, etwas Dynamit aus dem Lager geholt und ist durch die Tunnel entkommen, während wir überall nach ihm gesucht haben. Unser Wachposten hat ihn schließlich in den nördlichen Ruinen gesehen und ihm ein paar Kugeln verpasst. Die Leiche haben wir aber nie gefunden. Falls du also über sie stolperst, gehört dir alles, was er bei sich hat.}
{257}{}{Na gut, wir sehen mal.}

{260}{}{Was weißt du über Balder?}
{261}{}{Er ist ein verdammtes Stück Scheiße. Er war unser Kontaktmann in Reno, aber unser letztes Treffen war eine Falle. Er hat unsere Männer in einen Hinterhalt gelockt und viele gute Leute auf dem Gewissen. Warum, weiß ich nicht – ich glaube nicht, dass es nur ums Geld ging. Aber seitdem hat ihn keiner mehr gesehen. Einige sagen, er hockt noch immer in Reno, aber keine Ahnung. Wohin sollte er sonst gehen?}
{262}{}{Stimmt.}

#Female character
{1155}{}{Hier, bitte. Zeig mir deine Magie.}
{1161}{}{Geht dich nichts an.}
{1170}{}{Das Zeug ist gut! Nur, äh, verwechsel es nicht mit deinen Stimpaks. [er gibt dir eine Spritze mit sehr starkem Gift]}
{1224}{}{Für dich doch immer, mein Freund ... Für 500 Kröten.}
{1240}{}{Was, der Boss gibt dir die kalte Schulter? Draußen sieht's übel aus. Die Leute reisen jetzt in Gruppen, jeder hat eine Knarre. Überfälle werden immer schwieriger. Ich muss mich echt ins Zeug legen, damit ich und die Gang über die Runden kommen. Wenn diese verdammten Indianer nicht wären, hätten wir echt ein Problem.}
{1241}{}{Es sieht übel aus. Die Leute reisen jetzt in Gruppen, jeder hat eine Knarre. Überfälle werden immer schwieriger. Ich muss mich echt ins Zeug legen, damit ich und die Gang über die Runden kommen. Wenn diese verdammten Indianer nicht wären, hätten wir echt ein Problem.}
