{100}{}{Du siehst Makkon.}
{101}{}{Du siehst einen kleinen Cheyenne-Jungen namens Makkon der Kleine Bär.}

{102}{}{Das wird nicht funktionieren. Dieser Junge braucht eine umfangreiche Operation.}
{103}{}{Er braucht eine Operation.}

#Ïîñëå îïåğàöèè
{110}{}{Hey, Mister!}
{111}{}{Wie geht es dir, Makkon?}
{112}{}{Schön, dich zu sehen.}
{113}{}{Ich kann jetzt sogar rennen! Niemand glaubt es! Du bist ein großer Schamane, wie Avanigizhig! Danke, danke!}
{114}{}{Das ist gut. Ich hoffe, du wirst wieder gesund.}
{115}{}{Schade, dass ich nicht wie früher rennen kann. Aber ich bin froh, dass meine Beine nicht mehr wehtun! Danke! Möge der Herrscher dich immer auf deinem Weg begleiten!}
{116}{}{Ich gehe jetzt komisch, aber alles ist besser als vorher. Es war so furchterregend ... Ich sah böse Geister um mich herum, die darauf warteten, dass ich sterbe, wie damals, als ich aus Versehen Avanigizhigs Trank getrunken habe. Danke, dass du mich davor gerettet hast.}

#Ëåæèò â áåcñîçíàíèè
{120}{}{Das arme Kind ist bewusstlos. Seine blutigen, geschwollenen Beine sind mit Stoff und Kräutern umwickelt, und aus einer Schale in der Nähe steigt betäubender Rauch auf. Doch ohne eine Operation können diese Maßnahmen das Unvermeidliche nur hinauszögern.}
{121}{}{[Lass ihn in Ruhe]}

{122}{}{Eine medizinische Untersuchung durchführen.}
{123}{}{Selbst durch die Schwellung und Entzündung kannst du erkennen, dass seine Knochen und Muskeln gebrochen und zerrissen sind. Um sich davon zu erholen, bräuchte er eine umfangreiche Operation.}
{124}{}{Finde heraus, wie lange der Patient in diesem Zustand noch leben wird.}
{125}{}{Ermittle die Heilungschancen.}
{126}{}{Untersuche den Jungen gründlich.}

{127}{}{Es ist schwer zu sagen, wie lange der Patient noch leben wird – wahrscheinlich ein paar Wochen bis sechs Monate. Ohne rechtzeitige medizinische Versorgung ist der Tod jedoch unvermeidlich.}
{128}{}{Dafür hast du nicht die nötigen medizinischen Kenntnisse. Du brauchst die Hilfe eines erfahreneren Arztes.}
{129}{}{Nach der Untersuchung bist du zuversichtlich, dass du das Leben des Jungen retten kannst. Wie vollständig er sich erholen wird, lässt sich allerdings nur schwer vorhersagen.}
{130}{}{Du kannst nicht einmal feststellen, wo sich die Brüche befinden. Das übersteigt eindeutig deine Fähigkeiten.}
{131}{}{Dieser Patient wird mit traditioneller Medizin behandelt, etwa mit Abkochungen aus Wurzeln und Blüten, Mäusekot und Ruß. Obwohl diese Behandlung schmerzlindernd, beruhigend, antiseptisch und heilungsfördernd wirkt, reicht sie nur aus, um den Tod hinauszuzögern, nicht aber, um die Genesung zu fördern. Er ist in einem qualvollen Zustand zwischen Leben und Tod gefangen.}
{132}{}{Beurteile die verfügbaren chirurgischen Instrumente.}
{133}{}{Im Zelt des Heilers gibt es einige primitive Werkzeuge, aber sie reichen nicht aus. Für die Behandlung des Jungen brauchst du Schmerzmittel, ein stimpak zur Beschleunigung der Gewebereparatur, ein Erste-Hilfe-Set oder ein Arztbesteck, ein Skalpell oder eine andere scharfe Klinge und natürlich beeindruckende medizinische Fähigkeiten.}
{134}{}{Bereite den Patienten auf die Operation vor.}
{135}{}{Lass den Patienten in Ruhe.}

{136}{}{Dem Heiler wird deine Eigeninitiative wahrscheinlich nicht gefallen. Solange er in der Nähe ist, kannst du die Operation nicht durchführen.}
{137}{}{Der Heiler erzählt den Kindern am Lagerfeuer Geschichten. Du wirst etwa eine Stunde Zeit haben, um die Operation durchzuführen. Das sollte reichen.}
{138}{}{Ich bin bereit. Fangen wir an!}
{139}{}{Als du das geschwollene Glied betrachtest, wird dir klar, dass du nicht einmal feststellen kannst, wo sich die Brüche befinden. Denk gar nicht erst daran, diese Operation allein durchzuführen.}
{140}{}{Makozid folgt dir immer noch durch das ganze Dorf. Ohne seine Erlaubnis kannst du die Operation nicht in seiner Gegenwart durchführen.}

#Ïğîâåğêà ìåäèöèíñêîãî ñíàğÿæåíèÿ
{141}{}{Makkon könnte während der Operation wieder zu Bewusstsein kommen, aber du hast Schmerzmittel, um ihn ruhigzustellen.}
{142}{}{Makkon könnte während der Operation wieder zu Bewusstsein kommen, und du hast nichts, um seine Schmerzen zu lindern.}
{143}{}{[Weiter]}
{144}{}{[Gehen]}
{145}{}{Du brauchst Mull und Verbände. Zum Glück hast du beides in deiner Arzttasche.}
{146}{}{Du brauchst Mull und Verbände. Zum Glück hast du beides in deinem Erste-Hilfe-Kasten.}
{147}{}{Du brauchst Mull und Verbände, aber du hast keine.}
{148}{}{Nach der Operation solltest du ihm eine stimpak in die Beine spritzen, um den Heilungsprozess anzukurbeln.}
{149}{}{Du brauchst eine stimpak, um den Heilungsprozess nach der Operation zu beschleunigen, aber du hast keine.}
{150}{}{Du brauchst eine Klinge, um mit der Operation zu beginnen. Zum Glück hast du eine in deinem Rucksack.}
{151}{}{Bleib stark, Makkon. Sobald ich deine Knochen gerichtet habe, können sie wieder zusammenwachsen.}
{152}{}{Du brauchst jetzt nur noch eine Klinge für die Operation.}
{153}{}{Du hast alles, was du für die Operation brauchst. Niemand kann dich sehen. Der perfekte Zeitpunkt, um anzufangen!}
{154}{}{Während und nach der Operation brauchst du sauberes Wasser, um Makkons Wunden und deine Hände zu waschen.}
{155}{}{Du hast immer noch nicht alles, was du für die Operation brauchst.}
{156}{}{}
{157}{}{}

#Óäà÷íàÿ îïåğàöèÿ
{170}{}{Wer ... Wer bist du? Bist du ein Retter, gesandt von der Himmlischen Mutter?}
{171}{}{Äh, das ist kompliziert ...}
{172}{}{Was ist hier los ... Beim Herrscher! Fremder, was hast du getan?!}
{173}{}{Es ist ein Wunder, Struppige Federn! Der Fremde wurde von der Himmlischen Mutter gesandt, um mich zu heilen! Mir geht es ... Mir geht es besser!}
{174}{}{Lass mich dich ansehen, Makkon ... Es ist ... Es ist ... Oh, Himmlische Mutter! Es ist ein Wunder!}
{175}{}{Du erhältst 10000 Erfahrungspunkte und die ewige Liebe des Cheyenne-Stammes, weil du Makkon geheilt hast.}

#Íåóäà÷íàÿ îïåğàöèÿ
{180}{}{Was ist hier los ... Beim Herrscher! Fremder, was hast du getan?!}
{181}{}{Ich wollte ihm helfen, aber sein Zustand war zu ernst. Ich habe alles getan, was ich konnte.}
{182}{}{Habe ich dir das erlaubt?! Habe ich dich darum gebeten?!}
{183}{}{Er lag im Sterben! Ich wollte ihm helfen!}
{184}{}{Deine "Hilfe" hat dieses Kind getötet! Verschwinde!}
{185}{}{Verlass dieses Dorf und kehr nie zurück!}
{186}{}{Wenn dein Weg je wieder den Cheyenne kreuzt, mach kehrt! Von diesem Tag an werden die Cheyenne dich hassen!}
{187}{}{Du konntest Makkon nicht heilen, aber es war eine großartige Lernerfahrung. Du erhältst 5000 Erfahrungspunkte und deine Arzt-Fertigkeit steigt um 10.}

#Female character
{1110}{}{Hey, Fräulein!}
{1112}{}{Schön, dich zu sehen.}
{1113}{}{Ich kann jetzt sogar rennen! Niemand glaubt es! Du bist ein großer Schamane, wie Avanigizhig! Danke, danke!}
