{100}{}{Du siehst Makozid Bärentatze.}
{101}{}{Du siehst einen breit gebauten, stark vernarbten Krieger.}
{102}{}{Du böse! Strafe!}

#Íàíåñåíèå ãåğîåì óğîíà
{114}{}{Ugh. Stinkt.}
{115}{}{Du nicht gut gemacht.}
{116}{}{Ich nicht wollen. Deine Schuld!}
{117}{}{Böser Fremder! Igitt!}
{118}{}{Was für Stamm du?}
{119}{}{Himmlischer Vater bestrafen dich!}
{120}{}{Nein!}
{121}{}{Ich STARK!}
{122}{}{Gut ... für Fremden.}
{123}{}{Dein Stamm ehrenvoll.}
{124}{}{Ich nie verzeihen!}

#Óñòàğåâøèé äèàëîã ïğî øêóğû ãåêêî - íå èñïîëüçóåòñÿ!
{141}{}{Du hast bestimmt eine Menge Geckos gehäutet, oder?}
{143}{}{[Er nickt einmal] Ja. Ich häuten gut. Sehr gut! Alle Cheyenne benutzen meine Häute!}
{144}{}{Kannst du es mir beibringen? Ich wollte schon immer wissen, wie das geht.}
{145}{}{[Er lächelt mit seinen schwarzen Zähnen] Ich lehren! Ich lehren! [du lernst eine Weile etwas über Geckos, ihre Gewohnheiten und ihren Platz im örtlichen Ökosystem, dann – endlich – darüber, wie man sie richtig häutet]}
{146}{}{Danke, Makozid! Ich habe das Gefühl, vom Besten gelernt zu haben. Kann ich dich noch etwas fragen?}
{147}{}{Danke, Makozid! Ich habe das Gefühl, vom Besten gelernt zu haben. Aber jetzt muss ich gehen.}
{148}{}{Makozid Bärentatze hat dir beigebracht, wie man Geckos häutet. Du erhältst 750 Erfahrungspunkte.}

#Ïëàâàşùèå ïğåäóïğåæäåíèÿ - íå èñïîëüçóåòñÿ, òàê êàê îïöèÿ ïåğåíåñåíà òğèãåğó ñ äğóãèì ñêğèïòîì:
{161}{}{Du nicht hier gehen!}
{162}{}{Geh weg von hier!}
{163}{}{Nicht deins!}
{164}{}{Geh hier weg!}
{165}{}{Du gehen wohin?}
{166}{}{Ogima, anderer Weg!}

{167}{}{Warum du zu Bäumen gehst?}
{168}{}{Was du von Bäumen willst?!}
{169}{}{Was du denkst?}
{170}{}{Du kommst zurück!}
{171}{}{Du nervst Makozid.}

{172}{}{Du nicht hier zu Hause, Fremder!}
{173}{}{Geh weg vom Zelt, Fremder.}
{174}{}{Ogima nicht hier, Fremder. Geh zum großen Zelt.}
{175}{}{Du nicht hierhergehen, Fremder. Verboten.}

{176}{}{Wo verstecken, Fremder? Komm her!}


##########################################################
#
#          åğâûé äèàëîã
#
##########################################################

{300}{}{Halt, Bleichgesicht! Ich – Makozid, Bärentatze, Wächter der Cheyenne. Ich beobachte dich. Du erledigst dein Geschäft schnell. Dann gehst du.}
{301}{}{Erledige dein Geschäft oder geh.}
{302}{}{Wer hat hier das Sagen?}
{303}{}{Bleichgesicht? So nennst du Fremde?}
{304}{}{Pass auf deinen Ton auf, sonst ...}
{305}{}{Na gut.}
{306}{}{Keine Sorge, ich mache keinen Ärger.}
{307}{}{Gutes Gespräch, Bleichgesicht.}
{308}{}{Na gut.}
{309}{}{}

{310}{}{Häuptling Ogima Black Cloud. Wohnzelt hinter dem Wassertank.}
{311}{}{[Er kichert] Viele Fremde sehen Cheyenne, du nicht anders. Gesicht sieht aus, als fürchtest du Sonnenlicht.}
{312}{}{Das Ödland frisst viele von deiner Sorte. Das Ödland frisst auch dich, früher oder später.}
{313}{}{Bedrohst du mich? Willst du kämpfen?}
{314}{}{Na gut, ich verstehe. Lass uns das friedlich regeln.}
{315}{}{Vielleicht kämpfen wir, wenn du bereit bist. Aber nicht jetzt.}
{316}{}{Na gut, wir werden ja sehen.}

##########################################################
#
#          Âòîğîé äèàëîã
#
##########################################################

#Îñíîâíûå âåòêè

{320}{}{Bleichgesicht!}
{321}{}{Bleichgesicht!... Hm. Deine Augen ... Augen der Kinder des Verschlingers.}
{322}{}{Was weißt du über die Räuber?}
{323}{}{Erzähl mir von deinem Stamm.}
{324}{}{Weißt du etwas über einen örtlichen Radiosender?}
{325}{}{Du wirst nicht umsonst Bärentatze genannt, oder? Mal sehen, wer stärker ist!}
{326}{}{Bis dann.}
{327}{}{}
{328}{}{}
{329}{}{}

{330}{}{Du Frage dazu haben?}
{331}{}{Stimmt.}
{332}{}{Böse Männer. Kinder des Verschlingers. Nichts anderes zählt.}
{333}{}{Wenn du sie so sehr hasst, warum wirst du sie dann nicht los?}
{334}{}{Stimmt.}

{335}{}{Hm. Ogima weiß, die Kinder des Verschlingers sind böse, aber andere Kinder des Verschlingers aufzuhalten. Cheyenne töten Plünderer - andere kommen. Das Böse beginnt von Neuem.}
{336}{}{Das ist eine schwierige Lage.}

{337}{}{Cheyenne kamen vor langer Zeit hierher. Viele Monde sind vergangen. Jetzt - Heimat. Ogima Häuptling, Jäger jagen Beute, Frauen ernten Feldfrüchte, Wachen halten die bösen Kinder des Verschlingers auf.}
{338}{}{Ogima?}
{339}{}{Böse Leute?}
{340}{}{Jäger?}
{341}{}{}
{342}{}{Das wollte ich wissen.}
{343}{}{Ogima sehr klug. Wassergeister, Feuergeister beschützen ihn. Ogima findet Lager, spricht mit bösen Leuten. Ogima spricht mit dir - ich nicht gut sprechen.}
{344}{}{Tier töten, Tier nehmen, Tier essen. Cheyenne ernähren.}
{345}{}{Warst du ein Jäger?}
{346}{}{Vor Wache? Nein. Makozid kein Jäger, Makozid Kundschafter, dann Ogima Makozid zur Wache gemacht.}
{347}{}{Erinnerst du dich noch daran, wie man kundschaftet? Kannst du es mir beibringen?}

#Îáó÷åíèå

{350}{}{Nein, Bleichgesicht. Ich nicht lehren. Such Lehrer im Lager.}
{351}{}{Keine Chance? Na gut.}
{352}{}{Nein, Bleichgesicht. Du Fremder. Fremder gefährlich. Cheyenne helfen gefährlichem Fremden nicht.}
{353}{}{Du vertraust mir nicht? Na gut.}
{354}{}{Ja, Bleichgesicht, du loyal. Aber tu Gefallen, bevor ich lehre.}
{355}{}{Klar, was brauchst du?}
{356}{}{Die Forderungen hören nie auf, oder?}

{357}{}{Langes Gespräch. Bring Sandwich, bring Milch. Ich hungrig.}
{358}{}{Sandwich und brahmin Milch. Ich bin gleich zurück!}
{359}{}{Ich überleg's mir.}
{360}{}{Hier sind das Sandwich und die brahmin Milch.}
{361}{}{Ha! Siehst du, Gut hat zwei Seiten, helle Seite, dunkle Seite. Manchmal gibt dunkle Seite mehr Wissen.}
{362}{}{Was brauchst du?}
{363}{}{Bringst du mir jetzt das Kundschaften bei?}
{364}{}{Ja. Du hast Wissen verdient. Du wirst es für Gutes nutzen.}
{365}{}{Toll! Fangen wir an.}
{366}{}{Ich komme später wieder. Im Moment habe ich zu tun.}

{367}{}{Kannst du mir jetzt etwas über Kundschaften beibringen?}
{368}{}{Nach allem, was ich für dich getan habe!}

{369}{}{Du lernst, in der Wildnis zu überleben. Du hast +3 auf deine Wildnisleben-Fertigkeit erhalten.}
{370}{}{Du lernst, in der Wildnis zu überleben. Du hast +5 auf deine Wildnisleben-Fertigkeit erhalten.}

##########################################################
#
#       Ñîñòÿçàíèå
#
##########################################################

#Äèàëîã äëÿ ñîñòÿçàíèÿ:

{371}{}{Na schön, Bleichgesicht. Wie du willst.}
{372}{}{Gib mir etwas Zeit. Ich komme später zurück, um zu kämpfen.}
{373}{}{Fangen wir an!}
{374}{}{Nein, Bleichgesicht. Kämpfen nur ehrenhaft, wenn Kämpfer gleich stark. Du stark nur wie Kinder.}
{375}{}{Such keine Ausreden. Du bist einfach zu feige, um gegen mich zu kämpfen!}
{376}{}{Warte, bis ich wieder zu Kräften gekommen bin.}
{377}{}{Guter Krieger nicht nur stark. Guter Krieger geduldig.}
{378}{}{Wie auch immer.}
{379}{}{So sei es. Geh in den Kreis. Tritt hinaus – verloren. Bitte um Gnade – verloren. Leg Sachen in Truhe, dann beginnen wir.}
{380}{}{Los geht's.}

#Ïëàâàşùèå ôğàçû ïğè ñîñòÿçàíèè

{381}{}{Krieger tritt aus Kreis, verloren!}
{382}{}{Ich habe verloren!}
{383}{}{Ich habe gewonnen!}
{384}{}{Unentschieden!}

{385}{}{Du großer Schwächling. Du willst kämpfen – du verrückt. Hoffe, Schmerz bringt dir neue Weisheit.}
{386}{}{Du sehr stark! Du gewinnst. Danke, Fremder.}
{387}{}{Unentschieden! Große Überraschung! Danke, Fremder.}
{388}{}{Na schön, ruhen wir uns aus.}

{392}{}{Nein, Bleichgesicht. Du fremd, ich fremd. Kein Kampf.}
{393}{}{Du vertraust mir nicht? Na schön ...}
{394}{}{Vielleicht später dann.}

##########################################################
#
#       Ğàäèîñòàíöèÿ
#
##########################################################

{400}{}{[Er kratzt sich am Kopf und runzelt die Stirn] Hmm ... Seltsame Worte. Ray-dee-oh?}
{401}{}{Erzähl mir keinen Scheiß. Du verstehst mich bestens. Sag mir jetzt, wo es ist!}
{402}{}{Es müsste wie ein altes Haus aus der Zeit vor dem Krieg aussehen. Oben drauf ist eine große Schüssel.}
{403}{}{Dann finde ich es eben ohne dich.}

{404}{}{NEIN!!! Heiliger Ort! Fremde verboten!}
{405}{}{Sag es mir, du Abschaum, oder ich begrabe das ganze Dorf!}
{406}{}{Auch mich? Ich habe doch bewiesen, dass du mir vertrauen kannst, oder?}
{407}{}{[Er seufzt] Heiliger Ort ... Ich nicht entscheiden. Häuptling fragen.}
{408}{}{Dann gehe ich mit Ogima reden.}

{409}{}{Du machen mir keine Angst! Ich Bärentatze! Verschwinde!}
{410}{}{Na, sieh dich an. Ganz schön hart.}

{411}{}{Gut. Wir gehen, Bleichgesicht.}
{412}{}{[Folge ihm.]}
{413}{}{Warte, ich muss erst noch etwas erledigen.}

#Female character
{1300}{}{Halt, Bleichgesicht! Ich – Makozid Bärentatze, Wächter der Cheyenne. Ich beobachte dich. Du erledigst deine Geschäfte schnell. Dann gehst du.}
{1307}{}{Gutes Gespräch, Bleichgesicht.}
{1320}{}{Bleichgesicht!}
{1321}{}{Bleichgesicht!... Hm. Deine Augen ... Augen der Kinder des Verschlingers.}
{1350}{}{Nein, Bleichgesicht. Ich nicht lehren. Such Lehrer im Lager.}
{1352}{}{Nein, Bleichgesicht. Du Fremder. Fremder gefährlich. Cheyenne helfen gefährlichem Fremden nicht.}
{1354}{}{Ja, Bleichgesicht, du loyal. Aber tu Gefallen, bevor ich lehre.}
{1364}{}{Ja. Du hast Wissen verdient. Du wirst es für Gutes nutzen.}
{1368}{}{Nach allem, was ich für dich getan habe!}
{1371}{}{Gut, Bleichgesicht. Du bekommst deinen Willen.}
{1374}{}{Nein, Bleichgesicht. Kämpfen ist nur ehrenhaft, wenn die Kämpfer ebenbürtig sind. Deine Stärke reicht gerade für Kinder.}
{1385}{}{Du großer Schwächling. Du willst kämpfen – du verrückt. Hoffe, Schmerz bringt dir neue Weisheit.}
{1392}{}{Nein, Bleichgesicht. Du fremd, ich fremd. Kein Kampf.}
{1406}{}{Auch mich? Ich habe doch bewiesen, dass du mir vertrauen kannst, oder?}
{1411}{}{Gut. Wir gehen, Bleichgesicht.}
