{100}{}{Du siehst Niskigvan mit den zerzausten Federn.}
{101}{}{Du siehst einen gebräunten, mittelalten amerikanischen Ureinwohner mit einem abwesenden Blick.}

#Ïëàâàşùèå ñîîáùåíèÿ
{110}{}{Das war jetzt wirklich unnötig ... }
{111}{}{Tut mir leid, vielleicht später ... }

#########################################################
#
#           The tale about mouse
#
#########################################################

{112}{}{Also gut, Kinder, hört zu. Es war einmal eine kleine Maus.}
{113}{}{Sie war die jüngste unter all ihren Geschwistern.}
{114}{}{Eines Tages hörte sie ein Geräusch, das sie noch nie zuvor gehört hatte. „Was war das für ein Geräusch?“, fragte sie.}
{115}{}{„Welches Geräusch?“, antworteten die anderen Mäuse. „Kümmere dich um deinen eigenen Garten. Da ist kein Geräusch.“}
{116}{}{Doch diese Maus war neugierig. Also machte sie sich auf den Weg, um mehr über das Geräusch herauszufinden.}
{117}{}{Sie traf einen Frosch. Der Frosch sagte: „Dieses Geräusch stammt von einem Großen Fluss. Ich bringe dich hin.“}
{118}{}{Und gemeinsam machten sie sich auf den Weg zum Großen Fluss. Dort sagte der Frosch ...}
{119}{}{„Wenn du so hoch springst, wie du kannst, wirst du die Großen Berge sehen!“}
{120}{}{Und das tat die Maus. Sie sprang so hoch, dass sie in der Ferne die Großen Berge sah.}
{121}{}{Da wurde der Maus klar, dass sie sich nicht ausruhen könnte, bevor sie die Berge aus der Nähe gesehen hatte.}
{122}{}{Also reiste die Maus durch die Great Plains zu den Großen Bergen.}
{123}{}{Plötzlich sah sie einen Bison in der Ebene liegen. Er war stark und mächtig.}
{124}{}{„Oh, mächtiger Bison!“, sagte die Maus. „Bitte bring mich zu den Großen Bergen!“}
{125}{}{„Aber ich kann nicht“, sagte der Bison. „Ich sterbe. Nur ein Mäuseauge kann mich retten.“}
{126}{}{„Ein Mäuseauge?“, fragte die Maus. „Hier, nimm meins!“}
{127}{}{Der Bison nahm das Geschenk an und kam wieder zu Kräften. Dann brachte er die Maus zu den Großen Bergen.}
{128}{}{Am Fuß der Großen Berge sah die Maus einen Wolf, der sich im Gebüsch versteckte. Regungslos, still und in sich gekehrt.}
{129}{}{„O mächtiger Wolf!“, sagte die Maus. „Bitte hilf mir, diese Großen Berge zu erklimmen!“ Doch der Wolf antwortete nicht.}
{130}{}{Die Maus erkannte, dass auch der Wolf im Sterben lag. Also gab sie ihm ihr anderes Auge.}
{131}{}{Der Wolf kam wieder zu Kräften und brachte die Maus bis ins Herz der Großen Berge.}
{132}{}{Nun stand die kleine Maus ganz allein im Herzen der Großen Berge und konnte ihre Schönheit nicht einmal für einen Augenblick bewundern.}
{133}{}{Also begann sie, sich alles vorzustellen ... Die Erde ... Das Wasser ... So verschwommen, so fern ...}
{134}{}{Und sie hörte, wie jemand sie rief: „Hallo, Bruder! Wir freuen uns so, dich in unserem Schwarm zu haben. Flieg mit uns. Flieg mit uns, Bruder Adler!“}
{135}{}{Na, Kinder? Hat euch die Geschichte gefallen? Wenn ihr brav seid, erzähle ich euch später noch eine ...}

#########################################################
#
#                 Íà÷àëî äèàëîãà
#
#########################################################

{200}{}{Was brauchst du, Fremder?}
{201}{}{Ich muss mich heilen lassen.}
{202}{}{Ich brauche Medizin.}
{203}{}{Glaubst du wirklich, dass dein Heilzeug funktioniert? Ist das dein Ernst?}
{204}{}{Entschuldigung, was machst du da?}
{205}{}{Ich habe deinen verlorenen Rucksack gefunden.}

{206}{}{Nichts.}
{207}{}{Weißt du, wo der Radiosender ist?}

#########################################################
#
#                    Ëå÷åíèå ãåğîÿ
#
#########################################################

{250}{}{Mal sehen. [Er untersucht dich und murmelt vor sich hin.] Ja, ja ... Ich kann dich heilen.}
{251}{}{Mal sehen. [Er untersucht dich und murmelt vor sich hin.] Ja, ja ... Ich kann dich heilen, aber du musst mir 100 Dollar zahlen.}
{252}{}{Heil mich!}
{253}{}{Hier ist das Geld. Und jetzt heil mich!}
{254}{}{Aber so viel Geld habe ich nicht. Willst du mich wirklich einfach leiden lassen?}
{255}{}{Schon gut. Das heilt von allein. Bis dahin habe ich noch andere Fragen.}
{256}{}{Eigentlich brauche ich doch nichts mehr.}

{257}{}{Ich bin der Heiler meines Stammes. Das sagt alles.}
{258}{}{Ich bitte nicht, ich befehle es! Heile mich, sonst ...!}
{259}{}{Na gut, hier ist das Geld! Heil mich einfach!}
{260}{}{Siehst du die Ironie, Fremder? Der Räuber kam früher nach Niskigvan, um ihn zu verspotten. Jetzt fleht der Räuber Niskigvan um Gnade an.}
{261}{}{Halt die Klappe und heil mich!}
{262}{}{Interessanter Gedanke ... Ich werde darüber nachdenken.}
{263}{}{Du bist bereit, Niskigvans Körper zu verletzen, damit er deinen heilt? [Er schüttelt den Kopf] Weisheit hat dich zum Narren gemacht, Fremder.}
{264}{}{Na gut, hier sind 100 Dollar! Heil mich endlich!}
{265}{}{Zum Teufel damit. Ich kümmere mich selbst darum. Danke für nichts.}
{266}{}{Niskigvan hat alles getan, was er konnte.}
{267}{}{Der Räuber kam früher nach Niskigvan, um ihn zu verspotten. Jetzt bittet er ihn um einen Gefallen. Nein, Fremder. Such Hilfe bei deinem eigenen Volk.}
{268}{}{Das werde ich nicht vergessen, alter Mann!}
{269}{}{Na gut, ich frage mein Volk im Lager.}

#########################################################
#
#          Ïğîèçâîäñòâî ìåäèêàìåíòîâ è
#          ïîëó÷åíèå äîñòèæåíèÿ "Çíàõàğü"
#
#########################################################

#Ïğîèçâîäñòâî
{300}{}{Wir können unser Weniges nicht mit dir teilen, Fremder. Aber ich kann dir Medizin mischen, wenn du mir die Zutaten bringst.}
{301}{}{Was brauchst du, um Heilsalbe herzustellen?}
{302}{}{Was brauchst du, um ein Gegengift herzustellen?}
{303}{}{Ich habe noch eine Frage.}
{304}{}{Das wäre alles.}

{305}{}{Mach eine.}
{306}{}{Mach zwei.}
{307}{}{Mach drei.}
{308}{}{Mach fünf.}
{309}{}{Mach zehn.}

{310}{}{Eine Xanderwurzel, eine Broc-Blume und 25 Dollar.}
{311}{}{Den Schwanz eines Radskorpions und 25 Dollar.}

{312}{}{Erledigt.}
{313}{}{Ich habe noch eine Frage.}
{314}{}{Das war's.}

{315}{}{Kannst du Medizin gegen eine Infektion herstellen?}
{316}{}{[Er hebt die Augenbrauen] Das ist eine komplizierte Aufgabe, Fremder. Ich brauche eine Xanderwurzel, eine Broc-Blume, zwei Bündel Nachtschattenbeeren und 250 Dollar.}

#Äîñòèæåíèå Çíàõàğü
{350}{}{Ich werde nie vergessen, was du für Makkon getan hast. Keine Belohnung wäre genug, aber es wäre mir eine Ehre, dich alles zu lehren, was ich weiß.}
{351}{}{Du hast so viel für unseren Stamm getan. Es wäre mir eine Ehre, dich alles zu lehren, was ich weiß. Möge es dir auf deiner Reise helfen.}
{352}{}{Kannst du mir beibringen, wie man Kräutermedizin herstellt?}
{353}{}{Natürlich. Du wirst die Dienste von Heilern nicht länger benötigen und kannst die Gaben der Natur selbst nutzen.}
{354}{}{Großartig! Lehr mich, oh großer Heiler!}
{355}{}{Ich habe gerade keine Zeit. Können wir das später machen?}
{356}{}{Wenn du bereit bist, komm hierher zurück, dann werde ich dich unterrichten.}
{357}{}{Eigentlich kann ich mir etwas Zeit nehmen. Lehr mich, oh großer Heiler!}
{358}{}{Ich komme wieder.}

#########################################################
#
#          Ğàññïğîñû î ğàäèîñòàíöèè
#
#########################################################

{360}{}{Radio? ... Nein, ich weiß nichts davon.}
{361}{}{Du lügst! Bring mich hin! Sofort!}
{362}{}{Dann eine andere Frage.}
{363}{}{Na gut. Ich komme wieder.}

{364}{}{Du bist im Land unserer Vorfahren, in meinem Haus ... Und du wagst es, mich zu bedrohen! Möge der Zorn des Herrschers des Lebens über dich kommen!}
{365}{}{Wie du willst. Ich gehe deine Dorfbewohner einen nach dem anderen durch, bis mir jemand zeigt, wo es ist. Dann werden genug Leute da sein, die deinem „Heilort“ den gebührenden Respekt erweisen.}
{366}{}{He, he, tut mir leid. Ich war etwas zu aufgeregt. Aber du weißt wirklich nicht, ob es hier in der Nähe einen Radiosender gibt?}
{367}{}{Das ist sinnlos. Ich gehe.}

{368}{}{Nein.}
{369}{}{Na gut.}
{370}{}{Nein, warte! Ich bringe dich zum Radiosender. Tu nur niemandem etwas!}
{371}{}{Jetzt kommen wir der Sache näher! Los, alter Mann.}

#########################################################
#
#          Ğàññïğîñû î âğà÷åáíîì îïûòå
#
#########################################################

#Îáìåí âğà÷åáíûì îïûòîì
{400}{}{Ja. Der Herrscher des Lebens versorgt uns mit Nahrung und Wasser. Wenn wir im Einklang mit unserer Umwelt leben und uns der Gaben bewusst sind, die wir erhalten, haben wir alles, was wir zum Überleben brauchen.}
{401}{}{Mit Kräutern und Wasser kannst du unmöglich fortgeschrittene Krankheiten und Verletzungen behandeln.}
{402}{}{Könntest du mehr tun, wenn du bessere Werkzeuge hättest?}
{403}{}{Verstehe. Ich möchte noch etwas fragen.}
{404}{}{Das war alles, was ich wissen wollte.}

{405}{}{Ich erwarte nicht, dass ein Stadtmensch wie du das versteht. Wir Cheyenne leben schon seit vielen Jahren auf diese Weise, ob du es nun glauben willst oder nicht.}
{406}{}{Hm. Welche Gaben hält die Natur denn bereit?}
{407}{}{Welche Methoden wendet ihr an?}
{408}{}{Und funktioniert das?}
{409}{}{Und wie gesund sind die Cheyenne?}
{410}{}{Warum verwendet ihr keine Medizin aus der Vorkriegszeit?}

{411}{}{Wir verwenden Wurzeln, Kräuter, Pilze und Mäusekot.}
{412}{}{Welche Wurzeln?}
{413}{}{Was für Kräuter?}
{414}{}{Pilze?}
{415}{}{Mäusekot?! Das ist doch ein Scherz!}
{416}{}{Wie kann all das bei der Heilung helfen?}
{417}{}{Ich habe noch andere Fragen.}

{418}{}{Viele Wurzeln, besonders Xanderwurzel, kann man rauchen, auf die Haut reiben oder als Tee trinken.}
{419}{}{Wie helfen sie?}
{420}{}{Was verwendet ihr sonst noch?}

{421}{}{Unser magisches Heilpulver schmeckt bitter, ist aber für die bösen Geister giftig, die im Körper Wurzeln schlagen.}
{422}{}{Du meinst, es hat antimikrobielle Eigenschaften? Na gut, was ist mit eurer anderen Medizin?}
{423}{}{Das merke ich mir. Was verwendet ihr sonst noch?}

{424}{}{Broc-Blüten und andere Pflanzen.}
{425}{}{Der scharfe, doch wundersame Geschmack des Tranks vertreibt die Hitze aus dem Körper und beschleunigt seine Genesung.}
{426}{}{Du meinst, er kann Fieber senken? Es klingt, als hätten diese Pflanzen antibiotische Eigenschaften. Was ist mit eurer anderen Medizin?}

{427}{}{Pilze, die sich in den dunklen Winkeln des Ödlands vor den Augen der Suchenden verstecken.}
{428}{}{Pilze, die im Dunkeln leuchten, weisen den Weg zur Heilung. Sie geleiten den Geist durch seine Prüfungen und lindern so das Leiden des Körpers.}
{429}{}{Es klingt, als hätten sie halluzinogene und schmerzlindernde Eigenschaften. Erzähl mir von eurer anderen Medizin.}

{430}{}{Ich mache mich niemals über die Gaben der Himmlischen Mutter lustig, Fremder. Dieser Mäusekot enthält die Lebensenergie der Erde selbst.}
{431}{}{Nicht jeder Mäusekot kann heilen. Nur jene Mäuse, die in Höhlen leben und noch nie draußen waren, sind von der Himmlischen Mutter gesegnet und können den Heilungsprozess des Körpers unterstützen.}
{432}{}{Hm ... Es klingt, als wäre etwas Besonderes an der Nahrung der Höhlenmäuse. Ich nehme an, ihr Kot enthält Mineralien, die den Stoffwechsel anregen. Na gut, was ist mit eurer anderen Medizin?}
{433}{}{Nur jene, die von der Himmlischen Mutter begnadet sind, können aus diesen Zutaten Medizin herstellen. Alle anderen sind dazu verdammt, Gift zu trinken.}
{434}{}{Richtig. Erzähl mir noch einmal von diesen Zutaten.}
{440}{}{Das Heilungsritual ist nie dasselbe. Manchmal reicht jemandem ein Tee aus Kräutern und Wurzeln, um wieder gesund zu werden. Ein anderes Mal muss ich mit allem, was die Himmlische Mutter mir gegeben hat, um ein Leben kämpfen – mit Pfeifen, Zaubern, Tränken und natürlich dem Geschick meiner Hände.}
{441}{}{Verstehe.}
{442}{}{Jede Heilung ist auf ihre Weise ein Kampf. Deshalb geht sie oft mit Schmerzen und Schreien einher ... Doch mit Mut und Beharrlichkeit werden selbst die stärksten bösen Geister den Körper verlassen.}
{443}{}{Stimmt.}
{444}{}{Wir sind stark, selbst im Alter. Fremde werden von den Geistern, die in ihnen hausen, zugrunde gerichtet und geschwächt. Das Volk der Cheyenne wird alle anderen im Ödland überleben.}
{445}{}{Wenn du meinst.}
{446}{}{Die Menschheit hat alles vergessen, was die Himmlische Mutter ihr vermacht hat. Die Heiler, die vor dem Tag des Jüngsten Gerichts Heilmittel herstellten, erweckten nur den Anschein einer Heilung. Doch die bösen Geister wurden immer nur durch andere ersetzt – oft durch noch stärkere.}
{447}{}{Verstehe.}
{448}{}{Das stimmt nicht. Vor dem Krieg gab es verschiedene Behandlungsmethoden. Einige davon könnten dir nützlich sein.}
{449}{}{Die Medizin der Fremden hat uns nie geholfen. Ich sollte mich nicht erneut davon überzeugen lassen.}
{450}{}{Hm. Wenn ich mehr über Arzneimittelkunde wüsste, könnte ich versuchen, dich zu überzeugen. Vielleicht ein andermal.}
{451}{}{Ich bin Experte auf dem Gebiet der Medizin. Ich könnte es dir erklären, wenn du bereit bist, im Gegenzug dein Wissen mit mir zu teilen.}

{452}{}{Hm ... [er betrachtet dich neugierig] Die Himmlische Mutter hat uns stets gelehrt, nach neuem Wissen zu streben.}
{453}{}{Wollen wir es uns gemütlich machen?}
{454}{}{Natürlich. Ich teile mein Wissen gern mit dir.}
{455}{}{Dann legen wir los!}
{456}{}{Jetzt nicht.}

{457}{}{Der Austausch medizinischer Techniken mit Niskigvan hat deinen Erste-Hilfe-Wert um 5% erhöht.}

#########################################################
#
#          Ïğèíàäëåæíîñòè ëåêàğÿ
#
#########################################################

{460}{}{Es ist so schwer, mein Handwerk nur mit Messern und Löffeln auszuüben!}
{461}{}{Die fruchtbare Erde gibt uns alles, was wir brauchen, wenn wir nur weise genug sind, es zu erkennen.}
{462}{}{Wir haben alles, was wir brauchen. Nochmals vielen Dank.}

{463}{}{Was ist passiert?}
{464}{}{Das tut mir leid zu hören. Lass uns über etwas anderes reden.}
{465}{}{Dann lasse ich dich lieber weiterarbeiten. Auf Wiedersehen.}

{466}{}{Gern geschehen. Kannst du noch ein paar Fragen beantworten?}
{467}{}{Kein Problem. Bis später.}
{468}{}{Stimmt.}

{469}{}{Ohne meinen Rucksack ist es schwer, Kräuter und Wurzeln zu sammeln. Auch alle meine Instrumente waren darin.}
{470}{}{Was ist passiert?}
{471}{}{Lass uns über etwas anderes reden.}
{472}{}{Ich will dich nicht dazu bringen, dich damit aufzuhalten. Ich lasse dich in Ruhe.}

{473}{}{Einer der Raider hat ihn mitgenommen, als ich nicht im Dorf war. Es wird lange dauern, bis wir genug Leder für einen neuen entbehren können ... Und um meine Werkzeuge zu ersetzen, brauchen wir noch mehr. Heilen wird eine Zeit lang schwierig sein.}
{474}{}{Was, wenn ich dir deinen Rucksack zurückhole?}
{475}{}{[Er sieht dich unsicher an] Das sind gefährliche Männer, Fremder. Sich ihnen zu nähern, ist ein tödliches Risiko, es sei denn, du bist einer von ihnen.}
{476}{}{Mach dir um mich keine Sorgen. Du wärst überrascht, wie oft ich tödliche Risiken eingehe.}
{477}{}{Schon gut.}
{478}{}{Falls du auf eine Belohnung hoffst: Ich habe kaum etwas, das ich dir geben könnte. Noch weniger, das einen Fremden wie dich interessieren dürfte.}
{479}{}{Na ja, ich will trotzdem helfen. Vielleicht ändert das deine Sicht auf Fremde.}
{480}{}{Ich bin keine Wohltätigkeitsorganisation. Vergiss es.}
{481}{}{Dann wäre ich dir für deine Güte sehr dankbar.}
{482}{}{Weißt du, wo ich diesen Raider finden kann?}
{483}{}{In Ordnung, aber zuerst habe ich noch ein paar Fragen.}
{484}{}{Ich komme mit deinen Sachen zurück.}

{485}{}{Das Versteck der Raider ist nicht weit von hier – im Norden. Derjenige, der meinen Rucksack genommen hat, nennt sich Diesel.}
{486}{}{Zweifellos hat dich der Herrscher des Lebens geschickt! Danke, Fremder! So viel Großzügigkeit ist in unserer Zeit selten ... Selten und kostbar. Solange du lebst, werde ich deine Verletzungen kostenlos behandeln.}
{487}{}{Das ist großartig, aber so viel Großzügigkeit macht ganz schön hungrig ...}
{488}{}{Ach, das war doch nichts. Gern geschehen.}

{490}{}{Natürlich! Warte hier. Ich hole dir ein paar Sandwiches aus Omakaki.}
{491}{}{[Warten]}

#########################################################
#
#          Ïîñëå îòêàçà â ëå÷åíèè Ìàêîíñà
#
#########################################################

{500}{}{Der Häuptling hat mir verboten, Makkon zu behandeln!}
{501}{}{Ogimas Wort ist endgültig.}
{502}{}{Ogimas Wort ist endgültig. Ich werde nicht gegen ihn handeln.}
{503}{}{Aber was sollen wir jetzt tun?!}

{504}{}{Es ist vorbei, Fremder. Vergiss es und geh in Frieden.}
{505}{}{Meinst du das ernst?! Einfach weggehen?}
{506}{}{Na gut, ich gehe. Aber das wirst du bereuen!}

{507}{}{[Er beugt sich vor und schaut dir in die Augen] Ist das Herz des Fremden so schwer vor Kummer wie meines?}
{508}{}{Ja!}
{509}{}{Und er will nur helfen, ohne eine Gegenleistung zu verlangen?}
{510}{}{Natürlich!}

{511}{}{[Er seufzt] Der Häuptling hat recht, Fremder. In deinem Herzen ist zu viel Dunkelheit, als dass ich dir Makkons Leben anvertrauen könnte.}
{512}{}{[Geh.]}
{513}{}{[Er seufzt lange und bekümmert] Häuptling Ogima ... Er ist weise, aber auch nur ein Mensch. Selbst er kann sich manchmal irren ... Und ich weiß mehr über Heilkunst als er.}
{514}{}{Genau! Was kann ich tun, damit du mir vertraust?}
{515}{}{Zu oft behaupten Fremde, Fähigkeiten zu besitzen, die sie gar nicht haben. Erst letzten Monat kam ein Mann aus dem Osten. Er versprach uns Regen, konnte uns aber nur die Wolken zeigen.}
{516}{}{Willst du mein Wissen auf die Probe stellen?}

{517}{}{Hast du es dir anders überlegt und willst meine Heilkunst doch auf die Probe stellen?}
{518}{}{Häuptling Ogima hat mir verboten, Makkon zu behandeln.}

#########################################################
#
#          Ïåğåä ëå÷åíèåì Ìàêîíñà
#
#########################################################

{550}{}{Was ist mit dem Jungen in der Ecke passiert?}

{551}{}{Der arme Makkon. Bei einem Erdrutsch wurden seine Beine zerquetscht. Schon lange versuche ich, ihn zu heilen. Er hat ständig Schmerzen und sein Fieber hält schon seit drei Monaten an. Selbst die Gaben der Himmlischen Mutter können keine Wunder vollbringen. Ich will noch nicht aufgeben, aber ich fürchte, dass er bald sterben könnte. Das ganze Dorf trauert um ihn.}
{552}{}{Wenn deine, äh, Mutter nicht gut genug ist, kann vielleicht fortschrittlichere Medizin ihn retten. Kann ich helfen?}
{553}{}{Ich hoffe, alles wird gut. Bis dann.}
{554}{}{Hmm ... [er runzelt die Stirn] Sprich mit Ogima. Ich kann diese Entscheidung nicht treffen. Ich stehe diesem Jungen zu nahe und kann nicht zulassen, dass mein Herz statt meines Kopfes denkt.}
{555}{}{Ich rede mit ihm. Aber zuerst – noch eine Frage.}
{556}{}{Dann gehe ich mit ihm reden.}

{557}{}{Ich würde dir gern dabei helfen, den verletzten Jungen zu behandeln. Dein Häuptling hat es mir erlaubt.}

{558}{}{Das meinst du ernst? Du willst helfen?! Das ist heutzutage eine Seltenheit. [er hält inne, dann zieht er die Brauen zusammen] Ich wäre froh, wenn du den Jungen heilen könntest, aber selbst meine Fähigkeiten reichen hier nicht aus ... Bist du sicher, dass du damit zurechtkommst?}
{559}{}{Ja, ganz sicher.}
{560}{}{Dann würde ich gern zuerst deine Fähigkeiten prüfen. Ich habe dich noch nie arbeiten sehen. Sollen wir anfangen?}
{561}{}{Kein Problem. Legen wir los.}
{562}{}{Ich bin gerade etwas müde. Vielleicht später?}

#########################################################
#
#          Òåñò ãåğîÿ ïåğåä ëå÷åíèåì Ìàêîíñà
#
#########################################################

{600}{}{Stellen wir deine Fähigkeiten auf die Probe, Fremder. [er richtet sich auf und blickt dir scharf in die Augen] Ich werde Fragen stellen, du wirst sie beantworten.}
{601}{}{Ich bin bereit.}
{602}{}{[Er schiebt seine Robe zur Seite und zeigt eine Narbe links und etwas unterhalb seines Nabels] Als ich hier angeschossen wurde, was hat die Kugel getroffen?}
{603}{}{Deine Lunge.}
{604}{}{Deinen Dickdarm.}
{605}{}{Deine Blase.}
{606}{}{Deinen Dünndarm.}
{607}{}{Deinen Penis.}

{610}{}{Hmm. Und warum war die Verletzung nicht tödlich?}
{611}{}{Alle deine Knochen blieben unversehrt.}
{612}{}{Dein zentrales Nervensystem wurde nicht beeinträchtigt.}
{613}{}{Dein Bauch enthält viel Wasser. Es hat die Kugel aufgehalten.}
{614}{}{Die Hitze der Kugel hat die Wunde verödet.}
{615}{}{Sie hat keine lebenswichtigen Organe getroffen.}

{620}{}{Hmm. Und wozu dient der Dünndarm im Körper?}
{621}{}{Er verarbeitet das Blut.}
{622}{}{Er speichert Urin.}
{623}{}{Er speichert Kot.}
{624}{}{Er entzieht der Nahrung das Wasser.}
{625}{}{Es verdaut Nahrung.}

{630}{}{Hmm. Und wie lange dauert es, bis eine solche Verletzung verheilt?}
{631}{}{Ein paar Stunden.}
{632}{}{Ein paar Tage.}
{633}{}{Ein paar Wochen.}
{634}{}{Ein Jahr.}

{640}{}{Hmm. Wie behandelt man diese Verletzung, damit sich eine Schusswunde nicht entzündet?}
{641}{}{Spül sie mit Wasser aus dem Brunnen aus.}
{642}{}{Spül sie mit Alkohol aus, zum Beispiel mit Schnaps.}
{643}{}{Brenn sie mit Feuer oder erhitztem Metall aus.}
{644}{}{Leck sie ab.}
{645}{}{Gar nicht, die Hitze der Kugel hat die Wunde bereits kauterisiert.}

{650}{}{Hmm. Manche Kräuter helfen dem Körper, verletztes Gewebe schnell wiederherzustellen, aber sie alle haben eine Nebenwirkung. Welche Nebenwirkung hat Pulver aus Xanderwurzeln und Brocblüten?}
{651}{}{Es schwächt deine Stärke.}
{652}{}{Es verringert deine Ausdauer.}
{653}{}{Es trübt deine Wahrnehmung.}
{654}{}{Es verlangsamt deine Beweglichkeit.}
{655}{}{Es besteht Suchtgefahr.}

{660}{}{Hmm. Manche Vorkriegsmedizin macht stark abhängig. Wenn ein Abhängiger sie nicht regelmäßig bekommt, leidet er. Kann man diese Abhängigkeit behandeln?}
{661}{}{Ja. Wenn du lange genug keine weitere Dosis nimmst, klingt die Abhängigkeit irgendwann ab.}
{662}{}{Ja. Eine andere Art von Medizin kann die Abhängigkeit beseitigen.}
{663}{}{Ja. Ein Reinigungsritual mit besonderem Rauch beseitigt das Verlangen.}
{664}{}{Nein. Die Last bleibt für immer.}

{665}{}{Und jetzt?}
{666}{}{[Weiter]}

#Îöåíêà çíàíèé (òåîğåòè÷åñêàÿ ïîäãîòîâêà)
{667}{}{Das wäre alles. [er lächelt und seine Augen glänzen vor Aufregung] Dein Wissen über Heilkunst ist unglaublich, Fremder! Vielleicht solltest du mich prüfen! Ich glaube, gemeinsam haben wir genug Wissen, um Makkon zu behandeln.}
{668}{}{Das wäre alles. [er lächelt] Du weißt viel über Heilkunst, Fremder. Ich weiß, dass ich dir vertrauen kann.}
{669}{}{Das wäre alles. [er runzelt die Stirn] Makkons Zustand ist sehr kompliziert, Fremder, und ich glaube nicht, dass du genug weißt, um ihn richtig zu behandeln. Aber vielleicht hast du Fähigkeiten auf anderen Gebieten.}
{670}{}{[Er wirft die Hände hoch] Es hat keinen Sinn, das fortzusetzen. Du weißt überhaupt nichts! Wie kannst du dich Heiler nennen? Ich kann es nicht riskieren, dich Makkon behandeln zu lassen. Ich ... ich verbiete es!}
{671}{}{[Er verschränkt die Arme] Die Erfahrung hat mich gelehrt, dass Wissen allein nicht genügt. Omakaki war einst meine Helferin, und obwohl sie viel über Kräuter, Wurzeln und Pflanzen lernte, konnte sie keinen einfachen Trank herstellen. Zeig mir an dieser Attrappe, was du kannst, damit ich es in der Praxis sehen kann.}
{672}{}{Manchmal nimmt der Herrscher des Lebens jemandem die Fähigkeiten auf einem Gebiet, gewährt ihm dafür aber etwas anderes. Gekek hatte einen Bruder, der einen Leguan nicht von einem Gecko unterscheiden konnte, aber einen Speer aus fünfzig Schritten Entfernung mitten ins Auge werfen konnte. Zeig mir an dieser Attrappe, was du kannst, damit ich es in der Praxis sehen kann.}

{673}{}{Niskigvan beurteilte deine medizinischen Fähigkeiten, indem er dich bei der Arbeit an der Attrappe beobachtete.}
{674}{}{Nun prüfe ich, wie geschickt deine Hände sind. Du brauchst flinke Finger, um mit weichem und verletztem Gewebe zu arbeiten. Hier sind ein Gecko-Leder und eine Nadel. Stich die Nadel durch die Punkte, die ich für dich aufgezeichnet habe.}
{675}{}{[Niskigvan beurteilt sorgfältig Tempo, Genauigkeit, Vorsicht und Qualität deiner Nadelarbeit] Hmm. Nun prüfe ich, wie scharf deine Augen sind. Hier sind zwei Gläser. In einem ist Wasser aus unserem Brunnen, das Wasser im anderen ist sorgfältig gereinigt. Sag mir, welches Wasser reiner ist.}
{676}{}{[Auswählen]}
{677}{}{Hmm. Nun prüfe ich die Ausdauer deines Herzens. Die Operation kann mehrere Stunden dauern und wird anstrengend sein. Mach ein paar Sit-ups, dann prüfe ich, wie schnell dein Herz schlägt.}
{678}{}{Gut, machen wir's. [beginnt mit Sit-ups]}

#Îöåíêà óìåíèé è ñïîñîáíîñòåé (ïğàêòè÷åñêàÿ ïîäãîòîâêà)
{679}{}{[Nach ein paar Minuten packt Niskigvan dein Handgelenk und misst deinen Puls] Hmm ... Du bist erstaunlich fit und talentiert, Fremder! Der alte Mann wird glatt neidisch!}
{680}{}{[Nach ein paar Minuten packt Niskigvan dein Handgelenk und misst deinen Puls] Hmm ... Ja, das sollte reichen. Du bist stark und geschickt genug für diese Operation, Fremder.}
{681}{}{[Nach ein paar Minuten packt Niskigvan dein Handgelenk und misst deinen Puls] Hmm ... Ich bin mir nicht sicher, ob du genug Kraft für diese Operation hast, Fremder. Ich weiß nicht, ob wir beide zusammen es schaffen.}
{682}{}{[Nach ein paar Minuten schüttelt Niskigvan den Kopf] Schluss. Dein guter Geist kann die Schwäche deines Körpers nicht wettmachen, Fremder. Wenn ich dich diese Operation durchführen lasse, wirst du den Jungen töten, vielleicht sogar dich selbst! Es tut mir leid, aber ... ich muss dir verbieten, Makkon zu behandeln.}
{683}{}{Endlich der letzte Test. Ich habe hier eine Hausmaus. Sie ist sehr empfindlich und kann leicht zwischen Unreinem und Reinem unterscheiden. Ich lege dir etwas Saat in die Hände. Mal sehen, ob sie davon frisst.}

{684}{}{[Die Maus läuft davon, ohne auch nur zu versuchen, das Futter aus deinen Händen zu fressen] Hmm ... Ich glaube, in dir stecken böse Geister. Gift, Krankheit oder etwas noch Dunkleres. Wie dem auch sei, ich bin bereit, meine Entscheidung zu treffen.}
{685}{}{[Die Maus beschnuppert vorsichtig die Saat in deinen Händen und beginnt dann zu fressen] Ein Tier lässt sich nicht täuschen! Ich bin bereit, meine Entscheidung zu treffen!}

#Èòîãîâàÿ îöåíêà (ïî ñóììå òåîğèè/ïğàêòèêè è ñ ó÷åòîì ïğîâåğêè ìûøüş)
{686}{}{Ich hatte keine Ahnung, dass die Himmlische Mutter den Menschen aus der Stadt solche Gaben verliehen hat! Es wird mir eine Ehre sein, dir bei der Operation zu helfen.}
{687}{}{Gut gemacht, Fremder! Jetzt habe ich keine Zweifel mehr. Gemeinsam sollten wir Makkon heilen können.}
{688}{}{Ich glaube, ich kann dir vertrauen, Fremder. Du kannst mir bei der Operation helfen.}
{689}{}{Du bist ein großartiger Heiler, Fremder! Es wird mir eine Ehre sein, dich bei der Operation an meiner Seite zu haben! Aber sei vorsichtig – Tiere wissen Dinge, die Menschen nicht wissen. Wenn böse Geister in dir stecken, lass sie nicht zu stark werden, sonst endet es böse für dich.}
{690}{}{Gut gemacht, Fremder. Schade, dass die Maus Unreinheit an deinen Händen gerochen hat, aber ich glaube trotzdem, dass du die Operation bewältigen kannst.}
{691}{}{Ich hatte allen Grund, dir zu vertrauen, Fremder, aber Tiere wissen Dinge, die Menschen nicht wissen. Ich werde nie erfahren, wovor die Maus sich bei dir gefürchtet hat, aber ich kann dich Makkon nicht behandeln lassen. Ich ... verbiete es.}

{692}{}{Sonst noch was?}
{693}{}{Denk daran – die Zeit wartet nicht auf dich, Fremder. Noch ein paar Monate ohne Behandlung, und der Junge wird sterben. Ruh dich erst einmal aus. Wenn du bereit bist, über die Operation zu sprechen, komm zu mir.}
{694}{}{Das war's! Ich gehe.}
{695}{}{[Verlassen.]}

{696}{}{Für das mit Bravour bestandene Prüfungsstück erhältst du }
{697}{}{Für deine großartige Leistung bei der Prüfung erhältst du }
{698}{}{Für das Bestehen der Prüfung erhältst du }
{699}{}{ Erfahrungspunkte.}

#########################################################
#
#          Îáñóæäåíèå ëå÷åíèÿ Ìàêîíñà
#
#########################################################

{700}{}{Lass uns über Makkons Operation sprechen.}
{701}{}{[Er seufzt] Die Zeit ist gekommen. Was sollen wir tun?}
{702}{}{Zuerst müssen wir den Eiter ablassen und die Entzündung eindämmen. Wir müssen ihn zum Bluten bringen und dann die Verletzung säubern.}
{703}{}{[Er nickt] Ja, ja ... Wir brauchen sauberes Wasser und ein scharfes Messer. Aber wie soll er das aushalten? Er ist noch so jung ...}
{704}{}{Ja, der Junge braucht eine Narkose. Vorkriegs-Chems wären am besten, aber wenn du ihnen nicht traust, können wir Alkohol oder Kräuter verwenden.}
{705}{}{Ja ... Mein Heilpulver kann ihm in der Traumwelt Linderung verschaffen. Aber bring auch deine Chems mit. Wenn es so weit ist, entscheiden wir, was am besten ist. Was noch?}
{706}{}{Wir brauchen kräftige Hände, um seine gebrochenen Knochen zu richten, und eine Pinzette oder Zange, um Knochensplitter unter der Haut zu entfernen.}
{707}{}{Ja, genau. Und dann?}
{708}{}{Wir müssen seine Wunden nähen und verbinden und seine gebrochenen Knochen schienen.}
{709}{}{Verbände? In den Städten werden sie in Kisten mit einem roten Kreuz darauf aufbewahrt. Du weißt wahrscheinlich besser als ich, wo man sie bekommt.}
{710}{}{Ja, in Erste-Hilfe-Kästen. Nach der Operation muss der Junge ständig betreut werden und sich viel ausruhen. Er braucht Medikamente gegen sein Fieber und etwas, das das Zellwachstum anregt.}
{711}{}{Ja, ich werde Heilpulver aus Xanderwurzeln und Broc-Blüten zubereiten. Das wird seine Genesung beschleunigen.}
{712}{}{Ich kann auch Stimpaks mitbringen. Keine Sorge, sie sind harmlos. Ein stimpak enthält natürliche Inhaltsstoffe, heilt aber viel wirksamer als Heilpulver.}
{713}{}{Gut, das überlasse ich dir.}
{714}{}{Erinnere mich noch mal: Was brauchen wir alles?}
{715}{}{Wir brauchen: 1) sauberes Wasser; 2) Heilpulver, Schmerzmittel oder Alkohol; 3) ein scharfes Messer; 4) eine Pinzette oder Zange; 5) einen Erste-Hilfe-Kasten; und 6) Heilpulver oder Stimpaks.}
{716}{}{Wenn du alles hast, komm hierher zurück.}
{717}{}{Ich komme wieder.}

{718}{}{Wegen Makkon – was brauchen wir?}
{719}{}{Vergiss nichts. Wir brauchen: }
{720}{}{Stimmt.}

#########################################################
#
#          Îïåğàöèÿ
#
#########################################################

{800}{}{Ich bin bereit, Makkon zu operieren.}

{801}{}{[Er holt tief Luft und nickt dann] Es ist so weit. Hast du ein scharfes Messer?}
{802}{}{Hier.}
{803}{}{Äh ... Nein.}
{804}{}{Wie sollen wir es ohne Messer machen? Was hast du dir dabei gedacht? Du darfst mit Makkons Leben nicht so leichtfertig umgehen!}
{805}{}{Gut. Dann fangen wir an.}
{806}{}{[Anfangen.]}
{807}{}{Nein, warte, ich habe etwas vergessen. Ich bin gleich zurück.}

{808}{}{[Niskigvans Hände zittern leicht, doch er wirkt entschlossen] Wir müssen sicherstellen, dass Makkon während des Eingriffs nicht aufwacht. Was nehmen wir?}
{809}{}{Nehmen wir dein Heilpulver.}
{810}{}{Ich habe Schmerzmittel in dieser Arzttasche.}
{811}{}{Ich habe Schmerzmittel in diesem Erste-Hilfe-Kasten.}

{812}{}{Aber was, wenn sie gefährlich sind? Wo wurden sie aufbewahrt? Was, wenn sie verdorben sind?}
{813}{}{Na gut, nimm deine traditionelle Medizin.}
{814}{}{Diese Schmerzmittel laufen nicht ab und haben keine Nebenwirkungen. Lies die Aufschrift auf der Flasche, sie sind gut! Außerdem habe ich selbst schon solche genommen.}
{815}{}{Gut. Siehst du, dem Jungen fallen schon die Augen zu ... Er ist jetzt im Land der Träume und wird keinen Schmerz spüren. Kümmern wir uns um seine Wunden. [Niskigvans Hände zittern, als er die Verbände von Makkons Füßen entfernt, doch seine Bewegungen sind sicher] Womit verhindern wir eine Infektion? Diese Geister sind sehr gerissen ... }
{816}{}{Sauberes Wasser.}
{817}{}{Die Flasche mit dem Fusel. Der Alkohol sterilisiert seine Wunden.}
{818}{}{Ich habe hier etwas Fusel. Der Alkohol sterilisiert seine Wunden.}
{819}{}{Wir müssen es mit Brunnenwasser riskieren.}
{820}{}{Nein! [Er schüttelt stirnrunzelnd den Kopf] Ich bereite das Wasser zu. Ich habe einen Kräuteraufguss, der es reinigt.}
{821}{}{Was kommt als Nächstes?}
{822}{}{Alles ist bereit. Jetzt müssen wir uns um seine Knochen kümmern. Wo ist das Messer? Es sollte ebenfalls sterilisiert sein. Hast du eine Zange oder etwas Ähnliches mitgebracht?}
{823}{}{Nimm diese schmale Zange. Die ist dafür perfekt.}
{824}{}{Nein, tut mir leid.}
{825}{}{Diese hier müssen auch gereinigt werden ... So. Halt seine Beine fest, während ich die losen Splitter entferne ... }
{826}{}{Hm. Das ist nicht gut. Zum Glück habe ich hier eine Vorkriegs-Pinzette. Für so einen heiklen Eingriff ist sie nicht gerade geeignet, aber wir haben nichts anderes. Halt seine Beine fest, während ich die Splitter entferne ... }
{827}{}{[Du behandelst eine halbe Stunde lang Makkons Wunden und entfernst kleine Knochensplitter aus seinen Beinen]}
{828}{}{Wir müssen den Eiter ausspülen. Wir müssen die Wunden öffnen. [Du lässt vorsichtig den Eiter aus Makkons verletztem Gewebe abfließen]}
{829}{}{Wir müssen den Eiter ausspülen. Wir müssen die Wunden öffnen. Warum stehst du hier herum? Wir dürfen keine Zeit verlieren! Halt seine Beine fest, während ich den Eiter abfließen lasse.}
{830}{}{Das Gewebe ist sauber. Jetzt gibt es kein Zurück mehr. Nun müssen wir die Knochen richten. [er holt tief Luft] Wenn wir das Gewebe beschädigen, geht es ihm wieder so schlecht wie am Anfang. Fangen wir an.}
{831}{}{[Du reinigst die Wunden] Jetzt müssen wir die Wunden zunähen – oder sie zumindest fest verbinden.}
{832}{}{Ich habe Mull und Verbandszeug in dieser Arzttasche.}
{833}{}{Ich habe Mull und Verbandszeug in diesem Erste-Hilfe-Kasten.}
{834}{}{Ich habe nichts dergleichen. Können wir Gecko-Haut nehmen?}

{835}{}{[Niskigvan blinzelt hastig, während ihm Schweiß in die Augen läuft] Jetzt müssen wir eine Schiene anlegen. Ich habe Holzstangen und etwas Stoff, um sie festzubinden. [Du und Niskigvan schient vorsichtig Makkons verletzte Beine. Makkon stöhnt leise.] Pst, Bärenjunges. Bleib stark. Wir sind gleich fertig.}

{836}{}{[Schließlich bindest du den letzten Verband fest. Niskigvan steht auf; seine Hände zittern vor Erschöpfung.] Die Operation ist abgeschlossen. Makkons Körper muss heilen. Wir müssen entscheiden, wie wir ihn wieder auf die Beine bringen.}
{837}{}{Bettruhe und reichlich zu essen. Er muss all seine Kraft auf die Heilung verwenden.}
{838}{}{Morgen muss er mit Heilpulver behandelt werden, damit er schneller wieder gesund wird.}
{839}{}{Hier ist ein stimpak. Es beschleunigt das Zellwachstum. Spritz es ihm morgen ins Bein.}
{840}{}{Hier sind zwei Stimpaks. Spritz ihm morgen je eines in jedes Bein. Sie fördern das Zellwachstum und beschleunigen so die Genesung.}
{841}{}{[Das Gesicht des Heilers ist blass und schweißnass. Er wäscht sich die Hände und geht nach draußen, um etwas frische Luft zu schnappen.]}
{842}{}{Geh auch etwas frische Luft schnappen.}

{843}{}{Mir ist schlecht ...}

{844}{}{Ich habe ein altes Schmerzmittel.}

{860}{}{Ich habe ein Springmesser.}
{861}{}{Ich habe ein altes Küchenmesser.}
{862}{}{Ich habe ein Wurfmesser.}
{863}{}{Ich habe ein scharfes Kampfmesser.}
{864}{}{Ich habe ein Rasiermesser.}
{865}{}{Messer für eine Operation? Wie barbarisch! Nimm dieses Skalpell. Es ist genau für diesen Zweck gemacht.}

#Ñîîáùåíèÿ â êîíñîëü ïîñëå îïåğàöèè:
{850}{}{Du erhältst 1000 Erfahrungspunkte, weil du Niskigvan dabei geholfen hast, Makkons schwere Verletzungen zu behandeln. Du und Niskigvan habt beide etwas Neues gelernt.}
{851}{}{Du erhältst 2000 Erfahrungspunkte, weil du Niskigvan dabei geholfen hast, Makkons schwere Verletzungen zu behandeln. Du und Niskigvan habt beide etwas Neues gelernt.}
{852}{}{Du erhältst 3000 Erfahrungspunkte für die Behandlung von Makkons schweren Verletzungen. Du und Niskigvan habt beide etwas Neues gelernt.}
{853}{}{Du erhältst 5000 Erfahrungspunkte für deine wundersame Heilung. Du und Niskigvan habt beide etwas Neues gelernt.}

#########################################################
#
#          Óñòàğåâøàÿ ÷àñòü äèàëîãà (not used, old version)
#
#########################################################

{2146}{}{Ich mache mich im Auftrag von Ogima Schwarze Wolke auf den Weg zum Stützpunkt der Raider. Können Sie mir einen Rat geben?}
{2149}{}{Können Sie ein starkes Gift herstellen? Auf dem Stützpunkt der Raider gibt es einen Tank mit Trinkwasser. Wenn man das Wasser vergiftet ...}

#Ïğî îòğàâëåíèå âîäû ğåéäåğàì
{2178}{}{Die Himmlische Mutter hat mich nicht mit der Gabe einer Heilerin gesegnet, damit ich Gift braue! Ich heile Menschen, statt ihnen zu schaden. Und wenn ich ehrlich bin ... Ich weiß einfach nicht, wie man Gift herstellt. Wenn Sie bereit sind, diese Bürde auf sich zu nehmen, sollten Sie direkt nach New Reno gehen.}
{2179}{}{Und wo ist das?}
{2180}{}{Stellen sie dort Gift her? Und wer genau?}
{2181}{}{Woher wissen Sie eigentlich von Reno?}
{2182}{}{Verstehe. Noch eine Frage.}
{2183}{}{Das ist eine verdammte Stadt, nicht weit im Südwesten. Am besten lässt man sich dort nicht blicken. Andererseits gibt es in der Gegend nichts Vergleichbares. Ich markiere sie auf Ihrer Karte, aber ich warne Sie: Seien Sie dort vorsichtig und gehen Sie nicht in die abgelegenen Viertel.}
{2184}{}{Ich erinnere mich nicht an Namen. Und wahrscheinlich haben sie auch keine. Fragt in den Lokalen der Stadt herum. Sätze wie „Ich will jemanden vergiften“ oder „Ich muss jemanden umbringen“ hört man in New Reno öfter als Begrüßungen.}
{2185}{}{Niemand aus unserem Stamm ist so weit gereist und so vielen Menschen begegnet wie ich. Das lässt sich nicht so schnell erklären – die Geschichte der Cheyenne reicht viele Jahre zurück. Es gab vieles, worum ich mich kümmern musste, und unsere Götter haben mich geführt ... Seht ihr dort gegenüber von Ogimas Hütte den Bewässerungswasserfänger? Er wurde mit Hilfe der wundersamen Technologien von New Reno gebaut.}
{2186}{}{Verstehe. Na ja, ich muss zu den Raidern.}

#########################################################
#
#             Female character
#
#########################################################

{1205}{}{Ich habe deinen verlorenen Rucksack mitgebracht.}
{1300}{}{Wir können unser Weniges nicht mit dir teilen, Fremder. Aber ich kann dir Medizin mischen, wenn du mir die Zutaten bringst.}
{1366}{}{He, he, tut mir leid. Ich war etwas zu aufgeregt. Aber du weißt wirklich nicht, ob es hier in der Nähe einen Radiosender gibt?}
{1370}{}{Nein, warte! Ich zeige dir den Radiosender. Tu nur niemandem etwas!}
{1450}{}{Hm. Wenn ich mehr über Arzneimittelkunde wüsste, könnte ich versuchen, dich zu überzeugen. Vielleicht ein andermal.}
{1451}{}{Du musst nicht blind vertrauen. Ich bin ein Experte für Medizin. Ich könnte es dir erklären.}
{1480}{}{Ich bin keine Wohltätigkeitsorganisation. Vergiss es.}
{1486}{}{Zweifellos hat dich der Herrscher des Lebens geschickt! Danke, Fremder! So viel Großzügigkeit ist in unserer Zeit selten ... Selten und kostbar. Solange du lebst, werde ich deine Verletzungen kostenlos behandeln.}
{1504}{}{Es ist vorbei, Fremder. Vergiss es und geh in Frieden.}
{1507}{}{[Er beugt sich vor und schaut dir in die Augen] Ist das Herz des Fremden so schwer vor Kummer wie meines?}
{1509}{}{Und sie will nur helfen, ohne eine Gegenleistung zu verlangen?}
{1557}{}{Ich möchte dem verletzten Jungen helfen. Euer Häuptling hat mir die Erlaubnis gegeben.}
{1559}{}{Da bin ich mir sicher.}
{1562}{}{Ich bin gerade etwas müde. Vielleicht später?}
{1704}{}{Ja, der Junge braucht eine Narkose. Vorkriegs-Chemikalien wären am besten, aber wenn du ihnen nicht vertraust, können wir Alkohol oder Kräuter nehmen.}
{1800}{}{Ich bin bereit, Makkon zu operieren.}
{1802}{}{Hier.}
{1804}{}{Wie sollen wir es ohne Messer machen? Was hast du dir dabei gedacht? Du darfst mit Makkons Leben nicht so leichtfertig umgehen!}
{1807}{}{Nein, warte, ich habe etwas vergessen. Ich bin gleich zurück.}