{100}{}{Ogima, der Black Cloud, der Häuptling des Stammes.}
{101}{}{Du siehst einen alten Häuptling der Cheyenne.}
{102}{}{Das hättest du nicht tun sollen, Fremder.}
{103}{}{Du hast unser Vertrauen missbraucht, und wofür? Ich habe ohnehin nichts, was du haben wollen könntest.}

###############################################################
#
#  Íà÷àëî äèàëîãà
#
###############################################################

#Òğåáîâàíèå óáğà'ü îğóæèå èç ğóê
{110}{}{Wir sind ein friedlicher Stamm, Fremder. Wir werden nicht mit Waffen in der Hand reden.}
{111}{}{Dein Zelt, deine Regeln. [Steck deine Waffe weg]}
{112}{}{Dann werden wir nicht reden.}
{113}{}{Der Fremde muss seine Waffe wegstecken, wenn er sprechen will.}

#Ïğî ìîãèëû
{115}{}{Und so erscheint der Mann, dem seine Gier wichtiger ist als der Frieden unserer Toten ...}
{116}{}{Wovon redest du?}
{117}{}{Jemand hat unsere Gräber gestört. Es waren keine Tiere und keine Raider. Das ist uns beiden klar, aber behalten wir unsere Vermutungen für uns. Was geschehen ist, lässt sich nicht rückgängig machen, oder?}
{118}{}{Äh ... Na gut, schätze ich. Aber ich wollte mit dir reden.}
{119}{}{Oh ... Äh, dann gehe ich die Gräber wieder zuschütten.}

#Ñ'àğ' äèàëîãà
{120}{}{Sei gegrüßt, Fremder. Was hat dich in unser Dorf geführt?}
{121}{}{Kann ich dich etwas über diese Gegend fragen?}
{122}{}{Ich möchte über den kranken Jungen beim Heiler sprechen.}
{123}{}{Warum folgt mir Makozid?}
{124}{}{Euer Stamm interessiert sich nicht besonders für die Zivilisation, oder?}
{125}{}{Ich suche einen Radiosender hier in der Gegend. Weißt du, wo er ist?}
{126}{}{Lass uns über die Räuber sprechen.}
{127}{}{Nichts. Ich gehe.}
{128}{}{Die Räuber sind fort. Was wird nun aus eurem Stamm?}

###############################################################
#
#  Ïğî ìåñ'íîñ'ü
#
###############################################################

#Ñïèñîê âîïğîñîâ
{130}{}{Die Götter richten ihren Blick nur selten auf dieses Land. Hier gibt es nichts Besonderes. Wenn das Ödland unser Tal verschlingt, wird auch all das hier vergehen.}
{131}{}{Erzähl mir mehr über deinen Stamm.}
{132}{}{Erzähl mir mehr über diese Siedlung.}
{133}{}{Erzähl mir mehr über die Räuber.}
{134}{}{Was gibt es in der Nähe des Lagers?}
{135}{}{Leben noch andere hier in der Gegend?}
{136}{}{Das war's.}

#Î'âå'û
#140 We honor our gods and don't rebel against other people's, wishing only to live in peace and prosperity.
#But the thing is that in the nest of the World Devourer's kids - Reno! The tribe had other opinion back then...
#We hoped to trade and buy those amazing things... Er... Yes, technology.
#But in result we were discovered by dark hearted raiders under the leadership of Big Louie.
#That's how he is called now. And now we don't welcome outsiders.

{140}{}{Unser Stamm baut Feldfrüchte an und hält brahmin. Das ist das Einzige, was die Himmlische Mutter uns hinterlassen hat. Doch selbst der letzte Rest dessen, was wir haben, wird uns nun von Parasiten genommen – von denen, die ihr „Räuber“ nennt. Manchmal frage ich mich, ob wir den Herrscher des Lebens erzürnt haben und deshalb solche dunklen Zeiten über unser Volk hereinbrechen ...}
{141}{}{Unser Dorf heißt Fremde nicht willkommen, doch Wanderer finden hier immer Nahrung und eine Rast ... Gegen Bezahlung, versteht sich. Außerdem kann der Heiler Niskigvan mit der Hilfe der Himmlischen Mutter Wunden heilen und Gift aus deinem Körper ziehen.}
{142}{}{Kinder des Weltenverschlingers. Ihr dunkles Versteck liegt im Norden. Geh nicht ohne triftigen Grund dorthin, denn nicht alle, die dorthin gehen, kehren zurück.}
{143}{}{Das Tal, die Berge und unser Stamm – das werden Wanderer hier finden. Doch nähere dich nicht dem Nest der Kinder des Weltenverschlingers im Norden.}
{144}{}{Nur wenige entscheiden sich dafür, nahe bei den Kindern des Verschlingers zu leben. Die Mutigen haben diesen Ort vor vielen Monden verlassen; bis zum nächsten Lager sind es nun viele Tage Fußmarsch. Reno, Gerlach und Poseidon Oil – mehr hat das Auge der Cheyenne nicht gesehen ... Nun ja, abgesehen von den Legenden.}
{145}{}{Ich habe noch eine Frage.}
{146}{}{Das reicht.}

#Ïğî ïîñåëåíèÿ
{150}{}{Wo ist Reno?}
{151}{}{Was ist Gerlach?}
{152}{}{Poseidon Oil? Was ist das?}
{153}{}{Legenden?}
{154}{}{Davon weiß ich schon. Reden wir über etwas anderes.}
{155}{}{Reno, eine Stadt, die von den Göttern verflucht wurde. Böse Geister in Menschengestalt streifen durch jene Canyons aus Metall, Glas und Beton. Wenn du weise bist, hältst du dich davon fern.}
{156}{}{Ein Lager der Verzweifelten, die aus Reno geflohen sind. Möge die Himmlische Mutter sie segnen.}
{157}{}{Eine Stadt der Toten im Norden. Wir nennen sie Gecko, wegen der wilden Tiere, die dort in großen Rudeln leben. Aber auf dem größten Gebäude steht „NPP Poseidon Oil“. Sei vorsichtig, wenn du dorthin gehst – die Jäger, die den Ort zuerst erkundeten, wurden von Geistern vergiftet, die sie nicht sehen konnten. Niskigvan, die zerzausten Federn, kämpfte zwei ganze Monde lang, um ihr Leben zu retten!}
{158}{}{Nun ja ... Unser Hirte, der weit nach Norden zog, behauptet, in den Bergen gebe es eine wundersame Stadt aus weißem Stein und ewigem Licht, bewacht von Kriegern in grüner Rüstung, die niemals ruhen. Doch er ist der Einzige, der sie gesehen hat, und viele halten ihn für ... unzuverlässig.}

###############################################################
#
#  Ïğî ëå÷åíèå Ìàêîíñà
#
###############################################################

{200}{}{Niskigvan tut alles, was er kann, aber ich fürchte, es ist hoffnungslos. Makkon, der kleine Bär, ist dazu verdammt, für immer verkrüppelt zu sein ... falls er überhaupt überlebt.}
{201}{}{Lass es. Niskigvan kämpft darum, ihn zu retten, aber ich fürchte, es ist hoffnungslos. Makkon, der kleine Bär, ist dazu verdammt, für immer verkrüppelt zu sein ... falls er überhaupt überlebt.}

#Íå' äîñ'èæåíèÿ äå'îóáèéöû
{202}{}{Ich bin Arzt, ich kann das richten. Ehe du dich versiehst, tanzt Makkon wieder und jagt Mädchen nach!}
{203}{}{Reden wir über etwas Angenehmeres.}
{204}{}{Schon gut, dann ...}

#Ïåğåõîä ê âûáîğó ñïîñîáîâ
{205}{}{Du? [Er schüttelt den Kopf.] Deine Hände und Augen sagen die Wahrheit, die deine Worte verschweigen. Mach dir nichts vor, Fremder. Du bist kein Heiler.}
{206}{}{Hmm. Niskigvan wird der Medizin eines Fremden nicht so leicht vertrauen. Wie will der Fremde das Kind heilen?}
{207}{}{Mit Chems. Vertrau mir, dein Kind wird sich nicht einmal daran erinnern, dass es verkrüppelt war!}
{208}{}{Vorkriegsmedizin. Was sonst?}
{209}{}{Mit meinen Händen, natürlich. Wir brauchen nichts weiter.}
{210}{}{Ich bringe ihn an einen Ort mit funktionierender medizinischer Ausrüstung und werde ihn operieren.}
{211}{}{Dafür ist eine komplizierte rekonstruktive Operation nötig. Niskigvan und ich werden sie gemeinsam durchführen.}

{212}{}{Chems?! Bei der Himmlischen Mutter, ich verbiete dir, diesen Jungen auch nur anzufassen! Dieses Gift ist nur für die Kinder des Weltenverschlingers bestimmt!}
{213}{}{Lass mich das erklären ...}
{214}{}{Darüber wird nicht diskutiert! Sich mit Chems zu vergiften ist, als würde man dem Verschlinger seine Seele überlassen, obwohl man noch lebt.}
{215}{}{Was hat das überhaupt damit zu tun ... Ach, vergiss es.}

{216}{}{Nein! Unser Stamm hat schon einmal unter diesem Gift aus der Vorkriegszeit gelitten. Im Namen der Himmlischen Mutter werden wir niemals zulassen, dass es unseren Jungen krank macht.}
{217}{}{Na gut, wir können einen anderen Weg finden.}
{218}{}{Selbst jemand, der von der Himmlischen Mutter gesegnet ist, kann eine solche Verletzung nicht allein mit den Händen heilen.}
{219}{}{Auf keinen Fall!}
{220}{}{Bitte versteh doch: Er braucht eine umfangreiche und komplizierte Behandlung und Operation.}

{221}{}{Kannst du erklären, was deine fremdartige Behandlung bewirken soll, das Niskigvans nicht kann?}
{222}{}{Sieh mal, eure Heilerin behandelt Verletzungen mit Kräutern, aber die Wirkung setzt zu langsam ein und ist nicht stark genug, um die Schwellung zu lindern oder die Knochen wieder zusammenwachsen zu lassen. Deshalb wird die Verletzung nach einiger Zeit wieder anschwellen. Das ist ein Teufelskreis. Makkon braucht eine andere Behandlung.}
{223}{}{Eure Kräutermedizin wirkt zu langsam. Makkons Zustand wird bald zu Wundbrand führen. Wenn wir nicht sofort mit der richtigen Behandlung beginnen, muss Niskigvan dem Jungen die Beine amputieren – oder Schlimmeres!}

{224}{}{Hm, ich hoffe, Niskigvan versteht dich besser als der alte Häuptling ... Aber welche Behandlung bietet der Fremde an?}
{225}{}{Den Eiter entfernen, die Verletzung ausbluten lassen, die Entzündung lindern und dann die Knochen richten.}
{226}{}{Du willst ihn aufschneiden, während er noch lebt?!}
{227}{}{Unter Kräuternarkose.}
{228}{}{Unter Alkoholvergiftung.}
{229}{}{Unter Narkose mit vorkriegszeitlichen Medikamenten.}
{230}{}{Ja. Er muss es durchstehen.}

{231}{}{Unakzeptabel! Im Namen der Himmlischen Mutter verbiete ich dir, diesen Jungen auch nur anzufassen! Diese Behandlung ist nur für die Kinder des Weltenverschlingers geeignet!}
{232}{}{Lass mich das erklären ...}

{233}{}{Götter, schon der Gedanke daran ist widerwärtig! Aber ... Vielleicht hast du recht. Niskigvan kämpft schon seit drei Monden, und das hat das Leiden des Jungen nur verlängert. Deine Methoden könnten nötig sein. Aber ... ich ... Sag mir, wie viele Knochen hast du in deinem Leben schon gerichtet, Fremder?}
{234}{}{[Macht eine beruhigende Geste] Genug.}
{235}{}{Götter, schon der Gedanke daran ist widerwärtig! Ihn ausbluten lassen?! Was redest du da!!! Oh, Himmlische Mutter ...}
{236}{}{Klinge ich nicht überzeugend genug? Na ja, vielleicht änderst du später deine Meinung.}

{237}{}{Diese Antwort beruhigt mich. Ich erteile dir meine Erlaubnis. Aber wenn dem Jungen etwas zustößt, wird dich der Hass der Cheyenne treffen! Unsere Götter werden dich bestrafen, und der Weg in unser Land wird dir für immer verschlossen sein! Geh jetzt zu Niskigvan, und möge die Himmlische Mutter deine Hände führen!}
{238}{}{[Geh.]}
{239}{}{Du hast die Erlaubnis erhalten, Makkon zu heilen.}

{240}{}{Es tut mir leid. Lass uns über etwas Angenehmeres reden.}
{241}{}{Ich sollte mich wirklich nicht einmischen. Lass uns über etwas Angenehmeres reden.}
{242}{}{Nicht überzeugt, hm? Lass uns über etwas anderes reden.}

#Åñ'ü äîñ'èæåíèå äå'îóáèéöû
{250}{}{[Er beugt sich vor und blickt dir in die Augen] ... Kinder sind schon einmal durch deine Hand gestorben, nicht wahr?}
{251}{}{Das war ein Unfall, Häuptling! Du musst mir glauben! Das Kind war einfach zur falschen Zeit am falschen Ort!}
{252}{}{Ja, das sind sie. Aber ich möchte hier helfen.}
{253}{}{Äh, nein. Ehrlich.}
{254}{}{Was?! Leg dich nicht mit mir an, Alter, sonst röste ich jedes Kind im Stamm über deinem Lagerfeuer!}

{255}{}{[Er mustert dein Gesicht und nickt dann] Ich glaube dir. So etwas Böses passt nicht zu einem Mann, der so viel Gutes getan hat. Du kannst auf mein Vertrauen zählen.}
{256}{}{Gut.}
{257}{}{Selbst dir kannst du nicht trauen, solange du dich nicht durch gute Taten rehabilitiert hast.}
{258}{}{Steht mir etwa „Karma-Teufel“ auf die Stirn geschrieben? Na gut, ich gehe ein paar gute Taten in der Welt vollbringen und bin gleich wieder da.}
{259}{}{Als ob mich deine Meinung interessieren würde. Dein Pech, Alter.}
{260}{}{Oh nein, Wanderer. Du kannst mich nicht belügen. Ich sehe den Makel auf deiner Seele.}
{261}{}{Na gut, du hast recht. Er war nicht mein erstes Opfer. Aber ich will trotzdem helfen.}
{262}{}{Nein, Fremder. Wir brauchen und wollen keine Hilfe von deinesgleichen.}
{263}{}{Das werden wir ja sehen, Häuptling!}
{264}{}{Wie du willst.}

{265}{}{Das Böse deiner Taten wiegt noch immer schwerer als das Gute, das du getan hast, Wanderer. Der Tod eines Kindes wiegt schwerer als tausend gute Taten.}
{266}{}{Mann, man bringt ein Kind um, und keiner vergisst es je. Na gut, ich versuche es weiter.}
{267}{}{}
{268}{}{Heißt das Nein? Du könntest dich wirklich klarer ausdrücken.}
{269}{}{Hast du ein Problem mit Kindermördern, Alter?}

{270}{}{[Er schüttelt den Kopf] Warum bedrohst du einen alten Mann? Wird das irgendetwas lösen?}
{271}{}{Nein. Aber ich werde mich danach viel besser fühlen! [ihm ins Gesicht schlagen]}
{272}{}{Ich nehme an, du hast recht. Ich gehe friedlich.}

{273}{}{Verschwinde! Möge dein Weg nie wieder den der Cheyenne kreuzen. Mögen selbst die Kojoten deine Überreste meiden!}
{274}{}{Na gut, ich gehe friedlich.}
{275}{}{Das war eine schlechte Idee, Häuptling. [ihm ins Gesicht schlagen]}

###############################################################
#
#  Ìèíè-êâåñ'û
#
###############################################################

#Êâåñ' íà î÷èñ'êó ïëàí'àöèé
{300}{}{Wenn du mit einer Schlange spielst, lass sie nicht zu nahe kommen. Diese Welt ist gefährlich.}
{301}{}{Mit anderen Worten: Du vertraust Fremden nicht.}
{302}{}{[Er nickt] Viele Fremde kommen mit schönen Worten und hässlichen Gedanken zu den Cheyenne. Makozid Bärentatze beobachtet Fremde, damit sie unserem Stamm nichts Böses antun.}
{303}{}{Brauchst du bei irgendetwas Hilfe?}
{304}{}{Verstehe. Reden wir über etwas anderes.}
{305}{}{Ich verstehe den Wink. Ich gehe.}

{306}{}{Wir brauchen nichts von Fremden. Aber wenn du dir Essen und Unterkunft verdienen willst, haben wir Arbeit für dich.}
{307}{}{Wenn die Belohnung stimmt, gern.}
{308}{}{Du musst mir nichts geben. Ich helfe auch so gern.}
{309}{}{Worum geht's?}
{310}{}{Vielleicht später. Reden wir über etwas anderes.}

{311}{}{Der Verschlinger hat seinen Samen zwischen unseren Feldfrüchten gesät. Daraus wachsen Pflanzen, die nach Fleisch gieren. Sie hindern unsere Frauen daran, die Ernte einzubringen, aber ich kann keine Männer entbehren, um sie zu töten. Säubere die Plantage, und wir werden dich belohnen.}
{312}{}{Wie viel zahlst du?}
{313}{}{Hier mein Gegenangebot: Ich säubere die Plantage, und du zahlst mir keinen Cent.}
{314}{}{Gegen Pflanzen kämpfen? Nein, ich glaube nicht. Mach's gut.}

{315}{}{Wir können dir dafür 300 Dollar geben. Einverstanden?}
{316}{}{Klingt gut. Ich komme wieder, wenn der Auftrag erledigt ist.}
{317}{}{Behalt das Geld. Ich mach's umsonst.}
{318}{}{Sehr gut. Die Felder liegen im Westen. Wir erwarten gute Nachrichten, Fremder.}
{319}{}{Ich gehe.}

{320}{}{Wegen dieser Killerpflanzen ...}
{321}{}{Ja, Fremder?}
{322}{}{Wo waren sie noch mal?}
{323}{}{Wie viele sind es?}
{324}{}{Sie sind alle tot.}
{325}{}{Nichts.}
{326}{}{}
{327}{}{Im Westen, Fremder. Auf der anderen Seite des Lagers.}
{328}{}{Fünf. Sieh genau hin, denn sie verstecken sich gut vor den Augen ihrer Opfer.}
{329}{}{Diese Nachricht wird unseren Frauen das Herz erwärmen. Wir danken dir, Wanderer.}
{330}{}{Und was ist mit meiner Belohnung?}
{331}{}{Deine Dankbarkeit ist Belohnung genug. Ich brauche nichts.}
{332}{}{Dieser Kampf hat mich ganz schön mitgenommen. Kann ich stattdessen etwas zu essen bekommen?}
{333}{}{Hier sind deine 300 Dollar, Fremder. Mögen sich unsere Wege eines Tages wieder kreuzen.}
{334}{}{Nicht viel, aber immerhin etwas. Mach's gut, Häuptling.}
{335}{}{Nicht schlecht! Bis bald, Häuptling.}
{336}{}{Das ist sehr überraschend, Fremder. Die Cheyenne danken dir für deine Freundlichkeit. Aber ich kann dich nicht mit leeren Händen gehen lassen. Nimm dieses Sandwich, damit du die Kraft hast, anderen zu helfen.}
{337}{}{Danke.}
{338}{}{Das ist fair. Warte einen Moment hier. [der Häuptling geht für eine Minute hinaus und kommt mit fünf Sandwiches zurück, die er dir reicht]}
{339}{}{Ja!}

#Êâåñ' íà âîäîñáîğíèê
{350}{}{Die Erde durch Beton und den Baum durch Eisen zu ersetzen, heißt, die Wahrheit über sich selbst zu vergessen. Die Menschen der Städte verloren ihren Geist. Unsere Vorfahren lebten im Einklang mit der Natur, erwiesen der Himmlischen Mutter und Herrscherin des Lebens die Ehre und blieben so vor der Torheit bewahrt, die die Welt zerstörte.}
{351}{}{Andererseits benutzt ihr immer noch übrig gebliebene Technologie.}
{352}{}{... Ja. Aber nur, wenn es keine andere Wahl gibt. Doch auch das, was noch übrig ist, wird bald zu Asche zerfallen.}
{353}{}{Ist etwas kaputt?}
{354}{}{Verstehe. Ich habe noch eine Frage.}

{355}{}{Rust hat den Wassertank übernommen, den wir für unsere Felder nutzen. Um ihn zu reparieren, brauchen wir Ersatzteile und Fachwissen, und wir haben beides nicht.}
{356}{}{Ich kann euch helfen.}
{357}{}{Wie schade. Lass uns über etwas anderes reden.}
{358}{}{Ihr wollt uns helfen? Danke, Fremder, aber wir haben nichts, was wir euch im Gegenzug anbieten können.}
{359}{}{Machen wir einen Handel: Ich repariere den Wassertank, und dafür bekomme ich regelmäßig etwas zu essen.}
{360}{}{Wie schade. Dann viel Glück dabei.}
{361}{}{Ihr müsst mich nicht bezahlen. Ich möchte einfach nur helfen.}
{362}{}{Na schön, dann eben keine Reparatur.}

{363}{}{[Er nickt.] Wir nehmen an. Unser Koch wird dich wie einen der Unseren behandeln ... aber erst, wenn die Arbeit erledigt ist.}
{364}{}{Ich erledige das.}
{365}{}{Eigentlich habe ich es mir anders überlegt. Kein Handel.}
{366}{}{Du hast einen alten Mann glücklich gemacht, Fremder. Und denk daran: Sollte sich diese Aufgabe als zu schwierig erweisen, kann dir vielleicht jemand anderes draußen im Ödland helfen. Möge der Herrscher des Lebens deinen Weg leiten.}
{367}{}{Ich komme mit guten Nachrichten zurück.}
{368}{}{[Er nickt verständnisvoll.]}
{369}{}{Wow, du bist wohl nicht gerade gut im Feilschen, was?}
{370}{}{Du hast einen alten Mann glücklich gemacht, Fremder. Alle Cheyenne werden dir dankbar sein. Denk daran: Sollte sich diese Aufgabe als zu schwierig erweisen, kann dir vielleicht jemand anderes draußen im Ödland helfen. Möge der Herrscher des Lebens deinen Weg leiten.}
{371}{}{Ich komme mit guten Nachrichten zurück.}

{372}{}{Also, wie steht's um den Wassertank?}
{373}{}{Die Tränen der Natur werden nicht länger auf der unfruchtbaren Erde vergeudet. Jeder Tropfen, ein Geschenk des Lebens, wird nun unsere Felder segnen. Wir sind dir dankbar, Fremder. Wie können wir es dir vergelten?}
{374}{}{Ich möchte regelmäßig Sandwiches bekommen.}
{375}{}{Ich will sofort einen ganzen Haufen Sandwiches!}
{376}{}{Vergeltet es mir, indem ihr das Wasser sinnvoll nutzt. Das ist alles.}

{377}{}{}
{378}{}{Das ist in Ordnung.}
{379}{}{Mehr als dreißig Sandwiches können wir im Moment nicht machen. Mögen sie deinen Bauch viele Tage lang fuellen.}
{380}{}{Großartig! Mehr brauche ich nicht.}
{381}{}{Die Cheyenne werden deine Güte nicht vergessen. Nur wenige Fremde kommen mit so lauteren Absichten zu uns. Mögen die anderen in dieser Welt dir dieselbe Güte entgegenbringen, solange du deinen Weg gehst.}
{382}{}{Keine Ursache, Häuptling!}

{383}{}{Das ist fair. Omakaki wird dir fünf Sandwiches in einer Kiste zurücklegen. Aber denk daran: Sandwiches halten nicht ewig. Wenn du nicht rechtzeitig kommst, werden sie nur noch unsere Pflanzen ernähren.}
{384}{}{Abgemacht!}
{385}{}{Eigentlich habe ich es mir anders überlegt. Gib mir jetzt alle Sandwiches, die du hast, dann sind wir quitt.}
{386}{}{Lass nur, ich brauche keine Belohnung. Betrachte es als eine Geste des guten Willens.}
{387}{}{Möge die Himmlische Mutter dich im Ödland beschützen.}
{388}{}{Äh, ja. Dich auch.}

###############################################################
#
#  Ğàäèîñ'àíöèÿ
#
###############################################################

{400}{}{Radio ... was? Ich weiß nichts davon.}
{401}{}{Vor dem, der uns vor den Kindern des Verschlingers gerettet hat, haben wir nichts zu verbergen. Ich zeige dir unseren Ort der Anbetung.}
{402}{}{Los geht's.}
{403}{}{Dies ist ein heiliger Ort, aber ich glaube, einem mit einem so reinen Herzen kann ich vertrauen. Ich bringe dich dorthin.}
{404}{}{Wir werden nie vergessen, was du für Makkon getan hast. Wir schützen diesen Ort vor Fremden, aber ich glaube, vor dir müssen wir nichts befürchten. Ich bringe dich dorthin.}
{405}{}{Ich habe vorher noch andere Fragen.}
{406}{}{Jetzt nicht, ich komme später wieder.}

###############################################################
#
#  Ñè'óàöèÿ ñ ğåéäåğàìè
#
###############################################################

#Èíôîğìàöèÿ î ğåéäåğàõ
{500}{}{Der Kummer und der Schmerz dieses Landes.}

{501}{}{Ich habe Neuigkeiten für dich.}
{502}{}{Warum wehrt ihr euch nicht?}
{503}{}{Erzähl mir von diesen Räubern.}
{504}{}{Wo halten sie sich auf?}
{505}{}{Wollt ihr sie nicht loswerden?}
{506}{}{Reden wir über etwas anderes.}
{507}{}{Das wollte ich wissen. Tschüss.}
{508}{}{Stimmt.}
{509}{}{}

{510}{}{Warum sollte ich es dir sagen? Solltest nicht du es mir sagen?}
{511}{}{Pass auf, was du sagst, Häuptling.}

{512}{}{Sie sind die Kinder des Weltenverschlingers. }
{513}{}{Sie schlafen im Norden. Geh nicht dorthin, wenn es nicht sein muss, denn nicht alle, die dorthin gehen, kehren zurück.}
{514}{}{Wenn das Raubtier seine Beute verlässt, kommen andere Raubtiere zum Festmahl. Wir können nur beten, dass unsere Götter uns beschützen.}
{515}{}{Wir haben genug vom Krieg. Und außerdem, was kann ein Mann mit einem Speer gegen Dämonen mit Gewehren und starker Rüstung ausrichten?}
{516}{}{Du musst nicht alles selbst erledigen. Du kannst jemanden anheuern, der sie für dich beseitigt.}
{517}{}{Und unser Leben in die Hände eines Fremden legen? Wenn der Fremde versagt, wird der Zorn des Verschlingers über uns kommen. Dieses Risiko können wir nicht eingehen.}
{518}{}{Was, wenn wir sie auf unauffälligere Weise loswerden könnten?}
{519}{}{[Er kneift nachdenklich die Augen zusammen] Was hast du vor, Fremder?}
{520}{}{Sie haben nur eine Wasserquelle. Wenn wir sie vergiften ...}
{521}{}{Noch nicht, aber wenn du mich zu ihrem Lager bringst, fällt mir sicher etwas ein.}
{522}{}{Nein, noch nicht.}
{523}{}{Das ist raffiniert, Fremder. Aber du musst anderswo nach diesem Gift suchen. Wir haben hier nichts dergleichen.}

{524}{}{[Er mustert dein Gesicht und nickt] Die Götter sagen mir, dass du Großes für die Cheyenne tun könntest. Also gut. Ich kann deinen Weg nur segnen. Gekek der Falke, der Krieger, der den Eingang zu unserem Lager bewacht, wird dir den Weg zeigen.}
{525}{}{Bevor ich gehe, kannst du mir mehr über die Räuber erzählen?}
{526}{}{Gut, ich gehe mit Gekek reden.}
{527}{}{[Er mustert dein Gesicht und runzelt die Stirn] Die Götter flüstern mir zu, vorsichtig zu sein. Ich kann dir das nicht anvertrauen, Fremder.}
{528}{}{Wie du meinst. Kannst du mir mehr über die Räuber erzählen?}
{529}{}{Dann haben wir nichts zu besprechen. Leb wohl.}

#Ñäà÷à êâåñ'îâ íà ğåéäåğîâ
{530}{}{Hast du Neuigkeiten, Fremder?}
{531}{}{Die Räuber sind tot. Statt Moonshine ertrinken sie in ihrem eigenen Blut.}
{532}{}{Die Räuber sind tot. Gift ist eine schmutzige Methode ... aber sehr effektiv!}
{533}{}{Um den Anführer der Gang musst du dir keine Sorgen machen. Er ist nach Vegas gegangen und kommt nicht zurück.}
{534}{}{Der Anführer der Gang ist tot.}
{535}{}{Oh, entschuldige. Ich wollte dir etwas anderes sagen ...}
{536}{}{Im Moment nicht. Ich rede später mit dir.}

{540}{}{Weitere Kinder des Verschlingers werden kommen. Wir werden den Kreislauf durchbrechen, bevor er von Neuem beginnt. Dieses Land hat die Cheyenne viele Jahre ernährt, aber jetzt ist es Zeit, es zu verlassen.}
{541}{}{Ihr geht fort? Warum habt ihr das nicht schon früher getan?}
{542}{}{Wir haben Kinder, Älteste, brahmin und alles, was wir mitnehmen müssen. Man hätte uns bemerkt. Aber jetzt wird uns niemand aufhalten.}
{543}{}{Wohin werdet ihr jetzt gehen?}
{544}{}{Nach Westen, dorthin, wo die Sonne in einem Meer aus Tränen versinkt. Unsere Vorfahren haben davon gesprochen.}
{545}{}{Bist du sicher, dass weitere Kinder des Verschlingers kommen werden?}
{546}{}{Es wird immer mehr von ihnen geben. Aber unser Stamm ist jetzt weiser. Wir werden uns schützen.}
{547}{}{Es ist schon ein bisschen traurig, nach all dem fortzugehen, oder?}
{548}{}{Die Erde erinnert sich. Die Erde wird sich noch viele Jahre erinnern. Wir auch.}

{549}{}{Wie soll Makkon, der kleine Bär, diese Reise schaffen?}
{550}{}{[Er seufzt] Nur die Himmelsmutter weiß es.}
{551}{}{Wenn ich ihn operieren kann, bevor ihr aufbrecht, schafft er es vielleicht. Aber zuerst brauche ich deine Erlaubnis.}
{552}{}{Natürlich. Wir vertrauen dir.}
{553}{}{Danke.}
{554}{}{Wie bald werdet ihr aufbrechen?}
{555}{}{Oh, nicht so bald. Es werden noch viele Monde vergehen, bis wir bereit sind.}
{556}{}{}
{557}{}{}
{558}{}{Bevor ihr geht, möchte ich dich etwas fragen.}
{559}{}{Na gut, bleib gesund.}

{560}{}{Die Götter warnen mich, dass die Gefahr noch besteht. Hast du nachgesehen? Vielleicht hat der Verschlinger manchen das Leben nach dem Tod geschenkt.}
{561}{}{Ich sehe es mir an und komme wieder.}

{562}{}{[Der Häuptling nickt und lächelt] Selbst die Himmel müssen die Schreie aus jenem finsteren Lager gehört haben! Du hast einem alten Mann Freude gebracht, Fremder. Die Cheyenne sind nun frei! Nicht einmal der Verschlinger kann deiner List und Stärke etwas entgegensetzen. Unsere Legenden werden sich an dich als Vabigagosh erinnern – den Weißen Fuchs!}
{563}{}{Nicht schlecht.}
{564}{}{[Der Häuptling nickt zufrieden] Selbst der Jäger hat seinen Jäger. Die Götter selbst haben diesen Kampf gesegnet!}
{565}{}{Vielleicht.}
{566}{}{Selbst der Verschlinger wird sein letztes und liebstes Kind nicht verlassen.}
{567}{}{Du meinst Big Louie? Stimmt, wir müssen uns irgendwie um ihn kümmern.}
{568}{}{Aber Big Louie ist nicht das einzige Kind im Ödland.}
{569}{}{Ich sehe, was ich tun kann.}
{570}{}{Damit beginnt eine neue Ära für die Cheyenne! Wir werden uns immer an dich als Vabimakvu erinnern – den Weißen Bären! Bitte, nimm dieses Amulett. Denk an unser Volk, wenn du es trägst, und möge es deinen Weg für immer erhellen.}
{571}{}{Nicht schlecht.}

#Female character
{1115}{}{Und so erscheint die Frau, der ihre Gier wichtiger ist als der Frieden unserer Toten ...}
{1118}{}{Äh ... Na gut, schätze ich. Aber ich wollte mit dir reden.}
{1120}{}{Sei gegrüßt, Fremder. Was führt dich auf deinem Weg zu unserem Dorf?}
{1205}{}{Du? Deine Hände und Augen sprechen die Wahrheit, die deine Worte verschweigen. Mach dir nichts vor, Fremder. Du bist kein Heiler.}
{1206}{}{Hm. Niskigvan wird der Medizin eines Fremden nicht so leicht vertrauen. Wie wirst du das Kind heilen?}
{1214}{}{Darüber wird nicht diskutiert! Dich mit Chems zu vergiften ist, als würdest du dem Verschlinger bei lebendigem Leib deine Seele opfern.}
{1221}{}{Kannst du erklären, wie deine fremde Behandlung bewirken soll, was Niskigvan nicht kann?}
{1224}{}{Welche Behandlung kannst du anbieten?}
{1237}{}{Dann erteile ich dir meine Erlaubnis. Aber wenn dem Jungen etwas zustößt, werden die Cheyenne dir für immer verschlossen bleiben! Geh zu Niskigvan, und möge die Himmlische Mutter deine Hände leiten!}
{1252}{}{Ja, das habe ich. Aber ich möchte hier helfen.}
{1255}{}{[Er mustert dein Gesicht und nickt dann] Ich glaube dir. Dieses Böse passt nicht zu einer Frau, die so viel Gutes getan hat.}
{1257}{}{Dir kann man nicht trauen, bis du dich durch gute Taten rehabilitiert hast.}
{1260}{}{Oh nein, Wanderer. Du kannst mich nicht belügen. Ich sehe den Makel auf deiner Seele.}
{1265}{}{Das Böse deiner Taten wiegt noch immer schwerer als das Gute, das du getan hast, Wanderer. Der Tod eines Kindes wiegt schwerer als tausend gute Taten.}
{1303}{}{Brauchst du bei irgendetwas Hilfe?}
{1306}{}{Wir brauchen nichts von Fremden. Aber wenn du dir Essen und Unterkunft verdienen willst, haben wir Arbeit für dich.}
{1308}{}{Du musst mir nichts geben. Ich helfe auch so gern.}
{1318}{}{Sehr gut. Die Felder liegen im Westen. Wir erwarten gute Nachrichten, Fremder.}
{1324}{}{Sie sind alle tot.}
{1327}{}{Im Westen, auf der anderen Seite des Lagers.}
{1329}{}{Die Frauen werden sich freuen. Danke, Wanderer.}
{1336}{}{Das ist sehr überraschend, Fremder. Die Cheyenne danken dir für deine Freundlichkeit. Aber ich kann dich nicht mit leeren Händen gehen lassen. Nimm dieses Sandwich, damit du die Kraft hast, anderen zu helfen.}
{1358}{}{Ihr wollt uns helfen? Danke, Fremder, aber wir haben nichts, was wir euch im Gegenzug anbieten können.}
{1365}{}{Eigentlich habe ich es mir anders überlegt. Kein Handel.}
{1366}{}{Du hast einen alten Mann glücklich gemacht, Fremder. Und denk daran: Sollte sich diese Aufgabe als zu schwierig erweisen, kann dir vielleicht jemand anderes draußen im Ödland helfen. Möge der Herrscher des Lebens deinen Weg leiten.}
{1370}{}{Du hast einen alten Mann glücklich gemacht, Fremder. Alle Cheyenne werden dir dankbar sein. Denk daran: Sollte sich diese Aufgabe als zu schwierig erweisen, kann dir vielleicht jemand anderes draußen im Ödland helfen. Möge der Herrscher des Lebens deinen Weg leiten.}
{1385}{}{Eigentlich habe ich es mir anders überlegt. Gib mir jetzt alle Sandwiches, die du hast, dann sind wir quitt.}
{1514}{}{Wenn das Raubtier seine Beute verlässt, kommen andere Raubtiere zum Festmahl. Wir können nur beten, dass unsere Götter uns beschützen.}
{1519}{}{[Er kneift nachdenklich die Augen zusammen] Was hast du vor, Fremder?}
{1523}{}{Das ist schlau, Fremder. Aber so etwas haben wir hier nicht.}
{1524}{}{[Er mustert dein Gesicht und nickt] Die Götter sagen mir, dass du Großes für die Cheyenne tun könntest. Also gut. Ich kann deinen Weg nur segnen, aber Gekek der Falke wird dir den Weg zeigen. Er bewacht den Eingang zum Lager.}
{1530}{}{Hast du Neuigkeiten, Fremder?}
{1531}{}{Die Räuber sind tot. Statt Moonshine ertrinken sie in ihrem eigenen Blut.}
{1560}{}{Die Götter warnen mich, dass die Gefahr noch besteht. Hast du nachgesehen? Vielleicht hat der Verschlinger manchen das Leben nach dem Tod geschenkt.}
{1562}{}{[Der Häuptling nickt und lächelt] Selbst die Himmel müssen die Schreie aus diesem dunklen Lager gehört haben! Du hast einem alten Mann Freude bereitet, Fremder. Die Cheyenne sind nun frei! Nicht einmal der Verschlinger kann es mit deiner Klugheit und Stärke aufnehmen. Unsere Legenden werden sich an dich als Bensy – Donner-Vogel erinnern!}
{1570}{}{Damit beginnt eine neue Ära für die Cheyenne! Wir werden uns immer an dich als Bensy – Donner-Vogel erinnern! Bitte, nimm dieses Amulett. Denk an unser Volk, wenn du es trägst, und möge es deinen Weg für immer erhellen.}
