{100}{}{Du siehst Omakaki, die Köchin.}

##############################################################
#               Îïèñàíèÿ
##############################################################

{101}{}{Sie ist eine der Köchinnen des Stammes. Sie bereitet gerade gebratenen Gecko zu.}
{102}{}{Sie ist eine der Köchinnen des Stammes. Sie bereitet gerade einen Gecko-Eintopf zu.}
{103}{}{Sie ist eine der Köchinnen des Stammes. Sie bereitet gerade geräucherte Echse zu.}
{104}{}{Sie ist eine der Köchinnen des Stammes. Sie bereitet gerade brahmin-Steak zu.}
{105}{}{Sie ist eine der Köchinnen des Stammes. Sie bereitet gerade einen Salat zu.}
{106}{}{Sie ist eine der Köchinnen des Stammes. Sie bereitet gerade ein Sandwich zu.}
{107}{}{Sie ist eine der Köchinnen des Stammes, aber gerade ruht sie sich nur aus.}

##############################################################
#               Ïëàâàşùèå ñîîáùåíèÿ
##############################################################

{108}{}{Wer geht hier?}
{109}{}{Man sagt, Fremder geht hier.}
{110}{}{Oh!}
{111}{}{Es besser im Schatten.}
{112}{}{Es am wichtigsten, dass Kinder mein Essen mögen.}
{113}{}{Jäger immer hungrig! Viel Essen und Wasser essen und trinken!}
{114}{}{Der ganze Stamm isst mein Essen. Es macht mich glücklich, wenn ich das sehe.}

{115}{}{Übler Geruch.}
{116}{}{Das nicht richtig!}
{117}{}{Ich nicht wollen, aber du zwingst mich.}
{118}{}{Himmlische Mutter könnte dir Manneskraft geben!}
{119}{}{Aus welchem Stamm du bist?}
{120}{}{Cheyenne werden sich für immer daran erinnern!}
{121}{}{Verräter.}

{122}{}{Hilfe!!!}

{123}{}{Hmpf. Ich nicht sprechen mit jemand wie dir.}
{124}{}{Fremder, das nicht essen!}
{125}{}{Was du essen?}
{126}{}{Wen du isst?}
{127}{}{Nein, Fremder! Das nicht essen! Das ist schmutzig!}
{128}{}{Uäh! Schmutz essen macht dich krank!}
{129}{}{Nein, das mir nicht gefallen. Geh weg.}

{130}{}{Ich dich nicht kennen.}
{131}{}{Ich dich nicht füttern.}
{132}{}{Du nicht Cheyenne.}
{133}{}{Oh ...}
{134}{}{Was du willst, Fremder?}
{135}{}{Ich kochen. Nur kochen.}
{136}{}{Sprich mit Ogima. Nicht mit mir sprechen.}
{137}{}{Ich nicht Ogima.}
{138}{}{Ogima nicht hier. Du gehen, mit Ogima sprechen.}
{139}{}{Ich nicht wissen. Ich nicht helfen.}

{140}{}{[Sie beobachtet dich in stummer Angst]}

##############################################################
#               Äèàëîã
##############################################################

#Íà÷àëî äèàëîãà:
{150}{}{Oh! Du willst mit mir sprechen?}

{151}{}{Kannst du mir ein bisschen über deinen Stamm erzählen?}
{152}{}{Ich bin nur neugierig. Was machst du hier?}
{153}{}{Komm her, Frau! Ich will deine saftigen „Äpfel“ fühlen!}
{154}{}{Ich habe Hunger. Fütter mich, Frau!}
{155}{}{Ich brauche Vorräte. Können wir handeln?}
{156}{}{Eigentlich habe ich es mir anders überlegt. Kümmere dich nicht um mich.}
{157}{}{[Geh.]}

#Ïğèç çà ğåéäåğîâ:
{158}{}{Oh! Du kommen, Belohnung holen! [sie lächelt] Du warten! Ich Belohnung machen. Viele, viele Essen! Reicht la-a-ange!}
{159}{}{Ausgezeichnet!}

#Øàíòàæ íà æğàòâó
{160}{}{Nein! Nicht mich anfassen! Nicht mich anfassen!!!}
{161}{}{Halt die Klappe, Schlampe! Ich habe Hunger! Fütter mich, oder ich bewässere die Felder mit dem Blut deines Stammes!}
{162}{}{Na gut, beruhig dich. Heute bin ich großzügig. [gehen]}
{163}{}{Ich geben Essen!!! Ich geben Essen!!! [sie sammelt hektisch so viel Essen auf, wie ihre zitternden Hände tragen können]}
{164}{}{Na also! So schnell solltest du jedes Mal sein. Denk dran: Unsere Bande weiß, was sie mit vorlauten Huren macht. [gehen]}

#Òğàõ:
{165}{}{HILFE!!! HILFE!!! HILFE!!!}
{166}{}{Du Miststück! Diese Jäger werden dir nicht helfen!!!}
{167}{}{Falsche Antwort, Hure. [zieht ihr weiter die Kleider aus] Wenn du dich wehrst, erschießt unsere Bande deine Männer, hängt deine Frauen und zwingt deine Kinder, bis zum Tod gegeneinander zu kämpfen. Und ich spieße dich oben auf dem Wasserturm auf, damit du jede Sekunde deiner Tat mit ansehen kannst.}
{168}{}{Na schön, verdammte Wilde. Du solltest dich geehrt fühlen ... [gehen]}
{169}{}{Abschaum! Niemand wird dich retten!}
{170}{}{[Schluchzt hysterisch und rührt sich nicht mehr]}
{171}{}{Braves Mädchen. [stößt sie zu Boden] Denk an deine Kinder und rühr dich nicht.}
{172}{}{JA!!! [zieht ihr die letzten Kleider aus]}
{173}{}{[Vergewaltigung.]}
{174}{}{::schluchz::}

#Íåóäà÷íûé øàíòàæ íà æğàòâó
{175}{}{Du unhöflich!}
{176}{}{Äh ... ich möchte noch etwas anderes fragen.}
{177}{}{Was für ein Miststück! Ich verschwinde!}
{178}{}{Gut, ich gehe.}

#Ğàçãîâîğ ïğî åäó
{180}{}{Oh! [sie lächelt] Ich kochen! Ich füttere ganzen Stamm. Essen gut, frisch und lecker. Alle lieben es!}
{181}{}{Ja, ich sehe, wie sich die Leute die Finger lecken! Kannst du mir etwas Proviant für unterwegs machen?}
{182}{}{Ja, ich sehe, wie sich die Leute die Finger lecken! Es riecht so gut, ich muss etwas probieren!}
{183}{}{Igitt! [spuckt] Dieses Essen stinkt wie Scheiße! Und sieht auch so aus! Und die Köchin – na ja, du verstehst schon!}

{184}{}{Du wollen Essen? Dann wir tauschen!}
{185}{}{[Handeln.]}

{186}{}{[Sie errötet und lächelt noch breiter] Ja, du wollen probieren? Okay, okay! Ich geben dir eine Mahlzeit!}
{187}{}{Im Ernst? Ich würde dein Essen liebend gern probieren!}
{188}{}{Tut mir leid, aber ich habe keine Zeit. Vielleicht später.}
{189}{}{[Sie macht dir ein Sandwich mit Gemüse, Fleisch und Bohnen für den Geschmack. Du steckst es für später in deinen Rucksack.]}
{190}{}{Vielen Dank! Ich möchte dich noch etwas anderes fragen.}
{191}{}{[Sie sieht aus, als würde sie gleich weinen. Du glaubst nicht, dass sie noch einmal mit dir sprechen wird.]}

{192}{}{Äh ... Ogima sagt, Fremde kriegen kein Essen umsonst.}
{193}{}{Dann lass uns handeln.}
{194}{}{Ogima ist nicht gierig, es macht ihm nichts aus. Es riecht so gut!}
{195}{}{Äh ... Ogima Häuptling. Er sagt ...}
{196}{}{Du scheinst nicht zu verstehen, was ich sage. Na ja, man sieht sich.}

##############################################################
#               Îòâåòû íà âîïğîñû
##############################################################

{200}{}{Ja. Ich geben Antwort.}

{201}{}{Reden wir über etwas anderes.}
{202}{}{Erzähl mir von dem Stamm.}
{203}{}{Erzähl mir von Black Cloud.}
{204}{}{Erzähl mir von euren Jägern.}
{205}{}{Nichts. Ich gehe.}

{206}{}{Stamm Familie. Leben gut. Jäger findet Essen. Ich macht Essen. Andere arbeitet auf Feldern. Kinder hilft überall. Niskigvan heilt. Avanigizhig spricht mit Geistern. Ogima Häuptling – hilft allen.}
{207}{}{Dieser Ogima klingt wichtig. Erzähl mir von ihm.}
{208}{}{Na gut. Tschüss.}
{209}{}{Ich möchte noch etwas anderes fragen.}
{210}{}{Ogima Black ist sehr wichtig. Er spricht mit Fremden. Er trifft wichtige Entscheidungen. Er beruhigt böse Leute. Ogima sehr gut, sehr weise.}
{211}{}{Böse Leute? Wer sind die?}
{212}{}{Oh ... [Sie schüttelt den Kopf.] Böse Leute. Schlafen in altem Gebäude in der Nähe. Nachts nehmen Essen. Vergewaltigen Frauen. Schlagen Männer. Sie sehr, sehr böse.}
{213}{}{Beschützt euch denn niemand? Was ist mit euren Jägern?}
{214}{}{Jäger bringt frisches Fleisch. Jäger findet Tiere, dann BOOM! [Sie schlägt eine Faust in ihre Handfläche.] Dann bringt er mir totes Tier. Ich kocht Tier, macht Essen. Jeder braucht Essen. Macht Körper stark. Jäger isst Essen, wird stark, geht wieder Tiere jagen.}
{215}{}{Apropos Essen: Kann ich dir etwas abkaufen oder eintauschen?}

##############################################################
#               Ñîîáùåíèÿ íà èíôîîêíå
##############################################################

{300}{}{Du erhältst 200 Erfahrungspunkte für einen kleinen Überfall.}
{301}{}{Die Köchin ist völlig hysterisch. Du hast ihr zu viel Angst gemacht.}
{302}{}{Du erhältst 500 Erfahrungspunkte dafür, dass du eine harmlose Frau angegriffen hast.}

##############################################################
#               Êğèêè ïğè êğàæå êà÷àíà êàïóñòû 
##############################################################

{310}{}{Ich Essen! Nicht anfassen!}
{311}{}{Ich warnen!}
{312}{}{DIEB! Dieb, Dieb, Dieb!!!}

##############################################################
#               Female character
##############################################################

{1156}{}{Eigentlich habe ich es mir anders überlegt. Kümmere dich nicht um mich.}
{1190}{}{Vielen Dank! Ich möchte dich noch etwas anderes fragen.}
