{100}{}{Ein Wachposten.}
{101}{}{Du siehst einen Raider auf Patrouille.}

# Когда поймал ГГ: 
{110}{}{Keine Bewegung! Beweg dich, und du bist tot!}
{111}{}{Hey, hey! Ganz ruhig! Ich bewege mich nicht, siehst du?}
{112}{}{Wenn du mich anfasst, bekommst du deine Hand nicht zurьck.}
{113}{}{Und ich dachte schon, das wird langweilig. Mal sehen, was der Boss zu dir sagt...}
{114}{}{[Der Wachmann legt dir Handschellen an und bringt dich zu einem zweistцckigen Gebдude.]}

# Когда подбегает, чтобы арестовать:
{115}{}{Halt, keinen Schritt weiter!}
{116}{}{Beweg dich, und du bist tot!}
{117}{}{Halt, du Penner!}
{118}{}{Nicht bewegen!}
{119}{}{Ich sagte, nicht bewegen!}
{120}{}{Du kommst mir nicht davon!}
{121}{}{Du gehцrst mir!}

#Если ГГ в одежде рейдера:
{130}{}{Der Wachposten hat dich bemerkt, aber deine Verkleidung nicht durchschaut.}
{131}{}{Mold, bist du das?}
{132}{}{Hey, Moment mal! Wer zum Teufel bist du?}
{133}{}{Hey, du mit der Jacke! Wer bist du?}
{134}{}{Wer ist da? Mold, bist du das?}
{135}{}{Gehst du wieder kotzen, was, Mold? ReiЯ dich zusammen, Mann.}

# Когда враждебен, видит и нападает:
{200}{}{Hey, du!}
{201}{}{Macht diese Schlampe fertig!}
{202}{}{Ich mach dich fertig!}
{203}{}{Willst du ausgeweidet oder gehдutet werden?!}
{204}{}{Tanzen wir, Baby!}
{205}{}{Zeit, dich zum Heulen zu bringen.}
{206}{}{Halt still, wдhrend ich dich ausweide, ja?}

# Разговаривает сам с собой:
{207}{}{Da ist niemand...}
{208}{}{Das ist langweilig.}
{209}{}{Ich kann es nicht mehr ertragen, im Kreis zu laufen...}
{210}{}{Geht diese Patrouille jemals zu Ende?}
{211}{}{Warum mache ich das ьberhaupt?}

# Когда не враждебен: 
{212}{}{Na, hallo.}
{213}{}{Alles ruhig.}
{214}{}{Niemanden gesehen.}
{215}{}{Hier kommt keiner durch!}
{216}{}{Eigentlich nichts zu sagen.}
{217}{}{Ich halte Wache.}
{218}{}{Mann, ist das langweilig...}

{219}{}{Oh! Du bist es!}
{220}{}{Alles ruhig. Kein Grund zur Sorge.}
{221}{}{Niemanden gesehen.}
{222}{}{An mir kommt keiner vorbei!}
{223}{}{Nichts zu melden.}
{224}{}{Wie geht's dem Boss?}
{225}{}{Der Boss scheint dich zu mцgen. Respekt...}

#Female character
{1110}{}{Keine Bewegung! Beweg dich, und du bist tot!}