{100}{}{Du siehst einen Ausguck.}
{101}{}{Du siehst einen Raider auf Patrouille.}

# Êîãäà ïîäáåãàåò, ÷òîáû àğåñòîâàòü:
{110}{}{Halt, keinen Schritt weiter!}
{111}{}{Beweg dich, und du bist tot!}
{112}{}{Halt, du Penner!}
{113}{}{Nicht bewegen!}
{114}{}{Ich sagte, nicht bewegen!}
{115}{}{Du kommst mir nicht davon!}
{116}{}{Du gehörst mir!}

#Åñëè ÃÃ â îäåæäå ğåéäåğà:
{130}{}{Der Wachposten hat dich bemerkt, aber deine Verkleidung nicht durchschaut.}
{131}{}{Mold, bist du das?}
{132}{}{Hey, Moment mal! Wer zum Teufel bist du?}
{133}{}{Hey, du mit der Jacke! Wer bist du?}
{134}{}{Wer ist da? Mold, bist du das?}
{135}{}{Gehst du wieder kotzen, was, Mold? Reiß dich zusammen, Mann.}

#Êîãäà ïîéìàë ÃÃ:
{150}{}{Keine Bewegung! Beweg dich, und du bist tot!}
{151}{}{Hey, hey! Ganz ruhig! Ich bewege mich nicht, siehst du?}
{152}{}{Wenn du mich anfasst, bekommst du deine Hand nicht zurück.}
{153}{}{Und ich dachte schon, das wird langweilig. Mal sehen, was der Boss zu dir sagt...}
{154}{}{Na schön, bring mich zu eurem Boss. Ich werde nicht kämpfen.}
{155}{}{[Greif den Raider an]}
{156}{}{Halt die Klappe! Wenn du irgendwas versuchst, bleibt von dir nicht genug übrig, um dich zu begraben.}
{157}{}{Na schön, ich bewege mich nicht.}
{158}{}{Nein, DU hältst die Klappe!}
{159}{}{}

#Êîãäà Ïëåñåíü ñäîõ:
{160}{}{Großartig.}
{161}{}{Wusstest du, dass in den Ruinen gegenüber vom Stützpunkt eine Leiche liegt?}
{162}{}{Wir sehen uns.}
{163}{}{Ja, das ist Mold. Er hat sich eine Überdosis verpasst, also haben wir ihn rausgeworfen, bevor er anfing zu stinken. Das Seltsamste ist, dass wir nicht rauskriegen, woher er das Zeug hatte. Fatso schwört, er hätte ihn davon abgehalten.}
{164}{}{Verstehe ...}

# Êîãäà âğàæäåáåí, âèäèò è íàïàäàåò:
{200}{}{Hey, du!}
{201}{}{Macht diese Schlampe fertig!}
{202}{}{Ich mach dich fertig!}
{203}{}{Willst du ausgeweidet oder gehäutet werden?!}
{204}{}{Tanzen wir, Baby!}
{205}{}{Zeit, dich zum Heulen zu bringen.}
{206}{}{Halt still, während ich dich ausweide, ja?}

# Ğàçãîâàğèâàåò ñàì ñ ñîáîé:
{207}{}{Niemand...}
{208}{}{Das ist langweilig.}
{209}{}{Ich kann es nicht mehr ertragen, im Kreis zu laufen...}
{210}{}{Geht diese Patrouille jemals zu Ende?}
{211}{}{Warum mache ich das überhaupt?}

# Êîãäà íå âğàæäåáåí: 
{212}{}{Großartig.}
{213}{}{Alles ruhig.}
{214}{}{Niemanden gesehen.}
{215}{}{Hier kommt keiner durch!}
{216}{}{Eigentlich nichts zu sagen.}
{217}{}{Ich halte Wache.}
