{100}{}{Du siehst einen Hirten.}
{101}{}{Du siehst einen Hirten vom Stamm der Cheyenne.}

#Ïåğâàÿ âåòêà
{200}{}{Hah!}
{201}{}{Hallo. Wer bist du, und was machst du hier?}
{202}{}{}
{203}{}{Lass uns handeln.}
{204}{}{Ich bin nur auf der Durchreise.}
{205}{}{Wie viel noch mal für diese glänzende Metallkiste?}

{207}{}{Du hast blindlings einen scheinbar nutzlosen Tand gekauft, in der vagen Hoffnung, dass er eines Tages nützlich sein könnte. Du kommst dir wie ein echter Spieler vor.}

#Ïåğâûé âîïğîñ, êòî òàêîâ
{210}{}{Ich sein Hirte! Ich lebe hier, auf Feld. Ich passe auf Pflanzen auf und führe Vieh. Ich bin allein, aber das gut für mich sein.}
{211}{}{Aha. Was ist das für ein großes Metallding mitten auf dem Feld?}
{212}{}{Du passt also auf das ganze Feld auf, hm? Du musst hier draußen eine Menge interessanter Dinge gefunden haben. Lust zu handeln? Schade, dass ich keine Glasperlen dabei habe ...}
{213}{}{Ein Hirte ohne Schafe, hm? Ich sollte gehen.}
{214}{}{Dieser große Eimer voll Giftfeuer! Er vom Himmel gefallen und ausgelaufen. Es brannte wunderschön, aber nur ich habe es gesehen. Dann ... wuchsen Pflanzen drum herum, die beißen. Hmm.}
{215}{}{Vom Himmel gefallen? Wie interessant! Ich sehe es mir aus der Nähe an.}
{216}{}{Äh, warte, Fremder! Geh da nicht hin. Der Dreck verbrennt die Füße!}
{217}{}{Ich behalte das im Hinterkopf.}

#Áàğòåğ
{218}{}{Mmm. Ich haben Schrott. Ich tausche Schrott.}
{219}{}{Tauschen wir.}
{220}{}{Ich komme später wieder.}

#Áàğòåğ - òîñòåğ
{221}{}{Mmm. Ich habe etwas Schrott ... Ein paar Sachen. Und ... etwas Glänzendes!}
{222}{}{Was ist es? Zeigst du es mir?}
{223}{}{Glänzend? Das muss ich sehen!}
{224}{}{Sieh mal! [Er hält eine Metallkiste hin, auf der ein buntes Tier mit großen Ohren abgebildet ist. Du hast keine Ahnung, was es ist, aber es sieht nach einem Gerät aus der Vorkriegszeit aus. Du untersuchst ein paar Knöpfe, in der Hoffnung, dass der Hirte nicht auf die Idee gekommen ist, sie zu drücken.]}
{225}{}{Sehr verlockend. Was willst du dafür?!}
{226}{}{Geld! Viel Geld! Tauschen gegen ... Hmm ...}
{227}{}{Abgemacht. Hier ist das Geld.}
{228}{}{Tut mir leid, so viel habe ich nicht. Vielleicht später.}
{229}{}{Gut!}
{230}{}{Reden wir über etwas anderes.}

#Áàğòåğ - êóğòêà
{233}{}{Wie wäre es mit einer Lederjacke? Sie schützt vor Sonne und Wind.}
{234}{}{Du willst Kleidung? Es muss unangenehm sein, halbnackt herumzulaufen.}
{235}{}{Nee. Ich ist wohl in eigene Haut.}

{237}{}{Es ist einfacher, dich einfach umzubringen! Deinen Schrott kannst du den Würmern verkaufen, Arschloch!}

{238}{}{Ooh! [Er reibt sich die Hände] Das will ich! Abgemacht!}
{239}{}{Gib mir eine Sekunde, dann ziehe ich sie aus.}
{240}{}{Also, woran erinnere ich dich? Was brauchst du?}

{241}{}{Ooh! Das will ich! Abgemacht! [Er nimmt die Jacke, streicht mit einem zufriedenen Nicken über das Leder und gibt dir das Gerät]}

#Ğàäèîñòàíöèÿ
{250}{}{Ich suche einen Radiosender irgendwo hier in der Gegend. Du weißt wahrscheinlich, wo er ist. Kannst du es mir zeigen?}
{251}{}{Hmm ... Nee. Häuptling wird böse, schimpft. Schlecht.}
{252}{}{Ja, bei meinem Ruf wäre keiner erfreut zu hören, dass du mir geholfen hast. Tja.}
{253}{}{Reden wir über etwas anderes.}
{254}{}{Er wird es nicht herausfinden. Ich verspreche es. Du kannst mir vertrauen.}
{255}{}{Hmm. [Er schaut sich um] Okay. Du bist gute Leute. Ich zeig dir.}
{256}{}{Großartig. Bring mich hin.}
{257}{}{Du kannst es dir leicht machen, oder meine Gang kann dafür sorgen, dass du es auf die harte Tour lernst.}
{258}{}{Äh - ! Nein, ich zeig's, ich zeig's!}
{259}{}{Es ist wichtig. Ich muss diesen Sender finden, um etwas über meine Vergangenheit herauszufinden. Bitte, kannst du mir nicht helfen? Ich weiß, dass du ein guter Mann bist.}
{260}{}{Hmmmm ... Schöne Worte. Okay. Ich zeig dir.}
{261}{}{Was, wenn ich dir diesen angespitzten Speer gebe?}
{262}{}{Was, wenn ich dir diese Lederjacke gebe?}
{263}{}{Was, wenn ich dir diesen Viehtreiber gebe?}
{264}{}{[Er nickt und nimmt ihn] Ich zeig dir.}

#Ïîëó÷åíèå êîïüÿ
{350}{}{Kann ich mir deinen Speer leihen? Ich brauche ihn!}

{351}{}{Nein! Du nehmen Speer und weglaufen. Ich Speer für immer verlieren!}
{352}{}{Nein, nein! Ich bringe ihn zurück, versprochen!}
{353}{}{Ogima hat mich gebeten, die gefährlichen Pflanzen zu töten. Dafür brauche ich den Speer!}
{354}{}{Gib mir jetzt den verdammten Speer!}
{355}{}{Findest du nicht, dass du egoistisch bist?}
{356}{}{Na gut, na gut. Ich komm auch ohne deine Hilfe klar.}

{357}{}{[Er knirscht mit den Zähnen und umklammert seinen Speer noch fester.]}
{358}{}{[Pack den Speer und zieh ihn ihm weg.]}
{359}{}{Na gut, wie du willst.}
{360}{}{[Du packst den Speer und ziehst daran, aber der Hirte stemmt die Füße in den Boden und zieht mit einem angestrengten Grunzen zurück.]}
{361}{}{Hrrngg! [stärker ziehen]}
{362}{}{Na gut, behalt den verdammten Speer! [loslassen]}
{363}{}{[Der Hirte fällt auf den Rücken] Uff!}
{364}{}{Ha! Geschieht dir recht. [gehen]}
{365}{}{[Dieser Hirte ist ziemlich stark! Er zieht am Speer, seine Adern an Armen und Hals treten so stark hervor, dass sie jeden Moment zu platzen scheinen.]}
{366}{}{HRRRAAAGGHHH!! [mit aller Kraft ziehen]}
{367}{}{[Plötzlich den Speer loslassen.]}
{368}{}{[Dem Hirten den Speer entreißen, während er benommen ist] Aha!}
{369}{}{Ha! Und jetzt halt den Mund ... }
{370}{}{[Der Hirte überwältigt dich, reißt den Speer zurück und schleudert dich zu Boden] Ha! Ich stark! Fremder schwach!}
{371}{}{Weißt du, mit wem du dich anlegst?! Komm her, dann reiß ich dir die verdammten Arme aus!}
{372}{}{Na gut, na gut. Kein Streit.}
{373}{}{Ha-ha-ha! Fremder tut böse, aber nein! Ich seh's in deinen Augen!}
{374}{}{Nein, ich nicht egoistisch! Du gierig!}
{375}{}{Ich habe dich höflich gebeten, mir deinen Speer nur für kurze Zeit zu leihen, und nicht einmal das wolltest du. DU bist gierig.}
{376}{}{NEIN!}
{377}{}{JA!}
{378}{}{Nein, Fremder ist ... ist ... Nein, nein! Ich wollte Speer geben!}
{379}{}{Siehst du? Jemand bittet dich um Hilfe, und du denkst nur an dich selbst. Der Stamm wird sehr enttäuscht sein, wenn ich es ihm erzähle!}
{380}{}{Ahhh, nein! Fremder nicht erzählen! Nimm Speer, nimm ihn! [Er wirft den Speer auf den Boden und tritt zurück, während er sich hysterisch an den Kopf fasst]}
{381}{}{Gute Wahl, Kumpel.}
{382}{}{Ich trau Fremden nicht!}
{383}{}{Warum versuchst du's nicht? Vielleicht ist die Welt nicht so schlimm, wie du denkst.}
{384}{}{Ha! Fremde bringen dem Stamm Leid. Ogima sagt, der Stamm soll Fremde meiden!}
{385}{}{Na ja, nicht jeder, oder? Ich bin nicht wie die anderen!}
{386}{}{Nein, die Geister sagen etwas anderes.}
{387}{}{Hmm ... Die Geister sind sich bei dir nicht sicher. Seltsam.}
{388}{}{Das heißt, du hast die Chance, einem guten Menschen zu helfen. Stimmt's?}
{389}{}{Hmm ... Ogima sagt, man muss guten Menschen helfen. Hier, nimm den Speer.}
{390}{}{Danke, Freund. Ich werde gut darauf aufpassen.}
{391}{}{Ha! Du bist so leicht reinzulegen!}
{392}{}{Danke. Ich bringe ihn zurück, wenn ich fertig bin.}
{393}{}{Nein. Ich brauche Speer, um Muh-Kühe zu hüten. Stamm braucht ihn.}
{394}{}{Du sagst, du tötest Pflanzen, aber hast keinen Speer? [Er schüttelt den Kopf] Dumm.}
{395}{}{Kann ich mir also den Speer leihen?}
{396}{}{Du musst versprechen, dass du ihn zurückbringst!}
{397}{}{Äh ... Ich werd's versuchen.}
{398}{}{Versprechen!}
{399}{}{Ich schwöre feierlich, dass ich den Speer zurückbringe, nachdem ich die gefährlichen Pflanzen getötet habe. Möge ich verdammt sein, wenn nicht.}
{400}{}{Das kann ich nicht versprechen, tut mir leid.}
{401}{}{Dann behalte ich Speer.}
{402}{}{[Der Hirte überreicht dir feierlich den Speer, als wäre er eine heilige Reliquie.] Möge seine Klinge auf dem Pfad des Lichts immer nach vorn zeigen.}
{403}{}{Äh, ja, klar. Ich bin bald zurück.}
{404}{}{Ha! Was für ein Idiot!}
{405}{}{Mann, was für ein Aufwand. Willst du wirklich keinen Vertrag oder so aufsetzen?}
{406}{}{Danke. Ich bringe ihn zurück, wenn ich fertig bin.}
{407}{}{Nein. Stamm sagt, Fremde sind schlecht.}
{408}{}{Hier ist dein Speer.}
{409}{}{[Die Augen des Hirten weiten sich vor Staunen.]}
{410}{}{Ja, ich gebe ihn zurück. Ich bin ehrlich.}
{411}{}{Pff, sieh dir dein Gesicht an! Nein, war nur ein Scherz, jetzt gehört sie mir.}
{412}{}{Außenseiter nicht stehlen? Außenseiter armen Hirten nicht vergessen?}
{413}{}{Nimm einfach den verdammten Speer!}
{414}{}{Ja, genau. Ich will gut sein.}
{415}{}{Nein, Außenseiter nur Scherz machen. Ich behalte ihn.}
{416}{}{[Der Hirte nimmt den Speer und senkt respektvoll den Kopf] Außenseiter tut richtige Sache.}
{417}{}{Ja, ich bin eben so einer. Bis dann.}
{418}{}{[Der Hirte schiebt dir den Speer hin] Außenseiter ist gut. Außenseiter braucht ihn. Nimm!}
{419}{}{Danke, Freund! Ich brauche ihn wirklich.}
{420}{}{Der Hirte hat dir seinen Speer geschenkt. Offenbar vertraut er dir.}

#Ïî÷èíêà ìîñòà
{450}{}{Ich muss, dass du etwas Schweres für mich trägst.}
{451}{}{Nein. Ich nicht schwere Sachen tragen wollen.}
{452}{}{Ich habe nicht gefragt. Das ist ein Befehl!}
{453}{}{Ich will die Brücke reparieren. Ist es dir egal, dem Stamm zu helfen?}
{454}{}{Ach ja? Was, wenn ich deinem Häuptling erzähle, dass du die brahmin mit dem grünen Zeug auf dem Feld gefüttert hast?}
{455}{}{Vergiss es. Ich will dich etwas anderes fragen.}
{456}{}{Na gut, dann mache ich es eben selbst.}

{457}{}{Was?! Ich nicht Moo-Moos mit grünem Zeug füttern! Nein!}
{458}{}{Oh, das weiß ich. Aber der Häuptling nicht. Verstehst du, worauf ich hinauswill?}
{459}{}{Grr... Böser Außenseiter! Alle Außenseiter böse! Weg!}
{460}{}{Ich warne dich zum letzten Mal – hilf mir mit den Brettern, oder ich hetze den ganzen Stamm gegen dich auf! Ich bin mir ziemlich sicher, dass sie mir auch glauben – bestimmt gibt es einen Grund, warum du ganz allein lebst.}
{461}{}{Na gut, wie auch immer.}
{462}{}{[Er ist nervös] N-nein! Außenseiter falsch! Nur... ich helfe trotzdem. Ich stark. Kein Problem.}
{463}{}{Beweg deinen Arsch, endlich!}
{464}{}{Gut! An die Arbeit!}
{465}{}{Vielleicht brauche ich deine Hilfe doch nicht.}

{466}{}{[Er schlägt sich auf die Brust und richtet sich auf] Ich sein KEIN SKLAVE!}
{467}{}{Oh, sieh dir den großen Kerl an!}
{468}{}{[Er zögert einen Moment unentschlossen, bevor er in Richtung der Basis von Big Louie blickt] Ich... nicht wollen Ärger. Was ich tragen?}
{469}{}{Bring die Bretter zur Brücke. Aber dalli!}
{470}{}{Nichts. Ich schaffe das auch ohne dich.}

{471}{}{Ich trau Außenseitern nicht. Außenseiter tun nie etwas, nur um zu helfen.}
{472}{}{Na gut. Vielleicht kann ich dich davon überzeugen, dass ich anders bin.}
{473}{}{Außenseiter will helfen? Hmm... Außenseiter ist guter Mensch. Ich helfen.}
{474}{}{Großartig! Wir müssen die Bretter zur Brücke bringen...}
{475}{}{Ich glaube, ich schaffe das auch ohne dich. Ruh dich aus.}
{476}{}{Mit der Hilfe des Hirten baust du aus den Holzbrettern eine Zugbrücke.}
{477}{}{Die Brücke ist fertig.}

#Female character
{1204}{}{Ich bin nur auf der Durchreise.}
{1212}{}{Du passt also auf das ganze Feld auf, hm? Du musst hier draußen eine Menge interessanter Dinge gefunden haben. Lust zu handeln? Schade, dass ich keine Glasperlen dabei habe ...}
{1227}{}{Abgemacht. Hier ist das Geld.}
{1375}{}{Ich habe dich höflich gebeten, mir deinen Speer nur für kurze Zeit zu leihen, und nicht einmal das wolltest du. DU bist gierig.}
{1385}{}{Na ja, nicht jeder, oder? Ich bin nicht wie die anderen!}
{1410}{}{Ja, ich gebe ihn zurück. Ich bin ehrlich.}
{1414}{}{Ja, genau. Ich will gut sein.}
{1417}{}{Ja, ich bin eben so eine. Wir sehen uns.}
