{100}{}{Du siehst Mold.}

{101}{}{Du siehst einen dreckigen Junkie, den man Mold nennt, vermutlich wegen seines Gestanks.}


#Ïëàâàşùèå ôğàçêè ïåğåä ïğîïîåì:

{102}{}{Ach, v-ver-dammt ... Ich z-zittere ... }

{103}{}{Ich brauche mehr ... }

{104}{}{Wahrscheinlich ... Oder vielleicht auch nicht ... }

{105}{}{Ich brauche es dringend ... }

{106}{}{Ich glaube, ich habe mich übergeben, nur ein bisschen.}

{107}{}{::stöhn::}

{108}{}{::ächz::}

{109}{}{Verdammt ... }

{110}{}{Glaubst du, sie suchen nach mir?}

{111}{}{Hau ab!}

{112}{}{Scheiß drauf! Scheiß auf alles!}

{113}{}{Ich brauche nur einen Drink, um mich zu beruhigen ... }

{114}{}{Ein Bier wäre jetzt toll.}

{115}{}{Ich glaube, ich sterbe!}

{116}{}{Ich brauche was zu trinken ... ganz egal was! Sogar brahmin-Pisse, irgendwas!}

{117}{}{Wer? Was? Wo? Warum?!}

{118}{}{Du bist ein Handtuch!}

{119}{}{[Zeigt auf dich] Du bist gefeuert!}

{120}{}{So durstig ... }

{121}{}{Ich will leben ... }

{122}{}{Ich will sterben ... }

{123}{}{Wer ist hier im Arsch?! DU bist im Arsch!}

{124}{}{Ich brauche nur einen Schluck! Bitte, hab ein Herz!}

{125}{}{Nur ein Glas ... }

{126}{}{Wenn du mir nichts zu trinken holst, dann ... Ich ... Ach, vergiss es.}

{127}{}{Ich meine es ernst, ich brauche das wirklich. Besorg mir Schnaps, oder ich verrecke hier!}

{128}{}{Wer zum Teufel? ... Ach, warum sollte mich das kümmern ... }

{129}{}{Bitte! Eine halbe Flasche!}

{130}{}{Ich verlange doch nicht viel! Der Entzug bringt mich noch um!}



# Êîãäà ïğèìåíåí íà íåì íå òîò ïğåäìåò:

{131}{}{Leck mich!}

{132}{}{Fahr zur Hölle!}

{133}{}{Ich werde dich ... }

{134}{}{Lass mich los!}

{135}{}{Was zur Hölle ist das für eine Scheiße?}

{136}{}{Was hast du vor?}

{137}{}{Hey, halt Abstand!}

{138}{}{Das habe ich nie verlangt!}

{139}{}{Du willst mich bescheißen, was?!}



# Êîãäà ïğèìåíî áóõëî: 

{140}{}{Whoa, was zum... }

{141}{}{Verdammt... }

{142}{}{Oh! Oh! Ohhhh! Jetzt kommt's!!!}

{143}{}{Das... ist nicht richtig... }



# Êîãäà óïàë ïîñëå ïğèìåíåíèÿ áóõëà: 

{144}{}{Ich bin raus, Mann. Ganz weit weg... }

{145}{}{::schnarch::}

{146}{}{Entweder hab ich mir gerade in die Hose geschissen oder... Nein, das war's schon.}

{147}{}{::bewusstlos::}

{148}{}{::zzzzzz::}

{149}{}{Vielleicht bemerkt ja niemand den Gestank... }



# Äèàëîã

{150}{}{Hey, dein Fusel war echt übles Zeug! Ich hab Scheiße ausgekotzt, die ich nie gegessen hatte! Kannst du mir was Anständiges besorgen? Ich fang schon an zu zittern... }

{151}{}{Im Nebenraum steht eine Destille. Kannst du dir nicht selbst was holen?}

{152}{}{Das ist mir wirklich völlig egal. Tschüss.}

{153}{}{Du solltest nicht so viel trinken.}


{154}{}{Fatso meinte, er hat genug von mir. Er gibt mir nichts mehr. Und sonst hilft mir auch keiner, also... Bitte? Vielleicht teilen sie mit dir... }

{155}{}{Na gut, ich besorge dir etwas zu trinken. Versuch bis dahin nicht zu sterben.}


{156}{}{Hast du den Schnaps?}

{157}{}{Hier, ein Bier.}

{158}{}{Hier, etwas Schnaps.}

{159}{}{Hier, etwas Rotgut.}

{160}{}{Hier, ein Bloody Mary.}

{161}{}{Ich wusste, dass ich etwas vergessen hatte. Bin gleich wieder da.}


{162}{}{Verdammt! Danke, Freund... [er kippt den Alkohol gierig hinunter und beendet es mit einem lauten Rülpser] Ohhhh, das tut gut... Mann, du... Ich bin einfach... Wow! Hör zu, in dieser Gang ist das, weißt du... kompliziert. Du bist neu, aber du wirst es verstehen. Hey, hör mal... Kannst du mir noch einen besorgen? Ich bin ziemlich im Arsch... Ich brauche etwas von Fatsos Heilpulver. Es nimmt einfach den Schmerz, weißt du? Kannst du mir etwas besorgen? Ich sterbe hier... }
{163}{}{Du erhältst Erfahrung für die „Lieferung“.}

{164}{}{Ich versuch's.}


{165}{}{Ich geh hier langsam kaputt ... Ich brauche Medizin ... So Heilkräuter, Mann ... Ohhh ... }

{166}{}{Hier, bitte. Werd wieder gesund.}

{167}{}{Na dann viel Glück.}
{168}{}{Meinst du das ernst? Oh, mein Schutzengel! Danke! Danke! Komm her, lass dich umarmen!}

{169}{}{Du hast dem Junkie den nächsten Schuss besorgt.}


{170}{}{[Er krampft auf dem Boden, die Augen weit aufgerissen und an die Decke gerichtet] Ah, v-v-verdammt! Es ist schlimm! Ich brauche ... ich brauche einen Schuss ... Acid, Schmerzmittel, Anti-Raucher-Chemikalien, egal was! H-h-hilf mir einfach!}

{171}{}{}

{172}{}{Halt durch! Ich gebe dir, was du brauchst!}

{173}{}{Sehe ich für dich wie ein Dealer aus? Warum sollte ich für deinen Entzug verantwortlich sein?}


{174}{}{[Er sieht ein wenig besser aus.]}

{175}{}{[Lass ihn auf dem Boden liegen.]}


{176}{}{[Er schluchzt] Du herzloses Stück ... Ich sterbe hier! Hier, nimm das, gib mir einfach den Stoff, bitte ... [er gibt dir sein letztes Geld]}

{177}{}{Du erhältst 250 Erfahrungspunkte dafür, dass du dem Junkie den nächsten Schuss besorgt hast.}


{178}{}{[Sein ganzer Körper ist steif, seine Zähne sind zusammengebissen und Speichel läuft ihm aus den Mundwinkeln] Pssss ... Psssychooo ... B-b-besorg mir Pssssychooooo ... }

{179}{}{[Spritze ihm Psycho.]}

{180}{}{Was bin ich, ein Heiliger? [Durchsuche seine Kleidung nach Wertsachen.]}

{181}{}{[Trotz des Gestanks durchsuchst du den Junkie gründlich, findest aber nur eine alte Pistole, die du als Bezahlung für deine Dienste nimmst.]}

{182}{}{[Du suchst nach einer unverletzten Vene am durchlöcherten Arm des Junkies und triffst schließlich mit der Nadel eine. Molds Krämpfe hören auf, aber er bleibt bewusstlos.]}

{183}{}{[Lass ihn seinen Rausch ausschlafen.]}


{185}{}{[Schieb ihm Anti-Raucher-Chemikalien in den Mund.]}

{186}{}{[Schieb ihm Schmerzmittel in den Mund.]}



# Êîãäà âğàæäåáåí, âèäèò è íàïàäàåò:

{200}{}{Hey, du!}

{201}{}{Erledige den Wichser!}

{202}{}{Machen wir endlich Schluss damit, ich will mir was spritzen!}

{203}{}{Stirb! Stirb!!!}

{204}{}{Tanzen wir, Kleine!}

{205}{}{Gott wird dich richten! Oder vielleicht ich!}

{206}{}{Sei ein guter Verlierer und halt still!}

{207}{}{Du hältst dich wohl für ganz schön hart?!}

{208}{}{Wir erledigen sie!}

{209}{}{Das lässt mich meine Entzugserscheinungen fast vergessen!}



# Female character

{1162}{}{Verdammt! Danke, Lady... [er kippt das Getränk gierig hinunter und stößt zum Schluss laut auf] Ohhhh, das tut gut... Mann, du... Ich bin einfach... Wow! Hör zu, bei dieser Gang ist das, na ja... kompliziert. Du bist neu, aber du wirst es verstehen. Hey, hör mal... Kannst du mir noch einen besorgen? Ich bin ziemlich fertig... Ich brauche etwas von Fatsos Heilpulver. Das nimmt einfach den Schmerz, weißt du? Könntest du mir was besorgen? Ich sterbe hier... }

{1170}{}{[Er krampft auf dem Boden, die Augen weit aufgerissen und an die Decke gerichtet] Ah, v-v-verdammt! Es ist schlimm! Ich brauche ... ich brauche einen Schuss ... Acid, Schmerzmittel, Anti-Raucher-Chemikalien, egal was! H-h-hilf mir einfach!}