{100}{}{Du siehst einen Raider.}
{101}{}{Du siehst einen ungewaschenen Schläger mit finsterer Miene.}

#Êîãäà âğàæäåáåí, âèäèò è íàïàäàåò:
{200}{}{Hey, du!}
{201}{}{Tötet den Wichser!}
{202}{}{Mach's nicht schnell! Ich will sehen, wie er sich windet!}
{203}{}{Zwanzig Dollar, dass ich einen Kopfschuss hinkriege!}
{204}{}{Na los, tanzen wir!}
{205}{}{Du solltest besser anfangen, dein Grab zu schaufeln, du Stück brahmin Scheiße!}
{206}{}{Halt still! Bringen wir's hinter uns!}
{207}{}{Komm her! Ich fick dich, wie ich deine Mutter gefickt habe!}
{208}{}{TÖTET SIE ALLE!}

#Êîãäà íå âğàæäåáåí:
{210}{}{::spit::}
{211}{}{Ich suche keine Freunde.}
{212}{}{Verpiss dich.}
{213}{}{Mir ist langweilig. Hey, du! Unterhalt mich.}
{214}{}{Glotzt du mich an? Dann mach dich besser vom Acker.}
{215}{}{Deine Stiefel gefallen mir. Zieh sie aus.}
{216}{}{Big Daddy sagt, du bist in Ordnung. Vorerst.}

{217}{}{Hey. Was geht?}
{218}{}{Ich mach mein eigenes Ding.}
{219}{}{Wenn du eine Schlägerei siehst, ruf mich.}

{220}{}{Du bist ganz schön dicke mit dem Boss, was?}
{221}{}{Wie geht's dem Boss? Alles gut?}
{222}{}{Alles ruhig. Der Boss kann beruhigt schlafen.}
{223}{}{Wenn du was brauchst, frag einfach.}
{224}{}{Der Boss mag dich wirklich. Ich frage mich, wie sich das anfühlt...}
