{100}{}{Ein rasender Raider.}
{101}{}{Das ist dein erster Gegner im Ring der Raider.}

{102}{}{AHHH!!! SÜSSER SCHMERZ!}
{103}{}{Ist das alles, was du draufhast?!}
{104}{}{Du bist meine Schlampe! Du bist meine Schlampe!}
{105}{}{Ich fick dich so, wie ich letzte Nacht deine Mutter gefickt habe!}
{106}{}{Lass es bluten! HRAAUGH!!!}
{107}{}{Haltet mir jemand dieses Stück Scheiße fest! Ich mach's kurz!}
{108}{}{Du bist doch nicht krank, oder, Junge? DENN ICH WERDE DEINE LEBER FRESSEN UND SIE MIT DEINEM BLUT HINUNTERSPÜLEN!}
{109}{}{Verdammt...}
{110}{}{WIR SEHEN UNS IN DER HÖLLE!!!}

{113}{}{Mach dich bereit, Schlampe! Das wird mir Spaß machen!}
{114}{}{Ich zerreiß dich in Stücke!}

#Èìïîğò, îáùåå: ëîâóøêè:

{200}{}{Hey! Was zur Hölle machst du da drüben?!}
{201}{}{Du wurdest entdeckt.}

{202}{}{Mami! Mami!}
{203}{}{Husch!}
{204}{}{Schneller!}
{205}{}{Hilfe!!!}
{206}{}{Aaaah!!!}
{207}{}{Oh Scheiße, eine Bombe!}
{208}{}{Verdammter Abschaum!}

{210}{}{Die Kinder laufen beim Anblick deiner zweifelhaften Krimskrams davon.}
#Æåíñêèå ğåïëèêè
{1108}{}{Du bist doch nicht krank, oder, Mädchen? DENN ICH WERDE DEINE LEBER FRESSEN UND SIE MIT DEINEM BLUT HINUNTERSPÜLEN!}