{100}{}{Du siehst einen Zuschauer.}
{101}{}{Du siehst einen betrunkenen und zugedröhnten Raider, dem nur noch dieses Schauspiel fehlt, um vollkommen glücklich zu sein.}

#Âûêğèêè ïğè ïîëó÷åíèè óğîíà
{102}{}{Verdammt!}
{103}{}{Willst du so sehr sterben?}
{104}{}{Na los, ihr Leute!}
{105}{}{A-a-ah!}
{106}{}{Ah, Schmerz ist wunderschön!}
{107}{}{Schmerz, süßer Schmerz!}
{108}{}{Verdammt noch mal!}
{109}{}{Du kleiner ...}
{110}{}{Rate mal, was ich deiner Mutter angetan hab!}
{111}{}{Gottverdammt ...}
{112}{}{Warte nur, bis ich dich erwische ...}
{113}{}{Wart's nur ab!!!}

#Âûêğèêè âî âğåìÿ áîÿ ÃÃ íà ğèíãå
{114}{}{Macht den Clown fertig!}
{115}{}{Ach, komm schon!}
{116}{}{Mach diesen Grünschnabel fertig!}
{117}{}{::schreit::}
{118}{}{Geh weg davon!}
{119}{}{Schlag ihm aufs Ohr! Aufs Ohr!}
{120}{}{Schlag ihn! Mitten auf den Kiefer!}
{121}{}{Was passiert hier!!!}
{122}{}{Wow, hast du das gesehen?}
{123}{}{Das war heftig!!!}
{124}{}{::schreit::}
