{100}{}{Du siehst einen Sklaven.}
{101}{}{Du siehst „Nummer 18-22“.}

{102}{}{Du siehst einen müden Sklaven.}
{103}{}{Du siehst einen müden Sklaven mit der Nummer "18-22" auf der Stirn.}

{104}{}{Bitte tu mir nicht weh!}
{105}{}{Was? Ich bin jetzt frei? Das sind großartige Neuigkeiten! Danke, Freund!}

{110}{}{[Als er dich sieht, senkt der erschöpfte Sklave den Blick und fegt weiter den Boden]}
{111}{}{Hey, du! Wo sind deine Manieren!?}
{112}{}{Äh, hi. Wer bist du?}
{113}{}{Bleib hier und halt den Mund.}

{114}{}{Tut mir leid, mein Name ist Nummer 18-22. Ich bin hier sozusagen ein Sklave...}
{115}{}{Äh... Mein Name ist Nummer 18-22. Ich bin hier sozusagen ein Sklave...}

{116}{}{18-22? Das ist ja ein bescheuerter Name...}
{117}{}{Wie lange halten sie dich schon hier fest?}
{118}{}{Wie bist du hierhergekommen?}
{119}{}{Willst du hier raus?}
{120}{}{Hör zu, ich bin hier, um Nachforschungen anzustellen. Hilf mir mit ein paar Hinweisen.}
{121}{}{Ich muss über die Lage hier reden. Also, du erinnerst dich an unser Gespräch...}
{122}{}{Nun ja... Mein richtiger Name ist Smiley, aber hier werden alle Sklaven mit ihrer Nummer angesprochen... Ja.}
{123}{}{Zwei... Monate... glaube ich... Oder sechs... Oder ein Jahr... Ich weiß es nicht genau. Hier führt niemand Buch über die Zeit. Es interessiert auch keinen wirklich.}
{124}{}{Nun, ich wurde von Raidern gefangen genommen, als ich auf der Suche nach einem glücklichen Leben nach Vegas unterwegs war... Ha, das ist komisch... Aber ich hatte Glück, anders als die anderen. An mir führen sie keine Experimente durch... Ich werde nur geschlagen und zur Arbeit gezwungen... Ja.}
{125}{}{Freiheit? Nun, nicht mit diesem Ding... [zeigt die auf seine Stirn gebrannte Nummer] Jedem verpassen sie ein Brandzeichen. Und das bleibt ein Leben lang. Selbst wenn ich frei wäre, würde mich niemand als Menschen ansehen. Jeder würde mich verjagen, niemand würde mir Arbeit geben... Also ja.}

{126}{}{Du bist also eingebrochen oder so? Wow. So ist noch nie jemand hierhergekommen, ja. Dann sag ich dir mal eins: So schlecht ist es hier gar nicht. Zumindest für mich. Aber das Essen hier ist echt mies... Hast du vielleicht etwas zu essen? Für eine Pizza würde ich alles geben!}
{127}{}{Na gut, ich besorge dir später etwas Anständiges zu essen. Bis dahin setz dich hin und warte.}
{128}{}{Hier, sieh dich um und such dir etwas aus.}
{129}{}{Verlass dich bloß nicht drauf! Ich besorge dir nichts. Bleib schön hier sitzen.}

{130}{}{Ugh ... Du hast ja praktisch gar nichts zur Auswahl!}
{131}{}{Ja, die Auswahl ist klein. Tja, heute hast du eben Pech. Tschüss.}

{132}{}{Wow, was für ein Festmahl! [zeigt auf das Essen: }
{133}{}{] Gib mir das bitte!}
{134}{}{Natürlich, lass es dir schmecken.}
{135}{}{Hey, nicht anfassen! Das gebe ich dir nicht!}

{136}{}{Danke! Danke, guter Mensch! So gut habe ich schon lange nicht mehr gegessen! Dieser brahmin-Mist taugt nur dazu, Blähungen zu verursachen, aber das hier ... O-oh ...}
{137}{}{Äh, schon gut ... Jetzt lass uns über das Labor reden.}

{138}{}{Also, das hier ist the Pound. Dort stellen sie Drogen her und testen sie dann an Sklaven - an uns ... Ja.}
{139}{}{Wer leitet the Pound?}
{140}{}{Was ist das für ein Gebäude gegenüber vom Pferch?}
{141}{}{Kann man unbemerkt ins Hauptgebäude gelangen?}
{142}{}{Ich brauche vorerst nichts von dir. Du kannst weitermachen.}

{143}{}{Nun, es ist ... Niemand weiß es ... Er ist sehr verschlossen, niemand sieht ihn je hinein- oder hinausgehen. Aber eins kann ich dir sagen - ich habe gehört, dass es in seinem Büro einen Geheimgang gibt! Ja. Trotzdem weiß niemand, wer er ist.}
{144}{}{Das ist die Produktionsanlage. Dort stellen sie all ihre Drogen her, ja.}
{145}{}{Hm ... 18-22 sagt: ja, wenn du leise bist! Ja. Der Wachmann läuft im Kreis, du kannst ihm also ausweichen. Und die Kerle an der Tür sehen dich wahrscheinlich nicht, wenn du es nachts versuchst. Ja. Trotzdem ist das ein großes Risiko. Aber wenn du ins Büro des Chefs kommst, kannst du durch einen Geheimgang raus. Ich weiß aber nicht, wo der ist und wie man ihn benutzt ...}

{150}{}{Jetzt halt die Klappe und hör mir zu, du erbärmlicher Wurm: Entweder du erzählst mir alles, oder ich schmettere dich gegen die Wand!}
{151}{}{Nein, nein! 18-22 will nicht gegen die Wand geschmettert werden! Ich erzähl's! Alles! [fängt an zu weinen]}
{152}{}{Hör auf zu heulen, du Rotznase! Und jetzt reiß dich zusammen und erzähl mir alles, was du weißt.}

#Æåí ğåïëèêè
{1105}{}{Was? Ich bin jetzt frei? Das sind großartige Neuigkeiten! Danke, Lady!}