{100}{}{Du siehst Gizhiyash.}
{101}{}{Du siehst Gizhiyash, den Silent River, den Sklaven, dem du in Reno geholfen hast.}
{102}{}{Ich denken, du sein Freund! Ich falsch liegen!}
{103}{}{Sei gegrüßt, Wanderer! Möge Midnight Watcher dich segnen.}
{104}{}{Alte Flüsse vor langer Zeit Canyon verlassen, wo jetzt Geckos leben.}

#Ïåğâûé ğàçãîâîğ íà êàğ'å Ëàâëîê
{110}{}{Ich freuen, dich wiedersehen! Ich zu Hause sein, dank dir. Ich nicht wissen, wie dir danken. Hier, nimm diese – ich sie auf Rückweg machen. [Er gibt dir zwei Beutel Heilpulver]}
{111}{}{Danke.}
{112}{}{Das war's? Was für eine Abzocke!}
{113}{}{Mein Bruder Acabidab auch dir danken wollen. Er zu mir nach Reno kommen wollen, aber Häuptling nein sagen. Du mir helfen, also Acabidab dir helfen.}
{114}{}{Okay, ich gehe mit ihm reden.}

#Ïîëó÷åíèå ìèíè-êâåñ'à íà îõî'ó
{115}{}{Wir uns wiedersehen. Wie ich dir zurückzahlen können?}
{116}{}{Was machst du jetzt?}
{117}{}{Nichts. Genieß einfach deine Freiheit.}

{118}{}{Ich mich vorbereiten, im Schatten zu wandeln. Cheyenne hungrig sein, und ich Jäger sein.}
{119}{}{Du gehst auf die Jagd? Was jagst du?}
{120}{}{Du gehst jemanden töten? Jemanden, den ich kenne?}
{121}{}{Viel Glück! Erzähl mir, wie es ausgeht.}

{122}{}{Acabidab Geckos im Canyon sehen. Sie sich verirren, von Rudel getrennt sein. Sie gutes Essen und Felle sein. Ich sie jagen, bevor sie Weg aus Canyon finden.}
{123}{}{Nimm mich mit! Ich will auch jagen.}
{124}{}{Das klingt nicht nach meinem Ding, aber viel Glück.}

{125}{}{Bleichgesicht und Cheyenne zusammen jagen. Ha! Das lustiger Gedanke sein. Du hier alles lassen, außer Speer. Das echte Jagd sein, wie Midnight Watcher uns lehren.}
{126}{}{Gut, ich bin bereit.}
{127}{}{Bist du sicher, dass ich keine Waffe mitnehmen kann?}
{128}{}{Nur ein Speer? Ich hab's mir anders überlegt, du musst ohne mich gehen.}

{129}{}{[Er schüttelt den Kopf] Nein. Die Stärke eines Jägers liegt in seiner List, nicht in seinem Feuerstock. Um Midnight Watchers Segen zu erhalten, muss ein Jäger ehrlich zum Ödland sein. Ein Jäger muss ehrlich zu sich selbst sein.}
{130}{}{Na gut, machen wir's.}
{131}{}{Nein, ich jage nicht mit einem Speer. Geh ohne mich.}
{132}{}{Eine Jägerin? Das ist sehr seltsam. Aber du bist listig und mutig, also ... Nimm diesen Speer. Alles andere lässt du zurück. Das ist wahre Jagd, so wie Midnight Watcher es uns lehrt.}

#Ïîñëå çàâåğøåíèÿ îõî'û
{140}{}{Sie sind ganz nah! Wir müssen vorsichtig sein!}
{141}{}{Noch ein Gecko!}
{142}{}{Ich nehme die Felle. Geh du schon. Ich treffe dich im Lager.}
{143}{}{Wir sind noch nicht fertig! Nicht alle Geckos sind tot!}

#Ïîñëå çàâåğøåíèÿ îõî'û
{150}{}{Warte, Freund. Nach allem, was du für mich getan hast ... Ich kann nicht glauben, dass du mich im Stich lassen würdest! Ich vergesse es einfach. Ja. Ich versuche, es zu vergessen.}
{151}{}{Verzeih mir, Gizhiyash, ich habe etwas Schlimmes getan.}
{152}{}{Sei nicht böse, Gizhiyash, das passiert eben.}
{153}{}{Wie auch immer. Ich habe dich bereits vergessen.}

{154}{}{Ich bin dir nicht böse. Sei unbesorgt.}
{155}{}{Du hast vor der Jagd etwas von Fellen gesagt, oder?}
{156}{}{Auf Wiedersehen.}

{157}{}{Mein Freund! Hat dir die Jagd gefallen? Hast du etwas Neues gelernt?}
{158}{}{Du hast vor der Jagd etwas von Fellen gesagt, oder?}
{159}{}{Ja, gute Jagd.}

{160}{}{Geckofelle eignen sich gut für Kleidung, Zelte, Taschen ... für vieles. Ich zeige dir, wie man sie abzieht, wenn du möchtest.}
{161}{}{Ja, ich würde liebend gern lernen, wie man Geckos häutet!}
{162}{}{Danke, aber nein.}

{163}{}{Du bist dir nicht sicher, was du sagst. Ich habe es gehört.}
{164}{}{[Gizhiyash hat dir beigebracht, wie man Geckos häutet. Du bist zuversichtlich, dass du sie von nun an selbst häuten kannst.]}
{165}{}{Danke, Gizhiyash.}
{166}{}{Du hast den Erfolg "Geckos häuten" errungen.}

#Female character
{1103}{}{Sei gegrüßt, Wanderer! Möge Midnight Watcher dich segnen.}
{1113}{}{Mein Bruder Acabidab auch dir danken wollen. Er zu mir nach Reno kommen wollen, aber Häuptling nein sagen. Du mir helfen, also Acabidab dir helfen.}
{1126}{}{Gut, ich bin bereit.}
{1128}{}{Nur ein Speer? Ich hab's mir anders überlegt, du musst ohne mich gehen.}
{1129}{}{[Er schüttelt den Kopf] Nein. Die Stärke eines Jägers liegt in seiner List, nicht in seinem Feuerstock. Um Midnight Watchers Segen zu erhalten, muss ein Jäger ehrlich zum Ödland sein. Ein Jäger muss ehrlich zu sich selbst sein.}
{1151}{}{Verzeih mir, Gizhiyash, ich habe etwas Schlimmes getan.}
{1161}{}{Ja, ich würde liebend gern lernen, wie man Geckos häutet!}
