{100}{}{Du siehst einen Jäger.}
{101}{}{Du siehst einen sonnengebräunten Jäger vom Stamm der Cheyenne.}
{102}{}{Ich ruhe mich aus, Fremder.}
{103}{}{Du hast gesagt, du bist unser Freund!}

#Äèàëîã äî êâåñ'à:

#Ïåğâûé ğàçãîâîğ
{110}{}{Grüße, Fremder ... Du bist kein Cheyenne, doch im Schatten der Nacht sehen alle wie Brüder aus. Ich hoffe, du lässt dich nie vom strahlenden Goldstück blenden, das über den Himmel kriecht, und vom rechten Weg abbringen ... }
{111}{}{Hast du Gold gesagt? Wo ist dieses Goldstück?}
{112}{}{Äh ... Hallo, Bruder. Wer bist du eigentlich?}
{113}{}{Na ja ... Ich gehe dann mal.}

{114}{}{[Er zeigt mit einem Finger nach oben] Wenn die Schatten sich unter Zelten, Bäumen und Steinen verstecken, schau zum Himmel, und du wirst es sehen. Ein verfluchtes Metall, das die Augen verbrennt und den Geist blendet. Selbst die stärksten Geister verlassen den wahren Pfad, um ihm nach Westen zu folgen.}
{115}{}{Ach ja ... Die Sonne. Und wer bist du?}

{116}{}{Alles auf dieser Welt geht zu Ende, doch auch das Ende geht zu Ende. Wieder kommst du nach Acabidab ... }
{117}{}{Erzähl mir von dir.}
{118}{}{Was kannst du mir über deinen Stamm erzählen?}
{119}{}{Weißt du etwas über die Plünderer hier in der Gegend?}
{120}{}{Ich gehe wieder.}
{121}{}{Ja?}

{122}{}{Grüße, Bruder! Die Freude, dich zu sehen, wird nur von der Freude übertroffen, dass ein Bruder zurückkehrt ... }
{123}{}{Vielleicht, aber ich muss gehen.}
{124}{}{Ich muss gehen.}

#Åñëè âûïîëíåí êâåñ' ïî ğåéäåğàì ïó'åì î'ğàâëåíèÿ âîäû
{125}{}{Wahrlich, der Midnight Watcher geht durch dich seinen Pfad! Die Cheyenne werden in heiligen Liedern von dir singen und sich an dich als Ghost Asp erinnern, der sogar das schwarze Blut des Verschlingers vergiftete!}
{126}{}{Du ehrst mich, Bruder!}
{127}{}{Na ja, klingt immerhin besser als Thick Snake, denke ich.}
{128}{}{Grüße, Ghost Asp! Was brauchst du von mir?}
{129}{}{Ich war gerade in der Nähe und wollte Hallo sagen.}

#Î ñåáå è Òèõîé ğåêå
{130}{}{Ich bin Acabidab, der große Bison. Ich bin ein demütiger Diener derer, die im Schatten der Nacht wandeln.}
{131}{}{Derer, die ... Schatten ... Hm, heißt das, du sprichst mit Geistern?}
{132}{}{Verstehe. Ich habe noch andere Fragen.}
{133}{}{Du denkst, ich bin ein Schamane? Ha-ha, nein! Ich bin bei Weitem nicht so weise. Ich wandle nur auf dem Pfad der Schatten, wie der Midnight Watcher es mir zeigte. Es ist ein schwieriger Pfad, und allein ist er noch schwieriger ... Silent River, lieber Bruder ... .}
{134}{}{Erzähl mir vom Pfad der Schatten und diesem „Midnight Watcher“.}
{135}{}{Silent River? Ist das noch einer deiner Götter?}
{136}{}{Ah, ja ... Früher, als die gesegneten Länder ewiges Tageslicht kannten, kämpfte der Seelenverschlinger gegen den Feuergeborenen Vater, um die Himmlische Mutter und all ihre Länder, Meere und Berge zu rauben. Doch Mitternachtswasser, der sich lange unter der Erde in den Schatten verborgen hatte, warf einen schwarzen Mantel über das Schlachtfeld und erschuf die Nacht. So konnte der Feuergeborene Vater den Seelenverschlinger mit einem einzigen Schlag niederstrecken. Das hielt ihn viele Jahre lang auf, bis er wieder seine flammende Kriegsstreitaxt erhob ...}
{137}{}{Du wirkst wie ein Meister im Überleben in der Wildnis. Würdest du mir deine Geheimnisse verraten?}
{138}{}{Du bist hier allein, oder? Oder versteckt sich noch jemand in den Schatten?}
{139}{}{Ich sollte gehen.}
{140}{}{[Er seufzt] Silent River ... Mein Bruder, nicht durch Blut, sondern durch die Seele. Nur er und ich hören den Midnight Watcher und wandeln auf dem Pfad der Schatten. Er und ich sind die Spitzen der Klingen des Midnight Watcher. Ich bin geschickt mit jeder Waffe, die einen schnellen und lautlosen Tod bringt, aber die Cheyenne haben keinen besseren Späher als Silent River. Nachts ist er stiller als die Toten ... Und nun ist er in der weiten Einöde verschollen ...}
{141}{}{Was ist passiert?}
{142}{}{Du bist geschickt? Kannst du mir ein paar Tricks beibringen?}
{143}{}{Das tut mir leid. Lass uns über etwas anderes reden.}
{144}{}{[Er starrt dich lange an] Die Midnight Watcher geben dieses Wissen nur den Cheyenne weiter. Aber wie ich schon sagte: In der Nacht sind alle Brüder. Vielleicht, wenn einer den Pfad der Schatten beschreiten kann ... Silent River zurück zu seinem Stamm führen ...}
{145}{}{Heutzutage werde ich wohl oft gebeten, nach Vermissten zu suchen. Na gut, ich suche nach ihm. Ich hoffe nur, der Fluss ist noch nicht ausgetrocknet.}
{146}{}{Erzähl mir mehr über die Silent River.}
{147}{}{Klar, klar. Ich helfe dir, du hilfst mir, wir sind alle Brüder ...}
{148}{}{Die Cheyenne haben Silent River nicht mehr gesehen, seit er in die Einöde aufgebrochen ist. Aber Karawanenhändler sagen, sie hätten ihn in der Stadt des Verschlingers gesehen – der Stadt, die sie „Reno“ nennen. Sie sagen, ein böser Mann hält ihn in Ketten. Ich will ihn suchen gehen, aber Ogima, der Black Cloud, sagt nein, denn wenn die Cheyenne noch mehr Jäger verlieren, wird uns allen der Tod drohen.}
{149}{}{Wenn ich mal in Reno bin, versuche ich, ihn zu finden.}
{150}{}{Ich habe keine Zeit, nach vermissten Indianern zu suchen. Tut mir leid, Kumpel.}
{151}{}{Du denkst, ich bin ein Schamane? Ha-ha, nein! Ich bin lange nicht so weise. Ich geh nur den Pfad der Schatten, wie Midnight Watcher mir gezeigt hat. Es ist ein schwieriger Pfad.}
{152}{}{Wir folgen dem Pfad von Midnight Watcher. Nacht ist unser Wächter, Schatten sind unsere Verbündeten. Unsere Füße sind lautlos und unsere Waffen tödlich ...}
{153}{}{Stimmt.}
{154}{}{Was hast du vorhin über Silent River gesagt?}
{155}{}{Ich danke dir, Fremder. Möge Midnight Watcher seinen Mantel über dich breiten.}
{156}{}{Ich suche nach ihm. Ich habe allerdings noch eine Frage.}
{157}{}{Ich geh sofort nach ihm suchen.}
{158}{}{Kann ich dir noch ein paar Fragen stellen?}

#Î ğåéäåğàõ
{175}{}{Räuber! Sie sind die Kinder des Verschlingers. Sie bringen uns Leid, und sie werden auch in Zukunft noch mehr Leid bringen.}
{176}{}{Reden wir über etwas anderes.}
{177}{}{Warum nicht stattdessen sie leiden lassen?}
{178}{}{Überall sind die Zeiten hart. Na gut, bis dann.}
{179}{}{Ich könnte ... Wir sind nicht viele, aber Midnight Watcher kennt in diesen Zeiten den Pfad zum Sieg. Und er schätzt jene, die ihn ehren, mehr als jene, die sich sinnlos auf den Feind stürzen ... Aber nein. Es ist noch nicht die richtige Zeit.}
{180}{}{Ich könnte ... Wir sind nicht viele, aber Midnight Watcher kennt in diesen Zeiten den Pfad zum Sieg. Und er schätzt jene, die ihn ehren, mehr als jene, die sich sinnlos auf den Feind stürzen ... Aber ohne Silent River reiche ich nicht aus, um Rache zu nehmen ...}
{181}{}{Silent River? Wer ist das?}
{182}{}{Mitternacht was? Meinst du dich selbst? Oder eine Art Geist?}
{183}{}{Ja, ohne Hilfe ist es schwer, etwas zu erreichen. Apropos, kannst du mir noch bei ein paar Fragen helfen?}
{184}{}{Wenn du meinst. Ich muss gehen.}

#Î ïëåìåíè
{200}{}{Schatten sind überall und kennen viele Geheimnisse ... Aber einem Fremden können sie nicht alles sagen.}
{201}{}{Schatten sind überall und kennen viele Geheimnisse. [Er zwinkert verschmitzt] Ein Freund kann viel von ihnen erfahren ...}
{202}{}{Was kannst du mir über euren Häuptling erzählen?}
{203}{}{Habt ihr hier einen Heiler?}
{204}{}{Erzähl mir von eurem Schamanen.}
{205}{}{Ihr habt offenbar viele Jäger und Krieger. Gibt es jemanden, der besonders hervorsticht?}
{206}{}{Eigentlich möchte ich etwas anderes fragen.}

{207}{}{Ogima der Black Cloud ist ein weiser Häuptling. Er führt die Cheyenne mit der Stärke eines Bisons ... Und obwohl er uns verbietet, jene „Räuber“ zu vernichten, die uns quälen, verstehe ich seinen klugen Plan.}
{208}{}{Ahh, die Himmlische Mutter war sehr großzügig, als sie Niskigvan ihre Gabe schenkte. Sogar Geister, die zu den großen Jagdgründen gegangen sind, kann er in ihre Körper zurückrufen! Doch manchmal ist selbst er machtlos ... Armer Makkon ... }
{209}{}{Hm. Avanigizhig ist in mancher Hinsicht weise, aber er ist blind, wenn er unseren Gott verleugnet. Er sagt sogar, unser Gott sei nur eine andere Gestalt des Verschlingers! ... Wir wollen keinen Streit innerhalb der Cheyenne, also tun wir so, als würden wir einander nicht bemerken.}
{210}{}{Hmm ... Makozid Bärentatze ist der mächtigste Krieger des Stammes. Gekek ist an Leib und Seele stark und könnte dem Pfad des Midnight Watcher folgen, doch er kämpft nur auf so geradem Weg wie sein Speer. Unser Hirte war einst ein glorreicher Krieger, doch seit er von einem Feuerstab verwundet wurde, verbringt er seine Zeit außerhalb des Lagers, fern von den Cheyenne.}
{211}{}{Interessant. Lass mich etwas anderes fragen.}

#Êâåñ' íà ïîèñê Ãèæèÿøà
{250}{}{Aber hat Gizhiyash dir nicht schon erzählt, wie er zu den Cheyenne zurückgekehrt ist?}
{251}{}{Erzähl mir noch einmal von Silent River.}

{252}{}{[Er seufzt] Es schmerzt, über meinen Bruder zu sprechen, aber ich tue alles, um dir zu helfen, ihn zu finden.}
{253}{}{Wie ist er noch mal verschwunden?}
{254}{}{Kannst du mir noch einmal von ihm erzählen?}
{255}{}{Das ist alles. Ich setze meine Suche fort.}
{256}{}{Die Cheyenne haben Silent River nicht mehr gesehen, seit er in die Ödnis gegangen ist. Aber Karawanenhändler sagen, sie hätten ihn in der Stadt des Verschlingers gesehen – der, die sie „Reno“ nennen. Sie sagen, ein böser Mann halte ihn in Ketten. Ich will ihn suchen gehen, aber Ogima Black Cloud sagt Nein, denn wenn die Cheyenne noch mehr Jäger verlieren, wird uns das alle den Tod bringen.}
{257}{}{Silent River... Mein Bruder, nicht durch Blut, sondern durch die Seele. Nur er und ich hören das Midnight Watcher und wandeln auf dem Pfad der Schatten. Er und ich sind die Spitzen der Klingen des Midnight Watcher. Ich bin geschickt im Umgang mit jeder Waffe, die einen schnellen und lautlosen Tod bringt, aber Cheyenne hat keinen besseren Späher als Silent River. Er ist nachts leiser als die Toten... }
{258}{}{Ich muss nichts weiter wissen.}

{259}{}{Fremder! Du bist wahrlich vom Midnight Watcher gesegnet! Der Weg war hart für ihn, aber Gizhiyash der Silent River ist zu den Cheyenne zurückgekehrt!}
{260}{}{Ja, ja, schon gut. Wie wär's mit einem Segen, der wirklich etwas bringt? Zum Beispiel einer Belohnung?}
{261}{}{Ich freue mich für euch beide. Gute Freunde sind schwer zu finden. Passt aufeinander auf.}
{262}{}{Die Sonne hat dich geblendet, und jetzt kennst du nur noch deinen eigenen Durst. Aber du hast mir geholfen, also helfe ich dir.}
{263}{}{Genug von dem Mist. Kommen wir zur Sache!}
{264}{}{Ja, du hast recht... Und ich verstehe, dass dein Weg so schwierig ist wie der Pfad der Schatten. Viele Prüfungen erwarten dich, Bruder. Ich werde alles tun, um dir zu helfen, dich ihnen zu stellen.}
{265}{}{Ich bin dir dankbar!}
{266}{}{Vergiss es, ich habe keine Zeit für Training.}
{267}{}{Acabidab hat deine Nahkampf- und Wurfwaffenfertigkeit um 5% erhöht.}
{268}{}{[Stundenlang zeigt dir Acabidab verschiedene Tricks, etwa wie man Messer lautlos wirft oder einen Gegner an seiner verwundbarsten Stelle trifft. Schließlich fühlst du dich sicherer im Umgang mit deinen Fähigkeiten.]}
{269}{}{[Weiter]}
{270}{}{Du bist ein sehr guter Schüler... Bitte, nimm dieses Messer als Geschenk. Aber denk daran, ein Speer wird es besiegen. Bring mir einen Speer, und ich werde ihn schärfen... Aber mir geht der Feuerstein fast aus.}
{271}{}{Danke, Acabidab. Ich werde daran denken.}

#Çà'î÷êà êîïüÿ
{300}{}{Du hast etwas vom Schärfen von Speeren gesagt?}
{301}{}{Bring einen Speer, dann kann ich ihn schärfen. Aber mir geht der Feuerstein fast aus.}
{302}{}{Ich habe einen Speer dabei. Bitte schärf ihn.}
{303}{}{Das werde ich mir merken. Im Moment habe ich eine andere Frage.}
{304}{}{Das brauche ich gerade nicht. Leb wohl.}
{305}{}{Hmm ... Alles in dieser Welt geht einmal zu Ende, sogar Stein. Ich habe keinen Feuerstein mehr. Ich kann diesen Speer nicht weiter schärfen.}
{306}{}{Wie schade. Ich hatte den Dreh gerade raus.}

{307}{}{Macht der Fremde Witze?}
{308}{}{Wie konnte der Speer verschwinden?}
{309}{}{Fertig, Fremder.}
{310}{}{Fertig, Geisterviper.}
{311}{}{Danke.}
{312}{}{Danke. Ich habe ein paar Fragen.}
{313}{}{Fertig, Fremder. Aber alles in dieser Welt geht einmal zu Ende, sogar Stein. Ich habe keinen Feuerstein mehr. Ich kann keine Speere mehr schärfen.}
{314}{}{Fertig, Geisterviper. Aber alles in dieser Welt geht einmal zu Ende, sogar Stein. Ich habe keinen Feuerstein mehr. Ich kann keine Speere mehr schärfen.}

#Female character
{1110}{}{Grüße, Fremder ... Du bist kein Cheyenne, doch im Schatten der Nacht sehen alle wie Brüder aus. Ich hoffe, du lässt dich nie vom strahlenden Goldstück blenden, das über den Himmel kriecht, und vom rechten Weg abbringen ... }
{1116}{}{Alles auf dieser Welt geht zu Ende, doch auch das Ende geht zu Ende. Wieder kommst du nach Acabidab ... }
{1122}{}{Sei gegrüßt, Schwester! Die Freude, dich zu sehen, wird nur von der Freude über die Rückkehr eines Bruders übertroffen ... }
{1125}{}{Wahrlich, der Midnight Watcher wandelt durch dich! Cheyenne wird in heiligen Liedern von dir singen und sich deiner als White Shadow erinnern, der sogar das schwarze Blut des Verschlingers vergiftete!}
{1128}{}{Sei gegrüßt, White Shadow! Was brauchst du von mir?}
{1129}{}{Ich war gerade in der Nähe und wollte Hallo sagen.}
{1155}{}{Ich danke dir, Fremder. Möge Midnight Watcher seinen Mantel über dich breiten.}
{1200}{}{Schatten sind überall und kennen viele Geheimnisse ... Aber einem Fremden können sie nicht alles sagen.}
{1201}{}{Schatten sind überall und kennen viele Geheimnisse. [Er zwinkert verschmitzt] Ein Freund kann viel von ihnen erfahren ...}
{1259}{}{Fremder! Du bist wahrlich vom Midnight Watcher gesegnet! Der Weg war hart für ihn, aber Gizhiyash der Silent River ist zu den Cheyenne zurückgekehrt!}
{1261}{}{Ich freue mich für euch beide. Gute Freunde sind schwer zu finden. Passt aufeinander auf.}
{1262}{}{Die Sonne hat dich geblendet, und nun kennst du nur noch deinen eigenen Durst. Aber du hast uns geholfen, also helfe ich dir.}
{1264}{}{Ja, du hast recht ... Und ich verstehe, dass dein Weg so schwierig ist wie der Pfad der Schatten. Viele Prüfungen stehen dir bevor, Schwester. Ich werde alles tun, um dir zu helfen, dich ihnen zu stellen.}
{1265}{}{Ich bin dir dankbar!}
{1270}{}{Du bist ein sehr guter Schüler... Bitte, nimm dieses Messer als Geschenk. Aber denk daran, ein Speer wird es besiegen. Bring mir einen Speer, und ich werde ihn schärfen... Aber mir geht der Feuerstein fast aus.}
{1306}{}{Wie schade. Ich hatte den Dreh gerade raus.}
{1309}{}{Fertig, Fremder.}
{1310}{}{Fertig, White Shadow.}
{1313}{}{Fertig, Fremder. Aber alles in dieser Welt geht einmal zu Ende, sogar Stein. Ich habe keinen Feuerstein mehr. Ich kann keine Speere mehr schärfen.}
{1314}{}{Fertig, White Shadow. Aber alles in dieser Welt geht einmal zu Ende, sogar Stein. Ich habe keinen Feuerstein mehr. Ich kann keine Speere mehr schärfen.}
