{100}{}{Ein Jäger.}
{101}{}{Ein erfahrener Jäger des Cheyenne-Stammes.}

#Ïîïûòàòüñÿ ïîäâèíóòü
{102}{}{Ich gehen.}
{103}{}{Wir gehen.}
{104}{}{Geh langsam, Fremder.}
{105}{}{Hmm. Ich gehe.}
{106}{}{In Ordnung.}

#Ïîïûòêà çàãîâîğèòü
{107}{}{Nein. Ich rede nicht mit dir.}
{108}{}{Mmm! Ich will essen!}
{109}{}{Ich nicht sprechen.}
{110}{}{Ich will nicht.}


#Ïîïûòêà çàãîâîğèòü ïğè çàâèñèìîñòè îò íàğêîòû
{111}{}{Isst der Fremde einen Zaubertrank?}
{112}{}{Hmm ... Verlässt die Seele des Fremden seinen Körper?}
{113}{}{Warum schaut der Fremde?}
{114}{}{Ich nicht mögen.}

{115}{}{Nein. Riecht schlecht.}
{116}{}{Fremder macht Böses.}
{117}{}{Wir wollen nicht, aber Fremder zwingt uns.}
{118}{}{Böser Fremder! Hau ab!}
{119}{}{Was dein Stamm?}
{120}{}{Cheyenne erinnern für immer!}
{121}{}{Sohn des Verschlingers muss sterben!}

{122}{}{}
{123}{}{Böser Fremder! Böse!}
{124}{}{Du guter Stamm. Cheyenne Freund.}
{125}{}{Ich nicht vergeben!}
{126}{}{Oh! Babyjunge schon so groß!}
{127}{}{Ich Kind.}
{128}{}{Du gut machen?}
{129}{}{Kind sieht aus wie ich.}
{130}{}{Ich dieses Kind machen.}
{131}{}{Kind glücklich machen mich glücklich.}
{132}{}{Wir gute Familie, Kind. Sei gut.}
{133}{}{Du sein gut, Kind?}
{134}{}{Ich hungrig!}
{135}{}{Ich aufs Dach gehen!}
{136}{}{Mmm! Magischer Kräutertee!}
{137}{}{Mmm! Geckoeintopf und Pilze!}
{138}{}{Mmm! Küche riecht sehr gut!}

{139}{}{Wer hier?}
{140}{}{Wer du?}
{141}{}{Cheyenne kennen dich?}
{142}{}{Fremder will handeln?}
{143}{}{Fremder will Geckohäute?}
{144}{}{Fremder Geckohäute kaufen?}
{145}{}{Cheyenne mögen Fremde nicht.}
{146}{}{Cheyenne wollen, dass Fremder bald geht.}