{100}{}{Du siehst Big Louie.}
{101}{}{Der Muskelberg, der König der Halsabschneider, der Wolf des Ödlands. Reicht das nicht?}
{102}{}{Du siehst deinen Boss. Sein Wort ist Gesetz.}

################################################################################
#
#      Ïåğâûé äèàëîã
#
################################################################################

{103}{}{Durchsucht den Kerl! Packt alles in den Spind. [Er wendet sich dir zu.] Du, du bist erledigt! Was schnüffelst du in meinem Gebiet herum?}
{104}{}{Whoa, ganz ruhig, Mann ...}
{105}{}{Du wirst mich Boss nennen! Oder du kotzt deine Innereien aus!}
{106}{}{Okay, Boss. Ich habe nach deinem Stützpunkt gesucht, weil ich mich dir anschließen wollte.}
{107}{}{Ich bin hier, um deiner Leiche das Blut auszusaugen, deine Männer zu Leder zu verarbeiten und dieses Gebäude bis auf die Grundmauern niederzubrennen!}
{108}{}{Lustig, deine Mutter hat mich letzte Nacht auch so genannt. Aber das waren nicht die Antworten, die sie im Mund hatte.}

{109}{}{HA-HA-HA! Na, du bist ja ein ganz Harter! Okay, jetzt lernst du die Hunde kennen. Mal sehen, wie mutig du wirklich bist!}
{110}{}{[Er knurrt] Du arroganter SCHWEINEHUND! Ich HASSE selbstgefällige Arschlöcher wie dich! Bringt ihn zu den Hunden. Wir hatten schon lange keinen guten Kampf mehr!}
{111}{}{Was ... [man eskortiert dich gewaltsam zu den Ruinen nahe dem Fuß des Gebäudes]}

{112}{}{[Er verschränkt seine gewaltigen Arme vor der Brust] Ist das so?}
{113}{}{Ich habe die Nase voll davon, mit Möchtegern-Gangstern herumzuziehen. Ich bin echt! Ich will RICHTIG was erleben!}
{114}{}{Du hältst mich für einen Idioten, oder?}
{115}{}{Nein.}
{116}{}{Ja, das tust du. Oder?}
{117}{}{Ja.}
{118}{}{Nein.}

{119}{}{[Er mustert dich aufmerksam] Na gut, Hübscher. Warum sollte ich dich brauchen?}
{120}{}{[Er mustert dich aufmerksam] Na gut, Muskelprotz. Warum sollte ich dich brauchen?}
{121}{}{[Er mustert dich aufmerksam] Na gut. Warum sollte ich dich brauchen?}
{122}{}{Ich bin stark. Und nicht wie deine Männer unten - die sind nicht gerade hart im Nehmen. Nicht so wie du. Oder ich.}
{123}{}{Ich bin nachts eine Katze. Jeder kann eine Tür eintreten, aber ich kann meilenweit weg sein, bevor meine Opfer überhaupt merken, dass ich da war.}
{124}{}{Ich bin ein Meister der Sprengstoffe. Soll jemand sterben? Ich lösche seine ganze Familie aus. Soll etwas zerstört werden? Du wirst glauben, es hätte nie existiert. Ich kann Dinge auf einem ganz anderen Niveau erledigen als deine jetzigen Männer.}
{125}{}{Ich kann jedes Schloss öffnen, mechanisch oder elektrisch. Dafür kannst du mich doch bestimmt gebrauchen.}
{126}{}{Ich kenne dieses Ödland wie meine Westentasche. Wenn es ums Überleben in der Wildnis geht, macht mir keiner etwas vor.}
{127}{}{Sieh mich doch an. Ich war überall, habe alles gemacht und jeden getroffen. Was immer du brauchst, ich erledige es.}

{128}{}{Na gut, Hübscher. }
{129}{}{Na gut, Macho. }
{130}{}{Na gut. }
{131}{}{Ich bin überzeugt. Aber ich warne dich – das gilt fürs Leben. Entweder du bist bei mir oder weg. [he pounds one fist into his palm] Für immer!}
{132}{}{Hey, dafür habe ich mich nicht gemeldet! Ich bin weg!}
{133}{}{Kein Problem. Kann ich jetzt meine Sachen zurückhaben?}

{134}{}{[Er wühlt eine Weile in deinen Sachen, bis er zufrieden ist] Du kannst deine Sachen nehmen. Aber freu dich nicht zu früh. Ich will dich in Aktion sehen. Erledigst du den Auftrag, bist du in der Gang. Wenn nicht ... Nun, das wirst du unterwegs schon verstehen. Wir müssen uns nicht einmal die Hände schmutzig machen.}
{135}{}{Ich höre.}
{136}{}{[Er nickt] Gut. Die Waffen, die wir jetzt benutzen, reichen aus, um kleine Dörfer einzuschüchtern, aber wenn wir es ernst meinen, brauchen wir richtige Armeeausrüstung. Und ich weiß genau, wo wir die herbekommen.}
{137}{}{[Zuhören]}
{138}{}{Südlich von hier gibt es einen Armeestützpunkt aus der Vorkriegszeit. Meine Jungs haben versucht, hineinzukommen, aber die Geschütztürme sind noch aktiv. Wie du sie umgehst – das ist jetzt dein Problem. Ich schicke ein paar meiner Jungs mit, aber sie riskieren nicht für dich den Hals. Das ist DEIN Auftrag. Klar?}
{139}{}{Klar. Wann brechen wir auf?}
{140}{}{Ich gebe dir etwas Zeit zur Vorbereitung. Sprich mit mir, wenn du bereit bist, dann organisiere ich den Konvoi.}
{141}{}{Ich bin bald zurück.}
{142}{}{Ich bin bereit, sofort zum Stützpunkt aufzubrechen.}
{143}{}{Zeit ist Geld, Macho. Lass mich nicht warten. Wenn ich dich suchen muss, bist du besser schon tot.}
{144}{}{[Verlassen]}
{145}{}{Ha, der Macho will mich beeindrucken! Gut. Sei in einer Stunde abmarschbereit.}
{146}{}{[Du wartest, bis das Team fertig ist, dann macht ihr euch endlich auf den Weg ins Ödland.]}

{147}{}{[Er mustert dich aufmerksam] Ja, ja ... Ich sehe, jemand wie du könnte hier seinen Platz haben. Aber sag mir, Junge – was genau hast *du* mir zu bieten?}

{148}{}{Sprich.}
{149}{}{}

{150}{}{Während man dich nach unten eskortiert hat, ist es dir gelungen, einem Plünderer etwas zu stehlen.}
{151}{}{Die Geißel des Ödlands ist tot. Du erhältst 500 Erfahrungspunkte.}
{152}{}{Für den Sieg über die Geißel des Ödlands im fairen Kampf erhältst du 2000 Erfahrungspunkte.}
{153}{}{Ma... Ma...}
{154}{}{Grrr ... Schon wieder muss ich alles selbst erledigen!}

################################################################################
#
#     Îáùèå ğåïëèêè
#
################################################################################

# Êîãäà íà íåì ïîşçàíà íàğêî'à
{155}{}{Dafür hänge ich dich an deinen eigenen Eingeweiden auf!}

# Êîãäà ğåéäåğû óíè÷'îæåíû î'ğàâëåíèåì âîäîñáîğíèêà
{156}{}{Steht auf, ihr Inzuchtbrut! Muss ich wirklich alles selbst erledigen?!}
{157}{}{::murmelt::}
{158}{}{Nutzlose Idioten ...}
{159}{}{Auf die Beine, ihr wertlosen Hunde!}
{160}{}{Wenn ich herausfinde, wer das war ...}
{161}{}{Dafür zerreiße ich diese Indianer in Stücke!}
{162}{}{Ich zeige euch, was passiert, wenn ihr Big Louie nicht gehorcht!}
{163}{}{::knurrt::}
{164}{}{Aaaagh!}
{165}{}{Rnnmf ...}
{166}{}{NIEMAND MACHT DAS MIT BIG LOUIE!}
{167}{}{Du bist tot! Ich hab gesehen, was du getan hast!}

# Ïğîâåğêà èíâåí'àğÿ:
{170}{}{Nein. Ich will es mir erst ansehen.}
{171}{}{[Warte, bis er deine Ausrüstung durchsucht hat]}
{172}{}{[Versuche, dich loszureißen]}
{173}{}{[Er durchsucht deine Sachen und wirft dir das, was er nicht haben will, vor die Füße] Ah, glänzende Geschenke für Big Louie! Das nehme ich. [Er nimmt dein Geld]}
{180}{}{[Schweigend, beinahe ehrfürchtig, stellt er dein Elvis-Presley-Porträt auf sein Regal]}
{181}{}{[Er nimmt dein Feuerzeug, dreht es in der Hand, klappt es auf und starrt in die Flamme] Das nehme ich.}
{182}{}{[Beim Anblick deines Scharfschützengewehrs erschaudert er und legt es vorsichtig in seinen Spind]}
{183}{}{}
{184}{}{Hallo ... [Er hält deine Karte von Salt Lake City hoch] Danach habe ich schon lange gesucht. [Er faltet sie sorgfältig zusammen und legt sie in seinen Spind]}
{185}{}{Hundefleisch? [Er schüttelt grinsend den Kopf] Das exotische Zeug probiere ich später ...}
{186}{}{Ein bisschen von Vegas' Stolz und Freude? [Er steckt deine Droge aus Vegas in die Tasche] Hmmm ... Du bist ein harter Kerl - ich glaube, du wirst nützlich sein.}

################################################################################
#
#      Êâåñ'û
#
################################################################################

#Ñäà÷à ïåğâîãî êâåñ'à:
{200}{}{Na, du bist ja ganz schön fähig! Mein Trupp ist jetzt bestens ausgerüstet. Du hast dir etwas Respekt verdient. Betrachte dich als einen von uns. Also, als Erstes hol dir ein Bier oder so von Fatso und mach eine Pause. Wenn du fertig bist, komm zu mir. Dann reden wir richtig. Große Pläne.}
{201}{}{Bis dann.}

#Â'îğîé êâåñ' (äàíü Ñ'ğàéêåğà)
{202}{}{Über unsere Pläne ...}
{203}{}{Im Moment nichts. Hau ab.}
{204}{}{Das Geschäft läuft gut, kapiert? Trotzdem vergisst ein Spieler, seinen Anteil zu zahlen. Er heißt Stryker und wohnt in Reno. Du solltest ihn daran erinnern, welche Hand die Leine hält. Das ist übrigens das Passwort. Er wird verstehen. Hol mir meinen Anteil.}
{205}{}{[Seine Knöchel knacken, als er die Hände zu Fäusten ballt] Ich sehe dich, aber meinen Anteil sehe ich nicht. Steh auf und geh nach Reno, oder ich reiße dir die Finger raus!}

{206}{}{Es gibt ein Problem. Stryker ist nicht vergesslich, er ist tot.}
{207}{}{Hier ist Strykers Anteil.}
{208}{}{Hier ist Strykers Anteil. Dieser Gangster hält sich für viel zu wichtig ...}
{209}{}{Ich bringe ihn später.}
{210}{}{Gut ... Ich bin froh zu hören, dass sein Gedächtnis besser geworden ist. Hier. [Er gibt dir 500 Dollar und eine stimpak] Damit auch du ein gutes Gedächtnis behältst. Und jetzt verschwinde.}

#Òğå'èé êâåñ' (Ëûñûé ïğåäà'åëü)
{211}{}{Es gibt ein Problem. [Er knackt mit den Knöcheln] Irgendwo in Reno versteckt sich ein Mann. Er nennt sich „Balder“. Er hat natürlich eine Glatze und Narben am Hals – vor einiger Zeit hat jemand versucht, ihn aufzuhängen. Er ... Sagen wir, er hat versucht, mich hereinzulegen. Finde ihn und mach ihn fertig. Zeig allen, was mit dem Abschaum passiert, der Big Louie verrät. Und jetzt los! Mit Höchstgeschwindigkeit nach Reno!}
{212}{}{Tut mir leid, Auftragsmorde sind nicht mein Ding.}
{213}{}{[Er starrt auf dich hinab, die Augen zu Stecknadelköpfen verengt] Wie bitte? Es klang, als hättest du gesagt: „Ich will im Ring sterben, Boss.“ Aber du wirst in Reno zu beschäftigt sein, Balder zu töten, oder?}
{214}{}{Was gibt's? Ist Balder schon tot?}
{215}{}{Ich habe ihn gefunden! Er wartet in Reno auf einen Karawanenzug! Er versucht, nach Vegas zu fliehen!}
{216}{}{[Einen Moment lang starrt er dich fassungslos an, dann ballt er die Hände zu Fäusten] Und WAS machst du dann HIER?! LOS, UND TÖTE IHN, BEVOR ER ENTWISCHT!!! Geh, oder du lernst echte Wut kennen! Bewegung!}
{217}{}{Balder ist tot, Boss. Ich habe ihn eigenhändig getötet.}
{218}{}{Gute Arbeit, Macho! Lass uns Armdrücken! Oh, du willst nicht? Ha-ha!! Ich wusste es von Anfang an – du bist zwei von diesen hirnlosen Affen wert, die sich unten gegenseitig einen runterholen ... [er unterbricht sich plötzlich] Hier. [er hält dir 1000 Dollar hin, zieht sie aber wieder außer Reichweite, als du danach greifst] Bring nächstes Mal Beweise mit. Denn wenn du mich anlügst ... [er wartet ein paar Sekunden und beobachtet dich, bevor er dir das Geld gibt]}
{219}{}{Balder ist aus Reno entkommen. Jetzt werden wir ihn nie finden.}
{220}{}{[Big Louies Kiefer verkrampft sich. Seine verengten Augen glühen vor Wut.] Ich sage nur eins dazu. Du bist *fast* ein toter Mann, Macho.}

#×å'âåğ'ûé êâåñ' (êóğüåğ èç Âåãàñà)
{221}{}{Ich habe einen weiteren Auftrag für dich, und er muss *sofort* erledigt werden. Hol die Jungs. Ein Kurier bringt ein wertvolles Paket nach Reno ...}
{222}{}{Wer ist der Kurier?}
{223}{}{Was ist in dem Paket?}
{224}{}{Ich bin bereit.}
{225}{}{Man sagt *Kurier*. Unterschätze ihn nicht. In Vegas machen sie die knallhart. Er weiß, was er tut, und er weiß, wie viel das Paket wert ist. Ich will, dass ihr ihn schnell und hart erwischt. Bring mir das Paket. Und was den Kurier angeht ... Na ja, du verstehst schon.}
{226}{}{Das Paket kommt aus Vegas. Angeblich braut dort jemand eine neue Droge zusammen. In Reno ist sie noch nicht angekommen. Ich will sie als Erster sehen ... Und ich will, dass diese aufgeblasenen Ratten in Reno sich daran erinnern, wer Big Louie ist.}
{227}{}{Aufgeblasene Ratten? Was meinst du damit?}
{228}{}{Du verschwendest Zeit! Aber ich sage es dir. Das ist wichtig. Reno vergisst Big Louie. Meine Jungs Stryker und Thompson gehen ihre eigenen Wege, und die örtlichen Dealer gewinnen an Macht. Die Lage wird jeden Tag schlimmer. Ich kann nicht zulassen, dass irgendjemand in Reno stärker wird, ohne dass meine Leute die Kontrolle haben. Und jetzt los, Zeit ist Geld!}
{229}{}{Hey, ihr! Hoch mit euch, ihr Hunde! Bewegung!!!}
{230}{}{Alle haben es immer so eilig ...}

{231}{}{Du solltest das Paket dabeihaben, sonst bist du tot.}
{232}{}{Heute muss dein Glückstag sein, Boss! Hier ist es!}
{233}{}{Ich habe das Paket nicht gefunden, aber der Kurier ist tot.}
{234}{}{Verdammt, ich wusste, dass ich etwas vergessen hatte! Ich bin gleich wieder da.}
{235}{}{DU – ! [Er schließt die Augen und holt tief Luft] Vergiss es. Der Kurier ist tot, sie schicken kein weiteres Paket. Verzieh dich. [murmelt] ...Umgeben von dämlichen Arschlöchern ...}
{236}{}{Hey, das war nicht leicht! Er hatte eine verdammt gute Sicherheit! All die Arbeit umsonst ...}
{237}{}{[Seine Augen scheinen zu funkeln, als er das Paket öffnet] Na, na, was für ein großer Junge ich jetzt bin! Und hier ist auch was für dich! [Er gibt dir 3000 Dollar und zwei Stimpaks] Jetzt mach's dir gemütlich. Im Moment gibt's keine Arbeit mehr.}
{238}{}{Wow! Das ist eine Menge Geld!}
{239}{}{Gib dir nächstes Mal mehr Mühe. Vergiss nicht, für wen du arbeitest.}

#Êâåñ' íà íàğêîäèëåğà
{240}{}{Noch ein Dreckskerl, der seinen Platz nicht kennt.}
{241}{}{Wer, ich?}
{242}{}{Vor nicht allzu langer Zeit hat einer der Lieferanten von Fatso Jackson ihm schlechte Ware verkauft. Ein paar von unseren Jungs sind dabei draufgegangen.}
{243}{}{Dieser Lieferant muss lebensmüde sein.}
{244}{}{[Er runzelt die Stirn] Er soll mit Blut bezahlen! Es geht nicht mal um die Jungs – wir begraben sie, dann hören sie auf zu stinken. Es geht um Reno selbst. Die Stadt hat ... vergessen, wer Big Louie ist. Stryker und Thompson sind außer Kontrolle, irgendwelche Kleindealer ziehen Fatso über den Tisch ... Wir müssen ein Zeichen setzen. Du erledigst das für *mich* ... und für die Gang. Reno muss sich erinnern.}
{245}{}{Wo finde ich diesen Lieferanten?}
{246}{}{Frag Fatso. Er hat mit ihm zu tun gehabt. Alles, was ich weiß, ist, dass er immer einen Ring getragen hat. Bring ihn mir, wenn der Job erledigt ist.}
{247}{}{Na gut, ich rede mit Fatso.}
{248}{}{Wovon redest du?}
{249}{}{Ich habe den Lieferanten gefunden. Ich habe ihn dazu gebracht, mit seinen Schritten die Länge seiner Eingeweide abzumessen. Hier ist der Ring ... Äh, ich musste mir etwas einfallen lassen, um ihn ihm abzunehmen.}
{250}{}{Nichts.}

################################################################################
#
#      Áîíóñíûé êâåñ'
#
################################################################################

#ïîñëå âñåõ êâåñ'îâ
{251}{}{Gut. Sehr gut. [Er gibt dir 3000 Dollar]}
{252}{}{Du siehst nicht gerade glücklich aus.}
{253}{}{[Er seufzt tief] Ehrlich, Bruder, ich bin müde. Ich hab die Nase voll von dem ganzen ... Ach, vergiss es. Die Saison ist vorbei, nichts zu tun, außer den Stamm auszunehmen und Karawanen auszurauben. Du kannst deiner Wege gehen. Ich halte dich nicht länger hier fest.}
{254}{}{Was? Ich bin raus aus der Gang?}
{255}{}{So ist das nicht. Hier wird immer ein Platz für dich sein. Aber die anderen Jungs kommen von hier an allein zurecht, und ich sehe, dass du Besseres zu tun hast, als herumzusitzen und Indianer zu schikanieren. Für dich gibt es ohnehin nichts mehr zu tun.}
{256}{}{Das kommt unerwartet. Vielleicht sehen wir uns wieder.}

{260}{}{Wie finde ich diesen Lieferanten noch mal?}
{261}{}{Keine Ahnung. Frag Fatso.}
{262}{}{Erledigt. Hier ist der Ring des Lieferanten.}
{263}{}{Erledigt. Ich habe seine Schrotflinte als Beweis mitgebracht.}
{264}{}{Ha! Keiner von den alten Knackern da unten hätte das geschafft. Gute Arbeit! [er gibt dir 1000 Dollar] Und behalt die abgesägte Schrotflinte. Du hast sie dir verdient.}
{265}{}{In Reno wird es langsam zu bunt. Deshalb muss ich eine Erinnerung schicken ... Hey, weißt du, was hier drin ist? Ein kleines bisschen Glück für alle! Und damit meine ich auch dich. [er gibt dir 500 Dollar und eine stimpak]}
{266}{}{ARRGGGHH!!! [er schlägt mit den Fäusten auf den Tisch, du hörst Holz knacken] IHR NUTZLOSEN WÜRMER! WIE KONNTET IHR SO ETWAS ... DU!!! [er zeigt auf dich] RAUS!}
{267}{}{[Verlassen]}
{268}{}{Ich hab eine bessere Idee: Steck dir den Stützpunkt in den Arsch. Such dir jemand anderen für den Job. Ich mach's nicht.}
{269}{}{}

#Ïğî èñ'îğèş Áîëüøîãî Ëóè è Àğìñ'ğîíãà:
{270}{}{Interessant. Wer ist Armstrong?}

{276}{}{[Er wirft dir einen strengen Blick zu] Seh ich aus wie ein Bibliothekar? Verschwinde!}
{277}{}{Beruhig dich, ich frage nur.}

{278}{}{Louie ist ein Idol. Mehr sage ich dazu nicht. Und jetzt verschwinde!}
{279}{}{Entspann dich, es war nur eine einfache Frage, mehr nicht.}

{280}{}{[Er mustert dich einen Moment lang nachdenklich] Louie Armstrong war ... wahrhaftig ein Mann, den man respektieren musste. Und jetzt verschwinde!}
{281}{}{Ich war nur neugierig, mehr nicht.}

{282}{}{Hmm ... Er war mein Kindheitsheld. Aber das ist lange her ... Vergiss es. Ich werde nicht darüber reden.}
{283}{}{Na gut. Vielleicht später dann.}

{284}{}{[Er seufzt] Louie Armstrong ... Das war ein Mann. Er war mein Held, mein Vorbild. Er starb hundert Jahre, bevor ich geboren wurde, aber niemand in diesem Muellhaufen von einer Welt stand mir näher ... Hör zu, vergiss es. Jetzt spielt es keine Rolle mehr.}
{285}{}{Erzähl mir deine Geschichte.}
{286}{}{Du willst dich nicht erinnern?}
{287}{}{Wer ist dieser Armstrong überhaupt?}
{288}{}{Na gut, wie du meinst.}

{289}{}{Das ist lange her. Ich würde diese Tage zurückholen, wenn ich könnte, aber das kann ich nicht.}
{290}{}{[Weiter]}
{291}{}{Nach dem Krieg machten die Gangs Reno dem Erdboden gleich. Am Ende siegten die Eliten, allen voran die Polizei. Sie machten die Stadt sicher – ich meine, sicherer als zuvor. Man konnte ohne Waffe herumspazieren.}
{292}{}{Damals war ich jung. Nachts schlich ich mich in die örtliche Bar, um der Musik zu lauschen. Ich durfte nicht hinein, aber die Klänge fanden immer ihren Weg zu mir nach draußen. Es gab viele Musiker, aber die Lieder des großen Louie liebte ich am meisten. Irgendwie ließ er die Welt einfach ... wunderbar erscheinen. Wie einen Ort, für den es sich zu leben lohnte.}
{293}{}{Ein paar Jahre später brach die Ordnung zusammen und Reno wurde wieder zur Hölle. Danach war Armstrong Geschichte.}

{294}{}{Du warst hier nicht immer der große Boss?}
{295}{}{Du meinst ein brutaler Killer, der hirnlose Schläger anführt, damit sie über die Schwachen und Verlassenen herfallen? Nein. Ich war gebildet, kultiviert. Ein *Mann*, nicht eines dieser Tiere. Ich gründete sogar meine eigene Jazzband, aber das Leben zwang mich, mich zwischen ihr und einer Gang zu entscheiden. Sonst hätte ich nicht überlebt. Jedenfalls sehe ich die Dinge heute anders, wenn ich zurückblicke. Dieser indianische Schamane – er ist ein weiser Mann. Er hat mir die Wahrheit über die Menschen erzählt. Über meine Leute. [he motions towards the floor] Die da unten ... und die hier oben.}
{296}{}{Würdest du gern wieder Jazz spielen?}
{297}{}{Ich würde alles dafür tun, noch einmal diese Chance zu bekommen! Aber bei meinem Ruf ...}
{298}{}{Jazz ist die einzige schöne Erinnerung, die mir geblieben ist.}
{299}{}{Armstrongs Stimme war die einzige auf diesem verfluchten Planeten, der es sich zu lauschen lohnte. Solche Menschen sollten niemals sterben – sie sollten ewig leben. Ich habe jedes Lied auswendig gelernt. Ich kann sie sogar jetzt noch singen ... Aber das werde ich nicht. Nicht für diesen Abschaum da unten.}

#Áîëüøîé Ëóè êàê ìóçûêàí'
{300}{}{Im Moment gibt es keine Arbeit. Hier ist es so still wie in einer Kirche.}
{301}{}{Ich habe eine offene Stelle für einen Sänger in einer Band gefunden, falls du Interesse hast.}
{302}{}{Na dann, tschüss.}
{303}{}{Soll das ein Witz sein, Junge?}
{304}{}{Kein Witz. In Vegas ... [tell him about the cafe]}
{305}{}{Warte ... Du meinst ... ich kann zwischen Vegas und Reno auf Tournee gehen? Ich kann es nicht glauben! Ich mach's! HA-HA! Ich werde dich nie vergessen, Bruder! Du hast mir eine zweite Chance auf das gegeben, was ich immer am meisten geliebt habe! Lass uns zum Abschied Armdrücken!}
{306}{}{Keine Ursache. Wir sehen uns in Vegas!}
{307}{}{Heilige Scheiße! Big Louie hat dir geglaubt und ist nach Vegas gefahren, um auf der Bühne aufzutreten!}

{310}{}{Ich habe es geschafft, nach Hawthorne zu kommen und Zugang zum Lager zu erhalten. Die Jungs müssten jeden Moment mit den Waffen eintreffen.}
{311}{}{Ich habe es geschafft, nach Hawthorne zu kommen und Zugang zum Lager zu erhalten. Die Jungs sind zurückgeblieben ... Für immer.}
{312}{}{Ich habe es geschafft, nach Hawthorne zu kommen und Zugang zum Lager zu erhalten. Aber deine Jungs haben es nicht geschafft.}

#Female character
{1103}{}{Durchsuch sie! Pack alles in den Spind. [Er wendet sich dir zu.] Du bist so gut wie tot! Was schnüffelst du in meinem Gebiet herum?}
{1106}{}{Okay, Boss. Ich bin hier, um mich dir anzuschließen.}
{1107}{}{Ich bin hier, um deiner Leiche das Blut auszusaugen, deinen Männern das Fell für Leder abzuziehen und dieses Gebäude niederzubrennen!}
{1108}{}{Witzig, so hat mich deine Mutter gestern Nacht auch genannt. Aber mit ihrer Zunge hatte sie Besseres zu tun, als zu reden.}
{1110}{}{[Er knurrt.] Du arrogante KUH! Ich HASSE eingebildete Schlampen wie dich! Bringt sie zu den Hunden. Wir hatten schon lange keinen Kampf mehr!}
{1119}{}{[Er mustert dich aufmerksam.] Okay, Ballkönigin. Wozu sollte ich dich brauchen?}
{1120}{}{[Er mustert dich aufmerksam.] Okay, Kampflesbe. Wozu sollte ich dich brauchen?}
{1121}{}{[Er mustert dich aufmerksam] Na gut. Warum sollte ich dich brauchen?}
{1126}{}{Ich kenne diese Einöden wie meine Westentasche. Wenn es ums Überleben in der Wildnis geht, ist niemand besser als ich.}
{1127}{}{Sieh mich doch an. Ich war überall, habe alles gemacht und jeden getroffen. Was immer du brauchst, ich erledige es.}
{1128}{}{Okay, Ballkönigin. }
{1129}{}{Okay, Kampflesbe. }
{1131}{}{Ich bin überzeugt. Aber ich warne dich – das gilt fürs Leben. Entweder du bist bei mir oder weg. [he pounds one fist into his palm] Für immer!}
{1132}{}{Hey, dafür habe ich mich nicht gemeldet! Ich bin weg!}
{1143}{}{Denk dran: Zeit ist Geld. Lass mich nicht warten. [Seine Knöchel knacken, als er die Hände zu Fäusten ballt.] Wenn ich dich suchen gehen muss, solltest du besser schon tot sein.}
{1145}{}{Ah, eine Macherin! Ausgezeichnet. Die Männer sind in einer Stunde abmarschbereit.}
{1147}{}{[Er mustert dich aufmerksam.] Ja. Ja, ich sehe, dass jemand wie du hier seinen Platz hätte. Aber sag mir, Mädchen – was *genau* bringst du mir?}
{1186}{}{Einige von Vegas' ganzer Stolz? [Er steckt deine Droge aus Vegas in seine Tasche.] Hmm ... Du, Mädchen – ich glaube, du könntest nützlich sein.}
{1200}{}{Na, du bist ja ganz schön tüchtig! Mein Rudel ist jetzt bestens ausgerüstet. Du hast dir etwas Respekt verdient. Betrachte dich als eine von uns. Also, hol dir erst mal ein Bier oder so bei Fatso und entspann dich. Wenn du fertig bist, komm zu mir. Dann reden wir Klartext. Große Pläne.}
{1214}{}{Was gibt's? Ist Balder schon tot?}
{1215}{}{Ich habe ihn gefunden! Er wartet in Reno auf einen Karawanenzug! Er versucht, nach Vegas zu fliehen!}
{1216}{}{[Einen Moment lang starrt er dich fassungslos an, dann ballt er die Hände zu Fäusten.] WAS machst du dann HIER?! LOS, GEH RAUS UND TÖTE IHN, BEVOR ER ENTKOMMT!!! Verschwinde, oder ich zeige dir, wie echte Wut aussieht!}
{1217}{}{Balder ist tot, Boss. Ich habe ihn eigenhändig getötet.}
{1218}{}{Gute Arbeit, Mädchen! Lass uns Armdrücken! Oh, du willst nicht? Ha-ha! Ich wusste es von Anfang an – du bist zwei von diesen hirnlosen Affen wert, die sich unten gegenseitig einen runterholen ... [Plötzlich unterbricht er sich.] Hier. [Er hält dir 1000 Dollar hin, zieht sie aber außer Reichweite zurück, als du danach greifst.] Bring nächstes Mal Beweise mit. Denn wenn du mich anlügst ... [Er beobachtet dich einige Sekunden lang, bevor er dir das Geld gibt.]}
{1220}{}{[Big Louies Kiefer verkrampft sich. Seine verengten Augen glühen vor Wut.] Ich sage dazu nur eins. Du bist *fast* eine Leiche, Marimacho.}
{1233}{}{Ich habe das Paket nicht gefunden, aber der Kurier ist tot.}
{1237}{}{[Seine Augen scheinen zu funkeln, als er das Paket öffnet] Na, na, was für ein großer Junge ich jetzt bin! Und hier ist auch was für dich! [Er gibt dir 3000 Dollar und zwei Stimpaks] Jetzt mach's dir gemütlich. Im Moment gibt's keine Arbeit mehr.}
{1244}{}{[Er runzelt die Stirn] Er soll mit Blut bezahlen! Es geht nicht mal um die Jungs – wir begraben sie, dann hören sie auf zu stinken. Es geht um Reno selbst. Die Stadt hat ... vergessen, wer Big Louie ist. Stryker und Thompson sind außer Kontrolle, irgendwelche Kleindealer ziehen Fatso über den Tisch ... Wir müssen ein Zeichen setzen. Du erledigst das für *mich* ... und für die Gang. Reno muss sich erinnern.}
{1249}{}{Ich habe den Lieferanten gefunden. Ich habe ihn dazu gebracht, die Länge seiner Gedärme Schritt für Schritt auszumessen. Hier ist der Ring ... äh, ich musste mir etwas einfallen lassen, um ihn ihm abzunehmen.}
{1251}{}{Gut. Sehr gut. [Er gibt dir 3000 Dollar]}
{1253}{}{[Er seufzt tief.] Ehrlich, Schwester, ich bin müde. Das alles geht mir langsam auf die Nerven ... Ach, vergiss es. Die Saison ist vorbei, bleibt nichts anderes, als den Stamm auszunehmen und Karawanen auszurauben. Du kannst deiner Wege gehen. Ich halte dich nicht länger hier fest.}
{1266}{}{ARRRGGGHH!!! [Er schlägt mit der Faust auf den Tisch, du hörst das Holz krachen.] IHR WERTLOSEN SCHNECKEN! WIE KONNTET IHR BEI SO EINER ... DU!!! [Er zeigt auf dich.] VERSCHWINDE!}
{1277}{}{Beruhig dich, ich frage nur.}
{1303}{}{Ist das irgendein Scherz, Mädchen?}
{1305}{}{Warte ... Willst du sagen ... ich kann zwischen Vegas und Reno auf Tour gehen? Ich kann es nicht glauben! Ich mach's! HA-HA! Ich könnte dich küssen, Baby! Du hast mir eine neue Chance auf das gegeben, was ich immer am meisten geliebt habe!}
