#Ñòàğòîâûå ñîîáùåíèÿ ğàéîíîâ Ñîëò-Ëåéêà:
{100}{}{Du betrittst eine düstere, trostlos wirkende Stadt. Es riecht nach feuchtem, verrottendem Laub.}
{101}{}{Du betrittst das Wohnviertel der Salt Lake-Stadt. Als du die Kinder unbeschwert auf den Straßen spielen siehst, werden deine Augen feucht.}
{102}{}{Du betrittst ein verlassenes Lokomotivdepot.}
{103}{}{Dieses heruntergekommene Elendsviertel ist schon lange verlassen. Doch im Sand bemerkst du ziemlich frische Fußspuren.}
{104}{}{Dieser Ort zeugt noch immer von Blut und Leid. Sieht aus, als hätten sich die Bewohner des Vaults gestritten und gegenseitig zu Tode geprügelt.}