{100}{}{Du siehst ein Tor.}
{101}{}{Du siehst ein Tor mit einer Klingel daran.}

{102}{}{Hallo! Ist jemand zu Hause?! Jemand da?}
{103}{}{Das Tor ist verschlossen und niemand reagiert auf die Klingel. Sieht aus, als würde man dich ignorieren.}
{104}{}{Klopf, klopf!}
{105}{}{Jemand hat das Tor aus der Ferne geöffnet, nachdem du an der „geheimen“ Klingel geläutet hast.}
{106}{}{Das Tor ist bereits offen.}
{107}{}{Du knackst das Schloss am Tor mühelos.}
{108}{}{Erledigt.}
{109}{}{Fehlgeschlagen.}
{110}{}{Du schaffst es nicht, ein einfaches Schloss zu knacken.}