{100}{}{Du siehst einen Hinterwäldler.}
{101}{}{Du siehst einen der wenigen Bewohner von Provo.}
{102}{}{Ein Fremder!}
{103}{}{Ich bin nicht in Plauderlaune.}

###################################################
#
#  Floating dialog between Vulvee and Garry
#
#  Markers:
#         v - Vulvee's line
#         g - Garry's line
#
###################################################

{200}{v}{Ich will Aufmerksamkeit!!! Mir ist langweilig!!!}
{201}{g}{...Hör auf zu jammern! Ich versuche mich hier zu konzentrieren.}
{202}{v}{Wer ist das? Ach, nur du, mein Bruder ...}
{203}{g}{Natürlich bin ich's, wer denn sonst ... Glaubst du, nur du leidest hier?}
{204}{g}{Der Boss beachtet mich überhaupt nicht ...}
{205}{v}{Du bist einfach ein Arschloch. Und ich bin sein wichtigster Denker!!}
{206}{v}{ICH BRAUCHE ANREGUNG!}
{207}{g}{Auch ein Arschloch braucht Anregung.}
{208}{g}{Ich will reisen! Das glühende Vegas sehen!}
{209}{g}{Ich will mich in Bars übergeben und vor den Casinoeingängen mit Hanfsamen scheißen ...}
{210}{g}{...Aber stattdessen hänge ich in diesem stinkenden Motel fest.}
{211}{v}{Immer mit der Ruhe, Kumpel, wir kriegen, was wir wollen. Wir werden die Funken von Vegas sehen.}
{212}{g}{Echt jetzt? Und wie sollen wir das anstellen?}
{213}{v}{Ich habe einen Plan ...}
{214}{v}{::sieht sich um::}
{215}{v}{Verdammt! Ich erzähl's dir später, mein Fleisch brennt an.}
{216}{v}{Dein Fleisch brennt doch ständig an ...}
{217}{v}{Schon besser ...}
{218}{v}{Klopf ein bisschen Ruß ab und guten Appetit.}
{219}{v}{Und warum baut der Boss keine normale Küche?}
{220}{v}{Ich trage ständig diese blöde Hose. Ich brauche eine Schürze.}
{221}{v}{Was ist denn das Problem? Überfall einen Karawanenzug, und fertig ...}
{222}{v}{::denkt über etwas nach::}
{223}{v}{Hat dieser Salt Lake Sheriff ihm solche Angst eingejagt?}
{224}{v}{Dieser Arsch setzt nie wieder einen Fuß hierher!}
{225}{v}{Sie hassen und fürchten einander ...}
{226}{v}{Was für ein Blödsinn, hm!?}
{227}{v}{Ich hatte so viele großartige Ideen, aber der Boss hat einfach alles den Bach runtergehen lassen!}
{228}{v}{Wozu lebe ich überhaupt? Was ist mein Lebenszweck?!}
{229}{v}{Um das Fleisch mit Mist in einer Pfanne zu braten?!}
{230}{v}{Was? Mir eine Verdienstmedaille verleihen? Nein, weil ich verschlafen habe!}
{231}{v}{Was? Ich will einen freien Tag in Reno nehmen? Aber die Jungs haben noch nicht gefrühstückt!}
{232}{v}{N-nö! Keine Belohnungen! Ich verdiene überhaupt nichts, verdammt.}
{233}{v}{O-oh! Ich bin so high!}
{234}{v}{Ich platze vor Ideen! Mein Hirn explodiert bei all den genialen Gedanken!}
{235}{v}{Ich könnte die Gang wieder groß machen, wenn da nicht ... der Boss wäre!}
{236}{v}{Noch mal: Wozu das alles, wenn ich nicht mal eine Schürze kriege?!!}
{237}{v}{Der Boss hat all meine Ideen aus dem Fenster geworfen ...}
{238}{v}{... Dabei meinte ich es so ernst ...}
{239}{v}{::weint fast::}
{240}{v}{... Ich wollte doch nur hilfreich sein ...}
{241}{v}{... und nicht mal danken wird er mir!}
{242}{v}{Und nicht mal über den Kopf streicheln wird er mich!}
{243}{v}{Und ich bin VULVEE, verdammt noch mal, beim Geckoscheiß! Kein Arschloch!}