{100}{}{Du siehst Flayer.}
{101}{}{Du siehst einen Hinterwäldler, der auf seine Herde aufpasst. Mit seiner schmutzigen Schürze und seinen riesigen nackten Händen sieht er aus wie ein Henker.}
{102}{}{Hey, der Schäfer läuft vor dir weg!}

#Ïåğâûé ğàçãîâîğ
{110}{}{Na, du hast mich also erwischt, hm. Ich hab nichts falsch gemacht, ich kümmer mich nur um meine Brahmins, mehr nicht!}
{111}{}{Warum zum Teufel bist du dann weggelaufen?}
{112}{}{Oh, du bist also keiner von diesen Salt Lake-Narren? Na, dann solltest du hier besser nicht herumschnüffeln.}
{113}{}{Warum nicht?}
{114}{}{Weil die Leute aus der Stadt diese Gegend nicht besonders mögen, und du fährst besser, wenn du nicht weißt, warum.}
{115}{}{Wie auch immer.}
{116}{}{Na schön. Ich geh zurück zu meiner Herde.}
{117}{}{Warte mal. Wer wohnt in diesem großen Hotel? Die Türen sind verschlossen, aber es ist eindeutig bewohnt.}
{118}{}{[Gehen]}

#Î'âå', ê'î â î'åëå æèâå'
{119}{}{Hör zu, Kumpel, du willst das wirklich nicht wissen. Kümmere dich lieber um deinen eigenen Kram, wenn du meinen Rat willst.}
{120}{}{Lass mich in Ruhe!}
{121}{}{}
{122}{}{}

{123}{}{Ach ja? Dann bin ich der zukünftige Sheriff der Salt Lake ... Lass mich in Ruhe!}
{124}{}{Uff ... Na gut, aber komm hinterher nicht angeheult, ich hätte dich nicht gewarnt. Geh zum Tor und läute die Glocke so: einmal kurz, einmal lang und einmal kurz. Der Boss ist hinten, geh direkt zu ihm.}
{125}{}{Na, das klingt schon besser.}
{126}{}{Na gut, ich erzähl's dir! Aber dann ist das dein Problem! Dort leben Salt Lake-Ausgestoßene. Sie sind verzweifelt und vertrauen niemandem. Wenn du wirklich reinmusst, geh zum Tor und läute die Glocke so: einmal kurz, einmal lang und einmal kurz. Der Boss ist hinten, geh direkt zu ihm und sprich mit niemand anderem. Und jetzt lass mich in Ruhe!}

#Â'îğè÷íûå ğåïëèêè
{127}{}{Du bist wieder hier? Junge, ich freu mich ganz und gar nicht, dich zu sehen.}
{128}{}{Hast du Trockenfleisch?}
{129}{}{Ja, tschüss.}
{130}{}{Das war's. Und jetzt lass mich in Ruhe!}
{131}{}{Mit Vergnügen!}

{132}{}{Sag es mir sofort, du Hurensohn, sonst kannst du nicht mehr sprechen, wenn ich mit deinem Kiefer fertig bin!}
{133}{}{Ich gebe dir 100 Dollar für eine Chance auf einen Kontakt.}
{134}{}{Warum sagst du's mir nicht freiwillig? Komm schon, das bleibt unter uns.}
{135}{}{Ich bin nicht hier, um Verstecken zu spielen. Ich muss mit dem Verantwortlichen sprechen.}
{136}{}{Vielleicht können wir uns einigen. Ich weiß, wie das geht.}

#Female character:
{1110}{}{Na, du hast mich also erwischt, was? Ich hab nichts Unrechtes getan, ich kümmer mich nur um meine Brahmins, mehr nicht!}
{1119}{}{Hör zu, das willst du wirklich nicht wissen, Süßer. Kümmere dich lieber um deinen eigenen Kram, wenn du meinen Rat willst.}

