{100}{}{Du siehst eine erhöhte Druckplatte. Sieht aus wie eine Falle.}

# NPC name prepends this line
{101}{}{ sieht eine erhöhte Druckplatte. Sieht aus wie eine Falle.}

{102}{}{Du siehst eine erhöhte Druckplatte.}

# NPC name prepends this line
{103}{}{ sieht eine erhöhte Druckplatte.}

{104}{}{Du löst die Falle aus und weichst dem Geschoss, das aus der Wand geschossen kommt, nur knapp aus.}

# NPC name prepends this line
{105}{}{ löst die Falle aus und weicht dem Geschoss, das aus der Wand geschossen kommt, nur knapp aus.}

{106}{}{Du siehst eine erhöhte Druckplatte, die harmlos aussieht.}