{100}{}{Du siehst eine Truhe.}
{101}{}{Du siehst eine robust wirkende Holztruhe. Sie ist mit einem Vorhängeschloss gesichert.}
{102}{}{Du siehst eine robust wirkende Holztruhe.}
{103}{}{Die Truhe ist mit einem Vorhängeschloss gesichert.}
{104}{}{Fass nicht an, was dir nicht gehört!}
{105}{}{Du wurdest entdeckt.}
{106}{}{Das Schloss wurde bereits geknackt.}
{107}{}{Diese Fertigkeit ist hier nutzlos.}
{108}{}{Dieser Gegenstand nützt hier nichts.}
{109}{}{Das bringt nichts.}
{110}{}{Verschlossen.}
{111}{}{Dein Schlossknacken-Fertigkeit reicht nicht aus, um dieses Schloss zu knacken.}
{112}{}{Geht nicht.}
{113}{}{Du kannst das Schloss nicht knacken.}
{114}{}{Fehlgeschlagen.}
{115}{}{Du hast das Schloss geknackt. Dem Besitzer dieser Truhe wird das kaum gefallen.}
{116}{}{Dietriche dieser Art können nicht für Schlösser dieser Art verwendet werden.}
{117}{}{Erledigt.}
{118}{}{Du brichst das Schloss mit deiner Körperkraft auf. Dem Besitzer dieser Truhe wird das kaum gefallen.}
{119}{}{Du hast nicht genug Kraft, um dieses Schloss aufzubrechen.}
{120}{}{Ughh!}
{121}{}{Dein Dietrich bricht im Schloss ab und verklemmt es.}