{100}{}{Rostige Tür.}
{101}{}{Eine sehr rostige, aber immer noch äußerst stabile Tür. Solche Türen wurden oft in Gefängnissen eingebaut. Man kann sie nicht eintreten!}
{102}{}{Sie lässt sich nicht ohne Schlüssel öffnen.}
{103}{}{Sie lässt sich nicht ohne Schlüssel öffnen.}
{104}{}{Die Tür ist offen!}
{105}{}{Kein Glück.}
{106}{}{Das Schloss gibt nicht nach.}
{107}{}{Du knackst erfolgreich ein kompliziertes Schloss und erhältst 100 Erfahrungspunkte.}
{108}{}{Das Schloss ist mechanisch.}
{109}{}{Du brauchst einen Schlüssel. Oder zumindest einen Dietrich.}
{110}{}{Die Tür ist dafür zu stabil.}
{111}{}{Verdammt!}
{112}{}{Du schließt die Tür mit dem Schlüssel ab.}
{113}{}{Die Tür ist verschlossen.}
{114}{}{Das Schloss ist bereits geknackt.}
{115}{}{Das Schloss wurde bereits geknackt. Man kann es nicht zweimal knacken.}
