{100}{}{Ein Wasserspender mit Wasser.}
{101}{}{Ein leerer Wasserspender.}

{102}{}{Du siehst einen Spender voller sauberem Quellwasser.}
{103}{}{Du siehst einen leeren Spender. Jemand hat das ganze Wasser ausgetrunken.}

{104}{}{In diesem Spender ist kein einziger Tropfen Wasser mehr.}
{105}{}{Du fuellst eine Feldflasche mit reinem Quellwasser.}
{106}{}{}

{107}{}{In diesem Spender ist noch etwas Wasser. Wenn du es auffangen willst, brauchst du ein Gefäß.}
{108}{}{Du brauchst eine Flasche.}
