{100}{}{Selbstgebrannter Schnaps.}

{101}{}{Du siehst eine Brennblase. Sie hat bereits eine ganze Dose Selbstgebrannten destilliert!}
{102}{}{Du siehst eine Brennblase. Der Schnaps darin ist noch nicht fertig.}
{103}{}{Du siehst eine Brennblase. Verlassen und nutzlos.}

{104}{}{Die Brennblase ist leer.}
{105}{}{Leer}
{106}{}{Das ist nichts für dich! Reiz Jackson nicht, solange er in der Nähe ist.}
{107}{}{Versuch's noch einmal – und du bekommst Ärger!}
{108}{}{Erledigt!}
{109}{}{Du hast dir ein paar Flaschen Schnaps unter den Nagel gerissen.}
{110}{}{Du hast dreist ein paar Flaschen Schnaps gestohlen.}

{111}{}{Der Mondschein ist noch nicht gebrannt. Warte ein paar Stunden.}
{112}{}{He! Ihr Arschlöcher! Wer von euch hat meinen Schnaps gesoffen? Wenn ich einen von euch dabei erwische, reiße ich euch die verdammten Arme aus!}