{100}{}{Ein Hebel.}
{101}{}{Du siehst den Steuerhebel für die Brücke.}
{102}{}{Dank dir wird diese alte Brücke dem Stamm noch viele Jahre dienen.}

#Èñïîëüçîâàíèå ğóêîé
{110}{}{Dieser Hebel scheint mit nichts verbunden zu sein.}
{111}{}{Irgendetwas sagt dir, dass dieser Hebel nicht immer nur zur Dekoration diente.}
{112}{}{Hmm ...}
{113}{}{Irgendetwas sagt dir, dass die Brücke verschwunden ist.}
{114}{}{Das brauchst du nicht mehr.}

#Èñïîëüçîâàíèå ïğåäìåòîâ è íàâûêîâ
{120}{}{Nein, das hilft hier nicht weiter.}
{121}{}{Ein Seil ist bereits vorhanden.}
{122}{}{Gute Idee. Aber mit deinen Wissenschaftsfähigkeiten wird das nie funktionieren.}
{123}{}{Gute Idee. Aber mit deinen Reparaturfähigkeiten wird das nie funktionieren.}
{124}{}{Du benutzt das Seil, um den oberen Schacht mit dem Hebel zu verbinden und so einen Flaschenzug zu bauen – aber es gibt nichts, womit du etwas hochziehen könntest.}
{125}{}{Der Hebel funktioniert, ist aber mit nichts verbunden.}
{126}{}{Der Hebel ist mit einem Seil am oberen Schacht befestigt.}
