{100}{}{}
{101}{}{}

{110}{}{Diese Holzbretter können noch zum Bauen verwendet werden.}
{111}{}{Diese Bretter brauchst du nicht mehr.}
{112}{}{Bei deiner Statur kann das Tragen solcher Gewichte zu Verletzungen führen.}
{113}{}{Uff ...}
{114}{}{Das wird hier wohl kaum von Nutzen sein.}
{115}{}{Bau abgeschlossen.}
{116}{}{Du hast den beweglichen Teil der Brücke gebaut.}
{117}{}{Diese Holzbretter können zum Bauen verwendet werden.}
{118}{}{Nur ein paar Holzbretter.}
