{100}{}{Du siehst ein funktionierendes Terminal.}
{101}{}{Du siehst ein funktionsfähiges Computerterminal.}

#Çàïóñê êîìïüşòåğà:
{110}{}{Du kannst dieses Terminal erst benutzen, wenn du die Stromversorgung wiederhergestellt hast.}
{111}{}{Kein Strom.}
{112}{}{Dieses Terminal funktioniert, kann aber keine Verbindung zum Server der Station herstellen, der sich in einem anderen Teil des Bunkers befindet.}
{113}{}{[Verlassen]}
{114}{}{Dir fehlt das nötige wissenschaftliche Wissen, um diese Art von Software effektiv zu nutzen.}

#Ãëàâíîå ìåíş:
{115}{}{Willkommen beim Rundfunknetz des Lovelock-Informationskanals.}
{116}{}{[Nach Aufzeichnungen über frühere Sendungen suchen]}
{117}{}{[Alle Frequenzen nach einem Signal absuchen]}
{118}{}{}
{119}{}{}
{120}{}{}
{121}{}{[Das Leitbild dieser Station lesen]}
{122}{}{[Ende]}
{123}{}{[Zum Hauptmenü zurückkehren]}
{124}{}{[Ende]}

#Ôóíêöèè ñòàíöèè
{150}{}{Zugriff gewährt. Suche läuft ... Suche abgeschlossen. Der Lovelock-Radiosender ist für streng geheime Rundfunksendungen der Regierung und des Militärs vorgesehen. Alle Beschäftigten müssen eine Geheimhaltungsvereinbarung zu sämtlichen Informationen unterzeichnen, die sie im Verlauf des Empfangs, der Verarbeitung und der Übertragung von Nachrichten über den Lovelock-Radiosender erhalten. Zu den derzeitigen Hauptaufgaben gehören: Produktion, Verarbeitung und Übertragung von Funksignalen zwischen militärischen Einrichtungen, streng geheimen Laboratorien, dem Vault-Netzwerk und Regierungsmitarbeitern im Bundesstaat Nevada.}

#Èñòîğèÿ òğàíñëÿöèé
{151}{}{Zugriff gewährt. Suche läuft ... Suche abgeschlossen.}
{152}{}{[Die Signalreichweite der Station ermitteln]}
{153}{}{[Alle Frequenzen nach einem Signal absuchen]}
{154}{}{}

#Ïîïûòêà òğàíñëÿöèè
{155}{}{Zugriff gewährt. Programm wird initialisiert ... [du hörst auf allen Kanälen nichts außer weißem Rauschen]}
{156}{}{[Das Archiv früherer Kommunikationskontakte durchsuchen]}
{157}{}{}
{158}{}{[Unter normalen Bedingungen würde die Reichweite der Station den gesamten Bundesstaat Nevada umfassen. Im Notstrombetrieb reicht das Signal der Station jedoch kaum bis Vault City.]}
{159}{}{[Alle Frequenzen nach einem Signal absuchen]}
{160}{}{[Eine Nachricht senden]}
{161}{}{[Niemand antwortet.]}
{162}{}{[Du hörst nichts außer Rauschen.]}
{163}{}{[Alle Frequenzen erneut absuchen]}
{164}{}{}
{165}{}{}
{166}{}{}
{167}{}{}
{168}{}{Suche läuft ... Suche abgeschlossen. (Die Liste besteht größtenteils aus verschiedenen Siedlungen, die vor dem Krieg abgehört wurden. Zu den weiteren Kontakten zählen drei Militärstützpunkte (Sierra, Hawthorne und Area 51), mehrere Vaults (8, 13 und 15) sowie private Laboratorien. All diese Kontakte befinden sich innerhalb Nevadas oder nahe der Staatsgrenze, ihre genauen Standorte sind jedoch nicht aufgeführt. Funker benötigen nicht den genauen Standort eines Kontakts – sie arbeiten einfach auf den jeweiligen Kanälen.)}
{169}{}{Die Funkstation von Lovelock empfängt und sendet Signale auf einem festgelegten Bereich von Kommunikationskanälen, die im Projekt }
{170}{}{ festgelegt wurden. Abhörprogramme sind derzeit nicht in Betrieb.}
{171}{}{[Informationen zu diesem Projekt suchen.]}
{172}{}{Projekt }
{173}{}{ ist ein Kommunikationssystem für verschlüsselte Gespräche zwischen hochrangigen Militär- und Regierungsangehörigen. Es nutzt Signalverschlüsselung, feste, für Zivilisten nicht verfügbare Kommunikationskanäle und ein landesweites Netz von Relaisstationen, die 100 Jahre lang autonom betrieben werden können. Dieses System gewährleistet, dass die Kommunikation höchster Priorität zwischen den Abteilungen selbst unter Notfallbedingungen nicht unterbrochen wird.}
{174}{}{Hmm, dieser Name ist ... vertraut?}
{175}{}{Projekt }
{176}{}{ ist zu Ehren eines der mächtigsten Atomtests der amerikanischen Geschichte benannt.}
{177}{}{Das sind alle Informationen, die ich brauche.}

#Ïàğîëè:
{301}{}{HIROSHIMA}
{302}{}{NAGASAKI}
{303}{}{TRINITY}
{304}{}{CASTLE}
{305}{}{BRAVO}
{306}{}{EASY}
{307}{}{RANGER}
{308}{}{YOKE}
{309}{}{BAKER}
{310}{}{FATMAN}
{311}{}{LITTLEBOY}
