{0}{}{}
{100}{}{Du siehst eine Konsole.}
{101}{}{Du siehst das Passwortterminal. Es scheint eine Tür in der Nähe zu steuern.}
{102}{}{Du hast dieses Terminal bereits benutzt, du brauchst es nicht mehr.}
{103}{}{Das brauche ich nicht.}
{104}{}{Dieses Terminal hat keine Stromversorgung.}
{105}{}{Kein Strom.}

#Íà÷àëî äèàëîãà:
{110}{}{Willkommen. Bitte Passwort eingeben.}
{111}{}{[Versuchen, das Passwort zu hacken]}
{112}{}{[Passwort eingeben]}
{113}{}{[Verlassen]}

{114}{}{Passwort akzeptiert. Willkommen!}
{115}{}{[Fertig]}
{116}{}{Du hackst das Sicherheitssystem und erhältst }
{117}{}{ Erfahrungspunkte.}
{118}{}{Falsches Passwort.}
{119}{}{Wow, es hat funktioniert! Zeit, es sich im Büro von jemandem gemütlich zu machen.}

#Ïğîöåññ ïîäáîğà ïàğîëÿ
{120}{}{Das System akzeptiert nur Passwörter aus Buchstaben des englischen Alphabets. Du musst lediglich die Varianten durchgehen.}
{121}{}{Gib das Passwort ein.}
{122}{}{Du gibst ein: }
{123}{}{?}
{124}{}{Letzten Buchstaben löschen.}
{125}{}{Alles löschen und von vorn anfangen.}
{126}{}{Passwort falsch.}
{127}{}{Passwort akzeptiert. Willkommen!}
{128}{}{Na ja, dann genieße ich eben den Komfort eines fremden Büros.}
{129}{}{Dieses Rätsel übersteigt meine Fähigkeiten im Moment bei Weitem.}
{130}{}{}

{150}{}{A}
{151}{}{B}
{152}{}{C}
{153}{}{D}
{154}{}{E}
{155}{}{F}
{156}{}{G}
{157}{}{H}
{158}{}{I}
{159}{}{J}
{160}{}{K}
{161}{}{L}
{162}{}{M}
{163}{}{N}
{164}{}{O}
{165}{}{P}
{166}{}{Q}
{167}{}{R}
{168}{}{S}
{169}{}{T}
{170}{}{U}
{171}{}{V}
{172}{}{W}
{173}{}{X}
{174}{}{Y}
{175}{}{Z}
{176}{}{-mehr-}
{177}{}{Passworteingabe abschließen.}
{178}{}{Zum Anfang des Alphabets.}
{179}{}{Zurück.}
