{100}{}{Du siehst eine Tür.}
{101}{}{Du siehst eine Tür mit einem Schlüsselkartensystem.}
{102}{}{Diese Tür ist zu stabil.}

{110}{}{Kein Strom.}
{111}{}{Diese Tür lässt sich während eines Stromausfalls nicht öffnen.}
{112}{}{Schlüsselkarte erforderlich.}
{113}{}{Zum Öffnen des elektronischen Schlosses ist eine Schlüsselkarte erforderlich.}
{114}{}{Diese Tür ist bereits offen.}
{115}{}{Das bringt nichts.}

{116}{}{Ohne Strom bringt das nichts.}
{117}{}{Das bringt hier nichts.}
{118}{}{Sie ist offen.}
{119}{}{Schlüsselkarte akzeptiert. Die Tür ist offen.}
{120}{}{Erledigt.}
{121}{}{Du hast das elektronische Schloss erfolgreich überlistet. Die Tür ist offen.}
{122}{}{}
{123}{}{Du schaffst es nicht, das elektronische Schloss zu knacken.}
{124}{}{Fehlgeschlagen.}
{125}{}{Kein Strom.}
{126}{}{Der verwendete Dietrich passt nicht zu diesem Schloss.}
