{100}{}{Du siehst einen Generator.}
{101}{}{Du siehst einen gewöhnlichen Generator. Den Beschriftungen nach zu urteilen, ist er für die Automatik der Station zuständig.}

{102}{}{Der Generator ist in schlechtem Zustand, lässt sich aber reparieren.}
{103}{}{Muss repariert werden.}
{104}{}{ Erfahrungspunkte.}
{105}{}{Der Generator ist funktionsfähig und versorgt die Station mit Strom.}
{106}{}{Das bringt nichts.}
{107}{}{Der Generator läuft und muss nicht repariert werden.}
{108}{}{Du reparierst den Generator. Er beginnt laut zu brummen. Du erhältst }
{109}{}{Erledigt.}
{110}{}{Das ist hier nutzlos. Der Generator muss repariert werden.}
{111}{}{Du schaffst es nicht, den Generator zu reparieren.}
{112}{}{Fehlgeschlagen.}