{100}{}{Du siehst einen Generator.}
{101}{}{Du siehst einen gewöhnlichen Generator. Den Beschriftungen nach zu urteilen, versorgt er die zentrale Ausrüstung mit Strom.}

{102}{}{Sieht aus, als hätten die Ameisen diesen Generator beschädigt, aber er lässt sich noch reparieren.}
{103}{}{Reparaturen erforderlich.}
{104}{}{}
{105}{}{Der Generator ist betriebsbereit und versorgt die Station mit Strom.}
{106}{}{Das bringt nichts.}
{107}{}{Der Generator funktioniert und muss nicht repariert werden.}
{108}{}{Du hast den Generator repariert. Er versorgt jetzt den Server mit Strom.}
{109}{}{Erledigt.}
{110}{}{Das bringt hier nichts. Der Generator muss repariert werden.}
{111}{}{Du schaffst es nicht, den Generator zu reparieren.}