{100}{}{Du siehst einen Generator.}
{101}{}{Du siehst einen gewöhnlichen Generator. Den Markierungen nach zu urteilen, versorgt er die Beleuchtung der Station mit Strom.}

{102}{}{Der Generator wurde durch die Explosion beschädigt. Du musst einige Teile ersetzen, um ihn zu reparieren.}
{103}{}{Es fehlen Teile.}
{104}{}{Der Generator funktioniert und versorgt die Station mit Strom.}
{105}{}{Dieser Generator ist funktionsfähig.}
{106}{}{Dieser Generator braucht Ersatzteile, keinen Treibstoff.}
{107}{}{Nutzlos.}
{108}{}{Das hilft hier nicht weiter.}
{109}{}{Erledigt.}
{110}{}{Du ersetzt die beschädigten Teile. Der Generator ist wieder funktionsfähig.}
{111}{}{Ohne den Austausch einiger Teile wird der Generator nicht funktionieren.}