{100}{}{Ein Schalter.}
{101}{}{Du siehst einen Lichtschalter. Er steht auf „Ein“.}
{102}{}{Du siehst einen Lichtschalter. Er steht auf „Aus“.}
{103}{}{Mit diesem Schalter wird die Beleuchtung im unterirdischen Bereich der Station eingeschaltet.}

{110}{}{Du schaltest das Licht aus. Der unterirdische Bereich der Station versinkt in Dunkelheit.}
{111}{}{Du schaltest das Licht im unterirdischen Bereich der Station ein.}
{112}{}{Hmm, das Umlegen des Schalters scheint nichts bewirkt zu haben. Vielleicht ist der Strom ausgefallen?}
{113}{}{Erledigt.}
{114}{}{Es werde Dunkelheit!}
{115}{}{Es werde Licht!}
{116}{}{Es passiert nichts.}
