{100}{}{Ein Kohlkopf.}
{101}{}{Ein riesiger Kohlkopf, aus dem man einen schönen Salat machen kann.}

{102}{}{Leckeres Grünzeug! Dazu etwas brahmin-Fleisch, und schon hast du ein gesundes Abendessen.}
{103}{}{Dieses Gemüse wäre ein gutes Abendessen, wenn man Fleisch dazu hätte. Aber seinem Besitzer wird diese Idee wohl kaum gefallen.}
{104}{}{Na also!}
{105}{}{Du plünderst das Gemüse, um dir ein Sandwich zu machen. Seinem Besitzer wird das wahrscheinlich nicht gefallen. Du dreckiger Dieb!}
