{100}{}{Du siehst ein Computerterminal im Labor.}
{101}{}{Du siehst ein altes Computerterminal im Labor, randvoll mit Forschungsdaten.}

#Ãëàâíîå ìåíş 
{110}{}{Dieser Computer koordiniert die Arbeit aller Abteilungen des Labors. Es gibt jede Menge interessante Informationen. Wähle ein Thema aus.}
{111}{}{Produktionsberichte.}
{112}{}{Experimente.}
{113}{}{Ziele für das nächste Jahr.}
{114}{}{}
{115}{}{}
{116}{}{}
{117}{}{[Zurück]}
{118}{}{[Hauptmenü]}
{119}{}{[Herunterfahren]}

#Îò÷åòû î ïğîèçâîäñòâå
{120}{}{Produkt auswählen.}
{121}{}{Steroide.}
{122}{}{Psychodelika.}
{123}{}{Methamphetamine.}
{124}{}{Medikamente.}
{125}{}{Sonderbestellung von Clean City.}

{130}{}{Dieses Labor versuchte erfolglos, Drogen wie Buffout zu entwickeln, doch unter den örtlichen Arbeitsbedingungen war das zu schwierig. Es wurden Testproben ausgegeben, die später allesamt als mangelhaft eingestuft wurden. Die Proben gelangten jedoch unter die Händler (möglicherweise auf Kosten des Lebens ihrer Kunden).}
{131}{}{Dies ist eines der Hauptprodukte von the Pound. Es wurden verschiedene Arten von Psychodelika hergestellt, darunter LSD, Meskalin und Psilocybin. Der Schwerpunkt lag auf halluzinogenen Chemikalien auf Pilzbasis. Die Produkte waren nicht nur bei den Einheimischen erfolgreich, sondern auch außerhalb von Vegas. Sieht so aus, als wollten viele Menschen in dieser Welt der Realität entfliehen ...}
{132}{}{Daten gelöscht.}
{133}{}{Der Medikamentenvorrat ist klein. Dazu gehören Stimulanzien, einige Schmerzmittel, Heilpulver aus Pflanzen und eine Reihe minderwertiger Drogen. Alle Chargen wurden relativ kürzlich hergestellt, das Labor hatte also zuvor nicht mit solchen Produkten gearbeitet.}
{134}{}{Eine einflussreiche Person aus dem Clean City hat über Mittelsmänner die Herstellung leichter Drogen mit geringem Suchtpotenzial in Auftrag gegeben. Obwohl die Namen nicht aufgeführt sind, wird klar, dass the Pound seine Leute in Clean City hat.}

#İêñïåğèìåíòû
{140}{}{The Pound führte eine Reihe von Experimenten durch: sowohl zur Nachbildung alter Drogen und Medikamente als auch zur Entwicklung völlig neuer. Hier scheinen kluge Köpfe gearbeitet zu haben.}
{141}{}{Experiment „Psycho“.}
{142}{}{Experiment „Buffout“.}
{143}{}{Experiment „Mentats“.}
{144}{}{Experimente mit Psychedelika.}
{145}{}{Weitere Experimente.}

{150}{}{Diese alte Droge militärischen Ursprungs ist für die Führung zu einem echten Allheilmittel geworden. Eine Zeit lang beschäftigte sich das Labor ausschließlich mit Versuchen, Psycho eigenständig herzustellen. Ein solches Produkt hätte the Pound große Gewinne eingebracht. Doch die örtlichen Bedingungen, die Ausrüstung und der Mangel an erforderlichen Komponenten führten nur dazu, dass die Forschung eingestellt wurde.}
{151}{}{Wie bei „Psycho“ wurde das Projekt eingestellt, da es unter den örtlichen Bedingungen nicht hergestellt werden konnte.}
{152}{}{Anders als die Experimente mit „Buffout“ und „Psycho“ hätte „Mentats“ in Massenproduktion gehen können ... Doch die Droge erwies sich als unrentabel. Angesichts der hohen Arbeits- und Ressourcenkosten konnte the Pound nicht mit den Vorkriegsbeständen in der Region konkurrieren. Außerdem war der aktuelle Bedarf an diesem Produkt eindeutig geringer als an einer Reihe anderer Drogen.}
{153}{}{Psychedelika hatten lange Zeit einen wichtigen Platz in der Produktion ... bis sie den Markt so überschwemmten, dass the Pound selbst auf Vertriebsprobleme stieß. Daraufhin ordnete die Führung eine Reihe von Experimenten mit LSD und anderen psychedelischen Substanzen an, um sie gefragter zu machen. Das Projekt „Brom-LSD“ sollte beispielsweise LSD ohne psychedelische Wirkung entwickeln, das Menschen mit verschiedenen Hirnerkrankungen helfen könnte, etwa bei Clusterkopfschmerzen. Schade, dass Clean City beschloss, Psychedelika vollständig vom Markt zu verdrängen.}
{154}{}{Die Führung von the Pound versuchte, sich in Clean City zu legalisieren, um die Angriffe der Polizei zu beenden und den Verschwörungsfaktor zu beseitigen. Dazu versuchte the Pound, mit der Herstellung verschiedener „friedlicher“ Medikamente wie Aufputschmitteln und Schmerzmitteln zu beginnen.}

#Öåëè íà ñëåäóşùèé ãîä
{160}{}{Die wichtigsten Ziele: 1. „Brom-LSD“ fertigstellen; 2. Eine stabile Lieferroute zu New Reno organisieren; 3. Die Sterberate unter den Sklaven um 15% und mehr senken; 4. Das Rezept für ein Kampf-Aufputschmittel aus Reno nachbilden.}

#Äîñòèæåíèå "Çíàõàğü"
{170}{}{Mehr über Heilkräuter erfahren.}
{171}{}{Hier befindet sich die Wissensdatenbank über die wohltuenden Eigenschaften verschiedener Heilkräuter: Xanderwurzel, Broc-Blume, Nachtschatten und viele andere. Ein örtlicher Wissenschaftler sammelte Informationen aus allen Winkeln der Region, untersuchte Pflanzen und führte Experimente zur Herstellung von Drogen und Betäubungsmitteln durch. Nicht jeder Neugierige konnte diese wissenschaftlichen Forschungen verstehen.}
{172}{}{[Daten untersuchen]}
{173}{}{[Verlassen und zum nächsten Abschnitt gehen]}
