{100}{}{Du siehst einen Wassertank.}
{101}{}{Du siehst einen riesigen Tank voller fauligem Regenwasser. Er ist durchgerostet und an mehreren Stellen undicht.}
{102}{}{Du siehst einen riesigen Wassertank. Er hat schon bessere Tage gesehen, aber er ist noch dicht.}
{103}{}{Du kannst den Wassertank im Kampf nicht untersuchen!}

#Îïèñàíèå ïğè şçàíüå èëè èñïîëüçîâàíèè íàâûêîâ
{110}{}{Es ist einfach nur ein riesiger Wassertank.}
{111}{}{Du siehst einen riesigen Wassertank. Er ist fast leer.}
{112}{}{Wie neu!}
{113}{}{Alle Lecks im Wassertank sind abgedichtet. Der Stamm wird sich freuen, davon zu hören.}

#Îïèñàíèå â ğåæèìå äèàëîãå
{120}{}{Du siehst den undichten Wassertank des Stammes.}
{121}{}{[Den Tank genauer untersuchen]}
{122}{}{[Versuchen, den Tank zu reparieren]}
{123}{}{[Ihn in Ruhe lassen]}

{124}{}{Der Tank ist an mehreren Stellen durchgerostet und leckt ständig. Er lässt sich reparieren, aber du brauchst eine Menge Altmetall.}
{125}{}{Du brauchst mehr Altmetall, um das zu reparieren.}
{126}{}{(Ich habe nicht die nötigen Fähigkeiten, um das zu reparieren.)}
{127}{}{[Den Wassertank reparieren.]}
{128}{}{Die Reparatur dieses Tanks wird langwierig, schwierig und sehr materialaufwendig.}
{129}{}{Mit etwas Überlegung und geschickter Hand gelingt es dir, die Lecks im Tank mit mehreren Stücken Altmetall abzudichten. Dieser Tank wird dem Stamm noch viele Jahre dienen.}
{130}{}{Großartig!}
