{100}{}{Die alte Mauer zerfällt vollständig zu Staub.}

{101}{}{Du untersuchst den Wassertank und findest darin trübes Wasser. Offenbar trinken die Raider das, sofern sie nichts Stärkeres bekommen können. Wahrscheinlich leiden sie an Ruhr. Und wenn du das Wasser noch ein wenig verunreinigst, wird es selbst für sie tödlich sein.}
{102}{}{[Gehen]}
{103}{}{Du hast etwas Gift, aber es reicht nicht für so viel Wasser.}
{104}{}{Du hast genug Gift, um alle Raider tödlich zu vergiften.}
{105}{}{Gift in den Wassertank schütten.}
{106}{}{Du hast tödliches Gift in den Wassertank geschüttet. Jeder, der dieses Wasser trinkt, wird nun sterben ... Zumindest hoffst du darauf. Es lohnt sich, in einem Tag zurückzukommen und diese Vermutung zu überprüfen.}
{107}{}{}
{108}{}{Das Wasser ist immer noch ungenießbar.}
{109}{}{Offenbar tranken die Raider das, wenn sie nichts Stärkeres bekommen konnten. Sie leiden bestimmt an Ruhr.}
{110}{}{Das Wasser ist immer noch vergiftet.}
{111}{}{Eine Dosis Gift reicht nicht aus, du brauchst mindestens zwei weitere. [Verlassen]}
{112}{}{Zwei Dosen Gift reichen nicht aus. Wenn jemand am Leben bleibt, wird er merken, was passiert ist. Wenn du doch nur noch eine Dosis bekommen könntest ... [Verlassen]}
{113}{}{Sieht aus, als hätte das Gift gewirkt. Die Raider sind alle tot. Und so wie es aussieht, war ihr Tod weder leicht noch schmerzlos.}

{114}{}{Nicht während eines Kampfes!}
{115}{}{Die Raider haben früher dieses schlammige Wasser getrunken. Aber jetzt will es niemand mehr.}
{116}{}{Dieses Wasser ist vergiftet.}
