{100}{}{Da gehst du besser nicht rein}
{101}{}{Du kannst da nicht rein}
{102}{}{Weg da!}
{103}{}{Du solltest da nicht hingehen}
{104}{}{Hey, ich hab dich noch im Auge!}
{105}{}{Wo glaubst du, gehst du hin?}
{106}{}{Die Hütte des Häuptlings liegt in der anderen Richtung, Fremder.}
{107}{}{Was willst du dort?}
{108}{}{Was willst du dort?}
{109}{}{Was hast du vor?}
{110}{}{Komm sofort zurück!}
{111}{}{Suchst du Ärger?}

{112}{}{Fremder, das ist nicht deine Hütte!}
{113}{}{Fremder, raus aus dieser Hütte!}
{114}{}{Fremder, der Häuptling wohnt in der anderen Hütte.}
{115}{}{Du warst nicht eingeladen.}

{116}{}{Wo versteckst du dich, Fremder? Komm raus, du machst es nur noch schlimmer für dich!}