{100}{}{Körper.}
{101}{}{Der Körper steckt bis zur Brust im Nest, aber was herausragt, scheint noch zu atmen!}

#Äèàëîã:
{102}{}{Äh... Mghhhh...}
{103}{}{Hey! Kannst du mich hören? Verstehst du, was ich sage?}

{104}{}{Maaaahh...}
{105}{}{Du siehst nicht besonders gut aus. Vielleicht sollte ich dich aus dem Nest ziehen?}
{106}{}{[Lass ihn in Ruhe]}

{107}{}{Ugh... Hilfe...}
{108}{}{[Versuche, ihn herauszuziehen]}
{109}{}{[Lass ihn in Ruhe]}

#Òàéìåğíàÿ ñöåíà:
{110}{}{Hey, steh auf, bevor wir gefressen werden!}
{111}{}{Komm schon!}
{112}{}{Heilige Scheiße!...}
{113}{}{Du hast Glück, noch am Leben zu sein!}
{114}{}{Was zum... Moment, mir ist irgendwie komisch...}
{115}{}{Was?}
{116}{}{A-A-A-A-A-A-AH!!!}

{117}{}{Was zur Hölle war das?}
{118}{}{Dem armen Kerl war das Ende gewiss. Offenbar ist er nicht gestorben, als er in diese Biomasse gesogen wurde, sondern als die Biomasse durch Gas starb. Dieser Mann starb mit ihr.}

#Òàéìåğíûå ïëàâàşùèå ğåïëèêè
{120}{}{::stöhn::}
{121}{}{::surr::}
{122}{}{Ooh...}
{123}{}{Hurr...}
{124}{}{Mmmph...}
{125}{}{Hilfe...}

#Ïîñëå âûïóñêà ãàçà
{200}{}{Dieser Ghul ist hinüber. Offenbar ist er nicht gestorben, als er in diese Biomasse gesogen wurde, sondern als die Biomasse durch Gas starb. Dieser Mann starb mit ihr.}
{201}{}{[Durchsuche die Leiche nach Wertgegenständen]}
{202}{}{[Leiche liegen lassen]}
{203}{}{Diese Überreste interessieren dich jetzt nicht mehr.}
{204}{}{Unerwartet findest du in den Überresten eine rote Schlüsselkarte.}
{205}{}{Hier gibt es sonst nichts.}
