{100}{}{Du siehst einen Boxsack.}
{101}{}{Du siehst einen Boxsack. Du hast das Gefühl, er lädt dich dazu ein, ihn auszuprobieren. Du glaubst fast, in deinem Kopf die Worte „Lass dir diese Gelegenheit nicht entgehen!“ zu hören.}
{102}{}{An diesem Sack kannst du deine Fäuste aufwärmen und neue Kampftechniken ausprobieren.}
{103}{}{Hm, warum nicht?}
{104}{}{Der Sack ist durch dein Training so abgenutzt, dass er unbrauchbar geworden ist.}
{105}{}{Dieser Sack ist nutzlos.}
{106}{}{Dieser Sack könnte dir beim Trainieren deiner Fertigkeiten helfen, aber sie sind bereits zu hoch.}
{107}{}{Trainieren? Das brauche ich nicht mehr ...}
{108}{}{Du trainierst etwa eine Stunde lang und steigerst deinen Nahkampf-Wert um 1%.}
{109}{}{Gut.}

{110}{}{Du solltest nicht trainieren, solange Gegner in der Nähe sind.}
{111}{}{Du darfst kein Risiko eingehen – überall sind Aliens.}