{100}{}{Du siehst eine Tür.}
{101}{}{Eine elektronische Tür. Leider wird sie sich ohne Strom niemals öffnen.}
{102}{}{Eine elektronische Tür. Wegen der instabilen Stromversorgung funktioniert sie unvorhersehbar.}
{103}{}{Ohne Strom lässt sich die Tür nicht öffnen.}
{104}{}{Die Stromversorgung ist instabil, daher reicht die Leistung momentan nicht aus, um die Tür zu öffnen.}
{105}{}{Eine elektronische Tür. Irgendwo muss es ein Notöffnungssystem geben.}
{106}{}{Deine Fähigkeiten helfen dir hier nicht weiter. Suche nach einem Notöffnungssystem.}
{107}{}{Zugangsschlüssel erforderlich.}
{108}{}{Ein Zugangsschlüssel ist erforderlich, aber du hast keinen. Irgendwo muss es einen Notöffnungsmechanismus geben.}
