{100}{}{Du siehst eine Tür.}
{101}{}{Du siehst eine Tür, die von einem Zutrittskontrollsystem mit strengen Berechtigungsregeln gesteuert wird.}

{110}{}{Zugang gewährt.}
{111}{}{Zugriff verweigert.}
{112}{}{Das Sicherheitssystem blockiert die Tür. Finde einen Weg, dir Zutritt zu verschaffen.}
{113}{}{Du hast bereits Zugang zu dieser Tür.}
{114}{}{Das bringt nichts.}
{115}{}{Mit bloßen Händen kannst du diesen komplexen Sicherheitsmechanismus nicht überwinden. Benutze einen Dietrich oder finde einen anderen Weg hinein.}
{116}{}{Dietrich oder Zugangsberechtigung erforderlich.}
{117}{}{Diese Tür ist durch ein mehrstufiges Sicherheitssystem verriegelt. Sie lässt sich mit einer Schlüsselkarte oder von der Kontrollzentrale aus öffnen.}
{118}{}{Du knackst dieses ausgeklügelte elektronische Schloss erfolgreich.}
{119}{}{}
{120}{}{Erledigt.}
{121}{}{Du schaffst es nicht, diesen komplexen Sicherheitsmechanismus zu knacken.}
{122}{}{Fehlgeschlagen.}
{123}{}{Die Schlüsselkarte gewährt dir Zugang.}