{0}{}{.}
{100}{}{Es ist eine Gasfreisetzungsanlage.}
{101}{}{Du siehst eine Anlage, die dafür gedacht ist, Gas in die Hangarbelüftung einzuleiten.}
{102}{}{Das kannst du nicht im Kampf tun!}

{110}{}{Du setzt eine Gasflasche in die Anlage ein.}
{111}{}{Erste Gasflasche eingesetzt}
{112}{}{Zweite Gasflasche eingesetzt}
{113}{}{Dritte Gasflasche eingesetzt}
{114}{}{Die Anlage ist voll funktionsfähig. Jetzt musst du nur noch den Code eingeben und den Knopf drücken.}

{120}{}{Diese Anlage würde Giftgas in die Belüftung einleiten, aber es ist keine einzige Gasflasche angeschlossen.}
{121}{}{Diese Anlage kann nur betrieben werden, wenn drei Gasflaschen angeschlossen sind.}
{122}{}{Gasflaschen benötigt}
{123}{}{Nicht genügend Gasflaschen}
{124}{}{Diese Anlage hat ihren Zweck erfuellt.}
{125}{}{Anlage unbrauchbar}
{126}{}{Fertig.}

{127}{}{Code eingeben.}
{128}{}{Der Behälter ist vollständig gefuellt. Jetzt musst du nur noch den Code eingeben und den Knopf drücken.}

{129}{}{0}
{130}{}{1}
{131}{}{2}
{132}{}{3}
{133}{}{4}
{134}{}{5}
{135}{}{6}
{136}{}{7}
{137}{}{8}
{138}{}{9}

{139}{}{-weiter-.}
{140}{}{Zurück.}
{141}{}{Fertig.}
{142}{}{Löschen.}
{143}{}{ -- }
{144}{}{Code: }

{145}{}{Code falsch.}
{146}{}{Fertig.}
{147}{}{Löschen und von vorn beginnen.}

{148}{}{Die Anlage ist voll funktionsfähig. Jetzt musst du nur noch den Code eingeben und den Knopf drücken.}
{149}{}{Die Freisetzung einleiten.}
{150}{}{Code akzeptiert! Die Anlage ist betriebsbereit. Du musst nur noch den Knopf drücken.}

{151}{}{Warnung! Tödliches Gas wird gleich in das Belüftungssystem geleitet. Bestätigen?}
{152}{}{Ja.}
{153}{}{Nein, das machen wir später.}
{154}{}{Warnung! Tödliches Gas wird gleich in das Belüftungssystem geleitet! Verlasse sofort das Gelände. Du hast }
{155}{}{[Start]}
{156}{}{[Verlassen]}

{157}{}{Warnung! }
{158}{}{ Sekunden bis zur Freisetzung!}
{159}{}{ Sekunden bis zur Freisetzung.}
{160}{}{Gas wurde freigesetzt!}

#Æåíñêèå ğåïëèêè:
{1152}{}{Ja.}