{0}{}{.}
{100}{}{Kombinationssafe.}
{101}{}{Du siehst einen stabil wirkenden Safe mit Zahlenschloss.}

#Èñïîëüçîâàíèå ïğåäìåòîâ è ñêèëëîâ:
{110}{}{Das kannst du im Kampf nicht tun!}
{111}{}{}
{112}{}{Einer der Codes hat den Safe geöffnet!}
{113}{}{Verschlossen}
{114}{}{Der Safe ist mit einem Zahlenschloss verschlossen.}

#Èñïîëüçîâàíèå ïğåäìåòîâ
{120}{}{Der Safe ist mit einem Drehscheibenkombinationsschloss verschlossen. Da es so gut wie nie benutzt wurde, wäre es nahezu unmöglich, es nach Gehör zu knacken.}
{121}{}{[Code einstellen]}
{122}{}{[Zu knacken versuchen]}
{123}{}{[Gehen]}

{124}{}{Code: }
{125}{}{ -- }
{126}{}{}
{127}{}{}
{128}{}{}
{129}{}{}

{130}{}{1}
{131}{}{2}
{132}{}{3}
{133}{}{4}
{134}{}{5}
{135}{}{6}
{136}{}{7}
{137}{}{8}
{138}{}{9}
{139}{}{0}

{140}{}{[Mehr]}
{141}{}{[Zurück]}
{142}{}{[Entf]}
{143}{}{[Fertig]}
{144}{}{}

{145}{}{Der Code ist falsch.}
{146}{}{Löschen und erneut versuchen.}
{147}{}{[Fertig]}

{150}{}{Der Code stimmt! Der Tresor öffnet sich.}
{151}{}{Mit deiner Wahrnehmung würdest du einen Schuss nicht hören, selbst wenn er direkt neben deinem Ohr abgefeuert würde, geschweige denn ein Schloss nach Gehör knacken.}
{152}{}{Deine Fähigkeiten reichen bei Weitem nicht aus, um dieses Schloss zu knacken. Versuch es gar nicht erst, das ist viel zu schwierig für dich.}
{153}{}{Nichts passiert. Versuch es noch einmal und pass besser auf.}
{154}{}{[Erneut versuchen]}
