{100}{}{Du siehst ein Steuergerät.}
{101}{}{Du siehst ein Steuergerät, das die Gebäude der Basis vom Umspannwerk aus mit Strom versorgt. Es ist beschädigt.}
{102}{}{Du siehst das Steuergerät, das die Gebäude der Basis vom Umspannwerk aus mit Strom versorgt. Es brummt und liefert Strom.}

{103}{}{Am Steuergerät sind Bauteile durchgebrannt und Kabel gerissen. Du musst sie ersetzen.}
{104}{}{Die Bauteile müssen ersetzt werden.}
{105}{}{Diese Anlage funktioniert einwandfrei und muss nicht repariert werden.}
{106}{}{Alles ist in Ordnung.}

{107}{}{Hier ist das kaum angebracht.}
{108}{}{Es ist nutzlos.}

{109}{}{Dieser Generator muss nicht aufgeladen werden, er braucht Ersatzteile.}
{110}{}{Erledigt.}
{111}{}{Ohne einige Teile auszutauschen, kannst du den Generator nicht reparieren.}

{112}{}{Du ersetzt die beschädigten Teile des Generators. Jetzt werden die nächsten Gebäude mit Strom versorgt.}

{114}{}{Deine Reparaturfähigkeit reicht nicht aus.}
{115}{}{Das geht nicht.}
