#Аварийный выключатель в ремсекторе:
{100}{}{Schalter fьr die Notbeleuchtung.}
{101}{}{Du siehst den Schalter fьr die Notbeleuchtung auf dieser Etage.}
{102}{}{Du schaltest die Beleuchtung in allen Korridoren der Etage ein.}
{103}{}{Du schaltest die Beleuchtung in allen Korridoren der Etage aus.}

#Обычный выключатель света в лаборатории:
{110}{}{Das ist ein Lichtschalter.}
{111}{}{Du siehst einen gewцhnlichen Lichtschalter im Labor.}
{112}{}{Du schaltest das Licht im Labor ein.}
{113}{}{Du schaltest das Licht im Labor aus.}

#Обычный включатель света в лаборатории:
{120}{}{Das ist ein Schalter.}
{121}{}{Du siehst einen gewцhnlichen Schalter fьr die Projektoren im Hangar.}
{122}{}{Du schaltest das Licht ein.}
{123}{}{Du schaltest das Licht aus.}
