{100}{}{Du siehst einen Computer.}
{101}{}{Du siehst den Computer eines mächtigen Sicherheitsdienstes.}

{102}{}{Du siehst einen Computer des Sicherheitsdienstes.}
{103}{}{[Abbrechen]}
{104}{}{[Weiter]}

#Àêòèâàöèÿ áîìáû:
{105}{}{Hm ... Selbstzerstörungsprotokoll – was ist das?}

{109}{}{Wie zu erwarten, löst dieser Befehl die Selbstzerstörung des Hangars und der darunterliegenden Ebenen aus. Der Befehl aktiviert einen Nuklearsprengkopf mit einer Plutoniumladung von 0,3 Kilotonnen, der in den unteren Ebenen eingemauert ist. Wenn du ihn aktivierst, musst du verdammt schnell rennen, um nicht von der Druckwelle getroffen zu werden.}
{110}{}{Versuche, ins System einzudringen und das Protokoll zu aktivieren}
{111}{}{[Diesen Bereich verlassen]}

{112}{}{Um dieses Schutzsystem zu knacken, musst du schon fast ein Computergenie sein. Das übersteigt eindeutig deine Fähigkeiten.}
{113}{}{}
{114}{}{Du findest einen Weg, das Schutzsystem zu umgehen und das Selbstzerstörungsprotokoll des Hangars zu aktivieren.}
{115}{}{Na gut, Zeit, es zu tun!}
{116}{}{Auf keinen Fall. Lass das Ding so, wie es ist.}
{117}{}{Wähle die Verzögerung für die Aktivierung des Protokolls.}

{119}{}{Du stellst die Zeit ein und drückst beherzt den roten Knopf. Jetzt solltest du an deine Zukunft denken, wenn du nicht Teil der Hintergrundstrahlung werden willst ...}
{120}{}{[Renn, verdammt noch mal!]}

{121}{}{1 Minute.}
{122}{}{2 Minuten.}
{123}{}{3 Minuten.}
{124}{}{4 Minuten.}
{125}{}{5 Minuten.}
{126}{}{Aktivierung ablehnen und gehen.}
{127}{}{[Zum Hauptmenü zurückkehren]}
{128}{}{Abbrechen. Zum Hauptmenü zurückkehren.}

{129}{}{Du findest die Montagepläne. Der Vorgang scheint jedoch zu kompliziert für dich zu sein. Ohne besondere Kenntnisse auf dem Gebiet der Sabotage helfen dir diese Pläne nicht weiter.}

{131}{}{Funktioniert nicht}
{132}{}{Terminal ist offline.}

#Àêòèâàöèÿ òóğåëåé:
{200}{}{Das Betriebsprogramm der Geschütztürme untersuchen.}
{201}{}{Das Betriebsprogramm der Geschütztürme starten.}
{202}{}{Zum Hauptmenü zurückkehren.}
{203}{}{Herunterfahren.}
{204}{}{Das Programm scheint nicht zu funktionieren.}
{205}{}{Nach Berichten suchen.}
{206}{}{Auf dem Computer befindet sich ein unvollständiger Fehlerbericht, aber kein eindeutiger Lösungsalgorithmus für das Programm.}
{207}{}{Den Quellcode ansehen.}
{208}{}{Das ist zu schwierig für dich.}
{209}{}{Nach sechs Stunden Codeanalyse stellst du fest, dass der Fehler in einer zyklischen Unterroutine lag, die die Signalvariablen der Geschütztürme überprüfte. Da Signal und Zyklus jedoch nicht synchron waren, hielt das Programm dies für eine Fehlfunktion des Computers und startete ihn neu. Du könntest den Zyklus zurücksetzen, um das Problem zu beheben und das Programm wieder zum Laufen zu bringen.}
{210}{}{Den Code umschreiben, damit die Aliens vollständig vernichtet werden, und anschließend neu kompilieren.}
{211}{}{Bereit. Programm starten?}
{212}{}{Ja.}
{213}{}{Nein, offline lassen.}
{214}{}{Erledigt! Das Programm läuft wieder. Auf den Überwachungsmonitoren siehst du, wie die Geschütztürme auf Aliens schießen, die hinter den Wänden des Hangars hervorkriechen.}
{215}{}{Nicht mit deiner Intelligenz.}
{216}{}{Mit deiner Bildung kannst du *absolut* nichts anfangen.}
{217}{}{Mit mehr Bildung hättest du den Code vielleicht lesen können.}
{218}{}{Mit mehr Bildung hättest du den Code vielleicht verstanden.}
