{100}{}{Du siehst einen Laborcomputer.}
{101}{}{Du siehst einen Laborcomputer. Er ist funktionsfähig.}

#Ïîñëå âçëîìà, èçó÷åíèå àğõèâîâ:
{200}{}{Zugriff gewährt. Du kannst Archivberichte und Berechnungen zu verschiedenen Projekten durchsehen.}
{201}{}{Die Dokumentation ansehen.}
{202}{}{Wählen Sie eine Kategorie.}
{203}{}{[Verlassen]}

{204}{}{Berichte über Experimente an „Außerirdischen“.}
{205}{}{Dokumentation zum Gasschutzsystem.}
{206}{}{Dokumentation zum Projekt „Ghost F-31“.}
{207}{}{[Zurück]}
{208}{}{Wählen Sie ein Dokument zum Lesen aus.}

{209}{}{„Versuchsberichte der letzten fünf Quartale“}
{210}{}{„Bericht über die Schwächen der Außerirdischen“}
{211}{}{„Bericht über das Wärmebildsehen der Außerirdischen“}
{212}{}{„Bericht zum Vorfall im Winter 2077“}
{213}{}{„Der Befehl zur Erhöhung der Sicherheitsstufe“}

{214}{}{Die Außerirdischen wurden aufs Äußerste gedemütigt. Jede Woche wurden sie verschiedenen Arten physischer und biologischer Einwirkungen ausgesetzt. Wie sich herausstellte, sind die Außerirdischen starke Tiere mit enormem militärischem Potenzial: Eines von ihnen kann einen ganzen Trupp ausschalten. Wissenschaftler versuchten, sie zu zähmen, um sie später als lebende Waffen einzusetzen. Doch obwohl ihr Kampfpotenzial nie infrage stand, scheiterte der Versuch, sie zu zähmen.}
{215}{}{Sie scheinen keine bekannten Schwächen zu haben. Die einzige Schadensart, die sich als wirksamer als die anderen erwies, ist Feuer. Das einzig einigermaßen Beruhigende ist, dass diese Kreaturen zur Fortpflanzung besondere Bedingungen benötigen: hohe Strahlungswerte, eine warme, feuchte Umgebung und Dunkelheit. Außerdem kommt auf tausend Exemplare dieser Spezies nur ein Weibchen, weshalb die Wahrscheinlichkeit einer Fortpflanzung äußerst gering ist und die Spezies früher oder später aussterben wird. Klingt gut – abgesehen davon, dass der Lebenszyklus der Außerirdischen mehr als 70 Jahre dauert.}
{216}{}{Das erklärt, warum man Außerirdischen im Ödland meist nachts begegnet: Sie sehen mit Wärmebildsicht und richten sich nach der Geschwindigkeit ihrer Beute. Tagsüber halten sie Winterschlaf, denn die warme Umgebung beeinträchtigt ihre Wärmebildsicht und erschwert ihnen die Orientierung. Mit diesem Wissen machten sich die Forscher daran, eine einzigartige Ausrüstung zu entwickeln – ein Korsett, das die Körperwärme eines Menschen verbergen könnte.}
{217}{}{Im Winter 2077 kam es im Labor zu einem Zwischenfall: Durch die Nachlässigkeit des Personals geriet ein Experiment an einer weiblichen Außerirdischen außer Kontrolle. Das Versuchswesen entkam auf den Korridor. Offenbar sind diese Kreaturen nicht dumm, denn die Mutantin erfasste die Lage rasch und floh durch die Lüftungsschächte in die Wüste. Das Militär fand Spuren in den Höhlen von Sektor C, wagte es jedoch nicht, die Soldaten hineinzuschicken, und sprengte sämtliche Ausgänge. Sechs Monate später tauchte die Kreatur erneut auf.}
{218}{}{Der Befehl zur Einrichtung des Kraftfeldsystems erging nach einem Zwischenfall im Winter 2077. Das Militär versuchte, den Schutz vor den Versuchswesen zu maximieren. Offenbar wurde den Verantwortlichen klar, wie sehr sie die Fähigkeiten dieser Kreaturen unterschätzt hatten. Die Kommandeure von Sektor A5 überwachten gemeinsam mit der Wartungsabteilung persönlich den weiteren Ablauf. Auf der ersten Ebene finden sich möglicherweise Informationen darüber, was mit den Kraftfeldern geschehen ist und ob sie derzeit funktionieren. Fest steht jedenfalls, dass Kraftfelder für Außerirdische undurchdringlich sind.}
{219}{}{}

{220}{}{Ein Vermerk mit einem Vorschlag}
{221}{}{Abschlussakten des Projekts}
{222}{}{Zusammenfassung der Systeminstallation}
{223}{}{Wartungspasswörter}

{224}{}{Wie sich herausstellte, beunruhigte die Wissenschaftler ein Zwischenfall im Winter 2077 sehr, bei dem einer der Außerirdischen entkam. Für die Dauer der Experimente sollte ein leistungsstarkes Schutzsystem entwickelt werden. Die wichtigsten Bestandteile dieses Systems waren Kraftfelder und ein Gasschutz. Tödliches Gas, das nur in extremen Fällen eingesetzt werden sollte, konnte über das Belüftungssystem auf allen Ebenen verteilt werden, auch im oberen Bereich des Hangars. Die Leitung hielt diese Lösung für sinnvoll, aber sehr gefährlich, weshalb ein mehrstufiges Auslösesystem installiert wurde.}
{225}{}{Den Unterlagen zufolge wurden alle erforderlichen Arbeiten sowie die Tests erfolgreich abgeschlossen. Die Gasanlage befindet sich im Beobachtungsraum südlich des Labors. Offenbar wurde sie noch nicht eingesetzt.}
{226}{}{Der Bericht beschreibt ausführlich den technischen Ablauf und die Wartungsvorschriften für den Einsatz der Gasanlage. Die Verteilungseinheit befindet sich im Beobachtungsraum. Zum Einschalten ist ein Passwort erforderlich. Außerdem müssen alle drei Gasflaschen angeschlossen sein.}
{227}{}{[Mehr]}
{228}{}{Gasflaschen werden an drei verschiedenen Orten der Basis aufbewahrt: eine im Aufenthaltsraum im Erdgeschoss des Hangars, eine weitere in der Kaserne im Sektor A2 und die dritte im Labor. Die Flaschen liegen in speziellen, passwortgeschützten Tresoren. Bestimmte Personen erhalten die Passwörter per persönlicher Anweisung.}
{229}{}{Nach dem Anschließen der Flaschen wird ein äußerst starkes Gas in das Belüftungssystem geleitet. Es reagiert mit der Säure im Kreislaufsystem der Aliens, die sich dadurch buchstäblich in Biomasse auflösen. Auf Menschen hat das Gas ebenfalls verheerende Auswirkungen: Sie sterben innerhalb weniger Minuten unter Qualen. Daher muss der Einsatz eines Gasangriffs von jedem ... bla, bla, bla. Der Rest ist langweilig.}
{230}{}{Passwörter für Gasstationen und Tresore. Erstens: 153-648-987. Zweitens: 045-896-509. Drittens: 987-469-876. Viertens: 013-486-498.}

{231}{}{"Anordnung zu den Evaluierungsverfahren"}
{232}{}{"Bericht über die Entwicklung des Prototyps"}
{233}{}{"Bericht über die Erprobung des Prototyps"}
{234}{}{"Anordnung zur Verlegung eines Impulsphasengeräts"}

{235}{}{Die Abteilung für wissenschaftliche Forschung leitete das Projekt "Ghost" ein. Ziel war die Entwicklung eines speziellen Korsetts, das die Infrarotstrahlung um den Träger herum abschirmt. Mit einem solchen Modell wären die Träger für Aliens und einige automatisierte Systeme unsichtbar gewesen.}
{236}{}{Abschlussbericht zum Prototyp der F-31-Reihe "Ghost". Es gab ziemlich viele Versionen – leider ohne Erfolg. Die Arbeit dauerte mehrere Monate. Es fehlten nur noch Tests im großen Maßstab.}
{237}{}{Labortests des "Ghost F-31" ergaben positive Ergebnisse. Feldtests zeigten jedoch keine ausreichende Wirkung, da das Gerät nur die Wärmestrahlung eines kleinen Lebewesens – zum Beispiel eines Hundes – vollständig abschirmen konnte. Fazit: Der "Ghost F-31" muss weiterentwickelt werden, um die Polarisation des zentralen Zylinders zu erhöhen. Das ist jedoch nur mit einem speziellen Impulsphasengerät möglich.}
{238}{}{Laut Anordnung sollte der technische Sektor die Lieferung des Impulsphasengeräts vorbereiten, das aus Hawthorne nach Area 51 gebracht werden sollte. Es gibt jedoch keinen Empfangsbericht. Das kann nur eines bedeuten: Das Paket hat sein Ziel nicht erreicht.}
