{100}{}{Du siehst einen Computer.}
{101}{}{Du siehst einen gewöhnlichen Bürocomputer. Das Einzige, was ihn von den anderen unterscheidet, ist, dass er noch funktioniert.}

#Òèïîâûå ôğàçû:
{110}{}{Das System ist betriebsbereit. Gib den folgenden Befehl ein.}
{111}{}{[Abmelden]}

{113}{}{[Zurück]}
{114}{}{[Zurück zur Liste]}
{115}{}{Lies die nächste Notiz.}

#Ñïèñîê ñëóæåáîê:
{120}{}{Sieh dir die Liste der Notizen an.}
{121}{}{Sieh dir die Lagepläne des Hangarbereichs an.}

{122}{}{Berichte über Fehlfunktionen im Geschützsteuerungsprogramm.}
{123}{}{Berichte über Fehler in der Funktion der Kraftfelder.}
{124}{}{Suche nach Erwähnungen von Vault 8.}

#Ñõåìû ïîìåùåíèé:
{130}{}{Wie sich herausstellt, erstreckt sich der Hangar über viele unterirdische Etagen. Einige Etagen können wegen fehlender Zugriffsrechte nicht angezeigt werden. Fast jede Etage ist ein Labor oder eine technische Werkstatt. Offenbar hatte das örtliche Militär einen sehr vollen Terminkalender.}
{131}{}{Sieh dir die erste unterirdische Etage an.}
{132}{}{Auch die erste unterirdische Etage ist ein großes Labor. Außerdem befinden sich hier das Kontrollzentrum der äußeren Verteidigungslinie (gemeint sind offensichtlich die Geschütze und Überwachungskameras), der Notstromgenerator sowie die Steuerungssysteme für die Kraftfelder und die Außenbelüftung. Wegen strenger Sicherheitsvorschriften ist es unmöglich, tiefer als bis zur ersten unterirdischen Etage vorzudringen.}
#Ñëóæåáêè:
{140}{}{Die Notizen des letzten verfügbaren Monats wurden nach Themen sortiert. Meistens handelt es sich um übliche Berichte zu Produktion und Lieferungen, aber ein paar interessante Notizen sind dabei.}
{141}{}{Wähle eine Notiz zum Lesen aus.}

{142}{}{„Über einen Fehler im Steuerungsprogramm der Geschütztürme“}
{143}{}{„Vorschlag zur Installation eines SoS-Kits“}
{144}{}{„Eingangsbestätigung des SoS-Kits“}
{145}{}{„Bericht über die Installation des SoS-Kits“}

{146}{}{Dies ist eine Mitteilung eines Sicherheitsbeamten, in der von einem Fehler im Steuerungsprogramm der Geschütztürme berichtet wird. Das Programm stürzte regelmäßig ab, was wiederum häufige Neustarts zur Folge hatte. Bei jedem Neustart waren die Geschütztürme 10 bis 20 Sekunden lang deaktiviert. Trotz aller Versuche, das Programm zu reparieren, konnten die Ingenieure das Problem nicht lösen. Ihrer Meinung nach wurde es durch Experimente in den unteren Ebenen des Hangars verursacht, die starke elektromagnetische Wellen erzeugten.}
{147}{}{Ein Mitarbeiter des Sicherheitsdienstes schlägt vor, anstelle des Steuerungsprogramms der Geschütztürme ein fortschrittlicheres „System of Security“-Kit zu installieren. Dadurch würde das Problem mit den Neustarts behoben und die Wirksamkeit der Sicherheitssysteme des Hangars erheblich verbessert. Aus der Antwort geht hervor, dass der Vorschlag genehmigt wurde. Du bist dir nicht sicher, aber es sieht so aus, als würde in deinem Vault ein ähnliches System verwendet.}
{148}{}{Laut Empfangsbestätigung hat ein Mitarbeiter des Sicherheitsdienstes ein vollständiges und funktionstüchtiges SoS-Kit erhalten. Das Kit wurde nach Feldtests aus Hawthorne geliefert und anschließend von einheimischen Ingenieuren anhand des Feedbacks weiter verbessert. Der Sicherheitsdienst ordnete an, das Kit an die Sicherheitssysteme anzuschließen und zu prüfen, ob es wie vorgesehen funktioniert.}
{149}{}{Dem Bericht zufolge erzielte die Installation von Hawthornes SoS-Kit nicht die erwarteten Ergebnisse. Aus unbekanntem Grund funktionierte das Kit nicht. Der Hersteller schickte eine Mitteilung, dass das Kit erneut getestet werden müsse, doch es kam keine Antwort. Offenbar hatte das Militär wegen des Ausbruchs des Großen Krieges keine Zeit, sich darum zu kümmern. Am Ende blieb der Hangar ohne äußeren Schutz – die Geschütztürme waren vorübergehend deaktiviert.}
{150}{}{„Anordnung zur planmäßigen Überprüfung der Kraftfelder“}
{151}{}{„Vorschlag zur Verschärfung der Zugangsrechte“}
{152}{}{„Mitteilung über den Beginn der Neuprogrammierung der Kraftfelder“}

{153}{}{Eine Anordnung zur Durchführung regelmäßiger systematischer Inspektionen der Kraftfelder. Der Inspektor muss die Sicherheitsleitung und die Laborleitung über jeden Störfall informieren.}
{154}{}{Das Sicherheitsdezernat schlägt vor, persönliche Schlüsselkarten einzuführen, um die Kraftfelder einzeln steuern zu können. Derzeit kann jedes Mitglied des Personals mit mittlerer Zugangsberechtigung alle Kraftfelder ein- und ausschalten, was offensichtlich nicht den Sicherheitsstandards entspricht. Das Kommando ordnete an, die Kraftfelder neu zu programmieren und magnetische Schlüsselkarten mit hoher Verschlüsselungsstufe herzustellen. Der Auftrag ging an den Wartungssektor, woraufhin die Betriebsart der Kraftfelder angepasst wurde.}
{155}{}{Ein Mitarbeiter des Wartungssektors teilt mit, dass das Kraftfeld wegen der Neuprogrammierung vorübergehend abgeschaltet wird. Die Ausfallzeit beträgt bis zu drei Tage.}
{156}{}{"Ein Bericht über die Ergebnisse der Neuprogrammierung der Kraftfelder"}
{157}{}{Der Wartungssektor meldet positive Ergebnisse bei der Neuprogrammierung der Kraftfelder. Eine Liste aller Personen, die magnetische Schlüsselkarten erhalten haben, wurde erstellt. Außerdem wurde eine neue Betriebsart für die Kraftfelder aktiviert.}
{158}{}{"Eine Mitteilung über Änderungen der Betriebsart der Kraftfelder"}
{159}{}{Der Wartungssektor meldet die Aktivierung des verstärkten Betriebsmodus für die Kraftfelder. Konkret heißt es, dass aufgrund der hohen Auslastung der Anlagen zur Erzeugung der Kraftfelder regelmäßige zweistündige Abschaltungen erfolgen. Wird das Kontrollverfahren, das alle 60 Tage durchgeführt und im Computer auf der ersten unterirdischen Ebene eingetragen werden muss, nicht durchgeführt, schalten sich die Kraftfelder aus Gründen des Brandschutzes automatisch ab. Sie bleiben abgeschaltet, bis sie zwangsweise wieder aktiviert werden (also bis zum nächsten Kontrollverfahren).}

{160}{}{Lies Anordnung 1123.}
{161}{}{Fasse die Daten zum Projekt Vault 8 zusammen.}
{162}{}{Die Informationen sind verstreut, doch einige Dokumente tragen die Kennzeichnung „Projekt Vault 8“.}
{163}{}{Die Anordnung lautete, einen Überwachungsposten zur Beobachtung von Vault 8 einzurichten. Der Posten selbst speicherte keine Daten, sondern leitete sie lediglich an die Spitze der Befehlskette weiter: den Militärstützpunkt Hawthorne. Anschließend wurden die verarbeiteten Daten in Form von Berichten an Area 51 übermittelt.}
{164}{}{Obwohl das Vault-Netzwerk nicht in den Zuständigkeitsbereich von Area 51 fiel, bildete Vault 8 eine Ausnahme. Der Grund dafür war, dass das Vault den Status einer Regierungseinrichtung hatte. Im Notfall sollte Area 51 zum Schutz des Vaults beitragen, sich aber nicht in dessen innere Angelegenheiten einmischen. Es gab sogar den Plan, eine Kraftfeldbarriere um das Gebiet zu errichten, doch Zeit und Geld reichten nicht aus, da bereits zu viele Ressourcen für das Projekt aufgewendet worden waren. Die Bewachung des Vaults war standardmäßig dem Militärstützpunkt Hawthorne zugewiesen. Falls dieser seine Aufgaben nicht erfuellen konnte, sollte Area 51 sie übernehmen.}
