{100}{}{Du siehst einen Computer.}
{101}{}{Du siehst den Wartungscomputer. Er koordiniert den Betrieb der Kraftfelder.}

#Äèàëîã
{110}{}{Dieser Computer steuert die Kraftfelder und Türen auf dieser Ebene des Hangars.}
{111}{}{[Zugang zu allen Türen auf dieser Hangarebene erhalten]}
{112}{}{[Kraftfeldsteuerung]}
{113}{}{[Computer verlassen]}

{114}{}{Erledigt.}

{120}{}{Die Kraftfelder sind durch automatische Feuerlöschanlagen deaktiviert. An diesem Terminal kannst du das aktuelle Kraftfeldprotokoll ändern.}
{121}{}{An diesem Terminal kannst du den aktuellen Betriebsmodus der Kraftfelder ändern.}
{122}{}{[Kraftfelder wiederherstellen]}

{127}{}{[Kraftfeldmodus einstellen]}
{128}{}{Offenbar gibt es zwei Modi. Der Kältemodus verhindert vollständig, dass Gegenstände das Kraftfeld durchdringen. Der Hitzemodus erzeugt ein Feld mit erhöhter Temperatur. Das ist vermutlich sehr gefährlich.}
{129}{}{[Kältemodus einstellen]}
{130}{}{[Hitzemodus einstellen]}
{131}{}{Erledigt. Der Kältemodus ist ausgewählt.}
{132}{}{Erledigt. Der Hitzemodus ist ausgewählt.}