{100}{}{Du siehst einen Computer.}
{101}{}{Du siehst den Computer eines Funkers mit einer ziemlich einzigartigen Benutzeroberfläche.}

{103}{}{Du hast erfahren, dass es auf halbem Weg zwischen Reno und Vault 8 einen großen Funksender gibt.}

#Ïîñëå âêëş÷åíèÿ
{110}{}{Willkommen beim Betriebssystem des Kommunikationsterminals.}

{111}{}{Eine Liste der Funkverbindungen herunterladen.}
{112}{}{Den Sendebericht herunterladen.}
{121}{}{[Verlassen]}

{122}{}{Die Senderliste wurde geladen.}
{123}{}{Die Liste nach Status sortieren.}
{124}{}{Die Liste nach Standort im Bundesstaat Nevada sortieren.}
{125}{}{Nach Datum der Funksendungen sortieren.}
{126}{}{[Zurück]}

{127}{}{Erledigt. [Dir ist aufgefallen, dass der Status der militärisch-staatlichen Sender nur wenigen Orten in Nevada zugewiesen ist. Sie befinden sich an abgelegenen Orten – mitten in Wüsten, in den Bergen usw. –, wo die größte Reichweite erzielt wird und der Sender selbst nur schwer zu finden ist.]}
{128}{}{Offenbar waren diese Funkverbindungen für das Militär sehr wichtig.}
{129}{}{Im Bundesstaat gibt es etliche Kommunikationspunkte, doch eine der Stationen der Militärregierung liegt südöstlich deines Vaults, nahe der Vorkriegsstadt Lovelock (dort sind wahrscheinlich nur noch Ruinen).}
{130}{}{Die letzten Übertragungen fanden ... vor ein paar Jahren statt! Genauer gesagt versuchte jemand außerhalb des Bundesstaats, ein Signal an Area 51 zu senden, doch offenbar antwortete niemand. Es könnte sich jedoch um eine automatisierte Nachricht handeln. Die Signalquelle ist verschlüsselt.}

{131}{}{Bericht geladen.}
{132}{}{Inhalt untersuchen.}
{133}{}{(Bis in die letzten Tage vor dem Großen Krieg waren die Berichte recht spärlich. Kurz vor dem Krieg nahm die Zahl der Übertragungen drastisch zu. Sie fanden meist zwischen Militärhauptquartieren und Feldlaboren statt und waren stark verschlüsselt. Das kommt dir ziemlich verdächtig vor. Wussten die Eliten vom bevorstehenden Krieg und sogar davon, wann er ausbrechen würde? Merkwürdigerweise gab es einige Übertragungen *nach* dem Krieg. Es könnte sich jedoch um eine automatisierte Nachricht handeln.)}
{134}{}{Letzte Übertragung prüfen.}
{135}{}{Zusätzlich zu den üblichen Automatisierungsabläufen hatte jemand an diesem Terminal eine bewegliche Quelle des Funksignals verfolgt. Nachdem du ein wenig in den Parameterwerten gestöbert hast, findest du plötzlich heraus, dass es sich dabei um ... dich handelt. Offenbar hat jemand deine Bewegungen mithilfe einer Wanze verfolgt, die in deinem Pip-Boy platziert wurde.}
{136}{}{Na, das ist ja eine Überraschung ...}

{137}{}{Im Bundesstaat gibt es etliche Kommunikationspunkte, doch eine der Stationen der Militärregierung liegt südöstlich deines Vaults, nahe der Vorkriegsstadt Lovelock. Offenbar befindet sie sich am selben Ort wie das Dorf Cheyenne. Vielleicht solltest du die Einheimischen danach fragen.}
