{100}{}{Kraftfeldgenerator.}
{101}{}{Du siehst einen Kraftfeldgenerator.}

{110}{}{Das Kraftfeld verursacht schweren Schaden.}

#Просто поюзать (рука, предметы,скиллы):
{111}{}{Zugriff verweigert.}
{112}{}{Das Kraftfeld lдsst sich nur mit der hцchsten Zugriffsberechtigung einschalten.}
{113}{}{Das bewirkt nichts.}
{114}{}{Das bringt nichts.}
{115}{}{Ein anderer Ansatz ist nцtig.}

#Включение и выключение поля:
{116}{}{Du schaltest das Kraftfeld aus.}
{117}{}{Du schaltest das Kraftfeld ein.}
{118}{}{Fertig}

#Взлом системы защиты:
{120}{}{Du kannst den Schutz nicht umgehen.}
{121}{}{Fehlgeschlagen.}

{122}{}{Du knackst diesen komplizierten elektronischen Mechanismus erfolgreich, und das Kraftfeld erscheint wieder.}
{123}{}{Du knackst diesen komplizierten elektronischen Mechanismus erfolgreich, und das Kraftfeld verschwindet.}
{124}{}{Erledigt!}
