{100}{}{Du betrittst ein weitläufiges Gelände, auf dem früher Militärflugzeuge landeten. Im Westen kannst du einige Gebäude sehen.}
{101}{}{Du betrittst unbefugt Bundeseigentum. Vor dem Krieg hätte man dich dafür erschossen.}
{102}{}{Du bist in eine Art Spezialhangar gelangt. Vielleicht siehst du gerade etwas, das nur wenige zu Gesicht bekommen haben.}
{103}{}{Eine gewaltige Explosion zerfetzt das Innere des Hangars. Das Gebäude selbst stürzt jedoch wie durch ein Wunder nicht ein.}
{104}{}{Verdammt noch mal!!!}

{105}{}{Dieser Ort sieht aus wie eine Tankstelle für Flugzeuge. In diesen Tanks muss noch Flugbenzin sein.}
{106}{}{}
{107}{}{Der Gestank ist fast unerträglich ...}
{108}{}{Das Giftgas befindet sich noch immer in der Luft des Hangars.}