{100}{}{Du siehst ein Bedienfeld.}
{101}{}{Es ist ein Türsteuerungspult. Von hier aus wird die Tür gesteuert.}
{102}{}{Das Sicherheitssystem erlaubt es, jeweils nur eine Zugangstür zur Oberfläche zu öffnen.}
{103}{}{Das kannst du im Kampf nicht tun!}
{104}{}{Die Tür ist bereits offen.}
{105}{}{Moment, wo ist deine Holodisk?!}
{106}{}{Du musst deine Gruppe versammeln, bevor du dich auf den Weg machst.}
{107}{}{Der Aufseher wird die Vault-Tür erst öffnen, wenn du deine Mission abgeschlossen hast.}
{108}{}{Du musst auf dein Team warten.}
