{100}{}{Du siehst einen Bürger.}
{101}{}{Sie sehen einen Mitbürger aus Vault 8.}
{102}{}{Nein! Lassen Sie mich in Ruhe! Ich gehe da nicht raus!}
{103}{}{V-vielleicht sollten wir einfach wieder nach unten gehen?}
{104}{}{Können wir uns nicht beeilen und die Sache hinter uns bringen?!}

{110}{}{Ich gehe nicht ... Ich gehe nicht ... Ich gehe nicht ...}
{111}{}{Was ist denn mit Ihnen los? Reißen Sie sich zusammen, wir müssen los!}
{112}{}{Wie Sie wollen. Wir kommen auch ohne Sie klar.}

{113}{}{NEIN! NEIN! ICH GEHE NICHT!!!}
{114}{}{Komm schon, so schlimm ist es nicht.}
{115}{}{[Slap his face] Reiß dich zusammen, du Feigling!}
{116}{}{Lassen Sie mich in Ruhe! Ich ... ich kann nicht ... Warum ich? Warum muss es ausgerechnet ich sein?}
{117}{}{Es ist seltsam, dass der Aufseher Sie für diese Aufgabe eingeteilt hat. Aber wir brauchen Sie, also reißen Sie sich zusammen.}
{118}{}{Au! Au, hören Sie auf! Lassen Sie mich in Ruhe! Warum tun Sie mir das an?!}
{119}{}{Wovor auch immer Sie da draußen Angst haben, vor *mir* sollten Sie mehr Angst haben.}
{120}{}{[He stops whining. He looks afraid, but his eyes are clear] Okay ... Okay ... Mir geht's gut, wirklich. Geben Sie mir nur eine Sekunde ... Ich bin jetzt bereit zu gehen.}
{121}{}{Gut. Folgen Sie mir.}
{122}{}{Wie können Sie nur so ruhig bleiben? Der Aufseher hat uns immer gesagt, dass es verboten ist, dort rauszugehen. Was wird aus uns? Was soll das jetzt? Warum muss es ausgerechnet ich sein?!}
{123}{}{Ich weiß nicht, warum Sie ausgewählt wurden, aber wir können nicht ohne Sie los. Wenn wir schnell und vorsichtig sind, wird alles gut. Sie haben mich, Dr. Moreau und einen bewaffneten Wachmann an Ihrer Seite. Sie brauchen sich keine Sorgen zu machen.}
{124}{}{Wirklich? Beschützen Sie mich? [he grabs you by the suit] Bitte, lassen Sie mich nicht allein ... Ich habe solche Angst ...}
{125}{}{Keine Angst. Ich bin hier.}
