{100}{}{Du siehst einen Sicherheitswachmann der Vault.}
{101}{}{Du siehst ein Mitglied der Sicherheitskräfte von Vault 8.}
{102}{}{Los, los, los!}

#Ïåğâûé äèàëîã
{110}{}{Sei gegrüßt, Bürger. Ich bin der Sicherheitsbegleiter des Teams für diese Mission. Die anderen warten in der Krankenstation auf dich. Sag mir Bescheid, wenn sie bereit sind.}
{111}{}{Na gut ...}
{112}{}{Noch etwas: Nimm diese Leuchtfackeln. Sie können nützlich sein, wenn es draußen zu dunkel ist. Dreh das obere Teil, um eine anzuzünden.}
{113}{}{In Ordnung.}

{114}{}{Wie lautet der Auftrag?}
{115}{}{Was weißt du über unsere Mission?}
{116}{}{Hast du keine Angst, nach draußen zu gehen?}
{117}{}{Bekomme ich etwas, um mich zu verteidigen?}
{118}{}{Folge mir, wir sind bereit, die Mission zu beginnen.}
{119}{}{Warte hier. Ich mache unser Team einsatzbereit.}

{120}{}{Doktor Richard Moreau überwacht den Einsatz. Er wird dich einweisen. Ich bin nur für die Sicherheit zuständig.}
{121}{}{Nein. Ich habe jahrelang dafür trainiert. Man hat mir beigebracht, meine Angst vor der Außenwelt zu unterdrücken. Dieses Team kann sich auf mich verlassen.}
{122}{}{Nein. Die Sicherheitsvorschriften des Vaults verbieten allen Bürgern außer dem Aufseher und dem Sicherheitspersonal, Waffen zu tragen. Aber keine Sorge, ich beschütze dich.}
{123}{}{Verstanden. Wenn das Team bereit ist, öffne die Tür über das Terminal.}
{124}{}{Verstanden.}

#Íà ïîâåğõíîñòè
{150}{}{[Ignoriert dich und hält nach möglichen Bedrohungen Ausschau.]}
{151}{}{[Lass ihn in Ruhe]}
{152}{}{Weißt du, wo sich die Monitore befinden?}
{153}{}{Nein. Doktor Moreau sollte die Standorte auf deinem Karten-Scanner markiert haben. Bleib konzentriert!}
{154}{}{Na gut.}

{160}{}{Er ist tot! [Sein Kopf schnellt hin und her, während er in die Dunkelheit späht.] Was ist passiert? Wo ist Doktor Moreau?! ... Das spielt jetzt keine Rolle mehr. Zurück in den Vault!}
{161}{}{Was ist mit Dr. Moreau?}
{162}{}{Los, Bürger! Du hast die Daten. Diese Mission ist vorbei!}
{163}{}{Wir können nicht ohne Doktor Moreau gehen! Er könnte noch irgendwo hier draußen sein ...}
{164}{}{[Seine Augen blitzen auf. Er knirscht mit den Zähnen.] Ich sagte: LOS! Doktor Moreau ist fort. Geh in den Vault, SOFORT!}
{165}{}{Nein, Sergeant. Nimm die Holodisk und kehr zurück. Ich suche nach Dr. Moreau.}
{166}{}{Du hast recht, Sergeant. Wir müssen hier weg! Los!}
{167}{}{Bürger! [Er richtet seine Waffe auf dich.] Wage es ja nicht, dort rauszugehen! Geh sofort in den Vault, das ist ein Befehl!}
{168}{}{[Dreh dich um und geh los.]}
{169}{}{Ja, Sergeant, Sie haben recht. Wir müssen Dr. Moreau zurücklassen. Gehen wir zurück!}
{170}{}{Bürger! Bürger, stehen bleiben! [pause] Bleiben Sie stehen, oder ich schieße! [after a few seconds of silence, you hear footsteps accelerating toward the vault]}
{171}{}{Auf Wiedersehen, Sergeant. Hier trennen sich unsere Wege ...}