{100}{}{Sie sehen Moreau.}
{101}{}{Du siehst Richard Moreau, den leitenden Arzt von Vault 8.}
{102}{}{Beeil dich mit den Daten, wir reden später.}

{110}{}{[Du siehst Dr. Moreau. Er sieht wütend aus.] Endlich. Ich wollte schon eine Wache hinter dir herschicken.}
{111}{}{Nicht nötig. Warum bist du so aufgebracht?}
{112}{}{Was? ... Vergiss es. Zur Sache: Du weißt bereits, dass wir nach draußen gehen. Ich kann dir nicht genau sagen, was uns hinter dem Haupttor erwartet, also stell dich auf das Schlimmste ein. Wenn wir nach Plan vorgehen, sollte alles glattlaufen.}
{113}{}{Was ist unser Auftrag?}
{114}{}{Seit Kurzem erhalten wir keine Informationen mehr von unseren Überwachungsmonitoren an der Oberfläche. Sie sollten die Daten aber weiterhin lokal sichern. Deine Aufgabe ist es, die Daten von den Monitoren zu holen, sofern das möglich ist.}
{115}{}{Wie soll ich das machen?}
{116}{}{Nimm diese leere Holodisk. Jeder Monitor hat einen Einschub. Steck die Disk einfach hinein und drück auf „Kopieren“. Der Monitor erledigt den Rest – falls er überhaupt noch funktioniert. Gib mir jetzt deinen Sensor. Ich trage die Positionen der Monitore auf deiner Karte ein, damit du sie leichter findest.}
{117}{}{In Ordnung, Doktor Moreau, wir können los. Folge mir.}
{118}{}{Verstanden. Ich sage dir Bescheid, wenn wir bereit sind aufzubrechen.}
{119}{}{Ja?}

{120}{}{Wenn das Team bereit ist, gib den Aktivierungscode am Zugangsterminal ein. Und verlier die Holodisk nicht!}
{121}{}{Na gut.}
{122}{}{Ich sage dir Bescheid, wenn wir bereit sind aufzubrechen.}

{123}{}{Warte, was werden die anderen von euch machen?}
{124}{}{Ich bin für die medizinische Versorgung zuständig, falls jemand sie braucht. Die Wache sorgt für die Sicherheit. Der andere Bürger wird mit seinem tragbaren Monitor Daten an der Oberfläche sammeln.}
{125}{}{Doktor, sind Sie sicher, dass alles in Ordnung ist? Sie sehen angespannt aus ...}
{126}{}{Halt lieber den Mund. Der Aufseher hat dir einen Befehl gegeben – darum solltest du dich kümmern, um nichts anderes.}
{127}{}{}
{128}{}{}
{129}{}{Hör zu, ich will nicht mit! Vielleicht gehe ich einfach wieder nach drinnen?}
{130}{}{Wir können nicht ohne dich gehen. Das ist zu riskant.}
{131}{}{Es ist viel zu riskant, überhaupt loszugehen! Es kann kein Zufall sein, dass alle Monitore gleichzeitig aufgehört haben, Daten zu senden. Wer weiß, was da draußen los ist!?}
{132}{}{Hmm ... Vielleicht ist es tatsächlich besser, wenn du nicht gehst. Du könntest die Mission gefährden. Geh zurück in den Vault. Ich finde jemanden, der dich ersetzt.}
{133}{}{Puh, danke. Du hast mir gerade den Arsch gerettet ... [Gib deine Mission auf]}
{134}{}{Nein ... Nein, warte. Ich glaube, ich musste das einfach mal rauslassen. Ich gehe, ich schaffe das. Du kannst dich auf mich verlassen.}
