{100}{}{Du siehst einen Erdrutsch.}
{101}{}{Vor dir liegt ein Haufen schwerer Felsen, die von oben herabgestürzt sind. Es wäre zu gefährlich, darüberzuklettern. Du musst einen Weg finden, sie hinunterzuwerfen.}
{102}{}{Diese Felsen sind zu schwer, um sie mit bloßen Händen zu bewegen. Du brauchst eine Art Hebel.}

{110}{}{Du setzt den Hebel an und stemmst dich dagegen. Du schaffst es, die kleineren Felsbrocken ein paar Fuß weit zu rollen, bevor deine Arme nachgeben.}
{111}{}{*Hn-ngg...*}
{112}{}{Du wirfst dein ganzes Körpergewicht auf den Hebel und bewegst einige mittelgroße Felsen. Du hast fast genug Platz geschaffen, um hindurchzukommen.}
{113}{}{*HH-HHRGG!*}
{114}{}{Mit dem Schild als Hebel nach dem Prinzip des Archimedes bewegst du langsam die größten Felsbrocken, bis sie über die Kante rollen und auf den Vorsprung darunter krachen. Der Durchgang ist frei.}
{115}{}{Puh!}