{100}{}{Du siehst einen Bürger von Vault 8.}
{101}{}{Du siehst einen Bürger von Vault 8.}
{102}{}{Du siehst deinen Mitbürger.}

#Ïëàâàşùèå ñîîáùåíèÿ ïğè âğàæäåáíîñòè:
{103}{}{ }
{104}{}{ }
{105}{}{ }
{106}{}{ }
{107}{}{ }
{108}{}{ }
{109}{}{ }

#Äèàëîã:
{110}{}{Es lebe Vault City, Bürger!}
{111}{}{Ein schöner Tag, nicht wahr, Bürger?}
{112}{}{Wo bekomme ich Ausrüstung?}
{113}{}{Weißt du etwas über die Außenwelt?}
{114}{}{Hast du den Freak in der Sicherheitszelle gesehen?}
{115}{}{Lust auf einen Spaziergang in der Wildnis?}
{116}{}{Schön, dich gesehen zu haben. Ich muss los.}

{117}{}{Jawohl, Bürger!}
{118}{}{Kann ich dich noch etwas fragen?}
{119}{}{Danke. Mach's gut.}
{120}{}{Ja, Bürger?}
{121}{}{Äh ... Sprich mit Sam im Lagerhaus. Du musst einen Antrag stellen und warten, bis er bearbeitet wird ... Was normalerweise erst passiert, wenn man ihn nicht mehr braucht.}
{122}{}{Ich? Nein, nichts! Gewöhnliche Bürger wie ich dürfen nicht nach draußen.}
{123}{}{Ich kann es kaum erwarten, bis er aus der Stadt geworfen wird. Hoffentlich ist er nicht ansteckend ... Und die Wachen haben alle nötigen Vorsichtsmaßnahmen getroffen.}
{124}{}{Wir dürfen die Stadt nicht verlassen. Es ist gefährlich.}

{125}{}{Hast du den Freak in der Zelle gesehen?}

#Ïğèâåòñòâèå Ñıìà (òîëüêî äëÿ áëóæäàşùèõ ãğàæäàí)
{165}{}{Wie läuft's, Sam?}
{166}{}{Wie steht's mit meiner Bestellung der Transistoren, Sam?}
{167}{}{Sam, wie lange dauert es noch, bis mein Antrag bearbeitet wird?!}
{168}{}{Sam, hast du vielleicht ... Nein? Was für eine Überraschung.}
{169}{}{Sam, hast du einen Dreistufentransformator?}

#Ïğèâåòñòâèå íà÷àëüíèêà îõğàíû (òîëüêî äëÿ áëóæäàşùèõ ãğàæäàí)
{170}{}{Sergeant Graves, droht uns Gefahr durch die Raider?}
{171}{}{Sergeant Graves, du siehst heute sehr ... kugelsicher aus!}
{172}{}{Sergeant Graves, sag mal, wie bist du zum ersten Mal aus dem Vault gekommen?}
{173}{}{Sergeant Graves, ich sehe, du hast die Sicherheit der Stadt verstärkt!}
{174}{}{Sergeant Graves, unser Held! Ich freue mich, dich zu sehen!}
{175}{}{Es lebe Vault City, Sergeant Graves!}

#Ïğèâåòñòâèå Äæîøóà (òîëüêî äëÿ áëóæäàşùèõ ãğàæäàí)
{180}{}{Joshua, gibt es in der Stadt Strahlung?}
{181}{}{Joshua, hast du etwas Interessantes gefunden?}
{182}{}{Joshua, hast du die Ruinen im Westen erkundet?}

{204}{}{Oh nein! Bitte tu das nicht!}

#Female character
{1110}{}{Es lebe Vault City, Bürger!}
{1111}{}{Ein schöner Tag, nicht wahr, Bürger?}
{1117}{}{Jawohl, Bürger!}
{1120}{}{Ja, Bürger?}
