{100}{}{Du siehst: einen Bürger.}
{101}{}{Du siehst einen Bürger, der einem Dartspiel zusieht.}
{102}{}{ }
{103}{}{Es lebe Vault City!}
{104}{}{Komm schon, du schaffst das!}
{105}{}{Dein Wurfgeschick hat sich um 5% erhöht.}

#Ïåğåä ñîğåâíîâàíèåì
{110}{}{Hallo, Bürger. Schönes Wetter heute, nicht wahr?}
{111}{}{Was macht ihr?}
{112}{}{Ich muss los. Tschüss.}

{113}{}{Wir werfen nur ein paar Darts. Man hat uns gesagt, wir sollen in unserer Freizeit etwas unternehmen, also machen wir etwas Spaßiges.}
{114}{}{Wie spielt man das?}
{115}{}{Sieht interessant aus. Kann ich es versuchen?}
{116}{}{Na gut, dann lasse ich dich mal weitermachen.}

{117}{}{Die Zielscheibe ist in Kreise mit unterschiedlich vielen Punkten unterteilt. Jeder Spieler wirft fünf Darts und zählt die Punkte der Kreise zusammen, die er getroffen hat. Wer die meisten Punkte hat, gewinnt.}
{118}{}{Klar.}
{119}{}{Ich bin bereit.}
{120}{}{Bis später dann.}

{121}{}{Gut. Hier sind fünf Darts. Zielen und werfen. Beweg dich nur nicht von deiner Ausgangsposition, sonst wirst du disqualifiziert!}
{122}{}{Na dann, fangen wir an ...}
{123}{}{Es ist gegen die Regeln, sich von der Ausgangsposition zu bewegen.}

#Êîíåö ñîğåâíîâàíèÿ
{150}{}{}
{151}{}{}
{152}{}{ Punkte von 50. Mit etwas Übung wirst du besser. Ich kann dir ein paar Tipps geben, wenn du willst.}
{153}{}{Ja! Bring mir bei, wie man besser Darts wirft!}
{154}{}{Nein, danke. Ich finde es selbst heraus.}

{155}{}{ Punkte von 50. Das ist, äh ... wirklich schlecht. Vielleicht ist heute einfach nicht dein Tag. Aber ich kann dir keine weiteren Darts geben.}
{156}{}{Ach, leck mich doch, Kumpel! Wer will schon dumme Darts auf dumme Kreise werfen!}
{157}{}{Ja, heute ist einfach nicht mein Tag.}

{158}{}{ Punkte von 50! Du hast Talent! So gut hat schon lange niemand mehr geworfen. Du bist sogar besser als ich!}
{159}{}{Hey, danke! Das hat echt Spaß gemacht!}
{160}{}{}

{161}{}{[Ihr werft abwechselnd Darts, während er euch Tipps gibt] Siehst du jetzt, was du falsch gemacht hast?}
{162}{}{Ja, das sehe ich. Danke für die Lektion, Bürger!}
{163}{}{Gern geschehen. Lang lebe Vault City!}
{164}{}{Äh ... Ja, klar.}

{173}{}{Nein, das ist nicht fair. Regeln sind Regeln. Du hast verloren, find dich damit ab.}
{174}{}{[Verlassen]}

#Female character
{1110}{}{Hallo, Bürger. Schönes Wetter heute, nicht wahr?}
