{100}{}{Du siehst den Bürger Jeremy.}
{101}{}{Du siehst den Bürger Jesse.}
{102}{}{Du siehst Jeremy, den Pfleger der Krankenstation.}
{103}{}{Du siehst Jesse, den Pfleger der Krankenstation.}
{104}{}{Bitte nicht!}
{105}{}{Ich bin froh, dich zu sehen!}
{106}{}{Ich bin froh, dich zu sehen!}

#Ïåğâûé äèàëîã

{110}{}{[Du siehst ein süßes, stilles Mädchen] Oh, du bist es ... Es ist so schön, dich zu sehen. So viele Leute haben Angst, nach draußen zu gehen, aber du nicht, du bist so ...}
{111}{}{Was machst du hier?}
{112}{}{Hast du diese winzige Vault nicht satt?}
{113}{}{Ganz einfach! Geh nach draußen und schnapp frische Luft.}
{114}{}{Ich lasse dich weiterarbeiten.}

{115}{}{Ich? Oh, beachte mich gar nicht. Ich halte hier nur alles sauber. Dr. Willmouth hat mich darum gebeten.}
{116}{}{Oh nein! Hier drin ist alles so vertraut, die Wände sind dick und ich kenne die Leute. Aber draußen ... I-ich habe sogar Angst, daran zu denken.}

{117}{}{Für dich ist das einfach. Du bist so stark und mutig. Und Leute wie ich ... Ach, egal, vergiss es.}
{118}{}{Nein, warte. Du hast einfach nur Angst, ins Ödland zu gehen, stimmt's?}
{119}{}{Pff, wovor hast du Angst - vor draußen? Ha-ha-ha-ha!}
{120}{}{Na ja, viel Glück ... Danke, dass du mich nicht wie eine Fremde behandelst. Komm ab und zu vorbei.}
{121}{}{Tschüss.}

{122}{}{Ich gehe nie nach draußen ... Niemals. Nicht einmal in die Stadt.}
{123}{}{Leute wie du? Was meinst du damit?}
{124}{}{Du hast den Vault noch nie verlassen?!}

{125}{}{Nein, doch, natürlich. Ein paar Mal. Ich... stand einfach in der Nähe des Ausgangs, sah hinaus in die Wüste und... ich habe die brennende Sonne nicht ertragen... Den ständig wechselnden Himmel... Und den Platz! So viel offene, leere Weite! Das ist unheimlich und gefährlich! Wenn ich könnte, würde ich lieber für immer im Vault bleiben.}
{126}{}{Vergiss deine Ängste, in der Stadt ist es besser. Und genauso sicher wie im Vault.}
{127}{}{Na ja, es ist dein Leben. Das ist mir egal.}
{128}{}{Na schön! Dann sitz hier in deinem kleinen Käfig, bis dir die Zähne ausfallen.}

{129}{}{Oh... Es tut mir leid... Vielleicht bin ich keine besonders interessante Gesprächspartnerin. Ich lasse dich in Ruhe. Bitte verzeih mir.}
{130}{}{Was?...}
{131}{}{Oh ja, ja, natürlich. Du hast viele wichtige Dinge zu tun. Aber ich freue mich trotzdem, dich zu sehen!}
{132}{}{Gut. Dann gehe ich jetzt.}
{133}{}{Na ja, wenn du meinst...}
{134}{}{Komm schon! Stell dich deinen Ängsten und geh in die Stadt. Geh auf den Straßen spazieren, dann siehst du, wie erstaunlich die Welt da draußen ist.}
{135}{}{Na gut, ich versuche es. Danke für deine Unterstützung.}
{136}{}{Keine Ursache. Wir sehen uns.}

{137}{}{Tut mir leid, aber... Kennen wir uns?}
{138}{}{Oh, ja, du bist es... Ich erinnere mich, wie man dich hierher zu Doktor Willmouth geschleppt hat. Er erzählte mir, du hättest fast alles vergessen. Das tut mir leid.}

#Â'îğîé äèàëîã

{150}{}{Ich freue mich, dich zu sehen.}
{151}{}{Ich erinnere mich, dass man dich unmöglich aus dem Vault herausbekam. Nicht einmal mit Gewalt.}
{152}{}{Ja, dank dir habe ich keine Angst mehr davor, nach draußen zu gehen. Vielen, vielen Dank!}
{153}{}{Doktor Willmouth sagt, es gäbe nur einen Weg, seine Ängste zu überwinden: Man muss sich ihnen stellen. Also bin ich hier und versuche es. Jeden Tag gewöhne ich mich mehr daran, draußen zu sein. Doktor Willmouth ist so klug!}
{154}{}{Stimmt. Kannst du mir erzählen, was passiert ist, während ich weg war?}
{155}{}{Ich... weiß nicht, was ich sagen soll. Ich spreche selten mit jemandem, aber... ich habe das Gefühl, dass etwas nicht stimmt. Vielleicht bilde ich mir das nur ein.}
{156}{}{Wovon redest du?}
{157}{}{Ich habe gehört, dass Leute verschwinden. Nicht so wie du – sie sind einfach ... weg. Der Aufseher und die Wachen erzählen uns nichts. Vielleicht wollen sie nur nicht, dass die Leute in Panik geraten, aber sie sollen uns doch beschützen. Uns völlig im Dunkeln zu lassen, ist ... seltsam.}
{158}{}{Ja, ich glaube, du hast recht.}
{159}{}{Leider weiß ich nichts weiter.}
{160}{}{Dann sehen wir uns später.}
{161}{}{Danke, dass du gekommen bist, um mit mir zu reden!}
{162}{}{Tschüss.}

#Òğå'èé äèàëîã
{200}{}{[Du siehst Jesse. Sie hat ein Messer in der Brust und wird nicht mehr lange durchhalten. Als du näher kommst, erkennst du, dass sie sich das Messer selbst in die Brust gestoßen hat.]}
{201}{}{Nicht bewegen! Spar deine Kräfte!}
{202}{}{[Stößt dich weg] Nein! Jetzt kenne ich die Wahrheit ... Ich bin nur eine ... eine Puppe, die vorgibt, ein Mensch zu sein ... Warum?! Ich will nicht ... so ... leben ... [keucht ein letztes Mal und erschlafft]}
{203}{}{[Gehen]}

#Âàğèàí' ğåïëèê ïğè èãğå æåíùèíîé (ïåğñîíàæ - ìóæ÷èíà)

#Ïåğâûé äèàëîã

{1110}{}{[Der schüchterne junge Mann lächelt dich an] Hallo, Bürger! Schön, dich zu sehen. Nicht jeder ist mutig genug, den Vault zu verlassen, aber du, du bist ... etwas Besonderes ...}
{1117}{}{Für dich ist das ganz einfach. Du bist so stark und mutig. Und für Leute wie mich ... Ach, vergiss es, schon gut.}
{1124}{}{Du hast den Vault noch nie verlassen?!}
{1125}{}{Nein, ich war natürlich schon ein paarmal draußen. Ich ... stand einfach in der Nähe des Ausgangs, sah in die Wüste hinaus und ... ich konnte die brennende Sonne nicht ertragen ... den ständig wechselnden Himmel ... und die Weite! So viel offene, leere Fläche! Das ist furchterregend! Wenn ich könnte, würde ich lieber für immer im Vault bleiben.}
{1129}{}{Oh... Es tut mir leid... Vielleicht bin ich keine besonders interessante Gesprächspartnerin. Ich lasse dich in Ruhe. Bitte verzeih mir.}
{1131}{}{Ja, natürlich. Du hast viele wichtige Dinge zu erledigen. Aber ich freue mich trotzdem, dich zu sehen!}

#Â'îğîé äèàëîã

{1150}{}{Ich freue mich, dich zu sehen.}
{1152}{}{Ja, dank dir habe ich keine Angst mehr davor, nach draußen zu gehen. Vielen, vielen Dank!}
{1157}{}{Ich habe gehört, dass Leute verschwinden. Nicht so wie du – sie sind einfach ... weg. Der Aufseher und die Wachen erzählen uns nichts. Vielleicht wollen sie nur nicht, dass die Leute in Panik geraten, aber sie sollen uns doch beschützen. Uns völlig im Dunkeln zu lassen, ist ... seltsam.}

{1159}{}{Leider weiß ich nichts weiter.}
{1161}{}{Danke, dass du mit mir geredet hast!}

#Òğå'èé äèàëîã
{1200}{}{[Du siehst Jeremy. Er blutet aus mehreren Schusswunden. An der Lage seiner Verletzungen erkennst du, dass er sich absichtlich erschießen ließ.]}
{1202}{}{[Stößt dich weg] Lass mich ... Jetzt weiß ich es! Ich war nur ein Satz ... Ersatzorgane ... ein Vorrat ... Heh. Nun, jetzt bekommen sie ... nichts mehr von mir ... [keucht ein letztes Mal und erschlafft]}