{100}{}{Du siehst Joshua.}
{101}{}{Der arme Joshua hat wohl eine Menge zu tun. Er analysiert sorgfältig Daten auf dem Monitor.}

##############################################
#
#    Íà÷àëî äèàëîãà
#
##############################################

{200}{}{Hallo, Bürger }
{201}{}{. Was möchtest du?}
{202}{}{Was ist das hier für ein Ort?}
{203}{}{Was macht ihr?}
{204}{}{Kann ich diesen Computer benutzen?}
{205}{}{Sonst noch was?}
{206}{}{}
{207}{}{Wegen des Roboters... }
{208}{}{Ich habe diese Holodisk in den westlichen Ruinen gefunden, aber ich kann sie nicht lesen. Kannst du mir helfen?}
{209}{}{Nichts.}

##############################################
#
#    Âîïğîñ ïğî ğàäèîñâÿçü (â 1.00 íå èñïîëüçóå'ñÿ!)
#
##############################################

{210}{}{Ja, wir benutzen das Funkgerät, um mit den Sicherheitspatrouillen zu kommunizieren, also kennen wir uns auf diesem Gebiet ziemlich gut aus.}
{211}{}{Kannst du mir etwas über diese Papiere aus NPP "Poseidon Oil" erzählen?}

{212}{}{Funkübertragungspunkte? Hmm... Sieht so aus, als gäbe es im Ödland einen Radiosender, der kleinere Stationen unterstützt, indem er ihre Signale weiterleitet. Aber das ist nur eine Theorie. Wir haben noch nie ein Signal empfangen, nur weißes Rauschen. Ich habe keine anderen Berichte darüber gesehen. Und noch seltsamer ist, dass diese Aufzeichnungen im Kraftwerk Poseidon Oil gemacht wurden.}
{213}{}{Was ist „weißes Rauschen“?}
{214}{}{Können wir uns diese Frequenzen anhören?}
{215}{}{Können wir die Koordinaten dieser Stationen herausfinden?}

{216}{}{Und die zweite Station?}
{217}{}{Sie liegt im Südosten. Ich markiere die Koordinaten auf deinem Pip-Boy.}
{218}{}{Hmm, dort leben die Cheyenne. Vielleicht können sie mir zeigen, wo die Station ist.}
{219}{}{Danke. Ich komme von hier an allein zurecht.}

{220}{}{Ach, nichts. Nur ein Hintergrundgeräusch im Funkgerät.}
{221}{}{Unsere Station ist nicht stark genug. Ihre Reichweite beträgt nur ein paar Meilen. Du brauchst eine leistungsstärkere Station.}
{222}{}{Oh, ich... Das hätte ich nicht sagen sollen. Mir wurde gesagt, ich soll das gewöhnlichen Bürgern nicht erzählen. Aber ich schätze, für dich gilt eine Ausnahme, oder?}
{223}{}{Klar, du kannst mir vertrauen.}
{224}{}{Dann musst du warten, während ich das Signal untersuche.}
{225}{}{Klar. Du bist hier der wissenschaftliche Experte.}
{226}{}{Dann eben nicht. Ich versuche, es selbst herauszufinden.}
{227}{}{Hier ist, was ich habe. Mit einigen Daten aus unserem System konnte ich die Koordinaten der Versorgungsstationen herausfinden, aber zwei davon sind zu weit entfernt, um sie zu erreichen. Eine befindet sich bei NPP, vermutlich damit sie den Strom des Kraftwerks nutzen kann.}

{228}{}{Nein, nein-nein-nein-nein. Das ist von unserem Abteilungsleiter strengstens verboten.}
{229}{}{Ich habe dir den Arsch gerettet, schon vergessen?}
{230}{}{Na gut, ich zwinge dich nicht dazu.}
{231}{}{Ach, verdammt ... Na gut, aber nur dieses eine Mal. Ich habe schon einmal gegen das Gesetz verstoßen. Oh, das wird mich noch verfolgen ...}
{232}{}{Keine Sorge, ich passe auf.}

{233}{}{Joshua zeigte dir die Koordinaten eines bisher unbekannten Ortes im Südosten.}

##############################################
#
#    Ïğîñ'ûå âîïğîñû è ïîèñê ğàçâåäğîáî'à
#
##############################################

{250}{}{Dies ist das Büro des technischen Dienstes. Wir warten elektronische Geräte.}
{251}{}{Stimmt.}
{252}{}{Im Moment überwache ich die Aufklärungsroboter.}
{253}{}{Was für Roboter benutzt ihr?}
{254}{}{Wofür werden die Aufklärungsroboter eingesetzt?}
{255}{}{Ohne dich funktionieren sie nicht?}
{256}{}{Ist das schwierig?}
{257}{}{Läuft alles reibungslos?}
{258}{}{Selbststeuernde Multifunktionssysteme, von fliegenden Aufklärungsbots bis hin zu schweren Bergbaumaschinen. Jeder einzelne ist unersetzlich, und es gibt nie genug davon, also sind sie ständig im Einsatz. Trotzdem geht die Arbeit sehr langsam voran.}
{259}{}{Die Aufklärungsroboter dienen vor allem dazu, die Topografie, Seismografie und Radioaktivität der umliegenden Gebiete zu untersuchen.}
{260}{}{Äh, ja und nein. Sie haben komplexe KI-Systeme, aber bei unerwarteten Situationen brauchen sie einen menschlichen Bediener.}
{261}{}{Das hängt von der Aufgabe ab. Manchmal kann es sehr schwierig sein. Aber ich würde mich nicht allein auf Roboter verlassen. Sie brauchen immer noch einen Menschen, der ihnen sagt, was sie tun sollen. Ohne den sind sie nur nutzlose Haufen Metall.}
{262}{}{Mein Vorgesetzter würde das nicht erlauben. Selbst wenn er es täte, müsste ich dafür eine riesige Datenmenge vom Server herunterladen. Keiner von uns kann sich so viel Zeit nehmen.}
{263}{}{Kann ich die Aufklärungsberichte sehen?}
{264}{}{Äh ... [blickt zu einem Monitor mit einem rot blinkenden Licht] W-wir kommen klar.}
{265}{}{Wirklich? Denn auf der Anzeige steht „Roboter reagiert nicht“!}

{266}{}{Whoa, whoa, whoa, ganz ruhig - ganz ruhig, okay? Ich bring ihn wieder zum Laufen, okay? Ich krieg das hin, nur ... Sag es nicht meinem Vorgesetzten, klar?}
{267}{}{Warte mal kurz. Wovon redest du?}
{268}{}{Warte, was ist los?}
{269}{}{Ich werde niemandem etwas sagen. Beruhig dich und erzähl mir, was los ist.}

{270}{}{Also ... Ich habe einen der Roboter aus den Augen verloren, die in den Ruinen forschen, und jetzt reagiert er nicht mehr. Wenn mein Vorgesetzter davon erfährt, nagelt er mich an die Wand. Wenn ich nur wüsste, was schiefgelaufen ist, oder diese Informationen zurückbekäme, könnte ich vielleicht das Schlimmste abwenden.}
{271}{}{Weißt du, genau solche Probleme löse ich. Frag nur, und ich kann dein Problem verschwinden lassen!}
{272}{}{Ich suche deinen Roboter, wenn du mir dafür etwas gibst.}
{273}{}{Wow, du brauchst wirklich dringend Hilfe. Na ja, mach's gut.}
{274}{}{Oh, ja, bitte, danke! Er hat sich irgendwo bei den westlichen Ruinen verirrt. Ich wäre selbst rausgeschlichen, aber ... Dort ist es gefährlich.}
{275}{}{Keine Sorge um mich, ich kümmere mich darum.}
{276}{}{Etwas? Was denn? Ich hab nichts ... Moment, ich hab diesen Wasserflasch! Bitte, hilf mir!}
{277}{}{Okay, abgemacht. Ich mach's.}
{278}{}{Das war's? Mach's selbst, ich bin weg.}
{279}{}{Danke, }
{280}{}{! Du hilfst mir wirklich sehr. Sag nur meinen Vorgesetzten nichts, sonst bin ich erledigt.}
{281}{}{Das werde ich mir merken ... Wie auch immer, ich muss los.}
{282}{}{Natürlich, keine Sorge. Niemand wird je davon erfahren.}

{289}{}{Noch nicht.}
{290}{}{Hast du den Roboter schon gefunden?!}
{291}{}{Wo hast du den Kontakt zu ihm verloren?}
{292}{}{Geh nach draußen und die Straße hinauf bis zum Schild „Sperrzone“. Dort steht ein Wachmann. Geh nach Westen, dann bist du in den Ruinen.}
{293}{}{Das war's.}
{294}{}{Ich habe den Roboter gefunden. Die Daten sind auf dieser Holodisk. Hier, nimm sie.}
{295}{}{Ich habe den Roboter und diese Holodisk gefunden, aber gibst du mir dafür etwas?}
{296}{}{Oh, danke }
{297}{}{! Das ist genau das, was ich brauche. Du hast mir echt den Arsch gerettet!}
{298}{}{Okay, ich habe noch ein paar Fragen.}
{299}{}{Mach's gut, Joshua.}

##############################################
#
#    Íà 'åìó ãîëîäèñêîâ
#
##############################################

{300}{}{Was ist das? Eine Geschichte aus dem Ödland? Wie interessant! Warte hier, während ich versuche, sie auf den Computer zu laden.}
{301}{}{Nur zu, versuch's. Das ist wirklich interessant.}
{302}{}{Dafür habe ich keine Zeit.}
{303}{}{Ja! [Er reißt die Faust in die Luft.] Ich hab's geschafft!}
{304}{}{Was ist darauf? Zeig mal!}
{305}{}{Diese Notizen waren verschlüsselt. Ich musste unsere alten Archive durchstöbern, um den richtigen Code zu finden. Ich habe die entschlüsselte Datei auf die Holodisk gespeichert, damit du sie lesen kannst.}
{306}{}{Super! Wie lese ich sie von der Holodisk?}
{307}{}{Gut, gib sie mir. Ich lese sie, wenn ich Zeit habe.}
{308}{}{Ganz einfach. Wähle bei der Holodisk „Benutzen“ aus, dann werden die Informationen auf dein Pip-Boy kopiert. Öffne es anschließend und geh rechts deine Notizenliste durch. Wähle die Datei aus und lies sie.}
{309}{}{Danke, ich probier's aus.}
{310}{}{Joshua hat die Informationen auf der Holodisk entschlüsselt. Sie dürften sehr nützlich sein.}

{313}{}{Wie konntest du nur! Ich habe dir vertraut!}

##############################################
#
#    Êàğ'à ïàìÿ'è ğîáî'à - ğàçáè'ûé äèëèæàíñ
#
##############################################

{330}{}{Kannst du das entschlüsseln? [Zeig ihm die Aufzeichnungen des Roboters]}
{331}{}{Klar, das ist alles ziemlich gewöhnlich. Aber ich brauche etwas Zeit.}
{332}{}{Ich warte. Leg los.}
{333}{}{Dann vergiss es. Verschwende keine Zeit.}
{334}{}{Das hat eine Weile gedauert. Da steckt eine Menge Daten drin, der Roboter war nicht besonders gut optimiert.}
{335}{}{Danke. Genau das habe ich gebraucht.}

##############################################
#
#    Ïî÷èíêà áîğ'îâîãî êîìïüş'åğà ïîåçäà
#
##############################################

{340}{}{Ich muss diesen Bordcomputer reparieren.}
{341}{}{Hmm ... [Er untersucht das unbekannte Gerät sorgfältig, beinahe vorsichtig.]}
{342}{}{Äh, weißt du überhaupt, was das ist?}
{343}{}{Ehrlich gesagt: Nein. So etwas habe ich noch nie gesehen, aber ich denke, ich kann herausfinden, wie es funktioniert. Ich brauche nur die Erlaubnis meines Vorgesetzten. Das wird eine Weile dauern, und wenn er mich bei nicht genehmigten Arbeiten erwischt, wird er stinksauer sein.}
{344}{}{Ich rede mit deinem Vorgesetzten.}

##############################################
#
#    Female character
#
##############################################

{1200}{}{Hallo, Bürger }
{1208}{}{Ich habe diese Holodisk in den westlichen Ruinen gefunden, aber ich kann sie nicht lesen. Kannst du mir helfen?}
{1229}{}{Ich habe dir den Arsch gerettet, schon vergessen?}
{1294}{}{Ich habe den Roboter gefunden. Die Daten sind auf dieser Holodisk. Hier, nimm sie.}
{1295}{}{Ich habe den Roboter und diese Holodisk gefunden, aber gibst du mir dafür etwas?}
