{100}{}{Du siehst ein Terminal.}
{101}{}{Du siehst ein medizinisches Notfallterminal.}
{102}{}{Das kannst du im Kampf nicht tun!}
{103}{}{Dein Wissenschafts-Fertigkeitswert ist nicht hoch genug, um in dieses Terminal einzubrechen.}
{104}{}{Um auf diesen Computer zuzugreifen, musst du wissenschaftlich vorgehen.}
{105}{}{Wissenschaft ist erforderlich.}
{106}{}{Du bist bereits in diesen Computer eingebrochen.}
{107}{}{Nichts Interessantes.}
{108}{}{Du hast dich in das Notfallterminal gehackt und es gezwungen, eine stimpak auszugeben.}
{109}{}{Ja!}
