{100}{}{Du siehst eine Spielerin.}
{101}{}{Du siehst eine Spielerin, die mit großer Leidenschaft ein Spiel spielt.}
{102}{}{Hi.}

{110}{}{(Dieses Mädchen klebt förmlich am Spielautomaten; im Moment zählt für sie nur der Sieg.)}
{111}{}{Was macht ihr?}
{112}{}{[Gehen]}

{113}{}{Was? Oh, dieser Spielautomat ... [sie redet, ohne den Blick vom Bildschirm abzuwenden] Ich komme bei diesem Level nicht weiter ... Ich hab's so oft versucht, aber der letzte Boss ist echt etwas Besonderes. An ihm scheitere ich immer. Aber weißt du, jedes andere Spiel schaffe ich beim ersten Versuch. Ich wähle die schwierigsten aus – und gewinne immer. Kannst du dir das vorstellen? In solchen Momenten habe ich dieses seltsame Gefühl ... Als würde die ganze Welt nur für dich in der Zeit erstarren.}
{114}{}{Und wenn du gewinnst, was dann? Bekommst du irgendeine Belohnung, etwa Geld?}
{115}{}{Nein, hier zahlst du fürs Spielen, nicht umgekehrt. Das ist kein Kasino. Wenn du hier gewinnst, kannst du höchstens auf eine Flasche Bier vom Barkeeper hoffen. Sozusagen als Anerkennung.}
{116}{}{Wie lange spielst du schon an solchen Automaten?}

{117}{}{Sehr ... Verdammt! [Sie zuckt zusammen, als sie versucht, einem Angriff auf ihre Spielfigur auszuweichen.] Oh Mann, schon wieder verloren ... Hör mal, du lenkst mich ab!}
{118}{}{Tut mir leid, das wollte ich nicht! Ich dachte nicht, dass es dir so wichtig ist, ein Spiel zu gewinnen.}
{119}{}{Nicht mein Problem, wen kümmert's? Vielleicht wäre es mir wichtiger, wenn man fürs Gewinnen, na ja, hundert Dollar oder so bekäme.}
{120}{}{Nicht dein erster Verlust, hm? Sag mir, warum ist dir das so wichtig?}
{121}{}{Wichtig? Natürlich ist es wichtig! }
{122}{}{Warum spielst du dann nicht im Casino? Obwohl, ich nehme an, das ist etwas anderes. }
{123}{}{}
{124}{}{[Seufzt] Oh, ich weiß nicht, ob du das verstehen würdest ... Hier habe ich immer alles unter Kontrolle, oder? Ausweichen, schießen, töten ... Alles ist einfach, ich kenne die Regeln. Klar wird es manchmal langweilig, aber es ist besser als die alten Slums, in denen ich lebe. Und ... [seufzt erneut] Es fühlt sich einfach gut an, wenigstens für einen Moment dieses Gefühl zu haben, dass sich die Welt um mich dreht. Weißt du, was ich meine?}
{125}{}{Ja ... ich glaube schon. Was ist mit dem Automaten da drüben, funktioniert er nicht?}
{126}{}{Nein. Er hat mir nicht standgehalten! Ich war mit einem Leben beim Boss des zehnten Levels angekommen, und irgendwie hat das die Platine durchgeschmort. Die gehen alle ab und zu kaputt und werden normalerweise innerhalb eines Tages oder so repariert. Ich schätze, bei dem gab's einen ordentlichen Kurzschluss.}
{127}{}{Hmm. Verstehe. Na dann, bis später.}
{128}{}{Ich schätze, du hast recht. Jedenfalls werde ich dich nicht länger ablenken. Tschüss.}

{1118}{}{Tut mir leid, das wollte ich nicht! Ich dachte nicht, dass es dir so wichtig ist, ein Spiel zu gewinnen.}
