{100}{}{Du siehst Barkeeper Tony.}
{101}{}{Du siehst einen rundlichen Mann hinter der Bar. Er lächelt jeden Gast an.}

#Attempt to talk wearing a balaclava
{102}{}{Zeig erst mal dein Gesicht, ich will sehen, wen ich bediene.}

{126}{}{Damit fängst du dir noch eine Faust ins Gesicht ein!}

#Rumors:
{130}{}{Hey, Barkeeper, behalt diese 10 Dollar als Trinkgeld.}
{131}{}{[Er lächelt dich sofort an] Vielen Dank für Ihre Großzügigkeit, Sir.}
{132}{}{Kannst du mir etwas Interessantes erzählen, wenn du nicht zu beschäftigt bist?}
{133}{}{Ich habe gehört, irgendwo in Vegas sei ein wahrer Schatz vergraben. Wenn du ihn findest, wirst du unermesslich reich. Ich weiß nicht, ob das stimmt, bisher hat ihn noch niemand gefunden.}
{134}{}{Soll ich dir etwas über eine Waffe erzählen, die Mr. Hal Wallace besitzt? Sie ist eine echte Rarität! Man kann einen Mann nur beneiden, der eine Kugel aus so einer Waffe abbekommt. Und was für eine Gravur sie hat! Irgendwas mit Indianermotiven, sehr stilvoll.}
{135}{}{Barney Hill ist ein seltsamer Mensch. Da steht er, neben dem Laufband. Trägt diesen dämlichen Hut und sagt peinliche, dumme Dinge. Andererseits: Wen kümmert das, wenn er zahlt, oder? Heh! Unser Boss meinte, gute Kunden sollten Rabatte bekommen. Also wurde Barney hier sesshaft und bekam ein eigenes Zimmer. Aber nicht einmal das Zimmerpersonal lässt er rein. Oder überhaupt irgendwen. Wie kommt ein gewöhnlicher Prospektor an so viel Geld? Keine Ahnung ... }
{136}{}{Oh, klar, kein Problem. Da war ein Typ, Sam Riley, einer unserer Angestellten. Er ist mit der Karawane auf Geschäftsreise nach Westen gegangen. Die Karawane kam zurück, aber Sam nicht. Seitdem hat niemand mehr etwas von ihm gehört. Sieht so aus, als müssten wir eine Gedenkfeier für ihn abhalten und uns ordentlich besaufen.}
{137}{}{Tibbett hat ein paar großartige Knarren, hält sie aber normalerweise vor neugierigen Blicken verborgen. Der Handel mit der Polizei ist ihm wichtiger, obwohl sie ihm viel weniger zahlt als normale Käufer. Sie setzen einem ehrlichen Mann zu, diese Schweine ... Oh, Verzeihung, das war unangebracht.}
{138}{}{Danke.}
{139}{}{Sonst noch etwas, Sir?}
{140}{}{Gern geschehen.}
{141}{}{Leider nichts Interessantes.}

#About alcohol poisoning
{150}{}{Ich habe gehört, jemand hätte sich vergiftet, nachdem er etwas an der Bar getrunken hat. Was können Sie dazu sagen?}
{151}{}{[Hebt skeptisch eine Augenbraue] Verdammte Konkurrenz. Sie verbreitet falsche Gerüchte. Oder vielleicht sind sie es, die versuchen, unseren Gästen etwas ins Getränk zu mischen, wenn niemand hinsieht. Warum sollten wir unsere eigenen Kunden vergiften? Das ergibt keinen Sinn.}
{152}{}{Klar, klar ... }
{153}{}{Unschuldig, bis die Schuld bewiesen ist? Das ist ja praktisch ... }
{154}{}{Das klingt ziemlich logisch und überzeugend.}

#Random remarks:
{200}{}{Eine Portion Rotgut ist unterwegs ... }
{201}{}{Das macht drei Dollar ...}
{202}{}{Noch eine für dich, Kumpel?}
{203}{}{Hier ist das Gegenmittel, wenn du willst.}
{204}{}{Hier wird nicht gekotzt! Raus mit dir, und kotz auf die Straße!}
{205}{}{Zwei Päckchen zu je einer halben Unze oder eine Dose?}
{206}{}{Eine Sonderbestellung von Tim Cain ist unterwegs ... }
{207}{}{Lass mich raten: Soll ich's auf deine Rechnung setzen?}
{208}{}{Ein „Sturzflug“ mit Eis, kommt sofort.}
{209}{}{Wir dulden nicht, dass sich unsere Gäste hier zudröhnen, Kumpel.}
{210}{}{Weißt du, warum diese Theaterleute gehängt werden müssen? Weil das Theater am Kleiderbügel beginnt ... Ha-ha-ha!!!}

#Starting replics
{230}{}{Was willst du, Kumpel?}
{231}{}{Schnaps. Zeig mir, was du hast.}
{232}{}{Nein, danke.}
{233}{}{Willst du noch mehr?}
{234}{}{Gib mir mehr.}
{235}{}{Kann ich ein Zimmer buchen?}

{239}{}{Äh ... Hey, immer mit der Ruhe, Kumpel. Bist du sicher, dass du hier richtig bist?}

#Try to speak with weapons in hand
{240}{}{Sir, ich bediene Sie erst, wenn Sie dieses ... Selbstverteidigungswerkzeug wegstecken.}

#Questions
{241}{}{Wer ist der schäbige Typ links von der Theke?}
{242}{}{Wer ist der komische Kerl mit der Perücke rechts von der Theke?}
{243}{}{Das ist ein Stammkunde. Er war lange nicht mehr hier und ist irgendwo herumgezogen. Er sagt, das Militär hätte ihn geschnappt, aber er sei entkommen. Ha! Was für ein Schwätzer.}
{244}{}{Das ist ein Vertrauter meines Chefs. Das Einzige, was er tut, ist tagsüber zu schlafen und nachts im Kasino Geld um sich zu werfen. Er ist ein bisschen [tippt sich an die Schläfe] meschugge.}
{245}{}{Das Zimmer ist im dritten Stock, hier sind die Schlüssel ...}
{246}{}{Okay, danke.}
{247}{}{Hier sind die Schlüssel. Ihr Zimmer ist im dritten Stock. Angenehmen Aufenthalt!}
{248}{}{Danke.}
{249}{}{Du hast dich gut ausgeruht und neue Kraft geschöpft.}
{250}{}{Verdammt! Du hast den ganzen Boden vollgekotzt! Und wer soll das jetzt sauber machen?!!}
{251}{}{Sag mal, wer wohnt in Zimmer 26 im dritten Stock?}
{252}{}{Oh, das ist Barney Hill. Ich hoffe, er hat Ihnen keine Unannehmlichkeiten bereitet? Ich verstehe, dass sein etwas exzentrisches Aussehen ... abschreckend wirken kann, aber er tut niemandem etwas. Er behauptet, von Außerirdischen aus dem Weltall entführt worden zu sein. Können Sie sich das vorstellen? Heh. Er hat sogar mit einem Vorkriegsspielzeug herumgefuchtelt, das wie ein Alien-Blaster aussah. Offenbar ist er besessen von der Theorie einer Alien-Invasion. Ein seltsamer Mensch, aber trotzdem immer unterhaltsam.}
{253}{}{Verstehe. Würdest du noch eine Frage beantworten?}
{254}{}{Hm, wie interessant. Danke für den Hinweis und tschüss.}
{255}{}{Ich kümmere mich um Nuka-Cola. Wir könnten gemeinsame Sache machen.}
{256}{}{Siehst du nicht, dass wir Nuka-Cola bereits verkaufen? Und bevor du die nächste Frage stellst: Ja, wir haben unsere eigene Lieferroute von Salt Lake.}
{257}{}{Also wurde ich von Konkurrenten geschlagen? Pech gehabt ... }

{258}{}{Ja, natürlich. Das Zimmer kostet }
{259}{}{ Dollar pro Tag.}
{260}{}{[Geh in dein Zimmer]}

#Women's replics
{1131}{}{[Er lächelt dich sofort an] Danke für Ihre Großzügigkeit, Ma'am.}
{1139}{}{Sonst noch etwas, Ma'am?}
{1230}{}{Was willst du, Freund?}
{1239}{}{Äh ... Hey, immer mit der Ruhe, Kumpel. Bist du sicher, dass du hier richtig bist?}
{1240}{}{Ma'am, ich bediene Sie erst, wenn Sie dieses ... Selbstverteidigungswerkzeug wegstecken.}
