{100}{}{Erschöpfter Karawanenhändler.}
{101}{}{Du siehst einen mitgenommenen und erschöpften Karawanenhändler.}
{102}{}{Dieser Karawanenhändler braucht Erste Hilfe.}
{103}{}{Dieser Karawanenhändler braucht keine Heilung.}
{104}{}{Du hast es nicht geschafft, ihn zu heilen.}
{105}{}{Du hast ihn erfolgreich geheilt und erhältst 150 Erfahrungspunkte.}
{106}{}{Oh, was für eine Erleichterung! Danke, Freund!}
{107}{}{Hey, vielleicht fragst du mich erst mal?}

#ïîïû'êà çàãîâîğè'ü, ïîêà ïåğñîíàæ íå âûëå÷åí
{110}{}{Tut mir leid, mir geht's wirklich schlecht ...}
{111}{}{(ihm geht es schlecht)}
{112}{}{(er spricht nicht mit dir, ihm geht es schlecht)}
{113}{}{(dieser Karawanenhändler liegt geschwächt da)}
{114}{}{Lass mich in Ruhe, ich hatte einen harten Tag.}
{115}{}{Was willst du?! Siehst du nicht, in welchem Zustand ich bin?}
{116}{}{Ich krieg keine Luft ...}
{117}{}{Mitten ins Gesicht! ... O-oh ...}
{118}{}{Alles tut weh ... Scheiße ...}
{119}{}{Das tut so weh!}
{120}{}{Womit habe ich das verdient?!}
{121}{}{Andere hatten mehr Glück als ich.}
{122}{}{Noch ein Transport? Nach dem hier?! Auf keinen Fall!}
{123}{}{Eine Woche lang werde ich krank sein.}
{124}{}{Nach solchen Prügeleien will ich nur noch ins Casino gehen und alles verprassen. Nur habe ich nichts mehr übrig.}
{125}{}{Tut mir leid, ich kann gerade nicht nachdenken ...}
{126}{}{Sprich mit den anderen, ich kann mich kaum auf den Beinen halten.}

{128}{}{Danke für die Hilfe, Wanderer!}
{129}{}{[Den Patienten untersuchen]}
{130}{}{gehen.}

{131}{}{(Prellungen, Schnitte ... Dieser Karawanenhändler könnte Erste Hilfe gebrauchen.)}
{132}{}{[Erste-Hilfe-Kasten benutzen]}
{133}{}{[Arzttasche benutzen]}
{134}{}{[Militärischen Erste-Hilfe-Kasten benutzen]}
{135}{}{[Sanitäterset benutzen]}
{136}{}{[Mit deinen eigenen Fähigkeiten zu helfen versuchen]}
{137}{}{Geh weg.}
{138}{}{(Geschafft! Dem Karawanenhändler geht es viel besser.)}
{139}{}{(Mangels deiner Fähigkeiten hast du den Karawanenhändler verletzt, und er hat dich weggestoßen.)}
{140}{}{Verdammt, ich muss vorsichtiger sein.}

#Æåí ğåïëèêè
{1106}{}{Oh, was für eine Erleichterung! Danke, Freund!}
{1128}{}{Danke für die Hilfe, Wanderer!}
