{100}{}{Du siehst einen gelangweilten Besucher.}
{101}{}{Du siehst einen Besucher mit traurigem Blick.}

{110}{}{Hallo. Bist du auch wegen ein paar Drinks hier?}
{111}{}{Vielleicht. Was machst du hier?}
{112}{}{Warum ziehst du so ein Gesicht?}
{113}{}{Ja, warum interessiert dich das?}
{114}{}{Nein, ich bin nur vorbeigekommen.}

{115}{}{Nun, ich dachte, vielleicht möchtest du mir Gesellschaft leisten, aber wenn du nicht willst ...}
{116}{}{Ach, darum geht's. Klar, hier sind fünf Dollar für ein Bier.}
{117}{}{Diesmal nicht.}
{118}{}{Mal sehen ... Äh ... Oh, ich glaube, ich bin einfach traurig und habe niemanden, mit dem ich etwas trinken kann.}
{119}{}{Verstehe. Na gut, ich lasse dich dann mal.}
{120}{}{Ich versuche, mich zu betrinken und alles und jeden zu vergessen. Siehst du das nicht?}
{121}{}{Ich spendiere dir einen Drink. Hey, Barkeeper! Hier sind 10 Dollar für ein Bier für meinen Freund!}
{122}{}{Hier ist ein Bier. Greif zu.}
{123}{}{Dann spendiere ich dir ein Bier aus meinem Vorrat.}
{124}{}{Na gut, dann trink ein Bier aus meinem Vorrat.}

{125}{}{Danke, Kumpel. Schön, an diesem Ort so freundliche Leute zu treffen.}
{126}{}{Was ist mit deinem finsteren Blick?}
{127}{}{Du könntest wenigstens versuchen, glücklich auszusehen.}
{128}{}{Tut mir leid, ich bin einfach traurig. Manchmal komme ich hierher, um meinen besten Freund zu ehren.}
{129}{}{Was ist mit ihm passiert?}
{130}{}{Er war ein richtiger Sportler, ganz begeistert von einem gesunden Lebensstil! Tag für Tag trainierte er hart, trug saubere Unterwäsche und putzte sich sogar die Zähne.}
{131}{}{Er muss ein guter Kerl sein.}
{132}{}{Er hatte wohl sonst nichts zu tun, oder?}
{133}{}{Nun, das wäre ja alles schön und gut, wenn er nicht eines Tages dieses Plakat mit der Vorkriegswerbung gelesen hätte. Darauf stand, dass Radiumwasser gut für den Körper sei. Hier. [gives you a small bottle with clear liquid] Er fand eine ganze Kiste von dem Zeug und trank täglich drei Flaschen davon ... bis er an einer Vergiftung starb.}
{134}{}{Wie traurig und seltsam ...}
{135}{}{Was für ein lächerlicher Tod!}
{136}{}{Ja, ist es. Wie sich herausstellte, ist Radiumwasser ziemlich giftig. Armer Byers. Wer hätte ahnen können, dass die Leute vor dem Krieg so dumm waren ...}
{137}{}{Eine traurige Geschichte, mein Freund. Das tut mir leid.}
{138}{}{Verdammt richtig. Eine ganze Horde Idioten.}
{139}{}{Trinken wir auf den Verstorbenen. Mehr können wir jetzt nicht tun.}
{140}{}{Klar, trinken wir!}
{141}{}{Na gut, ich langweile dich wahrscheinlich schon. Danke, dass du mir zugehört hast. Und auch fürs Bier. Du bist ein guter Mensch.}
{142}{}{Na gut, ich langweile dich wahrscheinlich schon. Danke, dass du mir zugehört hast. Und auch fürs Bier. Keine Ahnung, was du vorhast, aber du gefällst mir.}
{143}{}{Ja, tschüss.}

#Æåí ðåïëèêè
{1110}{}{Hallo. Bist du auch wegen ein paar Drinks hier?}
{1114}{}{Nein, ich bin nur vorbeigekommen.}
{1115}{}{Nun, ich dachte, vielleicht möchtest du mir Gesellschaft leisten, aber wenn du nicht willst ...}
{1125}{}{Danke, Mädchen. Schön, so freundliche Leute an diesem Ort zu sehen.}
{1141}{}{Na gut, ich langweile dich wahrscheinlich schon. Danke, dass du mir zugehört hast. Und auch fürs Bier. Du bist ein guter Mensch.}
{1142}{}{Na gut, ich langweile dich wahrscheinlich schon. Danke, dass du mir zugehört hast. Und auch fürs Bier. Keine Ahnung, was du vorhast, aber du gefällst mir.}