{100}{}{Du siehst Bob.}
{101}{}{Du siehst einen Karawanenhändler mit äußerst wichtiger Miene. Er hält offensichtlich ziemlich viel von sich.}

#Ñòàğòîâàÿ âåòêà
{110}{}{Was willst du?}
{111}{}{Bist du der Bob, der die Waren für „Monte“ und „Hard Rock“ ausliefert?}
{112}{}{Nichts.}
{113}{}{Ich verkaufe nur im Großhandel, tut mir leid, Kumpel.}
{114}{}{Arschloch, ich will nichts kaufen! Sag mir, warum hast du den Cafébesitzer verpfiffen?!}
{115}{}{Ich bin nicht hier, um etwas zu kaufen. Hast du gehört, dass die Polizei versucht, den Cafébesitzer ins Gefängnis zu bringen?}
{116}{}{Na gut, dann tschüss.}

#Ïîëó÷åíèå ıìóëüãàòîğà
{117}{}{Ein Spitzel?! Wie kannst du es wagen, mich zu beschuldigen! Sam und ich sind alte Freunde!}
{118}{}{Du lügst! Antworte, du Hurensohn!}
{119}{}{Whoa, okay, vielleicht habe ich mich geirrt. Weißt du etwas darüber, was passiert ist?}
{120}{}{Das reicht, Cowboy! Verzieh dich, oder meine Jungs und ich werfen dich vom Parkplatz!}
{121}{}{Warum so nervös? Hast du am Ende doch etwas damit zu tun? Vielleicht denkst du schneller, wenn du keine Luft mehr bekommst. [packt ihn an der Kehle]}
{122}{}{Ha, der hat ja Kampfgeist! Na gut, ich lasse dich vorerst in Ruhe.}
{123}{}{Ich weiß von nichts! Jetzt verzieh dich, oder meine Jungs und ich werfen dich vom Parkplatz!}

{124}{}{Phillips - ins Gefängnis?! Verdammt ... Das wusste ich nicht. Weswegen?}
{125}{}{Du lügst! Gesteh, warum hast du ihn verpfiffen!?}
{126}{}{Wegen der Verbreitung eines Giftes, an dem Menschen gestorben sind.}
{127}{}{Blödsinn! Das würde er nie tun! .. Moment, wenn sie mit „Gift“ das Zusatzstoff-Emulgator E30 meinen, dann ...}
{128}{}{Aha! Ich wusste es! Raus damit, du hast ihn doch verpfiffen, oder!?}
{129}{}{Was ist das? Sieht aus wie irgendein chemischer Bestandteil.}
{130}{}{Sam benutzt diesen Emulgator beim Kochen. Wahrscheinlich weiß er, was er tut. Ich jedenfalls nicht. Ich liefere die Substanz nur von Salt Lake - die gewinnen das Zeug vom Grund des Sees und reichern es dabei mit irgendetwas an ... Verdammt, ich habe mit ihm einen Vertrag über die Lieferung dieses Zeugs für die nächsten sechs Monate!}
{131}{}{Was für ein Vertrag? Hast du den Vertrag dabei?}
{132}{}{Kann man daran sterben?}
{133}{}{Ja. Sieht aus, als könntest du nicht weiterhelfen. Tschüss.}
{134}{}{Na ja, nein. Schlimmstenfalls explodiert dir einen Tag lang der Arsch auf der Toilette, wenn du zu viel davon isst. Aber ehrlich gesagt stinkt das Zeug schlimmer als abgestandenes Nuka-Cola. Wir vertreiben damit sogar Geckos.}
{135}{}{Nein, natürlich nicht. Warum? Sam gibt mir einfach eine Liste mit dem, was er braucht, und ich versuche, es zu beschaffen. Das ist alles.}
{136}{}{Kannst du mir etwas geben, damit ich es mir ansehen kann?}
{137}{}{Na ja, weißt du ... So leicht kommt man da nicht ran ... Hör mal ...}
{138}{}{Ach, komm schon! Nur ein kleines Stück! So viel verlierst du doch nicht, oder?}
{139}{}{Na schön. Wie viel kostet ein kleines Stück? Reichen 10 Dollar?}
{140}{}{Was für ein Geizhals! Ich glaube, ich verschwinde lieber von hier.}

{141}{}{Na gut, nur ein kleines Stück ... Also gut, hier, nimm es. [Er zieht einen Beutel mit etwas Gelbem und Bröckeligem hervor, wickelt es in Papier und gibt es dir.]}
{142}{}{Danke. Es stinkt wirklich, schlimmer als brahmin-Scheiße ...}
{143}{}{Weißt du, es mag billig sein, aber ich verschenke nichts. Gib mir 10 Dollar, dann sind alle zufrieden.}
{144}{}{Hier, nimm deine 10 Dollar.}
{145}{}{Du hast einen Beweis gegen Sam Phillips. Oder einen Beweis für seine Unschuld. Oder vielleicht einfach nur ein Stück Schrott, wer weiß.}

#Female character
{1113}{}{Ich verkaufe nur im Großhandel, tut mir leid, Kleine.}
{1119}{}{Whoa, okay, vielleicht habe ich mich geirrt. Weißt du etwas darüber, was passiert ist?}
{1120}{}{Okay! Das reicht, Cowgirl! Hau ab, oder meine Jungs und ich werfen dich vom Parkplatz!}
{1128}{}{Aha! Ich wusste es! Na los, spuck's aus! Du hast ihn doch verpfiffen, oder?!}
