{100}{}{Du siehst eine Kellnerin.}
{101}{}{Du siehst ein sehr beschäftigtes und ziemlich hübsches Mädchen. Sie hält einen Aschenbecher in den Händen.}

#Starting dialogue branch:
{102}{}{[Das Mädchen senkt den Blick und vermeidet es, dich anzusehen] Möchtest du ... etwas ... bestellen?}
{103}{}{Oh! Du bist es! Soll ich dir unsere berühmte Pizza bringen?}
{104}{}{Du siehst Susie.}
{105}{}{Du siehst das Mädchen vom Foto von Ted Bundy. Sie ist gefunden!}

#Starting greetings replic:
{106}{}{Ja? Was willst du?}
{107}{}{Was darf's sein?}
{108}{}{Möchtest du etwas bestellen?}
{109}{}{Ja?}

#Dialogue:
{150}{}{Zeig mir die Speisekarte.}
{151}{}{Nichts, ich gehe.}
{152}{}{Möchtest du noch etwas?}
{153}{}{Speisekarte.}
{154}{}{Nein, nichts.}
{155}{}{Was macht so eine Schönheit wie du an einem Ort wie diesem?}
{156}{}{Warte mal! Dein Gesicht kommt mir bekannt vor ...}

#The completion of the epic Ted Bundy story from New Reno [only for female chars]:
{157}{}{Natürlich! Ich arbeite hier schon seit über einem Jahr.}
{158}{}{Seit über einem Jahr? Hmm ... Kommst du von hier?}
{159}{}{Hmm ... Na gut dann.}

{160}{}{[Aus irgendeinem Grund zögert das Mädchen kurz.] Ja.}
{161}{}{Ach, spiel nicht die Füchsin, Schätzchen! Ich durchschaue dich! Sag die Wahrheit!}
{162}{}{Schätzchen, du verschweigst mir etwas. Ich sehe das. Aber du musst es mir nicht sagen, wenn du nicht willst ...}

{163}{}{[Sie errötet und lächelt dann.] Ma'am, Sie haben recht. Ich bin aus New Reno gekommen, aber es ist eine sehr traurige Geschichte, deshalb erzähle ich sie niemandem.}
{164}{}{Eine traurige Geschichte? Normalerweise hängen all die traurigen Geschichten über schöne Mädchen aus New Reno mit diesem Nachtclub zusammen ...}

{165}{}{[Der Wachmann kommt auf dich zu.] Hey! Was geht hier vor?! Das Mädchen arbeitet. Hör auf, sie zu belästigen. Ich muss dich bitten, das Café zu verlassen. Raus!}
{166}{}{Au! Wie unhöflich!}

{167}{}{[Dem Mädchen gefällt dieses Gespräch ganz offensichtlich nicht.] Entschuldigung, ich muss wieder an die Arbeit.}
{168}{}{Äh, nein! Du gehst nirgendwohin, bis du mir die Wahrheit sagst!}
{169}{}{Moment! Bist du das auf dem Foto?!}
{170}{}{Natürlich. Nur zu.}

{171}{}{Oh, mein Gott! ... [Sie wird blass und setzt sich auf einen Stuhl.]}
{172}{}{[Lass sie sich beruhigen]}
{173}{}{Ist das ein Geständnis?! Und jetzt erzähl mir, was du mit Ted Bundy zu tun hast!}

{174}{}{Oh ... Wenn Ted herausfindet, dass ich hier bin ...}
{175}{}{Du versteckst dich also vor ihm?}
{176}{}{Ich bin aus New Reno weggelaufen, um ein normales Leben zu führen. Aber die Albträume verfolgen mich noch immer.}
{177}{}{Albträume? Was hat er dir angetan?}
{178}{}{Nichts, was offensichtlich falsch war, aber ich merkte, dass etwas ... nicht stimmte. Und ich verließ ihn, als diese Mädchen im Hinterhof auftauchten ...}
{179}{}{Tote Mädchen? Mit ausgestochenen Augen, richtig? Sodass man durch die Augenhöhlen ihr Gehirn sehen konnte?}
{180}{}{Ich verstehe, von wem du sprichst. Warum hat er das getan? Warst du der Grund?!}
{181}{}{Mein Gott! Warum bist du so herzlos?! Lass mich in Ruhe!}
{182}{}{Zu spät, Schatz! Du wirst alles gestehen!}
{183}{}{Dann soll es so sein.}
{184}{}{Ja ... Nun, ich glaube, es lag an mir. Er hatte eine bestimmte Angewohnheit – er küsste gern meine Augenlider und drückte mir den Nacken ... Wenn ich ihn nicht verlassen hätte, wären diese Mädchen noch am Leben ... Du ... Wirst es ihm doch nicht sagen, oder?}
{185}{}{Doch, du Dummkopf! Diese Tänzerinnen sind deinetwegen gestorben! Ich werde allen davon erzählen!}
{186}{}{Nein, meine Liebe. Und er wird niemandem mehr etwas antun können. Du kannst seine Existenz vergessen. Für immer.}
{187}{}{Nein, ich werde niemandem von dir erzählen. Leb wohl und pass auf dich auf.}
{188}{}{Was?! Er wurde bestraft?!}
{189}{}{Ja, die Welt ist jetzt von diesem Maniac befreit. Und du bist auch frei.}
{190}{}{Danke, dass du es mir erzählt hast! Das sind wunderbare Neuigkeiten! Und könntest du ...}
{191}{}{Was?}
{192}{}{Wenn du dich wieder mit der Besitzerin dieses Nachtclubs triffst, könntest du ihr sagen, dass ich noch lebe und nur weggezogen bin? Sie ist so ein guter Mensch ... Sie war für uns alle wie eine Mutter ... Für all die verlorenen Mädchen von New Reno.}
{193}{}{Nun, falls ich dort hinkomme, vielleicht ...}
{194}{}{Natürlich werde ich es ihr sagen.}
{195}{}{Vielen Dank! Danke! ... Oh, ich sollte mich wieder an die Arbeit machen.}
{196}{}{Klar. Gern geschehen.}

#Info messages
{197}{}{Du hast das Mädchen auf dem Foto aus Ted Bundy gefunden und den Fall des Maniacs gelöst.}
{198}{}{Du hast das Mädchen auf dem Foto aus Ted Bundy gefunden, auch wenn noch immer unklar ist, wie alles zusammenhing.}
