{100}{}{Du siehst einen Besucher.}
{101}{}{Du siehst einen Gast im Café.}
{102}{}{Siehst du nicht, dass ich esse?}

#Random floating phrases when the scene is empty:
{110}{}{Vegas ist eine verrückte Stadt.}
{111}{}{Ich hatte Glück, mich hier niederzulassen.}
{112}{}{Noch ein paar Tage, dann bin ich pleite.}
{113}{}{In der Stadt einen Job zu finden ist, als würde man einem Gecko bei lebendigem Leib die Haut abziehen.}
{114}{}{Puh! So viel Pfeffer ...}
{115}{}{Deine Pizza ist nuklear!}
{116}{}{Ist das Toilettenpapier? ... Oh, die Rechnung ...}
{117}{}{Wann ist die nächste Show, Boss?}
{118}{}{Hey, Boss! Los, wir brauchen Musik!}
{119}{}{Die Bühne ist schon lange leer.}
{120}{}{Bedienung! Die Rechnung!}
{121}{}{Bedienung! Bier! Los, beweg dich!}
{122}{}{Bedienung! Eine Speisekarte!}
{123}{}{Im »Monte« ist der Service viel besser.}
{124}{}{Karawanenleute sind hier zu Stammgästen geworden.}
{125}{}{Die Stadt wird größer.}
{126}{}{Die Stadt kann nicht weiter wachsen, aber die Leute kommen trotzdem noch.}
{127}{}{Ich gehe nirgendwohin, solange es hier noch Pizza gibt!}
{128}{}{Ich komme nur wegen der Pizza her.}
{129}{}{Ich würde gern mal einen guten Auftritt sehen.}

#Random floating phrases when there's performance at the scene:
{150}{}{Vegas ist eine verrückte Stadt.}
{151}{}{Ich hatte Glück, mich hier niederzulassen.}
{152}{}{Noch ein paar Tage, dann bin ich pleite.}
{153}{}{In der Stadt einen Job zu finden ist, als würde man einem Gecko bei lebendigem Leib die Haut abziehen.}
{154}{}{Puh! So viel Pfeffer ...}
{155}{}{Deine Pizza ist nuklear!}
{156}{}{Ist das Toilettenpapier? ... Oh, die Rechnung.}
{157}{}{Dieser große Kerl ist ein echter Mann!}
{158}{}{Ich habe noch nie etwas Irrsinnigeres gehört.}
{159}{}{Worüber singt er eigentlich?}
{160}{}{Bedienung! Die Rechnung!}
{161}{}{Bedienung! Bier! Los, beweg dich!}
{162}{}{Bedienung! Los jetzt!}
{163}{}{Im »Monte« ist der Service viel besser.}
{164}{}{Ich verstehe nicht, worüber dieser Schwarze da singt?!}
{165}{}{Die Stadt wird immer größer.}
{166}{}{Die Stadt kann nicht weiter wachsen, aber die Leute kommen trotzdem noch.}
{167}{}{Solange auf der Bühne was los ist, gehe ich nirgendwohin!}
{168}{}{Ich bin nur wegen des Konzerts hergekommen.}
{169}{}{Das Geld für dieses Konzert ist mir kein bisschen schade.}
{170}{}{Ich glaube, dieser Grobian hat kein Gehör für Musik ... Aber mir gefällt's!}
{171}{}{Hey, auf der Bühne! Lasst die Party steigen!}
{172}{}{Hey, auf der Bühne! Spielt unseren Lieblingssong!}
{173}{}{Mann, ich würde tanzen, während du singst!}
{174}{}{::rülps::}
{175}{}{Juhu!}
{176}{}{Los geht's!}
{177}{}{Rock weiter, Großer!}

#Indignation of the audience when the char appears on the stage during the performance of Big Louie 
{180}{}{Hey, wir sind eigentlich gekommen, um Louie zuzuhören!}
{181}{}{Wer ist das?}
{182}{}{Ich dachte, Louie tritt solo auf?}
{183}{}{Hey, wer hat den Clown auf die Bühne gelassen?}
{184}{}{Also, ist das Jazz oder Porno?}
{185}{}{Der Weiße und der Nigger auf derselben Bühne? Wahnsinn.}
