{100}{}{Du siehst einen Wachmann.}
{101}{}{Du siehst einen Wachmann. Er sieht genauso aus wie die anderen.}
{102}{}{}
{103}{}{Er wartet auf dich.}
{104}{}{Alarm!}

#Диалог, когда Убежище захвачено Анклавом
{110}{}{Halt! Der Colonel will dich sehen. Folge mir und mach keinen Unsinn.}
{111}{}{Wie kannst du es wagen, mich aufzuhalten! Dafьr mach ich dich fertig!}
{112}{}{Na schцn, ich spreche mit diesem ... Colonel.}
{113}{}{Ich habe vorher noch ein paar Fragen.}
{114}{}{Der Colonel wird sie beantworten, wenn er es fьr nцtig hдlt. Folge mir.}
{115}{}{Auf keinen Fall! Diesmal legst du mich nicht rein! FICK DICH!}

#Диалог, когда Убежище захвачено Собира'елем или им же в 'еле Смо'ри'еля
{120}{}{Halt! Der Boss will dich sehen. Folge mir und mach keinen Дrger.}
{121}{}{Verdammter Klon, wie kannst du es wagen, mich aufzuhalten! Dafьr mach ich dich fertig!}
{122}{}{Na gut, ich rede mit deinem Boss ...}
{123}{}{Ich habe vorher noch ein paar Fragen.}
{124}{}{Er wird sie dir selbst beantworten. Folge mir.}
{125}{}{Auf keinen Fall! Diesmal legst du mich nicht rein! FICK DICH!}

#Пов'орный диалог
{130}{}{Halt! Du hast im Vault nichts zu suchen, bis du das Gerдt zurьckbringst.}
{131}{}{Dann komme ich damit zurьck.}
{132}{}{Bring mich zu deinem Boss. Ich muss mit ihm sprechen.}
{133}{}{Ich habe nicht um Erlaubnis gefragt. Ich gehe hin, wo ich will! [Angriff]}
