{100}{}{Du siehst: einen Wachmann.}
{101}{}{Du siehst: einen Wachmann aus deiner Stadt. Er trägt eine Sonnenbrille.}

#Ïåğâûå ğåïëèêè
{110}{}{Du bist zu spät! Ist dir das überhaupt klar?! Was sollen wir jetzt tun?!}
{111}{}{Warte. Erzähl mir genau, was passiert ist.}
{112}{}{Mir wird schon etwas einfallen.}

#Âîïğîñû
{113}{}{Sie kamen aus den Schatten, wie aus dem Nichts! Dann bekam jeder von uns gleichzeitig einen Anfall! Und dann gingen sie in den Vault. Jetzt haben sie ihn unter ihrer Kontrolle.}
{114}{}{Was ist mit unseren Zivilisten?}
{115}{}{Wo ist der Sicherheitschef?}
{116}{}{Wie viele sind im Vault?}
{117}{}{Wer sind sie?}
{118}{}{Und du stehst hier einfach nur herum und tust nichts?! Du bist nutzlos!}
{119}{}{Na gut, mir wird schon etwas einfallen.}

#Îòâåòû
{120}{}{Wir haben sie in die Berge gebracht, an einen sicheren Ort, weit weg von hier. Diese Nächte werden für sie wie ein Albtraum sein.}
{121}{}{Stimmt.}
{122}{}{Sergeant Graves ist im Vault. Er ist hineingegangen und nie zurückgekommen. Über Funk meldet er sich nicht. Ich glaube, wir haben ihn verloren ... Für immer.}
{123}{}{Ein ganzer Trupp, ein paar Dutzend Männer, ich weiß nicht genau, wie viele. Aber sie haben zwei Stockwerke eingenommen und sind bis zum Posten des Aufsehers vorgedrungen. Eine totale Katastrophe.}
{124}{}{Und was KÖNNEN wir schon tun?! Uns hat ja nicht einmal jemand richtig schießen beigebracht! Viele von uns haben zum ersten Mal in ihrem Leben den Tod gesehen ... Scheiße, mir wird gleich schlecht!}
{125}{}{Nur eine große Raider-Bande. Mehr nicht.}
{126}{}{Ich kann nicht einmal erkennen, ob das Menschen sind oder nicht. Sie sehen alle gleich aus, wie Kopien voneinander. Und ihr Anführer ... ist irgendein abgerissener Kopf in einem Glas! Was geht hier vor?!}
{127}{}{Ich kann nicht einmal erkennen, ob das Menschen sind oder nicht. Sie sehen alle gleich aus, wie Kopien voneinander. Und ihr Anführer ... sieht unserem Aufseher zum Verwechseln ähnlich! Ich kann es nicht glauben. Könnte der Aufseher uns verraten?! Warum hat er den Vault angegriffen?! Warum?!!!}
{128}{}{Ich kann nicht einmal erkennen, ob das Menschen sind oder nicht. Sie sehen alle gleich aus, wie Kopien voneinander. Und ihr Anführer ... hat einen Sack über dem Kopf und jede Menge Kabel hängen heraus. Ich kann nicht einmal sagen, ob er lebt oder ein Roboter ist. Leg dich besser nicht mit ihm an, glaub mir.}

#Female character:
{1110}{}{Du bist zu spät! Ist dir das überhaupt klar?! Was sollen wir jetzt tun?!}
