{100}{}{Du siehst den Seelenschnitter.}
{101}{}{Du siehst einen Schnitter der „reinen Seelen“.}

{104}{}{Scheiße! Dieser Bastard hat seine Körperteile nachwachsen lassen!}

{105}{}{Ähh ... Regeneration!!!}
{106}{}{Arhhh ... Regeneration!!!}
{107}{}{Ich werde schwächer ... Regeneration!!!}
{108}{}{Wie hat er das gemacht?! ...}

#Äèàëîã
{109}{}{Keine Verhandlungen! Du wirst STERBEN!}
{110}{}{Halt. Du solltest mir besser zuhören.}
{111}{}{Ach ja? Vorhin wolltest du mich noch umbringen.}
{112}{}{Ich habe dich unterschätzt. Ich denke, wir können darüber reden.}
{113}{}{Willst du mir einen Handel anbieten?}
{114}{}{Ich biete dir eine Wahl. Entweder machst du mit oder du schließt dich dem Rest deiner Herde an.}
{115}{}{Na gut ... Fang an.}
{116}{}{Du kennst die Wahrheit bereits. Ihr wart alle nur Schlachtvieh für medizinische Zwecke. „Krankenversicherungsprodukte“. Jeder Bewohner von Vault 8 sollte dazu dienen, das Leben eines wichtigen Mitglieds der US-Regierung zu retten. Sie würden immer mehr Leben aus dem Vault nehmen, ungeachtet dessen, was euer kleines, willkürliches Komitee unternahm.}
{117}{}{Ich kann kaum glauben, dass du jetzt für die Regierung arbeitest.}
{118}{}{Meine Prioritäten haben sich geändert. Seit dem Tag, an dem der Regierungsvault leer wurde, spiele ich mein eigenes Spiel. [Er hebt seine Hand, die aus verschiedenen miteinander verschmolzenen Hautstücken besteht] Wie du siehst, habe ich einige Fortschritte gemacht. Und mit der Technologie dieses Ortes ... Du kannst es dir nicht einmal vorstellen. Die Menschen sind zu zerbrechlich, um in dieser Welt allein zu überleben, und das weißt du. Du hast diese Welt und ihre Grausamkeit gesehen, du hast erlebt, was aus der Menschheit geworden ist. Also sag mir: Was würdest du tun, um dein Volk zu retten? Bist du in der Lage, schwere Entscheidungen ohne Reue zu treffen? Würdest du dich der Meinung anderer widersetzen, wenn es das Beste für sie wäre?}
{119}{}{Ich würde alles tun, was nötig ist. Ich bin bereit, für jede schwierige Entscheidung die Verantwortung zu übernehmen. Mein Volk liegt mir am Herzen - und ich weiß, was zu tun ist.}
{120}{}{Die Menschen können selbst entscheiden, was das Beste für sie ist. Es ist ihre Entscheidung, nicht die von jemand anderem. Ich tue einfach, was ich tun muss.}
{121}{}{Mein sogenanntes „Volk“ ist mir scheißegal. Ich gehöre nicht zu ihnen. Alles, was sie mir gegeben haben, war ein Tritt in den Arsch, also könnten sie mir kaum egaler sein.}

{122}{}{Dann wirst du vielleicht verstehen, was ich erreichen will. Du scheinst genug Erfahrung zu haben, um zu wissen, dass die Mehrheit sich irren kann und ein Einzelner etwas bewirken kann.}
{123}{}{Dann wirst du vielleicht verstehen, was ich erreichen will ... Obwohl ich stark bezweifle, dass du erfahren genug bist, um es zu begreifen. Dein Machtlevel ist so niedrig, dass du es nicht einmal mit kleinen Reno-Gangstern aufnehmen kannst. Trotzdem ist deine Entschlossenheit bewundernswert.}

{124}{}{Merkwürdig ... Du bist viel herumgereist. Du hast all dieses Leid gesehen. Man hat dich aus deiner eigenen Stadt verstoßen, von deinen eigenen Leuten verraten. Und trotzdem hast du nicht die Absicht verloren, ihnen zu helfen ... Ich hatte das Gegenteil erwartet.}
{125}{}{Belüg dich nicht selbst. Ich weiß, dass deine Hände genauso schmutzig sind wie die des kleinen Schlägers aus New Reno. Mehr als einmal hast du die Dinge selbst in die Hand genommen, die Ordnung verändert, die Entscheidungen anderer und den Lauf der Ereignisse beeinflusst. Alles für das, was du für richtig hältst.}

{126}{}{Du klingst ... enttäuscht. Dann wird es uns leichter fallen, uns zu einigen.}
{127}{}{Dann wird es uns noch leichter fallen, uns zu einigen. Vielleicht verstehst du meine Absichten nicht, aber das ist mir inzwischen eigentlich egal.}

{128}{}{[Weiter]}

{129}{}{Merkwürdig ... Du bist viel herumgereist. Du hast all dieses Leid gesehen. Man hat dich aus deiner eigenen Stadt verstoßen, von deinen eigenen Leuten verraten. Und trotzdem hast du nicht die Absicht verloren, ihnen zu helfen ... Ich hatte das Gegenteil erwartet. Vielleicht irre ich mich und du hast nichts gelernt. An Illusionen zu glauben ist alles, was du kannst.}


{130}{}{Denk darüber nach: Die Menschen sind für die heutige Welt nicht geeignet. Wir müssen uns anpassen, uns als Spezies weiterentwickeln. Was, wenn wir länger leben könnten, ohne uns um Infektionen oder Strahlung sorgen zu müssen? Was, wenn wir stärker und klüger werden könnten? Die Zivilisation neu aufbauen, besser als zuvor? Das kann Wirklichkeit werden. Alles, was es braucht, sind ein paar Jahrzehnte Forschung. Die Technologie aus dem Regierungsbunker und die Ausrüstung dieses Ortes sind alles, was ich brauche. Dieses gestohlene Gerät ist nicht nur eine wichtige Komponente der lebenserhaltenden Systeme deines Bunkers, einschließlich der Verteidigung, sondern auch ein Datenspeicher. Es enthält eine gewaltige Menge an Informationen über den Klonprozess und den Betrieb dieser Anlage.}
{131}{}{Deshalb musstest du den Biker damit beauftragen, es zu stehlen? Damit du in den Bunker eindringen konntest, ohne dabei von den Sicherheitstürmen durchlöchert zu werden?}

#Main point 1
{132}{}{Ja. Ich konnte weder hineinkommen noch das Gerät benutzen. Der Aufseher wusste alles, was ich brauchte, um auf die Inhalte des Geräts zugreifen zu können. Also heuerte ich den Biker an. Nicht alles lief glatt, aber am Ende bekam ich, was ich wollte.}
{133}{}{Was haben die Vault-Bewohner damit zu tun? Und was hast du mit ihnen vor?}

#Main point 2
{134}{}{Die Regierung war zu kurzsichtig in ihren Absichten. Sie wollte lediglich ihr Leben verlängern, statt bessere Versionen ihrer selbst zu werden. Ich erkannte das Potenzial, aber sie hörten nicht auf mich. Sie glauben, das hebe sie von allen anderen ab, und halten sich für die einzig wahren Menschen. Das ist so ... engstirnig. Die Klonanlage lässt sich zusammen mit der Technologie des Regierungsvaults für etwas Größeres nutzen als nur für die Erschaffung von Ersatzkörpern, wie mein Beispiel zeigt. Leider braucht man für diese Art Forschung geeignetes Material. Körper, die nicht durch Strahlung, Krankheiten oder eine schlechte Umwelt verseucht sind. Reine Körper.}
{135}{}{Das ist dein Plan?! Meine Leute auf Jahre hinaus als Versuchskaninchen zu benutzen, während du in deinem kleinen Sandkasten Gott spielst?}
{136}{}{Jetzt verstehe ich, was du mit schwierigen Entscheidungen gemeint hast. Die Menschheit um den Preis unzähliger Leben zu verbessern ... Ich weiß nicht, was ich davon halten soll.}
{137}{}{Wie passt die Regierung in deinen Plan? Irgendetwas sagt mir, dass sie es nicht gerade gutheißen wird, wenn du den Vault übernimmst.}

{138}{}{Verwirrt dich der Preis? Du hast selbst gesehen, wie leicht sich das Leben einer ganzen Siedlung verändern kann. Wie wehrlos die Menschen äußeren Bedrohungen gegenüber sind – Verbrechern, Hungersnöten, Naturkatastrophen. Schon eine einzige Person kann alles verändern. Doch es könnte anders sein. Es ist nur eine Frage der Zeit und Mühe. Wie man es auch betrachtet: Deine Leute hätten überhaupt nicht existieren dürfen. Sie lebten auf geliehener Zeit. Jetzt haben sie wenigstens die Chance, zu einer besseren Zukunft für die Menschheit beizutragen. Ihr Leben wird einen Sinn haben.}
{139}{}{Betrachte das Ganze aus einer größeren Perspektive. In diesem Augenblick sterben Tausende Menschen an Hunger, Krankheiten oder Strahlung. Hunderte Sklaven in Pferchen erliegen den Folgen tödlicher Drogen, und Raiderbanden greifen wehrlose Siedlungen an. Die Menschheit ist zu zerbrechlich. Sie braucht Hilfe. Sie verdient Besseres.}
{140}{}{Ich kann mit ihnen fertigwerden. Mit all dem Wissen über das Gerät werde ich die Systeme des Vaults meinem Willen unterwerfen. Die Regierung würde es nicht wagen, sich hier mit mir anzulegen – besonders, wenn ich ihr einen Knochen hinwerfe. Ab und zu ein paar Leichen sollten ausreichen, um den Waffenstillstand zwischen uns aufrechtzuerhalten. Und wenn der richtige Zeitpunkt kommt, werden sie keine Rolle mehr spielen. Eine neue Art von Menschen wird voranschreiten.}
{141}{}{[Weiter]}
{142}{}{Dieser Vault wird zur Geburtsstätte wahrer Menschen. Einer besseren Spezies. In 70 Jahren wird Nevada wieder aufblühen. Handel, Kultur und Wirtschaft werden gedeihen. Und Vault 8 wird das Zentrum davon sein. Überlegene Wesen, fähig, diese Welt zu einem besseren Ort zu machen, eine neue Zivilisation, wie es sie in der ganzen Geschichte noch nie gegeben hat ... Das Einzige, was du noch tun musst, ist, mir das Gerät zu bringen. Dann kannst du dich mir entweder anschließen oder gehen. Ich werde nicht nach dir suchen.}
{143}{}{In Ordnung, ich tue, was du verlangst.}
{144}{}{Nein. Ich werde das Gerät zerstören, damit der Vault frei sein kann. Mein Volk kommt auch ohne dich gut zurecht.}
{145}{}{Ich zerstöre lieber das ganze Labor. Diese Experimente an Menschen sind falsch.}
{146}{}{Ich töte dich einfach und mache dem ein Ende.}
{147}{}{Ich werde warten.}
{148}{}{Ich bezweifle stark, dass du dazu in der Lage bist. Wie auch immer, lass dir Zeit. Denk darüber nach. Wenn du so weit bist, bring es mir. Bring mir das Gerät.}
{149}{}{Ich hatte nicht erwartet, dass du mich sofort verstehst. Aber du hast keine Wahl. Vielleicht brauchst du etwas Zeit, um darüber nachzudenken. Wenn du so weit bist, bring es mir. Bring mir das Gerät.}
{150}{}{Große Worte für einen Einzelgänger, der von einem schwer bewaffneten Trupp umzingelt ist. Mach es dir leicht. Du stirbst – und ich muss dein Gehirn Stück für Stück wieder zusammensetzen, um den Standort des Geräts herauszufinden. Das ist doch lächerlich. Tu, was man von dir verlangt, und du kannst frei gehen.}
{151}{}{Ich habe so gelebt, wie ich wollte. Und ich werde so sterben, wie ich will. [Attack]}
{152}{}{Du bist verblendet. Derjenige, der vor dir steht, wird dir deine Wahnvorstellungen austreiben. Denn ich habe so gelebt, wie ich wollte. Und ich werde so sterben, wie ich will. [Attack]}
{153}{}{Wenn ich so darüber nachdenke, hat dieses „Krankenversicherungsprodukt“ schon mehr geleistet, als du gedacht hättest. Nun, dann soll das das Letzte sein, was es tut. [Attack]}
{154}{}{[Gehen]}

{155}{}{Wo ist das Gerät?}
{156}{}{Irgendwo, außerhalb deiner Reichweite.}
{157}{}{Lustig, solche Fragen von jemandem zu hören, der bald nichts weiter als eine Leiche sein wird! [Angreifen]}

{160}{}{Bring mir, was ich will, solange ich noch Geduld habe.}
{161}{}{Ich habe das Gerät. Nimm es und lass mich in Ruhe.}
{162}{}{Ich habe dir etwas Besseres gebracht – eine Kugel in den Kopf. Nimm sie und unterschreib hier!}
{163}{}{Ich werde tun, worum du mich bittest.}

{164}{}{Klug gewählt. Ich werde für diese Technologie eine nützlichere Verwendung finden als ein Haufen Anzugträger in der Regierung. Und jetzt geh. Wie gesagt – niemand wird dich aufhalten.}
{165}{}{[Ende]}

#Female character:
{1114}{}{Nein. Ich biete dir eine Wahl. Du bist dem Untergang geweiht. Genau wie der Rest dieser Herde.}
{1120}{}{Ich wollte ein wenig Frieden in diese Welt bringen! Ich habe hart gearbeitet, um den Menschen das Beste zu geben, was ich konnte. Sieh sie dir an: Sie sind verzweifelt und können nicht einmal ein Stück Brot teilen.}
{1124}{}{Seltsam ... Du warst lange unterwegs. Du hast all das Leid gesehen. Man hat dich aus deiner eigenen Stadt verstoßen, du wurdest verraten. Und trotzdem hast du deine Absicht, die Dinge in Ordnung zu bringen, nicht aufgegeben? Ich hatte das Gegenteil erwartet.}
{1129}{}{Seltsam ... Du warst lange unterwegs. Du hast all das Leid gesehen. Man hat dich aus deiner eigenen Stadt verstoßen, du wurdest verraten. Und trotzdem hast du deine Absicht, die Dinge in Ordnung zu bringen, nicht aufgegeben? Ich hatte das Gegenteil erwartet ... Aber das ergibt Sinn – du hattest nur wenig Erfahrung. Du lebst noch immer in einer Welt voller Illusionen.}
{1162}{}{Ich habe dir etwas Besseres gebracht – eine Kugel in den Kopf. Nimm sie und unterschreib hier!}
