{100}{}{Siehst du diesen Polizisten.}
{101}{}{Du siehst einen Polizisten, der dir bekannt vorkommt.}
{102}{}{Steck die Waffe weg, bevor die Patrouille dich sieht.}
{103}{}{Ich wusste, dass man dir nicht trauen kann. Gib mir nur einen Grund – und ich erschieße dich auf der Stelle.}
{104}{}{Ich hab dich gebeten, nicht mit mir zu reden! Wenn uns jemand zusammen sieht, sind wir beide erledigt!}
{105}{}{Schön, dich im Clean City zu sehen! Viel Spaß, Kumpel.}
{106}{}{Willkommen im Clean City! Viel Spaß.}
{107}{}{Die Menschen auf den Straßen haben sicher nicht erwartet, dass so etwas mitten im Stadtzentrum passiert ...}
{108}{}{Etwas ist passiert ...}

#Ñäà÷à êâåñòà
{110}{}{Willkommen! Schön, dich zu sehen. Und ja, ich weiß alles. Jetzt wird die Stadt ein besserer Ort sein, und das alles dank dir. Danke.}
{111}{}{Gern geschehen. Hat Spaß gemacht.}
{112}{}{Warte, ich habe überlegt, womit ich dich belohnen könnte. Hier, nimm dieses Super-stimpak. Es könnte dir in einer brenzligen Lage das Leben retten. Nochmals vielen Dank.}
{113}{}{Ich danke dir auch.}

#Æåí ğåïëèêè
{1105}{}{Schön, dich im Clean City zu sehen! Viel Spaß, meine Liebe.}
