{100}{}{Du siehst einen Polizisten.}
{101}{}{Du siehst einen verdächtig wirkenden Polizisten ... Was macht er hier?}
{102}{}{Hey, du! Sieht so aus, als wäre jemand zu hoch geflogen. Zeit, wieder auf den Boden der Tatsachen zurückzukommen!}
{103}{}{Es ist vorbei ... Aber warum hat dieser Polizist dich angegriffen?!}
{104}{}{Friss Blei, verdammter Bulle!}

{110}{}{Keine Bewegung, verdammt!}
{111}{}{Wow! Ein Cop, der Ärger sucht?}
{112}{}{Nicht schießen, ich habe nichts Falsches getan!}

{113}{}{Das sagen alle ... Und alle lügen. Das habe ich gelernt, als ich als Polizeiinspektor gearbeitet habe. Ich habe kein Problem damit, dir eine Knarre in den Mund zu stecken und abzudrücken. Deshalb lässt Davis mich das erledigen. Also – kannst du mir wenigstens sagen, was zum Teufel hier los ist?}
{114}{}{Er will mich umbringen?! Davon weiß ich nichts!}
{115}{}{Na ja, er ist nicht der Erste, der mich umbringen wollte, also ist es mir ziemlich egal.}

{116}{}{Harter Kerl, was? Aber in Vegas setzt niemand ohne Grund ein Kopfgeld auf einen Mann aus. Ich habe meine Befehle, weißt du ... vom Polizeichef höchstpersönlich ...}
{117}{}{Sei nicht dumm, warum solltest du das tun? Wozu?!}

{118}{}{Oh ... Na gut, nehmen wir an, es stimmt. Aber in Vegas setzt niemand ohne Grund ein Kopfgeld auf einen Mann aus. Ich habe einen Befehl, weißt du ... vom Polizeichef höchstpersönlich ...}
{119}{}{Warte, sei nicht dumm, warum solltest du das tun? Wozu?!}

{120}{}{Nichts Persönliches, Kumpel, ich mache nur meinen Job.}
{121}{}{Warte, sei nicht dumm, warum solltest du mich umbringen? Wozu?!}
{122}{}{Dann wird das dein letzter Job sein, du Narr! Na los!}

{123}{}{Das hier ist meine Heimat. Und ich will, dass Abschaum von außerhalb wie du zurück in seine Höhlen kriecht. Ihr bringt dieser Stadt nur Drogen, Waffen und Diebstahl. Doch hinter mir steht ein großes, korruptes System und es gibt fragwürdige Befehle von den Behörden. Ich weiß, dass Davis mich gern loswerden würde – weil ich oft dubiose Geschäfte störe, die ich besser nicht stören sollte. Vielleicht versucht er deshalb, mich auf dich zu hetzen. Was hältst du davon?}
{124}{}{Ich denke, du bist ein erbärmlicher Feigling. Machen wir Schluss damit.}
{125}{}{Ich weiß, dass dein Boss in schmutzige Geschäfte verwickelt ist. Ich kümmere mich bald um ihn, und du bist nicht länger in Gefahr.}
{126}{}{Ich weiß, dass dein Boss in schmutzige Geschäfte verwickelt ist. Bald werde ich hier für Ordnung sorgen, und du wirst nicht länger in Gefahr sein.}

{127}{}{Dann leb wohl, Fremder ...}
{128}{}{[Angreifen]}

{129}{}{Wenn man darüber nachdenkt, werden Leute wie ich – Zeugen – auch beseitigt, wenn sie nicht mehr nützlich sind. Hast du wenigstens irgendwelche Beweise gegen Davis?}
{130}{}{Ich werde welche finden, daran solltest du nicht zweifeln.}
{131}{}{Scheiß auf die Beweise, ich werde mir nicht mal die Mühe machen, den Mist durchzuwühlen.}
{132}{}{Ich glaube dir nicht. Von Leuten mit so einem Ruf in Vegas ist nichts Gutes zu erwarten. Es wird Zeit, dieses sinnlose Gespräch zu beenden ... [hebt eine Waffe auf]}
{133}{}{[Angreifen]}

{134}{}{Ich möchte dir glauben. In Vegas hört man viel Gutes über dich. Versuch nur, die Sache schnell zu erledigen – die Leute dahinter könnten uns beobachten ... Noch etwas. Ich werde die Kreuzung nahe dem Eingang zum Casino „Monte“ patrouillieren. Aber sprich mich nicht ohne guten Grund an. Ich muss jetzt gehen. Viel Glück.}
{135}{}{Ich möchte dir glauben. In Vegas hat niemand etwas Schlechtes über dich gehört. Versuch nur, die Sache schnell zu erledigen – die Leute dahinter könnten uns beobachten ... Noch etwas. Ich werde die Kreuzung nahe dem Eingang zum Casino „Monte“ patrouillieren. Aber sprich mich nicht ohne guten Grund an. Ich muss jetzt gehen. Viel Glück.}
{136}{}{Dir auch viel Glück, Inspector. Danke für die Warnung.}
{137}{}{Stell dich nicht so an, alles wird gut!}

#Æåí ðåïëèêè
{1116}{}{Zähe Schlampe, was? Aber in Vegas setzt niemand grundlos ein Kopfgeld auf eine Frau aus. Ich habe schließlich meine Befehle ... vom Polizeichef höchstpersönlich ...}
{1120}{}{Nichts Persönliches, Kleine. Ich mache nur meinen Job.}
{1127}{}{Dann leb wohl, Fremder ...}
