{100}{}{Du siehst einen Gefangenen.}
{101}{}{Du siehst einen jungen Kerl mit einer ziemlich rebellischen Ausstrahlung.}
{102}{}{Der Polizist hier lässt dich nicht mit dem Gefangenen sprechen.}

{103}{}{Der Gefangene stirbt an dem vergifteten Wasser.}
{104}{}{::atmet ein letztes Mal::}

{110}{}{Wer hat dich geschickt?}
{111}{}{Ich bin nicht aufgrund eines Tipps hier. Ich habe mich nur gefragt, wie ein junger Mann mit so einer stylischen Frisur hinter Gittern landen konnte.}

{112}{}{Ich wurde reingelegt! Es ist ihnen egal, ob ich das Geld gestohlen habe oder nicht. Sie brauchen einfach jemanden, dem sie die Schuld geben können. Verdammte Bullen ...}
{113}{}{Du bist also unschuldig? Kannst du das beweisen?}

{114}{}{Ich habe das Geld im Kasino gewonnen, ganz ehrlich. Davon müsste es Aufzeichnungen geben, aber ich glaube nicht, dass sie diese Informationen herausrücken. Sieht also so aus, als könnte ich nichts beweisen ... [senkt die Stimme] Hey, hör zu, du bist kein Cop, oder? Kannst du mir helfen? Meine Leute bezahlen dich dafür.}
{115}{}{Hmm, lass mich nachdenken ...}

{116}{}{Keine Zeit zum Nachdenken, danach hast du noch genug Zeit dafür ... Hör zu, du musst meinen Kumpel finden. Er heißt Orris. Normalerweise findest du ihn beim Café „Hard Rock". Sag ihm, dass sein alter Freund Murphy in Schwierigkeiten steckt, dann versteht er ... Er wird helfen ... [hält sich verzweifelt den Kopf] Er ... wird helfen ...}
{117}{}{Vielleicht finde ich diesen Orris und rede mit ihm. Aber ich muss die Einzelheiten der Geschichte kennen.}
{118}{}{[Lass ihn in Ruhe]}
{119}{}{Ich wurde reingelegt!}
{120}{}{Beruhige dich und erzähl mir die Einzelheiten der Geschichte.}
{121}{}{Erinner mich daran, wo ich deinen Freund Orris finde.}
{122}{}{Normalerweise findest du ihn beim Café „Hard Rock". Sag ihm, dass sein alter Freund Murphy in Schwierigkeiten steckt.}

{123}{}{Es war so: Ich habe im Kasino gewonnen. Nicht viel, aber für das Geld kann man trotzdem eine richtig gute Party feiern. Als ich nach draußen ging, nahmen die Bullen mich ohne jede Erklärung in die Zange. Dann brachten sie mich hierher, und dann tauchte dieser großmäulige Kerl aus dem Büro des Bürgermeisters auf und zählte auf, wie viel Geld ich in den Taschen habe und in welchen Scheinen. Er wusste es ganz genau. Ich erinnere mich, dass er im Kasino neben der Kasse stand. Er ist mir gefolgt! Und jetzt heißt es, ich hätte ihm das Geld gestohlen.}
{124}{}{Wer ist dieser „großmäulige Kerl aus dem Büro des Bürgermeisters"?}
{125}{}{Können sie dich denn nicht im Kasino identifizieren?}
{126}{}{Warum sollte ich dir glauben?}
{127}{}{Verstehe. Ich muss gehen.}
{128}{}{So ein Typ namens Irwin, ein Angestellter der Stadtverwaltung. Scheint, als würden ihn hier viele kennen, aber ich nicht. Ich komme aus den Vororten und hänge nicht mit den Einheimischen herum.}
{129}{}{Das können sie doch sicherlich. Sie schreiben alles in dieses Kassenbuch, aber die Bullen kümmern sich nicht darum. Sie glauben lieber dem Kerl aus dem Bürgermeisteramt. Und ich bin sicher, dass das Casino nicht für mich einstehen wird. Es ist für sie bequemer, dem Rathaus und den Bullen in den Arsch zu kriechen.}
{130}{}{Du? Das solltest du nicht. Warum sollte es dich interessieren ... Aber ich verlange nicht, dass du mir glaubst! Ich bitte dich, mit Orris zu reden. Er wird helfen, er ist ein alter Freund. Und vielleicht springt auch für dich etwas dabei raus, verstehst du?}

{131}{}{Was ist los?!}
{132}{}{Nun, offenbar ist der Polizist im Warteraum nicht mehr auf seinem Posten. Du solltest dich freuen.}
{133}{}{Natürlich! Äh, hör zu, ich weiß nicht, was da passiert ist, aber danke für die Hilfe. Jetzt schleiche ich schnell zur Tür raus und dann durch die Büsche nach draußen. Bis dann!}
{134}{}{Tschüss.}
{135}{}{Nichts Besonderes. Setz dich hin und halt den Mund.}

{136}{}{Offenbar hast du nicht gelogen. Ich konnte einen Blick in die Buchungen im Kassenbuch des Casinos werfen. Das passt alles zusammen – man hat dir etwas angehängt.}
{137}{}{Ich hab's dir gesagt! Die Leute von Clean City halten sich für etwas ganz Besonderes. Hör zu, kannst du die Beweise zu den Bullen bringen? Orris wird dich dafür sicher belohnen.}
{138}{}{Ich überleg's mir.}
{139}{}{Was hat der Cop dir gesagt? Ihr habt über mich geredet, oder?}
{140}{}{Er sagte, dass du frei bist.}
{141}{}{Nichts, was dich angeht.}
{142}{}{Wirklich?! Ich weiß nicht, wie du das hingekriegt hast, aber danke für die Hilfe. Ich muss schnell hier raus, bevor sie es sich anders überlegen. Bis dann!}
