{100}{}{Du siehst einen Polizisten.}
{101}{}{Du siehst einen Polizisten mit einem Abzeichen auf der Brust.}
{102}{}{Probleme?}

{103}{}{Mein Herr, }
{104}{}{Meine Dame, }

####################################################################
#
#       О'ве'ные реплики на попы'ку заговори'ь
#       Ав'ор: Александр Агафонцев aka Kerb
#
####################################################################

{110}{}{Wir behalten dich besser im Auge als ein Big Brother.}
{111}{}{Fьr Recht und Ordnung sorgen Grausamkeit und Angst.}
{112}{}{Das Gesetz ist hart, aber es ist nun mal das Gesetz.}
{113}{}{Klar, du kannst in Vegas jedes Gesetz brechen ... Aber kьmmere dich vorher um deine Beerdigung.}
{114}{}{::streicht ьber sein Holster und sieht dich misstrauisch an::}
{115}{}{Wir lassen die Menge dich nicht verprьgeln ... Wir dulden nur keine Konkurrenz!}
{116}{}{Unschuld gibt es nicht, nur verschiedene Grade der Schuld.}
{117}{}{Benimm dich, dann wirst du auch so behandelt.}

####################################################################
#
#       О'ве'ные реплики на попы'ку заговори'ь при дос'ижении "Прокаженный"
#
####################################################################

{120}{}{Guhle gehцren nicht hierher ... Дh, nein, ich habe nicht mit dir gesprochen.}
{121}{}{Was!? Ein Freak in der Stadt!? Hoppla, mein Fehler, tut mir leid.}
{122}{}{Mach keinen Unsinn, Ghul.}
{123}{}{Wir werfen Ghule raus, also gib uns keinen Grund dazu.}
{124}{}{Дh, du bist kein Ghul ... Ich hдtte dich fast erschossen.}
{125}{}{Mit deinem, дh, Gesicht fдngst du leicht eine Kugel. Denk daran.}
{126}{}{Viele Leute hier mцgen keine Ghule. Nur so nebenbei, aber behalt das im Hinterkopf.}
{127}{}{Weiter, Ghul, beweg dich. Ich will mir keine Infektion einfangen.}
{128}{}{Hдssliche Leute werden hier nicht geduldet, also pass auf.}

####################################################################
#
#       Требования убра'ь оружие
#
####################################################################

#Первое предупреждение:
{200}{}{Steck deine Waffe weg!}
{201}{}{Das hier ist kein SchieЯstand!}
{202}{}{Lass deine Waffe im Holster!}
{203}{}{Leg dich nicht mit mir an, versteck die Waffe!}
{204}{}{Waffen sind innerhalb der Stadtgrenzen verboten!}
{205}{}{Du solltest die Waffe wegstecken.}

#В'орое предупреждение:
{206}{}{Hцrst du mich?}
{207}{}{Leg dich nicht mit mir an!}
{208}{}{Denk nicht einmal daran, das Ding zu benutzen!}
{209}{}{Wir haben den Befehl, tцdliche Gewalt anzuwenden!}
{210}{}{Steck sofort deine Waffe weg!}

#Последнее предупреждение
{211}{}{Letzte Warnung!}
{212}{}{Zwing mich nicht, bis zum ДuЯersten zu gehen!}
{213}{}{Ich will nicht kдmpfen!}
{214}{}{Ьberleg es dir lieber gut!}
{215}{}{Was macht ihr?}

#Нападение:
{216}{}{Das hдttest du nicht tun sollen!}
{217}{}{Du bist es, der den Streit angefangen hat!}
{218}{}{Du hast es nicht anders gewollt!}
{219}{}{Suchst du Дrger?!}
{220}{}{Das hдttest du dir frьher ьberlegen sollen!}
