{100}{}{Du siehst einen Polizisten.}
{101}{}{Du siehst einen Polizeibeamten am Empfang hinter dem Tresen.}
{102}{}{Falsche Beweise wurden in Dead hotel platziert und warten dort auf ihren Einsatz.}

{110}{}{Wen suchst du?}
{111}{}{Auf Wiedersehen.}
{112}{}{Wegen des Falls Sam Phillips.}

#Äåëî î Ñıìå Ôèëëèïñå
{113}{}{[Der Polizist zeigt plötzlich großes Interesse] Das ist ein besonders kniffliger Fall ... Was wolltest du mir also über Sam Phillips erzählen?}
{114}{}{Ich habe eine Substanz, die seine Verwicklung in den Drogenhandel in der Stadt beweist! Er kauft sie bei einer Karawane aus Salt Lake.}
{115}{}{Ich habe eine Substanz, die seine Unschuld in Bezug auf seine angebliche Verwicklung in den Drogenhandel in der Stadt beweist! Offenbar hat jemand dieses Nahrungsergänzungsmittel für eine Droge gehalten.}
{116}{}{Ich wollte nur fragen – wie läuft der Fall?}
{117}{}{Hm, nichts, schätze ich. Ich wollte nur mal fragen.}
{118}{}{Ach, so ist das! Dann lege ich dir einfach Handschellen an und stecke dich in eine Zelle, damit du nächstes Mal nachdenkst, bevor du einem Polizeibeamten die Zeit stiehlst.}
{119}{}{Oh nein, nicht in eine Zelle! Ich gehe lieber still und leise.}

{120}{}{Darf ich fragen, warum du dich für diesen Fall interessierst?}
{121}{}{Sam Phillips... Äh... Er schuldet mir Geld, und ich mache mir Sorgen.}
{122}{}{Sam Phillips ist mein Freund, und ich will nicht, dass er ins Gefängnis kommt!}
{123}{}{Ich ermittle in dem Verbrechen im Auftrag des Bürgermeisters höchstpersönlich.}
{124}{}{Kein besonderer Grund. Warum?}
{125}{}{Dein Boss hat mir den zivilen Auftrag gegeben, Phillips auszuspionieren.}

{126}{}{Oh, das ändert die Sache. Zuerst wurden wir von einer anonymen Person kontaktiert und darüber informiert, dass Phillips in seinem Café Drogen herstellt. Wir sind zum Tatort gefahren und haben dort etwas von diesem gelben, stinkenden Zeug gefunden. Unsere Spezialisten versuchen noch herauszufinden, was es ist. Aber sie kommen nicht weiter. Wenn sie diese Substanz nicht identifizieren können, weiß ich nicht, wie das alles ausgehen wird.}
{127}{}{Eine gelbe Substanz? So was hier? [zeigt einen Emulgator]}
{128}{}{Hm. Na gut.}
{129}{}{Dann musst du dich beeilen, denn bei der Durchsuchung des Cafés haben wir eine verdächtige gelbe Substanz gefunden, die an Bestandteile zur Drogenherstellung erinnert. Höchstwahrscheinlich wird er ins Gefängnis gesteckt.}
{130}{}{Oh Scheiße, ist es wirklich so schlimm?}
{131}{}{Ach, du bist also sein Freund! Tja, dann müsst ihr euch wohl voneinander verabschieden. Denn bald sitzt Sam Phillips hinter Gittern. Ende der Geschichte.}
{132}{}{Verdammt, ist es wirklich so schlimm?}
{133}{}{Drogen?! Das glaube ich nicht! Du lügst!}
{134}{}{[Mustert dich von Kopf bis Fuß] Unabhängiger Ermittler? Wie interessant. Also, so sieht's aus: Wir wurden von einer anonymen Person kontaktiert. Sie sagte, dass Sam Phillips Drogen herstellt. Wir sind zum Café gegangen, haben es durchsucht und dort etwas von diesem gelben, stinkenden Zeug gefunden. Wir wissen noch nicht genau, was es ist, aber wahrscheinlich reicht schon diese Sache aus, um seine Schuld zu beweisen.}
{135}{}{Jetzt verstehe ich. Danke.}

{136}{}{Ja. Genau das Gleiche haben wir in Phillips' Café gefunden! Wo hast du das her?}
{137}{}{Von Bob. Er ist ein Karawanenhändler aus Salt Lake, bei dem Sam das Zeug kauft.}
{138}{}{Wie interessant. Das heißt, diese Droge wird aus Salt lake hergebracht?}
{139}{}{Das ist keine Droge! Das ist ein harmloser Lebensmittelzusatz für Pizza. Mehr nicht.}
{140}{}{Ja! Und du solltest diese Vorräte so schnell wie möglich beseitigen, damit niemand zu Schaden kommt!}
{141}{}{Wie interessant. Was ist das also für eine Droge?}
{142}{}{Wow ... Nahrungsergänzungsmittel ... Sieht nicht danach aus. Aber ... Woher sollte ich wissen, wie Nahrungsergänzungsmittel aussehen? Deshalb können unsere Spezialisten das Zeug nicht identifizieren. Nun, ich denke, deine Sachkenntnis reicht aus, um Sam Phillipss Unschuld zu beweisen.}
{143}{}{Großartig! Ich gehe es ihm sagen.}
{144}{}{Du hast natürlich recht, und wir werden sofort handeln. Phillips wird verhaftet, und du wirst, wie in solchen Fällen üblich, belohnt. Hier, 1000 $. Danke für deine Mitarbeit, Bürger. Ich hoffe, du wirst uns auch weiterhin über mögliche Verbrechen informieren.}
{145}{}{Heh, leicht verdientes Geld.}

#Ïğî Âûñåğà
{150}{}{Wie läuft der Dienst, Freund? Ist in letzter Zeit etwas Interessantes passiert?}
{151}{}{Bei deinem Scharfsinn gibt es hier nichts für mich zu tun. Aber pass auf dich auf. Sonst endest du vielleicht wie der andere vor dir, den wir für alle sichtbar an den Schandpfahl gebunden haben. Versuch, seinen Platz nicht einzunehmen, mit deinen frechen Fragen.}
{152}{}{Von wem redest du?}
{153}{}{Wow – entschuldigen Sie, dass ich Sie störe, Herr Offizier! Meine Hochachtung, Herr Offizier! Ich verbeuge mich und bin bereit, Ihre Hände zu küssen, Herr Offizier!}
{154}{}{Dieser Idiot nennt sich Shitposter. Ein minderjähriges Arschloch mit übersteigertem Selbstwertgefühl. Er hängt jetzt in der Sonne, beim Begrüßungskonsolenbereich. Geh mal hin und sieh es dir an. Ist ein ziemliches Schauspiel!}
{155}{}{Na gut.}

#Äæåé Êóêèø
{160}{}{Ich suche jay Kukish, einen Biker. Hast du etwas über ihn gehört?}
{161}{}{Wow – was für ein Zufall. Wir suchen ihn auch! Wir haben den Befehl, den Täter festzunehmen. Wenn du ihm begegnest: Denk daran, er ist sehr gefährlich. Spiel nicht herum – erst schießen, dann fragen.}
{162}{}{Äh, danke für die Info.}
{163}{}{Sehr gut. Das war die richtige Entscheidung.}

#Äæåé Êóêèø
{170}{}{Ich verlange, dass Murphy aus der Isolierzelle entlassen wird.}
{171}{}{Das ist in zwei Fällen möglich: Entweder beweist du seine Unschuld oder du zahlst eine Kaution von 500 $.}
{172}{}{Ich zahle. Hier ist das Geld.}
{173}{}{Es hat keinen Zweck, mit dir zu reden. Bis dann.}
{174}{}{Gefangener Murphy! Sie können gehen.}
{175}{}{Danke.}
{176}{}{Das Geld ist dir wichtiger als deine Gesundheit? Und was, wenn du dich ansteckst?}
{177}{}{Ha-ha-ha, willst du mich veräppeln? Dieser Trick ist hundert Jahre alt. Ich habe schon alles gehört: „Ödlandkrankheit“, „Zittern“, „Narg-Syndrom“ ... Was hast du dir diesmal ausgedacht?}
{178}{}{Du willst mir also sagen, dass es die „Ödlandkrankheit“ gar nicht gibt? Ich bin ein Arzt mit langjähriger Erfahrung. Wir haben ganze Dörfer daran sterben sehen. Genau wie in Tonopah oder Mesquite. Warst du schon mal dort?}
{179}{}{Hmm. Von Tonopah habe ich gehört. Irgendwas mit Verrückten, die ihr eigenes Fleisch verzehrten ... Oder war es wirklich so, dass einfach das ganze Dorf dort ausgestorben ist ... Aber da du Arzt bist, muss ich dir wohl glauben. Schreib mir zuerst eine Bescheinigung, dass du für ihre Diagnose bürgst.}

#Êâåñò àğõèâàğèóñà è óëè÷íûé âîğèøêà
{180}{}{Gibt es hier Arbeit für einen Privatdetektiv?}
{181}{}{Normalerweise stellen wir niemanden ein und kümmern uns selbst darum. Aber es gibt ein paar Fälle, bei denen wir deine Hilfe gut gebrauchen könnten.}
{182}{}{Interessant. Worum geht es?}
{183}{}{Zuerst einmal ist die Tochter des Archivars im Bürgermeisteramt verschwunden. Wir konnten sie nicht finden. Du kannst den Archivar selbst nach seiner Tochter fragen. Er ist im zweiten Stock des Rathauses.}
{184}{}{Okay. Und was ist der andere Fall?}
{185}{}{Es gibt einen erfahrenen Taschendieb in Clean City. Wir haben fünf Anzeigen wegen kleiner Diebstähle erhalten. Dieser Schurke muss so schnell wie möglich gefasst werden. Sei aufmerksam, vielleicht erwischst du ihn auf frischer Tat.}
{186}{}{Okay. Die Tochter eines Archivars und ein Dieb. Ich sehe, was ich tun kann.}

{190}{}{Was kannst du über Anna Clarks Verschwinden sagen?}
{191}{}{Die Tochter ist spurlos verschwunden. In der „Hard Rock“ hat sie niemand gesehen, im „Monte“ war sie schon lange nicht mehr, und es gibt keine weiteren Orte, an denen man nach Mädchen wie ihr suchen könnte. Wir haben die Suche aufgegeben, weil es keinerlei Hinweise gab.}
{192}{}{In Ordnung.}

#Äåëî î âûğîäêàõ
{205}{}{Wegen der Freaks.}
{206}{}{Ich habe Beweise für ihre Unschuld. Sie wurden reingelegt!}
{207}{}{Ich habe Beweise für ihre Schuld. Diese Aufnahme habe ich während eines Gesprächs mit Larry Geller gemacht.}
{208}{}{Was ist bei der Polizei ihr Problem mit ihnen?}
{209}{}{Ach, das alte leidige Problem.}

{210}{}{Sie stellen Drogen her und verteilen sie in der Stadt. Der Bürgermeister ist dagegen und will daher solchen Abschaum unterdrücken, damit sie lernen, das Gesetz zu respektieren.}
{211}{}{Verstehe. Noch eine Frage.}

{212}{}{Was redest du da, Liebling der Freaks? Wie verdächtig. Na, sehen wir mal, was du da hast ...}
{213}{}{Hier, ich habe heimlich diese Broschüre von den Sklavenhändlern mitgenommen. Ein eindeutiger Beweis.}
{214}{}{Oh! Wie unerwartet. Ich weiß nicht, was die Sklavenhändler vorhatten, aber wir werden uns um sie kümmern. Ich gebe den Beweis dem Chef. Danke, Bürger. In solchen Fällen muss man belohnt werden. Hier, nimm das. [gibt 1000 $]}
{215}{}{Tausend Mäuse!}

{216}{}{Ganz schön gerissen von dir. Gute Arbeit! Die Unterwelt muss bestraft werden ... Und du solltest dafür belohnt werden. [Gibt dir 2000 $] Was die Freaks angeht – keine Sorge. Wir stellen jetzt eine Razzia auf die Beine, und von nun an werden sie niemandem mehr etwas antun.}
{217}{}{Ich will mitmachen! Ich habe es satt, dass meine Waffe ungenutzt verstaubt.}
{218}{}{Großartig!}
{219}{}{Eine zusätzliche Waffe kann nicht schaden. Ich denke, die Freaks zu vertreiben, wird leicht sein.}
{220}{}{[Du wartest, während sich die Polizeieinheit für einen Strafzug nach Dead Hotel bereitmacht]}

{221}{}{Ich war im Hotel der Freaks. Die haben sogar in den Kisten Dope herumliegen! Das müsst ihr euch sofort ansehen!}
{222}{}{Du kommst gerade recht. Danke für die Information, im Namen der Polizei von Las Vegas. Dir steht eine Belohnung zu. Hier sind 1.000 $. Was die Freaks angeht – du kannst beruhigt sein. Wir machen uns gerade bereit für einen Strafzug.}

#Óëèêè ïğîòèâ Óîëëèñà
{223}{}{Weißt du, dass Hal Wallace in schmutzige Geschäfte verwickelt ist? Ich habe Beweise!}
{224}{}{Hal Wallace?! Dieser große Mann soll in kriminelle Machenschaften verwickelt sein? Ist dir klar, dass du jetzt für deine Worte verantwortlich bist?}
{225}{}{Das ist eine Aufzeichnung unseres Gesprächs. Er hat mich überredet, die Freaks illegal auszuspionieren!}
{226}{}{Das ist eine Aufzeichnung unseres Gesprächs. Er hat mich angeheuert, um Bob Neils Waffe zu stehlen!}
{227}{}{Wenn die Sache so ernst ist, sollte ich vielleicht darauf verzichten, weitere Beweise vorzulegen.}

{228}{}{Ich glaube nicht, dass jemand bei der Polizei Mr. Wallace ernsthaft für solche Taten verantwortlich machen wird. Ganz im Gegenteil. Aber ich muss unserem Chef Beweise vorlegen. Danke, Bürger. Sie können jetzt gehen.}
{229}{}{Kann mir Anonymität garantiert werden?}
{230}{}{In Ordnung.}
{231}{}{Ja, natürlich.}
{232}{}{Ja, das ist ein schweres Verbrechen. Leider kann ich nichts überstürzen. Ich werde unserem Chef die Beweise vorlegen, und er muss die endgültige Entscheidung treffen. Danke für Ihre Hilfe, Bürger. Wir übernehmen von hier an.}
{233}{}{Habe ich nicht irgendeine Art von Belohnung verdient?}
{234}{}{Was glauben Sie, wozu Wallace die Pistole brauchte?}
{235}{}{Ich hoffe, Ihr Chef findet es heraus.}
{236}{}{Nein.}
{237}{}{WAS?! Ich habe mein Leben riskiert, und alles war umsonst! Scheiß Bulle! Schieb dir die Beweise in den Arsch!}
{238}{}{Schade.}
{239}{}{Ich kann es nicht mit Sicherheit sagen. Vielleicht wollte er Bob Neil etwas anhängen und ihn ins Gefängnis bringen. Aber wozu er das gebraucht hätte, verstehe ich nicht.}
{240}{}{Stimmt.}

#Ëàáîğàòîğèÿ Âåãàñà
{241}{}{Über die Drogen, die Vegas überschwemmen.}
{242}{}{Na, na, na! Was wollen Sie mir sagen?}
{243}{}{Ich weiß, wer die Stadt mit Drogen versorgt. Sie nennen sich „black caravan“.}
{244}{}{Ich weiß, wo das Labor ist, und kann es auf der Karte zeigen.}
{245}{}{Äh ... verstehe, das ist Ihnen wichtig. Aber ich wollte nur fragen, wie die Dinge laufen.}

{246}{}{Gut, Schlaumeier. Und ich war froh, dass neue Hinweise aufgetaucht sind. Wir arbeiten noch an dem Fall, aber ein Ende ist nicht in Sicht.}
{247}{}{Schlechte Polizeiarbeit, Officer!}
{248}{}{Schade.}

{249}{}{*Sehr* gut! Jetzt haben wir dieses Gesindel. Nun, im Namen der Clean City danke ich Ihnen! Sie haben das Richtige getan, indem Sie uns davon berichtet haben. Wie es sich gehört, steht Ihnen eine Belohnung zu. Hier, das ist für Sie.}
{250}{}{Das nenn ich eine Belohnung! Oh ja!}

{251}{}{Jetzt haben wir sie! Die Black Caravan wird bald zu Asche zerfallen. Ha! Wer hätte gedacht, dass es heutzutage noch so ehrenhafte Menschen wie Sie gibt. Hier, nehmen Sie diese Belohnung. Die ganze Las Vegas ist Ihnen dankbar. Ich hoffe, Sie werden uns auch weiterhin über solche Verbrecher informieren.}
{252}{}{Das nenn ich eine Belohnung.}

{253}{}{Kann ich mit einer Belohnung für die Enthüllung des Labors rechnen?}
{254}{}{Äh, wurdest du nicht bereits belohnt?}
{255}{}{Ja, aber für einen derart wichtigen Fall hätte ich gern noch etwas mehr.}
{256}{}{Ich bin nicht befugt, mich um solche Angelegenheiten zu kümmern. Wenden Sie sich an den Polizeichef, Oscar Davis, er ist in seinem Büro.}
{257}{}{In Ordnung.}
{258}{}{Wir bekommen bei so schwierigen Angelegenheiten nur selten Hilfe ... Ich denke, wir könnten dich belohnen, aber was möchtest du?}
{259}{}{Meine Schießkünste trainieren.}
{260}{}{Nichts, tut mir leid.}
{261}{}{Nun, das lässt sich leicht arrangieren. Aber ich denke, das wird unser einziges Zugeständnis sein. Also überstürze die Wahl nicht.}
{262}{}{Kleinwaffen.}
{263}{}{Schwere Waffen.}
{264}{}{Energiewaffen.}
{265}{}{Nahkampfwaffen.}
{266}{}{Wurfwaffen.}
{267}{}{Unbewaffnet.}
{268}{}{Ich überlege es mir und komme dann wieder.}

#Îäèí èç êîğîëåé
{270}{}{Wer ist der Typ hinter den Gitterstäben?}
{271}{}{Ein kleiner Dieb. Er wurde beim Stehlen einer großen Geldsumme erwischt. Aber harte Arbeit wird ihn die Folgen eines solchen Lebenswandels lehren.}
{272}{}{Kann ich mit ihm sprechen?}
{273}{}{Ja, das ist nicht verboten. Du hast drei Minuten.}
{274}{}{Danke.}

{275}{}{Stopp! Nicht bewegen! Ich habe dich im Visier. Beweg dich, und ich töte dich. Und jetzt sag mir: Was soll das?}
{276}{}{Hey, triff keine übereilten Entscheidungen! Dieser Bastard hat immer noch bekommen, was er verdient hat ...}
{277}{}{Wenn ich es dir sage, muss ich dich auch töten.}
{278}{}{Na, na. Also eine persönliche Angelegenheit, ja? Das klingt nicht sehr glaubwürdig. Und jetzt sag mir: Wer hat seinen Mord in Auftrag gegeben? Sofort!}
{279}{}{Es war Orris, einer von den Kings. Er wollte ihm vorsichtshalber den Mund stopfen. Ich mische mich nicht in ihre Angelegenheiten ein, ich befolge nur Befehle.}

{280}{}{[Zögernd] Wirklich?}
{281}{}{Das ist die Wahrheit, Boss! Der Bastard hat den Tod verdient. Er gehört zu den Banditen. Außerhalb der Stadtmauern begehen sie Verbrechen, die du dir nie hättest vorstellen können! Und ich ... [traurig] Ich hatte persönliche Gründe.}
{282}{}{Ich ... Äh ... Hör zu, ich verstehe dich gut. Aber das hättest du nicht tun dürfen. Wegen dir bekomme ich Ärger! Was soll ich den Behörden sagen? Was, wenn jetzt jemand hereinkommt?}
{283}{}{Ich kann einfach weglaufen, und du sagst, du hattest keine Zeit zu reagieren! Das klingt glaubwürdig, niemand wird sich um den Bastard scheren ...}
{284}{}{Hm ... Ach, verdammt noch mal ... Lauf einfach, bevor ich es mir anders überlege! Sofort!}
{285}{}{Danke, Boss! Danke!}
{286}{}{Warte, ich erinnere mich an dich! Ich hab von dir gehört, du verdammter Abschaum. Und ich hätte dir beinahe geglaubt ... [steckt die Waffe weg]}
{287}{}{Ich wusste es, die Kings würden sich einmischen. Verdammte Bastarde! Aber du ... Warte, du hast gesagt, du wärst nur ein Söldner. Hör zu, ich kann dich gehen lassen. Aber du musst etwas tun, um dich reinzuwaschen – töte Orris. Das wäre fair. Wenn du das nicht tust, hast du eine Kugel im Kopf, sobald du dich in Clean City blicken lässt. Kapiert? Und jetzt verpiss dich, bevor ich es mir anders überlege!}
{288}{}{[Gehen]}
{289}{}{Oh nein! [Angriff]}

{290}{}{Murphy ist unschuldig. Ich habe Beweise.}
{291}{}{Eine sehr unangenehme Geschichte. Die Angestellten des Rathauses sind normalerweise angesehene Bürger. Ich hoffe, du verstehst, dass das unter uns bleiben muss. Es geht nicht nur um Irvines Verbrechen, sondern auch um die allgemeine Lage. Andere könnten seinem Beispiel folgen, ganz zu schweigen vom Ruf eines Clean City. Was Murphy angeht, müssen wir ihn wohl gehen lassen. Allerdings glaube ich, dass uns das später noch auf die Füße fällt.}
{292}{}{Großartig.}

{293}{}{Ich hatte persönliche Gründe. Das ist die Wahrheit.}
{294}{}{[Durch die Zähne] Findest du das lustig? Mal sehen, wie lange du noch lachst. [Zielt zum Schuss]}
{295}{}{Hey, warte! Er hat bekommen, was er verdient hat ...}
{296}{}{[Verteidige dich]}
{297}{}{[Deine Erklärung war nicht überzeugend] Sag mir die Wahrheit, du Ödlandabschaum!!!}
{298}{}{Das ist die Wahrheit ...}
{299}{}{Schluss, ich hab genug!}

#Female character
{1116}{}{Ich wollte nur sehen, wie es mit dem Fall vorangeht?}
{1117}{}{Hm, nichts Besonderes, wollte nur mal fragen.}
{1151}{}{Bei deinem Scharfsinn gibt es hier nichts für mich zu tun. Aber pass auf dich auf. Sonst endest du vielleicht wie der andere vor dir, den wir für alle sichtbar an den Schandpfahl gebunden haben. Versuch, seinen Platz nicht einzunehmen, mit deinen frechen Fragen.}
{1153}{}{Wow – entschuldigen Sie, dass ich Sie störe, Herr Offizier! Meine Hochachtung, Herr Offizier! Ich verbeuge mich und bin bereit, Ihre Hände zu küssen, Herr Offizier!}
{1207}{}{Ich habe Beweise für ihre Schuld. Diese Aufnahme habe ich während eines Gesprächs mit Larry Geller gemacht.}
{1213}{}{Hier. Ich habe diese Broschüre heimlich von den Sklavenhändlern mitgenommen. Ein direkter Beweis.}
{1221}{}{Ich war im Hotel der Freaks. Die haben sogar in den Kisten Dope herumliegen! Das müsst ihr euch sofort ansehen!}
{1226}{}{Das ist eine Aufzeichnung unseres Gesprächs. Er hat mich angeheuert, um Bobs Neil-Pistole zu stehlen!}
{1237}{}{WAS?! Ich habe mein Leben riskiert, und alles war umsonst! Scheiß Bulle! Schieb dir die Beweise in den Arsch!}
{1245}{}{Äh ... verstehe, das ist dir wichtig. Ich wollte aber nur fragen, wie es läuft.}
{1246}{}{Nicht schlecht, Süße, sehr witzig. Und ich war froh, dass neue Hinweise aufgetaucht sind. Wir arbeiten noch an dem Fall, aber ein Ende ist nicht in Sicht.}
