{100}{}{Du siehst Curtis.}
{101}{}{Du siehst einen Mechaniker mit einem Schraubenschlüssel in der Hand. Er sieht ziemlich verwirrt aus.}

#Ïåğâûé äèàëîã
{110}{}{Was willst du, Kumpel?}
{111}{}{Ich schau nur mal vorbei und seh nach, wie es einem anderen hart arbeitenden Kerl geht.}
{112}{}{Nichts.}
{113}{}{„Ein anderer hart arbeitender Kerl“? Heh! Schlecht, wie immer. Siehst du den großen Kerl da auf dem Boden?}
{114}{}{Was ist das, ein „Robo-Cop“? Sieht komisch aus ...}
{115}{}{Ja, und wie. So viel komplizierter Kram, den man reparieren muss, nur damit er irgendwo zur Abschreckung rumstehen kann. Da könnte ich mir den Schrott gleich selbst umhängen und die Passanten erschrecken.}
{116}{}{Glaubst du, dass es keinen Nutzen davon gäbe?}
{117}{}{Nun, mit voller Munition und in gutem Zustand ist es ganz sicher eine echte Todesmaschine. Vielleicht könnte der Chief sie sogar bei Spezialoperationen einsetzen. Aber alles in allem ist dieses Ding dazu gedacht, durch sein Äußeres einzuschüchtern.}
{118}{}{Glaubst du, dass es nach der Aktivierung gefährlich sein wird?}
{119}{}{Wer weiß ... Militärmodelle wurden nicht für friedliche Zwecke gebaut, Baby. Sie wurden zum Töten gebaut! Und dieser Roboter schlummert seit etwa 70 Jahren, ohne dass sich jemand um ihn gekümmert hat. Zum Glück habe ich herausgefunden, wie man ihm die Munition entnimmt und die unteren Servomotoren deaktiviert, damit ich nicht auf der Stelle getötet werde, wenn er eingeschaltet wird. Aber was mir Angst macht, ist, dass sich nicht viele Leute mit dieser Art von Robotik auskennen. Also kann niemand sagen, was in diesem Stück Eisen wirklich vorgeht. Wir müssen uns auf Tests verlassen und viel Zeit damit verbringen, die Baupläne zu studieren. So viel Aufwand für einen einzigen Roboter! Lohnt sich das? Ich bin mir nicht sicher.}
{120}{}{Hat er irgendwelche Nachteile?}
{121}{}{Natürlich! Er ist voller Elektronik. Ein einziger Schuss aus einer Impulswaffe, und die Schaltkreise brennen einfach durch. Das ist ein häufiges Problem bei allen Robotern aus der Vorkriegszeit.}
{122}{}{Impulswaffe? Und wo findet man so eine?}
{123}{}{Ich schätze, nur in irgendwelchen Militärdepots oder an Orten, die mit der alten Armee zu tun haben. Diese Dinger wurden nicht für den zivilen Markt hergestellt.}

{128}{}{Gute Arbeit. Na ja, ich sollte dann mal los. Tschüss.}
{129}{}{Ja, bis dann.}
{130}{}{Viel Glück.}

#Âîïğîñ î âîçìîæíîñ'è ğåìîí'à
{131}{}{Kannst du mir bei Reparaturen helfen?}
{132}{}{Hör zu, ich arbeite für die Polizei. Die Cops lassen mich nicht für Außenstehende arbeiten, also ... tut mir leid, ich will meinen Job hier nicht verlieren. Ich kann dir nur einen guten Mechaniker beim Hoover Dam empfehlen. Aber er ist hauptsächlich auf Elektronik spezialisiert.}
{133}{}{Na gut. Dann will ich dich nicht weiter stören.}

#Ïîïû'êà çàãîâîğè'ü ïîñëå ïåğâîãî ğàçãîâîğà (ñëó÷àéíûå ïëàâàşùèå ôğàçû)
{150}{}{Hallo!}
{151}{}{Hey!}
{152}{}{Oh, du bist's ...}
{153}{}{Tut mir leid, ich arbeite gerade ...}
{154}{}{Was? Ist es Zeit für eine Pause?}

#Ìàøèíà
{230}{}{Hast du das Auto nicht weit von hier gesehen? Das ist mein Gefährt. Neidisch?}
{231}{}{[Pfeift] Es wäre mir eine Ehre, es auch nur berühren zu dürfen! Sozusagen aus beruflichem Interesse und technologischer Neugier. Und weißt du, wenn das Auto funktioniert, könnte ich es vielleicht mit etwas ausstatten – etwa mit Gravitationsplatten mit energozyklischem Chip! Das Auto fährt dann nicht bloß, es FLIEGT! Na ja, im übertragenen Sinne.}
{232}{}{Und hast du dieses ... Ding?}
{233}{}{Ja, es wartet auf seinen neuen Besitzer. Natürlich hätte ich auch nichts gegen eine Bezahlung für meine Arbeit. Der Preis beträgt 2500. Einverstanden?}
{234}{}{In Ordnung, hier ist das Geld.}
{235}{}{Ich habe gerade nicht genug Bargeld. Ich komme später wieder.}
{236}{}{Dann warte ein paar Stunden. Ich erledige alles und komme wieder.}
{237}{}{In Ordnung.}
{238}{}{Alles fertig! Du kannst jetzt losfahren und es ausprobieren ... Verdammt, ich bin so neidisch!}
{239}{}{Oh. Danke.}
{240}{}{Nach dem Einbau der Gravitationsplatten kann dein Auto unglaubliche Geschwindigkeiten erreichen und verbraucht dabei viel weniger Energie. Nevadas Highways, erzittert!}

#Female character
{1110}{}{Was willst du, Mädel?}
{1111}{}{Ich schau nur mal vorbei und seh nach, wie es einem anderen hart arbeitenden Kerl geht.}
