{100}{}{Siehst du, Phil!}
{101}{}{Sieh mal ... der Biker aus Battle Mountain! Was macht der hier?}

{109}{}{Na? Hast du dich noch nicht entschieden, ob du gehst oder nicht?}

#Íà÷àëî äèàëîãà
{110}{}{Hallo, mein Freund! Ich sehe, sie wollen dich nicht zurücknehmen?}
{111}{}{Das ist eine lange Geschichte. Ich glaube, sie werden sich ab jetzt nicht gerade freuen, mich hier zu sehen, so viel steht fest.}
{112}{}{Mich haben sie auch gleich rausgeworfen. Dabei habe ich gar nichts getan. Ich wollte mir nur ein bisschen den Vault ansehen. Warum sind deine Leute so geizig? Ich habe sogar angeboten zu zahlen ... Ach, verdammt.}
{113}{}{Wohin geht's jetzt?}
{114}{}{Ich weiß es noch nicht. Nördlich unserer Basis bereiten wir uns auf großen Ärger vor. Ich habe also einiges zu erledigen. Wenn du willst, kann ich dich mitnehmen.}

#Îòïğàâêà â ãîğîä
{115}{}{Ah, nein, ich komme schon allein zurecht. Mach's gut!}
{116}{}{Dann auf nach Salt Lake City!}
{117}{}{Dann auf nach New Reno!}
{118}{}{Dann setz mich in der Nähe von Lovelock ab.}
{119}{}{Kannst du mich zurück nach Battle Mountain bringen?}
{120}{}{Kannst du mich in der Nähe des Wind of War absetzen?}
{121}{}{Auf nach Las Vegas, was meinst du?!}

#Female character:
{1109}{}{Na? Hast du dich noch nicht entschieden, ob du gehst oder nicht?}
{1110}{}{Hallo, Süße! Ich sehe, sie wollen dich nicht zurücknehmen?}
{1115}{}{Ah, nein, ich komme schon allein zurecht. Mach's gut!}
