{100}{}{Siehst du: Sergeant Graves.}
{101}{}{Siehst du: Peter Graves, Leiter des Sicherheitsdienstes.}
{102}{}{Au, mein Kopf.}
{103}{}{Du hast die Tür geöffnet, die zum zweiten Aufzug führt.}
{104}{}{Du hast die Tür geöffnet, die zum Lagerhaus führt.}

#Ñòàğòîâûé äèàëîã
{110}{}{[Du siehst Sergeant Graves – brutal zusammengeschlagen, Arme und Beine gefesselt.]}
{111}{}{[Befreie ihn]}
{112}{}{[Lass ihn in Ruhe]}

{113}{}{Ughh ... Danke, Bürger. Du kommst gerade rechtzeitig. Diese Fremden haben den Vault übernommen. Wie hast du es geschafft, hier reinzukommen?}
{114}{}{Es war nicht besonders schwer. Wichtiger ist: Was machen wir jetzt?}
{115}{}{Richtig. Gegen die Fremden zu kämpfen, ist sinnlos. Es sind zu viele, und sie sind gut bewaffnet. Uns bleibt nur, ihren Forderungen nachzugeben oder einen anderen, clevereren Weg zu finden, sie unschädlich zu machen.}
{116}{}{Hast du eine Idee?}
{117}{}{Wir könnten versuchen, die Verteidigungssysteme zu aktivieren. Ich habe Zugriff auf die automatisierten Vault-Kontrollsysteme. Wenn wir dorthin gelangen und die Verteidigungsanlagen einschalten, könnte es klappen. Aber vermutlich sind sie blockiert.}
{118}{}{Gibt es noch andere Möglichkeiten, mit ihnen fertigzuwerden?}
{119}{}{Ja, aber das wäre tödlich. Laut Vorschrift müssen wir bei einer feindlichen Invasion die gesamte geheime Etage darunter zerstören. Die Explosion wird den gesamten Vault zerstören. Wir können nicht entkommen.}
{120}{}{Das ist doch nicht fair ...}

{121}{}{Dann müssen wir entweder ganz allein gegen sie kämpfen oder ihren Forderungen nachgeben. Im nächsten Raum steht ein Wachroboter. Wenn wir ihn reparieren könnten, hätten wir einen kleinen Vorteil. Jedenfalls kann ich nach all dem nicht einfach hier herumsitzen und nichts tun. Der Rat hat uns belogen, und diese Typen verteilen nicht gerade Kuchen und Luftballons. [er reibt seine Prellungen]}
{122}{}{Ausgezeichnet. Dann folgen Sie mir, Sergeant. Ich brauche jemanden, der mir den Rücken freihält.}
{123}{}{Warte eine Weile. Ich muss mich erst umsehen. Wir sollten zuerst darüber nachdenken.}

{124}{}{Wie ist die Lage?}
{125}{}{Warte, ich muss mich erst umsehen.}
{126}{}{Los, ich glaube, ich weiß, was zu tun ist.}
{127}{}{Wir reden später weiter.}

{1113}{}{Ughh ... Danke, Bürger. Du kommst gerade rechtzeitig. Diese Fremden haben den Vault übernommen. Wie hast du es geschafft, hierherzukommen?}

