{100}{}{Du siehst einen lebhaften Mann.}
{101}{}{Du siehst einen dünnen jungen Mann in einem gestreiften Hemd.}
{102}{}{Vielen Dank.}

#Äèàëîã
{110}{}{[Du siehst einen dünnen jungen Mann, der müde im Gras herumwühlt. Er trägt ein gestreiftes Hemd, das ihn zusammen mit seinem langen, ungepflegten Haar aus der Menge hervorstechen lässt.]}
{111}{}{Suchst du etwas?}
{112}{}{Hä? Oh ... Die Kings sind schon wieder am Werk. Sie haben mir die Brille weggenommen und irgendwo ins Gras geworfen. Ich suche schon seit einer Stunde danach. Wenn ich doch nur einen Metalldetektor hätte ... Uff. Sieht aus, als wäre heute nicht mein Glückstag. Ich sollte lieber ins Café gehen. Oh, wenn du die Brille findest, bring sie mir bitte zurück. Ich wäre dir sehr dankbar.}
{113}{}{Hier ist sie, du musst nicht weitersuchen.}
{114}{}{[Gehen]}

{115}{}{Hi. Hast du meine Brille gesehen? Das wäre toll.}
{116}{}{Ja, deine Brille ist gefunden worden.}
{117}{}{Nein, noch nicht.}
{118}{}{Oh! Was für ein Glück. Gib sie mir ... Toll, sie ist nicht kaputt. Vielen Dank.}
{119}{}{Mit Dank allein ist es nicht getan. Bezahl mich für meinen Fund.}
{120}{}{Gern geschehen.}
{121}{}{Wirklich? ... Dabei hattest du einen so guten ersten Eindruck gemacht. Na gut, hier sind fünf Dollar. Mehr gibt's nicht.}
{122}{}{Von dir war wohl kaum mehr zu erwarten. Tschüss.}
