{100}{}{Du siehst einen aufgebrachten Karawanenreisenden.}
{101}{}{Du siehst einen der Karawanenwachen.}
{102}{}{Nein danke, davon habe ich genug.}
{103}{}{Hey.}
{104}{}{Äh, hallo ... Lass mich erst meine Karten finden, dann reden wir ...}
{105}{}{Äh, hallo ... Lass mich erst diese Kartenstapel in Ordnung bringen. Warum gibt es davon so viele?}

#Acquaintance
{110}{}{Hey, Kumpel. Es ist ziemlich offensichtlich, dass du gerade erst aus dem Ödland kommst. Setz dich, mach eine Pause von der Reise.}
{111}{}{Warum bist du so freundlich? Hey ... Irgendwas sagt mir, dass du mich an den Kartentisch locken willst.}
{112}{}{Oh, danke, genau das brauche ich.}
{113}{}{Ich entscheide selbst, was ich mache.}
{114}{}{Du bist nicht dumm. Ehrlich gesagt wollte ich nur ein bisschen beim Kartenspiel gewinnen, aber nicht gegen Leute, die seit ihrer Kindheit in Casinos leben. Die ziehen dich aus wie einen Gecko.}
{115}{}{[Nickt ernst und geht die Karten in seinen Händen durch] Am besten entspannt man sich, indem man etwas anderes macht. Zum Beispiel in guter Gesellschaft spielt. Nur nicht mit Leuten, wie man sie im Casino findet. Die ziehen dich aus wie ein Gecko.}
{116}{}{Na gut, vergiss es. Vielleicht ist es besser so. Ehrlich gesagt wollte ich beim Kartenspiel nur ein bisschen gewinnen, aber nicht gegen Leute, die schon seit ihrer Kindheit ihr Leben im Casino verbringen. Die ziehen dich aus wie ein Gecko.}
{117}{}{Also, was möchtest du spielen?}
{118}{}{Kein Interesse. Tschüss.}
{119}{}{„Canasta“, „Caravan“, Poker – ganz wie du willst. Aber ich habe eine Bedingung: Wir spielen um Einsätze. Sozusagen Geschäftliches mit Vergnügen verbinden.}
{120}{}{Hmm, ich glaube, du hast das nicht nur aus Freundlichkeit eingefädelt. Was ist passiert, hast du im Casino dein ganzes Geld verloren?}

{121}{}{Sieht man mir das so deutlich an? Ich will nicht so tun, als wäre ich ein Heiliger. Du hast recht, genau das ist passiert. Ich habe den Kopf verloren und auf den großen Gewinn gehofft, aber am Ende nur verloren. Pass auf, ich habe ein stimpak und setze es gegen deine 100 Dollar. Was hältst du davon?}
{122}{}{Großartig, spielen wir.}
{123}{}{Warum kaufe ich dir das stimpak nicht einfach ab?}
{124}{}{Kein Interesse. Tschüss.}

#Ransom
{125}{}{Weißt du, der Händler auf der anderen Straßenseite hat mir läppische 175 Dollar für einen Steampunk geboten. Was bringt es, ihn für so einen Hungerlohn zu verkaufen, wenn du beim Kartenspielen doppelt so viel gewinnen kannst? Aber wenn du mir 350 Dollar zahlst, ist es ein gutes Geschäft.}
{126}{}{Dann lass uns spielen.}
{127}{}{Das Angebot ist gut. Hier ist dein Geld.}
{128}{}{Ich überlege es mir. Bis zum nächsten Mal.}

{129}{}{Oh, vielen Dank! Nimm es, es gehört jetzt dir.}
{130}{}{Gutes Geschäft. Auf Wiedersehen.}

#Game
{131}{}{Hier ist das stimpak. Jetzt leg 100 Dollar auf den Tisch.}
{132}{}{Na gut, hier ist mein Einsatz. Fangen wir an!}
{133}{}{Ich habe schon keine Lust mehr auf das Spiel. Verschieben wir es auf ein andermal.}
{134}{}{Mein Spielangebot gilt noch. Ich habe ein stimpak und setze es gegen deine 100 Dollar. Willst du spielen?}
{135}{}{[Wird konzentriert] Die Karten lügen nicht. Deshalb liebe ich sie. Sie verlangen dem Spieler *Geschick* und Einfallsreichtum ab, statt einfach nur eine zufällige Würfelzahl. [Er mischt und gibt die Karten] Ich werde mein ganzes Können einsetzen. Es steht nicht nur ein stimpak auf dem Spiel, sondern auch mein hungriger Magen. Also, fangen wir an ...}
{136}{}{Ja, nur zu ...}

{137}{}{[Packt sich verzweifelt an den Kopf] Was habe ich nur getan ...}
{138}{}{Ha-ha, wenn ich doch jeden Tag so viel Glück hätte! Sieh nur, wie ich dir dein ... Nein, MEIN stimpak abnehme! Und jetzt muss ich los. Viel Spaß noch, Verlierer!}
{139}{}{Ich verstehe. Bei dir muss es wirklich knapp sein. Hier, nimm diese 100 Dollar für das stimpak. Du brauchst sie dringender. Was mich angeht, ist mein Verlust immer noch geringer als mein Gewinn. Jetzt muss ich aber los.}
{140}{}{Tja, ich hatte Glück und du nicht. Ein anderes Mal könnte es auch andersherum sein. Aber jetzt muss ich los. Mach's gut.}
{141}{}{[Lehnt sich mit einem zufriedenen Grinsen im Stuhl zurück] Das war ein fairer Sieg. [Er sammelt den Gewinn vom Tisch ein und steckt ihn in die Tasche]}
{142}{}{Tja, ich hatte kein Glück. Und das war fair.}
{143}{}{Was? Wie!? Das kann nicht sein! ... Wage es ja nicht, mir auf derselben Strecke noch einmal unter die Augen zu treten, du Gauner! Sonst erinnere ich dich daran.}

#Women's replics
{1110}{}{Hey, Mädchen. Man sieht dir an, dass du gerade erst aus dem Ödland kommst. Setz dich, ruh dich ein wenig von der Reise aus.}
{1134}{}{Mein Spielangebot gilt noch. Ich habe ein stimpak und setze es gegen deine 100 Dollar. Willst du spielen?}
