{100}{}{Du siehst einen verdächtig wirkenden Karawanenhändler.}
{101}{}{Einer von vielen Karawanenhändlern. Ohne sein zwielichtiges Aussehen könntest du ihn nicht von den anderen unterscheiden.}
{102}{}{Verzieh dich!}

#Ñòàğòîâàÿ âåòêà
{110}{}{Hey, Kumpel, dieser Parkplatz gehört *uns*. Such dir einen anderen Platz, irgendwo anders, weg von unseren Wagen.}
{111}{}{Gehört dir der Laden? Na los – beweis, dass er *dir* gehört!}
{112}{}{Du bist einer von diesen „Schwarzen“, oder? Ich brauche es ... Du verstehst? Dringend! Nur eine Dosis!}
{113}{}{Na gut! Zeig mir, wo das Labor ist! Und zwar schnell!}
{114}{}{Schon gut, ich geh woanders hin.}

#Îòâåò íà 111:
{115}{}{Mach halblang, Bulle. Es ist in deinem Interesse, glaub mir.}
{116}{}{Du hast echt ein loses Mundwerk, Kumpel. Lass mich dir den Kiefer richten!}
{117}{}{Hui, wie gruselig. Na gut, ich lass es durchgehen ... fürs Erste.}

#Îòâåò íà 112:
{118}{}{Nur eine? Kein Interesse. Da drüben, bei „Hard Rock“, ist ein Kerl. Vielleicht kann er dir helfen.}
{119}{}{Nur eine? Kein Interesse.}
{120}{}{Du hast es also zugegeben. Zeit, dich zu bestrafen. Und zwar jetzt! [Angreifen]}
{121}{}{Na siehst du nicht, dass es mir dreckig geht?! Nur eine Dosis! Ich bezahle!}
{122}{}{Dann such ich eben woanders.}

{123}{}{Ich hab's dir gesagt – das ist dein Problem! Mit Junkies hab ich nichts am Hut, verstanden?!}
{124}{}{Junkie?! Ich? Dafür mach ich dich fertig!}
{125}{}{Verstanden, tut mir leid.}

#Îòâåò íà 113:
{126}{}{Na sieh einer an, hier haben wir wohl einen Kämpfer! Ruhig, Gorilla, du bist hier nicht allein.}
{127}{}{Ich bin nicht ruhig, bevor du's mir sagst! Na los, spuck's aus, Kumpel!}
{128}{}{Grmm, was du meinst ... Pavian.}
{129}{}{Na gut, noch ein Wort, und nicht mal die anderen Karawanenhändler können dich retten.}
{130}{}{Ooh, wie gruselig! Und wer schlägt zuerst zu? Vielleicht du?}
{131}{}{Verdammt, du hast mich überzeugt. Ich sollte vorsichtiger sein. Tschüss.}

{132}{}{Du bekommst gar nichts, du Affe, gar nichts! NICHTS!}
{133}{}{Warum ist das so? Vielleicht will ich dort arbeiten?}
{134}{}{Nichts? Na gut, dann sehe ich mich eben woanders um.}

{135}{}{Für solche Arbeit sucht man gezielt Leute. Dich will dort niemand.}
{136}{}{Und ich komme trotzdem und klopfe ans Tor.}
{137}{}{Schade. Wirklich schade.}

{138}{}{... und du endest als Geckofutter. Man erschießt dich gleich am Eingang.}
{139}{}{Kannst du mich empfehlen?}

{140}{}{Nein, Idiot! Verstehst du überhaupt, mit wem du redest? Ich fahre Karawanen! Wem soll ich dich empfehlen? Dem Arsch von brahmin?}
{141}{}{Ist das ... ein raffiniertes Angebot?}
{142}{}{Nein, du Affe! Das ist eine trickreiche Warnung. Ich transportiere die Waren und alles andere ist mir scheißegal. Ich bin nicht hier, um dir zu helfen, verstanden?}
{143}{}{Verstanden. Und wer kann mir helfen?}
{144}{}{Oh, na dann lasse ich dich in Ruhe.}
{145}{}{Bist du krank? Ich hab dir gesagt: Meine Aufgabe ist es, die Waren zu transportieren. Von allem anderen weiß ich nichts. Verzieh dich einfach.}
{146}{}{Äh, nicht gut.}

{147}{}{Verdammt, meine Finger jucken schon am Abzug. Ich kann das ganz schnell erledigen – ich schieß dir einfach in deinen dämlichen Kopf. Mein Partner hilft mir dabei. Aber ich brauche keinen Ärger. Hau ab, verpiss dich. Mach es uns beiden nicht schwer.}
{148}{}{...}

#Female character
{1110}{}{Hey, Mädel, das ist *unser* Parkplatz. Such dir woanders einen Platz, weg von unseren Wagen.}
{1125}{}{Verstanden, tut mir leid.}
{1126}{}{Na sieh mal an, hier haben wir eine Kämpferin! Halt die Klappe, Gorilla, du bist hier nicht allein.}
{1140}{}{Nein, Idiot! Verstehst du überhaupt, mit wem du redest? Ich fahre Karawanen! Wem soll ich dich empfehlen? Dem Arsch von brahmin?}
{1142}{}{Nein, du Affe! Das ist eine trickreiche Warnung. Ich transportiere die Waren und alles andere ist mir scheißegal. Ich bin nicht hier, um dir zu helfen, verstanden?}
{1145}{}{Bist du krank? Ich hab dir gesagt: Meine Aufgabe ist es, die Waren zu transportieren. Von allem anderen weiß ich nichts. Verzieh dich einfach.}
