{100}{}{Du siehst einen armen Mann.}
{101}{}{Du siehst einen Slumbewohner. Er hatte die Hoffnung fast aufgegeben, hält sich aber noch.}
{102}{}{Hallo.}

{110}{}{Hallo. [hustet] Nur auf der Durchreise? Oder bist du aus einem bestimmten Grund hier?}
{111}{}{Ich will nur wissen, wie das Leben in diesen Slums ist.}
{112}{}{Ich bin nur auf der Durchreise. Dann sollte ich wohl besser von hier verschwinden.}

{113}{}{Beschissen, wie du siehst. Das hier ist nicht Clean City – wir haben keinen Strom, kein Wasser, und die Häuser zerfallen gerade vor unseren Augen. Ich weiß nicht, wie lange wir unter solchen Bedingungen durchhalten.}
{114}{}{Was ist das hier? Eine Herberge?}
{115}{}{Hat hier jemand das Sagen?}
{116}{}{Warum floriert Clean City, während ihr unter solchen Bedingungen lebt?}
{117}{}{Erzähl mir von den Kings.}
{118}{}{Das war alles, ich wollte es nur wissen. Tschüss.}

{119}{}{Ja, so in etwa. Natürlich lassen wir nicht jeden hier rein, aber wir stellen auch keine hohen Anforderungen. Die Leute bleiben sowieso nicht lange – oft sterben sie einfach. Wer das nicht tut, versucht, so schnell wie möglich von hier wegzukommen.}
{120}{}{Nun, wir haben einen Verwalter, aber der ist eher zur Zierde da. Die Kings haben in diesen Slums das Sagen.}
{121}{}{Weil sie Geld und Macht haben. Wir haben nichts. Sie haben ihre Stadt so sauber und ordentlich gemacht, aber nicht mit eigenen Händen, sondern durch Sklaverei! Und sie benutzen Leute wie uns als billige Arbeitskräfte. Hier einen Job zu finden, ist unmöglich. Man muss für fast nichts arbeiten, und Clean City nutzt das aus. Gierig und arrogant.}
{122}{}{Mit ihnen ist nicht zu spaßen. Wenn sie dir sagen, du sollst etwas tun, solltest du es besser ohne Murren tun. Vielleicht triffst du sie in anderen Gegenden, sie sind überall am Stadtrand. Aber sie sind nicht einfach nur eine Gang. Sie behalten alles im Auge, besorgen Wasser und Nahrung und halten andere Gangs in Schach. Dafür arbeiten wir für sie. Die Schwachen sind Nahrung für die Starken, sagen sie.}

