{100}{}{Du siehst den Quartiermeister.}
{101}{}{Du siehst einen einfachen Arbeiter im Lagerhaus. Er ist faul und scheint unter Hämorrhoiden zu leiden.}
{102}{}{Hier kannst du nicht einfach durchlaufen! Geh außen herum durch den Korridor ...}

{110}{}{Was willst du?}
{111}{}{Das ist ein Lagerhaus, oder? Gibt es hier etwas von dieser Liste?}
{112}{}{Nichts.}

{113}{}{Von der Liste haben wir nur den Druckregler, einen ganzen Waggon voll! Die liegen hier nur herum und verstauben, völlig nutzlos. Es gibt niemanden, dem wir sie andrehen könnten.}
{114}{}{Vielleicht kannst du mir ja einen überlassen, wenn sie sowieso nutzlos sind?}

{115}{}{Na ja, nicht umsonst. Ich glaube nicht, dass jemand einen fehlenden Druckregler bemerken würde, aber Essen ist eine Seltenheit. Wir werden nicht gerade gut bezahlt, weißt du. Also entscheide dich: Ich kann ihn dir für 500 $ verkaufen oder gegen 10 Pizzen aus Phillips' Café eintauschen.}
{116}{}{Wie wär's mit Nuka-Cola? Ich versorge die Leute damit und kann dir mindestens eine ganze Kiste bringen.}
{117}{}{Ich habe so viele Pizzen, wie du brauchst. Hier, nimm sie.}
{118}{}{Hier sind die 10 Pizzen, wie vereinbart.}
{119}{}{Hier ist das Geld. Jetzt gib mir das Gerät.}

{120}{}{[Gierig schnappt er sich das Geld und versteckt es im Ausschnitt. Er sieht sich um und holt einen Druckregler.] Hier. Aber sei vorsichtig, niemand darf etwas merken.}
{121}{}{Aha, in Ordnung.}
{122}{}{Das nenne ich Service! Also, ich hole jetzt den Druckregler. Wenn du ihn mitnimmst, pass auf, dass es niemand merkt.}

{123}{}{Wirklich? Na ja, wenn du die Fabrik belieferst, warum nicht! 250 Flaschen, und der Druckregler gehört dir.}
{124}{}{Wie seltsam, ich habe genau die richtige Anzahl Flaschen dabei. Ich trage sie für alle Fälle mit mir herum, weißt du ...}
{125}{}{Ich habe die richtige Menge in den Lagerhäusern dieser Stadt. Ich bringe sie dir ...}
{126}{}{Ich habe nicht so viel in einem Lager vor Ort. Wir müssen warten.}
{127}{}{Ich werde über das Angebot nachdenken. Tschüss.}

{128}{}{Du bist wie ein brahmin Traktor! Jetzt muss ich einen Platz dafür finden, wo die anderen es nicht sehen ... Ach ja, hier ist der Regler. Aber vorsichtig, niemand darf etwas merken.}
{129}{}{Natürlich ...}

{130}{}{Wie du willst. Schließlich hast du es selbst vorgeschlagen.}
{131}{}{Tschüss.}

{132}{}{[Du bringst die benötigte Menge Nuka-Cola aus dem Lager ins Café.] }

{133}{}{Hast du über mein Angebot nachgedacht? Es gilt noch immer.}
{134}{}{Erinner mich noch mal: Was wolltest du als Gegenleistung?}
{135}{}{Nein, noch nicht.}
{136}{}{Such dir was aus: Ich kann dir das Ding für 500$ verkaufen oder gegen 10 Pizzen aus dem Café der Phillips eintauschen.}

#Æåí ğåïëèêè
{1130}{}{Wie du willst. Schließlich hast du es selbst vorgeschlagen.}
{1133}{}{Hast du über mein Angebot nachgedacht? Es gilt noch immer.}