{100}{}{Du siehst Bob Neil.}
{101}{}{Du siehst Bob Neil, den Leiter des Umspannwerks.}
{102}{}{Bob Neil ist tot. Stell dir das Blutbad vor, das jetzt um Hoover Dam losgehen wird ...}

{300}{}{Neu in der Stadt? Ich kann mich nicht erinnern, dich schon einmal getroffen zu haben ...}
{301}{}{Ja, wie kann ich helfen?}
{302}{}{Ach, du bist es. Was brauchst du?}

{305}{}{Keine Sorge, ich geh ja schon.}

#Question 1, meeting
{310}{}{Entschuldigung, mit wem spreche ich?}
{311}{}{Mit mir, natürlich. Ich würde lieber zuerst *deinen* Namen hören.}
{312}{}{Mein Name ist }
{313}{}{. Und du bist ...}
{314}{}{Geht dich nichts an, Alter.}
{315}{}{In dem Fall rede ich lieber nicht mit dir.}

{316}{}{Oh, gute Manieren? Das ist ja großartig. Ich heiße Bob Neil und bin gerade für den Damm zuständig. Also, was führt dich her?}
{317}{}{Größtenteils Neugier. Was kannst du mir über diesen Ort erzählen?}
{318}{}{Ich habe einen Rat für dich: Pass in dieser Stadt auf, was du sagst, Wanderer. Das ist generell sehr wichtig, besonders aber hier.}
{319}{}{Aha. Na gut, auf Wiedersehen.}
{320}{}{Danke für den Hinweis. Also, wie heißt du?}

{322}{}{Wenn es so wichtig ist: Ich heiße Bob Neil und bin für diesen Damm zuständig. Noch Fragen?}
{323}{}{Das war's fürs Erste. Bis dann.}
{324}{}{Das gefällt mir nicht. Du solltest besser verschwinden.}
{325}{}{Mit Vergnügen.}
{326}{}{Gut, dann störe ich dich nicht weiter.}

#Question 2, about the dam
{330}{}{Kannst du mir etwas über diesen Ort erzählen?}
{331}{}{Ich denke, dafür kann ich etwas Zeit erübrigen. Was möchtest du wissen?}
{332}{}{Deine Geschichte. Wie hast du es geschafft, das alles aufzubauen?}
{333}{}{Was ist das hier für ein Ort?}
{334}{}{Versorgst du die ganze Stadt mit Strom?}
{335}{}{Was machen all diese Leute?}
{336}{}{Was ist deine Aufgabe?}
{337}{}{Das reicht. Ich wollte noch etwas anderes wissen.}

{340}{}{Es war nicht schwer, das hier in Gang zu bringen. Das meiste lief seit dem Großen Krieg bereits automatisch. Die Probleme begannen, als die Ausrüstung langsam verschliss. Ich nahm die Sache selbst in die Hand und fing an, Strom zu einem angemessenen Preis zu verkaufen, um den Wertverlust auszugleichen. Doch das Bürgermeisteramt und die Geschäftsleute vor Ort beschlossen, alles zu übernehmen. Nach einer Reihe von Konflikten mussten wir einen Kompromiss finden. So kamen wir auf das Aktiensystem. Es ist vielleicht nicht perfekt, aber es hat offenes Blutvergießen verhindert und dafür gesorgt, dass der Damm in meiner Hand blieb.}
{341}{}{Und was ist mit dem Damm?}
{342}{}{Der Damm lief seit dem Krieg automatisch. Das tut er noch immer. Die eigentliche Arbeit fällt bei den Umspannwerken und Stromleitungen an – dort, wo der Strom in der Stadt verteilt wird.}
{343}{}{Das ist Kraftwerk Nummer eins. Der größte Teil des vom Damm erzeugten Stroms wird hier produziert. Angesichts des Wachstums von Vegas werden wir in Zukunft ein zweites Kraftwerk in Betrieb nehmen müssen. Im Moment haben wir mit einem schon genug Probleme.}
{344}{}{Erzähl mir deine Geschichte. Wie hast du es geschafft, diesen Ort in Gang zu bringen?}
{345}{}{Na ja, fast. Einige Bezirke und einzelne Gebäude haben beschlossen, sich selbst mit Energie zu versorgen, mithilfe kleiner Kernreaktoren und Generatoren. Trotzdem kommt der größte Teil der Energie in der Stadt von uns.}
{346}{}{Sie sind dafür zuständig, dass die Ausrüstung funktioniert und der Ort sauber ist. Außerdem haben wir ein Team, das sich um die Wartung und Reparatur der Stromleitungen kümmert.}
{347}{}{Mich um die Öffentlichkeitsarbeit kümmern und dafür sorgen, dass diese Idioten keinen Unsinn anstellen.}
{348}{}{Klingt, als wärst du unzufrieden damit, wie deine Angestellten ihre Arbeit machen.}
{349}{}{Im Moment läuft es bei uns nicht gerade gut, dank des Verwaltungskriegs um den Besitz des Damms. Die Leute wollen deshalb nicht wirklich hier arbeiten, und diejenigen, die es doch tun, kommen mit dem harten Dienstplan und der miesen Bezahlung nicht klar.}
{350}{}{Merkwürdige Lage für das wichtigste Unternehmen der Stadt, findest du nicht?}

#Question 3 - receiving quest to find workers
{351}{}{Die verdammten Anteilseigner haben alles so eingefädelt, dass uns kaum Geld bleibt, um die Arbeiter zu bezahlen. Sie wollen uns mittellos zurücklassen und sich dann den Damm unter den Nagel reißen. Gecko-Gesindel ...}
{352}{}{Wenn es dir an Arbeitern mangelt, könnte ich versuchen, ein paar neue Leute aufzutreiben.}
{353}{}{Das habe ich dir schon gesagt. Wir brauchen billige Arbeitskräfte.}
{354}{}{Ich kümmere mich um die Öffentlichkeitsarbeit und sorge dafür, dass alles reibungslos läuft. Dank der neuen Arbeitskräfte läuft es ziemlich gut. Danke, Wanderer.}
{355}{}{Verstehe. Gehen wir ein wenig zurück.}
{356}{}{Interessanter Vorschlag, aber wenn es so einfach wäre, hätte ich es längst selbst getan. Wir haben nicht viel Auswahl. Wahrscheinlich müssen wir Sklaven kaufen. Aber die Sklavengilde ist einer der Anteilseigner. Noch mehr Druck kann ich nicht gebrauchen.}
{357}{}{Was, wenn jemand anders Sklaven kauft und sie an dich verkauft?}
{358}{}{Sklaven sind teuer. Es ist schwer, jemanden zu finden, der 20 Sklaven kaufen kann und kein eigenes Interesse an der Sache hat. Kurz gesagt: eine Sackgasse.}
{359}{}{Ich sehe, was ich tun kann.}
{360}{}{Ich kann nichts versprechen.}

#Finding workers quest - freaks:
{370}{}{Hast du schon einmal daran gedacht, Mutanten als Arbeitskräfte einzusetzen?}

{371}{}{Hast du nichts davon gehört? Die Polizei hat diesen stinkenden Abschaum aus unserer Stadt vertrieben. Selbst wenn ich wollte, wäre niemand mehr da, den ich einstellen könnte.}
{372}{}{Dann eine andere Frage.}
{373}{}{Hm. Ich habe keine weiteren Fragen.}

{374}{}{Glaubst du wirklich, diese verwesenden Leichen wären für die Arbeit geeignet?! Außerdem sind sie wegen ihres Rufs in der Stadt nicht vertrauenswürdig.}
{375}{}{Die Polizei hat für sie gebürgt. Das sollte doch etwas zählen.}
{376}{}{Du bist mit ihrem Ruf unzufrieden? Dann hätte ich noch eine Frage.}
{377}{}{Hm. Ich habe keine weiteren Fragen.}

{378}{}{Ach? Das wusste ich nicht. Danke für den Hinweis. Wie gut sind sie bei körperlicher Arbeit?}
{379}{}{Schluss mit den Vorurteilen! Sie sind billig und effektiv, trotz ihres Aussehens.}
{380}{}{Als Wissenschaftler kann ich dir sagen: Dank einer Kombination aus Strahlung und einer Art Virus wurden ihre Zellen teilweise durch mineralische Gegenstücke ersetzt. Kurz gesagt, haben sie einige körperliche Vorteile für die Arbeit.}
{381}{}{Vertrau mir einfach.}
{382}{}{Ich weiß es nicht. Ich werde der Sache nachgehen.}

{383}{}{Na gut, wenn du so überzeugt von ihnen bist ... Angesichts ihrer derzeitigen Lage werden sie nicht viel verlangen ... Na schön, du hast mich überzeugt. Ich gebe den Freaks eine Chance und sehe, wie es läuft. Danke, Wanderer.}
{384}{}{Großartig!}
{385}{}{Du hast Bob Neil überzeugt, die Freaks einzustellen.}
{386}{}{Nicht überzeugend. Seine Ansichten auf die inspirierende Rede eines anderen zu stützen, ist keine gute Idee. Ich hoffe, du verstehst das.}
{387}{}{Hm, darüber muss ich nachdenken.}

{388}{}{Oh, das ist interessant! Wenn sie ausdauernder und weniger anfällig für Umwelteinflüsse und Strahlung sind, eignen sie sich hervorragend als Arbeiter. Und angesichts ihrer gesellschaftlichen Stellung werden sie nicht viel verlangen ... Na schön, du hast mich überzeugt. Ich arbeite mit den Freaks zusammen und sehe, wie es läuft. Danke, Wanderer.}
{389}{}{Großartig!}

{390}{}{Weißt du, du siehst nicht gerade wie ein Wissenschaftler aus ...}
{391}{}{Natürlich verdient ein Mann von deinem Ruf in Vegas unser Vertrauen. Du hast mich überzeugt. Ich arbeite mit den Freaks zusammen und sehe, wie es läuft. Danke, Wanderer.}
{392}{}{Ehrlich gesagt habe ich nicht viel Gutes über dich gehört. Warum sollte ich dir vertrauen?}

{393}{}{Ah, da ist unser Retter der Verdammten. Ich wusste, dass es früher oder später so enden würde. Na ja, jetzt, wo die Ghule weg sind, stehen wir wieder ganz am Anfang. Wir brauchen Arbeitskräfte.}
{394}{}{Das ist bedauerlich. Ich hoffe, du findest eine Lösung.}
{395}{}{Ich habe alles getan, was ich konnte, um zu helfen. Dein Gejammer will ich mir nicht anhören.}

{396}{}{Sieht so aus, als wäre billige Arbeitskraft in der Stadt völlig verschwunden ...}
{397}{}{Ja, im Grunde ist es das. Sklavenstadt ist leer, der Bürgermeister gibt keinen Cent für unsere Unterstützung. Ich hatte Hoffnung in die Ghule gesetzt, trotz meines Widerwillens gegen sie. Aber leider sind sogar sie weg. Sieht so aus, als bliebe mir nur, das Schicksal des Damms diesen Snobs von Clean City zu überlassen und zu hoffen, dass sie mich nicht wie einen Hund vor die Tür setzen.}
{398}{}{Das tut mir leid zu hören. Ich denke, ich gehe dann jetzt. Bei mir läuft es nicht ganz so schlecht.}

#Quest for labour force - slaves:
{400}{}{Ich kann dir ein paar Sklaven verkaufen. Interesse?}

{401}{}{Verdammt ja! Aber bist du sicher, dass die Sklavenhändlergilde nicht weiß, wofür sie gedacht sind?}
{402}{}{Ja, bin ich. Keine Sorge.}
{403}{}{Na gut. Als hätte ich eine Wahl. Dann muss ich mich wohl mit deinen Sklaven zufriedengeben. Nach Gildenpreisen sind sie etwa 10.000 $ wert. Ich kaufe sie dir für 15.000 $ ab.}
{404}{}{Einverstanden.}
{405}{}{20.000 $, keinen Cent weniger. Sonst suche ich mir einfach einen anderen Käufer.}
{406}{}{Ich habe es mir anders überlegt. Auf Wiedersehen.}

{407}{}{Das ist ja Wucher! Aber ... Uff ... Ich brauche sie einfach zu dringend. Na gut, ich willige in 20.000 $ ein. Aber das ist mein letztes Angebot.}
{408}{}{Großartig, es ist mir ein Vergnügen, mit dir Geschäfte zu machen.}
{409}{}{Nein danke, ich suche lieber nach anderen Verkäufern.}
{410}{}{Du wirst keine finden. Mein Angebot steht.}
{411}{}{Na gut. Machen wir 15.000 $.}

{412}{}{Ein gutes Geschäft! Jetzt wird alles viel besser.}
{413}{}{Viel Glück.}
{414}{}{Du hast deine Sklaven an Bob Neil verkauft.}

#Quest for labour -- finished:
{415}{}{Wie machen sich die neuen Arbeiter?}
{416}{}{Diese Freaks sind Gold wert! Sie sind nicht wählerisch, sehr ausdauernd und haben keine Angst vor der Strahlungshitze. Das Beste ist, dass sie umsonst arbeiten! Und ... ehrlich gesagt mag ich manchmal sogar ihre Witze. Eine großartige Truppe. Ich bin froh, dass sie bei uns sind.}
{417}{}{Gut, ich habe noch eine Frage.}
{418}{}{Gut. Ich muss jetzt gehen.}
{419}{}{Ich bereue den Kauf nicht. Mit den Sklaven gibt es ein paar Probleme. Ich musste einen Koch und Aufseher einstellen, aber das ist nichts im Vergleich zu dem, was sie für uns leisten werden. Ich bin zufrieden und ... danke dir.}

#Hal Wallace's quest
{450}{}{Warum hasst Hal Wallace dich?}
{451}{}{Was? Wovon redest du?}
{452}{}{Er, äh, suchte jemanden, der dich verhaften lässt.}
{453}{}{Er hat mich gebeten, dich aus dem Weg zu räumen.}
{454}{}{Nun, es geht das Gerücht um, dass er etwas gegen dich hat.}

{455}{}{Dieser Hurensohn! Ich habe ihn schon eine ganze Weile in Verdacht!}
{456}{}{Wovon redest du?}
{457}{}{Das ist mir egal. Sag mir, warum ich das nicht tun sollte?}

{458}{}{Ist er jetzt bereit, offen zu handeln? Hmm, hat er noch ein paar Asse im Ärmel gefunden?}
{459}{}{Diese Stadt liebt es, hinter deinem Rücken zwielichtige Geschäfte abzuwickeln. Und du kannst deinen letzten Dollar darauf verwetten, dass Wallace darin verwickelt ist.}
{460}{}{Wovon redest du?}
{461}{}{Alle einflussreichen Leute in Vegas, Hal eingeschlossen, versuchen, die Hoover Dam zu übernehmen. Normalerweise versuchen sie es auf legalem Weg, aber in letzter Zeit hat jemand zu Sabotage gegriffen.}
{462}{}{Wie bitte? Was meinst du?}
{463}{}{Zuerst verloren wir wichtige Mitarbeiter. Dann tauchten obszöne Beleidigungen und falsche Anschuldigungen an den Stadtmauern auf. Im Rathaus gab es Verwirrung wegen der Neuverteilung der Anteile, und die Polizei leitete mehrere schmutzige Verfahren ein, um unseren Ruf zu ruinieren. Wer uns in den Bankrott treiben will, weiß ganz genau, was er tut.}
{464}{}{Aber warum?}
{465}{}{Wenn wir bankrottgehen, beginnt der Krieg um den Damm erst richtig. Die Stadt wird in Trümmer gelegt, Menschen werden sterben. Aber wer auch immer gewinnt, wird der einflussreichste Mann der Stadt sein. Manche würden das Risiko für gerechtfertigt halten.}
{466}{}{Und Wallace?}

{467}{}{[Bob Neil bemerkt nicht, dass du das Gespräch mit deinem Pip-Boy aufzeichnest.] Er ist ein hinterhältiger Gangster. Er handelt nie selbst, sondern schickt lieber Mittelsmänner los, die seine schmutzige Arbeit erledigen, damit ihn niemand dafür verantwortlich machen kann.}
{468}{}{Ich kann mich um ihn kümmern. Ein für alle Mal.}
{469}{}{Also, warum sollte ich den Auftrag nicht ausführen, den er mir gegeben hat?}
{470}{}{Nun, das ist dein Problem. Ich halte mich lieber raus.}
{471}{}{Ich bin kein Freund solcher Methoden, aber das ist zu weit gegangen. Na schön. Ich zahle dir 5000$, wenn du ihn beseitigst.}
{472}{}{Na schön. Ich erledige das.}
{473}{}{Ich überleg's mir.}
{474}{}{Ich nehme an, dich interessiert nur die Bezahlung. In dem Fall habe ich ein Gegenangebot ... Es ist dir egal, wen du beseitigst, oder? 5000$.}
{475}{}{Vergiss es, alter Mann! Ich erfuelle Wallaces Auftrag!}

{476}{}{Natürlich. Das ist durchaus vernünftig. Und jetzt geh bitte. Alles Gute.}
{477}{}{Auf Wiedersehen.}
{478}{}{In diesem Fall habe ich keine andere Wahl ...}
{479}{}{[Gehen]}

{480}{}{Wallace wird uns nicht mehr im Weg stehen. Ich habe meinen Teil der Abmachung erfuellt. Wie sieht es mit deinem aus?}
{481}{}{Perfekt! Ich habe schon alles darüber gehört. Hier ist deine Bezahlung, wie versprochen. Aber wir wissen nichts und hatten nichts miteinander zu tun. Ich hoffe, du verstehst das.}
{482}{}{Hoffentlich endet deine Pechsträhne jetzt?}
{483}{}{Natürlich, kein Problem.}

{484}{}{Es ist dumm anzunehmen, dass ein einziger Mann hinter der ganzen Sache steckt. Da sind noch andere. Aber der größte Parasit ist beseitigt. Das bedeutet, ich kann nachts ruhig schlafen, ebenso wie meine Angestellten.}
{485}{}{}
{486}{}{Verstanden.}
{487}{}{Jetzt sollten Wallaces Anteile unter den anderen Teilhabern aufgeteilt werden. Das bedeutet auch, dass ein Teil davon an den Damm zurückgeht. Das ist gut. Die Clean City wird nur davon profitieren, genau wie alle anderen. Ich bezweifle, dass jemand eine Neuberechnung verlangen wird.}
{488}{}{Verstanden. Ich muss jetzt gehen.}
{489}{}{Erklär mir erst einmal, was hier los ist.}

#Female version
{1318}{}{Ich habe einen Rat für dich: Pass in dieser Stadt auf, was du sagst, Wanderer. Das ist generell sehr wichtig, besonders aber hier.}
{1354}{}{Ich kümmere mich um die Öffentlichkeitsarbeit und sorge dafür, dass alles reibungslos läuft. Dank der neuen Arbeitskräfte läuft es ziemlich gut. Danke, Wanderer.}
{1383}{}{Nun, wenn du so von ihnen überzeugt bist, musst du deine Gründe haben. In ihrer jetzigen Lage werden sie nicht viel verlangen ... Na gut, du hast mich überzeugt. Ich gebe den Freaks eine Chance und sehe, wie es läuft. Danke, Wanderer.}
{1388}{}{Oh, das ist interessant! Wenn sie ausdauernder und weniger anfällig für Umwelteinflüsse und Strahlung sind, eignen sie sich hervorragend als Arbeiter. Und angesichts ihrer gesellschaftlichen Stellung werden sie nicht viel verlangen ... Na schön, du hast mich überzeugt. Ich arbeite mit den Freaks zusammen und sehe, wie es läuft. Danke, Wanderer.}
{1391}{}{Natürlich kann man einer Frau mit deinem Ruf in Vegas vertrauen. Du hast mich überzeugt. Ich werde mit den Freaks zusammenarbeiten und sehen, wie es läuft. Danke, Wanderer.}
{1393}{}{Ah, da ist unser Retter der Verdammten. Ich wusste, dass es früher oder später so enden würde. Nun, da die Ghule weg sind, stehen wir wieder am Anfang. Wir brauchen Arbeitskräfte.}
{1402}{}{Ganz sicher. Keine Sorge.}
{1404}{}{Mit dem Preis bin ich einverstanden.}
{1406}{}{Ich habe es mir anders überlegt. Mach's gut.}
{1457}{}{Das ist mir egal. Sag mir, warum ich das nicht tun sollte?}
{1469}{}{Also, warum sollte ich den Auftrag nicht ausführen, den er mir gegeben hat?}
{1480}{}{Wallace wird kein Problem mehr sein. Ich habe meinen Teil der Abmachung erfuellt. Wie sieht es mit deinem aus?}