{100}{}{Du siehst einen Handwerker.}
{101}{}{Du siehst einen düsteren Kerl, der ganz in seine offensichtlich unglücklichen Gedanken versunken ist.}

{102}{}{Fass mich nicht an! Ich kann übrigens kämpfen!}
{103}{}{Die Sirene am Damm hat sich eingeschaltet. Das ist bestimmt das Werk dieses Putzmanns von oben.}
{104}{}{Warte nur ab, du Hurensohn!}

{110}{}{[Vor dir steht ein gewöhnlicher Hausmeister mit einer Bürste in der Hand. Er runzelt die Stirn, als er bemerkt, dass du näher kommst]}
{111}{}{Hey, Kumpel, kann ich kurz mit dir reden?}
{112}{}{[Lass den Arbeiter in Ruhe]}

{113}{}{Warum ich? Warum nervst du nicht jemand anderen? Ach ja – ich bin der Einzige hier, der Rest sitzt in einem sicheren Bunker unter der Erde. Glaubst du etwa, ich würde mir vor Aufregung in die Hose machen?}
{114}{}{Ich verstehe nicht, warum fährst du mich so an?}
{115}{}{Ich nehme an, dir gefällt diese Arbeit nicht, oder?}
{116}{}{Ich will mir keine Beschwerden anhören. Mach's gut.}
{117}{}{Na ja, tut mir leid. Ich hab einfach genug davon – ich meine, von dem Damm und ganz Vegas. Nur Probleme, keine Sicherheit.}
{118}{}{Und ob! Ich halte es nicht mehr aus! Vor Kurzem haben sie schon wieder meinen Lohn gekürzt. Und es geht das Gerücht um, dass Clean City die Mehrheit der Aktien bekommen soll. Dann sind wir alle erledigt. Sie ersetzen uns durch jemanden Cooleren und setzen uns alle vor die Tür, um Sabotage zu verhindern. Ich will nicht warten, bis es so weit ist. Besser, ich denke voraus.}
{119}{}{Wenn du diesen Job aufgeben willst, kannst du mir sagen, wie ich in die Station komme?}
{120}{}{[Sieht sich um] Du brauchst das wirklich, oder? Was, wenn du ein weiterer Spion bist und alle herausfinden, dass ich dich reingelassen habe?}
{121}{}{Ich weiß nicht, vielleicht finden wir ja etwas, das für uns beide von Interesse ist?}

{122}{}{Na gut, hör zu, ich kenne ein spezielles Passwort für Notfälle. Ich verrate es dir, wenn du mir das ganze Geld gibst, das diese Verwaltungsfuzzis mir vorenthalten haben. Das sind 1000 Kröten. Abgemacht?}
{123}{}{Na gut. Hier ist das Geld, gib mir das Passwort.}
{124}{}{Keine Abmachung. Ich erledige dich einfach und nehme deine Schlüsselkarte.}
{125}{}{Ich werde über dein Angebot nachdenken.}
{126}{}{Was hast du über das Passwort gesagt?}
{127}{}{[Sieht sich verstohlen um und steckt das Geld schnell weg] Pst! Wir müssen uns doch nicht in so einem exponierten Bereich in Schwierigkeiten bringen! Also, hör zu ... [Der Arbeiter flüstert das Passwort und entfernt sich vom Gelände des Damms]}
{128}{}{[Kümmere dich um deinen eigenen Kram]}
{129}{}{Na schön, ich habe schon von Leuten wie dir gehört. Sie spielen den Harten und schüchtern andere ein, aber drängt man sie in die Enge, machen sie sich in die Hose.}
{130}{}{[Nervös eine Waffe ziehen und auf den Arbeiter richten]}
{131}{}{Dann machen wir es auf deine Art. Hier ist das Geld, gib mir das Passwort.}

{132}{}{Hey, hey, immer mit der Ruhe!}
{133}{}{Sag mir verdammt noch mal das Passwort, du Arschloch! Sag es mir, bevor ich wütend werde!}
{134}{}{[Die Knie des Arbeiters geben nach, und auf seiner Hose zeigen sich nasse Flecken] B-bitte nicht! Ich sag es dir! Fass mich bloß nicht an!}
{135}{}{Das hättest du gleich sagen sollen ...}
{136}{}{[Der Arbeiter nennt dir das Passwort und rennt davon, nachdem du die Waffe von ihm abgewandt hast]}
{137}{}{[Ihm in den Rücken schießen]}
{138}{}{[Ihn laufen lassen]}
{139}{}{[Der Arbeiter hält dich für einen schwachen Gegner und stößt dich weg]}
{140}{}{[Angreifen]}

{141}{}{Hast du gesehen, wie viele Leute ich im örtlichen Ring fertiggemacht habe? Glaubst du, ich kann dir nicht dasselbe antun?}
{142}{}{Wo zum Teufel kommen solche Leute wie du her?! Ich habe nichts falsch gemacht ... Na gut, hier ist das Passwort. Wage es ja nicht, mich anzufassen!}
{143}{}{Du kannst jetzt gehen.}

{144}{}{Du bist so verspannt, Baby, du musst dich einfach entspannen. Soll ich dir Gesellschaft leisten?}
{145}{}{[Grinst über beide Ohren] Wo wir gerade davon sprechen, warum eigentlich nicht ... Bin ich etwa den ganzen Tag umsonst hier festgesessen? Na gut, komm mit, ich zeig dir den Damm. Sieh mal, hier haben wir ein abgelegenes Plätzchen, und irgendwo habe ich Bier versteckt ...}
{146}{}{Igitt, wie vulgär ... Ich will meine Zeit nicht mit jemandem wie dir verschwenden.}
{147}{}{Komm schon, Baby!}
{148}{}{Wie soll ich es ausdrücken ... Du bist nicht mein Typ. Nicht gut genug, um mich von dem abzulenken, was ich gerade mache.}
{149}{}{Na, dann fick dich, Arschloch!}
{150}{}{Könnte es nicht noch ein anderes gemeinsames Interesse zwischen uns geben?}
{151}{}{Der Arbeiter zwang dich zu hartem, schmutzigem Sex und ging danach seelenruhig davon. Du beschlossest, mit solchen egoistischen Individuen nie wieder etwas zu tun zu haben.}
{152}{}{[Während du am Damm entlanggingst, führte dich ein Arbeiter, der sich mit Alkohol Mut angetrunken hatte, schließlich zur Toilette und drückte dich gegen die Wand. Dann begann er, dir an die Brüste zu fassen und dir an den Hintern zu greifen.]}
{153}{}{[Gib ihm nach]}
{154}{}{[Reiß dem Bastard die Kehle heraus]}
{155}{}{[Widerstand leisten]}

#Women's replics
{1133}{}{Sag mir verdammt noch mal das Passwort, du Arschloch! Sag es mir, bevor ich wütend werde!}
