{100}{}{Du siehst einen Arbeiter.}
{101}{}{Du siehst einen gewöhnlichen Arbeiter.}

#Ïîïûòêà ğàçãîâîğà, êîãäà îí óæå ñîñòîÿëñÿ:
{102}{}{Ich bin beschäftigt. Siehst du das nicht?}

#Ïëàâàşùèå ôğàçû, êîãäà Áîá Íèë æèâ-çäîğîâ è íà ìåñòå
{110}{}{Vegas ist eine verrückte Stadt.}
{111}{}{Noch ein paar Schichten, dann bin ich reich.}
{112}{}{Wo ist der Boss?}
{113}{}{In dieser Stadt einen Job zu finden, ist wie einem Gecko das Fell zu stehlen.}
{114}{}{Ich gebe meinen nächsten Lohn im Café von Sam aus! ...}
{115}{}{Die Pizza von Phillips ist der Hammer!}
{116}{}{Ist das Toilettenpapier? ... Oh, das ist das Handbuch.}
{117}{}{Wo ist mein Werkzeug?}
{118}{}{So müde ...}
{119}{}{Schon wieder voller Öl ...}
{120}{}{Ich bin so dreckig, dass mich keiner erkennt.}
{121}{}{Ich habe schon ewig nicht mehr gebadet.}
{122}{}{Stinke ich sehr?}
{123}{}{Ugh ... Das Zeug macht mich schwindelig.}
{124}{}{Ugh ...}
{125}{}{::gähnt, ohne sich die Hand vor den Mund zu halten::}
{126}{}{::kratzt sich::}
{127}{}{Mein ganzer Körper juckt ...}
{128}{}{Ich habe Hunger.}
{129}{}{Bald verhungere ich.}

#Ïëàâàşùèå ôğàçû, êîãäà Áîá Íèë â òşğÿãå èëè óìåğ
{130}{}{Vegas ist eine beunruhigende Stadt.}
{131}{}{Noch ein paar Tage, dann bin ich pleite.}
{132}{}{Was sollen wir nur ohne unseren Boss machen?}
{133}{}{Einen neuen Job finden? Verdammt, da kann ich mich ja gleich aufhängen.}
{134}{}{Ich betrinke mich in Sams Café und vergesse alles.}
{135}{}{Wer hat meine Werkzeuge geklaut?}
{136}{}{Völlig erschöpft ...}
{137}{}{Ohne Gehaltsscheck lassen sie mich nicht in mein Haus.}
{138}{}{Seit einem Monat nicht mehr gebadet!}
{139}{}{Stinke ich sehr?}
{140}{}{Ugh ... Das Zeug macht mich schwindelig.}
{141}{}{Oh ...}
{142}{}{::gähnt, ohne sich die Hand vor den Mund zu halten::}
{143}{}{::kratzt sich::}
{144}{}{Mein ganzer Körper juckt ...}
{145}{}{Ich muss was essen, habe aber nicht mal Geld für ein Sandwich.}
{146}{}{Bald verhungere ich.}
{147}{}{Was sollen wir jetzt nur ohne Bob machen?}
{148}{}{Bob ist ein guter Mann. Ich glaube nicht, dass er schuldig ist!}
{149}{}{Bob wurde reingelegt! Da bin ich mir sicher!}

#Ïåğâûé äèàëîã
{250}{}{Siehst du nicht, dass ich beschäftigt bin?!}
{251}{}{Ich wollte nur wissen, was du da machst.}
{252}{}{Wie kommt ihr ohne euren Chef zurecht?}
{253}{}{Ich glaube, du bist einfach nur faul. Tschüss.}
{254}{}{Na gut, wenn du beschäftigt bist, lasse ich dich in Ruhe.}

{255}{}{Das würdest du nicht verstehen. Ehrlich gesagt verstehe ich es manchmal selbst nicht. Aber wir haben fähige Ingenieure, also kommen wir zurecht.}
{256}{}{Jetzt hat das Rathaus das Sagen. Nur ist das hoffnungslos. Sie haben keine Ahnung von Elektrizität. Sie glauben, wir kämen allein klar, aber ohne Bob schaffen wir das eigentlich nicht. Viele hier wollen sich einen anderen Job suchen ... Auch wenn das vielleicht noch schwieriger wird.}