{100}{}{Du siehst einen Dealer.}
{101}{}{Du siehst einen Mann in zerknitterter Kleidung. Er reibt sich die Nase und schaut sich verstohlen um.}
{102}{}{Denk nicht mal dran. So leicht kommt nichts in meine Taschen.}
{103}{}{Du hast einen Hinweis auf ein Drogenlabor irgendwo in der Nähe erhalten Las Vegas.}

#Dialogue mode
{110}{}{Komm näher, du erregst zu viel Aufmerksamkeit, wenn du einfach so rumstehst. Willst du high werden? Ich hab, was du brauchst. Jede Menge. Such dir was aus, wenn du zahlen kannst.}
{111}{}{Tschüss.}
{112}{}{Warte. Kann ich noch mal schauen?}
{113}{}{Zeig mir, was du hast.}
{114}{}{Diesmal brauche ich nichts.}
{115}{}{[Nickt, verstaut hastig seine Sachen und schaut sich um] War's das?}

#When the lab or the Black Caravan got destroyed
{120}{}{Tut mir leid, mit jedem neuen Tag gibt es weniger Ware. Such dir aus, was noch da ist. Und beeil dich, denn morgen könnte schon nichts mehr übrig sein.}
{121}{}{Was ist mit deinem Vorrat passiert?}
{122}{}{Meine Geschäftsbeziehungen sind zu Ende gegangen. Jemand hat sowohl den Lieferanten als auch den Hersteller zum Schweigen gebracht. Hör zu, du musst dich mit deiner Wahl beeilen, da kommt schon der nächste Kunde.}
{123}{}{Ja, machen wir ein Geschäft.}
{124}{}{Dann überlasse ich ihn dir. Tschüss.}

#Obtaining evidence about Sam Phillips
{130}{}{Du bist also derjenige, bei dem Phillips die Drogen kauft?}
{131}{}{[Sieht überrascht aus] Sam Phillips? Wirklich? Fällt er wieder in seine alten Gewohnheiten zurück?}
{132}{}{[Schaltet heimlich die Aufnahme auf dem Pip-Boy ein] Ist das so überraschend?}
{133}{}{Ich sehe, es überrascht dich. Das heißt, du wusstest nichts davon. Gut, das sollte ich mir merken. Tschüss.}

{134}{}{[Zuckt nachdenklich mit den Schultern] Die Leute ändern sich nicht. Sam hatte ein persönliches Drogenproblem, bis er sich an die Renovierung dieses Cafés machte. Alle dachten, er hätte mit den Drogen abgeschlossen. Aber wenn das stimmt, was du sagst, sollte ich ihn besuchen.}
{135}{}{Schon gut, ich bin eigentlich wegen der Ware hier. Zeig mir, was du hast.}
{136}{}{Sieht aus, als wüsstest du sonst nichts. Na gut, tschüss.}

#Pound
{140}{}{Woher hast du die Ware?}
{141}{}{Von zuverlässigen Lieferanten. Mehr musst du nicht wissen.}

{150}{}{Du weißt wirklich, wie man einen Kunden beruhigt. Aber mir reicht das nicht.}
{151}{}{Du lügst! Du hast keine zuverlässigen Lieferanten! Nur zweifelhafte Behauptungen.}
{152}{}{Eigentlich hast du recht. Lass uns einfach in Ruhe ein Geschäft machen.}
{153}{}{Wie auch immer, ich kaufe dir nichts ab. Tschüss.}

{154}{}{Ich lüge nicht. Meine Lieferanten sind zuverlässig.}
{155}{}{Aber heutzutage kann man nicht einfach losziehen und ein *reines* Produkt finden. Wer sollte das besser wissen als wir, oder?}
{156}{}{[Grinst] Man muss nur wissen, wo man suchen muss. Nicht alle Chemikalien auf der Welt stammen aus der Vorkriegszeit.}
{157}{}{Warte, willst du damit sagen, es gibt einen aktiven Chems-Hersteller?!}
{158}{}{Ganz genau. Und das ist alles, was du wissen musst. Bist du zufrieden? Jetzt kannst du gefahrlos ein Produkt auswählen. Es ist sauber, keine Sorge.}
{159}{}{Und trotzdem: Erzähl mir vom Hersteller. Ich muss wissen, wer dahintersteckt und wo ich ihn finden kann.}
{160}{}{[Er sieht dich finster an] Bist du von allen guten Geistern verlassen? Wer erzählt einem völlig Fremden so etwas? Außerdem weiß ich nur sehr wenig. Die Produkte werden von einem Kurier geliefert, ich war noch nie im Labor.}
{161}{}{Natürlich ... Natürlich ... Siehst du, ich interessiere mich für Chems, aber nicht als Konsument, sondern als Chemiker. Ich würde gern mit diesem Labor in Kontakt treten - vielleicht gibt es dort eine freie Stelle für mich.}
{162}{}{[Zieht skeptisch eine Augenbraue hoch] Na, sag mal, Sonderling: Was weißt du aus wissenschaftlicher Sicht über Methamphetamin?}
{163}{}{N-Methyl-alpha-methylfentanyl, ein Amphetaminderivat. Es ist eine weiße, kristalline Substanz und ein starkes Psychostimulans.}
{164}{}{Das ist eine Überraschung. Aber ich kann dir trotzdem nicht helfen. Wie gesagt, ich werde von einem Lieferkurier versorgt und war noch nie dort.}
{165}{}{Na ja ... Eine Droge. Weißes Pulver. Das wissen doch alle Junkies!}
{166}{}{Fahr zur Hölle! Wenn du ein Bulle bist, erschieße ich dich auf der Stelle.}
{167}{}{Hey, immer mit der Ruhe!}
{168}{}{Vielleicht weißt du, wie ich mit ihnen in Kontakt treten kann?}
{169}{}{[Sieht sich um und beginnt zu flüstern] Der Ort heißt the Pound. Angeblich liegt er weit von der Stadt entfernt, in der Mojave-Wüste. Ich bekomme ihre Produkte über einen Mittelsmann und verständige mich vorher per Funk mit ihm. Sein Rufzeichen lautet "Black Caravan". Das sind ein paar Typen, die sich als gewöhnliche Karawanenhändler ausgeben und mit den anderen auf dem Parkplatz stehen. Du musst nach ihnen suchen, wenn du mit the Pound in Kontakt treten willst. Slavertown hat bestimmt auch mit ihnen zu tun, aber das ist nur eine Vermutung von mir.}
{170}{}{Danke, das werde ich mir merken. Zeig mir jetzt, was die Typen dir besorgt haben. Vielleicht kaufe ich etwas.}
{171}{}{Gut, dass du dir das alles hast entlocken lassen. Jetzt wird es Zeit, dich umzubringen!}
{172}{}{Diese Information ist sehr nützlich für mich. Leb wohl.}

{173}{}{Ja, klar. Tolle Geschichte, erzähl mir mehr. Wo sind die Beweise? Wo?!}
{174}{}{Na gut, ich glaube dir. Lass uns handeln.}
{175}{}{Natürlich. Aber ich werde dir trotzdem nichts abkaufen.}
{176}{}{Deine Worte beruhigen mich. Zeig mir, was du hast.}
{177}{}{Ich verzichte. Tschüss.}
{178}{}{Natürlich ... Natürlich ... Weißt du, ich interessiere mich für Chems, nicht als Konsument, sondern als ...}
{179}{}{[Wütend] Halt die Klappe, bevor ich dich erschieße! Und jetzt verschwinde.}
{180}{}{[Angreifen]}
{181}{}{[Geh weg]}
{182}{}{Na, das reicht mir. Jetzt kommen wir zur Sache.}
{183}{}{Wie auch immer, das klingt immer noch nicht überzeugend. Ich gehe.}
{184}{}{Ich muss dir gar nichts beweisen. Brauchst du eine Dosis oder nicht?}
{185}{}{Ja, zeig mir, was du hast.}
{186}{}{Ich brauche deine verdächtige „Dosis“ nicht. Ich brauche gar nichts von dir. Ich gehe.}
{187}{}{Hast du eine Ahnung, wie viel Zeug Leute wie du mir schon verkauft haben?! All diese Dealer haben sich nie die Mühe gemacht, dich zu verstehen. Sie wissen nur, wie sie sich die Taschen fuellen, indem sie lebenden Leichen Scheiße verkaufen ...}
{188}{}{Hey, ganz ruhig, meine Kunden liegen mir am Herzen. Du kannst dich auf mich verlassen.}
{189}{}{Wirklich? Du willst mich nicht übers Ohr hauen? Na dann, mal sehen, was du hast.}
{190}{}{Lüg mich nicht an! Ich durchschaue dich. Ich gehe.}
{191}{}{Klar. Das sagen alle, aber ich werde nicht an dem sterben, was du da zusammenbraust!}
{192}{}{[Mustert dich aufmerksam] Du siehst nicht wie ein Drogenabhängiger aus. Für wen arbeitest du? Für die Bullen? Bleib mir vom Leib!}
{193}{}{[Gehen]}
{194}{}{[Mustert dich aufmerksam] Verstehe, du scheinst ein ernstes Drogenproblem zu haben. Selbst wenn ich dir gebe, was du willst, wird dich das nicht retten.}
{195}{}{Hä?}
{196}{}{Ihr Süchtigen seid alle hoffnungslose Fälle ... Obwohl ich weiß, wie ich dir helfen kann.}
{197}{}{Ich kenne Leute wie dich nur zu gut, aber ich schätze, zuhören kann nicht schaden.}
{198}{}{Du kannst mir nur helfen, wenn du mir etwas gibst, das die Entzugserscheinungen lindert. Zeig mir, was du verkaufst.}
{199}{}{Ich brauche deine Hilfe nicht. Ich komme auch ohne dich zurecht.}
{200}{}{Du kannst mir nur helfen, wenn du mir sagst, wo das Labor ist. Ich will DIE reinste Droge!}
{201}{}{Du musst den Lieferanten kontaktieren. Manchmal suchen sie Drogenabhängige. Ich glaube, dort wird es dir gefallen.}
{202}{}{Hm. Interessant. Erzähl mir mehr.}
{203}{}{Wenn ich mich doch nur ganz auf mich und meine Skepsis verlassen könnte. Du bist zu wortgewandt.}

#Pop-up phrases
{500}{}{Na, wen haben wir denn da! Komm rein, vielleicht ist etwas für dich dabei?}
{501}{}{Hey, ich hab was Süßes fürs Hirn!}
{502}{}{Ich mach dir einen Rabatt, komm her!}
{503}{}{::pfeift::}
{504}{}{Nach einem harten Tag gibt's nichts Besseres als eine Dosis. Oder?}
{505}{}{Ich hab etwas, das dich den Himmel küssen lässt!}
{506}{}{Oh ... Aus welchen Landen kommst du?}
{507}{}{Ich gebe dir Rabatt auf ALLE meine Waren.}
{508}{}{Ich weiß, wonach du suchst. Ich hab's. So viel, wie du BRAUCHST.}
{509}{}{Warum laufen, wenn du *fliegen* kannst?}
{510}{}{Ich hab das reinste Zeug der Stadt, nur damit du's weißt.}
{511}{}{Du willst fliegen? Hast du Geld? Dann bin *ich* genau der Richtige für dich.}
{512}{}{Willst du an einen Ort fliegen, an dem nur die Götter sein können? Ich helfe dir!}
{513}{}{Ich hab Zeug, Zeug und noch mehr Zeug. Reden wir.}

#Women's replics
{1158}{}{Ganz genau. Und das ist alles, was du wissen musst. Bist du zufrieden? Jetzt kannst du gefahrlos ein Produkt auswählen. Es ist sauber, keine Sorge.}
{1192}{}{[Mustert dich aufmerksam] Du siehst nicht wie ein Drogenabhängiger aus. Für wen arbeitest du? Für die Bullen? Bleib mir vom Leib!}
