{100}{}{Das ist Maurice.} 
{101}{}{Du siehst einen Mann mit Sonnenbrille. Dahinter erkennst du kaum ein Paar frecher, gerissener Augen.}
{102}{}{Bist du von hier? Falls nicht, haben wir wahrscheinlich nichts zu bereden.}
{103}{}{Leg dich bloß nicht mit mir an! Ich rieche deine Tricks schon von Weitem ...}

{110}{}{Ich hab gesehen, dass du ein Zimmer im dritten Stock hast. Gute Wahl – da ist es ruhig und gut gesichert.}
{111}{}{Bist du auch von hier?}

{112}{}{Nun ... Das kann man so sagen. Ich heiße Maurice. Freut mich, dich kennenzulernen ... [sieht sich um und beginnt zu flüstern] Hör zu, ich weiß, warum du hier bist. Ich sehe es in deinen Augen, ich weiß, was du willst. Warum wärst du sonst in diesem Kasino, hm? Wenn du Hilfe brauchst, stehe ich dir zu Diensten – ich besorge dir, weswegen du hergekommen bist. Zu einem fairen Preis natürlich.}
{113}{}{Wovon redest du?}
{114}{}{Äh, nein, so wird das nichts. [Er bringt dich in das Zimmer und öffnet seine Jacke, um dir die Ware zu zeigen] All diese Sachen helfen dir, Frau Fortuna zu reiten und sie in jeder Stellung zu beherrschen. Also, such dir was aus, wenn du das nötige Geld hast.}
{115}{}{[Handeln]}
{116}{}{Nein, danke, ich bevorzuge den ehrlichen Weg.}
{117}{}{[Lacht] Ehrlich? Na gut. Aber wenn dich deine Ehrlichkeit zum Sklaven macht, denk an mich.}
{118}{}{Äh, das werde ich.}
{119}{}{}

{120}{}{Ich wusste, dass du zurückkommen würdest. Was brauchst du heute?}
{121}{}{Nichts.}
{122}{}{Viel Glück, Freund.}
{123}{}{[Gehen]}

#Êëàä
{130}{}{Hör mal, Maurice, weißt du, wo ich ordentlich Geld verdienen kann?}
{131}{}{Nun, abgesehen vom Glücksspiel fällt mir nur irgendeine alte Geschichte über einen Schatz ein. Oder, wenn du gut darin bist, Leuten etwas vorzumachen, könntest du vielleicht einen Job im Rathaus bekommen. Die bezahlen sehr gut.}
{132}{}{Danke. Du hast etwas von einem Schatz gesagt. Erzählst du mir mehr darüber?}
{133}{}{Es ist eine alte Geschichte. Nach dem Krieg gab es einen Mann, der im Casino einen großen Gewinn abräumte ... Ich kann mich nicht mehr an seinen Namen erinnern, aber das ist auch nicht wirklich wichtig. Einer Version zufolge folgte ihm eine Gruppe Kopfgeldjäger, als er seinen Gewinn abholte und nach draußen ging. Aber der Mistkerl war schlau und schüttelte seine Verfolger ab, indem er in einer dunklen Gasse verschwand.}
{134}{}{Und?}
{135}{}{Am Morgen fand ihn einer der Kopfgeldjäger in einer Bar – er war voller Schlamm und hatte nur Kleingeld für Drinks in den Taschen. Als ihm klar wurde, dass er nicht entkommen konnte, erschoss er sich, ohne zu verraten, wo er den Schatz versteckt hatte.}
{136}{}{Also muss ich ganz Vegas durchgraben, um das Versteck zu finden.}
{137}{}{Ganz genau! Deshalb hat ihn bisher auch noch niemand gefunden. Aber es würde mich nicht überraschen, wenn er irgendwo ganz offen vergraben liegt.}
{138}{}{Hm, danke, dass du mir das erzählt hast.}
{139}{}{[Lächelt] Keine Ursache. Aber wenn du den Schatz findest, vergiss nicht, ein bisschen mit mir zu teilen, hehe.}
{140}{}{Mal sehen.}

#Îáó÷åíèå èãğå
{150}{}{Maurice, mein Freund, ich muss so schnell wie möglich Geld verdienen! Kannst du mir helfen?}
{151}{}{Helfen? Ha! Ich könnte dir einen Ghoul für den Analverkehr besorgen, aber Geld auftreiben ... Tut mir leid, aber wenn du es nicht verdienen kannst, bleiben dir nur zwei Möglichkeiten – jemanden auszurauben oder mit einer Hure namens Fortuna Liebe zu machen.}
{152}{}{Mit wem? Mit wem?}
{153}{}{Hör auf, du weißt doch, wovon ich rede. Geh an irgendeinen Spielautomaten oder sprich mit einem Croupier am Roulette-Tisch. Du hast die Chance, Millionär zu werden ... oder mehr zu verlieren, als du besitzt. Es ist immer ein Risiko, Süße. Alles, was du tun kannst, ist zu versuchen, dein Verlustrisiko zu senken.}
{154}{}{Wie?}
{155}{}{[Schnief] Lern erst mal, Spiele zu spielen. Du denkst, es geht nur um Mathematik? Oh nein. Glücksspiel ist wie jede andere Fertigkeit. Du musst die Spielsituation klar einschätzen, deine Chancen beurteilen und den Zug deines Gegners vorhersehen können. Es ist wichtig, dein gutes Gedächtnis einzusetzen und noch allerlei anderen Mist. Interessiert dich das? Oder zitterst du schon beim Anblick eines Spieltischs?}
{156}{}{Kannst du es mir beibringen?}
{157}{}{Gibt es noch einen anderen Weg? Einen einfacheren?}
{158}{}{Natürlich, aber denk daran, was ich dir über die Risiken gesagt habe! Klar, du kannst dir spezielle Karten und Würfel besorgen, aber ohne gewisse Fertigkeiten kannst du damit nichts anfangen. Oder schlimmer: Du landest in einem Leichensack.}
{159}{}{Klingt verlockend, aber ich verzichte auf diese Tricks. Mach's gut.}
{160}{}{Kann ich es dir beibringen? Verdammt, ich war der Einzige, der dieses Casino beinahe geschlagen hätte! Leider fing ich im letzten Moment an zu verlieren und stand am Ende mit leeren Händen da ... Aber Mr. Wallace wusste mein Talent zu schätzen und ließ mich im Casino bleiben, obwohl ich nicht mehr spielen durfte. Also ja – ich kann dir für 1.000 $ ein paar Dinge beibringen. Glaub mir, wenn du gut spielst, hast du das Geld schnell wieder drin.}
{161}{}{Hier ist mein letztes Geld für die Lektion! Ich zähle auf dein Talent, Maurice!}
{162}{}{[Maurice bringt dich auf sein Zimmer, und du verbringst den ganzen Tag damit, richtig Karten zu spielen. Natürlich gewann Maurice immer, aber am Ende gelang dir trotzdem ein Unentschieden.] Du bist ein guter Schüler. Lass dich von den Niederlagen nicht entmutigen. Manchmal halten sie dich auf dem Boden, wenn der Erfolg dir die Sicht vernebelt.}
{163}{}{Danke, Maurice. Das war eine wichtige Lektion.}
{164}{}{Deine Glücksspiel-Fertigkeit steigt um 10%.}

#Female character
{1102}{}{Bist du von hier? Wenn nicht, haben wir wahrscheinlich nichts zu besprechen.}
{1122}{}{Viel Glück, Freund.}
{1162}{}{[Maurice bringt dich auf sein Zimmer, und du verbringst den ganzen Tag damit, richtig Karten zu spielen. Natürlich gewann Maurice immer, aber am Ende gelang dir trotzdem ein Unentschieden.] Du bist ein guter Schüler. Lass dich von den Niederlagen nicht entmutigen. Manchmal halten sie dich auf dem Boden, wenn der Erfolg dir die Sicht vernebelt.}
