{100}{}{Du siehst Richard Pryor.}
{101}{}{Du siehst einen Komiker mit buschigem Schnurrbart und dem Gesicht eines Glücksspielers. Allein sein Blick verrät: Von ihm ist alles zu erwarten.}

#Ïîïû'êà çàãîâîğè'ü íà êàğ'å êàôå íå ïîëó÷èâ êâåñ'à
{102}{}{Raus aus meinem Haus, verdammte Paparazzi! Heute gebe ich keine Autogramme.}

#Ôğàçà ïğè ñìåğ'è
{103}{}{Neeein! Ich habe meine Tour durch Nevada noch nicht beendet!}

#Î'âå'íàÿ ğåïëèêà ïîñëå âûïîëíåíèÿ êâåñ'à íà äîñ'àâêó â êàôå
{104}{}{Wenn ich jetzt mit einem Bein auf der Bühne stehe, kann ich dem Clean City das andere in den Arsch rammen und durch den Mund wieder herausziehen. Kannst du dir vorstellen, wie das ist?!}
{105}{}{Wildes verbales Jucken, garniert mit jeder Menge vulgärer Ausdrücke, lenkt dich ständig ab. Dadurch kannst du ernsthafte Probleme bekommen.}
{106}{}{Solange Pryor bei dir ist, sinkt dein Glück um }
{107}{}{.}
{108}{}{Befreit von dem Komiker fühlst du dich unglaublich friedlich.}

#Âñ'óïè'åëüíûå ôğàçû ïğè çàãğóçêå êàğ'
{110}{}{Was zum Gecko machen wir hier?!}
{111}{}{ }
{112}{}{ }
{113}{}{ }
{114}{}{ }
{115}{}{ }

#Ïîïû'êà 'îëêàíèÿ
{140}{}{Ah, ich bin in einen Dorn getreten!}
{141}{}{Aua}
{142}{}{Such lieber nach *deinen* Eiern}
{143}{}{Ganz ruhig! Ich bin was Besonderes.}
{144}{}{Stoß fester zu. Macht mir nichts aus, wenn du verstehst, was ich meine.}
{145}{}{Deine Hände sind feucht. Willst du mir den Rücken schrubben?}

#Îïöèè ïàğ'èéöà â äèàëîãå
{150}{}{Hey, warum *wanderst* du so viel herum?.. Aha-ha! Guter Witz!}
{151}{}{Zeit aufzubrechen. Los geht's.}
{152}{}{Sag kein Wort mehr.}

{153}{}{...Und ich frage ihn: Hey, ist das hier Reno? Und er sagt...}
{154}{}{Du musst hier auf mich warten.}
{155}{}{Los geht's. Reno erwartet uns.}
{156}{}{Sag kein Wort mehr.}

#Äèàëîã â Âåãàñå
{200}{}{Fans, Fans... Du hast doch keine Paparazzi mitgebracht, oder? Gut.}
{201}{}{Also soll ich dich zur Bühne in Reno begleiten?}
{202}{}{Ich brauche dich nicht! Ich will nicht mal mit dir reden.}
{203}{}{Renos Bühne ruft nach mir, Baby! Aber du bist... ganz allein... Hatten sie keine Eskorte für dich, oder wenigstens eine Postkutsche? Na schön, na schön, ich komme schon, wenn es Zeit ist.}
{204}{}{Los geht's.}
{205}{}{Warte, ich muss mich noch auf die Abreise vorbereiten.}

{210}{}{Wie soll ich es milde ausdrücken ... Der Besitzer des Clubs ist gestorben, und jetzt bist du arbeitslos.}
{211}{}{Was zum Teufel mache ich dann hier!? [Schaut verwirrt umher] Was für ein Drecksloch! [Sieht die Obdachlosen am Fass] Hey, Leute! Wollt ihr Gesellschaft? ... [Geht zu ihnen und verschwindet in der Menge. In der Ferne ist gemeinsames Gelächter zu hören, das schließlich verstummt.]}
{212}{}{Na ja, offenbar sehen wir uns nicht wieder, Richard Pryor.}
{213}{}{Fick dich, du Stück Scheiße!}

#Îáû÷íûé äèàëîã
{250}{}{Erzähl mir von deiner Arbeit.}
{251}{}{Hör zu, ich bin witzig. Die Leute lachen über meine Witze, als wären sie ein Haufen Idioten. Ich bin dafür geboren. Aber Vegas hat mich wohl schon satt, also trete ich hier nicht mehr auf. Essen muss ich trotzdem, also hab ich beschlossen, mein Glück in Reno zu versuchen.}
{252}{}{Du klingst gerade nicht wie ein Komiker ...}
{253}{}{Na gut.}
{254}{}{Na ja ... Weißt du, mir liegt einiges schwer auf dem Herzen. Ich erzähle den Leuten etwas Wichtiges, und sie hören nicht zu. Sie denken, es sei nur ein Witz. Aber dir hören sie zu. Weil du ernst bist, obwohl du nicht viel zu sagen hast. Weißt du, was ich meine?}
{255}{}{Und was würdest du den Leuten in Reno erzählen?}
{256}{}{Wahrscheinlich denselben Mist. Mich nimmt sowieso keiner ernst. Außerdem kann ich nichts anderes. Nach all den Jahren mit dem ganzen Spaß auf großen Bühnen kann ich nicht einfach wieder so was machen wie in brahmin-Scheiße zu wühlen, weißt du, was ich meine?}

#Ñöåíà â Ğèíî

#Ôğàçû â îğèãèíàëå:
#What the fuck am I doing here!?
#Sick of hearing this shit about me not talking... Not true... Good days, bad days... But I still am a talkin motherfucker!
{300}{}{Was zum Teufel mache ich hier!?}
{301}{}{See No Evil, Hear No Evil.}
{302}{}{Allen gewidmet, die sich um mein Kokain gekümmert haben}
{303}{}{Gute Tage, schlechte Tage ... Aber ich bin immer noch ein verdammter Quasselkopf!}
{304}{}{Erinnerst du dich an diese beschissene Dürre vor 20 Jahren? Ich hab den Scheiß überlebt ...}
{305}{}{Als ich das erste Mal kam, hab ich mir vor Angst in die Hose geschissen, Alter!}
{306}{}{Und alle fragen: Was ist das?! Das ist Richard Pryor, das die Straße runterrennt!}
{307}{}{Ich dachte, das liegt an den glatten Haaren. Solange sie so sind, machen mich die Weißen fertig. Also hab ich sie abgefackelt.}
{308}{}{Lass mich den Reißverschluss zumachen, wenn ich vor Publikum auftrete.}
{309}{}{Vor 60 Jahren konntest du mit niemandem ficken, weil jedes Mädchen an einer Krankheit namens „Jungfräulichkeit“ litt.}
{310}{}{Schwarz zu sein ist cool. Denn weiß zu sein ist nicht cool.}
{311}{}{Küss meinen schwarzen Arsch!}
{312}{}{Wusstest du, dass eine Million Dollar 2204,6 Pfund wiegen?}
{313}{}{Was ist ein Kreuz auf einem Kreuz? Ein Papst auf einer Krankenschwester.}

#Female character
{1200}{}{Fans, Fans... Du hast doch keine Paparazzi mitgebracht, oder? Gut.}
{1254}{}{Na ja ... Weißt du, mir liegt einiges schwer auf dem Herzen. Ich erzähle den Leuten etwas Wichtiges, und sie hören nicht zu. Sie denken, es sei nur ein Witz. Aber dir hören sie zu. Weil du ernst bist, obwohl du nicht viel zu sagen hast. Weißt du, was ich meine?}
