{100}{}{Du siehst einen Spieler.}
{101}{}{Du siehst einen Spieler. Aufgeregt wedelt er mit den Hдnden, wдhrend die Geckos vorbeirennen.}

#Кричат во время бегов гекко
{110}{}{Los! Los!}
{111}{}{Bring mir das Geld, Gecko!}
{112}{}{Lauf, Toki!}
{113}{}{Bitte! Bitte!}
{114}{}{Verdammt!}
{115}{}{Los!}
{116}{}{Was fьr ein Rennen!}
{117}{}{Wird der hier gewinnen?!}
{118}{}{Was?! Der Rote liegt vorn?!}
{119}{}{Zu langsam!}
{120}{}{Zu schnell!}
