{100}{}{Du siehst einen Ghoul-Freak.}
{101}{}{Du siehst einen Mann mit einem Sack über dem Kopf, der seine entstellte Haut kaum bedeckt.}
{102}{}{Du solltest dich lieber nicht hier herumtreiben ...}

###################################################
#
# FLOATING PHRASES
# Author: Aleksandr Agafontsev
#
###################################################

#The problems aren't solved
{110}{}{Keine Drogen mehr?! Aber das war meine einzige Freude ...}
{111}{}{Keine Gesundheit, kein Job, keine Zukunft ...}
{112}{}{Ich würde gern sehen, wie diese Schweine in Uniform klarkommen, wenn sie selbst eine Handvoll Pillen schlucken müssten, nur um einmal pinkeln zu können ...}
{113}{}{Alle hier drin sind so hässlich ... Außer mir natürlich.}
{114}{}{Was bringt einem dieses ewige Leben, wenn man weder ins Casino noch zu den Nutten gehen kann ...}
{115}{}{Verdammte Bullen ...}
{116}{}{Sie behaupten, wir würden Drogen kochen? Die sind doch nur neidisch!}
{117}{}{Freaks? Wir? Du hättest die Typen aus Kalifornien 2077 sehen sollen ...}
{118}{}{Ich bin so schwach, dass ich mich nicht mal aufhängen kann ...}
{119}{}{Mir geht es so schlecht ...}
{120}{}{Das Leben ist eine furchtbar ungerechte Sache ...}
{121}{}{In diesem Hotel fühle ich mich, als wäre ich schon begraben.}
{122}{}{Früher konnte ich hundert Meter in zehn Sekunden laufen. Und jetzt schaffe ich es nicht mal mehr rechtzeitig aufs Klo ...}
{123}{}{Ich kann es kaum erwarten zu sterben ...}
{124}{}{Ich würde gern einschlafen und nie wieder aufwachen ...}
{125}{}{Und ich war ein Rassist! Aber jetzt sehe ich selbst aus wie ein Nigger ...}
{126}{}{Statt eines Huts ein stinkender Beutel.}
{127}{}{Hat sich mein Tod unterwegs verirrt?}
{128}{}{Jede Arbeit! Sogar brahmin Scheiße schaufeln ...}
{129}{}{Alle Glatthäute sind hässliche Bastarde ...}

#Problem solved
{150}{}{Ja! Wir kochen wieder Drogen! Äh ... ich meine – der Gerechtigkeit ist Genüge getan!}
{151}{}{Ich bin 90, aber fühle mich, als wäre ich erst 89!}
{152}{}{Jetzt fehlt nur noch eine Erlaubnis, die Huren zu besuchen. Und das Kasino!}
{153}{}{Das Leben ist schön! Und ich auch!}
{154}{}{Unser Hotel ist besser als jede Location in Vegas!}
{155}{}{Ich kann es kaum erwarten, wieder an die Arbeit zu gehen ...}
{156}{}{Zu Ehren dieses Ereignisses würde ich einen Festtagsbeutel tragen!}
{157}{}{Glatthäute und wir sind Brüder für immer!}
{158}{}{Zu Ehren dessen sollte man die Abenddosis erhöhen!}
{159}{}{Ruhm dem Glatthaut-Wanderer!}
{160}{}{Unsere Probleme wurden von einer Glatthaut gelöst? Das Leben hat sich wirklich verändert ...}
{161}{}{Das Leben ist wunderbar!}
{162}{}{Da wir hier oft Glatthäute haben, sollte ich lieber die abgepellte Haut entfernen und den Beutel sauber machen ...}
{163}{}{::pfeift eine fröhliche Melodie::}
{164}{}{Aber ich werde trotzdem noch ein letztes Mal auf die Schuhe irgendeines Bullen pissen!}
{165}{}{Wer hätte gedacht, dass ich mir den Tod herbeigewünscht habe. Jetzt liegt mein ganzes Leben vor mir!}
{166}{}{Das Leben fängt gerade erst an!}
{167}{}{Ja, ich kann nicht rennen! Aber ich kann weiter laufen als jede Glatthaut!}
{168}{}{Ich hätte ein Kind nach diesem Wanderer benannt, aber ich hatte vergessen, wie man Babys macht ...}
{169}{}{Ha-ha! Nimm das, ihr dummen Schweine in Uniform!}
