{10}{}{ }
{11}{}{ }

{100}{}{Du siehst einen Casinogast.}
{101}{}{Du siehst deinen Kunden.}

{102}{}{Was soll das sein, ein neuer Modetrend? Nimm dir den Fetzen vom Kopf, wenn du mit mir reden willst.}
{103}{}{Ich wollte mich nur entspannen. Es schien, als wäre heute ein schöner Tag dafür.}

{104}{}{Was willst du? [mustert dich von Kopf bis Fuß, bis ihm beim Anblick der Pizza in deinen Händen plötzlich etwas klar wird] Willst du mich verarschen?! Ich hab die Pizza bestellt, Gott weiß wann! Und jetzt, wo ich schon zu Abend gegessen habe, ist sie völlig nutzlos. Verschwinde, Kurier, und sag deinem Boss, er soll dich *feuern*!}
{105}{}{[Geh weg]}
{106}{}{Was willst du? [mustert dich von Kopf bis Fuß, bis ihm beim Anblick der Pizza in deinen Händen plötzlich etwas klar wird] Wo zum Teufel warst du, Kurier!? Wie lange soll ich noch warten? Noch zehn Minuten, und ich wäre verhungert. Gib mir jetzt die Pizza und verschwinde!}
{107}{}{Das macht }
{108}{}{ $, Sir.}
{109}{}{Wofür!? Für deinen lausigen Service? Zum Teufel mit dir, hier ist das Geld, gib mir einfach die Pizza. [Er wirft dir das Geld zu – etwas Kleingeld und zerknitterte Scheine]}
{110}{}{Was ist mit euch Leuten los? Vielleicht solltet ihr einfach keine Pizza mehr bestellen.}
{111}{}{Danke, Sir. Guten Appetit und einen schönen Tag! Das Café von Sam Phillips freut sich immer, Ihnen seine Türen zu öffnen. Alles Gute!}
{112}{}{[Geh weg]}
{113}{}{[Weitet die Augen] So eine dreiste Unverschämtheit hätte ich nicht erwartet!! Wo findet man in dieser Stadt nur solche Wilden! Verdammt, ich werde diesen Lieferservice nie wieder benutzen! Äh ... Verschwinde!}
{114}{}{[Starrt dich an] Du redest wie so ein Typ aus dem Fernsehen. Aber ... du redest nett. Na gut, jetzt geh. Ich mag es nicht, wenn mir Leute beim Essen zusehen.}

{150}{}{Du siehst einen der Casinogäste. Er sieht müde aus.}
{151}{}{Du siehst einen der Casinogäste. Seine Augen glänzen vor Aufregung.}
{152}{}{Du siehst einen der Casinogäste. Er bedeckt sein Gesicht.}
{153}{}{Du siehst einen der Casinogäste. Er wirkt ein wenig angetrunken.}
{154}{}{Du siehst einen der Casinogäste. Er zwinkert dir zu und geht schwankend davon.}
{155}{}{Du siehst einen der Casinogäste. Er versucht, die Aufmerksamkeit der Kellnerin zu erregen.}
{156}{}{Du siehst eine der Casinogästinnen. Sie sieht müde aus.}
{157}{}{Du siehst eine der Casinogästinnen. Ihre Augen glänzen vor Aufregung.}
{158}{}{Du siehst eine der Casinogästinnen. Sie bedeckt ihr Gesicht mit den Händen.}
{159}{}{Du siehst eine der Casinogästinnen. Sie wirkt ein wenig angetrunken.}
{160}{}{Du siehst eine der Casinogästinnen. Sie zwinkert dir zu und geht schwankend davon.}
{161}{}{Du siehst eine der Casinogästinnen. Sie versucht, die Aufmerksamkeit des Kellners zu erregen.}

#In-game messages:
{280}{}{Lady Luck, enttäusch mich nicht.}
{281}{}{Lass uns würfeln.}
{282}{}{Baby braucht ein neues Paar Schuhe ...}
{283}{}{Verdammte arme Touristen ...}
{284}{}{Verdammt! Ich lag *53* Chips vorn, aber dann ...}
{285}{}{Das ist wirklich Pech ...}
{286}{}{So nah dran!}
{287}{}{Jetzt knacke ich die Bank.}
{288}{}{Ich? Ich knacke die Bank. Sieh her.}
{289}{}{Alles war gegen mich.}
{290}{}{Lady Luck hat sich von mir abgewandt.}
{291}{}{Wird jemand zu meiner Beerdigung kommen?}
{292}{}{Die Bank hatte Erbarmen mit mir.}
{293}{}{Zwischen den Trinkgeldern und diesen riesigen Summen, die ich betrunken verprasse ...}
{294}{}{Wenn du so weiterspielst, landest du schon bald auf Golgatha ...}
{295}{}{Kellnerin, noch einen Drink!}
{296}{}{Kellner, noch einen Drink!}
{297}{}{Diese Drinks schmecken ... seltsam.}
{298}{}{Ich habe Fieber!}
{299}{}{Ich habe schon mein ganzes Geld verloren.}
{300}{}{Das Glück ist eine flatterhafte Schlampe. Die Mutter meiner besseren Hälfte übrigens auch.}
{301}{}{Na ja ...}
{302}{}{Ach, enttäusch mich nicht!}
{303}{}{Los, mein Schatz!}
{304}{}{Wohin man auch geht, überall diese verdammten Betrüger ...}
{305}{}{Na toll, noch ein Bettler.}
{306}{}{Ich habe SO ein Glück.}
{307}{}{Schlafen kann ich noch genug im Sarg.}
{308}{}{Hör mal, ich muss pinkeln. Mir ist schon ganz flau im Magen.}
{309}{}{Mann, ich muss mal die Schlange entleeren.}
{310}{}{Verdammt, hier lassen sie auch jeden rein.}
{311}{}{Komm schon, ich brauche eine Sieben!}
{312}{}{Du hast echt Charakter, Baby.}
{313}{}{Wer ist heute Abend der große Gewinner? Mikey!}
{314}{}{Nicht verlieren ... Komm schon ...}
{315}{}{Wenn wir doch nur verhandeln könnten ...}
{316}{}{Das ist SO ein verdammter Mist.}
{317}{}{Ich habe es geschafft, nur 60 Jetons zu verlieren. In den ersten fünf Minuten.}
{318}{}{Rot 23! Rot 23! Komm schon ... Rot 23 ...}
{319}{}{50 Jetons auf Schwarz 15 ...}
{320}{}{Die Kugel kreist im Roulette ... Rate mal, auf welchem Feld sie landet ...}

#Win
{321}{}{Heh!}
{322}{}{Ha! Jetzt gehört die Bank mir!}
{323}{}{Hey, ich habe tatsächlich gewonnen? Verdammt ja!}
{324}{}{Jetzt gehört es MIR! Ha-ha-ha!}
{325}{}{Verdammte Ziegen, ich habe gewonnen!}
{326}{}{Und sie haben gesagt, das wäre Betrug!}
{327}{}{::springt vor Freude::}
{328}{}{::klatscht::}
{329}{}{Ich habe gewonnen!!!}

#Lost
{330}{}{Verdammt!}
{331}{}{Verdammtes Pech}
{332}{}{Ich hab *schon wieder* verloren!}
{333}{}{Schon gut, ich habe noch etwas Kleingeld.}
{334}{}{Verdammt, gewinne ich es zurück?}
{335}{}{Ich zerreiße diesen Mistkerl in Stücke!}
{336}{}{Ich habe verloren ... Das ist echt mies ...}
{337}{}{Bin ich ein Versager?}
{338}{}{Es ist Zeit aufzuhören ...}
{339}{}{Ich staune, dass ich so schlecht bin.}
{340}{}{Bald bleibt mir nichts mehr.}