{100}{}{Du siehst einen Bewohner.}
{101}{}{Du siehst einen Einheimischen. Er sieht etwas kränklich aus.}
{102}{}{Oh, mir ist so übel ... Warum gibt es hier keinen Arzt?}

{103}{}{Die Symptome dieses Patienten sind etwas verwirrend. Du hast nicht genug Erfahrung, um sie zu verstehen.}
{104}{}{So schwierig ist es, hm?}
{105}{}{Dieser Mann scheint unter einer Vergiftung zu leiden.}
{106}{}{Hey, Doc, kann man das heilen?}
{107}{}{Danke, Doc.}

{108}{}{Du hast bei diesem Patienten bereits eine Drogenvergiftung diagnostiziert.}

{110}{}{Bist du wirklich Arzt? Kannst du mich heilen?}
{111}{}{Zuerst muss ich wissen, welche Droge du genommen hast.}
{112}{}{Solange ich keine Lösung gefunden habe, wirst du wohl damit leben müssen.}
{113}{}{Drogen?! Woher denn?! In letzter Zeit habe ich nur das lokale Essen aus der Bar unten gegessen. Und natürlich gesoffen. Haben die beschlossen, ihre Kunden zu vergiften? Das ist ziemlich seltsam.}
{114}{}{Okay, ich verstehe. Es klingt, als hätte jemand Drogen in deinen Alkohol gemischt, damit du abhängig wirst. Das lässt sich nur mit anderen Drogen ausgleichen – oder durch völligen Entzug, den du nicht leicht durchstehen wirst.}
{115}{}{Hm, ein schwieriger Fall. Es gibt keine andere Möglichkeit, als andere Drogen zu nehmen. Aber im Moment fällt mir nichts Konkretes ein. Wenn ich eine Lösung finde, komme ich dich besuchen.}

{116}{}{Also wurde ich unter Drogen gesetzt ... Wie konnte das passieren? Und ... Welche Drogen soll ich nehmen?}
{117}{}{Psycho. Ja, ich will es nicht verschweigen: Du kannst abhängig werden, aber vorher beseitigt es alle aktuellen negativen Effekte.}
{118}{}{Antiraucher würde die Wirkung der Droge ausgleichen und das Zittern lindern.}
{119}{}{Du solltest versuchen, den Entzug durchzustehen. Ich sage dir das als Arzt. Drogen sind zu gefährlich, weil du abhängig werden kannst. Oder Schlimmeres.}
{120}{}{Wirklich? Verdammt, ich würde mein ganzes Geld für die Dosis hergeben, wenn das helfen würde! Aber wo bekomme ich sie? Doc, du hast nicht zufällig eine dabei, oder?}
{121}{}{Klar. Aber nicht so schnell, erst das Geld. $500 reichen.}
{122}{}{Hab ich. Und behalt dein Geld.}
{123}{}{Hab ich noch nicht.}
{124}{}{Na ja, danke. [nimmt eine Dosis] Wow ... Wirklich ... Mir geht's schon viel besser ... Mein ganzer Körper gehorcht mir wieder ...}
{125}{}{Ja. Gute Besserung.}

{126}{}{Klar. Aber nicht so schnell, erst das Geld. $200 reichen.}
{127}{}{Verdammt, das wird eine heiße Nacht ... Aber wenn der Arzt das sagt, mach ich's. Ich versuche, es durchzustehen.}
{128}{}{Gut. Leg dir ein feuchtes Tuch auf die Stirn, forme einen Knebel und steck ihn dir in den Mund, damit du dir nicht die Zähne beschädigst. Und außerdem ... Gute Besserung.}
