{100}{}{Du siehst einen Wachmann.}
{101}{}{Du siehst den persönlichen Leibwächter des Casinobesitzers.}
{102}{}{Komm rein.}

{110}{}{Mr. Wallace ist beschäftigt. Worum geht es?}
{111}{}{Ich muss mit ihm reden. Ich ... Ähm ... suche Arbeit.}
{112}{}{Beschäftigt? Na schön. Ich komme später wieder.}
{113}{}{Darum kümmert er sich nicht.}
{114}{}{ICH VERLANGE ES! Lass mich rein!}
{115}{}{Na schön. Dann gehe ich eben.}
{116}{}{Ich sagte doch ... Entschuldigen Sie, Sir? [the guard listens to something through the door] Okay, Mr. Wallace, ich werfe ihn raus. [talks to you] Mr. Wallace braucht keine Laien wie dich ... Verschwinde, bevor ich dich aus dem Fenster werfe!}
{117}{}{Ich komme schon noch zu deinem Boss! Wage es ja nicht, mich nicht zu ihm zu lassen!!!}
{118}{}{Okay, ich beruhige mich und gehe.}
{119}{}{Ich sagte doch ... Entschuldigen Sie, Sir? [the guard listens to something through the door] Okay, Mr. Wallace. [talks to you] Diesmal kannst du reinkommen ... Hmm ... [contemptuously looks over you from head to toe]}
{120}{}{Endlich.}
{121}{}{Waffe weg! Sofort!}
{122}{}{[Nimm die Waffe aus deinen Händen]}
{123}{}{Auf keinen Fall!}
{124}{}{Mr. Wallace ist nicht hier. Niemand weiß, wann er zurückkommt.}
{125}{}{Stimmt.}

{126}{}{Sam Riley glaubt das nicht.}
{127}{}{Riley? Dieser Idiot hält sich jetzt für Mr. Wallaces Sekretär?}
{128}{}{Ja, er hat eindeutig einen kleinen Größenwahn.}
{129}{}{[The guard listens to something through the door] Okay, Mr. Wallace. [talks to you] Diesmal kannst du reinkommen ... Hmm ... [carefully and suspiciously looks at you]}
{130}{}{David, dein Wachmann im Casino, hat etwas anderes gesagt.}
{131}{}{David? Okay, das reicht. [the guard goes inside, then comes back and speaks to you] Mr. Wallace kann dich jetzt empfangen.}
{132}{}{Danke.}

{133}{}{Vielleicht hilft Maxsons Empfehlung?}
{134}{}{Maxson? Hm, der Boss hört in letzter Zeit auf ihn. Na gut, warten Sie hier. [Der Wachmann geht hinein, kommt zurück und spricht mit Ihnen.] Mr. Wallace kann Sie jetzt empfangen.}
{135}{}{Danke.}

#Female character
{1116}{}{Ich sagte doch ... Wie bitte, Sir? [Der Wachmann lauscht an der Tür.] In Ordnung, Mr. Wallace, ich werfe sie raus. [Spricht mit Ihnen.] Mr. Wallace braucht keine Mädchen wie Sie ... Verschwinden Sie, bevor ich Sie aus dem Fenster werfe!}
