{100}{}{Du siehst einen Aufseher.}
{101}{}{Du siehst den Vault City-Wartungsaufseher.}
{102}{}{Was hat Joshua diesmal verbockt?}
{103}{}{Bürger? Bitte lenken Sie Joshua nicht ab, er hat einen engen Zeitplan.}
{104}{}{Was habe ich nur getan ...}
{105}{}{Versuch das nicht noch einmal!}
{106}{}{*Fehler bei der Skriptausführung*}

{110}{}{Hallo, }
{111}{}{. Wollten Sie etwas?}
{112}{}{Was können Sie mir über Joshua erzählen?}
{113}{}{Wussten Sie, dass Joshua einen der Aufklärungsroboter verloren hat?}
{114}{}{Könnte ich Ihren Computer benutzen?}
{115}{}{Erzählen Sie mir von Ihrer Abteilung.}
{116}{}{Ich habe diese Information aus dem nahegelegenen Atomkraftwerk. Was können Sie mir darüber sagen?}
{117}{}{Keine Sorge.}

{120}{}{Aber natürlich. Wir warten die gesamte Technologie der Stadt, von einfachen Lampen bis hin zu Computern, Terminals und Robotern.}
{121}{}{Ich habe die Lampe repariert, mit der Ihr Mann Probleme hatte.}
{122}{}{Oh, äh ... Ja, ich habe davon gehört. Erfahrene Arbeiter sind heutzutage schwer zu finden, weißt du? Na ja, danke für die Hilfe, }
{123}{}{.}
{124}{}{Auf keinen Fall! Die Informationen auf unseren Servern können für gewöhnliche Bürger gefährlich sein! Der Aufseher hat sie als geheim eingestuft. Stell einen Antrag beim Informationsbüro, dann entscheiden sie, was du sehen darfst und was nicht.}
{125}{}{Das reicht.}
{126}{}{*Noch* einer? Nein, ich glaube nicht. Wenn er das getan hätte, würde er es mir sagen.}
{127}{}{Hier ist die Holodisk des vermissten Roboters. Glaubst du mir jetzt?}
{128}{}{[Seufzt] Er tut mir leid, wirklich. Er hat schon genug am Hals. Aber er hat bereits zwei Roboter verloren, und damit steht er auf dünnem Eis. Wir brauchen diese Roboter für die Arbeit in gefährlichen Zonen, und sie sind nicht leicht zu ersetzen. Joshua hat schon mehrere Verwarnungen erhalten. Wenn man ihm nicht trauen kann, muss er isoliert werden.}
{129}{}{Das ist ein bisschen hart, findest du nicht?}
{130}{}{Nein, finde ich nicht. Regeln sind Regeln. Wenn wir die Gesetze, die vom Komitee und dem Aufseher erlassen wurden, nicht durchsetzen können, herrscht Chaos in der Stadt.}
{131}{}{Joshua hat mich angelogen? Schluss mit Samthandschuhen. Ich lasse das Komitee Joshua in die Isolationsabteilung der Korrekturanstalt stecken.}
{132}{}{Ganz genau! Das hat er völlig verdient!}
{133}{}{Wenn du meinst.}
{134}{}{Danke, dass du mir das gesagt hast, }
{135}{}{! Du hast das Richtige getan und dieses Ungeziefer entlarvt! Weiter so. Ach, und es lebe Vault City!}
{136}{}{Natürlich.}

#Ğàäèî (â 1.00 íå èñïîëüçóåòñÿ)
{140}{}{Hm, interessant. Das sieht nach einer Liste nahegelegener Radiosender und ihrer Sendeparameter aus. Vermutlich können wir sie aber nicht empfangen.}
{141}{}{Wo befinden sich diese Sender?}
{142}{}{Äh ... Ich fürchte, das ist geheim ...}
{143}{}{Dann kriegst du das verdammt noch mal nicht!}
{144}{}{Was?! Das würdest du nicht ... Wenn ich dem Aufseher erzähle, wie die Ödnis dich verändert hat ...}
{145}{}{Was? Es ist doch nur eine einfache Bitte. Aber ... ich glaube, ich lasse dich lieber in Ruhe, nur für den Fall.}
{146}{}{... dann erzähle ich ihm, wie du Joshua in den Wahnsinn getrieben hast. Na, wie klingt das?}
{147}{}{Tja, schade. Ich glaube, ich gehe dann mal.}
{148}{}{Ich hätte nie gedacht, so etwas von einem unserer eigenen Bürger zu hören. Ist es wirklich das, was das Ödland aus einem Mann macht? Na gut, ich widerspreche nicht, wenn du zu *so etwas* fähig bist.}
{149}{}{Perfekt. Dann gehen wir getrennte Wege.}
{150}{}{Ich habe die Informationen mit unseren eigenen Daten abgeglichen. Es sieht so aus, als lägen nur zwei dieser Orte in der Nähe. Einer ist das Kernkraftwerk im Norden, der andere liegt ein paar Tagesreisen südöstlich. Hier, ich markiere ihn auf deiner Karte.}
{151}{}{Du hast von einem neuen Ort im Südosten erfahren}
{152}{}{Hey, das ist Cheyennes Gebiet! Interessant ...}
{153}{}{Damit habe ich wenigstens etwas zu tun ...}

#Ïî÷èíêà ïîåçäà
{160}{}{Kannst du helfen, diesen Bordcomputer zu reparieren?}
{161}{}{Ich kann nichts für dich tun, solange deine Bürgerschaft ausgesetzt ist. Ich brauche eine Genehmigung von Peter Graves. Wenn er sein Okay gibt, tue ich mein Bestes, um dir zu helfen.}
{162}{}{Verstanden.}
{163}{}{Klar. Sergeant Graves hat zugestimmt. Lass mich einen Blick darauf werfen.}
{164}{}{Hier, bitte.}
{165}{}{Eigentlich versuche ich lieber, ihn selbst zu reparieren.}
{166}{}{Du hast einen einfachen Weg gefunden, den Zug zu reparieren.}

#Òàéìåğíîå ñîáûòèå
{200}{}{Joshua! Komm her!}
{201}{}{Du Mistkerl! Du hast mich verpfiffen!}
{202}{}{Zu spät.}
{203}{}{Zum Teufel damit! Du kriegst mich nicht!}
{204}{}{Josh! Halt!!!}
{205}{}{Halt, Bürger!}
{206}{}{Komm zurück, Bürger!}
{207}{}{Joshua hat die Stadt niedergeschlagen verlassen. Du bist sicher, dass du ihn nie wiedersehen wirst.}

#Female character
{1103}{}{Bürger? Bitte lenken Sie Joshua nicht ab, er hat einen engen Zeitplan.}
{1121}{}{Ich habe die Lampe repariert, mit der Ihr Mann Probleme hatte.}
{1134}{}{Danke, dass du mir das gesagt hast, Bürger.}
{1148}{}{Ich hätte nie gedacht, so etwas von einer unserer eigenen Bürgerinnen zu hören. Ist es wirklich das, was das Ödland aus einer Frau macht? Na gut, ich widerspreche nicht, wenn du zu *so etwas* fähig bist.}
{1201}{}{Du Miststück! Du hast mich verpfiffen!}
