{100}{}{Du siehst Orris.}
{101}{}{Der Kerl sieht nicht gerade freundlich aus. Aber man muss sagen: Benehmen, Frisur und Lederjacke lassen ihn ziemlich stilvoll wirken.}
{102}{}{Komm näher ... Zeit zu sterben!}

{110}{}{Worum geht's?}
{111}{}{Nichts.}
{112}{}{Ich bin geschäftlich hier. Was machst du hier?}
{113}{}{Geschäftlich ... Ich bin auch geschäftlich hier. Und das geht dich nichts an.}
{114}{}{Also bist du derjenige, dem der Dieb Kevin in der Clean City etwas schuldet?}
{115}{}{Hä? Nie von ihm gehört.}
{116}{}{Er wurde auf frischer Tat ertappt und hat alles ausgeplaudert.}

{117}{}{Verdammte Memme ... Ich weiß nicht, warum du dich für den Jungen interessierst. Vielleicht aus Mitleid oder aus einem anderen Grund. Aber eins solltest du wissen: Er war schon lange ein Dieb, bevor ich aufgetaucht bin.}
{118}{}{Hmm. Sag mir, wie ist es dazu gekommen, dass er bei dir Schulden hat?}
{119}{}{Irgendwie glaube ich nicht, dass du das tust, weil du ihn magst.}
{120}{}{Machen wir's kurz: Wie viel schuldet er dir?}
{121}{}{Erzähl mir von deiner Gang.}
{122}{}{Ich muss los. Tschüss.}

{123}{}{Seine Eltern sind vor einiger Zeit gestorben. Nur seine ältere Schwester blieb übrig. Ich wollte ihr ehrlich helfen. Ich habe ihre Behandlung bezahlt, aber am Ende ist auch sie gestorben. Der Junge hat eine Weile von meinem Geld gelebt. Ich habe mich um ihn gekümmert und ihn die ganze Zeit unterstützt. Aber jetzt ist es an der Zeit, dass er auch mal etwas zurückgibt.}
{124}{}{Nehmen wir erst mal an, ich wäre Kevins Bruder: Ich kümmere mich um ihn, füttere ihn und habe seine Schwester behandeln lassen. Was willst du noch?}
{125}{}{[Lacht] Die Zeit vergeht, die Schulden wachsen. Das ist eine Menge Geld. Aber hör zu: Wenn du ihm unbedingt helfen willst, können wir einen Deal machen. Bring mir eine Laserpistole, ein Polizeimodell. Das ist ein teures Spielzeug, das gibt's nur in der Clean City. Schaffst du das? Wenn ja, betrachten wir Kevins Schulden als beglichen.}
{126}{}{Die Kings? Nun, wir sind ziemlich berühmt. In unserer Gang gibt es viele üble Typen, und wir sind überall in der Stadt. Ich rate dir, uns nicht in die Quere zu kommen. Wenn die Polizei nicht wäre, hätten wir ganz Vegas längst unter Kontrolle.}

{127}{}{Genau. Du hast den Jungen reingelegt, damit er sich schuldig fühlt. Und er erwies sich als guter Taschendieb. Und jetzt willst du ihn endlos „melken“.}
{128}{}{[Überrascht] Ich rieche Diebe schon aus einer Meile Entfernung. Und ich habe TALENT in Kevin gesehen. Und ich sehe, dass du selbst gar nicht so übel bist. Aber der Platz in Vegas ist besetzt. Also halt dich von meinem Revier fern.}

{129}{}{Es hat sich gerade ergeben, dass ich diese Pistole habe. Hier, nimm sie. Sind wir fertig?}
{130}{}{Ich habe es geschafft, die Pistole zu besorgen. Hier, nimm sie. Sind wir jetzt fertig?}
{131}{}{[Lächelt und untersucht die Pistole] Schulden? Es gab keine Schulden. Ich habe den Jungen ausgetrickst, weil ich schon damals wusste, dass er ein großartiger Taschendieb werden würde. Aber bei seiner Schwester war ich ehrlich. Wir waren zusammen. Und sie lag mir wirklich am Herzen. Ich hatte nur nicht genug Zeit, um ... Hör zu. Der Junge ist jetzt frei. Sag ihm einfach, er soll sich von den Außenbezirken von Vegas fernhalten.}
{132}{}{Was meinst du?}
{133}{}{Denk nach. Was wird er jetzt tun? Er stand unter meinem Schutz, eine ganze Gang hält mir den Rücken frei. Wenigstens hatte er einen Lebenssinn und ein regelmäßiges Einkommen. Und jetzt? Keine Ahnung. Er wird auf der Straße sterben – dann wirst du dich an mich erinnern.}
{134}{}{Darauf kannst du lange warten!}
{135}{}{Hmm. Vielleicht.}
{136}{}{Na gut.}

#Çàêëþ÷åííûé
{150}{}{Dein Freund Murphy sitzt im Gefängnis. Er bittet dich um Hilfe.}
{151}{}{Murphy ... Was hat dieser Schwachkopf diesmal angestellt?}
{152}{}{Die Bullen sagen, er hätte Geld gestohlen, aber die Geschichte klingt ziemlich faul.}

{153}{}{Und du? Warum rennst du für jemand anderen herum? Was hast du davon?}
{154}{}{Na ja, Murphy meinte, ich würde eine Belohnung bekommen ...}
{155}{}{So bin ich eben. Ich helfe gern Leuten.}
{156}{}{Es fällt mir schwer, Leuten Nein zu sagen. Sonst verliere ich den Sinn und das Selbstwertgefühl im Leben.}
{157}{}{Ha! Ich werde dir gar nichts zahlen. Wenn du mir jetzt einen Gefallen tust und mir hilfst, Murphy in den Griff zu bekommen, DANN können wir über eine Belohnung reden.}
{158}{}{Ich weiß nicht, wovon zur Hölle du redest. In Vegas macht niemand etwas ohne eigenen Vorteil. Du tust etwas für mich, ich tue etwas für dich. Verstanden? Vielleicht können wir also einen Deal machen.}
{159}{}{Du bist ein ziemlich eingebildeter Typ. Normalerweise mag ich solche Leute ... bis sie mir in die Quere kommen. Aber wir finden sicher gemeinsame Interessen. Willst du mein Angebot hören?}
{160}{}{Was hast du vor?}

{161}{}{Murphy ist gefährlich. Es war toll, mit ihm zusammenzuarbeiten, klar. Wir kannten uns, seit wir Kinder waren ... Aber wenn er einknickt und der Polizei all unsere Geheimnisse verrät, müssen wir die Stadt verlassen.}
{162}{}{Ehrlich gesagt ist es am einfachsten, ihn umzubringen.}
{163}{}{Ich bringe niemanden um, das ist nicht so mein Ding.}
{164}{}{Moment, das ist nicht mein Problem. Mein Job ist es, Murphys Nachricht zu überbringen. Den Rest musst du selbst herausfinden.}

{165}{}{Du musst echt hartgesotten sein, um so etwas zu sagen. Wie wär's mit einem Deal? Wenn du Murphy umlegst, bevor er uns verpfeift, werde ich versuchen, dir im Gegenzug einen Gefallen zu tun. Abgemacht?}
{166}{}{Was auch immer du sagst, ich kann dich nicht dazu zwingen. Aber wenn du einen Weg findest, Murphy aus der Patsche zu helfen, bekommst du, was dir zusteht. Abgemacht?}
{167}{}{Ja ... Klar ... Du bist nutzlos. Hau ab! Aber falls du es dir anders überlegst, überleg dir, wie du diesen Dreckskerl loswirst.}
{168}{}{Wie soll ich das in einem bewachten Gebiet voller Leute anstellen?}
{169}{}{So wie du aussiehst, kannst du nicht bezahlen. Was ist der Haken?}
{170}{}{Ich werde darüber nachdenken.}
{171}{}{Ich war einmal im Knast, als ich noch ein Kind war. Ich weiß also, dass die Gefangenen ihr Wasser nicht aus dem normalen Hahn bekommen, sondern aus einem anderen Kanister. Wenn du das Wasser vergiftest, sterben alle in den Zellen. Keine ideale Lösung, aber besser, als es mit einem Gebäude voller Cops aufzunehmen. Vielleicht siehst du das anders. Ich weiß nicht, was ich von dir erwarten soll.}
{172}{}{Ich habe die richtigen Kontakte, um an Militärdrogen zu kommen. Psycho, Buffout, so was in der Art. Ich werde überall suchen und sie bekommen, koste es, was es wolle.}
{173}{}{Was kannst du mir als Gegenleistung bieten, wenn ich das Problem mit Murphy löse?}
{174}{}{[Gehen]}
{175}{}{Hast du die Neuigkeiten gehört? Murphy ist dem Knast entkommen. Jetzt ist er frei und glücklich.}

{180}{}{Dein Wunsch ist erfuellt – Murphy ist tot.}
{181}{}{Du hast es wirklich getan?! Verdammt, du bist gefährlich ... Ich habe dir eine Bezahlung versprochen. Ich habe Kontakte und kann an Militärdrogen kommen. Interesse? Psycho, Buffout, Mentats – sag einfach Bescheid, ich kümmere mich darum.}
{182}{}{[2 Psycho]}
{183}{}{[2 Buffout]}
{184}{}{[2 Mentats]}
{185}{}{[3 Stimpaks]}
{186}{}{Hier, nimm alles, was du brauchst. Und erzähl niemandem davon. Besonders nicht in Clean City. Sonst finden dich unsere Jungs und tun dir dasselbe an wie Murphy.}
{187}{}{Kein Problem, Freund. Keine Sorge.}
{188}{}{Bedroh mich bloß nicht. Denk an deine Zukunft.}
{189}{}{Das heißt, Warten hat keinen Sinn. Fangen wir gleich an! [Angreifen]}

#Female character
{1153}{}{Und du? Warum rennst du für jemand anderen herum? Was hast du davon?}
{1186}{}{Hier, nimm alles, was du brauchst. Und erzähl niemandem davon. Besonders nicht in Clean City. Sonst finden dich unsere Jungs und tun dir dasselbe an wie Murphy.}
