#Îïèñàíèÿ
{100}{}{Du siehst einen Fremden.}
{101}{}{Du siehst Maxson.}
{102}{}{Du siehst einen Fremden. Er kommt dir irgendwie bekannt vor. Er erinnert dich ganz eindeutig an jemanden.}
{103}{}{Das ist Glatzkopf Maxson aus der Gang von Big Louie! Ganz sicher!}

{104}{}{Big Louies schmutziges Geschäft ist erledigt. Du erhältst 1000 Erfahrungspunkte.}
{105}{}{Du hast Maxson gefunden. Also hat er sich nach New Reno hierhin verzogen!}

#Äèàëîã êîãäà ÃÃ ÍÅ ïîìîã åìó áåæàòü èç Ğèíî
{110}{}{Hä? Was? [sieht dich an und wendet sich dann schnell ab] Ich verkehre nicht mit Kunden, tut mir leid. Alle Fragen an die Administratoren.}
{111}{}{Hä? Was? [sieht dich an und wendet sich dann schnell ab] Na gut, alle Fragen an die Administratoren. Und ich bitte dich, mein Büro zu verlassen.}
{112}{}{Wenn du kein Administrator bist, wer bist du dann?}
{113}{}{Na gut, ich lasse dich in Ruhe.}

{114}{}{Ich arbeite nicht mit Kunden in diesem ... [Er sieht dich an und fasst sich plötzlich wieder] ... Verdammt! Hast du mich nicht gehört? Soll ich den Sicherheitsdienst rufen? Ich wiederhole: Ich rede nicht mit Kunden. Verlass mein Büro.}
{115}{}{Ich arbeite nicht mit Kunden in diesem ... [Er sieht dich an und fasst sich plötzlich wieder] ... Verdammt! Hast du mich nicht gehört? Soll ich den Sicherheitsdienst rufen? Ich wiederhole: Ich rede nicht mit Kunden. Lass mich in Ruhe.}
{116}{}{Warte, warum reagierst du so? Was ist das Problem?}
{117}{}{Na gut, na gut, ich lasse dich in Ruhe.}
{118}{}{Na gut, bringen wir's hinter uns! Hier und jetzt! Genau das willst du doch, oder?}
{119}{}{Na schön, mach dich bereit, Abschaum! Du hast es so gewollt! [attack]}
{120}{}{Nein, ich will keinen Ärger. Ich gehe ganz friedlich.}

{121}{}{Warte, ich erinnere mich an dich ...}
{122}{}{Was, endlich erkannt? Ja, ich bin's! Früher ein dreckiger Raider aus einer Bande paranoider Bastarde, aber jetzt ein völlig anderer Mensch – ein angesehener Bürger mit einem prestigeträchtigen Job im Zentrum von Vegas. Ist das nicht erstaunlich?}
{123}{}{Aber ... Wie?!}
{124}{}{Ist doch egal. Zeit zu bezahlen, Glatzkopf. Stirb!}
{125}{}{Das Können des örtlichen Chirurgen, die Gebühren meines neuen Bosses und meine persönliche Fähigkeit, Wunder zu vollbringen. Jetzt bin ich ein anderer Mensch. Lass mich in Ruhe, sonst kommst du aus diesem Kasino nicht mehr raus.}
{126}{}{Denkst du, ich hab Angst? Mal sehen, was du draufhast! [attack]}
{127}{}{Na schön, Maxson, ich lasse dich in Ruhe. Beruhig dich.}

#Ïëàâàşùèå ôğàçû ïğè ïîïûòêå çàãîâîğèòü ïîñëå òîãî, êàê ÃÃ åãî ğàñïîçíàë
{130}{}{Du legst es drauf an!}
{131}{}{Leute! Hier legt es jemand drauf an!}
{132}{}{Hey, Leute! Schafft ihn raus!}
{133}{}{Halt dich von mir fern, verstanden?!}
{134}{}{Was?! Du legst es schon wieder drauf an?!}
{135}{}{Du willst wohl eine Kugel abkriegen, was?! Na schön!}

#Äèàëîã êîãäà ÃÃ ïîìîã åìó áåæàòü èç Ğèíî
{150}{}{Ich arbeite nicht mit Kunden in diesem ... [He looks and you suddenly pulls himself together] ... Verdammt! Sieh an, wer da ist! Ich hätte nicht erwartet, meine Freunde in diesem Teil Nevadas zu treffen. Was machst du hier, du verdammter Gecko?!}
{151}{}{Maxson ... Du hast es tatsächlich bis nach Vegas geschafft!}
{152}{}{Ja, ich bin's. Früher ein dreckiger Raider aus einer Bande paranoider Bastarde, aber jetzt ein völlig anderer Mensch – ein angesehener Bürger mit einem prestigeträchtigen Job im Zentrum von Vegas. Ist das nicht erstaunlich?}
{153}{}{Wie hast du dein Aussehen verändert?}
{154}{}{Wie bist du hierhergekommen?}
{155}{}{Arbeitest du jetzt für das Kasino?}
{156}{}{Schön, dich zu sehen, aber ich muss los.}
{157}{}{Das Können des örtlichen Chirurgen, die Gebühren meines neuen Bosses und meine persönliche Fähigkeit, Wunder zu vollbringen. Ich habe meine Frisur geändert und mir die Nase ein wenig richten lassen. Das hat gereicht, damit mich niemand aus meiner Vergangenheit wiedererkennt.}
{158}{}{Was für ein Chirurg?}
{159}{}{Wer ist jetzt dein Boss?}
{160}{}{Mit einer Postkutsche, natürlich. Das ist der einzige sichere Weg, den Great Nevada-Ring zu durchqueren.}
{161}{}{Nicht gerade fürs Casino, würde ich sagen. Für Hal Wallace persönlich. Frag nicht, sonst muss ich dich umbringen. Nur Spaß.}
{162}{}{Rob Reiner. Er sitzt unten im Untergrund. Ich habe keine Ahnung, wie man ihn kontaktieren kann. Nachts wurde ich mit verbundenen Augen in sein Labor gebracht. Und nach der Operation wurde ich betäubt.}
{163}{}{Hal Wallace, wer sonst? Ihm gehört das Casino, und er hat ... noch ein paar andere Geschäfte in der Stadt. Ein sehr mächtiger Mann, mit dem du besser befreundet bleibst, glaub mir.}
{164}{}{Bis vor Kurzem war es Hal Wallace ... Aber seine Assistenten sind noch im Casino, also läuft es auch ohne ihn weiter.}
{165}{}{Ich will auch für ihn arbeiten! Kannst du mich empfehlen?}
{166}{}{Hmm ... Ich weiß nicht, wie viel mein Wort bei meinem Boss gilt, aber ich kann es versuchen. Sprich mit seinem Leibwächter und sag ihm, Maxon schickt dich. Vielleicht hört er dir zu.}
{167}{}{Danke, Maxson.}

{168}{}{Na, alter Freund? Wie geht's dir?}
{169}{}{Hast du die Neuigkeiten über big Louie gehört?}
{170}{}{Dass er die Gang verlassen hat und jetzt im „Hard Rock“ auftritt? Ja, hab ich gehört. Ich werde wohl eine Weile im Clean City bleiben müssen.}
{171}{}{Bist du nicht überrascht?}
{172}{}{Ehrlich? Ich wusste, dass es so kommen würde. Er wurde gezwungen, ein Raider zu werden, aber er hat immer davon geträumt, Musiker zu sein.}

#Female character
{1130}{}{Du legst es drauf an!}
{1131}{}{Leute! Hier legt es jemand drauf an!}
{1132}{}{Hey, Leute! Bringt sie nach draußen!}
{1133}{}{Halt dich von mir fern, verstanden?!}
{1134}{}{Was?! Du legst es schon wieder drauf an?!}
{1135}{}{Du willst wohl eine Kugel abkriegen, was?! Na schön!}
{1168}{}{Na, Mädel? Wie geht's dir?}
