{100}{}{Du siehst einen Angestellten des Rathauses.}
{101}{}{Einer der Angestellten des Rathauses.}
{102}{}{Mit solchen Angelegenheiten befasse ich mich nicht.}
{103}{}{Wenn du Beschwerden hast, wende dich an den Türknauf da drüben.}

#Ñëó÷àéíûå ïëàâàşùèå ôğàçû
{110}{}{Die Bleistifte sind schon wieder stumpf.}
{111}{}{Kommt der Gehaltsscheck bald?}
{112}{}{Wenn ich das nächste Mal bezahlt werde, kaufe ich mir eine kugelsichere Weste.}
{113}{}{Gibt es etwas, das ich lesen könnte? Oh, die Steuererklärung!}
{114}{}{Langweilig.}
{115}{}{Bei all diesen Daten ...}
{116}{}{Das ist nicht meine Aufgabe.}
{117}{}{So viel Geld werde ich nie verdienen.}
{118}{}{Berichte, Berichte, Berichte ...}
{119}{}{Wen soll ich anschreien?}
{120}{}{Nicht so vielversprechend, wie es schien.}
{121}{}{Noch eine dumme Idee.}
{122}{}{Schrott!}
{123}{}{Noch eine blöde Antwort.}
{124}{}{Wann ist die Besprechung zur Planung?}
{125}{}{Wann ist Mittagspause?}
{126}{}{Wann gibt's Abendessen?}
{127}{}{Ich will schlafen.}
{128}{}{Ich muss mich ausruhen.}
{129}{}{Meine Augen sind müde.}
{130}{}{Das alles lesen? Kündigt mich doch einfach.}
{131}{}{Bitte, kündigt mich einfach nicht.}
