
{100}{}{Du siehst Damien Clark.}
{101}{}{Du siehst einen Archivar. Er ist wahrscheinlich der unauffälligste Angestellte des Rathauses.}
{102}{}{Ich habe meine ... verloren. Obwohl dich das wohl nicht interessiert.}

#Ñëó÷àéíûå ïëàâàþùèå ôðàçêè
{110}{}{Schon wieder meinen Bleistift zerbrochen ...}
{111}{}{Wann gibt's Gehalt?}
{112}{}{Mit dem nächsten Gehalt kaufe ich mir eine kugelsichere Weste.}
{113}{}{Was soll ich lesen? Oh, die Steuererklärung!}
{114}{}{Langweilig.}
{115}{}{Solche Daten ...}
{116}{}{Na, frag mich nicht.}
{117}{}{So viel werde ich nie verdienen.}
{118}{}{Berichte, Berichte, Berichte ...}
{119}{}{Muss ich noch in den Katalog aufnehmen.}
{120}{}{Nicht so vielversprechend, wie es scheint.}
{121}{}{Noch eine dumme Idee.}
{122}{}{Muss ich wegwerfen.}
{123}{}{Noch ein lächerlicher Bericht.}
{124}{}{Wann ist die Besprechung zur Planung?}
{125}{}{Wann ist Mittagspause?}
{126}{}{Wie lange dauert die Essenspause?}
{127}{}{Ich bin müde.}
{128}{}{Ein wenig ausruhen, und dann wieder an die Arbeit.}
{129}{}{Meine Augen tun weh.}
{130}{}{Das alles lesen? Feuert mich lieber!}
{131}{}{Feuert mich bloß nicht.}

#Starting conversation
{200}{}{Hallo. Was wollten Sie?}
{201}{}{Wo bin ich? Ist das ein Archiv?}
{202}{}{Ist das ein Archiv? Kann ich hier die Koordinaten eines Militärstützpunkts namens „Area 51“ finden?}
{203}{}{Die Polizei hat mir vom Verschwinden Ihrer Tochter erzählt. Ich habe mich freiwillig gemeldet, um bei der Suche zu helfen.}
{204}{}{Falsche Tür, entschuldigen Sie.}

{205}{}{Ja, hier werden alle Daten aufbewahrt, allerdings sind es größtenteils Berichte der Abteilungen des Rathauses. Ich bin ein leitender Mitarbeiter der Abteilung ... Allerdings ist unser Archiv nur für den internen Gebrauch bestimmt.}
{206}{}{In diesem Fall brauche ich die Koordinaten eines Militärstützpunkts namens „Area 51“.}
{207}{}{Nichts dergleichen. Eine andere Frage.}
{208}{}{Ich glaube, ich brauche nichts.}

{209}{}{Aber unser Archiv ist nur für den internen Gebrauch bestimmt. Ich kann Ihnen keinen Zugang zu irgendwelchen Dokumenten gewähren.}
{210}{}{Oh! Natürlich! Nach allem, was Sie für uns getan haben, werde ich jeden Winkel des Archivs durchforsten, um diese Information zu finden ...}
{211}{}{Großartig!}
{212}{}{... Allerdings ist unser Archiv nur für den internen Gebrauch bestimmt. Aber ich glaube nicht, dass der Gemeinde etwas passiert, wenn jemand ein paar Koordinaten erhält ...}
{213}{}{Es wird keine Konsequenzen geben, keine Sorge.}
{214}{}{Ja, gut zu hören. Aber ich brauche etwas Zeit ... Also, Area 51 ... Ein Militärstützpunkt ... ... ... Ja. [Er geht in den Archivraum]}
{215}{}{[Warten]}
{216}{}{Ja! Ich hab's gefunden! In einem der Vorkriegsberichte ... Hier. Und hier sind die geografischen Koordinaten. Ist das ein Pip-Boy? Funktioniert es? Dann kannst du einfach die Koordinaten eingeben und den Ort auf der Karte sehen.}
{217}{}{Genau! Vielen Dank, du hast mir sehr geholfen!}
{218}{}{Oh nein! Ich danke dir!}
{219}{}{Tschüss.}
{220}{}{}

{221}{}{Du bist kein dummer Mann und solltest verstehen, dass ich dir für deine Hilfe etwas zurückgeben werde.}
{222}{}{Dann könnten wir einen Handel abschließen. Was verlangt die Gemeinde im Austausch für diese Information?}
{223}{}{Okay, genug! Ich brauche die Koordinaten, bevor ich richtig wütend werde! Und zwar sofort!}
{224}{}{Na ja, das ist schade.}
{225}{}{Äh ... Junger Mann, versuchen Sie nicht, mir zu drohen ... Äh ... Die Wachen sind gleich hinter der Tür, also ...}
{226}{}{Hör zu, du Dreckskerl, ich hab die Schnauze voll von deinem Scheiß! Ich mach hier keine Witze! Gib mir die Koordinaten!}
{227}{}{Vielleicht gibt es bei der Gemeinde ein Verfahren, um an die Informationen aus dem Archiv zu kommen? Kann ich einen Antrag ausfuellen?}
{228}{}{Na gut, na gut, ich lasse dich in Ruhe.}
{229}{}{[Der Mann rückt seine Brille auf der Nase zurecht, sein Blick weicht deinem aus] Äh ... Ich wiederhole ... Drohungen bringen nichts. Du wirst nichts bekommen. Das Archiv ist *nur* für Mitarbeiter des Bürgermeisteramts ...}
{230}{}{Dann kann ich vielleicht jemanden überreden, die Informationen für mich zu holen?}
{231}{}{Nun ... Ich glaube nicht, dass ... Für dich ... Aber wenn du schon jemanden kennst, dann ...}
{232}{}{Na gut, ich lasse dich vorerst in Ruhe.}
{233}{}{Okay, das reicht, du Brillenschlange! Ich hab genug von dir! Zum letzten Mal: Gib mir die Koordinaten! Oder dein alter Arsch wird auf der Stelle plattgemacht, und keine Wache wird dich retten!}
{234}{}{[Er wird blass. Plötzlich beginnt er zu schreien] Wachen!!! Wachen!!! Eindringling!!!}
{235}{}{Du Hurensohn! Glaubst du, die sind schneller als meine Kugel!?}
{236}{}{Äh ... Ehrlich gesagt, weiß ich es nicht ... Bisher haben sich nur Mitarbeiter des Rathauses für das Archiv interessiert, und alle anderen Bürgern war es egal ...}
{237}{}{Hm. Wie viel bekommst du für diese Arbeit bezahlt?}
{238}{}{Äh ... ich fürchte, das kann ich dir auch nicht sagen. Nicht viel, ehrlich gesagt ...}
{239}{}{Dann zahle ich dir 100 Dollar für deine Mühe.}
{240}{}{Dann zahle ich dir 200 Dollar für deine Mühe.}
{241}{}{Dann zahle ich dir 300 Dollar für deine Mühe.}
{242}{}{Dann zahle ich dir 500 Dollar für deine Mühe.}
{243}{}{Vergiss es. Tschüss.}

{244}{}{Weißt du, ich finde das fair. Nach dieser staubigen Arbeit muss ich schließlich auch auf mich achten ... Für diesen Preis besorge ich dir die Koordinaten.}
{245}{}{Hier ist das Geld.}
{246}{}{Nur habe ich gerade kein Geld bei mir. Aber du kannst schon nach den Koordinaten suchen, während ich es hole.}
{247}{}{Äh ... Weißt du, mein Job ist mir wichtiger als die Gelegenheit, mich einmal bestechen zu lassen. Ich will ihn wirklich nicht verlieren.}
{248}{}{Nun, natürlich mache ich das, aber erst, wenn du mir die, äh, Entschädigung bringst. Für meine Mühe.}
{249}{}{Verdammt, dann warte. Ich bin gleich wieder da.}
{250}{}{Grrm, ach, sieh mal, hier ist das Geld in der anderen Tasche. Jetzt tu mir einen Gefallen und such die Koordinaten!}
{251}{}{[Der Archivar murmelt etwas und geht in den Archivraum. Eine halbe Stunde später kommt er mit einem Zettel in der Hand zurück.] Das sind die Koordinaten. Ich sehe, du hast ein Pip-Boy. Dann kannst du dort die Koordinaten eingeben und den Ort auf der Karte sehen.}
{252}{}{Großartig! Danke.}

{253}{}{Was machst du, willst du aus meinen Problemen Profit schlagen?!}
{254}{}{Du hast also Probleme?! Großartig, dann können wir einen Deal machen.}
{255}{}{Äh, nein. Wir sehen uns.}
{256}{}{Ugh, ich habe ein großes Problem, etwas, das die Polizei nicht lösen kann. Meine Tochter ist verschwunden.}
{257}{}{Unter welchen Umständen?}
{258}{}{Meine Tochter Anna ... Sie ist verschwunden. Zuvor hatten wir ein langes und unangenehmes Gespräch über ein paar neue Freunde, mit denen sie sich herumtrieb. Ich habe versucht, sie davon zu überzeugen, nicht aus den Mauern des Clean City hinauszugehen. Dort ist es nicht sicher. Offenbar hat sie nicht auf mich gehört.}
{259}{}{Ist es hier wirklich sicherer?}
{260}{}{Was für Freunde?}
{261}{}{Natürlich. Aber diese dreckigen Hippies, die auf ihren Motorrädern durch das Ödland fahren – sie legen immer junge, leichtgläubige Mädchen wie Anna herein.}
{262}{}{Es sieht so aus, als würden wir über Biker reden ...}
{263}{}{Ich weiß nicht viel über sie, und ich will es auch nicht. Sie liebt diese Typen. Das ist natürlich nicht überraschend – sie ist erst fünfzehn. Normalerweise habe ich in „Hard-Rock“ nach ihr gesucht, aber in letzter Zeit hat sie dort niemand mehr gesehen ... Vielleicht verstecken sie sie vor mir? Ich glaube nicht, dass sie in ihrem Alter beschließen würde, aus der Stadt abzuhauen.}
{264}{}{Du bist natürlich ein ziemlicher Feigling, aber ich helfe dir, sie zu finden. Vielleicht sollte ich in diesem Café anfangen ...}
{265}{}{Das ist zu schwierig. Ich bin mir nicht sicher, ob ich helfen kann.}

{266}{}{Du bist es! Ich bin so froh, dich zu sehen! Weißt du, sie ist tatsächlich zurückgekommen! Aber sie sieht furchtbar aus. Ich habe ihr gesagt, sie soll sich von diesen Bikern fernhalten, aber sie hat nicht auf mich gehört! Jetzt wird sie eher auf ihren Vater hören. Ich bin dir so dankbar ... Ähem. Weißt du, ich dachte mir, so etwas sollte nicht unbelohnt bleiben. Hier sind 2000 Bucks – ich hoffe, das reicht zumindest, um deine Reisekosten zu decken.}
{267}{}{Nicht schlecht für so einen einfachen Job! Mach's gut.}
{268}{}{Das ist gut, aber ich suche nach Area 51. Das ist eine Militärbasis, 80 Meilen von Vegas entfernt. Könnten Sie in den Akten nach den Koordinaten suchen?}

{269}{}{Oh, natürlich! Man hat mich schon informiert. Mr. Williamson hat persönlich nach Ihnen gefragt! Mal sehen ... Was wollten Sie noch mal herausfinden?}
{270}{}{Die Koordinaten von Area 51 ...}
{271}{}{}
{272}{}{}
{273}{}{}
{274}{}{}
{275}{}{Im Moment nichts.}
{276}{}{}
{277}{}{Danke.}

{278}{}{Mr. Clark, dieser Anhänger gehört Ihrer Tochter, stimmt's?}
{279}{}{[Seine Hände zittern] Oh Gott ... Es ist ihr Anhänger, aber ... Wo!? Wo haben Sie ihn her!? Antworten Sie mir!!!}
{280}{}{Das ist alles, was von ihr übrig ist. Sie ist gestorben.}
{281}{}{Sie hat ihn mir gegeben und gesagt, sie würde nie zu Ihnen zurückkommen.}
{282}{}{Er war bei einem der Biker. Diese Bastarde wollten mir nicht sagen, was sie ihr angetan haben.}

{283}{}{Nein! Neeein! [Er drückt den Anhänger ans Herz und beginnt, bitterlich zu weinen]}
{284}{}{Ja, heul ruhig, du Weichei.}
{285}{}{Es tut mir so leid.}
{286}{}{Oh nein ... [reißt panisch die Augen auf und setzt sich hin, um nicht zu Boden zu fallen] Nein ... Das ist alles meine Schuld! Ich hätte besser auf meine geliebte Tochter aufpassen müssen! Und jetzt ... Jetzt ist es zu spät ... [Er schlägt die Hände vors Gesicht und beginnt zu weinen]}
{287}{}{Oh nein ... [reißt panisch die Augen auf und setzt sich hin, um nicht zu Boden zu fallen] Nein ... Sie haben es getan. Sie haben sie umgebracht! ... Oh Gott ... Das ist alles meine Schuld! Ich hätte besser auf meine geliebte Tochter aufpassen müssen! Und jetzt ... Jetzt ist es zu spät ... [Er schlägt die Hände vors Gesicht und beginnt zu weinen]}
{288}{}{::weint::}
{289}{}{Heute wird er nicht mit dir reden.}

#Female character
{1201}{}{Wo bin ich? Ist das ein Archiv?}
{1204}{}{Falsche Tür.}
{1223}{}{Na schön, genug! Ich brauche die Koordinaten, bevor ich richtig wütend werde! Sofort!}
{1225}{}{Äh ... junge Dame, versuchen Sie nicht, mich zu bedrohen ... Ähm ... Die Sicherheitsleute stehen direkt hinter der Tür, also ...}
{1265}{}{Das ist zu schwierig. Ich bin mir nicht sicher, ob ich helfen kann.}
