{100}{}{Du siehst den Kulturminister.}
{101}{}{Du siehst einen gewandten Angestellten des Rathauses. Seinem Abzeichen nach zu urteilen, ist er Kulturminister.}

{110}{}{Worum geht es?}
{111}{}{Oh, ich habe eine Menge Fragen. Kannst du mir helfen, sie zu beantworten?}
{112}{}{Das hängt von deiner Stellung ab. Bist du der Kulturminister? Was bedeutet das?}
{113}{}{Ich habe keine Fragen. Bis später.}

{114}{}{Das bedeutet, dass ich der Kulturminister bin und du ein einfältiges Kind aus dem Ödland. Es ist sinnlos, dir zu erklären, was „Kultur“ bedeutet, tut mir leid.}
{115}{}{Trotzdem wäre es schön, wenigstens etwas klarzustellen.}
{116}{}{In dem Fall haben wir nichts zu besprechen.}
{117}{}{[Seufzt nervös] Meine Aufgabe ist es, sämtliche kulturellen Normen von Clean City zu entwickeln und zu bewahren. Meine Abteilung beurteilt, wie die Stadt aussehen und klingen soll, aber vor allem, wie die Einheimischen ihre intellektuellen Fähigkeiten verbessern sollten. Das wirst du wohl kaum verstehen.}
{118}{}{Es scheint, als hieltest du nicht viel von den Menschen, die außerhalb der Stadt leben.}
{119}{}{Was redest du da!? Jenseits der Mauern von Clean City gibt es viele talentierte und gebildete Menschen. Zum Beispiel mich.}
{120}{}{Die Lage ist klar. Vielleicht kannst du jetzt ein paar Fragen beantworten?}
{121}{}{Ja, ich denke, diese Informationen reichen meinem Hirn. Wir sehen uns.}

{122}{}{[Verschmitzt grinsend] Was redest DU da?! Ich halte tatsächlich ziemlich viel von den Bewohnern des Ödlands. Man muss sie nur waschen, anziehen, jedem ein Buch geben und ihnen ein paar gute Manieren beibringen – und schon hat man eine Armee anständiger Leute. Die Frage ist nur: Wie lange hält diese Anständigkeit an?}
{123}{}{Ich will dir nicht widersprechen. Außerhalb der Mauern herrscht wirklich ein verdammt erbärmliches und jämmerliches Leben.}
{124}{}{Bei so viel Snobismus kann man von dir nichts als Diskriminierung erwarten.}
{125}{}{Ich habe allen Grund zu glauben, dass du kaum etwas von der Welt verstehst und deinen eigenen Wahnvorstellungen zum Opfer gefallen bist. Ich bin der lebende Beweis dafür.}
{126}{}{Lassen wir die Diskussion dabei bewenden.}

{127}{}{Ich verstehe nicht – versuchst du, mich zu beeindrucken, oder kommst du selbst von einem anderen Stern? Wobei deine Sicht auf unsere Stadt angesichts des Kontrasts zwischen Clean City und dem Umland durchaus verständlich ist.}
{128}{}{Nein, davon rede ich nicht! Weißt du, all die Banditen auf den Straßen von Reno, wilde Ghule, Raider, durchgeknallte Idioten – auf meiner Reise habe ich so einiges gesehen.}
{129}{}{Pass auf, junger Mann! Hast du eine Ahnung, wie viel Arbeit in den Wiederaufbau dieses Gebiets geflossen ist?! Zehn Jahre lang haben wir gemeinsam versucht, hier ein anständiges Leben aufzubauen. Und jetzt kann jedes dahergelaufene Gesindel hier seinen Muell abladen. Aber jedenfalls habe ich keine Lust, dir irgendetwas zu beweisen. *Du* kommst hierher und hältst mich mit deinen sinnlosen Gesprächen von der Arbeit ab.}
{130}{}{Du siehst weder wie ein Karawanenführer noch wie ein Vertreter von „Nevada express“ aus. Dieses Gespräch wird langsam sinnlos.}
{131}{}{Vielleicht kannst du mir in dem Fall ein paar Fragen beantworten?}
{132}{}{Hast du auf deinen Reisen wirklich so viele Erfahrungen gesammelt? Wie interessant ... Ich würde gern mit dir über das Leben der Menschen in anderen Städten sprechen. Es macht dir doch nichts aus, oder?}
{133}{}{Oh, natürlich, sehr gern!}
{134}{}{Dafür habe ich gerade keine Zeit. Vielleicht ein andermal.}
{135}{}{Es kann keinen anderen Zeitpunkt geben. Aber du hast dich bereits entschieden, also belassen wir es dabei. War das alles, was du wissen wolltest?}
{136}{}{Nein, ich hatte noch mehr Fragen zum Clean City und zum Rathaus.}
{137}{}{Ja, ich muss jetzt gehen. Mach's gut.}
{138}{}{Ausgezeichnet. Jeden Tag esse ich im Casino auf der anderen Straßenseite zu Abend. Triff mich dort, dann können wir uns in einem kultivierteren Ambiente unterhalten.}
{139}{}{Das werde ich mir merken. Und jetzt – könntest du noch ein paar Fragen zur Stadt beantworten?}
{140}{}{Bis dann.}

{141}{}{Ach nein, du wirst mich nicht täuschen. Im Bereich Bildung glänzt du ganz sicher nicht.}
{142}{}{Wie arrogant ... Aber vielleicht irre ich mich manchmal. Ich habe seit zehn Jahren keinen Fuß mehr aus dem Clean City gesetzt. Vielleicht hat sich in der Zeit manches verändert, aber ich bezweifle es stark. Du wirst mir doch erzählen wollen, dass das Leben draußen besser geworden ist, oder?}
{143}{}{Zehn Jahre – das ist eine Zeit der Großen Depression. Eine Ewigkeit. Weißt du, in letzter Zeit läuft es im New Reno besser, und entlang der Bundesstraßen entstehen zahlreiche neue Siedlungen ... Die Welt verändert sich. Du solltest dich mal genauer umsehen.}
{144}{}{Große Depression ... Jetzt hör aber auf. Das ist Geschichte. Bist du nicht ein bisschen zu gebildet für einen Ödländer?}
{145}{}{Ich interessiere mich einfach fürs Lernen. Aber wie schaffst du es, dir unter diesen Bedingungen den Drang nach kultureller Entwicklung zu bewahren?}
{146}{}{Mein Gott! Mit wem rede ich hier? Hör zu, so einfach ist das eigentlich nicht. Seit vielen Jahren versuche ich, hier ein kulturelles Bildungsprogramm auf die Beine zu stellen, aber ich stoße bei den anderen Mitgliedern des Bürgermeisteramts ständig auf Unverständnis. Für sie sind Dinge wichtiger, die direkten Nutzen bringen, wie Handel, Mieteinnahmen, Unterhaltung, Strom und alles, womit man Profit machen kann. Nur wenige können meine Ambitionen würdigen. Zum Glück hat der Bürgermeister mir erlaubt, diese Abteilung einzurichten, auch wenn unser Budget knapp ist.}
{147}{}{Du hast es hier also nicht leicht. Vielleicht sollte ich darüber ein wenig nachdenken. Auf Wiedersehen.}
{148}{}{Du hast dem Snob bewiesen, dass es außerhalb der Stadtmauern kluge Leute gibt.}
{149}{}{Gut, aber ich würde gern ein paar Fragen stellen und nicht sie beantworten.}

{150}{}{[Bremst die Wohltätigkeit hinter arrogantem Lächeln] Deine Neugier ist durchaus respektabel, aber ich habe keine Zeit für sinnloses Gerede.}
{151}{}{Gern, aber ich habe wenig Zeit für Smalltalk.}
{152}{}{Ich tue so, als hätte ich das nicht gehört, aber andere Mitglieder der Clean City würden das nicht tun. Viele sind stolz darauf, hier zu leben. Ist dir überhaupt klar, wie viel Arbeit in den Wiederaufbau dieser Gegend geflossen ist?! Zehn Jahre lang haben wir gemeinsam versucht, hier ein anständiges Leben aufzubauen. Für Außenstehende ist das schwer zu verstehen. Sie glauben, die Einheimischen hätten von Anfang an alles gehabt.}
{153}{}{Auch wenn du viel Erfahrung hast, würde ich lieber zuverlässigere Quellen zu Rate ziehen.}
{154}{}{Ich bin Kulturminister, nicht dein Saufkumpan in einer Bar! Ich werde keine Fragen beantworten.}
{155}{}{Du reagierst auf eine einfache Frage ziemlich emotional. Magst du meine Gesellschaft nicht?}
{156}{}{Reden wir über dein Amt, das Amt des Kulturministers.}
{157}{}{Ja, genau. Ich sehe in dir nicht die Eigenschaften, die ich an anderen schätze. Außerdem bin ich nicht verpflichtet, mit dir zu reden. Dafür gibt es eine Sekretärin.}
{158}{}{Gut, ich gehe.}
{159}{}{Schade, dass du mich so behandelst. Ich bringe Vegas Gewinne ein ...}

{160}{}{Erzähl mir von der Geschichte der Clean City. Wie habt ihr es geschafft, all das wiederaufzubauen?}
{161}{}{Warum werden Außenstehende so stark diskriminiert?}
{162}{}{Heutzutage sind Polizei und Bürgermeisteramt in Städten etwas Ungewöhnliches. Wirst du für Ordnung sorgen können?}
{163}{}{Erzähl mir von deinem Ministerium. Was unterscheidet es von den anderen?}
{164}{}{Erzähl mir von deinem Bürgermeister.}

{167}{}{Noch eine Frage, bitte.}
{168}{}{Was willst du wissen?}
{169}{}{Wir haben schon vieles geklärt. Belassen wir es dabei.}

{170}{}{Zehn Jahre harte Arbeit. Anfangs war der Boulevard nichts weiter als dasselbe langweilige, wenig besuchte Viertel wie jedes andere in Vegas. Dann wurde er zu einem zentralen Markt, auf dem einige wohlhabende Familien mit dem Handel von Nahrung und Wasser ein Vermögen machten. Bald steigerten die Familien ihre Einnahmen und begannen, Sklavenarbeit einzusetzen. Mit Hilfe der Sklaven räumten sie das Gebiet und brachten alles in Ordnung. Seit zehn Jahren versuchen die Menschen hier, sich ein ordentliches Leben aufzubauen. Es bildete sich ein Teufelskreis aus Eliten und Berühmtheiten. In zehn Jahren hat sich viel verändert.}
{171}{}{Würde es Ihnen gefallen, wenn schmutzige Bettler in Ihr sauberes, liebevoll gepflegtes Haus eindringen, Lärm machen und Probleme verursachen? Die meisten sehen nur Luxus und Glanz, während unsere harte tägliche Arbeit hinter den Kulissen bleibt. Wenn ja, dann sehe ich keinen Grund, den Affen wie einen Menschen zu behandeln, wenn er ein Tier und ich ein Mensch bin.}
{172}{}{Natürlich. Aber nur in der Clean City. Für ganz Vegas haben wir einfach keine Zeit. Deshalb versinken die Außenbezirke in Armut und Kriminalität.}
{173}{}{Das Kulturamt ist für das Programm kultureller Veranstaltungen und die Repräsentation der Clean City und ihrer Bewohner verantwortlich, aber vor allem für die Bildung. Vor Kurzem haben wir sogar begonnen, die erhalten gebliebenen Bücher aus der Vorkriegszeit über Automaten zu verkaufen. Stellen Sie sich nur einen Mann vor, der außerhalb der Clean City ein Buch liest. Das ist fast unmöglich, nicht wahr?}
{174}{}{Ich würde lieber mit niemandem über den Bürgermeister sprechen, nicht einmal mit Bekannten. Aber manchmal frage ich mich: Wie konnte der Rat einen rückgratlosen, fügsamen alten Mann für einen so wichtigen Posten auswählen? Ich fürchte nur, dass persönliche Interessen den Bürgermeister verderben werden.}
{175}{}{Wirklich? Was ist das für ein Geschäft, wenn ich fragen darf?}
{176}{}{Ich beliefere die Nuka-Cola, gemäß der Vereinbarung mit der Fabrik im Norden. Ich kann Ihnen die Papiere zeigen, wenn Sie mir nicht glauben.}
{177}{}{Mein Privatgeschäft ist unabhängig. Ich bin nicht einmal verpflichtet, der Clean City Bericht zu erstatten.}
{178}{}{Das ist vertraulich. Ich habe eine Sondervereinbarung mit dem Bürgermeister der Stadt.}
{179}{}{Hmm, dann entschuldigen Sie. Ich muss allerlei Gesindel wegschicken, damit es mich nicht belästigt und bei der Arbeit stört. Sie wissen ja, wie das ist.}
{180}{}{Oh ja. Können Sie mir vielleicht etwas über die Arbeit im Rathaus erzählen?}
{181}{}{Sie haben den arroganten Kulturminister dazu gebracht, all Ihre Fragen zu beantworten.}
{182}{}{F-fass mich nicht an!!! Bleib weg! Wie hat die Security dich hier reingelassen?! Verschwinde! Verschwinde sofort, Ghoul, damit ich dich nicht mehr sehen muss!}
{183}{}{Hey, verwechsel eine Hautkrankheit nicht mit Verghoulung! Ach, verdammt, es ist sinnlos, es dir zu erklären.}
{184}{}{Wenn du noch einmal über meine Krankheit redest, wirst du viel schlimmer aussehen als jetzt. Viel schlimmer.}
{185}{}{Security! SICHERHEIT!!!}
{186}{}{[Gehen]}
{187}{}{Eigentlich ist das wirklich wichtig. Vielleicht kannst du ein paar Fragen beantworten?}
{188}{}{Vergiss es, es ist nicht wichtig.}
{189}{}{Auf meinen Reisen halte ich mich von großen Siedlungen fern. Die Erfahrung, in der Wildnis zu überleben, ist mir wichtiger.}
{190}{}{Hast du auf deinen Reisen wirklich so viel Erfahrung gesammelt? Wie interessant ... Ich würde mich gern mit dir über das Leben im Ödland unterhalten. Du hast doch nichts dagegen, oder?}

{200}{}{Und ich dachte schon, du kommst nicht mehr.}
{201}{}{Speist du oft hier?}
{202}{}{Du wolltest mit mir über die Welt außerhalb sprechen. Also, ich bin ganz Ohr.}
{203}{}{Warte bitte, ich muss noch etwas erledigen, dann komme ich zurück.}
{204}{}{Es ist meine Pflicht, zu wissen, wie die Geschäfte hier laufen. Außerdem gefällt es mir hier.}
{205}{}{Ja, es wäre toll, die Geschichte direkt von einem Reisenden zu hören. Machen wir es uns gemütlich, bestellen etwas Whiskey und reden darüber.}
{206}{}{Klar, gerne ...}
{207}{}{Tut mir leid, aber gerade geht es nicht. Warte bitte, ich muss noch ein paar Dinge erledigen.}
{208}{}{Du hast dem Snob die Augen geöffnet und ihm die erstaunliche und vielfältige Welt außerhalb von Vegas gezeigt.}
{209}{}{Guten Abend.}
{210}{}{Auf Wiedersehen.}
