{100}{}{Du siehst eine Sekretärin.}
{101}{}{Du siehst Marion Keysker.}
{102}{}{Du siehst eine Dame mittleren Alters mit einem ziemlich strengen, ja fast nervösen Blick.}
{103}{}{Tut mir leid, heute ist kein Besuchstag.}
{104}{}{Flirte nicht mit mir, ich arbeite.}
{105}{}{Es tut mir leid, aber ich muss dein Gesicht sehen.}

#Ñ'àğ' äèàëîãà
{110}{}{Guten Tag. Ich bin Marion Keysker, die Sekretärin unseres Bürgermeisters. Wie kann ich Ihnen helfen?}
{111}{}{Wie kann ich dir helfen?}
{112}{}{Ich muss den Bürgermeister sprechen.}
{113}{}{Ich suche die Koordinaten von Area 51. Ist es möglich, dass das Rathaus diese Informationen hat?}
{114}{}{Ich glaube nicht, dass das geht. Auf Wiedersehen.}

#Ïîëó÷åíèå ğàçğåøåíèÿ íà àóäèåíöèş ñ ìığîì
{115}{}{Haben Sie einen Termin?}
{116}{}{Äh ... Ja?}
{117}{}{Nein. Wie bekomme ich einen Termin?}
{118}{}{Gut. Ich werde Mr. Williamson Bescheid sagen. Wie ist Ihr Name?}
{119}{}{.}
{120}{}{Ich meine, wie bekomme ich einen Termin?}
{121}{}{Niemand. Schreiben Sie das auf!}
{122}{}{Wissen Sie was, ich komme später wieder.}

{123}{}{Oh, Mr. Niemand. Wissen Sie, dass Sie nicht auf der Liste stehen? Ich glaube, das wissen Sie.}
{124}{}{Hey, Lady! Ich werde den Bürgermeister so oder so sprechen!}
{125}{}{Na gut.}
{126}{}{Sie stehen nicht auf der Liste. Verlassen Sie jetzt bitte diesen Raum.}
{127}{}{Marion, mein Schatz! Bitte sag dem Herrn Bürgermeister, dass ein Herr ihn sprechen möchte. Und hier ist eine Süßigkeit für deinen Kaffee, damit dein schönes Gesicht etwas milder wird.}
{128}{}{Marion, mein Schatz! Bitte sag dem Herrn Bürgermeister, dass eine Dame mit ihm über etwas sehr Wichtiges sprechen möchte!}
{129}{}{Oh, vielen Dank, Herr ...?}
{130}{}{Herr }
{131}{}{. Einfach nur Herr }
{132}{}{.}
{133}{}{Na gut. Sagen Sie mir, sagen Sie mir Ihren Namen, und ich vereinbare einen Termin.}
{134}{}{Fräulein }
{135}{}{. Einfach nur Fräulein }
{136}{}{.}
{137}{}{Na gut, Herr }
{138}{}{. Warten Sie, ich kontaktiere Mr. Williamson.}
{139}{}{Okay. Ich warte.}
{140}{}{Okay, Fräulein }
{141}{}{Herr Williamson ist bereit, Sie zu empfangen. Gehen Sie in sein Büro.}
{142}{}{Danke.}

{143}{}{Du musst mir nicht so schmeicheln. Herr Williamson ist ein sehr beschäftigter Mann. Wenn du keinen Termin hast, wird er dich nicht empfangen.}

#Êàê çàïèñà'üñÿ íà ïğèåì?
{144}{}{Herr Williamson empfängt nur bei besonders wichtigen Angelegenheiten. Nennen Sie den Grund Ihres Besuchs.}
{145}{}{Ich habe wichtige Informationen, die einige Untergebene des Bürgermeisters belasten.}
{146}{}{Ich möchte einfach mit dem Bürgermeister über die Stadt sprechen.}
{147}{}{Ich denke, Sie verstehen, dass das nicht wichtig genug ist, um den Bürgermeister damit zu behelligen.}
{148}{}{Ich würde gern im Büro des Bürgermeisters arbeiten.}
{149}{}{Hmm ... Herr Williamson suchte einen Spezialisten für eine bestimmte Aufgabe ... Vielleicht kannst du ihm helfen. Ich werde ihm von deinem Besuch erzählen. Wie heißt du?}
{150}{}{Weißt du, vielleicht ein andermal. Mach's gut.}
{151}{}{Oh, das ist ein sehr schwerwiegender Vorwurf! Ich glaube, ich muss Sie einlassen. Wie heißen Sie?}
{152}{}{Du hast eine Besuchserlaubnis für Herrn Williamson, den Bürgermeister der Stadt, erhalten.}
{153}{}{Tut mir leid, Herr Williamson stellt vorerst niemanden ein.}
{154}{}{Als Sheriff einer kleinen Stadt im Westen finde ich bestimmt etwas, worüber ich mit Ihrem Bürgermeister sprechen kann.}
{155}{}{Oh, das ändert die Sache. Ich werde Herrn Williamson von Ihrem Besuch erzählen. Wie heißen Sie?}
{156}{}{Ich bin sicher, er wird sich für jemanden interessieren, der viele schwere Verbrechen aufgeklärt hat.}

#Çîíà 51
{200}{}{Hmm. Vielleicht gibt es solche Informationen in unserem Archiv. Aber nur Angestellte des Bürgermeisterbüros können Zugang beantragen.}
{201}{}{Also muss ich jemanden im Bürgermeisterbüro davon überzeugen, eine Anfrage zu stellen?}
{202}{}{Oh, wie schade.}
{203}{}{Offenbar ja. Es ist verboten, Archivakten an Dritte herauszugeben.}
{204}{}{Und was ist mit Ihnen? Können wir uns einigen?}
{205}{}{Stimmt.}
{206}{}{Wer könnte mir helfen?}
{207}{}{Unser Bürgermeister ist zu beschäftigt. Vielleicht kann sein Stellvertreter, Tom Parker, dir helfen.}
{208}{}{Wo ist sein Büro?}
{209}{}{Ich glaube, niemand. Alle sind zu beschäftigt für solche Kleinigkeiten.}
{210}{}{Im zweiten Stock, gleich beim Konferenzraum.}
{211}{}{Danke.}
{212}{}{Weißt du, ich bin zu beschäftigt ...}
{213}{}{Liebe Marion, du solltest nicht so viele Zweifel haben! Glaub mir, wir werden uns schon gut verstehen. Ich bitte dich doch um nichts Kriminelles, oder? Schließlich ist das Archiv dafür da, damit die Leute Informationen bekommen ...}
{214}{}{Dein Verlust.}
{215}{}{Na gut. Du hast mich überzeugt. Es ist ja ohnehin kein großes Geheimnis. Also, was brauchst du noch mal?}
{216}{}{Area 51, nur die Koordinaten der Basis ...}
{217}{}{Na gut. Du hast mich überzeugt. Aber du verstehst doch, dass in unserer Welt nichts umsonst ist, oder?}
{218}{}{Natürlich. Kein Problem. Wie viel?}
{219}{}{Geld? Für ein paar Koordinaten? Auf keinen Fall!}
{220}{}{Du brauchst mir nicht zu schmeicheln. Ich kenne meine Arbeit. Für deine fragwürdige Anfrage werde ich nicht die Archive durchwühlen.}
{221}{}{Schade.}
{222}{}{Idiot! Du hast gerade einen Kunden verloren!}

{223}{}{1000 Dollar. Wir schätzen unsere Archive sehr.}
{224}{}{Was soll das heißen? Ist das wirklich so teuer?! Überleg es dir! Ich kann gleich gehen und du bekommst keinen einzigen Penny.}
{225}{}{Na gut, hier sind 1000 Dollar.}
{226}{}{Oh nein, das ist zu teuer!}
{227}{}{Vielleicht hast du recht. Machen wir 500 draus. Aber keinen Cent weniger!}
{228}{}{Hier ist das Geld.}
{229}{}{Das ist immer noch zu viel. Nein.}
{230}{}{Meine Zeit ist kostbarer. Und ich werde darauf keinen Rabatt geben.}
{231}{}{Na gut, du hast mich bei 1000. Hier ist das Geld.}
{232}{}{So viel kann ich mir gerade nicht leisten.}
{233}{}{500 Dollar. Wir schätzen unsere Archive sehr.}
{234}{}{Vielleicht hast du recht. Senken wir den Preis auf 300. Aber keinen Cent weniger!}
{235}{}{Na gut, du hast mich bei 500. Hier ist das Geld.}
{236}{}{Der Preis stimmt. Hier ist das Geld.}

{237}{}{Na gut, die gute Nachricht ist: Unsere Archive sind sehr gut organisiert. Hier sind die Koordinaten, nach denen du gesucht hast.}
{238}{}{Danke. [Gib die Koordinaten in Pip-Boy ein und geh]}
{239}{}{Dann musst du ein wenig warten, bis ich im Archiv bin.}
{240}{}{Klar. Ich warte.}

#Ïğîõîä ê ìığó -- íàìåê ïğî ãîğîä
{242}{}{Oh nein. Ich glaube, der Bürgermeister braucht jemanden, der intelligent genug für Ermittlungsarbeit ist. Weißt du, in letzter Zeit ist in der Stadt viel Verdächtiges passiert! Und die Polizei unternimmt nichts dagegen ...}
{243}{}{Ja, ich habe davon gehört ... Mr. Williamson möchte vielleicht mit dir sprechen. Ich erinnere mich, dass er es oft erwähnt hat ...}
{244}{}{Dann sag ihm, dass der Detektiv zur Verfügung steht. Vielleicht gilt das Angebot ja noch ...}
{245}{}{Wahrscheinlich nicht jetzt. Ich komme später wieder.}

#Female character
{1120}{}{Ich meine, wie bekomme ich einen Termin?}
{1148}{}{Ich würde gern im Büro des Bürgermeisters arbeiten.}
