{100}{}{Du siehst David.}
{101}{}{Du siehst einen der Türsteher des Casinos.}

{110}{}{Hör zu, ich halte hier nach jemandem Ausschau, und du solltest dich besser nicht einmischen.}
{111}{}{Nach wem hältst du Ausschau?}
{112}{}{Was, wenn ich den Kerl vor dir finde?}
{113}{}{Okay, ich werde dich nicht stören.}
{114}{}{Unverschämt! Ich werde mich über Ihre Geschäftsführung beschweren!}

{115}{}{Für skrupellose Casinobesucher. Und jetzt lassen Sie mich in Ruhe.}
{116}{}{Hmm. Eigentlich ist das keine schlechte Idee. Einer unserer Kunden schuldet uns nämlich eine wirklich große Summe und versteckt sich jetzt vor der Justiz.}
{117}{}{Wie heißt dieser Kunde?}
{118}{}{Wie viel schuldet er dem Casino?}
{119}{}{Warum suchen Sie ihn nicht, sondern lungern hier in der Lobby herum?}
{120}{}{Was bekomme ich, wenn ich ihn zu Ihnen bringe?}
{121}{}{Wissen Sie was? Finden Sie es ohne mich heraus.}
{122}{}{Das reicht! Ich will die Schulden dieses Kerls begleichen!}

{130}{}{Er heißt Norman.}
{131}{}{Oh, das ist eine riiiesige Schuld. Was er uns schuldet, ist auf dem Markt ungefähr 3000 Dollar wert. Ziemlich gut, wenn man bedenkt, dass er sich davon nicht trennen will, solange er noch atmet.}
{132}{}{Was glaubst du denn, was ich mache? Ich suche diesen Hurensohn, Mr. Snoops! Ja, genau hier. Denn der einzige Ausgang ist hier, und ihn in der Menge auf allen Stockwerken kreuz und quer zu suchen, ist ziemlich anstrengend.}
{133}{}{Nun, du erhältst die Ehre des Verwaltungssektors des Casinos und vielleicht 500 Dollar von mir für seine Ergreifung. Ich werde an ihm ohnehin noch viel mehr verdienen als an diesem erbärmlichen Betrag.}
{134}{}{Oh, das wäre mir sehr recht. Dann muss ich mir nicht die Hände schmutzig machen und anschließend auf einen passenden Kunden für seinen ... äh, schon gut. Aber es sind 3000 Dollar – das ist der Preis für seine Schulden.}
{135}{}{Ich habe das Geld zusammen. Machen wir den Tausch.}
{136}{}{Ausgezeichnet! Viel Vergnügen mit dem guten Geschäft. Hier ist unsere Quittung. Er kann das Casino jetzt verlassen, keine Sorge. Ich halte mein Wort.}
{137}{}{Okay, ich sage es ihm.}

{150}{}{Der, den Sie suchen, ist tot.}
{151}{}{Ist das so? Sehen wir erst mal nach, ob das stimmt ...}
{152}{}{Klar.}
{153}{}{Ausgezeichnet! Weniger Ärger für uns. Natürlich ist das Casino nicht dafür bekannt, den Einsatz von Gewalt zur Problemlösung zu fördern, aber in diesem Fall spreche ich als Privatperson. Hier sind also 300 Dollar Trinkgeld. Danke, Wanderer.}
{154}{}{Nein, *ich* danke dir!}
{155}{}{... äh, ja, und noch etwas. Ich habe gehört, dass unser Boss, Hal Wallace, jemanden für eine bestimmte Arbeit sucht. Wenn du einen Job brauchst, solltest du mit ihm reden.}
{156}{}{Großartig! Bis dann!}

#Æåí ðåïëèêè
{1132}{}{Was glaubst du denn, was ich hier mache? Ich suche diesen Mistkerl, Mrs. Snoops! Ja, genau hier. Denn der einzige Ausgang ist hier, und ihn in der Menge zu suchen, auf allen Stockwerken rauf und runter, ist ziemlich anstrengend.}
{1153}{}{Ausgezeichnet! Weniger Ärger für uns. Natürlich ist das Casino nicht dafür bekannt, den Einsatz von Gewalt zur Problemlösung zu fördern, aber in diesem Fall spreche ich als Privatperson. Hier sind also 300 Dollar Trinkgeld. Danke, Wanderer.}