{100}{}{Siehst du: ein wachsamer Wachmann.}
{101}{}{Du siehst einen Wachmann, der die Straße aufmerksam auf und ab mustert.}
{102}{}{Versuch das ja nicht noch einmal!}

#Ðàçãîâîð
{110}{}{Ja, Bürger? Brauchen Sie etwas?}
{111}{}{Warum sehen Sie sich so um?}
{112}{}{Nein, nichts.}

{113}{}{Dann lenken Sie mich nicht ab. Und bleiben Sie wachsam!}
{114}{}{Äh ... Na schön, wie Sie meinen.}
{115}{}{Ich beobachte die Straßen und halte Ausschau nach Ärger.}
{116}{}{Warum, ist etwas passiert?}
{117}{}{Muss ein harter Job sein.}
{118}{}{Gibt es hier viele Verbrechen?}
{119}{}{Das klingt übertrieben. Ist etwas im Gange?}
{120}{}{Ich lasse dich allein.}

{121}{}{Noch nicht, Bürger. Keine Sorge.}
{122}{}{Äh ... Ja, wie Sie sehen.}
{123}{}{Abgesehen von einigen Vorfällen in der Vergangenheit ist die Stadt völlig frei von Verbrechen. Keine Sorge, Bürger.}
{124}{}{Diese Informationen darf ich nicht mit gewöhnlichen Bürgern teilen. Verbrechen und Unfälle werden von einer Sonderkommission behandelt.}
{125}{}{Kann ich Teil dieser Kommission werden?}
{126}{}{Hmm ... Nein, sie würden dich nicht aufnehmen. Aber du könntest trotzdem bei einer laufenden Untersuchung helfen.}
{127}{}{In Ordnung. Ein paar Bürger verhalten sich verdächtig. Wegen ihrer Arbeit müssen sie den Stadtbereich verlassen. Wenn sie zurückkommen, verhalten sie sich ... seltsam. Auf verdächtige Weise seltsam. Wenn du wirklich helfen willst, folge ihnen und erzähl mir, was sie treiben.}
{128}{}{[Nickt] Ich bin froh, dass dir die Sicherheit unserer Stadt am Herzen liegt.}
{129}{}{}
{130}{}{}
{131}{}{}
{132}{}{Nein, ich will niemanden ausspionieren.}

{133}{}{Natürlich. Vergiss einfach alles, was ich gesagt habe.}
{134}{}{Warte, ich habe es mir anders überlegt. Was ist mit diesen Bürgern? Wieso sind sie verdächtig?}
{135}{}{Na gut.}

{136}{}{}
{137}{}{Wer sind sie?}
{138}{}{Wie oft verlassen sie den Stadtbereich?}
{139}{}{Wie viel Zeit verbringen sie außerhalb der Stadt?}
{140}{}{Was machen sie außerhalb der Stadt?}
{141}{}{Ich komme wieder, wenn ich etwas herausgefunden habe.}

{142}{}{Es sind Bürger Jacob und Bürger Emily. Sie arbeiten in der technischen Wartungsabteilung.}
{143}{}{Sie sollen die Sicherheitssysteme rund um den Stadtbereich zweimal täglich überprüfen.}
{144}{}{Früher brauchten sie etwa zwei Stunden, aber in letzter Zeit dauert es deutlich länger.}
{145}{}{Sie überprüfen die Sicherheitssysteme rund um den Stadtbereich. Eine vollständige Überprüfung sollte etwa zwei Stunden dauern.}

{146}{}{Ich helfe bei der Untersuchung. Wer weiß, vielleicht ist es meine letzte Gelegenheit, der Stadt zu helfen, bevor ich gehe.}
{147}{}{Was soll das ganze Regelwerk? Hör zu, wegen dieser ganzen Bürokratie bist du völlig verkrampft. Sag mir einfach, was ich tun soll, und ich kümmere mich darum.}
{148}{}{Das ist ja schön und gut, aber mich interessiert etwas anderes.}
{149}{}{Auf keinen Fall. Ich glaube, du vergisst, wer hier Hilfe braucht. Ich lasse dich noch eine Weile darüber nachdenken.}
{200}{}{Du bist derjenige, der diese beiden Bürger beim Verstoß gegen die Vorschriften erwischt hat? Gute Arbeit!}
{201}{}{Was wird mit ihnen geschehen?}
{202}{}{Ich überleg's mir.}
{203}{}{Das entscheidet die Kommission, aber wahrscheinlich werden sie zu verlängerter Isolation verurteilt.}
{204}{}{In Ordnung. Nun, ich will dich nicht länger aufhalten.}

{205}{}{Ich habe gehört, du bist dafür verantwortlich, die beiden zu schnappen! Gute Arbeit!}
{206}{}{Gibt es Neuigkeiten?}
{207}{}{Falscher Alarm. Alles in Ordnung.}
{208}{}{Bist du sicher? Was, wenn sie dich gesehen haben?}
{209}{}{Sie haben nicht einmal nachgesehen, ob sie beobachtet werden. Sie haben nichts zu verbergen.}
{210}{}{Vielleicht, aber mir ist an ihnen nichts Verdächtiges aufgefallen.}
{211}{}{[nickt] Gute Arbeit, Bürger }
{212}{}{. Du bist deiner Pflicht nachgekommen. Ich und alle in Vault City danken dir.}
{213}{}{Ich helfe immer gern!}
{214}{}{Bekomme ich etwas für meine Mühen?}

{215}{}{So sehr hast du dich nicht angestrengt. Glaubst du wirklich, du hast eine Belohnung verdient?}
{216}{}{Na gut, wie du meinst ...}
{217}{}{Wer im Glashaus sitzt ...}

{218}{}{Du hast deine Pflicht getan und fragst trotzdem nach einer Belohnung? [er beugt sich dicht zu dir] Ich denke ... ich kann etwas für dich tun.}
{219}{}{Ich brauche 9-mm-Munition.}
{220}{}{Ich brauche 10-mm-Munition.}
{221}{}{Ich brauche Geld für das Ödland.}
{222}{}{Im Moment brauche ich nichts.}
{223}{}{Natürlich. Hier, nimm es.}
{224}{}{Danke.}
{225}{}{Hab einen schönen Tag, Bürger }
{226}{}{.}
{227}{}{Ich darf nicht über Angelegenheiten der Kommission sprechen. Wenn du helfen wolltest, bist du ohnehin zu spät – der neueste Fall wurde mangels Beweisen abgeschlossen.}
{228}{}{Aha. Ich möchte noch etwas anderes fragen.}

#Female character
{1110}{}{Ja, Bürger? Was möchtest du?}
{1121}{}{Noch nicht, Bürger. Keine Sorge.}
{1123}{}{Abgesehen von einigen Vorfällen in der Vergangenheit ist die Stadt völlig frei von Verbrechen. Keine Sorge, Bürger.}
{1134}{}{Warte, ich habe es mir anders überlegt. Was ist mit diesen Bürgern? Wieso sind sie verdächtig?}
{1209}{}{Sie haben nicht einmal nachgesehen, ob sie beobachtet werden. Sie haben nichts zu verbergen.}
{1211}{}{[nickt] Gute Arbeit, Bürger }
{1213}{}{Gern geschehen!}
{1225}{}{Hab einen schönen Tag, Bürger }
