{100}{}{Du siehst Jacob.}
{101}{}{Du siehst Jacob, einen Bürger von Vault City.}
{102}{}{Ugh, mach das nie wieder!}

{103}{}{Ähm ... Es lebe Vault City!}
{104}{}{Wir haben es verdient, ich weiß.}
{105}{}{Du siehst Emily.}
{106}{}{Du siehst Emily, eine Bürgerin von Vault City.}
{107}{}{Ohne Jacob sage ich kein Wort!}

#Ïëàâàşùèå ôğàçû
{110}{}{Psst, da kommt jemand ...}
{111}{}{Versteck es! Schnell!}
{112}{}{Ohh ... Niemand hat uns gesehen, oder?}
{113}{}{::seufzt schwer::}
{114}{}{Nur noch ... ein bisschen, und ...}

{120}{}{Du bist dran.}
{121}{}{Komm schon, bevor uns jemand sieht ...}
{122}{}{Ah ... Nur noch ein bisschen ...}
{123}{}{Was ... machst ... du ...}
{124}{}{Warum produziert mein Mund so viel Speichel!?}
{125}{}{Was ist das?!}
{126}{}{OHH!}
{127}{}{Das habe ich nicht erwartet.}

#Ğàçãîâîğ
{200}{}{[Sobald sie dich sehen, ziehen sie sich sofort wieder an] Oh, Bürger! Äh ... Darf man hier sein?}
{201}{}{Ich? Ja. Ihr etwa?}
{202}{}{Wir, äh, arbeiten hier. Wir haben die Sensoren überprüft ...}
{203}{}{Hört auf, so zu tun. Ich habe alles gesehen.}
{204}{}{Hast du das? Na gut, ich tue einfach so, als wäre es so, wie du sagst. Einen schönen Tag noch.}

{205}{}{[Senkt beschämt den Kopf]}
{206}{}{Oh, jetzt bekommst du ein schlechtes Gewissen?}
{207}{}{Hey, werd jetzt nicht weich. Du kannst es doch immer noch bringen, oder?}

{208}{}{Als ob ... Wir wissen beide, dass körperlicher Kontakt verboten ist ... Aber ... Wir konnten einfach nicht widerstehen.}
{209}{}{Wie interessant. Das muss eine sehr ungewöhnliche Erfahrung sein. Erzähl mir davon.}
{210}{}{Ich habe dein Gejammer satt. Ich weiß, was ich mit Leuten wie euch mache.}

{211}{}{Wir wissen, wie hart die Strafe ist. Wir haben versucht, uns zu beherrschen! Aber wir konnten einfach nicht ... Vielleicht ... Vielleicht gehören wir einfach nicht in eine normale Gemeinschaft.}
{212}{}{Was weißt du über das Verbot körperlichen Kontakts?}
{213}{}{Warum konntet ihr euch nicht beherrschen?}
{214}{}{Was habt ihr aneinander gesehen?}
{215}{}{Wie oft hattet ihr körperlichen Kontakt?}
{216}{}{Wie konntet ihr nicht merken, dass ihr beobachtet werden könntet?}

{220}{}{[Steht stramm] Gemäß Richtlinie 16/8 des Regelwerks von Vault 8 zu gesellschaftlicher Interaktion und persönlicher Kommunikation ist körperlicher Kontakt zwischen zwei oder mehr Bürgern für einen Zeitraum von mehr als fünf Sekunden verboten. Jeder direkte Kontakt nackter Haut oder Körperteile gilt als körperlich. Ein Verstoß gegen diese Regel wird mit einem Jahr Isolation von der Gesellschaft bestraft.}
{221}{}{Ich weiß nicht, wie ich es erklären soll ... Wir fühlen uns zueinander hingezogen. Wir haben die Regel einmal versehentlich gebrochen. Und dann wollten wir immer mehr ... Und schließlich konnten wir nicht genug bekommen! Vielleicht ist es eine Art ansteckende Krankheit, wie eine Strahlenvergiftung.}
{222}{}{Es ist ... seltsam, aber unter unserer Kleidung haben wir ... Unterschiede. Jetzt verstehe ich, warum wir getrennte Duschen und Toiletten benutzen und in verschiedenen Zimmern im Schlafanzug schlafen müssen.}
{223}{}{In den letzten zwei Monaten, während wir die Sensoren am Außenbereich überprüft haben. Wir haben nur geschaut und angefasst! Ehrlich!}
{224}{}{Ich glaube, einer der Wachleute verdächtigt uns, aber nur bestimmte Bürger dürfen den Außenbereich verlassen. Wenn wir rausgehen, ist uns noch nie jemand gefolgt ... Nun ja, bis jetzt.}

{225}{}{Du wirst es den Wachen sagen, und dann werden wir isoliert, oder?}
{226}{}{Nein, zuerst möchte ich hören, wie ihr es so weit kommen lassen konntet.}
{227}{}{Ja, genau.}
{228}{}{Nein, ich lasse euch gehen ... Diesmal. Betrachtet euch als gewarnt.}

{229}{}{Ich wusste, dass das ein Fehler war! Wir müssen uns stellen, Emily. Die Wachen würden früher oder später von uns erfahren.}
{230}{}{Weiter, ich habe zu tun.}
{231}{}{Wirklich!? Du lässt uns gehen? Emily, wir haben Glück! Von jetzt an müssen wir vorsichtiger sein ...}
{232}{}{Ganz genau. Die Wachen haben immer ein Auge auf euch. Und jetzt zurück an die Arbeit.}
{233}{}{Genau! Und macht keinen Unsinn ...}

#Æåíñêàÿ ğåïëèêà
{1200}{}{[Sobald sie dich sehen, ziehen sie sich sofort wieder an] Oh, Bürger! Äh ... Darf man hier sein?}
{1203}{}{Hört auf, so zu tun. Ich habe alles gesehen.}