{100}{}{Du siehst einen Vault City-Wachmann.}
{101}{}{Du siehst einen Mitbürger, der den Eingang zur Stadt bewacht.}
{102}{}{Halt! Sofort!}

#Åñëè âèäèò ãåğîÿ â êîìáèíåçîíå ñ ÷åğåïîì
{110}{}{Gibt's jetzt schwarze Overalls?}
{111}{}{Was soll das Outfit?}
{112}{}{Ist das ein ... Schädel?}
{113}{}{So einen Overall habe ich noch nie gesehen.}
{114}{}{Ich hoffe wirklich, dass dieser Overall nicht aus dem Ödland stammt.}
{115}{}{Ich glaube, solche Kleidung habe ich schon an Außenstehenden gesehen.}

#Ïîïûòêà çàãîâîğèòü
{120}{}{Denk dran! Dienst garantiert die Staatsbürgerschaft!}
{121}{}{Brauchst du Hilfe?}
{122}{}{Tut mir leid, im Dienst darf ich nicht reden.}
{123}{}{Ich habe nichts zu melden ... jedenfalls nicht dir.}
{124}{}{Ich bin im Dienst.}
{125}{}{Stimmt etwas nicht, Bürger?}
{126}{}{Sei gegrüßt, Bürger.}
{127}{}{Bleib wachsam!}
{128}{}{Es lebe Vault City!}
{129}{}{Der Feind ruht nie. Wir müssen immer bereit sein.}
{130}{}{Harter Tag, Bürger?}

{200}{}{Bürger! Zurück in die Stadt! Sofort!}
{201}{}{Warum darf ich nicht weg?}
{202}{}{Du solltest wissen, dass gewöhnliche Bürger die Stadtmauern ohne Erlaubnis nicht verlassen dürfen. Hast du eine Erlaubnis?}
{203}{}{Äh, eine Erlaubnis?}
{204}{}{Wenn du die Stadt wirklich verlassen musst, sprich mit dem Sicherheitschef, Peter Graves. Wenn du einen guten Grund hast, stellt Graves dir eine Genehmigung aus.}
{205}{}{Verstanden.}
{206}{}{Na gut, ich gehe zurück in die Stadt.}

#Female character
{1120}{}{Denk dran! Dienst garantiert die Staatsbürgerschaft.}
{1121}{}{Brauchst du Hilfe?}
{1122}{}{Tut mir leid, im Dienst darf ich nicht reden.}
{1123}{}{Ich habe nichts zu melden ... jedenfalls nicht dir.}
{1124}{}{Ich bin im Dienst.}
{1125}{}{Stimmt etwas nicht, Bürger?}
{1126}{}{Sei gegrüßt, Bürger.}
{1127}{}{Bleib wachsam!}
{1128}{}{Lang lebe der Vault City!}
{1129}{}{Der Feind ruht nie, wir müssen immer bereit sein.}
{1130}{}{Harter Tag, Bürger?}
{1200}{}{Bürger! Geh sofort zurück in die Stadt!}
