{100}{}{Du siehst einen erschöpften, kräftigen Mann.}
{101}{}{Du siehst einen Mann, der wegen des harten Trainings kaum noch auf den Beinen stehen kann.}

#Ñ'àğ'îâàÿ âå'êà 
{110}{}{[Du siehst einen erschöpften Mann, der schwer atmet]}
{111}{}{Hallo!}

{112}{}{Hey, was ist los mit dir? Bist du im Ring zusammengebrochen?}
{113}{}{Hör mal, Freund, weißt du nicht, wie man sich, äh, sozusagen ohne Training auf einen Kampf „vorbereitet“? Na ja, du weißt schon, zum Beispiel mit Amphetaminen.}
{114}{}{[Lass ihn in Ruhe]}

#Ïğî 'ğåíèğîâêè
{115}{}{Coach ist ein echtes Monster, der hat mich völlig fertiggemacht. Er sagt, meine Ausdauer ist beschissen!}
{116}{}{Na ja, du siehst nicht gerade wie ein Schwächling aus. Sieh dir diese Bizeps an!}
{117}{}{Ich dachte auch, dass es reicht, ordentlich Muskeln aufzubauen! Und weißt du was? Zwei Jahre Training und keine verdammten Siege!}
{118}{}{Äh ... Nicht einen einzigen?!}
{119}{}{Die erste Runde im Ring gehört normalerweise mir, aber danach bin ich einfach völlig erledigt.}
{120}{}{Ach, daher weht also der Wind.}

{121}{}{Und dieser Trainer ist ein Tier! Er versucht, meine Ausdauer aufzubauen. Nach dem Training liege ich deshalb immer so da – auf der Matratze, unfähig, mich zu bewegen.}
{122}{}{Wie wär's mit Amphetaminen? Psycho zum Beispiel. Das könnte helfen.}
{123}{}{Lass mich dich massieren! Danach fühlst du dich besser, wirst schon sehen.}
{124}{}{Na gut. Dann lasse ich dich mal in Ruhe.}

#Ìàññàæ
{125}{}{Ein Mann soll mich anfassen? Niemals! Hände weg!}
{126}{}{Ach, komm schon! Ich frage doch nur ...}
{127}{}{[Lächelnd] Wow! So eine Schönheit will mich begrapschen? Nur zu, Baby! Endlich!}
{128}{}{Großartig! Dreh dich um, Champion!}
{129}{}{Äh ... Nein. Ich hole erst ... Äh ... die Salbe. Ja. Warte einfach kurz.}
{130}{}{Nö! Mit deinen Händen wirst du mich schlimmer quälen als der Trainer!}
{131}{}{Wie du willst.}
{132}{}{Oh! Was für ein Hochgefühl!!}
{133}{}{Du hast den Kämpfer eine Stunde lang massiert. Der Kunde ist bestimmt zufrieden.}

#Ïğî äóğü
{134}{}{Weißt du, ich habe das Zeug ausprobiert. Der Trainer hat schon recht: Lieber im Training noch härter ranklotzen, als draufzugehen.}
{135}{}{Draufgehen?}
{136}{}{Ha! Was hast du denn erwartet?! Ein bisschen Stoff nehmen und schon gehört dir der Ring? Weißt du, wie viele von unseren Jungs an dem Zeug draufgegangen sind?}
{137}{}{Wie?}
{138}{}{Das Herz! Es macht einfach schlapp, wenn du es im Ring oder beim Training übertreibst. Das Zeug ist Muell. Denk nicht mal dran.}
{139}{}{Und trotzdem weißt du, wo man welches bekommt, oder?}
{140}{}{Na gut.}

{141}{}{Weiß ich nicht! Lass mich los, du verdammter Junkie! Verpiss dich! [Die Augen des Kämpfers funkeln vor Wut. Sieht aus, als würde ihm dieses Gespräch wirklich nicht gefallen.]}
{142}{}{Du weißt es doch! Sag's mir!}
{143}{}{Schon gut, Kumpel. Beruhig dich.}

{144}{}{Ich sag's dir, weil ich sehe, dass du einer von uns bist.}
{145}{}{Komm schon, ich verrate es niemandem. Darauf kannst du dich verlassen.}
{146}{}{Irgendwo außerhalb der Stadt gibt es ein großes Labor. Das Black Caravan, wie wir es nennen, fährt alle zwei Tage dorthin. Es kommt unauffällig zum Parkplatz hinter dem Büro und verkauft Drogen. So kommt das Zeug in die Stadt. Früher habe ich mit ihnen gedealt, aber dann habe ich aufgehört. Vielleicht sind sie inzwischen schon woanders hingezogen, ich habe keine Ahnung.}
{147}{}{Okay, danke für die Auskunft. Genau das habe ich gebraucht.}

{148}{}{Ein Dankeschön in anderer Form wäre netter. He-he.}
{149}{}{Ach ja, hier sind 50 Kröten für die Info.}
{150}{}{Nimm dir ein Bier und entspann dich ein bisschen.}
{151}{}{Hmm. Na gut, hier ist eine Flasche Cola zur Erfrischung.}
{152}{}{Tut mir leid, ich habe nichts dabei. Ich bringe später etwas vorbei.}

#Ïğî ğàñïèñêó íà ïîäëîã âûğîäêîâ
{153}{}{Ähm, hör mal, was glaubst du, warum die Sklavenhändler den Freaks etwas anhängen wollten?}
{154}{}{Was?}
{155}{}{Der Anführer von Sklavenstadt hat jemanden angeheuert, der den Freaks Drogen unterschiebt.}
{156}{}{Ach ja, das ist offensichtlich.}
{157}{}{Wirklich?}
{158}{}{Und wie! Begreifst du es nicht? Der Anführer will einen Anteil an den Einnahmen des Hoover dam. Und der Staudamm braucht Arbeiter. Ich weiß nicht genau, worum es bei dem Deal geht, aber ich glaube, der Anführer versucht, seine Sklaven an den Staudamm zu verkaufen. Bob Neil gefällt das natürlich nicht und sucht nach Alternativen. Also muss der Anführer beschlossen haben, dass man sich um die Freaks kümmern sollte, damit dem Besitzer des Staudamms nichts anderes übrig bleibt, als Sklaven zur Arbeit anzunehmen. Sonst bekommt er kein Geld.}
{159}{}{Woher bekommen sie das Zeug? Weißt du etwas darüber?}
{160}{}{Hmm. Ein interessanter Gedanke. Ich werde ihn mir merken.}

{161}{}{Ach, darum geht es also! Warum hast du das nicht gleich gesagt? Warum überhaupt mit dem Bob Neil anfangen?}
{162}{}{Kein besonderer Grund ... Na, zum Teufel mit ihnen. Wie sieht es also mit Amphetaminen aus?}