{100}{}{Du siehst einen Empfangschef.}
{101}{}{Das ist der Empfangschef des Sklavenrings und nebenbei auch Barkeeper.}

{110}{}{Komm rein. Der Ring ist in dem Saal dort drüben.}
{111}{}{Gib mir etwas zu trinken.}
{112}{}{In Ordnung.}
{113}{}{Das reicht. Wenn du dich übergeben musst, geh nach draußen. Verstanden?}
{114}{}{Ich brauche noch einen Drink.}
{115}{}{In Ordnung.}

{116}{}{Hast du von den Sklavenhändlern gehört?}
{117}{}{Ja. Ich kann mir nicht vorstellen, wer so etwas tun würde. Aber ich mache mir mehr Sorgen darum, was jetzt mit dem Ring passiert. Ich nehme an, der Besitzer wird den Betrieb fortführen, aber ohne Sklaven unter den Kämpfern. Nur noch freie Menschen. Ehrlich gesagt ist das gar nicht schlecht.}