{100}{}{Du siehst einen Trainer.}
{101}{}{Du siehst einen Trainer. Hinter seiner ernsten Miene erkennst du einen verborgenen Durst nach Blut.}
{102}{}{Gut. Aber ich muss los.}

#Starting dialogue branch
{109}{}{[Schüttelt zustimmend den Kopf] Schön, dich zu sehen. Du bist mein ganzer Stolz.}
{110}{}{Noch ein Star? [mustert dich von Kopf bis Fuß]}
{111}{}{Sprich. Ich höre zu.}

{112}{}{Bist du Trainer? Bringst du mir die Kunst des blutigen Kampfes bei?}
{113}{}{Ich brauche noch eine Trainingseinheit. Hier sind 1000 Dollar.}
{114}{}{Ich brauche nichts.}

#First workout
{115}{}{Meine Zeit ist Geld. Für ein Training verlange ich 1000 Dollar.}
{116}{}{Ich habe das Geld. Fangen wir gleich an?}
{117}{}{Verstehe. Ich komme wieder, wenn ich mich fürs Training entschieden habe.}
{118}{}{Los! Ab unter die Dusche! Bewegung!}
{119}{}{Jawohl, Sir!... Äh, wo ist die Dusche?}

#Intermediate workouts
{120}{}{Du solltest nicht so oft trainieren. Komm morgen wieder, wenn du wieder zu Kräften gekommen bist.}
{121}{}{Du weißt es besser, Trainer.}
{122}{}{Tut mir leid, aber ich kann dir nichts mehr beibringen. Du bist erwachsen und jetzt auf dich allein gestellt. Dein nächster Lehrer ist der Ring, nicht das Fitnessstudio.}
{123}{}{Na gut, Trainer, wenn du meinst ...}

#Info-messages after training
{124}{}{Nach der fünften Trainingseinheit hast du endlich Fortschritte gemacht. Deine Nahkampf-Fertigkeit ist um 5 gestiegen%!}
{125}{}{Du hast bereits deine zehnte Trainingseinheit absolviert, und die ist nicht ohne Wirkung geblieben. Deine Nahkampf-Fertigkeit ist um 5 gestiegen%!}
{126}{}{Deine harte Arbeit war nicht umsonst. Nach der fünfzehnten Trainingseinheit ist deine Nahkampf-Fertigkeit um 5 gestiegen%!}
{127}{}{Das war dein zwanzigstes Training! So viel Fleiß war nicht umsonst. Deine Waffenlos-Fertigkeit ist um 5% gestiegen.}
{128}{}{Das war dein letztes Training. Deine Waffenlos-Fertigkeit ist um 5% und deine Stärke um 1 gestiegen!}
{129}{}{Das war ein ganz normales Training. Aber die Ergebnisse sind noch nicht sichtbar. Du musst weiter trainieren.}

#After the last training session
{130}{}{Großartig, Champion! So viel Fleiß, so viel Ausdauer ... Wer hätte das gedacht? Bisher hat niemand solch lange Übungen durchgehalten. Ich bin stolz auf dich! Aber ... Weißt du, ich habe dir alles beigebracht, was ich konnte. Als Nächstes musst du allein weiterlernen.}
{131}{}{Danke, Coach. Für alles.}
{132}{}{Wow! Was für eine Technik! Aber ich kann dir nicht helfen. Ich habe noch nie mit einem so guten Kämpfer gearbeitet.}

#Floating phrases, if you stand in the middle of the small ring
{133}{}{Hör auf, hier herumzutanzen! Was soll das für eine Bewegung sein? Das ist der Ring, verdammt noch mal, nicht die Tanzfläche!}
{134}{}{Gut gemacht, du tanzt hübsch. Wäre besser, wenn du im Ring genauso tanzen würdest. Ha-ha-ha!}
{135}{}{Nein, Champion. Dein Platz ist im großen Ring und nicht auf dieser Tanzfläche.}
{136}{}{Äh ... Redest du mit mir?}

{137}{}{Deine harte Arbeit war nicht umsonst: Deine Waffenlos-Fertigkeit ist um 5% gestiegen!}
{138}{}{Nach all den anstrengenden Übungen ist deine Stärke gestiegen.}

#Women's replics
{1122}{}{Tut mir leid, aber ich habe dir nichts mehr beizubringen. Du bist erwachsen geworden und musst jetzt allein zurechtkommen. Deine zukünftige Schule ist der Ring, nicht das Fitnessstudio.}
{1130}{}{Großartig, Champion! So viel Fleiß, so viel Ausdauer ... Wer hätte das gedacht? Bisher hat niemand solch lange Übungen durchgehalten. Ich bin stolz auf dich! Aber ... Weißt du, ich habe dir alles beigebracht, was ich konnte. Als Nächstes musst du allein weiterlernen.}
