{100}{}{Du siehst Big Louie!}
{101}{}{Heilige Scheiße! Das ist Big Louie! Er hat es in Vegas tatsächlich zu Ruhm gebracht!}

#Îòâåòíûå ğåïëèêè äëÿ Æ è Ì
{102}{}{Hey, seht mal, wer da ist! Einen kräftigen Applaus für meinen alten Freund! Ohne ihn wäre ich nicht hier!}
{103}{}{Wir haben viel zusammen erreicht, aber er hat keine Zeit, dir die Einzelheiten zu erzählen ... Keine Zeit, sagte ich!}
{104}{}{Hey, seht mal, wer da ist! Einen kräftigen Applaus für meine alte Freundin! Ohne sie wäre ich nicht hier!}
{105}{}{Wir haben viel zusammen erreicht, aber sie hat keine Zeit, dir die Einzelheiten zu erzählen ... Keine Zeit, sagte ich!}

{106}{}{Ich freue mich, dich zu sehen, aber ich muss gleich auf die Bühne. Wir reden später.}
{107}{}{Die Vorstellung ist gerade zu Ende! Gib mir eine Minute.}

#Äèàëîã
{110}{}{Hey, Bruder! Schön, dich zu sehen! Wir haben seit diesem Indianerlager einen weiten Weg zurückgelegt, was?}
{111}{}{Big Louie! Du scheinst dich gut zu machen.}
{112}{}{Mir geht's großartig! Anfangs habe ich es fast bereut, diese Cheyenne-Schlucht verlassen zu haben. Ich wurde gefürchtet und respektiert. Aber hier haben mich die Eliten ... akzeptiert. Zum ersten Mal fühle ich mich *gebraucht* ... Ich hätte nie gedacht, dass ich es so weit bringen würde. Und das verdanke ich alles dir. Apropos: Du siehst ziemlich mitgenommen aus ...}
{113}{}{Ich hatte viel zu tun. Manchmal habe ich das Gefühl, jeder, mit dem ich rede, hat gleich einen neuen Auftrag für mich. Wie auch immer, können wir reden?}
{114}{}{Für dich habe ich immer Zeit ... wenn ich nicht gerade auf der Bühne stehe.}
{115}{}{Ich muss los. Wir reden später.}
{116}{}{Schön, dich gesehen zu haben. Das hat mir gefallen.}
{117}{}{Viel Glück.}

{118}{}{Schlechte Nachrichten. Alle aus deiner Bande sind tot.}
{119}{}{Ich hab mich schon gefragt, warum sie so still waren ... Nun, jetzt gibt's kein Zurück mehr. Keine Sorge, ich bin nicht sauer. Ich mochte diese Hunde sowieso nicht.}
{120}{}{Ripper wird langsam unberechenbar. Was sollen wir tun, Boss?}
{121}{}{Der Ripper? Als ich das Sagen hatte, war er nützlich ... an seinem Platz. Aber zum Anführer taugt er nicht. Keine Sorge, die machen sich früher oder später selbst fertig.}
{122}{}{Er will deinen Platz einnehmen. Er sagt, du seist weich geworden, und ...}
{123}{}{Reden wir über etwas anderes.}
{124}{}{Hmm. Lassen wir's dabei.}

{125}{}{Weich? ICH?! Ich habe die ganze Bande durchgefüttert, als er noch an der Brust seiner Mutter hing! Der sollte sich mal ... [Er bricht ab und holt mehrmals tief Luft]}
{126}{}{[Lass ihn sich beruhigen.]}
{127}{}{Ich lasse mich nicht wieder auf ihr Niveau herab. Aber Ripper muss weg. Ich gebe dir 1000 Dollar – kauf dem Händler draußen beim Café etwas Gift ab oder einfach Munition für deine Waffe. Ich werde nicht zurückgehen, also liegt es an dir, wie du das Problem löst. Keine Sorge – ich weiß, dass du das hinkriegst.}
{128}{}{Alles klar, Boss.}
{129}{}{}

{130}{}{Kommst du irgendwann zurück?}
{131}{}{Ich habe darüber nachgedacht. Aber mein Terminkalender ist hier für die nächsten paar Monate randvoll. Falls ich jemals zurückgehe, dann nicht so bald.}
{132}{}{Wie viel Geld verdienst du mit deiner Show?}
{133}{}{Viel weniger als damals mit der Gang. Heutzutage kann man so nicht viel Geld verdienen. Aber es gibt ... andere Vorteile.}
{134}{}{Wann ist deine nächste Show?}
{135}{}{Heute Abend, nach sechs. Du solltest sie dir ansehen. Das wird lustig!}

#########################################################################
#
#   Ïåñíè Áîëüøîãî Ëóè, âåğñèÿ äëÿ FoN 1.0.
#
#   Àâòîğ òåêñòîâ - Àëåêñàíäğ Àãàôîíöåâ (Kerb)
#	So, I changed it for metalocalypse lyrics, and maybe Weird Al's. Because relevance. Sorry.
#########################################################################

{200}{}{Mögt ihr Kaffee?~}
{201}{}{Echten Kaffee}
{202}{}{Aus den Hügeln}
{203}{}{Kolumbiens?~}

{204}{}{Hey, du! Hast du dir etwa schon ein Grab ausheben lassen oder was? Tanzt, ihr Trottel, ihr seid in der besten Bar des Ödlands – weil ich hier bin!}

{205}{}{~Die Duncan Hills werden dich wecken~}
{206}{}{~Aus tausend Toden,}
{207}{}{~Eine Tasse schwarzen Blutes}
{208}{}{~Sterben, sterben ... Du stirbst für eine Tasse~}

{209}{}{Hey! Du, Arschloch da rechts! Leg das zurück! Meine Jungs würden dir dafür die Hand abhacken, in unserer Gan- ich meine, in unserer Jazz-Gan- äh, Jazzband. Du weißt schon ... }

{210}{}{~Guatemala-Mischung, äthiopisch,}
{211}{}{Französische Vanille-Röstung~}
{212}{}{Sterben, sterben~}
{213}{}{Du stirbst für eine Tasse!}

{214}{}{Mach dich bereit für den ultimativen Geschmack! Jetzt bekommst du was ... Und schrei – nach deiner Sahne!}

{215}{}{Duncan Hills,}
{216}{}{Duncan Hills~ }
{217}{}{Duncan ... Hills ...}
{218}{}{Kaffee! Jaaaaaa!}

{219}{}{Ja, das Leben ist großartig, sogar mit euren hässlichen Fratzen ... Heh, JK LOL. Ihr seid das beste Publikum, das ich je hatte! Machen wir etwas völlig anderes –}

{220}{}{~Musta-Krakish, Musta - Krakish!~}
{221}{}{Die Zeit ist gekommen, ihn zu erwecken~}
{222}{}{Ich rufe die uralten Herren der Unterwelt an, }
{223}{}{~Um dieses Biest hervorzubringen und –}

{224}{}{Kommt schon, Jungs und Mädels! Wir haben die Apokalypse doch schon hinter uns! Wovor sollten wir also noch Angst haben? Singt mit mir!}

{225}{}{Erwache, erwache, erwache, erwache~}
{226}{}{Nimm das Land, das genommen werden muss~}
{227}{}{Erwache, erwache, erwache, erwache~}
{228}{}{~Verschlinge Welten, zerschmettere die Verdammten!}

{229}{}{Übrigens, meine Damen, ihr könnt die Herren zum Tanzen auffordern! Falls sie noch dazu in der Lage sind ...}

{230}{}{~Erhebe dich aus deinem tausendjährigen Schlaf,}
{231}{}{~Brich für alle Ewigkeit aus deinem Grab hervor~}
{232}{}{~Ich befehle dir ...}
{233}{}{~Erhebe dich! Erhebe dich! Erhebe dich! Erhebe dich!~}

{234}{}{Ja, ja, ich hab meine Zeit mit allen möglichen inneren Kämpfen verbracht, wisst ihr ... Wie jeder andere Künstler auch!}

{235}{}{~Ich bin der Beschwörer der Dämonen,}
{236}{}{Ich bin der Vater eures Todes~}
{237}{}{Ich rufe das uralte Böse herbei,}
{238}{}{~Ich kontrolliere jeden seiner Atemzüge.~}

{239}{}{Ich hatte mal einen ... Äh ... Kumpel, äh ... Schlagzeuger, der jeden fertig machen konnte ... Wie eine französische Baiser! Natürlich beim Kartenspiel! Dann traf er auf einen "größeren Fisch" ...}

{240}{}{~Ich bringe dein Unglück über dich ...~}
{241}{}{Mit der Geburt von Trollkillern!!}
{242}{}{Ich erwecke Armageddon!}
{243}{}{~Ich nähre mich von tausend Seelen~}

{244}{}{Vergesst nicht, den Cocktail des Tages zu probieren! Zwei zum Preis von einem! Passt hervorragend zu eurem Fusel! Also, wo waren wir ... Ach ja! Das nächste Lied!}

{245}{}{Ich will mit den Gangstern abhängen~}
{246}{}{~Doch bisher halten sie mich alle für zu weiß und nerdig~}
{247}{}{~Sie denken, ich bin einfach zu weiß und nerdig, ja, ich bin einfach zu weiß und nerdig,}
{248}{}{Ihr seht, ich bin weiß und nerdig - seht her, ich bin weiß und nerdig!~}

{249}{}{Ja, meine lieben Alkoholiker, Junkies und Liebhaber billiger Huren! Lauscht her - jetzt kommt wahres Können!}

{250}{}{War Klassenbester am MIT, hab Champion-Skills in D&D,}
{251}{}{M.C. Escher, mein Lieblings-M.C. - Behalt dein Forty, ich nehme einfach einen Earl Grey,}
{252}{}{Meine Felgen drehen sich nie, im Gegenteil, sie stehen still, wie du sehen wirst,}
{253}{}{Alle meine Actionfiguren sind tipptopp, Stephen Hawking steht in meiner Bibliothek~}

{254}{}{Ich möchte, äh, MTV danken, dass sie mir diese Chance geben ... Moment mal, was? Weiter geht's!}

{255}{}{~Holt eure Handtücher raus, gleich geht's ab~}
{256}{}{~Alle hier im Raum, verdammt noch mal auf den Boden~}
{257}{}{~Aber bleibt verdammt noch mal auf Zack~}
{258}{}{Big Louie ist am Start - los geht's!~}

{259}{}{Autotune wäre jetzt echt klasse, im T-Pain-Stil! Aber wir sind in der Postapokalypse, also machen wir mit dem weiter, was wir haben!}

{260}{}{Ich bin auf einem Boot - ich bin auf einem Boot! Auf einem Boot - ich bin auf einem Boot!}
{261}{}{Alle sehen mich an, denn ich segle auf einem Boot!}
{262}{}{Ich bin auf einem Boot - ich bin auf einem Boot! Auf einem Boot - ich bin auf einem Boot!-}
{263}{}{Schaut euch dieses verdammte Boot ganz genau an!!}

{264}{}{Also, wirklich ein riesiges Dankeschön an diese Leute, die uns heute begleiten! Wir freuen uns, dass ihr dabei wart, und werden euch immer in Erinnerung behalten!}

{265}{}{Johny-17, Drobovik, .Pixote., Risewild, Sagez, Matt Drax,}
{266}{}{theslitherydeee, gorlomi, Vault15, dozen, xps, Muttie,}
{267}{}{heatEXTEND, Reikis, Navarrrro, der RetrospectiveGaming-Kanal auf YouTube,}
{268}{}{außerdem TheChosen1 und 0wing - danke, Jungs, dass ihr von Anfang an dabei wart}

{269}{}{Der größte Dank geht an den großartigen und unglaublichen Foxx, den fantastischen _Pyran_ und Snikers, die alle eine enorme Menge Arbeit geleistet haben.}

{270}{}{Und natürlich ein großes Dankeschön an den Ideologen und das Herz des Übersetzungsprojekts - Dionis.}
{271}{}{Danke, dass du rund zwei Jahre deines Lebens und so viel Leidenschaft hineingesteckt hast.}
{272}{}{Ein großes Dankeschön an alle Spieler und das nma-fallout.com-Forum für jeden Durchlauf und jede Rückmeldung zu Fehlern.}
{273}{}{Der letzte Schnitt von Keyboard Gecko. Scheiße, ich hab das Originalteam vergessen! Danke, Leute! Und ganz besonders dir, BlackDesigner. Haltet Ausschau nach Fallout:Sonora. Viel Glück dabei.}

# Íåèñïîëüçîâàííûé òåêñò:

{274}{}{Deine Mutter, diese schwangere Hyäne,}
{275}{}{Die müsste man zurichten, bis alles blutrot ist,}
{276}{}{Unsere armselige Küche und das Kinderzimmer, wo ihr Schädel steht,}
{277}{}{Anstelle des Nachttopfs, hoffe ich, werde ich sie aufstellen,}

{278}{}{Und schade, dass ich deinen Vater zerschnitten habe}
{279}{}{In ungefähr zwanzig Stücke – ich würd's gern noch mal sehen! –}
{280}{}{Schon ein Jahr ist es her, und die Schakale haben ihn verschleppt,}
{281}{}{Mein „Zerstückler“ rostet ohne Blut vor sich hin ...}

{282}{}{Auch dein Cousin mit seiner feministischen Frau ...}
{283}{}{Die Frage nach ihnen stellt sich mir nicht mehr ...}
{284}{}{Ach, wie schön sie in Stücke gerissen wurden!}
{285}{}{Gelobt seist du, Nobel, für dein Dynamit!}

{286}{}{Du hast immer weniger Verwandte, und es wird immer besser}
{287}{}{Ich liebe dich, das Leben ist leicht und schön!}
{288}{}{Merk dir das, mein Freund, damit du dir die Mühe sparst:}
{289}{}{Vergewissere dich zuerst, dass sie eine Waise ist!}

#Æåí ğåïëèêè
{1110}{}{Hey, Schwester! Schön, dich zu sehen! Wir haben seit dem Indianerlager einen weiten Weg zurückgelegt, nicht wahr?}
