{100}{}{Du siehst einen Händler.}
{101}{}{Du siehst eine Straßenhändlerin. Mit ihrem bäuerlichen Aussehen und ihrer schäbigen Kleidung sticht sie aus ihrer Umgebung hervor.}
{102}{}{Wenn du hier bist, um mich zu belästigen, rufe ich die Polizei!}
{103}{}{Bitte komm mir nicht näher! Ich will keinen Ärger!}

{110}{}{[Als eine Straßenhändlerin sieht, wie du dich näherst, bemüht sie sich, auf ihrem müden, sonnengebräunten Gesicht ein Lächeln zustande zu bringen.] Hallo! Sandwiches, heiß und lecker!}
{111}{}{Wie viel kostet ein Sandwich?}

{112}{}{35 $. Ich nehme nur Bargeld.}
{113}{}{Hier ist das Geld. Gib mir eins.}
{114}{}{Äh, ein andermal. Tschüss.}
{115}{}{Auf Wiedersehen.}

{116}{}{Na, das ist ja toll, aber können wir uns einfach unterhalten?}
{117}{}{Möchtest du ein Sandwich? Der Preis ist unverändert: 35 $.}

{118}{}{[Stellt geschickt ein frisches Sandwich für dich zusammen] Bitte sehr. Möchtest du noch eins?}
{119}{}{Ja, bitte.}
{120}{}{Aber das reicht nicht ... Sieh mal, dieser Job ist schon anstrengend genug. Ich kann nicht einfach Essen verschenken.}
{121}{}{Ich verstehe ...}
{122}{}{Na gut. Gib mir jetzt ein Sandwich.}

#Chatter
{150}{}{[Ihr Blick wirkt besonders müde] Plaudern ... Worüber denn?}
{151}{}{Andererseits, gib mir dein Markensandwich. Hier sind 35 $.}
{152}{}{Ich plaudere später mit dir. Jetzt muss ich los.}

{153}{}{Du wirkst sehr müde. Handelst du schon eine ganze Weile?}
{154}{}{Ja ... Ich faulenze hier nicht, ich arbeite. Ich muss zwölf Stunden am Tag arbeiten, nur um mir das Recht zum Handeln leisten zu können.}
{155}{}{Das Recht zum Handeln ... Moment, was ist denn das?}
{156}{}{So läuft das hier. Die Clean City kassiert Gebühren dafür, dass man hier Waren verkaufen darf. Die sind ziemlich hoch ... Nein, ehrlich gesagt ist das schlicht Raub. Aber ich habe keine Wahl.}
{157}{}{Warum denn?}
{158}{}{In der Clean City musst du dir keine Sorgen um die Sicherheit machen, die Polizei sorgt für Ordnung. Außerdem gibt es dort mehr Leute, und sie sind wohlhabender, also verdient man mehr. Aber darum geht es gar nicht. Mein Vater hat mit dem Rathaus einen Deal zur Wiederherstellung der Farm gemacht. Und jetzt müssen wir unseren Teil beitragen. Wir müssen ihre unmenschlichen Bedingungen hinnehmen.}

{159}{}{Der Deal? Erzähl mir mehr. Und was haben diese „unmenschlichen Bedingungen“ zu bedeuten?}
{160}{}{Nun ... [seufzt] Mein Vater hatte eine Farm, aber nachdem er bankrottgegangen war, bat er das Rathaus um Hilfe. Man gewährte ihm einen Kredit, den er mit Zinsen zurückzahlen sollte. Aber der Zinssatz ist einfach grauenhaft! Und für jeden Tag, den die Zahlung sich verzögert, steigt er weiter. Doch die Sesselfurzer im Rathaus könnten sich darüber kaum mehr freuen, denn man könnte sagen, dass ihnen jetzt alles gehört: wir und die Farm.}

{161}{}{Was für eine Ungerechtigkeit. Vielleicht würde dir jemand im Rathaus einen Aufschub gewähren? Zum Beispiel eine Nachfrist.}
{162}{}{Unwahrscheinlich. Kennst du dort jemanden? Wenn du es wüsstest, würdest du verstehen. Diese Witzfiguren haben seit gut einem Dutzend Jahren die Stadt nicht mehr verlassen. Sie wissen nicht, wie hart das Leben im Ödland ist. Ganz abgesehen davon, dass es ihnen egal ist. Sie sind es ohnehin schon gewohnt, andere herumzukommandieren.}
{163}{}{Was ist mit der Farm passiert?}
{164}{}{Zuerst wurden wir von den Nagern überfallen, dann kamen die richtigen Räuber, und danach kam der Hurrikan. Die Scheune wurde in Stücke gerissen, von den Feldern ganz zu schweigen. Damals konnten wir kaum einen Sack Mais zusammenbekommen. Jetzt müssen wir alles wiederaufbauen: die Gebäude und die Plantage.}
{165}{}{Wie soll dir der Handel hier bei der Ernte dort helfen?}
{166}{}{Wir haben eine große und starke Familie. Während die Männer im Ödland arbeiten, werde ich hierher geschickt, um Handel zu treiben. Wir brauchen jede Menge Zeug. Manchmal kann man mit den Schürfern ein Geschäft machen, aber sie sind keine besonders angenehmen Leute. Sie könnten dich übers Ohr hauen.}

{167}{}{Wollen wir uns noch ein bisschen unterhalten?}
{168}{}{}
{169}{}{Erzähl mir etwas über deine Familie.}
{170}{}{Nun, wir haben eine große Familie und leben auf einer Farm außerhalb der Stadt. Die letzten zehn Jahre haben wir Landwirtschaft betrieben. Was gibt es sonst noch zu erzählen?}
{171}{}{Die letzten zehn Jahre? Und davor?}
{172}{}{Drei oder vier Jahre lang sind wir umhergezogen. Wir kamen aus dem Süden. Das Leben dort war hart, also mussten wir unsere Heimat verlassen. Als wir nach Vegas kamen, war der Ort ein richtiges Loch. Nichts Besonderes – kein Strom, kein Kasino. Aber in zehn Jahren hat sich die Stadt gewaltig verändert.}
{173}{}{Moment mal, wie konnte all dieser Prunk in so kurzer Zeit entstehen?}
{174}{}{Mit Sklavenarbeit natürlich. Die Sklaven wurden in großen Scharen hierhergebracht, damit sie die Stadt wiederaufbauen konnten. Das war eine Menge harte Arbeit. Aber sieh dir das Ergebnis an!}

{175}{}{Warum nimmst du nur Geld?}
{176}{}{Ich muss den Kredit abbezahlen, also muss ich die Lebensmittel in Geld umwandeln. Das Rathaus nimmt schließlich keine Sandwiches als Zahlungsmittel, weißt du.}

#Cart
{180}{}{Was für einen schicken Karren du hast.}
{181}{}{Ja. Früher wurden solche Wagen von den Händlern benutzt, die Hotdogs verkauften, und jetzt gehört er mir. Meine Brüder haben ihn in den Ruinen der alten Stadt gefunden und dann repariert und neu gestrichen. Ziemlich praktisch, wenn nur dieses verdammte Rad nicht wäre ...}
{182}{}{Ja, mir ist aufgefallen, dass der Wagen schief steht. Vielleicht kann ich ihn reparieren.}
{183}{}{Na ja, du kannst es versuchen. Wenn du ihn reparierst, gebe ich dir ein Sandwich. Mach ihn bloß nicht ganz kaputt!}
{184}{}{Ich versuch's.}

{185}{}{Jetzt ist mit dem Wagen alles in Ordnung.}
{186}{}{Allerdings! Vielen Dank. Hier, nimm das, frisch gemacht und noch ganz heiß.}
{187}{}{Gern geschehen.}

{188}{}{Reden wir über etwas anderes.}

#Main quest
{190}{}{Ich konnte einen Aufschub für deinen Kredit herausholen.}
{191}{}{Wirklich!? Was für eine Überraschung ... Das kam uns so gelegen! Ich weiß gar nicht, wie ich dir danken soll. Vielleicht kann ich dir ein Sandwich spendieren.}
{192}{}{Du brauchst dir keine Sorgen zu machen. Was das Sandwich angeht – das nehme ich.}
