{100}{}{Du siehst einen Raucher.}
{101}{}{Nur ein Raucher. Er versucht sich zu entspannen und achtet auf nichts.}

{102}{}{[Der Wäscher sieht dich nicht einmal an und achtet auf nichts.]}
{103}{}{Hey, du! Sag mir, wo das Labor ist! Ich weiß, dass ihr irgendwie damit zu tun habt!}
{104}{}{[Lass den Raucher in Ruhe]}

{105}{}{Heilige Scheiße ... Selbst ich bedränge die Leute nicht so sehr!}
{106}{}{Red schon, du verdammter Hurensohn!}
{107}{}{Du bist nutzlos. Ich sollte lieber gehen.}

{108}{}{Warum bist du so wütend? Siehst du nicht, dass ich bekifft bin? Mir geht's gut. Also verpiss dich.}
{109}{}{Wenn du nicht sofort antwortest, male ich dir das Gesicht voll!}

{110}{}{Ach, leck mich!}
{111}{}{[Packt ihn am Kragen] Das reicht, Miststück, du hast es so gewollt!}
{112}{}{Na gut, ich hör auf.}

{113}{}{Hey! Ganz ruhig!}
{114}{}{Ich prügle die Information mit diesen Fäusten aus dir raus! Also sag's lieber!}
{115}{}{Tut mir leid, ich hab überreagiert.}

{116}{}{Verdammt, wo kommen solche Arschlöcher überhaupt her?! Ich weiß nichts von irgendwelchen Laboren!}
{117}{}{Du lügst!!! Hier ist eine Notiz über die Freaks! Was zur Hölle geht hier vor? Sag's mir!}

{118}{}{Na ja ... Verdammt! Also gut, es war so – einmal kam irgendein Schleimer aus dem Rathaus hierher! Er wollte die Freaks aus der Stadt vertreiben! Also haben wir einen Jungen angeheuert, der ihnen die Drogen untergeschoben hat. Mehr weiß ich nicht! Ich schwör's!}
{119}{}{Wer war dieser Schleimer?!}

{120}{}{Woher zum Teufel soll ich das wissen! Es war dunkel! Der Deal fand nachts am Stadtrand statt ...}
{121}{}{Und wer wurde für den Job angeheuert?}

{122}{}{Nur irgendein Junge. Er ist schon ... erledigt ...}
{123}{}{„Erledigt“ was?!}

{124}{}{Man hat ihn beseitigt, du Holzkopf! Und dich wird's genauso treffen, wenn du weiter Ärger suchst!}
{125}{}{[Verpasst dem Mistkerl eine Ohrfeige] Ach ja? Hä?!}

{126}{}{AU! Du Arschloch, meine Kumpels sind gleich um die Ecke, also hör sofort auf, du!}
{127}{}{Deine „Kumpels“ hören dich von hier aus nicht!}

{128}{}{[Versucht zu fliehen] Was zum Teufel willst du von mir?! Ich bin nur ein einfacher Sklavenhändler!}
{129}{}{Labor! Wo ist es?! Antworte mir, du Dreckskerl!}

{130}{}{NEIN! Du Idiot! Die bringen uns beide um, begreifst du das nicht?!}
{131}{}{Ich hab genug davon! [tritt ihm in die Eier]}

{132}{}{Aaaargh ...}
{133}{}{[Schlägt ihm ins Gesicht]}

{134}{}{Aaghh! ...}
{135}{}{Reicht dir das, du kleine Schlampe?! Willst du noch mehr?!}

{136}{}{Oh ... ich wollte doch nur eine rauchen ... Verdammt!}
{137}{}{[Ihm mit dem Ellbogen in die Zähne schlagen]}

{138}{}{TPhh ... Du verdammte SCHLAMPE!!! MEINE BRÜDER WERDEN ...}
{139}{}{Hast du deine Meinung immer noch nicht geändert, hm?!}

{140}{}{Lass mich in Ruhe, du Schwein! ...}
{141}{}{[Noch einmal zuschlagen]}

{142}{}{Mmm ... Süßer Schmerz ...}
{143}{}{Gefällt's dir? Na, noch eine Runde, hm?}

{144}{}{NEIN! Genug! Ich erzähle dir alles!}
{145}{}{Bitte, mach weiter.}

{146}{}{Es ist ... Es ist außerhalb der Stadt ... Verdammt, der Ort ist eine Festung! Du wirst erschossen, sobald man dich sieht!}
{147}{}{Wo ist es?}

{148}{}{Im Süden, an der Fernstraße ... Wenn du aus der Stadt kommst ... zeige ich es dir ...}
{149}{}{Zeig es mir auf der Karte!}
{150}{}{Bring mich hin!}
{151}{}{Wie kommt man unbemerkt hinein?}

{152}{}{Da ist eine Karawane ... "Black Caravan" ... Sie schmuggeln für uns Drogen ...}
{153}{}{Wo sind sie?}

{154}{}{Auf dem Parkplatz für die Karawanen, neben dem Büro ... Sie fahren alle zwei Tage hin und her ...}
{155}{}{Großartig! Dann kann ich ihnen folgen.}

{156}{}{Also, du hast bekommen, was du wolltest, was, Bruder?! Lässt du mich jetzt endlich gehen?}
{157}{}{Hör zu, du Arsch! Wenn du jemals was erzählst ...}

{158}{}{Keine Drohungen nötig, Mann! Ich weiß, was dann passiert! Ich weiß es! Meine eigenen Leute würden mich umbringen!}
{159}{}{Ausgezeichnet. [Ihn gehen lassen]}
{160}{}{Ausgezeichnet. [Ihm mit einem Messer ins Herz stechen]}
{161}{}{Die Drohungen haben nichts gebracht. Offenbar hielt man dich nicht für einen würdigen Gegner.}

#Different questions
{200}{}{Wer bist du?}
{201}{}{Was ist das hier für ein Ort?}
{202}{}{Weißt du, wer die Freaks sind?}
{203}{}{[Der Raucher stößt einen Rauchring aus] Einer von diesen teuflischen Kerlen, die die Sklaven bewachen.}
{204}{}{Was machst du hier?}
{205}{}{Häng nur nach der Arbeit ab. Uh, was für ein starkes Zeug ...}
{206}{}{Sagt dir das Schild auf dem Dach gar nichts? Oh, stimmt ja! Das Schild hat erst nach dem fünften Joint zu mir gesprochen ... Du solltest ein bisschen warten.}
{207}{}{Necros. Ghule. Nenn sie, wie du willst. Eigentlich nette Kerle, aber viele Leute haben Angst vor ihnen. Deshalb sind sie immer an allem schuld, wenn hier vor Ort etwas schiefläuft.}
{208}{}{Hm.}
{209}{}{Verstanden.}

#Question about smoking
{210}{}{Weißt du, viele sind an dem Zeug krepiert.}
{211}{}{Weißt du, mit diesen Joints erinnerst du mich an die Straßenschläger in New Reno.}
{212}{}{Weißt du, wenn ich eine Frau wäre, würde ich mich nicht mit einem Raucher ins Bett legen. Ihr stinkt.}
{213}{}{Weißt du, Rauchen verursacht Lungenkrebs.}
{214}{}{Weißt du, Rauchen tötet.}
{215}{}{Weißt du, starke Raucher altern schneller.}
{216}{}{Weißt du, nach dem Rauchen wird die Leber braun.}
{217}{}{Weißt du, nach diesem Scheiß kann es passieren, dass du dich mit einem Straßenschild unterhältst.}
{218}{}{Weißt du, Zigaretten lassen dich nicht cool aussehen.}
{219}{}{Weißt du, manchmal ist da irgendein brahmin-Dreck drin.}
{220}{}{Weißt du, der Rauch zieht Fliegen und Kakerlaken an.}
{221}{}{Weißt du, man sagt, Zigaretten ziehen die Unterlippe runter.}
{222}{}{Weißt du, man sagt, der Rauch verhindert das Haarwachstum. Ich meine Schnurrbart und Augenbrauen.}
{223}{}{Weißt du, Nikotin lässt deine Nägel gelb werden.}
{224}{}{Weißt du, Nikotin lässt die Zähne verfaulen.}
{225}{}{Bekiffte kommen nicht in den Himmel.}

{250}{}{Sie machen's einfach falsch.}
{251}{}{Und?}
{252}{}{Du kannst froh sein, dass du keine Frau bist.}
{253}{}{Nichts für mich.}
{254}{}{Dafür werde ich ein paar Leibwächter anheuern.}
{255}{}{Verdammt, vielleicht werde ich dann auf der Straße nicht mehr schikaniert.}
{256}{}{Wirklich? Ich muss einen Raucher finden und nachsehen ... Interessant!}
{257}{}{Ich wollte schon immer mit der unbelebten Welt kommunizieren.}
{258}{}{Ich habe auch einen Fedora.}
{259}{}{Unsinn! Das ist eine Maus! ... Äh ... Hoppla.}
{260}{}{Wird was zum Mittagessen haben.}
{261}{}{So lässt sich der Joint leichter im Mund behalten.}
{262}{}{Hmm! Da spart man sich die Rasierer!}
{263}{}{Endlich gibt es einen Grund, mir die Nägel zu machen.}
{264}{}{[Zeigt einen zahnlosen Mund] Zu spät.}
{265}{}{Kein Problem – ich habe Beziehungen.}

{298}{}{Verdammt! Scheiße!! Schluss jetzt, hör auf! Okay! Ich gebe auf! Ich höre mit dem Rauchen auf! Hau einfach ab! Hier, [Er drückt dir hastig ein Feuerzeug in die Hand] nimm es! Jetzt habe ich kein Feuer mehr und kann nicht rauchen! Verpiss dich! Hau ab!!}
{299}{}{Na schön, beruhig dich!}

#Women's replics
{1108}{}{Warum bist du so wütend? Siehst du nicht, dass ich bekifft bin? Mir geht's gut. Also verpiss dich.}
{1115}{}{Tut mir leid, ich hab überreagiert.}
{1116}{}{Verdammt, wo kommen solche Schlampen überhaupt her?! Ich weiß nichts von irgendwelchen Labors!}
{1130}{}{NEIN! Idiot! Sie werden uns umbringen, verstehst du?!}
{1140}{}{Lass mich in Ruhe, Schwein ...}
{1156}{}{Na, hast du alles erfahren, was du wolltest, Schwesterchen?! Lässt du mich jetzt endlich gehen, hm?!}

{1212}{}{Weißt du, ich würde nie mit einer Raucherin ins Bett gehen. Ihr stinkt.}
{1252}{}{Bin ich sicher, dass ich mit einer Frau ins Bett will?.. Hoppla.}