{100}{}{Du siehst einen Diener.}
{101}{}{Du siehst einen Diener von Vault City.}
{102}{}{Äh, Grüße ... Bürger.}

{110}{}{Hey, du bist es! Äh, ich meine ... Verzeihung, Bürger. Schön, dich zu sehen, Bürger. Oh, und es lebe Vault City!}
{111}{}{Wer hat dir diese Begrüßung beigebracht?}
{112}{}{Hat dir die Reise gefallen?}
{113}{}{Gefällt es dir in der Stadt?}
{114}{}{Was machst du hier so?}
{115}{}{Wirst du gut behandelt?}
{116}{}{Was hältst du von den Bürgern?}

{119}{}{Bis dann.}

{120}{}{Der Oberdiener, Bürger. Wir müssen ... [zählt an den Fingern ab] ... jeden Bürger beim Anblick begrüßen, Vault City lobpreisen, allen Bürgern aus dem Weg gehen, keine Fragen stellen, niemals etwas benutzen, das Bürger benutzen, und ... noch irgendwas. Der Oberdiener erklärt uns jeden Morgen, wie wir uns verhalten sollen.}
{121}{}{Äh ... nicht wirklich, Bürger. Uns wurden die Augen verbunden und wir wurden in dieses Gefängnis mit Energietüren gebracht. Es war ... beängstigend. Zuerst wurden wir von einem Arzt untersucht, dann von den Wachen verhört. Ich dachte, ich würde verrückt werden. Aber das ist vorbei, und ehrlich gesagt bin ich froh, hier gelandet zu sein.}
{122}{}{Ja, Bürger! Wir werden versorgt, gekleidet und sind gesund. Wir haben ein Dach über dem Kopf und müssen nicht ums Überleben kämpfen wie damals, als wir frei waren. Allerdings ... ist die Arbeit hart. Besonders nach den Pillen, die wir jeden Morgen bekommen. Und es ist schwer, daran zu denken, dass wir die Stadt nicht verlassen dürfen, aber ... ich bin sicher, ich werde mich daran gewöhnen.}
{123}{}{Ich sortiere das Inventar in diesen Regalen, Bürger. Die anderen werden zur Arbeit am Bau irgendeines Gebäudes gebracht.}
{124}{}{Ja, Bürger, aber ... manchmal habe ich diese endlosen Regeln, Vorschriften, Formulare, Pillen und Spritzen satt. Ich weiß nicht, was in den Spritzen ist, aber danach kann ich an nichts anderes denken, als still dazusitzen und zu arbeiten.}
{125}{}{Ich... schätze... und danke den Bürgern. Sie sind wunderbare Menschen... Bürger. [seine Augen zeigen deutlich, dass er schamlos lügt]}

#Female Version
{1102}{}{Äh, grüße... Bürger.}
{1110}{}{Hey, du bist es! Äh, ich meine ... Verzeihung, Bürger. Schön, dich zu sehen, Bürger. Oh, und es lebe Vault City!}
{1120}{}{Der Oberdiener, Bürger. Wir müssen ... [zählt an den Fingern ab] ... jeden Bürger beim Anblick begrüßen, Vault City lobpreisen, allen Bürgern aus dem Weg gehen, keine Fragen stellen, niemals etwas benutzen, das Bürger benutzen, und ... noch irgendwas. Der Oberdiener erklärt uns jeden Morgen, wie wir uns verhalten sollen.}
{1121}{}{Äh... Nicht ganz, Bürger. Wir wurden mit verbundenen Augen in dieses Gefängnis mit Energietüren gebracht. Es war... beängstigend. Zuerst wurden wir von einem Arzt untersucht, dann von den Wachen verhört. Wir dachten, wir würden wahnsinnig werden. Aber das ist jetzt vorbei, und ehrlich gesagt bin ich froh, dass ich hier gelandet bin.}
{1122}{}{Ja, Bürger! Wir werden versorgt, gekleidet und sind gesund. Wir haben ein Dach über dem Kopf und müssen nicht ums Überleben kämpfen wie damals, als wir frei waren. Allerdings ... ist die Arbeit hart. Besonders nach den Pillen, die wir jeden Morgen bekommen. Und es ist schwer, daran zu denken, dass wir die Stadt nicht verlassen dürfen, aber ... ich bin sicher, ich werde mich daran gewöhnen.}
{1123}{}{Ich sortiere das Inventar in diesen Regalen, Bürger. Die anderen errichten irgendein Gebäude.}
{1124}{}{Ja, Bürger, aber ... manchmal habe ich diese endlosen Regeln, Vorschriften, Formulare, Pillen und Spritzen satt. Ich weiß nicht, was in den Spritzen ist, aber danach kann ich an nichts anderes denken, als still dazusitzen und zu arbeiten.}
{1125}{}{Ich... schätze... und danke den Bürgern. Sie sind wunderbare Menschen... Bürgerin. [ihre Augen zeigen deutlich, dass sie schamlos lügt]}
