{100}{}{Du siehst Gareth.}
{101}{}{Du siehst einen scheinbar ganz gewöhnlichen Passanten.}
{102}{}{*Skriptfehler beim Ausführen*}

{110}{}{Äh ... Hallo, Wanderer. Und ... einen schönen Tag noch.}
{111}{}{Warte, was machst du hier?}
{112}{}{Wie auch immer.}

{113}{}{Äh ... [mustert dein Gesicht aufmerksam] Du siehst aus wie einer von denen [zeigt in Richtung des Büros der Sklavenhändler]. Entschuldige, aber ich gehe dann mal weiter.}
{114}{}{Sehe ich wirklich so schlimm aus ...}

{115}{}{Äh ... [mustert dein Gesicht aufmerksam] Bist du einer von denen [zeigt in Richtung des Büros der Sklavenhändler]? Was machst *du* hier?}
{116}{}{Ich habe zuerst gefragt.}
{117}{}{Ich bin nur auf der Durchreise und kümmere mich um meine eigenen Angelegenheiten.}
{118}{}{Ich suche einen frischen Sklaven.}
{119}{}{Nichts, was ein Gespräch mit dir rechtfertigen würde.}

{120}{}{Dann haben wir wohl nichts zu besprechen.}
{121}{}{Äh ...}
{122}{}{Siehst du, du vertraust mir nicht. Dann sollte ich wohl lieber nicht mit dir reden.}
{123}{}{Also gehörst du nicht zu ihnen? Puh, wenigstens gibt es in dieser Stadt jemanden, der einfach nur ein Passant ist und keiner zwielichtigen Organisation angehört.}
{124}{}{Und welcher Organisation gehörst du an?}
{125}{}{Ja. Na ja, war nett, mit dir zu reden.}

{126}{}{Ein Mitglied der geheimen Rächer-Sekte ... Nur ein Scherz. He-he.}
{127}{}{Wow, kann ich eurer Sekte beitreten?}
{128}{}{Verdammt, hältst du mich für einen Idioten?}
{129}{}{He-he. Mach's gut, du verdammter Spaßvogel.}

{130}{}{Na ja, ohne Prüfung kannst du nicht beitreten. Wir sind buchstäblich nur zu zweit. Ich bezweifle, dass du dazugehören willst. Die Risiken und so ...}
{131}{}{Hey, reg dich nicht auf, ich habe nichts falsch gemacht!}
{132}{}{Du sagst mir besser, was du vorhast.}
{133}{}{Ich glaube, du steckst in Schwierigkeiten. Erzähl es mir, vielleicht kann ich dir helfen.}
{134}{}{Also gut, ich glaube dir ... diesmal. Mach's gut.}

{135}{}{Oh, okay. Jedenfalls schaffe ich das nicht allein.}
{136}{}{Also, was ist dein Problem?}

{137}{}{Das Problem ist nicht meins, sondern das meines Bruders. Verdammte Sklavenhändler haben ihn geschnappt, als er in die Stadt zurückkam, und ihn im Pferch eingesperrt. Ich will ihn retten, aber das wird nicht einfach.}
{138}{}{Hast du einen Plan?}
{139}{}{Ja, habe ich, aber zuerst muss ich Eric kontaktieren. Allerdings kommt man nur als Sklave in den Pferch. Und das bedeutet, für immer gebrandmarkt zu werden.}
{140}{}{Woher weißt du, dass er dort ist?}
{141}{}{Das ist doch eine Möglichkeit, oder? Du kannst Sklave werden, und ich werde dich rächen.}
{142}{}{Ich kann deinem Bruder die Nachricht überbringen.}
{143}{}{Äh, heute wird das nicht mein Problem sein. Pass auf dich auf.}
{144}{}{Ein Freund hat ihn gesehen und gesagt, er sei hier. Dann habe ich eine Lücke im Zaun gefunden und ihn unter den Sklaven entdeckt.}
{145}{}{Kommt nicht infrage. Erstens ist nicht garantiert, dass du mich hier rausholst, und zweitens will ich nicht den Rest meines Lebens mit einem Mal auf der Stirn herumlaufen.}

{146}{}{Willst du da wirklich rein?! Warum?! Wenn du erst mal dort bist, kommst du nicht ohne ein Mal auf der Stirn zurück!}
{147}{}{Mach dir keine Sorgen um mich, ich weiß, was ich tue.}
{148}{}{Na ja, das musst du selbst wissen ...}
{149}{}{Ich mach's, wenn du mich bezahlst.}
{150}{}{Stimmt, das ist zu albern. Bring dich selbst in Gefahr, ich bin dann weg.}

{151}{}{Oh, du bist es. Hallo.}
{152}{}{Was war das noch mit dem Problem mit deinem Bruder?}
{153}{}{Ja, ich bin's. Ganz ruhig.}

{154}{}{Verdammt, das wäre großartig. Du musst Eric nur eine Nachricht überbringen.}
{155}{}{Nur eine Nachricht? Das mach ich.}
{156}{}{Ich hab's mir anders überlegt, tut mir leid.}

{157}{}{Hey, warte. Ich kann dir 200 Mäuse zahlen, wenn du das machst. Ich würde mehr zahlen, wenn ich mehr hätte ... Aber natürlich zahle ich nicht sofort, damit du keinen Grund hast, mich zu betrügen. Du musst Eric nur eine Nachricht überbringen, mehr nicht.}
{158}{}{Gib mir die Nachricht, ich mach's.}
{159}{}{Nein, das mach ich nicht.}

{160}{}{Klar, ich zahle, aber erst, wenn Eric die Nachricht bekommen hat. Allerdings habe ich nur 200 Mäuse. Ich würde mehr zahlen, wenn ich reicher wäre ...}
{161}{}{Gib mir die Nachricht, ich mach's.}
{162}{}{Ich hab's mir anders überlegt, tut mir leid.}

{163}{}{Hier. Ich zähle *wirklich* auf dich! Bitte, alles hängt davon ab! Wenn diese Nachricht in die Hände von Sklavenhändlern fällt, war alles umsonst.}
{164}{}{Na gut, ich überleg's mir.}

#After getting the quest on passing the note
{200}{}{Na, wie läuft's, Wanderer?}
{201}{}{Ich habe schlechte Nachrichten – Eric ist tot.}
{202}{}{Keine Sorge, Eric hat deine Nachricht bekommen.}
{203}{}{Ich bin noch dabei.}

{204}{}{Was?! Was zum Teufel! Du könntest ihn verwechselt haben oder ... Oder du lügst ... Oder ... Ich weiß auch nicht, aber ich glaub dir nicht! ... Ugh, warum hab ich mich überhaupt mit dir eingelassen?! Verschwinde!}
{205}{}{Ach, so läuft das jetzt bei dir!}
{206}{}{Oh, gut! Jetzt wird es mir leichter fallen, damit fertigzuwerden ...}
{207}{}{Und was ist mit meiner Belohnung?}
{208}{}{Was? Ach ja. Aber warte, woher soll ich wissen, dass du die Wahrheit sagst? Nein, zuerst sehe ich selbst nach.}
{209}{}{WAS?!}
{210}{}{Es wird ganz einfach sein. Wir warten bis zum Abend, dann wirst du es sehen.}
{211}{}{Na gut, warten wir.}
{212}{}{Auf keinen Fall! Zahl mich jetzt aus!}
{213}{}{Dann komme ich später wieder.}
{214}{}{Ich habe gerade kein Geld. Du musst warten.}
{215}{}{Ich habe eine Idee. Weißt du, der Barkeeper in der Arena sagte, sie wollten Eric als Kämpfer einsetzen. Ich konnte die Gespräche der Sklavenhändler belauschen.}
{216}{}{Großartig! Ich glaube, dir wird nicht langweilig werden.}
{217}{}{Mal sehen.}

{218}{}{Die Sklaven sind jetzt frei. Nichts hält sie mehr davon ab, abzuhauen.}
{219}{}{Wunderbare Neuigkeiten! Und ich habe mich gerade gefragt, was es wohl mit dem verdächtigen Lärm im Pferch auf sich hatte. Danke, Wanderer! Hier, nimm 200 Kröten für das Risiko. Mehr habe ich nicht.}
{220}{}{Natürlich, pass auf dich auf!}

{221}{}{Danke für deine Hilfe, Wanderer. Es hat mich gefreut, so einen wunderbaren Menschen kennenzulernen. Hier [reicht 200 Kröten] – mehr kann ich dir für deine Hilfe nicht geben.}
{222}{}{Warte, woher wusstest du, dass Eric in die Arena gebracht werden soll?}
{223}{}{Ich habe es vom Barkeeper erfahren, ich kenne ihn. Dann habe ich die Gespräche über den Funkkanal der Sklavenhändler belauscht. Übrigens, hier, nimm das Funkgerät, ich brauche es nicht mehr. Vielleicht kannst du es gebrauchen.}
{224}{}{Danke. Also, pass auf dich auf.}
{225}{}{Alles war umsonst ... [fasst sich an den Kopf]}
