{100}{}{Du siehst: ein Roboter.}
{101}{}{Du siehst einen kaputten Eyebot. Er kann weder fliegen noch Befehlen gehorchen.}
{102}{}{Dieser Roboter ist beschädigt, lässt sich aber reparieren.}
{103}{}{Du hast den Roboter erfolgreich repariert.}
{104}{}{Du kannst einfach nicht begreifen, wie diese Maschine funktioniert.}
{105}{}{***Systeme werden überprüft ... Keine Fehlfunktionen festgestellt***}
{106}{}{***Systemanalyse abgeschlossen***}