{100}{}{Du siehst Vortis.}
{101}{}{Das ist Vortis, der Anführer von Slavertown.}
{102}{}{Was zum Teufel geht hier vor, ihr Mistkerle!!!}
{103}{}{Jetzt nicht! Ich muss mich um diese Mistkerle in der Lobby kümmern.}

#The starting dialogue branch:
{110}{}{Ich bin der Boss dieses Etablissements. Was machst du hier?}
{111}{}{Ich brauche Sklaven, eine ganze Menge. Zwanzig reichen für den Anfang.}
{112}{}{Kann ich einen Sklaven kaufen?}
{113}{}{Ich verlange eine Erklärung! Wie zum Teufel hängt ihr alle mit dem Drogenlabor zusammen?}
{114}{}{Um dir eine Kugel in den Schädel zu jagen! Du hast es verdient!}
{115}{}{Sieht aus, als wäre ich am falschen Ort gelandet ...}

#Ridiculous answers after the 115 phrase:
{116}{}{Nicht schon wieder! Na toll ... Der Eingang zum Ring ist NOCH EINE TÜR DRAUSSEN! Auf der anderen Seite des Gebäudes, hörst du?!}
{117}{}{Das Büro ist in der Lobby. Dort ist ein Verwalter, mit dem kannst du alles klären. Verstanden?}
{118}{}{Wovon redest du da? Wir haben mit dem Zeug nichts zu tun! Hörst du? WIR VERKAUFEN KEINE DROGEN!}
{119}{}{Äh, verstanden ...}

#Answer to the question about the slave to drive the train (112):
{120}{}{Ich mache keinen Einzelhandel. In der Lobby ist ein Verwalter. Klär alles mit ihm.}
{121}{}{Verstanden.}

#Answer to the question about the lab (113):
{122}{}{Du hast ein ganz schön loses Mundwerk, Kumpel. Pass auf.}
{123}{}{Du willst also sagen, dass du damit nichts zu tun hast? Ich rate dir, noch mal darüber nachzudenken. Ich bin nicht hier, um eine Umfrage zu machen.}
{124}{}{Ist das eine Drohung?! Wenn ja, schlage ich zuerst zu. Sieh nur zu!}
{125}{}{Oh, okay, mach ich. Weißt du, du redest irgendwie ziemlich beängstigend.}

{126}{}{Hm? Und warum sollte ich deine Fragen beantworten?}
{127}{}{Weil ich im Auftrag des Bürgermeisters die jüngsten Verbrechen in der Stadt untersuche.}
{128}{}{Ich habe persönliche Gründe.}
{129}{}{Na schön. Dann musst du mit deinem Blut antworten! Also antworte mir, Schlampe!}
{130}{}{Wenn du nicht willst, musst du nicht antworten.}

{131}{}{Ha, mein Freund, dann habe ich ein Dutzend Gründe, dich zum Schweigen zu bringen ... [zieht eine Waffe und lächelt, als wäre nichts geschehen]}
{132}{}{Hey! ...}

{133}{}{Welche denn?}
{134}{}{Ich will dort arbeiten.}
{135}{}{Ich will das Labor zerstören.}
{136}{}{Ich will mich einfach nur richtig wegschießen! Dafür brauche ich eine MENGE Zeug!}

{137}{}{Nicht schon wieder ... Die kaufen genug Sklaven bei uns, dich brauchen sie nicht.}
{138}{}{Äh ... Moment mal. [Aufnahme auf deinem Pip-Boy aktivieren] Du sagst also, ihr beliefert das Labor mit Sklaven?}
{139}{}{Schade.}

{140}{}{[Sieht dein Pip-Boy an] Aber ... Niemand wird von diesem Gespräch erfahren.}
{141}{}{Hey, warte mal! Ich frage doch nur!}

{142}{}{Ist mir egal. Das geht mich nichts an.}
{143}{}{Das bezweifle ich ja sowas von ...}

{144}{}{Die verkaufen nicht an Laufkundschaft, also kannst du dir das gleich aus dem Kopf schlagen. In der Stadt gibt es ein paar ihrer Verkaufsstellen. Schau beim Karawanenrastplatz vorbei, dort findest du ihre Kuriere. Ein weiterer treibt sich beim Café „Hard Rock“ herum. Das war's, verschwinde. Junkies haben hier nichts verloren. Wir haben selbst genug davon.}
{145}{}{Äh ... Moment mal. [Aufnahme auf dem Pip-Boy aktivieren] Du weißt also, wo das Labor ist, oder?}
{146}{}{Okay, ich halte die Augen offen.}

#Answer to the question about the slaves for the Hoover dam (111):
{147}{}{Kann ich erst erfahren, wofür diese Sklaven gedacht sind?}
{148}{}{Schwere körperliche Arbeit.}
{149}{}{Hmm ... Willst du genauer werden?}
{150}{}{Das kann ich nicht sagen.}
{151}{}{Ach ja? Dann kann ich dir nichts verkaufen. Ha!}
{152}{}{Hör auf zu bluffen, hier geht es um Geld! Deine Aufgabe ist es, im Austausch für Sklaven das Geld aufzutreiben. Alles andere ist egal. Also beeil dich, sonst verlierst du einen Kunden.}
{153}{}{Na ja, schade.}
{154}{}{Mann, du kannst dich gut ausdrücken. Weißt du, ich habe erfahren, dass dem Hoover dam in letzter Zeit die Arbeiter ausgehen. Und früher oder später wird der Chef des Damms zu uns kommen ... Also überzeug mich: Warum sollte ich die Sklaven *dir* verkaufen und nicht ihm?}
{155}{}{Soweit ich weiß, kämpfen in der Stadt Leute darum, den Damm zu kontrollieren ...}
{156}{}{Ach. Das ist zu kompliziert. Ich werde dich nicht dazu überreden.}

{157}{}{Na gut, dann versuche ich, lady Luck an die Titten zu gehen.}
{158}{}{Okay. Ich hoffe, du änderst deine Meinung noch.}

{159}{}{Verdammt, da hast du recht. Bei unseren Preisen kosten dich fünfzig Sklaven zehntausend.}
{160}{}{Ich habe genau den richtigen Betrag dabei.}
{161}{}{Dann eben ein anderes Mal.}

{162}{}{Wegen der Sklaven. Ich habe zehntausend dabei und bin bereit, einen Deal abzuschließen.}
{163}{}{Du hast für die Hoover dam eine Lieferung Sklaven gekauft. Jetzt musst du nur noch Bob Neil Bescheid geben.}
{164}{}{Gutes Geschäft. Die Sklaven warten in unserem Gehege. Schick einfach deine Arbeiter, um sie abzuholen. Und hier ist eine Quittung, damit alles seine Ordnung hat.}
{165}{}{Alles klar.}

{170}{}{Was geht hier vor? Antwortet mir!}
{171}{}{Äh, Boss, wir wissen nicht, was das war!}
{172}{}{Was soll das heißen?!}
{173}{}{Wir wissen es nicht, Boss! Niemand ist entkommen, alles ist unter Kontrolle!}
{174}{}{Und was war dann das ganze Geschrei über eine Flucht, das ich über Funk gehört habe?!}
{175}{}{Vielleicht war es ein Scherz von jemandem aus der Patrouille ...}
{176}{}{Wenn ich herausfinde, wer das war, begrabe ich ihn eigenhändig lebendig!}
{177}{}{Jawohl, Boss.}
{178}{}{Warum seid ihr verdammt noch mal immer noch hier!? Los, findet diesen Witzbold!}
{179}{}{Äh ... Boss, aber wie sollen wir ihn finden?}
{180}{}{Äh, ihr seid wirklich ein Haufen Hohlköpfe! Ich hasse euch alle so sehr!}
{181}{}{Ähm ... Boss ...}
{182}{}{Und zählt die Sklaven noch mal, ihr Schwachköpfe!}
{183}{}{Wie Sie wollen, Boss.}
{184}{}{::brummelt::}

{185}{}{Jeder könnte es übernehmen. Schaffst du es, deinen Handel abzuschließen? Und mein Geld ist *garantiert*. Denk darüber nach.}
{186}{}{Na und?}

#Women's replics
{1115}{}{Sieht aus, als wäre ich am falschen Ort gelandet ...}
{1119}{}{Äh, verstanden ...}
{1122}{}{Du hast ein großes Maul, Mädchen. Pass auf, was du sagst.}
{1131}{}{Ha, mein liebes Mädchen, dann habe ich ein Dutzend Gründe, dir den Mund zu stopfen ... [zieht eine Waffe und lächelt, als wäre nichts geschehen]}
{1141}{}{Hey, warte mal! Ich frage doch nur!}
