{100}{}{Du siehst Eric.}
{101}{}{Du siehst einen Sklaven namens Eric.}
{102}{}{Was für eine Verschwendung. Er hätte sich meinetwegen nicht in solche Gefahr bringen sollen.}
{103}{}{Danke, Wanderer. Wir werden es nie vergessen!}

{110}{}{Tut mir leid, aber ich muss sofort von hier verschwinden.}
{111}{}{Was?}
{112}{}{Wer bist du?}
{113}{}{Wie bist du hierhergekommen?}
{114}{}{Weißt du, wie man von hier wegkommt?}
{115}{}{Eric, ich habe einen Brief von deinem Bruder.}
{116}{}{Eric, du kannst jetzt von hier weg. Die Sklavenhändler sind tot.}
{117}{}{Nichts.}
{118}{}{Verdammt richtig! Wir müssen sofort von hier verschwinden! Los!}
{119}{}{Pass auf dich auf.}
{120}{}{Ich heiße Eric. Bevor ich hierherkam, war ich nur ein einfacher Arbeiter in dieser Stadt der Sünden.}
{121}{}{Stimmt.}
{122}{}{Das ist kaum möglich. Patrouillen bewachen alle Ausgänge, und die Lobby ist immer voller Leute. Öffne einfach das Tor, und die Sklavenhändler werden sofort zu ihren Waffen greifen.}
{123}{}{Der Postbote hat mich hergebracht. He-he. Ich habe tatsächlich alles im Kasino verloren, und die Besitzer haben mich, statt mich wegen meiner Schulden auszunehmen, einfach in die Sklaverei verkauft. Das war der größte Fehler meines Lebens. Ich werde nie wieder auf mein Glück vertrauen.}
{124}{}{Wirklich?!}
{125}{}{Ja, hier ist er.}
{126}{}{Ich habe ihn irgendwo verloren, aber ich erinnere mich noch an den Brief.}
{127}{}{Verdammt, ich habe ihn irgendwo verloren. Ich gehe ihn suchen.}

{128}{}{Es fällt mir schwer zu glauben, dass jemand zu den Sklavenpferchen gehen würde, nur um mir einen Brief von meinem Bruder zu bringen. Verdammt, mit den Gefühlen eines Menschen in Not zu spielen, sagt viel über denjenigen aus, der das tut.}
{129}{}{Ich sage die Wahrheit!}
{130}{}{Ja, klar.}
{131}{}{Ugh ...}

{132}{}{Mein Gott! [liest den Brief, dann liest ihn noch einmal] Er ist verrückt! Verdammt, er zieht das wirklich durch. Zwei bewaffnete Wachen werden mich beobachten ... Jedenfalls danke dafür. Sag ihm, dass mir die Idee nicht gefällt.}
{133}{}{Wie du meinst.}

{134}{}{Hast du etwas Interessantes von den Sklavenhändlern gehört?}
{135}{}{Nun, einige der Wachen haben geredet. Sie sagen, die Stadt habe ein geheimes Labor, in dem Sklaven für Experimente benutzt werden. Da würde ich nicht landen wollen. Obwohl Sklaven wie ich wahrscheinlich ohnehin zum Kämpfen in die Arena geschickt werden.}

#Æåí ğåïëèêè
{1103}{}{Danke, Wanderer. Wir werden es nie vergessen!}
