{100}{}{Du siehst einen Sklavenhändler.}
{101}{}{Du siehst einen gewöhnlichen Sklavenhändler.}

#Êîãäà âîğîòà ê ğàáàì îòêğûòû
{102}{}{Hey! Welcher Idiot hat das Tor offen gelassen?!}
{103}{}{Was ist da los?}
{104}{}{Das Tor steht schon wieder offen!}
{105}{}{Wer hat das Tor nicht geschlossen?!}
{106}{}{Ich verstehe nicht. Transportieren wir jetzt neue Sklaven? Oder was?}

#Ïîïûòêà çàãîâîğèòü
{150}{}{Frag den Verwalter. Oder Vortis.}
