{100}{}{Du siehst Verwalter Aidan.}
{101}{}{Du siehst den Verwalter der Sklavenstadt.}
{102}{}{*Skriptfehler beim Ausführen*}
{103}{}{Gut. Dann gehen wir im Guten auseinander.}

#Starting dialogue branch
{200}{}{Ah, frisches Blut! Komm, hab keine Angst. Das ist die Gilde der Sklavenhändler, mein Name ist Aidan. Bist du wegen einer geschäftlichen Angelegenheit hier? Das hoffe ich jedenfalls.}
{201}{}{Ich möchte fünfzig starke, gesunde Sklaven kaufen.}
{202}{}{Ich möchte fünfzig starke, gesunde Sklaven kaufen. Warum, geht dich nichts an.}
{203}{}{Du steckst offensichtlich in schmutzigen Geschäften. Deshalb werdet ihr alle sterben. Jetzt!}
{204}{}{Ich weiß, dass du im örtlichen Drogengeschäft steckst! Und du wirst mir zeigen, wo sich die Produktionsstätte befindet.}
{205}{}{Ich brauche einen Sklaven. Er soll als Fahrer auf einem Zug arbeiten.}
{206}{}{Äh... Nein. Tschüss.}

#Response on 203 
{207}{}{Oh, wow, was für ein Krieger! Ha-ha! Na los, versuch's. Ich bin ganz dein!}
{208}{}{Gut! Nimm das, Abschaum!}
{209}{}{Verdammt, ihr seid zu viele. Ich würde lieber einen von euch um die Ecke herum überfallen. Tschüss.}

#Response on 204
{210}{}{Echt? Ha! Wenn du etwas darüber herausfindest, sag es mir! Ich werde der Erste sein, der ihre neuen Drogen ausprobiert, ha-ha!}
{211}{}{Du lügst! Antworte mir, du Hurensohn! Wo ist das Labor?!}
{212}{}{Ach, na ja, wenn du es nicht weißt, tut es mir leid.}
{213}{}{Hey, Jungs! Hier ist ein Arschloch, das es drauf anlegt!}
{214}{}{Pass auf, wie ich mich verteidige!}
{215}{}{Schon gut, Mann, ich lasse dich in Ruhe. Bleib locker.}

#Response on 205
{216}{}{Da habe ich genau den Richtigen für dich. Er kennt sich mit Technik aus, läuft nicht weg und arbeitet hart. Was den Preis angeht: Ich verkaufe ihn für 3000 $.}
{217}{}{Ich bin überzeugt. Hier ist das Geld. Schick den Sklaven nach Salt Lake City und lass ihn mich im Hotel „Sechste Kugel“ treffen.}
{218}{}{Ich verzichte.}
{219}{}{Bist du verrückt? Für so viel Geld könnte ich ein Dutzend Sklaven kaufen. Geh runter auf 2000 $.}
{220}{}{So ein Stück landet nicht jeden Tag im Gehege. Deshalb werde ich den Preis nicht senken.}
{221}{}{Dann verlierst du einen Kunden. Ich gehe.}
{222}{}{So ein Stück landet nicht jeden Tag im Gehege ... Allerdings wird ihn wohl eine ganze Weile niemand kaufen. Vielleicht verlange ich tatsächlich zu viel. Na gut, ich senke den Preis auf 2000 $.}
{223}{}{Ein vernünftiger Vorschlag. Hier ist das Geld. Schick den Sklaven nach Salt Lake City und lass ihn mich im Hotel „Sechste Kugel“ treffen.}
{224}{}{Du hast einen Zugführer für den Zug gefunden. Du kannst jetzt nach Salt Lake zurückkehren und deine Mission fortsetzen.}

#Response on 202
{237}{}{Na gut, ich frage lieber gar nicht erst. Das macht der Boss. Ich bin nicht für solche großen Geschäfte zuständig. Sprich mit ihm, gleich den Flur runter auf der linken Seite.}
{238}{}{Okay, ich suche nach ihm.}

#Cowboy
{240}{}{Ich möchte einen starken Kampfsklaven verkaufen. Er steht gerade beim Wagen, nackt und wehrlos.}
{241}{}{In Ordnung. Gute Sklaven brauchen wir immer, besonders Kämpfer. Üblicherweise zahlen wir 500 $.}
{242}{}{Der Preis gefällt mir. Du kannst ihn abholen. Ach, und ... Vielleicht wird er sich wehren. Denn, du weißt schon, er ist schließlich ein Kampfsklave.}
{243}{}{Wie viel?! Nein, ich versuche, eine andere Verwendung für ihn zu finden.}
{244}{}{Der hier sieht ordentlich aus. Sein Körper ist in ausgezeichnetem Zustand, stark genug, um mehr als einmal zu kämpfen. Ein gutes Produkt. Hier ist die Bezahlung.}
{245}{}{Endlich ist er zu etwas nütze ...}

#Eric the slave
{250}{}{Ich suche einen bestimmten Sklaven namens Eric.}
{251}{}{Mal sehen ... Ja, es gibt einen mit diesem Namen. Ein Sklave aus der Arbeiterklasse. Man kann ihn Lasten tragen lassen oder in der Arena kämpfen lassen.}
{252}{}{Wie viel willst du für ihn?}
{253}{}{Sklaven dieser Art sind jeweils 500 Bucks wert.}
{254}{}{Na gut, ich kaufe ihn.}
{255}{}{Das ist zu viel!}
{256}{}{Danke, ich brauche ihn nicht.}
{257}{}{Solche Sklaven sind teuer. Wenn die Kunden nur wüssten, wie viel Mühe es kostet, sie einzufangen und abzurichten ...}
{258}{}{Ich komme wieder, wenn ich genug Geld habe.}
{259}{}{He, du da! Nummer A12-86! Komm her, ein Kunde wartet!}
{260}{}{Ich warte.}

{261}{}{Ich kann dir Informationen über den bevorstehenden Fluchtversuch verkaufen.}
{262}{}{Sehr interessant. Welcher Idiot hat beschlossen, seinen Tod in unserem Gehege zu suchen?}
{263}{}{Kaufst du die Informationen oder nicht?}
{264}{}{Ich denke schon. Aber du gehst zuerst!}
{265}{}{Na gut. Hier ist eine Nachricht von jemandem namens Gareth an einen deiner Sklaven.}
{266}{}{Nein, erst das Geld!}
{267}{}{Keine Informationen. Ich habe es mir anders überlegt.}
{268}{}{Ich bin kein Feilscher. Rede oder verschwinde.}
{269}{}{[Liest die Nachricht] Was für ein naiver Narr. Also, wo ist dieser Gareth jetzt?}
{270}{}{An der Ostmauer des Geheges.}
{271}{}{Das war's schon!?}
{272}{}{Kein Mann, kein Problem.}
{273}{}{Na gut, hier sind 300 Bucks und ein Dankeschön im Namen der Firma. Frag nicht nach mehr.}
{274}{}{Ha, so viel Geld für einen Nebenjob ...}

#Collars
{278}{}{Vier.}
{279}{}{Sieht so aus, als könnte ich noch mehr verkaufen.}
{280}{}{Ich habe Sklavenhalsbänder zu verkaufen.}
{281}{}{Hast du noch Interesse an Sklavenhalsbändern?}
{282}{}{Oh, dieses Accessoire ist bei Sklavenhaltern sehr beliebt. Eine äußerst nützliche Sache! Ich kaufe sie dir für 100 Dollar pro Stück ab.}
{283}{}{Ich dachte an 125.}
{284}{}{Na gut, damit kann ich leben.}
{285}{}{Ich glaube nicht, dass ich diesen Preis akzeptiere. Ich komme wieder, falls ich es mir anders überlege.}

{286}{}{Wie bitte?! Selbst manche Sklaven sind weniger wert als dein Preis! Ich war heute schon großzügig genug.}
{287}{}{Na schön, hundert müssen reichen.}
{288}{}{Nun, wenn man es sich überlegt ... Na gut, mit dem Preis bin ich einverstanden.}
{289}{}{Großartig.}
{290}{}{Allerdings könnten sie mir noch nützlich sein. Ich komme wieder, falls ich es mir anders überlege.}

{291}{}{Wie viele Halsbänder willst du verkaufen?}
{292}{}{Eins.}
{293}{}{Zwei.}
{294}{}{Drei.}
{295}{}{Fünf.}
{296}{}{Alles, was ich habe (}
{297}{}{ Stück).}
{298}{}{Keins. Ich habe es mir anders überlegt.}

{299}{}{Eine ganze Menge!}

#Women's replics
{1207}{}{Oh, wow, was für ein Krieger! Ha-ha! Na los, versuch's. Ich bin ganz dein!}
{1213}{}{He, Leute! Hier ist eine arrogante Schlampe, die es drauf anlegt!}
{1267}{}{Ich werde keine Informationen geben. Ich habe es mir anders überlegt.}
{1298}{}{Keins. Ich habe es mir anders überlegt.}
