{100}{}{Du siehst einen Sklaven.}
{101}{}{Du siehst einen Sklaven. Er wirkt erbärmlich.}
{102}{}{Dieser hier hat dir nichts zu sagen.}
{103}{}{::starrt dich ausdruckslos an::}
{104}{}{Du hast den Sklaven dazu gebracht, den Pferch zu verlassen.}

#Dialogue before slaves escape from the corral
{110}{}{Ich will mich hinlegen. Lass mich in Ruhe.}
{111}{}{Keine Zeit zum Herumliegen, ihr Faulpelze! Die Sklavenhändler sind tot. Ihr seid frei!}
{112}{}{In Ordnung.}

{113}{}{Äh ... Ja, äh, gute Nachrichten, ja.}
{114}{}{Das ist mal was Neues. Hey, habt ihr das alle gehört?! Los, Leute! Wir sind frei ... }
{115}{}{Beeilt euch!}
{116}{}{Bewegt eure Ärsche, ihr Herde!}
{117}{}{Warum seid ihr dann so traurig?}

{118}{}{Oh, du Dummkopf! Oh, du Dummkopf! Hast du eine Ahnung, was du getan hast?! [Er greift sich an den Kopf]}
{119}{}{Hey, was ist das Problem?! Ihr könnt diesen Ort verlassen und nach Hause gehen!}

#Dialogue with those slaves who remained in the corral and don't want to leave
{120}{}{Wohin denn? Ich habe kein Zuhause! Danke natürlich, tolle Arbeit und so, aber sie hätten mir wenigstens ein Dach über dem Kopf, Essen und Wasser geben können. Jetzt muss ich mir das alles selbst suchen ... Du bist ein Vollidiot, wenn du glaubst, du hättest irgendetwas verbessert!}
{121}{}{Hm. Was für eine unerwartete Reaktion. Wenigstens ist die Mehrheit zufrieden ...}
{122}{}{[Der Sklave sieht sich verwirrt um]}
{123}{}{Hey! Warum rennst du nicht? Das Tor zur Pferche ist offen! Du musst schnell raus und nach Hause!}
{124}{}{Hey! Beeil dich! Na los!}
{125}{}{Also ist das ... Sie sind alle ...}
{126}{}{Steh auf, du Idiot! Sofort! Keine Zeit zu verlieren! Vorwärts! Los!!!}

###################################################
#
# FLOATING PHRASES
# Author: Aleksandr Agafontsev
#
###################################################

{150}{}{In dieser Pferche begreifst du irgendwann, wie sich brahmin im Schlachthaus fühlt ...}
{151}{}{Warum habe ich auf Null gesetzt?}
{152}{}{Noch ein Tag in diesem Höllenloch ...}
{153}{}{Mama hat immer gesagt: Lass die Finger vom Glücksspiel.}
{154}{}{Lass mich ins Kasino! Nur ein Einsatz, dann bin ich wieder da!}
{155}{}{Und sie sagten, das wahre Leben spiele sich in Vegas ab ...}
{156}{}{Lasst mich raus!}
{157}{}{Das ist eine Verletzung der Menschenrechte! Ich werde mich beschweren!}
{158}{}{Selbst im Lager der Raider war es sauberer ...}
{159}{}{Früher hatte ich selbst ein paar Sklaven ...}
{160}{}{Freiheit! Freiheit!!!}
{161}{}{Eine Flasche Bier und eine Zigarre – dann können sie mich erschießen, ist mir egal ...}
{162}{}{Befreit uns!}
{163}{}{Wir sind keine Tiere! Na ja, ich jedenfalls nicht.}
{164}{}{Er hatte gezinkte Karten! Ich hätte gewinnen müssen!}
{165}{}{Wir leben in einem Land der Freiheit! Lasst mich raus!}
{166}{}{Ich halte es hier nicht mehr aus!}
{167}{}{Selbst meine Frau hat mich nicht so schlecht ernährt!}
{168}{}{Ich verlange eine richtige Toilette!}
{169}{}{Ahhh! ::schlägt seinen Kopf auf den Boden::}
{170}{}{Wie war das noch ... „Du wirst sowieso sterben“?}

#Women's replics
{1118}{}{Oh, du Dummkopf! Hast du eine Ahnung, was du getan hast?! [Er fasst sich an den Kopf]}
{1120}{}{Wohin denn? Ich habe kein Zuhause! Danke natürlich, tolle Arbeit und so, aber sie hätten mir wenigstens ein Dach über dem Kopf, Essen und Wasser geben können. Jetzt muss ich mir das alles selbst suchen ... Du bist ein Vollidiot, wenn du glaubst, du hättest irgendetwas verbessert!}
