{100}{}{Du siehst einen Wachmann.}
{101}{}{Dieser Wachmann wird dir schnell den Garaus machen, wenn du nicht aufpasst.}

#Когда впервые увидит ГГ
{102}{}{Alarm! Ich sehe den Feind!}
{103}{}{Feind! Angriff!}
{104}{}{Hey, du! Ich seh dich!}
{105}{}{Hab dich, Schlampe!!}
{106}{}{Ich habe dich nicht hergerufen!}
{107}{}{Sabotage!?}
{108}{}{Ich hab dich im Visier! Du hдltst nicht mehr lange durch!}
{109}{}{Alarm! Eindringling!}