{100}{}{Du siehst einen Bürger.}
{101}{}{Du siehst einen gewöhnlichen Bürger.}
{102}{}{Entschuldigung, ich habe es eilig.}

#Ğåïëèêè ïğè ïîïûòêå çàãîâîğèòü, êîãäà êîïà óáèëè:
{150}{}{Man sagt, die Schüsse seien vom Dach gekommen.}
{151}{}{Einige erwähnen, einen Scharfschützen auf dem Dach des Casinos gesehen zu haben. Seltsam.}
{152}{}{Das ging alles so schnell!}
{153}{}{Lange Zeit wurde in Clean City niemand getötet, besonders keine Polizisten.}
{154}{}{Niemand hatte damit gerechnet, dass es hier passiert ...}
{155}{}{Wer könnte das getan haben?}
