{100}{}{Du siehst einen Karawanenhдndler.}

#Описание, когда ГГ НЕ известно о Черном Караване
{101}{}{Du siehst einen verdдchtigen Karawanenhдndler. Was macht er hier?}

#Описание, когда ГГ известно о Черном Караване
{102}{}{Du siehst einen Karawanenhдndler von der Black Caravan. Er ist eindeutig wegen der Drogen hier.}

#Когда впервые увидят ГГ
{103}{}{Hey, du! Ich seh dich!}
{104}{}{Hab dich, Schlampe!!}
{105}{}{Alarm! Eindringling!}
{106}{}{Ich habe dich nicht hergerufen!}
{107}{}{Sabotage!?}
{108}{}{Ich habe dich im Visier! Du hдltst nicht mehr lange durch!}
{109}{}{Wachen! Eindringling!}
{110}{}{ScheiЯe, die Bullen sind hier!}