{100}{}{Das ist Paul Tibbett.}
{101}{}{Du siehst einen kleinen, dicken Besitzer eines Handelsladens.}

{110}{}{Hey, komm rein, Wanderer! Ich habe gerade nach einer guten Waffe für dich gesucht. Willst du sie dir ansehen?}
{111}{}{Hey, komm rein, Wanderer! Ich habe gerade nach einer soliden Rüstung für deine Reisen durch die Wildnis gesucht. Möchtest du sie anprobieren?!}
{112}{}{Hey, komm rein, Wanderer! Ich habe gerade überlegt, was ein Kunde wie du wohl brauchen könnte. Sieh dich um - vielleicht findest du etwas Nützliches.}

{113}{}{[Als du den Laden betrittst, fällt dir als Erstes der Besitzer auf, der eifrig an irgendeinem Teil herumbastelt. Er trägt eine Baseballkappe, ein T-Shirt und ausgebleichte Jeans. Im Gesicht hat er einen leicht ergrauten Bart im mexikanischen Stil. Ein wandelndes amerikanisches Klischee.]}
{114}{}{Ähem ...}

{116}{}{Hey, triff deine Entscheidung nicht überstürzt! Heute habe ich einen echten Sonderverkauf. Du musst nur diese wunderschönen, glänzenden Waffen bewundern! Eine mächtige Energiewaffe, direkt aus Area 51. Wie bitte? Nun, ein paar verzweifelte Bergleute haben es geschafft, in die Anlage einzudringen und alles zu stehlen, was sie tragen konnten. Aber das ist nicht so wichtig. Wichtig ist, dass du jetzt eine wirklich ausgezeichnete Waffe auswählen kannst.}
{117}{}{Klingt nicht schlecht.}

{118}{}{Oh! Kumpel, ich sehe, du hast es im Leben schon zu etwas gebracht, wenn du auf vier Rädern unterwegs bist. Womit läuft dein Baby? Mit einer Mikrofusionszelle? Hör mal, ich kann extra für dich und deine Schönheit zusätzliche Stromversorgungen anfertigen.}
{119}{}{Wow, das muss ich mir für später merken.}

{120}{}{Lass mich deine Ware ansehen.}
{121}{}{Ich glaube, ich bin hier falsch. Mach's gut.}
{122}{}{Noch mehr oder reicht's?}
{123}{}{Gut, sehen wir uns noch einmal um.}
{124}{}{Äh, nein, das reicht.}

{125}{}{Kannst du ein paar Fragen beantworten, während ich mich umsehe?}
{126}{}{Wie du siehst, verkaufe ich hier keine Informationen. Ich bin nicht der, den du suchst. In Vegas ist es schwer, einen guten Informanten zu finden.}
{127}{}{Vielleicht kannst du mir dann etwas über Vegas erzählen?}
{128}{}{Dann lass uns handeln.}
{129}{}{Vegas! Glitzerndes New Vegas! Die Stadt, die niemals schläft. Äh ... Vielleicht brauchst du eine Schaufel oder eine Packung Kondome?}
{130}{}{Vielleicht schon, aber später. Und was kann man hier machen?}
{131}{}{In Vegas gibt es jede Menge Unterhaltung für jeden Geschmack. Aber erwarte nicht, hier Arbeit zu finden. Alles ist so angelegt, dass das Geld immer zum Clean City fließt und nie wieder herauskommt.}
{132}{}{Erzähl mir vom Clean City.}
{133}{}{Das eingezäunte Gebiet im Norden. Sauber und komfortabel, jede Menge Licht, die Polizei sorgt für Ordnung. Vielleicht willst du dir diese Pracht einmal ansehen. Nirgendwo im Ödland findest du etwas Vergleichbares. Aber die Leute, die dort leben, sind nicht gerade für ihre Großzügigkeit bekannt. Diese Snobs sehen auf jeden und jede herab.}
{134}{}{Gibt es noch andere Gegenden?}
{135}{}{Im Westen liegt das Café „Hard Rock“. Die Gegend ist mehr oder weniger ruhig, aber manchmal kommt es zu Auseinandersetzungen zwischen den örtlichen Gangs und Straßenräubern. Südlich des Cafés liegt Slavertown. Ein unheimlicher und unangenehmer Ort, der von Sklavenhändlern beherrscht wird. Im Osten kannst du zum Hoover Dam gehen, aber es ist weit. Ein Ort mit spektakulärer Aussicht. Beeindruckend!}
{136}{}{Was muss ein Neuankömmling sonst noch über die Stadt wissen?}
{137}{}{Wenn du in einem Clean City bist, vergiss nicht, deine Waffe im Holster zu verstecken. Die örtliche Polizei mag keine Fremden. Auch im Kasino solltest du deine Waffe verbergen. Aber draußen hältst du die Knarre besser griffbereit.}
{138}{}{Alles klar, danke für die Hilfe.}
{139}{}{He, he, he! Ich hab dir alles erzählt, was dein Herz begehrt. Und jetzt gehst du, ohne auch nur irgendetwas zu kaufen?}
{140}{}{Na ja.}
{141}{}{Stimmt – das ist nicht in Ordnung. Hier, 10 $ Trinkgeld.}
{142}{}{Was? Ich sehe mich noch um. Lass uns handeln.}
{143}{}{[Lächelt] Danke. Komm vorbei, wenn du Zeit hast!}
{144}{}{Tschüss.}

{145}{}{Dann habe ich hier nichts zu suchen. Tschüss.}
{146}{}{}

{147}{}{Dann raus aus meinem Laden!}
{148}{}{Dein Laden sieht nicht mehr wie eine Scheune aus. Mach's gut.}
{149}{}{Ich wollte dich nicht beleidigen, tut mir leid. Ich glaube, ich gehe dann.}

{150}{}{}
{151}{}{}
{152}{}{Neu? Ist das nicht eine Vorkriegsstadt?}
{153}{}{Ja! Aber der Glanz der strahlenden Vorkriegsstadt verblasste kurz nach dem Großen Krieg. Jetzt ist alles ganz anders. Deshalb sage ich: Das ist eine new Vegas. Die neue Stadt, eine Oase in der Wüste. Allerdings hat noch niemand diese Idee verwirklicht. Glaub einem alten Mann: Die Zeit wird kommen, und alle werden sie so nennen.}
{154}{}{Du machst das Richtige, wenn du mir vertraust. Sehen wir uns jetzt die Waren an ...}

#Ïğèìåíåíèå íàâûêà áàğòåğ
{158}{}{Du hast ja eine riesige Auswahl. Der Handel hier muss ein sehr einträgliches Geschäft sein.}
{159}{}{Nicht ganz ... Hey, wie lange willst du noch glotzen? Soweit ich sehe, wird es Zeit, etwas zu kaufen.}
{160}{}{Hmm, mal sehen: Der Laden liegt an einem äußerst günstigen Ort, die Bullen sind nicht weit und du verkaufst Waffen. Du bist doch bestimmt mit denen verbandelt, oder?}
{161}{}{[Seufzt] Ich möchte nicht darüber reden, aber du bist zu schlau, um ein gewöhnlicher Kunde zu sein. Die Wahrheit ist: Mein Hauptgeschäft drehte sich um Waffen, aber dann begann die Clean City, sich alle Macht und Geschäfte unter den Nagel zu reißen. Die Bullen wollten nicht, dass Waffen frei gehandelt werden. Deshalb bekomme ich von ihnen Schutz und die Erlaubnis, hier zu arbeiten. Dafür liefere ich jede gute Waffe an Clean Citys Arsenal. So lautet die Vereinbarung. Aber denk dran: Ich erzähle dir das nur, weil du mich in die Enge getrieben hast.}
{162}{}{Ganz schön gerissene Bastarde. Du hast es dir gut eingerichtet. Na schön, tschüss.}
{163}{}{Dank deines Handelsgeschicks hast du 100 Erfahrungspunkte dafür erhalten, das Geheimnis von Tibbetts Geschäft aufzudecken.}
{164}{}{Du hast dein Handelsgeschick erfolgreich eingesetzt und Zugang zu Tibbetts geheimer Auswahl erhalten. Aber sei gewarnt: Das gilt nur dieses eine Mal.}
{165}{}{Hmm ... Wenn du deine Waren mit den Bullen teilst, musst du wohl alles Besondere an einem geheimen Ort sammeln.}
{166}{}{Das ist nur für Privilegierte ... Also für die Vertreter der Clean City. Ich glaube nicht, dass ich Fremden so etwas verkaufen werde. Mein Ruf bei den Clean City ist mir wichtiger.}
{167}{}{Du sagst das, weil du deinem Geschäftspartner nicht trauen kannst. Das kann ich gut verstehen. Ich habe selbst schon so viele Händler erlebt. Denk über meinen Vorschlag nach.}
{168}{}{Ich wusste irgendwie, dass du das sagen würdest.}
{169}{}{[Denkt] Du bist kein gewöhnlicher Kunde, stimmt's? Fähigkeiten wie deine findet man selten. Ich respektiere dein Geschäft – deshalb vertraue ich dir. Na gut, hier habe ich das für die Bullen versteckt. Wenn du etwas davon brauchst, kannst du es kaufen. Aber erzähl bloß niemandem, dass du es von mir hast.}

#Êîîğäèíàòû Ñâàëêè ïîêğûøåê
{170}{}{Hey, hast du etwas Besonderes für meinen Wagen?}
{171}{}{Hmm, lass mich überlegen. Ich habe nichts außer Batterien, aber bei meinem alten Kumpel findest du bestimmt etwas. Früher war er Mechaniker und hieß Skitter, bis er ... zum Ghul wurde. Eine schreckliche Geschichte. Die Einheimischen mögen Ghule hier nicht, deshalb lebt er nicht weit von Vegas entfernt. Als ihm die Menschen zu viel wurden, beschloss er, sich auf einem Reifenfriedhof zurückzuziehen.}
{172}{}{Warum hast du das nicht gleich gesagt! Gut, sag mir, wo dein Freund ist.}

{173}{}{Nicht weit von Vegas, nordöstlich. Allerdings weiß ich die genauen Koordinaten nicht mehr, ich werde alt. Aber der Geruch von Geld könnte mein Gedächtnis auffrischen.}
{174}{}{Wie wär's mit einem Handel? Du brauchst doch sicher frische Waren ...}
{175}{}{Hmm ... Bargeld wäre mir lieber, und die Waren liegen sonst lange im Regal, bis ein Käufer kommt. Hör zu: Ich schreibe dir die Koordinaten auf eine Holodisk, und du kommst wieder, wenn du etwas Nützliches zum Tauschen gefunden hast.}
{176}{}{Na gut, dann handeln wir.}
{177}{}{Dann kann ich auf deine Dienste verzichten, du Erpresser.}

{178}{}{Ha! Du läufst dir die Beine wund, wenn du danach suchst. Aber deine Sache – ob du selbst im ganzen Ödland danach suchst und auf deine Späherfähigkeiten vertraust oder mir einfach die genauen Koordinaten bezahlst. Nur so gesagt.}
{179}{}{Meine Entscheidung ist klar. Ich komme ohne dich zurecht.}

#Øëåì äëÿ ñèëîâóõè
{190}{}{Was ist das für ein Helm, den du verkaufst?}
{191}{}{Nun, in letzter Zeit tauchen seltsame Dinge auf. Man sagt, ein paar mutige Seelen hätten im Nordwesten mit dem Plündern angefangen – dort, wo die Aliens herkommen. Mit den Leuten stimmt doch was nicht. Aber mir kommt das nur zugute.}
{192}{}{Schon gut. Das war alles, was mich interessiert hat. Tschüss.}

#Ïèöà
{200}{}{[Erstaunt blickt er auf die Pizza in deinen Händen und dann auf die Uhr.] Junge, du bist langsamer als ein brahmin-Wagen voller altem Gerümpel. Wo hast du die ganze Zeit gesteckt? Du bist zu spät. Also kannst du sie zurück ins Café bringen und meine Kündigung überbringen. Ich bezahle nicht.}
{201}{}{[Gehen]}
{202}{}{Pizza! Gerade noch rechtzeitig. Gib sie her, jetzt werde ich sie mir schmecken lassen, he-he.}
{203}{}{Natürlich, Sir. Hier. Sie schulden mir }
{204}{}{$.}
{205}{}{Äh, wie viel?}
{206}{}{$ für die Pizza und 10 $ für die Lieferung ... Gibt es ein Problem, Sir?}
{207}{}{Nun, eigentlich waren es 5 $, als ich die Lieferung bestellt habe, also ... Macht es Ihnen etwas aus? [gibt das Geld und greift nach der Pizza]}
{208}{}{Natürlich, Sir. Abgemacht waren 5 $, also bitte sehr. Schönen Tag noch!}
{209}{}{Auf keinen Fall. Die Lieferung kostet *10 $*! Entweder du bezahlst, oder ich nehme die Bestellung wieder mit.}
{210}{}{Danke, Kurier! Es ist angenehm, mit so pflichtbewussten Mitarbeitern wie denen von Phillips zu tun zu haben. Richte ihm Grüße von mir aus.}
{211}{}{Schönen Tag noch!}
{212}{}{Oh, natürlich. Ich werde mich darum kümmern und bei der Gelegenheit auch nachfragen, wann Sie bestellt haben ... um die Preispolitik in Ihrem Fall zu überarbeiten.}
{213}{}{[Stirnrunzelnd und nervös blickend zählt er 5 $.] Na gut, na gut. Denk bloß nicht, dass ich das vergessen werde.}
{214}{}{[Stirnrunzelnd und nervös blickend zählt er das Geld.] Du glaubst, ich würde lügen, was? Du willst mir doch nicht etwa unterstellen, ich wäre ein Dieb, nur weil ich die 5 $ vergessen habe? Verdammt, ich habe den besten Laden in ganz Vegas! Ach, was soll ich sagen, du bist ja nur ein Kurier.}
{215}{}{Sir, ich versichere Ihnen – so etwas hatte ich gar nicht im Sinn. Sie sehen aus wie ein respektabler Mann! Ich würde niemals vermuten, dass Sie lügen könnten. Wirklich!}
{216}{}{[Gehen]}
{217}{}{[Grinst schief und richtet den Kragenknopf] Na ja, stimmt schon ... Ich weiß. Mach dir keine Sorgen, ich bin heute etwas nervös, vergiss es einfach. Beim nächsten Mal nenne ich den Preis, bevor du bestellst. Viel Glück und ... pass auf dich auf, Kurier.}

#Female character
{1110}{}{Hey, komm rein, Wanderer! Ich habe gerade nach einer guten Waffe für dich gesucht. Willst du sie dir ansehen?}
{1111}{}{Hey, komm rein, Wanderer! Ich habe gerade nach einer soliden Rüstung für deine Reisen durch die Wildnis gesucht. Möchtest du sie anprobieren?!}
{1112}{}{Hey, komm rein, Wanderer! Ich habe mich gerade gefragt, was ein Kunde wie du wohl brauchen könnte. Sieh dich um – vielleicht findest du etwas Nützliches.}
{1118}{}{Oh! Gnädige Frau, ich sehe, Sie haben es im Leben schon zu etwas gebracht, wenn Sie auf vier Rädern unterwegs sind. Womit fährt Ihr Baby? Mit einer Mikrofusionsbatterie? Sehen Sie, ich kann extra für Sie und Ihren stählernen Hengst zusätzliche Energiequellen anfertigen.}
{1121}{}{Ich glaube, ich bin hier falsch. Mach's gut.}
{1149}{}{Ich wollte dich nicht beleidigen, tut mir leid. Ich glaube, ich gehe dann.}
{1167}{}{Du sagst das, weil du deinem Geschäftspartner nicht trauen kannst. Das kann ich gut verstehen. Ich habe selbst schon so viele Händler erlebt. Denk über meinen Vorschlag nach.}
{1168}{}{Ich wusste irgendwie, dass du das sagen würdest.}
