{100}{}{Du siehst: „AVCS“.}
{101}{}{Du siehst die Zentraleinheit der automatisierten Vault-Kontrollsysteme.}

{110}{}{Du siehst die Zentraleinheit der automatisierten Vault-Kontrollsysteme. Genau hier gehört das Gerät hin, das Jay Kukish gestohlen hat.}
{111}{}{[Gehen]}
{112}{}{[Selbstzerstörung des Labors einleiten]}
{113}{}{[Eine Flucht aus dieser Ebene ist unmöglich. Du wirst also zusammen mit den Brutkästen sterben. Bist du sicher?]}
{114}{}{So ist's recht ... [Selbstzerstörung einleiten]}
{115}{}{Schließ das Gerät an und leite die Säuberung des Vaults von Feinden ein.}
