{100}{}{Das ist ein Scheißeposter.}
{101}{}{Du siehst ein wildes Wesen, das vage an einen Menschen erinnert und an den Schandpfahl gebunden ist, damit jeder Passant *ihm* ins Gesicht spucken kann.}

{110}{}{Du siehst einen schmutzigen, hässlichen Jungen. Er ist an einen Pfahl gebunden, damit jeder ihn treten oder bespucken kann. Neben ihm hängt ein Schild, auf dem sein Verbrechen steht: „Scheißeposter. Bestraft, weil er andere und sich selbst wie Scheiße behandelt hat.“}
{111}{}{[Tritt ihm kräftig in die Eier!]}
{112}{}{[Spuck ihm ins Gesicht.]}
{113}{}{Hey, Kleiner. Haben sie dich zu Recht an den Pfahl gebunden?}
{114}{}{Hey, warte mal, Kumpel! Ich mach dich los!}
{115}{}{[Lass ihn in Ruhe]}

#Spit on Shitposter
{120}{}{[Der Junge fängt plötzlich an, sich ekstatisch den Kopf einzuschlagen.] AH! AHHH! [Anscheinend gefällt es ihm, wenn du ihn anspuckst.] A-A-Ah!!!}
{121}{}{[Spuck ihm noch einmal ins Gesicht]}
{122}{}{Oh!!! O-o-o-oh!!! A-a-ah!!! [Der Junge ist von deinen Taten fast wie berauscht und will mehr.]}
{123}{}{[Na gut, warum nicht? Noch einmal ausspucken.]}
{124}{}{Mhm!!! [Der Kopf dieses Wahnsinnigen fängt an, schneller zu schlagen.] M-m-m!!! [Er schien jeden Rest gesunden Menschenverstands verloren zu haben.]}
{125}{}{Okay, das reicht. Na ja, zum Abschied sollte ich noch einmal ausspucken!}
{126}{}{Nein, genug ist genug.}
{127}{}{AAARGH!!! [Dieser Irre schlägt seinen Kopf mit solcher Wucht gegen den Pfahl, dass ihm Blutstropfen vom Kopf tropfen!]}
{128}{}{Hey! Warte! Was machst du da?! Beruhig dich!!!}
{129}{}{Das hast du davon! Komm schon! Noch mal!}

#conversation or the kick in the nuts
{130}{}{Oh, du verdammter Cowboy!!! Ah!!! [Offenbar war sein Geschlechtsorgan seine empfindliche Stelle. Seiner Würde beraubt, stirbt der Shitposter und spuckt dabei eine riesige Menge weißen Schaum aus.]}
{131}{}{Äh ... Wie widerlich.}
{132}{}{Verdammte Beschützer der Unschuldigen! Ich hasse euch alle, verdammt! Arrgh! Ich pinkle euch an, bis euch die Pisse zum Hals steht! Hände weg von den Seilen! Weg da!}
{133}{}{Warum reagierst du so auf Hilfeversuche? Glaubst du, du verdienst es, bestraft zu werden?}
{134}{}{Äh, okay. Kein Problem. Beruhig dich.}
{135}{}{Ja! Ja!!! JA!!! Ich bin ein Tier! Ich bin eine hinterhältige Schlampe! Ich hab's mit meiner Mutter getrieben und mein Vater mit mir! Ich bin erledigt! Ich will, dass mich alle hassen! ALLE!}
{136}{}{Hm. Weißt du, du wirkst nicht gerade geisteskrank. Ich glaube, du gibst nur an und versuchst, etwas Besonderes zu sein.}
{137}{}{Du hast recht, und dafür hau ich dir in die Eier!}
{138}{}{Na ja, wie auch immer, das ist deine Sache ...}
{139}{}{Du! Du! Du hast kein Recht! Nein!... Geh weg von mir! Lass mich los!}
{140}{}{Ja! Ich hatte recht, siehst du? Sonst hättest du mich von Anfang an ignoriert, aber du hast erst darüber nachgedacht und dann nach Ausreden gesucht. Du bist ein Großmaul.}
{141}{}{Grrrr! Ja, ich bin ein Großmaul! Ein Großmaul! Ein Großmaul! Ein Großmaul!!! Bist du jetzt zufrieden?!}
{142}{}{Und jetzt gibst du es nur zu, damit du noch mehr Prügel kassierst. Hör auf, dich so aufzuführen, und geh nach Hause. Schluss damit, dich vor den Erwachsenen zu blamieren!}
{143}{}{[Schluchzt] Wie kannst du es wagen! Ich habe so viel getan, nur um an einen Pfahl gebunden und von allen bespuckt zu werden, und jetzt ziehst du mich zurück! Nein! NEIN!!!}
{144}{}{Ja, Kumpel, JA! Schluss damit. Zeit, wieder zur Vernunft zu kommen. Jeder hat mal in die Hose gemacht. Das ist ganz normal.}
{145}{}{Verdammt! Ich hasse dich so sehr! [du bindest Shitposter los, und er macht sich auf den Heimweg] Oh, ich HASSE dich!!!}
{146}{}{Glaub ich nicht, du bist zu selbstgefällig. Wenn du lernst, dich nicht für etwas ganz Besonderes zu halten, wird alles gut.}

#Women's replics
{1130}{}{Oh, du verdammte Fotze!!! Ah!!! [Anscheinend war sein Fortpflanzungsorgan seine empfindliche Stelle; nachdem er seine Würde verloren hat, stirbt der Shitposter und presst eine riesige Menge weißen Schaum aus seinem Mund.]}
{1132}{}{Verdammte Beschützer der Unschuldigen! Ich hasse euch alle, verdammt! Arrgh! Ich pinkle euch an, bis euch die Pisse zum Hals steht! Hände weg von den Seilen! Weg da!}
{1140}{}{Ja! Ich hatte recht, siehst du? Sonst hättest du mich von Anfang an ignoriert, aber du hast erst darüber nachgedacht und dann nach Ausreden gesucht. Du bist ein Großmaul.}
{1141}{}{Grrrr! Ja, ich bin ein Großmaul! Ein Großmaul! Ein Großmaul! Ein Großmaul!!! Bist du jetzt zufrieden?!}
