{100}{}{Du siehst einen alten Bekannten.}
{101}{}{Du siehst den Gefangenen vom Wind des Krieges!}

#Different things
{102}{}{Du hast einen Hinweis auf die Existenz des geheimen Labors außerhalb der Stadt erhalten.}
{103}{}{Hrrm ... Yah ... Das wird der betrunkenste Staat Amerikas sein ... Hrrm ...}
{104}{}{Hallo, Freund!}

#First dialogue [booze] 
{110}{}{Heh-he! Mein Freund! Da bist du ja! Ich wusste, dass du herkommen würdest! Lass mich dir einen ausgeben! Hey, Barkeeper! Schreib's auf meine Rechnung!}
{111}{}{Also, du hast es geschafft, vom Wind des Krieges zu fliehen. Werden sie nicht nach dir suchen?}
{112}{}{Auf keinen Fall! Diese Militäridioten trauen sich nicht mal in die Nähe von Vegas! Keine Sorge, Kumpel! Hier sind wir sicher.}
{113}{}{Sind sie hier in Vegas nicht gerade beliebt?}
{114}{}{Sie werden hier *gehasst*. Diese Bastarde werden sofort aus Clean City rausgeschmissen.}
{115}{}{Warum?}
{116}{}{Weil sie glauben, sie wären knallhart und könnten tun, was sie wollen. So viele von unseren Leuten wurden von ihnen auf der Straße zwischen Vegas und dem Wind getötet ... Oh ... Trinken wir auf sie! [Er leert eine halbe Flasche Bier]}
{117}{}{Hey! Ist das nicht ein bisschen viel?}
{118}{}{Alles bestens, Kumpel! [Er rülpst]}
{119}{}{Du wirkst schon ganz benommen!}
{120}{}{Ha-ha-ha! Selbst betrunken würde ich jeden umhauen! Wetten? Dich schlage ich auch!}
{121}{}{Hey! Hör auf!}
{122}{}{Ha-ha-ha! Keine Angst, Kumpel! [He slaps your shoulder] Für dich würde ich jeden abschlachten! Soll ich den Barkeeper abstechen?!}
{123}{}{Äh ... Nein. Ich brauche ihn noch.}
{124}{}{Na ja ... Ja, er gibt mir auch Bier ... Jep. O-okay.}
{125}{}{Gibt? Einfach so? Umsonst?}
{126}{}{Ha! Was ist los, Kumpel?! Weißt du nicht, mit wem du redest?! [weighty pokes himself in the chest with his thumb] Weißt du, WER vor dir steht?!}
{127}{}{Ja. Der Typ, der der Todesstrafe entkommen ist.}
{128}{}{Äh, nein! Hal Wallace persönlich setzt sich für mich ein. Er selbst! Ganz persönlich. Er hätte mich aus dem Gefängnis geholt, da bin ich sicher.}
{129}{}{Wow! Der Besitzer dieses Casinos?! Wieso denn?}
{130}{}{Ha! Als ob ich dir das erzählen würde!}
{131}{}{Ich verrate es niemandem!}
{132}{}{Nein! Frag erst gar nicht!}
{133}{}{Ach, komm schon! Ich hab dich gerettet!}
{134}{}{Verdammt! Stimmt ... Na gut! Wenn du es bist - ich bin ... Dieses Ding, wie heißt es ...}
{135}{}{Ein Leibwächter?}
{136}{}{Was? Zum Teufel mit dem Leibwächter! Nein ...}
{137}{}{Ein Verwalter?}
{138}{}{Äh?! Nein, warte ... Ich bin ... Mir fällt's gleich ein ...}
{139}{}{Angestellter? Lagerarbeiter? Putzkraft? Masseur? Was denn?!}
{140}{}{Hey, hör auf! Lass mich nachdenken! ... Ah, ja! Ein Kurier!}
{141}{}{Ein Kurier? Du hast ganz schön lange gebraucht, um dich daran zu erinnern. Was ist daran so geheimnisvoll?}
{142}{}{Na ja, weißt du, das bringt mich an Orte. Die Einzelheiten solltest du lieber nicht kennen. Gefährliche Orte. Außerhalb der Stadt.}
{143}{}{Jetzt wirst du aber geheimniskrämerisch ... Als ob außerhalb der Stadt Leute leben würden.}
{144}{}{Nein, sie leben nicht dort. Aber sie verdienen dort ein bisschen Geld ... [winks and sips the second half of beer]}
{145}{}{Oh, das ist genau mein Gebiet! Wo ist das? Wo kann ich Geld verdienen?}
{146}{}{[Hört dir nicht zu] Ah, Mist, ist leer. He! Barkeeper! Gib mir Bier! Sofort!}
{147}{}{[Weiter]}
{148}{}{Was faselst du da, du?! Du willst mir kein Bier geben?! Ich frage dich nicht, ich befehle es dir!}
{149}{}{He, beruhig dich. Ich bestelle dir eine Flasche. Barkeeper! Schreib's auf meine Rechnung!}
{150}{}{[Lass sie in Ruhe]}

{151}{}{Kumpel ... Nein – Freund! Ja! Freund, du hast mir wieder mal ausgeholfen [rülpst]. Dieser großohrige Widerling weigert sich immer, mich nach der zweiten Flasche zu bedienen ... Ach ja, wo waren wir?}
{152}{}{Der Ort außerhalb der Stadt, wo man etwas Geld verdienen kann ...}
{153}{}{Ach ja! Dort im Labor wird so viel Geld gemacht, oh mein Gott! Du würdest es nicht glauben. Für eine Lieferung ... [scheint gleich einzuschlafen] für eine einzige Lieferung bekomme ich ... Ich ... bekomme ... Zzzz ...}
{154}{}{[Von ihm wirst du jetzt nichts mehr erfahren]}

{200}{}{Ja, pass auf dich auf.}
{201}{}{Freund, du hast gesagt, du arbeitest für den Casinobesitzer. Könntest du mich bei ihm empfehlen?}
{202}{}{[Schaut sich nervös um] Äh, hör zu, mein Rat: Geh als Hausmeister arbeiten. Zum Beispiel bei Hoover dam. Es gibt nicht genug Sklaven. Mr. Wallace braucht erfahrene Leute, und du siehst nicht so aus, als wärst du einer.}
{203}{}{Bin ich so schlecht? Na ja ...}
{204}{}{[Schaut sich nervös um] Pass auf, ich sag's dir: Mr. Wallace bietet ... eine Art „schmutzige“ Arbeit an, nichts für Leute, die sich die Hände sauber halten. Du verstehst, oder? [Er zwinkert dir seltsam zu]}
{205}{}{Ich bin für jede Art von Arbeit zu haben.}
{206}{}{Dann lasse ich es lieber. Tschüss.}
{207}{}{Verdammt. Na gut, auf meine Verantwortung. Mr. Wallace ist im dritten Stock. Geh zu seinen Wachen und sag ihnen [er setzt eine wichtige, selbstgefällige Miene auf], dass Sam Riley selbst dich empfohlen hat.}
{208}{}{Danke, Mann!}
{209}{}{Mit Dank bezahlst du keine Rechnungen.}
{210}{}{Stimmt, hier sind 50 Kröten.}
{211}{}{Wie bitte?! Ich hab dir den Arsch gerettet, was willst du noch?}
{212}{}{Äh, okay. Aber jetzt sind wir quitt – du hast mich gerettet, und ich habe dich Mr. Wallace vorgestellt. [Er lächelt und zwinkert dir zu; irgendetwas sagt dir, dass es nicht so einfach wird.]}
{213}{}{Oh ... Okay, tschüss.}
{214}{}{[Nimmt das Geld] Zusammen sind wir echt ein gutes Team. Ich will dich als Freund warnen. Mr. Wallace mag kein leeres Gerede. Wenn er dich um etwas bittet, tu es, ohne Fragen zu stellen. Sonst ... [fährt sich mit dem Daumen über die Kehle]}
{215}{}{Verstanden.}

#Women's replics
{1104}{}{Hallo, Freund!}
{1110}{}{He-he! Mein Mädchen! Da bist du ja! Ich wusste, dass du herkommen würdest! Lass mich dir einen Drink spendieren! Hey, Barkeeper! Schreib's auf meine Rechnung!}
{1112}{}{Auf keinen Fall! Diese Militäridioten trauen sich nicht einmal in die Nähe von Vegas! Keine Sorge, Baby! Hier sind wir sicher.}
{1118}{}{Schon gut, Baby! [Er rülpst]}
{1122}{}{Ha-ha-ha! Hab keine Angst, mein Mädchen! [Er klopft dir auf die Schulter] Für dich würde ich jeden abschlachten! Soll ich den Barkeeper abstechen?!}
{1126}{}{Ha! Was ist los, Kleine?! Weißt du nicht, mit wem du redest?! [sticht sich wichtigtuerisch mit dem Daumen in die Brust] Ist dir klar, WER vor dir steht?!}
{1133}{}{Ach, komm schon! Ich hab dich gerettet!}
{1151}{}{Freund ... Nein, Schwester! Ja! Sis, du rettest mich schon wieder. Dieser großohrige Widerling weigert sich immer, mich nach der zweiten Flasche noch zu bedienen ... Ach ja, wo waren wir?}
{1205}{}{Ich bin für jede Arbeit zu haben.}
{1207}{}{Jede Arbeit? Im Ernst? [mustert dich von Kopf bis Fuß] Für solche Beine findet Mr. Wallace bestimmt ein Paar Schuhe ... mit *Mordabsätzen*, wenn du verstehst, was ich meine. Mr. Wallace ist im dritten Stock. Sag seinen Wachen [macht ein äußerst wichtiges und wichtigtuerisches Gesicht], dass Sam Riley dich empfohlen hat.}
{1211}{}{Wie bitte?! Ich hab dir den Arsch gerettet, was willst du noch?}
{1212}{}{Äh, okay. Aber jetzt sind wir quitt – du hast mich gerettet, und ich habe dich Mr. Wallace vorgestellt. [Er lächelt und zwinkert dir zu; irgendetwas sagt dir, dass es nicht so einfach wird.]}
