{100}{}{Du hast auﬂerhalb von Vegas ein groﬂes Drogenlabor gefunden. Du bist hier eindeutig nicht willkommen.}

{101}{}{Puh! Fast erwischt worden ...}
{102}{}{Gerade noch geschafft!}
{103}{}{Nur ein bisschen mehr, und sie h‰tten mich gesehen!}
{104}{}{Ich glaube, sie haben mich nicht gesehen ...}
{105}{}{Gut, sie haben mich nicht gesehen ...}
{106}{}{He-he, denkst du, du siehst mich? Nein, tust du nicht!}
