{100}{}{Du siehst Oscar Davis.}
{101}{}{Du siehst Oscar Davis, den Polizeichef. Das Namensschild auf seiner Brust verrät es.}

#Íà÷àëüíûå âîïðîñû:
{110}{}{Also, Bürger. Ich höre.}
{111}{}{Ich habe nichts getan. Ich gehe.}
{112}{}{Wusstest du, dass Hal Wallace in schmutzige Geschäfte verwickelt war?!}
{113}{}{Mr. Davis, ich suche Arbeit. Können Sie mir helfen?}
{114}{}{Einer Ihrer Polizisten hat mich angegriffen. Das ist eine Unverschämtheit!}
{115}{}{Ich suche die Koordinaten von Area 51. Wissen Sie vielleicht, wo sie liegt?}
{116}{}{Was das Problem mit den Ghulen angeht.}
{117}{}{Über den Markt für „schwarze“ Chemikalien.}
{118}{}{Was das Problem mit Sam Phillips angeht.}
{119}{}{Mich interessiert, warum der Bürgermeister ausgerechnet *mich* als Privatdetektiv angeheuert hat.}

#Ìýð íàíÿë ÷óçà:
{120}{}{Privatdetektiv? Ich wusste gar nicht, dass es so etwas im Ödland gibt.}
{121}{}{Ich glaube, er traut dir nicht und hält dich für einen Scheißkerl, der nicht fähig ist, seine Arbeit ordentlich zu erledigen. Aber mich hat er als Spezialisten anerkannt!}
{122}{}{Ich glaube, der Bürgermeister traut dir nicht. Findest du nicht auch?}
{123}{}{Ja, das kommt manchmal vor. Bis später.}

{124}{}{Freu dich nicht zu früh, Mr. Überheblichkeit. Mal sehen, wie viel Scheiße aus dir herauskommt, wenn du am Pranger stehst.}
{125}{}{Am Pranger? Du wirst mich nicht dorthin schleppen! Auf keinen Fall!}
{126}{}{Whoa, okay, ich verstehe schon. Alles gut, Mr. Davis. Kein Problem.}

{127}{}{Du solltest dir überlegen, ob er *dir* vertraut. Wir jedenfalls sorgen schon lange für Ordnung in der Stadt ...}
{128}{}{Ich untersuche die jüngsten Verbrechen in der Stadt. Der Bürgermeister glaubt, dass sie alle zusammenhängen. Kannst du mir die Einzelheiten nennen?}
{129}{}{In der Stadt ist gerade eine Menge los. }
{130}{}{In den letzten Jahren hat der Drogenhandel zugenommen. In der Stadt gibt es ganz offensichtlich ein Labor, aber wir konnten es nicht finden.}
{131}{}{}
{132}{}{Sam Phillips wird der Drogenherstellung beschuldigt. }
{133}{}{Die Freaks werden der Drogenherstellung und des Drogenhandels beschuldigt. }
{134}{}{Die Freaks werden der Drogenherstellung und des Drogenhandels beschuldigt, aber unser Trupp hat diese Bedrohung bereits beseitigt. }
{135}{}{Außerdem gibt es ein separates Problem: Die Tochter eines örtlichen Archivars ist verschwunden. }
{136}{}{Ich glaube, das war alles.}
{137}{}{Kürzlich wurde jemand mit der Pistole von Bob Neil erschossen. Bob Neil wurde ins Gefängnis gesteckt.}
{138}{}{Kürzlich hat Clean City Hal Wallace beerdigt. Möge er niemals vergessen werden.}
{139}{}{Danke für die Informationen. Noch eine Frage.}
{140}{}{Danke für die Informationen. Das war alles.}

#Ïðî Óîëëèñà
{150}{}{Bist du dir der Verantwortung für das bewusst, was du gesagt hast?}
{151}{}{Natürlich. Er hat versucht, mich dazu zu überreden, den Freaks ... äh, ich meine den Ghulen, Drogen zu verkaufen. Dieses Gespräch wurde aufgezeichnet.}
{152}{}{Natürlich. Ich habe einen Beweis – hier ist eine Aufzeichnung des Gesprächs, in dem er mich zu einem Verbrechen gegen Bob Neil anstiften wollte.}
{153}{}{Vielleicht bin ich noch nicht bereit. Noch eine Frage.}
{154}{}{Vielleicht bin ich noch nicht bereit, die Verantwortung zu übernehmen. Mach's gut.}

{155}{}{Ich werde mir diese Aufzeichnung ansehen. Aber ich kann nichts versprechen.}
{156}{}{Ich vertraue dir nicht! Das ist gelogen! Gib mir den Beweis zurück, du verdammter Bulle!!!}
{157}{}{Werde ich dafür belohnt?}
{158}{}{Das ist gut. Ich hoffe, die Gerechtigkeit wird siegen.}

{159}{}{Nein.}
{160}{}{Schade. Wirklich schade.}
{161}{}{Das ist ein wichtiger Beweis. Also, gib mir die Holodisk. Ich brauche etwas Zeit, um sie zu untersuchen.}
{162}{}{Ich glaube dir nicht! Du lügst!}
{163}{}{Nein, ich kann dir die Originalaufnahme nicht geben.}
{164}{}{Na klar. Hier ist die Aufnahme. Ich hoffe, sie löst sich nicht in deinen Händen in Luft auf.}
{165}{}{Danke, Bürger. Wir werden eine Entscheidung treffen, aber das wird dauern.}
{166}{}{Was auch immer du sagst. Ich hoffe nur, dass die Verbrecher bestraft werden.}

{167}{}{Bürger, ich frage dich nicht. Verstehst du, wovon ich rede? Überleg dir deine Weigerung noch einmal.}
{168}{}{Du drohst mir! Na, dann *versuch* doch, mir die Beweise abzunehmen, Bulle!}
{169}{}{Entschuldigen Sie, Mr. Davis. Ich habe nicht gleich verstanden, worum es geht. Hier ist die Holodisk.}

#Ïðî êîïîâ-êèëëåðîâ
{170}{}{[Spöttisch] Tsk, tsk, tsk. Ach ja? Ein Killer-Cop?! Das ist mir neu.}
{171}{}{Was auch immer du sagst. Noch eine Frage.}
{172}{}{Na dann, tut mir leid, dass ich dich gestört habe.}
{173}{}{Ich bin nicht hier, um Spielchen zu spielen. Findest du es etwa schön, wenn man dir mit dem Lauf eines Revolvers ins Gesicht stochert?!}
{174}{}{Vielleicht war es Inspektor Callahan. Nun, das gehört zu den Besonderheiten seiner Arbeit – manchmal geht er zu weit. Ehrlich gesagt haben seine Methoden früher viele Leben gerettet, aber heutzutage sind sie etwas veraltet. Ich werde die Entlassung des Inspektors zur Sprache bringen und mich für die Unannehmlichkeiten entschuldigen.}
{175}{}{Und ich finde, deine Worte klingen nicht besonders aufrichtig. Ich sage es nur einmal: Niemand stellt sich mir in den Weg. Merk dir das, Davis. Man sieht sich.}
{176}{}{Na gut, dann lasse ich dich in Ruhe.}
{177}{}{Ist das alles, was du zu sagen hast!? Ich gehe nicht, bevor du zugibst, dass du einen Killer auf mich angesetzt hast!}
{178}{}{Eine Amtsperson zu beleidigen, die Polizei zu verleumden und sich so ignorant zu benehmen – für mich reicht das aus, um Gewalt anzuwenden. [beugt sich zu dir und sagt mit zusammengebissenen Zähnen] Willst du's drauf anlegen? Gib mir nur einen Grund!}
{179}{}{Oh wow, Drohungen vom Polizeichef! Wie ironisch! Du solltest erst mal den Staub von deinem Abzeichen wischen, Arschloch, und deine Hose hochziehen, bevor du für die Behörden sprichst.}
{180}{}{[Wütend und rot im Gesicht] Letzte Warnung!}
{181}{}{Du wagst es, vor aller Augen einen unbewaffneten Mann anzugreifen?! Na los, nur zu! Tu es! Zeig mir, was du draufhast, du fettes Stück Scheiße in Uniform!}
{182}{}{Na komm! War doch nur Spaß ...}

#Ïðî âûðîäêîâ
{183}{}{Ja, es gibt so ein Problem. Verdammte Degenerierte!}
{184}{}{Ich bin gekommen, um ihre Unschuld zu beweisen. Ich habe Beweise dafür, dass man ihnen eine Falle gestellt hat.}
{185}{}{Ich konnte Larry Geller dazu bringen, ein Geständnis abzulegen. Hier ist die Holodisk mit dem aufgezeichneten Gespräch.}
{186}{}{Ich will aussagen, dass sie Drogen vertreiben! Ihr könntet es sofort überprüfen! Sie haben ganze Päckchen mit Drogen in Kisten liegen. Ich kann es euch zeigen.}
{187}{}{Könntest du mir mehr über diesen Konflikt erzählen?}

{188}{}{Es ist ganz einfach. Die Abschaumtypen stellen eine starke Droge her und vertreiben sie in der ganzen Stadt. Das einzige Problem ist, dass wir sie noch nicht auf frischer Tat ertappen konnten. Aber das werden wir. Darauf kannst du dich verlassen.}
{189}{}{Vielleicht ist das alles, was ich über sie wissen wollte.}
{190}{}{Schon wieder so ein Beschützer wilder Tiere! Wie willst du das denn anstellen, hm?}
{191}{}{Lies das. Ich denke, die Handschrift zu identifizieren, dürfte nicht allzu schwierig sein.}
{192}{}{Sag deinen Schoßhündchen, dass sie weiterhin in dieser Stadt bleiben können ... vorerst. Aber eines Tages finde ich heraus, was hier wirklich vor sich geht. Und dann wird sie nichts mehr retten, nicht einmal dieses erbärmliche Stück Papier! [presst wütend ein Dokument in der Hand zusammen]}
{193}{}{Was hast du da über Schoßhündchen gesagt, hm?! Ich zeig dir, wer hier ein Schoßhündchen ist, du verdammtes Arschloch mit Abzeichen!}
{194}{}{Schon besser!}
{195}{}{Na komm, reg dich nicht so auf! Das sind gute Leute! Du wirst schon sehen.}

{196}{}{Sehr gute Nachrichten! Endlich machen wir dieser Plage in der Stadt ein Ende. Und Bürger wie du werden für gewöhnlich auf deutlich großzügigere Weise belohnt. [drückt dir 2000$ in die Hand] Hier ist deine Belohnung.}
{197}{}{Ihr bereitet einen Überfall auf sie vor, oder? Ich will mitmachen!}
{198}{}{Danke für das Geld.}
{199}{}{Eine zusätzliche Waffe kann nicht schaden. Ich bin dabei. Wir brechen sofort auf. Bist du bereit?}
{200}{}{Klar! Los geht's!}
{201}{}{Auf keinen Fall. Du musst ohne mich los. Viel Glück!}
{202}{}{Ich brauche nur vertrauenswürdige Leute. Tut mir leid, Bürger.}
{203}{}{Schade.}
{204}{}{Ich bin so froh, das zu hören, dass ich gar nicht erst fragen werde, wie du das herausgefunden hast. Endlich werden wir dieser Plage in der Stadt ein Ende setzen. Und Bürger wie du werden gewöhnlich mit klingender Münze belohnt. [gibt dir 2000$] Hier ist deine Bezahlung.}

#Ïðî Ñýìà Ôèëëèïñà:
{205}{}{Noch ein Splitter im Leib der Stadt. Bei der Durchsuchung haben wir eine gelbe Substanz gefunden, vermutlich eine Zutat für Drogen. Unsere Experten konnten ihren genauen Zweck allerdings noch nicht bestimmen.}
{206}{}{Ja, das ist eindeutig eine Zutat. Hier, sieh mal. Ein Drogenhändler aus Salt Lake liefert sie an Phillips.}
{207}{}{Das ist ein Emulgator E30 – ein Nahrungsergänzungsmittel. Sonst nichts.}
{208}{}{Kann ich in diesem Fall als Privatdetektiv helfen?}
{209}{}{Er ist unschuldig! Er ist ein guter Mann!}
{210}{}{Ich hoffe, du wirst dieses Problem lösen. Ich muss jetzt gehen.}
{211}{}{Warum bist du dir da so sicher, Bürger?}
{212}{}{Ähm, na ja, ich weiß es einfach. Reicht das nicht?}
{213}{}{Na ja, ich bin mir nicht sicher.}
{214}{}{Bring mich nicht zum Lachen. Wir werden Phillips nicht hinterherjagen, nur weil irgendwer beschlossen hat, sich über ihn zu beschweren. FAKTEN! Wir brauchen Fakten!}
{215}{}{In Ordnung.}
{216}{}{Hier ist ein Emulgator – ist das die Substanz, die ihr gefunden habt? Das ist doch nur ein Nahrungsergänzungsmittel!}

{217}{}{Sehr gut. Vielleicht gelingt es dir als Zivilist, das Vertrauen von Phillips und seinen Leuten zu gewinnen. Dann bekommen wir die Chance, den Verbrecher gerecht und offen zur Strecke zu bringen.}
{218}{}{Gut. Ich werde mir die Sache ansehen. Werde ich für meine Hilfe belohnt?}
{219}{}{Gut. Ich werde mir die Sache ansehen.}
{220}{}{Du?! Damit machst du alles nur noch schlimmer. Kümmere dich um deinen eigenen Kram, Bürger.}
{221}{}{Na gut.}
{222}{}{Natürlich bezahlen wir gute Arbeit.}
{223}{}{Na gut. Ich mache mich an die Arbeit.}

{224}{}{Nahrungsergänzungsmittel?! Damit kommst du mir nicht durch! Das ist doch lächerlich! Ich bin doch nicht so blind, dass ich eine Droge nicht von Lebensmitteln unterscheiden kann!}
{225}{}{Anscheinend ist es so.}
{226}{}{Na ja, wenn du dir so sicher bist, dann natürlich.}
{227}{}{Diese Beweise reichen wohl aus. Wir werden deine Identität geheim halten. Und Sam Phillips wird bald verhaftet. Vielen Dank für deine Hilfe bei den Ermittlungen. Du hast eine höhere Belohnung verdient. [gives 2000$]}
{228}{}{Geld ist immer gut.}

#Ïîèñê ðàáîòû:
{229}{}{Du bist nicht von hier? Dann könnten wir ein Geschäft machen.}
{230}{}{Ich höre mir dein Angebot an.}
{231}{}{Weißt du, ich habe es mir anders überlegt. Bis dann.}
{232}{}{Ich habe nichts für dich. Außerdem muss ich sagen, dass es in der Stadt generell schwer ist, Arbeit zu finden.}
{233}{}{Dann eine andere Frage.}
{234}{}{Dann vergiss es. Bis dann.}
{235}{}{Eine Angelegenheit ist noch ungeklärt und wartet auf eine endgültige Entscheidung: der Fall Sam Phillips, dem Besitzer des Cafés „Hard Rock“.}
{236}{}{Was hat er getan?}
{237}{}{Ihm wird vorgeworfen, eine abscheuliche Droge herzustellen und zu vertreiben. Das wissen wir dank einiger Indizien, aber ich bin fest davon überzeugt, dass es stimmt. Besonders, seit wir in seinem Café eine höchst verdächtige Substanz gefunden haben.}
{238}{}{Du willst, dass ich ermittle, wo sich sein Labor befindet?}
{239}{}{Im Grunde kommt das Labor ohne seinen Besitzer nicht weit. Wir sollten uns um Sam Phillips selbst kümmern.}
{240}{}{Du willst also, dass ich Beweise gegen ihn finde?}
{241}{}{Mir ist inzwischen egal, wie du das anstellst, aber wir müssen diesen Mann aufhalten! Um jeden Preis ... Verstanden?}
{242}{}{Oh! Ich sehe, worauf das hinausläuft! Das hättest du gleich sagen sollen – bring den armen Kerl einfach grundlos um. Ohne mich.}
{243}{}{Nun, manchmal müssen Verbrecher auch mit ungesetzlichen Mitteln bestraft werden. Ich helfe dir, etwas Belastendes über den Mann zu finden.}
{244}{}{Sehr gut. Ich warte auf gute Neuigkeiten.}
{245}{}{Na dann, ich mache mich an die Arbeit.}

#Çîíà 51
{246}{}{Area 51? Nein, davon weiß ich nichts. Aber ich kann dir sagen, wer solche Informationen hat ... wenn wir uns einigen können.}
{247}{}{Und wie können wir uns einigen?}
{248}{}{Deine Niedertracht gefällt mir nicht. Vergiss es.}
{249}{}{Aber nein! Ich halte mich von zwielichtigen Geschäften fern. Ich passe.}
{250}{}{Ich würde im Stadtarchiv im Rathaus nachfragen. Das kannst du nicht selbst erledigen – dir fehlt der Zugang. Aber die Informationen gibt es nicht umsonst, verstehst du?}
{251}{}{Äh, klar. Wie viel willst du für die Informationen?}
{252}{}{Geld? Nein, ich habe keins.}
{253}{}{Für 1000 kann ich dir die Koordinaten sofort besorgen.}
{254}{}{Großartig! Hier ist das Geld. Ich warte hier.}
{255}{}{Dann gehe ich das Geld holen.}
{256}{}{}
{257}{}{Das war einfach. Der Archivar hatte Zeit und fand die Koordinaten in wenigen Minuten. Hier ist das Ergebnis. [du gibst die Koordinaten in deinen Pip-Boy ein]}
{258}{}{Danke. Genau das habe ich gebraucht.}

{259}{}{Für deine Hilfe in der Sache Sam Phillips bin ich mehr als bereit, dir zu helfen. Area 51? Kein Problem. Aber du musst dich noch etwas gedulden.}
{260}{}{Klar.}
{261}{}{Wenn du unser Problem mit Phillips löst, bekommst du die gewünschten Koordinaten.}
{262}{}{Verdammt. Können wir uns nicht irgendwie anders einigen? Schade.}

#Íàðêîäåëà â ãîðîäå
{263}{}{Das ist ziemlich übel. In der Stadt läuft ein Drogenlabor, aber wir können es nicht ausfindig machen. Eine zwielichtige Sache. Wenn du etwas herausfindest, sag es uns, dann greifen wir sofort ein.}
{264}{}{Kein Problem! Das Drogenlabor ist erledigt.}
{265}{}{Das sind gute Neuigkeiten! Gute Arbeit, Mr. Davis!}
{266}{}{Das tut mir leid, Mr. Davis. Ich hoffe, du findest die Lösung.}

{267}{}{Ich möchte bei den Ermittlungen helfen. Ich habe zufällig von der Existenz von Black Caravan erfahren ...}
{268}{}{Ich kann Ihnen helfen. Zufällig habe ich ein Drogenlabor entdeckt ...}
{269}{}{Ausgezeichnete Arbeit, Bürger! Gut, dass Sie es mir gesagt haben. Black Caravan wird sofort verhaftet, unser Einsatztrupp ist schon unterwegs. Die Bastarde werden uns bestimmt den Standort des Labors verraten. Nun, Sie haben sich eine Belohnung verdient. Ich glaube, ich lege wegen des Risikos sogar noch etwas aus eigener Tasche drauf. Hier, 2000$.}
{270}{}{Gute Bezahlung!}
{271}{}{Großartige Neuigkeiten, Bürger! Wir schicken sofort alle los, die auf den Beinen stehen können. Aber jemanden wie Sie können wir nicht einfach gehen lassen ... Nicht ohne eine Belohnung. Keine Sorge, das ist für Sie.}
{272}{}{Wow, danke für die Bezahlung!}

#Female character
{1111}{}{Ich habe nichts getan. Ich gehe.}
{1124}{}{Freu dich nicht zu früh, Mr. Überheblichkeit. Mal sehen, wie viel Scheiße aus dir herauskommt, wenn du am Pranger stehst.}
{1153}{}{Vielleicht bin ich noch nicht bereit. Noch eine Frage.}
{1154}{}{Vielleicht bin ich noch nicht bereit, die Verantwortung zu übernehmen. Mach's gut.}
{1169}{}{Entschuldigen Sie, Mr. Davis. Ich habe nicht gleich verstanden, worum es geht. Hier ist die Holodisk.}
{1184}{}{Ich bin gekommen, um ihre Unschuld zu beweisen. Ich habe Beweise dafür, dass man ihnen eine Falle gestellt hat.}
{1189}{}{Vielleicht ist das alles, was ich über sie wissen wollte.}
{1229}{}{Du kommst nicht von hier? Dann könnten wir ein Geschäft machen.}
{1231}{}{Weißt du, ich habe es mir anders überlegt. Bis dann.}
{1238}{}{Du willst, dass ich den Standort seines Labors ausfindig mache?}
{1245}{}{Na dann, ich mache mich an die Arbeit.}
{1267}{}{Ich will bei den Ermittlungen helfen. Ich habe zufällig von der Existenz des Black Caravan erfahren...}
{1268}{}{Ich kann dir helfen. Zufällig habe ich ein Drogenlabor gefunden.}
