{100}{}{Du siehst Sam Phillips.}
{101}{}{Du siehst Sam Phillips, den Besitzer des Cafés „Hard Rock“.}

{110}{}{[Seufzt] Worum geht es, junger Mann?}
{111}{}{Ich bin zufällig hier gelandet und bin ganz bestimmt nicht auf einen Plausch aus. Ich bin dann mal weg.}
{112}{}{Entschuldigen Sie die Störung.}

####################################################################
#              Á. Ëóè êàê äæàçìåí
####################################################################

{113}{}{Ich sehe, du hast eine leere Bühne. Warum?}
{114}{}{Es ist ziemlich schwer, einen guten Künstler zu finden. Weißt du, im Moment ist nicht die Zeit für Unterhaltung.}
{115}{}{Ich kenne einen großartigen Jazzmusiker aus Reno...}
{116}{}{Hast du schon versucht, ein Casting zu veranstalten?}
{117}{}{Wie viele Leute hast du im Laufe der Jahre vorspielen lassen?}
{118}{}{Ja, ich verstehe. Na dann, viel Glück.}
{119}{}{Ja, kein Künstler bleibt in deinem Drecksloch! Ich eingeschlossen.}

{120}{}{Wir haben es vor ein paar Jahren versucht. Damals haben wir ein paar gute Leute gefunden, aber der Ruhm hat sie alle kaputtgemacht... Wenn du verstehst, was ich meine.}
{121}{}{Drei Leute pro Jahr. Mehr bekommen wir nicht. Sie spielen hauptsächlich Gangsterlieder und Blues, das ist für die Künstler am einfachsten und zugänglichsten.}

{122}{}{Ein Jazzmusiker? Meinst du das ernst?! Hm... Weißt du, ich mache mir ein wenig Sorgen, dass er aus Reno kommt. Wie gut ist er?}
{123}{}{Ehrlich gesagt, ich habe seine Tour irgendwie verpasst.}
{124}{}{Ich bin sicher, er ist genau der Richtige für dich!}
{125}{}{Was macht das schon? Lass ihn einfach vorspielen und entscheide selbst.}
{126}{}{Eigentlich weiß ich es nicht, tut mir leid, dass ich dich belästige.}

{127}{}{Ach ja? Hör zu, ich will meine Zeit nicht mit Leuten verschwenden, die mir und meinem Laden nichts nützen. Leb wohl.}
{128}{}{Verdammt. Na ja, vielleicht kannst du es dir ja noch anders überlegen...}
{129}{}{Hmm ... Wir können es versuchen ... Allein aus Respekt vor dir.}
{130}{}{Großartig!}
{131}{}{Das ist mir wichtig – ich kann mich nur auf vertrauenswürdige Leute verlassen. Alle Mitarbeiter in diesem Café werden nur auf Empfehlung eingestellt. Ich will keine Idioten auf der Bühne und den Ärger, den sie mit sich bringen. Mach's gut.}

{132}{}{Na gut, wir können uns deinen Freund anhören ... Schließlich bist *du* es, der ihn empfiehlt.}
{133}{}{Wie süß. Aber weißt du, ich kann mich nur auf vertrauenswürdige Leute verlassen. Alle Mitarbeiter in diesem Café werden nur auf Empfehlung eingestellt. Ich will keine Idioten auf der Bühne und den Ärger, den sie mit sich bringen. Also alles Gute für dich und deinen Bekannten.}

{134}{}{Na gut. Bring ihn ins Café, dann sehen wir ihn uns an. Ich vertraue dir, enttäusch mich nicht.}
{135}{}{Klar! Ich gehe ihm die gute Nachricht überbringen.}

{136}{}{Der Cafébesitzer ist bereit, Big Louie vorzuspielen. Jetzt muss ich nur noch dem Musiker Bescheid sagen.}

####################################################################
#              Êâåñò íà ïîèñê îïğàâäàíèÿ
####################################################################

{150}{}{Du siehst bedrückt aus. Was ist passiert?}
{151}{}{[Winkt ab] Tut mir leid, mir passieren gerade viele schlimme Dinge, aber das geht dich nichts an. Ich kann mich einfach nicht auf meine Arbeit konzentrieren ... Was willst du?}
{152}{}{Gehen wir zurück.}
{153}{}{Eigentlich nichts.}
{154}{}{Und trotzdem – vielleicht brauchst du Hilfe?}

{155}{}{Weißt du, ganz sicher nicht von dir. Meine Lage ist zu ungewiss und gefährlich. Ich fürchte, du machst alles nur noch schlimmer.}
{156}{}{Na, wie du meinst.}
{157}{}{In meiner Lage habe ich keine Wahl. Meine Freunde haben Angst, sich einzumischen, und du bist neu hier. Vielleicht kannst du herausfinden, wer es war ... wenn du mir natürlich glaubst. Und wenn nicht – dann schlag dich eben auf die Seite meiner Feinde. Platz ist dort genug.}
{158}{}{Ich sehe, dass du ein guter Mensch bist, ohne Dreck am Stecken. Deshalb helfe ich dir trotzdem.}
{159}{}{Dann lasse ich es lieber.}

{160}{}{[Seufzt] Danke, aber ich war nicht immer so ein guter Mensch. Ich habe eine lange Drogengeschichte hinter mir. Und die Vergangenheit hat sich wie ein Albtraum wieder gezeigt.}
{161}{}{Was ist passiert?}
{162}{}{Mir wurde etwas angehängt. Jemand hat der Polizei erzählt, ich würde Gift kaufen, an dem meine Kunden sterben. Die Bullen haben das Café auf den Kopf gestellt, alle möglichen Zusätze gefunden und sind gegangen – angeblich, um sie zu untersuchen. Aber wer soll das schon wirklich tun? Diese Idioten können Natrium nicht von Marihuana unterscheiden! Sie begreifen nicht, dass es einfach nur Salz ist.}
{163}{}{Warum sind sie sich so sicher?}
{164}{}{Ich weiß es nicht. Sie haben falsche Beweise, und offenbar kümmert es niemanden, der Sache auf den Grund zu gehen. Seit Tagen lebe ich in Angst vor dem Gefängnis oder der Todesstrafe.}
{165}{}{Und du hast wirklich eine Ladung Dope gekauft?}
{166}{}{Nein! Ich arbeite nur mit ein paar Karawanen zusammen, die meisten davon arbeiten für „Monte“. Aber grundsätzlich bringt Bob alle benötigten Waren.}
{167}{}{Wo finde ich ihn?}
{168}{}{Bob? Er hält sich immer auf dem Karawanenparkplatz auf.}
{169}{}{Wer könnte dir das angehängt haben?}
{170}{}{Ich weiß es nicht. Ich denke, irgendein Konkurrent. Schließlich gibt es nicht viele Leute, denen es gelungen ist, die alten Lokale wiederaufzubauen und der Stadt damit Einnahmen zu verschaffen. Mehr kann ich dazu nicht sagen.}
{171}{}{Das alles ist ziemlich vage. Na gut, mal sehen, was wir tun können.}

{172}{}{Was dein Problem mit der Polizei angeht – das ist erledigt. Na ja, zumindest wurde deine Unschuld bewiesen. Wer dahintersteckt, ist mir allerdings noch ein Rätsel.}
{173}{}{So einfach war es nicht, oder? Ich weiß übrigens schon Bescheid. Die Polizei hat mich kontaktiert und mir alles erzählt, samt Entschuldigung. Du hast mich gerettet! Ich hatte jede Hoffnung verloren und war bereit, ins Gefängnis zu gehen. Weißt du, ich finde, du hast dir das verdient. Hier, nimm das. [gibt 1000 Dollar]}
{174}{}{Oh! Das hat sich gelohnt!}
{175}{}{Was deine Feinde angeht: Es stellt sich heraus, dass die „Beweise“ von einem der Konkurrenten platziert wurden – dem Besitzer des „Monte“-Casinos.}
{176}{}{Mein Gott! Ich hätte nicht gedacht, dass Hal so gierig ist ... Na ja, es wird mich nicht grämen, wenn er bekommt, was er verdient. Ich habe mich nicht in seine Geschäfte eingemischt und werde das auch in Zukunft nicht tun, schon gar nicht aus Rache. Danke für die Information.}
{177}{}{Gern geschehen.}

{178}{}{Was kannst du mir über diese Substanz erzählen? Der Karawanenführer hat zugegeben, dass er dir diesen Dreck für die Party liefert ...}
{179}{}{Oh, du auch ... Die Polizei hat es auch nicht verstanden. Das ist für Pizza. In unserer Zeit ist es nicht so einfach, eine Handvoll Getreide für normalen Teig aufzutreiben, also machen wir ihn aus allen möglichen Dingen - zum Beispiel aus Pappe. Der Teig war dann so zäh, dass wir Emulgator E30 hinzufügen mussten. Dieser Stoff wird aus den Tiefen des Salt Lake gewonnen und verfeinert irgendwie den Geschmack ... Ungefährlich, aber du solltest ihn besser nicht pur probieren, sonst bist du die ganze Nacht auf dem Klo.}
{180}{}{Hmm ...}

####################################################################
#              Ïğî êîëó - ïîëó÷åíèå êâåñòà
####################################################################

{200}{}{Ich bin der offizielle Kurier der Nuka-Cola-Fabrik in Salt Lake. Hättest du Interesse, bei uns einzukaufen?}

{201}{}{Das würde ich gern, aber ich kann nicht. Wir haben große Probleme im Café. Es kann sein, dass wir dieses Geschäft abschließen und bald niemand mehr da ist, der sich darum kümmern kann. Gehen wir jetzt lieber kein Risiko ein.}
{202}{}{Darf ich fragen, worin das Problem besteht?}
{203}{}{Wow, tut mir leid. Klar, das musst du nicht.}

{204}{}{Hmm ... Vielleicht. Meine Probleme sind gelöst, also können wir das Risiko eingehen. Aber kann ich deine Papiere sehen?}
{205}{}{Klar. Hier ist die Lizenz.}
{206}{}{Ich habe sie gerade nicht dabei. Ich bringe sie später vorbei.}

{207}{}{Äh ... Nein. Frag nicht, warum. Ich habe meine Gründe ... Einige sogar. Aber frag trotzdem nicht!}
{208}{}{Ich hoffe, du überlegst es dir noch anders.}

{209}{}{Ich kann kein Risiko eingehen, besonders nach all den Problemen, die ich durchgemacht habe. Es liegt nicht an dir, bitte versteh das. Ich lebe einfach in unsicheren Zeiten. Ich muss mir bei deiner Ware völlig sicher sein. Bring also deine Lizenz mit, dann können wir ein Geschäft machen.}
{210}{}{Na gut.}

{211}{}{[Studiert die Papiere sorgfältig] Sehr gut. [nickt] Sehr gut. Genau das habe ich gebraucht - Vertrauen in meinen Geschäftspartner. Wir werden mit dir zusammenarbeiten.}
{212}{}{Großartig!}
{213}{}{Machen wir es so - ich bestelle ein Verkaufsautomaten-Set für den Verkauf des Getränks. Das wird unser Geschäft vereinfachen. Du kannst den Vorgang über die Software im Automaten überwachen. Aber denk daran - wir kümmern uns nicht um dein Produkt, bevor es bei uns auf Lager ist. Um Probleme mit den Lieferungen kümmerst du dich selbst.}
{214}{}{Ich kümmere mich darum ... Freust du dich auf unsere Zusammenarbeit?}
{215}{}{Ausgezeichnet. Dann kommen wir gleich zum Vertragsabschluss.}

{216}{}{Sehr! Endlich können wir diese Angeber in Clean City übertrumpfen.}
{217}{}{Wer?}
{218}{}{Falls es dir noch nicht aufgefallen ist: Das Casino „Monte“ hat einen Vertrag mit derselben Fabrik abgeschlossen, mit der du zusammenarbeitest. Sie ist unsere – und deine – Konkurrenz. Komisch, oder?}
{219}{}{Komisch, dass ich mit meiner eigenen Konkurrenz zusammenarbeite? Hm ...}
{220}{}{Solange das Casino läuft, müsst ihr euch den Markt in Vegas mit ihnen teilen ... Wo war ich? Ach ja! Ich schlage vor, du unterschreibst den Vertrag, Partner!}
{221}{}{Klar, Partner!}

{229}{}{Ein tolles Geschäft. Wir werden gut zusammenarbeiten. Komm morgen wieder, ich denke, bis dahin können wir einen Verkaufsautomaten aufstellen. Aber kümmere dich zuerst darum, dass genug Ware auf Lager ist. Schönen Tag noch.}
{230}{}{Klar! Schönen Tag, Mr. Phillips!}

#Female character
{1110}{}{[Seufzt] Worum geht's, Ma'am?}
#{1120}{}{His name is... Er... I don't know myself, but he's a talent, trust me.} #wrong replic
{1123}{}{Ehrlich gesagt, ich habe seine Tour irgendwie verpasst.}
{1124}{}{Ich bin sicher, er ist genau der Richtige für dich!}
