{100}{}{Sieh mal Hal Wallace.}
{101}{}{Hier steht niemand Geringeres als der Besitzer des „Three Card Monte“ höchstpersönlich.}
{102}{}{Ein Killer ist im Büro!!!}

#Ñ'àğ'îâàÿ âå'êà:
{107}{}{Das gibt's doch nicht ...}
{108}{}{Wachen! Schafft diesen Abschaum aus dem Büro!}
{109}{}{Wer?! Ich? Das ist ein Irrtum! Ich wollte gerade gehen.}
{110}{}{Die Wache sagte, Sie wollen mich sprechen?}
{111}{}{Ja. Ich möchte für Sie arbeiten!}
{112}{}{Oh, Entschuldigung, falsche Tür.}
{113}{}{Was machen die Wachen da?! Bringt ihn sofort auf den Flur!}
{114}{}{Nein! Wartet ...}

#Êâåñ' íà âûğîäêîâ:
{115}{}{Ja, es gibt da eine Aufgabe ... Nichts für schwache Nerven.}
{116}{}{Worum geht's?}
{117}{}{Ach, ich war nur neugierig. Ich glaube, ich gehe lieber.}

{118}{}{Du weißt doch, wer die Freaks sind, oder? Diese Ghule sind eine verdammte Plage. Die ganze Stadt leidet ihretwegen, und es ist nicht abzusehen, wie lange das noch so weitergeht. Wir müssen etwas dagegen unternehmen.}
{119}{}{Hm. Irgendwas sagt mir, dass deine Ziele nicht ganz edel sind.}
{120}{}{Wofür sind sie denn schuldig?}
{121}{}{Klar. Wenn du zahlst, dann müssen wir wohl.}
{122}{}{Keine Ghule! Mit denen lege ich mich nicht an!}

{123}{}{Ich habe, wie der Rest der Stadt, meine Gründe. Aber warum interessiert dich das? Konzentrier dich lieber auf deinen eigenen Vorteil.}
{124}{}{[Unauffällig die Aufnahme auf einem Pip-Boy starten] Also, worum geht's?}
{125}{}{Also, worum geht's?}
{126}{}{Wenn du nicht ehrlich zu mir sein willst, lehne ich ab!}

{127}{}{Mit der Herstellung und dem Vertrieb von Drogen. Ihre Überlebensmethoden sind einfach monströs. Wegen ihrer Drogen gehen Menschen zugrunde oder sterben. Auch meine Klienten. Als rechtschaffener Bürger möchte ich die Stadt deshalb von diesem ... Abschaum befreien.}
{128}{}{Ich zahle 2.500 für diese einfache Aufgabe. Für die meisten Bürger eine Menge Geld. Aber das Risiko ist ebenso groß. Du musst unauffällig vorgehen.}
{129}{}{Ganz einfach. Ich gebe dir die Droge, sie ist sehr stark. Frag nicht, woher sie stammt. Und probier sie nicht. Es ist eine tödliche Mischung.}
{130}{}{Na gut, ich werde vorerst keine Fragen stellen. Was kommt als Nächstes?}
{131}{}{Der nächste Schritt ist ziemlich einfach: Dring unauffällig und heimlich in das Hotel der Freaks ein und leg die Droge in die Kisten. Sobald du das erledigt hast, geh zur Polizeiwache und gib dem Polizeichef anonym einen Hinweis auf die Beweise. Er wird wissen, was zu tun ist.}
{132}{}{Verstanden. Ist es riskant? Haben diese Freaks Wachen?}
{133}{}{Wie schleiche ich mich ins Gebäude?}
{134}{}{Ich passe! Das ist zu gefährlich!}

{135}{}{Na, da habe ich mich wohl in dir getäuscht. [Er nickt den Wachen zu]}
{136}{}{Alle stehen bleiben! Ich werde mich verteidigen!!!}
{137}{}{Freaks lassen sich normalerweise nicht auf Kämpfe ein. Sie sitzen schon so lange auf der Nadel, dass sie kaum noch bei Kräften sind. Ich glaube nicht, dass du auf ernsthaften Widerstand stoßen wirst. Vor allem, weil sie dich wahrscheinlich nicht erwarten.}
{138}{}{Das liegt nicht an mir. Die Bewohner von Clean City gehen selten über die Mauern hinaus. Find es selbst heraus. Das ist dein Job.}
{139}{}{Na gut, klingt einfach. Gib mir die falschen Beweise und mach das Geld bereit. Ich bin bald zurück.}
{140}{}{Ausgezeichnet. Ich bin ein Mann von Wort. Aber wenn du Mist baust ...}
{141}{}{Verstanden, Mr. Wallace. Ein Auftrag ist ein Auftrag. Ich erledige das ohne Umschweife.}
{142}{}{Verdammt, nein! So einen zwielichtigen Auftrag nehme ich nicht an!!!}

{143}{}{Ich warte auf Neuigkeiten, Partner.}
{144}{}{In Ordnung, Mr. Wallace.}

#Ñäà÷à êâåñ'à íà âûğîäêîâ:
{145}{}{Ich warte auf die *guten* Neuigkeiten!}
{146}{}{Alles ist bereit. Die Drogen sind in den Kisten versteckt. Jetzt muss ich nur noch die Polizei informieren.}
{147}{}{Erledigt. Wie vereinbart wurden Drogen versteckt und die Freaks der Polizei ausgeliefert.}
{148}{}{Das Problem mit den Freaks wurde ohne Drogen gelöst. Larry Geller, ihr Anführer, ist tot.}
{149}{}{Ich konnte andere Beweise finden und die Freaks der Polizei ausliefern, ohne etwas vorzutäuschen.}
{150}{}{Tut mir leid, noch nichts.}

{151}{}{Ja, genau das haben wir gebraucht. Ich übernehme ab hier. Und was dich angeht: gute Arbeit. Ich nehme an, ich muss nicht extra betonen, wie wichtig Verschwiegenheit ist?}
{152}{}{Natürlich, Mr. Wallace. Von mir wird niemand etwas über diesen Vorfall erfahren.}
{153}{}{Das klingt wie eine Drohung! Zeit, zuerst zuzuschlagen!}
{154}{}{Ja, genau das brauchen wir. Du hast hervorragende Arbeit geleistet. Ich nehme an, ich muss nicht extra betonen, wie wichtig Verschwiegenheit ist?}
{155}{}{Aber ich hatte eine andere Lösung verlangt ... Na ja, die hier reicht auch. Ohne Anführer sollten sie keine Bedrohung mehr sein ... In Ordnung, meinetwegen. Ich nehme an, ich muss nicht extra betonen, wie wichtig Verschwiegenheit ist?}
{156}{}{Nun, meinetwegen. So oder so hast du deine Arbeit erledigt. Ich nehme an, ich muss nicht extra betonen, wie wichtig Verschwiegenheit ist?}
{157}{}{Die Belohnung beträgt wie vereinbart 2500.}
{158}{}{Der Betrag ist gut!}

#Ïîëó÷åíèå êâåñ'à íà íà÷àëüíèêà ÃİÑ:
{159}{}{Ich habe weitere Arbeit für dich.}
{160}{}{Ich höre, Mr. Wallace.}
{161}{}{Verdammt, nein! Hier laufen irgendwelche zwielichtigen Dinge! Es ist Zeit, dem ein Ende zu setzen!}

{162}{}{Ich wollte herausfinden, ob es einen „besonderen“ Auftrag für mich gibt.}
{163}{}{Da ist ein Mann, der mich schwer beleidigt hat. Ich kann es ihm nicht offen heimzahlen. Ich brauche belastendes Material über ihn.}
{164}{}{Ausgezeichnet. Wer ist diese Person?}
{165}{}{Auf keinen Fall! So etwas mache ich nicht!}
{166}{}{Er heißt Bob Neil. Er ist für den örtlichen Damm verantwortlich. Ein gerissener Kerl. Sei vorsichtig mit ihm.}
{167}{}{Okay. Was für belastendes Material brauchst du?}
{168}{}{Ich brauche seine persönliche Waffe. Aber Bob Neil selbst muss am Leben bleiben!}
{169}{}{Das wird nicht leicht. Warum bringen wir ihn nicht einfach um? Warum diese Komplikationen?}
{170}{}{Okay. Ich erledige alles.}
{171}{}{Zu viele Fragen schaden immer denen, die sie stellen.}
{172}{}{Okay. Ich erledige den Auftrag. Wie hoch ist der Preis für das Risiko?}
{173}{}{Der gleiche – 5000 Mäuse.}
{174}{}{Ich erledige das.}
{175}{}{Zu wenig. Es ist zu gefährlich und kompliziert. 7000, keinen Cent weniger.}
{176}{}{Du hast mich überzeugt. Erhöhen wir die Belohnung auf 7000. Ich feilsche nicht gern, aber wenn die Angelegenheit erledigt wird, bin ich bereit zu zahlen.}
{177}{}{Ausgezeichnet! Bereite das Geld vor.}
{178}{}{Gier hat schon viele Menschen an den Galgen gebracht. Ich rate dir, darüber nachzudenken.}
{179}{}{Verstanden. Es tut mir leid, Mr. Wallace. Ich erledige den Auftrag zu *deinem* Preis.}
{180}{}{Du drohst mir also!!! Die Erde wartet auf *dich*, Dreckskerl!}
{181}{}{Ich verzeihe keine Fehler. Ich brauche Bobs Waffe, und zwar unauffällig.}
{182}{}{Verstanden. Ich tue, was ich kann.}

#Ñäà÷à êâåñ'à íà íà÷àëüíèêà ÃİÑ:
{183}{}{Du weißt, was zu tun ist. Warum bist du hier?}
{184}{}{Auftrag erledigt. Hier ist die Waffe. Bob Neil lebt noch und weiß nichts von unserer Abmachung.}
{185}{}{Nichts. Ich verschwende nur meine Zeit.}
{186}{}{Ich bin gekommen, um dir zu sagen, dass ich mit dieser blöden Arbeit Schluss mache!}
{187}{}{Ich bin gekommen, um dir zu sagen, dass mir ein Gegenangebot gemacht wurde. Und ich habe es angenommen.}

{188}{}{Und du hattest die Frechheit, zurückzukommen?! Wachen!}
{189}{}{Aber Bob Neil ist gerächt!...}

{190}{}{Ich wusste, dass ich mich auf dich verlassen kann. Ausgezeichnete Arbeit. Hier ist deine Belohnung, wie vereinbart. Nun, es war nett, mit dir zusammenzuarbeiten. Aber jetzt trennen sich unsere Wege. Halte dich von der Polizei und dem Büro des Bürgermeisters fern, wenn du keinen Ärger willst.}
{191}{}{Wozu brauchtest du also die Waffe? Es wäre einfacher, den Polizeichef zu töten ...}
{192}{}{Wie du willst.}
{193}{}{Belastendes Material soll *gegen* Bob Neil verwendet werden. Das sagt doch alles. Wie – geht dich nichts an.}

{194}{}{Ich mag keine Herumtreiber auf dem Flur. Ich rate dir, dich um deine eigenen Angelegenheiten zu kümmern.}
{195}{}{[Schalte unauffällig die Aufnahmefunktion deines Pip-Boy ein] Ausgezeichnet. Wer ist diese Person?}

{196}{}{Ich werde jeden deiner Befehle ausführen! Bist du sicher, dass es keine weitere Arbeit für mich gibt?!}
{197}{}{Tut mir leid, nein.}
{198}{}{Wie schade.}
{199}{}{Warum wendest du dich nicht direkt an die Polizei?}
{200}{}{In Amerika ist es, wenn etwas nicht in Ordnung ist, meistens am besten, es so schnell wie möglich in Ordnung zu bringen.}

#Æåíñêèå ğåïëèêè
{1112}{}{Oh, Entschuldigung, falsche Tür.}
{1113}{}{Was treiben die Wachen da?! Bringt sie sofort auf den Flur!}
{1117}{}{Ach, ich war nur neugierig. Ich glaube, ich gehe lieber.}
{1141}{}{Verstanden, Mr. Wallace. Ein Auftrag ist ein Auftrag. Ich erledige das ohne Umschweife.}
{1176}{}{Du hast mich überzeugt. Erhöhen wir die Belohnung auf 7000. Ich feilsche nicht gern um den Preis, aber wenn sich die Angelegenheit damit erledigen lässt, bin ich bereit zu zahlen.}
{1179}{}{Verstanden. Es tut mir leid, Mr. Wallace. Ich erledige den Auftrag für *deinen* Preis.}
{1182}{}{Verstanden. Ich tue, was ich kann.}
{1186}{}{Ich bin gekommen, um dir zu sagen, dass ich mit dieser blöden Arbeit Schluss mache!}
{1187}{}{Ich bin gekommen, um dir zu sagen, dass mir ein Gegenangebot gemacht wurde. Und ich habe es angenommen.}
