{100}{}{Das ist Larry Geller.}
{101}{}{Das ist Larry Geller, der Anführer der Freaks von New Vegas, ihr moralischer und spiritueller Rückhalt.}

{108}{}{Aber deinem Gesichtsausdruck nach zu urteilen, hast auch du ein hartes Leben hinter dir.}
{109}{}{Da kommt unser glatthäutiger Freund ... Für uns bist du natürlich immer noch glatthäutig. Aber es ist ein Rätsel, wie du mit so einem Gesicht in Clean City nicht erschossen wirst.}

#Âîïğîñû è ïåğâûå ğåïëèêè
{110}{}{Du solltest hier besser nicht herumstreunen. Unser Hotel ist kaum besser als der örtliche Friedhof. Ha-ha! Nur ein Scherz. Der Friedhof ist natürlich viel besser ...}
{111}{}{Warum tragt ihr alle Säcke auf dem Kopf? Ist das irgendein Modetrend?}
{112}{}{Habt ihr Kontakt zu euren Nachbarn vom „Hard Rock“-Café?}
{113}{}{Weißt du etwas über die Substanz namens „Emulgator E30“?}
{114}{}{Ich suche einen Führer für die Zugreise. Kann einer von euch den Job übernehmen?}
{115}{}{Hoppla.}

#Îòâåòû íà ğÿäîâûå âîïğîñû
{116}{}{Selbst wenn sich jemand dafür melden würde, würde er die Reise nicht überleben. Gesundheitsprobleme, du weißt schon. Na ja, es sei denn, er trinkt etwas von deinem Blut ... Ha-ha! Keine Sorge, war nur ein Scherz. Wir essen nur Gehirne.}
{117}{}{Sehr lustig. Noch eine Frage.}
{118}{}{Ich glaube, ich gehe dann.}
{119}{}{Emulgator, ja ... Das ist ein gängiger Bestandteil einer Atombombe. Nur Spaß. Eigentlich ist es ein Nahrungsergänzungsmittel. Eine Art spezielles, säureangereichertes Salz. Es wird in Salt Lake abgebaut, in einem See hier in der Gegend. Sam Phillips verwendet den Emulgator, damit sein Pizzateig weicher und zarter wird. Früher war seine Pizza wie Gummi und ließ sich nicht mit dem Messer schneiden.}
{120}{}{Nein. Aber Sam und ich standen uns früher sehr nahe. Er hat mir immer mit einer Brechstange den Rücken massiert. Ha-ha-ha! Nur Spaß. Aber er ist ein unvoreingenommener Mensch und hat uns immer so akzeptiert, wie wir sind.}
{121}{}{Was kannst du über seine Drogensucht sagen? Hast du ihn jemals beim Konsum gesehen?}
{122}{}{In der Stadt gab es viele Drogenprobleme. Eine Zeit lang verkehrte auch Phillips mit den falschen Leuten. Aber das ist alles Vergangenheit. Ich bin sicher, er ist jetzt clean und hat seine Fehler eingesehen.}

#Ğàññïğîñ ïğî òî, êòî îíè òàêèå
{123}{}{Warte, du hast noch nie von uns gehört? Man hat dich nicht einmal gewarnt, dass man uns besser meidet? Sieht aus, als wärst du neu in der Stadt!}
{124}{}{Bin ich tatsächlich.}

{125}{}{Dann merk dir eins: Alle hier nennen uns „Freaks“. Wir tragen Säcke über dem Kopf, damit du nicht siehst, wie wir mit unseren verrotteten Zähnen Menschenfleisch kauen. Ha-ha-ha!!}
{126}{}{Menschenfleisch, was? Du bist ein lustiger Kerl. Was ist denn mit euren Gesichtern los?}

{127}{}{Mit unseren Gesichtern? Oh, Wanderer, das kann ich dir nicht sagen, sonst kotzt du gleich überall hin. Ha-ha!}
{128}{}{Hör auf, mir Angst machen zu wollen, Herr wandelnder Toter. Ich habe schon Schlimmeres gesehen.}
{129}{}{Was?! Willst du dich über mich lustig machen? Du brauchst noch einen Sack – um deine Überreste darin zu begraben, du Freak!}
{130}{}{Deine Witze gefallen mir nicht. Ich gehe besser.}

{131}{}{Oh! Ich sehe schon, du bist ein harter Bursche. Du kannst mich Larry nennen. Larry Geller, das ist mein voller Name.}
{132}{male}{Hey, Larry. Was ist mit dem Zeug in deiner Hose? Löst das auch Erbrechen aus?}
{133}{male}{Na und? Ich kann dir dein „Zeug“ abschneiden und mir selbst einpflanzen! Dann wäre ich fünfzig Jahre jünger. Ha-ha-ha!}
{134}{male}{Von wegen! Ich wette, du wirst deins zuerst essen!}
{135}{}{Du musst sofort beseitigt werden, bevor noch jemand zu Schaden kommt. Deine letzten Worte, Freak!}
{136}{}{Das ist ziemlich kranker Humor. Ich geh besser an die frische Luft.}
{137}{female}{Schade, dass dir mein Aussehen nicht gefällt. Aber wenn du auf Grobes stehst, bist du hier genau richtig, Baby!}
{138}{female}{Halt deine Leichen zurück, Kumpel! Ich hätte nie gedacht, dass mich ein Toter anmacht.}

{139}{}{Oh, das solltest du lieber nicht sagen. Ich könnte das wörtlich nehmen ... Ha-ha-ha!!!}
{140}{}{Also, was fehlt dir?}
{141}{}{Du bist ziemlich untauglich. Ich sollte dich beseitigen!}
{142}{}{Dann halte ich besser den Mund und verschwinde.}
{143}{}{Also, was hast du denn?}
{144}{}{Wie du willst, Larry. Ich muss jetzt los.}

#Ïîëó÷åíèå êâåñòà íà ïîèñê îïğàâäàíèé
{145}{}{Eigentlich leiden wir schon seit Langem an nichts mehr ... außer an einer kleinen Geistesstörung.}
{146}{}{Und was ist dann mit eurer Haut?}
{147}{}{Strahlung, Freund, Strahlung. Und offenbar noch irgendein anderer Mist, der durch die Luft fliegt. Der Körper ist verknöchert, die Haut wurde starr und die Venen haben ihre Elastizität verloren.}
{148}{}{Ja, verstehe. Und was jetzt? Versteckt ihr eure Gesichter, damit ihr keine Kinder erschreckt oder so?}
{149}{}{In Clean City erschrecken sie die Kinder sowieso mit uns. So nach dem Motto: Benimm dich, sonst kommt ein böser Freak und bringt dich zum Dead Hotel oder so. Sie halten uns für ansteckend, deshalb machen alle einen Bogen um uns ... meistens.}
{150}{}{Meistens?}
{151}{}{Offenbar hat jemand übertrieben, und jetzt beschuldigt man uns, Drogen herzustellen. Die Polizei scheint sogar Beweise zu haben. Ich weiß nicht, ob das stimmt, aber ich glaube nicht, dass die Polizei nach Beweisen suchen würde. Die kommen einfach her und erschießen uns. Hoffentlich werden unsere Seelen sie danach nachts heimsuchen, he-he.}
{152}{}{Aber ihr stellt doch keine Drogen her, oder?}
{153}{}{Die Polizei hat recht! Du musst an einen neuen Ort gebracht werden, wo du bleiben kannst – unter drei Meter Erde!}
{154}{}{Nun, das ist nicht meine Angelegenheit. Vielleicht sollte ich gehen.}
{155}{}{Nur pflanzliche Arzneimittel, um unser vergängliches Fleisch zu stützen und uns das Urinieren zu ermöglichen. Wir müssen Pulver herstellen, die das Venensystem erweitern. Leider hält die Polizei das für eine Droge.}
{156}{}{Bist du also in Lebensgefahr?}
{157}{}{Ich stimme ihnen zu! Und jetzt werde ich den Willen der Justitia erfuellen!}
{158}{}{Ich weiß nicht, wem ich glauben soll. Vielleicht gehe ich besser einfach meinen Geschäften nach.}
{159}{}{Wenn wir unsere Unschuld nicht beweisen, kommt die Polizei und jagt uns im besten Fall von hier fort. Im schlimmsten Fall nimmt sie uns unsere Medikamente weg und beraubt uns damit der Möglichkeit, ordentlich zu pissen ... Ha-ha! Allerdings diskutieren wir immer öfter darüber, ob sie sich überhaupt hertrauen. Irgendetwas sagt uns, dass sie es nicht tun werden.}
{160}{}{Kannst du deine Unschuld beweisen?}

{161}{}{Nein. Wir werden unsere Unschuld niemals beweisen. Zumal wir bald wegen deines Todes durch langsames Zerstückeln gehängt werden ... Ha-ha! Wir werden nicht einmal Beweise zum Clean City bringen können – sobald wir uns dem Haupttor nähern, werden wir auf der Stelle erschossen.}
{162}{}{Weißt du, was ich denke? Dass du Gerechtigkeit verdienst. Ich werde versuchen, dir zu helfen ... wenn du ehrlich bist.}
{163}{}{Du musst da nicht hingehen! Ich erschieße euch alle gleich hier!}
{164}{}{Hör zu, das ist dein Problem. Ich will damit nichts zu tun haben. Deshalb gehe ich.}

#Çàâåğøåíèå êâåñòà íà ïîèñê îïğàâäàíèé
{165}{}{Wie edel! So edel, dass ich es nicht einmal glaube. Und das, nachdem ich dir eine giftige saprophytische Zecke in die Tasche gesteckt habe ... Durchsuch nicht deine Hose. War nur ein Scherz.}
{166}{}{Ich bin ehrlich zu dir. Sei auch du ehrlich zu mir.}
{167}{}{[Heimlich das Gespräch auf deinem Pip-Boy aufnehmen] Ich bin ehrlich zu dir. Sei auch du ehrlich zu mir.}
{168}{}{Ich bin ehrlich ... und meine es ernst. So ernst, wie ich nur kann. Ja, wir hatten schwere Zeiten und haben früher Pulver mit viel stärkerer Wirkung hergestellt. Aber das liegt hinter uns. Du musst uns glauben.}
{169}{}{Niemand muss vorerst irgendetwas für dich tun, Witzbold. Na gut, ich vertraue dir. Wer hetzt also die Polizei auf euch und warum? Und welche Beweise haben sie?}
{170}{}{Ich habe nicht die geringste Ahnung! Die Beweise sind eindeutig Indizien. Der Polizeichef kam zu uns und fragte, woher wir die Zutaten bekommen und wie viele Drogen wir pro Monat herstellen ... Natürlich hat er uns nicht geglaubt. Ich glaube, er ist überzeugt, dass er recht hat, und wird daran festhalten, selbst wenn du Beweise für das Gegenteil findest.}
{171}{}{Na ja, das ist nicht viel.}
{172}{}{Ich denke, du solltest zuerst mit der Polizei reden. Ich glaube, sie werden dir zuhören. Überleg dir deine Geschichte gut, damit du keinen unnötigen Verdacht erregst. Noch besser: Töte dort alle und opfere ihre Herzen unserem Gott! Ha-ha-ha ...}
{173}{}{Mal sehen.}

{174}{}{[Heimlich das Gespräch mit deinem Pip-Boy aufnehmen] Aber ihr stellt doch keine Drogen her, oder?}

#Îïğàâäàíèå íàéäåíî
{175}{}{Ich habe eine Quittung von den Sklavenhändlern gefunden. Hier, sieh sie dir an.}
{176}{}{Und was haben wir damit zu tun?}
{177}{}{Das wollte ich dich auch fragen – was hast du damit zu tun und auf wessen Befehl wurde das alles getan?}
{178}{}{Auf wessen Befehl? Na gut, sehen wir mal. [Tut so, als würde er lesen]}
{179}{}{Verdammt! Larry, du hättest mir sagen sollen, dass du nicht lesen kannst. Ich lese es dir vor.}
{180}{}{Danke. Aber lesen kann ich. Ich sehe nur nicht mehr so gut wie früher.}
{181}{}{Hör auf, Ausreden zu machen. Was sagst du zu dieser Quittung?}

{182}{}{Ich sage, dass du hier den direkten Beweis für unsere Unschuld in den Händen hältst. Allerdings glaube ich nicht, dass der Polizeichef vollständig überzeugt sein wird. Es sei denn, du schiebst ihm einen glühenden Schürhaken zwischen die Beine ... Jedenfalls müssen wir jemanden mit glatter Haut finden, der verantwortungsbewusst genug ist, damit zu ihm zu gehen. Uns lassen sie ganz sicher nicht nach Clean City.}
{183}{}{Warte mal. Was ist hier los? Was hat das mit der Polizei zu tun?! Was zum Teufel hast du getan?!}
{184}{}{Wer könnte die Sklavenhändler dazu gebracht haben? Wer ist euer Feind?}

{185}{}{Wir haben keine „Feinde“. Das ist wahrscheinlich nur, äh, Rassendiskriminierung.}
{186}{}{Hmm. Das bezweifle ich stark. Mir scheint, jemand versucht absichtlich, euch von diesem Parkplatz zu vertreiben.}
{187}{}{Na gut. Es ist Zeit, zur Polizei zu gehen.}

{188}{}{Ich glaube nicht, dass wir irgendjemandem etwas Böses wollen, schließlich sitzen wir ruhig da und furzen nicht einmal in unserem Hotel. Generell sollten wir den Polizeichef schnell "zufriedenstellen". Wenn du verstehst, was ich meine.}
{189}{}{Ach ja, die Polizei. Ich bringe die Beweise hin.}
{190}{}{Was?! Warum ich?! Ich habe auch Angst! Hier ist das Papier, mach es selbst.}

{191}{}{Hör zu, wir sind nicht die besten Leute in der Stadt, das weiß ich. Man fürchtet uns. Und wir haben Angst. Aber du nicht. Nicht einmal die Polizei kann es mit dir aufnehmen! Lass uns nicht im Stich! Dafür helfen wir dir auch.}
{192}{}{Na gut, na gut! Ich bringe die Beweise zur Polizei. Hoffentlich erschießen sie mich deswegen nicht.}
{193}{}{Das glaubst du wohl! Ich bin doch nicht mein eigener Feind! Hier, du bringst die Beweise hin, und ich bin weg. Mein Auftrag ist erledigt.}
{194}{}{Wie werdet ihr mir helfen?}

{195}{}{Na ja. Letztendlich sollten wir selbst dafür dankbar sein. Danke. Ich glaube, jemand in "Hard Rock" wird sich bereit erklären, zur Polizei zu gehen.}
{196}{}{Großartig.}
{197}{}{Und was bekomme ich für die ganze Arbeit?}
{198}{}{Wir haben dein Leben verschont – ist das nicht genug? Ha-ha-ha! Hier. Mehr können wir dir nicht geben. [Gibt dir eine Packung Stimpaks]}
{199}{}{Ja, das ist nicht viel.}

{200}{}{Du, Wanderer, gerätst im Ödland bestimmt oft in gefährliche Situationen. Möge dir die Pharmakologie helfen! Nur heute – zwei zum Preis von ... zwei natürlich, wir müssen schließlich alle essen.}
{201}{}{Stimpak, 5.}
{202}{}{Super-Stimpak, 3.}
{203}{}{Psycho, 3.}
{204}{}{Anti-Raucher, 5.}
{205}{}{Nichts. Ich mache es kostenlos.}

{206}{}{Na gut. Wie du willst. Bring einfach die Beweise zur Polizei. Um den Rest kümmern wir uns.}
{207}{}{Prima. Ich gehe.}

{208}{}{Erledigt! Die Beweise sind abgegeben, du bist jetzt offiziell unschuldig.}
{209}{}{Ich bin gekommen, um dir mitzuteilen, dass dein Name reingewaschen ist. Du kannst in Ruhe schlafen. Die Polizei wird dich nicht wieder aufsuchen.}

{210}{}{Danke. Wir hatten schon einen Bullen, der hierherkam. Du hast uns vor dem Exil bewahrt. Du bist ein guter Mann. Genau wie wir. Niemand hier wird das je vergessen.}
{211}{}{Du hast versprochen, mich für meine harte Arbeit zu belohnen. Hast du das vergessen?}
{212}{}{Ein einfaches „Danke“ würde reichen.}

{213}{}{Alles in Ordnung. Missbrauch es nicht – das ist mein Rat an dich. Sonst wirst du high, wie wir. Ha-ha-ha!}
{214}{}{Lustig. Du wärst perfekt für eine Comedyshow im Fernsehen, Larry.}

{215}{}{Danke. Wir hatten schon einen Bullen hier, der sich offiziell entschuldigt hat. Wie du siehst, siegt die Gerechtigkeit.}
{216}{}{Genau. Pass auf dich auf.}

{217}{}{Ich sehe, dass jemand gezielt versucht, dich aus dem Hotel zu werfen.}
{218}{}{Was ist mit dieser Quittung?}
{219}{}{Der glatthäutige Wanderer ist wieder bei uns! Wie überraschend.}
{220}{}{Wegen der Beweise – ich kann sie nicht zur Polizei bringen. Such nach einem anderen Weg.}

#Ïëàâàşùèå ôğàçêè ïîñëå îáëàâû
{221}{}{Was sollen wir jetzt tun?}
{222}{}{Wir werden keinen neuen Ort zum Leben finden.}
{223}{}{Jetzt sind wir schlimmer dran als Bettler.}
{224}{}{Verdammt! Das war's wohl ...}
{225}{}{Pech gehabt!}
{226}{}{Es ist Zeit, sich von unserem Leben zu verabschieden.}

#Ïîëó÷åíèå äîñòèæåíèÿ "Çíàõàğü"
{227}{}{Wie hast du gelernt, diese Heilpulver herzustellen?}
{228}{}{So kompliziert ist das nicht. Wir sind Meister des Überlebens. Ohne unser Wissen über die Natur wären wir schon längst tot.}
{229}{}{Kannst du mir beibringen, Pulver und Stimmpacks herzustellen?}
{230}{}{Stimmt.}
{231}{}{...Aber niemand weiß, wofür dieses Wissen später eingesetzt wird. Denk nicht einmal daran. Dieser tote Körper erinnert sich noch an Stolz und Ehre.}
{232}{}{Hör mal, wie du jetzt redest!}
{233}{}{Gern! Ich glaube, du wirst dieses Wissen zum Wohl der Menschen einsetzen.}
{234}{}{Klar. Sollen wir anfangen?}
{235}{}{Jetzt nicht.}
{236}{}{}

{237}{}{[Insgeheim das Gespräch auf deinem Pip-Boy aufzeichnen] Was kannst du über seine Drogensucht sagen?}

#Ğàáî÷àÿ ïğîáëåìà íà äàìáå
{238}{}{Ich sehe, dass man dich in dieser Stadt nicht gerade willkommen heißt. Wo arbeitest du?}
{239}{}{Arb- arbeiten? Wir haben weder Geschäfte noch Arbeit. He-he.}
{240}{}{Und wovon lebt ihr dann?}
{241}{}{Wir schlagen uns irgendwie durch. Zum Beispiel haben wir nicht weit von hier ein paar Felder.}
{242}{}{Was wäre, wenn ich dir einen festen, sicheren Arbeitsplatz anbieten würde? Nicht gerade ungefährlich, aber immerhin sicher. Ich meine die Hoover Dam, vielleicht hast du davon gehört ...}
{243}{}{Na ja, wenn man darüber nachdenkt, sind wir für jede Arbeit bereit ... Falls sie uns nehmen. Aber das werden sie nicht.}
{244}{}{Sie werden euch nehmen. Bob Neil geht es gerade schlecht, er ist bereit, diese Möglichkeit in Betracht zu ziehen ... glaube ich.}
{245}{}{Das wäre eine annehmbare Lösung für uns, ja. Aber irgendwie bezweifle ich, dass dieser Mann zustimmen würde. Warum fragst du ihn nicht? Wir wären bereit, sogar schon ab morgen!}
{246}{}{Ausgezeichnet! Ich rede mit Bob.}
{247}{}{Du hast die Freaks dazu überredet, für Bob Neil zu arbeiten. Hmm ... Jetzt muss ich nur noch Bob Neil selbst überzeugen.}

{248}{}{Ernsthaft? Einfach so, für ein „Dankeschön“, hast du dein Leben riskiert? Na, dann kann ich dich nicht mit leeren Händen gehen lassen. Hier, nimm das. [Er gibt dir zwei Päckchen bunter Pillen] Ein sehr guter ... „Gedächtnisauffrischer“. He-he. Ich hoffe, du verstehst, was ich meine.}
{249}{}{Noch nicht, aber ich werd's schon herausfinden. Danke!}

#Female character
{1109}{}{Da kommt unser glatthäutiger Freund ... Für uns bist du natürlich immer noch glatthäutig. Aber es ist ein Rätsel, wie du mit so einem Gesicht in Clean City nicht erschossen wirst.}
{1110}{}{Du solltest hier besser nicht herumstreunen. Unser Hotel ist kaum besser als der örtliche Friedhof. Ha-ha! Nur ein Scherz. Der Friedhof ist natürlich viel besser ...}
{1123}{}{Warte, du hast noch nie von uns gehört? Man hat dich nicht einmal gewarnt, dass man uns besser meidet? Sieht aus, als wärst du neu in der Stadt!}
{1127}{}{Mit unseren Gesichtern? Oh, Wanderer, das kann ich dir nicht sagen, sonst kotzt du gleich überall hin. Ha-ha!}
{1166}{}{Ich bin ehrlich zu dir. Sei auch du ehrlich zu mir.}
{1167}{}{[Heimlich das Gespräch auf deinem Pip-Boy aufnehmen] Ich bin ehrlich zu dir. Sei auch du ehrlich zu mir.}
{1168}{}{Ich bin ehrlich ... und meine es ernst. So ernst, wie ich nur kann. Ja, wir hatten schwere Zeiten und haben früher Pulver mit viel stärkerer Wirkung hergestellt. Aber das liegt hinter uns. Du musst uns glauben.}
{1191}{}{Hör zu, wir sind nicht die besten Leute in der Stadt, das weiß ich. Man fürchtet uns. Und wir haben Angst. Aber du nicht. Nicht einmal die Polizei kann es mit dir aufnehmen! Lass uns nicht im Stich! Dafür helfen wir dir auch.}
{1193}{}{Das glaubst du wohl! Ich bin doch nicht mein eigener Feind! Hier, du bringst die Beweise hin, und ich bin weg. Mein Auftrag ist erledigt.}
{1200}{}{Du, Wanderer, gerätst im Ödland bestimmt oft in gefährliche Situationen. Möge dir die Pharmakologie helfen! Nur heute – zwei zum Preis von ... zwei natürlich, wir müssen schließlich alle essen.}
{1209}{}{Ich bin gekommen, um dir mitzuteilen, dass dein Name reingewaschen ist. Du kannst in Ruhe schlafen. Die Polizei wird dich nicht wieder aufsuchen.}
{1210}{}{Danke. Hier war schon mal ein Cop. Du hast uns vor dem Exil bewahrt. Du bist ein guter Mensch. Genau wie wir. Niemand hier wird das je vergessen.}
{1219}{}{Der glatthäutige Wanderer ist wieder bei uns! Wie überraschend.}
{1245}{}{Das wäre eine annehmbare Lösung für uns, ja. Aber irgendwie bezweifle ich, dass dieser Mann zustimmen würde. Warum fragst du ihn nicht? Wir wären bereit, sogar schon ab morgen!}
{1248}{}{Ernsthaft? Einfach so, für ein „Dankeschön“, hast du dein Leben riskiert? Na, dann kann ich dich nicht mit leeren Händen gehen lassen. Hier, nimm das. [Er gibt dir zwei Päckchen bunter Pillen] Ein sehr guter ... „Gedächtnisauffrischer“. He-he. Ich hoffe, du verstehst, was ich meine.}
