{100}{}{Du siehst den Bürgermeister.}
{101}{}{Du siehst Mr. Williamson, den Bürgermeister von Las Vegas. Trotz seiner hohen Stellung wirkt er ziemlich schlicht.}
{102}{}{Hast du einen Termin? Verlass mein Büro, bevor ich die Wachen rufe!}
{103}{}{Sicherheit! Ein Eindringling im Büro!}

#Starting cues
{110}{}{Ich höre.}
{111}{}{Mr. Williamson, vielleicht könnte ich der Stadt nützliche Dienste leisten? Oder sogar Ihnen persönlich?}
{112}{}{Was die Ermittlungen angeht ...}
{113}{}{Könnten Sie mir helfen, die Koordinaten von Area 51 zu finden?}
{114}{}{Ich habe nichts. Mach's gut.}

#Area 51
{115}{}{Ist das alles? Bitte belästigen Sie mich nicht mit solchen Kleinigkeiten. Sprechen Sie mit meiner Sekretärin.}
{116}{}{Warten Sie, halt! Ich brauche das wirklich!...}
{117}{}{Na gut, dann frage ich eben jemand anderen.}
{118}{}{Nun, ich denke, Sie haben Zugang zu unserem Archiv verdient. Sprechen Sie mit unserem Chefarchivar; er wird Ihnen alle nötigen Informationen geben.}
{119}{}{Danke, Mr. Williamson!}

#Finding work
{121}{}{Ja, ich glaube, ich habe etwas für Sie. Ich bitte Sie, diese Angelegenheit als meine persönliche Bitte zu betrachten, auch wenn ihre Lösung das Schicksal der Stadt maßgeblich beeinflussen würde.}
{122}{}{Klingt interessant.}
{123}{}{Machen Sie es sich bequem. Wir haben viel zu besprechen.}
{124}{}{Danke, Mr. Williamson.}

{125}{}{Möchten Sie eine Tasse Kaffee? Karamell? Eine Zigarre?}
{126}{}{Danke, gegen ein Stück Karamell habe ich nichts einzuwenden.}
{127}{}{Nein danke, kommen wir gleich zur Sache.}

{128}{}{Ich fürchte, Sie sehen nicht so aus, als wären Sie der Aufgabe gewachsen. Danke für das Angebot.}
{129}{}{Das ist bedauerlich.}

{130}{}{Also gut, kommen wir zur Sache.}
{131}{}{Ich höre.}
{132}{}{Wie Sie wahrscheinlich wissen, gibt es in der Nähe von Las Vegas ein riesiges Kraftwerk, das nach dem Großen Krieg, so ungewöhnlich das auch ist, fast unversehrt geblieben ist. Ich spreche natürlich von Hoover Dam. Für unsere Stadt ist es ein sehr wichtiges Unternehmen. Ihm verdankt Las Vegas seinen heutigen Status als wichtiger strategischer Punkt auf der Landkarte und einflussreicher Akteur auf der Weltbühne. Natürlich kann ein so wichtiges Objekt nicht einer einzelnen Partei gehören, sei es eine Einzelperson oder eine Organisation. Deshalb beschloss die Stadt, die Kontrollrechte über das Kraftwerk unter den Vertretern der städtischen Eliten aufzuteilen. Ein System aus Anteilen – oder Kontingenten – wurde eingeführt, um den Entscheidungsprozess transparenter und verantwortungsvoller zu gestalten ... Leider hat sich die Lage in letzter Zeit zugespitzt.}
{133}{}{Was meinen Sie mit „zugespitzt“?}
{134}{}{Die Arbeitsbedingungen im Kraftwerk sind ... nicht gerade angenehm. Ein so großes Unternehmen wie das Hoover Dam braucht viele Arbeitskräfte, darunter Ingenieure und Wartungspersonal. Das ist eine enorme finanzielle Belastung für die Stadt, deshalb lassen die Löhne für gering qualifizierte Arbeiter zu wünschen übrig. Außerdem haben der heruntergekommene Zustand der Anlagen, die erhöhte Strahlung, die schlechte Schalldämmung und andere Probleme zu gewissen Schwierigkeiten bei der ... Einstellung von Personal geführt. Am besten sprichst du darüber aber mit Bob Neil selbst – er ist Chefingenieur und Geschäftsführer des Hoover Dam.}
{135}{}{Soll ich dir dabei helfen, Arbeitskräfte für das Kraftwerk zu finden?}
{136}{}{...Nein. Als die Öffentlichkeit von diesen Problemen erfuhr, stieg die Kriminalität in der Stadt deutlich an. Und in den meisten Fällen waren die Arbeiter des Kraftwerks die Opfer dieser Verbrechen. Ich glaube nicht, dass das ein Zufall ist. Außerdem standen laut den Polizeiberichten die meisten festgenommenen Verbrecher unter Drogeneinfluss. Und das beunruhigt mich noch mehr.}
{137}{}{Von welchen Drogen sprechen wir?}
{138}{}{Ich bin kein Experte für Medizin oder Chemie, aber in denselben Polizeiberichten stand, dass es nicht um harmloses Gras oder gar Pilze geht – wir sprechen von Psychedelika, Opiaten und anderen synthetischen oder halbsynthetischen Drogen. Das bedeutet, dass nicht bloß ein paar Hobbychemiker dahinterstecken – obwohl ich keine Möglichkeit ausschließen würde.}
{139}{}{Dann müssen wir den Hauptlieferanten der Drogen finden.}
{140}{}{Richtig. Aber worauf ich hinauswill: Ich habe Grund zu der Annahme, dass alles zusammenhängt: die Probleme im Hoover Dam, die steigende Zahl der Verbrechen und die Angriffe auf die Mitarbeiter des Damms. Und das bedeutet zweifellos, dass jemand davon profitiert.}
{141}{}{Du vermutest also, dass all das geschieht, um ein zwielichtiges Ziel zu erreichen?}
{142}{}{Ich nehme an, dass alles, was geschieht, einen Grund hat. Jemand nutzt die Situation aus. Und genau das wirst du untersuchen.}
{143}{}{Warum setzt du nicht die Polizei darauf an?}
{144}{}{Die Polizei versucht bereits alles, was in ihrer Macht steht, aber das reicht einfach nicht aus, um alles auf einmal zu bewältigen. Allerdings hat sie schon einige Spuren. Sie glaubt, dass die Gruppe der ausgestoßenen Ghule – Freaks – darin verwickelt ist, und hat auch einen gewissen Verdacht gegen einen anderen bedeutenden Unternehmer in der Las Vegas – Herrn Sam Phillips. Weitere Einzelheiten dazu kann dir Polizeichef Oscar Davis geben. Ich kenne ihn als ehrlichen und verantwortungsbewussten Beamten – auch wenn er es mit der Einhaltung von Vorschriften ein wenig zu genau nimmt.}
{145}{}{Verstehe.}
{146}{}{Also möchte ich, dass du herausfindest, wer für all das verantwortlich ist, was in der Stadt vor sich geht. Ich bitte dich, nach Beweisen zu suchen – Dokumenten, Aufzeichnungen, Briefen –, nach allem, womit du deine Behauptungen untermauern kannst.}
{147}{}{Gehst du davon aus, dass es nur einen begrenzten Kreis von Verdächtigen gibt?}
{148}{}{Weißt du, es gibt nicht viele Leute, die die wirtschaftliche Lage hier tatsächlich beeinflussen können. Die Las Vegas ist, sagen wir mal, nicht gerade reich an einflussreichen Leuten. Gesellschaftlicher Aufstieg ist praktisch unmöglich. In unserem Fall ist also ganz klar derjenige, der nach mehr Macht strebt, jemand, der bereits reichlich davon hat.}
{149}{}{Hast du einen bestimmten Verdacht?}
{150}{}{Ja, habe ich. Aber ich möchte dir meine Vermutung nicht vorzeitig verraten. Ich möchte, dass du dir selbst ein Bild von den Ereignissen machst.}
{151}{}{Gut. Fassen wir also zusammen.}

{152}{}{Machen wir das. Hier ist deine Aufgabe: Untersuche, woher die Drogen kommen, die die Stadt überschwemmen. Finde heraus, wer der wichtigste Hersteller und Lieferant ist. Und wer davon profitiert. Wenn du genügend Beweise gesammelt hast, die sich zu einem stimmigen Bild zusammenfügen lassen, berichte mir davon. Wenn du Erfolg hast, bekommst du 30.000 Dollar in bar.}
{153}{}{Kann ich etwas davon im Voraus bekommen?}
{154}{}{Das ist ein Preis, für den es sich zu arbeiten lohnt. Ich nehme den Auftrag an.}

{155}{}{Sehr gut. Ich warte auf deinen Bericht. Lass dir nicht zu lange Zeit und ... sei vorsichtig. Übrigens sehe ich, dass du ein Pip-Boy hast. Du weißt doch, was dieses Gerät kann, oder? Insbesondere, dass es Gespräche aufzeichnen kann.}
{156}{}{Ja, ich kenne mich mit meinem Pip-Boy aus und weiß, wie man diese Funktion benutzt.}
{157}{}{Ehrlich gesagt, wusste ich das nicht.}
{158}{}{Dann merk dir das. Ich nehme an, die Aufzeichnungen könnten als Beweis dafür dienen, dass bestimmte Personen an bestimmten Ereignissen beteiligt waren.}
{159}{}{In Ordnung, ich werde daran denken.}
{160}{}{Na dann, viel Glück bei deinen Ermittlungen.}
{161}{}{Ich fange sofort an, Mr. Williamson.}

{162}{}{Du hast einen Ermittlungsauftrag im Zusammenhang mit Drogen übernommen. Der Auftrag ist ebenso gefährlich wie wichtig.}

#Reward and deposit
{163}{}{Ja, natürlich. Aber höchstens 10% of der Belohnung. Wie viel brauchst du?}
{164}{}{6000}
{165}{}{5000}
{166}{}{4000}
{167}{}{3000}
{168}{}{2000}
{169}{}{1000}
{170}{}{Ich denke, ich sammle alles nach Abschluss ein.}

{171}{}{Hier ist dein Vorschuss. Du bekommst erst mehr, wenn du den Auftrag abgeschlossen hast.}
{172}{}{Verstanden.}
{173}{}{Kann ich einen Vorschuss bekommen, damit ich mir bei den Ermittlungen helfen kann?}

{174}{}{Andererseits nehme ich lieber alles auf einmal.}
{175}{}{Na dann, Zeit, es mir zu verdienen.}

#Completing the main quest
{176}{}{Hast du neue Hinweise zu deinen Ermittlungen?}
{177}{}{Ich glaube nicht, dass ich genug habe.}
{178}{}{Ja, ich bin sicher, dass ich genug Beweise gesammelt habe, um alles zu erklären.}

{179}{}{Also gut. [Zur Sekretärin] Marion, lassen Sie niemanden in mein Büro, ich habe eine wichtige Besprechung! Gut, ich höre zu.}
{180}{}{Ich sollte wohl damit anfangen, dass unser geheimnisvoller Verdächtiger großen Einfluss auf die Stadtpolizei von Las Vegas hat. Kurz nachdem ich auf dem Revier ein paar Fragen gestellt hatte, erwartete mich einer der Inspektoren an den Toren von Clean City. Er hatte den Befehl, mich zu töten. Ich konnte nicht herausfinden, wer oder was ihn dazu gebracht hat, aber offensichtlich ging es nicht von ihm selbst aus.}
{181}{}{Also ist die Polizei involviert. Keine Überraschung - jede gesellschaftliche Institution zieht Unzufriedene an, die den aktuellen Zustand der Dinge ablehnen. Hast du Beweise, die helfen könnten, die gesuchte Person zu identifizieren?}
{182}{}{Das tue ich. Laut diesem Dokument hier hat die Polizei zusätzliche Haushaltsmittel ausgegeben, um Ermittlungen im Zusammenhang mit Drogenfällen Vorrang zu geben. Gleichzeitig hatte die Polizei aber bereits ihre Hauptverdächtigen – die Freaks und Sam Phillips.}
{183}{}{[Der Bürgermeister studiert sorgfältig den Beleg von Oscar Davis] Hm. Die Anordnung, das Budget zu überschreiten, ist von Tom Parker unterzeichnet. Und offenbar beschloss er, über den Polizeichef tätig zu werden. Den Drogenfällen „Vorrang geben“, obwohl die Freaks und Sam Phillips bereits beschuldigt werden ... Davis nahm die Sache bestimmt sehr ernst – er würde nichts ohne handfeste Beweise gegen die Ghule und Sam unternehmen. Was konntest du über Phillips herausfinden?}
{184}{}{Er wurde beschuldigt, Chems herzustellen – eine anonyme Quelle meldete das der Polizei. Bei der Durchsuchung fanden die Cops eine Substanz, die angeblich zur Drogenherstellung verwendet werden könnte.}
{185}{}{Ist er wirklich darin verwickelt?}
{186}{}{Ich habe die Aufzeichnung eines Gesprächs mit Larry Geller, dem Anführer der Ghule. Er glaubt, dass Phillips sich an das Gesetz hält.}
{187}{}{Ich habe die Aufzeichnung eines Gesprächs mit einem der örtlichen Dealer. Er sagte, Phillips habe weder Drogen noch Materialien zu ihrer Herstellung gekauft.}
{188}{}{Er wurde festgenommen. Es wurden jedoch keine Beweise für seine Schuld gefunden, also scheint er unschuldig zu sein.}
{189}{}{Das habe ich noch nicht herausgefunden.}
{190}{}{Was machst du dann noch hier?! Geh und erledige deine Arbeit!}
{191}{}{Wie Sie wünschen, Herr Bürgermeister.}
{192}{}{Ich glaube schon ... Ja ... Gibt es hier zufällig noch einen anderen Sam Phillips?}
{193}{}{Ich glaube schon, auch wenn ich nicht weiß, wer dafür verantwortlich ist.}

{194}{}{Ich habe die Aufzeichnung eines Gesprächs mit Larry Geller, dem Anführer der Ghule. Er glaubt, dass Phillips sich an das Gesetz hält.}
{195}{}{Ich habe mit Larry Geller, dem Anführer der Ghule, gesprochen. Er glaubt, dass Phillips sich an das Gesetz hält.}
{196}{}{Ich konnte das noch immer nicht herausfinden.}
{197}{}{Ich habe die Aufzeichnung eines Gesprächs mit einem der örtlichen „Dealer“. Er sagte, Phillips habe weder Drogen noch Materialien zu ihrer Herstellung gekauft.}
{198}{}{Ich habe mit einem der örtlichen „Dealer“ gesprochen. Er sagte, Phillips habe weder Drogen noch Materialien zu ihrer Herstellung gekauft.}
{199}{}{Ich konnte das noch immer nicht herausfinden.}
{200}{}{Du meinst, ich soll dir einfach glauben?}
{201}{}{Nun ... ich habe das Gespräch nicht aufgezeichnet.}
{202}{}{Trotz der Skepsis des Polizeipräsidiums konnte ich sie davon überzeugen, dass die Beweise, die sie gegen Sam Phillips haben, seine Beteiligung am Drogenhandel nicht belegen.}

{203}{}{Okay, die Sache mit der Beteiligung von Sam Phillips ist weitgehend geklärt. Aber die Frage bleibt: Wo kommen die Drogen her? Und die Freaks – haben sie etwas damit zu tun?}
{204}{}{Tatsächlich konnte ich das gesamte Drogenlabor am Stadtrand ausfindig machen.}
{205}{}{Ich bin noch dran. Im Moment habe ich keine Antwort.}

{206}{}{Ein ganzes Labor?! Genau das hatte ich vermutet. Die Mengen an Chems waren einfach zu groß – für einen kleinen Betrieb wäre ihre Herstellung nahezu unmöglich. Was hast du darüber herausgefunden? Vor allem: Weißt du, wer die Anlage leitet?}
{207}{}{Das Labor setzt zwar Sklaven als Arbeitskräfte und Versuchskaninchen für neue Produkte ein, was auf eine Verbindung zur Sklavenhändlergilde hindeuten könnte, aber in den Aufzeichnungen des Labors finden sich keine Namen. Ich denke, wir können die Freaks von der Liste der Verdächtigen streichen – hier sind die Dokumente, die ich in der Sklavenstadt gefunden habe.}
{208}{}{Das habe ich noch nicht herausgefunden.}
{209}{}{Lass mich mal sehen. Wo hast du das her?}
{210}{}{Aus dem Safe von Vortis, dem Oberhaupt der Sklavenhändlergilde.}
{211}{}{Dem hier zufolge wartet Vortis darauf, dass man den Freaks etwas anhängt. Wir können also getrost sagen, dass die Freaks unschuldig sind. Trotzdem macht mir diese Person namens „Boss“ Sorgen, die auf dem überteuerten Sklavengeschäft besteht. Hast du eine Ahnung, wer das sein könnte?}
{212}{}{Ich habe noch eine Notiz aus dem Labor über den Kauf einer Chemlieferung. Darin wird ein Käufer erwähnt – das Casino „Drei-Karten-Monte“.}
{213}{}{Ich weiß, dass Hal Wallace mit den Drogen zu tun hat. Ich habe ein Gespräch mit ihm aufgezeichnet, in dem er versucht hat, mich zu einer Straftat zu überreden.}
{214}{}{Leider ist das alles, was ich beweisen kann.}
{215}{}{Das Casino ist ein sehr einträgliches Geschäft. Warum muss er sich dann auch noch mit Drogen beschäftigen?}
{216}{}{Ich habe keine Beweise, aber meine Theorie ist folgende: Es gibt immer Leute, die mehr zu zahlen bereit sind als den derzeit angesetzten Preis. Warum sollte man sich so eine Gelegenheit entgehen lassen? Er maximiert einfach seinen Gewinn.}
{217}{}{Nehmen wir das einmal an. Inzwischen hast du also herausgefunden, dass die Drogen, die die Stadt überschwemmen, in einem großen Drogenlabor hergestellt wurden. Auf seinem Gelände wird ausgiebig Sklavenarbeit eingesetzt, und auch beim Testen neuer Produkte kommen Sklaven zum Einsatz. Irgendjemand leitet dieses Labor. Und es ist nicht Hal Wallace – er ist der Käufer. Gleichzeitig verhandelt Vortis mit irgendeinem „Boss“ über beiderseitige Vorteile aus dem Sklavenhandel, nachdem die Ghoule angesiedelt wurden – aber wer hätte etwas gegen sie?}
{218}{}{Soweit ich weiß, passen die Ghoule perfekt zu Hoover Dam – ihre Arbeitskraft ist billig, die Ghoule selbst sind freundlich, und außerdem würde unter den jetzigen Umständen sonst niemand am Damm arbeiten wollen. Wenn es keine Freaks gibt, bleibt dem Leiter des Kraftwerks nur, Sklaven einzusetzen.}
{219}{}{[Nickt] Ich verstehe. Davon profitieren diejenigen, die mit Sklaven handeln. In unserem Fall also die Sklavenhändler.}
{220}{}{Genauer gesagt: derselbe „Boss“ der Sklavenhändler und der Besitzer des Drogenlabors. Ich vermute, es ist ein und dieselbe Person.}
{221}{}{Es ist nicht Sam Phillips – er hat weder mit Drogen noch mit Sklavenhändlern zu tun. Es ist nicht Hal Wallace – es ergibt keinen Sinn, sich selbst als Käufer in ein Dokument einzutragen und aufzufliegen, falls es durchsickert. Vortis ist es auch nicht, denn er hat die Informationen über die Freaks von jemand anderem erhalten. Bob Neil ist es ganz sicher nicht – dieser geheimnisvolle Jemand hat Verbindungen und Einfluss beim Polizeirevier von Las Vegas. Und auch Oscar Davis ist nicht der Schuldige, denn er würde nicht auf irgendwelche Beweise warten, um Sam Phillips und die Freaks loszuwerden. Also bleibt uns ...}
{222}{}{Tom Parker. Ich habe ein von ihm unterzeichnetes Dokument, das 6% of der Anteile der Gemeinde an die Gilde der Sklavenhändler überträgt.}
{223}{}{Tom Parker. Allerdings habe ich keinen Beweis dafür, dass er mit dem Labor oder den Sklavenhändlern in Verbindung steht.}
{224}{}{[Nimmt dir das Dokument ab] Tom Parker. Ehrgeizig ist er, das steht fest, aber ich verstehe nicht, was er damit erreichen wollte. Hätte er versucht, diese Übertragung durchzuziehen, hätte das viele Fragen aufgeworfen. Nicht nur von mir.}
{225}{}{Ich nehme an, er hat sich dafür eine Erklärung zurechtgelegt.}
{226}{}{Sagen wir, er ist unser Mann. Wie hängen die Sklavenhändler und Parker zusammen? Welche Rolle spielt Hal Wallace?}
{227}{}{Ich glaube, Wallace sollte sich um die Freaks kümmern. Ohne dass Polizei oder Sklavenhändler involviert wären.}
{228}{}{Ergibt Sinn. Parker hatte schon einmal drastische Maßnahmen gegen die Freaks gefordert, doch bei Davis kam er damit nicht durch – es gab keine handfesten Beweise. Hätte Parker sie weiter beschuldigt, schuldig zu sein, hätte das großen Verdacht erregt.}
{229}{}{Also verschafft er sich ein Alibi, indem er Wallace dazu zwingt, die Arbeit zu erledigen.}
{230}{}{Sieht ganz danach aus. Gehen wir zum Anfang zurück und fassen alles zusammen.}
{231}{}{Ja. Es war so: Tom Parker – der Boss der Sklavenhändler und Besitzer eines Drogenlabors. Als es Probleme mit den Arbeitskräften am Staudamm gab, beschloss er, aus der instabilen Lage Profit zu schlagen.}
{232}{}{Er erhöht die Produktion und die Drogenlieferungen in die Stadt, was zu einem Anstieg der Kriminalität führt. Wahrscheinlich gab er sogar direkte Befehle, die Arbeiter der Anlage anzugreifen.}
{233}{}{Da die Stadt ohne Strom nicht überleben kann und die Zahl der Arbeitskräfte am Staudamm immer weiter sinkt, würde Bob Neil sich früher oder später Sorgen machen, dass es an Arbeitskräften für die Anlage mangelt.}
{234}{}{Doch die soziale Lage sorgt dafür, dass niemand diese Jobs übernehmen will. Letztlich bleiben also nur zwei Möglichkeiten – Freaks oder Sklaven. Und die zweite Option kommt Parker sehr gelegen.}
{235}{}{Aber da ist ein Problem – Freaks sind billig, zäh, machen sich wenig aus Strahlung und verfügen paradoxerweise oft über umfangreiche, einschlägige Erfahrung. Für den Staudamm sind sie viel besser geeignet.}
{236}{}{Doch das würde Toms Geschäftsinteressen zuwiderlaufen. Also beschließt er, die Freaks loszuwerden.}
{237}{}{Da Parker die Arbeitsweise von Oscar Davis kennt, startet er eine energische Kampagne gegen Drogenprobleme und erhöht die Mittel für die Polizei. So versucht er, sie dazu zu bringen, die Fälle zu untersuchen, die ihn interessieren – Fälle, in die Freaks verwickelt sind.}
{238}{}{Davis hat es jedoch nicht eilig, die Ghule zu beschuldigen, und verlangt handfeste Beweise. Also macht Parker seinen Zug.}
{239}{}{Er zieht Hal Wallace in die Sache hinein, um ihn das Problem erledigen zu lassen und selbst sauber dazustehen. Ich nehme an, sie hatten bereits gemeinsame Geschäfte laufen: Das Labor versorgte das Casino mit Drogen, während das Casino durch deren Verkauf zusätzliche Gewinne erzielte, was wiederum zum Chaos in der Stadt beitrug.}
{240}{}{Gemeinsam schließen sie einen neuen Deal: Wallace hilft den Freaks dabei, Chems herzustellen, und bekommt dafür das Versprechen, dass sein Hauptkonkurrent, Mr. Sam Phillips, aus dem Weg geräumt wird.}
{241}{}{Natürlich sieht Tom Parker darin eine weitere Gelegenheit, von sich abzulenken und die Aufmerksamkeit auf die Freaks zu lenken, und beschuldigt Sam Phillips ganz offen, in den Drogenhandel verwickelt zu sein.}
{242}{}{Oscar Davis beginnt, gegen Phillips zu ermitteln. Wallace legt den Freaks echte Drogen unter.}
{243}{}{Die Polizei macht mit den Freaks kurzen Prozess. Das Kraftwerk ist gezwungen, Sklaven zu kaufen, um den Betrieb aufrechtzuerhalten.}
{244}{}{Parker macht enorme Gewinne, sowohl mit dem Sklavenhandel als auch mit dem Drogenhandel in der Stadt.}
{245}{}{Er hätte Hal Wallace sogar wie den Hauptverdächtigen aussehen lassen können, falls etwas schiefgegangen wäre.}
{246}{}{Stimmt. Aber warum wollte er die Anteile der Gemeinde an die Sklavenhändler übertragen? Und wie hätte er das erklärt?}
{247}{}{Er hätte Gewinn gemacht und außerdem seinen Einfluss auf den Damm vergrößert – schließlich wären die Anteile der Sklavenhändler auch seine Anteile. Ich glaube, ihn hielt nur zurück, dass er nicht erklären konnte, warum er das tun sollte. Aber irgendwann wäre ihm schon etwas eingefallen.}
{248}{}{Vielleicht. Oder vielleicht hätte er mich irgendwie dazu überreden können, es zu unterschreiben, oder einfach meine Unterschrift gefälscht. Dann hätte es so ausgesehen, als wäre ich darin verwickelt. Mit dem Dokument hätte er mich unter Druck setzen können.}
{249}{}{Wer nach mehr Macht strebt, hat offensichtlich bereits reichlich davon.}
{250}{}{Ja, das habe ich gesagt, als wir uns zum ersten Mal trafen. Es tut mir leid, dass ich damit recht hatte.}
{251}{}{Parker hat nur einen Fehler gemacht: Er hat den Polizeibeamten damit beauftragt, mich umzubringen.}
{252}{}{Und deshalb hast du verstanden, dass derjenige, der dahintersteckt, die Polizei beeinflusst.}
{253}{}{Ja. Das war die erste Spur.}
{254}{}{Nun, Sie haben Ihre Arbeit bewundernswert erledigt und geschafft, was sonst niemand konnte. Für die brillante Aufklärung dieses Falls spreche ich Ihnen meinen persönlichen Dank aus. Danke.}
{255}{}{Danke, Mr. Williams.}
{256}{}{Ich bitte Sie, mir die Beweise zu überlassen, die Sie mitgebracht haben – sie werden im Strafverfahren verwendet. Außerdem wäre ich Ihnen dankbar, wenn Sie mir helfen würden, den vollständigen Bericht für den Rat vorzubereiten.}
{257}{}{Natürlich. Fassen wir die Ergebnisse noch einmal zusammen ...}
{258}{}{Und hier ist Ihre Belohnung. Im Namen der gesamten Clean City danke ich Ihnen!}
{259}{}{Danke. Was haben Sie jetzt vor?}
{260}{}{Die Beweise werden dem Gericht übergeben. Tom Parker wird wegen organisierter Kriminalität angeklagt, Hal Wallace wegen Beihilfe strafrechtlich verfolgt. Bis zum Abschluss des Gerichtsverfahrens wird Oscar Davis von seinen Pflichten als Polizeichef entbunden – die Beteiligung seiner Mitarbeiter muss überprüft werden. Danach sollte ich dem Rat eine Angelegenheit bezüglich der Hoover Dam vorlegen ... Ist da jemand hinter der Tür? Marion, ich hatte dich gebeten, niemanden hereinzulassen!}
{261}{}{Sieht aus, als hätten Sie Besuch ...}

#Floats upon completing the text
{262}{}{Tom? Was ist los?}
{263}{}{Wie ich sehe, haben Sie den legendären Detektiv von Las Vegas bei sich?}
{264}{}{Das geht dich nichts an, Tom ...}
{265}{}{Oh doch, ich denke schon. Dein Hund hat seine Nase in Dinge gesteckt, die ihn nichts angehen.}
{266}{}{... Du hast mich abgehört?}
{267}{}{Natürlich. Und ich hätte schon früher etwas tun sollen ...}
{268}{}{Dich aus einem verdammten Fenster werfen, du alter Bastard.}
{269}{}{Tom! Tu das nicht!}
{270}{}{Zu spät.}
{271}{}{Tom! Nein!!!}

{272}{}{Obwohl das Labor Sklaven als Arbeitskräfte und Versuchskaninchen für Tests neuer Produkte einsetzt, was für sich genommen auf eine Verbindung zur Sklavengilde hindeuten könnte, finden sich in den Laboraufzeichnungen keine Namen. Aber ich denke, wir können die Freaks von der Liste der Verdächtigen streichen – in Sklavenstadt habe ich Dokumente gefunden, denen zufolge jemand ihnen die Drogenherstellung anhängen will. Ich habe sie Oscar Davis übergeben.}

#Addition to being denied detective work
{273}{}{Warum glaubst du, dass ich damit nicht fertig werde?}
{274}{}{Na gut.}

{275}{}{Bei diesem Auftrag musst du mit vielen Leuten vorsichtig umgehen. Sehr vorsichtig, *mit Fingerspitzengefühl*.}
{276}{}{Du scheinst nicht gerade mit einer silbernen Zunge gesegnet zu sein. Und genau das ist bei dieser Aufgabe eine wichtige Fähigkeit.}
{277}{}{Ähem, es tut mir leid, wenn ich deine Gefühle verletze, aber deine geistigen Fähigkeiten scheinen eher ... mangelhaft zu sein. Für diesen Auftrag brauchst du mehr.}
{278}{}{Dir fehlt offenbar die Erfahrung, um eine so wichtige und gefährliche Aufgabe zu übernehmen.}
{279}{}{Wie wäre es, wenn du etwas übernimmst, das besser zu deinen Fähigkeiten passt.}
{280}{}{}

{281}{}{Erstens.}
{282}{}{Zweitens.}
{283}{}{Drittens.}

{284}{}{Das ist schade. Ich habe tatsächlich etwas Erfahrung. Auf meiner Reise habe ich bereits bei der Lösung von mehr als fünf ernsten Fällen mitgewirkt.}
{285}{}{Ähem. Wenn du tatsächlich Erfahrung hast, dann kann ich dir wohl die Einzelheiten erzählen.}

#Vendor's Cart
{300}{}{Ich bin wegen einer persönlichen Angelegenheit hier. Eine Bekannte von mir, eine Sandwichverkäuferin, hat Schulden, die sie nur schwer begleichen kann. Könnten Sie helfen?}
{301}{}{Als Mitmensch tut mir das mit Ihrer Freundin sehr leid. Aber sie hat Verpflichtungen, denen sie nachkommen muss. Bevor sie den Kredit aufnahm, hätte sie den Vertrag lesen sollen.}
{302}{}{Aber nur wegen der horrenden Raten kann sie keinen Gewinn machen. Könnte der Clean City ihr ein paar Monate Aufschub gewähren? Sie könnte ihr Geschäft ausbauen und mehr Geld in die Stadtkasse bringen.}

{303}{}{Ich will offen sein – es ist nicht meine Verantwortung. Ich kann meine Zeit nicht damit verbringen, den Stadtrat davon zu überzeugen, den Vertrag irgendeiner kleinen Händlerin zu ändern. Sie sollte einen Antrag bei der Verwaltung stellen, damit er ordnungsgemäß bearbeitet werden kann.}
{304}{}{Ist das so? Nun, ich betreibe hier selbst ein Geschäft – ich verkaufe Nuka-Cola. Ich könnte etwas von meiner eigenen Ware als Pfand anbieten, falls die Entlassung nichts bringt.}
{305}{}{Ich kenne mich mit Geschäften aus und denke, ich kann Ihren Rat mit handfesten Zahlen davon überzeugen, dass sich das lohnt.}
{306}{}{Es ist viel besser, der Händlerin einen Zahlungsaufschub zu gewähren, als für immer auf ihre Steuereinnahmen zu verzichten. Ich denke, ich kann Ihren Rat überzeugen.}
{307}{}{Herr Williams, ich bitte Sie darum als persönlichen Gefallen.}
{308}{}{Als erfahrener Anführer könntest du dabei helfen, die Sache mit dem Rat zu klären.}
{309}{}{Na ja, sieht so aus, als könnte man dich nicht überzeugen. Dann gehe ich jetzt.}

{310}{}{Ich sehe keinen Grund dazu. Der Rat wird dir ohne überzeugende Argumente einfach nicht zuhören. Wenn du zum Beispiel ein Geschäft in Vegas hättest oder dein Name in der Stadt Gewicht hätte, könntest du vielleicht auf die Entscheidungen einiger Ratsmitglieder Einfluss nehmen.}
{311}{}{Hm ... Das ändert die Lage natürlich. Ich gebe Bescheid, und du übergibst die Dokumente meiner Sekretärin.}
{312}{}{Perfekt.}
{313}{}{Ich würde erst gern noch ein paar Dinge meinerseits klären.}
{314}{}{Hm ... Ich glaube nicht, dass der Rat einem kleinen Händler zuhören wird.}
{315}{}{Du siehst aus, als könntest du deinen Standpunkt sogar gegenüber den starrköpfigen Ratsmitgliedern behaupten. Ich gebe Bescheid, und meine Sekretärin kümmert sich um die Dokumente. Alles Weitere liegt bei dir.}
{316}{}{Angesichts deiner Hilfe bin ich bereit, mich zu revanchieren. Ich gebe Bescheid, und meine Sekretärin kümmert sich um die Dokumente. Alles Weitere liegt bei dir.}
{317}{}{Der Rat hat grünes Licht gegeben. Zeit, die gute Nachricht zu überbringen.}

#Female version
{1157}{}{Ehrlich gesagt, wusste ich das nicht.}
{1174}{}{Andererseits nehme ich lieber alles auf einmal.}
{1178}{}{Ja, ich bin sicher, dass ich genug Beweise gesammelt habe, um alles zu erklären.}
{1180}{}{Ich sollte wohl damit anfangen, dass unser geheimnisvoller Verdächtiger großen Einfluss auf die Stadtpolizei von Las Vegas hat. Kurz nachdem ich auf dem Revier ein paar Fragen gestellt hatte, erwartete mich einer der Inspektoren an den Toren von Clean City. Er hatte den Befehl, mich zu töten. Ich konnte nicht herausfinden, wer oder was ihn dazu gebracht hat, aber offensichtlich ging es nicht von ihm selbst aus.}
{1205}{}{Ich bin noch dran. Im Moment habe ich keine Antwort.}
{1208}{}{Das habe ich noch nicht herausgefunden.}
{1253}{}{Ja. Das war die erste Spur.}
{1272}{}{Obwohl das Labor Sklaven als Arbeitskräfte und Versuchskaninchen zum Testen neuer Produkte einsetzt, was auf eine Verbindung zur Sklavengilde hindeuten könnte, stehen keine Namen in den Unterlagen des Labors. Aber ich glaube, wir können die Freaks von der Liste der Verdächtigen streichen – in Sklavenstadt habe ich Dokumente gefunden, denen zufolge jemand ihnen Drogenherstellung anhängen will. Ich habe sie Oscar Davis gegeben.}
