{100}{}{Du siehst den stellvertretenden Bürgermeister.}
{101}{}{Du siehst Tom Parker.}
{102}{}{Du siehst einen klein gewachsenen Mann mit Schnurrbart und einem fordernden Gesichtsausdruck. Dieser Mann ist der stellvertretende Bürgermeister.}

#Íà÷àëüíûå âîïğîñû
{110}{}{Tom Parker, der stellvertretende Bürgermeister. Was willst du?}
{111}{}{Was willst du?}
{112}{}{Ich suche die Koordinaten von Area 51. Können Sie mir helfen?}
{113}{}{Sag mal, wie viel verdienst du?}
{114}{}{Ich verlange eine Erklärung, warum Sie den Fall gegen Sam Phillips unterstützen!}
{115}{}{Ich schätze, ich brauche nichts.}

#Âûõîä èç äèàëîãà
{116}{}{Ist dir eigentlich klar, wo du bist? Das hier ist kein Bordell, sondern das Büro des Bürgermeisters! Ich verlange eine Erklärung! Was machst du hier?}
{117}{}{Ach ja? Und was, wenn ich nicht antworte? Hm?}
{118}{}{Ich bin geschäftlich hier. Mr. Williamson hat mich angeheuert.}
{119}{}{Tut mir leid, ich hatte einfach niemanden zum Reden.}
{120}{}{Tut mir leid, ich habe die Toilette gesucht. Ich schätze, das war die falsche Tür.}
{121}{}{Ich bin hier, um dir etwas Blut abzuzapfen.}
{122}{}{Ich suche das Archiv mit den Koordinaten von Area 51.}
{123}{}{Das Archiv ist am Ende des Flurs auf dieser Etage ... Obwohl es dir nichts nützen wird. Es ist nur für Mitarbeiter des Rathauses.}
{124}{}{Wow, na dann.}
{125}{}{Könnten Sie mir dabei helfen?}
{126}{}{Also gut, Bürger. Schluss mit dem Unsinn! Du bist nicht der erste zwielichtige Kerl, der ohne Grund ins Rathaus kommt. Leute wie dich brauchen wir hier nicht. Raus. Sofort! Aber zackig!}
{127}{}{Äh, sieh ihn dir an! Und was willst du jetzt tun, hm?!}
{128}{}{Schon gut, schon gut, ich gehe friedlich ...}
{129}{}{Wachen!!! Eindringling im Büro!!!}
{130}{}{[Widerstand leisten]}
{131}{}{[Gehorchen und mit einem Wachmann mitgehen]}
{132}{}{Hm. Jedenfalls muss ich dich bitten, dieses Büro zu verlassen.}
{133}{}{Wie du willst.}

#Ïî äåëó ìàôèîçíûõ ğàçáîğîê (äîïğîñû):
{134}{}{Ich verdiene genug, um über die Runden zu kommen. Und jetzt, verdammt noch mal, will ich eine Erklärung, warum das überhaupt zur Debatte steht.}
{135}{}{Hey, Großer, komm mal runter. Ich stelle hier die Fragen, mit der Vollmacht, die mir Mr. Williamson erteilt hat. Also, bestreitest du jegliche Beteiligung an den jüngsten Ereignissen in der Stadt?}
{136}{}{Hier stelle ich die Fragen!}
{137}{}{Ich war nur neugierig. Ehrlich.}
{138}{}{Äh ... Was?! Was soll das, ein Verhör?}
{139}{}{Was weißt du über den Fall Sam Phillips?}
{140}{}{Was hältst du von den Freaks?}
{141}{}{Hoover Dam. Bist du an diesem Unternehmen beteiligt?}
{142}{}{Hattest du jemals mit Rauschgift zu tun?}
{143}{}{Das ist eine Warnung. Wenn ich herausfinde, dass du in diese Verbrechen verwickelt bist, solltest du besser von diesem Planeten verschwinden.}
{144}{}{Keine weiteren Fragen. Du bist frei. Vorläufig.}
{145}{}{Oh, wir haben hier wohl einen harten Kerl! Wenn du mit deinen dämlichen Fragen fertig bist, fordere ich dich jetzt auf, mein Büro zu verlassen.}
{146}{}{Wie du willst.}
{147}{}{Weißt du, es war schön, einen Detektiv zu sehen, der noch am Leben ist ... Und jetzt bitte ich dich, mein Büro zu verlassen.}
{148}{}{Wie du willst.}
{149}{}{Was das „am Leben“ angeht – das werde ich mir merken. Behalt das im Hinterkopf, du Schlaumeier.}

{150}{}{Nur, dass er beschuldigt wurde, Drogen herzustellen, und noch nicht auf frischer Tat ertappt worden war.}
{151}{}{Am feindseligsten und skeptischsten. Für Clean City ist jede Ansteckung inakzeptabel.}
{152}{}{Ja, das tue ich. Früher wurde viel darüber gestritten. Schließlich kamen wir auf das Aktionärssystem, damit niemand ausgeschlossen werden konnte. Jeder gesellschaftlich aktive Mensch in der Stadt strebt danach, zumindest einen kleinen Anteil zu besitzen. Und das Bürgermeisteramt muss natürlich einen möglichst großen Anteil davon halten.}
{153}{}{Ähem. Die Stadt ist dadurch gewachsen, aber ich habe seit vielen Jahren nichts mehr davon verwendet und mit den Drogen nichts mehr zu tun.}

{154}{}{Das ist meine Aufgabe. Ich muss zur Entwicklung der Stadt beitragen, nicht zu ihrem Verfall oder ihrer Verwandlung in Schießbuden. Das reicht doch hoffentlich?}
{155}{}{Oh ja, fürs Erste reicht das.}
{156}{}{Ist das nicht eine zu hohe Investition für eine solche Kleinigkeit?}
{157}{}{Das geht dich nichts an.}
{158}{}{Jetzt mal langsam! Das ist ernst. Es geht um die Belastung der Stadtkasse.}
{159}{}{Wie du meinst.}
{160}{}{Verdammt! Warum muss ich mich für edle Taten rechtfertigen?! Warum sollte ich überhaupt Zweifel haben?! Die Verbrecher müssen bestraft werden, und es macht mir nichts aus, für eine gründliche Ermittlung mehr zu bezahlen. Findest du nicht auch?}
{161}{}{Du provozierst die Polizei also absichtlich, damit sie Sam Phillips verhaftet?}
{162}{}{Vielleicht hast du in gewisser Weise recht. Wir lassen diese Frage vorerst ruhen.}
{163}{}{Na schön, Herr Detective! Verdreh mir nicht die Worte im Mund. Ich versuche nicht, einen Unschuldigen hinter Gitter zu bringen. Ich unterstütze die Polizei dabei, Verbrechen aufzuklären, wie es sich gehört. Das ist meine direkte Pflicht als stellvertretender Bürgermeister!}
{164}{}{Na schön, belassen wir es vorerst dabei.}

#Çîíà 51
{165}{}{Area 51? Ich denke, solche Informationen müssten in unserem Archiv sein. Ich bin bereit, mir die Mühe zu machen, sie für dich herauszusuchen – für 3000 $.}
{166}{}{Wie viel?! Hältst du mich für verrückt?! Geh wenigstens auf 1000 $ runter! Sonst gehe ich, und du bekommst keinen Cent.}
{167}{}{Alles hat seinen Preis, das ist nur fair. Hier ist das Geld.}
{168}{}{Wow, so viel Geld habe ich gerade nicht. Vielleicht später.}
{169}{}{Vielleicht hast du recht. Ich gehe auf 1000 $ runter.}
{170}{}{Einverstanden! Hier ist das Geld.}
{171}{}{Dann gehe ich das Geld holen.}
{172}{}{Ich verdiene genug, um ohne deine Wohltätigkeit auszukommen.}
{173}{}{Na gut, na gut! Wie du willst. Hier sind 3000 Kröten.}
{174}{}{Dann gehe ich das Geld auftreiben.}
{175}{}{Du hast es geschafft, die Koordinaten von Area 51 zu bekommen. Jetzt kannst du dorthin reisen.}
{176}{}{Kein Problem. Ich stelle eine Anfrage an das Archiv, und man wird dir die Informationen zukommen lassen.}
{177}{}{Okay, ich gehe dann.}
{178}{}{Erledigt.}
{179}{}{[Du gibst die Koordinaten in dein Pip-Boy ein]}

#Female character
{1120}{}{Tut mir leid, ich habe die Toilette gesucht. Ich schätze, das war die falsche Tür.}
{1121}{}{Ich bin hier, um dir etwas Blut abzuzapfen.}
{1145}{}{Oh, wir haben hier wohl ein hartes Mädchen! Wenn du mit deinen dämlichen Fragen fertig bist, bitte ich dich jetzt, mein Büro zu verlassen.}
{1163}{}{Na schön, Frau Detective! Verdreh mir nicht die Worte im Mund. Ich versuche nicht, einen Unschuldigen hinter Gitter zu bringen. Ich unterstütze die Polizei dabei, Verbrechen aufzuklären, wie es sich gehört. Das ist meine direkte Pflicht als stellvertretender Bürgermeister!}
{1166}{}{Wie viel?! Hältst du mich für verrückt?! Geh wenigstens auf 1000 $ runter! Sonst gehe ich, und du bekommst keinen Cent.}
