{100}{}{Du siehst einen Wasserkrug.}
{101}{}{Du siehst ein Gefäß für die Gefangenen. Es ist mit fauligem Wasser gefuellt. Offenbar behält die Polizei das gute Wasser für sich.}
{102}{}{Bei genauer Betrachtung des Gefäßes wird klar, wie die Polizei die Gefangenen behandelt. Die Wasserqualität spricht für sich.}
{103}{}{Das Wasser ist ziemlich mies. Offenbar trinken nur die, die in der Isolierstation untergebracht sind, davon. Wenn du dieses Wasser vergiftest, könntest du die Gefangenen krank machen.}
{104}{}{Du hast das Wasser für die Gefangenen vergiftet. Das kann schwerwiegende Folgen haben.}
