{100}{}{Du siehst ein Geschäftsbuch.}
{101}{}{Du siehst ein Casino-Geschäftsbuch. Darin sind Schulden und Gewinne der Kunden verzeichnet.}
{102}{}{Diese langweiligen Aufzeichnungen sind für dich bedeutungslos.}
{103}{}{Du nutzt die Gelegenheit und reißt heimlich die Seite heraus, auf der Irvin und Murphy erwähnt werden.}
{104}{}{Dieses Geschäftsbuch enthält bestimmt Informationen über Irvine und Murphy, aber der Kassierer lässt dich nicht offen darin nachsehen.}
