#! В 1.0 не используе'ся
# Э'о рудимен' с'арой версии, когда скрип' описывал 'айник на кар'е Пикника
{100}{}{Du siehst einen Steinhaufen, den ein unbekannter Reisender hastig aufgeschichtet hat.}
{101}{}{Du siehst einen ungewцhnlichen Steinhaufen.}
{102}{}{Hey, ich habe hier ein geheimes Versteck gefunden!}
{103}{}{Was fьr ein unerwarteter Fund!}

#Реплики для образцов крови
{104}{}{Dieser Gegenstand muss bei Mutanten eingesetzt werden.}
{105}{}{Es lebt. Es lдsst dich das nicht tun.}
{106}{}{Dein Blut wird Dr. Willmouth nicht helfen.}
{107}{}{Du hast eine Blutprobe genommen. Bring sie fьr seine Experimente zu Dr. Willmouth.}
{108}{}{Du hast bereits eine Kojotenblutprobe.}
{109}{}{Du hast bereits eine Blutprobe von Wesen genommen, die mit Kojoten verwandt sind.}
{110}{}{Du hast bereits eine Gecko-Blutprobe.}
{111}{}{Du hast bereits eine Pigratten-Blutprobe.}
{112}{}{Erledigt.}
{113}{}{Dieser Gegenstand muss bei einem mutierten Tier eingesetzt werden, nicht bei einer mutierten Pflanze.}
{114}{}{Das Fett dieses Roboters wird Dr. Willmouth kaum helfen.}
{115}{}{Dr. Willmouth hat nach einer anderen Blutart gefragt.}
