{100}{}{Die Händlerin lässt dich nicht in ihren Karren sehen.}
{101}{}{Offensichtlich kannst du diesen Karren ohne mehr Schrott nicht reparieren.}
{102}{}{Du siehst keinen Grund, das zu tun.}
{103}{}{Dieser Karren muss nicht weiter repariert werden.}
{104}{}{Mit deinen Fähigkeiten kannst du hier nur Schaden anrichten.}
{105}{}{Das ist keine gute Lösung.}
{106}{}{Du hast den Karren erfolgreich repariert, indem du einige Teile ersetzt hast.}
{107}{}{Fertig}
