{101}{}{Dieser Spielautomat ist ausgeschaltet. Auf dem Schild steht „Außer Betrieb“.}
{102}{}{Dieser Spielautomat funktioniert wieder und bereitet den Leuten Freude am Glücksspiel.}
{103}{}{Nicht während des Kampfes.}
{104}{}{Außer Betrieb.}
{105}{}{Die Maschine ist funktionsfähig.}
{106}{}{Die Maschine ist funktionsfähig und erfuellt ihre Aufgabe gut.}
{107}{}{Diese Maschine ist kaputt. Wenn du daran herumschrauben willst, musst du um Erlaubnis fragen.}
{108}{}{Das erfordert einen umfassenden Ansatz.}
{109}{}{Erledigt.}
{110}{}{Du hast die Platine repariert, die Datenbank von unnötigen Daten bereinigt und das Programm wiederhergestellt.}
{111}{}{Du kommst der Sache nicht auf die Spur, wenn du versuchst, das Problem herauszufinden.}