{100}{}{Eine seltene Pflanze.}
{101}{}{Du siehst eine ausladende, verwelkte Pflanze. Hier fühlt sie sich offensichtlich nicht wohl und weigert sich, normal zu wachsen.}
{102}{}{Du hast zwischen den Blättern ein paar nahrhafte Nüsse gefunden!}
{103}{}{Du hast zwischen den Blättern dieser Pflanze nichts Nützliches gefunden.}
{104}{}{Da ist etwas Nützliches drin!}
{105}{}{Hier ist nichts Nützliches.}
