{100}{}{Du siehst eine Tafel.}
{101}{}{Es ist nur eine Tafel mit alten Anzeigen und Preisschildern. Du könntest deine eigenen Notizen hinzufügen.}
{102}{}{Du willst während des Kampfes lesen?! Das ist nicht besonders klug, weißt du ...}

#Dialogue branches
{103}{}{Wo möchtest du deinen Truck beim nächsten Mal parken?}
{104}{}{Parke das Auto in der Garage.}
{105}{}{Parke das Auto neben den Karawanenleuten.}
{106}{}{Parke das Auto am Eingang von Clean City.}
{107}{}{Lass es so.}

#Random remark after the change of the parking location
{108}{}{Fertig.}
{109}{}{Erledigt.}
{110}{}{In Ordnung.}
{111}{}{Alles klar.}
{112}{}{Keine Probleme.}
{113}{}{Wie du meinst.}
{114}{}{Wie du willst.}
{115}{}{Keine Frage.}
{116}{}{Mach ich.}
{117}{}{Natürlich, Boss.}
{118}{}{Du weißt es besser, Boss.}
{119}{}{Wie du willst.}

#After the change of the parking spot
{120}{}{Ändere es noch einmal.}
{121}{}{Schon besser.}
{122}{}{Das brauche ich jetzt nicht.}

#Information about the location of the car
{130}{}{Denk daran, wo ich das Auto abgestellt habe.}
{131}{}{.}
{132}{}{Okay, zurück zur Frage nach dem Parkplatz.}
{133}{}{Jetzt erinnere ich mich! Es ist Zeit, das Auto zu holen.}

{1130}{}{Denk daran, wo ich das Auto abgestellt habe.}
{1133}{}{Jetzt erinnere ich mich! Es ist Zeit, das Auto zu holen.}

#The locations where the car could be
{1499}{}{Es ist irgendwo im Ödland.}
#Attention! The list should be copied right from the file .../game/MAP.MSG
{1500}{}{Vault City}
{1501}{}{Kriegswind}
{1502}{}{Die Basis „Sigma“}
{1503}{}{Lovelock}
{1504}{}{Baydie}
{1505}{}{Poseidon Oil NPP}
{1506}{}{Ailie}
{1507}{}{New Reno}
{1508}{}{Area 51}
{1509}{}{Bridgeport}
{1510}{}{Las Vegas}
{1511}{}{Bezirk Provo}
{1512}{}{Militärbasis Hawthorne}
{1513}{}{Wendover}
{1514}{}{Salt Lake City}
{1515}{}{Alter Rabbi}
{1516}{}{Regierungs-Vault}
{1517}{}{Gerlach}
{1518}{}{Uranium City}
{1519}{}{The Pound}
{1520}{}{Battle Mountain}
{1521}{}{Auto ohne Strom}
{1522}{}{Vault City}
{1523}{}{Verkehrsstau}
{1524}{}{Operation „Wind des Krieges“}
{1525}{}{Black Rock}
{1526}{}{Wüste}
{1527}{}{Berg}
{1528}{}{Zerstörte Stadt}
{1529}{}{Küste}
{1530}{}{Tankstelle}
{1531}{}{Kreuzung}
{1532}{}{Großes Loch}
{1533}{}{Reifenhalde}
{1534}{}{Tankwagen in der Wüste}
{1535}{}{Ungewöhnlicher Ort}
{1536}{}{Verlorenes Büro}
{1537}{}{Café „The New Hopes“}
{1538}{}{Riesenei}
{1539}{}{Bobbys Hütte}
{1540}{}{Haus auf Rädern}
{1541}{}{„Furthur“}
{1542}{}{Verlassene Rangerstation}
{1543}{}{Picknickplatz}
{1544}{}{Karawane}
{1545}{}{„Lieber John“}
{1546}{}{Harrelson}
{1547}{}{Zufallsbegegnung}
{1548}{}{Zerbrochene Postkutsche}
