{100}{}{Du siehst einen Wartungscomputer.}
{101}{}{Du siehst den Servicecomputer, auf dem gerade die Passwortabfrage angezeigt wird.}

#Dialogue:
{120}{}{Du siehst Joshuas persönlichen Computer mit Zugriff auf den Wartungsserver.}
{121}{}{Lies die Vorschriften für Bürger.}
{122}{}{Studiere die Einträge über das Ödland rund um den Vault.}
{123}{}{Lies die Anforderung für Diener.}
{124}{}{Recherchiere über das nahegelegene Atomkraftwerk.}
{125}{}{Fälsche eine Anforderung für eine Sicherung aus dem Lager.}
{126}{}{[Gehen]}

{130}{}{Die Vorschriften für Bürger sind lang und langweilig, aber Joshua hat einige Punkte hervorgehoben, die er für wichtig hielt: 1. Bürger müssen direkten Körperkontakt vermeiden. 2. Bürger dürfen die Stadt nicht ohne Genehmigung verlassen. 3. Über die Aktivitäten der Führung darf nur bei Ratssitzungen gesprochen werden. 4. Die Kommunikation zwischen den Abteilungen ist nur per Memorandum gestattet, außer in extremen Umständen. }
{131}{}{Du studierst die Berichte der Patrouillen rund um Vault City. Das wird dir auf deiner Reise helfen.}
{132}{}{Die Überlebenskunde-Fertigkeit steigt um 3%.}
{133}{}{Der Bericht handelt von einem verlassenen Atomkraftwerk nördlich von Vault City. Es gibt nicht viele Informationen, da die hohe Strahlenbelastung der Anlage keine detaillierte Untersuchung zulässt. Du kopierst die Koordinaten der Anlage in deinen Pip-Boy.}
{134}{}{Der Bericht handelt von einem verlassenen Atomkraftwerk nördlich von Vault City. Es gibt nicht viele Informationen, da die hohe Strahlenbelastung der Anlage keine detaillierte Untersuchung zulässt.}

{135}{}{Ein Memorandum von Joshua: „Ich beantrage, fünf (5) Diener der technischen Wartungsabteilung für Außeneinsätze unter Bedingungen zuzuteilen, die für Bürger aufgrund der Strahlung zu gefährlich sind.“}
{136}{}{Lies die Antwort der Sicherheitsabteilung.}
{137}{}{„Um deiner Anfrage nachzukommen, muss die medizinische Abteilung bestätigen, dass die betreffenden Diener für den angegebenen Einsatz geeignet sind.“}
{138}{}{Lies die Antwort der medizinischen Abteilung.}
{139}{}{Die medizinische Abteilung ist nicht verpflichtet, der Wartungsabteilung Rede und Antwort zu stehen. Bitte richten Sie Ihre Anfrage an die Sicherheitsabteilung.}
{140}{}{Lies die Antwort der Sicherheitsabteilung.}
{141}{}{„Um deiner Anfrage nachzukommen, muss die medizinische Abteilung bestätigen, dass die betreffenden Diener für den angegebenen Einsatz geeignet sind.“}
{142}{}{Aha.}

{150}{}{Du brauchst Joshuas persönliche Zugangsdaten, um auf diesen Computer zuzugreifen. Von ihm bekommst du sie natürlich nicht, also musst du das System hacken.}
{151}{}{Versuchen wir's ...}
{152}{}{Du hast den Code geknackt und eine Bestellung ans Lager aufgegeben! Leider hast du damit die zulässige Anzahl an Anforderungen für diese Abteilung überschritten. Das solltest du lieber nicht noch einmal versuchen.}
{153}{}{Großartig!}
{154}{}{Du konntest nicht in das System eindringen. Sieht so aus, als hättest du nicht genug Wissen auf diesem Gebiet.}
{155}{}{}
{156}{}{Deine geistigen Fähigkeiten reichen eindeutig nicht aus, um das Konzept des Hackens zu verstehen.}
