{100}{}{Du siehst: Medizinischer Computer}
{101}{}{Du siehst den Computer der Klinik – nur für medizinisches Personal mit Zugangsberechtigung!}

#Overall
{120}{}{Du siehst den medizinischen Computer. Er enthält klinische Informationen über alle Bürger: Fortpflanzungspläne, geplante Berichte und anderen Kram, der dich nicht wirklich interessiert.}
{121}{}{Lies den medizinischen Bericht über die Diener aus Gerlach.}
{122}{}{Untersuche die Forschung zu Mutationen.}
{123}{}{Sieh die schwarze Liste durch.}
{124}{}{Untersuche die Informationen aus der Primärdatenbank.}
{125}{}{[Gehen]}

#Gerlachtown Servants
{130}{}{Es stellt sich heraus, dass sie in ziemlich bemitleidenswertem Zustand sind.}
{131}{}{Allgemeine Schlussfolgerung.}
{132}{}{Mutagenanalyse.}
{133}{}{Psychologische Analyse.}
{134}{}{Verordnete Behandlungen.}
{135}{}{Empfehlung für alle Bürger.}
{136}{}{Zurück zum Hauptmenü.}

{140}{}{Bei der Ankunft im Vault war der Gesundheitszustand der Bewohner Gerlachs unbefriedigend, was höchstwahrscheinlich an der Umwelt, dem hektischen Lebensstil, dem lebenslangen Mangel an medizinischer Versorgung und der Mangelernährung lag. Die geschätzte Lebenserwartung eines durchschnittlichen Bewohners Gerlachs betrug bestenfalls höchstens 50 Jahre. Die meisten wären an den bei ihnen festgestellten Herz-Kreislauf-Anomalien und bösartigen Tumoren gestorben. Nach der Erstdiagnose wurden die Diener zur Desinfektion isoliert. Alle Diener stehen nun unter der Beobachtung von Dr. Willmouth.}
{141}{}{Die meisten Mutationen sind genetischer Natur. Sie können nicht übertragen werden – außer durch Vererbung – und sind ein ursächlicher Faktor für die beobachteten Tumore. In 94% of der Fälle werden die Mutationen durch Strahlung verursacht, in den übrigen 6% of Fällen durch ein unbekanntes, aber nicht übertragbares Virus.}
{142}{}{Die Diener erleben aufgrund mangelnder Selbstverwirklichung eine Identitätskrise. Jeder von ihnen leidet unter schweren Depressionen. Außerdem sind die Diener psychisch instabil und neigen zu Wutausbrüchen. Es mangelt ihnen eindeutig an Selbstkontrolle und an Hemmungen, ihre Aggressionen auszuleben.}
{143}{}{Empfehlungen: 1. Regelmäßige Untersuchungen mit Schwerpunkt auf der Dynamik von Zellmutationen. 2. Regelmäßige Behandlungen gegen Strahlenbelastung. 3. Chemische Unterdrückung von Emotionen, insbesondere von Eigeninitiative und dem Drang nach Selbstverwirklichung. 4. Strenger Arbeitsplan.}
{144}{}{Empfehlungen: 1. Jeden körperlichen Kontakt mit Dienern vermeiden. Bei Kontakt die betroffene Stelle mit sauberem Wasser abwaschen und sofort den medizinischen Dienst informieren. 2. Gespräche mit Dienern vermeiden, abgesehen von direkten Arbeitsanweisungen. 3. In Gegenwart der Diener keine Gefühle zeigen, insbesondere keine Angst. 4. Alle Versuche der Diener, eigenständig zu handeln, unterbinden und verhindern, dass sie eine eigene Identität ausdrücken.}

#MC's Condition
{160}{}{Sieh dir deine Krankengeschichte an.}
{161}{}{Du verstehst von diesem medizinischen Kauderwelsch kein Wort.}
{162}{}{[Gehen]}
{163}{}{Du findest Dr. Willmouths Bericht über deinen Zustand, als du in die Stadt gebracht wurdest. Bei deiner Ankunft entsprachen deine geistigen Fähigkeiten denen eines zweijährigen Kindes. Du konntest weder essen noch laufen, sprechen oder dich an etwas erinnern. Bei dir wurde eine Hirnschädigung diagnostiziert, verursacht durch einen direkten elektromagnetischen Impuls, der von einem in dein Gehirn implantierten Mikrochip übertragen wurde. Der Chip war während einer Operation entfernt worden. Es war unmöglich, deine Erinnerungen wiederherzustellen, daher führte Dr. Willmouth ein spezielles Verfahren durch, um dein Gehirn mit einer neuen, künstlichen Persönlichkeit zu überschreiben.}
{164}{}{Heilige ...}