{100}{}{Ein Planwagen.}
{101}{}{Der Wagen ist fest verhüllt, sodass niemand sehen kann, was sich darin befindet.}
{102}{}{Hmm ... Bist du sicher, dass du das tun willst?}
{103}{}{Nicht im Kampf!}
{104}{}{In diesem Wagen gibt es nichts zu holen.}

#ïîñëå şçàíüÿ ïîâîçêè
{105}{}{Du siehst einen Planwagen, aber er transportiert nicht das, was viele erwarten würden!}
{106}{}{[Versteck dich im Wagen und warte, bis die Karawanenhändler aufbrechen]}
{107}{}{Jetzt weiß ich, wer Vegas mit Drogen versorgt!}
{108}{}{Lass es bleiben.}

{109}{}{Nur ein Wagen. Was kommt als Nächstes?}
{110}{}{Du hast einen Drogenlieferanten in Vegas entdeckt. Interessant. Würde die Polizei sich dafür interessieren?}

{111}{}{Dieser Wagen ist jetzt nur noch Schrott, denn seine Besitzer sind tot und der Inhalt wurde gestohlen.}
{112}{}{}
{113}{}{Nur nutzloser Schrott.}
{114}{}{Das scheint Schrott zu sein ... Warum transportieren sie ihn?}
{115}{}{Leer.}
{116}{}{Behalte die Wagen vorsichtshalber im Auge ...}