{100}{}{Das ist die Zugangskonsole.}
{101}{}{Du siehst die Zugangskonsole des Aufzugs.}
{102}{}{Zugang gewährt.}
{103}{}{Das Drücken wahlloser Knöpfe hat nichts gebracht. Das System ist ziemlich kompliziert.}
{104}{}{Hier ist wissenschaftliches Vorgehen gefragt.}
{105}{}{Mechanische Dietriche helfen bei elektronischen Geräten nicht weiter.}
{106}{}{Das System erkennt deinen Ausweis und entriegelt den Aufzug.}
{107}{}{Geschickt umgehst du die Logikschaltkreise, indem du ein alternatives Benutzerkonto anlegst. Das System entriegelt den Aufzug.}
{108}{}{Du versuchst, das System zu umgehen, scheiterst aber.}
{109}{}{Dieses System ist zu kompliziert für dich.}