{100}{}{Du siehst ein Archivterminal.}
{101}{}{Du siehst das Terminal mit dem Archiv des Rathauses. Um es zu benutzen, brauchst du Zugriffsrechte.}
{102}{}{Nur die Archivmitarbeiter haben Zugriff auf dieses Terminal.}

{103}{}{Dieses Terminal speichert einen Teil des Rathausarchivs in digitaler Form.}
{104}{}{[Koordinaten von Area 51 suchen]}
{105}{}{[Beenden]}

{106}{}{Du hast die Koordinaten erhalten. Du kannst jetzt nach Area 51 reisen.}
{107}{}{[Suche abgeschlossen]}
