{100}{}{Du siehst ein Terminal.} 
{101}{}{Du siehst ein Terminal für die Notfallhilfe für Mitarbeiter des Rathauses.}
{102}{}{Nicht während des Kampfes.}
{103}{}{Deine Kenntnisse über Computersysteme reichen nicht aus, um dieses Terminal zu knacken.}
{104}{}{Um dieses Terminal zu benutzen, sind wissenschaftliche Methoden erforderlich.}
{105}{}{Dafür ist Wissenschaft erforderlich.}
{106}{}{Dieses Terminal funktioniert nicht mehr.}
{107}{}{Nicht funktionsfähig.}
{108}{}{Du konntest das System umgehen. Das Notfallterminal gab dir ein stimpak und versuchte dann, neu zu starten – und schaltete sich ab.}
{109}{}{Ja!}
