{100}{}{Du siehst einen Tisch mit Teilen.}
{101}{}{Auf diesem Tisch liegt jede Menge Schrott herum.}
{102}{}{Diese Werkbank ist jetzt nutzlos.}
{103}{}{Während des Kampfes kannst du diesen Tisch nicht untersuchen.}

{110}{}{Jemand hat diesen Tisch zu einer Werkbank für Waffen umfunktioniert. Du siehst eine seltsam aussehende Waffe und einige Notizen, die eindeutig nicht ausreichen, um sie zu reparieren.}
{111}{}{[Näher ansehen]}
{112}{}{[Gehen]}

{113}{}{Diese Pistole ist sehr ungewöhnlich. Und eindeutig eine Energiewaffe. Die kaum sichtbare Gravur an der Seite lautet: „Eigentum von Area 51.“}
{114}{}{[Weiter]}
{115}{}{Die Waffe feuert nicht, obwohl sie geladen ist. Offenbar kann sich nur jemand mit viel Erfahrung in der Reparatur von Energiewaffen darum kümmern.}
{116}{}{[Blaster nehmen]}

{117}{}{Du nimmst die Waffe mit all ihren Teilen mit, einschließlich der geladenen Energiezellen.}
{118}{}{Der Besitzer wird nicht erfreut sein, aber ich brauche sie dringender!}
