{110}{}{„Unser Verkaufsautomat bietet Ihnen gern eine große Auswahl an spannenden und informativen Publikationen!“}
{111}{}{[Publikation auswählen]}
{112}{}{[Verkaufsautomat in Ruhe lassen]}
{113}{}{Tut mir leid, derzeit ist kein Artikel im Automaten.}
{114}{}{„Um etwas zu kaufen, drücken Sie die Taste mit der Nummer der gewünschten Publikation und werfen Sie den erforderlichen Geldbetrag in den Geldschlitz.“ (Jeder Artikel kostet 500 $)}
{115}{}{„Vielen Dank für Ihren Einkauf! Wir wünschen Ihnen eine angenehme Lektüre.“}
{116}{}{[Zurück zur Auswahl der Publikationen]}
{117}{}{[Leeres Fach]}
{118}{}{.}
{119}{}{„Bitte werfen Sie den erforderlichen Geldbetrag in den Geldschlitz.“}
{120}{}{So viel Geld habe ich natürlich nicht.}
{121}{}{[Bezahlen]}
{122}{}{> Nächste Liste}
{123}{}{< Vorherige Liste}