{100}{}{Nach einigen Tagen Ruhe wirst du aus dem Vault entlassen. Dein Geist fühlt sich klar und gesund an, aber du kannst dich an nichts erinnern.} 
{101}{}{Wieder zu Hause ... Aber man lässt dich nicht hinein.}

#Äëÿ ôèíàëüíîé êàğòû
{102}{}{Ist ein Hurrikan durch die Stadt gefegt oder war das einfach ein Massaker?!}
{103}{}{Sieht aus, als hätte ich etwas verpasst.}
{104}{}{Der Aufzug ist außer Betrieb.}
{105}{}{Durch diese freiliegenden Kabel fließt Strom.}

{106}{}{Deine Mission ist abgeschlossen.}

#Æåíñêèå ğåïëèêè:
{1103}{}{Sieht aus, als hätte ich etwas verpasst.}
