{100}{}{Karawanenfahrer Bibbit.}
{101}{}{Du siehst einen Karawanenfahrer, einen von vielen.}

{105}{}{Vielen, vielen Dank!}

#Ïëàâàşùèå ğåïëèêè:
{110}{}{Ich hab's total verbockt!}
{111}{}{Wie konnte ich mich nur darauf einlassen!}
{112}{}{18 Karat Pechsträhne ...}
{113}{}{Wann hört dieses ganze Pech endlich auf?!}
{114}{}{Lebt wohl, meine Freunde ...}
{115}{}{::seufzt schwer::}
{116}{}{Ich bin nicht mal mehr Karawanenfahrer!}
{117}{}{Vielleicht lebt noch jemand? Aber ...}
{118}{}{In den nächsten zwei Tagen begrüßt ein neues Gesicht die Armen ...}
{119}{}{Hey! Hilf mir, New Vegas zu erreichen! Bitte!}
{120}{}{Wenn du deine Waren verlierst, würdigen dich die anderen Karawanenfahrer keines Blickes!}
{121}{}{Aber was, wenn meine Kumpel tatsächlich Vegas erreicht haben?}
{122}{}{Verdammt, ich bin der größte Pechvogel unter allen Karawanenfahrern!}
{123}{}{So etwas ist uns noch nie passiert!}
{124}{}{Wir waren in Vegas ganz oben ...}
{125}{}{Verdammte Raider haben das Wertvollste mitgenommen.}
{126}{}{Ich bin am Ende. Das war's. Legt mich in den Sarg.}
{127}{}{Und dabei hatte alles so gut angefangen!}
{128}{}{Wir haben irgendetwas nach Salt Lake transportiert ...}
{129}{}{Warum will mich niemand nach Vegas mitnehmen? Ich bin ein erfahrener Karawanenhändler!}

#Íà÷àëüíûé äèàëîã:

{200}{}{[Du siehst einen besorgten Karawanenhändler] Äh ... Hallo, Wanderer! Ich nehme an, du bist aus einem bestimmten Grund zu mir gekommen, aber glaub mir, ich habe gerade keine Lust, irgendwem zu helfen.}
{201}{}{Was meinst du?}
{202}{}{Sieht so aus, als wärst du derjenige, der Hilfe braucht.}
{203}{}{Ich wollte nur ein paar Fragen stellen.}
{204}{}{Verstehe. Ich lasse dich in Ruhe.}

{205}{}{Ich muss mich beeilen, um nach Vegas zu kommen und meine Kameraden zu treffen.}
{206}{}{Tschüss.}

{210}{}{Fragen? Na gut, dann.}
{211}{}{Wer bist du?}
{212}{}{Was machst du hier?}
{213}{}{Erzähl mir deine Geschichte.}
{214}{}{Wenn ich's mir recht überlege, brauche ich doch nichts.}

{215}{}{Ich heiße Bibbit. Ich bin Karawanenhändler. Was gibt's sonst zu sagen? Ein cooler Typ und so, aber darum geht's nicht.}
{216}{}{Ich lecke meine Wunden nach einem harten Karawanenritt. Das Ödland hat sich diesmal als gnadenlose Schlampe erwiesen. Wenn ich nicht so gut im Überleben wäre, hätten mich schon Schweineratten oder irgendwas noch Schlimmeres gefressen.}
{217}{}{Ich stecke in großen Schwierigkeiten, das ist meine Geschichte. Wenn du die Einzelheiten hören willst, dauert das eine Weile, denn anders kann ich sie nicht erzählen. Kostet dich nur eine kleine Gebühr ... Hehe. War nur ein Scherz. Aber ich brauche wirklich Geld. Eine Menge.}
{218}{}{Wenn du Geld brauchst, verkauf etwas.}
{219}{}{}

{220}{}{Sieht nach einer ziemlich üblen Lage aus. So was passiert wohl, was?}
{221}{}{Das ist dein Problem. Mich interessiert etwas anderes.}
{222}{}{Kannst du das näher erklären?}
{223}{}{Hilfe? Ich?! Nicht, dass ich ein Weichei oder Hosenscheißer wäre, aber die Lage ist schwierig, verstehst du? Und in diesem Fall ... könnte ich tatsächlich etwas Unterstützung gebrauchen, sozusagen.}
{224}{}{Erzähl mir mehr.}
{225}{}{Du bist nutzlos. Tschüss.}

{226}{}{Was für eine Unterstützung?}
{227}{}{Dann sag mir, welche Hilfe du brauchst.}
{228}{}{200 Mäuse! Mehr ist es nicht!}

{229}{}{Wofür brauchst du Geld?}
{230}{}{Na gut, hier sind deine 200 Mäuse.}
{231}{}{Zweihundert für eine Geschichte? Das ist zu viel!}
{232}{}{Ich wusste es. Schon wieder ein Bettler!}
{233}{}{Nein, besorg dir das Geld selbst. Ich gehe.}

{234}{}{Glaubst du, mir macht das Spaß?! Jeden Cent in meinem Leben habe ich ehrlich verdient, und jetzt stecke ich in einer verzweifelten Lage, ohne einen klaren Ausweg.}
{235}{}{Wie viel brauchst du?}
{236}{}{Ich muss unbedingt nach Vegas. Aber Karawanenführer helfen nicht umsonst, sie verlangen eine Vorauszahlung. Hier ist jeder auf sich allein gestellt. So läuft das eben.}
{237}{}{Wie viel brauchst du?}
{238}{}{Du bist doch Karawanenführer, oder? Was hält dich also davon ab, Vegas zu erreichen?}
{239}{}{Allein?! Oh nein, so dumm bin ich nicht. Meine Leute sind verschollen, und andere Karawanen weigern sich, mich ohne Vorauszahlung mitzunehmen, weil ich für alle anderen ein Fremder bin.}

{240}{}{Schade, das Einzige, was ich anbieten könnte, ist dieser Comic.}
{241}{}{Genau das brauche ich. Hier sind deine 200 Mäuse für den Comic.}
{242}{}{Nein, den brauche ich nicht.}
{243}{}{Ich geh lieber, bevor du mir noch deine Hose verkaufen willst.}

{244}{}{Na gut, das ist fair. Aber jetzt kann ich mir den Geleitschutz leisten - darauf kommt es wirklich an. Danke, Wanderer.}
{245}{}{Erzählst du mir jetzt, was mit deiner Karawane passiert ist?}
{246}{}{Gern geschehen. Gute Reise.}

{247}{}{Im Ernst?! Du gibst mir einfach zweihundert?! Du bist der netteste Kerl, dem ich je im Ödland begegnet bin! Kein Scherz!}
{248}{}{Warum nicht! Aber es ist eine lange Geschichte.}
{249}{}{Erzähl weiter.}
{250}{}{Dann erzähl sie mir ein andermal.}

#Èñòîğèÿ êàğàâàíà
{300}{}{Also, wir transportierten Waren von Reno nach Vegas. Und wie immer machten wir Halt bei Wind of War, um unsere Wasservorräte aufzufuellen und etwas zu schlafen.}
{301}{}{Was, zu viel Angst, um im Ödland zu schlafen?}
{302}{}{Verstehe. Das ist klug.}
{303}{}{Erzähl es mir ein andermal. Ich habe das Gefühl, dass es sehr lange dauern wird.}

{304}{}{Sind wir nicht, aber warum sollten wir uns den Mutanten einfach so ausliefern?}
{305}{}{Na gut, ziemlich vernünftig. Was kommt als Nächstes?}
{306}{}{Gute Ausrede. Was kommt als Nächstes?}

{307}{}{Wir haben hier am Bahnhof übernachtet. Morgens waren wir bereit aufzubrechen. Aber plötzlich kommt ein Soldat auf uns zu und fragt uns, wohin wir wollen und was wir transportieren. Und bei diesem Militär sollte man besser den Mund halten.}
{308}{}{Warum sind diese Soldaten so unverschämt?}
{309}{}{Führt diese Geschichte irgendwohin oder nicht?}
{310}{}{Kommt mir bekannt vor. Ach, diese bis auf die Knochen militanten Typen ...}

{311}{}{Frag sie. Wahrscheinlich denken sie, dass sie hier das Sagen haben und alles bestimmen. Hast du den Typen mit dem zerschundenen Gesicht im Nebenraum gesehen? So ist die Sache.}
{312}{}{Natürlich, ich hab dir doch gesagt, dass es eine lange Geschichte wird!}
{313}{}{Ach, diese Soldaten ... Aber kommen wir zurück zu deinem Treck.}

{314}{}{Genau. Also, der Typ kommt auf uns zu, geht uns mit seinen Fragen auf die Nerven, tut ganz wichtig, puh ... Und betrunken war er auch noch. Wir konnten ihn nur mit Mühe abwimmeln. Gut, dass wir uns nicht geprügelt haben.}
{315}{}{Und?}
{316}{}{Es hätte gleich dort noch schlimmer kommen können. Du hattest Glück.}
{317}{}{Warte kurz, ich versuche, mich an die Reihenfolge der Ereignisse zu erinnern ...}
{318}{}{Klar.}

{319}{}{Dann zogen wir weiter nach Vegas und nahmen die Route entlang der Straße. Aber dann sagte unser Anführer, dass die Raider dort gewöhnlich Hinterhalte legen. Fahren wir durch die Wüste, sagte er, querfeldein.}
{320}{}{Ja, ja, solche Anführer kenne ich. Kaum gibt es Anzeichen für Gefahr, und schon ...}
{321}{}{Hmm. Sicherer, aber langsamer.}
{322}{}{Hey, fang jetzt nicht damit an! Wenn du ein paarmal in solche Schwierigkeiten gerätst, wirst du auch vorsichtig.}
{323}{}{Na gut, na gut, erzähl weiter.}

{324}{}{Wir sagten ihm, dass ein Tag verloren ginge, wenn wir die Route änderten. Also kamen wir abends, gegen Einbruch der Dunkelheit, an der Tankstelle an.}
{325}{}{Du redest wirklich gern mit dir selbst, was?}
{326}{}{Tankstelle?}
{327}{}{Erzähl weiter.}

{328}{}{Eine alte Tankstelle. Auf dem Weg vom Wind des Krieges nach Vegas machen wir dort immer Halt. Ein praktischer Zwischenstopp. Unter einem Dach schläft es sich immer besser als in einem Zelt mitten in der Wüste.}
{329}{}{Bei deiner Geschichte schlafe ich gleich ein ... Äh ... Erzähl weiter!}
{330}{}{Natürlich.}

{331}{}{Also, wir legten uns schlafen ... Als ich plötzlich höre: Da kommt jemand!}
{332}{}{Endlich wird deine Geschichte interessant!}
{333}{}{Und? Wer war das?}

{334}{}{Während die anderen schliefen, stand ich auf und ging nach draußen. Und plötzlich traf mich etwas direkt ins Gesicht – BA-AAM!!! Das Schienbein eines verdammten Stiefels! Und ich landete auf dem Boden! Alle Männer sprangen auf und griffen zu ihren Waffen. Na ja, dachte ich, jetzt geht der Spaß erst richtig los.}
{335}{}{Eine Schießerei?}

{336}{}{Diese Mistkerle hatten uns von allen Seiten umzingelt. Zwei von uns wurden sofort erschossen, die anderen liefen weg. Gut, dass ich es in den Bu... Äh ... Wie gesagt, ich kenne jede Menge Tricks, also machte ich mich genau im richtigen Moment aus dem Staub.}
{337}{}{Was ist dann passiert?}

{338}{}{Keine Ahnung! Dunkelheit, Schüsse, Getümmel. Als ich abhaute, waren die Raider an der Tankstelle noch damit beschäftigt, jemanden ordentlich zu vermöbeln.}
{339}{}{Und das war schon die ganze Geschichte?}
{340}{}{Das war's?}

{341}{}{Danach habe ich es zurück hierher geschafft. [Leise] Aber ich glaube kein bisschen, dass das Raider waren. So reden die doch nicht! Und so gut organisiert und schlau sind die auch nicht. Das ist alles höchst seltsam!}
{342}{}{Also ist das passiert ...}
{343}{}{Am Ende stand ich mit leeren Händen da und hatte den Kontakt zu meinen Leuten verloren. Hoffentlich gibt mir die Reise nach Vegas eine zweite Chance.}
{344}{}{Ganz schön eine Geschichte. Na dann, gute Reise.}
{345}{}{Tja, so was passiert. Na ja, jetzt bist du auf dich allein gestellt.}

{346}{}{Danke, dass du mir zugehört hast! Wenn du mich mal brauchst, findest du mich in Vegas.}
{347}{}{Ja. Leb wohl.}
{348}{}{Übrigens, was war das für eine Karawane, für die du gearbeitet hast?}

{349}{}{Hallo, Wanderer!}

#Îïğåäåëåíèå êàğàâàíà
{350}{}{Du meintest, du bist Karawanenführer ...}
{351}{}{Ja, genau ... Ich meine, ich war einer. Jetzt bin ich mir nicht mehr sicher. Unsere Leute sind weggelaufen, und ich weiß nicht, ob sie noch leben.}
{352}{}{Und wie hieß diese Karawane?}
{353}{}{Na gut, tschüss.}

{354}{}{"Speed Hawk". Ein ziemlich kleines Team.}
{355}{}{Ich kenne sie. Vier deiner Freunde sind vor Kurzem in Vegas gelandet.}
{356}{}{Oh, du weißt es also nicht ... Freund, sei stark: Alle deine Kameraden wurden getötet. Alle.}
{357}{}{Kommt mir bekannt vor. Ich komme wieder, wenn mir etwas dazu einfällt.}

{358}{}{Du hast das letzte verbliebene Mitglied von "Speed Hawk" gefunden.}
{359}{}{Großartige Neuigkeiten! Ich werde mich so schnell wie möglich zu ihnen aufmachen! Danke, Wanderer, ich bin so froh, dass ich dich getroffen habe!}
{360}{}{Willst du noch etwas hinzufügen?}
{361}{}{Auf Wiedersehen.}

{362}{}{Bist du sicher? Woher weißt du das?!}
{363}{}{Ich ... Äh ... Ich war dort. Ich habe gesehen, was davon übrig ist.}
{364}{}{Nun, es kursieren Gerüchte. Ich sehe mich um und komme wieder.}
{365}{}{Ach, komm schon, keine Sorge! Sie leben. Deine Kameraden warten in Vegas auf dich.}
{366}{}{Nun, ich hatte mich auf das Schlimmste eingestellt ... Ich schätze, das Licht von Vegas leuchtet nicht für mich. Die örtlichen Karawanenhändler übernehmen den Auftrag nicht, wenn sie meine Geschichte kennen. Das ist Aberglaube, mein Freund. Na ja, ich mache mich besser nach Reno auf und versuche dort, mein Leben zu verbessern.}
{367}{}{Das musst du selbst entscheiden, ich habe meine Arbeit erledigt.}

#Female character
{1200}{}{[Du siehst einen besorgten Karawanenhändler] Äh ... Hallo, Wanderer! Ich nehme an, du bist aus einem bestimmten Grund zu mir gekommen, aber glaub mir, ich habe gerade keine Lust, irgendwem zu helfen.}
{1232}{}{Ich wusste es. Schon wieder ein Bettler!}
{1236}{}{Ich muss unbedingt nach Vegas. Aber Karawanenführer helfen nicht umsonst, sie verlangen eine Vorauszahlung. Hier ist jeder auf sich allein gestellt. So läuft das eben.}
{1244}{}{Na gut, das ist fair. Aber jetzt kann ich mir den Geleitschutz leisten - darauf kommt es wirklich an. Danke, Wanderer.}
{1247}{}{Im Ernst?! Du gibst mir einfach zweihundert?! Du bist der netteste Kerl, dem ich je im Ödland begegnet bin! Kein Scherz!}
{1311}{}{Frag sie. Wahrscheinlich denken sie, dass sie hier das Sagen haben und alles bestimmen. Hast du den Typen mit dem zerschundenen Gesicht im Nebenraum gesehen? So ist die Sache.}
{1322}{}{Hey, fang jetzt nicht damit an! Wenn du ein paarmal in solche Schwierigkeiten gerätst, wirst du auch vorsichtig.}
{1329}{}{Bei deiner Geschichte schlafe ich gleich ein ... Äh ... Erzähl weiter!}
{1346}{}{Danke, dass du mir zugehört hast! Wenn du mich mal brauchst, findest du mich in Vegas.}
{1359}{}{Großartige Neuigkeiten! Ich werde mich so schnell wie möglich zu ihnen aufmachen! Danke, Wanderer, ich bin so froh, dass ich dich getroffen habe!}
{1362}{}{Bist du sicher? Woher weißt du das?!}
{1363}{}{Ich ... Äh ... Ich war dort. Ich habe gesehen, was davon übrig ist.}
{1366}{}{Nun, ich hatte mich auf das Schlimmste eingestellt ... Ich schätze, das Licht von Vegas leuchtet nicht für mich. Die örtlichen Karawanenhändler übernehmen den Auftrag nicht, wenn sie meine Geschichte kennen. Das ist Aberglaube, mein Freund. Na ja, ich mache mich besser nach Reno auf und versuche dort, mein Leben zu verbessern.}
{1367}{}{Das musst du selbst entscheiden, ich habe meine Arbeit erledigt.}