{100}{}{Karawanenhändler Billy.}
{101}{}{Du siehst einen gelangweilten Karawanenhändler. Er hantiert mit etwas in seinen Händen.}
{102}{}{Hi.}

#Ðàçãîâîð
{110}{}{[Der Karawanenwächter betrachtet neugierig den runden, abgeschliffenen Stein mit dem Emblem darauf]}
{111}{}{Was ist das?}
{112}{}{[Liegen lassen]}

{113}{}{[Zuckt mit den Schultern] Keine Ahnung. Hab ich in den Ruinen gefunden.}
{114}{}{Dann gib ihn einfach mir. Du brauchst ihn sowieso nicht.}
{115}{}{Ach, ich verstehe: ein Schrottsammler, ha-ha. Wie lange willst du damit deinen Lebensunterhalt verdienen?}
{116}{}{Na ja, vergiss es.}

{117}{}{[Hält den Stein instinktiv von dir fern] Ich ... Und warum willst du ihn?}
{118}{}{Weiß ich auch nicht. Aber mir wird schon etwas einfallen, keine Sorge.}
{119}{}{[Hält den Stein instinktiv von dir fern und spricht deutlich] Ich bin Karawanenwache.}
{120}{}{Ooh, seht euch an, wie stolz wir sind. Kann nicht mal ein Stück Stein hergeben.}
{121}{}{Entschuldige, dass ich deinen Stolz verletzt habe. Gibst du mir nun diesen nutzlosen Stein?}

{122}{}{Na gut. Besieg mich beim Kartenspiel, dann gehört der Stein dir.}
{123}{}{Hängst du nicht ein bisschen zu sehr an deinem Schrott? Du sahst aus wie ein ganz normaler Kerl ...}
{124}{}{Ich kann ihn dir einfach abkaufen. Reichen 50 Mäuse?}
{125}{}{Na gut, spielen wir.}
{126}{}{Vielleicht ein andermal. Jetzt muss ich los.}
{127}{}{Ich würde ihn hergeben, aber nicht an jemanden wie dich.}
{128}{}{Na ja, tut mir leid. Ich bin gerade nicht in der richtigen Stimmung. Normalerweise verstehe ich mich gut mit Karawanenleuten.}
{129}{}{Ach ja, du bist es ... Andere Karawanenleute haben mir von dir erzählt. Sie sagen, du hättest jemandem von uns geholfen. Na gut. Hier ist der Stein, nimm ihn. Ich brauche ihn sowieso nicht.}
{130}{}{Danke, Freund.}
{131}{}{Schon besser. Noch besser wäre es, wenn du dir weitere Worte sparen würdest.}
{132}{}{[Hebt skeptisch die Augenbraue] Sieht nicht danach aus.}
{133}{}{Na gut, vergiss es. Gibst du mir den Stein nun oder nicht?}

{134}{}{Im Ernst? Wie überraschend ... Na gut, machen wir es so.}
{135}{}{Hier ist das Geld. Jetzt gib mir den Stein.}
{136}{}{Für diesen Muell Geld bezahlen?! Nee, ich hatte wohl einen Blackout ... Wir reden später, wenn ich wieder ganz bei Sinnen bin.}
{137}{}{Und du hast das wirklich geglaubt? Was für ein Idiot würde dieses wertlose Stück Schrott kaufen? Denk darüber nach und gib ihn friedlich her.}
{138}{}{[Umklammert den Stein mit der Faust] Vergiss es. Und warum bist du plötzlich so versessen auf diesen Stein? Das gefällt mir nicht.}
{139}{}{Na gut, du hast mich überzeugt. Hier sind deine 50 Kröten für den Stein.}
{140}{}{Na gut, na gut, meinetwegen. Ich spiele mit dir Karten um diesen Schrott.}
{141}{}{Na dann, sieh zu und staune, wie dir eine hübsche Summe Geld durch die Lappen geht, Verlierer. [geht weg]}
{142}{}{Eigentlich habe ich wegen des Geldes gelogen. Vielleicht spielen wir Karten?}

{143}{}{[Zieht Karten aus der Tasche, denkt kurz nach, während er dich finster ansieht, und legt dann doch ein Kartenspiel auf den Tisch] Wir spielen fair. Wenn ich herausfinde, dass du schummelst – dein Pech.}
{144}{}{Okay. Dann los ...}
{145}{}{Hey, warum kaufe ich dir den Stein nicht einfach für 50 Kröten ab?}
{146}{}{Nicht so schnell. Setz erst mal 5 Kröten, sonst spiele ich nicht.}
{147}{}{Na gut, na gut. Ich gewinne sowieso.}
{148}{}{Weißt du, ich würde jederzeit sofort eine Runde Karten spielen, aber ich muss erst noch ein paar Dinge erledigen. Wir spielen später.}
{149}{}{Dich zu besiegen ist kinderleicht. Willst du es noch mal versuchen?}
{150}{}{Ja, ich werde bekommen, was ich will! Noch eine Runde ...}
{151}{}{Puh ... Das war ein gutes Spiel. Ich bin sogar ein bisschen erschöpft, vom Stress. Hier ist dein verdienter Gewinn.}
{152}{}{Pass auf dich auf.}
{153}{}{Nein, ich habe für heute genug von diesen Karten.}

{154}{}{Nimm es. Ich brauche es ohnehin nicht.}
{155}{}{Tschüss.}

{156}{}{Ich sehe, du hast ein ungesundes Verlangen danach, Dinge zu horten. Ich sollte lieber gehen, falls du plötzlich aggressiv wirst.}
{157}{}{Dann brauche ich es nicht. Viel Glück.}
{158}{}{Wie du meinst. Wachmann. Belassen wir es dabei und gehen getrennte Wege.}
{159}{}{Ich frage dich nicht, wie es aussieht. Aber von dir kann man wohl nichts anderes erwarten. Tschüss.}
{160}{}{Denk, was du willst. Ist mir egal. Tschüss.}
{161}{}{Mir auch. Beenden wir also einfach dieses sinnlose Gespräch.}
{162}{}{[Errötet vor Wut] ICH BIN - EIN KARAWANENWÄCHTER!!! Ich bin kein Landstreicher! Und auch kein Schrottsammler! Du willst diesen Stein, ja? Willst du ihn?! Dann NIMM IHN! [wirft ihn ans andere Ende des Raums]}
{163}{}{Hey, ganz ruhig! Oh Mann ... Jetzt muss ich überall danach suchen ...}