{100}{}{Du siehst den Karawanenreisenden Bobby.}
{101}{}{Du siehst einen übel zugerichteten Karawanenhändler.}

#Ñëó÷àéíûå ôğàçû:
{110}{}{::stöhnt::}
{111}{}{Oh, meine Zähne tun weh ...}
{112}{}{Zeit, diesen Job an den Nagel zu hängen.}
{113}{}{Das ist das erste Mal in meiner Laufbahn!}
{114}{}{Sie sollten alle vor ein Kriegsgericht gestellt werden!}
{115}{}{Wie kann man so etwas tun!}
{116}{}{Verdammt, ich fühle mich beschissen ...}
{117}{}{Einfach so, vor allen Leuten!}
{118}{}{Bastarde! Bastarde!}
{119}{}{Sie sind schlimmer als Räuber!}
{120}{}{Selbst die Schläger aus Reno sind nicht so brutal!}
{121}{}{Wie bin ich nur in so eine Lage geraten?}
{122}{}{Sobald ich wieder auf den Beinen bin, gehe ich direkt nach Vegas. Sofort!}
{123}{}{Ich habe gerade erst angefangen zu reden - und schon einen Schlag mitten ins Gesicht bekommen!}
{124}{}{Warum ich?!}
{125}{}{Diese Siedlung werde ich von jetzt an meiden.}

#Íà÷àëî äèàëîãà
{200}{}{[Du siehst einen verprügelten Mann. Er ist verletzt und stöhnt, aber aus irgendeinem Grund hilft ihm niemand.]}
{201}{}{Nicht bewegen, ich verarzte dich. Ich bin Arzt.}
{202}{}{Warte, ich rufe den Arzt, damit er dir hilft.}
{203}{}{Na ja, damit habe ich nichts zu tun, und es ist mir egal.}

{204}{}{[Zieht deine Hand weg] Was bist du denn für ein Arzt?! Lass gut sein, du machst alles nur noch schlimmer.}
{205}{}{Dann musst du eben weiterleiden.}
{206}{}{[Zieht wütend deine Hand weg] Ich nehme keine Almosen von Militärlieblingen an. Lass mich in Ruhe!}
{207}{}{Wenn du meinst ...}

{208}{}{Danke für deine Hilfe.}
{209}{}{Vielleicht sehen wir uns in Vegas.}

#Ïîñëå îêàçàíèÿ ìåäïîìîùè
{210}{}{Oh ... Das ist schon viel besser. Danke für die Hilfe.}
{211}{}{Sag mir jetzt, wer dich so zugerichtet hat.}

{212}{}{Ein paar Soldaten aus der Garnison! Wer sonst?}
{213}{}{Ich wette, du hast sie provoziert. Stimmt's?}
{214}{}{Im Ernst? Wie konnten sie nur! Sie hatten doch keinen Grund dazu, oder?}
{215}{}{Ziemlich seltsames Verhalten für eine paramilitärische Siedlung. Sollten sie hier nicht die Karawanenhändler beschützen?}

{216}{}{Bist du verrückt?! Warum sollte ich das tun?! Egal, was du machst, du kriegst ohne jeden Grund trotzdem einen Stiefel ins Gesicht.}
{217}{}{Du bist ein guter Mensch, aber du verstehst es trotzdem nicht. Sie brauchen keinen *Grund*. Wenn nötig, denken sie sich schon was aus.}
{218}{}{Ja, viele glauben immer noch an dieses weitverbreitete Missverständnis. Aber in Wahrheit sind sie nicht mehr daran interessiert, für deine Sicherheit zu sorgen. Gib ihnen nur einen Grund, und sie rauben dich bis aufs Hemd aus.}
{219}{}{Warum sind die Einheimischen so aggressiv?}
{220}{}{Weil sie es können. Sie glauben, sie seien besser als alle anderen. Wer bessere Waffen und dickere Rüstung hat, ist der Held des Ödlands, kapiert? Deshalb benehmen sie sich, als gehöre ihnen diese Gegend.}
{221}{}{Warum haben sie dir das also angetan?}

{222}{}{Wegen meiner Waffe und etwas Geld. Ich hätte sie nicht zeigen sollen. Jemand hat dem Militär davon erzählt, und schon bald tauchten dieser Jimmy und seine Bande auf. Sie verlangten, dass ich ihnen meine Waffe überlasse. Ich weigerte mich, und das ist das Ergebnis.}
{223}{}{Erzähl mir von deiner Waffe.}
{224}{}{Wer ist dieser Jimmy, und wo finde ich ihn?}
{225}{}{Ist es hier in der Gegend verboten, eine Waffe zu tragen?}
{226}{}{Jetzt verstehe ich. Na gut, tschüss.}
{227}{}{Eine "Desert Eagle" mit Ledergriff und verbessertem Lauf. Eine mutierte Ameise kippt nach einem einzigen Schuss tot um. Eine großartige Waffe.}
{228}{}{Einer der Gefreiten. Er lungert ständig am Kontrollpunkt herum. Ein junger, frecher Mistkerl.}
{229}{}{Nein! Nicht ganz. Verboten ist es nur innerhalb ihrer Garnison. Dafür würden sie dich abknallen. Und hier ist freies Gelände, solche Regeln gelten hier nicht. Aber kümmert das Jimmy?}

#Çàâåğøåíèå êâåñòà
{230}{}{Hey, danke für deine Hilfe. Bald verlasse ich diesen Ort und versuche, nicht wieder zurückzukommen.}
{231}{}{Hey, danke für deine Hilfe. Bald verlasse ich diesen Ort und versuche, nicht wieder zurückzukommen. Aber meine Waffe fehlt mir. Es ist nicht gerade vernünftig, ohne Waffe durchs Ödland zu ziehen.}
{232}{}{Schon gut. Tschüss.}

{233}{}{Dieser Jimmy hat bekommen, was er verdient hat, und will sich jetzt entschuldigen.}
{234}{}{Dieser Jimmy hat bekommen, was er verdient hat. Wir hatten eine ... klärende Unterhaltung.}
{235}{}{Sag mir noch mal, warum sie dich verprügelt haben.}

{236}{}{Echt jetzt? Du bist echt hart im Nehmen! Wer sonst würde es wagen, einen Soldaten an die Wand zu nageln ... Ach, übrigens, hast du meine Sachen zurückbekommen?}

{237}{}{Hier sind deine 200 Mäuse und eine Pistole.}
{238}{}{Hier sind deine 200 Mäuse, aber die Pistole hat er nicht rausgerückt.}
{239}{}{Hier ist deine Pistole, aber Geld war nicht Teil der Abmachung.}
{240}{}{Schade, jetzt ist es zu spät – ich konnte nichts zurückholen.}

{241}{}{Meine "Desert Eagle"?! Danke! Ich bin so froh, dass ich dich getroffen habe! Übrigens, behalt das Geld. Sieh es als Dank für deine Hilfe an.}
{242}{}{Danke. Mach's gut.}
{243}{}{Ich wusste es! Sie haben es *schon* geschafft, das ganze Geld auszugeben. Obwohl ich auch nicht viel Bargeld hatte. Beim nächsten Auftrag verdiene ich doppelt so viel. Viel wichtiger: Meine geliebte "Desert Eagle" ist wieder bei mir! Du hast mich gerade vor einer Depression bewahrt! Danke.}
{244}{}{Ja. Mach's gut.}
{245}{}{Nun, ich muss mich wohl von meiner "Desert Eagle" verabschieden ... Das ist ziemlich deprimierend. Weißt du, was auch immer dort passiert ist, ich schätze, sie haben bekommen, was sie verdient haben. Hier, nimm die Hälfte. [gibt 100 Mäuse] Du hast sie dir verdient. Danke für alles! Vielleicht sehen wir uns in Vegas.}
{246}{}{Vielleicht. Leb wohl.}
{247}{}{Oh, Pech gehabt. Wenigstens kann ich in Frieden ruhen, weil sie bekommen haben, was sie verdient haben. Danke für alles! Andere wären einfach weitergegangen. Vielleicht sehen wir uns in Vegas.}
{248}{}{Gern geschehen.}