{100}{}{Karawanenhändler Biggie.}
{101}{}{Du siehst einen finster dreinblickenden Karawanenhändler.}
{102}{}{Ich habe am Zaun auf dich gewartet, aber du bist nie gekommen. Nach so einem "Streich" will ich nicht mit dir reden.}
{103}{}{Hi.}

#About Hawk
{120}{}{Ja, hier ist einer. Aber ich glaube nicht, dass er dir weiterhelfen kann. Das Tragische an seiner Geschichte ist, dass seine Karawane von Räubern überfallen wurde. Er hat als Einziger überlebt.}
{121}{}{Ich muss trotzdem mit ihm reden. Sag mir, wo ich ihn finden kann.}
{122}{}{Weißt du etwas über diesen Angriff?}
{123}{}{Ich weiß nicht genau, wo er jetzt ist, aber bestimmt irgendwo in der Nähe des Bahnhofs. Frag einfach herum.}
{124}{}{Das ist alles, was ich von dem Überlebenden gehört habe. Die Raider griffen nachts an und erschossen alle. Er konnte entkommen. Was für Raider es waren, konnte er nicht sagen. Das ist alles.}
{125}{}{}
{126}{}{Verstehe. Keine weiteren Fragen.}
{127}{}{Hast du jemanden von der Karawane „Speed Hawk“ getroffen?}

#Main replics
{250}{}{Na toll, noch ein Wanderer. Was willst du von einem einfachen Arbeiter?}
{251}{}{Kannst du mir etwas über diese Siedlung erzählen?}
{252}{}{Du hast gesagt, du wolltest dich an dem Techniker für den kaputten Wagen rächen.}
{253}{}{Nichts. Du musst nicht gleich so aggressiv sein.}
{254}{}{Nichts.}

#About the Wind of War
{255}{}{Ein beschissener Ort. Wir haben hier nur angehalten, um Wasser zu holen. Wenn die anderen Karawanenleute nicht dabei wären, wäre ich niemals hier.}
{256}{}{Warum?}
{257}{}{Das örtliche Militär ist berüchtigt dafür, aus Mistkerlen zu bestehen. In der eigenen Gemeinschaft gibt es Probleme. Sie tun zwar so, als würden sie die Leute beschützen und so, aber manche von ihnen können dich in die Ecke drängen und völlig ausrauben. Und du kannst nichts beweisen. Deshalb bleiben die Karawanenleute hier immer zusammen, sogar wenn sie aufs Klo gehen.}
{258}{}{So schlimm ist es? Na gut, das merke ich mir.}
{259}{}{Und du solltest mir nicht sagen, was ich tun soll!... Na gut, tut mir leid. Nach einer Sache, die vor Kurzem passiert ist, bin ich etwas angespannt.}
{260}{}{Willst du mir davon erzählen?}
{261}{}{Hier gibt es so einen örtlichen Idioten. Alle halten ihn für einen Technikfreak, und man erzählte uns, er würde in seiner Garage irgendein kompliziertes Transportgerät bauen. Also dachten wir, vielleicht versteht er ja was davon. Wir bezahlen ihn also dafür, den Wagen zu reparieren. Und weißt du, was passiert? Er haut mit einem Hammer auf den Wagen, und der fällt auseinander. Dann hebt er einfach die Hände – „nicht mein Problem“, sagt er, „der Wagen war alt, der hätte die Behandlung nicht ausgehalten“. Kannst du dir das vorstellen?}
{262}{}{Aber du musst zugeben – die Ausrüstung ist wirklich alt. Du wusstest, dass es ein Risiko gab.}
{263}{}{Was für ein Mistkerl! Dafür hätte man ihm eine reinhauen sollen.}
{264}{}{Schwer zu sagen, wer recht hat und wer nicht.}
{265}{}{Ach komm! Er hätte den Auftrag ablehnen oder vielleicht sogar reparieren können, was er kaputtgemacht hat. Aber nein – er sagte nur „leck mich“ und drohte uns mit seinen Freunden aus der Garnison. Was für ein Arschloch...}
{266}{}{Das denke ich auch! Aber so ist es nicht. Statt seinen Schaden zu reparieren, sagte er einfach „Leck mich“ und drohte uns mit seinen Freunden aus der Garnison. Was für ein Arschloch ...}
{267}{}{Nun ja. Das sagen alle, bis ihnen so etwas passiert. Aber weißt du, was er getan hat? Statt seinen Schaden zu reparieren, sagte er einfach „Leck mich“ und drohte uns mit seinen Freunden aus der Garnison. Was für ein Arschloch ...}
{268}{}{Was habt ihr getan?}
{269}{}{Wir mussten uns selbst darum kümmern. Wir haben den Wagen so gut wie möglich repariert. Was den Techniker angeht: Es wäre toll, sich irgendwie an ihm zu rächen, als Abschiedsgeschenk sozusagen. Eine Art Sabotage oder so.}
{270}{}{Sabotage ist gefährlich. Aber vielleicht hat er es verdient. Viel Glück.}
{271}{}{Okay, jetzt ist alles klar. Tschüss.}

#Robbery
{275}{}{Solange ich nicht eins aufs Maul bekomme, bin ich dabei. Hast du einen Vorschlag?}
{276}{}{Natürlich. Ich will diesen Hurensohn ausrauben. Hilfst du mir, über den Zaun zu seiner Garage zu klettern?}
{277}{}{Hast du Angst vor ein bisschen Prügelei? Na schön, vergiss es.}

{278}{}{Bist du verrückt? Stehlen ist riskant!}
{279}{}{Wenn du dich rächen willst, ist das deine einzige Chance.}
{280}{}{Vertrau mir, ich weiß, was zu tun ist.}
{281}{}{Dann ist die Sache geplatzt.}
{282}{}{Ja ... Du hast recht. Na gut, ich bin dabei.}
{283}{}{Vielleicht, aber das geht mir zu weit. Bei dem Diebstahl mache ich nicht mit. Zu riskant.}
{284}{}{Ich verstehe deine Zweifel, aber du solltest mir vertrauen. Ich weiß, was zu tun ist.}
{285}{}{Dann verschwenden wir keine Zeit mehr. Wir haben jetzt die perfekte Gelegenheit.}
{286}{}{Warte hier, während ich die Lage erkunde.}
{287}{}{Warum sollte ich irgendeinem Fremden vertrauen? Vergiss es. Wenn ich jemandem vertraue, dann den Karawanenhändlern und denen, die ihnen helfen.}
{288}{}{Willst du dich überhaupt rächen? Oder kannst du nur reden? Denk mal nach – das ist deine einzige Chance.}

{290}{}{Du hast den Karawanenhändler dazu überredet, einen Raub zu begehen. Er wartet bei dem Zaun neben der Garage auf dich.}
{291}{}{Ja, das wäre sehr gut ...}

{292}{}{Hier kommt man am besten über den Zaun. Auf der anderen Seite scheint eine Treppe zu sein, also sollte es einfach sein, zurückzukommen.}
{293}{}{Hilf mir rauf, damit ich zum Zelt zurückkomme. Du hast nichts gesehen und nichts gehört.}
{294}{}{Es ist noch zu früh, um Sabotage zu verüben. Ich sage dir Bescheid, wenn wir anfangen.}
{295}{}{Für deine Taten verlierst du Karma, aber dein Schleichen-Wert steigt um 2%.}
{296}{}{Beruhige dich, keine Panik. Wir gehen nur ein wenig herum ...}

#Women's replics
{1250}{}{Na toll, noch ein Wanderer. Was willst du von einem einfachen Arbeiter?}
{1278}{}{Bist du verrückt? Stehlen ist riskant!}
