{100}{}{Du siehst Freckles.}
{101}{}{Du siehst einen Körper. Du bist dir nicht sicher, ob er tot oder lebendig ist.}
{102}{}{Ich hab's ihnen gesagt! Unzählige Male hab ich's ihnen gesagt! Aber keiner wollte zuhören ...}
{103}{}{Verdammt! Wie konnte das passieren?!}

#Ïëàâàşùèå ôğàçû
{110}{}{Oh! Mein Knie!}
{111}{}{Am Steuer eingeschlafen oder was?! Schreib nicht beim Fahren, verdammt noch mal!}
{112}{}{Hey, du! Du bist schuld, also hilf mir jetzt!}
{113}{}{Was, wenn es ein kleines Kind gewesen wäre und nicht ich?}
{114}{}{Bring mich sofort hier raus!}
{115}{}{Na ja ... Bitte ...}
{116}{}{Willst du einfach nur dastehen und glotzen?!}
{117}{}{Vielleicht könntest du endlich mal was unternehmen?}

#Äèàëîã
{150}{}{Verdammte Touristen! Was ist denn so eilig? Kriegt hier jemand ein Kind oder was?!}
{151}{}{Oh, tut mir leid, Kumpel. Lass mich dir helfen.}
{152}{}{Warum passt DU nicht auf, wo du hinläufst!}

{153}{}{Ach, keine Sorge! Ein paar gute Knochen hab ich noch.}
{154}{}{Gut zu hören.}
{155}{}{Schon vor 50 Jahren hab ich's ihnen gesagt: Stellt Ampeln auf oder malt wenigstens Straßenmarkierungen hin, verdammt noch mal! Aber nein! Niemand wollte auf den alten Freckles hören. Verdammte Bürokraten!}
{156}{}{Äh ...}
{157}{}{Und das ist noch nicht mal das letzte Mal! Wie viele werden diesen schlechten Straßen noch zum Opfer fallen?}
{158}{}{Aber ...}
{159}{}{Mehr braucht's nicht als eine Dose Farbe ... Aber nein! Sie sind zu beschäftigt. So viel zum „Ödland der Hauptstadt“, wie sie sich nennen. Meine Güte!}
{160}{}{Ruhig, alter Mann. Ich glaube nicht, dass das, was du sagst, noch relevant ist.}
{161}{}{Hm? Was? [Schüttelt den Kopf] Du wirst schon sehen. Noch ein halbes Jahrhundert, und du wirst dich an meine Worte erinnern. Ich muss jetzt los. Pass auf dich auf und fahr nicht noch mehr alte Männer um!}
{162}{}{Ja.}

{170}{}{Hey, wo hast du deinen Führerschein her, aus einer Müslipackung ausgeschnitten? Denk daran: Der Fußgänger hat immer Recht. Bringt man Kindern das heutzutage nicht mehr bei? Diese Welt ist völlig im Arsch ...}
{171}{}{Willst du jetzt einfach auf der Straße liegen bleiben?}
{172}{}{Ach, ist schon okay! Ich hab noch ein paar gute Knochen übrig. Danke, dass du mir nicht den Kopf angefahren hast.}
{173}{}{Gern geschehen ...}

#†åí ğåïëèêè
{1170}{}{Hey, wo hast du deinen Führerschein her, aus einer Müslipackung ausgeschnitten? Denk daran: Der Fußgänger hat immer Recht. Bringt man Kindern das heutzutage nicht mehr bei? Diese Welt ist völlig im Arsch ...}
