{100}{}{Du siehst einen einfachen Soldaten.}
{101}{}{Du siehst einen gewöhnlichen Soldaten ... Obwohl er mit so einem Gesicht eher wie ein gewöhnlicher Verbrecher aussieht.}

#Êîãäà âèäèò è áåæèò ê ÷óçó
{102}{}{Da ist er! Keine Bewegung! Ich sagte, sofort stehen bleiben!!!}

#Ïûòàşòñÿ çàïğÿòàòü çà ğåøåòêó
{110}{}{Hey, du! Hände hoch! Du bist verhaftet!}
{111}{}{Hey, ganz ruhig, Mann! Ich hab nichts getan!}
{112}{}{Verdammt!}

{113}{}{Das werden wir ja sehen ...}
{114}{}{[Du wirst in die örtliche Gefängniszelle gebracht und all deiner Besitztümer beraubt.]}
{115}{}{Sieht aus, als wärst du nicht nur verhaftet, sondern auch noch ausgeraubt worden!}

#Female character
{1102}{}{Da ist sie! Keine Bewegung! Ich sagte, sofort stehen bleiben!!!}
{1110}{}{Hey, du! Hände hoch! Du bist verhaftet! }
{1111}{}{Hey, ganz ruhig, Mann! IIch hab nichts getan!}