{100}{}{Du siehst Robert.}
{101}{}{Du siehst einen Bewohner des Windes des Krieges.}
{102}{}{::fasst sich an den Kopf:: Mein Leben ist sinnlos ...}
{103}{}{Bitte enttäuscht uns nicht, es ist unsere einzige Chance.}

#Acquaintance
{110}{}{Danke, Wanderer. Danke für alles!}
{111}{}{Gern geschehen.}

{120}{}{Oh, ich bin überrascht, hier in diesem abgeschotteten Gebiet auf einen Seelenverwandten zu treffen.}
{121}{}{Wovon redest du?}
{122}{}{Hier trifft man nicht viele Leute von außerhalb der Sperrzone. Ich bin einer der wenigen, die ... äh, das Glück hatten, hier leben zu dürfen.}
{123}{}{Verstehe. Kann ich dich etwas über den Wind des Krieges fragen?}
{124}{}{Na dann, freut mich, dich kennenzulernen. Vielleicht schaue ich irgendwann mal vorbei.}

{125}{}{Natürlich! Ich freue mich schon sehr darauf – mit Fremden gibt es immer etwas zu bereden.}
{126}{}{Äh, okay.}

{130}{}{Wollen wir uns hinsetzen und reden?}
{131}{}{Ich würde gern mehr über diesen Ort erfahren. Erzählst du mir etwas darüber?}
{132}{}{Erzähl mir von dir. Du bist wohl nicht von hier, oder?}
{133}{}{}
{134}{}{Danke für die Gastfreundschaft, aber ich muss los.}

{140}{}{Wir befinden uns jetzt in einer abgeschlossenen Siedlung. Hier leben nur das Militär und seine Familien. Draußen findest du nichts als Ruinen. Und dann gibt es noch das Karawanenlager am Bahnhof.}
{141}{}{Warum nennt ihr euch „Militär“?}
{142}{}{Wie ist diese Gemeinschaft entstanden, und wer sind all diese Leute?}
{143}{}{Was machen die Einheimischen so?}

{148}{}{Erzähl mir von dir.}
{149}{}{Ich glaube, das war alles, was ich wissen wollte.}

{150}{}{Unsere Vorfahren, die Gründer der Winds of War, nannten sich so. Sie waren Militärs und dienten den Vereinigten Staaten. Zumindest wurde uns das erzählt. Genau wissen wir es nicht. General Wesker glaubt an die Wiedergeburt des Landes und versucht deshalb, den Geist der Nation am Leben zu erhalten. Manchmal wirkt das sogar lächerlich.}
{151}{}{Der Großteil der Bevölkerung sind direkte Nachkommen der Menschen aus dem örtlichen Vault. Ihre Vorfahren überlebten den Großen Krieg unter der Erde. Als es dort schließlich unmöglich wurde zu leben, gingen sie nach draußen und gründeten auf den Ruinen der alten Stadt Pahrump eine Siedlung. Nach und nach kamen auch Wanderer aus dem Ödland vorbei, doch nur wenige durften sich ihnen anschließen. Als der General die Menschen aus der Außenwelt sah, war er entsetzt ... und ließ das Gebiet einzäunen. Jetzt darf nicht mehr jeder hierher.}
{152}{}{Tatsächlich gibt es drei Arten von Leuten. Erstens das Militär. Es beschützt uns, erkundet die Umgebung und geht auf größere Jagden. Zweitens diejenigen, die im Büro sitzen und Kopfarbeit leisten. Und schließlich die einfachen Leute wie ich, deren Aufgabe es ist, Brei zu kochen, Kleidung zu bügeln und die Unterkünfte instand zu halten.}
{153}{}{Ein Vault? Wo ist der?}
{154}{}{Ich weiß es nicht einmal. Irgendwo in den Bergen im Nordwesten. Frag lieber die Funker im Hauptquartier – die wissen alles über das Umland der Siedlung.}

{160}{}{Ich bin seit drei oder vier Jahren hier. Man hat mich aufgenommen, weil ich gute Arbeit für Wind des Krieges geleistet habe – ich habe ihnen bei einigen Geschäften mit der Außenwelt geholfen. Aber wenn es Jessica nicht gäbe, wäre ich ins Ödland zurückgekehrt.}
{161}{}{Wer ist Jessica?}
{162}{}{Du scheinst mit deinem Leben bei Wind des Krieges nicht besonders zufrieden zu sein.}
{163}{}{Was hält dich davon ab, die Siedlung zu verlassen?}
{164}{}{Erzähl mir mehr über diesen Ort.}

{170}{}{Oh, sie ist meine erste und einzige Liebe! Früher dachte ich immer nur an mich selbst, bis ich sie kennenlernte. Sie wohnt im Haus gleich hier in der Nähe.}
{171}{}{Hm. Kann ich dir vertrauen? Ich bin nämlich ein Wanderer wie du ... Weißt du, hier ist es gar nicht so übel, wenn man sich mit der „reinrassigen“ Bevölkerung arrangiert. Früher habe ich in einem ganz anderen Umfeld gelebt ... Aber wen will ich hier eigentlich täuschen? Als „Halbblut“ werde ich hier nicht respektiert, ich darf nicht einmal eine Familie gründen. Dabei wäre ich verdammt noch mal ein guter Ehemann!}
{172}{}{Äh ... Eigentlich könnte ich jederzeit gehen. Aber Jessica lassen sie nicht weg. Außerdem haben sie mir sogar verboten, mit ihr zu reden! Als ich ihr einen Heiratsantrag gemacht habe, nannten ihre Brüder mich ein Halbblut und warfen mich aus dem Haus. Und ohne sie sehe ich keinen Grund zu gehen.}

{173}{}{He! Was ist denn das Problem, Romeo? Lauft doch gemeinsam aus der Siedlung weg!}
{174}{}{Meinst du das ernst? Verdammt, daran habe ich schon so oft gedacht. Glaubst du wirklich, dass das klug wäre?}
{175}{}{Aber klar! Ignorier ihre Brüder, macht, was ihr beide wollt! Wer sind die schon, dass sie über euch bestimmen?}
{176}{}{Weißt du, das ist nicht besonders klug. Das Ödland ist gefährlich, wenigstens hier bist du geschützt.}

#Get the quest
{177}{}{[Seufzt] Stimmt. Na ja, danke für den Besuch.}
{178}{}{Ja, keine Sorge! War nur Spaß. Ich finde nämlich, du solltest unbedingt fliehen!}
{179}{}{Ja, tschüss.}
{180}{}{Ja! Ja!! Danke, mein Freund! Für deine Unterstützung und alles. Jetzt muss ich nur noch einen Plan aushecken. Ich denke schon sehr lange darüber nach, mit ihr zusammen wegzulaufen, aber das ist nicht so einfach.}
{181}{}{Ich helfe dir. Was brauchst du?}
{182}{}{Na, find es selbst heraus. Ich habe noch andere Dinge zu tun.}

{183}{}{Die Brüder halten Jessica also eingesperrt und lassen sie nicht unbeaufsichtigt hinaus. Entkommen kann sie nur nachts, wenn sie schlafen. Aber es gibt ein Problem: Nur die Brüder haben die Schlüssel zur Tür.}
{184}{}{Du musst also die Schlüssel zur Tür besorgen?}
{185}{}{Aber denk daran: Sie dürfen keinen Verdacht schöpfen. Wenn beide Brüder ihre Schlüssel verlieren, werden sie misstrauisch. Verlieren sie aber nur einen, schieben sie es vielleicht auf ihre eigene Nachlässigkeit. Zumindest denke ich das.}
{186}{}{In Ordnung. Ich sehe, was ich tun kann.}

{190}{}{Da bist du ja, Freund. Wie läuft's?}
{191}{}{Ich habe den Schlüssel!}
{192}{}{Jetzt ist alles viel einfacher. Keine Brüder, keine Probleme mit der Tür.}
{193}{}{Es gibt noch keinen Grund zur Freude. Zumindest noch nicht. Warte auf Neuigkeiten.}

{194}{}{Warte mal, du hast beide Schlüssel geklaut? Oh nein! Was hast du getan?! Bring einen der Schlüssel zurück, bevor sie es merken! Beeil dich!}
{195}{}{Schon gut, schon gut ...}
{196}{}{Großartig! Gute Arbeit. Jetzt müssen wir vor allem den richtigen Zeitpunkt finden, um die Barrikaden zu errichten.}
{197}{}{Die Barrikaden?}
{198}{}{Na klar! Sie lassen uns nicht durchs Tor, also müssen wir über die Muellhaufen am Rand klettern.}
{199}{}{Du brauchst ein Seil.}

{200}{}{Ganz genau! Ich weiß, dass der Techniker eins hatte, sofern er es nicht schon verkauft hat. Bitte besorg uns ein Seil!}
{201}{}{Okay, aber ich brauche etwas als Gegenleistung.}
{202}{}{Okay, du bekommst das Seil.}
{203}{}{Verdammt, ich habe mein Leben schon genug riskiert. Jetzt liegt es an dir, hier rauszukommen. Ich gehe.}

{204}{}{Ja, ich... verstehe. Danke trotzdem. Ohne deine Hilfe können wir zwar nicht entkommen, aber trotzdem - danke.}
{205}{}{Ja. Leb wohl.}

{206}{}{Oh, natürlich, tut mir leid. Aber ich habe hier keinen Laden. Außer diesen Flaschen habe ich kaum etwas anzubieten. Im Ödland könnten wir sie wirklich gut gebrauchen, aber das Seil ist wichtiger.}
{207}{}{Bist du wahnsinnig?! Wozu braucht der Techniker verdammte Feldflaschen? Gib mir Geld! Je mehr, desto besser!}
{208}{}{Großartig, das passt mir.}
{209}{}{Ich hab's mir anders überlegt. Du brauchst diese Sachen, also sehe ich mal nach, was ich entbehren kann.}

{210}{}{Äh ... Geld ist uns wichtiger. Also gut, hier sind 100 Dollar. Das reicht gerade für das Seil und deine Mühen.}
{211}{}{Na, geht doch. Warte auf mich.}
{212}{}{[Gibt dir 3 leere Feldflaschen] Hoffentlich reicht das.}
{213}{}{Hoffen wir's. Warte auf mich.}
{214}{}{Danke, Freund!}
{215}{}{Schon gut. Warte, bis ich das Seil besorgt habe.}
{216}{}{Wegen des Seils: Ich brauche etwas zum Tauschen.}

#Rope
{220}{}{Hallo. Tut mir leid, dass hier so ein Chaos herrscht ...}
{221}{}{Ich hab dir das Seil besorgt.}
{222}{}{Schon gut, ich gehe.}

{223}{}{Wirklich? Oh, das ist großartig. Gib es mir ...}
{224}{}{Nicht so schnell! Sag mir, warum sollte ich dir helfen? Warum sollte ich dich nicht einfach ausliefern?}
{225}{}{Hier, bitte. Ich hoffe, das hilft dir.}
{226}{}{Tut mir leid, ich hab es woanders liegen lassen.}

{227}{}{Verstehe. Ich weiß, wie ich mich bei dir bedanken kann. Aber erst, wenn du uns geholfen hast. Ich kann dir von einem Versteck mit sehr nützlichen Sachen erzählen. Auf jeden Fall wirst du dabei nicht leer ausgehen.}
{228}{}{Das ist in Ordnung für mich. Na dann, hier ist das Seil.}
{229}{}{Tut mir leid, aber nein. Ich komme wieder, wenn ich es mir anders überlegt habe.}

{230}{}{Das reicht. Jetzt bleibt nur noch eins zu tun. Wir müssen nachts fliehen, sonst werden wir leicht entdeckt und gefasst. Aber die Barrikaden nördlich von Jessicas Haus werden von einer Straßenlaterne beleuchtet. Ich fürchte, jemand muss zurückbleiben und den Strom abstellen, während wir auf die andere Seite gelangen.}
{231}{}{Ha, tu nicht so, als wäre dir das gerade erst klar geworden. Ich merke, wenn jemand Gefühle nur vorspielt. Schon gut, ich hab den Wink verstanden. Ich bin der Schalter, der den Strom abstellt. Wer sonst, wenn nicht ich!}
{232}{}{Such dir einen anderen Dummen. Ich hab meinen Teil erledigt. Ich bin weg.}

{233}{}{Na dann, wird's Zeit, zur Tat zu schreiten! Du musst nur bis zur Nacht warten und die Straßenbeleuchtung ausschalten.}
{234}{}{Klar. Legen wir los!}
{235}{}{Wahrscheinlich, aber ich bin noch nicht bereit. Du musst warten.}

{236}{}{Hast du es dir noch nicht anders überlegt?}
{237}{}{Ich werde den Schalter umlegen und den Strom abschalten. Wer sonst, wenn nicht ich!}
{238}{}{Zu deinem Pech muss ich ablehnen.}

{239}{}{}

#Brothers are dead
{240}{}{Was?! Verdammt! Wie hast du das denn geschafft? Erklär's nicht, ich will es gar nicht wissen. Wichtig ist jetzt, den richtigen Moment abzupassen, um die Barrikaden zu erklimmen.}

#Women's replics
{1110}{}{Danke, Wanderer. Danke für alles!}
{1177}{}{[Seufzt] Stimmt. Na ja, danke für den Besuch.}
{1180}{}{Ja! Ja!! Danke, mein Freund! Für deine Unterstützung und alles. Jetzt muss ich nur noch einen Plan aushecken. Ich denke schon sehr lange darüber nach, mit ihr zusammen wegzulaufen, aber das ist nicht so einfach.}
{1190}{}{Da bist du ja, Freund. Wie läuft's?}
{1194}{}{Warte mal, du hast beide Schlüssel geklaut? Oh nein! Was hast du getan?! Bring einen der Schlüssel zurück, bevor sie es merken! Beeil dich!}
{1203}{}{Verdammt, ich habe mein Leben schon genug riskiert. Jetzt liegt es an dir, hier rauszukommen. Ich gehe.}
{1209}{}{Ich hab's mir anders überlegt. Du brauchst diese Sachen, also sehe ich mal nach, was ich entbehren kann.}
{1214}{}{Danke, Freund!}
{1221}{}{Ich habe dir ein Seil besorgt.}
{1226}{}{Tut mir leid, ich hab es woanders liegen lassen.}
{1231}{}{Ha, tu nicht so, als wäre dir das gerade erst klar geworden. Ich merke, wenn jemand Gefühle nur vorspielt. Schon gut, ich hab den Wink verstanden. Ich bin der Schalter, der den Strom abstellt. Wer sonst, wenn nicht ich!}
{1232}{}{Such dir einen anderen Dummen. Ich hab meinen Teil erledigt. Ich bin weg.}
{1235}{}{Wahrscheinlich, aber ich bin noch nicht bereit. Du musst warten.}
{1236}{}{Hast du es dir noch nicht anders überlegt?}
