{100}{}{Du siehst Jessica.}
{101}{}{Du siehst einen Bewohner des Windes des Krieges.}
{102}{}{Guten Tag, Wanderer.}
{103}{}{Was haben sie getan!? Ich will sie nicht mehr sehen!}

#Brothers see the char when s/he tries to speak with Jessica
{110}{}{Hey, du! Lass meine Schwester in Ruhe!}
{111}{}{Äh, entschuldige ... Sie mögen es nicht, wenn ich mit Fremden rede.}
{112}{}{Hey! Wir haben dir nicht erlaubt, mit ihr zu reden! Hau ab!}

#If the char is a male
{120}{}{Oh, du solltest nicht mit mir reden. Meine Brüder sind wegen der Geschichte mit Robert völlig durchgedreht. Jetzt darf ich nicht mehr mit Fremden reden.}
{121}{}{Ich wollte nur sagen, dass Robert die Flucht vorbereitet. Sei bereit!}
{122}{}{}
{123}{}{Also, wer bist du, ein Gefangener?}
{124}{}{Na gut, ich werde nicht darauf bestehen.}
{125}{}{Was? Aber ... [whispering] Hat er sich wirklich dazu entschlossen? Ach, das wäre großartig. Ich bin so verzweifelt, hier zwischen diesen vier Wänden zu sitzen.}
{126}{}{Eher eine Sklavin. Meine Brüder halten mich eingesperrt und verbieten mir, mit anderen Männern zu reden, außer mit „reinrassigen“ Militärs. Und es ist schwer, sich ihnen zu widersetzen. Du solltest auch damit aufhören, sonst werfen sie dich aus dem Haus.}
{127}{}{Das ist großartig. Warte.}
{128}{}{Ziemlich strenge Moralvorstellungen ...}

#If char is a female
{130}{}{Hallo, Fremder. Schön, dich zu sehen. Meine Brüder sind wegen der Geschichte mit Robert völlig durchgedreht. Sie lassen mich nur mit Frauen und „reinrassigen“ Militärs reden, und die sind, glaub mir, keine besonders angenehme Gesellschaft.}
{131}{}{Ich wollte nur sagen, dass Robert die Flucht vorbereitet. Sei bereit!}
{132}{}{„Reinrassig“? Wie definieren sie das?}
{133}{}{Wer bist du also, ein Gefangener?}
{134}{}{Wer ist Robert?}
{135}{}{Ich rede später mit dir.}

{140}{}{Was? Aber ... [whispering] Hat er sich wirklich dazu entschlossen? Ach, das wäre großartig. Ich bin so verzweifelt, hier zwischen diesen vier Wänden zu sitzen.}
{141}{}{Du musst noch ein bisschen warten. Hab einfach Geduld.}
{142}{}{Nun, wenn man bedenkt, wie viele Verwandte aus dem Ödland stammen, sind wir eine der reinblütigsten Familien weit und breit – alle Mitglieder unserer Familie sind direkte Nachfahren der ersten Siedler. Und auf dieser dämlichen Grundlage kamen meine Brüder auf die Idee mit der „reinen Rasse“.}
{143}{}{Eher eine Sklavin. Meine Brüder halten mich eingesperrt und verbieten mir, mit anderen Männern zu reden, außer mit „reinblütigen“ Soldaten. Und dagegen lässt sich schwer etwas machen.}
{144}{}{[Verschränkt die Hände und kneift die Augen zusammen] Oh, er ist mein Hoffnungsschimmer. Auch wenn meine Brüder mir seinetwegen nicht mehr erlauben, mit Außenstehenden zu reden, bin ich mit dem Leben hier nicht zufrieden. Ich will Freiheit und Liebe. Robert ist der Mann, der mir all das gegeben hat. Aber sag es meinen Brüdern nicht, sie können ihn nicht ausstehen.}

#Women's replics
{1102}{}{Na, hallo, Wanderer.}
