{100}{}{Du siehst Jessicas Bruder.}
{101}{}{Du siehst einen Bürger von Wind of War.}
{102}{}{Für einen Außenstehenden bist du gar nicht so übel.}
{103}{}{Zurück ins Ödland, Affe! Hier bist du nicht willkommen!}
{104}{}{Was sollen wir jetzt nur ohne unsere Schwester machen?!}
{105}{}{*Skriptfehler*}

{108}{}{Ich bin nicht unbedingt ein Befürworter solcher Maßnahmen, es ist nur ... einfach passiert, verstehst du? Hör zu, Außenstehender, hier sind 1.000 Dollar, damit du den Mund hältst, klar?}
{109}{}{Ich weiß, wann ich den Mund halten muss, wenn die Bezahlung stimmt ...}

#Äèàëîã
{110}{}{Na, na. Was haben wir denn hier? Noch so ein verstrahlter Knochenbeutel. He-he ... So was wie ein Beutel voller Knochen! [spricht zu seinem Bruder] Hast du das gehört, Bruder!? Ein Knochenbeutel! Pft-ha-ha-ha-ha!}
{111}{}{Lacht nur, ihr Spaßvögel. Wenn Robert euch eure Schwester wegnimmt, vergeht euch das Lachen.}
{112}{}{Wenn euch meine Anwesenheit so amüsiert, dann verschwinde ich eben.}
{113}{}{Ja, schon klar. Ich gehe besser, bevor ich mir noch mehr von euren „Witzen“ anhören muss.}

{114}{}{Hä. Ich versteh's nicht. Robert? Ist dieser Köter schon wieder dahinter?!}
{115}{}{Ja. Wo glaubst du, sind die Schlüssel zu deinem Haus geblieben?}
{116}{}{Robert? Welcher Robert? Da musst du dich verhört haben.}

{117}{}{Ha! [spricht mit seinem Bruder] Hey, Bruder! Sieht so aus, als wäre es Zeit, jemandem die Taschen zu leeren! Dieses Stück Dreck bettelt schon wieder darum! [Er wendet sich an dich] Aber merk dir meine Worte, Fremder. Wenn wir die Schlüssel nicht bei ihm finden, wird das dein letzter Witz sein.}
{118}{}{Na los, Kämpfer! Auf in den Krieg!}

#Ñêğèïòîâàÿ ñöåíà
{120}{}{Wo glaubst du, gehst du hin, du Stück brahmin-Scheiße?}
{121}{}{Hey ... Was wollt ihr, Leute?}
{122}{}{Deine Taschen durchsuchen, falls sich ein verirrter Schlüssel darin verirrt hat!}
{123}{}{Ich ... Ich habe eure Schlüssel nicht ...}
{124}{}{Halt die Klappe!}
{125}{}{ }
{126}{}{Nimm das, Schwächling!}
{127}{}{Oh Scheiße! Was haben wir getan?!}
{128}{}{Verschwinden wir, bevor wir erwischt werden!}

#Female character
{1108}{}{Ich bin nicht unbedingt ein Befürworter solcher Maßnahmen, es ist nur ... einfach passiert, verstehst du? Hör zu, Außenstehender, hier sind 1.000 Dollar, damit du den Mund hältst, klar?}
{1117}{}{Ha! [spricht mit seinem Bruder] Hey, Bruder! Sieht so aus, als wäre es Zeit, jemandem die Taschen zu leeren! Dieses Stück Dreck bettelt schon wieder darum! [Er wendet sich an dich] Aber merk dir meine Worte, Fremder. Wenn wir die Schlüssel nicht bei ihm finden, wird das dein letzter Witz sein.}
