{100}{}{Du siehst einen Sanitäter.}
{101}{}{Du siehst einen sehr gerissenen alten Mann. Mit dem legst du dich besser nicht an!}

#Start of the dialogue
{110}{}{Ja?}
{111}{}{Ich brauche nichts.}
{112}{}{Verkaufst du Drogen?}
{113}{}{Stellst du Drogen her?}

#Selling Niskigwan's backpack
{120}{}{Ich habe ein ausgezeichnetes Set für Heiler gefunden, eine Sammlung von Werkzeugen und so weiter. Willst du es dir ansehen?}
{121}{}{Ein Set für Heiler, sagst du? Wie lustig. Was ist drin? Ein paar Blütenblätter und Blumen? He-he ...}
{122}{}{Nein. Es enthält allerlei Dinge, um draußen in der Wildnis Medizin herzustellen. Sieh es dir lieber selbst an.}
{123}{}{Hmm ... Interessant. Offenbar war der Besitzer kein schlechter Heiler. Also ... Ich kaufe das Set für 1000, keinen Cent mehr.}
{124}{}{Na gut, einverstanden.}
{125}{}{Nein, ich finde einen ernsthafteren Käufer.}
{126}{}{Wie du willst.}
{127}{}{[Mehr]}
{128}{}{Sehr gut, das kann ich gebrauchen.}
{129}{}{Das hast du doch absichtlich gemacht, oder? Jetzt heb es auf. Na los, na los!}
{130}{}{Äh, tut mir leid! Kommt nicht wieder vor!}
{131}{}{Wie läuft's mit dem Wasser? Ich war in Salt Lake, dort sieht es ziemlich übel aus ...}

#Consultation on the Salt Lake's problem
{132}{}{Was Wasser angeht, ist nicht überall alles gut. Aber wir sind keine besonders große Siedlung, und die Ökologie hier ist relativ normal. Wir kommen zurecht.}
{133}{}{Wie bekommt ihr sauberes Wasser?}
{134}{}{Wir graben einen tieferen Brunnen und schöpfen das Wasser auf kluge Weise. Es muss sich absetzen und abgekocht werden. Und eine Prise Desinfektionsmittel erledigt den Rest.}
{135}{}{Ein Wasserdesinfektionsmittel? Wo bekommt ihr das her?}
{136}{}{Wir hatten noch einen guten Vorrat von dem Ort, von dem wir gekommen sind, aber jetzt ist er fast aufgebraucht.}
{137}{}{Also verkaufst du mir diese Chemikalie nicht?}
{138}{}{Nein. Wasser ist wertvoller als dein Geld, selbst wenn du viel bieten würdest.}
{139}{}{Wie wollt ihr dann die Wasseraufbereitung in Angriff nehmen?}
{140}{}{Alles verfügbare Desinfektionsmittel aufkaufen, Zisternen bauen und Anlagen zur Wasseraufbereitung einrichten. Ich glaube, irgendwo gibt es auch Generatoren und Filter. In den großen Städten, zum Beispiel in Vegas ...}
{141}{}{Was noch? Du scheinst eine Idee zu haben.}
{142}{}{Ach, nichts. Es wäre einfach furchtbar praktisch, Wasser aus dem Boden zu pumpen. Dort ist es sauber. Dafür bräuchte man allerdings eine Menge Spezialausrüstung. Und offenbar gibt es in Salt Lake schon eine Menge solcher Ausrüstung.}
{143}{}{Warum glaubst du das?}
{144}{}{Weil schon ein paar Karawanen hierhergekommen sind und gefragt haben, ob wir einen Filter zur Aufbereitung von Grundwasser haben.}
{145}{}{Und? Habt ihr einen?}
{146}{}{Natürlich haben wir keinen! Wo sollten wir den herhaben?! Und selbst wenn wir einen hätten, würden wir ihn längst selbst benutzen. Na ja, du weißt schon.}
{147}{}{Ach ja. Traurig.}

#Medical care of the char
{180}{}{Ich muss mich heilen lassen.}
{181}{}{Wahrscheinlich ist es nichts Ernstes. Mal sehen ...}
{182}{}{Komm schon, Doc! Ich sterbe!}
{183}{}{Immer mit der Ruhe, reg dich nicht so auf!}
{184}{}{DOKTOR!!!}
{185}{}{Ah, jetzt ist alles klar. }
{186}{}{ Dollar, und du bist wieder ganz der Alte.}
{187}{}{Was?! Ich sterbe hier, und du denkst nur ans Geld?!}
{188}{}{Mach, was du willst, aber ich arbeite nicht umsonst.}
{189}{}{Hier ist das Geld. Verarzte mich.}
{190}{}{Auf deine blöde Medizin kann ich verzichten. Viel Glück.}
{191}{}{Sieh dich an! Und du musst wirklich nicht so schreien.}
{192}{}{Na ja, wenigstens danke, dass du mich nicht sterben lassen hast!}

{195}{}{Aber du bist kerngesund und kannst sofort ins Ödland geschickt werden. Brauchst du es wirklich?}
{196}{}{Freut mich zu hören.}

#The production of medicine:
{200}{}{Wenn du die nötigen Komponenten besorgst, kann ich Stimpaks, Super-Stimpaks, Gegengifte und Heilpulver herstellen.}
{201}{}{Dann brauche ich es nicht. Eine andere Frage.}
{202}{}{Könntest du mich unterrichten?}
{203}{}{Dann wärst du also mein Konkurrent? Nein, Geld zu verdienen ist schon schwer genug.}
{204}{}{Nein, aus einem anderen Grund – damit ich nicht zu Wesker gehe und ihm erzähle, dass du hier ein Drogenlabor hast. Das lässt sich übrigens leicht beweisen.}
{205}{}{Schade.}
{206}{}{Wa... Oh, du Schuft! So dankst du mir also für meine Güte!}
{207}{}{Alter, schrei nicht, sonst hören sie dich. Das endet übel. Ich sage es nicht zweimal. Letzte Chance.}
{208}{}{Äh ...}
{209}{}{Alter, ich warte. Na los! Entscheide dich endlich!}

{210}{}{Ach, so ist das! Wesker wäre das völlig egal! VERSCHWINDE!}
{211}{}{Du hast dein eigenes Todesurteil unterschrieben. Warte nur, bis du davon hörst.}

{212}{}{Äh ... Okay. Ich erzähle dir alles. So ein großes Geheimnis ist es schließlich nicht.}
{213}{}{Gute Entscheidung. Fang an zu reden.}

{214}{}{[Du experimentierst eine Weile. Schließlich gelingt es dir, dieses Handwerk zu erlernen. Jetzt kannst du Gegengifte und Heilpulver herstellen.]}
{215}{}{Guten Tag.}

#The production of medicine:
{216}{}{Ein stimpak herstellen.}
{217}{}{Einen Super-Stimpak herstellen.}
{218}{}{Ein Gegengift herstellen.}
{219}{}{Heilpulver herstellen.}

{220}{}{Das mache ich, wenn du mir den Schwanz eines Radskorpions bringst. }
{221}{}{Das mache ich, wenn du mir eine leere Spritze, eine Xanderwurzel und eine Broc-Blüte bringst. }
{222}{}{Das mache ich, wenn du mir eine Xanderwurzel und eine Broc-Blüte bringst. }
{223}{}{Ich mach's, wenn du mir ein stimpak, Nuka-Cola und eine Mutafrucht bringst. }
{224}{}{ Dollar pro Dosis.}
{225}{}{...Obwohl, warum brauchst du so eine primitive Droge? Du hättest dir ein stimpak kaufen sollen...}

{226}{}{Eins.}
{227}{}{Zwei.}
{228}{}{Drei.}
{229}{}{Fünf.}
{230}{}{Zehn.}
{231}{}{Nichts.}
{232}{}{Hoppla. Ich habe kein Geld.}

{233}{}{Na gut, was kannst du mir dafür anbieten?}
{234}{}{Hoppla. Ich habe kein Geld.}

#Medical aid to the beaten up caravaneer
{250}{}{Beeil dich! Einer der Karawanenleute braucht medizinische Hilfe!}

{251}{}{Äh... [schüttelt den Kopf] Noch einer wurde abgeknallt? Das passiert hier oft.}
{252}{}{Hier sind 100 $. Hilf ihm!}
{253}{}{}
{254}{}{Ich verpasse dir Schlimmeres, wenn du ihm nicht hilfst. Beeil dich, du alter Sack!}
{255}{}{Du solltest nicht so herzlos sein!}

{256}{}{Wenn ich's mir recht überlege - warum nicht...}
{257}{}{Genau. Los! Los!}

#Women's replics
{1120}{}{Ich habe ein ausgezeichnetes Set für Heiler gefunden, eine Sammlung von Werkzeugen und so weiter. Willst du es dir ansehen?}
{1124}{}{Na gut, einverstanden.}
{1131}{}{Wie läuft's mit dem Wasser? Ich war in Salt Lake, dort sieht es ziemlich übel aus ...}
{1180}{}{Hilfe! Ich bin verletzt!}
{1186}{}{ Dollar, und du bist wieder ganz der Alte.}
{1204}{}{Nein, aus einem anderen Grund – damit ich nicht zu Wesker gehe und ihm erzähle, dass du hier ein Drogenlabor hast. Das lässt sich übrigens leicht beweisen.}
{1206}{}{Wa... Oh, du Schuft! So dankst du mir also für meine Güte!}
{1210}{}{Ach, so ist das! Wesker wäre das völlig egal! VERSCHWINDE!}
