{100}{}{Du siehst einen Wachposten.}
{101}{}{Wie du dir denken kannst, ist das ein Wachposten.}

#If you received the permission to go into the settlement
{102}{}{Komm rein, komm rein, keine Sorge.}
{103}{}{Erst hacke ich dir die Hände ab, dann die Beine, und danach kannst du anfangen, Fragen zu stellen!}

#Dialogue, when the character has a weapon in hands
{110}{}{Warte! Holster deine Waffe! Entlade sie und leg sie hin! Sofort!}
{111}{}{Warum ist das nötig? Hast du Angst, ich könnte den vierten Weltkrieg anfangen?}
{112}{}{Okay, ich leg sie weg.}
{113}{}{Letzte Warnung! Leg die Waffe hin! Schnell!}
{114}{}{Trotzdem, warum brauchst du sie? Ist es hier so unsicher?}
{115}{}{Na gut, siehst du? Ich leg sie weg.}

#Attempts to go to the territory of the settlement
{116}{}{Das hier ist das Gebiet einer Militärgarnison. Außenstehende dürfen ohne Erlaubnis nicht hierher.}
{117}{}{Ich habe dort etwas zu erledigen.}
{118}{}{Wie bekomme ich eine Erlaubnis?}
{119}{}{Du meinst, ich darf nicht rein? Okay, ich gehe.}
{120}{}{Du DARFST nicht, du Vollidiot! Du hast dort nichts zu suchen. Dreh dich um und geh, wenn du keine Kugel in der Stirn willst.}
{121}{}{Jetzt hör mir mal zu, du Dreckskerl. Wenn du noch einmal so mit mir redest...}
{122}{}{Erlaubnis, hm? [Er grinst und kneift die Augen zusammen, während er die anderen Soldaten ansieht] Na ja, wir können über dein Problem sprechen, wenn du interessiert bist ...}
{123}{}{Natürlich. [Zwinkern und 100 $ aus der Tasche nehmen].}
{124}{}{Hm ... Ist das ein Hinweis auf etwas?}
{125}{}{[Sein Gesichtsausdruck wird unfreundlich] Umdrehen und verschwinden! Aber zackig!}
{126}{}{Was zum Teufel war das denn? ...}
{127}{}{Na gut. Endlich.}
{128}{}{Tschüss.}
{129}{}{Wie bitte? Na ja ... Das hier ist ein wichtiger Ort. Der Durchgang kostet 300 Mäuse.}
{130}{}{300? Warum sollte ich für den Zugang zu einem Wohngebiet bezahlen?!}
{131}{}{Na gut, hier ist das Geld.}
{132}{}{Sei da draußen vorsichtig ... Die Einheimischen mögen keine Fremden.}
{133}{}{Tschüss!}

#Dialogue after the phrase "I've got business there"
{134}{}{Ja? Was für ein Geschäft?}
{135}{}{Ich suche eine Toilette ... Obwohl ich es lieber woanders erledigen würde. Tschüss.}
{136}{}{Ich mache Geschäfte mit Nuka-Cola. Ich glaube, der Wind des Krieges lässt sich ein gutes Geschäft nicht entgehen.}
{137}{}{Ich bin nach Hawthorne gereist und habe interessante Informationen über eure Siedlung gefunden.}
{138}{}{Ich habe eine Kiste großkalibrige Munition für Maschinengewehre. Vielleicht können wir ins Geschäft kommen.}
{139}{}{Ich suche die Drahtzieher hinter dem Überfall auf den Karawanenzug aus Vegas.}
{140}{}{Ich muss wegen einer persönlichen Angelegenheit mit General Wesker sprechen.}
{141}{}{Wesker? Na ja ... In Ordnung, du kannst durch. Aber wir müssen dein Gepäck auf gefährliche Gegenstände überprüfen.}
{142}{}{Endlich.}
{143}{}{Wesker? Und warum sollte ich diesen Unsinn kaufen?}
{144}{}{Ich weiß nicht ...}
{145}{}{Was für eine Überraschung! Jetzt dreh dich um und verschwinde zurück ins Ödland. Das hier ist eine Militärgarnison, bei uns gibt es keine Plünderer. Verstanden? Gut. Wenn du darauf bestehst, wird es einen Frechen weniger geben.}
{146}{}{Grr ...}
{147}{}{Oh ... Na gut, dann lasse ich dich durch. Aber wir müssen dein Gepäck auf gefährliche Gegenstände überprüfen.}
{148}{}{Okay, danke.}
{149}{}{Drogen und Alkohol sind hier verboten. Lass die Waffe im Holster. Wenn wir dich bewaffnet sehen ... bist du selbst schuld. Alles klar? Wegen Wesker: die Straße entlang bis zum Ende, dann ins Gebäude auf der rechten Seite.}
{150}{}{Dann prüf nach.}
{151}{}{Auf keinen Fall!}
{152}{}{}
{153}{}{Okay. Ich kümmere mich um diese Sachen und komme wieder.}
{154}{}{Das hier ist kein Laden, du Schwachkopf, das ist ein Militärstützpunkt! Der Laden ist dort drüben! [Er zeigt auf das Gebäude hinter dir]}
{155}{}{Ich weiß, aber der Ladenbesitzer weigert sich, ohne Weskers Erlaubnis zu verhandeln.}
{156}{}{Na gut, ich gehe zu ihm.}
{157}{}{Weil er mir persönlich einen Auftrag in Hawthorne gegeben hat. Glaubst du mir nicht? Dann kontaktiere ihn über Funk!}
{158}{}{Weil ich in Hawthorne wichtige Dokumente gefunden habe, die den General interessieren dürften.}
{159}{}{}
{160}{}{Nein, es ist verboten, Drogen und Alkohol hier reinzubringen. Das musst du wegwerfen. [Er zeigt auf: }
{161}{}{]}
{162}{}{Okay, ich komme wieder.}

{163}{}{Diese Angelegenheit ist vertraulich und geht dich nichts an.}
{164}{}{Halt den Mund. Wenn du wirklich hier etwas zu erledigen hast, warum habe ich dann keine Anweisungen wegen dir?}
{165}{}{Weil dein Büro ein einziges Chaos ist. Also hör auf, meine Zeit zu verschwenden. Dein General wartet auf mich.}
{166}{}{Ich weiß nicht. Na gut, ich komme später wieder ...}

#After obtaining permission to enter
{170}{}{Komm rein, komm rein, bleib nicht einfach da stehen.}
{171}{}{Warte, lass mich dir erst ans Bein pinkeln. Das ist hier draußen im Ödland so Brauch.}
{172}{}{In Ordnung.}

{173}{}{Wie bitte?! Igitt! Verschwinde von mir!}
{174}{}{Ha, ein harter Kerl mit einer großen Waffe hat Angst vor ein bisschen Urin!}
{175}{}{Ich bestehe nicht darauf.}

{176}{}{Ach, so ist das also? Ich schätze, du suchst Ärger! Willst du ein paar Tage in unserem Knast verbringen? Das lässt sich sehr schnell einrichten!}
{177}{}{Ein Versager wie du droht mir mit dem Knast? [Spuckt ihm vor die Füße]Du hast dir den Falschen ausgesucht!}
{178}{}{Okay, schön, ich gehe einfach. Ganz ruhig und friedlich.}

{179}{}{[Er spricht durch zusammengebissene Zähne] Das reicht, du Abschaum. Ich habe genug von deinen Witzen. [Er richtet seine Waffe auf dich]}
{180}{}{Okay, einverstanden. Schluss mit den Witzen.}
{181}{}{Halt den Mund! Hände auf den Kopf! Bewegung! Jetzt verbringst du den Tag im Knast!}
{182}{}{Was immer du sagst, ich werde mich nicht mal wehren ...}
{183}{}{Ins Gefängnis?! Ich?! Fick dich!}

{184}{}{Oh, kriege ich dort auch Mittagessen? Das wäre nett.}
{185}{}{Ja, dein Mittagessen wird ein Gummireifen mit Schwefelsoße und Betonkrümeln sein. Probier ruhig mal!}

#Rednecks
{190}{}{Der General sprach von einem Vorfall mit ein paar Hinterwäldlern an diesem Posten. Erzähl mir mehr.}
{191}{}{[Zuckt gleichgültig mit den Schultern] Ein alter Mann aus dem Ödland wollte sich gewaltsam Zutritt verschaffen. Er hat einen Faustschlag ins Gesicht und einen Tritt in den Arsch kassiert und ist dann abgehauen. Wahrscheinlich ist er jetzt beim Bahnhof und leckt seine Wunden. Das Mädchen war bei ihm. Sie sah dämlich aus.}
{192}{}{Ja.}

#Women's replics
{1137}{}{Ich bin nach Hawthorne gereist und habe interessante Informationen über eure Siedlung gefunden.}
{1145}{}{Was für eine Überraschung! Jetzt dreh dich um und verschwinde zurück ins Ödland. Das hier ist eine Militärgarnison, bei uns gibt es keine Plünderer. Verstanden? Gut. Wenn du darauf bestehst, wird es einen Frechen weniger geben.}
{1158}{}{Weil ich in Hawthorne wichtige Dokumente gefunden habe, die den General interessieren dürften.}
