#Ïëàâàşùèå ôğàçêè ÃÃ êîãäà òîò îñìàòğèâàåò ïåğâûõ äâóõ óáèòûõ

{113}{}{Du hast den Karawanenreisenden von „Speed Hawk“ gefunden. Er ist tot.}
{114}{}{Du hast einen weiteren Karawanenreisenden von „Speed Hawk“ gefunden. Leider ist auch er tot.}
{115}{}{Verdammt, dieser Karawanenreisende von „Speed Hawk“ wurde mit außergewöhnlicher Brutalität zusammengeschlagen.}

#Ïëàâàşùèå ôğàçêè ÃÃ, êîãäà òîò îñìàòğèâàåò òğåòüå òåëî
{116}{}{Dieser hier wurde erschossen. Sieht aus, als hätte er fliehen wollen.}
{117}{}{Dieser hier hat einen Schädelbruch. Diese Räuber müssen ganz schön harte Kerle sein.}
{118}{}{Die Kerle waren definitiv nervös. Dieser hier muss mindestens zwei Stunden lang verprügelt worden sein ...}
{119}{}{Moment mal! Was ist das?}
{120}{}{Sieht aus wie ein Medaillon. Vielleicht ist es einem der Räuber heruntergefallen ...}
{121}{}{Du hast einen seltsamen Beweisgegenstand gefunden.}
