{100}{}{Du siehst einen einfachen Soldaten.}
{101}{}{Du siehst einen begriffsstutzigen einfachen Soldaten, der offenbar viel zu viel Freizeit hat.}

#Попытка заговорить
{102}{}{Er ist zu beschдftigt damit, nichts zu tun. Er wird nicht mit dir reden.}

#Перед тем, как разбежаться и вляпаться в матрас
{110}{}{Hey! Sieh mal, was ich kann!!!}
{111}{}{Sieh hin!}
{112}{}{Eins!}
{113}{}{Zwei!}
{114}{}{Ziele an ...}
{115}{}{Drei!}
{116}{}{Juhuu!}