{100}{}{Du siehst einen einfachen Soldaten.}
{101}{}{Das ist ein einfacher Soldat, der niedrigste Dienstgrad.}

{102}{}{Alarm! Wir werden angegriffen!}
{103}{}{Ich hab dich gewarnt! Dafür wird jemand bestraft!}

#Ñòàğòîâàÿ âåòêà
{110}{}{Halt! Du darfst nicht in der Kaserne sein. Raus hier. Los!}
{111}{}{Ich gehe, wo ich will! Verstanden, Soldat? Oder soll ich's dir pantomimisch zeigen?}
{112}{}{Kaserne? Ich dachte, das wäre irgendeine Art Hotel ...}
{113}{}{Was? Du schon wieder?! Das reicht - wenn ich dich noch einmal in der Kaserne sehe, reiße ich dich *persönlich* in Stücke, Glied für Glied! Verstanden?}