{100}{}{Du siehst einen müden Militärangehörigen.}
{101}{}{Du siehst einen Militärangehörigen in staubiger Kleidung.}
{102}{}{Du hast das Militär überredet, dir das Versteck mit der Beute zu zeigen.}
{103}{}{Du bist der Letzte, den wir hier sehen wollen ...}

{110}{}{[Fuchtelt mit den Händen] Zivilist, hör auf, vor meinen Augen herumzuwuseln. Für heute habe ich genug von dir.}
{111}{}{Verstehe. Nach dem Zustand deiner Ausrüstung zu urteilen, bist du gerade aus dem Ödland zurückgekehrt, oder?}
{112}{}{Na gut, ich mache Platz.}

{113}{}{Ja, wir haben das Gebiet wie befohlen patrouilliert. Was geht dich das an?}
{114}{}{Patrouilliert, ja ... Weißt du, manche sagen, in der Nähe des Ortes, an dem die Postkutsche von „Speed Hawk“ überfallen wurde, seien Soldaten gewesen ...}
{115}{}{Schon gut.}

{116}{}{Na und? Was hat das mit uns zu tun? Moment mal – willst du etwa uns, ehrliche Soldaten, für einen Überfall mitten in der Wüste verantwortlich machen? Uns, die wir all die Jahre versucht haben, in Südn evada für Ordnung zu sorgen?!}
{117}{}{Ich habe Beweise, also lass diese Haltung. Überleg dir lieber, was du dagegen tun kannst.}
{118}{}{Vielleicht finde ich erst einmal Beweise ...}

{119}{}{Dann reden wir, Herr Inspektor. Bring sie her. Wir werden gemeinsam sehen, was wir damit anfangen. Ha!}
{120}{}{Tatsächlich habe ich bereits Beweise dafür, dass ihr den Überfall verübt habt. Was sagst du dazu?}
{121}{}{Klar.}

{122}{}{[Sieht sich um] Verdammt. Für einen Wanderer bist du ganz schön gerissen. Du hast uns in der Hand ... Dann bleibt nur noch eine kleine Frage – wo und wie wir dich für dein Schweigen bezahlen sollen. Darum geht es dir doch, oder? Du willst deinen Anteil? Gehen wir vor die Basis, dann bekommst du ihn.}
{123}{}{Deine Einfältigkeit ist ein wenig verdächtig, aber ... Na gut, führ mich zu deinem Versteck. Ich behalte dich im Auge.}
{124}{}{Was für ein interessantes Angebot. Ich muss darüber nachdenken. Ich komme wieder, wenn ich mich entschieden habe.}

#Womens replica
{1110}{}{[Fuchtelt mit den Händen] Zivilist, hör auf, vor meinen Augen herumzuwuseln. Für heute habe ich genug von dir.}
{1119}{}{Dann reden wir, Herr Inspektor. Bring sie her. Wir werden gemeinsam sehen, was wir damit anfangen. Ha!}
{1122}{}{[Sieht sich um] Verdammt. Für einen Wanderer bist du ganz schön gerissen. Du hast uns in der Hand ... Dann bleibt nur noch eine kleine Frage – wo und wie wir dich für dein Schweigen bezahlen sollen. Darum geht es dir doch, oder? Du willst deinen Anteil? Gehen wir vor die Basis, dann bekommst du ihn.}
