{100}{}{Du siehst einen Gefangenen.}
{101}{}{Das ist ein Verbrecher, den das Militär hinter Gitter gebracht hat.}

{102}{}{Du hast den Gefangenen vor der Hinrichtung bewahrt.}
{103}{}{Verdammt! Das war klasse! Wir haben's geschafft! Ha-ha! Ich bin frei! Danke für deine Hilfe, ich schulde dir was. Jetzt komm ich schon klar. Übrigens, falls du mal in Vegas bist, such mich auf. [zwinkert]}
{104}{}{In Vegas? Na gut.}
{105}{}{Psst! Nicht jetzt!}
{106}{}{Keine Sorge. Ich bleib in der Nähe.}

{110}{}{Ein neues Gesicht, was? Super!}
{111}{}{Weswegen sitzt du hier?}
{112}{}{Eigentlich wegen nichts.}
{113}{}{Wirklich?}
{114}{}{Ja! Verdammt, natürlich! Was denkst du denn? Hier in Wind of War ist das Militär schlimmer als die Raider. Sie wollen alles für sich, nehmen dir dein Geld und deine Waffen weg und sperren dich dann einfach ein, diese Bastarde! Ughhh! [bruellt zur Tür] Dafür werdet ihr verdammt noch mal bezahlen, ihr Drecksäcke!!!}
{115}{}{Du willst also sagen, sie haben dich einfach angehalten und mit vorgehaltener Waffe ausgeraubt? War's so?}
{116}{}{Nein ... Na ja, doch, aber ... Ich meine ... Hör zu, ich bin hier, weil ich Widerstand geleistet habe. Jetzt bereiten sie eine Hinrichtung vor. Sie wollen eine Show daraus machen. Drecksäcke! Ich hasse diese Schweine!}
{117}{}{Hm, ich weiß nicht, ob ich dir das glaube.}
{118}{}{Wie auch immer! Benutz verdammt noch mal deinen Kopf! Sie haben dir einfach deine Sachen abgenommen und dich hier reingesteckt. Für sie bist du nur Dreck unter ihren Füßen. Denk drüber nach, du hast noch Zeit. Während ich in ein paar Tagen hingerichtet werde ...}
{119}{}{Hmm ...}

{120}{}{Also, was meinst du?}
{121}{}{Ich weiß nicht so recht. Ich muss erst meine Gedanken ordnen.}
{122}{}{Weißt du, ich bin zwar nicht in der Position, irgendetwas zu verlangen, aber an deiner Stelle würde ich Folgendes tun. [flüstert] Wenn sie dich gleich rauslassen, stell dich an die passende Stelle und stell eine dumme Frage, damit ich diesem Arschloch die Kehle packen kann, wenn er reinkommt, klar? Dann müssen wir nur noch unbemerkt um die Ecke zum Zaun kommen ...}
{123}{}{Ich denke darüber nach ...}
{124}{}{Ja, denk darüber nach, solange wir noch Zeit haben. Ich bin bei der Tür, falls du dich entscheidest.}
{125}{}{Ja ... Das ist eine verdammt schwierige Lage.}

{126}{}{Übrigens werde ich morgen hingerichtet, falls dich das interessiert.}
{127}{}{Der Weg ist frei. Verschwinden wir von hier.}
{128}{}{Du musst warten.}