{100}{}{Du siehst einen Drill Sergeant.}
{101}{}{Du siehst einen Zugführer, Ausbilder und Mentor.}

#Ïîïûòêà çàãîâîğèòü
{102}{}{Zivilisten?! Dafür habe ich keine Zeit.}

#Êîãäà áîéöû îòæèìàşòñÿ
{110}{}{Los, Mädels!}
{111}{}{Gut!}
{112}{}{Eins-zwei! Eins-zwei!}
{113}{}{Hört auf zu jammern!}
{114}{}{Ich mache Männer aus euch, selbst wenn ihr dabei draufgeht!}
{115}{}{Jetzt mit einer Hand!}
{116}{}{Jetzt ohne Hände!}
{117}{}{Keine Faulenzerei, Soldat!}
{118}{}{So macht man keine Liegestütze!}
{119}{}{He, Knochensäcke! Wenn ihr euch nicht sofort anstrengt, schrubbt ihr den Rest des Tages Latrinen!}
{120}{}{Bewegt euch, bewegt euch!}

#Êîãäà áîéöû äåğóòñÿ
{130}{}{Jawohl! Mit links! Links!}
{131}{}{Der Feind ist direkt vor euch!}
{132}{}{Wut! Ich sehe keine Wut in euren Augen!}
{133}{}{Grinst! Zeigt mir euer Grinsen!!!}
{134}{}{Los!!!}
{135}{}{Einige von euch haben noch eine Chance, Männer zu werden!}
{136}{}{Reden wir über die Green Berets!}
{137}{}{Arrrgh!!!}
{138}{}{Na also!}
{139}{}{Das nenne ich einen Hieb!}
{140}{}{Lernt, solange ich noch da bin!}
{141}{}{*Diese* Kerle? Krieger?!}
{142}{}{*Tsk-tsk-tsk*}
{143}{}{*Du nimmst mir das Leben, doch ich nehme dir auch deins*}