{100}{}{Du siehst Anders.}
{101}{}{Du siehst einen Techniker in schmutziger Arbeitskleidung, die voller Flecken ist, und ... barfuß!}

#Pulls you up, if you're trying to get into the garage
{108}{}{Dieb! Ein Dieb in meiner Garage!}
{109}{}{Verdammt, ich wurde erwischt ...}
{110}{}{Hey! Halt! Du darfst da nicht hin!}
{111}{}{Hoppla, ich dachte, das wäre die Toilette ...}
{112}{}{Ich habe dich gewarnt! Du darfst da *nicht* hin! Mach das noch mal, und jemand wird verletzt, verstanden?!}
{113}{}{In Ordnung.}
{114}{}{Das war's, du bist erledigt!}
{115}{}{Was?! Aber ich habe doch nichts getan! ...}

###############################################################
#
# The beginning of the conversation and the answers to the questions
#
###############################################################

#Starting dialogue branch:
{116}{}{Was?}
{117}{}{Wegen der Reparatur.}
{118}{}{Ich suche etwas ganz Bestimmtes.}
{119}{}{Ich habe gehört, du hast etwas echt Großartiges in der Garage, mit Motor und Lichtern. Brumm-brumm! Stimmt das?!}
{120}{}{Und? Was ist mit meiner Bestellung?}
{121}{}{Ach, vergiss es.}

#Search for items:
{130}{}{Na ja, meine Auswahl ist nicht gerade riesig ... Was willst du?}
{131}{}{}
{132}{}{Eine Munitionspresse. Du kannst doch eine bauen, oder?}
{133}{}{Ich habe gehört, hier in der Nähe soll es irgendwo einen Hightech-Bunker geben?}
{134}{}{Reinigungsfilter für den artesischen Wasserturm in Salt Lake.}
{135}{}{Hast du zufällig Schießpulver auf Lager?}
{136}{}{Vielleicht hast du ja etwas Nützliches zum Tauschen?}
{137}{}{Eigentlich wegen nichts.}

#Purchasing gunpowder:
{140}{}{Richtig!}
{141}{}{Was?! Ich soll doch nicht in das Lagerhaus von jemand anderem kriechen! Vergiss es.}
{142}{}{Vielleicht kann ich mit jemandem ein Geschäft einfädeln, aber das dauert einen ganzen Tag, und ich muss den Soldaten bezahlen, der das Lagerhaus bewacht. Also: 1000 Mäuse – und in zwei Tagen bekommst du ein Paket mit Schießpulver.}
{143}{}{Hier sind 500 als Anzahlung. Den Rest bekommst du, wenn das Paket fertig ist.}
{144}{}{Schon gut.}
{145}{}{Leg dich nicht mit mir an. Ich habe keinen Sinn für Humor.}
{146}{}{Verstanden.}
{147}{}{Na gut, fair genug. Ich mach's. Die Kiste gehört dir, aber nicht vor Ablauf von zwei Tagen.}
{148}{}{In Ordnung.}
{149}{}{Also, was ist mit meiner Bestellung?}
{150}{}{Ich habe die Kiste. Wo ist mein Geld?}
{151}{}{Hier sind 500 Dollar.}
{152}{}{Ich geh sie holen.}
{153}{}{Ein ausgezeichnetes Geschäft, aber ich kann dir kein weiteres Schießpulver besorgen. Sonst wird der Verlust bemerkt und sie fangen an, die Leute auszuquetschen.}
{154}{}{Wow! Das reicht für einen ganzen Zug.}

{155}{}{Schießpulver? Wesker verbietet uns, solch wertvolle Vorräte mitzunehmen. Ich verkaufe dir kein Pulver.}
{156}{}{Du kannst doch ein bisschen aus dem Lagerhaus nehmen ... [wink]}
{157}{}{In Ordnung.}
{158}{}{Lagerhaus? Ich? Ich darf da nicht mal rein! Aber ... [leans over to you and talks quietly] andererseits muss ich es ja nicht unbedingt selbst sein, oder? [winks at you]}

#Artesian water filter
{159}{}{Oh ja, ich habe von dem Ding von den Karawanenleuten gehört. Ehrlich gesagt, würde ich es gern selbst finden und sogar bis nach Salt Lake City transportieren. Aber ich habe keine Ahnung, wo ich eins herbekommen soll!}
{160}{}{Wie schade.}

#Reloading press
{161}{}{Nein, ich kann keins herstellen. Und wenn ich das verkaufe, mit dem ich arbeite, nagelt Wesker mich an den Zaun wie einen Deserteur. Also nein, nein und nochmals nein.}

#About the shelter
{167}{}{Hightech, sagst du? Ha! Ich würde dich gern nach ein paar Jahren in diesem Drecksloch wiedersehen. Wir sind weggegangen, als es unmöglich wurde, dort zu leben. Dieser Vault war überhaupt nicht zur Nutzung gedacht. Es war eine Versuchsanlage, um Materialien und Technologien zu testen. Mehr nicht. Woher weißt du überhaupt davon?}
{168}{}{Ich habe darüber auf dem alten Holodisk gelesen.}
{169}{}{Äh ... nur die Gerüchte.}

{170}{}{Ein alter Holodisk? Das ist sehr interessant!}
{171}{}{Ich kann dir den Eintrag auf meinem Pip-Boy zeigen.}
{172}{}{Äh, ich habe den Holodisk nicht dabei. Er lag im Büro in Hawthorne.}
{173}{}{Geht dich nichts an, Alter.}
{174}{}{Geht dich nichts an, sagst du? Wenn unsere Leute dich mit den Füßen über einem brennenden Fass aufhängen, wirst du anders denken.}
{175}{}{Verdammt, hör zu, ich will dich warnen – es gibt Leute in unserer Gemeinschaft, die dieses Band nicht sehen dürfen. Das ... könnte unangenehme Folgen haben. [kommt bedrohlich auf dich zu] Verstehst du mich, Fremder? Unangenehme Folgen *für uns alle* und ganz besonders für dich. Mach nichts Dummes.}
{176}{}{Ach, so ernst ist es also ...}
{177}{}{Bedroh mich nicht. Ich gehe einfach.}
{178}{}{Offenbar wird nicht jeder in dieser Stadt erfreut sein zu erfahren, dass er von Deserteuren abstammt.}
{179}{}{Nun, ich nehme es an. Aber jetzt spielt das keine Rolle mehr. Schließlich haben wir den Vault in die Luft gesprengt, als sich die Mutanten dort niedergelassen hatten.}
{180}{}{Ist es da drin gefährlich?}
{181}{}{Allerdings. Deshalb wird dich auch niemand herumführen.}

###############################################################
#
# About repairing
#
###############################################################

{200}{}{Das ist mein Fachgebiet! Was willst du?}
{201}{}{Kannst du meine Rüstung verbessern?}
{202}{}{Kannst du meine Waffen verbessern?}
{203}{}{}
{204}{}{Nichts.}

{205}{}{Nicht genug. Seltsam, findest du nicht?}
{206}{}{Hm.}
{207}{}{Dann musst du deine Rüstung ausziehen. Oder soll ich daran mit dem Schneidbrenner arbeiten, während du sie trägst? Kein Problem, zumindest für mich, hehe.}
{208}{}{Machen wir's lieber, ohne meine Gesundheit zu riskieren. Ich ziehe sie aus ...}

{228}{}{Äh ... Was jetzt, was jetzt ... Jetzt brauche ich }
{229}{}{ Dollar, um zum Zug zu kommen, außerdem die Zugkoordinaten und weitere Informationen darüber, wie man hinkommt und wo man was findet.}

{230}{}{Nur Rüstungen aus Metall und Leder. Mit denen weiß ich bereits umzugehen.}
{231}{}{Lederrüstung.}
{232}{}{Eine alte Metallrüstung.}
{233}{}{Metallrüstung MK2.}
{234}{}{Ich habe es mir anders überlegt. Es ist nicht nötig.}
{235}{}{Oh, so viel Geld habe ich nicht ...}
{236}{}{Keine Fragen. Ich mache es für }
{237}{}{ Dollar.}
{238}{}{Hier ist die Bezahlung, ich warte.}
{239}{}{(Vor deinen Augen verwandelt der Techniker die Rüstung in etwas Neues!)}
{240}{}{(Vor deinen Augen verwandelt der Techniker die Rüstung in etwas Neues und Glänzendes!)}
{241}{}{Das nenne ich guten Service!}

{242}{}{Hey! Ich werde *deinen* Kram nicht abholen!}
{243}{}{Oh, ich hole ihn gleich ab ...}

{244}{}{Ich habe die Schusswaffen satt. Ich arbeite ständig mit Waffen – „reparier mir das“, „montier das daran“ ... Im Grunde geht es um Militärzeug – Gewehre, Schrotflinten, manchmal Raketenwerfer und andere kleine Freuden eines guten Soldaten.}
{245}{}{}
{246}{}{Der Beschleuniger für den Magnum-Revolver.}
{247}{}{Stelle aus 5 Dynamitstangen Dynamit her.}
{248}{}{Zerlege Dynamit in Dynamitstangen.}
{249}{}{Zurück.}
{250}{}{}
{251}{}{Ist mir egal, mir gefällt es. Reparier es!}
{252}{}{Also, es lohnt sich nicht? Dann vergiss es.}
{253}{}{}
{254}{}{}
{255}{}{Erhöhe die Magazinkapazität des Sturmgewehrs.}
{256}{}{Kein Problem. Ich mache es für }
{257}{}{ Dollar.}
{258}{}{Fertig!}

#Fixing the train
{260}{}{Ich muss diesen Bordcomputer für den Zug reparieren lassen.}
{261}{}{Zugcomputer? Interessant. [Er berührt den Computer mit den Fingerspitzen, ganz pompös] Es scheint, als fehle etwas. Das muss ich mir genauer ansehen. Für }
{262}{}{ werde ich mir den Kopf zerbrechen.}
{263}{}{Na gut, ich bezahle. Aber gib dir Mühe!}
{264}{}{Ich komme wieder, wenn ich mir solche Ausgaben leisten kann.}

{265}{}{He-he-he! Wirf das Geld doch nicht einfach auf den Boden!}
{266}{}{Guter Punkt.}
{267}{}{Ah, jetzt ist mir alles klar. Für die Vorbereitungen brauche ich ein paar Tage. Es sollte nicht allzu lange dauern ... Vielleicht.}
{268}{}{Gut. Ich sehe später nach dir.}
{269}{}{Du hast einen Weg gefunden, den Zug zu reparieren. Glückwunsch!}

###############################################################
#
# The car
#
###############################################################

#Questioning about the car:
{270}{}{Moment mal! Woher weißt *du*, was in meiner Garage vor sich geht, hm? Antworte mir!}
{271}{}{Beruhig dich! Ein paar Leute haben nur ein eindeutiges Geräusch daraus gehört, mehr nicht.}
{272}{}{Hmm ... Klingt logisch. Nun, natürlich habe ich da drin etwas Technik ... Und sie funktioniert fast.}
{273}{}{Also stimmten die Gerüchte. Und wenn es kein Geheimnis ist – was ist es? Kann ich es mir ansehen? Kann ich es kaufen?}
{274}{}{Ich bin damit beschäftigt, ein wirklich cooles Stück Technik zu reparieren, aber du müsstest den Rest deines Lebens sparen, um es kaufen zu können.}
{275}{}{Ach, komm schon! Zwing mich nicht, dich deswegen auszufragen!}
{276}{}{Na schön. Aber Geld allein wird sowieso nicht reichen ...}
{277}{}{Hör auf, mich zu quälen! Sag mir, was hast du in der Garage?! Was?! Einen Generator? Einen Wagen? Ein Motorrad? Einen Hubschrauber? ... Oder ein AUTO?!!}
{278}{}{Ein Pickup. Fast wie neu. Aber wie gesagt, er fährt nicht.}
{279}{}{Oh, es wäre toll, ein echtes, funktionierendes Auto zu sehen. Ja, das ist das Coolste, was man zur Erkundung des Ödlands finden kann!}

{280}{}{Ganz genau. Ein Pickup eignet sich am besten für unsere Landschaft, also habe ich ihn zur Reparatur gebracht. Aber die Arbeit musste wegen eines einzigen Teils eingestellt werden. Ich brauche einen Kraftstoffregler, sonst fährt das Auto nicht.}
{281}{}{Sehr interessant. Hey, erzähl mir von Autos. Du scheinst dich gut damit auszukennen.}
{282}{}{Ich bin viel unterwegs und kann das fehlende Teil finden.}
{283}{}{Wenn ich das Teil finde, werde ich versuchen, es hierherzubringen.}

{284}{}{Ich habe viele kaputte Autos gesehen. Warum wurden sie zurückgelassen?}
{285}{}{Wie hast du es geschafft, deinen Truck zu kaufen?}
{286}{}{Was ist mit dem Regler los?}
{287}{}{Warum ist es so schwer, das Auto zu reparieren?}

{288}{}{Tatsächlich gibt es mehrere Gründe. Stell dir vor, wie es während des Großen Krieges war. Die Bomben fielen hauptsächlich auf Städte, wo die meisten Autos standen. Diejenigen, die weit genug von den Explosionen entfernt und größtenteils unversehrt geblieben waren, konnten einfach nicht mehr repariert oder aufgetankt werden. Diese Vorkriegsautos wurden von Atombatterien angetrieben und waren technisch komplex und wartungsintensiv. Sie brauchten gute Pflege und mussten ständig überwacht werden. Außerdem waren sie sehr teuer – nicht jeder konnte sich eins leisten. Und dann waren da noch die Schrecken, die auf den Krieg folgten: Tote, überall Verbrecher, Staus auf den Straßen ... Unzählige Autos wurden unter freiem Himmel zurückgelassen und sind in 70 Jahren einfach vor Alter auseinandergefallen. Und das sind nur einige der Gründe.}
{289}{}{Sie stand in der Garage eines Hauses in Pahrump. Aber der Vorbesitzer hat das Auto völlig heruntergewirtschaftet, also hatte ich alle Hände voll damit zu tun, Teile und Innenausstattung wieder einzubauen. Das einzige ungelöste Problem ist, einen Kraftstoffregler zu finden.}
{290}{}{}
{291}{}{Im Grunde ist das ein Chip, der die Stromverteilung im Elektromotor des Fahrzeugs steuert. Diese Chips brannten schnell durch, wenn das Auto nicht richtig gewartet wurde. Meistens passierte das, wenn man die Autos zu oft abrupt und gleich mit hoher Geschwindigkeit anfahren ließ. Dabei muss man sanft und aus niedriger Geschwindigkeit beschleunigen. Warum das passierte, lässt sich schwer erklären. Jedenfalls fand ich in den Wohngebieten keinen einzigen funktionierenden Chip, der für so einen Pick-up geeignet wäre.}
{292}{}{Das ist eine wirklich komplexe Technik. Komplexer als Computer oder sogar eine Radarstation, glaub mir. Kannst du dir vorstellen, wie viel Elektronik da drinsteckt? Und der Motor ist buchstäblich eine Bombe! Ich habe ein paar Jahre gebraucht, nur um die Konstruktion dieses Autos grob zu verstehen.}

{293}{}{Dann sieh dich gründlich um. Es ergibt kaum Sinn, unter dem freien Himmel nach Schrott zu suchen. Ich würde an Orten anfangen, wo die Autos sicher eingeschlossen waren, etwa in Garagen und Werkstätten. Und ich sollte erwähnen, dass ich bei den Karawanenhändlern in Vegas und Reno Bestellungen aufgegeben habe, aber sie sind alle gescheitert. Vielleicht solltest du noch weiter weg von der Zivilisation suchen.}
{294}{}{Wir könnten stundenlang darüber reden.}

#When you got the controller
{295}{}{Da ist er – der Kraftstoffregler!}
{296}{}{Sieht aus, als würde er funktionieren ... Oh, ich bin so aufgeregt, dass mir die Hände schwitzen!}
{297}{}{Nicht so schnell! Was bekomme ich für diesen Chip?}
{298}{}{Gute Frage. Also, machen wir es so: Ich kaufe dir diesen Chip für 2000 Dollar ab und repariere dann das Auto – das wird eine Weile dauern. Danach kannst du den ganzen Truck kaufen. Wenn du willst, natürlich.}
{299}{}{Hm. Und für wie viel?}
{300}{}{Gute Idee, hier ist der Steuerchip.}
{301}{}{Auf keinen Fall. Ich behalte das Ding erst mal.}
{302}{}{Ich hatte auf 35.000 Dollar gehofft. Und nur in bar! Und spar dir die Überredungsversuche, ich will erst dieses Auto reparieren.}
{303}{}{Reden wir noch mal über Autos.}

{308}{}{Hier ist das Geld. Ich denke, ein Tag sollte reichen, um die Arbeit fertigzustellen. Komm morgen wieder. Dann können wir über einen Kauf sprechen, falls du noch interessiert bist.}
{309}{}{Alles klar.}
{310}{}{}
{311}{}{}
{312}{}{[Starrt dich entsetzt an] Was machst du da, du Idiot?!! Das ist ein sehr empfindliches Ding!!!}
{313}{}{Keine Sorge, es ist nicht kaputtgegangen ...}
{314}{}{Na, wie steht's um meinen Truck?}

{315}{}{Deinen? Es ist immer noch *mein* Truck, du Spinner! Und weißt du was? Er ist einfach wunderschön! Mein ganzes Leben lang habe ich von so einem Ding geträumt, und ich weiß nicht, ob ich bereit bin, es an einen völlig Fremden zu verkaufen.}
{316}{}{Verstehe. Welche Summe würde den Schmerz über deinen Verlust lindern?}
{317}{}{. Nur Bares!}
{318}{}{Hier ist der volle Betrag, den du wolltest.}
{319}{}{Bist du sicher?}
{320}{}{Was? Nicht genug Geld? Hm, seltsam ...}

{321}{}{Gib mir Zeit zum Nachdenken.}
#Women dialogue branch
{322}{}{Das ist eine beträchtliche Summe. Sag mal, gibt es in dieser Stadt irgendwelche Möglichkeiten, mit einem Körper wie meinem gutes Geld zu verdienen?}
{323}{}{Mit diesem Körper könntest du höchstens als Fußmatte am Bahnhofseingang arbeiten. Bring dich erst mal in Ordnung. Vielleicht findet sich dann jemand mit einem prall gefuellten Geldbeutel, der Interesse hat.}
{324}{}{Oh, das ändert alles! Für solche Beine würde ich selbst bezahlen. Ich kann auch meine Freunde einladen.}

###############################################################
#
# Other
#
###############################################################

{325}{}{Den Granatwerfer leichter machen.}
{326}{}{Die Leistung des Flammenwerfers erhöhen.}
{327}{}{Rucksacktank für den Flammenwerfer.}
{328}{}{Die Magazinkapazität des „Desert eagle“ erhöhen.}
{329}{}{Ein Zielfernrohr am Jagdgewehr montieren.}

{330}{}{}
{331}{}{Ach, verpiss dich, du Flegel!}
{332}{}{Wie du willst. Ich schlage vor, du entscheidest.}

{333}{}{Dann erinner mich an den Preis.}
{334}{}{Das ist zu viel. Um so viel Geld aufzutreiben, müsste die ganze Karawane ein Jahr lang arbeiten. Überleg es dir noch einmal, wenn du keinen Kunden verlieren willst.}
{335}{}{Na gut, das ist es wert. Wo sollen wir uns einfinden, harter Kerl?}
{336}{}{Nein, das gefällt mir nicht. Leb wohl.}

{337}{}{Äh, ein starkes Argument ... Na gut, du hast gewonnen. Ich bin bereit, den Preis um }
{338}{}{ zu senken. Aber das ist mein letztes Angebot.}
{339}{}{Verstehe. Also ist es jetzt ...}
{340}{}{Oh, okay. Kehren wir zum vorherigen Preis zurück ...}
{341}{}{Nein, ich habe schon zu viel Arbeit hineingesteckt.}

{342}{}{Du hast 1000 Dollar verdient, indem du dem Techniker nachgegeben hast. Er war ein grausamer Perverser. Die Blutergüsse am ganzen Körper werden dir noch eine Weile wehtun.}
{343}{}{Wenn ich es mir recht überlege, werde ich das Geld auf andere Weise auftreiben.}
{344}{}{Schätzchen, das Geld, das du mir gegeben hast, reicht nicht einmal, um die Behandlung der Blutergüsse zu bezahlen. Ich erinnere mich, dass du etwas von deinen Freunden gesagt hast?}
{345}{}{Aus einer Jagdflinte eine abgesägte Schrotflinte machen.}
{346}{}{Ich komme später wieder.}
{347}{}{Bist du sicher, dass du das tun willst? Unsere Jungs aus der Garnison sind ausgesprochen hartnäckig. Sie könnten dich zu Brei schlagen.}
{348}{}{Ja ... ich ... muss da fürs Geld durch.}
{349}{}{Gleichzeitig Sex mit fünf Militärs zu haben, ist eine harte Sache. Du kannst froh sein, noch am Leben zu sein. Trotzdem hast du 5000 Dollar verdient.}

###############################################################
#
# Power armor
#
###############################################################

# Question about a helmet
{371}{}{Hast du schon einmal eine Rüstung mit so einem Helm gesehen?}
{372}{}{[Untersucht den Helm sorgfältig] Eigentlich stammt er nicht von einer Rüstung, sondern von einem Druckanzug. Ich glaube, er wurde vor dem Krieg in irgendeinem Labor verwendet.}
{373}{}{Gibt es eine Möglichkeit, den Hauptteil wiederherzustellen?}
{374}{}{Den ganzen Anzug? Natürlich nicht! Für so eine Aufgabe habe ich weder Werkzeug noch Maschinen oder Materialien. Frag Mechaniker in großen Industriestädten. In Salt Lake City zum Beispiel. Die haben keine solchen Probleme mit Ausrüstung und Bauteilen.}
{375}{}{In Ordnung.}

# Asking about the armor and the blueprints
{376}{}{Weißt du etwas über Powerrüstungen?}
{377}{}{Zu den Bauplänen für Powerrüstungen.}
{378}{}{Hmm ...}
{379}{}{}

{380}{}{Ein bisschen. Aber mein ganzes Wissen ist keinen Cent wert ohne Hightech-Maschinen und Materialien. Trotzdem kannst du in Nevada noch eine funktionstüchtige Rüstung sehen. Wesker zieht seine nie aus. Ich glaube, er wird darin sterben ...}
{381}{}{Wesker trägt eine funktionstüchtige?}
{382}{}{Nicht ganz. Sie hat keinen Helm, lässt sich nicht vollständig versiegeln, und einige Funktionen arbeiten nicht. Soldaten haben diesen Schrott vom Testgelände in Hawthorne mitgebracht. Dort wurde er auf Haltbarkeit getestet – deshalb besteht er jetzt aus Löchern, die wiederum voller Löcher sind.}
{383}{}{Und wie wurde diese Rüstung repariert?}
{384}{}{Gar nicht. Sie ist, wie sie ist. Es gibt weder Ersatzteile noch Werkzeuge, von Produktionsmaschinen ganz zu schweigen. Aber warum zum Teufel verhörst du mich?!}
{385}{}{Offensichtlich hätte ich gern so eine Rüstung für meinen persönlichen Gebrauch.}
{386}{}{Nur aus Neugier. Danke für die Erklärung.}
{387}{}{Natürlich ... Wer würde das nicht ... Aber das spielt keine Rolle. Wesker wird die Rüstung nicht hergeben, und wir haben keine zweite. Selbst mit allen Bauplänen in der Hand könnten wir die Produktion nicht auf die Beine stellen. Sie ist zu kompliziert und zeitaufwendig. Vor dem Krieg waren die gesamten Produktionsanlagen darauf ausgelegt, sie herzustellen. Es gab Hunderte Spezialisten und hochpräzise Maschinen, und die Prototypen brauchten Jahre bis zur Fertigstellung. Und jetzt kommst du hierher und sagst: „Ich will so eine.“ Ha!}
{388}{}{Hat also außer der von Wesker keine funktionstüchtige Rüstung bis heute überlebt?}
{389}{}{Alles, was du kriegen kannst, sind nutzlose Baupläne. Powerrüstungen waren im Besitz des Militärs und selbst damals schon knapp. Was glaubst du, wo sie jetzt sind? Natürlich entweder auf Militärbasen, an die wir nicht herankommen, oder im Lauf der Zeit zerstört. Ich würde sagen: Geh nach Osten, nach Washington, und wer weiß, wohin sonst noch. Vielleicht findest du eine zwischen den Ruinen der Hauptstadt. Heh, viel Glück dabei.}
{390}{}{Verstehe ... Moment, Baupläne? Du hast die Baupläne?!}

{391}{}{Verdammt, ich hab's ausgeplaudert, oder? Ich weiß nicht, wofür du sie brauchst, aber solche Sachen gibt man nicht völlig Fremden. Im Hauptquartier gibt es Baupläne der Rahmenkonstruktion, aber das ist nur ein Teil der gesamten Dokumentation. Und natürlich wird sie dir niemand aushändigen.}
{392}{}{Ich kann sie kaufen.}
{393}{}{*Du* wirst mir die Baupläne besorgen.}
{394}{}{Ich versuch's. Das Hauptquartier, sagst du? Na gut, ich sehe mir die Sache mal an.}
{395}{}{Kaufen!? Du hast doch gar nicht genug Geld, um so eine seltene Dokumentation zu bezahlen!}
{396}{}{Ich dachte, du hättest gesagt, sie wäre wertlos?}
{397}{}{Sobald es einen Käufer gibt, hat alles seinen Preis. Na gut, ich besorge dir die Baupläne. Für 3000 Dollar.}
{398}{}{Na gut, ich brauche die Baupläne. Hier ist das Geld.}
{399}{}{So viel!? Ich dachte, der echte Feilscher sitzt im Nebenzimmer, aber das hier ... Ich suche lieber nach einem anderen Weg.}

{400}{}{[Du wartest sehnsüchtig hinter den verschlossenen Türen, während der Techniker irgendwo auf dem Gelände des Hauptquartiers verschwindet. Schließlich kehrt er mit der Holodisk in der Hand zurück und sieht sich misstrauisch um.] Wenn ich für solche Sachen regelmäßig bezahlt würde, hätte ich inzwischen ganz Vegas gekauft. Kein Wort zu irgendwem!}
{401}{}{Kein Problem.}

{402}{}{Ach ja? Und warum sollte ich das tun?}
{403}{}{Weil ich dich bezahle.}
{404}{}{Weil ich dich bei Wesker verpetze, wenn du es nicht tust.}
{405}{}{Wenn du sie nicht brauchst, bestehe ich nicht darauf.}

{406}{}{Kumpel, sieh dir mein freundliches, mitfühlendes Gesicht an. Wie könnte ich dem Wanderer des Ödlands etwas Böses antun?}
{407}{}{Du hast dich verraten - du hast versucht, mich umzubringen, aber ich habe deinen Zettel gefunden. Ich habe ihn von der Leiche eines Söldners genommen.}
{408}{}{[Er scheint dich auf der Stelle erschießen zu wollen, doch plötzlich verändert sich sein Gesichtsausdruck.] Wie du willst. Die Baupläne zu besorgen, ist für mich ein Leichtes. Aber wenn ich sie habe, gibst du mir den Zettel zurück und ich vernichte ihn.}
{409}{}{Klar, abgemacht.}
{410}{}{Nicht so schnell, ich muss mir das erst überlegen.}

{411}{}{Wohin?}
{412}{}{Äh ...}

{413}{}{[Du wartest sehnsüchtig hinter den verschlossenen Türen, während der Techniker irgendwo auf dem Gelände des Hauptquartiers verschwindet. Schließlich kehrt er mit der Holodisk in der Hand zurück und sieht sich misstrauisch um] Ich habe, was du wolltest. Jetzt bist du dran.}
{414}{}{Na gut. Wir gehen friedlich und stillschweigend auseinander.}
{415}{}{Es hat nicht geklappt ...}

#Women's replics
{1111}{}{Hoppla, ich dachte, das wäre die Toilette ...}
{1114}{}{Das war's, du bist erledigt!}
{1115}{}{Was?! Aber ich habe doch nichts getan! ...}
{1146}{}{Verstanden.}
{1168}{}{Ich habe darüber auf dem alten Holodisk gelesen.}
{1175}{}{Verdammt, hör zu, ich will dich warnen – es gibt Leute in unserer Gemeinschaft, die dieses Band nicht sehen dürfen. Das ... könnte unangenehme Folgen haben. [kommt bedrohlich auf dich zu] Verstehst du mich, Fremder? Unangenehme Folgen *für uns alle* und ganz besonders für dich. Mach nichts Dummes.}
{1234}{}{Ich habe es mir anders überlegt. Es ist nicht nötig.}
{1312}{}{[Goggles starrt dich entsetzt an] Was tust du, du Idiot?!! Das Ding ist sehr zerbrechlich!!!}
{1315}{}{Deinen? Es ist immer noch *mein* Truck, du Spinner! Und weißt du was? Er ist einfach wunderschön! Mein ganzes Leben lang habe ich von so einem Ding geträumt, und ich weiß nicht, ob ich bereit bin, es an einen völlig Fremden zu verkaufen.}
{1407}{}{Du hast dich verraten - du hast versucht, mich umzubringen, aber ich habe deinen Zettel gefunden. Ich habe ihn von der Leiche eines Söldners genommen.}
