{100}{}{Du siehst Gefreiten Derren.}
{101}{}{Du siehst den jungen Gefreiten Derren. Über ihn gibt es nicht viel zu sagen.}
{102}{}{Meine, äh, Befehle erlauben mir nicht, mit dir zu sprechen.}
{103}{}{„Vielen Dank“ auch. Jetzt werde ich sie mein Leben lang nicht mehr los. Obwohl das Mädchen nett ist, vielleicht verstehen wir uns ja.}

{110}{}{Ich habe Dienst und kann nicht herumalbern.}
{111}{}{Also bist du der Gefreite, wegen dem dieser alte Hinterwäldler hergekommen ist?}
{112}{}{Tschüss.}

{113}{}{Nun, he, äh ... Sie haben es dir also auch erzählt? Ach, wie peinlich ... Moment, wer bist du? Ich hab dich mit Wesker gesehen, aber du gehörst nicht zur Garnison. Wer bist du?! Nenn deinen Namen!}
{114}{}{Ein Söldner, der Wesker Gelegenheitsarbeiten abnimmt. Und komm bloß nicht auf die Idee, der Frage auszuweichen.}
{115}{}{Hab ich nicht! Ich weiß nur nicht, was ich tun soll ... Diese Hinterwäldler kommen damit nicht so einfach davon. Und ich will nicht, dass sich die Gerüchte über mich in der Garnison verbreiten.}
{116}{}{Heißt das, was der Alte gesagt hat, stimmt? Du hast seine Tochter flachgelegt, oder?}

{117}{}{[Kratzt sich am Kopf] Ja, stimmt ... Hab ich. Aber ich bin doch kein Barbar! Während der Quartiermeister mit den Einheimischen zugange war, habe ich rund um die Scheune patrouilliert – und da war sie. Und ich musste sie nicht mal fragen. Sie ist von selbst auf den Rücken gefallen – juhu, wenn das doch jedes Mal so wäre!}
{118}{}{Tja, jetzt hast du eine Schachtel fürs Leben.}
{119}{}{Glaubst du, Wesker würde dein Verhalten gutheißen?}
{120}{}{Warum gehst du nicht zu ihnen, um zu verhandeln und alles zu beichten?}
{121}{}{}
{122}{}{Ich kann sie loswerden. Aber nicht umsonst.}
{123}{}{He, wer hat dieses Chaos hier angerichtet? Räum deinen Mist weg! Ich geh dann mal meinen eigenen Angelegenheiten nach.}

{124}{}{Was? He, du willst doch nicht sagen ... Was zum Teufel!? Dieser Trottel will mir also seine Verlobte aufhalsen!? Oh ...}
{125}{}{Na, bist du aber schick. Anscheinend gehört es in der Garnison zum guten Ton, auf sich zu achten. Kein Wunder, dass dieses Landei sich dir so leicht hingegeben hat.}
{126}{}{Hä? Hast du sie gesehen?! Das Gesicht voller Sommersprossen, die Schnauze eckig. Aber ja, hier gibt's nicht viele Mädchen, das stimmt. Natürlich ist sie besser als nichts. Aber nicht mit so einer Familie! Ich hab diese Dörfler gesehen. Da ist es viel besser, als Feigling zu gelten, als in ihre Familie einzuheiraten.}
{127}{}{Auf keinen Fall! In seinem Fall hältst du besser den Mund. Verstehst du, äh, was ich meine? Wenn nicht, dann, äh ... Hör zu, lass den General da besser raus.}
{128}{}{Bist du verrückt!? Hast du diese Familie gesehen? Das Mädchen mag ja hübsch sein, und in dieser Gegend gibt's nicht viel Auswahl, aber mit ihrer Familie verkehren? Da würde ich mich lieber aufhängen. Ich hab nicht all die Jahre in der Garnison verbracht, um den Rest meines Lebens unter Hinterwäldlern zu leben.}
{129}{}{Na ja, das ist übertrieben. Der Alte will dir seine Tochter wohl eher aufhalsen, damit er weniger Mäuler stopfen muss.}
{130}{}{Vielleicht. Aber stell dir vor, was für ein Gerede über mich bei uns die Runde machen wird. Es sind Dörfler. Obwohl wir sie vor Banditen schützen, freundet sich niemand mit ihnen an.}
{131}{}{Was für ein Narr. Der Ruhm eines Feiglings ist auch nicht besser.}
{132}{}{Solange ich nicht dazu gezwungen werde, gehe ich nicht zu ihnen. Und es ist mir egal, was irgendwer sagt.}
{133}{}{Wirklich? Äh, hör mal, ich verlange nichts Unmögliches. Sorge einfach dafür, dass sie Wind of War verlassen. Okay? Ich zahle dir alles, was ich in meinem Versteck habe – 300 Mäuse. Sie haben keinen Grund, hier herumzuhängen. Sollen sie einfach wieder aufs Feld gehen.}
{134}{}{Abgemacht.}

{135}{}{Die Hinterwäldler werden dich nicht mehr belästigen. Du kannst dich selbst davon überzeugen, wenn du willst.}
{136}{}{Wirklich? Puh, was für eine Erleichterung! Du willst mich doch nicht übers Ohr hauen, oder? Natürlich nicht, warum solltest du auch ... Ich habe dir 300 Mäuse versprochen. Hier, jetzt gehören sie dir. Aber sag dem General nichts davon.}
{137}{}{Nicht schlecht. Hör zu, lass dich bloß nicht noch einmal erwischen. Dann bist du auf dich allein gestellt.}
{138}{}{Du schon wieder? Willst du über diese Hinterwäldler reden?}

#Æåíñêèå ðåïëèêè
{1113}{}{Nun, äh ... Sie haben es dir auch erzählt? Oh, wie peinlich ... Moment, wer bist du? Ich hab dich mit Wesker gesehen, aber du bist nicht von der Garnison. Wer bist du?! Nenn mir deinen Namen!}
{1128}{}{Bist du verrückt!? Hast du diese Familie gesehen? Das Mädchen mag ja hübsch sein, und in dieser Gegend gibt's nicht viel Auswahl, aber mit ihrer Familie verkehren? Da würde ich mich lieber aufhängen. Ich hab nicht all die Jahre in der Garnison verbracht, um den Rest meines Lebens unter Hinterwäldlern zu leben.}