{100}{}{Du siehst einen Hinterwäldler.}
{101}{}{Du siehst einen groben, schwatzhaften Hinterwäldler. So einer kann selbst den größten Quasselkopf zum Schweigen bringen.}
{102}{}{Hey, du! Du bist doch keiner von den Soldaten, oder? Oh, ich würd dich ganz schön vermöbeln, wenn du einer wärst!}
{103}{}{Hey, du bist doch derjenige, der den Schlägern aus der Garnison ein Gewissen eingetrichtert hat? Danke!}

{110}{}{[Anscheinend redet dieser Sonderling gern viel und laut] Hey, du! Hallo! Komm her, komm schon! Komm, sag ich! Ja, ja, ich rede mit dir! Du lehnst uns doch nicht etwa Gesellschaft ab, oder? Steh nicht einfach da rum, was bin ich denn, so ein Ödlandknirps?! Ich hab Sachen gesehen, die du nicht glauben würdest!}
{111}{}{Moment mal, nicht so hastig. Wer genau bist du?}
{112}{}{Ach ja, verzeih einem Hinterwäldler. Unser Volk ist einfach gestrickt. Was sollen wir auch sonst tun, während wir warten, dass die Ernte wächst, oder abends, wenn es auf dem Hof dunkel ist? Uns unterhalten und die Fäuste schwingen. Aber ich rede zu viel. Das ist meine Tochter Christine. Ein gutes Mädchen, lass dich von ihren Sommersprossen nicht täuschen. Sie ist wuuunderschön, nicht wahr? Sieh sie dir nur an! [Christine murmelt mit näselnder Stimme leise „Paaapaaa!“] Ruhe! Sonst hau ich dir eine über und dann hältst du ganz schnell die Klappe!}
{113}{}{Äh ...}
{114}{}{Ähem. Also, ich bin ein alter Hinterwäldler. Ich heiße Festus. Sollte John heißen, das klänge kämpferischer, aber na ja – Festus ist auch in Ordnung. Jeder hier kennt mich! Frag irgendeinen Hinterwäldler in den Nachbardörfern – alle sagen Gutes über Festus. Na ja, manchmal Gutes, manchmal nicht ... Aber niemand behandelt mich respektlos. Außer diesen Schlägern auf der anderen Seite des Zauns. Oh, ich würd sie ganz schön vermöbeln, verdammt noch mal!}
{115}{}{Äh, kannst du das näher erklären? Wie haben diese Soldaten dich verärgert, Festus?}
{116}{}{Kommen wir gleich zur Sache – das gefällt mir! Wir werden uns prima verstehen, Junge. Halt nur immer dein Pulver trocken, wie ich stets sage, he-he ...}
{117}{}{Wegen dieser Soldaten ...}
{118}{}{Unterbrich mich nicht, ich war gerade dabei! Diese Militärs haben uns provoziert – sie kamen für Steuern und einer hat ein Auge auf mein Mädchen geworfen und sie ins Gebüsch gezerrt! Wäre ich dagewesen, hätte ich ihn vermöbelt. Wir erfuhren es erst später und suchten überall nach Christy, die weggelaufen war, um ihre Schande zu verbergen. Aber wir Hinterwäldler halten zusammen! Wir fanden sie, haben sie aufgewärmt, und da wurde alles klar. Jetzt will ich Gerechtigkeit: Ich will nicht nur dem Gefreiten die Fresse polieren, sondern ihn vor der Familie zur Rechenschaft ziehen! Doch wir kamen nicht durch den Kontrollpunkt. Ich wurde wütend, verprügelte den Wachmann, und sie jagten mich weg. Jetzt weiß ich nicht mal mehr, was ich tun soll.}

#Original Text unten
#Musste gekürzt werden, da 900 Zeichen Maximum erreicht war.
#{118}{}{Unterbrich mich nicht! Ich war ja gerade dabei ... Also, diese Militärs haben uns provoziert. O-oh, wie die uns provoziert haben! Sie kamen, um Steuern einzutreiben, und dann hatte einer von ihnen ein Auge auf mein Mädchen geworfen und sie direkt ins Gebüsch gezerrt! Wenn ich in der Nähe gewesen wäre, hätte ich ihn ordentlich vermöbelt! Erst später haben wir davon erfahren. Wir haben überall nach unserer Christy gesucht, denn sie war weggelaufen, um ihre Schande zu verbergen. Aber weißt du, wir Hinterwäldler halten zusammen! Das ist nicht das erste Mal! Wir haben sie gefunden, aufgewärmt, und dann wurde alles klar. Jetzt will ich Gerechtigkeit. Ich will nicht nur dem Gefreiten die Fresse polieren, sondern ihn auch vor der Familie zur Rechenschaft ziehen! Aber wir kamen nicht durch den Kontrollpunkt. Ich wurde wütend, verprügelte den Wachmann, und sie jagten mich weg. Jetzt weiß ich nicht mal, was ich tun soll.}

{119}{}{Ugh. Endlich hat sich wenigstens etwas geklärt. Also hat einer der Gefreiten deine Tochter vergewaltigt, du bist wütend geworden und hast den Streit am Kontrollpunkt angefangen. Stimmt's?}
{120}{}{Was hätte ich sonst tun sollen? Man ließ uns nicht rein, also bin ich ein bisschen ausgerastet. Wie auch immer, sie haben sich wahrscheinlich wieder beruhigt. Und ich bin auch müde. Ich schlafe diese Nacht und dann mach ich mich wieder ans Fressepolieren. Darauf kannst du dich verlassen.}
{121}{}{Könntest du mir mehr erzählen?}

#Âîïðîñû
{122}{}{Hä? Was ist? Na los, frag schon, sei nicht schüchtern. Sprich lauter, unter uns zu flüstern ist unhöflich.}

{123}{}{Entschuldige die Frage, aber wie alt ist deine Tochter?}
{124}{}{Sechzehn! Na und?}
{125}{}{Sei nicht so nervös. Es geht nur um den Altersunterschied ...}
{126}{}{Was zum Teufel willst du damit sagen!? Obwohl, ich weiß, worauf du hinauswillst, diese Sitten bei euch Stadtmenschen. Wir sind anders. Unsere Familien sind groß. Weißt du, wie viele Kinder ich habe? Sieben! Ich schwöre! Jedes Jahr bringt meine Frau noch ein Kind zur Welt, als hätte sie eine Kanone zwischen den Beinen – peng! Peng! Aber Christine ist unser letztes, mehr schaffen wir nicht. Und du solltest lieber fragen, wie alt MEINE FRAU ist! Ha-ha-ha-ha-hah!}
{127}{}{Äh, lieber nicht.}

{128}{}{Du hast etwas von Steuern gesagt?}
{129}{}{[Kratzt sich an der unrasierten Wange und zeigt, dass ihn das Thema nicht interessiert] Unser Dorf ist klein, nur ein paar Familien, wenn auch große. Und das Militär bewacht uns. Wenn was passiert, können wir um Hilfe rufen. Dafür geben wir ihnen etwas zu essen. [Spuckt aus] Keine große Sache.}
{130}{}{Wer hat deine Tochter vergewaltigt?}
{131}{}{Ein einfacher Soldat, er heißt Derren. Blöder Name und ein pickliger Bursche. Aber für uns reicht sogar das. Ich hab ihn gesehen – klebt am Posten und geht nirgendwohin. Ugh, wenn ich ihn in die Finger kriege!}
{132}{}{Und wie genau kam es zu der Vergewaltigung?}
{133}{}{Ich erzähl's dir, aber danach musst du dir die Ohren mit Seife waschen! Unser ganzes Dorf war im Zentrum versammelt, als die Militärs anrückten und ihre Wachen aufstellten. Beim Aufbruch fehlte plötzlich ihr Soldat Derren, bis ich ihn aus der Scheune kommen sah. Er kriegte einen Anschiss und zog ab, während Christine nirgends zu sehen war. Wir fanden sie eine Stunde später auf einer Klippe. So hatte ich sie noch nie gesehen – voller Blutergüsse, Blut und Tränen. Sie sagte, sie sei mit Derren in der Scheune gewesen, und meine Frau stellte fest, dass wir in neun Monaten ein neues Familienmitglied bekommen. So macht man das doch nicht! Also bin ich hier, um Gerechtigkeit zu fordern!}

#Original Text unten
#Musste gekürzt werden, da 900 Zeichen Maximum erreicht war.
#{133}{}{Ich erzähl's dir, aber danach musst du dir die Ohren mit Seife waschen! Wir hatten uns alle im Zentrum unseres Dorfes versammelt. Die Militärs rückten an, taten mächtig wichtig und stellten überall ihre Wachen auf. Und als es Zeit war aufzubrechen, verloren sie ihren Derren aus den Augen – er war einfach verschwunden! Dann seh ich ihn – der Mistkerl kommt aus der Scheune. Erst hab ich nicht verstanden, was passiert war. Er kassiert einen Anschiss und zieht mit den anderen ab. Und Christine? Nirgends zu sehen! Wir fanden sie eine Stunde später, weit weg, auf einer Klippe sitzend. So hatte ich sie noch nie gesehen. Blutergüsse, Blut und Tränen? Nein, so was gibt's bei uns nicht. Sie sagte nur, dass sie mit Derren in der Scheune gewesen war. Und dann war alles klar! Meine Frau untersucht sie und sagt, dass wir in neun Monaten ein neues Familienmitglied bekommen. Na, so macht man das doch nicht, oder? Also bin ich gekommen, um Gerechtigkeit zu fordern!}

{134}{}{Vielleicht habe ich genug Informationen. Pass auf dich auf.}

{135}{}{Hm, hör zu, Festus. Wenn sie nicht geschlagen und gefoltert wurde und nicht um Hilfe gerufen hat, dann gilt es nicht als Vergewaltigung. Es ist ... unschuldiger Teenagerkram. Ich spreche aus Erfahrung.}
{136}{}{WAS!? Wie du es auch nennst, ich werde alles tun, damit dieser Derren aus seinem Loch kommt und meine schöne Christine heiratet!!!}

{137}{}{Hättest du etwas dagegen, noch ein paar Fragen zu beantworten?}

{138}{}{Moment mal, sie wurde also nicht geschlagen, hat nicht um Hilfe gerufen und hat ihn sogar nach Namen und Rang gefragt?}
{139}{}{Na ja ... stimmt schon ... Ist doch egal!!! Ich werde alles tun, damit dieser Derren aus seinem Loch kommt und meine schöne Christine heiratet!!!}

{140}{}{Festus, ich glaube, du und deine Tochter solltet von hier verschwinden, so weit weg wie möglich.}
{141}{}{Warum?!}
{142}{}{Nur so ein Gefühl. Beantworte lieber ein paar Fragen.}
{143}{}{Na ja, äh, Derren hat die ganze Garnison gegen dich aufgehetzt. Sogar general Wesker ist dabei. Die halten zusammen, darauf kannst du dich verlassen.}
{144}{}{Weil ich dich sonst auf der Stelle erledige.}
{145}{}{Weil ich meine Freunde aus der Garnison rufe und sie dich ordentlich verprügeln werden.}

{146}{}{Ugh, du hast recht ... Da kommt nichts raus. Wie sollen wir mit denen fertigwerden? Und selbst die Karawanenhändler werden uns nicht helfen, wenn das Militär auftaucht. Wir müssen ins Dorf zurück.}
{147}{}{Gute Reise.}
{148}{}{Das ist doch nichts, Junge! Ich werd's ihnen zeigen! Ich hab Pulver für alle!}
{149}{}{In dem Fall mache ich dich hier und jetzt fertig.}
{150}{}{Na ja, ich bin hier, um dich zu warnen: Beim nächsten Mal bist du auf dich allein gestellt.}
{151}{}{Du weißt so viel über all diese Militärs, und das aus gutem Grund! Was für ein Abschaum du bist! Und deine Haut ist so weiß, als hätten deine Hände nie den Boden umgegraben. Na gut, na gut, ich versteh dich. Wir wollen unser Glück nicht länger herausfordern und gehen ins Dorf zurück. Aber wenn ich dich unterwegs erwische! Komm, Christine, wir finden anderswo einen Mann für dich.}
{152}{}{Jetzt reicht's! Ich gehe nirgendwohin, bevor ich Derren nicht dazu gebracht habe, meine Christine zu heiraten! ICH GEHE NICHT!}
{153}{}{Dann bist du selbst schuld. Mach's gut, Alter. [attack]}

#Female character
{1116}{}{Kommen wir gleich zur Sache - das gefällt mir! Wir werden uns prächtig verstehen, Mädchen. Halt nur dein Pulver trocken, wie ich immer sage, he-he! ...}
{1148}{}{Das ist doch nichts, Mädchen! Ich werd's ihnen zeigen! Ich hab Pulver für alle!}