{100}{}{Zellentür.}
{101}{}{Eine schwere Zellentür.}

#Ìàíèïóëÿöèè ñ äâåğüş êàìåğû
{103}{}{Die Zelle ist verschlossen.}
{104}{}{Die Zellentür ist mit einem riesigen Schloss verriegelt. Sie lässt sich nicht eintreten.}
{105}{}{Das Schloss wurde bereits geknackt.}
{106}{}{Na, das war ja gar nicht schwer!}
{107}{}{Du knackst das Schloss der Zellentür.}
{108}{}{Du kannst das Schloss nicht knacken.}
{109}{}{Fehlgeschlagen.}

#Äèàëîã ñ òşğåìíûì íàäçèğàòåëåì ïîñëå çàòî÷åíèÿ
{110}{}{Hey, du! Ruhe! Mach keinen Ärger, sitz deine 24 Stunden ab, dann kommst du unbeschadet wieder raus.}
{111}{}{Kannst du mir wenigstens sagen, was mir vorgeworfen wird?!}
{112}{}{Woher zum Teufel soll ich das wissen?}
{113}{}{Verdammt ...}

{114}{}{So, 24 Stunden sind um. Raus mit dir. Deine Sachen sind in dem Spind dort.}
{115}{}{Warte mal, Kumpel, ich will dich was fragen ... [Prepare to attack]}
{116}{}{Endlich!}

#Ïğî÷åå
{117}{}{Von dieser Seite lässt sich die Tür nicht aufschließen.}
{118}{}{Zu weit weg.}

#Female character:
{1115}{}{Warte mal, Kumpel, ich will dich was fragen ... [Prepare to attack]}
