{100}{}{Du siehst den Hauptcomputer.}
{101}{}{Du siehst den Zentralcomputer des Hauptquartiers.}

{102}{}{Als du den Schlüssel in den Anschluss steckst, hörst du ein schwaches Signal. Auf dem Monitor erscheint ein undeutliches Bild.}
{103}{}{Zugang gewährt.}

#List of questions
{110}{}{Zugriff gewährt. Verzeichnis auswählen.}
{111}{}{Verzeichnis auswählen.}
{112}{}{»Unsere Feinde«}
{113}{}{Örtliche Lage.}
{114}{}{Archiv des technischen Dienstes.}
{115}{}{Berichte des Gefängniswärters.}
{116}{}{Der Befehl zur Durchsuchung der Constitution.}
{117}{}{Arbeiten an der Entwicklung des Ortungssystems.}
{118}{}{}
{119}{}{[End session]}

{123}{}{[Zurück zur Liste]}

#Enemies
{130}{}{Die Feinde des Wind of War sind zahlreich, doch meist sind es Raiderbanden und jede Menge Mutanten – Taranteln und Aliens.}
{131}{}{Lies mehr über Raider.}
{132}{}{Lies mehr über Taranteln.}
{133}{}{Lies mehr über Aliens.}
{134}{}{Die Raiderbanden und andere Banditen, mit denen Wind of War um den Einfluss in der Region kämpft, sind gewöhnlich klein und umfassen 5 bis 15 Mann. Manche Banditen beherrschen kleine Siedlungen, deren Bewohner ihrer Unterdrückung überdrüssig sind und um Hilfe bitten.}
{135}{}{Räuberische Mutanten von enormer Größe, die an dunklen, feuchten Orten unter der Erde leben. Normalerweise kommen sie nachts an die Oberfläche. Gelegentlich fordern ihre Überfälle Opfer unter den Bewohnern von Wind of War, häufiger jedoch unter Fremden und Händlern, die sich in den Vororten aufhalten. Wind of War bekämpft die Kreaturen mit aller Kraft, doch ihre Zahl scheint sich nach jeder Begegnung wieder zu erholen. Es wurde festgestellt, dass die Mutanten in der Gegend des zerstörten örtlichen Vaults am aktivsten sind, doch mit jedem Jahr trifft man sie weiter davon entfernt an.}
{136}{}{Räuberische Mutanten mit Infrarotsicht. Wie Taranteln mögen sie kein Sonnenlicht und kommen lieber nachts an die Oberfläche, um tagsüber in dunklen Höhlen zu schlafen. Es ist sicher bekannt, dass sich das Hauptnest der Aliens auf einer Militärbasis im Norden befindet, der sogenannten „Area 51“.}

#Disposition
{137}{}{Rund um Wind of War gibt es, meist an den Hängen, kleine Siedlungen, gewöhnlich mit zwei oder drei Familien, die nicht von Interesse sind. Im Norden liegt die Militärbasis „Area 51“. Im Westen die Militärbasis „Hawthorne“. Zu den weiteren geografischen Orten gehört ein Vault in den Bergen im Nordwesten. Offenbar stammt die örtliche Bevölkerung aus diesem Vault.}
{138}{}{Notiere die Koordinaten des Vaults und begib dich in die Gegend.}
{139}{}{Notiere die Koordinaten der Basis Area 51.}
{140}{}{Notiere die Koordinaten von Hawthorne.}
{141}{}{Die Koordinaten stehen in deinem Pip-Boy.}

{142}{}{Der „Super-8“-Vorfall.}
{143}{}{Der Vorfall ereignete sich während des Transports der gefährlichen Fracht mit der Bezeichnung „Super 8“. Der Inhalt der Fracht wird in den Dokumenten nicht offengelegt. Bekannt ist, dass die Fracht wegen eines „Versäumnisses des Konvois“ verschwand und der Konvoi getötet wurde. Bald darauf wurde das Verschwinden von Bewohnern eines kleinen Dorfes in der Nähe gemeldet. Ihre sterblichen Überreste wurden in nicht weit entfernten Höhlen gefunden. Es ist unklar, wie diese Ereignisse zusammenhängen, doch eines ist fast sicher – „Super 8“ ist keine gewöhnliche Fracht.}

#Reports of the warden
{150}{}{Der Wind des Krieges schreckt auch vor Strafmaßnahmen nicht zurück. Hier wurden viele Raider und andere Verbrecher hingerichtet, um den Bewohnern Südn Nevadas als Abschreckung zu dienen.}
{151}{}{Sieh dir den Bericht über die aktuellen Gefangenen an.}
{152}{}{Sam Riley, 24 Jahre, männlich, Bewohner von Las Vegas. Hinrichtungsbefehl: Hände und Füße abschneiden, lebend an einem Zaun aufhängen. Grund für die Hinrichtung: Unser Geheimagent in Vegas erhielt Informationen über die Absichten des Gefangenen – er spionierte im Auftrag eines der angesehenen Bewohner der Stadt. Das Kommando wählte wie üblich den einfachsten Weg: den feindlichen Spion zu beseitigen.}

#Constitution
{160}{}{Es scheint, als glaube das Oberkommando des Stützpunkts wirklich an das alte Amerika und seine Werte. So wurde zum Beispiel den Karawanen befohlen, eine Kopie der Verfassung aus dem Museum in Reno zu beschaffen, zusammen mit US-Flaggen, Plakaten und allerlei militärischem Gerät aus der Vorkriegszeit. Schwer zu sagen, ob sich der Aufwand lohnt.}

#Blueprints
{170}{}{Der Computer zeigte eine Liste mit verschiedenen Bauplänen, technischen Daten und sonstigen technischen Unterlagen an. Das meiste davon ist für dich nutzlos, aber vielleicht findest du etwas Interessantes.}
{171}{}{[Nach den Bauplänen der Powerrüstung suchen]}
{172}{}{Die Datenbank enthält nur Baupläne der Rahmenkonstruktion. Baupläne der inneren Module der Rüstung sind nicht vorhanden.}
{173}{}{[Zurück]}

{174}{}{Leider ist der Zugriff auf die Baupläne durch ein sehr komplexes Passwort geschützt.}
{175}{}{[Versuchen, es zu knacken]}
{176}{}{Zugang gewährt.}
{177}{}{Ja! So macht man das!}
{178}{}{Du hast 350 EP für das Knacken des komplexen Passworts erhalten.}
{179}{}{Das übersteigt offenbar deine derzeitigen Fähigkeiten.}
{180}{}{[Zurück zum Hauptmenü]}
{181}{}{Kopiere alle verfügbaren Informationen auf die Diskette.}
{182}{}{Erledigt.}

{190}{}{Kopiere die Daten auf regulären Funkfrequenzen.}
