{100}{}{Du siehst eine Stromverteilungseinheit.}
{101}{}{Du siehst einen Verteiler, über den die Baracke mit Strom versorgt wird.}
{102}{}{Du siehst einen ungenutzten Stromverteiler.}

{103}{}{Dieser Verteiler brummt und versorgt die Baracke mit Strom.}
{104}{}{Dieser Verteiler ist bereits ausgeschaltet.}
{105}{}{Du betätigst den Schalter, und die Baracke wird nicht mehr mit Strom versorgt.}
{106}{}{Dir fehlt das technische Wissen, um den Verteiler auszuschalten.}
{107}{}{Bei Computern sollte man wissenschaftlich vorgehen, nicht bei Verteilern.}
{108}{}{Das hilft nicht, du musst technisch versierter sein.}
{109}{}{Das wird nicht helfen.}

{110}{}{Hey, wer hat das Licht ausgemacht!?}
{111}{}{Verdammt, schon wieder sind die Sicherungen durchgebrannt ...}
{112}{}{Ich habe Angst im Dunkeln ... Nur ein Scherz.}

{113}{}{Der Zeitpunkt für Sabotage ist ungünstig.}
{114}{}{*Skriptfehler*}
{115}{}{Beeil dich, Jesse!}
{116}{}{Das ist der Schlüssel zu einem Versteck in den Ruinen. Vielleicht kannst du ihn gebrauchen. Mach's gut!}
