#Стартовое сообщение при заходе на карту:
{100}{}{Du hast die Tankstelle gefunden, von der die Karawanenhдndler von Speed Hawk gesprochen haben.}

#Для триггера перехода на карту Ветра Войны:
{101}{}{Am Ausgang bemerkst du zahlreiche FuЯspuren. Vielleicht hat sich die Rдuberbande hier versammelt, um ihre Beute aufzuteilen. Die Spuren fьhren nach Westen.}
{102}{}{[Folge ihnen]}
{103}{}{[Ignorieren]}