{100}{}{Ein übel aussehendes Siedlungsgebiet. Es wäre wohl ratsam, ständig wachsam zu bleiben.}
{110}{}{Hey, du! Waffen sind hier nicht erlaubt!}
{111}{}{Hörst du mich? Steck deine Waffe weg!}
{112}{}{Du willst es wohl darauf anlegen, was?!}
{113}{}{Das ist deine letzte Warnung! Steck deine Waffe weg, oder ich schieße!}
{114}{}{ALARM! WIR WERDEN ANGEGRIFFEN!}

{115}{}{Damit habe ich nicht gerechnet!}
{116}{}{Jetzt verstehst du, warum der hiesige Mechaniker den Garageneingang so hektisch bewacht.}

{117}{}{Was ist das!?}
{118}{}{Hey! Das klingt, als käme das Geräusch eines laufenden Motors aus der Bahnhofsgarage!}