{100}{}{Du siehst einen Zugbegleiter.}
{101}{}{Du siehst deinen Zugbegleiter.}

#Òàéìåğ, ïëàâàşùèå ğåïëèêè
{105}{}{Wir müssen etwas langsamer fahren, sonst überhitzt die Turbine und wir müssen laufen.}
{106}{}{Na gut. Machen wir eine Pause.}
{107}{}{Ich gehe mal eine Toilette suchen.}
{108}{}{Na dann, ich sehe mich wohl in den Gebäuden um.}
{109}{}{::Leute, antworten. Ein Vogel sitzt im Käfig. Zeit mitzusingen::}
{110}{}{::Verstanden, Erster. Mache mich bereit::}
{111}{}{::Verstanden, Zweiter. Mache mich bereit::}
{112}{}{::Der Erste singt::}
{113}{}{::Der Zweite ist bereit::}
{114}{}{::Verstanden. Warte auf den Vogel. Ich komme zurück::}

#Âî âğåìÿ áîÿ
{115}{}{Ah! Verdammt! Stirb endlich!}
{116}{}{Du wolltest es doch so, oder?}
{117}{}{Idiot! Sie werden dich nicht in Ruhe lassen!}
{118}{}{Wovon redest du?!}
{119}{}{Die Regierung weiß alles über uns!! Sie werden dich finden!}
{120}{}{Das haben sie bereits, wie du siehst ...}
{121}{}{Hältst du dich für cool?! Stirb einfach!}
{122}{}{Auf keinen Fall!}
{123}{}{Das würde ich nicht tun, aber sie haben mich dazu gezwungen!}
{124}{}{Du lügst!}
{125}{}{Sprich! Wer hat den Befehl gegeben?}
{126}{}{Ich verrate es dir nicht!}

#Îòëàäêà
{150}{}{1}
{151}{}{2}
{152}{}{3}
{153}{}{4}
{154}{}{5}
{155}{}{6}