{100}{}{}
{101}{}{Du siehst deinen Zugbegleiter.}
{102}{}{Du siehst deinen Zugbegleiter.}

{103}{}{Ich bin hier, falls du mich brauchst.}
{104}{}{Warte auf mich.}
{105}{}{Oh, Scheiße! Du? Was zum Teufel?! Worauf hast du mich da bloß eingelassen?}
{106}{}{Beruhige dich. Wir haben keine Zeit, das zu klären. Gehen wir zurück zum Zug.}
{107}{}{Darum kümmern wir uns später. Bleib erst mal hier.}

{108}{}{Wenn ich so was noch mal mache!...}

{110}{}{Hey! Ist da jemand!}
{111}{}{Holt mich hier raus!}
{112}{}{Oh, Scheiße ...}
{113}{}{Verdammt, worauf habe ich mich da bloß eingelassen ...}
{114}{}{Wo ist mein Partner? ...}
{115}{}{Hey! Ist da jemand? Rettet mich!!}
{116}{}{Bin ich hier ganz allein?}
{117}{}{Lässt man mich wirklich hier drin zurück?}

#Æåíñêèå ğåïëèêè
{1105}{}{Oh, Scheiße! Du? Was zum Teufel?! Worauf hast du mich da bloß eingelassen?}
