{100}{}{}
{101}{}{Du siehst: den Seelenschnitter!}
{102}{}{Du siehst: den geheimnisvollen „Schnitter reiner Seelen“.}
{103}{}{Na, verdammt! Sieht aus, als wärst du in einen Hinterhalt geraten!}

#Damage regen
{104}{}{Oh, verdammt! Der Mistkerl hat seine verletzten Gliedmaßen irgendwie nachwachsen lassen!}
{105}{}{Hm ... Regeneration!!!}
{106}{}{Waaagh ... Regeneration!!!}
{107}{}{Meine Kraft schwindet ... Regeneration!!!}
{108}{}{Wie hat er das gemacht!? ...}

#Dialogue between Reaper and the Train Operator
{110}{}{Verdammt! Ich wusste, dass an diesem Auftrag etwas faul ist! Wirst du mich umbringen?}
{111}{}{Du interessierst mich nicht. Wo ist der Wanderer?}
{112}{}{Ich rede! Ich rede! ... Er ist zu dem Vault auf der anderen Seite der Brücke gegangen! Lass mich einfach gehen!}
{113}{}{Sperrt ihn ein!}
{114}{}{Aber ich habe euch doch alles gesagt!}
{115}{}{Beweg dich!}

{116}{}{Das ist der einzige Ausweg. Sichert alle Zugänge.}
{117}{}{Diesmal entkommt er nicht. Männer! Bezieht Stellung!}
{118}{}{Los! Los! Los! Doppelt marsch!!!}
{119}{}{Diesmal entkommt sie nicht. Männer! Bezieht Stellung!}

#Dialogue between Reaper and MC
{120}{}{Bürger, Sie haben Regierungsgelände betreten. Gehen Sie mit erhobenen Händen hinaus, oder wir eröffnen das Feuer.}
{121}{}{Wer zum Teufel bist du überhaupt!?}
{122}{}{Ich wiederhole: Widerstand ist zwecklos. Alle Ausgänge sind abgeschnitten. Wir lassen dich am Leben, wenn du deine Waffen niederlegst und mit erhobenen Händen herauskommst.}
{123}{}{(Reden wir vom Pech ...)}

{124}{}{Hey, warte mal, Großer! Lass uns darüber reden!}
{125}{}{Ich habe alles gesagt.}
{126}{}{Oh nein, du hast nicht gesagt, warum ich mich *lebend* ergeben sollte. Ich schätze, es hat etwas mit dem glänzenden Gerät aus meinem Vault zu tun. Du willst es, oder? Und du glaubst, ich hätte es bei mir. Was, wenn nicht? Wenn du mich tötest, wirst du es nie finden.}
{127}{}{Verdammt, ich muss nachdenken ...}

{128}{}{Hm. Du bluffst. Ich kann es in deinem Kopf hören.}
{129}{}{Hören? Irgendwie bezweifle ich das ...}

{130}{}{Ergib dich friedlich. Das wäre für alle besser. Eine Kugel in deinem Körper wird mich nicht daran hindern, die Informationen zu bekommen, die ich brauche. Es wird nur ... schmutziger.}
{131}{}{Ergib dich friedlich. Das wäre für alle besser. Eine Kugel in deinem Körper wird mich nicht daran hindern, die Informationen zu bekommen, die ich brauche. Es wird nur ... schmutziger.}
{132}{}{Zuerst will ich Antworten ... Reaper. Das ist dein Codename, oder?}
{133}{}{Ist das eine Drohung? Sieht so aus, als würdest du mich ohnehin töten. Na gut, ich denke darüber nach ...}

{134}{}{[Er schnaubt über deinen erbärmlichen Möchtegern-Hartmach-Auftritt] Frag.}
{135}{}{Wer bist du?}
{136}{}{Was machst du mit den sogenannten „reinen Körpern“?}
{137}{}{Warum brauchtest du den Aufseher?}
{138}{}{Wofür brauchst du das Gerät?}

{139}{}{Mein Rufzeichen ist Reaper of Souls. Mein richtiger Name ist Jason Bayham. Wie du siehst, haben dir die Antworten nichts gebracht.}
{140}{}{Ich nehme das Wertvollste. Der Rest geht für die Verpflegung der Wachen drauf.}
{141}{}{Er wusste, wie man das Gerät benutzt. Jetzt weiß ich es auch. Er hat seine Aufgabe erfuellt, und du bist hier. Es gibt nur noch eine Sache, die ich brauche, und die wirst du mir geben.}
{142}{}{Ich brauche die Daten, um Körper zu erschaffen. Diese Welt versinkt im Dreck. Die Menschheit muss sich weiterentwickeln.}
{143}{}{Du brauchst also einen Vorrat an reinen Körpern. Wofür? Um weiter zu experimentieren? Um Menschen nach deinem Gutdünken zu „formen“? Glaubst du, dass du darüber entscheiden darfst?}
{144}{}{Sieh mich an. Ich lebe schon viel länger als jeder andere. Ich bin etwas, das du nicht begreifen kannst. Die Zukunft. Die Besitzer dieses Vaults haben es nicht verstanden ... Aber ihre Beweggründe waren mir egal. Genauso wie deine. Hör jetzt auf, meine Zeit zu verschwenden.}

{165}{}{Du bist erbärmlich. Zeit, dem ein Ende zu setzen.}
{166}{}{Hey, wir haben doch gerade erst angefangen! ...}
{167}{}{Weißt du was, mir ist das egal. Fahr zur Hölle.}
{168}{}{Hör auf, meine Zeit zu verschwenden.}

{169}{}{Ich verstehe das nicht. Vielleicht sollte ich eine andere Frage stellen.}
{170}{}{Das klingt vernünftig ... Erzählst du mir noch etwas?}
{171}{}{Vielleicht tue ich's, vielleicht auch nicht. Ich frage lieber noch etwas anderes.}
{172}{}{Verdammt, das klingt tatsächlich fast überzeugend. Ich muss mehr erfahren.}
{173}{}{Was war das mit den Seelen? ...}

{174}{}{Du kannst es nicht verstehen. Du ... Du könntest einen Zweck erfuellen. Bis man dich aus deinem Vault geworfen hat.}
{175}{}{Welchen Zweck? Als Suppe für deine Schläger zu enden?}
{176}{}{Nein. Ein erbärmliches, wertloses Leben klammert sich an deinen Körper. Es bedeutet nichts. Du hättest etwas bewirken können. Du hättest helfen können, die Welt zu einem besseren Ort zu machen und das Leben künftiger Generationen zu retten. Aber jetzt bist du wertlos. Der Aufseher, die Regierung, der Biker, sogar du – ihr alle habt das Unvermeidliche nur hinausgezögert. Ein schwerer Fehler. Die Zeit ist um. Bringen wir es hinter uns.}
{177}{}{Was? Was soll das heißen!?}
{178}{}{Es ist so weit.}
{179}{}{Wovon redest du überhaupt!?}

#Female version:
#{112}{}{I'll talk! I'll talk! ... went towards that vault on the other side of the bridge! Just let me go!} #wrong replica
{1120}{}{Bürger, Sie haben Regierungsgelände betreten. Gehen Sie mit erhobenen Händen hinaus, oder wir eröffnen das Feuer.}
{1126}{}{Oh nein, du hast nicht gesagt, warum ich mich *lebend* ergeben sollte. Ich schätze, es hat etwas mit dem glänzenden Gerät aus meinem Vault zu tun. Du willst es, oder? Und du glaubst, ich hätte es bei mir. Was, wenn nicht? Wenn du mich tötest, wirst du es nie finden.}
