{100}{}{Du siehst ein Gefäß voller Flüssigkeit.}
{101}{}{Du siehst ein Gefäß, in dem sich der abgetrennte Kopf befindet.}
{102}{}{Du siehst einen Tank mit dem abgetrennten Kopf des ehemaligen Präsidenten der Vereinigten Staaten von Amerika. Überrascht?}

{103}{}{Weg von meinem Schatz, du!}

{104}{}{*Schnarch*}
{105}{}{Etwas blockiert die Konsole!}
{106}{}{Nichts Brauchbares.}
{107}{}{Du hast gesiegt!}
{108}{}{Du solltest dich besser beeilen und hier verschwinden.}
{109}{}{Was zum ...}
{110}{}{Scheiße!!!}

#Âòîğîé äèàëîã ïîñëå ïîáåäû íàä òóğåëÿìè:
{111}{}{[Vor dir ist ein Kopf, aus dessen Oberkiefer Drähte herausragen. Er starrt dich wortlos mit einem Auge an und wartet.]}
{112}{}{Du hast versprochen, mir nichts anzutun. Warum hast du dein Wort nicht gehalten? Ich habe dir vertraut!}
{113}{}{[Der Kopf schweigt.]}
{114}{}{Hey, tu nicht so, als könntest du mich nicht hören!}
{115}{}{Wir ... [weinend] Mister hat Unrecht!}
{116}{}{Ach ja? Warum?!}
{117}{}{Mein Kostbarer und ich wollten immer nur das Gute und für Gerechtigkeit kämpfen. Wir wollten das nicht! Wir schwören es! Es war ein Unfall! Es wird nie wieder vorkommen!}
{118}{}{Natürlich wird es nie wieder vorkommen, denn die Geschütztürme sind zerstört.}
{119}{}{Wir wollten das nicht! Wir haben es nicht so gemeint!! Mister soll uns vergeben! Ich verlange, dass Mister uns vergibt!}
{120}{}{Das ist eine gute Idee. Aber woher soll ich wissen, dass ihr mich nicht umbringt, wenn ich durch diese Tür hinausgehe, hinter der die Geschütztürme noch funktionieren?}
{121}{}{Sie handeln auf eigene Faust! Wir sind es nicht! Ehrliches Präsidentenwort!}
{122}{}{Ja?}
{123}{}{Ja! Ja! Sie wollten Mister ganz allein umbringen! Und wir wollten das nicht!}
{124}{}{Lass gut sein. Du wolltest mich DOCH umbringen, oder?}

{125}{}{Mister soll uns vergeben! Wir haben nur gescherzt! Wir würden das niemals wirklich tun! Irgendwie mögen die anderen unsere Witze nicht. Haben sie noch nie! Warum ...}
{126}{}{Na gut, ich vergebe euch. Vergessen wir die Vergangenheit, ja?}
{127}{}{Ich glaube dir nicht. Mach jetzt die große Tür auf, damit ich hier verdammt noch mal rauskomme!}
{128}{}{Ich muss nachdenken. Ich komme bald wieder und teile dir meine Entscheidung mit.}
{129}{}{}

#ÏÎËÎÆÈÒÅËÜÍÛÅ ĞÅÏËÈÊÈ [ïîñëå îòâåòà 126]:
{130}{}{Was sagt er, Kostbarer? Ohhhh ... Mister ist sehr weise und sehr höflich! Mister President mag Mister! Ah! Wenn doch nur alle Untergebenen so wären, nicht wahr, Kostbarer?!}
{131}{}{Was meinst du? Wurdest du schlecht behandelt?}
{132}{}{Mr. President möchte sich nicht an die Vergangenheit erinnern. Sie ist eine schlechte Erinnerung. Aber der Kostbare erinnert sich, wie grausam der Präsident beim letzten Mal behandelt wurde! Sie brachten ihn in aller Öffentlichkeit zum Weinen! Vor all seinen Untergebenen! Mister hat noch nie einen so erbärmlichen Anblick gesehen!}

#ÏÎËÎÆÈÒÅËÜÍÛÅ ĞÅÏËÈÊÈ, ïåğâàÿ ôğàçà, èñòîğèÿ [ïîñëå 132]:
{133}{}{Darf der Kostbare erzählen, warum Mister President hier ist und nicht auf seinem rechtmäßigen Posten?}
{134}{}{Kostbarer, willst du es Mister nicht erzählen? Ja, Mister muss es nicht wissen. Aber vielleicht hätte Mister gern eine Tasse Tee? Nein, mein Kostbarer, wir haben keine Zeit für eine Teegesellschaft. Erinnerst du dich, wie alle Cola missbraucht haben? Alle Zungen wurden blau. Es war so hässlich!}
{135}{}{Was hat Nuka-Cola mit irgendetwas zu tun?}

{136}{}{Ruhe! Der Mister darf die Rede des Präsidenten nicht unterbrechen! Wo hat der Mister denn seine Manieren?!}
{137}{}{Schluss jetzt, Schädel, genug mit dem Unsinn! Mach verdammt noch mal die Tür auf!!}
{138}{}{Oh, entschuldige. Mach weiter.}

{139}{}{Sie wussten nicht, wie gefährlich diese Flüssigkeit war! Sie dachten, sie würden nur von schlechten Erinnerungen und Zweifeln geplagt, aber es war etwas anderes. Sie glaubten, alles unter Kontrolle zu haben! Hahaha! Precious erinnert sich daran, wie wir über ihre Naivität gelacht haben.}
{140}{}{Naivität? Wieso? Was hatte es mit der Flüssigkeit auf sich?}
{141}{}{Ih! Der Mister will es wissen! Aber dürfen wir es ihm sagen? Ja, jetzt, da all die albernen Leute unsere Wohnung verlassen haben, können wir dem Mister vielleicht die Wahrheit sagen.}
{142}{}{Natürlich. Ich höre zu.}
{143}{}{Sie dachten, Cola sei harmlos. Aber ihr Vorrat war etwas Besonderes. Dieser Vorrat ... ähm ... Dieser Vorrat sollte ihr Zentralnervensystem und ihre Gehirnaktivität anregen. Ja.}
{144}{}{Interessant. Die Cola hat sie also ängstlicher gemacht?}
{145}{}{Ooooh, ja! Der Mister hat richtig geraten. Aber die Cola hat ihren Gefühlszustand nicht einfach nur verstärkt, sondern *gezielt*. Es dauerte eine Weile, aber als das Gift tiefer in sie eingedrungen war, konnten sie nicht mehr aufhören ... Sie wurden wahnsinnig! Sie kämpften, schrien, schlugen mit Stühlen aufeinander ein, und nachdem wir den Zugang zur Cola eingeschränkt hatten, rasteten sie noch mehr aus und fingen an, sich gegenseitig umzubringen.}
{146}{}{Haben sie dir wehgetan? Haben sie den Präsidenten verprügelt?}
{147}{}{[Klagend] Mister President möchte sich nicht daran erinnern, wie er verprügelt wurde.}
{148}{}{Also haben sie es getan. Ist das der Grund, warum du so bist?}
{149}{}{Jaaa. Seitdem sind wir so. Precious ist auch seit jenem Tag bei uns. Wir galten als zu wichtig, um in den Muelleimer geworfen zu werden. Der Doktor, unser guter Freund, hat uns wieder zusammengebaut und zum Leben erweckt.}
{150}{}{Wahrscheinlich aus gutem Grund. Und warum, sagst du, habt ihr über ihre Naivität gelacht? Weil ihr von Anfang an wusstet, dass die Bewohner des Vaults Versuchspersonen waren?}
{151}{}{Sie dachten, sie wären diejenigen, die die Experimente durchführten. Aber tatsächlich wurde auch an ihnen experimentiert.}
{152}{}{Sie haben die Experimente durchgeführt ... Heißt das, dass auch in anderen Vaults irgendwelche Experimente durchgeführt wurden?}
{153}{}{Wie hat Mister davon erfahren, mein Schatz? Ist Mister irgendwie mit geheimen Regierungskreisen verbunden?}
{154}{}{Was? Nein. Betrachte es als glücklichen Zufall. In meinem Vault geht auch etwas Ungewöhnliches vor sich.}
{155}{}{Wieder einmal wurde Mister Präsident nicht benachrichtigt! Wie soll man mit solchen Untergebenen überhaupt arbeiten?!}
{156}{}{Na schön. Wie wäre es, wenn ich jetzt deine Untergebenen bestrafe, damit sie sich in Zukunft benehmen?}
{157}{}{Oh, Mister will unsere Wohnung verlassen? So bald schon? Warum so bald?}
{158}{}{Weil meine Familie und meine Mitbürger auf mich warten. Ich muss zu ihnen zurück, sonst wird mein Zuhause den Angriffen der vielen mutierten Tiere und Raider zum Opfer fallen. Es ist meine Bürgerpflicht. Schließlich soll Mister Präsident für sein Volk sorgen. Er lässt es doch nicht sterben, oder?}
{159}{}{Nein, nein, nein!!! Schatz sagt, Mister versucht, uns zu verwirren! Bringt Mister zum Schweigen!!! Bringt ihn dazu, aufzuhören!!!}
{160}{}{Komm schon! Ich MUSS gehen! Das Wohl meines Volkes hängt davon ab, ebenso wie deins und meins.}
{161}{}{HALT DEN MUND!!! ICH WILL DAS NICHT!!! SEI STILL!!! [schluchzt] Mister ist sehr grausam! Mister soll unsere Wohnung verlassen. Wir wollen ihm nicht länger zuhören!}
{162}{}{Na gut.}

#ÏÎËÎÆÈÒÅËÜÍÛÅ ĞÅÏËÈÊÈ, âòîğàÿ ôğàçà, õî÷åò óéòè [ïîñëå 132]:
{163}{}{Mister will nicht sehen. Mister will nur von hier weg.}
{164}{}{Aber ... [sieht verwirrt aus] Aber ... Ist Mister unsere Gesellschaft leid? Warum will Mister so schnell gehen?}
{165}{}{Weil mein Volk auf mich wartet – meine Familie, meine Mitbürger. Ich muss zu ihnen zurück, sonst wird mein Zuhause den Angriffen der vielen mutierten Tiere und Raider zum Opfer fallen. Es ist meine Bürgerpflicht.}
{166}{}{Bürgerpflicht? Mister President hat schon vergessen, was Bürgerpflicht ist ... Oh ...}
{167}{}{Erinnert sich Mister Präsident an seine Nationalhymne?}
{168}{}{Nein. Mister President erinnert sich nicht! Er erinnert sich nicht!!!}
{169}{}{Was ist auf Amerikas Nationalflagge abgebildet?}
{170}{}{Mister President ERINNERT SICH NICHT!!!}
{171}{}{Ja, Herr Präsident hat vieles vergessen. Vielleicht ist es an der Zeit, nach draußen zu kommen und sich die Welt anzusehen, wie sie jetzt ist?}
{172}{}{NEIN, NEIN, NEIN!!! Precious sagt, Mister versucht, uns zu verwirren! Bring Mister zum Schweigen!!! Wir kommen nicht raus, Mister kommt nicht raus! Draußen ist es gefährlich!!! Gefährlich!!!}
{173}{}{Ja, ja, ja!!! Herr Präsident will nach draußen gehen! Er will es sehen! Ja! Mister wird Herrn Präsidenten helfen, stimmt's?}
{174}{}{Will Herr Präsident sich erinnern? Vielleicht können wir den Text der Hymne im Vault-Netzwerk nachschlagen und sie zusammen singen?}
{175}{}{NEIN, NEIN, NEIN!!! Precious sagt, Mister versucht, uns zu verwirren! Bring Mister zum Schweigen!!! Ruhe!!!}
{176}{}{Ja, ja, ja!!! Mister President will sich erinnern! Achtung!! Aufstehen! Köpfe hoch! Heimatland!! Amerika wieder groß machen!! Aber... Was?.. Nein!! Precious sagt, Mister versucht, uns zu verwirren! Bring Mister zum Schweigen!!! Ruhe!!!}
{177}{}{Aber Sie erinnern sich noch an die Tage, als Sie ein Mensch waren. Sie haben Ihre Menschlichkeit nicht völlig verloren, selbst nach Ihrer Tragödie. Erinnern Sie sich an Ihre Pflichten, lassen Sie mich gehen, Ihrem Land und Ihrem Volk zuliebe. Für die Sie gekämpft und für die Sie gelitten haben.}
{178}{}{HALT DEN MUND!!! ICH WILL DAS NICHT!!! SEI STILL!!! [schluchzt] Mister ist sehr grausam! Mister soll unsere Wohnung verlassen. Wir wollen ihm nicht länger zuhören!}
{179}{}{Na gut.}
{180}{}{Nun, vielleicht erinnert sich Herr Präsident an seine Pflicht als Präsident und lässt seinen Diener gehen?}
{181}{}{Herr Präsident erinnert sich an Ehre... Freiheit... Unabhängigkeit...}
{182}{}{Nun?}
{183}{}{NEIN, NEIN, NEIN!!! Precious sagt, Mister versucht, uns zu verwirren! Bring Mister zum Schweigen!!! Ruhe!!!}
{184}{}{HALT DEN MUND!!! ICH WILL DAS NICHT!!! SEI STILL!!! [schluchzt] Mister ist sehr grausam! Mister soll unsere Wohnung verlassen. Wir wollen ihm nicht länger zuhören!}
{185}{}{Na gut.}

#ÍÅÃÀÒÈÂÍÛÅ ĞÅÏËÈÊÈ, íà÷àëî:
{186}{}{Was sagt er, Precious? Ooooh... Mister will unsere Gastfreundschaft nicht annehmen. Und wie würde Mister sich wohl über ein kleines Boom in Korea fühlen? Was, Precious? Ach ja... Uns sind die Bomben ausgegangen... Na gut. Wir beantragen beim Rat, die Türen abzuschließen und den unhöflichen Mister hier bei uns zurückzulassen... FÜR IMMER!!! [weint] Wir möchten so gern eine kubanische Zigarre rauchen... Nicht wahr, Precious? Soll uns jemand eine Zigarre holen!}
{187}{}{Ist das also so? Was, wenn ich dich einfach umbringe?}
{188}{}{Ugh!!! Haha! Mister hat einen Witz gemacht! Der hat uns wirklich gefallen, nicht wahr, Precious?!}
{189}{}{Mister ist wütend über dein Gestammel! Öffne das Tor, oder ich zerschlage dieses Glas!}
{190}{}{Wow! Mister ist wütend! Wir mochten solche sturen Misters schon immer.}
{191}{}{Hör auf mit deinem Geschwätz, du Schädel!}
{192}{}{AH-ha-HA-HAH!!!}
{193}{}{[Er lässt dich nicht einfach gehen. Du brauchst ein überzeugendes Argument.]}

#ÍÅÃÀÒÈÂÍÛÅ ĞÅÏËÈÊÈ, ïåğâàÿ âîçìîæíîñòü - äèíàìèò:
{194}{}{Genug!!! Ich lege das Dynamit genau hier hin, und dann bekommst du endlich frische Luft!}
{195}{}{Äh? [Sein einsames Auge starrt ängstlich auf dein Dynamit.] Mister macht doch nur Spaß, oder? Mister macht nur Spaß! Das ist keine echte Bombe! Mister soll sie woanders zünden! Wir befehlen es ihm! Wir legen ein Veto gegen Misters Entscheidung ein!}
{196}{}{Dummer Kopf, du kannst gegen nichts ein Veto einlegen. Nicht mehr. [das Dynamit weiter platzieren]}
{197}{}{Aber ... Precious, was sollen wir tun? Mister macht keinen Spaß! Mister wurde befohlen, uns zu ermorden! Vielleicht akzeptiert Mister ein Gegenangebot? 50% mehr als der Betrag! Wir machen auch keinen Spaß, Mister.}
{198}{}{Hm. Klingt interessant.}
{199}{}{Wir haben Geld. Wir bezahlen Mister, wenn er das rote Ding in diesen Behälter legt.}
{200}{}{Ich mache es, wenn du mir 1.000.000 zahlst.}
{201}{}{Ich mache es, wenn du mir 500.000 zahlst.}
{202}{}{Ich mache es, wenn du mir 50.000 zahlst.}
{203}{}{Ich mache es, wenn du mir 5.000 zahlst.}
{204}{}{Jeeee-haaa! Wir haben Mister reingelegt! Ha-ha!!! Mister ist ein Trottel! Ist Mister vielleicht aus Kanada? Wie auch immer. Wachen! Bringt unseren Gast zur Tür!}
{205}{}{Hey! Ich bin wirklich von einem abgetrennten Kopf hereingelegt worden!}
{206}{}{Ich habe deinen Unsinn satt. Ich zünde die Bombe.}
{207}{}{Nein! Mister soll sich nicht beeilen! Wir müssen nachdenken! Precious will auch nachdenken!}
{208}{}{Du hast keine Zeit. Entscheide dich: Entweder du öffnest diese Tür, oder ich sprenge dich in die Luft und du kannst sie nicht mehr kontrollieren.}
{209}{}{[Ignoriere den Kopf und starte den Timer]}
{210}{}{Na gut. Wir entscheiden uns. Wir befehlen gemeinsam mit Precious, dass die Tür geöffnet wird. Ja. Mister soll sein rotes Ding nehmen und verschwinden ... [stöhnt]}
{211}{}{Das war's, ich gehe.}

#ÍÅÃÀÒÈÂÍÛÅ ĞÅÏËÈÊÈ, âòîğàÿ âîçìîæíîñòü - ïğîâîäà:
{212}{}{Ich mache etwas anderes. Ich öffne diese Kiste und ziehe ein paar Drähte heraus.}
{213}{}{Was? Aber ... Aber ... Precious, darf Mister an dieser Kiste mit den Drähten herumfummeln?}
{214}{}{Nein. Aber wie du siehst, mache ich es trotzdem.}
{215}{}{Mister kann uns nichts tun! Mister hat kein Recht dazu!}
{216}{}{Vielleicht. Aber das ist mir egal.}
{217}{}{Arrgh ... Wir sind der Präsident! Uns darf man nicht wehtun!}
{218}{}{Ja. [Öffne den Controller]}
{219}{}{Schatz, Mister unterliegt nicht unseren Gesetzen! Was sollen wir tun?!}
{220}{}{[Reiße ein paar unscheinbare Drähte heraus]}
{221}{}{Au, au, au, au!!! Mister darf das nicht tun!}
{222}{}{[Schließe ein paar Drähte kurz]}
{223}{}{Ughh!! Mister tut uns sehr weh!}
{224}{}{[Mach es noch einmal]}
{225}{}{Nein! Mister muss aufhören!}
{226}{}{[Mach es noch einmal]}
{227}{}{AHHH! Bringt Mister dazu aufzuhören! Hört auf!!!}
{228}{}{[Reiße den Schlauch mit der Nährflüssigkeit heraus]}
{229}{}{[Verursache einen stärkeren Kurzschluss]}
{230}{}{Wenn du die Tür nicht öffnest, werde ich dich weiter quälen.}
{231}{}{Mister ist sehr grausam! Wir haben so viel Gutes getan, aber Mister tut uns weh! Schatz, das ist nicht fair! [weint]}
{232}{}{Halt die Klappe und öffne die Tür!}
{233}{}{[Verursache erneut einen Kurzschluss, diesmal stärker]}
{234}{}{NEIN!!! NEIN!!! MOTHERF-!!! ... [Es scheint, als hätte das Gehirn des armen Kerls das nicht verkraftet.]}

#ÍÅÃÀÒÈÂÍÛÅ ĞÅÏËÈÊÈ, òğåòüÿ âîçìîæíîñòü - êóêëà:
{235}{}{Nein! Der Präsident ist gegen aggressive Maßnahmen! Der Präsident besteht auf einer friedlichen Lösung des Problems!}
{236}{}{Ich bestehe auch auf einer friedlichen Lösung. Also, lässt du mich vielleicht friedlich gehen?}
{237}{}{Nein, Mister hat seine Pflichten als Bürger noch nicht erfuellt. Mister kann nicht einfach verschwinden. Mister President ist nicht in der Stimmung. Nein.}
{238}{}{Jetzt reiße ich ihm das linke Bein ab.}
{239}{}{NEEEEIN!!! Der Präsident vermisst seinen Schatz! Tu dem Schatz nicht weh! Mein Schatz! Mein Schatz! Halt durch! Die Polizei ist unterwegs!}
{240}{}{Du Idiot, gleich fliegt das Bein deines Schatzes in die hinterste Ecke des Zimmers!}
{241}{}{NEIIIN!!! Warum ist Mister so grausam! Warum?!! Precious und ich waren all die Jahre über eng miteinander verbunden! Niemand war mir je so nahe! Möge Mister Vernunft zeigen und Precious zurückbringen! Der Präsident würde sogar auf die Knie gehen, wenn er welche hätte! Ehrlich!}
{242}{}{[Die Puppe zerreißen und die Fetzen in alle Richtungen werfen]}
{243}{}{NEIN!!! NEIN!!! MOTHERF-!!! ... [Es scheint, als hätte das Gehirn des armen Kerls das nicht verkraftet.]}
{244}{}{Nun, welche Entscheidung trifft der Präsident in dieser schwierigen Lage? Wäre es nicht besser, zu seinem eigenen Wohl auf einen Gast zu verzichten?}
{245}{}{Ja!!! Mister hat recht!! Wir lassen Mister gehen, aber Precious muss hierbleiben!!!}
{246}{}{}
{247}{}{[Zurücktreten und zusehen]}
{248}{}{Ich glaube, das ist die Puppe des Herrn Präsidenten. Was, wenn ich ihr ein paar Gliedmaßen abreiße?}
{249}{}{}

{250}{}{AAAAHHHA-HA-HA-HA!!! Willkommen in unseren Gemächern, Mister! Entschuldigen Sie, dass wir keine Uniform tragen, wir haben nichts, worauf wir sie anziehen könnten! Vielleicht könnte Mister uns mit einer Feder kitzeln, hm?}
{251}{}{Was zum... Ein sprechender Kopf?! Bist du... lebendig?}
{252}{}{Mister ist ein IDIOT!!! Ich bin nicht einfach nur ein sprechender Kopf! Vor dir steht der Herr Präsident höchstpersönlich! Wo ist dieser Mister nur hergekrochen, wenn er den Präsidenten nicht von allen anderen unterscheiden kann?!... Was, mein Precious? Aus dem Arsch?!!! Mein Precious, du solltest Manieren lernen!}
{253}{}{Na, das ist mal was Neues.}
{254}{}{Was sagst du da, mein Precious?! Ja, wir stimmen zu. Solche Misters sollte man vierteilen. Alle, die aus dem Arsch kommen, müssen ausgerottet werden!!!}
{255}{}{Bist du dir da sicher?}
{256}{}{Was? Was sagt er? Will er uns Angst machen? Na gut. Dann soll dieser Bürger herauskommen und sich auf meinen Klingelknopf stützen... Ich meine... Ich meine, meinen Finger. Was, mein Precious? Ich habe keinen Finger? Na ja... Dann soll er sich auf irgendetwas von mir stützen. Mister soll herauskommen. Wir tun ihm nichts.}
{257}{}{Versprichst du das? Kann ich dir vertrauen?}
{258}{}{Ja, ja, JA!!! Wir sind ganz lieb! Lass Mister nur näher kommen! Wir haben schon so lange niemanden mehr gesehen! Wir wollen Mister sehen!}
{259}{}{Hmm ...}

{260}{}{Du hast einen heftigen Stromschlag abbekommen. Das ist das Werk des Kopfes!}
{261}{}{Ah! Verdammt!!!}
{262}{}{Und trotzdem hast du geschafft, was du vorhattest!}
{263}{}{Ein kaputter Panzer.}
{264}{}{Alles, was vom früheren Präsidenten übrig ist – kleine grüne Stückchen Gehirn und Fleisch.}

{270}{}{Herr Präsident, an der Oberfläche ist das Leben inzwischen ganz normal. Es drohen keine Bomben mehr, und die Strahlenwerte sind durchaus erträglich. Sie haben nichts zu befürchten!}
{271}{}{Du verwöhntes kleines ...}
{272}{}{Aber ... Wie können wir diesen zweifelhaften Worten trauen?!}
{273}{}{Allein schon deshalb, weil hier ein Mensch aus der Außenwelt vor euch steht, der mühelos durch die Eingangstür gekommen ist. Ist das kein Beweis?}
{274}{}{Oh, stimmt ... Aber wir sind immer noch nicht sicher. Und ... Warum müssen wir nach draußen?}
{275}{}{Willst du dir die Außenwelt nicht einmal ansehen? Nur ein einziges Mal? Hör zu, wenn sie dir nicht gefällt, kannst du jederzeit zurückkommen. Das ist ganz einfach!}
{276}{}{Hahaha!! Der Herr hat recht! Und du, mein Schatz, was sagst du? Möchte mein Schatz auch die Außenwelt sehen? Ja, wir machen es!! Wir werden sie sehen, wir werden mutig sein!!}
{277}{}{Was für eine Entschlossenheit!}
{278}{}{Also gut! Berater! WIR VERKÜNDEN FEIERLICH DIE ÖFFNUNG DES REGIERUNGSBUNKERS UND DEN BEGINN DES WIEDERAUFBAUS DER AMERIKANISCHEN GESELLSCHAFT NACH DEM ATOMKRIEG! Leitet die Verfahren der Sarkophag-Direktive ein!}
{279}{}{Klingt cool. Lieber einen Schritt zurücktreten und zusehen ...}

{280}{}{Meine Damen und Herren! Es ist Zeit, unsere Ärsche von den Monitoren hochzukriegen! IM NAMEN AMERIKAS!!!}
{281}{}{Du kannst den Kopf davon überzeugen, an die Oberfläche zu gehen! Wohin wird er nun gehen?}
{282}{}{Also gut!! Jetzt stecke ich dieses Cordex hier rein, und ihr bekommt frische Luft!!!}

#Female character
{1108}{}{Du solltest dich besser beeilen und hier verschwinden.}
{1112}{}{Du hast versprochen, mir nichts anzutun. Warum hast du dein Wort nicht gehalten? Ich habe dir vertraut!}
{1115}{}{Wir ... [weint] Miss hat nicht recht!}
{1119}{}{Wir wollten das nicht! Wir haben es nicht so gemeint!! Miss soll uns verzeihen! Ich verlange, dass Miss uns verzeiht!}
{1123}{}{Ja! Ja! Sie selbst wollten Miss töten! Und wir wollten das nicht!}
{1125}{}{Miss soll uns verzeihen! Wir haben nur Spaß gemacht! Wir würden das niemals wirklich tun! Die anderen mögen unsere Witze irgendwie nicht. Haben sie noch nie! Warum ...}
{1127}{}{Ich glaube dir nicht. Mach jetzt die große Tür auf, damit ich hier verdammt noch mal rauskomme!}
{1130}{}{Was sagt sie, mein Schatz? Ohhhh ... Miss ist sehr weise und sehr höflich! Mister President mag Miss! Ah! Wenn doch nur alle Untergebenen so wären, stimmt's, mein Schatz?!}
{1132}{}{Der Präsident möchte sich nicht an die Vergangenheit erinnern. Es ist eine schlimme Erinnerung. Aber Precious erinnert sich daran, wie grausam der Präsident letztes Mal behandelt wurde! Sie haben ihn in der Öffentlichkeit zum Weinen gebracht! Vor all seinen Untergebenen! Miss hat noch nie einen so erbärmlichen Anblick gesehen!}
{1134}{}{Precious, willst du es Miss nicht erzählen? Ja, Miss muss es nicht wissen. Aber vielleicht hätte Miss gern eine Tasse Tee? Nein, mein Precious, wir haben keine Zeit für eine Teegesellschaft. Erinnerst du dich, wie alle Cola missbraucht haben? Allen wurden die Zungen blau. Es war so hässlich!}
{1136}{}{Still! Miss darf die Rede des Präsidenten nicht unterbrechen! Wo ist Miss' Anstand?!}
{1141}{}{Îh! Miss will es wissen! Aber können wir es ihr sagen? Ja, jetzt, da all diese dummen Leute unsere Wohnung verlassen haben, können wir Miss vielleicht die Wahrheit sagen.}
{1145}{}{Oooh, ja! Miss hat richtig geraten. Aber Cola hat ihren emotionalen Zustand nicht einfach nur verstärkt, sondern gezielt bestimmte Gefühle verstärkt. Es dauerte eine Weile, aber als das Gift tiefer eingedrungen war, konnten sie nicht mehr aufhören ... Sie wurden wahnsinnig! Sie kämpften, schrien, schlugen mit Stühlen aufeinander ein, und als wir den Zugang zu Cola einschränkten, flippten sie noch mehr aus und fingen an, einander umzubringen.}
{1153}{}{Wie hat Miss das herausgefunden, Precious? Hat Miss etwa Verbindungen zu geheimen Regierungskreisen?}
{1157}{}{Oh, Miss möchte unsere Wohnung verlassen? So bald schon? Warum so bald?}
{1159}{}{Nein, nein, nein!!! Precious sagt, Miss versucht, uns zu verwirren! Bringt Miss zum Schweigen!!! Bringt sie zum Schweigen!!!}
{1161}{}{HALT DEN MUND!!! ICH WILL DAS NICHT!!! SEI STILL!!! [schluchzt] Miss ist sehr grausam! Lasst Miss unsere Wohnung verlassen. Wir wollen ihr nicht länger zuhören!}
{1163}{}{Miss will nichts sehen. Miss will einfach nur von hier weg.}
{1164}{}{Aber ... [wirkt verwirrt] Aber ... Ist Miss unsere Gesellschaft leid? Warum möchte Miss so schnell gehen?}
{1172}{}{NEIN, NEIN, NEIN!!! Draußen ist es gefährlich! Precious sagt, Miss versucht, uns zu verwirren! Bringt Miss zum Schweigen!!! Still!!! Wir kommen nicht raus, Miss kommt nicht raus! Da draußen ist es gefährlich!!! Gefährlich!!!}
{1173}{}{Ja, ja, ja!!! Der Präsident möchte nach draußen gehen! Er will es sehen! Ja! Miss wird dem Präsidenten helfen, oder?}
{1175}{}{NEIN, NEIN, NEIN!!! Precious sagt, Miss versucht, uns zu verwirren! Bringt Miss zum Schweigen!!! Still!!!}
{1176}{}{Ja, ja, ja!!! Mister President will sich erinnern! Achtung!! Erhebt euch! Köpfe hoch! Heimatland!! Amerika wieder groß machen!! Aber... Was?.. Nein!! Precious sagt, Miss versucht, uns zu verwirren! Miss soll den Mund halten!!! Ruhe!!!}
{1178}{}{HALT DEN MUND!!! ICH WILL DAS NICHT!!! SEI STILL!!! [schluchzt] Miss ist sehr grausam! Lasst Miss unsere Wohnung verlassen. Wir wollen ihr nicht länger zuhören!}
{1183}{}{NEIN, NEIN, NEIN!!! Precious sagt, Miss versucht, uns zu verwirren! Bringt Miss zum Schweigen!!! Still!!!}
{1184}{}{HALT DEN MUND!!! ICH WILL DAS NICHT!!! SEI STILL!!! [schluchzt] Miss ist sehr grausam! Lasst Miss unsere Wohnung verlassen. Wir wollen ihr nicht länger zuhören!}
{1186}{}{Was sagt sie, Precious? Oooh... Miss will unsere Gastfreundschaft nicht annehmen. Und wie würde Miss sich wohl über einen kleinen Knall in Korea fühlen? Was, Precious? Ah, ja... Wir haben keine Bomben mehr... Na ja. Wir beantragen beim Rat, die Türen zu verriegeln und die unhöfliche Miss hier bei uns zu lassen... FÜR IMMER!!! [weint] Wir wollen so schrecklich gern eine kubanische Zigarre rauchen... Nicht wahr, Precious? Soll uns jemand eine Zigarre besorgen!}
{1188}{}{Ugh!!! Hahaha! Miss hat einen Witz gemacht! Der hat uns wirklich gefallen, nicht wahr, Precious?!}
{1189}{}{Miss ist wütend über dein Gemurmel! Öffne das Tor, oder ich zerschlage dieses Glas!}
{1190}{}{Wow! Miss ist wütend! Solche sturen Misses mochten wir schon immer.}
{1195}{}{Äh? [Sein einsames Auge starrt voller Angst auf dein Dynamit.] Miss macht doch nur Spaß, oder? Miss macht Spaß! Das ist keine echte Bombe! Miss soll sie woanders zünden! Wir befehlen es ihr! Wir legen ein Veto gegen Miss' Entscheidung ein!}
{1197}{}{Aber... Precious, was sollen wir tun? Miss macht keinen Spaß! Miss hat den Auftrag, uns zu ermorden! Vielleicht nimmt Miss ein Gegenangebot an? 50% mehr als den Betrag! Auch wir machen keinen Spaß, Miss.}
{1199}{}{Wir haben Geld. Wir bezahlen Miss, wenn sie das rote Ding in diesen Behälter legt.}
{1204}{}{Yeeee-haaaw! Wir haben Miss reingelegt! Ha-ha!!! Miss ist eine Trottelin! Vielleicht kommt Miss aus Kanada? Na ja. Wachen! Bringt unseren Gast zur Tür!}
{1207}{}{Nein! Miss soll sich nicht beeilen! Wir müssen nachdenken! Precious will auch nachdenken!}
{1210}{}{Also gut. Wir treffen eine Entscheidung. Wir und Precious befehlen, die Tür zu öffnen. Ja. Miss soll ihr rotes Ding nehmen und verschwinden... [stöhnt]}
{1213}{}{Was? Aber... Aber... Precious, darf Miss an dieser Kiste mit den Drähten herumfummeln?}
{1215}{}{Miss kann uns nicht wehtun! Miss hat kein Recht dazu!}
{1219}{}{Precious, Miss unterliegt nicht unseren Gesetzen! Was tun wir?!}
{1221}{}{Au, au, au, au!!! Miss kann das nicht tun!}
{1223}{}{Ughh!! Miss tut uns sehr weh!}
{1225}{}{Nein! Miss muss aufhören!}
{1227}{}{AHHH! Miss soll aufhören! Aufhören!!!}
{1231}{}{Miss ist sehr grausam! Wir haben so viel Gutes getan, aber Miss tut uns weh! Schätzchen, das ist nicht fair! [weint]}
{1237}{}{Nein, Miss hat ihre Pflichten als Bürgerin noch nicht erfuellt. Miss kann nicht einfach gehen. Mister President ist nicht in der Stimmung. Nein.}
{1241}{}{NEIIIN!!! Warum ist Miss so grausam! Warum?!! Schätzchen und ich stehen uns seit Jahren nahe! Noch nie stand uns jemand so nahe! Vielleicht ist Miss vernünftig und bringt Schätzchen zurück! Der Präsident würde sogar auf die Knie fallen, wenn er welche hätte! Ehrlich!}
{1244}{}{Nun, welche Entscheidung trifft der Präsident in dieser schwierigen Lage? Wäre es nicht besser, zu seinem eigenen Wohl auf einen Gast zu verzichten?}
{1245}{}{Ja!!! Miss hat recht!! Wir lassen Miss gehen, aber Schätzchen muss hierbleiben!!!}
{1250}{}{AAAAHHHA-HA-HA-HA!!! Willkommen in unseren Gemächern, Miss! Verzeihung, dass wir keine Uniform tragen, es gibt nichts, worauf man sie anziehen könnte! Vielleicht könnte Miss uns mit einer Feder kitzeln, hm?}
{1252}{}{Miss ist eine IDIOTIN!!! Ich bin nicht bloß ein sprechender Kopf! Vor Ihnen steht der Präsident höchstpersönlich! Wo ist diese Miss hergekrochen, wenn sie den Präsidenten nicht von allen anderen unterscheiden kann?! ... Was, mein Schätzchen? Aus dem Arsch?!!! Mein Schätzchen, du solltest Manieren lernen!}
{1253}{}{Na, das ist mal was Neues.}
{1254}{}{Was sagst du da, mein Schätzchen?! Ja, wir stimmen zu. Solche Misses sollte man einquartieren. Alle, die aus dem Arsch kommen, müssen ausgerottet werden!!!}
{1256}{}{Was? Was sagt sie? Will sie uns Angst machen? Na schön. Dieser Bürger soll herauskommen und sich auf meine Klingel stützen ... Ich meine ... Ich meine, auf meinen Finger. Was, mein Schätzchen? Ich habe keinen Finger? Na ja ... Dann soll sie sich auf irgendetwas von mir stützen. Miss soll herauskommen. Wir tun ihr nichts.}
{1258}{}{Ja, ja, JA!!! Wir sind ganz brav! Lasst Miss nur näher kommen! Wir haben so lange niemanden gesehen! Wir wollen Miss sehen!}
{1276}{}{Hahaha!! Miss hat recht! Und du, Schätzchen, was meinst du? Will Schätzchen auch die Außenwelt sehen? Ja, wir werden es tun!! Wir werden sie sehen, wir werden mutig sein!!}