{100}{}{Sauerstoff-Notflaschen.}
{101}{}{Sauerstoff-Notflaschen. Auf jeder steht in großen Buchstaben „EXPLOSIV!“}
{102}{}{Du könntest den Wagen zum Explodieren bringen und ihn in Richtung der Geschütztürme schieben.}
{103}{}{Sauerstoff-Notflaschen. Man kann sie zu den Geschütztürmen schieben, aber wie soll man sie aus der Entfernung zur Explosion bringen?}
{104}{}{Jetzt knallt's!}
{105}{}{Nichts.}
{106}{}{Das kannst du im Kampf nicht tun!}
{107}{}{Du legst das Dynamit in den Wagen. Jetzt musst du nur noch den Zünder stellen und ihm einen kleinen Schubs geben.}
{108}{}{Vermint.}
{109}{}{Du hast den Wagen bereits vermint; weitere Sprengladungen sind nicht nötig.}
{110}{}{Das ist unnötig.}
{111}{}{Du hast das Kabel an den Gasflaschen befestigt und den Wagen angeschoben. Jetzt musst du ihm nur noch einen kleinen Schubs geben.}
