{100}{}{}
{101}{}{Du kannst den Zug während eines Kampfes nicht starten!}
{102}{}{Dein Auftrag hier ist noch nicht erledigt!}

{103}{}{Du kannst den Zug starten und zurückfahren. Willst du zurückfahren?}
{104}{}{Du kannst den Zug starten und zurückfahren, aber dein Fahrer ist nicht hier. Bist du bereit, ihn seinem Schicksal zu überlassen und zurückzufahren?}
{105}{}{Heize die Turbine auf und kehre zurück.}
{106}{}{Abbrechen.}

{107}{}{Möchtest du nach Salt Lake reisen?}
{108}{}{Los geht's!}
{109}{}{Abbrechen.}
