{100}{}{Du siehst eine fest verriegelte Tür.}
{101}{}{Diese Tür scheint durch einen elektromagnetischen Mechanismus verschlossen zu sein.}
{102}{}{Es scheint der Notausgang zu sein. Er lässt sich nur öffnen, wenn du den Alarm auslöst.}
{103}{}{Diese Tür scheint über einen elektromagnetischen Mechanismus mit einem Sicherheitssystem zu verfügen.}

{110}{}{Die Tür lässt sich nur mit einem speziellen Code öffnen, den du nicht kennst.}
{111}{}{Eine Schlüsselkarte wird benötigt.}
{112}{}{Dies ist eine Nottür zum unteren Stockwerk. Sie lässt sich nur öffnen, wenn du den Alarm auslöst.}
{113}{}{Verschlossen.}
{114}{}{Die Tür klemmt. Du musst rohe Gewalt anwenden, um sie zu öffnen.}
{115}{}{Uff!...}
{116}{}{Laut knarrend gibt die Tür deinem Aufprall nach und öffnet sich.}
{117}{}{Ja!}
{118}{}{Diese Tür ist bereits offen.}
{119}{}{Nutzlos.}
{120}{}{Du öffnest die Tür mit der Schlüsselkarte.}
{121}{}{Öffnen.}
{122}{}{Diese Schlüsselkarte ist ungültig.}
{123}{}{Die Tür ist verschlossen. Du brauchst eine Schlüsselkarte.}
{124}{}{Die Fähigkeit Einbruch hilft hier nicht. Du brauchst eine Schlüsselkarte.}
{125}{}{Die Tür öffnet sich nur im Notfall. Es gibt nicht einmal ein Schloss, das man knacken könnte.}
{126}{}{Die Tür ist eigentlich offen. Sie klemmt nur.}
{127}{}{Nicht einmal ein Kratzer.}
{128}{}{Falsch.}
{129}{}{Diese Schlüsselkarte ist für diesen Türtyp nicht geeignet.}
{130}{}{Unmöglich.}
{131}{}{Zugang gewährt.}
