{110}{}{Du siehst ein Gerät, das die oberen Ebenen mit Energie versorgt. Ohne es gibt es im Vault keinen Strom.}
{111}{}{Das Gerät funktioniert nicht – und du bist schuld!}
{112}{}{Du hast diesem Verteiler bereits den Strom abgestellt.}
{113}{}{Du schaltest diesen Verteiler ab und hörst, wie das Summen der Leitungen im Vault leiser wird.}
{114}{}{Es bleibt dir nur sehr wenig Zeit, bevor sich die Notstromgeneratoren einschalten.}
{115}{}{**WARNUNG! NOTSTROMGENERATOREN AKTIVIERT!*}
{116}{}{Du kannst den Verteiler nicht abschalten; deine technischen Fähigkeiten reichen nicht aus.}
{117}{}{Das bringt nichts.}

{118}{}{Das Gerät funktioniert nicht.}
{119}{}{Das ist eine sehr wichtige Sache.}
{120}{}{Erledigt.}
{121}{}{Unklar.}
{122}{}{Das funktioniert hier nicht.}
{123}{}{Die Sprengladungen müssen *unter* dem Gerät platziert werden.}
{124}{}{Funktioniert nicht.}