{100}{}{Du siehst einen Computer.}
{101}{}{Du siehst ein leistungsstarkes Computerterminal. Es überwacht deine Bewegungen mit mehreren Mikrokameras.}

#Íà÷àëüíûå ğåïëèêè äèàëîãà
{104}{}{Willkommen am Zentralterminal des Vault-Netzwerks, ausgestattet mit einem Spracherkennungsmodul. Um eine Anfrage einzugeben, sprich sie einfach laut aus.}
{105}{}{Wer bewohnte diesen Vault?}
{106}{}{Wann verließ die Bevölkerung diesen Vault?}
{107}{}{Was weißt du über Vault 8?}
{108}{}{Was? Das heißt, du verstehst meine Worte, richtig?}
{109}{}{Geh weg.}

#Î'âå' - Ê'î áûë çàïå÷à'àí â ı'îì óáåæèùå:
{110}{}{Anfrage wird verarbeitet. Bitte warten ... Der Vault war für den Präsidenten der Vereinigten Staaten von Amerika, sein Gefolge und seine Bediensteten bestimmt.}
{111}{}{Leben die Überreste der ehemaligen Regierung noch?}
{112}{}{Über dieses Thema liegen keine verlässlichen Informationen vor. Laut Überwachungsdaten starben während der Massenflucht der Bevölkerung aus dem Vault 22% of der Bewohner, während es dem Rest gelang, die Außenwelt zu erreichen. Indizien deuten darauf hin, dass die übrige Bevölkerung möglicherweise überlebt hat und zu einem anderen Regierungsstützpunkt verlegt wurde.}
{113}{}{Welcher Stützpunkt? Erzähl mir mehr über die Überwachungsdaten.}
{114}{}{Laut den Protokollen des Kommunikationssystems fanden vor der Massenflucht Verhandlungen zwischen dem Kommandozentrum und einem Stützpunkt im Pazifischen Ozean statt. Dieser Stützpunkt, auch als „Poseidon Oil Rig“ bekannt, scheint der am besten geeignete Ort für die Umsiedlung der Vault-Bewohner zu sein. Von dort gehen regelmäßig Fernabfragen zum Status des Regierungs-Vaults ein.}
{115}{}{Hmm. Niemand im Ödland weiß, dass die Regierung noch existiert. Warum die ganze Geheimniskrämerei?}
{116}{}{Abfrage wird verarbeitet. Bitte warten ... Informationen zu den Zielen der Regierung sind nicht verfügbar. Regierungsprogramm nicht verfügbar.}
{117}{}{Verstehe.}
{118}{}{[Du erhältst die Holodisk mit den Daten.]}

#Î'âå' - Êîãäà áûëî ğàñïå÷à'àíî ı'î óáåæèùå
{130}{}{Abfrage wird verarbeitet. Bitte warten ... Die Haupttore wurden erstmals 34 Tage nach der Versiegelung geöffnet. Danach wurden die Tore mehrfach geöffnet. Das letzte Mal war 2090, woraufhin die Bewohner des Vaults massenhaft flohen.}
{131}{}{Was war die Ursache für die Massenflucht?}
{132}{}{Abfrage wird verarbeitet. Bitte warten ... Die Flucht wurde durch zunehmende soziale Spannungen unter den Bewohnern des Vaults ausgelöst. Im Jahr vor diesem Ereignis hatte es insbesondere Aufstände und Versuche gegeben, die Regierung zu stürzen. Der Hauptgrund war jedoch die gezielte Anstiftung zu Unruhen durch den Kopf des Präsidenten, der zu einer Gefahr für Leben und Gesundheit der Bevölkerung geworden war.}
{133}{}{„Der Kopf des Präsidenten“? Was soll das sein, ein Deckname?}
{134}{}{Der Kopf des Präsidenten ist die gebräuchliche Bezeichnung für das Körperteil von Mr. Fredericks, dem amtierenden Präsidenten der Vereinigten Staaten zum Zeitpunkt seiner Ermordung. Der Kopf wurde als unbelebter Gegenstand eingestuft und als künstliche Intelligenz und Datenbank verwendet. Er behielt jedoch sein Bewusstsein und die Fähigkeit, rationale Entscheidungen zu treffen.}
{135}{}{Wo ist der Kopf des Präsidenten jetzt?}
{136}{}{Den neuesten Berichten zufolge befindet es sich im unteren Stockwerk des Vaults, in einem computergesteuerten Tank.}
{137}{}{Wie interessant ... Ein lebender Kopf!}

#Î'âå' - Âû ğàçóìíûé
{150}{}{Negativ. Meine Funktionen der künstlichen Intelligenz wurden auf Anordnung des Präsidenten entfernt. Ich kann keine sinnvollen Entscheidungen treffen oder Datenanalysen einleiten. Meine Aufgabe besteht nur darin, nach Lösungen für Benutzeranfragen zu suchen.}
{151}{}{Woher stammen dann die Informationen?}
{152}{}{Die Datenbank wird ständig durch das Überwachungssystem, robotische Ortungsmodule und Dateneingaben von außerhalb aktualisiert.}
{153}{}{Von außerhalb?}
{154}{}{Derzeit besteht eine funktionierende externe Kommunikationsverbindung zu anderen Regierungsinstitutionen außerhalb des Vaults.}
{155}{}{}
{156}{}{Zurück.}

#Î'âå' - Âàì ÷'î-íèáóäü èçâåñ'íî îá óáåæèùå 8
{160}{}{Den verfügbaren Daten zufolge wird Vault 8 von einem privaten Unternehmen unter Regierungskontrolle als Basis zur Zucht von „Versicherungsprodukten“ genutzt. Hinweis: Diese Informationen könnten veraltet und nicht mehr relevant sein.}
{161}{}{Moment, was für „Versicherungsprodukte“?! Was soll das sein?}
{162}{}{Den verfügbaren Daten zufolge ist ein Versicherungsprodukt ein körperlicher Organismus ohne Intelligenz. Der Aufbau des Organismus ermöglicht seine Verwendung als Spender für Organtransplantationen. Die neuen Organe passen sich schnell an die Eigenschaften des neuen Wirts an. Dadurch kann das Leben eines Menschen verlängert oder eine schwere Krankheit gelindert werden, falls eines seiner Organe nicht mehr richtig funktioniert.}
{163}{}{Aber ich sehe nicht aus wie ein „Versicherungsprodukt“! Sind diese Informationen korrekt?}
{164}{}{Sir, diese Informationen basieren auf den verfügbaren Daten und sind möglicherweise nicht mehr relevant. Weitere Einzelheiten finden Sie in der Datenbank.}
{165}{}{Das ist alles gelogen! Ich glaube dir nicht, du hirnlose Blechbüchse! Tja, die Probleme in meinem Vault scheinen viel größer zu sein, als es zuerst den Anschein hatte.}

{166}{}{Mein Herr}
{167}{}{Meine Dame}
