#Êàæåòñÿ, òåêñò íå èñïîëüçóåòñÿ â 1.0., íî íå óâåğåí ïîëíîñòüş
{100}{}{Hier gibt es nur Bündel von Hochspannungskabeln.}
{101}{}{Nur ein paar Drähte.}
{102}{}{Hier gibt es nichts außer leeren Kabelkartons.}
{103}{}{Leer.}
{104}{}{In dieser Kiste sind Kabel und Stecker. Wozu brauchst du die?}
{105}{}{Was für ein genialer Plan!}
{106}{}{Wirklich, lass die Kiste in Ruhe.}
{107}{}{Das wird ein glorreicher Sieg über die Geschütztürme! Du bindest ein Ende des Kabels an den Wagen mit den Gasflaschen und steckst das andere in den Schaltschrank im Flur. Dann öffnest du die Ventile der Gasflaschen ein wenig und schiebst den Wagen. Jetzt musst du ihm nur noch einen kleinen Stromstoß verpassen.}
{108}{}{Führe diese einfachen Handlungen aus.}
{109}{}{Geh weg.}
{110}{}{Du befestigst das Kabel an den Gasflaschen. Jetzt musst du ihnen nur noch einen kleinen Stromstoß verpassen.}