{100}{}{Diese Fähigkeit hilft dir hier nicht weiter – dieses Schloss ist viel zu schwierig.}
{101}{}{Anscheinend lässt sich diese Tür mit gewöhnlichem Sprengstoff nicht öffnen.}
{102}{}{Du siehst sehr robuste, hermetische Türen mit elektronischen Schlössern. Du brauchst eine Zugangskarte.}
{103}{}{Puh! Gerade noch gerettet!}
{104}{}{Irgendetwas blockiert das Schloss.}
{105}{}{Du siehst hermetische Türen.}
{106}{}{Schlösserknacken hilft dir diesmal nicht weiter.}

{110}{}{AAAAHHHA-HA-HA-HA!!! Willkommen in unseren Gemächern, mein Herr! Verzeihung, dass wir keine Uniform tragen, wir haben nichts zum Anziehen! Vielleicht könnte der Herr uns mit einer Feder kitzeln, hm?}
{111}{}{Was zum... Ein sprechender Kopf?! Bist du... lebendig?}
{112}{}{Der Herr ist ein IDIOT!!! Ich bin nicht bloß ein sprechender Kopf! Vor dir steht höchstpersönlich Herr Präsident! Wo ist dieser Herr hergekrochen, wenn er den Präsidenten nicht von allen anderen unterscheiden kann?! ... Was, mein Schätzchen? Aus dem Arsch?!!! Mein Schätzchen, du solltest Manieren lernen!}
{113}{}{Na, das ist mal was Neues.}
{114}{}{Was sagst du da, mein Schätzchen?! Ja, wir sind einverstanden. Solche Herren sollte man vierteilen. Alle, die aus dem Arsch kommen, müssen ausgerottet werden!!!}
{115}{}{Bist du dir da sicher?}
{116}{}{Was? Was sagt er? Will er uns Angst machen? Na gut. Dieser Bürger soll herauskommen und sich auf meinen Klingelknopf stützen ... Ich meine ... auf meinen Finger. Was, mein Schatz? Ich habe keinen Finger? Na ja ... Dann soll er sich auf irgendwas von mir stützen. Der Herr soll herauskommen. Wir tun ihm nichts.}
{117}{}{Versprichst du das? Kann ich dir vertrauen?}
{118}{}{JA, JA, JA!!! Wir werden brav sein! Lasst den Herrn nur näher kommen! Wir haben schon so lange niemanden mehr gesehen! Wir wollen den Herrn sehen!}
{119}{}{Hm ...}

{120}{}{Diese Tür lässt sich nur in Notfällen öffnen.}
{121}{}{Notausgang hinten. Lässt sich natürlich nur in Notfällen öffnen.}
{122}{}{Das bringt nichts.}

{123}{}{Diese Schlüsselkarte passt nicht zu dieser Tür.}
{124}{}{Nicht das.}
{125}{}{Während eines Kampfes kannst du das nicht tun!}

#Æåíñêèå ðåïëèêè
{1110}{}{AAAAHHHA-HA-HA-HA!!! Willkommen in unseren Gemächern, mein Herr! Verzeihung, dass wir keine Uniform tragen, wir haben nichts zum Anziehen! Vielleicht könnte der Herr uns mit einer Feder kitzeln, hm?}
{1112}{}{Die Dame ist ein IDIOT!!! Ich bin nicht bloß ein sprechender Kopf! Vor dir steht höchstpersönlich der Präsident! Wo kommt diese Dame her, wenn sie den Präsidenten nicht von allen anderen unterscheiden kann?! ... Was, mein Schatz? Aus dem Arsch?!!! Mein Schatz, du solltest Manieren lernen!}
{1113}{}{Na ja, das meinte ich nicht ...}
{1114}{}{Was sagst du da, mein Schatz?! Ja, wir sind einverstanden. Solche Damen sollte man vierteilen. Alle, die aus dem Arsch kommen, müssen ausgerottet werden!!!}
{1116}{}{Was? Was sagt sie? Will sie uns Angst machen? Na gut. Diese Bürgerin soll herauskommen und sich auf meinen Klingelknopf stützen ... Ich meine ... auf meinen Finger. Was, mein Schatz? Ich habe keinen Finger? Na ja ... Dann soll sie sich auf irgendwas von mir stützen. Die Dame soll herauskommen. Wir tun ihr nichts.}
{1118}{}{JA, JA, JA!!! Wir werden brav sein! Lasst die Dame nur näher kommen! Wir haben schon so lange niemanden mehr gesehen! Wir wollen die Dame sehen!}
