{100}{}{Das ist der tropfende Wasserhahn.}
{101}{}{Du siehst ein gewöhnliches Waschbecken. Selten tropft Wasser aus dem Hahn. Wenn du die Tropfen beobachtest, bekommst du irgendwie Lust zu singen.}
{102}{}{Da ist kein Wasser mehr drin!}

{103}{}{Du drehst den Hahn auf und fuellst die Feldflasche mit sauberem Wasser.}
{104}{}{Nach gründlicher wissenschaftlicher Analyse bist du zu dem Schluss gekommen, dass du einfach den Hahn aufdrehen und die Feldflasche mit Wasser fuellen musst.}
{105}{}{Du drehst leise den Hahn auf und fuellst eine Feldflasche mit Wasser, als würdest du gleich auf frischer Tat ertappt werden.}
{106}{}{Du demonstrierst die Wunder der Schlossknackerei, drehst den Hahn auf und fuellst die Feldflasche mit Wasser, obwohl du einfach das verdammte Ventil aufdrehen kannst.}
{107}{}{Na, was zum Teufel erwartest du von einem gewöhnlichen Waschbecken?!}

{110}{}{Hey, der Wasserhahn tropft! Na toll!}

#Íîâûå òåêñòû
{111}{}{Aus diesem Hahn fließt sauberes Wasser, und die Menge ist praktisch unbegrenzt.}
{112}{}{Du fuellst eine Feldflasche mit sauberem Wasser.}