{100}{}{Du siehst einen Boxsack.}
{101}{}{Du siehst einen Boxsack. Es ist, als würde er dich einladen, es mal zu versuchen. Du kannst in deinem Kopf fast hören: „Verpass diese Gelegenheit nicht!“}
{102}{}{An diesem Sack kannst du deine Fäuste aufwärmen und neue Kampftechniken ausprobieren.}
{103}{}{Hm, warum nicht?}
{104}{}{Der Sack ist so heruntergekommen, dass er nach deinem Training unbrauchbar ist.}
{105}{}{Dieser Boxsack ist nutzlos.}
{106}{}{Dieser Boxsack könnte dir zum Trainieren deiner Fähigkeiten dienen, aber sie sind bereits zu hoch.}
{107}{}{Training? Das brauche ich nicht mehr ...}
{108}{}{Du trainierst zwei Stunden lang und steigerst deinen Nahkampffertigkeitswert um 5%.}
{109}{}{Gute Arbeit!}