{100}{}{Du siehst Überwachungsmonitore.}
{101}{}{Auf diesen Überwachungsmonitoren sind verschiedene Räume des Vaults zu sehen.}

{110}{}{Du siehst Überwachungsmonitore, auf denen verschiedene Räume des Vaults, Korridore und öffentliche Bereiche zu sehen sind.}
{111}{}{[Ebene 2 untersuchen]}
{112}{}{[Ebene 3 untersuchen]}
{113}{}{[Ebene 4 untersuchen]}
{114}{}{[Gehen]}

{120}{}{Die zweite Ebene beherbergt Wohnräume und Freizeiteinrichtungen. Die Räume sind ein unglaubliches Durcheinander und wurden offenbar seit Jahren nicht mehr gereinigt. Am Ende des Hauptkorridors, nahe dem Aufzug, ist die Wand durch die Explosion eingestürzt.}
{121}{}{Auf der dritten Ebene befinden sich Technik- und Versorgungsräume, darunter der Posten des Aufsehers und das Kraftwerk.}
{122}{}{Die vierte Ebene wird nicht überwacht. Das Gefühl von Geheimnis und Unheil lässt dich nicht los.}
