{100}{}{He-he, es ist, als wäre ich der Star dieser Szene.}
{101}{}{Überraschend!}
{102}{}{Der Besitzer dieses Klaviers hat irgendeinen Psycho darin versteckt. Jetzt gehört es dir.}
{103}{}{Nichts Interessantes.}
{104}{}{Das Versteck ist leer.}
{105}{}{Spiel, du Stück Holz!}
{106}{}{Das Klavier lässt sich nicht mehr spielen – du hast den Anschlagmechanismus beschädigt, als du das Versteck geöffnet hast.}