{100}{}{Du siehst ein gewöhnliches, domestiziertes brahmin.}
{101}{}{Der Grund, warum brahmin zwei Köpfe hat, ist die frühe Strahlenbelastung eines Tieres, das man früher Kuh nannte.}
{102}{}{Dir fällt an dem brahmin nichts Ungewöhnliches auf.}
{103}{}{Brahmin eignen sich nicht besonders gut für Gespräche.}
{104}{}{Hast du nichts Besseres zu tun, als herumzusitzen und mit Rindern zu reden?}
{105}{}{Es ist ein brahmin. Es hat zwei Köpfe.}

{201}{}{Muuu ...}
{202}{}{Muuu, muuu, muuu ...}
{203}{}{Muuu ...}
{204}{}{Muuuuu ...}
{205}{}{Muuuuuuuuu ...}
{206}{}{::GRUNZ::}