{100}{}{Du siehst einen Mann mit scharfem Blick und geschäftsmäßigem Auftreten.}
{101}{}{Du siehst einen Craps-Croupier.}
{102}{}{Er hat einen Stock und jede Menge Chips. Du könntest dein Glück bei ihm versuchen.}

{103}{}{Macht eure Einsätze. Wir haben einen weiteren Würfler.}
{104}{}{Wie viel setzt du auf die PASS-LINE?}
{105}{}{Wie viel setzt du auf die EXIT-LINE?}
{106}{}{Wie viel setzt du auf die COME-LINE?}
{107}{}{Wie viel setzt du auf die GO-LINE?}
{108}{}{Wie viel setzt du auf das FIELD?}
{157}{}{Wie viel setzt du auf deinen PLACEBET?}
#options
# 2 3 12 crap out. 7 11 win auto..

{109}{}{Der Punkt ist}

{110}{}{Pass-Linie.}
{111}{}{Exit-Linie.}

{112}{}{Come-Linie.}
{113}{}{Go-Linie.}

{114}{}{Spezialwetten ...}
{115}{}{Place-Wetten ...}
{116}{}{Field-Wette platzieren}
{118}{}{Würfeln}

{119}{}{Pass-Line-Einsatz festgelegt auf:}
{120}{}{Exit-Line-Einsatz festgelegt auf:}
{121}{}{Come-Line-Einsatz festgelegt auf:}
{122}{}{Go-Line-Einsatz festgelegt auf:}

{123}{}{7:}
{124}{}{d3s:}
{125}{}{d4s:}
{126}{}{d5s:}
{127}{}{d2s:}
{128}{}{1&2:}
{129}{}{5&6:}
{130}{}{1&1:}
{131}{}{6&6:}
{132}{}{Craps:}

{133}{}{Pls 4:}
{134}{}{Pls 5:}
{135}{}{Pls 6:}
{136}{}{Pls 8:}
{137}{}{Pls 9:}
{138}{}{Pls 10:}

{139}{}{Auf 4:}
{140}{}{Auf 5:}
{141}{}{Auf 6:}
{142}{}{Auf 8:}
{143}{}{Auf 9:}
{144}{}{Auf 10:}

{145}{}{Quoten 4:}
{146}{}{Quote 5:}
{147}{}{Quote 6:}
{148}{}{Quote 8:}
{149}{}{Quote 9:}
{150}{}{Quote 10:}

{151}{}{Feldeinsatz festgelegt auf:}

{152}{}{Welche PROPOSITIONSWETTE?}
{153}{}{Wie viel?}
{154}{}{Ein-Wurf-Wetten...}
{155}{}{Hardway-Wetten...}
{156}{}{Welche Art von Wette?}

#proposition bets
{200}{}{7 würfeln (Auszahlung 5 zu 1)}
{201}{}{Doppel-3 (Auszahlung 10 zu 1)}
{202}{}{Doppel-4 (Auszahlung 10 zu 1)}
{203}{}{Doppel-5 (Auszahlung 8 zu 1)}
{204}{}{Doppel-2 (Auszahlung 8 zu 1)}
{205}{}{1 und 2 (Auszahlung 15 zu 1)}
{206}{}{5 und 6 (Auszahlung 15 zu 1)}
{207}{}{1 und 1 (Auszahlung 30 zu 1)}
{208}{}{6 und 6 (Auszahlung 30 zu 1)}
{209}{}{Beliebiger Craps-Wurf (Auszahlung 8 zu 1)}

#place bets
{299}{}{Welche PLACE-WETTE?}
{300}{}{auf 4 (Auszahlung 1,8 zu 1)}
{301}{}{auf 5 (Auszahlung 1,4 zu 1)}
{302}{}{auf 6 (Auszahlung 1,16 zu 1)}
{303}{}{auf 8 (Auszahlung 1,16 zu 1)}
{304}{}{auf 9 (Auszahlung 1,4 zu 1)}
{305}{}{auf 10 (Auszahlung 1,8 zu 1)}

{400}{}{Zurück...}

{500}{}{$}
{501}{}{.}

#reward messages
#pass line strings
{600}{}{Bei einer 7 gewinnen die Pass-Line-Wetten, der Point ist aus.}
{601}{}{Bei einer 11 gewinnen die Pass-Line-Wetten.}
{602}{}{Bei einer 2 verlieren die Pass-Line-Wetten.}
{603}{}{Bei einer 3 verlieren die Pass-Line-Wetten.}
{604}{}{Bei einer 12 verlieren die Pass-Line-Wetten.}

#don't pass line strings
{610}{}{Bei einer 7 verlieren die Don't-Pass-Wetten, der Point ist aus.}
{611}{}{Bei einer 11 verlieren die Don't-Pass-Wetten.}
{612}{}{Bei einer 2 gewinnen die Don't-Pass-Wetten.}
{613}{}{Bei einer 3 gewinnen die Don't-Pass-Wetten.}
{614}{}{Bei einer 12 werden die Don't-Pass-Wetten zurückerstattet.}

#proposition begs
{620}{}{Prop-Wette: 7}
{621}{}{Prop-Wette: Doppel-3}
{622}{}{Spezialwette: Doppelvierer}
{623}{}{Spezialwette: Doppelfünfer}
{624}{}{Spezialwette: Doppelzweier}
{625}{}{Spezialwette: 1 und 2}
{626}{}{Spezialwette: 5 und 6}
{627}{}{Spezialwette: zwei Einsen}
{628}{}{Spezialwette: zwei Sechsen}
{629}{}{Spezialwette Craps: 2, 3, 12}
{630}{}{Verloren!}
{631}{}{Gewonnen!}

#place bets
{650}{}{Platzwette auf 4}
{651}{}{Platzwette auf 5}
{652}{}{Platzwette auf 6}
{653}{}{Platzwette auf 8}
{654}{}{Platzwette auf 9}
{655}{}{Platzwette auf 10}

#field bets
{660}{}{Feldwette auf 2 gewinnt das Doppelte.}
{661}{}{Feldwette auf 3 gewinnt.}
{662}{}{Feldwette auf 4 gewinnt.}
{663}{}{Feldwette auf 9 gewinnt.}
{664}{}{Feldwette auf 10 gewinnt.}
{665}{}{Feldwette auf 11 gewinnt.}
{666}{}{Feldwette auf 12 gewinnt das Dreifache.}
{667}{}{Feldwette verloren.}

#flat bet
{670}{}{Grundwette auf 4}
{671}{}{Grundwette auf 5}
{672}{}{Grundwette auf 6}
{673}{}{Grundwette auf 8}
{674}{}{Grundwette auf 9}
{675}{}{Grundwette auf 10}

{680}{}{Odds-Wette auf 4}
{681}{}{Odds-Wette auf 5}
{682}{}{Odds-Wette auf 6}
{683}{}{Odds-Wette auf 8}
{684}{}{Odds-Wette auf 9}
{685}{}{Odds-Wette auf 10}

{700}{}{Keine Punkt-Odds zurückgezahlt.}
{701}{}{Spielen}
{702}{}{Nicht spielen}

{710}{}{Würfel 1:}
{711}{}{Würfel 2:}

{712}{}{Tut mir leid, ich muss gehen.}
{713}{}{Tut mir leid, diese Wette möchte ich nicht eingehen.}
{714}{}{Der Punkt ist aufgehoben.}

#odds bet stuff
{800}{}{Odds auf Play-Zahlen setzen.}
{801}{}{Quotenmultiplikator wählen. Quote auf:}
{802}{}{Quote für x.}
{803}{}{Aktuell bei:}
{804}{}{Wette auf die 4.}
{805}{}{Wette auf die 5.}
{806}{}{Wette auf die 6.}
{807}{}{Wette auf die 8.}
{808}{}{Wette auf die 9.}
{809}{}{Wette auf die 10.}
{810}{}{Auf welche Zahl wetten?}

{1100}{}{Du siehst eine Frau mit scharfem Blick und geschäftsmäßigem Auftreten.}
{1102}{}{Sie hat einen Stock und jede Menge Chips. Du könntest dein Glück bei ihr versuchen.}