{100}{}{Du siehst einen Karawanenhändler.}
{101}{}{Du siehst einen Karawanenhändler. Er scheint sehr beschäftigt zu sein.}

{105}{}{Du hast die Aufgabe, Dinge für den örtlichen Karawanenhändler zu sammeln, nicht erfuellt – die Gruppe ist bereits abgereist.}
{106}{}{Wegen des Todes des Karawanenhändlers ist es nun unmöglich, die Aufgabe zum Sammeln der Gegenstände abzuschließen.}
{107}{}{Danke für deine Hilfe.}

#Äî êâåñòà
{110}{}{Hä? Ich habe keine Zeit zum Plaudern. Ich muss noch überall in der Stadt hin, bevor ich los kann.}
{111}{}{Wenn du Hilfe brauchst, kann ich dir helfen.}
{112}{}{[Gehen]}
{113}{}{Das wäre großartig. Also, ich habe eine ganze Liste von Dingen, die ich besorgen muss, bevor wir aufbrechen. Wenn du sie findest, zahle ich dir hundert Kröten. Abgemacht?}
{114}{}{Abgemacht. Gib mir die Liste, ich scanne sie mit meinem Pip-Boy.}
{115}{}{Nein, herumzurennen und irgendwelchen Kram zu suchen, ist mir zu langweilig. Auf Wiedersehen.}
{116}{}{Großartig. Hier. Versuch, das so schnell wie möglich zu erledigen. Meine Karawane bleibt nur noch drei Tage hier, bevor sie weiterzieht. Wenn du zu spät kommst, reisen wir einfach ab und deine ganze Mühe war umsonst.}
{117}{}{Also, drei Tage, um die Sachen zu sammeln. Ich versuche, daran zu denken.}
{118}{}{Warum gehst du nicht einfach weiter? Mit Leuten, deren Ruf schlechter ist als der Schweif eines Brahmin, will ich nichts zu tun haben.}
{119}{}{Äh, okay.}

#Âî âğåìÿ êâåñòà
{120}{}{Ach, du bist es. Wie läuft der Auftrag?}
{121}{}{Fast fertig. Es fehlen nur noch }
{122}{}{ Gegenstände. Warte noch ein bisschen.}
{123}{}{Ich habe noch nicht damit angefangen, aber ich behalte es im Hinterkopf. Ich komme wieder, wenn ich alles habe.}
{124}{}{Der Auftrag ist erledigt – hier sind die bestellten Sachen.}
{125}{}{Na gut. Aber vergiss nicht – wir brechen bald auf. Wenn du nicht rechtzeitig fertig wirst, bist du selbst schuld.}
{126}{}{In Ordnung.}
{127}{}{Wirklich? Wunderbar! Hier ist die Bezahlung. Vielen Dank, du hast mir sehr geholfen.}
{128}{}{Gern geschehen.}

{129}{}{Und trotzdem fehlt noch etwas. Sieh noch einmal nach.}
{130}{}{Hmm ...}
