{100}{}{Du siehst }
{101}{}{.}
{102}{}{Du siehst einen Verwalter der Postkutsche.}
{103}{}{Du siehst einen Karawanenhändler.}
{104}{}{Wir stehen dir jederzeit zu Diensten, mein Lieber!}

#Èìåíà íïñ:
{110}{}{Sentensa}
{111}{}{Blondie}
{112}{}{Tuco}
{113}{}{Tuco? Was für ein ungewöhnlicher Name ... }
{114}{}{Mein voller Name ist Tuco Benedicto Pacifico Juan Maria Ramirez. Aber über meine Familie spreche ich nicht gern.}
{115}{}{Tut mir leid. Reden wir über etwas anderes.}
{116}{}{Na gut. Tuco Bandito Dingsbums, reden wir über etwas anderes.}

#Äèàëîã â Ğèíî, êîãäà ñòàë ïğèáëèæåííûì Áîëüøîãî Ëóè
{150}{}{Ich sage es ganz direkt: Wir brauchen keine Geschäfte von Psychopathen wie dir. Und du kannst Big Louies anderen Hunden dasselbe ausrichten!}
{151}{}{Hoffentlich treffe ich dich nicht draußen auf der Straße ... }
{152}{}{Na schön. Ich brauche dich sowieso nicht.}
{153}{}{Ich prügle dir diese Worte aus dem Mund, zusammen mit deinen Zähnen! [Schlag ihm auf den Kiefer]}

{154}{}{[Der Verwalter der Postkutsche fällt der Länge nach auf den Rücken und spuckt blutige Zähne auf den Boden. Andere Angestellte der Postkutsche ziehen ihre Waffen.]}
{155}{}{[Stell dich ihnen entgegen.]}
{156}{}{[Angreifen!]}
{157}{}{}
{158}{}{[Der Verwalter steht wacklig auf, wischt sich das Blut vom Mund und hebt die Hand zu den anderen. Widerwillig stecken sie ihre Waffen ein.] So einen Schlag habe ich seit meiner Zeit im Ring nicht mehr kassiert! Das lasse ich dir durchgehen ... Aber auf der Postkutsche ist trotzdem kein Platz für dich.}
{159}{}{Pass nächstes Mal besser auf, was du sagst.}

{160}{}{Wir haben uns nichts mehr zu sagen.}
{161}{}{Weißt du, für Leute, die so zuschlagen können wie du, gibt es anständige Arbeit. Besser, als einer von Louies Hunden zu sein.}
{162}{}{Ich will hier oben besser nicht noch mehr von deiner Bande sehen ... }
{163}{}{Der Nevada Express macht keine Geschäfte mit Big Louie oder seinen Hunden.}
{164}{}{Wo finde ich hier in der Gegend einen Zahnarzt?!}

{165}{}{[Der Karawanenhändler weicht dem Schlag aus und zieht seine Waffe. Die anderen tun es ihm gleich. Hoffen wir, dass du besser schießen als kämpfen kannst.]}
{166}{}{[Kämpfen]}

#Ğèíî, êâåñò íà ïîèñê ïğîïàâøåé ïîñûëêè äëÿ ìîğìîíà
{170}{}{Erzähl mir von dem Paket, das euer Kutscher Patrick „geliefert“ hat.}
{171}{}{Wir haben den Vertrag eingehalten. Abgemacht war, das Paket nach Reno zu bringen, nicht, es persönlich an seiner Tür abzuliefern. Der Junge, der in den Slums auf der anderen Straßenseite wohnt, hat dafür bezahlt. Wenn du es aufspüren willst, such dort und nicht hier.}
{172}{}{Ich sehe mir das an.}

#Äèàëîã, ñòàğòîâàÿ âåòêà:
{200}{}{Hallo! Unser geschätzter Kunde! Was? Noch nicht? Nun, das wirst du noch! Es ist nur eine Frage der Zeit! Also, wobei kann }
{201}{}{ dir der Nevada Express behilflich sein?}
{202}{}{Ja, wie kann ich Ihnen helfen?}
{203}{}{Was ist los, Kumpel?}

{210}{}{Nevada Express? Was soll das sein?}
{211}{}{Wann fährt die nächste Fuhre?}
{212}{}{Ich muss irgendwohin.}
{213}{}{Nein, danke, ich bin nur auf der Durchreise.}

#Ãîëîäèñê
{215}{}{Woher bekommt ihr eure Postkutschen?}
{216}{}{Der Nevada Express unterhält die einzige Flotte funktionstüchtiger Überlandbusse im Ödland! Unsere talentierten Ingenieure warten sie gründlich, sowohl hier in Salt Lake als auch in unserem Hauptdepot in Las Vegas.}
{217}{}{Ich dachte, es gäbe keine funktionierenden Fahrzeuge mehr.}
{218}{}{Das kann ich dir nicht verdenken! Der Nevada Express hat womöglich die letzten funktionierenden Busse der Welt. Manche erzählen dir, ein Techniker in Wind of War würde einen alten Pickup-Truck wieder flottmachen, aber die solltest du nicht ernst nehmen. Hätte er irgendetwas, wüssten wir längst davon.}
{219}{}{Verstehe. Danke.}

{220}{}{Ich könnte dir die ganze Rede halten, aber deine Zeit ist kostbar, nicht wahr? Ich sehe, du hast einen Pip-Boy – das Zeichen eines Menschen, der noch Orte aufsuchen und Leute treffen muss! Stattdessen gebe ich dir diese Holodisk, damit du alles Nötige in aller Ruhe erfahren kannst!}
{221}{}{Na gut, in einem Punkt hast du recht: Ich habe definitiv keine Zeit, dir zuzuhören. Na schön, ich nehme den Holodisk.}
{222}{}{Danke! Ich sehe ihn mir später an.}

{223}{}{Die nächste Abfahrt ist in }
{224}{}{ Tagen. Wir fahren am 1., 11. und 21. Tag jedes Monats ab.}
{225}{}{Das war's.}
{226}{}{Ich habe noch eine Frage ... }
{227}{}{Heute! Aber ich glaube, wir haben noch ein paar Plätze frei, falls du ein Ticket kaufen willst!}
{228}{}{Die nächste Abfahrt ist morgen! Besorg dir lieber schnell ein Ticket, bevor alle Plätze ausverkauft sind!}
{229}{}{ Tag. Wir fahren am 1., 11. und 21. Tag jedes Monats ab.}

#Çàêàç ïóòè
{230}{}{Wir bringen dich ans Ziel! Wenn unsere Karawanen irgendwo nicht hinfahren, gibt es dort für dich nichts zu erledigen.}
{231}{}{Kannst du mich bei New Reno absetzen?}
{232}{}{Wie wäre es mit Salt Lake?}
{233}{}{Las Vegas erwartet mich!}
{234}{}{Ich muss zu den Cheyenne ... }
{235}{}{Ich habe in Wind of War etwas zu erledigen ... }
{236}{}{Ich muss nach Wendover.}
{237}{}{Können wir unterwegs bei Black Rock Halt machen?}
{238}{}{Bringst du mich nach Gerlach?}
{239}{}{Eigentlich habe ich noch eine Frage.}
{240}{}{Fährst du für mich zurück nach Uranium City?}

{247}{}{Ich habe ein Ticket. Los geht's.}
{248}{}{Hey, das ist nicht der normale Preis! Warum ist es so teuer?}
{249}{}{Hör mal, die Karawanenleute reden über dich. Du solltest dankbar sein, dass wir dich überhaupt in den Bus lassen.}

{250}{}{Auf in die große Stadt? Pass bloß auf, dass deine Waffe geladen ist! Wir wollen doch nicht, dass unserem geschätzten Kunden etwas zustößt! Apropos, das macht dann }
{251}{}{ Dollar für ein Ticket.}
{252}{}{Weißt du, ich vertrete die Fabrik Nuka-Cola. Wenn eure Preise nur niedriger wären, könntet ihr mit den Lieferungen eine Menge Geld verdienen ... }
{253}{}{Ach, wie schade. Ich hatte vor, viele Fahrten zu machen – geschäftlich, verstehst du –, aber bei diesen Preisen weiß ich nicht ... }
{254}{}{Hier ist das Geld.}
{255}{}{Ich komme später wieder.}

{256}{}{Dann kommst du gerade recht. Nimm die Fahrkarte und steig ein! Wir fahren bald ab.}
{257}{}{Endlich reise ich mit Stil! Hier ist das Geld.}
{258}{}{Eigentlich doch nicht. Ich gehe zu Fuß.}
{259}{}{Ich habe noch eine Frage, bevor du losfährst.}

{260}{}{Hm, ich glaube nicht. Vielleicht hast du ein Loch in der Tasche!}
{261}{}{Hä, seltsam. Ich hätte schwören können, dass ich es genau hier hatte ...}

{262}{}{Du musst noch ein bisschen warten! Wir fahren jeden 1., 11. und 21. des Monats ab.}
{263}{}{Ich komme, wenn die Zeit reif ist.}
{264}{}{Eigentlich habe ich es mir anders überlegt. Ich möchte woanders hin.}

{270}{}{Salt Lake ist ein großartiger Ort, um sich ein Zuhause aufzubauen ... Wenn du keinen Ärger mit dem Sheriff bekommst, versteht sich. Das macht }
{271}{}{ Dollar.}
{272}{}{Hm ... Nun, die Hawks haben ein gutes Wort für dich eingelegt, also nehmen wir dich kostenlos mit, aber nur dieses eine Mal! Wir müssen schließlich auch von etwas leben, ha-ha-ha!}
{273}{}{Was für eine angenehme Überraschung! Ich bin bereit.}
{274}{}{Los geht's!}
{275}{}{Willst du im örtlichen Casino dein Glück machen? Ich drücke unserem geschätzten Kunden die Daumen! Das macht nur }
{276}{}{ Dollar für die Fahrkarte.}
{277}{}{Wirklich? Warum solltest du ... Na gut, du bist unser geschätzter Kunde! Das macht nur }
{278}{}{ Dollar.}
{279}{}{Es liegt auf dem Weg, aber ich rate dir, nicht zu lange dort zu bleiben. Ich möchte nicht, dass unser geschätzter Kunde ... Ärger ... mit den örtlichen Soldaten bekommt. Jedenfalls macht das }
{280}{}{ Dollar!}
{281}{}{Black Rock? Davon habe ich gehört. Nun, wir fahren ganz in der Nähe vorbei, also machen wir einen Abstecher. Das macht nur }
{282}{}{ Dollar.}
{283}{}{Klar, das liegt auf dem Weg. Eine Fahrkarte kostet nur }
{284}{}{ Dollar.}
{285}{}{Nun, unsere Preise werden festgelegt von ... Äh ... Das sollte ich wirklich nicht tun, aber na gut. Ich kann dir zehn Prozent Rabatt geben, aber keinen Cent mehr!}
{286}{}{Danke!}
{287}{}{Ja ... Erzähl es nur niemandem, ja?}
{288}{}{Dann kommst du gerade recht. Nimm die Fahrkarte und steig ein! Wir fahren bald ab.}
{289}{}{Du musst noch ein bisschen warten! Wir fahren jeden 1., 11. und 21. des Monats ab.}
{290}{}{Ah, sie machen sich einen Namen! Dafür müssen wir kaum von unserer Route abweichen. Das kostet dich nur }
{291}{}{ Dollar.}

#Äèàëîã î äåâóøêå ñ ôîòîãğàôèè Òåäà Áàíäè
{300}{}{Erinnerst du dich daran, das Mädchen auf diesem Bild in einem deiner Busse mitgenommen zu haben?}
{301}{}{Oh, an sie erinnere ich mich! Wie könnte ich sie vergessen? Es kommt nicht jeden Tag vor, dass wir so entzückende Fahrgäste befördern dürfen!}
{302}{}{Weißt du noch, wohin sie gefahren ist?}
{303}{}{Hmm ... Ja! Nach Vegas! Daran erinnere ich mich, weil es ungewöhnlich war. Normalerweise planen die Leute eine Reise nach Vegas sorgfältig, aber sie kam im letzten Moment zu uns gerannt. Die meisten Fahrgäste machen das nur, wenn sie verschwinden wollen, ohne dass es jemand mitbekommt ... Oh. [er sieht plötzlich beunruhigt aus und gibt dir das Foto zurück] Ich ... ich erinnere mich an nichts Weiteres.}
{304}{}{Keine Sorge, Tuco, das ist alles, was ich wissen muss.}
{305}{}{Nein. [er schüttelt den Kopf und gibt dir das Foto zurück] Du kannst mir glauben, denn an so eine schöne Fahrgästin hätte ich mich erinnert.}
{306}{}{Schade.}

#Íàïàäåíèå íà äèëèæàíñ
{310}{}{Wie zuverlässig sind eure Busse?}
{311}{}{Du brauchst dir keine Sorgen zu machen, das verspreche ich dir! Ich weiß sogar, woran du denkst. An den Angriff der Biker, oder? Nun, das war das erste und letzte Mal! Glaub mir, in unseren Bussen bist du sicherer als zu Fuß in Reno.}
{312}{}{Was für ein Angriff der Biker?}
{313}{}{Na gut, ich glaube dir. Vorerst.}

{314}{}{Oh, davon weißt du nichts? Einer unserer Busse wurde von Bikern überfallen. Nur zwei Wachen haben überlebt. Aber keine Sorge – einmal haben sie uns überrascht, aber nie wieder.}

{315}{}{Was weißt du über die Biker?}
{316}{}{Das sind arbeitsscheue Gesetzlose, die nicht in den Städten leben können. Sie rauben den Leuten bei jeder Gelegenheit alte Technologie ab. Ich wünschte, ich wüsste, wo sie schlafen, dann könnte ich das Ödland von ihnen befreien!}
{317}{}{}
{318}{}{}
{319}{}{}

{320}{}{Biker haben unseren Bus zwischen Lovelock und Black Rock angegriffen. Sie nahmen alles mit und töteten alle bis auf zwei Wachen. Von ihnen haben wir alles erfahren.}
{321}{}{Ich würde gerne mehr über diese Geschichte erfahren.}
{322}{}{Gut zu wissen. Tschüss.}

{323}{}{Ich war nicht bei der Rettungsaktion dabei, also weiß ich selbst nicht viel. Aber ich erzähle dir, was ich kann!}
{324}{}{Habt ihr jemanden hingeschickt, um Nachforschungen anzustellen?}
{325}{}{Wo sind die Überlebenden?}
{326}{}{Warum bist du dir so sicher, dass ihr von Bikern angegriffen wurdet?}
{327}{}{Okay, auf Wiedersehen.}

{328}{}{Der Kutscher rief über Funk um Hilfe, aber noch bevor unser Rettungsteam den Angriffsort erreichen konnte, stieß es auf Überlebende, die in die andere Richtung liefen. Auf dem Rückweg nach Reno erzählten sie dem Rettungsteam alles.}
{329}{}{Zwei der Wachen. Sie haben jetzt dienstfrei und sind im Restaurant des Silver Legacy, wo sie versuchen, sich von dem Schock zu erholen. Es wird eine Weile dauern, bis ich sie wieder losschicke. Ich kann mir gar nicht vorstellen, wie schrecklich das für sie gewesen sein muss.}
{330}{}{Das haben uns die Überlebenden erzählt. Wir wussten schon immer, dass die Biker Unruhestifter sind, aber jetzt wissen wir auch, dass sie Diebe und Mörder sind! Ehrlich gesagt überrascht mich das nicht. Sie sind solche Leute, die in einer gesetzestreuen Gesellschaft nicht überleben können.}
{331}{}{Haben Sie Beweise?}
{332}{}{Nun ja ... Nein, aber keine gewöhnlichen Plünderer könnten uns angreifen und lebend davonkommen. Jede Kutsche ist gut gepanzert und mit einem Roboter sowie mehreren erfahrenen Wachen besetzt. Nur die Biker haben die Technologie und Fahrzeuge aus der Vorkriegszeit, um einen solchen Hinterhalt durchzuführen.}
{333}{}{Ihr habt eine ganze Kutsche verloren und nicht einmal nachgeforscht?!}
{334}{}{Meine Männer sind Profis! Ich vertraue ihrem Wort! Wenn sie sagen, es waren Biker, dann glaube ich ihnen, ob sie nun Beweise haben oder nicht. Wenn Sie mich jetzt davon überzeugen wollen, dass sie sich irren – DANN brauche ich Beweise!}
{335}{}{Na gut, ich untersuche die Sache selbst. Ich finde so oder so Beweise.}
{336}{}{Wirklich? Nun ja ... Ich weiß, dass unsere geschätzten Kunden Gewissheit haben müssen! Schließlich ist es ihr anspruchsvoller Geschmack, der sie überhaupt erst zum Nevada Express führt! Sie sollten mit dem Leiter des Rettungsteams anfangen. Er ist gerade im zweiten Stock des Silver Legacy.}
{337}{}{Na gut.}

{338}{}{Das ist eine schreckliche Idee. Ich bin weg.}
{339}{}{}

{340}{}{Noch einmal wegen des Angriffs auf die Postkutsche.}
{341}{}{In Ordnung, aber seien Sie versichert: Es besteht kein Risiko, dass so etwas noch einmal passiert. Beim nächsten Mal erschießen wir die Biker auf Sicht. Sie können dem Nevada Express Ihre Sicherheit anvertrauen!}
{342}{}{Wo finde ich noch mal den Mann, der den Rettungseinsatz geleitet hat?}
{343}{}{Gleich gegenüber, im zweiten Stock des Silver Legacy. Sein Zimmer ist in der Nähe der Treppe, und er trägt eine Metallrüstung.}
{344}{}{}
{345}{}{}
{346}{}{Danke, das wäre alles.}

{347}{}{Ich weiß, wer die Postkutsche wirklich angegriffen hat.}
{348}{}{Ach ja?}
{349}{}{Diese Holodisk vom Ort des Angriffs erklärt alles. Es waren nicht die Biker. Es waren deine Leute.}
{350}{}{Eigentlich habe ich die Beweise nicht dabei. Ich melde mich wieder bei dir.}
{351}{}{Was?! Aber – lass mich sehen. [Er nimmt die Holodisk, verschwindet im Büro und kommt wutentbrannt zurück.] Dieses Gesindel! Diese Verräter! Diese – diese – ich kann nicht glauben, dass wir so hintergangen wurden! Wir haben ihnen ehrliche Arbeit, Ansehen, alles gegeben, was sich ein Mann wünschen kann, aber das war ihnen nicht genug! Sie haben uns für – für GELD in den Rücken gestochen! [Er schlägt mit der Faust gegen die Wand.] Wir müssen reagieren.}
{352}{}{Was wirst du unternehmen?}
{353}{}{Das ist interne Angelegenheit. Mach dir keine Sorgen. Du... Du hast der Nevada Express einen großen Dienst erwiesen. Das werden wir nicht vergessen. Wenn du uns je wieder brauchst, bekommst du als Dank einen großzügigen Rabatt.}
{354}{}{Danke. Was soll ich den Bikern sagen?}
{355}{}{[Er seufzt.] Bitte richte ihnen unsere Entschuldigung aus. Ich weiß, dass das nicht reicht, aber unser Ruf wird ohnehin genug leiden, wenn ich meinen Vorgesetzten davon erzähle. Mehr können wir uns nicht leisten.}
{356}{}{Verstehe. Na dann, viel Glück.}
{357}{}{Deine Ermittlungen haben dir 20% d Rabatt auf die Dienste von Nevada Express eingebracht.}

# Female character
{1252}{}{Weißt du, ich vertrete die Fabrik Nuka-Cola. Wenn eure Preise nur niedriger wären, könntet ihr mit den Lieferungen eine Menge Geld verdienen ... }
{1264}{}{Eigentlich habe ich es mir anders überlegt. Ich möchte woanders hin.}
