{100}{}{Du siehst einen riesigen Skorpion.}
{101}{}{Du siehst den Legendären Skorpion!}
{102}{}{Du hast den legendären Skorpion, den Legendären Skorpion, erlegt! Schade, dass niemand da war, um es zu sehen.}
{103}{}{Diese Geschichte wird zur Legende.}
{104}{}{Du siehst Spud.}
{105}{}{Du siehst einen zahmen Skorpion namens Spud. Er wirkt harmlos, aber du hast trotzdem das Gefühl, dass du dich von ihm fernhalten solltest.}
