{100}{}{Du siehst einen arbeitslosen Mann.}
{101}{}{Du siehst einen rastlosen Mann, der nirgendwohin kann und nichts zu tun hat.}
{102}{}{Mach dir keine Sorgen um mich. Ich bin gleich da!}
{103}{}{Dieser Mann könnte nützlich sein. Du solltest ihn dir wohl merken.}

{104}{}{Du hast jemanden gefunden, der den Zug in Salt Lake steuert.}
{105}{}{Du hast jemanden gefunden, der den Zug bedienen kann. Jetzt kannst du deine Mission fortsetzen.}

{110}{}{Brauchst du etwas?}
{111}{}{Wer bist du, und was machst du hier?}
{112}{}{Ich brauche jemanden, der mir hilft, den Zug zu bedienen. Hast du Interesse?}
{113}{}{Nein, nichts.}
{114}{}{Klar. Bis dann.}
{115}{}{Ein Zug? Warum nicht? Inzwischen mache ich alles, wenn du mich bezahlst. Äh, du bezahlst mich doch, oder?}
{116}{}{Ich zahle dir 1000 Dollar für den Job. Triff mich in Salt Lake, dort bezahle ich dich. Abgemacht?}
{117}{}{Ach, wo bleibt denn dein Abenteuergeist? Na ja, schon gut.}
{118}{}{Schade.}
{119}{}{Hey, falls du jemanden kennst, der Leute einstellt, kannst du meinen Namen weitergeben? Ich bin handwerklich geschickt und nicht wählerisch.}

{120}{}{}
{121}{}{Ich war bei einer Karawane, bis sie überfallen wurde. Jetzt bin ich nur noch ein weiterer Penner auf der Straße. Für den Sheriff würde ich arbeiten, aber der nimmt keine Ortsfremden. Ich versuche einfach, irgendwie über die Runden zu kommen, von Tag zu Tag.}
{122}{}{Früher habe ich für einen der örtlichen Schnapsbrenner Schwarzgebrannten transportiert, aber das Geschäft ist in Reno gefährlich. Sein Konkurrent hat seine Brennblasen zerschlagen und ihm die Beine gebrochen. Ich dachte, ich könnte im Kasino Gewinn machen – und habe alles verloren. Jetzt versuche ich herauszufinden, was ich als Nächstes tun soll. Viele Möglichkeiten gibt es nicht.}
{123}{}{Auf ein Wunder hoffen, darauf eben. Ich muss Schulden bezahlen und habe gerade meinen Job verloren. Ich hoffe, mit Wetten auf die Kämpfe über die Runden zu kommen, aber ... Wen mache ich hier eigentlich was vor? Ich bin am Arsch. Es ist nur eine Frage der Zeit.}
{124}{}{Genau das versuche ich herauszufinden! Ich habe weder Arbeit noch Aussichten. Ich muss etwas tun, bevor ich noch tiefer in die Schulden gerate, aber wohin soll ich gehen? In Vegas ist es schwer, Arbeit zu finden, und in der Wüste kann ich nicht leben. Ich habe keine Ahnung, was ich tun soll.}
{125}{}{Ich bin seit Wochen arbeitslos. Ich stecke schon bis zum Hals in Schulden. Ich hoffe einfach auf den großen Gewinn, denn wenn nicht bald Geld reinkommt ... Ich weiß nicht mal, was dann passiert.}
{126}{}{Erst habe ich meinen Job verloren. Dann mein Zuhause. Kurz darauf meine Frau und Kinder ... Was kommt als Nächstes? Wahrscheinlich mein Verstand – ich kann nicht aufhören, über die ungewisse Zukunft nachzudenken.}
{127}{}{Ich sage dir Bescheid, wenn ich das herausgefunden habe. Früher habe ich für die Einheimischen kleine Touren durch die Ruinen gemacht, aber in letzter Zeit will niemand mehr mit mir zu tun haben. Als hielten sie mich für gefährlich! Jetzt habe ich keine Möglichkeit mehr, meinen Lebensunterhalt zu verdienen. Ich weiß nicht, was ich tun soll.}

{140}{}{Abgemacht! Bring das Geld zum Hotel „Sixth Bullet“. Ich werde warten!}
{141}{}{In Ordnung.}
{142}{}{Abgemacht! Aber wie komme ich nach Salt Lake? Ich müsste die Nevada Express nehmen, aber ich habe kein Geld für ein Ticket.}
{143}{}{Hier sind 1000 $. Kauf dir davon ein Ticket.}
{144}{}{Ich habe hier ein Ticket. Nimm es.}
{145}{}{Warte hier. Ich lasse mir etwas einfallen.}
{146}{}{Ich zahle dir 1000 Dollar für eine Hin- und Rückfahrt. Abgemacht?}
{147}{}{Prima! Wenn ich in Salt Lake ankomme, checke ich im örtlichen Hotel ein. Bring das Geld auf mein Zimmer. Ich werde warten!}

{1117}{}{Ach, wo bleibt denn dein Abenteuergeist? Na ja, schon gut.}

