{100}{}{Du siehst einen Karawanenhändler.}
{101}{}{Du siehst ein hübsches Karawanenmädchen.}

{110}{}{Hallo! Deinetwegen haben wir beschlossen, Bridgeport ab und zu einen Besuch abzustatten und dort Handel zu treiben. Deshalb geben wir dir 5% discount.}
{111}{}{Gern geschehen.}

{112}{}{Hey! Wie geht's dir, Freund?}
{113}{}{Wirst du jetzt öfter in Bridgeport sein?}
{114}{}{Solange es Kunden gibt. Jeden 15. des Monats sind wir hier – wir ruhen uns ein paar Tage aus und ziehen dann wieder weiter. }
{115}{}{Zeig mir deine Waren.}
{116}{}{Das war's schon? Mann, das war kein richtiger Handel.}
{117}{}{Na gut, ich lass dich erst mal in Ruhe. Man sieht sich.}
{118}{}{Zeig mir deine Waren.}
{119}{}{Mit Leuten wie dir machen wir keine Geschäfte! Verschwinde!}

#Æåíñêèå ğåïëèêè
{1112}{}{Hey! Wie geht's dir, Freund?}
