{100}{}{Du siehst einen Karawanenmeister.}

#Ïîïûòêà çàãîâîğèòü, êîãäà ÃÃ ñòàë âğàãîì êàğàâàíùèêîâ (ğåïóòàöèÿ "Ïğîêëèíàşò")
{102}{}{Na, sieh mal einer an: Der Tod eines Karawanenhändlers höchstpersönlich steht vor mir. Glaubst du, ich scheiß mir vor Angst in die Hose? Nein. Vergiss es.}

{103}{}{Ich will nichts von dir. Tschüss.}

#Îïèñàíèå äëÿ êàğàâàíùèêîâ ğàçíûõ ïóòåé:
#Ñîëò-Âåãàñ:
{104}{}{Du siehst einen Mann mit ungewaschenem Kopf. Auf seinem Schulterabzeichen steht: "Salt Lake - Las Vegas"}
#Ñîëò-Ğèíî:
{105}{}{Du siehst einen Mann, der mit Straßenstaub bedeckt ist. Auf seinem Schulterabzeichen steht: "Salt Lake - New Reno"}
#Ğèíî-Âåãàñ:
{106}{}{Du siehst einen Mann mit stark gebräunter Haut. Auf seinem Schulterabzeichen steht: "Las Vegas - New Reno"}
#Âåòåğ Âîéíû:
{107}{}{Du siehst einen müden Mann. Das Abzeichen auf seiner Schulter weist ihn als Karawanenmeister aus.}

###############################################################
#       Ñëó÷àéíûå ïğèâåòñòâèÿ (ïåğâàÿ ğåïëèêà íïñ)
###############################################################

{110}{}{Na, hallo.}
{111}{}{Ja?}
{112}{}{Oh, ein Kunde!? Wie kann ich helfen?}
{113}{}{Bist du wegen Geschäften hier? Oder willst du nur meine Zeit verschwenden?}
{114}{}{Ich höre ... Hm, wer weiß, vielleicht hast du ja etwas Nützliches zu sagen?}
{115}{}{Ich kann es kaum erwarten, dass du mir etwas Nettes erzählst. Zum Beispiel etwas über kostenloses Geld. Ha-ha!}
{116}{}{Hey, ich bin beschäftigt. Also mach schnell.}
{117}{}{[Seufzt] Na gut! Stell schon deine blöde Frage!}
{118}{}{Hallo. Was willst du?}
{119}{}{Hallo. Willst du zehn Mäuse verdienen? Wir haben niemanden, der einen brahmin ersetzen kann ... HA-HA-HA!!!}
{120}{}{Oh! Genau dann, wenn wir kostenlose Arbeitskräfte brauchen! Du kommst gerade rechtzeitig! ... HA-HA-HA!!!}

###############################################################
#       Ğàññïğîñû ïğî òåêóùèé ãîğîä
###############################################################

{150}{}{Ich wollte etwas über diese Stadt fragen.}

#Îòâåòû äëÿ êàæäîãî ãîğîäà:
{151}{}{Na ja, viel gibt es nicht zu erzählen. Nichts Besonderes. Nicht die beste Stadt in dieser Gegend.}

{152}{}{New Reno. Eine Stadt, die der Hölle gleicht. Hier gibt es sogar eine ähnliche Hierarchie, von Dämonen bis zu Teufeln. Die Teufel sind die örtlichen Gangster. Von denen hältst du dich besser fern. Wenn du ein Geschäft abschließt, verschwindest du wieder. Denn selbst das Ödland ist sicherer als dieser Ort!}
{153}{}{New Reno. Eine Stadt, die der Hölle gleicht. Sie hat sogar ihren eigenen Teufel, obwohl es vor nicht allzu langer Zeit noch zwei davon gab. Kurz gesagt: Hier musst du vorsichtig sein. Die Stadt macht gerade keine guten Zeiten durch. So viel steht fest.}
{154}{}{New Reno. Eine Stadt, die der Hölle in nichts nachsteht. Und nachdem jemand zwei lokale Bosse ausgeschaltet hat, scheint hier jeder durchzudrehen. Meide dunkle Gassen. Sonst hast du bald großen Ärger am Hals. Alles klar!}

{160}{}{Las Vegas. Eine Stadt, in der immer was los ist und die viel sicherer ist als der Rest. Ein toller Ort zum Entspannen und Handeln.}
{161}{}{Las Vegas. Eine Stadt, in der immer was los ist und die viel sicherer ist als der Rest. Ein toller Ort zum Entspannen und Handeln ... Allerdings gehen hier seltsame Dinge vor sich. Aber das ist vorerst nicht unser Problem.}

{170}{}{Salt Lake. Ein riesiger Haufen Scheiße. Dreck und Armut sind überall. Trotzdem ist die Bevölkerung viel friedlicher als in New Reno. Wenigstens musst du hier keine Angst haben, dass dir jemand ein Messer in den Rücken rammt.}
{171}{}{Salt Lake. Eine dreckige Stadt, aber die Bevölkerung ist viel friedlicher als in New Reno. Wenigstens musst du hier keine Angst haben, dass dir jemand ein Messer in den Rücken rammt – und du kannst gute Geschäfte machen.}
{172}{}{Salt Lake. Die Stadt mag ein bisschen dreckig sein, aber wenn ich nicht meiner Arbeit nachgehen müsste, würde ich mich hier niederlassen. In der ganzen Region findest du keinen besseren Ort zum Leben. Jeder hat Arbeit und kann seinen Lebensunterhalt verdienen, ohne Angst haben zu müssen, dass ihm jemand ein Messer in den Rücken rammt. Ein guter Ort.}

{175}{}{Wind des Krieges – das ist eine Militärsiedlung. Die Leute dort halten sich für die eigentlichen Bewohner des Ödlands, die rechtmäßigen Herrscher dieser Region. Alle anderen sind für sie bloß Milchkühe, denen sie nehmen, was sie wollen.}

{179}{}{Na schön, gehen wir ein Stück zurück.}

#Âîïğîñû ïğî ãîğîä -- Ğèíî:
{180}{}{Hast du dieses Mädchen auf dem Foto gesehen?}
{181}{}{[Betrachtet das Foto] Hübsch ... Nein, ich glaube nicht.}
{182}{}{In Ordnung. Noch eine Frage.}
{183}{}{Vergiss es. Tschüss.}

{184}{}{Und wenn du es genauer sagen müsstest – wo kann man sich zum Beispiel die Zeit vertreiben?}
{185}{}{Hör zu, ich bin selbst noch nicht lange hier und nach der Reise nicht in Partystimmung. Ich bin müde. Weißt du, hier gibt es einen Karawanenhändler, der in Rente ist, sozusagen. Er heißt Ricky – der Musher. Er wohnt im dritten Stock des „Rainbow“, gegenüber vom „El Dorado“. Geh zu ihm, spendier ihm einen Drink, und er erzählt dir alles über die Stadt. Er weiß eine Menge, glaub mir.}
{186}{}{Okay, aber ich habe noch ein paar andere Fragen.}
{187}{}{Dann gehe ich zu ihm. Tschüss.}

{188}{}{Hör mal, kennst du zufällig einen Karawanenhändler, der ... Nun, er sieht aus wie ein Toter. Seine Haut ist verbrannt, und man sieht seine Zähne ...}
{189}{}{Ho-ho! Du meinst Harold?!! Ich habe ihn lange nicht gesehen. Ein guter Kerl. Die Karawanenhändler mochten ihn immer. Selbst halb tot ist er sehr unterhaltsam.}
{190}{}{Kommt er oft hierher?}
{191}{}{Vergiss es. Eine andere Frage.}
{192}{}{Na gut, vergiss es.}

{193}{}{Nein, er ist ständig unterwegs. Man sagt, er sucht einen Ort, an dem er sich mit seinesgleichen niederlassen kann. Zuletzt habe ich ihn auf dem Weg nach Hub gesehen. Das ist sehr weit weg, frag bloß nicht, wo das liegt.}
{194}{}{Richtig. Noch eine Frage.}
{195}{}{Na gut. Ich denke, ich gehe jetzt.}

#Âîïğîñû ïğî ñòîÿíêó áàéêåğîâ:
{196}{}{Kommen manchmal Biker hier vorbei? Vielleicht hast du sie schon gesehen?}
{197}{}{Sie kommen schon her, aber selten. Sie bleiben nie lange. Hängen in der Bar herum, verprügeln jemanden und fahren morgens wieder los. Auf den Karawanenrouten trifft man sie leichter. Dort liefern sie sich gern Rennen mit ihren lauten Metallhaufen. Übrigens ein beeindruckender Anblick.}
{198}{}{Weißt du, ob sie einen festen Lagerplatz haben? Wo kann man sie immer finden, wenn man sie braucht?}
{199}{}{Wärst du ein Fremder, würde ich sagen, ich weiß es nicht. Die Biker wollen nicht, dass jeder von ihrem Stützpunkt weiß. Aber da du fragst, zeige ich ihn dir auf deiner Karte ...}
{200}{}{Zeig her.}
{201}{}{Ich weiß es nicht. Vielleicht weiß es jemand anderes, jemand, der andere Handelsrouten nutzt.}
{202}{}{Dann eine andere Frage.}
{203}{}{Genau hier. Das sind die alten Ruinen. Ihr Lager liegt irgendwo am Stadtrand, abseits der Straße.}
{204}{}{Danke! Aber ich habe noch Fragen.}
{205}{}{Danke, das ist alles, was ich wissen musste.}
{206}{}{Selbst wenn ich es wüsste, würde ich es nicht verraten. Zumindest nicht irgendwem. Ich will später keinen Ärger mit ihnen.}

{207}{}{Ja! Was für eine Überraschung. Das ist eine Kellnerin aus dem Café „Hard-Rock“. Sie ist ein nettes Mädchen.}

#Âîïğîñû ïî ãîğîä -- Âåòåğ Âîéíû:
{210}{}{Was machst du dann hier? Warum gehst du nicht weg?}
{211}{}{Nun, sie sind normalerweise nicht blutrünstig. Im Westflügel der Station gibt es einen Arzt, einen Händler und einen Mechaniker. Sie gehören zu ihren Leuten. Sie sind sehr nützlich, verlangen aber hohe Preise für ihre Dienste. Wir brauchen natürlich vor allem einen Mechaniker. Ohne ihn kann es schwierig werden. Allerdings ist er oft mit seinem Rotorfreund in der Garage beschäftigt.}
{212}{}{Äh ... „Rotorfreund“? Was zum Teufel ist das?}
{213}{}{Das weiß ich selbst nicht. Aber manchmal hört man ein Summen und Dröhnen aus der Garage, wie von einem laufenden Motor. Man sagt, er baut ein Flugzeug. Ha! Wenn das stimmt, wäre das eine große Neuigkeit für unsere Region!}
{214}{}{Hm. Sehr, sehr interessant! Noch eine Frage.}
{215}{}{Sehr interessant, aber ich muss los.}

#Âîïğîñû ïğî "Ñêîğîñòíîãî ßñòğåáà" -- Âåòåğ Âîéíû è Âåãàñ:
{216}{}{Hast du etwas über „Speed Hawk“ gehört? Man sagt, die Leute wurden von Raidern angegriffen ...}
{217}{}{Ja. Hier kennt inzwischen jeder die Geschichte. Pech, dass sie ihre Waren und ihre Leute verloren haben. Außerdem haben sie sich selbst zerstreut. Einer von ihnen war irgendwo hier und suchte nach seinen Leuten.}
{218}{}{Einer von ihnen ist hier? Ich sollte nach ihm suchen ...}
{219}{}{Hast du Überlebende von „Speed Hawk“ gesehen?}
{220}{}{Ich habe einen gesehen. Der Arme irrte irgendwo hier herum. Aber ich glaube, er ist schon nach Vegas aufgebrochen. Du kannst aber die Leute hier fragen, vielleicht erfährst du etwas.}
{221}{}{Stimmt.}
{222}{}{Hast du gehört, was mit „Speed Hawk“ passiert ist?}
{223}{}{Ja, die Leute hatten Pech. Schade, es war eine gute Karawane. Ich glaube nicht, dass sie den Rest der Leute finden werden. Wenn sie verschollen sind, hat wohl niemand überlebt. Sonst wären sie schon in Vegas angekommen.}
{224}{}{Ja, eine traurige Geschichte.}

#Âîïğîñû ïğî Ëûñîãî Ìàêñîíà -- Âåãàñ:
{225}{}{Sag mal, wurdest du auf dem Weg von New Reno nach Vegas von einem kahlköpfigen Sonderling mit einer Narbe am Hals begleitet?}
{226}{}{Nein, nichts dergleichen. Daran würde ich mich erinnern.}
{227}{}{Verdammt, kein Glück.}
{228}{}{Warte mal, ich glaube, ich habe so jemanden bei einer anderen Karawane gesehen. Frag dich mal um, vielleicht findest du etwas heraus.}
{229}{}{Okay!}
{230}{}{Warte mal! Da war ein Kerl. Ich weiß nicht, wie er hieß, aber er war mit uns von New Reno nach Vegas unterwegs und war ebenfalls kahl. Wo er jetzt ist, weiß ich nicht. Wahrscheinlich amüsiert er sich in Clean City.}
{231}{}{Hm, danke! Ich sollte dort nach ihm suchen ...}

#Âîïğîñû ïğî àğòåçèàíñêèé ÷èï -- Ñîëò-Ëåéê:
{232}{}{Weißt du, wo man einen Filter für den artesischen Turm in Salt Lake bekommt?}
{233}{}{Wenn ich das wüsste, würde ich mich längst in Gold baden.}
{234}{}{Wow, okay.}

#Âîïğîñû ïğî ãîğîä âöåëîì -- Ñîëò-Ëåéê:
{235}{}{Gibt es hier einen Ort, an dem man sich entspannen kann?}
{236}{}{Sieh dir zuerst das „Tin Angel“ an. Dort ist es immer lustig, ein wirklich netter Ort. Es gibt auch ein Hotel, in dem du dich ausruhen kannst, und gleich gegenüber eine Handelshalle. Dort gibt es zwei Händler: Der eine verkauft Waffen, der andere allen möglichen Kram.}
{237}{}{Was hält die Stadt eigentlich am Laufen?}
{238}{}{Am wichtigsten ist eine Nuka-Cola-Fabrik. Wenn du dein eigenes Geschäft aufziehen und das Zeug im Ödland verkaufen willst, geh am besten direkt dorthin. Sie liegt östlich vom Zentrum. Aber generell gibt es hier nicht viel zu tun, nicht viele Möglichkeiten ... Ach ja, hier wachsen auch Vocas-Nüsse, die sehr nahrhaft sind. Gleich außerhalb der Stadt gibt es ganze Plantagen davon.}
{239}{}{Und wie sieht es mit der sozialen Lage in der Stadt aus?}
{240}{}{Sie haben ein Büro des Sheriffs. Soweit ich sehe, halten sie den Abschaum fern. Zumindest ist es hier viel sicherer als in New Reno.}
{241}{}{Richtig. Das wär's dann.}
{242}{}{Warte, hier gibt es noch einen Ort, den du meiden solltest. Nur ein freundlicher Hinweis, denn ich sehe, du bist ein guter Mensch und hilfst unseren Leuten. Das wissen wir immer zu schätzen.}
{243}{}{Hm, erzähl schon.}
{244}{}{Provo – ein Viertel südlich von Salt Lake. Wir halten uns immer davon fern, weil sich dort der ganze Abschaum gesammelt hat, den der Sheriff rausgeworfen hat. Diebe, Mörder, Irre – das volle Programm. Geh da nicht hin.}
{245}{}{Okay!}

{246}{}{Weißt du etwas über einen Ort namens Provo?}
{247}{}{Ja. Wenn nicht, wäre ich längst tot, denn dieses Viertel liegt direkt an der Handelsroute. Dort lebt allerlei Abschaum, Leute, die der Sheriff rausgeworfen hat. Eine gefährliche Bande. Halt dich von der Gegend fern.}
{248}{}{Verstanden.}

###############################################################
#       Ğàññïğîñû ïğî Ïóñòîøü
###############################################################

{290}{}{Was für Raider machen euch unterwegs zu schaffen?}
{291}{}{Nun, zunächst einmal wurden die Überfälle und Hinterhalte auf Karawanen in der Region Provo häufiger. Man sagt, dort hätten sich alle möglichen Verbrecher versammelt, die aus der Stadt Salt Lake geflohen sind. Außerdem könntest du dort auf ein paar verrückte Einheimische treffen, die verlernt haben, friedlich zu leben. Nimm dich auch vor ihnen in Acht.}
{292}{}{Noch mehr?}
{293}{}{Eine weitere gefährliche Bande überfällt Reisende zwischen Vegas und der Stadt Salt Lake, ungefähr dort, wo die Straße nach Westen abbiegt. Die Bloom-Brüder führen die Bande an. Es sind nicht viele, aber sie sind echte Killer, hervorragend bewaffnet und äußerst erfahren. Niemand weiß genau, woher sie stammen. Gerüchten zufolge sind es ehemalige Soldaten des Wind of War, die sich dem Rauben und Plündern verschrieben haben. Das müssen sie sein, sonst wären ihre erstklassige Ausrüstung und ihr ausgezeichnetes Verständnis vom Kämpfen kaum zu erklären.}

{294}{}{Am Rand von Reno und Vegas lauern immer ein paar kleine Banden auf dich. Die bekanntesten sind die Windmill-Leute, die Caverners, die Sanders, die Bighorns und die Scorpions. Außerdem lebt südlich der Fernstraße ein Stamm Wilder, die manchmal zum Jagen aus den Bergen herabkommen. Zum Glück trauen sie sich nicht, Karawanen anzugreifen. Von allein reisenden Leuten kann man das nicht behaupten.}
{295}{}{Wilde?}
{296}{}{Sie nennen sich den Stamm der Coyotes, obwohl niemand etwas über sie weiß. Sicher ist, dass sie Kannibalen sind und Waffen benutzen, die sie nach alter Landbautechnik selbst herstellen. Sie leben hoch oben in den Bergen, deshalb geht niemand dorthin. Ein paar seltene Glückspilze haben Straßensperren und verlassene Lager dieser Tiere gesehen. Mehr ist nicht bekannt. Niemand kümmert sich um sie, abgesehen vielleicht von den Sklavenhändlern.}

{300}{}{Sag mal, wie ist es da draußen – im Ödland?}
{301}{}{Im Ödland ist es hart. Wir müssen auf den Vorkriegsstraßen reisen, denn das ist schneller und bequemer, als durch die Wüste zu laufen. Aber die Raider wissen das auch. Deshalb sind wir immer auf der Hut, wenn wir uns Tankstellen und kleinen Siedlungen nähern.}
{302}{}{Zwischen welchen Städten treibst du Handel?}
{303}{}{Also benutzen die meisten Reisenden diese Fernstraßen? Das muss ich mir merken. Leb wohl.}

{304}{}{Welche Siedlungen hast du auf deinen Reisen gesehen?}
{305}{}{Richtig. Das war alles, was ich wissen wollte.}

{306}{}{Ich handle zwischen New Reno und Salt Lake.}
{307}{}{Ich handle zwischen New Reno und Las Vegas.}
{308}{}{Ich handle zwischen New Reno und Las Vegas. Und hier, im Wind des Krieges, legen wir vorübergehend einen Halt ein.}
{309}{}{Ich handle zwischen Las Vegas und Salt Lake.}

{310}{}{Kannst du mir zeigen, wo die zweite Stadt liegt?}
{311}{}{[Der Karawanenhändler zeigt auf der Weltkarte den endgültigen Zielort seiner Karawane] Hier.}
{312}{}{Danke! Aber ich habe noch eine Frage.}
{313}{}{Danke! Das ist genau das, was ich wissen wollte.}

{314}{}{Dieses New Reno. Kannst du es auf der Karte zeigen?}
{315}{}{Ich interessiere mich für Salt Lake. Kannst du es auf der Karte zeigen?}
{316}{}{Las Vegas? Sehr interessant. Kannst du es auf der Karte zeigen?}

{317}{}{Der Standort von New Reno wurde auf deinem Pip-Boy markiert.}
{318}{}{Der Standort der Stadt Salt Lake wurde auf deinem Pip-Boy markiert.}
{319}{}{Der Standort von Las Vegas wurde auf deinem Pip-Boy markiert.}
{320}{}{Kannst du mir diese Städte zeigen?}
{321}{}{Wir handeln an vielen Orten. Aber vorerst haben wir uns hier niedergelassen.}

{322}{}{Noch eine Frage.}
{323}{}{Ich glaube, das waren alle meine Fragen.}

{324}{}{Fast die gesamte Bevölkerung lebt in Städten, nicht in der Wüste. Außer Karawanen und Räubern begegnet man unterwegs nur selten jemand anderem.}

{325}{}{Auf meinem Weg trifft man niemanden außer ein paar Eingeborenen eines Stammes.}
{326}{}{Was ist das für ein Stamm?}
{327}{}{Ein Indianerstamm. Gute Leute, wenn dich ihr übermäßiges Misstrauen gegenüber Fremden nicht stört. Du kannst ihnen eine Menge Lebensmittel abkaufen. Aber ehrlich gesagt trauen sich viele nicht zu ihnen, weil sich auch die Big Louie-Gang dort niedergelassen hat.}
{328}{}{Kannst du mir den Ort auf der Karte zeigen?}
{329}{}{Der Standort von Lovelock wurde auf deinem Pip-Boy markiert.}
{330}{}{[Der Karawanenhändler zeigt auf der Weltkarte den Standort der Siedlung Lovelock und einen Wegpunkt auf seiner Karawanenroute] Genau hier.}

{331}{}{Das ist eine ziemlich belebte Handelsroute, weil Las Vegas und Reno gute Handelsbeziehungen aufgebaut haben. Außerdem gibt es ungefähr auf halber Strecke einen Rastplatz, wo du dich ausruhen und etwas essen kannst.}
{332}{}{Was für ein Rastplatz?}
{333}{}{Das ist eine ziemlich belebte Handelsroute, weil Las Vegas und Reno gute Handelsbeziehungen aufgebaut haben. Außerdem liegt der Wind of War auf dem Weg, wo du dich von der Reise erholen kannst.}
{334}{}{Wind of War? Eine Militärstadt. Dort haben die Soldaten das Sagen. Ehrlich gesagt ist das nicht der beste Ort für einen Zwischenstopp. Die Einheimischen können manchmal ziemlich nervig sein. Aber dort rastet man immer noch besser, als es in der Wüste zu riskieren.}
{335}{}{Kannst du mir zeigen, wo das ist?}
{336}{}{Der Standort von Wind of War, der Siedlung mitten auf der Handelsroute, wurde auf deiner Pip-Boy markiert.}
{337}{}{[Der Karawanenhändler zeigt auf der Weltkarte den Standort von Wind of War, einem Rastplatz mitten auf seiner Handelsroute] Hier.}
{338}{}{Das ist eine ziemlich belebte Handelsroute, weil Las Vegas und Reno gute Handelsbeziehungen aufgebaut haben. Unterwegs kannst du sogar Einheimischen begegnen.}
{339}{}{Das ist eine ziemlich langweilige Handelsroute. Wenn du dich Salt Lake näherst, musst du wegen der Säuregeckos vorsichtig sein. Aber verglichen mit anderen Routen ist es die sicherste. Das Hauptproblem sind vielleicht die Sklavenhändler. Aber Raider sieht man nur sehr selten.}

###############################################################
#       Ğàññïğîñû, êóäà ïóòü äåğæàò
###############################################################

{340}{}{Wohin wollt ihr?}

{341}{}{Siehst du diesen Ausweis? Lies ihn nächstes Mal einfach genauer ... Wir fahren nach New Reno, um mit den Händlern vor Ort Geschäfte zu machen, und dann hängen wir im „El Dorado“ ab, verdammt ja!}
{342}{}{Siehst du diesen Ausweis? Lies ihn nächstes Mal einfach genauer ... Wir fahren nach Salt Lake, um unsere Warenbestände aufzufuellen, und kommen dann hierher zurück, um sie zu verkaufen.}
{343}{}{Siehst du diesen Ausweis? Lies ihn nächstes Mal einfach genauer ... Wir fahren nach Las Vegas, um unsere Warenbestände aufzufuellen, und kommen dann hierher zurück, um sie zu verkaufen.}
{344}{}{Siehst du diesen Ausweis? Lies ihn nächstes Mal einfach genauer ... Wir fahren nach New Reno, um mit den Händlern vor Ort Geschäfte zu machen, und dann hängen wir im „El Dorado“ ab, verdammt ja!}
{345}{}{Vorerst nirgendwohin. Wir bleiben ein paar Tage hier und ruhen uns aus. Dann fahren wir nach Vegas, um unsere Warenbestände aufzufuellen.}
{346}{}{Siehst du diesen Ausweis? Lies ihn nächstes Mal einfach genauer ... Wir fahren nach Las Vegas, um Handel zu treiben. In Vegas gibt es noch gute Ausrüstung und sauberes Wasser, und in Salt gibt es weniger Probleme mit der Versorgung mit Essen und natürlich Cola!}
{347}{}{Siehst du diesen Ausweis? Lies ihn nächstes Mal einfach genauer ... Wir fahren nach Salt Lake, um Handel zu treiben. In Vegas gibt es noch gute Ausrüstung, und das Wasser dort ist sauber. Außerdem gibt es in Salt weniger Probleme mit der Lebensmittelversorgung und natürlich Cola!}
{348}{}{Vorerst nirgendwohin. Wir müssen uns ausruhen, unsere Ausrüstung bereitmachen und dann brechen wir auf.}

{349}{}{Kann ich eure Karawane auf ihren Reisen begleiten?}
{350}{}{Nein, denk nicht mal dran. Wir sind voll. Und wir nehmen nicht gern Fremde mit, das ist zu gefährlich.}
{351}{}{Schade. Aber ich habe noch eine andere Frage.}
{352}{}{Wie schade. Ich gehe dann mal und frage jemand anderen.}
{353}{}{Schon gut, aber ich würde gern etwas über die Stadt fragen.}
{354}{}{Na gut, vergiss es.}

{359}{}{Die Karawanenroute nach Bridgeport ist eröffnet.}
{360}{}{Bridgeport braucht ein paar Dinge. Hier ist die Liste. Übernimmst du den Auftrag?}
{361}{}{Ja, das klingt nach einem guten Geschäft. Es liegt sowieso auf unserem Weg.}
{362}{}{Großartig. Von jetzt an kannst du dich allein darum kümmern.}
{363}{}{Ich wäre interessiert, wenn nicht dein Ruf wäre, wie er ist.}
{364}{}{[Gehen]}
{365}{}{Ehrlich gesagt wirkt dieser Handel selbst in dieser für uns schwierigen Zeit nicht besonders vielversprechend. Wir müssten viel zu weit reisen, und die Bezahlung ist nicht gerade üppig. Das könnte uns sogar etwas kosten. Zu riskant.}
{366}{}{Ich kann dir ein gutes Geschäft versprechen. Mein Ruf unter den Karawanenhändlern spricht für sich.}
{367}{}{Schade, dass ich kein Karawanenhändler bin, denn eine gute Karawanenroute zu verlieren, wäre einfach dumm.}
{368}{}{Entweder du gehst das Risiko ein, oder jemand anderes tut es. Deine Entscheidung.}
{369}{}{Mit diesem Trick kommst du bei mir nicht durch.}

###############################################################
#       Ïğîäàæà ÿäåğ-êîëû â Âåòğå Âîéíû
###############################################################

{400}{}{Der Wind des Krieges ist bereit, Cola zu handeln, aber ich brauche einen Lieferanten. Bist du dabei?}

{401}{}{Ha! Bist du verrückt?! Du willst, dass unsere Leute mit diesem Abschaum zusammenarbeiten?! Eher beißt ein Radskorpion sich den eigenen Schwanz ab, als dass du einen von uns für diese Blutsauger arbeiten siehst.}
{402}{}{Wie du willst, aber ich habe noch eine andere Frage.}
{403}{}{Wow, ich sehe, ihr habt ein angespanntes Verhältnis zu ihnen. Dann komme ich ohne dich aus.}

{404}{}{Wind of War? Nein, wir nehmen eine andere Route.}
{405}{}{Schade, aber ich habe noch eine Frage.}
{406}{}{Na gut, wie du willst.}

{407}{}{Bewundernswert. Aber was hat das mit uns zu tun? Wir haben eine ganz andere Route, wir fahren zwischen Vegas und Salt Lake hin und her.}
{408}{}{}
{409}{}{Du bist wohl nicht ganz bei Trost! Wie sollen wir Cola aus Salt Lake in eine so weit entfernte Gegend bringen?! Wir kennen die Gegend außerdem nicht, keiner von uns war je dort.}
{410}{}{Ehrlich gesagt ist das keine schlechte Idee. Sag mir nur eins: Wer wird uns beliefern? Zwischenhändler sind zu teuer – bei solchen Preisen verlierst du alle Kunden, glaub mir.}
{411}{}{Es gibt eine Karawane aus Salt Lake. Alles ist mit ihnen vereinbart. Direkte Lieferung aus Salt Lake, und ihr bringt die Ware von Vegas zum Wind des Krieges.}
{412}{}{Kannst du sie nicht selbst aus Salt Lake herbringen?}
{413}{}{Nein, die Reise ist zu lang. Aber wir können die Ware von jemandem in Vegas übernehmen und dann auf dem Weg nach Reno beim Wind des Krieges Halt machen. Das wäre das Beste.}
{414}{}{Das heißt, ich muss zuerst die Lieferung aus Salt Lake nach Vegas organisieren? Oje, das wird schwierig.}
{415}{}{Ausgezeichnet! Die Bedingungen gefallen mir. Wer bezahlt uns?}
{416}{}{Ein Händler im Wind des Krieges, den ihr beliefern werdet.}
{417}{}{Na gut. Und du ... Ähm, du sagst also, dass du ein offizieller Vertreter bist? Kann ich die Papiere sehen?}
{418}{}{Kein Problem! Hier ist die Lizenz. Unterschrieben und besiegelt. Alles ist in Ordnung.}
{419}{}{Ich habe sie nicht dabei.}
{420}{}{Na gut! Wir können sofort losfahren.}
{421}{}{Großartig! Ich erkläre dir die Einzelheiten, und danach bist du auf dich allein gestellt ...}
{422}{}{Nun, beweise, dass man dir vertrauen kann, dann machen wir ein Geschäft. Ich kann hier kein Risiko eingehen.}
{423}{}{Ist das wirklich so wichtig?! Verdammt, na schön, ich suche nach dem Papier ...}
{424}{}{Andererseits, zum Teufel mit den Formalitäten. [murmelt vor sich hin] Warum sollte uns das kümmern ... [spricht zu dir] Einverstanden.}
{425}{}{Gut! Ich erkläre dir die Einzelheiten, und danach bist du auf dich allein gestellt ...}

{426}{}{Du hast erfolgreich die Handelsroute von Nuka-Cola nach Wind of War eingerichtet. Jetzt musst du nur noch den Handel mit dem Intendanten abschließen.}

###############################################################
#       Ïğîäàæà ÿäåğ-êîëû â Âåãàñå
###############################################################

{450}{}{Ich richte in Vegas einen Handelsstützpunkt für Nuka-Cola ein und brauche einen Lieferanten. Übernimmst du den Auftrag?}
{451}{}{Dafür brauchen wir einen Karawanenzug, der Cola direkt nach Vegas zu einer anderen Karawane bringt, die sie dann weiter nach Wind of War transportiert. Verstehst du?}

{452}{}{Unsere eigene Lieferroute? Gute Idee, wenn du dort einen Abnehmer hast. Außerdem sind wir ohnehin auf dieser Route unterwegs.}
{453}{}{Unsere eigene Lieferroute? Hm! Gute Idee, wenn du dort einen Abnehmer hast. Aber wir haben eine andere Route geplant. Eine unbekannte Route, und dazu noch so weit ... Nein. Nein, die Jungs werden so einen Handel nicht akzeptieren.}
{454}{}{Schade. Noch eine Frage.}
{455}{}{Schade. Ich suche mir jemand anderen.}

{456}{}{Ja, dort gibt es einen Handelsstützpunkt, und keinen schlechten. Also? Übernimmst du den Auftrag?}
{457}{}{Gute Idee! Na los, erzähl mir die Einzelheiten. Wem bringen wir die Ware?}
{458}{}{Also, es läuft so ...}
{459}{}{Gute Idee, nur ... äh, hast du die Papiere dafür? Kann ich sie mir ansehen?}
{460}{}{Klar. Hier ist die Lizenz.}
{461}{}{Ich habe die Lizenz gerade nicht dabei. Ist das so wichtig?}
{462}{}{Hm. Weißt du, du hast recht. Was kümmert's mich? Ware ist Ware, und der Käufer steht schon bereit. Na los, erzähl mir die Einzelheiten.}
{463}{}{Okay, hör zu ...}
{464}{}{Die Jungs müssen sicher sein, dass es keine Hinterhalte gibt, verstehst du? Also beweise erst, dass man dir vertrauen kann, dann können wir ins Geschäft kommen.}
{465}{}{Ach, zum Teufel! Nicht mal das Geld überzeugt ihn! Urgh, na schön, wir sehen mal, was wir hier tun können.}
{466}{}{Das nenne ich ein Geschäft! Die Papiere sind in Ordnung, und der Plan ist durchdacht! Na los, erzähl mir die Einzelheiten. Ich bin bereit, mit dir zusammenzuarbeiten.}
{467}{}{Okay, also, es läuft so ...}
{468}{}{Du hast deine eigene Versorgungslinie für Nuka-Cola nach Las Vegas eingerichtet! Jetzt musst du nur noch den Handel mit dem Käufer abschließen.}

{469}{}{Klingt verlockend. Aber ich gehe das Risiko erst ein, wenn wir die Einzelheiten mit der Cola-Fabrik besprechen und Garantien bekommen, dass ihr uns nicht reinlegt. Dann brauche ich nicht einmal deine Lizenz. Also treffe ich dich in Salt Lake – dann reden wir über Geschäfte.}
{470}{}{Hmm. Nun, wie du willst. Aber ich habe eine Frage.}
{471}{}{Na gut. Dann sehen wir uns in Salt Lake.}

###############################################################
#       Ïğîäàæà ÿäåğ-êîëû â Íüş-Ğèíî
###############################################################

{480}{}{Ein Lieferant für Nuka-Cola von Salt Lake nach Reno wird gesucht. Bist du dabei?}

{481}{}{Wenn wir in Salt Lake wären, dann ja. Aber solange wir hier sind, können wir das Risiko nicht eingehen. Dort in Salt Lake können wir direkt zur Fabrik gehen und alle Einzelheiten besprechen, um Garantien gegen die vielen Unwägbarkeiten zu bekommen.}
{482}{}{Bevor ich nach Salt Lake aufbreche, möchte ich noch eine Frage stellen.}
{483}{}{Hmm. Das heißt, die Karawanen in Salt Lake können den Auftrag annehmen? Großartig! Dann mache ich mich auf den Weg nach Salt Lake.}

{484}{}{Keine schlechte Idee. Und die Fabrik ist nicht weit von hier. Ich zähle schon den Gewinn.}
{485}{}{Also, abgemacht?}
{486}{}{Wow, Kumpel, wir nehmen eine andere Route. In den Gegenden waren wir noch nie. Tut mir leid.}
{487}{}{Stimmt. Trotzdem habe ich eine Frage.}
{488}{}{Na gut. Dann viel Glück.}

{489}{}{Du hast deine eigene Versorgungslinie für Nuka-Cola nach New Reno organisiert! Bald wirst du reich ... Vielleicht.}

###############################################################
#       Ïğîäàæà ÿäåğ-êîëû
###############################################################

{500}{}{Ich möchte eine Lieferung in eine andere Stadt bestellen.}
{501}{}{Gute Idee! Aber wir fahren nur auf unserer eigenen Route. Und natürlich berechnen wir für den Auftrag unseren Anteil.}
{502}{}{Wie viel?}

{503}{}{ Prozent vom Gesamtbetrag. Ja, übrigens, wie viel hast du im Lager? Ich will keine kleinen Lieferungen ausfahren – zu viel Aufwand für zu wenig Gewinn. Wenn du handeln willst, dann beladen wir die Waggons voll!}
{504}{}{Was?! 15% - orIch suche mir eine andere Karawane.}
{505}{}{Du übergibst 1000 Flaschen.}
{506}{}{Du übergibst 750 Flaschen.}
{507}{}{Du übergibst 500 Flaschen.}
{508}{}{Du übergibst 300 Flaschen.}
{509}{}{Du übergibst 200 Flaschen.}
{510}{}{Du übergibst 100 Flaschen.}
{511}{}{Ich werde darüber nachdenken.}

{512}{}{Gut. Wohin bringen wir sie?}
{513}{}{„Cotton“-Café in New Reno.}
{514}{}{„Silver“-Restaurant in New Reno.}
{515}{}{„Hard Rock“-Café in Vegas.}
{516}{}{Handelsladen in Wind of War.}
{517}{}{Noch nirgendwo. Ich muss erst noch einen Deal mit dem Käufer abschließen.}

{518}{}{Kein Problem. Wir liefern die Ware und nehmen }
{519}{}{ Prozent vom Gesamtwert der Flaschen. Hoffentlich ist das nicht unser letzter Deal.}
{520}{}{Gut, fangt an!}

{521}{}{Hey, wir nehmen eine andere Route. Ich glaube nicht, dass unser Team einfach völlig unbekanntes Gebiet durchqueren will. Frag die, die nach Reno unterwegs sind.}
{522}{}{Okay, vielleicht kannst du die Cola dann in eine andere Stadt bringen?}
{523}{}{Dann brauche ich deine Dienste nicht. Leb wohl.}
{524}{}{Hey, wir nehmen eine andere Route. Ich glaube nicht, dass unser Team einfach völlig unbekanntes Gebiet durchqueren will. Frag die, die nach Vegas unterwegs sind.}

{525}{}{ oder gar nichts! Keine anständige Karawane würde für weniger arbeiten.}
{526}{}{Verdammt, so einen Deal würde ich nur ungern verlieren ... Na gut! }
{527}{}{ Prozent – und wir sind im Geschäft. Das ist unser letzter Preis.}

#Female character:
{1150}{}{Ich wollte etwas über diese Stadt fragen.}
{1228}{}{Warte kurz, ich glaube, ich habe so jemanden schon mal bei einer anderen Karawane gesehen. Frag dich herum, vielleicht findest du etwas darüber heraus.}
{1305}{}{Richtig. Das war alles, was ich wissen wollte.}
{1323}{}{Ich glaube, das war alles, was ich fragen wollte.}
{1353}{}{Schon gut, aber ich würde gern etwas über die Stadt fragen.}
{1462}{}{Hm. Weißt du, eigentlich hast du recht. Was kümmert's mich? Ware ist Ware und der Käufer steht schon bereit. Also los, erzähl mir die Einzelheiten.}
{1409}{}{Du bist verrückt! Wie sollen wir Cola von Salt Lake in eine so weit entfernte Gegend bringen?! Wir kennen uns dort überhaupt nicht aus, keiner von uns war je dort.}
{1486}{}{Wow, Mädchen, wir nehmen eine andere Route. In der Gegend waren wir noch nie. Tut mir leid.}
