{100}{}{Karawanenführer.}

#Ñëó÷àéíîå îïèñàíèå
{101}{}{Du siehst einen der Karawanenführer.}
{102}{}{Du siehst einen der Karawanenführer. Er wirkt etwas angespannt.}
{103}{}{Du siehst einen der Karawanenführer. Er ist nervös.}
{104}{}{Du siehst einen der Karawanenführer. Es scheint, als hätte er lange nicht geschlafen.}

#Ïîïûòêà çàãîâîğèòü
{110}{}{Hallo.}
{111}{}{Was brauchst du? Siehst du nicht, dass ich beschäftigt bin ...}
{112}{}{Hör mal, ich bin müde. Such dir also jemand anderen zum Reden, klar?}
{113}{}{Such unseren Boss – er trifft alle Entscheidungen, nicht ich.}
{114}{}{Das musst du mit unserem Boss besprechen.}

#Ïîïûòêà çàãîâîğèòü ïğè îòğèöàòåëüíîé ğåïóòàöèè ó êàğàâàíùèêîâ
{120}{}{Äh ... Hör mal, warum redest du nicht mit jemand anderem darüber?}
{121}{}{Ähem ... Unsere Karawane ist startklar. Also dann – mach's gut.}
{122}{}{Äh ... Wir brauchen Leute wie dich nicht.}
{123}{}{Du schon wieder?! Willst du uns provozieren?}
{124}{}{Hey, soll ich dich einfach erschießen?}
{125}{}{Hör zu, lass mich einfach in Ruhe, klar?}

#Êàğàâàíñêèå ôğàçû:
{200}{}{::pfeift::}
{201}{}{Diesmal gehe ich nicht campen.}
{202}{}{Zeit, diesen Job an den Nagel zu hängen.}
{203}{}{Manche sagen, die Einheimischen in Washington würden eine Blindgängerbombe anbeten. Was für Idioten!}
{204}{}{Lokales Wasser zu trinken ist keine gute Idee. Der Geigerzähler spielt dabei verrückt.}
{205}{}{Die Händler in Brahmin haben die Preise schon wieder erhöht.}
{206}{}{Zwei Wochen von Redding entfernt – ein harter, beschwerlicher Weg.}
{207}{}{Vor einem Monat waren wir in San Francisco. Überall Ruinen.}
{208}{}{Vegas wird ganz sicher die neue Hauptstadt Amerikas!}
{209}{}{Salt Lake City ist eine gute Stadt, aber schmutzig.}
{210}{}{Reno ist vielleicht die gefährlichste Stadt, die ich je gesehen habe.}
{211}{}{Ein paar meiner Freunde sind vor einer Woche nach Reno gezogen, und jetzt fressen sie die Würmer.}
{212}{}{Reno ist eine schöne Stadt – bring jemanden um, und niemand wird es bemerken.}
{213}{}{Wir sollten nicht zu lange bleiben – handeln und wieder auf die Straße.}
{214}{}{Manchmal sind die Straßen zwischen den Städten weniger gefährlich als die Städte selbst.}
{215}{}{Hier möchte ich nicht leben.}
{216}{}{Zum Glück bin ich nur auf der Durchreise.}
{217}{}{Neue Option für den Karawanendienst – brahmin an der Nase herumführen ... Ha-ha-ha!}
{218}{}{Ich muss Wasservorräte auffüllen. Wo ist der nächste Brunnen?}
{219}{}{Staubstürme sind tückisch. Sie reißen einen von den Beinen.}
{220}{}{Nachts sind wir nach Reno gefahren – sieht unheilvoll aus!}
{221}{}{Die Stadt des Paradieses? Die da oben im Norden? Natürlich ein Mythos.}

#Âåãàñ, ïëàâàşùèå ôğàçû, êîãäà ğàáû èç çàãîíà îñâîáîæäåíû:
{300}{}{Viele Leute verlassen die Stadt. Wer sind die?}
{301}{}{Ist dir aufgefallen, wie viele Leute diesen Ort verlassen?}
{302}{}{In letzter Zeit gibt es ziemlich viele Einwanderer ...}
{303}{}{Heutzutage wollen viel zu viele Leute Karawanen begleiten.}
{304}{}{Wer sind diese Migranten? Sind das nicht entflohene Sklaven?}
{305}{}{Auf der Straße heißt es, die Sklavenhändler hätten ihre Sklavenlieferung verloren.}
{306}{}{Daher kommt also das Einkommen der Leute ...}
{307}{}{Woher kommen all diese Migranten?}
{308}{}{Wer sind all diese Flüchtigen?}
{309}{}{Wir brauchen keine weitere Begleitung.}
