{100}{}{Du siehst Super 8.}
{101}{}{Du siehst ein monströses Wesen mit einem furchterregenden Blick. Auf seiner Stirn ist die verkohlte Aufschrift „Super 8“ zu sehen, und in seinen Augen erkennst du den Hass auf die ganze Menschheit.}
{102}{}{Deathclaw dringt in deinen Geist ein, und du erliegst der Einschüchterung.}
{103}{}{ erliegt der Einschüchterung durch seinen Blick.}

{110}{}{[Aus der Dunkelheit tritt lautlos ein schreckliches Monster hervor; seine schwarzen Augen durchbohren dich, und sofort kommt dir der Gedanke, dass du für Hypnose empfänglich bist] N-nicht bewegen, M-mensch! Ich habe so lange gebraucht, dich aufzuspüren, um dir dein s-schwarzes Herz herauszureißen!}
{111}{}{Oh nein, ein sprechendes Tier! Verschwinde! Stirb!}
{112}{}{Warte, wovon redest du? Warum musst du mich jagen und töten?}
{113}{}{R-Rache! Rache für meine Br-Brüder und -Schwestern! Sie fielen durch deine Hand! Du wirst als Nächstes sterben!}
{114}{}{Du meinst die Kreaturen im Vault? Aber sie haben mich und andere Leute angegriffen!}

{115}{}{Grrr! Ich kann nichts Böses in dir spüren, aber du wirst trotzdem sterben! Ich kann nicht verzeihen!}
{116}{}{Grrr! Ich kann dein sch-Schwarzes Herz riechen! Es ist vergiftet, es zerstört alles Leben in deiner Nähe! Mach dich auf den T-Tod gefasst!}
{117}{}{Na gut, du willst kämpfen, du kriegst einen Kampf, wie alle anderen auch. Na los, du übergroßer Truthahn! Zeig mir, was du draufhast!}
{118}{}{O-oh, ich muss hier weg...}

{119}{}{Es tut mir leid, was geschehen ist. Ich bitte dich weder um Vergebung noch darum, mich zu verstehen. Deine Gefühle... Dein Hass... Sie sind gerechtfertigt. Du hast allen Grund, mich zu hassen. Nimm mein Leben – ich habe es verdient.}
{120}{}{[Überrascht macht er einen Schritt zurück] Du... Bist bereit, dein L-Leben für Gerechtigkeit zu geben?}
{121}{}{Ja. Sieh nur, ich bin unbewaffnet. Nimm mein Leben als Strafe.}
{122}{}{Dummer M-Mensch!!! [Er schwingt seine Klaue und hält sie abrupt dicht vor deiner Halsschlagader an] Grrr... [Er blickt dir in die Augen] Das kann nicht sein... [Er senkt seine Pfote und geht davon]}
{123}{}{Also, verzeihst du mir?}
{124}{}{[Er bleibt stehen und blickt zu dir zurück] NEIN! [Dann verschwindet er wie ein Blitz in der Dunkelheit]}
{125}{}{Puh... Den werde ich so schnell nicht vergessen...}

{1120}{}{[Überrascht macht er einen Schritt zurück] Du... Bist bereit, dein L-Leben für Gerechtigkeit zu geben?}
