{100}{}{Du siehst einen Black Jack-Tisch.}
{101}{}{Du siehst einen Black Jack-Dealer.}
# Care to play some Black Jack? Minimum bet is $(money amount).
{102}{}{Lust auf eine Runde Black Jack? Mindesteinsatz: $}
{103}{}{.}
{104}{}{Klar.}
{105}{}{Nein, danke.}
{106}{}{Wuh blak juk?}
{107}{}{Tut mir leid, du scheinst nicht den Mindesteinsatz zu haben. Komm wieder, wenn du mehr Geld hast.}
{108}{}{Gut, alle Mindesteinsätze sind gesetzt.}
{109}{}{[Geben]}
#This is a Black Jack table. Minimum bet is $(dollar amount).
{110}{}{Das ist ein Black Jack-Tisch. Der Mindesteinsatz beträgt $}
{111}{}{.}
# You draw a (card face like #201-213) of (card suit like #251-254), a
#    (card face like #201-213) of (card suit like #251-254) and a
#    (card face like #201-213) of (card suit like #251-254) for
#    (Black Jack, a bust, or the total of the cards ranging from 15-21)
{112}{}{Du ziehst }
{113}{}{ von }
{114}{}{ und }
{115}{}{ und }
{116}{}{ für }
{117}{}{. Black Jack}
{118}{}{. Überkauft}
{119}{}{.}
# this is to replace the first part of the previous dialogs with the dealer
#    instead, it just replaces #112
{120}{}{Der Dealer hat }
{121}{}{[Mehr]}
{122}{}{[Mischt die Karten] Noch eine Runde?}
{123}{}{Tut mir leid, ich glaube, du hast hier dein Limit erreicht. Ich muss dich bitten zu gehen.}
{124}{}{Du gewinnst die Runde.}
{125}{}{Der Dealer gewinnt die Runde.}
{126}{}{Das Spiel macht Freude.}
{127}{}{Klar, kein Problem.}
{128}{}{Ich zeige dir mein Limit.}
{129}{}{Du darfst hier nicht mehr spielen. Bitte geh.}
{130}{}{Ohhh, tut mir leid.}
{131}{}{Du gewinnst $}
{132}{}{.}

{201}{}{Ass}
{202}{}{zwei}
{203}{}{drei}
{204}{}{vier}
{205}{}{fünf}
{206}{}{sechs}
{207}{}{sieben}
{208}{}{acht}
{209}{}{neun}
{210}{}{zehn}
{211}{}{Bube}
{212}{}{Dame}
{213}{}{König}

{251}{}{Herz}
{252}{}{Karo}
{253}{}{Pik}
{254}{}{Kreuz}