{0}{}{Kleine Waffen}
{1}{}{Große Waffen}
{2}{}{Energiewaffen}
{3}{}{Unbewaffnet}
{4}{}{Nahkampfwaffen}
{5}{}{Werfen}
{6}{}{Erste Hilfe}
{7}{}{Arzt}
{8}{}{Schleichen}
{9}{}{Schlösser knacken}
{10}{}{Stehlen}
{11}{}{Sprengstoffe}
{12}{}{Wissenschaft}
{13}{}{Reparieren}
{14}{}{Redekunst}
{15}{}{Tauschhandel}
{16}{}{Glücksspiel}
{17}{}{Überlebenskunst}

{18}{}{(Wissenschaft + Reparatur + Glücksspiel)}

{20}{}{Stärke}
{21}{}{Wahrnehmung}
{22}{}{Ausdauer}
{23}{}{Charisma}
{24}{}{Intelligenz}
{25}{}{Beweglichkeit}
{26}{}{Glück}
{27}{}{Max. Traglast}
{28}{}{Ruf}
{29}{}{Anatomische Chemie}
{30}{}{Karma}
{31}{}{Stufe}
{32}{}{Tötungen}
{33}{}{Alter}
{34}{}{Schnellschuss}

{39}{}{Privatdetektiv}
{40}{}{Kindermörder}
{41}{}{Cheyenne-Räuber}
{42}{}{Grabräuber}
{43}{}{Grabräuber / Stehlen }
{44}{}{Karawanen: Gepriesen / Feilschen }
{45}{}{Karma 250 / Charisma 9 / Sprache }
{46}{}{Sexappeal / Charisma }
{47}{}{}
{48}{}{Ruf:Gepriesen}
{49}{}{Ruf:Karawanen}

{50}{}{[}
{51}{}{] }
{52}{}{[Erforderlich: }
{53}{}{]}
{54}{}{; }
{55}{}{ / }
{56}{}{/}
{57}{}{ und }
{58}{}{[Chancen: }

{60}{}{Strahlung, Gift, Abhängigkeit}
{61}{}{Abhängigkeit}
{62}{}{New Reno Stern}
{63}{}{Stufe 9 / Beliebige Kampffertigkeit}

{94}{}{.}
{95}{}{Neuer Ort auf der Karte entdeckt: }

{96}{}{ Punkt(e).}
{97}{}{Du verlierst Karma }
{98}{}{Du gewinnst Karma }
{99}{}{Du hast die Koordinaten von Area 51 erhalten.}
