# 0. QUICK LOOK
{100}{}{Du siehst einen Dealer.}
{101}{}{Du siehst einen Würfeltisch.}
{102}{}{Lege vor dem Spielen alle gefährlichen Gegenstände ab.}

# has no gambling skill messages
{110}{}{Du siehst ein Mädchen.}
{111}{}{Du siehst einen Tisch.}

{112}{}{Ergebnisse: }
{113}{}{ zu }
{114}{}{ zu deinen Gunsten.}
{115}{}{ zugunsten des Casinos.}

# 0. EXAMINES
# table
{140}{}{Du siehst einen Tisch für Würfelspiele.}
# no skill
{141}{}{Du siehst einen Tisch mit Kram darauf.}

# dealer
{150}{}{Du siehst eine der Croupiers im Casino.}
{151}{}{Du siehst eine der Croupiers im Casino. Sie winkt dich heran, um mit dir zu spielen.}
{152}{}{Du siehst eine der Croupiers im Casino. Ihr Kleid bedeckt kaum ihren Körper.}
{153}{}{Du siehst eine der Croupiers im Casino. Sie hat ein paar schöne Knarren.}
{154}{}{Du siehst eine der Croupiers im Casino. Sie zwinkert dir zu.}
{155}{}{Du siehst eine der Croupiers im Casino. Sie riecht wiiirklich gut.}

# use gambling skill on dealer
# dealer dice amounts are screwed up
{175}{}{KEINE WÜRFEL!!!}
{176}{}{ZU VIELE WÜRFEL!!!}
# dealer has loaded dice planted by player
{177}{}{Die Gewinnchancen scheinen zu stimmen, seit du die Würfel gewechselt hast.}
{178}{}{Die Gewinnchancen stimmen nicht ganz.}
{179}{}{Du kannst die Gewinnchancen nicht mit Sicherheit bestimmen.}
# dealer has regular dice
{185}{}{Die Gewinnchancen scheinen ungefähr zu stimmen.}
{186}{}{Du kannst die Gewinnchancen nicht mit Sicherheit bestimmen.}
{187}{}{Die Gewinnchancen stimmen nicht ganz.}


# 3. FLOAT [MADE MAN, SAME CASINO] (WTG)
{215}{}{Hallo, }
{216}{}{Wenn du später ein bisschen Gesellschaft suchst ...}
{217}{}{Hey, du ... [zwinkert] ... Willst du spielen?}
{218}{}{Er sieht so ... [schaudert] ... gefährlich aus.}
{219}{}{Willkommen im Casino, }
{220}{}{Leg ein gutes Wort für mich bei deinem Boss ein.}
{221}{}{Hallo, meine Dame. Sag Bescheid, wenn ich dir irgendwie helfen kann.}
{222}{}{Möchtest du spielen, meine Dame?}
{223}{}{Sie sieht so ... [schaudert] ... gefährlich aus.}

# 5. FLOAT [MADE MAN, WRONG CASINO] (WTG)
{235}{}{Sieht aus, als würde dieser Kerl schon mit seinem Leben spielen.}
{236}{}{Äh, ich glaube, er ist gerade ins falsche Casino gelaufen ...}
{237}{}{Wenn er nicht verschwindet, bevor die Jungs ihn sehen ...}
{238}{}{Oh-oh. Ärger ...}
{239}{}{Sieht aus, als würde diese Frau schon mit ihrem Leben spielen.}
{240}{}{Äh, ich glaube, sie ist gerade ins falsche Casino gelaufen ...}
{241}{}{Wenn sie nicht verschwindet, bevor die Jungs sie sehen ...}


# 9. FLOAT [PORN STAR] (WTG)
{270}{}{Na, Filmstar. Willst du ein paar Chips loswerden?}
{271}{}{Hey, }
{272}{}{Hey, }
{273}{}{Wenn du ein paar Chips gewinnen willst }
{274}{}{Lady Luck ist heute Abend hier ... Nur Gewinner!}
{275}{}{Tritt näher, }
{276}{}{Noch einen Drink?}
{277}{}{Willkommen im Casino, }
{278}{}{Na, Frau Filmstar. Willst du deinen Gehaltsscheck auf den Kopf hauen?}
{279}{}{Tanzt du heute Abend?}

# 11. FLOAT [MALE, NO REP] (WTG)
{290}{}{Na, Süße. Willst du ein paar Chips loswerden?}
{291}{}{Hey, Süße ... [zwinkert] ... Willst du spielen?}
{292}{}{Hey, Süße ... [lächelt] ... Willst du dein Glück versuchen?}
{293}{}{Wenn du ein paar Jetons gewinnen willst, bist du hier genau richtig.}
{294}{}{Lady Luck ist heute Abend hier ... Nur Gewinner!}
{295}{}{Nur näherkommen, hier kannst du Jetons gewinnen.}
{296}{}{Noch einen Drink, Liebling?}
{297}{}{Willkommen im Casino, Liebling.}
{298}{}{Dieser Tisch ist frei, wenn du spielen willst ... }
{299}{}{Na, Liebling. Willst du ein paar Jetons loswerden?}
{300}{}{Willst du spielen, Liebling?}
{301}{}{Willkommen im Casino, Liebling.}

# 13.  PLACE YOUR BETS (WTG)
{320}{}{[Die Croupière sieht dich nervös an und kaut dann auf ihrer Lippe.] Ähm, setzt eure Einsätze ... Mindesteinsatz: $}
{321}{}{Setzen Sie Ihren Einsatz, mein Herr. Mindesteinsatz: $}
{322}{}{Setzen Sie Ihren Einsatz, gnädige Frau. Mindesteinsatz: $}
{323}{}{Setzt eure Einsätze, Mindesteinsatz: $}
{324}{}{Ich wet-ter als du}
{325}{}{Ich spielen Craps in Hose}
{326}{}{Was das für Spiel? Kann man Geckohäute setzen? Ich haben Geck ... Ooooh ... Hübsche Lichter! [schlendert davon]}
{327}{}{[Du hast $}
{328}{}{Einsatz: $}
{329}{}{Whoa, das ist mir zu viel.}
{330}{}{Heute keine Einsätze, danke.}
{331}{}{Äh, tut mir leid, ich weiß nicht, wie man diese verrückten Spiele spielt.}

# 14.  RETARD (14)
{340}{}{Ähm ... Ich habe gehört, hinten werden Gehirne verschenkt. Vielleicht solltest du mal nachsehen.}
{341}{}{Äh, sehr wohl, mein Herr. Kommen Sie bald wieder.}
{342}{}{Äh, sehr wohl, gnädige Frau. Kommen Sie bald wieder.}
{343}{}{Tschüüüss}
{344}{}{Fein. }
{345}{}{Äh ... Gehirne ... Was das?! Ich gehen schauen!}

# 15. POOR MAN (13)
{350}{}{Sehr wohl, mein Herr. Kommen Sie bald wieder.}
{351}{}{Sehr wohl, gnädige Frau. Kommen Sie bald wieder.}
{352}{}{[Der Croupier hebt eine Augenbraue.] $}
{354}{}{Mach ich, danke.}
{355}{}{Vielleicht.}

# 16. LOOOOOOSER (13)
{400}{}{Tut mir leid, vielleicht hast du nächstes Mal mehr Glück.}
{401}{}{Tut mir leid, mein Herr. Vielleicht haben Sie nächstes Mal mehr Glück.}
{402}{}{Tut mir leid, gnädige Frau. Vielleicht haben Sie nächstes Mal mehr Glück.}

{410}{}{Gewonnen!}
{411}{}{Gewonnen! Gut gemacht, mein Herr!}
{412}{}{Gewonnen! Gut gemacht, meine Dame!}

{420}{}{Gewonnen! Du hast deinen Einsatz verdoppelt!}
{421}{}{Gewonnen! Du hast deinen Einsatz verdoppelt! Gut gemacht, mein Herr!}
{422}{}{Gewonnen! Du hast deinen Einsatz verdoppelt! Gut gemacht, meine Dame!}

{430}{}{Gewonnen! Du hast deinen Einsatz verdreifacht!}
{431}{}{Gewonnen! Du hast deinen Einsatz verdreifacht! Das Glück ist heute Abend im Haus! Gut gemacht, mein Herr!}
{432}{}{Gewonnen! Du hast deinen Einsatz verdreifacht! Das Glück ist heute Abend im Haus! Gut gemacht, mein Herr!}

{440}{}{Mach Schluss für heute.}
{441}{}{Mach Schluss für heute Abend.}

{445}{}{Tut mir leid, dieser Tisch ist vorübergehend geschlossen. Benutze einen anderen, wenn du weiterspielen möchtest.}
{446}{}{Tut mir leid, der Tisch ist geschlossen. In ein paar Minuten wird er wieder geöffnet.}
{447}{}{Tisch geöffnet}

#17. TABLE TAMPER
{450}{}{Tut mir leid, dieser Tisch wurde geschlossen. Jemand hat an den Würfeln herumgepfuscht.}
{451}{}{Tut mir leid, mein Herr, dieser Tisch wurde geschlossen. Jemand hat an den Würfeln herumgepfuscht.}
{452}{}{Tut mir leid, meine Dame, dieser Tisch wurde geschlossen. Jemand hat an den Würfeln herumgepfuscht.}
{453}{}{Äh, okay.}
{454}{}{Das tut mir leid. Danke.}

# message parts
{2203}{}{! Willkommen im Casino, Held!}
{2215}{}{ Kann ich dir bei ... *irgendetwas* helfen?}
{2219}{}{.}
{2255}{}{ Willst du ein paar Chips ausgeben?}
{2258}{}{, gewinne ein paar Chips.}
{2260}{}{.}
{2261}{}{. Sag mir Bescheid, wenn ich dir irgendwie helfen kann.}
{2262}{}{?}
{2263}{}{.}
{2321}{}{. Mach deine Einsätze ... }
{2327}{}{.] }
{2328}{}{.}
{2344}{}{ könnte immer einen neuen Inventargegenstand gebrauchen [Gehen.]}
{2352}{}{? „Zu reich für dich?“ [Schnaubt.] Kumpel, du bist in der falschen Stadt.}
{2353}{}{? „Zu reich für dich?“ [Schnaubt.] Mädchen, du bist in der falschen Stadt.}
