{100}{}{Das bringt nichts.}
{101}{}{Du kannst diese Tьr nicht цffnen.}
{102}{}{Du musst zuerst mit dem Mann dort drьben sprechen.}

#Для дверей в Вегасе на карте работорговцев
{103}{}{Du siehst eine vernagelte Tьr.}
{104}{}{Diese Tьr ist fest am Tьrpfosten angenagelt.}

#Для дверей лифта на дамбе
{105}{}{Du siehst die Tьr des Lastenaufzugs.}
{106}{}{Dieser Aufzug fьhrt in die unteren Ebenen des Damms. Dort gibt es fьr dich nichts zu tun.}

#Для дверей в Офисе Интерплей
{107}{}{Du siehst eine gepanzerte Tьr.}
{108}{}{Diese Tьr ist stark verstдrkt und lдsst sich nicht eintreten. Darьber hдngt ein Schild: "Spammer sind nicht erlaubt!"}

#Для дверей в убежище 8
{109}{}{Du siehst eine Aufzugtьr.}
{110}{}{Dieser Aufzug fьhrt in die unteren Ebenen des Vaults, aber du hast den Aktivierungscode nicht.}
