#Êîğîòêîå îïèñàíèå:
{100}{}{Du siehst eine Tür.}
#Îáû÷íîå îïèñàíèå:
{101}{}{Du siehst eine gewöhnliche Tür.}
#Îïèñàíèå ñ ïîäòåêñòîì, âîçíèêàåò êîãäà äâåğü çàìèíèğîâàíà:
{102}{}{Du siehst eine gewöhnliche Tür. Sie scheint geradezu zu sagen: Mach mich auf!}

#Ïîëó÷åíèå óğîíà:
{103}{}{Die Tür ist zu stabil, um sie einzureißen.}
{104}{}{Der Schlag war nicht stark genug, um die Tür einzureißen.}
{105}{}{Die Tür ist völlig zerstört.}
{106}{}{Hast du wirklich erwartet, das mit solchen Muskeln zu schaffen?}

#Îáùèå ğåïëèêè ïğè ïğèìåíåíèè òåğìèòà,
#êîòîğûå èñïîëüçóşòñÿ ó âñåõ òèïîâûõ ñåéôîâ
#(òåêñò áåğåòñÿ îòñşäà äëÿ SSRSeif, LISeif, NIEldSlf è ïğ.)
{107}{}{Du hast nichts, womit du das Thermit entzünden kannst.}
{108}{}{Es ist zwecklos.}
{109}{}{Die unglaubliche Hitze schmilzt das Schloss wie Butter.}

#Èñïîëüçîâàíèå äâåğè è íàâûêîâ
{110}{}{Die Tür ist verschlossen.}
{111}{}{Verschlossen.}
{112}{}{Vorsicht, die Tür ist mit einer Falle gesichert!}
{113}{}{Eine Falle!}
{114}{}{Löschen.}
{115}{}{Du hast es nicht geschafft, die Falle zu entschärfen. Zum Glück ist sie nicht explodiert.}
{116}{}{Du hast die Falle entschärft und eingesteckt.}
{117}{}{Erledigt.}
{118}{}{Gut gemacht, du hast die Falle ausgelöst.}
{119}{}{Pech gehabt – der Dietrich ist abgebrochen.}

#Âçëîì äâåğè
{120}{}{Du hast die Tür abgeschlossen.}
{121}{}{Du hast die Tür aufgeschlossen.}
{122}{}{ Erfahrungspunkte für das Knacken eines schwierigen Schlosses.}
{123}{}{Du konntest dieses Schloss nicht öffnen.}
{124}{}{Du erhältst }
{125}{}{ Erfahrungspunkte.}
{126}{}{Das übersteigt deine Fähigkeiten.}
{127}{}{Du hast nichts, womit du das Thermit entzünden kannst.}
{128}{}{Es ist zwecklos.}
{129}{}{Die unglaubliche Hitze schmilzt das Schloss wie Butter.}

#Íàâûêè, ñèëà
{130}{}{Ein elektronischer Dietrich hilft dir hier nicht weiter, das ist ein mechanisches Schloss.}
{131}{}{Dietriche helfen dir hier nicht weiter, das ist ein elektronisches Schloss.}
{132}{}{Falsche Art von Dietrich.}
{133}{}{Die Tür gibt unter deiner Kraft nach.}
{134}{}{Hast du wirklich erwartet, das mit solchen Muskeln zu schaffen?}
{135}{}{Ugh!}
{136}{}{}
{137}{}{}
{138}{}{Du kannst diese Tür nicht einfach aufbrechen. Dafür brauchst du viel mehr Kraft.}
{139}{}{Der Laserstrahl kann die Tür nicht durchdringen.}

#Ìèíèğîâàíèå
{140}{}{Das bringt nichts.}
{141}{}{Das ist sinnlos.}
{142}{}{Das ist sinnlos – die Tür ist bereits mit einer Falle gesichert.}
{143}{}{Erledigt.}
{144}{}{Du hast die Tür mit einer Falle gesichert. Sie noch einmal anzufassen, ist vermutlich keine gute Idee.}
{145}{}{Mit einer Falle gesichert.}
{146}{}{Pech gehabt.}
{147}{}{Du konntest die Falle nicht anbringen.}
{148}{}{Wegen deiner mangelnden Erfahrung wurde die Falle vorzeitig ausgelöst.}

{150}{}{Du hast den Alarm ausgelöst!}
{151}{}{Hey! Was ist hier los!?}

{152}{}{Dieser Schlüssel passt nicht.}
{153}{}{Das stimmt nicht.}
{154}{}{Du kannst keine Falle an einer offenen Tür anbringen.}
{155}{}{Du hast Lucianos Aufgabe erledigt.}

#Èñïîëüçîâàíèå íà äâåğè İğóäèöèè (ïîëó÷åíèå ïîäñêàçîê)
{160}{}{Fazit: Dieses Schloss ist leicht zu knacken.}
{161}{}{Fazit: Dieses Schloss ist mittelschwer zu knacken.}
{162}{}{Fazit: Dieses Schloss ist schwer zu knacken.}
{163}{}{Fazit: Dieses Schloss ist äußerst schwer zu knacken.}
{164}{}{[Schlossknacken erforderlich >}
{165}{}{]}

#Îñîáûå ïîäğîáíûå îïèñàíèÿ
{200}{}{Du siehst eine robuste Lagertür.}
{201}{}{Du siehst einen Notausgang der Apotheke.}
{202}{}{Du siehst eine morsche Lagertür.}
{203}{}{Du siehst ein Tor zu den Sklavengehegen.}
{204}{}{Du siehst eine gepanzerte Tür zum Reaktor.}
{205}{}{Du siehst eine stabile Lagertür.}
{206}{}{Du siehst Hotelzimmer Nummer 26.}
{207}{}{Du siehst Hotelzimmer Nummer 14.}
{208}{}{Du siehst Hotelzimmer Nummer 7.}
{209}{}{Du siehst eine schwere, stabile, mit Metall verstärkte Tür. Sie aufzubrechen wird alles andere als leicht.}
{210}{}{Du siehst eine sehr stabile, mit Metall verstärkte Tür.}
{211}{}{Du siehst eine schwere, gepanzerte Tür zu einem Waffenlager.}
{212}{}{Du siehst eine stabile, elektronische Lagertür.}
{213}{}{Du siehst ein stabiles Garagentor.}
{214}{}{Du siehst ein äußerst stabiles Tor zu einem Bunker. Das Schloss sieht aus, als wäre es erst kürzlich ausgetauscht worden.}
{215}{}{Hmm. Darunter muss sich eine Art Bunker befinden. Das Schloss ist nagelneu.}
{216}{}{Du siehst eine gewöhnliche Vault-Tür.}
{217}{}{Du siehst Hotelzimmer Nummer 15.}
{218}{}{Du siehst eine robuste Luke mit einem stabilen Schloss. Sie braucht wahrscheinlich einen Spezialschlüssel.}
{219}{}{Das ist ein *äußerst* stabiles Schloss. Irgendwo in der Nähe gibt es wahrscheinlich einen Schlüssel dafür.}
{220}{}{Du siehst eine stabile Hintertür.}
{221}{}{Du siehst ein stabiles Hangartor.}
{222}{}{Du siehst eine gewöhnliche Tür. Die Nummer 9 ist auf der Oberfläche kaum zu erkennen.}
{223}{}{Du siehst stabile Tore mit elektronischen Schlössern.}