#Descriptions:
{100}{}{Du siehst einen Safe.}
{101}{}{Das ist dein persönlicher Safe mit Zahlenschloss.}
{102}{}{Du siehst einen verstärkten Safe, in dem du Gegenstände aufbewahren kannst.}
{103}{}{Du siehst deinen persönlichen Safe.}

#Usage:
{104}{}{Der Safe hat ein mechanisches Zahlenschloss. Er ist verschlossen. Solange du nichts hören kannst, wirst du ihn nicht öffnen können.}
{105}{}{Nicht im Kampf!}
{106}{}{Du hast nicht einmal einen Kratzer hinterlassen.}

#Cracking
{107}{}{Der Safe hat ein mechanisches Schloss mit 5 Walzen, die jeweils auf eine eigene Zahl eingestellt werden. Du kannst versuchen, den Code zu erraten, aber das wird eine Weile dauern.}
{108}{}{[Code knacken.]}
{109}{}{[Nicht jetzt.]}

{110}{}{[Erste Ziffer des Codes wählen.]}
{111}{}{[Zweite Ziffer des Codes wählen.]}
{112}{}{[Dritte Ziffer des Codes wählen.]}
{113}{}{[Vierte Ziffer des Codes wählen.]}
{114}{}{[Letzte, fünfte Ziffer des Codes wählen.]}
{115}{}{0}
{116}{}{1}
{117}{}{2}
{118}{}{3}
{119}{}{4}
{120}{}{5}
{121}{}{[Schloss in Ruhe lassen.]}

#Results
{122}{}{Als du die Ziffer einstellst, hörst du ein leises Klicken.}
{123}{}{Als du die Ziffer einstellst, hörst du ein gewöhnliches Klicken.}
{124}{}{Als du die Ziffer einstellst, hörst du ein deutliches Klicken.}

{125}{}{[Weiter zur nächsten Zahl.]}
{126}{}{[Versuchen, den Safe zu öffnen.]}
{127}{}{[Aufgeben.]}

{128}{}{Du hast den Code geknackt! Du drehst am Griff und die Tür schwingt auf.}
{129}{}{Für das Knacken der Safe-Kombination erhältst du 500 Erfahrungspunkte und einen persönlichen Safe, in dem du deine Ausrüstung lagern kannst.}
{130}{}{Erledigt.}

{131}{}{Du drehst am Griff und }
{132}{}{ Zuhaltungen drehen sich, bevor sie wieder einrasten. Der Safe ist immer noch verschlossen. Es sieht aus, als hättest du }
{133}{}{ Ziffern von fünf richtig.}
{134}{}{[Erneut versuchen.]}
{135}{}{Nicht einmal annähernd. Keine deiner Ziffern war richtig.}
{136}{}{Du drehst am Griff und hörst, wie sich eine Zuhaltung bewegt, bevor sie wieder einrastet. Der Safe ist immer noch verschlossen. Es sieht aus, als hättest du 1 Ziffer von fünf richtig.}
{137}{}{Für das so schnelle Knacken der Safe-Kombination erhältst du außerdem 700 Erfahrungspunkte und einen persönlichen Safe, in dem du deine Ausrüstung lagern kannst.}

#When receiving the "Infiltrator" perk
{138}{}{[Die Zahlen sorgfältig auf Abnutzungsspuren untersuchen.]}
{139}{}{Bei der Untersuchung des Safeschlosses siehst du, dass die Ziffern }
{140}{}{ und }
{141}{}{ Anzeichen wiederholter Abnutzung aufweisen. Sie kommen wahrscheinlich in der Kombination des Safes vor.}