# 100-199 are for grave site messages
{100}{}{Du siehst ein Grab.}
{101}{}{Du siehst ein freigelegtes Grab.}
{102}{}{Dies ist eine Grabstätte.}
{103}{}{Diese Grabstätte wurde freigelegt.}
{150}{}{Die Grabstätte wurde zugeschüttet.}
{151}{}{Die Grabstätte wurde freigelegt.}

# 200 on are all for headstones
{200}{}{Du siehst einen Grabstein.}
{201}{}{Du siehst einen Grabmarker.}

# 250 + long descriptions
# generic no name sites
{250}{}{Auf diesem Grabstein sind keine Markierungen.}
{251}{}{Der Name auf dem Grabstein wurde herausgekratzt.}
{252}{}{Auf dem Grabstein steht der Name "John Doe".}
{253}{}{Name und Datum auf diesem Grabstein sind durch die Witterung unleserlich geworden.}
# for crosses
{260}{}{Auf diesem Grabstein sind keine Markierungen.}
{261}{}{Der Name auf dem Grabstein wurde weggekratzt.}
{262}{}{Auf dem Grabstein steht „John Doe“.}
{263}{}{Name und Datum auf diesem Grabstein sind durch die Witterung unleserlich geworden.}

# leader
{275}{}{Auf dem Grabstein steht: }
{276}{}{Auf dem Grabstein steht: }

# specific cases
{300}{}{„Hier ruht Chris Avellone, König der Tanzfläche.“}
{301}{}{„Chris Jones. Der Nightwing.“}
{302}{}{„Christopher Michael Holland, auch bekannt als ‚Chris Holland‘, auch bekannt als ‚Chris‘: Es gibt zweieinhalb Gründe, diesen Grabstein zu lesen ... Normalerweise würde man erwarten, dass diese Gründe aufgezählt werden.“}
{303}{}{„Colin McComb: Ein weiteres sinnloses Leben“}
{304}{}{„David Hendee: der Lauteste unter den Toten. Möge er in Frieden ruhen. Und zwar leise.“}
{305}{}{„Ed Hyland. Er sagte der Welt: ‚Leck mich.‘“}
{306}{}{„Eric Demilt. Der WAHRE Combat Boy.“}
{307}{}{„Feargus Urquhart: Hat verdammt noch mal eine Liste zu viel gemacht.“}
{308}{}{„Fred Hatch. Starb bei dem Versuch, Myrons Stimme aufzunehmen.“}
{309}{}{„Gary Platner. Getötet, weil er nicht mehr Vault-Bürger-Modelle gemacht hat.“}
{310}{}{„Jason Anderson: kein lebender Gott mehr.“}
{311}{}{„Jason G. Suinn.“}
{312}{}{„Jason Taylor.“}
{313}{}{„Jeremy Barnes. Der kahlköpfige Affe von Black Isle.“}
{314}{}{„Jesse Reynolds. Mochte Ingwerplätzchen. Zu sehr.“}
{315}{}{„John Deiley.“}
{316}{}{„John Price.“}
{317}{}{„Leonard Boyarski. Aus Vault City verbannt.“}
{318}{}{„Rupert Dinkos, gestorben im Winter ’00.“}
{319}{}{„Matt Norton. Er hätte jemand werden können. Ein Kämpfer, statt ein Penner zu sein, was er nun mal war.“}
{320}{}{„Nick Kesting.“ [Obenauf steht ein kleiner Eimer mit runden Kupfergeschossen]}
{321}{}{„Robert Collier. Leise. Tödlich. Rob.“}
{322}{}{„Robert Hertenstein 2. Sein Arzt versuchte es ihm zu sagen, aber er bestand darauf: ‚Das sind mir ein bisschen zu viele Informationen.‘“}
{323}{}{„Scott Campbell. Nicht die Suppe.“}
{324}{}{„Hier liegt Scott Everts. Zu spät zur Arbeit. Zu spät fürs Leben.“}
{325}{}{„Scott Rodenhizer. Erschuf 3D-Köpfe.“}
{326}{}{„Thomas French: Starb beim Versuch, die Fliegende Guillotine zu meistern.“}
{327}{}{„Tim Cain. Gründer, Liebhaber, Kämpfer, Programmierer.“}
{328}{}{„Tramell Ray Isaac: Hier liegt einer der fleißigsten Männer der Branche. Animator par excellence (Einzelkern). Glaube ich. Ruhe in Frieden, T-Ray“}
{329}{}{„Zeb – Immer noch älter als der Dreck“}
{330}{}{„Dennis Presnell. Wir können ihn jetzt beinahe hören: ‚Das nennt ihr eine Beerdigung?! Das war mies! Ihr seid !@#löcher! Ich sterbe nie wieder! Bla-bla-bla ...‘“ Darunter eingeritzt steht: „Gott hab ‚Cryin‘ D selig, hätte den Flicken behalten sollen.“}
{331}{}{„Rupert Diukos, gestorben am 24.9.96“}
{332}{}{„Sal De Ban, gestorben am 24.9.96“}
{333}{}{„Greg Zeschule, Herbst ’99“}
{334}{}{„Ray Muzyka, Sommer ’98“}
{335}{}{„Evan Chantland, 74–??: Er war nicht paranoid, sie waren wirklich hinter ihm her.“}
{336}{}{„Hier liegt Moose, kalt und tot. Wir fanden ihn hier, ohne seinen Kopf.“}
{337}{}{„Amy Presnell“}
{338}{}{„Stephen Bokkes, 25 Jahre alt. In seiner Blüte vom Schleudern und Pfeilen des widrigen Schicksals dahingerafft.“}
{339}{}{„R.I.P. Doug „Skully“ Finch (Das Datum spielt keine Rolle) Getötet, weil er im French Market rauchte. Letzte Worte: `Donkey Punches to ya!'“}
{340}{}{„Hier liegt Donnie Cornwell, schön tot. In einem extragroßen Sarg, passend zu seinem extragroßen Kopf.“}
{341}{}{„Rob Giampa lebte sein Leben wie seine Frauen: schnell, billig und unkompliziert.“}
{342}{}{„T. D. Hamilton: Hier liegt eine stinkende Schlampe, die schon vor langer Zeit hätte tot sein sollen. Fahr zur Hölle, SCHLAMPE!“}
{343}{}{„Ein weiteres Opfer der Deadline.“}
{344}{}{„Dogbomb ist tot. Lang lebe der Hund.“}
{345}{}{„Kris Snider: Zu ehrgeizig“}
{346}{}{„Machst du irgendetwas Sinnvolles mit deinem Leben?“}
{347}{}{„Warum bringst du dich nicht einfach um und ersparst jemand anderem die Mühe?“}
{348}{}{Charles Cuevas: Er sagte einmal: „Gebt mir Hockey oder gebt mir den Tod.“ Hockey bekam er nicht ganz.}
{349}{}{William Lebus}
{350}{}{Reg Arnedo: Wir können seine Stimme noch immer durch die Flure hallen hören.}
{351}{}{Shanna SanPaolo}
{352}{}{Brahmin Wrangler}
{353}{}{Josh Walters, 1971–2011. Starb an Komplikationen bei seiner fünften Lebertransplantation.}
{354}{}{Doug Avery. Hasste den Krieg, weil er sein Leben im Wohnwagenpark zerstörte.}
# joke ones
{355}{}{Hier liegt Ezekial Aikle, 102 Jahre alt. Die Guten sterben jung.}
{356}{}{Hier liegt Ann Mann, die als alte Jungfer lebte und als alter Mann starb. 8. Dez. 1767}
{357}{}{Die Kinder Israels wollten Brot, und der Herr schickte ihnen Manna. Der alte Schreiber Wallace wollte eine Frau, und der Teufel schickte ihm Anna.}
{358}{}{Hier liegt Johnny Yeast. Verzeiht, dass ich nicht aufstehe.}
{359}{}{Hier liegt der Leib von Jonathan Blake. Er trat aufs Gas statt auf die Bremse.}
{360}{}{Hier liegt Butch, wir haben ihn roh begraben. Am Abzug war er schnell, beim Ziehen jedoch langsam.}
{361}{}{Zum ehrenden Gedenken an meinen Mann John Barnes, gestorben am 3. Januar 1803. Seine hübsche junge Witwe, 23 Jahre alt, verfügt über viele Eigenschaften einer guten Ehefrau und sehnt sich nach Trost.}
{362}{}{Sir John Strange, hier liegt ein ehrlicher Anwalt, und das ist seltsam.}
{363}{}{Ich war jemand. Wer, geht dich nichts an.}
{364}{}{Hier liegt Lester Moore, vier Kugeln aus einer .44er, nicht mehr und nicht weniger.}
{365}{}{Ich hab euch doch gesagt, mir ist schlecht!}
{366}{}{Leser, brauchst du Geld, dann grabe vier Fuß tief, und du wirst einen Penny finden.}
{367}{}{Sie sagte immer, ihre Füße brächten sie noch um, doch niemand glaubte ihr.}
{368}{}{Am 22. Juni – Jonathan Fiddle – fiel aus der Tonart.}
{369}{}{Hier liegt der Leib unsrer Anna, die eine Banane ins Grab brachte. Nicht die Frucht hat sie dahingerafft, sondern ihre Schale, die ihr den Tod gebracht.}
{370}{}{„Ging dahin: Owen Moore – mehr, als er sich leisten konnte.“}
{371}{}{„Zum Gedenken an den kleinen Chris Wood. Hier liegt ein Wood, von Holz umschlossen, ein Wood in einem anderen. Das äußere Holz ist sehr gut, doch das andere können wir nicht loben.“}
{372}{}{„Unter dem Rasen und unter den Bäumen liegt Jonathan Pease. Er ist nicht hier, hier ist nur die Hülse: Pease hat sich ausgeschält und ist zu Gott gegangen.“}
{373}{}{„Der am 21. März 1870 durch die Explosion einer Lampe, gefuellt mit „R. E. Danforths nichtexplosiver Brennflüssigkeit“, tödlich verbrannt wurde“}
{374}{}{„Geboren 1903 – gestorben 1942. Schaute in den Aufzugsschacht, um zu sehen, ob der Fahrstuhl herunterkam. Tat er.“}
{375}{}{„Hier liegt ein Atheist, fein herausgeputzt und ohne Ziel.“}
{376}{}{„Eileen Suh: Besuchte die juristische Fakultät von William & Mary. Jetzt ist sie Eileen Sue.“}
{377}{}{„Sarah Smart: Rednerin, Autorin, Professorin, De Amicitia.“}
{378}{}{„Tim Winkle – Heuchelei dulde ich nicht, außer meiner eigenen.“}
{379}{}{„Jughead – König von Königin Archies Welt.“}
# new additions
{380}{}{„Ruhe in Frieden, Casey Donahue. Gestorben am 6.8.98. Getötet von einem mutierten, übelgelaunten Wolfsbarsch.“}
{381}{}{„Christopher ‚Nightwing‘ Jones: Verwalter des Pilzblauen Flecks.“}
{382}{}{„Jay ‚Kartoffelfüße‘ Nielson. Musiker. Verstarb im Alter von 104 Jahren während eines Schlagzeugsolos.“}
{383}{}{„Nitsa – Der Grund, warum Charles Hockey nie ganz verstanden hat.“}
{384}{}{„Thuy Dang. Möge Gott sich seines Namens erbarmen.“}

# trapping the grave
{500}{}{Du stellst geschickt eine Falle im Grab auf.}
{501}{}{Du schaffst es nicht, die Falle im Grab richtig aufzustellen.}

{510}{}{ stellt geschickt eine Falle im Grab auf.}
{511}{}{ schafft es nicht, die Falle im Grab richtig aufzustellen.}

# Find Trap on grave
{515}{}{Du entdeckst eine Falle am Grab.}
{516}{}{Du entdeckst keine Fallen am Grab.}
{517}{}{Glückwunsch – die rostige alte Schaufel konnte deiner Kraft einfach nicht standhalten.}
{518}{}{Verdammt!...}

{520}{}{ entdeckt eine Falle am Grab.}
{521}{}{ entdeckt keine Fallen am Grab.}

# Disarm the Trap on grave
{525}{}{Du entschärfst die Falle geschickt.}
{526}{}{Du schaffst es nicht, die Falle zu entschärfen.}

{530}{}{ entschärft die Falle geschickt.}
{531}{}{ entschärfst die Falle nicht.}
