{100}{}{Du hast hier bereits alles geplündert, was auch nur halbwegs nützlich ist.}
{101}{}{Du kannst kaum eine Metallsorte von einer anderen unterscheiden, geschweige denn ihren Zweck erkennen.}
{102}{}{Du holst etwas brauchbaren Schrott aus dem Haufen. Er könnte sich für Reparaturen als nützlich erweisen.}
{103}{}{Dieser Haufen ist voller Metallschrott, der für allerlei Reparaturen nützlich sein könnte.}