#Для спуска в канализацию с бассейном в Солте:
{100}{}{Du solltest besser nicht in dieses schlammige Wasser steigen.}
{101}{}{In diese Jauchegrube tauchen?! Niemals!}

#Для ящиков на складах в Хоторне:
{102}{}{Du springst beherzt mithilfe der Kisten ьber den Zaun.}
{103}{}{Du kletterst mithilfe dieses groЯen Kistenstapels aufs Dach.}

#Для дамбы:
{104}{}{Von hier oben siehst du die riesige Station und entscheidest, dass es fьr dich keinen Grund gibt, hinunterzugehen.}
{105}{}{Ich habe dort nichts zu suchen.}

#Для спуска с артезианской башни:
{106}{}{Vor Erschцpfung konntest du dich nicht mehr auf den Beinen halten und stьrztest hin, wobei du dir beide Beine brachst.}
{107}{}{Unaufmerksam stolperst du und rollst die Treppe hinunter, wobei du dir beide Beine brichst.}
{108}{}{Ungeschickt rutschst du aus und rollst wie ein Ball hinunter, wobei du dir beide Beine brichst.}

#Для Ветра Войны:
{109}{}{Du kletterst auf das Dach des Gebдudes und springst dann zu Boden.}
