# lockpick
# dude
{100}{}{Du knackst das Schloss erfolgreich.}
{101}{}{Du knackst das Schloss nicht.}
{102}{}{Du verriegelst das Objekt erfolgreich.}
{103}{}{Du kannst das Objekt nicht verriegeln.}
# other critter
{200}{}{ knackt das Schloss erfolgreich.}
{201}{}{ kann das Schloss nicht knacken.}
{202}{}{ verriegelt das Objekt erfolgreich.}
{203}{}{ kann das Objekt nicht verriegeln.}

# explosion
{300}{}{Die Explosion zerstört das Schloss des Objekts.}
{301}{}{Die Explosion schafft es nicht, das Schloss des Gegenstands zu entfernen.}

# pry
# dude
{400}{}{Du hebelst das Schloss des Gegenstands erfolgreich auf.}
{401}{}{Du schaffst es nicht, das Schloss des Gegenstands aufzubrechen.}
# other critter
{500}{}{ hat das Schloss des Gegenstands erfolgreich aufgehebelt.}
{501}{}{ schafft es nicht, das Schloss des Gegenstands aufzubrechen.}