{100}{}{Die Chryslus Motors-Artikel waren sehr hilfreich. Du hast die Belastung des Wagens verringert und die Geschwindigkeit sowie die maximale Ladekapazität des Kofferraums leicht erhöht.}
{101}{}{10 Prozent sind eine Menge!}
{102}{}{Jetzt ist dieses Magazin nutzlos.}
{103}{}{Mit diesem Magazin könntest du deinen Pickup ordentlich verbessern, aber dafür brauchst du einen professionellen Werkzeugkasten, den du nicht hast.}
{104}{}{Ich brauche einen Werkzeugkasten.}
{105}{}{Mit diesem Magazin könntest du deinen Pickup ordentlich verbessern, aber du brauchst einen professionellen Werkzeugkasten und ... das Auto selbst.}
{106}{}{Deine Reparaturfähigkeit reicht nicht aus.}
{107}{}{Irgendetwas ist unklar ...}