{100}{}{Das kannst du nicht im Kampf benutzen!}
{101}{}{Dein Reparaturtalent ist zu gering, um diese komplexe Technologie zu verstehen.}
{102}{}{Der Metalldetektor schlägt nicht an.}

{103}{}{Der Metalldetektor piept, aber du kannst die Quelle nicht ausmachen.}
{104}{}{Der Metalldetektor piept wie verrückt! Aber du findest nichts in deiner Nähe.}
{105}{}{Für das Finden des Verstecks erhältst du }
{106}{}{ Erfahrungspunkte.}
{107}{}{Der Metalldetektor ortet etwas in etwa }
{108}{}{ Schritte von dir entfernt.}
{109}{}{}

{110}{}{Na, was haben wir denn hier?!}
{111}{}{Aha! Erwischt!}
{112}{}{Komm schon, Schätzchen, gib mir was Gutes!}
{113}{}{Wo sind meine Millionen, Miss Fortune?}
{114}{}{Ha! Jetzt gehört alles mir!}
{115}{}{Was dir gehörte, gehört jetzt mir ...}
{116}{}{Ha, der Goldrausch ist zurück!}
{117}{}{Hoffentlich ist es klein genug, um es mitzunehmen ...}
{118}{}{Nicht gerade ein G.E.C.K., aber trotzdem ziemlich gut ...}
{119}{}{Wer's findet, darf's behalten!}
{120}{}{Wenn ich doch nur einen größeren Rucksack hätte ...}
{121}{}{Feindkontakt!}
{122}{}{Ich brauche mehr ... MEHR!}
{123}{}{Was ist es diesmal?}
{124}{}{Mal sehen, worum es hier geht ...}
{125}{}{}
{126}{}{}
{127}{}{}
{128}{}{"Jemand will ins Weltall, doch ich will nur ein reicheres Gesicht ..." }
{129}{}{"Du bewahrst viele Geheimnisse, Erde ... Dich auszugraben tut nicht weh!"}

{130}{}{Du hast mit dem Metalldetektor eine Falle gefunden.}
{131}{}{Der Metalldetektor piept, aber du kannst keine Fallen finden.}
{132}{}{Ja!}
{133}{}{Der Metalldetektor piept wie verrückt, aber du kannst nichts finden.}

#Ñîîáùåíèÿ ïğè ïîèñêå ëàçà â ñåìåéíîå óáåæèùå íà Ïëîùàäè âîçğîæäåíèÿ
{200}{}{Du hast das Gefühl, hier alles gefunden zu haben, was es zu finden gibt.}
{201}{}{Unter einer dicken Sandschicht, vom Zahn der Zeit bedeckt, findest du den Eingang zu einem Schutzbunker.}
{202}{}{Der Metalldetektor piept wie verrückt, aber du siehst nichts. Nur ein sehr erfahrener Plünderer könnte hier etwas Brauchbares finden.}
{203}{}{Ich sehe nichts Besonderes ... Was könnte das sein?}
{204}{}{Ohne diesen Metalldetektor hätte ich diese Luke nie gefunden!}

#Ñîîáùåíèÿ ïğè ïîèñêå ñïóñêà â êàíàëèçàöèş Ğèíî
{210}{}{Du fegst Sand, Kies und Geröll beiseite und findest einen Eingang zu den Abwasserkanälen.}
{211}{}{Igitt! Dieser Gestank kann nur ... ein Abwasserkanal sein!}
{212}{}{Der Metalldetektor piept wie verrückt, aber du siehst nichts Besonderes.}
