{100}{}{Diese Arbeit hast du bereits studiert. Lass jetzt das Leben dein Lehrer sein.}

{101}{}{Der Autor muss verrückt gewesen sein.}
{102}{}{Wissenschaftliche Literatur? Nichts für dich!}
{103}{}{Diese Monografie richtet sich an qualifizierte Mediziner. Du kannst nichts davon verstehen.}
{104}{}{Diese Monografie ist in abstrakter wissenschaftlicher Sprache verfasst. Mit deinem Wissensstand irgendetwas davon verstehen zu wollen, wäre etwas zu optimistisch.}
{105}{}{Dir fehlt das nötige wissenschaftliche Wissen, um diese Monografie zu verstehen.}

{106}{}{Wow, das war ganz schön viel Denkarbeit!}
{107}{}{Du lernst viel über die medizinische Praxis, aber die Monografie gibt keine Berufsgeheimnisse preis.}
{108}{}{Du lernst nichts Neues.}
{109}{}{Zu deiner eigenen Überraschung entdeckst du einige Geheimnisse der menschlichen und tierischen Anatomie. Das könnte dir sowohl bei der Behandlung als auch im Kampf helfen.}
{110}{}{Zu deiner eigenen Überraschung entdeckst du einige Geheimnisse der menschlichen und tierischen Anatomie.}
