{100}{}{Du siehst einen Automaten für Nuka-Cola. Du fragst dich, ob er noch funktioniert.}

{101}{}{[Klonk, klonk, klingeling ... Pfffft]}
{102}{}{Du bekommst eine nicht mehr ganz frische Flasche Nuka-Cola.}
{103}{}{Verdammt!}
{104}{}{Du legst den Automaten herein.}
{105}{}{ legt den Automaten geschickt herein.}
{106}{}{Der Automat scheint ausverkauft zu sein.}

{107}{}{Hihi! Diebe bleiben eben Diebe!}
{108}{}{Deine Münze ist für immer in den Tiefen dieses Automaten verloren!}
{109}{}{Du erhältst einen neuen Erfolg und deine Diebesfähigkeit steigt um 5%.}

{110}{}{Dieser Automat hat noch mehrere Flaschen Limonade. Um ihn auszulösen, musst du eine Münze in den Schlitz stecken.}
{111}{}{Dieser Automat ist ausverkauft.}
{112}{}{Hey! Komm zurück!}

{113}{}{Du siehst einen Nuka-Cola-Automaten. Preis: $}
{114}{}{.}
{115}{}{Dieses Gerät erfordert eine Identitätsprüfung.}
{116}{}{Das bewirkt nichts.}
{117}{}{Nicht genug Geld.}
