{100}{}{Das kannst du im Kampf nicht benutzen.}
{101}{}{Das Radio kann nur in deinen Händen benutzt werden.}

#Common
{110}{}{Du hörst nichts außer Rauschen.}
{111}{}{Schalte das Radio aus.}

#Cheating
{112}{}{Wähle deinen Teleportationspunkt. ( 133 Gerlach; 22 Black Rock; 18 Lovelock; 31 NPP; 54 Reno; 92 Uranium City; 51 Hawthorne; 6 Wind of War; 27 Area 51; 46 Vegas; 137 Salt; 12 Provo; 25 Bikers; 130 Gov. Vault. )}
{113}{}{Der Nächste.}
{114}{}{Zurück}
{115}{}{Folge der Nummer auf der Karte }
{116}{}{Weiter 10}
{117}{}{Zurück 10}

#Slavers in Vegas
{120}{}{Durch die Betonwände des Kellers empfängst du kein Signal.}
{121}{}{Schalte das Radio aus.}
{122}{}{[Du hörst gewöhnliches Geplapper der Sklavenhändler, aber nichts Interessantes.]}
{123}{}{Pass auf, ein Sklave ist geflohen! Er hat eine Waffe!}
{124}{}{[Schalte das Radio aus.]}
{125}{}{[Die Sklavenhändler können sehen, dass du das Radio benutzt. Du musst das Gebäude verlassen oder einen ruhigen Ort dafür finden.]}
{126}{}{[Schalte das Radio aus.]}

#Lovelock, Cheyennes village
{130}{}{Du hörst das schwache Signal des örtlichen Radiosenders.}
{131}{}{Schalte das Radio aus.}
{132}{}{Plötzlich empfängst du ein seltsames Signal auf einer ungewöhnlichen Frequenz. Es ist sehr schwach, wird aber stärker, je näher du seiner Quelle kommst.}
{133}{}{Versuche, die Quelle der Übertragung zu finden.}
{134}{}{Das Signal ist hier laut und deutlich, scheint aber codiert zu sein.}

#Wind of War
{140}{}{Du hörst gewöhnliches Geplapper der Patrouille, aber nichts Interessantes.}
{141}{}{Durch die dicken Vault-Wände empfängst du kein Signal.}
{142}{}{Der Berg blockiert das Signal.}

#Salt Lake, little vaults area
{150}{}{Du empfängst ein schwaches Signal. Wenn du nach }

{151}{}{Südwesten}
{152}{}{Westen}
{153}{}{Nordwesten}
{154}{}{Nordosten}
{155}{}{Osten}
{156}{}{Südosten}

{157}{}{… wird es stärker. Als du dich der Quelle näherst, merkst du, dass es ein Notsignal ist.}
{158}{}{Das könnte interessant werden.}
{159}{}{Du hörst ein klares Signal. Es klingt wie Morsecode. Die Quelle muss ganz in der Nähe sein, aber du kannst keine Sender sehen.}
{160}{}{Hmm ...}
{161}{}{Du hörst gewöhnlichen Polizeifunk, aber nichts Interessantes.}

#Black Rock
{180}{}{Durch das Rauschen empfängst du ein schwaches Signal. Es klingt nach Raidern.}
{181}{}{Folge dem Signal.}
{182}{}{Kehre zu der Stelle zurück, an der der Karawanenüberfall stattfand.}
{183}{}{Durch die dicken Höhlenwände empfängst du kein Signal.}

#Reno, Silver
{200}{}{Du kannst kaum etwas hören. Offenbar schirmen die Betonwände des Hotels das Signal ab.}
{201}{}{Aus irgendeinem Grund ist das Signal in diesen Abwasserkanälen stärker.}
{202}{}{Das Funksignal ist sehr stark. Plötzlich siehst du seine Quelle.}
{203}{}{Wie unerwartet …}

#Nevada rangers outpost
{205}{}{}
{206}{}{}
{207}{}{}
{208}{}{Du hörst nichts außer Rauschen.}
{209}{}{[Versuche, irgendein Signal zu finden]}

{210}{}{[Endlich hörst du eine Stimme durch das Rauschen] Hier spricht Ranger Tycho. Wer ist da? Ende.}
{211}{}{Hallo, Ranger Tycho. Ich bin ein Reisender. Ich bin in den Bergen auf einen verlassenen Außenposten gestoßen und habe dort dieses Funkgerät und ein paar herumliegende Codes gefunden.}
{212}{}{Ein Außenposten in den Bergen? Das könnte einer von unseren sein. Du kannst ihn gern benutzen, mach nur nichts kaputt. Ende.}
{213}{}{Na gut, ich werd's versuchen.}
{214}{}{Ich werde vorsichtig sein.}
{215}{}{Eigentlich würde ich dir nicht raten, hier herumzustreifen. Hier gibt es außer uns Rangern nichts. Wenn etwas passiert, kommt keine Hilfe. Ende.}
{216}{}{Willst du damit sagen, dass es sicherer ist, in der Nähe der Zivilisation zu bleiben?}

{217}{}{Heh, erwischt. Das Ödland ist selbst für erfahrene und vorsichtige Reisende gefährlich. Strahlung und seltsame Kreaturen fordern überall in Nevada ihren Tribut. Geh vorsichtig vor und denk daran: Wenn du genau hinsiehst, kannst du überall Anzeichen für Gefahr erkennen. Was die Zivilisation angeht … Jeder findet seine eigene Art, sich anzupassen. Wir versuchen, uns von ihr fernzuhalten. Hast du noch Fragen?}
{218}{}{Warum hast du solche Angst vor der Zivilisation?}
{219}{}{Kann ich dich persönlich treffen?}
{220}{}{Was kannst du mir über die Ranger erzählen?}
{221}{}{Danke für deine Antworten, Freund. Wenn wir uns mal begegnen, geht das Bier auf mich.}

{222}{}{Angst? Nein, wir haben keine Angst. Wir ziehen einfach die Freiheit der Wildnis vor. Wir können uns alles beschaffen, was wir brauchen, und unabhängig bleiben. Ende.}
{223}{}{Ich weiß nicht. Wir sind viel unterwegs und mögen keine Menschenmengen. Wenn wir uns mal über den Weg liefen, würden wir wahrscheinlich lieber für uns bleiben. Nichts Persönliches. Ende.}
{224}{}{Du bist wirklich so interessiert? Das schmeichelt mir. Wir sind eine kleine Gruppe, aber gut darauf vorbereitet, in der Wildnis zu leben. Unsere Vorfahren lebten hier, als die Welt zu Asche verbrannte und die Städte ihr Bestes gaben, die Überlebenden endgültig auszulöschen. „Der Krieg war ein Zeugnis menschlicher Gier und Dummheit“, wie unsere Väter uns erzählten. Jetzt leben auch wir wie sie im Einklang mit der Natur. Während ihr Stadtbewohner schon am 1. Tag sterben würdet, haben wir gute Chancen, Nahrung, Wasser und eine Unterkunft für die Nacht zu finden. Wir haben die Technik weitgehend aufgegeben und nutzen nur noch, was von den Rangern und dem Militär übrig ist. Manchmal tauschen wir bei den Händlern auf den Pfaden Munition ein. Ich persönlich verlasse mich lieber auf mich selbst als auf Maschinen, die man nicht einmal reparieren kann. Ist deine Neugier damit gestillt?}
{225}{}{Heh. Ich hätte lieber ein kräftiges Stout oder vielleicht ein Root Beer. Pass da draußen auf dich auf. Ende.}
{226}{}{[Schalte das Radio aus.]}

#Freaks hotel
{230}{}{[Du hörst zufällig ein Gespräch im Funk mit.]}
{231}{}{[Zuhören]}
{232}{}{...Wie ist die Lage? Over. [...] Keine Zwischenfälle. Die Ghoul-Aktivität ist sehr gering. Over. [...] Überwachung fortsetzen. Wir müssen sie auf frischer Tat ertappen. Over. [...] Überwachung wird fortgesetzt. Over. [...] Boss, langsam glaube ich, dass die Ghouls nichts damit zu tun hatten. Was, wenn wir nichts finden? [...] Idiot, blockier nicht die Frequenz! Das besprechen wir später. Davis' Befehle waren eindeutig – beweis ihre Schuld, koste es, was es wolle. Wenn wir keine Beweise finden, schaffen wir welche. Verstanden? [...] Ja. Ja, Sir. Kommt nicht wieder vor, S- Moment! Ich sehe jemanden beim Hotel! Er hat ein Funkgerät in der Hand – ich glaube, er hört uns ab, Sir! Ich breche die Mission ab. Ende!}
{233}{}{Heh, diese Idioten.}

#Hoover Dam
{240}{}{[Durchsuche die Frequenzen nach Funkverkehr.]}
{241}{}{Boss, hörst du mich? [...] Ja, was? [...] Ich will das alles nicht mit mir herumschleppen. Was, wenn ich es hier verstecke, in einer Straßenlaterne vor dem Büro, und es auf dem Rückweg mitnehme? [...] Na gut, aber wenn es jemand findet, wische ich dir dieses blöde Grinsen endgültig aus dem Gesicht. [...] Keine Sorge, Boss. Alles wird gut ...}
{242}{}{Zu meinem Glück redet jemand zu viel ...}
{243}{}{[Gleiche das Signal mit den Daten auf der Holodisk des Drogendealers ab.]}
{244}{}{Du hast eine geheime Frequenz gefunden.}
{245}{}{[Dem Signal folgen]}
{246}{}{}
{247}{}{}
{248}{}{}

#Cheating
{511}{}{Operation auswählen.}
{512}{}{Teleportationsziel auswählen. ( 133 Gerlach; 22 Black Rock; 18 Lovelock; 31 NPP; 54 Reno; 92 Uranium City; 51 Hawthorne; 6 The Wind; 27 Area; 46 Vegas; 137 Salt; 12 Provo; 25 Bikers; 130 Gov. Vault. )}
{513}{}{Der Nächste.}
{514}{}{Zurück}
{515}{}{Folge der Karte zu Nummer }
{516}{}{Weiter 10}
{517}{}{Zurück 10}
{518}{}{[Weitere Optionen]}
{519}{}{}

{520}{}{+50.000 $}
{521}{}{+10.000 Erfahrungspunkte.}
{522}{}{Geschlecht ändern.}
{523}{}{+50 Infektionspunkte.}
{524}{}{Infektionspunkte usw. anzeigen.}
{525}{}{Inventar einem Auto übergeben.}
{526}{}{Einen Spielmonat überspringen.}
{527}{}{[Zum Hauptmenü]}
