{100}{}{Du siehst einen Safe.}
{101}{}{Du siehst einen robusten Safe mit Zahlenschloss.}

#individual description of safes
{102}{}{Du siehst einen Präsidentensafe.}
{103}{}{Du siehst einen Wandsafe aus einer widerstandsfähigen Legierung mit einem komplexen elektronischen Schloss.}
{104}{}{Du siehst einen Safe.}
{105}{}{Du siehst einen robusten Wandsafe mit kräftigen Hebelschlössern.}

#safe usage
{200}{}{Dieser robuste Safe hat einem kräftigen Schlag problemlos standgehalten. Er wird auch allen weiteren widerstehen.}
{201}{}{Geschlossen}
{202}{}{Geöffnet}
{203}{}{Du öffnest den Safe mühelos mit dem Code, den dir der Administrator gegeben hat.}
{204}{}{Für elektronische Schlösser brauchst du eine andere Art von Dietrichen.}
{205}{}{Für mechanische Schlösser brauchst du eine andere Art von Dietrichen.}

{206}{}{Du hast den Safe bereits geknackt.}
{207}{}{Du hast es nicht geschafft, das Schloss des Safes zu knacken.}
{208}{}{Fertig}
{209}{}{Du hast das Schloss des Safes erfolgreich geknackt.}

#Science usage
{210}{}{Fazit: Dieses Schloss lässt sich leicht knacken.}
{211}{}{Fazit: Dieses Schloss lässt sich mit mittlerem Schwierigkeitsgrad knacken.}
{212}{}{Fazit: Dieses Schloss lässt sich nur schwer knacken.}
{213}{}{Fazit: Dieses Schloss lässt sich sehr schwer knacken.}
{214}{}{[Die erforderliche Fähigkeit zum Schlösserknacken ist >}
{215}{}{]}

{220}{}{Dieser Safe ist bereits geöffnet.}