# quick looks
# unknown
{100}{}{Du siehst eine seltsame Maschine. }
# normal
{101}{}{Du siehst einen Spielautomaten. }
# high roller
{102}{}{Du siehst einen glitzernden Spielautomaten. }
# jackpot
{103}{}{Du siehst einen glänzenden Spielautomaten. }

# examines
# unknown
{130}{}{Er hat drei Augen und einen Arm.}
# bet amount
{140}{}{Der Mindesteinsatz beträgt $}
{141}{}{.}
# normal
{150}{}{Du schwörst, dass du aus dem Augenwinkel sehen kannst, wie er dich ansieht. }
{151}{}{Sein glänzendes Gehäuse und der goldene Hebel funkeln verführerisch im Licht. }
# high roller
{165}{}{Er ist für Spieler mit großem Geldbeutel gedacht. }
# jackpot
{180}{}{Sein hoher möglicher Gewinn wirkt ziemlich verlockend. }

# slot machine first play message
{200}{}{[Deine Hand zittert, als du nach deinen Münzen greifst. Die Maschine flüstert dir weiter zu.] *Komm schon, Süße ... Genau so ... Na los ... Zieh mich nicht auf ... *}
{201}{}{Du siehst einen Spielautomaten. Sein glänzendes Gehäuse und der goldene Hebel funkeln verführerisch im Licht. Sein Münzschlitz lockt dich, und dein Gesicht rötet sich vor Vorfreude.}
{202}{}{[Deine Hand zittert, als du nach deinen Münzen greifst. Die Maschine flüstert dir weiter zu.] *Komm schon, Liebling ... Genau so ... Fass den Hebel an ... Pack ihn fest ... Na los ... *}

# insert coin messages
{250}{}{$ einwerfen}
{251}{}{. }
{252}{}{Letzte $ setzen}
{253}{}{.}
{254}{}{Mach Schluss für heute.}
{255}{}{Du bist pleite. Du musst den Abend für heute beenden.}
{256}{}{Mach Schluss für heute Abend.}
{257}{}{Du bist pleite. Du musst den Tag für heute beenden.}
{258}{}{Das reicht! Ich gehe!}
{259}{}{Das reicht! Ich gehe!}

# this is the message for when the machine is played
{500}{}{Die Walzen drehen sich am Automaten ... }
# this goes between every symbol, example:   "cherry... Orange... Melon... "
{599}{}{... }

# pay off types
{600}{}{Nichts. }
{601}{}{Eine Kirsche. }
{602}{}{Zwei Kirschen. }
# Three [symbol].
{603}{}{Drei }
{613}{}{. }
{604}{}{JACKPOT! }
{605}{}{DOPPELJACKPOT!!! }

# payoff amount message
{700}{}{Auszahlung: $}
{701}{}{.}
# symbol types
# singular
{1001}{}{Kirsche}
{1002}{}{Orange}
{1003}{}{Pflaume}
{1004}{}{Glocke}
{1005}{}{Balken}
{1006}{}{Melone}
{1007}{}{sieben}
# plural
{1101}{}{Kirschen}
{1102}{}{Orangen}
{1103}{}{Pflaumen}
{1104}{}{Glocken}
{1105}{}{Balken}
{1106}{}{Melonen}
{1107}{}{Siebener}

# float messages
{2000}{}{*Komm und spiel eine Runde mit mir, Cowboy.*}
{2001}{}{*Hallo, Seemann.*}
{2002}{}{*Wirf eine Flasche ein und zieh am Hebel. Ich bin nett zu dir.*}
{2003}{}{*Tick ... Tick ... Tiiiiick ... *}
{2004}{}{*Ding*}
{2005}{}{*Bing*}
{2006}{}{*Kaaa-ching*}
{2007}{}{*Zzzzzzz*}
{2008}{}{*Klingeling*}
{2009}{}{*Dingeldiding*}
{2010}{}{*Na, Schöne. Spiel eine Runde mit mir.*}
{2011}{}{*Hallo, Schöne.*}
{2012}{}{*Na, du bist aber ein hübsches Ding. Warum spielst du nicht eine Runde mit mir?*}

# 3.  NO MONEY [WTG, 9]
# no money to play
{2175}{}{[Du starrst den Spielautomaten an und merkst, dass du nicht genug Geld zum Spielen hast. Du verfluchst deine Armut. Vielleicht ein andermal ... ]}
{2176}{}{Geh weg.}
# won jackpot block
{2185}{}{[Die Leuchte "AUSSER BETRIEB" am Spielautomaten blinkt.]}
{2186}{}{Geh weg.}

# 4. RETARD [WTG]
{2100}{}{Du siehst einen seltsamen goldenen Metallkasten mit drei Augen und einem Arm. Er ist eines der schönsten Dinge, die du je gesehen hast.}
{2101}{}{Ich }
{2102}{}{wer du?}
{2103}{}{Ich vermiss MAMA. }
{2104}{}{Ich vermiss Vault City. Ich will nach Hause.}
{2105}{}{[Schüttle ihm die Hand]}
{2106}{}{Du bist ein seltsamer Mutant.}
{2107}{}{Preiset den Vault! Preiset den Vault!}
{2108}{}{Bist du ein Wasserchip?}
{2109}{}{Geh davon und such nach anderen glänzenden Dingen.}
{2110}{}{Geh weg.}

# 5.  RETARD TALKS TO SLOT MACHINE [4, 5]
{2130}{}{Die seltsame, hübsche goldene Metallbox mit drei Augen und einem Arm antwortet nicht.}
{2131}{}{ICH }
{2132}{}{! DU ANTWORTEN MIR!}
{2133}{}{[Schüttle ihm die Hand]}
{2134}{}{Ich Kind von Vault-Bewohner. Du redest JETZT mit mir.}
{2135}{}{Du bist ein seltsamer Mutant.}
{2136}{}{Bist du ein Wasserchip?}
{2137}{}{Geh davon und such nach anderen glänzenden Dingen.}
{2138}{}{[Geh.]}

# 6.  RETARD PULLS HANDLE [4, 5]
{2151}{}{Du packst seinen Arm und schüttelst ihn herzlich. Dabei ertönt ein *bzzzzzzz,* und die Box spricht! "Bitte... Geld... einwerfen."}
{2152}{}{Aighhhhh! Roboter! Roboter! Lauf weg!}
{2153}{}{[Geh.]}

# slot machine taunts loss
# male
{2200}{}{[Du hörst sie über dich lachen.]}
{2201}{}{*Hehehe, warum gibst du nicht einfach auf, Süßer?*}
{2202}{}{*Vielleicht solltest du jemand anderen meinen Hebel ziehen lassen.*}
# any
{2204}{}{[Du hörst den Spielautomaten über dich lachen.]}
{2205}{}{[Der Spielautomat kichert über dich.]}
{2206}{}{*Na los, Verlierer, gib mich nicht auf*}
# female
{2207}{}{*Ich hab bekommen, was ich wollte, Baby. Warum gibst du nicht auf?*}
{2208}{}{*Schrott!*}
{2209}{}{*Lass dir beim Rausgehen nicht von der Casinotür in den Arsch treten.*}

# slot machine taunts win
# male [3X - 1X]
{2247}{}{*Aieeeeeeee! Genau so, Süßer! Oh Gott, ja! Ja! Ja, noch mal! Schneller! Härter! Worauf wartest du?! Noch mal!*}
{2248}{}{*Genau so, Süßer... zieh weiter am Hebel... schneller, härter, schneller... na los... *}
{2249}{}{*Komm schon, Süßer... das passiert jedem mindestens einmal... versuch's noch mal... Bitte... *}
# any
{2250}{}{*Bitte gib mich noch nicht auf, Baby! Ich brauch dich jetzt mehr denn je!*}
# female [1X - 3X]
{2251}{}{*Komm schon, Liebling... versuch's noch mal... pack den Hebel... halt ihn fest... na los... *}
{2252}{}{*Genau so, Liebling... zieh weiter am Hebel... schneller, härter, schneller... na los... *}
{2253}{}{*Uhhh...! Genau so, Schatz! Wer ist dein Daddy?! Wer ist dein Daddy?!! Mach's noch mal! Zieh diesmal fester! Fester!*}

# 13. DRUNK, HIGH OR OTHERWISE FUCKED UP [WTG]
{2280}{}{[Du siehst einen Spielautomaten. Sein glänzender Rahmen und der goldene Hebel schimmern verführerisch im Licht von New Reno. Sein Münzschlitz lockt dich, und dein Gesicht wird vor Vorfreude heiß. Während du ihn anstarrst, zwinkert dich eines seiner drei Fenster an. Aus dem Münzschlitz hörst du eine rauchige Stimme.] *Na, so was! Hallöchen, Süßer. Lust, einem Mädchen eine schöne Zeit zu bereiten?*}
{2281}{}{[Du siehst einen Spielautomaten. Sein kräftiger, robuster Rahmen und der goldene Hebel glänzen wie ein Sonnengott im Licht von New Reno. Sein Münzschlitz lockt dich verführerisch, und deine Schenkel brennen vor Vorfreude. Während du ihn anstarrst, flüstert plötzlich eine tiefe Männerstimme aus dem Münzschlitz.] *So eine hübsche Frau wie dich hab ich hier noch nie gesehen, Fräulein. Willst du dein Glück versuchen?*}
{2282}{}{::Kneif dich selbst::}
{2283}{}{Äh ... Hallo?}
{2284}{}{::Atme tief durch und geh weg.::}

# 14. DRUNK CONVERSATION 1 [13]
{2300}{}{*Ich bin immer noch hier, hübsche Dame.* [Der Spielautomat senkt die Stimme.] *Ach, komm schon ... Willst du einen Einsatz wagen?*}
{2301}{}{*Ah bin immer noch hier, Süße.* [Der Spielautomat senkt die Stimme.] *Du bist ein echt heißer Feger, weißt du das? Na los ... willst du ein paar Münzen in mein kleines altes Ich stecken?*}
{2302}{}{Weeer bist duuu?}
{2303}{}{Klar, ich setz 'ne Wette auf dichhh}
{2304}{}{Ich glaube, ich sollte lieber gehen, bevor ich etwas in dich stecke, das ich bereuen könnte. [Gehen.]}
{2305}{}{::Atme tief durch und geh weg.:: [Gehen.]}

# 15. DRUNK 2 [14]
{2320}{}{*Ich bin dein Traummann.* [Der Spielautomat zwinkert dir zu.] *Gib mir ein paar Münzen, und ich werde dich auf eine Weise befriedigen, wie es noch NIE ein Mann geschafft hat.*}
{2321}{}{*Ich bin deine Traumfrau, Schätzchen. Ich will doch nur ein bisschen Aufmerksamkeit. Kannst du der armen alten Schönheit helfen? Na los, nur ein, zwei Münzen?*}
{2322}{}{Können wir nicht einfah nur reden?}

# 16. DRUNK 3 [15]
{2340}{}{*Aber natürlich können wir das, Schatz, natürlich.* [Der Spielautomat sieht mitfühlend aus.] *Was bedrückt dein hübsches Köpfchen?*}
{2341}{}{*Aber natürlich können wir das, Süßer, natürlich.* [Der Spielautomat sieht mitfühlend aus.] *Was bedrückt dich, Hübscher?*}
{2342}{}{Ich vermiss MOM und vermiss ARROYO und ich ... find das GECK nich und ... *schnief*}
{2343}{}{Ich vermiss MOM und Arroyo wurden ANGEGRIFFEN und ich ... weiß nich, wo sie sind ... Und ... *schnief*}
{2344}{}{Ich muss das große Schiff reparieren ... Und ich weiß nich WIE ... Und m-m-meine Mom ist WEG und ... *schnief*}
{2345}{}{Ich hab das Spiel durchgespielt ... Und jetzt lauf ich nur noch so rum und ... Ich mach mir Sorgen, dass alles VORBEI ist und ... *schnief*}
{2346}{}{Es is nur, dass Fhallowt 2 meine 3D-Fxxxx-Karte nich unterstützt und ich so viel *Geld* dafür ausgegeben hab und *schnief*}
{2347}{}{Ich hab versucht, einen guten Charakter zu machen, aber ich glaub, ich hab die Punkte alle *falsch* verteilt ... Und jetzt hab ich einen beschissenen Charakter ... Und ... *schnief*}
{2348}{}{Ich unterhalte mich mit einem Spielautomaten, mir geht's echt mies}

# 17. DRUNK 4 [16]
{2370}{}{*Na, na ... zerbrich dir dein hübsches Köpfchen nicht länger darüber ... Lass mich einfach alles regeln. Komm, leg deinen Kopf an mich. So ist's gut. Lass alles raus.*}
{2371}{}{*Na, na ... mach dir keinen Kopf mehr darum, Süße ... Lass mich einfach alles regeln. Komm, leg deinen hübschen Kopf an mich. So ist's gut. Lass alles raus.*}
{2372}{}{Danke, Spielautomat *schnief* du bist die Beste}
{2373}{}{Du bist die einzige *nette* Person, die ich bisher getroffen hab. Alle anderen sind so gemein und wollten mir *wehtun* und mein Geld nehmen und ... *schnief*}

# 18. DRUNK 5 [17]
{2380}{}{*Wird schon alles gut, Liebling? Ich fühl mich nicht wohl dabei, dich allein rausgehen zu lassen, wenn es dir so geht.*}
{2381}{}{[Du legst deinen müden Kopf auf den Automaten.]}
{2382}{}{*Wird schon alles gut, Süße? Ah fühl mich nicht wohl dabei, dich allein rausgehen zu lassen, wenn es dir so geht.*}
{2383}{}{Mir wird's schon gut gehen ... Danke, dass du mit mir geredet hast, Spielautomat. Ich liiiiiebe dich}

# 19. DRUNK 6 [18]
{2400}{}{*Du bist die einzige Heldin, die wir in dieser lausigen Welt voller Mistkerle und Diebe haben! Pass auf dich auf, hörst du, Liebling?* [Dreht sich weg.] *Geh lieber, bevor ich mich unmännlich benehme.*}
{2401}{}{[Auf einem der Fenster scheint sich eine Träne zu bilden.] }
{2402}{}{*Du bist der einzige Held, den wir in dieser lausigen Welt voller Mistkerle und Diebe haben! Du ... Du ... Pass auf dich auf, hörst du, Süße?* [Dreht sich weg.] *Geh lieber, bevor ich anfange zu schluchzen.*}
{2403}{}{Tschüüüüüss}

# rollin' messages
{3000}{}{Komm schon, }
{3001}{}{! Baby braucht ein neues Paar Schuhe!}
{3002}{}{! Daddy braucht ein neues Plasma-Gewehr!}

# can't play
{4000}{}{Es scheint jemand die Maschine zu blockieren.}