{100}{}{Dein mangelndes Geschick hat die Bauteile des Geräts beschädigt. Die Lichter sind ausgegangen – offenbar für immer.}
{101}{}{Du hast diese Lichtquelle erfolgreich repariert.}
{102}{}{Dein Geschick reicht nicht aus, um dieses Gerät zu reparieren.}
{104}{}{Eine Reparatur ist nicht nötig.}
{105}{}{Du erhältst }
{106}{}{ Erfahrungspunkte.}
{107}{}{Du schaffst es nicht, das zu reparieren.}
{108}{}{Diese Lichtquelle funktioniert einwandfrei.}
{109}{}{Diese Lichtquelle funktioniert unregelmäßig. Sie lässt sich aber reparieren.}
{110}{}{Diese Lichtquelle funktioniert nicht mehr.}
{111}{}{Sie lässt sich nicht reparieren.}
