{100}{}{Das sollte an einer Person angewendet werden.}
{101}{}{Du erhältst }
{102}{}{ Erfahrungspunkte für das Testen des mutagenen Serums.}
{103}{}{Das war ... geistreich.}
{104}{}{Du musst die Leiche nicht zerstückeln.}

{105}{}{Du hättest vor deinem Opfer nicht mit einer Waffe herumfuchteln sollen!}
{106}{}{Dein Opfer hat dich zu früh bemerkt.}
{107}{}{Das Glück hat dich verlassen.}
{108}{}{Das kannst du während eines Kampfes nicht tun.}
{109}{}{Was zum Teufel machst du da!?}
{110}{}{Warum bist du so erpicht darauf zu sterben!?}
