{100}{}{Ein Brunnen mit schlammigem Wasser. Aber es ist immer noch sauberer als an den meisten anderen Orten.}
{101}{}{Möchtest du noch etwas herausholen?}
{102}{}{Indem du etwas schmutziges Brunnenwasser desinfizierst und abkochst, erhältst du sauberes Wasser.}
{103}{}{Du hast heute schon Wasser geholt. Lass etwas für den Stamm übrig!}
{104}{}{Mmm! Wasser!}
{105}{}{Warte eine Weile. Das Wasser hat sich noch nicht gesetzt und ist immer noch schlammig.}
{106}{}{Das Wasser ist noch nicht fertig.}
{107}{}{Wenn ich nur wüsste, wie man Wasser reinigt!}
{108}{}{Du hast etwas Wasser mit Desinfektionsmittel gereinigt.}

{110}{}{Du hast diesen Brunnen vergiftet. Hast du das vergessen?}
{111}{}{Verdammt, das Wasser ist vergiftet ...}
{112}{}{Du hast diesen Brunnen bereits vergiftet, und es wird eine Weile keinen Sinn ergeben, es noch einmal zu tun.}
{113}{}{Das Wasser ist bereits verseucht.}
{114}{}{Du hast den Brunnen vergiftet, und jetzt ist es gefährlich, daraus zu trinken. Wie niederträchtig von dir.}
{115}{}{Der Brunnen ist vergiftet!}
{116}{}{Du kannst dieses Wasser nicht trinken, es enthält noch Gift.}
{117}{}{Nein! Vergiftet!}
{118}{}{Ein Brunnen mit trübem, vergiftetem Wasser. Das Wasser ist eine Weile ungenießbar.}
{119}{}{Du hast den Brunnen einer sehr kleinen Siedlung vergiftet. Die Folgen deiner Tat werden wahrscheinlich tödlich sein.}
{120}{}{Du erhältst Erfahrung für die gewaltlose Auslöschung einer ganzen Siedlung.}
{121}{}{Deine Überlebenskünste reichen nicht aus, um das Wasser zu reinigen.}
{122}{}{}
{123}{}{Du brauchst einen Behälter, um Wasser aufzubewahren.}
{124}{}{Ich brauche ein Gefäß.}
{125}{}{Verwende Behälter, um Wasser aufzubewahren.}
{126}{}{Dieser Brunnen ist leer. Vielleicht wird er irgendwann in Zukunft wieder gefuellt.}
{127}{}{Dieser Brunnen ist trocken.}
