{100}{}{}
{101}{}{Vielleicht kannst du etwas Nützliches daraus bergen.}
{102}{}{Es ist sehr unwahrscheinlich, dass du hier etwas Nützliches findest.}
{103}{}{Verdammt!}
{104}{}{Diese Fertigkeit ist hier nutzlos.}
{105}{}{Wieder hineinlegen? Oh nein, damit läuft das Auto auch nicht wieder.}

{110}{}{Du hast unter der Motorhaube einen intakten Kraftstoffregler gefunden.}
{111}{}{Du hast bereits alles aus dem Corvega geholt, was du konntest.}
{112}{}{Deine Fähigkeiten reichen nicht aus, um hier etwas Nützliches zu finden.}

{114}{}{Du hast etwas Restkraftstoff aus dem Tank geholt und daraus Molotowcocktails gemacht.}
{115}{}{Du hast etwas Altmetall unter der Motorhaube hervorgeholt. Das wird bei Reparaturen nützlich sein.}
{116}{}{In einer Autotür hast du etwas vergessenes Geld gefunden. }
{117}{}{Überraschenderweise hast du auf dem Rücksitz etwas .223-Munition gefunden.}

{118}{}{Das wird sich als nützlich erweisen.}
{119}{}{Ja!}
{120}{}{Jetzt gibt es *definitiv* nichts Nützliches mehr.}
{121}{}{Hmm ...}
{122}{}{Du hast eine Mikro-Fusionsbatterie mitgenommen.}
{123}{}{ Dollar.}
