#Ñòàğòîâûå è òèïîâûå îïöèè äèàëîãà
{110}{}{Das kannst du im Kampf nicht tun.}
{111}{}{An diesem Lagerfeuer kannst du Nahrung zubereiten oder Chemikalien herstellen, wenn du die Zutaten und genügend Fertigkeit hast. Wähle zuerst ein Rezept aus.}
{112}{}{An dieser Laborwerkbank kannst du nützliche Vorräte herstellen, wenn du die Zutaten und genügend Fertigkeit hast. Wähle zuerst ein Rezept aus.}
{113}{}{Geh weg.}
{114}{}{An die Arbeit.}
{115}{}{Zurück zur Liste.}
{116}{}{Ende.}
{117}{}{Ich kenne noch keine Rezepte.}

{118}{}{> Nächste Liste.}
{119}{}{< Vorherige Liste.}

#Èçãîòîâëåíèå
{120}{}{Herstellen: }
{121}{}{.}
{122}{}{Du brauchst: }
{123}{}{Erledigt.}
{124}{}{Ende.}
{125}{}{Die Zubereitung ist abgeschlossen.}
{126}{}{Du erhältst }
{127}{}{ Erfahrungspunkte für die Herstellung von Vorräten am Lagerfeuer.}
{128}{}{ Erfahrungspunkte für die Herstellung von Vorräten mithilfe der Laborausrüstung.}

#Ğåöåïòóğà
{135}{}{Um dieses Rezept zu lernen, brauchst du Wissenschaft }
{136}{}{ Infektionspunkte.}
{137}{}{Du hast dieses Rezept erfolgreich gelernt.}

#Îïöèè öåíòğèôóãè
{140}{}{Du brauchst einen Wissenschaftswert von 25, um das zu benutzen.}
{141}{}{Die medizinische Zentrifuge ist einsatzbereit. Was möchtest du herstellen?}
{142}{}{Du musst dieses Gerät ausrüsten, um es benutzen zu können.}

{148}{}{Diese Werkbank gehört ihrem Besitzer. Du brauchst eine Erlaubnis, um sie zu benutzen.}
{149}{}{Sammle alle benötigten Gemüsesorten in deinem Rucksack.}

##############################################################################
#
#                          Äëÿ Áëıê-Ğîê - êàğòà îñàäû
#
##############################################################################

{150}{}{Der Eintopf für die Raider köchelt noch auf diesem Feuer. Du hast die Gelegenheit, "mit den Gewürzen herumzuspielen".}
{151}{}{Benutze das Gift „Pferdetöter“.}
{152}{}{Benutze Radskorpiongift.}
{153}{}{Fertig. Jetzt musst du nur noch ein wenig warten...}
{154}{}{Ende.}
{155}{}{Die Raider sollten das vergiftete Essen inzwischen gegessen haben.}
{156}{}{Vergifte das Essen der Raider.}
{157}{}{Du brauchst etwas Giftiges.}
{158}{}{Radskorpionengift wird normalerweise injiziert, nicht geschluckt. Du brauchst etwa drei Schwänze, um die Arbeit zu erledigen.}
{159}{}{Verwende drei Schwänze mit Radskorpionengift.}

##############################################################################
#
#                          Ëå÷åíèå ÎÇ
#
##############################################################################

{160}{}{Heilen.}
{161}{}{Du bist bereits gesund.}
{162}{}{Iss etwas, um }
{163}{}{ Trefferpunkte zu heilen.}
{164}{}{}
{165}{}{}
{166}{}{}
{167}{}{}
{168}{}{}
{169}{}{}

##############################################################################
#
#                          Ëå÷åíèå îò èíôåêöèè
#
##############################################################################

{170}{}{Behandle deine Infektion.}
{171}{}{Wähle deine Behandlung. Ihre Wirksamkeit hängt von deinem Arzt-Skill ab.}
{172}{}{Blutreiniger.}
{173}{}{Xanderwurzelpulver.}
{174}{}{Xanderwurzelpulver und Desinfektionsmittel.}
{175}{}{Xanderwurzelpulver, Desinfektionsmittel und sauberes Wasser.}
{176}{}{Nachtschattenbeeren und Schnaps.}
{177}{}{Nachtschattenbeeren und ein „Bloody Mary“.}
{178}{}{Nachtschattenbeeren und ein „Atomic Cocktail“.}
{179}{}{Zurück.}

{180}{}{Dir fehlen die nötigen Zutaten.}
{181}{}{Du hast }
{182}{}{ Infektionspunkte geheilt.}

##############################################################################
#
#                          Ñïèñîê ğåöåïòóğ
#
##############################################################################

{190}{}{Studiere das Rezept für „Root Beer“.}
{191}{}{Studiere das Rezept für „Atomic Cocktail“.}
{192}{}{Studiere das Rezept für „Nuka-Cola Turbo“.}
{193}{}{Studiere das Rezept für stimpak.}
{194}{}{Studiere die Herstellungsanleitung für den „Arztkoffer“.}
{195}{}{Studiere die Herstellungsanleitung für den „Molotowcocktail“.}
{196}{}{Studiere das Rezept für das „Karawanenessen“.}
{197}{}{Studiere das Rezept für den „Gottesanbeter-Snack“.}
{198}{}{Studiere das Rezept zur Herstellung von }
{199}{}{Studiere das Rezept zur Herstellung von }

##############################################################################
#
#                          Ñïèñîê èçãîòîâëåíèÿ
#
##############################################################################

{200}{}{Gegengift.}
{201}{}{Radskorpionenschwanz (1)}

{202}{}{Heilpulver.}
{203}{}{Xanderwurzel (1), Broc-Blüte (1)}

{204}{}{Blutreiniger.}
{205}{}{Nachtschattenbeeren (2), Xanderwurzel (1), Broc-Blüte (1), sauberes Wasser (1)}

{206}{}{Pferdetöter-Gift.}
{207}{}{Nachtschattenbeeren (2), Radskorpionenschwanz (2), leere Spritze (1)}

{208}{}{Root Beer.}
{209}{}{Xanderwurzel (2), Mutafrucht (1), sauberes Wasser (1)}

{210}{}{Vocasnusslösung.}
{211}{}{Vocasnüsse (10), "Bloody Mary" (1), leere Spritze (1)}

{212}{}{Atomic Cocktail (5).}
{213}{}{Nuka-Cola (5), Alkohol (5), Mentats (1)}

{214}{}{Turbo-Cola (3).}
{215}{}{Nuka-Cola (3), Mittel gegen das Rauchen (1)}

{216}{}{Vergifteter Alkohol für El Dorado-Gäste (5).}
{217}{}{Bier (5), Radskorpionenschwanz (1)}

{218}{}{Stim-Paks für Strikers Chemikalien (10).}
{219}{}{Strikers Chemikalien (1), leere Spritze (10)}

{220}{}{Stimpak.}
{221}{}{Xanderwurzel (1), Brokblüte (1), sauberes Wasser (1), leere Spritze (1)}

{222}{}{Super-Stimpak.}
{223}{}{stimpak (1), Nuka-Cola (1), Mutafrucht (1)}

{224}{}{Hausgemachte RadAway.}
{225}{}{Vocasnusslösung (1), Blutreiniger (1), sauberes Wasser (1)}

{226}{}{Arzttasche.}
{227}{}{Skalpell (1), Silbergecko-Fell (1), leere Spritze (1), Desinfektionsmittel (1), Gegengift (1), Schmerzmittel (1)}

{228}{}{Leguanmahlzeit.}
{229}{}{Leguan am Spieß (2)}

{230}{}{Karawanenmahlzeit.}
{231}{}{Mutafrucht (1), Dörrfleisch (1), brahmin-Milch (1)}

{232}{}{Fernsehmahlzeit (+25 Trefferpunkte).}
{233}{}{Fernsehmahlzeit (1)}

{234}{}{Nudeln zubereiten (+25 Trefferpunkte).}
{235}{}{Nudelpackung (1), sauberes Wasser (1)}

{236}{}{Molotowcocktail.}
{237}{}{Rot Gut (1), Leuchtfackel (1)}

{238}{}{Alkohol (10).}
{239}{}{Melasse (1), sauberes Wasser (1)}

{240}{}{Mantis-Snack (2).}
{241}{}{Mantis-Teil (2), Bier (1), Mutfrucht (1)}
