{100}{}{Du kannst dieses Gerät nicht im Kampf benutzen.}
{101}{}{Dieses Gerät kann nur benutzt werden, wenn du es in den Händen hältst.}

{102}{}{Dein Vorrat an schwerer Munition ist aufgebraucht.}

#Menu options
{110}{}{Die Munitionspresse ist einsatzbereit. Wähle dein Kaliber.}
{111}{}{[Liegen lassen]}
{112}{}{[Fertig]}

{113}{}{[Munition herstellen]}

{114}{}{Für eine Ladung Munition werden }
{115}{}{ Komponenten benötigt. Im Rucksack hast du }
{116}{}{ Komponenten.}
{117}{}{}
{118}{}{[Panzerbrechende Munition herstellen]}
{119}{}{[Eine Ladung Munition herstellen]}

{120}{}{[Fertig]}
{121}{}{[Zurück zur Kaliberliste]}
{122}{}{[Erneut versuchen]}
{123}{}{[Nächste Liste]}
{124}{}{[Vorherige Liste]}

#Caliber choosing
{200}{}{}
{201}{}{10 mm}
{202}{}{12 Gauge}
{203}{}{0,44 Magnum}
{204}{}{0,223}
{205}{}{0,30 Gewehr}
{206}{}{9 mm}
{207}{}{}
{208}{}{0,45}
{209}{}{5 mm}
{210}{}{12 Gauge Münzschrot (benötigt schwere Kugeln)}
