#Starting and typical dialogue options
{109}{}{Du musst die Hände frei haben, um die Werkbank zu benutzen.}
{110}{}{Du kannst die Werkbank nicht im Kampf benutzen.}
{111}{}{An dieser Werkbank kannst du Gegenstände reparieren oder verbessern, wenn du die nötigen Fertigkeiten und Materialien hast.}
{112}{}{}
{113}{}{Geh weg.}
{114}{}{An die Arbeit.}
{115}{}{Zurück zur Liste.}
{116}{}{Ende.}
{117}{}{Erledigt.}
{118}{}{> Nächste Liste.}
{119}{}{< Vorherige Liste.}

#Assembly
{120}{}{Herstellen }
{121}{}{.}
{122}{}{, }
{123}{}{ >=}
{124}{}{}
{125}{}{Materialien: }
{126}{}{. Voraussetzungen: }
{127}{}{ (}
{128}{}{Menge)}
{129}{}{Voraussetzungen: }

#Special options for "Savage 410"
{150}{}{Welche Art Leder möchtest du für den Patronengurt verwenden?}
{151}{}{Silberne Geckohaut verwenden (2).}
{152}{}{Goldene Geckohaut verwenden (1).}
{153}{}{Säuregeckohaut verwenden (1).}
{154}{}{Lederjacke verwenden (1).}
{155}{}{Verstärkte Lederjacke verwenden (1).}
{156}{}{Selbstgemachte Jacke verwenden (1).}
{157}{}{Zerlumpte Raiderjacke verwenden (1).}
{158}{}{Silberne Geckohaut verwenden (1).}

#Additional information to the console
{160}{}{Du studierst die Informationen über den Verstärker, kommst aber schließlich zu dem Schluss, dass er dir nichts nützen wird. Du verfügst bereits über diese Fähigkeit.}
{161}{}{Du hast den Vorteil „Empathie“ erhalten.}
{162}{}{Du knackst heimlich den Koffer und steckst 500 $ ein, dazu eine Packung Mentats und ein Pip-Boy-Modul. Dem Besitzer würde das vermutlich nicht gefallen.}
{163}{}{Du zerlegst die Munition in }
{164}{}{ Blei- und Pulverbestandteile.}
{165}{}{Du ersetzt das kaputte Strahlungsmessgerät in deinem Pip-Boy. Jetzt kannst du jederzeit deine genaue Strahlenbelastung ermitteln, indem du dich gründlich untersuchst.}
{166}{}{Du studierst die Anleitung sorgfältig und verbesserst deine Kampfsportfähigkeiten um } #I wasn't sure if this would be a bonus to Unarmed and Melee or just unarmed, so I kept it vague.

#Special options about repairing tattered jacket
{180}{}{Du brauchst mehr Leder, um diese Jacke wiederherzustellen.}

#Name of theassembling product + list of components
#(no comma at the end of list of components)
#(Each first line goes with a capital letter, the second one doesn't)

{200}{}{Munitionspresse verbessern.}
{201}{}{Munitionspresse (1), Schrott (1)}

{202}{}{Reinige die rostige Machete.}
{203}{}{rostige Machete (1), Flammenwerfer-Treibstoff (1), Rot Gut (1)}

{204}{}{Reinige das rostige Katana.}
{205}{}{rostiges Katana (1), Flammenwerfer-Treibstoff (1), Rot Gut (1)}

{206}{}{Münzmarken, um Nuka-Cola-Maschinen zu täuschen (50).}
{207}{}{Schrott (1)}

{208}{}{Repariere den mysteriösen Blaster aus Area 51.}
{209}{}{mysteriöser Blaster (1), Schrott (1)}

{210}{}{Repariere das 2043B-Funkgerät.}
{211}{}{Funkgerät (1), Schrott (1)}

{212}{}{„Mickey's Revenge“.}
{213}{}{Baupläne für „Mickey's Revenge“ (1), Schrott (1), Toaster (1), Sklavenhalsband (1)}

{214}{}{Reinige die alte „Lucky“-Pistole.}
{215}{}{„Lucky“-Pistole (1)}

{216}{}{Patronengurt für die „Savage“-Schrotflinte.}
{217}{}{„Savage 410“-Schrotflinte (1), Leder}

{218}{}{Dynamit zerlegen.}
{219}{}{Dynamit (1)}

{220}{}{PLC wiederherstellen.}
{221}{}{PLC (1)}

{222}{}{Die großkalibrige Munition von Hawthorne zerlegen.}
{223}{}{Munitionskiste (1)}

{224}{}{Schwarzpulverzünder.}
{225}{}{Bauplan für „Schwarzpulverzünder“ (1), Munitionsreste (30), Rot Gut (1), Signalrakete (1)}

{226}{}{}
{227}{}{}

{228}{}{Jagdspeer.}
{229}{}{Messer (1), Holzpflock (1)}

{230}{}{Bordcomputer des Zuges reparieren.}
{231}{}{Bordcomputer (1), Schrott (1)}

{232}{}{Sonarscanner am Metalldetektor installieren und debuggen.}
{233}{}{Metalldetektor (1), Sonarscanner (1)}

{234}{}{Bertolinis kaputten Queue reparieren.}
{235}{}{Queue (1), Bertolinis Queue (1)}

{236}{}{Einen Wanzen-Sender an Bertolinis Queue-Koffer anbringen.}
{237}{}{Wanzen-Sender (1), Bertolinis Queue (1)}

{238}{}{Den Wanzen-Sender aus Bertolinis Queue-Koffer entfernen.}
{239}{}{Bertolinis Queue (1)}

{240}{}{Beschädigte Laserpistole reparieren.}
{241}{}{beschädigte Laserpistole (1), Schrott (1)}

{242}{}{Defekte Mikro-Fusionszelle reparieren.}
{243}{}{defekte Mikro-Fusionszelle (1)}

{244}{}{Empathieverstärker an deinem Pip-Boy installieren.}
{245}{}{Pip-Boy-Empathieverstärker (1)}

{246}{}{Die Geschäftskassette des Hard Rock-Gönners aufbrechen.}
{247}{}{Geschäftskassette (1)}

{248}{}{Panzerplatten an der kugelsicheren Weste anbringen.}
{249}{}{Panzerplatten (1), Weste (1). Auf dem Etikett der Weste steht: „Vor dem Ändern Weste ausziehen!“}

{250}{}{Nelsons Schrotflinte reparieren.}
{251}{}{Nelsons kaputte Schrotflinte (1), Schrott (1), Waffenteile (1)}

{252}{}{Das Radiometer aus dem kaputten Pip-Boy 2000 ausbauen.}
{253}{}{kaputter Pip-Boy (1)}

{254}{}{Die beschädigte Lederjacke wiederherstellen.}
{255}{}{zerrissene Jacke (1), Leder. Auf dem Etikett der Jacke steht: „Vor dem Ändern Jacke ausziehen!“}

{256}{}{„Kubotan“.}
{257}{}{„Kubotan“-Baupläne (1), Schrott (1), Kubotan-Schlüssel (10)}

{258}{}{Kubotan-Schlüssel vorbereiten: }
{259}{}{Schlüssel (1)}

{260}{}{Die Geschäftskassette des Hard Rock-Gönners öffnen.}
{261}{}{Geschäftskassette (1), Werkzeug (1)}

{262}{}{Aus dem Panzer eines legendären Skorpions eine Rüstung herstellen.}
{263}{}{Panzer eines legendären Skorpions (1), Goldener-Gecko-Balg (4)}

{264}{}{Die alte Holodisk entschlüsseln.}
{265}{}{alte Holodisk (1)}

{266}{}{2-mm-EC-Munition herstellen.}
{267}{}{Schrott (2)}

{268}{}{Eine 10-mm-Waffe aus Ersatzteilen zusammenbauen.}
{269}{}{Waffenteile (5)}
