{100}{}{Dieses Auto scheint im Moment nicht zu funktionieren, aber vielleicht lässt es sich reparieren.}
{101}{}{Du kannst während eines Kampfes kein Auto starten!}
{102}{}{Du hast das Auto gestohlen!}

#Using controller, regulator or repair skill on car
{200}{}{Du reparierst das Auto erfolgreich mit dem Kraftstoffregler.}
{210}{}{Du konntest das Auto nicht mit dem Kraftstoffregler reparieren.}
{211}{}{Deine Fähigkeiten reichen nicht aus, um den Regler in diese komplizierte Maschine einzubauen.}
{212}{}{Kraftstoffregler eingebaut! Jetzt verbraucht dein Gefährt weniger Treibstoff.}
{213}{}{Jetzt leuchtet dein Fahrzeug seinen Weg mit brandneuen Scheinwerfern aus.}
{214}{}{Mit deinen Fähigkeiten weißt du nicht einmal, wo du anfangen sollst, die kaputten Scheinwerfer auszubauen.}
{215}{}{Es gibt absolut keinen Grund, einwandfrei funktionierende Scheinwerfer auszutauschen.}

{300}{}{Fähigkeiten allein reichen nicht aus.}

#When using a car
{301}{}{Dieses Fahrzeug springt nicht an. Ein entscheidendes Teil fehlt – ein Kraftstoffregler. Außerdem sind nirgends Schlüssel zu sehen.}
{302}{}{Versuche, das Teil einzubauen.}
{303}{}{Jetzt nicht.}
{304}{}{Ein Wunder! Du bringst das Teil mühelos an den Drähten und Schläuchen an!}
{305}{}{-mehr-}
{306}{}{Das Auto ist fahrbereit, aber es fährt nicht, da keine Ladung mehr vorhanden ist. Du brauchst mindestens zwei Mikrofusionszellen.}
{307}{}{Mikrofusionszellen austauschen.}
{308}{}{Erledigt!}
{309}{}{Wow! Jetzt kommen wir der Sache näher!}
{310}{}{Das Auto ist startklar. Es muss nur noch gestartet werden. Der Zündschlüssel fehlt.}
{311}{}{[Versuchen, das Auto kurzzuschließen]}
{312}{}{Das Auto mit dem Schlüssel starten, den du Techniker Anders abgenommen hast.}
{313}{}{Es lebt! Es lebt!}
{314}{}{Los geht's!}
{315}{}{Du konntest nicht herausfinden, was mit dieser ungewöhnlichen Technologie zu tun ist.}
{316}{}{Schade.}
{317}{}{Schilde hoch, Waffen online!}
{318}{}{Das Auto läuft!}
{319}{}{Du konntest nicht herausfinden, welche Kabel wohin gehören.}
{320}{}{Das ist zu verwirrend.}

#Tech's pop-ups when stealing a car
{321}{}{Du verdammter Mistkerl! Ich bring dich um!!!}
{322}{}{Ich finde dich und bring dich um!!! Hörst du?!}

{323}{}{Versuche, die Zündanlage wieder einzubauen.}
