########################################
#
#    Îïèñàíèÿ êğåñòîâ è ìîãèëüíûõ êàìíåé. Àâòîğ Kerb.
#
########################################

{10}{}{Du siehst ein Grabkreuz.}
{11}{}{Du siehst einen Grabstein.}
{12}{}{Du siehst eine Grabplatte.}

{20}{}{Auf dem Kreuz steht: "}
{21}{}{Auf der Grabplatte steht: "}
{22}{}{}
{23}{}{"}
{24}{}{Hier stand einmal etwas geschrieben, doch die Zeit hat es ausgelöscht.}
{25}{}{Dieses Kreuz ist unbeschriftet.}

#Êàôå Íîâûõ íàäåæä
{30}{}{Der Friedhof begrabener Ideen.}

#Øàéåíí
{100}{}{Ahiga der Zerschmetternde. Auf den Feldern der Ewigen Jagd, schlag mit deinem Speer nach den Dienern des Verschlingers ...}
{101}{}{Mechitehyu der Schatten des Mondlichts. Sein Geist wandelt noch immer mit den Nachtwinden ...}
{102}{}{Pouoka der Wächter durch die Zeit: 1877 – der Herbst der Cheyenne, 2077 – das Ende der Alten Welt, 2277 – lasst die Legion kommen ...}
{103}{}{Otaktay der Folternde Wolf. Er bevorzugte die Streitaxt gegenüber der Friedenspfeife.}

#Ïğîâî
{150}{}{Freddie „Gorefiend“ Voorhees: Sie haben den „Ripper“ nach mir benannt, Baby!}
{151}{}{Dallas „Evil Kitty“ Ocasec. Ein heißes kleines Ding, das selbst in den Tiefen der Hölle noch kalt wird.}
{152}{}{Nick „Savage“ Eckhart. 17 Morde, 4 Raubüberfälle, 9 Vergewaltigungen – und das war nur eine Woche.}
{153}{}{Arkin „Shiz“ Fernandez. Hasste seine Familie so sehr, dass er sich nach einer Woche ohne sie das Hirn wegpustete, um sie in der Hölle weiter zu quälen.}
{154}{}{Kevin „The Postman“ Brooks. Wohltäter, Familienvater, sadistischer Kannibale.}
{155}{}{Patrick „Kein Tag ohne Schmerzen“ Bale. Satan schickte ihn, Satan holte ihn zurück.}
{156}{}{Stephen „Arrow“ Travis. Er liebte nur seinen Hund Lilly ... Und zwar auf ganz normale Weise, Arschloch!}

#Âåãàñ
{200}{}{Brunson, Phil. Hervorragender Abend – angenehme Gesellschaft – 8 Bestechungen – Herzinfarkt.}
{201}{}{Chris Buddy. Seltenes Arschloch – ging mit drei Assen unter.}
{202}{}{Johnny „Zero“ Hellmuth. Ein echter Spieler ist nie zu arm, um Chips zu kaufen, solange er noch zwei Nieren hat.}
{203}{}{Mordecai Ungar. Die Lichter von Vegas riefen ihn, und seine Träume gingen darin in Flammen auf.}
{204}{}{Oscar „Toothy“ Manfredi. Im Ring schweige ich, denn meine Fäuste sprechen für mich.}

#Áëıê-Ğîê
{250}{}{Patricia Whitman. Meine Liebe zu dir war wie eine nukleare Explosion – schön, blendend und tödlich ...}
{251}{}{Michael „Runner“ Phelps. Seine letzten hundert Yards lief er ohne Kopf auf den Schultern.}
{252}{}{Marion Connelly. Sie starb an einer Überdosis – hielt aber ihr Versprechen, mit dem Rauchen aufzuhören.} #The original line referenced crack here, but I'm not sure if that fits in the Fallout lore so I kept it vague.
{253}{}{Lorenz Tate. In diesen Gegenden erschießen wir immer noch den Überbringer schlechter Nachrichten.}
{254}{}{Martin „Nomad“ Wallace. Der letzte romantische Reisende.}

#Ñîëò-Ëåéê
{300}{}{Gabriel „Jesuit“ Borgia. Er trank nicht, rauchte nicht und fluchte nicht, aber das deathclaw war nicht beeindruckt.}
{301}{}{Oliver Smith. „Ich erlebte einen Tag des Jüngsten Gerichts – um zum zweiten aufzustehen!“}
{302}{}{Fuzzy, Gourmet und Striped Tail. Frauen, Kinder und Alte umzubringen, ist verständlich. Aber welches Monster würde einer Katze etwas antun?!}
{303}{}{Oliver Rigdon. Das war alles, was man über ihn wusste.}
{304}{}{Vic Allison. Merkte zu spät, dass „Aqua Regia“ kein neues Getränk aus dem „Tin Angel“ war.}
{305}{}{Hayley Ross. Ihr Mann glaubte nicht an ihre unbefleckte Empfängnis.}
{306}{}{Adam „Cleaner“ Garner. Er erledigte die Drecksarbeit ... und machte sich am Ende selbst sauber.}
{307}{}{George „Commie“ Glick. Ihr werdet mich hier niemals kriegen, ihr gierigen Hunde des Kapitalismus!}
{308}{}{Johnny Melton. „Wie der Mensch jetzt ist, so war einst der Herr; wie der Herr jetzt ist, so war einst der Mensch.“}
{309}{}{Joseph Harris. „... Und bis an die Schwelle des Todes legte ich meine Arme ins Grab und diente unserem Schöpfer unermüdlich ...“}
{310}{}{Unbekannt. Seine letzten Worte waren: „Ich erwarte euch an den Toren der Hölle, Sünder!“}

#Âåòåğ Âîéíû
{350}{}{Captain Benjamin Kurtz. In die Hölle gegangen, um sich neu zu formieren.}
{351}{}{Private First Class Chris „Dull“ Lerner. Lächelte immer beim Töten.}
{352}{}{Corporal James Hartman. Er hätte den Namen seiner Mutter über der Seriennummer seiner persönlichen Waffe vergessen.}
{353}{}{Mayor Alex „Gravedigger“ Turchin. Wo wir vorbeiziehen, herrscht lange Stille.}
{354}{}{Sergeant Richard „Nuclear“ Beckett. Unsichtbar, allgegenwärtig und tödlich.}

#Ğèíî
{400}{}{Maureen Luciano.}
