{100}{}{Du siehst einen Verkaufsautomaten.}
{101}{}{Du siehst den Nuka-Cola-Automaten – ein unverzichtbares Werkzeug für dein Geschäft.}
{102}{}{Dieser Automat ist kaputt und ausgeraubt.}
{103}{}{Nicht während eines Kampfes!}

#Starting conversation:
{110}{}{Dieser Automat funktioniert noch und bringt dir Einnahmen.}
{111}{}{Einnahmen abholen.}
{112}{}{Colaflaschen einladen.}
{113}{}{Colaflaschen ausladen.}
{114}{}{Wie viel Cola ist noch auf Lager?}
{115}{}{Voraussichtlichen Gewinn anzeigen.}
{116}{}{Automat verlassen.}
{117}{}{}
{118}{}{}
{119}{}{}

#Take the revenue:
{120}{}{Deine Einnahmen im letzten Zeitraum betrugen $}
{121}{}{.}
{122}{}{Zurück.}
{123}{}{Kasse schließen.}
{124}{}{Seit der letzten Einnahme sind keine Münzen im Automaten aufgetaucht.}
{125}{}{Der Automat ist leer.}

#How many bottles left, and other statistics
{130}{}{Es ist kein Produkt mehr auf Lager.}
{131}{}{Die Maschine enthält }
{132}{}{ Nuka-Cola Flaschen.}

{133}{}{Vermutlich sind die Einwohner bereit, etwa }
{134}{}{ Flaschen Getränke pro Tag zu kaufen, solange die soziale Lage der Stadt gleich bleibt.}

#Load cola
{140}{}{Bitte fuell die Cola in den Behälter.}
{141}{}{5 Flaschen.}
{142}{}{10 Flaschen.}
{143}{}{20 Flaschen.}
{144}{}{30 Flaschen.}
{145}{}{50 Flaschen.}
{146}{}{100 Flaschen.}
{147}{}{[Alle verfügbaren Colaflaschen einfüllen]}
{148}{}{[Liegen lassen]}
{149}{}{[Fertig]}

#Unload cola
{150}{}{Die Maschine enthält }
{151}{}{ Nuka-Cola Flaschen}
{152}{}{}
{153}{}{5 Flaschen nehmen.}
{154}{}{10 Flaschen nehmen.}
{155}{}{20 Flaschen nehmen.}
{156}{}{30 Flaschen nehmen.}
{157}{}{50 Flaschen nehmen.}
{158}{}{100 Flaschen nehmen.}
{159}{}{[Alle übrigen Flaschen nehmen]}
{160}{}{[Liegen lassen]}
{161}{}{[Fertig]}
{162}{}{Es ist kein Produkt mehr auf Lager.}
{163}{}{Tut mir leid, du kannst nicht so viel tragen.}
{164}{}{[So viele Flaschen nehmen, wie ich tragen kann]}
