#Îáùèå ğåïëèêè
{100}{}{Das kannst du im Kampf nicht tun.}
{101}{}{Nicht schlecht.}
{102}{}{Nichts Brauchbares.}
{103}{}{Dein Überlebenskünstler-Talent erlaubt es dir, mehr als üblich zu sammeln.}

#Ñòğîêè äëÿ ïàñëåíà
{200}{}{Du siehst eine Nachtschattenpflanze.}
{201}{}{Du siehst eine Nachtschattenpflanze. Sie trägt einige Beeren.}
{202}{}{Du pflückst einige Nachtschattenbeeren.}
{203}{}{Diese Nachtschattenpflanze trägt noch keine Beeren.}

#Ñòğîêè äëÿ öâåòêà áğîê
{300}{}{Du siehst eine Broc-Pflanze.}
{301}{}{Du siehst eine Broc-Pflanze. Du glaubst, dass man die Blüten ernten kann.}
{302}{}{Du erntest einige Broc-Blüten.}
{303}{}{Diese Broc-Pflanze hat noch keine Blüten.}

#Ñòğîêè äëÿ êñàíäåğ
{400}{}{Du siehst etwas Xander.}
{401}{}{Du siehst etwas Xander. Du glaubst, dass man die Wurzeln ernten kann.}
{402}{}{Du sammelst einige Xanderwurzeln.}
{403}{}{Hier gibt es nicht genug zum Ernten.}

#Ñòğîêè äëÿ âîêàñ
{500}{}{Du siehst eine überwucherte, mutierte Seerose.}
{501}{}{Du siehst eine überwucherte, mutierte Seerose. Daran sind einige reife Nüsse zu erkennen.}
{502}{}{Du sammelst einige reife Nüsse.}
{503}{}{Diese mutierte Seerose trägt noch keine Nüsse.}
