{100}{}{Ein Steckbrief mit einer groben Kohlezeichnung der gesuchten Person. Die Person auf dem Plakat kommt dir bekannt vor.}
{101}{}{Die Bildunterschrift lautet:}
{102}{}{Tot oder lebendig gesucht wegen Kindermords und weil er ein verdammter Rattenbastard ist. Belohnung: 10.000 $ tot oder 5.000 $ lebendig.}
{103}{}{Tot oder lebendig gesucht wegen Kindermords. Belohnung: 10.000 $ tot oder 5.000 $ lebendig.}
{104}{}{Tot oder lebendig gesucht, weil er ein verdammter Rattenbastard ist. Belohnung: 10.000 $ tot oder 5.000 $ lebendig.}
{105}{}{Tot oder lebendig gesucht wegen Überfällen auf Karawanen. Belohnung: 5.000 $ tot oder 2.000 $ lebendig.}

{110}{}{Ein Steckbrief mit einer groben Kohlezeichnung der gesuchten Person.}
{111}{}{Du siehst nichts Ungewöhnliches.}

#female
{1102}{}{Tot oder lebendig gesucht wegen Kindermords und weil er ein verdammter Rattenbastard ist. Belohnung: 10.000 $ tot oder 5.000 $ lebendig.}
{1103}{}{Tot oder lebendig gesucht wegen Kindermords. Belohnung: 10.000 $ tot oder 5.000 $ lebendig.}
{1104}{}{Tot oder lebendig gesucht, weil er ein verdammter Rattenbastard ist. Belohnung: 10.000 $ tot oder 5.000 $ lebendig.}
{1105}{}{Tot oder lebendig gesucht wegen Überfällen auf Karawanen. Belohnung: 5.000 $ tot oder 2.000 $ lebendig.}
