#Translated by TheChosenOne, corected by Keyboard Gecko
{0}{}{ }

#Use of skills
{90}{}{Du hast die Falle entschärft.}
{91}{}{Du konntest die Falle nicht entschärfen.}
{92}{}{Das war wohl nicht die beste Entscheidung.}

#Primitive mind
{100}{}{Ughh!!!}

{101}{}{Hoppla! Ich stolpern?!}
{102}{}{Du lachen über mich?}
{103}{}{Ich Glück haben – nicht verletzt.}
{104}{}{Das jetzt meins.}
{105}{}{Ooh! Ich Nase brechen!}
{106}{}{Worauf ich treten?}
{107}{}{Oooh! Diese Mine jetzt meins.}
{108}{}{::unleserlicher Wortfluss::}
{109}{}{::murmelt und flucht bedrohlich::}

#Kids
{110}{}{Verdammt!!!}
{111}{}{Ach, verdammt! Schon wieder meine Hose zerrissen. Mom bringt mich um ...}
{112}{}{Oooh, na ja!!!}
{113}{}{Ich bin so tollpatschig!}

#Prostitutes
{120}{}{Verdammt noch mal!!!}

{121}{}{Ah! Mein Höschen rutscht!}
{122}{}{Hat jemand mein Höschen gesehen?}
{123}{}{*richtet den Rock*}
{124}{}{Das ist nicht lustig!}
{125}{}{Für ein dreckiges Gesicht bezahlt man mich nicht.}
{126}{}{Hab meinen ganzen Scheiß verloren ... Schon wieder.}
{127}{}{Verdammte Rotzbengel! Hoffentlich finde ich euch nicht!}
{128}{}{}
{129}{}{}

#Citizens
{130}{}{Was zum Teufel?!}

{131}{}{Soll das ein Witz sein?!}
{132}{}{DESHALB muss man Kinder versohlen!}
{133}{}{Das ist ein ziemlich dummer Witz, weißt du ...}
{134}{}{Das ist nicht lustig!}
{135}{}{Wer war das?! WER ZUM TEUFEL WAR DAS?!}
{136}{}{Sieht so aus, als sollte ich hier nicht herumstreunen ...}
{137}{}{Verdammte Kinder! Wenn ich euch finde, tret ich euch in den Arsch!}
{138}{}{Hey! Wer glaubt hier, witzig zu sein?! Ich tret dir in den Arsch!}
{139}{}{Ahh, auf diesen dämlichen Trick bin ich reingefallen!}

#Workers
{140}{}{Verdammte Scheiße!!!}

{141}{}{Welcher Vollidiot war das?!}
{142}{}{Was für ein beschissener Tag!}
{143}{}{Ich brauch danach ein Bier.}
{144}{}{Ugh! Muss schon wieder meine Hose waschen.}
{145}{}{Ugh ... Meine Sohlen sind im Arsch.}
{146}{}{Ich finde diesen Witzbold, und wenn ich ihn erwische ... frisst jemand Staub!}
{147}{}{Macht euch bereit, ihr Punks! Jetzt bin ich *richtig* sauer!}
{148}{}{Wer ist denn dieser Weichling?! Hä?}
{149}{}{Hey! Komm raus, Arschloch!!!}

#Farmers
{150}{}{Scheiß drauf!!!}

{151}{}{Wer war das?!}
{152}{}{Kann dieser Tag noch schlimmer werden?!}
{153}{}{Soll das ein Witz sein?! Gar nicht lustig!}
{154}{}{Ich hab den ganzen Tag gearbeitet, und du legst dich mit mir an?!}
{155}{}{Ugh ... Meine Sohlen sind im Arsch.}
{156}{}{Ich finde diesen Witzbold, und wenn ich ihn erwische ... frisst jemand Staub!}
{157}{}{MACH DAS NIE WIEDER!!!}
{158}{}{Willst du mich verarschen?!}
{159}{}{}

#Fallen
{160}{}{Oh!!!}

{161}{}{!?}
{162}{}{Ah ... Pech gehabt ...}
{163}{}{Soll das ein Witz sein?!}
{164}{}{Ich bin ... Ich ... Weißt du überhaupt, WER ICH BIN?!}
{165}{}{Ughh ...}
{166}{}{::stöhnt und rappelt sich aus dem Schlamm hoch::}
{167}{}{WAG ES JA NICHT, DAS NOCH MAL ZU MACHEN!!!}
{168}{}{}
{169}{}{}

#Enclave
{170}{}{VERDAMMT NOCH MAL!!!}
{171}{}{Ich finde dich und dann zerreiße ich dich in Stücke!!!}
{172}{}{WILLST DU MICH VERARSCHEN!? KOMM RAUS UND KÄMPF, DU KLEINE SCHLAMPE!!!}

#Brotherhood
{180}{}{Verdammt noch mal!!!}

{181}{}{Ist das für mich, oder was?!!!}
{182}{}{Du bist tot, Schlaumeier!}
{183}{}{Das war's! Du bist erledigt!}
{184}{}{Wer war das?! Wer zum Teufel war das?!!!}
{185}{}{Na, na! Was haben wir denn hier? Noch ein wandelnder Toter?}
{186}{}{He, Schlaumeier? Komm raus, dann klären wir das wie Männer!}
{187}{}{Heute ist nicht dein Tag, Kumpel!}

#Soldiers
{190}{}{Verdammt noch mal!!!}

{191}{}{Ist das für mich, oder was?!!!}
{192}{}{Du bist tot, Arschloch!!!}
{193}{}{Ich stopf dir den Kopf so tief in den Arsch!!!}
{194}{}{Ich finde dich, das schwöre ich!}
{195}{}{Wer war das?! Wer zum Teufel war das?!!!}
{196}{}{Ich werd dich!... Ich weiß nicht mal, *was* ich mit dir machen werde!!!}
{197}{}{He, Schlaumeier! Komm raus, dann klären wir das wie Männer!}

#Mutants 
{200}{}{WAAAAGH!!!}
{201}{}{Ich reiße dir die Arme aus! Und die Beine!.. und... den Schwanz!}
{202}{}{Ich finde dich und stampfe dich ins Grab!}
{203}{}{Perfekt! Noch eine Leiche. Komm einfach raus!}

#Ghouls
{210}{}{Au-au-au!!!}
{211}{}{Ein Auge mehr oder weniger, wen kümmert's?}
{212}{}{Ich glaube, mein Ohr ist abgefallen...}
{213}{}{Hat jemand gesehen, wo mein Daumen hin ist?}
{214}{}{Ich seh gar nicht mal so übel aus!}
{215}{}{Uff! Hauptsache, ich lebe noch!}
{216}{}{Leute! So grausam könnt ihr doch nicht sein!}

#Punks
{220}{}{Aiee!!!}
{221}{}{Wessen Eier müssen jetzt an den Galgen?! Na los!}
{222}{}{Komm raus! Ich tu dir nichts!}
{223}{}{Ich hab dich gesehen, Witzbold! Ich weiß, wer du bist! Und jetzt komm raus!}
{224}{}{Wer war das?! Versteckst du dich, du kleines Weichei?! DU BIST SCHWACH! SCHWACH!!!}
{225}{}{Wenn ich dich finde – dann frisst du Staub!}

#Hubbologists
{230}{}{Oh!!!}
{231}{}{Hm ... Sieht aus, als wäre ich in eine Falle getappt.}
{232}{}{Das sind wohl keine Kinder, die herumalbern.}
{233}{}{Ich bin mir nicht sicher, aber ich glaube, da wollte mich jemand umbringen!}
{234}{}{Für wen diese Falle wohl gedacht war?}

#Robots
{270}{}{Hindernis erkannt.}
{271}{}{Hindernis beseitigt.}
{272}{}{Gefährliches Gerät erkannt. Möglicherweise befinden sich Feinde in der Nähe.}
{273}{}{Aufmerksamkeitsprotokolle werden ausgeführt.}
{274}{}{WARNUNG! SABOTAGEVORRICHTUNG ERKANNT!!!}

{300}{}{Deine Falle hat funktioniert und das Ziel verletzt.}
{301}{}{Deine Falle hat funktioniert. Das Ziel stürzt und lässt all seine Sachen fallen.}
{302}{}{Dein Ziel hat deine Falle entdeckt und entschärft.}
{303}{}{Dein Ziel hat sich eine Gliedmaße verletzt.}
{304}{}{Der Roboter tappt in die Falle, doch seine schiere Masse durchbricht sie einfach.}
{305}{}{Das Tier stolpert über das Seil, rappelt sich aber sofort wieder auf.}
{306}{}{Wütend zerstört dein Ziel die Falle.}
