{100}{}{Du hast eine Falle entdeckt.}
{101}{}{Durch einen glücklichen Zufall ging die Mine nicht hoch.}
{102}{}{Du hast die Falle entschärft.}
{103}{}{Das war keine gute Idee.}
{104}{}{Du konntest die Falle nicht entschärfen.}
{105}{}{Das ist eine Falle!}
{106}{}{ hat eine Mine entdeckt.}
{107}{}{Entschärft}
{108}{}{Du bist der Mine erfolgreich ausgewichen.}
{109}{}{Mit deinem Metalldetektor entdeckst du eine Falle.}
{110}{}{Wegen deiner Ungeschicklichkeit geht die Falle kaputt.}
{111}{}{Du entdeckst die Falle gerade noch rechtzeitig und springst darüber.}
{112}{}{Diese Falle ist zu kompliziert für dich.}
{113}{}{Diese Falle ist scharf und gefährlich.}
