# 
# FALLOUT BATTLECRIES
# When the Bomb Drops, the real fun begins - So let's get to Work!!!
#
# Version 1.0  May 13, 1997  Scott Bennie
#         1.1  May 14, 1997  Chris Taylor (edits and line number change)
#         1.2  June 19, 1997 Leonard, Jason, Chris (edits)
#
# Version 2.0 July 29, 1998 Feargus Urquhart - modified for Fallout 2, most text has been rearranged, however some lines were still authored by the above people.
#
#  READ THIS!! READ THIS!! READ THIS!! READ THIS!!
#
#  This new file is different than the old one in that body locations are listed in a generic fashion first and are only listed for particular types of characters.  This is followed by a list of generic characters, which is then followed by the more specific taunts and party member taunts.
#
#
####################################################################################
#
#                    Generic Body Parts
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#
#                     1000 Wimpy Person
#                     1100 Normal Person
#                     1200 Tough Person
#                     1300 Berserk Person
#                     1400 Robot
#                     1500 Primitive
#                     1600 Ghoul
#                     1700 Raider (Khan)
#                     1800 Junkie
#
####################################################################################
#
#
############################################
# 1000 Wimpy Person
############################################
#
# target hit in head
#
{1000}{}{Mein Gesicht! Mein Gesicht!}
{1001}{}{Au! Das hat wehgetan!}
{1002}{}{Autsch! Ich brauche etwas Eis für meinen Kopf}
#
# target hit in left arm
#
{1010}{}{Au, mein Arm}
{1011}{}{Au!}
{1012}{}{Du hast mir den Arm gebrochen!}
#
# target hit in right arm
#
{1020}{}{Au, mein Arm}
{1021}{}{Wahhhh!}
{1022}{}{Mein Gott! Mein Arm!}
#
# target hit in torso
#
{1030}{}{Au! Das hat wirklich wehgetan!}
{1031}{}{Ich glaube, ich werde gleich ohnmächtig}
{1032}{}{Autsch!}
{1033}{}{Uff!}
{1034}{}{Das hat wehgetan!}
{1035}{}{Lass mich einfach in Ruhe!}
{1036}{}{Ohhh, diese Schmerzen!}
#
# target hit in right leg
#
{1060}{}{Au, mein Bein}
{1061}{}{Mein Knie!}
{1062}{}{Au!}
#
# target hit in left leg
#
{1070}{}{Au, mein Bein}
{1071}{}{Mein Knie!}
{1072}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{1080}{}{Au!! Meine Augen!}
{1081}{}{Mein Gesicht! Meine Augen! Arrrrgh!}
{1082}{}{Meine Augen!}
#
# target hit in groin
#
{1090}{}{Ooooooooo, meine Leiste! Ooooooo...}
{1091}{}{Autsch... Es brennt!}
{1092}{}{Würg!}
{1093}{}{Ooorp! aoooww...}
{1094}{}{Ich... kann... nicht... atmen...}
{1095}{}{Der Schmerz, der Schmerz...}
#
############################################
# 1100 Normal Person
############################################
#
# target hit in head
#
{1100}{}{Verdammt!}
{1101}{}{Mein schmerzender Schädel}
{1102}{}{Mein Gesicht! Mein Gesicht!}
#
# target hit in left arm
#
{1110}{}{Aggghhh! Mein Arm}
{1111}{}{Mein Arm!}
{1112}{}{Mann, tut das weh!}
#
# target hit in right arm
#
{1120}{}{Aggghhh! Mein Arm}
{1121}{}{Mein Arm!}
{1122}{}{}
#
# target hit in torso
#
{1130}{}{}
{1131}{}{Uff!}
{1132}{}{Autsch!}
{1133}{}{Uff! Meine Rippen tun weh}
{1134}{}{Ugh! Das hat wehgetan!}
{1135}{}{Verdammt! Ich spucke auf dich!}
{1136}{}{Argh!}
{1138}{}{Oh, meine Rippen!}
{1139}{}{Au!!!}
{1140}{}{Uff!}
#
# target hit in right leg
#
{1160}{}{Aggghhh! Mein Bein}
{1161}{}{Mein Bein!}
{1162}{}{Das war's mit meinem Knie}
#
# target hit in left leg
#
{1170}{}{Aggghhh! Mein Bein}
{1171}{}{Mein Bein!}
{1172}{}{Das war's mit meinem Knie}
#
# target hit in eyes
#
{1180}{}{Aggghhh! Ich bin blind!}
{1181}{}{Meine Augen! Meine Augen!}
{1182}{}{Mein Auge! Dafür wirst du bezahlen!}
#
# target hit in groin
#
{1190}{}{Aua, meine Weichteile!}
{1191}{}{Aaaaaaaaaah!}
{1192}{}{Ich... kann... nicht... atmen...}
{1193}{}{Uff! Genau in die Kronjuwelen!}
{1194}{}{Der Schmerz, der Schmerz...}
{1195}{}{Verdammt, das tut weh!}
#
############################################
# 1200 Tough Person
############################################
#
# target hit in head
#
{1200}{}{Au! Du Sohn einer ...}
{1201}{}{Du hast mir die Nase gebrochen!}
{1202}{}{Ich reiß dir den Kopf ab!}
#
# target hit in left arm
#
{1210}{}{Au, mein Arm}
{1211}{}{Du hast gerade den größten Fehler deines Lebens gemacht}
{1212}{}{Mein Arm!}
#
# target hit in right arm
#
{1220}{}{Au, mein Arm}
{1221}{}{Du hast gerade den größten Fehler deines Lebens gemacht}
{1222}{}{Mein Arm!}
#
# target hit in torso
#
{1230}{}{Würg!}
{1231}{}{Uff!}
{1232}{}{Autsch!}
{1233}{}{}
{1234}{}{Ugh! Das hat wehgetan!}
{1235}{}{Autsch!}
{1236}{}{Argh!}
{1237}{}{Oh, ich glaube, du hast mir eine Rippe gebrochen!}
{1238}{}{Au!!! Meine Milz!}
{1239}{}{Uff!}
#
# target hit in right leg
#
{1260}{}{Au, mein Bein}
{1261}{}{Ich muss nicht stehen, um dich umzubringen!}
{1262}{}{Mein Knie!}
#
# target hit in left leg
#
{1270}{}{Au, mein Bein}
{1271}{}{Ich muss nicht stehen, um dich umzubringen!}
{1272}{}{Mein Knie!}
#
# target hit in eyes
#
{1280}{}{Ich kann nichts sehen!}
{1281}{}{Dieser Kampf wird von Sekunde zu Sekunde schlimmer}
{1282}{}{Das war ein richtig fieser Tiefschlag!}
#
# target hit in groin
#
{1290}{}{Aua, meine Weichteile!}
{1291}{}{Das werde ich morgen noch spüren}
{1292}{}{}
{1293}{}{Würg!}
{1294}{}{}
{1295}{}{}
#
############################################
# 1300 Berserk Person
############################################
#
# target hit in head
#
{1300}{}{Das wird eine coole Narbe!}
{1301}{}{Langsam gehst du mir auf die Nerven}
{1302}{}{Mach das noch mal, Schwein}
#
# target hit in left arm
#
{1310}{}{Du hast mich erwischt!}
{1311}{}{}
{1312}{}{Du hast mir den Arm gebrochen, aber ich brech dir den Hals}
#
# target hit in right arm
#
{1320}{}{}
{1321}{}{Ist nur ein Kratzer ...}
{1322}{}{Du hast mir den Arm gebrochen, also brech ich dir den Hals}
#
# target hit in torso
#
{1330}{}{Ein bisschen Blut hat noch niemandem geschadet}
{1331}{}{Uff! Dafür mach ich dich fertig ...}
{1332}{}{Au!}
{1333}{}{Ich mag den Schmerz!}
{1334}{}{Ich liebe das Geräusch knackender Rippen!}
{1335}{}{Das ist doch nichts!}
{1336}{}{Arg!}
#
# target hit in right leg
#
{1360}{}{Ich liebe das Geräusch knackender Knochen}
{1361}{}{}
{1362}{}{Du hast mir das Bein gebrochen, aber ich brech dir den Hals}
#
# target hit in left leg
#
{1370}{}{Ich liebe das Geräusch knackender Knochen}
{1371}{}{}
{1372}{}{Du hast mir das Bein gebrochen, aber ich brech dir den Hals}
#
# target hit in eyes
#
{1380}{}{Hey, ich bin blind}
{1381}{}{Ich kann nichts sehen. So ist es wenigstens fair}
{1382}{}{Meine Augen, Schlampe!}
#
# target hit in groin
#
{1390}{}{Uff, meine Weichteile!}
{1391}{}{Das war ein mutiger Zug}
{1392}{}{}
{1393}{}{}
{1394}{}{Also so willst du spielen}
{1395}{}{Ach!}
#
############################################
# 1400 Robot 
############################################
#
# target hit in CPU
#
{1400}{}{Warnung, CPU-Fehlfunktion registriert!}
{1401}{}{Warnung! CPU beschädigt! Verarbeitung beeinträchtigt!}
{1402}{}{Warnung! CPU beschädigt! Kritisches System wird umgeleitet!}
#
# target hit in left manipulator
#
{1410}{}{Schaden am Manipulator registriert}
{1411}{}{Einheit am linken Manipulator getroffen. Schadensbewertung}
{1412}{}{Treffer am Manipulator registriert. Kompensation wird versucht}
#
# target hit in right manipulator
#
{1420}{}{Schaden am Manipulator registriert}
{1421}{}{Einheit am rechten Manipulator getroffen. Schadensbewertung}
{1422}{}{Treffer am Manipulator registriert. Kompensation wird versucht}
#
# target hit in frame
#
{1430}{}{Rahmen getroffen. Schaden wird ausgeglichen}
{1431}{}{Rahmen getroffen. Interne Reparaturen eingeleitet}
{1432}{}{Hauptstruktur wird angegriffen}
{1433}{}{Panzerung durchschlagen}
{1434}{}{Hauptstruktur wird angegriffen. Korrektur läuft}
{1435}{}{Diese Einheit wird angegriffen}
{1436}{}{Kampfmanöver wird versucht}
{1437}{}{Brzzzt!}
{1438}{}{Leichter Schaden}
{1439}{}{Brzzzt!}
#
# target hit in right motivator
#
{1460}{}{Schaden am Antrieb registriert}
{1462}{}{Einheit am rechten Antrieb getroffen. Schadensbewertung}
{1463}{}{Treffer am Antrieb registriert. Kompensation wird versucht}
#
# target hit in left motivator
#
{1470}{}{Schaden am Antrieb registriert}
{1471}{}{Einheit am linken Antrieb getroffen. Schadensbewertung}
{1472}{}{Treffer am Antrieb registriert. Kompensation wird versucht}
#
# target hit in sensors
#
{1480}{}{Sensor getroffen! Sensor getroffen!}
{1481}{}{Sensoren beeinträchtigt! Sensoren beeinträchtigt!}
{1482}{}{Fehlfunktion im Sensorsystem, Umgehung wird versucht}
#
# target hit in regulator
#
{1490}{}{Regler-Fehlfunktion registriert!}
{1491}{}{Regler beschädigt! Regelung beeinträchtigt!}
{1492}{}{Regler beschädigt! Kritisches System wird umgeleitet!}
#
#
############################################
# 1500 Primitive
############################################
#
# target hit in head
#
{1500}{}{Mein Kopf ist voller böser Geister.} 
{1501}{}{Ich kann meine Ahnen rufen hören.} 
{1502}{}{Das wird schön vernarben.}
{1503}{}{Auuuutsch!}
{1504}{}{Mein Kopf steht in Flammen!}
{1505}{}{Es brennt, es brennt!}
{1506}{}{Der Schmerz.}
{1507}{}{Deine Magie ist mächtig.}
{1508}{}{Du kannst mir nicht auf diese Weise die Seele rauben.} 
{1509}{}{Deine Magie kann mich nicht töten.}
#
# target hit in left arm
#
{1510}{}{Ich werde dich mit meinem rechten Arm töten.} 
{1511}{}{Ich brauche nur eine Hand, um dich zu töten.} 
{1512}{}{Dein Schmerz wird noch größer sein!} 
{1513}{}{So viele Finger brauche ich sowieso nicht.} 
{1514}{}{Der Arm war ohnehin ein wenig zu lang.} 
{1515}{}{Dafür nehme ich dir beide Arme.} 
{1516}{}{Dafür töte ich dich langsam.} 
{1517}{}{Autsch!}
{1518}{}{So viel Blut.}
{1519}{}{Etwas, womit ich den Jungen imponieren kann.}
#
# target hit in right arm
#
{1520}{}{Ich werde dich mit meiner linken Hand töten.} 
{1521}{}{Ist dein Ziel wirklich so schlecht?}
{1522}{}{Ich brauche nur eine Hand, um dich zu töten.} 
{1523}{}{So viele Finger brauche ich sowieso nicht.} 
{1524}{}{Dafür töte ich dich langsam.}
{1525}{}{Dafür nehme ich dir beide Arme.} 
{1526}{}{Du nimmst mir den Arm, ich nehme dir den Kopf!}
{1527}{}{Willst du mich verkrüppeln?}
{1528}{}{Dafür werde ich mich an deinen Eingeweiden laben.} 
{1529}{}{Du wirst lange sterben.}
#
# target hit in torso
#
{1530}{}{Awwwwwg!}
{1531}{}{Meine Eingeweide brennen!}
{1532}{}{Meine Gedärme stehen in Flammen!}
{1533}{}{Meine Lebensgeister verlassen mich.} 
{1534}{}{Ich bin aufgeschlitzt worden!}
{1535}{}{Hoffentlich lebe ich noch lange genug, um dich zu erledigen.} 
{1536}{}{Ahnen, ich komme.}
{1537}{}{Ich werde das Dorf nie wiedersehen.} 
{1538}{}{Wenigstens sterbe ich ehrenhaft.} 
{1539}{}{Meine Brüder werden mich rächen.} 
{1540}{}{Ich habe keinen Atem mehr in mir.} 
{1541}{}{Du hast mir die Seele geraubt.}
{1542}{}{Du willst mich verstümmeln?}
{1543}{}{Ich bin aufgeschlitzt wie ein brahmin.} 
{1544}{}{Mir geht es nicht gut.}
{1545}{}{Ich kann meine Beine nicht spüren.}
{1546}{}{Plötzlich wird mir warm und ich werde schläfrig.} 
{1547}{}{Errrggggg!}
{1548}{}{Gack! Hust, hust.}
{1549}{}{Muss weitermachen, muss den Feind erschlagen ...} 
{1550}{}{Die Dunkelheit ruft mich.} 
{1551}{}{Die Stunde meines Todes naht.} 
{1552}{}{Der Schamane hatte recht, ich kehre nicht zurück.} 
{1553}{}{Der Fremde hat mich erschlagen.} 
{1554}{}{Ich bin tot.}
{1555}{}{Meine Eingeweide lösen sich von meiner Wirbelsäule!} 
{1556}{}{Lasst mich im Tod keine Schande bringen.} 
{1557}{}{Verdammte, lästige Eingeweide.} 
{1558}{}{Hey, schaut her, ich kann mein Mittagessen sehen.} 
{1559}{}{Wo ist die ganze Luft hin?}
#
# target hit in right leg
#
{1560}{}{Ich werde zu dir kriechen, um dich zu töten.}
{1561}{}{Muss stehen bleiben, muss ...} 
{1562}{}{Lass mich nicht rennen, um dich einzuholen!}
{1563}{}{Du würdest mich zum Krüppel machen, Feigling!} 
{1564}{}{Awwwwgg!}
{1565}{}{Knochen? So weiß ...}
{1566}{}{Warum kann ich nicht laufen?}
{1567}{}{Arrrrrrgh.}
{1568}{}{Unnhhh.}
{1569}{}{Mein Bein fühlt sich an wie Feuer.}
#
# target hit in left leg
#
{1570}{}{Ich werde zu dir kriechen, um dich zu töten.}
{1571}{}{Muss stehen bleiben, muss ...} 
{1572}{}{Lass mich nicht rennen, um dich einzuholen!} 
{1573}{}{Du würdest mich zum Krüppel machen, Feigling!} 
{1574}{}{Awwwwgg!}
{1575}{}{Knochen? So weiß ...}
{1576}{}{Kann nicht laufen. Oh, diese Schmerzen ...} 
{1577}{}{Dafür werde ich dir den Fuß abfackeln.} 
{1578}{}{Ooooo-auuu!}
{1579}{}{Mein Bein brennt wie Feuer.}
#
# target hit in eyes
#
{1580}{}{Die Dunkelheit ist da.}
{1581}{}{Wo bist du?}
{1582}{}{Hilfe, hilf mir.}
{1583}{}{Ich kann dich noch hören.}
{1584}{}{Willst du mich blenden? Du Feigling!} 
{1585}{}{Mein Augenlicht wurde mir genommen.}
{1586}{}{Du kannst mir die Augen nehmen, aber nicht meinen Mut!} 
{1587}{}{Komm her, damit ich dich töten kann!} 
{1588}{}{Die Dunkelheit, die Dunkelheit, Aaaiiiieee!} 
{1589}{}{Wo ist mein Auge, wo ist es!?!}
#
# target hit in groin
#
{1590}{}{Ich habe schon genug Junge.} 
{1591}{}{Du kämpfst ohne Ehre.}
{1592}{}{Ich bin verheiratet, hab's sowieso nicht benutzt.} 
{1593}{}{Heilige Geister, die Welt ist gerade explodiert.} 
{1594}{}{Keuch ... ich kann nicht atmen ...}
{1595}{}{Mit hoher, quiekender Stimme: Autsch!} 
{1596}{}{Uuunh. Ich muss mich kurz hinsetzen.} 
{1597}{}{Du Bastard – dafür bring ich dich langsam um.} 
{1598}{}{Du weißt nichts von Ehre.}
{1599}{}{Dafür schneide ich dich in Stücke wie ein Tier.}
#
#
############################################
# 1600 Ghoul
############################################ 
#
# target hit in head
#
{1600}{}{Oh, mein hübsches Gesicht!}
{1601}{}{Mein Hirn tut weh.}
{1602}{}{Jetzt seh ich aus wie Van Gogh.}
{1603}{}{Verdammt, da ist meine Nase hin.}
{1604}{}{Hey, das war mein letzter Zahn.} 
{1605}{}{Man hat mich skalpiert!}
{1606}{}{Ich hätte lieber eine Flasche vor mir ...} 
{1607}{}{Lass mich dir mal die Meinung geigen.} 
{1608}{}{Das war mein einziges gutes Auge, Arrr.} 
{1609}{}{Da kommt mir eine Träne in mein einziges gutes Auge.}
#
# target hit in left arm
#
{1610}{}{Du hast mich entwaffnet!}
{1611}{}{Oooh, der Schmerz, der Schmerz.}
{1612}{}{Ein paar Finger hab ich noch übrig.} 
{1613}{}{Für *dich*, Kumpel, brauch ich nur einen Finger.} 
{1614}{}{Na gut, dann helf ich dir wohl auf die Sprünge.} 
{1615}{}{Das ist schlimmer als ein eingerissener Nagel.} 
{1616}{}{Das macht meinen Rückschwung ganz schön zunichte.} 
{1617}{}{Ich stech dich mit meinem Stumpf ab!} 
{1618}{}{Hey, wo sind meine Finger hin?} 
{1619}{}{Das passt perfekt zu meinem Käpt'n-Hook-Look.} 
#
# target hit in right arm
#
{1620}{}{Ich hätte den rechten Schutz nehmen sollen.} 
{1621}{}{Du hast mir den Arm gebrochen!}
{1622}{}{Das wirst du bereuen!}
{1623}{}{Ich werd hier umgebracht, Mann.}
{1624}{}{Das war's mit Wimbledon.}
{1625}{}{Sieg ... ach, vergiss es.}
{1626}{}{Du hast mich entwaffnet!}
{1627}{}{Für *dich*, Kumpel, brauch ich nur einen Finger.} 
{1628}{}{Dann tret ich dich eben zu Tode.} 
{1629}{}{Da ist mein silberner Paillettenhandschuh hin!} 
#
# target hit in torso
#
{1630}{}{Das ist *meine* Leber, gib sie zurück!} 
{1631}{}{Nur noch ein kleines Stück nach rechts, ahhh, so ist's besser.} 
{1632}{}{Gerrk!}
# [disabled because of duplicates]
#{1633}{}{What's that musty smell? Oh, it's my innards.} 
#{1634}{}{Now that you've eviscerated me, I'm sooo svelte! Thanks!} 
#{1635}{}{./~ I left my heart.../~}
#{1636}{}{That tickled my ribs.}
{1633}{}{Wer braucht schon einen Blinddarm.} 
{1634}{}{Nur ein bisschen an den Rändern, Doktor.} 
{1635}{}{Arrggghh, meine Wirbelsäule!}
{1636}{}{Meine Beine, ich kann meine Beine nicht spüren.} 
{1637}{}{Eine Bauchwunde, Sarge.}
{1638}{}{Lungen sind was für Weicheier.}
{1639}{}{Hey, ich hab Rippen!}
#
# target hit in right leg
#
{1660}{}{Au, mein Bein}
{1661}{}{Dafür wirst du bezahlen!}
{1662}{}{Argh! Du brichst mir das Bein, ich brech dir den Hals!} 
{1663}{}{Verdammt, da ist mein Tango hin.}
{1664}{}{Verdammt, meine Zehen sind hin.}
{1665}{}{Ich schätze, ich brauche eine Stütze.}
{1666}{}{Du hast meine blauen Wildlederschuhe verkratzt!} 
{1667}{}{Du hast meine Flügelspitzen-Schuhe verbeult!}
{1668}{}{Und ich hab sie gerade erst geputzt.} 
{1669}{}{Ich beiß dir die Kniescheiben ab!} 
#
# target hit in left leg
#
{1670}{}{Mein Bein!}
{1671}{}{Du hast meine Gucci-Schuhe zerfetzt!}
{1672}{}{Autsch! Hey! Das ist unter der Gürtellinie!} 
{1673}{}{Du kannst einem blaue Flecken verpassen wie kein anderer.} 
{1674}{}{Versohl mir den Hintern, Mama, ich war unartig.} 
{1675}{}{Das wird schön verkrusten.}
{1676}{}{Ist das alles mein Blut?}
{1677}{}{Marshall Dillon, Marshall Dillon!} 
{1678}{}{Das gibt eine Brandblase.}
{1679}{}{Kai, yai, yippee, ai, ay!}
#
# target hit in eyes
#
{1680}{}{Verdammt, Blut in meinen Augen!}
{1681}{}{Mein Auge! Dafür wirst du bezahlen!} 
{1682}{}{Mistkerl!}
{1683}{}{Wer hat das Licht ausgemacht?} 
{1684}{}{Hah, das war mein Glasauge!} 
{1685}{}{Matscht wie eine reife Traube, was?}
{1686}{}{Ich hab dich im Auge, äh, könntest du es mir bitte zurückgeben?} 
{1687}{}{Ich kann dich immer noch allein am Geräusch erkennen!}
{1688}{}{Aiyeee! Aiyeee! Mein Auge!}
{1689}{}{Du blendest mich, weil du Angst hast, stimmt's?} 
#
# target hit in groin
#
{1690}{}{Wie ritterlich von dir.}
{1691}{}{Auaaaah!} 
{1692}{}{Uuuhhh!}
{1693}{}{Ich glaube, ich muss mich kurz hinsetzen.}
{1694}{}{Mann, wenn es weibliche Ghule gäbe, wäre ich jetzt sauer auf dich.} 
{1695}{}{Autsch, das tat weh.}
{1696}{}{War das...? Oh ja, das tut weh.} 
{1697}{}{Hey, seht mal! Prärieaustern.} 
{1698}{}{Gehackte Nüsse gefällig?}
{1699}{}{Nie wieder schreibe ich meinen Namen in den Schnee.}
#
############################################
# 1700 Raider (Khan)
############################################
#
# target hit in head
#
{1700}{}{Nicht den verdammten Kopf, du ...}
{1701}{}{Mein ... Kopf ... mir ... wird schwindelig ...}
{1702}{}{Ugnnn!}
{1703}{}{Nicht ins Gesicht! Nicht ins Gesicht!}
#
# target hit in left arm
#
{1710}{}{Ich kann dich auch mit einem Arm besiegen!}
{1711}{}{Sanitäter! Mein Arm ist im Arsch!}
{1712}{}{Autsch! Gut, dass ich beidhändig ... wie auch immer.}
#
# target hit in right arm
#
{1720}{}{Du hast mir den Arm gebrochen! Jetzt ist der Kampf fair!}
{1721}{}{Sanitäter! Mein Arm ist im Arsch!}
{1722}{}{Du musst mir mehr als den Arm brechen, um deinen Arsch zu retten!}
#
# target hit in torso
#
{1730}{}{Ahhg! Treffer in den Bauch!}
{1731}{}{Hnrgggg! Kann ... nicht ... atmen ...}
{1732}{}{Meine Rippen tun weh. Bald nehme ich mir deine vor! Nur fair!}
{1733}{}{Dafür ... wirst ... du ... bezahlen ...!}
{1734}{}{*Uff* Gott, ich hasse das ...}
{1735}{}{Nggg! Solarplexus!}
#
# target hit in right leg
#
{1760}{}{Verdammt! Mein Bein!}
{1761}{}{Ich brauche keine zwei Beine, um dir den Arsch zu versohlen.}
{1762}{}{Für mein Bein brauche ich wohl einen stimpak ...}
{1763}{}{Urggg ... mein ... Bein ist ... hinüber ...}
#
# target hit in left leg
#
{1770}{}{Verdammt! Mein Bein!}
{1771}{}{*Ächz* Davon werde ich wohl hinken ...}
{1772}{}{Für mein Bein brauche ich wohl einen stimpak ...}
{1773}{}{Urggg ... mein ... Bein ist ... hinüber ...}
#
# target hit in eyes
#
{1780}{}{Scheiße! Nicht in die Augen!}
{1781}{}{Willst du also meine räumliche Wahrnehmung beeinträchtigen, was?}
{1782}{}{Kann ... nicht ... sehen ... Blut ... in den Augen ...}
{1783}{}{Ich muss dich nicht sehen, ich kann dich immer noch riechen!}
#
# target hit in groin
#
{1790}{}{Was glaubst du denn, was das hier ist? So ein billiger Actionfilm?}
{1791}{}{Meine Eier!!! Komm her und lass mich dir das antun!}
{1792}{}{Tja, da sind meine Messingkugeln wohl hin.}
{1793}{}{Entschuldige mich kurz, während ich mich übergebe.}
{1794}{}{Na toll. Ich darf gegen jemanden mit einem Eierfetisch kämpfen.}
{1795}{}{Lass mich kurz hinlegen, dann komme ich und töte dich.}
{1796}{}{Mist! Na ja, dann kriege ich eben keine Kinder.}
#
############################################
# 1800 Junkie
############################################
#
# target hit in head
#
{1800}{}{Whoa. Irgendwas hat mich gerade im Gesicht getroffen.}
{1801}{}{Was hat mich gerade am Kopf getroffen?}
{1802}{}{Ngggg}
{1803}{}{Gut, dass ich auf Jet bin, sonst hätte das wehgetan.}
{1804}{}{Auaaaa! Holt mir jemand einen stimpak! Oder etwas Jet!}
#
# target hit in left arm
#
{1810}{}{Hey! Jemand hat gerade meinen Arm getroffen!}
{1811}{}{Hör zu, mein Arm ist nur für Nadeln da. Hör auf, ihn anzugreifen.}
{1812}{}{Nggggg}
{1813}{}{Auaaaa! Holt mir jemand einen stimpak! Oder etwas Jet!}
#
# target hit in right arm
#
{1820}{}{Hey! Jemand hat gerade meinen Arm getroffen!}
{1821}{}{Hör zu, mein Arm ist nur für Nadeln da. Hör auf, ihn anzugreifen.}
{1822}{}{Nggggg}
{1823}{}{Auaaaa! Holt mir jemand einen stimpak! Oder etwas Jet!}
#
# target hit in torso
#
{1830}{}{Meine Milz!}
{1831}{}{Au! Auaaaa, meine blöde Brust! Au!}
{1832}{}{Hey! Warum hast du mir gegen die Brust geschlagen, Arschloch?!}
{1833}{}{Hör auf, mir gegen die Brust zu schlagen!}
{1834}{}{Whoa. Meine Brust. Du hast sie getroffen. Cool.}
{1835}{}{Nrgggg}
{1836}{}{*hfff*}
{1837}{}{Auaaaa! Holt mir jemand einen stimpak! Oder etwas Jet!}
#
# target hit in right leg
#
{1860}{}{Hey! Jemand hat gerade mein Bein getroffen!}
{1861}{}{Hey! Mit dem Bein laufe ich!}
{1862}{}{Auaaaa! Holt mir jemand einen stimpak! Oder etwas Jet!}
#
# target hit in left leg
#
{1870}{}{Hey! Jemand hat gerade mein Bein getroffen!}
{1871}{}{Hey! Mit dem Bein laufe ich!}
{1872}{}{Auaaaa! Holt mir jemand einen stimpak! Oder etwas Jet!}
#
# target hit in eyes
#
{1880}{}{Das...fühlte sich...NICHT an wie eine Nadel im Auge...}
{1881}{}{Hey! Mit dem Auge sehe ich!}
{1882}{}{Meine Augen! Meine Augen! Meine Augen tun weh!}
#
# target hit in groin
#
{1890}{}{Ich bin so auf Jet, dass ich das kaum gespürt habe. Oh...nein, warte.}
{1891}{}{*Hurhkkkk*}
{1892}{}{Tritt mir in die Eier, ja?!}
{1893}{}{Nghhhhh!}
{1894}{}{Nicht in die Eier! Nicht in die Eier!}
{1895}{}{Meine Genitalien! Meine armen Genitalien!}
{1896}{}{Entschuldige mich, während ich mich überall übergebe.}
{1897}{}{Das...tat...SEHR...weh.}
{1898}{}{Hoffentlich ist meine Leiste gerade ins Genitalparadies eingegangen.}
#
####################################################################################
#
#                    Generic People
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed.
#
#                     2000 Wimpy Person
#                     2100 Normal Person
#                     2200 Tough Person
#                     2300 Berserk Person
#                     2400 Guard (Normal)
#                     2500 Guard (Tough)
#                     2600 Primitive
#                     2700 Soldier
#                     2800 Leader
#                     2900 Raider (Khan)
#                     3000 Robot
#                     3100 Ghoul
#                     3200 Junkie
#
####################################################################################
#
#
############################################
# 2000 Wimpy Person
############################################
#
#  running away
#
{2000}{}{Gnade!}
{2001}{}{Hilfe!}
{2002}{}{Bitte hör auf!}
{2003}{}{Hilfe!}
{2004}{}{Aaaaahhhh!}
{2005}{}{Gnade!}
#
# moving in to attack
#
{2020}{}{Hmm, äh, hör auf!}
{2021}{}{Deinesgleichen kann ich nicht leiden ...}
{2022}{}{Ich hatte wirklich gehofft, dass es nicht so weit kommt ...}
{2023}{}{Ich schätze, ich muss mich verteidigen}
{2024}{}{Ich schätze, ich muss mich verteidigen}
{2025}{}{Ich hatte wirklich gehofft, dass es nicht so weit kommt ...}
#
# attacking
#
{2040}{}{Nimm das!}
{2041}{}{Du hättest damit nicht anfangen sollen!}
{2042}{}{Du hast darum gebeten!}
{2043}{}{Na, wie gefällt dir das?}
{2044}{}{}
{2045}{}{Du Ungeheuer!}
{2046}{}{Ich will das nicht tun!}
{2047}{}{}
{2048}{}{Ich wollte diesen Kampf nicht, aber ...}
{2049}{}{Du Schuft!}
#
# target being missed
#
{2060}{}{}
{2061}{}{Daneben!}
{2062}{}{Wow, das hätte wehtun können!}
{2063}{}{Puh! Ich lebe noch!}
{2064}{}{Hey! Das hätte wehtun können!}
{2065}{}{Puh! Ich lebe noch!}
#
############################################
# 2100 Normal Person
############################################
#
#  running away
#
{2100}{}{Greif bitte jemand anderen an!}
{2101}{}{Hab Erbarmen!}
{2102}{}{Hilfe!}
{2103}{}{Bitte hör auf!}
{2104}{}{}
{2105}{}{Dafür sterbe ich nicht!}
#
# moving in to attack
#
{2120}{}{Warte nur, bis ich dich erwische ...}
{2121}{}{}
{2122}{}{Hey, du!}
{2123}{}{Du bist hier nicht willkommen}
{2124}{}{Niemand übernimmt diesen Ort ...}
{2125}{}{Wer glaubst du eigentlich, wer du bist?}
#
# attacking
#
{2140}{}{Das hättest du nicht tun sollen}
{2141}{}{Wir kümmern uns um unsere Leute}
{2142}{}{So machen wir es mit Ungeziefer!}
{2143}{}{Du mutierter Freak!}
{2144}{}{Du Bastard!}
{2145}{}{Wir verfüttern dich an die Hunde}
{2146}{}{Das wird dir eine Lehre sein!}
{2147}{}{Na schön. Du hast darum gebeten.}
{2148}{}{Du Tier!}
{2149}{}{Du verdienst, was dir bevorsteht!}
#
# target being missed
#
{2160}{}{So übel bin ich doch gar nicht, oder?}
{2161}{}{Ich habe schon klügere Brahmin als dich gesehen}
{2162}{}{Puh!}
{2163}{}{Ich bin kein Leichtgewicht}
{2164}{}{Den Göttern sei Dank}
{2165}{}{Daneben!}
#
############################################
# 2200 Tough Person
############################################
#
#  running away
#
{2200}{}{Das ist es nicht wert!}
{2201}{}{Ich habe Besseres zu tun}
{2202}{}{Hilfe!}
{2203}{}{Diesmal hast du mich erwischt ...}
{2204}{}{Du wirst schon kriegen, was du verdienst!}
{2205}{}{Dafür sterbe ich nicht!}
#
# moving in to attack
#
{2220}{}{Es ist zu spät zum Wegrennen}
{2221}{}{Wer hat dich hier reingelassen?}
{2222}{}{Hey, du!}
{2223}{}{Deinesgleichen wollen wir hier nicht!}
{2224}{}{Niemand übernimmt diesen Ort ...}
{2225}{}{Wer glaubst du eigentlich, wer du bist?}
#
# attacking
#
{2240}{}{Nimm das!}
{2241}{}{Na, wie gefällt dir das?}
{2242}{}{So machen wir es mit Ungeziefer!}
{2243}{}{Das ist für dich!}
{2244}{}{Leb wohl!}
{2245}{}{Na, dann mal los!}
{2246}{}{Verdammter Unruhestifter!}
{2247}{}{Ich prügle dich windelweich}
{2248}{}{Du Tier!}
{2249}{}{Du wirst es bereuen, hierhergekommen zu sein!}
#
# target being missed
#
{2260}{}{Du bist nicht so gut, wie du glaubst}
{2261}{}{Erbärmlich}
{2262}{}{Du bist doch nur ein gewöhnlicher Schläger}
{2263}{}{Du bist wirklich nichts Besonderes}
{2264}{}{Ich lasse mich nicht von dir zum Opfer machen}
{2265}{}{Das war dein letzter Fehler}
#
############################################
# 2300 Berserk Person
############################################
#
#  running away
#
{2300}{}{Ich mach mich aus dem Staub}
{2301}{}{Ich komme wieder!}
{2302}{}{Bis später, du Penner!}
{2303}{}{Das hat Spaß gemacht, aber ich bin weg!}
{2304}{}{Dafür wirst du noch bezahlen – später!}
{2305}{}{Das sollten wir bald wiederholen!}
#
# moving in to attack
#
{2320}{}{Ich mach dich fertig!}
{2321}{}{Frischfleisch!}
{2322}{}{Du hast mir gerade den Tag versüßt!}
{2323}{}{Du wirst mein Spielzeug sein!}
{2324}{}{Ich mach dich fertig!}
{2325}{}{Ich mach dich fertig!}
#
# attacking
#
{2340}{}{Ich krieg dich!}
{2341}{}{Zeit zum Spielen!}
{2342}{}{Bitte fleh nicht. Der Tod sollte würdevoll sein.}
{2343}{}{Hoffentlich stirbst du nicht zu schnell.}
{2344}{}{Noch letzte Worte?}
{2345}{}{Nimm das!}
{2346}{}{Stirb! Stirb! Stirb! Stirb! Stirb!}
{2347}{}{Stirb!}
{2348}{}{Machen wir dich mal ein bisschen auf ...}
{2349}{}{Du endest als Hundefutter, Freundchen.}
#
# target being missed
#
{2360}{}{Du hast mich nicht mal gestreift.}
{2361}{}{Du langweilst mich zu Tode.}
{2362}{}{Na los, Hosenscheißer. Wehr dich!}
{2363}{}{Ist das alles, was du draufhast?}
{2364}{}{Du bist echt mies!}
{2365}{}{Das wird leichter als gedacht.}
#
############################################
# 2400 Guard (Normal)
############################################
#
#  running away
#
{2400}{}{Ich bin weg!}
{2401}{}{Vielleicht war das keine gute Idee.}
{2402}{}{Greif jemand anderen an, okay!}
{2403}{}{Hoppla!}
{2404}{}{Dafür sterbe ich nicht!}
{2405}{}{Das ist mir zu viel.}
#
# moving in to attack
#
{2420}{}{Hey, du!}
{2421}{}{Ich werd dir Manieren beibringen.}
{2422}{}{Deinesgleichen wollen wir hier nicht!}
{2423}{}{Du musst noch lernen, Respekt zu zeigen!}
{2424}{}{Zeit, mein Geld zu verdienen ...}
{2425}{}{Warte nur, bis ich dich erwische ...}
{2426}{}{Warum musstest du das auch tun?}
{2427}{}{Es gibt immer Idioten wie dich, die einem die Schicht vermiesen.}
#
# attacking
#
{2440}{}{Nimm das!}
{2441}{}{Fühlt sich gut an, was?}
{2442}{}{Hättest es besser in Ruhe gelassen.}
{2443}{}{Na, wie gefällt dir das?}
{2444}{}{Wo ist deine Mami jetzt?}
{2445}{}{Nimm alles!}
{2446}{}{Mal sehen, wie zäh du bist ...}
{2447}{}{Hosenscheißer.}
{2448}{}{Skag!}
{2449}{}{Ich mache dich endgültig unschädlich.}
#
# target being missed
#
{2460}{}{Hat deine Mami dir diesen Trick beigebracht?}
{2461}{}{Du bist einfach nur mies!}
{2462}{}{Du bist nicht gut genug.}
{2463}{}{Das war dein letzter Fehler}
{2464}{}{Amateur.}
{2465}{}{Hast du in Bars kämpfen gelernt?}
#
############################################
# 2500 Guard (Tough)
############################################
#
#  running away
#
{2500}{}{Ich muss hier weg!}
{2501}{}{Ich komme wieder ...}
{2502}{}{Heute bringst du mich nicht um!}
{2503}{}{Bis später, du Penner!}
{2504}{}{Du bist mich noch nicht los!}
{2505}{}{Dafür wirst du noch bezahlen – später!}
#
# moving in to attack
#
{2520}{}{Du bist erledigt!}
{2521}{}{Frischfleisch ...}
{2522}{}{Ich werde auf deinem Grab tanzen.}
{2523}{}{Alle herhören! Zielübung!}
{2524}{}{Bist du bereit, Schlampe?}
{2525}{}{Das wird mir Spaß machen ...}
#
# attacking
#
{2540}{}{Nimm alles!!!}
{2541}{}{Spar dir das Flehen um Gnade ...}
{2542}{}{Jetzt kommt der beste Teil ...}
{2543}{}{Willst du noch mehr davon!!! Hm?!}
{2544}{}{Wir verfüttern dich an die Hunde}
{2545}{}{Man sollte nichts anfangen, was man nicht zu Ende bringen kann.}
{2546}{}{Hoffentlich stirbst du nicht zu schnell.}
{2547}{}{Nur einer von uns wird hier lebend rauskommen.}
{2548}{}{Stirb!}
{2549}{}{Ich fresse Typen wie dich zum Frühstück.}
{2550}{}{Ich verfüttere dich an meinen Leguan.}
{2551}{}{Das Letzte, was du sehen wirst, ist mein grinsendes Gesicht.}
{2552}{}{Das ist mein Lieblingsjob.}
#
# target being missed
#
{2560}{}{Du bist ein Witz.}
{2561}{}{Ist das alles, was du draufhast?}
{2562}{}{Du machst es mir leicht.}
{2563}{}{Einfach erbärmlich ...}
{2564}{}{Zu langsam!}
{2565}{}{Verlierer}
#
############################################
# 2600 Primitive
############################################
#
#  running away
#
{2600}{}{Flieh vor dem Bösen!}
{2601}{}{Die Geister gebieten mir, mich selbst zu retten.}
{2602}{}{Unser Feind hat mächtige Magie eingesetzt – lauft! Holt jemand den Schamanen!}
{2603}{}{Der böse Geist ist stark in diesem hier. Der Tod wandelt auf Erden!}
{2604}{}{Der Dunkle ist hier!}
{2605}{}{Der Dunkle will uns bestrafen. Lauft! Meine Seele flieht, und ich muss ihr folgen!}
{2606}{}{Aiiieeeee!!}
#
# moving in to attack
#
{2620}{}{Ahne, lenke meinen Waffenarm!}
{2621}{}{Deine Stärke wird mein sein.}
{2622}{}{Groß wird mein Ruhm sein.}
{2623}{}{Ich werde deinen Stamm entehren.}
{2624}{}{Ayah! Nabataluk!}
{2625}{}{Geister, steht mir bei!}
{2626}{}{Komm, lass unsere Klingen tanzen.}
{2627}{}{Möge es beginnen!}
{2628}{}{U-Suthoooo!}
{2629}{}{Die Geister sind mit mir!}
#
# attacking
#
{2640}{}{Deine Ahnen haben dich verlassen.}
{2641}{}{Deine Niederlage wird mir große Ehre einbringen. Meine Magie kennt keine Niederlage!}
{2642}{}{Gib jetzt auf, dann werden wir dein Herz nicht essen.}
{2643}{}{Du kämpfst tapfer – ich werde deinen Mut essen. Die Schamanen werden von meinem Sieg singen.}
{2644}{}{Ich werde in deinem Blut baden!}
{2645}{}{Ich fürchte dich nicht!}
{2646}{}{Ich bringe dir Frieden, Verlorener.}
{2647}{}{Ruhm im Kampf sichert ewiges Leben! Ich ehre dich, Fremder.}
{2648}{}{Die Nebel rufen dich.}
{2649}{}{Unsere Ahnen dürsten nach deiner Seele.}
{2650}{}{Meine Klinge wird durstig.}
{2651}{}{Lass uns aus dem Kelch des Kampfes trinken!}
#
# target being missed
#
{2660}{}{Deine Augen sind von Hass getrübt.}
{2661}{}{Deine Geister haben dich verlassen.}
{2662}{}{Unsere Magie wirkt!}
{2663}{}{Meine Magie macht mich unbesiegbar!}
{2664}{}{Deine Lebenskraft schwindet!}
{2665}{}{Angst ist der Geisteskiller.}
{2666}{}{Mein Kriegsgesang wirkt!}
{2667}{}{Unsere Kinder verstehen mehr vom Kampf!}
{2668}{}{Du hast zu lange in Frieden gelebt.}
{2669}{}{Sind alle aus deinem Stamm so schwach?}
#
############################################
# 2700 Soldier
############################################
#
#  running away
#
{2700}{}{Verstärkung!}
{2701}{}{Sie können mich vor ein Kriegsgericht stellen ...}
{2702}{}{Sanitäter!}
{2703}{}{Rückzug! Rückzug!}
{2704}{}{Zurück! Zurück!}
{2705}{}{Vielleicht hast du die Schlacht gewonnen ...}
#
# moving in to attack
#
{2720}{}{Na, dann mal los!}
{2721}{}{Hoo-Yah!}
{2722}{}{Ich werd dir Manieren beibringen.}
{2723}{}{Du bist erledigt!}
{2724}{}{Angriff!}
{2725}{}{Begraben wir diesen Verlierer!}
{2726}{}{Laden und sichern!}
{2727}{}{Wir lassen Gott richten, was von dir übrig ist.}
#
# attacking
#
{2740}{}{Nimm das!}
{2741}{}{Jetzt hab ich dich!}
{2742}{}{Jetzt stirbst du!}
{2743}{}{Na, wie gefällt dir das?}
{2744}{}{Das ist für uns nicht bloß ein Job.}
{2745}{}{Man sollte nichts anfangen, was man nicht zu Ende bringen kann.}
{2746}{}{Du solltest besser zu den Göttern beten!}
{2747}{}{Du schaffst es nicht mal bis sechs Uhr morgens.}
{2748}{}{Fühlt sich gut an?}
{2749}{}{Wir sehen uns in der Hölle.}
#
# target being missed
#
{2760}{}{Trainier mal ein bisschen.}
{2761}{}{Ist das alles, was du draufhast?}
{2762}{}{Na los, Verlierer. Kämpf gefälligst!}
{2763}{}{Versuch's nächstes Mal mit Zielen.}
{2764}{}{Zivilist ...}
{2765}{}{Überlass das nächstes Mal den Profis.}
#
############################################
# 2800 Leader
############################################
#
#  running away
#
{2800}{}{}
{2801}{}{}
{2802}{}{}
{2803}{}{}
{2804}{}{}
{2805}{}{}
#
# moving in to attack
#
{2820}{}{}
{2821}{}{}
{2822}{}{}
{2823}{}{}
{2824}{}{}
{2825}{}{}
{2826}{}{}
{2828}{}{}
#
# attacking
#
{2840}{}{}
{2841}{}{}
{2842}{}{}
{2843}{}{}
{2844}{}{}
{2845}{}{}
{2846}{}{}
{2847}{}{}
{2848}{}{}
{2849}{}{}
#
# target being missed
#
{2860}{}{}
{2861}{}{}
{2862}{}{}
{2863}{}{}
{2864}{}{}
{2865}{}{}
#
############################################
# 2900 Raider
############################################
#
#  running away
#
{2900}{}{Flieht! Flieht!}
{2901}{}{Rückzug!}
{2902}{}{Neu formieren!}
{2903}{}{Zurückfallen!}
{2904}{}{Rückzug antreten!}
{2905}{}{Aaaaghhh!}
#
# moving in to attack
#
{2920}{}{Macht diesen Trottel fertig!}
{2921}{}{Frischfleisch ...}
{2922}{}{Plündern!}
{2923}{}{Der gehört mir!}
{2924}{}{Ahhhhhhh!}
{2925}{}{Angriff!}
#
# attacking
#
{2940}{}{Genieß die letzten Sekunden deines Lebens.}
{2941}{}{Blut! Blut! Blut!}
{2942}{}{Dein Herz gehört mir!}
{2943}{}{RAAAAAAARRRR!!}
{2944}{}{Eure Waffen werden meine Trophäen sein!}
{2945}{}{Tod!}
{2946}{}{Ich werde dich töten!}
{2947}{}{Deine Knochen werden im Ödland bleichen!}
{2948}{}{Blut und Dunkelheit!}
{2949}{}{YAAAAAAAAAAAAH!}
{2950}{}{Bohre dem verdammten Bastard ein Loch!}
#
# target being missed
#
{2960}{}{Vergebliche Mühe!}
{2961}{}{Du hast versagt!}
{2962}{}{Mein Blut ist stärker als deins!}
{2963}{}{Ich lebe!!}
{2964}{}{Dein Körper ist schwach und erbärmlich!}
#
############################################
# 3000 Robot
############################################
#
#  running away
#
{3000}{}{Rückzug eingeleitet}
{3001}{}{Taktischer Plan: Rückzug}
{3002}{}{Kampfeffektivität minimal. Rückzug empfohlen}
{3003}{}{Taktische Analyse abgeschlossen. Rückzug empfohlen.}
{3004}{}{Fluchtprogramm wird heruntergeladen}
{3005}{}{Rückzugssequenz eingeleitet}
#
# moving in to attack
#
{3020}{}{Ziel erfasst!}
{3021}{}{Vernichten! Vernichten!}
{3022}{}{Der Humanoide darf nicht entkommen}
{3023}{}{Eindringling vernichten}
{3024}{}{Kampfsequenz eingeleitet}
{3025}{}{Kampfprogramm wird hochgeladen}
#
# attacking
#
{3040}{}{Kampfsequenz eingeleitet}
{3041}{}{Ziel wird angegriffen}
{3042}{}{Angriffssequenz wird eingeleitet}
{3043}{}{Der Eindringling muss vernichtet werden!}
{3044}{}{Auswahl taktischer Optionen abgeschlossen}
{3045}{}{Angriff wird ausgeführt}
{3046}{}{Das Ziel wird vernichtet}
{3047}{}{Sequenz zur Eliminierung des Feindes eingeleitet}
{3048}{}{Ziel muss eliminiert werden}
{3049}{}{Auswahl der Offensivmaßnahme abgeschlossen}
#
# target being missed
#
{3060}{}{Analyse. Defensivprogramm erfolgreich}
{3061}{}{Analyse. Angriff des Ziels vernachlässigbar.}
{3062}{}{Angriff des Ziels fehlgeschlagen. Reaktion wird berechnet}
{3063}{}{Einheit blieb durch den Angriff unversehrt}
{3064}{}{Offensivfähigkeiten des Ziels werden neu berechnet}
{3065}{}{Analyse. Ziel traf eine falsche taktische Entscheidung. Einheit unbeschädigt}
#
############################################ 
# 3100 Ghoul
############################################ 
#
#  running away
#
{3100}{}{Nichts wie weg hier!}
{3101}{}{Ich komme wieder ...}
{3102}{}{Heute bringst du mich nicht um!} 
{3103}{}{Bis später, Normalo!}
{3104}{}{Du wirst noch von mir hören!} 
{3105}{}{Dafür wirst du noch bezahlen – später!} 
{3106}{}{Ich sterbe nicht zweimal.}
{3107}{}{Füße, lasst mich jetzt nicht im Stich!}
{3108}{}{Ich führe nur einen taktischen Rückzug durch.} 
{3109}{}{Äh, Zeit für einen taktischen Rückzug.} 
{3110}{}{Abgang links.}
{3111}{}{Es ist später, als ich dachte.} 
{3112}{}{Ich muss los. Bis dann.}
{3113}{}{Lauft um euer Leben!}
{3114}{}{Ich muss ein paar Teile wieder anbringen.} 
{3115}{}{Diese alten Knochen machen das nicht mehr mit.} 
{3116}{}{Es sind nicht die Jahre, sondern die Kilometer.} 
{3117}{}{Was für eine Welt, was für eine Welt ...}
{3118}{}{Na, du hast wohl deine Lektion gelernt. Ich bin dann mal weg!} 
{3119}{}{Hey, hör auf, vor mir zurückzuweichen.}
#
# moving in to attack
#
{3120}{}{Du bist erledigt!}
{3121}{}{Frischfleisch ...}
{3122}{}{Fleisch, Fleisch, Fleisch – Fleischwurst!} 
{3123}{}{Gehirne ...}
{3124}{}{Ich schaufle dir dein Grab ...} 
{3125}{}{Hoffentlich bleibt dein Kopf heil ...} 
{3126}{}{Mehr Gehirne ...}
{3127}{}{Schickt mehr Bullen!}
{3128}{}{Schickt mehr Sanitäter!}
{3129}{}{Ein paar frische Teile wären nicht schlecht.} 
{3130}{}{Steak Tatar, kommt sofort.}
{3131}{}{Kommt und holt es euch!}
{3132}{}{Ist die Suppe schon fertig?}
{3133}{}{Wo bleibt das Fleisch?}
{3134}{}{Mmm, ich liebe Glatthäute einfach.} 
{3135}{}{Du bist durch meinen Schatten gelaufen ... oder so was.} 
{3136}{}{Ich wusste, dass ich die Futterglocke gehört habe.} 
{3137}{}{Rate mal, wer zum Abendessen kommt.} 
{3138}{}{Teile sind Teile.}
{3139}{}{Na, du bist also mein nächster Organspender, was?} 
#
# attacking
#
{3140}{}{Deine Zeit ist gekommen!}
{3141}{}{Spar dir das Flehen um Gnade ...} 
{3142}{}{Das wird mir Spaß machen.}
{3143}{}{Oooo, das muss wehtun!}
{3144}{}{Zeit zum Schnippeln und Würfeln.}
{3145}{}{Ich werde deine Leber fressen!}
{3146}{}{Hoffentlich stirbst du nicht zu schnell.} 
{3147}{}{Essenszeit!}
{3148}{}{Stirb!}
{3149}{}{Ich fresse Kerle wie dich zum Frühstück und Mittagessen.} 
{3150}{}{Wie kann etwas, das so eine Sauerei macht, schlecht sein?} 
{3151}{}{Lass mich mal kosten!}
{3152}{}{Gib Daddy ein Küsschen, Baby!} 
{3153}{}{Ich hab was für dich!}
{3154}{}{Halt still! Dann tut's weniger weh.}
{3155}{}{Hör auf zu zappeln, der Koch ist in der Küche!} 
{3156}{}{Ich liebe es, ihnen beim Zappeln zuzusehen.}
{3157}{}{Lecker und nahrhaft noch dazu!}
{3158}{}{Du blutest ganz schön stark. Muss zart und saftig sein.} 
{3159}{}{Ich schätze, das ist eher Angst als Begeisterung.} 
#
# target being missed
#
{3160}{}{Du kannst mir nichts anhaben!}
{3161}{}{Und du glaubst, *Ghouls* sind langsam?} 
{3162}{}{Daneben, Normalo!}
{3163}{}{Daneben, Normalo!}
{3164}{}{Du kannst nicht töten, was du nicht treffen kannst!} 
{3165}{}{Zu langsam!}
{3166}{}{Okay, versuchen wir's jetzt mal mit voller Geschwindigkeit.} 
{3167}{}{Hast du wirklich auf mich gezielt?} 
{3168}{}{Was war das denn?}
{3169}{}{Das hier ist kein Pantomimespiel.}
{3170}{}{Im Kampf braucht man volle Konzentration.}
{3171}{}{Schade, dass dein erstes Mal auch dein letztes sein wird.} 
{3172}{}{Siehst du mich an?}
{3173}{}{Willst du's noch mal versuchen, wenn du weißt, was du tust?} 
{3174}{}{Nein, nein, nein, die *Spitze* zeigt zu *mir.* Verstanden?} 
{3175}{}{Worauf hast du gezielt, oder hast du überhaupt gezielt?} 
{3176}{}{Was ist dein verdammtes Problem, du Hohlkopf?}
{3177}{}{Das hast du noch nie gemacht, oder?} 
{3178}{}{Ich bin als Nächster dran!}
{3179}{}{War das wirklich dein *bester* Schuss? Mann, du steckst echt in Schwierigkeiten.}
#
############################################
# 3200 Junkie
############################################
#
#  running away
#
{3200}{}{Whoa. Ich bin SO was von weg.}
{3201}{}{Ich komme wieder ... sobald ich noch einen Treffer gelandet habe.}
{3202}{}{Hätte ich bloß mehr Buffout genommen ...}
{3203}{}{Ich kann mir nichts mehr spritzen, wenn ich tot bin ...}
{3204}{}{Aieeeeeee! Tu mir nicht weh! Tu mir nicht weh!}
{3205}{}{Diese Halluzination ist mir gerade viel zu real geworden ...}
#
# moving in to attack
#
{3220}{}{Friss das!}
{3221}{}{Hoffentlich hast du ein paar Stimpaks ... oder Schmerzmittel.}
{3222}{}{Vielleicht kann ich deinen Körper gegen Schmerzmittel eintauschen ...}
{3223}{}{Ich ... werde ... dich ... schlagen ... wenn ... ich ... dich ... erwische.}
{3224}{}{Vielleicht ist es genau das, was ich brauche: dich umzubringen ...}
{3225}{}{Ich bring dich um! Ich bring dich um! Ich bring dich um!}
{3226}{}{Dich umzubringen gibt meinem Rausch den perfekten Kick ...}
#
# attacking
#
{3240}{}{Friss das!}
{3241}{}{Ich bring dich um! Ich bring dich um! Ich bring dich um!}
{3242}{}{Willst du was davon abhaben?!}
{3243}{}{Nrrrg}
{3244}{}{Hiiijaaaaa}
{3245}{}{Ich bring dich ganz langsam um ...}
{3246}{}{Du gehst drauf wie 'ne Hure für zwei Kronkorken ...}
#
# target being missed
#
{3260}{}{Knapp daneben, aber kein Jet.}
{3261}{}{Ich bin so zugedröhnt, du kriegst mich nie zu fassen!}
{3262}{}{Auf welchen von mir zielst du eigentlich?}
{3263}{}{Whoa. Das war knapp.}
{3264}{}{Ich wusste, dass Jet mich schneller macht ...}
{3265}{}{Du kämpfst ziemlich mies für eine drogeninduzierte Halluzination.}
#
####################################################################################
#
#                   Area People
#
####################################################################################
#                     
#
#                     4000  Arroyo
#                     6000  The Den
#                     8000  Modoc
#                     10000  Klamath
#                     12000  Vault City / Raiders
#                     14000  Gecko
#                     16000 Broken Hills
#                     18000 New Reno
#                     20000 Sierra Army Depot
#                     22000 Redding
#                     24000 NCR
#                     26000 V13 / V15
#                     28000 Military Base
#                     30000 Navarro
#                     32000 San Fransisco
#                     34000 The Enclave
#                     36000 Special (Encounters and Created)
#
#                     Note : Some of these people will just have run away, moving to attack, attacking, and getting
#                                missed.  Others will also have cataloged hit locations.
#
####################################################################################
#
####################################################################################
#
# 4000 Arroyo
#
#                   4000 The Elder
#                   4100 Hakunin
#                   4200 Standing Fist
#
####################################################################################
#
#
####################################################################################
#
# 12000 Vault City / Raiders
#
#                   12000 Raider Mercs
#                   12100 Raider Captain
#                   12200 Gangster
#                   12300 Raider (Hit Locations)
#
####################################################################################
#
############################################
# 12000 Raider Mercs
############################################
#
#  running away
#
{12000}{}{In diesem Chaos bleib ich bestimmt nicht ...}
{12001}{}{Rückzug!}
{12002}{}{Zeit, schleunigst abzuhauen ...}
{12003}{}{Auseinander!}
{12004}{}{Zurückfallen!}
{12005}{}{Ich warte mit diesen Arschlöchern, bis Fallout 3 rauskommt ...}
{12006}{}{Bishop kann sein verdammtes Geld behalten ...}
#
# moving in to attack
#
{12020}{}{Ziel erfasst!}
{12021}{}{Deckt mich jemand!}
{12022}{}{Hut hut hut hut hut hut}
{12023}{}{Hut hut hut hut hut hut}
{12024}{}{Hut hut hut hut hut hut}
{12025}{}{Verabschiede dich von deinem Arsch ...}
{12026}{}{Zeit, diesen Hurensohn auszuschalten ...}
{12027}{}{Laden und entsichern!}
{12028}{}{Los geht's!}
{12029}{}{Na, wer ist denn da einfach ins freie Schussfeld gelaufen ...}
{12030}{}{Hoffentlich hast du ein paar Stimpaks eingepackt, Stammesangehöriger ...}
{12031}{}{Feindkontakt!}
{12032}{}{Das Gebiet wurde durchbrochen!}
{12033}{}{Wir haben einen Eindringling, Jungs!}
{12034}{}{Los, Jungs, wir haben einen Eindringling!}
{12035}{}{Du hast ganz schön Mumm, hier reinzukommen ...}
{12036}{}{Nach Plan, Leute, nach Plan.}
{12037}{}{Achtet auf jedes Detail, Leute!}
{12038}{}{Legt Sperrfeuer! Haltet sie unten!}
#
# attacking
#
{12040}{}{Macht sie fertig!}
{12041}{}{Du hast echt Pech, Stammesangehöriger ...}
{12042}{}{Ich ramme dir meinen Stiefel so tief in den Arsch, dass du eine Woche lang Schuhcreme riechst.}
{12043}{}{::Ich will ein Luftland Ranger sein ...::}
{12044}{}{Kritischer Treffer!}
{12045}{}{Willst du was abkriegen?! WILLST DU WAS ABKRIEGEN?!}
{12046}{}{Hiiijaaaaa!!!}
{12047}{}{Na, komm schon!}
{12048}{}{Hoffentlich hast du ein paar Stimpaks eingepackt, Stammesangehöriger ...}
{12049}{}{Verabschiede dich von deinem Arsch ...}
#
# target being missed
#
{12060}{}{Du kämpfst wie alte Leute vögeln!}
{12061}{}{Ha! Daneben!}
{12062}{}{Zu schnell für dich ...}
{12063}{}{Du wirst lange sterben ...}
{12064}{}{Schlampig ...}
{12065}{}{Schwach UND langsam, wie ich sehe.}
#
############################################
# 12100 Raider Captain
############################################
#
#  running away
#
{12100}{}{Ich muss hier weg!}
{12101}{}{Ich komme wieder ...}
{12102}{}{Heute bringst du mich nicht um!}
{12103}{}{Bis später, Normalo!}
{12104}{}{Du wirst noch von mir hören!}
{12105}{}{Dafür wirst du noch bezahlen – später!}
#
# moving in to attack
#
{12120}{}{Du bist erledigt!}
{12121}{}{Frischfleisch ...}
{12122}{}{Ah, das Abendessen ist da.}
{12123}{}{Gehirne ...}
{12124}{}{Ich schaufle dir dein Grab ...}
{12125}{}{Hoffentlich bleibt dein Kopf heil ...}
#
# attacking
#
{12140}{}{Deine Zeit ist gekommen!}
{12141}{}{Spar dir das Flehen um Gnade ...}
{12142}{}{Das wird mir Spaß machen.}
{12143}{}{Oooo, das muss wehtun!}
{12144}{}{}
{12145}{}{Ich werde deine Leber fressen!}
{12146}{}{Hoffentlich stirbst du nicht zu schnell.}
{12147}{}{Essenszeit!}
{12148}{}{Stirb!}
{12149}{}{Ich fresse Kerle wie dich zum Frühstück und Mittagessen.}
#
# target being missed
#
{12160}{}{Du kannst mir nichts anhaben!}
{12161}{}{}
{12162}{}{Daneben, Normalo!}
{12163}{}{Daneben, Normalo!}
{12164}{}{Du kannst nicht töten, was du nicht treffen kannst!}
{12165}{}{Zu langsam!}
#
############################################
# 12200 Gangster (Combat Messages)
############################################
#
#  running away
#
{12200}{}{Whoa, der Scheiß wird mir zu heftig.}
{12201}{}{Zeit, ein paar von den anderen Jungs zu holen ...}
{12202}{}{Beim nächsten Mal krieg ich dich!}
{12203}{}{Du hast nur Glück, dass ich keine Stimpaks dabei habe ...}
{12204}{}{Zeit, hier verdammt noch mal abzuhauen.}
{12205}{}{Ich muss schnell ein paar Stimpaks finden ...}
#
# moving in to attack
#
{12220}{}{Ich würfel dich wie einen Würfelbecher.}
{12221}{}{Und ich dachte schon, heute würde ich niemanden mehr umbringen ...}
{12222}{}{Sieht aus, als hätte Golgotha einen neuen Bewohner ...}
{12223}{}{Sieht aus, als müssten wir das auf die harte Tour erledigen ...}
{12224}{}{Ich schlag dir die Zähne aus und mach Würfel draus.}
{12225}{}{Sieht aus, als würde jemand mit seinem Leben spielen ...}
{12226}{}{Ich bring dich um, deine Familie und dann deinen Hund.}
{12227}{}{Zeit, den Muell rauszubringen ...}
{12228}{}{Ich brech dich wie ein Hähnchen ...}
#
# attacking
#
{12240}{}{Ich tret dir so hart in den Arsch, dass du ihn als Hut tragen wirst.}
{12241}{}{Lady Luck steht heute nicht auf deiner Seite ...}
{12242}{}{Ich verprügle dich, bis du hässlich bist.}
{12243}{}{Zeit, dich unter die Erde zu bringen.}
{12244}{}{Ich trete dir das Herz aus der Brust und zertrample es.}
{12245}{}{Wär nur Zeit, deinen Kopf in einen Schraubstock zu spannen ...}
{12246}{}{Ich zeig dir mal, was wir hier mit Abschaum machen ...}
{12247}{}{Ich schlag dich so hart, dass du glaubst, es gibt ein Erdbeben ...}
{12248}{}{Ich hab genug von diesem Dreckskerl ...}
{12249}{}{Grüß die Engel von mir ...}
#
# target being missed
#
{12260}{}{Mit solchen Moves landest du im Krankenhaus ...}
{12261}{}{Du schlägst wie ein Mädchen ...}
{12262}{}{Nicht schlecht. Ich zeig dir gleich, wie's geht.}
{12263}{}{Bist du blind und blöd?}
{12264}{}{Bist du auf Jet oder was?}
{12265}{}{Du würdest nicht mal die breite Seite eines Casinos treffen.}
{12266}{}{Wenn du versuchen würdest, die Luft zu treffen, würdest du danebenhauen.}
#
############################################
# 12300 Raider (Hit Locations)
############################################
#
# target hit in head
#
{12300}{}{Ngggg}
{12301}{}{Mein ... Kopf ... mir ... wird schwindelig ...}
{12302}{}{Ugnnn!}
{12303}{}{Nicht ins Gesicht! Nicht ins Gesicht!}
#
# target hit in left arm
#
{12310}{}{Mein ... Arm ... mein ... wunderschöner ... Arm.}
{12311}{}{Sanitäter! Mein Arm ist im Arsch!}
{12312}{}{*hffff*}
#
# target hit in right arm
#
{12320}{}{Meine Wichshand! Hast du denn gar keine Scham?!}
{12321}{}{Sanitäter! Mein Arm ist im Arsch!}
{12322}{}{Sieht aus, als könnte ich meine Knarre mit der Hand nicht mehr polieren ...}
#
# target hit in torso
#
{12330}{}{Meine Milz!}
{12331}{}{Hnrgggg}
{12332}{}{*hff*}
{12333}{}{Dafür ... wirst ... du ... bezahlen ...!}
{12334}{}{*Uuuff*}
{12335}{}{Nggg! Solarplexus!}
#
# target hit in right leg
#
{12360}{}{Verdammt! Mein Bein!}
{12361}{}{*Ärrg*}
{12362}{}{Für mein Bein brauche ich wohl einen stimpak ...}
{12363}{}{Urggg ... mein ... Bein ist ... hinüber ...}
#
# target hit in left leg
#
{12370}{}{Verdammt! Mein Bein!}
{12371}{}{*Ärrg*}
{12372}{}{Für mein Bein brauche ich wohl einen stimpak ...}
{12373}{}{Urggg ... mein ... Bein ist ... hinüber ...}
#
# target hit in eyes
#
{12380}{}{Mein Auge! Mein wunderschönes Auge!}
{12381}{}{Willst du also meine räumliche Wahrnehmung beeinträchtigen, was?}
{12382}{}{Kann ... nicht ... sehen ... Blut ... in den Augen ...}
#
# target hit in groin
#
{12390}{}{Was glaubst du denn, was das hier ist? So ein billiger Actionfilm?}
{12391}{}{Jetzt kann ich nicht mehr so tun, als hätte ich Eier.}
{12392}{}{Tja, da sind meine Messingkugeln wohl hin.}
{12393}{}{Entschuldige mich kurz, während ich mich übergebe.}
{12394}{}{Na toll. Ein Spielercharakter mit einem Kugelfetisch.}
{12395}{}{Lass mich kurz hinlegen, dann komme ich und töte dich.}
{12396}{}{Eier!}
#
####################################################################################
#
# 26000         V13/V15
#
#                    26000  Normal Khan
#                    26100  Tough Khan
#
####################################################################################
#
############################################
# 26000 Khan - Normal
############################################
#
#  running away
{26000}{}{Flieht! Flieht!}
{26001}{}{Rückzug!}
{26002}{}{Neu formieren!}
{26003}{}{Zurückfallen!}
{26004}{}{Rückzug antreten!}
{26005}{}{Ich bin weg!}
#
# moving in to attack
#
{26020}{}{Macht diesen Trottel fertig!}
{26021}{}{Du bist schon tot ...}
{26022}{}{Ich mach dich fertig!}
{26023}{}{Der gehört mir!}
{26024}{}{Nehmt sie euch!}
{26025}{}{Deine Ohren geben eine schöne Trophäe ab!}
#
# attacking
#
{26040}{}{Genieß die letzten Sekunden deines Lebens.}
{26041}{}{Blut! Blut! Blut!}
{26042}{}{Dein Herz gehört mir!}
{26043}{}{Ich liebe es, dir das anzutun!}
{26044}{}{Eure Waffen werden meine Trophäen sein!}
{26045}{}{Tod und Verstümmelung. Zwei meiner Lieblingsdinge!}
{26046}{}{Ich werde dich töten!}
{26047}{}{Deine Knochen werden im Ödland bleichen!}
{26048}{}{Blut und Dunkelheit!}
{26049}{}{Ich plündere deine Leiche!}
{26050}{}{Bohre dem verdammten Bastard ein Loch!}
#
############################################
# 26100 Khan - Tough
############################################
#
#  running away
#
{26100}{}{Khans! Gebt mir Deckung!}
{26101}{}{Rückzug!}
{26102}{}{Neu formieren!}
{26103}{}{Zurückfallen!}
{26104}{}{Rückzug antreten!}
{26105}{}{Abbrechen und neu formieren!}
#
# moving in to attack
#
{26106}{}{Das Spiel kann beginnen!}
{26107}{}{Ich benutze dich als Zielscheibe!}
{26108}{}{Keine Gnade für dich!}
{26109}{}{Der gehört mir!}
{26110}{}{Die Khans greifen an!}
{26111}{}{Jetzt wird gefeiert!}
# [disabled because of duplicates]
#{26111}{}{Would someone please kill this waste of flesh!}
#
# attacking
#
{26112}{}{Khans töten!}
{26113}{}{Die Khans sind die Elite des Ödlands!}
{26114}{}{Ich bin unbesiegbar!}
{26115}{}{Die Khans werden herrschen!}
{26116}{}{Die Khans sind unbesiegbar!}
{26117}{}{Kein Rückzug! Keine Kapitulation!}
{26118}{}{Ich werde dich töten!}
{26119}{}{Ich mache mir eine Halskette aus deinen Zähnen!}
{26120}{}{Blut und Dunkelheit!}
{26121}{}{Die Khans sind stark!}
#
# target being missed
#
{26122}{}{Gute Haltung, aber ich bin hier drüben!}
{26123}{}{Man kann mich nicht berühren!}
{26124}{}{Ich bin unzerstörbar!}
{26125}{}{Mein Blut ist stärker als deins!}
{26126}{}{Vielleicht sollten wir lange genug aufhören, damit du ein paar Übungsschüsse abgeben kannst!}
{26127}{}{Du bist es nicht wert, gegen mich zu kämpfen!}
{26128}{}{Warum verschwende ich meine Zeit mit so jemandem wie dir?}
#
####################################################################################
#
# 32000        San Fransisco
#
#                    32000  Shi Hit Location Messages
#                    32100  The Dragon
#                    32200  Lo Pan
#                    32300  Chip
#                    32400  Badger
#                    32500  Ryan
#                    32600  Shi Guards
#                    32700  Elron Hit Locations
#                    32800  Elron Guards
#                    32900  Ron Cruz/Nikki Goldman
#                    33000  OZ-9
#                    33100  OZ-7
#                    33200  Punk (Hit Locations)
#
####################################################################################
#
############################################
# 32000 Shi Hit Locations
############################################
#
# target hit in head
#
{32000}{}{Mein Gesicht! Mein Gesicht!}
{32001}{}{Meine Kopfhaut!}
{32002}{}{Ooooh ... meine Ohren ...}
#
# target hit in left arm
#
{32010}{}{Au, mein Arm!}
{32011}{}{Au!}
{32012}{}{Du hast mir den Arm gebrochen!}
#
# target hit in right arm
#
{32020}{}{Au, mein Arm!}
{32022}{}{Mein Gott! Mein Arm!}
#
# target hit in torso
#
{32030}{}{AUA!}
{32031}{}{Ich glaube, ich werde ohnmächtig ...}
{32032}{}{Hey! Meine Milz!}
{32033}{}{Uff!}
{32034}{}{Das hat wehgetan!}
{32035}{}{Ich glaube, du hast meine Leber getroffen!}
{32036}{}{Ohhh, diese Schmerzen!}
#
# target hit in right leg
#
{32060}{}{Au, mein Bein}
{32061}{}{Mein Knie!}
{32062}{}{Mitten in die Arterie!}
#
# target hit in left leg
#
{32070}{}{Au, mein Bein}
{32071}{}{::hüpf ... hüpf::}
{32072}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32080}{}{Ich kann nichts sehen! Du Mistkerl!}
{32081}{}{Mein Gesicht! Meine Augen! Arrrrgh!}
{32082}{}{Wo bist du? Hilfe!}
#
# target hit in groin
#
{32090}{}{Ooooooooo, meine Leiste! Ooooooo...}
{32091}{}{I ... ich ... au ...}
{32092}{}{::wimmer::}
{32093}{}{::erbrech::}
{32094}{}{Ich... kann... nicht... atmen...}
{32095}{}{Der Schmerz, der Schmerz...}
#
############################################
# 32100 The Dragon
############################################
#
#  running away
#
{32100}{}{Dein Kung-Fu ist besser als meins!}
{32101}{}{Du bist wahrhaft mächtig. Leb wohl.}
{32102}{}{Aieee! Das Böse triumphiert!}
{32103}{}{Oh nein ...}
{32104}{}{Ich habe versagt.}
{32105}{}{Ich bin entehrt.}
#
# moving in to attack
#
{32120}{}{Es schmerzt mich, dich anzugreifen.}
{32121}{}{Ich rate dir zu fliehen.}
{32122}{}{Nur ein Feigling benutzt Waffen.}
{32123}{}{Flieh, solange du noch kannst.}
{32124}{}{Mach dich auf was gefasst, Übeltäter.}
{32125}{}{Lauf, und ich tue dir nichts.}
{32126}{}{Wenn du unbedingt kämpfen willst ...}
{32128}{}{Glaubst du, du kannst mich besiegen?}
#
# attacking
#
{32140}{}{Haiiiiiiii-YA!}
{32141}{}{Hau drauf!}
{32142}{}{rooOOOooo!}
{32143}{}{Hai!}
{32145}{}{Hai oooOOo!}
{32146}{}{Hai - ah!}
{32147}{}{Zeig, was du draufhast!}
{32148}{}{Mongolisches RINDFLEISCH!}
{32149}{}{Ein Tritt ins Auge!}
#
# target being missed
#
{32160}{}{Nur ein Feigling benutzt Waffen.}
{32161}{}{Hast du Angst, dich einem echten Kämpfer zu stellen?}
{32162}{}{Dein Kung-Fu taugt hier nichts.}
{32163}{}{Ergib dich!}
{32164}{}{Das nennst du kämpfen?}
{32165}{}{Du bewegst dich wie ein trächtiger Yak.}
#
############################################
# 32200 Lo Pan
############################################
#
#  running away
#
{32200}{}{Ich suche ein Mädchen mit grünen Augen ... auf Wiedersehen!}
{32201}{}{Ja, Sir ... der Scheck ist unterwegs.}
{32202}{}{Ich glaube, ich habe einen Termin ...}
{32203}{}{Na gut, du gewinnst!}
{32204}{}{Ich gebe auf!}
{32205}{}{Dein Kung-Fu ist stärker als meins!}
#
# moving in to attack
#
{32220}{}{Blitz! Donner! Tötet sie für mich!}
{32221}{}{Eure Kräfte sind schwach!}
{32222}{}{Dein Kung-Fu kann mir nichts anhaben!}
{32223}{}{Ich bin unbesiegbar!}
{32224}{}{Flieh, Wurm!}
{32225}{}{Der Donner rollt auf dich zu!}
{32226}{}{Schwebe wie ein Schmetterling!}
{32228}{}{Stich wie eine Biene!}
#
# attacking
#
{32240}{}{Wer ist Jack Burton?}
{32241}{}{Ist es zu viel verlangt, dass du endlich stirbst?!}
{32242}{}{Hast du deine Schulden beglichen, Jack?}
{32243}{}{Mit deinem Gesicht stimmt was nicht.}
{32244}{}{Der Scheck ist in der POST!}
{32245}{}{Die Hölle erwartet dich!}
{32246}{}{Grüß deine Vorfahren von mir!}
{32247}{}{Ich bin unsterblich!}
{32248}{}{Chop Suey!}
{32249}{}{Hai-YA!}
#
# target being missed
#
{32260}{}{Ich fühl mich irgendwie unbesiegbar!}
{32261}{}{Zeig, was du draufhast.}
{32262}{}{Das halte ich aus.}
{32263}{}{Du weißt nicht wirklich, wie man kämpft, oder?}
{32264}{}{Das nennst du kämpfen?}
{32265}{}{::gähnt::}
#
############################################
# 32300 Chip
############################################
#
#  running away
#
{32300}{}{Ich habe eine Frau und Kinder!}
{32301}{}{Neeein ... ich habe Geburtstag!}
{32302}{}{Au ... meine Milz ...}
{32303}{}{Zurück ins Krankenhaus!}
{32304}{}{Muss ... schützen ... Milzloch ...}
{32305}{}{Oh, meine arme Leber.}
#
# moving in to attack
#
{32320}{}{Zwing mich nicht, das Cheat-Messer zu benutzen.}
{32321}{}{Ich werde dich so was von vermöbeln ...}
{32322}{}{Frisst du zum Frühstück kleine Stückchen Scheiße?}
{32323}{}{Ich tret dir verdammt noch mal in den Arsch.}
{32324}{}{Ich schneid dich auf!}
{32325}{}{Ich glaube, das war alles, was ich zu sagen habe.}
#
# attacking
#
{32340}{}{Bumm!}
{32341}{}{Ich hab dich fertiggemacht!}
{32342}{}{JAWOLL!}
{32343}{}{Ja, Baby, ja!}
{32344}{}{Willst du davon was abhaben?}
{32345}{}{Beweg dich bloß nicht so!}
{32346}{}{So was von geil, Baby!}
{32347}{}{Oh, ist das dein Gesicht?}
{32348}{}{Dein Gesicht ist hässlich wie die Nacht, was?}
#
# target being missed
#
{32360}{}{Meine Milz verfehlt! Ha-ha!}
{32361}{}{Du TAUGST NICHTS!}
{32362}{}{Ha-ha! Ich bin der Beste!}
{32363}{}{Gib mir einen Kuss, Süße.}
{32364}{}{Zeit, in die Riemen zu legen, Baby.}
{32365}{}{Ich schneid dich auf!}
#
############################################
 # 32400 Badger
############################################
#
#  running away
#
{32400}{}{Nicht ins Gesicht! Schlag mir nicht ins Gesicht!}
{32401}{}{Meine Frisur ist ruiniert, du Ungeheuer!}
{32402}{}{Bastard! Dafür fick ich dich in den Arsch!}
{32403}{}{Ich brauch eine größere Wumme!}
{32404}{}{Waaaaaaaaaaa!!!}
{32405}{}{AAGGH!! Du hast mir in den Arsch geschossen!!}
#
# moving in to attack
#
{32420}{}{Ich sorg dafür, dass du dir wünschst, dein Daddy hätte früher abgespritzt!}
{32421}{}{Sag mal ... du hast ein Gesicht wie ein Arsch!}
{32422}{}{Na, dann zeig mal, was du draufhast, Schwanzlutscher.}
{32423}{}{Runter mit dir und die Knöchel packen, Kleiner!}
{32424}{}{Für Shane!!}
{32425}{}{Ich werde versuchen, es so schmerzhaft wie möglich zu machen.}
{32426}{}{Darf ich dir vorher die Kniescheiben brechen?}
{32428}{}{Na los, Kleine. Zeig mir, was du draufhast.}
#
# attacking
#
{32440}{}{Hoffentlich brauchst du den Arm nicht mehr ...}
{32441}{}{Verdammt, das muss wehtun, was?}
{32442}{}{Uf-da!}
{32443}{}{Ich liebe den Geruch von Blut am Morgen ...}
{32444}{}{Mensch, du blutest ganz schön, was?}
 {32445}{}{::::Rülps!:::::}
{32446}{}{Du hast mein Hemd zerrissen, Mann!!!!}
{32447}{}{Ein heißer Blei-Einlauf kommt sofort!!} 
{32448}{}{Friss das!!}
#
# target being missed
#
{32460}{}{Du schießt schlechter als meine Mom!}
{32461}{}{Verdammt, bist du schlecht!}
{32462}{}{Geh zurück nach L.A., du Weichei!} 
{32463}{}{Soll ich für dich stillhalten?} 
{32464}{}{:::prrrt:::}
{32465}{}{Oh, guter Schuss ...} 
#
############################################
# 32500 Ryan
############################################
#
#  running away
#
{32500}{}{Heiliger Strohsack, ich wollte sie ablecken!}
{32501}{}{La-la-la ... Hilfe!}
{32502}{}{Ha-ha, AUA!}
{32503}{}{AT! AT! At-at-at-at-at!}
{32504}{}{Ay carumba!}
{32505}{}{Hiiilfe!}
#
# moving in to attack
#
{32520}{}{Das hier willst du nicht abkriegen!}
{32521}{}{Komm und hol's dir!}
{32522}{}{Willst du was davon? Hä? Hä?}
{32523}{}{Komm schon! Ich vergewaltige dich!}
{32524}{}{Du bist sowas von tot.}
{32525}{}{Du hast gerade eine ganze Ladung Prügel aufgerissen.}
{32526}{}{Ich hab was für dich, oh ja.}
#
# attacking
#
{32540}{}{Du musst dich durch diesen Scheiß durchkämpfen.}
{32541}{}{::singt::}
{32542}{}{Ich... werde dich immer lieeeben}
{32543}{}{Können wir uns nicht alle vertragen?}
{32544}{}{Du bist sowas von tot.}
{32545}{}{Beug dich mal kurz vor ...}
{32546}{}{Ich hab ein Geschenk für dich.}
{32547}{}{Willst du dich mit mir anlegen?}
{32548}{}{Er schießt ... und trifft!}
{32549}{}{Wie wär's mit ein bisschen Liebe?}
#
# target being missed
#
{32560}{}{Ganz genau!}
{32561}{}{Ganz GENAU!}
{32562}{}{Ha-ha-ha!}
{32563}{}{Wirst du eigentlich jemals besser?}
{32564}{}{Du kannst mich nicht anfassen!}
{32565}{}{Au! Ha-ha ... nur Spaß.}
#
############################################
# 32600 Shi Guards
############################################
#
#  running away
#
{32600}{}{Aiee!}
{32601}{}{Nächster Rang, vortreten!}
{32602}{}{Zurückfallen!}
{32603}{}{Flieht! Flieht!}
{32604}{}{Lauf weg!}
#
# moving in to attack
#
{32620}{}{Mach dich auf eine Schmach gefasst.}
{32621}{}{Die Säulen des Himmels erbeben ...}
{32622}{}{... die Giftpfeile regnen herab ...}
{32623}{}{Hier kommt der Porkchop Express.}
{32624}{}{Wir haben dich gewarnt ...}
{32625}{}{Ein Ex-Gaijin, fertig zum Servieren!}
{32626}{}{Leb wohl, Toter.}
#
# attacking
#
{32640}{}{Etwas für dich ...}
{32641}{}{... etwas für deine Mutter ...}
{32642}{}{... etwas für deinen Vater ...}
{32643}{}{... etwas für deine Schwester ...}
{32644}{}{... und etwas für deine Ahnen!}
{32645}{}{Verschwinde!}
{32646}{}{Stirb!}
{32647}{}{Leb wohl!}
{32648}{}{Lass mich dich entehren!}
{32649}{}{Deine Anwesenheit beleidigt mich.}
#
# target being missed
#
{32660}{}{Alles eine Frage der Reflexe.}
{32661}{}{Du törichter Gaijin!}
{32662}{}{::seufzt:: Wann kämpfen wir endlich gegen jemanden GUTEN?}
{32663}{}{Wird das jemals ein Ende nehmen?}
{32664}{}{Wann fängst du an, mich zu schlagen?}
{32665}{}{Das wird langsam langweilig ...}
#
############################################
# 32700 Elron Hit Locations
############################################
#
# target hit in head
#
{32700}{}{Mein Gesicht! Mein Gesicht!}
{32701}{}{Sternenvater! Heile mich!}
{32702}{}{Autsch! Ich brauche etwas Eis für meinen Kopf}
#
# target hit in left arm
#
{32710}{}{Au, mein Arm}
{32711}{}{Au!}
{32712}{}{Du hast mir den Arm gebrochen!}
#
# target hit in right arm
#
{32720}{}{Au, mein Arm}
{32721}{}{Wahhhh!}
{32722}{}{Bei Elron! Mein Arm!}
#
# target hit in torso
#
{32730}{}{Au! Das hat wirklich wehgetan!}
{32731}{}{Ich glaube, ich werde gleich ohnmächtig}
{32732}{}{Autsch!}
{32733}{}{Sternenvater! Hilf mir!}
{32734}{}{Das hat wehgetan!}
{32735}{}{Lass mich einfach in Ruhe!}
{32736}{}{Ohhh, diese Schmerzen!}
#
# target hit in right leg
#
{32760}{}{Au, mein Bein!}
{32761}{}{Mein Knie!}
{32762}{}{Au!}
#
# target hit in left leg
#
{32770}{}{Au, mein Schienbein!}
{32771}{}{Mein Knie!}
{32772}{}{Aaaarrrrggghhh!}
#
# target hit in eyes
#
{32780}{}{Au!! Meine Augen!}
{32781}{}{Mein Gesicht! Meine Augen! Arrrrgh!}
{32782}{}{Meine Augen!}
#
# target hit in groin
#
{32790}{}{Ooooooooo, meine Leiste! Ooooooo...}
{32791}{}{Autsch... Es brennt!}
{32792}{}{Würg!}
{32793}{}{::Keuch::}
{32794}{}{Ich... kann... nicht... atmen...}
{32795}{}{Zum Glück ... bin ich schon ... unfruchtbar ...}
#
############################################
# 32800 Elron Guards
############################################
#
#  running away
#
{32800}{}{Sternenvater! Hilf uns!}
{32801}{}{Meine Anodynen!}
{32802}{}{Ich will noch Quetzel erleben!}
{32803}{}{Iiiih!}
{32804}{}{Rettet unsere Berühmtheiten!}
{32805}{}{OZ-9! Hilf uns!}
#
# moving in to attack
#
{32820}{}{Ich werde dich so gründlich „zurechtrücken“ ...}
{32821}{}{Ich bin so froh, wenn wir deinesgleichen hinter uns lassen ...}
{32822}{}{Schade, dass du die Zukunft nicht mehr erleben wirst.}
{32823}{}{Widersetze dich niemals dem Sternenvater.}
{32824}{}{Elron wird dich zerschmettern!}
{32825}{}{Wir sind die Rache des Sternenvaters!}
{32826}{}{Tod den Uneingeweihten!}
{32828}{}{Betrachte das als einen anderen Zeta-Scan.}
#
# attacking
#
{32840}{}{Du hast schmutzige Energie!}
{32841}{}{Für den Sternenvater!}
{32842}{}{Für Elron!}
{32843}{}{Für Quetzel!}
{32844}{}{Für OZ-9!}
{32845}{}{Stirb, Ungewaschener!}
{32846}{}{Entweihe unser Heiligtum nicht!}
{32847}{}{Das ist für OZ-9!}
#
# target being missed
#
{32860}{}{Deine Energie ist aus dem Gleichgewicht.}
{32861}{}{Wenn du einer von uns wärst, hättest du mich getroffen.}
{32862}{}{Du hast schmutzige Energie.}
{32863}{}{Schlag keinen wahrhaft Gläubigen!}
{32864}{}{Das setzt deine Anodynen zurück!}
{32865}{}{Unreiner!}
#
############################################
# 32900 Ron Cruz/Nikki Goldman
############################################
#
#  running away
#
{32900}{}{Ich bin ein Filmstar!}
{32901}{}{Prominenz im Anmarsch!}
{32902}{}{Das steht nicht im Drehbuch!}
{32903}{}{Sternenvater! Hilf mir!}
{32904}{}{Aber ich bin berühmt!}
#
############################################
# 33000 OZ-9
############################################
#
#  running away
#
{33000}{}{Sternenvater! Hilf mir!}
{33001}{}{Nein! Nicht ich!}
{33002}{}{Bitte töte jemand anderen!}
{33003}{}{Töte mich nicht! Ich bin OZ-9!}
{33004}{}{Wachen! Helft mir!}
{33005}{}{Du kannst mich nicht töten! Ich bin zu wichtig!}
#
# moving in to attack
#
{33020}{}{Du hättest einer von uns sein können.}
{33021}{}{Die Dummen wenden sich immer gegen ihre Besseren.}
{33022}{}{Deine Unreinheit leuchtet!}
{33023}{}{Hättest du doch nur die Eide abgelegt ...}
{33024}{}{Der Sternenvater wird dich niederstrecken.}
{33025}{}{Du wirst den Planeten Quetzel niemals sehen.}
{33026}{}{Du bist ein Verräter an der Evolution der Menschheit.}
{33028}{}{Unwürdig und unrein.}
#
# attacking
#
{33040}{}{Meine Berührung wird dich reinigen!}
{33041}{}{Ich werde dich erschlagen!}
{33042}{}{Im Namen von Elron!}
{33043}{}{Für den Ruhm des Sternenvaters!}
{33044}{}{Spüre Elrons Zorn!}
{33045}{}{Das wird dich optimieren!}
#
# target being missed
#
{33060}{}{Der Sternenvater rettet mich!}
{33061}{}{Elron beschützt mich!}
{33062}{}{Deine Anodynen sind verstopft!}
{33063}{}{Deine Energie taugt nichts.}
{33064}{}{Weißt du nicht, wie man sich konzentriert?}
#
############################################
# 33100 OZ-7
############################################
#
#  running away
#
{33100}{}{Sternenvater! Hilf mir!}
{33101}{}{Ich wäre lieber auf Quetzel!}
{33102}{}{Nicht ich! Töte mich nicht!}
{33103}{}{Ich bin nur ein Handlanger!}
{33104}{}{Ich treffe nicht die Entscheidungen!}
{33105}{}{Ich bin nicht der, den du suchst!}
#
# moving in to attack
#
{33120}{}{Ich würde das lieber nicht tun ...}
{33121}{}{Bist du sicher, dass du nicht lieber aufgeben willst?}
{33122}{}{Wir können das doch regeln, oder?}
{33123}{}{Wenn OZ-9 sagt, dass du böse bist, musst du böse sein.}
{33124}{}{Für ... ähm ... den Ruhm Elrons!}
{33125}{}{Kämpfen ist schlecht für deine Schmerzmittel ...}
{33126}{}{Ich bin nicht gut in diesem Drohzeug.}
{33128}{}{Entschuldige, falls ich dir gleich wehtun sollte.}
#
# attacking
#
{33140}{}{Pass auf!}
{33141}{}{::kneift die Augen fest zu und greift an::}
{33142}{}{Hier kommt noch ein Angriff ...}
{33143}{}{Wenn du einfach weglaufen würdest, müsste ich das nicht tun.}
{33144}{}{Na los! Verschwinde von hier!}
{33145}{}{Husch! Husch!}
{33146}{}{Hör auf zu kämpfen!}
{33147}{}{Haaaaaallöchen!}
{33148}{}{Du riechst nach Blumen.}
{33149}{}{Wir können das klären!}
#
# target being missed
#
{33160}{}{Warum willst du mir wehtun?}
{33161}{}{Was habe ich dir je getan?}
{33162}{}{Wir müssen uns doch nicht prügeln!}
{33163}{}{Ich will dir nicht wehtun!}
{33164}{}{Ich will nicht, dass du mir wehtust!}
{33165}{}{Können wir das wie Erwachsene klären?}

############################################
# 33200 Punk Hit Locations
############################################
#
# target hit in head
#
{33200}{}{Ich glaube, du hast mir den Kiefer gebrochen!}
{33201}{}{Mein Jochbein!}
{33202}{}{Das gibt eine unschöne Narbe.}
#
# target hit in left arm
#
{33210}{}{Meine Schreibhand!}
{33211}{}{Mein Ellbogen!}
{33212}{}{Hey! Pass auf!}
#
# target hit in right arm
#
{33220}{}{Ahhh! Aiee! Ahh!}
{33221}{}{Wahhhh!}
{33222}{}{Au! Mein Elle!!}
#
# target hit in torso
#
{33230}{}{Ich glaube, du hast meine Niere erwischt!}
{33231}{}{Mein Solarplexus!}
{33232}{}{::keucht::}
{33233}{}{Uff!}
{33234}{}{Das musst du nicht tun ...}
{33235}{}{Okay, das tat weh.}
{33236}{}{Ohhh ... auuuuu}
#
# target hit in right leg
#
{33260}{}{Mein Wadenbein!}
{33261}{}{Mein Knie!}
{33262}{}{Au!}
#
# target hit in left leg
#
{33270}{}{Oooh, mein Oberschenkelknochen!}
{33271}{}{Mein Knie!}
{33272}{}{Danach werde ich wohl hinken ...}
#
# target hit in eyes
#
{33280}{}{Ich glaube, du hast meine Netzhaut abgelöst!}
{33281}{}{Mein Kammerwasser! Mein Glaskörper!}
{33282}{}{Ich bin blind! Ich bin blind!}
#
# target hit in groin
#
{33290}{}{Das ... das ... tut weh ...}
{33291}{}{Mutter ...}
{33292}{}{::wimmer::}
{33293}{}{Heilige Mutter Gottes!}
{33294}{}{Hmm. Au. Hmm.}
{33295}{}{Ich glaube, ich erleide jetzt einen Schock.}
#
####################################################################################
#
# 36000        Special Encounters (Randoms)
#
#                   36000 Kaga (Hit Locations)
#                   36100 Kaga (Combat Messages - Area 1)
#                   36200 Kaga (Combat Messages - Area 2)
#                   36300 Kaga (Combat Messages - Area 3)
#                   36400 Kaga (Combat Messages - Area 4)
#                   36500 Kaga (Combat Messages - Area 5)
#                   36600 Super Mutant (Master Army) - Hit Locations
#                   36700 Super Mutant (Master Army) - Combat Messages
#                   36800 Bounty Hunters - Combat Messages
#
####################################################################################
#
############################################
# 36000 Kaga (Hit Locations)
############################################
#
# target hit in head
#
{36000}{}{Gott! Das hat mich am Kopf getroffen!}
{36001}{}{Au! Mein Kopf!}
{36002}{}{Uff! Kagas Kopf steht in Flammen!}
#
# target hit in left arm
#
{36010}{}{Meine Hand!}
{36011}{}{Au! Zum Glück bin ich Rechtshänder.}
{36012}{}{Au!!}
#
# target hit in right arm
#
{36020}{}{Au, mein Arm}
{36021}{}{Du hast mir den Arm gebrochen!}
{36022}{}{Das wirst du bereuen!}
#
# target hit in torso
#
{36030}{}{(Stöhnt!)}
{36031}{}{Ist nur ein Kratzer!}
{36032}{}{Grrr!}
{36033}{}{Das wirst du bereuen!}
{36034}{}{Du solltest aufhören, solange du noch vorn liegst!}
{36035}{}{Guter Schuss. Jetzt bin ich dran.}
#
# target hit in right leg
#
{36060}{}{Au, mein Bein}
{36061}{}{Dafür wirst du bezahlen!}
{36062}{}{Ah! MEIN BEIN!}
#
# target hit in left leg
#
{36070}{}{Mein Bein!}
{36071}{}{Uff! Zielst du nicht ein bisschen zu tief?}
{36072}{}{Du wolltest doch nicht etwa mein Bein treffen, oder!?!}
#
# target hit in eyes
#
{36080}{}{Verdammt, Blut in meinen Augen!}
{36081}{}{Mein Auge! Dafür wirst du bezahlen!}
{36082}{}{Mistkerl!}
#
# target hit in groin
#
{36090}{}{Oooooo, Auszeit, ich muss etwas aufheben.}
{36091}{}{Ooo! Kaga muss diesen Trick lernen ...}
{36092}{}{Urg! Petey! Alles in Ordnung da unten?}
{36093}{}{Das ... keuch ... tat weh!}
{36094}{}{Würg!}
{36095}{}{(Keucht!)}
#
############################################
# 36100 Kaga (Combat Messages) Area 1
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36100}{}{Wir sehen uns wieder!}
{36101}{}{Ich komme wieder ...}
{36102}{}{Ich wurde noch nie besiegt!}
{36103}{}{Ich werde mich ganz darauf konzentrieren, dich aufzuspüren!}
{36104}{}{Du wirst noch von mir hören!}
{36105}{}{Dafür wirst du noch bezahlen – später!}
#
# moving in to attack
#
{36120}{}{Ich hätte der Auserwählte sein sollen!}
{36121}{}{Arroyo wird es bereuen, mich verstoßen zu haben.}
{36122}{}{Ich werde mich an DIR rächen!}
{36123}{}{Kaga schickt dich ins Jenseits.}
{36124}{}{Noch ein Auserwählter, den ich töten kann!}
#
# attacking
#
{36140}{}{Deine Mami ist nicht hier, um dir zu helfen.}
{36141}{}{Das wird mir Spaß machen.}
{36142}{}{Oooo, das muss wehtun!}
{36143}{}{Ich bringe deinen Kopf zum Ältesten zurück.}
{36144}{}{Ich werde deine Leber fressen!}
{36145}{}{Hoffentlich stirbst du nicht so schnell wie die anderen.}
{36146}{}{Noch ein Auserwählter, den ich töten kann!}
{36147}{}{Stirb!}
{36148}{}{Schrei für mich!}
#
# target being missed
#
{36160}{}{Du kannst mir nichts anhaben!}
{36161}{}{Die Geister beschützen mich.}
{36162}{}{Hoffe, das war nicht dein bester Schuss.}
{36163}{}{Bwahaha. Kaga musste nicht einmal ausweichen!}
{36164}{}{Du kannst nicht töten, was du nicht treffen kannst!}
{36165}{}{Zu langsam!}
#
############################################
# 36200 Kaga (Combat Messages) Area 2
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36200}{}{Wir sehen uns wieder!}
{36201}{}{Ich komme wieder ...}
{36202}{}{Du kannst den großen Kaga nicht töten!}
{36203}{}{Du hast Glück! Kaga hat anderswo zu tun.}
{36204}{}{Du und Kaga werdet euch wiedersehen.}
{36205}{}{Dafür wirst du noch bezahlen – später!}
#
# moving in to attack
#
{36220}{}{Nachdem ich dich getötet habe, werde ich Arroyo dem Erdboden gleichmachen!}
{36221}{}{Alle sollen mich fürchten.}
{36222}{}{Kaga wird deinen Kopf als Trophäe bekommen.}
{36223}{}{Ergib dich, dann mache ich deinen Tod schnell.}
#
# attacking
#
{36240}{}{Spüre Kagas Zorn!}
{36241}{}{Spar dir das Flehen um Gnade ...}
{36242}{}{Das wird mir Spaß machen.}
{36243}{}{Oooo, Kaga hat das sogar von hier gespürt.}
{36244}{}{Ich bringe deinen Kopf zum Ältesten zurück.}
{36245}{}{Ich werde dir mit einem Löffel das Herz herausschneiden!}
{36246}{}{Hoffentlich stirbst du nicht so schnell wie die anderen.}
{36247}{}{Noch ein Auserwählter, den ich töten kann!}
{36248}{}{Stirb!}
{36249}{}{Schrei für mich!}
#
# target being missed
#
{36260}{}{Du kannst mir nichts anhaben!}
{36261}{}{Die Geister beschützen mich.}
{36262}{}{Hoffe, das war nicht dein bester Schuss.}
{36263}{}{Bwahaha. Kaga musste nicht einmal ausweichen!}
{36264}{}{Du kannst nicht töten, was du nicht treffen kannst!}
{36265}{}{Zu langsam!}
#
############################################
# 36300 Kaga (Combat Messages) Area 3
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36300}{}{Das wird langsam zur schlechten Angewohnheit.}
{36301}{}{Kaga muss mehr trainieren.}
{36302}{}{Ich komme wieder. Bla bla bla, ich werde dich töten.}
{36303}{}{Du hast Glück! Kaga hat anderswo zu tun.}
{36304}{}{Du und Kaga werdet euch wiedersehen.}
{36305}{}{Dafür wirst du noch bezahlen – später!}
#
# moving in to attack
#
{36320}{}{Kaga und der Auserwählte treffen sich wieder.}
{36321}{}{Machen wir Schluss damit.}
{36322}{}{Du wirst es bereuen, jemals den Namen Kaga gehört zu haben!}
{36323}{}{Meine Fähigkeiten haben sich verbessert, seit wir uns das letzte Mal begegnet sind.}
#
# attacking
#
{36340}{}{Spüre Kagas Zorn!}
{36341}{}{Das wird mir Spaß machen.}
{36342}{}{Oooo, Kaga hat das sogar von hier gespürt.}
{36343}{}{Ich bringe deinen Kopf zum Ältesten zurück.}
{36344}{}{Ich werde dir mit einem Löffel das Herz herausschneiden!}
{36345}{}{Hoffentlich stirbst du nicht so schnell wie die anderen.}
{36346}{}{Noch ein Auserwählter, den ich töten kann!}
{36347}{}{Stirb!}
{36348}{}{Schrei für mich!}
#
# target being missed
#
{36360}{}{Du kannst mir nichts anhaben!}
{36361}{}{Die Geister beschützen mich.}
{36362}{}{Hoffe, das war nicht dein bester Schuss.}
{36363}{}{Bwahaha. Kaga musste nicht einmal ausweichen!}
{36364}{}{Du kannst nicht töten, was du nicht treffen kannst!}
{36365}{}{Zu langsam!}
#
############################################
# 36400 Kaga (Combat Messages) Area 4
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36400}{}{Das wird langsam zur schlechten Angewohnheit.}
{36401}{}{Kaga muss mehr trainieren.}
{36402}{}{Das ist nicht das letzte Mal, dass du Kaga siehst.}
{36403}{}{Du hast Glück! Kaga hat anderswo zu tun.}
{36404}{}{Du und Kaga werdet euch wiedersehen.}
{36405}{}{Dafür wirst du noch bezahlen – später!}
#
# moving in to attack
#
{36420}{}{Der Auserwählte wird nie nach Arroyo zurückkehren!}
{36421}{}{Kaga wird dich zermalmen!}
{36422}{}{Kaga fürchtet niemanden!}
{36423}{}{Lass Kaga dir die neuen Fähigkeiten beibringen, die er gelernt hat.}
#
# attacking
#
{36440}{}{Spüre Kagas Zorn!}
{36441}{}{Halt still, damit Kaga gut zielen kann.}
{36442}{}{Das wird mir Spaß machen.}
{36443}{}{Oooo, Kaga hat das sogar von hier gespürt.}
{36444}{}{Ich bringe deinen Kopf zum Ältesten zurück.}
{36445}{}{Ich werde dir mit einem Löffel das Herz herausschneiden!}
{36446}{}{Hoffentlich stirbst du nicht so schnell wie die anderen.}
{36447}{}{Noch ein Auserwählter, den ich töten kann!}
{36448}{}{Stirb!}
{36449}{}{Schrei für mich!}
#
# target being missed
#
{36460}{}{Du kannst mir nichts anhaben!}
{36461}{}{Die Geister beschützen mich.}
{36462}{}{Hoffe, das war nicht dein bester Schuss.}
{36463}{}{Bwahaha. Kaga musste nicht einmal ausweichen!}
{36464}{}{Du kannst nicht töten, was du nicht treffen kannst!}
{36465}{}{Zu langsam!}
#
############################################
# 36500 Kaga (Combat Messages) Area 5
# Check for pre attack floats See Kaga.doc
############################################
#
#  running away
#
{36500}{}{}
{36501}{}{}
{36502}{}{}
{36503}{}{}
{36504}{}{}
{36505}{}{}
#
# moving in to attack
#
{36520}{}{Kaga ist jetzt bereit für dich.}
{36521}{}{Du bist Kaga nicht gewachsen.}
{36522}{}{Kaga wird dich ins nächste Leben schicken.}
{36523}{}{Kaga wird dich vermissen.}
#
# attacking
#
{36540}{}{Spüre Kagas Zorn!}
{36541}{}{Kaga wird berühmt werden, weil er dich getötet hat.}
{36542}{}{Das wird mir Spaß machen.}
{36543}{}{Oooo, Kaga hat das sogar von hier gespürt.}
{36544}{}{Ich bringe deinen Kopf zum Ältesten zurück.}
{36545}{}{Hier endet es, Auserwählter.}
{36546}{}{Kaga muss dich jetzt töten.}
{36547}{}{Stirb!}
{36548}{}{Schrei für mich!}
#
# target being missed
#
{36560}{}{Du kannst mir nichts anhaben!}
{36561}{}{Die Geister beschützen mich.}
{36562}{}{Hoffe, das war nicht dein bester Schuss.}
{36563}{}{Bwahaha. Kaga musste nicht einmal ausweichen!}
{36564}{}{Du kannst nicht töten, was du nicht treffen kannst!}
{36565}{}{Zu langsam!}
#
#
############################################
# 36600 Super Mutant (Master Army) - Hit Locations
############################################
#
# target hit in head
#
{36600}{}{Ahhhgh! Mein Gesicht!}
{36601}{}{Mein Gesicht! Dafür wirst du leiden!}
{36602}{}{Ahhhgh! Ich zerreiße dich in Stücke!}
#
# target hit in left arm
#
{36610}{}{Ahhhgh!}
{36611}{}{Au! Du hast den Auserwählten beinahe verletzt!}
{36612}{}{Ahhhgh! Dafür breche ich dir den Hals!}
#
# target hit in right arm
#
{36620}{}{Ahhhgh!}
{36621}{}{Au! Du hast den Auserwählten beinahe verletzt!}
{36622}{}{Ahhhgh! Dafür breche ich dir den Hals!}
#
# target hit in torso
#
{36630}{}{Uff!}
{36631}{}{Grrr!}
{36632}{}{Dafür bringe ich dich um!}
{36633}{}{Du kannst mir nichts mehr anhaben, wenn du tot bist!}
{36634}{}{Ich lache über deinen jämmerlichen Angriff!}
{36635}{}{Oh!}
{36636}{}{Ich tauche dich unter!}
{36637}{}{Grrr! Du machst mich wütend}
{36638}{}{Agh!}
{36639}{}{Diesen Schmerz zahle ich dir heim!}
{36640}{}{Uff!}
{36641}{}{Autsch!}
{36642}{}{Hm, du könntest Ärger machen}
{36643}{}{Grrr! Ich freue mich auf deinen Tod}
{36644}{}{Du kannst mich verletzen, aber nicht gewinnen!}
{36645}{}{Au! Es war keine gute Idee, mich zu verletzen}
#
# target hit in right leg
#
{36660}{}{Ahhhgh! Mein Bein}
{36661}{}{Das nennst du Schmerz? Ich lache!}
{36662}{}{Ahhhgh! Dafür breche ich dir den Hals!}
#
# target hit in left leg
#
{36670}{}{Ahhhgh! Mein Bein}
{36671}{}{Das nennst du Schmerz? Ich lache!}
{36672}{}{Ahhhgh! Dafür breche ich dir den Hals!}
#
# target hit in eyes
#
{36680}{}{Ahhhgh! Elender Mensch! Ich bin blind!}
{36681}{}{Ahhhgh! Schmerz! Was hast du getan!}
{36682}{}{Ahhhgh! Ich werde dich tagelang foltern!}
#
# target hit in groin
#
{36690}{}{Das ist menschliche Schwäche!}
{36691}{}{Das nennst du Schmerz? Ich lache!}
{36692}{}{Du bist dumm, Mensch!}
{36693}{}{Warum greifst du mich dort an?}
{36694}{}{Ich werde dich stundenlang quälen}
{36695}{}{Warum greifst du mich dort an?}
#
############################################
# 36600 Super Mutant (Master Army) - Combat Messages
############################################
#
#  running away
#
{36700}{}{Lauf!}
{36701}{}{Du wirst mich nicht töten!}
{36702}{}{Ich komme wieder!}
{36703}{}{Meine Freunde werden dich für mich erwischen!}
{36704}{}{Dafür wirst du bezahlen -- später!}
{36705}{}{Wir sind Auserwählte! Du stirbst später!}
#
# moving in to attack
#
{36720}{}{Dein Tod naht!}
{36721}{}{Wer die Auserwählten belästigt, belästigt nie wieder jemanden!}
{36722}{}{Menschliche Waffen können mir nichts anhaben!}
{36723}{}{Du wirst leiden, furchtbar leiden!}
{36724}{}{Wenn ich kämpfe, töte ich!}
{36725}{}{Wer ist dumm genug, uns zu verärgern?}
{36726}{}{Ich sehe Feinde, die ich vernichten kann!}
{36727}{}{Du wirst leiden, furchtbar leiden!}
#
# attacking
#
{36740}{}{Jetzt stirbst du.}
{36741}{}{Niemand rettet dich jetzt!}
{36742}{}{Lass mich deinen Schmerz sehen!}
{36743}{}{Jetzt stirbst du einen brennenden Tod!}
{36744}{}{Stirb, du menschlicher Narr!}
{36745}{}{Jetzt stirbst du schreiend.}
{36746}{}{Leide!}
{36747}{}{Jetzt zermalme ich dich.}
{36748}{}{Du kannst nicht gegen die Auserwählten kämpfen!}
{36749}{}{Leide, Mensch!}
#
# target being missed
#
{36760}{}{Warum wehrst du dich?}
{36761}{}{Ist das alles, was Menschen draufhaben?}
{36762}{}{Du hast keine Macht!}
{36763}{}{Du bringst mich zum Lachen!}
{36764}{}{War das ein Angriff?}
{36765}{}{Wir sind die Auserwählten!}
#
####################################################################################
#
#                    Party Members
#
####################################################################################
#                     
#                     Notes
#                     
#                     00-09 Hit in Head
#                     10-19 Hit in Left Arm
#                     20-29 Hit in Right Arm
#                     30-59 Hit in Torso (Generic Non-Called Shot Hit)
#                     60-69 Hit in Right Leg
#                     70-79 Hit in Left Leg
#                     80-89 Hit in Eyes
#                     90-99 Hit in Groin
#                     00-19 Running Away
#                     20-39 Moving in to Attack
#                     40-59 Attacking
#                     60-79 Target being Missed
#
#                     40000 Sulik *
#                     40400 Vic
#                     40800 MacRae *
#                     41200 Lenny *
#                     41600 Marcus *
#                     42000 Myron *
#                     42400 Davin
#                     42800 Miria
#                     43200 Laddie
#                     43600 Cyberdog
#                     44000 Robo-Brain (Idiot/Chimp) *
#                     44400 Robo-Brain (Human/Cybernetic) *
#                     44800 Goris **
#
####################################################################################
#
############################################
# 44800 Goris
############################################
#
# target hit in head
#
{44800}{}{Ich hab zwar einen Dickschädel, aber das tat trotzdem weh.} 
{44801}{}{Ich hab verdammt starke Kopfschmerzen.} 
{44802}{}{Uff. Nicht auf den Kopf!}
{44803}{}{Ich kann übrigens auch Kopfschüsse verteilen!}
{44804}{}{Arrrgh! Mir ist schwindelig ...}
#
# target hit in left arm
#
{44810}{}{Ich bring dich mit dem anderen Arm um.} 
{44811}{}{Ich brauche nicht beide Arme, um dir den Tag zu versauen!} 
{44812}{}{Den Arm benutze ich sowieso nicht.} 
{44813}{}{Autsch! Ich kann hier eine Schlinge tragen.} 
{44814}{}{Ein Arm erledigt, einer noch!} 
 #
# target hit in right arm
#
{44820}{}{Hey, das ist mein Kampfarm!} 
{44821}{}{Verdammt, der Arm tut weh!}
{44822}{}{Mit Leuten wie dir werde ich auch mit nur einem Arm fertig.} 
{44823}{}{Rechter Arm ... arrgh!} 
{44824}{}{Du triffst meinen Arm. Ich reiße dir deinen ab!}
#
# target hit in torso
#
{44830}{}{Uff ... kann ... nicht atmen.}
{44831}{}{Danach fehlen mir wohl ein paar Rippen.}
{44832}{}{Autsch! Ich hasse Treffer in den Bauch.}
{44833}{}{Arrgghh! Brustschmerzen!} 
{44834}{}{Solarplexus ... Herrje, tut das weh!}
{44835}{}{Ist das ein Kampf, oder willst du nur meine Aufmerksamkeit?}
{44836}{}{Sag Bescheid, falls das wehtun sollte. Ich weine für dich.}
{44837}{}{Hat deine Mama dir nicht beigebracht, wie man kämpft?}
{44838}{}{Oh, der Schmerz (gähn). Bitte tu mir nicht noch mehr weh.}
{44839}{}{Das nennst du einen Treffer? Ich zeig dir, wie's geht!}
{44840}{}{Dafür mach ich dich fertig.}
{44841}{}{Whoa! Das brennt ein bisschen.}
{44842}{}{Dafür hab ich den Vault verlassen!?}
{44843}{}{Ich brauche dringend Urlaub.}
{44844}{}{Autsch! Das tut weh!}
{44845}{}{Das hat überhaupt nicht wehgetan.}
{44846}{}{Wo ist ein stimpak, wenn man einen braucht?}
{44847}{}{Sobald ich mich wieder bewegen kann, bist du dran.}
{44848}{}{Ich bin schmerzunempfindlich!}
{44849}{}{Ich mach dir den Monster Mash ins Gesicht!}
#
# target hit in right leg
#
{44860}{}{Na toll. Ich bin der einzige Deathclaw zu Hause mit einem Hinkebein.}
{44861}{}{Autsch! Mein Bein ...} 
{44862}{}{Für das, was du meinem Bein angetan hast, wirst du mit deinem Bein bezahlen.}
{44863}{}{Ich werde dieses Bein vermissen ...} 
{44864}{}{Ich brauche keine zwei Beine, um dich umzubringen.}
#
# target hit in left leg
#
{44870}{}{Na toll. Ein lahmes Bein.}
{44871}{}{Verdammt! Das Bein ...} 
{44872}{}{Nicht das Bein ... Ich kann jetzt schon kaum richtig laufen.} 
{44873}{}{Du machst mein Bein kaputt, ich mach deins kaputt.} 
{44874}{}{Arrrgh! Mein Knie tut weh!}
#
# target hit in eyes
#
{44880}{}{Ich kann nichts sehen!}
{44881}{}{Nicht die Augen!}
{44882}{}{Blut ... in den Augen ... kann nichts sehen.}
{44883}{}{Ich kann dich nicht sehen, aber ich kann dich riechen.}
{44884}{}{Nach der Nummer brauche ich eine Brille!} 
#
# target hit in groin
#
{44890}{}{Ein Tiefschlag ist so billig!} 
{44891}{}{Nein ... nicht ... unter ... die Gürtellinie!}
{44892}{}{Das ist ein dreckiger Trick. Wie wär's, wenn ich dir in den Schritt schlage?} 
{44893}{}{Ich hasse Tritte in die Weichteile! Uunngh ...} 
{44894}{}{Ein Tritt in den Schritt ... gut, dass ich kein Mensch bin!}
#
#  running away
#
{44900}{}{Zeit, abzuhauen!}
{44901}{}{Ich verschwinde!}
{44902}{}{Rückzug!}
{44903}{}{Zurückfallen!}
{44904}{}{Ich bin weg!}
{44905}{}{Beine, lasst mich jetzt nicht im Stich!}
{44906}{}{Aus dem Weg, ich mach mich aus dem Staub!}
{44907}{}{Ich ziehe mich nicht zurück, das ist ein strategischer Rückzug.}
{44908}{}{Ich hab die Scheiße satt!}
{44909}{}{Ich muss hier raus!}
#
# moving in to attack
#
{44920}{}{Komm her, damit ich dich vermöbeln kann!}
{44921}{}{Ihr gehört alle mir!}
{44922}{}{Du oder ich ... und ich stimme für dich!}
{44923}{}{Das wird dein Ende sein!}
{44924}{}{Na los, hol's dir!}
{44925}{}{Mach dich bereit, deinem Schicksal zu begegnen!}
{44926}{}{Verabschiede dich besser von deinem Arsch, solange du noch kannst.}
{44927}{}{Ich werde dich rot anmalen!}
{44928}{}{Jetzt wird gefeiert!}
{44929}{}{Ich stürme rein!}
{44930}{}{Wir sehen uns an der Front!}
{44931}{}{Zeit, jemanden zu erreichen und zu berühren!}
{44932}{}{Vorrücken und vernichten!}
{44933}{}{Ich stürze mich auf dich wie Hässlichkeit auf einen Menschen!}
{44934}{}{Zeit, handgreiflich zu werden!}
{44935}{}{Jetzt wird's persönlich.}
{44936}{}{Ein harter Kerl rückt an!}
{44937}{}{Achtung, ich komme!}
{44938}{}{Ziel erfasst, ich bin auf dem Weg!}
{44939}{}{Da zieht ein Sturm auf!}
#
# attacking
#
{44940}{}{Ich werde dir wehtun ... und zwar richtig!}
{44941}{}{Das wird dir viel mehr wehtun als mir!}
{44942}{}{Tu anderen zuvor, was sie dir antun würden!}
{44943}{}{Wenn dir noch irgendwo nichts wehtut, bist du als Nächstes dran!}
{44944}{}{Kontaktsport. Ich liebe es!}
{44945}{}{Sag mir deinen Namen, damit ich deine Angehörigen benachrichtigen kann.}
{44946}{}{Ich bin derjenige, der den „Tod“ in deathclaw gebracht hat!}
{44947}{}{Geben ist seliger denn Nehmen!}
{44948}{}{Ich hoffe, du hast genauso viel Spaß daran wie ich!}
{44949}{}{Hat das wehgetan? Wenn nicht, kann ich nächstes Mal fester zuschlagen.}
{44950}{}{Hier drüben blutet jemand!}
{44951}{}{Du brauchst mehr als einen stimpak, um wieder zusammengeflickt zu werden, wenn ich fertig bin.}
{44952}{}{Ich hoffe, du hast eine Krankenversicherung. Du wirst sie brauchen.}
{44953}{}{Hier ein Riss, da ein Riss, überall Risse ...}
{44954}{}{Mir ist egal, wer angefangen hat. Ich mache dem Ganzen ein Ende!}
{44955}{}{Ich liebe das Geräusch von reißendem Fleisch. Du nicht auch?}
{44956}{}{Ich wärme mich gerade erst auf. Das Beste kommt noch.}
{44957}{}{Ich schärfe nur meine Krallen.}
{44958}{}{Ups! Hoffentlich brauchtest du das nicht!}
{44959}{}{Wenn du umfällst und liegen bleibst, gehe ich weg!}
#
# target being missed
#
{44960}{}{Kannst du aufhören, dich zu bewegen, damit ich dich treffen kann?}
{44961}{}{Eine Brille. Ich sollte mir wohl eine besorgen.}
{44962}{}{Lach nicht. Wenn ich dich treffe, wird es wehtun!}
{44963}{}{Arrg! Grng! Ghrr! Thpt! (Deathclaw Schimpfwörter mit vier Buchstaben)}
{44964}{}{Ich glaube, Kämpfen sollte ich nicht zu meinem Beruf machen.}
{44965}{}{Wie konnte ich etwas so Großes wie dich nur verfehlen!}
{44966}{}{Sobald ich dich im Visier habe, bist du in Schwierigkeiten.}
{44967}{}{Du bist ja ein flinker kleiner Scheißer.}
{44968}{}{Ich bin froh, dass meine Mutter das nicht gesehen hat.}
{44969}{}{Warum schlage ich dorthin, wenn du doch hier bist?}
{44970}{}{Wie peinlich. Bitte erzähl niemandem, dass mir das passiert ist.}
{44971}{}{Das macht mich echt stinkig!}
{44972}{}{Na gut. Ich hab danebengehauen! Das kann jedem passieren!}
{44973}{}{Nächstes Mal erwische ich dich.}
{44974}{}{Gut gemacht, Grace!}
{44975}{}{Das war ein glänzendes Beispiel dafür, wie man das Ziel verfehlt!}
{44976}{}{Ich glaube langsam, das ist nichts für mich.}
{44977}{}{Arrgh! Ich kann nicht glauben, dass ich dich verfehlt habe!}
{44978}{}{Ich hab bei dem Schlag nur Luft getroffen, jawohl!}
{44979}{}{Hab ich dich gerade verfehlt, oder was?!}
#
