#
# 北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北?
#
# Text labels and messages used by EDITOR.C
#
# (These MUST match "text message" enumeration on the top of EDITOR.C)
#
# 北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北北?
#
#
{100}{}{OK}
{101}{}{OPTIONEN}
{102}{}{ABBRECHEN}
{103}{}{DRUCKEN}
{104}{}{ALTER}
{105}{}{GESCHLECHT}
{106}{}{NAME}
{107}{}{M腘NLICH}
{108}{}{WEIBLICH}
{109}{}{BONUS}
{110}{}{KARMA}
{111}{}{OPFER}
{112}{}{F腍IGKEITSPUNKTE}
{113}{}{Level:}
{114}{}{Erf:}
{115}{}{N鋍h. Lvl:}
{116}{}{FIGURENPUNKTE}
{117}{}{F腍IGKEITEN}
{118}{}{Du mu遲 alle Figurenpunkte verwenden,} # 1
{119}{}{bevor das Spiel beginnt!}         # 2
#
{120}{}{Figurenpunkte}
{121}{}{Anzahl der freien Figurenpunkte, die zu einem Grundwert hinzugef黦t werden k鰊nen.}
{122}{}{N鋍hster Level}
{123}{}{Die Anzahl der Erfahrungspunkte, die f黵 den n鋍hsten Level erforderlich ist.}
{124}{}{Bonus}
{125}{}{Karma}
{126}{}{Opfer}
{127}{}{Bonus gibt zus鋞zliche F鋒igkeiten. Bei jedem dritten Erfahrungslevel kannst du einen Bonus ausw鋒len.}
{128}{}{Dies sind die Auswirkungen der Auswahlm鰃lichkeiten, f黵 die du dich im Spiel entscheidest.}
{129}{}{Ein Z鋒ler, der die Art und Anzahl der Wesen aufzeichnet, die du get鰐et hast, oder deren T鰐ung du miterlebt hast.}
{130}{}{F鋒igkeitspunkte}
{131}{}{Mit diesen Punkten kannst du F鋒ig- keiten erh鰄en. Je weiter bestimmte F鋒igkeiten ausge- baut werden, um so mehr Punkte werden ben鰐igt. Es kann viel Zeit und Punkte kosten, eine F鋒ig- keit zu beherrschen.}
#
{132}{}{H鯿hststand.}        # 1
{133}{}{Zuwachs nicht m鰃lich.}  # 2
{134}{}{Mindeststand.}        # 1
{135}{}{Abnahme nicht m鰃lich.}  # 2
{136}{}{Nicht gen黦end F鋒igkeitspunkte verf黦bar.}
{137}{}{Basis:}
{138}{}{SPEZIALKENNTNISSE}
{139}{}{ZUSATZMERKMALE}
{140}{}{Du besitzt schon die H鯿hstzahl von} # 1
{141}{}{drei Spezialkenntnissen!}               # 2
{142}{}{Spezialkenntnisse m黶sen markiert werden}  # 1
{143}{}{bevor das Spiel beginnt!}       # 2
{144}{}{Spezialkenntnisse}
{145}{}{Spezialkenntnisse sind F鋒igkeiten, auf die sich deine Figur spezialisiert. Jede Spezialkenntnis bringt +20 % und verbessert sich doppelt schnell. Du mu遲 drei Spezialkenntnisse aussuchen.}
{146}{}{Zusatzmerkmale}
{147}{}{Zusatzmerkmale beschreiben deine Figur genauer. Alle Merkmale haben positive und negative Auswirkungen. Beim Erstellen kannst du bis zu zwei Merkmale w鋒len.}
{148}{}{Du besitzt schon die H鯿hstzahl von} # 1
{149}{}{zwei Merkmalen!}                     # 2
{150}{}{F鋒igkeiten}
{151}{}{F鋒igkeiten sind erlerntes Wissen. F鋒igkeiten werden durch Erfahrung bzw. im Verlauf des Spiels durch besondere Ereignisse verbessert. Je h鰄er der F鋒igkeitsgrad, desto besser ist deine F鋒igkeit.}
#
{152}{}{BONUS W腍LEN}
{153}{}{NEUES MERKMAL W腍LEN}
{154}{}{MERKMAL ABLEGEN}
{155}{}{NEUE SPEZIALKENNTNIS W腍LEN}
{156}{}{MERKMALE}
#
{157}{}{Alle Werte m黶sen zwischen 1 und 10 liegen} # 1
{158}{}{bevor das Spiel beginnt!}          # 2
# Fallout 2:
{160}{}{ Du hast den Spielernamen nicht ge鋘dert.} # 1
{161}{}{ Soll diese Spielerfigur dennoch verwendet werden?}        # 2

{175}{}{N鋍h. Lvl:}  # Short for Level:


#
# Abbreviated basic stat levels
#
{200}{}{躡el}  # Terrible
{201}{}{Mies}    # Bad
{202}{}{D黵ftig}   # Poor
{203}{}{Leidlich}   # Fair
{204}{}{Mittel}   # Average
{205}{}{Gut}   # Good
{206}{}{Toll} # Very Good
{207}{}{Klasse}  # Great
{208}{}{Super} # Excellent
{209}{}{Spitze} # Heroic

#
# Abbreviated Derived/Non Derived stat names
#
{300}{}{Trefferpk.}
{301}{}{Aktionspk.}
{302}{}{R黶tungsart}
{303}{}{Schaden-Nichtbewaffnet}
{304}{}{Schaden-Nahk.}
{305}{}{Resist. Verl.}
{306}{}{Resist. Gift}
{307}{}{Resist. Strlng.}
{308}{}{Reaktion}
{309}{}{Heilung}
{310}{}{Kriti. Treff.}
{311}{}{Tragekapaz.}
{312}{}{Vergiftet}
{313}{}{Verstrahlt}
{314}{}{Augenverletzung}
{315}{}{Armverletz.(rechts)}
{316}{}{Armverletz.(links)}
{317}{}{Beinverletz.(rechts)}
{318}{}{Beinverletz.(links)}

#
# Damage info texts
#
# Poisoned
{400}{}{Deine Figur wurde vergiftet. Gift schadet dem Organismus eine gewisse Zeitlang, bis es neutralisiert oder ausgeschieden wird.}
# Radiation
{401}{}{Deine Figur leidet an einer betr鋍htlichen Strahlenvergiftung. Je h鰄er die Verstrahlung, desto t鰀licher der Effekt.}
# Eye Damage
{402}{}{Dies bedeutet, da?deine Figur schwer an einem oder beiden Augen getroffen wurde. Dies beeintr鋍htigt deine Wahrnehmung.}
# Crippled right arm
{403}{}{Der rechte Arm wurde schwer verletzt und kann nicht mehr richtig benutzt werden. Wurde ein Arm verletzt, kannst du keine zweih鋘digen Waffen mehr nutzen. Sind beide Arme betroffen, kannst du nicht mit Waffen angreifen.}
# Crippled left arm
{404}{}{Der linke Arm deiner Figur wurde schwer verletzt und kann nicht mehr richtig benutzt werden. Wurde ein Arm verletzt, kannst du keine zweih鋘digen Waffen mehr nutzen. Sind beide Arme betroffen, kannst du nicht mit Waffen angreifen.}
# Crippled right leg
{405}{}{Deine Figur hat ein verst黰meltes rechtes Bein.}
# Crippled left leg
{406}{}{Deine Figur hat ein verst黰meltes linkes Bein.}

# Month strings
{500}{}{Januar}
{501}{}{Februar}
{502}{}{M鋜z}
{503}{}{April}
{504}{}{Mai}
{505}{}{Juni}
{506}{}{Juli}
{507}{}{August}
{508}{}{September}
{509}{}{Oktober}
{510}{}{November}
{511}{}{Dezember}

#
# Option menu text
#
{600}{}{SPEICHERN}
{601}{}{LADEN}
{602}{}{IN DATEI DRUCKEN}
{603}{}{L諷CHEN}
{604}{}{OK}
{605}{}{Bist du sicher, da?du}      # line 1
{606}{}{die aktuelle Figur l鰏chen willst?}                 # line 2
{607}{}{ wurde erfolgreich gespeichert.}
{608}{}{ wurde erfolgreich geladen.}
{609}{}{existiert schon.}
{610}{}{躡erschreiben?}
{611}{}{Fehler beim Speichern }
{612}{}{Fehler beim Laden }
{613}{}{Figurendatei ung黮tig.}
{614}{}{Figurendaten ung黮tig.}
{615}{}{Fehler beim Lesen der Dateiliste!}
{616}{}{DRUCKEN}
{617}{}{SPIELER}
{618}{}{BLANK.GCD}

#
# ASCII text file printing text
#
{620}{}{FALLOUT}                   # Title line 1
{621}{}{BUNKER-8 PERSONALAKTEN} # Title line 2
{622}{}{Stunden} # Title line 3
# -
# -
#{000}{}{      St鋜ke: 00        Trefferpunkte: 000/000          Reaktion: 00}
#{000}{}{    Wahrnehmung: 00       R黶tungsart: 000          Heilung: 00}
#{000}{}{     Ausdauer: 00     Aktionspunkte: 000       Kritischer Treffer: 000%}
#{000}{}{      Charisma: 00      Schaden im Nahkampf: 000          Tragekapazit鋞: 000 Pfd.}
#{000}{}{  Intelligenz: 00       Resistenz gegen Verletzungen: 000%}
#{000}{}{       Beweglichkeit: 00    Resistenz gegen Strahlung: 000%}
#{000}{}{          Gl點k: 00       Resistenz gegen Gift: 000%}
#
{623}{}{ ::: Werte :::}
{624}{}{       St鋜ke:}
{625}{}{        Trefferpunkte:}
{626}{}{        Reaktion:}
# -
{627}{}{     Wahrnehmung:}
{628}{}{       R黶tungsart:}
{629}{}{        Heilung:}
# -
{630}{}{      Ausdauer:}
{631}{}{     Aktionspunkte:}
{632}{}{      Kritischer Treffer:}
# -
{633}{}{       Charisma:}
{634}{}{      Schaden im Nahkampf:}
{635}{}{         Tragekapazit鋞:}
# -
{636}{}{   Intelligenz:}
{637}{}{       Resistenz gegen Verletzungen:}
# -
{638}{}{        Beweglichkeit:}
{639}{}{    Resistenz gegen Strahlung:}
# -
{640}{}{           Gl點k:}
{641}{}{       Resistenz gegen Gift:}
# -
# -
#{000}{}{ Name: 01234567890        Alter: 00         Geschlecht: Weiblich}
{642}{}{  Name:}
{643}{}{Alter:}
{644}{}{               Geschlecht:}
{645}{}{M鋘nlich}
{646}{}{Weiblich}
#-
#{000}{}{ Level: 00                 Erf: 000,000    N鋍hster Level: 000,000}
{647}{}{ Level:}
{648}{}{                Erf:}
{649}{}{N鋍hster Level:}
#-
{650}{}{ ::: Zusatzmerkmale :::}
{651}{}{ ::: Bonus :::}
{652}{}{ ::: Karma :::}

#-
{653}{}{ ::: F鋒igkeiten :::                ::: Opfer :::}
#-
{654}{}{ ::: Inventar :::}
#-
{655}{}{                                      Gesamtgewicht:}
{656}{}{ ::: Abh鋘gigkeiten :::}
{657}{}{ ::: Ansehen :::}

#
# Karma name strings
#
{1000}{}{Ansehen (Allgemein) }
{1001}{}{Berserker}
{1002}{}{Champion}
{1003}{}{M鰎der}
{1004}{}{Nuka-Cola-Verlangen}
{1005}{}{Buffout-Verlangen}
{1006}{}{Mentats-Verlangen}
{1007}{}{Psycho-Verlangen}
{1008}{}{RadAway-Verlangen}
{1009}{}{Alkohol-Verlangen}
{1010}{}{Jet-Verlangen}
{1011}{}{Tragisches Verlangen}
{1012}{}{THIS GOES WITH THE TEMPORARY ONE FOR DESCRIPTIONS #1112: DON'T TRANSLATE THIS}
{1013}{}{Sexperte}
{1014}{}{Preisboxer}
{1015}{}{Gigolo}
{1016}{}{Totengr鋌er}
{1017}{}{Mafioso: Salvatore}
{1018}{}{Verheiratet}
{1019}{}{Pornostar}
{1020}{}{Sklavenh鋘dler}
{1021}{}{---}
{1022}{}{Big Louies rechte Hand}
{1023}{}{Totengambler}
{1024}{}{Cola-Fanatiker}
{1025}{}{Backgroundsaenger}
{1026}{}{Ehrlicher Fahrer}
{1027}{}{Rasender Fahrer}
{1028}{}{Privatdetektiv}
{1029}{}{Infiziert}
{1030}{}{Legende des Rings von New Reno}
{1031}{}{Legende des Rings von New Vegas}
{1032}{}{Burlesquestar}
{1033}{}{Weisser Jazzmusiker}
{1034}{}{Tresorknacker}
{1035}{}{Bertolinis Berater}
{1036}{}{Lucianos Berater}
{1037}{}{Strykers Mann}
{1038}{}{Thompsons Mann}
{1039}{}{Geschaeftsmann}
{1040}{}{Geschaeftsfrau}
{1041}{}{Sheriff von Uranium City}
{1042}{}{Held der Slums}						

#
# Karma description strings
#
{1100}{}{Dies ist ein Wert, der dein allgemeines Ansehen darstellt. Je h鰄er der Wert, desto bekannter und respektierter bist du. Ist dein Ansehen negativ, wirst du von manchen wegen deiner b鰏artigen Handlungen geha遲.}
{1101}{}{Du hast ein viele Menschen get鰐et. Hierdurch bekannt zu werden ist im allgemeinen kein Vorteil. Menschen aus dem falschen Lager werden dich aber etwas mehr m鰃en.}
{1102}{}{Durch deine Handlungen zeigst du dich als Wohlt鋞er der Menschen. Dein Krieg gegen das B鰏e und Schlechte ist weithin bekannt. Ehrenwerte Menschen respektieren dich noch mehr.}
{1103}{}{Du hast Kinder get鰐et, die Jugend des 謉lands. Dies wird als wirklich schlimm angesehen. Du b鰏er, b鰏er Mensch.}
{1104}{}{Du verg鰐terst Nuka-Cola, die Limonade der postnuklearen Welt.}
{1105}{}{Du bist vom Pr鋚arat Buffout abh鋘gig. Du mu遲 es st鋘dig nehmen, sonst leidest du an Entzugserscheinungen.}
{1106}{}{Du leidest an einer Mentats-Abh鋘gigkeit. Du mu遲 es nehmen, sonst leidest du an Entzugserscheinungen.}
{1107}{}{Du hast eine Pr鋚arat-Abh鋘gigkeit. Wenn du Psycho nicht regelm溥ig nimmst, leidest du. Ansonsten leiden andere.}
{1108}{}{Dein K鰎per ist abh鋘gig von Radaway. Das ist zwar nicht lebensbedrohlich, doch du mu遲 es regelm溥ig nehmen.}
{1109}{}{Du hast ein Alkoholproblem. Genaugenommen hast du viele Probleme mit deinen Trinkgewohnheiten.}
{1110}{}{Du hast eine Pr鋚arat-Abh鋘gigkeit. Du mu遲 regelm溥ig Jet einnehmen.}
{1111}{}{Tragischerweise bist du Garnering-abh鋘gig. Du bist st鋘dig auf der Suche nach neuen Expansionsm鰃lichkeiten.}
{1112}{}{TEMPOR腞 - Was ist das?}
{1113}{}{Du kennst dich mit Sex aus. Du wei遲, was ein Vorspiel ist. Du kannst einen Sexualpartner des anderen Geschlechts so befriedigen, da?er mehr will.}
{1114}{}{Du bist Schwergewichtsmeister von Nordkalifornien. Du hast Ruhm, Respekt und die Liebe Tausender erlangt...und au遝rdem einen Bonus f黵 deine H鋜te und Schlagkraft ohne Waffen.}
{1115}{}{Jetzt mal ganz ehrlich: Du schl鋐st mit allem, was zwei Beine hat. Und manchmal achtest du noch nicht mal darauf.}
{1116}{}{"Die sind tot, denen ist es egal," ist zu deinem Leitspruch geworden. Die 躡erreste anderer auszugraben ist zu mehr als einem Hobby f黵 dich geworden.}
{1117}{}{Du bist ein Mafioso der Familie Salvatore. Du bist bekannt, wirst respektiert, und der Filzhut steht dir ausgezeichnet.}
{1118}{}{Du hast dir eine bessere H鋖fte angelacht. Das ist dein Problem.}
{1119}{}{Du bist ein gro遝r Star. Deine sexuellen Eroberungen sind in ganz New Reno bekannt.}
{1120}{}{Du bist als Mitglied der Sklavenh鋘dlergilde gekennzeichnet worden. Die T鋞owierung auf deiner Stirn macht deinen Beruf f黵 alle offensichtlich.}
{1121}{}{Du solltest mehr ausgehen. Deine sexuellen Erlebnisse sind in letzter Zeit eher...zweidimensional.}
{1122}{}{Man fuerchtet dich, weil dein Boss der Schrecken des Oedlands ist. Schurken flehen um Gnade, friedliche Leute wuenschen dir den Tod.}
{1123}{}{Einem leichtglaeubigen Publikum einen Toten vorzuspielen, mag dumm erscheinen. Fuer dich ist es Mut. Nun blickst du dem Tod viel selbstsicherer ins Auge.}
{1124}{}{In Salt Lake City bist du als schwer fassbarer, skrupelloser Pluenderer von Nuka-Cola-Automaten zur Legende geworden.}
{1125}{}{Schmierigkeit, Flirts, Petzen... Dir ist alles zuzutrauen. Du beherrschst die Kunst, dich einzuschmeicheln, um dir eine bessere Stellung zu verschaffen.}
{1126}{}{Du bist die Legende der Landstrasse. Maenner sind neidisch, Frauen sehen dir nach und Kinder bitten dich um eine Fahrt in deinem Pickup.}
{1127}{}{Dein Verlangen nach Geschwindigkeit brennt in dir. Jedes fahrbereite Fahrzeug betrachtest du als dein Eigentum, und weder Geld noch Gesetz darf euch trennen!}
{1128}{}{Niemand erreicht deine Kombinationsgabe! Deine Erfolge bei schwierigen Kriminalfaellen beeindrucken selbst die erfahrenen Ermittler in Las Vegas.}
{1129}{}{Du leidest an einer seltenen Infektionskrankheit. Sie kann folgenlos ausheilen oder schwere Schaeden verursachen.}
{1130}{}{Du bist der Ringkampf-Champion von Reno. Ruhm, Respekt und die Liebe Tausender sind dein Lohn... dazu ein Bonus auf Ausdauer und Schadenswiderstand.}
{1131}{}{Du bist der Ringkampf-Champion der Sklavenhaendler von Vegas. Ruhm, Respekt und die Liebe Tausender sind dein Lohn... dazu ein Bonus auf Ausdauer und Schadenswiderstand.}
{1132}{}{Du bist ein strahlender neuer Star. Du bist der Beste und verstehst viel von Striptease und der Schoenheit deines Koerpers. In Reno kennt dich jeder.}
{1133}{}{Du bist ein strahlender Buehnenstar. Du bist der Beste und verstehst viel von guter Musik und Harmonie der Sinne. In Reno kennt dich jeder.}
{1134}{}{Du hast so viele Schloesser geknackt, dass du aufgehoert hast zu zaehlen. Jetzt bleibt dir nur noch ein Bankraub... falls es in der postnuklearen Welt noch Banken gibt.}
{1135}{}{Du bist ein Vertrauter von Mr. Bertolini geworden, was deinen Ruf in Reno deutlich gestaerkt hat.}
{1136}{}{Du bist ein Vertrauter von Mr. Luciano geworden, was deinen Ruf in Reno deutlich gestaerkt hat.}
{1137}{}{Du bist ein Vertrauter von Stryker geworden, was deinen Ruf in Reno deutlich gestaerkt hat.}
{1138}{}{Du bist ein Vertrauter von Thompson geworden, was deinen Ruf in Reno deutlich gestaerkt hat.}
{1139}{}{Du bist im Nuka-Cola-Handel erfolgreich. Du erhaeltst einen Bonus auf Glueck; Lieferanten arbeiten nur mit dir und Haendler geben dir ueberall Rabatt.}
{1140}{}{Du bist im Nuka-Cola-Handel erfolgreich. Du erhaeltst einen Bonus auf Glueck; Lieferanten arbeiten nur mit dir und Haendler geben dir ueberall Rabatt.}
{1141}{}{Du bist Sheriff einer kleinen, aber vielversprechenden Stadt geworden.}
{1142}{}{Du hast so viel fuer die Bewohner der Slums von Reno getan, dass man sich noch Generationen an dich erinnern wird.}
#
# Town reputations
#
{2000}{}{Verehrt}
{2001}{}{Gemocht}
{2002}{}{Akzeptiert}
{2003}{}{Neutral}
{2004}{}{Antipathie}
{2005}{}{Geha遲}
{2006}{}{Verachtet}

{2100}{}{Jeder in der Gegend w黵de gerne mit dir tauschen. Du bist der Liebling der ganzen Stadt und giltst als leuchtendes Beispiel daf黵, was jemand aus sich machen kann.}
{2101}{}{Die Leute winken dir zu und gren dich, egal wohin du auch kommst. Jeder in der Gegend hat schon von dir geh鰎t und ist begeistert von dem, was man sich erz鋒lt.}
{2102}{}{Obwohl du in der Gegend nicht gerade mit offenen Armen empfangen wirst, nicken dir die meisten Leute doch zumindest zu. Du pa遲 ganz gut in die hiesige Gesellschaft. }
{2103}{}{Obwohl die Leute in der Gegend Fremden gegen黚er meistens mi遲rauisch sind, sind sie sich 黚er dich noch nicht v鰈lig im klaren.}
{2104}{}{Du bist einfach einer von vielen Fremden in der Stadt und f黨rst wahrscheinlich nichts Gutes im Schilde.}
{2105}{}{Du hast den Leuten aus der Gegend bewiesen, da?ihr anf鋘gliches Mi遲rauen dir gegen黚er gerechtfertigt war. Man starrt dich an und fl黶tert miteinander, wenn du kommst. Es ist bekannt, da?du nichts Gutes im Schilde f黨rst.}
{2106}{}{Manche Leute wechseln unter Gefl黶ter und b鰏en Blicken die Stra遝nseite, damit sie nicht in deiner N鋒e gehen m黶sen. Andere spucken sogar aus und wenden sich ab. Alle wissen, da?du mit zu den schlimmsten Gestalten z鋒lst, die es je in diese Gegend verschlagen hat.}

#
# Karma status strings
#
{3000}{}{Retter der Verdammten}
{3001}{}{W鋍hter des 謉lands}
{3002}{}{Schild der Hoffnung}
{3003}{}{Verteidiger}
{3004}{}{Wanderer}
{3005}{}{Verr鋞er}
{3006}{}{Schwert der Verzweiflung}
{3007}{}{Gei遝l des 謉lands}
{3008}{}{Teufelsbrut}

#
# Karma section titles.
#
{4000}{}{Ansehen}
{4001}{}{Abh鋘gigkeiten}

#
# Karma section descriptions.
#
{4100}{}{Stellt dein Ansehen f黵 einen bestimmten Ort dar.}
{4101}{}{Dinge, von denen du nicht genug bekommen kannst.}

#
# Special Demo version only text
#
{5000}{}{Bedaure, Drucken der }   # 1
{5001}{}{Figur geht nur in der Vollversion.}   # 2
{5002}{}{Bedaure, Speichern der}    # 1
{5003}{}{Figur geht nur in der Vollversion.}   # 2
{5004}{}{Bedaure, Laden einer gespeicherten} # 1
{5005}{}{Figur geht nur in der Vollversion.}   # 2
{5006}{}{MOGELMODUS}
{5007}{}{In der Demo nicht verf黦bar.}
