#======================================================
#
#      Старые названия локаций из Fallout 1 (не используются?)
#
#======================================================

{100}{}{Wueste}
{101}{}{Wueste}
{102}{}{Wueste}
{103}{}{Vault 8}
{104}{}{Vault 8}
{105}{}{Vault 8}
{106}{}{Kriegswind}
{107}{}{Kriegswind}
{108}{}{Kriegswind}
{109}{}{Basis 'Sigma'}
{110}{}{Basis 'Sigma'}
{111}{}{Basis 'Sigma'}
{112}{}{Basis 'Sigma'}
{113}{}{Basis 'Sigma'}
{114}{}{Basis 'Sigma'}
{115}{}{Vault City}
{116}{}{Vault City}
{117}{}{Vault City}
{118}{}{error:Map Name}
{119}{}{Stadtruinen}
{120}{}{Kueste}
{121}{}{Kueste}
{122}{}{Wueste}
{123}{}{Wueste}
{124}{}{error:Map Name}
{125}{}{error:Map Name}
{126}{}{error:Map Name}
{127}{}{error:Map Name}
{128}{}{error:Map Name}
{129}{}{error:Map Name}
{130}{}{error:Map Name}
{131}{}{error:Map Name}
{132}{}{error:Map Name}
{133}{}{error:Map Name}
{134}{}{error:Map Name}
{135}{}{error:Map Name}
{136}{}{error:Map Name}
{137}{}{Hub}
{138}{}{Hub}
{139}{}{Hub}
{140}{}{Hub}
{141}{}{Hub}
{142}{}{Glow}
{143}{}{Glow}
{144}{}{Knochenhof}
{145}{}{Knochenhof}
{146}{}{Knochenhof}
{147}{}{Kathedrale}
{148}{}{Militaerbasis Hawthorne}
{149}{}{Gebirge}
{150}{}{Gebirge}
{151}{}{Wueste}
{152}{}{Wueste}
{153}{}{Wueste}
{154}{}{Wueste}
{155}{}{Bruderschaft}
{156}{}{Wueste}
{157}{}{Wueste}
{158}{}{Gebirge}
{159}{}{Gebirge}
{160}{}{Viperlager}
{161}{}{Wueste}
{162}{}{Gebirge}
{163}{}{Wueste}
{164}{}{Gebirge}

#======================================================
#
#       Названия уровней карт -- AUTOMAP Names
#
#======================================================

#----------------------------------------
# 00: Desert, DESERT1.MAP
#----------------------------------------
{200}{}{Wueste}
{201}{}{}
{202}{}{}
#----------------------------------------
# 01: Desert, DESERT2.MAP
#----------------------------------------
{203}{}{Wueste}
{204}{}{}
{205}{}{}
#----------------------------------------
# 02: Desert, DESERT3.MAP
#----------------------------------------
{206}{}{Wueste}
{207}{}{}
{208}{}{}
#----------------------------------------
# 03: Vault8 Vault, ARCAVES.MAP
#----------------------------------------
{209}{}{Vault, Ebene 1}
{210}{}{Vault, Ebene 2}
{211}{}{Vault, Ebene 3}
#----------------------------------------
# 04: Vault8 VCity, arvillag.MAP
#----------------------------------------
{212}{}{Stadt}
{213}{}{Vault, Ebene 1}
{214}{}{}
#----------------------------------------
# 05: Vault8 Desert, arbridge.MAP
#----------------------------------------
{215}{}{Wueste}
{216}{}{}
{217}{}{}
#----------------------------------------
# 06: Wind Basa, denbus1.MAP
#----------------------------------------
{218}{}{Bahnhof}
{219}{}{Garnison}
{220}{}{Bahnhof, Keller}
#----------------------------------------
# 07: Wind Minivault, denbus2.MAP
#----------------------------------------
{221}{}{Vault-Eingang}
{222}{}{Verlassener Vault}
{223}{}{Hoehle}
#----------------------------------------
# 08: Wind Desert, denres1.MAP
#----------------------------------------
{224}{}{Zerstoerter Stadtrand}
{225}{}{Geheimer Keller}
{226}{}{}
#----------------------------------------
# 09: Klamath Downtown, kladwtwn.MAP
#----------------------------------------
{227}{}{Innenstadt}
{228}{}{}
{229}{}{}
#----------------------------------------
# 10: Klamath Mall, klamall.MAP
#----------------------------------------
{230}{}{Einkaufszentrum}
{231}{}{}
{232}{}{}
#----------------------------------------
# 11: Klamath Rat Caves, klaratcv.MAP
#----------------------------------------
{233}{}{Rattenhoehlen}
{234}{}{}
{235}{}{}
#----------------------------------------
# 12: SL Provo, klatoxcv.MAP
#----------------------------------------
{236}{}{Zentralplatz}
{237}{}{}
{238}{}{}
#----------------------------------------
# 13: Klamath Trapping Caves, klatrap.MAP
#----------------------------------------
{239}{}{Fanggebiet}
{240}{}{Fanggebiet}
{241}{}{Fanggebiet}
#----------------------------------------
# 14: Vault City Laba, VCtyLab.MAP
#----------------------------------------
{242}{}{Brutkammern}
{243}{}{}
{244}{}{}
#----------------------------------------
# 15: Vault City Courtyard, vctyctyd.MAP
#----------------------------------------
{245}{}{Innenhof}
{246}{}{}
{247}{}{}
#----------------------------------------
# 16: Special Bomba Encounter, rndBomba.MAP
#----------------------------------------
{248}{}{Oedland}
{249}{}{}
{250}{}{}
#----------------------------------------
# 17: SaltLakeShadow, vctycocl.MAP
#----------------------------------------
{251}{}{Todeszone}
{252}{}{Familien-Vault}
{253}{}{}
#----------------------------------------
# 18: Shaien Village, modmain.MAP
#----------------------------------------
{254}{}{Stammeslager}
{255}{}{Canyon}
{256}{}{}
#----------------------------------------
# 19: Shaien Raiders, modinn.MAP
#----------------------------------------
{257}{}{Raiderbasis}
{258}{}{Raiderbasis, 2. Stock}
{259}{}{Raiderbasis, Keller}
#----------------------------------------
# 20: Shaien Pastures, modbrah.MAP
#----------------------------------------
{260}{}{Plantagen}
{261}{}{}
{262}{}{}
#----------------------------------------
# 21: Shaien Radio Outside, modgard.MAP
#----------------------------------------
{263}{}{Radiosender - Erdgeschoss}
{264}{}{Radiosender - Untergeschoss}
{265}{}{}
#----------------------------------------
# 22: Black Rock, BlckRck.MAP
#----------------------------------------
{266}{}{Siedlung}
{267}{}{Wueste}
{268}{}{Wueste}
#----------------------------------------
# 23: Hawthorne Barracks, MBASE00.MAP
#----------------------------------------
{269}{}{Garnisonsgebiet}
{270}{}{Garnisonsgebiet}
{271}{}{Garnisonsgebiet}
#----------------------------------------
# 24: Baikers: Owl, gstfarm.MAP
#----------------------------------------
{272}{}{Hauptstrasse}
{273}{}{}
{274}{}{}
#----------------------------------------
# 25: Bikers: Basa, gstcav1.MAP
#----------------------------------------
{275}{}{Radarstation}
{276}{}{}
{277}{}{}
#----------------------------------------
# 26: Ely Depo, gstcav2.MAP
#----------------------------------------
{278}{}{Eisenbahnknoten}
{279}{}{}
{280}{}{}
#----------------------------------------
# 27: Zona Start, depolv1.MAP
#----------------------------------------
{281}{}{Rollbahn}
{282}{}{}
{283}{}{}
#----------------------------------------
# 28: Zona Kasarmes, depolva.MAP
#----------------------------------------
{284}{}{Personalbereich}
{285}{}{Personalbereich}
{286}{}{Hangareingang}
#----------------------------------------
# 29: Hangar Zone, depolvb.MAP
#----------------------------------------
{287}{}{Hangar, Obergeschoss / Erdgeschoss}
{288}{}{Hangar, Untergeschoss}
{289}{}{Hangar, Lueftungsschacht}
#----------------------------------------
# 30: Vault City Vault, vctyvlt.MAP
#----------------------------------------
{290}{}{Vault: Ebene 1}
{291}{}{Vault: Ebene 2}
{292}{}{Vault: Ebene 3}
#----------------------------------------
# 31: Gecko Settlement, gecksetl.MAP
#----------------------------------------
{293}{}{Dorf}
{294}{}{}
{295}{}{}
#----------------------------------------
# 32: Gecko Power Plant, geckpwpl.MAP
#----------------------------------------
{296}{}{Kraftwerk}
{297}{}{}
{298}{}{}
#----------------------------------------
# 33: Gecko Junkyard, geckjunk.MAP
#----------------------------------------
{299}{}{Stadtrand}
{300}{}{Garagendach}
{301}{}{}
#----------------------------------------
# 34: OldTribeCaves, oldTrbCv.MAP
#----------------------------------------
{302}{}{Eingang zur Gecko-Hoehle}
{303}{}{Ausgang der Gecko-Hoehle}
{304}{}{Unterschlupf}
#----------------------------------------
# 35: Vault8 CityDestr, argarden.MAP
#----------------------------------------
{305}{}{Opalmine}
{306}{}{Katakomben}
{307}{}{}
#----------------------------------------
# 36: HarrelsonMap, Harelson.MAP
#----------------------------------------
{308}{}{Gang zum Schutzraum}
{309}{}{Harrelsons Unterschlupf}
{310}{}{}
#----------------------------------------
# 37: New Reno Tommigun, newr6.MAP
#----------------------------------------
{311}{}{Rathaus}
{312}{}{Versorgungs-Vault}
{313}{}{}
#----------------------------------------
# 38: New Reno DeadRunch, newr9.MAP
#----------------------------------------
{314}{}{Verlassene Farm}
{315}{}{}
{316}{}{}
#----------------------------------------
# 39: BlackRockCave, BlckRck2.MAP
#----------------------------------------
{317}{}{Hoehleneingang}
{318}{}{Hoehlenausgang}
{319}{}{Hoehle}
#----------------------------------------
# 40: New Reno Theater, newRTR.MAP
#----------------------------------------
{320}{}{Freiluftkino}
{321}{}{Filmvorfuehrung}
{322}{}{}
#----------------------------------------
# 41: Special DesertRanger, slShadow.MAP
#----------------------------------------
{323}{}{Lager}
{324}{}{Hoehle}
{325}{}{}
#----------------------------------------
# 42: Vegas: The Strip, ncr1.MAP
#----------------------------------------
{326}{}{Saubere Stadt}
{327}{}{Saubere Stadt, 2. Stock}
{328}{}{Saubere Stadt, 2. Stock}
#----------------------------------------
# 43: Vegas: HardRock cafe, ncr2.MAP
#----------------------------------------
{329}{}{'Hard Rock'-Cafe}
{330}{}{}
{331}{}{}
#----------------------------------------
# 44: Vegas: SlaverTown, ncr3.MAP
#----------------------------------------
{332}{}{Sklavenhaendlerbuero}
{333}{}{Sklavenkampfarena}
{334}{}{}
#----------------------------------------
# 45: Vegas: GhoulTown, ncr4.MAP
#----------------------------------------
{335}{}{Totes Hotel}
{336}{}{Rattenloecher}
{337}{}{}
#----------------------------------------
# 46: Vegas: Sign, ncrent.MAP
#----------------------------------------
{338}{}{Parkplatz}
{339}{}{Parkplatz}
{340}{}{Untergrabung}
#----------------------------------------
# 47: Vegas: Hoover Dam, ncrex.MAP
#----------------------------------------
{341}{}{Staudamm - Erdgeschoss}
{342}{}{Unterirdische Staudammanlagen}
{343}{}{Kraftwerk}
#----------------------------------------
# 48: Hawthorne: Hangar 2, mbaseRA.MAP
#----------------------------------------
{344}{}{Reaktoranlage}
{345}{}{}
{346}{}{}
#----------------------------------------
# 49: Hawthorne Hangar, mbase12.MAP
#----------------------------------------
{347}{}{Armeelagerhallen}
{348}{}{Unterirdischer Hangar}
{349}{}{Lagerhausdaecher}
#----------------------------------------
# 50: Hawthorne Railway Station, mbase34.MAP
#----------------------------------------
{350}{}{Bahnhof}
{351}{}{}
{352}{}{}
#----------------------------------------
# 51: Hawthorne ElCapitan, mbclose.MAP
#----------------------------------------
{353}{}{Tote Stadt}
{354}{}{Tote Stadt}
{355}{}{Tote Stadt}
#----------------------------------------
# 52: Wind Run DenRun.MAP
#----------------------------------------
{356}{}{Lager}
{357}{}{Siedlung}
{358}{}{Raiderbasis}
#----------------------------------------
# 53: Car Desert out-of-gas, CarDesrt.MAP
#----------------------------------------
{359}{}{Wueste}
{360}{}{}
{361}{}{}
#----------------------------------------
# 54: New Reno Silver, newr1.MAP
#----------------------------------------
{362}{}{Hotel 'Silver'}
{363}{}{Kanalisation}
{364}{}{Hotel 'Silver', 2. Stock}
#----------------------------------------
# 55: New Reno Eldorado, newr2.MAP
#----------------------------------------
{365}{}{'Eldorado'-Kasino}
{366}{}{'Eldorado'-Kasino, 2. Stock}
{367}{}{Patricks Schlafsaal}
#----------------------------------------
# 56: New Reno Straiker, newr3.MAP
#----------------------------------------
{368}{}{Stadion}
{369}{}{Evakuierungsbunker}
{370}{}{Stadion, 2. Stock}
#----------------------------------------
# 57: New Reno Depo, newr4.MAP
#----------------------------------------
{371}{}{Bahnhof}
{372}{}{Bahnhof - Keller}
{373}{}{}
#----------------------------------------
# 58: New Reno Oliver, newrcs.MAP
#----------------------------------------
{374}{}{Ranch}
{375}{}{Umschlagplatz}
{376}{}{}
#----------------------------------------
# 59: PepGaz, newrgo.MAP
#----------------------------------------
{377}{}{Tankstelle}
{378}{}{}
{379}{}{}
#----------------------------------------
# 60: Vegas Stables, newrst.MAP
#----------------------------------------
{380}{}{Schutzgebiet}
{381}{}{}
{382}{}{}
#----------------------------------------
# 61: New Reno Boxing Arena, newrba.MAP
#----------------------------------------
{383}{}{Boxarena}
{384}{}{}
{385}{}{}
#----------------------------------------
# 62: Wendover Angar, RedWame.Map
#----------------------------------------
{386}{}{Werkstatt}
{387}{}{Hangardach}
{388}{}{}
#----------------------------------------
# 63: Wendover BigAngar, RedWan1.MAP
#----------------------------------------
{389}{}{Grosser Hangar, Dach}
{390}{}{Grosser Hangar, Ebene 1}
{391}{}{Grosser Hangar, Ebene 1}
#----------------------------------------
# 64: Wendover Center, RedDown.MAP
#----------------------------------------
{392}{}{Innenstadt}
{393}{}{Wohngebiet}
{394}{}{Unterirdische Anlagen}
#----------------------------------------
# 65: Wendover TrapperTown, RedMEnt.MAP
#----------------------------------------
{395}{}{Fallenstellervereinigung, Haltestelle}
{396}{}{Fallenstellervereinigung, 2. Stock}
{397}{}{Fallenstellervereinigung, Dach}
#----------------------------------------
# 66: Wendover KislotBog, RedDTun.MAP
#----------------------------------------
{398}{}{Jagdgebiet}
{399}{}{Jagdgebiet}
{400}{}{Jagdgebiet}
#----------------------------------------
# 67: Wendover CityDestroy, redmtun.MAP
#----------------------------------------
{401}{}{Ruinen von Wendover}
{402}{}{Ruinen von Wendover}
{403}{}{Ruinen von Wendover}
#----------------------------------------
# 68: Random Encounter, City 1
{404}{}{Stadt}
{405}{}{Stadt}
{406}{}{Stadt}
# 69: Random Encounter, Cavern 0
{407}{}{Gebirge}
{408}{}{Gebirge}
{409}{}{Gebirge}
# 70: Random Encounter, Cavern 1
{410}{}{Hoehlen}
{411}{}{Hoehle}
{412}{}{Hoehle}
# 71: Random Encounter, Cavern 2
{413}{}{Hoehle}
{414}{}{Hoehle}
{415}{}{Hoehle}
# 72: Random Encounter, Cavern 3
{416}{}{Hoehle}
{417}{}{Hoehle}
{418}{}{Hoehle}
# 73: Random Encounter, Cavern 4
{419}{}{Hoehle}
{420}{}{Hoehle}
{421}{}{Hoehle}
# 74: Random Encounter, Mountain 1
{422}{}{Gebirge}
{423}{}{Gebirge}
{424}{}{Gebirge}
# 75: Random Encounter, Mountain 2
{425}{}{Gebirge}
{426}{}{Gebirge}
{427}{}{Gebirge}
# 76: Random Encounter, Coast 1
{428}{}{Kueste}
{429}{}{Kueste}
{430}{}{Kueste}
# 77: Random Encounter, Coast 2
{431}{}{Kueste}
{432}{}{Kueste}
{433}{}{Kueste}
#----------------------------------------
# 78: Ely City, broken1.map
#----------------------------------------
{434}{}{Schlafsaal / Herberge, 1. Stock}
{435}{}{Schlafsaal / Herberge, 2. Stock}
{436}{}{Schlafsaal / Herberge, 3. Stock}
#----------------------------------------
# 79: Ely Altar, broken2.map
#----------------------------------------
{437}{}{Katholische Kirche}
{438}{}{Tempeluntergeschoss}
{439}{}{Obere Tempelgeschosse}
#----------------------------------------
# 80: Random Encounter, Cavern 5
{440}{}{Hoehle}
{441}{}{Hoehle}
{442}{}{Hoehle}
# 81: Random Encounter, Desert 4
{443}{}{Wueste}
{444}{}{Wueste}
{445}{}{Wueste}
# 82. Random Encounter, Desert 5
{446}{}{Verlassenes Lager}
{447}{}{Verlassenes Lager}
{448}{}{Verlassenes Lager}
# 83. Random Encounter, Desert 6
{449}{}{Verlassene Farm}
{450}{}{Verlassene Farm}
{451}{}{Verlassene Farm}
# 84. Random Encounter, Desert 7
{452}{}{Kaktusfeld}
{453}{}{Kaktusfeld}
{454}{}{Kaktusfeld}
# 85. Random Encounter, Coast 3
{455}{}{Kueste}
{456}{}{Kueste}
{457}{}{Kueste}
# 86. Random Encounter, Coast 4
{458}{}{Kueste}
{459}{}{Kueste}
{460}{}{Kueste}
# 87. Random Encounter, Coast 5
{461}{}{Fernstrasse}
{462}{}{Fernstrasse}
{463}{}{Fernstrasse}
# 88. Random Encounter, Coast 6
{464}{}{Kueste}
{465}{}{Kueste}
{466}{}{Kueste}
# 89. Random Encounter, Coast 7
{467}{}{Kueste}
{468}{}{Kueste}
{469}{}{Kueste}
# 90. Random Encounter, Coast 8
{470}{}{Fernstrasse}
{471}{}{Fernstrasse}
{472}{}{Fernstrasse}
# 91. Random Encounter, Coast 9
{473}{}{Kueste}
{474}{}{Kueste}
{475}{}{Kueste}
#----------------------------------------
# 92. RejectionCity, Reject.MAP
#----------------------------------------
{476}{}{Arbeitersiedlung}
{477}{}{Bergbaulager}
{478}{}{Bergbaustollen}
#----------------------------------------
# 93. DlzhsDead, DlsDeadMAP
#----------------------------------------
{479}{}{Angriffsort}
{480}{}{}
{481}{}{}
#----------------------------------------
# 94. Broken Hills, Random Encounter, Desert
#----------------------------------------
{482}{}{Wueste}
{483}{}{Wueste}
{484}{}{Wueste}
#----------------------------------------
# 95. Broken Hills, Random Encounter, Mountain
#----------------------------------------
{485}{}{Gebirge}
{486}{}{Gebirge}
{487}{}{Gebirge}
#----------------------------------------
# 96. Special Encounter: Roads, rndwhale.MAP
#----------------------------------------
{488}{}{Fallenort}
{489}{}{}
{490}{}{}
#----------------------------------------
# 97. Special Encounter: AnalDen, rndtinwd.MAP
#----------------------------------------
{491}{}{Stinkendes Loch}
{492}{}{Im Loch}
{493}{}{}
#----------------------------------------
# 98. Special Encounter: Mina Pole, rndBHead.MAP
#----------------------------------------
{494}{}{Muellkippenzentrum}
{495}{}{}
{496}{}{}
#----------------------------------------
# 99. Special Encounter: Tanker, rndShutl.MAP
#----------------------------------------
{497}{}{Deck des Tanklasters}
{498}{}{Tanklaster - Oberdeck}
{499}{}{Tanklaster - Unterdeck}
#----------------------------------------
# 100. Special Encounter: Unwashed Villagers
#----------------------------------------
{500}{}{Station}
{501}{}{Station - Keller}
{502}{}{Wueste}
#----------------------------------------
# 101. Special Encounter: Black Isle Office, rndbridg.MAP
#----------------------------------------
{503}{}{Buero - 1. Stock}
{504}{}{Buero - 2. Stock}
{505}{}{Buero - 3. Stock}
#----------------------------------------
# 102. Special Encounter: Cafe of Broken Dreams
#----------------------------------------
{506}{}{Cafe "Neue Hoffnung"}
{507}{}{Kellerraeume}
{508}{}{}
#----------------------------------------
# 103. Special Encounter: Big Egg
#----------------------------------------
{509}{}{Wueste}
{510}{}{}
{511}{}{}
#----------------------------------------
# 104. Special Encounter: Bobby
#----------------------------------------
{512}{}{Wueste}
{513}{}{}
{514}{}{}
#----------------------------------------
# 105. Special Encounter: HomeRoad
#----------------------------------------
{515}{}{Uebergangslager}
{516}{}{}
{517}{}{}
#----------------------------------------
# 106. Special Encounter: Toxic Waste Dump
#----------------------------------------
{518}{}{Oedland}
{519}{}{}
{520}{}{}
#----------------------------------------
# 107. Special Encounter: Cowboy
#----------------------------------------
{521}{}{Fernstrasse}
{522}{}{}
{523}{}{}
#----------------------------------------
# 108. Special Encounter: Piknik
#----------------------------------------
{524}{}{Oase}
{525}{}{Hoehle}
{526}{}{Hoehle}
#----------------------------------------
# 109. Old Rubby, Rubby.MAP
#----------------------------------------
{527}{}{Alte Huette von Rubby}
{528}{}{}
{529}{}{}
#----------------------------------------
# 110. Coast Encounter 10
{530}{}{Kueste}
{531}{}{Kueste}
{532}{}{Kueste}
# 111. Coast Encounter 11
{533}{}{Fernstrasse}
{534}{}{Fernstrasse}
{535}{}{Fernstrasse}
# 112. Coast Encounter 12
{536}{}{Sumpfsaeure}
{537}{}{Sumpfsaeure}
{538}{}{Sumpfsaeure}
# 113. Desert Encounter 8
{539}{}{Schwarzer Wald}
{540}{}{Schwarzer Wald}
{541}{}{Schwarzer Wald}
# 114. Desert Encounter 9
{542}{}{Schwarzer Wald}
{543}{}{Schwarzer Wald}
{544}{}{Schwarzer Wald}
# 115. Desert Encounter 10
{545}{}{Schwarzer Wald}
{546}{}{Schwarzer Wald}
{547}{}{Schwarzer Wald}
# 116. Desert Encounter 11
{548}{}{Wueste}
{549}{}{Wueste}
{550}{}{Wueste}
# 117. Desert Encounter 12
{551}{}{Wueste}
{552}{}{Wueste}
{553}{}{Wueste}
# 118. Cavern Encounter 5
{554}{}{Hoehle}
{555}{}{Hoehle}
{556}{}{Hoehle}
# 119. PsiFarm
{557}{}{Siedlungszentrum}
{558}{}{Unterirdisch}
{559}{}{}
# 120. BeattyCity, Beatty.MAP
{560}{}{Hauptstrasse}
{561}{}{Rathaus}
{562}{}{Rathaus, 2. Stock}
# 121. Mountain Encounter 3
{563}{}{Gebirge}
{564}{}{Gebirge}
{565}{}{Gebirge}
# 122. Mountain Encounter 4
{566}{}{Gebirge}
{567}{}{Gebirge}
{568}{}{Gebirge}
# 123. Mountain Encounter 5
{569}{}{Gebirge}
{570}{}{Gebirge}
{571}{}{Gebirge}
# 124. Mountain Encounter 6
{572}{}{Gebirge}
{573}{}{Gebirge}
{574}{}{Gebirge}
# 125. City Encounter
{575}{}{Verlassene Stadt}
{576}{}{Zerstoerte Stadt}
{577}{}{Zerstoerte Stadt}
#----------------------------------------
# 126. Vault8 FirstStart, artemple.MAP
#----------------------------------------
{578}{}{Jahr 2091 - Vault}
{579}{}{Jahr 2091 - Aussenwelt}
{580}{}{Jahr 2091 - Aussenwelt}
#----------------------------------------
# 127. VaultCityDestroy, ardead.MAP
#----------------------------------------
{581}{}{Zerstoerte Stadt}
{582}{}{Zerstoerte Stadt}
{583}{}{Zerstoerte Stadt}
#----------------------------------------
# 128. Enclave Vault, encdet.MAP
#----------------------------------------
{584}{}{Vault, Ebene 1}
{585}{}{Vault, Ebene 2}
{586}{}{Vault, Ebene 3}
#----------------------------------------
# 129. Enclave Stop, encdock.MAP
#----------------------------------------
{587}{}{Haltestelle}
{588}{}{Lager}
{589}{}{Eisenbahnbruecke}
#----------------------------------------
# 130. Enclave Hangar, encfite.MAP
#----------------------------------------
{590}{}{Hangar}
{591}{}{}
{592}{}{}
#----------------------------------------
# 131. Enclave PostStop, encgd.MAP
#----------------------------------------
{593}{}{Zwischenhalt}
{594}{}{}
{595}{}{}
#----------------------------------------
# 132. Enclave PresdntHead, encpres.MAP
#----------------------------------------
{596}{}{Vault, Ebene 4}
{597}{}{}
{598}{}{}
#----------------------------------------
# 133. Old Tribe, oldtribe.MAP
#----------------------------------------
{599}{}{Siedlung}
{600}{}{Unterirdisch}
{601}{}{Canyon}
#----------------------------------------
# 134. Ely Bunker, enctrp.MAP
#----------------------------------------
{602}{}{Station - Erdgeschoss}
{603}{}{Station - Untergeschoss}
{604}{}{}
#----------------------------------------
# 135. SL Train, sftanker.MAP
#----------------------------------------
{605}{}{Gueterbahnhof}
{606}{}{Unterirdische Kommunikationsanlage}
{607}{}{Eisenbahndepot}
#----------------------------------------
# 136. SL Ogden, sfdock.MAP
#----------------------------------------
{608}{}{Renaissanceplatz}
{609}{}{Familienschutzraum}
{610}{}{}
#----------------------------------------
# 137. SL Center, sfchina.MAP
#----------------------------------------
{611}{}{Geschaeftszentrum}
{612}{}{}
{613}{}{}
#----------------------------------------
# 138. SL Anal, SFSHUTL1.MAP
#----------------------------------------
{614}{}{Canyon}
{615}{}{Abwasserkanal}
{616}{}{Abwasserkanal}
#----------------------------------------
# 139. SL Mormones, SFSHUTL2.MAP
#----------------------------------------
{617}{}{Tempel}
{618}{}{Tempeldach}
{619}{}{Tempeluntergeschoss}
#----------------------------------------
# 140. SL Artesian, sfelronb.MAP
#----------------------------------------
{620}{}{Ghetto}
{621}{}{Artesischer Turm}
{622}{}{Familienschutzraum}
#----------------------------------------
# 141. City Encounter 3
{623}{}{Zerstoerte Stadt}
{624}{}{Zerstoerte Stadt}
{625}{}{Zerstoerte Stadt}
# 142. City Encounter 4
{626}{}{Zerstoerte Stadt}
{627}{}{Zerstoerte Stadt}
{628}{}{Zerstoerte Stadt}
# 143. City Encounter 5
{629}{}{Zerstoerte Stadt}
{630}{}{Zerstoerte Stadt}
{631}{}{Zerstoerte Stadt}
# 144. City Encounter 6
{632}{}{Zerstoerte Stadt}
{633}{}{Zerstoerte Stadt}
{634}{}{Zerstoerte Stadt}
# 145. City Encounter 7
{635}{}{Zerstoerte Stadt}
{636}{}{Zerstoerte Stadt}
{637}{}{Zerstoerte Stadt}
# 146. City Encounter 8
{638}{}{Zerstoerte Stadt}
{639}{}{Zerstoerte Stadt}
{640}{}{Zerstoerte Stadt}
#----------------------------------------
# 147. New Reno Raider, newrvb.MAP
#----------------------------------------
{641}{}{Stadtruinen}
{642}{}{}
{643}{}{}
#----------------------------------------
# 148. SL NukeCola, sfchina2.MAP
#----------------------------------------
{644}{}{Nuka-Cola-Fabrik}
{645}{}{Nuka-Cola-Fabrik, 2. Stock}
{646}{}{Nuka-Cola-Fabrik, Keller}
#----------------------------------------
# 149. In Game Movie, gammovie.MAP
#----------------------------------------
{647}{}{Wueste}
{648}{}{Wueste}
{649}{}{Wueste}
#----------------------------------------
# 150. RndBess, rndbess.MAP
#----------------------------------------
{650}{}{Uebergangslager}
{651}{}{Wueste}
{652}{}{Wueste}

#==========================================================
#
#	Названия локаций на карте мира и в мини-карте
#       Нумерация: 1500+Area. Номер area см. в CITY.TXT разделы вида [Area ??]
#
#==========================================================

{1500}{}{Vault City}
{1501}{}{Kriegswind}
{1502}{}{Die Basis 'Sigma'}
{1503}{}{Lovelock}
{1504}{}{Baydie}
{1505}{}{Poseidon-Oelkraftwerk}
{1506}{}{Ailie}
{1507}{}{New Reno}
{1508}{}{Area 51}
{1509}{}{Bridgeport}
{1510}{}{Las Vegas}
{1511}{}{Bezirk Provo}
{1512}{}{Militaerbasis Hawthorne}
{1513}{}{Wendover}
{1514}{}{Salt Lake City}
{1515}{}{Old Rabbi}
{1516}{}{Regierungs-Vault}
{1517}{}{Gerlach}
{1518}{}{Uranium City}
{1519}{}{The Pound}
{1520}{}{Battle Mountain}
{1521}{}{Auto ohne Treibstoff}
{1522}{}{Vault City}
{1523}{}{Verkehrsstau}
{1524}{}{Operation Kriegswind}
{1525}{}{Black Rock}
{1526}{}{Wueste}
{1527}{}{Gebirge}
{1528}{}{Zerstoerte Stadt}
{1529}{}{Kueste}
{1530}{}{Tankstelle}
{1531}{}{Kreuzung}
{1532}{}{Grosses Loch}
{1533}{}{Reifenhalde}
{1534}{}{Tanklaster in der Wueste}
{1535}{}{Unheimlicher Ort}
{1536}{}{Verlorenes Buero}
{1537}{}{Cafe 'Neue Hoffnung'}
{1538}{}{Riesenei}
{1539}{}{Bobbys Huette}
{1540}{}{Haus auf Raedern}
{1541}{}{'Furthur'}
{1542}{}{Verlassene Rangerstation}
{1543}{}{Picknickplatz}
{1544}{}{Karawane}
{1545}{}{"Lieber John"}
{1546}{}{Harrelson}
{1547}{}{Zufallsbegegnung}
{1548}{}{Zerbrochene Postkutsche}
{1549}{}{Auto}
{1550}{}{Umgebung von Vault 8}
{1551}{}{New Reno (2)}
{1552}{}{Total Recall}
