#
# ???????????????????????????????????????
#
# Text labels and messages used in PIPBOY.C
#
# (These MUST match "text message" enumeration on the top of PIPBOY.C)
#
# ???????????????????????????????????????

#
# Special holiday dates
#
{100}{}{Frohes neues Jahr!}      # New years
{101}{}{Frohen Valentinstag!}     # April fools
{102}{}{Frohen 1. April!}          # April fools
{103}{}{Frohen Kapitänstag!}       # Shipping day!
{104}{}{Frohen Unabhängigkeitstag!}    # Independence day
{105}{}{Frohes Halloween!}           # Halloween
{106}{}{Frohen Erntedanktag!}    # Thanksgiving
{107}{}{Frohe Weihnachten!}           # X-mas

#
# System messages
#
{200}{}{MEHR}
{201}{}{ZURüCK}
{202}{}{STATUS}
{203}{}{Derzeit keine Aufgaben.}
{204}{}{HINWEISE}  # clüs gone
{205}{}{KARTEN}
{206}{}{VIDEOARCHIV}
{207}{}{DATEN}
{208}{}{}
{209}{}{}
{210}{}{Status}
{211}{}{DATEN}
{212}{}{von}
{213}{}{Seite}
{214}{}{FERTIG}
{215}{}{An diesem Ort kannst du nicht rasten!}

#
# Alarm clock
#
{300}{}{WECKER}
{301}{}{Trefferpunkte}
{302}{}{Zehn Minuten rasten}
{303}{}{Dreissig Minuten rasten}
{304}{}{Eine Stunde rasten}
{305}{}{Zwei Stunden rasten}
{306}{}{Drei Stunden rasten}
{307}{}{Vier Stunden rasten}
{308}{}{Fünf Stunden rasten}
{309}{}{Sechs Stunden rasten}
{310}{}{Bis zum Morgen rasten (0800)}
{311}{}{Bis zum Mittag rasten (1200)}
{312}{}{Bis zum Abend rasten (1800)}
{313}{}{Bis Mitternacht rasten (0000)}
{314}{}{Rasten, bis du geheilt bist}
{315}{}{Rasten, bis die Gruppe geheilt ist}

#
# Holodisk titles
#
{400}{}{Lagerhauszuweisung}
{401}{}{Vorläufiger Bericht}
{402}{}{Gegenstandsliste}
{403}{}{-leer-}
{404}{}{Bericht über Deserteure}
{405}{}{-leer-}
{406}{}{Tagebucheinträge}
{407}{}{Medizinischer Bericht}
{408}{}{Exodus}
{409}{}{Dokumente des Radiosenders}
{410}{}{Jays Nachricht}
{411}{}{Geschichte von "Wind of War"}
{412}{}{Analyse der Speicherkarte}
{413}{}{Zeitungsnotiz über Big Louie}
{414}{}{Aufzeichnungen des gefangenen Mannes}
{415}{}{Aufzeichnungen des Offiziers}
{416}{}{-leer-}
{417}{}{-leer-}
{418}{}{Strafakte Nr. 4783}
{419}{}{Werbung für die Postkutsche}
{420}{}{-leer-}

#
# Movie archive titles
# Order must match the list (see gmovie.h)
#
{500}{}{Warnung}
{501}{}{Intro}
{502}{}{Jahr 2091}
{503}{}{Jahr 2140}
{504}{}{Verbannung}
{505}{}{Erstes Mal an der Oberfläche}
{506}{}{Auto starten}
{507}{}{Panorama von Hawthorne}
{508}{}{-leer-}
{509}{}{Abfahrt mit dem Zug}
{510}{}{-leer-}
{511}{}{Rückkehr nach Salt Lake}
{512}{}{Erinnerung 1}
{513}{}{Erinnerung 2}
{514}{}{Erinnerung 3}
{515}{}{SOS-Signal}
{516}{}{Credits}

#
# Things for the Mac version to speak
#
#
{600}{}{Status}
{601}{}{Hinweise}  # Clüs gone
{602}{}{Automaps}
{603}{}{Archive}
{604}{}{Wecker}
{605}{}{Doo da doo da dum dee dee doodly doo dum dum dum doo da doo da doo da doo da doo da doo da doo}
{606}{}{Willkommen beim Rob Co. Pipboy 2009.}
{607}{}{Mach's gut.}
{608}{}{Aufwachen.}


#
# Holodisk text
#

# Special assignment VC - list
# GVAR_VC_SUPERBONUS
{1000}{}{Das Lagerhaus von Vault 8 benötigt folgende}
{1001}{}{Vault-Tec-Technologiegeräte:}
{1002}{}{}
{1003}{}{  * Ionensynthesizer}
{1004}{}{  * Gasanalysator}
{1005}{}{  * Impulsmodulator}
{1006}{}{  * Druckregler}
{1007}{}{  * Chip für den Kleidungssynthesizer}
{1008}{}{}
{1009}{}{**END-DISK**}

# Vault 8: Investigator report
# GVAR_HOLODISK_COUNTRY_MSG (GVAR_HOLODISK_MB_OUTSIDE)
{2000}{}{Entwurf eines Berichts über die strafrechtliche Verfolgung}
{2001}{}{}
{2002}{}{Verfasser - Malcolm Rivers, Deputy des Sheriffs}
{2003}{}{}
{2004}{}{}
{2005}{}{Ich habe angefangen, diesen Bericht zu schreiben, falls}
{2006}{}{uns etwas zustösst. Wenn du diese Notizen findest,}
{2007}{}{schick sie an den Sheriff von Washö County,}
{2008}{}{Bundesstaat Nevada.}
{2009}{}{}
{2010}{}{Eintrag 1}
{2011}{}{}
{2012}{}{Ely Gorbinsky, ein mieser Hurensohn. Er entkam der}
{2013}{}{Justiz, nachdem er in den Strassen von New Reno einen Afroamerikaner}
{2014}{}{getötet hatte. Das Gericht verurteilte ihn lediglich zu}
{2015}{}{Hausarrest. Und ich kann so einen dreisten Akt von}
{2016}{}{Rassismus nicht einfach hinnehmen! Deshalb habe ich angefangen,}
{2017}{}{den Verbrecher zu beschatten, und das nicht ohne Grund. Er hat}
{2018}{}{die Stadt tatsächlich verlassen und ist nach Norden gezogen, unter Missachtung des Gerichtsbeschlusses.}
{2019}{}{Ich folgte ihm. Als er herausfand, dass er verfolgt wurde,}
{2020}{}{versuchte Gorbinsky, mich abzuschütteln, aber ich}
{2021}{}{blieb ihm ständig auf den Fersen, bis wir den Highway erreichten.}
{2022}{}{Ein paar Meilen von NPP "Poseidon Oil" entfernt holten wir ihn ein,}
{2023}{}{doch der Verbrecher versuchte, mein Auto von der Strasse zu rammen.}
{2024}{}{Bei dem Unfall wurden beide Fahrzeuge zu Schrott gefahren.}
{2025}{}{Gorbinsky stiess sich den Kopf und verlor das Bewusstsein.}
{2026}{}{Ich kam mit nur ein paar Prellungen davon (zum Glück!).}
{2027}{}{Während der Bastard wieder zu sich kam,}
{2028}{}{rief ich über Funk nach Verstärkung.}
{2029}{}{}
{2030}{}{Der Truck von NPP kam, brachte uns zur}
{2031}{}{Station. Damit Gorbinsky nicht auf dumme Gedanken kam,}
{2032}{}{legte ich mir selbst Handschellen an und kettete mich an}
{2033}{}{ihn. Ausserdem beschlagnahmte ich seine Sachen. Auf der Station}
{2034}{}{konnte mir niemand helfen - dort herrschte das reinste Chaos.}
{2035}{}{Es sah so aus, als würde NPP abgeriegelt und}
{2036}{}{die Leute sich auf eine Notevakuierung vorbereiten. Aber ich}
{2037}{}{hatte keine Zeit, die Dinge herauszufinden. Meine Verstärkung ist nie}
{2038}{}{angekommen, also musste ich morgens mit dem Bus nach New Reno fahren,}
{2039}{}{zusammen mit einem Verbrecher. Der Fahrer}
{2040}{}{machte Halt in einem Opal-Bergbaudorf, dem Eigentum der}
{2041}{}{Wilsons Familie. Sie sind anständige Leute, sie verdienten}
{2042}{}{ihren Lebensunterhalt mit dem Opalabbau in der Gegend,}
{2043}{}{und nahmen uns recht gastfreundlich auf.}
{2044}{}{}
{2045}{}{Irgendwann gegen 12:30 Uhr entkam Ely Gorbinsky.}
{2046}{}{Während er an einen Heizkörper gefesselt war, ging ich}
{2047}{}{zu einem Laden. Und irgendwie schaffte er es,}
{2048}{}{das Schloss mit einem Stück Draht zu knacken.}
{2049}{}{Als ich aus dem Haus rannte, fuhr er bereits}
{2050}{}{mit einem gekaperten Bus bei voller Geschwindigkeit nach Süden.}
{2051}{}{Ausserdem nahm er Fahrgäste mit, die}
{2052}{}{wahrscheinlich nicht einmal etwas bemerkten. Der Busfahrer}
{2053}{}{wurde später tot auf der Toilette gefunden.}
{2054}{}{}
{2055}{}{Hier gibt es kein Radio. Der nächste Bus sollte}
{2056}{}{morgen gegen Mittag kommen. Der örtliche Truck wird repariert.}
{2057}{}{und wird erst morgen früh fertig}
{2058}{}{höchstens. Alles, was bleibt, ist zu hoffen, dass}
{2059}{}{Gorbinsky in der Zeit keinen weiteren ärger macht.}
{2060}{}{}
{2061}{}{So oder so, ich werde ihn seiner gerechten Strafe zuführen!}
{2062}{}{Verbrecher werden nicht frei herumlaufen.}
{2063}{}{Nicht einmal an einem abgelegenen Ort wie unserem ruhigen Landkreis.}
{2064}{}{}
{2065}{}{Eintrag 2}
{2066}{}{}
{2067}{}{Ich habe bis 16:00 Uhr auf einen Bus gewartet. Als mir klar wurde,}
{2068}{}{dass er nicht kommen würde, fing ich an, den}
{2069}{}{Mechaniker zu drängen, sich mit dem Truck zu beeilen. Aber er war}
{2070}{}{zu dem Zeitpunkt stockbesoffen. Ich muss}
{2071}{}{noch einen Tag hierbleiben, während dieser verdammte}
{2072}{}{Gorbinsky mit einem gestohlenen Fahrzeug auf freiem Fuss ist!}
{2073}{}{Das ist unerträglich. Ich muss ihn aufhalten, aber}
{2074}{}{stattdessen sitze ich hier fest, wegen irgendwelcher technischen }
{2075}{}{Schwierigkeiten. Bin ich der Einzige, dem hier}
{2076}{}{Gerechtigkeit wichtig ist?...}
{2077}{}{}
{2078}{}{Wir haben den Körper des Fahrers in Bettlaken gewickelt}
{2079}{}{und ihn an einem kühlen Ort im Hangar abgelegt.}
{2080}{}{Dieser Bastard! Wenn ich Gorbinsky erwische, wird kein}
{2081}{}{Richter ihn retten!}
{2082}{}{}
{2083}{}{Eintrag 3}
{2084}{}{}
{2085}{}{Heute war ein harter Tag...}
{2086}{}{}
{2087}{}{Der Bus ist wieder nicht gekommen. Bis zum Mittagessen habe ich}
{2088}{}{den Mechaniker praktisch gezwungen, den Motor des}
{2089}{}{Trucks zu reparieren. Wir machten uns auf den Weg nach Reno,}
{2090}{}{doch gleich im nächsten Tal fanden wir den Bus,}
{2091}{}{mit dem Gorbinsky geflohen war.}
{2092}{}{Er war leer. Und aus irgendeinem Grund zeigte seine Front }
{2093}{}{zum Dorf. Entweder ist Gorbinsky zurückgekommen oder hat es gar nicht}
{2094}{}{verlassen! Mit dem Funkgerät im Bus versuchte ich,}
{2095}{}{meine Leute zu erreichen, dann wenigstens den Busbahnhof in }
{2096}{}{Reno, aber statt einer }
{2097}{}{Antwort hörte ich nur Rauschen. Sind dort etwa alle tot, verdammt?!}
{2098}{}{}
{2099}{}{Wir kehrten ins Dorf zurück, um die Leute}
{2100}{}{vor der Gefahr zu warnen, aber wir kamen zu spät - einer der}
{2101}{}{Arbeiter sind im Diner bereits eines gewaltsamen Todes gestorben.}
{2102}{}{So etwas wünscht man nicht einmal seinem Feind.}
{2103}{}{}
{2104}{}{Ich beschloss zu bleiben, um den Einheimischen zu helfen.}
{2105}{}{Sonst, verdammt noch mal, warum trage ich das Abzeichen eines }
{2106}{}{Hilfssheriffs? Die harte Hand der Themis ist genau das,}
{2107}{}{was dieser Ort braucht, was Amerika schon so lange}
{2108}{}{so dringend gebraucht hat... Und es war richtig, dass ich blieb.}
{2109}{}{Spät in der Nacht fanden die Wilsons einen weiteren Arbeiterkopf}
{2110}{}{in der Waschmaschine.}
{2111}{}{}
{2112}{}{Dieser Hurensohn treibt sich irgendwo in der Nähe herum!}
{2113}{}{Ich muss ihn aufhalten, bevor noch jemand}
{2114}{}{zu Schaden kommt...}
{2115}{}{}
{2116}{}{Eintrag 4}
{2117}{}{}
{2118}{}{...Habe kaum geschlafen. Der Truck wurde}
{2119}{}{nachts angezündet. Der Mechaniker war drin. Man hatte ihn zuvor}
{2120}{}{betrunken gesehen, also beschlossen die Wilsons, er sei für das Feuer}
{2121}{}{verantwortlich.}
{2122}{}{Aber ich weiss, wer daran schuld ist!}
{2123}{}{}
{2124}{}{Jetzt haben wir kein Transportmittel mehr. Gar keins.}
{2125}{}{Diejenigen, die sich in meine Ermittlungen einmischten, sperrte ich}
{2126}{}{im Diner ein. Sollen sie dort sitzen und ein wenig nachdenken,}
{2127}{}{während ich mich um diesen dreckigen Abschaum kümmere...}
{2128}{}{}
{2129}{}{Eintrag 5}
{2130}{}{}
{2131}{}{Jetzt bin ich ganz allein.}
{2132}{}{Die ganze Zeit seit meinem letzten Eintrag hat Gorbinsky}
{2133}{}{still und heimtückisch jeden Tag ein Leben genommen...}
{2134}{}{Bastard! Ich hoffe, du verreckst in der Hölle!!!...}
{2135}{}{Niemand ausser mir kann ihn jetzt noch aufhalten}
{2136}{}{und die Gerechtigkeit wiederherstellen.}
{2137}{}{Wenn doch nur... Wenn der Richter ihn doch nur auf den}
{2138}{}{elektrischen Stuhl geschickt hätte...}
{2139}{}{WENN DOCH NUR die Streife rechtzeitig auf meinen Ruf}
{2140}{}{reagiert hätte...}
{2141}{}{Aber was zum Teufel geht hier in der Welt vor?!}
{2142}{}{Warum sucht niemand nach uns?}
{2143}{}{Warum gibt es immer noch keinen Bus?}
{2144}{}{Kann es sein, dass ein Krieg begonnen hat?...}
{2145}{}{}
{2146}{}{Ich werde den Bastard mit *allen* Mitteln aufhalten}
{2147}{}{notwendig. Und selbst wenn sie mir meinen Dienstausweis abnehmen,}
{2148}{}{werde ich es nicht dabei belassen.}
{2149}{}{**END-DISK**}

# Item list
# GVAR_PIPBOY_LIST_CARAVAN_ITEMS
{3000}{}{Liste der vom Karawanenhändler bestellten Gegenstände.}
{3001}{}{}
{3002}{}{  * Vorschlaghammer}
{3003}{}{  * Gecko-Fell (beliebig)}
{3004}{}{  * Schaufel}
{3005}{}{  * Erste-Hilfe-Kasten}
{3006}{}{  * Signalrakete (3 Stk.)}
{3007}{}{  * Seil}
{3008}{}{  * Leere Feldflasche (2 Stk.)}
{3009}{}{  * Metallschrott }
{3010}{}{  * Gummistiefel}
{3011}{}{  * Schraubenschlüssel}
{3012}{}{  * Waffenteile}
{3013}{}{}
{3014}{}{Diese Sachen müssen unbedingt schnell besorgt werden,}
{3015}{}{denn in drei Tagen bricht die Karawane auf.}
{3016}{}{**END-DISK**}

# Free space
{4000}{}{--LEER--}
{4001}{}{**END-DISK**}

# Hawthorne: Report on deserters
# GVAR_HOWTHORNE_DSK_DESERTIRES (GVAR_HOLODISK_MB_LEVEL_3)
{5000}{}{}
{5001}{}{Dieses Dokument enthält einen Bericht über einen Fall}
{5002}{}{von Massendesertion.}
{5003}{}{}
{5004}{}{Wie die Kommission festgestellt hat, beschlagnahmte eine Gruppe}
{5005}{}{von Militärangehörigen Ausrüstung und Waffen aus den Lagern von }
{5006}{}{Hawthorne und kämpfte sich anschliessend aus dem}
{5007}{}{Stützpunktgelände hinaus. Der Grund, der die}
{5008}{}{Soldaten zu einem solchen Verbrechen trieb, war Panik,}
{5009}{}{angeblich ausgelöst durch die Freigabe von Informationen}
{5010}{}{über den bevorstehenden Atomkrieg.}
{5011}{}{}
{5012}{}{Die Deserteure nahmen ihre Familien und ihren persönlichen Besitz}
{5013}{}{mit. Es wurde festgestellt, dass sich die Gruppe im Bunker}
{5014}{}{mit dem Codenamen "Wind des Krieges" versteckte.}
{5015}{}{Dieser Testbunker befindet sich in der Nähe der Stadt}
{5016}{}{Pahrump. Er wurde zur Erprobung von Baumaterialien errichtet,}
{5017}{}{die später im Vault-Tec-Bunkernetzwerk verwendet wurden.}
{5018}{}{Anschliessend wurde er für Ausbildungszwecke der Militärabteilung}
{5019}{}{des Stützpunkts umgerüstet.}
{5020}{}{Die Koordinaten des Bunkers liegen bei.}
{5021}{}{}
{5022}{}{Der Bericht ist auf den 22. Oktober 2077 datiert.}
{5023}{}{**END-DISK**}

# Free space
{6000}{}{--LEER--}
{6001}{}{**END-DISK**}

# Gov. vault: Entries from Stapleton's diary
# GVAR_HOLODISK_ENCLAV_DIARY (GVAR_HOLODISK_SIERRA_EXP_LOG)
{7000}{}{Aufzeichnungen aus dem Tagebuch von Mr. Stapleton}
{7001}{}{}
{7002}{}{(Die Einträge wurden während mehrerer Jahre im Bunker}
{7003}{}{in unregelmässigen Abständen verfasst. Sie}
{7004}{}{haben die interessantesten Stellen festgehalten.)}
{7005}{}{}
{7006}{}{**END-PAR**}
{7007}{}{9. Juli 2077}
{7008}{}{Die Tür ist verschlossen, der Vault versiegelt. Die Leute haben}
{7009}{}{gemischte Gefühle dabei. Einige neigen eindeutig zu}
{7010}{}{Klaustrophobie, Krampfanfällen und dazu, durch die}
{7011}{}{Korridore zu rennen. Dr. Bayham ist mit der Arbeit}
{7012}{}{mit solchen Idioten völlig überfordert. Nach einem}
{7013}{}{Nervenzusammenbruch verliess der Vizepräsident den}
{7014}{}{Speisesaal mit nasser Hose. Er versucht allen einzureden,}
{7015}{}{es sei verschüttete Nuka-Cola gewesen. übrigens hat sie}
{7016}{}{angefangen, seinen Anzug zu zerfressen. Woraus besteht der bloss?}
{7017}{}{}
{7018}{}{15. Juli 2077}
{7019}{}{Die Lage hat sich allmählich beruhigt. Der Präsident ordnete an,}
{7020}{}{in der Mitte des Rasens gegenüber dem Speisesaal}
{7021}{}{das Geräusch eines Bachs einzuschalten. Jetzt ist es dort schön}
{7022}{}{friedlich.}
{7023}{}{}
{7024}{}{10. Aug. 2077}
{7025}{}{Alle haben sich gut an ihre Zimmer gewöhnt und}
{7026}{}{wollen nicht mehr raus. Niemand kümmert sich um irgendetwas}
{7027}{}{ausser um sich selbst. Eine Ausnahme sind unsere Wachen -}
{7028}{}{die armen Kerle müssen jeden Tag übungen}
{7029}{}{im Fitnessraum durchstehen. Man sagt, Private McKinley habe sich geweigert,}
{7030}{}{zum Training aus dem Bett zu kommen. Dafür}
{7031}{}{kürzte der Sergeant seine Nuka-Cola-Ration. Was für eine brutale}
{7032}{}{Strafe.}
{7033}{}{}
{7034}{}{10. Sept. 2077}
{7035}{}{Nuka-Cola bringt die Leute dazu, öfter zu rülpsen und färbt}
{7036}{}{ihre Zungen, aber niemand macht sich auch nur im Entferntesten}
{7037}{}{Sorgen, denn alle haben ihren Spass damit.}
{7038}{}{Ein Wettbewerb um den lautesten Rülpser hat begonnen.}
{7039}{}{Private McKinley liegt derzeit in Führung.}
{7040}{}{}
{7041}{}{12. Sept. 2077. Obwohl Private McKinley im Wettbewerb etwas}
{7042}{}{zurückgefallen ist, sagen alle,}
{7043}{}{sein Rülpser sei zwar nicht der lauteste, aber am}
{7044}{}{volltönendsten. Aus der Bevölkerung wird ein Musikerteam zusammengestellt,}
{7045}{}{das nur spielen und singen wird mit}
{7046}{}{Rülpser mit unterschiedlichen Frequenzen. Ich glaube, ich passe}
{7047}{}{perfekt in die Tenorstimme.}
{7048}{}{}
{7049}{}{18. Sept. 2077. Verdammt! Heute wurde eine allgemeine Warnung}
{7050}{}{herausgegeben: Rülpskonzerte sind von nun an verboten,}
{7051}{}{weil bei diesem Nuka-Cola-Verbrauch bald nichts mehr}
{7052}{}{im Vault übrig bleibt.}
{7053}{}{Wie schade. Dabei waren die ersten Auftritte der Rülps-}
{7054}{}{sänger so erfolgreich. Wie sollten wir jetzt leben,}
{7055}{}{ohne ihre unvergesslichen Kompositionen? ...}
{7056}{}{}
{7057}{}{20. Sept. 2077. Private McKinley hatte einen}
{7058}{}{neuen Wettbewerb im Sinn! Spucken aus grosser Entfernung!}
{7059}{}{Verdammt, das ist eine tolle Idee! Hoffentlich wird wenigstens}
{7060}{}{der nicht verboten!}
{7061}{}{}
{7062}{}{21. Sept. 2077.}
{7063}{}{Private McKinley wurde Opfer seiner eigenen Idee.}
{7064}{}{Als er versuchte, die Kappe eines Stifts auszuspucken, fiel sie}
{7065}{}{dem Private in die Luftröhre, und}
{7066}{}{er erstickte. Doktor Bayham sagt, der}
{7067}{}{Fall sei einzigartig und in seiner Praxis noch nie vorgekommen.}
{7068}{}{Er weigerte sich, die Kappe herauszuholen. Arme Kappe ... Ich meine,}
{7069}{}{armer Private.}
{7070}{}{}
{7071}{}{27. Sept. 2077. Ohne Private McKinley ist es}
{7072}{}{langweilig geworden. Deshalb ordnete der Aufseher an,}
{7073}{}{sonntags Feiern im Speisesaal zu veranstalten.}
{7074}{}{Cool. Hoffentlich geben sie uns Nuka-Cola.}
{7075}{}{}
{7076}{}{30. Sept. 2077. Auf der Feier trank der Sergeant zu viel}
{7077}{}{Cola und verprügelte den Vizepräsidenten. Der Grund war}
{7078}{}{ein Streit darüber, wessen Rülpser cooler sei - der Vize-}
{7079}{}{präsident sagte, seiner klinge voller, und der}
{7080}{}{Sergeant behauptete, sein Rülpser wirke besser.}
{7081}{}{Es kam zu einer Prügelei.}
{7082}{}{}
{7083}{}{31. Sept. 2077. Der Sergeant und der Vizepräsident}
{7084}{}{sitzen im Speisesaal wie alte Freunde.}
{7085}{}{Wahrscheinlich sind sie das auch.}
{7086}{}{**END-PAR**}
{7087}{}{*********}
{7088}{}{}
{7089}{}{5. Aug. 2078. Im Vault geht das Gerücht um, dass}
{7090}{}{Der Krieg hat nie stattgefunden. Natürlich dürfen normale Leute}
{7091}{}{das nicht wissen, aber ... was, wenn wir die ganze}
{7092}{}{Zeit hier umsonst verbracht haben, während die Welt}
{7093}{}{da draussen weiterlebte? Wir müssen einen Rat einberufen,}
{7094}{}{also gab uns der Aufseher eine Erklärung.}
{7095}{}{}
{7096}{}{13. Aug. 2078. Der Aufseher verkündete plötzlich,}
{7097}{}{dass der Cola-Synthesizer kaputtgegangen ist. Tja,}
{7098}{}{nun müssen wir ohne unsere liebste Unterhaltung auskommen.}
{7099}{}{Die Leute geraten langsam in Panik.}
{7100}{}{}
{7101}{}{15. Aug. 2078. Die Leute hatten das Warten satt und}
{7102}{}{fingen an, eine Petition an den Präsidenten zu schreiben,}
{7103}{}{damit der Cola-Automat schnell repariert wird.}
{7104}{}{}
{7105}{}{20. Aug. 2078. Aus Langeweile begannen die Bewohner,}
{7106}{}{Petitionen an den Präsidenten zu schreiben.}
{7107}{}{Ich schrieb, dass ich die Wände blau gestrichen haben will, und}
{7108}{}{der Nachbar bat um ein Seil und ein Stück Seife.}
{7109}{}{Ich frage mich, wofür er die braucht.}
{7110}{}{}
{7111}{}{27. Aug. 2078.}
{7112}{}{Verdammt noch mal! Warum wurde die Bitte meines Nachbarn}
{7113}{}{erfuellt, aber meine nicht? Ich bin so enttäuscht!}
{7114}{}{Was machen diese verdammten Bürokraten in ihrem verdammten}
{7115}{}{Büro! Vielleicht sollte ich noch eine Petition schreiben?}
{7116}{}{}
{7117}{}{**END-PAR**}
{7118}{}{}
{7119}{}{*********}
{7120}{}{}
{7121}{}{5. Feb. 2086. Die Lage ist einfach beschissen! Der}
{7122}{}{Vault ist in zwei Lager gespalten. Die einen verteidigen den}
{7123}{}{Sergeant und seine Politik des "Stillhaltens", während}
{7124}{}{die anderen den Vizepräsidenten unterstützen, der dazu aufruft,}
{7125}{}{den Vault zu verlassen und denen zu helfen, die nach dem}
{7126}{}{Krieg da draussen Hilfe brauchen. Ich glaube nicht, dass es sich lohnt,}
{7127}{}{unsere Technologie mit all diesen radioaktiven}
{7128}{}{Zombies zu teilen. Bisher haben sich nur der Aufseher und}
{7129}{}{der Präsident nicht dazu geäussert, was sie}
{7130}{}{darüber denken.}
{7131}{}{}
{7132}{}{12. März 2086. Die Kämpfe wurden so heftig, dass}
{7133}{}{sie den Speisesaal bald in zwei Lager teilen!}
{7134}{}{}
{7135}{}{13. März 2086. Es ist vorbei. Das ist das Ende. Heute,}
{7136}{}{nach massivem Cola-Konsum ein gewaltiger Kampf }
{7137}{}{zwischen Fraktionen ausbrach. Sie kämpften mit blossen}
{7138}{}{Händen, manche mit Stühlen. Warum sind die Leute so wütend?}
{7139}{}{Hat das vielleicht etwas mit Nuka-Cola zu tun?}
{7140}{}{}
{7141}{}{14. März 2086. Fraktionen, von wegen!}
{7142}{}{Die waren wieder betrunken! Haben sich WIEDER geprügelt!}
{7143}{}{Der Sergeant hat sogar den Präsidenten selbst getroffen! Mit einem Stuhl,}
{7144}{}{direkt am Kopf! Und plötzlich fiel ihm der Kopf ab!!}
{7145}{}{Und was passiert jetzt? ...}
{7146}{}{}
{7147}{}{15. März 2086. Die Fraktionen schlossen einen temporären Waffenstillstand, um}
{7148}{}{das Problem zu lösen, dass der Präsident nicht da ist.}
{7149}{}{Genauer gesagt wird das Problem nur vom Aufseher und}
{7150}{}{Doktor Bayham gelöst. Sie beschlossen, den abgerissenen Kopf}
{7151}{}{an ein paar Kabel anzuschliessen, damit}
{7152}{}{sie versuchen konnten, ihn wiederzubeleben. Gott weiss, wer}
{7153}{}{das nötig hatte, aber die Idee ist ziemlich interessant!}
{7154}{}{}
{7155}{}{20. März 2086. Wer hätte das gedacht?! Heute war }
{7156}{}{die grosse feierliche Inbetriebnahme des Präsidenten-}
{7157}{}{kopfes. Und die ersten Worte, die der Kopf von sich gab,}
{7158}{}{als die Schalter umgelegt wurden, waren: "Verdammte Arschlöcher! }
{7159}{}{Wo ist meine Puppe?!" Sie wurde im Büro des Präsidenten}
{7160}{}{gefunden, dann beruhigte sich der Kopf. Ich sage, alle}
{7161}{}{hatten wohl eine etwas andere Reaktion erwartet.}
{7162}{}{}
{7163}{}{**END-PAR**}
{7164}{}{1. April 2087. Der Kopf ist unerträglich!}
{7165}{}{Wie sich herausstellt, hat er die ganze Zeit die Computersysteme}
{7166}{}{des Vaults unter Kontrolle gehalten. Jetzt gibt es makabre Witze}
{7167}{}{aus den Lautsprechern, und unsere Donutmaschine}
{7168}{}{backt Donuts in Form einer Galgenschlinge.}
{7169}{}{Es wird Zeit, etwas zu unternehmen! Wir haben zu viel Angst, um}
{7170}{}{unsere Zimmer zu verlassen!}
{7171}{}{}
{7172}{}{3. Juli 2087. Das reicht! Dieser haarlose, körperlose}
{7173}{}{hässliche Freak hat sogar den Aufseher verärgert! Morgen}
{7174}{}{berufen wir eine Ratssitzung ein, um zu entscheiden, was wir}
{7175}{}{mit diesem abgerissenen Stück Kopf machen sollen.}
{7176}{}{}
{7177}{}{4. Juli 2087. Der Rat ... hat keine Entscheidung getroffen.}
{7178}{}{Wie sich herausstellt, können wir den Kopf nicht einfach abschalten.}
{7179}{}{Der Kopf ist so sehr mit dem Netzwerk des Vaults verwachsen,} 
{7180}{}{dass er irgendwie sogar die Stromversorgung kontrolliert.}
{7181}{}{Lange Rede, kurzer Sinn: Ich weiss nicht, wie lange noch,} 
{7182}{}{aber die Frage bleibt offen.}
{7183}{}{}
{7184}{}{10. Jan. 2090. Die letzten Jahre sassen wir in}
{7185}{}{unseren Zimmern und hatten kaum Kontakt zur Aussenwelt. Die} 
{7186}{}{dummen Witze des Kopfes wurden durch direkte Drohungen ersetzt.}
{7187}{}{Er beschwert sich ständig, dass man ihm nicht zuhört,} 
{7188}{}{ihn nicht frisiert und ihm nicht die Fersen kratzt.}
{7189}{}{Der Ort wurde gefährlich. Der Kopf hat einen Nervenzusammenbruch,} 
{7190}{}{so wie wir alle. Manche sagen, er kontrolliert sogar}
{7191}{}{ein wenig die Sicherheitstürme.}
{7192}{}{Ich frage mich, ob das stimmt.}
{7193}{}{}
{7194}{}{**END-PAR**}
{7195}{}{15. Jan. 2090. Wir gehen.}
{7196}{}{Leb wohl, Donutmaschine.}
{7197}{}{Leb wohl, Nuka-Cola.}
{7198}{}{Ich werde dich nie vergessen.}
{7199}{}{}
{7200}{}{**END-DISK**}

# Gov. vault: Medical report on the head
# GVAR_HOLODISK_ENCLAV_MED (GVAR_HOLODISK_SIERRA_MED_LOG)
{8000}{}{}
{8001}{}{Bericht über den Geisteszustand des Kopfes des Präsidenten}
{8002}{}{}
{8003}{}{Ziel: Gründe für die Aggression des Kopfes herausfinden.}
{8004}{}{Leitender Arzt: Solomon, Dr. med.}
{8005}{}{**END-PAR**}
{8006}{}{Wir haben uns mit dem Kopf des ehemaligen}
{8007}{}{Präsidenten unterhalten. Die Schlussfolgerungen sind ernüchternd. Nach}
{8008}{}{einigen Jahren ohne natürliche soziale Kontakte}
{8009}{}{hat der Kopf die Kontrolle über seine Fantasien verloren und}
{8010}{}{hält seine Gedanken häufig für die Wirklichkeit. Der}
{8011}{}{Kopf neigt dazu, sich mit seiner}
{8012}{}{Puppe zu identifizieren. Neben dem Mangel an Kontakten}
{8013}{}{liegen die Gründe für die Aggression in seinem von Anfang an}
{8014}{}{übermässig ausgeprägten Egozentrismus.}
{8015}{}{Der Kopf verlangt Aufmerksamkeit und wählt, wenn er nicht}
{8016}{}{genug davon bekommt, immer radikalere und}
{8017}{}{härtere Massnahmen, um zu bekommen, was er will.}
{8018}{}{Ich befürchte, dass der Kopf in wenigen Jahren zu einem}
{8019}{}{unkontrollierbaren Psychopathen werden könnte.}
{8020}{}{}
{8021}{}{Eine langfristige psychologische Behandlung ist erforderlich.}
{8022}{}{}
{8023}{}{**END-DISK**}

# Gov.vault: exodus
# GVAR_HOLODISK_ENCLAV_ISHOD (GVAR_HOLODISK_SIERRA_EVACUATION)
{9000}{}{Diese Diskette enthält verschiedene Informationen}
{9001}{}{vom Hauptterminal des Regierungstresors,}
{9002}{}{darunter Aufzeichnungen über die letzten Tage vor dem "Exodus" -}
{9003}{}{dem Ereignis, das seine Bewohner dazu brachte, den Tresor zu verlassen.}
{9004}{}{ }
{9005}{}{Im Wesentlichen wurde der Tresor für die}
{9006}{}{Regierungselite der Vereinigten Staaten gebaut, einschliesslich}
{9007}{}{des Präsidenten, seiner Familie und des Dienstpersonals. Der Tresor}
{9008}{}{war mit modernster Technik ausgestattet,}
{9009}{}{doch das half seinen Bewohnern trotzdem nicht. Nachdem}
{9010}{}{der Tresor versiegelt worden war, ereignete sich ein Vorfall mit dem Präsidenten -}
{9011}{}{sein Kopf wurde abgerissen. Der Kopf wurde}
{9012}{}{anschliessend im Labor von einem ortsansässigen Arzt wiederbelebt, angeblich,}
{9013}{}{um, wie er sagte, "das gesamte geheime Wissen zu bewahren,}
{9014}{}{das der Präsident besass". Doch mit der Zeit wurde er}
{9015}{}{zu egozentrisch, wenn man ihm zu lange keine Aufmerksamkeit schenkte,}
{9016}{}{was auch zu seinem zunehmend missbräuchlichen}
{9017}{}{Verhalten beitrug. Spott und Scherze über die Bewohner}
{9018}{}{des Tresors wichen Drohungen gegen ihre Gesundheit}
{9019}{}{und ihr Leben. Die Empfehlung, den Kopf abzuschalten, kam}
{9020}{}{viel zu spät; irgendwie gelang es dem Kopf, das Netzwerk}
{9021}{}{und die Robotik des Tresors zu unterwerfen, einschliesslich seiner}
{9022}{}{Verteidigungssysteme. Jeder weitere Fehltritt hätte}
{9023}{}{den Bewohnern des Tresors das Leben kosten können. Am}
{9024}{}{Ende beschloss man, den Ort zu verlassen, mit der}
{9025}{}{Absicht, zum staatlichen Reserve-Stützpunkt}
{9026}{}{auf einer Bohrinsel weit draussen im Ozean überzusiedeln. Am}
{9027}{}{Tag der Abreise versuchte der Kopf jedoch,} 
{9028}{}{die Flüchtlinge aufzuhalten.}
{9029}{}{}
{9030}{}{Eine Gruppe Sicherheitsleute beschloss, den}
{9031}{}{Speichertank des Kopfes zu zerstören, doch als sie ins}
{9032}{}{Labor gelangten, entbrannte ein Kampf mit den vom Kopf gesteuerten}
{9033}{}{Sicherheitstürme, bei dem alle Wachen}
{9034}{}{getötet wurden. Danach versuchte der Kopf,}
{9035}{}{jeden zu töten, den die Geschütztürme erreichen konnten. Dennoch gelang es den meisten}
{9036}{}{Bewohner schafften es in Sicherheit, darunter der derzeitige}
{9037}{}{Präsident. Sie konnten die wertvollsten}
{9038}{}{Geräte und Maschinen mitnehmen und fliehen.}
{9039}{}{}
{9040}{}{Der Vault wurde verlassen.}
{9041}{}{}
{9042}{}{Seltsamerweise enthält die Holodisk Informationen}
{9043}{}{über die umfangreiche Nutzung der verbliebenen}
{9044}{}{Systeme des Vaults nach dem Exodus. Den Protokollen zufolge}
{9045}{}{geschah dies über ein einziges Konto - "Bayham J.".}
{9046}{}{}
{9047}{}{**END-DISK**}

# Jay Kukish's message
# GVAR_HOWTHORNE_DSK_BAIKER_MSG (GVAR_SIERRA_MISSION_HOLODISK)
{10000}{}{Ich hätte nicht erwartet, dass du so weit kommst.}
{10001}{}{Wenn doch, dann war das kein Zufall.}
{10002}{}{Du wirst dich sehr anstrengen müssen, um mich zu treffen.}
{10003}{}{Dringe in den Militärhangar V9 im Norden ein und finde}
{10004}{}{den Funkstörsender. Um das Risiko zu senken, schlage ich vor,}
{10005}{}{den Strom im Untergeschoss abzuschalten.}
{10006}{}{Installiere anschliessend den Störsender in der Radaranlage}
{10007}{}{im zweiten Stock des Garnisonsgebäudes}
{10008}{}{und warte nahe dem Ausgang auf mich.}
{10009}{}{Das ist alles.}
{10010}{}{**END-DISK**}

# Case with docs from radio station
# GVAR_SHAIEN_RADIO_KEISHOLODISK (GVAR_SIERRA_GNN_HOLODISK)
{11000}{}{Der Koffer aus dem Radiosender enthält einen dicken}
{11001}{}{Stapel Dokumente und Disketten. Es mag wie ein}
{11002}{}{Haufen nutzloser Muell aussehen, wäre da nicht}
{11003}{}{die Geheimhaltung. Ein Teil der Informationen ist}
{11004}{}{zudem verschlüsselt, was ebenfalls zu denken gibt.}
{11005}{}{}
{11006}{}{Offenbar war der Radiosender in Lovelock einer}
{11007}{}{der wenigen wichtigen Punkte für die Militärfunkübertragung.}
{11008}{}{Er hielt die Verbindungen zwischen dem Oberkommando,}
{11009}{}{den Militärbasen, dem Vault-Netzwerk und}
{11010}{}{Labors. Sie konnten auch von hier angezapft werden.}
{11011}{}{}
{11012}{}{Unter den Unterlagen entdecken Sie plötzlich}
{11013}{}{einige überwachungsberichte über Vault 8:}
{11014}{}{Aufzeichnungen externer und interner Kommunikation,}
{11015}{}{abgefangene Daten aus Computersystemen usw.}
{11016}{}{Das Vault stand unter strenger Aufsicht des}
{11017}{}{Militärs - Informationen wurden direkt an den}
{11018}{}{Militärstützpunkt Hawthorne übermittelt.}
{11019}{}{}
{11020}{}{Es wird einige Zeit dauern, alles zu entziffern}
{11021}{}{Dokumentation, aber bereits jetzt ist klar, dass sie}
{11022}{}{für deine Stadt von grossem Wert sein kann.}
{11023}{}{**END-DISK**}

# Wind of War's history
# GVAR_WIND_HISTORY_HOLODISK (GVAR_ELRON_HOLODISK)
{12000}{}{Kurze Geschichte von Wind of War}
{12001}{}{}
{12002}{}{(Aufgezeichnetes Gespräch mit Militärpersonal)}
{12003}{}{}
{12004}{}{Wir alle stammen von Menschen ab, die den Krieg}
{12005}{}{in einem sicheren Vault überstanden haben. Unsere Vorfahren waren eine}
{12006}{}{Eliteeinheit vom Militärstützpunkt Hawthorne.}
{12007}{}{Zumindest hat man uns das erzählt.}
{12008}{}{Als es in Nevada niemanden mehr zu retten gab,}
{12009}{}{suchten sie in einem Prototyp-Vault nicht weit von hier Schutz.}
{12010}{}{Der Vault trug den Codenamen "Wind of War",}
{12011}{}{er wurde speziell zu Testzwecken für}
{12012}{}{Materialien und Technologien des Vault-Netzwerks gebaut.}
{12013}{}{}
{12014}{}{}
{12015}{}{Die Zeit verging, und wir wurden geboren, noch immer}
{12016}{}{im Vault eingeschlossen. Als seine Ressourcen zur Neige gingen,}
{12017}{}{mussten wir nach draussen gehen und ein neues Leben beginnen,}
{12018}{}{im Kampf um einen Platz an der Sonne.}
{12019}{}{General Wesker brachte die Lage unter Kontrolle.}
{12020}{}{Wir liessen uns in diesen Ruinen nieder und bauten sie wieder auf,}
{12021}{}{brachten Waffen und Technik aus Hawthorne mit.}
{12022}{}{Dann sprengten wir den Vault und begannen, hier zu leben.}
{12023}{}{Doch es stellte sich heraus, dass wir nicht besonders gut}
{12024}{}{für den Ackerbau geeignet waren, aber überleben mussten. Also}
{12025}{}{lebten wir grösstenteils von der Jagd. Diese Gegend}
{12026}{}{ist weitgehend Wüste, daher war es nicht einfach, uns}
{12027}{}{mit Nahrung zu versorgen. Dann kamen die "Aliens",}
{12028}{}{und es wurde besonders schwer.}
{12029}{}{Also griff der General auf eine andere Einnahmequelle zurück:}
{12030}{}{Wir wurden zu Beschützern kleiner Siedlungen und}
{12031}{}{zu einem Transitpunkt für Karawanen.}
{12032}{}{Auch wenn es langsam ging, begann sich unser Leben einzurenken.}
{12033}{}{**END-DISK**}


# robot-stagecoacher memory card
# GVAR_NEW_RENO_DILIZHAS_ROBOTMODUL (GVAR_RESERVED_VAR13)
{13000}{}{}
{13001}{}{}
{13002}{}{Hier sind wichtige Informationen zusammengestellt, die aus dem DVR}
{13003}{}{eines Wachroboters entschlüsselt wurden, der eine Postkutsche}
{13004}{}{von Salt Lake City nach New Reno eskortierte.}
{13005}{}{}
{13006}{}{Wie sich herausstellt, haben die Biker nicht angegriffen}
{13007}{}{Postkutsche - sie wurde von Mitgliedern der Crew gebaut.}
{13008}{}{Genau dieselben Mitglieder kehrten später in die}
{13009}{}{Stadt zurück und schoben es der Bikergang in die Schuhe.}
{13010}{}{}
{13011}{}{Diese Information wird ganz sicher mehrere Leute}
{13012}{}{gleichzeitig interessieren.}
{13013}{}{}
{13014}{}{**END-DISK**}

# Armstrong
# GVAR_LIST_ARMSTRONG_PANIHIDA (GVAR_VAULT_CITY_DESIGNER_NOTES)
{14000}{}{Artikel aus der Zeitung "Washington Post":}
{14001}{}{}
{14002}{}{Der Tod von Louie Armstrong löste eine wahre Flut}
{14003}{}{aufrichtigster und tiefster Anteilnahme aus.}
{14004}{}{Viele Zeitungen, nicht nur in den USA, sondern auch in anderen}
{14005}{}{Länder veröffentlichten auf ihren Titelseiten Artikel über seinen Tod}
{14006}{}{auf den Titelseiten.}
{14007}{}{}
{14008}{}{Die Trauerfeier war sehr würdevoll und wurde im Fernsehen}
{14009}{}{im ganzen Land übertragen.}
{14010}{}{Am 8. Juli war der Leichnam zum feierlichen Abschied}
{14011}{}{in der Ausbildungshalle der Nationalgarde aufgebahrt,}
{14012}{}{die auf persönliche Anordnung des Präsidenten der Vereinigten Staaten}
{14013}{}{für diesen Zweck zur Verfügung gestellt worden war. Eine Erklärung}
{14014}{}{von Präsident Nixon lautet:}
{14015}{}{}
{14016}{}{"Mrs. Nixon und ich teilen die Trauer von Millionen}
{14017}{}{Amerikanern über den Tod von Louis Armstrong.}
{14018}{}{Einer der Wegbereiter einer amerikanischen Kunstform,}
{14019}{}{ein freier und eigenständiger Geist und}
{14020}{}{ein weltweit berühmter Künstler,}
{14021}{}{bereicherten sein grosses Talent und sein grossartiger Geist}
{14022}{}{unser aller Leben und machten es lebenswerter."}
{14023}{}{**END-PAR**}
{14024}{}{**END-DISK**}

# Notes of the trapped man
# Author of text- Kerb (Alexander Agafontsev)
# GVAR_HOLODISK_SALT_MINIVAULT (GVAR_NCR_SPY_HOLO_DOWNLOAD)
{15000}{}{}
{15001}{}{(Ein schlichtes Notizbuch mit einem abgenutzten Lederumschlag.}
{15002}{}{Die ersten Seiten sind mit sauberer, feiner}
{15003}{}{Handschrift beschrieben, doch je weiter man liest, desto}
{15004}{}{schwerer kann man die abgehackten, unregelmässigen Buchstaben auf}
{15005}{}{blutbefleckten, zerknitterten Seiten entziffern.)}
{15006}{}{}
{15007}{}{}
{15008}{}{}
{15009}{}{Tag 1}
{15010}{}{}
{15011}{}{Verdammt noch mal, ich hab's geschafft! Könnt ruhig}
{15012}{}{kämpfen, euch sogar gegenseitig auffressen -  }
{15013}{}{Ich setz hier drin aus. Ja,}
{15014}{}{ich hab meine Lektion gelernt. Ich weiss, wie man wartet ...}
{15015}{}{Ich möchte, dass du das ganz genau weisst, Watkins!}
{15016}{}{Und du, Kurowski, du verdammter Pshek ...}
{15017}{}{Schon gut, ich werde euch nicht vergessen. Keinen von euch.}
{15018}{}{Ich komme vorbei und pisse auf eure Gräber!}
{15019}{}{Trotzdem habe ich den letzten Gang nach Essen nie gemacht ...}
{15020}{}{Aus irgendeinem Grund habe ich beschlossen, nicht mehr rauszugehen.}
{15021}{}{Vorerst jedenfalls. Ich habe keine Angst. Bin nur vorsichtig.}
{15022}{}{Ich habe mich wieder beruhigt, alles läuft gut,}
{15023}{}{so wird es ab jetzt laufen ...}
{15024}{}{}
{15025}{}{Tag 2}
{15026}{}{}
{15027}{}{Meistens schlafen und den Bauch vollschlagen.}
{15028}{}{Kann nicht lange lesen - Licht ist für mich immer noch}
{15029}{}{eine nicht erneuerbare Ressource.}
{15030}{}{Habe draussen ein paar Schüsse gehört. Hat es angefangen?}
{15031}{}{}
{15032}{}{Tag 3}
{15033}{}{}
{15034}{}{Scheisse! Sieht aus, als wären sie da aus ihren Ketten losgekommen!!}
{15035}{}{Den ganzen Tag Schüsse und Explosionen, Schreie ...}
{15036}{}{Habe gehört, einer von ihnen wurde direkt vor meine Tür gekippt ...}
{15037}{}{Er bruellt ohne Unterlass, wie Vieh in einer Schlachterei.}
{15038}{}{Verdammt, kann ihn nicht endlich jemand erledigen ...}
{15039}{}{}
{15040}{}{Tag 4}
{15041}{}{}
{15042}{}{Endlich ist er still. Tot oder nur ohnmächtig ...}
{15043}{}{Interessanterweise habe ich mich irgendwie ein bisschen an den armen}
{15044}{}{Kerl gewöhnt - habe sogar ein wenig mit ihm geredet ...}
{15045}{}{Einseitig natürlich, hehe ...}
{15046}{}{Jetzt ist es still. Sehr still ...}
{15047}{}{}
{15048}{}{Tag 5}
{15049}{}{}
{15050}{}{Ich hätte nie gedacht, was für eine Qual es ist -}
{15051}{}{in vollständiger Stille zu sein ...}
{15052}{}{Rede ständig mit mir selbst, klappere mit Ausrüstung,}
{15053}{}{nur um für einen weiteren Moment davor zu fliehen ...}
{15054}{}{}
{15055}{}{Tag 6}
{15056}{}{}
{15057}{}{Bin nachts aufgewacht, weil es sich anfühlte, als wäre jemand}
{15058}{}{in der Nähe ... Licht vertreibt die Dunkelheit nicht,}
{15059}{}{es drängt sie nur in entferntere Ecken ...}
{15060}{}{Nein, das kann nicht sein, ich bin hier ganz allein ...}
{15061}{}{Allein in der Dunkelheit ... Ha-ha ...}
{15062}{}{}
{15063}{}{Tag 7}
{15064}{}{}
{15065}{}{Kein Licht mehr ...}
{15066}{}{Die Stille bohrt mir das Hirn heraus, die Dunkelheit drückt}
{15067}{}{Augen ... Immer noch kein Laut! Genau das,}
{15068}{}{worauf es wartet ... Was? Ich bin hier allein, oder?}
{15069}{}{Ich bin verwirrt ... Kann noch nicht schlafen ...}
{15070}{}{Die Uhr ist nutzlos - die Zeit steht still ...}
{15071}{}{Wie ist es wohl - eine Ewigkeit lang nicht zu schlafen?}
{15072}{}{}
{15073}{}{Tag ???}
{15074}{}{}
{15075}{}{Weniger Essen, Wasser, Leben ...}
{15076}{}{Die Stille ist schon in mir ...}
{15077}{}{Sie fängt an, meine Eingeweide zu verschlingen ...}
{15078}{}{Langsam ...}
{15079}{}{Wenn ich nicht schlafe, kann Es mir nichts anhaben}
{15080}{}{wenn ich nicht schlafe ... Oder wenn}
{15081}{}{ich keinen Laut von mir gebe. Was, wenn Es nicht allein ist? ...}
{15082}{}{}
{15083}{}{keine Zeit mehr}
{15084}{}{}
{15085}{}{Kein Essen mehr ...}
{15086}{}{Ich komme nicht raus - die Tür ist von Trümmern blockiert ...}
{15087}{}{Oder das Schloss ist kaputt ...}
{15088}{}{Oder jemand wartet dort auf mich ...}
{15089}{}{Ich kann nicht raus, ich kann nicht, darf nicht raus,}
{15090}{}{Ich darf nicht........... So sieht mein Tag aus, Baby!!!}
{15091}{}{Ich werd sie austricksen!!! Sie können mich nicht fressen,}
{15092}{}{wenn ich mich selbst auffresse!!! Ha-ha!!}
{15093}{}{Sie haben nicht damit gerechnet, dass ich mich mit}
{15094}{}{Schmerzmitteln vollstopfe, mit jeder Menge davon! ...}
{15095}{}{Sie haben mir den Geist ausgetrieben, aber ich habe es trotzdem}
{15096}{}{geschafft, mir die Augen auszustechen ...}
{15097}{}{Leck mich, Dunkelheit!}
{15098}{}{Mir die linke Hand bis zum Ellbogen abgetrennt ...}
{15099}{}{Nur damit ich nicht vergesse, Blut zu trinken ...}
{15100}{}{Die Stille bekommt nicht einen einzigen Tropfen ...}
{15101}{}{Ohren und Zunge sind als Nächstes dran ...}
{15102}{}{... Sie gelten bestimmt als Delikatesse ...}
{15103}{}{... Also sollen sie mich doch beissen!! ...}
{15104}{}{**END-DISK**}


# Officer's audio logs in Area 51
# Author of text- Kerb (Alexander Agafontsev)
# GVAR_ZONA_SOLDAT_AUDIO_HOLODISK (GVAR_NCR_HISTORY_HOLO_DOWNLOAD)
{16000}{}{Audioaufzeichnungen des Officers}
{16001}{}{}
{16002}{}{[Eine selbstsichere, raue Stimme ist zu hören}
{16003}{}{durch Hintergrundrauschen]}
{16004}{}{}
{16005}{}{**END-PAR**}
{16006}{}{}
{16007}{}{3. August 2077}
{16008}{}{}
{16009}{}{[Das dumpfe Stampfen von Stiefeln auf dem Boden ist leise zu hören;}
{16010}{}{dann folgt der Befehl: "Stillgestanden! Im Laufschritt, Marsch!"}
{16011}{}{Du kannst die Worte nicht gut verstehen, aber es sieht aus, als}
{16012}{}{würden die Schwadronen irgendein Armeelied singen]}
{16013}{}{}
{16014}{}{Also, nach dem morgendlichen Drill hat unser dreisterniger}
{16015}{}{Stellvertreter Gottes auf Erden, behangen mit Generalsstreifen,}
{16016}{}{mich damit erfreut, dass ich statt meines geplanten}
{16017}{}{Chinaurlaubs, fast}
{16018}{}{totgeprügelten Gooks Gesellschaft zu leisten,}
{16019}{}{den zweiten Zug nach "Area 51" anführen werde. Warum sie denken,}
{16020}{}{dass lokale Wachen allein nicht reichen, ist mir schleierhaft.}
{16021}{}{Und als wäre das noch nicht genug, hat man uns ein paar zivile}
{16022}{}{Wissenschaftler angehängt - wie heissen die noch gleich...}
{16023}{}{Zeeno... Shmeeno... -logen oder so ähnlich.}
{16024}{}{Einer dieser Arschköpfe bat mich, sie}
{16025}{}{mit Waffen auszurüsten. Da musste ich lachen. Die können nicht mal}
{16026}{}{ihr Ding beim Pinkeln gerade halten, was soll man da von}
{16027}{}{Gewehren erwarten? Na, mal sehen, wie das ausgeht...}
{16028}{}{}
{16029}{}{**END-PAR**}
{16030}{}{}
{16031}{}{14. August 2077}
{16032}{}{}
{16033}{}{Lange Rede, kurzer Sinn - wir sind am Arsch. Lange Rede, lange Rede -}
{16034}{}{wir müssen Aliens bewachen. Und nein, ich hab mich nicht}
{16035}{}{besoffen, bis ich kleine grüne Männchen sehen konnte, obwohl}
{16036}{}{ich stark das Gefühl habe, dass ich das gern würde. Das ist der Spitzname,}
{16037}{}{den die Einheimischen ihnen gegeben haben. Falls das jemandes blödem}
{16038}{}{verdammten Scherz entsprang, dann hat er es richtig gemacht.}
{16039}{}{Als wir ankamen, liess der Sicherheitschef jede}
{16040}{}{Einweisung sausen - er brachte uns einfach zu den Zellen mit diesen}
{16041}{}{Kreaturen. Was für ein genialer Plan.}
{16042}{}{Ich hab tonnenweise Erfahrung gesammelt. Ein Blick in ihr} 
{16043}{}{Maul - und man bekommt sofort Lust,}
{16044}{}{irgendwo in Chinas Kriegsgebieten heldenhafte Taten zu vollbringen,}
{16045}{}{oder zum zweiten Mal die Klippen von Anchorage zu stürmen,}
{16046}{}{nur soll das verdammt viele Meilen von hier entfernt sein.}
{16047}{}{Laut offizieller Version ist ihr Schiff irgendwo hier in der Nähe}
{16048}{}{des Groom Lake abgestürzt.}
{16049}{}{Intelligente Wesen, bla-bla-bla...}
{16050}{}{Was für ein Haufen Scheisse! Wenn du mich fragst, ist das alles}
{16051}{}{durch Experimente irgendwelcher Eierköpfe entstanden, wie}
{16052}{}{die Typen, die hier mit uns hergeschleppt werden. Sieh sie dir nur an,}
{16053}{}{wie sie an diesen Zellen kleben. Forscher, am Arsch...}
{16054}{}{}
{16055}{}{**END-PAR**}
{16056}{}{}
{16057}{}{2. September 2077}
{16058}{}{}
{16059}{}{Die Wissenschaftler gehen mir jetzt schon auf die Nerven. Sie}
{16060}{}{beschweren sich ständig - über die strengen Sicherheitsvorkehrungen,}
{16061}{}{die Eskorte... Ach, und diese Arschlöcher - PFC Jones}
{16062}{}{und Korporal Sterling - haben es geschafft, sich mit}
{16063}{}{Alkohol volllaufen zu lassen... Sterling kriegt jetzt Schwänze statt}
{16064}{}{der Sprüche des Sergeants. McCoy, der Sicherheitschef,}
{16065}{}{hat plötzlich geholfen - er hat uns Kameraaufnahmen gezeigt, auf denen}
{16066}{}{eines dieser Alienmonster vor etwa}
{16067}{}{sechs Monaten ausgebrochen ist. Es wurde zwar erledigt, in die Enge getrieben}
{16068}{}{nahe den versiegelten Räumen in Sektor C (}
{16069}{}{übrigens, warum sind die versiegelt? Gute Frage),}
{16070}{}{aber es hat dort die meisten Sicherheitskräfte abgeschlachtet.}
{16071}{}{Also haben sich alle erst mal beruhigt. Wie lange}
{16072}{}{wird das wohl anhalten?...}
{16073}{}{}
{16074}{}{}
{16075}{}{**END-PAR**}
{16076}{}{}
{16077}{}{10. September 2077}
{16078}{}{}
{16079}{}{Ich mache meine Hausaufgaben. Ich prüfe die Widerstandsfähigkeit dieser}
{16080}{}{Dinger. 5 mm, 7,62 oder sogar 9 mm bringen kaum was -}
{16081}{}{wie Fliegen gegen einen Elefanten, panzerbrechende Munition eingeschlossen.}
{16082}{}{Natürlich zeigen sie eine gewisse Wirkung, aber die Hälfte}
{16083}{}{der Munition des Trupps auf ein einziges Ziel zu verballern, ist definitiv keine}
{16084}{}{gute Wahl. Laser oder Strom - alles dasselbe.}
{16085}{}{Die Grosshirne versuchen es mit Giften und Strahlung,}
{16086}{}{aber bisher ohne sichtbaren Erfolg. Na gut, morgen}
{16087}{}{kommen wir an schwere Waffen ran.}
{16088}{}{übrigens konnte ich etwas Dampf ablassen - einer}
{16089}{}{dieser hiesigen Spitzel versuchte, in mein Tablet einzubrechen.}
{16090}{}{Das ist für ihn ziemlich übel ausgegangen - alle Knochen können}
{16091}{}{schon in ein paar Wochen wieder zusammenwachsen.}
{16092}{}{}
{16093}{}{**END-PAR**}
{16094}{}{12. September 2077}
{16095}{}{}
{16096}{}{Die Sache wurde ein wenig lebhafter. Ich konnte nicht anders}
{16097}{}{Es hat einen mit der Bozar erschossen. Inzwischen ist die beste}
{16098}{}{bewährte Methode der Flammenwerfer. Die Jungs haben}
{16099}{}{eine Menge Spass, sogar ein paar Grosshirne angelockt, die}
{16100}{}{hier herumhängen. Einer meinte, diese Kreaturen sehen uns}
{16101}{}{im Infrarot oder so ähnlich.}
{16102}{}{Wärmebild, thermische Felder, das ganze Zeug...}
{16103}{}{Das ist übrigens die einzige nützliche Information, die wir von}
{16104}{}{diesen Nerds in der ganzen Zeit hier bekommen haben.}
{16105}{}{Und alles scheint normal zu sein, aber...}
{16106}{}{Ich bin nicht gerade leicht zu beeindrucken oder zu erschrecken, aber}
{16107}{}{in letzter Zeit habe ich das Gefühl, als wollte jemand}
{16108}{}{mir den Kopf verdrehen oder so...}
{16109}{}{Vielleicht setzt mir dieser Ort zu?}
{16110}{}{}
{16111}{}{**END-PAR**}
{16112}{}{}
{16113}{}{3. Oktober 2077}
{16114}{}{}
{16115}{}{Einer der Eierköpfe, Hubbard, ist ausgerastet.}
{16116}{}{Er fing an, uns anzuschreien, wir würden}
{16117}{}{eine empfindungsfähige Lebensform zerstören und sollten versuchen,}
{16118}{}{irgendeine Art friedliche Vereinbarung auszuhandeln. Dann}
{16119}{}{fuchtelte er mit diesen albernen Berichten herum... Irgendwie}
{16120}{}{fand er heraus, dass ich russische Vorfahren habe, und nannte}
{16121}{}{mich ein kommunistisches Schwein. Danach traf er seine beste}
{16122}{}{Entscheidung und ging in eine der Zellen. [lacht]}
{16123}{}{Ich kann stolz sagen, dass die Spezialeinheiten}
{16124}{}{dem wissenschaftlichen Fortschritt nicht im Weg standen.}
{16125}{}{Ich glaube, Diplomatie ist heutzutage viel}
{16126}{}{wirksamer als jede Waffe. Liebe und Frieden}
{16127}{}{und so. Beachtet nicht den blutigen Kerl, der Aliens ausweidet,}
{16128}{}{und die Eingeweide überall in seiner Zelle - das muss wohl}
{16129}{}{bei ihnen so Brauch sein. Man sollte sie, na ja,}
{16130}{}{mit Respekt behandeln und so.}
{16131}{}{----}
{16132}{}{Auf Flughöhe 117 entdeckte die UAV eine Art}
{16133}{}{verdächtige Aktivität in ihrem Patrouillengebiet.}
{16134}{}{Morgen untersuchen wir das und bringen zwei Einheiten mit.}
{16135}{}{}
{16136}{}{**END-PAR**}
{16137}{}{}
{16138}{}{19. Oktober 2077}
{16139}{}{}
{16140}{}{Jones wird vermisst. Zusammen mit einem der Wachleute.}
{16141}{}{Diese Basis hat einige "tote Winkel" nahe Sektor C,}
{16142}{}{zu denen der Zugang beschränkt ist. Trotzdem, warum sollten sie}
{16143}{}{da hineingehen? Jetzt laufen wir in Zweiergruppen herum,}
{16144}{}{und patrouillieren den Perimeter...}
{16145}{}{Mein Kopf ist ein verdammtes Chaos. Alle bleiben wachsam...}
{16146}{}{Ein neuer Befehl vom Hauptquartier ist eingetroffen -}
{16147}{}{auf weitere Anweisungen warten...}
{16148}{}{}
{16149}{}{**END-PAR**}
{16150}{}{}
{16151}{}{21. Oktober 2077}
{16152}{}{}
{16153}{}{Irgendetwas ist in die Wachbaracken eingedrungen und}
{16154}{}{hat alle Leute der Schicht abgeschlachtet... Es ist ein}
{16155}{}{Blutbad, vom Boden bis zur Decke, überall zerfetztes Fleisch}
{16156}{}{und Innereien... Die Verbindung zum Hauptquartier ist}
{16157}{}{abgerissen... Die Sicherheitssysteme fallen ständig aus,}
{16158}{}{wir haben teilweise die Kontrolle über die Basis verloren... Jetzt}
{16159}{}{durchkämmen wir den Perimeter mit zwei Einheiten, die}
{16160}{}{verbleibenden zwei halten die Stellung...}
{16161}{}{}
{16162}{}{**END-PAR**}
{16163}{}{}
{16164}{}{22. Oktober 2077}
{16165}{}{}
{16166}{}{[Schüsse aus Waffen grossen und kleinen Kalibers sind zu hören,}
{16167}{}{Explosionen, Schreie, heulende Alarme. Manchmal}
{16168}{}{dringt ein Kreischen durch den ganzen Lärm,}
{16169}{}{das in ein Zischen übergeht]}
{16170}{}{}
{16171}{}{Also, weitere Fragen gibt es keine mehr, aber die Antworten}
{16172}{}{sind auch nicht erfreulich... Dieses Ding, das vor einem halben}
{16173}{}{Jahr getötet wurde, war das Weibchen der}
{16174}{}{Spezies... Irgendwie hat es es geschafft, Eier in den}
{16175}{}{abgeriegelten Anlagen abzulegen, bevor es starb...}
{16176}{}{Als wir die Türen aufbrachen, brach die Hölle los...}
{16177}{}{PFC Irons und Leutnant Parker versengten die erste}
{16178}{}{Welle mit Flammenwerfern, aber dann kamen uns diese Maden}
{16179}{}{von hinten... Ich zerfetzte sie mit Feuerstössen,}
{16180}{}{bis eine von ihnen meine Hand erwischte und}
{16181}{}{sie zerkaute... Ich kam davon, indem ich das Ding erstach...}
{16182}{}{Versteckte mich in irgendeinem Lagerhaus im H-Block...}
{16183}{}{}
{16184}{}{**END-PAR**}
{16185}{}{}
{16186}{}{}
{16187}{}{25. Oktober 2077}
{16188}{}{}
{16189}{}{[Eine Weile ist nur raues Atmen zu hören]}
{16190}{}{}
{16191}{}{Ich bin der Einzige, der noch übrig ist. Aus den Schiessereien wurde Nahkampf,}
{16192}{}{Dann wurde ich bewusstlos geschlagen... jetzt ist alles still...}
{16193}{}{Ich kann mich kaum noch auf den Beinen halten, meine Hand gehorcht mir nicht...}
{16194}{}{Ich habe mich so zugedröhnt, dass ich}
{16195}{}{Halluzinationen sehe... Ich kann nicht klar denken...}
{16196}{}{Ich hoffe nicht auf Rettung - nachdem wir auf eine}
{16197}{}{Antwort auf das Statusmeldesignal verzichtet haben, hätte das Rettungsteam}
{16198}{}{längst hier sein müssen...}
{16199}{}{Aber etwas kann selbst ich noch tun...}
{16200}{}{Mir etwas Cordex spritzen, so viel wie ich}
{16201}{}{hab's geschafft, ... zu klauen}
{16202}{}{Ich will noch mehr von diesen Mistkerlen mitnehmen,}
{16203}{}{also wünscht mir Glück...}
{16204}{}{Einer meiner Vorfahren hat im Zweiten Weltkrieg den ganzen "Tiger"}
{16205}{}{Panzer auf ähnliche Weise zerstört... am}
{16206}{}{Ende ist selbst ein einzelner Spezialkräfteoffizier}
{16207}{}{eine kampffähige Einheit für sich...}
{16208}{}{Also... Operation beginnen!}
{16209}{}{**END-DISK**}


# Free space
{17000}{}{--LEER--}
{17001}{}{**END-DISK**}

# Free space
{18000}{}{--LEER--}
{18001}{}{**END-DISK**}

# Salt Lake city, criminal case 4783
# GVAR_HOLODISK_SALT_RAPORT
{19000}{}{Strafakte Nr. 4783}
{19001}{}{}
{19002}{}{[ Eine Strafakte, ziemlich ramponiert von}
{19003}{}{Nagetiere, Feuchtigkeit und Zeit. Doch ein Teil des Textes}
{19004}{}{war noch immer zu entziffern. ]}
{19005}{}{}
{19006}{}{[ Tagebuch mit Lederhülle und eleganter religionsbezogener}
{19007}{}{Beschriftung. ]}
{19008}{}{}
{19009}{}{Tag I}
{19010}{}{}
{19011}{}{Heute gestand Emily, dass sie ohne Erlaubnis eine Blume aus dem}
{19012}{}{Garten unseres Nachbarn, Herrn Flowers, gepflückt hatte.}
{19013}{}{Wir entschuldigten uns als ganze Familie bei diesem ehrenwerten Mann, und}
{19014}{}{er nahm unsere Entschuldigung wohlwollend an.}
{19015}{}{Wahrend ich dies schreibe, betet Emily inständig zu unserem}
{19016}{}{Herrn um Vergebung. Sie tut es aus freien Stücken, denn}
{19017}{}{der Same des Glaubens ist in ihrer unschuldigen Seele aufgegangen,}
{19018}{}{was mein unerbittliches Herz sehr erfreut...}
{19019}{}{Doch zurück zum Thema! Meine Herde wartet auf ihren}
{19020}{}{Hirten, denn selbst auf den Wiesen des Paradieses ist es}
{19021}{}{uns bestimmt, unermüdlich zu arbeiten, im Namen}
{19022}{}{unseres Herrn!}
{19023}{}{}
{19024}{}{Tag II}
{19025}{}{}
{19026}{}{Bittere Nachrichten erreichten unser kleines Städtchen - Frau Schultzes}
{19027}{}{Sohn, Major Otto Schultz, kam in Gilan ums Leben}
{19028}{}{Provinz ... Ich werde diesen armen Kerl ganz sicher besuchen}
{19029}{}{noch heute Abend.}
{19030}{}{Hoffentlich konnte ich ihr Leid lindern und ihr helfen,}
{19031}{}{sich mit unserem Herrn zu versöhnen ...}
{19032}{}{Warum können die Menschen nicht in Frieden leben? Schliesslich sind wir}
{19033}{}{Brüder in den allsehenden Augen unseres Vaters ...}
{19034}{}{}
{19035}{}{Tag III}
{19036}{}{}
{19037}{}{Der Tag des Gerichts ist gekommen ... Was kürzlich geschah, kann ich}
{19038}{}{nur noch bruchstückhaft in Erinnerung rufen ... Alarmsirenen, wie}
{19039}{}{die Posaunen von Jericho ... Meine arme Mary und Emily,}
{19040}{}{die hastig ihre Habseligkeiten packten ... Eine Massenpanik ...}
{19041}{}{Ein älteres Paar, von vor Angst rasenden Rindern}
{19042}{}{niedergetrampelt ... Bürgersteige, mit Blut bedeckt ... Die Türen zum}
{19043}{}{Familienbunker der Flowers, der fast drei Dutzend Flüchtlingen}
{19044}{}{Asyl gewährte ... Doch an eines}
{19045}{}{erinnere ich mich ganz klar - bevor die überwachungskameras}
{19046}{}{ausfielen, sah ich den Feuerball am}
{19047}{}{Horizont, der sich rasch ausdehnte und gierig die}
{19048}{}{Seelen der armen Lämmer Gottes verschlang ...}
{19049}{}{Und der blendende Lichtblitz ...}
{19050}{}{Unser Untergang kam vom Himmel, wie ein}
{19051}{}{Hollenfeuer, das aus dem Boden hervorbrach ...}
{19052}{}{}
{19053}{}{Tag IV}
{19054}{}{}
{19055}{}{Allmächtiger Herr, gib mir Kraft ... Mary, meine süsse}
{19056}{}{Mary ... Mr. Flowers sagte, der Bunker biete}
{19057}{}{nicht genug Schutz vor der Strahlung ...}
{19058}{}{Die Medikamente, die wir nahmen, lösten bei ihr schwere allergische}
{19059}{}{Reaktionen aus ... Ich sehe noch immer ihre geschwollenen, mit Flecken}
{19060}{}{bedeckten Hände, die nach mir greifen ...}
{19061}{}{Augen, vor Schmerz verschwommen ...}
{19062}{}{Ich höre unheimliche Schreie ...}
{19063}{}{Warum ist unser Herr so grausam zu mir?}
{19064}{}{Sie braucht mich so sehr in ihren letzten Momenten, doch}
{19065}{}{meine Kräfte schwinden ...}
{19066}{}{}
{19067}{}{Tag V}
{19068}{}{}
{19069}{}{Gelobt sei unser Herr! Oh, warum war ich nur so blind ...}
{19070}{}{Ich kasteite mich und stärkte meinen Geist durch}
{19071}{}{Gebete, und die Offenbarung kam über mich! Alles,}
{19072}{}{was geschah, ist der Grössere Plan unseres Schöpfers,}
{19073}{}{alle leidenden Seelen in den Himmel aufsteigen zu lassen! Der Blitz,}
{19074}{}{der mich beinahe blendete, war das Licht der Perlentore}
{19075}{}{des Himmels, die sich für alle Rechtschaffenen}
{19076}{}{und Gläubigen öffneten! Und wir wurden in dieses Fegefeuer gelockt}
{19077}{}{von den Dienern Satans, die uns mit}
{19078}{}{falschen Versprechen von Sicherheit verführten, entgegen}
{19079}{}{dem Willen unseres Vaters... Mary, ich weiss, dass du}
{19080}{}{im Himmel auf mich wartest, doch ich bin der Hirte}
{19081}{}{der Lämmer unseres Gottes, und ich habe noch unerledigte}
{19082}{}{Dinge auf dieser bösen, sündigen Erde zu tun... }
{19083}{}{Dennoch wird sich unsere Tochter dir bald anschliessen, ganz gleich,}
{19084}{}{wie sehr es mich betrübt, mich von ihr zu trennen...}
{19085}{}{}
{19086}{}{Tag VI}
{19087}{}{}
{19088}{}{Heute öffnete ich die Tore, damit das Licht unseres}
{19089}{}{Schöpfers, von unwissenden Narren "Strahlung" genannt, auf diesen}
{19090}{}{verfluchten Ort scheinen kann. Der Satanstück, verkleidet}
{19091}{}{als Mr. Flowers, wollte mich aufhalten, doch die Feueraxt in meiner}
{19092}{}{Hand hackte den kreischenden Boten Satans in Stücke, wie ein}
{19093}{}{flammendes Schwert des Erzengels.}
{19094}{}{Oh ja, viele von ihnen starben an jenem Tag durch meine Hand...}
{19095}{}{Es gibt keine Nahrung mehr, doch mit der Macht unseres Herrn}
{19096}{}{vereinte ich mich mit ihrem Fleisch und Blut, das mir}
{19097}{}{besser schmeckte als jeder Wein...}
{19098}{}{Doch Mary, das Wichtigste! Unser süsses und }
{19099}{}{liebenswertes Kind ist auf dem Weg zu dir!}
{19100}{}{Aus irgendeinem Grund wehrte sie sich hartnäckig, als}
{19101}{}{ich den letzten Atem aus ihrem sterblichen Leib presste...}
{19102}{}{Vielleicht hätte ich das Blut von meinem Gesicht wischen}
{19103}{}{und vorher meine Kleidung säubern sollen?}
{19104}{}{}
{19105}{}{Tag VII}
{19106}{}{}
{19107}{}{Ich bin hier fertig, doch es gibt noch so viele arme Seelen,}
{19108}{}{die ich zu den Perlentoren des Himmels schicken muss...}
{19109}{}{Mein Fleisch verändert sich unter dem Einfluss}
{19110}{}{unseres Herrn, was einige Unannehmlichkeiten mit sich bringt...}
{19111}{}{Aber ich glaube - es ist alles zum Besten!}
{19112}{}{Freut euch, ihr Gerechten! Ihr Ungläubigen, erzittert!}
{19113}{}{Denn ich komme euch holen...}
{19114}{}{}
{19115}{}{[Fragmente von Berichten zur Tatortuntersuchung]}
{19116}{}{}
{19117}{}{Untersuchung begonnen: 19:1...}
{19118}{}{Untersuchung beendet...}
{19119}{}{}
{19120}{}{...Einstöckiges Backsteingebäude...}
{19121}{}{Raumgrösse innen: 6,5 m x ...}
{19122}{}{Mann, kaukasischer Herkunft... Mit dem Kopf nach unten an der}
{19123}{}{Westwand gekreuzigt... Linkes Bein teilweise gehäutet...}
{19124}{}{Mehrere Bissspuren im Gesicht, am Hals und im Bauchbereich...}
{19125}{}{Frau... Kopf fehlt... Der Art der Wunde nach zu urteilen,}
{19126}{}{wurde er wahrscheinlich abgerissen...}
{19127}{}{}
{19128}{}{Untersuchung...}
{19129}{}{}
{19130}{}{...Wiese nordwestlich von...}
{19131}{}{Pfähle, etwa 2 Meter hoch... In Form eines}
{19132}{}{Kreuzes aufgestellt... Männer und Frauen... Aufgespiesst...}
{19133}{}{Das Geschlecht einiger Opfer liess sich wegen schwerer}
{19134}{}{Verletzungen und fehlender Körperteile nicht feststellen...}
{19135}{}{Auf unverletzter Haut sind einige Inschriften zu sehen...}
{19136}{}{Wahrscheinlich Latein...}
{19137}{}{}
{19138}{}{Am Tatort sichergestellte Beweisstücke:}
{19139}{}{1. Holz-Kruzifix...}
{19140}{}{2. Buch mit Ledereinband...}
{19141}{}{[überraschend gut erhaltene Postkarte mit einer}
{19142}{}{nicht gerade bekleideten Filmdiva eines bestimmten Genres.}
{19143}{}{Die Rückseite ist mit makelloser}
{19144}{}{Kalligraphie beschrieben:]}
{19145}{}{}
{19146}{}{"Guten Tag, Sheriff Crouch! Ich möchte Sie darauf}
{19147}{}{aufmerksam machen, dass ich mich zusammen mit Detective Hastings}
{19148}{}{auf die Suche nach unserem John Dö begebe. Die Akten}
{19149}{}{halfen uns, seinen mutmasslichen Aufenthaltsort zu ermitteln,}
{19150}{}{und auch festzustellen, dass er wohl bald wieder auf die Jagd}
{19151}{}{gehen wird. Wir haben beschlossen, nicht auf Ihre Truppe}
{19152}{}{zu warten, bis sie vom Rotten Crag zurückkehrt.}
{19153}{}{Ich nehme an, du wirst lautstark fragen:}
{19154}{}{Und warum sollte sich irgendein Priester in diese Angelegenheit einmischen?}
{19155}{}{(natürlich wirst du dich weniger höflich ausdrücken}
{19156}{}{und dabei überhaupt nicht elegant sein).} 
{19157}{}{Nun, was soll ich sagen ...}
{19158}{}{Der arme Mann war einst mein Glaubensbruder,}
{19159}{}{sehr eifrig darin, denen zu helfen, die litten.}
{19160}{}{Und dann, als er selbst derjenige wurde, der}
{19161}{}{Hilfe brauchte ... Auch wenn es spät kommt, möchte ich}
{19162}{}{ihm trotzdem helfen, in Frieden zu ruhen.}
{19163}{}{}
{19164}{}{}
{19165}{}{}
{19166}{}{"Er wird jede Träne aus ihren Augen wischen, und dann}
{19167}{}{wird es keinen Tod mehr geben, keine Trauer, kein Weinen}
{19168}{}{und keinen Schmerz mehr, denn die alte Ordnung ist vergangen."}
{19169}{}{}
{19170}{}{                                  Rev. McClaine}
{19171}{}{}
{19172}{}{P.S. Und um Himmels willen, verschwende nicht das ganze}
{19173}{}{Papier auf Zigarettenpapier! Stell dir nur vor, du müsstest}
{19174}{}{einen Brief schreiben, vielleicht den letzten, auf das Bild}
{19175}{}{eines sündigen Mädchens (und nicht einmal}
{19176}{}{besonders attraktiv, muss ich sagen!). Aber wenn ich deine}
{19177}{}{Vorlieben bedenke, wäre das wohl deine}
{19178}{}{bevorzugte Wahl. Sollte ich also nicht}
{19179}{}{heil zurückkehren, wird mein Assistent dich zu zehn Jahren Busse}
{19180}{}{verdonnern. Es liegt also in deinem eigenen Interesse, für unseren}
{19181}{}{Erfolg zu beten."}
{19182}{}{**END-DISK**}


# Commercial holodisk of stagecoach
# GVAR_HOLODISK_DILIZHANS_INFO -- GVAR_HOLODISK_ENCLAVE_WORD
{20000}{}{}
{20001}{}{Also, du hast beschlossen, mit dem Verkauf von}
{20002}{}{Perlen und Feuerwasser an die Cheyenne-Wilden Geld zu machen? Oder willst} 
{20003}{}{du in Vegas ein neues Leben anfangen, wegen Problemen}
{20004}{}{mit einem gewissen Sheriff (jeder weiss,}
{20005}{}{wen ich meine), hast aber zu viel Angst, die Einöde zu durchqueren,}
{20006}{}{wegen der wilden Bestien und}
{20007}{}{der Raider mit vereisten Köpfen?}
{20008}{}{Nun, was soll ich sagen - du hast recht, unser}
{20009}{}{gesegnetes Land ist nicht gerade der beste Ort für einen Spaziergang. Aber}
{20010}{}{heute ist dein Glückstag, meine Herren! Onkel Jö und}
{20011}{}{der "Nevada Express" schützen deinen verlausten Hintern vor}
{20012}{}{Schikanierung von Menschen und Nichtmenschen aller Schattierungen}
{20013}{}{und Farben! 1000 Dollar übrig? Reicht gerade so!}
{20014}{}{(Ausserdem sind wir jederzeit verhandlungsbereit!)}
{20015}{}{}
{20016}{}{1. Wer seid ihr? Was zum Teufel ist eine Postkutsche?}
{20017}{}{}
{20018}{}{Wir sind ein Team von Logistikprofis und}
{20019}{}{darin, denen ordentlich den Arsch aufzureissen, die unseren}
{20020}{}{geschätzten Kunden schaden wollen. Manche Unternehmen sehen in euch}
{20021}{}{nur potenzielles Sargmaterial, aber wir}
{20022}{}{sehen in euch ein potenzielles Mitglied unserer starken und}
{20023}{}{eingeschworenen Familie!}
{20024}{}{}
{20025}{}{2. Hmm, ist es wirklich so sicher mit euch in der Nähe?}
{20026}{}{}
{20027}{}{Kommt in eines unserer Buros und überzeugt euch selbst vom}
{20028}{}{Auftreten und der Ausrüstung unserer Leute! Wir wagen}
{20029}{}{bescheiden zu behaupten: Wenn Jesus selbst eine Reise ins}
{20030}{}{ödland antreten wollte, hätte er ganz sicher den}
{20031}{}{"Nevada Express" gewählt! Gekreuzigt würde dann jemand anderes,}
{20032}{}{aber nicht er.}
{20033}{}{}
{20034}{}{3. Und wie lange seid ihr schon im Geschäft?}
{20035}{}{}
{20036}{}{Lange genug, dass die meisten unserer Konkurrenten zu}
{20037}{}{Staub zerfallen sind. Schon 2050 pflügten die Karawanen unserer}
{20038}{}{Gründerväter durch die Weiten jedes Bundesstaates.}
{20039}{}{Natürlich ist unser Markt heute nicht mehr ganz so}
{20040}{}{gross, aber die Qualität unserer Dienste hat sich}
{20041}{}{enorm verbessert.}
{20042}{}{}
{20043}{}{4. Apropos Grösse: Wie weit und wohin}
{20044}{}{fahren eure Karawanen?}
{20045}{}{}
{20046}{}{Wir haben Buros im glänzenden Vegas, in der}
{20047}{}{Stadt der Kontraste - Reno - und in Salt Lake mit seiner}
{20048}{}{unvergleichlichen Atmosphäre des Niedergangs. Unsere Karawanen fahren}
{20049}{}{regelmässig und ununterbrochen zwischen ihnen hin und her, wie ein Uhrwerk.}
{20050}{}{Und wenn ihr nett fragt, halten wir extra für euch}
{20051}{}{am Wind des Krieges mit seinen Soldaten oder}
{20052}{}{nahe der Siedlung der rothäutigen Cheyenne.}
{20053}{}{}
{20054}{}{5. Genau das, was ich brauche! Aber reicht mein Geld?..}
{20055}{}{}
{20056}{}{Ihr werdet nirgends einen kundenfreundlicheren Ansatz finden}
{20057}{}{des Nevada-Wastelands - 1000 Dollar und startklar!}
{20058}{}{Ausserdem vergessen wir nie Gefallen, die man uns erwiesen hat,}
{20059}{}{und sind bereit, unseren Freunden einen guten Rabatt}
{20060}{}{zu gewähren.}
{20061}{}{}
{20062}{}{6. Ihr seid am Zug - wann brechen wir auf?}
{20063}{}{}
{20064}{}{Wir brechen am 1., 11. und 21. eines jeden}
{20065}{}{Monats auf. Nachzügler sind nicht willkommen, egal}
{20066}{}{aus welchen Gründen; ob ihr in einem Bordell oder in einer Kirche}
{20067}{}{festgehangen habt - euer Problem.}
{20068}{}{**END-PAR**}
{20069}{}{**END-DISK**}


# Elron Bible
# GVAR_HOLODISK_ENCLAVE_ATOMIC
{21000}{}{--LEER--}
{21001}{}{}
{21002}{}{**END-PAR**}
{21003}{}{**END-DISK**}
