{100}{}{Held (männlich)}
{101}{}{}
{200}{}{Heldin}
{201}{}{}
{300}{}{Bürger von Vault 8}
{400}{}{Bürger von Vault 8}
{500}{}{Radskorpion}
{501}{}{Ein kleiner mutierter Skorpion.}
{600}{}{Radskorpion}
{601}{}{Ein mutierter Skorpion.}
{700}{}{Todeskralle}
{701}{}{Eine junge Todeskralle.}
{800}{}{Todeskralle}
{801}{}{Eine junge Todeskralle.}
{900}{}{Hund}
{901}{}{Ein Hund, vermutlich ein Mischling.}
{1000}{}{Brahmin}
{1001}{}{Eine zweiköpfige Mutantenkuh.}
{1100}{}{Ratte}
{1101}{}{Eine gewöhnliche grosse Ratte.}
{1200}{}{Gottesanbeterin}
{1201}{}{Eine mutierte Gottesanbeterin.}
{1300}{}{Sergeant Graves}
{1400}{}{Doc}
{1500}{}{Richard Moro}
{1600}{}{Sporenpflanze}
{1601}{}{Eine fleischfressende Pflanze.}
{1700}{}{Hübscher Sklave}
{1800}{}{Gutaussehender Sklave}
{1900}{}{Gesunder Sklave}
{2000}{}{Gesunder Sklave}
{2100}{}{Starker Sklave}
{2200}{}{Starker Sklave}
{2300}{}{Kampfschwacher Sklave}
{2400}{}{Kampfschwacher Sklave}
{2500}{}{Schlauer Sklave}
{2600}{}{Schlauer Sklave}
{2700}{}{Gewöhnlicher Sklave}
{2800}{}{Gewöhnlicher Sklave}
{2900}{}{Anna}
{3000}{}{Härter Schläger}
{3100}{}{Härter Schläger}
{3200}{}{Nahkampfschläger}
{3300}{}{Nahkampfschläger}
{3400}{}{Flinker Schläger}
{3500}{}{Flinker Schläger}
{3600}{}{Schütze}
{3700}{}{Schütze}
{3800}{}{Schwer bewaffneter Schläger}
{3900}{}{Schwer bewaffneter Schläger}
{4000}{}{Härter Wachmann}
{4100}{}{Härter Wachmann}
{4200}{}{Nahkampf-Wachmann}
{4300}{}{Nahkampf-Wachmann}
{4400}{}{Flinker Wachmann}
{4500}{}{Flinker Wachmann}
{4600}{}{Wachmann mit Schusswaffe}
{4700}{}{Wachmann mit Schusswaffe}
{4800}{}{Schwer bewaffneter Wachmann}
{4900}{}{Schwer bewaffneter Wachmann}
{5000}{}{Waise (männlich)}
{5100}{}{Waise (weiblich)}
{5200}{}{Kind (männlich)}
{5300}{}{Kind (weiblich)}
{5400}{}{Versager}
{5500}{}{Versager}
{5600}{}{Schlechter Händler}
{5700}{}{Schlechter Händler}
{5800}{}{Durchschnittlicher Händler}
{5900}{}{Durchschnittlicher Händler}
{6000}{}{Meisterhändler}
{6100}{}{Meisterhändler}
{6200}{}{Jemand}
{6300}{}{Schwacher Bauer}
{6400}{}{Schwacher Bauer}
{6500}{}{Durchschnittlicher Bauer}
{6600}{}{Durchschnittlicher Bauer}
{6700}{}{Starker Bauer}
{6800}{}{Starker Bauer}
{6900}{}{Entflohener Häftling}
{7000}{}{Schwacher Nahkampf-Wachmann}
{7100}{}{Schwacher Wachmann mit Schusswaffe}
{7200}{}{Schwacher Wachmann mit Schusswaffe}
{7300}{}{Reparaturroboter}
{7400}{}{Reparaturroboter Mark II}
{7500}{}{Robohirn}
{7600}{}{Schwebender Augen-Bot}
{7700}{}{Wachroboter}
{7800}{}{Wachroboter Mark II}
{7900}{}{Robohirn}
{8000}{}{Kleiner Gecko}
{8100}{}{Zäher kleiner Gecko}
{8200}{}{Wilder Hund}
{8201}{}{Ein verwilderter Mischlingshund.}
{8300}{}{Goldgecko}
{8400}{}{Todeskralle}
{8500}{}{Todeskrallenbrut}
{8600}{}{Zäher Goldgecko}
{8700}{}{übliches Ziel}
{8800}{}{Gepanzertes Ziel}
{8900}{}{John Cassidy}
{9000}{}{üblicher Typ}
{9100}{}{Sergeant}
{9200}{}{Bürger}
{9300}{}{Mama}
{9400}{}{Bürger der Oberschicht}
{9500}{}{Fallensteller}
{9600}{}{Fallensteller}
{9700}{}{Sulik}
{9800}{}{Hinterwäldler}
{9900}{}{Hinterwäldler}
{10000}{}{Hinterwäldler}
{10100}{}{Leuchtender Ghul}
{10200}{}{Reaktor-Ghul}
{10300}{}{Wache des Reaktors}
{10400}{}{Eli}
{10500}{}{Einheimischer der Müllhalde}
{10600}{}{Das Gehirn}
{10700}{}{Freak}
{10800}{}{Harrelson}
{10900}{}{Jay Kukish}
{11000}{}{Maulwurfsratte}
{11100}{}{Grosse Maulwurfsratte}
{11200}{}{Schweinratte}
{11300}{}{Zahe Schweinratte}
{11400}{}{Schwaches Brahmin}
{11401}{}{Ein zweiköpfiges Mutantentier.}
{11500}{}{A.Pwr.Armor (nicht benutzen)}
{11600}{}{Mutierte Ratte}
{11601}{}{Eine zahe mutierte Ratte.}
{11700}{}{Mutierte Maulwurfsratte}
{11701}{}{Eine zahe mutierte Maulwurfsratte.}
{11800}{}{Mutierte Schweinratte}
{11801}{}{Eine zahe mutierte Schweinratte.}
{11900}{}{Söldner}
{12000}{}{Söldner}
{12100}{}{Anführer der Söldner}
{12200}{}{Held Andro (nicht benutzen)}
{12300}{}{Held Andro (nicht benutzen)}
{12400}{}{Held (männlich) (nicht benutzen)}
{12500}{}{Heldin (nicht benutzen)}
{12600}{}{Held (männlich) (nicht benutzen)}
{12700}{}{Heldin (nicht benutzen)}
{12800}{}{Held (männlich) (nicht benutzen)}
{12900}{}{Heldin (nicht benutzen)}
{13000}{}{Held (männlich) (nicht benutzen)}
{13100}{}{Heldin (nicht benutzen)}
{13200}{}{Held (männlich) (nicht benutzen)}
{13300}{}{Heldin (nicht benutzen)}
{13400}{}{Wache von Vault City}
{13500}{}{Wache von Vault City}
{13600}{}{Cyberhund}
{13700}{}{Polizist}
{13800}{}{Polizist}
{13900}{}{Ausbilder}
{14000}{}{Sklavenhändler-Wache}
{14100}{}{Fatso Jackson}
{14200}{}{Grossmeister-Händler}
{14300}{}{Grossmeister-Händler}
{14400}{}{Gezähmte Todesklaue}
{14500}{}{Stammeshäuptling}
{14600}{}{Roboaugen-Beschützer}
{14700}{}{Kojotenjäger}
{14800}{}{Angesehener Bürger}
{14900}{}{Handlanger der Bloom-Brüder}
{15000}{}{Kleiner}
{15100}{}{Einer der Bloom-Brüder}
{15200}{}{Goris}
{15300}{}{Söldner}
{15400}{}{Söldner}
{15500}{}{Anführer der Söldner}
{15600}{}{Söldner}
{15700}{}{Söldner}
{15800}{}{Anführer der Söldner}
{15900}{}{Ghoul (Standard)}
{16000}{}{Myron}
{16100}{}{Marcus}
{16200}{}{Arzt}
{16300}{}{Davin}
{16400}{}{Miria}
{16500}{}{Junge}
{16600}{}{Mechaniker}
{16700}{}{Handwerker}
{16800}{}{Handwerker}
{16900}{}{Handwerker}
{17000}{}{Türsteher}
{17100}{}{Big Louie}
{17200}{}{Mr. Handy}
{17300}{}{Hardy}
{17400}{}{Nick Hauer}
{17500}{}{Hardys Wache}
{17600}{}{Burton Hickok}
{17700}{}{Test (nicht verwenden)}
{17800}{}{Reaktor-Ghul}
{17900}{}{Ghoul (Standard)}
{18000}{}{Mike}
{18100}{}{Riley}
{18200}{}{Kopfgeldjäger (1-6)}
{18300}{}{Kopfgeldjäger-Anführer (7-12)}
{18400}{}{Soldat}
{18500}{}{Wache}
{18600}{}{Kopfgeldjäger-Anführer (13-18)}
{18700}{}{Wache}
{18800}{}{Kopfgeldjäger (13-18)}
{18900}{}{Kopfgeldjäger-Anführer (19-?)}
{19000}{}{Kopfgeldjäger (19-?)}
{19100}{}{Bess}
{19101}{}{Ein zweiköpfiges, mutiertes Tier.}
{19200}{}{Mann im Mantel}
{19300}{}{Niskigvan, die zerzausten Federn}
{19400}{}{Phil}
{19500}{}{"Super 8"}
{19600}{}{Elender Schurke}
{19700}{}{Kind}
{19800}{}{Ogima, die schwarze Wolke}
{19900}{}{Cheyenne}
{20000}{}{Makozid die Bärentatze}
{20100}{}{Verdächtiger Typ}
{20200}{}{Primitiver Jäger}
{20300}{}{Primitiver Jäger}
{20400}{}{Punk}
{20500}{}{Punk}
{20600}{}{Punk}
{20700}{}{Heilige Frau}
{20800}{}{Nomade - niedrig}
{20900}{}{Nomade - mittel}
{21000}{}{Nomade - niedrig}
{21100}{}{Nomade - mittel}
{21200}{}{Bandit}
{21300}{}{Bandit}
{21400}{}{Bauer}
{21500}{}{Bauer}
{21600}{}{Gottesanbeterin}
{21700}{}{Sklavenhändler}
{21800}{}{Sklavenhändler}
{21900}{}{Wilder Brahmin}
{22000}{}{Dorfbewohner}
{22100}{}{Dorfbewohner}
{22200}{}{Patrouille}
{22300}{}{Patrouille}
{22400}{}{Starker Sklavenhändler}
{22500}{}{Starker Sklavenhändler}
{22600}{}{Psycho}
{22700}{}{Aasjäger}
{22800}{}{Leuchtender Psycho}
{22900}{}{Leuchtender Aasjäger}
{23000}{}{Plünderer}
{23100}{}{Plünderer}
{23200}{}{Wilder}
{23300}{}{Wilder}
{23400}{}{Schmuggler}
{23500}{}{Schmuggler}
{23600}{}{Goldsucher}
{23700}{}{Goldsucher}
{23800}{}{Plünderer}
{23900}{}{Plünderer}
{24000}{}{Säuregecko}
{24100}{}{Zähes Säuregecko}
{24200}{}{Alien}
{24300}{}{Zähes Alien}
{24400}{}{Zähe kleine Todesklaue}
{24500}{}{Zähe Todesklaue}
{24600}{}{Schwimmer}
{24700}{}{Gemeiner Schwimmer}
{24800}{}{Tarantel}
{24900}{}{Gemeiner Zentaur}
{25000}{}{General Wesker}
{25100}{}{Generator}
{25200}{}{Schutzgelderpresser}
{25300}{}{Schutzgelderpresser}
{25400}{}{Söldner}
{25500}{}{Söldner}
{25600}{}{Nachtvolk}
{25700}{}{Zähes Nachtvolk}
{25800}{}{Zäherr Ghul}
{25900}{}{Gangster}
{26000}{}{Räuber}
{26100}{}{Polizist}
{26200}{}{Polizist}
{26300}{}{Marodeur}
{26400}{}{Marodeur}
{26500}{}{Administrator}
{26600}{}{Vorpal-Ratte}
{26700}{}{Ted Bundy}
{26800}{}{Biker}
{26900}{}{Aufseher}
{27000}{}{Mysteriöser Fremder}
{27100}{}{Mysteriöser Fremder}
{27200}{}{Terry Deveraux}
{27300}{}{Frecher Bergarbeiter}
{27400}{}{Leibwächter}
{27500}{}{Mutter-Todeskralle}
{27600}{}{Mitglied der Kings}
{27700}{}{Kutschenfahrer}
{27800}{}{Mormone}
{27900}{}{Mormone}
{28000}{}{Mysteriöser Fremder}
{28100}{}{Mysteriöser Fremder}
{28200}{}{Mysteriöser Fremder}
{28300}{}{Mysteriöser Fremder}
{28400}{}{Mysteriöser Fremder}
{28500}{}{Mysteriöser Fremder}
{28600}{}{Mysteriöser Fremder}
{28700}{}{Mysteriöser Fremder}
{28800}{}{Leibwächter des Präsidenten}
{28900}{}{Todesklauen-Ei}
{29000}{}{Biker Phil}
{29100}{}{Verfolger}
{29200}{}{Erddrache}
{29300}{}{Williamson}
{29400}{}{Tom Parker}
{29500}{}{Ingenieur}
{29600}{}{Kurier aus Vegas}
{29700}{}{Lewis Birch}
{29800}{}{Kind}
{29900}{}{Kind}
{30000}{}{Waffenhändler}
{30100}{}{Verwaltungsangestellter}
{30200}{}{Nelson}
{30300}{}{Der Bauer}
{30400}{}{Der Bauer}
{30500}{}{Frecher Bergarbeiter}
{30600}{}{Marilyn}
{30700}{}{Frecher Bergarbeiter}
{30800}{}{Vortis}
{30900}{}{Kojote}
{31000}{}{Sulik - Stufe 1}
{31100}{}{Sulik - Stufe 2}
{31200}{}{Sulik - Stufe 3}
{31300}{}{Sulik - Stufe 4}
{31400}{}{Sulik - Stufe 5}
{31500}{}{Sulik - Stufe 6}
{31600}{}{Lenny - Stufe 1}
{31700}{}{Lenny - Stufe 2}
{31800}{}{Lenny - Stufe 3}
{31900}{}{Goris - Stufe 1}
{32000}{}{Goris - Stufe 2}
{32100}{}{Goris - Stufe 3}
{32200}{}{Goris - Stufe 4}
{32300}{}{Goris - Stufe 5}
{32400}{}{Goris - Stufe 6}
{32500}{}{Myron - Stufe 1}
{32600}{}{Myron - Stufe 2}
{32700}{}{Myron - Stufe 3}
{32800}{}{Myron - Stufe 4}
{32900}{}{Marcus - Stufe 1}
{33000}{}{Marcus - Stufe 2}
{33100}{}{Marcus - Stufe 3}
{33200}{}{Marcus - Stufe 4}
{33300}{}{Marcus - Stufe 5}
{33400}{}{Cyberdog - Stufe 1}
{33500}{}{Cyberdog - Stufe 2}
{33600}{}{Cyberdog - Stufe 3}
{33700}{}{Cyberdog - Stufe 4}
{33800}{}{Cassidy - Stufe 1}
{33900}{}{Cassidy - Stufe 2}
{34000}{}{Cassidy - Stufe 3}
{34100}{}{Cassidy - Stufe 4}
{34200}{}{Dogmeat}
{34300}{}{Dogmeat - Stufe 1}
{34400}{}{Dogmeat - Stufe 2}
{34500}{}{Dogmeat - Stufe 3}
{34600}{}{Dogmeat - Stufe 4}
{34700}{}{Dogmeat - Stufe 5}
{34800}{}{Dogmeat - Stufe 6}
{34900}{}{Robobrain - Stufe 1}
{35000}{}{Robobrain - Stufe 2}
{35100}{}{Robobrain - Stufe 3}
{35200}{}{Robobrain - Stufe 4}
{35300}{}{Robobrain - Stufe 5}
{35400}{}{Ausserirdische Königin}
{35500}{}{Schwarzer Radskorpion}
{35600}{}{Schwarzer Radskorpion}
{35700}{}{Legendärer Skorpion}
{35800}{}{Ripper}
{35900}{}{Plünderer}
{36000}{}{Plünderer}
{36100}{}{Kämpfer}
{36200}{}{Punk}
{36300}{}{Punk}
{36400}{}{Rancho-Wache}
{36500}{}{Rancho-Arbeiter}
{36600}{}{Biker}
{36700}{}{Kleiner}
{36800}{}{Führer}
{36900}{}{Konvoi-Wache}
{37000}{}{Konvoi-Wache}
{37100}{}{Ricardo Bertolini}
{37200}{}{Angesehener Bürger}
{37300}{}{Vic - Stufe 1}
{37400}{}{Vic - Stufe 2}
{37500}{}{Vic - Stufe 3}
{37600}{}{Vic - Stufe 4}
{37700}{}{Vic - Stufe 5}
{37800}{}{Vic - Stufe 6}
{37900}{}{Robobrain - Schimpanse}
{38000}{}{Robobrain - Abnormal}
{38100}{}{Robobrain - Mensch}
{38200}{}{Riesenameise}
{38300}{}{Zähe Riesenameise}
{38400}{}{Pariahund}
{38500}{}{Schwacher Sklavenkämpfer}
{38600}{}{Gesunder Sklavenkämpfer}
{38700}{}{Starker Sklavenkämpfer}
{38800}{}{Mächtiger Sklavenkämpfer}
{38900}{}{Sklavenkämpfermeister}
{39000}{}{Der schwächste Kämpfer im Ring}
{39100}{}{Der stärkste Kämpfer im Ring}
{39200}{}{Mächtiger Kämpfer im Ring}
{39300}{}{Der Meister des Rings}
{39400}{}{Profikämpfer}
{39500}{}{Der Champion des Rings}
{39600}{}{Der Champion des Rings}
{39700}{}{Quartiermeister}
{39800}{}{Der Champion des Rings}
{39900}{}{Der Champion des Rings}
{40000}{}{Der absolute Champion des Rings}
{40100}{}{Herr Chase}
{40200}{}{Bob Neil}
{40300}{}{Ingenieur}
{40400}{}{Wüternder Brahmin}
{40500}{}{Ausbilder}
{40600}{}{Geschäftsmann}
{40700}{}{Hinterwäldler}
{40800}{}{Bishop}
{40900}{}{Machete}
{41000}{}{Besitzer}
{41100}{}{Alter Jed}
{41200}{}{Gerlach}
{41300}{}{Mrs. Wright}
{41400}{}{Solomon}
{41500}{}{Maxson}
{41600}{}{Maxson}
{41700}{}{Kämpfer aus den Slums}
{41800}{}{Madame}
{41900}{}{Madame}
{42000}{}{Herr Luciano}
{42100}{}{Leibwächter}
{42200}{}{Casino-Sicherheit}
{42300}{}{Wache}
{42400}{}{Betriebsleiter}
{42500}{}{Standard-Barkeeper}
{42600}{}{Standard-Barkeeper}
{42700}{}{Boxer 1}
{42800}{}{Boxer 2}
{42900}{}{Boxer 3}
{43000}{}{Boxer 4}
{43100}{}{Mike der Zerfleischer}
{43200}{}{Holyfeld}
{43300}{}{McKneely}
{43400}{}{Ringsprecher}
{43500}{}{Thompson}
{43600}{}{Oberst Night}
{43700}{}{Seelenschnitter}
{43800}{}{Casino-Türsteher}
{43900}{}{Casino-Türsteher}
{44000}{}{Casino-Mädchen}
{44100}{}{Drogendealer}
{44200}{}{Drogendealer}
{44300}{}{Kommandant}
{44400}{}{Miliz}
{44500}{}{Striker}
{44600}{}{Biker}
{44700}{}{Schlampe}
{44800}{}{Schlampe}
{44900}{}{Goldsucher}
{45000}{}{Apotheker}
{45100}{}{Koch}
{45200}{}{Patrick}
{45300}{}{Cowboy}
{45400}{}{Barton}
{45500}{}{Reisender}
{45600}{}{Reisender}
{45700}{}{Händler 1}
{45800}{}{Händler 2}
{45900}{}{Sklavenhändler}
{46000}{}{Sklavenhändler}
{46100}{}{Sklavenhändler}
{46200}{}{Gilmor}
{46300}{}{Neon-Gangster}
{46400}{}{Karawanenhändler}
{46500}{}{Soldat 3}
{46600}{}{Soldat 4}
{46700}{}{Seelenschnitter}
{46800}{}{Präsident}
{46900}{}{Barkeeper}
{47000}{}{Geschütz}
{47001}{}{Dies ist ein automatisches Geschütz mit einer doppelten Plasmakanone.}
{47100}{}{K-9 (Basis)}
{47200}{}{K-9 (Stufe 1)}
{47300}{}{K-9 (Stufe 2)}
{47400}{}{K-9 (Stufe 3)}
{47500}{}{K-9 (Stufe 4)}
{47600}{}{Allgemeine Märkte, Cafes und Nachtclubs}
{47700}{}{Wanamingo-Ei}
{47800}{}{Lo-Pan-Wache}
{47900}{}{Schneidiger Entwickler}
{48000}{}{Autokanone}
{48100}{}{Gecko-Spezialkreatur}
{48200}{}{Sensenmann}
{48300}{}{Präsident}
{48301}{}{Leibwächter des Präsidenten}
{48400}{}{Cheyennes Kind}
