{100}{}{Lederrüstung}
{101}{}{Deine einfache Volllederkleidung. Sorgfältig aus gegerbtem Brahminleder gefertigt.}
{200}{}{Metallrüstung}
{201}{}{Polierte Metallplatten, grob zu einer Rüstung zusammengefügt.}
{300}{}{Powerrüstung}
{301}{}{Eine eigenständige Rüstung mit fortschrittlicher Technologie. Angetrieben von einem Mikrofusionsreaktor, dessen Brennstoff hundert Jahre reicht.}
{400}{}{Messer}
{401}{}{Eine Waffe mit scharfer Klinge zum Schneiden und Stechen.\n Min. ST: 2.}
{500}{}{Schlagstock}
{501}{}{Nicht tödliche Nahkampfwaffe aus Stahl und Gummi, häufig von Polizeieinheiten eingesetzt.\n Min. ST: 3.}
{600}{}{Vorschlaghammer}
{601}{}{Ein grosser Hammer mit langem Stiel. Bei Muskelprotzen sehr beliebt.\n Min. ST: 6.}
{700}{}{Speer}
{701}{}{Eine handgefertigte Stangenwaffe mit rasiermesserscharfer Spitze. Der Schaft ist aus Holz, die Spitze aus bearbeitetem Stahl.\n Min. ST: 4.}
{800}{}{10-mm-Pistole}
{801}{}{Eine automatische 10-mm-Pistole Colt 6520. Bei jedem Abdrücken wird die Waffe automatisch nachgeladen, bis das Magazin leer ist. Einzelfeuer mit der durchschlagskräftigen 10-mm-Patrone.\n Min. ST: 3.}
{900}{}{10-mm-MP}
{901}{}{Maschinenpistole H&K MP9 (Kaliber 10 mm). Eine mittelgrosse MP mit Einzel- und Dauerfeuer.\n Min. ST: 4.}
{1000}{}{Jagdgewehr}
{1001}{}{Ein halbautomatisches Colt-Rangemaster-Gewehr im Kaliber .223. Nur Einzelfeuer.\n Min. ST: 5.}
{1100}{}{Flammenwerfer}
{1101}{}{Ein Flambe-450-Modell, Variante für die Schädlingsjagd. Verspritzt einen kurzen Schwall extrem heisser, entflammbarer Flüssigkeit. Für den ordnungsgemässen Betrieb ist Spezialtreibstoff erforderlich.\n Min. ST: 6.}
{1200}{}{Minigun}
{1201}{}{Eine persönliche Minigun Rockwell CZ53. Ein mehrläufiges Kettengewehr, das 5-mm-Munition mit über 60.000 U/min verschiesst.\n Min. ST: 7.}
{1300}{}{Raketenwerfer}
{1301}{}{Ein Raketenwerfer Rockwell BigBazooka. Mit dem Deluxe-Abzug von 3 Pfund. Verschiesst panzerbrechende oder explosive Raketen.\n Min. ST: 6.}
{1400}{}{Sprengrakete}
{1401}{}{Eine Rakete mit einem grossen Sprengkopf.}
{1500}{}{Plasmagewehr}
{1501}{}{Ein Winchester Model P94 Plasma-Gewehr. Eine Energiewaffe in Industriequalität, die über einen supraleitenden Lauf überhitzte Plasmaladungen abfeuert. Betrieb mit Micro-Fusionszellen.\n Min. ST: 6.}
{1600}{}{Laserpistole}
{1601}{}{Eine Wattz 1000 Laser-Pistole. Ziviles Modell, daher ist die Leistung geringer als bei Militär- oder Polizeiversionen. Verwendet kleine Energiezellen.\n Min. ST: 3.}
{1700}{}{Kampfrüstung}
{1701}{}{Hochtechnologische Rüstung aus fortschrittlichen Schutzpolymeren.}
{1800}{}{Desert Eagle .44}
{1801}{}{Eine uralte Desert-Eagle-Pistole im Kaliber .44 Magnum. Das Interesse an Filmen aus dem späten 20. Jahrhundert machte sie zu einer der beliebtesten Handfeuerwaffen aller Zeiten.\n Min. ST: 5.}
{1900}{}{Stein}
{1901}{}{Ein Stein. Sieht aus wie Granit.\n Min. ST: 1.}
{2000}{}{Brecheisen}
{2001}{}{Ein sehr solides und schweres Stück Metall, speziell dazu entworfen, Hebelkraft auszuüben. Oder Schädel einzuschlagen.\n Min. ST: 5.}
{2100}{}{Schlagring}
{2101}{}{Verstärkter Knüchelschutz, der eigentlich aus Stahl besteht. Er schützt die Hand und verursacht im waffenlosen Kampf mehr Schaden.\n Min. ST: 1.}
{2200}{}{Karawanenkarabiner}
{2201}{}{Ein altes Raubzeuggewehr. Der Lauf ist gekürzt und der Schaft so leicht wie möglich gefertigt. Dadurch ist die Waffe leichter und bequemer, allerdings auf Kosten der Genauigkeit.\n Min. ST: 4.}
{2300}{}{Sturmgewehr}
{2301}{}{Ein AK-112 5-mm-Sturmgewehr. Ein altes Militärmodell, das etwa zur Zeit des Krieges ausser Dienst gestellt wurde. Kann mit den Hochgeschwindigkeits-5-mm-Patronen Einzelschüsse oder Feuerstösse abgeben.\n Min. ST: 5.}
{2400}{}{Plasmapistole}
{2401}{}{Glock-86-Plasmapistole. Entworfen von der Gaston-Glock-KI. Verschiesst eine kleine Ladung überhitzten Plasmas. Betrieb mit einer kleinen Energiezelle.\n Min. ST: 4.}
{2500}{}{Granate (Splitter)}
{2501}{}{Eine gewöhnliche Splittergranate. Enthält eine geringe Menge Sprengstoff; der Behälter selbst bildet den Grossteil der schädigenden Splitter. Explodiert beim Aufprall.\n Min. ST: 3.}
{2600}{}{Granate (Plasma)}
{2601}{}{Eine magnetisch versiegelte Plasma-Abgabeeinheit mit Zündsprengstoff. Erzeugt beim Aufprall eine Druckwelle aus überhitztem Plasma.\n Min. ST: 4.}
{2700}{}{Granate (Impuls)}
{2701}{}{Eine EMP-Granate, die bei der Detonation ein starkes Magnetfeld erzeugt. Wirkt nicht auf biologische Kreaturen. Aufschlagzunder.\n Min. ST: 4.}
{2800}{}{Striker}
{2801}{}{Eine Schrotflinten-Pistolen-Hybridwaffe, entwickelt von einem afrikanischen Ingenieur. Verwendet Patronen im Kaliber 12, die in einen speziellen Zylinder geladen werden. Lässt sich problemlos mit einer Hand bedienen.\n Min. ST: 6.}
{2900}{}{10mm JHP}
{2901}{}{Munition. Kaliber: 10mm, ummantelte Hohlspitzgeschosse}
{3000}{}{10mm AP}
{3001}{}{Munition. Kaliber: 10mm, panzerbrechend.}
{3100}{}{ .44 Magnum JHP}
{3101}{}{Ein Paket Munition im Kaliber .44 Magnum mit Hohlspitzgeschossen.}
{3200}{}{Flammenwerfer-Treibstoff}
{3201}{}{Ein Zylinder mit extrem entzündlichem Flüssigtreibstoff für Flammenwerfer.}
{3300}{}{12 Gauge Magnum}
{3301}{}{Eine Munitionssorte aus der Vorkriegszeit für Schrotflinten. Mit stärkerem Pulver und mehr Schrot als klassische Patronen desselben Kalibers.}
{3400}{}{.223 FMJ}
{3401}{}{Eine Packung Munition im Kaliber .223, Vollmantel.}
{3500}{}{5mm JHP}
{3501}{}{Ein Paket kleiner, leichter Munition. Kaliber: 5mm, ummantelte Hohlspitzgeschosse.}
{3600}{}{5mm AP}
{3601}{}{Ein Paket Kleinkalibermunition. 5mm, panzerbrechend.}
{3700}{}{Rocket AP}
{3701}{}{Eine Rakete mit kleinerer Sprengladung, aber dafür ausgelegt, Panzerplatten zu durchschlagen.}
{3800}{}{Kleine Energiezelle}
{3801}{}{Eine kleine, eigenständige Energiespeichereinheit.}
{3900}{}{Mikrofusionszelle}
{3901}{}{Eine mittelgroße\nEnergieversorgungs-\neinheit. Eigenständiges Fusionskraftwerk.}
{4000}{}{Stimpak}
{4001}{}{Ein Heilmittel. Injiziert sorgt es für die sofortige Heilung kleinerer Wunden.}
{4100}{}{Geld}
{4101}{}{Gesetzliches Zahlungsmittel der ödlandwelt, aus der Vorkriegszeit erhalten. Die Bewohner Nevadas verwenden es derzeit beim Handel, aber wer weiss, wie lange diese Tradition noch bestehen wird?}
{4200}{}{Kühlschrank}
{4201}{}{Ein Kühlschrank. Kein Kühlmittel mehr.}
{4300}{}{Eiskiste}
{4301}{}{Eine Eiskiste alten Stils. Die Scharniere funktionieren einwandfrei.}
{4400}{}{Eiskiste}
{4401}{}{Eine Eiskiste alten Stils. Die Scharniere funktionieren einwandfrei.}
{4500}{}{Wurfmesser}
{4501}{}{Ein Messer, speziell zum Werfen ausbalanciert. Aus Titan gefertigt und laser-geschliffen.\n Min. ST: 3.}
{4600}{}{Cheaters Radio}
{4601}{}{Das ist das Radio von Mr. Cheater.}
{4700}{}{Erste-Hilfe-Kasten}
{4701}{}{Ein kleiner Kasten mit medizinischer Grundausstattung. Verbandszeug, Mullbinden, antiseptisches Spray und mehr.}
{4800}{}{RadAway}
{4801}{}{Eine chemische Lösung, die sich mit radioaktiven Partikeln verbindet und sie durch den Körper schleust. Die Wirkung setzt nur langsam ein.}
{4900}{}{Gegengift}
{4901}{}{Eine Flasche mit selbstgebrautem Gegengift. Eine milchige Flüssigkeit mit treibenden Stücken Radskorpionfleisch.}
{5000}{}{Reservierter Gegenstand}
{5001}{}{Dies ist ein reservierter Gegenstand. NICHT BENUTZEN.}
{5100}{}{Dynamit}
{5101}{}{Ein hochexplosiver Stoff aus Nitroglyzerin und dem aufsaugenden Stoff Kieselgur. Mit Zeitschalter.}
{5200}{}{Geigerzähler}
{5201}{}{Ein Geigerzähler vom Modell C-Radz von Wattz Electronics. Erkennt das Vorhandensein und die Stärke von Strahlungsfeldern.}
{5300}{}{Ultra-Gegengift}
{5301}{}{Packung mit einem starken Gegengift. Wahrscheinlich militärischen Ursprungs.}
{5400}{}{Stealth Boy}
{5401}{}{Ein persönliches Tarnvorrichtungsgerät Stealth Boy 3001 von RobCo. Erzeugt ein modulierendes Feld, das reflektiertes Licht von einer Seite eines Objekts zur anderen überträgt.}
{5500}{}{Filter}
{5501}{}{Ein leistungsstarker Filter zur Reinigung von Grundwasser. Wird in einer Art Spezialausrüstung verwendet.}
{5600}{}{Anti-Raucher}
{5601}{}{Seit einem ganzen Jahrhundert abgelaufene Tabletten für alle, die mit dem Rauchen aufhören wollen. Der Körper des Anwenders wird für kurze Zeit hyperaktiv und der Kopf wird ungewöhnlich klar.}
{5700}{}{---}
{5701}{}{---}
{5800}{}{---}
{5801}{}{---}
{5900}{}{Bewegungsmelder}
{5901}{}{Ein Bewegungsmelder vom Modell C-U von Wattz Electronics. Erkennt mit einem abgestimmten Radarsystem Bewegungen biologischer Materie in mehreren Metern Entfernung.}
{6000}{}{Bücherregal}
{6001}{}{Ein hölzernes Bücherregal.}
{6100}{}{Bücherregal}
{6101}{}{Ein hölzernes Bücherregal.}
{6200}{}{Bücherregal}
{6201}{}{Ein hölzernes Bücherregal.}
{6300}{}{Bücherregal}
{6301}{}{Ein hölzernes Bücherregal.}
{6400}{}{Bücherregal}
{6401}{}{Ein hölzernes Bücherregal.}
{6500}{}{Bücherregal}
{6501}{}{Ein hölzernes Bücherregal.}
{6600}{}{Schreibtisch}
{6601}{}{Ein hölzerner Schreibtisch.}
{6700}{}{Schreibtisch}
{6701}{}{Ein hölzerner Schreibtisch.}
{6800}{}{Kommode}
{6801}{}{Eine hölzerne Kommode.}
{6900}{}{Kommode}
{6901}{}{Eine hölzerne Kommode.}
{7000}{}{Kommode}
{7001}{}{Eine hölzerne Kommode.}
{7100}{}{Mutafrucht}
{7101}{}{Ein seltsames Stück Obst. Ohne Konservierungsstoffe und ohne zusätzliche Lebensmittelfarbe.}
{7200}{}{Bertolinis Koffer}
{7201}{}{Gepanzerter Koffer, mit Leder bezogen, damit er besonders solide wirkt, und mit einem Zahlenschloss gesichert. Darin muss ein sagenhaftes Vermögen stecken.}
{7300}{}{"Ein grosses Buch der Wissenschaft"}
{7301}{}{Ein Wegweiser durch die wissenschaftlichen Wunder unserer Zeit.}
{7400}{}{Lederjacke}
{7401}{}{Eine schwarze, schwere Lederjacke.}
{7500}{}{Werkzeug}
{7501}{}{Klassisches Multifunktionswerkzeug. Eine klappbare Zange mit hohlen Griffen, in denen sich zahlreiche weitere nützliche Werkzeuge verbergen.}
{7600}{}{Deans Elektronik}
{7601}{}{Ein Lehrbuch, in dem der Autor von den Grundlagen der Elektrotechnik zu den grundlegenden Prinzipien des Baus verschiedener elektrischer Geräte übergeht. Auf dem Einband steht: "Für den angehenden jungen Elektriker in jedem von uns!"}
{7700}{}{Elektronischer Dietrich}
{7701}{}{Ein elektronischer Dietrich Wattz Electronics Micromanipulator FingerStuff. Zum überwinden elektronischer Schlösser und Sicherheitsvorrichtungen.}
{7800}{}{Flauschiges Bild}
{7801}{}{Das Bild zeigt eine Sängerin. Offensichtlich sehr alt. Es hat einen Filzbezug, der noch in gutem Zustand ist. Sieht aus, als könnte es wertvoll sein.}
{7900}{}{Leuchtfackel}
{7901}{}{Eine Leuchtfackel. Erzeugt für kurze Zeit Licht. Das Papier ist etwas abgenutzt, ansonsten ist sie in gutem Zustand. Zum Aktivieren die Spitze drehen.}
{8000}{}{Erste-Hilfe-Buch}
{8001}{}{Ein Lehrbuch zu den Grundlagen und zur praktischen Anwendung der Ersten Hilfe.}
{8100}{}{Iguana am Spiess}
{8101}{}{Ein gegarter Iguana, in seiner eigenen Haut geröstet. Geschmacklos und zäh, mit wenig Nährwert. Ausserdem glaubst du nicht, dass er in einer umweltfreundlichen Umgebung gelebt hat.}
{8200}{}{Kubotan-Schlüssel}
{8201}{}{Ein gewöhnlicher Schlüssel, der nach nichts Besonderem aussieht.}
{8300}{}{Schlüssel zum Lagerraum}
{8301}{}{Der Schlüssel eines der Quok-Brüder zum Lagerraum ihres Geschäfts in Salt Lake City.}
{8400}{}{Dietriche}
{8401}{}{Ein Satz Werkzeuge für Schlosser. Enthält alle nötigen Dietriche und Spannwerkzeuge zum öffnen herkömmlicher Stiftzuhaltungsschlösser.}
{8500}{}{Plastiksprengstoff}
{8501}{}{Ein Stück Cordex, einer militärischen Marke für Plastiksprengstoff. Sehr stabil und äusserst zerstörerisch. Mit Zeitschalter.}
{8600}{}{Pfadfinderhandbuch}
{8601}{}{Ein Buch über Methoden und Ideale der Pfadfinderei. Enthält sehr praktische Informationen über das Leben im Freien.}
{8700}{}{Buffout}
{8701}{}{Hochentwickelte Steroide. Solange sie wirken, steigern sie Kraft und Reflexe. Machen stark abhängig.}
{8800}{}{Uhr}
{8801}{}{Eine teure Uhr. Funktioniert zwar nicht richtig, sieht aber immer noch gut aus.}
{8900}{}{Servomotor}
{8901}{}{Leistungsstarker und präziser Motor mit Drehschrittantrieb.}
{9000}{}{Körperpflegeset}
{9001}{}{Supercooles Körperpflegeset in einer Markenblechdose. Zeit, es zum Einsatz zu bringen!}
{9100}{}{Arzttasche}
{9101}{}{Diese braune Tasche enthält Instrumente und Chemikalien, die ärzte für ihre Arbeit verwenden.}
{9200}{}{Skorpionschwanz}
{9201}{}{Der abgetrennte Schwanz eines Radskorpions.}
{9300}{}{Wanze}
{9301}{}{Ein uraltes Gerät zum heimlichen Abhören von Gesprächen.}
{9400}{}{Schrotflinte}
{9401}{}{Eine Winchester Widowmaker, eine doppelläufige Schrotflinte im Kaliber 12. Kurzer Lauf, mit Mahagonigriff. \n Min. ST: 5.}
{9500}{}{Schrotpatronen Kal. 12}
{9501}{}{Schrotmunition. Auf dieser Packung steht: "Schrotpatronen, nicht für Kinder unter 3 Jahren geeignet."}
{9600}{}{Zugangskarte}
{9601}{}{Eine riesige Zugangskarte für eine äusserst mächtige Tür.}
{9700}{}{Symbol}
{9701}{}{Ein Stück polierter Stein mit der Symbolik des Bundesstaates Nevada. Den Stiften auf der Rückseite nach zu urteilen, muss das Symbol irgendwo eingesetzt werden.}
{9800}{}{Gerümpel}
{9801}{}{Teile aus verschiedenen Metallen sowie Harze und Drähte. Vielleicht hilft etwas davon bei Reparaturen.}
{9900}{}{Goldmedaillon}
{9901}{}{Ein wertvolles Goldmedaillon.}
{10000}{}{Radio}
{10001}{}{Ein im Tarnmuster lackiertes Funkgerät Modell 2043B von den netten Leuten bei Wattz Electronics. Nicht funktionsfähig.}
{10100}{}{Feuerzeug}
{10101}{}{Ein silbernes Butanfeuerzeug. In gutem Zustand.}
{10200}{}{"Waffen und Munition"}
{10201}{}{Ein Waffenmagazin. Eine Zeitschrift über den praktischen Gebrauch von Feuerwaffen und gelegentlich voreingenommene Tests.}
{10300}{}{Iguana-Stücke}
{10301}{}{Ein paar Stücke angekohltes Fleisch und Gemüse auf einem Bratspiess. Lecker und nahrhaft, aber wer weiss schon, aus welchen verseuchten Gegenden diese Leguane stammen?}
{10400}{}{Birchs Bericht}
{10401}{}{Eine Menge verschlüsselter Informationen. Auf dem Etikett steht: "An das Zentrum, die Union der Atomarbeiter".}
{10500}{}{Zündschlüssel}
{10501}{}{Zündschlüssel für ein Auto.}
{10600}{}{Nuka-Cola}
{10601}{}{Eine Flasche Nuka-Cola, das aromatisierte Erfrischungsgetränk der postnuklearen Welt. Warm und schal.}
{10700}{}{Kleiderschrank}
{10701}{}{Holzschrank. In relativ gutem Zustand.}
{10800}{}{Tisch}
{10801}{}{Holztisch. In relativ gutem Zustand.}
{10900}{}{Rad-X}
{10901}{}{Mittel gegen Strahlung, das vor dem Kontakt mit Strahlung eingenommen werden sollte. Keine bekannten Nebenwirkungen.}
{11000}{}{Psycho}
{11001}{}{Ein einzigartiges Verabreichungssystem, gefuellt mit seltsamen und unbekannten Chemikalien vermutlich militärischen Ursprungs. Es soll das Kampfpotenzial eines Soldaten steigern.}
{11100}{}{.44 Magnum FMJ}
{11101}{}{Ein Paket Munition im Kaliber .44 Magnum mit Vollmantelgeschoss.}
{11200}{}{Pfeil}
{11201}{}{Ein selbstgemachter Pfeil, wie er beim Dartspiel verwendet wird.\n Min. ST: 1.}
{11300}{}{---}
{11301}{}{---}
{11400}{}{Medaillon}
{11401}{}{Persönliches Medaillon mit eingraviertem Namen und einem Foto im Inneren.}
{11500}{}{Superhammer}
{11501}{}{Ein Superhammer, hergestellt mit der besten verfügbaren Waffentechnologie. Mit kinetischem Energiespeicher für eine höhere Rückstosswirkung.\n Min. ST: 5.}
{11600}{}{Ripper}
{11601}{}{Eine Ripper(tm)-Vibroklinge. Angetrieben von einer kleinen Energiezelle reisst die Kettenklinge ihr Ziel in Stücke.\n Min. ST: 4.}
{11700}{}{9-mm-Pistole}
{11701}{}{Die Pistole ist für 9-mm-Patronen ausgelegt. In ausgezeichnetem Zustand. Ideale Präzision.\n Min. ST: 2.}
{11800}{}{Lasergewehr}
{11801}{}{Ein Wattz-2000-Lasergewehr. Verwendet Mikrofusionszellen für stärkere Laser und einen verlängerten Lauf für grössere Reichweite.\n Min. ST: 6.}
{11900}{}{Bunkerschlüssel}
{11901}{}{Der Schlüssel zum Tor, das zum Reno-Bunker führt.}
{12000}{}{Pumpgun}
{12001}{}{Einst eine sehr beliebte Sportwaffe im Kaliber 12.\n Min. ST: 6.}
{12100}{}{9-mm-Standardmunition}
{12101}{}{Eine Sammlung uralter 9x19-mm-Patronen. Dick eingefettet, um sie vor den Umwelteinflüssen zu schützen. Standardgeschosse.}
{12200}{}{9-mm-Pistole}
{12201}{}{Eine Pistole im Kaliber 9 mm. Noch funktionsfähig, könnte aber eine kleinere Reparatur und eine Reinigung des Mechanismus vertragen.\n Min. ST: 2.}
{12300}{}{Kiste}
{12301}{}{Diese Kiste wurde aus dem Boden ausgegraben.}
{12400}{}{Bier}
{12401}{}{Eine Art selbstgebrautes Bier.}
{12500}{}{Schnaps}
{12501}{}{Selbstgemachtes alkoholisches Getränk.}
{12600}{}{Trinkwasser}
{12601}{}{Lebensspendendes Trinkwasser, von Schmutz und Strahlung gereinigt. Dient zur Behandlung von Krankheiten, Vergiftungen und zur Ersten Hilfe - oder einfach zum Trinken.}
{12700}{}{Seil}
{12701}{}{Eine starke, dicke Leine. Etwa 45 Fuss lang.}
{12800}{}{Fusskiste}
{12801}{}{Eine ganz normale Fusskiste. Bietet Stauraum, steht am Fussende des Bettes und lässt sich abschliessen.}
{12900}{}{Fusskiste}
{12901}{}{Eine ganz normale Fusskiste. Bietet Stauraum, steht am Fussende des Bettes und lässt sich abschliessen.}
{13000}{}{Fusskiste}
{13001}{}{Eine ganz normale Fusskiste. Bietet Stauraum, steht am Fussende des Bettes und lässt sich abschliessen.}
{13100}{}{Fusskiste}
{13101}{}{Eine ganz normale Fusskiste. Bietet Stauraum, steht am Fussende des Bettes und lässt sich abschliessen.}
{13200}{}{Spind}
{13201}{}{Ein Aufbewahrungsbehälter.}
{13300}{}{Spind}
{13301}{}{Ein Aufbewahrungsbehälter.}
{13400}{}{Spind}
{13401}{}{Ein Aufbewahrungsbehälter.}
{13500}{}{Spind}
{13501}{}{Ein Aufbewahrungsbehälter.}
{13600}{}{Spind}
{13601}{}{Ein Aufbewahrungsbehälter.}
{13700}{}{Spind}
{13701}{}{Ein Aufbewahrungsbehälter.}
{13800}{}{Spind}
{13801}{}{Ein Aufbewahrungsbehälter.}
{13900}{}{Spind}
{13901}{}{Ein Aufbewahrungsbehälter.}
{14000}{}{---}
{14001}{}{---}
{14100}{}{---}
{14101}{}{---}
{14200}{}{Dynamitstange}
{14201}{}{Kleine, aber mächtige Dynamitladung mit Zündschnur. Viel Spass beim Knallen, Baby!}
{14300}{}{Scharfschützengewehr}
{14301}{}{Ein DKS-501-Scharfschützengewehr. Hervorragende Fernkampfwaffe. Ursprünglich für .308 ausgelegt, wurde dieses Exemplar auf das weiter verbreitete Kaliber .223 umgerüstet.\n Min. ST: 5.}
{14400}{}{Super-Stimpak}
{14401}{}{Ein fortschrittliches Heilmittel. Sehr mächtig. Super-Stimpaks verursachen nach einiger Zeit leichten Schaden, da die verwendeten Chemikalien so stark sind.}
{14500}{}{Bücherregal}
{14501}{}{Ein Bücherregal aus Holz.}
{14600}{}{Bücherregal}
{14601}{}{Ein Bücherregal aus Holz.}
{14700}{}{Bücherregal}
{14701}{}{Ein Bücherregal aus Holz.}
{14800}{}{Bücherregal}
{14801}{}{Ein Bücherregal aus Holz.}
{14900}{}{Bücherregal}
{14901}{}{Ein Bücherregal aus Holz.}
{15000}{}{Bücherregal}
{15001}{}{Ein Bücherregal aus Holz.}
{15100}{}{Regale}
{15101}{}{Eine Reihe von Holzregalen.}
{15200}{}{Regale}
{15201}{}{Eine Reihe von Holzregalen.}
{15300}{}{Regale}
{15301}{}{Eine Reihe von Holzregalen.}
{15400}{}{Regale}
{15401}{}{Eine Reihe von Holzregalen.}
{15500}{}{Regale}
{15501}{}{Eine Reihe von Holzregalen.}
{15600}{}{Regale}
{15601}{}{Eine Reihe von Holzregalen.}
{15700}{}{Werkbank}
{15701}{}{Eine Werkbank. Ja, eine ganz normale, alte, stinkgewöhnliche Werkbank. Sieht dort auch ganz nett aus.}
{15800}{}{Werkzeugtafel}
{15801}{}{An dieser Tafel hängt eine Auswahl an Werkzeugen über der beliebten Werkbank.}
{15900}{}{Molotowcocktail}
{15901}{}{Eine selbstgemachte Brandgranate.\n Min. ST: 3.}
{16000}{}{Vieh Elektrotreiber}
{16001}{}{Ein Vieh-Elektrotreiber des Modells Farmer's Best Friend von Wattz Electronics. Wird mit kleinen Energiezellen betrieben.\n Min. ST: 4.}
{16100}{}{UD M42}
{16101}{}{Die Maschinenpistole ist ähnlich wie die Thompson konstruiert. Sie ist mit zwei gleichzeitig geladenen Magazinen ausgestattet, die für schnelles Nachladen nach einem "Jack"-Schema verbunden sind. Sie wurde nie sehr populär, aber eine Zeit lang aktiv vom Office of Strategic Services eingesetzt.\n Min. ST: 6.}
{16200}{}{9-mm-Maschinenpistole}
{16201}{}{Eine einfache und sehr zuverlässige Polizeiwaffe, die in Nevada und Kalifornien verwendet wird. Sie hat ein recht grosses Magazin, das in den Griff eingesetzt wird.\n Min. ST: 4.}
{16300}{}{12-ga.-Patronen}
{16301}{}{Munition für eine Schrotflinte. Die Patronen sind mit Geschossen bestückt.}
{16400}{}{Kampfstimulans}
{16401}{}{Dopingmittel für Kämpfer im Ring. Pumpt den Körper auf, erhöht kurzfristig die Widerstandsfähigkeit gegen Schaden und senkt die Schmerzschwelle. Nach einiger Zeit fordert es seinen Tribut, weil die enthaltenen schädlichen Chemikalien den Körper belasten.}
{16500}{}{Flugzeugluke}
{16501}{}{Du siehst eine durch die Explosion aufgerissene Flugzeugluke.}
{16600}{}{Tisch}
{16601}{}{Ein gewöhnlicher Tisch. Hält Dinge vom Boden fern.}
{16700}{}{Tisch}
{16701}{}{Ein gewöhnlicher Tisch. Hält Dinge vom Boden fern.}
{16800}{}{Kram}
{16801}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{16900}{}{Kram}
{16901}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17000}{}{Kram}
{17001}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17100}{}{Kram}
{17101}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17200}{}{Kram}
{17201}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17300}{}{Kram}
{17301}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17400}{}{Kram}
{17401}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17500}{}{Kram}
{17501}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17600}{}{Kram}
{17601}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17700}{}{Kram}
{17701}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17800}{}{Kram}
{17801}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{17900}{}{Kram}
{17901}{}{Das sind allerlei Gegenstände, auch bekannt als "Kram".}
{18000}{}{Kiste}
{18001}{}{Eine Holzkiste voller allerlei Kram.}
{18100}{}{Schreibtisch}
{18101}{}{Ein gewöhnlicher Schreibtisch. Hast du einen gesehen, hast du alle gesehen.}
{18200}{}{Schreibtisch}
{18201}{}{Ein gewöhnlicher Schreibtisch.}
{18300}{}{Schreibtisch}
{18301}{}{Ein gewöhnlicher Schreibtisch.}
{18400}{}{Schreibtisch}
{18401}{}{Ein gewöhnlicher Schreibtisch.}
{18500}{}{Schreibtisch}
{18501}{}{Ein gewöhnlicher Schreibtisch.}
{18600}{}{Schreibtisch}
{18601}{}{Ein gewöhnlicher Schreibtisch.}
{18700}{}{Schreibtisch}
{18701}{}{Ein gewöhnlicher Schreibtisch.}
{18800}{}{Spind}
{18801}{}{Ein alter Spind zur Aufbewahrung.}
{18900}{}{Spind}
{18901}{}{Ein alter Spind zur Aufbewahrung.}
{19000}{}{Strafakte}
{19001}{}{Von Nagetieren, Feuchtigkeit und der Zeit ziemlich mitgenommen, enthält dieser Ordner Unterlagen zu einem alten Kriminalfall. Einiges darin ist noch lesbar.}
{19100}{}{Diskette mit Soundtrack}
{19101}{}{Holografischer Film mit dem Soundtrack zu "Fallout: Nevada".}
{19200}{}{Buch "Homo Ludens"}
{19201}{}{Die Vorkriegs-Ausgabe von Johan Huizingas Buch "Der spielende Mensch". Das Buch untersucht Wesen und Bedeutung des Spielens in der Entwicklung der menschlichen Zivilisation.}
{19300}{}{Sicherungskopie der "Fallout-Enzyklopädie"}
{19301}{}{Die Diskette ist bis zum Rand mit allerlei Informationen über die Welt von Fallout gefuellt.}
{19400}{}{Bibel von Nevada}
{19401}{}{Ein seltenes prähistorisches Dokument. Jede einzelne Lektüre verschafft dir einen Erfahrungsschub. Allerdings nur einen kleinen.}
{19500}{}{Beruhigungsmittel}
{19501}{}{Janets Spritze ist mit einem ausgezeichneten "Beruhigungsmittel" gefuellt.}
{19600}{}{Werbung für die Postkutsche}
{19601}{}{Diese Kassette enthält Werbeinformationen über den "Nevada Express". Du kannst die Daten auf deinen Pip-Boy kopieren.}
{19700}{}{Kiste}
{19800}{}{Kiste}
{19900}{}{Kiste}
{20000}{}{Kiste}
{20100}{}{Kiste}
{20200}{}{Kiste}
{20300}{}{Kiste}
{20400}{}{Kiste}
{20500}{}{Leuchtfackel}
{20501}{}{Eine Signalrakete. Erzeugt für kurze Zeit Licht. Das Papier ist etwas abgenutzt, aber ansonsten in gutem Zustand. Sie ist angezündet.}
{20600}{}{Dynamit}
{20601}{}{Ein hochexplosiver Sprengstoff aus Nitroglycerin und dem absorbierenden Stoff Kieselgur. Mit Zeitschalter, der tickt.}
{20700}{}{Geigerzähler}
{20701}{}{Ein Geigerzähler, Modell C-Radz von Wattz Electronics. Erkennt das Vorhandensein und die Stärke von Strahlungsfeldern. Er ist eingeschaltet.}
{20800}{}{Bewegungsmelder}
{20801}{}{Ein Bewegungssensor, Modell C-U von Wattz Electronics. Erkennt mithilfe eines abgestimmten Radars die Bewegung biologischer Materie in mehreren Metern Entfernung. Er ist eingeschaltet.}
{20900}{}{Plastiksprengstoff}
{20901}{}{Ein Stück Cordex, ein militärischer Kunststoffsprengstoff. äusserst stabil und sehr zerstörerisch. Mit Zeitschalter, der tickt.}
{21000}{}{Stealth Boy}
{21001}{}{Ein persönliches Tarnvorrichtungsgerät Stealth Boy 3001 von RobCo. Erzeugt ein modulierendes Feld, das reflektiertes Licht von einer Seite eines Objekts zur anderen überträgt.}
{21100}{}{Knochen}
{21101}{}{Du siehst Ed. Ed ist tot.}
{21200}{}{Sauberes Wasser}
{21201}{}{Lebensspendendes Trinkwasser, durch die Filter von Vault 8 von Strahlung gereinigt.}
{21300}{}{Reservoir}
{21301}{}{Ein Reservoir, das lebende Zellen oder den gesamten Körper am Leben erhalten soll.}
{21400}{}{Dokumentenkisten}
{21401}{}{Aktenschrank für diverse Dokumente.}
{21500}{}{Labortisch}
{21501}{}{Tisch für Experimente mit Chemikalien.}
{21600}{}{Labortisch}
{21601}{}{Tisch für Experimente mit Chemikalien.}
{21700}{}{Labortisch}
{21701}{}{Tisch für Experimente mit Chemikalien.}
{21800}{}{Asche des Vorvaters}
{21801}{}{Eine widerliche Mischung aus Asche, verstrahlter Erde und Kadaverkompost.}
{21900}{}{Bordcomputer}
{21901}{}{Ein wichtiges Computerbauteil, das alle Zugsysteme steuert. Funktioniert derzeit nicht.}
{22000}{}{Bordcomputer}
{22001}{}{Ein wichtiges Computerbauteil, das alle Zugsysteme steuert.}
{22100}{}{Sicherheitskarte}
{22101}{}{Spezielle Schlüsselkarte, die Zugang zum Bunker der Radiostation Lovelock gewährt.}
{22200}{}{Encoder}
{22201}{}{Ein altes, aber gut erhaltenes Gerät. Sein grösster Vorteil ist, dass es noch funktioniert.}
{22300}{}{Funkschlüssel}
{22301}{}{Das ist der Schlüssel für das elektronische Schloss. Beim Drücken der Taste sendet er ein Funksignal einer bestimmten Frequenz über kurze Distanz.}
{22400}{}{Kabel}
{22401}{}{Langer Hochspannungskabelstrang.}
{22500}{}{Cat's Paw Magazin}
{22501}{}{Eine Ausgabe des Magazins Cat's Paw.}
{22600}{}{Nudelbox}
{22601}{}{Du hast keine Ahnung, was "Instant-Spaghetti" bedeutet. Aber offenbar kann man sie kochen.}
{22700}{}{Fertiggericht}
{22701}{}{Ein Fertiggericht aus dem Fernsehmenü. Du bist dir nicht sicher, was das bedeutet, aber du bist sicher, dass es nicht essbar aussieht. Du weisst nicht, ob es das jemals war.}
{22800}{}{Melasse}
{22801}{}{Die braune Masse stammt vermutlich aus zweifelhafter Quelle. Sie riecht unangenehm und enthält einige unverständliche Verunreinigungen.}
{22900}{}{Photonenkanone}
{22901}{}{Diese ungewöhnliche Waffe basiert auf einem Quantengenerator.\n Min. ST: 3.}
{23000}{}{Koordinaten einer Reifenkippe}
{23001}{}{Diese Holodisk enthält die Koordinaten der Reifenkippe in der Nähe von Vegas.}
{23100}{}{Koordinaten einer Reifenkippe}
{23101}{}{Diese Holodisk enthält die Koordinaten der Reifenkippe in der Nähe von Vegas.}
{23200}{}{Medizinischer Schlafanzug}
{23201}{}{Ein Schlafanzug aus einer speziellen Kunstfaser, die das Wärme- und Luftklima des Körpers stabilisiert. Vor dem Krieg wurde er Patienten nach einer Chemotherapie gegeben.}
{23300}{}{Turbo-Plasmagewehr}
{23301}{}{Fortschrittliche Plasmakanone Winchester P94. Die Plasmakammer ist mit einer Heizwicklung ausgestattet, die die Bildung der Plasmaladung beschleunigt.\n Min. ST: 6.}
{23400}{}{Stachelfäuste}
{23401}{}{Eine verbesserte Version der klassischen Schlagringe. Die Stachelfäuste verursachen mehr Schaden und reissen im unbewaffneten Kampf das Fleisch deines Gegners auf.\n Min. ST: 1.}
{23500}{}{Kraftfaust}
{23501}{}{Eine Kraftfaust "Big Frigger" von BeatCo. Viele halten sie für die ultimative Waffe im unbewaffneten Kampf. Andere haben einfach nur Angst. Betrieb mit kleinen Energiezellen.\n Min. ST: 1.}
{23600}{}{Kampfmesser}
{23601}{}{Ein hochwertiges Kampfmesser, das Stallona von SharpWit, Inc. Die Klinge bleibt bei normalem Gebrauch garantiert über ein Jahrzehnt lang schärf!\n Min. ST: 2.}
{23700}{}{Zeitungen}
{23701}{}{Mehrere Ausgaben der Zeitung "Denver Post". Darin: ein Bericht über Atomtests in Nevada, ein weiterer Beleg für UFO-Sichtungen 100 km von Las Vegas entfernt und Werbung für neue Produkte von "Pretty & Glamour".}
{23800}{}{Passwörter}
{23801}{}{Ein hastig beschrifteter Zettel mit Passwörtern.                    Eins: 153-648-987.         Zwei: 045-896-509.         Drei: 987-469-876.      Vier: 013-486-498.}
{23900}{}{Körperrüstung}
{23901}{}{Eine leichte kugelsichere Militärweste mit Vorrichtungen, um allerlei Kram schnell zu verstauen. Schützt nur einen Teil des Oberkörpers, da sie für Mitglieder der Notfall-Einsatzteams gedacht war. In ausgezeichnetem Zustand.}
{24000}{}{Tesla-Rüstung}
{24001}{}{Diese glänzende Rüstung bietet hervorragenden Schutz vor Energieangriffen. Die drei Tesla-Ablenkspulen zerstreuen einen grossen Teil der gebündelten Energieangriffe.}
{24100}{}{Zivilgewehr}
{24101}{}{Dieses Gewehr kam lange vor dem Grossen Krieg in verschiedenen militärischen Konflikten häufig zum Einsatz. Nach der Umstrukturierung der US-Armee strömten überschüsse auf den zivilen Markt, wo es sich schnell als erschwingliche und zuverlässige Waffe etablierte.\n Min. ST: 5.}
{24200}{}{Kampf-Schrotflinte}
{24201}{}{Eine Winchester City-Killer Kaliber 12, eine Kampf-Schrotflinte in Bullpup-Ausführung. In ausgezeichnetem Zustand und mit der optionalen DesertWarfare-Umweltdichtungsmodifikation für noch mehr Zuverlässigkeit.\n Min. ST: 6.}
{24300}{}{Topf}
{24301}{}{Ein fein gearbeiteter Tontopf.}
{24400}{}{Topf}
{24401}{}{Ein fein gearbeiteter Tontopf.}
{24500}{}{Truhe}
{24501}{}{Selbstgebaute Holztruhe.}
{24600}{}{Regal}
{24601}{}{Selbstgebautes Metallregal aus Rohren und gebogenen Eisenblechen.}
{24700}{}{Regal}
{24701}{}{Selbstgebautes Metallregal aus Rohren und gebogenen Eisenblechen.}
{24800}{}{Topf}
{24801}{}{Ein fein gearbeiteter Tontopf.}
{24900}{}{Topf}
{24901}{}{Ein fein gearbeiteter Tontopf.}
{25000}{}{Knochen}
{25001}{}{Ein Haufen menschlicher Knochen.}
{25100}{}{Sitzsack}
{25101}{}{Ein Haufen Dosen mit Schraubenmuttern darin. Dieses Zeug scheint wohl keinen Nutzen mehr zu haben ...}
{25200}{}{Sturmhaube}
{25201}{}{Eine eng anliegende Kopfbedeckung, die das Gesicht des Trägers fast vollständig verbirgt. Sie lässt sich mit vielen Rüstungsarten tragen, doch damit sorgt man bei gelegentlichen Passanten ganz sicher für Panik.}
{25300}{}{Brennstoffzellen-Steuergerät}
{25301}{}{Dieser Chip steuert den Stromfluss zu den Elektromotoren eines Autos. Viele Fahrer brannten ihn durch häufiges starkes Beschleunigen schnell durch. Trotzdem ist er ein sehr wertvolles Teil - wenn man ein Auto hat, in das man ihn einbauen kann.}
{25400}{}{Kraftstoffregler}
{25401}{}{Manche Fahrer bauten diesen Regler ein, der den Kraftstoffverbrauch halbiert, doch den meisten war es egal, wie viel ihre Autos schluckten. Schliesslich ist Kraftstoff billig und reichlich vorhanden. Wozu also Sorgen machen?}
{25500}{}{überreste des Kommandanten}
{25501}{}{Dieses Skelett liegt schon sehr lange hier. Es trägt eine verrottete Militäruniform, und in seinem Schädel klafft ein riesiges Loch.}
{25600}{}{Zerknittertes Stück Papier}
{25601}{}{Auf diesem Zettel stehen einige komplizierte alphanumerische Codes. Du kannst dir nicht vorstellen, was sie bedeuten sollen.}
{25700}{}{Paradeuniform}
{25701}{}{Militäruniform für hohe Offiziere. Jetzt ist sie nur noch Kleidung.}
{25800}{}{Rollbar}
{25801}{}{Mobiler Wagen zum Kochen und Verkaufen von warmem Essen direkt auf der Strasse.}
{25900}{}{Karamell}
{25901}{}{Süsses Bonbon mit einer unerwarteten halbtäubenden Füllung. Wenn du es isst, wirst du schläfrig, dein Kopf wird schwerer, deine Muskeln arbeiten langsamer, aber dein Gesichtsausdruck wird weicher und deine Stimme weniger rau.}
{26000}{}{Nicht benutzen}
{26001}{}{Nicht benutzen!}
{26100}{}{"Mickeys Rache"}
{26101}{}{Deine selbstgemachte Nahkampfwaffe. In gewisser Hinsicht kann sie es sogar mit industriell gefertigten Schockern aufnehmen.\n Min. ST: 3.}
{26200}{}{Gummistiefel}
{26201}{}{Ein altes Paar robuster Gummiarbeitsstiefel. Sie sehen strapazierfähig genug aus, um Schlamm zumindest eine Weile abzuhalten.}
{26300}{}{Truhe}
{26301}{}{Selbstgebaute Holztruhe.}
{26400}{}{Eierlegen}
{26500}{}{Ranch-Wächterjacke}
{26501}{}{Diese sehr strapazierfähige Lederjacke ist mit eingearbeiteten Metallteilen verstärkt. Erkennungszeichen auf Rücken und ärmeln weisen den Träger als Wächter auf Oliver Lucianos Ranch aus.}
{26600}{}{Feldflasche}
{26601}{}{Leere Feldflasche aus Metall mit Schraubverschluss zur Aufbewahrung und zum Transport von Flüssigkeiten.}
{26700}{}{Ausweis}
{26701}{}{Gewöhnlicher Ausweis mit Magnetstreifen.}
{26800}{}{H&K CAWS}
{26801}{}{Die Schrotflinte CAWS, kurz für Close Assault Weapons System, ist eine nützliche Waffe für den Nahkampf. Die Bullpup-Bauweise macht sie kompakt und handlich, bietet aber dennoch genug Lauflange für ihre Hochgeschwindigkeitspatronen.\n Min. ST: 6.}
{26900}{}{Schwere Kugeln}
{26901}{}{Eine Handvoll "erfolgreich" verschossener Kugeln aus Kaliber-12-Patronen. Diese Sammlung kann immerhin noch zur Herstellung neuer Patronen verwendet werden.}
{27000}{}{Robo-Raketenwerfer}
{27001}{}{Wird nur von mit Raketen ausgerüsteten Robotern benutzt.}
{27100}{}{Broc-Blume}
{27101}{}{Blütenstand einer sonnenliebenden Pflanze, die auf steinigem Boden wächst. Sie wird aufgrund ihrer heilenden Eigenschaften in der traditionellen Medizin verwendet.}
{27200}{}{Xander-Wurzel}
{27201}{}{Seltene, schattenliebende Wurzelpflanzen, die in lockerem Boden mit ausreichend Feuchtigkeit wachsen. Sie werden wegen ihrer heilenden Eigenschaften in der traditionellen Medizin verwendet.}
{27300}{}{Heilpulver}
{27301}{}{Ein äusserst starkes Heilmittel - doch es wird dich müde machen.}
{27400}{}{Robo-Raketenmunition}
{27401}{}{Wird nur von mit Raketen ausgerüsteten Robotern benutzt.}
{27500}{}{Auto}
{27501}{}{Es sieht so aus, als hätte dieses Auto mehr als zehn Jahre im Freien gestanden.}
{27600}{}{Gecko-Fell}
{27601}{}{Dies ist das getrocknete und gegerbte Fell eines gewöhnlichen Geckos.}
{27700}{}{Goldgecko-Fell}
{27701}{}{Dies ist das getrocknete und gegerbte Fell eines Goldgeckos.}
{27800}{}{Toaster}
{27801}{}{Multifunktionales Verbundgerät von Wattz Electronics. Eine Kombination aus Elektroherd, kleinem Ofen und Toaster. Für den Einsatz in beengten Wohnwagen konzipiert.}
{27900}{}{Gilmores Kopf}
{27901}{}{Ein abgetrennter Kopf in einem Sack, der einst Gary Gilmore gehörte. Ein eindeutiger Beweis für seinen Tod.}
{28000}{}{Geschärfter Speer}
{28001}{}{Eine Stangenwaffe mit messerscharfer Spitze. Der Schaft ist aus Holz, die Spitze aus geschärftem Stahl.\n Min. ST: 4.}
{28100}{}{Haarnadel}
{28101}{}{Lässt sich leicht in jede beliebige Form biegen.}
{28200}{}{Schweissgerät}
{28201}{}{Schweissgerät mit elektromagnetischer Funktionsweise. Vorsichtsmassnahmen: Von Kindern und elektronischen Geräten fernhalten.\n Min. ST: 6.}
{28300}{}{Tommy Gun}
{28301}{}{Diese Maschinenpistole Thompson M1928 sieht finster aus. Jedes Mal, wenn du sie in die Hand nimmst, bekommst du Lust, einen Fedora aufzusetzen und mit den Fingerknöcheln zu knacken. Die Thompson wird von einem grossen 50-Schuss-Trommelmagazin versorgt.\n Min. ST: 5.}
{28400}{}{Trockenfleisch}
{28401}{}{Diese geräucherten und getrockneten Stücke Bestienfleisch bleiben jahrelang zäh und köstlich und sind sogar einigermassen nahrhaft ...}
{28500}{}{Versteck}
{28501}{}{Stabile Holzkiste, im Boden vergraben.}
{28600}{}{"White Walls"}
{28601}{}{Ein Set zum Bemalen von Autoreifen. Weisse Reifen waren in den USA während der Grossen Depression sehr in Mode. Seitdem ist diese Farbe langsam eingetrocknet und schliesslich zu einem nutzlosen Stein geworden.}
{28700}{}{Zielfernrohr-Jagdgewehr}
{28701}{}{Nichts ist besser, als den überraschten Blick auf dem Gesicht deines Ziels zu sehen. Das Zielfernrohr Loophole x20 an diesem Jagdgewehr macht es einfacher denn je. Vom ersten bis zum letzten Schuss präzise, ganz gleich, auf welches Wild du es abgesehen hast.\n Min. ST: 5.}
{28800}{}{Generatorbrennstoff}
{28801}{}{Eine leistungsstarke Energiequelle für Stromgeneratoren von Wattz Electronics. Wenn du einen leeren Generator findest, ist dieses Zeug unersetzlich.}
{28900}{}{Schaufel}
{28901}{}{Eine Schaufel zum Ausheben von Gräben und so weiter.}
{29000}{}{Robo-Nahkampfwaffe 1}
{29001}{}{Für den Floating-Eye-Roboter. Verursacht elektrischen Schaden.}
{29100}{}{Robo-Nahkampfwaffe 2}
{29101}{}{Für den Floating-Eye-Roboter. Verursacht elektrischen Schaden.}
{29200}{}{Boxhandschuhe}
{29201}{}{Ein Paar Boxhandschuhe, die leicht nach Schweiss riechen. Sie sehen aus, als wären sie oft benutzt worden: Viele alte Blutflecken sind noch zu sehen.}
{29300}{}{Verstärkte Boxhandschuhe}
{29301}{}{Jemand hat diesen Boxhandschuhen "aus Versehen" Metallplatten untergeschoben. Technisch gesehen könnte man das als Betrug bezeichnen, aber du siehst es lieber als bessere Möglichkeit, Knochen zu zermalmen.}
{29400}{}{Jagdpfeife}
{29401}{}{Selbstgemachte Jagdpfeife, um mutierte Echsen anzulocken. Sie macht ein sehr unangenehmes Geräusch.}
{29500}{}{Harrelsons Angriffe}
{29501}{}{Wird von Sadisten und Monstern benutzt.}
{29600}{}{HK P90c}
{29601}{}{Das Heckler & Koch P90c kam gerade erst in Gebrauch, als der Krieg ausbrach. Das Bullpup-Layout und die kompakte Bauweise der Waffe machen sie leicht kontrollierbar. Das robuste P90c ist für seine Zuverlässigkeit und hohe Feuerkraft in einem widerstandsfähigen, kompakten Paket geschätzt.\n Min. ST: 4.}
{29700}{}{Fortschrittlicher Granatwerfer}
{29701}{}{Rockwell-Granatwerfer "Superbazooka", ausgestattet mit einem perfekten Rückstosskompensator.\n Min. ST: 5.}
{29800}{}{Kommunikationsschlüssel}
{29801}{}{Die ungewöhnliche Form der Schlüssel-Drehscheiben, die nach dem Einsetzen in das Schlüsselloch geöffnet werden müssen.}
{29900}{}{Rohrgewehr}
{29901}{}{Ein handgefertigtes Einzelschussgewehr.\n Min. ST: 5.}
{30000}{}{"Wilder"}
{30001}{}{Eine einschüsige Schrotflinte mit abgekürztem Lauf. Obwohl diese Waffe bereits stark abgenutzt und veraltet ist, hat sie einen unbestreitbaren Vorteil: schnelles Nachladen.\n Min. ST: 4.}
{30100}{}{Handtuch}
{30101}{}{Im Labor "Pretty & Glamour" entworfenes Handtuch mit integriertem Chip, der die Hauttrockenheit misst. Der Hinweis auf dem Etikett verbietet das Rauchen in der Nähe des Handtuchs.}
{30200}{}{Todesnotiz}
{30201}{}{"An denjenigen, der mich tötet: Ich habe den Weg des Raubes eingeschlagen, weil die Saubere Stadt mein Land annektiert hat. Die Ernte wird von den Bastarden aus Vegas genommen, ich habe nichts zu essen. Ich halte es nicht mehr aus."}
{30300}{}{Leere Holodisk}
{30301}{}{Du musst die Informationen von allen Monitoren an der Oberfläche auf dieser Holodisk speichern.}
{30400}{}{Kartenspiel "Tragic"}
{30401}{}{Ein Kartenspiel für ein Sammelkartenspiel. Sieht nach einem teuren Hobby aus, wenn man sich erst einmal dafür begeistern kann.}
{30500}{}{Computerschlüssel}
{30501}{}{Magnetischer Zugangsschlüssel für ein Computerterminal im Wind des Krieges.}
{30600}{}{Zugangskarte für Labor "Alpha"}
{30601}{}{Elektronische Zugangskarte der ersten Stufe für den Hangar von Area 51.}
{30700}{}{Munitionsreste}
{30701}{}{Bestandteile alter Munition: Patronen, Geschosse und Schiesspulver, sorgfältig Stück für Stück zusammengesetzt. Einiges davon kann noch zur Herstellung neuer Munition verwendet werden.}
{30800}{}{Super-Werkzeugkasten}
{30801}{}{Eine beeindruckende Werkzeugsammlung.}
{30900}{}{Alte Holodisk}
{30901}{}{Holodisk aus einer verlassenen Siedlung in der Nähe von Vault City. Die Informationen sind mit einem alten Code verschlüsselt.}
{31000}{}{Vorkriegswhiskey}
{31001}{}{Starker Alkohol aus einem sehr guten Jahrgang. Im postnuklearen Nevada im Vergleich zu anderen Alkoholsorten hoch geschätzt.}
{31100}{}{Vocas}
{31101}{}{Nüsse einer mutierten Seerose, die in den salzigen Gewässern nahe dem Salt Lake wächst. Die Anpassung an die hiesigen Bedingungen hat den Nüssen eine einzigartige Eigenschaft verliehen: Sie entfernen radioaktive Partikel aus dem Körper.}
{31200}{}{Abschleppseil}
{31201}{}{Robustes Abschleppseil für Autos, etwa 18 Fuss lang. An beiden Enden sind Haken befestigt.}
{31300}{}{.44-Magnum-Revolver}
{31301}{}{Da dies die stärkste Handfeuerwaffe der Welt ist und dir den Kopf wegblasen kann, musst du dir eine Frage stellen: "Fühle ich mich glücklich?" Na, du Punk?\n Min. ST: 5.}
{31400}{}{Kondom (blaue Packung)}
{31401}{}{Dies ist ein Kondom der Marke Jimmy Hats, einer sehr zuverlässigen Marke. Dieses hier ist für ihr Vergnügen gerippt.}
{31500}{}{Kondom (grüne Packung)}
{31501}{}{Dies ist ein Kondom der Marke Jimmy Hats, einer sehr zuverlässigen Marke. Dieses hier enthält phosphorgrüne Farbe Nr. 2 und ist zum zusätzlichen Schutz mit spermizidem Gleitmittel bestrichen.}
{31600}{}{Kondom (rote Packung)}
{31601}{}{Dies ist ein Kondom der Marke Jimmy Hats, einer sehr zuverlässigen Marke. Dieses hier enthält phosphorrote Farbe Nr. 5 und schmeckt lecker nach Zimtschnecke ... zumindest hast du das gehört.}
{31700}{}{Kosmetikkoffer}
{31701}{}{Dies ist ein echter Kosmetikkoffer der Marke "Mary May".}
{31800}{}{Leere Spritze}
{31801}{}{Dies ist eine leere Spritze für Injektionen unter die Haut.}
{31900}{}{Springmesser}
{31901}{}{Die Klinge dieses kleinen Messers wird von einer Feder gehalten. Drückt man auf einen Knopf am Griff, schnellt die Klinge mit einem befriedigenden "Sssssshk" heraus.\n Min. ST: 1.}
{32000}{}{Angespitzte Stange}
{32001}{}{Eine Holzstange, die an einem Ende angespitzt wurde.\n Min. ST: 4.}
{32100}{}{Abgerissener Kopf}
{32101}{}{Der Kopf eines Menschen in einem Sack. Er gehörte einst einem Einwohner von Provo, jetzt gehört er dir rechtmässig.}
{32200}{}{Mysteriöse Vorrichtung}
{32201}{}{Hightech-Vorrichtung mit unbekanntem Zweck.}
{32300}{}{Signalstörer}
{32301}{}{Auf jede Aktion folgt eine Reaktion. Diese Hightech-Vorrichtung soll das Funksignal unterdrücken und die elektronischen Komponenten seiner Quelle ausschalten. Wirksam in einem Umkreis von acht Meilen.}
{32400}{}{Desinfektion}
{32401}{}{Tabletten, die verschiedene biologische Krankheitserreger in Wasser und ähnlichen Flüssigkeiten vollständig abtöten. Damit kannst du sogar Abwasser reinigen und trinken, ohne deiner Gesundheit zu schaden.}
{32500}{}{Würfel}
{32501}{}{Ein gewöhnliches Paar Spielwürfel. Ein paar flauschige Würfel für dein Auto wären cool.}
{32600}{}{Gezinkte Würfel}
{32601}{}{Ein Paar gezinkte Würfel. Lass dich damit lieber nicht im Kasino erwischen.}
{32700}{}{Dealerdiskette}
{32701}{}{Diese Diskette enthält einige Funkfrequenzen. Ohne ein funktionierendes Funkgerät kannst du nichts Weiteres herausfinden.}
{32800}{}{DVR-Aufnahmen}
{32801}{}{Holodisk des Roboterwächters mit Aufzeichnungen über die Begleitung einer Postkutsche von Salt Lake City nach New Reno. Vielleicht sind hier einige Informationen erhalten geblieben, allerdings verschlüsselt. Dein Pip-Boy kann sie lesen.}
{32900}{}{Stranglehold}
{32901}{}{Gewöhnliche silberne Gitarrensaite, auf den Ton Re stimmbar. Allerdings wurde sie schon lange nicht mehr für ihren eigentlichen Zweck verwendet.}
{33000}{}{Kleine Truhe}
{33001}{}{Alte, verrostete Truhe zur Aufbewahrung.}
{33100}{}{"Superwissenschaft"}
{33101}{}{Vielleicht das einzige Vorkriegsmagazin, das sich ganz den Energiewaffen widmet. Die Leser rissen es sich förmlich aus den Händen. Eines zu finden ist also ein echter Glücksfall!}
{33200}{}{M3A1-"Grease Gun"-MP}
{33201}{}{Diese Maschinenpistole füllte die Lager der Nationalgarde, nachdem die Armee sie durch neuere Waffen ersetzt hatte. Die "Grease Gun" war jedoch einfach und billig herzustellen, daher sind noch immer recht viele davon im Einsatz.\n Min. ST: 4.}
{33300}{}{Herzpillen}
{33301}{}{Diese Pillen werden von Menschen mit Herzproblemen eingenommen.}
{33400}{}{"Pferdetöter"}
{33401}{}{Eine Spritze mit Nadel, gefuellt mit starkem Gift.}
{33500}{}{Koffer des Kuriers}
{33501}{}{Diesen Koffer brachte ein geheimer Kurier von Vegas nach Reno. Du konntest ihn nicht öffnen. Was wohl drin ist?}
{33600}{}{Maxsons abgesägte Schrotflinte}
{33601}{}{Du tauschst diesen Gegenstand mit Maxson.}
{33700}{}{Mentats}
{33701}{}{Tabletten mit einer bewusstseinserweiternden Chemikalie. Sie verbessern die mit dem Gedächtnis verbundenen Hirnfunktionen und beschleunigen bestimmte geistige Prozesse. Sie machen stark abhängig.}
{33800}{}{Frucht-Mentats}
{33801}{}{Tabletten mit einer bewusstseinserweiternden Chemikalie. Sie verbessern die mit dem Gedächtnis verbundenen Hirnfunktionen und beschleunigen bestimmte geistige Prozesse. Sie machen nicht abhängig.}
{33900}{}{Notizen des gefangenen Mannes}
{33901}{}{Tagebuch eines Mannes, der in einem Mini-Vault in Salt Lake gefangen war. Eine sehr drastische Lektüre.}
{34000}{}{überreste}
{34001}{}{Verrottende überreste eines Mannes, der in entspannter Haltung starb. Er liegt hier wohl schon seit mehr als einem Jahrzehnt.}
{34100}{}{Holodisk des Roboters}
{34101}{}{Auf diesem Holodisk sind Informationen über den Zustand der Umgebung gespeichert, die der Roboteraufklärer auf seinen Reisen gesammelt hat.}
{34200}{}{Nützliche Notizen}
{34201}{}{Eine kurze biografische Skizze von Jedediah Smith. Der Autor beschreibt die Lebensweise in den Siedlungen, die er besucht hat.}
{34300}{}{Apfelkuchen}
{34301}{}{M-m, ein Kuchen! Aus Maisteig und Mutfrüchten.}
{34400}{}{Friedhof}
{34500}{}{Friedhof}
{34600}{}{Friedhof}
{34700}{}{Friedhof}
{34800}{}{Hässliche Rüstung}
{34801}{}{Eine ziemlich hässliche Rüstung. Wer das gemacht hat, war offenbar nicht ganz bei Verstand ... oder setzte auf Einschüchterung und Ekel.}
{34900}{}{Polizeirüsteung}
{34901}{}{Vereinfachte Version der Kampfrüstung für die Polizei.}
{35000}{}{Maschinengewehr M2041}
{35001}{}{Ein manülles Maschinengewehr mit Luftkühlung und schnell wechselbarem Lauf. Es ist die Wiedergeburt einer alten kommerziellen Entwicklung, angepasst an moderne Anforderungen. Ein Teil der nach der Produktion übrig gebliebenen Maschinengewehre ging "unter der Hand" in den Verkauf und Handel mit Ländern der "Dritten Welt".\n Min. ST: 6.}
{35100}{}{Qüü}
{35101}{}{Gewöhnlicher Billardqüü. Nichts Besonderes.}
{35200}{}{H&K G11}
{35201}{}{Diese Waffe revolutionierte das Design von Sturmgewehren. Sie verschiesst hülsenlose Munition, bestehend aus einem Treibladungsklotz mit darin eingebettetem Geschoss. Das geringere Gewicht und der Platzgewinn ermöglichen ein sehr grosses Magazin.\n Min. ST: 5.}
{35300}{}{Eintrittskarte}
{35301}{}{Diese Karte berechtigt ihren Inhaber zu einem einmaligen kostenlosen Eintritt in den Nachtclub von New Reno.}
{35400}{}{Pancor Jackhammer}
{35401}{}{Der Jackhammer ist trotz seines Namens eine leicht kontrollierbare Schrotflinte, sogar bei vollautomatischem Feuer. Das beliebte Bullpup-Design, bei dem das Magazin hinter dem Abzug sitzt, sorgt für eine gute Balance und leichte Kontrolle.\n Min. ST: 6.}
{35500}{}{Schraubenmagazin-Maschinenpistole}
{35501}{}{Diese ungewöhnliche Waffe ist mit einem Schraubenmagazin ausgestattet, das eine grosse Anzahl Patronen fasst.\n Min. ST: 2.}
{35600}{}{CL 3000}
{35601}{}{Tragbare Laborausstattung mit Zentrifuge und Flüssigkeitserhitzer. Damit könntest du unterwegs Medikamente herstellen.}
{35700}{}{.45 Kaliber}
{35701}{}{Munition. .45 Kaliber.}
{35800}{}{2mm EC}
{35801}{}{Munition.}
{35900}{}{4.7mm Hülsenlos}
{35901}{}{Munition. Kaliber: 4.7mm, hülsenlos.}
{36000}{}{Energiezelle}
{36001}{}{Ungewöhnlicher Energiespeicher.}
{36100}{}{---}
{36101}{}{---}
{36200}{}{40-mm-Granate}
{36201}{}{Kassette mit Granaten für einen Granatwerfer.}
{36300}{}{Patronen Kaliber .30}
{36301}{}{Gewehrmunition. Kaliber: .30.}
{36400}{}{Poststempel}
{36401}{}{Sehr seltsame Poststempel aus der Serie "Pink Elephant". Ihr Zweck ist ebenso unklar wie die Frage, wie das saugfähige Papier all die langen Jahre unversehrt blieb.}
{36500}{}{Pflanzendorn}
{36501}{}{Ein organischer Samendorn, den fleischfressende Pflanzen auf mögliche Beute oder Samenverbreiter spucken.}
{36600}{}{---}
{36601}{}{---}
{36700}{}{Munitionskiste}
{36800}{}{Munitionskiste}
{36900}{}{Munitionskiste}
{37000}{}{Munitionskiste}
{37100}{}{Kralle}
{37101}{}{Kralle}
{37200}{}{Kralle}
{37201}{}{Kralle}
{37300}{}{Zugangskarte zum Bunker}
{37301}{}{Ein elektronischer Sicherheitsschlüssel für die Innentür des Bunkers in Reno.}
{37400}{}{Friedhof}
{37500}{}{Friedhof}
{37600}{}{Friedhof}
{37700}{}{Werkzeug zur Munitionsherstellung}
{37701}{}{Tragbares, selbstgebautes Gerät zur Munitionsherstellung. Mit dem speziellen Relais kannst du die Presse auf verschiedene Kaliber einstellen.}
{37800}{}{Werkzeug zur Munitionsherstellung (Ergänzung)}
{37801}{}{Tragbares, selbstgebautes Gerät zur Munitionsherstellung. Mit dem speziellen Relais kannst du die Presse auf verschiedene Kaliber einstellen. Ergänzt um Einsätze für panzerbrechende Patronen.}
{37900}{}{Lederrüstung Mark II}
{37901}{}{Eine verbesserte Version der einfachen Lederrüstung mit zusätzlichen Schutzschichten. Sorgfältig aus gegerbtem Brahminleder gefertigt.}
{38000}{}{Metallrüstung Mark II}
{38001}{}{Polierte Metallplatten, sorgfältig zu einer Rüstung verarbeitet.}
{38100}{}{Kampfrüstung Mark II}
{38101}{}{Hochtechnologische Rüstung aus fortschrittlichen Schutzpolymeren.}
{38200}{}{Flammenwerfer-Treibstoff MKII}
{38201}{}{Dieser Flammenwerfer-Treibstoff verwendet eine fortschrittliche Superbrennstoffmischung.}
{38300}{}{Nicht benutzen}
{38301}{}{Nicht benutzen!}
{38400}{}{Schraubenschlüssel}
{38401}{}{Ein typischer Schraubenschlüssel für Mechaniker.\n Min. ST: 3.}
{38500}{}{Abgesägte Schrotflinte}
{38501}{}{Jemand hat sich die Mühe gemacht, die letzten Zentimeter des Laufs und Schafts dieser Schrotflinte abzusägen. Die breite Streuung ihrer Schüsse aus kurzem Lauf macht diese Handkanone nun ideal, um Gegner auf kurze Distanz in Schach zu halten.\n Min. ST: 5.}
{38600}{}{Baseballschläger}
{38601}{}{Dieser typisch amerikanische Baseballschläger aus Hartholz ist mit Spitzen versehen, um die Wucht des Schlags zu verstärken.\n Min. ST: 4.}
{38700}{}{M60}
{38701}{}{Dieses relativ leichte Maschinengewehr wurde weltweit wegen seiner hohen Feuerrate von Militärs geschätzt. Das zuverlässige, kampferprobte Design kam auf Fahrzeugen und zur Feuerunterstützung von Trupps zum Einsatz.\n Min. ST: 7.}
{38800}{}{---}
{38801}{}{---}
{38900}{}{"Avenger"-Minigun}
{38901}{}{Rockwell entwickelte die Avenger als Ersatz für die alternde CZ53-Personalminigun. Zu den Verbesserungen gehören eine Kühlung mit Gelrippen und verchromte Laufbohrungen. Dadurch hat sie eine grössere Reichweite und mehr Durchschlagskraft.\n Min. ST: 7.}
{39000}{}{Solar Scorcher}
{39001}{}{Ohne die Sonnenstrahlen, die die Kondensatoren dieser Waffe aufladen, kann sie nicht einmal ein Streichholz entzünden. Bei vollem Tageslicht verwandeln die experimentellen photölektrischen Zellen, die den Scorcher antreiben, jedoch fast alles in ein knuspriges Häufchen.\n Min. ST: 3.}
{39100}{}{Kellys Gewehr}
{39101}{}{Kellys persönliches Gewehr. Sehr abgenutzt, aber immer noch zuverlässig.\n Min. ST: 5.}
{39200}{}{M72-Gaussgewehr}
{39201}{}{Das M72-Gewehr stammt aus deutscher Entwicklung. Es nutzt ein elektromagnetisches Feld, um Geschosse mit enormer Geschwindigkeit abzufeuern ... und fast jedes Hindernis zu durchschlagen. Seine Reichweite, Genauigkeit und Stoppwirkung sind nahezu unerreicht.\n Min. ST: 6.}
{39300}{}{Maschinengewehr .223}
{39301}{}{Handmaschinengewehr für Gewehrpatronen.\n Min. ST: 6.}
{39400}{}{PPK12-Gauss-Pistole}
{39401}{}{Die PPK12-Gauss-Pistole deutscher Bauart ist für ihre Reichweite und Stoppwirkung bekannt. Sie nutzt ein elektromagnetisches Feld, um Geschosse mit enormer Geschwindigkeit abzufeuern und fast jede Panzerung zu durchschlagen.\n Min. ST: 4.}
{39500}{}{M16K}
{39501}{}{Maschinenpistole, von der Firma "La France" in San Diego auf Grundlage der M16 entwickelt. Eine Zeit lang war sie bei Spezialeinheiten und der Polizei einzelner Bundesstaaten beliebt.\n Min. ST: 4.}
{39600}{}{YK32-Pulspistole}
{39601}{}{Die YK32 ist eine elektrische Impulswaffe, die vom Yuma Flats Energy Consortium entwickelt wurde. Obwohl sie leistungsstark ist, galt sie wegen ihres ineffizienten Energieverbrauchs und ihres klobigen Designs nie als praktikable Waffe.\n Min. ST: 3.}
{39700}{}{YK42B-Pulsgewehr}
{39701}{}{Die YK42B ist eine elektrische Impulswaffe, die vom Yuma Flats Energy Consortium entwickelt wurde. Sie gilt als der YK32-Pistole deutlich überlegen und bietet eine höhere Ladekapazität und grössere Reichweite.\n Min. ST: 3.}
{39800}{}{.44 Magnum (Schnellladung)}
{39801}{}{Ein .44-Magnum-Revolver mit Speedloader.\n Min. ST: 5.}
{39900}{}{Super-Viehtreiber}
{39901}{}{Ein Viehtreiber des Modells "Farmer's Best Friend" von Wattz Electronics. Dieses Modell wurde verbessert, um die elektrische Entladung zu verstärken.\n Min. ST: 4.}
{40000}{}{Verbesserter Flammenwerfer}
{40001}{}{Ein Flammenwerfer des Modells Flambe-450, in der Schädlingsjäger-Variante. Verspritzt einen kurzen Strahl extrem heisser, entflammbarer Flüssigkeit. Für den ordnungsgemässen Betrieb wird Spezialtreibstoff benötigt. Dieses Modell wurde so modifiziert, dass es ein heisseres Gemisch verspritzt, das sich leichter entzündet.\n Min. ST: 6.}
{40100}{}{Lasergewehr (Erw. Kap.)}
{40101}{}{Dieses Wattz 2000 Laser-Gewehr wurde mit einem verbesserten Ladesystem und einem speziellen Recycling-Chip ausgestattet, der den Verbrauch der Mikro-Fusionszelle um 50%.\n senkt. Min. ST: 6.}
{40200}{}{Magneto-Laserpistole}
{40201}{}{Diese Wattz-1000-Laserpistole wurde mit einem magnetischen Zielsystem aufgerüstet, das den Laserstrahl bündelt und der Pistole dadurch mehr Durchschlagskraft verleiht.\n Min. ST: 3.}
{40300}{}{Henrys Gewehr}
{40301}{}{Ein altes, aber immer noch zuverlässiges Karabinergewehr, entworfen zur Zeit des "Goldrauschs". Als beliebte Sportwaffe, Sammlerobjekt und Statussymbol wurde es bis zum Grossen Krieg für die Zivilbevölkerung hergestellt.\n Min. ST: 4.}
{40400}{}{Desert Eagle (Erw. Mag.)}
{40401}{}{Eine uralte Desert-Eagle-Pistole im Kaliber .44 Magnum. Das Interesse an Filmen des späten 20. Jahrhunderts machte sie zu einer der beliebtesten Handfeuerwaffen aller Zeiten. Dieses Exemplar hat ein erweitertes Magazin für noch mehr Spass und Spielereien!\n Min. ST: 5.}
{40500}{}{Sturmgewehr (Erw. Mag.)}
{40501}{}{Dieses Sturmgewehr hat ein verlängertes Magazin in Militärgrösse. Die erweiterte Magazinkapazität macht blindes Dauerfeuer so unterhaltsam wie nie zuvor.\n Min. ST: 5.}
{40600}{}{Plasmapistole (Erw. Kap.)}
{40601}{}{Bei dieser Glock-86-Plasmapistole wurde die Magnetkammer neu ausgerichtet, um den Verbrauch der Energiezelle zu senken. Ihre Effizienz hat sich verdoppelt, sodass sie mehr Schüsse abgeben kann, bevor die Batterie leer ist.\n Min. ST: 4.}
{40700}{}{Mega-Powerfaust}
{40701}{}{Eine "Big Frigger"-Powerfaust von BeatCo. Viele halten sie für die ultimative Waffe im unbewaffneten Kampf. Dieses Exemplar hat verbesserte Kraftservos für mehr Schlagkraft. Betrieb mit kleinen Energiezellen.\n Min. ST: 1.}
{40800}{}{Feldsanitäter-Erste-Hilfe-Kasten}
{40801}{}{Ein kleines Set mit grundlegender medizinischer Notfallausrüstung. Verbände, Wickel, antiseptisches Spray und mehr.}
{40900}{}{Sanitätertasche}
{40901}{}{Diese Tasche enthält Instrumente und Chems, die Sanitäter im Einsatz verwenden. Die Werkzeuge sind speziell für schwere Verletzungen und Notfälle ausgelegt.}
{41000}{}{Erweitertes Dietrichset}
{41001}{}{Ein Satz Werkzeuge für Schlosser. Enthält alle nötigen Dietriche und Spannwerkzeuge, um herkömmliche Stiftzuhaltungsschlösser zu öffnen. Dieses Set umfasst auch Spezialwerkzeuge für schwierigere mechanische Schliessmechanismen.}
{41100}{}{Elektronischer Dietrich MKII}
{41101}{}{Dies ist der elektronische Dietrich Wattz Electronics Micromanipulator FingerStuff der zweiten Generation. Zum überwinden elektronischer Schlösser und Sicherheitseinrichtungen. Diese Mark-II-Version enthält aktualisierte Software und Schnittstellenwerkzeuge.}
{41200}{}{Waffenteile}
{41201}{}{Teile verschiedener Schusswaffen. Sie können zur Reparatur oder Verbesserung anderer Waffen verwendet werden.}
{41300}{}{Foto eines Mädchens}
{41301}{}{Vor dir liegt das Bild eines nackten Mädchens, dessen Augen mit Lötkolben ausgebrannt wurden. Das Mädchen scheint sehr hübsch gewesen zu sein. Auf der Rückseite steht: "Virginia Street, 75".}
{41400}{}{Kellerschlüssel}
{41401}{}{Ein Standardschlüssel für das Türschloss am Bahnhof von New Reno.}
{41500}{}{Gecko-Ei}
{41501}{}{Daraus könnte einmal ein niedliches und lustiges Tier werden. Stattdessen dient es jemand Reichem als Nahrung.}
{41600}{}{Tribut von Stryker}
{41601}{}{Ein Metallkoffer für Diplomaten, bezogen mit Brahminleder. Für Big Louie bestimmt. Der Inhalt des Koffers ist unbekannt.}
{41700}{}{Laborschutzhelm}
{41701}{}{Einst war dieser Schutzhelm Teil eines hermetischen Chemikalienschutzanzugs. Jetzt ist er das einzige verbliebene Teil.}
{41800}{}{Rattenfalle}
{41801}{}{Ein uraltes mechanisches Gerät. Hervorragend gegen kleine, hirnlose Tiere.}
{41900}{}{Mantis-Snack}
{41901}{}{Ein fachgerecht zubereitetes Mantisbein.}
{42000}{}{"Blinde Wut"}
{42001}{}{Ein abgenutztes Schwert mit Holzscheide, die als Gehstock getarnt ist. Die Stahlqualität lässt zwar zu wünschen übrig, doch diese Waffe hat ihrem Besitzer eindeutig schon mehr als einmal das Leben gerettet.\n Min. ST: 3.}
{42100}{}{Pulvergranate}
{42101}{}{Selbstgebastelte Handgranate mit chemischem Zünder. Um einen starken Pulverzünder herum sind Splitter angebracht.}
{42200}{}{Shampoo}
{42201}{}{Eine Flasche Shampoo. Vor dem Krieg war diese Marke ziemlich bekannt.}
{42300}{}{Wurzelbier}
{42301}{}{Eine Sorte Wurzelbier, über dem Lagerfeuer gebraut. Macht den Kopf leicht benebelt, hat aber heilende Eigenschaften.}
{42400}{}{Taktische Rakete}
{42401}{}{Seltene Munition: eine Rakete mit angereichertem Uran für einen Granatwerfer. Heb sie dir für einen besonderen Anlass auf.}
{42500}{}{Posten des Aufsehers}
{42501}{}{Der Posten des Aufsehers, in dem eine seit Langem verwesende Leiche liegt. Von ihr hat sich eine biologische Seuche im ganzen Posten ausgebreitet.}
{42600}{}{Kisten}
{42601}{}{Zwei grosse Holzkisten. Die Aufschriften an den Seiten sind nicht mehr zu erkennen.}
{42700}{}{Flammender Atem}
{42800}{}{Habseligkeiten des Schamanen}
{42801}{}{Die persönlichen Habseligkeiten des Niskigvan. Darunter sind verschiedene Werkzeuge, die beim Sammeln und Verarbeiten von Heilpflanzen nützlich sind.}
{42900}{}{Goldzahn}
{42901}{}{Du hast Tuco den Goldzahn aus dem Kiefer geschlagen. Jetzt gehört er dir.}
{43000}{}{Mantisgliedmasse}
{43001}{}{Knuspriges Glied einer riesigen Insektenart.}
{43100}{}{Pistolenteil}
{43101}{}{Spezielle Hinterschaft-Holster-Kombination für eine 9-mm-Pistole. Darin findest du ausserdem alle nötigen Teile und Werkzeuge zur Reinigung und einfachen Reparatur.}
{43200}{}{Jacke eines Bik ers}
{43201}{}{Eine abgetragene Kampfjacke mit einem Biker-Aufnäher. Eine Schicht aus Folie und Metall bietet besseren Schutz vor Laser- und Plasmäinwirkung.}
{43300}{}{Amulett der Cheyenne}
{43301}{}{Das Totemamulett des Anführers des Cheyenne-Stammes. Wenn du es in den Händen hältst, lächelt dir das Glück selbst zu.}
{43400}{}{Wagen}
{43401}{}{Ein Karawanenwagen, der aus den überresten eines uralten Autos gebaut wurde.}
{43500}{}{Wagen}
{43501}{}{Ein Karawanenwagen, der aus den überresten eines uralten Autos gebaut wurde.}
{43600}{}{Kartenspiel}
{43601}{}{Ein normales Kartenspiel.}
{43700}{}{Gezinktes Kartenspiel}
{43701}{}{Ein normales Kartenspiel mit speziellen, unauffälligen Markierungen auf der Rückseite.}
{43800}{}{Reaktor-Zugangskarte}
{43801}{}{Elektronische Zugangskarte zur Reaktorebene im Hangar V9.}
{43900}{}{Rezept: "Mantis-Snack"}
{43901}{}{Kochrezept für Snacks aus Mantisfuss, in Bier eingelegt und mit Stücken Mutfrucht gebraten.}
{44000}{}{Brahminmilch}
{44001}{}{Nahrhafte Brahminmilch. Sie enthält viele Nährstoffe, die allerdings durch ... Radioaktivität ausgeglichen werden.}
{44100}{}{Hundemarke}
{44101}{}{Eine Marke mit dem Namen des Hundes und seines Besitzers.}
{44200}{}{Sicherung}
{44201}{}{Ein dünnens Drahtstück in einer luftleeren Glashülle, das bei elektrischer überlastung für die Sicherheit der Anlage sorgt.}
{44300}{}{Vergifteter Selbstgebrannter}
{44301}{}{Flasche Selbstgebrannter, versetzt mit tödlichem Gift.}
{44400}{}{"Handbuch des Saboteurs"}
{44401}{}{Beliebte Aufsätze des alten Kriegers Maddox, eines Veteranen von Sabotage- und Aufklärungseinsätzen. Der Autor enthüllt die Methoden von Sabotageaktionen und berichtet von Fallen und Massenvernichtungsgeräten.}
{44500}{}{Schuldschein}
{44501}{}{Quittung für Spielschulden im Casino "Eldorado".}
{44600}{}{Gedankenauslöscher}
{44601}{}{Diese Technologie ermöglicht es, eine bestimmte Erinnerung von kurzer Dauer zu löschen und durch eine andere, illusorische zu ersetzen. So kann man aus einem Feind einen Freund machen. Aber wenn es schiefgeht, werden einem solche Scherze nicht verziehen.}
{44700}{}{Vertrag über den Kauf von Sklaven}
{44701}{}{Das ist dein Vertrag mit der Sklavenhändlergilde von Vegas über den Erwerb einer grossen Gruppe von Sklaven.}
{44800}{}{Brief an Eric}
{44801}{}{"Eric, sie wollen dich im Ring kämpfen lassen. Du weisst, was das bedeutet. Wie auch immer, das ist nur gut für uns! Wenn du aus dem Gehege kommst, beginnt eine Schiesserei. In dem Moment renn so schnell du kannst! Mach dir keine Sorgen um mich. Dein Bruder Gareth".}
{44900}{}{Nicht benutzen}
{44901}{}{Nicht benutzen!}
{45000}{}{---}
{45001}{}{---}
{45100}{}{Notiz eines Goldsuchers}
{45101}{}{Diese Notiz lag bei der Leiche eines Goldsuchers in Hawthorne. Darauf steht: "Wenn ich sterbe, sagt meiner Familie in Reno, dass ich sie liebe." Unterschrift: Robert Gate.}
{45200}{}{Mittagessenmarke}
{45201}{}{Diese Marke mit dem Nuka-Cola-Symbol wurde aus einem alten Pokerchip gefertigt.}
{45300}{}{Flaschenkiste}
{45301}{}{Diese Holzkiste dient dem sicheren Transport von Glasflaschen.}
{45400}{}{Wagen}
{45401}{}{Dieser Karawanenwagen wurde speziell für den Transport von Flaschen vorbereitet.}
{45500}{}{Kofferraum}
{45501}{}{Der Kofferraum ist ein guter Ort, um deinen Kram zu verstauen.}
{45600}{}{Big Louies Schlüssel}
{45601}{}{Ein Haufen Schlüssel aus dem Raider-Stützpunkt in Lovelock.}
{45700}{}{Gutschein für David und Norman}
{45701}{}{Die Quittung, laut der Norman sich verpflichtet, Davids Spielschulden mit seiner eigenen Nebenniere zu begleichen.}
{45800}{}{Ely Gorbinskys Akte}
{45801}{}{Auf dem Etikett steht: "Ely Gorbinskys Akte, vorläufiger Bericht".}
{45900}{}{---}
{45901}{}{---}
{46000}{}{Jays Nachricht}
{46001}{}{Diese Holodisk enthält eine persönliche Nachricht an dich.}
{46100}{}{Bericht über Deserteure}
{46101}{}{Holodisk von Hawthorne mit einem Bericht über eine Gruppe geflüchteter Militärangehöriger.}
{46200}{}{---}
{46201}{}{---}
{46300}{}{Medizinischer Bericht}
{46301}{}{Auf dem Etikett steht: "Empfehlungen zur Behandlung des Kopfes des ehemaligen Präsidenten".}
{46400}{}{Aufzeichnungen eines Bürgerlichen}
{46401}{}{Tagebucheinträge eines Bewohners eines Regierungsbunkers. Ziemlich interessante Lektüre. Dieser Text kann auf deinen Pip-Boy kopiert werden.}
{46500}{}{"Exodus"}
{46501}{}{Holodisk mit Informationen über das Regierungsbunker-Projekt.}
{46600}{}{Fernbedienung}
{46601}{}{Fernbedienung für das Kraftfeld. Reichweite: 12 Fuss.}
{46700}{}{Kapuze}
{46800}{}{Sandwich}
{46801}{}{Nahrhaftes Sandwich aus Brahminfleisch, bedeckt mit dicker, dunkelgelber Sosse, zwischen zwei Hälften eines köstlichen weichen Brötchens und einem Stück Grünzeug. Köstlich.}
{46900}{}{Rot Gut}
{46901}{}{Ein sehr starker Schnaps. Oder Reinigungsflüssigkeit, ganz wie du willst.}
{47000}{}{Zertrümmerer}
{47001}{}{Ein grosser Hammer mit massivem Griff und selbstgemachten Spitzen am Kopf, um den Schaden zu erhöhen. Zum Zubereiten von Koteletts nimmt man besser einen kleineren Hammer.\n Min. ST: 6.}
{47100}{}{Das Handbuch der Neurochirurgie}
{47101}{}{Ein sehr seltenes Handbuch für hochqualifizierte Chirurgen. Hier sind offenbar sehr wichtige Informationen gesammelt, aber sie sind so wissenschaftlich und komplex, dass das Studium viel Zeit und Mühe kosten wird.}
{47200}{}{Dem Tod ins Auge sehen}
{47201}{}{Du bist mutig und findest dich deshalb leichter zurecht, wenn um dich herum alles drunter und drüber geht.}
{47300}{}{Verstrahlte Nuka-Cola}
{47301}{}{Erstaunliches Vorkriegsgetränk in einer leicht schmutzigen Flasche. Hat einen wunderbaren Nachgeschmack und leuchtet nachts äusserst fragwürdig.}
{47400}{}{Magnet-Laserpistole I2}
{47401}{}{Diese Wattz-1000-Laserwaffe wurde mehrfach verbessert. Dadurch erhöht sich ihre Kapazität um 50 %, auf Kosten von Reichweite und Energieverbrauch.\n Min. ST: 3.}
{47500}{}{Nicht benutzen}
{47501}{}{Nicht benutzen!}
{47600}{}{"Bloody Mary"}
{47601}{}{Ein hochprozentiger alkoholischer Cocktail. Sehr nützlich nach einem harten Tag am Ende der Woche.}
{47700}{}{Aktenkoffer mit Dokumenten}
{47701}{}{Der Aktenkoffer enthält Berichte vom Radiosender in Lovelock. Darin ist oft von Vault 8 die Rede. Leider sind die meisten verschlüsselt, aber die übrigen kannst du in deinen Pip-Boy eingeben.}
{47800}{}{---}
{47801}{}{---}
{47900}{}{Giftgas}
{47901}{}{Ein Hochdruckzylinder mit äusserst gefährlichem Gas. Dient dazu, im Notfall alles Leben im Hangar von Area 51 auszulöschen.}
{48000}{}{Guter Schlaf}
{48001}{}{Nach einer erholsamen Nacht im Hotel erhältst du eine Stunde lang einen Bonus von +1 auf Wahrnehmung und Intelligenz.}
{48100}{}{Gesteigerte Wahrnehmung}
{48101}{}{Der Besuch von Orten mit hervorragender Aussicht steigert vorübergehend deine Wahrnehmung.}
{48200}{}{Turbo-Cola}
{48201}{}{Droge aus Eigenherstellung. Löst einen kurzen Adrenalinschub aus, danach verursacht ein starker Druck auf die Arterien heftiges Fieber.}
{48300}{}{Kamera}
{48301}{}{Ein uraltes Fotogerät der Firma "Kodak". Zum Betrieb wird ein Film mit 24 Aufnahmen benötigt.}
{48400}{}{Nelsons Schlüssel}
{48401}{}{Standardschlüssel für das Lagerhaus im Tunnel von Uranium City.}
{48500}{}{Spind}
{48501}{}{Automatischer Schliessfachschrank zur Aufbewahrung von Gegenständen. Mit einem Sprachsteuerungssystem ausgestattet, das aus irgendeinem Grund nicht funktioniert.}
{48600}{}{Spind}
{48601}{}{Automatischer Schliessfachschrank zur Aufbewahrung von Gegenständen. Mit einem Sprachsteuerungssystem ausgestattet, das aus irgendeinem Grund nicht funktioniert.}
{48700}{}{Katalog von "Chryslus Motors"}
{48701}{}{Eine Publikation des Automobilherstellers "Chryslus Motors". Enthält viele nützliche Informationen für Fahrer und Automechaniker.}
{48800}{}{Antipersonenmine}
{48801}{}{Eine druckempfindliche Mine, die dazu dient, feindliche Truppen auszuschalten.}
{48900}{}{Spezielle Boxerwaffe}
{49000}{}{Aufzeichnungen des Offiziers}
{49001}{}{Holodisk mit Tonaufnahmen des Soldaten.}
{49100}{}{Mr.-Nixon-Puppe}
{49101}{}{Du siehst eine kleine Puppe mit einer grossen roten Nase. Aus irgendeinem Grund traust du diesem scheinbar harmlosen Kinderspielzeug nicht.}
{49200}{}{Tanker-Fob}
{49201}{}{Ein codierter Zugangsschlüssel, der Zutritt zu Hochsicherheitsbereichen gewährt.}
{49300}{}{Zeitungsausschnitte}
{49301}{}{Ein Stapel Seiten, aus verschiedenen Zeitungen herausgerissen. Alle handeln vom selben Thema - dem grossen Verlust von Big Louie.}
{49400}{}{Saurechsenfell}
{49401}{}{Von der Haut einer Saurechse gerissen. Geschätzt für seine feuerfesten und plasmaresistenten Eigenschaften.}
{49500}{}{Sonderausweis}
{49501}{}{Eine elektronische Zugangskarte für viele Regierungstresore.}
{49600}{}{Bos Stange}
{49601}{}{Eine sehr stabile und gut ausbalancierte Stange mit abgerundeten Enden, an denen weiche Polster befestigt sind. Trainingsversion der Firma "Hattori Souvenirs".\n Min. ST: 3.}
{49700}{}{Kubotan}
{49701}{}{Eine uralte, nichttödliche Waffe, ursprünglich für die Polizei entwickelt. Sie ist eine ausgezeichnete Hilfe im Kampf, aber nur für diejenigen, die über ausreichende Kampfsportkenntnisse verfügen. Min. ST: 1.}
{49800}{}{Doppelplasmakanone}
{49801}{}{Nur für das Geschütz-Turm-Kreatur verwenden.}
{49900}{}{Konservendose}
{49901}{}{Vor dir steht eine Dose Hundefutter. Dem Datum auf dem Deckel nach ist sie über 70 Jahre alt. Wenn du es wagst, sie zu öffnen, solltest du vorher besser eine Gasmaske aufsetzen.}
{50000}{}{Alter Revolver}
{50001}{}{Ein sehr altes Modell eines einst beliebten Revolvers. Vielleicht ein Ausstellungsstück im Museum.\n Min. ST: 1.}
{50100}{}{Wandtresor}
{50200}{}{Bodentresor}
{50300}{}{Blaues Speichermodul}
{50301}{}{Ein Nur-Lese-Speichermodul mit medizinischen Informationen. Dieses Modul beschreibt Verbesserungen der Ausstrahlung.}
{50400}{}{Grünes Speichermodul}
{50401}{}{Ein Nur-Lese-Speichermodul mit medizinischen Informationen. Dieses Modul beschreibt Verbesserungen der Wahrnehmung.}
{50500}{}{Rotes Speichermodul}
{50501}{}{Ein Nur-Lese-Speichermodul mit medizinischen Informationen. Dieses Modul beschreibt Verbesserungen der Stärke.}
{50600}{}{Gelbes Speichermodul}
{50601}{}{Ein Nur-Lese-Speichermodul mit medizinischen Informationen. Dieses Modul beschreibt Verbesserungen der Intelligenz.}
{50700}{}{Verwesende Leiche}
{50701}{}{Dies ist die teilweise verweste Leiche eines humanoiden Wesens.}
{50800}{}{10-mm-Pistole (verl. Magazin)}
{50801}{}{Selbstladepistole Colt 6520 im Kaliber 10 mm mit erweitertem Magazin.\n Min. ST: 3.}
{50900}{}{Maxsons abgesägte Schrotflinte}
{50901}{}{Eine alte Schrotflinte, die einst dem Raider Maxson gehörte. Lauf und Schaft wurden gekürzt, damit sich die Schrotkugeln weiter verteilen.\n Min. ST: 5.}
{51000}{}{Billardtisch}
{51100}{}{Billardtisch}
{51200}{}{Billardtisch}
{51300}{}{Billardtisch}
{51400}{}{Billardtisch}
{51500}{}{Billardtisch}
{51600}{}{Karte des Sees}
{51601}{}{Eine zerknitterte Vorkriegslandkarte der Umgebung von Salt Lake City und seines grossen Sees. über die ganze Karte verstreut finden sich Markierungen, die auf lokale Sehenswürdigkeiten und Einrichtungen hinweisen. Praktisch ein Reiseführer.}
{51700}{}{Hackbeil}
{51701}{}{Ein riesiges Messer zum Schneiden von Fleisch.\n Min. ST: 3.}
{51800}{}{Doppel-Minigun}
{51801}{}{Nur für Auto-Cannon-Kreaturen verwenden.}
{51900}{}{Flaschenkappen}
{51901}{}{Diese wertlosen Flaschenkappen stammen aus der Nuka-Cola-Fabrik. Einer Legende nach werden sie eines Tages viel mehr wert sein als heute. Doch momentan klingt das für dich wie ein seltsames Märchen.}
{52000}{}{Schwere Doppel-Minigun}
{52001}{}{Nur für Auto-Cannon-Kreaturen verwenden.}
{52100}{}{Zerlegetisch}
{52101}{}{Ein Tisch zum Zerlegen von Beute.}
{52200}{}{Rostige Machete}
{52201}{}{Jemand hat ein Rasenmähermesser bearbeitet, eine Kante geschärft und den Griff fest mit Brahminhaut umwickelt.\n Min. ST: 5.}
{52300}{}{"Trade"-Magazin}
{52301}{}{Ein wöchentliches Vorkriegsmagazin für Leute, die ihr eigenes Geschäft führten. Auch wenn sich die Zeiten geändert haben, kannst du dieser Ausgabe noch nützliche Informationen über den Handel entnehmen.}
{52400}{}{Abgetragene Jacke}
{52401}{}{Diese dreckige, stinkende Jacke gehörte einst einem Raider. Sie ist so abgetragen, dass du die Fäden reissen hörst, wenn du dich bewegst.}
{52500}{}{Diesels Kaugummi}
{52501}{}{Methamphetamin-Kaugummi, eingewickelt in einen Zeitungsfetzen. Laut Diesel stimuliert es für kurze Zeit das zentrale Nervensystem.}
{52600}{}{überreste}
{52601}{}{überreste des Vault-Bewohners. Die Leiche liegt schon so lange hier, dass sie bis auf die Knochen verwest ist.}
{52700}{}{überreste}
{52701}{}{überreste des Vault-Bewohners. Die Leiche liegt schon so lange hier, dass sie bis auf die Knochen verwest ist.}
{52800}{}{Ira Kane}
{52801}{}{Dieser Kerl scheint an einer Methanvergiftung gestorben zu sein.}
{52900}{}{Kochherd}
{52901}{}{Ein gewöhnlicher Kochherd. Er wurde schon lange nicht mehr zu seinem eigentlichen Zweck benutzt.}
{53000}{}{Kamin}
{53001}{}{Einst ein schöner Zierkamin mit dem Foto eines indischen Philosophen.}
{53100}{}{Laserpistole (Polizei)}
{53101}{}{Laserpistole Wattz 1500, Polizeimodell. Dank Kristallen statt billiger Dioden ist sie leistungsstärker als zivile Modelle.\n Min. ST: 3.}
{53200}{}{---}
{53300}{}{---}
{53400}{}{---}
{53500}{}{---}
{53600}{}{---}
{53700}{}{---}
{53800}{}{---}
{53900}{}{---}
{54000}{}{---}
{54100}{}{---}
{54200}{}{---}
{54300}{}{---}
{54400}{}{---}
{54500}{}{---}
{54600}{}{---}
{54700}{}{---}
{54800}{}{Munitionskiste}
{54801}{}{Seltene Munition grossen Kalibers für sehr schwere Maschinengewehre - so schwer, dass du nicht einmal weisst, für welche.}
{54900}{}{Zip Gun}
{54901}{}{Ein armseliger Pistolenverschnitt, bekannt als Zip Gun. Der Name sagt alles.\n Min. ST: 1.}
{55000}{}{Werkzeugregal}
{55100}{}{Geldbeutel}
{55101}{}{Ein männlicher, abgenutzter Geldbeutel mit diversen Dokumenten und Geschäftsnotizen. Für dich ist nichts Wertvolles dabei, aber der Verlust dieses Dings wird dem Vorbesitzer sicher zu schaffen machen.}
{55200}{}{Lizenz}
{55201}{}{Das ist deine persönliche Verkaufslizenz, ausgestellt vom Hersteller des berühmten Tonic-Getränks "Nuka-Cola".}
{55300}{}{Reiseticket}
{55301}{}{Einfache Fahrkarte für die Postkutsche.}
{55400}{}{Stücke}
{55401}{}{Metallplatten in der Grösse einer gewöhnlichen Münze. Theoretisch sollten sie völlig nutzlos sein.}
{55500}{}{Unverzichtbare Münze}
{55501}{}{Das ist eine vollwertige Jubiläumsmünze ... wäre da nicht jemand gewesen, der ein Loch hineingebohrt und einen starken Faden hindurchgezogen hat.}
{55600}{}{Metalldetektor}
{55601}{}{Das Gerät wird mit Nuklearbatterien betrieben. Es dient dazu, Metallgegenstände in einem Umkreis von bis zu 4 Metern aufzuspühren.}
{55700}{}{Metalldetektor}
{55701}{}{Das Gerät wird mit Nuklearbatterien betrieben. Es dient dazu, Metallgegenstände in einem Umkreis von bis zu 9 Metern aufzuspühren. Der eingebaute Ultraschallscanner hat die Reichweite verdoppelt.}
{55800}{}{C-4-Sprengstoff}
{55801}{}{Kiste mit Plastiksprengstoff für den Militäreinsatz.}
{55900}{}{Anzug eines Karawanenhändlers}
{55901}{}{Spezielle Kleidung, die die Bewegungsfreiheit in der Wüste maximiert. Schutzbrille und Staubmaske sind inklusive.}
{56000}{}{Strahlenschutzanzug}
{56001}{}{Zuverlässiger persönlicher Schutz vor radioaktiver Strahlung.}
{56100}{}{Gas-Schutzanzug}
{56101}{}{Schutzanzug für Arbeiter, die schmutzige und stinkende Arbeiten verrichten. Er wird mit Gasmaske, Gummistiefeln und abnehmbarer Brille geliefert. Schützt gut vor schädlichen Dünsten in der Luft, ist aber sehr unbequem zu tragen.}
{56200}{}{"Atomic Blades"}
{56201}{}{Packung Rasierklingen. Hergestellt von "Pretty & Glamour" in Knoxville, Tennessee. Auf der Schachtel sind Atomwaffentests im Pazifik abgebildet.}
{56300}{}{Seifenreste}
{56301}{}{Duftseife der Firma "Pretty & Glamour" mit Bissspuren. Den Zahnabdrücken nach zu urteilen, hat ein Erwachsener hineingebissen.}
{56400}{}{Zahnpasta}
{56401}{}{Zahnpasta mit Thorium. Hergestellt von der Firma "Pretty & Glamour". Poliert sanft den Zahnschmelz und macht die Zähne weiss und glänzend. Ihr Glanz ist sogar im Dunkeln zu sehen.}
{56500}{}{Comic}
{56501}{}{Lustige Comics über den fröhlichen Pip-Boy, der ständig auf seinem Hintern nach Abenteuern suchte.}
{56600}{}{Heilwasser}
{56601}{}{Kleine Flasche angeblich heilenden Wassers "Radium" von der Firma "Pretty & Glamour".}
{56700}{}{Colt-Revolver}
{56701}{}{Sehr maachtige, exklusive Waffe. Die Oberfläche ist mit traditionellen indianischen Mustern verziert. Wenn du sie im flackernden Licht von Vegas betrachtest, fühlst du dich wie ein Gott.\n Min. ST: 5.}
{56800}{}{"Black Dynamite"}
{56801}{}{Extrem cooler und stilvoller Revolver.\n Min. ST: 6.}
{56900}{}{Badesalz}
{56901}{}{Salz der Firma "Pretty & Glamour", um das Badewasser mit Radon anzureichern. Es wird bei Nervenleiden, Schlaflosigkeit, Kraftlosigkeit, Arthritis und Rheuma verwendet.}
{57000}{}{Rülpser}
{57001}{}{Stinkender Rülpser eines Säuregeckos.\n Min. ST: 1.}
{57100}{}{REZ-4}
{57101}{}{Seltene elektromagnetische Waffe. Du hast Glück ... wenn du mit einer Waffe dieser Grösse umgehen kannst. Ausserdem gibt es keine Möglichkeit, den Akku wieder aufzuladen. Ist die Ladung verbraucht, wird die Waffe nutzlos.\n Min. ST: 8.}
{57200}{}{Flegel}
{57201}{}{Die brutale Waffe der Biker: eine grosskalibrige Kette mit einer schweren Metallkugel am Ende.\n Min. ST: 5.}
{57300}{}{Rostiges Katana}
{57301}{}{Schwert aus dem Geschenkset der Firma "Hattori Souvenirs". Obwohl die Waffe ihrem japanischen Vorbild qualitativ deutlich unterlegen ist, kann sie in einer starken Hand den Gegner dauerhaft vom Schlachtfeld entfernen, selbst wenn er eine Rüstung trägt.\n Min. ST: 4.}
{57400}{}{Beatnik-Brille}
{57401}{}{Runde Brille. Nichts Besonderes, sieht aber stilvoll aus.}
{57500}{}{Gerades Rasiermesser}
{57501}{}{Rasiermesser mit offener Klinge von "Sharpy wits". Immer noch sehr scharf.\n Min. ST: 1.}
{57600}{}{Schmerzmittel}
{57601}{}{Diese Patrone ist mit einem starken Vorkriegs-Schmerzmittel gefuellt. Das Medikament ist seit mehr als 40 Jahren abgelaufen und schädigt Herz und Blutgefässe deshalb noch stärker und unumkehrbarer als zuvor.}
{57700}{}{Feuchttücher}
{57701}{}{Versiegelte Packung mit Damenbinden. Kann auf Wanderschaft durch das ödland ein Bad ersetzen. Hergestellt von der Firma "Pretty & Glamour".}
{57800}{}{Alte Futterdose}
{57801}{}{Eine geöffnete Dose, in der über 70 Jahre altes Hundefutter war. Sieht so aus, als hätte der Kerl dich reingelegt! (Alle zeigen spottend mit dem Finger auf dich und lassen ein langgezogenes "Iiiih!" hören)}
{57900}{}{Lagerausweis}
{57901}{}{Elektronische Zugangskarte für das AKW "Poseidon Oil".}
{58000}{}{Ausweis für Betriebspersonal}
{58001}{}{Elektronische Zugangskarte für das AKW "Poseidon Oil".}
{58100}{}{Pizza}
{58101}{}{Ausgezeichnete Pizza mit Gecko-Fleisch und Pilzen. Und jede Menge Pfeffer.}
{58200}{}{Shitposters Kraut}
{58201}{}{Das ist alles, was von Shitposter übrig ist - ein unscheinbares und scheinbar harmloses Krautbündel. Auf keinen Fall verwenden.}
{58300}{}{Nuka-Cola (Kirsche.)}
{58301}{}{Eine Flasche Nuka-Cola, ein aromatisiertes alkoholfreies Getränk aus der postnuklearen Welt. Es wird aus den Blättern mutierter Coca-Pflanzen und dem Saft einiger Früchte hergestellt. Warm und abgestanden. Mit Kirschgeschmack.}
{58400}{}{Nuka-Cola mit Geschmack}
{58401}{}{Flasche selbstgemachte Nuka-Cola. Jemand wollte wohl Geld verdienen, indem er dieses minderwertige Produkt unter Umgehung des "offiziellen" Herstellers verkauft.}
{58500}{}{"Desert Eagle"}
{58501}{}{"Desert Eagle", Kaliber .44 Magnum. Mit modernem, präzisem Visier ausgestattet.\n Min. ST: 5.}
{58600}{}{Ring}
{58601}{}{Ein massiver Metallring in Form eines Totenkopfs. Ziemlich brutales Schmuckstück. Er war so in die Haut eingewachsen, dass du den Finger samt Ring abtrennen musstest.}
{58700}{}{Vertrag mit dem Drogendealer}
{58701}{}{Der Vertrag zwischen Fatso und dem Drogendealer über den Erwerb einer Lieferung chemischer Rohstoffe. Auf der Rückseite steht eine Zusage für ein Geschäft - Wetten auf die Kämpfer im Ring "Eldorado".}
{58800}{}{Notiz des Killers}
{58801}{}{Beweisstück, das am Körper des Killers auf dem Parkplatz in New Vegas gefunden wurde. Es sieht ganz so aus, als hätte dieser Techniker von Wind of War ein Kopfgeld auf dich ausgesetzt! Und dazu noch seine eigenen Leute eingesetzt.}
{58900}{}{Emulgator E30}
{58901}{}{Eine bröckelige gelbe Substanz mit einem unerträglichen Geruch, als hätte man hunderte Muelltonnen vor sich. Auch ihr Aussehen macht keinen vertrauenerweckenden Eindruck.}
{59000}{}{Gellers Geständnis}
{59001}{}{Holodisk mit einer Aufnahme, die du während eines Gesprächs mit Larry Geller gemacht hast. Dabei gestand Larry, einst Drogen hergestellt zu haben. Das sollte der Polizei genügen.}
{59100}{}{Quittung des Sklavenhändlers}
{59101}{}{Die Geschäftsunterlagen und Notizen des Leiters der Sklavenhändlergilde. Einige Informationen kommen dir interessant vor: "...Der Boss hat angeordnet, mit den Ghulen zu warten, bis sie auf Drogen sind. Danach werden sie kein Problem mehr sein. Wir sollten bereit sein, die benötigte Anzahl Sklaven zu einem wirklich guten Preis an den Damm zu verkaufen."}
{59200}{}{Verdächtiges Paket}
{59201}{}{Diese Droge hat dir Hal Wallace gegeben, damit du sie im Hotel der Freaks unterbringst.}
{59300}{}{Belastendes Beweismaterial gegen H. Wallace}
{59301}{}{Holodisk mit einer Aufnahme, die du während eines Gesprächs mit Hal Wallace darüber gemacht hast, wie du einen Job bei den Freaks bekommst. Die Polizei dürfte das interessant finden.}
{59400}{}{"Desert Eagle"}
{59401}{}{"Desert Eagle" .44 Magnum, im Besitz von Bob Neil. Neben ihrem beeindruckenden Aussehen verfügt sie über einen verbesserten Mechanismus, der die Feuerkraft dieser Waffe erhöht.\n Min. ST: 5.}
{59500}{}{Geständnis von H. Wallace}
{59501}{}{Holodisk mit einer Aufnahme, die du während eines Gesprächs mit Hal Wallace darüber gemacht hast, wie du einen Job bei Bob Neil bekommst. Ein direkter Beweis.}
{59600}{}{Quittung von O. Davis}
{59601}{}{Dieses Dokument enthält Angaben zu ungewöhnlich hohen Gebühren, die die Gemeinde Las Vegas an O. Davis gezahlt hat. Offenbar soll die Polizei bei Drogendelikten Vorrang haben. Die Notiz ist von T. Parker unterzeichnet. Aber warum diese hohen Kosten? Und warum interessiert sich das Bürgermeisteramt so sehr dafür?}
{59700}{}{Quittung von Tom Parker}
{59701}{}{Ein Dokument der Stadtverwaltung von Las Vegas mit der Anordnung, 6% of der Gemeindeanteile an den Anführer von Slavertown zu übertragen. Entwurf von T. Parker. Die Unterschrift zur Ausführung fehlt noch.}
{59800}{}{Larry über Phillips}
{59801}{}{Holodisk mit einer heimlich während eines Gesprächs mit Larry Geller gemachten Aufnahme über Sam Phillips. Er sagte aus, dass Phillips einst Kontakt zu Drogenhändlern hatte.}
{59900}{}{Drogenhändler über Phillips}
{59901}{}{Holodisk mit einer heimlich während eines Gesprächs mit dem Drogenhändler gemachten Aufnahme über Sam Phillips. Er sagte aus, dass Phillips einst Kontakt zu Drogenhändlern hatte.}
{60000}{}{Notizen aus The Pound}
{60001}{}{Die Notizen und Aufnahmen aus dem Labor von "The Pound". Sie enthalten Informationen über die Herstellung und den Versand grosser Mengen von Rauschmitteln in den letzten Monaten. Unter mehreren Abnehmern fällt dir ein ungewöhnlicher auf: das Casino "Three-card Monte".}
{60100}{}{Belastendes Material über Bob Neil}
{60101}{}{Aufnahme deines Gesprächs mit Bob Neil, in dem er dich offen auffordert, Hal Wallace zu beseitigen.}
{60200}{}{Soldatenmarke}
{60201}{}{In diese Marke sind persönliche Angaben ihres Besitzers eingraviert: Name, Geburtsdatum, eine Seriennummer und weitere genaue Daten.}
{60300}{}{---}
{60400}{}{---}
{60500}{}{Powerrüstung}
{60501}{}{Dies ist deine persönliche Rüstung, ausgestattet mit autonomen Systemen, die sie der hochtechnologischen Vorkriegsrüstung T-51b ähnlich machen.}
{60600}{}{Autonomes System der T-51b-Rüstung}
{60601}{}{Ein komplexes System miteinander verbundener Geräte, darunter ein kleiner Kernreaktor, ein Exoskelett-Antriebsmodul, eine Kühleinheit und weitere Komponenten, die für den Zusammenbau der T-51b-Powerrüstung benötigt werden.}
{60700}{}{Zentrale Verarbeitungseinheit}
{60701}{}{Dies ist das zentrale Bauteil der motorisierten T-51b-Rüstung. Ohne diesen Prozessor kann die Hälfte des Rüstungspotenzials, darunter die Kraftverstärkung, nicht genutzt werden.}
{60800}{}{SPS}
{60801}{}{Speicherprogrammierbare Steuerung. Funktioniert nicht.}
{60900}{}{SPS}
{60901}{}{Speicherprogrammierbare Steuerung. Betriebsbereit.}
{61000}{}{Persönlicher Safe}
{61001}{}{Dein persönlicher Safe mit Zahlenschloss zur Aufbewahrung von Gegenständen.}
{61100}{}{Persönlicher Safe}
{61101}{}{Dein persönlicher Safe mit Zahlenschloss zur Aufbewahrung von Gegenständen.}
{61200}{}{---}
{61201}{}{---}
{61300}{}{Kommode mit Spiegel}
{61301}{}{Luxusmöbel mit einem grossen, gesprungenen Spiegel.}
{61400}{}{Kommode mit Spiegel}
{61401}{}{Luxusmöbel mit einem grossen, gesprungenen Spiegel.}
{61500}{}{Tisch}
{61501}{}{Leicht mit Fettflecken verschmutzter Tisch.}
{61600}{}{Kommode mit Spiegel}
{61601}{}{Luxusmöbel mit einem grossen, gesprungenen Spiegel.}
{61700}{}{Dokumentenkisten}
{61701}{}{Aktenschrank für diverse Dokumente.}
{61800}{}{Kommode}
{61801}{}{Alte Kommode mit Türen.}
{61900}{}{Regal}
{61901}{}{Glasregal, das auseinanderfällt.}
{62000}{}{Regal}
{62001}{}{Glasregal, das auseinanderfällt.}
{62100}{}{Bücherregal}
{62101}{}{Ein Regal mit einigen Büchern.}
{62200}{}{Bücherregal}
{62201}{}{Ein Regal mit einigen Büchern.}
{62300}{}{Bücherregal}
{62301}{}{Ein Regal mit einigen Büchern.}
{62400}{}{Bücherregal}
{62401}{}{Ein Regal mit einigen Büchern.}
{62500}{}{Ingram Police}
{62501}{}{Amerikanische Maschinenpistole aus der Mitte des letzten Jahrhunderts. Die Polizeiversion zeichnet sich durch den Vordergriff, den teilweise gerippten Lauf und ein Korn ohne Kimme aus.\n Min. ST: 5.}
{62600}{}{Raketenwerfer}
{62601}{}{Rockwells Waffe für Geschosse im Kaliber 40 mm. Einfach zu handhaben, erfordert aber für einen effektiven Einsatz erhebliche Kraft.\n Min. ST: 5.}
{62700}{}{Granatwerfer 40 mm}
{62701}{}{Rockwell-Handgranatenwerfer, als Weiterentwicklung der alten Modelle des Springfield-Arsenals geschaffen. Für starke Soldaten ausgelegt.\n Min. ST: 6.}
{62800}{}{Granatwerfer 40 mm (erw. Magazin)}
{62801}{}{Rockwell-Handgranatenwerfer, als Weiterentwicklung der alten Modelle des Springfield-Arsenals geschaffen. Mit einem Trommelmagazin für 6 Granaten ausgestattet.\n Min. ST: 7.}
{62900}{}{Verstärkte Jacke}
{62901}{}{Eine robuste schwarze Lederjacke, verstärkt mit verschiedenen Panzerplatten.}
{63000}{}{Massgeschneiderte Jacke}
{63001}{}{Eine robuste schwarze Lederjacke, die ganz auf deinen Körper zugeschnitten ist. Diese Jacke ist viel bequemer.}
{63100}{}{Konzertanzug}
{63101}{}{In diesem Smoking bist du unwiderstehlich! Trag ihn, wenn du deinen Gesprächspartner beeindrucken willst.}
{63200}{}{Lederrüstung M3}
{63201}{}{Lederrüstung mit einer zusätzlichen Schutzschicht aus den Häuten von Säuregeckos. Die bekannten Eigenschaften dieser Häute machen die Rüstung widerstandsfähiger gegen Feuer-, Säure- und Plasmaschäden.}
{63300}{}{Metallrüstung I2 (verstärkt)}
{63301}{}{Rüstung, kunstvoll aus polierten Metallplatten gefertigt, mit zusätzlichem Schutz für Knie, Ellbogen und andere weniger geschützte Körperteile.}
{63400}{}{Metallrüstung I2 (reflektierend)}
{63401}{}{Rüstung, kunstvoll aus polierten Metallplatten mit Spiegelfläche gefertigt, die Licht oder ähnliche Angriffe reflektiert.}
{63500}{}{Metallrüstung I3}
{63501}{}{Rüstung, kunstvoll aus polierten Metallplatten gefertigt, mit zahlreichen Verstärkungen und einer Spiegelfläche.}
{63600}{}{Schlüssel des Rednecks}
{63601}{}{Standardschlüssel für eine der Türen in Provo.}
{63700}{}{Anzug eines jungen Atomwissenschaftlers}
{63701}{}{Miniatur-Kernkraftwerk. Ein wenig Uranerz ist daran befestigt.}
{63800}{}{Schlüssel zu Zimmer 26}
{63801}{}{Dies ist der Schlüssel zu einem der Zimmer im Hotel "Three Card Monte".}
{63900}{}{Schlüssel zu Zimmer 14}
{63901}{}{Dies ist der Schlüssel zu einem der Zimmer im Hotel "Three Card Monte".}
{64000}{}{Mysteriöser Blaster (funktionsuntüchtig.)}
{64001}{}{Ungewöhnliche Waffen unbekannter Herkunft. Auf dem Gehäuse steht: "Property of Area 51". Aus irgendeinem Grund funktioniert sie nicht.}
{64100}{}{Mysteriöser Blaster}
{64101}{}{Ungewöhnliche Waffen unbekannter Herkunft. Auf dem Gehäuse steht: "Property of Area 51".\n Min. ST: 3.}
{64200}{}{Schlüssel zum Versteck}
{64201}{}{Der übliche Schlüssel zu irgendeinem Schloss im Wind of War.}
{64300}{}{Hausschlüssel}
{64301}{}{Der übliche Schlüssel zu einem Mietshaus im Wind of War.}
{64400}{}{Schlüssel zum Pferch}
{64401}{}{Ein Satz alter Schlüssel vom Sklavenpferch in The Pound.}
{64500}{}{Muelleimer}
{64501}{}{Muelleimer. Die Aufschrift auf dem Aufkleber ist kaum zu erkennen: "Haltet die Strassen eurer Stadt sauber!"}
{64600}{}{Schlüssel zu Zimmer 7}
{64601}{}{Dies ist der Schlüssel zu einem der Zimmer im Hotel "Silver Legacy".}
{64700}{}{Funktionierendes Radio}
{64701}{}{Funktionierendes Radiomodell 2043B. Zuverlässig und robust.}
{64800}{}{Leiche eines Polizisten}
{64801}{}{Leiche eines Polizisten, durch einen präzisen Schuss in den Kopf getötet.}
{64900}{}{Bob Neils Schlüsselkarte}
{64901}{}{Die Schlüsselkarte für die Tür zu Bob Neils Privatbüro am Hoover Dam.}
{65000}{}{Fabrikschlüssel}
{65001}{}{Ein Bund verschiedener Schlüssel aus der Nuka-Cola-Fabrik in Salt Lake City.}
{65100}{}{Mutters Schlüssel}
{65101}{}{Der Schlüssel zur Umkleide im Nachtclub von New Reno.}
{65200}{}{Brief eines Slumbewohners}
{65201}{}{"Was geht, Bruder! Weisst du noch, ich hab dir von dem Trottel Ted erzählt, von dem wir das Haus gekauft haben? Er ist ganz nach hinten in Reno gezogen - zum Bahnhof, weg von den Leuten. Da dachte ich mir: Warum besuchen wir diesen Spinner nicht? Ich brauche Geld für die Miete und kann einfach keins auftreiben..."}
{65300}{}{---}
{65301}{}{---}
{65400}{}{Stange}
{65401}{}{Improvisierte Waffe aus der Stahlstange eines Abwassergitters.\n Min. ST: 1.}
{65500}{}{Nachricht an Patrick}
{65501}{}{Ein Brief der Mormonengemeinschaft an Patrick. Nichts Aussergewöhnliches.}
{65600}{}{Zigarettenetui}
{65601}{}{Etui aus Kupfer für Zigarren. Nichts Besonderes.}
{65700}{}{Jazz-Trompete}
{65701}{}{Ein schlicht aussehendes Musikinstrument aus Kupfer mit Alt-Sopran-Klanglage. Perfekt für eine Jazzband.}
{65800}{}{"Nuclear Rush"}
{65801}{}{Ein Strategiespiel für Kinder. Im Grunde geht es darum, Kredite aufzunehmen und die Nuklearbrennstoffvorkommen auf der Spielkarte zu erkunden. Am Ende gewinnt, wer den grössten Gewinn gemacht hat. Leider bleibt wie im Leben der Zweitplatzierte ein Verlierer.}
{65900}{}{Altes Medaillon}
{65901}{}{Jemand hat dieses Familienmedaillon verloren, und du hast es gefunden. Nun gehört es dir.}
{66000}{}{Vortis' Schlüssel}
{66001}{}{Schlüssel zum Safe in Slavertown.}
{66100}{}{Beschädigte Rüstung}
{66101}{}{überreste einer beschädigten Powerrüstung. Die Zerstörung ihres Energiemoduls führte zum Aufreissen der Panzerhülle und zur teilweisen Zerstörung der Tragstruktur. Jetzt kann man sie nicht einmal mehr anziehen.}
{66200}{}{Baupläne T-51. Teil 1}
{66201}{}{Diese Baupläne beschreiben nur die Tragstruktur der T-51b-Powerrüstung. Seltene Informationen.}
{66300}{}{Baupläne T-51. Teil 2}
{66301}{}{Diese Baupläne beschreiben nur die internen Automatikmodule der T-51b-Powerrüstung. Seltene Informationen.}
{66400}{}{"Bloatfly"}
{66401}{}{Eine zivile Plasma-Selbstverteidigungspistole. Betrieben mit einer nicht wiederaufladbaren Batterie, die nur 4 Schuss lang hält.\n Min. ST: 1.}
{66500}{}{Deine Ausrüstung}
{66501}{}{Hier werden deine persönlichen Gegenstände aufbewahrt.}
{66600}{}{Fein skalpell}
{66601}{}{Sehr scharfes medizinisches Instrument zum Durchtrennen von Gewebe. Um es zu handhaben, braucht man viel chirurgische Erfahrung, sonst kann dieser Gegenstand für den Besitzer gefährlich sein.}
{66700}{}{Fein skalpell}
{66701}{}{Sehr scharfes medizinisches Instrument zum Durchtrennen von Gewebe. Um es zu handhaben, braucht man viel chirurgische Erfahrung, sonst kann dieser Gegenstand für den Besitzer gefährlich sein.}
{66800}{}{Taktisches überlebensmesser}
{66801}{}{Entwickelt für Arbeiten beim Aufbau eines Lagers in der Wildnis und um das überleben des Menschen in der "freien" Natur sicherzustellen.}
{66900}{}{"Lucky"}
{66901}{}{Stark abgenutzte defensive Plasma-Pistole, ziviles Modell der ersten Generation. Solche Waffen kamen lange vor dem Krieg aus der Mode.}
{67000}{}{"Lucky"}
{67001}{}{Stark abgenutzte Defensiv-Plasmapistole, ziviles Modell der ersten Generation. Nach Reinigung und Neukalibrierung stiegen Leistung und Reichweite um 10%.}
{67100}{}{Nachtschattenbeeren}
{67101}{}{Unreife Beeren einer wild wachsenden Pflanze. Süss-bitterer Geschmack, sehr giftig.}
{67200}{}{Karawanenmahlzeit}
{67201}{}{Eine nahrhafte Mahlzeit, die sich unterwegs schnell und einfach zubereiten lässt.}
{67300}{}{"Blutreiniger"}
{67301}{}{Traditionelle Medizin auf Basis von Heilkräutern. Kann Giftstoffe und Radionuklide aus dem Körper entfernen und sogar einige Arten von Infektionskrankheiten heilen.}
{67400}{}{Konzertplakate}
{67401}{}{Das sind handgeschriebene Plakate für dein Konzert, in Schwarz-Weiss gehalten. Sie könnten in gute Hände gelangen und in Reno verbreitet werden.}
{67500}{}{Nusslösung}
{67501}{}{Ein beliebtes RadAway-äquivalent zur intravenösen Anwendung. Bis zur vollen Wirkung dauert es eine Weile.}
{67600}{}{Hülse}
{67601}{}{Abgeschossene Hülse einer Patrone im Kaliber .223.}
{67700}{}{Katana}
{67701}{}{Schwert aus einem Geschenkset der Firma "Hattori Souvenirs". Obwohl die Waffe qualitativ deutlich hinter ihrem japanischen Vorbild zurückbleibt, kann sie in einer starken Hand den Gegner dauerhaft vom Schlachtfeld entfernen, selbst wenn er eine Rüstung trägt.\n Min. ST: 4.}
{67800}{}{Machete}
{67801}{}{Jemand hat das Messer eines Rasenmähers bearbeitet, eine Schneide geschärft und den Griff fest mit Brahminhaut umwickelt.\n Min. ST: 5.}
{67900}{}{Baupläne für "Mickeys Rache"}
{67901}{}{Anleitung zum Bau selbstgemachter Nahkampfwaffen. Der Entwickler ist ein gewisser Mickey. An wem er sich rächen wollte, ist unbekannt. Bekannt ist nur, dass man für den Bau dieser Waffen einen Toaster und einige andere Teile braucht.}
{68000}{}{Roboterüberreste}
{68001}{}{Ein Wachroboter, bedeckt mit Strassenstaub. Genauer gesagt: das, was von ihm übrig ist.}
{68100}{}{Wrights Vertrag}
{68101}{}{Ein Vertrag zwischen Mark und Wright, in dem der Auftragnehmer gezwungen ist, dem Kunden mehrere Kisten Sprengstoff zu bringen. Offen gesagt, harte Bedingungen.}
{68200}{}{Autoscheinwerfer}
{68201}{}{Scheinwerfer für ein Auto mit einseitigen Halogenlampen zu 65 Watt.}
{68300}{}{Autoscheinwerfer}
{68301}{}{Scheinwerfer für ein Auto mit einseitigen Halogenlampen zu 65 Watt.}
{68400}{}{Autoverdeck}
{68401}{}{Dies ist ein kleines Auto-Verdeck, das zur Verstärkung der Ladefläche dient. Genau richtig für einen Pickup.}
{68500}{}{Autoverdeck}
{68501}{}{Dies ist ein kleines Auto-Verdeck, das zur Verstärkung der Ladefläche dient. Genau richtig für einen Pickup.}
{68600}{}{Kraftstoffregler}
{68601}{}{Manche Fahrer bauten diesen Regler ein, der den Kraftstoffverbrauch halbiert, doch den meisten war es egal, wie viel ihre Autos schluckten. Schliesslich ist Kraftstoff billig und reichlich vorhanden. Wozu also Sorgen machen?}
{68700}{}{"Wilder" mit Patronengurt}
{68701}{}{Einzellader-Schrotflinte mit gekürztem Lauf und Patronengurt am Kolben. Obwohl diese Waffe bereits stark abgenutzt und veraltet ist, hat sie einen unbestreitbaren Vorteil - schnelles Nachladen.\n Min. ST: 4.}
{68800}{}{Beschädigter Roboter}
{68801}{}{Dieser Roboter ist beschädigt und kann nicht repariert werden.}
{68900}{}{Elis Schlüssel Nr. 10}
{68901}{}{Standardschlüssel für ein Türschloss.}
{69000}{}{Sklavenhalsband}
{69001}{}{Ein Vorkriegs-Taser in Form eines Halsbands. Früher wurde er in Gefängnissen eingesetzt, heute ist er ein grossartiges Werkzeug für den Sklavenhandel und die Ausbeutung.}
{69100}{}{Alter Revolver}
{69101}{}{Ein sehr altes Modell eines einst beliebten Revolvers. Vielleicht ein Museumsstück.\n Min. ST: 3.}
{69200}{}{Trainingsgewehr}
{69201}{}{Sportmodell eines Lasergewehrs, für Training und Präzisionswettkämpfe entwickelt. Es hat im Vergleich zu einem normalen Lasergewehr geringere Werte und eine etwas kürzere Reichweite.\n Min. ST: 5.}
{69300}{}{Kiste}
{69301}{}{Alte Holzkiste.}
{69400}{}{Kiste}
{69401}{}{Alte Holzkiste.}
{69500}{}{Baupläne: "Molotowcocktail"}
{69501}{}{Anleitung zur Herstellung von Brandgranaten unter "häuslichen" Bedingungen.}
{69600}{}{Teile}
{69601}{}{Verschiedene Teile von Robotern, Computern und Haushaltsgeräten.}
{69700}{}{Getränkekühlschrank}
{69800}{}{Getränkekühlschrank}
{69900}{}{Zerrissene Seite}
{69901}{}{Seite aus dem Kassenbuch des Casinos "Monte". Darauf sind Murphys Gewinne und Irwins Schulden vom selben Tag vermerkt.}
{70000}{}{Baupläne: "Pulvergranate"}
{70001}{}{Anleitung zum Bau einer selbstgemachten Granate mit Schiesspulver und chemischem Zünder. Bei der Herstellung werden nur leicht erhältliche Materialien verwendet.}
{70100}{}{---}
{70200}{}{---}
{70300}{}{---}
{70400}{}{---}
{70500}{}{Mrs. Mordinos Finger}
{70501}{}{Dieser kleine Finger gehörte Mr. Mordinos Frau.}
{70600}{}{Schockfaust}
{70601}{}{Der Vorläufer der polizeilichen Kraftfaust der Firma "Punch". Wird zusammen mit einem Gummihandschuh benutzt.}
{70700}{}{Ultraschallscanner}
{70701}{}{Inaktiver Scanner für ein Echolot mit Metalldetektor. Er analysiert Ultraschallwellen und gibt verarbeitete Informationen über die Umgebung auf einer runden Digitalanzeige aus.}
{70800}{}{Innereien mit Gewürzen}
{70801}{}{Brahmin-Innereien, nach einem Spezialrezept zubereitet. Neben offensichtlichem Brahmin-Gewebe kann buchstäblich alles darin sein.}
{70900}{}{Ionensynthesizer}
{70901}{}{Eine Art Vorkriegsgerät der Vault-Tec-Firma.}
{71000}{}{Gasanalysegerät}
{71001}{}{Eine Art Vorkriegsgerät der Vault-Tec-Firma.}
{71100}{}{Impulsmodulator}
{71101}{}{Eine Art Vorkriegsgerät der Vault-Tec-Firma.}
{71200}{}{Druckregler}
{71201}{}{Eine Art Vorkriegsgerät der Vault-Tec-Firma.}
{71300}{}{Chip für Kleidungssynthesizer}
{71301}{}{Eine Art Vorkriegsgerät der Vault-Tec-Firma.}
{71400}{}{Schlüssel für "Eldorado"}
{71401}{}{Ein Haufen Schlüssel zu verschiedenen Türen im Casino "Eldorado".}
{71500}{}{Bertolinis Qüü}
{71501}{}{Zusammenklappbarer Qüü mit königlichem Muster in einem bequemen Lederetui. Am Mittelgelenk brutal zerbrochen.}
{71600}{}{Bertolinis Qüü}
{71601}{}{Zusammenklappbarer Qüü mit königlichem Muster in einem bequemen Lederetui. Ein Metallrahmen am beschädigten Teil ermöglicht es, den Qüü wie zuvor bestimmungsgemäss zu benutzen.}
{71700}{}{Bertolinis Qüü}
{71701}{}{Zusammenklappbarer Qüü mit königlichem Muster in einem bequemen Lederetui mit einem "überraschenden" doppelten Boden. Ein Metallrahmen am beschädigten Teil ermöglicht es, den Qüü wie zuvor bestimmungsgemäss zu benutzen.}
{71800}{}{Leichen-Amphetamin}
{71801}{}{Die Dosis einer hyperbolisierenden Substanz, synthetisiert aus dem Plasma stark verstrahlten Blutes, Endorphinen und verschiedenen Enzymen des humanoiden Organismus.}
{71900}{}{Bier mit Geschmack}
{71901}{}{Eine Art selbstgebrautes Bier. Unterscheidet sich durch einen seltsamen, beissenden Geschmack.}
{72000}{}{Kaputte Laserpistole}
{72001}{}{Laserpistole Wattz 1000, Zivilmodell. Aus irgendeinem Grund funktioniert sie nicht.}
{72100}{}{Chemikalien}
{72101}{}{Ein Satz Chemikalien für vielfältige Anwendungen. Dem Etikett auf Ampullen und Schachteln nach stammt die Packung vom Militär.}
{72200}{}{Beschädigte Mikrofusionsbatterie}
{72201}{}{Diese Mikrofusionsbatterie ist beschädigt und kann daher momentan nicht benutzt werden.}
{72300}{}{Kondome (Gift.)}
{72301}{}{Das sind Kondome der Marke "Jimmy Hats". Eine sehr zuverlässige Marke, aber irgendwie wurde ein kleines Loch an der Hülse entdeckt ... vielleicht von einer Nadel.}
{72400}{}{Thompsons Depression}
{72401}{}{Das ist eine Art Einheit zur Messung von Thompsons Depression. Der arme Kerl hat vom Tod seiner besten Hündin erfahren ...}
{72500}{}{Ein Pip-Boy-Empathieverstärker}
{72501}{}{Dieser Verstärker besteht aus akustischen und optischen Sensoren, einer Programmdiskette und einem Kabel. Er dient dazu, Mimik und Stimme von Gesprächspartnern zu analysieren, um ihren emotionalen Zustand zu bestimmen.}
{72600}{}{Defekter Pip-Boy}
{72601}{}{überreste eines zerstörten tragbaren Computers Pip-Boy 2000. Der Monitor ist kaputt, das Gehäuse zerbeult und einige Knöpfe sind herausgefallen. Dieser Gegenstand lässt sich offensichtlich nicht reparieren.}
{72700}{}{Reifenrüstung}
{72701}{}{Eine ziemlich unbequeme und widerlich stinkende Gummirüstung. Aber spielt das eine Rolle, wenn es um Stromschläge oder Strahlung geht?}
{72800}{}{Elektrospeer}
{72801}{}{Ein wirksames Polizeimittel, um eine Meute von Rebellen auseinanderzutreiben. Vor dem Krieg oft eingesetzt.\n Min. ST: 4.}
{72900}{}{10-mm-Pistole #80}
{72901}{}{Veraltetes Modell der Selbstladepistole Colt 6520 im Kaliber 10 mm. Den Markierungen am Gehäuse nach wurde sie 2051 hergestellt.\n Min. ST: 3.}
{73000}{}{10-mm-Pistole mit Taschenlampe}
{73001}{}{Polizeimodell der Selbstladepistole Colt 6520 im Kaliber 10 mm, ausgestattet mit einer taktischen Lauf-Taschenlampe. Allerdings funktioniert sie manchmal nicht - man muss sie schütteln.\n Min. ST: 4.}
{73100}{}{Verschlossener Koffer}
{73101}{}{Robuster Metallkoffer eines Geschäftsmannes. Vermutlich ist etwas Wertvolles darin, denn er ist mit einem Zahlenschloss gesichert.}
{73200}{}{Anatomischer Pip-Boy-Analysator}
{73201}{}{Dieses Gerät besteht aus einer Programmdiskette, einem Kabel und einem Sensor. Es dient dazu, die Anatomie eines Gegners zu analysieren und seine verwundbarsten Stellen zu bestimmen.}
{73300}{}{Chrombrille}
{73301}{}{Brille mit verchromten Gläsern.}
{73400}{}{Panzerplatten}
{73401}{}{Schutzplatten aus Polymer, offenbar aus den überresten zerstörter Kampfrüstungen gefertigt.}
{73500}{}{Körperrüstung I2}
{73501}{}{Eine leichte kugelsichere Armee-Weste mit Vorrichtungen zum schnellen Verstauen allerlei Krempels. Sie schützt nur einen Teil des Oberkörpers, da sie für Mitglieder der Notfall-Einsatzteams gedacht war. Einige Panzerplatten wurden durch robustere ersetzt.}
{73600}{}{Winchester-Pistole}
{73601}{}{Diese Waffe ist nach dem Vorbild eines Plasmagewehrs der Firma "Winchester Arms" gefertigt. Wegen der Konkurrenz durch Plasmapistolen der Gaston Glock AI wurde sie nie populär.\n Min. ST: 5.}
{73700}{}{Prämierte Pistole}
{73701}{}{Standardpistole Colt 6520 aus legiertem Stahl. Die Verwendung widerstandsfähigerer, gehärteter Legierungen verleiht dieser Waffe grössere Tötungswirkung, macht sie aber auch etwas schwerer.\n Min. ST: 4.}
{73800}{}{Schwerer Kojotenspeer}
{73801}{}{Schwerer Speer der Kojotenjäger. Als Schneide dient offenbar eine massive, geschärfte Klinge von einer landwirtschaftlichen Maschine.\n Min. ST: 5.}
{73900}{}{Kampfmesser der Kojoten}
{73901}{}{Klingenwaffe der Kojotenjäger. Offenbar aus einer begradigten Grubberschar gefertigt.\n Min. ST: 4.}
{74000}{}{Kojotenknüppel}
{74001}{}{Schwere Stahlwaffe der Kojotenjäger. Offenbar aus einer Grouser-Kette und einem Metallrohr zusammengesetzt und verschraubt.\n Min. ST: 5.}
{74100}{}{Ultrathermische Mischung}
{74101}{}{Eine Termitenmischung, ergänzt durch unbekannte Bestandteile. Beim Verbrennen entwickelt sie eine enorme Hitze und schmilzt dadurch lautlos und rauchlos alles in ihrer Umgebung. Vergiss das Feuerzeug nicht!}
{74200}{}{Nelsons beschädigte Waffe}
{74201}{}{Diese Pumpgun wurde schwer beschädigt. Es wird viel Arbeit kosten, sie wieder funktionstüchtig zu machen.}
{74300}{}{Kotelett aus dem Fleisch eines "Erdwurms"}
{74301}{}{Gefuelltes Fleisch von "Erdwürmern" mit Grünzeug, in eine Tortilla gewickelt. Dieses Gericht enthält mehr Protein als ein Brahminsteak.}
{74400}{}{Verkehrsschild}
{74401}{}{Die Warnung für Fahrer ist auf diesem verrosteten Schild noch gerade so zu erkennen. Sie hat nichts mit dir zu tun.}
{74500}{}{Zerrissene Lederjacke}
{74501}{}{Lederjacke in schrecklichem Zustand. Sie hat viele Löcher, einen abgeschnittenen Arm und auf dem Rücken Krallenspuren kleiner Tiere. Mit genügend Mühe lässt sie sich aber noch reparieren.}
{74600}{}{Schlüssel zum Notausgang}
{74601}{}{Standardschlüssel für die Notausgangstür in Strykers Hauptquartier.}
{74700}{}{Hangarschlüssel}
{74701}{}{Standardschlüssel für das Hangartor auf der Ranch von Oliver Luciano.}
{74800}{}{Baupläne: "Kubotan"}
{74801}{}{Vorkriegs-Baupläne für Polizisten zum Zusammenbau eines Kubotans, mit einer Beschreibung seiner Anwendung. Diese Selbstverteidigungswaffe ist nicht schwer herzustellen, aber ohne die richtigen Fähigkeiten nutzlos.}
{74900}{}{Elis Schlüssel Nr. 9}
{74901}{}{Standardschlüssel für ein Türschloss.}
{75000}{}{Beherrschung des Kubotans}
{75001}{}{Wenn du lernst, den Kubotan im Kampf einzusetzen, kannst du dem Gegner mehr Schaden zufügen.}
{75100}{}{überreste von Sergeant Kong}
{75101}{}{Die vertrockneten überreste eines Mannes in einer Armeeweste, der einen Cowboyhut in der Hand hält. Den überresten nach zu urteilen, war dies einst Sergeant Kong.}
{75200}{}{Rucksack-Flammenwerfer}
{75201}{}{Flammenwerfer Modell Flare-450 mit grossem Rückentragegestell. Verspritzt einen kurzen Strahl brennbarer Mischung. Benötigt Spezialtreibstoff.\n Min. ST: 6.}
{75300}{}{Pokerchip "El Capitan"}
{75400}{}{Pokerchip "Eldorado"}
{75500}{}{Pokerchip "Silver Legacy"}
{75600}{}{Pokerchip "Monte"}
{75700}{}{Goldener Pokerchip}
{75701}{}{Beim Anblick dieses Prachtexemplars bist du fest davon überzeugt, dass du beim Poker oder Roulette nie wieder verlieren wirst!}
{75800}{}{"Atomcocktail"}
{75801}{}{Ein starkes alkoholisches Getränk, das laut Vorkriegsbeschreibung eindeutig mit etwas Besonderem verdünnt wurde.}
{75900}{}{Rezept: "Atomcocktail"}
{75901}{}{Das Rezept zur Zubereitung des "Atomcocktails". Die Vorkriegsqualität wirst du wohl kaum erreichen, aber schlecht wird er trotzdem nicht.}
{76000}{}{Abgenutztes Minigun}
{76001}{}{Minigun CZ53 Rockwell in sehr schlechtem Zustand.\n Min. ST: 7.}
{76100}{}{Kompromittierende Beweise gegen Mordino}
{76101}{}{Dies ist eine Aufzeichnung der Diskussion bei Strykers Treffen, bei der beschlossen wurde, Mr. Mordino zu beseitigen, sobald Strykers Gruppe in Reno die Macht ergriffen hat. Mordino wird das sicher gerne hören.}
{76200}{}{"Gonzo-Stil"}
{76201}{}{Mit diesem hochwertigen Kampfmesser kannst du jede Vortäuschung und Lüge leicht aufdecken, wenn du die nötigen Fähigkeiten hast.\n Min. ST: 1.}
{76300}{}{Bikermesser}
{76301}{}{Das Messer, das in der Tasche deiner Jacke gefunden wurde. Auf Knopfdruck am Griff schnellt die Klinge durch eine Feder heraus.\n Min. ST: 1.}
{76400}{}{Hormonexplosion}
{76500}{}{Extraktionsfenster}
{76600}{}{Rezept: "Root Beer"}
{76601}{}{Das Rezept zur Herstellung von Root Beer.}
{76700}{}{EMP-Handschuh}
{76701}{}{Kraftschlagring mit einem Generator für elektromagnetische Impulse.\n Min. ST: 2.}
{76800}{}{"Feuriger Kuss"}
{76801}{}{Hydraulische Faust aus einem feuerfesten Handschuh, einer Gasflasche und einem Sprüher mit Kolbenmechanismus. Beim Aufprall sprüht der Mechanismus Treibstoff auf den Körper des Opfers und entzündet ihn anschliessend.\n Min. ST: 2.}
{76900}{}{Leiche eines Prospektors}
{76901}{}{Alles deutet darauf hin, dass dieser Mann nicht von den einheimischen Nagetieren getötet wurde.}
{77000}{}{Panzer eines legendären Skorpions}
{77001}{}{Sehr starker Chitinpanzer.}
{77100}{}{Chitinrüstung}
{77101}{}{Deine persönliche Rüstung, gefertigt aus dem Panzer eines legendären Skorpions.}
{77200}{}{überreste des Arbeiters}
{77201}{}{Diese überreste liegen hier schon seit vielen Jahren. Keine Spuren eines gewaltsamen Todes.}
{77300}{}{überreste eines Prospektors}
{77301}{}{Das ist alles, was vom Prospektor übrig ist. Er wollte sich an den Schätzen der Gegend laben. Am Ende hat sich jedoch jemand an ihm gegönnt.}
{77400}{}{Waschbecken}
{77401}{}{Porzellanwaschbecken, das seine Aufgabe kaum erfuellt.}
{77500}{}{Waschbecken}
{77501}{}{Porzellanwaschbecken, das seine Aufgabe kaum erfuellt.}
{77600}{}{Proben}
{77601}{}{Steriles Set zum Sammeln von Blutproben mutierter Tiere. Ausgegeben von Dr. Willmouth.}
{77700}{}{Leiche}
{77701}{}{Offenbar wird diese Leiche weiter in der Sonne liegen, wenn sie nicht jemand nach den hiesigen Bräuchen begräbt.}
{77800}{}{Leiche eines Karawanenhändlers}
{77900}{}{Gauss-Pistole PPK5}
{77901}{}{Frühes Pistolenmodell, das auf dem Prinzip der elektromagnetischen Beschleunigung basiert. Kurz nach seiner Markteinführung wurden fortschrittlichere Modelle entwickelt, weshalb die PPK5 schnell ausser Gebrauch kam.\n Min. ST: 4.}
{78000}{}{Rezept: "Stimpak"}
{78001}{}{Rezept zur Herstellung eines Stimpaks und eines Super-Stimpaks.}
{78100}{}{Rezept: "Arztkoffer"}
{78101}{}{Anleitung zum Zusammenstellen eines Arztkoffers unter den Bedingungen des modernen ödlands.}
{78200}{}{Halb aufgegessene Leiche}
{78201}{}{überreste eines Mannes in einem Vault-Anzug. Kannibalen haben die Hälfte des Körpers gefressen.}
{78300}{}{Blutanalysator}
{78301}{}{Dieses Gerät untersucht deine Blutprobe und zeigt den Grad einer Infektion oder Vergiftung an.}
{78400}{}{Thompsons Plasmagewehr}
{78401}{}{Prototyp einer Impulswaffe von Thompson & Glock. Als Sturmwaffe für reguläre Armeeeinheiten entwickelt, schaffte sie es jedoch nicht rechtzeitig in die Massenproduktion. Fabrikstempel: "Lucky Tom 2029".\n Min. ST: 6}
{78500}{}{Die Liste von Nisckiguan}
{78501}{}{Eine flüchtig hingekritzelte Liste der Dinge, die für den Eingriff benötigt werden: 1) reines Wasser; 2) Rauschkraut, Alkohol oder Schmerzmittel; 3) ein scharfes Messer; 4) eine Zange oder Kneifzange; 5) ein Erste-Hilfe-Kasten mit Verbandszeug; 6) Heilpulver oder Stimpaks.}
