{100}{}{Brennendes Metallfass}
{101}{}{Das Fass enthält brennendes Papier und anderen lodernden Abfall.}
{200}{}{Holztür}
{201}{}{Eine Tür aus Holz.}
{300}{}{Holztisch}
{301}{}{Ein Tisch aus Holz.}
{400}{}{Holztisch}
{401}{}{Ein Tisch aus Holz.}
{500}{}{Metallfass}
{501}{}{Ein altes Fass aus Stahl.}
{600}{}{Metallfass}
{601}{}{Ein altes Fass aus Stahl.}
{700}{}{Reifenstapel}
{701}{}{Ein Stapel uralter Gummireifen. Sie sind vulkanisiert und verhärtet, vermutlich durch die Hitze.}
{800}{}{Sicherheitstür}
{801}{}{Diese Tür sieht sehr sicher aus. Sie schützt vor den Elementen der Außenwelt und gefährlichen Kreaturen.}
{900}{}{Computer}
{901}{}{Ein Computerterminal, das mit einem Großrechner verbunden ist.}
{1000}{}{Säule}
{1001}{}{Eine Stützsäule, die das gesamte Gebäude entlastet.}
{1100}{}{Computer}
{1101}{}{Ein Computerterminal, das mit einem Großrechner verbunden ist.}
{1200}{}{Computer}
{1201}{}{Ein Computerterminal, das mit einem Großrechner verbunden ist.}
{1300}{}{Monitor}
{1301}{}{Ein Grünbildschirm-Monitor, auf dem verschiedene Daten angezeigt werden. Gelegentlich tauchen ein paar Bytes auf.}
{1400}{}{Monitor}
{1401}{}{Ein Grünbildschirm-Monitor, auf dem verschiedene Daten angezeigt werden.}
{1500}{}{Autodoc}
{1501}{}{Dieser Autodoc ist dafür ausgelegt, Krankheiten zu heilen und verschiedene Medikamente zu verabreichen.}
{1600}{}{Bildschirme}
{1601}{}{Eine Reihe aus drei Anzeigemonitoren, auf denen verschiedene Daten angezeigt werden.}
{1700}{}{Bildschirme}
{1701}{}{Eine Reihe aus drei Anzeigemonitoren, auf denen verschiedene Daten aus dem Vault angezeigt werden.}
{1800}{}{Tür}
{1801}{}{Bei näherer Betrachtung ist es immer noch eine Tür.}
{1900}{}{Tür}
{1901}{}{Bei näherer Betrachtung ist es immer noch eine Tür.}
{2000}{}{Lüftungsschacht}
{2001}{}{Ein Lüftungsschacht, der den gesamten Komplex mit aufbereiteter und gereinigter Luft versorgt.}
{2100}{}{Lüftungsschacht}
{2101}{}{Ein Lüftungsschacht, der den gesamten Komplex mit aufbereiteter und gereinigter Luft versorgt.}
{2200}{}{Tür}
{2201}{}{Große, stabile Haupteingangstür.}
{2300}{}{Die Schranktür}
{2400}{}{Sockel}
{2401}{}{Ein hydraulischer Lift, der die Plattform mit Versorgungs-, Strom- und Kommunikationsleitungen verbindet.}
{2500}{}{Monitor}
{2501}{}{Wenn du einen Monitor gesehen hast, hast du sie alle gesehen.}
{2600}{}{Monitor}
{2601}{}{Ein Computermonitor, auf dem verschiedene Daten angezeigt werden.}
{2700}{}{Gitterrost}
{2701}{}{Ein Bodenrost.}
{2800}{}{Rohre}
{2801}{}{Ein paar Rohre. Bei näherer Betrachtung stellt sich heraus, dass es immer noch Rohre sind.}
{2900}{}{Lüftungsschacht}
{2901}{}{Standardlüftungssystem von Vault-Tec.}
{3000}{}{Säule}
{3001}{}{Standard-Säulenstützsystem von Vault-Tec.}
{3100}{}{Säule}
{3101}{}{Standard-Säulenstützsystem von Vault-Tec.}
{3200}{}{Lüftungsschacht}
{3201}{}{Standardlüftungssystem von Vault-Tec.}
{3300}{}{Lüftungsschacht}
{3301}{}{Standardlüftungssystem von Vault-Tec.}
{3400}{}{Bett}
{3401}{}{Ein Bett. Es sieht ziemlich bequem aus, wenn man bedenkt, worauf du bisher geschlafen hast.}
{3500}{}{Bett}
{3501}{}{Ein Standardbett. Sieht bequem aus.}
{3600}{}{Bett}
{3601}{}{Ein Standardbett. Sieht bequem aus.}
{3700}{}{Bett}
{3701}{}{Ein Standardbett. Sieht bequem aus.}
{3800}{}{Aufzug}
{3801}{}{Das ist ein Wartungsaufzug.}
{3900}{}{Stuhl}
{3901}{}{Ein Stuhl. Schade, dass du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{4000}{}{Stuhl}
{4001}{}{Ein Stuhl. Schade, dass du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{4100}{}{Stuhl}
{4101}{}{Ein Stuhl. Schade, dass du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{4200}{}{Stuhl}
{4201}{}{Ein Stuhl. Schade, dass du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{4300}{}{Monitor}
{4301}{}{Ein Computermonitor, auf dem verschiedene Daten angezeigt werden.}
{4400}{}{Monitor}
{4401}{}{Ein Computermonitor, auf dem verschiedene Daten angezeigt werden.}
{4500}{}{Monitor}
{4501}{}{Ein Computermonitor, auf dem verschiedene Daten angezeigt werden.}
{4600}{}{Monitor}
{4601}{}{Ein Computermonitor, auf dem verschiedene Daten angezeigt werden.}
{4700}{}{Monitor}
{4701}{}{Ein Computermonitor, auf dem verschiedene Daten angezeigt werden.}
{4800}{}{Monitor}
{4801}{}{Ein Computermonitor, auf dem verschiedene Daten angezeigt werden.}
{4900}{}{Kartenmarkierung für das Ausgangsraster}
{4901}{}{Kartenmarkierung für das Ausgangsraster}
{5000}{}{Luftaufbereitungsanlage}
{5001}{}{Eine Luftaufbereitungsanlage reinigt die verbrauchte Luft und versorgt den Komplex mit Frischluft. Diese hier ist kaputt.}
{5100}{}{Stuhl}
{5101}{}{Ein Stuhl. Schade, dass du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{5200}{}{Stuhl}
{5201}{}{Ein Stuhl. Schade, dass du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{5300}{}{Stuhl}
{5301}{}{Ein Stuhl. Schade, dass du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{5400}{}{Stuhl}
{5401}{}{Ein Stuhl. Schade, dass du keine Zeit hast, dich hinzusetzen und auszuruhen.}
{5500}{}{Bildschirmeinheit}
{5501}{}{Diese Bildschirmeinheit umfasst verschiedene Computermonitore und andere Bildschirme. Sieht sehr, sehr geschäftig aus.}
{5600}{}{Bildschirmeinheit}
{5601}{}{Diese Bildschirmeinheit umfasst verschiedene Computermonitore und andere Bildschirme. Sieht sehr, sehr geschäftig aus.}
{5700}{}{Stuhl}
{5701}{}{Ein Stuhl. Sieht ziemlich bequem aus.}
{5800}{}{Stuhl}
{5801}{}{Ein Stuhl. Sieht ziemlich bequem aus.}
{5900}{}{Stuhl}
{5901}{}{Ein Stuhl. Sieht ziemlich bequem aus.}
{6000}{}{Stuhl}
{6001}{}{Ein Stuhl. Sieht ziemlich bequem aus.}
{6100}{}{Tisch}
{6101}{}{Das ist ein Tisch. Vor Tischen mussten die Leute ihre Sachen auf dem Boden aufbewahren.}
{6200}{}{Tisch}
{6201}{}{Das ist definitiv ein Tisch.}
{6300}{}{Steppenläufer}
{6301}{}{Das ist ein Steppenläufer. Natürlich hast du noch nie einen echten lebenden Steppenläufer gesehen. Du solltest ihn besser gut im Auge behalten.}
{6400}{}{Kaktus}
{6401}{}{An diesem Kaktus fällt dir nichts Besonderes auf.}
{6500}{}{Ferokaktus}
{6501}{}{An diesem Kaktus fällt dir nichts Wichtiges auf.}
{6600}{}{Baum}
{6601}{}{Ein toter Baum. Hier wächst nichts besonders gut.}
{6700}{}{Geheimes blockierendes Hexfeld}
{6701}{}{Wenn du das sehen kannst, gib dem technischen Designer die Schuld.}
{6800}{}{Nebel}
{6900}{}{Stalagmit}
{6901}{}{Eine natürliche Verlängerung des Felsbodens.}
{7000}{}{Stalagmit}
{7001}{}{Eine natürliche Verlängerung des Felsbodens.}
{7100}{}{Blutfleck}
{7101}{}{An diesem blutigen Fleck ist nichts Ungewöhnliches. Außer natürlich, dass hier jemand oder etwas gestorben ist.}
{7200}{}{Felssäule}
{7201}{}{Diese dicke Felssäule reicht vom Boden bis zur Decke.}
{7300}{}{Felssäule}
{7301}{}{Diese dünne Felssäule reicht vom Boden bis zur Decke.}
{7400}{}{Felsen}
{7401}{}{Du beobachtest die Felsen eine Weile, aber sie bewegen sich nie.}
{7500}{}{Felsen}
{7501}{}{Du behältst diese Felsen gut im Auge, falls sie dich angreifen wollen.}
{7600}{}{Bretter}
{7601}{}{Ein ordentlich gestapelter Haufen Bretter.}
{7700}{}{Tor}
{7701}{}{Ein Holztor.}
{7800}{}{Felsen}
{7801}{}{Ein großer Haufen Felsen. Sie scheinen aus dieser Gegend zu stammen.}
{7900}{}{Felsen}
{7901}{}{Ein kleiner Haufen Felsen.}
{8000}{}{Felsen}
{8001}{}{Ein kleiner Haufen Felsen.}
{8100}{}{Felsen}
{8101}{}{Ein großer Haufen Felsen.}
{8200}{}{Knochen}
{8201}{}{Ein großer Haufen gebleichter Tierknochen. Zumindest glaubst du, dass alle Knochen von Tieren stammen ...}
{8300}{}{Knochen}
{8301}{}{Ein großer Haufen gebleichter Tierknochen. Zumindest glaubst du, dass alle Knochen von Tieren stammen ...}
{8400}{}{Knochen}
{8401}{}{Ein riesiger Haufen gebleichter Knochen. Du kannst nicht erkennen, zu welcher Art die toten Viecher gehörten.}
{8500}{}{Knochen}
{8501}{}{Du denkst, das könnten Knochen eines Gehörnten Kängurus sein, aber sicher bist du dir nicht. Sie sind zu stark verwittert, um eine endgültige Bestimmung zu treffen.}
{8600}{}{Knochen}
{8601}{}{Du siehst die Knochen eines großen, zweiköpfigen Tieres.}
{8700}{}{Tor}
{8701}{}{Ein Holztor. Es öffnet sich und schließt sich, öffnet sich und schließt sich und …}
{8800}{}{Tor}
{8801}{}{Ein Holztor.}
{8900}{}{Tor}
{8901}{}{Ein Holztor.}
{9000}{}{Felsen}
{9001}{}{Ein sehr großer Haufen Steine. Es sieht gefährlich aus, wenn er einfach so daliegt.}
{9100}{}{Felsen}
{9101}{}{Ein großer Haufen Steine. Wenn du genau hinsiehst, kannst du in den Steinseiten die Gesichter kleiner alter Männer erkennen.}
{9200}{}{Felsen}
{9201}{}{Steine, Steine, Steine! Überall, wohin du blickst, sind Steine!}
{9300}{}{Felsen}
{9301}{}{Ein kleiner Haufen Felsen.}
{9400}{}{Bar}
{9401}{}{In dieser Bar stehen verschiedene gebraute Getränke zum Ausschenken bereit.}
{9500}{}{Stuhl}
{9501}{}{Ein verrotteter alter Stuhl, der aus einem uralten Autositz gemacht wurde.}
{9600}{}{Stuhl}
{9601}{}{Ein stinkender alter Stuhl, der einmal ein Autositz war. Die Federn federn nicht mehr.}
{9700}{}{Stuhl}
{9701}{}{Ein verrotteter, stinkender alter Stuhl, der zur Stütze auf Ziegelsteinen steht. Sieht ziemlich unbequem aus.}
{9800}{}{Stuhl}
{9801}{}{Ein verrotteter, stinkender alter Stuhl, der zur Stütze auf Ziegelsteinen steht. Sieht ziemlich unbequem aus.}
{9900}{}{Couch}
{9901}{}{Ein sehr unbequem aussehendes Sitzmöbel, auch als Couch bekannt.}
{10000}{}{Couch}
{10001}{}{Ein sehr unbequem aussehendes Sitzmöbel, auch als Couch bekannt.}
{10100}{}{Reifen}
{10101}{}{Ein alter Gummireifen liegt mitten im Unkraut.}
{10200}{}{Strauch}
{10201}{}{Irgendein Wüstenkraut.}
{10300}{}{Strauch}
{10301}{}{Irgendein Wüstenkraut.}
{10400}{}{Strauch}
{10401}{}{Irgendein Wüstenkraut.}
{10500}{}{Strauch}
{10501}{}{Irgendein Wüstenkraut.}
{10600}{}{Schrott}
{10601}{}{Eine verrostete Autotür lehnt an einem verrosteten Metallfass. Hier rostet wirklich alles.}
{10700}{}{Schrott}
{10701}{}{Eine kaputte Toilette, halb im Sand vergraben. Das Leben ist scheiße, und dann stirbt man.}
{10800}{}{Unkraut}
{10801}{}{Irgendein Wüstenstrauch. Falls er in jüngster Vergangenheit noch gewachsen ist, tut er es jetzt nicht mehr.}
{10900}{}{Schrott}
{10901}{}{Ein Autoreifen, im Sand vergraben. Ringsherum liegen ein paar kleine Holzstücke.}
{11000}{}{Schrott}
{11001}{}{Bei genauerer Betrachtung denkst du, dass es sich tatsächlich um Stücke versteinerten Holzes handeln könnte.}
{11100}{}{Erde}
{11101}{}{Ein kleiner Erdhaufen, aus dem ein totes Kraut hervorragt.}
{11200}{}{Erde}
{11201}{}{Ein kleiner Erdhaufen.}
{11300}{}{Erde}
{11301}{}{Ein kleiner Erdhaufen.}
{11400}{}{Erde}
{11401}{}{Ein kleiner Erdhaufen.}
{11500}{}{Kraut}
{11501}{}{Ein kleiner Erdhaufen, aus dem ein trockenes Unkraut herausragt.}
{11600}{}{Schrott}
{11601}{}{Ein verdrehtes Stück verrostetes Metall.}
{11700}{}{Schrott}
{11701}{}{Ein paar zerbrochene Holzstücke.}
{11800}{}{Schrott}
{11801}{}{Ein kleiner Haufen allerlei Schrott.}
{11900}{}{Erde}
{11901}{}{Ein kleiner Erdhaufen.}
{12000}{}{Erde}
{12001}{}{Ein kleiner Erdhaufen.}
{12100}{}{Erde}
{12101}{}{Ein kleiner Erdhaufen.}
{12200}{}{Erde}
{12201}{}{Ein kleiner Erdhaufen.}
{12300}{}{Erde}
{12301}{}{Ein kleiner Erdhaufen.}
{12400}{}{Erde}
{12401}{}{Ein kleiner Erdhaufen.}
{12500}{}{Kraut}
{12501}{}{Ein gewöhnliches Wüstenunkraut.}
{12600}{}{Kraut}
{12601}{}{Ein gewöhnliches Wüstenunkraut.}
{12700}{}{Kraut}
{12701}{}{Ein gewöhnliches Wüstenunkraut.}
{12800}{}{Blockierendes Hexfeld (kein Licht)}
{12900}{}{Tanker}
{13000}{}{Tanker}
{13100}{}{Tanker}
{13200}{}{Tanker}
{13300}{}{Tanker}
{13400}{}{Tanker}
{13500}{}{Tanker}
{13600}{}{Tanker}
{13700}{}{Tanker}
{13800}{}{Tanker}
{13900}{}{Tanker}
{13901}{}{Es ist eine alte, ziemlich wackelige Leiter.}
{14000}{}{Kanalöffnung}
{14001}{}{Sieht aus wie ein Zugangsschacht zu den unterirdischen Anlagen.}
{14100}{}{Lichtquelle}
{14200}{}{Tür}
{14201}{}{Das sieht aus wie eine gewöhnliche Vault-Tür, die beschädigt wurde, vielleicht durch Feuer. Sie funktioniert jedoch noch.}
{14300}{}{Tür}
{14301}{}{Das sieht aus wie eine gewöhnliche Vault-Tür, die beschädigt wurde, vielleicht durch Feuer. Sie funktioniert jedoch noch.}
{14400}{}{Deckung}
{14401}{}{Ein schwerer Kanaldeckel. Er sieht gut erhalten aus und wurde offenbar vor Kurzem bewegt.}
{14500}{}{Loch}
{14501}{}{In diese Tür wurde ein großes Loch gesprengt.}
{14600}{}{Loch}
{14601}{}{In diese Tür wurde ein großes Loch gesprengt.}
{14700}{}{Kugelsicheres Glas}
{14701}{}{Völlig unzerbrechliches Glas. Versuch es gar nicht erst.}
{14800}{}{Kugelsicheres Glas}
{14801}{}{Völlig unzerbrechliches Glas. Versuch es gar nicht erst.}
{14900}{}{Kugelsicheres Glas}
{14901}{}{Völlig unzerbrechliches Glas. Versuch es gar nicht erst.}
{15000}{}{Kugelsicheres Glas}
{15001}{}{Völlig unzerbrechliches Glas. Versuch es gar nicht erst.}
{15100}{}{Zielscheibe}
{15101}{}{Diese Zielscheibe wurde sorgfältig an die Wand gemalt.}
{15200}{}{Das Heck des Flugzeugs}
{15300}{}{Das Heck des Flugzeugs}
{15400}{}{Flugzeugtür}
{15500}{}{Aufzug}
{15501}{}{Dies ist das Innere eines Vault-Tec-Aufzugs. Es ist blitzblank!}
{15600}{}{Aufzug}
{15601}{}{Dies ist das Innere eines Vault-Tec-Aufzugs. Es ist blitzblank!}
{15700}{}{Trockenes Gras}
{15701}{}{Nur trockenes Gras.}
{15800}{}{Monitor}
{15801}{}{Du siehst einen Computermonitor.}
{15900}{}{Monitor}
{15901}{}{Du siehst einen Computermonitor.}
{16000}{}{Computer}
{16001}{}{Dies ist ein Computerspeicher.}
{16100}{}{Computer}
{16101}{}{Dies ist ein Computerspeicher.}
{16200}{}{Computer}
{16201}{}{Ein Hightech-Computer, der moderne Magnetbandspeicher statt der veralteten Lochkarten verwendet.}
{16300}{}{Computer}
{16301}{}{Ein Hightech-Computer, der moderne Magnetbandspeicher statt der veralteten Lochkarten verwendet.}
{16400}{}{Monitor}
{16401}{}{Du siehst einen Computermonitor.}
{16500}{}{Monitor}
{16501}{}{Du siehst einen Computermonitor.}
{16600}{}{Kabel}
{16601}{}{Ein dickes Kabel.}
{16700}{}{Kabel}
{16701}{}{Ein dickes Kabel.}
{16800}{}{Kabel}
{16801}{}{Ein dickes Kabel.}
{16900}{}{Säule}
{16901}{}{Eine Stützsäule.}
{17000}{}{Säule}
{17001}{}{Eine Stützsäule.}
{17100}{}{Steuercomputer der Tür}
{17101}{}{Dieser Computer steuert die große Vault-Tür. Damit er funktioniert, musst du einen bestimmten Zugangscode eingeben.}
{17200}{}{Feuer}
{17300}{}{Äußere Tür von Vault 8}
{17301}{}{Diese große Tür verbindet den Vault mit der Außenwelt.}
{17400}{}{Äußere Tür von Vault 8}
{17401}{}{Diese große Tür verbindet den Vault mit der Außenwelt.}
{17500}{}{Basis}
{17501}{}{Automatisierte Basis für den Aufseherposten.}
{17600}{}{Pfeil nach unten}
{17700}{}{Pfeil nach oben}
{17800}{}{Kiste}
{17900}{}{Kiste}
{18000}{}{Kiste}
{18100}{}{Schalter}
{18101}{}{Schalter für die Wasserpumpe.}
{18200}{}{Hydraulikpumpe}
{18201}{}{Diese Pumpe fördert Grundwasser. Eine ziemlich seltene Maschine.}
{18300}{}{Träger}
{18400}{}{Betonbarriere}
{18500}{}{Betonbarriere}
{18600}{}{Ventil}
{18700}{}{Schalter}
{18800}{}{Betonbarriere}
{18900}{}{Betonbarriere}
{19000}{}{Etagenbett}
{19001}{}{Ein Etagenbett im Militärstil. Sieht sehr unbequem aus. Außerdem sieht es so aus, als könnte man von diesen Laken eine Münze abprallen lassen.}
{19100}{}{Etagenbett}
{19101}{}{Ein Etagenbett im Militärstil. Sieht sehr unbequem aus. Außerdem sieht es so aus, als könnte man von diesen Laken eine Münze abprallen lassen.}
{19200}{}{Etagenbett}
{19201}{}{Ein Etagenbett im Militärstil. Sieht sehr unbequem aus. Außerdem sieht es so aus, als könnte man von diesen Laken eine Münze abprallen lassen.}
{19300}{}{Kiste}
{19400}{}{Nuka-Cola-Maschine}
{19401}{}{Die Werbung an der Seite dieser Maschine preist ihre beliebte Limonade an.}
{19500}{}{Wand}
{19600}{}{Falltür}
{19601}{}{Sieht aus wie eine völlig intakte Falltür.}
{19700}{}{Gully}
{19701}{}{Die Leiter in diesem Gully führt hinunter in die Dunkelheit. Ohhh, gruselig.}
{19800}{}{Vault-Tür}
{19801}{}{Das ist eine Außentür deines Vaults. Sie ist verschlossen und lässt sich nur von innen öffnen.}
{19900}{}{Robocop}
{19901}{}{Verschiedene Ersatzteile, die zum Bau eines Polizeiroboters benötigt werden.}
{20000}{}{Kirchenbank}
{20001}{}{Sieht genauso aus, wie man es erwarten würde. An dieser Kirchenbank ist nichts Besonderes.}
{20100}{}{Wegweiser}
{20101}{}{Das Schild an diesem Pfosten sieht etwas rostig aus.}
{20200}{}{Wegweiser}
{20201}{}{Das Schild an diesem Pfosten sieht etwas rostig aus.}
{20300}{}{Wegweiser}
{20301}{}{Das Schild an diesem Pfosten sieht etwas rostig aus.}
{20400}{}{Wegweiser}
{20401}{}{Das Schild an diesem Pfosten sieht etwas rostig aus.}
{20500}{}{Wegweiser}
{20501}{}{Das Schild an diesem Pfosten sieht etwas rostig aus.}
{20600}{}{Alte Matratze}
{20601}{}{Eine alte, ramponierte Matratze. Du glaubst, eine Art kleines, käferartiges Viehzeug darin zu sehen.}
{20700}{}{Alte Matratze}
{20701}{}{Selbst wenn du allein auf diesem Ding schlafen würdest, wärst du nicht allein.}
{20800}{}{Bett}
{20801}{}{Ein behelfsmäßiges Bett. Das Material wurde irgendwo anders aufgetrieben.}
{20900}{}{Bett}
{20901}{}{Ein behelfsmäßiges Bett. Das Material wurde irgendwo anders aufgetrieben.}
{21000}{}{Bett}
{21001}{}{Dieses Bett hat schon bessere Tage (und wahrscheinlich auch Nächte) gesehen.}
{21100}{}{Bett}
{21101}{}{Bei näherer Betrachtung stellst du fest, dass die Laken schon sehr, sehr lange nicht mehr gewechselt wurden.}
{21200}{}{Bett}
{21201}{}{Auf diesem abgenutzten Schlafplatz sind ein paar Flecken unbekannter Herkunft.}
{21300}{}{Bett}
{21301}{}{Dieses Bett hat viel benutzt und abgenutzt ausgesehen. Sieht aus, als wäre etwas unter die Matratze gekrochen und dort gestorben.}
{21400}{}{Erde}
{21500}{}{Erde}
{21600}{}{Erde}
{21700}{}{Erde}
{21800}{}{Erde}
{21900}{}{Erde}
{22000}{}{Kisten}
{22001}{}{Diese Holzkisten zerfallen durch die Witterung.}
{22100}{}{Kisten}
{22101}{}{An diesen Holzkisten findest du nichts Erwähnenswertes.}
{22200}{}{Kisten}
{22201}{}{Du hast wirklich viel Zeit übrig, wenn du dir diesen verrotteten Muell so genau ansiehst.}
{22300}{}{Kisten}
{22301}{}{Diese Holzkisten zerfallen durch die Witterung.}
{22400}{}{Auto}
{22401}{}{Dieses Auto ist in schrecklichem Zustand. Dir fällt keine Möglichkeit ein, es wieder flottzumachen.}
{22500}{}{Auto}
{22501}{}{Dieses verrostete Stück Altmetall lässt sich nicht wieder herrichten.}
{22600}{}{Auto}
{22601}{}{Du kommst zu dem Schluss, dass dieses Fahrzeug nie wieder fahren wird. Wirklich.}
{22700}{}{Auto}
{22701}{}{Dieser Schrotthaufen wird ganz sicher nie wieder fahren.}
{22800}{}{Auto}
{22801}{}{Selbst wenn der Mechaniker des Jahres plötzlich neben dir auftauchte, könntet ihr diesen rostigen Haufen nicht reparieren.}
{22900}{}{Stuhl}
{22901}{}{Ein bequemer Stuhl.}
{23000}{}{Stuhl}
{23001}{}{Dieser Stuhl hat schon bessere Jahre gesehen.}
{23100}{}{Stuhl}
{23101}{}{Dieser Stuhl ist verschimmelt und widerlich. Wie du dir denken kannst, stinkt er auch.}
{23200}{}{Stuhl}
{23201}{}{Dieser Stuhl fällt auseinander. Und zwar schnell.}
{23300}{}{Stuhl}
{23301}{}{Wenn dir jemand viel Geld dafür zahlte und du außerdem ein Hinterteil aus Stahl hättest, könntest du in Betracht ziehen, dich auf diesen Stuhl zu setzen.}
{23400}{}{Stuhl}
{23401}{}{Das sieht aus wie ein alter Bürostuhl, der sich all die Jahre ziemlich gut gehalten hat.}
{23500}{}{Stuhl}
{23501}{}{Das ist ein alter Bürostuhl. Vielleicht hält er sogar das Gewicht eines Menschen aus.}
{23600}{}{Stuhl}
{23601}{}{Dieser Bürostuhl hat schon bessere Tage gesehen. Jetzt ist er praktisch Schrott.}
{23700}{}{Stuhl}
{23701}{}{Das sieht aus wie ein Stuhl aus dem Büro eines Leichenbestatters – tot.}
{23800}{}{Felsen}
{23900}{}{Felsen}
{24000}{}{Leiter}
{24100}{}{Leiter}
{24200}{}{Träger}
{24300}{}{Hydrant}
{24301}{}{Das ist ein Hydrant. Ohne Sprinkler an der Vault-Decke brauchst du vielleicht so einen, um Feuer zu löschen.}
{24400}{}{Laternenmast}
{24401}{}{Dieser Laternenmast scheint noch zu funktionieren. Stell dir vor: Etwas hier draußen, das funktioniert.}
{24500}{}{Laternenmast}
{24501}{}{Dieser Laternenmast wird nie wieder funktionieren.}
{24600}{}{Laternenmast}
{24601}{}{Das ist ein funktionierender Laternenmast. Nachts verbreitet er ein fahles, sanftes Licht, das dich an absolut nichts erinnert.}
{24700}{}{Laternenmast}
{24701}{}{Das ist ein kaputter Laternenmast. Er lässt sich nicht reparieren.}
{24800}{}{Laternenmast}
{24801}{}{Diese Leuchte funktioniert.}
{24900}{}{Laternenmast}
{24901}{}{Die Lampe in diesem Laternenmast ist so zerschmettert, dass sie nicht mehr zu reparieren ist.}
{25000}{}{Laternenmast}
{25001}{}{Das ist ein funktionierender Laternenmast.}
{25100}{}{Zerschmetterte Tür.}
{25101}{}{Diese Tür wurde durch eine Explosion zerschmettert und lässt sich nicht auf gewöhnliche Weise öffnen.}
{25200}{}{Schrott}
{25201}{}{Definitiv nutzloser Schrott, kein Zweifel.}
{25300}{}{Schrott}
{25301}{}{Definitiv nutzloser Schrott, kein Zweifel.}
{25400}{}{Schrott}
{25401}{}{Definitiv nutzloser Schrott, kein Zweifel.}
{25500}{}{Schrott}
{25501}{}{Definitiv nutzloser Schrott, kein Zweifel.}
{25600}{}{Schrott}
{25601}{}{Definitiv nutzloser Schrott, kein Zweifel.}
{25700}{}{Briefkasten}
{25701}{}{Der Briefkasten ist leer. Du hast das Gefühl, dass das schon eine Weile so ist.}
{25800}{}{Tür}
{25801}{}{Eine hübsch gearbeitete Holztür in gutem Zustand.}
{25900}{}{Tür}
{25901}{}{Eine hübsch gearbeitete Holztür in gutem Zustand.}
{26000}{}{Tür}
{26001}{}{Eine hübsch gearbeitete Holztür in gutem Zustand.}
{26100}{}{Tür}
{26101}{}{Eine hübsch gearbeitete Holztür in gutem Zustand.}
{26200}{}{Kirchenbank}
{26201}{}{Diese Kirchenbank fällt langsam auseinander.}
{26300}{}{Kirchenbank}
{26301}{}{Diese Kirchenbank wurde vernachlässigt und zeigt deutliche Verschleißspuren.}
{26400}{}{Kirchenbank}
{26401}{}{Eine Holzkirchbank, die Alter und Misshandlung nicht standgehalten hat.}
{26500}{}{Zeitungsautomat}
{26501}{}{Der Zeitungsautomat ist höchstwahrscheinlich leer.}
{26600}{}{Zeitungsautomat}
{26601}{}{Der Zeitungsautomat ist höchstwahrscheinlich leer.}
{26700}{}{Zeitungsautomat}
{26701}{}{Der Zeitungsautomat ist höchstwahrscheinlich leer.}
{26800}{}{Zeitungsautomat}
{26801}{}{Der Zeitungsautomat ist höchstwahrscheinlich leer.}
{26900}{}{Zeitungsautomat}
{26901}{}{Der Zeitungsautomat ist höchstwahrscheinlich leer.}
{27000}{}{Zeitungsautomat}
{27001}{}{Der Zeitungsautomat ist höchstwahrscheinlich leer. Sieht aus, als hätte er einmal Erwachsenenmagazine enthalten.}
{27100}{}{Schrott}
{27101}{}{Eine Matratze in schrecklichem Zustand. Nicht einmal die Ratten würden darauf oder darin schlafen.}
{27200}{}{Schrott}
{27201}{}{Eine Matratze für ein Einzelbett, die schon wesentlich bessere Tage gesehen hat.}
{27300}{}{Schrott}
{27301}{}{Ein Haufen verfaultes, verwittertes Holz. Sein Gewicht in, na ja, irgendetwas ist es nicht wert.}
{27400}{}{Schrott}
{27401}{}{Ein Haufen Holz mit tief darin steckenden alten, rostigen Nägeln. Völlig nutzlos.}
{27500}{}{Kisten}
{27501}{}{Ein Haufen alter Pappkartons. Du kannst kaum glauben, dass sie so lange überlebt haben.}
{27600}{}{Kisten}
{27601}{}{Ein Haufen alter Pappkartons.}
{27700}{}{Schrott}
{27701}{}{Ein bisschen Gerümpel, das vor seiner Zerstörung durch die Umwelt vielleicht einmal eine Matratze war.}
{27800}{}{Felsen}
{27900}{}{Felsen}
{28000}{}{Felsen}
{28100}{}{Der Aufzugsschacht}
{28200}{}{Waschbecken}
{28201}{}{Ein Porzellanwaschbecken, das schon lange nicht mehr funktioniert.}
{28300}{}{Waschbecken}
{28301}{}{Ein kaputtes Porzellanwaschbecken. Im Becken steht eine kleine Pfütze braunen Wassers, darin treibt eine tote Ratte.}
{28400}{}{Waschbecken}
{28401}{}{Dieses Waschbecken funktioniert nicht. Der große Riss in der Mitte verrät es.}
{28500}{}{Waschbecken}
{28501}{}{Ein kaputtes Porzellanwaschbecken. Im Becken steht eine kleine Pfütze braunen Wassers, darin treibt eine tote Ratte.}
{28600}{}{Stoppschild}
{28601}{}{Ein rotes Schild mit dem Wort STOP in großen Blockbuchstaben.}
{28700}{}{Stoppschild}
{28701}{}{Ein rotes Schild mit dem Wort STOP in großen Blockbuchstaben. Das Einschussloch kam erst nach der Herstellung dazu.}
{28800}{}{Ampel}
{28801}{}{Das ist ein uraltes Gerät zur Regelung des Autoverkehrs.}
{28900}{}{Ampel}
{28901}{}{Das ist ein uraltes Gerät zur Regelung des Autoverkehrs.}
{29000}{}{Ampel}
{29001}{}{Das ist ein uraltes Gerät zur Regelung des Autoverkehrs.}
{29100}{}{Straßenlaterne}
{29101}{}{Diese Straßenlaterne sorgt nach Einbruch der Nacht oder in dunklen Bereichen für Beleuchtung.}
{29200}{}{Straßenlaterne}
{29201}{}{Diese Straßenlaterne sorgt nach Einbruch der Nacht oder in dunklen Bereichen für Beleuchtung.}
{29300}{}{Straßenlaterne}
{29301}{}{Diese Straßenlaterne sorgt nach Einbruch der Nacht oder in dunklen Bereichen für Beleuchtung.}
{29400}{}{Straßenlaterne}
{29401}{}{Diese Straßenlaterne sorgt nach Einbruch der Nacht oder in dunklen Bereichen für Beleuchtung.}
{29500}{}{Straßenlaterne}
{29501}{}{Diese Straßenlaterne könnte in dunklen Bereichen für Beleuchtung sorgen, wenn sie nicht völlig kaputt wäre.}
{29600}{}{Straßenlaterne}
{29601}{}{Diese Straßenlaterne könnte in dunklen Bereichen für Beleuchtung sorgen, wenn sie nicht völlig kaputt wäre.}
{29700}{}{Straßenlaterne}
{29701}{}{Diese Straßenlaterne könnte in dunklen Bereichen für Beleuchtung sorgen, wenn sie nicht völlig kaputt wäre.}
{29800}{}{Wegweiser}
{29801}{}{Dieses Schild sollte angeben, an welcher Straße es steht, doch die Buchstaben sind bis zur Unkenntlichkeit verblasst.}
{29900}{}{Wegweiser}
{29901}{}{Dieses Schild sollte angeben, an welcher Straße es steht, doch die Buchstaben sind bis zur Unkenntlichkeit verblasst.}
{30000}{}{Tisch}
{30001}{}{Ein Holztisch in passablem bis mittelmäßigem Zustand.}
{30100}{}{Tisch}
{30101}{}{Ein Holztisch in passablem bis mittelmäßigem Zustand.}
{30200}{}{Tisch}
{30201}{}{Ein Holztisch in mittelmäßigem bis schlechtem Zustand.}
{30300}{}{Tisch}
{30301}{}{Ein Holztisch mit Kunststoffoberfläche, der schon seit einer Weile kaputt ist.}
{30400}{}{Tisch}
{30401}{}{Ein Holztisch, kotzgrün gestrichen und nicht mehr zu reparieren.}
{30500}{}{Tisch}
{30501}{}{Das sieht aus wie ein alter Couchtisch, niedrig genug für diese wirklich kleinen Mutanten.}
{30600}{}{Tisch}
{30601}{}{Das sieht aus wie ein alter Couchtisch, niedrig genug für diese wirklich kleinen Mutanten.}
{30700}{}{Toilette}
{30701}{}{Die geschärften Kanten rund um den Sitz machen das Sitzen hier äußerst unbequem.}
{30800}{}{Toilette}
{30801}{}{Diese Toilette ist kaputt.}
{30900}{}{Toilette}
{30901}{}{Igitt! Wer auch immer zuletzt hier war, hat nicht gespült!}
{31000}{}{Toilette}
{31001}{}{Diese Toilette ist kaputt und für Frauen definitiv nicht benutzbar.}
{31100}{}{Muell}
{31101}{}{Ein paar kaputte Rohre, halb im Dreck vergraben. Hier gibt es nichts Wichtiges zu sehen. Weitergehen.}
{31200}{}{Muell}
{31201}{}{Ein paar zerbrochene Glasscherben und anderer kaputter Schrott.}
{31300}{}{Muell}
{31301}{}{Ein paar zerbrochene Glasscherben und anderer kaputter Schrott.}
{31400}{}{Muell}
{31401}{}{Ein Rohr, das in der Mitte durchgebrochen ist. Es sieht aus, als wäre es so lange verrostet, bis es unter seinem eigenen Gewicht zusammenbrach.}
{31500}{}{Muelleimer}
{31501}{}{Ein Muelleimer. Das Etikett ist kaum noch zu lesen: Haltet eure Straßen sauber!}
{31600}{}{Baum}
{31601}{}{Ein toter Baum.}
{31700}{}{Baum}
{31701}{}{Ein Baumstumpf. Nichts wirklich Aufregendes. Tatsächlich könnte das das Langweiligste sein, was du je gesehen hast.}
{31800}{}{Baum}
{31801}{}{Ein toter Baum.}
{31900}{}{Baum}
{32000}{}{Baum}
{32100}{}{Baum}
{32200}{}{Hindernis}
{32300}{}{Lkw}
{32301}{}{Die verrotteten Überreste eines Diesel-Lkw. Dieser Metallhaufen wird sich nie wieder bewegen.}
{32400}{}{Lkw}
{32401}{}{Diesem Diesel-Lkw ist nicht mehr zu helfen. Nicht im Geringsten.}
{32500}{}{Badewanne}
{32501}{}{Diese Badewanne ist kaputt und voller Risse.}
{32600}{}{Badewanne}
{32601}{}{Bei näherer Betrachtung wird dir klar, dass du in dieser Wanne wohl doch kein Bad nehmen wirst.}
{32700}{}{Urinal}
{32701}{}{Es ist einfach nur ein Urinal.}
{32800}{}{Urinal}
{32801}{}{Es ist einfach nur ein Urinal.}
{32900}{}{Urinal}
{32901}{}{Es ist einfach nur ein Urinal. Nichts Besonderes.}
{33000}{}{Urinal}
{33001}{}{Es ist einfach nur ein Urinal. Nichts Besonderes.}
{33100}{}{Wassertank}
{33101}{}{Ein großer Tank für Flüssigkeiten. In diesem Fall glaubst du, dass er zur Lagerung von Wasser gedacht war.}
{33200}{}{Tür}
{33201}{}{Eine Holztür. Nichts besonders Interessantes daran.}
{33300}{}{Tür}
{33301}{}{Eine Holztür. Sie dient als Ein- und Ausgang dieses Gebäudes.}
{33400}{}{Wandlampe}
{33401}{}{Diese Lampe scheint in gutem Zustand zu sein.}
{33500}{}{Wandlampe}
{33501}{}{Eine kaputte Lampe. Kein Wunder, dass sie nicht funktioniert.}
{33600}{}{Wandlampe}
{33601}{}{Diese Lampe scheint in gutem Zustand zu sein.}
{33700}{}{Wandlampe}
{33701}{}{Eine kaputte Lampe. Kein Wunder, dass sie nicht funktioniert.}
{33800}{}{Wandlampe}
{33801}{}{Diese Lampe scheint in gutem Zustand zu sein.}
{33900}{}{Wandlampe}
{33901}{}{Eine kaputte Lampe. Kein Wunder, dass sie nicht funktioniert.}
{34000}{}{Wandlampe}
{34001}{}{Diese Lampe scheint in gutem Zustand zu sein.}
{34100}{}{Wandlampe}
{34101}{}{Eine kaputte Lampe. Kein Wunder, dass sie nicht funktioniert.}
{34200}{}{Vorfahrt-gewähren-Schild}
{34201}{}{Dieses Schild regelte den Verkehrsfluss.}
{34300}{}{Vorfahrt-gewähren-Schild}
{34301}{}{Das Schild ist verblasst, aber du kannst noch das Wort YIELD erkennen.}
{34400}{}{Block Hex Auto Inviso}
{34401}{}{Wenn du das sehen kannst, gib dem technischen Designer die Schuld.}
{34500}{}{Gully}
{34600}{}{Tür}
{34601}{}{Eine verzierte Holztür. Sie ist offensichtlich mit großer Handwerkskunst gefertigt.}
{34700}{}{Kirchenbank}
{34701}{}{Dieser Sitz wird von großen Betonziegeln gestützt. Das ist unwichtig, aber du hast ja danach gefragt.}
{34800}{}{Treppe}
{34801}{}{Diese Treppe führt nach oben.}
{34900}{}{Erde}
{35000}{}{Erde}
{35100}{}{Brückenpfeiler}
{35200}{}{Schild}
{35201}{}{Ein verwittertes Straßenschild. Die Zahlen „14:6“ sind noch darauf zu erkennen.}
{35300}{}{Lkw}
{35301}{}{Die Überreste eines Fernlastwagens.}
{35400}{}{Wegweiser}
{35401}{}{Ein schiefes Straßenschild.}
{35500}{}{Erde}
{35600}{}{Treppe}
{35601}{}{Diese Treppe führt nach unten.}
{35700}{}{Motorrad}
{35701}{}{Dieses Motorrad hat eine Fingerabdrucksicherung und kann daher nur vom Besitzer benutzt werden.}
{35800}{}{Motorrad}
{35801}{}{Dieses Motorrad hat eine Fingerabdrucksicherung und kann daher nur vom Besitzer benutzt werden.}
{35900}{}{Motorrad}
{35901}{}{Dieses Motorrad hat eine Fingerabdrucksicherung und kann daher nur vom Besitzer benutzt werden.}
{36000}{}{Motorrad}
{36001}{}{Dieses Motorrad hat eine Fingerabdrucksicherung und kann daher nur vom Besitzer benutzt werden.}
{36100}{}{Vorhang}
{36101}{}{Dieser Vorhang sieht aus, als wäre er mit primitiven Mitteln hergestellt worden, ist aber sehr zweckmäßig.}
{36200}{}{Vorhang}
{36201}{}{Dieser Vorhang sieht aus, als wäre er mit primitiven Mitteln hergestellt worden, ist aber sehr zweckmäßig.}
{36300}{}{Schüssel}
{36301}{}{Eine kunstvoll gefertigte Holzschüssel. Sie sieht aus, als wäre sie dazu gedacht, Getreide zu zerkleinern und zu trennen.}
{36400}{}{Schüssel}
{36401}{}{Eine kunstvoll gefertigte Holzschüssel.}
{36500}{}{Topf}
{36501}{}{Ein kunstvoll gefertigter Topf.}
{36600}{}{Pflanze}
{36601}{}{Für dich sieht sie wie ein mutierter Kohlkopf aus. Bei dem warmen Wetter scheint sie prächtig zu gedeihen.}
{36700}{}{Pflanze}
{36701}{}{Für dich sieht sie wie ein mutierter Kohlkopf aus. Bei dem warmen Wetter scheint sie prächtig zu gedeihen.}
{36800}{}{Karren}
{36801}{}{Ein grob gefertigter, aber zweckmäßiger landwirtschaftlicher Karren.}
{36900}{}{Mais}
{37000}{}{Mais}
{37100}{}{Mais}
{37200}{}{Topf}
{37201}{}{Ein fein gearbeiteter Tontopf.}
{37300}{}{Rechen}
{37301}{}{Dieser Rechen gehört seinen Besitzern. Du kannst dir nicht einmal vorstellen, wozu du ihn gebrauchen könntest.}
{37400}{}{Rechen}
{37401}{}{Dieser Rechen gehört seinen Besitzern. Du kannst dir nicht einmal vorstellen, wozu du ihn gebrauchen könntest.}
{37500}{}{Rechen}
{37501}{}{Dieser Rechen gehört seinen Besitzern. Du kannst dir nicht einmal vorstellen, wozu du ihn gebrauchen könntest.}
{37600}{}{Teppich}
{37601}{}{Ein einfacher Teppich. Der Weber war offensichtlich sehr talentiert.}
{37700}{}{Teppich}
{37701}{}{Ein einfacher Teppich. Der Weber war offensichtlich sehr talentiert.}
{37800}{}{Teppich}
{37801}{}{Ein einfacher Teppich. Der Weber war offensichtlich sehr talentiert.}
{37900}{}{Pflanze}
{37901}{}{Dekorative Zimmerpflanze.}
{38000}{}{Pflanze}
{38001}{}{Dekorative Zimmerpflanze.}
{38100}{}{Motorrad}
{38101}{}{Dieses Motorrad hat eine Fingerabdrucksicherung und kann daher nur vom Besitzer benutzt werden.}
{38200}{}{Vase}
{38201}{}{Eine sehr hübsche Tonvase.}
{38300}{}{Brunnen}
{38301}{}{Ein typischer Brunnen, wie man ihn im Ödland findet.}
{38400}{}{Pfosten}
{38401}{}{Dieser Pfosten stützt die Jurte.}
{38500}{}{Pfosten}
{38501}{}{Dieser Pfosten stützt die Jurte.}
{38600}{}{Pfosten}
{38601}{}{Dieser Pfosten stützt die Jurte.}
{38700}{}{Pfosten}
{38701}{}{Dieser Pfosten stützt die Jurte.}
{38800}{}{Pfosten}
{38801}{}{Dieser Pfosten stützt die Jurte.}
{38900}{}{Pfosten}
{38901}{}{Dieser Pfosten stützt die Jurte.}
{39000}{}{Vault-Tür}
{39001}{}{Diese Vault-Tür ist inzwischen nur noch ein schweres Stück Metallschrott.}
{39100}{}{Tür von Vault 15}
{39101}{}{Eine identische große Tür zum Vault, wie die in deiner Stadt, nur rostiger.}
{39200}{}{Stütze}
{39201}{}{Diese Stütze dient zur Stabilisierung der Verteidigungsmauer.}
{39300}{}{Stütze}
{39301}{}{Diese Stütze dient zur Stabilisierung der Verteidigungsmauer.}
{39400}{}{Stütze}
{39401}{}{Diese Stütze dient zur Stabilisierung der Verteidigungsmauer.}
{39500}{}{Stütze}
{39501}{}{Diese Stütze dient zur Stabilisierung der Verteidigungsmauer.}
{39600}{}{Metallfässer}
{39601}{}{Ein rostiges Metallfass. Es ist leer.}
{39700}{}{Metallfässer}
{39701}{}{Dieses Fass ist wahrscheinlich leer, dem hohlen Klang nach zu urteilen.}
{39800}{}{Metallfässer}
{39801}{}{Diese Fässer sind wahrscheinlich leer, dem hohlen Klang nach zu urteilen.}
{39900}{}{Metallfässer}
{39901}{}{Diese Fässer sind wahrscheinlich leer, dem hohlen Klang nach zu urteilen.}
{40000}{}{Lüftungsschacht}
{40001}{}{Dieser Lüftungsschacht scheint zu einer unterirdischen Anlage zu gehören.}
{40100}{}{Kiste}
{40101}{}{Eine Holzkiste. Sie sieht gar nicht so schlecht aus.}
{40200}{}{Kiste}
{40201}{}{Eine einfache Holzkiste. In recht gutem Zustand.}
{40300}{}{Kiste}
{40301}{}{Diese einfache Holzkiste ist unter ihrem eigenen Gewicht zusammengebrochen.}
{40400}{}{Schreibtisch}
{40401}{}{Ein einfacher Schreibtisch mit einem Computer.}
{40500}{}{Schreibtisch}
{40501}{}{Ein einfacher Schreibtisch mit einem Computer.}
{40600}{}{Tür}
{40601}{}{Eine Holztür in recht gutem Zustand.}
{40700}{}{Einsturz}
{40701}{}{Eine große Menge Geröll, viel zu viel, um es ohne Weiteres wegzuräumen.}
{40800}{}{Auto}
{40801}{}{Dieses überflutete Auto lässt sich nicht reparieren.}
{40900}{}{Auto}
{40901}{}{Dieses Auto ist etwas nass und lässt sich nicht reparieren.}
{41000}{}{Auto}
{41001}{}{Dieses Auto wurde schlecht geparkt. Leider ist es nicht mehr zu reparieren.}
{41100}{}{Schrott}
{41101}{}{Dieser Schrott wurde vom verseuchten Meerwasser zerstört.}
{41200}{}{Schrott}
{41201}{}{Dieser Schrott ist fast weggespült worden.}
{41300}{}{Schrott}
{41301}{}{Eine erlesene Auswahl nutzlosen Schrotts.}
{41400}{}{Rohre}
{41401}{}{Diese dicken Rohre werden zum Pumpen großer Flüssigkeitsmengen verwendet.}
{41500}{}{Rohr}
{41501}{}{Diese dicken Rohre werden zum Pumpen großer Flüssigkeitsmengen verwendet.}
{41600}{}{Rohre}
{41601}{}{Diese dicken Rohre werden zum Pumpen großer Flüssigkeitsmengen verwendet.}
{41700}{}{Aufzugsschacht}
{41701}{}{Ein Teil eines Aufzugsystems.}
{41800}{}{Aufzugsschacht}
{41801}{}{Ein Aufzugsschacht, der tief in den Boden reicht. Er wurde beschädigt.}
{41900}{}{Aufzug}
{41901}{}{Ein Aufzug. Benutze ihn, um zwischen den Ebenen auf und ab zu fahren.}
{42000}{}{Aufzugsschacht}
{42001}{}{Ein Aufzugsschacht, der tief in den Boden reicht. Er wurde beschädigt.}
{42100}{}{Elektronische Tür}
{42101}{}{Diese Tür hat ein elektronisches Schloss und ist mit Strom versorgt.}
{42200}{}{Rohr}
{42201}{}{Ein Metallrohr. Weitere Einzelheiten sind unwichtig.}
{42300}{}{Erde}
{42400}{}{Kiste}
{42500}{}{Kiste}
{42600}{}{Kiste}
{42700}{}{Kiste}
{42800}{}{Felsen}
{42801}{}{Ein Haufen Steine. Nicht besonders interessant.}
{42900}{}{Felsen}
{42901}{}{Ein Haufen Steine. Nicht besonders interessant.}
{43000}{}{Felsen}
{43001}{}{Ein kleiner Haufen Steine. Für dich nicht im Geringsten interessant.}
{43100}{}{Felsen}
{43101}{}{Ein sehr kleiner Haufen Steine.}
{43200}{}{Felsen}
{43201}{}{Ein sehr kleiner Haufen Steine.}
{43300}{}{Felsen}
{43301}{}{Ein sehr kleiner Haufen Steine.}
{43400}{}{Felsen}
{43401}{}{Ein sehr kleiner Haufen Steine.}
{43500}{}{Felsen}
{43501}{}{Ein kleiner Haufen Felsen.}
{43600}{}{Vault-Tür}
{43601}{}{Diese Vault-Tür ähnelt sehr der in Vault 8. Der Türmechanismus wurde außer Betrieb gesetzt.}
{43700}{}{Tür}
{43701}{}{Eine kunstvoll gefertigte Holztür, verstärkt mit verzierten Metallstreben von beinahe hypnotischem Design.}
{43800}{}{Tür}
{43801}{}{Eine kunstvoll gefertigte Holztür, verstärkt mit verzierten Metallstreben von beinahe hypnotischem Design.}
{43900}{}{Schatten}
{44000}{}{Schatten}
{44100}{}{Schatten}
{44200}{}{Schatten}
{44300}{}{Schatten}
{44400}{}{Schatten}
{44500}{}{Metallhaufen}
{44600}{}{Schrott}
{44601}{}{Ein Muellhaufen, bedeckt mit Sand und Gras. Aber irgendetwas daran ist besonders.}
{44700}{}{Schalttafel}
{44800}{}{Gitter}
{44801}{}{Schmutziges Kanalgitter.}
{44900}{}{Straßenlaterne}
{45000}{}{Brunnen}
{45001}{}{Ein typischer Brunnen, wie man ihn im Ödland findet.}
{45100}{}{Craps-Tisch}
{45200}{}{Craps-Tisch}
{45300}{}{Craps-Tisch}
{45400}{}{Craps-Tisch}
{45500}{}{Craps-Tisch}
{45600}{}{Craps-Tisch}
{45700}{}{Craps-Tisch}
{45800}{}{Craps-Tisch}
{45900}{}{Craps-Tisch}
{46000}{}{Craps-Tisch}
{46100}{}{Stein}
{46101}{}{Ein kleiner Stein, im Zusammenhang mit dieser Geschichte völlig uninteressant.}
{46200}{}{Stein}
{46300}{}{Stein}
{46400}{}{Stein}
{46500}{}{Spielautomat}
{46501}{}{Das ist ein Glücksspielautomat.}
{46600}{}{Spielautomat}
{46601}{}{Das ist ein Glücksspielautomat.}
{46700}{}{Türöffnung}
{46800}{}{Aufzug}
{46900}{}{Aufzug}
{47000}{}{Aufzugtür}
{47100}{}{Fenster}
{47101}{}{Statt Glas wurde für dieses Fenster Wachspapier verwendet.}
{47200}{}{Fenster}
{47201}{}{Statt Glas wurde für dieses Fenster Wachspapier verwendet.}
{47300}{}{Fenster}
{47301}{}{Statt Glas wurde für dieses Fenster Wachspapier verwendet.}
{47400}{}{Fenster}
{47401}{}{Statt Glas wurde für dieses Fenster Wachspapier verwendet.}
{47500}{}{Tür}
{47501}{}{Dieses große Metallrolltor wurde von innen blockiert.}
{47600}{}{Tür}
{47601}{}{Dieses große Metallrolltor wurde von innen blockiert.}
{47700}{}{Tür}
{47701}{}{Dieses große Metallrolltor wurde von innen blockiert. Darauf steht: NUR ANLIEFERUNG.}
{47800}{}{Tür}
{47801}{}{Dieses große Metallrolltor wurde von innen blockiert.}
{47900}{}{Tür}
{47901}{}{Dieses große Metallrolltor wurde von innen blockiert.}
{48000}{}{Tür}
{48001}{}{Dieses große Metallrolltor wurde von innen blockiert. Darauf steht: NUR ANLIEFERUNG.}
{48100}{}{Tür}
{48101}{}{Diese Tür sieht verdächtig nach der aus, die im Lagerhaus eingebaut ist.}
{48200}{}{Tür}
{48201}{}{Diese Tür sieht verdächtig nach der aus, die im Lagerhaus eingebaut ist.}
{48300}{}{Monitor}
{48301}{}{Ein Gerät zur autonomen Überwachung der Umgebung. Für mehr Robustheit mit einer 120 Pfund schweren Metallkonstruktion ausgestattet.}
{48400}{}{Kabel}
{48500}{}{Rednerpult}
{48501}{}{Das ist ein gewöhnliches Rednerpult.}
{48600}{}{Altar}
{48700}{}{Monitor}
{48701}{}{Ein großer Schwarz-Weiß-Monitor. Fast wie im Kino!}
{48800}{}{Kabel}
{48900}{}{Kraftfeld}
{48901}{}{Das ist ein mächtiges Energiefeld.}
{49000}{}{Kraftfeld}
{49001}{}{Das ist ein mächtiges Energiefeld.}
{49100}{}{Kraftfeld}
{49101}{}{Das ist ein mächtiges Energiefeld.}
{49200}{}{Kraftfeld}
{49201}{}{Das ist ein mächtiges Energiefeld.}
{49300}{}{Tisch}
{49301}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49400}{}{Tisch}
{49401}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49500}{}{Tisch}
{49501}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49600}{}{Tisch}
{49601}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49700}{}{Tisch}
{49701}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49800}{}{Tisch}
{49801}{}{Ein ziemlich gewöhnlicher Holztisch.}
{49900}{}{Schatten}
{50000}{}{Schatten}
{50100}{}{Schatten}
{50200}{}{Schatten}
{50300}{}{Schatten}
{50400}{}{Schatten}
{50500}{}{Altar}
{50501}{}{Ein einfacher Altar aus bemaltem Holz.}
{50600}{}{Kabel}
{50601}{}{Ein dickes Hochspannungskabel.}
{50700}{}{Kabel}
{50701}{}{Ein dickes Hochspannungskabel.}
{50800}{}{Altar}
{50801}{}{Ein einfacher Altar aus bemaltem Holz.}
{50900}{}{Lüftung}
{50901}{}{Ein rostiges Lüftungsgitter mit zerbrochenen Streben. Man kann hindurch auf die andere Seite gelangen.}
{51000}{}{Schatten}
{51100}{}{Schatten}
{51200}{}{Schatten}
{51300}{}{Schatten}
{51400}{}{Schatten}
{51500}{}{Schatten}
{51600}{}{Spuren}
{51601}{}{Du siehst die Spuren der Raupenketten des Roboters.}
{51700}{}{Spuren}
{51701}{}{Du siehst die Spuren der Raupenketten des Roboters.}
{51800}{}{Spuren}
{51801}{}{Du siehst die Spuren der Raupenketten des Roboters.}
{51900}{}{Spuren}
{51901}{}{Du siehst die Spuren der Raupenketten des Roboters.}
{52000}{}{Zylinder}
{52001}{}{Sauerstoff-Notvorratszylinder. Auf jeden ist in großen Buchstaben das Wort „EXPLOSIV!“ geschrieben.}
{52100}{}{Seil}
{52101}{}{Das Seil ist am Boden befestigt und hängt in dem übel riechenden Loch.}
{52200}{}{Schienen}
{52201}{}{Nur Schienen.}
{52300}{}{Öffnung}
{52301}{}{Eine sehr tiefe Öffnung. Starker Gestank nach Exkrementen.}
{52400}{}{Exkremente}
{52401}{}{Exkremente, die überall herumgeworfen wurden.}
{52500}{}{Kirchenbank}
{52501}{}{Eine hübsch gearbeitete und äußerst unbequem aussehende Kirchenbank.}
{52600}{}{Schatten}
{52700}{}{Wagen}
{52701}{}{Ein Karawanenwagen, umgebaut aus den Überresten eines uralten Autos.}
{52800}{}{Wagen}
{52801}{}{Ein Karawanenwagen, umgebaut aus den Überresten eines uralten Autos.}
{52900}{}{Wagen}
{52901}{}{Ein Karawanenwagen, umgebaut aus den Überresten eines uralten Autos.}
{53000}{}{Wagen}
{53001}{}{Ein Karawanenwagen, umgebaut aus den Überresten eines uralten Autos.}
{53100}{}{Wagen}
{53101}{}{Ein Karawanenwagen, umgebaut aus den Überresten eines uralten Autos.}
{53200}{}{Wagen}
{53201}{}{Ein Karawanenwagen, umgebaut aus den Überresten eines uralten Autos.}
{53300}{}{Matte}
{53301}{}{Eine Trainingsmatte.}
{53400}{}{Matte}
{53401}{}{Eine Trainingsmatte.}
{53500}{}{Matte}
{53501}{}{Eine Trainingsmatte.}
{53600}{}{Matte}
{53601}{}{Eine Trainingsmatte.}
{53700}{}{Boxsack}
{53701}{}{Das ist ein Strongman(tm)-Boxsack.}
{53800}{}{Stepper}
{53801}{}{Ein Trainingsgerät.}
{53900}{}{Stepper}
{54000}{}{Laufband}
{54001}{}{Ein Trainingsgerät.}
{54100}{}{Laufband}
{54101}{}{Ein Trainingsgerät.}
{54200}{}{Hantelbank}
{54201}{}{Ein Trainingsgerät.}
{54300}{}{Hantelbank}
{54301}{}{Ein Trainingsgerät.}
{54400}{}{Holzbretter}
{54401}{}{Diese stabilen Holzbretter sind fest zusammengebunden.}
{54500}{}{Holzbretter}
{54501}{}{Diese stabilen Holzbretter sind fest zusammengebunden.}
{54600}{}{Roulettetisch}
{54601}{}{Das ist ein Spieltisch.}
{54700}{}{Roulettetisch}
{54701}{}{Das ist ein Spieltisch.}
{54800}{}{Roulettetisch}
{54801}{}{Das ist ein Spieltisch.}
{54900}{}{Roulettetisch}
{54901}{}{Das ist ein Spieltisch.}
{55000}{}{Roulettetisch}
{55001}{}{Das ist ein Spieltisch.}
{55100}{}{Fass}
{55101}{}{Auf die Seite dieses leeren Metallfasses ist in leuchtend gelber Farbe das nukleare Trefoil-Symbol gemalt.}
{55200}{}{Fass}
{55201}{}{Dieses Fass enthält eine grün leuchtende Flüssigkeit. Das nukleare Trefoil-Symbol gibt einen Hinweis darauf, worum es sich handeln könnte.}
{55300}{}{Computer}
{55301}{}{Ein sehr modern aussehender Computer.}
{55400}{}{Computer}
{55401}{}{Ein sehr modern aussehender Computer.}
{55500}{}{Suspensionstank}
{55501}{}{Irgendeine medizinische oder experimentelle Vorrichtung. Sie sieht aus, als könnte sie einen Menschen oder einen größeren Körper aufnehmen.}
{55600}{}{Defekter Suspensionstank}
{55601}{}{Ein defektes Gerät. Es ist nicht mehr zu reparieren.}
{55700}{}{Ausrüstung}
{55701}{}{Wichtige Ausrüstung voller Elektronik.}
{55800}{}{Trägerplattform}
{55801}{}{Diese Plattform trägt die Ausrüstung für die Sonderkommunikation.}
{55900}{}{Nicht benutzen}
{56000}{}{Nicht benutzen}
{56100}{}{Bett}
{56101}{}{Ein Etagenbett im Militärstil. Sieht sehr unbequem aus. Außerdem sieht es so aus, als könnte man von diesen Laken eine Münze abprallen lassen.}
{56200}{}{Bett}
{56201}{}{Ein Etagenbett im Militärstil. Sieht sehr unbequem aus. Außerdem sieht es so aus, als könnte man von diesen Laken eine Münze abprallen lassen.}
{56300}{}{Bett}
{56301}{}{Ein Etagenbett im Militärstil. Sieht sehr unbequem aus. Außerdem sieht es so aus, als könnte man von diesen Laken eine Münze abprallen lassen.}
{56400}{}{Kabel}
{56401}{}{Sieht aus wie eine Art serielles Kabel.}
{56500}{}{Kabel}
{56501}{}{Sieht aus wie eine Art serielles Kabel.}
{56600}{}{Schild}
{56601}{}{Auf dem Schild steht BAR. Das dürfte selbsterklärend sein.}
{56700}{}{Schatten}
{56800}{}{Flagge}
{56801}{}{Die Flagge trägt das Emblem einer Postkutsche: vier Wagenräder an den Ecken und in der Mitte einen Stierkopf mit Cowboyhut und Halstuch.}
{56900}{}{Regale}
{56901}{}{Du siehst einige Metallregale.}
{57000}{}{Regale}
{57001}{}{Du siehst einige Metallregale.}
{57100}{}{Regale}
{57101}{}{Du siehst einige Metallregale.}
{57200}{}{Regale}
{57201}{}{Du siehst einige Metallregale.}
{57300}{}{Busch}
{57400}{}{Busch}
{57500}{}{Busch}
{57600}{}{Felsen}
{57601}{}{Ein großer Haufen Steine. Dem Aussehen nach stammen sie aus der Gegend.}
{57700}{}{Felsen}
{57701}{}{Kleiner Steinhaufen.}
{57800}{}{Felsen}
{57801}{}{Kleiner Steinhaufen.}
{57900}{}{Felsen}
{57901}{}{Großer Steinhaufen.}
{58000}{}{Klippe}
{58100}{}{Tür}
{58101}{}{Eine Tür, die in einer Zelle nicht fehl am Platz wäre.}
{58200}{}{Brückenpfeiler}
{58300}{}{Leiter}
{58301}{}{Diese Leiter führt hinunter in die Dunkelheit.}
{58400}{}{Leiter}
{58401}{}{Diese Leiter führt hinunter in die Dunkelheit.}
{58500}{}{Maschinerie}
{58501}{}{Sieht aus wie irgendein Fertigungsdingens.}
{58600}{}{Maschinerie}
{58601}{}{Sieht aus wie irgendein Fertigungsdingens.}
{58700}{}{Maschinerie}
{58701}{}{Sieht aus wie irgendein Fertigungsdingens.}
{58800}{}{Maschinerie}
{58801}{}{Sieht aus wie irgendein Fertigungsdingens.}
{58900}{}{Maschinerie}
{58901}{}{Sieht aus wie irgendein Fertigungsdingens.}
{59000}{}{Teil}
{59001}{}{Sieht aus wie irgendein Fertigungsdingens.}
{59100}{}{Tisch}
{59101}{}{Dieser Metalltisch scheint in gutem Zustand zu sein. In der Mitte befindet sich ein Abfluss.}
{59200}{}{Tisch}
{59201}{}{Dieser Metalltisch scheint in gutem Zustand zu sein. In der Mitte befindet sich ein Abfluss.}
{59300}{}{Tisch}
{59301}{}{Der Metalltisch ist mit einer Art Biomasse bedeckt.}
{59400}{}{Tisch}
{59401}{}{Der Metalltisch ist mit einer Art Biomasse bedeckt.}
{59500}{}{Tisch}
{59501}{}{Der Metalltisch ist mit einer Art Biomasse bedeckt.}
{59600}{}{Anschlagtafel}
{59601}{}{An der Tafel sind Stellenangebote angeheftet. Sie sieht aus, als würde sie oft benutzt.}
{59700}{}{Wachhäuschen}
{59701}{}{Dieses Wachhäuschen ist über siebzig Jahre alt, aber noch immer in ausgezeichnetem Zustand.}
{59800}{}{Schild}
{59801}{}{Auf diesem Schild steht: Gemischtwarenladen.}
{59900}{}{Schild}
{59901}{}{Auf diesem Schild steht: Gemischtwarenladen.}
{60000}{}{Schild}
{60001}{}{Auf diesem Schild steht: Markt}
{60100}{}{Schleimpfütze}
{60101}{}{Es sieht sehr ungesund aus. Du solltest vielleicht eine gepanzerte Badehose tragen, bevor du ein Bad nimmst.}
{60200}{}{Schleimpfütze}
{60201}{}{Es sieht sehr ungesund aus. Du solltest vielleicht eine gepanzerte Badehose tragen, bevor du ein Bad nimmst.}
{60300}{}{Schleimpfütze}
{60301}{}{Es sieht sehr ungesund aus. Du solltest vielleicht eine gepanzerte Badehose tragen, bevor du ein Bad nimmst.}
{60400}{}{Tisch}
{60401}{}{Ein hübscher Metalltisch.}
{60500}{}{Tisch}
{60501}{}{Ein hübscher Metalltisch.}
{60600}{}{Tisch}
{60601}{}{Ein hübscher Metalltisch.}
{60700}{}{Tisch}
{60701}{}{Ein hübscher Metalltisch.}
{60800}{}{Tisch}
{60801}{}{Dieser Metalltisch wurde nicht gut behandelt. Er ist großflächig verrostet.}
{60900}{}{Tisch}
{60901}{}{Ein gut aussehender Metalltisch, abgesehen vom Rost.}
{61000}{}{Tisch}
{61001}{}{Ein gut aussehender Metalltisch, abgesehen vom Rost.}
{61100}{}{Tisch}
{61101}{}{Ein gut aussehender Metalltisch, abgesehen vom Rost.}
{61200}{}{Feuerstelle}
{61201}{}{Das Feuer brennt.}
{61300}{}{Spiegel}
{61301}{}{Du betrachtest dich eine Weile.}
{61400}{}{Spiegel}
{61401}{}{Du starrst eine Weile auf dein Spiegelbild.}
{61500}{}{Waschbecken}
{61501}{}{Ein voll funktionsfähiges Waschbecken. Und noch dazu schön sauber.}
{61600}{}{Toilette}
{61601}{}{Diese Toilette ist sehr sauber. Sie funktioniert auch.}
{61700}{}{Urinal}
{61701}{}{Dieses Urinal ist funktionsfähig.}
{61800}{}{Zugtür}
{61900}{}{Waschbecken}
{61901}{}{Dieses Waschbecken ist in perfektem Zustand.}
{62000}{}{Urinal}
{62001}{}{Dieses Urinal ist in perfektem Zustand.}
{62100}{}{Dusche}
{62101}{}{Eine Dusche im Militärstil. Nichts für schamhafte Leute.}
{62200}{}{Dusche}
{62201}{}{Eine Dusche im Militärstil. Nichts für schamhafte Leute.}
{62300}{}{Dusche}
{62301}{}{Eine Dusche im Militärstil. Nichts für schamhafte Leute.}
{62400}{}{Dusche}
{62401}{}{Eine Dusche im Militärstil. Nichts für schamhafte Leute.}
{62500}{}{Dusche}
{62501}{}{Eine Dusche im Militärstil. Nichts für schamhafte Leute.}
{62600}{}{Dusche}
{62601}{}{Eine Dusche im Militärstil. Nichts für schamhafte Leute.}
{62700}{}{Bett}
{62701}{}{Ein sehr bequem aussehendes Bett.}
{62800}{}{Bett}
{62801}{}{Ein sehr bequem aussehendes Bett.}
{62900}{}{Bett}
{62901}{}{Ein verstärktes Etagenbett.}
{63000}{}{Bett}
{63001}{}{Ein verstärktes Etagenbett.}
{63100}{}{Bett}
{63101}{}{Ein verstärktes Etagenbett.}
{63200}{}{Nasse Kleidung}
{63201}{}{Jemand hat seine Kleidung zum Trocknen aufgehängt und unbeaufsichtigt gelassen.}
{63300}{}{Wassersammler}
{63301}{}{Dieser riesige Tank speichert Wasser.}
{63400}{}{Ständer}
{63401}{}{Ein Ständer mit Fotos einiger Leute, die dir bekannt vorkommen. Darauf steht: "Unsere Helden"}
{63500}{}{Ständer}
{63501}{}{Ein Ständer mit dem Gruppenfoto der Studiomitarbeiter.}
{63600}{}{Kühlbox}
{63601}{}{Eine ganz gewöhnliche Kühlbox.}
{63700}{}{Computer}
{63701}{}{Ein großer Computer.}
{63800}{}{Computer}
{63801}{}{Ein großer Computer.}
{63900}{}{Computer}
{63901}{}{Ein großer Computer.}
{64000}{}{Terminal}
{64001}{}{Das Terminal eines großen Computers.}
{64100}{}{Tote Person}
{64101}{}{Es sieht aus, als wäre diese Person sehr qualvoll gestorben.}
{64200}{}{Tote Person}
{64201}{}{Es sieht aus, als wäre diese Person sehr qualvoll gestorben.}
{64300}{}{Tote Person}
{64301}{}{Es sieht aus, als wäre diese Person sehr qualvoll gestorben.}
{64400}{}{Tote Person}
{64401}{}{Es sieht aus, als wäre diese Person sehr qualvoll gestorben.}
{64500}{}{Tür}
{64501}{}{Diese Gittertür eignet sich gut als Tür für eine Gefängniszelle.}
{64600}{}{Terminal}
{64700}{}{Terminal}
{64800}{}{Gabelstapler}
{64801}{}{Der Gabelstapler ist nicht funktionsfähig.}
{64900}{}{Gabelstapler}
{64901}{}{Der Gabelstapler ist nicht funktionsfähig.}
{65000}{}{Autodoc}
{65001}{}{Dieser Auto-Doc ist dafür ausgelegt, Krankheiten zu heilen und verschiedene Medikamente zu verabreichen. Derzeit außer Betrieb.}
{65100}{}{Medizinischer Tisch}
{65101}{}{Dieser Tisch ist stark verrostet. Der Abfluss in der Tischmitte ist verstopft.}
{65200}{}{Medizinischer Tisch}
{65201}{}{Dieser Tisch ist stark verrostet.}
{65300}{}{Tor}
{65301}{}{Dieses Tor hat eine Stange, die sich heben und senken lässt.}
{65400}{}{Rohr}
{65500}{}{Rohr}
{65600}{}{Stromgenerator}
{65601}{}{Ein Wattz-ElectroBox-Stromgenerator. Vor dem Krieg ein recht üblicher Notstromgenerator.}
{65700}{}{Tisch mit Teilen}
{65701}{}{Ein gewöhnlicher Tisch, der als Werkbank für Waffenreparaturen dient.}
{65800}{}{Express}
{65801}{}{Improvisiertes Transportmittel, aus Bus- und Autoteilen zusammengesetzt. Es wurde absichtlich außer Betrieb gesetzt.}
{65900}{}{Tisch}
{65901}{}{Ein hochwertiger Tisch. Handgefertigt, aber er sieht viel besser aus als jeder Tisch, den du bisher gesehen hast.}
{66000}{}{Tisch}
{66001}{}{Ein hochwertiger Tisch. Handgefertigt, aber er sieht viel besser aus als jeder Tisch, den du bisher gesehen hast.}
{66100}{}{Tisch}
{66101}{}{Ein hochwertiger Tisch. Handgefertigt, aber er sieht viel besser aus als jeder Tisch, den du bisher gesehen hast.}
{66200}{}{Stuhl}
{66201}{}{Ein sehr schön aussehender Stuhl.}
{66300}{}{Stuhl}
{66301}{}{Ein sehr schön aussehender Stuhl.}
{66400}{}{Stuhl}
{66401}{}{Ein sehr schön aussehender Stuhl.}
{66500}{}{Stuhl}
{66501}{}{Ein sehr schön aussehender Stuhl.}
{66600}{}{Stuhl}
{66601}{}{Ein sehr schön aussehender Stuhl.}
{66700}{}{Stuhl}
{66701}{}{Ein sehr schön aussehender Stuhl.}
{66800}{}{Stuhl}
{66801}{}{Ein sehr schön aussehender Stuhl.}
{66900}{}{Stuhl}
{66901}{}{Ein sehr schön aussehender Stuhl.}
{67000}{}{Stuhl}
{67001}{}{Ein sehr schön aussehender Stuhl.}
{67100}{}{Stuhl}
{67101}{}{Ein sehr schön aussehender Stuhl.}
{67200}{}{Stuhl}
{67201}{}{Ein sehr schön aussehender Stuhl.}
{67300}{}{Stuhl}
{67301}{}{Ein sehr schön aussehender Stuhl.}
{67400}{}{Stuhl}
{67401}{}{Ein sehr schön aussehender Stuhl.}
{67500}{}{Stuhl}
{67501}{}{Ein sehr schön aussehender Stuhl.}
{67600}{}{Stuhl}
{67601}{}{Ein sehr schön aussehender Stuhl.}
{67700}{}{Stuhl}
{67701}{}{Ein sehr schön aussehender Stuhl.}
{67800}{}{Bett}
{67801}{}{Ein sehr schön aussehendes Bett.}
{67900}{}{Bett}
{67901}{}{Ein sehr schön aussehendes Bett.}
{68000}{}{Bett}
{68001}{}{Ein sehr schön aussehendes Bett.}
{68100}{}{Bett}
{68101}{}{Ein sehr schön aussehendes Bett.}
{68200}{}{Herd}
{68201}{}{Ein funktionstüchtiger Holzofen.}
{68300}{}{Herd}
{68301}{}{Ein funktionstüchtiger Holzofen.}
{68400}{}{Herd}
{68401}{}{Ein funktionstüchtiger Holzofen.}
{68500}{}{Herd}
{68501}{}{Ein funktionstüchtiger Holzofen.}
{68600}{}{Zerbrochener Pfosten}
{68700}{}{Brückenpfeiler}
{68800}{}{Stufe des Raketenträgers}
{68801}{}{Du siehst den verkohlten Körper eines Apparats.}
{68900}{}{Bohnensack}
{68901}{}{Ein Haufen Dosen und Bolzen.}
{69000}{}{Toilette}
{69001}{}{Ein primitiver, aber effektiver Abort. Einige Blätter wurden in das Loch geworfen, um den Geruch einzudämmen.}
{69100}{}{Berg}
{69101}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69200}{}{Berg}
{69201}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69300}{}{Berg}
{69301}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69400}{}{Berg}
{69401}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69500}{}{Berg}
{69501}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69600}{}{Berg}
{69601}{}{Diese Bergwände sehen sehr unzugänglich aus.}
{69700}{}{Bus}
{69701}{}{Du siehst einen gewöhnlichen Bus. Er wird niemals Kinder zur Schule bringen können.}
{69800}{}{Bus}
{69801}{}{Du siehst einen schwer verbrannten Bus. Genauer gesagt: ein nutzloses Stück Rost.}
{69900}{}{Dein Lager für Nuka-Cola}
{69901}{}{Du siehst Kisten mit deinem persönlichen Lager für Nuka-Cola.}
{70000}{}{Einsturz}
{70001}{}{Du siehst die eingestürzten Wände und die Decke, begraben unter einer Schicht aus Sand und Beton.}
{70100}{}{Werbeschild}
{70101}{}{Nur ein altes Werbeschild an einem kräftigen Pfosten. So stark verrostet, dass man nichts mehr darauf lesen kann.}
{70200}{}{Wand}
{70201}{}{Nur eine baufällige Mauer. Das ist alles.}
{70300}{}{Klippe}
{70301}{}{Du kannst diese Klippe nicht erklimmen.}
{70400}{}{Stufe des Raketenträgers}
{70401}{}{Du siehst den verkohlten Körper eines Apparats.}
{70500}{}{Stufe des Raketenträgers}
{70501}{}{Du siehst den verkohlten Körper eines Apparats.}
{70600}{}{Schatten}
{70601}{}{Das ist ein Schatten.}
{70700}{}{Schild}
{70701}{}{Das Schild verlangt eine geringere Geschwindigkeit – höchstens 20 Meilen pro Stunde. Du brauchst es nicht.}
{70800}{}{Express}
{70801}{}{Rekonstruierter und umgebauter Vorkriegsbus.}
{70900}{}{Straßenschild}
{71000}{}{Straßenschild}
{71100}{}{Straßenschild}
{71200}{}{Straßenschild}
{71300}{}{Express}
{71301}{}{Rekonstruierter und restaurierter Vorkriegsbus.}
{71400}{}{Klippe}
{71401}{}{Du kannst diese Klippe nicht erklimmen.}
{71500}{}{Klippe}
{71501}{}{Du kannst diese Klippe nicht erklimmen.}
{71600}{}{Klippe}
{71601}{}{Du kannst diese Klippe nicht erklimmen.}
{71700}{}{Klippe}
{71701}{}{Du kannst diese Klippe nicht erklimmen.}
{71800}{}{Anlage}
{71801}{}{Du siehst einen Teil des Kraftwerks.}
{71900}{}{Anlage}
{71901}{}{Du siehst einen Teil des Kraftwerks.}
{72000}{}{Werbung}
{72001}{}{Du siehst eine „schreiende“ Warnung, dass du dich auf Bundeseigentum befindest. Fotografieren ist verboten, und überhaupt solltest du besser so schnell und so weit wie möglich von hier verschwinden.}
{72100}{}{Schleim}
{72101}{}{Du siehst eine seltsame, giftige biologische Masse.}
{72200}{}{Schleim}
{72201}{}{Du siehst eine seltsame, giftige biologische Masse.}
{72300}{}{Schleim}
{72301}{}{Du siehst eine seltsame, giftige biologische Masse.}
{72400}{}{Schatten}
{72500}{}{Klippe}
{72600}{}{Klippe}
{72700}{}{Klippe}
{72800}{}{Klippe}
{72801}{}{Du siehst eine seltsame, giftige biologische Masse.}
{72900}{}{Schleim}
{72901}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73000}{}{Schleim}
{73001}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73100}{}{Schleim}
{73101}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73200}{}{Schleim}
{73201}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73300}{}{Schleim}
{73301}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73400}{}{Schleim}
{73401}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73500}{}{Schleim}
{73501}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73600}{}{Schleim}
{73601}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73700}{}{Schleim}
{73701}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73800}{}{Schleim}
{73801}{}{Du siehst eine seltsame, giftige biologische Masse.}
{73900}{}{Schleim}
{73901}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74000}{}{Schleim}
{74001}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74100}{}{Schleim}
{74101}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74200}{}{Schleim}
{74201}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74300}{}{Schleim}
{74301}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74400}{}{Schleim}
{74401}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74500}{}{Schleim}
{74501}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74600}{}{Schleim}
{74601}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74700}{}{Schleim}
{74701}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74800}{}{Schleim}
{74801}{}{Du siehst eine seltsame, giftige biologische Masse.}
{74900}{}{Klippe}
{74901}{}{Du kannst diese Klippe nicht erklimmen.}
{75000}{}{Eingang}
{75001}{}{Steige auf die obere Terrasse.}
{75100}{}{Eingang}
{75101}{}{Steige auf die obere Terrasse.}
{75200}{}{Klippe}
{75201}{}{Du kannst diese Klippe nicht erklimmen.}
{75300}{}{Eingang}
{75301}{}{Steige auf die obere Terrasse.}
{75400}{}{Klippe}
{75401}{}{Du kannst diese Klippe nicht erklimmen.}
{75500}{}{Klippe}
{75501}{}{Du kannst diese Klippe nicht erklimmen.}
{75600}{}{Klippe}
{75601}{}{Du kannst diese Klippe nicht erklimmen.}
{75700}{}{Klippe}
{75701}{}{Du kannst diese Klippe nicht erklimmen.}
{75800}{}{Klippe}
{75801}{}{Du kannst diese Klippe nicht erklimmen.}
{75900}{}{Klippe}
{75901}{}{Du kannst diese Klippe nicht erklimmen.}
{76000}{}{Klippe}
{76001}{}{Du kannst diese Klippe nicht erklimmen.}
{76100}{}{Klippe}
{76101}{}{Du kannst diese Klippe nicht erklimmen.}
{76200}{}{Schild}
{76201}{}{Das Schild schreibt eine niedrigere Geschwindigkeit vor – höchstens 20 Meilen pro Stunde. Das brauchst du nicht.}
{76300}{}{Werbung}
{76301}{}{Du siehst eine „schreiende“ Warnung, dass du dich auf Bundeseigentum befindest. Fotografieren ist verboten, und überhaupt solltest du besser so schnell und so weit wie möglich von hier verschwinden.}
{76400}{}{Radar}
{76401}{}{Ein Radar zum Senden und Empfangen von Nachrichten über große Entfernungen.}
{76500}{}{Gerät}
{76501}{}{Ein bestimmtes Gerät, mit einer Plane abgedeckt und für den Transport vorbereitet.}
{76600}{}{Gerät}
{76601}{}{Ein bestimmtes Gerät, mit einer Plane abgedeckt und für den Transport vorbereitet.}
{76700}{}{Konsole}
{76800}{}{Atombombe}
{76900}{}{Sockel}
{76901}{}{Dieser Sockel trägt die darauf befindliche Atombombe.}
{77000}{}{Schlucht}
{77100}{}{Schatten}
{77200}{}{Stuhl}
{77201}{}{An diesem Stuhl ist nichts Ungewöhnliches.}
{77300}{}{Stuhl}
{77301}{}{An diesem Stuhl ist nichts Ungewöhnliches.}
{77400}{}{Stuhl}
{77401}{}{An diesem Stuhl ist nichts Ungewöhnliches.}
{77500}{}{Stuhl}
{77501}{}{An diesem Stuhl ist nichts Ungewöhnliches.}
{77600}{}{Stuhl}
{77601}{}{An diesem Stuhl ist nichts Ungewöhnliches.}
{77700}{}{Stuhl}
{77701}{}{An diesem Stuhl ist nichts Ungewöhnliches.}
{77800}{}{Stuhl}
{77801}{}{An diesem Stuhl ist nichts Ungewöhnliches.}
{77900}{}{Stuhl}
{77901}{}{An diesem Stuhl ist nichts Ungewöhnliches.}
{78000}{}{Pfeiler}
{78001}{}{Ein Stützpfeiler.}
{78100}{}{Pfeiler}
{78101}{}{Ein Stützpfeiler.}
{78200}{}{Pfeiler}
{78201}{}{Ein Stützpfeiler.}
{78300}{}{Pfeiler}
{78301}{}{Ein Stützpfeiler.}
{78400}{}{Wäschetrockner}
{78401}{}{Ein gewöhnlicher Wäschetrockner.}
{78500}{}{Bett}
{78501}{}{Dieses Bett ist in schlechtem Zustand.}
{78600}{}{Bett}
{78601}{}{Dieses Bett ist in schlechtem Zustand.}
{78700}{}{Bett}
{78701}{}{Dieses Bett ist in ziemlich schlechtem Zustand.}
{78800}{}{Monitore}
{78801}{}{Diese Monitore sind kaputt und funktionieren nicht.}
{78900}{}{Monitore}
{78901}{}{Diese Monitore sind kaputt und funktionieren nicht.}
{79000}{}{Monitore}
{79001}{}{Diese Monitore sind kaputt und funktionieren nicht.}
{79100}{}{Monitore}
{79101}{}{Diese Monitore sind kaputt und funktionieren nicht.}
{79200}{}{Lüftungsschacht}
{79201}{}{Aus diesem Lüftungsschacht kommt nur sehr wenig Frischluft.}
{79300}{}{Lüftungsschacht}
{79301}{}{Aus diesem Lüftungsschacht kommt fast keine Frischluft.}
{79400}{}{Lüftungsschacht}
{79401}{}{Aus diesem Lüftungsschacht kommt keine Frischluft.}
{79500}{}{Lüftungsschacht}
{79501}{}{Aus diesem Lüftungsschacht kommt nur ein winziges bisschen Frischluft.}
{79600}{}{Tisch}
{79601}{}{An diesem Tisch ist nichts Ungewöhnliches, außer dass er fast völlig zerstört ist.}
{79700}{}{Tisch}
{79701}{}{Dieser Tisch wurde schwer beschädigt.}
{79800}{}{Tisch}
{79801}{}{Dieser Tisch ist in sehr schlechtem Zustand.}
{79900}{}{Tisch}
{79901}{}{Es gibt keinen Grund, diesen Tisch zu durchsuchen.}
{80000}{}{Bildschirmeinheit}
{80001}{}{Dieses Monitorsystem funktioniert derzeit nicht.}
{80100}{}{Bildschirmeinheit}
{80101}{}{Dieses Monitorsystem funktioniert derzeit nicht.}
{80200}{}{Monitor}
{80201}{}{Der Bildschirm des Monitors ist gesprungen und zerstört.}
{80300}{}{Monitor}
{80301}{}{Dieser Monitor ist mit einem kaputten Bildschirm wertlos.}
{80400}{}{Computer}
{80401}{}{Dieser Computer ist kaputt.}
{80500}{}{Computer}
{80501}{}{Dieser Computer ist kaputt.}
{80600}{}{Computer}
{80601}{}{Dieser Computer ist kaputt.}
{80700}{}{Stuhl}
{80701}{}{Ein Stuhl mit beschädigtem Bezug.}
{80800}{}{Stuhl}
{80801}{}{Ein Stuhl mit beschädigtem Bezug.}
{80900}{}{Stuhl}
{80901}{}{Ein Stuhl mit beschädigtem Bezug.}
{81000}{}{Stuhl}
{81001}{}{Ein Stuhl mit beschädigtem Bezug.}
{81100}{}{Lüftungsschacht}
{81101}{}{Dieser Lüftungsschacht ist irreparabel beschädigt.}
{81200}{}{Lüftungsschacht}
{81201}{}{Dieser Lüftungsschacht ist stark beschädigt und kann nicht repariert werden.}
{81300}{}{Lüftungsschacht}
{81301}{}{Dieser Lüftungsschacht funktioniert überhaupt nicht.}
{81400}{}{Computer}
{81401}{}{Dieser Computer sieht aus, als würde er kaum noch funktionieren.}
{81500}{}{Computer}
{81501}{}{Dieser Computer sieht aus, als würde er kaum noch funktionieren.}
{81600}{}{Monitor}
{81601}{}{Der Monitor funktioniert kaum noch.}
{81700}{}{Monitor}
{81701}{}{Der Monitor funktioniert kaum noch.}
{81800}{}{Computer}
{81801}{}{Der Computer funktioniert nicht.}
{81900}{}{Computer}
{81901}{}{Der Computer funktioniert nicht.}
{82000}{}{Monitor}
{82001}{}{Der Monitor funktioniert nicht.}
{82100}{}{Monitor}
{82101}{}{Der Monitor funktioniert nicht.}
{82200}{}{Türöffnung}
{82201}{}{Das sieht nach einem sehr schönen Türrahmen aus. Er hält die Tür ausgezeichnet.}
{82300}{}{Monitore}
{82301}{}{Die Monitore sind in gutem Zustand.}
{82400}{}{Monitore}
{82401}{}{Die Monitore sind in gutem Zustand.}
{82500}{}{Wand}
{82600}{}{Gepanzerte Tür}
{82601}{}{Eine sehr robuste Tür. Hält sogar nach der Explosion noch stand.}
{82700}{}{Leicht}
{82701}{}{Eine Sicherheitsleuchte.}
{82800}{}{Leicht}
{82801}{}{Eine Sicherheitsleuchte.}
{82900}{}{Seil}
{83000}{}{Roboter-Ladestation}
{83001}{}{Dies ist eine Ladestation für Roboter. Wenn sie nicht im Einsatz sind, docken Roboter hier an, fahren herunter und laden sich auf.}
{83100}{}{Roboter-Ladestation}
{83101}{}{Dies ist eine Ladestation für Roboter. Wenn sie nicht im Einsatz sind, docken Roboter hier an, fahren herunter und laden sich auf.}
{83200}{}{Roboter-Ladestation}
{83201}{}{Dies ist eine Ladestation für Roboter. Wenn sie nicht im Einsatz sind, docken Roboter hier an, fahren herunter und laden sich auf.}
{83300}{}{Roboter-Ladestation}
{83301}{}{Dies ist eine Ladestation für Roboter. Wenn sie nicht im Einsatz sind, docken Roboter hier an, fahren herunter und laden sich auf.}
{83400}{}{Roboter-Ladestation}
{83401}{}{Dies ist eine Ladestation für Roboter. Wenn sie nicht im Einsatz sind, docken Roboter hier an, fahren herunter und laden sich auf.}
{83500}{}{Maschine}
{83501}{}{Diese Maschine hat etwas mit den Roboter-Wartungsbuchten zu tun. Sie sieht nicht besonders interessant aus.}
{83600}{}{Maschine}
{83601}{}{Diese Maschine hat etwas mit den Roboter-Wartungsbuchten zu tun. Sie sieht nicht sehr interessant aus.}
{83700}{}{Streifen}
{83800}{}{Streifen}
{83900}{}{Streifen}
{84000}{}{Streifen}
{84100}{}{Streifen}
{84200}{}{Streifen}
{84300}{}{Streifen}
{84400}{}{Streifen}
{84500}{}{Streifen}
{84600}{}{Streifen}
{84700}{}{Streifen}
{84800}{}{Tür}
{84801}{}{Eine ganz gewöhnliche Holztür.}
{84900}{}{Tür}
{84901}{}{Eine ganz gewöhnliche Holztür.}
{85000}{}{Tür}
{85001}{}{Eine ganz gewöhnliche Holztür.}
{85100}{}{Plakat}
{85101}{}{Ein Vorkriegsplakat, das zu einem Blueskonzert im Café „Hard Rock“ einlädt.}
{85200}{}{Plakat}
{85201}{}{Ein Vorkriegsplakat, das zu den Fußball-Olympischen Spielen im Stadion von Provo einlädt.}
{85300}{}{Medizinischer Tisch}
{85301}{}{Das sieht aus wie ein medizinischer Untersuchungstisch.}
{85400}{}{Seil}
{85500}{}{Kabel}
{85501}{}{Blank liegende Drähte. Vorsicht!}
{85600}{}{Graffiti}
{85700}{}{Graffiti}
{85800}{}{Graffiti}
{85900}{}{Graffiti}
{86000}{}{Graffiti}
{86100}{}{Graffiti}
{86200}{}{Graffiti}
{86300}{}{Graffiti}
{86400}{}{Graffiti}
{86500}{}{Graffiti}
{86600}{}{Graffiti}
{86700}{}{Graffiti}
{86800}{}{Graffiti}
{86900}{}{Schild}
{86901}{}{Hier steht: WAFFEN. Dort werden vielleicht Waffen verkauft.}
{87000}{}{Schild}
{87001}{}{Auf dem Schild steht: Polizei.}
{87100}{}{Hochbrücke}
{87200}{}{Plakat}
{87300}{}{Plakat}
{87301}{}{Auf diesem verblassten Plakat ist eine verlassene Rennstrecke mit einem Bergrücken im Hintergrund zu sehen. Dazu die Aufschrift: „Nevada ist ein Land der Unterhaltung“.}
{87400}{}{Stella}
{87500}{}{Schild}
{87501}{}{Das ist ein Schild für den Ring, der sich im Keller des Gebäudes befindet.}
{87600}{}{Schild}
{87601}{}{Die Aufschrift auf diesem unansehnlichen Schild lautet: „Die Stadt der Karawanen“.}
{87700}{}{Schild}
{87701}{}{Das ist das Schild der Sklavenhändlergilde.}
{87800}{}{Eierschale}
{87801}{}{Stücke einer zerbrochenen Eierschale.}
{87900}{}{Eierschale}
{87901}{}{Stücke einer zerbrochenen Eierschale.}
{88000}{}{Eierschale}
{88001}{}{Stücke einer zerbrochenen Eierschale.}
{88100}{}{Eierschale}
{88101}{}{Stücke einer zerbrochenen Eierschale.}
{88200}{}{Eierschale}
{88201}{}{Stücke einer zerbrochenen Eierschale.}
{88300}{}{Eierschale}
{88301}{}{Stücke einer zerbrochenen Eierschale.}
{88400}{}{Eierschale}
{88401}{}{Stücke einer zerbrochenen Eierschale.}
{88500}{}{Eierschale}
{88501}{}{Stücke einer zerbrochenen Eierschale.}
{88600}{}{Laternenmast}
{88601}{}{Ein Laternenpfahl. Er scheint noch gut zu funktionieren.}
{88700}{}{Schild}
{88701}{}{Auf dem Schild steht: Motel.}
{88800}{}{Pilze}
{88801}{}{Dieser Tischpflanzer wurde mit Dung gefuellt, und darin wachsen munter Pilze.}
{88900}{}{Pilze}
{88901}{}{Dieser Tischpflanzer wurde mit Dung gefuellt, und darin wachsen munter Pilze.}
{89000}{}{Skelett}
{89100}{}{Fass}
{89200}{}{Fass}
{89300}{}{Schild}
{89301}{}{Eine Werbung für Rasierklingen der Marke Blades.}
{89400}{}{Dusche}
{89401}{}{Eine ziemlich gewöhnliche Duschkabine.}
{89500}{}{Dusche}
{89501}{}{Eine ziemlich gewöhnliche Duschkabine.}
{89600}{}{Dach}
{89700}{}{Schatten}
{89800}{}{Schatten}
{89900}{}{Schatten}
{90000}{}{Stella}
{90100}{}{Aufzugsschacht}
{90101}{}{Vom Schacht hängt ein Seil herab.}
{90200}{}{Aufzugsschacht}
{90201}{}{Vom Rand des Schachts hängt ein Seil herab.}
{90300}{}{Krankenbett}
{90301}{}{Dieses Bett hat ein eingebautes Display zur Überwachung des Zustands der Patienten.}
{90400}{}{Wasserpumpe}
{90401}{}{Eine Maschine, die Wasser von unten nach oben pumpt.}
{90500}{}{Aufseher}
{90501}{}{Aufseher. Du wirst deinen Augen vielleicht nicht trauen, aber er ist es.}
{90600}{}{Powerrüstungsteile}
{90601}{}{Das sind Teile einer Powerrüstung.}
{90700}{}{Leicht}
{90701}{}{Diese Sicherheitsleuchte pulsiert gerade in grellem Rot.}
{90800}{}{Leicht}
{90801}{}{Diese Sicherheitsleuchte pulsiert gerade in grellem Rot.}
{90900}{}{Symbol}
{91000}{}{Symbol}
{91100}{}{Symbol}
{91200}{}{Symbol}
{91300}{}{Symbol}
{91400}{}{Symbol}
{91500}{}{Seil}
{91600}{}{Seil}
{91700}{}{Seil}
{91800}{}{Seil}
{91900}{}{Seil}
{92000}{}{Seil}
{92100}{}{Seil}
{92200}{}{Seil}
{92300}{}{Berg}
{92400}{}{Berg}
{92500}{}{Berg}
{92600}{}{Berg}
{92700}{}{Panorama}
{92800}{}{Terminal}
{92801}{}{Terminal zur Fernsteuerung eines Krans im Hangar.}
{92900}{}{Berg}
{93000}{}{Berg}
{93100}{}{Riesiger Buchstabe}
{93101}{}{Dieser Buchstabe ist vom Turm gefallen. Zuvor war er Teil des Schildes „Artesian Water“.}
{93200}{}{Riesiger Buchstabe}
{93201}{}{Woher kam er?}
{93300}{}{Riesiger Buchstabe}
{93301}{}{Woher kam er?}
{93400}{}{Skelette}
{93401}{}{Offenbar fand der Tod diese Menschen schlafend und ließ sie nicht einmal aufwachen.}
{93500}{}{Fackel}
{93501}{}{Eine brennende Fackel in einer Wandhalterung.}
{93600}{}{Fackel}
{93601}{}{Eine brennende Fackel in einer Wandhalterung.}
{93700}{}{Tank}
{93701}{}{Ein riesiger Lagerbehälter für Schüttgut.}
{93800}{}{Steinmonument}
{93900}{}{Steinmonument}
{94000}{}{Schädelpfahl}
{94001}{}{Ein Pfahl mit daran befestigten menschlichen Schädeln.}
{94100}{}{Schädelpfahl}
{94101}{}{Ein Pfahl mit daran befestigten menschlichen Schädeln.}
{94200}{}{Schädelpfahl}
{94201}{}{Ein Pfahl mit daran befestigten menschlichen Schädeln.}
{94300}{}{Pflanze}
{94400}{}{Pflanze}
{94500}{}{Baum}
{94600}{}{Baum}
{94700}{}{Baum}
{94800}{}{Bett}
{94900}{}{Bett}
{95000}{}{Generator}
{95001}{}{Selbstgebaute Stromanlage mit Automotor.}
{95100}{}{Angehobene Steinplatte}
{95101}{}{Eine angehobene Steinplatte.}
{95200}{}{Abgesenkte Steinplatte}
{95201}{}{Eine abgesenkte Steinplatte.}
{95300}{}{Ausgelöste Steinplatte}
{95301}{}{Eine ausgelöste Steinplatte.}
{95400}{}{Tür}
{95500}{}{Elektrischer Verteilerkasten}
{95501}{}{Nur ein Transformator im Stromkreis. Nichts Interessantes.}
{95600}{}{Tür}
{95700}{}{Tür}
{95800}{}{Tür}
{95900}{}{Tür}
{96000}{}{Tür}
{96100}{}{Tür}
{96200}{}{Tür}
{96300}{}{Mais}
{96400}{}{Mais}
{96500}{}{Mais}
{96600}{}{Mais}
{96700}{}{Mais}
{96800}{}{Mais}
{96900}{}{Holzstütze}
{97000}{}{Holzstütze}
{97100}{}{Holzstütze}
{97200}{}{Holzstütze}
{97300}{}{Holzstütze}
{97400}{}{Holzstütze}
{97500}{}{Beschädigte Holzstütze}
{97501}{}{Diese Stütze sieht aus, als könnte sie unter Belastung einstürzen.}
{97600}{}{Eingestürzter Boden}
{97601}{}{Der Steinboden ist hier in die untere Ebene eingestürzt.}
{97700}{}{Leiter nach unten}
{97701}{}{Ein von Menschen gegrabenes Loch mit einer Leiter, die nach unten führt.}
{97800}{}{Tür}
{97900}{}{Wand}
{98000}{}{Schild für Reaktor 5}
{98100}{}{Tür}
{98200}{}{Tür}
{98300}{}{Tür}
{98400}{}{Tür}
{98500}{}{Radioaktiver Schlamm}
{98600}{}{Radioaktiver Schlamm}
{98700}{}{Radioaktiver Schlamm}
{98800}{}{Radioaktiver Schlamm}
{98900}{}{Sicherheitstür}
{99000}{}{Vault-Tür}
{99100}{}{Nutzkran}
{99200}{}{Seltsame Felsen}
{99201}{}{Dieser Einsturz scheint aus dem Nichts gekommen zu sein!}
{99300}{}{Brunnen}
{99400}{}{Werbetafel}
{99500}{}{Schalttafel}
{99600}{}{Loch}
{99601}{}{Du kannst den Boden dieser Grube nicht sehen.}
{99700}{}{Bodenplatte}
{99701}{}{Du siehst eine Bodenplattenfalle.}
{99800}{}{Entschärfte Bodenplatte}
{99801}{}{Diese Bodenplattenfalle wurde entschärft.}
{99900}{}{Ausgelöste Bodenplatte}
{99901}{}{Diese Bodenplattenfalle wurde ausgelöst. Hoppla!}
{100000}{}{Brennapparat}
{100001}{}{Das sieht nach einem holzbefeuerten Alkoholbrennapparat aus.}
{100100}{}{Plakat}
{100200}{}{Kraftwerksmaschinen}
{100201}{}{Einige hochentwickelte Geräte.}
{100300}{}{Kraftwerksmaschinen}
{100301}{}{Einige hochentwickelte Geräte.}
{100400}{}{Kraftwerksmaschinen}
{100401}{}{Einige hochentwickelte Geräte.}
{100500}{}{Kraftwerksmaschinen}
{100501}{}{Einige hochentwickelte Geräte.}
{100600}{}{Kraftwerksmaschinen}
{100601}{}{Einige hochentwickelte Geräte.}
{100700}{}{Steuerung der Kraftwerkspumpe}
{100701}{}{Dies ist die Kühlmittelpumpe des Reaktors.}
{100800}{}{Plakat}
{100900}{}{Auto}
{101000}{}{Zertrümmertes Streifenfahrzeug}
{101001}{}{Dieses Fahrzeug hatte offensichtlich einen schweren Unfall.}
{101100}{}{Auto}
{101200}{}{Friedhof}
{101201}{}{Hier befindet sich ein Grab.}
{101300}{}{Grabstein}
{101301}{}{Grabstein}
{101400}{}{Grabstein}
{101401}{}{Grabstein}
{101500}{}{Grabstein}
{101501}{}{Grabstein}
{101600}{}{Grabstein}
{101601}{}{Grabstein}
{101700}{}{Pflug}
{101701}{}{Dieser Pflug ist dafür ausgelegt, von einem Brahmin gezogen zu werden.}
{101800}{}{Pflug}
{101801}{}{Dieser Pflug ist dafür ausgelegt, von einem Brahmin gezogen zu werden.}
{101900}{}{Wasser}
{102000}{}{Rahmen}
{102001}{}{Verwitterter Rahmen des Werbekonsolen-Gehäuses.}
{102100}{}{Konsole}
{102101}{}{Neonreklamekonsole des Café-Clubs.}
{102200}{}{Wand}
{102300}{}{Neonreklame}
{102301}{}{Neonreklamekonsole des Hotels „The Sixth Bullet“.}
{102400}{}{Rahmen}
{102401}{}{Ein halb zerstörter Metallrahmen mit einer Werbekonsole.}
{102500}{}{Diskette}
{102501}{}{Du hast absolut keine Ahnung, was das ist. Man kann nur vermuten, dass diese Scheibe einst fliegen konnte.}
{102600}{}{Schatten}
{102700}{}{Kernreaktor}
{102701}{}{Dank des Kernbrennstoffs wird dieser Reaktor jahrzehntelang Energie erzeugen können.}
{102800}{}{Zeitungsautomat}
{102801}{}{Dieser uralte, restaurierte Zeitungsautomat verkauft einige Bücher und Zeitschriften.}
{102900}{}{Graffiti}
{103000}{}{Territoriumsmarkierung}
{103100}{}{Territoriumsmarkierung}
{103200}{}{Territoriumsmarkierung}
{103300}{}{Plakat}
{103400}{}{Plakat}
{103500}{}{Graffiti}
{103600}{}{Graffiti}
{103700}{}{Graffiti}
{103800}{}{Graffiti}
{103900}{}{Graffiti}
{104000}{}{Graffiti}
{104100}{}{Graffiti}
{104200}{}{Graffiti}
{104300}{}{Graffiti}
{104400}{}{Graffiti}
{104500}{}{Graffiti}
{104600}{}{Graffiti}
{104700}{}{Plakat}
{104800}{}{Plakat}
{104900}{}{Plakat}
{105000}{}{Plakat}
{105100}{}{Plakat}
{105200}{}{Plakat}
{105300}{}{Graffiti}
{105301}{}{Auf diesem Graffiti steht: „Angst und Schrecken in Las Vegas“.}
{105400}{}{Graffiti}
{105500}{}{Graffiti}
{105600}{}{Graffiti}
{105700}{}{Plakat}
{105800}{}{Plakat}
{105900}{}{Plakat}
{106000}{}{Schild}
{106100}{}{Graffiti}
{106200}{}{Graffiti}
{106300}{}{Graffiti}
{106400}{}{Graffiti}
{106500}{}{Graffiti}
{106600}{}{Graffiti}
{106700}{}{Graffiti}
{106800}{}{Graffiti}
{106900}{}{Graffiti}
{107000}{}{Graffiti}
{107100}{}{Glasscherben}
{107200}{}{Glasscherben}
{107300}{}{Graffiti}
{107400}{}{Graffiti}
{107500}{}{Graffiti}
{107600}{}{Graffiti}
{107700}{}{Graffiti}
{107800}{}{Graffiti}
{107900}{}{Graffiti}
{108000}{}{Graffiti}
{108100}{}{Graffiti}
{108200}{}{Graffiti}
{108300}{}{Graffiti}
{108400}{}{Graffiti}
{108500}{}{Graffiti}
{108600}{}{Graffiti}
{108700}{}{Glasscherben}
{108800}{}{Glasscherben}
{108900}{}{Graffiti}
{109000}{}{Graffiti}
{109100}{}{Graffiti}
{109200}{}{Graffiti}
{109300}{}{Graffiti}
{109400}{}{Graffiti}
{109500}{}{Graffiti}
{109600}{}{Graffiti}
{109700}{}{Graffiti}
{109800}{}{Plakat}
{109900}{}{Plakat}
{110000}{}{Plakat}
{110100}{}{Plakat}
{110200}{}{Plakat}
{110300}{}{Plakat}
{110400}{}{Plakat}
{110500}{}{Plakat}
{110600}{}{USA-Karte}
{110601}{}{Zum ersten Mal siehst du eine Vorkriegslandkarte der USA. Es war ein großes Land ...}
{110700}{}{Plakat}
{110800}{}{Plakat}
{110900}{}{Plakat}
{111000}{}{Schild}
{111100}{}{Schild}
{111200}{}{Schild}
{111300}{}{Schild}
{111400}{}{Schild}
{111500}{}{Schild}
{111600}{}{Schild}
{111700}{}{Schild}
{111800}{}{Wand}
{111900}{}{Wand}
{112000}{}{Wand}
{112100}{}{Wand}
{112200}{}{Wand}
{112300}{}{Wand}
{112400}{}{Rohrbogen}
{112401}{}{Dieses massive Rohr führt aus einem unterirdischen Hangar. Daran kann man bestimmt hinunterklettern.}
{112500}{}{Kontobuch}
{112501}{}{Das ist ein Buchhaltungsbuch. Es zu lesen wird sehr mühsam sein.}
{112600}{}{Auto}
{112601}{}{Es sieht so aus, als hätte dieses Auto über zehn Jahre lang im Freien gestanden.}
{112700}{}{Knochen}
{112701}{}{Menschliche Knochen, die einem Mann, einer Frau und einem Kind gehörten. Keine Spuren von Gewalt sind daran zu erkennen. Vielleicht starben diese Menschen an Strahlung oder Hunger.}
{112800}{}{Knochen}
{112801}{}{Menschliche Knochen, die einem Mann, einer Frau und einem Kind gehörten. Keine Spuren von Gewalt sind daran zu erkennen. Vielleicht starben diese Menschen an Strahlung oder Hunger.}
{112900}{}{Verkehrsschild}
{113000}{}{Leiteroberteil}
{113100}{}{Leiterunterteil}
{113101}{}{Diese Leiter ist zu weit über dem Boden, um sie zu erreichen.}
{113200}{}{Auto}
{113201}{}{Ein sehr teures, atomgetriebenes Auto.}
{113300}{}{Auto}
{113301}{}{Ein sehr teures, atomgetriebenes Auto.}
{113400}{}{Auto}
{113401}{}{Früher war es ein sehr teures, atomgetriebenes Auto. Jetzt ist es nur noch ein Haufen rostiges Metall.}
{113500}{}{Auto}
{113501}{}{Früher war es ein sehr teures, atomgetriebenes Auto. Jetzt ist es nur noch ein Haufen rostiges Metall.}
{113600}{}{Gitter}
{113700}{}{Vernagelte Kiste}
{113701}{}{Eine vernagelte Holzkiste. Vielleicht ist etwas Nützliches darin.}
{113800}{}{Aktenschrank}
{113801}{}{Ein Schrank mit Schubladen für allerlei Dokumente. Für einen Sammler von Büropapier ein wahrer Schatz. Für dich ist nichts Interessantes dabei.}
{113900}{}{Karte}
{114000}{}{Alte Reifen}
{114001}{}{Dieser Berg aus alten Reifen versperrt dir den Weg. Du brauchst einen Traktor oder fünf Pfund Sprengstoff, um hier durchzukommen.}
{114100}{}{Filmkamera}
{114200}{}{Sarg}
{114300}{}{Sarg}
{114400}{}{Sarg}
{114500}{}{Sarg}
{114600}{}{Stahlstangen}
{114700}{}{Stahlstangen}
{114800}{}{Stahlfensterladen}
{114900}{}{Stahlfensterladen}
{115000}{}{Laser-Lichtschranke}
{115100}{}{Laser-Lichtschranke}
{115200}{}{Scheiße}
{115201}{}{Unverbesserlicher Bastard, am Pranger festgebunden.}
{115300}{}{Leiter}
{115400}{}{Leiche}
{115500}{}{Schild „Geschäft aufgegeben“}
{115600}{}{Schild „Geschäft aufgegeben“}
{115700}{}{Stütze}
{115800}{}{Stütze}
{115900}{}{Brückensteuerung}
{116000}{}{Hängebrücke}
{116100}{}{Retinascanner}
{116101}{}{Dieses Sicherheitsgerät scannt das Augenmuster einer Person.}
{116200}{}{Schild für den Kontrollraum}
{116300}{}{Schild für den Kontrollraum}
{116400}{}{Schild für den Kontrollraum}
{116500}{}{Baustellenschild}
{116501}{}{Ein großes und schweres Schutzschild. Es ist so schwer, dass eine einzelne Person es nicht bewegen kann.}
{116600}{}{Baustellenschild}
{116601}{}{Ein großes und schweres Schutzschild. Es ist so schwer, dass eine einzelne Person es nicht bewegen kann.}
{116700}{}{Maschine}
{116701}{}{Eine nicht funktionsfähige Maschine.}
{116800}{}{Maschine}
{116801}{}{Eine nicht funktionsfähige Maschine.}
{116900}{}{Tür}
{117000}{}{Tür}
{117100}{}{Rohre}
{117101}{}{Ein Satz Rohre, die in den Reaktor führen.}
{117200}{}{Tank}
{117300}{}{Tanks}
{117400}{}{Tanks}
{117500}{}{Tanks}
{117600}{}{Lüftungsschacht}
{117700}{}{Lüftungsschacht}
{117800}{}{Wand}
{117900}{}{Zaun}
{118000}{}{Zaun}
{118100}{}{Zaun}
{118200}{}{Lüftungsschacht}
{118300}{}{Lüftungsschacht}
{118400}{}{Vergittertes Fenster}
{118500}{}{Schild für das Büro des Managers}
{118600}{}{Schild für den Lagerraum}
{118700}{}{Strahlungswarnschild}
{118800}{}{Dampf}
{118900}{}{Maschine}
{118901}{}{Ein beliebiges Ausrüstungsteil für das Kraftwerk.}
{119000}{}{Tank}
{119100}{}{Feuer}
{119200}{}{Wasser}
{119300}{}{Graffiti}
{119400}{}{Graffiti}
{119500}{}{Palette}
{119501}{}{Diese Bretter sind auf unnatürliche Weise aufgeschichtet, als würden sie etwas verdecken.}
{119600}{}{Rohrstütze}
{119700}{}{Schild}
{119800}{}{Rohrstütze}
{119900}{}{Plakat}
{120000}{}{Feuerstelle}
{120100}{}{Höhlenwand}
{120200}{}{Höhlenwand}
{120300}{}{Höhlenwand}
{120400}{}{Höhlenwand}
{120500}{}{Höhlenwand}
{120600}{}{Höhlenwand}
{120700}{}{Höhlenwand}
{120800}{}{Höhlenwand}
{120900}{}{Höhlenwand}
{121000}{}{Höhlenwand}
{121100}{}{Höhlenwand}
{121200}{}{Höhlenwand}
{121300}{}{Höhlenwand}
{121400}{}{Höhlenwand}
{121500}{}{Höhlenwand}
{121600}{}{Pfahl}
{121601}{}{Auf diesem Pfahl scheint jemand aufgespießt zu sein!}
{121700}{}{Pfahl}
{121701}{}{Auf diesem Pfahl scheint jemand aufgespießt zu sein!}
{121800}{}{Pfahl}
{121801}{}{Auf diesem Pfahl scheint jemand aufgespießt zu sein!}
{121900}{}{Pfahl}
{121901}{}{Auf diesem Pfahl scheint jemand aufgespießt zu sein!}
{122000}{}{Pfahl}
{122001}{}{Auf diesem Pfahl scheint jemand aufgespießt zu sein!}
{122100}{}{Schreibtisch}
{122101}{}{Ein einfacher Tisch. Das Einzige, was ihn von anderen Tischen unterscheidet, sind die Schreibutensilien darauf.}
{122200}{}{Pfahl}
{122201}{}{Auf diesem Pfahl scheint ein menschlicher Schädel zu stecken.}
{122300}{}{Pfahl}
{122301}{}{Auf diesem Pfahl scheint ein menschlicher Schädel zu stecken.}
{122400}{}{Pfahl}
{122401}{}{Dieser leere Pfahl sieht aus, als wäre er für ein unfreiwilliges Opfer bereit.}
{122500}{}{Pfahl}
{122501}{}{Dieser leere Pfahl sieht aus, als wäre er für ein unfreiwilliges Opfer bereit.}
{122600}{}{Pfahl}
{122601}{}{Dieser leere Pfahl sieht aus, als wäre er für ein unfreiwilliges Opfer bereit.}
{122700}{}{Pfahl}
{122701}{}{Dieser leere Pfahl sieht aus, als wäre er für ein unfreiwilliges Opfer bereit.}
{122800}{}{Schild „Gesucht“}
{122801}{}{Das Bild auf diesem Schild sieht dir verdächtig ähnlich!}
{122900}{}{Boden}
{123000}{}{Plakat}
{123100}{}{Haubitze}
{123101}{}{Diese merkwürdig aussehende Kanone wirkt wie ein Relikt aus der Vorkriegszeit. Du fragst dich, wie sie hierhergekommen ist.}
{123200}{}{Lampe}
{123300}{}{Strahlungszeichen}
{123301}{}{"Gefahr! Strahlung!"}
{123400}{}{Strahlungszeichen}
{123401}{}{"Gefahr! Strahlung!"}
{123500}{}{Plakat}
{123600}{}{Schalter}
{123700}{}{Kreuz}
{123800}{}{Kreuz}
{123900}{}{Kreuz}
{124000}{}{Kreuz}
{124100}{}{Kreuz}
{124200}{}{Kreuz}
{124300}{}{Benzinpumpe}
{124400}{}{Benzinpumpe}
{124500}{}{Benzinpumpe}
{124600}{}{Pep-Gas-Schild}
{124700}{}{Schatten des Schildes}
{124800}{}{Heubett}
{124900}{}{Heubett}
{125000}{}{Heubett}
{125100}{}{Heubett}
{125200}{}{Heubett}
{125300}{}{Heubett}
{125400}{}{Ladenschild}
{125500}{}{Ein Stand eines Straßenhändlers}
{125600}{}{Ein Stand eines Straßenhändlers}
{125700}{}{Ein Stand eines Straßenhändlers}
{125800}{}{Ein Stand eines Straßenhändlers}
{125900}{}{Willkommensschild}
{125901}{}{Willkommensschild am Straßenrand der Vorkriegsstadt Lovelock.}
{126000}{}{Zeitungsausschnitte}
{126001}{}{Nach diesen Zeitungsausschnitten zu urteilen, ist der Bewohner dieses Zimmers geradezu besessen von der Angst vor einer Alien-Invasion.}
{126100}{}{Sheriffbüro}
{126200}{}{Plakat}
{126201}{}{Ein Poster mit einem Typen, der eine Kamera hält. Sein Gesicht kennt jeder, aber heute kann niemand mehr genau sagen, wer er ist.}
{126300}{}{Kürbisse}
{126400}{}{Plakat}
{126500}{}{Lampen}
{126600}{}{Barrikade}
{126700}{}{Schmutziges Wasser}
{126800}{}{Schmutziges Wasser}
{126900}{}{Schmutziges Wasser}
{127000}{}{Schmutziges Wasser}
{127100}{}{Kasinoschild}
{127200}{}{Kasinoschild}
{127300}{}{Steinhaufen}
{127301}{}{Diese Felsen scheinen etwas einzuschließen.}
{127400}{}{Träger}
{127500}{}{Träger}
{127600}{}{Träger}
{127700}{}{Träger}
{127800}{}{Träger}
{127900}{}{Träger}
{128000}{}{Träger}
{128100}{}{Träger}
{128200}{}{Träger}
{128300}{}{Träger}
{128400}{}{Schatten}
{128500}{}{Schatten}
{128600}{}{Schatten}
{128700}{}{Schatten}
{128800}{}{Schatten}
{128900}{}{Schatten}
{129000}{}{Schatten}
{129100}{}{Schatten}
{129200}{}{Schatten}
{129300}{}{Aufzugschacht}
{129400}{}{Benzinpumpe}
{129500}{}{Benzinpumpe}
{129600}{}{Benzinpumpe}
{129700}{}{Seil}
{129800}{}{Fenster}
{129900}{}{Brahmin-Fleisch}
{130000}{}{Brahmin-Fleisch}
{130100}{}{Brahmin-Fleisch}
{130200}{}{Brahmin-Fleisch}
{130300}{}{Brahmin-Fleisch}
{130400}{}{Brahmin-Fleisch}
{130500}{}{Träger}
{130600}{}{Träger}
{130700}{}{Träger}
{130800}{}{Träger}
{130900}{}{Träger}
{131000}{}{Träger}
{131100}{}{Träger}
{131200}{}{Träger}
{131300}{}{Schatten}
{131400}{}{Schatten}
{131500}{}{Schatten}
{131600}{}{Schatten}
{131700}{}{Schatten}
{131800}{}{Schatten}
{131900}{}{Schatten}
{132000}{}{Schatten}
{132100}{}{Blut}
{132200}{}{Blut}
{132300}{}{Blut}
{132400}{}{Blut}
{132500}{}{Blut}
{132600}{}{Blut}
{132700}{}{Blut mit Knochen}
{132800}{}{Blut mit Knochen}
{132900}{}{Blut mit Knochen}
{133000}{}{Höhleneingang}
{133100}{}{Mikrofon}
{133200}{}{Scheinwerfer}
{133300}{}{Scheinwerfer}
{133400}{}{Scheinwerfer}
{133500}{}{Computer}
{133501}{}{Ein Vault-Computerterminal, das an den Großrechner angeschlossen ist.}
{133600}{}{Computer}
{133601}{}{Ein Vault-Computerterminal, das an den Großrechner angeschlossen ist.}
{133700}{}{Kran}
{133701}{}{Ein verrosteter Kran. In diesem Zustand ist nicht viel zu erwarten.}
{133800}{}{Großer Muellhaufen}
{133801}{}{Ein Haufen gewöhnlicher Abfälle, zu einer Leiter aufgeschichtet.}
{133900}{}{Wand}
{134000}{}{Wand}
{134100}{}{Wand}
{134200}{}{Wand}
{134300}{}{Wand}
{134400}{}{Wand}
{134500}{}{Wand}
{134600}{}{Wand}
{134700}{}{Lüftung}
{134800}{}{Lüftung}
{134900}{}{Schatten}
{135000}{}{Hangar}
{135100}{}{Hangar}
{135200}{}{Hangar}
{135300}{}{Hangar}
{135400}{}{Hangar}
{135500}{}{Hangar}
{135600}{}{Hangar}
{135700}{}{Hangar}
{135800}{}{Tür}
{135900}{}{Panorama}
{136000}{}{Panorama}
{136100}{}{Panorama}
{136200}{}{Panorama}
{136300}{}{Panorama}
{136400}{}{Panorama}
{136500}{}{Feuerstelle}
{136600}{}{Feuerstelle}
{136700}{}{Geschützturm-Steuerung}
{136701}{}{Dies ist ein leistungsstarkes Computersystem, das die Geschütze auf dem Gelände der Basis koordiniert.}
{136800}{}{Schatten}
{136900}{}{Panorama}
{137000}{}{Berg}
{137100}{}{Höhle}
{137200}{}{Glasscherben}
{137300}{}{Fackel}
{137301}{}{Eine brennende Fackel in einer Wandhalterung.}
{137400}{}{Fackel}
{137401}{}{Eine brennende Fackel in einer Wandhalterung.}
{137500}{}{Fackel}
{137501}{}{Eine brennende Fackel in einer Wandhalterung.}
{137600}{}{Fackel}
{137601}{}{Eine brennende Fackel in einer Wandhalterung.}
{137700}{}{Kürbis mit einer Kerze}
{137800}{}{Lagertank}
{137801}{}{Vor dir siehst du einen automatisierten Flüssigkeitstank.}
{137900}{}{Grabkreuz}
{137901}{}{Darauf steht: "Eben Byers. So endet übertriebene Gesundheitsvorsorge".}
{138000}{}{Wand}
{138100}{}{Wand}
{138200}{}{Wand}
{138300}{}{Wand}
{138400}{}{Wand}
{138500}{}{Wand}
{138600}{}{Leicht}
{138700}{}{Tür}
{138800}{}{Tür}
{138900}{}{Tür}
{139000}{}{Tür}
{139100}{}{Tür}
{139200}{}{Tür}
{139300}{}{Banner}
{139400}{}{Pfosten}
{139500}{}{Pfosten}
{139600}{}{Banner}
{139700}{}{Banner}
{139800}{}{Pfosten}
{139900}{}{Pfosten}
{140000}{}{Banner}
{140100}{}{Schatten}
{140200}{}{Schatten}
{140300}{}{Schmutzige Bombe}
{140301}{}{Es fällt dir schwer zu erkennen, worum es sich handelt. Doch unter der Huelle dieses Ungetüms befindet sich eindeutig etwas sehr Radioaktives.}
{140400}{}{Schmutzige Bombe}
{140401}{}{Es fällt dir schwer zu erkennen, worum es sich handelt. Doch unter der Huelle dieses Ungetüms befindet sich eindeutig etwas sehr Radioaktives.}
{140500}{}{Werbebanner}
{140600}{}{Schmutzige Bombe}
{140601}{}{Es fällt dir schwer zu erkennen, worum es sich handelt. Doch unter der Huelle dieses Ungetüms befindet sich eindeutig etwas sehr Radioaktives.}
{140700}{}{Träger}
{140800}{}{Schild}
{140801}{}{Auf dem Schild steht: "Drogerie"}
{140900}{}{Gitter}
{141000}{}{Ringschild}
{141100}{}{Nachtclubbeleuchtung}
{141200}{}{Graffiti}
{141300}{}{Marken-Graffiti}
{141301}{}{Hotelwerbung. Jemand hat sie bereits mit Schmierereien verunstaltet.}
{141400}{}{Schild}
{141401}{}{Auf dem Schild steht: "Opal-Shop"}
{141500}{}{Stromverteiler}
{141501}{}{Dieses Gerät dient der Steuerung und Verteilung von Elektrizität.}
{141600}{}{Statue}
{141700}{}{Lagertür}
{141800}{}{Lagertür}
{141900}{}{Schichtplan}
{141901}{}{Der Arbeitsplan des Werks. Offenbar wird ausschließlich tagsüber gearbeitet; nachts ist niemand in der Werkhalle.}
{142000}{}{Sheriff-Schild}
{142100}{}{Schautafel}
{142101}{}{Du siehst eine Tafel voller Kreideaufzeichnungen und Blockdiagramme.}
{142200}{}{Überreste von Jay Kukish}
{142201}{}{Diese Leiche ist noch sehr frisch. Eine ruhige Hand hat einige Organe herausoperiert.}
{142300}{}{Notiztafel}
{142301}{}{Du siehst eine Tafel voller Kreidenotizen und Pläne zur Arbeit im Werk.}
{142400}{}{Zeitplan}
{142500}{}{Klippe}
{142600}{}{Ruine}
{142601}{}{Bei der Explosion entstand aus dem Inneren des Hangars ein Trümmerfeld. Von allem etwas.}
{142700}{}{Überreste}
{142701}{}{Dieses Skelett ist sehr alt.}
{142800}{}{Fernseher}
{142801}{}{Ein uraltes Fernsehgerät. Wie zu erwarten, gibt es nichts zu sehen.}
{142900}{}{Reinigungsroboter}
{142901}{}{Roboter zur Reinigung des Geländes von den Folgen radioaktiver Verseuchung. Er funktioniert schon lange nicht mehr.}
{143000}{}{Lautsprecherpfahl}
{143001}{}{Einst warnten diese Lautsprecher die Anwohner vor der Gefahr. Offenbar hat ihnen das nicht geholfen.}
{143100}{}{Straßenlaterne}
{143200}{}{Graffiti}
{143300}{}{Seil}
{143301}{}{Mit diesem Seil kannst du über die Mauer klettern.}
{143400}{}{Schlucht}
{143500}{}{Schlucht}
{143600}{}{Fenster}
{143700}{}{Fenster}
{143800}{}{Fenster}
{143900}{}{Fenster}
{144000}{}{Fenster}
{144100}{}{Fenster}
{144200}{}{Fenster}
{144300}{}{Fenster}
{144400}{}{Fenster}
{144500}{}{Fenster}
{144600}{}{Fenster}
{144700}{}{Fenster}
{144800}{}{Zugtür}
{144900}{}{Tür}
{145000}{}{Stütze}
{145100}{}{Stütze}
{145200}{}{Bogen}
{145300}{}{Bogen}
{145400}{}{Wasser}
{145500}{}{Wasser}
{145600}{}{Wasser}
{145700}{}{Wasser}
{145800}{}{Wasser}
{145900}{}{Wasser}
{146000}{}{Wasser}
{146100}{}{Tanker}
{146200}{}{Tanker}
{146300}{}{Tanker}
{146400}{}{Tanker}
{146500}{}{Laub}
{146600}{}{Zauntor}
{146700}{}{Zauntor}
{146800}{}{Kommandositz}
{146801}{}{Hier sitzt normalerweise der Aufseher.}
{146900}{}{Wand}
{147000}{}{Wand}
{147100}{}{Wand}
{147200}{}{Schatten}
{147300}{}{Hoteleingang}
{147400}{}{Hoteleingang}
{147500}{}{Teppich}
{147600}{}{Casinoeingang}
{147700}{}{Casinoeingang}
{147800}{}{Hoteleingang}
{147900}{}{Cas TüR}
{148000}{}{Cas TüR}
{148100}{}{Casinoeingang}
{148200}{}{Casinoeingang}
{148300}{}{Casinoeingang}
{148400}{}{Casinoeingang}
{148500}{}{Casinoeingang}
{148600}{}{Casinoeingang}
{148700}{}{Casinoeingang}
{148800}{}{Casinoeingang}
{148900}{}{Casinoeingang}
{149000}{}{Casinoeingang}
{149100}{}{Cas TüR}
{149200}{}{Cas TüR}
{149300}{}{Wandleuchte}
{149400}{}{Wandleuchte}
{149500}{}{Wandleuchte}
{149600}{}{Wandleuchte}
{149700}{}{Wandleuchte}
{149800}{}{Wand}
{149900}{}{Wand}
{150000}{}{Ventilator}
{150100}{}{Ventilator}
{150200}{}{Feuerlöscher}
{150300}{}{Feuerlöscher}
{150400}{}{Rohr}
{150500}{}{Stromverteiler}
{150600}{}{Stromverteiler}
{150700}{}{Wand}
{150800}{}{Wand}
{150900}{}{Wand}
{151000}{}{Wand}
{151100}{}{Wand}
{151200}{}{Wand}
{151300}{}{Wand}
{151400}{}{Wand}
{151500}{}{Wand}
{151600}{}{Holzvertäfelung}
{151700}{}{Holzvertäfelung}
{151800}{}{Rohr}
{151900}{}{Rohr}
{152000}{}{Rohr}
{152100}{}{Rohr}
{152200}{}{Rohr}
{152300}{}{Rohr}
{152400}{}{Rohr}
{152500}{}{Rohr}
{152600}{}{Rohr}
{152700}{}{Rohr}
{152800}{}{Rohr}
{152900}{}{Lüftungsschacht}
{153000}{}{Lüftungsschacht}
{153100}{}{Tür}
{153200}{}{Tür}
{153300}{}{Tür}
{153400}{}{Tür}
{153500}{}{Tür}
{153600}{}{Tür}
{153700}{}{Dusche}
{153800}{}{Plattform}
{153900}{}{Plattform}
{154000}{}{Großer Tank}
{154100}{}{Tanks}
{154200}{}{Kisten}
{154300}{}{Radarstation}
{154400}{}{Radarstation}
{154500}{}{Antenne}
{154600}{}{Antenne}
{154700}{}{Schatten}
{154800}{}{Kraftfeld}
{154900}{}{Kraftfeld}
{155000}{}{Toilette}
{155100}{}{Werbeschild}
{155200}{}{Werbeschild}
{155300}{}{Werbeschild}
{155400}{}{Werbeschild}
{155500}{}{Werbeschild}
{155600}{}{Werbeschild}
{155700}{}{Werbeschild}
{155800}{}{Werbeschild}
{155900}{}{Werbeschild}
{156000}{}{Werbeschild}
{156001}{}{Schild „Willkommen in der unglaublichen Stadt Las Vegas“.}
{156100}{}{Werbeschild}
{156101}{}{Schild „Willkommen in der unglaublichen Stadt Las Vegas“.}
{156200}{}{Werbeschild}
{156201}{}{Schild „Willkommen in der unglaublichen Stadt Las Vegas“.}
{156300}{}{Stadtzaun}
{156400}{}{Stadtzaun}
{156500}{}{Stadtzaun}
{156600}{}{Schatten}
{156700}{}{Schatten}
{156800}{}{Schatten}
{156900}{}{Schatten}
{157000}{}{Antenne}
{157100}{}{Schatten}
{157200}{}{Eingestürztes Schild}
{157300}{}{Block}
{157400}{}{Dunstabzugshaube}
{157500}{}{Gepanzerte Tür}
{157501}{}{Gepanzerte Tür, die sich mit einer speziellen Schlüsselkarte öffnen lässt.}
{157600}{}{Tür}
{157601}{}{Kunstvoll gefertigte Holztür in ausgezeichnetem Zustand.}
{157700}{}{Lüftungsschacht}
{157800}{}{Autodoc}
{157801}{}{Dieser Autodoc ist dafür ausgelegt, Krankheiten zu heilen und verschiedene Medikamente zu verabreichen.}
{157900}{}{Zerstörter Geschützturm}
{157901}{}{Dieser Geschützturm funktioniert nicht.}
{158000}{}{Steinhaufen}
{158100}{}{Kraftfeld}
{158101}{}{Ein Energiefeld versperrt dir den Weg.}
{158200}{}{Kraftfeld}
{158201}{}{Ein Energiefeld versperrt dir den Weg.}
{158300}{}{Kraftfeld}
{158301}{}{Ein Energiefeld versperrt dir den Weg.}
{158400}{}{Kraftfeld}
{158401}{}{Ein Energiefeld versperrt dir den Weg.}
{158500}{}{Schatten}
{158600}{}{Schatten}
{158700}{}{Schatten}
{158800}{}{Schatten}
{158900}{}{Schatten}
{159000}{}{Schatten}
{159100}{}{Schatten}
{159200}{}{Schatten}
{159300}{}{Der Sockel des Funkturms}
{159400}{}{Der Sockel des Funkturms}
{159500}{}{Einsturz}
{159600}{}{Einsturz}
{159700}{}{Hotelarchitektur}
{159800}{}{Spielautomat}
{159801}{}{Moderner Spielautomat mit Computerinnenleben. Dient zum Spielen von Arcade-Spielen.}
{159900}{}{Spielautomat}
{159901}{}{Moderner Spielautomat mit Computerinnenleben. Dient zum Spielen von Arcade-Spielen.}
{160000}{}{Wand}
{160100}{}{Wand}
{160200}{}{Bodenschacht}
{160300}{}{Steinbank}
{160400}{}{Steinbank}
{160500}{}{Fass im Sand}
{160600}{}{Gaskammer}
{160601}{}{Anlage für Gasflaschen.}
{160700}{}{Schatten}
{160800}{}{Schatten}
{160900}{}{Schatten}
{161000}{}{Schatten}
{161100}{}{Schatten}
{161200}{}{Schatten}
{161300}{}{Schatten}
{161400}{}{Träger}
{161500}{}{Schatten}
{161600}{}{Schatten}
{161700}{}{Schatten}
{161800}{}{Schatten}
{161900}{}{Schatten}
{162000}{}{Regal mit Figuren}
{162001}{}{Du siehst ein Regal, auf dem zahlreiche Gipsfiguren und Köpfe stehen.}
{162100}{}{Treibstofftank}
{162101}{}{Tank mit Treibstoff für den Transport. Und er ist definitiv nicht leer.}
{162200}{}{Behälter}
{162300}{}{Behälter}
{162400}{}{Behälter}
{162500}{}{Lagertank}
{162501}{}{Ein mit Biogel gefüllter Tank, in dem ein mutierter, gallertartiger Körper schwebt.}
{162600}{}{Lagertank}
{162601}{}{Ein mit Biogel gefüllter Tank, in dem ein mutierter, gallertartiger Körper schwebt.}
{162700}{}{Papiere auf dem Tisch}
{162800}{}{Demontierter Roboter}
{162900}{}{Lore}
{163000}{}{Wand}
{163100}{}{Wand}
{163200}{}{Wand}
{163300}{}{Wand}
{163400}{}{Wand}
{163500}{}{Wand}
{163600}{}{Wand}
{163700}{}{Flagge}
{163800}{}{Wand}
{163900}{}{Wand}
{164000}{}{Wand}
{164100}{}{Wand}
{164200}{}{Auspufföffnung}
{164300}{}{Schreibtisch}
{164400}{}{Schreibtisch}
{164500}{}{Treppe nach unten}
{164600}{}{Treppe nach oben}
{164700}{}{Tanker}
{164800}{}{Tanker}
{164900}{}{Tanker}
{165000}{}{Tanker}
{165100}{}{Tanker}
{165200}{}{Tanker}
{165300}{}{Tanker}
{165400}{}{Tanker}
{165500}{}{Tanker}
{165600}{}{Tanker}
{165700}{}{Tanker}
{165800}{}{Nachtschattenstrauch}
{165900}{}{Verkaufsautomat}
{166000}{}{Tanker}
{166100}{}{Tanker}
{166200}{}{Warnschild}
{166201}{}{„Halt! Sperrgebiet!“}
{166300}{}{Galgen}
{166400}{}{Galgen}
{166500}{}{Große Kisten}
{166501}{}{Ein Stapel Kisten, die zu einer „Leiter“ aufgestellt sind. Du kannst bis ganz nach oben klettern.}
{166600}{}{Hightech-Gerät}
{166700}{}{Klavier}
{166701}{}{Ein wunderschönes Klavier mit goldenen Verzierungen.}
{166800}{}{Warnschild}
{166801}{}{„Halt! Sperrzone!“}
{166900}{}{Warnschild}
{166901}{}{„Halt! Sperrzone!“}
{167000}{}{Werbeplakat}
{167100}{}{Werbeplakat}
{167200}{}{Werbeplakat}
{167300}{}{Tanker}
{167400}{}{Tanker}
{167500}{}{Fabrikschild}
{167600}{}{Fabrikschild}
{167700}{}{Propagandaplakat}
{167800}{}{Propagandaplakat}
{167900}{}{Propagandaplakat}
{168000}{}{Propagandaplakat}
{168100}{}{Gemälde}
{168200}{}{Tanker}
{168300}{}{Plakat}
{168400}{}{Flugroboter}
{168500}{}{Minenaufzug}
{168600}{}{Minenaufzug}
{168700}{}{Kleidungssynthesizer}
{168701}{}{Ein ruinierter Kleidungssynthesizer der Firma Vault-Tec. Obwohl einige Innenteile intakt zu sein scheinen, lässt er sich kaum wieder funktionsfähig machen.}
{168800}{}{Vertibird}
{168900}{}{Vertibird}
{169000}{}{Vertibird}
{169100}{}{Vertibird}
{169200}{}{Vertibird}
{169300}{}{Schatten}
{169400}{}{Schatten}
{169500}{}{Schatten}
{169600}{}{Schatten}
{169700}{}{Tanker}
{169800}{}{Tanker}
{169900}{}{Tanker}
{170000}{}{Tanker}
{170100}{}{Tanker}
{170200}{}{Tanker}
{170300}{}{Tanker}
{170400}{}{Tanker}
{170500}{}{Tanker}
{170600}{}{Tanker}
{170700}{}{Tanker}
{170800}{}{Tanker}
{170900}{}{Tür}
{171000}{}{Tür}
{171100}{}{Wand}
{171200}{}{Wand}
{171300}{}{Wand}
{171400}{}{Wand}
{171500}{}{Wand}
{171600}{}{Wand}
{171700}{}{Wand}
{171800}{}{Wand}
{171900}{}{Lüftungsschacht}
{172000}{}{Lüftungsschacht}
{172100}{}{Kugelsicheres Glas}
{172200}{}{Kugelsicheres Glas}
{172300}{}{Kugelsicheres Glas}
{172400}{}{Schwerer Laserturm}
{172500}{}{Schwerer Laserturm}
{172600}{}{Felsen}
{172700}{}{Felsen}
{172800}{}{Felsen}
{172900}{}{Felsen}
{173000}{}{Felsen}
{173100}{}{Felsen}
{173200}{}{Felsen}
{173300}{}{Felsen}
{173400}{}{Felsen}
{173500}{}{Felsen}
{173600}{}{Felsen}
{173700}{}{Straßenkarte}
{173800}{}{Plakat}
{173900}{}{Warnung}
{173901}{}{Ein Warnschild, das das offene Tragen von Waffen auf dem Gelände der Clean City verbietet.}
{174000}{}{Vorhang}
{174100}{}{Vorhang}
{174200}{}{Wand}
{174300}{}{Graffiti}
{174400}{}{Verrammelte Tür}
{174401}{}{Eine Tür mit quer verlaufenden Metalleinsätzen, die sich weder öffnen noch umstoßen lässt.}
{174500}{}{Jukebox}
{174501}{}{Eine alte Jukebox.}
{174600}{}{Ventilator}
{174700}{}{Ventilator}
{174800}{}{Gully}
{174900}{}{Ausgangsschild}
{175000}{}{Lampe}
{175100}{}{Lampe}
{175200}{}{Außer Betrieb}
{175300}{}{Loch im Boden}
{175301}{}{Ein tiefes Loch im Boden. Unten ist durch die Dunkelheit kaum der Metallboden zu erkennen.}
{175400}{}{Zugtüren}
{175500}{}{Kopf im Tank}
{175600}{}{Klippe}
{175700}{}{Brücke über die Schlucht}
{175800}{}{Brücke über die Schlucht}
{175900}{}{Brücke über die Schlucht}
{176000}{}{Brücke über die Schlucht}
{176100}{}{Klippe}
{176200}{}{Klippe}
{176300}{}{Klippe}
{176400}{}{Zug}
{176500}{}{Zug}
{176600}{}{Zug}
{176700}{}{Klippe}
{176800}{}{Schatten}
{176900}{}{Brücke über die Schlucht}
{177000}{}{Eingang}
{177100}{}{Eingang}
{177200}{}{Eingang}
{177300}{}{Eingang}
{177400}{}{Abwasserrohre}
{177500}{}{Abwasserrohre}
{177600}{}{Schlucht}
{177700}{}{Gilmores Leiche}
{177701}{}{Gerechtigkeit ist geschehen. Das ist Gary Mark Gilmore aus Provo, ein ehemaliger Verbrecher. Möge er in der Hölle brennen!}
{177800}{}{Tisch}
{177900}{}{Alte Windmühle}
{177901}{}{Das ist der äußere Teil des Windparks. Er besteht aus allerlei Schrott. Wir können demjenigen, der das gebaut hat, nur auf die Schulter klopfen.}
{178000}{}{Schatten}
{178100}{}{Schatten}
{178200}{}{Schatten}
{178300}{}{Schatten}
{178400}{}{Schatten}
{178500}{}{Brücke über die Schlucht}
{178600}{}{Dach}
{178700}{}{Dach}
{178800}{}{Dach}
{178900}{}{Schatten}
{179000}{}{Turm}
{179100}{}{Turm}
{179200}{}{Turm}
{179300}{}{Springbrunnen}
{179400}{}{Springbrunnen}
{179500}{}{Springbrunnen}
{179600}{}{Springbrunnen}
{179700}{}{Springbrunnen}
{179800}{}{Springbrunnen}
{179900}{}{Springbrunnen}
{180000}{}{Springbrunnen}
{180100}{}{Fenster}
{180200}{}{Trümmer}
{180300}{}{Felsen}
{180400}{}{Felsen}
{180500}{}{Felsen}
{180600}{}{Felsen}
{180700}{}{Plakat}
{180800}{}{Plakat}
{180900}{}{„Minen!“}
{180901}{}{Das Schild warnt vor Minengefahr.}
{181000}{}{„Minen!“}
{181001}{}{Das Schild warnt vor Minengefahr.}
{181100}{}{Werbeschild}
{181200}{}{Werbeschild}
{181300}{}{Tisch}
{181400}{}{Sarg}
{181500}{}{Kriegerstatue}
{181501}{}{Eine Statue, die einen muskulösen Krieger mit einer Baskenmütze und Granaten am Gürtel zeigt, der versucht, sich aus seinen Ketten zu befreien.}
{181600}{}{Namensschild}
{181700}{}{Tisch}
{181800}{}{Holztür}
{181900}{}{Holztür}
{182000}{}{Getränkekühlschrank}
{182100}{}{Getränkekühlschrank}
{182200}{}{Herd}
{182300}{}{Herd}
{182400}{}{Herd}
{182500}{}{Herd}
{182600}{}{Kram}
{182700}{}{Kram}
{182800}{}{Kram}
{182900}{}{Kram}
{183000}{}{Kram}
{183100}{}{Kram}
{183200}{}{Kram}
{183300}{}{Kram}
{183400}{}{Präsidentensessel}
{183500}{}{Treppe}
{183600}{}{Weltkarte}
{183700}{}{Lagekarte}
{183800}{}{Leiter}
{183900}{}{Tisch im Ratssaal}
{184000}{}{Tisch im Ratssaal}
{184100}{}{Stütze}
{184200}{}{Baum}
{184300}{}{Baum}
{184400}{}{Wachturm}
{184500}{}{Sitz}
{184501}{}{Ein stinkender alter Stuhl, der einst ein Autositz war. Die Federn haben ihre Spannkraft verloren.}
{184600}{}{Galgen}
{184700}{}{Förderband}
{184800}{}{Förderband}
{184900}{}{Futtertrog}
{185000}{}{Verfallene Bretter}
{185001}{}{Ein Abschnitt der Mauer besteht aus alten Brettern. Mit Werkzeug und roher Gewalt lässt er sich leicht auseinandernehmen.}
{185100}{}{Dampf}
{185200}{}{Schatten}
{185300}{}{Schatten}
{185400}{}{Schatten}
{185500}{}{Schatten}
{185600}{}{Schatten}
{185700}{}{Schatten}
{185800}{}{Schatten}
{185900}{}{Loch im Boden}
{185901}{}{Du siehst ein Loch im Boden. Das Seil ist sicher an den Steinen befestigt.}
{186000}{}{Sarg}
{186100}{}{Schild}
{186101}{}{„Das Atomic-Café“}
{186200}{}{Graffiti}
{186300}{}{Graffiti}
{186400}{}{Graffiti}
{186500}{}{Graffiti}
{186600}{}{Graffiti}
{186700}{}{Graffiti}
{186800}{}{Gully}
{186900}{}{Gully}
{187000}{}{Alte Reifen}
{187100}{}{Alte Reifen}
{187200}{}{Alte Reifen}
{187300}{}{Alte Reifen}
{187400}{}{Alte Reifen}
{187500}{}{Alte Reifen}
{187600}{}{Alte Reifen}
{187700}{}{Alte Reifen}
{187800}{}{Alte Reifen}
{187900}{}{Foto eines Künstlers}
{188000}{}{Foto eines Künstlers}
{188100}{}{Foto eines Künstlers}
{188200}{}{Transformator}
{188201}{}{Straßenverteiltransformator.}
{188300}{}{Schalttafel}
{188301}{}{Ein Schaltschrank mit Zähler. Er versorgt das Haus mit Strom.}
{188400}{}{Antenne}
{188500}{}{Antenne}
{188600}{}{Antenne}
{188700}{}{Antenne}
{188800}{}{Antenne}
{188900}{}{Drahtseil}
{189000}{}{Drahtseil}
{189100}{}{Lagerfeuer}
{189200}{}{Labortisch}
{189300}{}{Werkbank}
{189400}{}{Rattenfalle}
{189401}{}{Vor dir liegt eine rostige Falle. Sie ist gespannt und sehr gefährlich.}
{189500}{}{Lichter}
{189600}{}{Menschenknochen}
{189601}{}{Ein Haufen alter, angenagter Knochen, eindeutig menschlich. Auf einigen sind Spuren von Schrotkugeln zu sehen.}
{189700}{}{Menschenknochen}
{189701}{}{Ein Haufen alter, angenagter Knochen, eindeutig menschlich. Auf einigen sind Spuren von Schrotkugeln zu sehen.}
{189800}{}{Die Motorhaube des Transporters}
{189900}{}{Flagge der Hoffnung}
{189901}{}{Diese Flagge scheint von einem Kind gemacht worden zu sein. Sehr niedlich.}
{190000}{}{Kinderschaukel}
{190100}{}{Schaukelgestell}
{190200}{}{Schatten}
{190300}{}{Schatten}
{190400}{}{Schatten}
{190500}{}{Schatten}
{190600}{}{Loser Balken}
{190601}{}{Du siehst nichts Ungewöhnliches. Abgesehen davon, dass die Bretter etwas schief angenagelt sind.}
{190700}{}{Brahmin bleibt}
{190701}{}{Teilweise verweste Überreste eines brahmin – linker Kopf, rechter Kopf, ein bisschen von allem. Die köstlichsten Teile wurden offenbar schon vor langer Zeit gegessen.}
{190800}{}{Loch im Boden}
{190801}{}{Nur ein Loch, aus dem du gekrochen bist.}
{190900}{}{Notiz an Milo}
{190901}{}{Dieser Brief ist an Milo und an alle gerichtet, die ihm begegnen werden.}
{191000}{}{Seltsamer Bus}
{191001}{}{Dieser ungewöhnliche, säurefarbene Bus sieht aus, als hätte man ihn eigens hier abgestellt, damit er für alle Ewigkeit stehen bleibt.}
{191100}{}{Ei}
{191101}{}{Dieses schwere Ei steckt im Loch fest und lässt sich nicht mehr bewegen.}
{191200}{}{Staudamm}
{191300}{}{Staudamm}
{191400}{}{Staudamm}
{191500}{}{Staudamm}
{191600}{}{Staudamm}
{191700}{}{Staudamm}
{191800}{}{Staudamm}
{191900}{}{Staudamm}
{192000}{}{Staudamm}
{192100}{}{Staudamm}
{192200}{}{Staudamm}
{192300}{}{Staudamm}
{192400}{}{Staudamm}
{192500}{}{Staudamm}
{192600}{}{Staudamm}
{192700}{}{Staudamm}
{192800}{}{Staudamm}
{192900}{}{Staudamm}
{193000}{}{Staudamm}
{193100}{}{Staudamm}
{193200}{}{Staudamm}
{193300}{}{Staudamm}
{193400}{}{Staudamm}
{193500}{}{Staudamm}
{193600}{}{Staudamm}
{193700}{}{Staudamm}
{193800}{}{Staudamm}
{193900}{}{Staudamm}
{194000}{}{Berg}
{194100}{}{Berg}
{194200}{}{Berg}
{194300}{}{Berg}
{194400}{}{Zwei am Tisch}
{194500}{}{Zwei am Tisch}
{194600}{}{Leinwand}
{194601}{}{Diese Werbetafel ist mit alten Laken bedeckt und dient als Kinoleinwand.}
{194700}{}{Leinwand}
{194701}{}{Diese Werbetafel ist mit alten Laken bedeckt und dient als Kinoleinwand.}
{194800}{}{Leiter}
{194801}{}{Diese Treppe ist verbarrikadiert, damit niemand ins obere Stockwerk gelangen kann. Dafür hast du allerdings keinen Grund.}
{194900}{}{Schild der Ranch „Aromas of Maureen“}
{195000}{}{Wasserversorgung für Brahmin}
{195001}{}{Hier muss Wasser für brahmin im Gehege geschöpft werden.}
{195100}{}{Benzinfass}
{195101}{}{Wer es dort abgestellt hat, riskiert, ein Feuer zu entfachen.}
{195200}{}{Verbrannte Kisten}
{195300}{}{Verbrannte Kisten}
{195400}{}{Verbrannte Kiste}
{195500}{}{Verbrannte Kiste}
{195600}{}{Verbrannte Kiste}
{195700}{}{Bedienfeld}
{195701}{}{Es ist der Knotenpunkt zur Steuerung und Synchronisierung der Vault-Systeme. Wie üblich war die großartige Firma Vault-Tec der Hersteller des Geräts.}
{195800}{}{Bedienfeld}
{195801}{}{Ein Bedienfeld zur Raumklimaregelung der Firma Vault-Tec. Nichts Besonderes. Abgesehen davon, dass es kaputt ist.}
{195900}{}{Wand}
{196000}{}{Riss}
{196100}{}{Riss}
{196200}{}{Riss}
{196300}{}{Riss}
{196400}{}{Riss}
{196500}{}{Riss}
{196600}{}{Riss}
{196700}{}{Riss}
{196800}{}{Riss}
{196900}{}{Riss}
{197000}{}{Verkohlte menschliche Knochen}
{197100}{}{Verkohlte menschliche Knochen}
{197200}{}{Verkohlte menschliche Knochen}
{197300}{}{Verkohlte menschliche Knochen}
{197400}{}{Verkohlte menschliche Knochen}
{197500}{}{Kleiner Generator}
{197501}{}{Das Standardmodell eines kleinen Stromgenerators von Watts Electronics.}
{197600}{}{Polizeisperre}
{197700}{}{Polizeisperre}
{197800}{}{Polizeisperre}
{197900}{}{Polizeisperre}
{198000}{}{Plakat}
{198001}{}{Das ist ein grelles Propagandaplakat.}
{198100}{}{Plakat}
{198101}{}{Das ist ein grelles Propagandaplakat.}
{198200}{}{Schutzschilde}
{198300}{}{Schutzschilde}
{198400}{}{Schutzschild}
{198500}{}{Schutzschild}
{198600}{}{Verblasstes Bild}
{198601}{}{Das Bild eines Sängers. Offensichtlich ein sehr altes Bild in einem Filzrahmen, das noch gut erhalten ist.}
{198700}{}{Schrotthaufen}
{198701}{}{Kaputte Geräte und anderer Schutt. Wenn du darin wühlst, findest du vielleicht noch etwas Brauchbares.}
{198800}{}{Schrotthaufen}
{198801}{}{Kaputte Geräte und anderer Schutt. Wenn du darin wühlst, findest du vielleicht noch etwas Brauchbares.}
{198900}{}{Wasserstoffbombe}
{199000}{}{Wasserstoffbombe}
{199100}{}{Wasserstoffbombe}
{199200}{}{Wasserstoffbombe}
{199300}{}{Loch}
{199301}{}{Offensichtlich ein von Tieren gegrabenes Loch. Du passt kaum hinein.}
{199400}{}{Werbeplakat}
{199401}{}{Auf diesem Plakat ist noch die Aufschrift zu erkennen: "Preiser Incorporated. Schütze deine Familie, bevor die Bomben fallen!"}
{199500}{}{Werbeplakat}
{199501}{}{Auf diesem Plakat ist noch die Aufschrift zu erkennen: "Preiser Incorporated. Schütze deine Familie, bevor die Bomben fallen!"}
{199600}{}{Werbeplakat}
{199601}{}{Auf diesem Plakat ist noch die Aufschrift zu erkennen: "Preiser Incorporated. Schütze deine Familie, bevor die Bomben fallen!"}
{199700}{}{Motorrad}
{199701}{}{Dieses Motorrad ist völlig verrostet.}
{199800}{}{Zelt}
{199900}{}{Erhängter}
{199901}{}{Man kann es kaum als etwas Gewöhnliches bezeichnen.}
{200000}{}{Baum}
{200100}{}{Berg}
{200101}{}{Diese Bergwände sehen ziemlich unzugänglich aus.}
{200200}{}{Berg}
{200201}{}{Diese Bergwände sehen ziemlich unzugänglich aus.}
{200300}{}{Berg}
{200301}{}{Diese Bergwände sehen ziemlich unzugänglich aus.}
{200400}{}{Berg}
{200401}{}{Diese Bergwände sehen ziemlich unzugänglich aus.}
{200500}{}{Berg}
{200501}{}{Diese Bergwände sehen ziemlich unzugänglich aus.}
{200600}{}{Ausrüstung}
{200601}{}{Dieses Gerät ist mit dem Firmenlogo von Vault-Tec versehen.}
{200700}{}{Leiter}
{200701}{}{Eine alte, etwas wackelige Leiter.}
{200800}{}{Leiter}
{200900}{}{Unregelmäßige Quelle}
{200901}{}{Diese Quelle ist fast ausgetrocknet, aber man kann noch etwas Wasser daraus schöpfen.}
{201000}{}{Einsturz}
{201001}{}{Dieser schreckliche Felssturz kostete einen einheimischen Jäger das Leben.}
{201100}{}{Tisch}
{201101}{}{Dieser Tisch ist mit rohen Organen verschmutzt. Man kann nicht erkennen, ob sie menschlich sind.}
{201200}{}{Gully}
{201201}{}{Robuste Metallluke.}
{201300}{}{Gully}
{201301}{}{Robuste Metallluke.}
{201400}{}{Broc-Blumen}
{201500}{}{Xander-Wurzeln}
{201600}{}{Vocas-Pflanze}
{201700}{}{Beschädigter Generator}
{201701}{}{Ein von Watts Electronics hergestellter Stromgenerator. Dieser hier ist durchgebrannt und kann nicht repariert werden.}
{201800}{}{Radarausrüstung}
{201900}{}{Schreibtisch}
{201901}{}{Ein gewöhnlicher Schreibtisch.}
{202000}{}{Schreibtisch}
{202001}{}{Ein gewöhnlicher Schreibtisch.}
{202100}{}{Schreibtisch}
{202101}{}{Ein gewöhnlicher Schreibtisch.}
{202200}{}{Schreibtisch}
{202201}{}{Ein gewöhnlicher Schreibtisch.}
