#
# Messages for Prototypes
#
# strings
#
{10}{}{<Keine>}

#
# Material Types
#
{100}{}{Glas}
{101}{}{Metall}
{102}{}{Kunststoff}
{103}{}{Holz}
{104}{}{Erde}
{105}{}{Stein}
{106}{}{Zement}
{107}{}{Leder}

#
# Item Types
#
{150}{}{Rüstung}
{151}{}{Behälter}
{152}{}{Chem}
{153}{}{Waffe}
{154}{}{Munition}
{155}{}{Sonstiger Gegenstand}
{156}{}{Schlüssel}

#
# Scenery Types
#
{200}{}{Portal}
{201}{}{Treppe}
{202}{}{Aufzug}
{203}{}{Leiter unten}
{204}{}{Leiter oben}
{205}{}{Allgemeine Kulisse}

#
# Damage Code Types
#
{250}{}{normal}
{251}{}{Laser}
{252}{}{Feuer}
{253}{}{Plasma}
{254}{}{elektrisch}
{255}{}{EMP}
{256}{}{Explosion}

#
# Caliber Types for weapons
#
{300}{}{Keine}
{301}{}{Rakete}
{302}{}{Flammenwerfer-Treibstoff}
{303}{}{C-Energiezelle}
{304}{}{D-Energiezelle}
{305}{}{.223}
{306}{}{5 mm}
{307}{}{.40 cal}
{308}{}{10 mm}
{309}{}{.44 cal}
{310}{}{Energiezelle}
{311}{}{12 Gauge}
{312}{}{9 mm}
{313}{}{Leer 1}
{314}{}{.45 cal}
{315}{}{2 mm}
{316}{}{4,7 mm hülsenlos}
{317}{}{Leer 2}
{318}{}{.30 cal}
{319}{}{40-mm-Granaten}

#
# Race Types
#
{350}{}{Kaukasisch}
{351}{}{Afrikanisch}

#
# Body Types
#
{400}{}{Zweibeiner}
{401}{}{Vierbeiner}
{402}{}{Roboter}
#
# Kill Types names
#
# Note: These were moved to 1450+ to handle new ones!
{450}{}{Männer}
{451}{}{Frauen}
{452}{}{Kinder}
{453}{}{Supermutanten}
{454}{}{Ghule}
{455}{}{Brahmin}
{456}{}{Radskorpione}
{457}{}{Ratten}
{458}{}{Ringwürmer}
{459}{}{Zentauren}
{460}{}{Roboter}
{461}{}{Hunde}
{462}{}{Gottesanbeterinnen}
{463}{}{Todeskrallen}
{464}{}{Pflanze}
#{465}{}{}
#
# Kill type info descriptions
#
{465}{}{Diese Zeile zeigt die Anzahl männlicher Menschen, die du im Laufe deiner Abenteuer getötet hast.}
{466}{}{Diese Zeile zeigt die Anzahl weiblicher Menschen, die du im Laufe deiner Abenteuer getötet hast.}
{467}{}{Diese Zeile zeigt die Anzahl kleiner Menschenkinder, die du im Laufe deiner Abenteuer getötet hast. Du Schuft.}
{468}{}{Die Anzahl der Supermutanten, die du im Laufe deiner Abenteuer getötet hast.}
{469}{}{Diese Zeile zeigt die Anzahl männlicher und weiblicher Ghoulmutanten, die du im Laufe deiner Abenteuer getötet hast.}
{470}{}{Diese Zeile zeigt die Anzahl der Brahmin (mutierten Kühe), die du auf deinen Reisen zerhackt hast.}
{471}{}{Die Anzahl der mutierten Radskorpione, die du auf deinem Abenteuer ins Jenseits befördert hast.}
{472}{}{Die Anzahl der Ratten, die du getötet hast. Dazu zählen alle Mitglieder der Rattenfamilie.}
{473}{}{Die Anzahl mutierter Ringwürmer, die du getötet hast.}
{474}{}{Deine Bilanz getöteter mutierter Zentauren.}
{475}{}{Die Anzahl der Roboter, die du zerstört oder auseinandergenommen hast.}
{476}{}{Die Gesamtzahl der Hunde, die du auf die große Hundewiese im Himmel geschickt hast.}
{477}{}{Diese Zeile zeigt die Gesamtzahl der toten Gottesanbeterinnen oder großen mutierten, gottesanbeterinnenartigen Insekten, die du bisher zerquetscht hast.}
{478}{}{Diese Zeile zeigt, dass du den Deathclaw und all seine Nachkommen getötet hast.}
{479}{}{Die Anzahl der Pflanzen, deren Streben nach Sonnenlicht du unterbrochen hast.}

#
# Use text
#
{480}{}{Du siehst: %s.}

#
# Use Container text
#
{485}{}{Du durchsuchst %s.}
{486}{}{Du schließt %s.}
{487}{}{Es ist verschlossen.} # new

#
# Look text
#
{490}{}{Du siehst: %s.}
{491}{}{Du siehst einen toten: %s.}
{492}{}{Du siehst die Überreste von: %s.}
{493}{}{Du siehst nichts Ungewöhnliches.}

#
# Examine text
#
{500}{}{Tot}
{501}{}{Fast tot}
{502}{}{Schwer verwundet}
{503}{}{Verwundet}
{504}{}{Unverletzt}

#
# Examine text messages
#
{510}{}{RK-Mod: %d}
{511}{}{SR-Mod: %d}
{512}{}{Schadensmod: %d/%d}
{518}{}{Du siehst aus: %s }
{519}{}{%s %s }
{520}{}{Du siehst aus: %s.}
{521}{}{%s %s.}
{522}{}{Er sieht aus: %s }
{523}{}{Sie sieht aus: %s }
{524}{}{Es sieht aus: %s }
# (note: hps are short for hit-points)
{525}{}{%s hat %d/%d TP.}
# (note: this is for guns that have ammo)
{526}{}{Es hat noch %d/%d Schuss %s.}
{530}{}{und hat verkrüppelte Gliedmaßen.}  # These append to lines 500-504
{531}{}{aber hat verkrüppelte Gliedmaßen.}
{532}{}{und haben verkrüppelte Gliedmaßen.}
{533}{}{aber haben verkrüppelte Gliedmaßen.}
# (note: hps are short for hit-points)
{535}{}{Er hat %d/%d TP}
{536}{}{Sie hat %d/%d TP}
{537}{}{Es hat %d/%d TP}
{540}{}{Es wiegt %d Pfund.}
{541}{}{Es wiegt %d Pfund.}
{544}{}{, }
{545}{}{.}
{546}{}{ und trägt eine %s.}
{547}{}{ und trägt eine %s mit %d/%d Schuss %s.}
{548}{}{Das Auto scheint gerade nicht richtig zu funktionieren.}
{549}{}{Das Auto läuft mit %d%% Leistung.}

#
# Examine text error messages
#
{550}{}{\nFehler: lookup_val außerhalb des gültigen Bereichs!}
{551}{}{\nFehler: obj_examine: proto_ptr fehlgeschlagen!}

#
# Use text messages
#
{580}{}{Du benutzt %s.}
{581}{}{Du benutzt %s auf %s.}
{582}{}{Das bewirkt nichts.}
{583}{}{Zu deinem Entsetzen stellst du fest, dass es bereits tot ist.}
{584}{}{Als du dich hinunterbeugst, stellst du fest, dass es bereits tot ist.}
{585}{}{Ach, du bist zu spät.} # This is relating to a critter being dead.
{586}{}{Das funktioniert bei Toten nicht.}
{587}{}{Du zündest die Leuchtfackel an.}
{588}{}{Die Leuchtfackel brennt bereits.}
{589}{}{Du stellst den Timer ein.}
{590}{}{Der Timer läuft bereits!}
{595}{}{Du versorgst das Auto mit mehr Energie.}
{596}{}{Das Auto ist bereits voll aufgeladen.}
{597}{}{Der Durchgang scheint versperrt zu sein.}

#
# Experience-Point messages
#
{620}{}{Du erhältst %d Erfahrungspunkte für den Tod von: %s.}
{621}{}{%s du erhältst %d Erfahrungspunkte.}
{622}{}{Für den Sieg über deine Feinde, }  # 622-626 prepend to line 621
{623}{}{Für das Erschlagen deiner Gegner, }
{624}{}{Du bist siegreich aus dem Kampf hervorgegangen, }
{625}{}{Für das Zerschmettern deiner Feinde, }
{626}{}{Für die Vernichtung deiner Feinde, ohne einen Kratzer abzubekommen, }

#
# Dialog messages
#
{650}{}{[Fertig]}
{651}{}{[Mehr]}
{652}{}{Mehr}
{653}{}{[Zurück]}
{654}{}{Zurück}     # changed number from 653
{655}{}{Weiter}    # new
{656}{}{Äh ...}   # new
{660}{}{Du kannst dort nichts sehen.}
{661}{}{Zu weit weg.}
{670}{}{In Ordnung.}    # F2: Used in PM: CombatAI settings
{671}{}{Klar.}    # F2: Used in PM: CombatAI settings
{672}{}{Wie du willst.}       # F2: Used in PM: CombatAI settings
{673}{}{Wie du meinst.}  # F2: Used in PM: CombatAI settings
{674}{}{Ich versuch's.}          # F2: Used in PM: CombatAI settings
{675}{}{Das kann ich nicht.}   # F2: Used in PM: CombatAI settings
{676}{}{Ich glaube nicht, dass ich das kann.}   # F2: Used in PM: CombatAI settings
{677}{}{Wuff!}   # F2: Used in PM: CombatAI settings -- RoboDog
{678}{}{Wuff!}  # F2: Used in PM: CombatAI settings -- RoboDog

#
# Not Enough AP message
#
{700}{}{Du hast nicht genug Aktionspunkte.}
#
# Book messages
#
{800}{}{Du liest das Buch.}
{801}{}{Du lernst nichts Neues.}
{802}{}{Du lernst neue wissenschaftliche Erkenntnisse.}
{803}{}{Du lernst viel über die Reparatur kaputter Elektronik.}
{804}{}{Du lernst neue Möglichkeiten, Verletzungen zu heilen.}
{805}{}{Du lernst, besser mit deinen Waffen umzugehen.}
{806}{}{Du lernst eine Menge über das Überleben in der Wildnis.}
#
# Use on messages (and some extra stuff that Jesse needed)
#
{900}{}{Die Vorräte im Arztbeutel sind aufgebraucht.}
{901}{}{Die Vorräte im Erste-Hilfe-Kasten sind aufgebraucht.}
{902}{}{Das kannst du im Kampf nicht tun.}
{903}{}{Diese Person handelt nicht mit dir.}
{904}{}{Diese Person hat dir nichts zu erzählen.}
{905}{}{Du kannst diesen Gegenstand nicht aufnehmen. Du hast dein maximales Tragegewicht erreicht.}
{910}{}{Die Vorräte in der Sanitätstasche sind aufgebraucht.}
{911}{}{Die Vorräte im Erste-Hilfe-Kasten für Feldsanitäter sind aufgebraucht.}
{913}{}{Dieses Viech kann nichts tragen.}


#
# Kill Types names
#
{1450}{}{Männer}
{1451}{}{Frauen}
{1452}{}{Kinder}
{1453}{}{Supermutanten}
{1454}{}{Ghule}
{1455}{}{Brahmin}
{1456}{}{Radskorpione}
{1457}{}{Ratten}
{1458}{}{Ringwürmer}
{1459}{}{Zentauren}
{1460}{}{Roboter}
{1461}{}{Hunde}
{1462}{}{Gottesanbeterinnen}
{1463}{}{Todeskrallen}
{1464}{}{Pflanzen}
{1465}{}{Geckos}
{1466}{}{Aliens}
{1467}{}{Riesenameisen}
{1468}{}{Großer böser Boss}
#
# Kill type info descriptions
#
{1469}{}{Diese Zeile zeigt die Anzahl männlicher Menschen, die du im Laufe deiner Abenteuer getötet hast.}
{1470}{}{Diese Zeile zeigt die Anzahl weiblicher Menschen, die du im Laufe deiner Abenteuer getötet hast.}
{1471}{}{Diese Zeile zeigt die Anzahl kleiner Menschenkinder, die du im Laufe deiner Abenteuer getötet hast. Du Schuft.}
{1472}{}{Die Anzahl der Supermutanten, die du im Laufe deiner Abenteuer getötet hast.}
{1473}{}{Diese Zeile zeigt die Anzahl männlicher und weiblicher Ghoulmutanten, die du im Laufe deiner Abenteuer getötet hast.}
{1474}{}{Diese Zeile zeigt die Anzahl der Brahmin (mutierten Kühe), die du auf deinen Reisen zerhackt hast.}
{1475}{}{Die Anzahl der mutierten Radskorpione, die du auf deinem Abenteuer ins Jenseits befördert hast.}
{1476}{}{Die Anzahl der Ratten, die du getötet hast. Dazu zählen alle Mitglieder der Rattenfamilie.}
{1477}{}{Die Anzahl mutierter Ringwürmer, die du getötet hast.}
{1478}{}{Deine Bilanz getöteter mutierter Zentauren.}
{1479}{}{Die Anzahl der Roboter, die du zerstört oder auseinandergenommen hast.}
{1480}{}{Die Gesamtzahl der Hunde, die du auf die große Hundewiese im Himmel geschickt hast.}
{1481}{}{Diese Zeile zeigt die Gesamtzahl der toten Gottesanbeterinnen oder großen mutierten, gottesanbeterinnenartigen Insekten, die du bisher zerquetscht hast.}
{1482}{}{Diese Zeile zeigt, dass du den Deathclaw und all seine Nachkommen getötet hast.}
{1483}{}{Diese Zeile zeigt, wie viele Pflanzen du aus der Welt geschafft hast.}
{1484}{}{Die Anzahl der niedlichen Echsen, die du vom Antlitz des Planeten getilgt hast.}
{1485}{}{Die Anzahl der in Area 51 gezüchteten Kreaturen, die du eigenhändig getötet hast.}
{1486}{}{Die Anzahl der Insektoiden, die du im Ödland ausgerottet hast.}
{1487}{}{Die Anzahl der größten und berüchtigtsten Mistkerle im Ödland, die du zur Hölle geschickt hast.}