#---------------------------------------------------------
#                QUEST DESCRIPTION IN PIP-BOY
# (êàæäûé íîâûé ðàçäåë íà÷èíàòü ñ 100 è êðàòíûõ åìó ÷èñåë)
#---------------------------------------------------------



#---------------------------------------------------------
# Vault 8
#---------------------------------------------------------

{100}{}{Hol das Gerät zurück, das vom Biker gestohlen wurde}
{101}{}{Verfolge die Entführer des Aufsehers}
{102}{}{Erfuelle deinen Auftrag im Regierungsbunker}
{103}{}{}
{104}{}{}
{105}{}{Erledige den Sonderauftrag des Lagerhauses}
{106}{}{Bring Sam ein Pornomagazin}
{107}{}{Finde den vermissten Spähroboter}
{108}{}{Entschlüssle die Diskette des Hilfssheriffs}
{109}{}{Finde mehr über Gerlachs Gemeinschaft heraus}
{110}{}{Zerstöre Gerlachs Gemeinschaft}
{111}{}{Bespitzle ein „verdächtiges“ Bürgerpaar}
{112}{}{Sammle Blutproben von Schweineratten, Kojoten und Geckos für Doktor Willmouth}

{120}{}{Komm wieder auf die Beine: Sprich mit Graves und Willmouth und hol deine Ausrüstung aus dem Lagerhaus}
{121}{}{Bikerjagd: Finde mehr über Jay in Black Rock heraus}
{122}{}{Bikerjagd: Finde mehr über Jay in New Reno heraus}
{123}{}{Bikerjagd: Nimm Kontakt zur Bikergang auf}
{124}{}{Bikerjagd: Erhalte in Hawthorne eine Nachricht}
{125}{}{Bikerjagd: Finde Jay in Hawthorne}
{126}{}{Besorg dir einen Signalstörer in Hawthorne}
{127}{}{Werde den Peilsender in deinem Pip-Boy los}
{128}{}{Entlarve Doktor Willmouth}
{129}{}{Finde in Area 51 Informationen über Projekt Vault 8}
{130}{}{}
{131}{}{}
{132}{}{}
{133}{}{}
{134}{}{Finde den wahren Zweck von Vault 8 heraus}
{135}{}{Spreng den Regierungsbunker in die Luft}

#---------------------------------------------------------
# Wind of War
#---------------------------------------------------------

{200}{}{Kümmere dich um die örtlichen Schläger, die dich angegriffen haben}
{201}{}{Der Quartiermeister hat 30 Flaschen Bier bestellt}
{202}{}{Hilf dem Gefangenen bei der Flucht}
{203}{}{Robert und Jessica wollen aus der Siedlung fliehen}
{204}{}{Finde in Hawthorne Informationen über das Denkmal}
{205}{}{Bestrafe die Soldaten, die den Karawanenhändler verprügelt haben}
{206}{}{Finde Überlebende der Karawane „Speed Hawk“}
{207}{}{Kopiere die Funkfrequenzen für den Spion oder verrate ihn dem Militär}
{208}{}{Untersuche den Vorfall am Außenposten und erstatte Wesker Bericht}
{209}{}{Gewinne das Vertrauen des Farmers zurück}

#---------------------------------------------------------
# Gerlach
#---------------------------------------------------------

{300}{}{Repariere die Wasserpumpe}
{301}{}{Rette Steve vor der Hinrichtung}
{302}{}{Zieh nach Vault City}
{303}{}{Geckojagd: Die Prüfung}
{304}{}{Geckojagd: Eiersuche}
{305}{}{Jage den legendären Skorpion}

#---------------------------------------------------------
# Black Rock
#---------------------------------------------------------

{306}{}{Rette die Gemeinde vor der "Ansteckung"}
{307}{}{Kümmere dich um entlaufene Sklaven}
{308}{}{Untersuche das Verschwinden des Brahmins}
{309}{}{Untersuche das Verschwinden des Lieferanten}

#---------------------------------------------------------
# Lovelock
#---------------------------------------------------------

{400}{}{Vernichte die Raider, die den Cheyenne-Stamm terrorisieren}
{401}{}{Schalte Big Louie aus}
{402}{}{Besiege Makozid im Faustkampf}
{403}{}{Ogima bittet dich, den Wassertank zu reparieren}
{404}{}{Befreie die Plantage von fleischfressenden Pflanzen}
{405}{}{"Hilf" Mold, dem Drogensüchtigen}
{406}{}{Gib Niskigvan seine Habseligkeiten zurück, die ihm ein Raider namens Furiouser abgenommen hat}
{407}{}{Acabidab bittet dich, Gizhiyash in New Reno zu finden}
{408}{}{Finde einen Weg, den armen Makkon zu heilen}

{410}{}{Louie: Finde einen Weg nach Hawthorne}
{411}{}{Louie: Kassiere die Maut von Stryker und bring sie ihm}
{412}{}{Louie: Töte den Verräter Balder}
{413}{}{Louie: Räche dich an Solomon, dem Drogendealer in New Reno}
{414}{}{Louie: Halte den Drogenkurier aus Vegas auf}
{415}{}{Louie: Organisiere die Show in Vegas}

#---------------------------------------------------------
# Ïîìîùü ïðè íàæàòèè F1
#---------------------------------------------------------

{500}{}{[SPIEL]}
{501}{}{- Helligkeit verringern}
{502}{}{+ Helligkeit erhöhen}
{503}{}{F1 Hilfe}
{504}{}{F2 Lautstärke verringern}
{505}{}{F3 Lautstärke erhöhen}
{506}{}{F4 Spiel speichern}
{507}{}{F5 Spiel laden}
{508}{}{F6 Schnell speichern}
{509}{}{F7 Schnell laden}
{510}{}{F10 Spiel beenden}
{511}{}{F12 Screenshot aufnehmen}
{512}{}{Ctrl+P Pause}
{513}{}{Ctrl+R Testmodus im Hauptmenü}

{514}{}{[INTERFACE]}
{515}{}{LMT/RMT Cursor wechseln}
{516}{}{O/Esc Einstellungen}
{517}{}{P Pip-Boy}
{518}{}{Z Uhr im Pip-Boy}
{519}{}{I Rucksack}
{520}{}{Tab Umgebungskarte}

{521}{}{[AKTIONEN]}
{522}{}{A Kampf beginnen}
{523}{}{Space Zug im Kampf beenden}
{524}{}{Enter Kampf beenden}
{525}{}{B Gegenstand wechseln}
{526}{}{N Gegenstandsmodus wechseln}
{527}{}{< Im Uhrzeigersinn drehen}
{528}{}{> Gegen den Uhrzeigersinn drehen}
{529}{}{Home Bildschirm auf den Helden zentrieren}

{530}{}{[FÄHIGKEITEN]}
{531}{}{S Fähigkeitsübersicht}
{532}{}{1 Schleichen}
{533}{}{2 Schlösser knacken}
{534}{}{3 Taschendiebstahl}
{535}{}{4 Sprengstoff}
{536}{}{5 Erste Hilfe}
{537}{}{6 Arzt}
{538}{}{7 Wissenschaft}
{539}{}{8 Reparieren}

#---------------------------------------------------------
# NPP Poseidon Oil
#---------------------------------------------------------

{600}{}{}

#---------------------------------------------------------
# Ailey settlement
#---------------------------------------------------------

{700}{}{}

#---------------------------------------------------------
# New Reno
#---------------------------------------------------------

{800}{}{Patrick bittet darum, Itchie zu heilen}
{801}{}{Patrick bittet darum, das Paket zurückzubringen}
{802}{}{Patrick braucht Hilfe bei der Organisation einer Filmvorführung}
{803}{}{Hilf Harding mit seinen Leiden}
{804}{}{Begleiche die Schulden von Mrs. Clover}
{805}{}{Finde die verschwundenen Goldsucher aus den Slums}
{806}{}{Finde den Graffiti-Sprayer und bestrafe ihn}
{807}{}{Bring Ted Bundy zur Rechenschaft}
{808}{}{Löse das Rätsel um Ted Bundys Foto}
{809}{}{Bestrafe die Möchtegern-Biker}
{810}{}{Finde die Quelle der üblen Gerüchte über die Biker}
{811}{}{Werde zum legendären Champion des Rings von New Reno}
{812}{}{Werde ein Star in New Reno}
{813}{}{Erledige Solomons schmutzigen Auftrag}
{814}{}{Bring einen Komiker aus Vegas zum „Cotton“-Club}
{815}{}{Triff Nick Hauer im Hotel „Silver“}
{816}{}{Organisiere die Flucht der Familie Deveraux aus der Stadt}
{817}{}{Installiere Wanzen im Casino „Eldorado“}
{818}{}{Beschaffe Informationen über Lebensmittellieferungen}

{820}{}{Wright: Erkunde die Lage in Uranium City}
{821}{}{Wright: Erledige die C-4-Lieferung}
{822}{}{Wright: Erobere die Mine von den Konkurrenten zurück}
{823}{}{Wright: Spüre einen seltsamen Typen in den Slums auf}
{824}{}{Wright: Triff dich mit Oliver Luciano}
{825}{}{Bertolini: Triff den Informanten auf der Ranch}
{826}{}{Bertolini: Bring das Restaurant gegen die Ranch auf}
{827}{}{Bertolini: Schalte Luciano aus dem Geschäft aus, ohne ihn zu töten}
{828}{}{Bertolini: Luciano Unterstützung anbieten}
{829}{}{Bertolini: Huey folgen}
{830}{}{Luciano: Johnny Chase helfen}
{831}{}{Luciano: dem Casino „Eldorado“ etwas anhängen}
{832}{}{Luciano: dem Casino „Eldorado“ etwas anhängen (2)}
{833}{}{Luciano: Bertolini einen Geldkoffer stehlen}
{834}{}{Luciano: einen Konflikt zwischen Gangstern provozieren}
{835}{}{Luciano: am Stadtrand ein geheimes Geschäft abschließen}
{836}{}{Stryker: Patrick den Mormonen ausschalten}
{837}{}{Stryker: Chemikalien vom Dealer besorgen}
{838}{}{Stryker: Informationen in Thompsons Hauptquartier sammeln}
{839}{}{Stryker: Betty Page ausschalten}
{840}{}{Stryker: den Angriff auf Thompson vorbereiten}
{841}{}{Thompson: Straßenschläger bestrafen}
{842}{}{Thompson: den Angriff auf das Propagandateam untersuchen}
{843}{}{Thompson: Mordino zur Zusammenarbeit überreden}
{844}{}{Thompson: Strikers Geschäft sabotieren}
{845}{}{Thompson: den Angriff auf Stryker vorbereiten}

#---------------------------------------------------------
# Bridgeport
#---------------------------------------------------------

{900}{}{Dante helfen, die Herausforderungen zu meistern (Waffe und Schmerzmittel benötigt)}
{901}{}{Dante davon überzeugen, sich der Bikergang nicht anzuschließen}
{902}{}{Brahmin in den Pferch treiben}
{903}{}{Das Kind selbst heilen oder medizinische Vorräte besorgen}
{904}{}{Beim Ausrüsten der Karawane von New Reno nach Bridgeport helfen}
{905}{}{Den vermissten Einwohner finden}
{906}{}{Die Stromversorgung wiederherstellen}
{907}{}{Das Dorf von der Bikergang befreien}
{908}{}{}
{909}{}{}

#---------------------------------------------------------
# Vegas
#---------------------------------------------------------

{1100}{}{Auf Bitte des Bürgermeisters die jüngsten Verbrechen in der Stadt untersuchen}
{1101}{}{Die vermisste Tochter des Archivars finden}
{1102}{}{Sam Phillips wird beschuldigt, Gift verbreitet zu haben}
{1103}{}{Der Polizei helfen, Sam Phillips ins Gefängnis zu bringen}
{1104}{}{Beweise für die Unschuld der Freaks finden}
{1105}{}{Bei der Verbannung der Freaks helfen}
{1106}{}{Den Freaks heimlich Drogen im Hotel unterschieben}
{1107}{}{Wallace Bob Neils persönliche Waffe besorgen}
{1108}{}{Bob Neil hat ein Gegenangebot gemacht}
{1109}{}{Das Problem mit den Arbeitern am Hoover-Damm lösen}
{1110}{}{Den Angriff auf die Karawane „Speed Hawk“ untersuchen}
{1111}{}{Hilf den Sklaven, aus dem Pferch zu entkommen}
{1112}{}{Übergib die Schwarze Karawane der Polizei}
{1113}{}{Hilf der Polizei, den Pound zu stürmen}
{1114}{}{Werde zum legendären Ringchampion in Vegas}
{1115}{}{Dringe ins Drogenlabor von Vegas ein}
{1116}{}{Eric bittet dich, seinen Bruder aus dem Gefängnis zu holen}
{1117}{}{Pizzalieferung: Casino, Laden und Ring}
{1118}{}{Begleiche die Schulden des Diebs Kevin}
{1119}{}{Orris bat dich, Murphys Problem zu lösen}

#---------------------------------------------------------
# Salt Lake
#---------------------------------------------------------

{1500}{}{Repariere den Bordcomputer des Zuges}
{1501}{}{Für den Zugbetrieb wird ein Maschinist benötigt}
{1502}{}{Der Artesian Tower braucht einen Wasserfilter}
{1503}{}{Fall des vermissten Hundes}
{1504}{}{Kümmere dich um Marks Problem}
{1505}{}{Führe den „Raub des Jahrhunderts“ in Salt Lake aus}
{1506}{}{Hilf dem Bettler, Arbeit zu finden}
{1507}{}{Besorge eine Lizenz für den Verkauf von Nuka-Cola}
{1508}{}{Sorge für Ablenkung in der Nuka-Cola-Fabrik}
{1509}{}{Nuka-Cola: Schließe einen Handel mit dem Club „Cotton“ ab}
{1510}{}{Nuka-Cola: Schließe einen Handel mit dem Restaurant „Silver“ ab}
{1511}{}{Nuka-Cola: Schließe einen Handel mit dem Café „Hard Rock“ ab}
{1512}{}{Nuka-Cola: Schließe einen Handel mit dem Wind of War ab}
{1513}{}{Repariere den automatischen Logikcontroller der Nuka-Cola-Fabrik}
{1514}{}{Kümmere dich um den Nuka-Cola-Händler}
{1515}{}{Sorge dafür, dass Gary Gilmore seiner gerechten Strafe zugeführt wird}
{1516}{}{Metzle die Bevölkerung von Provo nieder}
{1517}{}{Töte auf Bitte von Provo den Sheriff von Salt Lake City}
{1518}{}{Gib die Schlüssel zur Nuka-Cola-Fabrik zurück}
{1519}{}{Nimm dem Karawanenhändler um jeden Preis den Encoder ab}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{1600}{}{}

#---------------------------------------------------------
# Government Vault
#---------------------------------------------------------

{1700}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{1800}{}{}

#---------------------------------------------------------
# Uranium City
#---------------------------------------------------------

{1900}{}{Beseitige die Mutanten in Uranium City}
{1901}{}{Wechsle den Minenbesitzer aus}
{1902}{}{Hol die Arbeiter nach Uranium City zurück: Verwalter}
{1903}{}{Hol die Arbeiter nach Uranium City zurück: Maschinenführer}
{1904}{}{Hol die Arbeiter nach Uranium City zurück: Zulieferer}
{1905}{}{Hol die Arbeiter nach Uranium City zurück: Kabaretttänzerin}
{1906}{}{Kurierlieferung von Lewis Birchs Bericht}
{1907}{}{Werde Sheriff von Uranium City}
{1908}{}{Carl bittet dich, eine Sicherung zu finden}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2000}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2100}{}{}

#---------------------------------------------------------
# Car outta Gas Quests
#---------------------------------------------------------

{2200}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2300}{}{}

#---------------------------------------------------------
# Provo
#---------------------------------------------------------

{2400}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2500}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------

{2600}{}{}

#---------------------------------------------------------
# Desert Encounter Quests
{2700}{}{}

# Mountain Encounter Quests
{2800}{}{}

# Ruined City Encounter Quests
{2900}{}{}

# Coast Encounter Quests
{3000}{}{}

#---------------------------------------------------------
# Reserv
#---------------------------------------------------------
{3200}{}{}

#---------------------------------------------------------
# Car
#---------------------------------------------------------

{3300}{}{Besorge dir ein eigenes Auto}
{3301}{}{Den Pickup mit Upgrades aus dem „Chryslus Motors“-Katalog verbessern}
{3302}{}{Die Karosserie des Pickups neu lackieren}
{3303}{}{Den Kofferraum vergrößern und verstärken}
{3304}{}{„Gravi-Platten“ einbauen}
{3305}{}{Den Stromverbrauch mit einem Treibstoffregler senken}
{3306}{}{Die Höchstgeschwindigkeit des Pickups mithilfe eines Bikers in Battle Mountain erhöhen}
{3307}{}{Die Scheinwerfer des Pickups reparieren}
{3308}{}{Einen Anhalter nach Vegas mitnehmen}
