#
#
#
#
#
{0}{}{Spieleinstellungen}
{1}{}{Bildschirmeinstellungen}



{50}{}{Bildschirmeinstellungen}
{51}{}{Benutzerdefiniert}
{52}{}{Breite}
{53}{}{Höhe}
{54}{}{Fertig}
{55}{}{Abbrechen}
{56}{}{Fallout muss neu gestartet werden, um die Einstellungen zu übernehmen.}
{57}{}{Möchtest du Fallout jetzt neu starten?}
{58}{}{Wahr}
{59}{}{Falsch}
{60}{}{}

{100}{}{Hohe Auflösung}
{101}{}{AUFLÖSUNG}
{102}{}{Farben}
{103}{}{8 Bit}
{104}{}{16 Bit}
{105}{}{32 Bit}
{106}{}{Seitenleisten-Grafik ändern}
{107}{}{Liste umkehren}
{108}{}{Fenstermodus}
{109}{}{Scrolltaste festlegen}
{110}{}{Skalierung X2}
{111}{}{Bildwiederholrate}

{130}{}{Fenstertaste}
{131}{}{Auswählen}
{132}{}{Name}

{140}{}{Grafikmodus:}
{141}{}{Einfach}
{142}{}{Sfall-DirectX-9-Modus:}
{143}{}{}

{144}{}{DirectDraw 7}
{145}{}{}
{146}{}{}

{147}{}{Direct3D 9}
{148}{}{Hardware-Vertexverarbeitung:}
{149}{}{Shader-Version 2.0:}

{150}{}{Panel-Skalierung}
{151}{}{Keine}
{152}{}{Anpassen}
{153}{}{Ausfuellen}

{154}{}{Videos}
{155}{}{Startbild}
{156}{}{Hilfe}
{157}{}{Tod}
{158}{}{Abspannbilder}
{159}{}{Hauptmenü}


{200}{}{Sfall}
{201}{}{SKALIEREN AUF: AUFL.}
{202}{}{DX-9-MODUS}
{203}{}{Aus}
{204}{}{Vollbild}
{205}{}{Fenster}
{206}{}{GPU-Blitting}
{207}{}{Diese Einstellung hat im einfachen Grafikmodus keine Wirkung.}

{250}{}{PC-Scrollbegrenzung ignorieren}
{253}{}{Pfadfindungsreichweite}
{254}{}{Normal}
{255}{}{Max.}
{256}{}{Nebel des Krieges aktivieren}
{257}{}{Sichtweite im Nebel}
{258}{}{Dunkel}
{259}{}{Heller}

{300}{}{DRÜCKE EINE TASTE oder ESC zum Abbrechen.}

{500}{}{Einstellungen des Hi-Res-Patches.}
{501}{}{Bildschirmauflösung, Farbmodus und Bildwiederholrate für den Vollbildmodus einstellen.}
{502}{}{Hier die Vollbild-Farbausgabe einstellen.}
{503}{}{Hier die Bildwiederholrate für den Vollbildmodus einstellen. Auf „0“ setzen, um die Standardeinstellung des Treibers zu verwenden.}
{504}{}{Passe die Vollbildbreite an, indem du auf das Zahlenfeld klickst.}
{505}{}{Passe die Vollbildhöhe an, indem du auf das Zahlenfeld klickst.}
{506}{}{Fenstermodus ein- oder ausschalten.}
{507}{}{Im Fenstermodus hältst du diese Taste gedrückt, um die Spiel- und Weltkarten mit der Maus zu verschieben.}
{508}{}{Drücke die rote Schaltfläche, um eine andere Taste auszuwählen. Oder klicke auf das Zahlenfeld, um den virtuellen Windows-Tastencode zu bearbeiten.}
{509}{}{Der Name der derzeit ausgewählten Taste.}
{510}{}{X2-Skalierung aktivieren. Dadurch wird auch die Mindestauflösung auf 1280x960 erhöht. Der Fenstermodus benötigt mehr Platz für seinen Rahmen.}
{511}{}{Nebel des Krieges ein- oder ausschalten. Für optimale Ergebnisse sollte diese Option aktiviert sein, bevor du eine Karte zum ersten Mal betrittst.}
{512}{}{Passe die Helligkeit und die Sichtbarkeit von Böden, Wänden und Kulissen unter dem Nebel beim Anzeigen mit der Maus an.}
{513}{}{Böden, Wände und Kulissen sind immer sichtbar, und „Mit der Maus ansehen“ funktioniert wie gewohnt.}
{514}{}{Böden, Wände und Kulissen werden abgedunkelt und können mit „Mit der Maus ansehen“ erst betrachtet werden, wenn sie entdeckt wurden.}
{515}{}{Wenn diese Option aktiviert ist, kannst du dich unbegrenzt weit von der Spielfigur wegbewegen. Das funktioniert gut, wenn der Nebel des Krieges aktiviert ist.}
{516}{}{Erhöhe die Anzahl der Suchknoten, um die Reichweite der Pfadsuche zu vergrößern. 20 Stufen in Schritten von 2000 Knoten.}
{517}{}{2000 Pfadsuchknoten (Originalwert). Hinweis: Jede Stufe benötigt zusätzlich 156,25 KB Speicher.}
{518}{}{40.000 Pfadsuchknoten. Hinweis: Benötigt 3.200.000 Byte (3125 KB) Speicher.}
{519}{}{Passe die Anzeige bestimmter Bildschirme an.}
{520}{}{Originalgröße.}
{521}{}{Auf Bildschirmgröße gestreckt, wobei das ursprüngliche Seitenverhältnis erhalten bleibt.}
{522}{}{Auf Bildschirmgröße gestreckt. Hinweis: Wenn Untertitel aktiviert sind, bleibt am unteren Bildschirmrand ein freier Bereich.}
{523}{}{Klicke unten, um die Optionen für die Seitenleiste der Spieloberfläche durchzuschalten.}
{524}{}{Änderungen übernehmen und beenden.}
{525}{}{Beenden, ohne zu speichern.}


