{101}{}{}
{102}{}{Skripttest 0}
{103}{}{Skripttest 1}
{104}{}{Skripttest 2}
{105}{}{Skripttest 3}
{106}{}{Skripttest 4}
{107}{}{Skripttest 5}
{108}{}{Wache}
{109}{}{Bürger}
{110}{}{Radioaktive Zone}
{111}{}{Peter Graves}
{112}{}{Dr. Willmouth}
{113}{}{Tür}   
{114}{}{Allgemein}
{115}{}{Kind}
{116}{}{Behälter}
{117}{}{Kassierer}
{118}{}{Nachricht}
{119}{}{Mutant}
{120}{}{Skorpion}
{121}{}{Gottesanbeterin}
{122}{}{Deathclaw}
{123}{}{Tür}
{124}{}{Gegenstände auf einem Tisch}
{125}{}{}
{126}{}{Holztür}
{127}{}{}
{128}{}{}
{129}{}{Schrott}
{130}{}{Bodenplatte}
{131}{}{Bodenplatte}
{132}{}{Bodenplatte}
{133}{}{Bodenplatte}
{134}{}{Generator}
{135}{}{Roboter}
{136}{}{Begrüßer}
{137}{}{Kasino-Wache}
{138}{}{Koch}
{139}{}{Militär}
{140}{}{Militär}
{141}{}{Kunde}
{142}{}{Besucher}
{143}{}{Leibwächter}
{144}{}{Biker}
{145}{}{Spieler}
{146}{}{Oscar Davis}
{147}{}{Ausbilder}
{148}{}{Fenster}
{149}{}{Behälter}
{150}{}{Partner}
{151}{}{Agent}
{152}{}{Rico}
{153}{}{Junge}
{154}{}{Suzy}
{155}{}{Paul Tibbett}
{156}{}{Dorfbewohner}
{157}{}{Sklavenmarkt} 
{158}{}{Sklavenkarren}
{159}{}{}
{160}{}{}
{161}{}{}
{162}{}{}
{163}{}{Statue}
{164}{}{Abstieg}
{165}{}{Platz für einen Käfer}
{166}{}{Tagebuch}
{167}{}{Terminal}
{168}{}{Nachricht}
{169}{}{Grab}         
{170}{}{Black Jack}
{171}{}{Sklave}
{172}{}{Black Jack}
{173}{}{Nachricht}
{174}{}{Evan}
{175}{}{Würfelspiel}
{176}{}{Steve}
{177}{}{Mitglied der Gemeinschaft}
{178}{}{Gerlach}
{179}{}{Evan}
{180}{}{Gizhiyash}
{181}{}{Metzger}
{182}{}{Sklave}
{183}{}{Bürger}
{184}{}{Wache}
{185}{}{Kiste}
{186}{}{Kiste}
{187}{}{Kiste}
{188}{}{Bürger}
{189}{}{Computer}
{190}{}{Bürger}
{191}{}{Bürger}
{192}{}{Computer}
{193}{}{Diener}
{194}{}{Karawanenhändler}
{195}{}{Spieler}
{196}{}{Wache}
{197}{}{Avanigizhig der neblige Tag}
{198}{}{Big Louie}
{199}{}{Wassertank}
{200}{}{Fatso Jackson}
{201}{}{Niskigvan mit den zerzausten Federn}
{202}{}{Ogima der Black Cloud}
{203}{}{Kind}
{204}{}{Kämpfer}
{205}{}{Gekek der Falke}
{206}{}{Wand}
{207}{}{Brahmin}
{208}{}{Omakaki}
{209}{}{Hal Wallace}
{210}{}{Verwalter der Postkutsche}
{211}{}{Karawanenhändler}
{212}{}{Palette}
{213}{}{Rowdy}
{214}{}{Spielautomat}
{215}{}{Unzureichender Kunde}
{216}{}{Depressiver Kunde}
{217}{}{Intelligenter Bettler}
{218}{}{Spielautomat}
{219}{}{Computer}
{220}{}{Vergiftetes Gebiet}
{221}{}{Bürger}
{222}{}{Bürger}
{223}{}{Zielscheibe}
{224}{}{Vault-Bewohner}
{225}{}{Leibwächter}
{226}{}{Huey}
{227}{}{Denunziant}
{228}{}{Lynette}
{229}{}{Huey}
{230}{}{Gecko}
{231}{}{John Williamson}
{232}{}{Casino-Gast}
{233}{}{}
{234}{}{Schalttafel}
{235}{}{Tür}
{236}{}{Barkeeper}
{237}{}{Diesel}
{238}{}{Karawanenhändler}
{239}{}{Big Louie}
{240}{}{Tränke}
{241}{}{Wand}
{242}{}{Räuber}
{243}{}{Konsoleneingabe}
{244}{}{Seil}
{245}{}{Echsenjäger}
{246}{}{}
{247}{}{}
{248}{}{}
{249}{}{Köter}
{250}{}{Wache}
{251}{}{Holodisk}
{252}{}{Holodisk}
{253}{}{Holodisk}
{254}{}{Computer}
{255}{}{Terminal}
{256}{}{Computer}
{257}{}{Computer}
{258}{}{Terminal}
{259}{}{Geschützturmsteuerung}
{260}{}{Computer}
{261}{}{Fernbedienung}
{262}{}{Monitore}
{263}{}{Generator}
{264}{}{Generator}
{265}{}{Papier}
{266}{}{Sergeant Graves}
{267}{}{Gehirn-Bot}
{268}{}{Aufzug}
{269}{}{Aufzug}
{270}{}{Warenkiste}
{271}{}{Spind}
{272}{}{Tandi}
{273}{}{Falle}
{274}{}{Evakuierungspunkt}
{275}{}{Falle}
{276}{}{Giftiges Gebiet}
{277}{}{Giftiges Gebiet}
{278}{}{Falle}
{279}{}{Behälter}
{280}{}{Tore}
{281}{}{Tür}
{282}{}{Boxsack}
{283}{}{Falle}
{284}{}{Flugzeugluke}
{285}{}{Holodisk}
{286}{}{Holodisk}
{287}{}{Holodisk}
{288}{}{Nachricht}
{289}{}{}
{290}{}{}
{291}{}{}
{292}{}{}
{293}{}{}
{294}{}{}
{295}{}{}
{296}{}{}
{297}{}{}
{298}{}{}
{299}{}{}
{300}{}{Schrott}
{301}{}{Pflanze}
{302}{}{Brennendes Fass}
{303}{}{Brahmin}
{304}{}{Frau}
{305}{}{Pumpe}
{306}{}{Kämpfer}
{307}{}{Kontobuch}
{308}{}{Vault-Tec-Technologie}
{309}{}{Kohl}
{310}{}{Plakat}
{311}{}{Kiste mit Nuka-Cola}
{312}{}{Wand}
{313}{}{Gegenstände auf einem Tisch}
{314}{}{Karawanenhändler}
{315}{}{Karawanenhändler}
{316}{}{Harold}
{317}{}{Abstieg}
{318}{}{Zeitungsausschnitte}
{319}{}{Kartencode}
{320}{}{Kind}
{321}{}{Joshua}
{322}{}{Verdächtiger Typ}
{323}{}{}
{324}{}{}
{325}{}{}
{326}{}{}
{327}{}{Barkeeper}
{328}{}{Warenkiste}
{329}{}{Terminal}
{330}{}{Schalttafel}
{331}{}{Tür}
{332}{}{Tore}
{333}{}{Kran}
{334}{}{Seil}
{335}{}{Truhe}
{336}{}{Acabidab der große Bison}
{337}{}{Gizhiyash der stille Fluss}
{338}{}{Kiste}
{339}{}{Mickey}
{340}{}{Schalttafel}
{341}{}{Militär}
{342}{}{Beutekiste}
{343}{}{Maschine}
{344}{}{Bürger}
{345}{}{Bürger}
{346}{}{Schwarzbrenner}
{347}{}{Nuka-Cola-Maschine}
{348}{}{Zeitungsautomat}
{349}{}{Rüstungsteile}
{350}{}{Luke}
{351}{}{Fetzen}
{352}{}{Händler}
{353}{}{Warenkiste}
{354}{}{Aufzug}
{355}{}{Warenkiste}
{356}{}{Räuber}
{357}{}{Bauer}
{358}{}{Händler}
{359}{}{Wache}
{360}{}{Drogenhändler}
{361}{}{Klavier}
{362}{}{Straßenlaterne}
{363}{}{Tisch}
{364}{}{Propagandaplakat}
{365}{}{Autodoc}
{366}{}{Norman}
{367}{}{Schleim}
{368}{}{David}
{369}{}{Zeitungsautomat}
{370}{}{Gecko}
{371}{}{Gecko}
{372}{}{Kartencode}
{373}{}{Kartencode}
{374}{}{}
{375}{}{Kartencode}
{376}{}{Kartencode}
{377}{}{}
{378}{}{}
{379}{}{}
{380}{}{Kartencode}
{381}{}{Kartencode}
{382}{}{Kartencode}
{383}{}{Kartencode}
{384}{}{Kartencode}
{385}{}{Kartencode}
{386}{}{Kartencode}
{387}{}{Kartencode}
{388}{}{Kartencode}
{389}{}{}
{390}{}{}
{391}{}{Kartencode}
{392}{}{Kartencode}
{393}{}{Kartencode}
{394}{}{Kartencode}
{395}{}{Notiz}
{396}{}{Patrick}
{397}{}{Zuschauer}
{398}{}{Zuschauer}
{399}{}{Vortis}
{400}{}{Hinterwäldler}
{401}{}{Sklave}
{402}{}{Köter}
{403}{}{Schlampe}
{404}{}{Auto}
{405}{}{Plakat}
{406}{}{Kartencode}
{407}{}{Kartencode}
{408}{}{}
{409}{}{Kartencode}
{410}{}{Auto}
{411}{}{}
{412}{}{Tor}
{413}{}{Kartencode}
{414}{}{Kartencode}
{415}{}{Kartencode}
{416}{}{Behälter}
{417}{}{Schließfach}
{418}{}{Schließfach}
{419}{}{Ed}
{420}{}{Starker Mann}
{421}{}{Ted Bundy}
{422}{}{Kämpfer}
{423}{}{Leibwächter}
{424}{}{Bikerin}
{425}{}{Bob Neil}
{426}{}{Ventilator}
{427}{}{Drogenhändler}
{428}{}{Kunde}
{429}{}{Lehrling}
{430}{}{Mangelhaft}
{431}{}{Möbel}
{432}{}{Boden}
{433}{}{Boden}
{434}{}{Holodisk}
{435}{}{Müder starker Mann}
{436}{}{Warenkiste}
{437}{}{Prostituierte}
{438}{}{Sklaven-Versuchsperson}
{439}{}{Johnny Chase}
{440}{}{Schauspielerin}
{441}{}{Clubkunde}
{442}{}{Kartencode}
{443}{}{Pirscher}
{444}{}{Schalttafel}
{445}{}{Konsole}
{446}{}{Geschützturm}
{447}{}{Leibwächter}
{448}{}{Milizionär}
{449}{}{Karawanenhändler}
{450}{}{Milizionär}
{451}{}{Türsteher}
{452}{}{Tochter eines Rednecks}
{453}{}{}
{454}{}{}
{455}{}{}
{456}{}{}
{457}{}{}
{458}{}{}
{459}{}{}
{460}{}{}
{461}{}{Holodisk}
{462}{}{Holodisk}
{463}{}{Holodisk}
{464}{}{Holodisk}
{465}{}{Holodisk}
{466}{}{Wache}
{467}{}{Tür}
{468}{}{Generator}
{469}{}{Roboauge}
{470}{}{Giftiges Gebiet}
{471}{}{Bürger}
{472}{}{Raucher}
{473}{}{Maxson}
{474}{}{Sklavenkämpfer}
{475}{}{Tür zur Zelle}
{476}{}{Warenkiste}
{477}{}{Spielautomat}
{478}{}{Frank Cochran}
{479}{}{Räuber}
{480}{}{Wache}
{481}{}{Erik}
{482}{}{Gareth}
{483}{}{Sulik}
{484}{}{Karawanenhändler Billy}
{485}{}{Funker}
{486}{}{}
{487}{}{Truppführer}
{488}{}{Generator}
{489}{}{Tür}
{490}{}{Konsole}
{491}{}{Sklavenhändler}
{492}{}{Schrecklicher Mutant}
{493}{}{Computer}
{494}{}{Gecko}
{495}{}{Grabinschrift}
{496}{}{Roboter}
{497}{}{Reißer}
{498}{}{Makkon}
{499}{}{Harold}
{500}{}{Wassersammler}
{501}{}{Gefängniswärter}
{502}{}{Faulpelz}
{503}{}{Stadtbewohner}
{504}{}{Computer}
{505}{}{Mangelhaft}
{506}{}{Karawanenhändler}
{507}{}{Sam Phillips}
{508}{}{Wagen}
{509}{}{Karawanenhändler}
{510}{}{Casino-Mädchen}
{511}{}{Casino-Mädchen}
{512}{}{DVR-Daten}
{513}{}{Gecko}
{514}{}{Holodisk}
{515}{}{Terry Deveraux}
{516}{}{Spion}
{517}{}{Bürger}
{518}{}{Bill}
{519}{}{Begrüßer}
{520}{}{Thompson}
{521}{}{Kraftfeldgenerator}
{522}{}{Biker}
{523}{}{Mordino}
{524}{}{Rowdy}
{525}{}{Rowdy}
{526}{}{Rowdy}
{527}{}{Archivar}
{528}{}{Patrick}
{529}{}{Straßenlaterne}
{530}{}{Schutzgelderpresser}
{531}{}{Funkgerät}
{532}{}{Ventilator}
{533}{}{Mama}
{534}{}{Barkeeper}
{535}{}{Maxson}
{536}{}{Bürger}
{537}{}{Myron}
{538}{}{}
{539}{}{Richard Moro}
{540}{}{Mitglied der Gemeinschaft}
{541}{}{Stryker}
{542}{}{Straßenhändler}
{543}{}{Bertolini}
{544}{}{Bishop}
{545}{}{Phil Pritchett}
{546}{}{Ausbilder}
{547}{}{Inspektor}
{548}{}{Gefreiter}
{549}{}{Mörder}
{550}{}{Barkeeper}
{551}{}{Barton}
{552}{}{Solomon}
{553}{}{Barkeeper}
{554}{}{Räuber}
{555}{}{Polizist}
{556}{}{Lewis Mordino}
{557}{}{Karawanenhändler Biggy}
{558}{}{String}
{559}{}{Warenkiste}
{560}{}{Ort des Preisverstecks}
{561}{}{Warenkiste}
{562}{}{Warenkiste}
{563}{}{Arzt}
{564}{}{Generator}
{565}{}{Tür}
{566}{}{Spind}
{567}{}{General Wesker}
{568}{}{Kellnerin}
{569}{}{Mitarbeiter im Büro des Bürgermeisters}
{570}{}{Larry Geller}
{571}{}{Techniker}
{572}{}{Ghoul}
{573}{}{Robohund}
{574}{}{Graffiti}
{575}{}{Shelley}
{576}{}{Karawanenhändler Bibby}
{577}{}{Brahmin}
{578}{}{Karawanenführer}
{579}{}{Karawanenhändler}
{580}{}{Karawanenwache}
{581}{}{Neuling}
{582}{}{Gangster}  
{583}{}{Jäger}   
{584}{}{Jäger}   
{585}{}{Waldläufer}   
{586}{}{Söldner}
{587}{}{Söldner}
{588}{}{Räuber}
{589}{}{Karawanenhändler}  
{590}{}{Karawanenwache}   
{591}{}{Patrouillenwache}    
{592}{}{Patrouillenkapitän}  
{593}{}{Bauer}          
{594}{}{Brahmin}         
{595}{}{Brahmin}         
{596}{}{Reisender}        
{597}{}{Patrouillenwache}    
{598}{}{Patrouillenkapitän}  
{599}{}{Patrouillenwache}    
{600}{}{Patrouillenkapitän}  
{601}{}{Brahmin Viehzüchter}  
{602}{}{Viehdieb}         
{603}{}{Hausbesetzer}        
{604}{}{Söldner}
{605}{}{Schwarzbrenner}   
{606}{}{Supermutant} 
{607}{}{Fischer}    
{608}{}{Sklavenhändler}       
{609}{}{Fallensteller}      
{610}{}{Kind}
{611}{}{Gefangener}
{612}{}{}
{613}{}{Scheißposter}
{614}{}{Marion Keysker}
{615}{}{Tür}
{616}{}{Computer}
{617}{}{Brahmin-Träger}
{618}{}{Karawanenhändler Bibbit}
{619}{}{}
{620}{}{Maschine}
{621}{}{Kampforganisator}
{622}{}{Raul}
{623}{}{Freckles}
{624}{}{Schalter}
{625}{}{Nachricht}
{626}{}{Roboter}
{627}{}{Roboter}
{628}{}{Soldat Jim}
{629}{}{Muelleimer}
{630}{}{Brunnen}
{631}{}{Robert}
{632}{}{Jessica}
{633}{}{Bürger}
{634}{}{Computer}
{635}{}{}
{636}{}{}
{637}{}{Kunde}
{638}{}{Kiste}
{639}{}{Bernie Hill}
{640}{}{Warenkiste}
{641}{}{Versteck}
{642}{}{Sklavennummer 18-22}
{643}{}{Computer}
{644}{}{Zaun}
{645}{}{Nachricht}
{646}{}{Wand}
{647}{}{Goris}
{648}{}{Warenkiste}
{649}{}{Polizist}
{650}{}{Betrüger}
{651}{}{V15-Kartencode}
{652}{}{Behälter}
{653}{}{Warenkiste}
{654}{}{Makozid Bärentatze}
{655}{}{Bewohner der Muellkippe}
{656}{}{Bretter}
{657}{}{Mechanismus}
{658}{}{Rowdy}
{659}{}{}
{660}{}{Rowdy}
{661}{}{Abstieg}
{662}{}{Schimmel}
{663}{}{Wache}
{664}{}{Gully}
{665}{}{Essie Gate}
{666}{}{Bobby}
{667}{}{Rekrut}
{668}{}{Gate Junior}
{669}{}{Inspektor}
{670}{}{Kontrolle}
{671}{}{Kanal-Ghul}
{672}{}{Cassidy}
{673}{}{Brunnen}
{674}{}{Raubpflanze}
{675}{}{Holodisk}
{676}{}{Schalter}
{677}{}{Aufzugtür}
{678}{}{Räuber}
{679}{}{Edward}
{680}{}{Sonnenfleck}
{681}{}{Tor}
{682}{}{Feuer}
{683}{}{Croupier}
{684}{}{Musiker}
{685}{}{Räuber}
{686}{}{Musiker}
{687}{}{Musiker}
{688}{}{Fleißiger Besucher}
{689}{}{Unerwarteter Besucher}
{690}{}{Milton}
{691}{}{Clubwache}
{692}{}{Zuhälter}
{693}{}{Zuhälter}
{694}{}{Theodor Wright}
{695}{}{Chuck}
{696}{}{Wrights Leibwächter}
{697}{}{Wrights Leibwächter}
{698}{}{Salvatore}
{699}{}{Mrs. Wright}
{700}{}{Marcus}
{701}{}{Tür}
{702}{}{Kutschenschützer}
{703}{}{Mitglied der Gemeinschaft}
{704}{}{William}
{705}{}{Justin}
{706}{}{Totengräber}
{707}{}{Goldsucher}
{708}{}{Jedediah Smith}
{709}{}{Mike}
{710}{}{Kleidung}
{711}{}{Jasmine}
{712}{}{Warenkiste}
{713}{}{Karawanenführer}
{714}{}{Sporenpflanze}                 
{715}{}{Gecko}                       
{716}{}{Radskorpion}                 
{717}{}{}                            
{718}{}{Krieger}                     
{719}{}{Kannibale}                    
{720}{}{Ausgestoßener}                     
{721}{}{Heilige Person}                 
{722}{}{Nomade}
{723}{}{Flüchtling}
{724}{}{Bandit}                      
{725}{}{Räuber}                      
{726}{}{Wegelagerer}                  
{727}{}{Sklavenhändler}                      
{728}{}{Sklave}
{729}{}{Wilder Ghul}
{730}{}{Gottesanbeterin}                     
{731}{}{Brahmin}
{732}{}{Raubtier}
{733}{}{Arroganter Larry}
{734}{}{Tom}
{735}{}{Simon}
{736}{}{Wachposten}
{737}{}{Toilette}
{738}{}{Musiker}
{739}{}{Lüftung}
{740}{}{Warenkiste}
{741}{}{Falle}
{742}{}{Falle}
{743}{}{Treffen mit Hardy}
{744}{}{Bess}
{745}{}{Hardy}
{746}{}{Harding}
{747}{}{Harrelson}
{748}{}{Kühlschrank}
{749}{}{Casinoverwalter}
{750}{}{Konsole}
{751}{}{Fass}
{752}{}{Safe}
{753}{}{Tür}
{754}{}{Computer}
{755}{}{Wassersammler}
{756}{}{Wache}
{757}{}{Höhle 1 – Zufallsbegegnungskarte}
{758}{}{Tür}
{759}{}{Konsole}
{760}{}{Höhle 2 – Zufallsbegegnungskarte}
{761}{}{Höhle 3 – Zufallsbegegnungskarte}
{762}{}{Höhle 4 – Zufallsbegegnungskarte}
{763}{}{Höhle 2 – Zufallsbegegnungskarte}
{764}{}{Mark}
{765}{}{Kartencode}
{766}{}{Tür}
{767}{}{Kind}
{768}{}{Nachricht}
{769}{}{Eugene}
{770}{}{Tür}
{771}{}{Topf}
{772}{}{Tür}
{773}{}{Gasflaschen}
{774}{}{Flüchtiger Sklave}
{775}{}{}
{776}{}{}
{777}{}{Irrer Brahmin}
{778}{}{Öffnung im Zaun}
{779}{}{}
{780}{}{Kartencode}
{781}{}{Kartencode}
{782}{}{Brahmin bleibt}
{783}{}{Marilyn}
{784}{}{}
{785}{}{Safe}
{786}{}{Sammlung}
{787}{}{Junge}
{788}{}{Karawanenführer}
{789}{}{Chinese}
{790}{}{Chinese}
{791}{}{Indianer}
{792}{}{Karawanenführer}
{793}{}{Karawanenführer}
{794}{}{Nelson}
{795}{}{Frecher Bergarbeiter}
{796}{}{Machete}
{797}{}{}
{798}{}{Frecher Bergarbeiter}
{799}{}{Frecher Bergarbeiter}
{800}{}{Frecher Bergarbeiter}
{801}{}{Lewis Birch}
{802}{}{Betty}
{803}{}{Wassersammler}
{804}{}{}
{805}{}{Agafontsev}
{806}{}{Trofimov}
{807}{}{Ostapenko}
{808}{}{Mikhalitsyn}
{809}{}{Poshelyuzhin}
{810}{}{Voloshin}
{811}{}{Schwachkopf}
{812}{}{Warenkiste}
{813}{}{Warenkiste}
{814}{}{Warenkiste}
{815}{}{Kartencode}
{816}{}{Patrouille}
{817}{}{Hund}
{818}{}{Erd-Drache}
{819}{}{Musikbox}
{820}{}{Bergarbeiter}
{821}{}{Bergarbeiter}
{822}{}{Bergarbeiter}
{823}{}{Itchie}
{824}{}{Bergarbeiter}
{825}{}{Metalldetektor}
{826}{}{Auto}
{827}{}{Auto}
{828}{}{Kabel}
{829}{}{Kind}
{830}{}{Thompsons Mann}
{831}{}{}
{832}{}{Mysteriöser Fremder}
{833}{}{Irrer brahmin}
{834}{}{}
{835}{}{}
{836}{}{Roboter-Wache}
{837}{}{Hintern}
{838}{}{}
{839}{}{Nomade}
{840}{}{Rauch}
{841}{}{Händler}
{842}{}{Abenteurer}
{843}{}{Krieger der Slums}
{844}{}{Steinhaufen}
{845}{}{}
{846}{}{Zuschauer}
{847}{}{Bürger}
{848}{}{Polizist}
{849}{}{Sam}
{850}{}{Colin}
{851}{}{Sergeant Stark}
{852}{}{Felder}
{853}{}{Clubbesucher}
{854}{}{Kind}
{855}{}{Zuschauer}
{856}{}{Apotheker}
{857}{}{Jul}
{858}{}{Kerith}
{859}{}{Mrs. Clover}
{860}{}{Computer}
{861}{}{}
{862}{}{}
{863}{}{Goldsucher}
{864}{}{}
{865}{}{Apotheker}
{866}{}{Hubologe}                
{867}{}{Psycho}                     
{868}{}{Eindringling}              
{869}{}{Kannibale}
{870}{}{Kojotenjäger}
{871}{}{Marodeur}
{872}{}{Kojotenhäuptling}
{873}{}{Einsiedler}                       
{874}{}{}                             
{875}{}{Karawanenführer}               
{876}{}{Karawanenführer}               
{877}{}{Karawanenführer}               
{878}{}{Karawanenführer}               
{879}{}{Karawanenführer}
{880}{}{Mitglied der Kings-Gang}
{881}{}{Filterjäger}
{882}{}{Hosenscheißer.}
{883}{}{Flüchtiger Gefangener}
{884}{}{Bauernfrau}        
{885}{}{Bauernkind}         
{886}{}{Dorfbewohner}          
{887}{}{Dorfbewohnerfrau}   
{888}{}{Dorfbewohnerkind}    
{889}{}{Karawanenführer}       
{890}{}{}                     
{891}{}{}                     
{892}{}{}                     
{893}{}{}                     
{894}{}{Enclave-Patrouilleur}
{895}{}{Thompsons Mann}
{896}{}{Super 8}
{897}{}{Morris}
{898}{}{Wand}
{899}{}{}
{900}{}{}
{901}{}{Leiche}
{902}{}{Schalter}
{903}{}{Meister}
{904}{}{Terminal}
{905}{}{Tür}
{906}{}{Boxsack}
{907}{}{Oliver Luciano}
{908}{}{Wagen}
{909}{}{Anführer des Konvois}
{910}{}{Konvoi-Wache}
{911}{}{Bote}
{912}{}{Deveraux' Frau}
{913}{}{Deveraux' Sohn}
{914}{}{Sheriff}
{915}{}{Räuber}
{916}{}{Jäger}
{917}{}{Räuber}
{918}{}{Räuber}
{919}{}{Schäfer}
{920}{}{Hilfssheriff}
{921}{}{Manager}
{922}{}{Arbeiter}
{923}{}{Arbeiter}
{924}{}{Pirscher}
{925}{}{Händler}
{926}{}{Tür}
{927}{}{Tür}
{928}{}{Kühlbox}
{929}{}{Nick Hauer}
{930}{}{}                              
{931}{}{Kaga}                          
{932}{}{Kaga}                          
{933}{}{Kaga}                          
{934}{}{Kaga}                          
{935}{}{Ein Echo der Vergangenheit}
{936}{}{Kopfgeldjäger}
{937}{}{Karawanenführer}
{938}{}{Computer}
{939}{}{Karawanenwache}
{940}{}{Karawanenhändler}
{941}{}{Karawanenführer}
{942}{}{Gangmitglied}
{943}{}{Gangführer}
{944}{}{Wagen mit Waren}
{945}{}{Warenkiste}
{946}{}{Charlie}
{947}{}{Monitor}
{948}{}{Mist}
{949}{}{Dammbauarbeiter}
{950}{}{Spuren}
{951}{}{Sklavenhändler}
{952}{}{Pflanze}
{953}{}{Gully}
{954}{}{Schaffner}
{955}{}{Gilmore}
{956}{}{Skinner}
{957}{}{Seelenschnitter}
{958}{}{Kopf des Präsidenten}
{959}{}{}
{960}{}{}
{961}{}{Irgendein Schrott}
{962}{}{Tür}
{963}{}{Kiste}
{964}{}{Artefakt}
{965}{}{Sklavenhändler}
{966}{}{Häuter}
{967}{}{Anschlagtafel}
{968}{}{Handwerker}
{969}{}{Aufseher}
{970}{}{Organisator}
{971}{}{Hoppla!}
{972}{}{Stadtbewohner}                    
{973}{}{Vault City-Ratsgebiet}
{974}{}{Zugriffskonsole}
{975}{}{Schalttafel}
{976}{}{Warenkiste}
{977}{}{Spieler}
{978}{}{Intendant}
{979}{}{Hinterwäldler}
{980}{}{Klon}
{981}{}{Geschützturm}
{982}{}{Hinterwäldler}
{983}{}{Generator}
{984}{}{Tür}
{985}{}{Abstieg}
{986}{}{Sklavenhändler}
{987}{}{Große Tür}
{988}{}{Tür}
{989}{}{Darrow-Vorrat}         
{990}{}{Tür} 
{991}{}{Geschützturm}
{992}{}{Koch}
{993}{}{Spielautomat}
{994}{}{Alter Freund}
{995}{}{Umspannwerk}
{996}{}{Abstieg}
{997}{}{Zugtür}
{998}{}{Tür}
{999}{}{}
{1000}{}{Behelfsfeuer}
{1001}{}{Werkbank}
{1002}{}{Zentrifuge}
{1003}{}{Werkbank zur Munitionsherstellung}
{1004}{}{Karawanenhändler}
{1005}{}{Colonel Knight}
{1006}{}{Kunde}
{1007}{}{Eli}
{1008}{}{Polizist}
{1009}{}{Wache}
{1010}{}{Konsole}
{1011}{}{Seelenschnitter}
{1012}{}{Karawanenhändler}
{1013}{}{Karte}
{1014}{}{Klon}
{1015}{}{Sklavenhändler} 
{1016}{}{Karawanenhändler}
{1017}{}{Safe}
{1018}{}{Warenkiste}
{1019}{}{Warenkiste}
{1020}{}{Kofferraum} 
{1021}{}{Tür}
{1022}{}{Gefangener}
{1023}{}{Tür}
{1024}{}{Hund mit Halsband}
{1025}{}{Händler}
{1026}{}{}
{1027}{}{Betrunkener Passant}
{1028}{}{}
{1029}{}{Tote Person} 
{1030}{}{Waschbecken}
{1031}{}{Sturmhaube}
{1032}{}{Sklave}                     
{1033}{}{Sklave}                     
{1034}{}{Sklavenhändler}
{1035}{}{Unverbesserlicher Ned}
{1036}{}{Zugtür}
{1037}{}{Feder}
{1038}{}{Gefreiter}
{1039}{}{Geldkassette}                    
{1040}{}{Wanamingo}
{1041}{}{Arbeitsloser}
{1042}{}{Terrorist}
{1043}{}{Gefängnistür}
{1044}{}{Kellnerin}
{1045}{}{Vernon}
{1046}{}{Information}
{1047}{}{}
{1048}{}{}
{1049}{}{Frog Morton}
{1050}{}{Dieb}
{1051}{}{Schalter}
{1052}{}{Kiste}
{1053}{}{Kotzender Charlie}
{1054}{}{Schlüssel}
{1055}{}{}
{1056}{}{Barkeeper}      
{1057}{}{Kiste}   
{1058}{}{Computer}
{1059}{}{}
{1060}{}{}
{1061}{}{Roboter}
{1062}{}{Warenkiste}
{1063}{}{Kartencode}
{1064}{}{Kartencode}
{1065}{}{Lydia}
{1066}{}{}
{1067}{}{Garry}
{1068}{}{Schaffner}
{1069}{}{Francis}
{1070}{}{Amanda}                      
{1071}{}{Joshua}                      
{1072}{}{Valerie}                     
{1073}{}{Lernsystem}
{1074}{}{Flugroboter}
{1075}{}{Urinierender Junge}           
{1076}{}{Curtis}
{1077}{}{Gehängter}
{1078}{}{Nuka-Cola-Kiste}
{1079}{}{Bürger}
{1080}{}{Wache}                        
{1081}{}{Steinhaufen}                
{1082}{}{Tür}
{1083}{}{Sklavenhändler}
{1084}{}{Laborassistent}
{1085}{}{Nachricht}
{1086}{}{Schild „Gesucht“}
{1087}{}{Jolly Joe}
{1088}{}{Warenkiste}
{1089}{}{Tore}
{1090}{}{Stammgast}
{1091}{}{Angestellter}
{1092}{}{Mädchen}
{1093}{}{Badewanne}
{1094}{}{Ladenbesitzer}
{1095}{}{Gully}
{1096}{}{}
{1097}{}{Leiter}
{1098}{}{Konsole}
{1099}{}{Tor}
{1100}{}{Tür}
{1101}{}{Wache}
{1102}{}{Wache}
{1103}{}{Wache}
{1104}{}{Wagen}
{1105}{}{Wache}
{1106}{}{Verwalter}
{1107}{}{Terminal}
{1108}{}{Mitglied der Familie Deveraux}
{1109}{}{Nick Hauer}
{1110}{}{Pirscher}
{1111}{}{Maschinenfriedhof}
{1112}{}{Gestohlener Gegenstand}
{1113}{}{Gesichtskontrolle}
{1114}{}{Abgeordneter}
{1115}{}{Wache}
{1116}{}{Kommandant}
{1117}{}{Information}
{1118}{}{Generator}
{1119}{}{Richard Pryor}
{1120}{}{Frau des Komikers}
{1121}{}{Arbeiter}
{1122}{}{Tür}
{1123}{}{Tür}
{1124}{}{Behälter}
{1125}{}{Beleuchtung}
{1126}{}{Neon Gangster}
{1127}{}{Behälter}
{1128}{}{Futtertrog}
{1129}{}{Igitt!}
{1130}{}{}
{1131}{}{Chet}
{1132}{}{}
{1133}{}{Vertibird}
{1134}{}{Schaffner}
{1135}{}{Bandit}
{1136}{}{Wache}
{1137}{}{Räuber}
{1138}{}{Elektrischer Verteilerkasten}
{1139}{}{Kurier}
{1140}{}{Polizist}
{1141}{}{Kraftfeld}
{1142}{}{Tür}
{1143}{}{Tor}
{1144}{}{}
{1145}{}{Sehr wild brahmin}
{1146}{}{}
{1147}{}{Sklave}
{1148}{}{Hinterwäldler}
{1149}{}{Tür}
{1150}{}{Starker Mann}
{1151}{}{Tresortür}
{1152}{}{Karawanenhändler}
{1153}{}{Raul}                         
{1154}{}{Quincy}                       
{1155}{}{Quartiermeister}
{1156}{}{Stammgast}
{1157}{}{Kybernetischer Hund}
{1158}{}{Hinterwäldler}
{1159}{}{Orris}
{1160}{}{Mitglied der Kings-Gang}
{1161}{}{Biker}
{1162}{}{Biker}
{1163}{}{Hinterwäldler}
{1164}{}{Hinterwäldler}
{1165}{}{Hinterwäldler}
{1166}{}{Hinterwäldler}
{1167}{}{Hinterwäldler}
{1168}{}{Brahmin}
{1169}{}{}
{1170}{}{Hinterwäldler}
{1171}{}{Geschützturmsteuerung}
{1172}{}{}
{1173}{}{}
{1174}{}{}
{1175}{}{}
{1176}{}{}
{1177}{}{}
{1178}{}{Karawanenhändler}
{1179}{}{Toilette}
{1180}{}{Leiche}                        
{1181}{}{Kiste}                         
{1182}{}{Kiste}                         
{1183}{}{Kiste}                         
{1184}{}{Karawanenwache}               
{1185}{}{Karawanenhändler}
{1186}{}{Mitchell}
{1187}{}{Rädelsführer}
{1188}{}{Boxer}                        
{1189}{}{Tür}                         
{1190}{}{Cheat-Charakter}
{1191}{}{Koffer}
{1192}{}{Holodisk}
{1193}{}{Kriminalakte}
{1194}{}{Katalog}
{1195}{}{Dogmeat}
{1196}{}{Wissenschaftsmagazin}
{1197}{}{Tagebuch}
{1198}{}{John}
{1199}{}{Reservoir}
{1200}{}{Maschinerie}
{1201}{}{Grube}
{1202}{}{Bürger}
{1203}{}{Eva Cohen}
{1204}{}{Bürger}
{1205}{}{Warenkiste}
{1206}{}{Warenkiste}
{1207}{}{Elektrizität}
{1208}{}{Flugroboter}
{1209}{}{Computer}
{1210}{}{Förderband}
{1211}{}{Ratgeber}
{1212}{}{}
{1213}{}{}
{1214}{}{Wache}                       
{1215}{}{Goldsucher}                  
{1216}{}{Schwarzbrenner}                 
{1217}{}{}                            
{1218}{}{Dan}
{1219}{}{Ricky}
{1220}{}{Mechaniker}
{1221}{}{}
{1222}{}{}
{1223}{}{Gasanlage}
{1224}{}{Fahrer}
{1225}{}{Tor}
{1226}{}{Tank}
{1227}{}{Computer}                     
{1228}{}{Kohl}                         
{1229}{}{Kind}                        
{1230}{}{Koch}                         
{1231}{}{Geschützturm}                       
{1232}{}{Brian}                        
{1233}{}{Generator}                    
{1234}{}{Konsole}                      
{1235}{}{Riesenameise}                    
{1236}{}{Riesenameise}                    
{1237}{}{Tür}                         
{1238}{}{}
{1239}{}{Selbstgebrannter-Schnaps-Brennerei}
{1240}{}{Eric}                       
{1241}{}{}                           
{1242}{}{Kiste}                        
{1243}{}{Riesenskorpion}             
{1244}{}{Jane}                         
{1245}{}{}
{1246}{}{}
{1247}{}{Konservendose}
{1248}{}{Wachhund}
{1249}{}{Rattray}                     
{1250}{}{Ehepartner}
{1251}{}{Passant}
{1252}{}{}
{1253}{}{Tür}                         
{1254}{}{Kybernetischer Hund}               
{1255}{}{Luke}
{1256}{}{Hausmeister}
{1257}{}{Tor}
{1258}{}{Henker}
{1259}{}{Tür}
{1260}{}{Roboter}
{1261}{}{Tür}
{1262}{}{Stapleton}
{1263}{}{Terminal}                     
{1264}{}{Geschützturm}                       
{1265}{}{Chuck Staggers}               
{1266}{}{}                             
{1267}{}{Terminal}                     
{1268}{}{Gangster}                    
{1269}{}{Betrüger}                      
{1270}{}{}
{1271}{}{Bürger}
{1272}{}{Lehrbuch}
{1273}{}{Radskorpion}                  
{1274}{}{Professor}                    
{1275}{}{Kiste}                          
{1276}{}{Kiste}                          
{1277}{}{Seymour}                      
{1278}{}{John Sullivan}                
{1279}{}{Freckles}                        
{1280}{}{}
{1281}{}{Holodisk}
{1282}{}{Verkaufswagen}
{1283}{}{Gefreiter}
{1284}{}{Lampe}
{1285}{}{Nachricht}
{1286}{}{Typhon}
{1287}{}{Seelenschnitter}
{1288}{}{}
{1289}{}{Spind}                       
{1290}{}{Brunnen}                         
{1291}{}{Mickey}
{1292}{}{Alien}
{1293}{}{Alter Ghul}                    
{1294}{}{Handlanger}                     
{1295}{}{Elmo}
{1296}{}{Konsole}
{1297}{}{Persönliche Kiste}
{1298}{}{Anführer der Angriffsgruppe}
{1299}{}{Dehydrierung}
{1300}{}{Skorpion}                     
{1301}{}{Generator}                    
{1302}{}{Tür}
{1303}{}{Wand}
{1304}{}{Körperpflegeset}
{1305}{}{Spind}
{1306}{}{Generator}
{1307}{}{Behälter}
{1308}{}{Tür}
{1309}{}{Spieleentwickler}
{1310}{}{Nuka-Cola-Maschine}
{1311}{}{Spind}
{1312}{}{Spieleentwickler}
{1313}{}{Tür}
{1314}{}{Kind}
{1315}{}{Schalter}
{1316}{}{Kind}
{1317}{}{Stolperdraht}
{1318}{}{Leiter}
{1319}{}{Nachricht}
{1320}{}{Tür}
{1321}{}{Bürger}
{1322}{}{Bürger}
{1323}{}{Lichtquelle}
{1324}{}{Falle}
{1325}{}{Kartencode}           
{1326}{}{Du kannst mich nicht sehen}
{1327}{}{Loch}
{1328}{}{}
{1329}{}{Familienoberhaupt}
{1330}{}{}
{1331}{}{Kind}
{1332}{}{Spritze}
{1333}{}{Frau}
{1334}{}{}
{1335}{}{Hund}
{1336}{}{Sicherheitsroboter}
{1337}{}{Kapuze}
{1338}{}{Computer}
{1339}{}{Milizionär}
{1340}{}{Jay Kukish}
{1341}{}{Spind}                       
{1342}{}{Spind}                       
{1343}{}{Spind}                       
{1344}{}{Spind}                       
{1345}{}{Spind}                       
{1346}{}{Spind}                       
{1347}{}{Spind}                       
{1348}{}{Spind}                       
{1349}{}{Spind}                       
{1350}{}{Spind}                       
{1351}{}{Spind}                       
{1352}{}{Spind}                       
{1353}{}{Spind}                       
{1354}{}{Spind}                       
{1355}{}{Spind}                       
{1356}{}{Spind}
{1357}{}{Mangelhaft}
{1358}{}{Kind}
{1359}{}{}
{1360}{}{Rennveranstalter}
{1361}{}{Warenkiste}
{1362}{}{Kraftfeldgenerator}
{1363}{}{Hintereingang}
{1364}{}{Tom Parker}
{1365}{}{}
{1366}{}{Generator}
{1367}{}{Bewohner der Slums}
{1368}{}{Munitionskiste}
{1369}{}{}
{1370}{}{}
{1371}{}{}
{1372}{}{}
{1373}{}{Nuka-Cola-Maschine}
{1374}{}{}
{1375}{}{Erdrutsch}
{1376}{}{Tretmine}
{1377}{}{Notizen}
{1378}{}{Dein Ex}                     
{1379}{}{Mal}                         
{1380}{}{Lüftungsschacht}                        
{1381}{}{Kevin}                       
{1382}{}{Alarm}                       
{1383}{}{Spind}                      
{1384}{}{Spind}                      
{1385}{}{Spind}
{1386}{}{Dreck}
{1387}{}{}
{1388}{}{}
{1389}{}{}
{1390}{}{}
{1391}{}{}
{1392}{}{}
{1393}{}{}
{1394}{}{Schmuggler}
{1395}{}{}
{1396}{}{}
{1397}{}{Karawanenhändler}
{1398}{}{}
{1399}{}{}
{1400}{}{Safe}
{1401}{}{Generator}
{1402}{}{Generator}
{1403}{}{Phaser}
{1404}{}{Tarantool}