#
#   Messages from skill.c
#
#
#   SKILL NAMES
#
{100}{}{Kleine Waffen}
{101}{}{Schwere Waffen}
{102}{}{Energiewaffen}
{103}{}{Unbewaffnet}
{104}{}{Nahkampfwaffen}
{105}{}{Werfen}
{106}{}{Erste Hilfe}
{107}{}{Arzt}
{108}{}{Schleichen}
{109}{}{Schlösser knacken}
{110}{}{Stehlen}
{111}{}{Fallen}
{112}{}{Wissenschaft}
{113}{}{Reparieren}
{114}{}{Redekunst}
{115}{}{Tauschhandel}
{116}{}{Glücksspiel}
{117}{}{Überlebenskunst}
#
#   SKILL DESCRIPTIONS
#
{200}{}{Der Umgang mit, die Pflege und das allgemeine Wissen über kleine Schusswaffen – Pistolen, MPs und Gewehre.}
{201}{}{Der Betrieb und die Wartung richtig großer Waffen – Miniguns, Raketenwerfer, Flammenwerfer und Ähnliches.}
{202}{}{Die Pflege und Handhabung von Energiewaffen. Wie man Waffen mit Laser- oder Plasmatechnologie einsatzbereit macht und bedient.}
{203}{}{Eine Kombination aus Kampfsport, Boxen und anderen waffenlosen Kampfkünsten. Kämpfe mit Händen und Füßen.}
{204}{}{Der Einsatz von Waffen im Nahkampf – Messer, Vorschlaghämmer, Speere, Knüppel und so weiter.}
{205}{}{Die Fertigkeit im Umgang mit Muskelkraftwaffen wie Wurfmessern, Speeren und Granaten.}
{206}{}{Allgemeine Heilkunst. Dient dazu, kleine Schnitte, Schürfwunden und andere leichte Beschwerden zu behandeln. Im Spiel kann Erste Hilfe mit der Zeit mehr Trefferpunkte wiederherstellen als bloßes Ausruhen.}
{207}{}{Die Behandlung schwerer Wunden und verkrüppelter Gliedmaßen. Ohne diese Fertigkeit dauert es viel länger, bis verkrüppelte Gliedmaßen wieder einsatzfähig sind.}
{208}{}{Leise Bewegung und die Fähigkeit, unbemerkt zu bleiben. Wenn du erfolgreich bist, wird es viel schwieriger, dich aufzuspüren. Du kannst nicht gleichzeitig rennen und schleichen.}
{209}{}{Die Fertigkeit, Schlösser ohne den passenden Schlüssel zu öffnen. Dietriche oder elektronische Dietriche verbessern diese Fertigkeit erheblich.}
{210}{}{Die Fähigkeit, dir die Dinge anderer zu eigen zu machen. Kann dazu dienen, Menschen oder Orten etwas zu stehlen.}
{211}{}{Die Fähigkeit, subversive Aktionen durchzuführen, etwa Fallen zu finden, aufzustellen und zu entfernen. Dazu gehört auch das Platzieren von Sprengstoff für Abrissarbeiten.}
{212}{}{Dient dazu, Wissen zu erwerben und Analysen durchzuführen. Umfasst verschiedene Hightech-Fertigkeiten (etwa den Umgang mit Computern sowie Kenntnisse in Chemie, Geologie usw.) und wissenschaftliche Methoden.}
{213}{}{Die praktische Anwendung von Reparaturfertigkeiten, um defekte Ausrüstung, Maschinen und Elektronik instand zu setzen.}
{214}{}{Die Fähigkeit, praktisch und effizient zu kommunizieren. Andere davon zu überzeugen, dass du recht hast. Lügen zu können, ohne erwischt zu werden.}
{215}{}{Die Fähigkeit, bessere Preise zu erzielen, das Vertrauen der Karawanenhändler zu gewinnen und besser mit Händlern zu verhandeln.}
{216}{}{Kenntnisse und praktische Fertigkeiten rund ums Glücksspiel, Kartenspiele, Würfel und andere Spiele.}
{217}{}{Praktische Kenntnisse im Freien und die Fähigkeit, von dem zu leben, was die Natur bietet. Kenntnisse über Pflanzen und Tiere.}
#
#   SKILL ATTRIBUTES
#
#   Updated: 6/5/97 KSW
#   Updated to New Skill System: 9/16/98 rwh2
#
{300}{}{+ (4 x AG)}
{301}{}{+ (2 x AG)}
{302}{}{+ (2 xAG)}
{303}{}{+ (2 x (AG + ST))}
{304}{}{+ (2 x (AG + ST))}
{305}{}{+ (4 x AG)}
{306}{}{+ (2 x (PE + IN))}
{307}{}{+ (PE + IN)}
{308}{}{+ (3 x AG)}
{309}{}{+ (PE + AG)}
{310}{}{+ (3 x AG)}
{311}{}{+ (PE + AG)}
{312}{}{+ (4 x IN)}
{313}{}{+ (3 x IN)}
{314}{}{+ (5 x CH)}
{315}{}{+ (4 x CH)}
{316}{}{+ (5 x LK)}
{317}{}{+ (2 x (EN + IN))}
#
#   Skill Use Text
#
{500}{}{Du heilst %d Trefferpunkte.}
{501}{}{Du bist bereits gesund.}
{502}{}{%s ist bereits gesund.}
{503}{}{Du kannst niemanden heilen.}
{505}{}{Du erhältst %d EP, weil du deine Fertigkeiten verfeinert hast.}
{510}{}{\nskill_use: Ungültige Fertigkeit verwendet.}
{512}{}{Du kannst Tote nicht heilen.}
{513}{}{Lass die Toten in Frieden ruhen.}
{514}{}{Der ist tot. Find dich damit ab.}
{520}{}{Du heilst dein %s.}
{521}{}{Du heilst das %s.}
{525}{}{Du kannst dein %s nicht heilen.}
{526}{}{Du kannst das %s nicht heilen.}
{530}{}{verletztes Auge}    # Lines 530-534 are the endings to lines 525 & 526.
{531}{}{verkrüppelter linker Arm}
{532}{}{verkrüppelter rechter Arm}
{533}{}{verkrüppeltes rechtes Bein}
{534}{}{verkrüppeltes linkes Bein}
{550}{}{Du kannst das Schloss nicht knacken.}
{551}{}{Du findest keine Fallen.}
{552}{}{Du lernst nichts dazu.}
{553}{}{Das kannst du nicht reparieren.}
{570}{}{Du wirst dabei erwischt, wie du das %s stiehlst.}
{571}{}{Du stiehlst das %s.}
{572}{}{Du wirst dabei erwischt, wie du das %s platzierst.}
{573}{}{Du platzierst das %s.}
{590}{}{Du hast dich mit dieser Fähigkeit verausgabt. Warte eine Weile.}
{591}{}{Du bist zu müde.}
{592}{}{Die Anstrengung könnte dich umbringen.}

# Fallout 2!
{600}{}{Du bist nicht geschickt genug, um verkrüppelte Gliedmaßen zu heilen.}
{601}{}{Die Robotereinheit ist irreparabel.}



#
# Fallout 2: Party Member skill use generic responses
#

#   I'll try
{1000}{}{Lass mich helfen.}
{1001}{}{Das kann ich erledigen.}
{1002}{}{Ich hab's.}
{1003}{}{Gern geschehen.}
{1004}{}{In Ordnung.}
{1005}{}{Ich versuch's.}

#   Player wants to do it
{1100}{}{Wenn du Probleme hast, sag Bescheid.}
{1101}{}{Hast du's geschafft?}
{1102}{}{Wenn du das möchtest.}
{1103}{}{Versuch's ruhig.}
{1104}{}{Nur zu.}