#
#	 Messages from stat.c
#
#
#	 STAT NAMES
#
{100}{}{Stärke}
{101}{}{Wahrnehmung}
{102}{}{Ausdauer}
{103}{}{Charisma}
{104}{}{Intelligenz}
{105}{}{Beweglichkeit}
{106}{}{Glück}
{107}{}{Maximale Trefferpunkte}
{108}{}{Maximale Aktionspunkte}
{109}{}{Rüstungsklasse}
{110}{}{Waffenloser Schaden}
{111}{}{Nahkampfschaden}
{112}{}{Traglast}
{113}{}{Reihenfolge}
{114}{}{Heilungsrate}
{115}{}{Kritische Trefferchance}
{116}{}{Bessere kritische Treffer}
{117}{}{Schadensschwelle}
{118}{}{Schadensschwelle (Laser)}
{119}{}{Schadensschwelle (Feuer)}
{120}{}{Schadensschwelle (Plasma)}
{121}{}{Schadensschwelle (Elektrizität)}
{122}{}{Schadensschwelle (EMP)}
{123}{}{Schadensschwelle (Explosion)}
{124}{}{Schadensresistenz}
{125}{}{Schadensresistenz (Laser)}
{126}{}{Schadensresistenz (Feuer)}
{127}{}{Schadensresistenz (Plasma)}
{128}{}{Schadensresistenz (Elektrizität)}
{129}{}{Schadensresistenz (EMP)}
{130}{}{Schadensresistenz (Explosion)}
{131}{}{Strahlungsresistenz}
{132}{}{Giftresistenz}
{133}{}{Alter}
{134}{}{Geschlecht}
{135}{}{Aktuelle Trefferpunkte}
{136}{}{Aktueller Giftwert}
{137}{}{Aktueller Strahlungswert}
#
#	 STAT DESCRIPTIONS
#
# @ Basic stats @
#
# Strength
{200}{}{Rohe körperliche Stärke. Ein hoher Stärkewert ist gut für körperlich orientierte Charaktere. Beeinflusst: Trefferpunkte, Nahkampfschaden und Traglast.}
# Perception
{201}{}{Die Fähigkeit, zu sehen, zu hören, zu schmecken und Ungewöhnliches zu bemerken. Eine hohe Wahrnehmung ist für einen Scharfschützen wichtig. Beeinflusst: Reihenfolge und Modifikatoren für die Fernkampfreichweite.}
# Endurance
{202}{}{Ausdauer und körperliche Widerstandsfähigkeit. Ein Charakter mit hoher Ausdauer überlebt, wo andere es vielleicht nicht schaffen. Beeinflusst: Trefferpunkte, Gift- und Strahlungsresistenz, Heilungsrate und zusätzliche Trefferpunkte pro Stufe.}
# Charisma
{203}{}{Eine Kombination aus Aussehen und Charme. Hohes Charisma ist wichtig für Charaktere, die andere mit Worten beeinflussen wollen. Beeinflusst: Reaktionen von NPCs und Tauschpreise.}
# Intelligence
{204}{}{Wissen, Weisheit und die Fähigkeit, schnell zu denken. Eine hohe Intelligenz ist für jeden Charakter wichtig. Beeinflusst: die Anzahl neuer Fertigkeitspunkte pro Stufe, Dialogoptionen und viele Fertigkeiten.}
# Agility
{205}{}{Koordination und die Fähigkeit, sich gut zu bewegen. Eine hohe Beweglichkeit ist für jeden aktiven Charakter wichtig. Beeinflusst: Aktionspunkte, Rüstungsklasse, Reihenfolge und viele Fertigkeiten.}
# Luck
{206}{}{Schicksal. Karma. Ein extrem hoher oder niedriger Glückswert wird den Charakter beeinflussen – irgendwie. Ereignisse und Situationen ändern sich je nachdem, wie viel Glück (oder Pech) dein Charakter hat.}
#
# Derived/Non Derived stats
#
# Maximum Hit Points
{207}{}{Wie viel Schaden dein Charakter ertragen kann, bevor er stirbt. Wenn du 0 TP oder weniger erreichst, bist du tot.}
# Maximum Action Points
{208}{}{Die Anzahl der Aktionen, die der Charakter während eines Kampfrunden-Zugs ausführen kann.}
# Armor Class
{209}{}{Beeinflusst die Trefferchance gegen diesen bestimmten Charakter.}
# Unarmed Damage
{210}{}{Der zusätzliche Schaden, den dein Charakter im Nahkampf verursacht.}
{211}{}{Der zusätzliche Schaden, den dein Charakter im Nahkampf verursacht.}
# Carry Weight
{212}{}{Die Höchstmenge an Ausrüstung, die dein Charakter in Pfund tragen kann.}
# Sequence
{213}{}{Legt fest, wie schnell dein Charakter in einer Kampfrunde reagieren kann.}
# Healing Rate
{214}{}{Am Ende jedes Tages heilt dein Charakter für jeden Punkt Heilungsrate 1 TP. Wenn du rastest, heilst du alle sechs Stunden.}
# Critical Chance
{215}{}{Die Chance auf einen kritischen Treffer im Kampf wird um diesen Wert erhöht.}
{216}{}{Bessere kritische Treffer}
{217}{}{Schadensschwelle}
{218}{}{Schadensschwelle (Laser)}
{219}{}{Schadensschwelle (Feuer)}
{220}{}{Schadensschwelle (Plasma)}
{221}{}{Schadensschwelle (Elektrizität)}
{222}{}{Schadensschwelle (EMP)}
{223}{}{Schadensschwelle (Explosion)}
# Damage Resistance
{224}{}{Jeder erlittene Schaden wird um diesen Wert verringert. Die Schadensresistenz kann durch das Tragen von Rüstung erhöht werden.}
{225}{}{Schadensresistenz (Laser)}
{226}{}{Schadensresistenz (Feuer)}
{227}{}{Schadensresistenz (Plasma)}
{228}{}{Schadensresistenz (Elektrizität)}
{229}{}{Schadensresistenz (EMP)}
{230}{}{Schadensresistenz (Explosion)}
# Radiation Resistance
{231}{}{Die auf dich einwirkende Strahlung wird um diesen Prozentsatz verringert. Die Strahlungsresistenz hängt von der getragenen Rüstung und Strahlenschutz-Chems ab.}
# Poison Resistance
{232}{}{Verringert den Giftschaden um diesen Wert.}
{233}{}{Alter}
{234}{}{Geschlecht}
{235}{}{Aktuelle Trefferpunkte}
{236}{}{Aktueller Giftwert}
{237}{}{Aktueller Strahlungswert}
#
# STAT LEVEL DESCRIPTIONS
#
{301}{}{Übel}
{302}{}{Mies}
{303}{}{Dürftig}
{304}{}{Leidlich}
{305}{}{Mittel}
{306}{}{Gut}
{307}{}{Toll}         # Abbreviated for character editor
{308}{}{Klasse}
{309}{}{Super}
{310}{}{Spitze}
#
#	 PC STAT NAMES
#
{400}{}{Nicht ausgegebene Fertigkeitspunkte}
{401}{}{Stufe}
{402}{}{Erfahrung}
{403}{}{Ruf}
{404}{}{Karma}
#
#	 PC STAT DESCRIPTIONS
#
# Unspent Skill Points
{500}{}{Punkte, die du beim Erreichen einer neuen Stufe erhältst. Für jeden ausgegebenen Punkt kannst du eine Fertigkeit um 1% oder eine markierte Fertigkeit um 2% erhöhen.}
# Level
{501}{}{Die allgemeine Kompetenz des Spielercharakters. Ein Maß für deine Erfahrung und Fähigkeiten.}
# Experience
{502}{}{Eine Belohnung für das Erfuellen bestimmter Aufgaben oder das Besiegen von Gegnern im Kampf. Für höhere Stufen werden mehr Erfahrungspunkte benötigt.}
# Reputation
{503}{}{Was die Welt über deine Taten und Handlungen weiß. Dies beeinflusst die Reaktionen von NPCs.}
# Karma
{504}{}{Die Auswirkungen deiner bisherigen Handlungen. Wichtige Informationen werden angezeigt.}

#
#  Experience-gain messages
#
{600}{}{Du bist eine Stufe aufgestiegen.}
