#
#   Messages from trait.c
#
#
#   TRAIT NAMES
#
{100}{}{Schneller Stoffwechsel}
{101}{}{Grobschlächtig}
{102}{}{Schmächtiger Körper}
{103}{}{Einhändig}
{104}{}{Finesse}
{105}{}{Kamikaze}
{106}{}{Grobe Hände}
{107}{}{Schnellschütze}
{108}{}{Blutiges Gemetzel}
{109}{}{Verflucht}
{110}{}{Gutmütig}
{111}{}{Chemieabhängig}
{112}{}{Chemieresistent}
{113}{}{Sexappeal}  # was: Night Person
{114}{}{Talentiert}
{115}{}{Begabt}
#
#   TRAIT DESCRIPTIONS
#
{200}{}{Dein Stoffwechsel ist doppelt so schnell wie normal. Das bedeutet, dass du deutlich weniger resistent gegen Strahlung und Gift bist, dein Körper sich aber schneller heilt.}
{201}{}{Etwas langsamer, aber dafür etwas größer. Du triffst vielleicht nicht so oft, aber wenn du triffst, spüren deine Gegner es! Deine Aktionspunkte sind um zwei verringert, dafür ist deine Stärke um zwei erhöht.}
{202}{}{Du bist nicht ganz so groß wie die anderen Dorfbewohner, aber das hat dich nie aufgehalten. Du kannst nicht so viel tragen, bist dafür aber beweglicher.}
{203}{}{Eine deiner Hände ist besonders dominant. Du erhältst einen Trefferbonus von 20% mit Pistolen und anderen einhändigen Waffen und einen Trefferabzug von 40% mit zweihändigen Waffen.}
{204}{}{Deine Angriffe sind äußerst raffiniert. Du verursachst 30% le weniger Schaden, hast dafür aber eine um 10% c erhöhte Chance auf kritische Treffer.}
{205}{}{Wenn du Bedrohungen einfach ignorierst, kannst du in einer Runde viel schneller handeln. Deine Rüstungsklasse entspricht dann nur noch der deiner getragenen Rüstung, dafür bist du im Kampf deutlich schneller am Zug.}
{206}{}{Du schlägst härter zu, aber nicht besser. Deine Angriffe sind sehr brutal, aber es fehlt ihnen an Finesse. Du landest selten einen guten kritischen Treffer, verursachst im Nahkampf aber immer mehr Schaden.}
{207}{}{Du hast keine Zeit, gezielt anzugreifen, denn du attackierst schneller als normale Menschen. Schusswaffen und Wurfwaffen kosten dich einen Aktionspunkt weniger.}
{208}{}{Durch eine seltsame Wendung des Schicksals sterben die Menschen in deiner Nähe gewaltsam. Du siehst immer die schlimmste Art, wie jemand sterben kann.}
{209}{}{Das Gute ist, dass alle um dich herum im Kampf 50% mehr kritische Fehlschläge haben. Das Schlechte ist: Du auch!}
{210}{}{Während du aufgewachsen bist, hast du weniger kampforientierte Fertigkeiten gelernt. Deine Kampffertigkeiten beginnen auf einem niedrigeren Niveau, aber Erste Hilfe, Arzt, Sprache und Tausch sind deutlich verbessert.}
{211}{}{Du wirst leichter von Chems abhängig. Die Wahrscheinlichkeit, durch den Gebrauch von Chems abhängig zu werden, ist doppelt so hoch wie normal, aber du erholst dich schneller von ihren Nebenwirkungen.}
{212}{}{Chems wirken bei dir nur halb so lange wie normal, aber deine Wahrscheinlichkeit, abhängig zu werden, beträgt ebenfalls nur 50% of des Normalen.}
{213}{}{Du hast das „gewisse Etwas“. Angehörige des anderen Geschlechts fühlen sich zu dir hingezogen, manchmal sogar trotz deiner äußerlichen Makel. Angehörige des gleichen Geschlechts werden dagegen ziemlich eifersüchtig.}
{214}{}{Da du mehr Zeit darauf verwendet hast, deine Fertigkeiten zu verbessern als ein normaler Mensch, erhältst du pro Erfahrungsstufe 5 zusätzliche Fertigkeitspunkte. Dafür bekommst du nicht so viele zusätzliche Fähigkeiten. Du erhältst alle vier Stufen ein Talent.}
{215}{}{Du hast mehr angeborene Fähigkeiten als die meisten und hast deshalb weniger Zeit damit verbracht, deine Fertigkeiten zu schärfen. Jeder deiner Grundwerte ist um +1 erhöht, aber zu Beginn verlierst du -10% on auf alle Fertigkeiten und erhältst pro Stufe 5 Fertigkeitspunkte weniger.}