#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
#
# Text labels and messages used by town and world map
#
# ±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±?
#

# Vault 8
{200}{}{Ödland}
{201}{}{Vault City}
{202}{}{Vault-Türen}
{203}{}{Opalmine}
{204}{}{Vault 8}
{205}{}{Labor}
#
# Wind of War
{210}{}{Kostenloses Parken}
{211}{}{Vault}
{212}{}{Nicht-Wohnbereich}
#
# Sigma base
{220}{}{Fehler: leer}
{221}{}{Fehler: leer}
{222}{}{Fehler: leer}
{223}{}{Fehler: leer}
{224}{}{(Fehler: leer)}
{225}{}{(Fehler: leer)}
#
# Cheyenne
{230}{}{Stammeslager}
{231}{}{Basis der Raider}
{232}{}{Plantagen}
{233}{}{Radiostation}
#
# Fake Vault 13 B
{240}{}{Vault 15}
#
# Gecko
{250}{}{Siedlung}
{251}{}{Kraftwerk}
{252}{}{Schrottplatz}
{253}{}{Fehler: leer}
#
# Ailie
{260}{}{Eisenbahnknotenpunkt}
{261}{}{Wohngebiet}
{262}{}{Tempel}
{263}{}{Wetterstation}
#
# New Reno
{270}{}{Hotel „Silver“}
{271}{}{Eldorado}
{272}{}{Stadion}
{273}{}{Bahnhof}
{274}{}{Lucianos Ranch}
{275}{}{Boxarena}
{276}{}{Angriffsort}
{277}{}{Rathaus}
{278}{}{Freiluftkino}
{279}{}{Verlassene Farm}
#
# Area 51
{280}{}{Flugzeuglandeplatz}
{281}{}{Kaserne}
{282}{}{Hangar}
#
# Bridgeport
{290}{}{Bridgeport}
#
# New Vegas
{300}{}{Parkplatz}
{301}{}{Hoover Dam}
{302}{}{Clean City}
{303}{}{'Hard Rock' Café}
{304}{}{Sklavenstadt}
{305}{}{Dead Hotel}
#
# Provo
{310}{}{Bezirk Provo}
#
# Hawthorne
{320}{}{Bahnhof}
{321}{}{Tote Stadt}
{322}{}{Garnisonsgebiet}
{323}{}{Hangar V9}
{324}{}{Reaktoranlagen}
#
# West Wendover
{330}{}{Innenstadt}
{331}{}{Werkstatt}
{332}{}{Großer Hangar}
{333}{}{Die Vereinigung}
{334}{}{Jagdgebiet}
{335}{}{Ruinen von Wendover}
#
# Salt Lake
{340}{}{Geschäftszentrum}
{341}{}{Renaissanceplatz}
{342}{}{Bahndepot}
{343}{}{Abwasser-Canyon}
{344}{}{Tempel}
{345}{}{Elendsviertel}
{346}{}{Nuka-Cola-Fabrik}
#
# Rabie
{350}{}{Hütte}
#
# Vault X
{360}{}{Haltestelle}
{361}{}{Vault}
{362}{}{Vault-Eingang}
{363}{}{Vorübergehender Halt}
{364}{}{Präsidentenebene}
#
# Gerlach
{370}{}{Siedlung}
{371}{}{Jagdgründe}
#
# Uranium-City
{380}{}{Siedlung der Arbeiter}
#
# Vegas DrugSet
{390}{}{The Pound}
#
# Battle-Mountain, Radar
{400}{}{Hauptstraße}
{401}{}{Bikercamp}
#
# Car Out of Gas
{410}{}{Auto ohne Sprit}
#
# Destroyed Vault City
{420}{}{Verwüstete Stadt}
#
# ???
{430}{}{Wüste}
#
# Wind of War
{440}{}{Überfälle auf Patrouillen}
#
# Black-Rock
{450}{}{Siedlung}
{451}{}{Schwarze-Felsen-Höhlen}
#
# Random Encounter Desert
{460}{}{Wüste}
{461}{}{Wüste}
{462}{}{Wüste}
{463}{}{Wüste}
{464}{}{Verlassenes Lager}
{465}{}{Verlassene Farm}
{466}{}{Kaktusfeld}
{467}{}{Schwarzer Wald}
{468}{}{Schwarzer Wald}
{469}{}{Schwarzer Wald}
#
# Random Encounter Mountain
{470}{}{Berg}
{471}{}{Höhle}
{472}{}{Berg}
{473}{}{Höhle}
{474}{}{Höhle}
{475}{}{Höhle}
{476}{}{Höhle}
{477}{}{Höhle}
{478}{}{Berg}
{479}{}{Berg}
#
# Random Encounter City
{480}{}{Zerstörte Stadt}
{481}{}{Zerstörte Stadt}
{482}{}{Zerstörte Stadt}
{483}{}{Zerstörte Stadt}
{484}{}{Zerstörte Stadt}
{485}{}{Zerstörte Stadt}
{486}{}{Zerstörte Stadt}
{487}{}{Zerstörte Stadt}
{488}{}{Zerstörte Stadt}
#
# Random Encounter Coast
{490}{}{Küstenlinie}
{491}{}{Küstenlinie}
{492}{}{Küstenlinie}
{493}{}{Küstenlinie}
{494}{}{Küstenlinie}
{495}{}{Küstenlinie}
{496}{}{Küstenlinie}
{497}{}{Küstenlinie}
{498}{}{Küstenlinie}
{499}{}{Küstenlinie}
#
# PepGaz
{500}{}{Tankstelle}
#
# Special Encounter: Roads
{510}{}{Wegkreuzung.}
#
# Special Encounter: AnalDen
{520}{}{Großes Loch.}
#
# Special Encounter: MineField
{521}{}{Reifenhalde.}
#
# Special Encounter: Crashed Federation Shuttle
{530}{}{Tanklaster in der Wüste.}
#
# Special Encounter: Unwashed Villagers
{540}{}{Wüste}
#
# Special Encounter: Interplay Office
{550}{}{Verlassenes Büro.}
#
# Special Encounter: Cafe
{560}{}{Café "New Hope".}
#
# Special Encounter: Big Egg
{570}{}{Wüste}
#
# Special Encounter: Bobby
{580}{}{Wüste}
#
# Special Encounter: HomeRoad
{590}{}{Haus auf Rädern.}
#
# Special Encounter: Bus Of Ken
{600}{}{"Furthur".}
#
# Rangers post
{610}{}{Verlassene Rangerstation.}
#
# Special Encounter: Picnic
{620}{}{Picknickplatz.}
#
# Caravan Encounters
{630}{}{Wüste}
{631}{}{Berg}
#
# Atomic
{640}{}{"Lieber John".}
#
# Harrelson
{650}{}{Harrelsons Schutzraum}
#
# Shadow Areas (Those which fit nowhere else)
{660}{}{Küstenlinie}
{661}{}{Küstenlinie}
{662}{}{Wüste}
{663}{}{Wüste}
{664}{}{Wüste}
{665}{}{Berg}
{666}{}{Berg}
{667}{}{Wüste}
{668}{}{Parkplatz}
{669}{}{Beängstigende Stille}
#
# Environmental Protection Agency
{670}{}{Straße}



#
# Terrain type names for world map hover button
#
{1000}{}{Wüste}
{1001}{}{Berge}
{1002}{}{Stadt}
{1003}{}{Küste}
{1004}{}{Unbekannt}  # Unknown/visited city


# Misc messages
{1500}{}{Du hast 10.000 Erfahrungspunkte erhalten!}
{1501}{}{Ruinen}
{1502}{}{Dem Auto ist der Sprit ausgegangen.}
{1503}{}{Das ist ein Auto. Es sieht nicht so aus, als würde es noch fahren.}


#
# Worldmap Encounter messages
#

{2998}{}{Du triffst auf:}
{2999}{}{Möchtest du auf Folgendes treffen:}

# Encounter Table 0
{3000}{}{Eine Gruppe von Plünderern.}
{3001}{}{Ein paar Radskorpione.}
{3002}{}{Riesenratten.}
{3003}{}{Eine Händlergruppe.}
{3004}{}{<Spezial>}

# Encounter Table 1
{3050}{}{Eine Gruppe von Plünderern.}
{3051}{}{Ein Schwarm Gottesanbeterinnen.}
{3052}{}{Eine Gruppe Geckos.}
{3053}{}{Eine Gruppe Maulwurfsratten.}
{3054}{}{Eine Gruppe Radskorpione.}
{3055}{}{Eine Gruppe Riesenratten.}
{3056}{}{Eine Händlergruppe.}
{3057}{}{<Spezial>}

# Encounter Table 2
{3100}{}{Eine Gruppe von Plünderern.}
{3101}{}{Eine Gruppe Radskorpione.}
{3102}{}{Eine Gruppe Riesenratten.}
{3103}{}{Eine Händlergruppe.}
{3104}{}{<Spezial>}

# Encounter Table 3
{3150}{}{Eine Gruppe von Plünderern.}

# Encounter Table 4
{3200}{}{Eine Gruppe von Plünderern.}

# Encounter Table 5
{3250}{}{Eine Gruppe von Plünderern.}

# Encounter Table 6 -- VCTY_M (Mountains around vault 8)
{3300}{}{Eine Gruppe Silbergeckos.}
{3301}{}{Ein Schwarm Geckos.}
{3302}{}{Eine Gruppe Schädlinge.}
{3303}{}{Eine kleine Gruppe Maulwurfsratten.}
{3304}{}{Eine kleine Gruppe Radskorpione.}
{3305}{}{Vault City-Patrouille.}
{3306}{}{Vault City-Patrouille, die eine Geckohorde abwehrt.}
{3307}{}{Vault City-Patrouille im Kampf mit Radskorpionen.}

# Encounter Table 7 -- VCTY_D (Mountains around vault 8)
{3350}{}{Eine Gruppe Silbergeckos.}
{3351}{}{Ein Schwarm Geckos.}
{3352}{}{Eine Gruppe Schädlinge.}
{3353}{}{Eine kleine Gruppe Maulwurfsratten.}
{3354}{}{Eine kleine Gruppe Radskorpione.}
{3355}{}{Eine Herde brahmin.}
{3356}{}{Eine Kojotenhorde.}
{3357}{}{Eine Herde brahmin, die einen Angriff von Geckos abwehrt.}
{3358}{}{Riesenei.}

# Encounter Table 8 -- BLRCK
{3400}{}{Eine Gruppe Silbergeckos.}
{3401}{}{Eine Gruppe Schädlinge.}
{3402}{}{Eine kleine Gruppe Maulwurfsratten.}
{3403}{}{Eine kleine Gruppe Radskorpione.}
{3404}{}{Eine Herde wilder brahmin.}
{3405}{}{Eine Kojotenhorde.}
{3406}{}{Eine Herde brahmin, die einen Angriff von Geckos abwehrt.}
{3407}{}{Jäger von Wüstenleguanen.}

# Encounter Table 9 -- SGMA_M
{3450}{}{Reinigungsroboter.}
{3451}{}{Eine Gruppe Schädlinge.}
{3452}{}{Eine kleine Gruppe Maulwurfsratten.}
{3453}{}{Eine kleine Gruppe Schweineratten.}
{3454}{}{Eine kleine Gruppe Radskorpione.}
{3455}{}{Eine Herde wilder brahmin.}
{3456}{}{Ein Wolfsrudel.}
{3457}{}{Café "New Hope".}
{3458}{}{Wegkreuzung.}
{3459}{}{Großes Loch.}
{3460}{}{Picknickplatz.}
{3461}{}{Haus auf Rädern.}
{3462}{}{"Furthur".}
{3463}{}{Riesenei.}

# Encounter Table 10 -- SGMA_D
{3500}{}{Eine Gruppe fleischfressender Pflanzen.}
{3501}{}{Eine Gruppe Schädlinge.}
{3502}{}{Eine kleine Gruppe Maulwurfsratten.}
{3503}{}{Eine kleine Gruppe Schweineratten.}
{3504}{}{Eine kleine Gruppe Radskorpione.}
{3505}{}{Eine Herde wilder brahmin.}
{3506}{}{Ein Wolfsrudel.}
{3507}{}{Jägertrupp.}
{3508}{}{Jägertrupp im Kampf mit Radskorpionen.}
{3509}{}{Jägertrupp im Kampf mit Maulwurfsratten.}
{3510}{}{Jägertrupp, der einen Angriff eines Wolfsrudels zurückschlägt.}
{3511}{}{Eine Herde brahmin, die Wölfe abwehrt.}
{3512}{}{Legendärer Radskorpion.}
{3513}{}{Verlassenes Büro.}
{3514}{}{Wegkreuzung.}
{3515}{}{Café "New Hope".}
{3516}{}{Großes Loch.}
{3517}{}{Picknickplatz.}
{3518}{}{Haus auf Rädern.}
{3519}{}{"Furthur".}
{3520}{}{Riesenei.}
{3521}{}{"Lieber John".}
{3522}{}{Eine Kojotenhorde.}
{3523}{}{Wasser!}

# Encounter Table 11 -- SGMA_T
{3550}{}{Eine kleine Gruppe Radskorpione auf der Straße.}
{3551}{}{Eine Herde brahmin, die die Straße überquert.}
{3552}{}{Ein Rudel wilder Hunde, das die Straße entlangläuft.}
{3553}{}{Eine Gruppe Fischer auf dem Rückweg vom Fischen.}
{3554}{}{Eine Gruppe Einwanderer.}
{3555}{}{Gruppe von Farmern.}
{3556}{}{Räuberbande, die im Hinterhalt lauert.}
{3557}{}{Plündererbande, die im Hinterhalt lauert.}
{3558}{}{Gruppe von Jägern, die einen Angriff von Plünderern abwehrt.}
{3559}{}{Gruppe von Jägern, die einen Angriff von Räubern abwehrt.}
{3560}{}{Gruppe von Jägern, die einen Angriff von Radskorpionen abwehrt.}
{3561}{}{Gruppe von Jägern, die einen Angriff von Räubern abwehrt.}
{3562}{}{Gruppe von Jägern, die einen Angriff von Radskorpionen abwehrt.}
{3563}{}{Karawane, die die Straße entlangzieht.}
{3564}{}{Wegkreuzung.}
{3565}{}{Verlassenes Büro.}
{3566}{}{Großes Loch.}
{3567}{}{Café "New Hope".}
{3568}{}{Haus auf Rädern.}
{3569}{}{"Furthur".}
{3570}{}{Anhalter.}
{3571}{}{Fröhlicher Bobby.}

# Encounter Table 12 -- SALT_O
{3600}{}{Eine Gruppe Schädlinge.}
{3601}{}{Ein Rudel Wildhunde.}
{3602}{}{Eine Herde wilder brahmin.}
{3603}{}{Eine Gruppe Säuregeckos.}
{3604}{}{Jägertrupp.}
{3605}{}{Gruppe von Jägern, die gegen Ungeziefer kämpft.}
{3606}{}{Gruppe von Jägern, die einen Angriff von Wildhunden abwehrt.}
{3607}{}{Gruppe von Jägern, die einen Angriff von Banditen abwehrt.}
{3608}{}{Gruppe von Banditen.}
{3609}{}{Gruppe von Banditen, die einen Angriff von Wildhunden abwehrt.}
{3610}{}{Entflohene Sträflinge.}
{3611}{}{Punks aus der Stadt Salt Lake.}

# Encounter Table 13 -- SALT_T
{3650}{}{Kleine Gruppe Ungeziefer, die auf der Straße festsitzt.}
{3651}{}{Eine kleine Gruppe Radskorpione auf der Straße.}
{3652}{}{Herde von brahmin, die die Straße entlangzieht.}
{3653}{}{Ein Rudel wilder Hunde, das die Straße entlangläuft.}
{3654}{}{Gruppe von Jägern auf dem Rückweg in die Stadt.}
{3655}{}{Gruppe von Banditen, die im Hinterhalt lauert.}
{3656}{}{Gruppe von Marodeuren, die im Hinterhalt lauert.}
{3657}{}{Gruppe von Plünderern, die im Hinterhalt lauert.}
{3658}{}{Gruppe von Jägern, die einen Angriff von Marodeuren abwehrt.}
{3659}{}{Gruppe von Jägern, die einen Angriff von Plünderern abwehrt.}
{3660}{}{Gruppe von Jägern, die einen Angriff von Räubern abwehrt.}
{3661}{}{Gruppe von Jägern, die einen Angriff von Radskorpionen abwehrt.}
{3662}{}{Karawane, die die Straße entlangzieht.}
{3663}{}{Wegkreuzung.}
{3664}{}{Verlassenes Büro.}
{3665}{}{Café "New Hope".}
{3666}{}{Haus auf Rädern.}
{3667}{}{"Furthur".}
{3668}{}{Anhalter.}
{3669}{}{Fröhlicher Bobby.}
{3670}{}{Kopfgeldjäger aus der Stadt Salt Lake, die das Kopfgeld auf dich kassieren wollen.}
{3671}{}{Kopfgeldjäger aus der Stadt Salt Lake, die das Kopfgeld auf dich kassieren wollen.}
{3672}{}{Kopfgeldjäger aus der Stadt Salt Lake, die das Kopfgeld auf dich kassieren wollen.}
{3673}{}{Verrückter Mr. Handy.}
{3674}{}{Autowrack auf dem Weg in die Stadt.}
{3675}{}{Zäher Bandit mit einem Presslufthammer.}
{3676}{}{Entflohene Sträflinge.}
{3677}{}{Punks aus der Stadt Salt Lake.}
{3678}{}{Nomaden der Great Basin.}

# Encounter Table 14 -- RDRS_T
{3700}{}{Kleine Gruppe Ungeziefer, die auf der Straße festsitzt.}
{3701}{}{Eine kleine Gruppe Geckos ist plötzlich auf der Straße aufgetaucht!}
{3702}{}{Eine kleine Gruppe Radskorpione auf der Straße.}
{3703}{}{Herde von brahmin, die die Straße entlangzieht.}
{3704}{}{Ein Rudel wilder Hunde, das die Straße entlangläuft.}
{3705}{}{Cheyennes auf dem Rückweg von der Jagd.}
{3706}{}{Eine Gruppe Einwanderer.}
{3707}{}{Gruppe von Banditen, die im Hinterhalt lauert.}
{3708}{}{Plünderer von Big Louie.}
{3709}{}{Plünderer von Big Louie.}
{3710}{}{Gruppe von Jägern, die einen Angriff von Räubern abwehrt.}
{3711}{}{Gruppe von Jägern, die einen Angriff von Banditen abwehrt.}
{3712}{}{Karawane, die die Straße entlangzieht.}
{3713}{}{Wegkreuzung.}
{3714}{}{Café "New Hope".}
{3715}{}{Haus auf Rädern.}
{3716}{}{"Furthur".}
{3717}{}{Anhalter.}
{3718}{}{Fröhlicher Bobby.}

# Encounter Table 15 -- RDRS_D
{3750}{}{Eine Gruppe fleischfressender Pflanzen.}
{3751}{}{Eine Gruppe Silbergeckos.}
{3752}{}{Ein Schwarm Geckos.}
{3753}{}{Eine Gruppe Schädlinge.}
{3754}{}{Eine kleine Gruppe Maulwurfsratten.}
{3755}{}{Eine kleine Gruppe Schweineratten.}
{3756}{}{Eine kleine Gruppe Radskorpione.}
{3757}{}{Eine Herde brahmin.}
{3758}{}{Wilde Hunde.}
{3759}{}{Cheyennes auf dem Rückweg von der Jagd.}
{3760}{}{Eine Gruppe Jäger.}
{3761}{}{Eine Gruppe Banditen.}
{3762}{}{Plünderer von Big Louie.}
{3763}{}{Plünderer von Big Louie.}
{3764}{}{Eine Gruppe Jäger kämpft gegen Radskorpione.}
{3765}{}{Eine Gruppe Jäger kämpft gegen Wölfe.}
{3766}{}{Eine Gruppe Jäger kämpft gegen Raider.}
{3767}{}{Eine Gruppe Jäger kämpft gegen Banditen.}
{3768}{}{Wegkreuzung.}
{3769}{}{Café "New Hope".}
{3770}{}{Verlassenes Büro.}
{3771}{}{Großes Loch.}
{3772}{}{Picknickplatz.}
{3773}{}{Haus auf Rädern.}
{3774}{}{"Furthur".}
{3775}{}{Riesenei.}
{3776}{}{Anhalter.}
{3777}{}{Fröhlicher Bobby.}
{3778}{}{"Lieber John".}

# Encounter Table 16 -- RDRS_M
{3800}{}{Eine Gruppe fleischfressender Pflanzen.}
{3801}{}{Eine Gruppe Silbergeckos.}
{3802}{}{Ein Schwarm Geckos.}
{3803}{}{Eine Gruppe Schädlinge.}
{3804}{}{Eine kleine Gruppe Maulwurfsratten.}
{3805}{}{Eine kleine Gruppe Radskorpione.}
{3806}{}{Eine Herde brahmin.}
{3807}{}{Ein Wolfsrudel.}
{3808}{}{Cheyennes auf dem Rückweg von der Jagd.}
{3809}{}{Eine Gruppe Jäger.}
{3810}{}{Plünderer von Big Louie.}
{3811}{}{Plünderer von Big Louie.}
{3812}{}{Eine Gruppe Jäger kämpft gegen Radskorpione.}
{3813}{}{Eine Gruppe Jäger wehrt einen Wolfsangriff ab.}
{3814}{}{Eine Gruppe Jäger kämpft gegen Raider.}
{3815}{}{Eine Gruppe Cheyennes wehrt einen Wolfsangriff ab.}
{3816}{}{Café "New Hope".}
{3817}{}{Großes Loch.}
{3818}{}{Picknickplatz.}
{3819}{}{Haus auf Rädern.}
{3820}{}{"Furthur".}
{3821}{}{Riesenei.}
{3822}{}{"Lieber John".}

# Encounter Table 17 -- RINO_T
{3850}{}{Ein Rudel wilder Hunde, das die Straße entlangläuft.}
{3851}{}{Eine kleine Gruppe Radskorpione auf der Straße.}
{3852}{}{Kleine Gruppe Ungeziefer, die auf der Straße festsitzt.}
{3853}{}{Herde von brahmin, die die Straße entlangzieht.}
{3854}{}{Eine Gruppe Sklavenhändler mit ihren Sklaven.}
{3855}{}{Eine Gruppe Sklavenhändler versucht, einige Leute zu versklaven.}
{3856}{}{Eine Bande Sklavenhändler und ein paar Hunde.}
{3857}{}{Stadtbande.}
{3858}{}{Räuberbande, die im Hinterhalt lauert.}
{3859}{}{Plündererbande, die im Hinterhalt lauert.}
{3860}{}{Gruppe von Marodeuren, die im Hinterhalt lauert.}
{3861}{}{Eine Karawane zieht durch die Ruinen.}
{3862}{}{Anhalter.}
{3863}{}{Kopfgeldjäger aus New Reno wollen das Kopfgeld auf dich kassieren.}
{3864}{}{Kopfgeldjäger aus New Reno wollen das Kopfgeld auf dich kassieren.}
{3865}{}{Kopfgeldjäger aus New Reno wollen das Kopfgeld auf dich kassieren.}
{3866}{}{Räuber lauern auf einsame Reisende.}

# Encounter Table 18 -- RED_D
{3900}{}{Eine Gruppe fleischfressender Pflanzen.}
{3901}{}{Eine Gruppe Silbergeckos.}
{3902}{}{Ein Schwarm Geckos.}
{3903}{}{Eine Gruppe Goldgeckos.}
{3904}{}{Eine Gruppe Schädlinge.}
{3905}{}{Eine kleine Gruppe Maulwurfsratten.}
{3906}{}{Eine kleine Gruppe Schweineratten.}
{3907}{}{Eine kleine Gruppe Radskorpione.}
{3908}{}{Ein Wolfsrudel.}
{3909}{}{Ein Nachtschattenstrauch, bewacht von Ameisen.}
{3910}{}{Wegkreuzung.}
{3911}{}{Großes Loch.}
{3912}{}{"Lieber John".}
{3913}{}{Picknickplatz.}
{3914}{}{Haus auf Rädern.}
{3915}{}{"Furthur".}
{3916}{}{Riesenei.}
{3917}{}{Fröhlicher Bobby.}
{3918}{}{Mutierte Vogelspinnen.}

# Encounter Table 19 -- RED_M
{3950}{}{Eine Gruppe fleischfressender Pflanzen.}
{3951}{}{Eine Gruppe Silbergeckos.}
{3952}{}{Ein Schwarm Geckos.}
{3953}{}{Eine Gruppe Goldgeckos.}
{3954}{}{Eine Gruppe Schädlinge.}
{3955}{}{Eine kleine Gruppe Maulwurfsratten.}
{3956}{}{Eine kleine Gruppe Schweineratten.}
{3957}{}{Ein Wolfsrudel.}
{3958}{}{Ein Nachtschattenstrauch, bewacht von Ameisen.}
{3959}{}{Ein Körper unter der Gerölllawine.}
{3960}{}{Großes Loch.}
{3961}{}{Picknickplatz.}
{3962}{}{"Lieber John".}
{3963}{}{"Furthur".}
{3964}{}{Riesenei.}
{3965}{}{Ein verlassener Stützpunkt der Nevada-Ranger.}
{3966}{}{Mutierte Vogelspinnen.}

# Encounter Table 20 -- SALTk_D
{4000}{}{Eine Gruppe Säuregeckos.}
{4001}{}{Eine Gruppe Schädlinge.}
{4002}{}{Eine kleine Gruppe Maulwurfsratten.}
{4003}{}{Eine kleine Gruppe Schweineratten.}
{4004}{}{Eine kleine Gruppe Radskorpione.}
{4005}{}{Eine Herde brahmin.}
{4006}{}{Ein Rudel Wildhunde.}
{4007}{}{Eine Gruppe Jäger.}
{4008}{}{Eine Bande Raider.}
{4009}{}{Gruppe von Banditen.}
{4010}{}{Eine Gruppe Banditen teilt ihre Beute mit Raidern.}
{4011}{}{Gruppe von Jägern, die einen Angriff von Plünderern abwehrt.}
{4012}{}{Gruppe von Jägern, die einen Angriff von Banditen abwehrt.}
{4013}{}{Ein Tanklaster in der Wüste.}
{4014}{}{Großes Loch.}
{4015}{}{Anhalter.}
{4016}{}{Entflohene Sträflinge.}
{4017}{}{Punks aus der Stadt Salt Lake.}
{4018}{}{Filterjäger.}

# Encounter Table 21 -- VGSLT_T
{4050}{}{Kleine Gruppe Ungeziefer, die auf der Straße festsitzt.}
{4051}{}{Eine kleine Gruppe Radskorpione auf der Straße.}
{4052}{}{Herde von brahmin, die die Straße entlangzieht.}
{4053}{}{Ein Rudel wilder Hunde, das die Straße entlangläuft.}
{4054}{}{Eine Gruppe Jäger auf dem Rückweg in die Stadt.}
{4055}{}{Gruppe von Banditen, die im Hinterhalt lauert.}
{4056}{}{Eine Gruppe Einwanderer.}
{4057}{}{Räuberbande, die im Hinterhalt lauert.}
{4058}{}{Plündererbande, die im Hinterhalt lauert.}
{4059}{}{Gruppe von Jägern, die einen Angriff von Plünderern abwehrt.}
{4060}{}{Gruppe von Jägern, die einen Angriff von Räubern abwehrt.}
{4061}{}{Karawane, die die Straße entlangzieht.}
{4062}{}{Einheimische, die den Weg des Verbrechens gewählt haben.}
{4063}{}{Wegkreuzung.}
{4064}{}{Verlassenes Büro.}
{4065}{}{Café "New Hope".}
{4066}{}{Haus auf Rädern.}
{4067}{}{"Furthur".}
{4068}{}{Anhalter.}
{4069}{}{Fröhlicher Bobby.}
{4070}{}{Lynchjustiz.}
{4071}{}{Filterjäger.}
{4072}{}{Nomaden der Great Basin.}

# Encounter Table 22 -- RINO_D
{4100}{}{Eine Gruppe fleischfressender Pflanzen.}
{4101}{}{Opfer der Apokalypse.}
{4102}{}{Eine Gruppe Schädlinge.}
{4103}{}{Eine kleine Gruppe Maulwurfsratten.}
{4104}{}{Eine kleine Gruppe Schweineratten.}
{4105}{}{Eine kleine Gruppe Radskorpione.}
{4106}{}{Eine Herde brahmin.}
{4107}{}{Wilde, wütende brahmin.}
{4108}{}{Eine Gruppe Jäger.}
{4109}{}{Eine Bande Raider.}
{4110}{}{Gruppe von Jägern, die einen Angriff von Plünderern abwehrt.}
{4111}{}{Café "New Hope".}
{4112}{}{Verlassenes Büro.}
{4113}{}{Großes Loch.}
{4114}{}{Wegkreuzung.}
{4115}{}{Anhalter.}
{4116}{}{Picknickplatz.}
{4117}{}{Haus auf Rädern.}
{4118}{}{"Furthur".}
{4119}{}{Riesenei.}
{4120}{}{Fröhlicher Bobby.}
{4121}{}{"Lieber John".}

# Encounter Table 23 -- South_D
{4150}{}{Eine kleine Gruppe Maulwurfsratten.}
{4151}{}{Eine kleine Gruppe Radskorpione.}
{4152}{}{Eine Kojotenhorde.}
{4153}{}{Ein Rudel Todeskrallen.}
{4154}{}{Café "New Hope".}
{4155}{}{Verlassenes Büro.}
{4156}{}{Großes Loch.}
{4157}{}{Wegkreuzung.}
{4158}{}{Picknickplatz.}
{4159}{}{Haus auf Rädern.}
{4160}{}{"Furthur".}
{4161}{}{Riesenei.}
{4162}{}{Hardys Karawane.}
{4163}{}{"Lieber John".}
{4164}{}{Wasser!}
{4165}{}{Versiegende Quelle und Maulwurfsratten.}
{4166}{}{Versiegende Quelle und Radskorpione.}
{4167}{}{Versiegende Quelle und fleischfressende Pflanzen.}
{4168}{}{Versiegende Quelle und ein Schwarm Gottesanbeterinnen.}
{4169}{}{Schwarm Gottesanbeterinnen.}

# Encounter Table 24 -- South_M
{4200}{}{Eine Gruppe fleischfressender Pflanzen.}
{4201}{}{Schwarm Gottesanbeterinnen.}
{4202}{}{Eine Gruppe Goldgeckos.}
{4203}{}{Ein Schwarm Geckos.}
{4204}{}{Eine Gruppe Schädlinge.}
{4205}{}{Eine kleine Gruppe Maulwurfsratten.}
{4206}{}{Eine kleine Gruppe Schweineratten.}
{4207}{}{Eine kleine Gruppe Radskorpione.}
{4208}{}{Eine Herde brahmin.}
{4209}{}{Ein Wolfsrudel.}
{4210}{}{Kojotenjäger, die ihre Beute jagen.}
{4211}{}{Anführer des Kojotenstamms.}
{4212}{}{Café "New Hope".}
{4213}{}{Großes Loch.}
{4214}{}{Wegkreuzung.}
{4215}{}{Picknickplatz.}
{4216}{}{"Furthur".}
{4217}{}{Riesenei.}
{4218}{}{Fröhlicher Bobby.}
{4219}{}{"Lieber John".}
{4220}{}{Stamm von Kannibalen beim Mittagessen.}

# Encounter Table 25 -- Wind_T
{4250}{}{Kleine Gruppe Ungeziefer, die auf der Straße festsitzt.}
{4251}{}{Kleine Gruppe Maulwurfsratten, die auf der Straße festsitzt.}
{4252}{}{Kleine Gruppe Schweineratten, die auf der Straße lebt.}
{4253}{}{Kleine Gruppe Aliens, die sich versehentlich in diese Gegend verirrt hat.}
{4254}{}{Eine Gruppe Silbergeckos ist plötzlich auf der Straße aufgetaucht!}
{4255}{}{Ein Rudel Geckos ist plötzlich auf der Straße aufgetaucht!}
{4256}{}{Eine Gruppe Goldgeckos ist plötzlich auf der Straße aufgetaucht!}
{4257}{}{Ein Schwarm Gottesanbeterinnen zieht die Straße entlang.}
{4258}{}{Eine kleine Gruppe Radskorpione auf der Straße.}
{4259}{}{Herde von brahmin, die die Straße entlangzieht.}
{4260}{}{Ein Rudel wilder Hunde, das die Straße entlangläuft.}
{4261}{}{Eine Gruppe Sklavenhändler mit ihren Sklaven.}
{4262}{}{Eine Gruppe Sklavenhändler versucht, einige Leute zu versklaven.}
{4263}{}{Eine Bande Sklavenhändler und ein paar Hunde.}
{4264}{}{Gruppe von Jägern auf dem Rückweg in die Stadt.}
{4265}{}{Gruppe von Banditen, die im Hinterhalt lauert.}
{4266}{}{Eine Gruppe Einwanderer.}
{4267}{}{Gruppe von Farmern, die auf der Straße umherirrt.}
{4268}{}{Räuberbande, die im Hinterhalt lauert.}
{4269}{}{Plündererbande, die im Hinterhalt lauert.}
{4270}{}{Gruppe von Marodeuren, die im Hinterhalt lauert.}
{4271}{}{Gruppe von Jägern, die einen Angriff von Marodeuren abwehrt.}
{4272}{}{Gruppe von Jägern, die einen Angriff von Plünderern abwehrt.}
{4273}{}{Gruppe von Jägern, die einen Angriff von Räubern abwehrt.}
{4274}{}{Gruppe von Farmern, die einen Angriff von Marodeuren abwehrt.}
{4275}{}{Gruppe von Farmern, die einen Angriff von Plünderern abwehrt.}
{4276}{}{Gruppe von Farmern, die einen Angriff von Räubern abwehrt.}
{4277}{}{Gruppe von Farmern, die einen Angriff von Radskorpionen abwehrt.}
{4278}{}{Karawane, die die Straße entlangzieht.}
{4279}{}{Super 8.}
{4280}{}{Wegkreuzung.}
{4281}{}{Verlassenes Büro.}
{4282}{}{Café "New Hope".}
{4283}{}{Haus auf Rädern.}
{4284}{}{Fröhlicher Bobby.}
{4285}{}{Verzweifelter Neuling, der einen Angriff von Plünderern abzuwehren versucht.}

# Encounter Table 26 -- Wind_D
{4300}{}{Eine Gruppe fleischfressender Pflanzen.}
{4301}{}{Gruppe von Aliens.}
{4302}{}{Schwarm Gottesanbeterinnen.}
{4303}{}{Eine Gruppe Goldgeckos.}
{4304}{}{Ein Schwarm Geckos.}
{4305}{}{Eine Gruppe Schädlinge.}
{4306}{}{Eine kleine Gruppe Maulwurfsratten.}
{4307}{}{Eine kleine Gruppe Radskorpione.}
{4308}{}{Eine Herde brahmin.}
{4309}{}{Ein Rudel Wildhunde.}
{4310}{}{Eine Gruppe Sklavenhändler mit ihren Sklaven.}
{4311}{}{Eine Gruppe Sklavenhändler versucht, einige Leute zu versklaven.}
{4312}{}{Bande von Sklavenhändlern und ein paar Hunde.}
{4313}{}{Eine Gruppe Jäger.}
{4314}{}{Bande von Banditen.}
{4315}{}{Eine Bande Raider.}
{4316}{}{Gruppe von Jägern, die einen Angriff von Plünderern abwehrt.}
{4317}{}{Gruppe von Jägern, die einen Angriff von Banditen abwehrt.}
{4318}{}{Gruppe von Jägern, die einen Angriff von Wildhunden abwehrt.}
{4319}{}{Gruppe von Jägern, die einen Angriff von Radskorpionen abwehrt.}
{4320}{}{Gruppe von Jägern, die einen Gecko-Angriff abwehrt.}
{4321}{}{Gruppe von Jägern, die einen Angriff von Gottesanbeterinnen abwehrt.}
{4322}{}{Gruppe von Jägern, die einen Angriff von Aliens abwehrt.}
{4323}{}{Gruppe von Banditen, die einen Angriff von Aliens abwehrt.}
{4324}{}{Bande von Plünderern, die einen Angriff von Aliens abwehrt.}
{4325}{}{Super 8.}
{4326}{}{Wegkreuzung.}
{4327}{}{Großes Loch.}
{4328}{}{Café "New Hope".}
{4329}{}{Picknickplatz.}
{4330}{}{Haus auf Rädern.}
{4331}{}{"Furthur".}
{4332}{}{Riesenei.}
{4333}{}{Fröhlicher Bobby.}
{4334}{}{"Lieber John".}
{4335}{}{Verzweifelter Neuling, der einen Angriff von Plünderern abzuwehren versucht.}

# Encounter Table 27 -- Wind_M
{4350}{}{Eine Gruppe fleischfressender Pflanzen.}
{4351}{}{Schwarm Gottesanbeterinnen.}
{4352}{}{Eine Gruppe Goldgeckos.}
{4353}{}{Ein Schwarm Geckos.}
{4354}{}{Eine Gruppe Schädlinge.}
{4355}{}{Eine kleine Gruppe Maulwurfsratten.}
{4356}{}{Eine kleine Gruppe Radskorpione.}
{4357}{}{Eine Herde brahmin.}
{4358}{}{Ein Wolfsrudel.}
{4359}{}{Eine Gruppe Jäger.}
{4360}{}{Super 8.}
{4361}{}{Großes Loch.}
{4362}{}{Café "New Hope".}
{4363}{}{Picknickplatz.}
{4364}{}{Haus auf Rädern.}
{4365}{}{"Furthur".}
{4366}{}{Riesenei.}
{4367}{}{Fröhlicher Bobby.}
{4368}{}{"Lieber John".}
{4369}{}{Verzweifelter Neuling, der einen Angriff von Plünderern abzuwehren versucht.}

# Encounter Table 28 -- Zona_D
{4400}{}{Gruppe von Aliens.}
{4401}{}{Ein Schwarm Geckos.}
{4402}{}{Eine Gruppe Goldgeckos.}
{4403}{}{Eine kleine Gruppe Radskorpione.}
{4404}{}{Großes Loch.}

# Encounter Table 29 -- VGSX_T
{4450}{}{Kleine Gruppe Ungeziefer, die auf der Straße festsitzt.}
{4451}{}{Eine kleine Gruppe Radskorpione auf der Straße.}
{4452}{}{Herde von brahmin, die die Straße entlangzieht.}
{4453}{}{Karawane, die die Straße entlangzieht.}
{4454}{}{Einheimische, die den Weg des Verbrechens gewählt haben.}
{4455}{}{Einer der Bloom-Brüder.}
{4456}{}{Wegkreuzung.}
{4457}{}{Verlassenes Büro.}
{4458}{}{Café "New Hope".}
{4459}{}{Haus auf Rädern.}
{4460}{}{"Furthur".}
{4461}{}{Anhalter.}
{4462}{}{Fröhlicher Bobby.}
{4463}{}{Lynchjustiz.}
{4464}{}{Filterjäger.}
{4465}{}{Nomaden der Great Basin.}

# Encounter Table 30 -- VEGS_T
{4500}{}{Kleine Gruppe Ungeziefer, die auf der Straße festsitzt.}
{4501}{}{Ein Schwarm Gottesanbeterinnen zieht die Straße entlang.}
{4502}{}{Eine Gruppe silberner Geckos ist plötzlich auf der Straße aufgetaucht.}
{4503}{}{Eine kleine Gruppe Radskorpione auf der Straße.}
{4504}{}{Herde von brahmin, die die Straße entlangzieht.}
{4505}{}{Ein Rudel wilder Hunde, das die Straße entlangläuft.}
{4506}{}{Eine Gruppe Sklavenhändler mit ihren Sklaven.}
{4507}{}{Eine Gruppe Sklavenhändler versucht, einige Leute zu versklaven.}
{4508}{}{Bande von Sklavenhändlern und ein paar Hunde.}
{4509}{}{Gruppe von Banditen, die im Hinterhalt lauert.}
{4510}{}{Gruppe von Farmern, die auf der Straße umherirrt.}
{4511}{}{Räuberbande, die im Hinterhalt lauert.}
{4512}{}{Plündererbande, die im Hinterhalt lauert.}
{4513}{}{Gruppe von Farmern, die einen Angriff von Marodeuren abwehrt.}
{4514}{}{Gruppe von Farmern, die einen Angriff von Plünderern abwehrt.}
{4515}{}{Gruppe von Farmern, die einen Angriff von Räubern abwehrt.}
{4516}{}{Gruppe von Farmern, die einen Angriff von Radskorpionen abwehrt.}
{4517}{}{Eine Karawane zieht durch die Ruinen.}
{4518}{}{Wegkreuzung.}
{4519}{}{Verlassenes Büro.}
{4520}{}{Großes Loch.}
{4521}{}{Café "New Hope".}
{4522}{}{Haus auf Rädern.}
{4523}{}{"Furthur".}
{4524}{}{Fröhlicher Bobby.}
{4525}{}{Kopfgeldjäger von Las Vegas, die das auf dich ausgesetzte Kopfgeld kassieren wollen.}
{4526}{}{Kopfgeldjäger von Las Vegas, die das auf dich ausgesetzte Kopfgeld kassieren wollen.}
{4527}{}{Kopfgeldjäger von Las Vegas, die das auf dich ausgesetzte Kopfgeld kassieren wollen.}
{4528}{}{Agent einer Patrouillenagentur, der zum Wilden geworden ist.}
{4529}{}{Neon Gangster und seine Bande.}
{4530}{}{Filterjäger.}
{4531}{}{Die Bande der Kings.}
{4532}{}{Verzweifelter Hinterwäldler.}
{4533}{}{Perverser mit seiner Sexsklavin.}
{4534}{}{Zwei Mitglieder der Kings-Bande versuchen, eine Leiche zu begraben.}

# Encounter Table 31 -- VEGS_D
{4550}{}{Eine Gruppe fleischfressender Pflanzen.}
{4551}{}{Schwarm Gottesanbeterinnen.}
{4552}{}{Eine Gruppe Silbergeckos.}
{4553}{}{Ein Schwarm Geckos.}
{4554}{}{Eine Gruppe Schädlinge.}
{4555}{}{Eine kleine Gruppe Maulwurfsratten.}
{4556}{}{Eine kleine Gruppe Schweineratten.}
{4557}{}{Eine kleine Gruppe Radskorpione.}
{4558}{}{Eine Herde brahmin.}
{4559}{}{Eine Kojotenhorde.}
{4560}{}{Ein Wolfsrudel.}
{4561}{}{Eine Gruppe Sklavenhändler mit ihren Sklaven.}
{4562}{}{Eine Gruppe Sklavenhändler versucht, einige Leute zu versklaven.}
{4563}{}{Bande von Sklavenhändlern und ein paar Hunde.}
{4564}{}{Eine Gruppe Jäger.}
{4565}{}{Eine Bande Raider.}
{4566}{}{Eine Bande von Plünderern greift Jäger an.}
{4567}{}{Eine Bande von Plünderern wehrt einen Angriff von Radskorpionen ab.}
{4568}{}{Eine Bande von Plünderern wehrt einen Ungezieferangriff ab.}
{4569}{}{Gruppe von Jägern, die einen Angriff von Gottesanbeterinnen abwehrt.}
{4570}{}{Gruppe von Jägern, die einen Angriff von Radskorpionen abwehrt.}
{4571}{}{Eine Gruppe von Jägern wehrt einen Ungezieferangriff ab.}
{4572}{}{Plünderer und Banditen teilen ihre Beute.}
{4573}{}{Wegkreuzung.}
{4574}{}{Großes Loch.}
{4575}{}{Café "New Hope".}
{4576}{}{Picknickplatz.}
{4577}{}{Haus auf Rädern.}
{4578}{}{"Furthur".}
{4579}{}{Riesenei.}
{4580}{}{Fröhlicher Bobby.}
{4581}{}{"Lieber John".}
{4582}{}{Lynchjustiz.}
{4583}{}{Filterjäger.}

# Encounter Table 32 -- VEGS_M
{4600}{}{Eine Gruppe fleischfressender Pflanzen.}
{4601}{}{Eine Gruppe Silbergeckos.}
{4602}{}{Ein Schwarm Geckos.}
{4603}{}{Eine Gruppe Goldgeckos.}
{4604}{}{Eine Gruppe Schädlinge.}
{4605}{}{Eine kleine Gruppe Maulwurfsratten.}
{4606}{}{Eine kleine Gruppe Schweineratten.}
{4607}{}{Eine kleine Gruppe Radskorpione.}
{4608}{}{Ein Wolfsrudel.}
{4609}{}{Eine Gruppe Jäger.}
{4610}{}{Gruppe von Jägern, die einen Angriff von Banditen abwehrt.}
{4611}{}{Eine Gruppe von Jägern jagt Kleintiere.}
{4612}{}{Eine Gruppe von Jägern jagt Kleintiere.}
{4613}{}{Großes Loch.}
{4614}{}{Café "New Hope".}
{4615}{}{Picknickplatz}
{4616}{}{Haus auf Rädern.}
{4617}{}{"Furthur".}
{4618}{}{Riesenei.}
{4619}{}{"Lieber John".}

# Encounter Table 33 -- VEGS_J
{4650}{}{Eine Gruppe Schädlinge.}
{4651}{}{Reifenhalde.}

# Encounter Table 34 -- SALT_Z
{4700}{}{Beängstigende Stille}

# Encounter Table 35 -- RINW_T
{4750}{}{Ein Rudel Kojoten späht die Straße aus.}
{4751}{}{Eine kleine Gruppe Radskorpione auf der Straße.}
{4752}{}{Kleine Gruppe Ungeziefer, die auf der Straße festsitzt.}
{4753}{}{Herde von brahmin, die die Straße entlangzieht.}
{4754}{}{Einheimische, die den Weg des Verbrechens gewählt haben.}
{4755}{}{Eine Gruppe Sklavenhändler mit ihren Sklaven.}
{4756}{}{Eine Gruppe Sklavenhändler versucht, einige Leute zu versklaven.}
{4757}{}{Bande von Sklavenhändlern und ein paar Hunde.}
{4758}{}{Gruppe von Banditen, die im Hinterhalt lauert.}
{4759}{}{Räuberbande, die im Hinterhalt lauert.}
{4760}{}{Plündererbande, die im Hinterhalt lauert.}
{4761}{}{Gruppe von Marodeuren, die im Hinterhalt lauert.}
{4762}{}{Eine Karawane zieht durch die Ruinen.}
{4763}{}{Wegkreuzung.}
{4764}{}{Verlassenes Büro.}
{4765}{}{Großes Loch.}
{4766}{}{Café "New Hope".}
{4767}{}{Haus auf Rädern.}
{4768}{}{"Furthur".}
{4769}{}{Anhalter.}
{4770}{}{Fröhlicher Bobby.}

# Encounter Table 36 -- South_MD
{4800}{}{Eine Gruppe fleischfressender Pflanzen.}
{4801}{}{Schwarm Gottesanbeterinnen.}
{4802}{}{Eine Gruppe Goldgeckos.}
{4803}{}{Ein Schwarm Geckos.}
{4804}{}{Eine Gruppe Schädlinge.}
{4805}{}{Eine kleine Gruppe Maulwurfsratten.}
{4806}{}{Eine kleine Gruppe Schweineratten.}
{4807}{}{Eine kleine Gruppe Radskorpione.}
{4808}{}{Eine Herde brahmin.}
{4809}{}{Ein Wolfsrudel.}
{4810}{}{Café "New Hope".}
{4811}{}{Verlassenes Büro.}
{4812}{}{Großes Loch.}
{4813}{}{Wegkreuzung.}
{4814}{}{Picknickplatz}
{4815}{}{"Furthur".}
{4816}{}{Riesenei.}
{4817}{}{Fröhlicher Bobby.}
{4818}{}{"Lieber John".}

# Encounter Table 37 -- BLCK_B
{4850}{}{Eine Gruppe Silbergeckos.}
{4851}{}{Eine Gruppe Schädlinge.}
{4852}{}{Eine kleine Gruppe Maulwurfsratten.}
{4853}{}{Eine kleine Gruppe Radskorpione.}
{4854}{}{Eine Herde wilder brahmin.}
{4855}{}{Eine Kojotenhorde.}
{4856}{}{Eine Herde brahmin wurde von Geckos angegriffen.}
{4857}{}{Haus auf Rädern.}
{4858}{}{Riesenei.}
{4859}{}{"Lieber John".}
{4860}{}{Wilde, wütende brahmin.}

# Encounter Table 38 -- HTRN_D
{4900}{}{Eine Gruppe Schädlinge.}
{4901}{}{Eine kleine Gruppe Schweineratten.}
{4902}{}{Eine kleine Gruppe Maulwurfsratten.}
{4903}{}{Eine Kojotenhorde.}
{4904}{}{Einige verzweifelte Marodeure.}
{4905}{}{Anhalter.}

# Encounter Table 39
{4950}{}{Eine Gruppe verängstigter Schädlinge.}
  
# Encounter Table 40
{5000}{}{}

# Encounter Table 41
{5050}{}{}

# Encounter Table 42
{5100}{}{}

# Encounter Table 43
{5150}{}{}

# Encounter Table 44
{5200}{}{}

# Encounter Table 45
{5250}{}{}

# Encounter Table 46
{5300}{}{}

# Encounter Table 47
{5350}{}{}

# Encounter Table 48
{5400}{}{}

# Encounter Table 49
{5450}{}{}

# Encounter Table 50
{5500}{}{}

# Encounter Table 51
{5550}{}{}

# Encounter Table 52
{5600}{}{}

# Encounter Table 53
{5650}{}{}

# Encounter Table 54
{5700}{}{}

# Encounter Table 55
{5750}{}{}

# Encounter Table 56
{5800}{}{}

# Encounter Table 57
{5850}{}{}

# Encounter Table 58
{5900}{}{}

# Encounter Table 59
{5950}{}{}

# Encounter Table 60
{6000}{}{}

# Encounter Table 61
{6050}{}{}

# Encounter Table 62
{6100}{}{}

# Encounter Table 63
{6150}{}{}

# Encounter Table 64
{6200}{}{}

# Encounter Table 65
{6250}{}{}

# Encounter Table 66
{6300}{}{}

# Encounter Table 67
{6350}{}{}

# Encounter Table 68
{6400}{}{}

# Encounter Table 69
{6450}{}{}

# Encounter Table 70
{6500}{}{}

# Encounter Table 71
{6550}{}{}

# Encounter Table 72
{6600}{}{}

# Encounter Table 73
{6650}{}{}

# Encounter Table 74
{6700}{}{}

# Encounter Table 75
{6750}{}{}